### ISSUE TITLE
[🐛 Bug]: element click is not always at the center of element on Android device Chrome Browser

### ISSUE THREAD

**Issue by normanlei0901** [webdriverio/webdriverio#10027]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.6.2

### Node.js Version

16.18.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
local simulator capability:
{
      platformName: "Android",
      "appium:deviceName": "Pixel 3",
      "appium:platformVersion": "10.0",
      "appium:automationName": "UiAutomator2",
      "appium:browserName": "Chrome",
}
browserstack capability:
{
      browserName: "chrome",
      browserVersion: "latest",
      "bstack:options": {
        ...commonCapabilities,
        realMobile: true,
        deviceName: "Google Pixel 3",
      },
}
```

### What happened?

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/112607209/226823341-9d3cb822-77db-4c30-be50-b0a25b566908.png">
tried to click on `div#renderer` element as shown above to apply a stroke on image, but it is not always hitting the center point of the image on Android mobile Chrome bowser. 

### What is your expected behavior?

hitting the center

### How to reproduce the bug.

because the page is not in production yet. can't reproduce it here. Could you provide any potential issue here or solution that I can try on? thanks 

### Relevant log output

```typescript
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by normanlei0901** [comment]
below are examples of the offsets. Basically the cat image is the element `div#renderer` shown above and I call ele.click(), it hit the center as expected in desktop mode but not in mobile mode. The only difference is the control panel position, desktop mode is on the left and mobile mode is at the bottom. The element `div#renderer` shouldn't be affected. Any thought? thanks

desktop mode:
<img width="330" alt="image" src="https://user-images.githubusercontent.com/112607209/226967389-f5c9f8a2-c519-4659-b2a5-1ea2ad6d6c1c.png">

mobile mode:
<img width="313" alt="image" src="https://user-images.githubusercontent.com/112607209/226967553-17315fef-e510-41e3-8b1c-21152663d9b6.png">

**Comment by christian-bromann** [comment]
> Any thought?

Yeah, this looks like a driver issue. WebdriverIO receives the wrong values from the driver. We could try to do some interpolation and adjust these results but this seems like very difficult to maintain and it should be ideally be fixed by the driver. I [filled an issue](https://github.com/w3c/webdriver/issues/1729) in the spec repo and we should follow the development there.

**Comment by christian-bromann** [comment]
@normanlei0901 does this issue appears in Chrome or also in other browser like Firefox?

**Comment by normanlei0901** [comment]
> @normanlei0901 does this issue appears in Chrome or also in other browser like Firefox?

I haven't been able to run in on Android Firefox yet, but I will try best to see if I can run automation on it, the issue was determined on Chrome for now.

One more issue here, I just ran automation on a real Samsung Tab A8 device, and the `image.click()` turned out different in portrait mode and landscape mode as well. It can hit the center in `portrait` mode but not in `landscape` mode fyi
