### ISSUE TITLE
Special tags

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1002]
What do you think about special tags?

[![Chimp tags][2]][1]

  [1]: https://vimeo.com/151186833#t=95s
  [2]: https://cloud.githubusercontent.com/assets/803674/12210282/d8e555c6-b669-11e5-9f99-20ada1791b81.jpg (Chimp tags)

I like idea

```js
yield browser.tag('watch'); // watch these suite
yield browser.tag('ignore'); // ignore these suite

```

**Comment by christian-bromann** [comment]
Sounds good, I am open for anything like this. Could you please file an issue with your proposal in the official [cucumber framework adaptor project](https://github.com/webdriverio/wdio-cucumber-framework) so we can specify all requirements there. Thanks!

**Comment by monolithed** [comment]
How it will work without `cucumber`?)

**Comment by christian-bromann** [comment]
> Why not provide something like browser.tag as well?

In what context? Do you have an example?

**Comment by monolithed** [comment]
```js
it('....', function *() {
	yield browser
		.url('/unknown_method')

	yield browser.tag('watch');
});
```

preprocessor? (

**Comment by monolithed** [comment]
I don't know how it can be implemented without preprocessor...

**Comment by monolithed** [comment]
Ultimately, can be implemented via decorators!

**Comment by christian-bromann** [comment]
right...for mocha and jasmine it can be something like this:

```js
it('should test something @watch', function() {....
```

and in Cucumber it should also live in feature files. All that stuff has to be implemented within the framework adapters not here in webdriverio

**Comment by monolithed** [comment]
What do you think about another config section like `preprocessors`?
http://karma-runner.github.io/0.13/config/preprocessors.html

**Comment by christian-bromann** [comment]
Should be also part of the framework adapter and many already have preprocessor as option

**Comment by monolithed** [comment]
@christian-bromann, I found a good solution :smile:

**[Mocha](http://mochajs.org/#exclusive-tests)**

```js
describe.only('All nested suites will still be executed', function() {
    // ...
});

it.only('Execute a particular test case', function() {
    // ...
});
```

**[Jasmine](http://jasmine.github.io/2.2/focused_specs.html)**

```js
fdescribe('All nested suites will still be executed', function() {
    // ...
});

fit('Execute a particular test case', function() {
    // ...
});
```

**[Cucumber](https://github.com/cucumber/cucumber/wiki/Tags#special-tags)**

```yml
@only
Feature: All nested scenarios will still be executed

@only
Scenario: Execute a particular test scenario

cucumber --tags @only
```
