### ISSUE TITLE
[💡 Feature]: Allow to access custom parameters from config file earlier can achieve using browser.config['key_']

### ISSUE THREAD

**Issue by nikhilgupta1789** [webdriverio/webdriverio#10031]
### Is your feature request related to a problem?

It is difficult to fetch added parameters from config file earlier it was an easy to fetch key value pairs from wdio.config file using browser.config['customer_user'], browser.config['customer_password'], browser.config['prod_user'], browser.config['prod_password'], now after upgrading to webdriverio version 8, browser.config has been replaced with browser.options but after doing the same thing with options like browser.options['customer_user'] it returnes undefined.

### Describe the solution you'd like.

Can we add the feature again using browser.options to fetch custom added parameters in wdio.config file.

`exports.config = {
    
	//custom variables
    customer_user : "automation_user",
	customer_password : "test_123"
				

    autoCompileOpts: {
        autoCompile: true,
        tsNodeOpts: {
            transpileOnly: true,
            project: 'tsconfig.json'
        }
    },
    
    specs: [ './src/specs/access-custom-params.spec.ts' ],
    maxInstances: 1,
    capabilities: [{
        maxInstances: 1,
        browserName: 'chrome',
        acceptInsecureCerts: true,
        'goog:chromeOptions': {
            args: [
                '--no-sandbox',
                '--disable-infobars',
                //'--headless',
                '--disable-gpu',
                '--window-size=1366,768',
            ],
            prefs: {
                'prompt_for_download': false,
                'download.default_directory': downloadDir,
                "credentials_enable_service": false,
            },
            'excludeSwitches': ['enable-automation'],
        },
    }],
    
    logLevel: 'debug',
    logLevels: {
        webdriver: 'error',
        '@wdio/utils': 'silent'
    },
    bail: 0,
    baseUrl: 'https://aremerald-t03.nhin.com/emerald/login',
    waitforTimeout: 60000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 0,
    services: ['chromedriver', [TimelineService]],
    framework: 'mocha',
    reporters: [
        ['spec',
            {
                symbols: {
                    passed: '[PASS]',
                    failed: '[FAIL]',
                },
                addConsoleLogs: true,
                realtimeReporting: true,
            }
        ]
    ],
    mochaOpts: {
        ui: 'bdd',
        timeout: 90000
    },
    
    onPrepare: function (config, capabilities) {
    },
}
`

### Describe alternatives you've considered.

Better if you provide someway to access the custom added parameters from wdio config file using browser.options['customer_user'] using syntax like **browser.options['key']** as what we're using before like browser.config['key']

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
It is not recommended to mix WebdriverIO configurations with custom properties. I recommend store the data in an external file and import it in your test.

**Comment by nikhilgupta1789** [comment]
@christian-bromann but question remains same how dynamically I will replace the username, password on the fly running from CI/CD in case if I place key:value pair in some external file. We have been placing all customer users and their passwords in the config file and replacing it from command prompt --params.key=value, but now since it has changed and config not available.

Moreover we are not checkin users and passwords keyt value pair in github due to HIPPA security policy.
@christian-bromann  may you have any solution how we can acehive this? or you may provide just one custom optioj in the config file to access in test script and can be replaced from command prompt same as we're doing it in version 7.

We have many test case depends on this concept. We are blocked now sonce we upgraded it to the latest version 8. 
Please help!!

**Comment by christian-bromann** [comment]
You can e.g. use the shared store service to access any kind of data in your tests. You can use the `onPrepare` hook to set the data before the test starts or a custom service that would do that for you.

**Comment by nikhilgupta1789** [comment]
@christian-bromann I tried with your approach using dotenv concept problem with that is it is not allowing to override the values defined in .env file, I couldn't understand if the feature was there in verion 7 now you have deprecated that feature so there should be some alternative given in latest new release version 8, because many of the projects were using that concept. If I checked with options which is a replacement for config, no such feature available. I don't know how others are managing with their user/passwords and other key values in their project. Ideally we can't check-in users/passwords in the git repository we're passing users/passwords from the command line at runtime.

If that feature has removed there should be some alternative for it or any example should be posted on webdriverio website, after using webdriverio coming from long way we have to think on different tool if core feature is going to be miss.

Kindly please provide any real time example of overriding key-value pairs and also can be used in the script.

**Comment by christian-bromann** [comment]
> If that feature has removed there should be some alternative for it or any example should be posted on webdriverio website

This was not a feature, it was no where documented that you should do this. Therefore there is no need to provide an alternative. As I mentioned above there are so many other ways you can consume or propagate custom variables into your test. As mentioned above you can use the `onPrepare` hook to store any kind of data into e.g. the [shared store service](https://webdriver.io/docs/shared-store-service).
