### ISSUE TITLE
Show HTTP redirects

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1003]
```js
yield browser
	.open('/user/login')
	.submitForm('[data-name="submit"]')
	.waitUntil(() => {
		return browser
			.getUrl().then(url => {
				console.log(url); // only the last url
			})
			//.should.be.eventually.match(url);
	}, 5000);
```

There'a several HTTP-redirects (301-302) after `submitForm`, but I see only the last of them.
My question is how to preserve requests to other resources?
Any ideas?

**Comment by christian-bromann** [comment]
I don't think this is possible with Selenium .. sorry

**Comment by monolithed** [comment]
The latest version of Selenium Webdriver does not really support traffic
capture. But, I found some examples how it can be possible with Java:

1. [Java .net package ....](https://github.com/AutomatedTester/AutomatedTester.PagePerf)
2. [BrowserMobProxy](https://github.com/lightbody/browsermob-proxy)

```java
BrowserMobProxy server = new BrowserMobProxyServer();
server.start(0);

Proxy proxy = ClientUtil.createSeleniumProxy(proxy);

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(CapabilityType.PROXY, proxy);

WebDriver driver = new FirefoxDriver(capabilities);
server.newHar("google.com");
driver.get("http://google.com");

Har har = server.getHar();

File file = new File("har.json");
har.writeTo(file);

server.stop();
driver.quit();
```

3. Firefox + Firebug

```
ProxyServer server = new ProxyServer(8107);

server.start(0);
server.setCaptureHeaders(true);
server.setCaptureContent(true);

Proxy proxy = ClientUtil.createSeleniumProxy(proxy);

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(CapabilityType.PROXY, proxy);

WebDriver driver = new FirefoxDriver(capabilities);
driver.get("http://www.google.com");

server.newHar("gooogle");

Har har = server.getHar();
File file = new File("har.json");
har.writeTo(file);

server.stop();
driver.quit();
```

*HAR file is json based file, refer HAR specification for more. It can be transformed to image*

4. [Firefox + Firebug + NetExport plugin](https://eveningsamurai.wordpress.com/2013/06/29/capturing-network-traffic-using-selenium-webdriverfirebug/)

```java
...
File netExport = new File(System.getProperty("user.dir"));
profile.addExtension(netExport);
...

5. [Firefox + Firebug + NetExport plugin](https://eveningsamurai.wordpress.com/2013/06/29/capturing-network-traffic-using-selenium-webdriverfirebug/)

```java
Proxy proxy = new Proxy();
proxy.setHttpProxy("localhost:9100");
DesiredCapabilities capabilities = DesiredCapabilities.firefox();
capabilities.setCapability(CapabilityType.PROXY, proxy);
```

6. [CaptureNetworkTraffic](http://blog.eviltester.com/2010/05/a-selenium-capturenetworktraffic-example-in-java.html)

7. [ProxyLight](http://www.supermind.org/blog/968/howto-collect-webdriver-http-request-and-response-headers)

8. [Selenium Requests](https://github.com/cryzed/Selenium-Requests)

9. [WebDriverBackedSelenium](https://selenium.googlecode.com/svn/trunk/docs/api/java/org/openqa/selenium/WebDriverBackedSelenium.html)?

And very interesting idea with Profiling [1](https://code.google.com/p/selenium-profiler/), [2](http://www.theautomatedtester.co.uk/blog/2010/selenium-webtimings-api.html)

**Comment by christian-bromann** [comment]
I wanted to dig into that topic of network analysis in Selenium but didn't get a chance to do so. I already created that repo here though: https://github.com/webdriverio/proxo

**Comment by monolithed** [comment]
@christian-bromann, Have you seen [Selenium Requests](https://github.com/cryzed/Selenium-Requests)?

**Comment by christian-bromann** [comment]
Looks interesting.

**Comment by intergleam** [comment]
in c# it is possible by looping through logs, if message.params.redirectResponse.url is equal to original URL then message.params.request.url will contain redirect URL. Have a look at [the SO answer](https://stackoverflow.com/questions/35592602/how-can-i-get-a-intermediate-url-from-a-redirect-chain-from-selenium-using-pytho/42212131#42212131)

I wonder would it be possible with `webdriverio`?

**Comment by christian-bromann** [comment]
@intergleam yeah that should be no problem with WebdriverIO

**Comment by intergleam** [comment]
don't see [LoggingPreferences](https://sites.google.com/a/chromium.org/chromedriver/logging/performance-log) in [docs](http://webdriver.io/guide/getstarted/configuration.html) though

**Comment by christian-bromann** [comment]
@intergleam this is something you need to set in your desired capabilities. These are options for Chrome.

**Comment by monolithed** [comment]
Артур Удалов (30.03.2017 16:07):
capabilities: utils.capabilities([
  {
   browserName: 'chrome',
   loggingPrefs: {
    'browser':     'ALL',
    'driver':      'ALL',
    'performance': 'ALL'
   }
  }
 ]),

Артур Удалов (30.03.2017 16:07):
browser.log('performance');

**Comment by intergleam** [comment]
Thanks! 
`browser.log ` indeed writes something but it shortens the output `... (740254 more bytes)` where I guess all the info is. Can I make it write full output?

**Comment by christian-bromann** [comment]
`browser.log()` returns a result and you can do whatever you want with it 😉

**Comment by christian-bromann** [comment]
I guess nodejs shortens the output

**Comment by monolithed** [comment]
Sure, use a memory storage instead of your terminal to view all the requests 😉

**Comment by intergleam** [comment]
ok got it :)
