### ISSUE TITLE
[🐛 Bug]: <title>The locator "someTag"="SomeTxt" is not working since @wdio/local-runner version 8.6.2 (last working version)

### ISSUE THREAD

**Issue by alek75** [webdriverio/webdriverio#10067]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.6.8

### Node.js Version

16.14.0

### Mode

Standalone Mode

### What happened?

Example "div=SomeTxt" or "div*=someTxt" are not working after wdio/local-runner version 8.6.2 (last working version). 
This is applicable to all tags >>> h1, a, span etc.

The other packages I am using are: "@wdio/cli": "8.6.8", "@wdio/cucumber-framework": "8.6.8", "@wdio/spec-reporter": "8.6.8", "@wdio/local-runner": "8.6.2", "wdio-chromedriver-service": "8.1.1", "wdio-intercept-service": "4.4.0",

As you can see the only downgraded package is "@wdio/local-runner". If I can help you with some other info, please let me know...

### How to reproduce the bug.

Just use the locator div=someTxt
You can use it with any tags, not only with div...

wdio/local-runner version 8.6.2 (last working version)

### Relevant log output

```typescript
Error: element ("a*=Test Queue 4") still not existing after 15000ms
[chrome 111.0.5563.111 windows #0-0] Error: element ("a*=Test Queue 4") still not existing after 15000ms
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by alek75** [comment]
@christian-bromann Since you closed the ticket "as completed" I've expected the issue to be fixed in the newer version... but i guess that's not the case > the issue still persist in "8.6.9"

**Comment by christian-bromann** [comment]
Based on your description my assumption was that the issue described in #10040 is the same as described in here. If that is not the case please provide a reproducible example, thank you!

**Comment by alek75** [comment]
@christian-bromann I've checked #10040. 
Indeed "h1=someTxt" is fixed, but did you check searching by partial txt? > "h1*=someTxt"

Thanks

**Comment by alek75** [comment]
Will see what i can do...

Cheers

**Comment by gjvoosten** [comment]
Hi @christian-bromann! Seeing as this is still part of a patch release (not minor or even major), and the behaviour has changed, many people might be surprised why their tests suddenly started failing with this new webdriverio version. So the safest bet would be to make it behave the same as before. Now if the former behaviour was ill-defined or under-documented, it's okay to change it, but be sure to mark this clearly in the release notes / changelog, as we don't want to make people search for relevant issues to find out what happened (and/or how to fix it).

**Comment by gjvoosten** [comment]
@christian-bromann In any case, aside from documenting which exact element gets matched, the main problem is of course that currently the test I described above doesn't find the element _at all_, so that still needs to be fixed.
(And maybe this issue should be reopened until it is?)

**Comment by christian-bromann** [comment]
Raised another PR with fixes for this.

**Comment by alek75** [comment]
version 8.7.0

HTML example:
<div>
     <span>Test me</span>
</div>


wdio code example:
browser.$("span=Test me") = working
browser.$("div=Test me") = working
browser.$("span*=Test") = working
browser.$("div*=Test") = NOT working

Is this ok as an example @christian-bromann ?

**Comment by alek75** [comment]
wdio - 8.7.0

HTML example:

```
<div>
    <span>Test me</span>
</div>
```

wdio example:
browser.$('span=Test me') - working
browser.$('div=Test me') - working
browser.$('span*=Test') - working
browser.$('div*=Test') - NOT working

@christian-bromann Is this example reproducible?
Thanks...

**Comment by christian-bromann** [comment]
The PR mentioned above is not released yet.
