### ISSUE TITLE
Something like "wait" option to limit number of custom commands

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1007]
In my typical single-page application I don't like to use `waitForExist` everywhere.
And I think we should discuss what we can do.

### Classic way

```js
let button = '.button';

yield browser
	.url('/user')
	.waitForExist(button)
	.click(button);
        ...
```

### Alternative way

```js
yield browser
	.url('/user')
	.tap('.button');
        ...
```

```js
browser.addCommand('tap', function (selector) {
	return this.waitForExist(...arguments).click(selector);
});
```

Or it can be a wrapper around `url` like:

```js
yield browser
	.open('/user')
	.click('.button');
        ...
```

```js
browser.addCommand('open', function (url, ...options) {
	return this.url(url).waitForExist('.MY_GLOBAL_INDICATOR', ...options);
});
```

I think it would be a useful feature, but I don't know to implement it. 
There'a a couple of questions:
— How to configure?
— How to implement?
— What about performance?

Config?

```js
{
    wait () {
            return this.waitForExist('.foo');
    }
}
```

I don't think so, because of context

And what if...

```js
{
    wait: '.MY_GLOBAL_INDICATOR'
}
```

Hm, don't know (

Any ideas?

**Comment by christian-bromann** [comment]
Usually you don't need to call wait after the url command because Selenium checks if the page has loaded or not (depending on the pageLoadStrategy). However if you use Angular this might not always work. This stuff highly depends on the app you are working on and I am not sure if there is a pattern that would work for all people.

**Comment by monolithed** [comment]
> Usually you don't need to call wait after the url command because Selenium checks if the page has loaded or not (depending on the pageLoadStrategy)
Yup, `pageLoadStrategy` is working only for already created HTML but not for dynamic DOM elements. 


My ~~crazy~~ proposal:

```js
{
   waitFor: {
       url (selector) {
            return '.MY_GLOBAL_INDICATOR';
       },
       
      click (selector) {
           return selector;
      }
   }
}
```

Equivalents are:

```js
browser.addCommand('open', function (url, ...options) {
    return this.url(url).waitForExist('.MY_GLOBAL_INDICATOR', ...options);
});

browser.addCommand('tap', function (selector) {
    return this.waitForExist(...arguments).click(selector);
});
```

**Comment by christian-bromann** [comment]
I think this can be extracted into a service that uses the beforeCommand hook to wait for a certain element. I am not sure if this should be part of the main package.

**Comment by xbill82** [comment]
Note for Angular users: you have the [webdriverjs-angular](https://github.com/webdriverio/webdriverjs-angular) plugin that automagically adds waiting routines to some WebdriverIO methods so that you don't have to wait for Angular to finish the rendering.

**Comment by christian-bromann** [comment]
> Note for Angular users: you have the webdriverjs-angular

This plugin is not maintained anymore and requires to run an old version of WebdriverIO. We will work on a new plugin that enables this functionality for the new version

**Comment by christian-bromann** [comment]
As [mentioned above](https://github.com/webdriverio/webdriverio/issues/1007#issuecomment-175306132) this could be an excellent service for WebdriverIO. We are planning to write an angular service that provides all the neat features protractor has. Closing
