### ISSUE TITLE
[🐛 Bug]: All `it` blocks are considered test functions of single `spec` file when running specs on the same browser instance

### ISSUE THREAD

**Issue by mayankshukla94** [webdriverio/webdriverio#10083]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

"@wdio/cli": "^7.25.2",

### Node.js Version

v16.18.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
maxInstances: 3,
      //
      browserName: 'chrome',
      acceptInsecureCerts: true,
      // If outputDir is provided WebdriverIO can capture driver session logs
      // it is possible to configure which logTypes to include/exclude.
      // excludeDriverLogs: ['*'], // pass '*' to exclude all driver session logs
      // excludeDriverLogs: ['bugreport', 'server'],
      'goog:chromeOptions': {
        args: BROWSER_OPTIONS ? [BROWSER_OPTIONS, 'window-size=1382, 744'] : undefined,
      },
```

### What happened?

When trying to run multiple `spec` files in the same browser instance, then only those specs are executed that contain `it.only` blocks. Other specs where all test blocks are expected to run are skipped.

Let's say, there are 3 spec files:

a. abc.spec.js

```js
describe('Abc spec', ()=>{
    it.only('spec 1', async()=>{
         
    });

   it('spec 2', async()=>{
         
    });
});
```

b. pqr.spec.js

```js
describe('Pqr spec', ()=>{
    it.only('spec 1', async()=>{
         
    });

   it('spec 2', async()=>{
         
    });
});
```

c. xyz.spec.js

```js
describe('Xyz spec', ()=>{
    it('spec 1', async()=>{
         
    });

   it('spec 2', async()=>{
         
    });
});
```

If we run above specs in same instance, i.e. 
```js
suites: {
   end2end: [
      ['abc.spec.js', 'pqr.spec.js', 'xyz.spec.js']
   ]
}
```

This will only execute `it` blocks of `abc.spec.js` and `pqr.spec.js` i.e. `spec 1` test functions of `abc.spec.js` and `pqr.spec.js`. It will skip `xyz.spec.js` completely.

### What is your expected behavior?

It should execute `it` blocks of `abc.spec.js` and `pqr.spec.js` i.e. `spec 1` test functions of `abc.spec.js` and `pqr.spec.js`. And all `it` blocks of `xyz.spec.js`

### How to reproduce the bug.

To reproduce a bug, create 3 spec files and use `only` for `it` blocks for 2 of the spec files. In `wdio.conf.js`, under `suites` pass all 3 spec files in an array:

```js
suites: {
   end2end: [
      ['abc.spec.js', 'pqr.spec.js', 'xyz.spec.js']
   ]
}
```

run command: `npx wdio --suite end2end`

### Relevant log output

```typescript
[chrome 111.0.5563.112 windows #0-0] Running: chrome (v111.0.5563.112) on windows
[chrome 111.0.5563.112 windows #0-0] Session ID: 72befcd08ebab147c6333285fcccce10
[chrome 111.0.5563.112 windows #0-0]
[chrome 111.0.5563.112 windows #0-0] » \test\specs\abc.spec.js
[chrome 111.0.5563.112 windows #0-0] Abc spec
[chrome 111.0.5563.112 windows #0-0]    ✓ spec 1 
[chrome 111.0.5563.112 windows #0-0]
[chrome 111.0.5563.112 windows #0-0]
[chrome 111.0.5563.112 windows #0-0] » \test\specs\pqr.spec.js
[chrome 111.0.5563.112 windows #0-0] Pqr spec
[chrome 111.0.5563.112 windows #0-0]    ✓ spec 1  
[chrome 111.0.5563.112 windows #0-0]
[chrome 111.0.5563.112 windows #0-0] 2 passing (3m 37.3s)

Spec Files:      1 passed, 1 total (100% completed) in 00:03:45
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> This will only execute `it` blocks of `abc.spec.js` and `pqr.spec.js` i.e. `spec 1` test functions of `abc.spec.js` and `pqr.spec.js`. It will skip `xyz.spec.js` completely.

This is the expected behavior. If you have `it.only` set, it will only run these it blocks. This is how Mocha works. You can include `xyz.spec.js` by running it in a separate session.
