### ISSUE TITLE
[📖 Website]: Use typescript.

### ISSUE THREAD

**Issue by AugustinMauroy** [webdriverio/webdriverio#10117]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Other

### Description of the improvement / report

Use typescript for the website.
Ref: https://docusaurus.io/docs/typescript-support

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Thanks for reporting!

Totally agree, we should have our website files in TypeScript as well.

Any contributions that resolves the issue are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by AugustinMauroy** [comment]
> Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute)

Ho waw that an complet contribution guideline
I'm looking at this 😄.

**Comment by AugustinMauroy** [comment]
I'm in an exam period. I'll keep it on my to-do list.

**Comment by christian-bromann** [comment]
Awesome, good luck with your exams!

**Comment by AnthonyQuy** [comment]
@christian-bromann  I created a PR for this, can you have a look
https://github.com/webdriverio/webdriverio/pull/11249

**Comment by AnthonyQuy** [comment]
Pulled latest code and fix commit check fail via another PR  #11259

**Comment by AnthonyQuy** [comment]
@christian-bromann I think we should close this

**Comment by christian-bromann** [comment]
We can, thanks again!
