### ISSUE TITLE
[🐛 Bug]: Specs are running in reverse alphabetical order

### ISSUE THREAD

**Issue by shubham0803** [webdriverio/webdriverio#10125]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

18.15.0

### Mode

Standalone Mode

### What happened?

In this file - `node_modules/@wdio/config/build/lib/ConfigParser.js` the implementation of fetching the spec files from a suite is written in such a way that **suiteSpecs** array will store the spec files in reverser order so thats the reason the specs are running in reverse order when you run a complete suite
this method -  `getSpecs(capSpecs, capExclude)` does that

Here, we have 2 scenarios -

**Scenario 1 - Regular expression for spec files**
`regression: ['demos/honeycomb/native/e2e-test/specs/**.spec.ts'],`

In this case specs will execute in reverse order (reason mentioned above)

**Scenario 2 - Multiple Spec File Paths specified in a suite**
    `
button: [
      'demos/honeycomb/native/e2e-test/specs/Button-Component-Test.spec.ts',
      'demos/honeycomb/native/e2e-test/specs/Dialog-Modal-Component-Test.spec.ts',
      'demos/honeycomb/native/e2e-test/specs/IconButton-Component-Test.spec.ts',
      'demos/honeycomb/native/e2e-test/specs/RadioGroup-Component-Test.spec.ts',
    ],
`

In this case specs will execute in the same order how we have specified in the above suite

For Scenario 1, this is the difference in execution order now -
**wdio v8**
Suite Specs -
file:///Users/shubham/Documents/GitHub/core-ui/demos/honeycomb/native/e2e-test/demo/TextInput-Component-Test.spec.ts,
file:///Users/shubham/Documents/GitHub/core-ui/demos/honeycomb/native/e2e-test/demo/ProgressBar-Component-Test.spec.ts,
file:///Users/shubham/Documents/GitHub/core-ui/demos/honeycomb/native/e2e-test/demo/Divider-Component-Test.spec.ts,
file:///Users/shubham/Documents/GitHub/core-ui/demos/honeycomb/native/e2e-test/demo/Accordion-Component-Test.spec.ts

**wdio v7**
Suite Specs -
/Users/shubham/Documents/GitHub/core-ui/demos/honeycomb/native/e2e-test/demo/Accordion-Component-Test.spec.ts,
/Users/shubham/Documents/GitHub/core-ui/demos/honeycomb/native/e2e-test/demo/Divider-Component-Test.spec.ts,
/Users/shubham/Documents/GitHub/core-ui/demos/honeycomb/native/e2e-test/demo/ProgressBar-Component-Test.spec.ts,
/Users/shubham/Documents/GitHub/core-ui/demos/honeycomb/native/e2e-test/demo/TextInput-Component-Test.spec.ts

### What is your expected behavior?

Spec files should execute in alphabetical order in wdio v8 like how it used to work in wdio v7

### How to reproduce the bug.

Execute any suite of your webdriverio repo using `--suite` and you will observe that spec files will run in reverse alphabetical order

### Relevant log output

```typescript
Order of spec files execution will be in reverse alphabetical order
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

There was no intentional change in WebdriverIO to change the order of spec file, so I assume it is a transient change from the `glob` dependency, can't say that for sure though. It makes sense to fix this to recreate the same behavior as v7.

Any contributions that resolves the bug are highly appreciated. Don't expect this to be picked up by active contributors as they have their own priorities. If you depend on this bug to be fixed, your contribution is required. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by hdesai-dave** [comment]
@christian-bromann having a proper boilerplate repo would have been very useful https://github.com/amiya-pattnaik/webdriverIO-with-mochaBDD for e.g. doesn't have yarn.lock commited to compare resolutions. I was following your repo, but that has not been upgraded. Will look into contributing guidelines and prioritize this if it is straightforward. Wouldn't it be easier for the original author though to help out with such an issue?

**Comment by dilpreetj** [comment]
I noticed this behaviour as well. Will have a PR out for it shortly.
