### ISSUE TITLE
[🐛 Bug]: Executing config from inner folder no longer working since v8

### ISSUE THREAD

**Issue by DIFSRIP** [webdriverio/webdriverio#10127]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.7.0

### Node.js Version

19.0.1

### Mode

WDIO Testrunner

### What happened?

Formerly in v7 we could execute a config from a inner folder calling it like `npx wdio ../myFolder/test.conf.js`.
Since migration to v8 I receive the error:

```bash
? Could not execute "run" due to missing configuration, file "test[.js/.ts]" not found! Would you like to
 create one? (y/N) 
```

Going inside a folder like `npx wdio myFolder/test.conf.js` or calling the config from the same folder is working fine.

I tested resolving the path before calling wdio command in our cli tool, but without success.

### What is your expected behavior?

Expected behaviour is to be able to execute from any location using relative or absolute paths.

Any support is welcome!

### How to reproduce the bug.

- To reproduce the bug, init a new project using `npm init wdio` and select mocha as framework.
- Let the command create the sample spec.
- Navigate into to the `test` folder.
- Execute command `npx wdio ../wdio.conf.js`.

### Relevant log output

```typescript
? Could not execute "run" due to missing configuration, file "test[.js/.ts]" not found! Would you like to
 create one? (y/N)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by praveendvd** [comment]
`npx wdio run ..\wdio.conf.js`

**Comment by praveendvd** [comment]
this works , i will take this up

**Comment by praveendvd** [comment]
@christian-bromann  that was fast , @DIFSRIP fixed it please check with the fix , thanks

**Comment by DIFSRIP** [comment]
> @christian-bromann that was fast , @DIFSRIP fixed it please check with the fix , thanks

Thanks a lot @praveendvd and @christian-bromann 

Work now perfectly fine!
