### ISSUE TITLE
[📖 Docs]: wdio config eslint-plugin-jsdoc flagged items

### ISSUE THREAD

**Issue by anselmbradford** [webdriverio/webdriverio#10133]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Other

### Description of the improvement / report

The `eslint-plugin-jsdoc` plugin flags several things in https://github.com/webdriverio/webdriverio/blob/main/examples/wdio.conf.js, specifically:

https://github.com/webdriverio/webdriverio/blob/main/examples/wdio.conf.js#L321-L324

- `The type 'Any' is undefined`. It should be `*`.
- `Number`, `Boolean`, and `Object` should be down-cased.

Additionally, in https://github.com/webdriverio/webdriverio/blob/main/examples/wdio.conf.js#L239-L242

- `Syntax error in type: [type]`. 

However, I know these are just example code comments, so I'm not sure if there's a better way to format that, or if they should be ignored by eslint.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
> The `eslint-plugin-jsdoc` plugin flags several things in

This project doesn't use the plugin so I am not sure why these error pop up for you.

**Comment by anselmbradford** [comment]
> This project doesn't use the plugin so I am not sure why these error pop up for you.

It will pop up in any project that uses wdio and does use eslint with the latest jsdocs plugin. There's probably nothing to be done about the jsdocs that are examples that should be adjusted when implemented, but the `Any` type should be `*` according to https://jsdoc.app/tags-param.html#multiple-types-and-repeatable-parameters, and the jsdocs in the example config are inconsistent in their casing. Very minor, but it is flagged as a warning.

**Comment by christian-bromann** [comment]
> It will pop up in any project that uses wdio and does use eslint with the latest jsdocs plugin.

This means these errors pop up in the `wdio.conf.js` of the user project?

**Comment by anselmbradford** [comment]
> This means these errors pop up in the wdio.conf.js of the user project?

Technically they are warnings, but yes, this is correct.

The user could edit the wdio.conf.js or their eslint config to ignore this file, but it would probably be better if the jsdocs were correct in wdio.conf.js. 

> would you like to raise a PR with fixes to these examples?

Would you want to add https://www.npmjs.com/package/eslint-plugin-jsdoc to the project or only fix the noted issues directly?

**Comment by christian-bromann** [comment]
> or only fix the noted issues directly?

Let's fix the issues only
