### ISSUE TITLE
Support for multiple selections which contain text?

### ISSUE THREAD

**Issue by grofit** [webdriverio/webdriverio#1014]
This started as a brief discussion on gitter:

`grofit 10:03`
I want to be able to select a "button" (and I use this term loosly not in the context of a html button element) on a page via its text
now this could be `a=some text` or `button=some text`
so is there a way to basically collate selectors in an or fashion, I have tried most logical permutations `a=some text, button=some text` or `a='some text', button='some text'` and many more etc
so does anyone know off top of their heads the correct way to do an or selector for textual matches?
crisis averted
just gone with xpath for now, although would be interested in how to do it via non xpath selectors (as I assume xpath for any element with a text match will be slow on larger pages)

`christian-bromann 13:27`
@grofit agree, this sounds like an interesting enhancement, would you be so kind and create an issue?

**Comment by vrundbaken** [comment]
This is a function a co-worker wrote that may do what you want. You can give it a selector and inner text to search for and it will return the JSON wire ID of an element that matches. It has not been tested very much yet, and there are definitely some cases that will break it and there is no error handling but it's worked well for our needs so far. 

You can use a comma to combine selectors so your selector could be 'a, button'

```javascript
/**
	 * Returns JSON-Wire ID of matching element based on inner text or index
	 * @param  {string} 			  selector   Selector to search within
	 * @param  {string|number} 		  target     Text or index of element to search for
	 * @return {promise}          	 
	 */
	getElementIdBy: function getElementIdBy(selector, target) {
		return client.elements(selector).then(function(elms) {

			var elementText = [];

			//If index is given, click that index in returned elements
			if (typeof target === 'number') {
				return elms.value[target].ELEMENT;

			//If string is given, click element that holds that string
			} else if (typeof target === 'string') {

				//Grabbing text of all matched elements
				for (var i = 0; i < elms.value.length; i++) {
					elementText.push(client.elementIdText(elms.value[i].ELEMENT));
				}

				//When all promises resolve, find the one which one holds matching text
				return Q.all(elementText).then(function() {
					for (var i = 0; i < elms.value.length; i++) {
						if (elementText[i].value === target) {
							return elms.value[i].ELEMENT;
						}
					}
				});
			}


		});
	}
```

**Comment by christian-bromann** [comment]
This has been hanging around for a while so I will close it. With v5 we don't do this kind of element selection anyway. If you want to interact with an element you need to fetch it and do something with it. There will be no
```js
const elems = $$('a=some text, button=some text or a='some text', button='some text')
elems.click()
```
you will need to do:
```
const elems = [
    $("a=some text"),
    $("button=some text"),
    $("a='some text'"),
    $("button='some text'")
]
elems.forEach((elem) => elem.click())
```
