### ISSUE TITLE
How to do a Basic Auth

### ISSUE THREAD

**Issue by vincentsaluzzo** [webdriverio/webdriverio#1015]
We need to execute some tests on internal staging site before publish the production site.

The staging are protected by a basic authentication but we haven't found a solution to do a Basic Auth in your documentation.

Any help or documentation ?

**Comment by christian-bromann** [comment]
@vincentsaluzzo open the url like:
`username:password@mysite.com`

**Comment by vincentsaluzzo** [comment]
Quick response but not working ! I've something like this in our test case:
```
browser.url('http://<username>:<password>@outsite.com') 
```

But that's work ONLY for Chrome not for Firefox or Safari (i'm on OS X)

**Comment by christian-bromann** [comment]
mhm .. well this is the only way to get around basic auth I am aware of. Maybe there is a different approach on the internet I don't know. Selenium can't just input name and password in these auth fields.

**Comment by kimek** [comment]
Refer to https://github.com/webdriverio/webdriverio/issues/837
