### ISSUE TITLE
Webdriver.io with axe-core giving error [ new AxeBuilder({ client: browser }) ] "Type 'Browser' is not assignable to type 'WdioBrowser'.

### ISSUE THREAD

**Issue by singhMo007** [webdriverio/webdriverio#10166]
```
import { browser } from '@wdio/globals'
import AxeBuilder from '@axe-core/webdriverio'

describe('Accessibility Test', () => {
    it('should get the accessibility results from a page', async () => {
        const builder = new AxeBuilder({ client: browser })

        await browser.url('https://testingbot.com')
        const result = await builder.analyze()
        console.log('Acessibility Results:', result)
    })
})
```

**Comment by praveendvd** [comment]
could you try browser as Browser , and try ? also please add a reproducible project . zip or link to repo

**Comment by singhMo007** [comment]
Thanks, I tried this but no luck on this.
Please find the link to repo: https://github.com/singhMo007/wdio-accessibilityTest

**Comment by christian-bromann** [comment]
It seems that support for v8 is currently not great, see https://github.com/dequelabs/axe-core-npm/issues/705. There is nothing we can do about this here in this project. I recommend to give that issue a 👍  to let them know you are interested in this as well.

**Comment by singhMo007** [comment]
Thanks, and any idea or plan to take this fix in coming future?
