### ISSUE TITLE
[💡 Feature]: Jest Framework Runner

### ISSUE THREAD

**Issue by sidferreira** [webdriverio/webdriverio#10177]
### Is your feature request related to a problem?

Although Jasmine and Jest are really similar, Jest has a larger adoption and extra tools, including tools for visual regression.

### Describe the solution you'd like.

There are only 2 types of runners accepted:
- Absolute path
- Inside WDIO

Creating a new npm package for it won't help, adding it to WDIO is the best way.

### Additional context

I have a mostly working version, happy to PR, but I would like some help reviewing it and ensuring it works properly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
> Jest has a larger adoption and extra tools, including tools for visual regression.

Jest is a popular tool but mostly used in the context for unit tests. Can you please explain what kind of features you are missing from Jest in WebdriverIO?

> I have a mostly working version, happy to PR, but I would like some help reviewing it and ensuring it works properly

Can you share what you have build so far?

**Comment by sidferreira** [comment]
@christian-bromann 

Link to my branch/code: https://github.com/sidferreira/webdriverio/tree/jest-framework/packages/wdio-jest-framework

One good example of feature I would like is https://github.com/americanexpress/jest-image-snapshot

**Comment by christian-bromann** [comment]
> One good example of feature I would like is https://github.com/americanexpress/jest-image-snapshot

There is an issue for that: https://github.com/webdriverio/webdriverio/issues/9989. What other features?

**Comment by christian-bromann** [comment]
To be clear, I am not against adding a Jest framework adapter. When it comes to features we need to be careful. Things like image or DOM snapshots should be part of the testrunner and not the testrunner framework. People running tests in Cucumber might also want to use them too.

**Comment by sidferreira** [comment]
@christian-bromann What I mean is that if we have Jest, the developers can integrate jest extensions as they need. 

I don't think https://github.com/americanexpress/jest-image-snapshot should be part of WDIO

**Comment by sidferreira** [comment]
@christian-bromann I'm not familiar enough with cucumber... I integrated it with Jasmine once, but the experience was sub-optimal.

**Comment by christian-bromann** [comment]
I think what I am trying to say is that WebdriverIO has integrated different test runners so people have a choice how their test are being run. I see image snapshot testing not as a test runner feature but more a test framework feature. As a runner I see a tool that executes the tests and provides reporting, a test framework integrates a test runner with multiple features on top, e.g. an assertion library. Therefor I would love to see the `jest-image-snapshot` plugin as something everyone using WebdriverIO, no matter which test runner, should be able to use.

**Comment by sidferreira** [comment]
@christian-bromann Although I agree, I don't have any projects with Cucumber/Mocha/Jasmine... 
To be honest, I have a small barrier as the project for which I want to add WDIO wants it to use Jest.

I'm totally in favour of other tools having `jest-image-snapshot`, but I don't have the time nor the knowledge to integrate them. I don't have the knowledge to be sure that it even works as expected.

**Comment by christian-bromann** [comment]
> I have a small barrier as the project for which I want to add WDIO wants it to use Jest.

Do you use Jest for UI and component testing as well?

> but I don't have the time nor the knowledge to integrate them. I don't have the knowledge to be sure that it even works as expected.

The easiest way to have support for image snapshot is to find a way to extend the WebdriverIO expect helper. Have you tried to run:

```js
const { toMatchImageSnapshot } = require('jest-image-snapshot');
expect.extend({ toMatchImageSnapshot })
```

as part of your `before` hook?

**Comment by sidferreira** [comment]
> Do you use Jest for UI and component testing as well?

That's our goal, but different run commands

> as part of your before hook?

I had to do some workarounds back in the day, but it would not solve all my problems

**Comment by christian-bromann** [comment]
> That's our goal, but different run commands

Have you considered using WebdriverIO for doing that? See: https://webdriver.io/docs/component-testing. One framework to rule them all 😉 

> but it would not solve all my problems

What are your problems?

**Comment by sidferreira** [comment]
@christian-bromann there's a desire, from some stakeholders, of using jest as runner

**Comment by christian-bromann** [comment]
@sidferreira do you think we can close this issue? Adding support for snapshot testing will be part of https://github.com/webdriverio/webdriverio/issues/9989

**Comment by sidferreira** [comment]
@christian-bromann snapshot is a side effect of this isdue, not the main reason

**Comment by christian-bromann** [comment]
> snapshot is a side effect of this isdue, not the main reason

Can you please outline the reasons why a Jest testrunner would provide value? As I mentioned before it is great for unit testing but not ideal for e2e testing. So far some of the arguments I heard were:

__Jest has snapshot testing__
Jest can take snapshots of objects and compare them with each other but how is this useful for e2e testing? There is #9989 as a feature request where we want to bring this into the WebdriverIO world.

__it.each__
Something like this can be done with Jasmine and Mocha too (see [here](https://blog.harveydelaney.com/running-multiple-test-cases-in-jasmine/)). You can also extend the `it` global in your `before` hook to support this.

__"We" want to write the same style of tests for unit and e2e__
WebdriverIO has the same expect library and uses the same tdd language. There is already no difference.

__"We" don't want to learn another tool__
Well, I would argue you can't build a house with a single tool either. Unit and e2e testing has different requirements and deserve different tooling approaches. WebdriverIO now supports unit and component testing and you could run your Node.js unit tests in WebdriverIO to using Chrome headless and just ignore the browser is there.

So please provide a "main" reason why WebdriverIO should consider adding Jest as testrunner. Everyone is free to try to integrate WebdriverIO into a Jest framework but I can ensure you that it will end up with more work than just using the WebdriverIO testrunner.

**Comment by sidferreira** [comment]
> not ideal for e2e testing

 Can you elaborate on that? What does Jasmine/Mocha offer that Jest doesn't? 

> it.each

Jest offers very complex uses of it. The solution in the article doesn't match them

> main reason

It is hard to provide a "main" argument as we have opposite views in some aspects. The idea is to have Jest and its ecosystem accessible to work with WDIO, giving developers more freedom in what stack to use.

**Comment by christian-bromann** [comment]
> Can you elaborate on that? What does Jasmine/Mocha offer that Jest doesn't?

None. The only thing that Jest offers compared to Mocha/Jasmine is maybe this `it.each` construct.

> The idea is to have Jest and its ecosystem accessible to work with WDIO, giving developers more freedom in what stack to use.

True. Adding a framework runner integration is not a trivial task of work. Given the amount of competing prioritise I doubt it will be picked up by someone from the core team. If you like to contribute this, that would be awesome and I am happy to support that.

**Comment by christian-bromann** [comment]
@sidferreira any updates on the development on this?

**Comment by sidferreira** [comment]
> @sidferreira any updates on the development on this?

We're developing it internally for now. Alpha state, no release goals yet.

**Comment by christian-bromann** [comment]
Sounds good! Let me know if there are any questions.

**Comment by rostislav-simonik** [comment]
@sidferreira can you provide some updates, We would be interested in such integration as well, thx.

**Comment by sidferreira** [comment]
@rostislav-simonik I have a local version for now, which is focused on WDIO7. I'll try to share an alpha version soon

**Comment by christian-bromann** [comment]
@sidferreira any updates? I feel inclined to close this.

**Comment by christian-bromann** [comment]
I will go ahead and close the issue. We are always welcoming contributions in this direction but this would not be something the WebdriverIO team is able to work on due to limited capabilities and due to the fact that it wouldn't provide much additional value compared to the frameworks WebdriverIO already provides. Thanks @sidferreira for providing insights on this. If you ever end up releasing a package like this, please reach out so we can promote this accordingly.
