### ISSUE TITLE
[🐛 Bug]: `ui: tdd` doesn't seem to have any effect

### ISSUE THREAD

**Issue by jayeshbhoot** [webdriverio/webdriverio#10175]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

16.18.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
        maxInstances: 5,
        browserName: 'chrome',
        acceptInsecureCerts: true,
        'goog:chromeOptions': {
            args: ['disable-web-security'],
        },
}
```

### What happened?

1. Configure mocha to use tdd in `wdio.conf.js`

2. Use tdd functions in a **component** test (i.e., using browser runner).

3. Test fails (see log below) trying to look for `before`.

### What is your expected behavior?

wdio/mocha shouldn't be looking for `before` at all, because mocha is configured to use `tdd`.

### How to reproduce the bug.

Use the following wdio.conf.js

```
export const config = {
    runner: ['browser', {
        preset: 'react',
        headless: !Boolean(process.env.DEBUG),
        viteConfig: (env) => {
            return {
                define: {
                    'process.env.NODE_ENV': JSON.stringify('test'),
                },
            };
        },
    }],

    specs: [
        // './tests-wdio/**/*.test.js',
        './tests-wdio/**/*.test.jsx',
    ],
    exclude: [
        // 'path/to/excluded/files'
    ],
    maxInstances: 10,
    capabilities: [{
        maxInstances: 5,
        browserName: 'chrome',
        acceptInsecureCerts: true,
        'goog:chromeOptions': {
            args: ['disable-web-security'],
        },
    }],
    logLevel: 'warn',
    bail: 0,
    baseUrl: '',
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    services: [
        'chromedriver',
        'geckodriver',
    ],
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'tdd',
        // timeout: 60000,
    },
};
```

Use tdd functions in a **component** test (i.e., using browser runner).

```
suite('Test suite', function() {
    suiteSetup(async function() {
       // set up
    });

    test('run this test', async function() {
      // test code
    });
});
```

Run the test.

```
$ DEBUG=true npx wdio run ./wdio.conf.js
```

### Relevant log output

Running this test ends with the following error in the browser console:

```
mocha.js?v=b32bc9c5:84 Uncaught (in promise) ReferenceError: before is not defined
    at MochaFramework.run (mocha.js?v=b32bc9c5:84:9)
run @ mocha.js?v=b32bc9c5:84
```

And the following error in the terminal console:

```
$ DEBUG=true npx wdio run ./wdio.conf.js

Execution of 1 workers started at 2023-04-12T09:35:10.772Z

[0-0] RUNNING in chrome - file:///tests-wdio/L2/login.test.jsx
[0-0] %cDownload the React DevTools for a better development experience: https://reactjs.org/link/react-devtools font-weight:bold
[0-0] 2023-04-12T09:35:23.796Z ERROR @wdio/runner: Failed to run browser tests with cid 0-0: Error: browser test timed out
[0-0]     at file:///Users/jayesh/project/node_modules/webdriverio/build/commands/browser/waitUntil.js:39:23
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0]     at async Proxy.wrapCommandFn (file:///Users/jayesh/project/node_modules/@wdio/utils/build/shim.js:72:29)
[0-0]     at async BrowserFramework.#loop (file:///Users/jayesh/project/node_modules/@wdio/runner/build/browser.js:86:13)
[0-0]     at async BrowserFramework.run (file:///Users/jayesh/project/node_modules/@wdio/runner/build/browser.js:39:30)
[0-0]     at async Runner.run (file:///Users/jayesh/project/node_modules/@wdio/runner/build/index.js:145:24)
[0-0]  Error:  browser test timed out
[0-0] FAILED in chrome - file:///tests-wdio/L2/login.test.jsx

Spec Files:	 0 passed, 1 failed, 1 total (100% completed) in 00:00:13
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

It seems like we don't initiate Mocha correctly when running in the browser.

Any contributions that resolves the bug are highly appreciated. Don't expect this to be picked up by active contributors as they have their own priorities. If you depend on this bug to be fixed, your contribution is required. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by jayeshbhoot** [comment]
Yes, there seems to be a disparity between the local and the browser runner w.r.t mocha integration. [See also](https://github.com/webdriverio/webdriverio/discussions/10170#discussioncomment-5613212), which notes another discrepancy that the local runner supports `mochaOpts.require`, but the browser runner throws an error.

> Any contributions that resolves the bug are highly appreciated. Don't expect this to be picked up by active contributors as they have their own priorities. If you depend on this bug to be fixed, your contribution is required.

Noted. I appreciate all the hard work put into wdio.

I intend to pick this up when it becomes an annoyance. Would you mind keeping the issue open?
