### ISSUE TITLE
[💡 Feature]: Make a possibility to pass arguments to sub-worker processess

### ISSUE THREAD

**Issue by pharaoh-11** [webdriverio/webdriverio#10184]
### Is your feature request related to a problem?

It's related to a bug https://github.com/webdriverio/webdriverio/issues/8971 in v7

### Describe the solution you'd like.

In v7 and earlier wdio had a hidden possibility to  pass arguments to sub-processess. To achieve this we could use onWorkerStart() hook, like this
```
onWorkerStart(cid: string, caps: any, specs: string[], args: any) {
        args.entity = 'entity1';
},
```
It worked but with one [bug](https://github.com/webdriverio/webdriverio/issues/8971). In laters version of v8 wdio and don't have such ability at all. I don't know was this hidden feature was caused by a bug or now but if we revert the feature back and well document it, we can create a one of the most important pros of wdio product.

### Additional context

A quick solution how could we achieve this in v7.

There was a code in 7.30.1 version in [packages/wdio-cli/src/launcher.ts](https://github.com/webdriverio/webdriverio/blob/v7.30.1/packages/wdio-cli/src/launcher.ts) file
```
// run worker hook to allow modify runtime and capabilities of a specific worker
        log.info('Run onWorkerStart hook')
        await runLauncherHook(config.onWorkerStart, runnerId, caps, specs, this._args, execArgv)
            .catch((error) => this._workerHookError(error))
        await runServiceHook(this._launcher!, 'onWorkerStart', runnerId, caps, specs, this._args, execArgv)
            .catch((error) => this._workerHookError(error))

        // prefer launcher settings in capabilities over general launcher
        const worker = this.runner.run({
            cid: runnerId,
            command: 'run',
            configFile: this._configFilePath,
            args: { ...this._args, ...(config?.autoCompileOpts ? { autoCompileOpts: config.autoCompileOpts } : {}) },
            caps,
            specs,
            execArgv,
            retries
})
```
where `this._args` field of the `Lancher` class gave us the possibility to get arguments from a root process. But the fact that  _args is an object field led to a bug above. 
So, my suggestion how to fix this, we can do something like this
```
// run worker hook to allow modify runtime and capabilities of a specific worker
        log.info('Run onWorkerStart hook')
        const addedArgs = await runLauncherHook(config.onWorkerStart, runnerId, caps, specs, this._args, execArgv)
            .catch((error) => this._workerHookError(error))
        await runServiceHook(this._launcher!, 'onWorkerStart', runnerId, caps, specs, this._args, execArgv)
            .catch((error) => this._workerHookError(error))

        // prefer launcher settings in capabilities over general launcher
        const worker = this.runner.run({
            cid: runnerId,
            command: 'run',
            configFile: this._configFilePath,
            args: { ...this._args, ...(config?.autoCompileOpts ? { autoCompileOpts: config.autoCompileOpts } : {}), ...addedArgs },
            caps,
            specs,
            execArgv,
            retries
})
```
and user can do this on his side
```
onWorkerStart(cid: string, caps: any, specs: string[], args: any) {
        return 'entity1';
},
```
But as I said there is no such possibility in last wdio version so we have to create it from scratch now.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
> In v7 and earlier wdio had a hidden possibility to pass arguments to sub-processess.

Never use hidden possibilities as you never know if they continue to work 😉 

I don't quite get your use case? What are you trying to achieve?

**Comment by pharaoh-11** [comment]
@christian-bromann for example we have a limited quantity of testing entities, let it be 5. And we have 1000 or more e2e tests. There is only one way to use them instead of creation 1000 entities per each tests. We set up wdio to run tests paralely in 5 threads and assign one entity per thread. To achieve this we need somehow pass that entity to a sub-process

**Comment by christian-bromann** [comment]
What do you mean by "entity"?

**Comment by pharaoh-11** [comment]
It can be a simple string or any object doesn't matter. The main idea that the root process can manage limited testing staff. Allocate it for a sub-proccess and then release it in onWorkerEnd() hook to re-allocate it for a new thread. In this way we can use 10 expensive entities in the whole test run

**Comment by christian-bromann** [comment]
Would this solve your use case: https://webdriver.io/docs/shared-store-service#resource-pools ?

**Comment by pharaoh-11** [comment]
no, 'cause it's a common resource pool. It can manage resources from the root process but we have to pass it in [onWOrkerStart()](https://webdriver.io/docs/configuration/#onworkerstart) hook, but args arguments f it has the bug https://github.com/webdriverio/webdriverio/issues/8971

**Comment by pharaoh-11** [comment]
To be honest we still have a possibility to pass args argument in v8.8.2 in [onWOrkerStart()](https://webdriver.io/docs/configuration/#onworkerstart), I don't know why I didn't find it in v8.7.x, so we can close this ticket, but the bug https://github.com/webdriverio/webdriverio/issues/8971 should be fixed

**Comment by christian-bromann** [comment]
> It can manage resources from the root process but we have to pass it in [onWOrkerStart()](https://webdriver.io/docs/configuration/#onworkerstart) hook

You can fetch resources from that pool within the `onWorkerStart` hook, e.g.

```js
    beforeSession: async (conf) => {
        conf.baseUrl = await getValueFromPool('availableUrls');
    }
```

> but the bug #8971 should be fixed

As mentioned in the ticket, please get involved. Don't expect this to be picked up by anyone.
