### ISSUE TITLE
[🐛 Bug]: no such element

### ISSUE THREAD

**Issue by fabianschmider** [webdriverio/webdriverio#10182]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
browserName: 'chrome',
browserVersion: 'latest',
platformName: 'Windows 10'
}
```

### What happened?

Hi all,
since this week ALL the tests from our company are failing with this error message:
1. "no such element: no such element: Unable to locate element: {"method":"css selector","selector":"[id="user"]"}"
2.  "no such element: unknown error"

The error message also comes up,
if I throw the click commands in comments,
so there are only the defined selectors without action,
f.e.:
const icon_login = await $('[id="user"]');

### What is your expected behavior?

The selectors should be clicked.

### How to reproduce the bug.

describe('1_Login', () => {
    it('1.1/1.2/1.3', async() => {        
        await browser.url(`https://www.sick.com`);
        await browser.deleteCookies();

        const cookie = await $('[class="button blue big"]');
        const icon_login = await $('[id="user"]');
        const button_login_div = await $('[class="login-button text-base font-semibold"]');
 
        await cookie.click();

        //login
        await icon_login.moveTo();
        await button_login_div.click();
   });
});

### Relevant log output

```typescript
no such element: no such element: Unable to locate element: {"method":"css selector","selector":"[id="user"]"}
  (Session info: chrome=112.0.5615.50)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for filing the issue.

This is not a bug in WebdriverIO. It seems it is not possible to find the element you are looking for. That could also be caused by your application.

**Comment by fabianschmider** [comment]
Hi @christian-bromann ,
thanks for your answer.

In our application there was no release last week - so nothing changed here.
Interesting is,
the tests work fine with WDIO mobile tests,
all the browser tests (safari/chrome/firefox) are failing - all together since last week.

Maybe Saucelabs could be a reason here ?
I need to fix this asap, 
If you dont have any other ideas I will contact saucelabs.

Thanks,
BR

**Comment by Tomasz-Klubasz** [comment]
> Hi @christian-bromann , thanks for your answer.
> 
> In our application there was no release last week - so nothing changed here. Interesting is, the tests work fine with WDIO mobile tests, all the browser tests (safari/chrome/firefox) are failing - all together since last week.
> 
> Maybe Saucelabs could be a reason here ? I need to fix this asap, If you dont have any other ideas I will contact saucelabs.
> 
> Thanks, BR

Hi @fabianschmider, I have the same issue, it seems to be a Sauce Labs problem
Contact them, the more people will report something, the bigger chance is that they'll look into that

**Comment by fabianschmider** [comment]
Hi @Tomasz-Klubasz ,
Saucelabs called me:
"our Engineers have deployed a fix which may have resolved this issue"

Our tests are running fine now,
Hope yours as well !
BR

**Comment by Tomasz-Klubasz** [comment]
> Hi @Tomasz-Klubasz , Saucelabs called me: "our Engineers have deployed a fix which may have resolved this issue"
> 
> Our tests are running fine now, Hope yours as well ! BR

Same here! Thank you
