### ISSUE TITLE
Use Selenium's automatic screenshot where possible

### ISSUE THREAD

**Issue by georgecrawford** [webdriverio/webdriverio#1018]
In some error cases (the example I saw was when throwing an `Error` in the browser context during an `executeAsync` call), Selenium will return a `screen` property on the HTTP response. If the user has opted in to screenshots, we should save this to disk, and record the file path on the error object so it can be referred to. This prevents both webdriverio and the user from having to request another screenshot to be taken when processing the error, which introduces a latency which may well cover up the error condition if it was a quick glitch.

**Comment by christian-bromann** [comment]
Can you check if you get access to the screen property of the failed response somewhere along these lines: https://github.com/webdriverio/webdriverio/blob/master/lib/webdriverio.js#L118-L122

**Comment by christian-bromann** [comment]
I think we can close this since #1021 fixes the issue. Feel free to reopen if not.
