### ISSUE TITLE
[🐛 Bug]: Allure report is missing steps, links data when the afterEach() hook is present is the suite

### ISSUE THREAD

**Issue by Medvedscak** [webdriverio/webdriverio#10185]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.7.0

### Node.js Version

18.14.2

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
"platformName": "Android",
"deviceName": "Emulator",
"app": "path_to.apk",
"appPackage": "com.sand.appname",
"appWaitActivity": "com.sand.appname.activity",
"udid": "emulator-5556",
"autoGrantPermissions": true,
"systemPort": 6001,
"port": 4723
}
```

### What happened?

When I add the **afterEach()** hook to the suite (**even if it's empty**) - the allure report doesn't contain any steps/links data. The report is fine without the hook.

```
afterEach(async () => {
     // there can be anything or even nothing
})
```

### What is your expected behavior?

Allure steps, severity, links etc. are shown in the report, the same as when I run tests without using the afterEach()

### How to reproduce the bug.

Add any test case inside the suite, add any allure steps data to the test case. Add the afterEach hook:

    afterEach(async () => {
        // anything here or leave empty
    })

NOTE: I'm not sure about other hooks but 100% repro with these steps above

Repo with the code to reproduce (see the readme.md inside): https://github.com/Medvedscak/webdriverio-allure-issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by BorisOsipov** [comment]
@Medvedscak, is it necessary to use await driver.launchApp() specifically or can any afterEach hooks result in this behavior?

**Comment by Medvedscak** [comment]
@BorisOsipov actually, you're right. I've just retested this and the issue happens when I just add (even empty!) afterEach() hook... I'll update the description of the issue

**Comment by BorisOsipov** [comment]
@Medvedscak Could I ask you to create a very simple repository with a minimum reproducible example using the [WDIO Getting Started](https://webdriver.io/docs/gettingstarted#initiate-a-webdriverio-setup) guide? This will help contributors to easily reproduce and fix issues by simply cloning and running the code.

**Comment by Medvedscak** [comment]
@BorisOsipov I've created the repo here: https://github.com/Medvedscak/webdriverio-allure-issue
Added this to the issue description

**Comment by TepmuT13** [comment]
I have the same problem. These 2 screenshots for 2 equal tests with _beforeEach_ and without _beforeEach_.
Intresting moment that duration of test without steps is 1ms. I don't undertsantd why a test body isn't generated with beforeEach hook (it's also actual for _afterEach_ hook) 
![image](https://github.com/webdriverio/webdriverio/assets/22410553/c81744cb-1410-4099-a476-6af7e31c8d4f)
![image](https://github.com/webdriverio/webdriverio/assets/22410553/e20c0590-e163-4d23-a796-9f7c1ecd8281)

**Comment by christian-bromann** [comment]
Thanks for further information @TepmuT13 !

We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!
