### ISSUE TITLE
[🐛 Bug]: Issue with image comparison service

### ISSUE THREAD

**Issue by piyushsingh1994** [webdriverio/webdriverio#10193]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

6.6.7

### Node.js Version

Node 14

### Mode

WDIO Testrunner

### What happened?

All the functions related to image comparison is not working.
One of the error is this
1. browser.saveFullPageScreen is not a function
 2. browser.checkScreen is not a function

### How to reproduce the bug.

While running with wdio runner. Node v being used is 14 and wdio version is 6.6.7

### Relevant log output

```typescript
browser.saveFullPageScreen is not a function
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@piyushsingh1994 thanks for raising the issue. Please report this bug in the image comparison repository. Thank you!
