### ISSUE TITLE
[🐛 Bug]: TSConfigPathsOptions not available in autoCompileOpts

### ISSUE THREAD

**Issue by matthew2564** [webdriverio/webdriverio#10191]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.8.2

### Node.js Version

v18.10.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
N/A
```

### What happened?

In v7.x, you could specify TS config path aliases like so

```
  autoCompileOpts: {
    autoCompile: true,
    tsNodeOpts: {
      transpileOnly: true,
      project: 'tsconfig.json',
    },
    tsConfigPathsOpts: {
      baseUrl: './',
      paths: {
        '@shared-boilerplate/*': ['shared/boilerplate/*'],
        '@shared-custom/*': ['shared/custom/*'],
        '@shared-helpers/*': ['shared/helpers/*'],
      },
    },
  },
```

`autoCompileOpts` conforms to the interface described here

```
export interface AutoCompileConfig {
    autoCompile?: boolean;
    tsNodeOpts?: RegisterOptions;
    babelOpts?: Record<string, any>;
    tsConfigPathsOpts?: TSConfigPathsOptions;
}
```

In v8.8.x, the interface has changed to the following, I'm therefore enquiring where should the paths be specified
```
export interface AutoCompileConfig {
    autoCompile?: boolean;
    babelOpts?: Record<string, any>;
    tsNodeOpts?: TSNodeOptions;
}
```

### What is your expected behavior?

I would expect to be able to us TS path aliasing successfully.

### How to reproduce the bug.

Init new WDIO project inside folder using `npm init wdio .`

Dev Dependencies
```
  "devDependencies": {
    "@wdio/cli": "^8.8.2",
    "@wdio/cucumber-framework": "^8.8.0",
    "@wdio/local-runner": "^8.8.2",
    "@wdio/spec-reporter": "^8.8.0",
    "chromedriver": "^112.0.0",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.0.4",
    "wdio-chromedriver-service": "^8.1.1"
  },
```

### Relevant log output

```typescript
Cannot find package '@shared-helpers/clickElement' imported from /<FILE-PATH>/src/step-definitions/steps.ts
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by yangzeqiminichris** [comment]
Is there an alternative plan to solve this? There are so many places used tsconfig-path alias in my project.

**Comment by christian-bromann** [comment]
> Is there an alternative plan to solve this?

Doesn't TS now support this out of the box? See https://www.typescriptlang.org/tsconfig#paths

**Comment by sschoorens** [comment]
Hello, I also need this to avoid rewriting paths when i move files but if it can be directly read from the `tsconfig.json` it would be perfect.
To reproduce I've created a clean wdio with `npm init wdio@latest`
with that conf
```
{
    runner: 'local',
    autoCompileOpts: {
        autoCompile: true,
        tsNodeOpts: {
            project: './tsconfig.json',
            transpileOnly: true
        }
    },
    specs: [
        './test/specs/**/*.ts'
    ],
    maxInstances: 10,
    capabilities: [{
        browserName: 'chrome' // or "firefox", "microsoftedge", "safari"
    }],
    logLevel: 'error',
    baseUrl: 'http://localhost',
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    services: ['chromedriver'],
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    }
}
```

then i've edited the tsconfig.json as below
```
{
    "compilerOptions": {
        "moduleResolution": "node",
        "module": "ESNext",
        "types": [
            "node",
            "@wdio/globals/types",
            "expect-webdriverio",
            "@wdio/mocha-framework"
        ],
        "target": "es2022",
        "baseUrl": ".",
        "paths": {
            "@test/*": ["test/*"]
        }
    }
}
```

and changed the generated test `test/specs/example.e2e.ts` as below
```
import LoginPage from '@test/pageobjects/login.page.js'
import SecurePage from '@test/pageobjects/secure.page.js'

describe('My Login application', () => {
    it('should login with valid credentials', async () => {
        await LoginPage.open()

        await LoginPage.login('tomsmith', 'SuperSecretPassword!')
        await expect(SecurePage.flashAlert).toBeExisting()
        await expect(SecurePage.flashAlert).toHaveTextContaining(
            'You logged into a secure area!')
    })
})
```

What i excepted is that everything goes right

What i got is the same issue as host
```
Error: Error: Cannot find package '@test/pageobjects' imported from /[...]/test/specs/example.e2e.ts
```

I hope you will announce here when it will work ! ty.

**Comment by christian-bromann** [comment]
@sschoorens what you are describing should work as it is a native TypeScript feature. The original author asked for continued support for [`tsconfig-paths`](https://www.npmjs.com/package/tsconfig-paths) which isn't possible.

> I hope you will announce here when it will work ! ty.

To set expectations clear: if you are interested for support of this, please get involved, I have my own priorities and am unlikely to get to this ever. I understand the value of this feature but there are other things that are more important to me.

**Comment by BlackSwan2019** [comment]
With these changes, are aliased imports, like `import { SomePage } from '@pages'` no longer supported?

Should I change all my imports to `import { SomePage } from '../../screens/index.ts'`?

Looks like someone [found a solution](https://github.com/TypeStrong/ts-node/discussions/1450#discussioncomment-1806115) for ts-node paths, and someone further made an npm package from it [here](https://github.com/luanglopes/ts-paths-esm-loader). I tried using that package via the `requireModule` wdio config so paths could be registered before a test, but that didn't work (I was naïve to think it'd be that simple).

**Comment by christian-bromann** [comment]
> With these changes, are aliased imports, like `import { SomePage } from '@pages'` no longer supported?

Unfortunately it seems we couldn't support this anymore, see my comment [above](https://github.com/dividab/tsconfig-paths/issues/221).

> Should I change all my imports to `import { SomePage } from '../../screens/index.ts'`?

I would suggest this workaround for now.

> Looks like someone [found a solution](https://github.com/TypeStrong/ts-node/discussions/1450#discussioncomment-1806115) for ts-node paths, and someone further made an npm package for it [here](https://github.com/luanglopes/ts-paths-esm-loader). I tried using that package via the `requireModule` wdio config so paths could be registered before a test, but that didn't work (I was naïve to think it'd be that simple).

I am all for adding support again for this functionality. Any PRs are welcome and I am happy to help.

**Comment by BlackSwan2019** [comment]
I was able to get my import aliases (`import SomeScreen from '@screens'`) working with WebdriverIO v8! 

I copied the code from the workaround [here](https://github.com/TypeStrong/ts-node/discussions/1450#discussioncomment-1806115) and made a file in my project called loader.js.

Additionally, right before the `wdio` CLI command is invoked, I also `export TS_NODE_PROJECT=tsconfig.json`.

Then, in the wdio config file, I set the `execArgv` field like so:
`execArgv: ['--experimental-specifier-resolution=node', '--loader', './loader.js'`.

I ran some Appium tests and my `@screen` alias works again.

**Comment by Winify** [comment]
@BlackSwan2019 Thank you!!!
My magic command was your `execArgv` trick! Now it works for me seamlessly.

Though I did not need to set the `TS_NODE_PROJECT` env var (maybe I was overeager and forgot), and the `./loader.js` somehow initiated a chrome download error, or an allure command error (I do not know which propagated which...)

But when I switch to `execArgv: ['--loader', 'ts-paths-esm-loader/transpile-only']`, then it works as expected!
It is an npm module that was created for this exact problem, with the same exact loader file as you linked, as a reference:
[ts-paths-esm-loader](https://www.npmjs.com/package/ts-paths-esm-loader)

The TS_NODE_PROJECT is set in my autoCompileOpts and the `--experimental-specifier-resolution=node` is set in my tsconfig.json.

**Comment by amin-setayeshfar** [comment]
@Winify could you please explain more or provide your tsconfig and wdio configs? also to be sure: you are not using a loader file but the ts-paths-esm-loader instead. right?
i think since I'm using a new node version I should use your solution but wdio v8 still does not recognize my paths
