### ISSUE TITLE
[🐛 Bug]: @wdio/cli CJS build SyntaxError

### ISSUE THREAD

**Issue by DirkoOdendaal** [webdriverio/webdriverio#10198]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

V8.8.2

### Node.js Version

v18.12.0

### Mode

Standalone Mode

### What happened?

When using the CJS import on @wdio/cli then you get the error:

node_modules/@wdio/cli/build/cjs/index.js:1
export class Launcher {
^^^^^^

SyntaxError: Unexpected token 'export'

### What is your expected behavior?

Expect that importing the @wdio/cli CJS build would result in no SyntaxErrors.

### How to reproduce the bug.

To reproduce the bug you need to import the @wdio/cli CJS build and execute tests

### Relevant log output

```typescript
None
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Let's continue convo in #10199
