### ISSUE TITLE
v3 much slower than v2

### ISSUE THREAD

**Issue by bonjonbovi87** [webdriverio/webdriverio#1022]
Hello,

I'm trying to convert our code from v2 to v3, but I can't help but notice how much slower it is in general, am I missing something?  Here is an example using the webdriver.io site, and my execution times.

v2.4.5 = 11 seconds
v3.4.0 = 38 seconds

```javascript
var webdriverio = require('webdriverio');

var options = {
    desiredCapabilities: {
        browserName:'chrome',
    },
    host : '138.120.132.39',
    port : '5555',
};

driver = webdriverio.remote(options);

describe('describe', function(){

    this.timeout(600000)

    it('time test', function(done){
        driver
        .init()
        .url('http://www.webdriver.io')
        .click('//*[text()="API"]')
        .waitForExist('//*[@name="search"]', 5000)
        .setValue('//*[@name="search"]', "this is some search criteria")
        .click('//*[@class="icon icon-remove"]')
        .end(done)

    });
});
```

It seems finding new elements is costly.

Thanks,
Travis

**Comment by christian-bromann** [comment]
Hi Travis,
I also ran the test and it seems that v3.4.0 is slightly slower yeah:

__v2.4.5__
```
./node_modules/.bin/mocha index.js  0.97s user 0.12s system 12% cpu 8.647 total
./node_modules/.bin/mocha index.js  1.00s user 0.12s system 13% cpu 8.454 total
./node_modules/.bin/mocha index.js  0.95s user 0.12s system 12% cpu 8.833 total
```

__3.4.0__
```
./node_modules/.bin/mocha index.js  1.15s user 0.14s system 14% cpu 8.943 total
./node_modules/.bin/mocha index.js  1.05s user 0.13s system 13% cpu 8.762 total
./node_modules/.bin/mocha index.js  1.08s user 0.13s system 13% cpu 8.877 total
```

But I think it is because we are now generating way more objects which have to be collected by the garbage collector. I would still recommend updating your code and make use of the wdio test runner where you can run tests in parallel.

**Comment by bonjonbovi87** [comment]
Thanks for the quick response, I'll keep tinkering around with it

**Comment by bonjonbovi87** [comment]
I should also mention that my times were executing on a remote selenium.  Running on localhost with firefox the times were:

v2.4.5 = 4.4 seconds
v3.4.0 = 9.1 seconds

**Comment by bonjonbovi87** [comment]
Bumping an old-closed thread, but the issue was with proxies.  v4 doesn't like them but v2 is fine with them (or at least WRT the proxy I have at work)
