### ISSUE TITLE
tsconfig import @wdio/globals/types, while use  $$.map(ele  => {}) still report TS error TS7006

### ISSUE THREAD

**Issue by yangzeqiminichris** [webdriverio/webdriverio#10229]
While upgrade webdriverio from 7 to 8,  I found the tsconfig is changed from webdriverio/async to @wdio/globals/types according to official doc.

But the function like $$(selector).map(ele => {}) still report  error TS7006: Parameter 'ele' implicitly has an 'any' type. 

How can  I solve this problem without announce the ele is Element type, cause there are so much place use these functions.

I will be very grateful if you could answer my question

**Comment by christian-bromann** [comment]
@yangzeqiminichris can you provide a minimal reproducible example project?

**Comment by yangzeqiminichris** [comment]
Sorry, My mistake, it is because the path, the problem is solved now
