### ISSUE TITLE
[💡 Feature]: Add Appium Capabilities - disableIdLocatorAutocompletion

### ISSUE THREAD

**Issue by a6a18** [webdriverio/webdriverio#10223]
### Is your feature request related to a problem?

I'm always frustrated when i use this capabilities, but there is a error.

![image](https://user-images.githubusercontent.com/39345520/232703555-71b334e9-1b2e-4254-92ab-486fbc17d6a2.png)

### Describe the solution you'd like.

add `disableIdLocatorAutocompletion` Capabilities

more infomation: https://github.com/appium/appium/issues/15138?fbclid=IwAR0zk-Cz8dikj5HYgKda3UVoZdFaCNOr4R2sVtNCuXZytxs_VkpJN7ss2oo

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by a6a18** [comment]
You can find disableIdLocatorAutocompletion in this [file](https://github.com/appium/appium-uiautomator2-driver/blob/master/README.md). This Capabilities is dedicated to uiautomator2 driver.

**Comment by christian-bromann** [comment]
This property is part of the settings API which you can use via https://webdriver.io/docs/api/appium#updatesettings, it is not a capability.

**Comment by Mynziak** [comment]
@a6a18 Is this issue still relevant for you? How did you resolve it?

I've encountered a similar challenge with the `resource-id` when using wdio with Jetpack Compose support. Interestingly, I noticed that the added `resource-id` can be found as `~resource-d` in the Appium inspector, but when running tests, they can't be located.

Here are details of my setup:
- Appium version: 2.4.1
- "@wdio/appium-service": "^7.33.0"
- "appium-uiautomator2-driver": "^2.41.0"

I'd appreciate any insights you might have on how to address this issue. Thanks!

**Comment by testingmobileat** [comment]
> I encountered the same issue as you, where I couldn't locate it during test runs, but the Appium Inspector could. From what I remember, it involved adding `disableIdLocatorAutocompletion` as suggested in the reply.
> 
> You can write it like this:
> 
> ```
> config.beforeHook = () => {
>     driver.updateSettings({ 'appium:disableIdLocatorAutocompletion': true })
> }
> ```
> 
> But I think the core issue is that Jetpack Compose UI requires manually adding testTag for better localization. You can refer to this here: https://developer.android.com/reference/kotlin/androidx/compose/ui/platform/package-summary#(androidx.compose.ui.Modifier).testTag(kotlin.String)"

Hi @a6a18 i have try your code but still not working for me always get error 

> Setting disableIdLocatorAutocompletion is not supported.

Can your share all code?
