### ISSUE TITLE
[Typescript] AppiumAndroidCapabilities not in W3C format

### ISSUE THREAD

**Issue by AdamOakman** [webdriverio/webdriverio#10225]
Typescript
Appium 2.0.0-beta61
WDIO version: 8.8.2

When a AppiumAndroidCapabilities capability (below example is for autoGrantPermissions) is passed without W3C prefix (appium:)

```  
capabilities: [
    {
      platformName: 'Android',
      'appium:automationName': 'UiAutomator2',
      'appium:app': './apps/app-debug.apk',
      'appium:deviceName': 'Pixel_7_Pro_API_29',
      'appium:platformVersion': '10',
      'appium:orientation': 'PORTRAIT',
      autoGrantPermissions: true,
    },
  ],
```

an errror is thrown:

`[0-2] 2023-04-18T12:53:30.011Z ERROR @wdio/runner: Error: Invalid or unsupported WebDriver capabilities found ("autoGrantPermissions"). Ensure to only use valid W3C WebDriver capabilities (see https://w3c.github.io/webdriver/#capabilities).If you run your tests on a remote vendor, like Sauce Labs or BrowserStack, make sure that you put them into vendor specific capabilities, e.g. "sauce:options" or "bstack:options". Please reach out to to your vendor support team if you have further questions.`

On the other hand whe I use capability name with W3C prefix tests can be run without issues but IDE treats this line as an error:

<img width="442" alt="image" src="https://user-images.githubusercontent.com/43219983/232788859-633788ab-f049-4880-8589-9683174845d5.png">

Error details:

```Type '{ platformName: string; 'appium:automationName': string; 'appium:app': string; 'appium:deviceName': string; 'appium:platformVersion': string; 'appium:orientation': string; 'appium:clearSystemFiles': true; 'appium:autoGrantPermissions': true; }' is not assignable to type 'DesiredCapabilities | W3CCapabilities'.
  Object literal may only specify known properties, and ''appium:autoGrantPermissions'' does not exist in type 'DesiredCapabilities | W3CCapabilities'.ts(2322)
```

**Comment by christian-bromann** [comment]
You should use `appium:autoGrantPermissions` , I just pushed a fix to add that as type.
