### ISSUE TITLE
Edge capabilites not working

### ISSUE THREAD

**Issue by kundarsowjanya** [webdriverio/webdriverio#10231]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

16.20.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
edge
```

### What happened?

I updated all packages and if I run edge config I'm getting bellow error.

And also I have latest version of ms edge browser( 112.0.1722.48) but still I'm getting it supports only version 96.

webdriver: Request failed with status 500 due to Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: session not created: This version of MSEdgeDriver only supports MSEdge version 96
[0-0] Current browser version is 112.0.1722.48

### What is your expected behavior?

It should support new version of edge

### How to reproduce the bug.

 webdriver: Request failed with status 500 due to Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: session not created: This version of MSEdgeDriver only supports MSEdge version 96
[0-0] Current browser version is 112.0.1722.48 webdriver: Request failed with status 500 due to Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: session not created: This version of MSEdgeDriver only supports MSEdge version 96
[0-0] Current browser version is 112.0.1722.48

### Relevant log output

```typescript
webdriver: Request failed with status 500 due to Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: session not created: This version of MSEdgeDriver only supports MSEdge version 96
[0-0] Current browser version is 112.0.1722.48
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> This version of MSEdgeDriver only supports MSEdge version 96

As the error states your EdgeDriver and Edge browser don't have the same version which is required. Make sure you use a version of EdgeDriver that matches your browser version.

Join our  [Discord Channel](https://discord.webdriver.io) for these kind of questions. This is not necessary an issue.
