### ISSUE TITLE
[💡 Feature]: Sitespeed.io integration 

### ISSUE THREAD

**Issue by salvag-ntt** [webdriverio/webdriverio#10232]
### Is your feature request related to a problem?

No, more a missing opportunity.

### Describe the solution you'd like.

Currently WDIO integrates well with Google Lighthouse, which is great, but that only supports Chrome (or Chromium based browsers at best?)
Scanning performance of a web application, sometimes can be challenging because some pages might not directly be accessible via direct url, so user or automation tool needs to get there performing actions

### Describe alternatives you've considered.

Looks like Sitespeed.io supports multiple browsers, it's written in Javascript and works with Webdriver protocol.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Can you describe how such an integration could look like? For someone who never used sitespeed.io how could it help me to do performance testing with WebdriverIO?

**Comment by salvag-ntt** [comment]
Hey @christian-bromann thanks for your interest in this (and apologies for the late reply). So, as far as I can see, from a quick look into Sitespeed.io (so far I have only used it for static pages, you pass a link, it scans it and gives the result) there is a whole support for actions and commands as you can see in the scripting section, which is meant to support user journeys (https://www.sitespeed.io/documentation/sitespeed.io/scripting/)
What I was thinking is one of these two options (and others are of course welcome):

1. Grab the Webdriver client and pass it to Sitespeed.io, then use all the Sitespeed commands. This is not actually even an integration, it's just making sure Sitespeed can  use the webdriver protocol created by Webdriver.io
2. Much more interesting is a wrapper around Sitespeed.io commands, albeit more complex and potentially source of incompatibilities in the interface if things change on Sitespeed side.

Please @christian-bromann let me know if this at least makes some sort of sense. Happy to discuss further

**Comment by christian-bromann** [comment]
Thanks for clarification. I think this would be a wonderful thing to have, however I am not sure if it makes sense to integrate it into the core of the project. Here is what I am thinking: we can bootstrap a new project in the [WebdriverIO Community](https://github.com/webdriverio-community) organisation and create a service for this, e.g. `wdio-sitespeed-service`. This would implement one of the options and could be used by anyone.

@salvag-ntt let me know if you are interested to work on this and I am happy to set-up the project for you and invite you to the organisation.

Happy to discuss this further. I will close this because there is nothing actionable for this repository.

**Comment by salvag-ntt** [comment]
@christian-bromann totally agree, definitely wanted to adopt a plugin style (or service to use the WDIO "namespace" 😃 )
I would be happy to give it a go but I would prefer to use my personal account (@giuseppe-salvatore) so that I can do this when I have time outside of working hours. 
I am not sure how long this will take as it's first time I going deep into WDIO, but still it will be interesting to try.

**Comment by christian-bromann** [comment]
Sounds good. Let me know when you have something initially build together and I can create the community project set up.

**Comment by salvag-ntt** [comment]
Any sample on how to spin up a new service? I would need to look at a starting point that would help a lot.

**Comment by christian-bromann** [comment]
@salvag-ntt I recommend use https://github.com/webdriverio-community/wdio-edgedriver-service or similar services in this organisation as a start. They all come with a great set up for you to get started.
