### ISSUE TITLE
Question : Is it possible to pass capabilities on the cli via wdio?

### ISSUE THREAD

**Issue by dmfranko** [webdriverio/webdriverio#1025]
It seems that we can pass just about anything on the command line with the exception of the capabilities.  Is there a trick I'm just missing or this just not possible currently?  I'd be happy to look into trying to enable this if it's not possible as-is.

Thanks!
Dan

**Comment by monolithed** [comment]
You [can't](https://github.com/webdriverio/webdriverio/blob/master/lib/cli.js#L256-L262)

**Comment by christian-bromann** [comment]
No you can't set capabilities using cli arguments but you can set environment variables and read these:

```sh
§ _BROWSER=firefox wdio wdio.conf.js
```
in you config do
```js
// ...
capabilities: [{
    browserName: process.env._BROWSER || 'chrome'
}],
// ...
```

**Comment by srajagopalan1712** [comment]
If I have some tests to run in headless mode (api tests) and some in UI mode I would like to pass capabilities args as args: ['--headless']. Is this how that will work with the env variable?

args: process.env.args,
and cli will be $npm test args=['--headless']
?

**Comment by Hariks21** [comment]
> ```js
> process.env._BROWSER
> ```

is it working? for me no!
