### ISSUE TITLE
[🐛 Bug]: browser services using `getPort` have issues running in Node v20

### ISSUE THREAD

**Issue by aadiene** [webdriverio/webdriverio#10264]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest (8)

### Node.js Version

latest (20)

### Electron Version

latest (24)

### Electron-chromedriver Version

latest (24)

### Mode

WDIO Testrunner

### Which capabilities are you using?

```
services: [
    [
	'electron',
	{
		binaryPath: electronPath,
		chromedriver: {
			chromedriverCustomPath: chromedriverPath,
		},
	},
    ],
],
```

### What happened?

On node 16, e2e tests are executed successfully without error message
On node 18, e2e tests are executed successfully without error message
On node 20, e2e tests are skipped without error message

### What is your expected behavior?

On node 16, e2e tests are executed successfully without error message
On node 18, e2e tests are executed successfully without error message
On node 20, e2e tests are executed successfully or failing with an error message

### How to reproduce the bug.

With node 20

```
git clone https://github.com/aadiene/wdio8-node20.git

npm install

npm run wdio
```

### Relevant log output

```typescript
npm run wdio             

> wdio
> wdio run ./wdio.conf.ts


Execution of 1 workers started at 2023-04-25T22:43:56.152Z



Ended WebDriver sessions gracefully after a SIGINT signal was received!
2023-04-25T22:43:56.202Z INFO @wdio/local-runner: Shutting down spawned worker
2023-04-25T22:43:56.359Z INFO chromedriver: Initiate Chromedriver Launcher (v8.1.1)
2023-04-25T22:43:56.360Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-04-25T22:43:56.360Z INFO chromedriver: Start Chromedriver (/github/wdio8-node20/node_modules/.bin/chromedriver) with args --port=9515 --url-base=/
2023-04-25T22:43:56.455Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-04-25T22:43:56.456Z INFO @wdio/local-runner: shutting down

```

My guess => Worker(s) shut down before tests

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@aadiene please always always 🙏 provide log messages, no one can guess what is going on

**Comment by aadiene** [comment]
@christian-bromann, I updated the issue with logs I have (not very much I am afraid). 
I provided also a reproducible example on [github](https://github.com/aadiene/wdio8-node20.git).

**Comment by christian-bromann** [comment]
It looks like the process shuts down when the Chromedriver service calls `tcpPortUsed.waitUntilFree`. Not sure why that is but it doesn't seem like WebdriverIO is responsible for it. I would not recommend to use Node.js v20 just yet due to issues like that. Don't expect this to be picked up by active contributors as they have their own priorities. If you depend on this bug to be fixed, your contribution is required. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) or join our [Discord](http://discord.webdriver.io/) development server and let us know if you have any questions. Cheers!

**Comment by aadiene** [comment]
My apps are currently running very well on node 16 and 18. Just wanted contributors to be aware of this issue. 
Thanks for your feedback.

**Comment by christian-bromann** [comment]
To clarify though: this is unlikely an issue within WebdriverIO as the process quits while waiting on Chromedriver to be booted.

**Comment by dinocraftz** [comment]
I had the same issue with node -version 20.0.0 nothing would boot including Appium then I downgraded v18.16.0(node LTS). Everything worked again.

**Comment by christian-bromann** [comment]
Moved to https://github.com/webdriverio-community/wdio-chromedriver-service/issues/294
