### ISSUE TITLE
wdio.conf.js hooks and promise errors

### ISSUE THREAD

**Issue by vvo** [webdriverio/webdriverio#1028]
I am using the onPrepare hook and when the returned promise rejects there's no error report.

I think we should throw in case of the onPrepare hook is returning a promise rejection? (and all other hooks)

Thanks

**Comment by christian-bromann** [comment]
This is already considered and implemented in v4. We will release that version soon.

**Comment by jamesseanwright** [comment]
@vvo for the time being, I've been able to work around a similar issue by subscribing to `process`' `unhandledRejection` event.

https://nodejs.org/api/process.html#process_event_unhandledrejection
