### ISSUE TITLE
[🐛 Bug]: Type 'string' is not assignable to type 'WebdriverIO'

### ISSUE THREAD

**Issue by noahgregory-avanade** [webdriverio/webdriverio#10286]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

2.0.0-beta.66

### Node.js Version

19.8.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
    platformName: 'Android',
    'appium:automationName': 'UiAutomator2',
    'appium:appPackage': 'com.android.settings',
    'appium:appActivity': '.Settings'
}
```

### What happened?

Using the above capabilities with TypeScript 5.0.2 results in the type error `Type 'string' is not assignable to type 'WebdriverIO'.` for each key of the capabilities. Removing the `appium:appActivity` key resolves this issue.

It appears that: 
- the `appium:appActivity` key is not in the type(s) for `capabilities`, and
- the type(s) for `capabilities`, for some reason, start to enforce a key type of `WebdriverIO` if an unfamiliar key is present

### What is your expected behavior?

There is no type error.

### How to reproduce the bug.

Use the following code:

```ts
import type { RemoteOptions } from 'webdriverio';

import { remote } from "webdriverio";

const capabilities: RemoteOptions['capabilities'] = {
    platformName: 'Android',
    'appium:automationName': 'UiAutomator2',
    'appium:appPackage': 'com.android.settings',
    'appium:appActivity': '.Settings',
}

const remoteOpts: RemoteOptions = {
    hostname: '0.0.0.0',
    port: 4723,
    capabilities,
}

const sampleTest = async () => {
    const driver = await remote(remoteOpts);
    console.info(driver);
}

sampleTest();
```

### Relevant log output

```typescript
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

I think we should allow to have all [`AppiumAndroidCapabilities`](https://github.com/webdriverio/webdriverio/blob/76d6b5cb7da67b9b927a1db9a5a39d273d400b9b/packages/wdio-types/src/Capabilities.ts#L518) with an `appium:` prefix as well. This should be possible to define with a TS loop.

Any contributions that resolves the bug are highly appreciated. Don't expect this to be picked up by active contributors as they have their own priorities. If you depend on this bug to be fixed, your contribution is required. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) or join our [Discord](http://discord.webdriver.io/) development server and let us know if you have any questions. Cheers!

**Comment by noahgregory-avanade** [comment]
Thank you so much for the prompt response! I will look into it.
