### ISSUE TITLE
Provide a clear API on how to target cloudservices

### ISSUE THREAD

**Issue by vvo** [webdriverio/webdriverio#1029]
Currently the guide advise people to just put they user and key no matter what the cloud service is without saying much more.

So as a user here's how I felt: "I have a saucelabs account, so there must be somewhere I need to say type: saucelabs" But could not find such configuration entry, so after putting user and key (and removing the hub configuration, it worked. Thanks to our magical user and key detection of cloud services.

But still I felt like "Uh?" because being magical in the configuration file do not help reduce the FUD, it raises it.

I would prefer something like:

wdio.conf.js
```js
{
  cloud: {
    service: 'saucelabs' // testingbot, browserstack,
    user:,
    key
  }
}
```

What do you think?

**Comment by christian-bromann** [comment]
Let's merge this issue with #993
