### ISSUE TITLE
[📖 Docs]: <title>

### ISSUE THREAD

**Issue by swathiraj85** [webdriverio/webdriverio#10309]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Missing documentation

### Description of the improvement / report

The Configuration-> Capabilities section in the WebdriverIO Docs does not include information about UFT Mobile Center, a mobile application testing platform to test the mobile applications on various devices and operating systems, both on-premises and in the cloud.

Can the Cloud Vendor Capability Extensions header be updated to include the specific capabilities of UFT Mobile Center?

The link has further details about the capabilities .
https://admhelp.microfocus.com/digitallab/en/2022/Content/Appium/Appium_Capabilities.htm

I can help with the submission if that helps.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
> The Configuration-> Capabilities section in the WebdriverIO Docs does not include information about UFT Mobile Center, a mobile application testing platform to test the mobile applications on various devices and operating systems, both on-premises and in the cloud.

Please understand that we can't run after every cloud vendor that comes up with special capabilities. If they contribute docs to the project we are happy to merge it. In https://webdriver.io/docs/capabilities#cloud-vendor-capability-extensions you see we mention `Cloud Vendor Capability Extensions` and say that there are `many more...`. Feel free to add a link to the UFT Mobile Center docs in similar fashion to how other cloud vendors are mentioned here.
