### ISSUE TITLE
[🐛 Bug]: Allure reporter adding environment value overwrites the last value

### ISSUE THREAD

**Issue by m4hdyar** [webdriverio/webdriverio#10321]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

v16.13.2

### Mode

WDIO Testrunner

### What happened?

When using allureReporter.addEnvironment() the new value overwrites the last value.

The problem comes from https://github.com/webdriverio/webdriverio/blob/f0c607340b4f31a4ae48509115335283f488e38f/packages/wdio-allure-reporter/src/reporter.ts#L740.

I guess the reason is that in allure reporter you should now set all environment variables at once as it is a `Record<string,string>`, which makes IMHO also sense.

### What is your expected behavior?

I have two approaches to solve the problem, and I'm happy to implement whichever one the community prefers.

1. Setting all variables in wdio.conf in the reporter configuration is the first approach. Normally, you would not/should not change environment variables during the tests. So IMHO something like this makes sense:
```
reporters: [['allure', {
    outputDir: 'allure-results',
    environment: [
        a:'a',
        b:'b'
    ]
}]],
```
2. Changing `addEnvironment(name: string, value: string)` to `setEnvironment(Record<string,string>)` is the second approach.

The second one is more flexible, but in my opinion, the first one is the right approach because the second one opens the door to mistakes and makes it possible to overwrite the environment variable information.

### How to reproduce the bug.

Just write this anywhere in your test:
```
allureReporter.addEnvironment('d', 'c');
allureReporter.addEnvironment('a', 'b');
```
### Relevant log output

```typescript
a b
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by epszaw** [comment]
So, I definitely break the functionality during migration to the latest allure version.

Of course, I can return the behavior as it was, but the better approach to set the variables on config/process level.

If we still need to have ability to set env info on test level, how do we need to handle the info because it'll be store globally for the whole report.

For example, we want to set `{ foo: 1 }` in test `A`, but in test `B` we decided to set `{ foo: 2 }`. Which one do we expect?

**Comment by christian-bromann** [comment]
@m4hdyar any comment?

**Comment by hardikchotaliya** [comment]
@epszaw, Is there a way to prevent such an issue of overwriting Environment variables? Would it be possible for you to provide an approach that resolves this issue?

**Comment by m4hdyar** [comment]
- @christian-bromann I think setting it in the configuration file makes sense. I will pick this up.
