### ISSUE TITLE
[🐛 Bug]: Version collison with execa package

### ISSUE THREAD

**Issue by LuoKevin** [webdriverio/webdriverio#10326]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

@wdio/cli@8.10.0

### Node.js Version

19.6.0

### Mode

WDIO Testrunner

### What happened?

When running the wdio testrunner for e2e js tests, the following error occurs

Error file:///Users/**/Documents/**/@wdio/cli/build/utils.js:15
import { $ } from 'execa';
         ^
SyntaxError: The requested module 'execa' does not provide an export named '$'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)

I am noticing that wdio cli uses version `^7.0.0`. The error does not occur when running `@wdio/cli@8.8.7`

### What is your expected behavior?

My e2e tests to run smoothly

### How to reproduce the bug.

Run the wdio test runner on `@wdio/cli` version 8.10.0. 

### Relevant log output

```typescript
Error file:///Users/**/Documents/**/@wdio/cli/build/utils.js:15
import { $ } from 'execa';
         ^
SyntaxError: The requested module 'execa' does not provide an export named '$'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@LuoKevin can you please provide a reproducible example?

**Comment by LuoKevin** [comment]
wasn't an issue with the wdio library
