### ISSUE TITLE
[💡 Feature]: Add support for web extensions for Safari

### ISSUE THREAD

**Issue by AnikoBorosova** [webdriverio/webdriverio#10347]
### Is your feature request related to a problem?

Similarly to Chrome and Firefox, a support for adding and configuring web extensions for `Safari` would be very helpful for those who want to automate tests for their web extension product that supports all major browsers.

### Describe the solution you'd like.

A documented way of adding and configuring web extensions for Safari.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Thanks for reporting!

Unfortunately loading web extensions in Safari is either currently not possible or not well documented in general. I at least haven't found a way. Any hints would be appreciated.

Any contributions that resolves the bug are highly appreciated. Don't expect this to be picked up by active contributors as they have their own priorities. If you depend on this bug to be fixed, your contribution is required. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) or join our [Discord](http://discord.webdriver.io/) development server and let us know if you have any questions. Cheers!

**Comment by AnikoBorosova** [comment]
@christian-bromann Thank you for the answer and the added info!

I only know about this piece of documentation but not sure how up-to-date it is, or if it even works :
 https://www.javadoc.io/static/org.seleniumhq.selenium/selenium-safari-driver/2.37.1/org/openqa/selenium/safari/SafariOptions.html

**Comment by christian-bromann** [comment]
It seems like installing extensions has been added to the WebDriver Bidi scope: https://github.com/w3c/webdriver-bidi/pull/421

**Comment by christian-bromann** [comment]
Since there is nothing we can do about this here in this project, I will go ahead and close this.
