### ISSUE TITLE
Issue with moveTo(Object)?

### ISSUE THREAD

**Issue by plessbd** [webdriverio/webdriverio#1035]
I am tryng to get moveTo to work, but I am running into an error
here is some example code, it is not exactly what I am doing but is close, I am running javascript to actually find the element since in my project I do not have an easy to use selector

I cant figure out if I am doing something wrong of if I have found a bug.

using moveTo
```
describe("Open google", function(){
	it("Click Logo", function(done){
		browser.url("http://www.google.com/")
			.element("#hplogo")
			.click().pause(5000).call(done);
		});
		it("Click Search", function(done){
			browser

			.execute("return document.getElementById('lst-ib')")
			.moveTo()
			.click()
			.pause(5000)
			.call(done);
	});
})
```
output:
```
[20:08:04]:  SET SESSION ID 71998ec5-ec81-4fb4-a71e-2d3663b17ac4
Open google
  ✓ Click Logo (6391ms)
[20:08:11]:  ERROR	ServerError	number or type of arguments don't agree with moveTo command
ProtocolError: number or type of arguments don't agree with moveTo command
    at pause(5000) - indes.js:13:5
  1) Click Search


1 passing (9.20s)
1 failing

1) Click Search:
number or type of arguments don't agree with moveTo command
running chrome
ProtocolError: number or type of arguments don't agree with moveTo command
```
using moveToObject
```
describe("Open google", function(){
	it("Click Logo", function(done){
		browser.url("http://www.google.com/")
			.element("#hplogo")
			.click().pause(5000).call(done);
		});
		it("Click Search", function(done){
			browser

			.execute("return document.getElementById('lst-ib')")
			.moveToObject()
			.click()
			.pause(5000)
			.call(done);
	});
})

```
output:
```
[20:10:21]:  SET SESSION ID 91d40575-c005-436d-9b6e-b26782b2b11f
Open google
  ✓ Click Logo (6392ms)
[20:10:27]:  ERROR	ServerError	selector needs to be typeof `string`
ProtocolError: selector needs to be typeof `string`
    at element() - click.js:29:17
    at moveTo("1", 0, 0) - moveToObject.js:63:25
  1) Click Search


1 passing (8.70s)
1 failing

1) Click Search:
selector needs to be typeof `string`
running chrome
ProtocolError: selector needs to be typeof `string`
    at moveTo("1", 0, 0) - moveToObject.js:63:25
```

**Comment by plessbd** [comment]
so i figured out my issue.  It seems I cannot chain moveToObject.
moveToObject does not return the object moved to, so I have to rerun my element command.

I was also reading the stacktrace wrong, since it clearly says the error is in click.js and not movetoobject.

I do have another question though.  in my example, how would I pass an offset to moveToObject?

**Comment by christian-bromann** [comment]
Check out http://webdriver.io/api/action/moveToObject.html. The 2nd and 3rd parameter is x and y offset.

**Comment by fredguest** [comment]
@christian-bromann Is there a way to click an element at a specific X/Y offset, rather than the default location of the center of the element? I need to test clicking a modal overlay, which takes up the entire size of the viewport, so the center of the overlay is the center of the viewport, and the center of the viewport is occupied by another element, the modal itself, so currently, this code `client.click('.Modal-overlay')` actually clicks a different element. What I need to do is click the upper left corner of the modal overlay for example.

**Comment by ipranavpatel** [comment]
@christian-bromann @fredguest Do you find any answer of "Is there a way to click an element at a specific X/Y offset?" My application requires to click on specific X/Y offset of canvas element.

**Comment by fredguest** [comment]
@ipranavpatel @christian-bromann nope. just hacking around it for now by manually targeting and hiding the element that is in the way of the element we are trying to click.
