### ISSUE TITLE
[🐛 Bug]: ag-grid scrollIntoView bad alignement in v8

### ISSUE THREAD

**Issue by talbss** [webdriverio/webdriverio#10369]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.10.1

### Node.js Version

v16.14.0

### Mode

WDIO Testrunner

### What happened?

Cell location before scrollIntoView on it

![image](https://github.com/webdriverio/webdriverio/assets/6849441/42baf803-0139-433a-97b0-11db0ef0c553)

Bad alignment to parent when using scrollIntoView on an ag-grid cell on wdio v8.

![image](https://github.com/webdriverio/webdriverio/assets/6849441/d9f88c17-6c8d-4130-99b5-afab45e2f79d)

### What is your expected behavior?

Same alignement to its parent as in wdio v7
![image](https://github.com/webdriverio/webdriverio/assets/6849441/ffefe56b-2001-45b1-8aa5-9e5a43d62215)

### How to reproduce the bug.

**Repo to reproduce the issue:**
https://github.com/talbss/wdio-v8-gridRow-ScrollIntoView

npm i
npm run wdio

**Repo to get the reference correct behavior**
https://github.com/talbss/wdio-v7-gridRow-ScrollIntoView

npm i
npm run wdio

### Relevant log output

In v8 (with issue) we have the following:

**ag-grid first row first cell location after scrollIntoView() on first row locator:**
`[0-0] firstRowfirstCellLocationAfterFirstRowScrollIntoView: '{"x":0,"y":368}'
`
**ag-grid first row first cell location after scrollIntoView() on first row first cell locator:**
`[0-0] firstRowFirstCellLocationAfterFirstRowFirstCellScrollIntoView: '{"x":0,"y":0}'
`
we should have here the same coordinates after the 2 scrollIntoView (cell and its parent row). and we should have the same as in v7 for the same grid (see hereunder), so x whould not be 0 after the first scrollIntoView

In v7 (without issue) we have the following:

**ag-grid first row first cell location after scrollIntoView() on first row locator:**
`[0-0] firstRowfirstCellLocationAfterFirstRowScrollIntoView: '{"x":17,"y":326}'
`
**ag-grid first row first cell location after scrollIntoView() on first row first cell locator:**
`[0-0] firstRowFirstCellLocationAfterFirstRowFirstCellScrollIntoView: '{"x":17,"y":326}'
`
we can see here that the coordinates are the same after the 2 scrollIntoView. and x is not 0!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!



Any contributions that resolves the bug are highly appreciated. Don't expect this to be picked up by active contributors as they have their own priorities. If you depend on this bug to be fixed, your contribution is required. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) or join our [Discord](http://discord.webdriver.io/) development server and let us know if you have any questions. Cheers!

**Comment by bernardobelchior** [comment]
I have experienced this bug as well. Our solution was to use `browser.execute()` to call `scrollIntoView` directly from the browser.

**Comment by christian-bromann** [comment]
> I have a similar bug with scrollIntoView:

This is not a bug @joao-motork , it is a fallback in case the action doesn't work.

**Comment by christian-bromann** [comment]
This has likely to do with the fact that our action implementation of `scrollIntoView` takes the whole viewport into account instead of just the table. I can see two options:

- have the command find any parent element that has a `overflow: scroll` style property and use that element as target when calculating the scroll heights
- allow to pass in an argument to the method that specifies the target boundaries (so no auto detection is required)

It is absolutely fine to use the web APIs for this.

We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by bernardobelchior** [comment]
@christian-bromann is there a reason not to use the browser's `scrollIntoView` directly?

**Comment by rashiq231** [comment]
> * allow to pass in an argument to the method that specifies the target boundaries (so no auto detection is required)

@christian-bromann , could you please add few more details of what is expected? below are my few queries

1. what does the target boundaries represent, is it X, Y co-ordinates of pixels or an element given by user, from which X, Y are calculated
2. So, when the boundaries are set does that mean that, the origin position has to be shifted to the given boundary and all the calculations should be done from the new value?

example- current Origin is (0,0), when given a new boundary, say new Origin(17, 326)
scrollIntoView({block:"start", inline: "nearest"}) would scroll the element to (17,326) instead of Old Origin(0,0)

**Comment by christian-bromann** [comment]
> 1. what does the target boundaries represent, is it X, Y co-ordinates of pixels or an element given by user, from which X, Y are calculated

We could just accept an WebdriverIO element and calculate the boundaries ourselves.

> 2\. So, when the boundaries are set does that mean that, the origin position has to be shifted to the given boundary and all the calculations should be done from the new value?

Yes, instead of taking the whole viewport as boundary we have to take the boundary of the given element.

**Comment by christian-bromann** [comment]
@rashiq231 can you verify if this error still exist after recent updates?

**Comment by viper3400** [comment]
I'm somehow bugged by this issue, as well.

@christian-bromann: I used the repo (https://github.com/talbss/wdio-v8-gridRow-ScrollIntoView) provided by @talbss and updated the dependencies to 8.16.4 (resp. 8.16.3) but the behaviour in this repo still exists (and  as well in the project where I am bugged).

**Comment by rsshilli** [comment]
I created my own scrollIntoView (thank you @christian-bromann for the pointer on Discord). This might help others. The browser has a `scrollIntoView` that worked perfectly for me.

```
/**
 * Scroll to center seems to be broken in WebDriver 8 (ex. the header may be blocking the view), so this method uses 
 * the browser scrolling.
 *
 * See  https://github.com/webdriverio/webdriverio/issues/10369 and https://github.com/webdriverio/webdriverio/issues/9805
 * @param element The element (found from browser.$())
 * @param options Options that you want to pass to element.scrollIntoView()
 */
async function scrollElementIntoView(element, options, browserParam) {
  const thisBrowser = exports.getBrowser(browserParam);

  // In a table, the WebDriver.io v8 logic doesn't work sometimes, so we use the browser's logic and if that doesn't work, we fall back to the Webdriver logic.
  await thisBrowser.execute((elem, options) => elem.scrollIntoView(options), element, options);

  let isElementInView = await element.isDisplayedInViewport();
  if (!isElementInView) {
    await element.scrollIntoView(options);
  }
};
```

**Comment by christian-bromann** [comment]
@rsshilli there is a PR by @erwinheitzman (#11120) with improvements on the command but your approach is totally legit too. The reason we use the WebDriver Actions API for it instead of the Web API as you showed is that the actions API emits scroll events and mimics the user closer.

**Comment by viper3400** [comment]
@christian-bromann , after updating the repo that was referenced in the description of this issue to 8.16.6 the problem has gone. As well in the project I encountered it myself. 👍
