### ISSUE TITLE
💡 Feature: Move mochawesom reporter here

### ISSUE THREAD

**Issue by xwmyth8023** [webdriverio/webdriverio#10364]
### Is your feature request related to a problem?

The [wdio-mochawesome-reporter](https://github.com/fijijavis/wdio-mochawesome-reporter) doesn't update any more and is not compatible with the latest wdio version

### Describe the solution you'd like.

Move the project here and make it compatible with the latest wdio version

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Duplicate of https://github.com/fijijavis/wdio-mochawesome-reporter/issues/68
