### ISSUE TITLE
Element with certain text selector not respecting element chaining scope

### ISSUE THREAD

**Issue by chewy2** [webdriverio/webdriverio#1038]
I've been trying the example chain selecor located in http://webdriver.io/guide/usage/selectors.html and the code example does not work as expected. I modified the html so that the buttons onclick will console log 'button 1', 'button 2', or 'button 3' based on their row entry. 

When I try to run 

` client.element('.row .entry:nth-Child(2)').click('button*=Add');`

In the console log it only displays 'button 1' instead of the expected value 'button 2'. Console logging what the click command retrieves reveals that the click selector returns an array of all 3 buttons and isn't being scoped to the row that the element retrieves.

**Comment by christian-bromann** [comment]
can you provide the WebdriverIO log output or Selenium log?

**Comment by chewy2** [comment]
I'm not 100% certain how to obtain the log file you're requesting. Are you talking about the output from the selenium terminal this is it

15:26:23.430 INFO - Executing: [find element: By.cssSelector: .row .entry:nth-Child(1)])
15:26:23.443 INFO - Done: [find element: By.cssSelector: .row .entry:nth-Child(1)]
15:26:23.446 INFO - Executing: [find child element: 0 [[FirefoxDriver: firefox on MAC (526eaebe-f2ad-5c4f-82cf-c7243ac858bd)] -> css selector: .entry], By.xpath: //button[contains(., "Add")]])
15:26:23.453 INFO - Done: [find child element: 0 [[FirefoxDriver: firefox on MAC (526eaebe-f2ad-5c4f-82cf-c7243ac858bd)] -> css selector: .entry], By.xpath: //button[contains(., "Add")]]
15:26:23.462 INFO - Executing: [click: 3 [[[[FirefoxDriver: firefox on MAC (526eaebe-f2ad-5c4f-82cf-c7243ac858bd)] -> css selector: .entry]] -> xpath: //button[contains(., "Add")]]])
15:26:23.524 INFO - Done: [click: 3 [[[[FirefoxDriver: firefox on MAC (526eaebe-f2ad-5c4f-82cf-c7243ac858bd)] -> css selector: .entry]] -> xpath: //button[contains(., "Add")]]]

if its not could you please direct in how to obtain the requested logs?

**Comment by christian-bromann** [comment]
It seems that your query returns multiple elements and selenium picks per default first element it can find

**Comment by chewy2** [comment]
From the documentation it states if I use an "element" command I'm suppose to be able to chain selectors and maintain scope throughout the entire chain.

`client.element('.row .entry:nth-Child(2)')`

should have scoped it to the second ".entry" div and the "click" command should have searched only that div for a button to click. If I try to use this using purely CSS selectors I'm able to produce the expected results, but using a selector that looks for specific text it does not seem to work correctly and scans the entire DOM instead of using the previously scoped element.

Is the example on the site wrong and chaining is only supported for CSS selectors and not Element with certain text selectors?

**Comment by christian-bromann** [comment]
ahhh yeah it does actually because of the xPath we are using:

```js
//button[contains(., "Add")
```
Could you change your selector to this:
```js
client.element('.row .entry:nth-Child(2)').click('./button[contains(., "Add")');
```
We should fix this.

**Comment by chewy2** [comment]
I tried the new selector and I receive this following error.

{ [Error: The given selector ./button[contains(., "Add") is either invalid or does not result in a WebElement. The following error occurred:
InvalidSelectorError: Unable to locate an element with the xpath expression ./button[contains(., "Add") because of the following error:
SyntaxError: The expression is not a legal expression.
For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'Stanleys-MacBook-Pro.local', ip: '10.0.1.23', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.1', java.version: '1.8.0_65'
Driver info: driver.version: unknown]
  message: 'The given selector ./button[contains(., "Add") is either invalid or does not result in a WebElement. The following error occurred:\nInvalidSelectorError: Unable to locate an element with the xpath expression ./button[contains(., "Add") because of the following error:\nSyntaxError: The expression is not a legal expression.\nFor documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html\nBuild info: version: \'2.48.2\', revision: \'41bccdd\', time: \'2015-10-09 19:59:12\'\nSystem info: host: \'Stanleys-MacBook-Pro.local\', ip: \'10.0.1.23\', os.name: \'Mac OS X\', os.arch: \'x86_64\', os.version: \'10.10.1\', java.version: \'1.8.0_65\'\nDriver info: driver.version: unknown',
  type: 'RuntimeError',
  seleniumStack: 
   { status: 32,
     type: 'InvalidSelector',
     message: 'Argument was an invalid selector (e.g. XPath/CSS).',
     orgStatusMessage: 'The given selector ./button[contains(., "Add") is either invalid or does not result in a WebElement. The following error occurred:\nInvalidSelectorError: Unable to locate an element with the xpath expression ./button[contains(., "Add") because of the following error:\nSyntaxError: The expression is not a legal expression.\nFor documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html\nBuild info: version: \'2.48.2\', revision: \'41bccdd\', time: \'2015-10-09 19:59:12\'\nSystem info: host: \'Stanleys-MacBook-Pro.local\', ip: \'10.0.1.23\', os.name: \'Mac OS X\', os.arch: \'x86_64\', os.version: \'10.10.1\', java.version: \'1.8.0_65\'\nDriver info: driver.version: unknown' } }

**Comment by christian-bromann** [comment]
Please try
```js
client.element('.row .entry:nth-Child(2)').click('/button[contains(., "Add")');
```

**Comment by chewy2** [comment]
I noticed the problem. In your first command

`client.element('.row .entry:nth-Child(2)').click('./button[contains(., "Add")');`

theres a missing closing ']'. I added this in and it works correctly. Thank you for your help.

**Comment by christian-bromann** [comment]
ohh indeed.
