### ISSUE TITLE
[🐛 Bug]: @wdio-junit-reporter working on mac os x but not windows

### ISSUE THREAD

**Issue by OluJS** [webdriverio/webdriverio#10391]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8

### Node.js Version

18.16.0

### Mode

WDIO Testrunner

### What happened?

On my mac os x device, I'm able to get generate a populated junit report using the @wdio/junit-reporter reporter. However, cloning the same repo on a windows machine results in an 'empty' junit report.

### What is your expected behavior?

For the junit reporter to return test results when running on a windows machine

### How to reproduce the bug.

To reproduce this bug, you can clone the following repository, install the node_modules by running `npm i` and then run the tests using `npm run wdio`.

The repository -> https://github.com/OluJS/WebdriverIO-JUnit

Or you can just setup a new wdio project and choose junit as one of the reporter options

### Relevant log output

```typescript
mac os x junit report output:
 "junit" Reporter:
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="The Internet Guinea Pig Website" timestamp="2023-05-15T22:22:27" time="2.991" tests="2" failures="0" errors="0" skipped="0">
    <properties>
      <property name="specId" value="0"/>
      <property name="featureName" value="The Internet Guinea Pig Website"/>
      <property name="capabilities" value="chrome.113_0_5672_92.macosx"/>
      <property name="featureFile" value="file://./features/login.feature"/>
    </properties>
    <testcase classname="CucumberJUnitReport-chrome.113_0_5672_92.macosx.The Internet Guinea Pig Website" name="As a user I can log into the secure area" time="2.135">
      <system-out><![CDATA[
✅ Given I am on the login page✅ When I login with tomsmith and SuperSecretPassword!✅ Then I should see a flash message saying You logged into a secure area!
]]></system-out>
    </testcase>
    <testcase classname="CucumberJUnitReport-chrome.113_0_5672_92.macosx.The Internet Guinea Pig Website" name="As a user I can log into the secure area" time="0.838">
      <system-out><![CDATA[
✅ Given I am on the login page✅ When I login with foobar and barfoo✅ Then I should see a flash message saying Your username is invalid!
]]></system-out>
    </testcase>
  </testsuite>
</testsuites>


windows output:
 "junit" Reporter:
<?xml version="1.0" encoding="UTF-8"?>
<testsuites/>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!



Any contributions that resolves the bug are highly appreciated. Don't expect this to be picked up by active contributors as they have their own priorities. If you depend on this bug to be fixed, your contribution is required. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) or join our [Discord](http://discord.webdriver.io/) development server and let us know if you have any questions. Cheers!

**Comment by christian-bromann** [comment]
@OluJS have you been able to look into this?

**Comment by OluJS** [comment]
@christian-bromann I've attempted to but with no result. I must admit, I'm probably not the best person knowledge-wise to dig through this
