### ISSUE TITLE
Using the selenium-standalone service with Safari Technology Preview results in error

### ISSUE THREAD

**Issue by AnikoBorosova** [webdriverio/webdriverio#10395]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.13

### Node.js Version

16.17.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
path: '/wd/hub',
hostname: 'localhost',
port: 4444,
capabilities: [
    {
      maxInstances: 1,
      browserName: 'safari technology preview',
],
services: [
    ['selenium-standalone']
 ],
```

### What happened?

I was trying to setup the `selenium-standalone` service to work with `Safari Technology Preview` on MacOS Ventura (13.3.1 (a).

Based on closed tickets I gathered the info that it is possible to use WebdriverIO with STP, but it was not clear if it is possible with the `selenium-standalone` service as well.

I tried different configurations and syntaxes of the capabilities object, but ran into errors.

Version 1: 
```
capabilities: [
    {
      maxInstances: 1,
      browserName: ‘safari technology preview’,
}
```
This never opened the browser, it seems that it loads infinitely. 
The error I'm getting: 
```
2023-05-16T15:00:02.667Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
2023-05-16T15:00:02.667Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'safari technology preview' },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'safari technology preview' }
}
2023-05-16T15:02:02.694Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
```

Version 2:

```
capabilities: [
    {
      maxInstances: 1,
      browserName: ‘safari’,
      'safari.options': {
            technologyPreview: true
      }
]
```
Error: `Request failed with status 500 due to Illegal key values seen in w3c capabilities: [safari.options]`

Version 3:
```
capabilities: [
    {
      maxInstances: 1,
      browserName: ‘safari’,
      safariOptions: {
        technologyPreview: true
      }
]
```
Error: `Request failed with status 500 due to Illegal key values seen in w3c capabilities: [safariOptions]`

I was also trying to start the safaridriver of Safari Technology Preview with the command:
`/Applications/Safari\ Technology\ Preview.app/Contents/MacOS/safaridriver -p 4444`

This also resulted in an error due to the port being occupied.

### What is your expected behavior?

The goal would be to run automated tests on Safari Technology Preview with the `selenium-standalone service` with the correct configuration.

### How to reproduce the bug.

For more capabilities syntax variations see the `What happened` section.

const config = {

...

  connectionRetryTimeout: 120000,
  connectionRetryCount: 3,

  path: '/wd/hub',
  hostname: 'localhost',
  port: 4444,
  capabilities: [
    {
      maxInstances: 1,
      browserName: 'safari technology preview',
     }
  ],
  services: [
    ['selenium-standalone']
  ],

...

};

exports.config = config;

### Relevant log output

```typescript
For error logs for each variations see the `What happened` section.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Using `safari.options` is not valid anymore. To start Safari in Technology preview set `browserName: "Safari Technology Preview"`.

**Comment by AnikoBorosova** [comment]
@christian-bromann I tried with your suggestion, but still not working.

The only log I'm getting is
```
2023-05-16T16:54:37.372Z DEBUG @wdio/utils:initialiseServices: initialise service "selenium-standalone" as NPM package
2023-05-16T16:54:37.425Z INFO @wdio/cli:launcher: Run onPrepare hook
```

And the terminal says:
` ELIFECYCLE  Command failed with exit code 1.`

The browser itself never opens.

**Comment by christian-bromann** [comment]
There is not really that we can fix about this in WebdriverIO. I am happy to re-open if we can pin down an issue in WebdriverIO. Let me know if you find a way to get this running. Maybe try the `wdio-safaridriver-service`?

**Comment by AnikoBorosova** [comment]
Yes, I did manage to make this work with the `wdio-safaridriver-service` :) 

I used these settings:

```
hostname: 'localhost',
  port: 4444,
  path: '/',
  maxInstances: MAX_INSTANCES,
  capabilities: [{
    browserName: 'safari technology preview',
    port: 4444,
  }],
  services: [
    ['safaridriver', {
        outputDir: './logs',
        logFileName: 'wdio-safaridriver.log',
    }]
  ],
```

And before running the tests I also ran this command in a separate terminal window:
`/Applications/Safari\ Technology\ Preview.app/Contents/MacOS/safaridriver -p 4444`


But currently I'm looking at both services to see which one would fit best to our needs.

This is also why I asked this question on Discord about the `safaridriver-service`: https://discord.com/channels/1097401827202445382/1097674067601010709/1108036143682945025

Do you have any insight on this?
What does it mean that this service is a community-service and not officially listed in webdriverIOs documentation?
Would that mean any maintenance/security/etc issues on the long-run?

**Comment by christian-bromann** [comment]
> What does it mean that this service is a community-service and not officially listed in webdriverIOs documentation?

It should, mind raising a PR for it? Something similar to this: https://github.com/webdriverio/webdriverio/commit/bdf8a4f7ce9a07dc3308df0d28025352b732319f

> Would that mean any maintenance/security/etc issues on the long-run?

All community projects are as well maintained as the core projects.

**Comment by christian-bromann** [comment]
> I will raise a PR in the upcoming days.

I ended up pushing a fix for this adding the service to the docs: https://webdriver.io/docs/wdio-safaridriver-service

**Comment by AnikoBorosova** [comment]
Thank you!
