### ISSUE TITLE
[🐛 Bug]: Allure Reporter incorrectly marks tests as passed on before or beforeEach hook failure

### ISSUE THREAD

**Issue by HimanshuD-Groove** [webdriverio/webdriverio#10393]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.0.13

### Node.js Version

18.12.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  browserName: 'chrome',
  maxInstances: 1,
  acceptInsecureCerts: true,
}
```

### What happened?

I am using Mocha test framework with webdriverio and @wdio/allure-reporter. this is the behavior I see: 

Lets say I run following tests:
```
suite('Templates Golden Suite', () => {
  suiteSetup('Suite Setup', async () => {
	some.suiteSetup.logic();
});

  setup('Test Setup', async () => {
       some.setup.logic();
  });

  test(‘test1’, async () => {
    Some.test.steps();
    expect(some.value()).toBe(true);
  });
});
```

If for some reason `suite` or `suiteSetup` fails during test run. The test in my example `test1` is marked as passed in allure report which is incorrect.

### What is your expected behavior?

Test should be marked as failed as before or beforeEach hook failed.

### How to reproduce the bug.

suite('Templates Golden Suite', () => {
  suiteSetup('Suite Setup', async () => {
	some.suiteSetup.logic();
});

  setup('Test Setup', async () => {
       throw new Error("Throw this error on purpose");
  });

  test(‘test1’, async () => {
    Some.test.steps();
    expect(some.value()).toBe(true);
  });
});

### Relevant log output

```typescript
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!



Any contributions that resolves the bug are highly appreciated. Don't expect this to be picked up by active contributors as they have their own priorities. If you depend on this bug to be fixed, your contribution is required. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) or join our [Discord](http://discord.webdriver.io/) development server and let us know if you have any questions. Cheers!

**Comment by Amitesh** [comment]
I am also getting same issue with integration of TestDeck and I have reported there. :(
https://github.com/testdeck/testdeck/issues/384

**Comment by hemche** [comment]
@HimanshuD-Groove 
Can you throw `SevereServiceError` instead of `throw new Error`?

        throw new SevereServiceError('Something went wrong.')

More info here: https://webdriver.io/docs/customservices/#service-error-handling

**Comment by HimanshuD-Groove** [comment]
> @HimanshuD-Groove Can you use `throw SevereServiceError` instead of `throw new Error`?
> 
> ```
>     throw new SevereServiceError('Something went wrong.')
> ```
> 
> More info here: https://webdriver.io/docs/customservices/#service-error-handling

@hemche not sure how would that be helpful? What I gave was just an example to reproduce the issue. Test fail during normal operations and I see this issue.

**Comment by christian-bromann** [comment]
@Amitesh @HimanshuD-Groove any clues how this bug can be resolved? I've never used testdeck so I wouldn't be the right person to look into this. Happy to help with questions to the WebdriverIO code base though.

**Comment by piyush2903** [comment]
quick thought on this, Shouldn't be test marked as skipped if before or beforeEach hook fails?

**Comment by BorisOsipov** [comment]
@Amitesh @HimanshuD-Groove Is the bug still there? There are a few fixes in Allure Reporter that will probably fix this too.

**Comment by AnthonyQuy** [comment]
I created a test project with specs:

`import { expect } from '@wdio/globals'

suite('Templates Golden Suite', async() => {
    suiteSetup('Suite Setup', async () => {
        console.log("Suite Setup");
    });

    setup('Test Setup', async () => {
        console.log("Test Setup");
        throw new Error("Throw this error on purpose");
    });


    test("test1", async () => {
        console.log("Test 1");
        const some = true;
        expect(some).toBe(true);
    });

    test("test2", async () => {
        console.log("Test 2");
        const some = true;
        expect(some).toBe(true);
    });
});`

Then Allure result is:
![image](https://github.com/webdriverio/webdriverio/assets/19924396/38b9fed4-285f-488d-b921-6b70572e0df2)

Look like when the setup fail it also mark the test fail which probably acceptable behavior  but there're other concerns here:

- When we use Mocha tdd (suite, setup, test...) the allure result till display as bdd (before all, before each...)
- "test2" was ignored after test1 setup fail (without run the setup again for "test2") -> not sure if this is expected

Test project: https://github.com/AnthonyQuy/wdio-mocha-allure-issue

==> I think we can close this issue and open new one for the concerns if necessary

FYI @BorisOsipov @christian-bromann

**Comment by BorisOsipov** [comment]
>When we use Mocha tdd (suite, setup, test...) the allure result till display as bdd (before all, before each...)

I don't think Mocha itself cares about hook names and always names them in the BDD style for reporters. It has nothing to do with Allure Reporter.

>"test2" was ignored after test1 setup fail (without run the setup again for "test2") -> not sure if this is expected

I think it is how mocha works with hooks. It has nothing to do with Allure Reporter. If you have conserns it is better to ask in mocha support chanels.
