### ISSUE TITLE
[🐛 Bug]: <webdriverio> Incorrect JSDoc Info for default timeout value on waitUntil.ts 

### ISSUE THREAD

**Issue by SiNONiMiTY** [webdriverio/webdriverio#10392]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

18.16.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
Not relevant
```

### What happened?

The JSDoc information here states that the default value for options.timeout is set to 5000ms
https://github.com/webdriverio/webdriverio/blob/73666f523d9d9701fac4061a5a59b37ca97e7286/packages/webdriverio/src/commands/browser/waitUntil.ts#L13

However, while using waitUntil() method without passing the timeout option, I was expecting the timeout to be at 5000ms,
suddenly, an error was displayed on my test and I can see that it reported the test lapsed the 3000ms timeout.

I was pretty surprised so I browsed the default configuration and indeed, it is only set to 3000ms.
https://github.com/webdriverio/webdriverio/blob/73666f523d9d9701fac4061a5a59b37ca97e7286/packages/webdriverio/src/constants.ts#L171

### What is your expected behavior?

The default must be 5000ms or the JSDoc info must be updated

### How to reproduce the bug.

N/A

### Relevant log output

```typescript
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for raising an issue. A patch has been pushed and will be released in the next version of WebdriverIO.
