### ISSUE TITLE
[🐛 Bug]: wdio-chromedriver-service doc edit link is broken - 404

### ISSUE THREAD

**Issue by Amitesh** [webdriverio/webdriverio#10404]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### What happened?

I try to click the edit link for https://webdriver.io/docs/wdio-chromedriver-service this page on the website but it leads to 404.
<img width="876" alt="image" src="https://github.com/webdriverio/webdriverio/assets/42645/a9157fa3-7968-4159-9ccd-2680513e3ca7">

<img width="1386" alt="image" src="https://github.com/webdriverio/webdriverio/assets/42645/ad362e6a-9e23-4450-b51d-27002fcbe0e4">

### What is your expected behavior?

It should open the documentation page.

### How to reproduce the bug.

- Open this page - https://webdriver.io/docs/wdio-chromedriver-service
- click edit page link
- it will open 404 page

### Relevant log output

```typescript
it is a documentation issue.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for raising an issue. I pushed a PR with a fix.
