### ISSUE TITLE
Looping elements

### ISSUE THREAD

**Issue by danielsvane** [webdriverio/webdriverio#1043]
This has been asked before, but I'm having some problems getting it to work. Say I want to open `https://www.google.dk/search?q=burrito`, click a result, wait for a while, go back, then click the next result, etc. I have tried with the following code:

```javascript
var q = require("q");
var webdriverio = require('webdriverio');
var options = {
    desiredCapabilities: {
        browserName: 'chrome'
    }
};

var clicks = [];
var runner = webdriverio.remote(options);

runner
    .init()
    .url('https://www.google.dk/search?q=burrito')
    .elements(".r").then(function(res){
        res.value.forEach(function(elem){
            console.log(elem);
            clicks.push(
                runner
                    .elementIdClick(elem.ELEMENT)
                    .pause(5000)
                    .back()
                    .pause(2000)
            );
        });

        return q.all(clicks);
    });
```

I hoped this would click a result, then wait 5 seconds, go back, click the next result, etc. Instead the clicks all run at the same time, and results in a `RuntimeError: stale element reference: element is not attached to the page document`.

I have looked at https://github.com/webdriverio/webdriverio/issues/273 and https://github.com/webdriverio/webdriverio/issues/941, and obviously I'm doing something wrong.

**Comment by christian-bromann** [comment]
If you query an element and go to a different page the element id expires and you have to fetch it again. We have an automated system for that implemented in the next version of WebdriverIO. For now maybe instead of querying the ids I would try to get a selector of all these elements to query them in the callback, maybe:

```js
runner
    .init()
    .url('https://www.google.dk/search?q=burrito')
    .getText(".r").then(function(res){ // given `.r` is the <a /> tag on google search page
        res.value.forEach(function(elem){
            console.log(elem);
            clicks.push(
                runner
                    .click('=' + elem.ELEMENT) // use link text selector to query the element again
                    .pause(5000)
                    .back()
                    .pause(2000)
            );
        });

        return q.all(clicks);
    });
```

**Comment by danielsvane** [comment]
Thank you @christian-bromann !

I managed to get it working with this modified code:
```javascript
runner
    .init()
    .url('https://www.google.dk/search?q=burrito')
    .getText(".r").then(function(res){
        console.log(res);
        res.forEach(function(elem){
            console.log(elem);
            clicks.push(
                runner
                    .click('=' + elem)
                    .back()
            );
        });

        return q.all(clicks);
    });
```

**Comment by nicolaivadim** [comment]
Can you please review the snippet.
It is not working as expected with current version.

**Comment by christian-bromann** [comment]
@nicolaivadim it is fine

**Comment by aqiqul** [comment]
Hi Chris,
I am trying to click on one of the radio button , but the code stops at for loop.

.elements('radio-button').then(function(res){
		console.log("aaa + :"+res);
		res.forEach(function(elem){
			console.log("elems  :"+elem);
			//client.click(elem.ELEMENT);
		})
	})

I am using webdriverio, and do not get any thing after (res.forEach)

**Comment by maenotsuzuki** [comment]
?

**Comment by maenotsuzuki** [comment]
then is not a function

**Comment by christian-bromann** [comment]
> then is not a function

@maenotsuzuki all commands are synchronous if you use wdio test runner these days
