### ISSUE TITLE
'autoGrantPermissions' is not working in android with appium 2.0.0.

### ISSUE THREAD

**Issue by 16dec12** [webdriverio/webdriverio#10487]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.10.2

### Node.js Version

18.14.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [{
    
        platformName: 'Android',
    maxInstances: 1,
    //'appium:deviceName': 'Pixel 3a API 33 x86 64',
    'appium:deviceName':'Demo11',
    'appium:platformVersion': '13',
    'appium:orientation': 'PORTRAIT',
    'appium:automationName': 'UiAutomator2',
    'appium:app': 'C:/Users/Z004RD2T/Desktop/base.apk',
    //'appium:app':'D:/Newfolder/ApiDemos.apk',
    'appium:appWaitActivity': 'com.siemens.commissioning.MainActivity',
    //'appium:appWaitActivity':'io.appium.android.apis.MainActivity',
   'appium:newCommandTimeout': 500,
    'appium:autoWebview': false,
    'appium:noReset': false,
    //"appium:autoAcceptAlerts": true,
    'autoGrantPermissions': true,       
   
    }],
```

### What happened?

Below error is displayed :

ERROR @wdio/runner: Error: Invalid or unsupported WebDriver capabilities found ("autoGrantPermissions"). Ensure to only use valid W3C WebDriver capabilities (see https://w3c.github.io/webdriver/#capabilities).If you run your tests on a remote vendor, like Sauce Labs or BrowserStack, make sure that you put them into vendor specific capabilities, e.g. "sauce:options" or "bstack:options". Please reach out to to your vendor support team if you have further questions.

### How to reproduce the bug.

 "devDependencies": {
    "@wdio/allure-reporter": "^8.2.0",
    "@wdio/appium-service": "^8.6.9",
    "@wdio/cli": "^8.6.9",
    "@wdio/cucumber-framework": "^8.2.3",
    "@wdio/local-runner": "^8.6.9",
  
    "appium": "^2.0.0-beta.58",
    "appium-uiautomator2-driver": "^2.12.7",
    "appium-xcuitest-driver": "^4.21.4",
    "chromedriver": "^109.0.0",
    "ts-node": "^10.9.1",
    "typescript": "^5.0.3",
    "wdio-chromedriver-service": "^8.0.1",
    "webdriverio": "^8.10.2"
  },

### Relevant log output

```typescript
ERROR @wdio/runner: Error: Invalid or unsupported WebDriver capabilities found ("autoGrantPermissions"). Ensure to only use valid W3C WebDriver capabilities (see https://w3c.github.io/webdriver/#capabilities).If you run your tests on a remote vendor, like Sauce Labs or BrowserStack, make sure that you put them into vendor specific capabilities, e.g. "sauce:options" or "bstack:options". Please reach out to to your vendor support team if you have further questions.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
As the error mentions, please use a vendor prefix, in this case: `appium:autoGrantPermissions. Join our support chat on [Discord](https://discord.webdriver.io) for these kind of questions. This is not necessary an issue.
