### ISSUE TITLE
UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token '||='

### ISSUE THREAD

**Issue by HeartlyRegis** [webdriverio/webdriverio#10484]
I repeatedly getting this error while I try to execute my test in my linux box.

Node Version
`v14.20.0`

webdriverio
`^8.8.8`

I am using this webdriverio in my create-react-app. Everytime I execute this, I repeatedly getting this error. 

```
> wdio run wdio.conf.js

(node:27363) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token '||='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27363) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27363) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I searched a lot, but nothing helps. Is there any way to fix this issue?

**Comment by christian-bromann** [comment]
Can you provide a minimal reproducible example please?

**Comment by udarrr** [comment]
Hello I also have catched the issue, generally it's because of version of node. Solution is raise it to 16

**Comment by christian-bromann** [comment]
Thanks for reporting back @udarrr. I will close this issue due to inactivity. A reproducible example can help identify the root cause. Happy to re-open if we have that.
