### ISSUE TITLE
'Spec not found' not reported when running a spec locally

### ISSUE THREAD

**Issue by antonborisoff** [webdriverio/webdriverio#10483]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7

### Node.js Version

18.12.1

### Mode

WDIO Testrunner

### What happened?

Suppose you have a spec A.spec.js defined.

Then
` wdio wdio.conf.js --spec A.spec.js `
will execute the spec.

However, if you try to run it with a non-existent spec:
` wdio wdio.conf.js --spec NonExistentA.spec.js `
It will not print any error messages and silently finish.

I believe the issue is related to https://github.com/webdriverio/webdriverio/blob/82c01b9fcf03c477505fd3afed777ce7b227567b/packages/wdio-cli/src/run.ts#L86
If to change it to console.warning, then the message is printed again. This is a know issue of console.error immediately followed by process.exit: https://github.com/nodejs/node-v0.x-archive/issues/3479
Although the reported bug is for old Node versions, it seems it is still relevant.

wdio/cli@7.24.0 is used, but I believe the issue is relevant for the latest version as well.

### What is your expected behavior?

'Spec not found' is printed in the console for non existent specs.

### How to reproduce the bug.

Suppose you have a spec A.spec.js defined.

Then
` wdio wdio.conf.js --spec A.spec.js `
will execute the spec.

However, if you try to run it with a non-existent spec:
` wdio wdio.conf.js --spec NonExistentA.spec.js `
It will not print any error messages and silently finish.

### Relevant log output

```typescript
None
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by rashiq231** [comment]
Hi @antonborisoff, is this issue reproducible on MAC?
I am trying with the version 8 and node 18.15, I can see an error message with the stack trace that the following spec is not found. If we pass spec options through command line.

**Comment by antonborisoff** [comment]
@rashiq231 , it doesn't work on Mac as well.
Please, note that we're talking about WDIO version 7 (I believe V8 is not released yet)

**Comment by christian-bromann** [comment]
@antonborisoff can you please provide a reproducible example?

> I believe V8 is not released yet

v8 is release for almost 7 month now, see https://webdriver.io/versions. We strongly recommend to update as we push most fixes to v8 these days.

**Comment by christian-bromann** [comment]
I will go ahead and close this as we don't actively fix bugs in v7 anymore. Happy to merge a bugfix and release a new version of v7.

Thanks @rashiq231 for investigating.
