### ISSUE TITLE
[🐛 Bug]: <title>@wdio/config:Configp[arser: Failed loading configuration file:file:///C:/github/wdio8/wdio.prod.config.ts: Cannot find module 'C:\github\wdio8\wdio.conf' imported from C:\github\wdio8\wdio.prod.config.ts

### ISSUE THREAD

**Issue by limbogabi** [webdriverio/webdriverio#10494]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.3.11

### Node.js Version

v18.14.2

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [{

        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        maxInstances: 5,
        //
        browserName: 'chrome',
        "goog:chromeOptions": {
            args: ["--disable-gpu"],
            // args: ["--headless", "--disable-gpu"]
        },
        // If outputDir is provided WebdriverIO can capture driver session logs
        // it is possible to configure which logTypes to include/exclude.
        // excludeDriverLogs: ['*'], // pass '*' to exclude all driver session logs
        // excludeDriverLogs: ['bugreport', 'server'],
    }],
```

### What happened?

I have a wdio.conf.ts file:

`import type { Options } from '@wdio/types'

// const reportportal = require('wdio-reportportal-reporter');
import ReportPortalReporter from 'wdio-reportportal-reporter'
// const RpService = require("wdio-reportportal-service");
import RpService from 'wdio-reportportal-service'

export const conf = {
    reportPortalClientConfig: { // report portal settings
      token: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
      endpoint: 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',
      launch: 'meat',
      project: yyyyyyyyyyyyyyyyyyyyyy',
      mode: 'DEFAULT',
      debug: false,
      description: "for testing cleanup wdio 8",
      attributes: [{key:"tag", value: "foo"}],
      headers: {"foo": "bar"}, // optional headers for internal http client
    //   restClientConfig: { // axios like http client config - https://github.com/axios/axios#request-config
    //     proxy: {
    //       protocol: 'https',
    //       host: '127.0.0.1',
    //       port: 9000,
    //       auth: {
    //         username: 'mikeymike',
    //         password: 'rapunz3l'
    //       }
    //     },
    //     timeout: 60000
    //   }
    },
    reportSeleniumCommands: false, // add selenium commands to log
    seleniumCommandsLogLevel: 'debug', // log level for selenium commands
    autoAttachScreenshots: false, // automatically add screenshots
    screenshotsLogLevel: 'info', // log level for screenshots
    parseTagsFromTestTitle: false, // parse strings like `@foo` from titles and add to Report Portal
    cucumberNestedSteps: false, // report cucumber steps as Report Portal steps
    autoAttachCucumberFeatureToScenario: false, // requires cucumberNestedSteps to be true for use
    sanitizeErrorMessages: true, // strip color ascii characters from error stacktrace
    sauceLabOptions : {
      enabled: true, // automatically add SauseLab ID to rp tags.
      sldc: "US" // automatically add SauseLab region to rp tags.
    }
  };
export const config: Options.Testrunner = {
    //
    // ====================
    // Runner Configuration
    // ====================
    // WebdriverIO supports running e2e tests as well as unit and component tests.
    runner: 'local',
    autoCompileOpts: {
        tsNodeOpts: {
            project: './tsconfig.json'
        }
    },

    // port: 4723,
    //
    // ==================
    // Specify Test Files
    // ==================
    // Define which test specs should run. The pattern is relative to the directory
    // of the configuration file being run.
    //
    // The specs are defined as an array of spec files (optionally using wildcards
    // that will be expanded). The test for each spec file will be run in a separate
    // worker process. In order to have a group of spec files run in the same worker
    // process simply enclose them in an array within the specs array.
    //
    // If you are calling `wdio` from an NPM script (see https://docs.npmjs.com/cli/run-script),
    // then the current working directory is where your `package.json` resides, so `wdio`
    // will be called from there.
    //
    specs: [
        './features/**/*.feature'
    ],
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    //
    // ============
    // Capabilities
    // ============
    // Define your capabilities here. WebdriverIO can run multiple capabilities at the same
    // time. Depending on the number of capabilities, WebdriverIO launches several test
    // sessions. Within your capabilities you can overwrite the spec and exclude options in
    // order to group specific specs to a specific capability.
    //
    // First, you can define how many instances should be started at the same time. Let's
    // say you have 3 different capabilities (Chrome, Firefox, and Safari) and you have
    // set maxInstances to 1; wdio will spawn 3 processes. Therefore, if you have 10 spec
    // files and you set maxInstances to 10, all spec files will get tested at the same time
    // and 30 processes will get spawned. The property handles how many capabilities
    // from the same test should run tests.
    //
    maxInstances: 10,
    //
    // If you have trouble getting all important capabilities together, check out the
    // Sauce Labs platform configurator - a great tool to configure your capabilities:
    // https://saucelabs.com/platform/platform-configurator
    //
    capabilities: [{

        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        maxInstances: 5,
        //
        browserName: 'chrome',
        "goog:chromeOptions": {
            args: ["--disable-gpu"],
            // args: ["--headless", "--disable-gpu"]
        },
        // If outputDir is provided WebdriverIO can capture driver session logs
        // it is possible to configure which logTypes to include/exclude.
        // excludeDriverLogs: ['*'], // pass '*' to exclude all driver session logs
        // excludeDriverLogs: ['bugreport', 'server'],
    }],
    //
    // ===================
    // Test Configurations
    // ===================
    // Define all options that are relevant for the WebdriverIO instance here
    //
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    logLevel: 'info',
    //
    // Set specific log levels per logger
    // loggers:
    // - webdriver, webdriverio
    // - @wdio/browserstack-service, @wdio/devtools-service, @wdio/sauce-service
    // - @wdio/mocha-framework, @wdio/jasmine-framework
    // - @wdio/local-runner
    // - @wdio/sumologic-reporter
    // - @wdio/cli, @wdio/config, @wdio/utils
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    // logLevels: {
    //     webdriver: 'info',
    //     '@wdio/appium-service': 'info'
    // },
    //
    // If you only want to run your tests until a specific amount of tests have failed use
    // bail (default is 0 - don't bail, run all tests).
    bail: 0,
    //
    // Set a base URL in order to shorten url command calls. If your `url` parameter starts
    // with `/`, the base url gets prepended, not including the path portion of your baseUrl.
    // If your `url` parameter starts without a scheme or `/` (like `some/path`), the base url
    // gets prepended directly.
    baseUrl: 'http://localhost',
    //
    // Default timeout for all waitFor* commands.
    waitforTimeout: 10000,
    //
    // Default timeout in milliseconds for request
    // if browser driver or grid doesn't send response
    connectionRetryTimeout: 120000,
    //
    // Default request retries count
    connectionRetryCount: 3,
    //
    // Test runner services
    // Services take over a specific job you don't want to take care of. They enhance
    // your test setup with almost no effort. Unlike plugins, they don't add new
    // commands. Instead, they hook themselves up into the test process.
    services: [[RpService, ['selenium-standalone',
            { drivers: { chrome: "latest", chromiumedge: "98.0.1108.50" } }]],
        
    ],
    reporters: [[ReportPortalReporter, conf]],

    // Framework you want to run your specs with.
    // The following are supported: Mocha, Jasmine, and Cucumber
    // see also: https://webdriver.io/docs/frameworks
    //
    // Make sure you have the wdio adapter package for the specific framework installed
    // before running any tests.
    framework: 'cucumber',
    //
    // The number of times to retry the entire specfile when it fails as a whole
    // specFileRetries: 1,
    //
    // Delay in seconds between the spec file retry attempts
    // specFileRetriesDelay: 0,
    //
    // Whether or not retried specfiles should be retried immediately or deferred to the end of the queue
    // specFileRetriesDeferred: false,
    //
    // Test reporter for stdout.
    // The only one supported by default is 'dot'
    // see also: https://webdriver.io/docs/dot-reporter

    //
    // If you are using Cucumber you need to specify the location of your step definitions.
    cucumberOpts: {
        // <string[]> (file/dir) require files before executing features
        require: ['./features/step-definitions/steps.ts'],
        // <boolean> show full backtrace for errors
        backtrace: false,
        // <string[]> ("extension:module") require files with the given EXTENSION after requiring MODULE (repeatable)
        requireModule: [],
        // <boolean> invoke formatters without executing steps
        dryRun: false,
        // <boolean> abort the run on first failure
        failFast: false,
        // <boolean> hide step definition snippets for pending steps
        snippets: true,
        // <boolean> hide source uris
        source: true,
        // <boolean> fail if there are any undefined or pending steps
        strict: false,
        // <string> (expression) only execute the features or scenarios with tags matching the expression
        tagExpression: '',
        // <number> timeout for step definitions
        timeout: 60000,
        // <boolean> Enable this config to treat undefined definitions as warnings.
        ignoreUndefinedDefinitions: false
    },

    //
    // =====
    // Hooks
    // =====
    // WebdriverIO provides several hooks you can use to interfere with the test process in order to enhance
    // it and to build services around it. You can either apply a single function or an array of
    // methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
    // resolved to continue.
    /**
     * Gets executed once before all workers get launched.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     */
    // onPrepare: function (config, capabilities) {
    // },
    /**
     * Gets executed before a worker process is spawned and can be used to initialise specific service
     * for that worker as well as modify runtime environments in an async fashion.
     * @param  {String} cid      capability id (e.g 0-0)
     * @param  {[type]} caps     object containing capabilities for session that will be spawn in the worker
     * @param  {[type]} specs    specs to be run in the worker process
     * @param  {[type]} args     object that will be merged with the main configuration once worker is initialized
     * @param  {[type]} execArgv list of string arguments passed to the worker process
     */
    // onWorkerStart: function (cid, caps, specs, args, execArgv) {
    // },
    /**
     * Gets executed just after a worker process has exited.
     * @param  {String} cid      capability id (e.g 0-0)
     * @param  {Number} exitCode 0 - success, 1 - fail
     * @param  {[type]} specs    specs to be run in the worker process
     * @param  {Number} retries  number of retries used
     */
    // onWorkerEnd: function (cid, exitCode, specs, retries) {
    // },
    /**
     * Gets executed just before initialising the webdriver session and test framework. It allows you
     * to manipulate configurations depending on the capability or spec.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     * @param {String} cid worker id (e.g. 0-0)
     */
    // beforeSession: function (config, capabilities, specs, cid) {
    // },
    /**
     * Gets executed before test execution begins. At this point you can access to all global
     * variables like `browser`. It is the perfect place to define custom commands.
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs        List of spec file paths that are to be run
     * @param {Object}         browser      instance of created browser/device session
     */
    // before: function (capabilities, specs) {
    // },
    /**
     * Runs before a WebdriverIO command gets executed.
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     */
    // beforeCommand: function (commandName, args) {
    // },
    /**
     * Cucumber Hooks
     *
     * Runs before a Cucumber Feature.
     * @param {String}                   uri      path to feature file
     * @param {GherkinDocument.IFeature} feature  Cucumber feature object
     */
    // beforeFeature: function (uri, feature) {
    // },
    /**
     *
     * Runs before a Cucumber Scenario.
     * @param {ITestCaseHookParameter} world    world object containing information on pickle and test step
     * @param {Object}                 context  Cucumber World object
     */
    // beforeScenario: function (world, context) {
    // },
    /**
     *
     * Runs before a Cucumber Step.
     * @param {Pickle.IPickleStep} step     step data
     * @param {IPickle}            scenario scenario pickle
     * @param {Object}             context  Cucumber World object
     */
    // beforeStep: function (step, scenario, context) {
    // },
    /**
     *
     * Runs after a Cucumber Step.
     * @param {Pickle.IPickleStep} step             step data
     * @param {IPickle}            scenario         scenario pickle
     * @param {Object}             result           results object containing scenario results
     * @param {boolean}            result.passed    true if scenario has passed
     * @param {string}             result.error     error stack if scenario failed
     * @param {number}             result.duration  duration of scenario in milliseconds
     * @param {Object}             context          Cucumber World object
     */
    // afterStep: function (step, scenario, result, context) {
    // },
    /**
     *
     * Runs after a Cucumber Scenario.
     * @param {ITestCaseHookParameter} world            world object containing information on pickle and test step
     * @param {Object}                 result           results object containing scenario results
     * @param {boolean}                result.passed    true if scenario has passed
     * @param {string}                 result.error     error stack if scenario failed
     * @param {number}                 result.duration  duration of scenario in milliseconds
     * @param {Object}                 context          Cucumber World object
     */
    // afterScenario: function (world, result, context) {
    // },
    /**
     *
     * Runs after a Cucumber Feature.
     * @param {String}                   uri      path to feature file
     * @param {GherkinDocument.IFeature} feature  Cucumber feature object
     */
    // afterFeature: function (uri, feature) {
    // },

    /**
     * Runs after a WebdriverIO command gets executed
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     * @param {Number} result 0 - command success, 1 - command error
     * @param {Object} error error object if any
     */
    // afterCommand: function (commandName, args, result, error) {
    // },
    /**
     * Gets executed after all tests are done. You still have access to all global variables from
     * the test.
     * @param {Number} result 0 - test pass, 1 - test fail
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // after: function (result, capabilities, specs) {
    // },
    /**
     * Gets executed right after terminating the webdriver session.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // afterSession: function (config, capabilities, specs) {
    // },
    /**
     * Gets executed after all workers got shut down and the process is about to exit. An error
     * thrown in the onComplete hook will result in the test run failing.
     * @param {Object} exitCode 0 - success, 1 - fail
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {<Object>} results object containing test results
     */
    // onComplete: function(exitCode, config, capabilities, results) {
    // },
    /**
    * Gets executed when a refresh happens.
    * @param {String} oldSessionId session ID of the old session
    * @param {String} newSessionId session ID of the new session
    */
    // onReload: function(oldSessionId, newSessionId) {
    // }
}
`
Then I added another enviroment specific configuration file, wdio.prod.config.ts:

`// wdio.dev.config.ts
import { deepmerge } from 'deepmerge-ts'
import {conf} from './wdio.conf'

// have main config file as default but overwrite environment specific information
export const config = deepmerge(conf.reportPortalClientConfig, {
    reportPortalClientConfig: { // report portal settings
      token: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
      endpoint: 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',
      launch: 'cleanup',
      project: 'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
      mode: 'DEFAULT',
      debug: false,
      description: "for testing cleanup wdio 8",
      attributes: [{key:"tag", value: "foo"}],
      headers: {"foo": "bar"}, // optional headers for internal http client
    //   restClientConfig: { // axios like http client config - https://github.com/axios/axios#request-config
    //     proxy: {
    //       protocol: 'https',
    //       host: '127.0.0.1',
    //       port: 9000,
    //       auth: {
    //         username: 'mikeymike',
    //         password: 'rapunz3l'
    //       }
    //     },
    //     timeout: 60000
    //   }
    }

    
},{ clone: false })`

and this is the package.json file:

`{
  "name": "my-new-project",
  "type": "module",
  "devDependencies": {
    "@wdio/appium-service": "^8.3.11",
    "@wdio/cli": "^8.3.11",
    "@wdio/cucumber-framework": "^8.3.0",
    "@wdio/local-runner": "^8.3.11",
    "@wdio/selenium-standalone-service": "^8.3.11",
    "@wdio/spec-reporter": "^8.3.0",
    "appium": "^1.22.3",
    "ts-node": "^10.9.1",
    "typescript": "^4.9.5",
    "wdio-reportportal-reporter": "^7.6.0",
    "wdio-reportportal-service": "^7.3.1"
  },
  "scripts": {
    "wdio": "wdio run ./wdio.hotfix.config.ts"
  },
  "dependencies": {
    "deepmerge-ts": "^5.1.0"
  }
}`

then i run the script and the outcome is:

C:\github\wdio8>npm run wdio
Debugger attached.

> wdio
> wdio run ./wdio.prod.config.ts

Debugger attached.
Debugger attached.
2023-06-05T10:02:52.095Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///C:/github/wdio8/wdio.prod.config.ts: Cannot find module 'C:\github\wdio8\wdio.conf' imported from C:\github\wdio8\wdio.prod.config.ts
CustomError: Cannot find module 'C:\github\wdio8\wdio.conf' imported from C:\github\wdio8\wdio.prod.config.ts
    at finalizeResolution (C:\github\wdio8\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:366:11)
    at moduleResolve (C:\github\wdio8\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:801:10)
    at Object.defaultResolve (C:\github\wdio8\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:912:11)
    at C:\github\wdio8\node_modules\ts-node\src\esm.ts:218:35
    at entrypointFallback (C:\github\wdio8\node_modules\ts-node\src\esm.ts:168:34)
    at C:\github\wdio8\node_modules\ts-node\src\esm.ts:217:14
    at addShortCircuitFlag (C:\github\wdio8\node_modules\ts-node\src\esm.ts:409:21)
    at resolve (C:\github\wdio8\node_modules\ts-node\src\esm.ts:197:12)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...

### What is your expected behavior?

instead, I would expect the two config files been merged and the run successfully with the enviroment specific configuration

### How to reproduce the bug.

create a new wdio 8 project and add a enviroment config file then run the new file with wdio

### Relevant log output

```typescript
C:\github\wdio8>npm run wdio
Debugger attached.

> wdio
> wdio run ./wdio.prod.config.ts

Debugger attached.
Debugger attached.
2023-06-05T10:02:52.095Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///C:/github/wdio8/wdio.prod.config.ts: Cannot find module 'C:\github\wdio8\wdio.conf' imported from C:\github\wdio8\wdio.prod.config.ts
CustomError: Cannot find module 'C:\github\wdio8\wdio.conf' imported from C:\github\wdio8\wdio.prod.config.ts
    at finalizeResolution (C:\github\wdio8\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:366:11)
    at moduleResolve (C:\github\wdio8\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:801:10)
    at Object.defaultResolve (C:\github\wdio8\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:912:11)
    at C:\github\wdio8\node_modules\ts-node\src\esm.ts:218:35
    at entrypointFallback (C:\github\wdio8\node_modules\ts-node\src\esm.ts:168:34)
    at C:\github\wdio8\node_modules\ts-node\src\esm.ts:217:14
    at addShortCircuitFlag (C:\github\wdio8\node_modules\ts-node\src\esm.ts:409:21)
    at resolve (C:\github\wdio8\node_modules\ts-node\src\esm.ts:197:12)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by limbogabi** [comment]
I know that i run this:
wdio run ./wdio.prod.config.ts
and I put this file in the description wdio.hotfix.config.ts
the content of the file are the same, don't worry about this please

**Comment by limbogabi** [comment]
> It seems you are using ESM where the full file extension is needed, so try `import {conf} from './wdio.conf.js'`.

but its not .js its .ts

**Comment by christian-bromann** [comment]
> but its not .js its .ts

This shouldn't matter for TypeScript which compiles the file in memory.

**Comment by limbogabi** [comment]
> > but its not .js its .ts
> 
> This shouldn't matter for TypeScript which compiles the file in memory.

it doesnt work, i tried

**Comment by christian-bromann** [comment]
Check out our [Jasmine boilerplate](https://github.com/webdriverio/jasmine-boilerplate) where this works.

**Comment by christian-bromann** [comment]
That error message (`No specs found to run, exiting with failure`) seems clear to me.
