### ISSUE TITLE
[🐛 Bug]: browser.waitUntil() is not throwing custom error message

### ISSUE THREAD

**Issue by nils-hoyer** [webdriverio/webdriverio#10495]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.8.3

### Node.js Version

v18.12.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
automationProtocol: 'devtools', 
browserName: 'chrome',
'goog:chromeOptions': {
   args: ['--incognito', '--window-size=1920,1080'],
 },
```

### What happened?

the function browser.waitUntil() is not throwing custom error message

### What is your expected behavior?

throwing the custom error message over the internal error message.

### How to reproduce the bug.

```typescript
describe('browser.waitUntil() tests', async () => {
    it('should throw custom error message', async () => {
        await browser.waitUntil(() => false, { timeoutMsg: 'timeoutMsg will be ignored' });
    });
});
```

### Relevant log output

```typescript
[chrome 113.0.0.0 win32 #0-0] browser test
[chrome 113.0.0.0 win32 #0-0]    ✖ should throw custom error message
[chrome 113.0.0.0 win32 #0-0]
[chrome 113.0.0.0 win32 #0-0] 1 failing (10.1s)
[chrome 113.0.0.0 win32 #0-0]
[chrome 113.0.0.0 win32 #0-0] 1) browser test should throw custom error message
[chrome 113.0.0.0 win32 #0-0] waitUntil condition failed with the following reason: return value was never truthy
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!



We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by rashiq231** [comment]
@christian-bromann, @nils-hoyer, as per the waitUntil implementation, condition uses a promise based timer, which stops when the function is resolved.
In the above scenario we are trying to return a false value always and error message is thrown accordingly.
```javascript
describe('verifying waituntil', () => {
  it('expected given error message', async () => {
    const falsePromise = async function() {
      return new Promise((resolve, reject) => {
        resolve(false);
      });
    };
    await browser.waitUntil(falsePromise,
      { timeoutMsg: 'This is a custom message' });
  });
});
```

**Comment by christian-bromann** [comment]
@rashiq231 thanks for investigating!
It should work regardless whether a promise is returned or not, e.g. this should return the same result:

```ts
describe('verifying waitUntil', () => {
  it('expected given error message', async () => {
    const falsePromise = async function() {
      return false;
    };
    await browser.waitUntil(falsePromise,
      { timeoutMsg: 'This is a custom message' });
  });
});
```

**Comment by rashiq231** [comment]
@christian-bromann ,but form internal implementation, this is what I understood.

```javascript
_tick() {
        const result = this._fn();
        if (typeof result.then !== 'function') {
            if (!result) {
                return this._checkCondition(new Error('return value was never truthy'));
            }
            return this._checkCondition(undefined, result);
        }
        result.then((res) => this._checkCondition(undefined, res), (err) => this._checkCondition(err));
    }
``` 
please suggest what should be done. As this is my first time I am working on open source projects.

**Comment by christian-bromann** [comment]
The current implementation might be incorrect. It would be desirable if the custom timeout message it propagated no matter if the result is a promise or not. Can you adjust the current implementation to do so?

**Comment by rashiq231** [comment]
Okay,  I will work on it. Thank you

**Comment by rashiq231** [comment]
!assign

**Comment by rashiq231** [comment]
@christian-bromann , could you please assign this bug to me?

**Comment by christian-bromann** [comment]
Done, let me know if you have any questions to any code parts.

**Comment by christian-bromann** [comment]
Let's continue convo in https://github.com/webdriverio/webdriverio/pull/10535
