### ISSUE TITLE
[🐛 Bug]: session backend not connected

### ISSUE THREAD

**Issue by Chaffexd** [webdriverio/webdriverio#10510]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

v16.18.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
function generateCapabilities() {
    const macChromeVersions = [
      '113', '112', '111', '110', '109', '108', '107', '106', '105', '104', '103', '102',
      '101', '100', '99', '98', '97', '96', '95', '94', '93', '92', '91', '90', '89',
      '88', '87', '86', '85', '84', '83', '81', '80', '79', '78', '77', '76'
    ];
  
    const macFirefoxVersions = [
      '113', '112', '111', '110', '109', '108', '107', '106', '105', '104', '103', '102',
      '101', '100', '99', '98', '97', '96', '95', '94', '93', '92', '91', '90', '89',
      '88', '87', '86', '85', '84', '83', '82', '81', '80', '79'
    ];
  
    const macEdgeVersions = [
      '113', '112', '111', '110', '109', '108', '107', '106', '105', '104', '103', '102',
      '101', '100', '99', '98', '97', '96', '95', '94', '93', '92', '91', '90', '89',
    ];

    const safariVersions = [
      {
        browserVersion: '16',
        platformName: 'macOS 13'
      },
      {
        browserVersion: '15',
        platformName: 'macOS 12'
      },
      {
        browserVersion: '14',
        platformName: 'macOS 11'
      }
    ];

    console.log(macEdgeVersions.length, macFirefoxVersions.length, macChromeVersions.length)
  
    const capabilities = [];
  
    // Map over Chrome versions
    macChromeVersions.forEach(version => {
      capabilities.push({
        browserName: 'chrome',
        browserVersion: version,
        platformName: 'macOS 13',
        'sauce:options': {
          build: 'automated run',
          name: 'Login test'
        }
      });
    });
  
    // Map over Firefox versions
    macFirefoxVersions.forEach(version => {
      capabilities.push({
        browserName: 'firefox',
        browserVersion: version,
        platformName: 'macOS 13',
        'sauce:options': {
          build: 'automated run',
          name: 'Login test'
        }
      });
    });
  
    // Map over Edge versions
    macEdgeVersions.forEach(version => {
      capabilities.push({
        browserName: 'MicrosoftEdge',
        browserVersion: version,
        platformName: 'macOS 13',
        'sauce:options': {
          build: 'automated run',
          name: 'Login test'
        }
      });
    });

    safariVersions.forEach(version => {
      capabilities.push({
        browserName: 'Safari',
        browserVersion: version.browserVersion,
        platformName: version.platformVersion,
        'sauce:options': {
          build: 'automated run',
          name: 'Login test'
        }
      });
    });
```

### What happened?

I run 100 concurrent sessions on Sauce Labs using the config I shared above and in a lot of the tests I frequently see:
at async Context.<anonymous> (/home/runner/work/automatedWeb/automatedWeb/test/specs/loginExample.js:5:9)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
invalid session id: session backend not connected
https://app.eu-central-1.saucelabs.com/tests/eced1cd9937146d48821daca28c4f688

I have this set up in a CI (GitHub Actions) and think this might be a bug as it seems to very rarely be able to pass, you can see history here: https://github.com/Chaffexd/automatedWeb/actions

### What is your expected behavior?

No error - full suite should run, see linked runs above

### How to reproduce the bug.

You can use the repo from https://github.com/Chaffexd/automatedWeb/actions or see the results in there

### Relevant log output

```typescript
at async Context.<anonymous> (/home/runner/work/automatedWeb/automatedWeb/test/specs/loginExample.js:5:9)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
invalid session id: session backend not connected
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by idem7x** [comment]
I am facing exactly with same issue on Saucelabs. 
But from wdio libraries I did not change something.
Looks like Saucelabs made some change on their side, so tests started to fail...

**Comment by christian-bromann** [comment]
I will go ahead and close this. I doubt this is related to WebdriverIO as this seems to be a Sauce Labs issue. Happy to re-open if someone knows any improvements we can do in this code base.
