### ISSUE TITLE
Cucumber Option 'featureDefaultLanguage' not recognonized in v8

### ISSUE THREAD

**Issue by gr0l** [webdriverio/webdriverio#10512]
I am currently migrating a v7 project to v8 and the option `featureDefaultLanguage` seems not work.
I get the following error when running the fests: 

```
@wdio/local-runner: Failed launching test session: Error: Parser errors:
[0-0] (2:1): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'Funktionalität: Auswahllisten bearbeiten'
```

When I add the language info in the feature file the error is solved.

```
# language: de
```

Thanks in advance

**Comment by christian-bromann** [comment]
Thanks for reporting!



We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!
