### ISSUE TITLE
Problems with cookie working

### ISSUE THREAD

**Issue by dunpeal** [webdriverio/webdriverio#1052]
Hello!

I try to set cookie for loading page, but i failed in all browsers

OS: Mac OS 10.11.2
Chrome: 48.0.2564.82 (64-bit)
ChromeDriver: 2.20.353124
Firefox: 43.0.4
PhantomJS: 2.0.0
webdriverio: 3.4.0
selenium server: 2.49.0

I take default example and little modify it

var webdriverio = require('../index');
var options = {
    desiredCapabilities:
        {browserName: 'chrome'}
    ,
    logLevel: 'verbose'
};

webdriverio
    .remote(options)
    .init()
    .url('http://localhost/')
    .setCookie({name: 'test', value: '11111', domain: 'localhost'})
    .getHTML('body', function(err, html) {
        console.log(html);
    })
    .waitForExist('.non-exist-block',2000)
    .end();

On http://localhost/ is simple php script displaying incoming cookies

<?php
print_r($_COOKIE);
?>

Non of all browsers send cookie. I think, i tried all possible combination. With and without domain (phantomjs need domain). I tried "setCookie" before "url", but chrome throw error:
RuntimeError: <unknown>: Failed to set the 'cookie' property on 'Document': Cookies are disabled inside 'data:' URLs. 

I am always get 
<body>Array
(
)
</body>
no incoming cookies.

Also i tried these scenario in ubuntu 15.10 - same result.

Can you help me? :)

**Comment by christian-bromann** [comment]
@dunpeal you have to reload the page to get the cookies:

```js
webdriverio
  .remote(options)
  .init()
  .url('http://localhost/')
  .setCookie({name: 'test', value: '11111', domain: 'localhost'})
  .url('http://localhost/')
  .getHTML('body', function(err, html) {
    console.log(html);
  })
  .waitForExist('.non-exist-block',2000)
  .end();
```

**Comment by dunpeal** [comment]
Thank you! Its working now. May be add this information on this page http://www.webdriver.io/api/cookie/setCookie.html?

**Comment by christian-bromann** [comment]
Well this is kind of obvious ;-) See php renders the page if you request it from the server. At the time you request the page for the first time it can't find any cookies since you haven't called the command. After you did you have to request the page again to give php the opportunity to rerender the page
