### ISSUE TITLE
[🐛 Bug]: Problem with running feature files in wdio v8

### ISSUE THREAD

**Issue by Lara2409** [webdriverio/webdriverio#10534]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.11.1

### Node.js Version

v18.14.2

### Mode

WDIO Testrunner

### What happened?

Run cucumber tests via command `wdio run ./config/wdio.conf.js --cucumberOpts.tagExpression=@smoke` successfully in 7 version of wdio.

But now I receive an error 
`Execution of 0 workers started at 2023-06-09T12:56:02.165Z
2023-06-09T12:56:03.004Z ERROR @wdio/cli:launcher: No specs found to run, exiting with failure
Spec Files:      0 passed, 0 total (0% completed) in 00:00:00`

### How to reproduce the bug.

wdio config file

`exports.config = {
  specs: ['./features/**/*.feature'],
  capabilities: [
    {
      maxInstances: 5,
      browserName: 'chrome',
      'goog:chromeOptions': {
        args: process.env.CI
          ? ['--headless', '--disable-gpu', '--no-sandbox'] : ['--start-maximized'],
      },
    },
  ],
  logLevel: 'error',
  bail: 0,
  baseUrl: url,
  waitforTimeout: 10000,
  connectionRetryTimeout: 10000,
  connectionRetryCount: 3,
  services: ['chromedriver', 'shared-store', 'devtools'],
  framework: 'cucumber',
  specFileRetries: 1,
  specFileRetriesDelay: 1,
  reporters: [
    [ 'allure',
      {
        outputDir: 'allure-results',
        disableWebdriverStepsReporting: true,
        disableWebdriverScreenshotsReporting: false,
        useCucumberStepReporter: true,
      },
    ],
    'spec',
  ],
  cucumberOpts: {
    require: ['./step-definitions/*.js'],
    backtrace: false,
    requireModule: [],
    dryRun: false,
    failFast: false,
    colors: true,
    snippets: true,
    source: true,
    strict: false,
    tagExpression: '(not @ignore)',
    timeout: 10000,
    ignoreUndefinedDefinitions: false,
  },`

### Relevant log output

```typescript
`Execution of 0 workers started at 2023-06-09T12:56:02.165Z
2023-06-09T12:56:03.004Z ERROR @wdio/cli:launcher: No specs found to run, exiting with failure
Spec Files:      0 passed, 0 total (0% completed) in 00:00:00`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Can you provide a minimal reproducible example?

**Comment by christian-bromann** [comment]
This is not a reproducible example. A reproducible example is e.g. GitHub repository I can check out and run myself.

**Comment by RahulARanger** [comment]
Please add a location for the spec files, as mentioned here: https://webdriver.io/docs/configuration/#specs. in the example provided it should be the path to your feature files.

[Reference Example](https://github.com/webdriverio/cucumber-boilerplate/blob/a6d7ff61c0bece2383399e7d2aec8928da96ac14/wdio.conf.ts#L26)

**Comment by christian-bromann** [comment]
Thanks for investigating @RahulARanger!

Your config file defines the feature files to be located within the config directory. All file paths are relative to the config file.
