### ISSUE TITLE
Running tests from behind a proxy in webdriverio

### ISSUE THREAD

**Issue by tapanbasak** [webdriverio/webdriverio#1055]
How to run tests from behind local proxy.

In "selenium webdriver" node module we have the below options available to set the proxy -
var driver = new webdriver.Builder().
  usingServer('http://hub.browserstack.com/wd/hub').
  withCapabilities(capabilities).
  usingWebDriverProxy("proxy.org:8080").
  build();

Here by 'usingWebDriverProxy' we can pass proxy configuration to run test scripts from behind a local proxy.

How can we do the same with webdriverio?

Thanks in advance.

**Comment by christian-bromann** [comment]
You can try this:

```js
var browser = require('webdriverio').remote({
    desiredCapabilities: {
        browserName: "firefox",
        proxy: "proxy.org:8080"
    }
});

browser.init().url('http://google.com').end()
```

Let me know if this works!

**Comment by tapanbasak** [comment]
Hi Christian...it didn't work. I am getting the below error message -
RuntimeError: Couldn't connect to selenium server

Here is my sample code - I have taken the sample code from the example folder of webdriverio module 

var webdriverio = require('../../index'),
    client = webdriverio.remote({
        desiredCapabilities: {
            browserName: "firefox",
            proxy: "http://<IP address>:8080" //here i set the proxy IP. 
        },
        host: 'hub.browserstack.com',
        port: 80,
        user : '<BrowserStack_User>',
        key: '<BrowserStack_AccessKey>'
    }).init();

client
    .url('http://google.com')
    .setValue('*[name="q"]','webdriverio')
    .click('*[name="btnG"]')
    .pause(1000)
    .getTitle().then(function(title) {
        console.log(title);
    })
    .end();

I have tried with both options with and without http: 
like [proxy: "http://<IP address>:8080"] or [proxy: "<IP address>:8080"]

The same proxy, user & accesskey is working fine with 'selenium-webdriver' node module.

Please let me know in case if you need any further details.

Thanks

**Comment by christian-bromann** [comment]
I looked into the docs and it seems that you have to specify which proxy you want to use, I think this could work:

```js
var proxy = "http://IP address:8080";
var webdriverio = require('../../index'),
    client = webdriverio.remote({
        desiredCapabilities: {
            browserName: "firefox",
            proxy: {
                httpProxy: proxy,
                sslProxy: proxy,
                ftpProxy: proxy,
                proxyType: "MANUAL",
                autodetect: false
        },
        host: 'hub.browserstack.com',
        port: 80,
        user : 'BrowserStack_User',
        key: 'BrowserStack_AccessKey'
    }).init();

client
    .url('http://google.com')
    .setValue('*[name="q"]','webdriverio')
    .click('*[name="btnG"]')
    .pause(1000)
    .getTitle().then(function(title) {
        console.log(title);
    })
    .end();
```

**Comment by tapanbasak** [comment]
Nope..it didn't work..I had contacted with BrowserStack and below is the reply from BrowserStack:

> **I understand you wish to run your tests on BrowserStack from behind a proxy. As per the config you shared, I believe you are specifying the proxy parameters as capabilities. This config will help you configure proxy on the remote browser, however, it would not help you authenticate locally configured proxy.**

Christian..I need further help from you to overcome this problem.

Note: With 'selenium-webdriver' node module, proxy is working fine.

Thanks

**Comment by christian-bromann** [comment]
ohhh @tapanbasak now I see what you want. There are two ways on applying proxies: one is on the browser site (route requests _from the browser_ through a proxy) and one is on the Selenium side (route _Selenium commands_ through a proxy). It seems that you want to achieve the second case. If so you need to know that WebdriverIO uses the popular request module (even though it is a bloated package). In order to apply a proxy you need to set a `HTTP_PROXY` env variable (see [here](https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables)).

**Comment by tapanbasak** [comment]
Christian..you are right...i already figured it out...thank you very much for your help.

**Comment by tauheedkhan** [comment]
@tapanbasak can you post your solution, I am also facing the same problem

**Comment by doomsbuster** [comment]
Setting the `HTTP_PROXY` or `http_proxy` does not work for me, here is my simple test code.

```
var webdriver = require('webdriverio');
var options = {
        desiredCapabilities: {
            browserName: 'chrome'
        },
        logLevel: 'verbose',
        coloredLogs: true,
        debug: true,
        host:'external host outside corporate firewall',
        port: 443
};
webdriver.remote(options).init().url('http://www.google.com').getTitle().then(function(title) {
        debugger;
        console.log(title);
}).end();
```

**Comment by biz786** [comment]
Hi @tapanbasak  I am also facing the same problem, can u please paste your webdriver conf file?

**Comment by biz786** [comment]
@christian-bromann can u please help me debug too. I probably not setting the proxy at the browser end or at the Selenium side

![error](https://user-images.githubusercontent.com/4602480/37544875-f89dda3a-293c-11e8-8c84-6ebc985aa610.jpg)

![wdio_config](https://user-images.githubusercontent.com/4602480/37544883-fd2c4dca-293c-11e8-978c-fb75159710cf.jpg)

**Comment by mr-nilesh** [comment]
@tapanbasak can you please post your solution here?

**Comment by dmaziar** [comment]
I have set process.env.HTTP_PROXY = 'someproxy:8080' and it worked.

**Comment by biz786** [comment]
@dmaziar can you please share your webdriverio.config file

**Comment by phillirodney** [comment]
I am havign the same issue, my wdio.config.js file is as follows:

exports.config = {
  specs: [
    'spec/**'
  ],
  maxInstances: 1,
  capabilities: [{
    browserName: 'chrome',
    chromeOptions: {
      // to run chrome headless the following flags are required
      // (see https://developers.google.com/web/updates/2017/04/headless-chrome)
      args: ['--headless', '--disable-gpu', '--window-size=1920,1080'],
    }
  }],
  debug: false,
  sync: true,
  // Level of logging verbosity: silent | verbose | command | data | result | error
  logLevel: 'error',
  coloredLogs: true,
  bail: 0,
  screenshotPath: 'shots',
  deprecationWarnings: false,
  baseUrl: 'http://localhost:3000',
  // Default timeout for all waitForXXX commands.
  waitforTimeout: 5000,
  framework: 'jasmine'
};

**Comment by Alek5andr** [comment]
The same problem.
I have environment proxy variables set, proxy option in wdio.conf.js, and even in selenium-standalone configuration I set proxy option.
No progress with launching tests behind proxy. Can the cause be in too greedy proxy?
