### ISSUE TITLE
[💡 Feature]: cjs builds along with es

### ISSUE THREAD

**Issue by andrew-hm** [webdriverio/webdriverio#10573]
### Is your feature request related to a problem?

while I applaud [v8](https://github.com/webdriverio/webdriverio/releases/tag/v8.0.0) and welcome [pure ESM packages](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c), would it be possible to also include the cjs builds along with the esm build output?

As of now, I'm blocked. For example, I have a custom reporter that has `import WDIOReporter from '@wdio/reporter'` at the top of the file. I now can no longer offer a cjs build variant of this package, only an esm. If I tried to, babel would output something along lines of `var _reporter = _interopRequireDefault(require("@wdio/reporter"));` in the cjs version. This does not work since there is no cjs code in your library. I can't use `await import …` either since I need to have extend from the default export and top level awaits are not allowed.

I'm only suggesting this step as a stop gap to allow developers to adopt the new code and be able to slowly transition all their projects to esm.

### Describe the solution you'd like.

I'd like to have an exports added to package.json that references a `build/esm/index.js` and a `build/cjs/index.js` file in the package. Something along lines of, 

```
"exports": {
  ".": {
    "node": {
      "require": "./build/cjs/index.js",
      "import": "./build/esm/index.js"
    }
  }
}
```

Or pick your flavor but both are published to allow flexibility.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Unfortunately we can't provide a CJS version of the `@wdio/reporter` package as it relies on ESM only dependencies too. I recommend to either use v7 of that package which comes in CJS or build the reporter as ESM package and have WebdriverIO import it for you (this however only works if you pass in the service as string).

Let me know if you have further questions. I will close this as we can't provide a transpiled CJS export for all packages no more without introducing unnecessary difficult build steps.
