### ISSUE TITLE
moveToObject ("middle of the element") broken in latest version

### ISSUE THREAD

**Issue by xeladotbe** [webdriverio/webdriverio#1057]
documentation says:

xoffset	Number	X offset to move to, relative to the top-left corner of the element. If not specified, the mouse will move to the middle of the element.
yoffset	Number	Y offset to move to, relative to the top-left corner of the element. If not specified, the mouse will move to the middle of the element.

but x and y will be defined with default values (0, 0)

https://github.com/webdriverio/webdriverio/blob/master/lib/commands/moveToObject.js
let moveToObject = function (selector, xoffset = 0, yoffset = 0) {

**Comment by christian-bromann** [comment]
Good catch!

**Comment by xeladotbe** [comment]
wow, that was fast :)

**Comment by christian-bromann** [comment]
:wink:
