### ISSUE TITLE
[🐛 Bug]: jasmine.addMatchers(...) does not work with injectGlobals set to true.

### ISSUE THREAD

**Issue by PSpSynedra** [webdriverio/webdriverio#10586]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.11.2

### Node.js Version

18.13.0

### Mode

WDIO Testrunner

### What happened?

In our project we use [Custom Matchers](https://jasmine.github.io/tutorials/custom_matcher) from jasmine to simplify testing of certain expectations.

We have set up wdio to use the jasmine-framework adapter (v.8.11.2) by setting the config `framework` to `jasmine`.
When setting `injectGlobals` in the wdio-config to `false` -  everything works fine.
When setting `injectGlobals` in the wdio-config to `true` - the custom matchers won't be present on the return value of `expect(...)`

A workaround currently implemented sets `injectGlobals` to `false` and explicitly defines globals from `@wdio/globals` on the `global`-Object.

### What is your expected behavior?

A call to `jasmine.addMatchers(...)` should add the defined matchers to return values of `expect`-calls as described in the [jasemine Documentation](https://jasmine.github.io/api/edge/jasmine.html) of `addMatchers(...)`.

### How to reproduce the bug.

I have provided a [Demo Project](https://github.com/PSpSynedra/wdio-jasmine-custom-matchers) that reproduces the bug and allows simple testing of the proposed workaround.

### Relevant log output

```typescript
"spec" Reporter:
------------------------------------------------------------------
[chrome 114.0.5735.133 linux #0-0] Running: chrome (v114.0.5735.133) on linux
[chrome 114.0.5735.133 linux #0-0] Session ID: 06e7c5baadf140e1dfe3c126f2a73c01
[chrome 114.0.5735.133 linux #0-0]
[chrome 114.0.5735.133 linux #0-0] » /test/specs/CustomMatchersTest.js
[chrome 114.0.5735.133 linux #0-0] expect utility
[chrome 114.0.5735.133 linux #0-0]    ✖ should provide the custom matcher
[chrome 114.0.5735.133 linux #0-0]
[chrome 114.0.5735.133 linux #0-0] 1 failing (61ms)
[chrome 114.0.5735.133 linux #0-0]
[chrome 114.0.5735.133 linux #0-0] 1) expect utility should provide the custom matcher
[chrome 114.0.5735.133 linux #0-0] Expected undefined to be defined.      
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@PSpSynedra thanks for raising the issue.

Your demo should work by calling `jasmine.addAsyncMatchers` instead of `jasmine.addMatchers`. Reason being is that WebdriverIO merges Jasmines sync matchers into async matchers to create a more consistent behavior across frameworks and simplify documentation.

There are two things we could do:
1. document this better in https://webdriver.io/docs/frameworks#using-jasmine
2. monkey patch `jasmine.addMatchers` and have it call `jasmine.addAsyncMatchers` instead

Would you like to help us on this effort?

**Comment by PSpSynedra** [comment]
Yes - monkey patching `jasmine.addMatchers` with `jasmine.addAsyncPatchers` seems to avoid the bug.
This recreates the behaviour as documented by jasmine and is thus preferable to extending the documentation (at least for me).

I will clarify internally if I can provide help in solving the issue.

**Comment by PSpSynedra** [comment]
> I will clarify internally if I can provide help in solving the issue.
>
All good. I will try to prepare a PullRequest with the fix next week.

**Comment by PSpSynedra** [comment]
I updated the [Demo Project](https://github.com/PSpSynedra/wdio-jasmine-custom-matchers) to use `@wdio/jasmine-framework-8.12.1`.
And yes, the custom matcher added in the test is present on the result of a call to `expect(...)`.

I Added a test-case to the [Demo Project](https://github.com/PSpSynedra/wdio-jasmine-custom-matchers) that actually uses the registered custom-matcher and get the following error:
```
[chrome 114.0.5735.198 linux #0-0] TypeError: this.expector.compare(...).then is not a function
[chrome 114.0.5735.198 linux #0-0]     at <Jasmine>
[chrome 114.0.5735.198 linux #0-0]     at UserContext.<anonymous> (/home/psp/github/PSPsynedra/wdio-jasmine-custom-matchers/test/specs/CustomMatchersTest.js:21:13)
[chrome 114.0.5735.198 linux #0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

This is because, the registered matcher is not an async matcher but simply returns the test-result synchronous matchers would.

I would argue that `addMatchers(...)`  does not behave like documented by the jasmine docs.

**Comment by christian-bromann** [comment]
@PSpSynedra raised another PR with a fix for it: https://github.com/webdriverio/webdriverio/pull/10727

**Comment by PSpSynedra** [comment]
Using @wdio/jasmine-framework-8.13.13 `addMatchers` works as expected and documented by JasmineJS even if `injectGlobals` is set to `true`.

Thanks for the quick fixes and response!
