### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by MrHayato** [webdriverio/webdriverio#1059]
Is there a reason TypeScript is not supported for webdriverio? I noticed babel preprocessing using `require('babel-register')` works fine. I dug through the code and noticed ConfigParser.js filters all files that don't end in `.js`, `.feature`, and `.coffee`. By adding `.ts` to the list and using [ts-node](https://github.com/TypeStrong/ts-node), I was able to write my unit tests using typescript properly. I can submit a pull request, but wanted to make sure there wasn't a specific reason in the first place for filtering other extensions.

**Comment by christian-bromann** [comment]
> there wasn't a specific reason in the first place for filtering other extensions.

There was no reason for that. Happy to add typescript support to wdio

**Comment by MrHayato** [comment]
Good to know. I'll open a pull request. Thanks!
