### ISSUE TITLE
[🐛 Bug]: @wdio/cucumber-framework 'DataTable' refers to a value, but is being used as a type here. (TS2749)

### ISSUE THREAD

**Issue by patrickschilder** [webdriverio/webdriverio#10605]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### What happened?

Since @wdio/cucumber-framework version 8.10.2 i get a type error on Datatables used in cucumber step definitions.
'DataTable' refers to a value, but is being used as a type here. (TS2749)
It was working correctly up and till @wdio/cucumber-framework 8.10.1

### How to reproduce the bug.

```
import { When, DataTable } from '@wdio/cucumber-framework'

When('This is my step definition', async (myDatatable: DataTable) => {
    for (const myData of myDatatable.hashes()) {
        // do something
    }
})
```

### Relevant log output

```typescript
There is no issue running the test, but my IDE is giving error TS2749
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> import { When, DataTable } from '@wdio/cucumber-framework'

You might want to change it to

```ts
import { When, type DataTable } from '@wdio/cucumber-framework'
```

Closing as this is not an issue within WebdriverIO.

**Comment by erwinheitzman** [comment]
This is actually an issue with the way we import and reassign the variables in which the types seem to get lost.
