### ISSUE TITLE
Running WebdriverIO 'spec' tests as node file

### ISSUE THREAD

**Issue by thepianist2** [webdriverio/webdriverio#1061]
I need this response please:

I'm new to webdriverio. I don't understand how it's supposed to be configured and used within a node application. How do you run 'spec' tests when webdriverio is being imported? Can it be done?

more details:
http://stackoverflow.com/questions/33311721/running-webdriverio-spec-tests-as-node-file

**Comment by christian-bromann** [comment]
Answered on SO

**Comment by thepianist2** [comment]
tnx
