### ISSUE TITLE
 It would be a good idea to implement callbacks in the stages of testing in configuration wdio.conf.js

### ISSUE THREAD

**Issue by thepianist2** [webdriverio/webdriverio#1062]
I have a problem, on this file wdio.conf.js (http://webdriver.io/guide/testrunner/configurationfile.html) i can insert the functionality of:

```js
var sauceConnectLauncher = require('sauce-connect-launcher');
```
and into onPrepare function connect to the tunnel of saucelabs to launch the test into server, but the problem is the time of establish tunnel connection, so the test is launching before the function of sauceConnectLauncher is finished, 

and I thought it was a good idea to implement a callback at each stage, is it possible?

now is:
```js
    onPrepare: function() {
        sauceConnectLauncher({
          username: 'the_pianist2',
          accessKey: '67dde83a-1cf7-450d-8c88-857c4d3cde49',
        }, function (err, sauceConnectProcess) {
          if (err) {
            throw err;
          }else{
            return true;
          }

        });
    },
```

with callback:

```js
    onPrepare: function(cb) {
        sauceConnectLauncher({
          username: 'the_pianist2',
          accessKey: '67dde83a-1cf7-450d-8c88-857c4d3cde49',
        }, function (err, sauceConnectProcess) {
          if (err) {
            throw err;
          }else{
            console.log(sauceConnectProcess);
            console.log('conectado');
            cb(true);
          }

        });
    },
```

i try return true inside the function, but not wait the finish of sauceConnectLauncher function.

My way is correct?

**Comment by christian-bromann** [comment]
You need to return a promise in order to wait until SC is launched. E.g.
```js
onPrepare: function() {
    return new Promise(function(resolve, reject) {
        sauceConnectLauncher({
          username: 'the_pianist2',
          accessKey: '67dde83a-1cf7-450d-8c88-857c4d3cde49',
        }, function (err, sauceConnectProcess) {
            if (err) {
                return reject(err);
            }
            resolve();
        });
    })
},
```

Fyi: in v4 we will provide a service that will take care of that ;-)
https://github.com/webdriverio/wdio-sauce-service

**Comment by thepianist2** [comment]
ok , that's great , thank you very much for you answer, is working correctly.
