### ISSUE TITLE
[🐛 Bug]: Tag above Examples table doesn't work wdio-cucumberjs

### ISSUE THREAD

**Issue by ldelosreyesm** [webdriverio/webdriverio#10644]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.6.8

### Node.js Version

18.16

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
        maxInstances: 5,
        browserName: 'chrome',
        'goog:chromeOptions': {
            args: ['head', 'disable-gpu']
        },
        acceptInsecureCerts: true
}
```

### What happened?

We I put a tag above Examples table, show Spec Files:  0 passed, 1 skipped, 0 total (0% completed) in 00:00:0
I am triying run this feature:
```
Feature: The Internet Guinea Pig Website
 @thisTagWorks
  Scenario Outline: As a user, I can log into the secure area
     Given I am on the "login" page
     When I login with "<username>" and "<password>"
     Then I should see a flash message saying "<message>"
     @thisTagDoesntWork
     Examples:
       | username | password             | message                        |
       | tomsmith | SuperSecretPassword! | You logged into a secure area! |
       | foobar   | barfoo               | Your username is invalid!      |
```
```
package.json
{
  "name": "my-new-project",
  "type": "module",
  "devDependencies": {
    "@wdio/cli": "^8.6.8",
    "@wdio/cucumber-framework": "^8.6.8",
    "@wdio/local-runner": "^8.6.8",
    "@wdio/spec-reporter": "^8.6.8",
    "chromedriver": "^113.0.0",
    "wdio-chromedriver-service": "^8.1.1"
  },
  "scripts": {
    "wdio": "wdio run ./wdio.conf.js"
  },
  "dependencies": {
    "pixelmatch": "^5.3.0"
  }
}
```

I am using webdriverio and cucumber. Additionally I have tried in protractor and cucumber and it works.

### What is your expected behavior?

The scenario in feature file should be ran.

### How to reproduce the bug.

I could replicate on this repository
https://github.com/ldelosreyesm/wdio_poc

and run 
Mac or Linux
make wrer-module arg=TAG2RUN 
Windows
npm run wdio -- --cucumberOpts.tagExpression=TAG2RUN

### Relevant log output

```typescript
Spec Files:  0 passed, 1 skipped, 0 total (0% completed) in 00:00:00
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for raising this issue @ldelosreyesm 

Can you verify that this works with raw Cucumber? Why would someone want to tag the whole examples map?

**Comment by nextlevelbeard** [comment]
@christian-bromann 
This feature is practical in order to separate context for test running.
Some Examples can be smoke tests while others not.

```gherkin

Feature: The Internet Guinea Pig Website
  @thisTagWorks
  Scenario Outline: As a user, I can log into the secure area
     Given I do stuff
     
    @smoke
    Examples:
       | username | password             | message                        |
       | tomsmith | SuperSecretPassword! | You logged into a secure area! |
       | foobar   | barfoo               | Your username is invalid!      |
       
    @nonSmoke
    Examples:
       | username | password             | message                        |
       | mrssmith | SuperSecretPassword! | You logged into a secure area! |
       | notfoo   | barfoo               | Your username is invalid!      |
       
       
```

**Comment by christian-bromann** [comment]
@nextlevelbeard thanks for verifying, is this a latest Cucumber feature or has it been around for a while?

**Comment by ldelosreyesm** [comment]
> @nextlevelbeard thanks for verifying, is this a latest Cucumber feature or has it been around for a while?
Hi @christian-bromann 
I have ran in protractor with the same version of cucumber, and it works.

**Comment by christian-bromann** [comment]
Thanks for confirming. Just wanted to make sure this is actually a bug in here.

I am guessing this needs to be fixed in the `@wdio/cucumber-framework` package where we probably don't pass on the tags for tables properly.

We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by christian-bromann** [comment]
Fixed in https://github.com/webdriverio/webdriverio/pull/10690
