### ISSUE TITLE
[💡 Feature]: <Ability to terminate all tests (it) in a description section if 1st one fails>

### ISSUE THREAD

**Issue by olenasavinova** [webdriverio/webdriverio#10645]
### Is your feature request related to a problem?

I have a checkout test suite where the 1st step (it section) is "Add product to Cart", then each checkout step is executed in the next 11 it sections. If the 1st step fails, ex: because inventory is out of stock - test keeps running and takes all time.

### Describe the solution you'd like.

Solution would be an ability to quit and move to the next test in test suite 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
@olenasavinova thanks for raising the issue.

The [`bail`](https://webdriver.io/docs/configuration/#bail) and for [Mocha](https://webdriver.io/docs/frameworks#bail) should do what you want.

Let me know if you have further questions. You can join our  [Discord](https://discord.webdriver.io) server for these kind of questions too.
