### ISSUE TITLE
How to implement Selenium Page Object Model and Page Factory Model

### ISSUE THREAD

**Issue by amiya-pattnaik** [webdriverio/webdriverio#1065]
Hi,
It would be great if you can let us know how to impement Page Object Model and Page Factory Model in JavaScript for this below scenarios which JAVA API provides

1. In POM
      import org.openqa.selenium.By;
      By userName = By.name("uid");

2. In Page Factory Model 
   @FindBy(name="uid")   WebElement userName;
     
     import org.openqa.selenium.support.PageFactory;
     PageFactory.initElements(driver, this);

Thanks,
Amiya

**Comment by christian-bromann** [comment]
Please check out our example: https://github.com/webdriverio/webdriverio/tree/master/examples/pageobject
