### ISSUE TITLE
[🐛 Bug]: Impossibility to add an attachment to a test containing a custom command with Allure report and Mocha

### ISSUE THREAD

**Issue by NIBOSAP** [webdriverio/webdriverio#10670]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8

### Node.js Version

18

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
framework: 'mocha',
mochaOpts: {
        ui: 'bdd'
   }
```

### What happened?

Since the new version of Allure reporter 8.5.0, We can't add attachments to a 'test' in the allure report with mocha framework using the afterTest in the wdio config.

With a custom command, I didn't figure out why but the afterStep is not called.

So, when we try to use the afterTest(), the currentTest is empty as the test has been popped ([here](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-allure-reporter/src/reporter.ts#L186)) in the allure-reporter before calling the afterTest() in wdio. It's by design as the documentation has been changed ([here](https://github.com/webdriverio/webdriverio/pull/9704/files#diff-44f5775b821e2834e33f8f03f26549d28c0f46e01d734403c0869c552e6ac2b8R127)).

### What is your expected behavior?

We should be able to add attachments to a test with mocha framework.

### How to reproduce the bug.

1. use Mocha framework
2. Create a basic test 
3. Use addAttachment() in afterTest() in the wdio config.

### Relevant log output

```typescript
nothing
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for filing the issue.

Would you mind providing a reproducible example as in a repository we can clone and run?

@BorisOsipov @epszaw any clues?

**Comment by epszaw** [comment]
@NIBOSAP is it possible to provide any repo, where I'll be able to reproduce the problem?

**Comment by NIBOSAP** [comment]
Hi @epszaw @christian-bromann ,
sorry for the delay. I tried with a simple case and it worked fine :(. So, after investigation, when I add a custom command in the 'it', the screenshot is not part of the allure result. 

Not sure, but it seem that with the custom command the emit command is not triggered, so the '_startStep' in [allure-reporter](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-allure-reporter/src/reporter.ts#L204) is not called. 

Hope it's helpful.

**Comment by christian-bromann** [comment]
Thanks for providing a reproducible example!

We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by epszaw** [comment]
I tried to reproduce the problem with the latest allure reporter, and this is a report I got from your repo:

<img width="1334" alt="image" src="https://github.com/webdriverio/webdriverio/assets/13414205/ffb0a548-4c07-46c6-b6aa-ec624124eb6b">

As far as I understand, the screenshot you expect to was added to the report.

Could you please update the reporter and try it once more?

**Comment by NIBOSAP** [comment]
Fixed with the last version :). Thanks @christian-bromann & @epszaw
