### ISSUE TITLE
[🐛 Bug]: @wdio/allure-reporter: Adding steps to Allure does not work if there is a beforeach hook

### ISSUE THREAD

**Issue by fedoseevGIT** [webdriverio/webdriverio#10672]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.11.0

### Node.js Version

18

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
      browserName: "chrome", // or "firefox", "microsoftedge", "safari"
      "goog:chromeOptions": {
        args: ["--headless"],
      },
    }
```

### What happened?

Hi! I came across a problem that when there are beforeEach hooks, adding steps to Allure breaks down. To quickly reproduce the problem, a repository has been prepared: https://github.com/fedoseevGIT/wdioBug

```
git clone
nvm use
npm install
npm run wdio
```

As a result, an empty gait is displayed in the text where the hook is present
<img width="1188" alt="image" src="https://github.com/webdriverio/webdriverio/assets/64091259/ffc96394-5ead-4cc8-b73a-d630e3297e8f">

I see that at least there is a problem here in [this place](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-allure-reporter/src/reporter.ts#L773). Because of the return in reporter.ts, the error is not thrown [here](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-allure-reporter/src/reporter.ts#L206).

### What is your expected behavior?

Correctly adding steps to allure

### How to reproduce the bug.

```
git clone https://github.com/fedoseevGIT/wdioBug.git
nvm use
npm install
npm run wdio
```

### Relevant log output

```typescript
No useful logs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by fedoseevGIT** [comment]
It seems that adding disableMochaHooks solves the problem, but it still seems there are points that can be improved on this report

**Comment by BorisOsipov** [comment]
Thanks for reporting!

We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by BorisOsipov** [comment]
cc @epszaw

**Comment by epszaw** [comment]
@BorisOsipov assign the issue on me

**Comment by TepmuT13** [comment]
We already have the same bug here https://github.com/webdriverio/webdriverio/issues/10185
Adding _disableMochaHooks:true_ to allure in config file is worked for me, but it wasn't a problem before.

**Comment by BorisOsipov** [comment]
@TepmuT13 This bug is different from the one at https://github.com/webdriverio/webdriverio/issues/10185 :)

**Comment by TepmuT13** [comment]
Oh, sorry. Then I apologize for the misinformation. I thought it was similar error :(

**Comment by epszaw** [comment]
Could you please try to use [`step` method](https://github.com/webdriverio/webdriverio/tree/main/packages/wdio-allure-reporter#custom-steps)? It's a new and much more convenient way to create Allure steps

**Comment by epszaw** [comment]
The method won't help, found the problem source. But, anyway, I recommend to use the method in future

**Comment by epszaw** [comment]
It works correct with `step` method. There is a result in the repo (https://github.com/fedoseevGIT/wdioBug):

<img width="1335" alt="image" src="https://github.com/webdriverio/webdriverio/assets/13414205/31892237-8498-403b-a2fa-bcf80b98101a">

Will open PR to the repo

**Comment by epszaw** [comment]
There is the PR https://github.com/fedoseevGIT/wdioBug/pull/2

**Comment by christian-bromann** [comment]
It seems we can close this. Let me know if the problem still exists.
