### ISSUE TITLE
Dynamically computed capabilities

### ISSUE THREAD

**Issue by hoho** [webdriverio/webdriverio#1068]
The number of browsers in multiremote can depend on the test (I have tests with one, two and three browsers). It would be nice to be able to compute the capabilities dynamically for each instance of runner.js.

**Comment by christian-bromann** [comment]
> The number of browsers in multiremote can depend on the test

Can you specify an example?

> I have tests with one, two and three browsers

I guess you need to create multiple wdio.conf files. Can you think of a better idea?

**Comment by hoho** [comment]
When you test, for example, chats, there are different scenarios for one-to-one chats and group conversations.

Multiple wdio.conf files is the obvious solution, but all the properties in these files will need to be synced manually and I need to call wdio for each wdio.conf file. Another thing is that if I'm, for example, running a test with three browsers in multiremote, I want to vary the browsers (one FF, two IEs / one Chrome, one FF, one IE and so on) and it makes the number of wdio.conf files quite large. The ability to vary the browsers with the command line arguments would be nice.

To solve this, I see (for the moment) a couple of things to do.

The cheapest one is to let capabilities in wdio.conf be a function. If it's a function we might call it and then proceed with the result. It doesn't solve the problem completely, but gives at least some flexibility.

Another thing which could be done is to extend the config with something like that (also nice in a combination with the first one to vary the browsers):
```js
tests: [
    {specs: './test/1/**.js', capabilities: ...},
    {specs: './test/2/**.js', capabilities: ...},
    {specs: './test/3/**.js', capabilities: ...}
],
```

Third thing is to add the ability to extend and modify `ConfigParser`. I tried to monkey-patch `ConfigParser.prototype.getCapabilities` from `onPrepare` callback, but it applies for the main process only, and doesn't affect the runner child process.

Fourth (and probably most difficult and controversial) thing is to add some API to readjust the capabilities dynamically. For example some method like `.resetCapabilities(..)` which might be called from some place like `before(...)` in the test case and will shut down the current sessions and start a new runner with the new ones.

**Comment by christian-bromann** [comment]
Sorry for catching up so late. Here are my answers:

> The ability to vary the browsers with the command line arguments would be nice.

I don't think there is a proper way to pass capabilities as cli arguments.

> The cheapest one is to let capabilities in wdio.conf be a function.

There is no need for that just define that function somewhere and generate the output directly:
```js
// wdio.conf.js
capabilities: generateCaps(),
// ...
``

> Another thing which could be done is to extend the config with something like that

This already works the other way around. You can specify certain specs per capability.

> Third thing is to add the ability to extend and modify ConfigParser

Not sure if this is a good idea. The configParser is an internal module

> in the test case and will shut down the current sessions and start a new runner with the new ones.

You can achieve that by a good spec file structure.

In general, if you want to run multiple different wdio test runs, split your configs like that: 1. have a main config file where everything goes into that all config files should have. 2. create multiple wdio.conf files that inherit from the main config file like this:
```js
var merge = require('deepmerge');
var mainConfig = require(':/main.wdio.conf');

export.config = merge(mainConfig, {
  // your config
  // ...
};
```

**Comment by Ankith3796** [comment]
I am working on wdio and i have a wdio.config file with 4 browser capabilities. I want to dynamically provide the browser name for the test case keeping the 4 browser names as such. How can i do it?

**Comment by christian-bromann** [comment]
modify the config in the beforeSession hook

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have further questions.

**Comment by kajmagnus** [comment]
@hoho I dealt with the many-wdio-config-files, by importing a `wdio.conf` file for one browser only, and overwriting its `capabilities` field to add more browsers, and I keep all other settings:

https://github.com/debiki/talkyard/blob/master/tests/e2e/wdio.2chrome.conf.ts

and there's a *...3chrome...* too.

@Ankith3796 if you look at the `wdio.2chrome.conf.ts` file above, you'll see that the browser name (Chrome, FF etc) is read dynamically from a `settings` file, which in turn parses command line arguments, like `--ff` for "use Firefox". Not sure if this is the best way to do it, but works, anyway.

(B.t.w. @hoho  I'm also testing group chats in sometimes 2, sometimes 3 browsers — if your chat is online anywhere, or any GitHub repo, it'd be interesting to have a look?)
