### ISSUE TITLE
[🐛 Bug]: wdio V8 Beforesession imports not working  

### ISSUE THREAD

**Issue by troyyer** [webdriverio/webdriverio#10714]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.11.2

### Node.js Version

19.9.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
beforeSession: function (config,capabilities, specs) {
        require("expect-webdriverio");
        const { faker } = require('@faker-js/faker');
        global.faker = faker;
        global.wdioExpect = global.expect;
        global.expectChai = require("chai").expect;
        global.assertChai = require("chai").assert;
    }
```

### What happened?

(please note that i cant access the discord service from my corporate laptop hence why i am raising this here and not in the discord channel) 
I am upgrading my wdio framework from V7 to V8. currently in V7, i have in the wdio config file a section within the beforeSession to import certain modules such as chai and faker-js
in V7 once i have done this, within my test scripts i am able to use these 2 without importing them at the start of the test script 
eg 
within the test script i can use the faker module as is
`
 const Mobilefortest =  faker.phone.number('+614########')  `

i have created a branch for my code to upgrade to v8. Now in this branch when i run my test scripts they fail with either 
ReferenceError: assertChai is not defined 
or 
ReferenceError: faker is not defined

I'm unsure about how to fix this. Any direction on what changes I need to action would be greatly appreciated.

### What is your expected behavior?

on upgrading from v7 of webdriverio to v8 i can run my test scripts importing of modules from within the beforeSession of the wdio config file in a similar way 

### How to reproduce the bug.

create a new wdio code project using the wdio get started guide and with creating a sample pageobject script
within the wdio.conf.js file 

create a beforeSession section

```

beforeSession: function (config,capabilities, specs) {
         import { expect } from 'expect-webdriverio';
        import { faker } from '@faker-js/faker';

        global.faker = faker;
       
        global.wdioExpect = global.expect;
        global.expectChai = require("chai").expect;
        global.assertChai = require("chai").assert;
  
        },
```

within the generated e2e.sample.js file 
```
import LoginPage from '../pageobjects/login.page.js'
import SecurePage from '../pageobjects/secure.page.js'

describe('My Login application', () => {
    it('should login with valid credentials', async () => {

        await LoginPage.open()
        const Mobilefortest =  faker.phone.number('+614########')
        await assertChai.fail("making the script fail")
        await LoginPage.login('tomsmith', 'SuperSecretPassword!')
        await expect(SecurePage.flashAlert).toBeExisting()
        await expect(SecurePage.flashAlert).toHaveTextContaining(
            'You logged into a secure area!')
    })
})
```

### Relevant log output

```typescript
[chrome 114.0.5735.110 windows #0-0] faker is not defined
[chrome 114.0.5735.110 windows #0-0] ReferenceError: faker is not defined
[chrome 114.0.5735.110 windows #0-0]     at Context.<anonymous> (file:///C:/code/wdio8/test/specs/example.e2e.js:8:32)
[chrome 114.0.5735.110 windows #0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> I'm unsure about how to fix this. Any direction on what changes I need to action would be greatly appreciated.

Have you tried to move these imports to the top:

```ts
import { expect } from 'expect-webdriverio';
import { faker } from '@faker-js/faker';
```

Have you tried to assign the variables to `globalThis`?

```ts
        global.faker = faker;
       
        global.wdioExpect = global.expect;
        global.expectChai = require("chai").expect;
        global.assertChai = require("chai").assert;
```

I will go ahead and close this as this doesn't seem to be an issue with WebdriverIO. It would help if you could provide a reproducible example. Also I recommend to join the [Discord](https://discord.webdriver.io) server for these kind of questions. This is not necessary a WebdriverIO related issue.

**Comment by troyyer** [comment]
as mentioned i dont have access to Discord from my corporate network :'(
In any case thanks for your initially suggestions as it provided me further directions. Unfortunately those suggestions still get the same issue as before thou I was able to find some direction with googling and I had a look at this documentation from the webite https://webdriver.io/docs/assertion/#global
in the documentation it had used async with an arrow funtion within the config file so when i changed it to async with await this got my framework working
```
     beforeSession: async (config,capabilities, specs) => {
         await import('expect-webdriverio');
         global.wdioExpect = global.expect;
         const { faker } = await import('@faker-js/faker');
          global.faker = faker;
          const chai = await import('chai');
          global.expectChai = chai.expect;
          global.assertChai = chai.assert;
  
        },
```
Unsure why when i updated from v6 to v7 the same didnt fail since v7 went with async.
the earlier pattern i mention was a pattern I have been using from a few tutorials from wdio users have provided 
https://github.com/jpott77/webdriverio/blob/master/wdio.conf.js
Also a qustion, should the templated config file when auto generated thru the cli, should it have async now in the function blocks?

**Comment by christian-bromann** [comment]
> Also a qustion, should the templated config file when auto generated thru the cli, should it have async now in the function blocks?

Everytime you do async operations and use the keyworkd `await` you have to add `async` in front of the function.
