### ISSUE TITLE
[🐛 Bug]: Expect toHaveText, toHaveTextContaining doesn't work while comparing with getAttribute Value  

### ISSUE THREAD

**Issue by ktsivaprakash** [webdriverio/webdriverio#10713]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.8.6

### Node.js Version

18.16.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  browserName: 'chrome',
  browserVersion: 'latest',
  platformName: 'Windows 11'
}
```

### What happened?

Using getAttribute method I can able to get an attribute from a DOM-element based on the given attribute name.
But When I try to compare the Expected Attribute Value with Actual Actual Value using toHaveText, toHaveTextContaining expect method it returns Undefined, since both toHaveText & toHaveTextContaining internally calls getText() method, which is not applicable to attribute value

### What is your expected behavior?

Value derived from the getAttribute() method should be able to compare using expect matchers

### How to reproduce the bug.

In the same code snippet given in the link
https://webdriver.io/docs/api/element/getAttribute/

using getAttribute('method'), i am getting the value in attribute method
but when i try to verify the value of method is post using 
await expect(attr).toHaveText('post');
it return undefined, since getText() is not applicable 

### Relevant log output

```typescript
Expected: "post"
Received: undefined
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> Using getAttribute method I can able to get an attribute from a DOM-element based on the given attribute name.

To validate an attribute of a DOM element please use https://webdriver.io/docs/api/expect-webdriverio#tohaveattribute

Join our [Discord](https://discord.webdriver.io) if you have further questions.
