### ISSUE TITLE
Unsuccessful retries count shown as failed in "wdio-html-nice-reporter

### ISSUE THREAD

**Issue by GPSC1** [webdriverio/webdriverio#10724]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.0.0

### Node.js Version

16

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
"wdio-html-nice-reporter": "^7.7.12",
"webdriverio": "^8.0.0"}
```

### What happened?

Implemented "Retries" in cucumber project using "wdio-nice-html-reporter.
Issue- If i have 1 test scenario which gets retried 3 times and gets passed on 3rd attempt then test report is not supposed to show this test scenario as failed but currently, Failed test cases count is shown as 2(failed retry attempt count) in report. 

### What is your expected behavior?

1. If 1 test scenario is attempted thrice and passed on 3rd attempt then test scenario should be shown as passed
2. If 1 test scenario is attempted thrice and never passed then failed test cases count should be just 1.

### How to reproduce the bug.

![MicrosoftTeams-image (53)](https://github.com/webdriverio/webdriverio/assets/112697496/a3d9f1fa-acbb-4a0e-9a35-1917a9ad4107)

### Relevant log output

```typescript
Attached screenshot of report.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for raising the issue.

Unfortunately this issue is related to the `wdio-html-nice-reporter` which is not part of this repository and a 3rd party community project. I recommend to raise the issue in that project. Thanks!
