### ISSUE TITLE
[🐛 Bug]: Type extensions are no longer working

### ISSUE THREAD

**Issue by erwinheitzman** [webdriverio/webdriverio#10723]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

16.20

### Mode

WDIO Testrunner

### What happened?

In the following PR https://github.com/webdriverio/webdriverio/pull/10689 a change was made to how a TypeScript config file is treated. 

As you can see in that PR the following line was changed: https://github.com/webdriverio/webdriverio/blob/0702ebfb41b6ec5598cb3f4ebe9bd50765b9cf6d/packages/wdio-cli/src/commands/run.ts#L180

from:
```
NODE_OPTIONS += ' --loader ts-node/esm/transpile-only --no-warnings'
```
to:
```
NODE_OPTIONS += ' -r ts-node/register --loader ts-node/esm/transpile-only --no-warnings'
```

This change results in custom type extensions no longer being taken into account.

example
```
declare module WebdriverIO {
    interface Browser {
        setWindowSizeMD: () => Promise<void>; // no longer works
    }
}
```

According to the ts-node docs it looks like we need to use `node -r ts-node/register` or `node --loader ts-node/esm/transpile-only` but not both together. 
Reference: https://github.com/TypeStrong/ts-node#node-flags-and-other-tools

### What is your expected behavior?

I expect my types to work.

### How to reproduce the bug.

install the latest version and extend you browser type with a custom command while using the command in a TypeScript config (beforeTest hook in my case), then run your tests.

### Relevant log output

```typescript
wdio.e2e.conf.ts:40:17 - error TS2551: Property 'setWindowSizeMD' does not exist on type 'Browser'. Did you mean 'setWindowSize'?
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

Let's get this fixed and make sure we have tests for this. Mind creating a minimal reproducible example?

We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by erwinheitzman** [comment]
Would it be okay to revert this line back to how it was or do we require a different solution?

**Comment by christian-bromann** [comment]
Do you have a reproducible example for me to take a look. We can revert the change as long as we can ensure that CJS + TypeScript works.

**Comment by erwinheitzman** [comment]
I tried with the latest version but the latest version is completely broken for me sadly. I will try to revert to an older version to get an example out.

**Comment by christian-bromann** [comment]
> If I remove nuxt, it will try to run and then error on `cannot find Chrome binary`

This will be resolved with https://github.com/webdriverio/webdriverio/pull/10767
