### ISSUE TITLE
[🐛 Bug]: @wdio/shared-store-service not working in multi-remote

### ISSUE THREAD

**Issue by ddNils** [webdriverio/webdriverio#10729]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7

### Node.js Version

16

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    userA: {
      capabilities: {
        browserName: 'chrome',
        acceptInsecureCerts: true,
        'goog:loggingPrefs': { browser: 'ALL' },
        'goog:chromeOptions': {
          args: ['--disable-gpu', '--window-size=1440,800', '--enable-logging-info']
        }
      },
      baseUrl: process.env.CRM_FRONTEND_E2E_BASEURL
    },
    userB: {
      capabilities: {
        browserName: 'chrome',
        acceptInsecureCerts: true,
        'goog:chromeOptions': {
          args: ['--disable-gpu', '--window-size=1440,800']
        }
      },
      baseUrl: process.env.WEBSHOP_FRONTEND_E2E_BASEURL
    }
  },
```

### What happened?

Running test with multi-remote causes the code in launcher to break on `forEach`, as capabilities is in this case an object with `userA`, `userB` (see above config). 
```typescript
        capabilities.forEach((capability) => {
            capability['wdio:sharedStoreServicePort'] = port
        })
```
I did experiment a bit and got the code working for set and get, but it always returns 'value,value' to me. Which I think is caused by the two browser objects. 

### What is your expected behavior?

Either the capabilities in the onPrepare hook should really be the capabilities (not the two browsers). or there should be some code to handle the two browser objects in get down into their capabilities.

At the end of the day, I want the shared-store-service to work with multiple browsers, because that's what it is there for, right? 

### How to reproduce the bug.

I will try to set something up, if you are not able to reproduce this yourselfes.

### Relevant log output

```typescript
TypeError: capabilities.forEach is not a function
    at SharedStoreLauncher.onPrepare (...\e2e-tests\node_modules\@wdio\shared-store-service\build\launcher.js:16:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ...\e2e-tests\node_modules\@wdio\cli\build\utils.js:38:17
    at async Promise.all (index 1)
    at async Launcher.run (...\e2e-tests\node_modules\@wdio\cli\build\launcher.js:86:13)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by ddNils** [comment]
Might be a similar issue than this one: https://github.com/webdriverio/webdriverio/issues/5906#issuecomment-708694201

**Comment by christian-bromann** [comment]
Thanks for reporting!



We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!
