### ISSUE TITLE
[🐛 Bug]: upgrading TS to 5.1 causes type errors - unable to resolve @wdio/globals/types

### ISSUE THREAD

**Issue by goosewobbler** [webdriverio/webdriverio#10754]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.13.1

### Node.js Version

18.16.0

### Mode

WDIO Testrunner

### What happened?

Updating the TS version from 5.0.x in `wdio-electron-service` to the latest 5.1.x causes the build to fail with compilation errors.  I suspect it might be something to do with [this TS change](https://devblogs.microsoft.com/typescript/announcing-typescript-5-1/#explicit-typeroots-disables-upward-walks-for-node_modules-types), but as yet, I have not been able to work out what is going on.  

The root error seems to be `Cannot find type definition file for '@wdio/globals/types'`.  It might also be related to https://github.com/webdriverio/webdriverio/issues/9160

Issue: https://github.com/webdriverio-community/wdio-electron-service/issues/105

PR reproducing the issue: https://github.com/webdriverio-community/wdio-electron-service/pull/106

GH action output:
https://github.com/webdriverio-community/wdio-electron-service/actions/runs/5579900434/jobs/10196072974

### What is your expected behavior?

The update of TS should not cause the build to fail.

### How to reproduce the bug.

Check out the `ts-update` branch of the [`wdio-electron-service`](https://github.com/webdriverio-community/wdio-electron-service) repo, then run:

`pnpm init-dev && pnpm build`

### Relevant log output

```typescript
See https://github.com/webdriverio-community/wdio-electron-service/issues/105
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by goosewobbler** [comment]
Fixed - the issue was just misconfigured TSconfig files across the different packages in the repo.

**Comment by billnbell** [comment]
I get this too Cannot find type definition file
