### ISSUE TITLE
[🐛 Bug]: "logs.map is not a function" error when tests are running 

### ISSUE THREAD

**Issue by carri747** [webdriverio/webdriverio#10763]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.32.1

### Node.js Version

18.15.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
buildConfig.capabilities = [
    {
        browserName: 'chrome',
        'goog:chromeOptions': {
            args: [
                '--headless',
                '--disable-infobars',
                '--no-sandbox',
                '--disable-gpu',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage',
                '--window-size=1920,1080',
                `--user-agent=${userAgent}`,
                '--remote-allow-origins=*'
            ],
            prefs: {
                ['profile.default_content_setting_values.images']: 2
            }
        }
    }
];
```

### What happened?

Hi, I need help with this error community. Thanks in advance.
Sometime when we run our automation project appear this error
![image](https://github.com/webdriverio/webdriverio/assets/22347831/59fba1c7-9101-4f47-8557-478335a3e3a6)

We don't know why sometimes works sometime not, we have this setup in wdio.conf.ts

`specs: [
        ['./src/featuresResetSale/**/*.feature'],
        ['./src/features/georestrictions/**/*.feature'],
        ['./src/features/admin/**/*.feature'],
        ['./src/features/api/**/*.feature'],
        ['./src/features/web/**/*.feature'],
        ['./src/features/webResponsive/**/*.feature']
    ],
...
 maxInstances: 5, 
...
  services: [
        ['selenium-standalone', { drivers: { firefox: 'latest', chrome: 'latest', chromiumedge: 'latest' } }],
        'intercept',
        'shared-store',
        'devtools'
    ],`

I've detected that when I reduce the number of instances from 5 to 1 didn't have this error or at least is less probable.

When this error appear the rest of the instances that it's running start to have errors (blank pages, timeout ,...)

### What is your expected behavior?

Not have this error when the automation project run with more than one instances

### How to reproduce the bug.

As I said before this error is randomly and I don't have any example to reproduce that. Sorry for that 

### Relevant log output

```typescript
See picture attached
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for raising the issue!

> As I said before this error is randomly and I don't have any example to reproduce that. Sorry for that

Without a reproducible example there is nothing I can do then. There is not even a stack trace provided that would allow any further investigation. I recommend doing some more debugging to provide more information about what is going on.

At this point I can only close the issue. I am happy to re-open if more information can be provided but so far this is not actionable.

**Comment by carri747** [comment]
Hi Christian, thanks for your reply.
During this time, I've tried several option including upgrade wdio7 to wdio8 and in wdio8 this issue continue. this issue not happen every time in my project but time to time we have this error and after this error all the scenarions fail because the reload session is not working. 
I've located the method that is failing and a potential solution for that. I know that the better option is has a example that you can reproduce the error but I don't know how to prepare this example because it's a random error.
My proposal:
The issue is here:
@wdio library, runner folder and index.js line 309
![image](https://github.com/webdriverio/webdriverio/assets/22347831/11055c77-8ed1-4c7b-a4d6-6f56c11a88ed)

previous to this line "logs" is checking that is not null and has more tha one element but in my case the error is "logs.map" is not a function and as you know this occurs when you call the map() method on a non-array object.
My solution is add a new conditions more and check if "logs" is an array, the impact of this in this code will be minimun and with this option wdio will be assure that not fail. 
something similar was added in the version8, a new condition was added in this "if" sentence

Left picture wdio7, right picture wdio8


![image](https://github.com/webdriverio/webdriverio/assets/22347831/e678bf5b-c78b-4087-a2ba-35f4b88396b8)

please consider add this condition in following version the impact as far as I know will be minimum and with this condition will be avoid strange errors like mine

**Comment by carri747** [comment]
@christian-bromann  thanks for your reply 
here the PR adding the new condition 
https://github.com/webdriverio/webdriverio/pull/10997
