### ISSUE TITLE
Missing wdio-mocha-framework dependency?

### ISSUE THREAD

**Issue by jeffcharles** [webdriverio/webdriverio#1077]
Hi,

When I run wdio, I get `Couldn't load "wdio-mocha-framework" framework. You need to install it with `$ npm install wdio-mocha-framework`!`. Should this be a dependency instead of a devDepedency?

**Comment by christian-bromann** [comment]
No, depending of which framework you want to use you need to install the adapter separately. Sorry we haven't mentioned that on our website because we just released v4.
