### ISSUE TITLE
how to send CTRL + A

### ISSUE THREAD

**Issue by tav1313** [webdriverio/webdriverio#1079]
no info at the documentation \ src ((

**Comment by christian-bromann** [comment]
`browser.setValue('input', ['CTRL', 'A'])`

**Comment by tav1313** [comment]
thanks for your answer, Christian, but it just prints CTRLA ((
should I try other instruction?

**Comment by christian-bromann** [comment]
Sorry, ctrl is not the right metakey, try `browser.setValue('input', ['Control', 'A'])`

**Comment by tav1313** [comment]
Christian, I tried it before - no lucky - such combination just puts 'A' to the input, I use doubleclick for the moment to select  input's content(in combination with clearElement). But it would be nice to have a skill to send CTRL+A smoothly

thanks

**Comment by christian-bromann** [comment]
@tav1313 it depends on which OS you are running the command. Maybe `browser.setValue('input', ['Meta', 'A'])` works better

**Comment by tav1313** [comment]
win 7 x64, webdriverio 3.4.0, ie 10
just prints '   A'

**Comment by tav1313** [comment]
any news for that issue?

**Comment by christian-bromann** [comment]
No, maybe someone on the internet found a solution. This is clearly not a bug of WebdriverIO though.

**Comment by MethodGrab** [comment]
Try using lowercase 'a':
```js
browser.setValue('input', ['Control', 'a'])
```

**Comment by tario-yang** [comment]
Our world is not perfect -- from [chromedriver_status](https://chromium.googlesource.com/chromium/src/+/master/docs/chromedriver_status.md) , you will see both `browser.keys()` and `browser.actions()` are incomplete. Also, `browser.setValue()` is used to set value for a `input` or `textarea`. So, 

> browser.setValue('input', ['Control', 'a'])

cannot resolve the issue. From the debug information, you can get it.
![image](https://user-images.githubusercontent.com/3666914/49073356-3d622780-f26d-11e8-8bf9-ec06ea18b212.png)

**Comment by christian-bromann** [comment]
@tario-yang WebdriverIO can only work according to the WebDriver or JSONWire protocol standard here. If the driver is behaving inconsistently the bug has to get reported there and not here.

**Comment by kamleshzanjadSynerzip** [comment]
How to type Control - using webdriverIo. Inn chrome browser i have to zoom out or zoom in

**Comment by ksiddharthaee** [comment]
Any luck with this issue? I'm also trying to achieve Control - using wdio for zooming ot my web page.

**Comment by kamleshzanjadSynerzip** [comment]
Please add "--force-device-scale-factor=0.9"
in connfig file

capabilities: [{
///maxInstances: 3, //argv.ChromeParallelExeutionCount
maxInstances: argv.ChromeParallelExeutionCount,
browserName: "chrome",
// chromeOptions: {
// prefs: {
// //'download.default_directory': downloadDir
// }
// },
applicationCacheEnabled: true,
webStorageEnabled: true,
"goog:chromeOptions": {
args: [
"--start-maximized",
"--disable-infobars",
"--force-device-scale-factor=0.9"
],
prefs: {
'download.default_directory': downloadDir
}
}
}],

refer below url for unicode
//https://w3c.github.io/webdriver/#keyboard-actions unicode characters
public PressPageDownKey() {
logger.debug("Inside method: CommonUtil.pressControlKey");
browser.keys('\uE00F');
this.staticWait(2000);
}
public PressTabKey() {
logger.debug("Inside method: CommonUtil.PressTabKey");
browser.keys('\uE004');
}

public pressControlEndKey() {
logger.debug("Inside method: CommonUtil.pressControlEndKey");
browser.keys(['Control', '\uE010']);
}
public pressEnterKey() {
browser.keys('\uE007'); // The unicode character for 'enter' is '\uE007'.
}
public pressControlKey() {
logger.debug("Inside method: CommonUtil.pressControlKey");
//browser.pressKeycode(17);
browser.keys('Control');
//browser.keys("Ctrl");//not workinng
// this.staticWait(1000);
//browser.keys('\u2303');
// The unicode character fo// r 'enter' is '\uE007'.
}
public pressShiftKey() {
logger.debug("Inside method: CommonUtil.pressShiftKey");
//browser.pressKeycode(17);
// browser.keys("Shift");
this.staticWait(1000);
browser.keys('\u21E7');
// The unicode character for 'enter' is '\uE007'.
}




<https://www.gomercatus.com/>
[image: Mercatus Website] <https://www.gomercatus.com/>

Regards,
Kamlesh Zanjad,
Test Architect,
Mercatus Solutions India Pvt Ltd,
Pune, Maharashtra, India

**Comment by iamamonkeyman** [comment]
That worked for me, chrome browser: 
browser.keys(['\uE009', 'a']);

**Comment by christian-bromann** [comment]
> browser.keys(['\uE009', 'a']);

Which is the same as calling `browser.keys(['Control', 'a']);`

**Comment by jasmin-husadzic-apfm** [comment]
@christian-bromann  Any idea for CTRL + F5? `browser.keys(['\ue009', '\ue035']);` not give desired behavior.
