### ISSUE TITLE
[🐛 Bug]: [Chrome] Error when trying to find element, unexpected response

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#10843]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

20

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
  "browserName": "chrome"
}
```

### What happened?

When trying to find an element, in certain cases, tests error with 
```shell
elemResponse.map is not a function
```

### What is your expected behavior?

webdriverIO should handle error cases when finding elements 

### How to reproduce the bug.

https://github.com/webdriverio/webdriverio/blob/929f86f190b6f7401a597dafee49622c37b05dbe/packages/webdriverio/src/utils/getElementObject.ts#L111-L119

```ts
   // Simulate response from ChromeDriver
   elemResponse = {
    "error": "no such element",
    "message": "no such element: No node with given id found\n  (Session info: headless chrome=116.0.5845.50)",
    "stacktrace": "#0 0x55ddf07ae623 <unknown>\n#1 0x55ddf04d0f67 <unknown>\n#2 0x55ddf04b8527 <unknown>\n#3 0x55ddf04b6a94 <unknown>\n#4 0x55ddf04b700f <unknown>\n#5 0x55ddf04b6f64 <unknown>\n#6 0x55ddf04ddf16 <unknown>\n#7 0x55ddf04d5a34 <unknown>\n#8 0x55ddf04d4643 <unknown>\n#9 0x55ddf04d6d40 <unknown>\n#10 0x55ddf04d6dfc <unknown>\n#11 0x55ddf0514de8 <unknown>\n#12 0x55ddf05151b1 <unknown>\n#13 0x55ddf050b1a3 <unknown>\n#14 0x55ddf0535f3d <unknown>\n#15 0x55ddf050acf6 <unknown>\n#16 0x55ddf05360de <unknown>\n#17 0x55ddf054e249 <unknown>\n#18 0x55ddf0535ce3 <unknown>\n#19 0x55ddf05097bb <unknown>\n#20 0x55ddf050a55e <unknown>\n#21 0x55ddf076f648 <unknown>\n#22 0x55ddf0773547 <unknown>\n#23 0x55ddf077ddbc <unknown>\n#24 0x55ddf0774176 <unknown>\n#25 0x55ddf074251f <unknown>\n#26 0x55ddf0798458 <unknown>\n#27 0x55ddf0798628 <unknown>\n#28 0x55ddf07a74f3 <unknown>\n#29 0x7f60e12a0044 <unknown>\n"
   }

    const elements = elemResponse.map((res: ElementReference | Element | Error, i) => {
        /**
         * if we already deal with an element, just return it
         */
        if ((res as WebdriverIO.Element).selector) {
            return res
        }
```

```json
{
  "error": "no such element",
  "message": "no such element: No node with given id found\n  (Session info: headless chrome=116.0.5845.50)",
  "stacktrace": "#0 0x55ddf07ae623 <unknown>\n#1 0x55ddf04d0f67 <unknown>\n#2 0x55ddf04b8527 <unknown>\n#3 0x55ddf04b6a94 <unknown>\n#4 0x55ddf04b700f <unknown>\n#5 0x55ddf04b6f64 <unknown>\n#6 0x55ddf04ddf16 <unknown>\n#7 0x55ddf04d5a34 <unknown>\n#8 0x55ddf04d4643 <unknown>\n#9 0x55ddf04d6d40 <unknown>\n#10 0x55ddf04d6dfc <unknown>\n#11 0x55ddf0514de8 <unknown>\n#12 0x55ddf05151b1 <unknown>\n#13 0x55ddf050b1a3 <unknown>\n#14 0x55ddf0535f3d <unknown>\n#15 0x55ddf050acf6 <unknown>\n#16 0x55ddf05360de <unknown>\n#17 0x55ddf054e249 <unknown>\n#18 0x55ddf0535ce3 <unknown>\n#19 0x55ddf05097bb <unknown>\n#20 0x55ddf050a55e <unknown>\n#21 0x55ddf076f648 <unknown>\n#22 0x55ddf0773547 <unknown>\n#23 0x55ddf077ddbc <unknown>\n#24 0x55ddf0774176 <unknown>\n#25 0x55ddf074251f <unknown>\n#26 0x55ddf0798458 <unknown>\n#27 0x55ddf0798628 <unknown>\n#28 0x55ddf07a74f3 <unknown>\n#29 0x7f60e12a0044 <unknown>\n"
}
```

### Relevant log output

```typescript
elemResponse.map is not a function
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@nextlevelbeard thanks for raising the issue.

Can you provide a minimal reproducible example for this please?

**Comment by christian-bromann** [comment]
I will go ahead and close this, happy to re-open when a reproducible example can be provided.

**Comment by rsshilli** [comment]
FWIW, I received this too on our CICD server. I'm not sure how to reproduce it. I'm not sure if it's consistent. I'm guessing chromedriver has to respond with an error or something.

**Comment by nextlevelbeard** [comment]
@rsshilli @christian-bromann 

Created a simple fix, tested this locally and stopped seeing the error.

The fix prevents the crash, the error still occurs, was getting this consistently, Chrome/Chromedriver keeps denying the element exists, despite actually being there on the DOM.
 
I believe with this fix webdriverIO handles the error gracefully and attempts to re-fetch it, which is all we can do.

**Comment by rsshilli** [comment]
@nextlevelbeard Nice!

I was getting this error consistently when running Webdriver.io in a Linux docker container (but not when running the test on Windows).

Without upgrading Webdriver.io, I changed the way I was scrolling to elements (see more here https://github.com/webdriverio/webdriverio/issues/10369#issuecomment-1711992753) and this error magically went away. I wish I had more information, but that might be useful to the next person who encounters this. Try upgrading first to get @nextlevelbeard 's fix, then consider whether the element in question is in the viewport.

**Comment by rsshilli** [comment]
Hmm... it shows up randomly now.

I suspect this issue is related to Chrome randomly returning this error message that caused me to get off of WebDriver 7. https://bugs.chromium.org/p/chromedriver/issues/detail?id=4440

Ryan
