### ISSUE TITLE
[🐛 Bug]: <More failed expect>

### ISSUE THREAD

**Issue by rebajz** [webdriverio/webdriverio#10859]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.14.4

### Node.js Version

16.20.0 64bit

### Mode

Standalone Mode

### What happened?

in config
bail: 0,
framework: 'mocha',
used typescript 5.1.6

in test:
describe('My Login application', () => {
    it('should login with valid credentials', async () => {
        console.log('My own comment in IT')
        await LoginPage.open()

        await LoginPage.login('tomsmith', 'SuperSecretPassword!')
        await expect(SecurePage.flashAlert).toBeExisting()
        await expect(SecurePage.flashAlert).toHaveTextContaining(
            'You logged into a secure area!')
        console.log('Second comment before expect', __dirname);
        await expect(true).toBe(true);
        console.log('Third comment after first expect (passed)');
        await expect(true).toBe(false);
        console.log('Fourth comment after second expect (failed)');
        await expect(false).toBe(true);
        console.log('Fifth comment after last expect (failed)');
    })
})

in allure report i see only this:
.........Console Logs.........

My own comment in IT
Second comment before expect C:\_git\demo-app\testing\test\specs
Third comment after first expect (passed)

Therefore when second expect in code will failed, after code not continue (not show console.log ).

### What is your expected behavior?

when bail: 0, continue in same IT.

.........Console Logs.........

My own comment in IT
Second comment before expect C:\_git\demo-app\testing\test\specs
Third comment after first expect (passed)
Fourth comment after second expect (failed)
Fifth comment after last expect (failed)

### How to reproduce the bug.

/**
 * test with page objects
 */
import LoginPage from '../pageobjects/login.page'
import SecurePage from '../pageobjects/secure.page'

describe('My Login application', () => {
    it('should login with valid credentials', async () => {
        console.log('My own comment in IT')
        await LoginPage.open()

        await LoginPage.login('tomsmith', 'SuperSecretPassword!')
        await expect(SecurePage.flashAlert).toBeExisting()
        await expect(SecurePage.flashAlert).toHaveTextContaining(
            'You logged into a secure area!')
        console.log('Second comment before expect', __dirname);
        await expect(true).toBe(true);
        console.log('Third comment after first expect (passed)');
        await expect(true).toBe(false);
        console.log('Fourth comment after second expect (failed)');
        await expect(false).toBe(true);
        console.log('Fifth comment after last expect (failed)');
    })
})

### Relevant log output

```typescript
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\_git\demo-app-wdio> cd .\testing\
PS C:\_git\demo-app-wdio\testing> npm run wdio
         
> wdio run ./Workflows/wdioConfBrowser.ts


Execution of 2 workers started at 2023-08-03T17:44:21.724Z

[0-0] RUNNING in chrome - file:///C:/_git/demo-app-wdio/testing/test/specs/test.e2e.ts

DevTools listening on ws://127.0.0.1:49512/devtools/browser/299727cb-76c5-4cfd-b4f4-f971420f4e9e
 Hook executed: "before all" hook in "{root}"
 ------------------------------------------------------------------
 Suite started:                                                    
   » \test\specs\test.e2e.ts                                       
 My Login application
[0-0] My own comment in IT
[0-0] Second comment before expect C:\_git\demo-app-wdio\testing\test\specs
[0-0] Third comment after first expect (passed)
[0-0] Error in "My Login application.should login with valid credentials"
Error: expect(received).toBe(expected) // Object.is equality

Expected: false
Received: true
    at C:\_git\demo-app-wdio\testing\test\specs\test.e2e.ts:19:28
    at Generator.next (<anonymous>)
    at fulfilled (C:\_git\demo-app-wdio\testing\test\specs\test.e2e.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    ✖ should login with valid credentials » [ \test\specs\test.e2e.ts ]
 Hook executed: "after all" hook in "{root}"
[0-0] FAILED in chrome - file:///C:/_git/demo-app-wdio/testing/test/specs/test.e2e.ts

 "spec" Reporter:
------------------------------------------------------------------
Running: chrome (v115.0.5790.110) on windows
Session ID: 17959deebf7fe1dbc3ecae546b5bc279

» \test\specs\test.e2e.ts
My Login application
   ✖ should login with valid credentials

      .........Console Logs.........
         My own comment in IT
          Second comment before expect C:\_git\demo-app-wdio\testing\test\specs
          Third comment after first expect (passed)


1 failing (4.1s)

1) My Login application should login with valid credentials
expect(received).toBe(expected) // Object.is equality

Expected: false
Received: true
Error: expect(received).toBe(expected) // Object.is equality

Expected: false
Received: true
    at C:\_git\demo-app-wdio\testing\test\specs\test.e2e.ts:19:28
    at Generator.next (<anonymous>)
    at fulfilled (C:\_git\demo-app-wdio\testing\test\specs\test.e2e.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)


Spec Files:      0 passed, 1 failed, 1 skipped, 2 total (100% completed) in 00:00:18

PS C:\_git\demo-app-wdio\testing>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> Therefore when second expect in code will failed, after code not continue (not show console.log ).

That is the expected behavior. The assertion libraries stops the test as soon as the first assertion fails.
