### ISSUE TITLE
capabilities values overwritten  

### ISSUE THREAD

**Issue by rajivnw** [webdriverio/webdriverio#10862]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7,8

### Node.js Version

18

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  "platformName": "android",
  "appium:udid": "[assigning in hook onWorkerStart]",
  "appium:app": "Some-App.app.zip",
  "appium:automationName": "uiAutomator2",
}
```

### What happened?

I have 2 feature files and set the maxInstance 2 in order to run parallel. Idea is, let say I have 10 tests in each feature file (total 20) so 10 can run on one device and other 10 run on different device.

When I start the execution, I can see a message in console "Execution of 2 workers started at xxxxxxxx".

In onWorkerStart Hook I setup the udid of the device and set the cid to identify capabilities in other hooks as below:

```
 onWorkerStart: function (cid, caps, specs, args, execArgv) {
if(cid.includes("0-0")){
caps["appium:udid"]="device_one_udid";
}

if(cid.includes("0-1")){
caps["appium:udid"]="device_second_udid";
}
caps["wdio:cid"]=cid;

    },
```
now in the beforeSession hook its only have capabilities set in "0-1" worker thread for both "0-0" and "0-1" thread and overwritten  "0-0" worker thread capabilities.

```
beforeSession: function (config, capabilities, specs) {
const cid=capabilities["wdio:cid"]
console.log("capabilities  cid :  "+cid)
    },
```

console output is:
[0-0] capabilities cid : 0-1
[0-1] capabilities cid: 0-1

In console thread id is correct but cid is same. 
due to this issue script try to create 2 sessions on same devices and only one session successfully created and  second session is failed.

I am trying  to set udid at runtime in order  to run the tests in parallel. 

### What is your expected behavior?

console output should be as below and should not override the "0-0" cid so 2 sessions should be created on different devices.
[0-0] capabilities cid : 0-0
[0-1] capabilities cid: 0-1

### How to reproduce the bug.

 create appium-service project and use capabilities as below
 {
  "platformName": "android",
  "appium:udid": "[assigning in hook onWorkerStart]",
  "appium:app": "Some-App.app.zip",
  "appium:automationName": "uiAutomator2",
}

should have 2 feature files and try to run with maxInstance value 2
try to add udid capabilities in workerStarted hook. and get that in beforeSessionStart hook.

### Relevant log output

```typescript
[0-0] capabilities cid : 0-1
[0-1] capabilities cid: 0-1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
You have access to the worker id via [`WDIO_WORKER_ID`](https://webdriver.io/docs/api/environment#wdio_worker_id). 
Join our  [Discord](https://discord.webdriver.io) server for these kind of questions. This is not necessary a WebdriverIO related issue.
