### ISSUE TITLE
Support for basic mouse/touch operations inside Canvas object

### ISSUE THREAD

**Issue by hanthomas** [webdriverio/webdriverio#1086]
The API works great for mouse interaction between elements.  But there's no way to perform granular mouse operations within an element, such as a canvas..  The existing buttonDown and buttonUp doesn't have the ability to pass x,y coordinates relative to the element, and dragAndDrop only works as mechanism for moving one DOM element into another.  The solution might be something as simple as extending the functionality of buttonDown and buttonUp so that it accepts relative x,y coordinates, and for dragAndDrop to do something similar within the same element.  Touch actions are more flexible, but the problem is that they use only absolute screen coordinates.  It would be nice if we could specify x,y coordinates relative to the element.

**Comment by christian-bromann** [comment]
I know this took quite some time but we just released a new command ([touchAction](http://webdriver.io/api/mobile/touchAction.html)) that runs arbitrary (multi)touch gestures on canvas .. e.g.

![malen](https://cloud.githubusercontent.com/assets/731337/19971268/d4d2ff22-a1de-11e6-94fd-90e04c500b20.gif)

**Comment by hanthomas** [comment]
Thanks!
