### ISSUE TITLE
[🐛 Bug]: <title>devtoolsOptions does not work as expected

### ISSUE THREAD

**Issue by mighty98** [webdriverio/webdriverio#10866]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
        browserName: 'chrome',
        acceptInsecureCerts: true,
        'wdio:devtoolsOptions': {
          ignoreDefaultArgs: true,
          defaultViewport: null,
        },
        'goog:chromeOptions': {
          args: ['--disable-gpu', '--disable-prompt-on-repos', '--start-maximized'],
          prefs: {
            directory_upgrade: true,
            prompt_for_download: false,
          },
        },
      }
```

### What happened?

As per the capabilities defined above for launching chrome via devtools it should not set default view port  and should start browser maximized but it still set the window size

devtools: Launch Google Chrome (undefined) with flags: --window-position=0,0 --window-size=1200,900 --disable-gpu --disable-prompt-on-repos --start-maximized --ignore-certificate-errors

### What is your expected behavior?

Window size parameters should not have set

### How to reproduce the bug.

Launch chrome using devtools protocol with below setting
```typescript
await remote({
      automationProtocol: 'devtools',
      capabilities: {
        browserName: 'chrome',
        acceptInsecureCerts: true,
        'wdio:devtoolsOptions': {
          ignoreDefaultArgs: true,
          defaultViewport: null,
        },
        'goog:chromeOptions': {
          args: ['--disable-gpu', '--disable-prompt-on-repos', '--start-maximized'],
          prefs: {
            directory_upgrade: true,
            prompt_for_download: false,
          },
        },
      },
    })```

### Relevant log output

```typescript
2023-08-07T10:25:06.613Z INFO webdriverio: Starting session using Chrome DevTools as automation protocol and Puppeteer as driver
2023-08-07T10:25:06.621Z INFO devtools:puppeteer: Initiate new session using the DevTools protocol
2023-08-07T10:25:06.630Z INFO devtools: Launch Google Chrome (undefined) with flags: --window-position=0,0 --window-size=1200,900 --disable-gpu --disable-prompt-on-repos --start-maximized --ignore-certificate-errors
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by mighty98** [comment]
![image](https://github.com/webdriverio/webdriverio/assets/32213921/54ad5ac8-05cd-45a1-8af8-a97ff2cecf01)
@christian-bromann Not sure if i should be tagging you. (sorry)
If im not wrong, the window size seems to be mandatory and we cannot ignore this somehow. 
With this in place, how can we start chrome with --start-maximized and defaultViewport: null ?

**Comment by christian-bromann** [comment]
Thanks for reporting!



We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by mighty98** [comment]
Ok.. I'll give a try.. Will update

**Comment by mighty98** [comment]
@christian-bromann I have raised PR https://github.com/webdriverio/webdriverio/pull/10883 for this

**Comment by christian-bromann** [comment]
Awesome, let's continue the convo there.
