### ISSUE TITLE
waitForVisible not returning false when element is not within viewport

### ISSUE THREAD

**Issue by chewy2** [webdriverio/webdriverio#1087]
Hi, the documentation located at http://webdriver.io/api/utility/waitForVisible.html states when I use waitForVisible command it will count something not within the viewport as not visible yet when I run the following command it always returns true. 

`browser.waitForVisible('[gherkin-qa="feedbackCards"] .slds-card:nth-child(1)').then(console.log)
{ state: 'pending' }`

`true`

When I run the command isVisibleWIthinViewPort it will correctly return false

`browser.isVisibleWithinViewport('[gherkin-qa="feedbackCards"] .slds-card:nth-child(1)').then(console.log)`

`false`

Here are the respective selenium logs

waitForVisible:

10:01:48.516 INFO - Executing: [find elements: By.cssSelector: [gherkin-qa="feedbackCards"] .slds-card:nth-child(1)])
10:01:48.532 INFO - Done: [find elements: By.cssSelector: [gherkin-qa="feedbackCards"] .slds-card:nth-child(1)]
10:01:48.535 INFO - Executing: [is displayed: 3 [[ChromeDriver: chrome on MAC (58952fa283e23aa2a56c954950de9a9d)] -> css selector: [gherkin-qa="feedbackCards"] .slds-card:nth-child(1)]])
10:01:48.548 INFO - Done: [is displayed: 3 [[ChromeDriver: chrome on MAC (58952fa283e23aa2a56c954950de9a9d)] -> css selector: [gherkin-qa="feedbackCards"] .slds-card:nth-child(1)]]

isVisibleWithinViewport:

10:06:25.829 INFO - Executing: [execute script: return !!document.evaluate;, []])
10:06:25.838 INFO - Done: [execute script: return !!document.evaluate;, []]
10:06:25.842 INFO - Executing: [execute script: return (function (fn, sArr, args) {  var cb = arguments[arguments.length - 1],  i = 0, sArgs = [],  use, value, xp, cs, tn,  res, j, arg;   if (typeof document.querySelectorAll === 'undefined') {  document.querySelectorAll = function(selector) {  var doc = document,  head = doc.documentElement.firstChild,  styleTag = doc.createElement('STYLE');  head.appendChild(styleTag);  doc.__qsaels = [];   styleTag.styleSheet.cssText = selector + '{x:expression(document.__qsaels.push(this))}';  window.scrollBy(0, 0);   return doc.__qsaels;  };  }   while ((use = sArr[i++]) && (value = sArr[i++])) {  arg = [];  xp = cs = tn = null;  switch (use) {  case 'partial link text':  xp = '//a[contains(text(),"' + value + '")]';  break;  case 'link text':  xp = '//a[text()="' + value + '"]';  break;  case 'xpath':  xp = value;  break;  case 'id':  cs = '#' + value;  break;  case 'name':  cs = '[name="' + value + '"]';  break;  case 'tag name':  tn = value;  break;  case 'css selector':  cs = value;  break;  default: throw new Error('Could not evaluate selector: Invalid strategy ' + use);  }   if (xp) {  res = document.evaluate(xp, document, null, 0, null);   value = res.iterateNext();  while (value) {  arg.push(value);  value = res.iterateNext();  }  } else if (tn || cs) {  res = tn ? document.getElementsByTagName(tn) : document.querySelectorAll(cs);  for(j = 0; j < res.length; ++j) {  arg.push(res[j]);  }  }  sArgs.push(arg);  }   var parameter = args && sArgs.concat(args) || sArgs;  if(parameter.length === 0 || (parameter.length === 1 && parameter[0].length === 0)) {  if(typeof cb === 'function') {  return cb('NoSuchElement') && new Error('NoSuchElement');  }  return new Error('NoSuchElement');  }   parameter.push(arguments[arguments.length - 1]);   return fn.apply(window, parameter);
})(function (elements) {  var db = document.body,  dde = document.documentElement,  result = [];   if(elements.length === 0) {  throw new Error('NoSuchElement');  }   for (var i = 0; i < elements.length; ++i) {  var elem = elements[i],  isWithinViewport = true;   while (elem.parentNode && elem.parentNode.getBoundingClientRect) {   var elemDimension = elem.getBoundingClientRect(),  elemComputedStyle = window.getComputedStyle(elem),  viewportDimension = {  width: dde.clientWidth,  height: dde.clientHeight  };   isWithinViewport = isWithinViewport && (elemComputedStyle.display !== 'none' &&  elemComputedStyle.visibility === 'visible' &&  parseFloat(elemComputedStyle.opacity, 10) > 0 &&  elemDimension.bottom > 0 &&  elemDimension.right > 0 &&  elemDimension.top < viewportDimension.height &&  elemDimension.left < viewportDimension.width);   parentElement = false;   elem = elem.parentNode;   }  result.push(isWithinViewport);  }  return result;
},["css selector","[gherkin-qa=\"feedbackCards\"] .slds-card:nth-child(1)"],[], arguments[arguments.length - 1]);, []])
10:06:25.850 INFO - Done: [execute script: return (function (fn, sArr, args) {  var cb = arguments[arguments.length - 1],  i = 0, sArgs = [],  use, value, xp, cs, tn,  res, j, arg;   if (typeof document.querySelectorAll === 'undefined') {  document.querySelectorAll = function(selector) {  var doc = document,  head = doc.documentElement.firstChild,  styleTag = doc.createElement('STYLE');  head.appendChild(styleTag);  doc.__qsaels = [];   styleTag.styleSheet.cssText = selector + '{x:expression(document.__qsaels.push(this))}';  window.scrollBy(0, 0);   return doc.__qsaels;  };  }   while ((use = sArr[i++]) && (value = sArr[i++])) {  arg = [];  xp = cs = tn = null;  switch (use) {  case 'partial link text':  xp = '//a[contains(text(),"' + value + '")]';  break;  case 'link text':  xp = '//a[text()="' + value + '"]';  break;  case 'xpath':  xp = value;  break;  case 'id':  cs = '#' + value;  break;  case 'name':  cs = '[name="' + value + '"]';  break;  case 'tag name':  tn = value;  break;  case 'css selector':  cs = value;  break;  default: throw new Error('Could not evaluate selector: Invalid strategy ' + use);  }   if (xp) {  res = document.evaluate(xp, document, null, 0, null);   value = res.iterateNext();  while (value) {  arg.push(value);  value = res.iterateNext();  }  } else if (tn || cs) {  res = tn ? document.getElementsByTagName(tn) : document.querySelectorAll(cs);  for(j = 0; j < res.length; ++j) {  arg.push(res[j]);  }  }  sArgs.push(arg);  }   var parameter = args && sArgs.concat(args) || sArgs;  if(parameter.length === 0 || (parameter.length === 1 && parameter[0].length === 0)) {  if(typeof cb === 'function') {  return cb('NoSuchElement') && new Error('NoSuchElement');  }  return new Error('NoSuchElement');  }   parameter.push(arguments[arguments.length - 1]);   return fn.apply(window, parameter);
})(function (elements) {  var db = document.body,  dde = document.documentElement,  result = [];   if(elements.length === 0) {  throw new Error('NoSuchElement');  }   for (var i = 0; i < elements.length; ++i) {  var elem = elements[i],  isWithinViewport = true;   while (elem.parentNode && elem.parentNode.getBoundingClientRect) {   var elemDimension = elem.getBoundingClientRect(),  elemComputedStyle = window.getComputedStyle(elem),  viewportDimension = {  width: dde.clientWidth,  height: dde.clientHeight  };   isWithinViewport = isWithinViewport && (elemComputedStyle.display !== 'none' &&  elemComputedStyle.visibility === 'visible' &&  parseFloat(elemComputedStyle.opacity, 10) > 0 &&  elemDimension.bottom > 0 &&  elemDimension.right > 0 &&  elemDimension.top < viewportDimension.height &&  elemDimension.left < viewportDimension.width);   parentElement = false;   elem = elem.parentNode;   }  result.push(isWithinViewport);  }  return result;
},["css selector","[gherkin-qa=\"feedbackCards\"] .slds-card:nth-child(1)"],[], arguments[arguments.length - 1]);, []]

**Comment by christian-bromann** [comment]
@chewy2 sorry this was our mistake. It was that case some time ago but now waitForVisible just checks if the element is visible according to Selenium `elementIdVisible` command. Thanks for pointing that out.
