### ISSUE TITLE
'.' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by AmitMaini09** [webdriverio/webdriverio#10890]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.11.2

### Node.js Version

20.5.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    browserName: 'chrome',    
    maxInstances: 5,
    'goog:chromeOptions':{  
      'useAutomationExtension' : false, 
     // 'args': ['--start-maximized', "--start-fullscreen", '--ignore-ssl-errors=yes', '--ignore-certificate-errors','user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36'],
         'args': [ '--start-fullscreen', '--ignore-ssl-errors=yes', '--ignore-certificate-errors','user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6 Safari/605.1.15 CVS_Automation'],
    },
```

### What happened?

**When I tried to run code,** 

>scriptName:  ./node_modules/.bin/wdio ./stepPAth/web/cli/googlechromeProd.js

**got this error**
'.' is not recognized as an internal or external command,
operable program or batch file.

  "devDependencies": {
    "@rpii/wdio-html-reporter": "^7.7.1",
    "@wdio/allure-reporter": "^8.11.0",
    "@wdio/appium-service": "^8.11.2",
    "@wdio/cucumber-framework": "^8.11.0",
    "@wdio/devtools-service": "^8.11.2",
    "@wdio/local-runner": "^8.11.2",
    "@wdio/mocha-framework": "^8.11.0",
    "@wdio/selenium-standalone-service": "^8.11.0",
    "@wdio/spec-reporter": "^8.11.2",
    "@wdio/sumologic-reporter": "^8.11.0",
    "chromedriver": "^114.0.2",
    "cross-port-killer": "^1.4.0",
    "geckodriver": "^4.0.4",
    "wdio-chromedriver-service": "^8.1.1",
    "wdio-cucumber-parallel-execution": "^3.6.15",
    "wdio-cucumberjs-json-reporter": "^5.1.5",
    "wdio-ms-teams-service": "^0.1.9"

### What is your expected behavior?

Script must run successfully without any issues 

### How to reproduce the bug.

To reproduce the bug , run npm run scriptName

### Relevant log output

```typescript
> cvs-retail@1.0.0 prod_jenkins_run
> /node_modules/scriptPath/googlechromeProd.js

The system cannot find the path specified.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
As mentioned in the [docs](https://webdriver.io/docs/gettingstarted#run-test) we recommend to kick of the testrunner via:

```sh
npx wdio run ./wdio.conf.js
```

Make sure the file is a WebdriverIO config file. Join our  [Discord](https://discord.webdriver.io) server for these kind of questions. This is not necessary a WebdriverIO related issue.
