### ISSUE TITLE
[💡 Feature]: Getting proper hook details for cucumber hooks

### ISSUE THREAD

**Issue by sriteja777** [webdriverio/webdriverio#10894]
### Is your feature request related to a problem?

Currently in the hooks `beforeHook` and `afterHook`, we don't get much details for cucumber hooks. Specifically

- for `BeforeFeature`: the `test` object is empty.
- for `BeforeScenario`: the `test` object consists of just the hook id.
- for `BeforeStep`: the `test` object consists of step details, nothing about the hook.

But for reporting and debugging purposes, it is good to have some details of the cucumber hook that is running.

### Describe the solution you'd like.

1. We should at least have some basic details of cucumber hooks such as name, type of hook.
2. It would be good, if we can provide some additional hook details such as body and parent.

### Describe alternatives you've considered.

I have checked `onHookStart` event of reporter, but no hook details are related in that too.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sriteja777** [comment]
Have created a PR for [this](https://github.com/webdriverio/webdriverio/pull/10895). @christian-bromann Please have a look at that in your free time

**Comment by christian-bromann** [comment]
Let's continue this conversation in #10895
