### ISSUE TITLE
Fix scroll() with webdrivercss's scrollFn()

### ISSUE THREAD

**Issue by jadamgreen1010** [webdriverio/webdriverio#1089]
I noticed that I couldn't get the webdriver.scroll() command to work in a certain page in chrome. In fact, on the page I was testing, window.scrollTo() didn't work at all.

WebdriverCSS's [method](https://github.com/webdriverio/webdrivercss/blob/master/lib/documentScreenshot.js#L60-L72) for this does work however. Any reason not to use this same method for WebdriverIO? I could submit a PR if you like.

**Comment by christian-bromann** [comment]
@jadamgreen1010 what WebdriverCSS does is a bit hacky and is used because of a different reason. Why do you need scroll anyway?

**Comment by jadamgreen1010** [comment]
I need to bring the element into view in order to avoid the 'element not clickable at (x, y)' error. I already pulled parts of the webdrivercss solution into an overriding custom command which has been working fine.
Do you think the hacky webdrivercss solution would cause problems? I'm just not seeing the reason to avoid pulling that in.

**Comment by christian-bromann** [comment]
> 'element not clickable at (x, y)' error

This error doesn't happen due to the fact the it is not within the viewport but because there is an element on top of it which would get the click event. Are you using some kind of scroll framework?

> Do you think the hacky webdrivercss solution would cause problems?

Yes, this method changes the body margin and would move elements out of the page. This approach is ok in WebdriverCSS because I reset this once I am done taking the screenshot. This is not the case for a usual scroll use case.

**Comment by BlueRaja** [comment]
> This error doesn't happen due to the fact the it is not within the viewport [..]

That's false, the error does occur when the element is not in the viewport.  See https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/2766

**Comment by christian-bromann** [comment]
> That's false, the error does occur when the element is not in the viewport.

Nope, the element doesn't need to be in the viewport to interact with it. In fact the browser driver will scroll to that element if you want to interact with it. That is also what the issue is telling me.

**Comment by jadamgreen1010** [comment]
@christian-bromann I wasn't using any scrolling libs - just a React SPA. I did notice what you said about not needing to scroll to interact was true for some pages but not for all - though I couldn't find the common thread.

It's been too long at this point to provide any more specific useful info so I'm fine with closing this. But, from what I can remember, I couldn't interact with elements off-screen without scrolling to them (got the aforementioned error), but I couldn't consistently scroll to them the normal way in my spa (it just wouldn't scroll). My solution was to override wdio's scroll with wdcss's scroll. Then, when I wanted to interact, I'd scroll to, interact, and reset every time. It made the viewport weird (wrong place sometimes and couldn't scroll the window manually after transforming), but it the screenshot turned out as expected.

It was tedious and far from ideal, but that's what it took. It'd be nice if scrolling functionality was a bit more robust but I know there are lots of limitations.
