### ISSUE TITLE
[💡 Feature]: Allow specs to run multiple times in a group

### ISSUE THREAD

**Issue by ddNils** [webdriverio/webdriverio#10910]
### Is your feature request related to a problem?

I have started to rewrite tests to be more granular. Before this we had spec files with around 1000 rows of code. Now I am trying to split them up, so that parts of the tests can be run in each test (like login for example).
After splitting up a complex spec file, it did not run correctly as I did reuse a spec file inside a group multiple times.

So our specs look something like this:
```json
  specs: [
    [
      './test/specs/initBrowsers.ts',
      './test/specs/loginUserSetGuest.ts',
      './test/specs/loginShared.ts',
      './test/specs/testGuest.ts',
      './test/specs/logout.ts',
      './test/specs/loginUserSetAdmin.ts',
      './test/specs/loginShared.ts',
      './test/specs/testAdmin.ts',
      './test/specs/createEntity.ts',
      './test/specs/checkButtonDeleteIsVisible.ts',
      './test/specs/logout.ts',
      './test/specs/loginUserSetGuest.ts',
      './test/specs/loginShared.ts',
      './test/specs/checkButtonDeleteIsNotVisible.ts',
      './test/utils/logBrowsersOutput.ts'
    ]
  ]
```

Of course we have multiple test-groups and there we are re-using the logins and logouts for example. Now I get frustrated, because the above sample does not work. wdio only runs the first login, the next ones are omitted. How can I make this work?

### Describe the solution you'd like.

I would like wdio to use an indexed array instead of a simple array to hold the spec files, so that the same spec file can be used multiple times in a group.

### Describe alternatives you've considered.

Alternatively it might also be ok, to introduce a special character or similar to avoid the problem, which gets ignored when resolving the file names.

### Additional context

I was also experimenting with suites, but was not able to get them running in the desired way, maybe because we are using an multiremote approach and we need to loose the session in specific cases.
The main issue was, that we needed to save the id of the entity that we created in the test to delete it in a later test and were not able to securely share this id between the specs.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
> Now I get frustrated, because the above sample does not work. wdio only runs the first login, the next ones are omitted. How can I make this work?

Can you explain a bit further? Do you see any errors in the first spec?

Can you also provide a minimal reproducible example please that outlines the problem?

**Comment by ddNils** [comment]
Hi Christian, I just tried to implement a mini example: https://github.com/ddNils/miniTestMulti

Notice, that the [third test group](https://github.com/ddNils/miniTestMulti/blob/main/wdio.conf.ts#L32-L39) will NOT work, as it tries to use the login.ts test twice.

Is this more understandable?

**Comment by christian-bromann** [comment]
Yes, this makes it more clear now.

We greatly appreciate any contributions that help implement this feature request. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this feature being implemented. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by christian-bromann** [comment]
Thank you @tamil777selvan for adding support for this 🎉  closing!
