### ISSUE TITLE
Error: Couldn't Connect to Selenium Server when using an internal Selenium Grid

### ISSUE THREAD

**Issue by fijijavis** [webdriverio/webdriverio#1093]
I am new to WebdriverIO and could use some help.  

I am setup to use WebdriverIO with Mocha, Chai and Chai-as-promised.  I want to run my tests against an internal Selenium Grid.

Attached are the wdio.conf.js and test files I am using.

[Files.zip](https://github.com/webdriverio/webdriverio/files/126864/Files.zip)

When I run wdio from terminal I get the following:

`=======================================================================================
Selenium 2.0 / webdriver protocol bindings implementation with helper commands in nodejs.
For a complete list of commands, visit http://webdriver.io/docs.html.
=======================================================================================

[13:08:51]  COMMAND	POST 	 "/wd/hub/session"
[13:08:51]  DATA		{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"chrome","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.0.3","name":"webdriverio"}}}
[13:08:51]  COMMAND	POST 	 "/wd/hub/session"
[13:08:51]  DATA		{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"chrome","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.0.3","name":"webdriverio"}}}
ERROR: Couldn't connect to selenium server
chrome
    at new RuntimeError (/usr/local/lib/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:115:12)
    at Request._callback (/usr/local/lib/node_modules/webdriverio/build/lib/utils/RequestHandler.js:240:41)
    at self.callback (/usr/local/lib/node_modules/webdriverio/node_modules/request/request.js:373:22)
    at emitOne (events.js:78:13)
    at Request.emit (events.js:170:7)
    at Request.init (/usr/local/lib/node_modules/webdriverio/node_modules/request/request.js:619:17)
    at new Request (/usr/local/lib/node_modules/webdriverio/node_modules/request/request.js:283:8)
    at request (/usr/local/lib/node_modules/webdriverio/node_modules/request/index.js:50:10)
    at /usr/local/lib/node_modules/webdriverio/build/lib/utils/RequestHandler.js:207:42
    at new Promise (/usr/local/lib/node_modules/webdriverio/node_modules/core-js/library/modules/es6.promise.js:197:7)

All documentation seems to point towards running Selenium Server Standalone.  Is selenium Grid supported?  If so, what am I missing?

Any help would be appreciated
Thanks

**Comment by christian-bromann** [comment]
@fijijavis apparently it can not connect to the local grid. Make sure the machine your are running your tests on can reach the server. So you should be able to open `http://10.3.161.234:4444/wd/hub` in your browser.

**Comment by fijijavis** [comment]
I am able to connect to that machine.  I run Selenium WebDriver Java based tests against it quite often.  When I access http://10.3.161.234/wd/hub in my browser I get the following (expected):

{"status":13,"value":{"class":"java.lang.NullPointerException","stackTrace":[{"fileName":"ExternalSessionKey.java","className":"org.openqa.grid.internal.ExternalSessionKey","methodName":"fromWebDriverRequest","lineNumber":77},{"fileName":"WebDriverRequest.java","className":"org.openqa.grid.web.servlet.handler.WebDriverRequest","methodName":"extractSession","lineNumber":62},{"fileName":"RequestHandler.java","className":"org.openqa.grid.web.servlet.handler.RequestHandler","methodName":"getSession","lineNumber":239},{"fileName":"RequestHandler.java","className":"org.openqa.grid.web.servlet.handler.RequestHandler","methodName":"process","lineNumber":120},{"fileName":"DriverServlet.java","className":"org.openqa.grid.web.servlet.DriverServlet","methodName":"process","lineNumber":83},{"fileName":"DriverServlet.java","className":"org.openqa.grid.web.servlet.DriverServlet","methodName":"doGet","lineNumber":61},{"fileName":"HttpServlet.java","className":"javax.servlet.http.HttpServlet","methodName":"service","lineNumber":687},{"fileName":"HttpServlet.java","className":"javax.servlet.http.HttpServlet","methodName":"service","lineNumber":790},{"fileName":"ServletHolder.java","className":"org.seleniumhq.jetty9.servlet.ServletHolder","methodName":"handle","lineNumber":808},{"fileName":"ServletHandler.java","className":"org.seleniumhq.jetty9.servlet.ServletHandler","methodName":"doHandle","lineNumber":587},{"fileName":"SessionHandler.java","className":"org.seleniumhq.jetty9.server.session.SessionHandler","methodName":"doHandle","lineNumber":221},{"fileName":"ContextHandler.java","className":"org.seleniumhq.jetty9.server.handler.ContextHandler","methodName":"doHandle","lineNumber":1127},{"fileName":"ServletHandler.java","className":"org.seleniumhq.jetty9.servlet.ServletHandler","methodName":"doScope","lineNumber":515},{"fileName":"SessionHandler.java","className":"org.seleniumhq.jetty9.server.session.SessionHandler","methodName":"doScope","lineNumber":185},{"fileName":"ContextHandler.java","className":"org.seleniumhq.jetty9.server.handler.ContextHandler","methodName":"doScope","lineNumber":1061},{"fileName":"ScopedHandler.java","className":"org.seleniumhq.jetty9.server.handler.ScopedHandler","methodName":"handle","lineNumber":141},{"fileName":"HandlerWrapper.java","className":"org.seleniumhq.jetty9.server.handler.HandlerWrapper","methodName":"handle","lineNumber":97},{"fileName":"Server.java","className":"org.seleniumhq.jetty9.server.Server","methodName":"handle","lineNumber":499},{"fileName":"HttpChannel.java","className":"org.seleniumhq.jetty9.server.HttpChannel","methodName":"handle","lineNumber":310},{"fileName":"HttpConnection.java","className":"org.seleniumhq.jetty9.server.HttpConnection","methodName":"onFillable","lineNumber":257},{"fileName":"AbstractConnection.java","className":"org.seleniumhq.jetty9.io.AbstractConnection$2","methodName":"run","lineNumber":540},{"fileName":"QueuedThreadPool.java","className":"org.seleniumhq.jetty9.util.thread.QueuedThreadPool","methodName":"runJob","lineNumber":635},{"fileName":"QueuedThreadPool.java","className":"org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3","methodName":"run","lineNumber":555},{"fileName":"Thread.java","className":"java.lang.Thread","methodName":"run","lineNumber":745}]}}

**Comment by fijijavis** [comment]
Just tried running wdio with sudo and that solved the problem.

**Comment by christian-bromann** [comment]
mhm that's weird why does it require that? Apparently you got a session but it seems that the second command failed.

**Comment by fijijavis** [comment]
I'm not sure why I need sudo... Might be some corporate lockdown on my Mac???

**Comment by fijijavis** [comment]
BTW...Thanks for the quick reply.
