### ISSUE TITLE
[🐛 Bug]: reportedEnvironmentVars not working

### ISSUE THREAD

**Issue by jhaltrecht-rev** [webdriverio/webdriverio#10956]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### What happened?

In the code below, I use the reportedEnvironmentVars option: in my wdio.conf.js file.  

`reporters: [
    [
      'allure',
      {
        outputDir: 'allure-results',
        disableWebdriverScreenshotsReporting: false,
        disableWebdriverStepsReporting: true,
        addConsoleOutput: true,
        reportedEnvironmentVars: ['BASE_URL','BUILD','BUILD_VERSION'],
      },
    ],
  ],`

I have tried setting and updating the value of these environment variables, but am only shown an index number followed by the variable name in my report.

![image](https://github.com/webdriverio/webdriverio/assets/97201439/1361f2ba-94fa-438b-9c9b-5a688f64ef7c)

Formerly, I used addEnvironment(name, value), but this is now deprecated. The only documentation I've found is "reportedEnvironmentVars - Set this option to display the environment variables in the report. Note that setting this, does not modify the actual environment variables."

### What is your expected behavior?

I expect to see the same output as addEnvironment, with the name and value shown in my report.

### How to reproduce the bug.

To reproduce the bug, use the reportedEnvironmentVars option, and define the environment variables.

### Relevant log output

```typescript
When logging the environment variables, my console shows the expected value.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@jhaltrecht-rev can you provide a reproducible example to help contributor to easily reproduce this issue. Ideally a liitle Github repository will be sufficient, thanks!

**Comment by jhaltrecht-rev** [comment]
@christian-bromann Thank you for the prompt response. Is there a working example that uses reportedEnvironmentVars?
My understanding is that all cases will be reproducible.

**Comment by christian-bromann** [comment]
> Is there a working example that uses reportedEnvironmentVars?

I don't have an example at hand that uses Allure, there are some boilerplates that do.

cc @epszaw @BorisOsipov

**Comment by BorisOsipov** [comment]
Working as Intended. `reportedEnvironmentVars` is `Record<string, string>` type:
```
            reportedEnvironmentVars: {
                'BASE_URL':'https://github.com/webdriverio/webdriverio/issues/10956',
                'BUILD': '42',
                'BUILD_VERSION': '123'
            }
```

**Comment by jhaltrecht-rev** [comment]
@BorisOsipov thank you for the explanation. Record<string, string> was not listed in the documentation. Seeing this example with an object of keys and values made this clear. My understanding instead was to list an array of environment variables where I would set the value in my code.

If I have any issues, I will provide a reproducible example.

**Comment by christian-bromann** [comment]
@jhaltrecht-rev you are right, the docs are not much clear about that. I pushed a commit to fix this.

**Comment by christian-bromann** [comment]
> but face many restrictions (browser not defined, etc.

You have to be specific here.

**Comment by christian-bromann** [comment]
> 'stack_BUILD': 'process.env.stackBuild',
> 'app_BUILD': 'process.env.appBuild',

It seems in your example you are passing in a string rather than the actual value. It should be:

```js
'stack_BUILD': process.env.stackBuild,
'app_BUILD': process.env.appBuild,
```

**Comment by jhaltrecht-rev** [comment]
@christian-bromann apologies, I forgot to remove the quotes here but I can assure you that I have been testing without the quotes.

My comments from above still apply. Please advise on how to update the values of reportedEnvironmentVars.

**Comment by christian-bromann** [comment]
I can't give any recommendation as I don't know all of your requirements. It seems you are using environment variables which is the way I would recommend applying dynamic values in there. I don't understand why you need to update them during the test, this probably might not be possible whatsoever.

**Comment by jhaltrecht-rev** [comment]
Thank you @christian-bromann . In order to get the value of my environment variables, we need to use WDIO since there are no APIs and this is a web app. If there is a way to run wdio or puppeteer before the reporter gets defined, that would be the solution. I will explore running wdio or puppeteer in a separate file and try to workaround the browser not defined issues. If you have any suggestions, let me know.

**Comment by christian-bromann** [comment]
> we need to use WDIO since there are no APIs and this is a web app

You need to use WebdriverIO to get the build id? You could make a HTTP request and parse the response or run a single WebdriverIO script before.

**Comment by jhaltrecht-rev** [comment]
Yes, we need to run WDIO to pull the version from the about page.

How do we run a wdio script before the wdio.conf.js/configuration file is set? Do you have any documentation on this?

**Comment by christian-bromann** [comment]
> Yes, we need to run WDIO to pull the version from the about page.

Just make a HTTP request to that about page and parse the content. Or as mentioned above run a WebdriverIO Node.js script like shown in here: https://github.com/webdriverio/webdriverio/tree/main/packages/webdriverio#usage

**Comment by jhaltrecht-rev** [comment]
Perfect. This is what I was looking for. I will try both approaches. Thank you for your time and guidance!

**Comment by NIBOSAP** [comment]
@jhaltrecht-rev Since the new version of allure, on our side, we patch directly the allure-results/environment.properties in the afterSession... maybe not the best way...

**Comment by jhaltrecht-rev** [comment]
@NIBOSAP in the past, we used addEnvironment(name, value) within a test, which was ideal. 
This allowed us to pull variables out from my test run and update Allure.

I understand that this is deprecated, and Christian's solution should work for us. I will also explore the afterSession hook to see if we can overwrite the variables when time permits.

**Comment by kanamadiraju** [comment]
@jhaltrecht-rev you have to use something like below, it works
'stack_BUILD': process.env.stackBuild || 'DefaultBuildNumber'
e.g.
'stack_BUILD': process.env.stackBuild || '42'
