### ISSUE TITLE
[💡 Feature]: Restore ability to connect to local selenium server

### ISSUE THREAD

**Issue by gpaciga** [webdriverio/webdriverio#10964]
### Is your feature request related to a problem?

On MacOS systems, we have relied on spinning up a selenium server locally and having WDIO connect to that, because of constraints where we must run the Node process on Intel architecture. This allows us to run Selenium, Chromedriver, and Chrome on arm64 architecture, whereas letting the `selenium-standalone` service spin up selenium or chromedriver automatically from the Node process that runs the tests will result in it running with Intel architecture emulation. This results in a performance runtime difference of 3-4 times.

We used to do this by removing `selenium-standalone` from the list of services when running Mac, and leaving it there when running on other systems.

It appears that with `selenium-standalone` deprecated in WDIO 8.14, there is no way to ask WDIO to connect to an already existing selenium server.

### Describe the solution you'd like.

Restore the ability to tell WDIO somehow to connect to an existing selenium server instead of always managing its own Chrome/chromdriver instances.

Alternatively, if there was a way to force selenium, chromedriver, and chrome to run with arm64 architecture even when started from an Intel-looking terminal (e.g. `process.arch` and `os.arch()` return `x64`), I'd be quite happy with that.

### Describe alternatives you've considered.

I've tried using the hostname, port, path, runner: "remote", settings, none seem to be able to restore the WDIO 7 behaviour.

### Additional context

This is a loss in functionality that blocks us from upgrading to WDIO 8 because of the significant performance degradation it causes.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Thanks for raising this issue.

> there is no way to ask WDIO to connect to an already existing selenium server.

There is, you can set the `hostname` and `port` properties in your `WebdriverIO.Config` and WebdriverIO will connect to that backend. Can you verify?

I think we need to update [`definesRemoteDriver`](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-utils/src/driver/utils.ts#L219-L227) and return true if any value is set.

We greatly appreciate any contributions that help implement this feature request. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this feature being implemented. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by gpaciga** [comment]
Confirmed I am able to connect if I define `port`; the other obvious settings seem to not count if they are set but happen to be equal to the defaults.
