### ISSUE TITLE
[🐛 Bug]: NewSession method creates session in installed desktop Chrome version instead of using browserVersion: 'stable' from capabilities

### ISSUE THREAD

**Issue by HannaTarasevich** [webdriverio/webdriverio#10960]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.15.0

### Node.js Version

18.17.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
        browserName: 'chrome',
        browserVersion: 'stable'
    }
```

### What happened?

My wdio config contains the following capabilities:
{
        browserName: 'chrome',
        browserVersion: 'stable'
    }
It starts execution in Chrome-for-testing browser.

Then my test contains step to create new session with the same capabilities:
    await browser.newSession({
        browserName: 'chrome',
        browserVersion: 'stable'
    })
But it tries creating session in installed Chrome on desktop.

![image](https://github.com/webdriverio/webdriverio/assets/79576380/3ac487bf-12cb-436a-81c7-3255f696b8dc)

And in case of lack of installed Chrome or it is not up-to-date with running chromedriver.exe - newSession method fails.

### What is your expected behavior?

New session method should create session in the same Chrome-for-testing browser (e.g., from cache).

### How to reproduce the bug.

I created a repo with the example. The script is "npm run wdio"
https://github.com/HannaTarasevich/wdio-bug

### Relevant log output

```typescript
-
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Hey @HannaTarasevich thanks for raising the issue.

The `newSession` command sends the capabilities directly to the driver. It is different from the testrunner capabilities as here we evaluate `stable` and download/setup the driver for you. If your local default browser differs from `stable` this error appears. In short: the capabilities you provide to the testrunner will be modified to ensure you get the right ("stable") browser while the `newSession` command doesn't do that. This can result in errors like:

> This version of ChromeDriver only supports Chrome version 116

When you have Chrome 115 locally installed and not updated.

To rerun the same session with the same capabilities, use `await remote({ capabilities: browser.requestedCapabilities })`.

Let me know if you have any further questions.
