### ISSUE TITLE
setValue() fails in Firefox when running parallel tests

### ISSUE THREAD

**Issue by michaelDomingues** [webdriverio/webdriverio#1098]
Hi guys,

I've experienced something awkward within Firefox. 
When I launch a set of test suites in parallel, the test cases which setValue() a specific element fail inconsistently. Either the value is set or the element is not filled.  

```
browser
.setValue('//*[@id="sidebar"]/div/div[1]/div[2]/div[1]/div[1]/input', 11)
.keys('Enter')
.call(done);
```

Individually everything goes well! It seems a click register issue. 
To overcome the problem I added a click() action like this:

``` 
 browser
.click('//*[@id="sidebar"]/div/div[1]/div[2]/div[1]/div[1]')
.setValue('//*[@id="sidebar"]/div/div[1]/div[2]/div[1]/div[1]/input', 11)
.keys('Enter')
.call(done);
```

Any ideas for this behaviour?
Note: Chrome is fine!

**Comment by christian-bromann** [comment]
Sometimes browser driver behave differently. This is not necessary a problem with WebdriverIO. Our goal though is to bring consistency into all commands. I will keep this open in order someone finds a nice solution to overcome this problem.

**Comment by christian-bromann** [comment]
I don't think there is a general way to fix this issue across all drivers.
