### ISSUE TITLE
[🐛 Bug]: Unable to use Spacebar key in WebdriverIO

### ISSUE THREAD

**Issue by ChintanMehta0510** [webdriverio/webdriverio#10996]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.12

### Node.js Version

18.16.19

### Mode

Standalone Mode

### What happened?

I used different ways to use spacebar key but none seem to be working:

browser.keys("\uE00D");
browser.keys("\ue00d");
browser.keys(" ");
browser.keys("Space");
browser.keys(["Space"]);
browser.keys('Space');

My tsconfig.json:

`{ "compileOnSave": false, "compilerOptions": { "baseUrl": "./", "outDir": "./dist/out-tsc", "sourceMap": true, "declaration": false, "downlevelIteration": true, "experimentalDecorators": true, "module": "es2020", "moduleResolution": "node", "importHelpers": true, "target": "ES2022", "typeRoots": [ "node_modules", "node_modules/@types", "node_modules/@wdio", "node_modules/async" ], "lib": [ "es2018", "dom" ], "types": [ "node", "jasmine-framework", "expect-webdriverio", "webdriverio/async", "types" ], "paths": { "links there" ] }, "useDefineForClassFields": false }, "angularCompilerOptions": { "strictTemplates": true } } `

### What is your expected behavior?

The output is expected to use Spacebar and perform an action in my project. Manually it is working, but when automated the spacebar key is not getting executed.

### How to reproduce the bug.

I am using TypeScript for automating the tests.
You can write any file which involves use of browser.keys("\uE00D");

### Relevant log output

```typescript
The output is expected to use Spacebar and perform an action in my project. Manually it is working, but when automated the spacebar key is not getting executed.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Can you try:

```ts
import { Key } from 'webdriverio'

await browser.keys([Key.Space])
```

**Comment by erwinheitzman** [comment]
I can confirm that using the old way of passing keys does not work as expected, using the Key module however does work as expected so I suggest using as it is the recommended way of using keys in v8.

**Comment by ChintanMehta0510** [comment]
@christian-bromann Thank you for answering.

This actually is not working for me. It gives me an error saying: "_Module '"webdriverio"' has no exported member 'Key'.ts(2305)_"
I searched this issue, and I found a page where you have addressed the same issue: https://github.com/webdriverio/webdriverio/issues/7432
But, I already have the same configuration in my ts-config.json. 
"types": ["node", "jasmine-framework", "expect-webdriverio", "webdriverio/async", "types"],

Could you please help me further?

@erwinheitzman  Please Note my webdriver IO version is 7.16.12 as mentioned in the description.

**Comment by ChintanMehta0510** [comment]
@christian-bromann I am awaiting your response.

**Comment by christian-bromann** [comment]
My response only works with v8 and upwards. I recommend upgrading. `browser.keys(["Space"])` should work in v7. You can also try to fiddle with the `performAction` command.

**Comment by erwinheitzman** [comment]
Apologies @ChintanMehta0510 I did not notice your reply earlier, I agree with what Christian said. Also, don't forget you need to focus the input element before typing
