### ISSUE TITLE
[🐛 Bug]: Importing @wdio/reporter module throws ESM error

### ISSUE THREAD

**Issue by joel-klassen-tempo-io** [webdriverio/webdriverio#11001]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.15.6

### Node.js Version

v18.12.1

### Mode

Standalone Mode

### What happened?

There are three things that seem to be going wrong:
- `@wdio/reporter` is missing a `package.json`
- `@wdio/logger` is causing ESM issues
- `supports-color@^9.x` is only ESM and is also causing issues

The first two problems seem to have been fixed with  [this commit](https://github.com/webdriverio/webdriverio/commit/01ebfcb5ff8d30ff84a3a60c64b3de856ab260b4). It looks like the latter issue can only be fixed by downgrading `supports-color` or adding a dynamic import.

### What is your expected behavior?

Calling `require("@wdio/reporter")` does not throw errors.

### How to reproduce the bug.

index.js
```
const reporter = require('@wdio/reporter')
```
package.json
```
{
  "name": "wdio",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "type": "commonjs",
  "dependencies": {
    "@wdio/reporter": "^8.15.6"
  }
}
```

running the script:
```
➜ node index.js
/Users/me/debugging/wdio/index.js:1
const reporter = require('@wdio/reporter')
                 ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/me/debugging/wdio/node_modules/@wdio/reporter/cjs/index.js from /Users/me/debugging/wdio/index.js not supported.
/Users/me/debugging/wdio/node_modules/@wdio/reporter/cjs/index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename /Users/me/debugging/wdio/node_modules/@wdio/reporter/cjs/index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/me/debugging/wdio/node_modules/@wdio/reporter/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at Object.<anonymous> (/Users/me/debugging/wdio/index.js:1:18) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.12.1
```

After applying the changes from  [this commit](https://github.com/webdriverio/webdriverio/commit/01ebfcb5ff8d30ff84a3a60c64b3de856ab260b4), the error is then:
```
➜ node index.js
/Users/me/debugging/wdio/node_modules/@wdio/reporter/cjs/utils.js:7
const supports_color_1 = __importDefault(require("supports-color"));
                                         ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/me/debugging/wdio/node_modules/supports-color/index.js from /Users/me/debugging/wdio/node_modules/@wdio/reporter/cjs/utils.js not supported.
Instead change the require of index.js in /Users/me/debugging/wdio/node_modules/@wdio/reporter/cjs/utils.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/me/debugging/wdio/node_modules/@wdio/reporter/cjs/utils.js:7:42)
    at Object.<anonymous> (/Users/me/debugging/wdio/node_modules/@wdio/reporter/cjs/index.js:9:20)
    at Object.<anonymous> (/Users/me/debugging/wdio/index.js:1:18) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.12.1
```

Updating the `package.json` to be:
```
➜  cat package.json
{
  "name": "wdio",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "type": "commonjs",
  "dependencies": {
    "@wdio/reporter": "^8.15.6"
  },
  "resolutions": {
	  "@wdio/reporter/**/supports-color": "8"
  }
}
```

fixes all the errors.

### Relevant log output

```typescript
Attached in the reproduction steps to be easier to read.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@joel-klassen-tempo-io thanks for reporting, we have identified the problem an try to push a fix soon.
