### ISSUE TITLE
[🐛 Bug]: Duplicate execution of spec due to lowercase drive letter in specs path (Windows)

### ISSUE THREAD

**Issue by hbc007** [webdriverio/webdriverio#11009]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.15.6

### Node.js Version

18.15.0

### Mode

WDIO Testrunner

### What happened?

On the Windows platform, specifying a lowercase drive letter in the specs path within the configuration file results in this spec being executed twice.

#### Config File
```
export const config: WebdriverIO.Config = {
  runner: 'local',
  specs: [ 'D:\\data\\case-repos\\Project\\case1.spec.ts' ],
  capabilities: [
      {
        platformName: 'Android',
        maxInstances: 1,
        ...
      }
  ],
  ...
}
```
#### `wdio run` and start debugging
The `globResult` variable within `FileSystemPathService.glob` yields the following result: 
```
['D:\\data\\case-repos\\Project\\case1.spec.ts', 'd:\\data\\case-repos\\Project\\case1.spec.ts']
```
This results in `ConfigParser.getSpecs` returning two test case paths that point to the same file, ultimately leading to the execution of that test case twice.

### Relevant log output

```typescript
Execution of 2 workers started at 2023-08-25T02:09:00.936Z

2023-08-25T02:09:00.956Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-08-25T02:09:00.959Z INFO @wdio/cli:launcher: Run onWorkerStart hook
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!



We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!
