### ISSUE TITLE
Changelog / upgrade guide for 4.0?

### ISSUE THREAD

**Issue by jordansexton** [webdriverio/webdriverio#1100]
The npm version has been updated and 4.0 presumably includes breaking changes. I see there has been a ton of project activity lately, so I'm not sure how much of an undertaking this is, but it would help to know what has changed at a high level when considering upgrading.

**Comment by vvo** [comment]
Looking forward to it too :)

**Comment by oliviertassinari** [comment]
That would be awesome. I have no quick way to know how to upgrade to v4.

**Comment by jhnns** [comment]
:+1:

**Comment by Harsha509** [comment]
+1

**Comment by xbill82** [comment]
+1

**Comment by mroien** [comment]
Yeah I think v4 is a huge change and we'll need docs and examples of how to run news tests on v4

**Comment by daemon1981** [comment]
:+1:

**Comment by christian-bromann** [comment]
I put together a rough changelog and will add more documentation around some specific parts of it.
