### ISSUE TITLE
update isVisible documentation on array return value

### ISSUE THREAD

**Issue by bevanhunt** [webdriverio/webdriverio#1101]
https://github.com/webdriverio/webdriverio/blob/3d7201416c97850c24d5ea12fea26284fe7c4960/test/spec/isVisible.js

http://webdriver.io/api/state/isVisible.html

IsVisible if it matches multiple elements will return an array. This is missing from the docs. Please add. Cheers.

**Comment by christian-bromann** [comment]
Got added. This applies to all commands btw.
