### ISSUE TITLE
Allure report treats passed Mocha beforeAll and afterAll hooks as passed tests

### ISSUE THREAD

**Issue by ramsesh18** [webdriverio/webdriverio#11021]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.15.5

### Node.js Version

19.0.0

### Mode

WDIO Testrunner

### What happened?

I recently upgraded to WebdriverIo v8 and I noticed that all the mocha hooks are displayed in the allure report. 
![image](https://github.com/webdriverio/webdriverio/assets/44935938/c8debd5f-5d56-4585-ac56-cd45bea42417)

If I set "disableMochaHooks: true", then for the failed tests, there is no screenshot generated as it ignores all the hooks in wdio.conf.ts. 

![image](https://github.com/webdriverio/webdriverio/assets/44935938/6ceda686-fdec-42cc-a879-3bc347aa729a)

### What is your expected behavior?

before, after, aftereach, beforeeach hooks shouldn't be displayed on the report

### How to reproduce the bug.

My package.json

"devDependencies": {
    "@types/crypto-js": "^4.1.1",
    "@types/jest": "^29.5.3",
    "@types/supertest": "^2.0.12",
    "@wdio/allure-reporter": "^8.15.7",
    "@wdio/cli": "8.15.5",
    "@wdio/junit-reporter": "8.15.0",
    "@wdio/local-runner": "8.15.4",
    "@wdio/mocha-framework": "^8.15.4",
    "@wdio/spec-reporter": "8.15.0",
    "@wdio/types": "^8.15.0",
    "allure-commandline": "^2.23.1",
    "jest": "^29.6.2",
    "prettier": "^3.0.2",
    "rimraf": "^5.0.1",
    "ts-jest": "^29.1.1",
    "ts-node": "^10.9.1",
    "tslint": "^6.1.3",
    "tslint-config-prettier": "^1.18.0",
    "typescript": "^5.1.6"
  },
  "dependencies": {
    "@rpii/wdio-commands": "^8.0.2",
    "@rpii/wdio-report-events": "^8.0.2",
    "@types/dateformat": "^3.0.1",
    "@types/faker": "^5.5.8",
    "@wdio/logger": "^7.19.0",
    "@wdio/selenium-standalone-service": "^8.14.0",
    "@wdio/utils": "^8.15.4"
    "npm-check-updates": "^16.12.2",
    "wdio-html-nice-reporter": "^8.1.0",
    "xml2js": "^0.6.2"
  }

Use WebdriverIo v8, with these packages and the spec file  should be in the below format along with hooks in wdio.conf.ts

describe("Name", async function () {

before()

beforeEach()

it()

AfterEach()
});

### Relevant log output

```typescript
Already attached in the what happened section
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Please see the `disableMochaHooks` option of the [Allure reporter](https://webdriver.io/docs/allure-reporter#configuration).

Looking for quick answers and valuable insights while using WebdriverIO? Join us on the official Discord server at https://discord.webdriver.io/ – your go-to hub for all your usage questions and developer discussions!
