### ISSUE TITLE
[🐛 Bug]: Auto-Completion and Type Prediction Issue for Global Values (e.g., browser, $, expect) in TypeScript on v8 with intelij

### ISSUE THREAD

**Issue by shlomo100** [webdriverio/webdriverio#11020]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

v16.13.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
from auto-generated example
TypeScript version: (e.g., 4.9.5)
```

### What happened?

I am encountering an issue related to auto-completion and type prediction for global values such as browser, $, and expect in TypeScript while using WebdriverIO.

Problem:

When typing global values such as browser, $, and expect in my TypeScript files, the auto-completion suggestions do not appear immediately, even though the correct types are recognized. After typing the value and letting it stand, the TypeScript compiler infers the types correctly, but auto-completion does not show the suggestions in real-time.

### What is your expected behavior?

I expect that when typing global values like browser, $, and expect, the TypeScript editor should provide immediate auto-completion suggestions based on the recognized types. This behavior is crucial for improving coding efficiency and reducing potential errors.

### How to reproduce the bug.

I initiated a new WebdriverIO project using the command npm init wdio . to create a fresh project.

I added the following types setting to my tsconfig.json:

```
"types": [
  "@wdio/globals/types",
  "node",
  "expect-webdriverio",
  "@wdio/mocha-framework"
]
```

Upon writing TypeScript code and using global values like browser, $, and expect, I noticed that auto-completion suggestions were not immediately displayed.

However, TypeScript does recognize the correct types for these global values and provides accurate type checking.

### Relevant log output

```typescript
I confirmed that this issue is not specific to my project by creating a fresh WebdriverIO project using "npm init wdio .", 
and the auto-completion issue was still present.
I have tried different approaches, including adjusting tsconfig.json, triple-slash directives, and TypeScript versions, but the auto-completion issue persists.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by shlomo100** [comment]
I discovered a workaround: I navigated to the index.d.ts file in the wdio/globals directory under the node_modules folder, specifically in the build subfolder. I modified the line `/// <reference types="types" /> ` to` // <reference types="../types" />`.
And I changed the value in tsconfig to "@wdio/globals", and auto-completion for global values like browser, $, and expect started working as expected in my TypeScript files.

**Comment by christian-bromann** [comment]
Thanks for reporting!

It seems like the global package doesn't propagate the types correctly.

We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by christian-bromann** [comment]
@shlomo100 actually the reason for this issue is the `includes` property didn't include the test directory. I fixed that and it will release the next version now. Thanks for reporting.
