### ISSUE TITLE
Logger does not sanitize app path

### ISSUE THREAD

**Issue by agauthiez** [webdriverio/webdriverio#1104]
When providing the [`app` desired capability](https://wiki.saucelabs.com/display/DOCS/Test+Configuration+Options#TestConfigurationOptions-ApplicationPath), the logger fails because it tries to open a log file containing the app path:
```
Error: ENOENT: no such file or directory, open '/.../log/google.android./my/super/long/path/to/app.apk.2016-02-15T10:30:06.742.log'
```
I think we have to options here: do not include the app name in file name or escape the path properly.

**Comment by christian-bromann** [comment]
Let's close this and continue discussion in #1108
