### ISSUE TITLE
[📖 Docs]: Add docs on setting permission how to copy paste

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#11052]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Missing documentation

### Description of the improvement / report

In order to have copy text work the following needs to be set:

```ts
await browser.setPermissions({ name: 'clipboard-read' }, 'granted')
await browser.setPermissions({ name: 'clipboard-write' }, 'granted')

it('should allow to copy some text', async () => {
    const { container } = render(<CopyButton textToCopy="foobar" />)
    const btn = await $(container).$('button')
    await expect(btn).toHaveText('Copy')
    await btn.click()
    await expect(btn).toHaveText('Copied!')
    expect(await browser.execute(() => navigator.clipboard.readText())).toBe('foobar')
})
```

This should be better documented.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harsha509** [comment]
Hi @christian-bromann ,

So this should go into browser protocol docs, right?

**Comment by christian-bromann** [comment]
@harsha509 yes, similar how we did it [here](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-protocols/src/protocols/saucelabs.ts#L8-L45)
