### ISSUE TITLE
v4 opens a blank page when multiple tests files

### ISSUE THREAD

**Issue by michaelDomingues** [webdriverio/webdriverio#1106]
Installed v4 today and I'm getting a blank page (pointing to `data:,`) session every time I run more than one test.

Dependencies:

```
    "selenium-standalone": "^4.9.0",
    "webdriverio": "^4.0.3"
```

I turned on `singleton` config in wdio to keep the session between tests. When one test ends the other uses the same session. In v3 that was working just fine.

Saw some issues in the Internet saying that's due an old version of drivers and Selenium but this can't be it right now. It's the latest version for each one.

Other question, is there any changes in the way tests are run ? It seems that tests A and B and C (e.g) are being run in parallel.  A should execute before B and then C and I get the opposite or a simultaneous run, don't know for sure.

![screen shot 2016-02-16 at 01 25 25](https://cloud.githubusercontent.com/assets/5079803/13064593/3b5efc02-d44c-11e5-9cf6-de5d53f3846c.png)
![screen shot 2016-02-16 at 01 25 45](https://cloud.githubusercontent.com/assets/5079803/13064594/3b8ca972-d44c-11e5-9410-cdfc8dc7c18a.png)

**Comment by duarte-pina** [comment]
I'm facing the same issue of having the blank page in my project. What has changed on v4?

**Comment by christian-bromann** [comment]
Please use v3.4.x since v4 is still in beta

**Comment by christian-bromann** [comment]
@michaelDomingues could you post your test specs?

**Comment by michaelDomingues** [comment]
I need these new features, that's way I keep on testing v4.

Here it goes:

```
specs = [
    'spec/testA.js',
     'spec/testB.js',
      'spec/testC.js'
];

**Comment by Blackbaud-BobbyEarl** [comment]
Seeing same behavior, but in our case we're specifying with a glob pattern.

```
specs = [
  'specs/**/*.js'
];
```

**Comment by christian-bromann** [comment]
how does `spec/testA.js` look like?

**Comment by michaelDomingues** [comment]
```
'use strict'

describe('TestA', function() {
    it('should do it', function(done) {
        console.log("A");
        browser.call(done);
    });
});
```

Difference between A, B and C tests it's just the `console.log()`

**Comment by christian-bromann** [comment]
So in v4 each test spec gets executed in a single child process meaning that it generates a new session for each spec. That's why the order was different. Also I am not sure if done is defined here since all commands are running synchronously and there is no need to provide an callback method. It seems that this is not a bug in WebdriverIO

**Comment by timbru31** [comment]
@christian-bromann can the process spawning be configured? Our project has currently >90 .feature files (cucumber/gherkin) and if each one would spawn an own process - well that freezes the whole system.
