### ISSUE TITLE
[🐛 Bug]: Missed custom step status

### ISSUE THREAD

**Issue by JorgeCarrio** [webdriverio/webdriverio#11062]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.15.10

### Node.js Version

v16.16.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{    
        outputDir: 'logs',
        maxInstances: 1,
        browserName: 'chrome',
        'goog:chromeOptions': {
          extensions: [encodeBase64(chromeModheader.getExtension())],
          args: [
            '--window-size=1920,1080',
            '--no-sandbox',
            '--disable-gpu',
            '--disable-software-rasterizer'
          ],
        },
```

### What happened?

With the version 8.11 I was able to set my own steps at allure report using:
`startStep('Title')
--code
endStep('failed/passed')`
This allows me to control the result of my custom steps.

In the new version where startStep() is deprecated I should be use step(name, body) instead startStep() but I am not able to find the way to set the status step.

### What is your expected behavior?

Able to set status at custom steps

### How to reproduce the bug.

Add a step with custom status

### Relevant log output

```typescript
no relevant found, only not able to write custom steps with status
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by BorisOsipov** [comment]
>I am not able to find the way to set the status step.

Yu don't need it. Step status are automatically calculated by the result of the body function. If function throws exception\reject promise - step will be failed\broken(It depends whether it is an assertion error or not) and passed otherwise.

In general we don't plan allow user to set custom status to step via `step(name, body)` api.

**Comment by weronikazoltaniecka** [comment]
Hi @BorisOsipov are you sure that "step status is automatically calculated by the result of the body function"?
I'm fighting with an issue using wdio allure-reporter and jasmine. The result of a test shows status: failed but all custom steps have status: passed.
`{
"uuid":"14caf37f-03d8-4b18-ba1e-8c6ea1a8faab",
"historyId":"88486f210370709e4196d5172d35d1ac",
"status":"failed",
"statusDetails":{
"message":"Modal is still displayed\nExpect $(`[data-at-xyz]`) not to be displayed\n\nExpected [not]: \"not displayed\"\nReceived : \"displayed\" \n actual expected\n \n Element { sessionIdwait: '3b47b96dd59ceaca8f41bdc6062ddf51'2000, elementIdmessage: 'DB5B56D317392D51578F1DAD54D129E3_element_114',Connection 'element-6066-11e4-a52e-4f735466cecf':to 'DB5B56D317392D51578F1DAD54D129E3_element_114',the selector:device '[data-at-xyz]', parent:is Browserstill { sessionId: displayed'3b47b96dd59ceaca8f41bdc6062ddf51', capabilities: { acceptInsecureCerts: false, browserName: 'chrome', browserVersion: '117.0.5938.132', chrome: { chromedriverVersion: '116.0.5845.96 (1a391816688002153ef791ffe60d9e899a71a037-refs/branch-heads/5845@{#1382})', userDataDir: '/var/folders/p3/nr0gy2tx6ms3srpp2hrv70kc0000gp/T/.org.chromium.Chromium.uokB1e' }, 'fedcm:accounts': true, 'goog:chromeOptions': { debuggerAddress: 'localhost:63740' }, networkConnectionEnabled: false, pageLoadStrategy: 'normal', platformName: 'mac os x', proxy: {}, setWindowRect: true, strictFileInteractability: false, timeouts: { implicit: 0, pageLoad: 300000, script: 30000 }, unhandledPromptBehavior: 'dismiss and notify', 'webauthn:extension:credBlob': true, 'webauthn:extension:largeBlob': true, 'webauthn:extension:minPinLength': true, 'webauthn:extension:prf': true, 'webauthn:virtualAuthenticators': true }, addCommand: [Function (anonymous)], overwriteCommand: [Function (anonymous)], addLocatorStrategy: [Function (anonymous)] }, emit: [Function: bound ], isReactElement: false, isShadowElement: false, addCommand: [Function (anonymous)], overwriteCommand: [Function (anonymous)] }\n ",
"trace":" at <Jasmine>\n at /Users/x/y/z/a/specs/my-test/4114/4114-1.spec.ts:70:79\n at processTicksAndRejections (node:internal/process/task_queues:96:5)"
},
"stage":"finished",
"steps":[
{
"name":"Login to xyz\"",
"start":1696422098391,
"stop":1696422100516,
"stage":"finished",
"status":"passed",
"statusDetails":{
},
"attachments":[
],
"parameters":[
],
"steps":[
],
"description":""
},
{
"name":"Navigate to xyz",
"start":1696422101511,
"stop":1696422107178,
"stage":"finished",
"status":"passed",
"statusDetails":{
},
"attachments":[
],
"parameters":[
],
"steps":[
],
"description":""
},
{
"name":"Open xyz",
"start":1696422107178,
"stop":1696422112838,
"stage":"finished",
"status":"passed",
"statusDetails":{
},
"attachments":[
],
"parameters":[
],
"steps":[
],
"description":""
},
{
"name":"Click on xyz",
"start":1696422112838,
"stop":1696422113061,
"stage":"finished",
"status":"passed",
"statusDetails":{
},
"attachments":[
],
"parameters":[
],
"steps":[
],
"description":""
},
{
"name":"Click on abc",
"start":1696422113061,
"stop":1696422115289,
"stage":"finished",
"status":"passed",
"statusDetails":{
},
"attachments":[
],
"parameters":[
],
"steps":[
],
"description":""
}
],
"attachments":[
{
"name":"screenshot_2023-10-04T12_21_55_876Z",
"type":"image/png",
"source":"2982dfb2-1b48-4295-a918-645a0073e24d-attachment.png"
},
{
"name":"Console Logs",
"type":"text/plain",
"source":"772dd399-c428-4a43-890f-c6512c532401-attachment.txt"
}
],
"parameters":[
{
"name":"browser",
"value":"chrome-117.0.5938.132"
}
],
"labels":[
{
"name":"language",
"value":"javascript"
},
{
"name":"framework",
"value":"wdio"
},
{
"name":"package",
"value":"4114.4114-1.spec.ts"
},
{
"name":"thread",
"value":"0-0"
},
{
"name":"suite",
"value":"some test"
},
{
"name":"feature",
"value":"some test"
}
],
"links":[
{
"url":"abc",
"type":"tms"
}
],
"start":1696422089025,
"name":"xyz",
"stop":1696422116493
}`

**Comment by BorisOsipov** [comment]
@weronikazoltaniecka Does it reproduce in the latest reporter version? We fixed fixed simular issue in [8.16.21](https://github.com/webdriverio/webdriverio/releases/tag/v8.16.21)

**Comment by weronikazoltaniecka** [comment]
@BorisOsipov thanks for a quick response. Waiting for this version to be available in npm and I will give an update (for now v8.16.20 is available)

**Comment by BorisOsipov** [comment]
@christian-bromann The latest release was published to [github releases](https://github.com/webdriverio/webdriverio/releases/tag/v8.16.21), but not to npm due to the[ npm service outage](https://github.com/webdriverio/webdriverio/actions/runs/6411434827/job/17406884828#step:7:326). Could we somehow re-release these packages?

**Comment by christian-bromann** [comment]
Sure, I am running a new release now.

**Comment by weronikazoltaniecka** [comment]
> Sure, I am running a new release now.

Hi, could you please re-run it again? It seems that there was the same error on re-runing yesterday.

**Comment by christian-bromann** [comment]
Just triggered a release.
