### ISSUE TITLE
[🐛 Bug]: Attempt to execute touchAction('tap'), returns an error "no such element".

### ISSUE THREAD

**Issue by Mike-Ro** [webdriverio/webdriverio#11072]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.10.5

### Node.js Version

18.16.0

### Mode

Standalone Mode

### What happened?

Why can't I make a touch click (tap) on the button, although the usual click() works?

element.touchAction('tap') not working message:
```
{error: "no such element", message: "The element identified by 'dcf38789-49c7-4699-a9dd…in the cache or has expired. Try to find it again", stacktrace: "io.appium.uiautomator2.common.exceptions.ElementNo…a:144)\n\tat java.lang.Thread.run(Thread.java:920)\n"}
```

element.click() clicks on the element without any problems, and element.touchAction('tap') says that the element was not found.
Help!

### How to reproduce the bug.

My code:
```js
import {remote} from 'webdriverio';

const options = {
  host: process.env.APPIUM_HOST || 'localhost',
  port: parseInt(process.env.APPIUM_PORT, 10) || 4723,
  logLevel: 'info',

  capabilities: {
    platformName: 'Android',
    'appium:automationName': 'UiAutomator2',
    'appium:deviceName': 'test-device',
    browserName: 'Chrome',
    'appium:chromedriverExecutableDir': 'D:\\android\\chromedriver',
  }
}

async function main() {
  const browser = await remote(options);
  await browser.url('example.com');

  const button = await browser.$('.techdomain-controls > button');

  // test (see down)

  await browser.deleteSession();
}

main().catch(console.error);
```
test:
```js
  // true
  await button.isDisplayed();

  // work
  await button.click();

  // not work
  await button.touchAction('tap');

  // not work
  await button.touchAction({
    action: 'tap', x: 1, y:1
  });
```

### Relevant log output

```typescript
{error: "no such element", message: "The element identified by 'dcf38789-49c7-4699-a9dd…in the cache or has expired. Try to find it again", stacktrace: "io.appium.uiautomator2.common.exceptions.ElementNo…a:144)\n\tat java.lang.Thread.run(Thread.java:920)\n"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

I am not sure if `touchAction` is still a command the Appium team recommends to use. I reached out in their Slack channel. A simple click should do the same thing.

We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by christian-bromann** [comment]
Ok the Appium team said that `touchActions` are deprecated and should not be used anymore. We recommend use the action API. See a blog post here: https://appiumpro.com/editions/29-automating-complex-gestures-with-the-w3c-actions-api and how to use it with WebdriverIO: https://webdriver.io/docs/api/browser/action

**Comment by christian-bromann** [comment]
I will go ahead and deprecate these commands and remove them in `v9`.

**Comment by Mike-Ro** [comment]
@christian-bromann 
Example from https://webdriver.io/docs/api/element/touchAction/#example works for touch click (tap), thank you!

**Comment by christian-bromann** [comment]
Great, closing this issue then.
