### ISSUE TITLE
.log() returns a raw JsonWireProtocol response

### ISSUE THREAD

**Issue by electricmonk** [webdriverio/webdriverio#1109]
When calling `.log()`, the returned object is a raw `JsonWireProtocol` response that looks something like this:
```
{ state: 'success', sessionId: '89d58cce-c744-4e0b-9ec2-3362daeb3166', hCode: 2115739528, value: [ [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object] ], class: 'org.openqa.selenium.remote.Response', status: 0 }
```

Each of the objects in the array has the following schema:
{
   timestamp: unix-time-stamp,
   level: LOG_LEVEL,
   message: string
}

I suggest that, at the very least, the call to .log() will return this array instead of the raw response.

**Comment by electricmonk** [comment]
My current implementation is this:
```js
    logs.value.forEach(entry => console.log(`${new Date(entry.timestamp).toISOString()} ${name} ${entry.level}: ${entry.message}`));
```

I'm not completely sure what would be a reasonable generic version, but maybe accept an entry formatting function `(entry) => string` could be a good idea. Still have to think about it.

**Comment by christian-bromann** [comment]
@electricmonk `log` is a protocol command and will always return the raw response. Feel free to create a PR and add a command like `getBrowserLogs` that sanitize the response.
