### ISSUE TITLE
[📖 Docs]: Broken link on the #outputdir page

### ISSUE THREAD

**Issue by NutriMarc** [webdriverio/webdriverio#11104]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Missing documentation

### Description of the improvement / report

I will modify the docs but am unsure if this is something that needs to be updated or simply removed. Chat with me about it for a moment, and I will make a PR to fix it!

The page @ https://webdriver.io/docs/configuration/#outputdir has a link to "setup types"([setup type](https://webdriver.io/docs/configuration/setuptypes)) 

When clicked the page is not found. Update or remove?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Hey @NutriMarc , thanks for raising the issue.

Yes this should be fixed. Can you do a search and replace in the project for: search `](setuptypes)` and replace with `](./setuptypes)`. Give it a test to make sure it works but I am sure it does.
