### ISSUE TITLE
[🐛 Bug]: Facing issue while executing cucumber based test cases on Appium server

### ISSUE THREAD

**Issue by RahulARanger** [webdriverio/webdriverio#11108]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.16.4

### Node.js Version

v18.16.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
[ {
        "appium:platformName": "Android",
        "appium:automationName": "UiAutomator2",
        "appium:deviceName": "Android",
        "appium:newCommandTimeout": 3600,
        "appium:connectHardwareKeyboard": true,
        "appium:chromedriverExecutableDir": join(cwd(), "bin"),
        "appium:chromedriverUseSystemExecutable": false,
        "appium:noReset": false
    }]
```

### What happened?

Executing test cases written in the Cucumber framework in mobile gives us this message: `You're calling functions (e.g. "Given") on an instance of Cucumber that isn't running.

Connecting with Appium - ✅
Installing given APK file in mobile - ✅
onPrepare hook is passing - ✅

Test Runner stops its execution when it starts executing the step file. 

### What is your expected behavior?

Execution of Test cases written in gherkin files in a mobile application (through Appium).

### How to reproduce the bug.

Create the following files.

Feature File:
```gherkin
Feature: Role-Based Access Functionality in the X Module
Scenario: If the Logged in users is an Admin
Given I login as "xyzi@ls.in"
``` 

Step definition file
```js
import { Given } from "@wdio/cucumber-framework";

Given("I login as {string}", async () => {
    console.log("worked")
})
```

> install appium 

`npm install appium` 
So we would be using Appium v2.1.3

either run the Appium manually `npx appium -p 4723` or use [appium-service](https://webdriver.io/docs/appium-service/)

now run this command `npm run wdio` which is in short for `wdio run ./wdio.conf.js`

### Relevant log output

```typescript
[0-0] 2023-09-07T10:06:11.383Z ERROR @wdio/runner: Error: 
[0-0]           You're calling functions (e.g. "Given") on an instance of Cucumber that isn't running.
[0-0]           This means you have an invalid installation, mostly likely due to:
[0-0]           - Cucumber being installed globally
[0-0]           - A project structure where your support code is depending on a different instance of Cucumber
[0-0]           Either way, you'll need to address this in order for Cucumber to work.
[0-0]           See https://github.com/cucumber/cucumber-js/blob/main/docs/installation.md#invalid-installations
[0-0]
[0-0]     at checkInstall (.\@cucumber\cucumber\src\support_code_library_builder\index.ts:127:15)
[0-0]     at .\node_modules\@cucumber\cucumber\src\support_code_library_builder\index.ts:145:11
[0-0]     at file:///C:/Users/tangellapalli.s/Documents/appium-webdriverio/ace-mobile-automation/step-definitions/login.steps.js:3:1
[0-0]  Error: 
          You're calling functions (e.g. "Given") on an instance of Cucumber that isn't running.
          This means you have an invalid installation, mostly likely due to:
          - Cucumber being installed globally
          - A project structure where your support code is depending on a different instance of Cucumber      
          Either way, you'll need to address this in order for Cucumber to work.
          See https://github.com/cucumber/cucumber-js/blob/main/docs/installation.md#invalid-installations 
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@RahulARanger are you using the latest WebdriverIO version? I don't think this is related to Appium at all, can you maybe create a reproducible example for a web test?

@tamil777selvan it seems like the Cucumber primitives we export don't seem to be the same used by Cucumber anymore, wdyt?

**Comment by RahulARanger** [comment]
@christian-bromann yes I am latest version of both cucumber framework and webdriverio 8.16.4

Sure sharing some example in few mins. 

I didn't face this issue in web,i faced this while running for mobile e2e test

**Comment by tamil777selvan** [comment]
@christian-bromann, I'm wondering if there could be multiple versions of Cucumber installed, which might be causing [this issue](https://github.com/cucumber/cucumber-js/blob/main/docs/installation.md#duplicate-dependency). 

@RahulARanger, Could you kindly verify whether you have installed any other version of `@cucumber/cucumber` apart from `9.4.0`?

**Comment by tamil777selvan** [comment]
Furthermore, I'm currently in the process of upgrading the version of `@cucumber/cucumber` to `9.5.1`, which addresses the issue mentioned in https://github.com/webdriverio/webdriverio/pull/11010#discussion_r1316999608.

**Comment by christian-bromann** [comment]
> I'm wondering if there could be multiple versions of Cucumber installed

As you can see @RahulARanger is importing the Cucumber primitives we export in WebdriverIO, so they have to use the same Cucumber version, right?

> Furthermore, I'm currently in the process of upgrading the version of `@cucumber/cucumber` to `9.5.1`, which addresses the issue mentioned in [#11010 (comment)](https://github.com/webdriverio/webdriverio/pull/11010#discussion_r1316999608).

Awesome!

**Comment by RahulARanger** [comment]
@tamil777selvan its v9.4.0

**Comment by RahulARanger** [comment]
I checked with the above files but just replaced the existing capabilities with:

```js
[{ browserName: "chrome" }]
```
It's working as expected.

**Comment by tamil777selvan** [comment]
> As you can see @RahulARanger is importing the Cucumber primitives we export in WebdriverIO, so they have to use the same Cucumber version, right?

In an ideal scenario, yes, unless cucumber hasn't been explicitly installed or included by other packages.

**Comment by RahulARanger** [comment]
@tamil777selvan sure I will. Could you also share the appium version I believe we are using v2.1.3

**Comment by tamil777selvan** [comment]
> @tamil777selvan sure I will. Could you also share the appium version I believe we are using v2.1.3

My version was `2.1.2`, but this is unrelated to Appium.

**Comment by RahulARanger** [comment]
```json
{
  "name": "mobile",
  "version": "1.0.0",
  "description": "",
  "type": "module",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "wdio": "wdio run ./wdio.conf.js"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.22.15",
    "@babel/preset-env": "^7.22.15",
    "@babel/register": "^7.22.15"
  },
  "dependencies": {
    "@wdio/appium-service": "^8.16.4",
    "@wdio/cucumber-framework": "^8.16.4",
    "@wdio/local-runner": "^8.16.4",
    "@wdio/spec-reporter": "^8.16.3",
    "appium": "^2.1.3",
    "appium-uiautomator2-driver": "^2.29.5",
    "chromedriver": "^116.0.0",
    "ts-node": "^10.9.1",
    "wdio-chromedriver-service": "^8.1.1",
    "wdio-wait-for": "^3.0.6"
  }
}
```

Here's my package.json I hope this helps.


FYI I added `ts-node` in order to escape from this `Error: "ts-node/esm/transpile-only 'resolve'" did not call the next hook in its chain and did not explicitly signal a short circuit. If this is intentional, include 'shortCircuit: true' in the hook's return.` but it's not required for my JS-Project.

**Comment by RahulARanger** [comment]
@tamil777selvan is there any way I could search for the alternate cucumber package that's causing this issue?

**Comment by tamil777selvan** [comment]
> @tamil777selvan is there any way I could search for the alternate cucumber package that's causing this issue?

Please try to gather a list of all the packages inside your project repository and see if any other version of cucumber is installed. Run the following commands:

For your project:
```
npm list --depth=1
```

For a global check:
```
npm list -g --depth=1
```

**Comment by RahulARanger** [comment]
I could only see the @cucumber/cucumber@9.4.0 listed under @wdio/cucumber-framework@8.16.4. And as per the docs, I could confirm it's not due to the first reason. because if it finds a duplicate version, I would see some warning message as mentioned [here](https://github.com/cucumber/cucumber-js/blob/main/docs/installation.md#duplicate-dependency). but unfortunately, I didn't.

here's the demo project; https://stackblitz.com/edit/js-wrqivi

For running the package, please download the latest version of https://github.com/webdriverio/native-demo-app and place it under the `bin` folder as `demo.apk`.

![image](https://github.com/webdriverio/webdriverio/assets/57987728/e6802a45-5e9e-4cf0-b8bf-677837c638fc)
It fails at the third line

I am happy to see it work in your case, please share if there's any mistake I made while configuring.

**Comment by RahulARanger** [comment]
@tamil777selvan yes I did try command 'npm - g list' but couldn't find the cucumber installed. I will reinstall node if possible and update if i see any improvement

**Comment by RahulARanger** [comment]
@tamil777selvan I found the library causing this issue in the global package: `wdio-cucumber-framework` I might have installed it accidentally. 

Uninstalling it resolved this issue, Hence closing this issue.

**Comment by christian-bromann** [comment]
Thanks for confirming!
