### ISSUE TITLE
[🐛 Bug]: Cannot install WebdriverIO latest using Node 16. Dependent package ky@^1.0.0 requires Node 18

### ISSUE THREAD

**Issue by kdecelle** [webdriverio/webdriverio#11114]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

16.20.2

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
N/A
```

### What happened?

Running `npm install -D webdriver@latest` fails when using Node 16 (npm 8) due to "Unsupported engine" failure for dependency package `ky@^1.0.0`.

Breaking change to require Node 18 for `ky`: https://github.com/sindresorhus/ky/releases/tag/v1.0.0

`webderiverio` dependency was bumped from 0.33.0 to 1.0.0 here: https://github.com/webdriverio/webdriverio/commit/f4ebb241b3735302abd0d9aa2e13b91e9aa4593a

### What is your expected behavior?

WebdriverIO should allow install with Node 16: https://webdriver.io/docs/gettingstarted/#system-requirements

### How to reproduce the bug.

To reproduce the bug:
* Install Node 16 LTS, npm version 8+.
* Attempt to install latest webdriverio package `npm install -D webdriver@latest`

### Relevant log output

```typescript
Snippet from .npm debug logs:

303 silly placeDep ROOT ky@1.0.1 OK for: webdriver@8.16.4 want: ^1.0.0
...
1232 error code EBADENGINE
1233 error engine Unsupported engine
1234 error engine Not compatible with your version of node/npm: ky@1.0.1
1235 error notsup Not compatible with your version of node/npm: ky@1.0.1
1235 error notsup Required: {"node":">=18"}
1235 error notsup Actual:   {"npm":"8.19.4","node":"v16.20.2"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@kdecelle thanks for reporting, this slipped through the cracks of our automated dependency updates. Will be fixed with the next release.
