### ISSUE TITLE
[📖 Docs]: <This or These options??>

### ISSUE THREAD

**Issue by kent-hervey** [webdriverio/webdriverio#11112]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Unclear documentation

### Description of the improvement / report

I would edit, but I really don't know the resolution--I really don't know if single or multiple.  It seems like just grammar, but the meanings are different

On this page:  https://webdriver.io/docs/api/expect-webdriverio/

In the two below places, do we mean that both String and Number have multiple options, so "This options" should become "These options. OR, do we mean there is only one option for each and this "This options" should become "This option"

??

> String Options
> This options can be applied in addition to the command options when strings are being asserted.
> ......
> Number Options
> This options can be applied in addition to the command options when numbers are being asserted.

![image](https://github.com/webdriverio/webdriverio/assets/41525831/da655f08-ec61-4e2e-87b3-fb51bc4b148c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Thanks for raising the issue @kent-hervey 

This should definitely say `this.option`. I tested the behavior and it doesn't recognise having e.g. `eq` and `lte` set.

Mind raising a PR in https://github.com/webdriverio/expect-webdriverio/blob/main/docs/API.md ?

**Comment by kent-hervey** [comment]
I can pick it up.  

I suppose I need to figure how to remove "help wanted" as a first step.  Then read contributing guidelines.

**Comment by christian-bromann** [comment]
> I suppose I need to figure how to remove "help wanted" as a first step.

I can only do it and just did.

> Then read contributing guidelines.

No real need for it since you just updating docs. Just clone the `expect-webdriverio` project, make the updates and raise a PR. Happy to support if there are specific questions around that.

**Comment by kent-hervey** [comment]
Here is the PR:  https://github.com/webdriverio/expect-webdriverio/pull/1281

There is some complaint about Easy CLA which I don't understand....

**Comment by christian-bromann** [comment]
@kent-hervey please sign the CLA, it basically ensures that all IP stays within the project.

**Comment by kent-hervey** [comment]
My global git email was a different one than my GitHub account and the signed CLA, but I changed it using:

git config user.email   

I could not tell that it was accepted, so I did a new commit and looked at the PR with .patch suffix 

It shows the corrected email

**Comment by kent-hervey** [comment]
And here:

![image](https://github.com/webdriverio/webdriverio/assets/41525831/fecac5c7-e091-4d45-9664-baaf45b28dc5)

**Comment by christian-bromann** [comment]
<img width="1212" alt="Screenshot 2023-09-07 at 14 33 23" src="https://github.com/webdriverio/webdriverio/assets/731337/36da2c36-a53c-4f2d-b7e6-9adabcb2ce16">

Unfortunately all made commits must match the email you signed the CLA with. Can you squash all commits into 1?

**Comment by kent-hervey** [comment]
I think I have that accomplished

![image](https://github.com/webdriverio/webdriverio/assets/41525831/ee4d40b2-463c-47cc-91e3-529f9703b74d)

![image](https://github.com/webdriverio/webdriverio/assets/41525831/2d1c5373-764f-448c-91f2-bd46715b7887)

**Comment by christian-bromann** [comment]
Awesome 🎉

**Comment by christian-bromann** [comment]
Closing. Thanks for your contribution @kent-hervey
