### ISSUE TITLE
[🐛 Bug]: cucumber-framework: Error: Cannot find module 'pretty'

### ISSUE THREAD

**Issue by joao-motork** [webdriverio/webdriverio#11117]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.16.5

### Node.js Version

18.17.1

### Mode

WDIO Testrunner

### What happened?

I've just updated the dependencies of my automation project to the latest WDIO version (8.16.5).
I switch the usage of "@cucumber/cucumber" to "@wdio/cucumber-framework".
Then I tried to run the project but I get the error `ERROR @wdio/runner: Error: Cannot find module 'pretty'` and tests do not run.

### What is your expected behavior?

Project to tun.

### How to reproduce the bug.

Run a project with the following dependencies installed:

{
    "dependencies": {
        "@cucumber/cucumber": "^9.5.1",
        "@types/chai": "^4.3.6",
        "@types/node": "^20.5.9",
        "@types/fs-extra": "^11.0.1",
        "@wdio/cli": "^8.16.5",
        "@wdio/cucumber-framework": "^8.16.5",
        "@wdio/local-runner": "^8.16.5",
        "wdio-lambdatest-service": "2.1.0",
        "chai": "^4.3.8",
        "multiple-cucumber-html-reporter": "^3.4.0",
        "ts-node": "^10.9.1",
        "tsconfig-paths": "^4.2.0",
        "typescript": "^5.2.2",
        "chromedriver": "116.0.0",
        "wdio-cucumberjs-json-reporter": "^5.1.7",
        "webdriverio": "^8.16.5"
    },
    "devDependencies": {
        "@typescript-eslint/eslint-plugin": "^6.6.0",
        "@typescript-eslint/parser": "^6.6.0",
        "eslint": "^8.48.0",
        "eslint-plugin-wdio": "^8.8.7",
        "eslint-config-prettier": "^9.0.0"
    }
}

### Relevant log output

![image](https://github.com/webdriverio/webdriverio/assets/132624270/e0683a29-2f17-41ca-981b-5590eee67495)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by tamil777selvan** [comment]
@joao-motork, Can you kindly provide the cucumberOpts configuration that you are using?

**Comment by joao-motork** [comment]
Hi @tamil777selvan 
`cucumberOpts: {
        requireModule: ["tsconfig-paths/register.js"],
        require: ["./src/steps/**/*.ts"],
        backtrace: true,
        dryRun: false,
        failFast: false,
        format: ["pretty"],
        colors: true,
        snippets: false,
        source: false,
        profile: [],
        strict: true,
        tagExpression: "",
        timeout: 60000,
        ignoreUndefinedDefinitions: false,
    }`

**Comment by tamil777selvan** [comment]
The `@wdio/cucumber-framework` comes with its own formatter designed to work with reporters extended from `@wdio/reporter` by default.

However, since you've utilized `format: ["pretty"]`, please note that this format is considered outdated, as indicated on https://www.npmjs.com/package/cucumber-pretty. To potentially resolve the error you're encountering, it's recommended to align with the [reporters](https://github.com/webdriverio/webdriverio#reporter) officially supported by WebdriverIO.

**Comment by joao-motork** [comment]
@tamil777selvan Thanks for the clarification a put `format: []` and it worked.

However, I faced another issue. At the end of the run, the report was not generated. This is my config:
![image](https://github.com/webdriverio/webdriverio/assets/132624270/96bf3257-9fa5-4cf3-8d47-99a9f3896c10)

Is there any change here in the latest version?

**Comment by tamil777selvan** [comment]
@joao-motork Please remove `format` option from `cucumberOpts` and this should resolve the problem, allowing you to generate the report.

The `format` option proves valuable in situations where we need to generate specific types of reports like `json` and `cucumber-messages` files. This is particularly helpful when we want to capture report data without displaying it in the standard output.

**Comment by joao-motork** [comment]
Thanks @tamil777selvan again for clarification.
Issue closed
