### ISSUE TITLE
[💡 Feature]: disable automatic driver setup when using devtools automation protocol

### ISSUE THREAD

**Issue by marcogrcr** [webdriverio/webdriverio#11129]
### Is your feature request related to a problem?

Version `8.14` introduced [automatic web driver configuration](https://webdriver.io/blog/2023/07/31/driver-management). While this is great, it can be an annoyance when using the `devtools` automation protocol. My tests run in a network environment with limited access to the Internet and they fail because of this. While this can be disabled (#11128), it's counterintuitive to specify a `port` or a driver `binary` to disable the download despite it will never be used.

### Describe the solution you'd like.

At first glance, it should be as simple as wrapping this:

https://github.com/webdriverio/webdriverio/blob/aa35c291fb496b80350766d674385ea7b4d1516a/packages/wdio-cli/src/launcher.ts#L138-L144

with an `if` statement as follows:

```ts
if (config.automationProtocol !== 'webdriver') {
    await Promise.all([
        setupDriver(config, caps),
        setupBrowser(config, caps)
    ])
}
```

However, this wouldn't work with configurations where multiple automation protocols are used, for example:

```ts
export const config: WebdriverIO.Config = {
  beforeSession(config, capabilities) {
    if (capabilities.browserName === 'chrome') {
      config.automationProtocol = 'devtools'
    } else {
      config.automationProtocol = 'webdriver'
    }
  }
  // ...
}
```

Thus, in order for this to work, the `setup*()` method invocations must be moved after the `onWorkerStart` and before the actual runner is started (e.g. line `437` below):

https://github.com/webdriverio/webdriverio/blob/aa35c291fb496b80350766d674385ea7b4d1516a/packages/wdio-cli/src/launcher.ts#L431-L439

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
@marcogrcr thanks for raising the issue and the other PR which I will look at tomorrow.

> However, this wouldn't work with configurations where multiple automation protocols are used, for example:

I am not aware WebdriverIO would support this. The only way of using different automation protocols is through using multiremote.

I raised a PR in #11130 that resolves the problem, please take a look.

__Note:__ I personally would not recommend using the `devtools` automation protocol. The reason I've implemented it was because it simplified running WebdriverIO given Puppeteer doesn't require a driver. These days since setting up driver is part of WebdriverIO I would not use it anymore. We can't guarantee that all the automation commands in [`devtools`](https://www.npmjs.com/package/devtools) behave the same as in WebDriver.

**Comment by marcogrcr** [comment]
> I am not aware WebdriverIO would support this. The only way of using different automation protocols is through using multiremote.

Hmm I guess it works since that was my setup 😅. For some reason when I tried using the `devtools` protocol with `firefox`, the process would hang, so I wound up using `devtools` only for `chrome`.

> I personally would not recommend using the `devtools` automation protocol.

That's good to know and bad to know since I just migrated both browsers to `devtools` 🥲. It turns out after updating my dependencies to the latest version of `wdio`, the process no longer hangs with `firefox` + `devtools`, so I wound up deciding to simplify thing on my side by using `devtools` everywhere.

Unfortunately, the environment where I run my tests cannot use the driver automated setup since the hosts have limited Internet access and they can't access the endpoints where the browsers/drivers are downloaded from, so I had to resort to somewhat complex logic to make `firefox` + `webdriver` work. If I go with `chrome` + `webdriver` as well, I would have to duplicate my setup logic for `chromedriver` as well.

Will `webdriver` not be supported in the future?

**Comment by christian-bromann** [comment]
> Will `webdriver` not be supported in the future?

You probably mean `devtools`, right? Most of our work these days is focused on WebDriver features and we won't be able to keep the `devtools` package feature compliant as we used to. In fact, with v9 we will no longer have `devtools` as dependency of `webdriverio` and will slowly fade this package out.
