### ISSUE TITLE
[🐛 Bug]: element.keys is not working in V8

### ISSUE THREAD

**Issue by skamineni** [webdriverio/webdriverio#11147]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

18.17.1

### Mode

WDIO Testrunner

### What happened?

In V7 we have tests that do below

let element = $('selector')
await element.click()
await element.keys('value')

Now in V8 all element.keys are throwing errors saying TypeError: elementToSelect.keys is not a function
or TypeError: (intermediate value).keys is not a function

### What is your expected behavior?

It should enter text

### How to reproduce the bug.

let element = $('selector')
await element.click()
await element.keys('value')

### Relevant log output

```typescript
TypeError: (intermediate value).keys is not a function

    at textInput.deleteText (/usr/src/huey/libs/testUtils/wdio/pages/textInput/textInput.po.js:58:35)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TableReport.search (/usr/src/huey/features/table-report/wdio/pages/gridTableReport.po.js:1051:5)
    at UserContext.<anonymous> (/usr/src/huey/qbServiceTests/sbserver/wdio/tests/productionDeploySmokeTest/actionsAutomationsWebHooks/webhooksSmokeTest.wdio.prod.smoke.js:98:5)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by skamineni** [comment]
Example await $$(
        `[data-test-id='reportBuilderSubpanel.color.header'] ~div div.itemPickerV2`
      )[dropdownIndex].keys(optionSearchText); are failing now which use to work in V7.

**Comment by christian-bromann** [comment]
> await element.keys('value')

You can't call `keys` on an element object because `keys` is setting the value to the current active element. You can either do:

```ts
element.addValue("value")
```

or:

```ts
element.click()
browser.keys("value")
```

Please join our [Discord](https://discord.webdriver.io) for questions around usage of WebdriverIO.

**Comment by skamineni** [comment]
Thanks! @christian-bromann  Brought it to your attention because this worked in V7. We can update our tests but just checking why this changed in V8 only.
