### ISSUE TITLE
Cannot init a new session, please end your current session first

### ISSUE THREAD

**Issue by sahas-** [webdriverio/webdriverio#1114]
This may not be a real issue with wdio, but this question is out there in stackoverflow  for a few days now and I would like to get some help to fix this without going back to older wd versions..

sometimes my selenium grid errors out with this error `Session [e4b60cfd-88f9-40ad-a14f-18ba46355a30] ` was terminated due to TIMEOUT" and appears to be related to this issue in SeleniumHQ https://github.com/SeleniumHQ/selenium/issues/1557

In my webdriverio code, I can catch this exception like

    .getAttribute('something').then((onSuccess,onError))

And inside onError, I'm trying end the session like

    client.end().then(()=>{
      console.log("ending the session due to error");
    });

    or

    client.session('delete').then(()=>{
      console.log("deleting the session due to error");
    });

Both of these didn't work. Meaning, I never saw my console messages. Possible that the session was terminated already (based on the previous error message).

However, when I try to run the test again, getting this error

    Cannot init a new session, please end your current session first

Whats the proper way to end the session and handle this issue?

Thanks !!

**Comment by christian-bromann** [comment]
If you are using the wdio test runner don't use `init` or `end` because the test runner takes care on creating/ending the session for you.

**Comment by sahas-** [comment]
Unfortunately, not using wdio. I'm using this as a module in a larger flow to scrap the screen..is there any guidance to handle this error?

**Comment by christian-bromann** [comment]
Then make sure that you don't end a session and use the same instance to scrap other pages. Once the session is over you have to call `init` again
