### ISSUE TITLE
Error while usinng firefox 

### ISSUE THREAD

**Issue by kundarsowjanya** [webdriverio/webdriverio#11169]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

16.16.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [{
        browserName: 'firefox',
        browserVersion: 'latest',
        'moz:firefoxOptions': {
            args: ['-headless','--no-sandbox','--disable-dev-shm-usage']
        }
    }],
```

### What happened?

Getting this error :
  ERROR @wdio/runner: Error: Failed to create session.
14:20:12  [0-0] Timeout awaiting 'response' for 120000ms when running "http://0.0.0.0:39627/session" with method "POST" and args "{"capabilities":{"alwaysMatch":{"browserName":"firefox","moz:firefoxOptions":{"binary":"/tmp/firefox/linux-119.0a1/firefox/firefox","args":["-headless","--no-sandbox","--disable-dev-shm-usage"]}},"firstMatch":[{}]},"desiredCapabilities":{"browserName":"firefox","moz:firefoxOptions":{"binary":"/tmp/firefox/linux-119.0a1/firefox/firefox","args":["-headless","--no-sandbox","--disable-dev-shm-usage"]}}}"

In local it's working fine, with same config If try to use it in pipeline jenkins or in docker getting this error

### What is your expected behavior?

Testcases should pass

### How to reproduce the bug.

    capabilities: [{
        browserName: 'firefox',
        browserVersion: 'latest',
        'moz:firefoxOptions': {
            args: ['-headless','--no-sandbox','--disable-dev-shm-usage']
        }
    }],

### Relevant log output

```typescript
ERROR @wdio/runner: Error: Failed to create session.
14:20:12  [0-0] Timeout awaiting 'response' for 120000ms when running "http://0.0.0.0:39627/session" with method "POST" and args "{"capabilities":{"alwaysMatch":{"browserName":"firefox","moz:firefoxOptions":{"binary":"/tmp/firefox/linux-119.0a1/firefox/firefox","args":["-headless","--no-sandbox","--disable-dev-shm-usage"]}},"firstMatch":[{}]},"desiredCapabilities":{"browserName":"firefox","moz:firefoxOptions":{"binary":"/tmp/firefox/linux-119.0a1/firefox/firefox","args":["-headless","--no-sandbox","--disable-dev-shm-usage"]}}}"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment]
I believe the arguments other than headless are for chrome, not Firefox. Other than that, please share the driver logs as well

**Comment by kundarsowjanya** [comment]
Hi @erwinheitzman  I created new project by referring  Getting Started documentation, And I added capabilities as like this
```
    capabilities: [{
        browserName: 'firefox',
        browserVersion: 'latest',
        'moz:firefoxOptions': {
            args: ['-headless']
        }
    }],
```

But unfortunately  still firefox is not launching in pipeline and docker , This is the error I'm getting.
<img width="617" alt="image" src="https://github.com/webdriverio/webdriverio/assets/21242317/29c866b8-1742-48cf-b4e6-ad38af5848b0">

**Comment by christian-bromann** [comment]
@kundarsowjanya can you provide a reproducible example, e.g. a new WebdriverIO project with a Dockerfile as GitHub project?

**Comment by jRichardeau** [comment]
Hello,

I'm facing similar issue with firefox since upgrading webdriver version from `8.11.2` to `8.16.7`(I removed `wdio-geckodriver-service`), firefox session starts but after a (little) while browser is freezing and I get some errors like :

`Request failed with status undefined due to TimeoutError: Timeout awaiting 'response' for 120000ms when running "elements" with method "POST" and args "{"using":"css selector","value":"XXXX"}"`.

I have to kill the test session to stop it.

**Comment by erwinheitzman** [comment]
@jRichardeau are you also using `browserVersion` `latest`?

**Comment by jRichardeau** [comment]
I'm using Firefox Developer Edition but had same issue with Firefox (latest).

It seems the problem has disappeared since I updated `WebDriver` to `8.16.10` 👌

**Comment by christian-bromann** [comment]
Thanks for confirming @jRichardeau , I will close then. Happy to re-open if folks still experience issues.
