### ISSUE TITLE
[🐛 Bug]: Screenshot on Failure is not attached to Allure report in case we are using Multiremote capabilities with WDIO v8

### ISSUE THREAD

**Issue by AntRybalko** [webdriverio/webdriverio#11164]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

20.5.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: {
          myChromeDriver: {
              capabilities: {
                  browserName: 'chrome',
                  'wdio:devtoolsOptions': { headless: false }
              }
          }
        }
```

### What happened?

In the case of using MultiRemote capabilities screenshots of failure are not attached to the Allure report at all
In the case of using not multiremote caps - everything works as expected - I see screenshots inside the Allure report

### What is your expected behavior?

Allure report should contain screenshots on failure in case of using of MultiRemote capabilities

### How to reproduce the bug.

All instructions are mentioned inside the Readme file in my Git Repo
https://github.com/AntRybalko/wdiov8test

### Relevant log output

```typescript
❯ npm run test-local

> webdriverIO-with-cucumberBDD@2.0.4 test-local
> wdio  wdio.local.conf.ts


Execution of 1 workers started at 2023-09-13T14:10:33.877Z

[0-0] RUNNING in MultiRemote - file:///test/features/login.feature
[0-0] Error in "0: Then I should see a flash message saying You logged into a secure area!"
Error: Expect $(`#flash`) to have text

Expected: "test"
Received: ["You logged into a secure area!
×"]
    at World.<anonymous> (file:///Users/arybalko/NomoRepos/wdiov8test/test/step-definitions/then.ts:8:41)
[0-0] Error in "1: Then I should see a flash message saying Your username is invalid!"
Error: Expect $(`#flash`) to have text

Expected: "test"
Received: ["Your username is invalid!
×"]
    at World.<anonymous> (file:///Users/arybalko/NomoRepos/wdiov8test/test/step-definitions/then.ts:8:41)
[0-0] FAILED in MultiRemote - file:///test/features/login.feature

 "spec" Reporter:
------------------------------------------------------------------
[MultiremoteBrowser #0-0] Running: MultiremoteBrowser on chrome
[MultiremoteBrowser #0-0]
[MultiremoteBrowser #0-0] » test/features/login.feature
[MultiremoteBrowser #0-0] The Internet Guinea Pig Website
[MultiremoteBrowser #0-0] As a user, I can log into the secure area
[MultiremoteBrowser #0-0]    ✓ Given I am on the login page
[MultiremoteBrowser #0-0]    ✓ When I login with tomsmith and SuperSecretPassword!
[MultiremoteBrowser #0-0]    ✖ Then I should see a flash message saying You logged into a secure area!
[MultiremoteBrowser #0-0]
[MultiremoteBrowser #0-0] As a user, I can log into the secure area
[MultiremoteBrowser #0-0]    ✓ Given I am on the login page
[MultiremoteBrowser #0-0]    ✓ When I login with foobar and barfoo
[MultiremoteBrowser #0-0]    ✖ Then I should see a flash message saying Your username is invalid!
[MultiremoteBrowser #0-0]
[MultiremoteBrowser #0-0] 4 passing (26s)
[MultiremoteBrowser #0-0] 2 failing
[MultiremoteBrowser #0-0]
[MultiremoteBrowser #0-0] 1) As a user, I can log into the secure area Then I should see a flash message saying You logged into a secure area!
[MultiremoteBrowser #0-0] Error: Expect $(`#flash`) to have text
[MultiremoteBrowser #0-0] Error: Expect $(`#flash`) to have text
[MultiremoteBrowser #0-0]
[MultiremoteBrowser #0-0] Expected: "test"
[MultiremoteBrowser #0-0] Received: ["You logged into a secure area!
[MultiremoteBrowser #0-0] ×"]
[MultiremoteBrowser #0-0]     at World.<anonymous> (file:///Users/arybalko/NomoRepos/wdiov8test/test/step-definitions/then.ts:8:41)
[MultiremoteBrowser #0-0]
[MultiremoteBrowser #0-0] 2) As a user, I can log into the secure area Then I should see a flash message saying Your username is invalid!
[MultiremoteBrowser #0-0] Error: Expect $(`#flash`) to have text
[MultiremoteBrowser #0-0] Error: Expect $(`#flash`) to have text
[MultiremoteBrowser #0-0]
[MultiremoteBrowser #0-0] Expected: "test"
[MultiremoteBrowser #0-0] Received: ["Your username is invalid!
[MultiremoteBrowser #0-0] ×"]
[MultiremoteBrowser #0-0]     at World.<anonymous> (file:///Users/arybalko/NomoRepos/wdiov8test/test/step-definitions/then.ts:8:41)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!



We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by sushantsoni5392** [comment]
This happens even without the `Multiremote` capabilities and seems like a generic issue. I have added a reproducible example here - https://github.com/sushantsoni5392/wdio-mocha-boilerplate

I investigated a bit, it seems like the code doesn't go past line [ #493](https://github.com/webdriverio/webdriverio/blame/main/packages/wdio-allure-reporter/src/reporter.ts#L493).

`this._state.currentStep` is undefined

![image](https://github.com/webdriverio/webdriverio/assets/3597767/6d2b24cd-548c-4019-8374-107372d8c284)

If I revert the change made in [this MR](https://github.com/webdriverio/webdriverio/commit/3bde885cabc0a39f19c58ffbd27f63d6a2c6a274), the screenshot is attached. But I do not know why this change was done in the first place.

**Comment by BorisOsipov** [comment]
@AntRybalko It is not a bug. It is intentional a long time ago - we don't attach screns for multiremote mode. I don't remember why and maybe now it maybe changed if it works.

**Comment by BorisOsipov** [comment]
@sushantsoni5392 This is a completely different issue. Please file a new bug with repro repo

**Comment by BorisOsipov** [comment]
@AntRybalko 
>But on V7 screenshots on failure successfully attached for Allure report with Multiremote

It was a bug 🙂. Seems to have been "fixed" in v8 when migrating to the new allure-commons.

**Comment by AntRybalko** [comment]
@BorisOsipov And what should I do if I need them with Multiremote? :) Workarounds?

**Comment by BorisOsipov** [comment]
@AntRybalko make a PR to remove [Multiremote check here](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-allure-reporter/src/reporter.ts#L476)[and [here](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-allure-reporter/src/reporter.ts#L493)
