### ISSUE TITLE
Selenium standalone not able to run 

### ISSUE THREAD

**Issue by kundarsowjanya** [webdriverio/webdriverio#11163]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

18

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [{
        browserName: 'MicrosoftEdge',
        'ms:edgeOptions': {
            //  "binary": filePath,
            args: ['--headless', '--no-sandbox', '--disable-dev-shm-usage']
        }
    }],
```

### What happened?

Whenever I tried to run the testcase I'm getting this error 
 ERROR @wdio/runner: Error: Failed to create session.
[0-0] Unable to connect to "http://localhost:4444/", make sure browser driver is running on that address.

I'm using selenium standalone as a service inside config file like this

       services: [
        ['selenium-standalone', {
            logPath: 'logs',
            installArgs: { drivers }, // drivers to install
            args: { drivers } // drivers to use
        }]
    ],

I checked the document I didn't find selenium-standalone service inside service config. Is it removed? Is that is the reason I'm getting error? 

https://webdriver.io/docs/appium-service

### What is your expected behavior?

It should launch selenium standalone service and run the application

### How to reproduce the bug.

Add selenium as a service and hostname is localhost with port 

### Relevant log output

```typescript
@wdio/runner: Error: Failed to create session.
[0-0] Unable to connect to "http://localhost:4444/", make sure browser driver is running on that address.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment]
The package has been deprecated.

If you are on v8 you need to use the newly built-in driver manager that removes the heavy load of starting the selenium server just to start some drivers.  to read more about the new driver manager checkout our blog: https://webdriver.io/blog/2023/07/31/driver-management

If you are still on v7 you can use the wdio-chromedriver-service and the services for safari, firefox etc instead until you ugrade to v8.

**Comment by erwinheitzman** [comment]
The package has been deprecated.

If you are on v8 you need to use the newly built-in driver manager that removes the heavy load of starting the selenium server just to start some drivers. to read more about the new driver manager checkout our blog: https://webdriver.io/blog/2023/07/31/driver-management

If you are still on v7 you can use the wdio-chromedriver-service and the services for safari, firefox etc instead until you ugrade to v8.

**Comment by kundarsowjanya** [comment]
Hi I'm using V8, and I need to test my testcases for chrome, firfox and edge browser. How do I test these using V8.

**Comment by christian-bromann** [comment]
@kundarsowjanya you can remove the `@wdio/selenium-standalone-service` or `selenium-standalone` and just have WebdriverIO manage the setup. See the blog post linked by @erwinheitzman
