### ISSUE TITLE
Edge browser crashed

### ISSUE THREAD

**Issue by kundarsowjanya** [webdriverio/webdriverio#11170]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

16.16.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [{
        browserName: "MicrosoftEdge",
        'ms:edgedriverOptions': {
            binary:filePath,
        },
        'ms:edgeOptions': {
            args: ['--headless'],
            'binary':filePath,
        }
    }],
```

### What happened?

Running testcases in jenkins and docker for the browser edge, 

But getting error as browser is crashed, I'm downloaded msedgedriver and added in my project folder , and referring as filepath for binary.

### What is your expected behavior?

Edge should launch and run the testcases

### How to reproduce the bug.

<img width="694" alt="image" src="https://github.com/webdriverio/webdriverio/assets/21242317/cdeb4f8c-09a7-494b-9edc-612a4d2d3243">

### Relevant log output

```typescript
Request failed with status 500 due to session not created: Microsoft Edge failed to start: exited normally.

session not created: DevToolsActivePort file doesn't exist
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@kundarsowjanya thanks for raising the issue. It seems like you have set `msedgedriver` as browser binary. There is also no `ms:edgedriverOptions` in WebDriver. You probably mean `wdio:edgedriverOptions`. Please see https://webdriver.io/docs/capabilities#browser-specific-driver-options for the full documentation.

**Comment by christian-bromann** [comment]
Join our  [Discord](https://discord.webdriver.io) server for these kind of questions. This is not necessary a WebdriverIO related issue.

**Comment by kundarsowjanya** [comment]
@christian-bromann  I added  wdio:edgedriverOptions earlier but I got error like this:
<img width="647" alt="image" src="https://github.com/webdriverio/webdriverio/assets/21242317/b7a40030-2bde-4cc1-8fa4-31b0f4a09809">
