### ISSUE TITLE
[🐛 Bug]: Cucumber Framework - Feature tag not found

### ISSUE THREAD

**Issue by davidyew** [webdriverio/webdriverio#11171]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

Standalone Mode

### What happened?

GIVEN WDIO configured to use Cucumber Framework
WHEN a Feature has tags
THEN feature.tags should have the tags

Example
@api
Feature: API Testing

### What is your expected behavior?

In any event hooks that has feature object, the tags member should have the tags.

### How to reproduce the bug.

A feature file with at least this
@api
Feature: API Testing

Then to run the test

### Relevant log output

```typescript
[0-0] feature {
[0-0]   tags: [],
[0-0]   location: { line: 1, column: 1 },
[0-0]   language: 'en',
[0-0]   keyword: 'Feature',
[0-0]   name: 'API Testing',
[0-0]   description: '',
[0-0]   children: [ { scenario: [Object] } ]
[0-0] }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by tamil777selvan** [comment]
Hi @davidyew, Did you encounter any particular hook where you had difficulty retrieving the tags? I wasn't able to replicate the error myself.

![Screenshot 2023-09-15 at 7 52 18 AM](https://github.com/webdriverio/webdriverio/assets/49207189/865eb410-b8f5-4f09-a5a0-d9cf0dae56bc)

**Comment by davidyew** [comment]
I am sorry, it is a mistake on my part.
I was validating a wrong file.
