### ISSUE TITLE
Add a configue option to add a pause before each command.

### ISSUE THREAD

**Issue by vrundbaken** [webdriverio/webdriverio#1118]
Timing issues are not always obvious. I add pauses before commands while troubleshooting to determine if it's a timing issue or something else. I then have to remove all these pauses after I'm done. If there was a way to automatically add a pause before every command that could make identifying timing issues much easier.

**Comment by christian-bromann** [comment]
In v4 you can use the beforeCommand hook, to execute a pause before each command
