### ISSUE TITLE
Cannot click on DOM elements found in Hybrid App?

### ISSUE THREAD

**Issue by gsccheng** [webdriverio/webdriverio#1119]
Hi, can someone confirm that with this library it wouldn't be possible to properly click on DOM elements of hybrid apps such that the action is triggered (to load a new page). This is even after using a webview context when using Appium.

I can successfully `click` on a button but even after waiting for a while, the expected new page is not rendered. I got this to work with the WD.js library when I clicked on the native element instead, but I was hoping this library would magically be different, or can somehow map between the two contexts. Thanks.

**Comment by christian-bromann** [comment]
> somehow map between the two contexts.

Interesting idea. Automatically switch contexts given certain selectors.

> this library would magically be different

It is magically different but not in your case. You still need to specify the context you want to work in. How am I suppose to know which context you want to use?

**Comment by christian-bromann** [comment]
> map between the two contexts

Guessing which context is the best isn't feasible and only would cause confusion. Not sure why I labeled this as Enhancement but no library will handle context for you.
