### ISSUE TITLE
[🐛 Bug]: in the onPrepare hook, using getValue from shared store service crashes.

### ISSUE THREAD

**Issue by nbowman-lulus** [webdriverio/webdriverio#11208]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

LTS (18.18)

### Mode

WDIO Testrunner

### What happened?

In the onPrepare hook, using getValue crashes. 

### What is your expected behavior?

using getValue and setValue in the onPrepare hook as written up in the documentation https://www.npmjs.com/package/@wdio/shared-store-service should work.

### How to reproduce the bug.

Minimal repro case:
https://github.com/nbowman-lulus/wdio_test

npx wdio run .\wdio.conf.js --spec .\test\specs\test.e2e.js

Windows output:
```
npx wdio run .\wdio.conf.js --spec .\test\specs\test.e2e.js
Execution of 1 workers started at 2023-09-19T21:21:40.922Z
beginning of onPrepare

Ended WebDriver sessions gracefully after a SIGINT signal was received!
```

comment out ln 156 of wdio.conf and re-run same:

```
npx wdio run .\wdio.conf.js --spec .\test\specs\test.e2e.js

Execution of 1 workers started at 2023-09-19T21:23:29.709Z

beginning of onPrepare
[0-0] RUNNING in chrome - file:///<SNIP>/wdio_test/test/specs/test.e2e.js
[13892:20064:0919/142335.724:ERROR:policy_logger.cc(154)] :components\enterprise\browser\controller\chrome_browser_cloud_management_controller.cc(163) Cloud management controller initialization aborted as CBCM is not enabled.

DevTools listening on ws://127.0.0.1:55842/devtools/browser/82b7a1f1-bdb3-4598-bc12-0fca0d491626
[0-0] beginning test
[0-0] shared store values:
[0-0] {test: value}
```

### Relevant log output

```typescript
2023-09-19T21:21:40.966Z DEBUG @wdio/utils:initialiseServices: initialise service "shared-store" as NPM package
2023-09-19T21:21:41.036Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-09-19T21:21:41.038Z INFO @wdio/local-runner: Shutting down spawned worker
2023-09-19T21:21:41.303Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

edits: I was able to re-test on a different windows machine, where setValue worked fine, so removed references to it failing silently as that is probably something with my machine setup. using getValue in the onPrepare hook still crashes things.

**Comment by erwinheitzman** [comment]
getValue is currently indeed causing issues, no matter what hook you place it in.

**Comment by tamil777selvan** [comment]
Hi @erwinheitzman,

From what I've observed, the server for the "shared store" gets started in the `onPrepare` hook within the `runServiceHook`. This happens after the `onPrepare` hook in the `runLauncherHook` is executed.

This sequence cause a problem because the server is not ready when we're waiting for it, leading to unexpected failures.

I've thought of the following possible solutions to tackle this issue:
1. We can consider changing the order in which the hooks are executed. This would ensure that the server initialisation happens before any other hooks or processes that rely on it.
2. Alternatively, we might want to discourage the use of `getValue` in the `onPrepare` hook, as it could lead to issues like the one we're experiencing.

I'd appreciate your input on which approach we should adopt, or if you have any alternative ideas to consider.

**Comment by christian-bromann** [comment]
> 2\. Alternatively, we might want to discourage the use of `getValue` in the `onPrepare` hook, as it could lead to issues like the one we're experiencing.

I think this makes most sense. I don't see a reason why you would want to call `getValue` in the `onPrepare` hook, @nbowman-lulus can you elaborate your use case? What we support is using `setValue`. Afaik there is nothing that runs before the `onPrepare` hook and therefor there is nothing that can be received from the store.

**Comment by erwinheitzman** [comment]
I don't think this is the issue as like I have shared, using the getValue in the "after" hook also does not work anymore. It will cause the test to hang.

I'm quite confused about what could have caused this to suddenly break. I thought it might have been the Got upgrade to a new major version but I tried downgrading and that did not fix it. Pretty weird

**Comment by tamil777selvan** [comment]
Hi @erwinheitzman, I tested the usage of `getValue` in all the hooks except for `onPrepare` to make sure everything was working smoothly. Surprisingly, I didn't run into any issues in those cases.

However, the problem arises when we use `getValue` before the server starts in the `onPrepare` hook. At this point, the promise within `getValue`, specifically the `await baseUrlPromise`, doesn't get resolved as expected. This causes the tests to either hang indefinitely or terminate unexpectedly.

![Screenshot 2023-09-25 at 7 54 54 AM](https://github.com/webdriverio/webdriverio/assets/49207189/eda1bd87-fb6c-45e5-98db-8abaa2d8ef4e)

**Comment by christian-bromann** [comment]
Thanks for verifying @tamil777selvan.

@tamil777selvan what do you think of improving the error message if `getValue` is called within `onPrepare`?

**Comment by tamil777selvan** [comment]
I would consider adding an error log within the `getValue` function as below, which could prevent problems or unexpected failures when using this service. Please share your opinion

```javascript
if (!isBaseUrlReady) {
    log.error('Attempting to use `getValue` before the server has been initialised.')
    return
}
```

**Comment by christian-bromann** [comment]
An error message can get lost in the amount of logs that WebdriverIO is generating. Throwing an error makes more sense to me and makes this more explicit, what do you think @erwinheitzman ?

**Comment by christian-bromann** [comment]
Thanks @tamil777selvan for providing a better error message on this. We can go ahead and close this now.
