### ISSUE TITLE
[💡 Feature]: Add support for Appium launch/relaunch commands for iOS XCUITest driver v5.0.x

### ISSUE THREAD

**Issue by AntRybalko** [webdriverio/webdriverio#11205]
### Is your feature request related to a problem?

Starting from v5.0.0 of XCUITest driver for Appium main methods for app launching/relaunching stopped working

Based on their's changelist - 'Obsolete reset, launchApp and closeApp APIs now throw errors on invocation'

And in code:
  async closeApp() {
    throw new Error(
      `The closeApp API has been deprecated and is not supported anymore. ` +
      `Consider using corresponding 'mobile:' extensions to manage the state of the app under test.`
    );

And the same for async launchApp() { .... } and reset()

### Describe the solution you'd like.

All main Appium methods for app launch/relaunch should be refactored for iOS runs in accordance with XCUITest driver breaking changes

Here is the documentation that I found which could be useful during refactoring process - https://appium.readthedocs.io/en/latest/en/writing-running-appium/ios/ios-xctest-mobile-apps-management/

### Describe alternatives you've considered.

N/A

### Additional context

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
@AntRybalko there is already support for it, e.g.

```sh
await browser.execute('mobile:launchApp' { ... })
```

But I agree that we should update the protocol commands to reflect on these changes for Appium.

We greatly appreciate any contributions that help implement this feature request. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this feature being implemented. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!
