### ISSUE TITLE
Screenshot on Failure is not attached to Allure report

### ISSUE THREAD

**Issue by BorisOsipov** [webdriverio/webdriverio#11215]
Screenshot on Failure is not attached to Allure report.
I have added a reproducible example here - https://github.com/sushantsoni5392/wdio-mocha-boilerplate

I investigated a bit, it seems like the code doesn't go past line [ #493](https://github.com/webdriverio/webdriverio/blame/main/packages/wdio-allure-reporter/src/reporter.ts#L493).

`this._state.currentStep` is undefined

![image](https://github.com/webdriverio/webdriverio/assets/3597767/6d2b24cd-548c-4019-8374-107372d8c284)

If I revert the change made in [this MR](https://github.com/webdriverio/webdriverio/commit/3bde885cabc0a39f19c58ffbd27f63d6a2c6a274), the screenshot is attached. But I do not know why this change was done in the first place.

_Originally posted by @sushantsoni5392 in https://github.com/webdriverio/webdriverio/issues/11164#issuecomment-1725603766_

**Comment by erwinheitzman** [comment]
Here's a temporary workaround that was mentioned by one of our Discord users:
```js
import AllureReporter from '@wdio/allure-reporter';

// afterTest()
if (!passed) {

  // await browser.takeScreenshot();
  AllureReporter.addAttachment('Screenshot', Buffer.from(await browser.takeScreenshot(), 'base64'), 'image/png');
}
```

**Comment by sairam9994** [comment]
@erwinheitzman  When i try to use afterTest as you success, I'm getting undefined error "addAttachment". I was using latest v16 wdio library versions
```
const AllureReporter = require('@wdio/allure-reporter');

    afterTest: async function (test, context, { error, result, duration, passed, retries }) {
        if (!passed) {
            //await browser.takeScreenshot();
            AllureReporter.addAttachment('Screenshot', Buffer.from(await browser.takeScreenshot(), 'base64'), 'image/png');
        }
    },
  ```
 **Output error:**
```
[0-0] 2023-09-22T16:58:31.835Z ERROR @wdio/utils:shim: TypeError: Cannot read properties of undefined (reading 'addAttachment')
[0-0]     at Object.afterTest (tests/wdio.conf.js:331:28)
[0-0]     at file:///tests/node_modules/@wdio/utils/build/shim.js:31:27
[0-0]     at new Promise (<anonymous>)
[0-0]     at file:///tests/node_modules/@wdio/utils/build/shim.js:28:47
[0-0]     at Array.map (<anonymous>)
[0-0]     at executeHooksWithArgsShim (file:///tests/node_modules/@wdio/utils/build/shim.js:28:33)
[0-0]     at UserContext.testFrameworkFnWrapper (file:///tests/node_modules/@wdio/utils/build/test-framework/testFnWrapper.js:60:46)
[0-0] Error in "AfterTest Hook"
Cannot read properties of undefined (reading 'addAttachment')
```

**Comment by christian-bromann** [comment]
@sairam9994 WebdriverIO has no v16 can you verify you are using the latest version?

**Comment by nikhilgupta1789** [comment]
Even I am also facing the same issue screenshot is not getting attached to the webdriverio allure report with package release as version 8.16.12 and webdriverio cli version as 8.16.12. Kindly please anyone fix this issue we're facing this issue past 25 days.
