### ISSUE TITLE
[🐛 Bug]: cannot start multiple appium servers

### ISSUE THREAD

**Issue by hdesai-dave** [webdriverio/webdriverio#11212]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.8.0

### Node.js Version

18.15.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
config.services = (config.services ? config.services : []).concat([
  [
    'appium',
    {
      // This will use the globally installed version of Appium
      // command: 'appium',
      logPath: './wdio-appium1.log',
      args: {
        port: 4723,
        // This is needed to tell Appium that we can execute local ADB commands
        // and to automatically download the latest version of ChromeDriver
        relaxedSecurity: true,
        defaultCapabilities: `{"systemPort": 8200, "udid": "emulator-5554","command-timeout": "6000"}`
      },
    },
  ],
  [
    'appium',
    {
      // This will use the globally installed version of Appium
      // command: 'appium',
      logPath: './wdio-apium2.log',
      args: {
        port: 4725,
        // This is needed to tell Appium that we can execute local ADB commands
        // and to automatically download the latest version of ChromeDriver
        relaxedSecurity: true,
        defaultCapabilities: `{"systemPort": 8202, "udid": "emulator-5556","command-timeout": "6000"}`

      },
    },
  ]
]);
```

### What happened?

When i run 
```
node node_modules/appium/index.js --base-path / --port 4725 --relaxed-security --default-capabilities '{"systemPort": 8202, "udid": "emulator-5556", "command-timeout": "6000"}'
```
which is what above appium service config is supposed to do too the server starts just fine but when i run a test i get below error:
```
2023-09-20T04:02:15.539Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: Appium exited before timeout (exit code: 1)
    at ChildProcess.<anonymous> (file:///<local_path>/node_modules/@wdio/appium-service/build/launcher.js:116:22)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)

### What is your expected behavior?

2 appium servers should start succesfully

### How to reproduce the bug.

use the code provided in capabilities section above

### Relevant log output

```typescript
2023-09-20T04:02:15.539Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: Appium exited before timeout (exit code: 1)
    at ChildProcess.<anonymous> (file:///<local_path>/node_modules/@wdio/appium-service/build/launcher.js:116:22)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by tamil777selvan** [comment]
@hdesai-dave According to the [documentation](https://github.com/appium/appium/blob/master/packages/appium/docs/en/cli/args.md), `defaultCapabilities` should have an object as its value. Kindly adjust it accordingly to resolve the issue.

```
[
   'appium',
   {
      logPath: './wdio-appium1.log',
      args: {
         port: 4723,
         // This is needed to tell Appium that we can execute local ADB commands
         // and to automatically download the latest version of ChromeDriver
         relaxedSecurity: true,
         defaultCapabilities: {"systemPort": 8200, "udid": "emulator-5554","command-timeout": "6000"}
      }
   }
],
[
   'appium',
   {
      logPath: './wdio-apium2.log',
      args: {
         port: 4725,
         // This is needed to tell Appium that we can execute local ADB commands
         // and to automatically download the latest version of ChromeDriver
         relaxedSecurity: true,
         defaultCapabilities: {"systemPort": 8202, "udid": "emulator-5556","command-timeout": "6000"}
      }
   }
]
```

**Comment by tamil777selvan** [comment]
> ```
> 2023-09-20T18:18:12.237Z DEBUG @wdio/appium-service: Will spawn Appium process: node <local_path>/node_modules/appium/index.js --base-path / --port 4723 --relaxed-security --default-capabilities '[object Object]'
> 2023-09-20T18:18:12.241Z DEBUG @wdio/appium-service: Will spawn Appium process: node <local_path>/node_modules/appium/index.js --base-path / --port 4725 --relaxed-security --default-capabilities '[object Object]'
> ```

Hi @hdesai-dave, I've noticed that in the CLI, `--default-capabilities '[object Object]'` is being passed instead of `--default-capabilities {"systemPort":8200,"udid":"emulator-5554","command-timeout":"6000"}`, which appears to be causing an issue.

When I passed the values as shown below, I wasn't able to replicate the error. Could you please provide a sample codebase that can be used to reproduce the error?
![Screenshot 2023-09-21 at 6 49 47 AM](https://github.com/webdriverio/webdriverio/assets/49207189/b73a26eb-928f-4dda-8b2e-e81f15109421)

![Screenshot 2023-09-21 at 6 49 30 AM](https://github.com/webdriverio/webdriverio/assets/49207189/fe284357-1f41-47c2-a6ae-ae55e49ff7a1)

**Comment by erwinheitzman** [comment]
I think the issue might be that you are passing `/` as a path. `/` stands directory of your OS. I'm assuming you need `./`

**Comment by hdesai-dave** [comment]
> I think the issue might be that you are passing `/` as a path. `/` stands for the root directory of your OS. I'm assuming you need `./`

Which path are we talking about here?

**Comment by hdesai-dave** [comment]
This is a simple config change? Can we not try it on sample repo?

**Comment by tamil777selvan** [comment]
@hdesai-dave, We've tested this use-case and couldn't replicate the error. To provide more guidance, we would require a reproducible example.

**Comment by hdesai-dave** [comment]
> @hdesai-dave, We've tested this use-case and couldn't replicate the error. To provide more guidance, we would require a reproducible example.

Thank You @tamil777selvan ! Code that worked for me:
`config.services = (config.services ? config.services : []).concat([
  [
    'appium',
    {
      // This will use the globally installed version of Appium
      // command: 'appium',
      args: {
        log: './wdio-appium1.log',
        port: 4723,
        // This is needed to tell Appium that we can execute local ADB commands
        // and to automatically download the latest version of ChromeDriver
        relaxedSecurity: true,
        defaultCapabilities: {systemPort: 8200, 'appium:udid': 'emulator-5554','appium:command-timeout': '6000'}
      },
    },
  ],
  [
    'appium',
    {
      // This will use the globally installed version of Appium
      // command: 'appium',
      args: {
        log: './wdio-appium2.log',
        port: 4725,
        // This is needed to tell Appium that we can execute local ADB commands
        // and to automatically download the latest version of ChromeDriver
        relaxedSecurity: true,
        defaultCapabilities: {systemPort: 8201, 'appium:udid': 'emulator-5556','appium:command-timeout': '6000'}
      },
    },
  ]
]);`

But the problem is when i run the test, it runs against the first appium server only. Any help would be appreciated around running tests in parallel across multiple appium server instead of just 1 server!

**Comment by christian-bromann** [comment]
> But the problem is when i run the test, it runs against the first appium server only.

You can set the port number as part of your capabilities, e.g.:

```ts
export const config = {
  // ...
  capabilities: [{
    deviceName: '...',
    port: 4723
    // ...
  }, {
    deviceName: '...',
    port: 4725
    // ...
  }],
  // ...
}
```

**Comment by hdesai-dave** [comment]
> > But the problem is when i run the test, it runs against the first appium server only.
> 
> You can set the port number as part of your capabilities, e.g.:
> 
> ```ts
> export const config = {
>   // ...
>   capabilities: [{
>     deviceName: '...',
>     port: 4723
>     // ...
>   }, {
>     deviceName: '...',
>     port: 4725
>     // ...
>   }],
>   // ...
> }
> ```
> 
> One route we could go to make this easier is to have Appium start in the `beforeSession` hook as part of the worker process and have it set the `port` option for a random port automatically.

No luck @christian-bromann :
```
const sharedCapabilities = {
  'appium:appActivity': 'com.dave.MainActivity',
  'appium:automationName': sharedValues.automationName,
  'appium:appPackage': 'com.dave',
  'appium:platformName': platformName,
  'appium:newCommandTimeout': process.env.DEBUG === 'true' ? 300000 : 180,
  'appium:appWaitDuration': 30000,
  'appium:waitForIdleTimeout': 1000,
};

const singleDeviceCapabilities = [
  {
    ...sharedCapabilities,
    'appium:port': 4723,
    'appium:systemPort': 8200,
    'appium:udid': "emulator-5554",
  },
];

const multiDeviceCapabilities = [
  ...singleDeviceCapabilities,
  {
    ...sharedCapabilities,
    'appium:port': 4725,
    'appium:systemPort': 8201,
    'appium:udid': "emulator-5556",
  },
];
```

**Comment by hdesai-dave** [comment]
fixed it by changing 'appium:port': 4723 to port: 4723 and 'appium:port': 4725 to port: 4725 above
