### ISSUE TITLE
[💡 Feature]: Limited console logging for chrome driver download in WebdriverIO v8

### ISSUE THREAD

**Issue by Zarmeena** [webdriverio/webdriverio#11213]
### Is your feature request related to a problem?

Chrome browser on my machine updated and while executing the scripts, it's taking too long to download the latest chrome driver. Also, logging of each step is done which is flooding the command prompt window leading to difficulty in checking other console logs

### Describe the solution you'd like.

Can we not limit the console logging lines and update the download status differently?

Attached the current logging in Windows command prompt

![wdioV8_Logger](https://github.com/webdriverio/webdriverio/assets/46337025/196b622c-1ba8-43cd-8c90-b8e9b4e6f7dd)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by erwinheitzman** [comment]
I think we can overwrite the same line instead of posting a new line every time, would that help?

**Comment by Zarmeena** [comment]
> I think we can overwrite the same line instead of posting a new line every time, would that help?

Sure @erwinheitzman . That would be better!

**Comment by christian-bromann** [comment]
Thanks for raising this issue.

We greatly appreciate any contributions that help implement this feature request. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this feature being implemented. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by erwinheitzman** [comment]
Resolved by https://github.com/webdriverio/webdriverio/pull/11255
