### ISSUE TITLE
[🐛 Bug]: Allure nested steps aren't working

### ISSUE THREAD

**Issue by BorisOsipov** [webdriverio/webdriverio#11221]
Allure nested steps aren't working.

Test:
```
    it('should have the right title', async () => {
        await browser.url('https://github.com/')
        await step("foo", async ( that1) => {
            that1.parameter("name1", "value1");
            await step("bar", async (that2) => {
                that2.parameter("name2", "value2");
                return await step("baz", async (that3) => {
                    that3.parameter("name3", "value3");
                })
            })
        })
    })
 ```
 
Produces a flat hierarchy of steps
![image](https://github.com/webdriverio/webdriverio/assets/6514276/118c6a4b-22b3-44f6-b739-a4307a04353c)

I prepared repo with example https://github.com/BorisOsipov/wdio-allure-nested-step-issue

**Comment by BorisOsipov** [comment]
@epszaw Could you take a look? It seems critical issue if we deprecate other methods of creating steps

**Comment by epszaw** [comment]
@BorisOsipov of course. Will check as soon as possible

**Comment by epszaw** [comment]
Actually, it's not a bug. If you want to create nested step, you should call step method from the first argument of the callback:

```js
    it('should have the right title', async () => {
        await browser.url('https://github.com/')
        await step("foo", async ( that1) => {
            that1.parameter("name1", "value1");
            await that1.step("bar", async (that2) => {
                that2.parameter("name2", "value2");
                return await that2.step("baz", async (that3) => {
                    that3.parameter("name3", "value3");
                })
            })
        })
    })
```

**Comment by BorisOsipov** [comment]
@epszaw Thank you!

**Comment by Diegocortes15** [comment]
Hi everyone! Hope all you find well!

I am facing the same issue 😢

this is the code that I am try to run but for some reason it is not working, I don't know understand why 😢

```
  async enterFirstName({ firstName }) {
    await allureReporter.step(`⏩ Enter first name: ${firstName}`, async () => {
      await this._wdioFactory.sendTypedKeys(
        this._pageName,
        "inputFirstName",
        firstName
      );
    });
  }
```

The code works perfectly if I remove the `allureReporter.step`

Probably I've been doing something wrong. Anyone one can please help me with this doubt 😃
