### ISSUE TITLE
click(locator) on a drop down list -  Do not work in Linux / Firefox

### ISSUE THREAD

**Issue by andreas-smith1995** [webdriverio/webdriverio#1122]
Thank you very much for any help!

It works fine on Windows, but not work on Linux / Firefox (our server is on Amazon Web Service )

I use: client.click('.//*[text() = "Some Text"]')
   - I have tried many locators, none of them works. If use: element(locator) , it will pass, but not click().

I was trying to use: selectByVisibleText(), but not work at all. I think it is because there is no Select element for the drop down list?

The drop down list code is like this: 

div class="rui-combobox__dropdown" data-reactid=".0.0.0.2.0.1.1"// dropdown
          div id="11" class="rui-combobox-option"
          div id="12" class="rui-combobox-option"
              ------  span class="rui-combobox-option__text">Some Text</span
          /div>
         div id="280" class="rui-combobox-option"
/div> // end of dropdown
Error Message

Element is not currently visible and so may not be interacted withBuild info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'System info: host: 'ip-10.12.22.123', ip: '10.12.22.123', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-48-generic', java.version: '1.8.0_72'Driver info: driver.version: unknown
Stacktrace

RuntimeError: Element is not currently visible and so may not be interacted with
Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
System info: host: 'ip-10.12.22.123', ip: '10.12.22.123', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-48-generic', java.version: '1.8.0_72'
Driver info: driver.version: unknown

**Comment by christian-bromann** [comment]
> RuntimeError: Element is not currently visible and so may not be interacted with

It seems that you are selecting an element that is not visible. You can't interact with it (like the error message says).
