### ISSUE TITLE
[💡 Feature]: allow sharding tests for better scalability in large CI systems

### ISSUE THREAD

**Issue by muhqu** [webdriverio/webdriverio#11243]
### Is your feature request related to a problem?

We have over 100 tests and like to run them across multiple test executors in our CI environment. A single machine can only run a few browsers in parallel due to memory consumption. Being able to run the tests across multiple machines allows for better scaling.

### Describe the solution you'd like.

The [playwright](https://playwright.dev/docs/test-parallel#shard-tests-between-multiple-machines) and [vitest](https://vitest.dev/guide/cli.html#shard) test runners support a `--shard` parameter, that evenly splits the number of tests to run.
e.g. if you have 100 tests `--shard=1/4` would execute test 1-25, `--shard=2/4` would execute test 26-50, etc…

### Describe alternatives you've considered.

To work around the issue I can manually [group tests in test suites](https://webdriver.io/docs/organizingsuites/#grouping-test-specs-in-suites) and setup specific jobs to trigger each test suite to have them run across multiple machines... 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by erwinheitzman** [comment]
Hi @muhqu thank you for sharing this idea.

I think it's quite interesting and am interesting in how you currently run your tests on multiple devices. Do you use a selenium grid for example?

**Comment by muhqu** [comment]
We are currently using playwright, but looking to evaluate alternatives like WebdriverIO as browser interaction layer. Mostly because playwright is too opinionated and does not work well if you require persistent browser context (non-incognito), or if you need to test with Safari preview or Firefox nightly releases…

We’re not using Selenium Grid, but we have used BrowserStack and SauceLabs in the past. However, as the added latency between test code and remote browser had a huge impact on per-test performance, we are now running playwright test runners on multiple machines in parallel using their sharding mechanism. Each test runner also runs multiple workers, but we’re a bit limited by the memory footprint of our application (+4GB per browser).

That’s why I’m looking for a similar feature in WebdriverIO.

**Comment by christian-bromann** [comment]
@muhqu sounds like a valuable feature to have. Let me have a look into this. I am happy to make that contribution if it helps you run your tests more effectively.

**Comment by nextlevelbeard** [comment]
+1

**Comment by christian-bromann** [comment]
This has landed and was released. Closing.
