### ISSUE TITLE
Cannot select items by name attribute for Native UI elements

### ISSUE THREAD

**Issue by gsccheng** [webdriverio/webdriverio#1125]
Hi,

I am unable to identify a native UI element on the iPhone 6 simulator through Appium by searching with the name attribute. According to the [documentation](http://webdriver.io/guide/usage/selectors.html), you would use something like `[name="some-name"]` I am however able to locate my element using an x-path identifier.

So in my project, with `Create New Account` clearly being shown with `getSource` under the name attribute, and also being shown as the name attribute in my Appium Inspector, I am unable to grab that element with any of these queries with the `click` or `element` methods. Examples using `element` are shown:
```
.element('[name=Create New Account]')
.element(['name=Create New Account'])
.element('[name="Create New Account"]')
.element('[name="Create New Account"]')
.element('UIAStaticText').click('*="Create New Account"')
.element('Create New Account')
```

Without me putting more details and code, is there something obvious that I'm missing? Thanks.

**Comment by christian-bromann** [comment]
Are you using v4? If so it has also new (not yet documented selectors):

- recursive element search using the UiAutomator library (Android only)
  example: `browser.element('android=xxx')`
- recursive element search using the UIAutomation library (iOS-only)
  example: `browser.element('ios=xxx')`
- recursive element search using accessibility id
  example: `browser.element('~xxx')`

Maybe they work better.

**Comment by gsccheng** [comment]
Thanks for the response. Can you please clarify the examples or provide the exact commit of these changes? Using v4.0.3, it doesn't seem to be working for me, but my input may be wrong.

For example, for iOS, I have a UIAStaticText element. From the inspector in Appium, the details for the element are:
```
name: Login
type: UIAStaticText
value:
label: Login
enabled: true
visible: false
valid: true
location: {167, 351}
size: {41, 21}
xpath: //UIAApplication[1]/UIAWindow[1]/UIAScrollView[1]/UIAWebView[1]/UIAStaticText[4] 
```
I believe the label listed here would be the accessibility ID. Yet, using this '.element('Login')` would give this from Appium which seems to be the regularly documented CSS selector method:
```
nfo: --> POST /wd/hub/session/4374658c-bf48-4f37-92d8-2337a8e19b62/element {"using":"css selector","value":"Login"}
info: [debug] Invalid locator strategy: css selector
info: [debug] Responding to client with error: {"status":9,"value":{"message":"Invalid locator strategy: css selector","origValue":"Invalid locator strategy: css selector"},"sessionId":"4374658c-bf48-4f37-92d8-2337a8e19b62"}
info: <-- POST /wd/hub/session/4374658c-bf48-4f37-92d8-2337a8e19b62/element 500 3.797 ms - 177
```
Alternatively, using `.element('ios=Login')` gives this response:
```
info: [debug] Got result from instruments: {"status":17,"value":"Can't find variable: Login"}
info: [debug] Condition unmet after 1332ms. Timing out.
info: [debug] Responding to client with error: {"status":17,"value":{"message":"An error occurred while executing user supplied JavaScript.","origValue":"Can't find variable: Login"},"sessionId":"3f8f83c3-70f6-4df3-8962-2e625bcb69f5"}
info: <-- POST /wd/hub/session/3f8f83c3-70f6-4df3-8962-2e625bcb69f5/element 500 1352.863 ms - 187
```
Finally, using `.element('ios=UIAStaticText')` will give this response:
```
info: [debug] [INST] 2016-03-22 05:07:54 +0000 Error: VerboseError: smartWrap failed,
info: [debug] [INST] 2016-03-22 05:07:54 +0000 Error: Error during eval: [native code]
```

**Comment by christian-bromann** [comment]
Check out https://github.com/webdriverio/webdriverio/blob/master/docs/guide/usage/selectors.md#mobile-selectors
Also this blog post might be interesting: http://sauceio.com/index.php/2015/09/advanced-locator-strategies/

**Comment by gsccheng** [comment]
Thanks for the links. I did a really simple run according to the docs: 
[https://github.com/webdriverio/webdriverio/blob/master/docs/guide/usage/selectors.md#class-name](https://github.com/webdriverio/webdriverio/blob/master/docs/guide/usage/selectors.md#class-name
) where it is listed:
```
// iOS example
browser.click(`UIATextField`);
```
When I ran my own
```
.click('UIAStaticText')
```
I get the same error response from Appium
```
info: --> POST /wd/hub/session/ef73a7c2-7ebf-4f1f-9174-6d789b2e4413/element {"using":"css selector","value":"UIAStaticText"}
info: [debug] Invalid locator strategy: css selector
info: [debug] Responding to client with error: {"status":9,"value":{"message":"Invalid locator strategy: css selector","origValue":"Invalid locator strategy: css selector"},"sessionId":"ef73a7c2-7ebf-4f1f-9174-6d789b2e4413"}
info: <-- POST /wd/hub/session/ef73a7c2-7ebf-4f1f-9174-6d789b2e4413/element 500 6.165 ms - 177
```
where `UIAStaticText` should be an acceptable UIAutomation class name . I also definitely see the element there in my simulator. The screen is definitely loaded.

**Comment by christian-bromann** [comment]
@gsccheng sorry I've just seen that these selectors aren't published yet. It's on master though

**Comment by gsccheng** [comment]
Thanks for the quick responses. I'm using the master branch now, and it does look like a few more selector strategies are available to me. According to Appium I am searching by Accessibility ID with the `~` prefix and with Class Name with something like `.click('UIAStaticText')`.

However, the iOS UIAutomation selector strategy is not working for me. Using a selector like 
```
.click('UIATarget.localTarget().frontMostApp().mainWindow().scrollViews()[0].webViews()[0].staticTexts()["Login"]')
```
will result in the element not found. I haven't tried too many different inputs yet, but looking at Appium, I'm not sure if it's necessarily because of my input. Appium will give 
```
info: --> POST /wd/hub/session/2d603da0-ff06-4450-83df-ff8ecce8f7a6/element {"using":"class name","value":"UIATarget.localTarget().frontMostApp().mainWindow().scrollViews()[0].webViews()[0].staticTexts()[\"Login\"]"}
info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: "au.getElementByType('UIATarget.localTarget().frontMostApp().mainWindow().scrollViews()[0].webViews()[0].staticTexts()[\\\"Login\\\"]')"
info: [debug] Sending command to instruments: au.getElementByType('UIATarget.localTarget().frontMostApp().mainWindow().scrollViews()[0].webViews()[0].staticTexts()[\"Login\"]')
info: [debug] [INST] 2016-03-23 02:34:50 +0000 Debug: evaluation finished
info: [debug] [INST] 2016-03-23 02:34:50 +0000 Debug: responding with:
       2016-03-23 02:34:50 +0000 Debug: Running system command #11: /Users/GabbAHH/.nvm/versions/node/v4.3.0/bin/node /Users/GabbAHH/.nvm/versions/node/v4.3.0/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...
info: [debug] [INST] 2016-03-23 02:34:51 +0000 Debug: Got new command 11 from instruments: au.getElementByType('UIATarget.localTarget().frontMostApp().mainWindow().scrollViews()[0].webViews()[0].staticTexts()[\"Login\"]')
info: [debug] [INST] 2016-03-23 02:34:51 +0000 Debug: evaluating au.getElementByType('UIATarget.localTarget().frontMostApp().mainWindow().scrollViews()[0].webViews()[0].staticTexts()[\"Login\"]')
info: [debug] Socket data received (25 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}
info: [debug] Condition unmet after 988ms. Timing out.
info: [debug] Responding to client with error: {"status":7,"value":{"message":"An element could not be located on the page using the given search parameters.","origValue":""},"sessionId":"2d603da0-ff06-4450-83df-ff8ecce8f7a6"}
info: <-- POST /wd/hub/session/2d603da0-ff06-4450-83df-ff8ecce8f7a6/element 500 990.211 ms - 179
```
It looks like Appium thinks it's supposed to get element by `class name` and the method called is `getElementByType`. Instead, if done properly, wouldn't the method be something like `findElementsByIosUIAutomation`? Or is what's shown sort of the result after checking for other selector matches.

**Comment by christian-bromann** [comment]
@gsccheng class name is actually the right strategy, check out this blog post: http://sauceio.com/index.php/2015/09/advanced-locator-strategies/

**Comment by gsccheng** [comment]
I'm a little bit confused. From the blog post, there is a `class name` strategy which I believe works for me, and isn't my issue (I don't think is applicable because I need a specific `UIAStaticText` element and I'm not getting back a selection of them to choose from, nor can I seem to include other search params in the call).

What my issue is, is from the `-ios uiautomation` strategy listed in the blog link you provided. I can't seem to find anything with it. Are you saying with webdriverio, if I were to call something like 
```
.click('UIATarget.localTarget().frontMostApp().mainWindow().scrollViews()[0].webViews()[0].staticTexts()["Login"]')
```
or according to the Python example in the blog just
``` 
.click(.scrollViews()[0].webViews()[0].staticTexts()["Login"]')
```
that Appium is still supposed to be using a `class name` strategy? as indicated with this Appium log:
```
info: --> POST /wd/hub/session/021de781-df28-4d3c-b4cf-7c516200fc7e/element {"using":"class name","value":"UIATarget.localTarget().frontMostApp().mainWindow().scrollViews()[0].webViews()[0].staticTexts()[\"Login\"]"}
info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: "au.getElementByType('UIATarget.localTarget().frontMostApp().mainWindow().scrollViews()[0].webViews()[0].staticTexts()[\\\"Login\\\"]')"
```
You can also see a `.getElementByType` method being called, but shouldn't it be something equivalent to `.find_element_by_ios_uiautomation` ?

Thanks!

**Comment by gsccheng** [comment]
I'm thinking I'm having trouble finding an element inside a `UIAWebview` element using the ios uiautomation strategy because of Appium as explained here: 

> For some locator strategies we explicitly avoid recursing into a webview because there are so many elements within, and when in native mode, we don't really care what's in a webview.

[https://github.com/appium/appium/issues/4160](https://github.com/appium/appium/issues/4160)
[https://github.com/appium/appium/issues/4160](https://github.com/appium/appium/issues/4160)

Using the ios uiautomation strategy doesn't seem to be accepted by Appium either when I have switched over to a webview context.

For the time being I'm going to have to rely on the xpath strategy with something like 
```
.click('//UIAStaticText[contains(@name,"Login")]')
```

**Comment by gsccheng** [comment]
Okay I tried a few more things, perhaps this can be closed.

I realized I was just missing the `ios=` prefix in my calls  :grin:. As you've mentioned, the documentation isn't updated yet, and I didn't construct the arguments to the right of the equal sign properly before.

So, in the native context, something like
```
.click('ios=.scrollViews()[0].webViews()[0].staticTexts().withPredicate("name MATCHES \'Login\'")')
```
or
```
.click('ios=.elements()[0].webViews()[0].staticTexts().withPredicate("name MATCHES \'Login\'")')
```
or
```
.click('ios=UIATarget.localTarget().frontMostApp().mainWindow().staticTexts().withPredicate("name MATCHES \'Login\'")')
``` 
works. You can verify it in the Appium log using the `-ios uiautomation` strategy:
```
info: --> POST /wd/hub/session/abf18cf4-03c1-4923-8f05-48a636f8a165/element {"using":"-ios uiautomation","value":"UIATarget.localTarget().frontMostApp().mainWindow().scrollViews()[0].webViews()[0].staticTexts().withPredicate(\"name MATCHES 'Login'\")"}
```

However, it does look like I can't do any recursive searches in the webview with something like
```
.click('ios=.staticTexts().withPredicate("name MATCHES \'Login\'")')
```
or
```
.click('ios=staticTexts().withPredicate("name MATCHES \'Login\'")')
```
which will not find anything. I feel like I could be wrong here though. So, if I didn't want to be so constrained in my search, I may still have to resort back to using the xpath locator strategy of something like
```
.click('//UIAStaticText[contains(@name,"Login")]')
```

**Comment by rahulmr** [comment]
How to deal with WinAppDriver ? Find Element By Name say for calculator?

**Comment by christian-bromann** [comment]
@rahulmr use xPath

**Comment by rahulmr** [comment]
@christian-bromann wow great. Thanks a lot!
