### ISSUE TITLE
[🐛 Bug]: Appium not connected to Android emulator (headless mode) in Ubuntu server

### ISSUE THREAD

**Issue by Oleksii-QA** [webdriverio/webdriverio#11251]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.13.14

### Node.js Version

18.17.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
            "platformName": "Android",
            "appium:platformVersion": "9",
            "appium:deviceName": "devicename",
            "appium:app": join(process.cwd(), "./myapp"),
            "appium:automationName": "UiAutomator2",
            "appium:appPackage": "com.Myapp",
            "appium:adbExecTimeout": 50000,
            "appium:isHeadless": true,
            "appium:adbPort": "5037",
            "appium:ignoreHiddenApiPolicyError": true,
            "appium:noReset": true,
            'appium:newCommandTimeout': 12000
}
```

### What happened?

I try to run my tests in Ubuntu 20.04.4 LTS server (without GUI)
To install and run Android emulator (in headless mode) in server use similar installing like in https://gist.github.com/nhtua/2d294f276dc1e110a7ac14d69c37904f

`Android emulator version 32.1.15.0`
Started correct for me only after run with command:
`emulator -avd avdname -no-audio -no-window -no-accel &`

Adb devices:
```
List of devices attached
emulator-5554   device
```
According to the logs (via `abd logcat` commmand), it looks like the emulator is working correctly. the application is also installed correctly using the command `adb install  <app path>`

But after running tests, looks like appium not connected to emulator. 
Currently I see only this error in console:

In tests use JavaScript. Also I tried run test in Jenkins and in command line in server. Same errors.

My Dependencies in `package.json`
```
"devDependencies": {
    "@moroo/wdio-slack-reporter": "^8.1.0",
    "@wdio/appium-service": "^8.13.13",
    "@wdio/cli": "^8.13.14",
    "@wdio/local-runner": "^8.13.13",
    "@wdio/mocha-framework": "^8.13.13",
    "@wdio/spec-reporter": "^8.12.2",
    "appium": "^2.0.0-rc.5",
    "appium-uiautomator2-driver": "^2.29.3",
    "ts-node": "^10.9.1"
  },
```
 
Main config in wdio.conf.js
```
export const config = {
    runner: 'local',
    port: 4723,
    specs: [
        './test/specs/**/mytest.js'
    ],
maxInstances: 1,
    capabilities: [{
      same as provided above
           }],
logLevel: 'info',
bail: 0,
baseUrl: '',
waitforTimeout: 12000,
connectionRetryTimeout: 40000,
connectionRetryCount: 3,
services: [
        ['appium', {
            logPath : './Appiumlogs'
        }]
    ],
framework: 'mocha',
reporters: ['spec'Ї
mochaOpts: {
        ui: 'bdd',
        timeout: 100000000
    },
```

**Some additional information:**
After first test running, I checked intalled app to emulator via command `adb shell pm list packages`
I saw new installed app - `io.appium.settings`
And also if I kill emulator and run tests, I see error in test runner ouput:
`WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20035ms.`

It looks like Appium sees this emulator and tries to interact, but the tests don't run.

And also my tests are worked correctly in pc (Windows 10 pro) in headless mode and without headless mode

### What is your expected behavior?

Appium should connect to emulator in headless mode in Ubuntu server and run tests 

### How to reproduce the bug.

Some steps to reproduce:
Use Ubuntu 20.04.4 LTS server (without GUI)
1. Install JavaJDK and add JAVA_HOME variable to path
2. Install Android SDK 
3. Add `ANDROID_HOME` variable to path
4. Install Android emulator with image Android 9 Pie image (API Level 28)
5. Run emulator in command line in headless mode via command
`emulator -avd avdname -no-audio -no-window -no-accel &`
6. Check device via command `adb devices`. Emulator should work correctly
7. Install app via command adb install <path my app>
8. Run tests in command line (in test project folder) or run Job in Jenkins

### Relevant log output

```typescript
ERROR webdriver: Request failed with status undefined due to TimeoutError: Timeout awaiting 'response' for 40000ms when running "http://127.0.0.1:4723/session" with method "POST" and args "{"capabilities":{"alwaysMatch":{"platformName":"Android","appium:platformVersion":"9","appium:deviceName":"avd28","appium:app":"app path","appium:automationName":"UiAutomator2","appium:appPackage":"com.myapp","appium:adbExecTimeout":50000,"appium:isHeadless":true,"appium:adbPort":"5037","appium:ignoreHiddenApiPolicyError":true,"appium:noReset":true,"appium:newCommandTimeout":12000},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"Android","appium:platformVersion":"9","appium:deviceName":"avd28","appium:app":"apppath","appium:automationName":"UiAutomator2","appium:appPackage":"com.myapp","appium:adbExecTimeout":50000,"appium:isHeadless":true,"appium:adbPort":"5037","appium:ignoreHiddenApiPolicyError":true,"appium:noReset":true,"appium:newCommandTimeout":12000}}"
ERROR webdriver: TimeoutError: Timeout awaiting 'response' for 40000ms when running "http://127.0.0.1:4723/session" with method "POST" and args "{"capabilities":{"alwaysMatch":{"platformName":"Android","appium:platformVersion":"9","appium:deviceName":"avd28","appium:app":"apppath","appium:automationName":"UiAutomator2","appium:appPackage":"commyapp","appium:adbExecTimeout":50000,"appium:isHeadless":true,"appium:adbPort":"5037","appium:ignoreHiddenApiPolicyError":true,"appium:noReset":true,"appium:newCommandTimeout":12000},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"Android","appium:platformVersion":"9","appium:deviceName":"avd28","appium:app":"apppath","appium:automationName":"UiAutomator2","appium:appPackage":"commyapp","appium:adbExecTimeout":50000,"appium:isHeadless":true,"appium:adbPort":"5037","appium:ignoreHiddenApiPolicyError":true,"appium:noReset":true,"appium:newCommandTimeout":12000}}"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Hey @Oleksii-QA , this seems to me more like an Appium configuration issue than a bug in WebdriverIO directly. I recommend to reach out to the Appium support channels with this query. Thank you!
