### ISSUE TITLE
[📖 Docs]: Config bail documentation not clear

### ISSUE THREAD

**Issue by nils-hoyer** [webdriverio/webdriverio#11265]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Unclear documentation

### Description of the improvement / report

**Summary**
From the docs: 
> If you want your test run to **stop after a specific number of test** failures, use bail. (It defaults to 0, which runs all tests no matter what.) ...
ref: https://webdriver.io/docs/configuration/#bail

> With the bail option, you can tell WebdriverIO to stop testing after any **test fails.**

ref: https://webdriver.io/docs/organizingsuites/#stop-testing-after-failure

> // If you only want to run your tests until a **specific amount of tests have failed** use

ref: https://webdriver.io/de/docs/configurationfile/

**steps to reproduce**

spec file structure:

```
describe('spec1', () => {
it('test1', () => {})
    it('test2', () => {
        throw new Error('')
    })
    it('test3', () => {})
    it('test4', () => {
        throw new Error('')
    })
    it('test5', () => {})
    it('test6', () => {
        throw new Error('')
    })
})
```
Testcase
```
given: set config with bail 1
when: running spec file1, spec file2 spec file3
and: each spec file including 6 tests
then: file 1 executed with 6 tests
and: file 2 skipped
and: file 3: skipped
```

expected behavior: from the docs I expected the tests to stop after the the first failing test. E.g.:
```
then: file 1 executed with 2 tests, 4 skipped
and: file 2 skipped
and: file 3: skipped
```

When running this scenario with bail:2 it executes spec file 1, spec file 2 ans skip spec file 3.

**Solution**
Either the documentation is unclear and bail _stop after a specific number of test **files**_ or the implementation is not working as expected. 

**Side notes**
The Options Page link seems to be broken: https://webdriver.io/de/docs/organizingsuites/#stoppen-sie-den-testlauf-nach-einem-fehler
this term might be also incorrect or uncomplete. _Note: Please be aware that when using a third party test runner (such as Mocha), additional configuration might be required._ , because currently u can combine webdriverio bail and mocha bail if you want, but both works independently with different behavior.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by erwinheitzman** [comment]
The problem here is that you are running all these tests in parallel.

Imagine that you have 6 tests and you limit the max instances to 2 (parallel). This means that only two tests will run at the same time.
I set the bail option to 1 and let the third spec file error. 
This gives me the expected output of:
![test-results](https://github.com/webdriverio/webdriverio/assets/15839059/71772680-f4d5-49af-ad7f-aae6a1ba28ab)

Testcase (from the spec that fails:
![test-example](https://github.com/webdriverio/webdriverio/assets/15839059/43912967-f841-4c6c-8967-d34d31bfcd46)

**Comment by erwinheitzman** [comment]
So in summary, if I have 6 test files with all 3 testcases.

When running and the bail condition is met, it will break stop the execution at that point and will report X passed, N failed, R total (in my example, as expected the last two spec files have not ran)

**Comment by nils-hoyer** [comment]
First of all, thanks @erwinheitzman for diving into this. 

I guess your assumption is not corrent. I run the test sequential. I will now share my configuration and upload a example repo for you.

**wdio.conf.js**
```
exports.config = {
    automationProtocol: 'devtools',
    services: ['devtools'],
    maxInstances: 1,
    bail: 1,
    framework: 'mocha',
    mochaOpts: {
        timeout: 60000,
    },

    specs: [
        './test/specs/**/*.js'
    ],
    baseUrl: 'http://localhost',
    capabilities: [
        {
            browserName: 'chrome',
        },
    ],
   
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    reporters: ['spec'],
    logLevel: 'info',
}
```
**package.json**
```
...
"wdio": "wdio run ./wdio.conf.js"
...
```
**example test file (one of three)**
```
describe('spec1', () => {
    it('test1', () => {})
    it('test2', async () => {
        await expect(browser).toHaveUrl('https://webdriver.io')
    })
    it('test3', () => {})
    it('test4', async () => {
        await expect(browser).toHaveUrl('https://webdriver.io')
    })
    it('test5',  () => {})
    it('test6', async () => {
        await expect(browser).toHaveUrl('https://webdriver.io')
    })
})
```

**Comment by erwinheitzman** [comment]
You have confused `bail` and `mochaOpts.bail`. The functionality is working as expected as shown in my examples and as shown in the other issue you created

**Comment by erwinheitzman** [comment]
When you run mocha as a unit test framework you would configure mocha to bail like that. However as can be read here: https://webdriver.io/docs/frameworks#mocha-options not all options are supported because 1. we have our own implementation 2. it makes no sense to support something 3. something isn't supported (yet)

**Comment by christian-bromann** [comment]
@nils-hoyer please have a look at #11340 and let me know if this would resolve this confusion?

**Comment by nils-hoyer** [comment]
@erwinheitzman thanks for clarifying the webdriver.io bail implementation. This was not clear to me from the wdio docs.

**To summarize it for the future googlers:** 
- webdriver.io bail is bailing on spec file level
- mocha is bailing on test (it()/test()) level.
- both implementation (webdriver.io / mocha) works independently
- both implementation can also be combined for bailing fast and stop after first failing test

@erwinheitzman in your comment you define a "test" as "spec file" not as "it block". There might be people who keep only one e2e test per file, where then the analogy will be correct. From my experience more often its common to keep more than one test per file and treat them as a suite e.g. Login Page Tests oder Category Page Tests. Because of this I would recommend to use the wording "spec file" instead of "test" in the documentation to make it clear to user. Some refs to proof the terminology:
- wdio: https://github.com/webdriverio/webdriverio/blob/main/e2e/element.test.ts
- cypress: https://github.com/cypress-io/cypress/blob/develop/system-tests/test/downloads_spec.ts
- playwright: https://github.com/microsoft/playwright/blob/main/tests/playwright-test/reporter-dot.spec.ts

**Comment by nils-hoyer** [comment]
@christian-bromann great improvement, I think this will help a lot :-)
