### ISSUE TITLE
[🐛 Bug]: isAlertOpen not runs with confirm, runs with alert

### ISSUE THREAD

**Issue by agracia-foticos** [webdriverio/webdriverio#11267]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

webdriverio@8.16.16

### Node.js Version

v18.17.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [{
        maxInstances: 10,
        browserName: 'chrome',
            'goog:chromeOptions': {
                args: [
                    '--no-sandbox',
                    '--disable-infobars',
                    '--headless',
                    '--disable-gpu',
                    '--disable-extensions',
                    '--window-size=1920,1080',
                    '--start-maximized',
                    '--disable-dev-shm-usage',
                    '--multi-browser'
            ],
        }
    }]
```

### What happened?

when i check if a confirm is opened, always returns me false, but i see in navigator that the confirm is displayed

### What is your expected behavior?

when i check if a confirm is opened, always returns me false, but i see in navigator that the confirm is displayed

### How to reproduce the bug.

when i check if a confirm is opened, always returns me false, but i see in navigator that the confirm is displayed

### Relevant log output

```typescript
when i check if a confirm is opened, always returns me false, but i see in navigator that the confirm is displayed
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by tamil777selvan** [comment]
Hi @agracia-foticos, I tried to recreate this issue with given capabilities, but I couldn't make the issue happen. Could you please share a working example where we can see this error in action?

**Sample Code Used:**

```javascript
import { remote } from 'webdriverio';

(async () => {
    const browser = await remote({
        capabilities: {
            browserName: 'chrome',
            'goog:chromeOptions': {
                args: [
                    '--no-sandbox',
                    '--disable-infobars',
                    '--headless',
                    '--disable-gpu',
                    '--disable-extensions',
                    '--window-size=1920,1080',
                    '--start-maximized',
                    '--disable-dev-shm-usage',
                    '--multi-browser',
                ],
            },
        },
        logLevel: 'silent',
    });

    try {
        await browser.url('https://demo.automationtesting.in/Alerts.html');
        const alertButton = await browser.$('//a[normalize-space(text())="Alert with OK & Cancel"]');
        await alertButton.click();
        console.log('Alert before --> ', await browser.isAlertOpen());
        const okButton = await browser.$('.btn-primary');
        await okButton.click();
        console.log('Alert after --> ', await browser.isAlertOpen());
    } finally {
        await browser.deleteSession();
    }
})();

```

**Output:**
![Screenshot 2023-09-29 at 4 54 03 PM](https://github.com/webdriverio/webdriverio/assets/49207189/5afbdd68-3388-4499-8ab4-4ec36686a2f7)

**Comment by agracia-foticos** [comment]
i try your example in our systems and test is launched correctly.

I have try my test code with two browser.pause and now test is correct.
![image](https://github.com/webdriverio/webdriverio/assets/77386602/7da61bed-c35d-4df2-8ed5-fbe2f23796a4)

Thanks for the support
