### ISSUE TITLE
[💡 Feature]: Download browser drivers once, in the beginning of the execution

### ISSUE THREAD

**Issue by joao-motork** [webdriverio/webdriverio#11262]
### Is your feature request related to a problem?

I have an automation project with multiple features (I am using "cucumber") and running with multiple parallel instances.
I notice that every time a new feature starts, wdio tries to download the browser driver.
Example:
![image](https://github.com/webdriverio/webdriverio/assets/132624270/d27230ca-a190-44a6-8612-b0cbbf956428)

### Describe the solution you'd like.

No need to try to download the driver every time a new feature starts.
In the beginning of the execution, check the capabilities configured and download the needed browser drivers once.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by erwinheitzman** [comment]
I checked my project and I do not have this same behavior so I think this is rather related to how you run your tests in parallel or related to the Cucumber setup

**Comment by christian-bromann** [comment]
@joao-motork can you provide a minimal reproducible example, maybe in as a Dockerfile?

**Comment by joao-motork** [comment]
Hi @erwinheitzman / @christian-bromann 
In meanwhile, I updated chrome version to 117 and I am no longer able to reproduce the case. I would say to close the ticket and we can discuss it back in the future in case I am able to reproduce it again.

**Comment by erwinheitzman** [comment]
Thank you for letting us know and glad to hear that it's no longer reproducible 👍
