### ISSUE TITLE
[🐛 Bug]: mochaOpts.bail from CLI will be ignored 

### ISSUE THREAD

**Issue by nils-hoyer** [webdriverio/webdriverio#11266]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

18

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
automationProtocol: 'devtools',
services: ['devtools'],
maxInstances: 1,
bail: 1,
framework: 'mocha',
mochaOpts: {
    bail: true,
    timeout: 60000,
},
```

### What happened?

List of supported mocha options for wdio.conf.js
ref: https://webdriver.io/de/docs/frameworks/#mocha-optionen

List of wdio run options für cli e.g. mochaOpts
ref: https://webdriver.io/docs/testrunner/#wdio-run

Assuming the supported mocha options also work as cli parameter. I could not find any other documentation against this assumption.

```
GIVEN set mochaOpts.bail:true in wdio.conf.js
WHEN running wdio run ./wdio.conf.js --mochaOpts.bail false
THEN webdriverio is still bailing after the first test meaning it('testname' () => {}) 
-> Expected webdriverio is not bailing
```

The following workaround seems to work but only accept bail not other or multiple options:
```
GIVEN set mochaOpts.bail:true in wdio.conf.js
WHEN running wdio run ./wdio.conf.js --mochaOpts {bail:false}
THEN webdriverio is not bailing
```

### What is your expected behavior?

From what I can read in the documentation, I would expect to be able to parse all supported mocha options from the CLI.

possible implementation:
`wdio run ./wdio.conf.js --mochaOpts {bail:false,timeout:60000}`
`wdio run ./wdio.conf.js --mochaOpts.bail false --mochaOpts.timeout 60000`

### How to reproduce the bug.

-

### Relevant log output

```typescript
-
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by tamil777selvan** [comment]
Hi @nils-hoyer, I tried to recreate the problem by passing `--mochaOpts.retries` from CLI, but everything worked as it should, and I couldn't make the issue happen. Could you please share a working example where we can see this error in action?

**Retries with 0:**

![Screenshot 2023-09-29 at 4 25 47 PM](https://github.com/webdriverio/webdriverio/assets/49207189/1644f79d-1685-4be6-94ee-4c1476878b76)

**Retries with 1:**

![Screenshot 2023-09-29 at 4 26 05 PM](https://github.com/webdriverio/webdriverio/assets/49207189/57be75fb-a8cf-476b-a066-b9467aa0f186)

**Comment by erwinheitzman** [comment]
I think this got mistaken for #11265 as the bail might indeed not function as expected anymore, I have little time so I could not have a good test going but I do feel like the bail option might have some issues and that the CLI options are fine.

**Comment by erwinheitzman** [comment]
@tamil777selvan can you share some information about your setup? As I am indeed not able to assign anything to the mochaOpts using node 20, Windows and the latest version of the webdriverio packages

**Comment by tamil777selvan** [comment]
Hi @erwinheitzman, I've shared my configuration in this [repository](https://github.com/tamil777selvan/wdio-test), which I've utilized.

To recreate the specific error, please follow these steps:

1. Run the command below to execute the test without retries:

```bash
npm run mocha -- --mochaOpts.retries 0
```
This command will override the value set in `mochaOpts` and intentionally fail the test.

2. Alternatively, you can run the default command, which will pass the test because `retries` is set to 1 in the configuration file:

```bash
npm run mocha
```

**Comment by erwinheitzman** [comment]
@tamil777selvan thanks, I forgot that I tried putting it in the package.json first. works as expected indeed, both in my own project as yours. I also tested the grep option which works too. I think we can close this

**Comment by nils-hoyer** [comment]
thanks @tamil777selvan & @erwinheitzman for diving into this topic.

I did not test all of the available parameters from the list ([link]( https://webdriver.io/de/docs/frameworks/#mocha-optionen)) but I can confirm that mochaOpts.bail can not be overwritten from CLI. So the headline/description might be incorrect now. It seems that only mochaOpts.bail is affected. I will adjust the ticket.

```
GIVEN set mochaOpts.bail=true in wdio.conf.js
RUN wdio run ./wdio.conf.js --mochaOpts.bail false
THEN test 1 and test 2 should run
-> only test 1 run
```

I uploaded a repo for you to reproduce the issue.
[test.zip](https://github.com/webdriverio/webdriverio/files/12783396/test.zip)

**Comment by erwinheitzman** [comment]
Closing due to confusion between `bail` and `mochaOpts.bail`

**Comment by tamil777selvan** [comment]
Hi @erwinheitzman, With latest issue summary description, I experimented with `mochaOpts.bail`, and it appears to have issues (specifically with boolean-type options). Upon closer examination, I noticed that it isn't functioning correctly for other frameworks either. I'm currently working on a fix for this issue. In the meantime, could we consider reopening this?

Thanks @nils-hoyer, for uncovering this bug!

**Comment by erwinheitzman** [comment]
@tamil777selvan webdriverio's bail option should be used instead. We have a line in our docs mentioning that not all options function might function as expected and for the bail option this is because we have a bail option in the root of the config handling this behaviour for all frameworks, not just one

**Comment by erwinheitzman** [comment]
I see you have created a PR but this won't change the behaviour as setting bail to 0 is equal to mochaOpts.bail false and bail <number> is equal to setting it to true but with the added functionality of the number of failures it takes before bailing

**Comment by erwinheitzman** [comment]
In short, there's a reason we provide a bail option in the root that overshadows the framework specific bail option

**Comment by tamil777selvan** [comment]
Hi @erwinheitzman, Please do share your opinion on this as these were my assumptions regarding the bail options,

1. The `bail` option at configuration level, is used to stop the test run if a specified number of files have failed tests within them.

   > If a file has a failed test, subsequent files would be ignored based on the specified bail count.

2. On the other hand, the `bail` option at the Framework level is used to stop the test run if a single test fails.

   > If a single test fails in a spec file, subsequent tests within that file would be ignored.

My assumption was that both of these bail options are supported. However, the fix I provided is to make the `bail` option inside the framework level work as expected when it is passed from command line.

Let's consider a scenario with 4 spec files, each containing 4 tests. Here are the possible outcomes:

With `bail: 2` configured at the configuration level and `bail: false` configured at the framework level:
![Screenshot 2023-10-08 at 8 24 07 AM](https://github.com/webdriverio/webdriverio/assets/49207189/63ff5dc5-b075-4bcf-9236-9e5bd86c6e0f)

With `bail: 2` configured at the configuration level and `bail: true` configured at the framework level:
![Screenshot 2023-10-08 at 8 24 46 AM](https://github.com/webdriverio/webdriverio/assets/49207189/6e258e69-578b-4ac9-9561-d208702188f9)

**Comment by erwinheitzman** [comment]
@tamil777selvan how I see it is that instead of a bug fix you provided a solution for a feature request, let me explain why I think this is. We could have allowed our users to set the bail (root) option from the cli which would fix the same underlying issue but additionally provide more flexibility (as it would allow the user to enable and disable the bail option but next to that also control the number of it). So what you did is great work but since it was never intended to be used like this I believe that if our users want to set/control the bail option, it should be done with that of the wdio root config property instead of the framework specific. So allowing our users to pass this option in the cli instead would be the ideal solution imo 🙂

**Comment by erwinheitzman** [comment]
PS: even though it would not make sense to do so, both options can work alongside each other in the future if we add the bail option ass a possible cli argument/flag
