### ISSUE TITLE
reporter "wdio-spec-reporter" is not installed

### ISSUE THREAD

**Issue by dylanfoster** [webdriverio/webdriverio#1129]
Following the 4.x I get this error while trying to use the `spec` reporter. In addition, this module is not yet published so there is no way to install it to make this work.

**Comment by jurgob** [comment]
I have the same error

**Comment by dcypherthis** [comment]
The spec reporter will not work with v4 and above because of the way it executes tests in parallel.  I'm not sure if this is on the immediate roadmap or not to re-integrate it, but if you want to use spec for now, you will need v3.4 or below

**Comment by christian-bromann** [comment]
Please stick with v3.x until we have updated the website. Thanks!

**Comment by marcodejongh** [comment]
@christian-bromann Updated with what, is there a alternative way of using reporters?
@dcypherthis Will any reporter work? I think this should definitely be on top of the roadmap.

**Comment by christian-bromann** [comment]
@marcodejongh spec reporter is not really on top of the roadmap because it doesn't really provide much value compared to the dot reporter. But we will ship it eventually once other important packages have been updated.

**Comment by jurgob** [comment]
I did a quick custom report you can use in the meanwhile
https://gist.github.com/jurgob/c86920043f0a7c766b79eb63562e15fe

just add save it in a file called **e2eReport.js** and add  in your **wdio.conf.js** file the following lines:

var e2eReport = require('./e2eReport.js');

```
exports.config = {
 ...
 reporters: [e2eReport],
 ...
}
```

**Comment by marcodejongh** [comment]
@christian-bromann But the xunit reporter doesn't work either, is that getting priority?

**Comment by christian-bromann** [comment]
@marcodejongh this reporter: http://webdriver.io/guide/reporters/xunit.html should actually work

**Comment by Baltino** [comment]
Hi @christian-bromann , I forked https://github.com/webdriverio/wdio-spec-reporter, and pointed to that in mi `package.json`. Set the 'spec' reporter and it worked with a test I have (webdriverio ^4.0.5). What's the issue you are referring to?

Note: If anyone wants to try something like this, you should run `npm install` and `grunt build` within the `wdio-spec-reporter/` directory

**Comment by dheerajbhaskar** [comment]
bump for spec reporter

how are test reporters not priority to the webdriver project? I just don't get it.

PS: it's been close to 6 months now

**Comment by christian-bromann** [comment]
> how are test reporters not priority to the webdriver project?

Because the only difference between the dot and spec reporter is that you see the test descriptions instead of the dot. That's it. Failing tests will be displayed the same way like in the dot reporter.

**Comment by dcypherthis** [comment]
I think some people find the spec reporter useful for failures because that test description provides context.  With cucumber reusing step definitions, I often find myself counting dots to determine which scenario failed that step definition.

The value I'm trying to communicate is not just how many failed but in what context, and dot reporting makes that difficult.

**Comment by dheerajbhaskar** [comment]
@christian-bromann I've also commented and opened an issue on the spec reporter repo itself. If dot reporter is npm ready? I can just fork it and add the descriptions, would that get released to npm ?

**Comment by christian-bromann** [comment]
@dheerajbhaskar we already have published a dot reporter

@dcypherthis I see. Well it is one of the next things I will work on

**Comment by object88** [comment]
I see that the [spec reporter](https://github.com/webdriverio/wdio-spec-reporter) is getting some updates -- is it ready to use with the 4.0 release at this point?

**Comment by christian-bromann** [comment]
yes aboslutely

**Comment by Zougi** [comment]
problem is reproducible on wdio-spec-reporter v0.0.3 with webdriverio v4.2.16 (windows 10, nodejs 4.5.0)

**Comment by zmorris** [comment]
I'm still getting this error.

```
$ wdio -v
v4.6.2
```

package.json:

```
  "devDependencies": {
    "wdio-appium-service": "^0.2.3",
    "wdio-cucumber-framework": "^1.1.0",
    "wdio-spec-reporter": "^0.1.4"
  }
```

```
$ wdio config

=========================
WDIO Configuration Helper
=========================

? Where do you want to execute your tests? On my local machine
? Which framework do you want to use? cucumber
? Shall I install the framework adapter for you? Yes
? Where are your feature files located? ./features/**/*.feature
? Where are your step definitions located? ./features/step-definitions
? Which reporter do you want to use?  spec - https://github.com/webdriverio/wdio-spec-reporter
? Shall I install the reporter library for you? Yes
? Do you want to add a service to your test setup?  appium - https://github.com/rhysd/wdio-appium-service
? Shall I install the services for you? Yes
? Level of logging verbosity silent
? In which directory should screenshots gets saved if a command fails? ./errorShots/
? What is the base url? http://localhost

Installing wdio packages:

Packages installed successfully, creating configuration file...

Configuration file was created successfully!
To run your tests, execute:

$ wdio wdio.conf.js

My-Computer:my-tests $ wdio wdio.conf.js
~/.config/yarn/global/node_modules/webdriverio/build/lib/launcher.js:158
                        throw _iteratorError;
                        ^

Error: reporter "wdio-spec-reporter" is not installed. Error: Error: Cannot find module 'wdio-spec-reporter'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Launcher.initReporters (~/.config/yarn/global/node_modules/webdriverio/build/lib/launcher.js:133:40)
    at new Launcher (~/.config/yarn/global/node_modules/webdriverio/build/lib/launcher.js:69:31)
    at Object.<anonymous> (~/.config/yarn/global/node_modules/webdriverio/build/lib/cli.js:424:20)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at Launcher.initReporters (~/.config/yarn/global/node_modules/webdriverio/build/lib/launcher.js:135:35)
    at new Launcher (~/.config/yarn/global/node_modules/webdriverio/build/lib/launcher.js:69:31)
    at Object.<anonymous> (~/.config/yarn/global/node_modules/webdriverio/build/lib/cli.js:424:20)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
```

**Comment by christian-bromann** [comment]
@zmorris if you call `wdio` from the terminal it uses the global installed webdriverio package. If you install your packages like this you need to use the local installed wdio version:

```sh
$ ./node_modules/.bin/wdio wdio.conf.js
```

**Comment by zmorris** [comment]
Wow you are FAST.  I was literally about to post this comment that it might be a local/global node module issue and I was investigating.  Keep up the great work!

**Comment by fabriciows** [comment]
if you are using windows 10, I recommend checking if there is a "." (dot) on the path

Ex:
C: \Users\angelina.jolie\Documents\test\node_modules

REMOVE this dot

C:\Users\angelinajolie\Documents\test\node_modules
