### ISSUE TITLE
Run with chromedriver

### ISSUE THREAD

**Issue by brianmhunt** [webdriverio/webdriverio#113]
I am trying to get `webdriverjs` to work with chromedriver.

The README seems to indicate that a local driver should simply work, however I found no mention of chromedriver in the source.

I would think it would seem to be relatively straightforward to get this working, requiring:
1. Starting (and exiting) chromedriver on demand;
2. Connecting to `localhost:9515` and changing the `startPath` in `lib/utils/RequestHandler.js` to `/` (or, more specifically, making it an option) or add `--url-base=/wd/hub` to the chromedriver options.

Or at least, that's what I have gleaned from `selenium-webdriver` and [a comment on stackoverflow](http://stackoverflow.com/a/18394150/19212).

Then again, I don't quite get chromedriver. It's just a bit surprising that it appears to not be supported by webdriverjs.

Please note that I am unable to use java in our test environment.

**Comment by dristic** [comment]
As a heads up, if you get the `unhandled request` error for all endpoints when hitting chrome driver, you need to start chrome driver on windows without the first slash:

`./chromedriver.exe --url-base=wd/hub --port=PORT`

**Comment by Glavin001** [comment]
I have found the following works:

```
npm install webdriverio chromedriver
```

```javascript
const webdriverio = require('webdriverio');
const chromedriver = require('chromedriver');

const port = 9515;
const args = [
  '--url-base=wd/hub',
  `--port=${port}`
];
chromedriver.start(args);

const options = {
  port,
  desiredCapabilities: {
    browserName: 'chrome'
  }
};
webdriverio
  .remote(options)
  .init()
  .on('error', (e) => console.error(e))
  .once('end', () => {
    console.log('end');
    chromedriver.stop();
  })
  .url('http://www.google.com')
  .getTitle().then(function (title) {
    console.log('Title was: ' + title);
  })
  .end();
```

Hope that helps someone else!

**Comment by kolya-ay** [comment]
@Glavin001, it seems that `once('end', () => chromedriver.stop())` stops chromedriver too early for correct 'chrome' process shutdown (e.g. `chromium` instance is still in memory). How do you handle this? Or maybe it's only my concern..

**Comment by christian-bromann** [comment]
` process.nextTick` is the way to handle this 😉

**Comment by thebarty** [comment]
Guys, I lost some time on this. @Glavin001 Thanks to your code I finally got it working!!!

Any chance of adding a link to this topic in the readme "ChromeDriver"-Paragraph?

**Comment by christian-bromann** [comment]
@thebarty I am not sure if this is a good way to start the driver. If you are about to run build a test suite it might make more sense to use the wdio testrunner instead with the wdio-selenium-standalone-service, then all the magic happens automatically.

**Comment by kolya-ay** [comment]
@christian-bromann I think there are a lot of situations when you don't wan't to build complete test stand downloading jar blob, setting up wdio test runner, etc. In our case we use webdriver.io for simple graphics automation without even touching the testing facilities. So we ended up with this lightweight solution.

I believe this method of launching things is worth mentioning at least in "Standalone" section, which by the way needs more love in docs to my taste.

**Comment by thebarty** [comment]
Hi guys,

I am having problems with this code in production. It works perfect on my macbook, but on the digitalocean droplet (1GB RAM) I am getting the "Error: Couldn't connect to selenium server".

Does anyone have an idea what else I can try?

**Comment by christian-bromann** [comment]
> Does anyone have an idea what else I can try?

You need to start Chromedriver.

**Comment by HFsi** [comment]
Hi people!
I´ve tried to execute "chromedriver --url-base=/wd/hub --port=4321"
but I get:
chromedriver: no se encontró la orden
(Sorry It´s in spanish, It says "the order is not found")
Of course, I´ve downloaded and tried to run from the same directory.
Thanks!

**Comment by christian-bromann** [comment]
it should be `chromedriver --url-base=/wd/hub --port=4444`

**Comment by HFsi** [comment]
I´m still getting the same

**Comment by Lomse** [comment]
Can someone explain the purpose of `--url-base=/wd/hub`? Can seem to find it anywhere. In the [ChromeDriver - WebDriver for Chrome documentation](https://sites.google.com/a/chromium.org/chromedriver/getting-started/getting-started---android), `wd/hub` is mentioned under the FAQ section without any explanation of what that is.

**Comment by dristic** [comment]
wd/hub (I'm guessing "webdriver hub") is the endpoint that webdriver expects to hit when executing its commands. My guess is that the concept comes from Selenium grid's hub model https://github.com/SeleniumHQ/selenium/wiki/Grid2 which is used for scaling your automated testing across many clients
