### ISSUE TITLE
[🐛 Bug]: Saucelabs hangs when trying to add annotation with real devices

### ISSUE THREAD

**Issue by ricardorlg** [webdriverio/webdriverio#11343]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    platformName: "Android",
    "appium:automationName": "UIAutomator2",
    "appium:platformVersion": osVersion,
    "appium:app": `storage:filename=${ANDROID_APK}`,
    "appium:appWaitActivity": "***********",
    "appium:autoGrantPermissions": true,
    "appium:newCommandTimeout": 240,
    "appium:language": process.env.LANGUAGE?.toString().toLowerCase() ?? "en",
    "appium:locale": "us",
    "appium:disableIdLocatorAutocompletion": true,
    "appium:allowInvisibleElements": true,
    "sauce:options": {
      build: buildName,
      phoneOnly: true,
      appiumVersion: "2.0.0",
      cacheId: cacheName,
      resigningEnabled: false,
      allowTouchIdEnroll: false,
      sauceLabsImageInjectionEnabled: false,
    },
  },
```

### What happened?

When the tests start, some of them runs without problem but eventually, when SauceLabs service calls the `sauce:context` to try to add an annotation with the current test, the call never ends which makes Appium kill the session.

Also checking on SauceLabs logs, the request never appears. 

### What is your expected behavior?

I would expect tests to keep running, no hang should happen, and in case of any timeout, it should be caught. 

### How to reproduce the bug.

To reproduce try to run a mobile project on Saucelbas with real devices.

### Relevant log output

```typescript
When the call to execute the sauce:context happens the only log I get is: Request failed with status 500 due to Unknown error while proxying appium request, please contact Sauce Labs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Hey @ricardorlg , thanks for raising an issue.

Unfortunately this appears to be an issue with Sauce Labs. There is not much we can do about it in WebdriverIO. Please reach out to their support for help. Thank you!
