### ISSUE TITLE
[🐛 Bug]: @wdio/cucumber-framework version 7 "mockery is vulnerable to prototype pollution" Critical security vulnerability needs to be fixed

### ISSUE THREAD

**Issue by JordiSAGE** [webdriverio/webdriverio#11359]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.32.3

### Node.js Version

v18.16.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
Not relevant
```

### What happened?

There is a **critical security vulnerability in @wdio/cucumber-framework latest version 7 based 7.32.3** of the package that needs to be fixed. This is causing the "mockery is vulnerable to prototype pollution" critical vulnerability, and **should be addressed ASAP** as @wdio/cucumber-framework version 8 is marked as breaking change and can't be upgraded on a webdriverIO version 7 based project.

### What is your expected behavior?

@wdio/cucumber-framework latest version 7 based 7.32.3 mockery script not vulnerable to prototype pollution.
https://github.com/advisories/GHSA-gmwp-3pwc-3j3g

### How to reproduce the bug.

Run npm audit with @wdio/cucumber-framework latest version 7 based 7.32.3

### Relevant log output

```typescript
mockery  *
Severity: critical
mockery is vulnerable to prototype pollution - https://github.com/advisories/GHSA-gmwp-3pwc-3j3g
fix available via `npm audit fix --force`
Will install @wdio/cucumber-framework@8.16.19, which is a breaking change
node_modules/mockery
  @wdio/cucumber-framework  <=8.15.10
  Depends on vulnerable versions of @cucumber/cucumber
  Depends on vulnerable versions of mockery
  node_modules/@wdio/cucumber-framework
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@JordiSAGE thanks for raising the issue.

At this point I can only recommend to update to v8 where we have resolved the issue (see https://github.com/webdriverio/webdriverio/pull/11010). Feel free to apply the same PR changes to the v7 branch, I am happy to merge and release if tests pass.

**Comment by JordiSAGE** [comment]
Hi @christian-bromann,
It seems that this is just a matter of removing the mockery script from the package.json file and that would be all.
Could you confirm?
https://github.com/webdriverio/webdriverio/pull/11010/files#diff-f748d040ba3547dfc1fb1be9e237e899a96b96ddf5e190da7e62938a75fbe829
Thank you in advance.

**Comment by christian-bromann** [comment]
I don't think it is that easy as it is also being used [here](https://github.com/webdriverio/webdriverio/blob/v7/packages/wdio-cucumber-framework/src/index.ts#L239-L259).

**Comment by JordiSAGE** [comment]
Ok, in that case, I'm going to apply the changes made on version 8 to the equivalent method on v7.

Thanks for your help @christian-bromann

**Comment by JordiSAGE** [comment]
Hi again @christian-bromann,

I've been investigating how to remove the mockery dependency, and it seems that, it can be changed by using the SupportCodeLibraryBuilder from the cucumber library, as they're doing on version 8, but unfortunately, it will require a deep understanding of the project, as there are other properties and methods to change, which I didn't have yet and won't be possible to me to be assumed in the short range (or at least, a period of time in which development is viable), so it would be better if someone with more experience in the project can have a look at it, and provide the corresponding patch for the critical bug.

Thank you in advance.

**Comment by ymouhat** [comment]
Hi @christian-bromann 
Would it be possible to plan a fix for webdriverIO 7 ?  
This issue is reported as Critical with a CVSS score of 9.8

Migrating to webdriverio 8 is in progress but it didn't succeed yet due to other issues blocking us to migrate
e.g  https://github.com/webdriverio/webdriverio/issues/10968

Many thank in advance

**Comment by christian-bromann** [comment]
> Would it be possible to plan a fix for webdriverIO 7 ?

As mentioned before, feel free to raise a PR to the `v7` branch and I am happy to merge and release it.

**Comment by ymouhat** [comment]
HI  @christian-bromann 
Sorry but I am not a developer so I won't be able to do that. I am Just raising the fact this vulnerability is critical and someone should have a look at it .
Thank you in advance.

**Comment by christian-bromann** [comment]
Our recommendation is to update to v8 of WebdriverIO which doesn't have this vulnerability.

**Comment by lidanataborda** [comment]
Hi all @christian-bromann, I am trying to migrate from version 7 to 8, but I still see the issue with mockery, any other dependency that can replace mockery? 
![image](https://github.com/webdriverio/webdriverio/assets/113041672/05c3848e-94d6-442d-b1cc-68c4d906d058)

**Comment by christian-bromann** [comment]
> but I still see the issue with mockery, any other dependency that can replace mockery?

@lidanataborda make sure you remove the v7 dependency. There is no mockery dependency in v8

**Comment by christian-bromann** [comment]
I will go ahead and close this due to inactivity. If anyone likes to pick this up, we are happy to support by answering any questions.

For folks still encountering this: we recommend to upgrade WebdriverIO to v8.
