### ISSUE TITLE
[🐛 Bug]: Allure step() not working in failures.

### ISSUE THREAD

**Issue by deyvisPedrosa** [webdriverio/webdriverio#11351]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

^8.16.20

### Node.js Version

v18.16.0

### Mode

WDIO testrunner

### Which capabilities are you using?

```typescript
{
  browserName: 'chrome',
  browserVersion: 'stable'
}
```

### What happened?

Allure report API method `step()` does not show any error when a line within it fails. For instance, if an assertion inside `step()` fails, it will not be shown in the report, and the test succeeds without noticing that failure. 

### What is your expected behavior?

When an assertion fails, then the test case should fail too.

### How to reproduce the bug.

To reproduce the bug, clone the following public repo [allure.step.bug](https://github.com/deyvisPedrosa/allure.step.bug)

This repo has wdio project with its latest versions. It includes the spec file `test/specs/allureStep.test.js` with two different examples of the described 'bug'. 
To run those scripts, first run `npm install`. After having the repo clone and installing the npm dependencies, hit `npm run wdio`.

The `npm run wdio` command should execute a script that tries to log into a public website and has a wdio assertion inside an allure step() that should fail.

Scripts:
![image](https://github.com/webdriverio/webdriverio/assets/87876246/4588a0b8-7d04-4af7-8eaf-fe74bad879ed)

Allure report:
![image](https://github.com/webdriverio/webdriverio/assets/87876246/df332eeb-ada9-4607-a409-8294322d199d)

### Relevant log output

```typescript
"spec" Reporter:
------------------------------------------------------------------
[chrome 117.0.5938.92 windows #0-0] Running: chrome (v117.0.5938.92) on windows
[chrome 117.0.5938.92 windows #0-0] Session ID: f95ea2bd85df3b8c87ac1f437e5e2625
[chrome 117.0.5938.92 windows #0-0]
[chrome 117.0.5938.92 windows #0-0] » \test\specs\allureStep.test.js
[chrome 117.0.5938.92 windows #0-0] My Login application
[chrome 117.0.5938.92 windows #0-0]    ✓ Should login with valid credentials
[chrome 117.0.5938.92 windows #0-0]    ✓ Should login with valid credentials (Throw error)
[chrome 117.0.5938.92 windows #0-0]
[chrome 117.0.5938.92 windows #0-0] 2 passing (18.1s)


Spec Files:      1 passed, 1 total (100% completed) in 00:00:27

2023-10-04T13:42:00.044Z INFO @wdio/local-runner: Shutting down spawned worker
2023-10-04T13:42:00.308Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-10-04T13:42:00.309Z INFO @wdio/local-runner: shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@epszaw @boris-brtan is the `step` method suppose to propagate the error?

**Comment by epszaw** [comment]
@christian-bromann it does. @deyvisPedrosa which version of the integration do you use?

**Comment by BorisOsipov** [comment]
@deyvisPedrosa Thank you for your detailed bug report! 👍

**Comment by deyvisPedrosa** [comment]
Thank you all! Awesome job 😎

**Comment by weronikazoltaniecka** [comment]
Hi @BorisOsipov should this fix work also if the assertion fails? i.e. await expect(element).toBeDisplayed()?

**Comment by BorisOsipov** [comment]
@weronikazoltaniecka yes

**Comment by weronikazoltaniecka** [comment]
> @weronikazoltaniecka yes

I'm trying to fail step using webdriverio assertion i.e. await expect(element).toBeDisplayed() or jasmine expect(true).toBe(false) and I'm getting passed step result. Only adding 'throw new Error()' works es expected.

**Comment by BorisOsipov** [comment]
@weronikazoltaniecka 

The test:
```
import { step } from '@wdio/allure-reporter';

describe('Suite', () => {
  it('should fail step', async () => {
    await browser.url("https://www.sicpdistilled.com/")
    await step('find something that doesnt exist', async () => {
      await expect($('#foobar')).toBeExisting();
    });
  });
});
```
The report:
![image](https://github.com/webdriverio/webdriverio/assets/6514276/a0eaae77-da83-40a4-8c97-fda7d874df07)

It looks ok.

How can I reproduce your issue? Please share example project

**Comment by weronikazoltaniecka** [comment]
> import { step } from '@wdio/allure-reporter';

Hi,

I've noticed that with Mocha framework, I'm getting the same result as yours, but using Jasmine, the result is different:

<img width="968" alt="jasmine result" src="https://github.com/webdriverio/webdriverio/assets/63448524/95e5a81a-d1e7-4ab6-89d9-647aa6151f48">

sharing repo with my configuration: https://github.com/weronikazoltaniecka/wdio-allure-step-bug


Anyway - this "mocha result" seems to be wrong. Should't it be "failed" instead of "broken"?

**Comment by BorisOsipov** [comment]
@weronikazoltaniecka Thank you for your investigation, it was important.

>Anyway - this "mocha result" seems to be wrong. Should't it be "failed" instead of "broken"?

Yes it must, please file a new issue. It does not appear to be critical as the test status is still valid - Failed.

>but using Jasmine, the result is different:

That seems Jasmine specific thing. Following code still cause failed test, but must pass. Due this we can not determinate `step() ` function status because it always pass even assert fail the test.
```
    it('should fail', async () => {
        await browser.url("https://www.sicpdistilled.com/")
        try {
            await expect($('#foobar')).toBeExisting();
        } catch (e) {
			// catch the error to prevent test fail
        }
    });
```
In your test, `expect()` comes from jasmine, so it causes this behaviour. If you explicitly import expect `import { expect } from `expect-webdriverio'` everything is fine.

**Comment by weronikazoltaniecka** [comment]
@BorisOsipov thanks a million for this tip - I will have to adjust configuration in my project to use it, but I hope it will work.
