### ISSUE TITLE
[🐛 Bug]: Argument of type 'WebdriverIO.Element | Element' is not assignable to parameter of type 'Element'

### ISSUE THREAD

**Issue by bhanuagarwal73** [webdriverio/webdriverio#11350]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.16.20

### Node.js Version

18.17.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [{

        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        maxInstances: 3,
        //
        browserName: runtimeArgs.browserName,
        browserVersion: runtimeArgs.browserVersion,
        acceptInsecureCerts: true,

        "goog:chromeOptions": {
            "args": ["user-agent=gcp-automation-test (Windows NT)",
                `${process.env.HEADLESS === 'true' ? '--headless' : undefined}`,
                `${process.env.HEADLESS === 'true' ? '--disable-dev-shm-usage' : undefined}`,
                `${process.env.HEADLESS === 'true' ? '--no-sandbox' : undefined}`,
                `${process.env.HEADLESS === 'true' ? '--window-size=1920,1080' : undefined}`
            ]
        },

        "bstack:options": runtimeArgs.service === 'browserstack' ? {
            "projectName": "merx-shopify-automation",
            "buildName": `${runtimeArgs.env} - ${runtimeArgs.brand} - ${runtimeArgs.suite} - ${runtimeArgs.browserName}`,
            "os": runtimeArgs.os,
            "osVersion": runtimeArgs.osVersion,
            "deviceName": runtimeArgs.device,
            "networkLogs": true,
            "consoleLogs": "errors",
            "browserVersion": "latest",
            "local": true
        } : {}
    }],
```

### What happened?

Getting for error when calling elements array as below:

Argument of type 'WebdriverIO.Element | Element' is not assignable to parameter of type 'Element'.
  Type 'Element' is missing the following properties from type 'Element': sessionStatus, sessionNew, sessionEnd, sessionSubscribe, and 25 more.ts(2345)

![image](https://github.com/webdriverio/webdriverio/assets/38572421/a843e324-bac7-43d9-bf15-fb943ca8dfb3)
![image](https://github.com/webdriverio/webdriverio/assets/38572421/20a7d7bd-1bdb-4d87-80d2-b8c8c0d25d90)

### What is your expected behavior?

With v7 or when upgraded to v8 last month --> didn't see this issue. I guess need to change something with types file under webdriverio

### How to reproduce the bug.

Just clone this https://github.com/bhanuagarwal73/Git-Merx.git
npm install
navigate & open file src/pageobjects/globalPage.page.ts --> see line 47 & 52

### Relevant log output

```typescript
No issue with run but seeing error in File
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!



We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by erwinheitzman** [comment]
@bhanuagarwal73 can you please share the code of the availableDates function so that we can see what types those use (if you have any assigned that is)?

**Comment by bhanuagarwal73** [comment]
Hey @erwinheitzman 

I shared the git link https://github.com/bhanuagarwal73/Git-Merx.git

Just clone this in IDE & hit npm install & open the file src/pageobjects/globalPage.page.ts

you can navigate from here. All the custom commands written under 
![image](https://github.com/webdriverio/webdriverio/assets/38572421/f5ef57ab-c2c4-4347-be28-6480ffeda36f)

**Comment by erwinheitzman** [comment]
Just to be sure, it should be WebdriverIO.Element right?

**Comment by bhanuagarwal73** [comment]
As per my understanding:

$$ --> should return array of WebdriverIO.Element

and using await PageElements.availableDates[0] --> should return the WebdriverIO.Element

so ya, it should be WebdriverIO.Element

**Comment by bhanuagarwal73** [comment]
@erwinheitzman @christian-bromann 

Its creating issue because of line 73
![image](https://github.com/webdriverio/webdriverio/assets/38572421/df052a90-84db-4075-ba83-0cf6552a1f41)

If I remove the Element from here then working fine but not sure what's the impact of this
![image](https://github.com/webdriverio/webdriverio/assets/38572421/cb0713fb-cebb-47d3-9328-ab19e69931bd)

Somewhere issue with ChainablePromiseElement though its part of or but still throwing error

**Comment by christian-bromann** [comment]
I think we should use `WebdriverIO.Element` everywhere, so removing it makes sense to me.

**Comment by bhanuagarwal73** [comment]
Cool then, will raise PR tomorrow

**Comment by asliyurt** [comment]
is it fixed? Im still getting it..

**Comment by asliyurt** [comment]
<img width="587" alt="Screenshot 2024-01-11 at 22 01 07" src="https://github.com/webdriverio/webdriverio/assets/96418261/6a35ba5b-8c67-4111-bb92-7df882920a5e">
Hello, i m getting a similar issue with error : Argument of type 'WebdriverIO.Element | Element | undefined' is not assignable to parameter of type 'Element'.
  Type 'undefined' is not assignable to type 'Element'.ts(2345) is the one above fixed?

**Comment by bhanuagarwal73** [comment]
Hey @asliyurt  can you please point the version you're using ??

**Comment by asliyurt** [comment]
on v8 =>"webdriverio": "8.24.2"

**Comment by bhanuagarwal73** [comment]
@asliyurt please update to latest one
