### ISSUE TITLE
Basic Example Fails To Log

### ISSUE THREAD

**Issue by ashblue** [webdriverio/webdriverio#1136]
When I run the following snippet on Mac OSX El Captain the URL will open, but it fails to check the title. It just silently fails without logging anything. I've noticed that other tests I've tried to write all seem to silently fail with anything beyond URL navigation. Verbose output simply seems to log everything as being okay. I've been trying for hours to get this working and not too sure what might be wrong here.

Using Grunt Webdriver.io with Selenium Standalone.

```javascript
var webdriverio = require('webdriverio');
var options = {
  desiredCapabilities: {
    browserName: 'firefox'
  }
};

webdriverio
  .remote(options)
  .init()
  .url('http://www.google.com')
  .title(function(err, res) {
    console.log('Title was: ' + res.value);
  })
  .end();
```

**Comment by davidwilde** [comment]
+1

**Comment by davidwilde** [comment]
So I've looked further into the documentation and discovered that I can get this to work with the promises introduced in v3. This code works for me

```
var webdriverio = require('webdriverio');
var options = {
    desiredCapabilities: {
                             browserName: 'firefox'
                         }
};

webdriverio
    .remote(options)
    .init()
    .url('http://www.google.com')
    .getTitle().then(function(titleResult) {
        console.log('Title was: ' + titleResult);
    })
    .end();

```

I will make a pull request for a change to the documentation

**Comment by davidwilde** [comment]
So I discovered that this has already been updated but is not reflected on the website. See https://github.com/webdriverio/webdriverio/blob/master/docs/guide.md

**Comment by christian-bromann** [comment]
@davidwilde yeah we are in the process of updating the website. Sorry for the confusion!
@ashblue please don't use callbacks anymore and make use of promises (see example of @davidwilde)
