### ISSUE TITLE
catching .waitForVisible() if not visible and past timeout

### ISSUE THREAD

**Issue by fooljulian** [webdriverio/webdriverio#1138]
What's the best way for detecting when the element in .waitForVisible() is not visible and past the timeout? 

Should the global error event handler catch this? I'm not seeing it triggered with the example below. I'm using:

selenium-server-standalone-2.47.0.jar
webdriverio:4.0.3

If I run the code below, I see the output:

> Example app listening on port 4000!
> Starting test

But it looks like .on('error') or .then(function(visible)... never get triggered.

If I uncomment the .catch() section, I see:

> Example app listening on port 4000!
> Starting test
> in local catch
> { [Error: element (#DOESNOTEXIST) still not visible after 2000ms]
>   message: 'element (#DOESNOTEXIST) still not visible after 2000ms',
>   type: 'CommandError' }
> visible undefined

So is a local catch() after each .waitForVisible() the right way to do detect this?

Here's the code I'm playing with:

```javascript
var express = require('express');
var app = express();
var webdriverio = require('webdriverio');
var options = {
    desiredCapabilities: {
        browserName: 'chrome'
    }
};

app.get('/', function (req, res) {
  console.log('Starting test');
  webdriverio
    .remote(options)
    .init()
    .on('error', function(e) {
      console.log('in global error handler');
    })
    .url('http://www.google.com')
    .waitForVisible('#DOESNOTEXIST', 2000)
    //.catch(function(e) {
    //  console.log('in local catch');
    //  console.log(e);
    //})
    .then(function(visible) {
      console.log('visible ' + visible);
    })
    .end();

  res.send('Hello World!');
});

app.listen(4000, function () {
  console.log('Example app listening on port 4000!');
});
```

**Comment by christian-bromann** [comment]
> So is a local catch() after each .waitForVisible() the right way to do detect this?

Yes! The error listener is more or less for reporting purposes. I am not sure what you are trying to achieve here. Executing this when accessing the server seems not right. Also all these commands are running async. Check out the example section especially the wdio and pageobject folder for examples how to set up a test suite.

**Comment by fooljulian** [comment]
Thanks!
