### ISSUE TITLE
[🐛 Bug]: No "browserName" defined in capabilities nor hostname or port found!

### ISSUE THREAD

**Issue by amrsa1** [webdriverio/webdriverio#11398]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.17.0

### Node.js Version

18.16.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
DesktopApp =
    [{
      "appium:path": '/wd/hub',
      "appium:hostname": '127.0.0.1',
      "appium:app": "C:\\Program Files (x86)\\Evernote\\Evernote.exe",
      "appium:platformName": "windows",
      "appium:deviceName": "WindowsPC",
      "ms:waitForAppLaunch": '20',
    }]

exports.config = {
    ...config,
    ...{

        specs: [
        '../specs/03.1_WinApp_Suite.ts',
        ],
        capabilities: caps.DesktopApp,
        services: [['appium',{
            args: {
                debugLogSpacing: true,
                sessionOverride: true,
                address: 'localhost',
                port: 4723,
                hostname: "127.0.0.1",
                relaxedSecurity: true
            }}
        ]]
    }

}
```

### What happened?

Unable to execute the test against desktop app due to the following error

```
[0-0] 2023-10-10T20:49:42.391Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2023-10-10T20:49:42.391Z ERROR @wdio/runner: Error: No "browserName" defined in capabilities nor hostname or port found!
[0-0] If you like to run a mobile session with Appium, make sure to set "hostname" and "port" in your WebdriverIO options. If you like to run a local browser session make sure to pick from one of the following browser names: chrome,googlechrome,chromium,chromium-browser,firefox,ff,mozilla,mozilla firefox,edge,microsoftedge,msedge,safari,safari technology preview
[0-0]     at startWebDriver (file:///Users/amrsa/Desktop/wido-ultimate/node_modules/@wdio/utils/build/driver/index.js:41:15)
[0-0]     at Function.newSession (file:///Users/amrsa/Desktop/wido-ultimate/node_modules/webdriver/build/index.js:25:37)
[0-0]     at remote (file:///Users/amrsa/Desktop/wido-ultimate/node_modules/webdriverio/build/index.js:45:35)
2023-10-10T20:49:42.499Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
```

### What is your expected behavior?

Session should not be interrupted due to missing browserName

### How to reproduce the bug.

Upgrade to the latest webdriverio version, execute the test against any desktop App

### Relevant log output

```typescript
amrsa@Amrs-MacBook-Pro wido-ultimate % npx wdio run src/test/config/desktopApp.conf.ts
{
  autoCompileOpts: {
    autoCompile: true,
    tsNodeOpts: { transpileOnly: true, project: './tsconfig.json' }
  },
  capabilities: [
    {
      'appium:path': '/wd/hub',
      'appium:hostname': '127.0.0.1',
      'appium:app': 'C:\\Program Files (x86)\\Evernote\\Evernote.exe',
      'appium:platformName': 'windows',
      'appium:deviceName': 'WindowsPC',
      'ms:waitForAppLaunch': '20'
    }
  ],
  exclude: [],
  maxInstances: 1,
  logLevel: 'trace',
  bail: 0,
  waitforTimeout: 20000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  framework: 'mocha',
  mochaOpts: { ui: 'bdd', timeout: 120000, retries: 0 },
  afterTest: [AsyncFunction: afterTest],
  reporters: [ 'spec', [ 'allure', [Object] ] ],
  specs: [ '../specs/03.1_WinApp_Suite.ts' ],
  services: [ [ 'appium', [Object] ] ]
}

Execution of 1 workers started at 2023-10-10T20:49:40.757Z

2023-10-10T20:49:40.764Z DEBUG @wdio/utils:initialiseServices: initialise service "appium" as NPM package
2023-10-10T20:49:40.769Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-10-10T20:49:40.770Z INFO @wdio/appium-service: Will spawn Appium process: node /Users/amrsa/Desktop/wido-ultimate/node_modules/appium/index.js --base-path / --debug-log-spacing --session-override --address localhost --port 4723 --hostname 127.0.0.1 --relaxed-security
2023-10-10T20:49:41.734Z ERROR @wdio/appium-service: Appium exited before timeout (exit code: 1)


2023-10-10T20:49:41.735Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: Appium exited before timeout (exit code: 1)


    at ChildProcess.<anonymous> (file:///Users/amrsa/Desktop/wido-ultimate/node_modules/@wdio/appium-service/build/launcher.js:140:22)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)

Continue...
2023-10-10T20:49:41.735Z DEBUG @wdio/cli:utils: Finished to run "onPrepare" hook in 965ms
2023-10-10T20:49:41.736Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-10-10T20:49:41.736Z DEBUG @wdio/cli:utils: Finished to run "onWorkerStart" hook in 0ms
2023-10-10T20:49:41.737Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,src/test/config/desktopApp.conf.ts
2023-10-10T20:49:41.738Z DEBUG @wdio/local-runner: Send command run to worker with cid "0-0"
[0-0] 2023-10-10T20:49:42.214Z INFO @wdio/local-runner: Run worker command: run
[0-0] {
[0-0]   autoCompileOpts: {
[0-0]     autoCompile: true,
[0-0]     tsNodeOpts: { transpileOnly: true, project: './tsconfig.json' }
[0-0]   },
[0-0]   capabilities: [
[0-0]     {
[0-0]       'appium:path': '/wd/hub',
[0-0]       'appium:hostname': '127.0.0.1',
[0-0]       'appium:app': 'C:\\Program Files (x86)\\Evernote\\Evernote.exe',
[0-0]       'appium:platformName': 'windows',
[0-0]       'appium:deviceName': 'WindowsPC',
[0-0]       'ms:waitForAppLaunch': '20'
[0-0]     }
[0-0]   ],
[0-0]   exclude: [],
[0-0]   maxInstances: 1,
[0-0]   logLevel: 'trace',
[0-0]   bail: 0,
[0-0]   waitforTimeout: 20000,
[0-0]   connectionRetryTimeout: 90000,
[0-0]   connectionRetryCount: 3,
[0-0]   framework: 'mocha',
[0-0]   mochaOpts: { ui: 'bdd', timeout: 120000, retries: 0 },
[0-0]   afterTest: [AsyncFunction: afterTest],
[0-0]   reporters: [ 'spec', [ 'allure', [Object] ] ],
[0-0]   specs: [ '../specs/03.1_WinApp_Suite.ts' ],
[0-0]   services: [ [ 'appium', [Object] ] ]
[0-0] }
[0-0] 2023-10-10T20:49:42.285Z DEBUG @wdio/runner: init remote session
[0-0] 2023-10-10T20:49:42.287Z DEBUG @wdio/utils:initialiseServices: initialise service "appium" as NPM package
[0-0] RUNNING in windows - file:///src/test/specs/03.1_WinApp_Suite.ts
[0-0] 2023-10-10T20:49:42.391Z DEBUG @wdio/runner: init remote session
[0-0] 2023-10-10T20:49:42.391Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2023-10-10T20:49:42.391Z ERROR @wdio/runner: Error: No "browserName" defined in capabilities nor hostname or port found!
[0-0] If you like to run a mobile session with Appium, make sure to set "hostname" and "port" in your WebdriverIO options. If you like to run a local browser session make sure to pick from one of the following browser names: chrome,googlechrome,chromium,chromium-browser,firefox,ff,mozilla,mozilla firefox,edge,microsoftedge,msedge,safari,safari technology preview
[0-0]     at startWebDriver (file:///Users/amrsa/Desktop/wido-ultimate/node_modules/@wdio/utils/build/driver/index.js:41:15)
[0-0]     at Function.newSession (file:///Users/amrsa/Desktop/wido-ultimate/node_modules/webdriver/build/index.js:25:37)
[0-0]     at remote (file:///Users/amrsa/Desktop/wido-ultimate/node_modules/webdriverio/build/index.js:45:35)
2023-10-10T20:49:42.499Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in windows - file:///src/test/specs/03.1_WinApp_Suite.ts
2023-10-10T20:49:42.500Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-10-10T20:49:42.500Z DEBUG @wdio/cli:utils: Finished to run "onWorkerEnd" hook in 0ms
2023-10-10T20:49:42.500Z INFO @wdio/cli:launcher: Run onComplete hook
2023-10-10T20:49:42.500Z DEBUG @wdio/cli:utils: Finished to run "onComplete" hook in 0ms

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:01 

2023-10-10T20:49:42.501Z INFO @wdio/local-runner: Shutting down spawned worker
2023-10-10T20:49:42.754Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-10-10T20:49:42.755Z INFO @wdio/local-runner: shutting down
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!



We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by tamil777selvan** [comment]
@amrsa1, `appium:path` and `appium:hostname` are not valid Appium capabilities. 
To resolve the issue, please configure `hostname`, `port`, and `path` at the configuration level.

Here's a sample configuration:

```javascript
exports.config = {
    // ... other config options
    hostname: '127.0.0.1',
    port: 4723,
    path: '/',
    capabilities: [
        {
            'appium:appActivity': 'com.wdiodemoapp.MainActivity',
            'appium:appPackage': 'com.wdiodemoapp',
            'appium:platformName': 'Android',
            'appium:deviceName': 'emulator-5554',
            'appium:automationName': 'UiAutomator2',
            'ms:waitForAppLaunch': '20'
        }
    ],
    services: [
        [
            'appium',
            {
                command: 'appium',
                args: {
                    debugLogSpacing: true,
                    sessionOverride: true,
                    address: '127.0.0.1',
                    port: 4723,
                    relaxedSecurity: true
                }
            }
        ]
    ]
};
```

**Comment by LayMui** [comment]
the above config 
services: [
        [
            'appium',
            {
                command: 'appium',
                args: {
                    debugLogSpacing: true,
                    sessionOverride: true,
                    address: '127.0.0.1',
                    port: 4723,
                    relaxedSecurity: true
                }
            }
        ]
    ]

will not work, it will cause ERROR webdriver: RequestError: connect ECONNREFUSED 127.0.0.1:4723

**Comment by christian-bromann** [comment]
@LayMui are you using latest WebdriverIO? Did you scan the WebdriverIO logs for any errors?

**Comment by LayMui** [comment]
Yes. 
"webdriverio": "^8.17.0"

where can I see the webdriverio log?

**Comment by erwinheitzman** [comment]
> the above config services: [ [ 'appium', { command: 'appium', args: { debugLogSpacing: true, sessionOverride: true, address: '127.0.0.1', port: 4723, relaxedSecurity: true } } ] ]
> 
> will not work, it will cause ERROR webdriver: RequestError: connect ECONNREFUSED 127.0.0.1:4723

@LayMui Seems like you forgot to apply the `port`, `hostname` and `path` to the root of the configuration as suggested by @tamil777selvan

**Comment by LayMui** [comment]
yes I did, I put into the common file wdio.conf.ts

baseUrl: "http://localhost",
  //
  // Default timeout for all waitFor* commands.
  waitforTimeout: 2000000,

  **hostname: '127.0.0.1',
  port: 4723,
  path: '/',**
  //
  // Default timeout in milliseconds for request
  // if browser driver or grid doesn't send response
  connectionRetryTimeout: 2000000,

  // Default request retries count
  connectionRetryCount: 30,
  //
  // Test runner services
  // Services take over a specific job you don't want to take care of. They enhance
  // your test setup with almost no effort. Unlike plugins, they don't add new
  // commands. Instead, they hook themselves up into the test process.
  services: [
  ],


  appium: { command: 'appium' },
  // Framework you want to run your specs with.
  // The following are supported: Mocha, Jasmine, and Cucumber
  // see also: https://webdriver.io/docs/frameworks
  //
  // Make sure you have the wdio adapter package for the specific framework installed
  // before running any tests.
  framework: "cucumber",
  //

**Comment by sshankaregowda** [comment]
this file is wdio.conf.js. 

   import { resolve } from 'path';
const pathToDownload = resolve('exportsDir');
import pkg from 'uuid';
const { v4: uuidv4 } = pkg;

export const config= {
    
    //
    // ====================
    // Runner Configuration
    // ====================
    //
    // WebdriverIO allows it to run your tests in arbitrary locations (e.g. locally or
    // on a remote machine).
    // runner: 'local',
    //
    // ==================
    // Specify Test Files
    // ==================
    // Define which test specs should run. The pattern is relative to the directory
    // from which `wdio` was called. Notice that, if you are calling `wdio` from an
    // NPM script (see https://docs.npmjs.com/cli/run-script) then the current working
    // directory is where your package.json resides, so `wdio` will be called from there.
    //
    specs: [   
        './test/specs/**/*.spec.js',
     ],
    suites: {
         //Admin
         CPR_SC :['./test/specs/CPR_SUNSHINECOAST/*.js'],
         CPR_Actions : ['./test/specs/ADMIN/CPR/Actions/DefaultActions/*.spec.js'],
         CPR_DraftActions : ['./test/specs/ADMIN/CPR/Actions/DraftActions/*.spec.js'],
         CPR_NodeLevels : ['./test/specs/ADMIN/CPR/NodeLevels/DefaultNodeLevels/*.spec.js'],
         CPR_InlineActions : ['./test/specs/ADMIN/CPR/Actions/InlineUpdateActions/*.spec.js'],
         CPR_InlineNodeLevels : ['./test/specs/ADMIN/CPR/NodeLevels/InlineUpdateNodeLevels/*.spec.js'],
         HCM_Onboarding: ['./test/specs/ADMIN/HCM_Onboarding/*.spec.js'],
         FCR: ['./test/specs/ADMIN/FCR/*.spec.js'],
         DPR:['./test/specs/ADMIN/DPR/**/*.spec.js'],
         PMC:['./test/specs/ADMIN/PMC/*.spec.js'],
         //ADT:['./test/specs/AUDIT/auditPlanTest.spec.js'],
         ERM:['./test/specs/ADMIN/ERM/*.spec.js'],
         PRF:['./test/specs/ADMIN/PRF/*.spec.js'],
         FORMS:['./test/specs/ADMIN/Forms/*.spec.js'],
         LAM:['./test/specs/ADMIN/LAM/**/*.spec.js' ],
         RCM:['./test/specs/ADMIN/RCM/*.spec.js' ],
         PULSESECURITY: ['./test/specs/ADMIN/PULSESECURITY/*.spec.js'],
         //User
         CPR_SC_U :['./test/specs/CPR_SUNSHINECOAST/*.js'],
         CPR_Actions_U : ['./test/specs/USER/CPR_U/Actions_U/*.spec.js'],
         CPR_NodeLevels_U : ['./test/specs/USER/CPR_U/NodeLevels_U/*.spec.js'],
         HCM_Onboarding_U: ['./test/specs/USER/HCM_Onboarding_U/*.spec.js'],
         //FCR_U: ['./test/specs/USER/FCR_U/*.spec.js'],
         DPR_U:['./test/specs/USER/DPR_U/**/*.spec.js'],
         PMC_U:['./test/specs/USER/PMC_U/*.spec.js'],
         ADT_U:['./test/specs/USER/AUDIT_U/auditPlanTest.spec.js'],
         ERM_U:['./test/specs/USER/ERM_U/*.spec.js'],
         PRF_U:['./test/specs/USER/PRF_U/*.spec.js'],
         //FORMS_U:['./test/specs/USER/Forms_U/*.spec.js'],
         LAM_U:['./test/specs/USER/LAM_U/**/*.spec.js' ],
         RCM_U:['./test/specs/USER/RCM_U/*.spec.js' ],
         PULSESECURITY_U: ['./test/specs/USER/PULSESECURITY_U/*.spec.js'],
         SMOKETESTS: ['./test/specs/Smoketests/**/*.spec.js']
    },
  
    // Patterns to exclude.
    exclude: [
    ],
    //
    // ============
    // Capabilities
    // ============
    // Define your capabilities here. WebdriverIO can run multiple capabilities at the same
    // time. Depending on the number of capabilities, WebdriverIO launches several test
    // sessions. Within your capabilities you can overwrite the spec and exclude options in
    // order to group specific specs to a specific capability.
    //
    // First, you can define how many instances should be started at the same time. Let's
    // say you have 3 different capabilities (Chrome, Firefox, and Safari) and you have
    // set maxInstances to 1; wdio will spawn 3 processes. Therefore, if you have 10 spec
    // files and you set maxInstances to 10, all spec files will get tested at the same time
    // and 30 processes will get spawned. The property handles how many capabilities
    // from the same test should run tests.
    //
    maxInstances: 5,
    //
    // If you have trouble getting all important capabilities together, check out the
    // Sauce Labs platform configurator - a great tool to configure your capabilities:
    // https://docs.saucelabs.com/reference/platforms-configurator
    //
    capabilities: [{
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        maxInstances: 1,
        //
        browserName: 'firefox',
      
    //   browserName: 'chrome',

        // If outputDir is provided WebdriverIO can capture driver session logs
        // it is possible to configure which logTypes to include/exclude.
        // excludeDriverLogs: ['*'], // pass '*' to exclude all driver session logs
        // excludeDriverLogs: ['bugreport', 'server'],
        alwaysMatch: {
            'moz:firefoxOptions': {
               
             // 'goog:chromeOptions': {
     
                 args: ["-headstate"],
                 prefs: {
                     'directory_upgrade': true,
                     'prompt_for_download': false,
                     'browser.helperApps.neverAsk.saveToDisk' :'application/octet-stream,application/vnd.ms-excel,application/pdf',
                     'browser.download.folderList' : 2,
                     'pdfjs.disabled' : true,
                     'browser.download.dir' : pathToDownload,
               }
            }
        }
           
     
    }],
    //
    // ===================
    // Test Configurations
    // ===================
    // Define all options that are relevant for the WebdriverIO instance here
    //
    // Level of logging verbosity: trace | debug | info | warn | error | silent
//   -- logLevel: 'error',
    logLevel: 'error',

    //
    // Set specific log levels per logger
    // loggers:
    // - webdriver, webdriverio
    // - @wdio/applitools-service, @wdio/browserstack-service, @wdio/devtools-service, @wdio/sauce-service
    // - @wdio/mocha-framework, @wdio/jasmine-framework
    // - @wdio/local-runner, @wdio/lambda-runner
    // - @wdio/sumologic-reporter
    // - @wdio/cli, @wdio/config, @wdio/sync, @wdio/utils
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    // logLevels: {
        // webdriver: 'info',
        // '@wdio/applitools-service': 'info'
    // },
    //
    // If you only want to run your tests until a specific amount of tests have failed use
    // bail (default is 0 - don't bail, run all tests).

    // Saves a screenshot to a given path if a command fails.
    //screenshotPath: './Error_test_resources',
    bail: 0,
    //
    // Set a base URL in order to shorten url command calls. If your `url` parameter starts
    // with `/`, the base url gets prepended, not including the path portion of your baseUrl.
    // If your `url` parameter starts without a scheme or `/` (like `some/path`), the base url
    // gets prepended directly.
    baseUrl: 'https://ballina.dev.lgsoftwaresolutions.com.au',
    //
    // Default timeout for all waitFor* commands.
    waitforTimeout: 100000,
    //
    // Default timeout in milliseconds for request
    // if Selenium Grid doesn't send response
    connectionRetryTimeout: 90000,
    //
    // Default request retries count
    connectionRetryCount: 3,
    //
    // Test runner services
    // Services take over a specific job you don't want to take care of. They enhance
    // your test setup with almost no effort. Unlike plugins, they don't add new
    // commands. Instead, they hook themselves up into the test process.
    services: [],
    // hostname: 'localhost',
    // port: 4444,
    //
    // Framework you want to run your specs with.
    // The following are supported: Mocha, Jasmine, and Cucumber
    // see also: https://webdriver.io/docs/frameworks.html
    //
    // Make sure you have the wdio adapter package for the specific framework installed
    // before running any tests.
    framework: 'mocha',
    //
    // The number of times to retry the entire specfile when it fails as a whole
    // specFileRetries: 1,
    //
    // Test reporter for stdout.
    // The only one supported by default is 'dot'
    // see also: https://webdriver.io/docs/dot-reporter.html
	reporters: [
        'spec',
		['junit', {
			outputDir: './reports',
            outputFileFormat: function(options) { 
                return `${options.suite}-${uuidv4()}.log`
            }
        }
		]
	],
    //
    // Options to be passed to Mocha.
    // See the full list at http://mochajs.org/
    mochaOpts: {
        ui: 'bdd',
        timeout: 9999999
       // retries:1

    },
    //
    // =====
    // Hooks
    // =====
    // WebdriverIO provides several hooks you can use to interfere with the test process in order to enhance
    // it and to build services around it. You can either apply a single function or an array of
    // methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
    // resolved to continue.
    /**
     * Gets executed once before all workers get launched.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     */
    // onPrepare: function (config, capabilities) {
    // },
    /**
     * Gets executed just before initialising the webdriver session and test framework. It allows you
     * to manipulate configurations depending on the capability or spec.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     */
    // beforeSession: function (config, capabilities, specs) {
    // },
    /**
     * Gets executed before test execution begins. At this point you can access to all global
     * variables like `browser`. It is the perfect place to define custom commands.
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     */
    before: function (capabilities, specs) {
       return specs
    },
    /**
     * Runs before a WebdriverIO command gets executed.
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     */
    // beforeCommand: function (commandName, args) {
    // },
    
    /**
     * Hook that gets executed before the suite starts
     * @param {Object} suite suite details
     */
    // beforeSuite: function (suite) {
    // },
    /**
     * Function to be executed before a test (in Mocha/Jasmine) or a step (in Cucumber) starts.
     * @param {Object} test test details
     */
    // beforeTest: function (test) {
    // },
    /**
     * Hook that gets executed _before_ a hook within the suite starts (e.g. runs before calling
     * beforeEach in Mocha)
     */
    // beforeHook: function () {
    // },
    /**
     * Hook that gets executed _after_ a hook within the suite starts (e.g. runs after calling
     * afterEach in Mocha)
     */
    // afterHook: function () {
    // },
    /**
     * Function to be executed after a test (in Mocha/Jasmine) or a step (in Cucumber) starts.
     * @param {Object} test test details
     */
    afterTest:  function (test) {
        if(!test.passed){
         browser.takeScreenshot();
        }

    },
    /**
     * Hook that gets executed after the suite has ended
     * @param {Object} suite suite details
     */
    // afterSuite: function (suite) {
    // },
    
    /**
     * Runs after a WebdriverIO command gets executed
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     * @param {Number} result 0 - command success, 1 - command error
     * @param {Object} error error object if any
     */
    // afterCommand: function (commandName, args, result, error) {
    // },
    /**
     * Gets executed after all tests are done. You still have access to all global variables from
     * the test.
     * @param {Number} result 0 - test pass, 1 - test fail
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // after: function (result, capabilities, specs) {
    // },
    /**
     * Gets executed right after terminating the webdriver session.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // afterSession: function (config, capabilities, specs) {
    // },
    /**
     * Gets executed after all workers got shut down and the process is about to exit.
     * @param {Object} exitCode 0 - success, 1 - fail
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {<Object>} results object containing test results
     */
    // onComplete: function(exitCode, config, capabilities, results) {
    // },
    /**
    * Gets executed when a refresh happens.
    * @param {String} oldSessionId session ID of the old session
    * @param {String} newSessionId session ID of the new session
    */
    //onReload: function(oldSessionId, newSessionId) {
    //}
}

Error message is 
Error: No "browserName" defined in capabilities nor hostname or port found!

I have tried to put the host name / port at the root of the config and also in the capabilities but no luck. I migrated wdio to V8 and its causing this error when trying to run the test
