### ISSUE TITLE
Add messaging/disclaimer to existing docs about version compatability until new docs are available.

### ISSUE THREAD

**Issue by dcypherthis** [webdriverio/webdriverio#1139]
Over the last few weeks we've seen a large number of issues raised surrounding problems with webdriverIO that have been due to documentation being out of sync with the latest release.

Since updating the documentation is no quick task, I recommend that for the time being, you add a disclaimer statement to the readme.md file, contribution.md file, npm registry, gitter description, and webdriverIO docs page that indicates the target version of the documentation.

I hope this will serve as a first line of defense for troubleshooting and questions and allow you to separate v3 issues from v4 issues and focus on improvements by reducing some of the friction from damage control.

It might also be good to implement the new PR/Issue templates to help flush out some of these details from new issues or contributions.  Especially since there are many common troubleshooting questions that recur over and over like ***version, reporter, browser/driver, configuration file(s), test files themselves, etc***

You guys have done an amazing job so far handling this and I just want to help you succeed.  Let me know if I can help!

**Comment by christian-bromann** [comment]
Good point. Will try to catch up on the documentation part and release the new website asap. Thanks!
