### ISSUE TITLE
[💡 Feature]: <Update junit-report-builder dependencie>

### ISSUE THREAD

**Issue by Pi-fe** [webdriverio/webdriverio#11402]
### Is your feature request related to a problem?

Hi! I don't know if this is the right Issue type...
I need to use the attribute "property"  for testCase in junit format report (xml).

### Describe the solution you'd like.

In the last update of "[junit-report-builder](https://github.com/davidparsson/junit-report-builder)"  this is implemented.

Could you upgrade the dependecie to the last version (3.1.0)? 

Thank you very much

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
@Pi-fe thanks for filing the issue.

The dependencies is defined with `^3.0.0` which means that all the minor version updates are included. Just re-installed your dependencies with an empty `package-lock` and you should get the `3.1.0` version of [junit-report-builder](https://github.com/davidparsson/junit-report-builder)
