### ISSUE TITLE
[🐛 Bug]: attachments provided in afterEach hook are not displayed in report (wdio 8+mocha+ts+allure)

### ISSUE THREAD

**Issue by anatoly-karpovich** [webdriverio/webdriverio#11404]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

20.3.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
      browserName: "chrome",
    },
```

### What happened?

Attachment provided in afterHook are not displayed in report

  afterEach(() => {
    allure.addAttachment("test log", "successfully opened url", "text/plain");
  });

### What is your expected behavior?

Attached text/plain log even when afterhook is not displayed

### How to reproduce the bug.

https://github.com/anatoly-karpovich/allure-test-rep

### Relevant log output

```typescript
run wdio test from provided repository
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by BorisOsipov** [comment]
@anatoly-karpovich 
 It is as intended. If you want to attach smth in the after\before hook in Mocha, you have to set `disableMochaHooks:true`
