### ISSUE TITLE
[🐛 Bug]: Selectors passed with SJ getter methods, resulting in undefined when appending the [index] to them when using $$

### ISSUE THREAD

**Issue by wbigno** [webdriverio/webdriverio#11405]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v7

### Node.js Version

v14

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  browserName: 'chrome',
  'goog:chromeOptions': {
  args: ['--disable-infobars', '--window-size=1920,1440'],
  prefs: { 'download.default_directory': 'C:\\Users\\Administrator\\Downloads' }
}
```

### What happened?

We call all of our selectors from getter methods within our classes, like this. 

class Component {
get element() { return $$(.'some-class') }
}
export default new Component();

We have always used the $$ to fetch all instances of the elements on a page. 

Then in our test we would do something like 

await component.element[0].click()

In this case we would click on the first index element returned.

Now, all of our tests are failing with an error of undefined. Doing some triage on this issue, we could that the getter is not returning the element back when we append the [index]. Doing some console logs, if we did console.log(await component.element) we would get back all of the elements found not that page without any issues. once we try to append the [index] to the end, we get nothing back. 

If we do something like this
const elm = await component.element
elm[0].click() 

that works fine. but for years we have had no issues with appending the index to the selector until this past week. The only change we did to our entire framework was to add 3 new NPM modules, got, pageant, jsdom.. but these are not even used on the tests that now return undefined. 

### What is your expected behavior?

we should be able to use the $$ and the append an index to the selector when calling a getter method to take action on specific instance of that element on the page.

### How to reproduce the bug.

/** Class of Accordion component*/
class Accordion extends Common {
    /**
     * Get the css selector for element.
     * @return {object} returns selector for element.
     */
    get accordionButton() {
        return $$('.cmp-accordion .cmp-accordion__header');
    }
}
export default new Accordion();

import accordionComponent from '../../../../component/core-content/accordion/nylim/accordion-component';

describe(`${process.env.DOM_BUILD_ENV.toUpperCase()} Accordion Component, Visual Validation On SM`, () => {
    beforeEach(async () => {
        await accordionComponent.openTestAsync();
        await Utilities.changeViewportAsync('SM');
        await browser.pause(10000);
    });

    it.only('should compare accordion component striped bg image with a baseline compare sm viewport', async () => {
        const elm = await accordionComponent.accordionButton;
        console.log(elm[0]);
        console.log(await accordionComponent.accordionButton);

        await accordionComponent.accordionButton[0].click();
        await browser.pause(5000);
        await expects(
            await browser.checkElement(
                await accordionComponent.accordionComponents[0],
                'Accordion Component Striped BG Page-SM',
                {
                    fullPageScrollTimeout: '5000'
                }
            )
        ).to.be.below(0.5);
    });
});

### Relevant log output

```typescript
I see this error now in the logs

require() of ES modules is not supported.
require() of /Users/williambigno/Desktop/Desktop-NYL/nyl-aem-automation/webdriverio/node_modules/query-string/index.js from /Users/williambigno/Desktop/Desktop-NYL/nyl-aem-automation/webdriverio/node_modules/saucelabs/build/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /Users/williambigno/Desktop/Desktop-NYL/nyl-aem-automation/webdriverio/node_modules/query-string/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/williambigno/Desktop/Desktop-NYL/nyl-aem-automation/webdriverio/node_modules/query-string/package.json.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@wbigno can you update the issue title and provide a reproducible example please?

**Comment by wbigno** [comment]
We can close the issue, I updated from 7.17 to the latest 7.33 on all the models, and the ES error that was being thrown on the sauce build file is no longer present and all of the selectors are no passing again. Seems the Sauce module used a query-string/index.js module.. not sure how this error broke how all of the selectors were being passed with js getters but after this minor version update, everything is again running.
