### ISSUE TITLE
[🐛 Bug]: TypeError: logger is not a function

### ISSUE THREAD

**Issue by yach01** [webdriverio/webdriverio#11418]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.17.0

### Node.js Version

18.18.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
        browserName: 'chrome',
        'goog:chromeOptions': {
            args: [
                '--disable-infobars',
                '--log-level=ALL',
                ...!args.getHeadless() ? [] : [
                    '--headless',
                    '--disable-gpu',
                    '--window-size=1920,1080',
                ],
            ],
        },
        acceptInsecureCerts: true,
        maxInstances: args.getMaxBrowserInstances(),
    }
```

### What happened?

I import the logger in my files using following syntex:
import logger from '@wdio/logger';
And use like this
logger('Navigation').info(`Navigating to ${url + componentSwitch}`);
After this getting following error
TypeError: logger is not a function

### What is your expected behavior?

It should log without error

### How to reproduce the bug.

Try to use latest version of webdriverIO

### Relevant log output

```typescript
NA
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment]
const log = logger('unique-identifier-to-recognize')

**Comment by yach01** [comment]
> const log = logger('unique-identifier-to-recognize')

Already try this, but getting same Type error.

**Comment by christian-bromann** [comment]
@yach01 mind providing a minimal reproducible example?
