### ISSUE TITLE
Couldn't load "wdio-jasmine-framework" framework, even though it's installed.

### ISSUE THREAD

**Issue by alexmngn** [webdriverio/webdriverio#1142]
Hi there!
I'm trying to have a very simple test running using Jasmine but I can't make it to work.
I've installed all the node modules needed (I think) to run it, which includes `jasmine-core` and `wdio-jasmine-framework`.

I have `wdio` node module installed globally

I'm running this command:
`wdio wdio.jasmine.conf.js`

I have a `wdio.jasmine.conf.js` at the root level of my project, which is pretty much a copy of this file: https://github.com/webdriverio/webdriverio/blob/master/examples/wdio/wdio.jasmine.conf.js, expect the specs array
```
    specs: [
        './jasmine.spec.js'
    ],
```

And I have the file `jasmine.spec.js` that I'm trying to run at the root level, which is this file: https://github.com/webdriverio/webdriverio/blob/master/examples/wdio/runner-specs/jasmine.spec.js

And I keep getting this error:

> ERROR: Couldn't load "wdio-jasmine-framework" framework. You need to install it with `$ npm install wdio-jasmine-framework`!

I also tried to clone this repo, to run `npm install wdio-jasmine-framework --save-dev` and to run `wdio examples/wdio/wdio.jasmine.conf.js` and I get the same error

I'm running node v4.3.0 and npm v3.6.0

Did I miss something somewhere?
Thanks.

**Comment by alexmngn** [comment]
I was able to fix the issue, `wdio-jasmine-framework` needs to be install globally on your computer.

But with that fixed, I got plenty of different issues.
The first one, looks like the version 4 doesn't like Jasmine. I got the following error:
> if (!runner.specs) throw Error('Cannot generate spec hash for runner with no \'specs\' key');
Already reported here: https://github.com/webdriverio/webdriverio/issues/1116

I tried to downgrade to 3.4.0, and now I have another issue:
> 1) should have the right title - the fancy generator way:
TypeError: Cannot read property 'finally' of undefined

Any idea what's wrong? Is it an issue with Jasmine?

**Comment by patthiel** [comment]
If you're using 3.4.0, you will need to insert yields in your test to make it work.. i've updated your example below, this should work on 3.4.0:

```
describe('webdriver.io page', function() {

    it('should have the right title - the fancy generator way', function* () {
       yield browser.url('/');
        var title = yield browser.getTitle();
        expect(title).toBe('WebdriverIO - Selenium 2.0 javascript bindings for nodejs');
    });

});
```

**Comment by christian-bromann** [comment]
> The first one, looks like the version 4 doesn't like Jasmine. I got the following error:

@alexmngn this is fixed now. As you already figured out you need to install additional wdio packages at the same place where you've installed wdio. If wdio is installed globally with `-g` you need to install the `wdio-jasmine-package` globally as well. I would recommend to have them installed locally though.
