### ISSUE TITLE
webdriverio does not support elementToBeClickable

### ISSUE THREAD

**Issue by emmazhangshine** [webdriverio/webdriverio#1145]
Hi All,

It seems that 'waitForEnabled' does not work the same as Webdriver's elementToBeClickable. Could someone help with an API of it?

**Comment by christian-bromann** [comment]
`waitForEnabled` only checks if the element is [enabled or not](https://www.w3.org/TR/webdriver/#dfn-is-element-enabled). It does not consider if the element is actually clickable. Could you explain your use case a bit more?

**Comment by emmazhangshine** [comment]
Hi Christian,
Thanks for your reply. I am currently automating address search to check availabilities of internet services providers. The use case is after clicking an auto-generated address, a button is shown and it should be clicked to process the automation. However, the button takes about half second to be clickable. I am implementing it with .pause(500) after clicking the auto-generated address. This could be risky if the button is not ready to be clicked after 500ms and 500ms may not be working for all cases. Could you help with this?

**Comment by christian-bromann** [comment]
ok, so `elementToBeClickable` waits until an element is visible and enabled. I don't think it makes much sense to add this to the API since we already have a lot of commands and it is easy to create your own custom command to enable the support for this:

```js
browser.addCommand('elementToBeClickable', function (selector, timeout) {
    return this.waitForVisible(selector, timeout).waitForEnabled(selector, timeout);
});
```
in your spec file just do
```js
browser.elementToBeClickable('#someElem', 5000);
```

**Comment by abhimassive** [comment]
I keep getting this error when I use @christian-bromann 's code

`[chrome #0-0] this.waitForVisible(...).waitForEnabled is not a function
[chrome #0-0] TypeError: this.waitForVisible(...).waitForEnabled is not a function`

**Comment by christian-bromann** [comment]
@abhimassive waitFor commands return boolean values, so you can't chain them

**Comment by iftekhar92** [comment]
@christian-bromann
`browser.elementToBeClickable('#someElem', 5000)`; approach will be usefull but still is not working. Same result I am getting. I am using such as:
1. **Declaration & Definition**
`browser.addCommand('elementToBeClickable', function (selector, timeout = browser.config.waitforTimeout) {
    this.waitForVisible(selector, timeout);
    this.waitForEnabled(selector, timeout);
});`

2. **Usages**
`browser.elementToBeClickable('selector');`
3. **Dependency**
`"webdriverio": "^5.2.4"`
4. **Result**
`this.waitForVisible is not a function`

**Comment by christian-bromann** [comment]
> 4\. this.waitForVisible is not a function

Please see API https://webdriver.io/docs/api/element/waitForDisplayed.html

**Comment by iftekhar92** [comment]
Thanks for replying.
As per mentioned link: I used into existing code such as:

1. `browser.addCommand('elementToBeClickable', function (selector, timeout = browser.config.waitforTimeout) { $(selector).waitForDisplayed(timeout); $(selector).waitForEnabled(timeout); });`
2. `browser.elementToBeClickable('selector');`
3. **Result** Its not working. Please share a running code, if possible.

**Comment by christian-bromann** [comment]
> As per mentioned link: I used into existing code such as:

You used waitForVisible in you first comment

> 3\. It's not working. Please share a sample of code, if possible.

Please share more information about why it is not working, any logs or anything

**Comment by iftekhar92** [comment]
OK,
Just I am sharing log whatever I am getting. Please help me as possible.
`unknown error: Element <div class="op-player op-player__keyboard--inactive op-player__video op-player__full op-captions--detected" tabindex="0" id="interview" data-fullscree
n="false">...</div> is not clickable at point (571, 334). Other element would receive the click: <span class="button-text">...</span>`

**Comment by adamsjoe** [comment]
I'd be interested if we had a waitForClickable - I have an application which has a full screen "blocking" element which can appear if operations take a while.  I am getting lots of errors as click events are being intercepted by this "blocker" (and the element which is to get the click is both enabled and visible.)

**Comment by iftekhar92** [comment]
Hi @emmazhangshine christian-bromann
I am facing a problem to find listed item index in table container.
Scenario such as:
`<table>
    <tbody>
       <tr>
           <td>Item 1</td>
           <td><button aria-label="item-1">Add</td>
      </tr>
       <tr>
           <td>Item 2</td>
           <td><button aria-label="item-2">Add</td>
      </tr>
    </tbody>
</table>`

I want to get Row index of **Item-1**
**Approach**:
`selectRow(name) {
        return $$('tr').findIndex(function (items) {
            return items.$$('td').find(function (item) {
                return item.$(`//button[@aria-label="${name}"]`) === name;
            });
        });
    }`
// Calling method **selectRow** for getting Row index.

const rowIdx = this.selectRow('item-2');

**Result**:
It returns always **0** index. Which is incorrect. It should return **1**
And another thing, ` item.$(`//button[@aria-label="${name}"]`) === name;` does not validate.

Please assist me as possible.

Regards Iftekhar Ahmad

**Comment by osmolyar** [comment]
Seconding this comment https://github.com/webdriverio/webdriverio/issues/1145#issuecomment-496165065 - waitForClickable in this instance is not a combination of Visible and Enabled, but something like javascript's element.isInteractable
