### ISSUE TITLE
[🐛 Bug]: browser runner stales if no it block is found

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#11466]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
any
```

### What happened?

If a browser test has no `it` block the test stales as it never recognises that no test was run.

### What is your expected behavior?

Should fail with: no test executed.

### How to reproduce the bug.

n/a

### Relevant log output

```typescript
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by Pawel1894** [comment]
I checked it and I got no stale.
Result i got when no `it` block - `0 passed, 1 skipped, 1 total (100% completed) in 00:00:06`

**Comment by christian-bromann** [comment]
@Pawel1894 I might haven't described the issue well enough here. Can you try running component tests using `@wdio/browser-runner`?

**Comment by christian-bromann** [comment]
I can't reproduce this anymore, closing.
