### ISSUE TITLE
Couldn't load "wdio-mocha-framework" framework.

### ISSUE THREAD

**Issue by jtn-d** [webdriverio/webdriverio#1146]
$ wdio -v
v4.0.3

$ wdio ...
ERROR: Couldn't load "wdio-mocha-framework" framework. You need to install it with `$ npm install wdio-mocha-framework`!

$ npm install wdio-mocha-framework --save-dev
...

$ wdio ...
ERROR: Couldn't load "wdio-mocha-framework" framework. You need to install it with `$ npm install wdio-mocha-framework`!

**Comment by christian-bromann** [comment]
If you have installed WebdriverIO globally you need to also install all the additional packages globally. I would recommend to install WebdriverIO locally for each project and run the binary like:

```sh
$ ./node_modules/.bin/wdio -v
```

**Comment by Manne010** [comment]
Do **npm install -g wdio-mocha-framework**. This is because the framework might be installed locally, -g will install it globally.it solved my problem

**Comment by palakdesai7** [comment]
@christian-bromann I am facing this issue. I have installed everything locally and tried different solutions but still giving same error. 

Thanks

**Comment by Manne010** [comment]
Once try with -g global installation may it will help u

**Comment by palakdesai7** [comment]
@Manne010 I tried that. It shows updated 1 package [+ wdio-mocha-framework@5.0.0-alpha.7]
But when I run script, it still showing error about not able to find wdio-mocha-framework module :(

**Comment by amrocha** [comment]
@palakdesai7 It's a problem with the latest version, downgrading to 0.6.1 fixed it for me

**Comment by webedims** [comment]
I’m facing same issue. Will try with downgraded mocha

**Comment by GabrielNicolasAvellaneda** [comment]
With wdio v4.13.1 it is having the same issue wtih wdio-mocha-framework.

Version numbers can be confusing here because at this time latest version of **wdio-mocha-framework** is '5.0.0-alpha.7 and latest stable seems to be **0.6.1**.

If you run `npm show wdio-mocha-framework@*` you will see something like the following:
```
     '0.5.13': '2018-03-08T09:09:31.328Z',                                                                                               
     '0.6.1': '2018-06-22T09:14:07.582Z',                                                                                                
     '5.0.0-alpha.2': '2018-06-22T11:24:06.697Z',                                                                                        
     '5.0.0-alpha.3': '2018-06-22T12:12:43.239Z',                                                                                        
     '5.0.0-alpha.4': '2018-06-24T17:27:48.292Z',                                                                                        
     '5.0.0-alpha.5': '2018-06-24T17:49:33.769Z',                                                                                        
     '5.0.0-alpha.6': '2018-06-24T17:57:43.235Z',                                                                                        
     '5.0.0-alpha.7': '2018-06-26T09:00:15.926Z' },    
```
As @amrocha said, it is working fine with 0.6.1, so just running `npm install wdio-moch-framework@0.6.1` to override the installed alpha versions will work.

**Comment by palakdesai7** [comment]
@GabrielNicolasAvellaneda Yes, I got it resolved with manually updating wdio-mocha version to 0.5.13.
I observed this is a new issue as everytime I dpo npm install wdio-mocha-framework '**alpha**' version are created. Even for reporters provided by wdio. 

cc: @christian-bromann

**Comment by webedims** [comment]
Thank you for solution @amrocha. manually updating wdio-mocha version 0.6.1 worked for me.

**Comment by lloydkenneth** [comment]
Thank you very much guys. Got the same problem.

**Comment by blarvin** [comment]
Tried 0.6.1 local (dev), no workee. Installed glabal... Seems to be working. (Have another error now :) )
