### ISSUE TITLE
[🐛 Bug]: wdio-allure-reporter: Inaccurate Reporting and Statistics for Hooks as Test Cases

### ISSUE THREAD

**Issue by lararojasmr** [webdriverio/webdriverio#11473]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### What happened?

The current issue arises from the inability to utilize the fixtures provided by the AllureJS project effectively. Currently, hooks are being reported as tests, leading to several significant problems with the generated reports and statistics.

**Misleading Reports:** The primary issue is that hooks, which are not actual test cases, are being incorrectly reported as tests. This misrepresentation creates confusion and ambiguity in the generated reports.

**Statistics Distortion:** Reporting hooks as tests distorts the statistics related to the number of actual test cases. This affects the accuracy of execution statistics, making it challenging to maintain clear and reliable execution data.

**Execution Uniqueness:** The inaccurate reporting of hooks as tests can lead to difficulties in distinguishing between the execution of actual test cases and the execution of setup/teardown hooks. This can hinder the ability to track the uniqueness of test executions accurately.

**Currently:**
![image](https://github.com/webdriverio/webdriverio/assets/15206513/6befef30-a456-403a-b54d-317e7bed9b6c)

### What is your expected behavior?

The expected behavior, once this issue is resolved, should include the following:

**Accurate Reporting:** Hooks will be correctly identified as fixtures, not as test cases, in the AllureJS project. This will ensure that the generated reports accurately reflect the nature of the executed code and tests.

**Clear Statistics:** With the accurate identification of hooks as fixtures, the statistics related to test cases will no longer be distorted. This should lead to clear and reliable statistics about the execution of actual test cases.

**Distinct Execution Tracking:** The resolution of this issue should enable a clear distinction between the execution of actual test cases and the execution of setup/teardown hooks. This will help in maintaining the uniqueness and reliability of test execution history.

Overall, the expected behavior is that the changes and improvements proposed in this issue will result in a more precise, reliable, and comprehensible reports.

**Example:**
![image](https://github.com/webdriverio/webdriverio/assets/15206513/34efbaa7-e950-4f2d-89a2-316fdf23da4c)

### How to reproduce the bug.

To reproduce this bug, simply create a new project with Allure, add a test case with hooks, and generate an Allure report using the command line.

### Relevant log output

```typescript
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by lararojasmr** [comment]
The changes were discussed in: https://github.com/webdriverio/webdriverio/issues/9928

**Comment by lararojasmr** [comment]
PR: https://github.com/webdriverio/webdriverio/pull/11475

**Comment by RickyMarou** [comment]
We're seeing the same problem in the [adblockplus ui](https://gitlab.com/adblockinc/ext/adblockplus/adblockplusui) repository after upgrading from wdio 7 to 8 and using allure reporter

**Comment by BorisOsipov** [comment]
@RickyMarou What exactly is "the same problem"? Default hook reporting behavior has not changed since webdriverio 4 to 8.

**Comment by RickyMarou** [comment]
After upgrading all our `@wdio` packages from `7.20` to `@latest` a couple weeks ago, we noticed that `beforeAll` hooks are showing up as tests in the allure test result.

Downgrading to `@wdio/allure-reporter` from `8.16.14` to to `8.0.0` fixed the problem for now.

We just noticed this today, i'll report back when we have clearer understanding of the problem on our side.

**Comment by lararojasmr** [comment]
I made a changes in the PR after run 394 test cases with deafferents behaviors to fix bugs.

**Comment by lararojasmr** [comment]
It is possible, i hope to work on that rhis weekend. Why? On 7 Feb 2024, at 13:50, Mykola Prykhodko ***@***.***> wrote:﻿
This issue still happens with allure-reporter v8.30.0
image.png (view on web)

**Comment by lararojasmr** [comment]
Hey, I'm working on it today and hope to finish those changes by the end of the day. Sorry for the delay; I've been very busy at work. 🤓 @BorisOsipov, @christian-bromann, please assign this ticket to me.

**Comment by lararojasmr** [comment]
@christian-bromann this bug was solved in the PRs:

-  https://github.com/webdriverio/webdriverio/pull/12852
- https://github.com/webdriverio/webdriverio/pull/12855
