### ISSUE TITLE
[🐛 Bug]: isAndroid doesn't work in BrowserStack

### ISSUE THREAD

**Issue by Pi-fe** [webdriverio/webdriverio#11474]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.16.20

### Node.js Version

18.0.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [
    {
      "bstack:options": {
        deviceName: "Samsung Galaxy S22 Ultra",
        platformVersion: "12.0",
        platformName: 'Android',
      },
    },
  ],
  commonCapabilities: {
    "bstack:options": {
      projectName: "Test suite",
      buildName: "Test1",
      debug: true,
      networkLogs: true,
    },
  },
```

### What happened?

Hi, I saw https://github.com/webdriverio/webdriverio/issues/2325 this issue, but I have the same problem and 
seems the problem is still there.
In BrowserStack  driver.isAndroid doesn't run and consequentially all my "element id" isn't decleare.

Any solution?

### How to reproduce the bug.

To reproduce the bug just try driver.isAndroid command on browserstack

### Relevant log output

```typescript
The driver otuput is:
`......
[0-2]   isChrome: false,
[0-2]   isFirefox: false,
[0-2]   isMobile: false,
[0-2]   isIOS: false,
[0-2]   isAndroid: false,
[0-2]   isSauce: false,
[0-2]   isBidi: false,
.......`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by bhanuagarwal73** [comment]
You can use curl command from browserstack & match for the input device you give & then get the OS

curl -u "user621:HVGJBw1ZvzuxKSxxvrya" \
https://api.browserstack.com/automate/browsers.json

Let say deviceName: "Samsung Galaxy S20" then check in json response this device name & then get the OS value

**Comment by bhanuagarwal73** [comment]
@christian-bromann 

if you're fine, will create the function as getBrowserStackDeviceOS(device: string) that returns the OS.

Now, same can be called over IsAndroid & isIOS


But if anyone have other approaches then go ahead

**Comment by Pi-fe** [comment]
Ok, I have fork the repo and I'm update isIOS, isAndroid and isMobile, so it's in default function

**Comment by Pi-fe** [comment]
If anyone want to follow I open https://github.com/webdriverio/webdriverio/pull/11509  this PR
