### ISSUE TITLE
[🐛 Bug]: macOS > wdio init > node_modules, package.json, package-lock.json installs in the wrong directory

### ISSUE THREAD

**Issue by sdoigmm** [webdriverio/webdriverio#11485]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.20.0

### Node.js Version

16.15.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [{
    
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        maxInstances: 5,
        //
        browserName: 'chrome',
        acceptInsecureCerts: true
        // If outputDir is provided WebdriverIO can capture driver session logs
        // it is possible to configure which logTypes to include/exclude.
        // excludeDriverLogs: ['*'], // pass '*' to exclude all driver session logs
        // excludeDriverLogs: ['bugreport', 'server'],
    }],
```

### What happened?

- In VS Code, `mkdir wdio-test`
- `cd wdio-test`
- `pwd` -> `/Users/Steve/Documents/Projects/wdio-test/`
- `npx wdio init`
- `y` to `Could not execute "run" due to missing configuration, file "[.js/.ts]" not found! Would you like to create one? (y/N)`
- Receive a message `A project was detected at "/Users/Steven", correct? (Y/n)`
- This is the wrong directory to look in

### What is your expected behavior?

`npx wdio init` to run in the current directory

### How to reproduce the bug.

- In VS Code, `mkdir wdio-test`
- `cd wdio-test`
- `npx wdio init`
- `y` to `Could not execute "run" due to missing configuration, file "[.js/.ts]" not found! Would you like to create one? (y/N)`
- Receive a message `A project was detected at "/Users/Steven", correct? (Y/n)`
- This is the wrong directory to look in

### Relevant log output

```typescript
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> * Receive a message `A project was detected at "/Users/Steven", correct? (Y/n)`

Is there a chance that there is a `package.json` at `/Users/Steven`?

**Comment by sdoigmm** [comment]
> > * Receive a message `A project was detected at "/Users/Steven", correct? (Y/n)`
> 
> Is there a chance that there is a `package.json` at `/Users/Steven`?

Yes, that's right

**Comment by christian-bromann** [comment]
So yes, this behaves by design then. It fines the next `package.json` because it would assume it is the root if your project. You can always say no when getting asked `A project was detected at "/Users/Steven", correct? (Y/n)` and provide a custom path.

**Comment by sdoigmm** [comment]
Ahh got it, thanks
