### ISSUE TITLE
Code not being run

### ISSUE THREAD

**Issue by garrickajo** [webdriverio/webdriverio#1149]
I'm working on a presentation for webdriverio, and I noticed strange things (not) happening. Run the Developer Guide with the latest build (4.0.3), http://webdriver.io/guide.html , and you'll see that console.log never happens. I also tried some assertions, and they just disappear. I try the tests against an older build, and they work (3.2.6).This is failing on Windows 7.

**Comment by garrickajo** [comment]
Assertion seem to get fully snuffed...

.title(function(err, res) {
        console.log('Title was: ' + res.value);
        require('assert').equal(true, false);
    })

...nothing happens

**Comment by christian-bromann** [comment]
@garrickajo sorry we haven't updated the website yet but working hard to get this out asap. Please use v3.x for now. Thanks!
