### ISSUE TITLE
[🐛 Bug]: afterHook is no longer called for Cucumber hooks

### ISSUE THREAD

**Issue by grant-mccarriagher** [webdriverio/webdriverio#11491]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.19.0

### Node.js Version

16.20

### Mode

WDIO Testrunner

### What happened?

Previously, we were using `afterHook` to report some test results to an external test reporting platform. We noticed after updating Webdriverio, that `afterHook` was no longer being called after Cucumber hooks like `Before` and `After`.

The previous version we were using was 8.9.0.

### How to reproduce the bug.

On the latest version of Webdriverio, using a Cucumber suite, set up at least one global `Before` hook. Add an `afterHook` to your WDIO config, like:

```
afterHook: async function (test) {
    console.error("Here's the afterHook");
    console.error(test);
  }
```

### Relevant log output

```typescript
There's no relevant log output.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

This regression was introduced when we updated our Cucumber integration recently. I looked into it and it doesn't seem to be straightforward by just wrapping the exported hook functions from Cucumber.

We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by christian-bromann** [comment]
@tamil777selvan maybe you have an idea?

**Comment by tamil777selvan** [comment]
I believe that when upgrading to the latest version of Cucumber, we might not have included this specific feature due to the changes in the latest version, or we might have overlooked it. However, I'll make an effort to investigate and address it.

**Comment by christian-bromann** [comment]
Thank you! It seems like we didn't test this feature well enough and therefor this regression is not surprising. Any help would be much appreciated!
