### ISSUE TITLE
[🐛 Bug]: 'goog:chromeOptions' --start-maximized not working

### ISSUE THREAD

**Issue by sdoigmm** [webdriverio/webdriverio#11526]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.16.19

### Node.js Version

16.15.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [
        {
            maxInstances: 6,
            browserName: 'chrome',
            'goog:chromeOptions': {
                args: ['--disable-prompt-on-repost','--start-maximized''],
                prefs: {
                    'profile.managed_default_content_settings.popups' : 2,
                    'profile.managed_default_content_settings.notifications' : 2,
                }
            },
            acceptInsecureCerts: true
         },
    ],
```

### What happened?

Setting `--start-maximized` on `goog:chromeOptions`, Chrome does not open maximised.

### What is your expected behavior?

Chrome open full size (1920x1080).

### How to reproduce the bug.

Use the following capabilities:

`    capabilities: [
        {
            browserName: 'chrome',
            'goog:chromeOptions': {
                args: ['--disable-prompt-on-repost','--start-maximized'],
            },
         },
    ],`

Chrome may not open

### Relevant log output

```typescript
Nothing relevant
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment]
The flag works just fine, remove the accidental quote at the end of your args list.
```js
args: ['--disable-prompt-on-repost','--start-maximized''],
```
vs
```js
args: ['--disable-prompt-on-repost','--start-maximized'],
```

**Comment by sdoigmm** [comment]
FTR, I did change to `args: ['--disable-prompt-on-repost','--start-maximized'],` but the issue remains

**Comment by christian-bromann** [comment]
> args: ['--disable-prompt-on-repost','--start-maximized'],

Does `args: ['disable-prompt-on-repost', 'start-maximized'],` make a difference? I remember that I didn't need to add the `-` characters.

**Comment by sdoigmm** [comment]
Hmm, no, same thing happens, windows starts about 2/3 of fullscreen

**Comment by christian-bromann** [comment]
Not sure then. Note that WebdriverIO just passes on these arguments to the browser driver who applies them when booting up the browser. Not sure where things get lost in between.
