### ISSUE TITLE
[🐛 Bug]: doubleclick not working, no errorr

### ISSUE THREAD

**Issue by sdoigmm** [webdriverio/webdriverio#11525]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.16.19

### Node.js Version

20.8.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [
        {
            maxInstances: 6,
            browserName: 'chrome',
            'goog:chromeOptions': {
                args: ['--disable-prompt-on-repost','-window-size=1920,1080'],
                prefs: {
                    'profile.managed_default_content_settings.popups' : 2,
                    'profile.managed_default_content_settings.notifications' : 2,
                }
            },
            acceptInsecureCerts: true
         },
    ],
```

### What happened?

I have a doubleclick command that doesn't run:

`       await(await Studio.searchFormInput).click();
        await browser.keys('Hospitality_Pub_RSL_027');
        await Studio.searchFormInput.addValue([Key.Enter]);
        await(browser.pause(2000));
        await $('canvas.lower-canvas').doubleClick() || console.log('Double clicked');`

The console.log works, but the doubleClick doesn't occur in the web app, no errors occur.

`canvas.lower-canvas` is the correct selector.

Manually double-clicking works fine.

### What is your expected behavior?

That `canvas.lower-canvas` be double-clicked.

### How to reproduce the bug.

Use Chromedriver to open a webpage, select an element and doubleClick it.

await $('<element>').doubleClick();

Nothing happens, the test ultimately fails because a dependent element has not appeared on `canvas.upper-canvas` (which requires the doubleClick on `canvas.lower-canvas`).

### Relevant log output

```typescript
No relevant errors, just an error about an element not being found. This element appears after the doubleClick occurs properly.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> Use Chromedriver to open a webpage, select an element and doubleClick it.

This unfortunately doesn't help to reproduce the issue. Please provide a minimal project that someone could clone and can easily reproduce. Thank you.

**Comment by sdoigmm** [comment]
Thanks, a minimal project didn't contain the bug. I switched to 2 x `click()` events to solve the problem.

**Comment by erwinheitzman** [comment]
@sdoigmm are you okay with closing this as you mentioned it does work with a minimal project? It's quite likely that the clicks happen too fast for your frontend framework to count.

**Comment by sdoigmm** [comment]
Yes thanks @erwinheitzman, thanks for the tip too
