### ISSUE TITLE
[🐛 Bug]: Name selector does not support parentheses in the name

### ISSUE THREAD

**Issue by canon-aris-van-dijk** [webdriverio/webdriverio#11535]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

LTS

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
    browserName: '',
    platformName: 'Windows',
    'appium:automationName': 'Windows',
    'appium:app': 'C:\\Program Files\\Test\\MyApp.exe'
}
```

### What happened?

I am using a name selector on Appium that contains parentheses in the name, e.g. `$("[name='test (Test)']")`. The issue is that when using parentheses, WebdriverIO does not match to a `name` selector strategy but to a `css selector` selector strategy.

### What is your expected behavior?

Any name should match a name selector strategy.

### How to reproduce the bug.

Use a selector that contains parentheses in the name, e.g. `$("[name='test (Test)']")`.

Note: In my setup I use Cucumber to drive the tests and standalone WebDriverIO drivers, so the log below is from Cucumber.

### Relevant log output

```typescript
2023-10-26T06:58:27.801Z INFO webdriver: COMMAND findElement("css selector", "[name='test (Test)']")        
2023-10-26T06:58:27.802Z INFO webdriver: [POST] http://127.0.0.1:4723/session/f9893854-ed2b-4434-badd-a47a63ad5873/element
2023-10-26T06:58:27.802Z INFO webdriver: DATA { using: 'css selector', value: "[name='test (Test)']" }      
2023-10-26T06:58:27.840Z WARN webdriver: Request failed with status 400 due to The selector "[name='test (Test)']" used with strategy "css selector" is invalid! For more information on selectors visit the WebdriverIO docs at: https://webdriver.io/docs/selectors
2023-10-26T06:58:27.841Z INFO webdriver: Retrying 1/3
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by canon-aris-van-dijk** [comment]
@christian-bromann: Added some logging to the issue description. Note: In my setup I use Cucumber to drive the tests and standalone WebDriverIO drivers, so the log is from Cucumber. I think that is not relevant to the issue. 

The cause of this issue is I think in <https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/utils/findStrategy.ts#L107>

**Comment by erwinheitzman** [comment]
@canon-aris-van-dijk the logs contain the selector that is created, this helps us debugging and pinpointing the issue.

**Comment by erwinheitzman** [comment]
I think you are right in your assumption and I see another bug in the regex as `A-z` I believe should be `A-Z`.

We should use the official html specs as a reference for the regex: https://html.spec.whatwg.org/multipage/syntax.html#attributes-2

**Comment by christian-bromann** [comment]
Fixed in https://github.com/webdriverio/webdriverio/pull/11537 .. thanks @aristotelos for picking this up 🙌
