### ISSUE TITLE
[🐛 Bug]: 404 error during requesting Browserstack session (app-automate)

### ISSUE THREAD

**Issue by AndrewKorol14** [webdriverio/webdriverio#11543]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

18.18.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
services: [
	['browserstack', {
		app: 'bs_custom_id',
		browserstackLocal: true,
		testObservability: false,
		opts: {
			localIdentifier: 'some_local_identifier',
		}
	}]
],
capabilities: [{
	projectName: 'some_project_name',
	buildName: 'some_build_name',
	debug: true,
	networkLogs: true,
	device: 'iPhone 14',
	os_version: '16',
}]
```

### What happened?

When I run my tests for native mobile app via BS rests are passed but I receive
`ERROR @wdio/utils:shim: HTTPError: Response code 404 (Not Found)` when @wdio/browserstack-service tries to request BS session url - url contains `/automate`, not `/app-automate`
Issue is not reproduced if in `packages/wdio-browserstack-service/src/service.ts` update `_isAppAutomate` method with `return !!browserDesiredCapabilities['appium:app'] || !!desiredCapabilities['appium:app'] || !!desiredCapabilities['app']` locally
If I try to pass in `capabilities` custom id as `appium:app` I receive error `Error: Invalid or unsupported Webdriver capabilities found...`

### What is your expected behavior?

Error should not appear, browserstack-service should request url with `app-automate`, not with `automate`

### How to reproduce the bug.

Add to default WDIO config next attributes
```js
user: 'some_bs_user',
key: 'some_bs_key',
services: [
	['browserstack', {
		app: 'bs_custom_id',
		browserstackLocal: true,
		testObservability: false,
		opts: {
			localIdentifier: 'some_local_identifier',
		}
	}]
],
capabilities: [{
	projectName: 'some_project_name',
	buildName: 'some_build_name',
	debug: true,
	networkLogs: true,
	device: 'iPhone 14',
	os_version: '16',
}]
```
Add import:
```js
import browserstack from 'browserstack-local'
```
And add to WDIO config next hooks:
```js
onPrepare: async () => {
    console.log('Connecting local');
    return new Promise<void>((resolve, reject) => {
        exports.bsLocal = new browserstack.Local();
        exports.bsLocal.start({
            key: exports.config.key,
            localIdentifier: 'some_local_identifier',
        }, (error: Error) => {
            if (error) return reject(error);
            console.log('Connected. Now testing...');
            resolve();
        });
    });
},

onComplete: async (exitCode, config, capabilities, results) => {
    console.log('Closing local tunnel');
    return new Promise<void>((resolve) => {
        exports.bsLocal.stop(() => {
            console.log('Stopped BrowserStackLocal');
            resolve();
        });
    });
},
```

### Relevant log output

```typescript
ERROR @wdio/utils:shim: HTTPError: Response code 404 (Not Found)
[0-0]     at Request.<anonymous> (file:///Users/My_User/Documents/my-project/node_modules/got/dist/source/as-promise/index.js:86:42)
[0-0]     at Object.onceWrapper (node:events:632:26)
[0-0]     at Request.emit (node:events:529:35)
[0-0]     at Request.emit (node:domain:489:12)
[0-0]     at Request._onResponseBase (file:///Users/My_User/Documents/my-project/node_modules/got/dist/source/core/index.js:727:22)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async Request._onResponse (file:///Users/My_User/Documents/my-project/node_modules/got/dist/source/core/index.js:766:13)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

@kamal-kaur04 @piyush2903 @chetan-p-browserstack any ideas?

We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by kamal-kaur04** [comment]
@christian-bromann Sure, will have a look at this.

**Comment by akanksha1909** [comment]
@christian-bromann @AndrewKorol14 The issue is in the way capabilities are passed, in wdio versions >= v8.10.0(latest version v8.20.5) fix was sent to validate W3C caps, hence v8.10.0 onwards, we should place the caps in vendor specific capabilities (`bstack:options`) and use the W3C format as suggested below.

You can find more information on how to send capabilities by checking out the Browserstack document at this link: [Browserstack Document](https://app-automate.browserstack.com/dashboard/v2/quick-start/setup-browserstack-wdio-service).
```
  services: [
    ['browserstack', {
      app: 'bs://8cf12a3e8ab6ed16df81c3009438f31e42d2df41',
      browserstackLocal: true,
      testObservability: false,
      opts: {
        localIdentifier: 'some_local_identifier',
      }
    }]
  ],
  capabilities: [
    {
      'bstack:options': {
        projectName: 'some_project_name',
	buildName: 'some_build_name',
	debug: true,
	networkLogs: true,
	deviceName: 'iPhone 14',
	osVersion: '16',
      }
    },
  ]
 ```
-  Changes to validate W3C caps are mentioned in release notes of [v8.10.0](https://github.com/webdriverio/webdriverio/releases/tag/v8.10.0). [Code reference](https://github.com/webdriverio/webdriverio/pull/10317/files#diff-e44d73826b5a9f951211dcb5b02f9462e3c489fd708d091f881b78cc86d2f724R294)
- [Code reference](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriver/src/utils.ts#L32-L56) which blocks JSONWP caps.

**Comment by AndrewKorol14** [comment]
@akanksha1909 I will recheck. I thought I've tried such set of capabilities but better to recheck.

**Comment by AndrewKorol14** [comment]
@akanksha1909 I've rechecked and it works as expected... I guess I've made some error previously when I tried to use similar set of capabilities. Sometimes need a fresh look... Many thanks!!!
@christian-bromann I think this bug can be closed - problem is related on correctness of capabilities - I've used incorrect. Thank you for your assistance!

**Comment by christian-bromann** [comment]
@AndrewKorol14 thanks for confirming.
