### ISSUE TITLE
[💡 Feature]: Add scroll behavior to w3c moveTo, click with offset arguments, and dnd methods

### ISSUE THREAD

**Issue by udarrr** [webdriverio/webdriverio#11544]
### Is your feature request related to a problem?

Currently scrolling should be implemented in test level. 
For example if i'd like to move pointer to element with scrolling I should do not so obvious action like scrolling because element can be shifted for some reason.

1. moveTo
```
await (await browser.$("#root div.theme-switcher-menu > button > span")).scrollIntoView()
await browser.pause(animationTimeout)
await (await browser.$("#root div.theme-switcher-menu > button > span")).moveTo()
```

2. w3c click with x,y
```
await (await browser.$("#root div.theme-switcher-menu > button > span")).scrollIntoView()
await browser.pause(animationTimeout)
await (await browser.$("#root div.theme-switcher-menu > button > span")).click({x: 1, y: 1})
```

3. for dragAndDrop it can't be performed because of current implementation 

```
    const browser = getBrowserObject(this);
    return browser.action('pointer')
        .move({ duration: 0, origin, x: 0, y: 0 })
        .down({ button: ACTION_BUTTON })
        .pause(10)
        .move({ duration, origin: targetOrigin, x: targetX, y: targetY })
        .up({ button: ACTION_BUTTON })
        .perform();
```

### Describe the solution you'd like.

I'd like to suggest add scrollIntoView by default to the methods and some arguments for parametrizing the behavior.

1. moveTo

just with arguments by default

`await (await browser.$("#root div.theme-switcher-menu > button > span")).moveTo()`

and with preset arguments

`await (await browser.$("#root div.theme-switcher-menu > button > span")).moveTo({x: 10, y: 10, scrollOptions: options})`

2. the same for w3c clicking with x,y
3. and maybe for dnd if it possible to iterate with the same 'pointer' after using 'wheel'

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
@udarrr thanks for raising the issue.

Do you have some examples where this additional `moveTo` step benefits the user?

Note that an element that is not in viewport might not be able to be scrolled into view. Relying on the WebDriver protocol to do its thing and move the element into the viewport is usually a good step. Also be aware that adding these commands can increase test execution time when WebDriver endpoints are hosted in the cloud.

**Comment by udarrr** [comment]
> Do you have some examples where this additional `moveTo` step benefits the user?

Yes it's really helpful with different resolution of screen. Resolution could be slightly deferent in some platform even with wdio tests in headless mode there is resolution 1024x768 by default and without scrolling the element is going to be out of bound although locally it's worked perfectly.

> Note that an element that is not in viewport might not be able to be scrolled into view. Relying on the WebDriver protocol to do its thing and move the element into the viewport is usually a good step. 

Generally that's why i've raised the issue. It's quite annoying add scrollIntoView each time when i'd like to do moveTo. At the moment when click have the behavior by default. 

>Also be aware that adding these commands can increase test execution time when WebDriver endpoints are hosted in the cloud. 

Yes some extra time is necessary for that but i believe it much better then failed test cases. Moreover we can replace timeout to simple a check like waiting for is element into view or not after scrolling it reduces time of waiting after scrolling.

**Comment by erwinheitzman** [comment]
I feel like this is a broader topic as we have discussed this for other commands before as well (like the click command). I am in favor of automatically trying to scroll to an element. I am also in favor that when an element is not interactive, we auto wait until interactive or we timeout. I feel like these kind of automatic behaviours really help our users.

**Comment by christian-bromann** [comment]
These arguments make sense. Thanks for all your input, it helped me to understand this much better now. Let's move forward with this @udarrr.

**Comment by erwinheitzman** [comment]
Thank you for the contribution @udarrr sadly I was not in time to re-review your changes before the merge so I'll share my feedback here.

As a next step I would like to apply the following changes in v9:
1. make scrolling to the middle instead of to the top the default behavior (for both the moveTo and scrollIntoView command, this allows us to remove some fallbacks)
2. automatically scroll to an element when trying to interact with an element that is currently not in the viewport
3. if the element is within the viewport but not interactable, wait for the element to become interactable (enabled)

I feel like these three steps together will remove a ton of boilerplate code on our user's end (no longer having to manually scroll) while also preventing a lot of errors for elements like a submit button that changes from disabled to enabled after entering data into a form. This last example also removes a lot of boilerplate code because a lot of users for example use waitForClickable whenever something is flaky.

Is this something you all align with?

**Comment by christian-bromann** [comment]
> 2\. automatically scroll to an element when trying to interact with an element that is currently not in the viewport

This is currently the default behavior already. It is defined by the WebDriver spec to do that.

> 3\. if the element is within the viewport but not interactable, wait for the element to become interactable (enabled)

This might help in some cases but could cause issues in others. Like when an element is actually not interactable. Rather than having the test wait for many seconds I would prefer to fail immediately with some concrete information. I think it is more valuable if we can improve the error message and determine why the element is not intractable.

**Comment by udarrr** [comment]
> Thank you for the contribution @udarrr sadly I was not in time to re-review your changes before the merge so I'll share my feedback here.
> 
> As a next step I would like to apply the following changes in v9:
> 
> 1. make scrolling to the middle instead of to the top the default behavior (for both the moveTo and scrollIntoView command, this allows us to remove some fallbacks)
> 2. automatically scroll to an element when trying to interact with an element that is currently not in the viewport
> 3. if the element is within the viewport but not interactable, wait for the element to become interactable (enabled)
> 
> I feel like these three steps together will remove a ton of boilerplate code on our user's end (no longer having to manually scroll) while also preventing a lot of errors for elements like a submit button that changes from disabled to enabled after entering data into a form. This last example also removes a lot of boilerplate code because a lot of users for example use waitForClickable whenever something is flaky.
> 
> Is this something you all align with?

**Comment by christian-bromann** [comment]
@udarrr with https://github.com/webdriverio/webdriverio/pull/11565 merged, what else needs to be done that is within scope of this issue?

**Comment by erwinheitzman** [comment]
> > 2. automatically scroll to an element when trying to interact with an element that is currently not in the viewport
> 
> This is currently the default behavior already. It is defined by the WebDriver spec to do that.
> 
> > 3. if the element is within the viewport but not interactable, wait for the element to become interactable (enabled)
> 
> This might help in some cases but could cause issues in others. Like when an element is actually not interactable. Rather than having the test wait for many seconds I would prefer to fail immediately with some concrete information. I think it is more valuable if we can improve the error message and determine why the element is not intractable.

If we can explain why an element is not interactable that would also work indeed I guess.

I think we can close #7311 #8628 and #11544 together with this issue when this one is considered done.

Currently the situation is
```js
elem.click() // does not scroll
elem.click({}) // does scroll
```
this is why #8628 is related. mind if I update the click command to automatically scroll?

Regarding the scrolling default @udarrr I understand that nearest sounds nice in theory but if there are elements that have a fixed position, it will be seen as visible/in view while it is not clickable. Therefor I feel it is better to scroll to the center by default to prevent such issues without having to worry about it.

**Comment by erwinheitzman** [comment]
update: just tested the click and the scroll already seems to work (only talking about the normal scroll I mentioned in the message above) so I think we can already close #8628 perhaps

**Comment by erwinheitzman** [comment]
Just tested the new moveTo and with the current implementation I already ran into an issue.
We have this code (which I warned about before):
```js
    await this.scrollIntoView({ block: 'nearest', inline: 'nearest', behavior: 'instant' });
    if (!(await isIntoView())) {
        await this.scrollIntoView({ block: 'center', inline: 'center', behavior: 'instant' });
    }
```
now the element is scrolled to the bottom if the element is further down the page, you can test this using this html:
```html
  <div style="width: 200px; height: 10000px">
    <button
      style="
        width: 46px;
        height: 46px;
        position: absolute;
        top: 9000px;
        background-color: red;
      "
    ></button>
  </div>
```
If you now do this is will fail:
```js
await $("button").moveTo({ xOffset: 1, yOffset: 40 }); // error out of bounds (cause you are at the edge of the viewport)
```

Hence I again like to stress the importance of taking things like this into account.

I think we can do a few things:
1. calculate the actual location (might mean we have to refactor the moveTo command back to what it was)
2. scroll it to the center instead
3. apply it to other commands like the click command as it has the same issue

So as a recap, I think that we should not have changed the moveTo but rather click command to take all of this into account.

**Comment by erwinheitzman** [comment]
A similar issue can be observed when adding in a fixed position element like a footer:
```html
    <div style="width: 200px; height: 10000px">
    <div style="width: 100%; height: 80px; position: fixed; bottom: 0; left: 0; background-color: blue;"><div>  
    <button
      style="
        width: 46px;
        height: 46px;
        position: absolute;
        top: 9000px;
        background-color: red;
      "
    ></button>
  </div>
```
```js
await $("button").moveTo(); // error out of bounds cause of fixed element overlay
```

**Comment by erwinheitzman** [comment]
a similar issue can be observed when using a fixed position element:
 ```html
   <div style="width: 200px; height: 10000px">
    <button
      style="
        width: 46px;
        height: 46px;
        position: absolute;
        top: 9000px;
        background-color: red;
      "
    ></button>
    <div style="width: 100%; height: 80px; position: fixed; bottom: 0; left: 0; background-color: blue;"><div>  
  </div>
 ```
 ```js
 await $("button").moveTo(); // error out of bounds due to element underneath the fixed element
 ```
 This also applies to the click command

**Comment by udarrr** [comment]
From my perspective it's working as expected

Let me explain
In the case

```
  <div style="width: 200px; height: 10000px">
    <button
      style="
        width: 46px;
        height: 46px;
        position: absolute;
        top: 9000px;
        background-color: red;
      "
    ></button>
  </div>
```
here 
```await $("button").moveTo({ xOffset: 1, yOffset: 40 }); // error out of bounds (cause you are at the edge of the viewport)```
We're moving pointer more then height of the element below of viewport because webdriver shift offset regarding center of the element and height/2 + 40  = 63 if we'd like to be inside of the element our offset couldn't be more then height/2. Moving to center just maybe give us a trick to move a pointer to outside of element but instead of that we will lost 'nearest' behavior

Using {block: "nearest"}, the element:
is aligned at the top of its ancestor if you're currently below it.
is aligned at the bottom of its ancestor if you're currently above it.
**stays put, if it's already in view.**

If we're going to scroll it to center it'll be triggered each time when will be calling moveTo method. Why should we move it to center if it's shifted slightly regarding center?

Even more, scroll with calculation can't work in iframe, because we should be aware about dimensions of iframe for calculations. That's why it's been throwing to workaround with web scrollIntoView each time.

Unfortunately I wasn't able to reproduce the bug
```
  <div style="width: 200px; height: 10000px">
   <button
     style="
       width: 46px;
       height: 46px;
       position: absolute;
       top: 9000px;
       background-color: red;
     "
   ></button>
   <div style="width: 100%; height: 80px; position: fixed; bottom: 0; left: 0; background-color: blue;"><div>  
 </div>
```
It was working as expected without errors when i tested it.

**Comment by udarrr** [comment]
> @udarrr with #11565 merged, what else needs to be done that is within scope of this issue?

I'd like to suggest support scrolling for clicking with arguments. It's the last for the task.

```
elem.click({ xOffset: 1, yOffset: 1 })
```

**Comment by christian-bromann** [comment]
@udarrr sounds good to me!

**Comment by udarrr** [comment]
@erwinheitzman Just a little bit confused regarding pard of code with calculations in scrollIntoView.Why are we using 'wheel' action?

**Comment by udarrr** [comment]
I'd like to suggest consider the tool https://github.com/scroll-into-view/compute-scroll-into-view
This is polyfil scrollIntoView but with implementation of proposal to js 'if-needed' for all type of scrolling

**Comment by udarrr** [comment]
@erwinheitzman I am a slightly confused regarding calculations in scrollIntoView, what's the reason or idea of using the calculations with 'wheel' ?

**Comment by udarrr** [comment]
@christian-bromann @erwinheitzman I have an update. I don't know what is going on either w3c protocol has been changed in the latest version of drivers or i was able to test it with origin but looks like browser.action can perform moving and scrolling automatically when element has been set as origin with 'nearest' behavior by default, that's why not necessary to add something to click with arguments.
I'd just suggest to implement moveTo with fallback

```
export async function moveTo (
    this: WebdriverIO.Element,
    { xOffset, yOffset }: MoveToOptions = {},
) {
    if (!this.isW3C) {
        return this.moveToElement(this.elementId, xOffset, yOffset)
    }
    /**
     * W3C way of handle the mouse move actions
     */
    const browser = getBrowserObject(this)
    const scrollIntoViewMoveTo = async (options?: ScrollIntoViewOptions | boolean)=>  {
        return browser.execute((elem: HTMLElement, options: ScrollIntoViewOptions | boolean) => {
            elem.scrollIntoView(options)
        }, {
            [ELEMENT_KEY]: this.elementId,
            ELEMENT: this.elementId, // jsonwp compatible
        } as any as HTMLElement, options as boolean | ScrollIntoViewOptions)
    }
    const moveToNested = async ( xOffset?: number, yOffset?: number ) => {
        return  await browser.action('pointer', { parameters: { pointerType: 'mouse' } })
            .move({ origin: this, x: xOffset ? xOffset : 0, y: yOffset ? yOffset : 0 })
            .perform()
    }
    try {
        return await moveToNested(xOffset, yOffset)
    } catch {
        await scrollIntoViewMoveTo({ block: 'center', inline: 'center', behavior: 'auto' })
        return await moveToNested(xOffset, yOffset)
    }
}
```

**Comment by christian-bromann** [comment]
Seems reasonable to me. Let's add some comments in there to ensure we know later why we did this.

**Comment by erwinheitzman** [comment]
That looks good with the exception that `behavior: 'auto'` isn't a valid option for the command. I noticed you already used it previously and it is a valid native scrollIntoView option but not for the wdio command. Oh and the following `.move({ origin: this, x: xOffset ? xOffset : 0, y: yOffset ? yOffset : 0 })` can be simplified to `.move({ origin: this, x: xOffset || 0, y: yOffset || 0 })`.

Regarding the x/y offsets, if we want to scope the offsets to only the size of the element I think it will be very good to add a check for this like so for both commands:
```js
    const { width, height } = await getElementRect(this)
    if (xOffset > width) {
      throw new Error('xOffset cannot be greater than the element's width')
    }
    if (yOffset > height) {
      throw new Error('yOffset cannot be greater than the element's height')
    }
```

**Comment by taninnazar** [comment]
Hi @christian-bromann @erwinheitzman @udarrr,
Thanks for your improvements. 
But for now, how should I proceed if I would like to click outside the element? Previously I was performing a click on element with xOffset and yOffset which were greater than the element's size. Same with unhovering the element.

**Comment by erwinheitzman** [comment]
@taninnazar for now you are able to use the action command to click on a specific location but  your usecase is absolutely valid and should be supported in my opinion as I have shared my concerns about this previously as well

**Comment by christian-bromann** [comment]
> Same with unhovering the element.

Correct me if I am wrong but you could also just click on a different element, e.g. `$('body').click({x: 1, y: 1})` to have the same effect right? This seems to be a much more explicit approach as you now have a target and don't just click randomly above the element which could cause a side effect.

**Comment by taninnazar** [comment]
@christian-bromann As for me, click on some different element looks like a workaround. Test becomes dependent on one more element. So, if I would like to unhover/move the mouse out of the element - I'm just locating this element and moving the mouse out using "moveTo" with x and y offset.
In other words, with this update, you are cutting some useful functional from the framework. Would be nice to get it back

**Comment by christian-bromann** [comment]
What would you all suggest be the best approach:

- remove the error being thrown
- add a flag to allow clicking outside of the element

Any feedback would be appreciated.

**Comment by taninnazar** [comment]
Hello @christian-bromann , 
Are you going to implement solutions from your last message here?
As for me, both solutions are fine, but I need at least something to be able to click outside the elements as previously. 
Because of that I can't update to the last versions of WDIO.
Thanks

**Comment by christian-bromann** [comment]
@taninnazar mind raising a new issue for this?
