### ISSUE TITLE
Spec reporter doesn't work when set in the conf file.

### ISSUE THREAD

**Issue by alexmngn** [webdriverio/webdriverio#1154]
I'm trying to use the `spec` reporter, but I can't make it to work when I set it up on my conf file

*wdio.jasmine.conf.js*
```
exports.config = {
   ...
   reporters: ['spec'],
}
```

Although, it works fine when I run the command `wdio wdio.jasmine.conf.js  -r spec`

Using webdriverio 3.4.0

**Comment by dmfranko** [comment]
If you're still using 3.x you want reporter: 'spec'.  4.x allows for an array of reporters.

**Comment by christian-bromann** [comment]
@alexmngn it seems that your config is for v4.x. Please use this example config as reference: https://github.com/webdriverio/webdriverio/blob/v3.4.1/examples/wdio.conf.js

**Comment by alexmngn** [comment]
I am using 3.4.0 like I said on the original ticket.
