### ISSUE TITLE
Selenium session should not persist between tests cases using wdio

### ISSUE THREAD

**Issue by sylar28** [webdriverio/webdriverio#1155]
Using **mocha and the wdio test runner**, it seems that a single selenium session persist between all test cases within a specific spec file. Is this intended? Ideally, each test case would initialize a new session to keep the tests isolated from the affects of others.

I couldn't find anything in the documentation, nor any existing issues regarding this, so its possible I'm missing something obvious to make this work (I apologize if this is the case).

As an example, I am expecting a new selenium session for each `it` block below:
```
...
describe("a page", function() {
  it("should do something", function() {
  });

  it("should do this other thing", function() {
  });
});

it("should do another thing", function() {
});
...
```

**Comment by christian-bromann** [comment]
> Is this intended?

Yes! In v3 each capability will create one Selenium session. In v4 each spec file per capability will create one Selenium session.
