### ISSUE TITLE
Looking for working example for addLocatorStrategy in .ts file extension[📖 Docs]: <title>

### ISSUE THREAD

**Issue by skumar5a9** [webdriverio/webdriverio#11566]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Missing documentation

### Description of the improvement / report

Hi Team,

Please provide working example for addLocatorStrategy in .ts file extension. Example which is currently provided in web driver io documentation is not working(https://webdriver.io/docs/api/browser/custom$/)

Let me know if you require more details from my end.

Regards,
Kumar Somisetti

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by skumar5a9** [comment]
it('should fetch the project title', async () => {
    await browser.url('https://webdriver.io')
    browser.addLocatorStrategy('myStrat', (selector) => {
        return document.querySelectorAll(selector)
    })

    const projectTitle = await browser.custom$('myStrat', '.projectTitle')

    console.log(await projectTitle.getText());
})

I am running  test.ts file on above use case is throwing below error

Error: locator strategy script must return an element

Please assist me on this

**Comment by christian-bromann** [comment]
Thanks for reporting!



We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!
