### ISSUE TITLE
[🐛 Bug]: Few options are not present in the `runnerStats` in `onRunnerStart` hook ~ WDIOReporter

### ISSUE THREAD

**Issue by kamal-kaur04** [webdriverio/webdriverio#11561]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.19.0

### Node.js Version

latest

### Mode

WDIO Testrunner

### What happened?

We use to send test status extending WDIO Reporter. We had some checks as per framework value inside the [config](https://github.com/webdriverio/webdriverio/blob/712767b49161e483a51eb12cf44074acd29e018d/packages/wdio-browserstack-service/src/reporter.ts#L42). Now, it seems that the value isn't in the config object anymore. Possibly because we have removed framework and other few parameters from **WDIO_DEFAULTS** in this [PR](https://github.com/webdriverio/webdriverio/pull/11441) that is creating some test reporting failures.

Note that this is happening in few tests. Also, it's broken since WebdriverIO `v8.19.0`

### What is your expected behavior?

runnerStats should contain `runnerStats.config.framework` inside `onRunnerStart` hook in all the cases.

### How to reproduce the bug.

N/A

### Relevant log output

```typescript
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!



We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by christian-bromann** [comment]
Fixed by https://github.com/webdriverio/webdriverio/pull/11589
