### ISSUE TITLE
waitUntil doesn't raise error after reaching timeout period

### ISSUE THREAD

**Issue by eyalzek** [webdriverio/webdriverio#1156]
Using v3 and the following example:
https://gist.github.com/eyalzek/a97f11c9726f19cbbc10

Expected behavior: waitUntil will reach the timeout period of 10 seconds and will then fail or throw an error.

Actual behavior: execution of the test continues as normal, the 'it' is successful. (console output available in gist).

**Comment by christian-bromann** [comment]
@eyalzek have you been able to reproduce this in v4? I probably won't do any releases for v3 anymore.

**Comment by eyalzek** [comment]
Actually I can't manage to run v4 with mocha standalone, it hangs

**Comment by christian-bromann** [comment]
Can't reproduce this in v4 anymore:

```js
describe('a', function() {
    it('b', function() {
        browser.url('http://google.com')
        browser.waitUntil(function() {
            return Promise.resolve(false)
        }, 1000)
    });
});
```

fails propery with 
```
0 passing (7.50s)
1 failing

1) b:
Promise was rejected with the following reason: timeout
```
