### ISSUE TITLE
Topic "Selenium-Standalone-Service" is deprecated or just documentation is broken?

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#11572]
### Discussed in https://github.com/webdriverio/webdriverio/discussions/11568

<div type='discussions-op-text'>

<sup>Originally posted by **danielsvelicenko** November  1, 2023</sup>
I remember that there was some documentation on Selenium Standalone service for WebdriverIO. It's bit confusing, that we can search for it, but then display that can't find anything.

# Steps:
1. Search for the "Selenium Standalone Service"
![image](https://github.com/webdriverio/webdriverio/assets/81615057/2702447f-2e39-4518-b58a-b0cec4654f7b)
2. Select any sub-topic that goes under it

# Actual results:
![image](https://github.com/webdriverio/webdriverio/assets/81615057/152fb94f-2f78-4a49-b6cc-59a64b5a3cb4)
</div>

**Comment by udarrr** [comment]
Maybe not related with the issue, but last version the package don't have compiled folder on npm, there are just some files like package.json and so on https://www.npmjs.com/package/@wdio/selenium-standalone-service

**Comment by christian-bromann** [comment]
I removed the page and re-triggered the crawler so it should also get removed from the Algolia index. I will go ahead and close this. Let me know if you see any other weirdness.
