### ISSUE TITLE
[🐛 Bug]: JSONWP methods are visible in Browser and Element types when it's W3C by default

### ISSUE THREAD

**Issue by udarrr** [webdriverio/webdriverio#11588]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.21.0

### Node.js Version

18

### Mode

WDIO Testrunner

### What happened?

I'm starting my test execution but still have access to all JSONWP protocol functions, even more i have access to APPIUM, BIDI, Saucelab, Browserstack functions but i even didn't run it or wouldn't use it.

Currently WDIO8 is W3C by default and if i'd like to switch it on to JSONWP i have to use w3c: false in options, something like that

  capabilities: {
    browserName: 'chrome',
    'goog:chromeOptions': {
        'w3c': false
    }
  }
in the case i have access to whole scope off w3c methods together with JSONWP

### What is your expected behavior?

I think expected behavior have an acess only to list of methods related to current protocol that are being using at the moment.

if it W3C Browser and Element should contain only W3C methods
if it JSONWP  Browser and Element should contain only JSONWP methods

### How to reproduce the bug.

JSONWP
browser.moveToElement() when it's W3C run

W3C
browser.maximazeWindow() when it's jsonwp run

and so on
the main issue all of them are available in browser

### Relevant log output

```typescript
-
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

I started to deprecated JSONWP all together https://github.com/webdriverio/webdriverio/pull/11584 since I believe there is no need to support it anymore given that everyone now pretty much supports WebDriver (or should).

I made a note to remove the commands in https://github.com/webdriverio/webdriverio/issues/10362 and I would suggest to keep the current status quo until then.

What do you think?

**Comment by udarrr** [comment]
That great @christian-bromann! Looking forward with merging the PR https://github.com/webdriverio/webdriverio/pull/11584 to wdio8 with deprecated notice, then it could be possible to use it with 'eslint-plugin-deprecation' package. it will definitely help in migration process, because whole deprecated method are going to be highlighted. To be honest currently it's hell to migrate old projects and tried to figure out where else JSONWP method exist.

**Comment by christian-bromann** [comment]
> To be honest currently it's hell to migrate old projects and trying to figure out where else JSONWP method exist.

Do you think there is anything we can do more to help with that or can we go ahead and close this with merging #11584?

**Comment by udarrr** [comment]
just added some deprecated methods else here https://github.com/webdriverio/webdriverio/pull/11611

**Comment by udarrr** [comment]
@christian-bromann could you trigger a new version?
