### ISSUE TITLE
[🐛 Bug]: Webdriverio.Element has types issues

### ISSUE THREAD

**Issue by Pawel1894** [webdriverio/webdriverio#11582]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
-
```

### What happened?

It looks like `Webdriverio.Element` has wrong typings. It allows us to run some functions that does not exists in `Webdriverio.Element`. 

Example that I found is `execute` function. I spoke to Erwin about that and it seems like there is more `browser commands` that are in  `Webdriverio.Element` typings.

### What is your expected behavior?

Remove typings of functions that does not exists on  `Webdriverio.Element`.

### How to reproduce the bug.

```ts
    await browser.url('https://webdriver.io')
    const el = await browser.$$('.prism-code.language-js.codeBlock_bY9V.thin-scrollbar')[0]
    
    const cssValue = await el.execute(
        (el, pseudoElement, cssProperty)=> (window.getComputedStyle(el, pseudoElement) as any)[cssProperty],
        el,
        '::before',
        'width'
    )
```

### Relevant log output

```typescript
-
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!



We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by udarrr** [comment]
I think problem more complicated. For example i'm starting my execution like w3c but still have access to all jsowp protocol functions, even more i have access to bidi, saucelab, browserstack functions but i even didn't run it.

**Comment by udarrr** [comment]
The original issue easy to resolve like possible solution could be changed in the file https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/types.ts

lines 38,78 to
```
parent: Promise<WebdriverIO.Element | WebdriverIO.MultiRemoteBrowser>
```

but issue that i've highlighted require more efforts

**Comment by Pawel1894** [comment]
Yeah, but also all the functions have Element type in params 😄 So I guess they needs to be cleaned up too.

**Comment by udarrr** [comment]
let's get started to resolve initial one, the rest i move to different issue
