### ISSUE TITLE
Generators don't seem to be working

### ISSUE THREAD

**Issue by zdfs** [webdriverio/webdriverio#1159]
Tests that worked in V3 don't seem to functioning properly in V4. For example, this worked:

```javascript
'use strict';

describe('Logo', function() {

	// Before we run any tests, navigate to the home page.

	before(function*() {
		yield browser.url('/');
	});

	// Let's make an array of all the CSS properties we want to test.

	let cssProps = {
		color: 'rgba(255,255,255,1)',
		'font-family': 'logoregular',
		'text-transform': 'uppercase'
	};

	// For every CSS property we have, let's write a test for it.

	Object.keys(cssProps).forEach(cssPropKey => {

		it(`has a ${cssPropKey} property with the value of ${cssProps[cssPropKey]}`, function*() {

			var property = yield browser.getCssProperty('[data-topbar] h1 a', cssPropKey);

			property.value.should.not.equal(cssProps[cssPropKey]);

		});

	});

});
```

But what happens now is that the browser just remains blank and the tests always pass, though I coded it to be failing.

Here are my Mocha options:

```javascript
mochaOpts: {
	ui: 'bdd',
	compilers: ['js:babel-register', 'js:babel-polyfill'],
	timeout: 30000,
	slow: 1000
}
```

And one final thing. I can't seem to use the `spec` reporter anymore. The test runner asks for `wdio-spec-reporter`, but this package doesn't seem to exist on NPM.

**Comment by christian-bromann** [comment]
@zdfs there is no need for generators in v4 because all commands are running synchronous anyway

**Comment by zdfs** [comment]
Oh. Wow! Ok. And the `spec` reporter?

**Comment by khirakawa** [comment]
@christian-bromann Would generators still work if we set `sync: false`?
