### ISSUE TITLE
v4 starting skipped tests with wdio-mocha-framework

### ISSUE THREAD

**Issue by psimyn** [webdriverio/webdriverio#1160]
When I have tests excluded with describe.skip (or one selected with .only) webdriver seems to start a browser instance of every test anyway.

Locally this means a bunch of browser instances popping up, and it spawns a lot of instances on browserstack.

Using the following versions of things:
```
"wdio-mocha-framework": "^0.2.11",
"webdrivercss": "^2.0.0beta-rc1",
"webdriverio": "^4.0.3"
```

Incredible update from v3 though!

**Comment by christian-bromann** [comment]
@psimyn note that in v4 wdio will spawn one Selenium session per spec file, that means if you have 3 spec files and 3 capabilities it would spawn 9 sessions to reach the maximum possible concurrency. You can limit this by setting `maxInstances: 1` in your wdio.conf.js or apply this property to a certain capability to limit only certain browser.

**Comment by psimyn** [comment]
thanks for the quick response @christian-bromann,  `maxInstances: 1` is great for dev.

Is it possible to not spawn a browser instance for skipped tests?

**Comment by psimyn** [comment]
Ah, nvm - tracking in https://github.com/webdriverio/webdriverio/issues/1163
