### ISSUE TITLE
[🐛 Bug]: getting type errors trying to use bidi methods

### ISSUE THREAD

**Issue by jlipps** [webdriverio/webdriverio#11630]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.21.0

### Node.js Version

18.17.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
n/a
```

### What happened?

I tried to run the following command:

```js
        await driver.browsingContextNavigate({
          context: 'foo',
          url: 'https://appium.io',
          wait: 'complete',
        });
```

And I got the following error output:

```
     Error: Malformed type for "params" parameter of command browsingContextNavigate
Expected: `remote.BrowsingContextNavigateParameters`
Actual: object

For more info see https://w3c.github.io/webdriver-bidi/#command-browsingContext-navigate
```

### What is your expected behavior?

According to the type definitions, my params object matches the interface. TypeScript agrees with me. But when running an actual test I get this error. I would expect it not to exist and to send the websocket data instead.

### How to reproduce the bug.

above

### Relevant log output

```typescript
above
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Running the following example just works fine:
```ts
const driver = await remote({
    capabilities: {
        browserName: 'chrome',
        webSocketUrl: true
    }
})

const { contexts } = await driver.browsingContextGetTree({})
driver.browsingContextNavigate({
    context: contexts[0].context,
    url: 'https://appium.io/',
    wait: 'complete',
})

await driver.pause(2000)
await driver.deleteSession()
```

Can you provide a reproducible example from your side?

**Comment by jlipps** [comment]
I reinstalled my deps and can no longer repro. Closing.

**Comment by jlipps** [comment]
Actually, I figured out how to repro this. If you don't include `webSocketUrl` in your caps, you get this error. It's a confusing error to get in that case; a better error would probably be `You can't use these methods unless you set the bidi capability` etc...

**Comment by christian-bromann** [comment]
Oh, nice, thanks! I will look into this.
