### ISSUE TITLE
v4 wdio-mocha-framework behaves incorrectly when using ".only" 

### ISSUE THREAD

**Issue by jishuoyang** [webdriverio/webdriverio#1163]
Hey, I'm running into a few issues when using wdio cli to run Mocha tests:

1. When `.only` is appended to a `describe`, Webdriver seems to ignore it and incorrectly continues to run all test suites in the spec file.

2. When `.only` is appended to an `it` test case, it correctly becomes the only test case to run, but suffers from a different problem: it runs asynchronously instead of synchronously.

For example, the code below has two identical tests, but one is sync and the other is async. 
When the suite is run, **Test 1** passes and **Test 2** fails. 
When **Test 1** is appended with `.only`, it fails. 
When **Test 2** is appended with `.only`, it passes.
```
describe('sanity tests', function () {
    it('Test 1: sync google search', function (done) {
        browser.url('https://www.google.com');
        browser.setValue('input[type="text"]', 'test search string');
        browser.click('button[type="submit"]');
        browser.pause(1000);
        assert.equal(browser.getTitle(), 'test search string - Google Search', "Search title is incorrect");
    });

    it('Test 2: async google search', function (done) {
        browser.url('https://www.google.com')
            .setValue('input[type="text"]', 'test search string')
            .click('button[type="submit"]')
            .pause(1000)
            .getTitle(function(err, title) {
                assert.equal(browser.title, 'test search string - Google Search', "Search title is incorrect");
            })
            .call(done);
    });
});
```

Node modules being used:
```
    "mocha": "2.4.5",
    "selenium-standalone": "4.9.0",
    "wdio-mocha-framework": "0.2.11",
    "webdriverio": "4.0.3"
```

**Comment by christian-bromann** [comment]
Ahh yeah that could be an issue indeed. Thanks for reporting!

**Comment by dcosson** [comment]
I'm seeing a similar issue with jasmine as well - using `fit` and `fdescribe` aren't working with the wdio runner. Could it be the same issue?

**Comment by christian-bromann** [comment]
Yes

**Comment by christian-bromann** [comment]
@dcosson `fit` and `fdescribe` should work in jasmine, I just added [a test](https://github.com/webdriverio/wdio-jasmine-framework/commit/ac4f34801df967a19ea70747104a35a9a0bd72cc) for `fdescribe` .. note that Jasmine seems to not care between multiple spec files, it seems that `fdescribe` only forces one `describe` block between multiple within one file

**Comment by dcosson** [comment]
@christian-bromann hmm do I have to run it with the jasmine runner? With wdio with my jasmine specs split into multiple files it's not working. It seems that in the test file with the `fit`, that's the only test that runs but all the other tests from all the other files still run in parallel with it.

**Comment by christian-bromann** [comment]
@dcosson that's the behavior what I tried to explain. If you have 3 spec files and in one file you have a `fdescribe` or `fit` that doesn't stop the other files from getting executed. If you want to only execute a specific spec file you need to put it in a suite like:
```js
// wdio.conf.js
export.config = {
  // ...
  suites: {
    mySuite: ['some.spec.js'],
    // ...
  },
  // ..
};
```
and run the wdio command like
```sh
$ ./node_modules/.bin/wdio wdio.conf.js --suite mySuite
```

**Comment by dcosson** [comment]
Ah ok, thanks for the suite example.

**Comment by christian-bromann** [comment]
`it.only` will be supported with the next mocha reporter version `v1.0.0`, can't release it yet though as it requires the new WebdriverIO version to be released

**Comment by openam** [comment]
Is `describe.only` going to be supported in the new version along with `it.only`?

**Comment by christian-bromann** [comment]
`describe.only` should work out of the box, we don't overwrite this function

**Comment by tjoskar** [comment]
I can't get `describe.only` to work. If I have test cases in different files and one of the specs are using  `describe.only`, all tests are executed anyway.

i.e.

```
// spec1.js
describe.only('Spec 1', () => {

  it('should test something', () => {
    ...
  })

});

// spec2.js
describe('Spec 2', () => {

  it('should test something', () => {
    ...
  })

});
```

```
$ wdio wdio.conf.js // both spec1 and spec2 are being executed
```

**Comment by christian-bromann** [comment]
@tjoskar if you want to run a single spec, rather use the suite option. See http://webdriver.io/guide/testrunner/organizesuite.html bottom.

**Comment by christian-bromann** [comment]
Just fyi: `describe.ony` won't work because each spec file runs in its own child process and doesn't know about other files. We will introduce a global grep/fgrep option with #1247

**Comment by albertogasparin** [comment]
FYI, I've implemented a "quick and dirty" solution to support it (I prefer a slower bootstrap than having my entire suite running because I forgot `.only` is not working as it should):

``` js
// wdio.conf.js
function getTestFiles(filesPattern) {
  let glob = require('glob');
  let fs = require('fs');
  let files = glob.sync(filesPattern, { cache: true });
  let singleSpec;
  files.some((f) => fs.readFileSync(f).indexOf('describe.only') >= 0 && (singleSpec = f));
  return singleSpec || filesPattern;
}

let config = {
  specs: [
    getTestFiles('./tests/**/*.spec.js'),
  ],
  //...
};
```
