### ISSUE TITLE
[🐛 Bug]: allure report addEpic is not a function

### ISSUE THREAD

**Issue by carri747** [webdriverio/webdriverio#11632]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.15.10

### Node.js Version

18.15.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities = [
    {
        browserName: 'chrome',
        browserVersion: '119.0.6045.105',
        'goog:chromeOptions': {
            args: [
                '--headless',
                '--disable-infobars',
                '--no-sandbox',
                '--disable-gpu',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage',
                '--window-size=1920,1080',
                `--user-agent=${userAgent}`,
                '--remote-allow-origins=*'
            ],
            prefs: {
                ['profile.default_content_setting_values.images']: 2
            }
        }
    }
```

### What happened?

I'm trying to add a "epic" in allure report. I'm using this version "@wdio/allure-reporter": "8.21.0", but I've this error in my log:
```
023-11-09T17:07:59.982023-11-09T17:07:59.991Z ERROR @wdio/utils:shim: TypeError: allure_reporter_1.default.addEpic is not a function
    at addEpicToAllureReport (....\AutomationTest\src\utils\customAllureReportGeneration.ts:116:20)
    at Object.<anonymous> (...\AutomationTest\wdio.conf.ts:447:30)
    at Generator.next (<anonymous>)
    at fulfilled (...\AutomationTest\wdio.conf.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Make not sense because I'm using other function like:
- addFeature
- addSeverity
And I don't have any issue with that 
My code is this:

```
import AllureReporter from '@wdio/allure-reporter';
// Function working
export function addSeverityToAllureReport(world: ITestCaseHookParameter) {
    const severity = world.pickle.tags.find(x => x.name.indexOf('@Severity') === 0);
    if (severity) {
        let severityValue: string = severity.name.substring(severity.name.indexOf('.') + 1, severity.name.length - 1).toLocaleLowerCase();
        AllureReporter.addSeverity(severityValue.trim());
    }
}

// Function working
export function addFeatureToAllureReport(world: ITestCaseHookParameter) {
    const inEnum = Object.values(AllureFeature) as string[];
    world.pickle.tags.forEach(tag => {
        if (inEnum.includes(tag.name)) {
            AllureReporter.addFeature(tag.name.replace('@', '').toUpperCase());
            return;
        }
    });
}
//function with error 
export function addEpicToAllureReport(world: ITestCaseHookParameter) {  
    AllureReporter.addEpic('asdfads');
}
```

See image for more info
![image](https://github.com/webdriverio/webdriverio/assets/22347831/9cfa9bdf-3c25-4c71-9f1f-1c38fdc24342)
![image](https://github.com/webdriverio/webdriverio/assets/22347831/4e5a285c-3586-4166-b077-86ac64bca6b7)

I don't know if it's mi mistake or not

Thanks.

### What is your expected behavior?

no errors adding epic in allure

### How to reproduce the bug.

wdio.conf.ts
```
 afterScenario: async function (world, result) {
        addSeverityToAllureReport(world);
        addFeatureToAllureReport(world);
        addEpicToAllureReport(world);
}
```

### Relevant log output

```typescript
023-11-09T17:07:59.982023-11-09T17:07:59.991Z ERROR @wdio/utils:shim: TypeError: allure_reporter_1.default.addEpic is not a function
    at addEpicToAllureReport (....\AutomationTest\src\utils\customAllureReportGeneration.ts:116:20)
    at Object.<anonymous> (...\AutomationTest\wdio.conf.ts:447:30)
    at Generator.next (<anonymous>)
    at fulfilled (...\AutomationTest\wdio.conf.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by BorisOsipov** [comment]
@carri747 

It works like a charm in [my test repo](https://github.com/BorisOsipov/tmp-wdio-cucumber-test)
Could you share a repo with reproducable example?

**Comment by carri747** [comment]
Hi @BorisOsipov 
In your code you have the same problem 
See the picture:
![image](https://github.com/webdriverio/webdriverio/assets/22347831/a0e881ad-a80a-43c9-9dfa-9f4f617fa6b6)
![image](https://github.com/webdriverio/webdriverio/assets/22347831/01f8c022-26ed-4567-8981-12903f6d2df1)

But in your case the function that have the error is "addFeature" and not "addEpic"

I'm using node 18.15.0 and npm version 9.5.0

**Comment by erwinheitzman** [comment]
@carri747 can you please provide a reproducible example? thank you

**Comment by carri747** [comment]
I think that It's not necessary a reproducible example, I found the issue 
in @BorisOsipov's  example he use this import 
`import AllureReporter from '@wdio/allure-reporter';`
like me. I don't know why but he was lucky because the "epic" function is redirect to "reporter.d.ts" and not "api.d.ts". I don't know why but sometime this function use one or other "d.ts". 
In any case, I checked both "d.ts" file and I found something strage, at least for me:
When you import the complete object you have access to default object 
"api.d.ts" file:
```
...
declare const _default: {
    addFeature: typeof addFeature;
    addAllureId: typeof addAllureId;
    addLabel: typeof addLabel;
    addSeverity: typeof addSeverity;
    addIssue: typeof addIssue;
    addTestId: typeof addTestId;
    addStory: typeof addStory;
    addEnvironment: typeof addEnvironment;
    addDescription: typeof addDescription;
    addAttachment: typeof addAttachment;
    startStep: typeof startStep;
    endStep: typeof endStep;
    addStep: typeof addStep;
    addArgument: typeof addArgument;
    step: typeof step;
    addTag: typeof addTag;
};
export default _default;
```
as you can see in this default declaration is not the "epic" function and this is the cause why I've "allure_reporter_1.default.addEpic is not a function" because it's not defined there. The thing is that in all the cases in the default declaration is defined all the export function but "epic" no

Workaround for me change the import from this `import AllureReporter from '@wdio/allure-reporter';` to this `import { addEpic } from '@wdio/allure-reporter';` and with this "epic" function is working fine

Please consider if in future release this change should be introduce or not 

Thanks for the help @BorisOsipov  and @erwinheitzman
