### ISSUE TITLE
Some commands are not chainable with pageObjects.

### ISSUE THREAD

**Issue by nathansmj** [webdriverio/webdriverio#1164]
some functions like 'getHTML', 'selectByIndex' are not working with PageObject. [v4 with wdio]

File: pageobjects/registration.page.js
```javascript
...
var registrationPage = Object.create(page, {
    textBox_email: { get: function() { return browser.element('#email'); } },
    dropDown_sex : { get: function() { return browser.element('select[name=sex]'); } }

...
```
file: tests/example.js
```javascript
var RegistrationPage = require ('../pageobjects/client/registration.page');
...
RegistrationPage.textBox_email.setValue(suiteData.email); // works 
browser.selectByIndex('select[name=sex]',1);    // works

RegistrationPage.dropDown_sex.selectByIndex(1); // error: number or type of arguments don't agree with selectByIndex commandcode
```

`RegistrationPage.dropDown_sex.selectByIndex ` errors out with message 

> "number or type of arguments don't agree with selectByIndex commandcode"

**Comment by nathansmj** [comment]
if get have get in the below format,
```javascript
textBox_email: { get: function() { return browser.element('#email'); } },
```
`isExisting` on the pageObject ends up in errors, when the element doesn't exist. This is because `browser.element` for a non-existing selector ends up in error. Any thoughts on making below syntax work or on cleaner alternate syntax!
```javascript
var existCheck = PageObject.textBox_email.isExisting();
```

**Comment by patthiel** [comment]
this might be a little hacky, but you could do this for your page object..
```
textBox_email: { get:  
    try { 
        return browser.element('#email'); 
    }
    catch(err) { 
        return false
    } 
},
```

This will try the command, and if it finds the element return true, if it doesn't find the element and returns any error, it'll return false.

**Comment by christian-bromann** [comment]
> number or type of arguments don't agree with selectByIndex command

I have to fix that for couple of commands which do parameter checks


> when the element doesn't exist

In your page object I would recommend to always use the `elements` commands to query elements. This way you don't get these errors and `getText` returns `[]` which is assertable

**Comment by nathansmj** [comment]
Btw, any reason for marking this closed. I believe the 'number or type of arguments don't agree with selectByIndex command' is the key issue and thats still open.

**Comment by christian-bromann** [comment]
yeah but I am aware of that and it's already mentioned in an other ticket.

**Comment by xywang68** [comment]
Guys, thank you for pointing out this issue. Any plan for fixing the element chained getHTML() issue?

**Comment by christian-bromann** [comment]
@xywang68 this issue should already be fixed
