### ISSUE TITLE
How to upload a file without clicking a submit button

### ISSUE THREAD

**Issue by ryan-cubic** [webdriverio/webdriverio#11640]
How to upload a file without clicking a follow up submit button??

steps:
1. Set file path using codes at https://webdriver.io/docs/api/browser/uploadFile/
2. Without executing "await $('#file-submit').click()"

Context: 
User can upload a file simply by selecting a file via the system dialog window and then clicking the OPEN button (Mac OS) without following up with another click from the web page.  That's the way our web app was designed to work.  Yes we could add another button called submit or upload to the web page but why?  Just for UI automation?

Please confirm if such use case is possible or not with WebdriverIO.  Thanks.

**Comment by erwinheitzman** [comment]
You can read all about that here: https://webdriver.io/blog/2019/06/25/file-upload/

**Comment by erwinheitzman** [comment]
Questions like this can be asked in GH discussions or in Discord.

**Comment by christian-bromann** [comment]
The submit click is optional. It depends how your application works. If it can detect the change to the file upload field and auto submit, then this extra click is not needed. There are hundreds of different ways a file upload can be implemented and there is no way to implement a single automation command that can control them all. Note that you can always use the `execute` command to trigger a submission as well.

Let me know if you have any further questions. I am not sure what further information I can provide.

**Comment by ryan-cubic** [comment]
@christian-bromann , Thanks for replying.  
It turned out using .addValue(value) instead of .setValue(value) resolved the issue.

ref: https://webdriver.io/docs/api/browser/uploadFile/
