### ISSUE TITLE
[🐛 Bug]: Startup command `yarn create wdio .` seems broken

### ISSUE THREAD

**Issue by giuseppe-salvatore** [webdriverio/webdriverio#11669]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

18.17.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
Don't even get to capabilities setup
```

### What happened?

When running 

`yarn create wdio .`

the following error shows

```
Error: Couldn't find a package.json file in "/home/gr4ce/workspakce/personal/webdriver.io/version-test/webdriverio-autoinit"
    at MessageError.ExtendableBuiltin (/home/gr4ce/.nvm/versions/node/v18.18.2/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/home/gr4ce/.nvm/versions/node/v18.18.2/lib/node_modules/yarn/lib/cli.js:750:123)
    at /home/gr4ce/.nvm/versions/node/v18.18.2/lib/node_modules/yarn/lib/cli.js:41356:15
    at Generator.next (<anonymous>)
    at step (/home/gr4ce/.nvm/versions/node/v18.18.2/lib/node_modules/yarn/lib/cli.js:310:30)
    at /home/gr4ce/.nvm/versions/node/v18.18.2/lib/node_modules/yarn/lib/cli.js:321:13
```

### What is your expected behavior?

The command should ideally run through completion

### How to reproduce the bug.

Just run `yarn create wdio .` as explained in the Getting Started guide here https://webdriver.io/docs/gettingstarted

### Relevant log output

```typescript
Error: Couldn't find a package.json file in "/home/gr4ce/workspakce/personal/webdriver.io/version-test/webdriverio-autoinit"
    at MessageError.ExtendableBuiltin (/home/gr4ce/.nvm/versions/node/v18.18.2/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/home/gr4ce/.nvm/versions/node/v18.18.2/lib/node_modules/yarn/lib/cli.js:750:123)
    at /home/gr4ce/.nvm/versions/node/v18.18.2/lib/node_modules/yarn/lib/cli.js:41356:15
    at Generator.next (<anonymous>)
    at step (/home/gr4ce/.nvm/versions/node/v18.18.2/lib/node_modules/yarn/lib/cli.js:310:30)
    at /home/gr4ce/.nvm/versions/node/v18.18.2/lib/node_modules/yarn/lib/cli.js:321:13
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by giuseppe-salvatore** [comment]
@christian-bromann that is interesting! 

I was just running `yarn create wdio .` on a fresh clean directory just created.

I have executed in 3 different linux machines and it looks like in the one that is using node 16 is working, not on the ones using node 18. 
Can you please try with node 18 if you get the chance (unless you are not already using it). Also are you win/linux/mac?

**Comment by giuseppe-salvatore** [comment]
I can only provide this one below plus the environment I am using 
- Ubuntu 22.04
- node 18.17.1
- yarn freshly installed with `npm install -g yarn`
- executing `yarn create wdio .`

Happy for you to close it, I guess if someone else hits this problem they will hopefully report it. I found strange that it is failing because it's not finding `package.json`


![image](https://github.com/webdriverio/webdriverio/assets/5897348/9f4fd708-a3cf-4c20-8f83-88e720b6e84f)

**Comment by christian-bromann** [comment]
> executing yarn create wdio .

Does it fail with other starter projects too?
