### ISSUE TITLE
Session stops working after runtime error

### ISSUE THREAD

**Issue by Deadly0** [webdriverio/webdriverio#1166]
I't trying to close browser and session after NoSuchElement exeption as sayd in docs http://www.webdriver.io/guide/usage/eventhandling.html

```
client.on('error', function(e) {
    client.end();
})
```
but ```client.end()``` do nothing. Browser still stays open and i can't execute any command for ```client```

I have found closed issue with similar problem https://github.com/webdriverio/webdriverio/issues/337 but issue has been not solved.

Any ideas how to close browser after error?
version 3.4.0

**Comment by christian-bromann** [comment]
Why would you like to end a session after a NoSuchElement exception? This exception can happen at each point in your test and when you close the session all following test cases fail due to a no session error. If you use Mocha you can let the whole test suite fail after the first test broke. That might be a better idea to handle this.

**Comment by christian-bromann** [comment]
Also event handler can't handle async code executions. Therefor it's not possible to do such thing anyway. Closing.

**Comment by Deadly0** [comment]
@christian-bromann sorry, i didn't know that webdriverio designed only for testing, my mistake. Thank you for your answer!

**Comment by christian-bromann** [comment]
Well it is not only designed for testing. People use it to automate things as well. However ending the session within an event handler is not possible. You need to structure the command execution in a way you can stop command execution if an error happened

**Comment by Deadly0** [comment]
@christian-bromann ok, got it, thank you for your help!
