### ISSUE TITLE
[🐛 Bug]: "@wdio/cucumber-framework": "^8.22.0" not respecting config.cucumberOpts.timeout

### ISSUE THREAD

**Issue by SameerYoussef** [webdriverio/webdriverio#11675]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.22.0

### Node.js Version

18

### Mode

WDIO Testrunner

### What happened?

Given wdio config includes:
{
  framework: "cucumber",
  cucumberOpts: {
    timeout: 70000,
}

When I run tests using npx wdio wdio.config.js

And my step definition includes: `await browser.pause(20000);`

### What is your expected behavior?

Then I expect my step to pass given the cucumber step timeout is 70s while my step only takes 20s

It appears the timeout has become 20s rather than what is defined in the wdio config.

### How to reproduce the bug.

```js
Then(/^I should be on the page$/, async (givenPage) => {
    await browser.pause(20000);
}
```

### Relevant log output

```typescript
[0-10] Error in "0: Then I should be on the page"
Error: Timeout
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

Any chance you can create a reproducible example?

We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by charlesh21** [comment]
I have same issue, after upgrade to @wdio/cucumber-framework@8.23.0

Our tests got lots of failure with Timeout error

```
11:39:21 [chrome 119.0.6045.106 windows #0-0] Error: Timeout
11:39:21 [chrome 119.0.6045.106 windows #0-0] Error: Timeout
11:39:21 [chrome 119.0.6045.106 windows #0-0]     at listOnTimeout (node:internal/timers:559:17)
11:39:21 [chrome 119.0.6045.106 windows #0-0]     at processTimers (node:internal/timers:502:7)
```

In wdio.config.js
```
cucumberOpts: {
timeout: 60000,
},
```

In specific step
```
Given(/^input 2 type and 2 format :$/, {timeout: 120 * 1000}, async function (table) {
       step script
});
```

It seems both setting timeout method not working, our test got failure before hit the setting timeout.

**Comment by HannaTarasevich** [comment]
The same issue is for me

**Comment by dmarcas** [comment]
Yesterday I experienced the same issue (with the same error output) and I had to downgrade to the "8.22.0" and remove the autoupdate minor/patch versions "^". In my case, it wasn't respecting the timeout for the step-definitions defined in the wdio.conf.js:

```
  // If you are using Cucumber you need to specify the location of your step definitions.
    cucumberOpts: {
        // <string[]> (file/dir) require files before executing features
        require: ['src/features/step-definitions/**/*.js'],
        // <boolean> show full backtrace for errors
        backtrace: false,
        // <string[]> ("extension:module") require files with the given EXTENSION after requiring MODULE (repeatable)
        requireModule: [],
        // <boolean> invoke formatters without executing steps
        dryRun: false,
        // <boolean> abort the run on first failure
        failFast: false,
        // <boolean> hide step definition snippets for pending steps
        snippets: true,
        // <boolean> hide source uris
        source: true,
        // <boolean> fail if there are any undefined or pending steps
        strict: false,
        // <string> (expression) only execute the features or scenarios with tags matching the expression
        tagExpression: '',
        // <number> timeout for step definitions
        timeout: 360000,
        // <boolean> Enable this config to treat undefined definitions as warnings.
        ignoreUndefinedDefinitions: false
    },
```
