### ISSUE TITLE
External libraries and v4

### ISSUE THREAD

**Issue by jakesjews** [webdriverio/webdriverio#1168]
Hello, I am trying to update some webdriver tests to version 4 but having some difficulties. I use a few external libraries which return promises but am unsure how to use them since generators are no longer supported. Is there some way to continue to run tests with generator support or do I need to find a way to wrap external promises with fibers?

**Comment by christian-bromann** [comment]
@jakesjews you can still use external libraries in v4. Just handle them like you did before with a tiny difference: you can activate sync commands by wrapping a callback within the global `wdioSync` method like this:

```js
it('...', function() {
    browser.url("...");
    return externalLib.command(arg).then(wdioSync(function(res) {
        console.log(browser.getTitle();
    });
});
```
Once you start using the external lib make sure you return the promise. You can also just continue using async commands. The sync effect is gone as soon as you are in a different eventloop:

```js
it('...', function() {
    browser.url("...");
    return externalLib.command(arg).then(wdioSync(function(res) {
        return browser.getTitle().then(function(titile) {
             console.log(title);
        });
    });
});
```

Also a nice way to embed external libraries is to put them into a async custom command like:

```js
browser.customCommand('doExternalJob', function async (params) {
    return externalLib.command(params);
});
```
Make sure the function name of your custom command is `async`. Then you can just use it synchronously:
```js
it('...', function() {
    browser.url("...");
    browser.doExternalJob('someParam');
    console.log(browser.getTitle();
});
```

**Comment by jakesjews** [comment]
@christian-bromann exactly what I was looking for. Thanks!

**Comment by rogernorling** [comment]
After talking to @christian-bromann over gitter I'd like to add that `customCommand` is a typo, that method doesn't exist. The correct method is `addCommand`.
