### ISSUE TITLE
[🐛 Bug]: <Unable to capture screenshot in an iframe>

### ISSUE THREAD

**Issue by Rudecruels** [webdriverio/webdriverio#11685]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.16.11

### Node.js Version

v18.12.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [
    {
      browserName: "firefox",
    },
  ],
```

### What happened?

When try to capture screenshot using browser.saveScreenshot() webdriverio throws an error.
 ERROR webdriver: Request failed with status 200 due to unknown error: SecurityError: Permission denied to access property "pageXOffset" on cross-origin object.
issue occured when saveScreenshot is used after switch  to an iframe and perform som actions in that frame.
when tried in chrome browser no issues found

### What is your expected behavior?

Able to captureScreenshot using saveScreenshot  after switch to iframe

### How to reproduce the bug.

To reproduce this issue clone the repository
https://github.com/Rudecruels/webdriverio-iframe-issue

### Relevant log output

```typescript
ERROR webdriver: Request failed with status 200 due to unknown error: SecurityError: Permission denied to access property "pageXOffset" on cross-origin object
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting and for providing a reproducible example.

This seems to be an issue in Geckodriver and Firefox and was reported here: https://github.com/mozilla/geckodriver/issues/2068. There is nothing we can do at this point to fix it in WebdriverIO and have to wait until it gets fixed upstream.

Let me know if you have further questions.

**Comment by Rudecruels** [comment]
Okay thank you for this information. I look forrward the issue that you mentioned
