### ISSUE TITLE
select from li elements (dropdown list)?

### ISSUE THREAD

**Issue by narainsagar** [webdriverio/webdriverio#1169]
I want to `select` element like Used or New from the dropdown. But i think select command supports only `option` elements and there is i have `li` elements?

Can anyone tell how can i do this? though i am using `phantomjs` as browser.

FYI: this is link http://checkaflip.com/ please inspect and see the desired html. thanks.

Here is my code via without using `select` - though it works fine with `browserName: "chrome"` but not with `phantomjs`

```
var opts = {
  desiredCapabilities: {
    browserName: 'phantomjs'
  }
};

var client = require('webdriverio').remote(opts).init();
var upc = '724771050223';

client.url('http://checkaflip.com/')
	.setValue('#query', upc)
	.click('#newOrUsed')
	.waitForVisible('#newOrUsed>ul>li:nth-child(2)', 1000)
	.click('#newOrUsed>ul>li:nth-child(2)')
	.click('#submit')
	.waitUntil(function() {
	  return this.getText('#complavgprice').then(function(text) {
	    console.log('text', text);
	    return text !== 'calculating...';
	  });
	}, 1000)
	.waitUntil(function() {
	  return this.getText('#kwavgprice').then(function(text) {
	    console.log('text2', text);
	    return text !== 'calculating...';
	  });
	}, 1000);
```

**Comment by christian-bromann** [comment]
> But i think select command supports only option elements

That's right

The code looks fine. Don't know why it's not working in PhantomJS. Maybe try a different selector.

**Comment by narainsagar** [comment]
Yeah, Thanks for the response @christian-bromann!
