### ISSUE TITLE
Unable to get chrome logs 

### ISSUE THREAD

**Issue by madebysid** [webdriverio/webdriverio#1170]
I'm trying to get chrome's logs when launched through WebdriverIO.
These are the options I use to start chrome with:

```
{
      desiredCapabilities: {
        browserName: 'chrome',
        chromeOptions: {
          binary: path.resolve('/usr/bin/google-chrome'),
          forceDevToolsScreenshot: true,
          args: [
            '--load-and-launch-app=' + path.resolve('./build/chrome/'),
            '--enable-logging',
            '--v=1',
            '--no-sandbox',
          ]
        }
      }
}
```

When I run my script through Mocha, Chrome (and the external app) launches, but I do not see a chrome_debug.log file in my user directory (which should be `~/.config/google-chrome/` if I'm not mistaken).

If I do the same manually, as in, launching chrome via the command line `google-chrome --enable-logging --v=1`, the file does indeed appear, which leads me to believe this might be an issue with WebdriverIO.

I'm using Ubuntu 14.04 (Chrome 48), but I've tried doing the same on OSX(Chrome 49), with the same result.

**Comment by christian-bromann** [comment]
It should work if you remove the double dashes (`--`)

**Comment by madebysid** [comment]
I had no dashes initially, I added them later. Can you not replicate this?

**Comment by christian-bromann** [comment]
I haven't tried yet, chrome args have been applied correctly though. So not sure what's wrong

**Comment by madebysid** [comment]
Indeed they have, as I see the warning in chrome about the no-sandbox flag. Also, my app wouldn't load at all if they weren't being applied. Does Webdriver set a CHROME_LOG_FILE environment variable or something? That's seems like the only way Chrome wouldn't write logs where it is supposed to.

**Comment by AgentME** [comment]
If I set CHROME_LOG_FILE to a filename before running wdoi, then Chrome writes the log to the filename. (If I don't set CHROME_LOG_FILE, then it doesn't seem like Chrome writes its log file anywhere, which isn't consistent with the behavior I get from just launching Chrome with --enable-logging.)

**Comment by christian-bromann** [comment]
I think this is something that needs to be fixed in the chromedriver project.
