### ISSUE TITLE
[💡 Feature]: Replace current build system with Vite

### ISSUE THREAD

**Issue by colinrotherham** [webdriverio/webdriverio#11713]
### Is your feature request related to a problem?

This issue is a follow up to comment https://github.com/webdriverio/webdriverio/pull/11712#issuecomment-1823159517

Some older browsers [configured in `capabilities`](https://webdriver.io/docs/configuration#capabilities) throw errors when running scripts from [**webdriverio**/src/scripts](https://github.com/webdriverio/webdriverio/tree/main/packages/webdriverio/src/scripts), is this something we could solve or prevent using automation?

I've added some suggestions below

### Script errors in older browsers
For example, I've fixed some element method issues in older Firefox and IE11:

* https://github.com/webdriverio/webdriverio/issues/11705
* https://github.com/webdriverio/webdriverio/issues/11711

I'm getting there, but some are still failing:

[See GitHub Actions logs](https://github.com/alphagov/accessible-autocomplete/actions/runs/6960833744/job/18941141174) and [Sauce Labs output](https://app.saucelabs.com/tests/1c73bf850de1406db2de4304235851c8) for more info

```console
[internet explorer 11 windows #2-0] 25 passing (2m 3.7s)
[internet explorer 11 windows #2-0] 6 failing
```

### Describe the solution you'd like.

Since the scripts in [**webdriverio**/src/scripts](https://github.com/webdriverio/webdriverio/tree/main/packages/webdriverio/src/scripts) are TypeScript, could we target an older ECMAScript version?

They're currently using TypeScript `"target": "es2022"`

### Describe alternatives you've considered.

1. Using TypeScript `"target": "es5"` or lower for downleveling (and warnings)
2. Using ESLint with [`eslint-plugin-es-x`](https://github.com/eslint-community/eslint-plugin-es-x?tab=readme-ov-file#eslint-plugin-es-x) to check syntax against `ecmaVersion`
3. Using Babel presets to transform scripts without heavy polyfills
4. Using Internet Explorer 11 as a "token old browser" in E2E tests

### Additional context

What tests could be added to prevent unsupported syntax from being added again in future?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Thanks for raising this issue.

I think this topic opens up a broader discussion on improving our build system to allow different build outputs. Currently everything is build through TypeScript and it already got quite complex with CJS/ESM support.

Let's say we could introduce [Vite](https://vitejs.dev/) as build tool to:

- compile all modules in `/packages` as CJS and ESM version
- compile sub artifacts e.g. in `/packages/webdriverio/src/scripts` with different targets
- copy templates within `@wdio/cli` package to the right spot
- generate typings for changes within the protocols package
- introduce build metrics to monitor how long it takes to compile

This could be all embedded into a single Vite build. Our scripts can be moved into Vite plugins to streamline everything.

We greatly appreciate any contributions that help implement this feature request. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this feature being implemented. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!
