### ISSUE TITLE
npm install gives version 4 instead of 3

### ISSUE THREAD

**Issue by jonashdown** [webdriverio/webdriverio#1171]
Hi,
 running ```npm install webdriverio``` gives me version 4 not version 3. Surely if version 4 is still beta, it shouldn't be the default install ?

**Comment by christian-bromann** [comment]
Basically yes but we were at a point where we were confident to release v4 as it runs stable enough. We still call it beta because we haven't updated the website yet. This will change soon.

**Comment by jonashdown** [comment]
spent a lot of time working out that values where being returned instead of promises of values in functions like ```getText()```. This in my view is an undocumented breaking change
