### ISSUE TITLE
[🐛 Bug]: waitForDisplayed method does not work properly for Chrome

### ISSUE THREAD

**Issue by HannaTarasevich** [webdriverio/webdriverio#11710]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

20.9.0

### Mode

Standalone Mode

### Which capabilities are you using?

{
    browserName: 'chrome',
    browserVersion: 'stable',
    "w3c": false
}

### What happened?

We have some elements that are displayed right after click on other element. Appeared pop-up contains target element (I can find it in the DOM and it always displays on the screenshots), but WDIO fails with error message that element is not clickable/interactable/displayed. It has started failing since 11/20. There were no any code changes from our side. We always use the latest WDIO on the pipeline. So, I had to downgrade the versions to 8.22.0 (webdriver, local-runner, cli) and now it works again.

I found out that using previous approach with await this.isElementDisplayed(this.elementId) (that was working for Chrome before https://github.com/webdriverio/webdriverio/pull/11681) fixes the issue.

I guess that previous approach included repeating in getting the element by id (and looks like page reinitialization each time), that current approach does not do so. Therefore, even if the element has appeared on the page in my app, it does not see it.

### What is your expected behavior?

Element is found as displayed

### How to reproduce the bug.

Unfortunately, I didn't find the way to reproduce this issue on some open-source apps.

### Relevant log output

```typescript
v23
2023-11-21T19:25:26.822Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
2023-11-21T19:25:26.822Z INFO webdriver: [POST] http://0.0.0.0:49987/session/da5aa12ceff5f44bb622b633a7234d81/execute
2023-11-21T19:25:26.822Z INFO webdriver: DATA {
  script: 'isElementDisplayed(...) [8033 bytes]',
  args: [
    {
      'element-6066-11e4-a52e-4f735466cecf': '4684D05EC26DCDFA1BD83A49BDF17511_element_164',
      ELEMENT: '4684D05EC26DCDFA1BD83A49BDF17511_element_164'
    }
  ]
}
2023-11-21T19:25:26.833Z INFO webdriver: RESULT false
..
**_FAILURE_**


v22
2023-11-21T19:37:07.821Z INFO webdriver: COMMAND findElement("css selector", "div .k-multiselect")
2023-11-21T19:37:07.821Z INFO webdriver: [POST] http://0.0.0.0:51224/session/f7df37e8192d4936bfef514ad3a8390f/element
2023-11-21T19:37:07.821Z INFO webdriver: DATA { using: 'css selector', value: 'div .k-multiselect' }
2023-11-21T19:37:07.838Z INFO webdriver: RESULT { ELEMENT: '957A04CFD450AEA222A434341E72792B_element_162' }
2023-11-21T19:37:07.841Z INFO webdriver: COMMAND isElementDisplayed("957A04CFD450AEA222A434341E72792B_element_162")
2023-11-21T19:37:07.841Z INFO webdriver: [GET] http://0.0.0.0:51224/session/f7df37e8192d4936bfef514ad3a8390f/element/957A04CFD450AEA222A434341E72792B_element_162/displayed
2023-11-21T19:37:07.852Z INFO webdriver: RESULT true
..
**_PASSED_**
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@HannaTarasevich Thanks for raising the issue.

Is there really no chance to reproduce this? It seems very hard for anyone to look into fixing this when there is no example for this issue to occur. Can you maybe check on your end again why [this script](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/scripts/isElementDisplayed.ts) is returning `false` on your end and/or provide something that can be reproduced?

**Comment by HannaTarasevich** [comment]
Hi @christian-bromann,
I investigated deeper, and found out that there is an issue in the part:

```
    if (isElementSubtreeHiddenByOverflow(element)) {
        return false;
    }
```

I have the following DOM structure for my element:
```
kendo-multiselect (locator itself, visible)
               |
               -------> kendo-taglist (overflow: hidden)
                                         |
                                         -------> kendo-searchbar (display: none)
                                                                       |
                                                                       ------->input (overflow: hidden)
```

Steps in the script, that fail visibility:
1) Starts with - if (isElementSubtreeHiddenByOverflow(element))  - row 260
2) Then it checks subtree for non zero dimensions - if (!elementSubtreeHasNonZeroDimensions(childNode)) - row 191 starts recursion, then row 186 executes for subtree
3) For my case, elementSubtreeHasNonZeroDimensions returns _false_ (in part _return Array.from_) - row 145
4) So isElementSubtreeHiddenByOverflow returns true - row 187

If I understand correctly, if element childNodes are hidden, it means that the element is not visible for the current logic (even if the element itself has dimension and displayed)?

**Comment by christian-bromann** [comment]
@HannaTarasevich thank you for your investigations. Is there a way you can produce a minimal reproducible example so we can run this on our end? It is otherwise hard if not impossible to work on an exact solution.

**Comment by HannaTarasevich** [comment]
Hey @christian-bromann,
Finally, I researched the reproducible example: https://github.com/HannaTarasevich/wdio-timeout-issue. 
Also, I added some comments to the repro code inside the test step.

Please run "npm run wdio" script. It is working fine with the previous implementation, but with the new isDisplayed script it fails.

Please let me know in case of any questions. Thanks!

**Comment by christian-bromann** [comment]
Thanks for providing a reproducible example!



We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!
