### ISSUE TITLE
javascript error: javascript error: Object.hasOwn is not a function

### ISSUE THREAD

**Issue by iniyavans** [webdriverio/webdriverio#11728]
### Discussed in https://github.com/webdriverio/webdriverio/discussions/11725

<div type='discussions-op-text'>

<sup>Originally posted by **iniyavans** November 26, 2023</sup>
```
const isGetStartedDisplayed = await this.getingStarted.isDisplayed();
console.log(`The value is ${isGetStartedDisplayed}`);
await this.getingStarted.click();
```

from the above code I got true from isGetStartedDisplayed. But the js throw

javascript error: javascript error: Object.hasOwn is not a function
  (Session info: chrome=119.0.6045.159)
  
above error with a click function. Anyone can please assist me resolve this issue?</div>

**Comment by christian-bromann** [comment]
No need to raise an issue when you already raised an discussion. Closing.
