### ISSUE TITLE
Timeout of 10000ms exceeded even when timeout is give as 30000

### ISSUE THREAD

**Issue by arjunkomath** [webdriverio/webdriverio#1172]
Task for the test:
```
gulp.task('mds', ['default', 'selenium'], function() {
	return gulp.src('wdio.conf.js')
	.pipe(webdriver({
		waitforTimeout: 30000,
		reporter: 'spec'
	})).on('error', function() {
		seleniumServer.kill();
		process.exit(1);
	});
});
```

Config file:
`waitforTimeout: 30000,`

At both places I'm giving timeout as 30000, but still the test will timeout at 10000.

```
[18:28:53] spawn wdio with these attributes:
 /Usxxxers/xxx/xxx/xxxx/xxxxxx/public_html/tests/wdio.conf.js
--waitforTimeout=30000
--reporter=spec
```

**Comment by patthiel** [comment]
Can you provide the error that's outputted? thanks

**Comment by christian-bromann** [comment]
As you can get from the docs the `waitforTimeout` sets the default timeout for all `waitForXXX` commands. If you want to increase the test timeout you need to set it in your framework options like in Mocha:

```js
// wdio.conf.js
// ...
mochaOpts: {
    timeput: 99999999
}
// ...
```

**Comment by asoto-2sol** [comment]
Thanks for the clarification, changed the mocha timeout settings and is all working as expected now.

**Comment by prewk** [comment]
@christian-bromann You might want to change `timeput` to `timeout` in your answer.

**Comment by christian-bromann** [comment]
@prewk good catch 👍

**Comment by jampow** [comment]
I'm still getting this failure message "timeout of 10000ms exceeded" running tests on browserstack, even after set `mochaOpts: {timeout: 200000}`. What could it be?

**Comment by megamindbrian** [comment]
There should be a warning for repeated config settings.  WebStorm highlights the object key when there is a duplicate declaration it would be nice if the "testing" framework shows these kinds of mistakes.

**Comment by christian-bromann** [comment]
> it would be nice if the "testing" framework shows these kinds of mistakes

This is not the responsibility of the testing framework. It should be caught by your IDE!

**Comment by megamindbrian** [comment]
@christian-bromann Right, that is exactly the response my P.S. comment addresses.  When I am configuring Apache and make a mistake I get warnings.  It is not out of scope to do basic sanity checks.  When I am building my project, I get some TS Lint errors, how do I attach linting features to ```wdio run test``` ?

**Comment by christian-bromann** [comment]
> It is not out of scope to do basic sanity checks

We do these but not on that level. If you have duplicate property keys in your config, WebdriverIO couldn't even detect those.

**Comment by megamindbrian** [comment]
@christian-bromann After doing some research, I don't see a way for Nodejs to report this error either.  Is this normal to have 1 IDE that correctly evaluates code, but then those evaluations aren't available from within the compiler?  That seems odd that an IDE does something a compiler does not.

**Comment by christian-bromann** [comment]
> Is this normal to have 1 IDE that correctly evaluates code, but then those evaluations aren't available from within the compiler?

I don't know. What I know is that WebdriverIO can't do anything here.

**Comment by selvakumar1994** [comment]
@christian-bromann  where i added the below script in node js

mochaOpts: {
    timeout: 99999999
}

**Comment by christian-bromann** [comment]
in your `wdio.conf.js` as shown in the example
