### ISSUE TITLE
[🐛 Bug]: yarn pnp can't resolve `@wdio/local-runner`

### ISSUE THREAD

**Issue by epszaw** [webdriverio/webdriverio#11750]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.24.0

### Node.js Version

20.9.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
  browserName: 'chrome'
}
```

### What happened?

When I try to launch wdio inside yarn pnp project it throws an error about local runner and that it can't be resolved. When I try to do the same using npm everything works as expected

### How to reproduce the bug.

1. Create an empty directory
2. Run `yarn init -2` inside the directory
3. Run `yarn exec wdio init .` and answer all the questions with the default options
4. Run `yarn wdio`

### Relevant log output

```typescript
wdio-yarn-pnp on master [!?] via  v20.9.0
λ yarn wdio

Execution of 1 workers started at 2023-11-27T15:59:18.063Z

Error: Couldn't find plugin "local" runner, neither as wdio scoped package "@wdio/local-runner" nor as community package "wdio-local-runner". Please make sure you have it installed!
    at initialisePlugin (file:///usr/local/lib/node_modules/@wdio/cli/node_modules/@wdio/utils/build/initialisePlugin.js:35:11)
    at async Launcher.run (file:///usr/local/lib/node_modules/@wdio/cli/build/launcher.js:75:25)
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Can you provide the whole stdout text? I am a bit suspicious about the `yarn exec wdio init .` part which should be `yarn create wdio ./`. This is how it is documented. You are calling `wdio init` which is not a wdio command. Can you double check whether it works with this command?

**Comment by epszaw** [comment]
Unfortunately, `yarn create wdio ./` throws an error without any detail:

```
⚠️  Ups, something went wrong: Error calling: yarn add --exact --cwd /Users/epszaw/Code/Test/wdio-yarn-pnp --dev @wdio/cli@latest!
```

It doesn't relate to way, how to initialize the project because I've tried to do the same in existing project which was created manually.

**Comment by christian-bromann** [comment]
@epszaw can you provide a set of commands that help me reproduce the issue on my machine?

**Comment by epszaw** [comment]
I will a repository to make you able to reproduce the problem tomorrow

**Comment by epszaw** [comment]
Here is the example https://github.com/epszaw/wdio-yarn-pnp

**Comment by christian-bromann** [comment]
Thanks for providing the reproducible example! It seems like the `wdio` CLI dependency used is not within the same `node_modules` directory as all the other WebdriverIO dependencies. I am not too familiar with all the intricacies of Yarn so not sure how to fix this.

We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by erwinheitzman** [comment]
I wonder if this issue still exists with the new version we just released. Could you try running yarn create wdio@latest .?

**Comment by RSS1102** [comment]
> 不知道我们刚刚发布的新版本是否还存在这个问题。您可以尝试运行yarn create wdio@latest 吗？
```cmd
PS D:\html\electron-vite-test> yarn create wdio@latest
yarn create v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "create-wdio@8.4.1" with binaries:
      - create-wdio
[########################] 24/24'C:\Users\A1064\AppData\Local\Yarn\bin\create-wdio@latest' Not an internal or external command, nor a runnable program  or batch file.
error Command failed.
Exit code: 1
Command: C:\Users\A1064\AppData\Local\Yarn\bin\create-wdio@latest
Arguments: 
Directory: D:\html\electron-vite-test
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
PS D:\html\electron-vite-test> node -v
v18.6.0
PS D:\html\electron-vite-test> 
```

**Comment by erwinheitzman** [comment]
I have resolved the issue mentioned (this was an issue in the `create-cli` package) but ran into another issue with the `@wdio/cli` package so I am doing a follow-up on this 👍
