### ISSUE TITLE
[💡 Feature]: isDisplayed vs isDisplayedInViewport

### ISSUE THREAD

**Issue by udarrr** [webdriverio/webdriverio#11766]
### Is your feature request related to a problem?

I am wondering regarding behavior isDisplayed it's true when isn't into view
there is a method isDisplayedInViewport it's checking both isDisplayed and isElementInViewport
Is it necessary to check isDisplayed even if it's not into view? 

### Describe the solution you'd like.

Why don't we merge isDisplayedInViewport to isDisplayed ? 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Thanks @udarrr for raising the issue.

I believe there are two valid use cases for both of these:

- `isDisplayed`: verifying if an element is displayed in the app regardless of viewport location, e.g. check if an element pops up after interacting with the application
- `isDisplayedInViewport`: verify that element is within the viewport to ensure certain interactions work as expected, if not use `elem.scrollIntoView()` - there are some WebDriver commands that require an element to be within viewport to interact with them, e.g. action commands

I could imaging to merge these commands together and allow users to provide a parameter flag to let WebdriverIO know that a stricter viewport focused display check is desired. We can add this to the v9 list.

@webdriverio/technical-steering-committee any opinions?

**Comment by BorisOsipov** [comment]
There is nothing to change. `isDisplayed` and `isDisplayedInViewPort` are completely different checks in terms of test cases.

**Comment by christian-bromann** [comment]
> are completely different checks in terms of test cases.

@BorisOsipov can you elaborate on that?

**Comment by udarrr** [comment]
>    I could imaging to merge these commands together and allow users to provide a parameter flag to let WebdriverIO know that a stricter viewport focused display check is desired. We can add this to the v9 list.

Yes @christian-bromann  agree it makes sense, a argument could be options, I wonder regarding behavior by default. From my perspective it should be intoView as definition of the displayedness for w3c here 

https://w3c.github.io/webdriver/#element-displayedness  there having been said as that it should be visible to the human eye. 

Currently the method the most flaky in wdio from my point of view, as people don't understand why it's true if they can't see it. Even experienced engineers are encountered the behavior.

**Comment by erwinheitzman** [comment]
I agree with what has already been said and don't think it is worth changing the API when there are no actual benefits.

**Comment by udarrr** [comment]
@erwinheitzman isElementDisplayed exist for both JSONWP and W3C and the method isn't deprecated, it's part of W3C standard https://w3c.github.io/webdriver/#element-displayedness
 
i've described the issue here https://github.com/webdriverio/webdriverio/issues/11770

**Comment by erwinheitzman** [comment]
> > since the command clearly states this at the top of the documentation
> 
> > "Return true if the selected DOM-element is displayed (even when the element is outside the viewport). If you want to verify that the element is also not within the viewport, use the isDisplayedInViewport command."
> 
> The part has been added two weeks ago before that there weren't any doc regarding behavior just
> 
> 'Return true if the selected DOM-element is displayed.'

That is indeed true but right now it is clearly documented so I don't see what this adds to the conversation.

**Comment by christian-bromann** [comment]
I will add a task to our [v9 task list](https://github.com/webdriverio/webdriverio/issues/10362).

Remaining question: what should be the default behavior?

In my opinion just checking for displayedness somewhere on the app is in most cases totally sufficient and it makes sense to have user add a parameter to opt into a stricter check. I want to iterate that defining what "visible" means is very hard, e.g. one could say, if the element is only 1x1 pixel of size it is not visible either. This is why this command is not part of the protocol itself. We should ensure that our docs reflect what we do in the command and let the rest up for the user to decide.

**Comment by erwinheitzman** [comment]
> I added a task to our [v9 task list](https://github.com/webdriverio/webdriverio/issues/10362).
> 
> Remaining question: what should be the default behavior?
> 
> In my opinion just checking for displayedness somewhere on the app is in most cases totally sufficient and it makes sense to have user add a parameter to opt into a stricter check. I want to iterate that defining what "visible" means is very hard, e.g. one could say, if the element is only 1x1 pixel of size it is not visible either. This is why this command is not part of the protocol itself. We should ensure that our docs reflect what we do in the command and let the rest up for the user to decide.

Currently the todo task states that we will merge the two commands, is this the case or are we going to document the current behavior instead?

**Comment by udarrr** [comment]
> defining what "visible" means is very hard, e.g. one could say, if the element is only 1x1 pixel of size it is not visible either.

Oh i got it, look like they delegate it to client to determine what is displayed exactly. But it seems isElementDisplayed works better in some cases, Let me look into it. I'd like to find out source of  isElementDisplayed and then figure out differences, maybe i'll be able to improve current script or create some extra options 
> 
> Remaining question: what should be the default behavior?
> 
When i'm thinking about that... i would say better to save it like it was in previous versions of wdio by default for backward compatibility and as you've suggest to add some options for changing behavior if current version don't satisfied users needs.

Please assign the task to me when it'll be available.

**Comment by christian-bromann** [comment]
I went ahead and raised a [v9 PR](https://github.com/webdriverio/webdriverio/pull/11857) to merge the commands. Sorry @udarrr I didn't recognised you wanted to work on this. Would you be interested picking up a different task for v9?

I think there is nothing actionable here anymore, so I will go ahead and close. Let me know if I am wrong, i am happy to re-open.

**Comment by udarrr** [comment]
@christian-bromann I am ok with that :) don't worries. Maybe just one suggestion here. Does it make sense to deprecate isDisplayedInViewport in V8 ?

**Comment by christian-bromann** [comment]
@udarrr yes, I was thinking about it .. mind raising a PR?

**Comment by jedwards1211** [comment]
@christian-bromann the removal of `isDisplayedViewport` isn't documented in the v9 release notes

**Comment by christian-bromann** [comment]
@jedwards1211 thanks for pointing this out, just pushed a commit with an update!
