### ISSUE TITLE
[🐛 Bug]: isDisplayed isn't working as expected JSOWP vs W3C

### ISSUE THREAD

**Issue by udarrr** [webdriverio/webdriverio#11770]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

18

### Mode

Standalone Mode

### What happened?

Current one implementation is using the condition

```
    const isNativeApplication = !(browser.capabilities as WebdriverIO.Capabilities).browserName
    if (browser.isMobile && isNativeApplication) {
        return await this.isElementDisplayed(this.elementId)
    }

    return await browser.execute(isElementDisplayedScript, {
        [ELEMENT_KEY]: this.elementId, // w3c compatible
        ELEMENT: this.elementId // jsonwp compatible
    } as any as HTMLElement)
```

previous one this one

```
    const useAtom = (
        await browser.isDevTools ||
        (
            await browser.isW3C &&
            !browser.isMobile &&
            noW3CEndpoint.includes((browser.capabilities as WebdriverIO.Capabilities).browserName?.toLowerCase()!)
        )
    )

    return useAtom
        ? await browser.execute(isElementDisplayedScript, {
            [ELEMENT_KEY]: this.elementId, // w3c compatible
            ELEMENT: this.elementId // jsonwp compatible
        } as any as HTMLElement) :
        await this.isElementDisplayed(this.elementId)
```

it seems JSOWP rely on isElementDisplayed and it's worked as expected but w3c protocol rely on isElementDisplayedScript that is just fork of isElementDisplayed. 

### What is your expected behavior?

isElementDisplayedScript seems is just fork of isElementDisplayed. At the same moment isElementDisplayed have a different result than isElementDisplayedScript because it seems isElementDisplayedScript don't care about intoView
isElementDisplayed check if element intoView. I'd like to suggest to use isElementDisplayed by default for both JSONWP and W3C as it's working as expected and isElementDisplayedScript with checking intoView when it's only browser.isDevTools

something like that

```
    return browser.isDevTools
        ? await browser.execute(isElementDisplayedScript, {
            [ELEMENT_KEY]: this.elementId, // w3c compatible
            ELEMENT: this.elementId // jsonwp compatible
        } as any as HTMLElement) :
        await this.isElementDisplayed(this.elementId)
```

### How to reproduce the bug.

execute isDisplayed for JSOWP and W3C

### Relevant log output

```typescript
isElementDisplayedScript don't care about intoView
isElementDisplayed check if element intoView
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by udarrr** [comment]
related to https://github.com/webdriverio/webdriverio/issues/11766

**Comment by erwinheitzman** [comment]
The JSON wire implementation is going to be removed as it has been deprecated for years. If you run into situations where it is still used you can change this ticket with that instead.

**Comment by erwinheitzman** [comment]
Also the code you shared is incorrect as it is old, this is the current code https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/element/isDisplayed.ts

**Comment by erwinheitzman** [comment]
Closing this as there's no issues described and the examples are old. Feel free to ask questions on Discord or you can create a new issue with the problems you are experiencing (but first update to the latest version)
