### ISSUE TITLE
Chrome is not loading a window but responding it finished testing in 0.Xs

### ISSUE THREAD

**Issue by jltCoding** [webdriverio/webdriverio#1177]
I am simply trying to get the chrome browser to work, but it doesn't seem to load. It always finishes in 0.X amount of seconds i.e.(0.4s, 0.9s etc). It also is clearly not running through the entire code. Any thoughts of what to do or what could be causing this?

var webdriverio = require('webdriverio');
var options = {
    desiredCapabilities: {
        browserName: 'chrome'
    }
};

webdriverio
    .remote(options)
    .init()
    .url('http://www.google.com')
    .getTitle().then(function(title) {
        console.log('Title was: ' + title);
    })
    .pause(2000)
    .end();

**Comment by christian-bromann** [comment]
@jltCoding check out if the init command throws an error by adding a catch method after it. I bet you haven't installed the chromedriver properly. Switch to firefox and it should work.

**Comment by jltCoding** [comment]
Yeah it works easily on firefox and safari. I am just trying to get chrome working as well. I am still pretty new at all of this and I am having a hard time finding examples for catch methods with webdrivio, I keep only finding regular webdriver exceptions.

**Comment by christian-bromann** [comment]
To get the error message do:
```js
var webdriverio = require('webdriverio');
var options = {
    desiredCapabilities: {
        browserName: 'chrome'
    }
};

var client = webdriverio.remote(options);
client
    .init().catch(console.log)
    .url('http://www.google.com')
    .getTitle().then(function(title) {
        console.log('Title was: ' + title);
    })
    .pause(2000)
    .end();
```
Each command is just a usual promise. You need to install chromedriver properly to run Chrome tests

**Comment by jltCoding** [comment]
@christian-bromann  Great thanks! I'm trying to figure out what I did wrong on the chromedriver side now. Thanks again
