### ISSUE TITLE
[💡 Feature]: scrollIntoView improving

### ISSUE THREAD

**Issue by udarrr** [webdriverio/webdriverio#11792]
### Is your feature request related to a problem?

improving

### Describe the solution you'd like.

I've tested some functionality with 'compute' from 'compute-scroll-into-view' package for scrollIntoViiew. It's working marvelous with 'wheel', I finally comprehend the action), all attempts were accurate, even in cases where web scrollIntoView can't be performed because of overview: hidden or where can be used only scrollLeft or scrollTop. It's working in iframes as well. It also provides cords for nested scrolls of element if it's needed, and can be scrolling all of them in one attempt with actions for of loop.

I'd like to suggest to investigate a bit, weight pros and cons and if it makes sense i can create worked an example for wdio.

it could be something like that
```javascript
let cords = browser.execute(compute,{[ELEMENT_KEY]: this.elementId}, options)
const actions = browser.action('wheel')

for(let cord of cords){
const elm = await browser.$(coord.el);
action.scroll({duration:0, deltaX: Math.round(cord.left), deltaY: Math.round(cord.top), origin: elm)
}
await action.perform();
```

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Thanks for raising the PR!

Mind sharing what problem you are trying to resolve here?

**Comment by udarrr** [comment]
Initially it's issue with scrolling for **overview: hidden** elements it's worked as expected in the case, but the package can't calculate iframes properly... that's why i don't think it makes a big sense to proceed with that
