### ISSUE TITLE
Polling for getText() and similar methods?

### ISSUE THREAD

**Issue by dcosson** [webdriverio/webdriverio#1179]
First off, thanks for maintaining this library and for all the quick and helpful responses on issues. I've been really enjoying webdriverio.

I'm using the v4 api, with jasmine.

Is there a built-in method for polling the browser for dom changes? I'm testing an ajax heavy site so a lot of interactions happen asynchronously, and I wrote my own helper to poll using `getText()` and similar methods until a given timeout.

The issue is, when getText doesn't find an element it raises an exception and triggers the `onError` callback. In this context it's not actually an error until it reaches the timeout, so it's making my test output noisy and taking a bunch of unnecessary screen shots (even when I wrap it in a try/catch). I'm just wondering if there's a better way to do what I'm trying to do.

**Comment by christian-bromann** [comment]
@dcosson you can do an isExisting check before you call getText meaning that you only call getText if that element actually exists

**Comment by dcosson** [comment]
@christian-bromann That doesn't cover every case though. For instance, sometimes the element already exists on the page but it has a different value (an empty state or previous value) which asynchronously updates to the expected value. 

Would you accept a patch that updates getText to return `null` if the selector isn't found rather than throw an exception? 

With the current behavior, I can't fully catch the exception in my code, it still takes the error screenshot if I catch an exception. So an alternative fix would be maybe to continue having `getText` raise exceptions but do the automatic screenshot higher up the stack to give the user's code a chance to catch any thrown exceptions.

What do you think?

**Comment by christian-bromann** [comment]
> Would you accept a patch that updates getText to return null if the selector isn't found rather than throw an exception?

No because you can check if the selector you are about to use exists on the page.

I don't quite get what is the problem of using `isExisting` to check if the element is available. Maybe provide an example test spec to describe your case.

**Comment by dcosson** [comment]
Sure, I guess I can poll for `isExisting` and then poll for `getText` everywhere I need to, it would just be nice if it were possible in one command instead of two.

**Comment by christian-bromann** [comment]
> With the current behavior, I can't fully catch the exception in my code

I don't understand that. In v4 you can just try catch to prevent the test case from failing like

```js
it("...", function() {
    var text = null;
    try {
        text = browser.getText(selector);
    catch (e) {
        // element wasn't found
    }
    // ...
})
```

**Comment by dcosson** [comment]
Right, the test can still pass but it's still taking automatic screenshots even when I catch the exception. Not a huge deal, it just makes the test output noisier.

**Comment by christian-bromann** [comment]
ahh I see, well I can't check if you have put the command within a try catch block so yeah I guess you have to life with it then (if you don't want to use `isExisting`)
