### ISSUE TITLE
"Cannot read property 'log' of undefined" for crashes 

### ISSUE THREAD

**Issue by graingert** [webdriverio/webdriverio#1180]
In some errors I often get "Cannot read property 'log' of undefined"

https://github.com/graingert/wdio-console-log-crash/tree/master

**Comment by eyalzek** [comment]
I'm getting this also in a lot of the errors. Coming from line 287 of webdriverio.js:
`this.logger.log('\tSaved screenshot: ' + fileName);`

**Comment by christian-bromann** [comment]
Already working on fixing this :wink:

**Comment by eyalzek** [comment]
Can you please explain how to fix this manually in the meantime? It causes too many crashes in my tests..

**Comment by molily** [comment]
@eyalzek I monkey-fixed this locally by putting an `if (this.logger)` around the `this.logger.log` call. There might be a better way. 🐵
https://github.com/webdriverio/webdriverio/blob/master/lib/webdriverio.js#L220
