### ISSUE TITLE
[🐛 Bug]: TypeError: globals.get(...)[matcher] is not a function

### ISSUE THREAD

**Issue by erwinheitzman** [webdriverio/webdriverio#11817]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

18

### Mode

WDIO Testrunner

### What happened?

I get an error: `TypeError: globals.get(...)[matcher] is not a function`

### How to reproduce the bug.

Initiate a new project (Jasmine and Typescript was chosen in my case) with the latest versions and I use the new matchers like so:
```js
        await expect(SecurePage.flashAlert).toHaveText(expect.stringContaining(
            'You logged into a secure area!'))
```

### Relevant log output

```typescript
TypeError: globals.get(...)[matcher] is not a function
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@erwinheitzman in Jasmine you would usually do:

```ts
        await expect(SecurePage.flashAlert).toHaveText(jasmine.stringContaining(
            'You logged into a secure area!'))
```

However I think making this more compatible make sense to us, so I raised a PR.
