### ISSUE TITLE
[💡 Feature]: Add missing browserStack's Capabilities

### ISSUE THREAD

**Issue by thiru-mohan** [webdriverio/webdriverio#11836]
### Is your feature request related to a problem?

**networkLogsIncludeHosts** and **networkLogsIncludeHosts** capabilities are not available to use from the **BrowserStackCapabilities** interface in the run configuration file. 

Link to the BrowserStack NetworkLogs Capabilities - https://www.browserstack.com/docs/app-automate/appium/debug-failed-tests/network-logs

### Describe the solution you'd like.

To add the missing capabilities in the BrowserStackCapabilities interface. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
This has been merged and will be released with the upcoming version. Thanks @Vaahin for the contribution!
