### ISSUE TITLE
[🐛 Bug]: Jasmine - Skipping a test in beforeTest global hook is not preventing the test runner from executing the entire test code

### ISSUE THREAD

**Issue by HananArgov** [webdriverio/webdriverio#11834]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.26.0

### Node.js Version

18.12.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
      browserName: 'chrome',
      browserVersion: 'stable', // or 'stable', 'beta', 'dev' or 'canary'
      acceptInsecureCerts: true,
    },
```

### What happened?

when adding 
`pending('skip message')`
to the `beforeTest` hook in the config, it will not skip the test, and will continue the test

### What is your expected behavior?

to skip the test.
there was a fix for mocha, i've tried to do the same for Jasmine, but the reject will fail the test.
https://github.com/webdriverio/webdriverio/issues/6645

### How to reproduce the bug.

install wdio with the testrunner, and Jasmine.

in the config file add the following:

```
  beforeTest(test, context) {
    pending('test 123');
  },
```

### Relevant log output

```typescript
getting this from log:

[0-0] 2023-12-10T10:01:44.372Z ERROR @wdio/utils:shim: undefined
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by HananArgov** [comment]
somehow, i've found the solution (I think)
i'm using the same solution that was used for Mocha, and I add a reason to the reject:

```
            if (/^=> marked Pending/.test(e)) {
                return reject(e);
            }
```

the result is

```
 "spec" Reporter:
------------------------------------------------------------------
[firefox 64 mac #0-0] Running: firefox (v64) on mac
[firefox 64 mac #0-0] Session ID: 4b936dd8-3369-49e8-b002-c6464e5797e7
[firefox 64 mac #0-0]
[firefox 64 mac #0-0] » /e2e-specs/test/specs/example.api.ts
[firefox 64 mac #0-0] example
[firefox 64 mac #0-0]    - skipped test
[firefox 64 mac #0-0]
[firefox 64 mac #0-0]       .........Pending Reasons.........
[firefox 64 mac #0-0]          test 123
[firefox 64 mac #0-0]
[firefox 64 mac #0-0] 1 skipped (2.7s)
```

**Comment by christian-bromann** [comment]
Closing, thanks @HananArgov for the fix!
