### ISSUE TITLE
[🐛 Bug]: Missing types for UiAutomator2 capabilities

### ISSUE THREAD

**Issue by GP-QA** [webdriverio/webdriverio#11830]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

v18.13.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
export const config: Options.Testrunner = {
  runner: 'local',
  autoCompileOpts: {
    autoCompile: true,
    tsNodeOpts: {
      project: './tsconfig.json',
      transpileOnly: true
    }
  },
  specs: ['./features/**/*.feature'],
  exclude: [
    // 'path/to/excluded/files'
  ],
  maxInstances: 1,

  capabilities: {
    app: {
      capabilities: {
      platformName: 'Android',
      'appium:app': 'app/android/app-debug.apk',
      'appium:udid': 'removed for bug ticket',
      'appium:automationName': 'UiAutomator2',
      'appium:newCommandTimeout': 240,
      'appium:hideKeyboard': true,
      'appium:autoWebview': true,
      'appium:autoWebviewName': 'WEBVIEW_chrome'
      }
    },
    chrome: {
      capabilities: {
        browserName: 'chrome'
      }
    }
  },
...
```

### What happened?

The capabilities appium:hideKeyboard and appium:autoWebviewName are missing in import type { Options } from '@wdio/types';
I use WebDriverIO, Appium, Cucumber, language: Typescript.

In file wdio.android.conf.ts I get the error: 
Type 'string' is not assignable to type 'WebdriverIO'.ts(2322)
(property) 'appium:autoWebviewName': string

I have added @wdio/types (latest version) in the package.json.

I don't see the two capabilities in node module file @wdio\types\build\Capabilities.d.ts 

### What is your expected behavior?

The two capabilities are known in the capabilities of @wdio/types

### How to reproduce the bug.

Use the indicated config.

### Relevant log output

```typescript
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment]
@christian-bromann I want to suggest adding appium as a dev dependency to take the types from the project and apply them. Do you think this would work and is a good idea? This way the types will be maintained by them and used by us

**Comment by erwinheitzman** [comment]
@GP-QA thank you for reporting 🙂

**Comment by christian-bromann** [comment]
Yes there are some files written in TypeScript but the majority is in plain JS. I know that the team decided to move to JSDoc comments and won't do more work on porting code to TypeScript. I scanned the whole Appium project and couldn't find any capabilities defined anywhere.

**Comment by christian-bromann** [comment]
> The capabilities appium:hideKeyboard and appium:autoWebviewName are missing in import type { Options } from '@wdio/types';

@GP-QA can you link us some docs to the capabilities?

**Comment by GP-QA** [comment]
> > The capabilities appium:hideKeyboard and appium:autoWebviewName are missing in import type { Options } from '@wdio/types';
> 
> @GP-QA can you link us some docs to the capabilities?

No problem: https://github.com/appium/appium-uiautomator2-driver#adb

**Comment by GP-QA** [comment]
> @GP-QA thanks, are you interested adding these types to WebdriverIO through a PR?

I am not a developer. So I think it will be too difficult for me.

**Comment by erwinheitzman** [comment]
> Yes there are some files written in TypeScript but the majority is in plain JS. I know that the team decided to move to JSDoc comments and won't do more work on porting code to TypeScript. I scanned the whole Appium project and couldn't find any capabilities defined anywhere.

It is possible that the types are generated on release as typescript supports Jsdoc type notation and can generate types from them. I can do a quick search for it too and will report back 🙂

**Comment by christian-bromann** [comment]
This has been merged and will be released with the upcoming version.

**Comment by wswebcreation** [comment]
@berekmerilorand 

As mentioned in the logs, this is a known limitation in Appium, not WDIO. This even comes from Apple, not from Appium because it's a limitation in the Apple XCUITest runner used in the `appium-xcuitest-driver`.

You can overcome this by clicking:
1. outside of the keyboard, see [this](https://github.com/webdriverio/appium-boilerplate/blob/main/tests/screenobjects/LoginScreen.ts#L43) example (by the way, the complete boilerplate is updated with new tips, tricks and best practices)
2. click on the `done` button of the keyboard

My advice would be to go for option 1, because then you are not dependent on the language of the keyboard/the OS version that has an impact on what is shown on a keyboard
