### ISSUE TITLE
[💡 Feature]: Update all dependencies

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#11858]
### Is your feature request related to a problem?

The following dependencies haven't been updated due to our restriction to keep support for Node.js v16:
```json
    # these packages don't support Node.js v16 anymore
    - dependency-name: "got"
    - dependency-name: "ky"
    - dependency-name: "@octokit/rest"
    - dependency-name: "@cucumber/cucumber"
    - dependency-name: "jsdom"
```

Now that we drop Node.js v16 support we can update these.

### Describe the solution you'd like.

Update the following dependencies in their respective packages:

- `@octokit/rest`
- `@cucumber/cucumber`
- `jsdom`

Note: `got` and `ky` don't need updates as we replace them for Node.js fetch.

### Describe alternatives you've considered.

n/a

### Additional context

This is a v9 task and pull requests should be raised against the [`v9`](https://github.com/webdriverio/webdriverio/tree/v9) branch. Join the `🙏-contribute` channel on [Discord](https://discord.webdriver.io) if you are interested to join us in this effort.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tech-dm-klymenko** [comment]
I will take this task
