### ISSUE TITLE
Empty 'browserName' capability gets overridden with 'firefox'

### ISSUE THREAD

**Issue by tebs1200** [webdriverio/webdriverio#1185]
I'm attempting to use webdriverio with Appium to automate native apps, but in order to have Appium launch a native app instead of a browser, the `browserName` capability needs to be set to an empty string.

When passing a configuration object into the `remote` method that contains an empty string, this gets changed to 'firefox' somehow. Example object:

    var driverOptions = {
        desiredCapabilites: {
            browserName: '',
            platformName: 'iOS',
            deviceName: 'iPhone 5s'
        }
    }

**Comment by christian-bromann** [comment]
You need to specify an `app` property! This way WebdriverIO believes you still want to do browser testing.

**Comment by tebs1200** [comment]
Thanks christian. I was adding the `app` as a capability when calling `init`during a later stage. Looks like i need to add the `app` when I initially call `remote`.
