### ISSUE TITLE
💡 Feature: Enhance the sharding command to available suites under "suites" tag in conf file(s)

### ISSUE THREAD

**Issue by umer-ali-khan** [webdriverio/webdriverio#11869]
### Is your feature request related to a problem?

Currently sharding is applicable to "specs" tag in conf file
example: 
npx run wdio wdio.conf.tdd.js -- --shard 1/2 >>>> it will shard "specs" tag in conf file

but if I have 30 suites, then above command will require me to mention the suites for which I need sharding. 
Like

npx run wdio wdio.conf.tdd.js -- --shard 1/2 --suite suite1 suite2 suite3 ....

but it requires me to mention suite names.

### Describe the solution you'd like.

Ask: There should be mechanism where we just tell wdio to shard all suites without providing the list of suites.

npx run wdio wdio.conf.tdd.js -- --shard 1/2 --suites true  >>> should shard suites
npx run wdio wdio.conf.tdd.js -- --shard 1/2 --specs true  >>> should shard specs

### Describe alternatives you've considered.

For sharding suites, I need to provide the full list of suites mentioned under "suites" tag in conf file

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
@umer-ali-khan thanks for raising an issue. More clarity, let's say I have 3 suites defined in my config, e.g.:

```ts
export const config = {
    // ...
    suites: {
        suiteA: [...],
        suiteB: [...],
        suiteC: [...],
    }
    // ...
}
```

If I run `npx run wdio wdio.conf.tdd.js -- --shard 1/3 --suites` you would expect to basically run `npx run wdio wdio.conf.tdd.js -- --suite suiteA` right?

**Comment by erwinheitzman** [comment]
We shouldn't forget you can combine running suites and specs together as well

**Comment by umer-ali-khan** [comment]
> @umer-ali-khan thanks for raising an issue. More clarity, let's say I have 3 suites defined in my config, e.g.:
> 
> ```ts
> export const config = {
>     // ...
>     suites: {
>         suiteA: [...],
>         suiteB: [...],
>         suiteC: [...],
>     }
>     // ...
> }
> ```
> 
> If I run
> 
> * `npx run wdio wdio.conf.tdd.js -- --shard 1/3 --suites` you would expect to basically run `npx run wdio wdio.conf.tdd.js -- --suite suiteA`
> * `npx run wdio wdio.conf.tdd.js -- --shard 2/3 --suites` you would expect to basically run `npx run wdio wdio.conf.tdd.js -- --suite suiteB`
> * `npx run wdio wdio.conf.tdd.js -- --shard 3/3 --suites` you would expect to basically run `npx run wdio wdio.conf.tdd.js -- --suite suiteC`
> 
> right?

Yes that is true. But as @erwinheitzman mentioned it will bring more complexity when we run specs and suites. But as far as we are separating specs and suites (through command) it should not be a problem and I guess mixing specs and suites together can be done like that

npx run wdio wdio.conf.tdd.js -- --shard 1/2 --specs true --suites true  >>>> shall shard both

**Comment by christian-bromann** [comment]
> npx run wdio wdio.conf.tdd.js -- --shard 1/2 --specs true --suites true >>>> shall shard both

Can you explain in an example?

**Comment by umer-ali-khan** [comment]
export const config = {
    // ...
specs: ['./test/specs/spec1.spec.js', './test/specs/spec2.spec.js', './test/specs/spec3.spec.js'],
    suites: {
        suiteA: [...],
        suiteB: [...],
        suiteC: [...],
    }
    // ...
}


and run following 

expected:
npx run wdio wdio.conf.tdd.js -- --shard 1/3 --suites --specs you would expect to basically run npx run wdio wdio.conf.tdd.js -- --suite suiteA --spec spec1
npx run wdio wdio.conf.tdd.js -- --shard 2/3 --suites you would expect to basically run npx run wdio wdio.conf.tdd.js -- --suite suiteB  --spec spec2
npx run wdio wdio.conf.tdd.js -- --shard 3/3 --suites you would expect to basically run npx run wdio wdio.conf.tdd.js -- --suite suiteC  --spec spec3

**Comment by christian-bromann** [comment]
Config files are unlikely specified like that. It mostly resolves to:

```ts
export const config = {
    // ...
    specs: ['./test/**/*.spec.js'], // could be 100 files
    suites: {
        suiteA: [...],
        suiteB: [...],
        suiteC: [...],
    }
    // ...
}
```

to what would `npx run wdio wdio.conf.tdd.js -- --shard 1/3 --suites --specs` then resolve to?

**Comment by umer-ali-khan** [comment]
> Config files are unlikely specified like that. It mostly resolves to:
> 
> ```ts
> export const config = {
>     // ...
>     specs: ['./test/**/*.spec.js'], // could be 100 files
>     suites: {
>         suiteA: [...],
>         suiteB: [...],
>         suiteC: [...],
>     }
>     // ...
> }
> ```
> 
> to what would `npx run wdio wdio.conf.tdd.js -- --shard 1/3 --suites --specs` then resolve to?

it should resolve to first 33% of specs and suites

**Comment by christian-bromann** [comment]
@umer-ali-khan @erwinheitzman can you provide some more feedback here? I am still a bit confused about this usecase. Right now, WebdriverIO can't run specs __and__ suites if your call e.g. `wdio run wdio.conf.ts --suite foobar` , you can only pass in a specs via parameter when you use the `--suite` param, e.g. `wdio wdio.conf.js --suite login --spec ./test/specs/signup.js`.

I don't think there is a use case where someone would like to run all suites and all specs as defined in the spec. The original idea of specs and suites here is that you would define all e2e test files via the `spec` property and would group spec files of a certain feature within a suite, so that you can e.g. run only certain login tests via `wdio run wdio.conf.ts --suite login`. This means that it is very likely that specs defined in some of the suites are also included in the glob of the `specs` property.

If anyone could shed some light into additional use cases that would be very helpful!

**Comment by umer-ali-khan** [comment]
The actual ask for this ticket was to shard suites. Sharding for specs is available but not for suites. @christian-bromann you are right general use case would be to execute suites with given names. Should we implement sharding on suites level that is a question

**Comment by christian-bromann** [comment]
@umer-ali-khan thanks for the feedback, you've mentioned above that:

```sh
npx run wdio wdio.conf.tdd.js -- --shard 1/2 --suite suite1
```

Already works right? What is the exact feature you would like to see?
