### ISSUE TITLE
[🐛 Bug]: Unable to Customize 'it' Function Using 'require' Option in mochaOpts

### ISSUE THREAD

**Issue by yarinsa** [webdriverio/webdriverio#11863]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.24.12

### Node.js Version

18.5

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
[0-1]   desiredCapabilities: {
[0-1]     browserName: 'chrome',
[0-1]     'goog:chromeOptions': {
[0-1]       binary: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
[0-1]       args: []
[0-1]     },
[0-1]     'LT:Options': {
[0-1]       platformName: 'Windows 11',
[0-1]       build: 'https://app.linxstg.net',
[0-1]       video: true,
[0-1]       network: true,
[0-1]       console: 'true',
[0-1]       project: 'console',
[0-1]       visual: true,
[0-1]       tunnel: true,
[0-1]       buildTags: [Array],
[0-1]       seCdp: true,
[0-1]       selenium_version: '4.13.0'
[0-1]     }
[0-1]   }
[0-1] }
```

### What happened?

Problem:
I am attempting to customize the global it function in WebdriverIO (WDIO) using the require option within the mochaOpts configuration in my wdio.conf.js file. My goal is to add a custom it.flag functionality for feature flags testing. However, I'm encountering issues with accessing the test context and adding this custom behavior.

### What is your expected behavior?

I expect that the custom it.flag functionality defined in customIt.js should be accessible and usable within my test files, allowing me to customize test behavior for feature flag testing.

### How to reproduce the bug.

Steps to Reproduce:

1. Create a JavaScript file that defines a custom it function with extended behavior, such as it.flag, similar to the following:

```
// customIt.ts

global.it = function customIt(testName, testFunction) {
  // Custom logic here, including it.flag functionality
};
```

2. Update the wdio.conf.js file to include the require option in the mochaOpts configuration:
```
// wdio.conf.ts

exports.config = {
  // Other WDIO configuration settings...
  
  mochaOpts: {
    require: ['./path/to/customIt.ts'], // Specify the path to your custom it function file
    // Other Mocha options...
  },
  
  // Other WDIO configuration settings...
};
```
3. Attempt to use the custom it.flag functionality in your test files (e.g., spec files).

### Relevant log output

```typescript
x
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment]
This can be done like so:
```js
// wdio.conf.js
    beforeTest: function (test, context) {
        context.foo = 'foobar'
    },
```
```js
// test.js
    it('logs "foobar"', async function() {
        console.log(this.foo) // note that you cannot use arrow functions when accessing the `this` scope
    })
```

**Comment by yarinsa** [comment]
> @yarinsa I feel like we can close the issue but am awaiting your response

Thanks for the quick response, and sorry for bothering I will give it a shot tmrw and update back

**Comment by christian-bromann** [comment]
@yarinsa I will go ahead and close this, please let me know if you still run into issues and I am happy to re-open.
