### ISSUE TITLE
[💥 Breaking] Remove the `devtools` package as it requires a lot of maintenance and has no real value anymore

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#11860]
The `devtools` package has been used to automate WebdriverIO through Puppeteer. Back in the days this was useful because Puppeteer helped with setting up Chrome. Today this is done by WebdriverIO and there is no real value anymore to run automation through CDP rather than WebDriver. In fact there are a lot of bugs where the expected automated behavior was not met due to CDP specifics that we were never able to fix e.g. switching windows and run commands in them.

Moving on it makes most sense to remove this capability and force users to use WebDriver. We will use the `devtools` package for a different project.

This is a v9 task and pull requests should be raised against the [`v9`](https://github.com/webdriverio/webdriverio/tree/v9) branch. Join the `🙏-contribute` channel on [Discord](https://discord.webdriver.io) if you are interested to join us in this effort.

**Comment by gromanas** [comment]
This (hopefully) will be my first contribution to wdio. If it is ok I want to give a try on this.

**Comment by christian-bromann** [comment]
@gromanas thanks for picking this up. Can you do me a favor and also raise a PR against `main` to add a deprecation notice to the `devtools` package and to its driver, so people will know, it will be removed. Thank you!

**Comment by gromanas** [comment]
> @gromanas thanks for picking this up. Can you do me a favor and also raise a PR against `main` to add a deprecation notice to the `devtools` package and to its driver, so people will know, it will be removed. Thank you!

Not in a pc at the moment. Will do this asap.

**Comment by gromanas** [comment]
@christian-bromann what I should include in this PR as it will be against `main` and not `v9` branch? Shall I make any changes and then open the PR? Please provide any info. Thank you in advance!

**Comment by christian-bromann** [comment]
Please make two separate PRs:

- one that adds deprecation notices for `devtools` -> PR against `main` branch
- one that removes the `devtools` package -> PR against `v9` branch

**Comment by rsinghi** [comment]
Is devtools service is being deprecated, what is the recommended approach to capture browser traffic in WDIO tests?

**Comment by christian-bromann** [comment]
@rsinghi with Bidi support around the corner we will have cross browser support for it natively in WebdriverIO soon. Today, you can already use the `getPuppeteer` command to access the CDP interface for network logging.

**Comment by christian-bromann** [comment]
I will take on the next step which is removing the package from this repo.

**Comment by Jabbar2010** [comment]
when will the v9 be released?

> @rsinghi with Bidi support around the corner we will have cross browser support for it natively in WebdriverIO soon. Today, you can already use the `getPuppeteer` command to access the CDP interface for network logging.

And I also want to know how to intercept network, is there a workaround with webdriver way?

**Comment by Jabbar2010** [comment]
@christian-bromann I found in the document
"INFO
Note that using the mock command requires support for Chrome DevTools protocol. That support is given if you run tests locally in Chromium based browser or if you use a Selenium Grid v4 or higher. This command can not be used when running automated tests in the cloud. Find out more in the [Automation Protocols](https://webdriver.io/docs/automationProtocols) section."

It said the cmd requires CDP, but I don't understand: if the browser should support CDP or if we have to use "devtools" for "automationProtocol". Do Safari, Firefox browsers support "mock"?

**Comment by Jabbar2010** [comment]
And I found another answer from you @christian-bromann : https://github.com/webdriverio/webdriverio/issues/2759#issuecomment-394275596

If I use mock API, and I want to modify the HTTP request headers. You mean the "headers" in the mock API are just for selenium server requests not for the browser. So what can I do?

**Comment by christian-bromann** [comment]
> Do Safari, Firefox browsers support "mock"?

Not right now but they will in the future through Bidi. I am currently implementing Bidi support for the mock command in v9 and it will allow cross browser mocking using the same interface.

> So what can I do to modify the request header?

I will enhance the `mock` command to allow something like this:

```ts
const mock = await browser.mock('/some/path', {
  requestWith: {
    // set request header
    header: {
      'x-foo': 'bar'
    }
  }
})

// keep response but update response headers
mock.response(null, {
  header: {
    'x-bar': 'foo'
  }
})
```

What do you think?

**Comment by christian-bromann** [comment]
> they're not compatible for all browsers

The idea of WebdriverIO is that all commands work the same way in all browser. Unfortunately as browser adopt the new Bidi standard, we have different progress on certain APIs which will hopefully resolve itself some day. In the past we enabled these features by using Chrome DevTools (which only works for Chrome and Edge in most cases) but with Bidi we move away from that. That said, network interception will work the same way across browser once these features land. I am currently running interception tests successfully in Canary and I expect this to work in FF Nightly soon as well. I can't speak about Safari, except that they plan to implement it.

> And BTW, want to know when v9 will be released.

You can already use v9 today using the `@next` tag. As we aren't as careful shipping breaking changes I recommend maybe pin the version to ensure your tests are stable.

**Comment by Jabbar2010** [comment]
Wow! very quick response, thanks, @christian-bromann , we have lots of questions about Webdriverio, but maybe here is not a good place to ask.

**Comment by Jabbar2010** [comment]
Sorry, I forgot an important feature of network intercept is Websocket, does it support? @christian-bromann

**Comment by christian-bromann** [comment]
> but maybe here is not a good place to ask.

Join our [Discord](https://discord.webdriver.io) server and ask away 😉 

> I forgot an important feature of network intercept is Websocket, does it support?

This currently does not seem to be supported by the protocol but is something we can implement in WebdriverIO via script injection. I will create a feature request for this.
