### ISSUE TITLE
[💡 Feature]: revamp Lighthouse integration

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#11861]
### Is your feature request related to a problem?

We currently maintain a `@wdio/devtools-service` that provides various integration to Chrome Devtools related features:

- [Performance Testing](https://webdriver.io/docs/devtools-service#performance-testing)
- [Device Emulation](https://webdriver.io/docs/devtools-service#device-emulation)
- [PWA Testing](https://webdriver.io/docs/devtools-service#pwa-testing)
- [Code Coverage Capturing](https://webdriver.io/docs/devtools-service#capture-code-coverage)
- [Chrome DevTools Access](https://webdriver.io/docs/devtools-service#chrome-devtools-access)

As we deeper integrated Puppeteer into WebdriverIO using the `getPuppeteer` command there is not much use for the original use case of this package anymore. Most development and excitement has been around its Lighthouse integration. Therefor it makes sense to focus on that and remove the rest.

### Describe the solution you'd like.

Rename `@wdio/devtools-service` to `@wdio/lighthouse-service` and remove everything except features around Performance and PWA testing.

### Describe alternatives you've considered.

n/a

### Additional context

This is a v9 task and pull requests should be raised against the [`v9`](https://github.com/webdriverio/webdriverio/tree/v9) branch. Join the `🙏-contribute` channel on [Discord](https://discord.webdriver.io) if you are interested to join us in this effort.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by goosewobbler** [comment]
I took a brief look at this, would the following be correct?  I'll update these lists as required.

Removed Functionality

- `browser.getCoverageReport` & service options - code coverage
- `browser.cdp` - devtools access
- `browser.getNodeId` - devtools helper
- `browser.getNodeIds` - devtools helper
- `browser.on` (emitting CDP events) - devtools access

Retained Functionality

- `browser.enablePerformanceAudits` - perf testing
- `browser.disablePerformanceAudits` - perf testing
- `browser.getMetrics` - perf testing
- `browser.getPerformanceScore` - perf testing
- `browser.getDiagnostics` - perf testing
- `browser.getMainThreadWorkBreakdown` - perf testing
- `browser.startTracing` - perf testing
- `browser.endTracing` - perf testing
- `browser.getTraceLogs` - perf testing
- `browser.getPageWeight` - perf testing
- `browser.checkPWA` - PWA testing
- `browser.emulateDevice`- device emulation

The next 10-14 days is very busy for me, I'm unlikely to get a PR up for at least a week but happy to do so when things ease off.

**Comment by christian-bromann** [comment]
> I took a brief look at this, would the following be correct?

That is correct. Let me know if you like to use #12300 as a base or prefer to start from scratch.

> The next 10-14 days is very busy for me, I'm unlikely to get a PR up for at least a week but happy to do so when things ease off.

No worries, appreciate the help a lot!

**Comment by goosewobbler** [comment]
Thanks for that.  I'll start from scratch seeing as there's a few merge conflicts.

**Comment by christian-bromann** [comment]
@goosewobbler I got myself push the PR over the goal line!

**Comment by goosewobbler** [comment]
That's great - sorry I've not had much time recently...

**Comment by christian-bromann** [comment]
No worries!
