### ISSUE TITLE
[🐛 Bug]: Inconsistency between the result displayed in the console, the total number of testcases executed and the documentation

### ISSUE THREAD

**Issue by carri747** [webdriverio/webdriverio#11867]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.22.0

### Node.js Version

18.15.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [
        {
            browserName: 'chrome'
        }
    ],
```

### What happened?

Hi everyone and thanks in advance for the help.

I notice a inconsistence in WDIO's result at the end of the process. 
I've a project with 3 test cases, one of them is executed in a worker (worker1) and the others in other worker (worker2), when the process end I've this result:
`Spec Files:      0 passed, 2 failed, 2 total (100% completed) in 00:00:08`
And it's not true because I've 3 test cases and not 2. 

In the official [doc  ](https://webdriver.io/docs/configurationfile/) in "onComplete"  hooks mentions very clear that the forth parameter is `@param {<Object>} results object containing test results` but make not sense with the previous result. The previous result, I think, that it's showing the worker's status and not test results. 
I've other example with test cases that pass:
4 Test cases, 2 test cases in a worker which results is pass and other 2 in other worker that one of the is pass and other fail 
Result: `Spec Files:      1 passed, 1 failed, 2 total (100% completed) in 00:00:08`

Other mistake in this result is: If I defined a retry parameter, for instance retry = 1, and in the second execution the test is success I've a fail in the result and the exit code is 1 instead of 0 because all the test were success

### What is your expected behavior?

The final result should show:
- the total number of test cases and not the total number of workers
- The correct state of the testcase regardless of the retry policy that is defined, and if the last attempt was success, count that result as success and not as failed
- Exit code 0 regardless of the retry policy, now the exit code is 1 if the test fail in the first attempt but it was success in the second execution

### How to reproduce the bug.

wdio.conf.ts
```
import type { Options } from '@wdio/types';
import AllureReporter from '@wdio/allure-reporter';
import * as fs from 'fs';
import RerunService from 'wdio-rerun-service';

export const config: Options.Testrunner = {
    runner: 'local',
    autoCompileOpts: {
        autoCompile: true,
        tsNodeOpts: {
            project: './tsconfig.json',
            transpileOnly: true
        }
    },
    specs: [['./features/worker1/*.feature'], ['./features/worker2/*.feature']],
    exclude: [],
    maxInstances: 1,
    capabilities: [
        {
            browserName: 'chrome'
        }
    ],
    logLevel: 'info',
    bail: 0,
    baseUrl: 'http://www.google.com',
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    services: [
        [
            RerunService,
            {
                rerunDataDir: './reRun',
                rerunScriptPath: './reRun/rerun.bat',
                customParameters: './wdio.conf.ts'
            }
        ]
    ],
    framework: 'cucumber',
    reporters: ['spec', ['allure', { outputDir: 'out/allure-result', useCucumberStepReporter: true }]],
    cucumberOpts: {
        require: ['./features/step-definitions/steps.ts'],
        backtrace: false,
        requireModule: [],
        dryRun: false,
        failFast: false,
        snippets: true,
        source: true,
        strict: false,
        timeout: 60000,
        ignoreUndefinedDefinitions: false,
        retry: 1
    },
    afterScenario: function (world, result, context) {},

    after: function (result, capabilities, specs) {}
};
```

stepDefinition.ts

```
import { Given, When, Then } from '@wdio/cucumber-framework';
import * as chai from 'chai';

Given(/^I am on the (\w+) page$/, async (page) => {
    await chai.expect(false).to.be.true;
});

When(/^I login with (\w+) and (.+)$/, async (username, password) => {});

Then(/^I should see a flash message saying (.*)$/, async (message) => {});
```

Feature1.feature, Feature2.feature, Featuer3.feature

```
Feature: The Internet Guinea Pig Website
  Scenario Outline: As a user, I can log into the secure area

    Given I am on the login page
    When I login with <username> and <password>
    Then I should see a flash message saying <message>

    Examples:
      | username | password             | message                        |
      | tomsmith | SuperSecretPassword! | You logged into a secure area! |

```

package.json

```
{
    "name": "my-new-project",
    "type": "module",
    "devDependencies": {
        "@wdio/allure-reporter": "^8.21.0",
        "@wdio/cli": "^8.22.1",
        "@wdio/cucumber-framework": "^8.22.0",
        "@wdio/local-runner": "^8.22.1",
        "@wdio/spec-reporter": "^8.21.0",
        "ts-node": "^10.9.1",
        "typescript": "^5.2.2"
    },
    "scripts": {
        "wdio": "wdio run ./wdio.conf.ts",
        "report:generate": "npm run restoreHistory && npx allure generate --clean ./out/allure-result/ -o ./out/allure-report && npm run saveHistory",
        "report:open": "npx allure open out/allure-report",
        "saveNewHistory": "copyfiles -f out/allure-report/history/*.json c:\\allureHistory",
        "restoreHistory": "copyfiles -f c:\\allureHistory\\*.json out/allure-result/history",
        "report": "npm run restoreHistory && npm run report:generate",
        "rerun": "call ./reRun/rerun.bat"
    },
    "dependencies": {
        "@types/node": "^20.9.0",
        "allure-commandline": "^2.24.1",
        "allure-cucumberjs": "^2.9.2",
        "chai": "^4.3.10",
        "copyfiles": "^2.4.1",
        "minimist": "^1.2.8",
        "wdio-rerun-service": "^2.0.7"
    }
}
```
Project's structure
![image](https://github.com/webdriverio/webdriverio/assets/22347831/922f8f11-d04c-4423-9e35-d44784f8f855)

Run this commando
`npm run wdio`

### Relevant log output

```typescript
[chrome 120.0.6099.71 windows #0-1]     -false
[chrome 120.0.6099.71 windows #0-1]     +true
[chrome 120.0.6099.71 windows #0-1]
[chrome 120.0.6099.71 windows #0-1]     at World.<anonymous> (file:///C:/Dev/git/testAllure/features/step-definitions/steps.ts:5:35)
[chrome 120.0.6099.71 windows #0-1]     at Object.run (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\user_code_runner.ts:37:21)
[chrome 120.0.6099.71 windows #0-1]     at Object.run (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\step_runner.ts:50:41)
[chrome 120.0.6099.71 windows #0-1]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[chrome 120.0.6099.71 windows #0-1]     at async TestCaseRunner.invokeStep (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:137:12)        
[chrome 120.0.6099.71 windows #0-1]     at async TestCaseRunner.runStep (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:334:20)
[chrome 120.0.6099.71 windows #0-1]     at async C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:240:34
[chrome 120.0.6099.71 windows #0-1]     at async TestCaseRunner.aroundTestStep (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:170:28)    
[chrome 120.0.6099.71 windows #0-1]     at async TestCaseRunner.runAttempt (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:218:7)
[chrome 120.0.6099.71 windows #0-1]     at async TestCaseRunner.run (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:188:29)
[chrome 120.0.6099.71 windows #0-1]     at async Runtime.runTestCase (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\index.ts:89:20)
[chrome 120.0.6099.71 windows #0-1]     at async Runtime.start (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\index.ts:116:7)
[chrome 120.0.6099.71 windows #0-1]     at async runCucumber (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\api\run_cucumber.ts:125:19)
[chrome 120.0.6099.71 windows #0-1]     at async CucumberAdapter.run (file:///C:/Dev/git/testAllure/node_modules/@wdio/cucumber-framework/build/index.js:186:33)
[chrome 120.0.6099.71 windows #0-1]     at async Runner.run (file:///C:/Dev/git/testAllure/node_modules/@wdio/runner/build/index.js:148:24)


Spec Files:      0 passed, 2 failed, 2 total (100% completed) in 00:00:08

2023-12-14T08:17:58.433Z INFO @wdio/local-runner: Shutting down spawned worker
2023-12-14T08:17:58.696Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-12-14T08:17:58.697Z INFO @wdio/local-runner: shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment]
Hi, you mention three expectations which I feel are probably two or three separate things that have got nothing in common. Let me break them down.

The number you see in your terminal is the amount of specs that have run which is different from the amount of tests. We can change this but I feel like this is not an issue but rather a discussion topic/idea to improve upon.

Regarding the retries, this is a whole different issue. You can create an issue to improve upon the current situation with a link to a GH repo (as Boris already mentioned).

**Comment by christian-bromann** [comment]
> And it's not true because I've 3 test cases and not 2.

Yes you have 3 test cases but you have grouped your specs like this `specs: [['./features/worker1/*.feature'], ['./features/worker2/*.feature']],` which means there are only gonna be 2 workers for them.

- worker 1: `['./features/worker1/*.feature']`
- worker 2: `['./features/worker2/*.feature']`

You would get 3 worker processes when defining the specs like this `['./features/**/*.feature']`.

> but make not sense with the previous result. The previous result, I think, that it's showing the worker's status and not test results.

I am not sure what you mean by that, please explain.

> Other mistake in this result is: If I defined a retry parameter, for instance retry = 1, and in the second execution the test is success I've a fail in the result and the exit code is 1 instead of 0 because all the test were success

Also here it is not very easy to understand what you mean.

Generally I recommend raising one issue for one specific problem so it is more clear. As my previous poster mentioned, it is better to provide reproducible examples that we can run ourselves as we won't spend time putting this together. Please read more about this in our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

**Comment by carri747** [comment]
make sense I'm going to split this issue in three and clarify all the situation sorry for the inconveniences
