### ISSUE TITLE
[💡Feature]: migrate to Node.js native `fetch` method

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#11862]
With v18 of Node.js `fetch` is natively available and we should migrate to that and remove `got` and `ky` as dependencies everywhere.

This is a v9 task and pull requests should be raised against the [`v9`](https://github.com/webdriverio/webdriverio/tree/v9) branch. Join the `🙏-contribute` channel on [Discord](https://discord.webdriver.io) if you are interested to join us in this effort.

**Comment by nextlevelbeard** [comment]
@christian-bromann Thinking of Deno, Bun, etc, shouldn't we keep `got` & `ky` arround?

**Comment by christian-bromann** [comment]
`fetch` has become the defacto standard across JavaScript platforms so Bun and Deno will support it too eventually if they haven't already.

**Comment by christian-bromann** [comment]
Thanks @tamil777selvan for pushing this out 👏
