### ISSUE TITLE
[🐛 Bug]: source map tests are failing on Windows

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#11875]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
any
```

### What happened?

We have [source map e2e tests](https://github.com/webdriverio/webdriverio/blob/73d23a01640e7e2a9833bf0b4aa6f3d40a920496/e2e/wdio/headless/source-maps.e2e.ts#L7) that ensure Serenity tests fail with correct pointers to the source file. Recently these tests started to fail on Windows:

```
Array [
-   "source-maps.e2e.ts:43:19",
-   "source-maps.e2e.ts:39:12",
-   "source-maps.e2e.ts:35:12",
-   "source-maps.e2e.ts:8:38",
+   "source-maps.e2e.ts?invalidateCache=0.24997314658807124:32",
+   "source-maps.e2e.ts?invalidateCache=0.24997314658807124:29",
+   "source-maps.e2e.ts?invalidateCache=0.24997314658807124:26",
+   "source-maps.e2e.ts?invalidateCache=0.24997314658807124:6",
]
```

see https://github.com/webdriverio/webdriverio/actions/runs/7225734778/job/19689787689?pr=11874

### What is your expected behavior?

I expect the test to pass like in other environments.

### How to reproduce the bug.

Revert this commit https://github.com/webdriverio/webdriverio/pull/11874/commits/73d23a01640e7e2a9833bf0b4aa6f3d40a920496 and run the test on Windows.

### Relevant log output

```typescript
see above
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
cc @jan-molak .. this could be very well an issue unrelated to WebdriverIO and might also resolve itself at any time. Just logged it to keep a note.

**Comment by jan-molak** [comment]
Thanks @christian-bromann! Looks like the tests correctly picked up an issue with the source map. The question is, of course, what caused the issue in the first place 🤔 Has anything changed in this area in WebdriverIO?

According to the https://github.com/webdriverio/webdriverio/commit/73d23a01640e7e2a9833bf0b4aa6f3d40a920496, it seems that you observed the [first test](https://github.com/webdriverio/webdriverio/blame/73d23a01640e7e2a9833bf0b4aa6f3d40a920496/e2e/wdio/headless/source-maps.e2e.ts#L7-L38) failing, but the [second one](https://github.com/webdriverio/webdriverio/blob/73d23a01640e7e2a9833bf0b4aa6f3d40a920496/e2e/wdio/headless/source-maps.e2e.ts#L41-L47) passing?

Detecting instantiation location works correctly in Serenity/JS and is extensively tested on both Linux and Windows, so I'd be curious to understand the difference that leads to test failure here.

This part of the path looks suspicious: `?invalidateCache=0.24997314658807124`; do we know where it is coming from?

You mentioned the test started failing recently, was there any change in the WebdriverIO codebase or its dependencies? Maybe it's related to something in TypeScript or TSNode?

**Comment by christian-bromann** [comment]
It seems to be flaky behavior because in https://github.com/webdriverio/webdriverio/actions/runs/7225734778 it was passing on Macs and now I see it failing in both which made me skip the whole test. I can't really tell if this was introduced at a certain point or was a flaky test all along and just now appears to be how more flaky now.

**Comment by jan-molak** [comment]
Hmm, I think [skipping tests](https://github.com/webdriverio/webdriverio/blob/af9a0d56eace57092a91c6b8906e387e8740355b/e2e/wdio/headless/source-maps.e2e.ts#L4) that work correctly on Mac and Linux and only recently started failing on Windows could be masking an actual problem.

I suggest limiting the skipping to Windows runners only and investigating the root cause.

**Comment by christian-bromann** [comment]
> I suggest limiting the skipping to Windows runners only and investigating the root cause.

I fails also for Mac. I thought first it was Windows only but when I skipped for Windows it started to also fail on Mac. No issues on Linux machines.

> Also, is this test failing on the `main` branch now?

I just merged a bug fix where I had to skip the whole test to unblock the build. See history here: https://github.com/webdriverio/webdriverio/pull/11874

**Comment by jan-molak** [comment]
Cool, thanks! And do you know if this test was failing on `main` before? I can't find it in the build history..

**Comment by christian-bromann** [comment]
> And do you know if this test failed on `main` before?

Yes, I can see tests failing before, e.g. https://github.com/webdriverio/webdriverio/actions/runs/7133838415/job/19427366814#step:7:119 push by a [commit](https://github.com/webdriverio/webdriverio/commit/94c39323945dbb38c415cc9d1390f23494138195) from last week.

**Comment by jan-molak** [comment]
What bothers me is that I can't seem to find where this `invalidateCache` part is coming from 🤔

**Comment by jan-molak** [comment]
@christian-bromann - I can't reproduce the issue you were seeing locally on my MacOS.
If I created a PR and enabled the sourcemaps test, that should run the Windows build too on CI, am I right? (I hate debugging on CI, but have no Windows machines available)

**Comment by christian-bromann** [comment]
You can maybe use https://github.com/stateful/vscode-server-action to debug within GitHub Actions. As mentioned before I see this happening on Mac and Windows. Note that we are using Node.js v18 in CI. Also, don't feel pressured to fix this asap .. it might very well go away as quickly as it appeared 🤷

**Comment by jan-molak** [comment]
OK, I managed to reproduce it on CI on macOS https://github.com/webdriverio/webdriverio/actions/runs/7228203949/job/19697221261?pr=11877

Locally, I use the same version of Node that's defined in the [WebdriverIO .nvmrc file](https://github.com/webdriverio/webdriverio/blob/a8d00d826d49b1b01bf4921a10974e1db47085f6/.nvmrc) - 18.12.1

Local result:
```
Local Node v18.12.1 - pass
```

However, note how GitHub Actions [**doesn't use .nvmrc**](https://github.com/webdriverio/webdriverio/blob/a8d00d826d49b1b01bf4921a10974e1db47085f6/.github/workflows/test.yml#L22-L28) as it relies on whatever's the latest Node 16/18/20:

```yaml
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
```

And in fact, on GitHub Actions, `setup-node` pulls in [**Node 18.19.0**](
https://github.com/webdriverio/webdriverio/actions/runs/7228203949/job/19697221261?pr=11877#step:3:8):

```
Found in cache @ /Users/runner/hostedtoolcache/node/18.19.0/x64
```

I've tried that locally:

```
nvm install 18.19.0
nvm use 18.19.0
npm run test:e2e
```

Boom:

```
  Array [
-   "source-maps.e2e.ts:43:19",
-   "source-maps.e2e.ts:39:12",
-   "source-maps.e2e.ts:35:12",
-   "source-maps.e2e.ts:8:38",
+   "source-maps.e2e.ts?invalidateCache=0.24283749260231757:32",
+   "source-maps.e2e.ts?invalidateCache=0.24283749260231757:29",
+   "source-maps.e2e.ts?invalidateCache=0.24283749260231757:26",
+   "source-maps.e2e.ts?invalidateCache=0.24283749260231757:6",
  ]
```
Taking it one minor version back:

```
nvm install 18.18
nvm use 18.18.2
npm run test:e2e
```

And everything's passing again.

**Comment by christian-bromann** [comment]
> The conclusion folks seem to have arrived at in that thread is to [use `tsx`](https://github.com/privatenumber/tsx) instead of `ts-node`...

This is awesome, as it would support tsconfigs path again. I will create an issue.

Closing as we have enabled the tests. Thanks @jan-molak for your work in this!

**Comment by christian-bromann** [comment]
https://github.com/webdriverio/webdriverio/issues/11878
