### ISSUE TITLE
[💡 Feature]: Replace `ts-node` with `tsx`

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#11878]
### Is your feature request related to a problem?

We have been running into issues using `ts-node` lately, see:

- https://github.com/webdriverio/webdriverio/issues/10857
- https://github.com/webdriverio/webdriverio/issues/11875

For running TypeScript files on demand we currently use `ts-node` which seems to have difficulties with ESM/CJS as well as sourcemaps.

### Describe the solution you'd like.

Switch to `tsx` which seems to have general better support for it.

### Describe alternatives you've considered.

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Delagen** [comment]
Now I solved this with running
TSX_TSCONFIG_PATH="./tsconfig.json" NODE_OPTIONS="$NODE_OPTIONS --import tsx" wdio run ./wdio.conf.js

Config need to be compiled to JS or need to be written in plain JS in case to prevent loading ts-node in @wdio/config by detection of extention of config

**Comment by christian-bromann** [comment]
@Delagen writing the config to the file system as JS file is not an option. We should provide the ability to just load TS files and execute them.

**Comment by Delagen** [comment]
@christian-bromann I understand, I use config in JS only to prevent loading of ts-node. All tests and etc. written in Typescript, an d not transpiled to JS manually, all compilation in memory via TSX

**Comment by goosewobbler** [comment]
I took a look at this but it seems there is a fair bit of overlap with the removal of transpiler choice / `autoCompileOpts`, so maybe we do them together or at least that one first.

Some things I noted:

- `tsx` has no configuration outside of setting a custom `tsconfig.json` path
- We may need to do some switching on node version to ensure the correct loader syntax is used: https://tsx.is/node#es-modules-only
- The programmatic use, e.g. replacement for `ts-node` register function, may look quite different: https://github.com/privatenumber/tsx/discussions/102

**Comment by christian-bromann** [comment]
> so maybe we do them together or at least the latter one first.

Sounds good to me. I am open to remove `autoCompileOpts` all together and have it "just" work™.

**Comment by erwinheitzman** [comment]
@goosewobbler sounds good. I think it is good to stick as much as possible to how the tools work out of the box (no config using wdio but instead document how wdio can be used with tsx). So if tsx recommends using environment variables to appoint a tsconfig then we just point to the tsx documentation, simple, clean and most of all less maintenance and confusion

**Comment by goosewobbler** [comment]
@erwinheitzman `tsx` just provides both methods, CLI switch and env var, there's [no explicit recommendation](https://tsx.is/usage#custom-tsconfig-json-path).  I implemented a `tsxTsConfigPath` setting which is passed to the switch but can easily remove it if we want to reduce the maintenance load here.

**Comment by christian-bromann** [comment]
I think being able to provide the path to a `tsconfig.json` makes sense since many projects have a different `tsconfig.json` for development and testing. One suggestion: I would call this option in WebdriverIO just `tsConfigPath`.

**Comment by christian-bromann** [comment]
Re-assigning this to @goosewobbler as he took a first stab at a PR on this.

**Comment by QA-ler** [comment]
Hi @christian-bromann @goosewobbler,

in our project we currently run into problems related to ts-node see https://github.com/TypeStrong/ts-node/issues/2053.
Switched to 9.0.0-alpha to see if it solves the problem and works perfectly fine.
Thanks a lot already!
