### ISSUE TITLE
waitForExist doesn't seem to work with PhantomJS

### ISSUE THREAD

**Issue by alexmngn** [webdriverio/webdriverio#1189]
Hi there,
I'm using webdriverio v3.4.0 to test my app.

The following code doesn't work with PhantomJS but works fine with Chrome:

```
	return browser
	.url('/login')
        .click('.submit')
```

I get the following error with PhantomJS:

```
Failed: Element is not currently visible and may not be manipulated
running phantomjs
```

It doesn't seem to find the element `.submit`, any idea what's wrong?

Thanks

**Comment by christian-bromann** [comment]
This is a phantomjs issue. You will find a solution if you google the error message.
