### ISSUE TITLE
[💡 Feature]: Video recordings in a standalone mode

### ISSUE THREAD

**Issue by gladykov** [webdriverio/webdriverio#11905]
### Is your feature request related to a problem?

I was writing abstraction layer to be able to run same tests both using WebdriverIO and Playwright, and I encountered issue where WebdriverIO cannot record screen in a standalone mode: https://webdriver.io/docs/setuptypes/

Playwright can do it, but I have no idea how they achieve this internally:

```
 const context: BrowserContext = await browser.newContext({
                    recordVideo: {
                        dir: environmentConfig.videosFolder,
                    },
                });
```

### Describe the solution you'd like.

I want to be able to record video in standalone mode.

```
  const browser = await remote({
                    capabilities: {
                        browserName: 'chrome',
                        'goog:chromeOptions': {
                            args: headless ? ['--headless=new', 'disable-gpu'] : [],
                        },
                    },
                });
                await browser.startVideoRecording()
```

### Describe alternatives you've considered.

I created wdio.conf.js , to try to use [wdio-video-reporter](https://webdriver.io/docs/wdio-video-reporter/), but it didn't work:

```
const video = require('wdio-video-reporter');

export const config = {

  reporters: [
    [video, {
      saveAllVideos: true,       // If true, also saves videos for successful test cases
      videoSlowdownMultiplier: 3, // Higher to get slower videos, lower for faster videos [Value 1-100]
      outputDir: './artifacts/videos/',
    }],
  ],

}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
@gladykov thanks for reporting the issue.

Currently WebdriverIO doesn't support video reporting in standalone mode. This is mostly due the fact that there is no reliable cross browser capability that would allow us to do that without causing delays in test execution. The community has worked on a video reporter that you pointed out which has support for running tests using the testrunner. If you have issues using the video reporter within the test runner we advise to raise an issue in the video reporter project.

As for now we don't plan to add support until there is a cross browser compliant way to do this. I am sure there are ways to connect the reporter with a standalone instance and call certain reporter methods when other WebdriverIO events are triggered. I don't have any examples for that though.

I will go ahead and close the issue as `won't do` but I am happy to advise further.

**Comment by gladykov** [comment]
After take two I learned more, so leaving in case someone will be interested:

Playwright uses [Page.startScreencast](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-startScreencast) functionality of DEV tools. I didn't look into other browsers. So they emit frames into buffer, which ffmpeg uses to encode.

`wdio-video-reporter` saves screenshots on disk using wdio screenshot functionality (`browser.saveScreenshot` or `browser.browsingContextCaptureScreenshot`) and they glue them in the end with `ffmpeg` as well.
