### ISSUE TITLE
`after` callback fired only after session is deleted.

### ISSUE THREAD

**Issue by eyalzek** [webdriverio/webdriverio#1190]
Using webdriverio v3.4, selenium-server 2.53.0

Expected behavior: global `browser` object would be available in the `after` callback, as well as all the custom commands etc.

Actual behavior: session is deleted before the `after` callback is reached, so the browser object is missing a session id, causing a `ServerError`.

Code sample and output can be found here:
https://gist.github.com/5390e856ba180f49eced

**Comment by christian-bromann** [comment]
Have you tried to put the after hook within the describe command?

**Comment by eyalzek** [comment]
That works, but I'm using the test runner and I want to avoid repeating this code in each of the test files.

**Comment by christian-bromann** [comment]
then just put the code within the after hook in your wdio.conf.js

**Comment by eyalzek** [comment]
That's exactly what's not working.

**Comment by christian-bromann** [comment]
ok, just checked the old code and it seems that we kill the session first before executing after

**Comment by eyalzek** [comment]
Is this something that would be fixed in v3?

**Comment by christian-bromann** [comment]
you can organise your spec files in a way that you execute one specific spec at the end (kinda like a teardown file). Try
```js
// wdio.conf.js
specs: ["/glob/of/my/specs/*.js", "teardown.js"]
```

try this

**Comment by eyalzek** [comment]
Not the cleanest solution, but works:) Thanks!
