### ISSUE TITLE
Example opens Firefox window and does nothing else

### ISSUE THREAD

**Issue by wyqydsyq** [webdriverio/webdriverio#1192]
So I just followed the tutorial on http://webdriver.io/guide.html

When I run:
`$ node test.js`

A new Firefox window opens up to the homepage and nothing happens.

Nothing is echoed out to the console and the opened Firefox window just sits on the homepage instead of loading `http://www.google.com`

I'm running node 5.7.0 on OpenSUSE Tumbleweed

**Comment by christian-bromann** [comment]
@wyqydsyq please update your selenium-standalone server

**Comment by jrmalin** [comment]
@christian-bromann I am having this same problem, however when I attempt to check the version of selenium-standalone with `selenium-standalone --version`, it returns `selenium-standalone: command not found`.

Any advice on this?
