### ISSUE TITLE
[🐛 Bug]: Cucumber step timeout override in step-definitions not respected

### ISSUE THREAD

**Issue by xbrys31** [webdriverio/webdriverio#11936]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.27

### Node.js Version

18.16.1

### Mode

WDIO Testrunner

### What happened?

Given a fresh install of webdriverIO (v8.27.0), with E2E testing, typescript, cucumber, chrome, spec, and pages object 

Given wdio config includes:
{
framework: "cucumber",
cucumberOpts: {
**timeout: 1000,**
}

Given step definitions 
Given (/^I am inthe (\w+) page$/, {timeout: **30000**}, async (page) => {
 await browser.pause(**2000**);
//await pages[page].open();
});

When I run tests using npm run wdio

The test failed with 
[0-10] Error in "0: Given I am on the login page"
Error: Timeout
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)

It seems to be link to the issue 11675
https://github.com/webdriverio/webdriverio/issues/11675

### What is your expected behavior?

the step timeout in the step definition (30000) 30 seconds should be apply

### How to reproduce the bug.

1. a fresh install of webdriverIO (v8.27.0), with E2E testing, cucumber, chrome, spec, and pages object 

2. update wdio.conf.ts to set cucumber timeout to 1000 (default timeout), 1 second:
{
framework: "cucumber",
cucumberOpts: {
**timeout: 1000,**
}

Update steps.ts line 11 to add a timeout 30000 (30 seconds) 
comment the line await pages[page].open();
add await browser.pause(**2000**); 2 seconds

example : 
Given (/^I am inthe (\w+) page$/, {timeout: **30000**}, async (page) => {
 await browser.pause(**2000**);
//await pages[page].open();
});

3. run tests using npm run wdio

The timeout of the step which is 30 seconds is not respected. The step fails

Note : wih webdriverio v8.22.1 it was passed

### Relevant log output

```typescript
[0-10] Error in "0: Given I am on the login page"
Error: Timeout
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by tamil777selvan** [comment]
@xbrys31, I believe a recent fix has been merged, but the updated version hasn't been published yet. Please try again once the new version is released.

**Comment by christian-bromann** [comment]
Thanks for verifying, I will close and cut a release.

**Comment by xbrys31** [comment]
Sorry for my late answer.
For me it's ok. Thank you all !

**Comment by andrei-ilyukovich** [comment]
> I was wondering if anyone had noticed/tested this with Hook timeouts. I am seeing this exact behaviour in my BeforeAll() hook. It will adhere to the cucumberOpts timeout or a hook timeout that is equal to or less than the cucumberOpts. It is only with hooks, the other steps (When, Then etc) are overriding the default fine. I don't know whether I should raise another bug for this or whether I am misunderstanding or missing a configuration setting.
> 
> `cucumberOpts: { timeout: 1000, }`
> 
> `BeforeAll({ 60000}, async () => {`
> 
> In the above example, the beforeAll will timeout at 1000ms. If modify 60000 to 500ms it will then respect the value.

See the same issue, baforeAll does not respect it own timeout if it is bigger than cucumberOpts.timeout.

"@cucumber/cucumber": "9.6.0",
"@wdio/cucumber-framework": "9.19.1",
