### ISSUE TITLE
Problem with install with node v5.2.0

### ISSUE THREAD

**Issue by OpakAlex** [webdriverio/webdriverio#1193]
npm: 3.3.12
node: v5.2.0
```
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/oopak/projects/intuo/gherkin-specs/features/node_modules/webdriverio/node_modules/readline2/node_modules/strip-ansi/cli.js'
```
Any ideas?

**Comment by christian-bromann** [comment]
No! How am I suppose to have an idea without any description how this happens :wink:

**Comment by oliviertassinari** [comment]
Same issue here:
npm: 3.3.12
node: v5.2.0

```sh
npm install --save-dev webdriverio@4.0.5

> npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/oliviertassinari/SplitMe/node_modules/webdriverio/node_modules/readline2/node_modules/strip-ansi/cli.js'
```

**Comment by christian-bromann** [comment]
Ok so it's an install error. Apparently something is broken either in the readline2 or strip-ansi module. I will try to update the packages to see if that helps. It might be related to chalk/strip-ansi#4.

**Comment by oliviertassinari** [comment]
The issue is solved on my end.
