### ISSUE TITLE
wdio runner process.exit should be synced

### ISSUE THREAD

**Issue by eben0** [webdriverio/webdriverio#1194]
v4.0.5

Steps to Reproduce:

in wdio.conf.js set 'afterSuite' function with setTimeout:

`afterSuite: function (suite) {
	setTimeout(function(){
		console.log('Bye!');
	}, 1000);
}`

Actual Results:
no log.

WORKAROUND:
add a timeout in runner.js (line: 253)

`setTimeout(function(){
process.exit(failures === 0 ? 0 : 1);
}, 1000);`

**Comment by christian-bromann** [comment]
> afterSuite: function (suite) { setTimeout(function(){ console.log('Bye!'); }); }

why should this suppose to work?

**Comment by eben0** [comment]
I'm writing custom reporter that sends email, but the process takes 1 second and the runner terminates before the email is sent.

the setTimeout is just an example, but the runner should not be terminated if there are still child processes running.

**Comment by christian-bromann** [comment]
@eben0 if you have to execute an async within the hook, return a promise so ensure that the runner waits until the returned promise is fulfilled.
