### ISSUE TITLE
[🐛 Bug]: Type WebdriverIO.Capabilities not exported (replaces DesiredCapabilities)

### ISSUE THREAD

**Issue by carljdp** [webdriverio/webdriverio#11940]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest (v8.27.0)

### Node.js Version

latest (v20.10.0)

### Mode

WDIO Testrunner

### Which capabilities are you using?

```jsonc
// probably not applicable, but seems this field is required, so ..
//
// My dev env is in WSL2, hence the /mnt/c/... paths,
//  for the win10 suite of tests

capabilities: [{
        browserName: 'firefox',
        'moz:firefoxOptions': {
            binary: '/mnt/c/Program Files/Firefox Developer Edition/firefox.exe',
            args: ['-P', 'minimal'],
        },
        'wdio:devtoolsOptions': {},
        acceptInsecureCerts: true,
        maxInstances: 1
    }],
```

### What happened?

Type `DesiredCapabilities` is marked as [**_deprecated_**](https://github.com/webdriverio/webdriverio/blame/06b17a6cb2f971b2c4f200dbafc4f145aa6448ae/packages/wdio-types/src/Capabilities.ts#L107), which [**_is an exported type_**](https://github.com/webdriverio/webdriverio/commit/4277730700d5f099c532cb5f365bb2d660906b46#diff-082ad1ee85a80f59fae2a0888ef95db547f2c0cb699250d6ea410a1d3e688cedR109)

However, the new / recommended replacement type, `WebdriverIO.Capabilities` is not exported / not available for import elsewhere like was possible with the previous type

Use case **(JS & JsDoc, not TS)**

```js
// Shows deprecation warning

/** @param {import('@wdio/types').Capabilities.DesiredCapabilities} capabilities */
const beforeHookFn = async (capabilities) => {
    const browserName = capabilities.browserName
    // ..
```

If you want type hinting/completion, you can only use the old deprecated type/interface, since the replacement is not yet exported. Illustrated in image below: using deprecated version of type/interface **with JsDoc `@param` directive** for type hinting.

![image](https://github.com/webdriverio/webdriverio/assets/5579064/9b8f2c47-195a-405c-80d1-103bab2c1488)

Code in example image above taken from docs [here](https://webdriver.io/docs/extension-testing/web-extensions#firefox) **(JsDoc-ified version)**

### What is your expected behavior?

It would be nice if i could import the recommended replacement type/interface, i.e. if it was also exported ([here](https://github.com/webdriverio/webdriverio/commit/4277730700d5f099c532cb5f365bb2d660906b46#diff-082ad1ee85a80f59fae2a0888ef95db547f2c0cb699250d6ea410a1d3e688cedR44)) - but I am no TypeScript expert - I'm not sure where the export should happen.

```js

// below is just an example -> the.export.hierarchy probably best determined by lib authors?

/** @param {import('@wdio/types').Capabilities.Capabilities} capabilities */
const beforeHookFn = async (capabilities) => {
    const browserName = capabilities.browserName
    // ..
```

### How to reproduce the bug.

To repreduce, create a config file like this in vscode **( JsDoc-ified version of example code taken from [here](https://webdriver.io/docs/extension-testing/web-extensions#firefox))**

```js title=wdio.conf.js

import path from 'node:path'
import url from 'node:url'

const __dirname = url.fileURLToPath(new URL('.', import.meta.url))
const extensionPath = path.resolve(__dirname, `web-extension.xpi`)

/** @param {import('@wdio/types').Capabilities.DesiredCapabilities} capabilities */
const beforeHookFn = async (capabilities) => {
    const browserName = capabilities.browserName
    if (browserName === 'firefox') {
        const extension = await fs.readFile(extensionPath)
        await browser.installAddOn(extension.toString('base64'), true)
    }
}

export const config = {
    before: beforeHookFn,
    runner: 'local',
    // rest of your config
}

```

### Relevant log output

```typescript
not applicable / no runtime logs ..

VS Code linter can not find the sub properties of `Capabilities` however i try to import it,
 it just shows the type as `any` for all.

Except if I import the deprecated type/interface, then everything works as expected
¯\_ (ツ)_/¯
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Possible related changes:

- PR https://github.com/webdriverio/webdriverio/pull/11367
- Commit (all files) https://github.com/webdriverio/webdriverio/commit/4277730700d5f099c532cb5f365bb2d660906b46#
- Capabilities.ts diff https://github.com/webdriverio/webdriverio/commit/4277730700d5f099c532cb5f365bb2d660906b46#diff-082ad1ee85a80f59fae2a0888ef95db547f2c0cb699250d6ea410a1d3e688ced

**Comment by christian-bromann** [comment]
@carljdp thanks for raising the issue. We recommend to make use of the WebdriverIO namespace like so:

```js
/**
 * Represents a book.
 * @constructor
 * @param {WebdriverIO.Capabilities} caps - some capabilities
 */
function Book(caps) {
    caps.browserName
}
```

This will correctly type the parameter with JSDoc:

<img width="594" alt="Screenshot 2024-01-13 at 6 59 34 PM" src="https://github.com/webdriverio/webdriverio/assets/731337/57e0195b-167f-4a20-8e66-a2f877e00d9c">

I will go ahead and close the issue but I would like to know what we could do to better document this? Any suggestions?
