### ISSUE TITLE
[📖 Docs]: Improve TypeScript documentation for extending `expect`

### ISSUE THREAD

**Issue by MrGVSV** [webdriverio/webdriverio#11960]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Unclear documentation

### Description of the improvement / report

Currently, the [docs](https://webdriver.io/docs/api/expect-webdriverio/#adding-your-own-matchers) for extending WDIO's `expect` with a custom matcher only use JavaScript as an example.

While following these docs does work, TypeScript users will run into compiler errors. This is because the normal method for extending the `expect` type does not seem to have any effect on the `expect` from `expect.webdriverio`:

```ts
declare module 'expect' {
  interface AsymmetricMatchers {
    toBeWithinRange(floor: number, ceiling: number): void;
  }
  interface Matchers<R> {
    toBeWithinRange(floor: number, ceiling: number): R;
  }
}
```
```
error TS2339: Property 'toBeWithinRange' does not exist on type 'Matchers<void, number>'
```

It would be nice if the docs included a snippet for TypeScript users demonstrating how to properly extend the type for `expect` when extending it with custom matchers.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrGVSV** [comment]
Testing this a bit more, it seems the following partially works:
```ts
declare global {
  export namespace ExpectWebdriverIO {
    // interface AsymmetricMatchers {
    //   toBeWithinRange(floor: number, ceiling: number): void;
    // }

    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    interface Matchers<R, T> {
      toBeWithinRange(floor: number, ceiling: number): R;
    }
  }
}
```

However, as you can see, it only works with `Matchers<R, T>` (note the `T` is required despite being unused). 

I think this is due to how [`AsymmetricMatchers`](https://github.com/webdriverio/expect-webdriverio/blob/ff65811a5482da581d0acc535f1a02271978d14f/types/standalone.d.ts#L18-L26) is typed in the package. If I change it from a `type` to an `interface` definition, it works.

**Comment by MrGVSV** [comment]
Also to get `AsymmetricMatchers` to be fully free of warnings, we need to change the return value of our custom matcher from `void` to `PartialMatcher`.

I'm not sure what `PartialMatcher` does or how it works as it doesn't seem to have any documentation on it, but I think it should still work so long as we return `ExpectationResult` since all its properties are optional.

**Comment by MrGVSV** [comment]
Made a PR to fix the type definition: https://github.com/webdriverio/expect-webdriverio/pull/1406

**Comment by christian-bromann** [comment]
@MrGVSV I took a stab and wrote something up, please review and let me know if it makes sense: https://webdriver.io/docs/custommatchers

**Comment by MrGVSV** [comment]
> @MrGVSV I took a stab and wrote something up, please review and let me know if it makes sense: https://webdriver.io/docs/custommatchers

Looks great! My one comment would be that I think it'd be nice to include the `AsymmetricMatcher` interface in the TypeScript section. 

I don't think you necessarily need to explain what an asymmetric matcher is, but a link to the Jest docs on "Jest style" at the start of the page or something might also be helpful for those who want to learn more.

**Comment by christian-bromann** [comment]
Can you elaborate why documenting `AsymmetricMatchers` is useful for users here? It seems like it doesn't matter when the requirement is to extend matchers. Maybe I am missing something here.

**Comment by MrGVSV** [comment]
Well for my use case, I wanted to extend `expect` so that I could use it asymmetrically like:

```ts
expect(foo).toMatchObject({
  bar: expect.myCustomMatcher('baz'),
});
```

And in that case, I would need to do:

```ts
declare global {
  namespace ExpectWebdriverIO {
    interface AsymmetricMatchers {
      // `Normally these return `void`, but wdio expects its `PartialMatcher` type
      myCustomMatcher(value: string): PartialMatcher;
    }
  }
}
```

So I think it would be useful to include that in the TypeScript Support section. 

And optionally, you could link to [Jest's documentation](https://jestjs.io/docs/expect#expectextendmatchers) to avoid having to explain `AsymmetricMatchers` in the WDIO docs (it also gives a bit more insight into how to write custom matchers apart from browser/element ones).

**Comment by christian-bromann** [comment]
Thanks for the feedback, I added an additional section for it.
