### ISSUE TITLE
[💡 Feature]: More updated devices to the browser.emulateDevice()

### ISSUE THREAD

**Issue by DimaScholkin** [webdriverio/webdriverio#11985]
### Is your feature request related to a problem?

The most modern iPhone device from the emulateDevice() list is iPhone 13 Pro, it's emulated user agent has iOS 15.0 version that is outdated in 2 major versions and not supported for lots of web products.  Same for Samsung.

### Describe the solution you'd like.

Add more modern devices

### Describe alternatives you've considered.

Add an easy way to override the default OS version when calling the browser.emulateDevice('iPhone 13 Pro') method, e.g browser.emulateDevice('iPhone 13 Pro', {OS: 17.1}) 

### Additional context

I know I can create my own custom device with required userAgent, still I find browser.emulateDevice() very handy and preferable to use

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by erwinheitzman** [comment]
Seems like we can close this since the feature is merged. Let me know if it needs to be reopened (tag me in a reply).
