### ISSUE TITLE
[📖 Docs]: Image Comparison (Visual Regression Testing) Service - link to docs is broken

### ISSUE THREAD

**Issue by HananArgov** [webdriverio/webdriverio#11988]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Missing documentation

### Description of the improvement / report

the link to docs in Image Comparison (Visual Regression Testing) Service leads to [https://github.com/wswebcreation/wdio-image-comparison-service/blob/main/webdriver.io/docs/visual-testing](url)
but when clicking on it we get 404

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
@HananArgov thanks for reporting! We are about to update the docs (see #11906) and bring them into the core project. Please stay tuned.
