### ISSUE TITLE
Unable to provide service programmatically

### ISSUE THREAD

**Issue by just-boris** [webdriverio/webdriverio#1198]
[This code](https://github.com/webdriverio/webdriverio/blob/57bf7bc/lib/launcher.js#L357) always trying to load launcher by name as an npm module. But service can be provided as object and it is treated [here](https://github.com/webdriverio/webdriverio/blob/57bf7bc44d84bb234b634dd3af56a3507f91b7e7/lib/runner.js#L319).

I guess you want to keep config clear, so you are using the same option for both service and launcher.

What about in case of service object try to get launcher as `service.launcher` property?

**Comment by christian-bromann** [comment]
@just-boris done!

> What about in case of service object try to get launcher as service.launcher property?

just require the launcher directly like

```js
    services: [
        require('../launcher')
    ],
```

**Comment by khirakawa** [comment]
@christian-bromann any chance we can get a patch bump soon?  Would like to use this feature =)
