### ISSUE TITLE
[🐛 Bug]: `getText()` on SVG nodes

### ISSUE THREAD

**Issue by LukasHeimann** [webdriverio/webdriverio#11984]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.27.0

### Node.js Version

v20.9.0

### Mode

WDIO Testrunner

### What happened?

When calling `getText()` on an `Element`, the browser eventually executes `elem.innerText`: https://github.com/webdriverio/webdriverio/blob/dc35a2f9163ef2d6ab82e4834e0c65e1089afcf3/packages/devtools/src/scripts/getElementText.ts#L1-L3

It turns out that SVG elements don't have `innerText`, only HTMLELements have (https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent#differences_from_innertext). WebdriverIO Elements can be generic DOM nodes (i.e. you can match a `tspan` in an SVG). Thus, using `getText()` on such a node will return `undefined`, even though the `tspan` clearly includes some text. As a result, also matchers of `expect-webdriverio` fail unexpectedly.

### What is your expected behavior?

Previously, we were on WebdriverIO 7 and not using the devtools protocol, where `getText()` was working differently and returned the text properly. Perhaps this is a slight inconsistency between the `devtools` implementation and the `WebDriver` specification: https://w3c.github.io/webdriver/#get-element-text

> The [Get Element Text](https://w3c.github.io/webdriver/#dfn-get-element-text) [command](https://w3c.github.io/webdriver/#dfn-commands) intends to return an [element](https://dom.spec.whatwg.org/#concept-element)’s text “as rendered”.

In my reading, this might be why it has worked for the `tspan` node with the WebDriver protocol in the past: even though `innerText` is not defined on the node in the dom, it still has rendered text which is returned correctly for the webdriver protocol. As devtools relies on `innerText` only, `undefined` is returned when using that protocol.

A workaround might be to use `textContent` instead of `innerText` (or fall back to it), though that would expose whitespace differently (and also different compared to the WebDriver spec). In my project, we can fall back to `Element.getHTML()`, though that isn't ideal as well.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by LukasHeimann** [comment]
> Yes, this is the reason we stop suggesting using the devtools protocol anymore for automation and rather use the WebDriver protocol or switch to Puppeteer through WebdriverIO.

Oh, this is not ideal... We rely on the (community-provided) ui5 service, which mandates a switch to devtools protocol with their update to version 2 (which is the only version supporting WebdriverIO 8): https://ui5-community.github.io/wdi5/#/migration?id=usage-of-devtools-automation-protocol

I guess I'll be contacting them about this...

**Comment by BorisOsipov** [comment]
@LukasHeimann You can also make them "happy " with https://github.com/webdriverio/webdriverio/issues/11860

**Comment by LukasHeimann** [comment]
I've opened https://github.com/ui5-community/wdi5/issues/572 at the `wdio-ui5-service` to make them aware of this.

@christian-bromann, @BorisOsipov: Thank you for your really quick answers -- I guess there's nothing left to do for this issue here, as it rightfully won't fix. I don't know if you want to supply some additional labels to make it easier to find later on, but it can be closed otherwise.

**Comment by christian-bromann** [comment]
Thanks for raising the issue, I will go ahead and close this then. Feel free to join our [Discord](https://discord.webdriver.io) server if there any further questions around this topic.
