### ISSUE TITLE
[🐛 Bug]: Spec reporter can miss some Cucumber steps

### ISSUE THREAD

**Issue by grant-mccarriagher** [webdriverio/webdriverio#11996]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.27.2

### Node.js Version

20.10.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
let config = {
  runner: 'local',
  framework: 'cucumber',
  cucumberOpts: {
    failAmbiguousDefinitions: true,
    ignoreUndefinedDefinitions: false,
    profile: ['default'],
    require: ['./tests/support/hooks/**/*.js', './tests/stepDefinitions/**/*.js'],
    tagExpression: "not @bugged",
    timeout: cucumberTimeout
  },
  capabilities: [{
    browserName: 'chrome',
    'wdio:devtoolsOptions': {
      headless: true
    },
    'goog:chromeOptions': {
      args: [ 
        'use-fake-device-for-media-stream',
        'use-fake-ui-for-media-stream',
        'window-size=1920,1080'
      ]
    }
  }],
  specs: ['../tests/features/**/*.feature'],
  logLevel: 'error',
  deprecationWarnings: true,
  maxInstances: 2,
  bail: 0,
  baseUrl: 'https://www.google.com',
  waitforTimeout: 30000,
  connectionRetryTimeout: 120000,
  connectionRetryCount: 3,
  specFileRetries: process.env.RETRIES ? parseInt(process.env.RETRIES) : undefined,
  reporters: ['spec'],
  services: ['shared-store']
}
```

### What happened?

When using the same Cucumber steps in a scenario multiple times, the spec reporter seems to miss printing some of the duplicated steps.

For example, with the following Feature/Scenario:

```
Feature: Test

Scenario: Test Scenario
  Given something has happened
  When I do something
  Then I should see something

  When I do something
  Then I should see something
```

The step reporter output will be:

```
[chrome 120.0.6099.216 mac #0-0] Running: chrome (v120.0.6099.216) on mac
[chrome 120.0.6099.216 mac #0-0] Session ID: 17544089e9a77081a0fa137ecea0ed63
[chrome 120.0.6099.216 mac #0-0]
[chrome 120.0.6099.216 mac #0-0] » /tests/features/settings/test.feature
[chrome 120.0.6099.216 mac #0-0] Test
[chrome 120.0.6099.216 mac #0-0] Test Scenario
[chrome 120.0.6099.216 mac #0-0]    ✓ Given something has happened
[chrome 120.0.6099.216 mac #0-0]    ✓ When I do something
[chrome 120.0.6099.216 mac #0-0]    ✓ Then I should see something
[chrome 120.0.6099.216 mac #0-0]
[chrome 120.0.6099.216 mac #0-0] 5 passing (6.1s)
```

### What is your expected behavior?

All steps are printed in the spec reporter summary, regardless of how many times/when they're used in the scenario.

### How to reproduce the bug.

A boilerplate WDIO suite with Cucumber should be able to reproduce this with the scenario/steps above.

### Relevant log output

```typescript
Full trace output: https://gist.github.com/grant-mccarriagher/5ab0b08904609710fe2fd3e869b9c9c3
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by perillai** [comment]
In wdio-spec-reporter, getEventsToReport() function filters out duplicate feature steps. That is why you are not able to get duplicate feature lines generated in the report. Maybe, we should keep the part where retries are spliced, but allow duplicate non-retried steps as it is?

**Comment by christian-bromann** [comment]
Good point, I think we filter them out because they get retried. If we can make a differentiation and don't filter by their name and rather by their retry state that would be awesome.

**Comment by christian-bromann** [comment]
Issue is fixed and released. Thanks @perillai for working on this.
