### ISSUE TITLE
[🐛 Bug]: webdriverio@8.14.1 using webdriver protocol no longer able to connect to chromedriver

### ISSUE THREAD

**Issue by straker** [webdriverio/webdriverio#11998]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.14.1

### Node.js Version

18.17.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
  automationProtocol: 'webdriver',
  capabilities: {
    browserName: 'chrome'
  },
  logLevel: 'error',
  port: 4444
}
```

### What happened?

When upgrading from webdriverio@8.14.0 to webdriverio@8.14.1 (or any version >8.14.1), trying to use the webdriver protocol to connect to a running chromedriver instance spawned through nodes `child_process.spawn` API gives rejecting request errors.

### What is your expected behavior?

Webdriverio is able to connect to the running chromedriver and work

### How to reproduce the bug.

`package.json`

```json
{
  "devDependencies": {
    "chromedriver": "^120.0.1",
    "webdriverio": "^8.14.1"
  }
}
```

Relevant code:

```js
const webdriverio = require('webdriverio');
const chromedriver = require('chromedriver');
const assert = require('assert');
const { spawn } = require('child_process');

(async () => {
  const driverProcess = spawn(chromedriver.path, ['--port=4444', '--verbose', '--whitelisted-ips', '--allowed-origins="*"']);
  driverProcess.stdout.pipe(process.stdout);
  driverProcess.stderr.pipe(process.stderr);

  const client = await webdriverio.remote({
    automationProtocol: 'webdriver',
    capabilities: {
      browserName: 'chrome'
    },
    logLevel: 'error',
    port: 4444
  });

  await client.url('https://www.google.com/');
  const title = await client.getTitle();

  assert.equal(title, 'Google');
})();
```

When running the code with `webdriverio@8.14.1` an error occurs. When running with `webdriverio@8.14.0` no error happens, the browser opens the page and verbose messages are logged from chromedriver. 

What's interesting is that if I run the chromedriver process manually in my terminal and comment out the lines in the code that spawn the chromedriver process, webdriver is able to connect without issues. However, doing it this way requires that chromedriver be started with `--whitelisted-ips --allowed-origins="*"` whereas before in @8.14.0 those args were not needed.

```
./node_modules/chromedriver/bin/chromedriver --port=4444 --verbose --whitelisted-ips --allowed-origins="*"
```

### Relevant log output

```typescript
Starting ChromeDriver 120.0.6099.109 (3419140ab665596f21b385ce136419fde0924272-refs/branch-heads/6099@{#1483}) on port 4444
All remote connections are allowed. Use an allowlist instead!
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[1705086811.071][SEVERE]: Rejecting request with host: 0.0.0.0:4444 address: 0.0.0.0
[1705086811.076][SEVERE]: Rejecting request with host: 0.0.0.0:4444 address: 0.0.0.0
[1705086811.077][SEVERE]: Rejecting request with host: 0.0.0.0:4444 address: 0.0.0.0
[1705086811.078][SEVERE]: Rejecting request with host: 0.0.0.0:4444 address: 0.0.0.0
2024-01-12T19:13:31.078Z ERROR webdriver: Request failed with status 500 due to Error: Host header or origin header is specified and is not whitelisted or localhost.
2024-01-12T19:13:31.079Z ERROR webdriver: Error: Host header or origin header is specified and is not whitelisted or localhost.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Hey @straker , thanks for raising the issue.

I am not sure why Chromedriver is rejecting the connection, you can get it working with this script:

```ts
const webdriverio = require('webdriverio');
const chromedriver = require('chromedriver');
const assert = require('assert');
const { spawn } = require('child_process');

(async () => {
  const driverProcess = spawn(chromedriver.path, ['--port=4445']);
  driverProcess.stdout.pipe(process.stdout);
  driverProcess.stderr.pipe(process.stderr);

  const client = await webdriverio.remote({
    automationProtocol: 'webdriver',
    capabilities: {
      browserName: 'chrome'
    },
    logLevel: 'trace',
    hostname: 'localhost',
    port: 4445
  });

  await client.url('https://www.google.com/');
  const title = await client.getTitle();

  assert.equal(title, 'Google');
})();
```

We are currently working on fixing this in https://github.com/webdriverio/webdriverio/pull/11542. Therefor I will go ahead and close this as `duplicate`. Happy to answer further questions.

**Comment by straker** [comment]
Thanks, that fixed the issue for me!
