### ISSUE TITLE
[🐛 Bug]: Cucumber features filtering occurs after workers execution

### ISSUE THREAD

**Issue by losyukov-leonid** [webdriverio/webdriverio#11994]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.27.2

### Node.js Version

18.18.2

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  browserName: 'chrome'
}
```

### What happened?

Hi there,

When cucumber tags are used to filter features and scenarios workers execution started also for that `.features` that are skipped according to tag expression in `wdio.conf.ts` in `cucumberOpts.tags`.
It seems like features filtering occurs after workers execution.
E.g. if I have 8 `.feature` files and just 4 of them should be run after filtering according to tag expression execution of 8 workers will be started

<img width="495" alt="image" src="https://github.com/webdriverio/webdriverio/assets/149357837/ed1415b7-7cc3-4105-ba6e-9e7214bfd042">

but only 4 features would be run

<img width="610" alt="image" src="https://github.com/webdriverio/webdriverio/assets/149357837/fc716af5-8df1-4ca8-9675-bd86728cbdd7">

Every started worker uses RAM and occupies it. So it means that 4 uses a lot of resources for skipping specs.

### What is your expected behavior?

According to this [PR](https://github.com/webdriverio/webdriverio/pull/4326) it seems like it should work in another way - firstly filter all the `.feature` files and then start workers only for that ones that should be run.

### How to reproduce the bug.

1. Clone [this repo](https://github.com/losyukov-leonid/ts-wdio-cucumer)
2. Run `npm install`
3. Run  `npm run wdio`

### Relevant log output

```typescript
Execution of 8 workers started at 2024-01-12T10:34:18.182Z

[0-0] RUNNING in chrome - file:///features/login_1.feature
[0-0] PASSED in chrome - file:///features/login_1.feature
[0-1] RUNNING in chrome - file:///features/login_2.feature
[0-1] PASSED in chrome - file:///features/login_2.feature
[0-2] RUNNING in chrome - file:///features/login_3.feature
[0-2] PASSED in chrome - file:///features/login_3.feature
[0-3] RUNNING in chrome - file:///features/login_4.feature
[0-3] PASSED in chrome - file:///features/login_4.feature

Spec Files:      4 passed, 4 skipped, 8 total (100% completed) in 00:00:48
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@losyukov-leonid this is the expected behavior. We have to start 8 workers because we don't know before whether a feature file will be skipped or not. Cucumber is only initialised within the worker.

> So it means that 4 uses a lot of resources for skipping specs.

Well, a worker process is started and Cucumber gets initialised which costs resources but that's it. No browser is being opened.

Let me know if you have further questions.

**Comment by pfyod** [comment]
@christian-bromann: #10330 was supposed to change this behavior. Either it did not work or there was a regression.

**Comment by christian-bromann** [comment]
If you think something is not working as documented, please raise an issue with a reproducible example. Thanks.
