### ISSUE TITLE
Remove dependence on wgxpath

### ISSUE THREAD

**Issue by jacobmarble** [webdriverio/webdriverio#1199]
Hi there, I maintain https://www.npmjs.com/package/wgxpath, which webdriverio depends on. I suggest that you switch to https://www.npmjs.com/package/wicked-good-xpath because it's maintained by the upstream folks. I plan do delete wgxpath as soon as you have done this, so please drop me a line when you do.

**Comment by christian-bromann** [comment]
@jacobmarble I replaced the wgxpath dependency and replaced it by wicked-good-xpath. Could you please don't delete the wgxpath though? Many old versions still depend on it!

**Comment by jacobmarble** [comment]
Thanks. I'll wait at least a year or two.

**Comment by christian-bromann** [comment]
@jacobmarble why would you want to delete the package? It doesn't bother anyone there 😉

**Comment by christian-bromann** [comment]
@jacobmarble I had to revert the change because the suggested package doesn't work in IE.
