### ISSUE TITLE
Safari driver doesn't support the popup or alert

### ISSUE THREAD

**Issue by saravanguru** [webdriverio/webdriverio#1200]
How to handle popup windows in safari driver?  Popup window is not coming in safari browser. Below script is working in chrome, but it's not working in safari.

            client.alertText(function (err, res) {
                if (res != null) {
                    console.log("Alert: " + res.value);
                    message = res.value;
                    this.alertAccept();
                }
                client.call(done);
            });
Anyone have thought on this..

**Comment by christian-bromann** [comment]
Hi,
the issue you've described seems not be related to WebdriverIO and is rather an issue of Selenium or one of their browser driver. Please [reach out](https://github.com/SeleniumHQ/selenium/issues) to them or join the Gitter chat for the WebdriverIO project ([![Gitter](https://badges.gitter.im/Join Chat.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)).

Cheers
