### ISSUE TITLE
[🐛 Bug]: ERROR @wdio/local-runner: Failed launching test session: Error: Couldn't find plugin "video" reporter, neither as wdio scoped package "@wdio/video-reporter"

### ISSUE THREAD

**Issue by aozolin** [webdriverio/webdriverio#12027]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.27.0

### Node.js Version

v20.11.0

### Mode

WDIO Testrunner

### What happened?

I've build a WDIO project based on [webdriverio/jasmine-boilerplate](https://github.com/webdriverio/jasmine-boilerplate) template and installed **"wdio-video-reporter": "^5.1.0"**.
Added video reporter in the [wdio.shared.conf.ts](https://github.com/aozolin/wdio-video-reporter-issue/blob/main/wdio.shared.conf.ts) file as per https://www.npmjs.com/package/wdio-video-reporter guide:

`reporters: [
       'spec',
        ['video', {
            maxTestNameCharacters: 1000,
            saveAllVideos: true,       // If true, also saves videos for successful test cases
            videoSlowdownMultiplier: 3, // Higher to get slower videos, lower for faster videos [Value 1-100]
        }],
        ['allure', {
            outputDir: 'results/allure-results',
            disableWebdriverStepsReporting: true,
            disableWebdriverScreenshotsReporting: false,
            useCucumberStepReporter: false,
            disableMochaHooks : true
        }]
    ],`

The test case execution failed with below error:
`ERROR @wdio/local-runner: Failed launching test session: Error: Couldn't find plugin "video" reporter, neither as wdio scoped package "@wdio/video-reporter" nor as community package "wdio-video-reporter". Please make sure you have it installed!`

Any help to get it working is much appreciated.

### What is your expected behavior?

The video should be recorded and attached to Allure report.

### How to reproduce the bug.

To reproduce the issue checkout the sample project from [Project to reproduce](https://github.com/aozolin/wdio-video-reporter-issue.git).

1. Execute **npm install** 
2. Execute **npm run test:local** 
3. Check the **wdio logs**.

### Relevant log output

```typescript
2024-01-15T13:47:58.542Z INFO @wdio/local-runner: Run worker command: run
2024-01-15T13:47:59.000Z DEBUG @wdio/runner: init remote session
2024-01-15T13:47:59.012Z ERROR @wdio/local-runner: Failed launching test session: Error: Couldn't find plugin "video" reporter, neither as wdio scoped package "@wdio/video-reporter" nor as community package "wdio-video-reporter". Please make sure you have it installed!
    at initializePlugin (file:///projects/e2e_wdio/node_modules/@wdio/utils/build/initializePlugin.js:35:11)
    at async BaseReporter._loadReporter (file:///projects/e2e_wdio/node_modules/@wdio/runner/build/reporter.js:178:30)
    at async Promise.all (index 1)
    at async BaseReporter.initReporters (file:///projects/e2e_wdio/node_modules/@wdio/runner/build/reporter.js:23:27)
    at async Runner.run (file:///projects/e2e_wdio/node_modules/@wdio/runner/build/index.js:70:9)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
I found an issue in the `packgage.json` of the new video reporter version. This has been fixed and released. @aozolin please update your `wdio-video-reporter` package version to latest.

**Comment by aozolin** [comment]
@christian-bromann  Thank you a lot, it works well now.
