### ISSUE TITLE
[🐛 Bug]: [Mobile XCUITest-driver] Key Down action must have a closing Key Up successor

### ISSUE THREAD

**Issue by wswebcreation** [webdriverio/webdriverio#12039]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

18+

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
- Operating system: MacOS 14.2
- Appium server version (output of `appium --version`): `v2.4.1 (REV bab86d5de571015b63fd8fc30b47bbe072a1290e)`
- Appium driver(s) and their version(s): `xcuitest@5.13.2 (automationName 'XCUITest')`
- Appium plugin(s) and their version(s): -
- Node.js version (output of `node --version`): `v18.19.0`
- `npm` version (output of `npm --version`): `10.2.3`
- Last component(s) version which did _not_ exhibit the problem: not
- Platform and version under test: iOS 17.2
- Real device or emulator/simulator: Sims
```

### What happened?

Sending key actions according to the W3C ([simple](https://github.com/jlipps/simple-wd-spec?tab=readme-ov-file#perform-actions)) spec with a `pause` is breaking the implementation for iOS, but not for Android

I've filed an [issue](https://github.com/appium/appium/issues/19670) on the Appium project, but the XCTest API only allows to send keypresses (e.g. keydown+keyup). There is no way to "split" them

### What is your expected behavior?

Key can be send on iOS

### How to reproduce the bug.

# Failing
```ts 
            await driver.performActions(
                [
                    {
                        'id': 'action1',
                        'type': 'key',
                        'actions': [
                            {
                                'type': 'keyDown',
                                'value': '3'
                            },
                            {
                                'type': 'pause',
                                'duration': 10
                            },
                            {
                                'type': 'keyUp',
                                'value': '3'
                            }
                        ]
                    }
                ]
            )
```

# Works
```ts 
            await driver.performActions(
                [
                    {
                        'id': 'action1',
                        'type': 'key',
                        'actions': [
                            {
                                'type': 'keyDown',
                                'value': '3'
                            },
                            {
                                'type': 'keyUp',
                                'value': '3'
                            }
                        ]
                    }
                ]
            )
```

### Relevant log output

[appium.failing.log](https://github.com/appium/appium/files/13963393/appium.failing.log)
[appium.succeeds.log](https://github.com/appium/appium/files/13963394/appium.succeeds.log)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by wswebcreation** [comment]
Will be fixed with #12040

**Comment by web3rd2** [comment]
still got problem

## WebdriverIO Version
latest
## Appium
[Appium] Welcome to Appium v2.4.1 (REV c92adb3c479d70bb29f4399a808c972ef41510e7)

## XCUITest
xcuitest@5.16.1
## Failing
            await driver.performActions(
                [
                    {
                        'id': 'action1',
                        'type': 'key',
                        'actions': [
                            {
                                'type': 'keyDown',
                                'value': '3'
                            },
                             {
                                'type': 'keyDown',
                                'value': '4'
                            },
                            {
                                'type': 'keyUp',
                                'value': '4'
                            },
                              {
                                'type': 'keyUp',
                                'value': '3'
                            }
                        ]
                    }
                ]
            )
## Works
            await driver.performActions(
                [
                    {
                        'id': 'action1',
                        'type': 'key',
                        'actions': [
                            {
                                'type': 'keyDown',
                                'value': '3'
                            },
                            {
                                'type': 'keyUp',
                                'value': '3'
                            },
                             {
                                'type': 'keyDown',
                                'value': '4'
                            },
                            {
                                'type': 'keyUp',
                                'value': '4'
                            }
                        ]
                    }
                ]
            )

**Comment by wswebcreation** [comment]
This is not related to WDIO

what do you also want to achieve, to submit 34 you need to have a  keyDow and Up per char, for CTRL + something else you can use two keyUps before you put them to down
