### ISSUE TITLE
[🐛 Bug]: Cant able to download latest chrome  after updating Webdriver.io version to 8.27.2

### ISSUE THREAD

**Issue by LakshmiYaswanth** [webdriverio/webdriverio#12033]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.27.2

### Node.js Version

21.6.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
import allure from '@wdio/allure-reporter';
import dns from 'node:dns';
const mochaTimeout = 12 * 10 * 1000;
const timeout = 9 * 10 * 1000;
exports.config = {
    runner: 'local',
    specs: [
       'src/test.spec.ts'
    ],
    baseUrl: environment.dev,
    injectGlobals: true,
    /**
     * ============
     * Capabilities
     * ============
     * Define your capabilities here. WebdriverIO can run multiple capabilities at the same
     * time. Depending on the number of capabilities, WebdriverIO launches several test
     * sessions. Within your capabilities you can overwrite the spec and exclude options in
     * order to group specific specs to a specific capability.
     * First, you can define how many instances should be started at the same time. Let's
     * say you have 3 different capabilities (Chrome, Firefox, and Safari) and you have
     * set maxInstances to 1; wdio will spawn 3 processes. Therefore, if you have 10 spec
     * files and you set maxInstances to 10, all spec files will get tested at the same time
     * and 30 processes will get spawned. The property handles how many capabilities
     * from the same test should run tests.
    **/

    maxInstances: 10,
    /** 
     * If you have trouble getting all important capabilities together, check out the
     * Sauce Labs platform configurator - a great tool to configure your capabilities:
     * https://docs.saucelabs.com/reference/platforms-configurator
    **/
    capabilities: [
        /**  maxInstances can get overwritten per capability. So if you have an in-house Selenium
        *    grid with only 5 firefox instances available you can make sure that not more than
        *     5 instances get started at a time.
        **/
        {
            maxInstances: 5,
            browserName: 'chrome',
            browserVersion: 'stable',
            timeouts: { pageLoad: 90000, implicit: 90000, script: 90000 },
            acceptInsecureCerts: true,
            'goog:chromeOptions': { // or 'moz:firefoxOptions'
                args: [
                    '--remote-allow-origins=*',
                    '--enable-logging',
                    //'--headless',
                    '--no-sandbox',
                    '--disable-gpu',
                    '--disable-setuid-sandbox',
                    '--disable-dev-shm-usage',
                    '--disable-infobars',
                    '--window-size=1280,800',
                    '--incongnito'
                ],
            }
        },
    ],
    logLevel: 'trace',
    outputDir: './test-report/output',
    bail: 0,
    waitforTimeout: timeout,
    connectionRetryTimeout: timeout,
    connectionRetryCount: 3,
    framework: 'mocha',
    mochaOpts: {
        timeout: mochaTimeout,
        ui: 'bdd',
    },
    reporters: [
        'spec',
        ['json', {
            outputDir: './test-report/json-result/',
            outputFileFormat: function (options: { cid: any }) {
                return `results-${options.cid}.json`
            }
        }],
        [
            'allure',
            {
                outputDir: './test-report/allure-result/',
                disableWebdriverStepsReporting: true,
                disableWebdriverScreenshotsReporting: false,
            },
        ],
    ],
    services: [
        'docker',
        'devtools',
        'intercept'
    ],
    autoCompileOpts: {
        autoCompile: true,
        tsNodeOpts: {
            project: './tsconfig.json',
            transpileOnly: true
        }
    },
    /** 
    * =====
    * Hooks
    * =====
    * WebdriverIO provides several hooks you can use to interfere with the test process in order to enhance
    * it and to build services around it. You can either apply a single function or an array of
    * methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
    * resolved to continue.
    **/
    /**
     * Gets executed once before all workers get launched.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     */
    /** 
     * onPrepare: function (config, capabilities) {
     * },
    **/
    /**
     * Gets executed before a worker process is spawned and can be used to initialise specific service
     * for that worker as well as modify runtime environments in an async fashion.
     * @param  {String} cid      capability id (e.g 0-0)
     * @param  {[type]} caps     object containing capabilities for session that will be spawn in the worker
     * @param  {[type]} specs    specs to be run in the worker process
     * @param  {[type]} args     object that will be merged with the main configuration once worker is initialised
     * @param  {[type]} execArgv list of string arguments passed to the worker process
     */
    /** 
     * onWorkerStart: function (cid, caps, specs, args, execArgv) {
     * },
    **/
    /**
     * Gets executed just before initialising the webdriver session and test framework. It allows you
     * to manipulate configurations depending on the capability or spec.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     */
    beforeSession() {
        // https://github.com/webdriverio/webdriverio/issues/8279
        dns.setDefaultResultOrder('ipv4first');
    },
    /**
     * Gets executed before test execution begins. At this point you can access to all global
     * variables like `browser`. It is the perfect place to define custom commands.
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs        List of spec file paths that are to be run
     * @param {Object}         browser      instance of created browser/device session
     */
    before: async function (capabilities: Array<object>, specs: Array<string>) {
        global.allure = allure;
    },
    /**
     * Runs before a WebdriverIO command gets executed.
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     */
    /** 
     * beforeCommand: function (commandName, args) {
     * },
     */
    /**
     * Hook that gets executed before the suite starts
     * @param {Object} suite suite details
     */
    beforeSuite: async function (suite: { name: string }) {
        await allure.addFeature(suite.name);
    },
    /**
     * Function to be executed before a test (in Mocha/Jasmine) starts.
     */
    // beforeTest: function (test, context) {
    //     allure.reportedEnvironmentVars("BROWSER", browser.capabilities.browserName);
    //     allure.reportedEnvironmentVars("BROWSER_VERSION", browser.capabilities.version);
    //     allure.reportedEnvironmentVars("PLATFORM", browser.capabilities.platform);
    // },
    /**
     * Hook that gets executed _before_ a hook within the suite starts (e.g. runs before calling
     * beforeEach in Mocha)
     */
    // beforeHook: async function (test, context) {
    // },
    /**
     * Hook that gets executed _after_ a hook within the suite starts (e.g. runs after calling
     * afterEach in Mocha)
     */
    // afterHook: async function (test, context, { error, result, duration, passed, retries }) {
    // },
    /**
     * Function to be executed after a test (in Mocha/Jasmine).
     */
    afterTest: async function (
        test,
        context,
        { error, result, duration, passed, retries },
    ) {
        if (error) {
            await browser.takeScreenshot()
        } else {
            await browser.takeScreenshot()
        }
    },

    /**
     * Hook that gets executed after the suite has ended
     * @param {Object} suite suite details
     */
    /**
     * afterSuite: function (suite) {
     *   },
     */

    /**
     * Runs after a WebdriverIO command gets executed
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     * @param {Number} result 0 - command success, 1 - command error
     * @param {Object} error error object if any
     */
    // afterCommand: function (commandName, args, result, error) {
    // },
    /**
     * Gets executed after all tests are done. You still have access to all global variables from
     * the test.
     * @param {Number} result 0 - test pass, 1 - test fail
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // after: function (result, capabilities, specs) {
    // },
    /**
     * Gets executed right after terminating the webdriver session.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // afterSession: function (config, capabilities, specs) {
    // },
    /**
     * Gets executed after all workers got shut down and the process is about to exit. An error
     * thrown in the onComplete hook will result in the test run failing.
     * @param {Object} exitCode 0 - success, 1 - fail
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {<Object>} results object containing test results
     */
    // onComplete: function (exitCode, config, capabilities, results) {
    //     mergeResults('./test-report/json-result', 'results-*.json', 'wdio-custom-filename.json')
    // }
    /**
     * Gets executed when a refresh happens.
     * @param {String} oldSessionId session ID of the old session
     * @param {String} newSessionId session ID of the new session
     */
    //onReload: function(oldSessionId, newSessionId) {
    //}
};
```

### What happened?

After changeing version to 8.27.2 when on running test scripts . Webdriver.io Cant able to download the chrome it is throwing error.
![image](https://github.com/webdriverio/webdriverio/assets/54092913/5d1315cf-dc22-42df-8c1b-d5b20f58dede)
Error: Couldn't find a matching chrome browser for tag "120.0.6099.109" on platform "win64"
    at setupPuppeteerBrowser (file:///C:/Users/bbolli065/Documents/GitHub/toolkit-automation/node_modules/@wdio/utils/build/node/utils.js:193:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async Promise.all (index 1)
    at async Launcher.run (file:///C:/Users/bbolli065/Documents/GitHub/toolkit-automation/node_modules/@wdio/cli/build/launcher.js:102:13)

### How to reproduce the bug.

Package.json
{

  "scripts": {
    "code:format": "eslint . --ext .ts && prettier --check \"src/**/*.ts*\" --write",
    "report:generate": "npx allure generate --clean ./test-report/allure-result/ -o ./test-report/allure-report",
    "report:open": "npx allure open test-report/allure-report",
    "test": "wdio run ./wdio.dev.conf.ts"
  },
  "devDependencies": {
    "@wdio/allure-reporter": "^8.21.0",
    "@wdio/cli": "^8.27.2",
    "@wdio/devtools-service": "^8.27.2",
    "@wdio/local-runner": "^8.27.2",
    "@wdio/mocha-framework": "^8.27.2",
    "@wdio/spec-reporter": "^8.27.2",
    "allure-commandline": "^2.22.1",
    "eslint-plugin-wdio": "^8.8.7",
    "ts-node": "^10.9.1",
    "typescript": "^5.2.2",
    "wdio-docker-service": "^3.2.1",
    "wdio-image-comparison-service": "^5.0.3",
    "wdio-intercept-service": "^4.4.0"
  },
  "dependencies": {
    "@typescript-eslint/eslint-plugin": "^5.59.9",
    "@typescript-eslint/parser": "^5.59.9",
    "@wdio/json-reporter": "^8.26.3",
    "eslint": "^8.42.0",
    "prettier": "^2.8.8",
    "webdriverio": "^8.27.2"
  }
}
wdio.dev.conf.ts
import allure from '@wdio/allure-reporter';
import dns from 'node:dns';
const mochaTimeout = 12 * 10 * 1000;
const timeout = 9 * 10 * 1000;
exports.config = {
    runner: 'local',
    specs: [
       'src/test.spec.ts'
    ],
    baseUrl: environment.dev,
    injectGlobals: true,
    /**
     * ============
     * Capabilities
     * ============
     * Define your capabilities here. WebdriverIO can run multiple capabilities at the same
     * time. Depending on the number of capabilities, WebdriverIO launches several test
     * sessions. Within your capabilities you can overwrite the spec and exclude options in
     * order to group specific specs to a specific capability.
     * First, you can define how many instances should be started at the same time. Let's
     * say you have 3 different capabilities (Chrome, Firefox, and Safari) and you have
     * set maxInstances to 1; wdio will spawn 3 processes. Therefore, if you have 10 spec
     * files and you set maxInstances to 10, all spec files will get tested at the same time
     * and 30 processes will get spawned. The property handles how many capabilities
     * from the same test should run tests.
    **/

    maxInstances: 10,
    /** 
     * If you have trouble getting all important capabilities together, check out the
     * Sauce Labs platform configurator - a great tool to configure your capabilities:
     * https://docs.saucelabs.com/reference/platforms-configurator
    **/
    capabilities: [
        /**  maxInstances can get overwritten per capability. So if you have an in-house Selenium
        *    grid with only 5 firefox instances available you can make sure that not more than
        *     5 instances get started at a time.
        **/
        {
            maxInstances: 5,
            browserName: 'chrome',
            browserVersion: 'stable',
            timeouts: { pageLoad: 90000, implicit: 90000, script: 90000 },
            acceptInsecureCerts: true,
            'goog:chromeOptions': { // or 'moz:firefoxOptions'
                args: [
                    '--remote-allow-origins=*',
                    '--enable-logging',
                    //'--headless',
                    '--no-sandbox',
                    '--disable-gpu',
                    '--disable-setuid-sandbox',
                    '--disable-dev-shm-usage',
                    '--disable-infobars',
                    '--window-size=1280,800',
                    '--incongnito'
                ],
            }
        },
    ],
    logLevel: 'trace',
    outputDir: './test-report/output',
    bail: 0,
    waitforTimeout: timeout,
    connectionRetryTimeout: timeout,
    connectionRetryCount: 3,
    framework: 'mocha',
    mochaOpts: {
        timeout: mochaTimeout,
        ui: 'bdd',
    },
    reporters: [
        'spec',
        ['json', {
            outputDir: './test-report/json-result/',
            outputFileFormat: function (options: { cid: any }) {
                return `results-${options.cid}.json`
            }
        }],
        [
            'allure',
            {
                outputDir: './test-report/allure-result/',
                disableWebdriverStepsReporting: true,
                disableWebdriverScreenshotsReporting: false,
            },
        ],
    ],
    services: [
        'docker',
        'devtools',
        'intercept'
    ],
    autoCompileOpts: {
        autoCompile: true,
        tsNodeOpts: {
            project: './tsconfig.json',
            transpileOnly: true
        }
    },
    /** 
    * =====
    * Hooks
    * =====
    * WebdriverIO provides several hooks you can use to interfere with the test process in order to enhance
    * it and to build services around it. You can either apply a single function or an array of
    * methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
    * resolved to continue.
    **/
    /**
     * Gets executed once before all workers get launched.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     */
    /** 
     * onPrepare: function (config, capabilities) {
     * },
    **/
    /**
     * Gets executed before a worker process is spawned and can be used to initialise specific service
     * for that worker as well as modify runtime environments in an async fashion.
     * @param  {String} cid      capability id (e.g 0-0)
     * @param  {[type]} caps     object containing capabilities for session that will be spawn in the worker
     * @param  {[type]} specs    specs to be run in the worker process
     * @param  {[type]} args     object that will be merged with the main configuration once worker is initialised
     * @param  {[type]} execArgv list of string arguments passed to the worker process
     */
    /** 
     * onWorkerStart: function (cid, caps, specs, args, execArgv) {
     * },
    **/
    /**
     * Gets executed just before initialising the webdriver session and test framework. It allows you
     * to manipulate configurations depending on the capability or spec.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     */
    beforeSession() {
        // https://github.com/webdriverio/webdriverio/issues/8279
        dns.setDefaultResultOrder('ipv4first');
    },
    /**
     * Gets executed before test execution begins. At this point you can access to all global
     * variables like `browser`. It is the perfect place to define custom commands.
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs        List of spec file paths that are to be run
     * @param {Object}         browser      instance of created browser/device session
     */
    before: async function (capabilities: Array<object>, specs: Array<string>) {
        global.allure = allure;
    },
    /**
     * Runs before a WebdriverIO command gets executed.
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     */
    /** 
     * beforeCommand: function (commandName, args) {
     * },
     */
    /**
     * Hook that gets executed before the suite starts
     * @param {Object} suite suite details
     */
    beforeSuite: async function (suite: { name: string }) {
        await allure.addFeature(suite.name);
    },
    /**
     * Function to be executed before a test (in Mocha/Jasmine) starts.
     */
    // beforeTest: function (test, context) {
    //     allure.reportedEnvironmentVars("BROWSER", browser.capabilities.browserName);
    //     allure.reportedEnvironmentVars("BROWSER_VERSION", browser.capabilities.version);
    //     allure.reportedEnvironmentVars("PLATFORM", browser.capabilities.platform);
    // },
    /**
     * Hook that gets executed _before_ a hook within the suite starts (e.g. runs before calling
     * beforeEach in Mocha)
     */
    // beforeHook: async function (test, context) {
    // },
    /**
     * Hook that gets executed _after_ a hook within the suite starts (e.g. runs after calling
     * afterEach in Mocha)
     */
    // afterHook: async function (test, context, { error, result, duration, passed, retries }) {
    // },
    /**
     * Function to be executed after a test (in Mocha/Jasmine).
     */
    afterTest: async function (
        test,
        context,
        { error, result, duration, passed, retries },
    ) {
        if (error) {
            await browser.takeScreenshot()
        } else {
            await browser.takeScreenshot()
        }
    },

    /**
     * Hook that gets executed after the suite has ended
     * @param {Object} suite suite details
     */
    /**
     * afterSuite: function (suite) {
     *   },
     */

    /**
     * Runs after a WebdriverIO command gets executed
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     * @param {Number} result 0 - command success, 1 - command error
     * @param {Object} error error object if any
     */
    // afterCommand: function (commandName, args, result, error) {
    // },
    /**
     * Gets executed after all tests are done. You still have access to all global variables from
     * the test.
     * @param {Number} result 0 - test pass, 1 - test fail
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // after: function (result, capabilities, specs) {
    // },
    /**
     * Gets executed right after terminating the webdriver session.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // afterSession: function (config, capabilities, specs) {
    // },
    /**
     * Gets executed after all workers got shut down and the process is about to exit. An error
     * thrown in the onComplete hook will result in the test run failing.
     * @param {Object} exitCode 0 - success, 1 - fail
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {<Object>} results object containing test results
     */
    // onComplete: function (exitCode, config, capabilities, results) {
    //     mergeResults('./test-report/json-result', 'results-*.json', 'wdio-custom-filename.json')
    // }
    /**
     * Gets executed when a refresh happens.
     * @param {String} oldSessionId session ID of the old session
     * @param {String} newSessionId session ID of the new session
     */
    //onReload: function(oldSessionId, newSessionId) {
    //}
};

### Relevant log output

```typescript
Error: Couldn't find a matching chrome browser for tag "120.0.6099.109" on platform "win64"
    at setupPuppeteerBrowser (file:///C:/Users/bbolli065/Documents/GitHub/toolkit-automation/node_modules/@wdio/utils/build/node/utils.js:193:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async Promise.all (index 1)
    at async Launcher.run (file:///C:/Users/bbolli065/Documents/GitHub/toolkit-automation/node_modules/@wdio/cli/build/launcher.js:102:13)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@LakshmiYaswanth I see this browser being available for your platform. Maybe it was a network blip. Can you try again?

**Comment by christian-bromann** [comment]
Please let us know if it worked for you!

**Comment by LakshmiYaswanth** [comment]
@christian-bromann  thanks for u help it is working

**Comment by christian-bromann** [comment]
Awesome, closing then.

**Comment by qabog** [comment]
Hi @christian-bromann,
I am getting the same issue 
`Error: Error: Couldn't find a matching chrome browser for tag "121.0.6167.160" on platform "mac"`

**Comment by christian-bromann** [comment]
@qabog see #12251
