### ISSUE TITLE
[💡 Feature]: Need a service to manually download the drivers and manage them

### ISSUE THREAD

**Issue by Avinash-Kannan** [webdriverio/webdriverio#12043]
### Is your feature request related to a problem?

https://github.com/webdriverio/webdriverio/issues/12038

### Describe the solution you'd like.

I can see this blog post about driver management => https://webdriver.io/blog/2023/07/31/driver-management/
But in my case, my tests are failing in gitlab CI runner due to chromedriver issue and I'm unable to get any other work around to resolve this.

### Describe alternatives you've considered.

I tried standalone-service and chromedriver-service, but nothing seems to help.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BorisOsipov** [comment]
>But in my case, my tests are failing in gitlab CI runner due to chromedriver issue and I'm unable to get any other work around to resolve this.

Investigate and fix the issue. As you mentioned, we already have driver management. We don't plan to build another one.

**Comment by Avinash-Kannan** [comment]
we already have driver management => Which one ? standalone-service seems to be deprecated not working with WDIO v8.16 and above. 
chromedriver-service seems to consider driver has been downloaded since wdio is internally marking chrome downloaded as true from @puppeteer browsers service

**Comment by BorisOsipov** [comment]
>we already have driver management => Which one ?

You wrote: ```I can see this blog post about driver management => webdriver.io/blog/2023/07/31/driver-management```
