### ISSUE TITLE
[🐛 Bug]: [WDIO-wait-for]: Argument of type 'ChainablePromiseArray<ElementArray>' is not assignable to parameter of type 'StringOrElements'.

### ISSUE THREAD

**Issue by voropa** [webdriverio/webdriverio#12059]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.28.6

### Node.js Version

18.19

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
Capabilities:
{
maxInstances: 3, 
browserName: 'chrome', 
acceptInsecureCerts: true, 
'goog:chromeOptions': {   
      args:     process.env.HEADLESS === 'true' ? ['--verbose', '--no-sandbox', '--headless', '--disable-gpu', '--window-size=1920x1080'] : ['--verbose', '--no-sandbox'],   
prefs: {     'profile.default_content_setting_values.automatic_downloads': 1,     
download: {       
prompt_for_download: false,       
directory_upgrade: true,       
default_directory: path.resolve(__dirname, TEST_RESULTS.downloads),     
},   
}, 
},
}

tsconfig:
{   
"compilerOptions": {     
"module": "commonjs",     
"target": "es6",     
"moduleResolution": "node",
}
}
```

### What happened?

Seems like "wdio-wait-for" types are incompatible with WDIO types.
EC methods like 'numberOfElementsToBeMoreThan' accept `StringOrElements` type of argument which is 
`type StringOrElements = string | ChainablePromiseArray<WebdriverIO.ElementArray>;`
But there's no such a type in WDIO globals - `'WebdriverIO.ElementArray'` and $$('locator') returns `ChainablePromiseArray<ElementArray>` instead of `ChainablePromiseArray<WebdriverIO.ElementArray>`.

However it works good with $('locator') and EC methods for a single element like `EC.elementToBeClickable($('locator'))`
because $() returns `ChainablePromiseElement<WebdriverIO.Element>` and elementToBeClickable() method accepts `StringOrElment = string | ChainablePromiseElement<WebdriverIO.Element>`

<img width="1206" alt="image" src="https://github.com/webdriverio/webdriverio/assets/14195681/e6bcbcd8-d7ee-4a6d-b8a5-3d2ff15576a2">

`"wdio-wait-for": "^3.0.10",`

Quite similar issue: #11350 and the fix: #11444

### How to reproduce the bug.

import * as EC from 'wdio-wait-for';

export default class WaitUtils {
  public static async waitForSmmth() {
    await browser.waitUntil(EC.numberOfElementsToBeMoreThan($$('locator'), 2), {});
    await browser.waitUntil(EC.elementToBeClickable($('locator')), {});
  }
}

### Relevant log output

```typescript
Argument of type 'ChainablePromiseArray<ElementArray>' is not assignable to parameter of type 'StringOrElements'.
  Type 'import("/node_modules/webdriverio/build/types").ChainablePromiseArray<import("/node_modules/webdriverio/build/types").ElementArray>' is not assignable to type 'import("/node_modules/webdriverio/build/types").ChainablePromiseArray<WebdriverIO.ElementArray>'.
    Type 'ElementArray' is missing the following properties from type 'ElementArrayExport': forEachSeries, mapSeries, findSeries, findIndexSeries, and 3 more.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by tech-dm-klymenko** [comment]
Hi @voropa 
Now I see that `$$` returns appropriate type `ChainablePromiseArray<WebdriverIO.ElementArray>`, but not `ChainablePromiseArray<ElementArray>` as you wrote

![Screenshot_9](https://github.com/webdriverio/webdriverio/assets/145493125/d10f31d7-343f-49a0-82e1-8bf32b7a1f61)

If you still have the problem, please provide a link to git-repo with reproducible example, so the problem can be more accurately investigated.

**Comment by voropa** [comment]
Hi @tech-dm-klymenko,
Thank you, it works for me now as well. 
It was just cached webdriverio version 8.4 in my npm packages, so when I cleared the cache and reinstalled all the modules with latest wdio v8.29 - the problem is gone. 
Will close the issue.
