### ISSUE TITLE
CommandError: Don't end the session manually. This will be done automatically.

### ISSUE THREAD

**Issue by marcodejongh** [webdriverio/webdriverio#1206]
Using mocha when I try to manually end the browser session in a afterEach I get the error:

```
CommandError: Don't end the session manually. This will be done automatically.
```

My beforeEach & afterEach looks like this:

```
describe('Onboarding', function() {
    beforeEach(function() {
        login();
    });
    afterEach(function() {
        browser.end();
    });
});
```

I am using ```webdriverio@4.0.5```. Judging from the pageobjects example I shouldn't have to manually end the browser it should be don automatically, which brings me to issue #1208

**Comment by christian-bromann** [comment]
Nope, using wdio you should not end your session manually. Let's continue the convo in #1208 then.
