### ISSUE TITLE
[🐛 Bug]: 8.29.0 introduces updateSnapshots to config but causes bug with --user cli argument

### ISSUE THREAD

**Issue by HermansJarno** [webdriverio/webdriverio#12078]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.29.0

### Node.js Version

18.18.2

### Mode

WDIO Testrunner

### What happened?

At our project we primarily start our tests from command line with wdio run config -- --user=... --key=...  
Since version 8.29.0 we get the message: Type check for option "updateSnapshots" failed: the "updateSnapshots" options needs to be one of "all", "new", "none".

During debugging we see that when --user is passed to the cli as an argument, that the config option updateSnapshots is set with this value. When --user is left out from cli, updateSnapshots keeps it value. 

### What is your expected behavior?

updateSnapshots does not get updated by --user

### How to reproduce the bug.

Add option --user to the wdio run command.

### Relevant log output

```typescript
Error: Type check for option "updateSnapshots" failed: the "updateSnapshots" options needs to be one of "all", "new", "none"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by pmerwin** [comment]
After updating to the latest wdio vs 8 to reclove chrome driver path issue, I am now seeing this:

Error: Type check for option "updateSnapshots" failed: the "updateSnapshots" options needs to be one of "all", "new", "none"

I set the option, but it has not resolved the issue.

**Comment by christian-bromann** [comment]
@pmerwin yes, as you can see in #12088 we had to change the alias from `-u` to `-s`.
