### ISSUE TITLE
[🐛 Bug]: Allure result generated by wdio is missing default name parameter of links

### ISSUE THREAD

**Issue by AndreiSakalouskiSalesfloor** [webdriverio/webdriverio#12070]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

Standalone Mode

### Which capabilities are you using?

{
  browserName : 'chrome',
  browserVersion : 'latest',
  platformName : 'OS X'
}

### What happened?

After migrating to WebdriverIO 8 allure reports made by the latest version of jenkins allure plugin display an empty string instead of attached  links. In WebdriverIO 7 this problem didn't exist.

For example here testrail and browsetstack links should be displayed but you can see - *empty string* *comma* *empty string*
<img width="347" alt="image" src="https://github.com/webdriverio/webdriverio/assets/87650155/6e0b63b6-5faf-438e-badf-c82ad87564cc">

I investigated that it happens because allure results are missing default *name* parameter of a link which used to be equal *url* by default in WebdriverIO 7

Example of a link from an actual generated allure result file:
`
"links":[{"url":"https://testrail/index.php?/cases/view/180743","type":"tms"}]
`

With links from browserstack I can set a custom name parameter and it works well on jenkins:

`allureReporter.addLink(
      response.urlFromBS,
      'Video from Browserstack',
      this.linkType.video
    );
`

But testrail links are added by another command and it's impossible to set a custom name here
`allureReporter.addTestId(testId);`

### What is your expected behavior?

Allure results should contain the link name parameter which is equal the link url by default for example:
`"links" : [{
    "name" : "https://testrail.net/index.php?/cases/view/184215",
    "url" : "https://testrail.net/index.php?/cases/view/184215",
    "type" : "tms"
  } ]
`

### How to reproduce the bug.

If you run this code you'll see that link in allure results is missing name parameter

wdio.conf.js:

```javascript
export const config = {
    runner: 'local',
    specs: [
        './test/specs/**/*.js'
    ],
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    capabilities: [{
        browserName: 'chrome'
    }],
    logLevel: 'info',
    baseUrl: 'http://localhost',
    framework: 'mocha',
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },
    reporters : [['allure',
        {
            outputDir       : './allure-results',
            tmsLinkTemplate : 'https://testrail.net/index.php?/cases/view/{}',
        },
    ]],
}
```

test.e2e.js:
```javascript
import allureReporter from '@wdio/allure-reporter';

describe('My Login application', () => {
    it('should login with valid credentials', async () => {
        allureReporter.addTestId('C123');

        allureReporter.addStep('Open chrome')
        await browser.url('https://google.com')
    })
})
```

package.json
```json
{
  "name": "IssueWithAllureLinks",
  "type": "module",
  "devDependencies": {
    "@wdio/cli": "^8.28.8",
    "@wdio/local-runner": "^8.28.8",
    "@wdio/mocha-framework": "^8.28.8",
    "@wdio/spec-reporter": "^8.28.8"
  },
  "scripts": {
    "wdio": "wdio run ./wdio.conf.js"
  },
  "dependencies": {
    "@wdio/allure-reporter": "^8.28.6",
    "@wdio/globals": "^8.28.8"
  }
}
```

### Relevant log output

```typescript
Logs were mentioned above.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by AndreiSakalouskiSalesfloor** [comment]
@BorisOsipov added reproducible example

**Comment by BorisOsipov** [comment]
@AndreiSakalouskiSalesfloor From first sight the fix is pretty easy
in
https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-allure-reporter/src/common/api.ts#L78

replace `tellReporter(events.addTestId, { testId })` with `tellReporter(events.addTestId, { testId, testId })`

Would you mind give a try and fix it? :)

**Comment by AndreiSakalouskiSalesfloor** [comment]
@BorisOsipov I believe in this case  it's better in
https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-allure-reporter/src/reporter.ts

to replace line 725 by `name: linkName || 'tms',` it would have a more concise look in the report and it fixes the issue 

I can create a pr later

**Comment by christian-bromann** [comment]
Thanks for verifying @AndreiSakalouskiSalesfloor !
