### ISSUE TITLE
[🐛 Bug]: Unknown browser name "electron". when setting browserName to 'electron' in standalone mode

### ISSUE THREAD

**Issue by lerouxb** [webdriverio/webdriverio#12087]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.28.8

### Node.js Version

18.16.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
      browserName: 'electron',
      'wdio:electronServiceOptions': {
        appBinaryPath: '/path/to/my/app',
        appArgs: ['foo', 'bar', 'baz'],
      },
```

### What happened?

I'm upgrading our webdriver config for an electron app from 7.x to latest. We used to accomplish this by setting:

```typescript
capabilities: {
      browserName: 'chrome',
      'goog:chromeOptions': {
        binary: '/path/to/our/app/'
        args: ['blah'],
     },
```

but now when running `await remote(options)` webdriver starts to want to download a chromedriver for the relevant chrome version matching the electron version we're using when obviously doesn't work.

We don't use the `wdio.conf.js` style testing, we build an `options` variable that we pass to `await remove(options)` to get a browser instance. I did still look at the documentation here: https://webdriver.io/docs/desktop-testing/electron/configuration and tried to adapt that to a remote options var.

But when I set browserName: 'electron' it hits the error `Error: Unknown browser name "electron". Make sure to pick from one of the following chrome,googlechrome,chromium,chromium-browser,firefox,ff,mozilla,mozilla firefox,edge,microsoftedge,msedge,safari,safari technology preview`

I'm trying to find a way to either get back to the old behaviour or just change our config to move forward. Is it still possible?

### What is your expected behavior?

I expect remote() to just launch our electron app like it did before, connect to it and resolve to a `browser` variable. See https://github.com/mongodb-js/compass/blob/45d585c724d18015ea8c3ca6cba539d538e0b624/packages/compass-e2e-tests/helpers/compass.ts#L607-L638

### How to reproduce the bug.

```typescript
// test.ts
import { remote } from 'webdriverio';

async function run() {
  const options = {
    capabilities: {
      browserName: 'electron',
      'wdio:electronServiceOptions': {
        appBinaryPath: '/path/to/my/app',
        appArgs: ['foo', 'bar', 'baz'],
      },
    }
  }

  const browser = await remote(options);

}

run()
  .then(function () {
    console.log('done');
  })
  .catch(function (err) {
    console.error(err.stack);
  });
```

### Relevant log output

```typescript
npx ts-node test.ts
2024-01-24T19:07:20.114Z INFO webdriver: Initiate new session using the WebDriver protocol
Error: Unknown browser name "electron". Make sure to pick from one of the following chrome,googlechrome,chromium,chromium-browser,firefox,ff,mozilla,mozilla firefox,edge,microsoftedge,msedge,safari,safari technology preview
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> We don't use the `wdio.conf.js` style testing,

Is there any particular reason for this? We recommend to use the WebdriverIO testrunner as you get access to reporting and plugin feature we can't offer otherwise. The Electron service we offer for seamless Electron testing unfortunately only works when using the testrunner.

> But when I set browserName: 'electron' it hits the error

`electron` is not a valid browser name for Chromedriver. It is only supported when using the Electron service. I think something we can improve here is a custom error message, providing better guidance.

**Comment by lerouxb** [comment]
OK I think I found a workaround. By specifying `browserName: 'chromium', browserVersion: '120.0.6099.216'` (ie. the chromium version that the version of electron we're using is built on) it downloads the right chromedriver and things work again. Now I just need to find a programmatic way of working out that version number..

**Comment by lerouxb** [comment]
> Is there any particular reason for this?

I think using a library rather than a whole framework just fits more easily into an existing setup. We already have a cli around all this and a customised mocha setup and we augment the browser object. We stop and start the app arbitrarily depending on the tests, etc. It could probably be ported over, but that's work. `const browser = await remote(options);` is one line that fits anywhere :)

I'm sure the WebdriverIO testrunner works well and is probably the better solution for most people.

**Comment by lerouxb** [comment]
I think we can probably close this as confusion on my end.

**Comment by christian-bromann** [comment]
@lerouxb just note that using the WebdriverIO testrunner and the [Electron service](https://webdriver.io/docs/desktop-testing/electron) has a lot of additional features, e.g. [mocking and stubbing](https://webdriver.io/docs/desktop-testing/electron/mocking) of Electron APIs as well as [accessing](https://webdriver.io/docs/desktop-testing/electron/api) that API in your test for setup purposes. It seems you are working on a project that has given setup for longer already, so if the current setup works for you great. However using the testrunner should be not much work, can remove code that needs to be maintained on your site and gives you access to much more features.

**Comment by lerouxb** [comment]
I'd be most concerned about things like how `browser` seems to be a global. We have several tests that care about starting the app with different command line args or with different env vars set, so creating the browser instance at arbitrary points and with various configurations is necessary. I'd have to look into it to see if our use cases would all be possible.

**Comment by christian-bromann** [comment]
> We have several tests that care about starting the app with different command line args or with different env vars set

This is interesting feedback. We have a `reload` method that can restart a session but never considered one would want to update some capabilities. I will create an issue for this.

> [some of our tests test part of the app running in a browser](https://github.com/mongodb-js/compass/pull/5355)

You are totally able to start more instances when using the testrunner using the [`remote`](https://webdriver.io/docs/api/modules#remoteoptions-modifier) method.

> I'll have to look into it to see if our use cases would all be possible.

Don't hesitate to raise issues if you are missing capabilities. Feedback like this is very valuable so we can tweak the APIs to become more useful. Thanks!
