### ISSUE TITLE
[🐛 Bug]: Unable to maximize the window when using Devtools mode in v7

### ISSUE THREAD

**Issue by rdelhaise-wiiisdom** [webdriverio/webdriverio#12090]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v7.34.0

### Node.js Version

18.18.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
      browserName: 'chrome',
      'goog:chromeOptions': {
        args: argsTab,
        // Don't install automation extension, installing extensions to chrome may require admin privileges
        useAutomationExtension: false,
        // Disable same site cookie enformcement because Tableau Server on Windows doesn't like it
        localState: {
          'browser.enabled_labs_experiments': [
            'same-site-by-default-cookies@2',
            'cookies-without-same-site-must-be-secure@2',
          ],
        },
        prefs: {
          directory_upgrade: true,
          // prompt_for_download: false,
          download: {
            default_directory: downloadDir,
          },
        },
      },
    },
```

### What happened?

I am using WebdriverIO in an electron application, we cannot upgrade to v8 because of ESM. 
I want to migrate to the devtools mode, but, unfortunately, I am unable to maximize the window on chrome because of a known bug resolved in the v8 [PR Link](https://github.com/webdriverio/webdriverio/pull/10883). 

### What is your expected behavior?

I want to do a PR on the v7 to resolve this bug (with the same code) it will be easier than forking the repository entirely. 

### How to reproduce the bug.

- Configure WebdriverIo to use Chrome with the Devtools mode
- Let the window width and height options at null to maximize the window
- The window is not maximized

### Relevant log output

```typescript
None
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> we cannot upgrade to v8 because of ESM.

WebdriverIO v8 also works if tests are written in CJS.

> I want to migrate to the devtools mode

I would not recommend doing this as will deprecate this mode in the next major release (see https://webdriver.io/docs/automationProtocols#devtools-protocol). There is no advantage using this mode anymore. If you like to switch to CDP automation you can always use the `getPuppeteer` command.

> I am unable to maximize the window on chrome because of a known bug resolved in the v8 [PR Link](https://github.com/webdriverio/webdriverio/pull/10883).

Feel free to raise the same PR to the `v7` branch and I can make a release with this fix.

**Comment by rdelhaise-wiiisdom** [comment]
Hello ! 
Thank you for your response and your tips ! 

I did the [PR](https://github.com/webdriverio/webdriverio/pull/12100) ! :)
