### ISSUE TITLE
can't reverse waitForExist on browser.elements

### ISSUE THREAD

**Issue by marcodejongh** [webdriverio/webdriverio#1209]
I don't want any selectors littering my specs. So to check if something isn't there I want to be able to reverse waitForExists on ```browser.elements```

My current workaround is: 

```
expect(function() {
      DashboardPage.body.waitForExists(1000);
}).to.throw();
```

**Comment by christian-bromann** [comment]
`waitForExists` is using `isExisting` which is using `elements`. So if you query the body using the `elements` command, everything should be good.

**Comment by marcodejongh** [comment]
@christian-bromann So I should be able to reverse by adding a second argument?

```
DashboardPage.body.waitForExists(1000, true);
```

**Comment by christian-bromann** [comment]
If you want to wait until an element is gone away just add true as second argument (if you call waitForExist like you did)

**Comment by marcodejongh** [comment]
@christian-bromann this is probably broken for me because of https://github.com/webdriverio/webdriverio/issues/1215
