### ISSUE TITLE
[🐛 Bug]: browser.cdp is not a function

### ISSUE THREAD

**Issue by somecho** [webdriverio/webdriverio#12107]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.29.1

### Node.js Version

18.17.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
let browser = await remote({
  capabilities: {
    browserName: "chrome",
  },
  services: ["devtools"],
});
```

### What happened?

I am trying to use the devtools service with WDIO Standalone mode. Using `browser.cdp` throws the error `browser.cdp is not a function`. 

### How to reproduce the bug.

I've created a minimal reproduction here: https://github.com/somecho/wdio-devtools-repro

### Relevant log output

```typescript
await browser.cdp("Network", "enable");
              ^

TypeError: browser.cdp is not a function
    at file:///D:/code-examples/wdio-devtools-repro/main.mjs:10:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.17.1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@somecho thanks for filing the issue.

The `cdp` command is only available when using the testrunner. We recommend however to use `getPuppeteer` to access the Puppeteer instance of the page to interact with Chrome Devtools.

Join our [Discord Server](https://discord.webdriver.io) for questions like this as you can help much faster than through GitHub issues. Thanks!
