### ISSUE TITLE
[📖 Docs]: document how to set download behavior across browser

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#12105]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Missing documentation

### Description of the improvement / report

It's often a use case that folks like to trigger a download with the browser and verify that the correct file is downloaded. So far browser have not made it easy to automate that, as it is not straight forward how download behavior is defined. Therefore let's make sure to provide guidance here.

### Chrome

To set this up for Chrome, a user needs to use Chrome Devtools, the code is somewhat like this:

```ts
const page = await browser.getPuppeteer()
const cdpSession = /* find out how to get CDP session for page */
await cdpSession.send("Page.setDownloadBehavior", {
  behavior: "allow",
  downloadPath: PATH,
})
```

### Edge

Should be same as Chrome.

### Firefox

For Firefox users have to set certain preferences in the browser, e.g using the [Firefox Profile Service](https://webdriver.io/docs/firefox-profile-service).

### Safari

It's probably not possible, that should be mentioned.

## Acceptance Criteria

- test each browser and find a via-able approach to set download behavior for browser
- create a sub page under _Best Practices_ called _File Downloads_ (alternative suggestions welcome!) 
- document behavior for given browser
- add examples to https://github.com/webdriverio/example-recipes and reference them in docs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
> Can you assign me this one?

Done! Thanks for taking a stab at it 🙏 

> I only need to add examples for chrome, edge, safari, and firefox and write docs about it, right?

That is correct.

**Comment by M-Hammad-Faisal** [comment]
@christian-bromann what should i write about safari? and i shoudl raise my PR against example receipies first and then here in docs. right? 

I was able to automate the safari browser but about download path override i didn't found any way uptil now.

**Comment by M-Hammad-Faisal** [comment]
@christian.bromann, I have created PR in example recipes: https://github.com/webdriverio/example-recipes/pull/336. Can you have a look?  

I got another way to resolve this issue.

```javascript
const page = await browser.getPuppeteer()
const cdpSession = /* find out how to get CDP session for page */
await cdpSession.send("Page.setDownloadBehavior", {
  behavior: "allow",
  downloadPath: PATH,
})
```

we can just pass download path in capabilities options. Check it out in PR!
I have added a ReadMe.md file for further explanation. I am now adding it in docs.

**Comment by christian-bromann** [comment]
@M-Hammad-Faisal I reviewed the example recipes

**Comment by M-Hammad-Faisal** [comment]
@christian-bromann now that remains is just add docs in references in best practice. right?

**Comment by M-Hammad-Faisal** [comment]
@christian-bromann have a look on this PR.

**Comment by christian-bromann** [comment]
Thanks for the contribution @M-Hammad-Faisal
