### ISSUE TITLE
Chai plugin for easier assertions

### ISSUE THREAD

**Issue by marcodejongh** [webdriverio/webdriverio#1210]
This is just an idea of something I might end up doing myself that I want to gather feedback on.
I think the specs can look a lot nicer if there was a webdriverio-chai plugin example plugin assertions:

Some examples:

```
expect(someElement.getText()).to.equal('Whatever');
expect(someElement).to.have.text('Whatever');

expect(otherElement.isExisting()).to.equal(true);
expect(otherElement).to.exist();

expect(function() {
     browser.elements('someElements').waitForExists(1000);
}).to.throw();
expect( browser.elements('someElements')).to.not.exist();
```

Any feedback is welcome, maybe it already exists and I haven't found it.

**Comment by christian-bromann** [comment]
@marcodejongh that looks pretty good! We could enable this functionality as a service for WebdriverIO so that people can use it by adding it to their services:

```js
// wdio.conf.js
// ...
services: ['sauce', 'chai']
// ...
```

The service would need to have the name `wdio-chai-service`. If you want to work on that I could create a repo and make you the maintainer.

**Comment by marcodejongh** [comment]
@christian-bromann I was actually thinking this could be a chai plugin

http://chaijs.com/plugins/

Basically it would add ```browser.element``` & ```browser.elements``` specific support to chai.

And you would set it up like this:

```
//randomspec-test.js
var chai = require('chai');
var chaiWebdriverIO = require('chai-webdriverio');

chai.use(chaiWebdriverIO);
```

**Comment by christian-bromann** [comment]
Well I guess since this is the common way to use chai plugins, so your suggestion might be the better way to do this.

**Comment by marcodejongh** [comment]
It's on my list of things todo, when I have some spare time I'll get started on it. 
Shouldn't be too much work.

**Comment by JamesMGreene** [comment]
Definitely just a Chai plugin, not a WDIO service/framework/plugin.

**Comment by JamesMGreene** [comment]
The first two examples make sense (though revising `.exist();` to `.exist;` to match Chai standard usage:

```js
// normal assertion
expect( someElement.getText() ).to.equal( 'Whatever' );
// custom assertion
expect( someElement ).to.have.text( 'Whatever' );

// normal assertion
expect( otherElement.isExisting() ).to.equal( true );
// custom assertion
expect( otherElement ).to.exist;
```

However, the last example does not directly translate as there is no representation of the waiting aspect:

```js
// normal assertion
expect( function() { browser.elements( '.someElements' ).waitForExists( 1000 ); }).to.throw();
// custom assertion
expect( browser.elements( '.someElements' ) ).to.not.exist;
```

So that last example would need to be vetted further.

One prior art idea to consider is how the [`chai-as-promised` plugin adds an `.eventually` property](https://github.com/domenic/chai-as-promised#shouldexpect-interface) to handle waiting for Promises to resolve, e.g.:

```js
expect( Promise.resolve( { foo: "bar" } ) ).to.eventually.deep.equal( { foo: "bar" } );
```

Something similar could be considered here for the various `waitFor...` pauses.

**Comment by jbhelfrich** [comment]
So, I've been using Chai in my scripts already by adding the following two lines to my before hook in wdio.config:
`        var chai = require('chai').use(require('sinon-chai'));
        chai.should();
`

Is there a reason making it a plugin is necessary?  Am I missing something about the end goal of this plugin?

**Comment by JamesMGreene** [comment]
@jbhelfrich: The proposal is not just to integrate Chai, it is to offer custom WebDriver-specific assertions via a plugin (like `sinon-chai` in your example) for it.

**Comment by monolithed** [comment]
I like chai, but with sync api it does't make any sense to me.  Standard `assert` module does its job well.
PS: My old [plugin](https://www.npmjs.com/package/wdio-chai-plugin) for that

**Comment by christian-bromann** [comment]
There is already a plugin for the selenium-webdriver project: https://github.com/goodeggs/chai-webdriver. Adapting that for WebdriverIO should be easy.

**Comment by marcodejongh** [comment]
@christian-bromann Good tip, I've converted it and just testing it now, will probably create a repo for it later today

**Comment by marcodejongh** [comment]
@christian-bromann https://github.com/marcodejongh/chai-webdriverio That's my intial version I still need to get the tests to work, maybe you can give me a bit of a hand with that? (you have push rights on that repo). Also I'm not sure who should own the repo, do you think it belongs under the webdriverio organisation? If so I'm happy to transfer it

**Comment by christian-bromann** [comment]
> how to start a standalone webdriverio session without using promises

You can't not run commands synchronously in standalone mode so you need to use promises.

> Also I'm not sure who should own the repo, do you think it belongs under the webdriverio organisation? If so I'm happy to transfer it.

I think it should stay wherever it will be maintained 😉 

Awesome to see a chai plugin for WebdriverIO. I'ld be happy to add it to the plugin section on webdriver.io.

**Comment by christian-bromann** [comment]
Let's move this conversation to the plugin repository.

**Comment by mltsy** [comment]
I see this (or a similar thing) has been published on NPM! :) (just wanted to comment here, since this is what I found first)

https://www.npmjs.com/package/chai-webdriver

http://chaijs.com/plugins/chai-webdriver/
