### ISSUE TITLE
[🐛 Bug]: Mocha Step Definition Timeout

### ISSUE THREAD

**Issue by NIBOSAP** [webdriverio/webdriverio#12102]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.27.1

### Node.js Version

18

### Mode

WDIO Testrunner

### What happened?

Local Timeout for step definitions doesn't work:

In the config:
```
framework: 'mocha',
mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },
```

If we want to set a specific timeout for a specific mocha step:
```
    it('Test timeout mocha', async () =>  {
        this.timeout(120000); // 2min
    });
```

The timeout for the step (it) is not set to 2min. And the mocha timeout appears at 1min:

```
 Error in "Test timeout mocha"
Error: Timeout
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
```

Seems to be the same that the one for cucumber: https://github.com/webdriverio/webdriverio/issues/11873

### What is your expected behavior?

Timeout must be taken into account

### How to reproduce the bug.

use repo - https://github.com/NIBOSAP/webdriverIO-with-mochaBDD

and run:
```
npm i
npx wdio wdio.local.conf.ts  --spec ./test/specs/timeout-test.spec.ts
```

### Relevant log output

```typescript
[chrome 120.0.6099.234 mac #0-0] Timeout
[chrome 120.0.6099.234 mac #0-0] Error: Timeout
[chrome 120.0.6099.234 mac #0-0]     at listOnTimeout (node:internal/timers:569:17)
[chrome 120.0.6099.234 mac #0-0]     at processTimers (node:internal/timers:512:7)
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by jhorvat7** [comment]
I do not believe this is a bug and it is working as intended. It's just not possible to change the timeout within a lambda function. It is a simple fix though. Just convert your it block into a non arrow function. Your it block should look like this: 

it('Test timeout mocha', async function () { 
this.timeout(120000); // 2min
 });

I don't remember if it is required that you make your describe block have a non-lambda function with an increased timeout too. It may not be required, but here's what it would look like anyway if you want to be safe (I'm replying on a phone so excuse any odd formatting):

describe('My description', function (){
        this.timeout(120000);

it('Test timeout mocha', async function () { 
this.timeout(120000); // 2min
 });

});

**Comment by vinodreddy-bs** [comment]
Not a Bug. Read this: https://mochajs.org/#arrow-functions. As mentioned by @jhorvat7 try that without lamdas/arrow

**Comment by christian-bromann** [comment]
@vinodreddy-bs good catch 👌

**Comment by NIBOSAP** [comment]
@jhorvat7 @vinodreddy-bs @christian-bromann Thanks a log guys for your replies.

I made a mistake in my examples... I don't have arrow functions in my code but when I got the boiler webdriverIO-with-mochaBDD, I forgot to remove it. My bad...

For the issue, @jhorvat7, I tried this:
```
it('Test timeout mocha', async function () {
     this.timeout(120000); // 2min
});
```
without adding ```this.timeout(120000);``` in the describe, and the timeout is not taken in account.

And, when I tried what you supposed to do:
```
describe('My description', function (){
     this.timeout(120000);

     it('Test timeout mocha', async function () {
          this.timeout(120000); // 2min
     });
});
```
The timeout is set for all 'it' blocks. So it works also without the ```this.timeout(120000);``` in the it:
```
describe('My description', function (){
     this.timeout(120000);

     it('Test timeout mocha', async function () {

     });
});
```

I thought that we can set a specific timeout for a specific 'it' block, It's what I want to do. So, what to do you think? Should this be possible ?  Many thanks.

**Comment by NIBOSAP** [comment]
I found another way to set the timeout for a specific 'it', and it works:

```
it('Test timeout mocha', async function () {
    
}).timeout(120000);
```

Thanks :)

**Comment by BorisOsipov** [comment]
@talbss feel free to create a new issue with [a reproducible ](examplehttps://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues)
