### ISSUE TITLE
Developer guide: Selenium server link broken

### ISSUE THREAD

**Issue by AlexRex** [webdriverio/webdriverio#1211]
The link in the [Developer Guide](http://webdriver.io/guide.html) for downloading the Selenium server looks be broken: [http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.48.2.jar](http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.48.2.jar)

But changing the version to *2.48* before the first slash makes it work again. [http://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar](http://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar)

**Comment by christian-bromann** [comment]
Thanks for noticing. Fixed it and goes live soon!
