### ISSUE TITLE
[🐛 Bug]: [wdio-appium service]: Excessive Repeated Logging of Appium Connection Status after Update to 8.29.3

### ISSUE THREAD

**Issue by lararojasmr** [webdriverio/webdriverio#12134]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.29.3

### Node.js Version

latest

### Mode

WDIO Testrunner

### What happened?

Hello,

After updating WebDriverIO from version 8.29.1 to 8.29.3, I've encountered a logging issue with the wdio-appium-service. There is an excessive amount of repeated log messages displaying the Appium connection status. Specifically, the log is flooded with countless instances of the message:

"INFO @wdio/appium-service: Appium started with ID: 496446"

This issue was not present in version 8.29.1 and seems to have started immediately after the update to 8.29.3. Attached is a screenshot that illustrates the extent of the repeated logging.

![image](https://github.com/webdriverio/webdriverio/assets/15206513/e5f45784-d583-49c3-bc93-10c4d3483d2e)

It’s important to note that while I am reporting this issue, it was initially discovered and commented on by a user named @picakia. His observations can be found in the comments section of a related GitHub pull request: #12095 (Issue: Bug #12094).

### What is your expected behavior?

Only one log per connection.

### How to reproduce the bug.

Execute a test case that use appium service in webdriverio

### Relevant log output

```typescript
To many logs indicating that the server is started.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by lararojasmr** [comment]
Working on it now.

**Comment by christian-bromann** [comment]
Hey @lararojasmr 👋 any updates?

**Comment by christian-bromann** [comment]
This seems to be fixed, thanks @lararojasmr for the fix 👍
