### ISSUE TITLE
Opens a new browser for each individual test

### ISSUE THREAD

**Issue by alexmngn** [webdriverio/webdriverio#1214]
## The problem

When I run the my tests, `wdio wdio.jasmine.conf.js` opens a new browser instance for each individual file that has tests.
If I have 2 test files, Chrome opens 2 instances. The tests are running in parallel. Is there a way to have them running in a unique browser one after the others? 

## Environment

* WebdriverIO version: 4.0.5
* Node.js version: 4.3.2
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio

## Config file

```
exports.config = {

   /**
   * server configurations
   */
   host: '0.0.0.0',
   port: 4444,

   /**
   * specify test files
   */
   specs: [
      './tests/**/test.js'
   ],

   /**
   * capabilities
   */
   capabilities: [{
      browserName: 'chrome',
   }],

   /**
   * test configurations
   */
   logLevel: 'silent',
   coloredLogs: true,
   screenshotPath: 'shots',
   baseUrl: 'http://www.google.com',
   waitforTimeout: 10000,
   framework: 'jasmine',

   reporter: 'spec',
   reporterOptions: {
      outputDir: './'
   },

   jasmineNodeOpts: {
      defaultTimeoutInterval: 9999999
   },

   /**
   * hooks
   */
   onPrepare: function() {
      console.log('let\'s start');
   },
   onComplete: function() {
      console.log('that\'s it');
   }
};
```

**Comment by marcodejongh** [comment]
You can set the ```maxInstances``` to 1 inside the config.

http://webdriver.io/guide/testrunner/configurationfile.html

**Comment by christian-bromann** [comment]
Yes, you can restrict the global maxInstance property (see https://github.com/webdriverio/webdriverio/blob/master/examples/wdio.conf.js#L52-L60) to execute one test at a time
