### ISSUE TITLE
[🐛 Bug]: Rate limit issue on GitHub Actions

### ISSUE THREAD

**Issue by nzakas** [webdriverio/webdriverio#12143]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.29.1

### Node.js Version

20.11.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
"chrome" and "firefox" capabilities
```

### What happened?

On https://github.com/humanwhocodes/humanfs/pull/62, GitHub Actions are failing due to a rate limit error. I'm unsure if this is an issue with GitHub or a WebDriver issue, but wanted to report it.

Note: Not all of the runs failed, which is strange.

### What is your expected behavior?

CI should succeed and run the tests.

### How to reproduce the bug.

No specific repro, as some of the runs worked and one didn't.

### Relevant log output

```typescript
> @humanfs/web@0.2.0 test
> wdio run ./wdio.conf.js


Execution of 2 workers started at 2024-02-02T00:14:37.646Z

Error: Error: Couldn't find version name in releases: {"message":"API rate limit exceeded for 20.75.95.162. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
    at download (file:///home/runner/work/humanfs/humanfs/node_modules/geckodriver/dist/install.js:38:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async Promise.all (index 0)
    at async Launcher.run (file:///home/runner/work/humanfs/humanfs/node_modules/@wdio/cli/build/launcher.js:102:13)
Error: Couldn't find version name in releases: {"message":"API rate limit exceeded for 20.75.95.162. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
    at download (file:///home/runner/work/humanfs/humanfs/node_modules/geckodriver/dist/install.js:38:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async Promise.all (index 0)
    at async Launcher.run (file:///home/runner/work/humanfs/humanfs/node_modules/@wdio/cli/build/launcher.js:102:13)
npm ERR! Lifecycle script `test` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @humanfs/web@0.2.0 
npm ERR!   at location: /home/runner/work/humanfs/humanfs/packages/web
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting @nzakas - this is related to recent changes https://github.com/webdriverio-community/node-geckodriver/issues/345 - unfortunately Mozilla has shut down some sources we used before. I will take a look for alternatives.

**Comment by christian-bromann** [comment]
I fixed the issue (hopefully), please update your `package-lock.json` to get the latest [`geckodriver`](https://www.npmjs.com/package/geckodriver) `v4.3.2`.

**Comment by nzakas** [comment]
Thanks, I'll give it a shot!
