### ISSUE TITLE
add documentation for ...

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#1216]
- [x] how to split up test specs and how they are getting executed (maxInstances etc)
- [ ] how to use timeouts which does what?
- [x] change all old jsonwebdriver links to the w3 specs
- [x] change element to elements in PO example
- [x] write a page about the browser object and how to get information about capabilities and options
- [x] update standalone examples (not use callbacks)

**Comment by patthiel** [comment]
@christian-bromann  Will the first point cover the inability to call `init()` and `end()` when using the wdio runner and how the wdio runner treats each spec file as an individual session?

**Comment by christian-bromann** [comment]
> Will the first point cover the inability to call init() and end() when using the wdio runner and how the wdio runner treats each spec file as an individual session?

yes

**Comment by fijijavis** [comment]
@christian-bromann an example of how the `--suite` flag should be used would be nice.  I haven't had any luck figuring this one out.
