### ISSUE TITLE
[🐛 Bug]: getSize() typing expects at least 1 argument

### ISSUE THREAD

**Issue by therealbrad** [webdriverio/webdriverio#12173]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### What happened?

When using getSize() in TypeScript I get a compile error:
`Expected 1 arguments, but got 0.`

### What is your expected behavior?

[getSize()](https://webdriver.io/docs/api/element/getSize) argument is optional.

### How to reproduce the bug.

https://github.com/therealbrad/wdio-getsize shows the bug
Note the test passes, but TypeScript complains:
```Expected 1 arguments, but got 0.
Property 'height' does not exist on type 'number'.
Property 'width' does not exist on type 'number'.```

### Relevant log output

```typescript
Expected 1 arguments, but got 0.
Property 'height' does not exist on type 'number'.
Property 'width' does not exist on type 'number'.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Hey @therealbrad , thanks for raising the issue.

It seems like we are loosing the optional information when trying to map the types to the prototype: https://github.com/webdriverio/webdriverio/blob/0cba687a8df2464ca970b26c2bab9cd78e5bdccc/packages/webdriverio/src/types.ts#L20-L24

```ts
type ChainablePrototype = {
    [K in ElementQueryCommands]: (...args: Parameters<$ElementCommands[K]>) => ChainablePromiseElement<ThenArg<ReturnType<$ElementCommands[K]>>>
} & {
    [K in ElementsQueryCommands]: (...args: Parameters<$ElementCommands[K]>) => ChainablePromiseArray<ThenArg<ReturnType<$ElementCommands[K]>>>
}
```

**Comment by justalemming** [comment]
same issue with [getLocation()](https://webdriver.io/docs/api/element/getLocation/). Here the docs also don't specify the `prop` as optional.
