### ISSUE TITLE
Feature request: config for maxCapabilities

### ISSUE THREAD

**Issue by PeteOnTheGitHub** [webdriverio/webdriverio#1217]
Hi :)

Great Project!

We have a feature request around the issue of: 
On browserstack we have an account with the parallel limit of 2. However our capabilities (or browser matrix) contains 24 different browser types to cover. Even with maxInstances to 1 wdio test runner will try and spin up 24 different VM's on browserstack.

The ideal solution would be a maxCapabilities configuration that would limit the amount of capabilities created at a time and deal with sequencing of the capabilities at the maxCapabilities parallel limit. So similar to maxInstances, accept for capabilities.

Do you think this is with the scope of the wdio test runner?  If so if you require I can create a PR.

Regards,
Pete

**Comment by christian-bromann** [comment]
This is already possible. You can assign `maxInstances` for on specific capability but also for all (see [here](https://github.com/webdriverio/webdriverio/blob/master/examples/wdio.conf.js#L52-L60)).
