### ISSUE TITLE
[🐛 Bug]: breaking change in webdriverio@8.21.0 (logic of moveTo is changed)

### ISSUE THREAD

**Issue by DudaGod** [webdriverio/webdriverio#12185]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

18.12.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: {
  browserName: 'chrome',
},
```

### What happened?

The logic of the `moveTo` command has changed in this PR - https://github.com/webdriverio/webdriverio/pull/11529.

Previously (before webdriverio@8.21.0) when you specifying a coordinate `xOffset` and `yOffset`, it was counted from the upper-left corner of the element. It is even specified in the documentation of the command - https://webdriver.io/docs/api/element/moveTo. But it actually works from the center now.

There is a major change and it shouldn't have been released as a feature. Do you agree with me? Can we roll back these changes?

### What is your expected behavior?

I expect that `moveTo` command works exactly the same as in webdriverio@8.20.5.

### How to reproduce the bug.

Test:
```
// wdio.mjs
import {remote} from 'webdriverio';

let browser;

(async () => {
    try {
        const browser = await remote({
            logLevel: 'trace',
            capabilities: {
                browserName: 'chrome',
            },
        });

        await browser.url('http://localhost:4000');

        const elem = await browser.$("header");
        await elem.moveTo({ xOffset: 0, yOffset: 0 });

        await browser.debug();

        await browser.deleteSession();
    } catch (err) {
        console.log('ERR:', err);
        if (browser) {
            await browser.deleteSession();
        }
    }
})();
```

Server:
```
// server.js

const express = require('express');
const app = express();
const port = 4000;

app.get('/', async (req, res) => {
  const html = `
<html>
    <head>
        <style>
            body {
                margin: 0;
            }
            header {
                background-color: green;
                height: 50px;
            }
            header:hover {
                background-color: white;
            }
            footer {
                background-color: yellow;
                height: 50px;
            }
            footer:hover {
                background-color: black;
            }
        </style>
    </head>
    <body background-color>
        <header>HEADER</header>
        <footer>FOOTER</footer>
    </body>
    <script type="text/javascript">
        document.body.style.backgroundColor = "red";
        document.body.style.height = "1000px";

        function onMousePosition(e) {
          console.log(e.pageX, e.pageY);
        }

        document.addEventListener('mousemove', onMousePosition, false);
        document.addEventListener('mouseenter', onMousePosition, false);
    </script>
</html>
`;

  res.send(html);
});

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`)
});
```

Run server:
```
node server.js
```

Run test:
```
node wdio.mjs
```

### Relevant log output

```typescript
Log inside devtools:

600 25
```

Expected log:
```
0 0
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment]
Hi @DudaGod do we not strictly follow semantic versioning but we try to be realistic about changes.
There's a difference between the intention and the actual result, example: a change that should not break things, in reality accidentally breaks something.

I feel it makes sense to update the docs accordingly if needed and move forward instead of rolling anything back.

**Comment by christian-bromann** [comment]
I'ld suggest to update the docs on this command saying that the offset starts from the center of the element.

> There is a major change and it shouldn't have been released as a feature. Do you agree with me?

Yes and no. Technically it is a change in behavior and therefor a breaking change however if we would see semver that strict, we would constantly have to release major versions. We only define a change as breaking change if it actually impacts all user. This behavior is very niche and only affects folks that used x/yOffset in a `moveTo` command.

Any contributions are appreciated, thanks!

**Comment by M-Hammad-Faisal** [comment]
@christian-bromann in this scenario, all i need is to update the docs that offset starts from center of element. right? If yes, you can assign me the issue.

**Comment by christian-bromann** [comment]
Yes, I think this is the best resolution here. I don't see a reason why we should keep it at 0,0 and why this would be better as oppose to from the center.

**Comment by M-Hammad-Faisal** [comment]
ok. then you can assign me this one. Can you tell me which file i need to update?

**Comment by DudaGod** [comment]
> Yes and no. Technically it is a change in behavior and therefor a breaking change however if we would see semver that strict, we would constantly have to release major versions. We only define a change as breaking change if it actually impacts all user. This behavior is very niche and only affects folks that used x/yOffset in a moveTo command.

And how do you know how many users use the command `moveTo` with x/yOffset? To my mind, the right decision would be to postpone this change until the next major. Or at least explicitly specify in the release notes that this change can break your code. Currently this change is specified in "Polish" section.

**Comment by erwinheitzman** [comment]
The release and the changelog have been updated stating that it's a breaking change.

**Comment by erwinheitzman** [comment]
I have not tested this but I think a quick workaround could be something like this if you have a lot of test related code that you cannot refactor right away, hope it helps.
```js
await browser.overwriteCommand('moveTo', async (originalMoveToFn, offsets) => {
  const { height, width } = this.getSize();
  originalMoveToFn(offsets ? {
    x:  offsets.x - (width / 2),
    y: offsets.y - (height / 2),
  } : undefined);
}, true);
```

**Comment by christian-bromann** [comment]
@DudaGod thanks for your feedback. This is a good learning for us (mostly me) and we will be more careful about this moving on.

**Comment by christian-bromann** [comment]
Docs got updated in https://github.com/webdriverio/webdriverio/pull/12226, thanks @DudaGod and @M-Hammad-Faisal
