### ISSUE TITLE
Custom commands are not chainable

### ISSUE THREAD

**Issue by LKay** [webdriverio/webdriverio#1218]
## The problem

I have fe custom methods defined but I can't chain them with other standard commands. They, however work fine when are called outside chain. I run my tests in async mode and have imported all custom methods so they are accessible. Promises are transferred to `chai-as-promised` based on docs example. How to use custom commands in async mode as part of methods chain?

## Environment

* WebdriverIO version: 4.0.5
* Node.js version: 5.8.0
* Mode: wdio testrunner
* Additional wdio packages used (if applicable): `wdio-mocha-framework`, `chai` + `chai-as-promised`

## Output

```
․

0 passing (3.70s)
1 failing

1) should pass:
browser.url(...).waitForExist(...).isExisting(...).should.eventually.be.true.isExisting(...).should.eventually.be.true.elementsCount is not a function
running chrome
TypeError: browser.url(...).waitForExist(...).isExisting(...).should.eventually.be.true.isExisting(...).should.eventually.be.true.elementsCount is not a function
```

## Code To Reproduce Issue

I have some methods defined in external file:
```javascript
module.exports = {
    "elementsCount" : function async (selector) {
        return new Promise((resolve, reject) => {
            this
                .elements(selector)
                .then((res) => {
                    if (!res || res.status === -1) {
                        reject()
                    }
                    resolve(res.value.length)
                })
        })
    }
}
```

This file gets imported to `wdio`confi.js` file and inside `before()` hook custom commands are added:

```javascript
{
   ...
   before : function () {
        chai.should()
        chai.use(chaiAsPromised)

        Object.keys(customCommands).forEach((command) => browser.addCommand(command, customCommands[command]))
        chaiAsPromised.transferPromiseness = browser.transferPromiseness

        global.expect = chai.expect
    },
    ...
}

```

Then when I try to use them as part of chain in the test I get the error that my custom command method is not defined:

```javascript
describe("Header", function () {
    context("General", function () {
        it("should pass", function async () {
            browser
                .url("/")
                .waitForExist(".navbar", TIMEOUT)
                .isExisting(".navbar .navbar-header .navbar-brand").should.eventually.be.true
                .isExisting(".navbar .navbar-nav.navbar-right").should.eventually.be.true
                .elementsCount(".navbar .navbar-nav.navbar-right > li").should.eventually.equal(0)
        })
    })
})
```

**Comment by christian-bromann** [comment]
Thanks for reporting. I fixed the issue.
Will have to publish a new version of wdio-sync which means that I also have to release a new version of the framework adapters. I will let you know here once this is done.

**Comment by maximilianschmitt** [comment]
Hi, was this fixed in the meantime? It's not possible to chain custom commands for me with the latest version of webdriver.
