### ISSUE TITLE
[💡 Feature]: Bump puppeteer-core to version 22.0.0

### ISSUE THREAD

**Issue by somecho** [webdriverio/webdriverio#12192]
### Is your feature request related to a problem?

I am currently using `getPuppeteer` (from `webdriverio 8.30.0`) to get all the requests from a page. This is working great, but sometimes the `HTTPRequest.postData()` method returns `undefined`, despite the payload being well formed when viewed from developer tools in the browser. 

According to the Puppeteer docs:
>True when the request has POST data. Note that [HTTPRequest.postData()](https://pptr.dev/api/puppeteer.httprequest.postdata) might still be undefined when this flag is true when the data is too long or not readily available in the decoded form. In that case, use [HTTPRequest.fetchPostData()](https://pptr.dev/api/puppeteer.httprequest.fetchpostdata)

`fetchPostData` is available only in 22.0.0. 

### Describe the solution you'd like.

Bump the version of puppeteer than WebDriverIO uses to version 22.0.0 so these methods are available for standalone webdriverio use. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by erwinheitzman** [comment]
This is resolved by https://github.com/webdriverio/webdriverio/pull/12355
