### ISSUE TITLE
WDIO SKIPS test when using Cucumber tags

### ISSUE THREAD

**Issue by ken4ward** [webdriverio/webdriverio#12202]
Thanks everyone. I want to run tests based on the tags I added. But whenever tag is added, it skips the test, what is the issue?
Log
```
2024-02-08T09:22:36.058Z INFO @wdio/cli: [0-0] SKIPPED in android - file:///cucumber/features/en/onboard_wikipedia.feature
2024-02-08T09:22:36.059Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2024-02-08T09:22:36.059Z INFO @wdio/cli:launcher: Run onComplete hook
Report successfully generated to ./report/allure/allure-report
```

Festure file
```
@onboard
Feature: Language Selection and Onboarding in Wikipedia App

  Scenario: User adds a new language and completes onboarding
    Given the user has launched the Wikipedia app

```
.env file
`TAG=@onboard`

wdio.conf.js
```
let TAGS_EXPRESSION = process.env.TAG ? process.env.TAG : '';
TAGS_EXPRESSION += ' and not @defect and not @manual and not @wip and not @local';

cucumberOpts: {
        tagExpression: TAG_EXPRESSION,
    }, 

```

I have also tried tags, it didn't work either. Any way I can resolve this issue? When I console print the value in wdio.conf.js file. I see that it reads the value from .env file. If I run the test without tags, it works. the downside is that it'll always run all test, and I only want to run specific test that I add tags to.

**Comment by nextlevelbeard** [comment]
You appear to have a typo, `TAG_EXPRESSION` !== `TAGS_EXPRESSION`

**Comment by erwinheitzman** [comment]
I resolved this on Discord and we can close this, right @ken4ward ?

**Comment by ken4ward** [comment]
Sure, we can. Thanks, @erwinheitzman
