### ISSUE TITLE
WDIO Multiremote example is always launching Firefox

### ISSUE THREAD

**Issue by buscape** [webdriverio/webdriverio#1220]
## The problem

Running the wdio.multiremote example is always launching two Firefox Instances instead of two Chrome Instances.

## Environment

* WebdriverIO version: 4.0.5
* Node.js version: 5.6.0
* wdio testrunner (synchronous)

## How to Reproduce
* Follow the instructions from the examples [here](https://github.com/webdriverio/webdriverio/tree/master/examples)
* Fire up a selenium server with chromedriver (I just installed the [selenium-standalone-package](https://www.npmjs.com/package/selenium-standalone) and ran `selenium-standalone install && selenium-stanalone start`)
* Execute `./bin/wdio examples/wdio/wdio.multiremote.conf.js`
* Two Firefox browsers are spawning although both desiredCapabilities are requiring chrome.

May be worthy to note that when I run `./bin/wdio examples/wdio/wdio.mocha.conf.js` the three browsers (Chrome, Phantom, Firefox) are launched as expected.

Thanks for all the great work you're doing on this project by the way, keep it up!

**Comment by christian-bromann** [comment]
Indeed! There seems to be a problem.

**Comment by christian-bromann** [comment]
Fixed, will be released with v4.0.6. Can't give any ETA on that though.
