### ISSUE TITLE
Problems with capabilities

### ISSUE THREAD

**Issue by mjancarik** [webdriverio/webdriverio#1222]
There are several problems with capabilites. The first one is that the capabilities are deleted from required config file which is cached so the re-running tests using default Firefox and not my defined capabilities. The second one is that the capabilites are not merged from incoming argv in the Launcher class https://github.com/webdriverio/webdriverio/blob/master/lib/launcher.js#L8-L23

**Comment by christian-bromann** [comment]
> re-running tests using default Firefox

What do you mean by re-running tests?

> are not merged from incoming argv in the Launcher class

they do: https://github.com/webdriverio/webdriverio/blob/master/lib/launcher.js#L11

Don't see a problem here. Closing.

**Comment by christian-bromann** [comment]
@mjancarik I now understand the part with the deleted configs. What's your usecase? Usually you only use a config once

**Comment by mjancarik** [comment]
I use gulp-webdriver for my tests. There is not problem for single run test. But when I writing test I use gulp watch and re-run gulp task 'test:e2e' which is same as described in [usage](https://github.com/webdriverio/gulp-webdriver#usage) section. For the first running test webdriverio use my defined capabilities but for the second running test webdriverio use Firefox because the capabilites are deleted from cached object for [require](https://github.com/webdriverio/webdriverio/blob/master/lib/utils/ConfigParser.js#L87). So I tried use argv for giving capabilites to webdriverio but I found that is not suppurted [argument](https://github.com/webdriverio/webdriverio/blob/master/lib/cli.js#L36).

**Comment by christian-bromann** [comment]
While updating the `gulp-webdriver` package I faced the same problem which can be annoying and doesn't have to be there. Will fix it.
