### ISSUE TITLE
[🐛 Bug]: Expect not found when using as a global in latest expect-webdriverio

### ISSUE THREAD

**Issue by ShannonH** [webdriverio/webdriverio#12229]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

20.11.1

### Mode

Standalone Mode

### What happened?

I recently upgraded my wdio packages from 8.29.3 -> 8.31.1 and expect-webdriverio from 4.9.4 -> 4.11.4. After that, the expect global stopped being recognized. All usages of expect are underlined in my IDE. The linter started reporting `error TS2304: Cannot find name 'expect'.` as well. 
I didn't change anything in my project except upgrading packages. This also happens in a brand new project where I just ran yarn create wdio and added mocha types.
The only workaround is explicitly importing expect, which I don't think is needed according to https://webdriver.io/docs/api/globals
![CleanShot 2024-02-13 at 08 58 04@2x](https://github.com/webdriverio/webdriverio/assets/2179605/3e4257e8-4b80-4851-938c-8833bf4ee6bc)

### What is your expected behavior?

With injectGlobals being true, I shouldn't have to explicitly import expect

### How to reproduce the bug.

To reproduce:
1. create a new wdio project that uses typescript and every other default - `yarn create wdio .`
2. run `yarn install`
3. open the test.e2e.ts file in an IDE
4. remove the explicit import for expect (for some reason the default project is using an explicit import despite injectGlobals being true by default?)
5. or run something like `tsc --noEmit` to view compilation errors because expect isn't found

Repro repo: https://github.com/ShannonH/clean-install-wdio (it's a basic install plus what's needed for TS/mocha so I could test a run)

### Relevant log output

```typescript
shannon.harris@sharrismbp23 clean-install-wdio % tsc --noEmit
test/specs/test.e2e.ts:9:15 - error TS2304: Cannot find name 'expect'.

9         await expect(SecurePage.flashAlert).toBeExisting()
                ~~~~~~

test/specs/test.e2e.ts:10:15 - error TS2304: Cannot find name 'expect'.

10         await expect(SecurePage.flashAlert).toHaveTextContaining(
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by ShannonH** [comment]
I've also upgraded my work project to expect-webdriverio 4.11.7 after @erwinheitzman suggested it might be fixed in the latest, but no joy.
The repro repo has the latest for everything.

**Comment by christian-bromann** [comment]
@ShannonH thanks for reporting and sorry for the inconvenience. We have reverted [the change](https://github.com/webdriverio/expect-webdriverio/commit/2eac1de04fe7c7172adcfda3de421f63a8560e7d) and triggered a new release. Please update your `expect-webdriverio` version and all should be ok again.
