### ISSUE TITLE
[🐛 Bug]: It seems that `@wdio/cli` does not parse the `wdio.conf.{ts/js}` configuration file but uses it directly.

### ISSUE THREAD

**Issue by 1111mp** [webdriverio/webdriverio#12248]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v8.31.1

### Node.js Version

v20.6.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
"@wdio/cli": "^8.31.1",
"@wdio/globals": "^8.31.1",
"@wdio/local-runner": "^8.31.1",
"@wdio/mocha-framework": "^8.31.1",
"@wdio/spec-reporter": "^8.31.1",
"wdio-electron-service": "^6.3.0",
"webdriverio": "^8.31.1"

"electron": "^28.2.2",

platform: macOS Sonoma 14.3.1
```

### What happened?

The configuration in the configuration file `wdio.conf.{ts/js}` will not take effect. When I quickly checked the source code, I found that `@wdio/cli` did not parse these configuration files. The key code is here: [packages/wdio-cli/src/commands/run.ts#L235C48-L235C63](https://github.com/webdriverio/webdriverio/blob/ec6597be34a119f6498e2bd39e6a173ed81d097e/packages/wdio-cli/src/commands/run.ts#L235C48-L235C63)

```ts
const { configPath = 'wdio.conf.js', ...params } = argv
/**
argv {
  _: [ 'run' ],
  '$0': 'node_modules/@wdio/cli/bin/wdio.js',
  configPath: './wdio.conf.ts',
  'config-path': './wdio.conf.ts'
}
*/

// ...

const tsNodeProjectFromEnvVar = process.env.TS_NODE_PROJECT &&
            path.resolve(process.cwd(), process.env.TS_NODE_PROJECT)
        // The file should be parsed in advance to obtain the configuration data
        const tsNodeProjectFromParams = params.autoCompileOpts?.tsNodeOpts?.project &&
            path.resolve(process.cwd(), params.autoCompileOpts?.tsNodeOpts?.project)
        const tsNodeProjectRelativeToWdioConfig = path.join(path.dirname(wdioConf.fullPath), 'tsconfig.json')
        if (tsNodeProjectFromParams) {
            console.log('Deprecated: use the TS_NODE_PROJECT environment variable instead')
        }
        const localTSConfigPath = (
            tsNodeProjectFromEnvVar ||
            tsNodeProjectFromParams ||
            tsNodeProjectRelativeToWdioConfig)
        const hasLocalTSConfig = await fs.access(localTSConfigPath).then(() => true, () => false)
        const p = await execa(nodePath, process.argv.slice(1), {
            reject: false,
            cwd: process.cwd(),
            stdio: 'inherit',
            env: {
                ...process.env,
                ...(hasLocalTSConfig ? { TS_NODE_PROJECT: localTSConfigPath } : {}),
                NODE_OPTIONS
            }
        })
```
It should be that the step of parsing and reading the contents of the `./wdio.conf.ts` file is missing.

---

Maybe this is the right fix (I have tested it locally):

```ts
async function loadConfigData(isTSFile, path) {
     const { createRequire } = await import("node:module").then(module => module.default)
    const require = createRequire(import.meta.url)
    isTSFile && require('ts-node/register')
    const data = require(path);
    return data.default ? data.default : data;
}

const { config: wdioConfig } = await loadConfigData(isTSFile, wdioConf.fullPath);
console.log("wdioConfig", wdioConfig);
// wdioConfig {
//     runner: 'local',
//     outputDir: 'wdio-logs',
//     autoCompileOpts: {
//       autoCompile: true,
//       tsNodeOpts: { project: './tsconfig.test.json', transpileOnly: true }
//     },
//     specs: [ './src/__tests__/specs/**/*.ts' ],
//     exclude: [],
//     maxInstances: 10,
//     capabilities: [
//       {
//         browserName: 'electron',
//         'wdio:electronServiceOptions': [Object]
//       }
//     ],
//     logLevel: 'info',
//     bail: 0,
//     baseUrl: '',
//     waitforTimeout: 10000,
//     connectionRetryTimeout: 120000,
//     connectionRetryCount: 3,
//     services: [ [ 'electron', [Object] ] ],
//     framework: 'mocha',
//     reporters: [ 'spec' ],
//     mochaOpts: { ui: 'bdd', timeout: 60000 }
//   }

const tsNodeProjectFromParams = wdioConfig.autoCompileOpts?.tsNodeOpts?.project &&
            path.resolve(process.cwd(), wdioConfig.autoCompileOpts?.tsNodeOpts?.project);
```

### What is your expected behavior?

Configuration of `wdio.conf.{ts/js}` should work properly.

### How to reproduce the bug.

Just start the test through the configuration file, like: `"test": "wdio run ./wdio.conf.ts"`

Code example: [https://github.com/1111mp/nvm-desktop/tree/tsup](https://github.com/1111mp/nvm-desktop/tree/tsup)

### Relevant log output

```typescript
`const { configPath = 'wdio.conf.js', ...params } = argv`

Before:

argv {
  _: [ 'run' ],
  '$0': 'node_modules/@wdio/cli/bin/wdio.js',
  configPath: './wdio.conf.ts',
  'config-path': './wdio.conf.ts'
}


After:

wdioConfig {
  runner: 'local',
  outputDir: 'wdio-logs',
  autoCompileOpts: {
    autoCompile: true,
    tsNodeOpts: { project: './tsconfig.test.json', transpileOnly: true }
  },
  specs: [ './src/__tests__/specs/**/*.ts' ],
  exclude: [],
  maxInstances: 10,
  capabilities: [
    {
      browserName: 'electron',
      'wdio:electronServiceOptions': [Object]
    }
  ],
  logLevel: 'info',
  bail: 0,
  baseUrl: '',
  waitforTimeout: 10000,
  connectionRetryTimeout: 120000,
  connectionRetryCount: 3,
  services: [ [ 'electron', [Object] ] ],
  framework: 'mocha',
  reporters: [ 'spec' ],
  mochaOpts: { ui: 'bdd', timeout: 60000 }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by 1111mp** [comment]
I've added a reproducible example: [https://github.com/1111mp/nvm-desktop/tree/tsup](https://github.com/1111mp/nvm-desktop/tree/tsup)

**Comment by christian-bromann** [comment]
Before we go with above suggested solution, can we do some research how other projects like Vitest are solving this problem?

**Comment by 1111mp** [comment]
@christian-bromann I checked the source code of `Vitest` and found that it uses `Vite` to parse the configuration file. When `Vite` parses configuration files, it compiles them into `.js` files through `esbuild`, and then loads them to finally obtain the configuration data.

`webdriverio` uses `ts-node`, so similar to `Vite`, we need to compile the configuration file based on `ts-node` to obtain its data. I have initially completed the relevant core code locally:
```ts
// for commonjs
// we can directly `require` it
const { createRequire } = await import("node:module").then(module => module.default)
const require = createRequire(import.meta.url)
isTSFile && require("ts-node/register")

// This is the configuration data we want to get
const config = require(wdioConf.fullPath)

---

// for `esmodule` it’s a little different

// .mjs
const config = await import(wdioConf.fullPath)

// .mts
const { compile } = require("ts-node").register({
        compilerOptions: {
            "target": "ES2022",
            "module": "ESNext",
            "moduleResolution": "node",
            "resolveJsonModule": true,
            "esModuleInterop": true,
            "sourceMap": false,
            "allowJs": true,
        },
        esm: true
    })

    const code = compile(await fs.readFile(wdioConf.fullPath, { encoding: 'utf8' }), wdioConf.fullPath);

    try {
        await fs.writeFile("./temp.mjs", code)
        const config = await import("./temp.mjs")
        console.log(config)
    } finally {
        await fs.unlink("./temp.mjs")
    }
```

**Comment by christian-bromann** [comment]
@1111mp do you think there is a way to read the config file without having to write it to file system? Also any reasons why you use `require("ts-node/register")` instead of `import("ts-node/register")`?

**Comment by 1111mp** [comment]
> do you think there is a way to read the config file without having to write it to file system?

For `.mts`, I have not found a better way yet. For `esmodule`, `ts-node` cannot recognize and compile `.mts` code at runtime like `CommonJS` (because the keyword becomes `import` in `esmodule`). In `CommonJS` `ts-node` recognizes and compiles them with `typescript` by registering extension hooks for `require` (require.extensions['.ts'] = function () {}), then redirects using something like `require()` method to load them. All this does not work in `esmodule`. We need to explicitly compile `.mts` files into `.mjs` files.

Please feel free to correct me if I got something wrong.

Another way is to let the user provide `esm loader`(for `.mts`):
```ts
// you can directly import .mts files in this way
const config = await import(wdioConf.fullPath)

// but it requires extra work when running the command
"test": "TS_NODE_PROJECT=tsconfig.json NODE_OPTIONS=\"--loader ts-node/esm\" wdio run ./wdio.conf.mts"
```

> Also any reasons why you use require("ts-node/register") instead of import("ts-node/register")?

Just to test some issues, we can use `import("ts-node/register")`.

**Comment by christian-bromann** [comment]
Thanks for the investigation on this. My only concern with this is that we are now loading the config file 3 times:

1. to get the right tsconfig options in the test runner process
2. to read for WebdriverIO options in the test runner process
3. to read for WebdriverIO options in the worker process

I recognize this problem now and at the time when I visited the code last time I was ok with the limitation of having to define specific tsconfig options via environment variable or parameters like `--autoCompileOpts.tsNodeOpts.project=./otherTsconfig.json`. Before we move on with this, let's identify the cases where the current approach fails. Afaik it is currently only a problem if you have a different path to a tsconfig file other that `tsconfig.json` in the root directory. Is this assumption correct?

**Comment by 1111mp** [comment]
Yes, you are right. I neglected to get the `WebdriverIO` option after the `launch` call. My mistake, sorry.

As warned here, I think I should just use `TS_NODE_PROJECT=tsconfig.test.json`:
```ts
if (tsNodeProjectFromParams) {
    console.log('Deprecated: use the TS_NODE_PROJECT environment variable instead')
}
```
