### ISSUE TITLE
[🐛 Bug]:  chromedriver available at a new domain  storage.googleapis.com

### ISSUE THREAD

**Issue by jacekcho** [webdriverio/webdriverio#12251]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

20

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [
    {
      browserName: 'chrome',
      acceptInsecureCerts: true,
      'goog:chromeOptions': {
        ...(isMobile() && {
          mobileEmulation: { deviceName: 'Pixel 2' }
        }),
        ...(isHeadless() && {
          args: ['--headless', '--disable-gpu', '--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage']
        })
      }
    }
  ],
```

### What happened?

from version 121.0.6167.85 the chrome driver is available under a new domain:
```
storage.googleapis.com
```

https://googlechromelabs.github.io/chrome-for-testing/#stable 

https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json 

### What is your expected behavior?

use proper domain  to download chromedriver 
https://storage.googleapis.com/chrome-for-testing-public/ 

### How to reproduce the bug.

update chrome and run a test

### Relevant log output

```typescript
2024-02-15T13:39:01.543Z ERROR webdriver: Failed downloading chromedriver v121.0.6167.184: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.184/mac-arm64/chromedriver-mac-arm64.zip, retrying ...
Error: Error: Failed downloading chromedriver v121.0.6167.184: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.184/mac-arm64/chromedriver-mac-arm64.zip, retrying ...
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by PetrKnedlik** [comment]
Having the same issue

**Comment by gjvoosten** [comment]
Our GitHub Actions are failing because of this; error during the build while running our WebdriverIO tests:

> Error: Failed downloading chromedriver v121.0.6167.184: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.184/linux64/chromedriver-linux64.zip, retrying ...

**Comment by BorisOsipov** [comment]
We don't download browser\drivers directly, but use @puppeteer/browsers. The issue seems will be fixed in 
https://github.com/puppeteer/puppeteer/pull/11923 and after release we have to update dependency in wdio.

**Comment by owens-ben** [comment]
Also having this issue. 

Error: Error: Failed downloading chromedriver v121.0.6167.184: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.184/linux64/chromedriver-linux64.zip, retrying ...
    at file:///home/runner/work/web/web/test/node_modules/@wdio/utils/build/node/utils.js:105:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _install (file:///home/runner/work/web/web/test/node_modules/@wdio/utils/build/node/utils.js:102:5)
    at async _install (file:///home/runner/work/web/web/test/node_modules/@wdio/utils/build/node/utils.js:102:5)
    at async setupChromedriver (file:///home/runner/work/web/web/test/node_modules/@wdio/utils/build/node/utils.js:261:17)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Launcher.run (file:///home/runner/work/web/web/test/node_modules/@wdio/cli/build/launcher.js:102:13)
    at async Module.run (file:///home/runner/work/web/web/test/node_modules/@wdio/cli/build/run.js:64:20)

**Comment by jsilvaqa** [comment]
also receiving same error
Failed downloading chromedriver v121.0.6167.184: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.184/mac-arm64/chromedriver-mac-arm64.zip, retrying ...

**Comment by karthikeyan-sage** [comment]
Even I am facing the same error.Error: Error: Failed downloading chromedriver v121.0.6167.184: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.184/mac-arm64/chromedriver-mac-arm64.zip, retrying ...

**Comment by benstein** [comment]
Our builds are also failing with the same. Any workarounds?
`-----> chromedriver app detected
-----> Looking up latest chromedriver version...
-----> Downloading chromedriver v121.0.6167.184...
curl: (22) The requested URL returned error: 404
`

**Comment by oscarocornejo** [comment]
@voropa I found this temp fix, adding an old version for your capability.

```browserVersion: "122.0.6261.39"```

**Comment by voropa** [comment]
> @voropa @benstein I found this temp fix, adding an old version for your capability.
> 
> `browserVersion: "122.0.6261.39"`

It works, thank you!

**Comment by noelly** [comment]
it works as well 
![Screenshot 2024-02-16 at 1 25 10 PM](https://github.com/webdriverio/webdriverio/assets/21228092/85b9b279-2e7d-4080-b79c-69e6d40027d3)

**Comment by paymand** [comment]
Should be fixed once https://github.com/webdriverio/webdriverio/pull/12303 is merged.

**Comment by paymand** [comment]
Tentative workaround: https://github.com/webdriverio/webdriverio/pull/12304

**Comment by SinghMegha27** [comment]
The current stable version at this website shows : https://googlechromelabs.github.io/chrome-for-testing/#stable
![image](https://github.com/webdriverio/webdriverio/assets/149373865/a77d930c-b071-472d-af95-229f9dca0bc8)
![image](https://github.com/webdriverio/webdriverio/assets/149373865/1e209789-c66c-4f0a-a793-7cf554200e48)
but with these version things were not working but after specifying this 
capabilities: [{
        browserName: 'chrome',
        browserVersion: '122.0.6261.39'
    },
    
    the code worked, but this should not be the way. I mean I can see multiple PRs has been raised for this chromedriver mismatch issue but wdio community is not able to recover this problem.

**Comment by SinghMegha27** [comment]
Got This error Downloading Chromedriver v121.0.6167.185        
2024-02-18T14:50:45.738Z WARN webdriver: Chromedriver v121.0.6167.185 don't exist, trying to find known good version..
Then tried adding browserVersion : stable,
capabilities: [{
        browserName: 'chrome',
        browserVersion: 'stable'
    },
    
    after which got this error Error: Error: Couldn't find a matching chrome browser for tag "121.0.6167.184" on platform "win64", although at this website : https://googlechromelabs.github.io/chrome-for-testing/#stable
    the stable version is 
![image](https://github.com/webdriverio/webdriverio/assets/149373865/2842da37-ec8d-4162-8604-fa678dea575b)
then after going through multiple PRs comments gave the version as 122.0.6261.39
then finally had luck. 

**But now my point is this work around is going to work always or again some version mismatch problem will arise ?**

**Comment by adalakoti90** [comment]
@SinghMegha27  use below it will work
browserVersion: 'dev'

**Comment by xinxin11** [comment]
after setting chromedriverCustomPath and use the local chrome driver, why it still download the chrome driver from the website?

**Comment by NikGithub2023** [comment]
I am facing the same error as I run my automated tests. 
Error HTTP 404 executing https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.184/win64/chromedriver-win64.zip
Starting ChromeDriver 114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}) on port 64839
Only local connections are allowed.

**Comment by zohids** [comment]
> @SinghMegha27 use below it will work browserVersion: 'dev'
It works for me
Thanks!

**Comment by irisfaraway** [comment]
@oleksiizozulenko I am seeing the same issue with Firefox after updating to v8.32.2 to fix the Chromedriver problem.

I was wondering if it may be because the `installOptions` are always being set to have `baseUrl: CHROMEDRIVER_BASE_URL` in `setupPuppeteerBrowser()` regardless of the browser, rather than just for Chromedriver downloads?

**Comment by cvakiitho** [comment]
You can set capabilities to link paths to driver/browser: 

```
capabilities: [
    {
      browserName: "chrome",
      "wdio:chromedriverOptions": {
        binary: <chromedriverBinaryPath>
      },
      "goog:chromeOptions": {
        binary: <chromeBinaryPath>,
```

https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-utils/src/node/utils.ts#L282 

But I would also vote for the flag, as mentioned previously :) https://github.com/webdriverio/webdriverio/issues/10965

**Comment by christian-bromann** [comment]
> I'd be happy to raise a PR if the approach makes sense, @christian-bromann?

Thanks! I suggest an alternative solution which is having the Chromedriver service to set hostname and port so that `definesRemoteDriver` returns `true` and skips download of all browser. What do you think?

**Comment by christian-bromann** [comment]
> Couldn't find a matching firefox browser for tag "124.0a1" on platform "mac"

@oleksiizozulenko we are investigating the issue as we see it in our builds as well.

**Comment by jan-molak** [comment]
> I  suggest an alternative solution which is having the Chromedriver service to set hostname and port so that definesRemoteDriver returns true and skips download of all browser. What do you think?

This sounds cleaner; I wasn't aware of `definesRemoteDriver`.

It looks like [`wdio-chromedriver-service` is deprecated](https://github.com/webdriverio-community/wdio-chromedriver-service?tab=readme-ov-file#readme), though, so perhaps folks shouldn't rely on it?

**Comment by nextlevelbeard** [comment]
@christian-bromann  I seem to have Firefox issue fixed on my end.
Opened issue https://github.com/webdriverio/webdriverio/issues/12322 and there is a tentaive fix at https://github.com/webdriverio/webdriverio/pull/12323

**Comment by christian-bromann** [comment]
> It looks like [`wdio-chromedriver-service` is deprecated](https://github.com/webdriverio-community/wdio-chromedriver-service?tab=readme-ov-file#readme), though, so perhaps folks shouldn't rely on it?

Yeah, there is no need to use Chromedriver at this point anymore as this functionality is built into WebdriverIO now.

**Comment by christian-bromann** [comment]
This has been fixed in https://github.com/webdriverio/webdriverio/pull/12305 .. please let us know if you still run into any issues. This unfortunately has been thrown at us over the weekend as Chrome stopped supporting that specific endpoint and their transition to the new one was rather rough since we were not notified before.

**Comment by wolasss** [comment]
> This has been fixed in #12305 .. please let us know if you still run into any issues. This unfortunately has been thrown at us over the weekend as Chrome stopped supporting that specific endpoint and their transition to the new one was rather rough since we were not notified before.

Will this be fixed in v7 as well?

**Comment by oscarocornejo** [comment]
@mascok @seadcehic this should already be fixed in the new released version of WDIO.
Just update to latest.

**Comment by wolasss** [comment]
> > Is this the latest version you are talking about 7.35.0?
> 
> Are you using the Chromedriver service or Selenium Standalone service?

I am using `"@wdio/selenium-standalone-service": "7.33.0"` and still stuck with this issue. Unfortunately I cannot upgrade to webdriver v8 because my project runs on node v14.

**Comment by christian-bromann** [comment]
@wolasss we have [fixed](https://github.com/webdriverio/selenium-standalone/pull/875) this for selenium-standalone, can you check that you are using `selenium-standalone@9.3.3`?
