### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by b3hdad** [webdriverio/webdriverio#1226]
## The problem

Logging doesn't work on Windows. 

## Environment

* WebdriverIO version:3.4.0
* Node.js version: 5.8.0
* OS: Windows

## Details

While running the driver on Windows we get an error that the log file does not exist. The
Log file name has the character ":" which prevents the driver from creating it on the file system.

## Fix

I tried to do a pull request but don't have access. I think the following can fix the problem:

Add the following to the package.json:

`"sanitize-filename": "1.5.3",`

And update the lib/utils/Logger.js file, by adding the following to the method getLogfile before the return line:

`
if (/^win/.test(process.platform)) {
            filename = sanitize(filename)
        }
`

**Comment by christian-bromann** [comment]
Fixed. No need for an extra package for these characters :wink: . Will be released with the next version (v4.0.6).

**Comment by b3hdad** [comment]
Awesome, thanks @christian-bromann
