### ISSUE TITLE
[🐛 Bug]: Cursor disappears from terminal after running wdio

### ISSUE THREAD

**Issue by zeljkofilipin** [webdriverio/webdriverio#12269]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.32.1

### Node.js Version

20.11.1

### Mode

Standalone Mode

### What happened?

Every time I run a wdio script, the cursor from the terminal disappears. Cursor is very useful if I want to use wdio repl (via browser.debug) or if I want to edit a command in terminal.

I have reproduced this on macos 14.3.1 and ubuntu 22.04.3.

### What is your expected behavior?

The cursor should still be there.

Before, there is a cursor:

<img width="842" alt="before" src="https://github.com/webdriverio/webdriverio/assets/23927/cc8c8e2e-b8e1-4f5b-a286-e93a7831a9da">

After running the script, the cursor is gone:

<img width="842" alt="after" src="https://github.com/webdriverio/webdriverio/assets/23927/7d8a6aa2-976c-4dfc-8d40-153f925545af">

### How to reproduce the bug.

I have created a very small script:

https://github.com/zeljkofilipin/wdio-simple

After the repo is cloned, run the script

```
npm ci
node ./run-in-script.js
```

### Relevant log output

```typescript
Nothing in log output is relevant, but I can't submit the issue without entering something here.

$ node ./run-in-script.js
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment]
That terminal does not look like the default iirc. Did you change any settings / install anything related to your terminal?

**Comment by k03mad** [comment]
Also encountered this issue, but only when running locally with Chromedriver/Chrome
Could not reproduce with the remote browser

System details:
— zsh 5.9 (arm-apple-darwin22.1.0)
— wdio 8.30.0
— default macOS terminal application

"Resolved" by adding `console.log('\u001B[?25h')` at the onWorkerStart hook...
