### ISSUE TITLE
provide screenshot data to the event

### ISSUE THREAD

**Issue by sullenor** [webdriverio/webdriverio#1229]
Hi,

I found out that sometimes webdriver doesn't provide enougth information to the allure reporter which may result in errors.

I made a small research and found out if webdriver tries to make a screenshot manually, it emits screenshot event with empty data:

https://github.com/webdriverio/webdriverio/blob/master/lib/webdriverio.js#L218
https://github.com/webdriverio/webdriverio/blob/master/lib/webdriverio.js#L221-L225

which is collected by baseReporter:

https://github.com/webdriverio/webdriverio/blob/master/lib/runner.js#L91-L98
https://github.com/webdriverio/webdriverio/blob/master/lib/utils/BaseReporter.js#L82-L84

So, in the end we will get something like this:

```javascript
{
  event: 'runner:screenshot',
  specs: ['xx'],
  filename: 'name_of_the_file',
  data: undefined,
}
```

And exception occurs somewhere here after: https://github.com/webdriverio/wdio-allure-reporter/blob/master/lib/reporter.js#L162 (see the issue: https://github.com/webdriverio/wdio-allure-reporter/issues/7).

I managed to build a small example which reproduces it: https://github.com/sullenor/wdio-bugreport/tree/reporter

**Comment by sullenor** [comment]
Since, there is no possibility to restore the full path to the screenshot file from the reporter I think we can fetch it manually before event will be emitted: https://github.com/webdriverio/webdriverio/pull/1230

Also it will make the consistent API.

**Comment by christian-bromann** [comment]
Let's continue conversation on #1230
