### ISSUE TITLE
[🐛 Bug]: TypeError: browser.cdp is not a function when called in `before` hook

### ISSUE THREAD

**Issue by dianabarsan** [webdriverio/webdriverio#12321]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

v21.5.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  browserName: 'chrome',
}
```

### What happened?

If I try to access any devtools function in a before hook, an error is thrown. It looks like a race condition where the `before` hook in the config is run before the service is fully registered. 
If I add a timeout in the `before` hook before accessing devtools functions, everything works as expected. 

### What is your expected behavior?

I expect to be able to call devtools commands in the `before` hook without errors. 

### How to reproduce the bug.

Sample config that triggers the error: https://gist.github.com/dianabarsan/a0bafcec06d2dcd0741b3ca62708b59c

Example of before hook that throws error: 
```
before: async () => {
    await browser.cdp('Log', 'enable');
}
```

Example of before hook that does *not* throw an error:
```
before: async () => {
    do {
      await new Promise(r => setTimeout(r, 10));
    } while (typeof browser.cdp === 'undefined');

    await browser.cdp('Log', 'enable');
}
```

Simply running `wdio run ./config.js` should 

### Relevant log output

```typescript
[0-0] RUNNING in chrome - file:///test.spec.js
[0-0] 2024-02-19T18:52:11.742Z ERROR @wdio/utils:shim: TypeError: browser.cdp is not a function
[0-0]     at Object.before (/home/diana/projects/sandbox/wdio/config.js:21:19)
[0-0]     at file:///home/diana/projects/sandbox/node_modules/@wdio/utils/build/shim.js:32:27
[0-0]     at new Promise (<anonymous>)
[0-0]     at file:///home/diana/projects/sandbox/node_modules/@wdio/utils/build/shim.js:29:47
[0-0]     at Array.map (<anonymous>)
[0-0]     at executeHooksWithArgs (file:///home/diana/projects/sandbox/node_modules/@wdio/utils/build/shim.js:29:33)
[0-0]     at Runner.run (file:///home/diana/projects/sandbox/node_modules/@wdio/runner/build/index.js:99:15)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@dianabarsan we don't recommend to use the devtools service for CDP activity anymore. This service is deprecated and will be removed with v9. Instead, use the `getPuppeteer` command to access a Puppeteer instance connected to the browser you are automating.

I will go ahead and close this as it is unlikely we are working on fixing this issue as we already focus on v9. Happy to answer further question if you have any. Thanks!

**Comment by dianabarsan** [comment]
Thank you for the information. I've switched to getting a Puppeteer instance instead of using `cdp`.
