### ISSUE TITLE
[🐛 Bug]: Seeing vulnerabilities when installing @wdio/sauce-service >=8.0.6

### ISSUE THREAD

**Issue by JuanHerH** [webdriverio/webdriverio#12325]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.10.5

### Node.js Version

v18.14.2

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
Bug is not related to capabilities
```

## Repro steps
- Using node 18
- Create a folder, say "test"
- Cd to that folder
- Run “npm init -y” which will create package.json file
- Run this command “npm install @wdio/sauce-service --save-dev”
## Issue
Non fixable vulnerability detected even in newer versions of @wdio/sauce-service

### What is your expected behavior?

Installing the dependency, but not adding vulnerabilities to the project

### How to reproduce the bug.

- Run "npm install @wdio/sauce-service --save-dev" in any repository
- Then run npm audit 
- You should be able to see the following warning:
```
# npm audit report

ip  <=2.0.0
Severity: high
NPM IP package vulnerable to Server-Side Request Forgery (SSRF) attacks - https://github.com/advisories/GHSA-78xj-cgh5-2h22
fix available via `npm audit fix --force`
Will install @wdio/sauce-service@8.0.2, which is a breaking change
node_modules/ip
  @wdio/sauce-service  >=8.0.6
  Depends on vulnerable versions of ip
  node_modules/@wdio/sauce-service

2 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```
- Running `npm audit fix --force` will install older version and breaking the sauce labs e2e execution

### Relevant log output

```typescript
# npm audit report

ip  <=2.0.0
Severity: high
NPM IP package vulnerable to Server-Side Request Forgery (SSRF) attacks - https://github.com/advisories/GHSA-78xj-cgh5-2h22
fix available via `npm audit fix --force`
Will install @wdio/sauce-service@8.0.2, which is a breaking change
node_modules/ip
  @wdio/sauce-service  >=8.0.6
  Depends on vulnerable versions of ip
  node_modules/@wdio/sauce-service

2 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Please see this comment: https://github.com/indutny/node-ip/issues/136#issuecomment-1952930767 .. this vulnerability has been fixed in `ip@v1.1.9` which is automatically downloaded when the package is installed.
