### ISSUE TITLE
How can I utilize callbacks in page object pattern design?

### ISSUE THREAD

**Issue by lawrencechong** [webdriverio/webdriverio#1234]
For my test, I created a page object in which I would click a label and that label redirects me to a new page. The goal is to verify the header name in the new page. The problem I am having is that after I click on the label and retrieve the text on the new page, the remainder the callback doesn't run. 

Page.js
    function Page(){
	var client = webdriverio.remote(options)
	var page = client
		.init()
		.url('https://www.1stdibs.com/');
	this.page = page
    }

    Page.prototype.clickLabel = function(label) {
	return this.page.click('#label');
    }

    Page.prototype.getHeader = function() {
	this.page.getText('.browse-header').then(function(value){
		console.log(value)
		return value
	})
    };
    module.exports = Page

Test.js

    var page = new Page();
			page
				.clickLabel('ABC').then(function(done){
					console.log('clicked')
					page.getHeader().then(function (value) {
      // After getHeader prints to console in page object it should also print to  console the same value, but     it never reaches here                     
						console.log('retreived it' + value) // doesnt' reach here
                                               assert.equal(value, 'ABC') // doesn't reach here
					})
					done()
				})

`

**Comment by christian-bromann** [comment]
Hey @lawrencechong,
please checkout our page object example ([here](https://github.com/webdriverio/webdriverio/tree/master/examples/pageobject)) and most importantly the documentation page for that [here](http://webdriver.io/guide/testrunner/pageobjects.html).

**Comment by lawrencechong** [comment]
Hey @christian-bromann thanks for sharing the two examples. I'm still not seeing why after I call my getHeader function in the test and it executes the method, it doesn't finish on with the: " .then(function (value) { " chain on

**Comment by christian-bromann** [comment]
@lawrencechong you don't even return the promise in getHeader. Please give the example a try and go from there on.
