### ISSUE TITLE
non-Error exceptions are not caught

### ISSUE THREAD

**Issue by YousefED** [webdriverio/webdriverio#1235]
## The problem

```
client.init().then(() => throw "stringerror").then(() => console.log("resolved"), () => console.log("rejected")));
```

The above code results in "resolved". This is because you check explicitly for Error objects in webdriverio.js:resolve (```if (result instanceof Error) {```), but in safeExecute the value caught can be any value (also non-Error objects such as strings;

## Environment

* WebdriverIO version: 4.0.5
* Node.js version:
* [Standalone mode]
* if wdio testrunner, running synchronous or asnychronous tests:
* Additional wdio packages used (if applicable):

**Comment by christian-bromann** [comment]
@YousefED why would someone throw a string error?

**Comment by YousefED** [comment]
I agree, but it's valid javascript. You just can't expect the object that you catch to be of type Error.
If I'm using a library which throws different kind of objects as exceptions, it'll currently result in my resolve handler to be called.

**Comment by christian-bromann** [comment]
> but it's valid javascript

Well that doesn't mean it is correct JavaScript. I doubt that any assertion library does that.

**Comment by YousefED** [comment]
Especially if it's not "correct" javascript, wouldn't you want to prevent webdriverio from silently resolving it as a non-error?

**Comment by YousefED** [comment]
Also, according to the Promises spec: https://promisesaplus.com/

> “exception” is a value that is thrown using the throw statement.

**Comment by christian-bromann** [comment]
But how I am suppose to catch the error if it is not from type string?

**Comment by YousefED** [comment]
I think the issue should be solved in safeExecute. This is where you currently catch all exceptions, but then translate them to a regular return value (of which later only Error types are converted to rejections).

First time I'm diving into the webdriverio source code though - so my assessment could be incorrect :)

**Comment by christian-bromann** [comment]
I will try to recreate this issue in a test and will return an error. Thanks for letting me know :+1:

**Comment by YousefED** [comment]
Cool, thanks. I don't think this solution complies with the Promises spec though, which brings me to another question: should webdriverio be Promises/A+ compliant? I saw some earlier discussion regarding this in #402 but not sure whether this has implemented (I'm asking because I ran into several other issues combining webdriverio with promises).

**Comment by christian-bromann** [comment]
> should webdriverio be Promises/A+ compliant?

Yes! As far as possible

**Comment by YousefED** [comment]
Ok, in that case I'll also open issues for other stuff I ran into. Need to dig into it again though :)
