### ISSUE TITLE
chaining filter function for elements with addComand

### ISSUE THREAD

**Issue by redexp** [webdriverio/webdriverio#1236]
Hello, I want to create method which will filter elements and chain them to next browser methods. For example filter visible elements

``` javascript
browser.addComand('filterVisible', function async (selector) {
  var elements = browser.elements(selector).value.filter(function (item) {
    return browser.elementIdDispalyed(item.ELEMENT);
  });

  browser.lastResult = {value: elements};
});

browser.addComand('first', function async (selector) {
  var element = browser.elements(selector).value[0];

  browser.lastResult = {value: element};
});

browser
  .elements('.btn')
  .filterVisible()
  .first()
  .click();
```

But this code will not work. Is there way to filter and chain value?
- WebdriverIO version: 4.0.5
- Node.js version: 5.4
- wdio testrunner synchronous

**Comment by christian-bromann** [comment]
@redexp you need to make sure to return an object in order to be able to chain your custom commands. Please don't `lastResult` , it's an internal variable and changing it could lead to side effects.

**Comment by redexp** [comment]
@christian-bromann Looks like added commands are not chainable at all. I can't call them right after `.elements()` for example.
Next code will throw error `browser.elements(...).filterElements is not a function`
```javascript
browser.addCommand('filterElements', function () {});

browser.elements('input').filterElements();
```

**Comment by albertogasparin** [comment]
I'm having a similar issue. Let's take this simple wrapper:
```js
// wdio.config.js > before()
browser.addCommand('waitForHidden', function (selector, ms) {
  return this.waitForVisible(selector, ms, true);
});

// test.js - throws "selector needs to be typeof 'string'"
browser.element('.my-elem').waitForHidden(); 

// test.js - works
browser.waitForHidden('.my-elem');
```
Either I'm doing it wrong or for some reason custom commands run in a different "context".

**Comment by christian-bromann** [comment]
@redexp you need to return something otherwise the result of the custom command will be undefined and you can't chain commands, so do
```js
browser.addComand('filterVisible', function async (selector) {
  return browser.elements(selector).value.filter(function (item) {
    return browser.elementIdDispalyed(item.ELEMENT);
  });
});
```

@albertogasparin I will have to investigate this what do you get as arguments in your waitForHidden method?

**Comment by albertogasparin** [comment]
In the example: 
```js
browser.element('.my-elem').waitForHidden(); 
```
the custom command is called without arguments. I was expecting at least the selector (as the built-in commands do) but both `selector` and `ms` remain undefined.

**Comment by bimusiek** [comment]
Hey, I have the same issue. 
I tried to access `this.lastResult` or find anything in `this` but I cannot. 

Any idea how to get element here?

**Comment by mkj28** [comment]
Seeing similar issue to @albertogasparin : 
```
 Error: selector needs to be typeof `string`
     at elements() - getLocation.js:18:17
     at getLocation(".composition-send") - index.js:267:37
     at elementIdDisplayed("43") - isVisible.js:71:55
```


For a function defined like this:
```
    browser.addCommand('waitForAnimation', function(selector, timeout = config.waitforTimeout) {
      const INTERVAL = 100;
      let prevLocation = { x: false, y: false };
      let location = browser.getLocation(selector);
      let i = 0;
      while (location.x !== prevLocation.x || location.y !== prevLocation.y) {
        if (i * INTERVAL > timeout) {
          console.log(`Element '${selector} did not stop moving in more than ${timeout}ms'`);
          return;
        }
        browser.pause(INTERVAL);
        prevLocation = location;
        location = browser.getLocation(selector);
        i++;
      }
    });
```


WebdriverIO version: 4.9.11
Node.js version: v7.10.1
wdio testrunner synchronous

**Comment by mkj28** [comment]
for me changing `browser.addCommand('waitForAnimation', function(selector, timeout = config.waitforTimeout) {` to `browser.addCommand('waitForAnimation', function **async**(selector, timeout = config.waitforTimeout) {`
but I am not sure why it worked to be honest

**Comment by christian-bromann** [comment]
Hey,

we update the core architecture of WebdriverIO and with that a lot of implementation details that might make this issue obsolete. Please try with the latest version of WebdriverIO and verify if this still occurs. If so please open a new issue and we will tackle it asap.

Thanks!
