### ISSUE TITLE
Unable to use Nested getText to read hundreds of record.

### ISSUE THREAD

**Issue by Vinlite** [webdriverio/webdriverio#1237]
Initially I used to use 4-5 nested getText to read multiple columns of a table with 100 records. I never faced any issues for this.

But when I have to read 500 records, the speed with which the text is being read, slows down and it ends up failing the test case. I increased the individual test case timeout and still it is happening.

I am using webDriverIO ver2.4.5 along with Jasmine in a framework.

Is this a known issue or is something going wrong?

**Comment by christian-bromann** [comment]
> I am using webDriverIO ver2.4.5 along with Jasmine in a framework.

This is a pretty old version, have you thought about updating it?

**Comment by Vinlite** [comment]
We are using the Framework at my workplace. Sadly I cant change anything much in it. I will suggest it though.

Sent from my Windows Phone
________________________________

**Comment by christian-bromann** [comment]
It makes a lot of sense to update to the latest version. I don't think that I will work on any fixes for v2.x anymore.
