### ISSUE TITLE
[🐛 Bug]: Missing resigningEnabled sauce:option in @wdio/types

### ISSUE THREAD

**Issue by AlexRivero** [webdriverio/webdriverio#12397]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

20.11.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [
        {
            // maxInstances can get overwritten per capability. So if you have an in-house Selenium
            // grid with only 5 firefox instances available you can make sure that not more than
            // 5 instances get started at a time.
            // maxInstances: 5,
            //
            // browserName: 'chrome',
            // acceptInsecureCerts: true
            // If outputDir is provided WebdriverIO can capture driver session logs
            // it is possible to configure which logTypes to include/exclude.
            // excludeDriverLogs: ['*'], // pass '*' to exclude all driver session logs
            // excludeDriverLogs: ['bugreport', 'server'],     

            //SAUCELABS (Android 13 on Google Pixel)
            platformName: 'Android',
            'appium:app': 'storage:<storageId>',
            'appium:deviceName': 'Google.*',
            'appium:platformVersion': '13',
            'appium:automationName': 'UiAutomator2',
            'appium:noReset': true,
            'appium:autoWebview': false,
            'appium:autoGrantPermissions': true,
            'sauce:options': { 
                build: `Test Build`, 
                appiumVersion: 'appium2-20231101',
                resigningEnabled: true
            }
        },
    ],
```

### What happened?

Saucelabs is requiring Instrumentation to be active on all apps to be able to run automated tests. There's a sauce:option that lets the user enable it, but it is not declared in the @wdio/types' SauceLabsCapabilities interface

When adding the _resigningEnabled_ capability to sauce:options I get the following compilation error on all the other capabilities but the _resigningEnabled_ one:
Type 'string' is not assignable to type 'WebdriverIO'.ts(2322)

I have added @wdio/types (latest version) in the package.json, but _resigningEnabled_ doesn't seem to be declared in it.

When manually declaring it in @wdio/types/build/Capabilities.d.ts, the compilation error goes away and it is actually sent within the desired capabilities to SauceLabs appium server

### What is your expected behavior?

Since now it is mandatory to have Instrumentation active, _resigningEnabled_ capability should be known by @wdio/types

### How to reproduce the bug.

Add _resigningEnabled:true_ capability to sauce:options

### Relevant log output

```typescript
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by AlexRivero** [comment]
I've just submitted a PR (https://github.com/webdriverio/webdriverio/pull/12398) in which I add the resigningEnabled capability to the SauceLabsCapabilities interface at @wdio/types

**Comment by christian-bromann** [comment]
Thanks for the contribution. I merged the PR. Mind raising the same to the `v8` branch so it can be release to the current WebdriverIO versions?

**Comment by AlexRivero** [comment]
I've submitted a PR to the v8 branch as well: https://github.com/webdriverio/webdriverio/pull/12399

Really excited to contribute to this project (with my first contribution ever)! Thanks, @christian-bromann!

**Comment by christian-bromann** [comment]
Congrats on your first contribution @AlexRivero .. your PRs got merged! There are some build issues in `main` and `v8` that we are trying to resolve, but don't worry about that. We will release as soon as these issues are resolved.
