### ISSUE TITLE
Setting window size

### ISSUE THREAD

**Issue by filidorwiese** [webdriverio/webdriverio#124]
Since you've helped me out so well with my previous question, I thought I'd ask another. When making screenshots after opening the page, I noticed the window size is rather small. So small in fact that the mobile styling/logic is in place. It seems that .windowHandleSize() is the method to increase the window size, however I can't seem to find out how to actually use it. Could you give me an example?

**Comment by iDVB** [comment]
This does not seem to work for me in some browsers.
Chrome defaults to fixed width and height.
However, when screenshoting on Firefox it always seems to be longscroll of the whole body.

Code:
```javascript
var webdriverio = require('webdriverio');

var client = webdriverio.remote({
        desiredCapabilities: {
            browserName: 'chrome',
            version: '41.0',
            platform: 'OS X 10.10',
            tags: ['examples'],
            name: 'OSX Chrome'
        },
        host: 'ondemand.saucelabs.com',
        port: 80,
        user: process.env.SAUCE_USERNAME,
        key: process.env.SAUCE_ACCESS_KEY,
        logLevel: 'silent'
    }).init();
 
client
    .url('http://www.cnn.com/')
    .windowHandleSize({width: 1024, height: 768})
    .pause(1000)
    .saveScreenshot('./output/chrome/1.png')
    .end();
```

**Comment by iDVB** [comment]
UPDATE
I also tried this...
```javascript
var webdriverio = require('webdriverio');

var client = webdriverio.remote({
        desiredCapabilities: {
            browserName: 'firefox',
            version: '36.0',
            platform: 'OS X 10.10',
            tags: ['examples'],
            name: 'OSX Firefox'
        },
        host: 'ondemand.saucelabs.com',
        port: 80,
        user: process.env.SAUCE_USERNAME,
        key: process.env.SAUCE_ACCESS_KEY,
        logLevel: 'silent'
    }).init();
 
client
    .url('http://www.cnn.com/')
    .setViewportSize({
        width: 1024,
        height: 768
    })
    .windowHandleSize(function(err, res) {
        console.log(res.value); // outputs: "{ width: 1024, height: 773 }"
    })
    .pause(1000)
    .saveScreenshot('./output/firefox/1.png')
    .end();
```

As you can see, the console output almost looks right, but more importantly the image that gets output is **1024x4524** in size. Obviously not following the requested viewport size.

**Comment by christian-bromann** [comment]
@iDVB taking screenshots has nothing to do with the browser dimension. Firefox always captures the whole document no matter the size of your browser window. There is actually nothing you can do about this but cropping it by yourself. I recommend to use [WebdriverCSS](https://github.com/webdriverio/webdrivercss) for those kind of tasks
