### ISSUE TITLE
getUrl does not actually exist

### ISSUE THREAD

**Issue by AngryPidgeon** [webdriverio/webdriverio#1240]
## The problem

client.getUrl is not actually a function on the client object, its undefined.  I've tried all possible spellings imaginable and all of them are undefined.  This should be pretty simple to reproduce.  I believe I'm on 4.0.5

How can I access the current url?

**Comment by AngryPidgeon** [comment]
EBWODP: the "url" method with no parameters does what I want it to do, but the docs are misleading and should be updated anyways.  If "getUrl" is not supported, then remove it from the docs.

**Comment by christian-bromann** [comment]
`getUrl` is [supported](https://github.com/webdriverio/webdriverio/blob/master/lib/commands/getUrl.js) and [tested](https://github.com/webdriverio/webdriverio/blob/master/test/spec/getUrl.js). I am not sure how you've accessed it but it should be there.

**Comment by tbradley-sans** [comment]
I know it's been 2.5 years since this bug was closed, but I think it's broken again in 5.0.3. 

See here: https://github.com/webdriverio/webdriverio/issues/3194
