### ISSUE TITLE
How to get browser name with the browser instance?

### ISSUE THREAD

**Issue by yhjor1212** [webdriverio/webdriverio#1242]
as title

**Comment by christian-bromann** [comment]
Please give a detailed description of your use case and add code if possible, otherwise I don't know how to answer this question.

**Comment by yhjor1212** [comment]
I searched through the api (http://webdriver.io/api.html) and I failed to find any usage to show what is the current capabilities like what kind of browser I am using (e.g. firefox, chrome, etc).

Usage:
const name = browser.browserName;

So that I can use the name variable to further determine which logic I should run depend on different browser.

**Comment by christian-bromann** [comment]
You can get the browser name by accessing `browser.desiredCapabilities.browserName`. I will make sure we better document this kind of stuff

**Comment by osmolyar** [comment]
@christian-bromann  browser.desiredCapabilities.browserName seems to have no relation to the browser tests are currently running in, alternating apparently at random among all the ones configured in wdio.conf.js.  Is there any way to access the name of the currently-running browser if multiple desired capabilities are configured?

**Comment by christian-bromann** [comment]
> browser.desiredCapabilities.browserName seems to have no relation to the browser tests are currently running in

Not sure what you mean by this. It gives you exactly the browser name that you are currently running in your test.

> Is there any way to access the name of the currently-running browser if multiple desired capabilities are configured?

see above

**Comment by mo** [comment]
Just FYI; in webdriverio 5.x it no longer works to read browser.desiredCapabilities.browserName but you can instead use browser.capabilities.browserName
