### ISSUE TITLE
Cannot focus element error

### ISSUE THREAD

**Issue by tnguyen14** [webdriverio/webdriverio#1244]
## The problem

When trying to change the value of an input, I'm getting the `error: cannot focus element` error

## Environment

* WebdriverIO version: ^3.3.0
* Node.js version: 4.x
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio test runner
* if wdio testrunner, running synchronous or asnychronous tests: async
* Additional wdio packages used (if applicable):

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Selenium/WebdriverIO logs

https://gist.github.com/tnguyen14/a21087ffbcecb37c3903164a73710102

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
This is an [issue of chromedriver](https://bugs.chromium.org/p/chromedriver/issues/detail?id=35) and can't be fixed in WebdriverIO. I also don't see a workaround for this issue.
