### ISSUE TITLE
Done callbacks aren't defined in latest WebdriverIO 4.0.5

### ISSUE THREAD

**Issue by pi4r0n** [webdriverio/webdriverio#1245]
## The problem

I have updated my gulp-webdriver npm package to use latest version 2.0.1 which points to latest version of webdiriverio ver 4.0.5. Each time I execute below test with gulp -> wdio -> mocha the test fails with error **TypeError: undefined is not a function**

**IMPORTANT: as soon as i change gulp-webdriver npm package to 1.0.1 it all works fine**

```
1) "before all" hook:
undefined is not a function
running firefox
TypeError: undefined is not a function
    at Context.<anonymous> (/Users/pi4r0n/Documents/Development/testing/tests/mocha_test.js:7:9)
    at /Users/pi4r0n/Documents/Development/testing/node_modules/wdio-mocha-framework/node_modules/wdio-sync/build/index.js:619:36

Error in plugin 'gulp-webdriver'
Message:
    wdio exited with code 1
[11:26:40] Finished 'test:e2e' after 8.44 s
[11:26:40] Starting 'default'...
[11:26:40] Finished 'default' after 31 μs
```

## Link to Selenium/WebdriverIO logs

https://gist.github.com/pi4r0n/f1187f634b4ec952a487c059664f195a

## Code To Reproduce Issue [ Good To Have ]

```javascript
var webdriverio = require('../../webdriverio/webdriverio-LATEST');

describe('DuckDuckGo search', function() {

    before(function(done){
        browser.url('http://www.google.co.uk');
        done();
    });

    it('searches for WebdriverIO', function(done) {
        browser.setValue('#lst-ib', 'test')
            .pause(5000)
            .setValue('#lst-ib', 'arek')
            .pause(5000)
            .end(done);
    });
});
```

**Comment by christian-bromann** [comment]
In `v4.0.5` all commands are running synchronous, why would you need a callback?

**Comment by christian-bromann** [comment]
However if you use 3rd party libraries to do async stuff (e.g. calling a mysql service or whatever) which only works with callbacks you should wrap that methods within promises. Callbacks do a terrible job in providing helpful stacktraces.

**Comment by pi4r0n** [comment]
@christian-bromann Yes I am using async npm package and MongoDB. Will have change my framework a bit ;)

**Comment by christian-bromann** [comment]
I would recommend to make each method you use from the mongo package to a WebdriverIO custom command. With that you can easily make these methods synchronous 😉

**Comment by christian-bromann** [comment]
See http://webdriver.io/guide/usage/customcommands.html

**Comment by JimBarrows** [comment]
This doesn't solve all problems with breaking mocha's done function.  I have a common function written in ES6, that returns a promise.  It works just in every other mocha test as is.  It does not work in webdriverio's mocha implementation because of the broken done function.  The work around the problem does not solve the problem, I just have to find more yaks to shave to get working code to work.

**Comment by marcodejongh** [comment]
@christian-bromann I strongly feel that you should reconsider this design decision. It is not documented well enough and developers should be able to use their current expectations of mocha when using wdio.

**Comment by justinffs** [comment]
Also this requires a significant amount of work to change existing tests that were using 3.X and mocha with a lot of `before(function(done){...})` and `after(function(done){...})`  

Based on the documentation my assumption was that setting `async: false` would allow this to continue to work.

**Comment by BryceEWatson** [comment]
+1 to reconsidering the removal of all callbacks. I ended up here after being confused as to why mocha's before(done) callback no longer works. Are there any examples for using mocha's before & after methods with promises, is it possible?

**Comment by shedali** [comment]
I believe the option is `sync` rather than `async` from the config [example](https://github.com/webdriverio/webdriverio/blob/master/examples/wdio.conf.js#L94)
