### ISSUE TITLE
assert option types in ConfigParser

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#1246]
## The problem

If developer specify options wrong (e.g. `specs` as `string` and not `string[]`) they should be informed about the problem due to an error.

## Details

Found out that if you set `suites` to be an `string` it says:

```
pattern . did not match any file
pattern / did not match any file
pattern t did not match any file
pattern e did not match any file
pattern s did not match any file
pattern t did not match any file
pattern / did not match any file
pattern g did not match any file
pattern a did not match any file
...
```

**Comment by jbhelfrich** [comment]
Actually, it's when I set 'specs' as a string, not suite, that I got that result.
