### ISSUE TITLE
[🐛 Bug]: creating a package from wdio config will result in compilation errors

### ISSUE THREAD

**Issue by HananArgov** [webdriverio/webdriverio#12486]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

18.12.1

### Mode

WDIO Testrunner

### What happened?

in case I want to use base config for different repos, i've created a package of wdio config.
i've tried to use the config, but got an error of:
```
ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///Users/XXXXXXXXXX/Documents/repos/testing/src/wdio.test.conf.ts: Cannot find module '/Users/XXXXXXXXXX/Documents/repos/testing/node_modules/wdio_test/src/wdio.conf' imported from /Users/XXXXXXXXXX/Documents/repos/testing/src/wdio.test.conf.ts
Cannot find module '/Users/XXXXXXXXXX/Documents/repos/testing/node_modules/wdio_test/src/wdio.conf' imported from /Users/XXXXXXXXXX/Documents/repos/testing/src/wdio.test.conf.ts
```

### What is your expected behavior?

I expect to use the package as if i'm using the configuration as a base config, and extend it like I regularly do.

### How to reproduce the bug.

i've created an example repo:
https://github.com/HananArgov/doa_testing
it uses a package i've created with the `wdio init` command
the package is called: `wdio_test`

### Relevant log output

```typescript
only compilation error:

ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///Users/XXXXXXXXXX/Documents/repos/testing/src/wdio.test.conf.ts: Cannot find module '/Users/XXXXXXXXXX/Documents/repos/testing/node_modules/wdio_test/src/wdio.conf' imported from /Users/XXXXXXXXXX/Documents/repos/testing/src/wdio.test.conf.ts
Cannot find module '/Users/XXXXXXXXXX/Documents/repos/testing/node_modules/wdio_test/src/wdio.conf' imported from /Users/XXXXXXXXXX/Documents/repos/testing/src/wdio.test.conf.ts
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Hey @HananArgov ,

your import doesn't have an extension which is important when using ESM:

```patch
- import { config } from "wdio_test/src/wdio.conf";
+ import { config } from "wdio_test/src/wdio.conf.ts";
```

Then I recommend to use proper exports defined in your `package.json` to access the config file.

I will go ahead and close this as it doesn't seem to be a WebdriverIO issue.

**Comment by erwinheitzman** [comment]
@christian-bromann i was thinking the same thing but I could not get it to work myself so I asked them to create an issue for it. To me it looks related to how the config file is loaded and might be missing the TS-node workaround we did for node 18.19 and 20 and higher

**Comment by christian-bromann** [comment]
As I mentioned above, if you like to export a config module from another package, I would recommend to define it as exports in your `package.json`, e.g.:

```json
{
  "name": "my-npm-package",
  "exports": {
    "./config": {
      "import": "./path/to/config.ts"
    }
  }
}
```

I don't see how this is related to `ts-node` at the moment.

**Comment by erwinheitzman** [comment]
Sorry about that Christian, I just did some testing and after setting the package.json type to module, adding the exports and importing it using 'import { sharedConfig } from "my-package/config" it works 👍

**Comment by christian-bromann** [comment]
No worries! Glad it works.
