### ISSUE TITLE
[📖 Docs]: Deprecated Matchers are not marked as deprecated in the Expect documentation page

### ISSUE THREAD

**Issue by cafshari** [webdriverio/webdriverio#12489]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Unclear documentation, Missing documentation

### Description of the improvement / report

In the following production documentation link: https://webdriver.io/docs/api/expect-webdriverio/#tohaveattrcontaining there is mention of a matcher, `toHaveAttrContaining` which is deprecated. Likely there are other matchers on that documentation page that are deprecated. The documentation should be updated to instead list the up-to-date replacements for the deprecated matchers.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Fixed with https://github.com/webdriverio/expect-webdriverio/commit/3fdc1bd941c484c180f0f5e3ad12d1be8fc504c5 .. kicked of the deploy pipeline so change should be out any minute. Let me know if now.
