### ISSUE TITLE
JUnit reporter does not generate steps

### ISSUE THREAD

**Issue by djaromir** [webdriverio/webdriverio#1251]
## The problem

Hi, I would like webdriverio to generate junit xml report. Unfortunately generated file does not contain any actual steps(see bellow). I am able to see my steps in std output correctly, they are just missing in the file. If I just edit wdio.conf.js to use allure instead of junit, files are generated as expected.

```
<testsuites>
  <testsuite name="first_test" timestamp="2016-04-15T16:15:13" time="2.655" tests="1" failures="0" errors="0" skipped="0">
    <properties>
      <property name="specId" value="16398144714645719902ce8e7de2da72"/>
      <property name="suiteName" value="first test"/>
      <property name="capabilities" value="chrome"/>
    </properties>
    <testcase classname="chrome.first test" name="should have the right title" time="2.653"/>
  </testsuite>
</testsuites>
```

## Environment

* WebdriverIO version: 4.0.5
* Node.js version: 5.9.0
* wdio-junit-reporter@0.0.2
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asnychronous tests: synchronous
* Additional wdio packages used (if applicable): junit, allure, jasmine

P.S.
I noticed that the page about junit usage contains dot install command:
http://webdriver.io/guide/reporters/xunit.html

When I click improve this doc I am redirected to file https://github.com/webdriverio/webdriverio/edit/master/docs/guide/reporters/junit.md
which is actualy correct.

**Comment by dcypherthis** [comment]
@djaromir the docs page you are looking at was out of date in regards to the latest version of webdriverIO.  Be sure you set the api version to the latest on the docs website or visit this link:

http://webdriver.io/guide/reporters/junit.html 

That was why you were getting the redirect.

**Comment by christian-bromann** [comment]
I believe this issue is resolved. Feel free to reopen if not.
