### ISSUE TITLE
[🐛 Bug]: element search commands like browser.$ and element.$ have incorrect types

### ISSUE THREAD

**Issue by shadowusr** [webdriverio/webdriverio#12527]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.34.1, 9.0.0-alpha.0

### Node.js Version

18.16.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
any
```

### What happened?

Commands `browser.$` and `element.$` return `ChainablePromiseElement<Element>`, which isn't quite `WebdriverIO.Element`.

```typescript
const element = browser.$("body") satisfies WebdriverIO.Element;
// TS1360: Type ChainablePromiseElement<Element> does not satisfy the expected type Element
//   Type ChainablePromiseElement<Element> is missing the following properties from type Element: #private, _webSocketUrl 
```

And in runtime `this` resolves to `WebdriverIO.Element` (thanks to Proxy, defined [here](https://github.com/webdriverio/webdriverio/blob/51ac8482284ad34dea3cc899872397fb734de617/packages/wdio-utils/src/shim.ts#L224)), inside chained commands.

### What is your expected behavior?

I'd expect consistent types between commands and return type of `$` function. Currently `$` returns that chainable promise element and all commands in webdriverio expect `this` to be `WebdriverIO.Element` or `WebdriverIO.Browser`, see [$ command sources](https://github.com/webdriverio/webdriverio/blob/51ac8482284ad34dea3cc899872397fb734de617/packages/webdriverio/src/commands/browser/%24.ts#L69). It works now, because types for use by end users are generated separately and don't include `this` in command signatures.

I do not have a clean solution here, because obviously proxy returned by `browser.$` isn't exactly `WebdriverIO.Element`. But in the end of the day commands receive actual `WebdriverIO.Element`.

### How to reproduce the bug.

My use-case is implementing custom commands like this:
```typescript
const makeCustomCommand = (session: WebdriverIO.Browser) => async function (this: WebdriverIO.Element) {}

session.addCommand(
    "customCommand",
    makeCustomCommand(session),
    true,
);
```
I then use TypeScript's declaration merging to enrich `WebdriverIO.Browser` with `customCommand` and try to use it like this:
```typescript
session.$("body").customCommand();
```
This will give us aforementioned error, because my command expects Element:
```
Type ChainablePromiseElement<Element> is missing the following properties from type Element: #private, _webSocketUrl 
```

Obviously the workaround is to do the same thing webdriverio does — do not include `this` in public signature. But it's a hack and in the end all commands truly get `WebdriverIO.Element`.

### Relevant log output

```typescript
.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for raising the issue @shadowusr 

It is worth to take a look at this again for v9 as it is quite confusing. The biggest drawback of the `ChainablePromiseElement` is that IDEs autocomplete element chains to things like `await (await $('foo')).click()`. The reason we have this separation is because we implement the ability to just do `await $('foo').$('bar').click()` later on and so properties of `ChainablePromiseElement` are all promises, e.g.

```ts
const elem = await $('foo')
console.log(elem.elementId) // returns a string
// while
const elem = $('foo')
console.log(elem.elementId) // returns a Promise<string>
```

Over time it turned out that it really doesn't matter to have `WebdriverIO.Element` properties resolved when accessing it. Therefor I suggest to make `ChainablePromiseElement` the new `WebdriverIO.Element`.

**Comment by shadowusr** [comment]
> Over time it turned out that it really doesn't matter to have WebdriverIO.Element properties resolved when accessing it.

I didn't get what exactly you mean, sorry. Do you mean that most of the time there's enough data in ChainablePromiseEvent?

I personally think being able to write `$().$().click()` is very convenient and hope this new solution won't lead to getting rid of it. Because that'd require changing a lot of tests code.

If it's possible to replace `WebdriverIO.Element` with `ChainablePromiseElement` while keeping this feature, and use this single type everywhere in commands, that'd be great for sure!

**Comment by christian-bromann** [comment]
> I didn't get what exactly you mean, sorry. Do you mean that most of the time there's enough data in ChainablePromiseEvent?

WebdriverIO is able to resolve the chain of promises, so it only matters that you have 1 `await` at the beginning of the chain like `await $('foo').$('bar').$('loo').click()`. In this case the `bar` element is fetched once the `foo` query is resolved, then the `loo` element is fetched once the `bar` element is resolved and the actual click is done once `loo` is resolved. This has been battle tested and works pretty great even for arrays like `await $('foo').$$('bar')[123].$('loo').click()`.

**Comment by christian-bromann** [comment]
related to #12591

**Comment by christian-bromann** [comment]
Fixed in https://github.com/webdriverio/webdriverio/pull/13051
