### ISSUE TITLE
[💡 Feature]: Compatibility with ESLint flat config and more precise exported types for wdio ESLint driver

### ISSUE THREAD

**Issue by gavvvr** [webdriverio/webdriverio#12547]
### Is your feature request related to a problem?

Hi. Trying to to configure wdio eslint plugin in modern typescript project and using the [new "flat" config system](https://eslint.org/docs/latest/use/configure/configuration-files-new) of ESLint. Here are my observations:
- The wdio ESLint plugin object does not seem to be "plug and play"-ready for new ESLint flat config system
- It's not possible to make TS happy when configuring wdio ESLint plugin in flat ESLint config with types-aware [`tseslint.config(...)`](https://typescript-eslint.io/packages/typescript-eslint#config) function and `@ts-check` enabled for `eslint.config.js`

### Describe the solution you'd like.

Ideally, I would expect wdio ESLint plugin to be pluggable in couple of lines (not sure if it's possible though):

```typescript
import wdioEslint from 'eslint-plugin-wdio'
// ...
export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  ...wdioEslint.configs.recommended // <-- like this
// ...
```

### Describe alternatives you've considered.

While the above does not work, I manually try to apply the plugin piece by piece in `eslint.config.js`:

```javascript
// @ts-check

import eslint from '@eslint/js'
import tseslint from 'typescript-eslint'
import { configs as wdioConfig, rules as wdioRules } from 'eslint-plugin-wdio'

export default tseslint.config(
  eslint.configs.recommended,
  {
  files: ['test/e2e/specs/*.ts'],
  plugins: {
    ['wdio']: { rules: wdioRules }, // <-- adding WDIO plugin rules
  },
  extends: [
    eslint.configs.recommended,
    ...tseslint.configs.recommended,
    {
      languageOptions: {
        parserOptions: {
          project: true,
          tsconfigDirName: import.meta.dirname,
        },
        globals: {
          ...wdioConfig.recommended.globals, // <-- adding WDIO globals
        },
      },
    },
    { rules: wdioConfig.recommended.rules }, // <-- trying to add rules, but @ts-check is not happy that rules is '{ 'wdio/await-expect': string; 'wdio/no-debug': string; 'wdio/no-pause': string; }' instead of being a `Record<string, RuleEntry>` 😓
  ],
}
)
```

![image](https://github.com/webdriverio/webdriverio/assets/1719646/fc2459a7-b7b1-43c3-9b37-b732f71ac21e)

So, I am also struggling to apply the plugin piece by piece, because TS treats values of `configs.recommended.rules` object as strings, while a more narrow types are [expected](https://github.com/typescript-eslint/typescript-eslint/blob/v7.3.1/packages/utils/src/ts-eslint/Config.ts#L11-L16)

### Additional context

- I have a TypeScript codebase, so I'm using the `typescript-esltint` project
- Both `eslint` and `typescript-esltint` now encourage to use the so-called "flat" config
- Usage of `@ts-check` + [`tseslint.config(...)`](https://typescript-eslint.io/packages/typescript-eslint#config) is recommended by `typescript-esltint` in their [Getting Started](https://typescript-eslint.io/getting-started/) guide

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
@gavvvr thanks for raising the issue. We haven't been able to update our [existing plugin](https://github.com/webdriverio/webdriverio/tree/main/packages/eslint-plugin-wdio) to be compatible with the new plugin system of Eslint. Any contributions that would us get there would be very much appreciated.

**Comment by gavvvr** [comment]
Hi @christian-bromann 
Sent a PR to v8 branch with the fix. Waiting for the feedback. If it's fine, I can proceed and create another one for `main`

**Comment by christian-bromann** [comment]
Reviewed the PR and it looks good to me, I want someone else from the team take a look as well. Thanks a lot!

**Comment by christian-bromann** [comment]
Thanks @MadSandwich for working on a fix for this 🙏  closing!

**Comment by krististepanek** [comment]
Is there any documentation on using the flat config?

**Comment by christian-bromann** [comment]
@krististepanek mind raising an issue for this? I don't think we have any documentation for the plugin at all on webdriver.io

**Comment by krististepanek** [comment]
done! https://github.com/webdriverio/webdriverio/issues/13775

**Comment by christian-bromann** [comment]
Thanks!
