### ISSUE TITLE
Add a Key in Configuration File for Custom Use

### ISSUE THREAD

**Issue by ResolverJay** [webdriverio/webdriverio#1255]
This is a feature request.

I'm looking for a way to pass some custom variables from command line. Does WebdriverIO have anything like that?

If not, can we add a key in the config file, so that we can use it for passing custom/environment variables from command line?

Here's an example of the config file.
```
exports.config = {
    host: 'localhost',
    port: 4444,
    // more configurations

    // whichever name makes sense
    environmentVariables: {
        variable1: 'variable1',
        variable2: 2,
        // more variables
    }
};
```

Here's how to pass from the command line.
```
wdio --environmentVariables.variable1 "variable 1" --environmentVariables.variable2 2
```

**Comment by christian-bromann** [comment]
@ResolverJay if you do:
```sh
$ export environmentVariable1="variable 1"
$ export environmentVariable2="variable 2"
$ wdio
```

it should work as well

**Comment by ResolverJay** [comment]
@christian-bromann It doesn't work on Windows. As we develop code on Windows and deploy on Linux, we need a universal way to handle it. (I know we are crazy)

**Comment by christian-bromann** [comment]
@ResolverJay I am not a windows user but I don't think you can set environment variables in Windows like this. There is a different way. But once you set the environment variable you should be able to access it.

**Comment by ResolverJay** [comment]
Sorry for the confusion. I actually meant for custom variables mostly (environment variable is a small part of it). I want it to be able to set up in config file and can be override from command line, which is like "host", "port" and "mochaOpts" in the config file.

I think my original proposal is doable, as WebdriverIO already has it setup for all the existing keys (host, port, mochaOpts...). It is just a matter to add another key in the config file so we can override it from command line.

**Comment by christian-bromann** [comment]
I am not sure if it is a good idea to add `environmentVariables` to the config file. It leads to confusion I think. So if I execute:

```sh
$ SOMEVARIABLE=somevalue wdio wdio.conf.js
```

I can use `somevalue` in my test via

```js
process.env.SOMEVARIABLE
```

Why is that not feasible for you?

**Comment by ResolverJay** [comment]
It's doable, but it isn't any better than what we are doing now.

Let me show you an example. We develop code locally with a different set of baseUrl, username and password than running on the server. And we use the Webstorm to run the tests locally, while we use command line to run the tests on the server. So, it would be convenient to be able to set username and password the same way to set baseUrl.

Currenlty, we have a file to store all these kind of variables. We check in the file for server run, and keep a local copy for the local run. If we could set these variables the same way as baseUrl, then we don't need to keep a local file or set different environment variables.

Anyways, this is not critical, but it's nice to have in my case. And I thought it would be an easy change. Let me know if you would like to do it. Thanks.

**Comment by christian-bromann** [comment]
@ResolverJay the thing about this change is that it adds another property to the config which is already full of different options. Adding another one makes it even more complex and since it is easy achievable in other ways, I really not in favor of implementing it. Sorry.

You could also work with multiple config files, one for each environment. Check out this doc: https://github.com/webdriverio/webdriverio/blob/master/docs/guide/testrunner/organizesuite.md#inherit-from-main-config-file. Just have a wdio conf for local testing and one for integration tests. And have different properties for each one of the environments. You should be able to put any random property in your wdio.conf.js and access it in your test via `browser.option.property`.

**Comment by ResolverJay** [comment]
@christian-bromann that's totally fine. Thanks for your input. The link looks really helpful for me :+1:

**Comment by stuartcrobinson** [comment]
updated link:

http://webdriver.io/v4.9/guide/testrunner/organizesuite.html#Inherit-From-Main-Config-File

**Comment by snetch-gym** [comment]
404^ no such key =(

**Comment by christian-bromann** [comment]
With a little search on the current docs page you find a new link: https://webdriver.io/docs/organizingsuites#inherit-from-main-config-file
