### ISSUE TITLE
[🐛 Bug]: Module '"webdriverio"' has no exported member 'ElementArray'.

### ISSUE THREAD

**Issue by alexDunga3pg** [webdriverio/webdriverio#12586]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.35.1

### Node.js Version

21.7.1

### Mode

Standalone Mode

### What happened?

just running this demo learning project and if I update to the latest packages I get quite a few errors. 
Is the type still available? 
git@github.com:testSadab/WebdriverIOTSFramework.git

### What is your expected behavior?

to have the type ElementArray  

### How to reproduce the bug.

just changed 2 file 
package.json
{
  "name": "webdriveriocucumberts",
  "version": "1.0.0",
  "description": "Learning WebdriverIO framework",
  "main": "index.js",
  "scripts": {
    "test": "npx wdio wdio.conf.ts",
    "smoke": "npx wdio wdio.conf.ts --suite smoke",
    "regression": "npx wdio wdio.conf.ts --suite regression",
    "report": "allure generate allure-results --clean && allure open"
  },
  "keywords": [
    "webdriverio",
    "typescript",
    "cucumber",
    "nodejs"
  ],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@wdio/cli": "^8.35.1"
  },
  "devDependencies": {
    "@types/supertest": "^6.0.2",
    "@wdio/allure-reporter": "^8.34.0",
    "@wdio/cucumber-framework": "^8.35.0",
    "@wdio/types": "^8.32.4",
    "@wdio/local-runner": "^8.35.1",
    "@wdio/spec-reporter": "^8.32.4",
    "allure-commandline": "^2.27.0",
    "chromedriver": "^123.0.0",
    "supertest": "^6.3.4",
    "ts-node": "^10.9.2",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.4.3",
    "wdio-chromedriver-service": "^8.1.1",
    "webdriverio": "^8.35.1"
  }
}

and

tsconfig.json
{
  "compilerOptions": {
    "target": "ES5",
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "baseUrl": ".",
    "types": [
      "node",
      "webdriverio/async",
      "@wdio/globals/types",
      "@wdio/cucumber-framework",
      "@wdio/devtools-service",
      "expect-webdriverio"
    ]
    // Add this line
  }
}

### Relevant log output

```typescript
2024-03-27T12:38:44.838Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///C:/Users/alex.dunga/IdeaProjects/WebdriverIOTSFramework/wdio.conf.ts: ⨯ Unable to compile TypeScript:
src/utils/commands.ts:1:58 - error TS2305: Module '"webdriverio"' has no exported member 'ElementArray'.

1 import { ChainablePromiseArray, ChainablePromiseElement, ElementArray } from "webdriverio";
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by alexDunga3pg** [comment]
please ignore this for now. probably a non issue. will as for support on Discord Server if needed

**Comment by christian-bromann** [comment]
@alexDunga3pg please use the `WebdriverIO` namespace, e.g. `WebdriverIO.ElementArray`
