### ISSUE TITLE
[🐛 Bug]: VSCode adds parentheses around methods during auto-completion

### ISSUE THREAD

**Issue by k03mad** [webdriverio/webdriverio#12591]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.35.0

### Node.js Version

20

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    browserName: 'chrome'
}
```

### What happened?

I have encountered strange behavior with auto-inserting unwanted parentheses around WDIO methods in VSCode.

Perhaps this is due to the way VSCode interprets types and doesn't recognize that this methods can be chained.
Or could it be a bug in the WDIO types?

Maybe someone has encountered such behavior and can give advice or a solution.

### How to reproduce the bug.

Repo to reproduce: https://github.com/k03mad/wdio-reproduce-autocomplete
Created with the default `npm init wdio@latest .`

Reproduced in both GitHub Codespaces and local VSCode installations.
Please refer to the GIF below.

### Relevant log output

File: `wdio-reproduce-autocomplete/test/pageobjects/login.page.js`

![](https://github.com/k03mad/wdio-reproduce-autocomplete/raw/master/autocomplete.gif)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@k03mad thanks for raising the issue. This is a know problem. I had some ideas how we might be able to resolve this for v9.

**Comment by SimonRazor** [comment]
@k03mad if it helps I disabled these settings in VSCode and it's better than having to remove the brackets every time
![image](https://github.com/webdriverio/webdriverio/assets/137889885/28b89f07-f8ca-4144-b7c2-d2b50eb9c775)

**Comment by k03mad** [comment]
> @k03mad if it helps I disabled these settings in VSCode and it's better than having to remove the brackets every time

Wait... But the first option disables the suggestions entirely :)
The second disabled option alone doesn't work to prevent extra parentheses.
