### ISSUE TITLE
Execute command does not work on instruments for iOS by passing a function

### ISSUE THREAD

**Issue by agauthiez** [webdriverio/webdriverio#1259]
## The problem

When calling `driver.execute(function ([args]) { ... }, [args])` during a session on a native iOS app, Appium returns a 500.

## Environment

* WebdriverIO version: *4.0.5*
* Node.js version: *5.7.1*
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): *standalone*

## Details

For some reason, the `execute` command [adds a `return` statement](https://github.com/webdriverio/webdriverio/blob/master/lib/protocol/execute.js#L53) before the function call, which causes the error.

## Link to Appium logs

```
info: --> POST /wd/hub/session/10d7417e-3c3f-421b-b07a-10313dbe051f/execute {"script":"return (function (){}).apply(null, arguments)","args":[1]}

info: [debug] Pushing command to appium work queue: "return (function (){}).apply(null, arguments)"
info: [debug] Sending command to instruments: return (function (){}).apply(null, arguments)

info: [debug] [INST] 2016-04-20 15:17:39 +0000 Debug: responding with:

info: [debug] [INST] 2016-04-20 15:17:39 +0000 Debug: Running system command #5: /usr/local/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":17,"value":"Return statements are only valid inside functions."}...

info: [debug] [INST] 2016-04-20 15:17:51 +0000 Debug: Got new command 5 from instruments: return (function (){}).apply(null, arguments)

info: [debug] [INST] 2016-04-20 15:17:51 +0000 Debug: evaluating return (function (){}).apply(null, arguments)

info: [debug] Socket data received (76 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":17,"value":"Return statements are only valid inside functions."}
info: [debug] Responding to client with error: {"status":17,"value":{"message":"An error occurred while executing user supplied JavaScript.","origValue":"Return statements are only valid inside functions."},"sessionId":"10d7417e-3c3f-421b-b07a-10313dbe051f"}
info: <-- POST /wd/hub/session/10d7417e-3c3f-421b-b07a-10313dbe051f/execute 500 1052.792 ms - 211 
info: [debug] [INST] 2016-04-20 15:17:51 +0000 Error: SyntaxError: Return statements are only valid inside functions.
```

## Code To Reproduce Issue

During a native app on iOS session, simply call `driver.execute(function () {})`.

**Comment by christian-bromann** [comment]
@agauthiez I doubt that it is even possible to call `execute` on a native app, there is no JavaScript runtime behind it.

**Comment by agauthiez** [comment]
It is supported on iOS, thanks to UIAutomation which provides a JavaScript API. I tried by passing a string and it works. For instance `driver.execute('(function (a) { return a + 1; }).apply(null, [1])')` works but `driver.execute(function (a) { return a + 1; }, 1)` does not, because of [this](https://github.com/webdriverio/webdriverio/blob/master/lib/protocol/execute.js#L53). I do not know the behavior on the web, so I do not know if we can find a generic fix so it handles the iOS use case or if we should use a `if (this.isIOS)` trick.

**Comment by sa-spag** [comment]
I faced the problem once again. I am using the aforementioned workaround for now but it is not elegant. Is `if (this.isIOS)` solution worth considering? If yes I will open a pull request.

**Comment by christian-bromann** [comment]
Fixed! Will be released with the next version.
