### ISSUE TITLE
[🐛 Bug]: getLogs('browser') Function Not Working in Multiremote Mode

### ISSUE THREAD

**Issue by benazouaou** [webdriverio/webdriverio#12592]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

^8.4.0

### Node.js Version

v18.16.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
Browser name :  Chrome
Browser version : 123.0.6
Plateforme name : windows 10 pro
```

### What happened?

Issue Description: When attempting to use the getLogs('browser') function in a multiremote setup with WebDriverIO, the function does not return the expected browser logs. This issue occurs despite setting the logging preferences to 'ALL' and adding '--verbose' arguments to the chromeOptions. 

Steps to Reproduce:

- Set up a multiremote configuration with WebDriverIO, specifying multiple Chrome browsers and enabling verbose logging.
- Navigate to a webpage using the multiremote browser instances.
- Attempt to retrieve the browser logs using await remoteBrowsers.getLogs('browser');.
- The following error message is displayed: remoteBrowsers.getLogs is not a function

### What is your expected behavior?

The getLogs('browser') function should return an array of browser logs for each of the instances specified in the multiremote configuration

### How to reproduce the bug.

const { multiremote } = require('webdriverio');
let remoteBrowsers;

describe('Test the getLogs function with multiremote', () => {
    before(async () => {
        remoteBrowsers = await multiremote({
            browser1: { capabilities: { browserName: 'chrome', 'goog:chromeOptions': {args: ['--verbose']}, 'goog:loggingPrefs': { browser: 'ALL' } } },
            browser2: { capabilities: { browserName: 'chrome', 'goog:chromeOptions': {args: ['--verbose']}, 'goog:loggingPrefs': { browser: 'ALL' } } },
            browser3: { capabilities: { browserName: 'chrome', 'goog:chromeOptions': {args: ['--verbose']}, 'goog:loggingPrefs': { browser: 'ALL' } } },
            browser4: { capabilities: { browserName: 'chrome', 'goog:chromeOptions': {args: ['--verbose']}, 'goog:loggingPrefs': { browser: 'ALL' } } },
            browser5: { capabilities: { browserName: 'chrome', 'goog:chromeOptions': {args: ['--verbose']}, 'goog:loggingPrefs': { browser: 'ALL' } } },
        });
     });

    it('Retrieving logs', async () => {
        await remoteBrowsers.url('https://webdriver.io/docs/api/chromium/#getlogs')

        const logs = await remoteBrowsers.getLogs('browser');
        console.log(logs); 

    })
    after(async ()=>{
        await remoteBrowsers.deleteSession()
    })
    

})

### Relevant log output

```typescript
remoteBrowsers.getLogs is not a function
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
`getLogs` is a JSONWireProtocol command which we've deprecated and is probably already not supported anymore in latest browser. To fetch logs from browser I recommend this approach:

```ts
await browser.sessionSubscribe({ events: ['log.entryAdded'] })
browser.on('log.entryAdded', (entry) => {
    console.log(entry)
})
await browser.execute(() => console.log('Hello, World!'))  
```

This also works in multiremote. Note that calling `browser.on` will give you the logs from both browser which makes it hard to differentiate from which browser the log came from. Therefor I recommend if you are interested in the log of a single browser do this:

```ts
await browser.sessionSubscribe({ events: ['log.entryAdded'] })
browser.myChrome.on('log.entryAdded', (entry) => {
    console.log('myChrome log:', entry)
})
browser.myFirefox.on('log.entryAdded', (entry) => {
    console.log('myFirefox log:', entry)
})
await browser.execute(() => console.log('Hello, World!'))
```
