### ISSUE TITLE
Question about drop files to upload_area

### ISSUE THREAD

**Issue by keyclaim** [webdriverio/webdriverio#1261]
Hello!
How can I upload files to area that don't accept chooseFile method?
Like in scenario with drag and drop from another window.
Sorry for my bad english.

**Comment by christian-bromann** [comment]
> Sorry for my bad english.

No worries 😉 

Well I think you just can't. File uploads are not really supported in Selenium. The commands WebdriverIO provides aren't even really documented anywhere. So testing a drag&drop area for file uploads might be not possible. You should try to cover it with unit tests as good as possible.

**Comment by irae** [comment]
Hi, I found a pretty nifty StackExchange answer that simulates the desired behavior. For now I'll just use `choseFile` as I support both in the application, but the following trick seems portable to webdriverio:

https://sqa.stackexchange.com/a/22199/1786

I am not sure it is worth maintaining this logic in the codebase on a high level API, that's for the maintainers to choose, but in case I try to roll it, I'll let you know how it goes.
