### ISSUE TITLE
getCssProperty doesn't preserve character case

### ISSUE THREAD

**Issue by eyalzek** [webdriverio/webdriverio#1262]
I'm using the `getCssProperty` method in order to get a `background-image` css property from an element, that property is a URL. The url I am getting as a result is all lower-case, instead of preserving the original capitalization of letter in the url.
This is a problem in my use case since it produces an invalid url, for example:
Original URL: http://media2.giphy.com/media/W8krmZSDxPIfm/200w.gif
Faulty URL: http://media2.giphy.com/media/w8krmzsdxpifm/200w.gif

* WebdriverIO version: 4.0.5
* Node.js version: 4.4.0
* wdio testrunner
* async
* wdio-mocha-framework

Code example and console output can be found here:
https://gist.github.com/eyalzek/3eaee668a718287ee3c54003c9947442

**Comment by dbhowell** [comment]
This looks like a browser driver issue as opposed to webdriverio. By the time the result gets to webdriverio, it is already lower-cased. 

Also you get the same result (lower-case value via getCssValue(cssStyleProperty)) when using selenium-driver without webdriverio.

I could be wrong though...

**Comment by christian-bromann** [comment]
No, you are absolutely right. I just left it open in case someone comes up with a workaround but I believe this isn't feasible thinking about it again. Closing.
