### ISSUE TITLE
[🐛 Bug]: 404s when downloading Chromedriver for an unsupported version of Electron

### ISSUE THREAD

**Issue by goosewobbler** [webdriverio/webdriverio#12630]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### What happened?

When running WDIO on an Electron project where the version of Electron is > 2 major versions behind the latest, WDIO throws a 404 error when trying to download Chromedriver.

Electron Service issue: https://github.com/webdriverio-community/wdio-electron-service/issues/422

### What is your expected behavior?

WDIO should be able to handle older Electron versions if the relevant Chromedriver version is available.

This URL has downloadable files for Chromedriver v102.0.5005.61, which is used by Electron 19.0.0:
[https://chromedriver.storage.googleapis.com/index.html?path=102.0.5005.61](https://chromedriver.storage.googleapis.com/index.html?path=102.0.5005.61/)

Can WDIO use the scheme `https://chromedriver.storage.googleapis.com/index.html?path=<chromedriver_version>/chromedriver_<arch>.zip` to download Chromedriver, instead of the current URL `https://storage.googleapis.com/chrome-for-testing-public`?

### How to reproduce the bug.

Generated electron project as suggested [here](https://www.electronforge.io/templates/vite-+-typescript) 
```
npm init electron-app@latest my-new-app -- --template=vite-typescript
```

Configured WDIO for Electron as suggested [here](https://webdriver.io/docs/desktop-testing/electron),
```
npm create wdio@latest ./
```

Changed Electron version in package.json to `19.0.0`.  Then build the project and run WDIO:
```
npm run make
npm run wdio
```

### Relevant log output

```typescript
2024-04-06T11:37:51.756Z INFO webdriver: Downloading Chromedriver v102.0.5005.61
2024-04-06T11:37:51.943Z WARN webdriver: Chromedriver v102.0.5005.61 don't exist, trying to find known good version...
2024-04-06T11:37:52.229Z ERROR webdriver: Failed downloading chromedriver v102: Download failed: server returned code 404. URL: https://storage.googleapis.com/chrome-for-testing-public/102/mac-arm64/chromedriver-mac-arm64.zip, retrying ...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by seanpoulter** [comment]
Ah, yea, for ChromeDriver < 115 it'd need to download from the old URL, https://chromedriver.chromium.org/downloads.

**Comment by christian-bromann** [comment]
We have introduced Chrome for Testing to manage Chrome and Chromedriver downloads. Chrome for Testing starts with Chrome 115 and up, therefor it is not possible to use a lower version number, except using the Chromedriver service which you can still do.

Could you give the [`wdio-chromedriver-service`](https://www.npmjs.com/package/wdio-chromedriver-service) a shot and see it manages the driver for you?

**Comment by goosewobbler** [comment]
Apologies, I think I misunderstood something here regarding Chrome for Testing and conflated their CD support level with Electron's rolling support.  So the lowest CD version available on CfT is fixed at 115, which corresponds to Electron 26.  This is less of an issue as before long, most Electron users will be off v25 and lower.  

If with this we are saying that given the pace of Chromedriver / Electron releases, adding a download fallback for Chromedriver < 115 is not worth it, I will simply update the Electron service docs to specify that Electron versions lower than 26 will require manual configuration of Chromedriver.

I'm not sure how using the Chromedriver service helps here?

**Comment by christian-bromann** [comment]
> I'm not sure how using the Chromedriver service helps here?

The Chromedriver service would allow to download a Chromedriver version before v115 of Chrome. You could use it within the `onPrepare` hook to download Chromedriver if the Electron version is v25 or lower.

> I will simply update the Electron service docs to specify that Electron versions lower than 26 will require manual configuration of Chromedriver.

I think this would be the best since there aren't many Electron v25 devs out there anymore.

**Comment by goosewobbler** [comment]
Thanks for the clarification, I'll close this then - Electron service docs update [here](https://github.com/webdriverio-community/wdio-electron-service/pull/511).

**Comment by christian-bromann** [comment]
Thanks @goosewobbler 👍

**Comment by seanpoulter** [comment]
> > I'm not sure how using the Chromedriver service helps here?
> 
> The Chromedriver service would allow to download a Chromedriver version before v115 of Chrome. You could use it within the `onPrepare` hook to download Chromedriver if the Electron version is v25 or lower.

FWIW: Here's an over-complicated example. I set up the `onPrepare` hook to download ChromeDriver for Linux ARM64 from the Electron releases on GitHub instead of from ChromeDriver or Chrome for Testing.

**Comment by goosewobbler** [comment]
Thanks for the example, there was something similar in the Electron service before WDIO started handling CD downloads, we were using `@electron/get` though:  https://github.com/webdriverio-community/wdio-electron-service/blob/4.3.0/src/launcher.ts
