### ISSUE TITLE
[📖 Docs]: } added after method names in INFO panels

### ISSUE THREAD

**Issue by mikesalvia** [webdriverio/webdriverio#12667]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

A typo

### Description of the improvement / report

<img width="1008" alt="Screenshot 2024-04-10 at 12 06 21 PM" src="https://github.com/webdriverio/webdriverio/assets/6209204/f8b02b9b-8bd8-457b-a62e-98a730009a7f">

I know I can edit the documentation but I have no idea where to look for where to make the change.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mikesalvia** [comment]
@christian-bromann If you can point me to the right direction I can submit a PR!

**Comment by erwinheitzman** [comment]
@mikesalvia you can find that here scripts/templates/template.eta

**Comment by christian-bromann** [comment]
@mikesalvia you can find it here: https://github.com/webdriverio/webdriverio/blob/a2f81bb7f5d43d5168b45923dea69389a216ac9d/scripts/templates/template.eta#L24-L30
