### ISSUE TITLE
[💡 Feature]: Find the `wdio.conf.ts` if you call `wdio` without anything else

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#12663]
### Is your feature request related to a problem?

If you currently run `npx wdio` and use TypeScript it will fail, saying it can't find the config file `wdio.conf.js`.

### Describe the solution you'd like.

Make it check for a default TS version of the config file.

### Describe alternatives you've considered.

n/a

### Additional context

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harsha509** [comment]
Fixed by https://github.com/webdriverio/webdriverio/pull/12891
