### ISSUE TITLE
Configure session timeout if no DELETE request was received

### ISSUE THREAD

**Issue by timbru31** [webdriverio/webdriverio#1266]
## The problem

We are using TestingBot to run our tests automated, but from time to time the execution is stuck. The TestingBot log tells me (since it detected that the test failed) that a DELETE request was sent
```
19:24:38.66 forwarder.js:23 info: [DELETE] Forward to 127.0.0.1 : /wd/hub/session/dfaf9d3e-d281-4443-b7c8-51cf4667ec68
19:24:38.74 forwarder.js:44 info: 127.0.0.1:5555 responded: {"state":"success","sessionId":"dfaf9d3e-d281-4443-b7c8-51cf4667ec68","hCode":1179455345,"value":null,"class":"org.openqa.selenium.remote.Response","status":0}
```

However the tunnel never received a DELETE request in it's log and the test continues to run until it's manually aborted.
*Question* Can (and if yes, how), can I configure a timeout to mark the test as failed if no DELETE request was received?

We use Cucumber, but the execution of the step stopped at BeforeScenario, so no step timeout was received.

Hope this is the right place to ask :)
(If more logs are necessary, I'll try to get them)

## Environment

* WebdriverIO version: 3.4.0
* Node.js version: 4.4.3
* using wdio testrunner
* running synchronous or asnychronous tests: sync

**Comment by christian-bromann** [comment]
@timbru31 not sure if I understood the issue correctly but you can use the after hook to mark test as failed. We do the same in the sauce service: https://github.com/webdriverio/wdio-sauce-service/blob/master/lib/sauce-service.js#L47-L69

**Comment by timbru31** [comment]
Well the problem was that we never ran into a timeout - the before scenario hangs and there was no way to be notified of this.
Instead I've made a Promise.race between the real test execution and a setTimeout which killed the process and marking it as failed:

```js
	var proc;
	var integrationTest = new Promise(function(resolve, reject) {
		var cucumberTags = ...

		var args = [
			require.resolve('webdriverio/lib/cli.js'),
			'./wdio.local.conf.js',
		];
		args = Array.prototype.concat.apply([], [args, cucumberTags]);
		var out = [];
		var err = [];
		out.push('Run Cucumber With Args ' + args + '\n');
		proc = childProcess.spawn(nodePath, args);
		proc.stdout.on('data', function(data) {
			out.push(data.toString());
		});
		proc.stderr.on('data', function(data) {
			err.push(data.toString());
		});
		proc.on('close', function(code) {
			console.log(out.join(''));
			console.error(err.join(''));
			resolve(code);
		});
		proc.on('error', function(code) {
			console.log(out.join(''));
			console.error(err.join(''));
			resolve(code);
		});
	});
	var timeout = new Promise(function(resolve, reject){
		setTimeout(function() {
			proc.kill('SIGHUP');
			reject(1);
		}, 1200000); // 20 mins
	});

	return Promise.race([integrationTest, timeout]);
```
