### ISSUE TITLE
[💡 Feature]: Support for Grid Managed Downloads

### ISSUE THREAD

**Issue by isc-aray** [webdriverio/webdriverio#12671]
### Is your feature request related to a problem?

No

### Describe the solution you'd like.

WebdriverIO should support the use of Selenium Grid manged downloads.

### Describe alternatives you've considered.

I'm not aware of any alternatives for fetching files downloaded onto remote workers.

### Additional context

Selenium Grid version 4.8 introduced support for Manged Download, which allows the Grid to pull files from the remote browser worker to the client using a new `downloadFile` operation. The feature is described at [https://www.selenium.dev/documentation/webdriver/drivers/remote_webdriver/#downloads].

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Hey @isc-aray , thanks for raising the issue.

I totally agree with you, I haven't seen this commands yet but they should be added in `packages/wdio-protocols/src/protocols/selenium.ts`. Furthermore we should verify that tests run on the Selenium grid are detected as such and the protocol commands are applied accordingly. Any contribution on this would be appreciated.

**Comment by christian-bromann** [comment]
Thanks @ccharnkij for taking a stab at this, will go ahead and close the issue.
