### ISSUE TITLE
[🐛 Bug]: Is the gitpod environment broken?

### ISSUE THREAD

**Issue by step21** [webdriverio/webdriverio#12707]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

20.11.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
-
```

### What happened?

I clicked on "gitpod" in the README. Gitpod starts, but on startup an error is shown, and f.e. npm/pnpm install also doesn't work. Is there some special setup necessary?

### What is your expected behavior?

I start gitpod. All the packages are installed and no error is shown.

### How to reproduce the bug.

Start gitpod from the README. Select one of the available pod sizes. I tried small and large. I also tried github codespaces, but there it said the free ones are too small? Also kind of suprising.

### Relevant log output

```typescript
gitpod /workspace/webdriverio (main) $  HISTFILE=/workspace/.gitpod/cmd-3 history -r; {
> gp sync-await installation
> } && {
> node .gitpod/welcome.mjs
> }
installation done
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'chalk' imported from /workspace/webdriverio/.gitpod/welcome.mjs
    at new NodeError (node:internal/errors:399:5)
    at packageResolve (node:internal/modules/esm/resolve:794:9)
    at moduleResolve (node:internal/modules/esm/resolve:843:20)
    at defaultResolve (node:internal/modules/esm/resolve:1058:11)
    at nextResolve (node:internal/modules/esm/hooks:654:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:309:30)
    at ESMLoader.resolve (node:internal/modules/esm/loader:312:26)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:172:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

Additionally, the `pnpm` version seems to be too old and I couldn't update it yet:

```
gitpod /workspace/webdriverio/packages/wdio-utils/src/node (main) $ pnpm i pnpm
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

Your pnpm version is incompatible with "/workspace/webdriverio".

Expected version: >=8.15.3
Got: 8.6.7

This is happening because the package's manifest has an engines.pnpm field specified.
To fix this issue, install the required pnpm version globally.

To install the latest version of pnpm, run "pnpm i -g pnpm".
To check your pnpm version, run "pnpm -v".
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Yeah, I haven't tested Gitpod in a while and we migrated from NPM to pnpm which might have caused this. I think it is worth fixing the [`gitpod.yml`](https://github.com/webdriverio/webdriverio/blob/8cb10cdd5258547cf635a1cc2d2feb99e62cca78/.gitpod.yml) and update it to the current local setup.

**Comment by christian-bromann** [comment]
@sangcnguyen thanks for taking a stab at this, will close the issue.
