### ISSUE TITLE
Can I create conditional into events?

### ISSUE THREAD

**Issue by Danjavia** [webdriverio/webdriverio#1270]
browser.getText( '.container-step' ).then( function ( value ) {
        if ( value == 'text' ) { browser.click( 'element' ).then( function(){}) }
        else {  browser.click( 'element' ).then( function (){}) }
    })

Is it Possible?

I try but without success.

Thanks

**Comment by christian-bromann** [comment]
If you don't use wdio that allows you to write synchronous tests you need to make sure to handle promises properly! This one will work:

```js
browser.getText( '.container-step' ).then( function ( value ) {
    if ( value == 'text' ) {
        return browser.click( 'element' );
    }
    return browser.click( 'element' );
})
```

However if you setup wdio and run tests with WebdriverIOs test runner you could do:

```js
if (browser.getText( '.container-step' ) === 'text') {
    browser.click('element');
} else {
    browser.click('element');
}
```

**Comment by Danjavia** [comment]
Run perfectly cool thanks!
