### ISSUE TITLE
Synchronous tests do not wait for completion

### ISSUE THREAD

**Issue by object88** [webdriverio/webdriverio#1271]
## The problem

When running a test, the synchronous tests do not complete.

## Environment

* WebdriverIO version: 4.0.5
* Node.js version: v5.11
* Standalone mode
* Additional wdio packages used (if applicable):

## Details

This test was run with Firefox configured in wdio.conf.js.  I would expect to see, as a part of the test output, the three "TESTING [foo]" messages.  However, this is all of the output:

````
STARTING
STARTED
TESTING...
TESTED
ENDING
ENDED
․
````

Please note that this code comes from the [webdriverio examples](https://github.com/webdriverio/webdriverio/blob/master/examples/standalone/webdriverio.with.jasmine.spec.js). 

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]

````
const webdriverio = require('webdriverio');

describe('my webdriverio tests', function() {

    let client;
    jasmine.DEFAULT_TIMEOUT_INTERVAL = 9999999;

    beforeEach(function() {
      console.log('STARTING');
        client = webdriverio.remote({});
        const result = client.init();
      console.log('STARTED');
        return result;
    });

    it('test it', function() {
      console.log('TESTING...');
        const result = client
            .url('https://github.com/')
            .getElementSize('.header-logo-wordmark').then(function (result) {
              console.log('TESTING WORDMARK');
                expect(result.height).toBe(26);
                expect(result.width).toBe(89);
            })
            .getTitle().then(function (title) {
              console.log('TESTING TITLE');
                expect(title).toBe('GitHub · Where software is built');
            })
            .getCssProperty('a[href="/plans"]', 'color').then(function (color) {
              console.log('TESTING COLOR');
                expect(color).toBe('rgba(64,120,192,1)');
            });
      console.log('TESTED');
      return result;
    });

    afterEach(function(done) {
      console.log('ENDING');
        const result = client.end();
      console.log('ENDED');
      return result;
    });
});

````

**Comment by christian-bromann** [comment]
Your code above is not synchronous. I guess you misunderstand the difference between standalone and testrunner mode, see here http://webdriver.io/guide/getstarted/modes.html

There is also an onboarding how to write real sync tests.

**Comment by object88** [comment]
OK, I backed up a little and created a new project with just webdriverio as a dependency, as described by the [original example instructions](https://github.com/webdriverio/webdriverio/blob/master/examples/standalone/webdriverio.with.jasmine.spec.js).  I initialized jasmine and used the below (very slightly modified) spec where jasmine would find it.  The spec (as included below) is slightly modified from above, but is still almost exactly the same as your example code.  I do not have a wdio.conf.js file, and am starting the test as:

````
jasmine
````

These are the results:
````
STARTING
STARTED
TESTING...
TESTED
ENDING
ENDED
````

As before, I have a standalone Selenium driver (my apologies for not mentioning that above).

I still do not see the messages, which prove that the `expect` assertions are running.  I see this behavior regardless of whether I am using firefox or phantomjs as my browser.  Regardless of whether the test (as implemented) is synchronous or not, shouldn't I see my "TESTING" messages?

Furthermore, these messages appear _before_ the browser even starts.

````
var webdriverio = require('webdriverio');

describe('my webdriverio tests', function() {

    var client;
    jasmine.DEFAULT_TIMEOUT_INTERVAL = 9999999;

    beforeEach(function() {
      console.log('STARTING');
        client = webdriverio.remote({ desiredCapabilities: {browserName: 'firefox'} });
        var result = client.init();
      console.log('STARTED');
        return result;
    });

    it('test it', function() {
      console.log('TESTING...');
        var result = client
            .url('https://github.com/')
            .getElementSize('.header-logo-wordmark').then(function (result) {
              console.log('TESTING WORDMARK');
                expect(result.height).toBe(26);
                expect(result.width).toBe(89);
            })
            .getTitle().then(function (title) {
              console.log('TESTING TITLE');
                expect(title).toBe('GitHub · Where software is built');
            })
            .getCssProperty('a[href="/plans"]', 'color').then(function (color) {
              console.log('TESTING COLOR');
                expect(color).toBe('rgba(64,120,192,1)');
            });
      console.log('TESTED');
      return result;
    });

    afterEach(function(done) {
      console.log('ENDING');
        var result = client.end();
      console.log('ENDED');
      return result;
    });
});
````

**Comment by christian-bromann** [comment]
you still run tests asynchronous since you use promise syntax. Just check out the wdio examples. For Jasmine it is:

the wdio.conf.js: https://github.com/webdriverio/webdriverio/blob/master/examples/wdio/wdio.jasmine.conf.js
a sample spec file:
https://github.com/webdriverio/webdriverio/blob/master/examples/wdio/runner-specs/jasmine.spec.js
