### ISSUE TITLE
[🐛 Bug]: Chrome temporary profile left on disk

### ISSUE THREAD

**Issue by RafalSkorka** [webdriverio/webdriverio#12712]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

18.18

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  browserName: 'chrome'
}
```

### What happened?

Execution of each test suite on Chrome leaves temporary profile folder. I tested on Windows and in `%TEMP%` folder there are folders named `scoped_dir***` (eg. `scoped_dir19696_604435620` or `scoped_dir6004_1963846735`). In MacOS the folders are stored in `$TMPDIR` and named `.org.chromium.Chromium.***` and `.com.google.Chrome.***`.
On Linux these folders are stored in `/tmp` although I was not able to reproduce it on a clean WSL Ubuntu 20.04 LTS. It does happen though on our Jenkins Linux workers.
The problem is these folders are never deleted on Windows unless you run some cleanup utility.
On MacOs and Linux these files are deleted upon system restart, however such machines are never restarted normally.
Each such folder is about 20MB which isn't too much but since we have around 100 tests which are run several times a day, we run out of disk space almost daily. As a workaround the Jenkins job includes cleaning up of these folders but I think Webdriver should clean them itself.

### What is your expected behavior?

No temporary files should be left after running tests.

### How to reproduce the bug.

1. Initialize a new repo with `npm init wdio@latest . -- --yes`
2. Run test with `npm run wdio`
3. Check the temp folder (`%TEMP%` on Windows, `$TMPDIR` on MacOS or `/tmp` in Linux)

### Relevant log output

```typescript
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment]
These are temporary files are should be cleared automatically after rebooting

**Comment by christian-bromann** [comment]
> On MacOs and Linux these files are deleted upon system restart, however such machines are never restarted normally.

On MacOS I've seen these files being removed regularly .. every other day or so.

> Each such folder is about 20MB which isn't too much but since we have around 100 tests which are run several times a day, we run out of disk space almost daily.

WebdriverIO only downloads the driver once and reuses it until a new version is available, e.g. if you set `stable` as `browserVersion`.

> As a workaround the Jenkins job includes cleaning up of these folders but I think Webdriver should clean them itself.

I disagree. The temporary dir is the best and most innocent place to throw these binaries into. If you want to clean them up after every run, you always define a custom directory that is being cleaned up by your pipeline. See more how to define this directory in https://webdriver.io/docs/capabilities#cachedir

I will go ahead and close the issue as I don't see how we can improve WebdriverIOs behavior here. If you have a better suggestion where to put these files, please let us know. I don't want to introduce a new option that would clean these driver binaries up since this is something a user can already do.

Happy to answer further questions.

**Comment by RafalSkorka** [comment]
> WebdriverIO only downloads the driver once and reuses it until a new version is available, e.g. if you set `stable` as `browserVersion`.

The issue is not about the driver binaries, but about the Chrome profile folders.
Like I wrote above, they are never periodically removed in Windows, even after reboot.

**Comment by BorisOsipov** [comment]
@RafalSkorka We are not Chrome browser developers, what do you want from us? It seems this issue should be reported in chromium issue tracker https://issues.chromium.org/issues?q=status:open

**Comment by christian-bromann** [comment]
@RafalSkorka sorry for misunderstanding. I agree with @BorisOsipov that WebdriverIO should not go into the business of managing Chrome profiles, however this is a valid issue that we should look into addressing it. For now I think this can be solved using the `@wdio/shared-store-service`, e.g.:

```ts
// wdio.conf.ts
export const config: WebdriverIO.Config = {
    // ...
    onPrepare: function (config, capabilities) {
        setValue('chromeProfiles', [])
    },
    // ...
    before: async function (capabilities: WebdriverIO.Capabilities, specs, browser) {
        const chromeProfiles = await getValue('chromeProfiles') as string[]
        setValue('chromeProfiles', [...chromeProfiles, browser.capabilities.chrome.userDataDir])
    },
    // ...
    onComplete: async function(exitCode, config, capabilities, results) {
        const profiles = await getValue('chromeProfiles') as string[]
        await Promise.all(profiles.map(async (profile) => fs.rmdir(profile, { recursive: true })))
    },
    // ...
```

Would you be interested contributing this to the docs?
