### ISSUE TITLE
[🐛 Bug]: @wdio/junit-reporter - Both Errors and Failures Incremented for Failed Tests

### ISSUE THREAD

**Issue by ASaiAnudeep** [webdriverio/webdriverio#12710]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.32.4

### Node.js Version

20

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
NA
```

### What happened?

The JUnit report incorrectly increments both the "errors" and "failures" counts when a test case fails. Seems, failures and errors are being treated similarly - [link](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-junit-reporter/README.md#failures-and-errors)

### What is your expected behavior?

Only the "failures" count should increase for failed tests. JUnit reports typically distinguish between errors (unexpected exceptions) and failures (asserted conditions not met).

**JUnit Schema Links**
- https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd
- https://github.com/testmoapp/junitxml

### How to reproduce the bug.

```xml
<testsuite name="As a user I can log into the secure area" timestamp="2023-11-01T21:55:07" time="2.554" tests="3" failures="3" errors="3" skipped="0">
```

[Test Case Expected Output Reference](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-junit-reporter/tests/__snapshots__/reporter.test.ts.snap#L17)

### Relevant log output

```typescript
NA
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> JUnit reports typically distinguish between errors (unexpected exceptions) and failures (asserted conditions not met).

I found the responsible code path here: https://github.com/webdriverio/webdriverio/blob/146668cd7841179e4e0fea70e38d9df328f00379/packages/wdio-junit-reporter/src/index.ts#L195-L213

If we can only report failures, and are able to pass in a failure message, I am happy to accept a pull request with necessary changes.

All contributions are welcome.
