### ISSUE TITLE
[🐛 Bug]: touchAction exec error ( uiautomator2@3.1.0 )

### ISSUE THREAD

**Issue by benson-singapore** [webdriverio/webdriverio#12711]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

^8.36.0

### Node.js Version

v16.15.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
"platformName": "Android",
  "appium:platformVersion": "13",
  "appium:automationName": "UiAutomator2",
}
```

### What happened?

 await driver.touchAction({action: 'tap', x: 458, y: 863}); 
exec error

### What is your expected behavior?

Appium v2.5.2
uiautomator2@3.1.0

### How to reproduce the bug.

```node
 await driver.touchAction({action: 'tap', x: 458, y: 863})
```

### Relevant log output

```typescript
2024-04-17T04:51:43.625Z INFO webdriver: [POST] http://localhost:4723/session/39e5f79f-c87b-4c77-951e-86ea97a3c60c/touch/perform
2024-04-17T04:51:43.625Z INFO webdriver: DATA { actions: [ { action: 'tap', options: [Object] } ] }
2024-04-17T04:51:43.654Z ERROR webdriver: Request failed with status 404 due to unknown command: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource
unknown command: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for raising the issue @benson-singapore 

> ```ts
> request was received using an HTTP method that is not supported by the mapped resource
> ```

As you can see, this command is not supported in Appium any longer and we tried to point this out via the deprecation warning that you see in https://webdriver.io/docs/api/element/touchAction/

**Comment by benson-singapore** [comment]
I can perform click operations in the following way. You can consider optimizing the interface for calling appium for adaptation.

```node
 // 执行点击操作
  await driver.performActions([
      {
          type: 'pointer',
          id: 'mouse',
          parameters: {pointerType: 'mouse'},
          actions: [
              {type: 'pointerMove', duration: 0, x, y},
              {type: 'pointerDown', button: 0},
              {type: 'pointerUp', button: 0}
          ]
      }
  ]);
```

**webdriverio log:**
2024-04-19T09:14:54.239Z INFO webdriver: COMMAND performActions(<object>)
2024-04-19T09:14:54.239Z INFO webdriver: [POST] http://localhost:4723/session/3a7c5314-e880-4329-9950-ba4149a56405/actions
2024-04-19T09:14:54.239Z INFO webdriver: DATA {
  actions: [
    {
      type: 'pointer',
      id: 'mouse',
      parameters: [Object],
      actions: [Array]
    }
  ]
}
