### ISSUE TITLE
wdio - synchronous mode

### ISSUE THREAD

**Issue by origaut** [webdriverio/webdriverio#1272]
Hi,

I re-opened the defect as you didn't give me a chance to answer your comment. I do run the test using wdio. wdio wdio.conf.js and wdio.conf.js is at the end of this email.

Our test specs use libraries to execute RPC calls. The functions in these libraries are asynchronous and return promises. We use wdio as a test runner. The tests run fine in asynchronous mode (sync=false). We would like to start using synchronous mode. How does wdio handle these asynchronous libraries (returning promises - these libraries do rpc calls - they don't do any browser related actions)?

I did some tests with a simple application automating a web application computing the parking cost. With the sync flag set to true, I indeed see that the webdriverio object calls (browser) are executed synchronously (which is great) but the wdio runner doesn't wait for the completion of other asynchronous methods.

Environment

WebdriverIO version: 4.0.5
Node.js version: 4.2.6
wdio testrunner
wdio testrunner, running synchronous
Additional wdio packages used (if applicable):
Code To Reproduce Issue [ Good To Have ] -

The parking library implements an asynchronous call:

parking.prototype.waitForTimeout = function(ms) {
    var deferred = Q.defer();
    setTimeout(deferred.resolve, ms);
    return deferred.promise;
}
parking.prototype.asynccall = function(ms) {
    return this.waitForTimeout(ms)
        .then(function() {
            return "Done waiting";
        });
}
The test case calls the asyncall method.

   it("Should navigate to the expected page", function() {
        ....
        var s = park.asynccall(10000);
        console.log(s)
        ...
    });
But wdio doesn't wait for the completion of this asyncall.

~/WebStormProjects/Parking/webdrvio >wdio wdio.conf.js 
{ state: 'pending' }
//----------------------------------------COMPLETE CODE --------------------------------------------------------

//***************************************************************
// test_parking_io.js
//***************************************************************

"use strict";

var should = require('chai').should();
var chai = require("chai");
var chaiAsPromised = require("chai-as-promised");
var ParkingApp = require('./parkinglib');

describe("Parking webapp", function() {
    this.timeout(40000);
    var driver = {};
    var park;
    chai.use(chaiAsPromised);

    before(function() {
        if(typeof browser === "undefined") {
            driver = webdriverio.remote({desiredCapabilities: {browserName: 'firefox', platform: 'ANY'}});
            chaiAsPromised.transferPromiseness = driver.transferPromiseness;
            driver.init();
        } else {
            driver = browser;
            chaiAsPromised.transferPromiseness = driver.transferPromiseness;
            park = new ParkingApp(driver);
        }
    });

    it("Should navigate to the expected page", function() {
        park.visit();

        var page_title = park.getTitle();
        (page_title).should.equal("Parking Calculator");

        var lot = park.getLotValue("#Lot");
        (lot).should.equal("STP");

        park.selectByValue("#Lot", "VP");
        park.setEntryTime("8:00");
        var entry_time = park.getEntryTime("#EntryTime");
        (entry_time).should.equal("8:00");

        park.setExitTime("11:00");
        var exit_time = park.getExitTime("#ExitTime");
        (exit_time).should.equal("11:00");

        var o = park.synccall();
        console.log(o);

        var s = park.asynccall(10000);
        console.log(s);

        park.submit();
        var cost = park.getCost();
        (cost).should.equal("$ 432.00");
    });
});

//**********************************************************
// parkinglib.js
//**********************************************************
Q = require('q');

var parking = function(browser) {
    this.browser = browser;
};

parking.prototype.visit = function() {
    return this.browser.url("http://adam.goucher.ca/parkcalc/index.php?Lot=STP&EntryTime=12%3A00&EntryTimeAMPM=AM&EntryDate=3%2F17%2F2016&ExitTime=12%3A00&ExitTimeAMPM=AM&ExitDate=3%2F31%2F2016&action=calculate&Submit=Calculate");
}

parking.prototype.getTitle = function() {
    return this.browser.getTitle();
}

parking.prototype.getLotValue = function() {
    return this.browser.getValue("#Lot");
}

parking.prototype.selectByValue = function() {
    return this.browser.selectByValue("#Lot", "VP");
}

parking.prototype.setEntryTime = function(t) {
    return this.browser.setValue("#EntryTime", t);
}

parking.prototype.getEntryTime = function() {
    return this.browser.getValue("#EntryTime");
}

parking.prototype.setExitTime = function(t) {
    return this.browser.setValue("#ExitTime", t);
}

parking.prototype.getExitTime = function() {
    return this.browser.getValue("#ExitTime");
}

parking.prototype.submit = function() {
    return this.browser.submitForm('//form[@name="Calculator"]');
}

parking.prototype.getCost = function() {
    return this.browser.getText('.SubHead*=$');
}

parking.prototype.wait = function(d) {
    return this.browser.pause(d);
}

parking.prototype.synccall = function() {
    var title =  this.browser.getTitle();
    var lot = this.browser.getValue("#Lot");
    var ent = this.browser.getValue("#EntryTime");
    var ext = this.browser.getValue("#ExitTime");
    return {title: title, lot:lot, entry_time:ent, exit_time:ext};
}

parking.prototype.waitForTimeout = function(ms) {
    var deferred = Q.defer();
    setTimeout(deferred.resolve, ms);
    return deferred.promise;
}

parking.prototype.asynccall = function(ms) {
    return this.waitForTimeout(ms)
        .then(function() {
            return "Done waiting";
        });
}

module.exports = parking;

here is the wdio.conf.js

var webdriverio = require("webdriverio");

exports.config = {
    
    //
    // ==================
    // Specify Test Files
    // ==================
    // Define which test specs should run. The pattern is relative to the directory
    // from which `wdio` was called. Notice that, if you are calling `wdio` from an
    // NPM script (see https://docs.npmjs.com/cli/run-script) then the current working
    // directory is where your package.json resides, so `wdio` will be called from there.
    //
    specs: [
        'test_parking_io_6.js'
    ],
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    //
    // ============
    // Capabilities
    // ============
    // Define your capabilities here. WebdriverIO can run multiple capabilities at the same
    // time. Depending on the number of capabilities, WebdriverIO launches several test
    // sessions. Within your capabilities you can overwrite the spec and exclude options in
    // order to group specific specs to a specific capability.
    //
    // First, you can define how many instances should be started at the same time. Let's
    // say you have 3 different capabilities (Chrome, Firefox, and Safari) and you have
    // set maxInstances to 1; wdio will spawn 3 processes. Therefore, if you have 10 spec
    // files and you set maxInstances to 10, all spec files will get tested at the same time
    // and 30 processes will get spawned. The property handles how many capabilities
    // from the same test should run tests.
    //
    capabilities: [{
        browserName: 'firefox'
    }],
    //
    // ===================
    // Test Configurations
    // ===================
    // Define all options that are relevant for the WebdriverIO instance here
    //
    // By default WebdriverIO commands are executed in a synchronous way using
    // the wdio-sync package. If you still want to run your tests in an async way
    // e.g. using promises you can set the sync option to false.
    sync: true,
    //
    // Level of logging verbosity: silent | verbose | command | data | result | error
    logLevel: 'silent',
    //
    // Enables colors for log output.
    coloredLogs: true,
    //
    // Saves a screenshot to a given path if a command fails.
    screenshotPath: './errorShots/',
    //
    // Set a base URL in order to shorten url command calls. If your url parameter starts
    // with "/", then the base url gets prepended.
    baseUrl: 'http://localhost',
    //
    // Default timeout for all waitFor* commands.
    waitforTimeout: 10000,
    //
    // Default timeout in milliseconds for request
    // if Selenium Grid doesn't send response
    connectionRetryTimeout: 90000,
    //
    // Default request retries count
    connectionRetryCount: 3,
    //
    // Initialize the browser instance with a WebdriverIO plugin. The object should have the
    // plugin name as key and the desired plugin options as properties. Make sure you have
    // the plugin installed before running any tests. The following plugins are currently
    // available:
    // WebdriverCSS: https://github.com/webdriverio/webdrivercss
    // WebdriverRTC: https://github.com/webdriverio/webdriverrtc
    // Browserevent: https://github.com/webdriverio/browserevent
    // plugins: {
    //     webdrivercss: {
    //         screenshotRoot: 'my-shots',
    //         failedComparisonsRoot: 'diffs',
    //         misMatchTolerance: 0.05,
    //         screenWidth: [320,480,640,1024]
    //     },
    //     webdriverrtc: {},
    //     browserevent: {}
    // },
    //
    // Test runner services
    // Services take over a specific job you don't want to take care of. They enhance
    // your test setup with almost no effort. Unlike plugins, they don't add new
    // commands. Instead, they hook themselves up into the test process.
    // services: [],//
    // Framework you want to run your specs with.
    // The following are supported: Mocha, Jasmine, and Cucumber
    // see also: http://webdriver.io/guide/testrunner/frameworks.html
    //
    // Make sure you have the wdio adapter package for the specific framework installed
    // before running any tests.
    framework: 'mocha',
    //
    // Test reporter for stdout.
    // The following are supported: dot (default), spec, and xunit
    // see also: http://webdriver.io/guide/testrunner/reporters.html
    // reporters: ['dot'],
    //
    // Options to be passed to Mocha.
    // See the full list at http://mochajs.org/
    mochaOpts: {
        ui: 'bdd'
    },
    //
    // =====
    // Hooks
    // =====
    // WedriverIO provides several hooks you can use to interfere with the test process in order to enhance
    // it and to build services around it. You can either apply a single function or an array of
    // methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
    // resolved to continue.
    //
    // Gets executed once before all workers get launched.
    // onPrepare: function (config, capabilities) {
    //     browser = webdriverio.remote({desiredCapabilities: {browserName: 'firefox', platform: 'ANY'}});
    //     return browser.init();
    // },
    //
    // Gets executed before test execution begins. At this point you can access all global
    // variables, such as `browser`. It is the perfect place to define custom commands.
    // before: function (capabilities, specs) {
    // },
    //
    // Hook that gets executed before the suite starts
    // beforeSuite: function (suite) {
    // },
    //
    // Hook that gets executed _before_ a hook within the suite starts (e.g. runs before calling
    // beforeEach in Mocha)
    // beforeHook: function () {
    // },
    //
    // Hook that gets executed _after_ a hook within the suite starts (e.g. runs after calling
    // afterEach in Mocha)
    // afterHook: function () {
    // },
    //
    // Function to be executed before a test (in Mocha/Jasmine) or a step (in Cucumber) starts.
    // beforeTest: function (test) {
    // },
    //
    // Runs before a WebdriverIO command gets executed.
    // beforeCommand: function (commandName, args) {
    // },
    //
    // Runs after a WebdriverIO command gets executed
    // afterCommand: function (commandName, args, result, error) {
    // },
    //
    // Function to be executed after a test (in Mocha/Jasmine) or a step (in Cucumber) starts.
    // afterTest: function (test) {
    // },
    //
    // Hook that gets executed after the suite has ended
    // afterSuite: function (suite) {
    // },
    //
    // Gets executed after all tests are done. You still have access to all global variables from
    // the test.
    // after: function (capabilities, specs) {
    // },
    //
    // Gets executed after all workers got shut down and the process is about to exit. It is not
    // possible to defer the end of the process using a promise.
    // onComplete: function(exitCode) {
    // }
}

**Comment by christian-bromann** [comment]
Please read the docs first: http://webdriver.io/guide/getstarted/modes.html! Also you can always comment even if the issue is closed. Don't just recreate the issue.

**Comment by Gennadiii** [comment]
@christian-bromann The docs say I can't use 3-rd party promises in wdio runner. It's possible only for standalone version where I have to integrate it with test runner myself. Is that right?
