### ISSUE TITLE
Handling ajax calls

### ISSUE THREAD

**Issue by kgish** [webdriverio/webdriverio#1274]
I'm trying to make a remote ajax call using the mailtrap api to access an email notification verifying that the reset password link is correct.

```javascript
var request = require('request');
browser.addCommand('getMailtrapMessages', function async (){
    return new Promise(function(resolve, reject) {
        var url = 'http://mailtrap.io/api/v1/inboxes/xxxxxx/messages?api_token=xxxx';
        request(url, function (error, response, data) {
            if (!error && response.statusCode === 200) {
                resolve(data);
            } else {
                reject(error);
            }
        });
    });
});
```

```javascript
describe('Acceptance | Mailtrap | Inbox ', function() {
    it('should find mailtrap inbox', function () {
        console.log('mailtrap-inbox');
        browser.getMailtrapMessages().then(
            function(data) {
                console.log(data);
        })
        .catch(
            function(reason) {
                console.log('Handle rejected promise ('+reason+') here.');
        });
    });
});
```
When I run the test, the `resolve(data)` returns fine with the correct data, but then I get the following error:
```
1) should find mailtrap inbox:
undefined is not a function
running chrome
TypeError: undefined is not a function
    at Context.<anonymous> (/home/kiffin/projects/tagpoint/test/test/specs/mailtrap/mailtrap-inbox.js:5:39)
    at /home/kiffin/projects/tagpoint/test/node_modules/wdio-mocha-framework/node_modules/wdio-sync/build/index.js:579:24
```
I studied the documentation and tried all kinds of stuff, but must admit that the instructions are not very clear.

I must be doing something wrong and would appreciate it if someone could help me out, thanks alot in advance.

**Comment by christian-bromann** [comment]
Are you running wdio? And if so are your tests synchronous? It helps a lot to provide additional context information (especially if there is a issue template 😉 )

**Comment by kgish** [comment]
Sorry I didn't use the issue template, but I thought that that was only relevant for bugs and not general questions. Please allow me to restate my questions:

## The problem

See above.

## Environment

* WebdriverIO version: v4.0.5
* Node.js version: v0.12.7
* WDIO testrunner
* sync: true (should this be false?)
* Additional wdio packages used (if applicable):
```
 "dependencies": {
    "chai": "^3.5.0",
    "wdio-mocha-framework": "^0.2.12",
    "webdriverio": "^4.0.5"
  },
...
  "devDependencies": {
    "faker": "^3.1.0",
    "phantomjs": "^2.1.7",
    "selenium-standalone": "^5.1.0"
  }
```

## Details

See above.

## Link to Selenium/WebdriverIO logs

N/A

## Code To Reproduce Issue [ Good To Have ]

N/A

**Comment by christian-bromann** [comment]
@kgish please see http://webdriver.io/guide/usage/customcommands.html

Even though you define an async command you still execute it synchronously. So instead of your example above do:
```js
describe('Acceptance | Mailtrap | Inbox ', function() {
    it('should find mailtrap inbox', function () {
        console.log('mailtrap-inbox');
        try {
            console.log(browser.getMailtrapMessages());
        } catch (e) {
            console.log(e);
        }
    });
});
```
