### ISSUE TITLE
[🐛 Bug]: "goog:chromeOptions" args and prefs are being ignored?

### ISSUE THREAD

**Issue by TheMasquerader** [webdriverio/webdriverio#12755]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.35.1

### Node.js Version

18

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    maxInstances: 5,
    browserName: 'chrome',
    "goog:chromeOptions": {
      args: [
        '--accept-lang=en-US',
        '--accept-language=en-US',
        '--lang=en-US',
        '--no-sandbox',
        '--headless=new',
      ],
      prefs: {
        'intl.accept_languages': 'en-US,en_US,en-us',
        'intl.selected_languages': 'en-US,en_US,en-us',
      },
    },
}
```

### What happened?

We've upgraded from WDIO 7 to WDIO 8 and now the tests no longer have an `Accept-Language` header, which causes failures due to how our app is configured. This happens when deploying the tests to be run on Fargate in AWS.

I have now tried various combinations of capabilities, but nothing works. It looks like `"goog:chromeOptions"` get ignored, maybe.

### What is your expected behavior?

I expect the requests made by the tests to have the `Accept-Language` header appended.

### How to reproduce the bug.

Add the `capabilities` to a WDIO project:
```
{
    browserName: 'chrome',
    "goog:chromeOptions": {
      args: [
        '--accept-lang=en-US',
        '--accept-language=en-US',
        '--lang=en-US',
        '--no-sandbox',
        '--headless=new',
      ],
      prefs: {
        'intl.accept_languages': 'en-US,en_US,en-us',
        'intl.selected_languages': 'en-US,en_US,en-us',
      },
    },
}
```

Run the tests, observe `Accept-language` header value.

Change the language in the `capabilities` to `fr-FR`.

Run the tests, observe `Accept-language` header value hasn't changed.

### Relevant log output

```typescript
Session info: headless chrome=111.0.5563.146

`onPrepare` lists the `capabilities` and I can see my changes there.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@TheMasquerader thanks for raising the issue.

Unfortunately there is nothing WebdriverIO can do about this. It only passes along the capabilities and has no control what happened to it in Chrome. Feel free to investigate and if it turns out that this is and issue with WebdriverIO I am happy to re-open. At this point though I don't see anything actionable we can change in the project.

Let me know if you have any further questions.

**Comment by TheMasquerader** [comment]
Thank you very much for your response, @christian-bromann. Would you be able to point me to where the capabilities (args & prefs) are being passed to Chrome?

I've looked at `packages/wdio-utils/src/node/startWebDriver.ts` and `packages/wdio-utils/src/node/utils.ts` and couldn't find where these capabilities are actually passed along.

**Comment by christian-bromann** [comment]
@TheMasquerader sure, the request to initiate the session with your capabilities is done here: https://github.com/webdriverio/webdriverio/blob/b14befdda780837824f8f98fcbf684d21b8c225e/packages/webdriver/src/utils.ts#L88
