### ISSUE TITLE
[💡 Feature]: Support configuring NODE_OPTIONS for ChromeDriver separately from NODE_OPTIONS for WDIO itself

### ISSUE THREAD

**Issue by tanin47** [webdriverio/webdriverio#12753]
### Is your feature request related to a problem?

Here's the background: https://github.com/webdriverio-community/wdio-electron-service/issues/331

tldr: we were stuck in getting Electron (dev mode, not prod) to start within WDIO. We've figured that the root cause is because NODE_OPTIONS was set on ChromeDriver. The NODE_OPTIONS (intended for WDIO) happens to cause issue in Electron.

Specifically, WDIO sets `NODE_OPTIONS=' --loader ts-node/esm/transpile-only --no-warnings'` ([ref](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-local-runner/src/worker.ts#L129)), which is carried over to ChromeDriver and, thus, Electron.

To verify the impact of this env, we can run: `NODE_OPTIONS=' --loader ts-node/esm/transpile-only --no-warnings' ./node_modules/.bin/electron` in Terminal, and Electron will crash.

### Describe the solution you'd like.

We want to be able to to configure NODE_OPTIONS for ChromeDriver separately from the NODE_OPTIONS for WDIO.

Today NODE_OPTIONS for WDIO is carried over to ChromeDriver; in turn, it is carried over to Electron (dev mode), and Electron crashes because of it.

Here's the line that we want to inject NODE_OPTIONS only for ChromeDriver: https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-utils/src/node/startWebDriver.ts#L86

We want to change it to something like:

```
driverProcess = cp.spawn(chromedriverExcecuteablePath, driverParams, { env: {...process.env, NODE_OPTIONS: configured_node_options } })
```

I would also consider adding `shell: true`, so it closely resembles when the Electron is started directly from command line.

### Describe alternatives you've considered.

We could just filter out NODE_OPTIONS altogether as well like:

```
driverProcess = cp.spawn(chromedriverExcecuteablePath, driverParams, { env: { ...process.env, NODE_OPTIONS: null } })
```

This also might be preferable because it's more minimal, and we currently don't have a reason to set NODE_OPTIONS for ChromeDriver/Electron.

### Additional context

We are trying to get wdio-electron-service to support testing against Electron (dev mode), not just prod mode.

Electron (prod mode) doesn't have the same problem because the prod mode forbids NODE_OPTIONS ([ref](https://github.com/electron/electron/blob/0346e0a8bff7b712f86f51075b3effcc1d8358f1/docs/api/environment-variables.md)).

cc @goosewobbler  @christian-bromann 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
> Today NODE_OPTIONS for WDIO is carried over to ChromeDriver; in turn, it is carried over to Electron (dev mode), and Electron crashes because of it.

Can you be more specific on this section? I don't quite get why certain environment variables available when starting Chromedriver cause Electron to crash.

> I would also consider adding `shell: true`, so it closely resembles when the Electron is started directly from command line.

How is starting Electron related to starting Chromedriver?

**Comment by tanin47** [comment]
Thank you.

> How is starting Electron related to starting Chromedriver?

ChromeDriver starts Electron, and I think the shell env is likely carried over to Electron when ChromeDriver starts Electron, but I don't have a way to confirm this.

I also added in the below to the post:

> Specifically, WDIO sets NODE_OPTIONS=' --loader ts-node/esm/transpile-only --no-warnings' ([ref](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-local-runner/src/worker.ts#L129)), which is carried over to ChromeDriver and, thus, Electron.
> 
> If we run: NODE_OPTIONS=' --loader ts-node/esm/transpile-only --no-warnings' ./node_modules/.bin/electron manually in Terminal, Electron crashes.

**Comment by christian-bromann** [comment]
Thanks for clarifying! I think the best solution would be to just filter out `NODE_OPTIONS` as you mentioned in your alternative approach. Until we don't really have a reason why someone would need to control extra env vars for Chrome/Electron we shouldn't add any complexity.

Any contributions would be appreciated.

**Comment by tanin47** [comment]
Sounds good. I'm happy to make the change!
