### ISSUE TITLE
[🐛 Bug]:  I should be able to chain element using both xpath and css

### ISSUE THREAD

**Issue by noobzillla** [webdriverio/webdriverio#12754]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

20

### Mode

Standalone Mode

### What happened?

Tried to add chain element like below

```
const parentElement = $("//some-xpath");
await parentElement.$("div[@id='some-id']/span").click(); // this is also xpath

```

While executing the script below error is shown

```
javascript error: javascript error: {"status":32,"value":"An invalid or illegal selector was specified"}
  (Session info: chrome=124.0.6367.78)

```

My observation:
after debugging I found that for any locator that does not start with "//", wdio thinks css selector is being used. Due to this above error was thrown.

### How to reproduce the bug.

```
const parentElement = $("//some-xpath");
await parentElement.$("div[@id='some-id']/span").click(); // this is also xpath
```

### Relevant log output

```typescript
javascript error: javascript error: {"status":32,"value":"An invalid or illegal selector was specified"}
  (Session info: chrome=124.0.6367.78)
```

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@noobzillla thanks for raising the issue.

I don't think `div[@id='some-id']/span` is a valid xpath in this context. Please try

```ts
const parentElement = $("//some-xpath");
await parentElement.$("./div[@id='some-id']/span").click(); // this is also xpath
```

Let me know if this works. Happy to re-open the issue if it turns out an issue in WebdriverIO.

**Comment by noobzillla** [comment]
> @noobzillla thanks for raising the issue.
> 
> I don't think `div[@id='some-id']/span` is a valid xpath in this context. Please try
> 
> ```ts
> const parentElement = $("//some-xpath");
> await parentElement.$("./div[@id='some-id']/span").click(); // this is also xpath
> ```
> 
> Let me know if this works. Happy to re-open the issue if it turns out an issue in WebdriverIO.

thanks it worked
