### ISSUE TITLE
Jasmine focus not working as expected

### ISSUE THREAD

**Issue by pivotal-studionow** [webdriverio/webdriverio#1276]
Similar to issue #1163, I'm not seeing `fit` and `fdescribe` work for jasmine specs. When running jasmine unit specs, using a `fit` or `fdescribe` restricts the test run to just the scoped block and does not run any other files unless they are also using `fit` or `fdescribe`.

My best guess is that there's one file per process, so the `fit` and `fdescribe` are not being taken into account and thus they aren't filtering out other files. Is there a way to check for focus before the files are divided up amongst threads?

**Comment by christian-bromann** [comment]
@pivotal-studionow this doesn't quite work. WDIO runs your tests concurrently in separate processes. If you want to run single spec files use the suite option (see https://github.com/webdriverio/webdriverio/blob/master/docs/guide/testrunner/organizesuite.md#group-test-specs) or overwrite the specs property.

**Comment by spleshakov-univision** [comment]
the article moved https://github.com/webdriverio/webdriverio/blob/main/website/blog/2021-03-23-grouping-specs.md
