### ISSUE TITLE
[📖 Docs]: v8.36.0 tag and GitHub release points to wrong commit, v8.36.1 release notes are wrong

### ISSUE THREAD

**Issue by Mr0grog** [webdriverio/webdriverio#12776]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Other

### Description of the improvement / report

I tried to update from v8.35.1 today and noticed some weirdness in the release notes, which uncovered an underlying issue with the tags in Git:

1. The tag and the GitHub release for v8.36.0 are pointing to the wrong commit (the version of the commit that landed on `main` instead of the `v8` branch). The tag and release reference fa5f02f24b64372d2791814bde1306788319e30e (wrong) instead of 01d39abdf72195b8f9f140d488c40454c021090d (right). You can also see this in the GitHub releases UI: https://github.com/webdriverio/webdriverio/releases/tag/v8.36.0

    I found the correct commit via NPM provenance: https://www.npmjs.com/package/@wdio/cli/v/8.36.0 (Yay for the provenance feature! At first I was worried the published version of 8.36.0 had been built from the `main` branch and included v9 code, but it looks like that’s not the case, and what got published was the correct build. 😅)

2. The release notes for v8.36.1 contain a bunch of duplicates from v8.36.0, which you can see both on [GitHub releases](https://github.com/webdriverio/webdriverio/releases/tag/v8.36.1) and in [`CHANGELOG.md`](https://github.com/webdriverio/webdriverio/blob/v8/CHANGELOG.md#v8361-2024-04-20). I think this is probably because of the incorrect tag above, so when the changelog was built, it grabbed the wrong commits (or rather, extra commits) when looking for everything between v8.36.0 and the commit v8.36.1 was built from.

    As far as I can tell, the changelog for v8.36.1 should just be:

    ```markdown
    ## v8.36.1 (2024-04-20)

    #### :bug: Bug Fix
    * `wdio-cli`, `wdio-runner`, `wdio-utils`, `webdriverio`
      * [#12703](https://github.com/webdriverio/webdriverio/pull/12703) [webdriverio-v8] Fix issue wdio log is missing in standalone mode ([@nguyencuongabcxyz](https://github.com/nguyencuongabcxyz))
    * `wdio-browserstack-service`
      * [#12665](https://github.com/webdriverio/webdriverio/pull/12665) Fix error messages ([@07souravkunda](https://github.com/07souravkunda))

    #### :nail_care: Polish
    * `wdio-browserstack-service`
      * [#12675](https://github.com/webdriverio/webdriverio/pull/12675) Fix skip test filename ([@07souravkunda](https://github.com/07souravkunda))

    #### Committers: 3
    - Sourav Kunda ([@07souravkunda](https://github.com/07souravkunda))
    - Sriteja Sugoor ([@sriteja777](https://github.com/sriteja777))
    - [@nguyencuongabcxyz](https://github.com/nguyencuongabcxyz)
    ```

Normally I’d just file a PR for the above, but changing the tags and releases obviously requires someone with control over this repository to do the work.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Thanks for noticing this 👏  I really don't know how this could have happened. I will make sure to double check with the next release.
