### ISSUE TITLE
Bail option

### ISSUE THREAD

**Issue by oyvindeh** [webdriverio/webdriverio#1277]
A bail option, to make the test runner stop after the first failing test, could be useful.

Two use cases:
* To save time if a test fails during deployment.
* Allow the developer to identify what has failed without having to wait for all tests to finish.

**Comment by christian-bromann** [comment]
@oyvindeh you can already use that, e.g. with Mocha:

```js
// wdio.conf.js
export.config = {
    // ...
    mochaOpts: {
        timeout: 10000,
        bail: true
    },
    // ...
});
```

**Comment by oyvindeh** [comment]
Yes, it somewhat works, but it still seems to run quite a lot of tests before it bails in many cases. For example, in one run the 11th test failed, and it still ran 56 of the 57 total tests (with maxInstances set to 10). Perhaps it bails in only one of the processes?

**Comment by christian-bromann** [comment]
oh, right, each test runs in a separate process. Alright this needs to get implemented internally.

**Comment by oyvindeh** [comment]
Should the issue be reopened, or do you have it under control? :)

**Comment by diachedelic** [comment]
Looks like the testrunner [already has](http://webdriver.io/guide/testrunner/configurationfile.html) it's own `bail` option, which I hadn't noticed.  By default it is set to `0`, meaning never bail, but you can set it to the number of tests which need to fail before bailing.

**Comment by rohityadavrv** [comment]
@oyvindeh : are you able to run bail option now?

**Comment by oyvindeh** [comment]
@rohityadavrv I am currently not working on any projects that use WebdriverIO, so I don't know.

**Comment by christian-bromann** [comment]
@robhowell @oyvindeh the wdio testrunner has a bail option that should be used instead of the mocha one http://beta.webdriver.io/docs/options.html#bail
