### ISSUE TITLE
ERROR @wdio/runner: Error: Cannot find typescript module imported from spec.ts

### ISSUE THREAD

**Issue by Jp-Aubry** [webdriverio/webdriverio#12775]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.36.0

### Node.js Version

21

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [{
        browserName: 'chrome'
    }],
```

### What happened?

Hi I am new on wdio. I use wdio with Angular 17. I am trying to launch a test with npm run wdio. i get this error:
ERROR @wdio/runner: Error: Cannot find module '/home/francois/Documents/dev/new-moulinet/moulinet/test/pageobjects/app.po' imported from /home/francois/Documents/dev/new-moulinet/moulinet/test/specs/app.e2e-spec.ts.Discussed in https://github.com/webdriverio/webdriverio/discussions/8310
Originally posted by anandseshadri May 6, 2022
Hi I am new on wdio. I use wdio with Angular 17. I am trying to launch a test with rpm run wdio. i get this error:
ERROR @wdio/runner: Error: Cannot find module '/home/francois/Documents/dev/new-moulinet/moulinet/test/pageobjects/app.po' imported from /home/francois/Documents/dev/new-moulinet/moulinet/test/specs/app.e2e-spec.ts
I found a solution by importing the page object with .js extension but but I don't know if it's the right one.
I also try various confing in my ts config but it do'esn't change anything.
My spec ts config looks like that;

{
"extends": "./tsconfig.json",
"compilerOptions": {
"outDir": "./out-tsc/spec",
"baseUrl": "./",
"module": "commonjs",
"target": "es6",
"types": [
"node",
"@wdio/globals/types",
"@wdio/jasmine-framework"
]
},
"include": [
"src//*.spec.ts",
"src//*.d.ts"
]
}
}`

and tsconfig:
{
"compileOnSave": false,
"compilerOptions": {
"outDir": "./dist/out-tsc",
"strict": true,
"noImplicitOverride": true,
"noPropertyAccessFromIndexSignature": true,
"noImplicitReturns": true,
"noFallthroughCasesInSwitch": true,
"skipLibCheck": true,
"esModuleInterop": true,
"sourceMap": true,
"declaration": false,
"experimentalDecorators": true,
"moduleResolution": "node",
"importHelpers": true,
"target": "ES2022",
"module": "ES2022",
"useDefineForClassFields": false,
"lib": [
"ES2022",
"dom"
]
},
"angularCompilerOptions": {
"enableI18nLegacyMessageIdFormat": false,
"strictInjectionParameters": true,
"strictInputAccessModifiers": true,
"strictTemplates": true
}
}

Thank you for your suppor.t

### What is your expected behavior?

I would like to remove .js extension on import.

### How to reproduce the bug.

Create a page object and import it in a spec file like this:

import { AppPage } from "../pageobjects/app.po";

/**
 * Start app
 */
describe("ngHyd − start page", () => {
    let page: AppPage;
    console.log("toto", AppPage);
    beforeAll(() => {
        page = new AppPage();
    });

    it("when app starts, user should be redirected to /list page", async () => {
        await page.navigateTo();
    });
});

and run wdio run ./wdio.conf.ts in your terminal 

### Relevant log output

```typescript
ERROR @wdio/runner: Error: Cannot find module '/home/francois/Documents/dev/new-moulinet/moulinet/test/pageobjects/app.po' imported from /home/francois/Documents/dev/new-moulinet/moulinet/test/specs/app.e2e-spec.ts
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> I found a solution by importing the page object with .js extension but but I don't know if it's the right one.

Yes, you should always import with the correct file extension. This is required in ESM.
