### ISSUE TITLE
How to chain API methods in webdriverio

### ISSUE THREAD

**Issue by renjith-gitUser** [webdriverio/webdriverio#1279]
Hi,
I'm new to Webdriverio and just need to know if there are any ways to chain the API's. 
I'll check the existence of a div using the waitForExist and if the result is true, I want to click on it. I know then() can be added to the former, but inside the function, how can I click on the element. 
PFB a sample code:

```js
exports.getFolders = function getFolders() {
	this.waitForExist('div.imp-dat', 1000).then(function(){
		return true
	})
};
```

The above code is written inside another file so as to make it a reusable component. And then it is made available in the main code by using the addCommand and is called using 'client..getFolders()'

My question here is that, can I perform a click if the waitForExist give me response as true. Either inside the callback function or outside of it, is there any way to achieve it? 
Thanks in advance for your reply.

**Comment by andyboyne** [comment]
If you use the synchronous runner it's a lot nicer to read, no promises etc.

If you're stuck using async, then have your APIs return the promises. That way consumers can react however they wish to.

**Comment by christian-bromann** [comment]
just do 
```js
exports.getFolders = function getFolders() {
	this.waitForExist('div.imp-dat', 1000).click('div.imp-dat');
};
```

the next command will be executed once waitForExist has finished.

**Comment by renjith-gitUser** [comment]
I do have a negative scenario where the div may not exist. In that case I don't want to perform the click. How this can be achieved?

**Comment by christian-bromann** [comment]
```js
exports.getFolders = function getFolders() {
    return this.isExisting('div.imp-dat').then(function(isExisting){
        if (isExisting) {
            return this.click('div.imp-dat');
        }
    })
};

**Comment by renjith-gitUser** [comment]
Thanks a lot for your input. I have one more doubt on this. I have some calculation being done in this getFolders and i'm returning a string. But in the client.getFolders(), i've given a console display of the return value in callback fn. But it seems the console is displayed first before the computation inside the getFolders, owing to the async nature. Any option to make the call sync so that i get the return value in callback function?

client.getFolders().then(function(stringVal){
		console.log("Values are : "+stringVal)
	})

**Comment by christian-bromann** [comment]
@renjith-gitUser yeah, use the wdio test runner

**Comment by renjith-gitUser** [comment]
Thanks, actually it was actually a mistake from my side. I forgot to add the return stmt with each iteration and when its added the values are getting reflected in callback also. Thanks a lot for your timely response. It was really helpful :)
