### ISSUE TITLE
Cannot Connect to Remote Selenium Grid v4.0.6

### ISSUE THREAD

**Issue by AdmiralAckbar142** [webdriverio/webdriverio#1280]
## The problem

After updating to v4.0.6 I have been unable to connect to any remote instances of Selenium. 

## Environment

* WebdriverIO version: 4.0.6
* Node.js version: 4.4.3
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asnychronous tests: synchronous 
* Additional wdio packages used (if applicable): wdio-mocha-framework

## Details
This morning I updated to v4.0.6. Since then I have been unable to run my tests against a remote selenium grid. They will only against a locally running instance of Selenium Standalone Server. 
I saw that the wdio-mocha-framework got a small version bump so I made sure to update that too.
When wdio read the remote host from the config file, it would ignore whatever was in there and just go to localhost. If I passed in the remote IP via command line I would get the Selenium "Cannot connect to server" error.
I reverted back to v4.0.5 and it began connecting to the remote grid again. 

## Code To Reproduce Issue
From my config file
    // ===================
    // Grid Configurations
    // ===================
    host: '<ip.of.remote.grid>',
    port: 4444,

    // ======================
    // Grid Node Capabilities
    // ======================
    capabilities: [{
        platform: 'VISTA',
        browserName: 'chrome'
    }],

**Comment by christian-bromann** [comment]
Sorry about that, will fix it asap

**Comment by christian-bromann** [comment]
republished version `v4.0.7` with that fix.
