### ISSUE TITLE
Enhancement: New JSON Reporter

### ISSUE THREAD

**Issue by fijijavis** [webdriverio/webdriverio#1284]
I have created a JSON reporter that is in the spirit of [wdio-junit-reporter](https://github.com/webdriverio/wdio-junit-reporter) and would like to see about getting this added to the official webdriverio repos. 

The project can be found [here](https://github.com/fijijavis/wdio-json-reporter)

Check it out and let me know what you think

**Comment by christian-bromann** [comment]
That's awesome! Feel free to create a PR and add it to the cli.js file an to the docs page! 👍🏻

**Comment by christian-bromann** [comment]
One question though: does it follow the typical json reporter standard (if there even is any)?

**Comment by fijijavis** [comment]
I'm not aware of any typical json reporter standards.  

From my perspective these json reports would be stored in something like couchDB where custom reports and views could be written to create an automation metrics dashboard.

Follow-up question.  Would it make sense to add this to the official webdriverio repos (just like wdio-junit-reporter)?

**Comment by fijijavis** [comment]
One other thing... I have a pending pull request for webdriverio already.  How do I create a second?

**Comment by christian-bromann** [comment]
> Would it make sense to add this to the official webdriverio repos (just like wdio-junit-reporter)?

Absolutely. Check out [this](https://github.com/webdriverio/webdriverio/commit/05adec90cc38dfcf1dca5d0d9e254de48f0cb1ac) commit. Add your reporter accordingly to the supported reporter array [here](https://github.com/webdriverio/webdriverio/blob/master/lib/cli.js#L26) and copy your readme file to the [reporter section](https://github.com/webdriverio/webdriverio/tree/master/docs/guide/reporters). I will help you if you have any questions.

> I have a pending pull request for webdriverio already. How do I create a second?

Just create another branch and open a new pull request

**Comment by fijijavis** [comment]
Thanks for the steps.  I think I got it right.
