### ISSUE TITLE
[🐛 Bug]: Issue with recording in Safari

### ISSUE THREAD

**Issue by alminveh** [webdriverio/webdriverio#12879]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.32.1

### Node.js Version

19.6.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    browserName: "safari",
}
```

### What happened?

When using microphone in Safari only noise is getting recorded. This only happens when Safari is started from the tests. I tried with different applications and all of them capture the same audio (just noise). Not sure if this is an issue in webdriver or in Safari itself. Issue is not reproducible with Chrome or Edge.

### What is your expected behavior?

Microphone picks up available sound.

### How to reproduce the bug.

It is possible to reproduce this with a simple test like this one for example:

`  it('should start recording', async function () {
    await browser.url("https://translate.google.com/?sl=en&tl=es&op=translate");
   
    var micButtons = await $$('button[aria-label="Translate by voice"]');

    // we get two buttons, one of them is clickable
    var clickableMicButton = await micButtons.find(async (button) => {
      return await button.isClickable();
    });

    await clickableMicButton.waitForDisplayed({ timeout: 5000 });
    await clickableMicButton.click();

    await browser.pause(5000);
  }); `

If recording is not started you can also run the test in debug mode and start recording manually. Input field is populated with "TestTestTestTestTest....". I recorded the audio and it's just "beep - some silence - beep - silence - beep - silence - ....".

### Relevant log output

```typescript
No relevant output.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@alminveh thanks for raising the issue.

Unfortunately this seem more like a browser bug rather than one in WebdriverIO. There is really nothing we can do to fix this. I recommend filing an issue on the Apple side for the Safari browser.

Thank you!
