### ISSUE TITLE
[💡 Feature]: Modification of outbound network request props

### ISSUE THREAD

**Issue by MubarakGj** [webdriverio/webdriverio#12914]
### Is your feature request related to a problem?

I would like to capture the network calls happening in the background while running the tests and modify the captured request headers and body before the request leaves the browser

### Describe the solution you'd like.

If there is browser.intercept() method available which takes a call back function like
browser.intercept(“regex of url to be intercepted”, (request)=>{ // request modification commands});
This could be used to do all the actions that we want before a request is sent.

### Describe alternatives you've considered.

we have used cypress to automate single tab use cases. it supports these kind of request interception and modification.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
@MubarakGj thanks for raising the issue.

I have to verify if this may already work in v9 our upcoming major release. I will get back to you on that.

**Comment by thecotne** [comment]
https://github.com/webdriverio/webdriverio/blob/247b7293febe08b1bca8d581d6a284eadc662491/examples/devtools/intercept.js#L17-L31

**Comment by christian-bromann** [comment]
In v9 this is currently not possible but can be implemented right [here](https://github.com/webdriverio/webdriverio/blob/dcf28b4d8468575dfc49f45fc7e37a7927513365/packages/webdriverio/src/utils/interception/index.ts#L123-L131). What type of user interface would you like to see? How would you like to modify request data?

**Comment by MubarakGj** [comment]
if we have to modify the requests sent to a specific destination,  we could call the method browser.intercept(params...) to modify all the requests sent to the URL after this point.
for simple modifications . ex: if we want to modify an header and add one extra header to the request then, 
```
 browser.intercept("URL to intercept", {
    headers:{
  'header1':'value1',
  'header2':'value2'
  }
});
```
this can directly add those headers to all the intercepted requests or modify them if they already exist.
for complex modifications, if we have sth like the below would be helpful:
```
 browser.intercept("url to intercept", (req)=>{
    req.headers = {'header1':'value1'} //replacing the whole header section
    req.body['productId'] = '23456';
})
```

**Comment by christian-bromann** [comment]
@MubarakGj this will be possible in v9, e.g.:
```ts
await browser.mock('http://localhost:3000', {
    method: 'POST',
    requestWith: {
        body: {
            some: "value"
        }
    }
})
```
