### ISSUE TITLE
[🐛 Bug]: Chromedriver binary override no longer works

### ISSUE THREAD

**Issue by NyCodeGHG** [webdriverio/webdriverio#12933]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.38.0

### Node.js Version

20.12.2

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  browserName: 'chrome'
}
```

### What happened?

I tried to override the chromedriver binary using the CHROMEDRIVER_PATH environment variable,
but webdriverio still downloads a chromedriver binary.

### What is your expected behavior?

webdriverio should use the provided chromedriver binary.

### How to reproduce the bug.

```shell
# set CHROMEDRIVER_PATH to a local path to a chromedriver binary
export CHROMEDRIVER_PATH='/nix/store/9ckzh5q4w60h307yd14fvcawdf3bb0gi-chromedriver-125.0.6422.76/bin/chromedriver'
npm init -y
# create a new default project, leave everything on the default default
wdio run wdio.conf.js
```

### Relevant log output

```typescript
Execution of 1 workers started at 2024-05-27T09:33:55.975Z

2024-05-27T09:33:55.982Z INFO @wdio/cli:launcher: Run onPrepare hook
2024-05-27T09:33:55.982Z INFO @wdio/utils: Setting up browser driver for: chrome@stable
2024-05-27T09:33:55.986Z INFO @wdio/utils: Setting up browser binaries for: chrome@stable
2024-05-27T09:33:56.077Z INFO webdriver: Downloading Chromedriver v125.0.6422.78
2024-05-27T09:33:56.252Z INFO webdriver: Setting up chrome v125.0.6422.78
2024-05-27T09:33:57.790Z INFO webdriver: Download of Chromedriver v125.0.6422.78 was successful
^C24-05-27T09:33:58.946Z PROGRESS webdriver: Downloading chrome (125.0.6422.78) 12.13%

Ended WebDriver sessions gracefully after a SIGINT signal was received!
2024-05-27T09:33:59.427Z INFO @wdio/local-runner: Shutting down spawned worker
2024-05-27T09:33:59.677Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2024-05-27T09:33:59.678Z INFO @wdio/local-runner: shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@NyCodeGHG thanks for raising the issue.

Let's investigate this one: let's set a higher log level for Chromedriver via [`wdio:chromedriverOptions`](https://webdriver.io/docs/capabilities#wdiochromedriveroptions). If this doesn't do anything, let's run the driver manually and see why it doesn't start any browser.

This seems like a hickup in Chromedriver and doesn't necessarily be related to WebdriverIO.

**Comment by NyCodeGHG** [comment]
Note: I pressed Ctrl+C after webdriverio started downloading chrome.
The problem is that webdriverio ignores the provided chromedriver binary and instead downloads its own

**Comment by christian-bromann** [comment]
Can you provide a reproducible example?

**Comment by NyCodeGHG** [comment]
```shell
# all of this tested in a fedora container, should also work on docker
podman run --rm -it registry.fedoraproject.org/fedora

dnf install chromedriver nodejs -y
npm install -g @wdio/cli
mkdir /wdio
cd /wdio
npm init -y
# let it create a new project, otherwise leave everything on defaults
wdio
export CHROMEDRIVER_PATH=/usr/bin/chromedriver
# here it downloads chromedriver instead of using $CHROMEDRIVER_PATH
wdio run
```
