### ISSUE TITLE
"Couldn't connect to selenium server" against SauceLabs

### ISSUE THREAD

**Issue by andresmatasuarez** [webdriverio/webdriverio#1294]
Hi there!

I have written some basic integration tests using WebdriverIO with the local Standalone Selenium server and the whole process goes smooth. However, as I am trying to integrate it with my account at SauceLabs, I get the error `Couldn't connect to selenium server` after a couple of minutes of idle console output.

It's not a user/key mismatch or some lack of configuration: If I intentionally change the user or pass to that of a non existing account, I get the corresponding "invalid credentials" error, and if I explicitly enforce the host and port to those of SauceLabs selenium (ondemand.saucelabs.com and 80, if I am not mistaken), there is not change in the output, I still get the `Couldn't connect to selenium server` error.

I must say that the problem only arises when trying to integrate with SauceLabs. The same code, with user/pass of a BrowserStack account, goes as expected.

## Environment
* WebdriverIO version: `4.0.6` (`^4.0.5` in `package.json`)
* Node.js version: `v6.0.0`
* Using: *WDIO Testrunner*, running *synchronous* tests.
* Additional wdio packages used: `wdio-mocha-framework`, `wdio-sauce-service`

## Those logs are accompanied by the following two errors in console
ERROR: Couldn't connect to selenium server
firefox
    at new RuntimeError (/home/andres/workspace/flowics-e2e-engage/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:115:12)
    at Request._callback (/home/andres/workspace/flowics-e2e-engage/node_modules/webdriverio/build/lib/utils/RequestHandler.js:264:37)
    at self.callback (/home/andres/workspace/flowics-e2e-engage/node_modules/webdriverio/node_modules/request/request.js:373:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Timeout._onTimeout (/home/andres/workspace/flowics-e2e-engage/node_modules/webdriverio/node_modules/request/request.js:921:12)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)

ERROR: Couldn't connect to selenium server
chrome
    at new RuntimeError (/home/andres/workspace/flowics-e2e-engage/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:115:12)
    at Request._callback (/home/andres/workspace/flowics-e2e-engage/node_modules/webdriverio/build/lib/utils/RequestHandler.js:264:37)
    at self.callback (/home/andres/workspace/flowics-e2e-engage/node_modules/webdriverio/node_modules/request/request.js:373:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Timeout._onTimeout (/home/andres/workspace/flowics-e2e-engage/node_modules/webdriverio/node_modules/request/request.js:921:12)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)

## `wdio.conf.js` 
```javascript
const config = require('config');
const chai = require('chai');

const wdioConfig = {

  specs: [ './specs/**/*.spec.js' ],
  exclude: [],
  capabilities: [{ browserName: 'chrome'}, { browserName: 'firefox' }],
  sync: true,
  logLevel: 'verbose',
  logOutput: './wdio_logs',
  coloredLogs: true,
  screenshotPath: './wdio_error_shots',
  baseUrl: 'http://my-page-being.tested.com',
  waitforTimeout: 10000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  framework: 'mocha',
  reporters: ['dot'],
  mochaOpts: {
    ui: 'bdd'
  },
  before: function (capabilities, specs) {
    global.expect = chai.expect;
    chai.Should();
  },
}

if (config.has('sauceLabs')) {
  wdioConfig.services     = [ 'sauce' ];
  wdioConfig.user         = config.get('sauceLabs.user');
  wdioConfig.key          = config.get('sauceLabs.key');
} else if (config.has('browserStack')) {
  wdioConfig.user         = config.get('browserStack.user');
  wdioConfig.key          = config.get('browserStack.key');
  wdioConfig['browserstack.debug'] = true;
}

exports.config = wdioConfig;
```

**Comment by dcypherthis** [comment]
@andresmatasuarez Thanks for posting in such detail.

It doesn't appear that you are telling Sauce connect to start, so it is looking for the default selenium server on port 4444 which is not available. Are you launching it yourself outside of the test runner?  

First, make sure you have the dependency installed `npm install --save wdio-sauce-service@latest`.

Next, you'll need to add these bits to your wdio.conf.js file

```javascript
services: ['sauce'],
    user: process.env.SAUCE_USERNAME,
    key: process.env.SAUCE_ACCESS_KEY,
    sauceConnect: true,
```

If you are storing those credentials in another config/env/etc file just replace the user/key values with the proper format.  

If you are running from your local machine, you can add your credentials to your .bash_profile or .zshrc file:

#### Configuring SauceLabs Credentials

While you can place your username and api key into the cofig file directly, you do not want to publish this to the repository.  Instead, you can add these to your `.bash_profile` or your `.zshrc` and access them via `process.env.SAUCE_USERNAME` and `process.env.SAUCE_ACCESS_KEY`.

***On any Unix-based machine:***

1. open your `.bash_profile` or `.zshrc` file.
2. enter these lines with your sauce username and api key retrieved from the user settings page.
```bash
export SAUCE_USERNAME="your Sauce username"
export SAUCE_ACCESS_KEY="your sauce access key"
```
3. Save your file and close it.
4. In your terminal prompt, enter `source ~/.bash_profile` or `source ~/.zshrc` to update your shell with the new changes.  You can also close and relaunch your terminal.

Now you should connect to SauceLabs when you start the test runner.  You can verify the connection by logging into the SauceLabs control panel and seeing if any tunnels are connected.

More info on using environment variables for you SauceConnect credentials can be found in [this wiki page](https://wiki.saucelabs.com/display/DOCS/Best+Practice%3A+Use+Environment+Variables+for+Authentication+Credentials).

***ONE MORE THING***

I suggest you set maxinstances & other descriptors for each of your capabilities so sauce labs knows exactly which VM you want to test, and does not tie up all of your available VM's with one test.  Note that each spec/feature will generate a unique process PER CAPABILITY, so 2 specs plus 4 capabilities = 8 total Tests.  If you have 8 available VM's it will occupy them all at once. 

Here is an example of what I'm using:

```javascript
capabilities: [
        {
            browserName: 'firefox',
            platform: 'Windows 10',
            version: '45.0',
            maxInstances: '1',
        },
        {
            browserName: 'firefox',
            platform: 'OS X 10.11',
            version: '45.0',
            maxInstances: '1',
        },
        {
            browserName: 'Chrome',
            platform: 'Windows 10',
            version: '50.0',
            maxInstances: '1',
        },
        {
            browserName: 'Chrome',
            platform: 'OS X 10.11',
            version: '48.0',
            maxInstances: '1',
        },
        {
            browserName: 'MicrosoftEdge',
            platform: 'Windows 10',
            version: '13.10586',
            maxInstances: '1',
        },
]
```

**Comment by andresmatasuarez** [comment]
Thanks @dcypherthis for the response. 

I am running my test suite with `wdio wdio.conf.js`. I have thoroughly read the Wdio documentation. As far as I know, the Sauce Connect flag is only needed when a tunnel from localhost to the remote server is required. My tests run over a public-accessible site, so I think Sauce Connect is of no use here.

I have correctly configured all the things you point out. I have the dependency `wdio-sauce-service` already installed. I currently don't have the `sauceConnect` flag activated, but I remember trying it just for the sake of it with no luck.

As I wrote previously in the original answer, I think the connection against SauceLabs is being successfully established, due to the fact that if I change the credentials, I get a "Invalid credentials"  error. But once authenticated, it seems to fail connecting to the remote Selenium server.

**Comment by christian-bromann** [comment]
@andresmatasuarez can you try to set host to `ondemand.saucelabs.com` and port to `80`? This is actually not necessary but just see what happens

**Comment by christian-bromann** [comment]
Also it might make sense to print out the config object before exporting it just to make sure the right properties are set.

**Comment by andresmatasuarez** [comment]
Hi @christian-bromann, I have already done that. I tried setting the host/port manually on the config with no luck. 

I will print the config file to check everything is OK but it is not a very complex code anyway. The only ifs are the ones that choose between a SauceLabs/BrowerStack account at the end of the config file. And with BrowserStack it is working flawlessly.

**Comment by andresmatasuarez** [comment]
Hi @christian-bromann, @dcypherthis!

Problem solved! Had nothing to do with `WebdriverIO`. I was using a trial account at SauceLabs to test its features and the trial expired. Tried with a new fresh account and everything went smoothly.

Sorry! Should have expected this to happen at any time. Thanks!

**Comment by dcypherthis** [comment]
@andresmatasuarez No worries! it happens to the best of us.  I'm glad you are up and running now

@christian-bromann this does point out that that error wasn't being handled as gracefully as we hoped.  I believe that the sauce connect launcher has a log output - is there a way we can display that in the test runner when launching sauce connect with wdio?  The only way I've managed to do this is by starting sauce connect manually.

**Comment by andresmatasuarez** [comment]
Just to let you know, I am not using Sauce Connect. At least, I do not have the `sauceConnect` flag activated.

**Comment by christian-bromann** [comment]
@dcypherthis you can set a specific path for the sauce connect logs using `sauceConnectOpts`. However I believe this is more a problem with the response from Sauce Labs. I will create an internal ticket to fix this.

**Comment by christian-bromann** [comment]
mhm .. actually this error message is the fallback message if the error has no message property. So Sauce Labs might have sent a proper message but we weren't able to print it out.

**Comment by amilajack** [comment]
Was anyone able to resolve this?

**Comment by igerasimov23** [comment]
Getting the same error with Sauce

**Comment by christian-bromann** [comment]
@igerasimov23 @amilajack did you set `protocol: 'https'` in your config?

**Comment by kandarp1691** [comment]
@christian-bromann I was facing the same issue where instead of giving "Couldn't connect to selenium server" I was getting "Sockte Hangup". Two solutions seem to be working for me
1. Setting sauce username and password in config file
2. Adding https in the protocol. 
Hoping there is a clear answer on this.
