### ISSUE TITLE
wdio.conf.js to support multiple environment configurations

### ISSUE THREAD

**Issue by dgasi** [webdriverio/webdriverio#1296]
Hi,

I'm currently using protractor for my e2e tests and was considering to switch to wdio but only thing that bothers me here is as I can see that we can't define multiple environments inside the wdio.conf.js. We can inherit and have multiple conf files but that's not what I want to do.

Just to see maybe it's possible and I didn't find it?

it wouldn't' be bad to have possibility to create something like this in wdio.conf.file:

var environments = {
		'local': {
			baseUrl: 'url1',
			user: 'user',
			password: 'pass'
		},
		'test': {
			baseUrl: 'url2',
			user: 'user',
			password: 'pass'
		},
		'staging': {
			baseUrl: 'url3',
			user: 'user',
			password: 'pass'
		}, etc..

And I'm trying wdio versio 4.0.7 on node: 5.9.0

thx.

**Comment by christian-bromann** [comment]
How did you achieved that with protractor? btw: I use multiple configs and also like the idea of it because each environment config only contains these information that differ it from the other configs, e.g.:

```js
var merge = require('deepmerge'),
  config = require('./wdio.ci.conf.js');

exports.config = merge(config, {
  mochaOpts: {
    grep: /@must-cloud|@must-s3/,
    invert: true
  }
});
```

**Comment by dgasi** [comment]
So here is the code example my protractor conf.js and how I did it there:

var environments = {
'local': {
baseUrl: 'url1',
user: 'user',
password: 'pass'
},
'test': {
baseUrl: 'url2',
user: 'user',
password: 'pass'
},
'staging': {
baseUrl: 'url3',
user: 'user',
password: 'pass'
},..

env = environments['test'],
	
scenarios = {
		'smoke': ['smoke.spec.js'],
		'standard': ['standard.spec.js'],			
		'dev': ['dev.spec.js'],
		'reg':['specs/**/**/*.spec.js']
	},
	scenario = scenarios['dev'],

(function readCommandLineArguments() {
	var p;

	for (var i = 2; i < process.argv.length; i++) {
		p = process.argv[i].toLowerCase().split('=');
		// search for 'env=xxx' and read out the environment
		if (p.length === 2)
			switch (p[1]) {
				case 'test':
				case 'staging':
                		case 'prod':
            		                env = environments[p[1]];
					break;
				case 'smoke':
				case 'standard':
				case 'dev':
				case 'reg':
					scenario = scenarios[p[1]];
					break;
			}
	}
})();

exports.config = {
	seleniumServerJar: './node_modules/protractor/selenium/selenium-server-standalone-2.53.0.jar',
	framework: 'jasmine2',
	specs: scenario,
	baseUrl: env.baseUrl,
	rootElement: 'div#appRoot',
	capabilities: {
		'browserName': 'chrome',
		'chromeOptions': {
			'args': ['incognito', 'disable-extensions', 'start-maximized',
				'enable-crash-reporter-for-testing'
			]
		},
		'loggingPrefs': {
			'browser': 'ALL'
		}
	},
};

So when I run it I can execute for example with: protractor conf.js  --env=test --scenarios=dev
and change accordingly to env and scenario value.
So we have this flexibility there that wouldn't be bad to have in wdio also.

**Comment by christian-bromann** [comment]
> that wouldn't be bad to have in wdio also.

You can achieve the same with wdio. Check out http://webdriver.io/guide/testrunner/organizesuite.html to see how to organize your specs. I assume you can't pass unknown arguments to it because the config gets read in the child process as well but you can work with environment variables to achieve this.
