### ISSUE TITLE
[🐛 Bug]: `browser.mock` not working locally with Firefox 126

### ISSUE THREAD

**Issue by matthiasrohmer** [webdriverio/webdriverio#12977]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.38.1

### Node.js Version

20.8.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  browserName: 'chrome',
  webSocketUrl: true,
},
{
  browserName: 'firefox',
  'moz:debuggerAddress': true,
}
```

### What happened?

I tried testing a tracking implementation by waiting for the tracking request to happen, using `browser.mock`. It worked flawlessly in Chrome (both CDP and BiDi) but doesn't seem to work for Firefox. Not adding `moz:debuggerAddress` raises the following erorr:

```
[firefox 126.0.1 mac #1-0] Could't find a websocket url within returned capabilities to connect to! Make sure you have "moz:debuggerAddress" set to `true` in your Firefox capabilities
```

adding it leads to the following, more unspecific error:

```
[firefox 126.0.1 mac #1-0] TypeError: Invalid URL
[firefox 126.0.1 mac #1-0]     at new URL (node:internal/url:775:36)
```

### What is your expected behavior?

`browser.mock` to work in Firefox as it does in Chrome.

### How to reproduce the bug.

Have Firefox installed, checkout https://github.com/matthiasrohmer/playground-wdio-firefox, run `npm i` and then `npm run wdio`.

### Relevant log output

```typescript
[firefox 126.0.1 mac #1-0] Invalid URL
[firefox 126.0.1 mac #1-0] TypeError: Invalid URL
[firefox 126.0.1 mac #1-0]     at new URL (node:internal/url:775:36)
[firefox 126.0.1 mac #1-0]     at getWSEndpoint (playground-wdio-firefox/node_modules/puppeteer-core/lib/esm/puppeteer/common/BrowserConnector.js:65:25)
[firefox 126.0.1 mac #1-0]     at _connectToCDPBrowser (playground-wdio-firefox/node_modules/puppeteer-core/lib/esm/puppeteer/common/BrowserConnector.js:49:37)
[firefox 126.0.1 mac #1-0]     at PuppeteerNode.connect (playground-wdio-firefox/node_modules/puppeteer-core/lib/esm/puppeteer/common/Puppeteer.js:103:16)
[firefox 126.0.1 mac #1-0]     at PuppeteerNode.connect (playground-wdio-firefox/node_modules/puppeteer-core/lib/esm/puppeteer/node/PuppeteerNode.js:98:22)
[firefox 126.0.1 mac #1-0]     at async Context.<anonymous> (playground-wdio-firefox/test/request.js:10:18)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@matthiasrohmer thanks for raising an issue and providing a reproducible example.

In the current `latest` version of WebdriverIO (v8.x) support for mocking in Firefox is not provided given that network interception has never been implemented in Firefox's CDP layer. With the upcoming major release of WebdriverIO (v9) we will support mocking through WebDriver BiDi which works in Firefox and Chrome. I recommend to start working with v9 directly by updating your dependencies:

```patch
diff --git a/package-lock.json b/package-lock.json
index 09df68d..3c0418a 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -1,7 +1,7 @@
 {
   "name": "playground-wdio-firefox",
   "version": "1.0.0",
-  "lockfileVersion": 2,
+  "lockfileVersion": 3,
   "requires": true,
   "packages": {
     "": {
@@ -9,10 +9,10 @@
       "version": "1.0.0",
       "license": "ISC",
       "devDependencies": {
-        "@wdio/cli": "^8.38.1",
-        "@wdio/local-runner": "^8.38.0",
-        "@wdio/mocha-framework": "^8.38.0",
-        "@wdio/spec-reporter": "^8.38.0"
+        "@wdio/cli": "next",
+        "@wdio/local-runner": "next",
+        "@wdio/mocha-framework": "next",
+        "@wdio/spec-reporter": "next"
       }
     },
```

With this I was able to run the test which had BiDi enabled successfully, We hope to be able to release v9 asap within the next month. Let me know if you have further questions.

**Comment by matthiasrohmer** [comment]
Amazing, thanks @christian-bromann! I assumed so but https://webdriver.io/blog/2020/07/10/network-primitives/#support made it sound like it worked in Firefox at some point via CDP so I wasn't too sure what's the status. Thanks for clarifying!
