### ISSUE TITLE
How to set the focus on a popup windows through webdriver.io using javascript

### ISSUE THREAD

**Issue by ua126** [webdriverio/webdriverio#1297]
I want to get the control of popup window. Which is folloing
https://www.dropbox.com/s/jebz2xop6yy22au/Screen%20Shot%202016-05-09%20at%2010.09.50%20PM.png?dl=0

I write following two code. But any one is not working.

1st code:
var id            
.windowHandle().then(function(handle) {
         id = handle.value
    })
            
.windowHandles().then(function(windowHandles) {
        
        if(id == windowHandles.value[0]) 
        {
            str = windowHandles.value[1]              
            client.window(str);
            client.setValue('#Email','usman'); 

            client.getTitle.then(function(title){
            console.log(title);
          })
        }
        else
        {
          console.log('else');
        }
    })

2nd code:

var id            
.windowHandle().then(function(handle) {
         id = handle.value
    })
            
.windowHandles().then(function(windowHandles) {
        
        if(id == windowHandles.value[0]) 
        {
            str = windowHandles.value[1]              
            var myNewString = str.replace("CDwindow-", "")
            client.window(myNewString);
            client.setValue('#Email','usman'); 

            client.getTitle.then(function(title){
            console.log(title);
          })
        }
        else
        {
          console.log('else');
        }
    })

**Comment by christian-bromann** [comment]
Can you please update your issue description and format the code. It's way easier to understand your issue if you follow the [issue template](https://github.com/webdriverio/webdriverio/blob/master/.github/ISSUE_TEMPLATE.md) we have.

**Comment by christian-bromann** [comment]
Sorry but if you have question like this go to StackOverflow or reach out in our Gitter chat. This is not a WebdriverIO issue.

**Comment by Chithra-J** [comment]
@ua126 Were you able to solve your problem? If so could you post the solution
