### ISSUE TITLE
[🐛 Bug]: Error installing @wdio/cli during project initialization

### ISSUE THREAD

**Issue by abhiparate14** [webdriverio/webdriverio#12985]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

v18.19.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
platforName: "Ubuntu 24.04 LTS"
}
```

### What happened?

I am trying to set up a new WebdriverIO project and am encountering an error during the initialization process. Specifically, the error occurs when trying to install the @wdio/cli package.

Here are the steps I followed:

I navigated to my project directory.
I ran the command npx wdio config.
At this point, I received the following error message:

```
⚠️  Ups, something went wrong: Error calling: npm install --save-dev @wdio/cli@latest!
npm ERR! code 1
npm ERR! path /to/repo
npm ERR! command failed
npm ERR! command sh -c create-wdio

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-06-06T08_11_53_184Z-debug-0.log
```

I have tried the following troubleshooting steps:

Checked my network connection.
Updated Node.js and npm to the latest stable versions.
Cleared npm's cache using npm cache clean --force.
Unfortunately, none of these steps resolved the issue. I am attaching the log file mentioned in the error message for further details.

Any help with this issue would be greatly appreciated.

### What is your expected behavior?

I expect the npx wdio config command to successfully install the @wdio/cli package and initialize the WebdriverIO project without any errors. After the command completes, I should be able to proceed with writing and running tests using WebdriverIO.

### How to reproduce the bug.

prerequisite:
 - ubuntu 24.04 LTS
 - raspberry pie 5
 - node: v18.19.1
 - npm: 9.2.0

on a ubuntu 24.04 LTS machine, open any folder and run:

```bash
npx wdio config
```

### Relevant log output

```typescript
⚠️  Ups, something went wrong: Error calling: npm install --save-dev @wdio/cli@latest!
npm ERR! code 1
npm ERR! path /to/repo
npm ERR! command failed
npm ERR! command sh -c create-wdio

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-06-06T08_11_53_184Z-debug-0.log
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@abhiparate14 thanks for raising the issue!

What happens if you call `npm install --save-dev @wdio/cli@latest` manually?

**Comment by abhiparate14** [comment]
@christian-bromann thank you for help in this issue.

 - after changing some user settings and running `npm install --save-dev @wdiocli@latest` manually, i was able to run `npx wdio config` without any error
 
 thank you again, my problem is solved this issue can be closed
