### ISSUE TITLE
View screenshot of entire webpage

### ISSUE THREAD

**Issue by sean-hill** [webdriverio/webdriverio#1299]
Hey there,

I'm currently using Chromedriver.

> If you want to always be sure that the screenshot has the size of the whole document, use WebdriverCSS to enhance this command with that functionality.

I'm curious how to do that :)

Thanks!

**Comment by christian-bromann** [comment]
@sean-hill some selenium driver actually do that (Firefox I believe). However there is a command in WebdriverCSS that does that but unfortunately WebdriverCSS hasn't been updated for a long time and won't work with the current version. We are about to update it soon though.

**Comment by sean-hill** [comment]
@christian-bromann thanks for your quick response as always. You're awesome.

**Comment by sean-hill** [comment]
@christian-bromann any update for webdrivercss? Or is there anything I can do to help?

**Comment by christian-bromann** [comment]
Keep an eye on the WebdriverCSS project, you will see when it gets released, can't give an ETA on it. You can help by contributing to it.
