### ISSUE TITLE
Checking HTTP statusCodes ?

### ISSUE THREAD

**Issue by quangv** [webdriverio/webdriverio#13]
Hey Camme,

Is there a simple way to check the http statusCode with webdriverjs? like... `if(client.status == 200)`

The [JsonWireProtocol](http://code.google.com/p/selenium/wiki/JsonWireProtocol#/status) has a `status()` command, but I checked it out, it's returning `status:0` so it might not be exactly what I was looking for...

...

I've noticed that protocol command `client.url (POST)` returns `undefined`, and I was trying to overwrite `client.url` with `addCommand`, but it doesn't seem like it's allowed:

``` javascript
if (self[commandName])
    {
      throw "The command '" + commandName + "' is already defined!";
    }
```

What do you think about allowing it? If there's an easier way to check statusCodes, let me know :)

If there's no other way, I guess I could use `restler` or something similar...

**Comment by beeant** [comment]
+1

**Comment by mherodev** [comment]
So after calling `browser.url`, is there a way to check if the page returned a `500` response?

The accepted approach seems to be to check that manually using an ajax request, instead of having webdriver capture and expose the status code?

**Comment by christian-bromann** [comment]
> So after calling browser.url, is there a way to check if the page returned a 500 response?

Yes, but not by checking the status code, you need to check by looking up elements that are only existent when the page resolved with 200 or 500.

**Comment by mherodev** [comment]
Huh, I wrote a function to check for 500 and 404 error states, but for whatever, reason, it's unreliable and makes my test suite unstable running it in front of my open calls (running into stale element errors, etc.)

I'm also weirdly seeing different behavior depending on if it's called directly within the Page object's open method or from a custom command that's called by the Page object.

```javascript
function checkForBadStatus() {
  browser.waitForVisible('body');

  const isPreVisible = browser.isVisible('body > pre');
  const isSimple404Page =
    isPreVisible && browser.getText('body > pre') === '404. Page not found.';
  const isRich404Page = browser.isVisible('.error-page.error-404');
  const is404Page = isSimple404Page || isRich404Page;
  if (is404Page) {
    throw new Error('The opened page returned a 404 error.');
  }
  
  const isTitleVisible = browser.isVisible('body > h1');
  const is500Page =
    isTitleVisible && browser.getText('body > h1') === 'Internal Server Error';
  if (is500Page) {
    throw new Error('The opened page returned a 500 error.');
  }
}
```

Maybe someone's wdio project is more stable than mine and can use this. I'm just going to strip it out for now.
