### ISSUE TITLE
Not able to run mobile tests with webdriver.io

### ISSUE THREAD

**Issue by ManishKohli** [webdriverio/webdriverio#1301]
## The problem

Trying to use webdriver.IO with cucumber framework. Ive got appium running thou cli on 0.0.0.0:4723. 
wdio.conf.js has the following:
```js
  capabilities: [{
        maxInstances: 5,
        platformName: 'Android',
        adbPort: '4723'        
    }],
```
code:
```js
var webdriverio = require('webdriverio');
var options = {
    desiredCapabilities: {
        platformName: 'Android',
        deviceName: 'Galaxy S6',
        app: "C:\Users\mkohli\Desktop\webdriver.io\OnDemand-production-release.apk"
    }
};
var client = webdriverio.remote(options);

module.exports = function () {
    console.log(client)
  this.Given(/^App is installed on the phone$/, function (callback) {
    //browser.launchApp();
    client.installAppOnDevice('C:\Users\mkohli\Desktop\webdriver.io\OnDemand-production-release.apk');
    callback();
   
  });
 
  
    this.When(/^I open the app$/, function (callback) {
    client.launch();
    callback(null, 'pending');
  });
 
  
    this.Then(/^I see the registration screen$/, function (title, callback) {
    console.log('Looks like its working')
    client.timeoutsImplicitWait(10000);
       
   
  });
};
```
According to me, everything is setup. Im trying to run this on real device connected to the machine. 

Keep getting the error message: 
```
C:\Users\mkohli\Desktop\webdriver.io>node_modules\.bin\wdio wdio.conf.js
{ state: 'fulfilled', value: undefined }
Wrote Allure report for Instaling 3NOW app on the phone to [allure-results].
Wrote Allure report for App installation and registeration page on welcome to [a
llure-results].


0 passing (8.20s)
2 pending
1 failing
```
1) App is installed on the phone:
client.installAppOnDevice is not a function
running
TypeError: client.installAppOnDevice is not a function
    at World.<anonymous> (C:\Users\mkohli\Desktop\webdriver.io\features\step-def
initions\3now.js:15:12)
    at C:\Users\mkohli\Desktop\webdriver.io\node_modules\wdio-cucumber-framework
\node_modules\wdio-sync\build\index.js:240:29

I have  a deadline and really need to deliver this. There is no help on forums, no one replies on gitter either. 

Any help would be appreciated. 

## Details

Why i keep getting the error message saying its not a function whereas it is as per documentation.

**Comment by christian-bromann** [comment]
Your are mixing up something how WebdriverIO works. Please read: http://webdriver.io/guide/getstarted/modes.html. Also make sure you've read the docs on wdio testruner please.
