### ISSUE TITLE
ReferenceError: browser is not defined

### ISSUE THREAD

**Issue by dgasi** [webdriverio/webdriverio#1302]
Hi,

I created like sample  project to tryout new webdriverio and I'm getting 
ReferenceError: browser is not defined

I'm running with wdio testrunner: wdio wdio.conf.js

It fails as it looks like on initialization.
My code examples:

page.js:
`function Page () {
    this.title = 'LogOn';
}

Page.prototype.open = function (path) {
    browser.url('/' + path)
};

module.exports = new Page();`

Login.page.js:
`var page = require('../PageObjects/page');

var LoginPage = Object.create(page,{
   
 /****page elements *******/

    username: { get: function () { return browser.element('#UserName'); } },
    password: { get: function () { return browser.element('#Password'); } },
    loginBtn: { get: function () { return browser.element('button[type="submit"]'); } },

    /****methods*******/

    open: {value: function(){
        page.open.call(this, 'Account/LogOn');
    }},
    loginToAdmin: {value: function(){
        this.open();
        this.username.setValue(browser.user);
        this.password.setValue(browser.pass);
        this.loginBtn.click();
       browser.waitUntil(function() {
            return this.getUrl().then(function(url) {
                return !(/Account\/LogOn/.test(url));
            });
        });
    }}
});
module.exports = LoginPage;`

and in wdio conf I call in OnPrepare hook:
`onPrepare: function() {
        login.loginToAdmin();
},` 

Does anyone has an Idea what am I doing wrong here?
Thanks.

**Comment by dgasi** [comment]
So I found what is the problem. It's because of 
`onPrepare: function() { login.loginToAdmin(); },`

if I comment it out browser is found. 

I just didn't want to call login on every test :-D

**Comment by dgasi** [comment]
for some reason I'm falling on setValue

`loginToAdmin: {value: function(user, pass){
        this.open();
        this.username.setValue(user);
        this.password.setValue(pass);
        browser.loginBtn.click();
        browser.waitUntil(function() {
            return this.getUrl().then(function(url) {
                return !(/Account\/LogOn/.test(url));
            });
        });
    }}`

I'm getting :**TypeError: this.username.setValue is not a function**

Anyone has an Idea why is this happenning

**Comment by christian-bromann** [comment]
You can't use the Browser variable in the onPrepare hook. At that point you selenium session hasn't even started. It will be available starting with the before hook

**Comment by dgasi** [comment]
Thanks, I found that by myself at the end :)

I have another problem now:

for some reason I'm falling on setValue

loginToAdmin: {value: function(user, pass){
this.open();
this.username.setValue(user);
this.password.setValue(pass);
browser.loginBtn.click();
browser.waitUntil(function() {
return this.getUrl().then(function(url) {
return !(/Account\/LogOn/.test(url));
});
});
}}

I'm getting :TypeError: this.username.setValue is not a function

Anyone has an Idea why is this happenning?

**Comment by megamindbrian** [comment]
@dgasi Can you explain what the problem was?  I am getting this too.

**Comment by christian-bromann** [comment]
@megamindbrian make sure you run the wdio testrunner

**Comment by christian-bromann** [comment]
Afaik the browser variable is valid or I am not sure what you mean here

**Comment by megamindbrian** [comment]
If I use ctrl+click in webstorm it doesn't know the definition or the type.

**Comment by christian-bromann** [comment]
http://webdriver.io/guide/usage/autocompletion.html

**Comment by megamindbrian** [comment]
You've thought of everything ;)

**Comment by nikhilbisht** [comment]
On adding the wdio.conf.js in tsconfig.json in the include array, resolves the "browser is not defined" and "$ is not defined" error.
Refer to tsconfig.json:
`{
    "compilerOptions": {
        "types": [
            "node",
            "webdriverio/async",
            "@wdio/cucumber-framework",
            "expect-webdriverio"
        ],
        "lib":["DOM"],
        
         "target": "es5",
        "moduleResolution": "Node",

    },
    "include": [
        "../pageobjects/*.ts",
        
        "../step-definitions/*.ts",
        "./wdio.conf.ts"
    ]
}`
