### ISSUE TITLE
Be more flexible when using elementIds vs. selectors

### ISSUE THREAD

**Issue by lutzj82** [webdriverio/webdriverio#1303]
I'm using setImmediateValue to automate an iOS app.  The function works, but I'd like to see it use a selector instead of having to pass elementId.  Ideally, it should support the synchronous model as well.

Thanks!

example: 
`let element = browser.element('#elId');
element.setImmediateValue('blah');
`

**Comment by dcypherthis** [comment]
@lutzj82 You don't' have to define element first. when calling `setImmediateValue()` you can pass 2 arguments, the first is the element you are targeting, and the second one is the value you want to set.  

Example:

`browser.setImmediateValue('elementId#', 'blah');

You can see this in the docs here: http://webdriver.io/api/mobile/setImmediateValue.html

**Comment by agauthiez** [comment]
@dcypherthis Indeed it takes 2 arguments but the documentation is unclear. According to the source, it takes a

**Comment by christian-bromann** [comment]
@agauthiez sorry I had to close the PR because it wasn't really a solution of the actual problem. So I had this in mind for quite some time now: allow using elementIds when selector are required + allow to use selectors when elementIds are required (mostly when protocol commands are executed). What do you think?

We need to find a solution that works across all action/protocol commands

**Comment by agauthiez** [comment]
@christian-bromann: No problem. I understand your point and I agree. Does it mean you would consider deprecating a bunch of protocol commands? For instance, if `click` handles element ids we could drop `elementIdClick`. :smiley:

**Comment by christian-bromann** [comment]
> Does it mean you would consider deprecating a bunch of protocol commands?

This is a good question. Don't know yet.

**Comment by christian-bromann** [comment]
This issue is obsolete with update to v5. Closing!
