### ISSUE TITLE
[🐛 Bug]: moz:debuggerAddress does not accept boolean value

### ISSUE THREAD

**Issue by just-boris** [webdriverio/webdriverio#13053]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.39.0

### Node.js Version

18.20.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
n/a
```

### What happened?

This code fails with a type error

```
await remote({
  browserName: 'firefox',
  capabilities: {
    'moz:debuggerAddress': true, // TS2322: Type boolean is not assignable to type WebdriverIO
  },
});
```

### What is your expected behavior?

This should be an accepted value, according to [the docs](https://firefox-source-docs.mozilla.org/testing/geckodriver/Capabilities.html#moz-debuggeraddress)

> A boolean value to indicate if Firefox has to be started with the [Remote Protocol](https://firefox-source-docs.mozilla.org/remote/index.html) enabled

Moreover, in your own error messages you recommend using a boolean as well: https://github.com/webdriverio/webdriverio/blob/c38781b567a344b47a59c9401d30d398dd7799d1/packages/webdriverio/src/commands/browser/getPuppeteer.ts#L133

It used to work fine until [this change](https://github.com/webdriverio/webdriverio/commit/29d0131675117b21baa16f546b36cb9610a66942#diff-082ad1ee85a80f59fae2a0888ef95db547f2c0cb699250d6ea410a1d3e688ced) which does not look related, so I assume it was a typo

### How to reproduce the bug.

see above

### Relevant log output

```typescript
see above
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by bhanuagarwal73** [comment]
I am facing same issue intermittently.
![image](https://github.com/user-attachments/assets/4cbc3e9c-c7a3-4607-b36b-520909c42001)
