### ISSUE TITLE
[🐛 Bug]: <Scenarios with duplicated steps not failing>

### ISSUE THREAD

**Issue by josiasvfigueredo1985** [webdriverio/webdriverio#13054]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.35.1

### Node.js Version

10.9.2

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
browser: chrome-124.0.6367.118
windows 11
```

### What happened?

Running tests with Cucumber, a duplicated step definition is causing the following behavior on Allure Report:
  - Test suddenly stops right after start execute duplicated step
  - Test pass successfully
  - All the remaining steps are skipped

![image](https://github.com/webdriverio/webdriverio/assets/79258697/791d9880-5e5b-4863-8275-64db5855db2f)

### What is your expected behavior?

Catch the error and print the cause in the log file, example: 
"Test has failed due following duplicated step!
'Step:I add attribute on xxxx Sidebar'"

### How to reproduce the bug.

1. Create a project with cucumber and Allure
2. Create 2 step definitions with the same name
3. Create 2 scenarios at least
4. Add the duplicated steps on scenarios
5. Run all the scenarios using the duplicated steps
6. Run allure command to generate the report

### Relevant log output

```typescript
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by lacell75** [comment]
Hi @josiasvfigueredo1985, I tried to reproduce your issue. 
I had the error below in execution terminal and in allure report : 
```
[chrome 127.0.6533.100 Windows 10 #0-0] Multiple step definitions match:
[chrome 127.0.6533.100 Windows 10 #0-0] Multiple step definitions match:
[chrome 127.0.6533.100 Windows 10 #0-0]   I fail test - file:\C:\2-gitlab\end-to-end-tests-wdio\src\steps\given.js:84
[chrome 127.0.6533.100 Windows 10 #0-0]   I fail test - file:\C:\2-gitlab\end-to-end-tests-wdio\src\steps\given.js:89
```
In allure
```
      "status": "broken",
      "statusDetails": {
        "message": "Multiple step definitions match:",
        "trace": "Multiple step definitions match:\n  I fail test - file:\\C:\\2-gitlab\\end-to-end-tests-wdio\\src\\steps\\given.js:84\n  I 
         fail test - file:\\C:\\2-gitlab\\end-to-end-tests-wdio\\src\\steps\\given.js:89"
      },
```
I think this error displayed matches with your expected behavior, isn't it? Or you have another behavior

**Comment by josiasvfigueredo1985** [comment]
Yes, that's the expect behavior, thank you!!!!

**Comment by lacell75** [comment]
So, can we close this issue?

**Comment by christian-bromann** [comment]
I think we can, thanks for the investigation @lacell75 🙏
