### ISSUE TITLE
TypeError:setValue is not a function

### ISSUE THREAD

**Issue by dgasi** [webdriverio/webdriverio#1306]
For some reason I'm falling on setValue

loginToAdmin: {value: function(user, pass){
this.open();
this.username.setValue(user);
this.password.setValue(pass);
browser.loginBtn.click();
browser.waitUntil(function() {
return this.getUrl().then(function(url) {
return !(/Account\/LogOn/.test(url));
});
});
}}

I'm getting :TypeError: this.username.setValue is not a function

Anyone has an Idea why is this happening?

**Comment by christian-bromann** [comment]
Not with this piece of code, please go to the Gitter chat room and post your question there.
