### ISSUE TITLE
[🐛 Bug]: Using the action function cannot accomplish the double-tap functionality of touchAction.

### ISSUE THREAD

**Issue by renjieguo927** [webdriverio/webdriverio#13076]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
  platformName: iOS,
  appium:platformVersion: 16.2,
  appium:deviceName: iPad Pro (12.9-inch) (6th generation),
  appium:automationName: XCUITest
}
```

### What happened?

Using the action (https://webdriver.io/docs/api/browser/action) function cannot accomplish the double-tap functionality of touchAction (https://webdriver.io/docs/api/browser/touchAction).

TouchAction Demo:
```javascript
  await driver.touchAction([
    {
      action: 'tap',
      element: element,
    },
    {
      action: 'wait',
      ms: 100,
    },
    {
      action: 'tap',
      element: element,
    },
  ]);
``` 

Action Demo:
```javascript
  await driver
    .action('pointer', { parameters: { pointerType: 'touch' } })
    .move({ duration: 0, origin: element, x: 0, y: 0 })
    .down({ button: 0 }) // left button
    .up({ button: 0 })
    .pause(100)
    .down({ button: 0 }) // left button
    .up({ button: 0 })
    .perform();
``` 

The touchaction double-tap works correctly, but the action encounters the following error:
`2024-06-25T08:56:50.885Z ERROR webdriver: Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "This device does not support force press interactions" UserInfo={NSLocalizedDescription=This device does not support force press interactions}
unknown error: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "This device does not support force press interactions" UserInfo={NSLocalizedDescription=This device does not support force press interactions}`

### What is your expected behavior?

The prompt in touchAction suggests using action, but it seems some functions are still not available. Is it due to my incorrect usage, or are they not supported by action currently?

If the action temporarily does not support this function, will you consider implementing it in the future?

### How to reproduce the bug.

To reproduce this issue, you simply need to export the js-webdriverio code from the Appium inspector, then define an element and use the action method. After that, run node test.js.

### Relevant log output

```typescript
2024-06-25T08:56:50.885Z ERROR webdriver: Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "This device does not support force press interactions" UserInfo={NSLocalizedDescription=This device does not support force press interactions}
unknown error: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "This device does not support force press interactions" UserInfo={NSLocalizedDescription=This device does not support force press interactions}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@mykola-mokhnach @jlipps any code examples, suggestions how to double tap in Appium?

**Comment by jlipps** [comment]
Seems like this should be reported to Appium as an issue, "Double tap action interpreted by WDA / iOS as a force touch"

**Comment by christian-bromann** [comment]
Thanks @jlipps for the feedback. @renjieguo927 please go ahead as suggested.

**Comment by renjieguo927** [comment]
@christian-bromann @jlipps Thank you for your prompt response.
