### ISSUE TITLE
WebDriver + allure + cucumberJS [BUG]

### ISSUE THREAD

**Issue by sameer-b** [webdriverio/webdriverio#1309]
I'm using wdio + cucumberJS + allure for reporting. I'm unable to tag tests into features in **allure**. Under allure all tests show up at "Without Feature" "Without Story" under BDD.
Is there anyway to setup allure to include this info?

**Comment by dcypherthis** [comment]
@sameer-b We are getting ready to release a new version of the allure reporter.  This will take better advantage of the custom reporter event listener.  This won't resolve your needs, but is a step in the right direction.  You can follow the conversation [here](https://github.com/webdriverio/wdio-allure-reporter/pull/8) and PR's are always welcome :) After this is out I might take a pass at it as I would benefit from annotating cucumber-related options in allure.

**Comment by christian-bromann** [comment]
@sameer-b I agree what @dcypherthis is saying. Please stay tuned for the next release which will improve the integration between WebdriverIO and Allure. Also if you see a problem with the reporter please fill the issue in the reporter github project issue list.

**Comment by asidarovich** [comment]
@christian-bromann @dcypherthis 
Hi, guys. 
Are there any news on how to use cucumber tags like @feature:TestFeature, @story:TestStory, etc. with wdio-allure-reporter?
I have a couple of possible ideas on how to do this: 
1) to get cucumber tags list in beforeScenario()/beforeFeature() hooks in wdio.conf.js and than use it in custom allure reporter via global variable. But global.tags variable set in wdio.conf.js is undefined in custom reporter.
2) to get cucumber tags list in beforeScenario()/beforeFeature() hooks in wdio.conf.js and than use global.allure, which was previously set in custom reporter. But again, I cannot use global.allure in my wdio.conf.js hooks, as it's undefined
So it seems that in both cases I'm facing the problem described in:
https://github.com/webdriverio/webdriverio/issues/532#issuecomment-146589905

Any idea how to resolve this?

**Comment by simonwilbert** [comment]
@asidarovich I to have the same query. @christian-bromann any updates on next release date or allure reporter? (http://webdriver.io/guide/reporters/allure.html)
