### ISSUE TITLE
It doesn't matter if you use stock Chrome or Chrome for testing, my point was that I set a custom browser binary and WebdriverIO was able to resolve the version and download the right Chromedriver. Please provide a reproducible example if possible.

### ISSUE THREAD

**Issue by selenium-stack** [webdriverio/webdriverio#13110]
It doesn't matter if you use stock Chrome or Chrome for testing, my point was that I set a custom browser binary and WebdriverIO was able to resolve the version and download the right Chromedriver. Please provide a reproducible example if possible.

_Originally posted by @christian-bromann in https://github.com/webdriverio/webdriverio/discussions/12329#discussioncomment-8570977_

**Comment by christian-bromann** [comment]
I am not sure if this issue was filed through a bot or real person, anyway it doesn't seem like a legit issue.
