### ISSUE TITLE
Ensuring that Jquery is loaded

### ISSUE THREAD

**Issue by kokujin** [webdriverio/webdriverio#1314]
## The problem

I am using jQuery in an executeAsync() callback, In this callback, I trigger a click, which in turn triggers an AJAX call on my test site. This works well with all browser drivers except phantomjs. I get no errors. Is there some way to ensure that Jquery is loaded soon enough for usage with phantomjs?

* WebdriverIO version: 1.4
* Node.js version: 5.11.1
*  wdio testrunner

**Comment by christian-bromann** [comment]
Yes, just use the waitFor command. Also for such question I would recommend to rather reach out to the WebdriverIO Gitter chat.

**Comment by kokujin** [comment]
None of the "wait..."  commands work in the case I described, is there some other way?

**Comment by christian-bromann** [comment]
Sorry I meant the waitUntil command
