### ISSUE TITLE
Error in call skip() after call custom command

### ISSUE THREAD

**Issue by ando771** [webdriverio/webdriverio#1315]
## The Problem
When I use custom command in my test, call of this.skip() is falling with error:
`the object {
  "message": [undefined]
  "uncaught": true
} was thrown, throw an Error :)
`
## Environment

* WebdriverIO version: 4.0.7
* Node.js version: v5.10.0
* wdio testrunner
* running synchronous:
* Additional wdio packages used: wdio-dot-reporter v0.0.5, wdio-mocha-framework v0.2.13

## Link to Selenium/WebdriverIO logs

https://gist.github.com/ando771/12977a197f61741694572de1a1a32b6f

## Code To Reproduce Issue

```javascript
describe('app', function() {
	before(function (){
		browser.addCommand('someCommand', function () {
			browser.url('http://google.com');
		})
	})

	it('should do something', function(){
		browser.someCommand();
		this.skip(); // throw error
	})
})
```

**Comment by christian-bromann** [comment]
I don't see `this.skip()` being supported in Mocha. Can you send me any documentation around this?

**Comment by ando771** [comment]
Yes, `this.skip()` is not documented, but i found pull request about this: https://github.com/mochajs/mocha/pull/946

Also, I noticed that this error occurs when the `browser` is used to call `this.skip()`, for example:
```JavaScript
it('should do something else', function(){
	browser.url('http://google.com');
	this.skip(); // throw error
})
```

**Comment by christian-bromann** [comment]
mhm .. ok, however I am not sure if this is actually a bug and if we should support this. I believe you can workaround this without needing `this.skip()` to work.

**Comment by kevinmcdonnell** [comment]
+1 for this

We have a situation where the appropriateness to run a test can only be determined inside the test... Imagine that 2 different versions of an app can be served, and it is not known which prior to the test. Previously we could have checked for this and just called `done` in this scenario.

Is there an alternative way to abort a test run inside a `beforeEach` / `describe` / `it` block?

**Comment by christian-bromann** [comment]
@kevinmcdonnell you can just call `return` instead of `done`. Even though your test will be marked to be passed instead of pending but it will still be the same result.

**Comment by kevinmcdonnell** [comment]
That will work but will involve a lot of repetition of code and does not really scale. Ideally I would move this out to a function or custom command

I found that the following works:
```
it('test', function () {
    this.runnable().skip();
});
```

but if used after wdio command it doesn't.
```
it('test', function () {
    var facade = browser.execute(function(){return window.myVar;})
    this.runnable().skip();
```

error:
```
the object {
  "message": [undefined]
  "uncaught": true
} was thrown, throw an Error :)
running chrome
Error: the object {
  "message": [undefined]
  "uncaught": true
} was thrown, throw an Error :)
    at Runner.fail (/srv/api/author/node_modules/mocha/lib/runner.js:226:11)
    at Runner.uncaught (/srv/api/author/node_modules/mocha/lib/runner.js:695:8)
    at process.uncaught (/srv/api/author/node_modules/mocha/lib/runner.js:778:10)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:224:26)
```

I also tried creating a copy of this but to no avail: `copy.runnable is not a function`

```
   it('should return false when getting widget in item edit view', function (done) {

        // this.runnable().skip();

        var copy = Object.assign({}, this);

        var result = browser.execute(function () {
            return window.authorApp.getWidget();
        });
        expect(result.value).to.equal(false);

        copy.runnable().skip();
    });
```

**Comment by christian-bromann** [comment]
Why not doing this:
```js
it('should do something', function() {
    var result = browser.execute(function () {
        return window.authorApp.getWidget();
    });

    if (result.value === 'XXX') return;

    // continue with test if result has different value
});
```

I don't see a difference of calling `this.skip()` and `return`.

**Comment by kevinmcdonnell** [comment]
yeah could but I have 15 tests to handle like this

if we supported `this.skip()` I could call this in the `beforeEach` or a `customCommand`

**Comment by christian-bromann** [comment]
Gotcha, the thing is that we execute these Mocha tests in the Mocha context meaning that it should be supported. So I am wondering if this is supported why isn't it documented in Mocha?

**Comment by kevinmcdonnell** [comment]
it seems to work via `this.runnable().skip();` but not after using wdio commands which seems strange.  

I am going to move the check logic to a custom command so i just need to repeat a sigle  check on the value returned in each test

Yeah I'm not sure, there are lots of mocha issues/discussions around `this.skip()` its been around since v2.2.0 maybe they just failed to document https://github.com/mochajs/mocha/pull/946

**Comment by lhdomenech** [comment]
It is documented in [Mocha](http://mochajs.org/#inclusive-tests), with the following example:
```
before(function() {
  if (/* check test environment */) {
    // setup code
  } else {
    this.skip();
  }
});
```

**Comment by mullanaphy** [comment]
Similar issue. When calling `this.skip()` I get an error `Cannot read property 'split' of undefined`.

The difference between `this.skip()` and just doing a `return;` is the skip will let my test know that it was Pending and not just Passing. Using webdriverajax with a timeout but if an ajax takes too long I would want my tests to return Pending instead of Passing.

**Comment by christian-bromann** [comment]
`this.skip()` is available with MochaJS v3 which is was not supported with the the wdio framework adapter. Please update your `wdio-mocha-framework` package to `v0.5.0`.
