### ISSUE TITLE
Mobile Automation Sample Project using WebdriverIO

### ISSUE THREAD

**Issue by mgthor** [webdriverio/webdriverio#1316]
I am searching for sample project for mobile automation using webdriverio. I have put request on the gitter chat also but no one responded. Opening this request now.

Thanks!!

**Comment by christian-bromann** [comment]
You mean an open source project that uses WebdriverIO for their mobile automation?

**Comment by msneiQA** [comment]
Yes

**Comment by jankcat** [comment]
This is an old issue, but there are quite a few [examples](https://github.com/webdriverio/webdriverio/tree/master/examples) already provided:
Native app with webview: https://github.com/webdriverio/webdriverio/blob/master/examples/appium/appium-draws-its-logo.js
Simple "boilerplate" for native apps: https://github.com/webdriverio/webdriverio/blob/master/examples/standalone/webdriverio.with.appium.nativeapp.js

**Comment by dguzmanSM** [comment]
Hey Cris, so what will be done here, just more documentation? I have a project example that will be publish in github, that could be use as another example using cucumber,  WDIO Testrunner, saucelabs,  if thats helps to have more working examples.

**Comment by christian-bromann** [comment]
@dguzmanSM maybe we add an example to the [wdio examples](https://github.com/webdriverio/webdriverio/tree/master/examples/wdio) which a config that uses the appium service and tests an app that is somewhere publicly accessible.

@mgthor can you elaborate what you would think could be in your interest?

**Comment by sumeetp4** [comment]
Any update on this will be helpful. Thanks!

**Comment by dguzmanSM** [comment]
@sumeetp4 if you provide a public app to test I publish an example:)

**Comment by sumeetp4** [comment]
Hey @dguzmanSM if you take an example of Calculator app in Android and perform some basic operations like swipe, tap, click, sendkeys and different ways to identify elements.

**Comment by christian-bromann** [comment]
Had a chat with @wswebcreation about this. He is gonna tackle it.

**Comment by wswebcreation** [comment]
True

Can be closed now?

**Comment by fergadipa** [comment]
> @sumeetp4 if you provide a public app to test I publish an example:)

Hi @dguzmanSM , have you published the example? I also need it, because so far I only able to open the native app, I also need other functionalities. Very appreciate for your example

**Comment by wswebcreation** [comment]
@fergadipa 

You can find more info at https://github.com/webdriverio/appium-boilerplate, also regarding a testapp
