### ISSUE TITLE
[🐛 Bug]: Can't run test and stuck on wdio run

### ISSUE THREAD

**Issue by Iwonk** [webdriverio/webdriverio#13181]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.16.15

### Node.js Version

20.9.0

### Mode

Standalone Mode

### What happened?

I can't run test and stuck on wdio run
<img width="450" alt="Screenshot 2024-07-19 at 08 25 58" src="https://github.com/user-attachments/assets/70244887-3dd3-4c3f-a1f3-36cb463dfd06">

### How to reproduce the bug.

Run any spec test and stuck on wdio run

### Relevant log output

```typescript
ilhamnuswantoro@Ilhams-MacBook-Air ayo-toko-1 % npm run login

> ayo-toko-mocha@1.0.0 login
> wdio run ./wdio.conf.ts --suite login

^^just stuck there for 30+ minutes
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by Iwonk** [comment]
I've experienced on this issue couple months ago but it tooks only several minutes to run normally, now it's stuck more than 30 minutes. Any advice?

**Comment by christian-bromann** [comment]
@Iwonk thanks for raising this issue. This is a very odd behavior and I've never experienced this. Unfortunately it is impossible to make any guesses without a reproducible example. Mind providing one?

**Comment by Iwonk** [comment]
The problem is now solved
