### ISSUE TITLE
 Error('Unrecognised test [' + title + '] for suite [' + runner.parent + ']');

### ISSUE THREAD

**Issue by kgish** [webdriverio/webdriverio#1318]
## The problem

Tried using `it-each` package but causes wdio to generate error and abort.

## Environment

* webdriverio 4.0.7
* node 0.12.7
* wdio testrunner, running synchronous
* wdio-mocha-framework 0.2.13

## Details

```
/node_modules/webdriverio/build/lib/utils/ReporterStats.js:292
 Error('Unrecognised test [' + title + '] for suite [' + runner.parent + ']');
```

## Link to Selenium/WebdriverIO logs

N/A

## Code To Reproduce Issue

```javascript
var items = [{id: 1, name: 'one'}, {id: 2, name: 'two'}, ...];
it.each(items, 'Item "%s" is ok', ['name'], function (item) {
    assert.ok(item.id, 'Item id is ok');
    assert.ok(item.name, 'Item name is ok');
    console.log(JSON.stringify(module));
});
```

**Comment by christian-bromann** [comment]
> it.each(items, 'Item "%s" is ok', ['name'], function (item) {
>     assert.ok(item.id, 'Item id is ok');
>     assert.ok(item.name, 'Item name is ok');
>     console.log(JSON.stringify(module));
> });

`it.each` is not supported yet in the wdio mocha framework. I can't find it documented on the official mocha page either. Can you create a feature request in the wdio-mocha-framework page and reference to the documentation around this feature?

Thanks!

**Comment by christian-bromann** [comment]
As a workaround you can also just create a forEach loop.

**Comment by kgish** [comment]
That's the whole problem, when I use a `forEach` with `it()` they are not called, how can I run tests on an array?

**Comment by christian-bromann** [comment]
have you tried a simple for loop?
