### ISSUE TITLE
--suite CLI-parameter does not work

### ISSUE THREAD

**Issue by tiefenauer** [webdriverio/webdriverio#1320]
## The problem

the `--suite` CLI argument does not seem to work: running `./node_modules/webdriverio/bin/wdio --specs ./test/specs/pages/index.js` executes all tests in `./test/spec/**/*` (as defined in `wdio.conf.js`)  and not just the tests in `./test/spec/pages/index.js`. 

## Environment

* WebdriverIO version: 4.0.7
* Node.js version: 4.2.2
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
* if wdio testrunner, running synchronous or asynchronous tests: asynchronous
* Additional wdio packages used (if applicable): none

## Details

see description

## Link to Selenium/WebdriverIO logs

--
## Code To Reproduce Issue [ Good To Have ]

--

**Comment by tiefenauer** [comment]
I just found out that `--suite` does not refer to a file/pattern (like the `spec`-property does in the `wdio.conf.js`), but to a suite defined in `wdio.conf.js`.

Source: http://webdriver.io/guide/testrunner/organizesuite.html

However, I really think this should be a bit better described better in the console help...

**Comment by faelperetta** [comment]
I'm facing the same problem on  webdriverio 3.4

**Comment by christian-bromann** [comment]
this is only supported in latest webdriverio version
