### ISSUE TITLE
[🐛 Bug]: new selector logic doesn't take iframe switches into consideration

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#13218]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v9

### Node.js Version

latest

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
any
```

### What happened?

With the improvements to our locator implementation, we have experienced issues when trying to find elements within an iframe.

### What is your expected behavior?

all tests should pass.

### How to reproduce the bug.

see breaking tests

### Relevant log output

```typescript
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by danielhjacobs** [comment]
I tried to work around this by switching to this for what previously used a string selector:

```ts
        await browser
            .$(() =>
                document
                    .querySelector("#test-frame")
                    .contentDocument.body.querySelector("ruffle-object"),
            )
```
It worked for that, but `getHTML` isn't working on an element searched by function:

```ts
        const actual = await browser
            .$(() =>
                document
                    .querySelector("#test-frame")
                    .contentDocument.body.querySelector("#test-container"),
            )
            .getHTML({ includeSelectorTag: false, pierceShadowRoot: false });
```
```
$3 is not a function
```

**Comment by danielhjacobs** [comment]
Apparently $3 is not a function because it is
```json
{
  error: {
    message: 'TypeError: element is null',
    columnNumber: 2,
    exception: { type: 'error' },
    lineNumber: 1,
    stackTrace: { callFrames: [Array] }
  }
}
```
That's returned by `await basicGetHTML(this.elementId, includeSelectorTag)`. It seems that it's another bug as the element exists, its lookup in `getHTML` just fails.

**Comment by danielhjacobs** [comment]
In case it helps others, I found a way to work around this, but I really hate how complicated the workaround is, so we may just wait for this to be fixed:

**Old:**
```ts
        await browser.switchToFrame(await browser.$("#test-frame"));
        await browser.$("ruffle-object").waitForExist();
```
**New:**
```ts
        await browser
            .$(
                () =>
                    (
                        document.querySelector(
                            "#test-frame",
                        ) as HTMLIFrameElement
                    ).contentDocument?.body.querySelector(
                        "ruffle-object",
                    ) as HTMLElement,
            )
            .waitForExist();
```

**Old:**
```ts
        await browser.switchToFrame(await browser.$("#test-frame"));
        const actual = await browser.$("#test-container").getHTML({ includeSelectorTag: false, pierceShadowRoot: false });
```
**New:**
```ts
        const actual = await browser.execute(() => {
            const el = (
                document.querySelector("#test-frame") as HTMLIFrameElement
            ).contentDocument?.body.querySelector("#test-container");
            return el?.innerHTML;
        });
```

**Comment by sschoorens** [comment]
Hi, is there any news about a bug fix release for this issue ? It's a big breaking issue for us.

**Comment by danielhjacobs** [comment]
Any idea how or when this might be fixed? It's the blocker for us merging https://github.com/ruffle-rs/ruffle/pull/17539 (the only blocker since https://github.com/webdriverio/webdriverio/pull/13470 was fixed), and it would be nice to merge that PR to resolve the ws vulnerability even though it doesn't affect us. It would also just be nice to be on webdriverio v9 in general. We can work around it, but we generally considered the code for the workaround, https://github.com/ruffle-rs/ruffle/pull/17539/commits/21714052f18985b49f491987aa251e4c70b162be, a bit too hacky to actually merge.

**Comment by lararojasmr** [comment]
@christian-bromann any news on this?

**Comment by christian-bromann** [comment]
@lararojasmr nope, I have been out for 3 weeks. Any contributions are appreciated as always.
