### ISSUE TITLE
[🐛 Bug]: the string "The test library was called with unknown functions! Error: waitAsync is already running and cannot be called again at this moment"

### ISSUE THREAD

**Issue by alvinisabboy** [webdriverio/webdriverio#13221]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.38.0

### Node.js Version

v20.15.0

### Mode

WDIO Testrunner

### What happened?

Our WDI5 test case can be execute from local to access the remote system such as ACC environment and VAL environment without any issue. But when it runs by pipeline on these environments, the error occurs occasionally, indicating:  **_the string "The test library was called with unknown functions! Error: waitAsync is already running and cannot be called again at this moment" was thrown, throw an Error_**.  {{Error: the string "The test library was called with unknown functions! Error: waitAsync is already running and cannot be called again at this moment" was thrown, throw an Error 
at thrown2Error (/home/jenkins/agent/workspace/WDIO/VAL-on/node_modules/mocha/lib/runner.js:1241:10)
at Runner.fail (/home/jenkins/agent/workspace/WDIO/VAL-on/node_modules/mocha/lib/runner.js:443:11)
at /home/jenkins/agent/workspace/WDIO/VAL-on/node_modules/mocha/lib/runner.js:814:18
at done (/home/jenkins/agent/workspace/WDIO/VAL-on/node_modules/mocha/lib/runnable.js:310:5)
at /home/jenkins/agent/workspace/WDIO/VAL-on/node_modules/mocha/lib/runnable.js:377:11
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)}}   

### What is your expected behavior?

We except the the test cases run successfully.

### How to reproduce the bug.

The issue can not be reproduced every time but it happens occasionally. 
Our test code can be found in : https://github.tools.sap/epd-specification/specmgmt/blob/main/app/ui-maintainspecification/webapp/test/wdi5/specs/Specification_Multirow_properties.spec.js
The error log in pipeline can't be access it, it's overdue. But we can check the latest runs from https://epdspecification.jaas-gcp.cloud.sap.corp/job/WDIO/ to see more detail when the issue happen. 

### Relevant log output

```typescript
Error message is:
the string "The test library was called with unknown functions! Error: waitAsync is already running and cannot be called again at this moment" was thrown, throw an Error 
{{Error: the string "The test library was called with unknown functions! Error: waitAsync is already running and cannot be called again at this moment" was thrown, throw an Error 
at thrown2Error (/home/jenkins/agent/workspace/WDIO/VAL-on/node_modules/mocha/lib/runner.js:1241:10)
at Runner.fail (/home/jenkins/agent/workspace/WDIO/VAL-on/node_modules/mocha/lib/runner.js:443:11)
at /home/jenkins/agent/workspace/WDIO/VAL-on/node_modules/mocha/lib/runner.js:814:18
at done (/home/jenkins/agent/workspace/WDIO/VAL-on/node_modules/mocha/lib/runnable.js:310:5)
at /home/jenkins/agent/workspace/WDIO/VAL-on/node_modules/mocha/lib/runnable.js:377:11
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)}}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
This sounds like a race condition to me. Maybe @vobu knows more about it?

**Comment by vobu** [comment]
i hope i can 👍 
what you're seeing most likely happens when parts of your UI5 app continuously poll an http endpoint. That prevents the UI5 lifecycle to never complete, making the wdi5 test time-out - because wdi5 auto-syncs with the UI5 lifecycle, waiting for the app to complete all asynchronous operations. Which, in turn, doesn't b/c of the long polling. 
**solution**: configure the polled endpoint to be excluded from long-polling in wdi5 via https://ui5-community.github.io/wdi5/#/configuration?id=ignoreautowaiturls
example: https://github.com/ui5-community/wdi5/blob/b144a9549a742d304f573c0272501329cee87286/examples/ui5-js-app/e2e-test-config/wdio-ui5tooling.conf.js#L9

**Comment by vobu** [comment]
ps: hop over to the wdi5 repo to report issues there: https://github.com/ui5-community/wdi5

**Comment by christian-bromann** [comment]
Thanks @vobu for chiming in, I will go ahead and close this.
