### ISSUE TITLE
configuration for webdriverio with phantomjs

### ISSUE THREAD

**Issue by jiayuc** [webdriverio/webdriverio#1323]
If the JavaScript file index.js included in html is written in es6 and it works fine when opening the website locally. However, with webdriverio and phantomjs, the tester can't see all the elements appended by the functions defined in index.js. I saw documents about using Babel, but that's used when the test case itself is written in es6. So what kind of configuration should I do in order for index.js to work when running the tester

**Comment by christian-bromann** [comment]
WebdriverIO gets compiled into ES5 before it gets published. If you run `npm install webdriverio` it will be already compiled. I am not sure what's the issue here but running tests with phantomjs shouldn't be a problem.

**Comment by jiayuc** [comment]
it works when I change browsername to firefox, but not with phantomjs. I also include a small script in my html page to see if it works. Specifically, I simply try to append an div using javascript. when I switch the javascript to es6 format, it doesn't work on phantomjs, but works fine on firefox.

**Comment by christian-bromann** [comment]
Where do you write es6 javascript code? In the browser or within the tests? Also make sure if you call execute and pass in a function that is written in ES6 and compiled using babel, this doesn't work!

**Comment by jiayuc** [comment]
I write es6 javascript code in the browser
```
<script type="text/javascript">
        (function(){
            //'use strict';
            const $map = $('#map');
            $map.append($('<div>').text('test'));
            console.log("get here");
            
        })();
</script> 
```
I tested it with and without use strict: in firefox, both modes works fine; in phantomjs, only without use strict works

**Comment by christian-bromann** [comment]
Well in this case PhantomJS can't interpret ES6 code then.
