### ISSUE TITLE
[🐛 Bug]: If Edgedriver doesn't exist for installed Edge browser but a different Edgedriver is already installed, don't fail

### ISSUE THREAD

**Issue by danielhjacobs** [webdriverio/webdriverio#13251]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.39.1

### Node.js Version

22

### Mode

Standalone Mode

### What happened?

https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#browsers-and-drivers had Microsoft Edge 126.0.2592.113 installed and Microsoft Edge WebDriver 126.0.2592.102 installed. At the time, https://msedgedriver.azureedge.net/126.0.2592.113/edgedriver_linux64.zip did not exist. The job https://github.com/ruffle-rs/ruffle/actions/runs/10068053329/job/27832705746 said "Detected Microsoft Edge v126.0.2592.113" and then after "Downloading Edgedriver from https://msedgedriver.azureedge.net/126.0.2592.113/edgedriver_linux64.zip" said "Error: End of central directory not found".

That Linux build does now exist, but let's imagine a different scenario. https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/ has 127.0.2651.74 as the newest Edge version. However, https://msedgedriver.azureedge.net/LATEST_RELEASE_127_LINUX is 127.0.2651.72. https://msedgedriver.azureedge.net/127.0.2651.74/edgedriver_linux64.zip is now what https://msedgedriver.azureedge.net/126.0.2592.113/ was then.

If the new Ubuntu 22.04 image release has Microsoft Edge 127.0.2651.74 and Microsoft EdgeDriver 127.0.2651.72, which at this point is likely, the same problem will re-occur.

**Edit:** In fact, that's exactly the Edge and Edgedriver versions in https://github.com/actions/runner-images/pull/10376

### What is your expected behavior?

If an Edgedriver doesn't exist for the installed Edge browser, instead of failing when the corresponding Edgedriver version does not exist, if a different Edgedriver is already installed, just use that.

### How to reproduce the bug.

I'll try to add this later. For now, I'll note it should work with any wdio script that runs on Edge when using a system that has an Edge version without a corresponding EdgeDriver but a different EdgeDriver version is installed.

### Relevant log output

```typescript
2024-07-24T00:03:53.200Z INFO edgedriver: Detected Microsoft Edge v126.0.2592.113
2024-07-24T00:03:53.201Z INFO edgedriver: Downloading Edgedriver from https://msedgedriver.azureedge.net/126.0.2592.113/edgedriver_linux64.zip
2024-07-24T00:03:53.423Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: End of central directory not found
    at ZipReader.getEntriesGenerator (file:///home/runner/work/ruffle/ruffle/web/node_modules/@zip.js/zip.js/lib/core/zip-reader.js:160:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ZipReader.getEntries (file:///home/runner/work/ruffle/ruffle/web/node_modules/@zip.js/zip.js/lib/core/zip-reader.js:324:20)
    at async downloadZip (file:///home/runner/work/ruffle/ruffle/web/node_modules/edgedriver/src/install.ts:164:23)
    at async download (file:///home/runner/work/ruffle/ruffle/web/node_modules/edgedriver/src/install.ts:53:3)
    at async file:///home/runner/work/ruffle/ruffle/web/node_modules/@wdio/cli/build/utils.js:42:17
    at async Promise.all (index 1)
    at async Launcher.run (file:///home/runner/work/ruffle/ruffle/web/node_modules/@wdio/cli/build/launcher.js:93:13)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by danielhjacobs** [comment]
Corresponding runner-images bug: https://github.com/actions/runner-images/issues/10336

Corresponding EdgeDriver bug: https://github.com/MicrosoftEdge/EdgeWebDriver/issues/156

**Comment by danielhjacobs** [comment]
I assume the way to do this would be to put this in a try and then in a catch return the currently installed EdgeDriver if one exists. But I don't know how to get that with wdio:

https://github.com/webdriverio/webdriverio/blob/d1ba15487fd270f935d80b172230456662703f94/packages/wdio-utils/src/node/utils.ts#L324

**Comment by christian-bromann** [comment]
Let's close this in favor of https://github.com/webdriverio-community/node-edgedriver/issues/365
