### ISSUE TITLE
Selenium session dies when large number of elements returned from getAttribute

### ISSUE THREAD

**Issue by kunwardeep** [webdriverio/webdriverio#1326]
So the issue is same as 
https://github.com/webdriverio/webdriverio/issues/859

I used this code -
```
return client.elements('a').then(function(res) {                                                                                                                                                
  var promises = res.value.map(function(element) {
    return client.elementIdAttribute(element.ELEMENT, 'href');                                                                                                                              
  });
  return Q.allSettled(promises);
});
```

on the page http://www.seek.com.au/sitemap-industry. But selenium crashes. The only way around i found was to use 
```
function getLinksOnCurrentPage(){
  return browser
  .execute(function() {
    var links = []
    var allLinks = document.links;
    for(var i = 0; i < allLinks.length; i++) {
      links.push(allLinks[i].href);
    }
    return links;
  })
.then(function(links){
    return links.value;
  });
}

```
Is it something reproducible on your end? And i am using webdriverio 3.4

**Comment by christian-bromann** [comment]
@kunwardeep if you want to get an attribute of multiple elements just call the getAttribute method:

```js
return client.getAttribute('a', 'href');
});
```

If the selector matches multiple elements it will return an array of results automatically.

**Comment by kunwardeep** [comment]
Hey @christian-bromann please try your solution with the page - http://www.seek.com.au/sitemap-industry.... It still crashes webdriver

**Comment by christian-bromann** [comment]
Well in this case it isn't an issue of WebdriverIO and rather one of Selenium. Feel free to propose a PR that times the requests in a way Selenium stops crashing.
