### ISSUE TITLE
console logs in api

### ISSUE THREAD

**Issue by markelog** [webdriverio/webdriverio#1328]
## The problem

There is lots of `console.log`s in `Launcher` module, like so https://github.com/webdriverio/webdriverio/blob/7dff678ecd82e4a26db3931ea892964864b5b74e/lib/launcher.js#L321, which is fine when used from cli, but not ideal when this API used directly, since those logs are side-effects which are in some cases unwanted.

I would suggest to use event system or analogues pattern in which users would decide from themselves what they want to output to the console.log.

On related note, it would be cool to document this.

## Environment

* WebdriverIO version: 4.0.7
* Node.js version: 5.11.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable): none

**Comment by christian-bromann** [comment]
> On related note, it would be cool to document this.

Fixed!

> since those logs are side-effects which are in some cases unwanted.

I don't think it is a good idea to remove these logs. People get confused when they hit ctrl+c and don't see that message. In addition to that I doubt that these logs have any negative side effects.

**Comment by markelog** [comment]
I used this in https://github.com/webdriverio/webdriverio/blob/7dff678ecd82e4a26db3931ea892964864b5b74e/lib/launcher.js#L147 and I have my own messages for this, there they just disturb the flow.

> when they hit ctrl+c 

You supposed to "hit ctrl+c" in cli tool, in cli tool those messages could be very helpful, here they just unwanted side-effects, that is why i suggested to provide some way to communicate these messages between actual API and consumer of that API.

And all and all, messing with separation of concerns like that is just bad design (no offence)

**Comment by christian-bromann** [comment]
> messing with separation of concerns like that

What do you mean?

**Comment by markelog** [comment]
Let's look at [`exitHandler`](https://github.com/webdriverio/webdriverio/blob/7dff678ecd82e4a26db3931ea892964864b5b74e/lib/launcher.js#L319) method for example, it's achieving two things:
First: 

> Make sure all started selenium sessions get closed properly and prevent
having dead driver processes. To do so let the runner end its Selenium
session first before killing

But it also sends message to console. 

So it does two things instead of one, instead of doing only what was promised, it's [doing more](https://en.wikipedia.org/wiki/Side_effect_(computer_science)) that was ask from it.

Which makes `launcher` module less [cohesive](https://en.wikipedia.org/wiki/Cohesion_(computer_science)). 

It's like combining V and C in MVC paradigm. 

So in
```js
var wdio = new Launcher(opts.configFile, opts);
wdio.run().then(function (code) {
 process.exit(code);
}, function (error) {

 // Like if you wouldn't trust user to make that call 
 console.error('Launcher failed to start the test', error.stacktrace);
 process.exit(1);
});
```

Like in my module [gulp-wdio](https://github.com/markelog/gulp) (which uses this API), I have [`browserstack`](https://github.com/markelog/gulp-wdio/blob/9e7840d97fd4a65f5825d8d6e7e9841e872a654c/src/transports/browserstack.js#L30) transport.

I could have put `console.logs` in that class too, but instead I only provide [access](https://github.com/markelog/gulp-wdio/blob/9e7840d97fd4a65f5825d8d6e7e9841e872a654c/src/index.js#L40-L44) for this information to the consumer, cause only consumer can decide what their want to do with it – https://github.com/markelog/gulp-wdio/blob/master/src/index.js#L40-L44.

So instead of hardcoding this, you could do something like this –
```js
var wdio = new Launcher(opts.configFile, opts);

wdio.disableMessages(); // by default it's enabled or it could be in the `opts.configFile` object
....
```
