### ISSUE TITLE
CSS pseudo-class :not() apparently not supported

### ISSUE THREAD

**Issue by marceln** [webdriverio/webdriverio#1330]
## The problem

I'm trying to locate a set of elements with a CSS selector, which looks like this:
```javascript
export default class MenuBar {
    constructor() {
        this.selector = '#itm-content-tab-bar li:not(.dxtc-spacer)';
        this.menuBarItems = browser.execute(this.selector).value;
    }
...
```

However, the output from the testrunner is:
> unknown error: Runtime.evaluate threw exception: SyntaxError: Unexpected token ILLEGAL
>     at Object.InjectedScript._evaluateOn (<anonymous>:145:167)
>     at Object.InjectedScript._evaluateAndWrap (<anonymous>:137:25)
>     at Object.InjectedScript.evaluate (<anonymous>:118:14)

Is this selector not supported or is anything else going on?
I should mention that if I run 
```javascript
$$('#itm-content-tab-bar li:not(.dxtc-spacer)')
```
in the Chrome console then it works fine. 

## Environment

* WebdriverIO version:v4.0.7
* Node.js version: v5.9.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): none

## Details
wdio log:
![image](https://cloud.githubusercontent.com/assets/964586/15501024/086694f8-21b4-11e6-8dd8-76686e63cbde.png)

Selenium logs:
![image](https://cloud.githubusercontent.com/assets/964586/15501039/1d767e44-21b4-11e6-9503-bcfd5a262c08.png)

![image](https://cloud.githubusercontent.com/assets/964586/15501030/0f6eb5dc-21b4-11e6-88cd-1055ef290588.png)

## Code To Reproduce Issue [ Good To Have ]

None yet.

**Comment by christian-bromann** [comment]
Sorry but this is a Selenium issue and I don't see an easy way to build a workaround in WebdriverIO. Please use a different locator strategy (maybe xpath is working for you). Try to right click on the desired element in your devtools and click on `Copy xPath Selector` and use that selector for querying the element with WebdriverIO.

**Comment by marceln** [comment]
Hi Christian,

I actually checked the same selector webdriverjs and it does work. So it cannot be a Selenium issue. 
It's not that I'm trying now to find alternatives to this selector, because I know there are plenty. I'm just testing various test automation solutions.

This is the test I've used to check this:
```javascript
var webdriver = require('selenium-webdriver'),
    By = webdriver.By,
    until = webdriver.until;

var driver = new webdriver.Builder()
    .forBrowser('chrome')
    .usingServer('http://localhost:4444/wd/hub')
    .build();

driver.get('https://www.reddit.com/');
driver.findElement(By.className('tabmenu'));
driver.findElements(By.css('ul.tabmenu li:not(.selected)')).then(function (res) { console.log(res.length) });
driver.quit();
```

What do you think it is?

Thanks,
Marcel

**Comment by christian-bromann** [comment]
Sorry I haven't seen the WebdriverIO code? Why do you want to call `execute` on a selector? Please check out the [API](http://webdriver.io/api.html) to find out more about WebdriverIO commands. If you want to get the text of the tabmenus you can do:

standalone version:
```js
client.getText("ul.tabmenu li:not(.selected)").then(function(text) {
    console.log(text);
});
```
wdio version:
```js
it("should get me unselected tab menus", function() {
    console.log(browser.getText("ul.tabmenu li:not(.selected)"));
});
```

**Comment by marceln** [comment]
Christian,

OK, thanks! I have read your API documentation and while most of it is clear, I'm just confused that 
some of the commands, like getText(), work with certain selectors, while others like click() do not. 

I'm sure you have a good reason to do so, but it's not clear when I can use all CSS selectors and when I cannot. 

Thanks,
Marcel

**Comment by christian-bromann** [comment]
@marceln you can use css selectors for each command but protocol commands, here an json web element id is required. Usually you don't need to use protocol commands.

**Comment by marceln** [comment]
OK Christian, I think I get it now. 

I also see the confusion with my initial code. It should have been browser.elements instead of browser.execute. 

Thanks, all clear now.
