### ISSUE TITLE
Pass offsetX, offsetY into left/middle/rightclick

### ISSUE THREAD

**Issue by isnifer** [webdriverio/webdriverio#1331]
## The problem
Hey, folks!

I'm working on tests for timepicker on my project. I selected [Material UI TimePicker](http://www.material-ui.com/#/components/time-picker). I've found that click on hours or minutes is not on an element, but on the mask layer above.

I tried to click on the mask with offset through 

```javascript
.moveTo(selector, offsetX, offsetY).leftClick()
```

or

```javascript
this.browser.moveTo(selector, offsetX, offsetY)
this.browser.leftClick()
```
but nothing works

I suggest to add offsetX, offsetY to left/middle/right-click methods, because it simply works. I've forked webdriverio and push changes https://github.com/isnifer/webdriverio/commit/ae8e5af3d71535f552fd6b20d14b2e980ffbc3b8

What do you think?

## Environment

* WebdriverIO version: >=3.4.0
* Node.js version: 6.1.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Standalone
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

**Comment by christian-bromann** [comment]
Could you please open a PR? The change looks reasonable and I would be happy to merge it. Thanks
