### ISSUE TITLE
[🐛 Bug]: ChromeDriver connection fails when using VPN due to default hostname (0.0.0.0)

### ISSUE THREAD

**Issue by DIFSRIP** [webdriverio/webdriverio#13329]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

LTS

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
  browserName: 'chrome'
}
```

### What happened?

When using WebdriverIO behind a VPN connection, the session could not be created and leads to the following error:
`Error: Failed to create session. read ENOTCONN at startWebDriverSession`

### What is your expected behavior?

The connection should be established reliably even when a VPN is used. Changing the default hostname to 127.0.0.1 ensures that the connection can be made successfully under these conditions.

Issue should be fixed with: https://github.com/webdriverio/webdriverio/pull/13328

### How to reproduce the bug.

- Set up WebdriverIO for chrome using mocha runner.
- Connect to a VPN (GlobalProtect).
- Attempt to start a WebDriver session with the default hostname.
- Observe the connection failure.

### Relevant log output

```typescript
[0-0] 2024-08-06T07:23:12.501Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] read ENOTCONN
[0-0]     at startWebDriverSession
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by DIFSRIP** [comment]
PR with fix: https://github.com/webdriverio/webdriverio/pull/13328

**Comment by christian-bromann** [comment]
Thanks for providing a PR with a fix. I will go ahead and close this one.
