### ISSUE TITLE
waitUntil called multiple times, however promise is returned

### ISSUE THREAD

**Issue by slavafomin** [webdriverio/webdriverio#1333]
Hello!

Thank you for this great library!

However, I've encountered a situation when function passed to the [waitUntil](http://webdriver.io/api/utility/waitUntil.html) is called multiple times, however promise is returned by it.

Shouldn't the library call it only once to get the promise and then wait for promise to resolve?

Thanks!

---

# Example:

```js
client
  .init()
  .url('http://www.example.com')
  .saveScreenshot(SCREENSHOT_PATH)
  .waitUntil(function () {
    return easyimg.info(SCREENSHOT_PATH).then(function (image) {
      console.log(image);
    });
  })
  .end()
;
```

**Comment by christian-bromann** [comment]
No, it is meant to be a helper utility to wait for certain conditions using Selenium commands. If you just want to wait until a promise has resolve, do:

```js
client
  .init()
  .url('http://www.example.com')
  .saveScreenshot(SCREENSHOT_PATH)
  .call(function () {
    return easyimg.info(SCREENSHOT_PATH).then(function (image) {
      console.log(image);
    });
  })
  .end();
```
