### ISSUE TITLE
[🐛 Bug]: Multiremote with Selenium Grid

### ISSUE THREAD

**Issue by HassHz** [webdriverio/webdriverio#13337]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.39.0

### Node.js Version

18.19.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  userA: {
    capabilities: {
      hostname: 'company.grid.com'
      port: 4444,
      path: '/',
      protocol: 'http'
      browserName: 'chrome',
      acceptInsecureCerts: true,
      'goog:chromeOptions:': { ...prefs, ...args }
    },
  userB: { ... }
}
```

### What happened?

When passing the above capabilities into `multiremote` like so: `const browser = await multiremote(capabilities)`, the following error appears:
`Error: Invalid or unsupported WebDriver capabilities found ("hostname", "port", "path", "protocol")`

### What is your expected behavior?

The browsers should launch in the selenium grid.

### How to reproduce the bug.

Attempt to create Multiremote instance while specifying `ConnectionOptions` as part of the browsers' capabilities.

### Relevant log output

```typescript
Error: Invalid or unsupported WebDriver capabilities found ("hostname", "port", "path", "protocol"). Ensure to only use valid W3C WebDriver capabilities (see https://w3c.github.io/webdriver/#capabilities).If you run your tests on a remote vendor, like Sauce Labs or BrowserStack, make sure that you put them into vendor specific capabilities, e.g. "sauce:options" or "bstack:options". Please reach out to your vendor support team if you have further questions.
    at startWebDriverSession (file://.../node_modules/webdriver/build/utils.js:36:19)
    at Function.newSession (file://.../node_modules/webdriver/build/index.js:19:51)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at remote (file://.../node_modules/webdriverio/build/index.js:46:22)
    at file://.../node_modules/webdriverio/build/index.js:101:26
    at async Promise.all (index 0)
    at multiremote (file://.../node_modules/webdriverio/build/index.js:100:5)
    at launchPartners (.../launch.js:93:21)
    at Server.<anonymous> (...partnerService.js:32:9)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by srizvi1** [comment]
@HassHz Can you try putting all the grid information outside the capabilities. That resolved this error for me.
