### ISSUE TITLE
setValue

### ISSUE THREAD

**Issue by xhuang26** [webdriverio/webdriverio#1337]
Currently having an input tag with type range, aka a slider. I'm trying to set value for it but getting the error: Element must be user-editable in order to clear it. 
I understand that setValue ask the input value to be cleared first, so is that why it doesn't work when type is range?

Thanks!

**Comment by andyboyne** [comment]
You can use browser.execute(..) to inject some script to set the value
'manually'.

**Comment by christian-bromann** [comment]
@xhuang26 try to use the addValue command here, if this is not working do what @andyboyne is recommending.
