### ISSUE TITLE
[🐛 Bug]: v9: getHTML not backward-compatible

### ISSUE THREAD

**Issue by danielhjacobs** [webdriverio/webdriverio#13378]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v9

### Node.js Version

22

### Mode

Standalone Mode

### What happened?

When using `.getHTML(false)`, I got the error message `error TS2559: Type 'false' has no properties in common with type 'GetHTMLOptions'`.

### What is your expected behavior?

According to https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/element/getHTML.ts#L79-L80, `getHTML` was meant to retain backwards-compatibility. However, the type definition `options: GetHTMLOptions` doesn't allow that. The definition should likely instead be `options: GetHTMLOptions | boolean`.

### How to reproduce the bug.

```js
await browser.$("#example").getHTML(false);
```

### Relevant log output

```typescript
error TS2559: Type 'false' has no properties in common with type 'GetHTMLOptions'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting @danielhjacobs!

I think we missed this in the release notes as it was one of the first features. I will go ahead and mark this as breaking change and recommend to update your types.
