### ISSUE TITLE
Async flow is not working with wdio

### ISSUE THREAD

**Issue by isnifer** [webdriverio/webdriverio#1338]
## The problem
I think async flow is not working with wdio.

## Environment

* WebdriverIO version: **4.0.7**
* Node.js version: **6.1.0**
* [Standalone mode or  testrunner](http://webdriver.io/guide/getstarted/modes.html): **wdio**
* if wdio testrunner, running synchronous or asynchronous tests: **async**
* Additional wdio packages used (if applicable): **wdio-dot-reporter**, **wdio-mocha-framework**

## Details

Yesterday I opened webdriver.io. I found out that tool was updated to v4. 
I started read the docs and of course breaking changes. I understood that now I can run my tests with async flow but in sync way, because wdio testrunner will handle promises itself.
But it doesn't work.

## Link to Selenium/WebdriverIO logs

https://gist.github.com/isnifer/0e2e492df300a274c0df6286f0aac9cc

## Code To Reproduce Issue [ Good To Have ]

```js
describe('webdriver.io page', function() {
    it('should have the right title', function () {
        browser.url('/');
        var title = browser.getTitle();
        assert.equal(title, 'WebdriverIO - Selenium 2.0 javascript bindings for nodejs');
    });
});
```

## wdio.conf.js
```js
exports.config = {
    specs: [
        './test/specs/**/*.js',
    ],
    exclude: [
        // 'path/to/excluded/files'
    ],
    maxInstances: 10,
    capabilities: [{
        maxInstances: 5,
        browserName: 'chrome',
    }],
    sync: false,
    logLevel: 'error',
    coloredLogs: true,
    screenshotPath: './test/errorShots',
    baseUrl: 'http://webdriver.io',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    framework: 'mocha',
    reporters: ['dot'],
    mochaOpts: {
        ui: 'bdd',
        compilers: ['js:babel/register'],
        reporters: ['spec'],
    },
};
```

## screen record
![async_flow](https://cloud.githubusercontent.com/assets/1788245/15534894/c14a7006-2273-11e6-9662-84170a0bb794.gif)

**Comment by christian-bromann** [comment]
If you config says `sync: false` you can't run commands synchronous!

**Comment by isnifer** [comment]
@christian-bromann wait! But example from https://webdriver.io doesn't work with sync and async.
![image](https://cloud.githubusercontent.com/assets/1788245/15565080/9ae22dfc-2320-11e6-9b9e-c46146a61b98.png)
I want to write my tests w/out async/await like before. What should I do?

**Comment by christian-bromann** [comment]
Just remove the sync property in your config and it should work.

**Comment by isnifer** [comment]
I'm sorry, but is there any demo with this feature? 
I'm asking cause it doesn't work again.

**Comment by christian-bromann** [comment]
@isnifer if you have `sync: false` you run your tests in async mode so they all return a promise (something like `{ state: 'pending' }` if you console.log it). If you have `sync: true` then all commands return the result directly (like a synchronous method). You will find more about this in the docs.

**Comment by ankur22008** [comment]
For me sync mode is not working at all and I have to write code using async/await commands. is this really work ?

for example 


I clicked a button to navigate to another page
I need to search an element in next page but my test failed saying element not present ( as page was not laoded)

I am using latest version of node and webdriverIO at the moment .

can someone pls help 

Thanks
