### ISSUE TITLE
[🐛 Bug]: Selecting "Other" as framework results in error

### ISSUE THREAD

**Issue by miyasudokoro** [webdriverio/webdriverio#13419]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

20.10.0

### Mode

WDIO Testrunner

### What happened?

1. Run npm init wdio@latest
2. A project named X was detected at X, correct? **yes**
3. What type of testing would you like to do? **Component or Unit Testing - in the browser**
4. Which framework do you use for building components? **Other**
5. Which framework do you want to use? **Mocha**
6. A bunch of stuff prints out starting with wdio.js config
7. TypeError: answers.preset?.includes is not a function
    at Object.when (file:///C:/path/of/project/redacted/node_modules/@wdio/cli/build/index.js:652:27)

### What is your expected behavior?

I should be able to select "Other" as an option.

### How to reproduce the bug.

See the "What happened?" section. 

Adding a check for whether the type of answers.preset is a string in line 652 fixes the issue. This is because, if you select "Other," answers.preset is `false`, rather than a string.

### Relevant log output

```typescript
TypeError: answers.preset?.includes is not a function
    at Object.when (file:///C:/path/redacted/node_modules/@wdio/cli/build/index.js:652:27)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
A potential fix should be applied in https://github.com/webdriverio/webdriverio/blob/24a5be8ebefe75310ceaa337120d79f95840e64c/packages/wdio-cli/src/constants.ts#L476-L485, any contribution are appreciated. Thanks for reporting.
