### ISSUE TITLE
[🐛 Bug]: WDIO Testrunner V9 removed `capabilities` on `Options.Testrunner`

### ISSUE THREAD

**Issue by Zidious** [webdriverio/webdriverio#13427]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

20

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
NA
```

### What happened?

https://github.com/webdriverio/webdriverio/pull/12987/files#diff-94ae4a4f3aed5a220757c6ff152c8cf410b7798e2e60b303fca642ab9172ec5dL311 removed `capabilities` as part of the `Options.Testrunner` type on the v9 release but still allowed on v8. 

### What is your expected behavior?

Be able to add capabilities as part of WDIO Testrunner configuration as previously allowed on v8 

Docs also show that this is still the case: https://webdriver.io/docs/configurationfile 

### How to reproduce the bug.

Install the local wdio test runner via `npx wdio config` 

### Relevant log output

```typescript
Object literal may only specify known properties, and 'capabilities' does not exist in type 'Testrunner'.ts(2353)
(property) capabilities: {
    browserName: string;
}[]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Please use the `WebdriverIO.Config` type or if you use multiremote `WebdriverIO.MultiremoteConfig`. We are working on providing better docs for our types.

**Comment by DellanX** [comment]
^For those who don't know how to navigate @wdio/types, where can I import the type WebdriverIO.Config from?

**Comment by christian-bromann** [comment]
@DellanX it should be available by default, if not add `@wdio/globals/types` to your `tsconfig.json` types.
