### ISSUE TITLE
[🐛 Bug]: `new`-ing a custom element results in `TypeError: Illegal constructor`

### ISSUE THREAD

**Issue by nolanlawson** [webdriverio/webdriverio#13428]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.0.5

### Node.js Version

20.11.0

### Mode

WDIO Testrunner

### What happened?

Due to the `WdioWrapperElement` wrapping `customElements.define()` [here](https://github.com/webdriverio/webdriverio/blob/8d9e3020217d35e0458f154bb12fec9bc49f2219/packages/webdriverio/src/scripts/customElement.ts#L27), it is not possible to `new` a custom element constructor like so:

```js
class Foo extends HTMLElement {}
customElements.define('x-foo', Foo)
new Foo () // throws
```

This throws an error (in all browsers – Chrome, Firefox, and Safari). Here is the error from Chrome 127:

```
Uncaught TypeError: Illegal constructor
    at new Foo (index.html:5:3)
```

The reason for this is that WebdriverIO has called the underlying `customElements.define()` with its own wrapper constructor. Only this constructor may be `new`-ed – the original `Foo` constructor itself cannot be `new`-ed.

### What is your expected behavior?

I expect the above script to not throw an error. You can try it on a vanilla HTML page ([sample Codepen](https://codepen.io/nolanlawson-the-selector/pen/OJevNYz)) and it will not throw.

For WebdriverIO itself, I would suggest having an option to disable the `WdioWrapperElement` wrapper behavior. It is not a simple task to override the global `customElements` APIs in a non-obtrusive way, without [significant gymnastics](https://github.com/webcomponents/polyfills/tree/master/packages/scoped-custom-element-registry).

### How to reproduce the bug.

Here is [a minimal repro of the issue](https://gist.github.com/nolanlawson/327193c5b3ff62de7fdfe656b8263a48). You can run `npm run wdio` in the project to reproduce the error.

### Relevant log output

```typescript
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks @nolanlawson , I will take a look 🙏
