### ISSUE TITLE
[🐛 Bug]: Only Android does not show appName in wdio-spec-reporter

### ISSUE THREAD

**Issue by waddlaw** [webdriverio/webdriverio#13433]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
**android**

{
  platformName: "Android",
  "appium:automationName": "uiautomator2",
  "appium:appPackage": "com.example.android",
  "appium:appActivity": ".MainActivity"
}

----

**iOS**

{
  platformName: "iOS",
  "appium:automationName": "xcuitest",
  "appium:bundleId": "com.example.ios",
  "appium:udid": "dummy",
  "appium:xcodeOrgId": "dummy",
  "appium:xcodeSigningId": "dummy"
}
```

### What happened?

On iOS, the configured `bundleId` is displayed, but on android, `undefined` is displayed even though `appPackage` is configured.

iOS outputs:

```
...
[com.example.ios iOS #1-0]
[com.example.ios iOS #1-0]
..
```

android outputs:

```
...
[undefined Android #1-0]
[undefined Android #1-0]
...
```

### What is your expected behavior?

The cause is probably that only iOS is being handled here.

https://github.com/webdriverio/webdriverio/blob/9e5beb548b6862b7353b834f8e7294804d10204d/packages/wdio-spec-reporter/src/index.ts#L603C15-L603C22

```ts
const appName = app || caps['appium:bundleId'] || (caps as any).bundleId
```

The following change made it possible to display the values correctly on my environment as well as on iOS.

```ts
const appName = app || caps['appium:bundleId'] || (caps as any).bundleId || caps['appium:appPackage'] || (caps as any).appPackage
```

### How to reproduce the bug.

skip (I will try to prepare it if necessary.)

### Relevant log output

```typescript
iOS outputs:


...
[com.example.ios iOS #1-0]
[com.example.ios iOS #1-0]
..
```

android outputs:

```
...
[undefined Android #1-0]
[undefined Android #1-0]
...
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@waddlaw thanks for reporting! Mind raising a PR with a change?

**Comment by christian-bromann** [comment]
> Mind raising a PR with a change?

Nevermind, I took a quick stab at this myself.

**Comment by waddlaw** [comment]
@christian-bromann thanks!
