### ISSUE TITLE
Keys are not working with webdriverIO 

### ISSUE THREAD

**Issue by kedunuru** [webdriverio/webdriverio#1344]
Keys are not working with webdriverIO ....
I am trying to use keys to simulate command+i 
None of the options are working....
driver.keys(['\uE03D', '\u0049']);
driver.keys(['meta','i']);
## Environment
- WebdriverIO version:
- Node.js version: 4.4.3

when I read in forums, there was a indication that it is an issue with chrome driver, is this resolved or is it still an issue?

Thanks, 
Veni

**Comment by pi4r0n** [comment]
@kedunuru have you tried to use it that way

`
driver.keys('Enter')
driver.keys('F5')
`

**Comment by kedunuru** [comment]
yeah i tried that as well :)

**Comment by christian-bromann** [comment]
This is probably Selenium related.

**Comment by kedunuru** [comment]
I have tried one more time using 
:driver.keys('Enter')
driver.keys('F5')
It does not work

**Comment by pi4r0n** [comment]
@kedunuru can you post you selenium version and sample code please.

**Comment by kurtharriger** [comment]
Keys is working fine for me (4.0.9) with selenium 2.53 and chrome, and several browsers on saucelabs which still uses 2.48.

The following package will install selenium and chrome driver for you. Perhaps you have some version incompatibilities with selenium and chrome driver? 
https://www.npmjs.com/package/selenium-standalone

If that doest work you'll probably need to be more specific about your setup

**Comment by lladrona** [comment]
I have partly the same issue

> selenium-standalone: 5.1.1
> webdriverio: 4.0.9

i've tried
```
driver.keys(['Command', 'A'])
driver.keys(['Control, 'A'])
```
however, simple keys are sent, i. e.
```
driver.keys(['some','word'])
driver.keys('some word')
```

**Comment by christian-bromann** [comment]
@lladrona try Command instead of Control or Meta maybe

**Comment by lladrona** [comment]
@christian-bromann i've tried both command and control, nothing changes
then inspected server logs for `browser.keys(['Command', 'c']);` in chrome and phantomjs
```
12:01:42.611 INFO - Executing: [send keys to active: [, c]])
12:01:42.626 INFO - Done: [send keys to active: [, c]]
```
we have tests written in java, and their SendKeys ends up like 
12:01:42.611 INFO - Executing: [send keys to active: [, ]])
12:01:42.626 INFO - Done: [send keys to active: [, ]]

is this still browser driver issue?

**Comment by monolithed** [comment]
I can confirm the problem. It does not depend on the version of the Selenium or WebDriver.

**Comment by jeffmanhart** [comment]
I am able to use `browser.keys('Enter')` successfully on all browsers except using safaridriver.  This I believe to be a safaridriver issue but figured I would mention it here as well.
Err message is -
 Failed: Unknown command: {"id":"eh7bqx6syufe","name":"sendKeysToActiveElement","parameters":{"value":[""]}} (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 4 milliseconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
os.version: '10.10.5', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=9.1.1, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}]
Session ID: null

**Comment by timbru31** [comment]
@jeffmanhart AFAIK Safari does not support `browser.keys` yet: https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/4136

**Comment by monolithed** [comment]
Also, there's a bug with text data:

```
browser.keys('my some text') // mysometext
```

**Comment by bekite** [comment]
chrome driver: 2.21.2
webdriverio: 4.0.4

I had issues sending key combinations with modifiers, too. 
In the docs at http://webdriver.io/api/protocol/keys.html I found out, that the modifiers (Control, Shift, Alt) are not released by default. You have to pass 'NULL' to release the modifier key.

`browser.keys(['Control', 'r', 'NULL'])`

Another gotcha I had, was that the character type keys on https://w3c.github.io/webdriver/webdriver-spec.html#h-keyboard-actions (which was linked in the docs), are not identical to those that webdriverio is using. They have to match exactly in case to work.
The character type keys which webdriverio is using can be found  here: https://github.com/webdriverio/webdriverio/blob/master/lib/helpers/constants.js#L67

And update to the docs and maybe an example on how to use key combinations with modifiers would be helpful.

**Comment by christian-bromann** [comment]
> are not identical to those that webdriverio is using

@bekite this got updated

**Comment by christian-bromann** [comment]
... and released. If some keys aren't working in some browser is probably an issue of the driver. Closing.

**Comment by gogoyqj** [comment]
seems firefox webdriver doesn't support this api

**Comment by christian-bromann** [comment]
@gogoyqj you are right

**Comment by nvega-ms** [comment]
Did you find the way to press tab on Firefox? Thanks

**Comment by pmerwin** [comment]
Any updates on ff driver having a fix?

**Comment by christian-bromann** [comment]
It won't as this command is not part of the WebDriver protocol

**Comment by pmerwin** [comment]
@christian-bromann I see that is deprecated, what command will replace 'keys'?

**Comment by christian-bromann** [comment]
Keyboard actions: https://www.w3.org/TR/webdriver/#keyboard-actions

**Comment by rsshilli** [comment]
So... how do we use those "Keyboard Actions" from webdriver.io?  The keys() method doesn't seem to use that and I don't see any other options.

**Comment by rsshilli** [comment]
Nevermind.  I found it: https://stackoverflow.com/questions/44339046/browser-keys-is-not-working-on-firefox-53-0-webdriver-io

**Comment by fogrizovic** [comment]
Hi all, 
Just wanted to share a custom command that i´m using as an alternative to browser.keys() which works with Chrome and Internet Explorer. I have taken some information from [this post](https://stackoverflow.com/questions/44339046/browser-keys-is-not-working-on-firefox-53-0-webdriver-io)  

browser.addCommand("keys_", function (keys) {
        var result = browser.elementActive()
        if (result.value) {
            var activeElement = (browserName == 'internet explorer') ? Object.values(result.value)[0] : result.value.ELEMENT
            browser.elementIdValue(activeElement, keys)
        }
    })

**Comment by chandanrayarm** [comment]
Hi there I'm trying to work Option+Command+m key to work but its not working can someone help me here  as client.keys(['Shift','Command', 'W']);
