### ISSUE TITLE
[🐛 Bug]: Memory leak in execution and warning running mpm install 

### ISSUE THREAD

**Issue by carri747** [webdriverio/webdriverio#13456]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.40.3

### Node.js Version

18.15.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
Windows 10, 

    {
        browserName: 'chrome',
        browserVersion: '127.0.6533.99',
        'goog:chromeOptions': {
            args: [
                '--headless=new',
                '--disable-infobars',
                '--no-sandbox',
                '--disable-gpu',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage',
                '--window-size=1920,1080',
                `--user-agent=${userAgent}`,
                '--remote-allow-origins=*'
            ],
            prefs: { ['profile.default_content_setting_values.images']: 2 }
        }
    }
```

### What happened?

Hello again and many thanks in advance.

I've a project with more than 500 scenarios, splitted by features and in the most of the execution I've a memory leak. Initially my node is setup to use only 4G but I increased to double and I continue with the memory leak.
When I remove or I create a new WDIO project and I run "npm i" I can see this warning

![image](https://github.com/user-attachments/assets/0734a7df-564d-43fc-b7bf-c1e2d381e0c6)

I know that there is a WARN but maybe it's related with the memory leak that I've in my project 

Those are the dependencies that the previous library has in the project 

├─┬ @wdio/cucumber-framework@8.40.2
│ └─┬ @cucumber/cucumber@9.5.1
│   └─┬ glob@7.2.3
│     └── inflight@1.0.6 deduped
├─┬ @wdio/devtools-service@8.40.2 overridden
│ ├─┬ babel-plugin-istanbul@7.0.0
│ │ └─┬ test-exclude@6.0.0
│ │   └─┬ glob@7.2.3
│ │     └── inflight@1.0.6 deduped
│ └─┬ lighthouse@9.6.8 overridden
│   └─┬ puppeteer-core@13.7.0
│     └─┬ rimraf@3.0.2
│       └─┬ glob@7.2.3
│         └── inflight@1.0.6 deduped
├─┬ @wdio/local-runner@8.40.2
│ └─┬ @wdio/runner@8.40.2
│   └─┬ gaze@1.1.3
│     └─┬ globule@1.3.4
│       └─┬ glob@7.1.7
│         └── inflight@1.0.6 deduped
├─┬ allure-cucumberjs@2.4.0
│ └─┬ @cucumber/cucumber@8.11.1
│   └─┬ glob@7.2.3
│     └── inflight@1.0.6 deduped
├─┬ copyfiles@2.4.1
│ └─┬ glob@7.2.3
│   └── inflight@1.0.6
└─┬ read-excel-file@5.6.1
  └─┬ unzipper@0.10.14
    └─┬ fstream@1.0.12
      └─┬ rimraf@2.7.1
        └─┬ glob@7.2.3
          └── inflight@1.0.6 deduped

And I found this bug 

https://github.com/sveltejs/kit/issues/12258

I need help because I don't know if this bug is related with me memory leak or not and I don't know how to fix the issue with the memory leak that I've

Many thanks

### How to reproduce the bug.

Create a new project in wdio (version 8 or 9) and execute a "npm install". Check the warning.

### Relevant log output

```typescript
see the image in description
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
NPM warnings aren't connected to memory leak issues in your application. Many of these warnings may disappear when you update to v9 of WebdriverIO. If you have further questions, please join our [Discord](https://discord.webdriver.io) channel. Thank you.
