### ISSUE TITLE
Dynamically create the wdio.conf.js from another script?

### ISSUE THREAD

**Issue by dmfranko** [webdriverio/webdriverio#1346]
## The problem

Want to be able to dynamically create the wdio.conf.js from another script.  This isn't really a wdio problem, but it seems something that you may have thought about.

## Environment

N/A

## Details

I want to be able to write:

```
var UnitReporter = require('../unitreporter');

exports.config = {
    // ...
    reporters: [UnitReporter],
    // ...
};
```

Here's what I'm doing currently, but I feel like there must be a much better way to do it:
```
exports = {};
caps = {};
caps.os = 'Mac';
exports.capabilities = [caps];

jsonString = JSON.stringify(exports);
var full = jsonString.slice(0, 1) + '"reporters":[UnitReporter],' + jsonString.slice(1);
script = "var UnitReporter = require('../unitreporter');exports.config =" + full;

console.log(script);
```
## Link to Selenium/WebdriverIO logs

N/A

## Code To Reproduce Issue [ Good To Have ]

N/A

**Comment by christian-bromann** [comment]
Please see http://webdriver.io/guide/testrunner/organizesuite.html
