### ISSUE TITLE
[🐛 Bug]: V9: cannot run tests using node.js v18.16.0

### ISSUE THREAD

**Issue by mjohnstonkura** [webdriverio/webdriverio#13480]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.0.7

### Node.js Version

18.16.0

### Mode

WDIO Testrunner

### What happened?

Upgraded to V9. Attempted to run the tests and was presented with an error. `SyntaxError: The requested module 'node:events' does not provide an export named 'addAbortListener'`

### What is your expected behavior?

Since nodejs v18 is supported I would have expected it to work. Doing a little digging I found [events.addAbortListener(signal, listener)](https://nodejs.org/api/events.html#eventsaddabortlistenersignal-listener) was added as an experimental feature in `Added in: v20.5.0, v18.18.0`. Node 18 versions under `v18.18.0` won't currently work.

### How to reproduce the bug.

I can reproduce the issue with the jasmine boilerplate project. https://github.com/webdriverio/jasmine-boilerplate
`npm i` then `npm run test:local`. Make sure you have nodejs v18.16.0 installed.

### Relevant log output

```typescript
> jasmine-boilerplate@1.0.0 test:local
> wdio run wdio.local.conf.ts

file:///C:/Users/mjohnston/Downloads/jasmine-boilerplate-main/node_modules/execa/lib/utils/max-listeners.js:1
import {addAbortListener} from 'node:events';
        ^^^^^^^^^^^^^^^^
SyntaxError: The requested module 'node:events' does not provide an export named 'addAbortListener'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)

Node.js v18.16.0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting @mjohnstonkura - I have bumped the engine property field and updated the docs to better reflect this requirement. I recommend to update Node.js to the latest v18 or better v20.

**Comment by christian-bromann** [comment]
Thanks for reporting @mjohnstonkura - I have bumped the engine property field and updated the docs to better reflect this requirement. I recommend to update Node.js to the latest v18 or better v20.

**Comment by andi-faizal94** [comment]
Hello i got the error like this
import {addAbortListener} from 'node:events';
        ^^^^^^^^^^^^^^^^
SyntaxError: The requested module 'node:events' does not provide an export named 'addAbortListener'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async file:///Users/andifaizal/Documents/project/qa-automation/node_modules/@wdio/cli/bin/wdio.js:15:17


 I use node js version :  20.15.1

**Comment by andi-faizal94** [comment]
> Thanks for reporting [@mjohnstonkura](https://github.com/mjohnstonkura) - I have bumped the engine property field and updated the docs to better reflect this requirement. I recommend to update Node.js to the latest v18 or better v20.


Hello i got the error like this
import {addAbortListener} from 'node:events';
^^^^^^^^^^^^^^^^
SyntaxError: The requested module 'node:events' does not provide an export named 'addAbortListener'
at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
at async Promise.all (index 0)
at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
at async file:///Users/andifaizal/Documents/project/qa-automation/node_modules/@wdio/cli/bin/wdio.js:15:17

I use node js version : 20.15.1

**Comment by christian-bromann** [comment]
This function was added in Node.js v20.5.0, can you double check your Node.js version?
