### ISSUE TITLE
DeprecationWarning: 'GLOBAL' is deprecated, use 'global'

### ISSUE THREAD

**Issue by remss** [webdriverio/webdriverio#1349]
## The problem

A warning is sent on nodejs 6 
DeprecationWarning: 'GLOBAL' is deprecated, use 'global'

## Environment

* WebdriverIO version: 2.4.5
* Node.js version: 6

## Details

Should replace GLOBAL.WDIO_GLOBALS by global.WDIO_GLOBALS in webdriverio.js and lib/utils/ErrorHandler.js

**Comment by christian-bromann** [comment]
Please update to v4. We don't use `GLOBAL` anymore.
