### ISSUE TITLE
[🐛 Bug]: Does not run the project with wdio-video-reporter

### ISSUE THREAD

**Issue by paulohvalipio** [webdriverio/webdriverio#13517]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.0.8

### Node.js Version

20.17.0

### Mode

WDIO Testrunner

### What happened?

When running the project with wdio-video-reporter it displays the message

Error: Type check for option "reporters" failed: a reporter should be either a string in the format "wdio-<reportername>-reporter" or a function/class. Please see the docs for more information on custom reporters (https://webdriver.io/docs/customreporter)
    at validateConfig (file:///C:/project/node_modules/@wdio/config/build/index.js:105:17)
    at Launcher.run (file:///C:/project/node_modules/@wdio/cli/build/index.js:2164:5)

### What is your expected behavior?

It should allow running the project using wdio-video-reporter.

### How to reproduce the bug.

const video = require('wdio-video-reporter')

reporters: [
    [video, {
      saveAllVideos: true,      
      videoSlowdownMultiplier: 3, 
      videoRenderTimeout: 5,   
    }]
  ],

### Relevant log output

```typescript
Error: Type check for option "reporters" failed: a reporter should be either a string in the format "wdio-<reportername>-reporter" or a function/class. Please see the docs for more information on custom reporters (https://webdriver.io/docs/customreporter)
    at validateConfig (file:///C:/project/node_modules/@wdio/config/build/index.js:105:17)
    at Launcher.run (file:///C:/project/node_modules/@wdio/cli/build/index.js:2164:5)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for raising the issue but it should be raised in the wdio video reporter project. Would you mind raising the same issue there? Thanks!
