### ISSUE TITLE
[💡 Feature]: Add option to add console logs to junit report

### ISSUE THREAD

**Issue by sebastian-sauer** [webdriverio/webdriverio#13522]
### Is your feature request related to a problem?

When viewing junit xml results in e.g. jenkins it'd be very helpful to have the ability to view the console logs for a testcase.

Currently i'm only able to see the commands sent by webdriverio

### Describe the solution you'd like.

As implemented for allure and spec reporter in https://github.com/webdriverio/webdriverio/pull/7134 i'd like to add a option to add console logs to junit xml report.

If activated the standardout will contain:

```
console log line 0
console log line 1

...Command output...

COMMAND: POST /session/4875944f97c944d80e944a399b682656/url - {"url":"http://google.com/"}
RESULT: {"url":"http://google.com/"}
COMMAND: GET /session/4875944f97c944d80e944a399b682656/title - {}
RESULT: {}
```

### Additional context

If this feature is accepted i'm happy to send a PR for this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
This should be very simple now with WebDriver Bidi and the ability to listen to browser events. Any contributions are welcome!

**Comment by sebastian-sauer** [comment]
> This should be very simple now with WebDriver Bidi and the ability to listen to browser events. Any contributions are welcome!

Maybe my ticket was misleading - I don't mean the browser console log. I mean the nodejs console logs as implemented for allure and spec reporter. 

This helps a lot if you add logs in your wdio test cases to easier analyze problems.

I'll raise a pr for this.
