### ISSUE TITLE
[🐛 Bug]: v9 browser.mock not returning mock response

### ISSUE THREAD

**Issue by SimonRazor** [webdriverio/webdriverio#13555]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

20.11.1

### Mode

WDIO Testrunner

### What happened?

Using browser.mock in v9 doesn't appear to intercept the network request and therefore doesn't update the reponse. Reverting to version 8.32.3 works as expected

### How to reproduce the bug.
```
describe('Mocking the BBC Sports Page with JS Alert on failure', () => {
    it('should show an alert when navigating to the sports page fails', async () => {
      // Mock the request for the BBC Sports page
      const bbcSportsMock = await browser.mock('https://www.bbc.co.uk/sport', {
        method: 'get',
      });
  
      // Simulate a 500 Internal Server Error
      bbcSportsMock.respond({}, {
        statusCode: 500,
        headers: { 'Content-Type': 'text/html' }
      });
  
      // Navigate to the BBC Sports page
      await browser.url('https://www.bbc.co.uk/sport');
  
      // Inject JavaScript into the page to trigger an alert when there's an error
      await browser.execute(() => {
        // Check if the page failed to load properly (status 500)
        const errorStatus = 500; // Simulated error status
        if (errorStatus === 500) {
          alert('Page failed to load due to server error!');
        }
      });

      await browser.debug(); // should see the JS alert but don't
    });
  });
```
### Relevant log output

```typescript
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by sschoorens** [comment]
For me `browser.mock` is no more working like before it needs to respond at least a bit of text
`bbcSportsMock.respond({}` => `bbcSportsMock.respond('OK'`

also and it's a big breaking change `bbcSportsMock.respond((request) => { return request.body }` no more working too

**Comment by sschoorens** [comment]
I tested your case the problem is more with the url pattern that seems to work only without host

```
it('should show an alert when navigating to the sports page fails', async () => {
    // Mock the request for the BBC Sports page
    const bbcSportsMock = await browser.mock('**/sport');

    // Simulate a 500 Internal Server Error
    bbcSportsMock.respond({}, {
      statusCode: 500,
      headers: { 'Content-Type': 'text/html' }
    });

    // Navigate to the BBC Sports page
    await browser.url('https://www.bbc.co.uk/sport');

    // Inject JavaScript into the page to trigger an alert when there's an error
    await browser.execute(() => {
      // Check if the page failed to load properly (status 500)
      const errorStatus = 500; // Simulated error status
      if (errorStatus === 500) {
        alert('Page failed to load due to server error!');
      }
    });

    await browser.debug(); // should see the JS alert but don't
  });
```

So the respond work with `{}`

**Comment by sschoorens** [comment]
> For me `browser.mock` is no more working like before it needs to respond at least a bit of text `bbcSportsMock.respond({}` => `bbcSportsMock.respond('OK'`
> 
> also and it's a big breaking change `bbcSportsMock.respond((request) => { return request.body }` no more working too

from my tests it respond JSON if we pass an object

but if it not working if we pass an empty string `bbcSportsMock.respond(''` and also if we used a function `bbcSportsMock.respond((req) => { console.error(req); return 'OK'; }`

**Comment by Badisi** [comment]
I can confirm that the following example does not work anymore in v9.0.9:
https://webdriver.io/docs/mocksandspies/#dynamic-responses
```ts
mock.respond((req) => {
  // replace todo content with their list number
  return req.body.map((item, i) => ({ ...item, title: i }))
})
```
This regression is a real blocker for me...

**Comment by Badisi** [comment]
Still not working in v9.1.0, but I'm afraid it's a Bidi's current limitation...
https://github.com/w3c/webdriver-bidi/issues/747
