### ISSUE TITLE
[🐛 Bug]: Incorrect file type in specs when using cucumber framework

### ISSUE THREAD

**Issue by Chubok-bit** [webdriverio/webdriverio#13554]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.0.8

### Node.js Version

20.9.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [{
        browserName: 'MicrosoftEdge'
    }],
```

### What happened?

When starting a brand new project with the Cucumber framework (? Which framework do you want to use? Cucumber (https://cucumber.io/)) the specs property is not set correctly. When you attempt to run the tests you get the following error:

2024-09-11T13:33:46.462Z WARN @wdio/config:ConfigParser: pattern ./test/specs/**/*.ts did not match any file
2024-09-11T13:33:46.463Z ERROR @wdio/cli:launcher: No specs found to run, exiting with failure

### What is your expected behavior?

    The specs property for the example project needs to change from:
    
    specs: [
        './test/specs/**/*.ts'
    ],
    
    to: 
    
       specs: [
        './test/specs/**/*.featur'
    ],

### How to reproduce the bug.

1. Create a new wdio v9 project with the following settings:
    
? A project named "v9" was detected at "C:\Work\v9", correct? yes
? What type of testing would you like to do? E2E Testing - of Web or Mobile Applications
? Where is your automation backend located? On my local machine
? Which environment you would like to automate? Web - web applications in the browser
? With which browser should we start? Microsoft Edge
? Which framework do you want to use? Cucumber (https://cucumber.io/)
? Do you want to use Typescript to write tests? yes
? Do you want WebdriverIO to autogenerate some test files? yes
? What should be the location of your spec files? C:\Work\v9Testing\test\specs\**\*.ts
? What should be the location of your step definitions? C:\Work\v9Testing\features\step-definitions\steps.ts
? Do you want to use page objects (https://martinfowler.com/bliki/PageObject.html)? yes
? Where are your page objects located? C:\Work\v9Testing\features\pageobjects\**\*.ts
? Which reporter do you want to use? spec
? Do you want to add a plugin to your test setup?
? Would you like to include Visual Testing to your setup? For more information see https://webdriver.io/docs/visual-testing! no
? Do you want to add a service to your test setup?
? Do you want me to run `npm install` yes

2. Try to run the example tests. 

### Relevant log output

```typescript
2024-09-11T13:38:04.783Z INFO @wdio/cli:launcher: Run onPrepare hook
2024-09-11T13:38:04.786Z INFO @wdio/utils: Setting up browser driver for: MicrosoftEdge@stable
2024-09-11T13:38:04.787Z INFO @wdio/utils: Setting up browser binaries for: MicrosoftEdge@stable
2024-09-11T13:38:04.788Z WARN @wdio/config:ConfigParser: pattern ./test/specs/**/*.ts did not match any file
2024-09-11T13:38:04.789Z ERROR @wdio/cli:launcher: No specs found to run, exiting with failure
2024-09-11T13:38:04.789Z INFO @wdio/cli:launcher: Run onComplete hook
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
This got fixed in https://github.com/webdriverio/webdriverio/pull/13566 and will be released with the next version.
