### ISSUE TITLE
[🐛 Bug]: [v9 ][CRITICAL] Misfound elements when BiDi locators lose parent context and fall back to WebDriver Classic

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#13556]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

20

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
"browserName": "firefox"
}
```

### What happened?

We issue the commands

```ts
const wrapper = $('[data-testid="wrapper"]')
const nested = wrapper.$('[data-testid="wrapper-nested"]')

```

The nested is retrieved from the root, instead of from nested within wrapper, which brings us a different element !
This happens because internally we get an error:

> WebDriver Bidi command "browsingContext.locateNodes" failed with error: no such node - The node with the reference (wrapper reference) is not known, falling back to regular WebDriver Classic command

Which then executes a normal WebDriver classic but from the root of the page, losing the wrapper parent context, which retrieves a different element !

Classic method is executing a find from the root
Using URL http://localhost:65260/session/${sessionURL}/element
instead of http://localhost:65260/session/${sessionURL}/element/${refetchedElementReference}/element

Here is the offending line of code:
https://github.com/webdriverio/webdriverio/blob/10c8e31abb600f7c31e83df818428813580460db/packages/webdriverio/src/utils/index.ts#L334

`findElements` in called from browser, without parent nesting context !

### What is your expected behavior?

Element nesting and parent context should be respected !

### How to reproduce the bug.

Observed in Firefox.

Conditions tricky to implement due to staleness of elements but solution is not: Element context should be preserved when calling WebDriver Classic method !

### Relevant log output

Here we give a command to find [data-testid="wrapper-nested"] which is located inside a [data-testid="wrapper"]
```ts
INFO webdriver: DATA { using: 'css selector', value: '[data-testid="wrapper-nested"]' }
```
Since this is BiDi v9, `browsingContext.locateNodes` attempts to find it, with the correct context, the element reference for the wrapper is sent in `startNodes`

```json
INFO webdriver: BIDI COMMAND browsingContext.locateNodes {
    "locator": {
        "type": "css",
        "value": "[data-testid=\"wrapper-nested\"]"
    },
    "context": "437e2afe-fd61-4568-af88-26ff1e51ac1e",
    "startNodes": [
        {
            "sharedId": "97e6478d-2fd9-45d3-acfc-ad162ae362a4"
        },
        {
            "sharedId": "3ae62490-0013-4583-aad7-2fe8fbf1660c"
        }
    ]
}
```
Then it fails, due to unknown reference to the wrapper element (97e6478d-2fd9-45d3-acfc-ad162ae362a4)
Possibly a stale element, then falls back to WebDriver classic
```
2024-09-11T14:51:44.626Z WARN webdriverio: Failed to execute browser.browsingContextLocateNodes({ ... }) due to
Error: WebDriver Bidi command "browsingContext.locateNodes" failed with error:
no such node - The node with the reference 97e6478d-2fd9-45d3-acfc-ad162ae362a4 is not known, 
falling back to regular WebDriver Classic command
```
And here lies the problem, Classic method is executing a find from the root
Using URL http://localhost:65260/session/${sessionURL}/element
instead of http://localhost:65260/session/${sessionURL}/element/${refetchedElementReference}/element
```ts
2024-09-11T14:51:44.626Z INFO webdriver: COMMAND findElement("css selector", "[data-testid="wrapper-nested"]")
2024-09-11T14:51:44.626Z INFO webdriver: [POST] http://localhost:65260/session/76788a73-a7c1-4c90-94dc-67f478e3d2a2/element
2024-09-11T14:51:44.626Z INFO webdriver: DATA {
  using: 'css selector',
  value: '[data-testid="wrapper-nested"]'
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by CernyRobert** [comment]
I observed same problem on Chrome. Chainable selectors are not working correctly in v9.

**Comment by nextlevelbeard** [comment]
The offending PR is https://github.com/webdriverio/webdriverio/pull/12720
This was released with version 9.0.0, so if affects all v9 versions

**Comment by christian-bromann** [comment]
@nextlevelbeard please provide a minimal reproduction case otherwise it will be hard to work on this.

**Comment by SimonRazor** [comment]
Here's an example of something that worked in v8 but doesn't work in v9. Obviously there is parentElement() which works but if you do something like the below to traverse the DOM it breaks.

```
describe('Chaining', () => {
    it('should be true', async () => {
        await browser.url("https://the-internet.herokuapp.com/challenging_dom");
        console.log(await (await $("td=Adipisci1").$("..").$("a=edit")).isDisplayed());
    });
});
```

**Comment by christian-bromann** [comment]
I will go ahead and close the issue as it doesn't seem anyone can provide a reproduction case. I am sure this defect exist and was introduced in v9 however working on such an issue without a proper reproduction case in not efficient for maintainers which is why we require this. Happy to re-open the issue if an example can be provided.

**Comment by SimonRazor** [comment]
@christian-bromann I added a repro test above....

**Comment by christian-bromann** [comment]
> I added a repro test above....

I am not sure if this is the same issue as reported by OP, mind raising a new issue for it?

**Comment by SimonRazor** [comment]
Sure, raised here https://github.com/webdriverio/webdriverio/issues/13652

**Comment by nextlevelbeard** [comment]
@christian-bromann

I know a reproducible example is missing here but this issue is too major and needs an experienced set of eyes.
Good news is **I'm able to consistently reproduce the error in question** with my E2E tests.
Therefore, I have booked an open office hour, lmk if you can make it.

I've tried my best in coming up with a test for this but I'm having a hard time with the mocks.
It seems there are no good examples and mocks in place to simulate web-socket responses from BiDi commands.

Setting capability `browserName` as  `bidi` is unhelpful as it is a customization of mocking the `fetch`(as opposed to `ws`) module. Furthermore, it is unclear where `findDeepElement`  and BiDi's `browsingContext.locateNodes` fits into the overall architecture and what to do in case of staleness of any out of N `startNode`s.

Here is the flow, hopefully you or somebody finds this helpful:

DOM state: 
```xml
<div id="foo">
    <div id="bar">
<div id="bar">
```

Element 1 (#foo) and element 2 (#bar) exist in the root of the DOM.
Element 3 (also a #bar) is nested inside the Element 1 (#foo), therefore we build a nested element to find them.
This part is important. The process fails because of the webdriverIO feature of nested elements.

```ts
const rootFoo = await $('#foo');
const rootBar = await $('#bar');

// Problem is when you do this
// If "rootFoo" becames stale, and WebDriver BiDi is on, it actually returns "rootBar"
const fakeNestedBar = await rootFoo.$('#bar'); 

// No problem finding the nested #bar here
const realNestedBar = await $('#foo #bar');
```
