### ISSUE TITLE
Clicks not working and Pause between commands

### ISSUE THREAD

**Issue by MikiDavid** [webdriverio/webdriverio#1356]
## The problem

At my script, I'm catching few elements (using `.elements`) and then I'm clicking on the 5th element and 4th element (using `elementIdClick`).
From some reason, the clicks sometimes works as expected and sometimes not working and only the 4th element being clicked \ only the 5th element being clicked.
Therefor,
I wanted to pause execution between the clicks, and thought that this probably will help, but, it seems like the pause (`.pause`) is not happening at all.

I'm having two questions here..
1. Why sometimes only one element clicked \ sometimes both clicked?
2. Why does the pause command is not working?

## Environment

* WebdriverIO version: 4.0.3
* Node.js version: 5.9.1

## Details

I'm running with chromedriver, a custom electron browser.

## Code To Reproduce Issue:
```
.elements(css_checkBoxes).then(function (res) {
        client.elementIdClick(res.value[5].ELEMENT).then(function(){
            client.pause(10000)
            console.log('Check box #', 5, ' Checked.')
        })
        client.elementIdClick(res.value[4].ELEMENT).then(function(){
            console.log('Check box #', 4, ' Unchecked.')
        })
    })
```

**Comment by christian-bromann** [comment]
You need to handle command promises properly:
```js
    .elements(css_checkBoxes).then(function (res) {
        return client.elementIdClick(res.value[5].ELEMENT).then(function(){
            return client.pause(1000).call(function() {
                console.log('Check box #', 5, ' Checked.')
            })
        }).elementIdClick(res.value[4].ELEMENT).then(function(){
            console.log('Check box #', 4, ' Unchecked.')
        })
    })
```
