### ISSUE TITLE
getLocations causes error when selector matches multiple elements in async mode

### ISSUE THREAD

**Issue by gronke** [webdriverio/webdriverio#1357]
## The problem

When `getLocations()` in async mode on a selector that matches multiple elements an error may be thrown. (Could not reproduce locally, but on SauceLabs)

```
{ [Error: ERROR user sent another command while waiting for command to complete]
  message: 'ERROR user sent another command while waiting for command to complete',
  type: 'RuntimeError',
  seleniumStack: 
   { status: 13,
     type: 'UnknownError',
     message: 'An unknown server-side error occurred while processing the command.',
     orgStatusMessage: 'ERROR user sent another command while waiting for command to complete',
     screenshot: null } }
``` 

## Environment

* WebdriverIO version: master
* Node.js version: 6.2.0
* standalone and wdio
* asynchronous mode

## Details

The `getLocation` function calls `elementIdLocation` multiple times without explicitly awaiting the previous command to finish. When used with async tests this leads to multiple commands executed in concurrently.

Code Reference: https://github.com/webdriverio/webdriverio/blob/0b1cd54d6cfb14f9b6133be9223af52fd3af8b07/lib/commands/getLocation.js#L41-L43

**Comment by christian-bromann** [comment]
I think instead of querying all locations at once we could just get them one after time

**Comment by cnbcqaauto** [comment]
Hi this suggestion is not working. still facing the issue.
