### ISSUE TITLE
[🐛 Bug]: v9: junit-reporter: Report is empty

### ISSUE THREAD

**Issue by torbenkohlmeier** [webdriverio/webdriverio#13608]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.0.9

### Node.js Version

18.20.4

### Mode

Standalone Mode

### What happened?

After updating wdio including @wdio/junit-reporter to version 9, the generated report is empty:

    <?xml version="1.0" encoding="UTF-8"?>
    <testsuites tests="0" failures="0" errors="0" skipped="0"/>

I debugged this and found the reason. [This method](https://github.com/webdriverio/webdriverio/blob/d6c0af67c69e2ccf75bb539b067fafe18f681afc/packages/wdio-junit-reporter/src/index.ts#L364) compares file paths of different types and cases. The first file path (specFileName) has the form `file:///C:/[...]`, the second file path `c:\[...]`. After the conversion with `fileURLToPath` the paths are `C:\[...]` and `c:\[...]`. So the case of the drive letters does not match. Maybe on Windows the comparison should be done case-insensitive.

### What is your expected behavior?

The report should not be empty.

### How to reproduce the bug.

Run tests with junit-reporter on Windows.

### Relevant log output

```typescript
Nothing
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by torbenkohlmeier** [comment]
Here you go: https://github.com/torbenkohlmeier/junit-report-error-example

**Comment by sebastian-sauer** [comment]
@torbenkohlmeier i've raised a pr - unfortunately i've got no windows laptop at hand currently. Maybe you could give it a test? Otherwise i'll test the pr as soon as i'm on my windows machine.

**Comment by torbenkohlmeier** [comment]
@sebastian-sauer: It works! The report now looks like this:

    <?xml version="1.0" encoding="UTF-8"?>
    <testsuites tests="1" failures="0" errors="0" skipped="0">
      <testsuite name="webdriver io page" timestamp="2024-09-25T09:23:27" time="2.244" tests="1" failures="0" errors="0" skipped="0">
        <properties>
          <property name="specId" value="0"/>
          <property name="suiteName" value="webdriver.io page"/>
          <property name="capabilities" value="chrome.129_0_6668_70.windows"/>
          <property name="file" value="file:///C:/git/junit-report-error-example/jasmine.spec.ts"/>
        </properties>
        <testcase classname="chrome.129_0_6668_70.windows.webdriver.io_page" name="should have the right title" time="2.242">
          <system-out><![CDATA[
    COMMAND: GET /session/0bb3c6e4ac13e8cd7d962208e0dc3324/window - {}
    RESULT: {}
    COMMAND: GET /session/0bb3c6e4ac13e8cd7d962208e0dc3324/window - {}
    RESULT: {}
    COMMAND: GET /session/0bb3c6e4ac13e8cd7d962208e0dc3324/window - {}
    RESULT: {}
    COMMAND: GET /session/0bb3c6e4ac13e8cd7d962208e0dc3324/window - {}
    RESULT: {}
    COMMAND: GET /session/0bb3c6e4ac13e8cd7d962208e0dc3324/title - {}
    RESULT: {}
    COMMAND: DELETE /session/0bb3c6e4ac13e8cd7d962208e0dc3324 - {}
    RESULT: {}
    ]]></system-out>
        </testcase>
      </testsuite>
    </testsuites>

Thanks!
