### ISSUE TITLE
[🐛 Bug]: context.skip() behaviour is inconsistent with Sync and Async mocha hooks

### ISSUE THREAD

**Issue by vignesh-grexit** [webdriverio/webdriverio#13620]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

v18

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [{
        browserName: 'chrome'
 }],
```

### What happened?

I've encountered inconsistent behaviour when trying to skip tests using context.skip() within mocha hook `beforeTest`.
Specifically, when I define async beforeTest and call `context.skip()`, the test does not get skipped.
```
async beforeTest (test, context) {
context.skip()
}
```

However, when I define an sync beforeTest and call `context.skip()`, the test get skipped as expected
``` 
beforeTest: function (test, context) {
  context.skip()
}
```

Upon analysis, I found that we are resolving the rejected promise that is returned.
https://github.com/webdriverio/webdriverio/blob/ef5f2e505b4d394321a22173e3da8347b8d0b4c8/packages/wdio-utils/src/shim.ts#L69-L74

I would appreciate your thoughts on rejecting the rejected promise with a message like `sync|async skip; aborting execution` to ensure the test is skipped as intended.

### What is your expected behavior?

When `context.skip()` is called in an async beforeTest, the test should be skipped, just as it works with sync beforeTest.

### How to reproduce the bug.

conf file
```
// wdio.conf.js

export const config = {
    runner: 'local',
    specs: [
        './test/specs/**/*.js'
    ],

    exclude: [
    ],
    capabilities: [{
        browserName: 'chrome'
    }],
    logLevel: 'error',
    bail: 0,
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000,
    },
    async beforeTest (test, context) {
        context.skip()
    }
}

```
test file
```
//test/specs/test.skip.js

describe('SKIP TEST', () => {

    it('TO SKIP', () => {
        console.log('SHOULD NOT BE PRINTED...')
    })

})

```

### Relevant log output

```typescript
[0-0] RUNNING in chrome - file:///test/specs/test.skip.js
[0-0] 2024-09-19T16:29:20.386Z ERROR @wdio/utils:shim: sync skip; aborting execution
[0-0] SHOULD NOT BE PRINTED...
[0-0] PASSED in chrome - file:///test/specs/test.skip.js
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting and your investigation. Would you be interested helping raising a PR?
