### ISSUE TITLE
[🐛 Bug]: 'capabilities' does not exist in type 'Testrunner'

### ISSUE THREAD

**Issue by SerhiiMaksymivQAMadness** [webdriverio/webdriverio#13621]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.0.9

### Node.js Version

20.16.0, 18.20.4

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [{
        browserName: 'chrome'
    }],
```

### What happened?

following `npm init wdio@latest .` steps with typescript im seeing error in wdio.config.ts file:
```
╰─ tsc --project tsconfig.json
wdio.conf.ts:56:5 - error TS2353: Object literal may only specify known properties, and 'capabilities' does not exist in type 'Testrunner'.

56     capabilities: [{
       ~~~~~~~~~~~~

Found 1 error in wdio.conf.ts:56
```

### What is your expected behavior?

I'd expect capabilities property included in TestRunner
or
If TestRunner shouldn't include capabilites, would be nice to know how to specify capabilities.

### How to reproduce the bug.

npm init wdio@latest .
with ts

### Relevant log output

```typescript
-
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@SerhiiMaksymivQAMadness thanks for reporting! This is a known issue and has been fixed in `main` and we just haven't released this fix yet. Hopefully on Monday we can push out a fix for it. A workaround for this is to change the type for your `wdio.conf.ts` to:

```ts
export const config: WebdriverIO.Config = {
  // ...
}
```
