### ISSUE TITLE
[📖 Docs]: Dedicated Section for  running tests on Remote Selenium Grid

### ISSUE THREAD

**Issue by amardeep2006** [webdriverio/webdriverio#13626]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Missing documentation

### Description of the improvement / report

Hi Team, 
I feel there can be a dedicated section to add instructions for running tests on Remote Selenium grid. I am happy to contribute but not sure where should I add it.
Can this be added under Using Cloud Services https://webdriver.io/docs/cloudservices OR we should add new section under Integration called Selenium grid ?
I will prefer to add a separate page.
1. Configuration to point tests at selenium grid
2. Basic Authentication
3. Timeout configurations
4. Passing Custom Capabilities
5. Reference to File Upload and Download with Selenium grid

Thanks a lot.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amardeep2006** [comment]
I have raised a PR https://github.com/webdriverio/webdriverio/pull/13627
Please review and share feeedback.

**Comment by christian-bromann** [comment]
Thanks @amardeep2006 for writing up the docs, let's continue our convo in #13627
