### ISSUE TITLE
Commands not being executed due to timeout

### ISSUE THREAD

**Issue by kevinmcdonnell** [webdriverio/webdriverio#1365]
## The problem

I am seeing an intermittent issue where commands after a click are not being executed. Most recently 33 passes and then 1 failure

Allure report suggests the click itself is timing out. 

I should note that the button does not actually do anything. Depending on config it redirects to another url or does nothing, in this case nothing.
## Environment

* WebdriverIO version: 4.0.9
* Node.js version: 4.4.4
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): junit, selenium-standalone, mocha, allure

## Link to Selenium/WebdriverIO logs

https://gist.github.com/kevinmcdonnell/607c6d061a958f5de24288f6beec2afe

## Code To Reproduce Issue [ Good To Have ]

I cannot reproduce on demand but instead see the error intermittently so cannot really provide details here. In the logs and screenshot there should be a pause after the click followed by other commands

```
...
browser.click('button.test-dialog-quit');
browser.pause(2000);
...
```

<img width="611" alt="screen shot 2016-06-07 at 08 01 27" src="https://cloud.githubusercontent.com/assets/7575152/15839475/e11aca80-2c86-11e6-9389-7b2c8246edea.png">

**Comment by christian-bromann** [comment]
It seems that you never received the response from the click command. Is this an reproducible error?

**Comment by kevinmcdonnell** [comment]
Not reproducible unfortunately

I isolated the test and ran it 200 times with no failures. When running as part of my test suite it fails sporadically, in between 3-10% of test runs

**Comment by christian-bromann** [comment]
I believe this is more on the selenium servers end. Not sure what to do about it in WebdriverIO. Any ideas on your side?

**Comment by kevinmcdonnell** [comment]
After opening this ticket I began to suspect a possible bug in chromedriver. 

We have 100's of tests running and have only seen this in 1 test a 6-12 times. 

I think its fair to close this. If I see it again I will try to isolate and also compare if it is browser specific.
