### ISSUE TITLE
Test reports are not generated

### ISSUE THREAD

**Issue by yhjor1212** [webdriverio/webdriverio#1366]
I am using junit to export test report but the following settings suddenly do not work any more.

When specifying wdio.conf.js, the following does not generate any error report, without any error messages:

```javascript
reporter: 'junit',

  reportOptions: {
    outputDir: './test/browser/reports',
  },
```

If I change the settings to this one, the error message is like this:

```
2 passing (27.90s)

Cannot write xunit report: empty or invalid 'outputDir'.
info: Browser test completed!
```

```javascript
reporters: ['dot', 'junit'],

  reportOptions: {
    junit: {
      outputDir: './test/browser/reports',
    }
  },
```

## Environment

* WebdriverIO version: 4.0.9
* Node.js version: 6
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio-mocha-framework
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):

**Comment by christian-bromann** [comment]
Can you try:
```js
reporters: ['dot', 'junit'],

  reportOptions: {
    junit: {
      outputDir: './test/browser/reports/',
    }
  },
```

**Comment by yhjor1212** [comment]
Same result: Cannot write xunit report: empty or invalid 'outputDir'.

**Comment by yhjor1212** [comment]
btw, I can generate screenshots when there are failed cases:

`screenshotPath: './test/browser/screenshots',`

but the report generation just doesn't work,

no matter I use another path or I use path.resolve to render full path.

**Comment by yhjor1212** [comment]
I've tried different combinations, and installed:

```
"wdio-dot-reporter": "0.0.5",
    "wdio-junit-reporter": "0.0.2",
```

and it just DOESN'T work:

```
reporters: ['dot', 'junit'],

  reportOptions: {
    outputDir: './',
    outputFileFormat: function(opts) { // optional
       return `results-${opts.cid}.${opts.capabilities}.xml`
    }
  },
```

**Comment by yhjor1212** [comment]
It is found that the reporter related options cannot be called from another file, it must be resided in wdio.conf.js.

Here is my workaround particularly for that options:

```javascript
require('babel-core/register');

const wdioConfig = require('./wdio.conf.babel');

exports.config = Object.assign({}, wdioConfig.default, {
  reporters: ['dot', 'junit'],
  reporterOptions: {
    junit: {
      outputDir: './test/browser/reports',
    },
  },
});
```

**Comment by floede** [comment]
@yhjor1212 

I just struggled with this problem, but got it working after I noticed:

`reportOptions`

vs

`reporterOptions`

I see you have the same difference in your failing and working examples.
