### ISSUE TITLE
merge capabilities from the Selenium server after initialising the session

### ISSUE THREAD

**Issue by maggiesavovska** [webdriverio/webdriverio#1368]
## The problem

After I've initiated the driver I want to be able to get the browser name and version with driver.getCapabilities(); Currently I am using driver.desiredCapabilities.browserName but this is not ideal because the desired Capabilities might not match the actual capabilities.

**Comment by christian-bromann** [comment]
What would you think, shall we add another property like `actualCapabilties` or shall we just merge them together?

**Comment by maggiesavovska** [comment]
Thanks! I think it would be more intuitive if we add another property "actualCapabilities".

**Comment by beck** [comment]
@maggiesavovska `session` has all the information you're looking for.

Try it in the repl:
```
> browser.session().value
{ 'moz:profile': '/var/folders/3y/7jrv6jr95fnbs9rr0vx1xwzc0000gn/T/rust_mozprofile.luU1z3NGy5qr',
  rotatable: false,
  timeouts: { implicit: 0, pageLoad: 300000, script: 30000 },
  pageLoadStrategy: 'normal',
  platform: 'ANY',
  specificationLevel: 0,
  'moz:accessibilityChecks': false,
  'webdriver.remote.sessionid': 'c7ae6dc2-b66a-4c8b-a70f-b5a408e6935f',
  acceptInsecureCerts: false,
  browserVersion: '54.0.1',
  platformVersion: '16.7.0',
  'moz:processID': 21271,
  browserName: 'firefox',
  takesScreenshot: true,
  javascriptEnabled: true,
  platformName: 'darwin',
  cssSelectorsEnabled: true }
```

What worked for me, adding a global `agent` using `wdio.conf.js`:
```js
exports.config = {
  before: function (capabilities, specs) {
    const session = browser.session().value;
    global.agent = `${session.browserName} ${session.browserVersion}`;
    global.expect = chai.expect;
  },
}
```

And now in the spec, can do something like:
```js
browser.logger.info(`Using ${agent}`);
```

and now my test run shows:
```
[15:07:35]  INFO	Using firefox 54.0.1
```

**Comment by christian-bromann** [comment]
This will be implemented in v5. Since no one touched this issue for v4 I will close this.
