### ISSUE TITLE
Running server (selenium-standalone start) takes 2.5 min~

### ISSUE THREAD

**Issue by MikiDavid** [webdriverio/webdriverio#1370]
## The problem

When running the command 

> selenium-standalone start

It takes the server to launch approximately 2.5 minutes.

Is this make sens?

## Environment

* WebdriverIO version: 4.0.9
* Node.js version: 5.9.1
* [wdio testrunner]

**Comment by christian-bromann** [comment]
Please open this issue in the [selenium-standalone](https://github.com/vvo/selenium-standalone) project.
