### ISSUE TITLE
Running more than one suite

### ISSUE THREAD

**Issue by MikiDavid** [webdriverio/webdriverio#1372]
## The problem

I started to arrange my tests in suites and find this features very helpful.

My question is:
Is there a way to run more than one suite at session?

Meaning-
Say I have the following config file:

```
///
specs: [
        './testRunner/*.js'
    ],
    suites :{
        suiteOne: [
            './testRunner/TC1.js',
            './testRunner/TC2,js'
        ],
        suiteTwo: [
            './testRunner/TC3.js',
            './testRunner/TC4.js'
        ],
        suiteThree: [
            './testRunner/TC5.js',
            './testRunner/TC6.js'
        ]
    },
///
```

Is it possible to execute only suiteOne and suiteThree?

I tried to do something like `wdio wdio.conf.js --suite suiteOne suiteTwo`, But it failed to start a session.

## Environment

* WebdriverIO version: 4.0.9
* Node.js version: 5.9.1
* [wdio testrunner]

**Comment by christian-bromann** [comment]
It's not possible to do this right now but it should be an easy enhancement

**Comment by christian-bromann** [comment]
Will be released with the next version (`v4.1.0` no ETA on that though)

**Comment by UserTester115** [comment]
Hey! Just was curious, is it possible right now?

**Comment by christian-bromann** [comment]
> Hey! Just was curious, is it possible right now?

Yes, see https://webdriver.io/docs/organizingsuites

**Comment by UserTester115** [comment]
Many thanks! That is awesome. Somehow missed that
