### ISSUE TITLE
[🐛 Bug]: Change Headers not works

### ISSUE THREAD

**Issue by agracia-foticos** [webdriverio/webdriverio#13739]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

^8.40.6

### Node.js Version

22.7.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [{
        maxInstances: 10,
        browserName: 'chrome',
        'goog:chromeOptions': {
            args: [
                '--no-sandbox',
                '--disable-infobars',
                '--headless',
                '--disable-gpu',
                '--disable-extensions',
                '--disable-dev-shm-usage',
                '--multi-browser',
                '--disable-blink-features=AutomationControlled', // Desactiva la detección de automatización
            ],
            prefs: {
                'profile.password_manager_enabled': false,
                'credentials_enable_service': false
            }
        }
    }],
```

### What happened?

Change headers throuh url method not works

### What is your expected behavior?

...

### How to reproduce the bug.

``describe('Añadir encabezados personalizados al navegar', () => {
    it('Debería incluir encabezados personalizados en la solicitud', async () => {
        // URL de destino
        const targetUrl = 'https://httpbin.org/headers'; // Esta URL devuelve los encabezados que recibe

        // Encabezados personalizados
        const customHeaders = {
            'Custom-Header': 'ValorPersonalizado',
            'Referer': 'https://google.com'
        };

        // Navegar a la URL con encabezados personalizados
        await browser.url(targetUrl, {
            headers: customHeaders
        });

        // Verificar los encabezados recibidos
        const responseHeaders = await browser.getText('pre'); // Obtenemos el contenido de la respuesta
        console.log('Encabezados recibidos:', responseHeaders);
        
        // Opcional: puedes validar que el encabezado fue recibido correctamente
        expect(responseHeaders).toContain('Custom-Header');
        expect(responseHeaders).toContain('Referer');
    });
});``

### Relevant log output

```typescript
Execution of 1 workers started at 2024-10-07T11:01:12.689Z

[0-0] RUNNING in chrome - file:///test/specs/common/utm-params.spec.ts
[0-0] PASSED in chrome - file:///test/specs/common/utm-params.spec.ts

 "spec" Reporter:
------------------------------------------------------------------
[chrome 128.0.6613.113 linux #0-0] Running: chrome (v128.0.6613.113) on linux
[chrome 128.0.6613.113 linux #0-0] Session ID: 3994b33111b82c41a186b2d6201d0d49
[chrome 128.0.6613.113 linux #0-0]
[chrome 128.0.6613.113 linux #0-0] » /test/specs/common/utm-params.spec.ts
[chrome 128.0.6613.113 linux #0-0] testing UTM Params - cookies
[chrome 128.0.6613.113 linux #0-0]    ✓ config test
[chrome 128.0.6613.113 linux #0-0]
[chrome 128.0.6613.113 linux #0-0] 1 passing (637ms)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by BorisOsipov** [comment]
@agracia-foticos 

>`WebdriverIO Version ^8.40.6`

Passing custom headers via url command is v9 feature.

**Comment by agracia-foticos** [comment]
@BorisOsipov i try to change referer from an url request, but this code not works,

Can you help me? 

` it(`simulate referrer from Google`, async () =>  {
        await browser.cdp('Fetch', 'enable', { patterns: [{ requestStage: 'Request' }] });

        // Interceptar la solicitud y modificar el header Referer
        browser.on('Fetch.requestPaused', async (params) => {
            const { requestId, request } = params;

            const headers = request.headers;
            headers['Referer'] = 'https://google.com';

            await browser.cdp('Fetch', 'continueRequest', {
                requestId,
                headers: Object.entries(headers).map(([name, value]) => ({ name, value }))
            });
        });

        await HomePage.open();
  

    })`

**Comment by christian-bromann** [comment]
> Passing custom headers via url command is v9 feature.

Correct, we recommend to update to v9 to access this feature. If there is any reason you can't update to v9, please let us know. Looking at your CDP code, you may want to try the [`Fetch.fulfillRequest`](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/#method-fulfillRequest) method.
