### ISSUE TITLE
All mocha-tests are green when sync is false and capabilities is set

### ISSUE THREAD

**Issue by crazyh** [webdriverio/webdriverio#1373]
## The problem

Looks like WebDriverIO does not catch assertions/exceptions in async mode when capabilities is set.

When capabilities is not set (just comment capabilities key in conf) in wdio.conf.js then WebDriverIO works as expected.

## Environment

* WebdriverIO version: 4.0.9
* Node.js version: 5.10.1
* wdio testrunner mode
* Asynchronous tests (sync: false)
* Additional wdio packages used (if applicable): mocha version 2.5.3, wdio-sync 0.5.1, wdio-mocha-framework version 0.3.1

## Link to Selenium/WebdriverIO logs

https://gist.github.com/crazyh/4fcb36d2ff4f5a229df01a837e281fc1

## Code To Reproduce Issue

1. Set sync to false in wdio.conf.js

2. Set capabilities, e.g.: `capabilities: [{ browserName: 'chrome' }]`

3. Write the following Mocha test:

```
describe('index', function () {
  it('foo', function () {
    'a'.should.be.equal('b');
  });
  it('bar', function () {
    throw Error('bar');
  });
});

```

Run `wdio -l verbose wdio.conf.js`.

**Comment by christian-bromann** [comment]
@crazyh can you try with the latest mocha framework adapter `v0.3.2`?

**Comment by gkatny** [comment]
I tried replicating this with wdio-mocha-framework 0.3.4 and got the same results. Tests which should fail are passing.

**Comment by christian-bromann** [comment]
@gkatny @crazyh do you guys could provide a reproducible example?

**Comment by crazyh** [comment]
I can send my wdio.conf.js (and I use gulp and gulp/wdio plugin) example next week if it is still necessary.

**Comment by christian-bromann** [comment]
I will need also a mocha test file

**Comment by gkatny** [comment]
I ran your config setup per the documentation after I had already installed some modules.
[gkatnyConfigTest.zip](https://github.com/webdriverio/webdriverio/files/332162/gkatnyConfigTest.zip)

Please let me know if you need other information. Thanks!

**Comment by crazyh** [comment]
Well, I tried @gkatny's config which are similar to mine ones and got the same result:

- Upack @gkatny's files
- Run `docker run --rm -it -v $(pwd):/foo node bash`
- Run `cd /foo ; npm install ; ./node_modules/webdriverio/bin/wdio --host 192.168.53.19 --port 24444 -r wdio.conf.js`

>> 2 passing (1.20s)

**Comment by christian-bromann** [comment]
Just tried with the latest versions of WebdriverIO and the mocha framework adapter and your test file has thrown two errors as expected. Please update your dependencies and try again. Closing.
