### ISSUE TITLE
Mobile touch error

### ISSUE THREAD

**Issue by MakePLAN** [webdriverio/webdriverio#1375]
## The problem

I am trying to implement mobile touch on ios app. After opening video player, I am trying to touch center of screen for close button to pop up and click close button. However, the console said, "RuntimeError: An unknown server-side error occurred while processing the command. (UnknownError:13)". 

## Environment

* WebdriverIO version: 2.15.1
* Node.js version: 4.4.4
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): standalone mode
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Link to Selenium/WebdriverIO logs

Since my log is short, I will post it on here. 

 RuntimeError: An unknown server-side error occurred while processing the command. (UnknownError:13)
      at touchPerform([object Object]) - test_iOS_SmokeTest_FrontPorch.js:149:23

## Code To Reproduce Issue [ Good To Have ]
```js
it ("Check the video player", 
		function(){
			
			return client.click("//UIAApplication[1]/UIAWindow[1]/UIACollectionView[2]/UIACollectionCell[1]")
						.pause(10000)
						.then(
							function(){
								return client.touchPerform(
									{
										action: 'tap',
										options: {
											x: 100,
											y: 250,
											count: 1
										}
									}
								).then(
									function(){
										return client.waitForExist('[name="CLOSE"]').then(
											function(result){
												return client.click('[name="CLOSE"]');
											}
										);
									}
								);
							}
						)
					
		}
	);
```

**Comment by christian-bromann** [comment]
> WebdriverIO version: 2.15.1

what kind of version are you using?

**Comment by MakePLAN** [comment]
I am not sure if I understand your question. I am using node js one. Also, I made a mistake. I have webdriverio version 4.0.7

**Comment by MakePLAN** [comment]
Hi Christian. I am about to send an sample script and app file to run my test. Where should I send it to?

**Comment by christian-bromann** [comment]
just post it in this thread.

**Comment by MakePLAN** [comment]
Do you have mocha installed on your computer?

**Comment by MakePLAN** [comment]
[Archive.zip](https://github.com/webdriverio/webdriverio/files/314508/Archive.zip)

**Comment by MakePLAN** [comment]
Inside the zip, there should be package.json, test.js, and TestApp.app files.

I wrote simple mobile touch action on test.js. i used mocha to run it. I am using webdriverio standalone for this one. So you can see the error for yourself.

**Comment by MakePLAN** [comment]
I figured it out. Sorry about that.
