### ISSUE TITLE
[🐛 Bug]: Could not install on packages on Mac (Apple Chip)

### ISSUE THREAD

**Issue by eduardlavrov** [webdriverio/webdriverio#13752]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

20.18.0

### Mode

Standalone Mode

### What happened?

Steps:
The installation process fails on the following command
`npm install @wdio/local-runner@latest @wdio/mocha-framework@latest @wdio/spec-reporter@latest @wdio/dot-reporter@latest @wdio/junit-reporter@latest @wdio/allure-reporter@latest @wdio/sumologic-reporter@latest @wdio/concise-reporter@latest @wdio/json-reporter@latest wdio-reportportal-reporter wdio-video-reporter wdio-cucumberjs-json-reporter wdio-mochawesome-reporter wdio-timeline-reporter wdio-html-nice-reporter @moroo/wdio-slack-reporter wdio-teamcity-reporter @delta-reporter/wdio-delta-reporter-service @wdio/testrail-reporter@latest wdio-light-reporter wdio-wait-for @badisi/wdio-harness @testing-library/webdriverio @wdio/appium-service@latest @wdio/visual-service wdio-vite-service wdio-nuxt-service @wdio/firefox-profile-service@latest wdio-gmail-service @wdio/sauce-service@latest @wdio/testingbot-service@latest @wdio/browserstack-service@latest @wdio/lighthouse-service@latest wdio-vscode-service wdio-electron-service wdio-eslinter-service wdio-lambdatest-service wdio-zafira-listener-service wdio-reportportal-service wdio-docker-service wdio-ui5-service wdio-wiremock-service wdio-ng-apimock-service wdio-slack-service wdio-cucumber-viewport-logger-service wdio-intercept-service wdio-docker-service wdio-novus-visual-regression-service wdio-rerun-service wdio-winappdriver-service wdio-ywinappdriver-service wdio-performancetotal-service wdio-cleanuptotal-service wdio-aws-device-farm-service wdio-ms-teams-service wdio-tesults-service @gmangiapelo/wdio-azure-devops-service wdio-google-chat-service @sap_oss/wdio-qmate-service wdio-robonut-service wdio-qunit-service @wdio/visual-service appium-uiautomator2-driver --save-dev`

Terminal returns an error
`npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: androidDemo@undefined
npm error Found: @wdio/cli@9.1.4
npm error node_modules/@wdio/cli
npm error   dev @wdio/cli@"^9.1.4" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @wdio/cli@"^7.19.7" from wdio-light-reporter@0.2.7
npm error node_modules/wdio-light-reporter
npm error   dev wdio-light-reporter@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /Users/qansigliere/.npm/_logs/2024-10-10T12_04_56_742Z-eresolve-report.txt
npm error A complete log of this run can be found in: /Users/qansigliere/.npm/_logs/2024-10-10T12_04_56_742Z-debug-0.log`

### How to reproduce the bug.

npm install @wdio/local-runner@latest @wdio/mocha-framework@latest @wdio/spec-reporter@latest @wdio/dot-reporter@latest @wdio/junit-reporter@latest @wdio/allure-reporter@latest @wdio/sumologic-reporter@latest @wdio/concise-reporter@latest @wdio/json-reporter@latest wdio-reportportal-reporter wdio-video-reporter wdio-cucumberjs-json-reporter wdio-mochawesome-reporter wdio-timeline-reporter wdio-html-nice-reporter @moroo/wdio-slack-reporter wdio-teamcity-reporter @delta-reporter/wdio-delta-reporter-service @wdio/testrail-reporter@latest wdio-light-reporter wdio-wait-for @badisi/wdio-harness @testing-library/webdriverio @wdio/appium-service@latest @wdio/visual-service wdio-vite-service wdio-nuxt-service @wdio/firefox-profile-service@latest wdio-gmail-service @wdio/sauce-service@latest @wdio/testingbot-service@latest @wdio/browserstack-service@latest @wdio/lighthouse-service@latest wdio-vscode-service wdio-electron-service wdio-eslinter-service wdio-lambdatest-service wdio-zafira-listener-service wdio-reportportal-service wdio-docker-service wdio-ui5-service wdio-wiremock-service wdio-ng-apimock-service wdio-slack-service wdio-cucumber-viewport-logger-service wdio-intercept-service wdio-docker-service wdio-novus-visual-regression-service wdio-rerun-service wdio-winappdriver-service wdio-ywinappdriver-service wdio-performancetotal-service wdio-cleanuptotal-service wdio-aws-device-farm-service wdio-ms-teams-service wdio-tesults-service @gmangiapelo/wdio-azure-devops-service wdio-google-chat-service @sap_oss/wdio-qmate-service wdio-robonut-service wdio-qunit-service @wdio/visual-service appium-uiautomator2-driver --save-dev

### Relevant log output

```typescript
`npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: androidDemo@undefined
npm error Found: @wdio/cli@9.1.4
npm error node_modules/@wdio/cli
npm error   dev @wdio/cli@"^9.1.4" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @wdio/cli@"^7.19.7" from wdio-light-reporter@0.2.7
npm error node_modules/wdio-light-reporter
npm error   dev wdio-light-reporter@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /Users/qansigliere/.npm/_logs/2024-10-10T12_04_56_742Z-eresolve-report.txt
npm error A complete log of this run can be found in: /Users/qansigliere/.npm/_logs/2024-10-10T12_04_56_742Z-debug-0.log`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> ```ts
> npm error peer @wdio/cli@"^7.19.7" from wdio-light-reporter@0.2.7
> ```

It seems like you are using this reporter which is not compatible with v9. I recommend to raise an issue in the reporter project.

I will go ahead as there is nothing we can do in WebdriverIO to fix this. Let me know if you have further questions.

**Comment by eduardlavrov** [comment]
@christian-bromann Thank You for help!

**Comment by eduardlavrov** [comment]
@christian-bromann I had to remove other libs and now it is reduced to this list:
`npm install @wdio/local-runner@latest @wdio/mocha-framework@latest @wdio/spec-reporter@latest @wdio/dot-reporter@latest @wdio/junit-reporter@latest @wdio/allure-reporter@latest @wdio/sumologic-reporter@latest @wdio/concise-reporter@latest @wdio/json-reporter@latest wdio-reportportal-reporter wdio-video-reporter wdio-mochawesome-reporter wdio-timeline-reporter wdio-html-nice-reporter @moroo/wdio-slack-reporter wdio-teamcity-reporter @delta-reporter/wdio-delta-reporter-service @wdio/testrail-reporter@latest wdio-wait-for @badisi/wdio-harness @testing-library/webdriverio @wdio/appium-service@latest @wdio/visual-service @wdio/firefox-profile-service@latest wdio-gmail-service @wdio/sauce-service@latest @wdio/testingbot-service@latest @wdio/lighthouse-service@latest wdio-electron-service wdio-eslinter-service wdio-zafira-listener-service wdio-reportportal-service wdio-docker-service wdio-wiremock-service wdio-ng-apimock-service wdio-slack-service wdio-cucumber-viewport-logger-service wdio-intercept-service wdio-docker-service wdio-novus-visual-regression-service wdio-rerun-service wdio-winappdriver-service wdio-ywinappdriver-service wdio-performancetotal-service wdio-cleanuptotal-service wdio-aws-device-farm-service wdio-ms-teams-service wdio-tesults-service @gmangiapelo/wdio-azure-devops-service wdio-google-chat-service @sap_oss/wdio-qmate-service wdio-robonut-service wdio-qunit-service @wdio/visual-service appium-uiautomator2-driver --save-dev`

**Comment by christian-bromann** [comment]
@eduardlavrov you certainly don't need to install all services and reporters

**Comment by eduardlavrov** [comment]
Got it! Thank You!
