### ISSUE TITLE
[🐛 Bug]: invalid argument from invalid argument: 'pointerType' must be a string that matches sources pointer type. Touch not recognized.

### ISSUE THREAD

**Issue by PavlikJozef** [webdriverio/webdriverio#13755]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v8

### Node.js Version

v18.20.3

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
		'bstack:options': {
			acceptInsecureCerts: true,
			appiumVersion: '2.4.1',
			browserVersion: device.browserVersion,
			buildName: `${process.env.COMMIT_REF_NAME} - ${process.env.CI_COMMIT_SHORT_SHA}: ${process.env.COMMIT_TITLE}`,
			deviceName: device.deviceName,
			interactiveDebugging: true,
			local: false,
			networkLogs: true,
			os: device.os,
			osVersion: device.osVersion,
			projectName: 'myApp',
		},
		browserName: device.browserName,
		specs: [
			['./tests/*'],
		],
	},
```

### What happened?

In function used for swiping on mobile and tablet devices, i get this error:

**invalid argument from invalid argument: 'pointerType' must be a string that matches sources pointer type (Session info: chrome=127.0.6533.64)**

It fails only on android devices and basically in every run. Can i provide some configuration in wdio capabilities or what can be reason for this error? According to https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/pointerType, "Touch" type for pointerType should be known also here https://chromium.googlesource.com/chromium/src/+/master/chrome/test/chromedriver/window_commands.cc#1326.

Or any ideas of how to implement swipe functionality for web applications which run in browser? I am testing website on different devices via BrowserStack.

### How to reproduce the bug.

custom function for swipe looks like this:

```ts
export const swipe = async (
	direction: 'left' | 'right' | 'up' | 'down',
	times = 1,
	start: { x?: number; y?: number } = {},
	stop: { x?: number; y?: number } = {},
) => {
	const { width, height } = await browser.getWindowSize();

	const getStartCoordinates = () => {
		...
	};

	const getStopCoordinates = () => {
		...
	};

	const startCoordinates = getStartCoordinates();
	const stopCoordinates = getStopCoordinates();

	for (let i = 0; i < times; i++) {
		await browser.performActions([
			{
				type: 'pointer',
				id: `finger${i + 1}`,
				parameters: { pointerType: 'touch' },
				actions: [
					{
						type: 'pointerMove',
						duration: 0,
						x: startCoordinates.x,
						y: startCoordinates.y,
					},
					{ type: 'pointerDown', button: 0 },
					{ type: 'pause', duration: 100 },
					{
						type: 'pointerMove',
						duration: 1000,
						x: stopCoordinates.x,
						y: stopCoordinates.y,
					},
					{ type: 'pointerUp', button: 0 },
				],
			},
		]);
	}
	
	await browser.releaseActions();
};

```

### Relevant log output

```typescript
[chrome Android #0-0] invalid argument
from invalid argument: 'pointerType' must be a string that matches sources pointer type
  (Session info: chrome=127.0.6533.64)
[chrome Android #0-0] invalid argument: invalid argument
[chrome Android #0-0] from invalid argument: 'pointerType' must be a string that matches sources pointer type
[chrome Android #0-0]   (Session info: chrome=127.0.6533.64)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> ```ts
> parameters: { pointerType: 'touch' },
> ```

`touch` is a valid pointer type in [WebDriver Classic](https://www.w3.org/TR/webdriver2/) and Bidi, the specification says:

> If pointer type does not have one of the values "mouse", "pen", or "touch", return [error](https://www.w3.org/TR/webdriver2/#dfn-error) with [error code](https://www.w3.org/TR/webdriver2/#dfn-error-code) [invalid argument](https://www.w3.org/TR/webdriver2/#dfn-invalid-argument).

I am not sure if BS modifies some of the parameters passed to their driver or if there is a different compatibility issue. I will go ahead and close this as I don't think there is something we can fix in WebdriverIO. Happy to answer further questions.
