### ISSUE TITLE
waitUntil returns prematurely

### ISSUE THREAD

**Issue by ebordeau** [webdriverio/webdriverio#1377]
I have a test case that types into a search box and waits for the table filter down to one row:
```
browser.setValue('#mySearchBox', 'foobar');
browser.waitUntil(function() {
    return this.execute(function() {
        return document.querySelectorAll('.table-row').length === 1;
    });
});
```
The `waitUntil` resolves immediately, even though the table has more than one row. After debugging, I've narrowed the problem down to the `Timer.tick()` function:
```
    tick () {
        this._fn().then((res) => {
            // resolve timer only on truthy values
            if (res) {
                this._resolve(res)
                this.stop()
                this.stopMain()
                return
            }
```
In my case, `res` is an object, but its value is false:
```
{
	"state": "success",
	"sessionId": "53ef9ef4-6f35-4120-a43a-4c842fe94027",
	"hCode": 707072008,
	"value": false,
	"class": "org.openqa.selenium.remote.Response",
	"status": 0
}
```
I'm not sure if I'm going about this all wrong or if this is a legitimate bug. If I change `Timer.tick()` to look like this, it works:
```
    tick () {
        this._fn().then((res) => {
            // resolve timer only on truthy values
            if (res && (!res.class || res.class !== 'org.openqa.selenium.remote.Response' || res.value)) {
                this._resolve(res)
                this.stop()
                this.stopMain()
                return
            }
```

## Environment

* WebdriverIO version: 4.0.9
* Node.js version: 4.4.3
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):

**Comment by patthiel** [comment]
I have a similar issue but my promise never gets resolved, as if waitUntil isn't respecting the timeout. 

```

**Comment by monolithed** [comment]
```js
/**
 * @param {string} value
 * @param {number} timeout — ms
 * @returns {Promise}
 */
browser.addCommand('waitForUrl', function (value, timeout) {
	return this.waitUntil(function () {
		return this.url((error, result) => {
			return result.value === value;
		});
	}, timeout);
});
```

Tested with wdio 3

**Comment by ebordeau** [comment]
@monolithed It's possible the issue is with calling `browser.execute()`, which your example doesn't do.

**Comment by christian-bromann** [comment]
I improved the waitUntil command in `v4.0.10`. Please retry with that version. Note: if you run commands synchronously with the wdio test runner make sure the commands in the condition are synchronously as well. You can change that by setting the condition function name to `async`.

**Comment by wlsf82** [comment]
Hi,
I'm having a similar or maybe the same issue.
I'm testing a WebRTC based application, and in one of the tests, I have this code:

```
var roomName = faker.random.word() + faker.random.number();
browser1.url('/' + roomName);
...
browser1.waitUntil(browser1.execute(scripts.allVideosHaveEnoughData).value === true);
expect(browser1.execute(scripts.allVideosHaveEnoughData).value).toBe(true);
```

It is failing in the browser1.waitUntil() line with the following error:

```
Failed: Cannot read property 'indexOf' of undefined
TypeError: Cannot read property 'indexOf' of undefined
```

And here are the logs, in verbose mode:

```
[10:12:12]  COMMAND	POST 	 "/wd/hub/session/468d3ab1-194d-4723-93ce-e07713ae4976/execute"
[10:12:12]  DATA		{"script":"var videos = document.querySelectorAll(\".video-wrapper video\");var ready = 0;for (var i = 0; i < videos.length; i++) {if (videos[i].readyState >= videos[i].HAVE_ENOUGH_DATA) {ready++;}}return ready === videos.length;","args":[]}
[10:12:12]  RESULT		false
```

The fact is that if I execute this script manually in the browser, in the same room that the tests is visiting, it returns true.

Note:I'm using wdio v4.2.16
Note2: In this test I'm running two browsers (browser1 and browser2).

**Comment by khyati2010** [comment]
hi all,


 "spec" Reporter:
------------------------------------------------------------------
[chrome 91.0.4472.106 windows #0-0] Spec: /Users/khyati.sehgal/Documents/workspace/july2021/web-app/e2e/src/test/Signin.spec.ts
[chrome 91.0.4472.106 windows #0-0] Running: chrome (v91.0.4472.106) on windows
[chrome 91.0.4472.106 windows #0-0] Session ID: b7fa08085c061a6cd52aefe731b0ddada725db1d
[chrome 91.0.4472.106 windows #0-0]
[chrome 91.0.4472.106 windows #0-0] Login : test suite
[chrome 91.0.4472.106 windows #0-0]    ✖ "before all" hook in "Login : test suite"
[chrome 91.0.4472.106 windows #0-0]
[chrome 91.0.4472.106 windows #0-0] 1 failing (52.5s)
[chrome 91.0.4472.106 windows #0-0]
**[chrome 91.0.4472.106 windows #0-0] 1) Login : test suite "before all" hook in "Login : test suite"
[chrome 91.0.4472.106 windows #0-0] waitUntil condition failed with the following reason: POST /session/b7fa08085c061a6cd52aefe731b0ddada725db1d/execute/sync
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'**
System info: host: '150-129-2-46', ip: '150.129.2.46', os.name: 'windows', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: unknown
**[chrome 91.0.4472.106 windows #0-0] Error: waitUntil condition failed with the following reason: POST /session/b7fa08085c061a6cd52aefe731b0ddada725db1d/execute/sync
[chrome 91.0.4472.106 windows #0-0] Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
[chrome 91.0.4472.106 windows #0-0] System info: host: '150-129-2-46', ip: '150.129.2.46', os.name: 'windows', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_181'**
[chrome 91.0.4472.106 windows #0-0] Driver info: driver.version: unknown
[chrome 91.0.4472.106 windows #0-0]     at Context.<anonymous> (/Users/khyati.sehgal/Documents/workspace/july2021/web-app/e2e/src/test/Signin.spec.ts:13:25)


I am getting this error while running my code in Browserstack, the code is running absolutely fine on my local. Any suggestion ?
