### ISSUE TITLE
webdriverjs vs selenium-wedriverjs (question)

### ISSUE THREAD

**Issue by dmitrym0** [webdriverio/webdriverio#138]
Hello everyone,

I apologize in advance if I'm asking stupid questions.

First, this project is in fact different from [selenium-wedriver-js](https://code.google.com/p/selenium/wiki/WebDriverJs) is that correct? The name threw me off for a little while :(

Secondly, how does webdriverio compare to selenium-webdriverjs? selenium-webdriverjs looks very java-y to me, on the other hand I can't quite fiigure out how webdriverio (yours) does async stuff. 

I basically need help choosing one or the other. Thanks!

**Comment by jameseisenhauer** [comment]
curious you and adam wd.js both work at sauce.   Plan to keep 2 webdriver node libs going?

**Comment by christian-bromann** [comment]
I don't know where WD.js is going, I started working on webdriver.io long before I joined sauce and all my work I put in here has nothing in common with the stuff I do at sauce. I am doing this all in my free time and enjoy it to contribute to the open source world ;-)

**Comment by jameseisenhauer** [comment]
thanks for the response and the project looks great!

**Comment by abacaj** [comment]
I know this is rather old and may have been resolved already but your example of using a pause is a really bad practice in the selenium world and leads to inconclusive results, i.e how do you know it takes 5 seconds? 

`  .pause(5000);`

A better approach is to retry with a timeout period, i.e we don't know how long it takes but if it takes more then 30 seconds then there is obviously an issue.

Is there something in place for this type of approach using webdriver IO?

**Comment by christian-bromann** [comment]
Yeah, WebdriverIO has a bunch of waitFor* commands. Check out the API

**Comment by arpit7j** [comment]
Hi Christian , I really need your help. I am very much confused in selecting automation testing stack.
Options 1) Webdriver.IO , Selenium standalone and Cucumber.io  (A JavaScript Approached)    AND
Option 2) WebdriverJS, Selenium JAR and Cucumber JAR (A Java Approached) .

We as a team really had spent a good amount of time and experienced - WebdriverIO is not mature enough as compare to Selenium , Cucumber and Webdriver (java approach) .

I saw your lot of help and comments in the internet and would really appreciate your comments here too.

**Comment by sumeetp4** [comment]
Hi Guys,

I have gone through this thread, but I'm still confused which framework to go for.
I will be testing a mobile application on Android and iOS both, also will be on real devices/simulators.
It will be having need of functions to scroll vertically/horizontally and all.

Please suggest!

Thanks

**Comment by christian-bromann** [comment]
> but I'm still confused which framework to go for.

What am I suppose to say here? I can just recommend to use WebdriverIO. It supports it all.

**Comment by sumeetp4** [comment]
Okay. Thank you @christian-bromann  :)
Do you have any sample code for TouchAction functions?

**Comment by christian-bromann** [comment]
See http://webdriver.io/api/mobile/touchAction.html#Example
