### ISSUE TITLE
[🐛 Bug]: (npm) install fails downstream due to workspace: protocol

### ISSUE THREAD

**Issue by webpro** [webdriverio/webdriverio#13810]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

N/A

### Node.js Version

N/A

### Mode

Standalone Mode

### What happened?

Looks like think this change:

https://github.com/webdriverio/webdriverio/commit/d7c058870f58ef0cce22feacb780cba621b512da#diff-e022b199cd426448e3feb32597cfa9278dcf396d95c9968ca887fba33a9a6774R106-R112

causes issues for e.g. ESLint (but probably many more?) to fail `npm install`:

https://github.com/eslint/eslint/actions/runs/11549810352/job/32143535456

I noticed this by accident in:

https://github.com/webpro-nl/knip/actions/runs/11551181453/job/32147686661#step:7:2

Reason: npm installs peer dependencies by default and apparently the `workspace:*` items haven't been resolved to their latest version when publishing.

### What is your expected behavior?

Peer dependencies should have valid semver version/range

### How to reproduce the bug.

`npm install` on any downstream depending on `@wdio/browser-runner`

### Relevant log output

```typescript
^^ see what happened
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting. This has been fixed in https://github.com/webdriverio/webdriverio/commit/5f49ae36e64f1bac4c7bd7be4b194d2fb0fa62c6 and released in `v9.2.2`

**Comment by webpro** [comment]
That was fast! Any chance you know what happened, is it something others can learn from maybe? Looks like such an easy thing to miss.

**Comment by christian-bromann** [comment]
I moved some dependencies into the `peerDependency` section using pnpm's way to reference workspace packages which apparently doesn't work when defined in the `peerDependency` section. I didn't know that.
