### ISSUE TITLE
Prerun capability not running

### ISSUE THREAD

**Issue by khirakawa** [webdriverio/webdriverio#1382]
## The problem

SauceLabs `prerun` executable does not run using `wdio` runner.

## Environment

* WebdriverIO version: 3.4.0
* Node.js version:4.3.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio test runner
* if wdio testrunner, running synchronous or asynchronous tests: asynchronous
* Additional wdio packages used (if applicable): sauce

## Details

Followed directions [here](https://wiki.saucelabs.com/display/DOCS/Setting+Up+Pre-Run+Executables) to run a script before executing tests on SauceLabs and added a `prerun` object to the `capabilities` object in `wdio.conf.js`:

```
capabilities: [
  {
    browserName: 'internet explorer',
    maxDuration: 3600, // Max timeout of an hour
    platform: 'Windows 7',
    version: '10',
    prerun: {
      executable: 'https://gist.githubusercontent.com/khirakawa/3f6675df017e92f174d97b90afb98e90/raw/de37fada1f1d2955b3823b382b554e4cb89b1767/fix-ie.bat',
      background: 'false'
    }
  }
]
```

However, the script does not run in SauceLabs.

## Link to Selenium/WebdriverIO logs

- Link to actual SauceLabs test: https://saucelabs.com/beta/tests/7bafb8936baf41beacdb21284d58cc1d/commands
- SauceLabs ticket #39631
- Link to selenium-server.log https://gist.github.com/khirakawa/b23fbc352c2479429821eaf80af28671
- Link to log.json https://gist.github.com/khirakawa/566645a15f3b806446ffcced657cbf69

**Comment by Tapin42** [comment]
:+1:

**Comment by kanderek** [comment]
👍

**Comment by nhuhai** [comment]
👍

**Comment by Liliiammm** [comment]
👍

**Comment by khirakawa** [comment]
The `prerun` seems to work if I pass in a string rather than an object:

```
capabilities: [
  {
    browserName: 'internet explorer',
    maxDuration: 3600, // Max timeout of an hour
    platform: 'Windows 7',
    version: '10',
    prerun: 'https://gist.githubusercontent.com/khirakawa/3f6675df017e92f174d97b90afb98e90/raw/de37fada1f1d2955b3823b382b554e4cb89b1767/fix-ie.bat'
  }
]
```

(but then we lose the ability to specify the other `prerun` flags such as `background` 😞 )

**Comment by christian-bromann** [comment]
@khirakawa can you try
```js
capabilities: [
  {
    browserName: 'internet explorer',
    maxDuration: 3600, // Max timeout of an hour
    platform: 'Windows 7',
    version: '10',
    prerun: 'https://gist.githubusercontent.com/khirakawa/3f6675df017e92f174d97b90afb98e90/raw/de37fada1f1d2955b3823b382b554e4cb89b1767/fix-ie.bat'
    background: false
  }
]
```

**Comment by christian-bromann** [comment]
ping @khirakawa

**Comment by khirakawa** [comment]
Apologies for the late response @christian-bromann.  I tried setting `background` as you described, but it didn't seem to have much effect.  However, since `prerun` works just fine in it's string format, we're good to go for now.  Thanks!

**Comment by lalka-workco** [comment]
This is not working for me. Has there been a regression? Using "prerun" with the script provided in the documentation (https://gist.githubusercontent.com/saucyallison/3a73a4e0736e556c990d/raw/d26b0195d48b404628fc12342cb97f1fc5ff58ec/disable_fraud.sh) causes an immediate failure.
