### ISSUE TITLE
Incorrect sessionId when running wdio with multiple instances

### ISSUE THREAD

**Issue by evert0n** [webdriverio/webdriverio#1383]
## The problem

I want to cross reference my tests with sessions Ids in SauceLabs and/or Browserstack using the wdio runner.

Currently the session ID is tracked by each capabilities and not by each test suite, if you are able to run multiple instances it end up with the incorrect session ID.

## Environment

* WebdriverIO version: 4.0.9
* Node.js version: v4.2.4
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable):

## Details

I'm using SauceLabs to demonstrate the issue but the same is true for Browserstack users.

Here I have two tests that will result in failure:
https://github.com/evert0n/webdriverio-bug-session-ids/tree/master/tests/specs

And here is my wdio.conf.js:
https://github.com/evert0n/webdriverio-bug-session-ids/blob/master/wdio.parallel.conf.js
Note that I have `maxInstances` set to 2

I found some custom code in webdriverio that suppose to give you the link to SauceLabs session for all failed tests:
https://github.com/webdriverio/webdriverio/blob/master/lib/utils/ReporterStats.js#L82

When I run my example setup with:
`npm run test_parallel` 

This the full output in my console:
https://gist.github.com/evert0n/360e124ad7f84690fb4c77a20dd9dbce

Two sessions are initialised in "parallel"
https://gist.github.com/evert0n/360e124ad7f84690fb4c77a20dd9dbce#file-wdio-log-txt-L20
https://gist.github.com/evert0n/360e124ad7f84690fb4c77a20dd9dbce#file-wdio-log-txt-L22

And the reporter output gives me the same sessionId for both tests:
https://gist.github.com/evert0n/360e124ad7f84690fb4c77a20dd9dbce#file-wdio-log-txt-L54
https://gist.github.com/evert0n/360e124ad7f84690fb4c77a20dd9dbce#file-wdio-log-txt-L62

The first test should have been linked to the first session initialised "75d3200976344deb94f746beaa4df8da"

I've confirmed that currently sessionIds are tracked along with capabilities but not for each test suite:
https://github.com/webdriverio/webdriverio/blob/master/lib/launcher.js#L130

Before submitting PR I would like to check with you guys if this would be reasonable solution:

Passing the `sessionId` the same way the `cid` is passed to the test assert framework, adding a forth parameter here: https://github.com/webdriverio/webdriverio/blob/master/lib/runner.js#L145
Changing the line to  `this.failures = await this.framework.run(m.cid, config, m.specs, this.caps, global.browser.sessionId)`

I'm currently using mocha so I will take it has an example,

Make it aware of the new param in here:
https://github.com/webdriverio/wdio-mocha-framework/blob/master/lib/adapter.js#L30

Add a new param `sessionId` changing it to: `constructor (cid, config, specs, capabilities, sessionId) {`

Add a new property `this.sessionId = sessionId`

Pass the `sessionId` with every event emitted, adding `message.sessionId = this.sessionId` here:
https://github.com/webdriverio/wdio-mocha-framework/blob/master/lib/adapter.js#L177

I've test this with a custom reporter and it would solve my issue if I use a custom reporter.
But might need some extra work to fix the current SauceLabs link in here:
https://github.com/webdriverio/webdriverio/blob/master/lib/utils/ReporterStats.js#L101

**Comment by christian-bromann** [comment]
@evert0n thanks for reporting. The issue is that the capId only identifies the capability and is not connected to the test. So if you run two spec files with the same capability you most likely will get the sauce link from the last or first running test of that capability. I have a fix prepared that will enhance the capId with a character that is identifying the test. So instead of having cap ids like

0
1
2
3

we will have cap ids like

0a
0b
1a
1b
2a
2b
...

**Comment by evert0n** [comment]
Thank you, looking forward for the fix, if I can help in any way with let me know.

**Comment by christian-bromann** [comment]
This is fixed and will be deployed with the next version (`v4.1.0` I think, no ETA though)

**Comment by Khromchenko** [comment]
Hey @christian-bromann , it seems old but was it fixed and released already?

THanks

**Comment by christian-bromann** [comment]
As you can see in my last comment, yes!
