### ISSUE TITLE
[🐛 Bug]: AddCommand -> Command doesn't exist for all browser

### ISSUE THREAD

**Issue by P-Courteille** [webdriverio/webdriverio#13836]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.0.8

### Node.js Version

22.9.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
export const mobileWebCapabilities = [
    {
        chromeBrowser: {
            hostname: '127.0.0.1',
            "port": 9515,
            "path": "/",
            capabilities: {
                browserName: 'chrome',
                'goog:chromeOptions': {
                    args: ['--start-maximized']
                },
                'webdriver:options': {
                    hostname: '127.0.0.1',
                    port: 41325,
                    path: '/'
                }
            }
        },
        androidDevice: {
            hostname: '127.0.0.1',
            port: 4723,
            path: '/wd/hub',
            capabilities: {
                //Device 1
                ...commonMobileCapabilities,
                "appium:systemPort": 8200,
            }
        }
    }
]
```

### What happened?

If I use addCommand with multiple browser capabilities or at least one named browser, the addCommand is not applied to all browser.

With : 
```
before(() => {
    browser.addCommand('test', async function () {
        console.log('test')
    })
})
```

Current behavior : 
- browser.test() -> Working
- chromeBrowser.test() -> is not a function
- androidDevice.test() -> is not a function

### What is your expected behavior?

The command should be available for all browser so : 
- browser.test() -> Working
- chromeBrowser.test() -> Working
- androidDevice.test() -> Working

### How to reproduce the bug.

1) Use a capabilities with at least one named browser
2) AddCommand on "browser" (not on the name of the browser from step 1)
3) Use the new command chain to browser name from step 1

Issue similar to [this old fixed issue](https://github.com/webdriverio/webdriverio/issues/3445) ?

### Relevant log output

```typescript
androidDevice.test() is not a function
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by P-Courteille** [comment]
According to those subject it's not something new: 

- https://github.com/webdriverio/webdriverio/issues/3939
- https://github.com/webdriverio/webdriverio/issues/2949
- https://github.com/webdriverio/webdriverio/pull/2073
- https://github.com/webdriverio/webdriverio/issues/3445

I still think thats not a really flexible solution. The user should have the possibility to add the command to all the browser at once if it's a global command or just one if he think it's a specific command.

Waiting a better solution, I will try this approach:
https://www.gizra.com/content/wdio-multiremote-tests/

**Comment by christian-bromann** [comment]
@P-Courteille please don't "wait", get involved in the project! We are paying out for each contributions.

**Comment by wswebcreation** [comment]
Related to https://github.com/webdriverio/visual-testing/issues/657, so closing this one
