### ISSUE TITLE
[💡 Feature]: <title> Update @wdio/sauce-service to use sauce-connect version 5

### ISSUE THREAD

**Issue by mknish** [webdriverio/webdriverio#13847]
### Is your feature request related to a problem?

The feature request is related to a problem since saucelabs will be stopping their security & major bug fixes support for sauce connect v4 on the 31st of December 2024. Please see update from [saucelabs](https://docs.saucelabs.com/secure-connections/sauce-connect/lifecycle/) 

### Describe the solution you'd like.

The [saucelabs](https://www.npmjs.com/package/saucelabs) dependency within [@wdio/sauce-service](https://www.npmjs.com/package/@wdio/sauce-service/v/9.2.1?activeTab=readme) package needs to be updated to use sauce connect version 5

### Describe alternatives you've considered.

n/a

### Additional context

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
@mknish mind helping the project and raising a PR?

**Comment by christian-bromann** [comment]
After taking a 2nd look at our [@wdio/sauce-service](https://www.npmjs.com/package/@wdio/sauce-service/v/9.2.1?activeTab=readme) package I realised that we already using the [latest](https://github.com/webdriverio/webdriverio/blob/32a5e8f638a1e021d2414f2e7a513ac6dfcafe82/packages/wdio-sauce-service/package.json#L39) `saucelabs` package version.

**Comment by mknish** [comment]
Hi @christian-bromann, thank you so much for looking in to this. The saucelabs package seems to be using [sc V4.9.1 ](https://www.npmjs.com/package/saucelabs?activeTab=code). Would we need to be in contact with Saucelabs to raise this then?

**Comment by mknish** [comment]
I have received an update from Saucelabs that the WDIO Sauce Service package is owned by WebDriverIO rather than Sauce Labs, so updating this to use the latest version of Sauce Connect would be under the jurisdiction of WDIO.
