### ISSUE TITLE
A way to handle Windows native pop ups

### ISSUE THREAD

**Issue by MikiDavid** [webdriverio/webdriverio#1384]
## The problem

At my app, I have a button that opens a Windows Open prompt (Native), and there I need to choose a folder and click Open.
Then returning to my app and continue.

Is there a way to move focus on to this window and control it (Select a path and click Open)?
If not-
Is there any other cool solution someone can offer?

Thanks.

## Environment

* WebdriverIO version: 4.0.9
* Node.js version: 5.9.1

**Comment by christian-bromann** [comment]
Unfortunately Selenium doesn't provide a way to interact with native dialogs.
