### ISSUE TITLE
webdriverjs-angular page is confusing

### ISSUE THREAD

**Issue by DavidFrahm** [webdriverio/webdriverio#1385]
While evaluating functional testing solutions for AngularJS I came across your page for an angularjs version of webdriverio:

http://webdriver.io/guide/plugins/webdriverjs-angular.html

I spent some time trying to figure out if that is currently maintained, and want to suggest that you either remove the page or explain things better.

My best conclusion is that angular users of webdriverio are finding it unnecessary or not worth the ROI for anything angular-specific, and/or that its even counter-productive for the tests to be specific to the implementation technology.

Is that summary very accurate?

**Comment by christian-bromann** [comment]
Yes, you don't really need the additional stuff to deal with angular pages. We currently working on a service though that helps you with angular pages, gives you access to certain controllers and whatnot. But in general you can test an Angular page like any other page too.
