### ISSUE TITLE
[🐛 Bug]: Node Version ?!

### ISSUE THREAD

**Issue by danichim** [webdriverio/webdriverio#13853]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

v18.17.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
[
  {
    "project": "Button Mobile - Test",
    "build": "Button Mobile Pipeline.BuildNumber",
    "name": "Button Mobile",
    "platformName": "ios",
    "device": "iPhone XR",
    "real_mobile": "true",
    "os_version": "15",
    "app": "BrowserStack.Url",
    "browserstack.debug": true,
    "autoAcceptAlerts": true,
    "webviewConnectTimeout": 5000,
    "browserstack.networkLogs": true,
    "enablePasscode": false
  }
]
```

### What happened?

![image (13)](https://github.com/user-attachments/assets/abf84508-3f12-48ab-aa47-70e66f9ebbfc)

### What is your expected behavior?

Well, to work ?

### How to reproduce the bug.

Just run command 
`npm init wdio@latest .`

### Relevant log output

```typescript
⚠️  Unsupported Node.js Version Error ⚠️
You are using Node.js v18.17.1 which is to old to be used with WebdriverIO.
Please update to Node.js v16 to continue.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@danichim thanks for reporting, this was an oversight and we just fixed the version. The minimum required Node.js version is v18.18.0.
