### ISSUE TITLE
[🐛 Bug]: `switchFrame()` doesn't always accept promise

### ISSUE THREAD

**Issue by gavvvr** [webdriverio/webdriverio#13856]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v9.2.8

### Node.js Version

v22.6.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
    browserName: 'electron',
    browserVersion: '33.0.0',
    'wdio:electronServiceOptions': {
        appArgs: []
    }
}
```

### What happened?

The `await browser.switchFrame($('iframe'))` will fail in Electron app test setup with `wdio-electron-service` with the following error:
> WebDriverError: invalid argument: missing 'ELEMENT'

### What is your expected behavior?

Based on [`switchFrame()`](https://webdriver.io/docs/api/browser/switchFrame/) WDIO docs and [existing test](https://github.com/webdriverio/webdriverio/blob/v9.2.10/e2e/wdio/headless/test.e2e.ts#L517-L526) in E2E test suite, the following construct should work with no errors:

```javascript
await browser.switchFrame($('iframe'))
```

### How to reproduce the bug.

Here is the repo to reproduce the problem: https://github.com/gavvvr/wdio-electron-service-818

### Relevant log output

```typescript
[0-0] 2024-11-05T22:00:38.362Z ERROR webdriver: WebDriverError: invalid argument: missing 'ELEMENT'
[0-0]   (Session info: chrome=130.0.6723.59) when running "frame" with method "POST" and args "{"id":{}}"
[0-0] invalid argument in "My Login application.should reset the frame when the page is reloaded"
invalid argument: WebDriverError: invalid argument: missing 'ELEMENT'
  (Session info: chrome=130.0.6723.59) when running "frame" with method "POST" and args "{"id":{}}"
    at async Context.<anonymous> (/Users/user/Documents/sandboxes/wdio-electron-iframe-ts/test/specs/test.e2e.ts:4:5
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by gavvvr** [comment]
Initially I've opened a webdriverio-community/wdio-electron-service#818, but after some debugging I can see that it's rather a problem of `switchFrame()` implementation of primary webdriverio codebase.

The `browser.switchFrame()` call coming from `wdio-electron-service`-based test get into the following branch and `context` will be passed to `switchToFrame()` without promise resolution:
https://github.com/webdriverio/webdriverio/blob/5253860388668c3e4b7761a1151b5d9bd82e2c3d/packages/webdriverio/src/commands/browser/switchFrame.ts#L76-L84

So, I think it should rather be fixed in this repository.

**Comment by erwinheitzman** [comment]
Hi there, I think that awaiting the promise is the quickest and easiest solution for now but I do feel like we can/should support this indeed 👍

**Comment by gavvvr** [comment]
@erwinheitzman, yeah, that's what I do as a workaround. But I would like to note that TypeScript doesn't agree with me that the result of `$(...)` can be awaited:
<img width="832" alt="image" src="https://github.com/user-attachments/assets/8e6eca89-0701-4dbf-89ec-a711c5599258">

That's probably another bug with types (let me know if I should report it too), the object returned from `$(...)` obviously has `.then()` at runtime.

**Comment by goosewobbler** [comment]
I'd like to note that there's some inconsistency in the docs here: In most of the docs, e.g. the [selectors examples](https://webdriver.io/docs/selectors/) `$(...)` is used with `await`, but in the best practices it says that ["You should always use await with the exception of the $ and $$ command."](https://webdriver.io/docs/bestpractices#lazy-loading-and-promise-chaining).

**Comment by erwinheitzman** [comment]
@goosewobbler with v9 we introduced the .getElement method on the Element object which you can use to make TS stop complaining 🙂
I'm sure there will be leftovers pieces in the docs that we could update but why not contribute those documentation changes to the project? It is an easy way to get involved 😉

**Comment by goosewobbler** [comment]
@erwinheitzman so you would suggest the following?

```
switchFrame($('iframe').getElement())
```

My WDIO bandwidth is currently occupied with getting back into https://github.com/webdriverio-community/wdio-electron-service/issues/308, but I'll see if I can fit it in!

**Comment by erwinheitzman** [comment]
@goosewobbler yes but with the awaited added as well 👍

**Comment by christian-bromann** [comment]
> but in the best practices it says that ["You should always use await with the exception of the $ and $$ command."](https://webdriver.io/docs/bestpractices#lazy-loading-and-promise-chaining).

This has changed in v9 and we haven't really fully cleaned up our docs. Elements don't need to be awaited anymore.

Anyway, `switchFrame` should work with `switchFrame($('iframe'))` and I thought I'd have tested that.
