### ISSUE TITLE
Integrate Mochawesome as custom reporter

### ISSUE THREAD

**Issue by ponmudivn** [webdriverio/webdriverio#1387]
## Integrate Mochawesome as custom reporter

How could i integrate Mochawesome as custom reporter with my wdio.
I know i have Allure reporter which is pretty much good. But i need Mochawesome  reports as the clients requested it.

thanks & regards

**Comment by patthiel** [comment]
This [doc](http://webdriver.io/guide/reporters/customreporter.html) from the guide will definitely be of some help.

Also, you could reference the [team city custom reporter](https://github.com/sullenor/wdio-teamcity-reporter) if you need an example.

**Comment by ponmudivn** [comment]
Im getting following error when trying to add simple custom report as mentioned in the link

> Error: Custom reporters must export a unique 'reporterName' property

**Comment by christian-bromann** [comment]
You need to provide a `reporterName` property, depending on how you write your reporter is should look like:

```js
function myCustomReporter () {...}
myCustomReporter.reporterName = "myReporterName";
```
