### ISSUE TITLE
[🐛 Bug]: browser.getPuppeteer() doesn't work.  WDIO doesn't see "puppeteer-core" package

### ISSUE THREAD

**Issue by Yurii397** [webdriverio/webdriverio#13873]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.2.11

### Node.js Version

v20.16.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [
    {
      maxInstances: 1,
      browserName: 'chrome',
      browserVersion: 'stable'
      'goog:chromeOptions': {
        args: [
          '--headless=new',
          '--disable-gpu',
          '--disable-impl-side-painting',
          '--disable-gpu-sandbox',
          '--disable-accelerated-2d-canvas',
          '--disable-accelerated-jpeg-decoding',
          '--disable-dev-shm-usage',
          '--no-sandbox',
          'window-size=1920,1080',
          '--no-sandbox'
        ],
        prefs: {
          download: {
            directory_upgrade: true,
            prompt_for_download: false,
            default_directory: global.downloadFolder,
          },
        },
      },
    },
  ],
```

### What happened?

I'm trying to migrate from v8 to v9 and faced with issue that the puppeteer browser doesn't get. The following error is shown.
Error: Couldn't import "puppeteer-core"! Do you have it installed? If not run "npm install puppeteer-core"!
<img width="1523" alt="Screenshot 2024-11-11 at 19 32 06" src="https://github.com/user-attachments/assets/fa44aeff-59e1-4fab-8239-cc0341de9438">

At the same time, this package is present in `node_modules`
 
 

### How to reproduce the bug.

install 
    "@wdio/cli": "^9.2.11",
    "@wdio/cucumber-framework": "^9.2.8",
    "@wdio/local-runner": "^9.2.11",
    "@wdio/spec-reporter": "^9.2.8",
    "@wdio/types": "^9.2.2",

### Relevant log output

```typescript
[0-0] Error in "0: And get Puppeteer browser"
Error: Couldn't import "puppeteer-core"! Do you have it installed? If not run "npm install puppeteer-core"!
    at userImport (file:///Users/Yurii_Kudriavtsev/WebstormProjects/t3d/node_modules/@wdio/utils/build/index.js:238:11)
    at Browser.getPuppeteer (file:///Users/Yurii_Kudriavtsev/WebstormProjects/t3d/node_modules/webdriverio/build/index.js:3198:21)
    at Browser.wrapCommandFn (file:///Users/Yurii_Kudriavtsev/WebstormProjects/t3d/node_modules/@wdio/utils/build/index.js:884:23)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@Yurii397 with v9 `puppeteer-core` became a peer dependency and you need to have it installed. I am not sure why it is not able to find it when you say that you indeed see it being installed. Mind sharing a reproduction case?

**Comment by Yurii397** [comment]
hmm, the 'puppeteer-core' wasn't added to the yarn.lock - that's strange

**Comment by christian-bromann** [comment]
After adding it to your `package.json` you have to run `yarn install` to ensure the dependency gets installed and added to the `yarn.lock` file. This is important in CI when you install deps via frozen lockfile. I will go ahead and close the issue as it doesn't seem to be related to WebdriverIO. Let me know if you have further questions.

**Comment by Yurii397** [comment]
> After adding it to your `package.json` you have to run `yarn install` to ensure the dependency gets installed and added to the `yarn.lock` file. This is important in CI when you install deps via frozen lockfile. I will go ahead and close the issue as it doesn't seem to be related to WebdriverIO. Let me know if you have further questions.

sure, I ran 'yarn install' install every time.
