### ISSUE TITLE
[💡 Feature]: Add possibility to use Selenium command pattern, such as findElement, sendKeys, etc... to automate both mobile and web

### ISSUE THREAD

**Issue by paulohvalipio** [webdriverio/webdriverio#13877]
### Is your feature request related to a problem?

I currently use the selenium-appium library with webdriverio, but it is outdated and does not allow the use of more devices and I would like to use just webdriverio.

### Describe the solution you'd like.

Provide a new driver that allows the use of Selenium commands, such as findElement, sendKeys, etc..., for automation with webdriverio.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by erwinheitzman** [comment]
Hi there, you can already use all of these directly if you want: https://webdriver.io/docs/api/selenium

**Comment by erwinheitzman** [comment]
That said, WebdriverIO uses these commands under the hood and I would recommend using those instead as they often solve challenges that you'd otherwise have to work around yourself

**Comment by christian-bromann** [comment]
> that allows the use of Selenium commands

What commands are you referring to? Selenium as well as WebdriverIO us common WebDriver commands.

**Comment by paulohvalipio** [comment]
@christian-bromann, commands according to the Selenium standard, such as findElement, findElements, click, sendKeys, clear, etc.... like those available in the links:

https://www.selenium.dev/documentation/webdriver/elements/finders/
https://www.selenium.dev/documentation/webdriver/elements/interactions/

**Comment by christian-bromann** [comment]
These are all available in WebdriverIO already:

- [`findElement`](https://webdriver.io/docs/api/webdriver#findelement) but it is better to use [`$`](https://webdriver.io/docs/api/browser/$)
- [`findElements`](https://webdriver.io/docs/api/webdriver#findelements) but it is better to use [`$$`](https://webdriver.io/docs/api/browser/$)
- https://webdriver.io/docs/api/browser/keys
- [`clearValue`](https://webdriver.io/docs/api/element/clearValue)

Please note: there is __no__ Selenium standard. Selenium as well as WebdriverIO use the [WebDriver](https://www.w3.org/TR/webdriver2/) protocol. Please take a close look at the WebdriverIO [API](https://webdriver.io/docs/api) and let us know if you are missing any commands. I will go ahead and close the issue.
