### ISSUE TITLE
Typo in Guide

### ISSUE THREAD

**Issue by BillyZac** [webdriverio/webdriverio#1388]
## The problem

The final line in the [Getting Started Guide](http://webdriver.io/guide.html) reads: 

```
$ ./node_modules/.bin/wdio wdio.config.js
```

This throws an error, because there is no config.js. The following code worked for me:

```
$ ./node_modules/.bin/wdio wdio.conf.js
```

## P.S.

I noticed that this seems to be fixed [in the repo](https://github.com/webdriverio/webdriverio/blob/a7f50b5bf91edd45d6c81c0514b2a38f48485b46/docs/guide.md). I saw the issue on the website, [here](http://webdriver.io/guide.html).

**Comment by christian-bromann** [comment]
Thanks for notifying we will update the website soon!
