### ISSUE TITLE
[🐛 Bug]: Appium + WebdriverIO+cucumber - hooks is showing failed by default in Allure report

### ISSUE THREAD

**Issue by Krithikmano** [webdriverio/webdriverio#13884]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.2.14"

### Node.js Version

v23.2.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
      'appium:platformName': 'Android',
      'appium:deviceName': 'Pixel 6',
      'appium:platformVersion': '14',
      'appium:automationName': 'UIAutomator2',
      'appium:udid': '23291FDF600439',
      'appium:app': path.join(
        process.cwd(),
        'app/android/' + 'netflix.apk'
      ),
      'appium:appActivity':
      ApplicationConstants.MOBILE_APP.ANDROID.APP_ACTIVITY,
      'appium:appPackage': ApplicationConstants.MOBILE_APP.ANDROID.APP_PACKAGE,
      'appium:noReset': false, // treu-This tells Appium to uninstall and reinstall the app
      //
      //'appium:noReset': true,
    }
```

### What happened?

I successfully ran the automation scripts for mobile and was able to generate the Allure report. However, the report always shows that the hooks have failed.
All test cases passed, yet the hooks still show failures and the result is not 100%.

### What is your expected behavior?

Hooks failures should not show in the report

### How to reproduce the bug.

Steps to reproduce

1. import this project from https://github.com/Krithikmano/MobileAutomation
2. run npm install command
3. Open config/wdio.conf_android_local.ts file and update the below capabilities what android device you are using
      'appium:platformName': 'Android',
      'appium:deviceName': 'Pixel 6',
      'appium:platformVersion': '14',
      'appium:udid': '23291FDF60049',
4. open the terminal run **npm run android"
5. This will run and generate the allure report and will be displayed like below
6. Allure report and allure results are stored in the report folder

Note: udid  -  This info you will get it using **adb devices* command from terminal

### Relevant log output

```typescript
[0-0] successfully Terminate the app at end of each test case
[0-0] 2024-11-17T05:26:03.438Z INFO webdriver: COMMAND deleteSession()
[0-0] 2024-11-17T05:26:03.438Z INFO webdriver: [DELETE] http://127.0.0.1:4723/session/623e14d4-b00c-49e5-b49d-a85ccf44d707
[0-0] 2024-11-17T05:26:03.694Z INFO webdriver: RESULT null
[0-0] PASSED in Android - file:///e2e/features/android/AndroidLogin.feature
2024-11-17T05:26:03.817Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2024-11-17T05:26:03.817Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2024-11-17T05:26:03.817Z INFO @wdio/local-runner: Start worker 0-1 with arg: run ./config/wdio.conf_android_local.ts --cucumberOpts.tags=@android
[0-1] 2024-11-17T05:26:04.145Z INFO @wdio/local-runner: Run worker command: run
2024-11-17T05:26:04.467Z INFO @wdio/cli: [0-1] SKIPPED in Android - file:///e2e/features/ios/IosLogin.feature
2024-11-17T05:26:04.467Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2024-11-17T05:26:04.467Z INFO @wdio/cli:launcher: Run onComplete hook
2024-11-17T05:26:04.467Z INFO @wdio/appium-service: Killing entire Appium tree

Spec Files:      1 passed, 1 skipped, 2 total (100% completed) in 00:00:22  

2024-11-17T05:26:04.471Z INFO @wdio/local-runner: Shutting down spawned worker
2024-11-17T05:26:04.491Z INFO @wdio/appium-service: Process and its children successfully terminated
2024-11-17T05:26:04.723Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2024-11-17T05:26:04.723Z INFO @wdio/local-runner: shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by BorisOsipov** [comment]
@Krithikmano 
`import this project from https://github.com/Krithikmano/MobileAutomation` 

I can hardly believe that anyone would try to figure this out using this repository - there is too much unnecessary stuff in there.
I can't even find where the hooks are in the codebase for the first look.

It will be nice to prepare a short version via [WebdriverIO Starter Toolkit](https://webdriver.io/docs/gettingstarted#initiate-a-webdriverio-setup) and add only the code that makes the problem happen.

**Comment by automationtoolshub** [comment]
@BorisOsipov I kept a separate file for hooks, which is located at e2e/hooks/hooks.ts.

**Comment by BorisOsipov** [comment]
I will go ahead and close this issue - there is no problem with the `useCucumberStepReporter:true` reporter option. Soon it will be a default option and the option will be removed, I don't see the point in fixing a problem in a mode that will be removed soon.

**Comment by varshanharshank** [comment]
@BorisOsipov  Thanks for the update. After adding this  one useCucumberStepReporter:true , i am not seeing hooks failed in the report.

**Comment by nayvzve** [comment]
Im facing this issue even using useCucumberStepReporter:true, I have several hooks but only failing on the afterScenario. Any ideas @BorisOsipov?

**Comment by trvtuan** [comment]
I have the same issue. Despite that I turned off or comment all hooks but it is still giving empty failed hook in the report
I'm using 9.19.2 latest version of allure report.
"@wdio/allure-reporter": "^9.19.2",
    "@wdio/appium-service": "^9.19.2",

Could be versioning is conflicting? or specific wdio is required to avoid this?

UPD: this thread https://github.com/orgs/allure-framework/discussions/2614 gives a solution. Just need to disable mochaHooks
