### ISSUE TITLE
[💡 Feature]: Cache Allure report attachements

### ISSUE THREAD

**Issue by aviralpostman** [webdriverio/webdriverio#13881]
### Is your feature request related to a problem?

Attachments in allure report are downloaded on the fly whenever expanded & this takes time when the attachments are large.

Also, for some weird reason, this download is super slow on circle-ci. So, it might be a allure-performance issue wrt to downloading files as well.

### Describe the solution you'd like.

I would like these attachments to be cached in an ideal situation.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BorisOsipov** [comment]
The wdio-allure-reporter is responsible for generating allure-results files, which are used to create HTML report data.

The reporter itself does not have a mechanism to 'cache' anything, as it is not responsible for how you download\view report and attachments after they are generated to report.

>Also, for some weird reason, this download is super slow on circle-ci.
>I would like these attachments to be cached in an ideal situation.

You probably need to investigate why it's so slow and find a way to improve it.

**Comment by erwinheitzman** [comment]
I agree with Boris, if you want to cache the attachments this is part of your pipeline (CI/CD) configuration.

**Comment by christian-bromann** [comment]
Closing as this doesn't seem to be anything we can fix in WebdriverIO.
