### ISSUE TITLE
[🐛 Bug]: Appium + WebdriverIO+cucumber + Allure - Widget/Summary.json file not showing correct pass and fail numbers

### ISSUE THREAD

**Issue by Krithikmano** [webdriverio/webdriverio#13885]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.2.14

### Node.js Version

v23.2.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
      'appium:platformName': 'Android',
      'appium:deviceName': 'Pixel 6',
      'appium:platformVersion': '14',
      'appium:automationName': 'UIAutomator2',
      'appium:udid': '23291FDF600439',
      'appium:app': path.join(
        process.cwd(),
        'app/android/' + 'netflix.apk'
      ),
      'appium:appActivity':
      ApplicationConstants.MOBILE_APP.ANDROID.APP_ACTIVITY,
      'appium:appPackage': ApplicationConstants.MOBILE_APP.ANDROID.APP_PACKAGE,
      'appium:noReset': false, // treu-This tells Appium to uninstall and reinstall the app
      //
      //'appium:noReset': true,
    }
```

### What happened?

I successfully ran the mobile scripts and generated the Allure report. However, when I checked the total pass and fail test case counts in the summary.json file (located in allure-report/widgets/summary.json), it showed incorrect values.

Example :The expected result in the summary.json file is a total test case count of 2. However, it is showing 8 instead of 2, as it counts feature steps and hooks.

    @android
    Scenario Outline: Netflix Logiin with <emailAddress>
        Given Load the Application for android
        Then Click Sign in Option for android
        Then Enter "<emailAddress>" in the email or phonumber text box for android

        Examples:
           |emailAddress|
           |test1@gmail.com|
           |test2@gmail.com|
           
           
<img width="396" alt="image" src="https://github.com/user-attachments/assets/a6b42271-2389-494e-8e45-f9b3ddb18bb6">

           
          
<img width="1086" alt="image" src="https://github.com/user-attachments/assets/b6c254fc-9e16-495c-9262-2ac93050346b">

### What is your expected behavior?

Summary.json should show total number of scenarios instead of counting steps.

### How to reproduce the bug.

Steps to reproduce

1. import this project from https://github.com/Krithikmano/MobileAutomation
2. run npm install command
3. Open config/wdio.conf_android_local.ts file and update the below capabilities what android device you are using
'appium:platformName': 'Android',
'appium:deviceName': 'Pixel 6',
'appium:platformVersion': '14',
'appium:udid': '23291FDF60049',
4. open the terminal run **npm run android"
5. This will run and generate the allure report and will be displayed like below
6. Allure report and allure results are stored in the report folder

Note: udid - This info you will get it using *adb devices command from terminal

### Relevant log output

```typescript
{"reportName":"Allure Report","testRuns":[],"statistic":{"failed":2,"broken":0,"skipped":0,"passed":6,"unknown":0,"total":8},"time":{"start":1731821150127,"stop":1731821163435,"duration":13308,"minDuration":0,"maxDuration":5444,"sumDuration":12434}}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by BorisOsipov** [comment]
>Summary.json should show total number of scenarios instead of counting steps.

use `useCucumberStepReporter:true ` reporter config option.
