### ISSUE TITLE
[🐛 Bug]: Runner ignores maxInstances as a parameter of capabilities on wdio v9

### ISSUE THREAD

**Issue by robinzzzzzon** [webdriverio/webdriverio#13897]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.2.14

### Node.js Version

v20.14.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [{
  browserName: 'chrome',
    'goog:chromeOptions': {
      args: [
        '--no-sandbox',
        '--ignore-certificate-errors',
        '--disable-infobars',
        '--headless',
        '--disable-gpu',
        '--enable-features=NetworkService,NetworkServiceInProcess',
        '--disable-dev-shm-usage',
        '--use-fake-ui-for-media-stream',
        '--use-fake-device-for-media-stream',
      ],
    },
    maxInstances: 1,
    specs: ['./source/tests/specs/*.spec.mjs'],
  }]
```

### What happened?

According to wdio docs it is possible to set count of instances as maxInstances parameter right into capabilities instead of setting it as a wdio config parameter. It worked fine for me on v8 where I could define a few objects with different maxInstances and spec folders. But after updating version v8(for example 8.32.2 or 8.40.6) to 9.2.14, runner starts to ignore value of maxInstances if I set it via capabilities just running all of my tests simultaneously instead. MaxInstances as not a capabilities parameter works correctly.

One more thing I would mention here(I can split current behavior on two issues as you wish):
If set a path of specs also in capabilities, then runner find specs correctly but in console you will see 0 count of workers:
 
<img width="676" alt="console attach" src="https://github.com/user-attachments/assets/146d8842-69c7-440a-83d9-2c439f021bbe">

### What is your expected behavior?

No difference whether I would set these parameters as a part of capabilities object or right as parameters of wdio config

### How to reproduce the bug.

For reproducing this bug you need have more than 1 specs ready for running
1. set a wdio.conf.mjs as this configuration:
```
export const config = {
  runner: 'local',
  services: [['intercept'], ['shared-store']],
  reporters: ['spec'],
  capabilities: [{
  browserName: 'chrome',
    'goog:chromeOptions': {
      args: [
        '--no-sandbox',
        '--ignore-certificate-errors',
        '--disable-infobars',
        '--headless',
        '--disable-gpu',
        '--enable-features=NetworkService,NetworkServiceInProcess',
        '--disable-dev-shm-usage',
        '--use-fake-ui-for-media-stream',
        '--use-fake-device-for-media-stream',
      ],
    },
    maxInstances: 1,
    specs: ['./source/tests/specs/*.spec.mjs'],
  }],
  exclude: [],
  logLevel: 'error',
  coloredLogs: true,
  bail: 0,
  waitforTimeout: 10000,
  connectionRetryTimeout: 20000,
  connectionRetryCount: 2,
  framework: 'mocha',
  mochaOpts: {
    ui: 'bdd',
    timeout: 30000,
  },

  before(/* capabilities, specs */) {
    global.browser.maximizeWindow()
  },
}
```
2. run tests

### Relevant log output

```typescript
Execution of 0 workers started at 2024-11-19T21:30:03.807Z

[0-1] RUNNING in chrome - file:///source/tests/specs/2.Second.spec.mjs
[0-3] RUNNING in chrome - file:///source/tests/specs/4.Fourth.spec.mjs
[0-0] RUNNING in chrome - file:///source/tests/specs/1.First.spec.mjs
[0-2] RUNNING in chrome - file:///source/tests/specs/3.Third.spec.mjs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Just to clarify the expected behavior: `maxInstances` on the configuration level defines the maximum amount of parallel sessions/worker WebdriverIO is allowed to spin up. For example: if you have 3 capabilities, e.g. Chrome, Firefox and Safari and 3 spec files, when setting `maxInstances` to `5` you should only see 5 total test in parallel.

-> 2 Chrome sessions, 2 Firefox sessions and 1 Safari session

On the other side, if you set maxInstances on the capability level you should only see x amount of parallel capabilities spin up at once. For example: if you have 3 capabilities, e.g. Chrome, Firefox and Safari and 3 spec files, if you have unlimited maxInstances on the capability level but `wdio:maxInstances` set on the Chrome capability to 2, then you get

-> 2 Chrome sessions, 3 Firefox sessions and 3 Safari sessions
-> any Chrome session ended, it spins up another Chrome session for the 3rd spec file

**Comment by robinzzzzzon** [comment]
Thanks a lot for such a detailed explanation! 
So, this feature I mean an ability to set maxInstances and specs on the capabilities level is absolutely vital on my current working project because of having a part of specs which require mutually exclusive settings of a database. By splitting our specs on e.g. two capabilities we get two independent streams one of them run our tests concurrently("db tests") and another in parallel mode.

**Comment by christian-bromann** [comment]
Looking at your capabilities, it seems you have used the capability name `maxInstances` which is invalid in v9 as it is not a valid capability that conforms with the WebDriver protocol. Instead when passing in this option within the capabilities, use `wdio:maxInstances`. I will try to update the docs to make this more clear. Let me know if you have further questions.

**Comment by robinzzzzzon** [comment]
@christian-bromann, I checked it with new naming and it has been worked correctly what comes to wdio:maxInstances and wdio:specs as well.
Thank you for clarifying situation and tuning docs.
