### ISSUE TITLE
[💡 Feature]: Update Cucumber to >= 10.8.0 to support `world` and `context` to allow accessing state from arrow functions

### ISSUE THREAD

**Issue by htho** [webdriverio/webdriverio#13908]
### Is your feature request related to a problem?

In order to work with state, I can not use arrow functions to define steps, because they don't provide the proper `this` value.

### Describe the solution you'd like.

I want to use the new `world` and `context` exports from cucumber to access state from arrow functions.

### Describe alternatives you've considered.

I have to use the old and tedious `function` syntax - which is not even endorsed by Cucumbers vscode extension.

### Additional context

The feature is added in [10.8.0](https://github.com/cucumber/cucumber-js/blob/main/CHANGELOG.md#1080---2024-05-26).
The next non-breaking minor version is [10.9.0](https://github.com/cucumber/cucumber-js/blob/main/CHANGELOG.md#1090---2024-08-13).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
@htho thanks for raising the issue.

WebdriverIO supports the latest version of Cucumber, you can already use these primitives by importing them via:

```ts
import { world, context } from '@cucumber/cucumber'
```

I raised a PR so you can import these primitives from the WebdriverIO Cucumber framework.
