### ISSUE TITLE
Could not set cookies in beforeHook

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1391]
### config.js

```js
beforeHook () {
   browser.setCookie({ name: 'foo', value: 'bar' });
},

afterHook () {
   browser.deleteCookie();
}
```

### test.js

```js
describe('TESTMAIL-8674', () => {
	it('Авторизация', () => {
		browser.url('/messages/inbox');
		console.log(browser.getCookie());

		/*
			[
				{
					path    : '/',
					domain  : '.mail.ru',
					name    : 'mrcu',
					httpOnly: false,
					expiry  : 1781454591,
					hCode   : 3359959,
					secure  : false,
					value   : 'E29D5762D3FF7C61B1309CF506B9',
					class   : 'org.openqa.selenium.Cookie'
				}
			]
		*/
	});
});
```

How to set cookies using `beforeHook`?

**Comment by christian-bromann** [comment]
Please make sure you are on a page where you want to set an url. You can't set cookies for an arbitrary page on a about:blank page.

**Comment by salvag-ntt** [comment]
Would you be able to suggest a strategy to set the cookies before the page load? I need to test a scenario where the user accepts the cookies with the popup showing up and one without the banner showing up. In cypress I could do this quite easily by setting the cookies in the before callback. That allows the page to load without the banner appearing.

**Comment by christian-bromann** [comment]
There are two options:

- go on an arbitrary page with the same hostname and set the cookie (can be a 404 page or a test page that is only available in your test environment)
- You can use the `getPuppeteer` command to [overwrite headers](https://pptr.dev/api/puppeteer.continuerequestoverrides)  for the request

The 1st option is the most feasible one and should probably work also for your use case. We have [an issue](https://github.com/webdriverio/webdriverio/issues/6361) to provide a better interface for this. You are welcome to contribute. Cheers!
