### ISSUE TITLE
PhantomJS: Can only set Cookies for the current domain

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1392]
```js
browser.setCookie({
    name: 'foo',
    value: 'bar'
});
```

> Can only set Cookies for the current domain

Solution:

```js
browser.setCookie({
    name: 'foo',
    value: 'bar',
    domain: '.mail.ru'
});
```

Based on JsonWireProtocol `expiry` and `domain` should be [optional](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#cookie-json-object).
The problem is located [here](https://github.com/ariya/phantomjs/blob/master/src/ghostdriver/request_handlers/session_request_handler.js#L775).

Can we fix it?

**Comment by christian-bromann** [comment]
Feel free to open a PR in the PhantomJS project. I don't think this is an issue of WebdriverIO though.
