### ISSUE TITLE
Selenium "Element is no longer attached to the DOM" error not bubbled up, causes infinite loop

### ISSUE THREAD

**Issue by sean-lynch** [webdriverio/webdriverio#1396]
## The problem

Some functions such as `isSelected()` treat "Element is no longer attached to the DOM" error as transient and automatically retry when encountered. 

This is problematic if the element was actually removed as it will cause the test to timeout without notifying the developer why. 
## Links
- https://gist.github.com/sean-lynch/dc9b94e55d704bc5084fe3568b8c74ee - Logs from both wdio and Selenium Server, as well an example spec and the wdio configuration
- Chat logs of the attempt to diagnose the issue - https://gitter.im/webdriverio/webdriverio?at=5766fffcf0528c4c5bba833c
## Environment
- WebdriverIO version: 4.0.9
- Node.js version: 0.12.0
- [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
- if wdio testrunner, running synchronous or asynchronous tests: synchronous
- Additional wdio packages used (if applicable): wdio-selenium-standalone-service
## Details

In order to reproduce, the DOM element being clicked must destroy and replace itself with a new DOM element. This may seem strange, but is an increasingly common side effect of events in JS frameworks such as react.
## Code To Reproduce Issue [ Good To Have ]

This assumes it is running against a page that includes that DOM structure, and checking the checkbox will replace itself with a new DOM element.

```
suite 'Tasklist', ->
    test 'click should be persistent', ->
        browser.url '/'

        # This works
        browser.click('#todo-list .task .check')
        assert.isTrue browser.element('#todo-list .task .check').isSelected()

        # This doesn't
        taskCheckbox = browser.element('#todo-list .task .check')
        taskCheckbox.click()
        assert.isTrue taskCheckbox.isSelected()
```

**Comment by christian-bromann** [comment]
@sean-lynch is there any chance you could create a small backbone app that allows us to reproduce the issue?

**Comment by sean-lynch** [comment]
Ooops, sure thing! 

https://github.com/sean-lynch/wdio-dom-change-test

Uses simple bit of jquery to do the DOM element replacement instead of backbone but still shows the same error. Let me know if you have issues getting it to run.

**Comment by CTaylor1118** [comment]
@sean-lynch Do you have a good way to recover from this? I think I am experiencing randomly this but I am not sure how to make sure the process does not crash.

**Comment by sean-lynch** [comment]
@CTaylor1118 hmm I didn't find a way to recover from this (other than avoiding it completely by re-creating the element reference.

**Comment by CTaylor1118** [comment]
@christian-bromann Part of the problem here is at https://github.com/webdriverio/webdriverio/blob/master/lib/webdriverio.js#L121
and 
https://github.com/webdriverio/webdriverio/blob/master/lib/helpers/errorHandler.js#L14

The error handler expects this to be the client but the context is passed into the call so if a stale element error occurs fails though passing the client does not resolve the issue with the uncaught error.

**Comment by christian-bromann** [comment]
@sean-lynch please try with the latest version, it should be fixed now.
