### ISSUE TITLE
[🐛 Bug]: <title> webdriverio will wait for the countdown finished，then input the text.

### ISSUE THREAD

**Issue by tlqiao** [webdriverio/webdriverio#13969]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.4.1

### Node.js Version

v23.3.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
            platformName: "Android",
            "wdio:maxInstances": 1,
            "appium:deviceName": "127.0.0.1:6555",
            "appium:platformVersion": "11.0",
            "appium:orientation": "PORTRAIT",
            "appium:automationName": "UiAutomator2",
            "appium:appWaitActivity": "xxx",
            "appium:newCommandTimeout": 240
        },
```

### What happened?

I login a mobile app in android simulator, it need to verification code，there is countdown which is 60 seconds. webdriverio will wait for the countdown finished, then input the verification code.
<img width="1545" alt="image" src="https://github.com/user-attachments/assets/50ee8b2d-0853-45e0-94db-64702fb760d5" />

### What is your expected behavior?

Hope can input the verification code after it identify the element. as you can see, it has find the element, but because the countdown is still in progress, so the webdriver wait.

### How to reproduce the bug.

It is our inside app，it is a little difficult to reproduce in your side.

### Relevant log output

```typescript
no log, it just wait.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@tlqiao thanks for raising the issue.

I am not sure what you referring to when saying `there is countdown which is 60 seconds`, I would generally recommend to use `browser.waitUntil` and use the callback to query the element with the countdown and verify when the countdown is done, e.g. use `getText` on the element displaying the number or verify whether a certain element appears/disappears. Another option is to just call `browser.pause(60 * 1000)` which would be a hard wait but would do the job if the countdown is always 60s.

Please join our [Discord channel](https://discord.webdriver.io) for questions like that in the future, thanks!
