### ISSUE TITLE
How to set appium caps in wdio

### ISSUE THREAD

**Issue by saikrishna321** [webdriverio/webdriverio#1397]
@christian-bromann i'm struggling to figure out how to set the appium desire caps in wdio config.js

var options = {
    desiredCapabilities: {
    	platformName: 'android',                        // operating system
    	platformVersion:'4.3',                          // OS version
        browserName: 'chrome',                          // browser
        udid: 'asdfasdfasdf',                           // udid of the android device
		deviceName: 'devicexy',                         // device name
    },
    host: 'localhost',                                  // localhost
    port: 4723                                          // port for appium
};

i need the above to be set something here 
https://github.com/webdriverio/webdriverio/blob/master/examples/wdio/wdio.mocha.conf.js#L23

* Can i start appium server within the code?

**Comment by christian-bromann** [comment]
> Can i start appium server within the code?

No, we will probably create a `wdio-appium-service` that will start the appium server for you but we don't have that now. You need to start the server manually.
