### ISSUE TITLE
[🐛 Bug]: Unstable retrieval of browsers in CI

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#13971]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

20

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  browserName: 'firefox'
}
```

### What happened?

Running tests in CI today threw an error:

```
Error: Error: Couldn't find a matching firefox browser for tag "nightly_135.0a1" on platform "linux"

    at setupPuppeteerBrowser (file://dir/e2e/node_modules/@wdio/utils/build/node.js:158:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async Promise.all (index 1)
    at async Launcher.run (file://dir/e2e/node_modules/@wdio/cli/build/index.js:2278:7)
    at async Module.run (file://dir/e2e/node_modules/@wdio/cli/build/index.js:3302:16)

Error: Couldn't find a matching firefox browser for tag "nightly_135.0a1" on platform "linux"
    at setupPuppeteerBrowser (file://dir/e2e/node_modules/@wdio/utils/build/node.js:158:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async Promise.all (index 1)
    at async Launcher.run (file://dir/e2e/node_modules/@wdio/cli/build/index.js:2278:7)
    at async Module.run (file://dir/e2e/node_modules/@wdio/cli/build/index.js:3302:16)
```

### What is your expected behavior?

Fail gracefully, continue testing, fallback to another available version.

### How to reproduce the bug.

Use given capabilities and run on linux with firefox.

### Relevant log output

```typescript
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> Fail gracefully, continue testing, fallback to another available version.

Can you describe the solution a bit more? Which version should WebdriverIO use if `nightly_135.0a1` is not available on Linux?

**Comment by Nathalie-C8** [comment]
I see exactly the same issue, the failure started to occur about 2 days ago on our CI/CD system.
Running wdio tests with capabilities:
{
    'wdio:maxInstances': 1,
    browserName: 'firefox',
    browserVersion: 'latest', 
    acceptInsecureCerts: true,
    'moz:firefoxOptions': {
        args: ['--headless']
}

Is it possible to fix the browserVersion to a specific firefox version to see if this makes a difference? What value should be used instead of 'latest'?

**Comment by nextlevelbeard** [comment]
Thank you @Nathalie-C8
@christian-bromann this appears to be solely on Mozilla team by not reaching out to puppeteer devs.
Nothing to do here. Devs have published a new puppeteer version that and this appears to be fixed.

But I'm still having trouble sometimes when trying to use the "stable" version of Firefox.
```json
{
  "browserName": "firefox",
  "browserVersion": "stable"
}
```

With the very latest stable (133.0.3) already installed locally, looking up the version for 'stable' can give a 404 error and WDIO exits, instead of running the tests with the local (stable channel, even if outdaded) version.
