### ISSUE TITLE
[🐛 Bug]: JSON Import throwing error

### ISSUE THREAD

**Issue by wbigno** [webdriverio/webdriverio#13979]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

 8.39.1

### Node.js Version

Node 22

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
            maxInstances: 90,
            browserName: 'googlechrome',
            platformName: 'Windows 10',
            browserVersion: '126',
            'sauce:options': {
                ...defaultWindowsBrowserSauceOptions
            },
            ...chromeOptions
        }

const chromeOptions = {
    'goog:chromeOptions': {
        w3c: true,
        args: [
            '--user-agent=NYL_AUTOMATION',
            '--disable-features=InsecureDownloadWarnings'
        ],
        prefs: {
            'download.default_directory': 'C:\\Users\\Administrator\\Downloads',
            'download.prompt_for_download': false,
            'safebrowsing.enabled': true,
            'autofill.profile_enabled': false
        }
    }

onst defaultWindowsBrowserSauceOptions = {
    build: `WebdriverIOPipeline-V8 build-${process.env.DOM_BUILD_ENV}-${new Date().getTime()}`,
    screenResolution: '2560x1600',
    idleTimeout: '1000',
    maxDuration: '4500',
    commandTimeout: '600',
    tunnelName: 'NYL_AUTOMATION_TUNNEL',
    extendedDebugging: true
};
```

### What happened?

Migrating from Node 16 to node 22, using the exact same code and versions, and when it runs it throws an error on every test that has an import for a JSON file. 

I have the import set up like this
import data from './path/to/file.json' assert { type: 'json' };

and the error shows as
[0-41]  Error:  Unable to load spec files quite likely because they rely on `browser` object that is not fully initialized.
`browser` object has only `capabilities` and some flags like `isMobile`.
Helper files that use other `browser` commands have to be moved to `before` hook.
Spec file(s): file:///home/jenkins/agent/workspace/cpvs/Martech/AEMSites/Automation/Automation-Selectorized/webdriverio/test/specs/annuities/component/test/auv-product-component-visual-regression.spec.js
Error: SyntaxError[ @/home/jenkins/agent/workspace/cpvs/Martech/AEMSites/Automation/Automation-Selectorized/webdriverio/test/specs/annuities/component/test/auv-product-component-visual-regression.spec.js ]: Unexpected identifier 'assert'
    at compileSourceTextModule (node:internal/modules/esm/utils:337:16)
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:166:18)
    at callTranslator (node:internal/modules/esm/loader:437:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:443:30)
    at async ModuleJob._link (node:internal/modules/esm/module_job:106:19)

I have set up Babel to help correct this, but that did not resolve the issue either
.babelrc file
{
  "presets": [
    ["@babel/preset-env", {
      "targets": { "node": "current" }
    }]
  ],
  "ignore": ["**/*.json"],
  "plugins": [
    "@babel/plugin-syntax-import-assertions"
  ]
}

  
and added this to the wdio file
autoCompileOpts: {
        autoCompile: true, // Enables Babel auto-compilation
        babelOpts: {
          presets: [
            ['@babel/preset-env', { targets: { node: 'current' } }]
          ],
          plugins: ['@babel/plugin-syntax-import-assertions'],
        },
      },

I even tried dynamic imports but that did not fix the issue
const data = await import('./path/to/file.json', { assert: { type: 'json' } });

To be clear, on Node 16 I don't get the browser nor the assert error. It only shows up on Node 22.

### What is your expected behavior?

import should work, and test should run.

### How to reproduce the bug.

 "devDependencies": {
        "@babel/plugin-syntax-import-assertions": "7.26.0",
        "@wdio/cli": "8.39.1",
        "@wdio/local-runner": "8.39.1",
        "@wdio/mocha-framework": "8.39.0",
        "@wdio/sauce-service": "8.39.1",
        "@wdio/visual-service": "5.2.1",
        "chai": "4.3.10",
        "chai-html": "2.1.0",
        "chai-match-pattern": "1.3.0",
        "global-agent": "3.0.0",
        "got": "13.0.0",
        "hpagent": "1.2.0",
        "jsdom": "16.7.0",
        "wdio-timeline-reporter": "5.1.4",
        "webdriverio": "8.39.1",
        "write-excel-file": "1.4.27",
        "xlsx": "0.18.5",
        "xml2js": "0.4.23"
    }

### Relevant log output

```typescript
[0-41]  Error:  Unable to load spec files quite likely because they rely on `browser` object that is not fully initialized.
`browser` object has only `capabilities` and some flags like `isMobile`.
Helper files that use other `browser` commands have to be moved to `before` hook.
Spec file(s): file:///home/jenkins/agent/workspace/cpvs/Martech/AEMSites/Automation/Automation-Selectorized/webdriverio/test/specs/annuities/component/test/auv-product-component-visual-regression.spec.js
Error: SyntaxError[ @/home/jenkins/agent/workspace/cpvs/Martech/AEMSites/Automation/Automation-Selectorized/webdriverio/test/specs/annuities/component/test/auv-product-component-visual-regression.spec.js ]: Unexpected identifier 'assert'
    at compileSourceTextModule (node:internal/modules/esm/utils:337:16)
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:166:18)
    at callTranslator (node:internal/modules/esm/loader:437:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:443:30)
    at async ModuleJob._link (node:internal/modules/esm/module_job:106:19)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> It only shows up on Node 22.

The `assert` syntax has been replaced by `with`, and it's currently only shipped by Chrome and Node.js v22. Other browsers will only ship the with syntax.

This is not an issue within WebdriverIO. The correct way of importing a json is:

```ts
import packageJson from "./package.json" with { type: "json" };
```
