### ISSUE TITLE
[🐛 Bug]: types: Missing BrowserStack capabilities platformVersion

### ISSUE THREAD

**Issue by tristian-azuara-sh** [webdriverio/webdriverio#13981]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    'bstack:options': {
        deviceName: 'Samsung Galaxy S22 Ultra',
        platformVersion: '12.0',
        platformName: 'android'
     }
}
```

### What happened?

BrowserStack's documentation indicates that the `platformVersion` capability can be defined, however the linter and current type don't have it.

<img width="371" alt="Screenshot 2024-12-15 at 12 22 33 AM" src="https://github.com/user-attachments/assets/7a680fc4-d904-429e-b589-c9327d7a751c" />

Current properties:

  * https://github.com/webdriverio/webdriverio/blob/480bc18b7d106e49e73dfadf6b30bb7ebe3ccf10/packages/wdio-types/src/Capabilities.ts#L1519

### What is your expected behavior?

The `platformVersion` field should be available

### How to reproduce the bug.

Simply follow BrowserStack's getting started guide for Appium + WebdriverIO

<img width="1178" alt="Screenshot 2024-12-15 at 12 25 52 AM" src="https://github.com/user-attachments/assets/27a3441c-8f90-464e-ad41-6b510122ab95" />

### Relevant log output

```typescript
This is the lint VSCode reported error:


Type '({ 'bstack:options': { deviceName: string; platformVersion: string; platformName: string; }; } | { 'bstack:options': { deviceName: string; platformName: string; platformVersion: string; autoAcceptAlerts: boolean; }; } | { ...; })[]' is not assignable to type 'RequestedStandaloneCapabilities[]'.
  Type '{ 'bstack:options': { deviceName: string; platformVersion: string; platformName: string; }; }' is not assignable to type 'RequestedStandaloneCapabilities'.
    Types of property ''bstack:options'' are incompatible.
      Object literal may only specify known properties, and 'platformVersion' does not exist in type 'BrowserStackCapabilities'.ts(2322)
Capabilities.d.ts(183, 5): The expected type comes from property 'capabilities' which is declared here on type 'Config'
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by Delta456** [comment]
I will work on a PR for this

**Comment by christian-bromann** [comment]
Thanks @Delta456
