### ISSUE TITLE
Suites with capabilities

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1398]
I've some browser-specific tests and I want to pass capabilities as options to suites:

```js
{
	suites: {
		ie: {
			capabilities: {
				....
			},

			files: [
			   .... 
			]
		}
	}
}
```

Is there any plan to implement it?

**Comment by christian-bromann** [comment]
No, I don't think so. We want to keep the config file flat and simple as possible. If you want to run a certain spec only for a specific browser you can do this:

```js
// ie.spec.js
if (browser.desiredCapabilities.browserName !== 'internet explorer') {
    return;
}

describe("...", function () {...
```
