### ISSUE TITLE
[🐛 Bug]: strictSSL=true option does not work anymore

### ISSUE THREAD

**Issue by mykola-mokhnach** [webdriverio/webdriverio#13994]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.4.3

### Node.js Version

22

### Mode

Standalone Mode

### Which capabilities are you using?

`driver = await wdio({...wdOpts, protocol: 'https', strictSSL: false, capabilities});`

```
{"capabilities":{"alwaysMatch":{"appium:automationName":"Fake","platformName":"Fake","appium:deviceName":"Fake","appium:app":"/Users/elf/code/appium/packages/fake-driver/test/fixtures/app.xml","webSocketUrl":true},"firstMatch":[{}]}}
```

### What happened?

wdio fails to start a BiDi session if the server uses self-signed SSL certificate: 

```
     Error: Failed to create session.
WebDriverError: Request failed with error code DEPTH_ZERO_SELF_SIGNED_CERT when running "https://127.0.0.1:52162/session" with method "POST" and args "{"capabilities":{"alwaysMatch":{"appium:automationName":"Fake","platformName":"Fake","appium:deviceName":"Fake","appium:app":"/Users/elf/code/appium/packages/fake-driver/test/fixtures/app.xml","webSocketUrl":true},"firstMatch":[{}]}}"
      at startWebDriverSession (file:///Users/elf/code/appium/node_modules/webdriver/build/node.js:1029:11)
      at processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async Function.newSession (file:///Users/elf/code/appium/node_modules/webdriver/build/node.js:1256:41)
      at async remote (file:///Users/elf/code/appium/node_modules/webdriverio/build/index.js:7825:20)
      at async Context.<anonymous> (test/e2e/driver.e2e.spec.js:652:14)
```

### What is your expected behavior?

No certificate error.
This feature was working properly with wdio v8

### How to reproduce the bug.

1. Checkout https://github.com/appium/appium
2. `npm i`
3. `cd packages/appium`
4. Set `only` option for the test at https://github.com/appium/appium/blob/c765bc31e03d37ed194fcd52f4e4a2ca1128b260/packages/appium/test/e2e/driver.e2e.spec.js#L698 and uncomment the stuff in the `before` block
5. `npm run test:e2e`

### Relevant log output

See above

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@mykola-mokhnach it seems this is caused by Node.js not trusting self signed certificates. Please disable this error via:

```ts
process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0
```

before you call the command. I think it makes more sense to do this in the test rather than doing this for all WebdriverIO sessions.

Let me know if you have further questions.

**Comment by mykola-mokhnach** [comment]
Thank you @christian-bromann. Adjusting the above env variable helped to address the issue.
