### ISSUE TITLE
Retry Does Not Run Hooks

### ISSUE THREAD

**Issue by mattc41190** [webdriverio/webdriverio#1404]
## The problem

The intended use for hooks is to bring the SUT into a state wherein each test can be atomically run. A reasonable set of before hooks is to redirect to the home page, and perform a login leaving the user free to run whatever test they need to run against the application. A reasonable after hook is to redirect to some stable page and perform a log out and clear cookies leaving the browser clean for the next test.

**The retry functionality ONLY re-runs test code located inside the spec**. For tests with crucial set up and tear down located in the hooks this renders the retry functionality useless. Consider the  code in the Code To Reproduce. I believe it represents a high volume use case. 

If this test fails on the `purchaseProductPage.click('#purchase'); ` step the test will be "re-run" from that step. This will cause the search method to fail unless search field is also present on the purchaseProductPage. The hooks need to be run to get the application into a state in which retries make a meaningful difference.

## Code To Reproduce Issue

``` javascript
    beforeEach(function() { //this function will not re-run
        browser.url('/');
        homePage.login('uname', 'pass');
    });

    it('Order some item', function() {
        searchProductsPage.search('Bear');
        searchProductsPage.goToSomeProduct();
        purchaseProductPage.click('#purchase');
        var cartNumber  =  browser.getText("#cartNumberDisplay");
        expect('cartNumber')toEqual('1');
    });
   afterEach(function() {  //this function will not re-run
        browser.url('/');
        homePage.logout();
    });
```
## Environment

* WebdriverIO version: 4.1.0
* Node.js version: v4.4.1
* Standalone mode
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): Occurs native and with Gulp runner

**Comment by christian-bromann** [comment]
This is gonna tough to implement as it requires to modify the test framework a lot. I even doubt it is possible. It will be task of Mocha and Jasmine to implement this.

**Comment by mattc41190** [comment]
Jasmine does implement this and in WDIO the beforeHooks are done on failed and passed tests just not on the retry.  

``` javascript
describe("A spec (with setup and tear-down)", function() {
  var foo;

  beforeEach(function() {
    foo = 0;
    foo += 1;
  });

  afterEach(function() {
    foo = 0;
  });

  it("is just a function, so it can contain any code", function() {
    expect(foo).toEqual(1);
  });

  it("can have more than one expectation", function() {
    expect(foo).toEqual(1);
    expect(true).toEqual(true);
  });
});
```

**Comment by christian-bromann** [comment]
> Jasmine does implement this

How?

**Comment by origaut** [comment]
+1. I consider this also a must. If a test fails, wdio should re-run also the beforeEach and afterEach hooks and not just a spec. In our case, the spec will fail if run again without going back to a specific state (beforeEach).

**Comment by andyboyne** [comment]
+1 without the hooks retry is too difficult to use in practice

**Comment by christian-bromann** [comment]
Like I said, rerunning whole describe blocks is out of scope of WebdriverIO. This needs to be part of the test framework (jasmine/mocha). In general rerunning flaky suites is a bad pattern. Sure you can have tests that rely on a stable network and can be very flaky because of that should be an individual case and can be structured in a way to fit within an `it` block

**Comment by mattc41190** [comment]
If the beforeEach or afterEach hooks are not run AND those steps are used to get the app into a particular state that your `it` depends on then the retry doesn't provide much value to me.  I load up my homepage in my beforeHook and my `it`s assume I am at the homepage when the test starts. 

Can you show me an example of a place where you are using it and are doing no set up outside of the `it` because I feel like I might be using it wrong.

**Comment by christian-bromann** [comment]
I don't have an example because I try to avoid retries as much as possible. What I was saying is: if you have a testcase that tends to be flaky, just organise it in a way that all steps are running within an `it` block. That might be a bad test design but retrying test is bad test design too!

**Comment by mattc41190** [comment]
Shots fired 😉 

Yeah, I could reorg my tests for this, but my biggest flake issues never occur locally. They only occur when I run through the tunnel. My solution should probably focus around figuring out why my tunnel runs are flaky. If `describe` could be wrapped that would be awesome because we could just nest our hooks and retain the same basic structure, but if this isn't doable I get it.

**Comment by christian-bromann** [comment]
> should probably focus around figuring out why my tunnel runs are flaky

👍 

> but if this isn't doable I get it

Yeah, sorry, if it would be as easy as with the it blocks I would have already implemented it. Wrapping describe blocks doesn't help, it just reaches to deep into the test framework.

**Comment by andyboyne** [comment]
The problem is not all developers are as tuned in as you'd hope. If someone
on the team (perhaps junior) writes a test or PageObject that is a bit
flakey it would be 'easier' to just auto retry rather than waste 6 hours
debugging their test of all race conditions that may occur. I agree the
test shouldn't be flakey in the first place, but in reality it would be
better sometimes to just auto-retry and add an item on the backlog to
investigate the flakey test written by someone that doesn't have the
appreciation of the detail required in writing solid automation tests. At
least that way the build has a fighting chance of staying green. Relying on
inexperienced developers to try-catch retry will never work in practice. It
will be me fixing their tests, or commenting them out.

**Comment by kluverua** [comment]
Possible workaround is to create your own function **myBeforeEach** and call it at the beginning of each test
