### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by knownasilya** [webdriverio/webdriverio#1405]
## The problem

There are a few vulnerabilities introduced by dependencies

<img width="698" alt="screen shot 2016-06-24 at 9 59 13 am" src="https://cloud.githubusercontent.com/assets/34726/16339739/55353d60-39f2-11e6-9104-ad23fd15b6c6.png">

**Comment by christian-bromann** [comment]
Thanks for creating that issue I will try to update these dependencies

**Comment by knownasilya** [comment]
Check out https://www.bithound.io/ or https://snyk.io for automated security checks.

**Comment by christian-bromann** [comment]
Fixed vulnerabilities and added snyk tests.
