### ISSUE TITLE
waitUntil does not wait for the condition to finish executing at least once before throwing an error.

### ISSUE THREAD

**Issue by CTaylor1118** [webdriverio/webdriverio#1407]
## The problem

The timer for waitUntil does not wait until at least the first attempt at the condition has finished. This doesn't seem like a good way to fail as you would expect the condition to be checked at least once before failing, otherwise you may erroneously throw an error.

## Environment

* WebdriverIO version: 4.10.0
* Node.js version: 0.12.7
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): standalone
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Details

I mainly am experiencing this problem with the waitForVisible command. For some reason, isVisible is taking longer than the timeout to return and is inconsistent with the amount of time it takes. For instance, I have a waitForVisible that is taking 3.338 seconds to complete but my timeout is 3 seconds. I am not sure why it would be taking so long for the command to complete but waitUntil should wait for at least on iteration of the condition before failing to give a better picture of what is happening, or alternatively, if the condition has not returned at least once, it should throw an error that reflects that.

**Comment by christian-bromann** [comment]
@CTaylor1118 if you experiencing slow commands due to the network it might be a good idea to increase the timeout for your waitFor commands. Having a 3 second timeout is really short especially when testing on a grid or on cloud services. I doesn't hurt to have a higher timeout.

**Comment by CTaylor1118** [comment]
That makes sense but I still think that waitUntil should at least allow for the condition to return at least once before throwing a timeout error. It took a long time to figure out that was the actual problem because there is no indication that that the command did not return before the timeout.

**Comment by christian-bromann** [comment]
> for the condition to return at least once before throwing a timeout error

That makes sense

**Comment by christian-bromann** [comment]
Fixed, will be released with the next version
