### ISSUE TITLE
A consistent behavior for DOM-methods

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1408]
```js
let element = browser.element(selector);

element.getValue() // Ok
element.selectByAttribut() // Ok
element.click(); // element.click is not a function
element.isVisible() // error
...
```

Is possible to provide a consistent behavior for all DOM-methods?

**Comment by christian-bromann** [comment]
> Is possible to provide a consistent behavior for all DOM-methods?

Can you explain in more detail?

**Comment by monolithed** [comment]
I mean that `.click`, `.isVisible` and other DOM-methods should work with `browser.element`

**Comment by christian-bromann** [comment]
It is consistent throughout the commands. Maybe it doesn't work if you use the same variable multiple times. Need to investigate that.

**Comment by christian-bromann** [comment]
Ok, just tried running a bunch of commands with one element instance and it was working fine. Closing this. If you think this is still an issue please provide a reproducible example of what is wrong.
