### ISSUE TITLE
Click done but the related action never happens on phantomjs. Works with chrome.

### ISSUE THREAD

**Issue by bhuvnesh2703** [webdriverio/webdriverio#1409]
## Problem:
A Button is selected correctly with the CSS selector used, and then a click is performed on it. The event is marked as done as seen in the selenium logs, however if successful a new page must be rendered which does not happen.
The same piece of code works in chrome.

## Environment:
WDIO version: v4.0.9
Node: 6.2.0
WDIO testrunning
Synchronous test.

## Details
```bash
      CommonElements.clickNext();
      browser.saveScreenshot('test1.jpg');
      browser.pause(5000);
      CommonElements.clickConfirmationOk();
      browser.pause(5000);
      // On Page 3
      browser.saveScreenshot('test.jpg');
      CommonElements.clickComplete();
```

In the above code snippet
clickNext() opens up a popup which has 2 buttons Cancel and Ok.
clickConfirmationOk() should click on the Ok button and move on to the next page
clickComplete() marks the completion on the new page.

However, clickConfirmationOk() is succesful as per the logs and it moves on to clickComplete(). However it keeps waiting for the element to exist, but it never comes up as actually its still on the pop which shows Ok and Cancel.

The CSS selector used to identify the button is correct, as verified by getHTML and other css selectors tools online.

Code Snippet
```bash
    clickConfirmationOk: {
        value: function () {
            var okSelector = '.modal-footer .btn.btn-success';
            browser.waitForExist(okSelector);
            console.log(browser.getHTML(okSelector));
            browser.waitForEnabled(okSelector, 100000);
            browser.click(okSelector);
        }
    },
    clickComplete: {
        value: function () {
            var completeSelector = '#common-progress-page .btn.btn-success.pull-right';
            browser.waitForExist(completeSelector);
            console.log(browser.isEnabled(completeSelector));
            browser.waitForEnabled(completeSelector, 900000);
            browser.click(completeSelector);
        }
    }
```

## Logs
Selenium Logs https://gist.github.com/bhuvnesh2703/aec82bea06debf92f9a4f6e4da93c2ea:
Test Results Output: https://gist.github.com/bhuvnesh2703/076af36f5931c8fdae4a81db612bf4b7

**Comment by christian-bromann** [comment]
@bhuvnesh2703 so where do you see the bug in WebdriverIO with your issue?

**Comment by bhuvnesh2703** [comment]
@christian-bromann Are you suggesting that it is not an issue with Webdriverio ? 
Feel free to guide me. 
Is it this way, wdio is a wrapper which allows to run test and if selenium jar says that the event is clicked as in this case. wdio testrunner continues. ?
If so, then it a selenium issue ?

**Comment by jedwards1211** [comment]
most likely an issue with phantomjs itself or the phantomjs driver

**Comment by christian-bromann** [comment]
@jedwards1211 nope he is using Chrome

**Comment by bhuvnesh2703** [comment]
@christian-bromann The issue is when i use phantomjs. With Chrome its works fine.
We have changed our setup to use chrome as its more closer to what the users will experience and phantomjs was having such issues.
Thank you.

**Comment by christian-bromann** [comment]
Ok, closing then.
