### ISSUE TITLE
Promises can't be catched running wdio with async spec

### ISSUE THREAD

**Issue by wirsingj** [webdriverio/webdriverio#1411]
Hey,   I would like to see an isAlertPresent() command- or know if there is a work-around
Is there any  work being done w/ that?  

I am using the wdio cucumber framework-   and if I used a .then like this:

```
    .alertText()
    .then(
        function(data){
            console.log('Got alert text:')
            //here i accept the alert, and find a new product to add to cart...
        }, function(err){
            console.log('There was no alert, but should handle gracefully:')
           //here the product was in stock,  so we continue normally
          //But, even though I 'catch' the error here,  selenium still gets fussy.
        }
      )
```

a selenium error is still thrown far enough for the framework to take a screenshot.

My goal is to be able to tell if an alert popped or not-   either way not throw an error.   (its an out of stock message on a product page which should be handled gracefully)

(fyi,  I tried wrapping it all in  a try/catch, and also tried setting the browser.on('error', (e) => {}) with no success)

**Comment by kevinmcdonnell** [comment]
what selenium error are you getting? Also what version of webdriverIO are you using?

Your example should work, though you might run into issues where the check for `alertText` returns `undefined` (ie no alert) but then an alert is subsequently displayed. You should look at the verbose logs to see what is happening

```
.alertText()
.then(function(result){
    if(result){
        // If result is defined an alert was displayed
        browser.acceptAlert()
        ....
    }
})
```

In wdio v4 this would be:
```
var text = browser.alertText();

if (text){
    browser.alertAccept();
}
```

**Comment by jbarngr** [comment]
Seeing similar issue. Using version 4.1.1. Inside of a Mocha test fails with `no alert open`

**Comment by jbarngr** [comment]
I have come up with a work around that seems kind of strange but in my case of need to check and make sure an alert hasn't been fired it works. @wirsingj 
`
var alertFired = false;
var resolve = function () {
	expect(alertFired).to.be.false;
};
try {
	var text = browser.alertText();

	if (text) {
		alertFired = true;
	}
} catch (e) {
	if (typeof e.seleniumStack !== 'undefined' && 
		typeof e.seleniumStack.status !== 'undefined' &&	
		e.seleniumStack.status === 27) {
		void(e);
	} else {
		alertFired = false;
		throw e;
	}
}
resolve();
`

**Comment by christian-bromann** [comment]
If you run wdio in sync mode you can do that:

```js
    it('check if open sync', function () {
        browser.url('http://google.com');

        var isAlertOpen = false;
        try {
            console.log(browser.alertText());
            isAlertOpen = true
        } catch (e) {}
        console.log(isAlertOpen ? 'alert is open' : 'no alert');
    })
```
That works. If you don't run wdio you can do that:
```js
var client = require('./build').remote({
    desiredCapabilities: {
        browserName: 'chrome'
    }
})

var isAlertOpen = true;

client
    .init()
    .url('http://google.com')
    .alertText().catch(function () {
        isAlertOpen = false;
    })
    .call(function() {
        console.log(isAlertOpen ? 'alert is open' : 'no alert');
    })
    .end();
```
That works too. Unfortunately if you run an async test with wdio like that:
```js
    it('check if open async', function async () {
        var isAlertOpen = true;

        return browser
            .url('http://google.com')
            .alertText().catch(function (e) {
                isAlertOpen = false;
            })
            .call(function () {
                console.log(isAlertOpen ? 'alert is open' : 'no alert');
            })
    })
```
it will fail. I will fix that!

**Comment by christian-bromann** [comment]
Latest example works for me with latest version now too.
