### ISSUE TITLE
hold with xpath selector throws error

### ISSUE THREAD

**Issue by aaronbriel** [webdriverio/webdriverio#1412]
## The problem

When trying a hold(selector) call using xpath it fails with: 
"RuntimeError: Parameters were incorrect. We wanted {"required":["elements"]} and you sent ["element"] at touchLongClick("67") - ..\node_modules\webdriverio\build\lib\commands\hold.js:31:18". 

The following workaround also failed:

```
client.elements('android.widget.CheckedTextView').then(function(elems) {
                return this.hold(elems.value[0].ELEMENT) })
```

Error:
RuntimeError: Locator Strategy 'css selector' is not supported for this session
at element("5") - ..\node_modules\webdriverio\build\lib\commands\hold.js:30:15
## Environment
- WebdriverIO version: 4.0.9
- Node.js version: 5.6.0
- Standalone mode with "selenium-standalone": "5.1.0"
## Code To Reproduce Issue

client.hold(valid_xpath_selector);

**Comment by christian-bromann** [comment]
`android.widget.CheckedTextView` is not an xpath selector. Try something like

```js
var selector = 'new UiSelector().text("Cancel")).className("android.widget.Button")';
browser.click('android=' + selector);
```

or use a proper xpath selector like `./android.widget.CheckedTextView`

**Comment by aaronbriel** [comment]
The second example was a workaround attempt. The actual xpath selector I tried is:
`'//android.widget.CheckedTextView[@text="Atlanta, GA"]'`, which is a valid selector.

**Comment by christian-bromann** [comment]
> which is a valid selector.

so then it should work. However your selector `android.widget.CheckedTextView` looks more like a class name which you can grab using the UI automation API

**Comment by aaronbriel** [comment]
I also tried this with the following:
```
var selector = 'new UiSelector().text("Atlanta, GA").className("android.widget.CheckedTextView")';
browser.hold('android=' + selector);
```
This failed with the same initial error:
RuntimeError: Parameters were incorrect. We wanted {"required":["elements"]} and you sent ["element"]
      at touchLongClick("62") -..\node_modules\webdriverio\build\lib\commands\hold.js:31:18

Please reopen this issue?

**Comment by christian-bromann** [comment]
> RuntimeError: Parameters were incorrect. We wanted {"required":["elements"]} and you sent ["element"]
> at touchLongClick("62") -..\node_modules\webdriverio\build\lib\commands\hold.js:31:18

@aaronbriel we introduced the [touchAction](http://webdriver.io/api/mobile/touchAction.html) command that should help you do these kind of actions. It doesn't seem to be an issue with the selector but more with the command. So try

```js
var selector = 'new UiSelector().text("Atlanta, GA").className("android.widget.CheckedTextView")';
browser.touchAction('android=' + selector, 'longPress');
```
