### ISSUE TITLE
Include typings for webdriverio

### ISSUE THREAD

**Issue by michael-yx-wu** [webdriverio/webdriverio#1413]
The current typings in DefinitelyTyped are for version `3.3.0`. Is it possible for the webdriverio team to include typings as part of the project? @pearsonhenri

**Comment by abettadapur** [comment]
These would be especially useful given the new PageObject paradigm

**Comment by abettadapur** [comment]
Has this been scheduled anytime soon? I am trying to use the element as a first class citizen pattern that you have introduced in 4.0, but it's hard to do given the outdated typings.

**Comment by christian-bromann** [comment]
The current DefinitelyTyped version is on `4.0.4`. Though there is still no element interface. I am not using TypeScript so for me it has no high prio. Happy to see contribution from some TypeScript nerds 😉 😛

**Comment by christian-bromann** [comment]
Typings are available for v4.x. Though there are some issues with it when using wdio testrunner. Closing in favor of #1686
