### ISSUE TITLE
`click` broken change in 4.1.1?

### ISSUE THREAD

**Issue by Spy-Seth** [webdriverio/webdriverio#1415]
## Problem

In our test suite we use:
```javascript
const description  = 'My text A';

driver.waitForExist('.place-selector', 5000)
    .element('.place-selector')
    .click(`a=${description}`); 
```

The HTML looks like:
```html
<div class="place-selector">
  <div class="item"><a href="...">My text A</a></div>
  <div class="item"><a href="...">My text B</a></div>
  ...
</div>
```

With webdriverio version 4.0.9 this code works. 
After upgrading to the version 4.1.1, the `.click` call trigger this error:

```
Error: An element could not be located on the page using the given search parameters.
         at new RuntimeError (/app/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:115:12)
         at Object.<anonymous> (/app/node_modules/webdriverio/build/lib/commands/click.js:49:19)
         at Object.exec (/app/node_modules/webdriverio/build/lib/helpers/safeExecute.js:28:24)
         at Object.resolve (/app/node_modules/webdriverio/build/lib/webdriverio.js:171:29)
         at /app/node_modules/webdriverio/build/lib/webdriverio.js:435:32
         at _fulfilled (/app/node_modules/webdriverio/node_modules/q/q.js:820:54)
         at self.promiseDispatch.done (/app/node_modules/webdriverio/node_modules/q/q.js:849:30)
         at Promise.promise.promiseDispatch (/app/node_modules/webdriverio/node_modules/q/q.js:782:13)
         at /app/node_modules/webdriverio/node_modules/q/q.js:590:44
         at runSingle (/app/node_modules/webdriverio/node_modules/q/q.js:123:13)
```

## Environment

* WebdriverIO version: 4.1.1
* Node.js version: 6.2.2
* standalone mode
* synchronous test

**Comment by christian-bromann** [comment]
@Spy-Seth can you provide selenium logs?

**Comment by Spy-Seth** [comment]
Here the full logs: https://gist.github.com/Spy-Seth/5374a3a2f5c4f3568831455dc85e34dc

The failing step if on line 104: https://gist.github.com/Spy-Seth/5374a3a2f5c4f3568831455dc85e34dc#file-test-log-L104

**Comment by christian-bromann** [comment]
Logs are looking ok. Can you ensure that there is a link with the text `24 Cours Franklin Roosevelt 13001 Marseille` within the element `.place-selector`. Also are there multiple `.place-selector` elements? Selenium will choose the first element that it can find.

**Comment by Spy-Seth** [comment]
I've check manually `document.getElementsByClassName('place-selector')` return only one element (the good one). I've not check that the text is exactly `24 Cours Franklin Roosevelt 13001 Marseille` in my page but I during my test I see something like this. As I said the only change is the upgrade if webdireverio so I suppose the text is the same as previous. I could double check later.

**Comment by christian-bromann** [comment]
Can you try this to check:

```js
driver.waitForExist('.place-selector', 5000)
    .execute(() => {
        return [].slice.call(document.querySelectorAll('.place-selector a')).map(function (a) { return a.innerHTML.trim(); })
    ).then((res) => console.log(res.value))
    .element('.place-selector')
    .click(`a=${description}`);
```

We haven't changed any functionality in the click method.
