### ISSUE TITLE
How to use Page object pattern and multibrowser configuration?

### ISSUE THREAD

**Issue by ssfxate** [webdriverio/webdriverio#1416]
How to make action in specific browser like browserA or browserB?

I can't find examples with it.

**Comment by christian-bromann** [comment]
Here is a multibrowser example: https://github.com/webdriverio/webdriverio/tree/master/examples/multiremote

If you want to use multibrowser with wdio just define your caps as an object:

```js
// wdio.conf.js
//...
capabilties: {
    browserA: {
        browserName: 'chrome',
    },
    // ...
}
// ...
```

The page object pattern can be applied the same way as in this example: https://github.com/webdriverio/webdriverio/tree/master/examples/pageobject

**Comment by ssfxate** [comment]
I need to user methods from page object in different browser like this
`it('Test', () = > {
browserA.loginPage.inputA.setValue('1')
browserB.loginPage.inputA.setValue('2')

browserA.loginPage.inputB.setValue('1')
browserB.loginPage.inputB.setValue('2')

browser.loginPage.submitButton.click()

browserA.appPage.header.should.be.equal('user1')
browserA.appPage.header.should.be.equal('user2')
})`

How to do this?

A browser is determined at the time of the call.

**Comment by christian-bromann** [comment]
Without knowing your setup and Page Objects I can't help you. This: `BrowserA.appPage.header.should.be.equal('user1')` looks not right though seems you missing `getText()` method? Also why do you assign the page object to the browser instance?

**Comment by ssfxate** [comment]
Oh sorry. getText(). Sure.

```
it('test', () => {
    BrowserA
        .loginPage.inputA
                .setValue('1')
    BrowserB
        .loginPage.inputA
                .setValue('2')

    BrowserA
        .loginPage.inputB
                .setValue('1')
    BrowserB
        .loginPage.inputB
                .setValue('2')

    BothBrowsers
        .loginPage.submitButton
                .click()

    BrowserA
        .appPage.header.getText().should.be.equal('User1')
    BrowserB
        .appPage.header.getText().should.be.equal('User2')
})
```
or
```
it('test', () => {
    BrowserA
        .loginPage.inputA
                .setValue('1')
        .loginPage.inputB
                .setValue('1')

    BrowserB
        .loginPage.inputA
                .setValue('2')
        .loginPage.inputB
                .setValue('2')
        
    BothBrowsers
        .loginPage.submitButton
                .click()

    BrowserA
        .appPage.header.getText().should.be.equal('User1')
    BrowserB
        .appPage.header.getText().should.be.equal('User2')
})
```


```
exports.config = {
    
    specs: [
        './tests/test.js'
    ],

    capabilities: {
        browserA: {
            desiredCapabilities: {
                browserName: 'chrome',
            }
        },
        browserB: {
            desiredCapabilities: {
                browserName: 'chrome',
            }
        }
    },
    sync: true,
    logLevel: 'silent',
    coloredLogs: true,
    screenshotPath: './errorShots/',
    baseUrl: '/',
    waitforTimeout: 4000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    mochaOpts: {
        ui: 'bdd'
    },
    before: function() {
        var chai = require('chai');
        chai.Should();
    }
}
```

```
// page.js
class Page {
	open (path) { browser.url(path) }
}
module.exports = Page()
```

```
// Login.page.js
var Page = require('./page')
class Login extends Page {
    get loginInput ()   { return browser.element(".login") }
    get passInput ()    { return browser.element(".password") }
    get submitButton () { return browser.element(".submit") }

   open () {
        super.open(MySite); 
    }
}
module.exports = Login;
```

```
var Page = require('./page')
class App extends Page {
    get header ()   { return browser.element(".header") }
module.exports = App;
```

In my tests i need to make something in browserA authorised with User1 and check results in browserB authorised with User2.
I need to use all elements in browser object with both browsers at the same time or by specific one.

How to write my tests correct? How to make something in specific browser in tests?
It may be completely different than I wrote above. I'm interested in the variant, as it is conceived by developers.

`P.S. Sorry for my English. I use online-translater. English isn't my native language.`
