### ISSUE TITLE
waitForExist does not work as expected

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1420]
```
browser.waitForExist(undefined);
// or
browser.waitForExist('unknown_element');
```

```diff
- timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
````

Should be boolean result, as far as I know.

My standard user case:

```js
let actual = browser.waitForExist('selector');

assert(actual, 'Could not found required element');
```

**Comment by christian-bromann** [comment]
@monolithed you should use `waitForExist` like this:

```js
it("should do something", function () {
  // some commands
  browser.waitForExist("selector");
  // more commands
});
```
You don't need the assert because the command will throw if it can't find the element within the timeout.

**Comment by monolithed** [comment]
**timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.**

I think, is not the best message for this case

**Comment by monolithed** [comment]
![img-2016-06-29-21-44-07](https://cloud.githubusercontent.com/assets/803674/16464388/a2ec341a-3e42-11e6-81e1-c86072230d62.png)

**Comment by monolithed** [comment]
@christian-bromann, could you test it? It seems `wait*` commands not throw error if it can't find the element within the timeout.

**Comment by christian-bromann** [comment]
We have a test for that right [here](https://github.com/webdriverio/webdriverio/blob/master/test/fixtures/specs/element.spec.js#L95-L107)

**Comment by monolithed** [comment]
1. 

```
elem.waitForText(2000)
``

Output:

```
timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
```

It's non informative output

2.

```js
 try {
         elem.waitForText(2000)
} catch (e) {
        console.log(e)
}
```

Output:

```
err { WaitUntilTimeoutError: element (.pm-toolbar__search__container [data-operand-name="q_attach"]) still not visible after 1ms
    at Object.Future.wait (/node_modules/fibers/future.js:449:15)
    at Object.waitForVisible (/node_modules/wdio-mocha-framework/node_modules/wdio-sync/build?index.js:398:27)
    at PortalSearch.hasOperand (tests/e.mail.ru/pages/portal-menu/portal-search.js:90:14)
    at PortalSearchSteps.hasOperand (tests/e.mail.ru/steps/portal-menu/portal-search.js:37:38)
    at Context.it (tests/e.mail.ru/cases/search/TESTMAIL-31697.js:16:21)
    at Context.executeSync (node_modules/wdio-mocha-framework/node_modules/wdio-sync/build/index.js:625:12)
    at node_modules/wdio-mocha-framework/node_modules/wdio-sync/build/index.js:833:34
    at isVisible(".pm-toolbar__search__container [data-operand-name="q_attach"]") - node_modules/webdriverio/build/lib/commands/waitForVi
sible.js:65:22
  message: 'element (.pm-toolbar__search__container [data-operand-name="q_attach"]) still not visible after 1ms',
  type: 'WaitUntilTimeoutError' }
```

I don't want to use try/catch statement everyplace.

**Comment by monolithed** [comment]
By the way, is there way to reduce 10000ms timeout globally?

**Comment by christian-bromann** [comment]
yes by setting the timeout in your mochaOpts

**Comment by monolithed** [comment]
We're not passing our function to `assert.throws()`. But I found a way how to solve my problem:

```
	mochaOpts: {
		'ui': 'bdd',
		'retries': 0,
		'trace': true, // !!!
		'full-trace': true, // !!
		'throw-deprecation': true,
		'trace-deprecation': true,
		'timeout': 1 * 1000
	},
```

**Comment by christian-bromann** [comment]
What difference does this make?

**Comment by monolithed** [comment]
![img-2016-06-30-19-46-10](https://cloud.githubusercontent.com/assets/803674/16496573/53dd6e52-3efb-11e6-84b2-d913092d0178.png)

**Comment by kurtharriger** [comment]
I think the difference is in the error messaging.  The "ensure done() is
being called in this test" is confusing for new users and sends them
astray.  We have a story in our backlog to improve error messaging.
Unfortunately, we are currently using jasmine to make migrating our
previous test suite easier.

**Comment by christian-bromann** [comment]
> The "ensure done() is being called in this test" is confusing for new users and sends them astray

That only shows up though when a Mocha timeout was reached. I might be able to fix that error in `wdio-sync`
