### ISSUE TITLE
Inheritance between Page Objects

### ISSUE THREAD

**Issue by joaoffalcao** [webdriverio/webdriverio#1422]
## Inheritance between Page Objects

Is there any way to have inheritance between page-objects? For instance, if I have a component that is repeated in multiples places (in this case a button) and I want to use it in different contexts, how can I restrict the context instead of get from the all DOM?

## Environment

* WebdriverIO version: 4.1.1

## Code To Reproduce Issue 
```javascript 
var Page = require('./page');

module.exports = Object.create(Page, {
        module: {get: function () {return browser.element('.topbar');}},
        button: { get: function () {return browser.element('.button');}}
    });
```

How can I get button from the topbar and the navigationBar, if both of them use the same css selector?

**Comment by christian-bromann** [comment]
You can just create another PO that will inherit from that PO:
```js
// main.page.js
var Page = require('./page');

module.exports = Object.create(Page, {
    button: { get: function () {return browser.element('.button');}}
});
```

Now your actual PO looks like:

```js
var Main = require('./main.page');

module.exports = Object.create(Main, {
    module: {get: function () {return browser.element('.topbar');}},
    // other elements
});
```

**Comment by joaoffalcao** [comment]
So, here is Header on HomePage

```javascript
var HomePage = require('./home.page');

module.exports = Object.create(HomePage, {
    headerModule: {get: function () {return browser.element('.header');}},
    // other elements
});
```

An here is Footer also on HomePage
```javascript
var HomePage = require('./home.page');

module.exports = Object.create(HomePage, {
    footerModule: {get: function () {return browser.element('.footer');}},
    // other elements
```

In both modules, I have the same button and I want to create just one page object for both cases. Which page should I use to inherit? I don't know how to pass by parameter, the parent page object.

**Comment by christian-bromann** [comment]
Just put the button into the home.page PO and it will get inherited by your header and footer PO

**Comment by joaoffalcao** [comment]
And what If I have more than one button (with the same css) at the same header?

**Comment by christian-bromann** [comment]
Then you need to be more specific with your selector
