### ISSUE TITLE
browser.debug is not working as expected

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1425]
```js
{
	framework: 'mocha',

	mochaOpts: {
		'timeout': 10 * 1000 // Maximum time for debugging
	}
}
```

If it's possible to control this value while test is running it should be something like Infinity

**Comment by christian-bromann** [comment]
Unfortunately we can't do that during the test because we have no access to the Mocha scope. The user has to do that. Also see https://github.com/webdriverio/webdriverio/blob/master/lib/commands/debug.js#L7-L8

**Comment by kurtharriger** [comment]
I use an environment variable to temporarily increase the timeout while
debugging.
See http://webdriver.io/guide/testrunner/debugging.html

**Comment by monolithed** [comment]
> I use an environment variable to temporarily increase the timeout while

Thanks, I've already a simple wrapper like

```
➜ npm test -- e.mail.ru --suite=login --grep=TESTMAIL-867 --debug
```
