### ISSUE TITLE
Getting  ERROR: Couldn't connect to selenium server when running from Jenkins to SauceLabs

### ISSUE THREAD

**Issue by nirjashah** [webdriverio/webdriverio#1426]
## The problem
Running tests on local machine works fine. 
However, the tests fail on Jenkins with following error:
In wdioSauce.. build number is : 44
In wdioSauce.. port is : 44
ERROR: Couldn't connect to selenium server
firefox.windows8
    at new RuntimeError (/home/scmbuild/.jenkins/workspace/TST-QBO-Developer-Portal-UI-Smoke-Suite-wdio/node_modules/@sbg/plugin-build/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:115:12)
    at Request._callback (/home/scmbuild/.jenkins/workspace/TST-QBO-Developer-Portal-UI-Smoke-Suite-wdio/node_modules/@sbg/plugin-build/node_modules/webdriverio/build/lib/utils/RequestHandler.js:267:37)
    at self.callback (/home/scmbuild/.jenkins/workspace/TST-QBO-Developer-Portal-UI-Smoke-Suite-wdio/node_modules/@sbg/plugin-build/node_modules/webdriverio/node_modules/request/request.js:373:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/home/scmbuild/.jenkins/workspace/TST-QBO-Developer-Portal-UI-Smoke-Suite-wdio/node_modules/@sbg/plugin-build/node_modules/webdriverio/node_modules/request/request.js:971:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:256:9)
    at emitOne (events.js:77:13)

## Environment
  capabilities: [{
        browserName: "firefox",
        platform: "Windows 8",
        name: "Testing QBO Developers - Firefox"
    }],

* WebdriverIO version: "webdriverio": "^4.0.0",
* if wdio testrunner, running synchronous or asynchronous tests: synchronous tests

## Details
 wdio sauce config:
```js
var baseConfig = require(process.cwd() + "/node_modules/@sbg/plugin-build/node_modules/@sbg/trinityjs/config/base");
console.log("In wdioSauce.. build number is : "+ process.env.BUILD_NUMBER);
config = {
    host: (process.env.BUILD_NUMBER) ? 'ondemand.saucelabs.com':'localhost',
    port: (process.env.BUILD_NUMBER) ? process.env.BUILD_NUMBER:4447,
    updateJob: true,
    reporter: "spec",
    waitforTimeout: 1250000,
    user: "@@@@@@@@@@@",
    key: "@@@@@@@@@@",
    services: ["sauce"],
    sauceConnect: true,
    capabilities: [{
        browserName: "firefox",
        platform: "Windows 8",
        name: "Testing QBO Developers - Firefox"
    }],
    mochaOpts: {
        timeout: 100000
    },
    onPrepare: function(config, capabilities) {
        // browser.timeoutsImplicitWait(150000);
        // browser.timeoutsAsyncScript(150000);
        // browser.timeouts('page load', 600000);
    },
};

exports.config = Object.assign(baseConfig.getBaseConfig(), config);
```
on Jenkins, we are assigning unique TCP ports to avoid collisions to BUILD_NUMBER
commands issued on Jenkins:
time npm install
export NODE_ENV=qa
echo ${BUILD_NUMBER}
export BUILD_NUMBER=${BUILD_NUMBER}
grunt testAutomation --config=test/config/wdioSauce

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
If you want to connect with Sauce your port need to be `80`, change this line:
```js
port: (process.env.BUILD_NUMBER) ? 80:4447
```

**Comment by wido-user** [comment]
@christian-bromann : does this limit us from running only one job per slave in jenkins as this port will be already taken ?

**Comment by nirjashah** [comment]
@christian-bromann : Randomly getting ERROR: Couldn't connect to selenium server
firefox.46_0.osx10_9 even after updating port to 80.

**Comment by christian-bromann** [comment]
@nirjashah make sure you don't start more vms that your concurrency on sauce allows it.
