### ISSUE TITLE
support testdroid

### ISSUE THREAD

**Issue by talarari** [webdriverio/webdriverio#1429]
I see that you support sauce labs and a few other services, can you add support for testdroid?

**Comment by christian-bromann** [comment]
Any cloud service is supported. Just set host and port property in your wdio config file and your tests will get executed on testdroid.

**Comment by rahulmr** [comment]
@talarari were you able to configure something for testdroid? @christian-bromann did you come across any examples?

**Comment by christian-bromann** [comment]
> @christian-bromann did you come across any examples?

No, I am not using it

**Comment by rahulmr** [comment]
@christian-bromann Found https://kobiton.com/ better and pricing is also good. @christian-bromann webdriverio is awesome for testing native apps, I have been working very well recently. It will be better when Amazon Device Farm has something like this which supports webdriverio on the fly, just provides us the url, user and api key to access the hub.
