### ISSUE TITLE
Incorrect promise behavior when rejecting promises in resolve/reject callback

### ISSUE THREAD

**Issue by amilner42** [webdriverio/webdriverio#1431]
## The problem - Promises....

Promises in webdriverio don't follow the spec.

Here is a gist with examples of where it is broken: https://gist.github.com/amilner42/67a7d230184f240ff1d711190aced978

**Comment by christian-bromann** [comment]
@amilner42 thanks for putting together these examples. We reimplemented promises in WebdriverIO and it could be that the behavior does not reflect the standard. I would recommend to use the wdio test runner and synchronous commands. It makes writing tests way easier. I will keep this open and to fix issues you mentioned in your project. Thanks!

**Comment by amilner42** [comment]
@christian-bromann no worries, thanks for making webdriverio!

Why re-implement promises if you don't mind me asking? To me it seems the easiest way to match the spec and make webdriverio maximally versatile would be to use an existing implementation of promises. We aren't using webdriverio for testing, we are using it for automating browser work (getting data), so I'm not sure if `wdio` fits our use-case, but I will take a deeper look.

Let me know if there is something I can do to help! Thanks again

**Comment by christian-bromann** [comment]
> Why re-implement promises if you don't mind me asking?

WebdriverIO is a mixture of an ajax (to be able to chain commands) and promise monad (to make sure each command gets executed after the other). There is no way to just inject an existing Promise library. We had to write the promise monad from scratch which allowed us to also add a lot of neat features.

mhm wdio is actually meant to do test execution. Maybe it still fits your needs.

**Comment by PatrickKing** [comment]
I can add one more WTF to the list ... 

```javascript
var webdriverio = require('webdriverio');
var Promise = require('bluebird');

var webdriverSession = null;

webdriverPromise = new Promise(function(resolve, reject) {
  var wdOpts = { desiredCapabilities: { browserName: 'phantomjs' } };
  webdriverSession = webdriverio.remote(wdOpts).init();
  resolve(webdriverSession);
});


webdriverPromise.then(function(promisedSession) {
  console.log("Session assigned to variable via closure:");
  console.log(webdriverSession); // The session object, as expected
  console.log(webdriverSession.url); // [Function]
  console.log("Promised session:");
  console.log(promisedSession); // ... something else! 
  console.log(promisedSession.url); // undefined

  console.log(promisedSession === webdriverSession) // false
  // Expected both objects to be the same!

});
```
It's really, *really* important to document that your API is not A+ Promise compatible, so that people can stop wasting time stumbling over things like this.

**Comment by amilner42** [comment]
I'd even go as far as arguing that this should be given a high priority, my team ended up stopping using webdriverio, in part because without actual promises it was impossible for us to use to write the type of high quality code you get with promises.

Any news on this @christian-bromann?

**Comment by christian-bromann** [comment]
@amilner42 @PatrickKing we haven't prioritized issues in the standalone version because we want people to use the test runner to build scaleable e2e test suites. With wdio you don't need to deal with promises anymore and these issues also don't seem to affect the workflow. However we are interested to keep both modes stable so other libraries can adapt the standalone mode as their automation engine.
At the end of the day working on WebdriverIO is an unpaid hobby of mine and when I work on it I try to use my time as best as possible. Input like this definitely helps me prioritizing things but I can't work on everything at the same time.

**Comment by PatrickKing** [comment]
@christian-bromann I understand completely that time at a premium, and I appreciate the effort you've put into this project. WDIO is a hugely useful tool, and it's not a problem to me if promises aren't supported or aren't a priority feature, but your users have just got to know not to mix WDIO objects with promises. Discovering this in the issues section is pretty rough.

**Comment by amilner42** [comment]
@christian-bromann Ya, I appreciate you working on this, <3 open source ;)

I just wanted to say that I (and the rest of my team, more experienced that I) thought it was a big deal so my 2 cents are that it would be a valuable fix...BUT that being said, even if you disagree with me and that their are more important things, you definitely should take up @PatrickKing advice and document it, that should only take a second :) It took me a long time (if I remember correctly, around a week) to figure out the bug, because it was a medium code base and I wouldn't have ever guessed that the webdriverio promises were the buggy part. I would make this as clear as possible so others dont go through the same thing.

**Comment by lf94** [comment]
Got bit by this one...

**Comment by sipayRT** [comment]
One more case when wdio promises works incorrect:

```javascript
client
    .init()
    .url('http://yandex.ru')
    .title()
    .finally(() => console.log('fin')) // finally will break passing title() result to .then
    .then((res) => console.log('===>', res)) // got undefined!
    .end()
    .catch((e) => console.log(e));
```
but it works fine with bluebird/q promises

``` javascript
Promise.resolve('a')
    .finally(() => console.log('fin'))
    .then((res) => console.log('===>', res)) // got 'a'
```

**Comment by christian-bromann** [comment]
This will be fixed with v5. Closing.
