### ISSUE TITLE
WDIO Multiremote test launches an extra session

### ISSUE THREAD

**Issue by khenri** [webdriverio/webdriverio#1434]
## The problem

Running test:wdio starts 3 sessions in selenium, instead of 2. 

## Environment

* WebdriverIO version: 4.1.1
* Node.js version: 6.2.2
* Selenium version: 2.53.1

## Details

Seems like #1401 has broken the functionality. Reverting the merge fixes the problem. https://github.com/webdriverio/webdriverio/blob/master/lib/runner.js#L262 creates a new instance from the processNumber that is added to the caps in https://github.com/webdriverio/webdriverio/blob/master/lib/launcher.js#L290

## Link to Selenium/WebdriverIO logs

https://gist.github.com/khenri/b219510de7a46380309f13fc5fc96ddd

## Code To Reproduce Issue [ Good To Have ]

```grunt test:wdio```

**Comment by christian-bromann** [comment]
Fixed and will be released with `v4.1.2` soon
