### ISSUE TITLE
NPM dependencies are not specific enough

### ISSUE THREAD

**Issue by DavidFrahm** [webdriverio/webdriverio#1436]
## The problem

I had an old version of Node installed (v0.12.x) and was brand new to WebdriverIO. I installed the npm stuff for webdriverio (4.0.9) and wrote a really simple test for our Login screen.  Running my jasmine tests on an angular website I needed to have it wait for the url to change as a form submitted and angular routed to a new view.

This code worked for that:

```
  it("should login successfully", function () {
    browser.url('/#/login');

    browser.setValue('input[name=EmailAddress]', 'valid-user@company.com');
    browser.setValue('input[ng-model="loginUser.password"]', 'correct-password');

    browser.click('button[type="submit"]');

    browser.waitUntil(function () {
      return browser.getUrl()
        .then(function (url) {
          return !(/\/login/.test(url));
        });
    });

    expect(browser.getUrl()).toContain('/#/home/rentals');
  });
```

After I got that working, for other reasons I had to update Node, delete my `node_modules`, and reinstall them via `npm install`. After that, the same config and test failed on the promise `.then()`, like this:

```
[11:35:22]  COMMAND	GET 	 "/wd/hub/session/d9fdd01dc1b44423908d6a6406d6dab0/url"
[11:35:22]  DATA		{}
[11:35:22]  RESULT		"https://staging.equipmentshare.com/billing/#/login"
/Users/david/Projects/es-mono/app/es-admin/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: browser.getUrl(...).then is not a function
    at Object.<anonymous> (/Users/david/Projects/es-mono/app/es-admin/test/functional/login-happy-spec.js:19:31)
    at /Users/david/Projects/es-mono/app/es-admin/node_modules/wdio-sync/build/index.js:293:29
```

The fix was to change the test code to remove the promise, like this:

```
    browser.waitUntil(function () {
      var url = browser.getUrl();
      return !(/\/login/.test(url));
    });
```

So I think that the first test code should not have worked, but some dependency used by webdriverio wasn't force to be bumped, so it did.

If that is true, I recommend that you review the webdriverio dependencies and ensure that it requires the newer versions of whatever it needs to have the completely correct behavior.

## Environment

* WebdriverIO version: 4.0.9
* Node.js version: First 0.12.7, then 6.3.0
* wdio testrunner mode:
* if wdio testrunner, running synchronous or asynchronous tests: default
* Additional wdio packages used (if applicable): wdio-sauce-service, wdio-jasmine-framework

**Comment by christian-bromann** [comment]
After you have updated your dependencies you've installed webdriverio v4.1.1 which changed the behavior how waitUntil works. I am not sure what you are recommending but I don't think I can do anything here.
