### ISSUE TITLE
browser.frameParent() doesn't work for internet explorer

### ISSUE THREAD

**Issue by vavd** [webdriverio/webdriverio#1437]
Hello,

Is there any workaround?

Command not found: POST /session/f07b4ea6-8237-4ac5-ac19-0735c4319986/frame/parent
Command duration or timeout: 0 milliseconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: '***', ip: '***', os.name: 'Windows 8.1', os.arch: 'amd64', os.vers
ion: '6.3', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{browserAttachTimeout=0, enablePersistentHover=true, ie.forceCreateProcessApi=false, i
e.usePerProcessProxy=false, ignoreZoomSetting=false, handlesAlerts=true, version=11, platform=WINDOW
S, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwi
tches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:
41851/, takesScreenshot=true, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableEleme
ntCacheCleanup=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=dismiss}]
Session ID: f07b4ea6-8237-4ac5-ac19-0735c4319986

**Comment by christian-bromann** [comment]
@vavd you can try to grab all available window handles and jump to the one that you are not on. Seems like IE can't deal with frame parent.

**Comment by dbuck** [comment]
In case anyone else stumbles on this also:

per https://w3c.github.io/webdriver/#dfn-switch-to-frame and the description in the [webdriver.json](https://github.com/webdriverio/webdriverio/blob/96801efd9a6881f917e8ef6bbd65cbe4797f2d11/packages/webdriver/protocol/webdriver.json#L177) file, you can also send null to select the top level context:

```
browser.frame(null);
```
