### ISSUE TITLE
Async Custom Commands are Not Executed in Order when Chaining them

### ISSUE THREAD

**Issue by ResolverJay** [webdriverio/webdriverio#1439]
## The problem

I'm just migrating v3 to v4. I want to maintain async scripts while developing sync scripts, so I set `sync: true`, and mark the tests and custom commands as async.

A major issue I'm experiencing is chaining custom commands doesn't work the same as in v3. Async custom commands are executed in random order.

## Environment

* WebdriverIO version: 4.2.0
* Node.js version: 4.4.7
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): testrunner (mocha)
* if wdio testrunner, running synchronous or asynchronous tests: `sync: true` tests run in async
* Additional wdio packages used (if applicable): N/A

## Details

Unless a "then" callback is used, I don't see any way to ensure the order of execution. For this specific log attached, you can see "click" was executed before setting any values, which is not the same order in the script.

## Link to Selenium/WebdriverIO logs

https://gist.github.com/ResolverJay/4960d16b4578c628ecd53afc65f59d7a

## Code To Reproduce Issue [ Good To Have ]

```
browser.addCommand('customSetValue', function async(locator, name) {
    return this.setValue(locator, name);
});

browser.addCommand('customClick', function async(locator) {
    return this.click(locator);
});
```

```
describe('v4', function () {
    it('Chaining custom commands', function async() {
        return browser
            .url('https://www.facebook.com/')
            .customSetValue('[name="email"]', 'some@email.com')
            .customSetValue('[name="pass"]', 'somePassword')
            .customClick('input[type=submit]')
    });
});
```

**Comment by ResolverJay** [comment]
Is there any update on this? We pretty much depend on it to migrate to v4.

**Comment by christian-bromann** [comment]
Sorry for the late fix. All custom commands were executed without waiting on the previous chained command. Please update your framework adapter to get that change. Thanks for filing the issue.
