### ISSUE TITLE
Do not display more than one path to the report

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1440]
![img-2016-07-10-21-18-34](https://cloud.githubusercontent.com/assets/803674/16715281/e5fd67ac-46e3-11e6-9c54-0ad7a054eeea.png)

Is it possible to not display more than one path to the report?

**Comment by christian-bromann** [comment]
> Is it possible to not display more than one path to the report?

What do you mean?

**Comment by monolithed** [comment]
I see hundreds of lines like `Wrote json to [...]` in my console. I'd like to hide them.

**Comment by christian-bromann** [comment]
> I'd like to hide them.

Why? It is reporter output. It doesn't affect your tests.

**Comment by monolithed** [comment]
> It doesn't affect your tests. 
Sure, it doesn't, but I don't understand why you want to display this line for each test. It's a visual noise. 

```js
{
	reporterOptions: {
		outputDir: `./cache/tests/${project}/reports` // only one directory
	}
}
```

We cannot configure the output for each test so it looks like a bug to me.

**Comment by christian-bromann** [comment]
> We cannot configure the output for each test, so it looks like a bug to me.

That is a good point. However it is not a bug in WebdriverIO and should be fixed in the reporter. I will close this issue here. Will try to tweak those reporter in order to print that message only once.
