### ISSUE TITLE
"Don't end the session manually. This will be done automatically." when using reload()

### ISSUE THREAD

**Issue by lambsubstitute** [webdriverio/webdriverio#1443]
I have been trying to use the browser.reload() functionality to force the browser to reset the session between scenarios that are located in the same feature files. This is in order to remove any uncertainty that there is not session creep from one scenario to another, as some of our features run complicated business examples. 
However, when trying to use this unfortunately when trying to implement the said function the error message "Don't end the session manually. This will be done automatically."

have tried this in a before hook 
```beforeScenario: function () {
      browser.reload()
    },``` 

and in a setup method that runs from  background step before any scenario
```export const setUpBrowser = async () => {browser.reload()}```

"webdriverio": "4.2.1"

**Comment by christian-bromann** [comment]
Are you running WebdriverIO in sync or async mode?

**Comment by lambsubstitute** [comment]
having inherited this test suite, how would i be able to tell which mode it is running in? i can say i am having to use "async" on every method i write, if that helps in any way.

**Comment by christian-bromann** [comment]
> how would i be able to tell which mode it is running in?

That is something you specify. See http://webdriver.io/guide/getstarted/modes.html

**Comment by lambsubstitute** [comment]
standalone mode, so async i believe

**Comment by christian-bromann** [comment]
so you are not using the wdio testrunner?

**Comment by christian-bromann** [comment]
See #1445

**Comment by monolithed** [comment]
```
Error in onRefresh hook: "CommandError: Don't end the session manually. This will be done automatically.
```

It seems not working with wdio testrunner

**Comment by christian-bromann** [comment]
@monolithed this is already fixed but not published yet.
