### ISSUE TITLE
Cli argument --suite is ignored if suite specified does not match any file

### ISSUE THREAD

**Issue by david-benes** [webdriverio/webdriverio#1448]
## The problem

When using commandline argument '--suite TESTSUITE' and 'TESTSUITE' in config does not contain any valid file (or this suite is not defined), this argument is ignored and all tests are run.

This is very confusing. User's obvious intention is to run TESTSUITE and quit if no test is found.

## Environment

* WebdriverIO version: 4.1.0
* Node.js version: 5.6.0
* wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):

**Comment by christian-bromann** [comment]
@david-benes what would you suggest? Letting it fail or just printing an info message and execute all tests?

**Comment by david-benes** [comment]
I would suggest failing. When I specify test suite, I expect that only this test suite is going to be executed.

Or this can be decomposed to a few situations (just a suggestion):
- failure if suite is not defined in config
- failure if invalid test path is encountered in suite definition (or alternatively just ignore that path)
- success if no test files from suite are run (but do not run tests outside of test suite)

**Comment by christian-bromann** [comment]
Fixed issue. If no suite was found the config parse will throw an error in advance.
