### ISSUE TITLE
Get contents of iFrame

### ISSUE THREAD

**Issue by hackable** [webdriverio/webdriverio#1449]
How to get html contents of iframe 

````

function logS(item) {
     client.elementIdElements(item.ELEMENT,'//body').then(function(text) {
       console.log(text);
    });
   
}

var echoLog = function(frames){
    frames.forEach(logS);
};

var client = {},iframes = [];

    client =  webdriverio.remote(options).init().url(websiteURI);


    client.selectorExecute("//iframe", function(frames) {
       return frames;
    })
    .then(function(frames){
        echoLog(frames);
    });


````

**Comment by christian-bromann** [comment]
You need to get the windowHandle of that frame using http://webdriver.io/api/protocol/windowHandles.html then you need to switch to it by executing http://webdriver.io/api/window/switchTab.html.

Please ask in the Gitter channel if you have more questions like this. Only use the issue tracker if you discover bugs. Thanks!
