### ISSUE TITLE
Enable "element as 1st citizen" for multiremote

### ISSUE THREAD

**Issue by straris** [webdriverio/webdriverio#1453]
## The problem

The attached script runs perfectly fine when executed with a single browser or concurrent browser runs but will fail with the following error when run in parallel
`ERROR: number or type of arguments don't agree with setValue command`

More specifically, I see all three sessions launching but after navigating to the page the execution stops due to the error.
 (The sessions should be 2 but due to https://github.com/webdriverio/webdriverio/issues/1434 there are three)
## Environment
- WebdriverIO version: 4.2.1
- Node.js version: 4.4.5
- wdio testrunner
- synchronous tests
- multiremote
## Code To Reproduce Issue [ Good To Have ]

```
capabilities config:
capabilities: {
    chrome: {
      desiredCapabilities: {
        browserName: 'chrome'
      }
    },
    firefox: {
      desiredCapabilities: {
        browserName: 'firefox'
      }
    }
  }
```

test:

```
var assert = require('assert');

describe('webdriver.io page', function () {
  it('should have the right title - the fancy generator way', function () {
    browser.url('http://www.eyeem.com/login')
      .element('input[data-field-type="email_or_nickname_exists"]').setValue("blabla")
      .element('input[data-field-type="existing_password"]').setValue("blabla")
      .click('.wrapper-signuplogin button')
      .getTitle();
    assert.equal(browser.getTitle(), 'EyeEm');
  });
});
```

**Comment by christian-bromann** [comment]
Calling an element command this way doesn't work yet for multiremote. Please use the standard syntax:

```js
var assert = require('assert');

describe('webdriver.io page', function () {
  it('should have the right title - the fancy generator way', function () {
    browser.url('http://www.eyeem.com/login')
    browser.addValue('input[data-field-type="email_or_nickname_exists"]', "blabla")
    browser.addValue('input[data-field-type="existing_password"]', "blabla")
    browser.click('.wrapper-signuplogin button')

    assert.equal(browser.getTitle(), 'EyeEm');
  });
});
```
for the time being.

**Comment by cannuk** [comment]
What would it take to make `element` work with multiremote? What other commands do not work with multiremote? I want to use multiremote but our infrastructure is heavily using Page Object pattern and extensive use of `element`

**Comment by christian-bromann** [comment]
> I want to use multiremote

Is the feature you are testing requiring changing a state of the app from two different devices/browser?

**Comment by cannuk** [comment]
Yes and no. The feature/test in question is a chat application. While I think there is some trickery I could do to use different tabs to work around this (open chats in different tabs), it seems like multiremote is appropriate. Ultimately the test I am trying to create is:

1. Open chat widgetA
2. Open chat widgetB
3. Send message from widgetA to widgetB
4. Verify widgetB received message.
5. Send message from widgetB to widgetA
6. Verify widgetA received message

**Comment by christian-bromann** [comment]
This won't be fixed in v4 but will definitely land in v5
