### ISSUE TITLE
How to import cucumber-boilerplate tests to new webdriverio

### ISSUE THREAD

**Issue by vitaly87** [webdriverio/webdriverio#1457]
## The problem
Hi,
I am using git hub cucumber-boilerplate, my issue as I saw that the old code cant support logs.
My issue is that I want to movie all my tests that relay on  cucumber-boilerplate and use them with this new webdriverio.
Is it possible , if yes what us the correct way to do that.

**Comment by christian-bromann** [comment]
Yeah sure. Make sure you check out webdriver.io and check out the test runner. You should use that with cucumber. Then move all your step definitions over but make sure they work with cucumber.js. In the cucumber-boilerplate project we use a different framework called yadda.

**Comment by vitaly87** [comment]
what parts I need to take from cucumber-boilerplate  project that it can run with new webdriverio?
basically, I want to keep the clear mapping between text to functions like you did on cucumber-boilerplate .
