### ISSUE TITLE
Overwriting exclude property when using multiple config files doesn't work

### ISSUE THREAD

**Issue by dgasi** [webdriverio/webdriverio#1459]
I have an issue when inheriting from main config file, exclude property doesn't get overwritten and I can't run files from second conf file because those files are excluded in main config file:

 **main.conf:**
` specs: [
        './specs/some.spec.js'],
    suites: {
        smoke: [
            './smoke.spec.js'
        ],
        suite1: [
            './specs/suite1.spec.js',
    },
    exclude: [
         './specs/suite1.spec.js',
         './specs/somespec2.spec.js'
    ],`

**second conf:**
` suites: {
        suite1: [
            './specs/suite1.spec.js',        
    },
exclude: [
  './specs/somespec2.spec.js'
    ],`

So now I'm running configuration file 2 and this suit1.spec can't be run because it's excluded in main conf file. 
But doesn't it get overwritten with exclude form second config file?

Any ideas how to exclude this suite from main config file but than be able to run it with second config file.

currently using:
 webdriverio: 4.2.1
node: 6.3.0
with jasmine framework              

And I'm using wdio testrunner to run tests.

**Comment by christian-bromann** [comment]
How do you inherit from `main.conf`? Depending on how you do that but make sure both exclude arrays aren't getting merged. So instead just overwrite it directly:

```js
// second conf
exports.config.exclude = [ './specs/somespec2.spec.js' ]
```

**Comment by dgasi** [comment]
Thanks man. This worked fine.
