### ISSUE TITLE
touchPerform not working

### ISSUE THREAD

**Issue by talarari** [webdriverio/webdriverio#1463]
copied from docs:
```
client.touchPerform({
                action: 'press',
                type: {
                    x: 100,
                    y: 250
                }
            });
```
getting 
An unknown server-side error occurred while processing the command. Original error: [object Object] is not iterable!

tried :
```
client.touchPerform([{
                action: 'press',
                type: {
                    x: 100,
                    y: 250
                }
            }]);
```
getting :
An unknown server-side error occurred while processing the command. Original err
or: Cannot set property 'offset' of undefined

**Comment by christian-bromann** [comment]
We are planning to build a better API around touch events. Can't say anything yet about release dates tho.

**Comment by talarari** [comment]
i figured this out, the docs are wrong.
if you do this, it works:

```
 client.touchPerform([{
                        action: 'press',
                        options: {
                            x: 0,
                            y: 0
                        }
                    },{
                        action: 'moveTo',
                        options: {
                            x: 0,
                            y: 200
                        }
                    },{
                        action: 'release'
                    }]);
```

**Comment by christian-bromann** [comment]
Fixed docs. Thanks!

**Comment by okryvorotko** [comment]
@talarari what version of release should I pull to use this method?

I'm getting an error: `Method has not yet been implemented` on `"webdriverio": "^4.2.3"` version.

**Comment by petrmiko** [comment]
Have anyone encountered following issue with touchPerform?
`Method has not yet been implemented Error: Method has not yet been implemented
    at touchPerform([object Object])`

I'm trying to invoke following and it results in aforementioned error:
```javascript
driver.element(selector)
  .then(elementWrapper => {
      return driver.touchPerform([{
          action: 'tap',
          options: {
              el: elementWrapper.value.ELEMENT,
              x: 0,
              y: 0,
              count: 1
          }
          }]);
  });
```

Testing against Android with:
- Appium: 1.5.3
- WebdriverIO: 4.2.15

Is the method really not implemented yet (if so, it is weird that above is stated, that it works), or any idea, what am I doing wrong, please? Thanks in advance!

**Comment by christian-bromann** [comment]
@petrmiko this method only works if you run native apps, not hybrid or web apps it should be a native app

**Comment by petrmiko** [comment]
@christian-bromann I see, thanks - such info might be useful in docs. Is there an alternative for hybrid/web apps for touch click (tap and long touch variant)? I ask since touchClick and touchLongClick are stated in docs as deprecated so I assume they will be removed in newer versions - moreover they work only on android, not iOS.
