### ISSUE TITLE
chaining element selector will not match deep descendants 

### ISSUE THREAD

**Issue by scags9876** [webdriverio/webdriverio#1465]
## The problem

Chaining a selector will fail if the element is not an immediate descendant of the base element.    It should search the entire descendant tree of the base element.

## Environment

* WebdriverIO version: >= 4.1.0
* Node.js version: 6.2.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Standalone

## Details

With the fix to https://github.com/webdriverio/webdriverio/issues/1354 a change was made to the findStrategy of chained elements to use the 'relative' flag.   While this fixed the issue, it uncovered the fact for us that the relative selection only selects immediate children, and not deep descendants.   

There should be an easy for this: changing lib/helpers/findElementStrategy.js:8 to:

```
    let xpathPrefix = relative ? './/' : '//'
```

That is, changing the relative xpathPrefix to `.//` from `./`

## Link to Selenium/WebdriverIO logs

https://gist.github.com/scags9876/ba6e4eb23da25d58cfa17cd3d9e02830

### Does not work

Looking for a label which is inside a containing div in the parent div.  This results in an error:

```
webdriverio
    .remote(options)
    .init()
    .url('http://output.jsbin.com/topaku/1')
    .element('#topdiv')
    .element('label=Took')
    .click()
    .end();
```

**Comment by scags9876** [comment]
It looks to me like this issue has the same root cause:

 https://github.com/webdriverio/webdriverio/issues/1415

**Comment by christian-bromann** [comment]
@scags9876 looking at the logs the xpath looks about right:
```
Executing: [find child element: 0 [[FirefoxDriver: firefox on MAC (b124c848-afb0-a844-bbcf-0e62cdbb596b)] -> id: topdiv], By.xpath: ./label[normalize-space() = "Took"]])
```
This should find the label inside the topdiv element:
```html
<div id="topdib">
    <label>Took</label>
</div>
```

**Comment by scags9876** [comment]
@christian-bromann thanks for the reply.   

The problem is when the element being queried is a child of a child.   Such as seen here: http://jsbin.com/topaku/edit?html,output  

Or directly here:

```
  <div id="topdiv">
    <div>
      <label>Took</label>
    </div>
  </div>
```

First level descendants work fine, it is when the element is a deeper descendant that the problem manifests.

**Comment by christian-bromann** [comment]
Merged PR. Thanks again!
