### ISSUE TITLE
Suggestion: allow execute script's result to be promise of currently allowed things

### ISSUE THREAD

**Issue by 3n-mb** [webdriverio/webdriverio#1468]
It would greatly simplify tests, if `func` in `client.execute(func);` could return a promise, which gets waited on and unwrapped either to value, or to exception.
Reactions to value and exception can be currently existing ones.

This can be extended to allow `done` in  `client.executeAsync(function(done){ ... });` to accept promises, doing the same. Side effect here will be an auto-magic proper reporting of errors.

I am not sure, if this suggestion in this form belongs here, or in selenium repo.

**Comment by christian-bromann** [comment]
@3n-mb thanks for the suggestion

I think it it possible to maybe merge both commands into one and wrap it in a way that it would respect promise returns to handly async. However most browser don't support native JS promises yet so people would have a hard time using it. What would you suggest in these cases?

**Comment by 3n-mb** [comment]
@christian-bromann my use case is testing in [Spectron](https://github.com/electron/spectron). There we have only one browser, that already supports native promises. More so, an app is written in TypeScript with compile target JS6. This allows to inject into client's window `beforeAll ...` a shim, to which await clauses are expanded by TypeScript. So, code looks like JS7 (?). Actual snippet, jasmine is driving webdriver:
```
itAsync('...', async function() {
	let r = (await webDriverClient.executeAsync(
		async function(appDomain, done) {
			let fs = await w3n.storage.getAppFS(appDomain);
			if (fs) { done(true); }
			else { logError(`FS is not produced for app ${appDomain}`) }
		}, appDomain)).value;
	expect(r).toBe(true);
});
```
With suggested implemented, this will change to
```
itAsync('...', async function() {
	let r = (await webDriverClient.execute(
		async function(appDomain) {
			let fs = await w3n.storage.getAppFS(appDomain);
			return !!fs;
		}, appDomain)).value;
	expect(r).toBe(true);
});
```
With TypeScript being meticulously close to JS7, we are talking about future JS API, which can already be used by Electron's app developers. And given increased complexity of apps, promises save the day. Promises also tend to promisify everything they touch. As a result one deals with tons of promises at testing.

Writing this example, I've noticed that `executeAsync` with injection of `done()` will be not needed in most of cases. But its better be kept, as use of `done()` sometimes is a requirement, like deferred-pattern is needed in some cases, while in most cases it is considered an anti-pattern.

### Old and new may coexist
[Docs say](http://webdriver.io/api/protocol/execute.html), quote, "script result will be returned to the client as WebElement JSON objects". Nobody retruns promises, anyway. When wrapping/putting result into "WebElement JSON object", we may check if result is a promise-like object. If it is not promise-like, everything goes like it is now. But if it is promise, we unwrap it, with respective then/catch branches setting either result or exception of execution.

**Comment by christian-bromann** [comment]
See https://github.com/webdriverio/webdriverio/issues/999#issuecomment-434879020
