### ISSUE TITLE
"element not found" with multiremote parrarell runs

### ISSUE THREAD

**Issue by straris** [webdriverio/webdriverio#1470]
## The problem
The below simple test will fail with _'element not visible'_ exception although it has already found the element and filed the input.
The issue seems to be related to parallel browser runs as running the test concurrently has no issues.

## Environment

* WebdriverIO version: 4.2.1
* Node.js version: 4.4.5
* wdio testrunner
* synchronous tests
* multiremote

## Link to Selenium/WebdriverIO logs

https://gist.github.com/straris/c300e2ec1cd748cd9d34e545fa129f41#file-selenium-log

## Code To Reproduce Issue 

```
var assert = require('assert');

describe('webdriver.io page', function () {
  it('should have the right title - the fancy generator way', function () {
    browser.url('http://www.eyeem.com/login')
    browser.addValue('input[data-field-type="email_or_nickname_exists"]', "blabla")
    browser.addValue('input[data-field-type="existing_password"]', "blabla")
    browser.click('.wrapper-signuplogin button')

    assert.equal(browser.getTitle(), 'EyeEm');
  });
});
```

## Capabilities
```
  capabilities: {
    chrome: {
      desiredCapabilities: {
        browserName: 'chrome'
      }
    },
    firefox: {
      desiredCapabilities: {
        browserName: 'firefox'
      }
    }
  },
```

**Comment by christian-bromann** [comment]
Can you post the selenium logs please?

**Comment by straris** [comment]
https://gist.github.com/straris/c300e2ec1cd748cd9d34e545fa129f41#file-selenium-log

**Comment by christian-bromann** [comment]
The error is saying `org.openqa.selenium.ElementNotVisibleException: Element is not currently visible and so may not be interacted with`. Selenium finds elements even though they are not visible. In order to interact with an element it has to be visible though.

**Comment by christian-bromann** [comment]
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
