### ISSUE TITLE
Searching for geckodriver?

### ISSUE THREAD

**Issue by DaveStein** [webdriverio/webdriverio#1473]
## The problem

Having an issue I described here: https://github.com/vvo/selenium-standalone/issues/199
Just not sure if it's actually `selenium-standalone` or this package.

## Environment

* WebdriverIO version: 4.2.1
* Node.js version: 6.3.0 (although reproduced on a machine with 5.* and 4.*)
* wdio config of syncronous tests:
```
exports.config = {
  specs: [
    'tests/**'
  ],
  maxInstances: 1,
  capabilities: [{
    browserName: 'chrome'
  }]
};
```

## Link to Selenium/WebdriverIO logs

Not sure where the logs are? Sorry I'm a noob ;)

## Code To Reproduce Issue [ Good To Have ]
I run `selenium_install` in one tab, run command to start my server, then `test` in another tab.

```
// ---WebdriverIO Testing---
gulp.task('selenium_install', function(cb) {
  gutil.log('Checking selenium-standalone installation...');
  selenium.install({
    version: '2.48.2',
    baseURL: 'https://selenium-release.storage.googleapis.com',
    drivers: {
      chrome: {
        version: '2.22',
        arch: process.arch,
        baseURL: 'https://chromedriver.storage.googleapis.com'
      }
    },
    progressCb: function(total, progress) {
      gutil.log('progressing');
      var bar = new ProgressBar('selenium-standalone & chromedriver installation [:bar] :percent', {
        total: total,
        complete: '=',
        incomplete: ' ',
        width: 20
      });
      bar.tick(progress);
    }
  }, function(err) {
    if (err) {
      gutil.log(gutil.colors.red(err));
      return cb();
    }

    gutil.log('Installed');
    cb();
  });
});

gulp.task('selenium_start', ['selenium_install'], function(cb) {
  selenium.start({
    version: '2.48.2',
    spawnOptions: {
      stdio: 'ignore'
    }
  }, function(err, child) {
    gutil.log('Starting selenium-standalone server...');
    if (err) {
      gutil.log(gutil.colors.red(err));
      return cb();
    }
    selenium.process = child;
    cb();
  });
});

gulp.task('test', ['selenium_start'], function() {
  return gulp.src('wdio.conf.js').pipe(webdriver())
  .on('end', function() {
    selenium.process.kill();
  });
});
```

**Comment by christian-bromann** [comment]
sorry but this doesn't tell anything about a problem? Can you explain more?

**Comment by DaveStein** [comment]
@christian-bromann The link I have should explain it better than this post... just didn't want to repeat myself that hard last night :P Anyway it seems when I go to run tests, selenium is looking for gecko driver, even tho webdriverio isn't requesting it via my config. So not sure if selenium is trying to look for a driver cause a bug, or that webdriverio is sending something wrong. Gonna try and dig some more.

**Comment by DaveStein** [comment]
I am hacking in the selenium-standalone code. Totally a bug there it seems

**Comment by christian-bromann** [comment]
@DaveStein I would recommend to use the wdio-selenum-standalone-service

**Comment by DaveStein** [comment]
@christian-bromann Is that a fork of the other? Or just a whole set of code with webdriver in mind?

**Comment by christian-bromann** [comment]
it is a service that is using selenium-webdriver but is better integrated into webdriver.io, see http://webdriver.io/guide/services/selenium-standalone.html

**Comment by DaveStein** [comment]
I'll check it out. First I'm gonna help other package get bug fix tho :D
