### ISSUE TITLE
How to use an older version of Chrome? TravisCI Chrome version is "too old"

### ISSUE THREAD

**Issue by mohsen1** [webdriverio/webdriverio#1474]
## The problem
My tests are all passing locally with Chrome 51 installed. In TravisCI environment however I get [this error](https://travis-ci.org/rah-foundation/website/builds/146009864#L330):

```
ERROR: unknown error: Chrome version must be >= 49.0.2623.0
```

I'm not sure what version of Chrome I have in TravisCI. If you disable container environment with `sudo: required` in `.travis.yml` file you'll have a version of Chrome that works for Karma and Protractor runners but WebdriverIO fails with above error.

How can I tell WDO to use the older version of Chrome and not complain? 

## Environment

* WebdriverIO version: 4.2.1
* Node.js version: v6.3.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): I guess standalone, see https://github.com/rah-foundation/website/blob/master/wdio.conf.ts
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable): wdo spec reporter

**My project is open source at https://github.com/rah-foundation/website/tree/e61503aa66f753ae13cbec34f6a84b903599a90f**

**Comment by christian-bromann** [comment]
@mohsen1 I would recommend to use cloud services like Sauce Labs for CI. That will help you to debug issues way faster then using a VM browser in Travis. Since your project is open source is doesn cost a penny 😉 

However if you want to stick with your current solution just specify a version of chrome in your desired capabilities like:
```js
    capabilities: [{
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instance available you can make sure that not more than
        // 5 instance gets started at a time.
        maxInstances: 5,
        //
        browserName: 'chrome',
        version: 51
    }],
```
