### ISSUE TITLE
Multiple isVisible() calls changes output

### ISSUE THREAD

**Issue by jrmalin** [webdriverio/webdriverio#1475]
When I call my command 'homeA' as described below, 'equalTest' is another custom command that prints the boolean value of 'isVisible' as false (This is the correct response.):

`    client.addCommand('homeA', function(file) {
       return this.isVisible('.Slide__subtitle___3Cbr4').then(function(isVisible) {
           this.equalTest('Homepage', isVisible, file);
       })
    });`

However, if I call 'homeB' as described below, 'equalTest' prints the value of 'isVisible' as true (This is the incorrect response.):

```
    client.addCommand('homeB_helper', function() {
        if(!this.isVisible('.Slide__subtitle___3Cbr4')) return false;
        if(!this.isVisible('.NavBar__link___3kcZW=Coaches Choice')) return false;
        return true;

    });

    client.addCommand('homeB', function(file) {
        return this.homeB_helper().then(function(isVisible) {
            this.equalTest('Homepage', isVisible, file);
        })
    });
```

If nothing else has been changed, I don't understand a scenario in which it could evaluate to false in the first one, yet true in the second.

**Comment by christian-bromann** [comment]
Hold on, you have a wild mixture of sync and async usage of commands here. You need to fix that first before everything else 😉

**Comment by jrmalin** [comment]
That could definitely be my problem, how do I fix that?

**Comment by christian-bromann** [comment]
Let's continue convo on Gitter
