### ISSUE TITLE
how to select an native android element by id?

### ISSUE THREAD

**Issue by talarari** [webdriverio/webdriverio#1476]
from what i can find this is possible in the java client like this:
http://stackoverflow.com/a/22325414/2029019

i'm trying to use it to get the Allow button in an android 6 permission popup
![image](https://cloud.githubusercontent.com/assets/4973087/17031632/cbc65f04-4f7d-11e6-945c-a70a11128e52.png)

**Comment by talarari** [comment]
answering myself for documentation:

i can select the element using uiAutomator like this:
client.element('android=new UiSelector().resourceId("com.android.packager/someid")');
or like this:
client.element('//*[@resource-id="com.android.packager/someid"');

**Comment by rahulmr** [comment]
Thanks @talarari but is it possible to add custom command to use only id like `btnLogin `instead of `android=new UiSelector().resourceId("com.myapp.package.am:id/btnLogin`
