### ISSUE TITLE
Possible infinite recursion

### ISSUE THREAD

**Issue by just-boris** [webdriverio/webdriverio#1478]
## The problem

While I doing #1461 I got a note from @j0tunn, that there is possible recursion during taking screenshot. 

The thing is that I could reproduce it with current master, so I'd like to put it as a separate ticket.

## Environment

* WebdriverIO version: 4.2.1
* Node.js version: v6.3.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio runner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable):

## Code To Reproduce Issue

Given the following config: 

```js
var exec = require('child_process').exec;
var phantomjs;

exports.config = {
    specs: [
        './test.js'
    ],
    capabilities: [{
        browserName: 'phantomjs'
    }],

    screenshotPath: 'shots',
    baseUrl: 'http://webdriver.io',
    waitforTimeout: 10000,
    framework: 'mocha',
    reporters: ['dot'],

    onPrepare: function() {
        return new Promise(resolve => {
            phantomjs = exec('phantomjs --webdriver=4444')
            phantomjs.stdout.once('data', (message) => {
                resolve();
                setTimeout(() => {throw new Error('surprise!')}, 1000);
            })
        })
    },
    onComplete: function() {
        phantomjs.kill();
    }

};
```

And the following test
```js
describe('test suite', () => {
  it('is a test', () => {
    browser.url('/');
    browser.waitUntil(() => false, 6000);
  });
})
```

Under this circumstances the code falls into infinite loop while trying to take screenshot. The crucial points here that we have uncaught exception in main process and long-running command in test process. The test process tries to send data to main process but gets: `Error: channel closed`.

**UPD** To check that there is a recursion, after test command run this `ps ax | grep "webdriverio/build/lib/runner.js"`, you will see hung up test process.

I don't know how this possible to get the same condition in the real world, but this is the only way how to reproduce this.

**Comment by christian-bromann** [comment]
@just-boris can we close this one now?

**Comment by just-boris** [comment]
No, this is still open issue.

I will look at @j0tunn implementation, and check, whether is fixes this or not. Now I am not actually sure about this.

**Comment by christian-bromann** [comment]
This issue is resolved. Thanks @just-boris and @j0tunn
