### ISSUE TITLE
why does addCommand exist? 

### ISSUE THREAD

**Issue by talarari** [webdriverio/webdriverio#1479]
why not just extend the browser prototype?

when adding extensions as code and dynamically with string names we get benefits of some editors (webstorm for instance) understanding that the function is defined and allows clicking into it.

i'm guessing there's a reason, just curious.

**Comment by christian-bromann** [comment]
There is absolutely a reason: each command is wrapped into couple of other functions (like an onion) to ensure the functionality (like sync execution and command hooks) of each one.

Fyi: please join our gitter channel! Issue should only be created for bugs not questions 😉

**Comment by talarari** [comment]
cool, thanks for the answer! i'll ask on gitter next time
