### ISSUE TITLE
Show the selector when fails

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1481]
```diff
-An element could not be located on the page using the given search parameters
```

![img-2016-07-22-19-01-09](https://cloud.githubusercontent.com/assets/803674/17063173/aff1c93c-503e-11e6-8f84-827ba91233e6.png)

Is possible to show a failed selector?

**Comment by christian-bromann** [comment]
Fix will be released with next version. Thanks for reporting.
