### ISSUE TITLE
Video compability

### ISSUE THREAD

**Issue by sean-hill** [webdriverio/webdriverio#1482]
Hey,

I'd love to have some way to record the entire selenium session and watch it later for debugging purposes. I'd like to open this issue as a discussion of how we could possibly do this.

Any suggestions would be great :)

**Comment by sean-hill** [comment]
Reference:

http://roadtoautomation.blogspot.in/2013/03/screen-recording-video-of-java-webdiver.html

**Comment by christian-bromann** [comment]
@sean-hill definitely possible to create a service that screencasts the test. Just create that ffmpeg child process in the before hook and kill it in the after hook. Then you need to figure out where to move the file. As a said this should be a separated project/service and does not belong into the webdriverio core.

**Comment by sean-hill** [comment]
Awesome. Thanks!

-- 
Sean Hill
me@seanhill.info
www.seanhill.info
