### ISSUE TITLE
document recommended way to activate babel-runtime

### ISSUE THREAD

**Issue by jedwards1211** [webdriverio/webdriverio#1485]
Requiring `babel-polyfill` at the wrong time can cause problems with some frameworks (e.g. mocha) that monkeypatch `.finally` onto whatever `Promise` is in global scope (see https://github.com/webdriverio/webdriverio/issues/1477)

The [configuration docs](http://webdriver.io/guide/getstarted/configuration.html) make it clear how to use `babel-register` to compile test files with Babel, but as of Babel 6 (not sure about Babel 5), **`babel-register` does not include `babel-polyfill`**.  Hence the docs should illustrate where to include `babel-polyfill` so that it polyfills `Promise` before any `wdio` framework monkeypatches `.finally` onto it.

**Comment by christian-bromann** [comment]
Would you like to take this @jedwards1211 ?

**Comment by jedwards1211** [comment]
Sure!

**Comment by jedwards1211** [comment]
Looks like it might be best to use [babel-runtime](https://babeljs.io/docs/plugins/transform-runtime/) instead of `babel-polyfill`
