### ISSUE TITLE
some recommendations in config docs aren't compatible with Babel 6

### ISSUE THREAD

**Issue by jedwards1211** [webdriverio/webdriverio#1486]
It seems the config docs were written for Babel 5 and haven't been updated since Babel 6 came out.

As recommended in the [docs](http://webdriver.io/guide/getstarted/configuration.html), I added `"blacklist": ["regenerator"]` to my `.babelrc` and got the following error since I'm using Babel 6:
```
ERROR: [BABEL] /usr/src/app/test/index.js: Using removed Babel 5 option: base.blacklist - Put the specific transforms you want in the `plugins` option
```

Maybe it's better to just use regenerator?  I know it's unnecessary with the latest node, but there's less to worry about (e.g. async function support) if the babel config is simpler.

**Comment by jedwards1211** [comment]
@christian-bromann shall I fix this along with https://github.com/webdriverio/webdriverio/issues/1485?

**Comment by christian-bromann** [comment]
That would be terrific, thanks!

**Comment by christian-bromann** [comment]
ping @jedwards1211

**Comment by jedwards1211** [comment]
I made the PR, did you see it?

**Comment by jedwards1211** [comment]
Wait nevermind, it's in my branch but somehow I didn't create the PR
