### ISSUE TITLE
How to configure wdio.js file, to run test suites in order ?

### ISSUE THREAD

**Issue by srikanthrl** [webdriverio/webdriverio#1487]
## The problem

I use grunt plugin to run selenium tests with the WebdriverIO testrunner.  
In my "specs" folder I have 3 test folders
- Login 
- License
- User

In the wdio file, I configured **specs** as 
specs: 
    ['./test/specs/**/*.js'],

As per my test scenario first it should login, then add license and then create user.

Right now, tests are not running in sequential order. First, its running .js files(test cases) from User folder, then  from license folder and finally from Login folder .

**My  Grunt file looks like this:** 

  webdriver: {
            options: {
                logLevel: 'command',
                waitforTimeout: 10000,
                framework: 'mocha',
                coloredLogs: true
            },
            testTargetConfigFile: {
                configFile: './wdio.conf.js'
            }
        }

## Environment

* WebdriverIO version: v4.1.1
* Node.js version: v4.4.7
* Grunt: v1.0.1
* Page Object Pattern

**Comment by christian-bromann** [comment]
Your test should be independent from each other and not require a certain order of execution. I believe Mocha orders them by alphabet you can also set the order by doing ['first.js', 'second.js', ...]` instead of using glob.
