### ISSUE TITLE
Documentation in retry.md has drifted from master branch

### ISSUE THREAD

**Issue by mpfilbin** [webdriverio/webdriverio#1489]
## The problem

The documentation in [retry.md](/webdriverio/webdriverio/blob/master/docs/guide/testrunner/retry.md) does not match what is published at [http://webdriver.io/guide/testrunner/retry.html](http://webdriver.io/guide/testrunner/retry.html). Specifically concerning the versions of [wdio-mocha-framework](https://github.com/webdriverio/wdio-mocha-framework) and [wdio-jasmine-framework](https://github.com/webdriverio/wdio-jasmine-framework) documented as required for the retry behavior to work.

It appears there was a change introduced at 9ded1109529a30b8875c8fff41915bab61899f17 but that change has not yet been published to the documentation site.

## Environment

* WebdriverIO version: 4.2.3
* Node.js version: N/A
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): N/A
* if wdio testrunner, running synchronous or asynchronous tests: N/A
* Additional wdio packages used (if applicable): wdio-jasmine-framework/wdio-mocha-framework

## Details

The document on the master branch specifies the required version of `wdio-mocha-framework` to be `0.3.0` and the version of `wdio-jasmine-framework` to be `0.2.0`; however, the documentation at [http://webdriver.io/guide/testrunner/retry.html] has this reversed.

## Link to Selenium/WebdriverIO logs

Not Applicable

## Code To Reproduce Issue [ Good To Have ]

Not Applicable

**Comment by christian-bromann** [comment]
Thanks for filing this issue, I haven't had a chance to deploy the latest released version. Will do it asap.

**Comment by christian-bromann** [comment]
Website got deployed and it should be correct now.
