### ISSUE TITLE
css -> xpath selector - has different symantics

### ISSUE THREAD

**Issue by kurtharriger** [webdriverio/webdriverio#1493]
## The problem

When you write a selector matching class and text such as `.element('.container=Text')` this gets converted to an xpath `//*[contains(@class, "container") and normalize-space() = "Text"]`
this however will also match `container-header` which is not what is expected for a css selector for `.container` which would only match if the full class name is `container`. 

As a workaround we have been using xpath explicitly with `concat` and `normalize-space` to search for padded class name as follows:

`//div[contains(concat(" ", normalize-space(@class), " "), " container " and normalize-space() = "Text"]`

## Environment

* WebdriverIO version: "^4.0.9"
* Node.js version: 5.11.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):testrunner
* if wdio testrunner, running synchronous or asynchronous tests:async
* Additional wdio packages used (if applicable): na

**Comment by christian-bromann** [comment]
Does your workaround would find this element:
```html
<div class="container">..</div>
```
See that I don't have spaces around it.

**Comment by christian-bromann** [comment]
> which is not what is expected for a css selector for .container

It is expected. Given the following html:

```html
<span class="box foobar">foobar</span>
<span class="box">test</span>
```
calling
```js
document.querySelectorAll('span.box')
```
returns both span elements. If you want to only query the elements containing only `container` you have to find a different way doing it. Maybe looking for it within a different element.

**Comment by mynoheart** [comment]
I have similar problem.
Html:
```html
  <div class="container">Text</div>
  <div class="container-sub">Text</div>
```
JS:
```javascript
  $$('.container*=Text');
  // returns two divs
```

Right way for select elements with class in http://stackoverflow.com/a/34779105

**Comment by christian-bromann** [comment]
@mynoheart this is also expected, if you use the `$$` command it will fetch all elements with `"Text"` in it

**Comment by mynoheart** [comment]
@christian-bromann text equal, yes, but classes different.

Selector ```javascript $$('.container*=Text'); ``` shouldn't return element with text "Text" AND class ".container"?

**Comment by christian-bromann** [comment]
> Selector javascript $$('.container*=Text'); shouldn't return element with text "Text" AND class ".container"?

Yes you're rigth

**Comment by mynoheart** [comment]
But selector now return two elements and this all the same not expected behavior?
Because class ".container" and ".container-sub" different.

You watch link in my previous message (from stackoveflow)?
