### ISSUE TITLE
Cannot select elements by ID+Text if the Text is only a single word.

### ISSUE THREAD

**Issue by kwright1** [webdriverio/webdriverio#1494]
## The problem

Issues finding elements that have a specific id and single word text.  Multi word text is fine.  .class= and tag= seem to not have this problem.

## Environment

* WebdriverIO version: 4.2.3
* Node.js version: 6.3.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable):

## Details

If you make a selector like '#id-here=Word' it won't work.  The logs seems to show it trying to use id-here=Word as an id rather than splitting on the =.  If you include multiple words '#id-here=Word Two' it will correctly interpret the id as #id-here and text as Word Two.

The latter case gets converted to xpath, the former does not.

Tried with both *= and =.

## Link to Selenium/WebdriverIO logs
https://gist.github.com/kwright1/a3fb8a4f1273c0a196c2e208cd161f0c

## Code To Reproduce Issue [ Good To Have ]
```javascript
var assert = require('assert');
describe('webdriver.io page', function() {
   it('should work with ids and single word text', function () {
        browser.url('http://webdriver.io');
        var visible = browser.isVisible('#What-is-WebdriverIO*=What');
        assert.equal(visible, true);
    });
	
    it('should work with ids and multi word text', function () {
        browser.url('http://webdriver.io');
        var visible = browser.isVisible('#What-is-WebdriverIO*=What is');
        assert.equal(visible, true);
    });
	
	after(function() {
		console.log(browser.log('client'));
	});
});
```

**Comment by christian-bromann** [comment]
Thanks for filing this issue. It's fixed and will be released with the next version.
