### ISSUE TITLE
Whole page screenshot

### ISSUE THREAD

**Issue by bondarum** [webdriverio/webdriverio#1497]
Since webdrivercss is not supported in webdriverio v 3.*.* and 4.*.*, how can I take whole page screenshot using webdriverio?

**Comment by christian-bromann** [comment]
Take a look at https://www.npmjs.com/package/wdio-screenshot

**Comment by christian-bromann** [comment]
Also, feel free to ask those kind of question in our gitter chat. People can help you there way faster than here. This should only be for bugs.
