### ISSUE TITLE
getValue() result is trimmed

### ISSUE THREAD

**Issue by gronke** [webdriverio/webdriverio#1501]
Consider the following fixture and test

```html
<textarea id="target"></textarea>
```

```javascript
var expect = require('chai').expect
var testValue = 'some text\n with line breaks at the end\n\n'
return browser
  .setValue('#target', testValue)
  .pause(50)
  .getValue('#target')
  .then(function(value) {
     expect(value).to.be.equal(testValue)
  })
```

### Current Result
```
expected 'some text\n with line breaks at the end' to equal 'some text\n with line breaks at the end\n\n'
```
Visually checking the textarea reveals the value including all line-breaks was set properly, but the output of `getValue()` trims the trailing line breaks.

### Expected Result
Both values should be equal.

**Comment by christian-bromann** [comment]
There is nothing we can do about that. We just return the values we get from the browser driver. This behavior might be even different between the browser driver. I am not sure how this should be relevant for your tests but this is a Selenium issue we can't fix.
