### ISSUE TITLE
Missing onComplete event for multiremote tests

### ISSUE THREAD

**Issue by artur-michalak** [webdriverio/webdriverio#1504]
## The problem

I'm trying to run multiremote tests with jasmine reporter under gulp. It works but i faced problems with closing selenium instances after tests are completed.

Wdio capabilities looks like follow:
```
    capabilities: {
        'myChrome': {
            desiredCapabilities: {
                browserName: 'chrome'
            }
        },
        'myFirefox': {
            desiredCapabilities: {
                browserName: 'firefox'
            }
        }
    },
    framework: 'jasmine',
    services: ['selenium-standalone']
```

I checked code and it looks like onComplete event won't be triggered for multiremote run due to this return statement
https://github.com/webdriverio/webdriverio/blob/6e07ce5057b42417f7a3c7c4341b65ddb840b9b3/lib/launcher.js#L130

For quick check i just copied these two lines above return:
```
/**
         * run onComplete hook
         */
        await this.runServiceHook(launcher, 'onComplete', exitCode)
        await config.onComplete(exitCode)
```

And it started to work perfectly. If something is not clear please mention me in comment.

## Environment

* WebdriverIO version: 4.2.3
* Node.js version:
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronus
* Additional wdio packages used (if applicable):
```
"wdio-jasmine-framework": "^0.2.5",
"wdio-selenium-standalone-service": "0.0.5",
"wdio-spec-reporter": "0.0.3",
```

**Comment by christian-bromann** [comment]
Fixed! Will be released with next version. Thanks!
