### ISSUE TITLE
click at parent element coordinates should also trigger click on child if child occupies parent at point where click occurs. Using an offset also doesn't fix problem

### ISSUE THREAD

**Issue by maggiesavovska** [webdriverio/webdriverio#1505]
## The problem

MARKUP: 
```html
<div class="add"><input type="checkbox" class="inputCheckbox" id="checkbox34" onclick="someEventHandler()" name="q4">
    <label for="checkbox34">
        <span class="inputCheckboxLabel">Add</span>
    </label>
</div>
```

EXPECTED BEHAVIOR: Using "moveToObject" to click on parent div ".add" should trigger click event handler on child "label" as long as child is visible and accessible at point where parent is clicked (middle of parent as long as no offsets are specified).

ACTUAL BEHAVIOR: When clicking on parent element ".add", if child element "label" does not occupy 100% of parent width/height then click does not affect child "label" (even though click should occur at parent middle point where child IS PRESENT AND ACCESSIBLE in this case).

RELATED ISSUE MOVETOOBJECT: Assuming that perhaps the click is not actually happening at the parent middle point I tried providing an offiset. Providing an offset to moveToObject doesn't seem to have an effect. The coordinates remain at 0, 0. (see log)
13:47:54.187 INFO - Executing: [mousemove: 0 true])
13:47:54.234 INFO - Done: [mousemove: 0 true]

RELATED ISSUE MOVETO: Assuming that perhaps the click is not actually happening at the parent middle point I tried providing an offset. Using moveTo with an element json id and offset also doesn't seem to work (coordinates remain at 0, 0). 

## Environment

* WebdriverIO version: 3.7.3
* Node.js version: 5.8.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): standalone

## Code
```
//with moveToObject
        it('should click button', function(done){
                driver.moveToObject('.add', 40, 10).then(function(){
                    driver.pause(500).then(function(){
                        driver.buttonPress().then(function(){
                            console.log('bp done');
                            done();
                        });
                    });
                }).catch(function(err){console.log(err.message)});
        });

//with moveTo
        it('should click button', function(done){
            driver.element('.add').then(function(result){
                driver.moveTo(result.value.ELEMENT, 40, 10).then(function(){
                    driver.pause(10000).then(function(){
                        driver.buttonPress().then(function(){
                            console.log('bp done');
                            done();
                        });

                    });

                }).catch(function(err){console.log(err.message)});

            });
            
        });
```
## Link to Selenium/WebdriverIO logs

with moveToObject: 
https://gist.github.com/maggiesavovska/700d44f44d08a9ebef38289f386ba3d2

with moveTo: 
https://gist.github.com/maggiesavovska/f85869d687234c498cef24e8f849d028

**Comment by christian-bromann** [comment]
> The coordinates remain at 0, 0. (see log)

This issue get fixed and will be released soon

Please try again with the next release. Maybe the moveTo fix will get this working. If not I am afraid there is nothing really we can do about it. Selenium takes care of the click action and should propagate events properly.

Thanks for posting the issue!
