### ISSUE TITLE
Cucumber tests failing due to intermittently 'undefined' steps

### ISSUE THREAD

**Issue by dimirey** [webdriverio/webdriverio#1507]
## The problem

My cucumber tests often fail due to an issue where defined steps are mistakenly considered undefined. When run again, the failed 'undefined' steps occasionally pass correctly as defined. This happens when running ~16 tests in parallel. The failures started after updating webdriverio and the cucumber framework to the latest versions. 

## Environment

* WebdriverIO version: v4.2.3
* Node.js version: v6.1.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous 
* Additional wdio packages used (if applicable): wdio-cucumber-framework@0.2.4

## Details

This doesn't seem to happen when running tests individually, only when tests (which share step definitions) are run in parallel.

## Link to Selenium/WebdriverIO logs

unable to find any logs which have significance to this

## Code To Reproduce Issue [ Good To Have ]

Create a user and assert that the settings conform with the Org settings I enter in the user details "A" "B" "C" "D":
```
module.exports = function(){

var add_user = require("../support/pages/page_admin_users_adduser.js");

this.When(/^I Enter in the user details "([^"]*)" "([^"]*)" "([^"]*)" "([^"]*)"$/, function (arg1, arg2, arg3, arg4) {
            
            add_user.first_name_textfield.waitForVisible()
            add_user.first_name_textfield.setValue(arg1)

            add_user.last_name_textfield.waitForVisible()
            add_user.last_name_textfield.setValue(arg2)

            add_user.display_name_textfield.waitForVisible()
            add_user.display_name_textfield.setValue(arg1 + " " + arg2)

            add_user.email_textfield.waitForVisible()
            add_user.email_textfield.setValue(arg3)

            add_user.password_textfield.waitForVisible()
            add_user.password_textfield.setValue(arg4);

      });
}
```

**Comment by dimirey** [comment]
i may have found some more information regarding the issue. In the latest test run the only 'undefined' steps followed this pattern:

the page object element was defined using the .elements function:

```
      username_field: { get: function () { return browser.elements("#userName"); } },
```

function which uses the element:

```
    this.When(/^I enter (".*"|a random string) in the (.+) on the (.+) page$/, function(text, accessor, page){
        var element = accessor.replace(/"/g, '').toLowerCase().replace(/ /g, '_');

        if (text == 'a random string') {
          random_text = text = random.generate();
        } else {
          text = text.slice(1, -1);
        }
        pages[page][element].waitForVisible();
        pages[page][element].setValue(text);
    });
```

**Comment by christian-bromann** [comment]
This issue was moved to webdriverio/wdio-cucumber-framework#32
