### ISSUE TITLE
Update to request 2.74.0

### ISSUE THREAD

**Issue by jayS-de** [webdriverio/webdriverio#1508]
## The problem

The required version of the request package uses a deprecated version of tough-cookie. As the request package has a fixed constraint in package.json it's not possible to get an up-to-date version.

## Environment

* WebdriverIO version: 4.2.3
* Node.js version: 6.2.1

## Details

```bash
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
```

See also https://github.com/request/request/blob/master/CHANGELOG.md#v2740-20160722

**Comment by christian-bromann** [comment]
Can you make a PR?
