### ISSUE TITLE
Configuration file in TypeScript

### ISSUE THREAD

**Issue by mohsen1** [webdriverio/webdriverio#1509]
Hi,

I would like to write wdio.conf file in TypeScript. Using [ts-node](https://github.com/TypeStrong/ts-node) I can invoke `wdio` executable and pass my config file to it:

```
ts-node ./node_modules/.bin/wdio wdio.conf.ts
```

It appears that my `wdio.conf.ts` is being required using ts-node correctly and then it is being required again using regular node which will throw.

This method works out of box with Karma config files but doesn't work for Webdriver.io

I did some digging and noticed that this `require` call [here](https://github.com/webdriverio/webdriverio/blob/73a5eccb3453f00b0f2e15c5b047821bf3396ad0/lib/utils/ConfigParser.js#L95) throws. Not sure why ts-node didn't catch that. (/cc @blakeembrey)

**Comment by christian-bromann** [comment]
You also need to set typescript as compiler (see http://webdriver.io/guide/getstarted/configuration.html bottom).

**Comment by mohsen1** [comment]
I'm afraid that wont' work for configuration file itself.

**Comment by mohsen1** [comment]
For reference here is a pull request that is trying to use TypeScript for wdio.config file:

https://github.com/rah-foundation/website/pull/10

**Comment by christian-bromann** [comment]
Seems like we can't support this atm .. after launching the runner process it requires the config file again and fails as it is in typescript. We need to improve that process anyway so taking it on the roadmap. PRs are welcome.

**Comment by mohsen1** [comment]
For anyone interested I found a way to write wdio.conf in TypeScript

Add a `wdio.conf.js` file that contains this:

```js
require('ts-node/register');
module.exports = require('./wdio.conf.ts');
```

and write your wdio.conf in TypeScript!  ✨

**Comment by monolithed** [comment]
@mohsen1, what is the purpose to write a config file in TypeScript? 

**package.json**
```json
{
    "dependencies": {
		"typescript": "^2.2.1",
		"ts-node": "^2.1.0"
    }
}
```

**config.js**
```js
	framework: 'mocha',

	mochaOpts: {
		compilers: ['ts-node/register']
	}
}
```

That's my solution.

**Comment by mohsen1** [comment]
> why do you want to write a config file in TypeScript?

Because I need to import things written in typescript into my config

**Comment by monolithed** [comment]
> Because I need to import things written in typescript into my config

Here is my solution for such files:

![img-2017-02-28-12-27-16](https://cloud.githubusercontent.com/assets/803674/23399449/48769ad2-fdb1-11e6-8bf0-e7d5afd7b3e7.png)

`@qa/` is a private scope. 

**.gitignore**

```sh
*.js
*.js.map
*.d.ts
!/index.d.ts
!types/*.d.ts
```

**package.json**

```json
{
    "name": "@qa/foo",
    "types": "index.d.ts",
    "scripts": {
         "prepublishOnly": "tsc"
     }
}
```

All these packages are written in TS and compiled to `.js` with `d.ts` files.

**Comment by christian-bromann** [comment]
I think we can close this issue. I would recommend to go with @mohsen1 solution. Thanks @monolithed!
