### ISSUE TITLE
.catch((err) => {}) on waitFor functions 

### ISSUE THREAD

**Issue by dsudia** [webdriverio/webdriverio#1510]
## The problem

My team would like to check to see if something shows up on a page, and then take an action if it does not. As far as we can tell right now, if waitForVisible/Exists, etc time out, there is no way to continue on without that test failing. You can .then() off the success of those functions, but not .catch() on a failure.

## Environment

* WebdriverIO version: 4.0.3
* Node.js version: 6.3.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wide testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable): wdio-cucumber-framework

## Details

An example code we've written is:
```js
getErrorMessage() {
    return global.browser.pause(200)
    .isVisible(global.dictionary.labelErrorMessage)
    .then((isVisible) => {
      if (isVisible) {
        return global.browser.getTextWhenVisible(dictionary.labelErrorMessage)
        .then((text) => {
          if (typeof text === `string`) {
            return text
          } else {
            return text[0]
          }
        })
      } else {
        return global.browser.getTextWhenVisible(global.dictionary.labelErrorMessageBox)
        .then((text) => {
          return text
        })
      }
    })
  }
```
That would be a lot nicer as :
```js
getErrorMessage() {
return global.browser.waitForExist(dictionary.labelErrorMessage, 200)
    .then(() => {
        return global.browser.getTextWhenVisible(dictionary.labelErrorMessage)
        .then((text) => {
          if (typeof text === `string`) {
            return text
          } else {
            return text[0]
          }
    })
    .catch(() => {
        return global.browser.getTextWhenVisible(global.dictionary.labelErrorMessageBox)
        .then((text) => {
          return text
        })
    })
}
```
(Please don't ask why we have a text error message and a message in a box, not our fault)

I could see how the current behavior is purposeful...if something doesn't show up that I'm expecting, the test fails. But it would be nice to determine if that's true or not.

**Comment by christian-bromann** [comment]
does

```js
getErrorMessage() {
return global.browser.waitForExist(dictionary.labelErrorMessage, 200)
    .then(() => {
        return global.browser.getTextWhenVisible(dictionary.labelErrorMessage)
        .then((text) => {
          if (typeof text === `string`) {
            return text
          } else {
            return text[0]
          }
    }, () => {
        return global.browser.getTextWhenVisible(global.dictionary.labelErrorMessageBox)
        .then((text) => {
          return text
        })
    })
}
```
work?

**Comment by christian-bromann** [comment]
Also I would recommend to use wdio testrunner where you can write sync commands. Then you can just use try catch and don't have to work with that promise chain

**Comment by dsudia** [comment]
Thanks for the suggestions!
