### ISSUE TITLE
browser.doubleClick doesn't work any more on v4.2.3

### ISSUE THREAD

**Issue by arif49** [webdriverio/webdriverio#1512]
## The problem

`browser.doubleClick` doesn't work anymore. last worked on v4.1.1

## Environment

* WebdriverIO version: 4.2.3
* Node.js version: 6.2.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):

## Code To Reproduce Issue [ Good To Have ]

browser.doubleClick('#some-element');

**Comment by christian-bromann** [comment]
We have integration tests making sure that doubleClicks are working. Without any logs or detailed description I just can reject this. Sorry!
