### ISSUE TITLE
Uploading a .zip file with chooseFile() 

### ISSUE THREAD

**Issue by alkinsen** [webdriverio/webdriverio#1513]
When I try to upload a zip called images.zip through a button with <type=file and <accept="application/zip,application/x-zip-compressed"> it gives me an error saying that the file I should upload should be a zip file. If i choose the same images.zip file manually with my hand, it accepts and starts uploading.

**Comment by christian-bromann** [comment]
How am I suppose to investigate in that issue without any information? I understand the issue but can't do anything unless I get something like a reproducible example or more details about what browser was used and how the upload button is implemented and the logic behind. In general I would advise not to test upload functionalities with Selenium. It is not super good supported.

**Comment by cagataycali** [comment]
+1
I tryed with chromedriver mac os x 64 bit. 
[Driver url]( http://chromedriver.storage.googleapis.com/index.html?path=2.9/ )

I used this code for upload github user profile image but doesn't working in angularjs apps.

WDI says upload succeed.
zip file exist, url: /Users/cagatay/Apify/zipFiles/Demo.zip
```
{ sessionId: '48615bdf-ef12-4e3b-baa8-8d34f0986211',
  status: 0,
  state: 'success',
  value: null,
  class: 'org.openqa.selenium.remote.Response',
  hCode: 1456817255 }
```
![image](https://cloud.githubusercontent.com/assets/9213230/18217385/57635c24-7111-11e6-8fd3-b6b4784e2d0f.png)
```
<form name="uploadZipFileform" class="ng-valid ng-dirty">
  <input type="hidden" name="XSRF-TOKEN" value="61333563383530306661616537633764353833663939373964343633313839636330333834353962">
    <p class="MdBtn01">
      <label class="mdBtnLabel">Upload ZIP File
        <input class="mdBtn ng-valid ng-valid-file-selected ng-dirty" type="file" ng-model="zipfile" name="file" lcm-file-selected="product.uploadZip(sticker, $file)">
      </label>
    </p>
</form>
```

I selected object with: [lcm-file-selected="product.uploadZip(sticker, $file)"]

Thx
