### ISSUE TITLE
Is there a way to execute test multiple times?

### ISSUE THREAD

**Issue by MikiDavid** [webdriverio/webdriverio#1514]
## The problem

I'm using WebdriverIO along with Mocha test runner and at the wdio.conf.js file under specs, I have a single js file (Test Case).
The Test Case contain 1 _describe_ function and and 1 _it_ function within it.

My goal is to run the test multiple times and not at same time - Meaning, run it (Along with the initiate onPrepare \ Before etc.), and the _it_ function should run, say 100 times, one after the other.

Is there any configuration available for this?

I tried to use a for loop at the test case js file - but its not working quite as I need.

## Environment

* WebdriverIO version: 4.0.9 
* Node.js version: 5.9.1
* wdio testrunner

**Comment by christian-bromann** [comment]
just wrap the it block in a for loop

**Comment by 1950195** [comment]
if you want run 1 case 100 times, you can config in wdio.conf.js:
```
specs: Array(100).fill('./test/specs/**/your.e2e.ts'),
```

**Comment by mrityunjay-ck** [comment]
> if you want run 1 case 100 times, you can config in wdio.conf.js:
> 
> ```
> specs: Array(100).fill('./test/specs/**/your.e2e.ts'),
> ```

It's running 100 times but problem is they have not lunch the new page , suppose we have login into application and done my work and if i again i want to do this we have to first logout then it will contine, is there any solution for this?
