### ISSUE TITLE
Reverse waitForExist exiting test runner without failing test

### ISSUE THREAD

**Issue by williamsm1** [webdriverio/webdriverio#1516]
## The problem

Reverse `waitForExist` commands where the element is still existing are causing the test runner to exit without failing the test.  These tests where the issue occurs don't seem to be accounted for in the test totals.  In my code example below, there is only 1 test in the spec file - the test runner will exit stating `0 passing` and no mention of failures.  The test runner will exit with the following message - `wdio exited with code 1`

## Environment

* WebdriverIO version: 4.2.3
* Node.js version: 4.2.6
* [Standalone mode or wdio testrunner]: Standalone
* Additional wdio packages used (if applicable): gulp-webdriver, wdio-jasmine-framework, wdio-dot-reporter, wdio-junit-reporter

## Link to Selenium/WebdriverIO logs

[Selenium log](https://gist.github.com/williamsm1/c44b0d0e5f778874d4a0c569ac79514e)
WDIO console output
```
0 passing (44.00s)


[10:50:48] 'wdio' errored after 45 s
[10:50:48] Error in plugin 'gulp-webdriver'
Message:
    wdio exited with code 1
```

## Code To Reproduce Issue [ Good To Have ]

```
describe ('WDIO Error', function() {
    it('WDIO Error Test', function () {
        browser.url('http://www.cnn.com');
        browser.waitForExist('.nav__logo', 5000, true);
    });
});
```

**Comment by christian-bromann** [comment]
Can't reproduce on current master:

```
0 passing (42.10s)
1 failing

1) WDIO Error Test:
element (.nav__logo) still  existing after 5000ms
running chrome
CommandError: element (.nav__logo) still  existing after 5000ms
    at Object.Future.wait (/Users/christianbromann/Sites/Webprojekte/webdriverjs/gulp-webdriver/node_modules/wdio-mocha-framework/node_modules/wdio-sync/node_modules/fibers/future.js:449:15)
    at Object.waitForExist (/Users/christianbromann/Sites/Webprojekte/webdriverjs/gulp-webdriver/node_modules/wdio-mocha-framework/node_modules/wdio-sync/build/index.js:345:27)
    at Context.<anonymous> (webdriver.spec.js:4:17)
    at /Users/christianbromann/Sites/Webprojekte/webdriverjs/gulp-webdriver/node_modules/wdio-mocha-framework/node_modules/wdio-sync/build/index.js:579:24
    - - - - -
    at elements(".nav__logo") - isExisting.js:45:17
    at isExisting(".nav__logo") - waitForExist.js:40:22



[11:40:14] 'aa' errored after 43 s
[11:40:14] Error in plugin 'gulp-webdriver'
Message:
    wdio exited with code 1

```

**Comment by richardgorman** [comment]
Same issue after installing: https://github.com/jonyet/gulp-webdriverio-boilerplate

**Comment by AKFourSeven** [comment]
I am having the same issue, the test occasionally works but most of times fails with the exit code 1 but never stating the error encountered.
