### ISSUE TITLE
Reports with  CID causes issue with saving reports on windows

### ISSUE THREAD

**Issue by dgasi** [webdriverio/webdriverio#1518]
Hi,
I noticed when using json reporter or junit if you have large number of files that it fails after 28 files:
.
.
.
Wrote json report to [reports].
Wrote json report to [reports].
Failed to write json report to [reports]. Error: Error: ENOENT: no such file or directory, open '%PATH%\WDIO.json.chrome.0|.json'

So reports CID it starts with '0a' and after going trough the alphabet it starts with special characters because it created: WDIO.json.chrome.0}.json and then tried WDIO.json.chrome.0|.json where it failed.

So is it possible to reformat the name or to use numbers instead of characters?

Thx.

**Comment by christian-bromann** [comment]
@dgasi I think we should not include the capability id in the name then. I think this should be fixed in the json reporter then.
