### ISSUE TITLE
version 4.2.3 breaks waitForVisible when not visible

### ISSUE THREAD

**Issue by DutchRican** [webdriverio/webdriverio#1519]
## The problem

Waiting for an element to be visible using waitForVisible() is currently not working anymore when trying to make it fail on purpose. Giving a selector that is not on the page with a timeout of 1000ms will run for the entire time until cucumber times out.

## Environment

* WebdriverIO version: 4.2.3
* Node.js version: 6.2.2;6.2.0  tested on both
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Standalone mode
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Details

Rolling back to WebdriverIO version 4.2.1 fixes the issue.

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]
 
This runs in a async fashion. Cucumberjs is the runner. 
```javascript
emailMeHREF: function (href) {
    return new Promise(function (resolve, reject) {
        var badSelector = 'a[href="' + href + '"]'
        browser
            .waitForVisible(badSelector, 1000)
            .catch(reject)
            .call(resolve);
    });
}```

**Comment by christian-bromann** [comment]
@DutchRican can you provide a reproducible example?

**Comment by DutchRican** [comment]
emailMeHREF is a method on a pageobject that is called from the step definitions file. 
this is caught and rejected without issues in version 4.2.1. but in 4.2.3 this does not adhere to the given timeout of 1000ms.

**Comment by DutchRican** [comment]
I tried to create a working example without Cucumber, but I am unable to reproduce the issue that way.

```var webdriverio = require('webdriverio'),
    options = {desiredCapabilities: {browserName: 'chrome'}},
    client = webdriverio.remote(options);

client
    .init()
    .url('https://duckduckgo.com/')
    .then(() => console.log('starting search for selector'))
    .waitForExist('#soFake', 1000)
    .then(() => console.log('found'))
    .end();

**Comment by DutchRican** [comment]
I tried to reproduce the issue without Cucumber, but I am unable to reproduce the issue that way.

**Comment by christian-bromann** [comment]
Sorry but without anything reproducible this is hard to fix. Feel free to reopen when you have something we can work with.
