### ISSUE TITLE
Webdriverio doesnt work with TCP/IP monitor

### ISSUE THREAD

**Issue by doomsbuster** [webdriverio/webdriverio#1521]
## The problem

I started a TCP/IP monitor on local port 10000 that proxies the request to the port 4444 (the selenium hub). When I run the test directly connecting to port 4444 my tests work, when I connect to port 10000 it does nothing, just executes my nodejs program and exits. I wrote similar program with the Java remote web driver and it can execute the tests on either of the two ports.

## Details

My program can be found here https://gist.github.com/doomsbuster/dc39e1fe571b9dc5d2373f01bcd8e4e2

## Link to Selenium/WebdriverIO logs

https://gist.github.com/doomsbuster/2ffac0d04bc2c04c0b28c04ea03778bb

**Comment by christian-bromann** [comment]
@doomsbuster can you change the test code to
```js
webdriver.remote(options).init().catch(console.log).url('http://www.google.com').getTitle().then(function(title) {
	console.log(title);
}).end();
```
to see what's going on. Also it looks like the monitor is a transparent proxy so you should run the code like
```sh
HTTP_PROXY=localhost:10000 node index.js
```

**Comment by doomsbuster** [comment]
I am having the same trouble, none of the above methods really worked.
