### ISSUE TITLE
Converting circular structure to JSON

### ISSUE THREAD

**Issue by talarari** [webdriverio/webdriverio#1525]
getting this error :
```
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at process.target._send (internal/child_process.js:609:23)
    at process.target.send (internal/child_process.js:521:19)
    at C:\Development\soluto-home-app\reactNativeSrc\node_modules\webdriverio\bu
ild\lib\runner.js:341:25
    at C:\Development\soluto-home-app\reactNativeSrc\node_modules\wdio-sync\buil
d\index.js:251:34
```

when calling a custom async command that calls an api

**Comment by christian-bromann** [comment]
I don't think this is an error by WebdriverIO. You are trying to convert a json with a circular structure to string which of course doesn't work.

**Comment by khirakawa** [comment]
The error can be reproduced with the following custom async command:

```
browser.addCommand('test', function async () {
  return {
    browser: browser
  };
});
```

The reason one might do this is to have a page object with a local reference to `browser` that is returned by a custom async command:

```
function PageObject (browser) {
  this.browser = browser;
}

browser.addCommand('test', function async () {
  return browser.url('https://some-url')
    .then(() => {
      return new PageObject(browser);
    });
});
```

One way to fix this is to remove the locale reference to browser and simply call the global one instead.  However, my question is, why is the return value of the async command being stringified?

**Comment by christian-bromann** [comment]
> why is the return value of the async command being stringified?

Probably because the result gets logged somewhere, either by a testrunner reporter or by the internal logger. I don't think it makes sense to keep the browser variable as a local reference, since it is a global variable.
