### ISSUE TITLE
Collect list of WebdriverIO boilerplate projects

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#1528]
## The problem

Many new devs have trouble getting started with Node.js or/and WebdriverIO. It can be helpful to have some boilerplate repositories that help people to get started quicker.

If you have such a boilerplate project please post it here!

## Requirements

- existing readme with step by step description how to run it
- description what are the advantages of this boilerplate project (what was the intention to structure it this way)

**Comment by jonyet** [comment]
https://github.com/jonyet/gulp-webdriverio-boilerplate

designed to be quick to get you started without getting terribly complex, as well as to share examples of how one can leverage external node modules to work in conjunction with wdio specs.

**Comment by christian-bromann** [comment]
https://github.com/cognitom/webdriverio-examples

**Comment by christian-bromann** [comment]
https://github.com/michaelguild13/Selenium-WebdriverIO-Mocha-Chai-Sinon-Boilerplate

**Comment by jonyet** [comment]
https://github.com/dcypherthis/wdio-boilerplate-cucumber

**Comment by christian-bromann** [comment]
Added boilerplate projects to the getstarted section. If anyone wants to contribute his/her boilerplate project, I would be happy to receive a PR with a modification for [this](https://github.com/webdriverio/webdriverio/blob/master/docs/guide/getstarted/boilerplate.md) page. Thanks!
