### ISSUE TITLE
synchronous command handling example

### ISSUE THREAD

**Issue by hlb-schmidt** [webdriverio/webdriverio#1529]
on the frontpage at http://webdriver.io/ is stated: **synchronous command handling**

but when i run this:

```
var webdriverio = require('webdriverio');
var driver = webdriverio.remote({whatever});
var foo = false;

driver.init();
driver.url("whatever");
if (foo) {
    driver.click("whatevershouldfail");
} else {
    driver.element("whatevershouldfail");
}
driver.end();
console.log("done");
```

i can see `done` printed on the console even before selenium server started the browser...
(not to mention that it doesnt load the url, nor close the session...)

guess i'm doing it wrong, where can we find an example for *synchronous command handling*?

FWIW, i'm trying to port our dynamic (as in created from json file) selenium action creator/runner from python, where above example is no problem.

**Comment by christian-bromann** [comment]
Please make sure you've read the docs: http://webdriver.io/guide/getstarted/modes.html 😉

**Comment by hlb-schmidt** [comment]
hmm, is that suggesting that:

- we can't use webdriverio (as selenium webdriver api) with "synchronous command handling"
- and only the included testrunner can run webdriverio with "synchronous command handling"

is there a (simple) example how the included testrunner does this "synchronous command handling"?

**Comment by christian-bromann** [comment]
Yes, sync commands are only supported using wdio test runner.

> is there a (simple) example how the included testrunner does this "synchronous command handling"?

There is an example on how to use the test runner: https://github.com/webdriverio/webdriverio/tree/master/examples/pageobject
