### ISSUE TITLE
Chrome version 52.0.2743.116 (64-bit) with gulp-webdriver produce error on visual studio online

### ISSUE THREAD

**Issue by daljitsahota** [webdriverio/webdriverio#1530]
## The problem

We are using webdriver@4.2.3 version with gulp-webdriver@2.0.2 with selenium-standalone@5.1.0 to run functional ui tests. On server chrome browser updated to version@52.0.2743.116 (64-bit), and we think this has broken now all our tests with following error - 
**Error: unknown error: unable to discover open pages
Driver info: chromedriver=2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc1b),platform=Windows NT 6.3.9600 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.56 seconds**

This problem is only happening on visual studio online not on the developer machines.

We have same problem with karma and we solve using this solution -
https://github.com/karma-runner/karma-chrome-launcher/issues/73#issuecomment-236597429

As running using npm script solve karma problem, so we made following changes in the wdio.conf.js file
```js
**services: ['selenium-standalone']**,
    specs: [
        './tests/test_functionalUI/**/*Spec.js'
    ],
    exclude: [
    ],
    maxInstances: 1,
    capabilities: [
        {
            browserName: 'chrome',
            **chromeOptions: {
                args: ['--no-sandbox']
            }**  
        }       
    ],
```
and than use npm script to run test as following -
 **"postDeploymentTestFunctional": "node_modules/.bin/wdio wdio.conf.js",**   

After this change our tests are broken randomly are we missing anything?

Thanks,

## Environment

* WebdriverIO version: 2.0.2
* Node.js version: 5.0.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
You are using a *highly* outdated version of the ChromeDriver. Your first port of call should be to update it [here][1].

I would highly suspect the problem is your Chrome on your server has updated, and ChromeDriver v2.2 doesn't [support][2] any recent versions of Chrome.


  [1]: http://chromedriver.storage.googleapis.com/index.html
  [2]: http://chromedriver.storage.googleapis.com/2.8/notes.txt

Copied from http://stackoverflow.com/posts/21004947/edit. Sometimes a quick google search is easier 😉

**Comment by daljitsahota** [comment]
Thanks for reply, I will look into it.

**Comment by charliedavison** [comment]
@christian-bromann I have been looking into a similar issue, and looking at the link to the link you provided @daljitsahota to update the chromedriver, it appears that his V2.22 is actually not _that_ out of date at all and should support his version of Chrome perfectly fine unless I am misreading!

[See V2.22 Release notes here] ](http://chromedriver.storage.googleapis.com/2.22/notes.txt)

The version numbers in that folder are pretty confusing, why is V2.23 the latest release but then they're all in a folder with versions up to V2.9 (which was actually released way back in 2014)?!

**Comment by christian-bromann** [comment]
@charliedavison 2.__23__.0 > 2.__9__.0 . My comment was copied from SO so don't know which version @daljitsahota is using
