### ISSUE TITLE
Documentation says you can use an array of methods for hooks.

### ISSUE THREAD

**Issue by kradical** [webdriverio/webdriverio#1531]
## The problem

When passing an array of methods they do not get executed.

## Environment

* WebdriverIO version: 4.2.3 
* Node.js version: 6.x
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): standalone
* if wdio testrunner, running synchronous or asynchronous tests: n/a
* Additional wdio packages used (if applicable): n/a

## Details

Just a conflict of the docs and functionality (unless I am somehow using it wrong / mistaken?)

## Link to Selenium/WebdriverIO logs

No error, just when trying to use something declared in a before hook it thinks it doesn't exist (and after insert log statements the functions are never called)

## Code To Reproduce Issue

module.export.config = {
  ...
  before: [function() { console.log('1'); }, function() { console.log('2'); }]
  ...
}

I'm going to make a pull request because it looks like a quick fix (it seems everything is set up to handle arrays its just a small mistake in configParser) 

Thanks for all your dedicated work on this project :) it makes my and many others lives much easier!

**Comment by christian-bromann** [comment]
PR was merged

**Comment by kradical** [comment]
Thanks!
