### ISSUE TITLE
wdio testrunner runs all specs even when --spec option is specified

### ISSUE THREAD

**Issue by bradlord** [webdriverio/webdriverio#1533]
## The problem

I tried running a single Jasmine spec file using the --spec option, as described in the [documentation](http://webdriver.io/guide/testrunner/organizesuite.html):

```
wdio wdio.conf.js --spec ./test/specs/e2e/login.js
```

I was expecting that only the single spec file would be run, but all of my spec files were run.

## Environment

* WebdriverIO version: 4.2.4
* Node.js version: 4.2.2
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): none

## Details

The value of the --spec argument isn't getting passed into the `Launcher` constructor. That seems to be because the [ALLOWED_ARG value in cli.js](https://github.com/webdriverio/webdriverio/blob/master/lib/cli.js#L43-L45) doesn't include the value `'spec'`. Adding `'spec'` to `ALLOWED_ARG` locally caused the --spec argument to work as intended.

**Comment by christian-bromann** [comment]
wow .. totally missed that. Thanks for reporting. Just about to release it.
