### ISSUE TITLE
'runner:screenshot' event not received on failure screenshot even if screenshotOnReject is enabled

### ISSUE THREAD

**Issue by lisss** [webdriverio/webdriverio#1535]
## The problem
I'm creating my custom reporter and want to link failure screenshots to all the rest report data. I found that such ability has been implemented, and I could subscribe to `'runner:screenshot'` event to get required data.
I set **screenshotOnReject** flag to `true` in wdio.conf.js
But it doesn't work for me - I don't receive `'runner:screenshot'`.

## Environment
* WebdriverIO version: v4.2.5
* Node.js version: v4.4.6
* wdio testrunner
* synchronous tests
* Additional wdio packages used:
wdio-mocha-framework, wdio-screenshot, wdio-selenium-standalone-service, wdio-sync, wdio-testingbot-service, wdio-visual-regression-service

## Details
I did some digging and found that runner doesn't receive internal `'screenshot'` event either (so that it doesn't fire the `'runner:screenshot'` one). Adding `'screenshot'` to the list of internal events (`INTERNAL_EVENTS`) helped. Is this a bug in webdriverio or I misuse the feature?

**Comment by lisss** [comment]
@christian-bromann, can anyone confirm the issue or help?

**Comment by christian-bromann** [comment]
Yeah it looks like the event is not propagated to the outside. You can subscribe to the error event though to get the screenshot. Feel free to create a PR and add `runner:screenshot` to the list of internal events.
