### ISSUE TITLE
unhandled inspector error

### ISSUE THREAD

**Issue by ThibaultFriedrich** [webdriverio/webdriverio#1538]
## The problem

While using webdriverio, I am experiencing a runtime error while using `setValue` on an element. 

```
it('edit fields', function () {
    preferences.profile.firstName = 'John';
    preferences.profile.lastName = 'Smith';
    preferences.profile.email = 'john.smith@co-exp.com';
    preferences.profile.job = 'Business consultant';
    preferences.profile.mobilePhone = '06.42.12.12.21';
    preferences.profile.officePhone = '04.12.12.12.12';
    preferences.profile.address = '1 infinite loop';
    preferences.profile.website = 'www.co-exp.com';

    return app.client
    //.pause(500)
    .setValue('input[placeholder="First Name"]', preferences.profile.firstName)
    .setValue('input[placeholder="Last Name"]', preferences.profile.lastName)
    .setValue('input[placeholder="Email"]', preferences.profile.email)
    //.pause(500)
    .setValue('input[placeholder="Job Title"]', preferences.profile.job)
    .setValue('input[placeholder="Mobile Phone Number"]', preferences.profile.mobilePhone)
    .setValue('input[placeholder="Office Phone Number"]', preferences.profile.officePhone)
    //.pause(500)
    .setValue('input[placeholder="Address"]', preferences.profile.address)
    .setValue('input[placeholder="Website"]', preferences.profile.website)
    /*.pause(500)*/;
});
```

The message is so weird that I cannot debug my selenium test myself.

```
RuntimeError: unknown error: unhandled inspector error: {"code":-32000,"message":"Exception while making a call."}
      at elements("input[placeholder="Office Phone Number"]") - setValue.js:29:17
      at elementIdValue("0.967076821019873-8", "06.42.12.12.21") - setValue.js:46:80
```

Do you have any idea of the source of this bug ? I only need to understand the error message.

> Notice that I use Spectron with mocha and webdriverio. But the bug seems to come from webdriverio

The selenium seems to work a little better when I remove several `setValue` or if I add pause but it is still too much random for a stable test.

## Environment

* WebdriverIO version: 4.2.5
* Node.js version: 5.0.0

**Comment by christian-bromann** [comment]
> But the bug seems to come from webdriverio

Not quite. It is from Chromedriver. Not sure why it is throwing this but it looks like a network/request issue between node script and chromedriver I would say. Might be a good idea to file this issue in the Spectron project since they are responsible for starting chromedriver.

**Comment by ThibaultFriedrich** [comment]
Ok I will see with Spectron project.
