### ISSUE TITLE
Counting the number of items in a list

### ISSUE THREAD

**Issue by nareshbhatia** [webdriverio/webdriverio#1540]
I have the following DOM structure:

```
<div data-qa-id="criteriaDisplay">
    <ul>
        <li>...</li>
        <li>...</li>
        <li>...</li>
    </ul>
</div>
```

I would like to write a function in my page object that returns the number of `<li>`s in the list:

    criteriaDisplay: { get: function () { return browser.element('[data-qa-id="criteriaDisplay"]'); } },

    getNumberOfItems: { value: function() {
        ...
    } },

What is the best way to do this? I am a newbie and do not know the selenium API well.

Thanks in advance for your time.

P.S. Why do page object functions wrap a `value` property? I could not find an explanation for this in the docs.

**Comment by christian-bromann** [comment]
do `this.criteriaDisplay.elements('li').value.length`.

I would recommend to use the Gitter chat for such questions. This issue tracker should be for actual bugs.

**Comment by nareshbhatia** [comment]
Thanks for the quick response, Christian. I will use Gitter going forward.
