### ISSUE TITLE
Launching all available tests

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1543]
## The problem

```js
{
   suites: {
       foo: ['**/*.js'],
       .....
   }
}
```

```
wdio config.js
```

## What happens

Nothing.

## Expected

Launching all available tests

## Environment

* WebdriverIO version: 4.2.5
* Node.js version: 6.2.0
* wdio testrunner
* synchronous tests:

**Comment by christian-bromann** [comment]
You need specify the suite to run: `wdio config.js --suite foo`

**Comment by monolithed** [comment]
Nope, I want to run all tests.

**Comment by monolithed** [comment]
`foo`, `bar` and so on these suites are merged automatically by developers and I don't want to know anything about it. The suites are used to run tests by groups in our release cycle. And tests for production stage are launching independently from any group.

**Comment by christian-bromann** [comment]
So you want to run all tests from all suites? Note that if you define your test path in the suite object you need to specify the suite you want to run. Otherwise define the general test path with the [`specs`]{https://github.com/webdriverio/webdriverio/blob/master/examples/wdio.conf.js#L35-L37} property.

**Comment by monolithed** [comment]
I see what you mean, but I don't want to use `specs`. What is problem to run all tests?

**Comment by christian-bromann** [comment]
> What is problem to run all tests?

You, not using specs? specs is the property where you should define all your test specs e.g. `test/specs/**/*`. If all your specs are in there, they run.

**Comment by monolithed** [comment]
```js
{
   specs: ['**/*.js'],
   suites: {
       foo: ['foo/**/*.js']
       .....
   }
}
```

The problem is that`wdio suite=foo` will start all tests

**Comment by monolithed** [comment]
Oh, sorry, it seems has been fixed allready
