### ISSUE TITLE
After hook is called after every suite

### ISSUE THREAD

**Issue by przemuh** [webdriverio/webdriverio#1546]
## The problem

After hook is called after every suite instead of after all tests

## Environment

* WebdriverIO version:4.2.5
* Node.js version: 6.3.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): -

## Details

After hook is called after every suite instead of after all tests

## Link to Selenium/WebdriverIO logs

N/A

## Code To Reproduce Issue [ Good To Have ]

create "after" hook and run more that 1 spec file

here is a video with bug: https://psuchodolski.egnyte.com/dl/GXpvpmkezM

**Comment by christian-bromann** [comment]
That might be a bit misleading but it is the right behavior. Use onComplete if you want to run something after all tests are done.

**Comment by przemuh** [comment]
Ok but what if I want to perform async operation e.g. http call to rest API to delete folder ? Is there any option to do that?

**Comment by christian-bromann** [comment]
just return a promise

**Comment by przemuh** [comment]
Ok, So comment may be misleading:

"It is not possible to defer the end of the process using a promise."

But thanks! Works like a charm :)
