### ISSUE TITLE
Unable to get test name into BrowserStack session name 

### ISSUE THREAD

**Issue by leonstafford** [webdriverio/webdriverio#1552]
## The problem

By setting `name` option to some string in `capabilities`, that will show in BrowserStack. Protractor users seem to be able to get test names showing by omitting option or setting an empty string - neither of these work for me with WDIO, it instead shows the `sessionId` as the session name.

## Environment

* WebdriverIO version: 4.1.1
* Node.js version: 5.9.0
* wdio testrunner, asynchronous
* Additional wdio packages used:
 - wdio-mocha-framework 0.3.5
 - wdio-selenium-standalone-service 0.0.5
 - wdio-spec-reporter 0.0.3

**Comment by leonstafford** [comment]
May be same as [this issue over on nightwatch](https://github.com/nightwatchjs/nightwatch/issues/1060)?

**Comment by leonstafford** [comment]
^ using following code in hook performs assignment with correct test name, but still doesn't help it show up in BrowserStack at all

```javascript
beforeTest: function(test) {
  browser.options.desiredCapabilities.name = test.title;
}
```

**Comment by christian-bromann** [comment]
There is currently now way to change the capabilities right before we initialise the session and I don't know if it makes sense to introduce a beforeBefore hook just for the sake to do so. On Sauce Labs you can tweak the session name after the test but it seems that BrowserStack doesn't support that. Unless there is more value in having that additional hook I don't see a reason to add it as it would confuse more people as it would help them.

**Comment by tripleratamacue** [comment]
@christian-bromann, I am using Sauce Labs, so how can I get/inject the tests name (either cucumber Feature name or steps), or even the file name, any advise would be greatly appreciated.

**Comment by christian-bromann** [comment]
@tripleratamacue if you use the wdio testrunner you can use the [wdio-sauce-service](https://github.com/webdriverio/wdio-sauce-service)

**Comment by steindani** [comment]
You can set the name of the session using the following hook abuse:

```js
beforeSession: function (config, capabilities, specs) {
  capabilities.name = specs && specs[0].split('/').pop() || undefined;
},
```

modifying the capabilities on-the-fly, when the tests are run in parallel:
```js
maxInstances: 10,
```

It works for me.

**Comment by Tudmotu** [comment]
Building on what @leonstafford and @steindani wrote, I found that using the `beforeTest` hook allows me to include the full name of the test, since I am reloading the session before each test:
```javascript
beforeTest: test => {
    browser.desiredCapabilities.name = test.fullTitle;
    browser.reload();
}
```
I am reloading the session before each test because I need empty state for each `it()`. This doesn't seem to work without reloading the session.

**Comment by raketenolli** [comment]
For those coming here looking for a way to get the test name into Saucelabs, I've had success – thanks to @Tudmotu – with adding

```javascript
beforeTest: function(test) {
    browser.desiredCapabilities.name = test.fullTitle;
}
```

to `wdio.conf.js` which will use the title of the first `display()` block of each test/spec as the test name in Saucelabs.

Do not use `browser.reload()`, it will fail the test with

    Error in onReload hook: "Error: Don't end the session manually. This will be done automatically.`

**Comment by christian-bromann** [comment]
> Do not use `browser.reload()`, it will fail the test with

You should be able to run this command in your test but not in the hooks

**Comment by savsav** [comment]
The best solution is to use the [BrowserStack REST API](https://www.browserstack.com/automate/rest-api) - the `Update the name of the test` section.

If you have `browser.reload()` it is good to have it executed from the second test onwards - the first test starts a new session anyway so no need to additionally reload it. You can set a global variable - `global.firstTestFinished = true;`. Then based on it, you call that API to update the first test name, or you do `browser.desiredCapabilities.name = test.title;` if it't the second test:
```javascript
const request = require('request-promise-native');

if (!global.firstTestFinished) {
  // can't use browser.desiredCapabilities.name as the session has already been started
  // see https://github.com/webdriverio/webdriverio/issues/1552#issuecomment-241357584
  let bsAPIRequestOptions = {
    url: `https://api.browserstack.com/automate/sessions/${browser.sessionId}.json`,
    method: 'PUT',
    headers: {
      'Content-Type': 'application/json'
    },
    body: `{"name":"${test.title}"}`,
    auth: {
      user: siteConfig.browserstackUser,
      pass: siteConfig.browserstackPass
    }
  };
  request(bsAPIRequestOptions); // no need for await - the rest of the test doesn't depend on that
} else {
  // browser.reload() will start a new selenium session and the name will be updated
  browser.desiredCapabilities.name = test.title;
}
```

I also think `browser.reload()` in the `beforeTest()` hook is necessary in a serious web automation project where pages set various cookies, use service worker, localStorage, sessionStorage, etc. You can't possibly clean everything in the beginning - there are http-only cookies (which can't be deleted on some browsers), there are cookies with different domain, path, etc.

**Comment by empshyamjeet** [comment]
Nunit use below :
                capabilities.SetCapability("name", TestContext.CurrentContext.Test.MethodName);

before creating browserstack browser
it is working for me
