### ISSUE TITLE
wdio-mochawesome-reporter

### ISSUE THREAD

**Issue by Mignon-han** [webdriverio/webdriverio#1553]
Hello,
I hope to be able to use wdio-mochawesome-reporter.
Thanks!

**Comment by just-boris** [comment]
Have you considered [wdio-allure-reporter](https://github.com/webdriverio/wdio-allure-reporter)?
This is the recommended way to receive html-based report for your tests.

**Comment by christian-bromann** [comment]
Yes, please use the wdio-allure-reporter. It is identically to the mochaawesome concept.

**Comment by Mignon-han** [comment]
Thanks,I will try it.

**Comment by rahulmr** [comment]
@Mignon-han were you able to integrate mochawesome reporter? If yes, please do share your work, thanks.

**Comment by christian-bromann** [comment]
@rahulmr what's the issue with the wdio-allure-reporter? I doubt that mochaawesome is compatible with wdio.

**Comment by rahulmr** [comment]
@christian-bromann allure needs post processing to create html reports and I need to install more npm packages. I want to keep it simple. The new mochawesome reporter is very impressive. It has screenshot and gives a single html file as end result, which is very handy. We are using GOCD pipeline and html is good way to share info which is an artifact for the pipeline.

**Comment by rahulmr** [comment]
This is main reason I am confused whether to use wdio runner or mocha runner, I liked the wdio runner with wdio.conf.js but reporter is not to good.

**Comment by christian-bromann** [comment]
> allure needs post processing to create html reports

No problem, just do it in your onComplete hook

> The new mochawesome reporter is very impressive.

I know. If you can write an integration I would be happy to support it.

> It has screenshot

So has the Allure reporter

Did you try the Allure reporter? I don't see any disadvantages against the mochaawesome reporter.

**Comment by rahulmr** [comment]
Yes, tried an implemented. The new version is kool :)

**Comment by krundrufanatics** [comment]
Hi @rahulmr, are you able integrate mochawesome with webdriver.io ? if so, can you share your code here

**Comment by christian-bromann** [comment]
@krundrufanatics I recommend to use the allure reporter

**Comment by snoblenet** [comment]
Also `allure-reporter` is an AJAX single-page apps so to share it with others you either need to run a webserver or instruct them to start one. In the past, sharing mochawesome reports as plain HTML files with all attachments embedded has worked a treat.

**Comment by christian-bromann** [comment]
> In the past, sharing mochawesome reports as plain HTML files with all attachments embedded has worked a treat.

Just to be clear about this: I am not against having a Mochaawesome reporter. If someone can spend time building it I would be happy to add it to our reporter list.

**Comment by snoblenet** [comment]
I had a look at the custom reporter page on the Webdriver.io and I'm thinking the best option may be for me to write a basic HTML reporter specifically for my test harness

**Comment by fijijavis** [comment]
@christian-bromann I’ve been working on building a wdio-mochawesome-reporter. Been using it internally for about 6 weeks or so now.  I think in the next week or two I could make it available.  Want to create an issue and assign it to me?

**Comment by christian-bromann** [comment]
> I think in the next week or two I could make it available.

That's awesome!

> Want to create an issue and assign it to me?

Just propose a PR if you are ready

**Comment by rahulmr** [comment]
Hi @fijijavis , any updates on this? Do you have a repo on github?

**Comment by fijijavis** [comment]
@rahulmr Nothing is publicly available yet.  Probably won’t be able to get to it until the weekend.  I’ll post an update here on Monday (or sooner if I am able to work on it)

**Comment by fijijavis** [comment]
Quick update... I've done some pretty significant code cleanup to make things more presentable for public consumption.  I am in the process of writing tests and updating the README.  Will most likely be next Monday 11/27 before this is ready.

**Comment by rahulmr** [comment]
@fijijavis still waiting for your update :)

**Comment by christian-bromann** [comment]
@rahulmr the package was recently published: https://www.npmjs.com/package/wdio-mochawesome-reporter

**Comment by snoblenet** [comment]
added it to my harness -- works as advertised -- thanks for your efforts @fijijavis

**Comment by fijijavis** [comment]
@snoblenet you’re welcome and thanks for the feedback
