### ISSUE TITLE
Mobile Testing | Take Photo using Native Camera Gallery

### ISSUE THREAD

**Issue by khareprashant** [webdriverio/webdriverio#1554]
Hi,

I have been trying to automate the process of taking photo through our mobile devices.

I want to use the photo from the gallery of the device and for that i use .chooseFile method of the repository but it does not seem to work well.

I tried the same method for normal document uploads in desktop browsers and it worked just fine, but specifically for choosing photo from gallery it does not seem to working fine. Please help!

**Comment by christian-bromann** [comment]
> .chooseFile method of the repository but it does not seem to work well.

Not all commands are supported for mobile. This is not an problem of WebdriverIO but of your automation driver. We are trying to improve our documentation in this regards but have problems ourselfs to figure out which commands are supported in which automation driver.
