### ISSUE TITLE
Issue with the payment flow - entering Credit card No. and Expiration date 

### ISSUE THREAD

**Issue by amiya-pattnaik** [webdriverio/webdriverio#1556]
## The problem

Hi all,
I've a scenario where I need to automate the payment page.

I need to enter the credit card details, but the thing is when I use browser.setValue method to type the text, it doesn't take the full card number though it only takes the first 4 chars.

The card field is designed in such a way that it takes 4 numbers and then provide auto space and then next 4 numbers and so on...

Same thing happens for Expiration date field where it auto '/' between month and year. example - 12/20
How would I handle this particular thing using webdriverIO?

## Environment

* WebdriverIO version: Latest
* Node.js version: 6.4.0
* [ wdio testrunner]
* if wdio testrunner, running synchronous tests:

Thanks,
Amiya

**Comment by christian-bromann** [comment]
Just use setValue for each input field. It is hard to give recommendation without knowing any context of the app you are testing. Might be a good idea to join our [Gitter](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) channel and ask there.
