### ISSUE TITLE
Uncaught RuntimeError: Underlying driver does not implement advanced user interactions yet.

### ISSUE THREAD

**Issue by kdaimiel** [webdriverio/webdriverio#1559]
I need to test my mobile app in different browsers and I am trying to use touchFlick protocol in a non mobile device then I get this error.

## Environment

* WebdriverIO version: 4.2.7
* ChromeDriver version: 2.22.397932

**Comment by christian-bromann** [comment]
What error?

**Comment by kdaimiel** [comment]
Here is the error:

     Uncaught RuntimeError: Underlying driver does not implement advanced user interactions yet.
      at elementIdDisplayed("0") - isVisible.js:71:55

**Comment by christian-bromann** [comment]
touchFlick doesn't work on desktop, mobile only!

**Comment by kdaimiel** [comment]
That's not truth, I have a laptop with touchable screen and as I see it ChromeDriver supports touchFlick, so why do you throw the following exception with an action like swipe which implement touchFlick protocol?

 Uncaught CommandError: swipe command is not supported on non mobile platforms

**Comment by christian-bromann** [comment]
> ChromeDriver supports touchFlick

Where is this documented?

> why do you throw the following exception

Because I never thought that a driver would support it for desktop.

**Comment by kdaimiel** [comment]
Hi, I could see it on https://sites.google.com/a/chromium.org/chromedriver/downloads. It seems to be an experimental feature from ChromeDriver 2.16

ChromeDriver 2.16

Changes:
Experimental support for Touch Actions
Fixed a bug when navigating back or forwards, where ChromeDriver sometimes would not wait for the page to finish loading
Fixed a bug when navigating or reloading a page, where ChromeDriver would sometimes send commands to the wrong <iframe>

**Comment by christian-bromann** [comment]
> Experimental support for Touch Actions

I am not sure that this is meant for desktop. You can run Chrome on Android or iOS too where this function might be useful. Try to comment out the if statement in the touchflick command and see if chromedriver supports it.

**Comment by kdaimiel** [comment]
Yes, I have commented the if statement and doesn't work with selenium-standanlone server, it seems that they don't support this kind of interactions yet, but It works in SauceLabs and with a selenium parched by me. Thanks
