### ISSUE TITLE
How to trigger an onkeyup event?

### ISSUE THREAD

**Issue by Zw3rv3r** [webdriverio/webdriverio#1562]
I'm trying to test the appearance and disappearance of an error message when entering an invalid value in an input field. This behavior is triggered with an onkeyup JavaScript event. I'm able to change the value of the input field with setValue() or keys() but this won't trigger the onkeyup event. After searching through the API, documentation, blogs and examples I haven't found a solution.

I'm using WebdriverIO 4.2.5 with selenium-standalone 5.5.0 in standalone mode

What is the correct way to do this with webdriver.io? I'm familiar with Selenium where one can use actions.

**Comment by christian-bromann** [comment]
Try the [buttonUp](http://webdriver.io/api/protocol/buttonUp.html) command but I made the experience that Selenium sometimes doesn't propagate the events. So if this command doesn't work just use [execute](http://webdriver.io/api/protocol/execute.html) and trigger the event manually.
