### ISSUE TITLE
WDIO test runner unable to find cucumber step definitions

### ISSUE THREAD

**Issue by gsccheng** [webdriverio/webdriverio#1565]
When executing the WDIO test runner with 
```
$ ./node_modules/.bin/wdio wdio.conf.js
```
a new Chrome window (as I have configured) pops up briefly and I get:
```
ERROR: ENOENT: no such file or directory, lstat '/Users/me/path/to/app/features/step_definitions/**'
```
Meanwhile, I have:
1) Installed the Cucumber framework: `wdio-cucumber-framework`
2) Set `wdio.conf.js` file to `framework: 'cucumber'`
3) Am using the default wdio generated cucumberOpts, except for `require` where I used `step_definitions` instead of `step-definitions`: 
```
    cucumberOpts: {
        require: ['./features/step_definitions/**/*.js'],        // <string[]> (file/dir) require files before executing features
        backtrace: false,   // <boolean> show full backtrace for errors
        compiler: [],       // <string[]> ("extension:module") require files with the given EXTENSION after requiring MODULE (repeatable)
        dryRun: false,      // <boolean> invoke formatters without executing steps
        failFast: false,    // <boolean> abort the run on first failure
        format: ['pretty'], // <string[]> (type[:path]) specify the output format, optionally supply PATH to redirect formatter output (repeatable)
        colors: true,       // <boolean> disable colors in formatter output
        snippets: true,     // <boolean> hide step definition snippets for pending steps
        source: true,       // <boolean> hide source uris
        profile: [],        // <string[]> (name) specify the profile to use
        strict: false,      // <boolean> fail if there are any undefined or pending steps
        tags: [],           // <string[]> (expression) only execute the features or scenarios with tags matching the expression
        timeout: 20000,     // <number> timeout for step definitions
        ignoreUndefinedDefinitions: false, // <boolean> Enable this config to treat undefined definitions as warnings.
    },
```

If I were to run `$ cucumber.js` from the command line it would read my file: `features/step_definitions/auth/login.js`

Yet, the WDIO test runner doesn't appear to be able to do this, and from the error message, it appears the search path is truncated since I don't see a `/*.js`

What can I do here to get cucumber to read my step definitions using the WDIO test runner? Thanks.

**Comment by gsccheng** [comment]
Thanks, it works now. I just realized the comments also say it expects a directory: `files/dir`

**Comment by cheungkayip** [comment]
@gsccheng I have been trying to get it to work with Wdio cucumber but it still is giving me an error that it cannot find the stepdefinitions
do I also need to put in ./files/dir/features/step-definitions?

but if i look at the change of christian it only says ./features/step-definitions...i'm a bit puzzled...

**Comment by christian-bromann** [comment]
@cheungkayip with support of cucumber v2 you now need to apply the actual file instead of the folder.

**Comment by igniteram** [comment]
@christian-bromann If globs are not supported now then do users have to specify individual files? that is not at all feasible if there are multiple files.

**Comment by christian-bromann** [comment]
@igniteram feel free to propose a PR to fix this 😉

**Comment by igniteram** [comment]
@christian-bromann Yes, I am planning to fix this, I had looked at the source code of `wdio-cucumber2-framework`, there are couple of other issues as well, the compiler doesn't recognize typescript ts-node.
I found few issues with the Interactive CLI as well, Would send separate PR's ;)  BTW I built the Interactive CLI for protractor - [cliptor](https://github.com/igniteram/Cliptor.js)  by getting inspired by webdriverio's cli, it's still in nascent stage just wanted to give some attribution :)

**Comment by christian-bromann** [comment]
`wdio-cucumber2-framework` is not our official framework package. Please have a look at https://github.com/webdriverio/wdio-cucumber-framework

**Comment by igniteram** [comment]
ahh, I see. ok I think this issue still exists in `wdio-cucumber-framework`. I will definitely look at it!
