### ISSUE TITLE
Docs / Guide on how to work with Appium

### ISSUE THREAD

**Issue by gaurav21r** [webdriverio/webdriverio#1569]
Thanks for this excellent framework. Unfortunately I couldn't find much help / guidance on how to use WebDriverIO to automate testing of a Hybrid App using Appium. I checked the test folder and also the documentation. Although there is a `Mobile` column in the API, I wanted to know what needs to be written in the config file (and any special instructions on starting appium).

Apologising in advance if I have missed some doc somewhere :(

**Comment by christian-bromann** [comment]
@gaurav21r what kind of instruction you are looking for?

Basically you just need to tweak the capabilities and define a mobile device, see the [platform configurator](https://wiki.saucelabs.com/display/DOCS/Platform+Configurator?src=sidebar) on Sauce Labs wiki page. In the API (e.g. [here](http://webdriver.io/api/mobile/getOrientation.html)) you find commands that are for mobile usage + if they are supported by android and/or ios.

**Comment by gaurav21r** [comment]
@christian-bromann Thank you for such a quick response! I see you have linked to the SauceLabs Configuration here as well http://webdriver.io/guide/getstarted/configuration.html

As a beginner I find it a bit difficult to configure WebDriverIO with the `desiredCapabilities` from the SauceLabs link. Do you think the doc can be improved with a more **full featured** example configuration. And then one with Appium?

I'd love to submit a PR if you could just jot down a quick full configuration file or point me to one in the test folder or something.

**Comment by christian-bromann** [comment]
@gaurav21r check out the [example](https://github.com/webdriverio/webdriverio/blob/master/examples/standalone/webdriverio.with.appium.chrome.js) section.

**Comment by gaurav21r** [comment]
@christian-bromann Thank you so much! I see its for the standalone case but I'm sure the same config will also work for the WDIO TestRunner?

**Comment by christian-bromann** [comment]
yes

**Comment by rahulmr** [comment]
@gaurav21r  I am also struggling to get a working example for android mobile native app testing using webdriverio. Is it possible for you guide me on this?
I wanted to use the following packages

1. wdio
2. wdio-spec-reporter (console spec reporter)
3. wdio-appium-service (for starting and stopping the appium server automatically)
4. gulp-webdriver (for running tests using gulp)

I am referring the saucelabs document [here](https://github.com/saucelabs-sample-test-frameworks/JS-Mocha-WebdriverIO-Appium-Android)

I do not want to automate browser but native app.

Thanks in advance.

**Comment by christian-bromann** [comment]
Here is an example which can be easily transferred to wdio: https://github.com/webdriverio/webdriverio/blob/master/examples/appium/appium-draws-its-logo.js. Feel free to join the Gitter channel if you have any problems getting started.

**Comment by rahulmr** [comment]
Yes, I was trying to use that scenario but it seems a bit complex for me, since it is for IOS and I was not able to run it properly for Android, also the UI elements are bit used in a complex way. Helpers for touchAction :( and all that.

Sorry, but I was not able to follow it correctly. Secondly, I wanted to use the [`wdio-appium-service` ](https://www.npmjs.com/package/wdio-appium-service)package to ease out on starting and stopping of appium server.

I am getting the below error - I am on windows 7 x64. Appium 1.5.3
```
> wdio wdio.conf.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn D:\projects\automation\node_modules\.bin\appium ENOENT
    at exports._errnoException (util.js:1012:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
    at Module.runMain (module.js:577:11)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
 npm ERR! Test failed.  See above for more details.
```

I am not able to debug this problem. Totally lost :(

**Comment by christian-bromann** [comment]
You have the Appium NPM package installed?

**Comment by rahulmr** [comment]
I tried installing appium@1.5.3 locally as well as globally. I think it supports local one inside node_modules. Currently, I am trying to install npm@4.0.5 and appium 1.6.3 locally and will try again. But my problem is I am not able to get what the issue is based on the above error log.

**Comment by rahulmr** [comment]
I see you have something written [here](https://github.com/webdriverio/webdriverio/blob/master/examples/standalone/webdriverio.with.appium.nativeapp.js)
I will try to follow it.
But @christian-bromann  it will be good if you can write something as per my requirement with some services for local execution of tests wherein appium server starts and stops on completion of tests.  
People generally like these kind of integration where they can concentrate more on writing test cases.  
   As I mentioned if it is possible please do provide some example for my requirement.   BTW I am loving webdriverio . With extensive support for mobile automation it will be great.

**Comment by christian-bromann** [comment]
> With extensive support for mobile automation it will be great.

WebdriverIO has extensive support for mobile automation however setting up the test environment is not really within the scope of WebdriverIO. These services do provide an easy set up for Selenium and Appium but do not necessarily fit into each environment. They can be configured tho.

> it will be good if you can write something as per my requirement with some services for local execution of tests wherein appium server starts and stops on completion of tests.

There are plenty tutorials on the internet on how to setup Appium. We try to improve our docs all the time and might put together a better tutorial for that but there is already a lot on the web.

**Comment by rahulmr** [comment]
Thanks @christian-bromann , it seems there is [bug](https://github.com/rhysd/wdio-appium-service/issues/2) in wdio-appium-service . And yes your standalone examples are very useful, I will checkout those and try to implement them.

**Comment by gaurav21r** [comment]
@rahulmr Sorry noticed this late. Will look into it.
@christian-bromann Any examples / or any direction you can point me to for hybrid apps? Web Apps but  packaged with Cordova to get native binaries?

**Comment by christian-bromann** [comment]
> Any examples / or any direction you can point me to for hybrid apps?

To do what?

**Comment by rahulmr** [comment]
@gaurav21r it is very easy to automate using uiautomator selectors. Read the [docs](http://webdriver.io/guide/usage/selectors.html) on selectors `Mobile Selectors` => `Android UiAutomator`.
If you create util to create selectors it becomes easier.
```
var selector = 'new UiSelector().text("Cancel")).className("android.widget.Button")';
browser.click('android=' + selector);
```
I created a small utils like below
```
var uiSelector = 'android=new UiSelector()';
var androidId = 'android=new UiSelector().resourceId("com.android:id/';
var myPackageId = 'android=new UiSelector().resourceId("com.my.package:id/';
var Selector = Object.create({}. {
  text: {
    value: function (textContent) {
      return uiSelector + '.text("' + textContent + '")';
    },
  androidId: {
    value: function (id) {
      return androidId + id + '")';
    }
  },
  
  myPackageId: {
    value: function(myId) {
      return myPackageId + myId + '")';
    }
  }
}
module.exports = Selector;

```
It is just returning string (not sophisticated), but can be used like below
```
var selector = require('../utils/selector');
browser.click(selector.text('OK'));
```

**Comment by And93** [comment]
Hello. Help me please. I don't understand, why i cann't use UiSelector. Because I have this mistake:

```
>browser.$('android=new UiSelector().text("Account")).className("android.widget.EditText")')
[00:10:09]  COMMAND     POST     "/wd/hub/session/6db0c8aa-5713-4fcb-81f8-9b6635865af5/element"
[00:10:09]  DATA                {"using":"-android uiautomator","value":"new UiSelector().text(\"Account\")).className(\"
android.widget.EditText\")"}
[00:10:09]  COMMAND     GET      "/wd/hub/session/6db0c8aa-5713-4fcb-81f8-9b6635865af5/screenshot"
[00:10:09]  DATA                {}
[00:10:10]  RESULT              "iVBORw0KGgoAAAANSUhEUgAABDgAAAeACAYAAAArYecKAACAAElEQVR4AezBDVSchYHv/18eJyUv8ICJL5GZ2Go9
ZCD21NowTNzd7l1mg32JB/gHexsrEdw91zbR6J5uCpHYc/6VUKzdsw2snnV7akDcYhXC5CR3bSc7w7bdJjBErVaHyawaTZ6xIRpjHhKbCAn/5ex ... (8416
6 more bytes)
[00:10:10]      Failed to take screenshot on reject:     {"errno":-4058,"code":"ENOENT","syscall":"open","path":"C:\\Proj
ect\\end-to-end-autotest\\errorShots\\ERROR_nexus5api24v2.android.7_0.c:\\project\\tools\\mobileapp\\app-release_apk_2018
-05-08T21-10-09.799Z.png"}
C:\Project\end-to-end-autotest\node_modules\wdio-sync\build\index.js:357
            throw e;
            ^

Error: The requested resource could not be found, or a request was received using an HTTP method that is not supported by
 the mapped resource.
    at $("android=new UiSelector().text("Account")).className("android.widget.EditText")") -     at C:\Project\end-to-end
-autotest\node_modules\wdio-sync\build\at element("android=new UiSelector().text("Account")).className("android.widget.Ed
itText")") - C:\Project\end-to-end-autotest\node_modules\webdriverio\build\lib\commands\$.js:42:17
```

But if I use:
```
browser.$("~input-login_account")
```

then everything is fine.

**Stack: webdriverio+mocha+appium**

What I doing is wrong?

**Comment by sandikumar3** [comment]
@christian-bromann , Although WebdriverIO supports mobile automation with the help of Appium . But there is lack in webdriverIO documentation as no specific help on setting up the test for android app. Also, if i take my case, i am about to evaluate webdriverIO library for native app automation. From so long, i am struggling with basic setup. No help in terms of any video/tutorial step by step available on internet neither on webdriverIO website. One Guy, Kevin Lamping posted helping videos, but they seems complex in itself. I have one suggestion , its upto you- any free library become popular when it is used by more audience. Audience can use it when they found it good after giving it a try. PLZ post some helping content in respect of mobile automation by WebDriverIO.
Regards
Sandeep
Email - sandikumar3@gmail.com

**Comment by wswebcreation** [comment]
@sandikumar3 

Maybe this helps https://github.com/webdriverio/appium-boilerplate
