### ISSUE TITLE
Error in PhantomJS are not caught in webdriver.io

### ISSUE THREAD

**Issue by maximecharron** [webdriverio/webdriverio#1570]
## The problem
Error that happens in PhantomJS (such as PhantomJS giving up because it cannot find an element) are not caught by the error listener. 

## Environment

* WebdriverIO version: 0.3.3
* Node.js version: 6.4.0
* Mode : Standalone with PhantomJS running on port 4444

## Code To Reproduce Issue 
```
var options = {
    capabilities: [{
        browserName: 'phantomjs'
    }],
    waitforTimeout: 1000
};


var browser = webdriverio.remote(options)
browser.on('error', function (error) {
    console.log("An error occured");
});
browser.init()
    .url('https://google.com/')
    .click('#something') //#something does not exist. 
    .end()
```

PhantomJS relevant logs: 
```
[ERROR - 2016-08-31T15:35:05.932Z] WebElementLocator - _handleLocateCommand - Element(s) NOT Found: GAVE UP. Search Stop Time: 1472657705920

  phantomjs://platform/console++.js:263 in error
```

**Comment by christian-bromann** [comment]
This is because each command represents a promise and won't throw in a normal script like that. If you set up a wdio test runner script it will. It is like if you reject a promise it won't throw either.

**Comment by maximecharron** [comment]
I don't want it to be in a test runner script since I'm using it for automation and not testing. Is there a way to catch the error in a normal script?

Thanks!

**Comment by christian-bromann** [comment]
handle the promises properly and call catch at the end like
```js
var options = {
    desiredCapabilities: {
        browserName: 'phantomjs'
    },
    waitforTimeout: 1000
}

var browser = require('./build').remote(options)

var result = browser.init()
    .url('https://google.com/')
    .click('#something')
    .end()

result.catch(function (e) {
    process.nextTick(function () {
        throw e
    })
})
```
