### ISSUE TITLE
Typescript setup not working; followed the documentation

### ISSUE THREAD

**Issue by dheerajbhaskar** [webdriverio/webdriverio#1573]
## The problem
I followed the setup instructions at http://webdriver.io/guide/getstarted/configuration.html under the heading **Setup TypeScript** but I'm getting this error (Detailed below) while running. I can't seem to find the `common.js` which has been mentioned there.

I'm using Webstorm and sublime text 3 also, if that matters. I'm just using them for text editing, nothing fancy. I'm running `wdio` command from the commandline itself

## Environment

* WebdriverIO version:
"webdriverio": "^4.2.7"

 Here's my entire `package.json`

    {
      "name": "wdio",
      "version": "1.0.0",
      "description": "",
      "main": "index.js",
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "author": "",
      "license": "ISC",
      "devDependencies": {
        "ts-node": "^1.3.0",
        "wdio-mocha-framework": "^0.4.0",
        "wdio-selenium-standalone-service": "0.0.5",
        "wdio-spec-reporter": "0.0.3",
        "webdriverio": "^4.2.7"
      }
    }
    

* Node.js version:

>node --version
v6.4.0

* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
wdio

* if wdio testrunner, running synchronous or asynchronous tests:
sync
* Additional wdio packages used (if applicable):

Here's my entire wdio.conf.js

https://gist.github.com/dheerajbhaskar/089b214acfda5560d2e64bc958ec09d5

## Details

Describe in more detail the problem you have been experiencing, if necessary.

This is the error stacktrace

    ERROR: Module C:\my-home\AutomationProjects\WebdriverioProjects\wdio\test\helpers\common.js can't get loaded. Are you sure you have installed it?
    Note: if you've installed WebdriverIO globally you need to install these external modules globally too!
    chrome
        at MochaAdapter.load (C:\my-home\AutomationProjects\WebdriverioProjects\wdio\node_modules\wdio-mocha-framework\build\adapter.js:453:23)
        at C:\my-home\AutomationProjects\WebdriverioProjects\wdio\node_modules\wdio-mocha-framework\build\adapter.js:396:28
        at Array.forEach (native)
        at MochaAdapter.requireExternalModules (C:\my-home\AutomationProjects\WebdriverioProjects\wdio\node_modules\wdio-mocha-framework\build\adapter.js:388:21)
        at MochaAdapter.options (C:\my-home\AutomationProjects\WebdriverioProjects\wdio\node_modules\wdio-mocha-framework\build\adapter.js:228:18)
        at Suite.<anonymous> (C:\my-home\AutomationProjects\WebdriverioProjects\wdio\node_modules\wdio-mocha-framework\build\adapter.js:257:35)
        at emitThree (events.js:121:20)
        at Suite.emit (events.js:194:7)
        at C:\my-home\AutomationProjects\WebdriverioProjects\wdio\node_modules\wdio-mocha-framework\node_modules\mocha\lib\mocha.js:219:11
        at Array.forEach (native)
    
## Link to Selenium/WebdriverIO logs

Sorry, no logs were produced. Here's my folder tree, just to be sure:
https://gist.github.com/dheerajbhaskar/049703a68f5972a13af5855dee31a954

## Code To Reproduce Issue [ Good To Have ]
I've removed the .git and node_modules due to GH size constraints
[wdio.zip](https://github.com/webdriverio/webdriverio/files/450574/wdio.zip)

**Comment by christian-bromann** [comment]
@dheerajbhaskar seems that your problem is:
`Module C:\my-home\AutomationProjects\WebdriverioProjects\wdio\test\helpers\common.js can't get loaded`

**Comment by susnigdha1** [comment]
Even I am facing the same issue, how to resolve it? Could you please tell the steps?
