### ISSUE TITLE
[Question] Not possible to write the same sentence for Given and Then

### ISSUE THREAD

**Issue by racodond** [webdriverio/webdriverio#1574]
Hi,

I'd like to be able to define a `Given` and a `Then` with the same sentence. But it seems that it is not possible.

Here's one of my use cases:

Gherkin:
```
Feature: Login / Logout

  Background:
    Given I am on the home page
    And I am a visitor

  Scenario: Successful login with valid credentials
    When I log in as john.doe@email.com/password
    Then I am logged in as user John/Doe

 Scenario: Unsuccessful login with invalid password
    When I log in as john.doe@email.com/wrongpassword
    Then I am a visitor
    And I am told that I have provided wrong credentials

  Scenario: Unsuccessful login with invalid username
    When I log in as blabla@email.com/password
    Then I am a visitor
    And I am told that I have provided wrong credentials
```

Steps:
```
this.Given(/^I am a visitor$/, function () {
        return browser.forceLogout().seeVisitor();
  });
```
and
```
this.Then(/^I am a visitor$/, function () {
    return browser.seeVisitor();
  });
```

The implementation is different:

- The Given sets the context (forceLogout = logout if I am logged in, do nothing if I am not logged in) and validates it (seeVisitor = check that I am not logged in).
- The Then only validates the context (seeVisitor)

But from a functional point of view, using the same sentence makes sense to me. And it seems more obvious from a business analyst or tester point of view.

For now, I ended up writing:
```
Given I am a visitor

Then Validates that I am a visitor
```

But I don't like it...

What is wrong with my way of thinking?
Is it only a technical limitation? Or is it a wrong approach of writing Gherkin test cases?

Any feedback or suggestion is more than welcome.

Thanks!

**Comment by christian-bromann** [comment]
This seems to be a technical limitation by cucumber.js.
