### ISSUE TITLE
Undefined returned when using browser.sessionStorage() and browser.localStorage()

### ISSUE THREAD

**Issue by si-mikey** [webdriverio/webdriverio#1575]
I am trying to store a json object into the session storage. Followed the documentation
api doc
```javascript
client.sessionStorage('POST', {key: someKey, value: someValue});
```
mine ( persona is a json object as the value )
```javascript
browser.sessionStorage('POST', {key: 'persona', value: persona});
```
when I run this, I get an undefined (the browser firefox, halts for a few seconds then returns undefined)

I also tried quoting the {'key': 'persona', 'value': persona} but that didn't work either. Any Ideas. everything else works find ( pageObject stuff and interacting with page elements )

**Comment by christian-bromann** [comment]
We've implemented these commands according to the spec. However I haven't seen anyone using session storage successfully with Selenium. Either the browser or the driver doesn't support it. However you can try to access it via the `execute` command (see https://loadfocus.com/blog/tech/2015/06/how-to-clear-local-storage-using-selenium-webdriver/).
