### ISSUE TITLE
Commands not synced anymore

### ISSUE THREAD

**Issue by jcaarls** [webdriverio/webdriverio#1578]
## The problem

Recently I started migrated my webdriver.io 2.x scripts to webdriver.io 4. In my 2.x I used async to synchronize the execution of the code. What the code basically does:

- It has one Mocha test case that parses json input file(s) with the webdriver commands to execute. This test case processes the files one by one with async.foreach
- It loops through each json file with async.foreach and calls a function for each command. For example the function to do a click:

	```
// process the click
	this.processClick = function (target,parameter1,parameter2,functionCallback){
		try {
			console.log(browser.options);
			browser.pause(10000);
			console.log('before wait');
			browser.waitForExist(target,1000);
			console.log('after wait,before click');
			browser.click(target);
			this.lastUrl = browser.getUrl();
			console.log('after click, before pause 10s');
			browser.pause(10000);
			console.log('after pause, click done');					
			functionCallback(null,true);								
		} catch (err) {
			console.log('Click failed' + util.inspect(err, false, null));
			functionCallback(err,false);			
		}
	};
```

The problem: the commands are somehow not synced anymore and the callback is called after the console logging is done. Also the try/catch is not working, waiting for an element that doesn't will fail the entire script. If I execute the code above in a separate script it works just fine. Any idea why this is happening? Somehow the combination of async and multiple callbacks are making webdriver.io out of sync? Thanks a lot for your help!

## Environment

* WebdriverIO version: 4.2.11
* Node.js version: 4.4.7
* wdio testrunner synchronous 
* Additional wdio packages used (if applicable): wdio-visual-regression-service wdio-screenshot

## Link to Selenium/WebdriverIO logs

https://gist.github.com/jcaarls/2ece7cf938b4e8c24a759979b43bd8d9

## Code To Reproduce Issue [ Good To Have ]

The main test case with an async foreach to browse through a list of json files. myScriptRunner has the methods to get json and process it.

	it('Regression test',function(){
		var _this = this;
		return new Promise(function(reject, resolve){
			async.forEachSeries(relatedTestCases,function(relatedTestCase,testCaseDone){
				//name of the test case 
				var testcase = testSuiteExecutionName + '/' + baselineName + '/' + relatedTestCase.id;
				global.testcase = testcase;		
				logger.info('Running testcase: ' + testcase);
				var url = parametersBaseUrl + "/" + relatedTestCase.type + "/" + relatedTestCase.id; 
				myScriptRunner.getJSON(url,function(err,testCase){
					if (err){
						logger.info('Ooo no json, we just move on to the next test case and dont do the callback with the error.');
						myScriptRunner.failureCount += 1;
						testCaseDone();
						reject();
					} else {
						try {
							var script = JSON.parse(testCase.data.attributes.script);            	
							logger.info("Start executing the script");
							myScriptRunner.executeScript(relatedTestCase.id,script,function(err,successful){
								if (successful === false){
									myScriptRunner.failureCount += 1;
								} else {
									myScriptRunner.successCount += 1;
								}	    						  
								// we are done with this one, proceed to the next    							
								testCaseDone();
							});
						}  catch (err) {
							//TODO process the error message
							// Ooo no json, we just move on to the next test case and don't do the callback with the error.
							myScriptRunner.failureCount += 1;    						
							testCaseDone(err);
						}
					}
				});
			},function(err){
				if (err){
					logger.info('Something went wrong ' + err.message);
					reject();
				}
				resolve();
			});//end of async each
		});//end of outer it
	}); //end of outer promise

Execute script:

```
//script is the entire list of commands
async.forEachSeries(script,function(step,commandDone){
			var command = step.command;
				switch(command) {
					case "click":
						_this.processClick(target,parameter1,parameter2,function(err,res){
//some more code to handle the output
							commandDone();						  
						});
						break;  
//more cases for other commands       
```

Example of the click function:

```
	// process the click
	this.processClick = function (target,parameter1,parameter2,functionCallback){
		try {
			console.log(browser.options);
			browser.pause(10000);
			console.log('before wait');
			browser.waitForExist(target,1000);
			console.log('after wait,before click');
			browser.click(target);
			this.lastUrl = browser.getUrl();
			console.log('after click, before pause 10s');
			browser.pause(10000);
			console.log('after pause, click done');					
			functionCallback(null,true);								
		} catch (err) {
			console.log('Click failed' + util.inspect(err, false, null));
			functionCallback(err,false);			
		}
	};
```

**Comment by christian-bromann** [comment]
Instead of using `async.forEachSeries` just run in in a for or while loop. I see that you are doing some async stuff in between, note that commands are sync as long as they get executed in the same eventloop as the it function. So if you call any other async function with a callback you need to wrap it into a wdioSync again, like:
´myScriptRunner.getJSON(url,wdioSync(function(err,testCase){ ... }))`

**Comment by jcaarls** [comment]
Thanks a lot for helping me out!
