### ISSUE TITLE
Allow multiple specs when using the --spec option

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [webdriverio/webdriverio#1579]
## Feature request

With the --suite option, you can use the command like so `wdio wdio.conf.js --suite login,otherFeature`, specifying multiple comma-separated suites. 

It would be nice if this were also possible when using the --spec option, like `wdio wdio.conf.js --spec ./test/specs/e2e/login.js,./test/specs/e2e/feature1.js`

Thanks!

**Comment by christian-bromann** [comment]
Enhanced config parser. Will be released with next version.

**Comment by Blackbaud-PatrickOFriel** [comment]
You da man Christian

**Comment by dalimian** [comment]
could u please update the docs with this info http://webdriver.io/guide/testrunner/organizesuite.html#Run-Single-Test-Suites and http://webdriver.io/guide/testrunner/organizesuite.html#Run-Multiple-Specific-Test-Specs

**Comment by christian-bromann** [comment]
> could u please update the docs with this info

@dalimian why not just proposing a PR by yourself 😉 ?

**Comment by dalimian** [comment]
sure thing, am i correct to assume i can remove this section http://webdriver.io/guide/testrunner/organizesuite.html#Run-Multiple-Specific-Test-Specs since this new way achieves the same in more elegant way and would work cross OS

**Comment by christian-bromann** [comment]
@dalimian no, you can enhance this section: http://webdriver.io/guide/testrunner/organizesuite.html#Run-Single-Test-Suites
