### ISSUE TITLE
Selector throws error if an html element's id starts with a number.

### ISSUE THREAD

**Issue by SamantaChinmoy** [webdriverio/webdriverio#1580]
## The problem

I want to click on a html element whose id start with number. But following error is thrown.
org.openqa.selenium.InvalidSelectorException: The given selector #2y-but-ton is either invalid or does not result in a WebElement. The following error occurred:
InvalidSelectorError: An invalid or illegal selector was specified
 

## Environment

* WebdriverIO version: latest version
* Node.js version: 0.10.25

## Code To Reproduce Issue .
**Example.html**
```
<button id="2my-Button" onclick="document.getElementById('someText').innerHTML='I was clicked'">Click me</button>
<div id="someText">I was not clicked</div>
```

**click.js**
```
client
    .click('#2my-Button')
    .getText('#someText').then(function(value) {
        assert(value === 'I was clicked'); // true
    });
```

**Comment by dmfranko** [comment]
It's not valid for an html id to start with a number.

**Comment by SamantaChinmoy** [comment]
It was working in previous version of webdriverio. But it is not working in latest version of webdriverio. So i think it is a webriverio related issue.

**Comment by hamishtaplin** [comment]
@dmfranko: it is valid for a html id to start with a number in html5, however it's not valid according to CSS spec. The reason this fails is due to `document.querySelector` being used under the hood.

A workaround for now is to use an attribute selector, eg. `[id="2lksfsljkd"]`

**Comment by christian-bromann** [comment]
@hamishtaplin is right, there is nothing WebdriverIO can do about this. Closing.
