### ISSUE TITLE
Upgrade to Selenium 3.0

### ISSUE THREAD

**Issue by tuckerconnelly** [webdriverio/webdriverio#1581]
Our automated test started failing in Firefox 48+, however they work in Firefox 47. I think Browserstack is aware of the issue 'cause they put this header on their Automate page:
 
<img width="565" alt="screen shot 2016-09-08 at 1 54 18 pm" src="https://cloud.githubusercontent.com/assets/4349082/18360375/c4f1e288-75cb-11e6-857a-25131ec5282e.png">

Need to upgrade to 3.0 for Firefox 48+ to work 🙂

**Comment by christian-bromann** [comment]
WebdriverIO runs your tests but is not responsible for the Selenium infrastructure. All commands will work exactly the same as in 2.x so feel free to update.

**Comment by GeoffreyBooth** [comment]
The http://webdriver.io/ homepage describes the project as “Selenium 2.0 bindings for NodeJS”. Is Selenium 3.0 supported? If so, why not mention that fact?

**Comment by christian-bromann** [comment]
@GeoffreyBooth good catch, I will have to update this. Selenium 3 is the same as Selenium 2.0 besides that fact that there are new commands. Starting with Selenium 4 a bunch of commands from Selenium 2 will be depcrecated
