### ISSUE TITLE
Mobile screenshots include device frame

### ISSUE THREAD

**Issue by maggiesavovska** [webdriverio/webdriverio#1584]
## The problem
I'm not sure if this is a webdriverio problem or a selenium problem, but the screenshots I'm taking via "driver.saveScreenshot" on iphone and android include the device frame. I'm taking multiple screenshots and piecing them together since safari and android emulator don't seem to take full page screenshots. The device frame makes it hard to effectively piece my screenshots together. 

## Environment
* WebdriverIO version: 3.7.3
* Appium version: 1.5.3
* Node.js version: 5.8.0

capabilities: 
        {browserName: "Safari", deviceName: "iPhone 5", version:"9.0", "appiumVersion": "1.5.3"}
       { "appiumVersion": "1.5.3", "deviceName": "Samsung Galaxy S3 Emulator", "deviceOrientation":  "portrait", "browserName": "Browser", "platformVersion": "4.4", "platformName": "Android"}

**Comment by christian-bromann** [comment]
This is an issue of the mobile driver. You can try `wdio-screenshot` not sure if that crops the device frame. I don't think so. WebdriverIO only saves the screenshot it gets from Selenium to the file system.
