### ISSUE TITLE
hasElementResult does not check for elements command well.

### ISSUE THREAD

**Issue by CTaylor1118** [webdriverio/webdriverio#1585]
## The problem

In hasElementResultHelper.js the way it is checking for the result from the elements command is implemented badly. This is causing bug when a command that returns an empty array is called before another command that is inserting null into the arguments list. If the command already specifies a selector webdriverio should not be inserting anything into the arguments. The implementation for the hasElementResult should also check that each item of the array is actually an Element rather than only filtering out the ones that are.

```Javascript
    /**
     * check for elements call
     */
    if (result && Array.isArray(result.value) && result.value.filter((r) => !r.ELEMENT).length === 0) {
        return 2
    }
```

## Environment

* WebdriverIO version: 4.2.8
* Node.js version: 0.12.7
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Standalone

**Comment by christian-bromann** [comment]
@CTaylor1118 can you give an example?

**Comment by CTaylor1118** [comment]
@christian-bromann when you run an element command you do not get an array back, just the singular element. The way this is implemented now, it does not check for that. It also specifically filters the elements result to return those without and ELEMENT property rather than those that do. The way I discovered this was having a command that returned [null] and that was being added as the elementId of the following command.

**Comment by christian-bromann** [comment]
@CTaylor1118 I meant a code example where is error can be reproduced

**Comment by CTaylor1118** [comment]
I don't have a simple one of hand. The error involved a complicated custom command.

**Comment by christian-bromann** [comment]
I am not sure how to help then. The helper returns 1 if the result was an element result , 2 if elements and 0 the result was not an element call
