### ISSUE TITLE
client.execute callback?

### ISSUE THREAD

**Issue by tolmasky** [webdriverio/webdriverio#1586]
I'd like to receive a callback from client.execute AFTER an asynchronous event, so I can't simply return. So for example:

```javascript
client.execute(function(callback)
{
      element = document.getElementById("x");
      element.addEventListener("transitionend", function()
      {
            callback();
      });
      element.style.transition = "left .45s";
      element.style.left = "4px";
}, callback);
```

Of course this doesn't work, but maybe there's like a `webdriver.sendMessage()` or something I could use?
## Environment

* WebdriverIO version: 4.2.11
* Node.js version: 4
* standalone

**Comment by christian-bromann** [comment]
http://webdriver.io/api/protocol/executeAsync.html will do the trick 😉  .. for those kind of questions you might want to join our gitter chat
