### ISSUE TITLE
Execute in frame (vs .frame.then.execute)

### ISSUE THREAD

**Issue by tolmasky** [webdriverio/webdriverio#1587]
## The problem

I'm running into a problem with wanting to execute two scripts at the same time in different frames. Essentially, something along the lines of:

```javascript

bluebird.all(
[
     client.frame(frame1).then(function()
     {
          return client.execute(SomeScript)
     }),
     client.frame(frame2).then(function()
     {
          return client.execute(SomeScript2);
     })
]);
```
So clearly there is a "race condition" here of the fact that one of the two frames will become focused and then both scripts may execute in the same frame, just by the very nature of the way async works. Of course, this can be restructured to something more like this:

```javascript
client.frame(frame1).then(function()
{
      var p1 = client.execute(SomeScript)
      var p2 = client.frame(frame2).then(function() { client.execute(SomeScript2) }     
         
      return bluebird.all([p1, p2]);
})
```

However, in our particular setup, these frame-change/script-executes are deep in other functions (think `doSomething1` and `doSomething2`), so its kind of a coupling mess to have to unroll everything for the purpose of getting the .frame() calls sequenced together, not to mention that in our case we are actually doing more than just 2 of these, which increases the complexity. Essentially, when working with multiple frames where you want to execute scripts, it becomes very hard to compose functions.

Is there any way to add support for something akin to: `client.execute(frame1, SomeScript)`?

That way, it would be as easy as:

```javascript
bluebird.all([client.execute(frame1, SomeScript1), client.execute(frame2, SomeScript2)]
```

Currently, writing such a function myself in "user land" would seem to require a sort of "locking" (not real locking) mechanism: 
```javascript
bluebird.all([
    client.waitForAndGetFrameLock().frame(frame1).executeAndReleaseFrameLockImmediately(SomeScript1),
    client.waitForAndGetFrameLock().frame(frame2).executeAndReleaseFrameLockImmediately(SomeScript2)
])
```

## Environment

* WebdriverIO version:  4.2.11
* Node.js version: 4
* standalone

**Comment by monolithed** [comment]
> So clearly there is a "race condition" here of the fact that one of the two frames will become focused and then both scripts may execute in the same frame, just by the very nature of the way async works. 

Nope, you should call [`frameParent`](http://webdriver.io/api/protocol/frameParent.html) after each `frame` to switch the parent context.

**Comment by tolmasky** [comment]
Sure, sorry it should have read like this:

```javascript
bluebird.all(
[
     client.frame(frame1).then(function()
     {
          return client.execute(SomeScript).then(function()
{
    client.parentFrame();
})
     }),
     client.frame(frame2).then(function()
     {
          return client.execute(SomeScript2).then(function()
{
    client.parentFrame();
})
     })
]);

```

But the issue remains that it may execute as such since I'm running them in "parallel":

1. client.frame(frame1)
2. client.frame(frame2) // error

**Comment by christian-bromann** [comment]
@tolmasky you can't run that in parallel. Selenium will execute it one command at a time for a session since you can't access two iframes at the same time as a normal user right?

**Comment by christian-bromann** [comment]
Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
