### ISSUE TITLE
How to go to browser url and pass cookies in request header?

### ISSUE THREAD

**Issue by eGavr** [webdriverio/webdriverio#1593]
## The problem

I have the following code:

```js
const webdriverio = require('webdriverio');

const options = {
    host: 'localhost',
    port: 4444,
    path: '/wd/hub',
    desiredCapabilities: {
        browserName: 'chrome',
        version: '48'
    }
};

const browser = webdriverio.remote(options);

browser
    .init()
    .url('https://google.com')
    .end();
```

I need to add a cookie via request header. How can I do this? The variant when I add cookie after method `url` via method `cookie` does not siute me.

## Environment

* WebdriverIO version: latest
* Node.js version: 4.x:

Thanks.

**Comment by christian-bromann** [comment]
The only way to set cookies is via `setCookie`. You need to elaborate on why it doesn't suite you but this is the only way. For those kind of question, it is better to reach out to our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).

**Comment by 21stio** [comment]
I got exactly the same question. Any progress on that? Is it an webdriverio issue or a selenium issue?

**Comment by christian-bromann** [comment]
There is no progress because it is not an issue. Please reach out to the Gitter channel.

**Comment by gurugray** [comment]
Gitter channel didn't loaded…

So there is no any way to load page with cookies without loading this page set cookies and load page again?

I need to do one request to test heavy page depends on cookie, so it seems quite strange to load it several times :\

**Comment by gurugray** [comment]
`curl -v --cookie "USER_TOKEN=Yes" http://127.0.0.1:5000/` :\

**Comment by 21stio** [comment]
@gurugray I didn't find any better way than what you described in your first post..

**Comment by worc** [comment]
the docs (and comments) leave a lot to be desired here. i'm seeing cookies not persisting during tests and the RTFG attitude doesn't really help when this is the first place to stop and look for similar problems/solutions
