### ISSUE TITLE
Looping radio button and selecting one of them

### ISSUE THREAD

**Issue by aqiqul** [webdriverio/webdriverio#1599]
## The problem

I am unable to select a radio button

## Environment

* WebdriverIO version:  4.2.15
* Node.js version: v6.4.0
* [Standalone mode or wdio testrunner]: Standalone
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Details

I have html code as 
```html
<div class="form-input radio-buttons">
	<label>Gender</label>
	<span class="radio-button"><input type="radio" name="gender" value="m" > Male  </span> 
	<span class="radio-button"><input type="radio" name="gender" value="f" > Female </span>
	<span class="required-icon required-blue"></span>	
	<span class="validation-msg"></span>							
</div>
```

I am trying to loopinto the radio button and set selection on "Male"

Using this code
```
.elements('radio-button').then(function(res){
console.log("aaa + :"+res);
res.forEach(function(elem){
console.log("elems :"+elem);
//client.click(elem.ELEMENT);
})
})
```

I am using webdriverio, and do not get any thing after (res.forEach)

**Comment by christian-bromann** [comment]
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

When you execute a command you execute an asynchronous method which returns a promise. Make sure you handle these promises properly. You can't call them like synchronous methods.

**Comment by aqiqul** [comment]
Could you please give some examples ?
