### ISSUE TITLE
Can't interact with an alert/authentification layer

### ISSUE THREAD

**Issue by mpvlv** [webdriverio/webdriverio#1600]
Hi, i'm having issues with handling an authentification poppup on a secured page. 
I'm not able to interact with the overlay at all and i get an "Failed: no alert open
" exception, probably because the Overlay os not on focus. 
1. How can i get the frame in focus?
2. How can i input user credentials (https://user:pass@abc.com does not work for me, because i need it in Chrome)?

* WebdriverIO version: 4.2.3
* Node.js version: 6.3.1
* Additional: Jasmine 

Thanks!

**Comment by christian-bromann** [comment]
> https://user:pass@abc.com does not work for me

This would be the only way. You can't interact with a auth popup in Selenium. Make sure you grant access to your test instance.

Also those type of questions aren't issues. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). This is not necessary an issue.
