### ISSUE TITLE
unable to run multiremote() for different browser on different VM on saucelab in parallel

### ISSUE THREAD

**Issue by aqiqul** [webdriverio/webdriverio#1602]
## The problem
error when running diff caps to sauce lab using multiremote.

## Environment

* WebdriverIO version: 4.2.15
* Node.js version: 6.4.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Not used
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable): 

## Details
```js
var webdriverio = require('webdriverio');
var client = webdriverio.multiremote({
	myChromeBrowser:{
		desiredCapabilities: {
			user: process.env.SAUCE_USERNAME,
			key: process.env.SAUCE_ACCESS_KEY,
			host: 'ondemand.saucelabs.com',
			port: 80,
			browserName: 'chrome'		
		}
	},
	myFireFoxBrowser: {
		desiredCapabilities:{
			user: process.env.SAUCE_USERNAME,
			key: process.env.SAUCE_ACCESS_KEY,
			host: 'ondemand.saucelabs.com',
			port: 80,
			browserName: 'firefox'
		}
}}).init()
    .url('http://google.com')
	.windowHandleMaximize()
	.end();
```
- Strange it runs on local selenium server not even trying to reach sauce 

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by monolithed** [comment]
I've got the same problem.  There are 120 nodes with chrome browser in our Grid, but used only one! `maxInstances` is ignored by Grid.

```js
{
	host: 'http://grid-host.example.com'
	suites: { ... },
	capabilities: [
		maxInstances: 120, // its' ignored
        	browserName: 'chrome'
	]
}
```

**Comment by christian-bromann** [comment]
@monolithed you can set host and port for each capabiltiy in your config, it will overwrite the default value you've set in the config root

**Comment by monolithed** [comment]
```js
capabilities: [
   {
        browserName: 'chrome'
    },
   {
        browserName: 'chrome'
    },
    // ... 120 items?
]
```

Not so pretty solution ))

))

**Comment by christian-bromann** [comment]
@monolithed don't understand the issue. If you are using an internal grid it should load balance the session within all available nodes. `maxInstances` regulates how many selenium session will be initiated  at the same time. Please be more specific what you mean it gets ignored by the grid.

**Comment by christian-bromann** [comment]
@aqiqul your host and port were not assigned properly. Here is the working example:

```js
var webdriverio = require('webdriverio');
var client = webdriverio.multiremote({
    myChromeBrowser:{
        user: process.env.SAUCE_USERNAME,
        key: process.env.SAUCE_ACCESS_KEY,
        desiredCapabilities: {
            host: 'ondemand.saucelabs.com',
            port: 80,
            browserName: 'chrome'
        }
    },
    myFireFoxBrowser: {
        user: process.env.SAUCE_USERNAME,
        key: process.env.SAUCE_ACCESS_KEY,
        desiredCapabilities:{
            host: 'ondemand.saucelabs.com',
            port: 80,
            browserName: 'firefox'
        }
}}).init()
    .url('http://google.com')
    .windowHandleMaximize()
    .end();
```

**Comment by aqiqul** [comment]
worked, thanks !
perhaps we should think of some more optimization somehow?

**Comment by christian-bromann** [comment]
> perhaps we should think of some more optimization somehow?

Why? Optimization in what sense?

**Comment by aqiqul** [comment]
the common properties if they are not required to fill in each time unless it changes
e.g
 user: process.env.SAUCE_USERNAME,
        key: process.env.SAUCE_ACCESS_KEY,
            host: 'ondemand.saucelabs.com',
            port: 80,

these may not change for each different browser, we could put them at the top and mention in any child node only if they are to change (browser stack etc.)

**Comment by christian-bromann** [comment]
I don't think there is a need for that. You can easily compute these properties with simple js.
