### ISSUE TITLE
Javascript to test html5 validation for required field

### ISSUE THREAD

**Issue by IshaSinghBauer** [webdriverio/webdriverio#1604]
## The problem
There is a field on site https://www.travelin.com.au/ which is required and I need to automate testing if any validation message is displayed in UI for this. 

## Environment

* WebdriverIO + Node.JS

## Details

I am new to Webdriver.io + JS and I am having a problem as mentioned below:

There is a field on site https://www.travelin.com.au/ which is required and I need to automate testing this. If I enter a blank text in this field and press enter, it displays "Please enter search term". But there is no way webdriver.io or javascript helping to validate if this message is getting displayed or not. I am totally stuck here. Any help would be much appreciated

_HTML for the field is:_ 
 <form method="get" id="headerSearchForm" action="/searchResults">
                            <input name="context" type="hidden" value="Sitesearch">
        
                            <div class="search-input-container">
                                <input id="site-search-input" class="search-input" name="q" placeholder="I'm looking for..." type="text" **required**>
                                <i class="show-for-large-up fa fa-search"></i>
                            </div>
                            <div class="submit-input-container">
                                <button class="button search" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        </form>

## Code To Reproduce Issue
 browser.click(div.menu-items a.sitesearch-toggle);
browser.keys('Enter');

// If I use following, it says undefined
var form=browser.element('form');
console.log(form.validity.valid);
Or
console.log(form.validity);
console.log(form.CheckValidity);

**Comment by IshaSinghBauer** [comment]
@christian-bromann : I see you have helped many users to solve their queries. Would you be able to help me too?

**Comment by christian-bromann** [comment]
These kind of native browser features aren't testable with Selenium. If you need to check the value of these placeholders use `getAttribute(element, 'placeholder)` but you can't check if this is visible or not.

**Comment by christian-bromann** [comment]
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
