### ISSUE TITLE
Not getting os_version specific junit reports

### ISSUE THREAD

**Issue by jaiminpanchal27** [webdriverio/webdriverio#1607]
## The problem

I am running my tests on Browserstack. For the sake of example consider following environments

`"bs_chrome_51_windows_10": {
    "base": "BrowserStack",
    "os_version": "10",
    "browser": "chrome",
    "browser_version": "51.0",
    "device": null,
    "os": "Windows"
  },
"bs_chrome_51_windows_8.1": {
    "base": "BrowserStack",
    "os_version": "8.1",
    "browser": "chrome",
    "browser_version": "51.0",
    "device": null,
    "os": "Windows"
  }`

Now the reports which are getting generated for reporter junit are as follows
Filename: WDIO.xunitchrome.51_0.windows.14a.xml
Filename: WDIO.xunitchrome.51_0.windows.13a.xml

How can i know the os version used here ? 
Will i get if i create custom reporter ?

## Environment

* WebdriverIO version: v4.2.16
* Node.js version: v6.2.2
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* Additional wdio packages used (if applicable): wdio-junit-reporter

**Comment by christian-bromann** [comment]
This issue was moved to webdriverio/wdio-junit-reporter#18
