### ISSUE TITLE
Can't get the sected options of a <select>

### ISSUE THREAD

**Issue by Yvem** [webdriverio/webdriverio#161]
Sorry, I tried `.element`, `.elements`, `.getSelected` with no success.

Java and C# drivers have a getFirstSelected()

Is it possible to get the selected options with webdriver.js ? If not, should it be added ?

Note : S/O question : http://stackoverflow.com/q/22153812/587407

**Comment by AndyGee** [comment]
Fiddled with this for hours until it worked - Nothing obvious about it!

`let elements = $("#selectId").elements("option").value;

    let selectedText = "";

    elements.map(function(option) {
      let selected = option.getAttribute("selected");
      if (selected) {
        selectedText = option.getText().trim();
        console.log("Current selectedText is: " + selectedText);
      }
    });

    return selectedText;`

**Comment by MatthiasEngh** [comment]
I like using the value to retrieve the text:
```
/** assume you found your select and called it 'element' */
/** I want to find the selected option text and store it in 'optionText' */
const optionValue = element.getValue();
const option = element.$(`[value='${optionValue}']`);
const optionText = option.getText();
```
