### ISSUE TITLE
browser.url() and browser.getUrl() returns promise in synchronous mode

### ISSUE THREAD

**Issue by sergeyt** [webdriverio/webdriverio#1610]
## The problem

`browser.url()` returns promise while I expect to get string synchronously. Calling `browser.url("https://localhost:8000/")` works synchronously. I think this is not consistent behavior.

## Environment

* WebdriverIO version: 4.2.16
* Node.js version: 6.5.0
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): none

**Comment by christian-bromann** [comment]
Both commands return synchronous results. Just verified it. Make sure to call the command in the same eventloop as your it block.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by sergeyt** [comment]
@christian-bromann thanks, it seems it because I use https://github.com/xolvio/chimp with its own https://github.com/xolvio/sync-webdriverio
