### ISSUE TITLE
removeApp doesn't work - 

### ISSUE THREAD

**Issue by omerbaki** [webdriverio/webdriverio#1612]
it seems you check appPath param is of type string instead of bundleId.

```
var removeApp = function removeApp(bundleId) {
    if (typeof appPath !== 'string') {
        throw new _ErrorHandler.ProtocolError('removeApp command requires bundleId parameter from type string');
    }
```

**Comment by christian-bromann** [comment]
`bundleId` can be type of string like `browser.removeApp('com.example.android.apis');`

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by omerbaki** [comment]
There's a bug in the code - the param name is "bundleId" but the if statement check that "appPath" is of type string instead of checking "bundleId".

**Comment by christian-bromann** [comment]
Sorry, just seen it. This is already tackled by #1614

**Comment by somaritane** [comment]
I'm afraid this is still not solved. #1614 only cared about `isAppInstalled` command. 
`removeApp` command still checks for `appPath` being `string` type, not `bundleId` being `string` type.
Should we reopen the issue or create a new one? Thanks.

**Comment by christian-bromann** [comment]
@somaritane thanks for pointing this out. Fixed issue.
