### ISSUE TITLE
Change userAgent in FireFox browser

### ISSUE THREAD

**Issue by jangot** [webdriverio/webdriverio#1613]
Hello.
I need to change userAgent in FireFox browser.
I have found [docs](http://webdriver.io/guide/services/firefox-profile.html) for firefox-profile module.
I have instaled `firefox-profile` in my project.
But did not get some effect.
```
webdriverio.remote({
        browserName: 'firefox',
        services: ['firefox-profile'],
        firefoxProfile: {
            'general.useragent.override': userAgent
        }
    }).init();
```
Where did I do a mistake?

**Comment by christian-bromann** [comment]
the profile service works only when using the wdio testrunner. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
