### ISSUE TITLE
webdriverio.multiremote does not work if the remote capabilities are being passed as a variable

### ISSUE THREAD

**Issue by aqiqul** [webdriverio/webdriverio#1615]
## The problem

passing multiremote(<variable>) does not work. errors 
 Error: Cannot init a new session, please end your current session first
but when I write all capabilities in the body it works:
  multiremote( browser_1;{ user:sause.user, key:saucwekey, desiredCapabilities{ browsername: 'firefox'}})

## Environment

* WebdriverIO version:  4.1
* Node.js version: 6.4.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): standalone
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Details
multiremote() using a string variable fails, but if I set the same string inside the method it works.
error:
/root/node_modules/webdriverio/node_modules/q/q.js:155
                throw e;
                ^

Error: Cannot init a new session, please end your current session first

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]

```js
var q = require("q");
var client = require('webdriverio');
var options_a = " mySafari:{ user: process.env.SAUCE_USERNAME, key: process.env.SAUCE_ACCESS_KEY, desiredCapabilities: { browserName: 'safari' } }";
client
	.multiremote({ options_a)
        .init()
	.pause(1000)
        .url('http://google.com')
	//.windowHandleMaximize()
       .pause(7000)
       .end();
```

**Comment by christian-bromann** [comment]
First of all it only helps if you write code example in proper markdown. Second the code above has a syntax error. Third please check out the example folder in this repository and read about multiremote on webdriver.io
