### ISSUE TITLE
Website Navigation Issue from Cloud Services page

### ISSUE THREAD

**Issue by kaushlakers** [webdriverio/webdriverio#1616]
## The problem

[The Get Started Configuration Page](http://webdriver.io/guide/getstarted/configuration.html) mentions to refer to the "cloud service docs" which links to [this page](http://webdriver.io/guide/testrunner/cloudservices.html). None of the links on the left side of this page actually work. I'm guessing [this](http://webdriver.io/guide/usage/cloudservices.html) is the correct link it should navigate to and the previous one is from an older version or it was moved to a new path.

**Comment by christian-bromann** [comment]
Thanks for filing the issue. Link got fixed and website will be updated soon.
