### ISSUE TITLE
Throwed error after webdriver instance ended

### ISSUE THREAD

**Issue by mpetrak** [webdriverio/webdriverio#1618]
## Question

Hi guys,
I've one question about webdriver. I'm experiencing this kind of problem and can't find a way how to solve it.

Running selenium tests in node with webdriverIO and Mocha. Mocha `bail` options is set to `false`.
When first test ends by mocha timeout. Second starts, init new webdriver, but error from first run (assertion, selenium session no longer valid, etc.) is throwed and catched here, which basically means second test is failing because of timeout from previous one, however there is `end()`call even if test fails.
Is there a way how to completely and immediately stop actual webdriver execution and stop / reset all opened promise chains?

## Environment

* WebdriverIO version: 4.2.16
* Node.js version: 4.4.7
* Standalone mode
* asynchronous tests:
* Mocha version: 2.5.3

## Code To Reproduce Issue

For example imagine this part of code like 1st test:
```

before: function(done) {
    driver.init().then(() => {
        done();
   });
},

'open a google window: function(done) {
   this.timeout(5000); // set mocha timeout
   driver.url('http://google.com')
             .then(() => {
                setTimeout(() => {
                     assert.isTrue(false, 'Failed assert');
                     done();
                }, 10000);
            });
},

after: function(done) {
  driver.end().then(() => {
       done();
   });
}
```

**Comment by christian-bromann** [comment]
I would recommend using the wdio testrunner if you want to scale up your Selenium tests. You also don't need to deal with async commands anymore. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
