### ISSUE TITLE
waitForVisible docs are internally inconsistent

### ISSUE THREAD

**Issue by acthp** [webdriverio/webdriverio#1622]
## The problem

waitForVisible docs are internally inconsistent.

## Details

http://webdriver.io/api/utility/waitForVisible.html

param ```selector``` is not documented as optional, but the example does not include a selector parameter.

The call is documented as a method on ```client```, but the example shows it invoked on an element.

The other waitFor method docs are similar. If there are two methods, on the client and element objects, it should be documented as such, and params for both calls should be accurately described.

**Comment by christian-bromann** [comment]
I wrote more documentation around how to use elements as first citizen as well as removed all async examples from the API. This should prevent new people from getting confused around sync/async. In general we want everyone to write their automation test with the test runner.
