### ISSUE TITLE
Failure in root-level Mocha hooks causes a TypeError

### ISSUE THREAD

**Issue by msegado** [webdriverio/webdriverio#1628]
_(Note, this probably isn't critical to fix since there's presumably an easy workaround [using WDIO's hooks instead of Mocha's], but it should be mentioned in the docs to avoid confusion when people try to use the Mocha hooks and things break. Thanks for the great free tool!)_

## The problem

Mocha allows for [root-level hooks](https://mochajs.org/#root-level-hooks) which run before all test suites. A failure in one of these currently results in a TypeError:

```
/[...]/webdriverio/build/lib/utils/ReporterStats.js:403
            testStats.state = 'fail';
                            ^

TypeError: Cannot set property 'state' of undefined
    at ReporterStats.testFail (/[...]/webdriverio/build/lib/utils/ReporterStats.js:403:29)
    at BaseReporter.<anonymous> (/[...]/webdriverio/build/lib/utils/BaseReporter.js:159:25)
    at emitOne (events.js:96:13)
    at BaseReporter.emit (events.js:188:7)
    at BaseReporter.handleEvent (/[...]/webdriverio/build/lib/utils/BaseReporter.js:300:27)
    at Launcher.messageHandler (/[...]/webdriverio/build/lib/launcher.js:594:28)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

Related:
- #1460 ("Errors in beforeSuite don't get correctly reported and prevent onComplete")... see comments further down in particular and some of the attempted/reverted fixes for it.
- webdriverio/wdio-mocha-framework@2e5e7642f41c5cdcdf73c1a42c0f1ce1e35b44be ("make sure user hooks don't interfer with test process - closes webdriverio/webdriverio1460"). I suspect this fixed the problem for WDIO's global hooks but not for Mocha's root-level hooks.
- #1624 ("ReporterStats throws a TypeError if nested test suites are in a single spec"). May result from a different issue altogether, but it leads to the same error being thrown in ReporterStats.js so it is probably good to keep in mind when considering any fixes.

## Environment

* WebdriverIO version: **4.2.16**
* Node.js version: **6.5.0**
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): **wdio**
* if wdio testrunner, running synchronous or asynchronous tests: **sync**
* Additional wdio packages used (if applicable):
   - "wdio-mocha-framework": "^0.4.3",
   - "wdio-phantomjs-service": "^0.1.0",
   - "wdio-spec-reporter": "0.0.3",

## Link to Selenium/WebdriverIO logs

https://gist.github.com/msegado/af5efd3e7778d6e9eed09a9b9ccb97cf

## Code To Reproduce Issue
test.js:
```js
before(() => {
  browser.url('/login');
  browser.waitForExist('#does-not-exist');  // cause a failure
});

describe('Some suite', () => {
  it('does nothing', () => {});
});
```

wdio.conf.js:
```js
exports.config = {
  specs: [
    './test.js',
  ],
  capabilities: [
    { browserName: 'phantomjs' },
  ],
  sync: true,
  logLevel: 'verbose',
  coloredLogs: true,
  baseUrl: 'http://localhost:8000',
  waitforTimeout: 3000,
  services: ['phantomjs'],
  framework: 'mocha',
  reporters: ['spec'],
  mochaOpts: {
    ui: 'bdd',
  },
};
```

**Comment by christian-bromann** [comment]
fixed, will be released with the next version `4.3.0`
