### ISSUE TITLE
waitUntil returns no usable stack trace

### ISSUE THREAD

**Issue by acthp** [webdriverio/webdriverio#1629]
## The problem

When the condition passed to waitUntil throws, there's no usable stack trace logged.

## Environment

* WebdriverIO version: 4.2.16
* Node.js version: 0.12.7
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): no idea. Running from chimp.
* if wdio testrunner, running synchronous or asynchronous tests: synchronous.

## Details

An example stack trace stemming from an error in the waitUntil condition:

```
     Error: Promise was rejected with the following reason: TypeError: undefined is not a function
      at Object.Future.wait (node_modules/fibers/future.js:454:15)
      at Object.<anonymous> (node_modules/wdio-sync/build/index.js:345:27)
      at Context.<anonymous> (test.js:110:12)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
```

This is not the stack at the time of the error. It's the stack of the promise.

**Comment by christian-bromann** [comment]
@acthp chimpjs is using a different way to synchronize commands so this issue should be reported on the chimpjs repository.
