### ISSUE TITLE
sync / async behavior is not documented

### ISSUE THREAD

**Issue by acthp** [webdriverio/webdriverio#1630]
## The problem

There are sync and async examples in the docs, but no explanation of how to call synchronously vs. asynchronously. This is horribly confusing. By accident I ran across Timer code that does a string match on the name of the anonymous function passed to waitUntil, and thus behaves differently wrt sync/async. So, magic, undocumented semantic function names? Wow, that is impossible to know unless you already know it.

**Comment by christian-bromann** [comment]
This functionality is not undocumented! The difference why we have async and sync examples is stated here: http://webdriver.io/guide/getstarted/modes.html

The fact that you can switch back to async behavior is either documented here:
http://webdriver.io/guide/getstarted/upgrade.html

Also the [API page](http://webdriver.io/api.html) states:
> Each command documentation usually comes with an example that demonstrates the usage of it using WebdriverIO asynchronously in standalone mode and synchronously using the wdio test runner.

We are trying to work on the docs as we release our version. Never hesitate to reach out on our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) and __never__ assume we wouldn't care!

**Comment by acthp** [comment]
Thanks. :)  I never would have found the docs for functions named 'async', since they're on the 'upgrade' page. I also would not have expected to find it in 'Standalone vs. WDIO'. Having read it, I still don't understand it. ;) I started with chimp, for historical reasons, but my test functions look like the wdio example, not the standalone example: calls are synchronous.

So, 'client' and 'browser' are different objects, implementing async & sync versions of the API, respectively? Looks like no, because the 'upgrade' docs show you can pick sync/async at run time. So, the API switches mode based on the name of the spec function from which it was invoked?

But waitUntil independently switches mode based on the name of the condition function?

I really think sync/async could use a doc section of its own.

Looking at wdio now, I'm wondering if my project would be better moved to it, vs. chimp, as it seems to provide a lot of the same integration.

**Comment by christian-bromann** [comment]
I agree that there could be clearer docs around the async function name but it was a feature introduced to make porting tests to v4 easier (in v3 all commands were async) and will be deprecated/removed with the next versions.

Chimp has its own sync implementation for commands. They basically use WebdriverIO in standalone mode (so in async mode) but build a wrapper around commands to make them sync.

> So, 'client' and 'browser' are different objects

No, they are basically the same. I refer to `client` to instances that are initiated using the standalone package and `browser` to instances initiated by the wdio testrunner.

> But waitUntil independently switches mode based on the name of the condition function?

Yes, for convenient purposes, given you want to create a custom command that executes a 3rd party library which returns a promise.

If you switch to wdio you still can run commands synchronously and also can leverage from all the reporters and services wdio provides.

Hope that makes it clear. 
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have more questions.

**Comment by nullin** [comment]
@christian-bromann , which commands will be deprecated/removed in future versions? Are you going to drop support for async version in wdio test runner? Or drop the wdio stand alone mode?

I am planning on using wdio test runner but writing all tests in async mode (sync: false)...

**Comment by christian-bromann** [comment]
> which commands will be deprecated/removed in future versions?

All protocol commands that are not part of the W3 Webdriver spec.

> Are you going to drop support for async version in wdio test runner? Or drop the wdio stand alone mode?

Even if I would like to, I couldn't. The project will always support standalone mode because that is how it naturally works. I am recommending to still consider use the sync mode because it provides several syntax features that you don't have with standalone.

**Comment by monolithed** [comment]
I want to intercede for async mode. Look at my example:

```ts
import AccountManager, { Credentials, RegisterOptions } from '@qa/account-manager';

class Account {
	async session (type: string = 'basic', options: Credentials = {}): Credentials {
		let { type = 'oauth',  host = browser.options.baseUrl } = options;           
		let account = new AccountManager.Session();

		let { cookie, credentials }  = browser.waitForPromise<Credentials>(() => {
			return account.session({ ...options, type, service });
		}, timeout, 'Could not get user session');

		this.setCookie(cookie);

		return credentials;
	}
}
```

**waitForPromise**:

```ts
let { waitforTimeout = 10 * 1000 } = browser.options;
let lastMessage = '';

browser.addCommand('waitForPromise', (promise, timeout = waitforTimeout, message = '') => {
	let result = null;

	browser.waitUntil(function async () {
		return new Promise((resolve, reject) => {
			global.setTimeout(() => {
				console.error('Rejection error:', lastMessage);
			}, waitforTimeout);

			if (typeof promise === 'function') {
				promise = promise();
			}

			promise.then(response => {
				result = response;
				resolve(true);
			},
			error => {
				lastMessage = error;
				resolve(false);
			});
		});
	}, waitforTimeout, `Timeout of ${waitforTimeout}ms exceeded. ${message}`);

	return result;
});
```

The current situation:

```ts
import AccountManager, { Credentials, RegisterOptions } from '@qa/account-manager';

class Account {
	async session (type: string = 'basic', options: Credentials = {}): Credentials {
		let { type = 'oauth',  host = browser.options.baseUrl } = options;           
		let account = new AccountManager.Session();

		let { cookie, credentials }  = account.session<Credentials>({ ...options, type, service });

		this.setCookie(cookie);

		return credentials;
	}
}
```

In my case, the `account.session`method  has its own internal timeout and good exceptions. So, async mode with async/await is more preferred way to write even more clearer code without any strange wrappers around waitUntil.

**Comment by christian-bromann** [comment]
> In my case, the account.sessionmethod has its own internal timeout and good exceptions. So, async mode with async/await is more preferred way to write even more clearer code without any strange wrappers around waitUntil.

Sure you can abstract anything so that it is clearer for your use case. Unfortunately not everyone is an advanced coder and sometimes just likes a simple and quick solution. Async vs sync is just a matter of how it gets executed. You can do that with sync behavior as well.

**Comment by oliviertassinari** [comment]
> I am recommending to still consider use the sync mode because it provides several syntax features that you don't have with standalone.

I'm curious to learn more about it. What are those features? With the information I have, I would definitely pick the *async/await* syntax over another sync abstraction.

**Comment by christian-bromann** [comment]
For example, we enhance the prototype of the element response so that you can stuff like:

```js
var expect = require('chai').expect;
describe('webdriver.io api page', function() {
    it('should be able to filter for commands', function () {
        browser.url('http://webdriver.io/api.html');
        // filtering property commands
        $('.searchbar input').setValue('getT');
        // get all results that are displayed
        var results = $$('.commands.property a').filter(function (link) {
            return link.isVisible();
        });
        // assert number of results
        expect(results.length).to.be.equal(3);
        // check out second result
        results[1].click();
        expect($('.doc h1').getText()).to.be.equal('GETTEXT');
    });
});
```

**Comment by diachedelic** [comment]
I have not been able to find documentation on the exact nature of standalone/asynchronous mode's "Promises".  I had to check out [this example](https://github.com/cognitom/webdriverio-examples/tree/master/standalone-mode), run and modify the tests to discover that

```javascript
it('gets the title of MDN toppage', () => {
  return browser
    .url('https://developer.mozilla.org/en-US/')
    .getTitle().then(title => {
       assert.equal(title, 'Mozilla Developer Network')
    })
})
```

is not equivalent to

```javascript
it('gets the title of MDN toppage', async() => {
  browser.url('https://developer.mozilla.org/en-US/')
  const title = browser.getTitle()
  assert.equal(title, 'Mozilla Developer Network')
})
```

even though it looks like it should be.  In the second example using `async`/`await`, `title` ends up being an empty string.

Is there any plan to support `async`/`await`?  The testrunner/synchronous mode kind of freaks me out.

I fully understand that it is not trivial to support actual promises here.

**Comment by christian-bromann** [comment]
> Is there any plan to support async/await?

This is supported!

> The testrunner/synchronous mode kind of freaks me out.

Why is that?

> because I'm assuming that a command queue is being constructed ala Nightwatch

No command queue. The client object is a Monad. It supports both types: the promise and the ajax monad.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions.

**Comment by oliviertassinari** [comment]
> Why is that?

@christian-bromann I would love to see an asynchronous only API. with async/await rolling out. I don't think that the synchronous API is longer needed.

**Comment by christian-bromann** [comment]
> it could simplify webdriverio internals, less prone to errors.

What kind of errors are you talking about?

> would love to see an asynchronous only API. with async/await rolling out.

Again, this is supported, you can use async/await with WebdriverIO

If you claim something is not supported please provide an example or some sort of proof that it actually isn't supported.

**Comment by diachedelic** [comment]
I just assumed because I couldn't find an example anywhere of async/await being used with webdriver.io, and because I tried it and it didn't work (see above example), that `async`/`await` was not supported!  Could you please point me in the direction of some examples of it working, or documentation?

The reason the synchronous API feels strange to me is that I've been trained to expect non-trivial operations in javascript to be async (especially network!).  It's the same reason I don't like the way Nightwatch's callbacks are executed in a different scope, it breaks the expectations you have of the language.

**Comment by christian-bromann** [comment]
> I tried it and it didn't work (see above example)

You need to be clear why it was not working, any error message?

> Could you please point me in the direction of some examples of it working, or documentation?

Here:
```js
var client = require('webdriverio').remote({ desiredCapabilities: { browserName: 'chrome' } });

(async () => {
    await client.init();
    await client.url("...");
    // ....
})()
```

> The reason the synchronous API feels strange to me is that I've been trained to expect non-trivial operations in javascript to be async (especially network!)

I get that. A lot of people though don't have a lot of JS experience and find it difficult to handle async code in their tests. By abstracting away all this it gets much more easier to write less verbose and error prone tests. I rather have my test look like this:

```js
var expect = require('chai').expect;
var DynamicPage = require('../pageobjects/dynamic.page');

describe('dynamic loading', function () {
    it('should be an button on the page', function () {
        DynamicPage.open();
        expect(DynamicPage.loadedPage.isExisting()).to.be.equal(false);

        DynamicPage.btnStart.click();
        DynamicPage.loadedPage.waitForExist();
        expect(DynamicPage.loadedPage.isExisting()).to.be.equal(true);
    });
});
```

.. than having an `await` in front of every line. Since all commands are asynchronous, for me it doesn't really make sense to let the user handle it. However you can still switch back to async even when using wdio but the syntax is just so much nicer, e.g. being able to do this:

```js
var results = $$('.commands.property a').filter(function (link) {
    return link.isVisible();
});
```

is awesome and would not work with async/await.

**Comment by diachedelic** [comment]
Steps to reproduce:

1. Check out [this repo](https://github.com/cognitom/webdriverio-examples/tree/master/standalone-mode)
2. Run test (passes, or at least nearly passes)
2. Change `test/e2e/first.js` to use `async`/`await` (as per my example above)
3. Run test (does not pass at all, `title` is an empty string)

**Comment by diachedelic** [comment]
I can put together a sample repo and open a new issue if thats easier.

**Comment by christian-bromann** [comment]
> I can put together a sample repo and open a new issue if thats easier.

Isn't https://github.com/cognitom/webdriverio-examples/tree/master/standalone-mode already an sample repo?

**Comment by diachedelic** [comment]
> .. than having an await in front of every line. Since all commands are asynchronous, for me it doesn't really make sense to let the user handle it.

I found my error, I was missing an `await` before `browser.url()`, which I think proves your point.

I had been wary about where the magic was hiding, but now I feel confident that the async mode has no hidden magic.  And knowing that the sync mode is (presumably) built directly on top of the async mode makes me less wary of sync too.

**Comment by christian-bromann** [comment]
> And knowing that the sync mode is (presumably) built directly on top of the async mode makes me less wary of sync too.

👍 

One missing await can screw up a whole workday that is why I feel it should be handled as sync everywhere.

**Comment by monolithed** [comment]
> One missing await can screw up a whole workday that is why I feel it should be handled as sync everywhere.

That's why we use TypeScript :)

**Comment by marthinus-engelbrecht** [comment]
I must say I just disagree with the sync by default argument on a philosophical level. Promises and Javascript's async nature are fundamental concepts of the language and I would argue if you don't understand them then you shouldn't be writing javascript code, cause it's everywhere. At least if we don't hide it, then the pain will cause you to learn.

**Comment by trickeyd** [comment]
I have to say i totally agree that there is a huge lack of documentation on this topic. I have recently taken over a huge codebase (without handover) that uses webdriver with appuium, neither of which I have used before.

I read everything I could find, but there was no explanation of why I should chose one over the other. And that made the rest of the docs pretty confusing to be honest. It took a while before I even realised it was not a choice on a function by function basis. 

This thread has finally cleared it up for me but it would have saved a huge headache if id found it a couple of days ago. Even a link to this from the docs would be useful.

p.s. quote of the year 
"if you don't understand [promises] then you shouldn't be writing javascript code" 🤣 🤣 🤣 
New years day hangover per chance? 😉

**Comment by trickeyd** [comment]
Quick question - in async mode I know that all browser functions return a promise. Is this also true of all element functions?

**Comment by sombreroEnPuntas** [comment]
Consider the following use case.

There is an async function `searchMessages` that fetches messages from an external service.
It takes some time for the service to actually have those messages, so the resolved promise will contain an empty list for some X milliseconds. But later on, it will contain some messages.

This is correct expected behavior.

We need to keep re-trying until there is content on the list.

Something like the following seems to be **NOT** possible on wdio:
```
    let messagesIds;

    // can not pass async here cuz' it is expecting sync function
    await browser.waitUntil(async () => {
      messagesIds = await searchMessages(searchfilter);
      return messagesIds.length >= 1;
    }, TIMEOUT);

   // do something with messagesId
```

Why? Is it by design? If so, is there a better way to do this?

**Comment by mgrybyk** [comment]
How is this related to this issue? There are no logs, no steps to reproduce, I don't know why it doesn't work. 

If you can manage to find out, please rise a ticket, we would be glad to help.

Thank you

**Comment by sombreroEnPuntas** [comment]
@mgrybyk it is not documented that `waitUntil` can ONLY receive a sync function.
I did provide a code sample that fails.

I just edited my comment with a solution.... but still seems a bit convoluted :)

From the docs, I would expect that both sync and async are valid here.

**Comment by christian-bromann** [comment]
> it is not documented that `waitUntil` can ONLY receive a sync function.
> I did provide a code sample that fails.

`waitUntil` respects promises and waits for them. Please provide a reproducible example and we can look into it.

**Comment by sombreroEnPuntas** [comment]
That is not what I observed.

I am using `"webdriverio": "^5.9.6"` on typescript and the following plugins/modules:
```
    "@wdio/allure-reporter": "^5.9.3",
    "@wdio/cli": "^5.9.4",
    "@wdio/local-runner": "^5.9.6",
    "@wdio/mocha-framework": "^5.9.4",
    "@wdio/selenium-standalone-service": "^5.9.3",
    "@wdio/spec-reporter": "^5.9.3",
    "@wdio/sync": "^5.9.4",
```

I invoke the runner with `yarn wdio`.

And the compiler fails 'cuz (as explained on the sample I posted above) `waitUntil` can not receive an async function.

```
0-0 worker error { name: 'TSError',
  message:
   "⨯ Unable to compile TypeScript:\ntest/specs/basicPolicyOrderHappy.ts(121,7): error TS2345: Argument of type '() => Promise<boolean>' is not assignable to parameter of type '() => boolean'.\n  Type 'Promise<boolean>' is not assignable to type 'boolean'.\n",
```

**Comment by christian-bromann** [comment]
> `waitUntil` can not receive an async function.

It can, the typings just aren't accurate on that front. PRs are welcome!

**Comment by mgrybyk** [comment]
@sombreroEnPuntas please update to the latest version, the issue has been fixed some time ago

**Comment by mgrybyk** [comment]
https://github.com/webdriverio/webdriverio/blob/d77ba56300b2f172c35b3ce1e69ebaa9eee78cda/packages/webdriverio/webdriverio.d.ts#L50

**Comment by diachedelic** [comment]
@sombreroEnPuntas perhaps you could use a library like [p-wait-for](https://www.npmjs.com/package/p-wait-for) instead of `browser.waitUntil`, assuming you are not using the sync testrunner

**Comment by christian-bromann** [comment]
@diachedelic `waitUntil` waits for promises, it is just a typescript problem that was fixed a couple of versions ago.

@sombreroEnPuntas please let us know if this error persists after upgrading the webdriverio versions. Thanks!
