### ISSUE TITLE
custom http-headers

### ISSUE THREAD

**Issue by ngadiyak** [webdriverio/webdriverio#1632]
Hi!
Whether possible means webdriver add a custom http-header?

**Comment by monolithed** [comment]
There is no way in Selenium to set the request headers. 
But you can specify cookie with [setCookie](http://webdriver.io/api/cookie/setCookie.html) or `document.cookie` and `UserAgent`. The usual way to change the UserAgent for Firefox is to set the variable "general.useragent.override" in your [Firefox profile](https://github.com/webdriverio/wdio-firefox-profile-service). 
With Chrome use chromeOptions in your capabilities section:

```js
{
        browserName: 'chrome',
        chromeOptions: {
             args: ['user-agent=Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X; en-us) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53']
        }
    }
```

**Comment by ngadiyak** [comment]
it will not work for me.
Scenario:
1. Open the page
2. Click on the button

When you click the button you want to add some nttp-header

**Comment by christian-bromann** [comment]
Adding http headers dynamically is not possible with Selenium.

**Comment by pablocoletto** [comment]
Hi, I know this ticket is closed but since it's quite old, I want to check if it's an available feature in newer versions from webdriver.io
