### ISSUE TITLE
web testing on sauce android/ios is failing - also observe multi instance start one after another

### ISSUE THREAD

**Issue by aqiqul** [webdriverio/webdriverio#1636]
## The problem

Webtesting on sauce android/ios fails

## Environment

* WebdriverIO version: 1.4.1
* Node.js version:4.6.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):wdio
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Details
**problem1:** trying to launch chrome/browser inside
[sample.zip](https://github.com/webdriverio/webdriverio/files/516177/sample.zip)

 android 4.4 , works well on local appium, but fails on sauce.
**Problem2**: once the first one fails another instance starts and have observed upto 10 instances run and fail.

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
1. you've set `maxInstances` to 10 which will automatically tell the runner to run 10 instances in parallel

> android 4.4 , works well on local appium, but fails on sauce.

capabilities look right so without any further information like sauce job url or logs I can't tell anything.

**Comment by aqiqul** [comment]
I have tried with max instance =1 as well, same result unending loop of jobs running after previous failure.
saw this error in the ,metadata:
The new session request was cancelled before a Sauce Labs virtual machine was found. For help, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages 
![numberofjobsrunning_failed](https://cloud.githubusercontent.com/assets/21106771/19192396/1a3735fe-8c74-11e6-9cf7-c0a4c581caff.png)
[selenium-server_log.txt](https://github.com/webdriverio/webdriverio/files/516309/selenium-server_log.txt)

**Comment by aqiqul** [comment]
Here is url to one of the jobs:
https://saucelabs.com/beta/tests/526ccff3495242589e5573b454aa3e80/metadata

**Comment by christian-bromann** [comment]
@aqiqul can you try to use these caps:
```js
caps['browserName'] = 'Browser';
caps['appiumVersion'] = '1.5.3';
caps['deviceName'] = 'Android Emulator';
caps['deviceOrientation'] = 'portrait';
caps['platformVersion'] = '5.1';
caps['platformName'] = 'Android';
```
Also try to double the `retryConnectionTimeout`

**Comment by aqiqul** [comment]
Giving a try!

**Comment by aqiqul** [comment]
sorry : there is "connectionRetryCount" and a "waitforTimeout:" which one should I increase , waitfortimeout is already set to 5000000, should I add the retryConnectionTimeout as a new option?

**Comment by christian-bromann** [comment]
connectionRetryCount

**Comment by aqiqul** [comment]
The change in caps seemed to work without the 
"browser.windowHandleMaximize();"

it was getting stuck on this code as not supported on android.
so it beats the purpose of using the same code for browsers on PC and Devices.
Shoudl there be something else to handle this.

**Comment by christian-bromann** [comment]
Nope. I just wouldn't use `windowHandleMaximize` and set resolution in the desired capabilities

**Comment by aqiqul** [comment]
Great! shall give it a try , Thanks for all the help, so the Platform configurator has a bug?

**Comment by christian-bromann** [comment]
No, I am wondering by myself why the galaxy vms don't start chrome. I will forward it to our mobile team.

**Comment by aqiqul** [comment]
I opened a case on sauce if that helps 
Case ID: 	43891
Assigned Agent: 	Enrique Gonzalez
