### ISSUE TITLE
Show support for different environments for each command

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#1637]
## The problem

Some commands are only working in specific environments and only when running a specific driver. The API need to help test developers to understand which commands they can use in the environment they test in.
## Details

Let's create more visual support in our API docs showing which command can run in which environment. This requires to have some kind of automated test for each command to check if an error message gets returned or not. From that we should create a support table.  It also will help us to identify the bottlenecks of certain drivers and accelerate the effort in fixing these problems and find workarounds.

ref https://github.com/webdriverio/webdriverio/pull/1583

**Comment by jankcat** [comment]
Non-dynamic support technically exists in the doc engine for this now. API files can include the `* @for android, ios` tag currently. If chrome, ie11, edge, safari, etc icons were added [here](https://github.com/webdriverio/webdriver.io/tree/master/themes/webdriver.io/source/images/icons), this could be a simple solution to the problem. Then it would be just a matter of updating documentation in the js files themselves.

**Comment by christian-bromann** [comment]
@jankcat it is less about which browser support the command but more which environment. I think we can differentiate between:

- web (chrome, firefox, etc)
- mobile web (iOS Safari, Android web browser)
- mobile hybrid (Selendroid)
- mobile native (ios | android)

Looking at this issue it seems to be almost impossible to track support across all these environments especially since different drivers in a single environment support different things. I would almost say we can close this with a `won't do` resolution.

**Comment by jankcat** [comment]
Fair enough. Yeah there are so many combos that maintaining tests for it would be too cumbersome.
