### ISSUE TITLE
Support for ⌘ key on Mac

### ISSUE THREAD

**Issue by shime** [webdriverio/webdriverio#1638]
## The problem

I'm testing an Electron app via [Spectron](https://github.com/electron/spectron) and I'm trying to send a ⌘ key combination on Mac, but it's not registered. Seems like it's missing from [the spec](https://w3c.github.io/webdriver/webdriver-spec.html#h-keyboard-actions).

Are there any plans to support it?

## Environment

* WebdriverIO version:  4.2.16
* Node.js version: 6.7.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): standalone

## Code To Reproduce Issue

```js
client.keys(['Command', 'm'])
```

**Comment by christian-bromann** [comment]
@shime have you tried `client.keys(['COMMAND', 'm'])` or `client.keys(['META', 'm'])`? WebdriverIO is just a webdriver client and if webdriver doesn't support it WebdriverIO can't support it either.

**Comment by shime** [comment]
Looks like `Command` is [supported](https://seleniumhq.github.io/selenium/docs/api/py/webdriver/selenium.webdriver.common.keys.html) in Selenium 2.0 and it should be passed like in my example, but can't get it to work with Electron.

**Comment by prashantagarwal** [comment]
@shime were you able to solve this ?

**Comment by shime** [comment]
@prashantagarwal nope, sorry.

**Comment by coda-nsit** [comment]
This still seems to be an issue? @shime should this be reopened? Were you able to solve this?

**Comment by shime** [comment]
@coda-nsit I don't remember, but probably not.
