### ISSUE TITLE
waitForExist timeouts do not result in test failures

### ISSUE THREAD

**Issue by patthiel** [webdriverio/webdriverio#1639]
## The problem

When a waitForExist command times out, an exception is thrown and execution of the spec stops, preventing other tests in the spec from running. This failed test is not counted as a failure as well.

## Environment

* WebdriverIO version: 4.2.15
* Node.js version: 4.2.4
* wdio test runner  w/gulp-webdriver latest package
* sync
* wdio-jasmine-framework (latest)

## Link to Selenium/WebdriverIO logs

[Selenium log](https://gist.github.com/patthiel/497dc129df0a295a035d3569452e7980)
[Wdio results](https://gist.github.com/patthiel/5424cbbd7afce615786568b8e91bd4a8)

## Code To Reproduce Issue [ Good To Have ]

[Reproduceable spec](https://gist.github.com/patthiel/2774b36a23099664dd9fd810294e49c6)

**Comment by christian-bromann** [comment]
@patthiel sorry I can't reproduce this issue, can you provide the whole setup as minimum reproducible example?

**Comment by patthiel** [comment]
@christian-bromann i'll try to configure a project this evening to replicate the issue.

**Comment by patthiel** [comment]
@christian-bromann  I've made a quick repo [Here](https://github.com/patthiel/wdio-test-playground) that reproduces the issue. If you pull it down, run: 
```
npm install
gulp wdio
```
You'll see, the first test will timeout and fail and subsequent tests are skipped (although they are executed, based on my selenium logs). This is not the same exact issue as what I've initially reported here. I'm not able to reproduce that yet, but this issue seems related. 

The output should look like this:
```BASH
username12:wdio-test-playground username12$ gulp wdio
[18:08:53] Requiring external module babel-core/register
[18:08:56] Using gulpfile ~/Developer/wdio-test-playground/gulpfile.babel.js
[18:08:56] Starting 'wdio'...

F

0 passing (19.00s)
1 failing

1) Wdio waitforExist Suite waitForExist Timeout - test will FAIL:
Failed: element (something) still not existing after 5000ms
running chrome
Error: element (something) still not existing after 5000ms
    at Object.<anonymous> (specs/test.spec.js:5:17)
    at new Promise (node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:191:7)
    at elements("something") - isExisting.js:45:17
    at isExisting("something") - waitForExist.js:37:22



[18:09:16] 'wdio' errored after 19 s
[18:09:16] Error in plugin 'gulp-webdriver'
Message:
    wdio exited with code 1
```

Note: tested on **Node 4.2.4**

**Comment by christian-bromann** [comment]
I can't do anything until I have something that reproduces the problem

**Comment by patthiel** [comment]
@christian-bromann is it expected that other tests are skipped after a waitForExist times out?

**Comment by christian-bromann** [comment]
> is it expected that other tests are skipped after a waitForExist times out?

no

> My repo reproduces that issue ^^

but you said `I'm not able to reproduce that yet, but this issue seems related.`

**Comment by patthiel** [comment]
Ah, I understand the confusion. Ok, since I am not able to reproduce the original issue of waitForExist command not failing tests on timeout (yet), but I am able to reproduce this other issue related to waitForExist commands timing out and skipping subsequent tests. I will raise a separate issue for that. 👍 ?

**Comment by christian-bromann** [comment]
Please do
