### ISSUE TITLE
ERR_NO_SUPPORTED_PROXIES

### ISSUE THREAD

**Issue by platedodev** [webdriverio/webdriverio#1644]
## The problem

I'm getting "ERR_NO_SUPPORTED_PROXIES" when I try to set up a proxy to my chromedriver.

## Environment

* WebdriverIO version: 4.2.16
* Node.js version: 6.4.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Standalone mode
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Details

I can't find a way to open any website when I set up the argument --proxy-server.

## Link to Selenium/WebdriverIO logs

Theres no logs

## Code To Reproduce Issue [ Good To Have ]

```
var webdriverio = require('webdriverio');
var options = { desiredCapabilities: {
    browserName: 'chrome',
    chromeOptions: {
        // proxy: proxy
        args: ['--proxy-server="http://87.98.219.96:8080"']
    }
} };
var client = webdriverio.remote(options);
client
    .init()
    .url('https://google.com/')
    .getTitle().then(function(title) {
        console.log('The title is: ' + title);
    })
   .end();
```

**Comment by christian-bromann** [comment]
try:

```js
var webdriverio = require('webdriverio');
var options = { desiredCapabilities: {
    browserName: 'chrome',
    chromeOptions: {
        // proxy: proxy
        args: ['proxy-server="http://87.98.219.96:8080"']
    }
} };
var client = webdriverio.remote(options);
client
    .init()
    .url('https://google.com/')
    .getTitle().then(function(title) {
        console.log('The title is: ' + title);
    })
   .end();
```

**Comment by intergleam** [comment]
I am still getting `ERR_NO_SUPPORTED_PROXIES` in Chrome
```
var webdriverio = require('webdriverio');
var options = {
    desiredCapabilities: {
        browserName: 'chrome',
        chromeOptions: {
            // proxy: proxy
            args: ['proxy-server="socks://127.0.0.1:1080"']
        }
    }
};
var client = webdriverio.remote(options);
client
    .init()
    .url('http://ip-api.com/')
    .getTitle().then(function (title) {
        console.log('The title is: ' + title);
    })
   //.end();
```
![image](https://cloud.githubusercontent.com/assets/2155554/26031432/0428c202-386b-11e7-9ace-c7b80be9a809.png)

At the same time Firefox works fine with 127.0.0.1:1080
![image](https://cloud.githubusercontent.com/assets/2155554/26031431/f1bb5e4a-386a-11e7-916e-91638060b52a.png)
![image](https://cloud.githubusercontent.com/assets/2155554/26031445/7e2149c6-386b-11e7-8200-ffa315d436e7.png)

**Comment by intergleam** [comment]
should be 
```  args: ['--proxy-server=socks5://127.0.0.1:1080']```
