### ISSUE TITLE
Fails running against selenium-server-standalone-2.37.0

### ISSUE THREAD

**Issue by wereHamster** [webdriverio/webdriverio#1646]
## Environment

* WebdriverIO version: 4.2.16
* Node.js version: 6.1.0

## Details

Even the simplest script fails:

```javascript
var webdriverio = require('webdriverio');
var options = { desiredCapabilities: { browserName: 'chrome' } };
webdriverio
  .remote(options)
  .init()
  .url('https://duckduckgo.com/')
  .end();
```

The issue appears to be that selenium-server-standalone version 2.37.0 responds with 204 No Content to POST /.../session/.../url, but webdriverio requires a body.

If I change the if condition which processes the response to:

```
if (!err && ((body && body.status === 0) || response.statusCode == 204)) {
```

Then I can run the simple test. I have not tried more complex tests.

**Comment by christian-bromann** [comment]
@wereHamster please update your selenium standalone version. I don't mind to apply this change but your version is more than 2 years old. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by wereHamster** [comment]
webdriverio claims to be "Selenium 2.0 bindings for NodeJS", so I thought it was compatible with all selenium-server-standalone versions 2.x. Are those two version numbers not related?

Also, I could not find any documentation about which versions of selenium-server-standalone webdriverio is compatible with, the documentation only mentions to download the 'current' version.
