### ISSUE TITLE
Watch mode?

### ISSUE THREAD

**Issue by tizmagik** [webdriverio/webdriverio#1647]
Is there a "watch" mode for tests written in WebdriverIO? Similar to how Chimp.js has support for `@watch` tags that automatically re-runs the suite when the test spec has changed?

**Comment by tizmagik** [comment]
Answer is no, but there are gulp and grunt plugins.

**Comment by christian-bromann** [comment]
We haven't build in that feature yet but planning to do so!

**Comment by tizmagik** [comment]
Happy to contribute this feature if you could point me in the right direction!

**Comment by klamping** [comment]
@tizmagik took a quick look at the 'onchange' npm module and was able to get this sort of thing working with the following command:
```
# onchange 'src/**/*.[css,js,html]' 'test/**/*.js' -- wdio
```

It will run the tests whenever the src or test files are changed. You can configure that to be a bit more specific if you'd like: https://www.npmjs.com/package/onchange

**Comment by tizmagik** [comment]
@klamping pretty cool, thanks for sharing! Might give that a try

**Comment by klamping** [comment]
@tizmagik FYI, documented the full set up here: http://blog.kevinlamping.com/continuous-local-webdriverio-testing-with-onchange-and-node-notifier-watching/

**Comment by tizmagik** [comment]
That's awesome, thanks @klamping !
