### ISSUE TITLE
An enhancement for getText function

### ISSUE THREAD

**Issue by JIM-CHEN** [webdriverio/webdriverio#1650]
Hi, 

I found getText cannot get text deeply, it would be better to get all children deeply text with getText function.

**Comment by christian-bromann** [comment]
What do you mean by "deeply"?

**Comment by JIM-CHEN** [comment]
Hi,

Here's the example
---
<div>
    <div>
        <span>
            <span>a</span>
            <span>b</span>
        </span>
        <b>123</b>
    </div>
    <span>test2</span>
</div>
---
I expect that will get "ab123test2" from the top, but it will break in "ab".

Not sure if there's another solution.

Thanks.

**Comment by JIM-CHEN** [comment]
Sorry for mistake,

We found there's a known issue that getText cannot get elements were invisible.
Just use getHTML then parsing them.

Let's close it
Thanks
