### ISSUE TITLE
Implement W3C Actions API

### ISSUE THREAD

**Issue by graingert** [webdriverio/webdriverio#1653]
## The problem

moveTo is not part of the W3C WebDriver spec, it would be a good idea to move to the actions API to support modern firefox.

see also: https://github.com/mozilla/geckodriver/issues/159 and https://github.com/SeleniumHQ/selenium/issues/2285
## Environment
- WebdriverIO version: 4.2.16
- Node.js version: v6.8.1
- [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): standalone
- if wdio testrunner, running synchronous or asynchronous tests: asynchronous
- Additional wdio packages used (if applicable): N/A

**Comment by christian-bromann** [comment]
on hold until it landed in one of the driver
ref https://bugzilla.mozilla.org/show_bug.cgi?id=1292178

**Comment by christian-bromann** [comment]
Latest info from @jgraham from 2016-10-20 14:23:30 PDT
> This is being actively worked on and we are well aware of its importance. It is also a large and complex part of the specification to get right. Please don't spam the bug with me-too style comments.

**Comment by christian-bromann** [comment]
Done by https://github.com/webdriverio/webdriverio/commit/b78172b6da8788a4dc38f056918d425bf4512ff1
