### ISSUE TITLE
Stop on first failure

### ISSUE THREAD

**Issue by delijah** [webdriverio/webdriverio#1654]
## The problem

I want to stop the test run after the first failure, but there is no config option for this for jasmine.

## Environment

* WebdriverIO version: 4.2.16
* Node.js version: 6.7.0
* wdio testrunner
* synchronous

**Comment by christian-bromann** [comment]
Try https://www.npmjs.com/package/jasmine-bail-fast

Jasmine doesn't support this natively. Mocha does.

**Comment by delijah** [comment]
What about...?

"To use the new feature in node.js, set "stopSpecOnExpectationFailure": true on the top level of jasmine.json or run jasmine --stop-on-failure=true (confusing just --stop-on-failure is silently ignored). If given, flag overrides config"

Stolen from: http://stackoverflow.com/questions/22119193/stop-jasmine-test-after-first-expect-fails#comment53273690_31809311

In the jasmine world: http://jasmine.github.io/2.5/node.html

**Comment by christian-bromann** [comment]
you can add this option to you `jasmineNodeOpts` then.

**Comment by delijah** [comment]
As far as i can see wdio-jasmine-framework does not really forward this config option to Jasmine. The fact that it has no influence on the test-run confirms my guess.

**Comment by christian-bromann** [comment]
@delijah probably because this add on is only working with jasmine@v2.5. Can you open an issue to update jasmine in the wdio-jasmine-framework?

**Comment by delijah** [comment]
Done. Thank you!
