### ISSUE TITLE
Incorrect paths in config

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1656]
### Config

```js
{
   seleniumLogs: '/Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/cache/logs'
}
```

### Result

```
/Users/a.abashkin/workspace/mail.ru/e.mail.ru/Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/cache/logs
```

### Expected

```
/Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/cache/logs
```

![img-2016-10-19-20-52-17](https://cloud.githubusercontent.com/assets/803674/19530785/f25f782e-963d-11e6-9911-f594d51aa276.png)

**Comment by monolithed** [comment]
My fail

**Comment by christian-bromann** [comment]
Are you using the selenium-standalone service? If yes I think we should file the issue there.

**Comment by monolithed** [comment]
Yep, selenium-standalone

**Comment by christian-bromann** [comment]
This issue was moved to webdriverio/wdio-selenium-standalone-service#13
