### ISSUE TITLE
Authentication popup

### ISSUE THREAD

**Issue by sky-joaonabais** [webdriverio/webdriverio#1658]
## The problem

Hi,

I'm being unable to fill and submit an authentication popup using webdriverio.

## Environment

* WebdriverIO version: 4.2.16
* Node.js version: 4.5.0
* Standalone Mode
* Running synchronous

## Details

From this [SO question/answer](http://stackoverflow.com/questions/24304752/how-to-handle-authentication-popup-with-selenium-webdriver-using-java) it is possible to do it with selenium webdriver (I know I've linked a java example, but I've seen other examples with js selenium webdriver version before).

From [webdriverio API](http://webdriver.io/api.html) I only have 3 methods for handling alerts:

- alertAccept
- alertDismiss
- alertText

How can I instantiate an alert instance? Or how can I get the webdriver instance in order to do this like the example linked?

PS: this is a redirect I get in the middle of my test when I click a button, and I can't manipulate URL in order to add basic auth to the URL like "http://user:password@www.testsite.com".

Thanks!

Best,
João.

**Comment by christian-bromann** [comment]
You can't handle authentication popups with selenium. You need to access the url with the following form: `http://username:passwork@applicationURL`. If it is a redirect then I don't know how to do this. In general you have two options. Use a browser profile that is already authenticated with the page or which I would recommend, remove the auth barrier in your test environment.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by kimek** [comment]
Copy of https://github.com/webdriverio/webdriverio/issues/837

**Comment by siddharthmittal97** [comment]
@christian-bromann I am surprised webdriverIo does not handle such cases

Alert
Prompt 

are basic things now

**Comment by christian-bromann** [comment]
> I am surprised webdriverIo does not handle such cases

WebdriverIO does handle Alerts and Prompts. The issue is about handling authentification popups which were not possible to automate through WebDriver but likely to be possible with WebDriver Bidi. Note that WebdriverIO depends on the WebDriver automation protocol to provide this feature in a reliable cross browser way.
