### ISSUE TITLE
how to pass arguments to firefox browser

### ISSUE THREAD

**Issue by huzjakd** [webdriverio/webdriverio#1659]
This is how i start the test:
`spawn('node', ['wdiotests/my_test.js']);`

This is what I have in the test:
```
var browsers = webdriverio.multiremote({
    myFirefoxBrowser: {
        desiredCapabilities: {
            browserName: 'firefox',
			resolution : '1024x768'
        },
		logLevel: 'silent'
    },
	myChromeBrowser: {
        desiredCapabilities: {
            browserName: 'chrome'
        },
		logLevel: 'silent'
    },

});
var browser = browsers.select('myFirefoxBrowser');
```

Now is there way to pass an argument to the firefox browser? Like you would with chrome:
```
capabilities: [{
    browserName: 'chrome',
    chromeOptions: {
        args: ['disable-web-security']
    }
}]
```

So something like:
```
    myFirefoxBrowser: {
        desiredCapabilities: {
            browserName: 'firefox',
			resolution : '1024x768',
        args: ['disable-web-security']
        },
		logLevel: 'silent'
    },
```

**Comment by christian-bromann** [comment]
@huzjakd there is [firefox-profile](https://www.npmjs.com/package/firefox-profile) to do that. If you would use the wdio testrunner (which also allows multiremote testing) then you can easily use our [firefox-profile service](https://www.npmjs.com/package/wdio-firefox-profile-service). 

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
