### ISSUE TITLE
Multi Remote with android/ios and chrome dont work

### ISSUE THREAD

**Issue by Templum** [webdriverio/webdriverio#1661]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to WebdriverIO). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, join the Gitter chat room ([![Gitter](https://badges.gitter.im/Join Chat.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge))!

I set up the wdio.conf.js for multi remote as described in the [docs](http://webdriver.io/guide/usage/multiremote.html). Both appium and selenium are running on my local device. Selenium on port 4444 and Appium at port 4437. When I execute the test appium doesnt receive any request. Instead selenium answers the request, with the error you can see below.

## Environment

* WebdriverIO version: 4.2.16
* Selenium version: 3.0.0
* Appium version: 1.6.0-beta3
* Node.js version: 4.6.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable): [wdio-appium-service](https://www.npmjs.com/package/wdio-appium-service) @0.2.2

## Details

If you remove either the web part or the android part. And comment out the effected lines in the test. It will run without an error. One thing i noticed is that I must set the port for appium to work on the outer layer of the config object and not within the desired capabilities. As you can see below:

```javascript
exports.config = {
    port: 4723, //This got recognized
    capabilities: {
        webClient: {
            desiredCapabilities: {
                maxInstances: 1,
                browserName: 'chrome',
                port: 4444
            }
        },

        androidClient: {
            desiredCapabilities: {
                browserName: 'android',
                appiumVersion: '1.5.3',
                platformName: 'android',
                platformVersion: '4.4',
                deviceName: 'emulator-5554',
                orientation: 'PORTRAIT',
                port: 4723, //this alone seem not to get recognized
                appiumVersion: '1.6.0-beta3',
                app: APP_PATH
            }
        }
    },
    services: ['appium'],
    appium: {
        args: {
            address: '127.0.0.1',
            commandTimeout: '7200',
            sessionOverride: true,
            debugLogSpacing: true,
            platformVersion: '4.4',
            platformName: 'android',
            deviceName: 'emulator-5554',
            nativeInstrumentsLib: true,
            isolateSimDevice: true,
            app: APP_PATH
        }
    }
}

```

## Link to Selenium/WebdriverIO logs

```sh
ERROR: The best matching driver provider org.openqa.selenium.safari.SafariDriver can't create a new driver instance for Capabilities [{app=.../multi-remote-android-web/sample-apk/app-debug.apk, rotatable=true, orientation=PORTRAIT, appiumVersion=1.6.0-beta3, handlesAlerts=true, deviceName=emulator-5554,
 requestOrigins={name=webdriverio, version=4.2.16, url=http://webdriver.io}, port=4723, platformVersion=4.4, locationContextEnabled=true, browserName=android, jav
ascriptEnabled=true, platformName=android}] 

```

## Code To Reproduce Issue [ Good To Have ]

[This is a little show case, but only for android. But the problem also effects ios.](https://github.com/Templum/multi-remote-android-web)

**Comment by christian-bromann** [comment]
can you try this config:
```js
exports.config = {
    capabilities: {
        webClient: {
            desiredCapabilities: {
                maxInstances: 1,
                browserName: 'chrome',
                port: 4444
            }
        },

        androidClient: {
            port: 4723,
            desiredCapabilities: {
                browserName: 'android',
                appiumVersion: '1.5.3',
                platformName: 'android',
                platformVersion: '4.4',
                deviceName: 'emulator-5554',
                orientation: 'PORTRAIT',
                appiumVersion: '1.6.0-beta3',
                app: APP_PATH
            }
        }
    },
    services: ['appium'],
    appium: {
        args: {
            address: '127.0.0.1',
            commandTimeout: '7200',
            sessionOverride: true,
            debugLogSpacing: true,
            platformVersion: '4.4',
            platformName: 'android',
            deviceName: 'emulator-5554',
            nativeInstrumentsLib: true,
            isolateSimDevice: true,
            app: APP_PATH
        }
    }
}
```

**Comment by christian-bromann** [comment]
Ok, closing this because I am pretty sure the config above works. Let me know if it doesn't.

**Comment by Templum** [comment]
Indeed moving the port out of the desiredCapabilities did work. Maybe docs could need some enhancement.
