### ISSUE TITLE
Screenshot making with webdriver 

### ISSUE THREAD

**Issue by AngeIII** [webdriverio/webdriverio#1662]
Is there any example how to make visual regression testing with screenshots?

As I understand I need to integrate some framework into webdriver and then run, what about native behaviour?

**Comment by christian-bromann** [comment]
Please see http://blog.kevinlamping.com/whats-up-with-webdrivercss/ or check out https://learn.visualregressiontesting.com. Feel free to join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by AngeIII** [comment]
Thanks Christian! Gitter is good idea.
