### ISSUE TITLE
Cannot chain .clearElement() function

### ISSUE THREAD

**Issue by delijah** [webdriverio/webdriverio#1663]
## The problem

Cannot chain .clearElement() function.

## Environment

* WebdriverIO version: 4.2.16
* Node.js version: 6.7.0
* synchronous wdio testrunner

## Details

It is possible to chain .click() or .keys() functions, but not the .clearElement() function. I get the following error:

`Failed: selector needs to be typeof 'string'`

## Code To Reproduce Issue

Works:

```
browser.element('#myInputField')
    .click()
    .keys('test');
```

Does not work:

```
browser.element('#myInputField')
    .click()
    .clearElement()
    .keys('test');
```

**Comment by christian-bromann** [comment]
@delijah if you want to set a value to an input element use `setValue`. 
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by ckm2k1** [comment]
@christian-bromann We've run into this issue as well. It's very common to select an element with $(selector), then run .click().clearElement(). Currently this flow doesn't work. Is there any reason that shouldn't work?

**Comment by christian-bromann** [comment]
@ckm2k1 the following flow sure won't work
```js
$(selector).click().clearElement();
```
However this should:
```js
var elem = $(selector);
elem.click();
elem.clearElement();
```
The click command doesn't return any information on the element it was executed on.
