### ISSUE TITLE
Looping through commands

### ISSUE THREAD

**Issue by jharrowmortelliti** [webdriverio/webdriverio#1668]
I am trying to loop through an array of commands.
I tried to copy the solution this issue:  #1043
Right now it is hitting the selection action before going to bing.
```
const browser = require('./browser.js')
const cheerio = require('cheerio')
const q = require('q')

const testData = [
  {action: 'goToUrl', target: 'www.bing.com'},
  {action: 'doText', target: '#sb_form_q',  textInput: 'hi'}
]

let readyTasks = []

const doTasks  = (tasks) => {

  let index=0

  browser.init()
    .then(() => {
      tasks.forEach((task) => { 
        if (task.action==='goToUrl')
          readyTasks.push(browser.url(task.target).pause(5000))
        if (task.action==='doClick')
          readyTasks.push(browser.click(task.target).pause(5000))
        if (task.action==='doText')
          readyTasks.push(browser.setValue(task.target, task.textInput).pause(5000))
      })
      return q.all(readyTasks)
    }).end()
    .then(() => {
      console.log("complete")
    })
}

doTasks(testData)
```

**Comment by christian-bromann** [comment]
Running through the forEach loop and calling all commands at the same time doesn't work. Make sure you call url first and then the next one. It is important that commands are getting executed in order and that the next commands is not executed until the previous has finished. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
