### ISSUE TITLE
Looping through table rows not working

### ISSUE THREAD

**Issue by aqiqul** [webdriverio/webdriverio#1669]
## The problem

Can't get to table elements, the selenium log says it got the table element, but does not move into the function for looping through the rows.

## Environment

* WebdriverIO version:
* Node.js version:
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Details

Can't simply  loop into an html table to get to rows and cell values

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]
Tried this code : does not go beyond found element : table
```js
browser.element('//*[@id="wpbody-content"]/div[3]/form/table', function(table){
			//browser.pause(10000);
			console.log("456 " +table );
			table.element('#the-list',function(tbody){
				tbody.elements('//*[@id="wpbody-content"]/div[3]/form/table/thead/tr', function(rows){
					for(i=0; i<rows.length;i++)
					{
						rows[i].elements('//*[@id="cb"]', function(cols){
							console.log(getText(cols2[i]));
							//expect(cols[2].getText()).toMatch('ok');
						});
					}
				});
			}); 
		});
```

then tried belwo  same result nothign after getting table element
```js
browser.element('//*[@id="wpbody-content"]/div[3]/form/table', function(table){
			console.log("#of table : ");
			var table_row =[];
			table_row=browser.elements('//*[@id="wpbody-content"]/div[3]/form/table/thead/tr');
			console.log("#of rows : "+table_row.length);
		}); 
```
Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
First of all: please format your code properly so people can read the code (I just did that for you). Second please use the issue template and fill out all information so we know how you use WebdriverIO. Last: this is not an issue, please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions.

To answer the issue: you are using the API wrong. WebdriverIO doesn't support callbacks like this. There are a lot of examples on the website and on the internet.

**Comment by aqiqul** [comment]
its so funny all you do is close peoples issues and not answer them, pointing to gitter chat where no one answers, really thinking if I made a mistake using webdriverio

**Comment by christian-bromann** [comment]
Sorry to disappoint you but this is an open source project. We help people out on Gitter in our free time! The way how you posted the code and the code you posted itself makes me thing you haven't really worked with WebdriverIO at all and it is not really my job to consult everyone. I like to give hints and help pointing out directions but not solving the whole problem for others.

**Comment by aqiqul** [comment]
True just started using famous webdriverio open source. And how would one know with the fantastic webdriverio document where I can become a master of webdriverio perhaps.

**Comment by christian-bromann** [comment]
We even have an online course 😉  : http://learn.webdriver.io/
Yes it costs money but this is because the originator also spend his valueable time to create it.

**Comment by neoadventist** [comment]
@christian-bromann I agree with @aqiqul that it just sucks having to go to another platform to find an answer to a question.  If everything could be in Github then it would make finding the answer a whole lot more effective. 

@aqiqul do you know how I can get the text off of this? 
```
         .$$('#dc> table > tbody > tr').then(function(rows){
                   console.log(rows[0]);
                   var x = client.element(rows[0].value).getText();
                   x.then(function(val){
                           console.log(val);
                   });
                   return x;
           })
```

`rows.length` returns 631 (a big table) 
`rows[0]` shows this: 
```
{ ELEMENT: '11',
  value: { ELEMENT: '11' },
  selector: '#d > table > tbody > tr',
  index: 0 }
```

Any idea on how to get the text of this element?

**Comment by christian-bromann** [comment]
@neoadventist if you would use the wido testrunner you could do this:
```js
var trs = $$('#d > table > tbody > tr')
console.log(trs[0].getText())
```
