### ISSUE TITLE
[Feature Request] Support wrapping of elements in the value array with prototype methods

### ISSUE THREAD

**Issue by gregorskii** [webdriverio/webdriverio#1672]
## The problem

When querying for elements via `client.elements()` in sync mode the response includes a WebDriver JSON object that contains a field `values` as an array. Each element of this array does not have the prototype methods .click .isVisible etc. There is also no way to query the DOM for the original WebDriver JSON element via the ID returned by the elements call.
## Environment
- WebdriverIO version: https://github.com/xolvio/sync-webdriverio v5.1.0
- Node.js version: 6.5.0
- Standalone mode, I believe
## Details

When querying the DOM for elements through a selector the Webdriver JSON Object returned includes an array in its values field:

```
{ sessionId: '4a8763ec-9c6e-42c1-90a9-e64a2508c0d6',
  state: 'success',
  value: [ { ELEMENT: '204' } ],
  class: 'org.openqa.selenium.remote.Response',
  hCode: 886205991,
  selector: 'SELECTOR',
  _status: 0 }
```

There is not currently a way to use the prototype methods .click(), .element(), .elements() etc directly with a single item in the array. The docs state that these prototype methods will apply to the first element in the array, an example of which is [click](http://webdriver.io/api/action/click.html):

```
element to click on. If it matches with more than one DOM-element it automatically clicks on the first element
```

There are convenience methods to do these actions against an ELEMENT ID in the DOM via the `elementIDMETHOD` functions ex [click](http://webdriver.io/api/protocol/elementIdClick.html). 

However under certain use cases it would be helpful to have the ability to have the prototype methods applied to each element in the array, or to be able to query the DOM by ID and get the prototype methods.

An example use case of this would be in a map method after a elements query:

Direct form:

```
const items = this.instance.elements('SELECTOR');

return items.value.each((element) => {
   element.elements('a').isVisible();
  // ... any other actions against this element
});
```

Function form:

```
const items = this.instance.elements('SELECTOR');

return items.value.map((webJSONElement) => {
  return webJSONElement.ELEMENT;
}).each((id) => {
  const element = client.elementID(id);
  element.elements('a').isVisible();
  // ... any other actions against this element
});
```

This functionality is being used primarily with [ChimpJS](https://github.com/xolvio/chimp) which uses a sync form of Webdriverio, or forces it to be sync.

**Comment by christian-bromann** [comment]
> This functionality is being used primarily with ChimpJS which uses a sync form of Webdriverio, or forces it to be sync.

Even though Chimpjs uses some functions from wdio-sync I can't promise that it will be supported there as well.

**Comment by gregorskii** [comment]
Will the feature be available in wd-sync? I can work with the developers of chimp to pull it in.

**Comment by gregorskii** [comment]
Also let me know if there is anything I can do to work on this. Happy to work on a PR if I know where to look and tips on implementing it.

Thanks!

**Comment by christian-bromann** [comment]
> Will the feature be available in wd-sync?

Yes, in fact it will affect the method that is consumed by chimp.

All magic happen when the [result object](https://github.com/webdriverio/wdio-sync/blob/master/index.js#L221) gets overloaded by [applyPrototype](https://github.com/webdriverio/wdio-sync/blob/master/index.js#L247) in [wdio-sync](https://github.com/webdriverio/wdio-sync).

Actually let's move this into the wdio-sync project since most of the implementation has to been made there.

**Comment by christian-bromann** [comment]
This issue was moved to webdriverio/wdio-sync#40

**Comment by gregorskii** [comment]
Ok thank you
