### ISSUE TITLE
TestRunner/Mocha/Sync with this.skip() is failing.

### ISSUE THREAD

**Issue by mullanaphy** [webdriverio/webdriverio#1675]
## The problem

Using this.skip() with the test runner fails with `Cannot read property 'split' of undefined`.
## Environment
- WebdriverIO version: 4.2.16
- Node.js version: 6.6.0
- [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): testrunner
- if wdio testrunner, running synchronous or asynchronous tests: synchronous
- Additional wdio packages used (if applicable): none
## Details

Pretty sure it's line: https://github.com/webdriverio/wdio-sync/blob/master/index.js#L456 which is expecting an Error.stack. Not sure how that gets passed in for a this.skip() though.
## Link to Selenium/WebdriverIO logs

```
TypeError: Cannot read property 'split' of undefined
    at /path/to/project/node_modules/wdio-sync/build/index.js:672:30
    at Context.executeSync (/path/to/project/node_modules/wdio-sync/build/index.js:663:12)
    at /path/to/project/node_modules/wdio-sync/build/index.js:889:34
```
## Code To Reproduce Issue [ Good To Have ]

```
describe('Test', function() {
  it('Skip', function() {
    this.skip();
  });
});
```

Then run `./node_modules/.bin/wdio wdio.conf.js` where wdio.conf.js is a basic mocha configuration with bdd and using a local Firefox.

**Comment by mullanaphy** [comment]
Currently doing:

```
if (someReasonToSkip) {
  console.warn('Skipping because of something');
  return;
}
```

Which marks a test as Passing although ideally it would be Pending with the reason mentioned.

**Comment by Henne2806** [comment]
I've got the same problem with this.skip()...

**Comment by christian-bromann** [comment]
`this.skip()` is available with MochaJS v3 which is was not supported with the the wdio framework adapter. Please update your `wdio-mocha-framework` package to `v0.5.0`.
