### ISSUE TITLE
Errors from 3rd party reporters

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1676]
``` js
{
    reporters: ['json', 'spec', 'junit', 'allure'],

    reporterOptions: {
        outputDir: './cache/reports',

        allure: {
            outputDir: './cache/reports/allure-results'
        }
    }
}
```

``` js
let launcher = new WebDriverIO.Launcher(runner.file, runner.data);

return launcher.run()
     .catch(console.log);
```

```
Error: ENOTEMPTY: directory not empty, rmdir 'cache/reports/allure-results' 
```

I don't understand why WebdriverIO fails when 3rd party reporters throw any error

**Comment by christian-bromann** [comment]
> I don't understand why WebdriverIO fails when 3rd party reporters throw any error

Why do you assume that this error comes from the allure reporter? The reporter doesn't remove any directories. Without any further information I can't tell where this comes from.

**Comment by monolithed** [comment]
> Why do you assume that this error comes from the allure reporter?

I have no any idea, but I see these errors in my logs. In my case It depends on Allure reporter. 
it can be assumed, that problem [here](https://github.com/allure-framework/allure-js-commons/blob/df6fbc44ee597bba4c94e9cc8795db45e063a4c3/writer.js#L9)

**Comment by monolithed** [comment]
> Without any further information I can't tell where this comes from.

I see what you mean. But my guess is that reporters should be wrapped by `try / catch`

**Comment by christian-bromann** [comment]
Well if I would know where this error comes from I can probably do that 😉
