### ISSUE TITLE
Connecting to Cloud Service Broken with v4.3.0

### ISSUE THREAD

**Issue by ChadKillingsworth** [webdriverio/webdriverio#1683]
With the v4.3.0 release, our sauce labs tests completely quit working. The selenium server never connects. We've downgraded to 4.2.16 for the time being.

I'm putting this here as a placeholder for now. I'm going to try tomorrow to use git bisect to tell me which commit caused the problem.

**Comment by christian-bromann** [comment]
@ChadKillingsworth can you provide more information? Are you using Sauce Connect?

**Comment by ChadKillingsworth** [comment]
Yes we use sauce connect. The tunnel is started externally and we pass the tunnel ID to the configuration.

git bisect identifies this as the offending commit: 9ce7f7bb508fb2bb47071c11bbb8b76ff743f0f5

**Comment by ChadKillingsworth** [comment]
```js
return {
    protocol: 'https',
    host: 'ondemand.saucelabs.com',
    port: 80
}
```

https on port 80 looks mighty suspicious.

**Comment by christian-bromann** [comment]
https://github.com/webdriverio/webdriverio/blob/master/lib/helpers/detectSeleniumBackend.js#L41-L46

**Comment by christian-bromann** [comment]
if you use sauce connect please set `"protocol": "http"`. I will make sure that we get back to port 80 when sauce connect is running

**Comment by ChadKillingsworth** [comment]
I saw that just after I posted it.

Switching back to `protocol: "http"` and `port: 80` works. I'm researching to see why saucelabs isn't connecting with https.

**Comment by ChadKillingsworth** [comment]
>  I will make sure that we get back to port 80 when sauce connect is running

I'll leave it to you then. I've found no other way around this so far.

**Comment by christian-bromann** [comment]
No worries, I will push out a fix for that tomorrow.

**Comment by christian-bromann** [comment]
Please update `wdio-sauce-service` to `v0.3.1` and `webdriverio` to `v4.5.0` (when released)
