### ISSUE TITLE
[Typescript] type definition doesn’t differentiate between sync and async mode

### ISSUE THREAD

**Issue by Burgi0101** [webdriverio/webdriverio#1686]
**Example**
When using Typescript with WebdriverIO it seems like the type definition doesn't differentiate between sync and async mode and treats everything async. 

For example the following code snippet shows a method that should get a text given a locator and afterwards return the text. As we expect to get back a text we define the method to be typeof string.

    getItemFromTable(item: string): string {
            return browser.getText(item);
    }

**Issue**

No we face the problem, the method won't work like this as it's treated asynchronous and we do not get back a string yet but instead we get:

`WebdriverIO.Client<string | string[]>`

So it seems like the type definitions don't differtiate between both modes and treat everything asynchronously.

## Environment
Using typings from:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/webdriverio
* WebdriverIO version: 4.2.3
* Node.js version: 3.10.8
* Standalone mode or wdio testrunner: wdio testrunner
* Tests: Synchronous
* Additional wdio packages used: 

>     "wdio-allure-reporter": ">=0.1.1",
>     "wdio-jasmine-framework": "^0.2.5",
>     "wdio-json-reporter": ">=0.0.3",
>     "wdio-junit-reporter": ">=0.1.0",
>     "wdio-selenium-standalone-service": ">=0.0.5",
>     "wdio-spec-reporter": ">=0.0.2",
>     "wdio-teamcity-reporter": "^1.0.2"

**Comment by christian-bromann** [comment]
@Burgi0101 our type definitions just got an update, can you re-check?

**Comment by timbru31** [comment]
Again this is solved by adding support for intersection types in the PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14945

**Comment by christian-bromann** [comment]
Thanks @timbru31
