### ISSUE TITLE
Could not proxy command to remote server

### ISSUE THREAD

**Issue by echonox** [webdriverio/webdriverio#1691]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to WebdriverIO). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, join the Gitter chat room ([![Gitter](https://badges.gitter.im/Join Chat.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge))!

## Environment

* WebdriverIO version: 4.3.0
* Node.js version: 6.9.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable):
"appium": "^*",
    "chai": "^*",
    "cucumber": "^*",
    "wdio-appium-service": "^*",
    "wdio-cucumber-framework": "^*",
    "wdio-selenium-standalone-service": "*",
    "webdriverio": "^*"

## Details

I am using WDIO with CucumberJS and Appium when running the test case it runs fine (filing inputs, clicking buttons, getting text and etc) until it reaches to the point where it does http request to backend (login call) and the test crashes with this error:

An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: socket hang up

## Link to Selenium/WebdriverIO logs

wdio.conf.js:

https://gist.github.com/echonox/bc20b72207c21805e9f5010f6d7c357e

appium.log:

https://gist.github.com/echonox/0189281689819a1c2b669cf39e97fa89

package.json:

https://gist.github.com/echonox/a0e2d5e74f4e30281cc4fa52f8f8b5d6

**Comment by christian-bromann** [comment]
It seemed to fail after an attempt to click on an element:
```
[JSONWP Proxy] Proxying [POST /wd/hub/session/f0108c2c-45dd-4e60-8d85-8f8892898382/element/:wdc:1478441596204/click] to [POST http://localhost:8080/wd/hub/session/45121cb8-8f3e-4359-6bb6-aa05a375bc52/element/:wdc:1478441596204/click] with body: {}
[MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: socket hang up
    at doJwpProxy$ (lib/mjsonwp/mjsonwp.js:340:13)
```
This is not a WebdriverIO issue. Please fill this issue in the Appium project.
