### ISSUE TITLE
Issue with skipping particular describe in webdriverio  !

### ISSUE THREAD

**Issue by sasank26** [webdriverio/webdriverio#1692]
I am trying to skip an jasmine describe in webdriverio using "xdescribe" but while running the code, that describe is not being skipped .Thus failing all my remaining describes and specs .i have recently installed webdriver latest version through npm. Before this i was using webdriverio v4.2.16 and its working well.
And i tried reverting back to v4.2.16 .But still "xdescribe"  is not working .

**Comment by christian-bromann** [comment]
Can't reproduce with latest wdio-jasmine-framework and latest WebdriverIO:

__wdio.conf.js__
```js
exports.config = {
    specs: ['test.js'],
    capabilities: [{ browserName: 'phantomjs' }],
    framework: 'jasmine',
    reporters: ['dot']
}
```
__test.js__
```js
describe('test', () => {
  it('should pass', () => {
    expect(1).toBe(1)
  })

  xdescribe('test again', () => {
    it('should not run', () => {
      expect(1).toBe(2)
    })
  })
})
```
__output:__
$ ./node_modules/.bin/wdio wdio.conf.js

․․

1 passing (2.70s)
1 pending
```
