### ISSUE TITLE
'beforeSuite' hook doesn't work with mocha's dynamically testing feature

### ISSUE THREAD

**Issue by dfleer100** [webdriverio/webdriverio#1697]
## The problem

I'm using webdriverio together with mocha's dynamically testing feature (it's simply a loop over an array). I expected that the 'beforeSuite' hook is called one per loop, but obviously this isn't the case.

## Environment

* 4.4.0
* 6.9.1 LTS
* wdio testrunner
* synchronous tests

## Link to Selenium/WebdriverIO logs

https://gist.github.com/dfleer100/8be199b4c0c49bfea311a2ecb8432411#file-console-output

## Code To Reproduce Issue [ Good To Have ]

```
const tests = [
    { key: 'test1', url: 'http://www.google.de' },
    { key: 'test2', url: 'http://www.google.de' },
    { key: 'test3', url: 'http://www.google.de' }
]

tests.forEach((test, index) => {
    describe(test.key, () => {
        it('browser url', () => {
            browser.url(test.url)
        })
    })
})
```

If you need more information, feel free to contact me.

**Comment by christian-bromann** [comment]
As discussed on [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) please set the hooks within your spec files.
