### ISSUE TITLE
.chooseFile works with Chrome but not with Safari

### ISSUE THREAD

**Issue by vin1391** [webdriverio/webdriverio#1699]
Hi,

The .chooseFile function seems to work in chrome but not with safari. When I use the command, it sends the file location [Seen from selenium logs], then thats it. The testcase finishes up and no failure is thrown either.

Also for my case there is no textbox to fill the file path with. Only the choose file option is present. So I cannot upload the file in that way.

On searching for possible solutions I found that it may be an issue with Safari [https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/4220].

Is there some workaround for this which we can do via WebDriverIO?

Using:
node v4.5.0
Jasmine v2.5.2
Safari Version 10.0
Mac OSX

Thanks,
Vin

**Comment by christian-bromann** [comment]
Hey @vin1391 
unfortunately not. WebdriverIO can only support what the driver supports.

Cheers
