### ISSUE TITLE
isVisible() is not returning a result when the element is not visible

### ISSUE THREAD

**Issue by krobertson92** [webdriverio/webdriverio#1701]
## The problem

isVisible() is not returning a result when the element is not visible when you are operating on browser.element.
This also causes allure report generation to fail.

## Environment

* WebdriverIO version: 4.4.0
* Node.js version: v6.9.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): wdio-mocha-framework, wdio-allure-reporter

## Details

```
var elem = browser.element('//div[@id="search-layer-selector"]/div[2]')
if(!elem.isVisible()){
  //do something
}
```
**In the case where elem IS visible (works as expected)**: 
With verbose logging turned on, the above results in a COMMAND line followed by a DATA line followed by a RESULT line:
```
[14:16:39]  COMMAND	POST 	 "/wd/hub/session/e28a716e-ae88-4ea8-a1f2-961d073bc289/element"
[14:16:39]  DATA		{"using":"xpath","value":"//div[@id=\"search-layer-selector\"]/div[2]"}
[14:16:39]  RESULT		{"ELEMENT":"4"}
[14:16:39]  COMMAND	GET 	 "/wd/hub/session/e28a716e-ae88-4ea8-a1f2-961d073bc289/element/4/displayed"
[14:16:39]  DATA		{}
[14:16:39]  RESULT		true
```

**In the case where elem is NOT visible (not as expected- missing RESULT)**: 
With verbose logging turned on, the above results in a COMMAND line followed by a DATA line but no 
RESULT line:
```
[14:20:18]  COMMAND	POST 	 "/wd/hub/session/4ca5c595-9791-45ff-a8c2-ad34ac9aa16a/element"
[14:20:18]  DATA		{"using":"xpath","value":"//div[@id=\"search-layer-selector\"]/div[2]"}
[14:20:18]  COMMAND	POST 	 "/wd/hub/session/4ca5c595-9791-45ff-a8c2-ad34ac9aa16a/elements"
[14:20:18]  DATA		{"using":"xpath","value":"//div[@id=\"search-layer-selector\"]/div[2]"}
[14:20:18]  RESULT		[]
```

If I do this instead, it works correctly:
```
if(!browser.isVisible('//div[@id="search-layer-selector"]/div[2]')){
    // do something
}
```

In the case where it doesn't work correctly, I get the following error when I try to create the allure report:
Exception in thread "main" java.lang.NumberFormatException: For input string: ""

## Link to Selenium/WebdriverIO logs

https://gist.github.com/krobertson92/fbcee0e05f6027adfaba65ab0290bb27

## Code To Reproduce Issue [ Good To Have ]
assuming elem is not visible:
```
var elem = browser.element('//div[@id="search-layer-selector"]/div[2]')
if(!elem.isVisible()){
  //do something
}
```

**Comment by christian-bromann** [comment]
Your element doesn't seem to exist. The browser.element call should throw.

**Comment by krobertson92** [comment]
Oh that would make sense... My bad

**Comment by christian-bromann** [comment]
@krobertson92 also I would recommend to use the `$` and `$$` shortcuts to fetch elements. E.g.
```js
var expect = require('chai').expect;
describe('webdriver.io api page', function() {
    it('should be able to filter for commands', function () {
        browser.url('http://webdriver.io/api.html');
        // filtering property commands
        $('.searchbar input').setValue('getT');
        // get all results that are displayed
        var results = $$('.commands.property a').filter(function (link) {
            return link.isVisible();
        });
        // assert number of results
        expect(results.length).to.be.equal(3);
        // check out second result
        results[1].click();
        expect($('.doc h1').getText()).to.be.equal('GETTEXT');
    });
});
```

**Comment by krobertson92** [comment]
@christian-bromann very helpful, thank you!

**Comment by michal-boruczkowski** [comment]
> Your element doesn't seem to exist. The browser.element call should throw.

There might be a problem with this actually...

Each invocation of `isVisible` throws Selenium error in the log when element does not exist (which is ok I guess) but wdio ignores this silently and just returns `false` (which is also great if you ask me). The problem is that this information is stored in the internal report along with the Selenium original screenshot. So every time you use `isVisible` on non existing element you get another screenshot in the memory.

In the end you get this:
`FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`

Check memory dump screenshot:
![image](https://user-images.githubusercontent.com/29930780/28968660-74fa059e-7921-11e7-9a1e-4aa7de26fc26.png)

Each test have like 6-8 of those screenshots in my (case ~50 MB in memory)
