### ISSUE TITLE
waitForVisible broken after a waitUntil

### ISSUE THREAD

**Issue by khirakawa** [webdriverio/webdriverio#1702]
## The problem

```
describe('waitForVisible', () => {
  it('should work', () => {
    browser.url('https://google.com');

    browser.waitUntil(() => {
      return browser.element('#viewport');
    });

    browser.waitForVisible('#main');  // This results in a `null` selector instead of `#main`
  });
});
```

In the above test, I expect `browser.waitForVisible` to use `#main` as the selector.  However, it uses `null`.

## Environment

* WebdriverIO version: 4.2.26
* Node.js version: 4.3.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): test runner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable):

## Details

From what I can tell, the offending code is [here](https://github.com/webdriverio/webdriverio/blob/master/lib/webdriverio.js#L331-L339).

When `browser.waitForVisible` is run,

- `this.lastResult` is:

  ```
  { state: 'success',
    sessionId: 'ba387ccb-d09f-4132-bf83-10c92047a28c',
    hCode: 1114222073,
    value: { ELEMENT: '0' },
    class: 'org.openqa.selenium.remote.Response',
    selector: '#viewport',
    _status: 0 }
  ```

- `args.length` is 1 (`#main`)
- `func.length` is 3 (`selector`, `ms`, `reverse`) as coded [here](https://github.com/webdriverio/webdriverio/blob/master/lib/commands/waitForVisible.js#L38)

Which makes [this line](https://github.com/webdriverio/webdriverio/blob/master/lib/webdriverio.js#L332) true.

It then proceeds to unshift the arguments with `null` [here](https://github.com/webdriverio/webdriverio/blob/master/lib/webdriverio.js#L337), ultimately calling `safeExecute(func, args)` with an `args` of `[null, '#main']`.

This has the unintended consequence of calling `waitForVisible` with a `null` selector and `#main` for `ms`.  The `waitForVisible` method has [this check](https://github.com/webdriverio/webdriverio/blob/master/lib/commands/waitForVisible.js#L53) to make sure `ms` is a number, thus hiding the issue.

## Link to Selenium/WebdriverIO logs

https://gist.github.com/khirakawa/b5aad411f4c173ff2ce31becfe0717bb

## Code To Reproduce Issue [ Good To Have ]

Please see above

**Comment by christian-bromann** [comment]
@khirakawa you should not return the result of an element command. What do you want to achieve here? Use waitforexist to wait until the element shows up. However this is still a bug because lastResult should not be propagated after a wait command.

**Comment by christian-bromann** [comment]
It seems that any element call within waitUntil gets propagated to following command calls, no matter if a element result is returned or not:
```js
  it('should show it', function () {
      browser.url('https://google.com');
      browser.waitUntil(() => {
        browser.element('#viewport');
        browser.getUrl();
      });
      console.log(browser.getTagName()); // should fail but does not
  })
```

**Comment by khirakawa** [comment]
> you should not return the result of an element command. What do you want to achieve here?

@christian-bromann Apologies, that test was quickly written to reproduce the error.  The actual tests we have don't return `element` in `waitUntil`

**Comment by christian-bromann** [comment]
@khirakawa no worries, as I mentioned above it didn't matter whether or not the element was returned. I applied a fix in wdio-sync and currently updating the framework adapters. Please update them to get the bugfix. Thanks for reporting this!

**Comment by christian-bromann** [comment]
Ok, applied fix to all framework adapters.
