### ISSUE TITLE
Scripts with XMLHttpRequest does not seem to be working

### ISSUE THREAD

**Issue by shyamul** [webdriverio/webdriverio#1704]
## The problem

I'm writing tests which include some API requests.

When I run the js script on it's own, it works fine. However, when I run the script using wdio testrunner a successful request does not seem to get generated. 

As a simple example I tried compiling the following code

```sh
            var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;

            var xhr = new XMLHttpRequest();
            xhr.onreadystatechange = function() {
                if (this.readyState == 4 && this.status == 200) {
                   console.log(xhr.status)
                } else {
                   console.log('Error! ' + xhr.status)
                }
            }
            xhr.open('GET', 'http://example.com', true);
            xhr.send(null);
```
This eventually yielded a **_200_** response when I run the js script without wdio...

But when I run this same code from the terminal using 'wdio wdio.conf.js' line, I get **_Error!_ 0** output instead.

## Environment

* WebdriverIO version: 4.2.3
* Node.js version: 5.0.0
* wdio testrunner (synchronous)

**Comment by shyamul** [comment]
Ok, after a certain duration of head bumping on a very solid surface, I've got to make it work in two ways:
* I turn the sync option to **false**
* I apply a callback function with a small delay

**Comment by christian-bromann** [comment]
Hey @shyamul,
you don't need to switch to async to do async 3rd party requests. You can simply use the call command:

```js
var request = require('require');

before(function () {
    browser.url('http://testsite.com');
    var response = browser.call(function () {
        return request.get("http://example.com");
    });

    // ...
});
```
I used the require package here which might be a little bit too big for just a simple request but it demonstrates the use case. See also http://webdriver.io/api/utility/call.html

**Comment by shyamul** [comment]
Thanks @christian-bromann, that's quite helpful!
