### ISSUE TITLE
Page is not open via url method

### ISSUE THREAD

**Issue by SamantaChinmoy** [webdriverio/webdriverio#1705]
## The problem

I want to open a page through url method. But page is not open and only browser is open. 

## Environment

* WebdriverIO version: 4.4.0
* Node.js version:6.8.1
* [Standalone mode]

## Details

**This problem is not arising in previous version(2.4.3) of webdriverio.**

## Code To Reproduce Issue
```js
var webdriverio = require('webdriverio'),
    client,
    driverOptions = {};
driverOptions = {
    desiredCapabilities: {
        browserName: 'chrome'
    }
};
client = webdriverio.remote(driverOptions);
client
    .init();
var fun = function() {
    client
        .url("http://www.google.com")
        .saveScreenshot("a.png")
        .end();
}
fun();
```

**Comment by christian-bromann** [comment]
You have a racing condition in there:
```js
var webdriverio = require('webdriverio'),
    client,
    driverOptions = {};
driverOptions = {
    desiredCapabilities: {
        browserName: 'chrome'
    }
};
client = webdriverio.remote(driverOptions);
client
    .init();
    .url("http://www.google.com")
    .saveScreenshot("a.png")
    .end();
```
Make sure you properly handle the promise of each command. I would recommend to use the wdio testrunner. It runs all commands synchronously, e.g.
```js
var expect = require('chai').expect;
describe('webdriver.io api page', function() {
    it('should be able to filter for commands', function () {
        browser.url('http://webdriver.io/api.html');
        // filtering property commands
        $('.searchbar input').setValue('getT');
        // get all results that are displayed
        var results = $$('.commands.property a').filter(function (link) {
            return link.isVisible();
        });
        // assert number of results
        expect(results.length).to.be.equal(3);
        // check out second result
        results[1].click();
        expect($('.doc h1').getText()).to.be.equal('GETTEXT');
    });
});
```
See the guide page at the bottom to get started: http://webdriver.io/guide.html. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by SamantaChinmoy** [comment]
But same implementation is working in the version (2.4.3) of webdriverio.

**Comment by christian-bromann** [comment]
Please update to the latest version (`v4.4.0`)
