### ISSUE TITLE
new Date() returns null on IE 11

### ISSUE THREAD

**Issue by nhuhai** [webdriverio/webdriverio#1709]
## The problem

```
describe('value of new Date() should not be null on IE 11', () => {
  it('should not return null', () => {
    browser.url('https://google.com');

    var result = browser.execute(() => {
      return new Date();
    });

    console.log(result.value); // output: null
  });
});
```
on:

```
Browser: IE 11 
OS: Windows 10 - version: 11.103
iedriverVersion: 2.53.1
```

## Environment

* WebdriverIO version: `4.2.16`
* Node.js version: `4.3.0`
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): test runner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): wdio-mocha-framework@0.5.4

## Link to Selenium/WebdriverIO logs
```
[12:00:16]  COMMAND    	POST   	 "/wd/hub/session/ca907a013eb74f0fa2091bcb0b454ff2/execute"
[12:00:16]  DATA       		{"script":"return (function () {\n          return new Date();\n        }).apply(null, arguments)","args":[]}
[12:00:17]  RESULT     		null
```

**Comment by christian-bromann** [comment]
This is not a bug in WebdriverIO. The edgedriver returned null, so WebdriverIO returns null as well. Not sure why.

**Comment by patthiel** [comment]
@nhuhai This is failing because the `execute` command is not implemented yet in Edgedriver. See https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/webdriver-commands/  for a list of the commands implemented and status on those remaining.

**Comment by christian-bromann** [comment]
Thanks for clarifying @patthiel

**Comment by nhuhai** [comment]
Thanks @patthiel and @christian-bromann!
