### ISSUE TITLE
No equivalent of findElements get Count, Expect to have a browser.elements(<Selector>).length

### ISSUE THREAD

**Issue by bpskishore** [webdriverio/webdriverio#1710]
## The problem

It is important to have an equivalent value of findElements to get count of all elements either from drop down or from grid etc.

## Environment

* WebdriverIO version: 4.x
* Node.js version:6.9.x
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Details

To make code simplify and use it if we could get count of all <li> under <ul> that would be great

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]
you can reporduce anywhere in any page which contains number of elements in dropdown, use facebook.com for example

**Comment by christian-bromann** [comment]
There is an example right on the startpage of webdriver.io:

```js
var expect = require('chai').expect;
describe('webdriver.io api page', function() {
    it('should be able to filter for commands', function () {
        browser.url('http://webdriver.io/api.html');
        // filtering property commands
        $('.searchbar input').setValue('getT');
        // get all results that are displayed
        var results = $$('.commands.property a').filter(function (link) {
            return link.isVisible();
        });
        // assert number of results
        expect(results.length).to.be.equal(3);
        // check out second result
        results[1].click();
        expect($('.doc h1').getText()).to.be.equal('GETTEXT');
    });
});
```

**Comment by anjunatl** [comment]
I was having trouble getting element counts with wdio and this solution worked for me. You don't even need the `.filter()` if you don't need it - `.length` still works on `$$()` just the same. Thanks!

**Comment by christian-bromann** [comment]
@anjunatl the filter function just demonstrates how you can count elements more specifically e.g. get number of visible elements

**Comment by alex-zaman-zocdoc** [comment]
FYI in case someone uses `browser.elements` instead of `$$` shortcut. You should use `browser.elements(selector).values.length` as using just `.length` will return undefined.

**Comment by deepikadixitb** [comment]
@alex-zaman-zocdoc : I think it's ```value``` instead of  ```values```.  So ```browser.elements(selector).value.length``` works for me.
