### ISSUE TITLE
WaitForExist not working as expected

### ISSUE THREAD

**Issue by kvnlnt** [webdriverio/webdriverio#1712]
# The problem

WaitForExist and other wait functions don't seem to work as you'd expect.

## Environment

* WebdriverIO version: ^4.4.0
* Node.js version: v5.0.0
* Standalone mode

## Details

I'm running webdriverio in standalone and using it with phantomjs (phantomjs-prebuilt) to test a static html page. The page attaches a class to the html tag upon reaching a certain state. I want to wait until that class has been attached before proceeding with reading the html of the page. 

## Code To Reproduce Issue
Here are simplified versions of my code

This works:

```
phantomjs
.run('--webdriver=4444')
.then(program => {
    webdriverio
        .remote(options)
        .init()
        .url('./tests.html')
        .getTitle().then(function (title) {
            console.log('Title was: ' + title);
            program.kill();
        })
        .end();
});
```
...and this doesn't...it hangs then outputs nothing.

```
phantomjs
.run('--webdriver=4444')
.then(program => {
    webdriverio
        .remote(options)
        .init()
        .url('./tests.html')
        .waitForExist('html.tests-completed')
        .getTitle().then(function (title) {
            console.log('Title was: ' + title);
            program.kill();
        })
        .end();
});
```

What's going on here?

**Comment by christian-bromann** [comment]
Without PhantomJS logs I can't say what's wrong here. Also you call asynchronous commands here and don't proper handle promises, here is how it should work:

```js
var client = webdriverio.remote(options)

phantomjs
.run('--webdriver=4444')
.then(program => {
    return client
        .init()
        .url('./tests.html')
        .waitForExist('html.tests-completed')
        .getTitle().then(function (title) {
            console.log('Title was: ' + title);
            program.kill();
        })
        .end();
})
```

If you want to build a sophisticated test suite I would recommend to use the wdio testrunner. You will find a lot of boilerplater projects on the website. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by kvnlnt** [comment]
@christian-bromann I just tried your example and it doesn't work - waitForExist doesn't work. Also, your "should work" example was the same as my example...so I'm confused about whether or not you looked at my examples???

I don't see how I'm not "handling promises correctly" either. Unless you were referring to the fact that I was missing a return statement – that however was merely lost in translation when I dummied down my code for the purposes of this ticket.

Additionally, I'm not using any of the test libraries promoted by the examples using the wdio testrunner. I have a unique case and would like to simply use webdriverio in standalone mode. 

Any chance you could open this ticket back up, it does seem legit.
