### ISSUE TITLE
Page objects cannot use `isExisting()` or `waitForExist()`

### ISSUE THREAD

**Issue by scottrippey** [webdriverio/webdriverio#1715]
## The problem
In my tests, I'm using page objects exclusively.  However, I have run into a serious issue with the `isExisting()` method, and its derivative `waitForExist()`.

For an element that doesn't exist, this will work:
```
var exists = browser.isExisting("zzzz"); 
// returns false
```
However, using the page object pattern (simplified here), this will not work:
```
var exists = browser.element("zzzz").isExisting();
// throws:
// Error: An element could not be located on the page using the given search parameters ("zzzz").
```

The same error is thrown whenever I use `waitForExist()` ... it pauses for the timeout, waiting for the element to exist, then throws the same "An element could not be located..." error above.

**Comment by scottrippey** [comment]
Wow, thanks for the fast response!
I updated my test to match yours, but was surprised to find it still failed.  I'm on version `4.4.0`, which is latest.
The only thing that might be different is that I'm not using "synchronous mode", I'm actually using Promises.  I'm not sure if that makes a difference, but I simplified my example to look sync even though it was async.
Here's how I'm actually reproducing the issue:
```
    return browser.url("https://google.com").then(() => {
      return browser.element('aaa').isExisting().then((exists) => {
        console.log(exists);
      });
    });
```

**Comment by scottrippey** [comment]
After debugging for a while, here's what I've found.
 `isExisting` essentially does  `this.elements(selector).length > 0`. 
So if I try `browser.element('aaa').elements()`, I get the same error (not an empty array).  I think `elements()` is looking for *descendants* of `element('aaa')`, so it fails on https://github.com/webdriverio/webdriverio/blob/master/lib/protocol/elements.js#L59

**Comment by christian-bromann** [comment]
@scottrippey we concentrated our recent efforts on sync browser testing so some of the feature might not be compatible in async mode yet. Why do you want to run it async?

**Comment by scottrippey** [comment]
My tests are running in Spectron (for an Electron app), and as far as I can determine, it only supports async mode.

**Comment by Bharadwaj108** [comment]
I eactly have the same issue I have to use spectron to test my electron app and I get the same problem I cant access any of the elements on the spectron app this is my code : 
```

var assert = require('assert');
var Application = require('spectron').Application
var should = require('chai').should();
spawn = require('child_process').spawn;
describe('Test Suite 1', function () {
    var runtimeVersion = '6.49.11.73';  // need to match the version of Runtime being tested
    var app, client, notificationButton, cpuInfoButton, cpuInfoExitButton;
    var timeout = 60000;
    this.timeout(timeout)
    beforeEach(function () {
        this.app = new Application({
            path: '/CorumDispense-win32-ia32/CorumDispense.exe'
        })

        return this.app.start()        
    })
    afterEach(function () {
        if (this.app && this.app.isRunning()) {
            return this.app.stop()            
        }
    })


    it('Login Dispense', function () {      
        this.app.client.isExisting('body').then(function (result) {
            console.log('Element  exists : ' + result);
            if (result) then
            {
                var txtControl = this.app.client.element('//*[@id="inputUsername3"]');
                var controlsize = txtControl.getElementSize();
                console.log('Element size : ' + controlsize);
            }
        })
    })
})
```

And this is the output

```
Test Name:	Test Suite 1 Login Dispense
Test Outcome:	Passed
Result StandardOutput:	
mocha.json options file not found. Using default values: { ui: 'tdd', reporter: 'tap', timeout: 2000 }
1..1
ok 1 Test Suite 1 Login Dispense
Element  exists : true
# tests 1
# pass 1
# fail 0

```


Can you please provide a solution for this issue as I am totally unable to access any of the page objects.

**Comment by scottrippey** [comment]
@Bharadwaj108 Sorry, it looks like your issue is not related.  You are not using `.element(selector).isExisting()`, and since your test is logging `Element exists: false`, it means the `isExisting` method is returning `false`.  In my example, `element(selector).isExisting()` is throwing an error (rejection).

**Comment by christian-bromann** [comment]
Ok after reviewing this issue again I am afraid I can't do anything here. According to the protocol Webdriver will throw an error if an element can't be found. I don't want to change that. If you want to check if an element exists, do this instead:

```js
    return browser.url("https://google.com").then(() => {
      return browser.isExisting('aaa').then((exists) => {
        console.log(exists);
      });
    });
```

**Comment by manhnt9** [comment]
Confirmed, `waitForExist` doesn't work in async mode. browser.isExisting works.

**Comment by mgrybyk** [comment]
This is v4 issue that is no longer supported, please stop spamming all the issues and raise a bug with a reproducible example in latest wdio v5 @manhnt9
