### ISSUE TITLE
Result event not emitted when requests are rejected

### ISSUE THREAD

**Issue by krobertson92** [webdriverio/webdriverio#1718]
## The problem

This 
```
it( 'test', () => {
	browser.url('https://google.com');
	browser.element('//input[@id="does not exist"]').isVisible();
});
```
Will result in no errors, but reports will fail to generate (I'm working with allure but other reporters may be messed up as well).  

## Environment

* WebdriverIO version: 4.4.0
* Node.js version: v6.9.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): wdio-allure-reporter, wdio-mocha-framework

## Details

This is happening because the browser.element fails as it should which results in RequestHandler.request returning a rejected promise.  There is no catch in RequestHandler.create and no result event is ever emitted for the element command. 

 I'm not sure how the other handlers work, but with Allure, the result event is what causes `allure.endStep('passed');` to be called.  The end result is endStep is never called for the step and the resulting report has all of the following steps nested within that browser.element step. 

That step is never ended, so a step end and a step status are never added to the report output which causes the report generation to fail. You end up with a step that looks like this:
```<step start="1479503987229" stop="" status="">```
A valid step looks like this:
```<step start="1479503986404" stop="1479503987225" status="passed">```

When you run the allure generate, you get the following error as a result of the empty strings:
```Exception in thread "main" java.lang.NumberFormatException: For input string: ""```

What I have done to fix this problem for myself temporarily is to add a catch onto the promise chain in RequestHandler.create that emits the result and then throws the error again so that it doesn't alter the rest of the execution (notice the catch at the end):
```
return this.request(fullRequestOptions, this.defaultOptions.connectionRetryCount).then(({body, response}) => {
    /**
     * if no session id was set before we've called the init command
     */
    if (this.sessionID === null && requestOptions.requiresSession !== false) {
        this.sessionID = body.sessionId

        this.eventHandler.emit('init', {
            sessionID: this.sessionID,
            options: body.value,
            desiredCapabilities: data.desiredCapabilities
        })

        this.eventHandler.emit('info', 'SET SESSION ID ' + this.sessionID)
    }

    if (body === undefined) {
        body = {
            status: 0,
            orgStatusMessage: ERROR_CODES[0].message
        }
    }

    this.eventHandler.emit('result', {
        requestData: data,
        requestOptions: fullRequestOptions,
        response: response,
        body: body
    })

    return body
}).catch((err) => {
    this.eventHandler.emit('result', {
        requestData: data,
        requestOptions: fullRequestOptions,
        body: null
    })
    throw err
})
```

This probably isn't exactly correct yet, but it does fix the problem.

## Code To Reproduce Issue [ Good To Have ]

```
it( 'test', () => {
	browser.url('https://google.com');
	browser.element('//input[@id="does not exist"]').isVisible();
});
```
when using the allure reporter. After running, try to generate the allure report

**Comment by christian-bromann** [comment]
@krobertson92 thank you very much for this patch. Excellent catch 👏
