### ISSUE TITLE
xpath and waitForVisible

### ISSUE THREAD

**Issue by attilaaronnagy** [webdriverio/webdriverio#1719]
## The problem

Simply couldn't find any solution where I can use both Xpath and waitForVisible.

item.path = "//*[@id=\'root\']/div[1]/div[1]/div[1]/div[1]/span[1]"

**does not work** _(err: element could not be located)_:
browser.waitForVisible(item.path, 5000).then().catch();

**does not work** _(err: element could not be located)_:
const elem = browser.element(item.path);
elem.waitForVisible(5000).then().catch();

**does not work** _(err: element could not be located -» from the doc, this should work http://webdriver.io/guide/testrunner/timeouts.html)_:
const elem = browser.element(xPathToCss(item.path));
elem.waitForVisible(5000).then().catch();

// Only this works, but xPathToCss is an extra npm library I don't trust... So any other idea, how could I achive this?
browser.waitForVisible(xPathToCss(item.path), 5000).then().catch();

## Environment
* WebdriverIO version: 4.4.0
* Node.js version: 7.1
* Standalone mode

**Comment by christian-bromann** [comment]
I don't think `waitForVisible` has a problem with xPath. Have you tried:

```js
browser.waitForVisible("//body");
```

Might want to check if your item path is correct.
