### ISSUE TITLE
Different behaviour when starting selenium server manually and via wdio.conf using wdio-selenium-standalone-service

### ISSUE THREAD

**Issue by UrbaniseQA** [webdriverio/webdriverio#1722]
## The problem

Test fails with incorrect error when wdio with selenium-standalone service is used. Test works fine if selenium server is started manually and wdio just connects to the instance running.

## Environment

* WebdriverIO version: 4.4.0
* Node.js version: v6.9.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: syncronous
* Additional wdio packages used (if applicable):

"devDependencies": {
    "mocha": "^3.1.2",
    "selenium-standalone": "^5.8.0",
    "wdio-mocha-framework": "^0.5.4",
    "wdio-phantomjs-service": "^0.2.2",
    "wdio-selenium-standalone-service": "0.0.7",
    "webdriverio": "^4.4.0"
  },

## Details

Scenario that fails - 
1. run any code that has a click on invalid page element
2. execute test via wdio with config - chrome, mocha  set to bdd, dot reporter. 
3. services: ['selenium-standalone'] enabled. I even used additional params in few executions  - 

seleniumArgs: [ '--version=3.0.1','--drivers.chrome.version=2.25'],

    seleniumArgs: {
        version: '3.0.1',
        'drivers.chrome.version': '2.25'
    },
4. All this executions fail with - 
timeout of 70000ms exceeded. Ensure the done() callback is being called in this test.
running chrome

This is totally incorrect on few levels in my conf i use sync: true and my test is synchronous. I do not need to pass done at all and the real failure in selenium log is element not found exception.

Scenario that works - 

1. Start selenium-standalone manually with start only or 
selenium-standalone start --version=3.0.1  --drivers.chrome.version=2.25
2. run any code that has a click on invalid page element via wdio
3. selenium server throws the element not found exception and in dot reporter I see -

0 passing (66.20s)
1 failing

1) Authentication Page Tests smoke Should allow access with correct creds:
An element could not be located on the page using the given search parameters.
running chrome
Error: An element could not be located on the page using the given search parameters.
    at element() - click.js:12:17
    at click() - at Context.<anonymous> (tests/login.js:31:51)

I am not sure why using wdio-selenium-standalone-service to run tests will not fail the test on exception thrown by selenium and will wait the maximum timeout set for mocha.

## Link to Selenium/WebdriverIO logs

https://gist.github.com/UrbaniseQA/660fbef6246edcc1cdd4d5fde05c18f5
https://gist.github.com/UrbaniseQA/63ea24912b9639f56b5f8f3184c261b7
https://gist.github.com/UrbaniseQA/bbb90512d426449985a435b7144f8c43

Selenium log with correct failure
<script src="https://gist.github.com/UrbaniseQA/63ea24912b9639f56b5f8f3184c261b7.js"></script>

Webdriverio log correct failure -

<script src="https://gist.github.com/UrbaniseQA/bbb90512d426449985a435b7144f8c43.js"></script>

Webdriverio incorrect failure -

<script src="https://gist.github.com/UrbaniseQA/660fbef6246edcc1cdd4d5fde05c18f5.js"></script>

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
Interesting scenario. It seems that if the service is running the execution hung up after the driver wasn't able to query the element. Not sure why that happened. It shouldn't behave differently. I fixed the error message though to give a more meaningful information.
I can't do anything until I get a reproducible example I can look into. Happy to investigate further when I get an example.
