### ISSUE TITLE
browser.switchTo().etc. switchTo() is not a function.

### ISSUE THREAD

**Issue by skortch** [webdriverio/webdriverio#1733]
## The problem
When I try to use browser.switchTo().parentDirectory (or something else) I get the error message switchTo() is not a function. 

## Environment

* WebdriverIO version: 4.4.0
* Node.js version: node --version 6.9.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: ??
* Additional wdio packages used (if applicable): selenium server standalone 2.45

## Details

Not much to add. When I use browser.switchTo().somethingvalid I get the error message switchTo() is not a function and I am dumbstruck on how to switch iFrame.

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

Where do I find those? 

## Code To Reproduce Issue [ Good To Have ]

exports.setup = function() {

    browser.addCommand("pmFillRequirementForm", function (oData) { //Command added to library
        var eTextElement=0;
        console.log("now executing pmFillRequirementForm"); //Prompt to screen of current function executed

        browser.pmRequiredFieldsBlankMessage('requirement', 'Anforderung', 'Requirement'); // see /pm_custom_commands/required_fields_check

        if (oData.domains) {
            browser.pmSetDomainCheckboxes(oData.domains, 'requirement'); //see /pm_custom_commands/set_domain_checkboxes.js
        }
        console.log("filled domain checkboxes");

        if (oData.productlines) {
            browser.pmSetProductlineCheckboxes(oData.productlines, 'requirement'); //see /pm_custom_commands/set_productline_checkboxes.js
        }

        console.log("SET productline checkboxes");

        //  AUSWAHL nach Index statt value
        //  .selectByIndex('#requirement_r_type', 2)

        if (oData.sb_type) {
            browser.selectByValue('#requirement_r_type', oData.sb_type); //sets "Type*:" in "New Requirement"
            //  .getValue('#requirement_r_type')
            //  .then(function(value) {
            //     console.log(value)
            // })
            //.pause(2000)

            /*  Set Number after // replacing the number after .selectByIndex('#requirement_r_type',
             to select a different value in the drop down menue.

             <select id="requirement_r_type" class="select required input-xlarge" name="requirement[r_type]">

             <option value="use" selected="selected"></option>
             <option value="leg"></option>        //   0
             <option value="mar"></option>        //   1
             <option value="org"></option>        //   2
             <option value="out"></option>       //    3
             <option value="sys"></option>       //    4

             </select>

             */
            console.log("SET Type DONE");
        }
        // setzen der Custom-ID (einfaches Textfeld)
        if(oData.if_custom_id) {
            browser.setValue('#requirement_custom_id', oData.if_custom_id); //Fills out the field "Custome ID /source" in "New Requirement"
            console.log("FILL Custome ID DONE");
        }

        if(oData.if_rtext) {
            // setzen des Anforderungs-Texts (ckeditor Richt-Text-Feld)

        //   browser.switchTo().parentFrame();
            browser.switchTo().frame('iframe.cke_wysiwyg_frame');

            browser.setValue('iframe.cke_wysiwyg_frame', oData.if_rtext);
            driver.switchTo().parentFrame();

            //eTextElement=browser.element("#cke_1_contents");
            //browser.click('#cke_requirement_requirement'); //filles out the field "* Requirement" in "New Requirement"
            // .pause(2000)
         //   browser.keys(String(oData.if_rtext));
          //  browser.elementIdValue(eTextElement.value.ELEMENT,oData.if_rtext);
            console.log("FILL Requirement DONE");
            browser.pause(2000);
            browser.switchTo().parentFrame();
        }

        if(oData.s2_keyword) {
          browser.pmSetS2Field('#s2id_autogen7', oData.s2_keyword); //fills out the field "Belongs to keyword" in "New Requirement"
          console.log("FILL Belongs to Keyword DONE");

        }

    });

};
Please excuse the mess.
Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
Please do not chain the commands after switchTo. The command afaik returns `null` and I add any commands to its prototype. So instead of:
```js
browser.switchTo().parentFrame();
```
do:
```js
browser.switchTo();
browser.parentFrame();
```

**Comment by skortch** [comment]
Thanks for the fast response. 

I still get the same error message browser.switchTo is not a function. Its the only instance of switchTo(); I left active to exclude it concking out elsewhere. If only browser.parentFrame(); is active I get the same message browser.parentFrame is not a function.

**Comment by christian-bromann** [comment]
@skortch can you provide a minimal reproducible example that I can run on my machine?

**Comment by skortch** [comment]
Do you have an email for a wetransfer link? The file is not going to be big.

**Comment by christian-bromann** [comment]
@skortch I just need a small test spec that I can run? No need for big files.

**Comment by skortch** [comment]
Well this is the JS I ran. 

exports.setup = function() {


    browser.addCommand("pmFillRequirementForm", function (oData) { //Command added to library
        var eTextElement=0;
        console.log("now executing pmFillRequirementForm"); //Prompt to screen of current function executed

        browser.pmRequiredFieldsBlankMessage('requirement', 'Anforderung', 'Requirement'); // see /pm_custom_commands/required_fields_check



        if (oData.domains) {
            browser.pmSetDomainCheckboxes(oData.domains, 'requirement'); //see /pm_custom_commands/set_domain_checkboxes.js
        }
        console.log("filled domain checkboxes");

        if (oData.productlines) {
            browser.pmSetProductlineCheckboxes(oData.productlines, 'requirement'); //see /pm_custom_commands/set_productline_checkboxes.js
        }

        console.log("SET productline checkboxes");



        //  AUSWAHL nach Index statt value
        //  .selectByIndex('#requirement_r_type', 2)

        if (oData.sb_type) {
            browser.selectByValue('#requirement_r_type', oData.sb_type); //sets "Type*:" in "New Requirement"
            //  .getValue('#requirement_r_type')
            //  .then(function(value) {
            //     console.log(value)
            // })
            //.pause(2000)

            /*  Set Number after // replacing the number after .selectByIndex('#requirement_r_type',
             to select a different value in the drop down menue.

             <select id="requirement_r_type" class="select required input-xlarge" name="requirement[r_type]">

             <option value="use" selected="selected"></option>
             <option value="leg"></option>        //   0
             <option value="mar"></option>        //   1
             <option value="org"></option>        //   2
             <option value="out"></option>       //    3
             <option value="sys"></option>       //    4

             </select>


             */
            console.log("SET Type DONE");
        }
        // setzen der Custom-ID (einfaches Textfeld)
        if(oData.if_custom_id) {
            browser.setValue('#requirement_custom_id', oData.if_custom_id); //Fills out the field "Custome ID /source" in "New Requirement"
            console.log("FILL Custome ID DONE");
        }

        if(oData.if_rtext) {
            // setzen des Anforderungs-Texts (ckeditor Richt-Text-Feld)


          // browser.switchTo();
           browser.parentFrame();
          //  browser.switchTo().frame('iframe.cke_wysiwyg_frame');

            browser.setValue('iframe.cke_wysiwyg_frame', oData.if_rtext);
       //     driver.switchTo().parentFrame();

            //eTextElement=browser.element("#cke_1_contents");
            //browser.click('#cke_requirement_requirement'); //filles out the field "* Requirement" in "New Requirement"
            // .pause(2000)
         //   browser.keys(String(oData.if_rtext));
          //  browser.elementIdValue(eTextElement.value.ELEMENT,oData.if_rtext);
            console.log("FILL Requirement DONE");
            browser.pause(2000);
            browser.switchTo().parentFrame();
        }

        if(oData.s2_keyword) {
          browser.pmSetS2Field('#s2id_autogen7', oData.s2_keyword); //fills out the field "Belongs to keyword" in "New Requirement"
          console.log("FILL Belongs to Keyword DONE");

        }



    });



};

In the iFrame its just supposed to parse in a string.

**Comment by christian-bromann** [comment]
@skortch I can't execute this on my machine as it contains commands and other stuff that I don't have. What I need is something that I can reproduce on my end.

**Comment by skortch** [comment]
Ok this would be a minimum example. Switch to parent frame and then switch into any iFrame by ID or any other tag. Or switch directly into the iFrame if that is possible. 

browser.switchTo();
browser.parentFrame();
browser.switchTo().frame('iframe.cke_wysiwyg_frame');

**Comment by christian-bromann** [comment]
@skortch I think you confuse the usage of `frame` with another library. See the API docs how to switch frames using any selectors strategies.

**Comment by SuchitraK** [comment]
@christian-bromann  I get the same error for browser.getWindowHandles() or browser.getWindowHandle()


> browser.getWindowHandle is not a function

**Comment by abjerstedt** [comment]
@SuchitraK you just necroed an issue from 2 years ago and wdio v4.

Please ask your question in gitter, as this is not an issue and we can help you do things correctly.
