### ISSUE TITLE
How to switch browsers in multiremote mode OR how to exact browser start last?

### ISSUE THREAD

**Issue by ssfxate** [webdriverio/webdriverio#1735]
## The problem
In multiremote mode wdio start two browsers, but randomly selected.
How to switch window in multiremote mode? Like alt+tab to switch program.

## Environment
* WebdriverIO version: 4.4.0
* Node.js version: 7.2.0
* wdio testrunner
* synchronous
* Mocha, personal warp for chainable

## Details
Method from my pageobject
```javascript
tagInputFillAndSubmit (tagName) {
        this.tagInput
                .selectorExecute( els => els[0].scrollIntoView() )
                .waitForVisible()
                .click()
                .setValue(tagName)
                .waitForValue()
                .getValue()
                    .should.equal(tagName, `Tag name isn't correct.`)

        // if window isn't in focus, form closed without sending,
        // but if i switch to window by my self — it works correct.
        this.enter()
        return this;
    }
```

I mean that browsers need to start in sequence of initialize in wdio.conf.js.
```javascript
capabilities: {
        browserB: { desiredCapabilities: { browserName: 'firefox' } },
        browserA: { desiredCapabilities: { browserName: 'firefox' } }
    },
```
Then last started browser will be in focus.

**Comment by christian-bromann** [comment]
@ssfxate multiremote gives you two variables you can use to execute commands on each of the browser (see [example](https://github.com/webdriverio/webdriverio/blob/master/examples/multiremote/webdriverio.multiremote.chat.js)). Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by ssfxate** [comment]
I can't switch browsers.
I can only switch windows in session (in one browser). That is sandbox. First browser can't manipulate others.

Multiremote mode has different sessions.

I need to switch to first browser, not focus. It already in focus for webdriverio. Or make it in focus for OS at start.

**Comment by christian-bromann** [comment]
> I can't switch browsers.

Sure you can. See [these two lines](https://github.com/webdriverio/webdriverio/blob/master/examples/multiremote/webdriverio.multiremote.chat.js#L27-L28) where I set credentials for one browser then for the other.

**Comment by ssfxate** [comment]
If I could, I would have seen the changes in focus of the browsers in the OS. Like shadows of browsers windows.
https://yadi.sk/i/riF7aFPgzkGEq (screenshot)
First row — left browser in focus.
Second row — right browser in focus.

Focus is changed only for webdriverio, not for Mac OS. No shadows changed.

It works good for 99% of my tests, but i have troubles in 1% of tests with input send action in Firefox.

**Comment by christian-bromann** [comment]
@ssfxate Selenium can't set the focus on a browser window. How are your tests affected by that? It shouldn't matter if the browser window has focus or not

**Comment by ssfxate** [comment]
In Firefox some inputs isn't submit correctly or not submit basically.

Maybe it's a bug of firefox, but i can fix it with focus browser in OS manually and then it isn't auto testing =)

**Comment by christian-bromann** [comment]
How do you submit then?

**Comment by ssfxate** [comment]
At the moment I just excluded these tests from the firefox suite.
