### ISSUE TITLE
TestRunner + Jasmine, Async Regression in 4.4

### ISSUE THREAD

**Issue by federicobarera** [webdriverio/webdriverio#1738]
## The problem

jasmine async done() callback is not considered when running in wdio (async mode)
Seems the problem was fixed (https://github.com/webdriverio/wdio-sync/pull/34) but possibly regressed in 4.4
Compared against 3.4.0. Working fine in 3.4.0

## Environment

* WebdriverIO version: 4.4.0
* Node.js version: 4.6.1
* wdio
* async
* framework: jasmine, services: phantomjs

## Link to Selenium/WebdriverIO logs

could not create gist due to comp. proxy. I'll attach whenever possible.

## Code To Reproduce Issue [ Good To Have ]

npm webdriverio, wdio-jasmine-framework, wdio-phantomjs-service.
create wdio config with sync:false, framework: jasmine + jasmine config.
create async test:

```js
it('starts up', function (done) {
        setTimeout(function() {
            expect(false).toBe(true);
            done();
        }, 1000);
          
    });
```
run tests. it passes

**Comment by christian-bromann** [comment]
Why async? WebdriverIO doesn't support done callbacks anymore. I would recommend to use promises here:

it('starts up', function (done) {
        return new Promise(function(resolve) {
            return setTimeout(function() {
                expect(false).toBe(true);
                resolve();
            }, 1000);
        })
    });
```
Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
