### ISSUE TITLE
TypeScript Definition Files

### ISSUE THREAD

**Issue by heri16** [webdriverio/webdriverio#174]
Would the author of this awesome Javascript library be kind enough to write a typescript definition file (d.ts) to make auto-completion work on WebStorm IDE?

Examples here: https://github.com/borisyankov/DefinitelyTyped

Nope, your library does not have to be written in TypeScript to have d.ts files: https://github.com/borisyankov/DefinitelyTyped/tree/master/selenium-webdriver

**Comment by Sanjo** [comment]
:+1: Would be really helpful to get auto completion.

**Comment by christian-bromann** [comment]
There is already a plugin for [Sublime Text](https://packagecontrol.io/packages/WebdriverIO) but I agree that having autocompletion in other IDEs would be great. Though this is not highest priority for me. So if anyone wants to work on this feel free to submit a PR. Thanks!

**Comment by danielcondemarin** [comment]
+1

**Comment by jifeon** [comment]
+1 it would be really great

**Comment by ResolverJay** [comment]
+1

**Comment by christian-bromann** [comment]
Someone awesome contributed to that: https://www.nuget.org/packages/webdriverio.TypeScript.DefinitelyTyped/0.0.1

However that was :hand: :five:
