### ISSUE TITLE
windowHandleSize() and electron

### ISSUE THREAD

**Issue by sean-hill** [webdriverio/webdriverio#1743]
## The problem

Hey there, I'm testing out using Electron instead of my native Chrome binary since Electron appears to be quicker. My existing tests work fine minus this command: `windowHandleSize()`. 

## Environment

* WebdriverIO version: 3.3.0
* Node.js version: 4.5.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Standalone

## Details

I get this error when trying to handle that command:

    RuntimeError: unknown error: cannot get automation extensionfrom unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html

## Code To Reproduce Issue 

```js
let options = {
    host: 'localhost',
    port: 9515,
    desiredCapabilities: {
        browserName: 'chrome',
        loggingPrefs: { 'driver': 'INFO', 'browser': 'INFO' },
        chromeOptions: {
            binary: '/my/electron/binary'
        }
    }
}

webdriverio.remote(options)
    .init()
    .url('https://www.google.com')
    .windowHandleSize({ width: 500, height: 500 })
    .end();
```

**Comment by sean-hill** [comment]
In fact, it appears any commands that do any kind of background process fail.

**Comment by christian-bromann** [comment]
@sean-hill are you sure this is supported by chromedriver and electron?

**Comment by sean-hill** [comment]
@christian-bromann I am unsure. I believe chromedriver does because it was all working dandy before I started using the Electron binary instead of the Chrome binary on my computer. Perhaps they just don't support those kinds of commands yet.

**Comment by christian-bromann** [comment]
I think this is related to Electron and not a specific WebdriverIO bug. Closing.
