### ISSUE TITLE
Parallelize testing on scenarios as well

### ISSUE THREAD

**Issue by si-mikey** [webdriverio/webdriverio#1744]
## Allow parallelization on individual tests/scenarios 

Currently is seems wdio takes a .feature file and runs the entire .feature file in a process. Instead what would be faster would be to extract the scenarios from the feature file and divide those up into the amount of instances specified.

## Environment

* WebdriverIO version: All
* Node.js version: Any
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
* if wdio testrunner, running synchronous or asynchronous tests: Sync
* Additional wdio packages used (if applicable):

**Comment by patthiel** [comment]
Philosophically, the wdio test runner treats every spec or .feature file as a session. This would be a departure from that idea, as every scenario in the .feature would have to be totally self contained. 

It may make sense to do something like this when writing tests in cucumber, but I would argue that each scenario being totally self-contained within a .feature file would actually slow down execution.

**Comment by christian-bromann** [comment]
> I would argue that each scenario being totally self-contained within a .feature file would actually slow down execution.

Exactly. Starting up or tearing down a session can take a lot of time (especially when running on cloud services or certain devices).

Also I think that some people want to keep a session over the whole feature file to test for example a whole checkout process. In addition to that many people won't have the capabilities to parallel their suites on that scale. Therefor I think we should stick with the current behavior until this has changed.
