### ISSUE TITLE
Implicit timeouts are not working as expected

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1748]
## The problem

I want to use `implicit timeouts`, but it are not working (tested with ChromeDriver) as expected.
It works like `browser.pause`, but with endless waiting.

The problem is that 

## Environment

* WebdriverIO version: 4.4.0
* Node.js version: 7.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): it does not matter
* if wdio testrunner, running synchronous or asynchronous tests: sync

### 

### 1

```js
{
    before () {
        browser.timeouts('implicit', 0);
    }
}
```

```js
browser.click(selector);
```

```
1 passing (24.90s)
```

### 2

```js
{
    before () {
        browser.timeouts('implicit', 3 * 100);
    }
}
```

```js
browser.click(selector);
```

```
1 passing (98.40s)
```

### 3

```js
{
    before () {
        browser.timeouts('implicit', 30 * 100);
    }
}
```

```js
browser.click(selector);
```

```
Shutting down... after 15 minutes
```

```js
browser.timeouts('implicit', 0); // no any timeouts
browser.timeouts('implicit', 30); // minor delay
browser.timeouts('implicit', 300); // minor delay 
browser.timeouts('implicit', 3000); // 30-60 sec 
browser.timeouts('implicit', 30000); // endless waiting
```

## Link to Selenium/WebdriverIO logs

```
[12:12:36]  DATA		{"type":"implicit","ms":3000}
....
[12:13:30]  COMMAND	POST 	 "/wd/hub/session/06286e8e-b14f-4d5d-b1d2-3661c32ff6eb/element/56/elements"
[12:13:30]  DATA		{"using":"css selector","value":".messageline__body[data-id=\"00009@bk.3proxy.ru\"] .contactline__body__item_name"}
....
```

**Comment by christian-bromann** [comment]
This can't be a bug of WebdriverIO. It only sends the command to the selenium server. Please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions.

**Comment by monolithed** [comment]
Not so constructive. 
In Serenity platform, the implicit timeouts are placed in configuration settings:

```xml
<webdriver.timeouts.implicitlywait>15000</webdriver.timeouts.implicitlywait>
<webdriver.wait.for.timeout>15000</webdriver.wait.for.timeout>
```

So, the first my proposal is adding another option like `implicitlyWait` as a replacement:

```js
{
    implicitlyWait: 1000

    before () {
        browser.timeouts('implicit', this.implicitlyWait);
    }
}
```

The second observation is that the implicit timeouts are not working as expected (really, you can test).
After some investigation I found [a place](https://github.com/serenity-bdd/serenity-core/blob/0cc86e67f88e8c0533343b95b3668e2c24a7837c/serenity-core/src/main/java/net/serenitybdd/core/pages/PageObject.java#L874-L877) how it was implemented in Serenity:

```java
    public <T extends net.serenitybdd.core.pages.WebElementFacade> T element(WebElement webElement) {
        return net.serenitybdd.core.pages.WebElementFacadeImpl.wrapWebElement(driver, webElement,
                getImplicitWaitTimeout().in(MILLISECONDS),
                getWaitForTimeout().in(MILLISECONDS),
                nameOf(webElement));
    }
```

```
element(locator).click();
```

Maybe my proposal in a previous issue to execute `waitForExist` before each command is reasonable )

**Comment by christian-bromann** [comment]
see Webdriver [docs](http://www.seleniumhq.org/docs/04_webdriver_advanced.jsp#implicit-waits): 

> An implicit wait is to tell WebDriver to poll the DOM for a certain amount of time when trying to find an element or elements if they are not immediately available. The default setting is 0. Once set, the implicit wait is set for the life of the WebDriver object instance.

Sure we could make it an option but I don't think it is a good idea to do so because it can be done easily with a before hook and providing a confusingly huge amount of options isn't helpful too.

> In Serenity platform, the implicit timeouts are placed in configuration settings

Serenity is also just a different implementation of the Webdriver protocol. That doesn't justify whether or not this is a good idea.

> Not so constructive.

Sorry but so is the issue. WebdriverIO is a Selenium 2.0 / Webdriver protocol client implementation. If there is a problem with the implicit timeout it is either a misconception of implicit timeouts (on my or your side) or something in Selenium. All WebdriverIO does is sending a proper request to the server. How it is handled in the browser is not in the scope of WebdriverIO anymore.
