### ISSUE TITLE
browser.sessionId not changing after browser.reload() -BrowserStack

### ISSUE THREAD

**Issue by prasanjitmohanty** [webdriverio/webdriverio#1749]
## The problem

    browser.sessionId not changing after browser.reload() -BrowserStack

        console.log(browser.sessionId); // outputs: ba0c37d61c676128642f5da1980a0f232982bad6
        browser.reload();
        browser.pause(10000);
        console.log(browser.sessionId); // outputs: ba0c37d61c676128642f5da1980a0f232982bad6

Looks like something wrong with BrowserStack integration for WebDriverIO.  This is the third issue similar  #1720 and wdio-firefox-profile-service not working in BrowserStack . Where things are happening correctly in BrowserStack but the SessionIds and window handle Ids are not updating in wdio.  Please don't close this issue as #1720 as it is really blocking us to do things using BrowserStack and I have already wrote lot of tests using WebdriverIO and convinced my team about the WebDriverIO as better framework as compared to other tools available. It will be be painful for us to switch to a different framework at this point of project.

## Environment

* WebdriverIO version:4.4
* Node.js version:6.9.1
* [wdio testrunner]
* if wdio testrunner, synchronous

**Comment by christian-bromann** [comment]
@prasanjitmohanty as mentioned on Gitter, this seems to be an issue of Browserstack. The reload command should end the session and start a new session. This is tested with on an internal selenium cloud and on Sauce Labs.

**Comment by christian-bromann** [comment]
Also, join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by prasanjitmohanty** [comment]
As work around browser.requestHandler.sessionID  works

    console.log(browser.requestHandler.sessionID); 
    browser.reload();
    console.log(browser.requestHandler.sessionID);

**Comment by christian-bromann** [comment]
Fixed issue. `sessionId` is now (with the next release) updated properly.
