### ISSUE TITLE
Abort webdriverio test run on condition [feature]

### ISSUE THREAD

**Issue by ninnepinne** [webdriverio/webdriverio#1750]
## The problem

There are situations where an abort of the wdio test session would be desirable. 

## Details

Example: A needed web service goes down. To avoid running a suite of perhaps hundreds of tests and wait for all their timeouts, the test session could be aborted.

One solution would be to have a stop flag of a configurable number of failed tests.
Another would be to somehow expose an abort function (more flexible).

Thanks!
/Fredrik

**Comment by christian-bromann** [comment]
Implemented. Will be released with next version.

**Comment by ninnepinne** [comment]
@christian-bromann Great news! That was f-a-s-t! Thank you.
