### ISSUE TITLE
TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1751]
## The problem

```js
try {
	browser.waitForVisible('unknown_element');
}
catch (error) {
	console.log('=======', error);
}
```

Press `ctrl+c`;

```
(node:55875) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Couldn't connect to selenium server
(node:55875) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: channel closed
    at process.target.send (internal/child_process.js:540:16)
    at /Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/node_modules/webdriverio/build/lib/runner.js:352:25
    at execHook (/Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/node_modules/wdio-sync/build/index.js:259:35)
======= TypeError: Cannot read property 'trim' of undefined
    at sanitizeErrorMessage (/Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/node_modules/wdio-sync/build/index.js:190:34)
    at Object.waitForVisible (/Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/node_modules/wdio-sync/build/index.js:446:23)
    at Context.it (/Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/cases/addressbook/MAIL-50877/TESTMAIL-33934.js:26:12)
    at /Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/node_modules/wdio-sync/build/index.js:756:26
    at Context.executeSync (/Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/node_modules/wdio-sync/build/index.js:754:12)
    at /Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/node_modules/wdio-sync/build/index.js:952:38
(node:55875) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: channel closed
```

Pay your attention to:

```
 TypeError: Cannot read property 'trim' of undefined
    at sanitizeErrorMessage 
```

## Environment

* WebdriverIO version: latest
* Node.js version: 7

**Comment by christian-bromann** [comment]
Not reproducible. When I press `ctrl+c` while WebdriverIO is fetching the element I get
```
./node_modules/.bin/wdio wdio.conf.js
^C

End selenium sessions properly ...
(press crtl+c again to hard kill the runner)

------------------------------------------------------------------
[phantomjs #0-0] Session ID: 2a298c51-f841-4582-af8b-47bc2c933c96
[phantomjs #0-0] Spec: /Users/christianbromann/Sites/Webprojekte/webdriverjs/issues/1752/index.js
[phantomjs #0-0] Running: phantomjs
[phantomjs #0-0]
[phantomjs #0-0]   #1752
[phantomjs #0-0]
[phantomjs #0-0]
[phantomjs #0-0]

```

**Comment by andremarceloteixeira** [comment]
I get this error 

[chimp][helper] setupBrowserAndDDP had error
TypeError: Cannot read property 'trim' of undefined
    at sanitizeErrorMessage (/root/.nvm/versions/node/v7.4.0/lib/node_modules/chimp/node_modules/wdio-sync/build/index.js:190:34)
    at Object.<anonymous> (/root/.nvm/versions/node/v7.4.0/lib/node_modules/chimp/node_modules/wdio-sync/build/index.js:467:23)
    at initBrowser (/root/.nvm/versions/node/v7.4.0/lib/node_modules/chimp/dist/lib/chimp-helper.js:174:17)
    at Object.setupBrowserAndDDP (/root/.nvm/versions/node/v7.4.0/lib/node_modules/chimp/dist/lib/chimp-helper.js:248:7)
    at /root/.nvm/versions/node/v7.4.0/lib/node_modules/chimp/dist/lib/cucumberjs/hooks.js:21:24
    at /root/.nvm/versions/node/v7.4.0/lib/node_modules/chimp/node_modules/meteor-promise/fiber_pool.js:32:39
TypeError: Cannot read property 'trim' of undefined
    at sanitizeErrorMessage (/root/.nvm/versions/node/v7.4.0/lib/node_modules/chimp/node_modules/wdio-sync/build/index.js:190:34)
    at Object.<anonymous> (/root/.nvm/versions/node/v7.4.0/lib/node_modules/chimp/node_modules/wdio-sync/build/index.js:467:23)
    at initBrowser (/root/.nvm/versions/node/v7.4.0/lib/node_modules/chimp/dist/lib/chimp-helper.js:174:17)
    at Object.setupBrowserAndDDP (/root/.nvm/versions/node/v7.4.0/lib/node_modules/chimp/dist/lib/chimp-helper.js:248:7)
    at /root/.nvm/versions/node/v7.4.0/lib/node_modules/chimp/dist/lib/cucumberjs/hooks.js:21:24
    at /root/.nvm/versions/node/v7.4.0/lib/node_modules/chimp/node_modules/meteor-promise/fiber_pool.js:32:39

Any idea?

**Comment by monolithed** [comment]
@andremarceloteixeira, Do you have a reproducible example? I have not seen this problem for a long time.

**Comment by andremarceloteixeira** [comment]
@monolithed  - Hello monolithed.... Yes , i running the chimp tests in firefox bowser.... 
# xvfb-run -s "-screen 0 1920x1080x24+32" /root/.nvm/versions/node/v7.4.0/bin/chimp  --browser=firefox  --jsonOutput=cucumber_report.json 

node version : node -v
v7.4.0
npm -v
4.0.5
chimp -v
0.47.0

CC: @ErezSo (Expert java-script Developer.)

**Comment by NickBusey** [comment]
I am seeing the same error, same versions as @andremarceloteixeira except chimp 0.47.1.

**Comment by magp3** [comment]
Also getting this running 0.47.1 and node: 7.4.0. I don't get the issue when running node 4.7.3.

**Comment by kajmagnus** [comment]
This same error (?) has started happening to me too now, i.e. weird seemingly impossible `FAIL: TypeError: Cannot read property 'trim' of undefined` errors.

I don't think this is because of any bugs in any of my code, so I just commented out the broken tests, for now. (Feels as if I'm too short of time to try to produce a reproducible test case right now, sorry.)

My code where the problem happens:

1:
```
      console.log('ZZZ selector: ' + selector);    <— shows 'selector' isn't empty
      browser.click(selector);   <— somewhere in here 'trim' fails
```

2:
```
            console.log('ZZZ buttonSelector: ' + buttonSelector);
            let replyButtonLocation = browser.getLocationInView(buttonSelector);
```

As you might have noticed, I added a `console.log` that debug-prints the selector, so I know for sure it's not an empty string. There's something else going on, inside `browser.click()` and `.getLocationInView()`.

Versions:
```
$ wdio -v
v4.6.2
]$ node -v
v7.5.0
$ cat /etc/issue
Ubuntu 16.04.2 LTS \n \l
$ # And Chrome Version 56.0.2924.87 (64-bit)
```

(... Could this be one more of the never-ending incompatibility problems (?) caused by new and new and new versions of Chrome + ChromeDriver ... ?  Anyway, thanks for building Webdriver.io I like it a lot :-) )

**Comment by kajmagnus** [comment]
Do you think this could possibly be related to this issue:
 https://github.com/webdriverio/webdriverio/issues/1885
`Unnecessary trim to browser.getValue()`
 — because I seem to be getting this error in situations where the elems I attempted to click or whatever, were _absent_ because of bugs in my code. So I imagine `getValue()` might have returned nothing, resulting in an error when doing `undefined.trim()`
