### ISSUE TITLE
Chain Commands

### ISSUE THREAD

**Issue by gCrew** [webdriverio/webdriverio#1753]
## The problem

Is it possible to have chain commands in our `test.spec.js` For example, I have pasted the code below but the I get an error saying doClick is not a function. I know I can use promises and take advantage of `.then` but was wondering if anything like below can be accomplished?

 ```
function Page () {
  this.loadingMain = ".overlay";
  this.longTimeout = 60000;
  this.randomButton = ".randomButton";
}

Page.prototype.open = function (url) {
  return browser
    .url(url);
    .waitForVisible(this.loadingMain, this.longTimeout, true);
}

Page.prototype.doClick = function() {
  return browser
    .waitForVisible(this.randomButton)
    .waitForEnabled(this.randomButton)
    .click(this.randomButton)
}

module.exports = new Page()
``` 

`test-page.js` looks like 
```
var page = require('./page.js');

var testPage = Object.create(page, {

    open: { value: function(url) {
        page.open.call(this, url);
    } }

   doClick: { value: function(url) {
        page.doClick.call(this,);
    } }

});

module.exports = testPage
``` 
and finally `test.spec.js` looks like 

```
var page = require('../test-page.js');

describe("test123: test", () => {

  it("test123: test", function () {

    return page
       .open(somethingUrl)
       .doClick()

  });
});
```

## Environment

* WebdriverIO version: 4.2.16
* Node.js version: 4.6.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: async

**Comment by christian-bromann** [comment]
@gCrew your example looks like a weird mixup between sync and async code. Please checkout our [page object](https://github.com/webdriverio/webdriverio/tree/master/examples/pageobject) example and use this. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
