### ISSUE TITLE
<Span> Element is not clickable on mobile web.

### ISSUE THREAD

**Issue by varap** [webdriverio/webdriverio#1755]
## The problem
<button class="button-email btn btn-default" type="button"><span>Sign up with Email</span></button>

* WebdriverIO version: 3.4.0
* Node.js version: 6.7
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):test runner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):

## Details

Describe in more detail the problem you have been experiencing, if necessary.

the react JS form having the signup Button with SPAN element is not working when we try to click through command(.click()). interestingly, on the web, this is not working for chrome Versions after 48 and on the mobile web checked with iphone 6s model . 

im using browserstack for the configuartion.

## Code To Reproduce Issue [ Good To Have ]

let signupModalUserName = '.login-modal-container input[type="email"]';
let signupModalPassword ='.login-modal-container input[type="password"]';
let signupModalSubmitButton ='.login-modal-container.col-md-5.col-sm-12.col-xs-12 > div > div > div.row > div > button > span';

                .setValue(signupModalUserName, validEmail)
                .setValue(signupModalPassword, password)
                .click(submitButton)

The most confused part is it works for chrome version 48 and firefox version 42 . mobile web not working . pls help me in the analysis.
Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
@varap can you provide logs please?

**Comment by varap** [comment]
@christian-bromann 
i'm using browserstack to do the runs and so i got the raw logs from their run  , let me know if you need more data on it .

2016-12-8 2:31:56:245 REQUEST [2016-12-8 2:31:56:245] POST /session/7e17a5b824a10acba1b371047ecd93cd25f29b67/element/5121/value {"value":["v","a","r","a","+","4","8","0","9","0","d","9","0","-","b","c","e","e","-","1","1","e","6","-","8","9","0","b","-","e","d","b","0","3","d","8","1","5","9","9","7","@","s","h","o","p","b","a","c","k",".","c","o","m"]}
2016-12-8 2:31:56:503 DEBUG https://s3.amazonaws.com/testautomation/7e17a5b824a10acba1b371047ecd93cd25f29b67/screenshot-5535cf3692.jpeg
2016-12-8 2:31:56:503 RESPONSE {"status":0,"value":null,"sessionId":"7e17a5b824a10acba1b371047ecd93cd25f29b67"}
2016-12-8 2:31:57:163 REQUEST [2016-12-8 2:31:57:163] POST /session/7e17a5b824a10acba1b371047ecd93cd25f29b67/elements {"using":"css selector","value":".login-modal-container input[type=\"password\"]"}
2016-12-8 2:31:57:186 RESPONSE {"status":0,"value":[{"ELEMENT":"5122"}],"sessionId":"7e17a5b824a10acba1b371047ecd93cd25f29b67"}
2016-12-8 2:31:57:884 REQUEST [2016-12-8 2:31:57:884] POST /session/7e17a5b824a10acba1b371047ecd93cd25f29b67/element/5122/clear {}
2016-12-8 2:31:57:914 DEBUG https://s3.amazonaws.com/testautomation/7e17a5b824a10acba1b371047ecd93cd25f29b67/screenshot-9ad448fb21.jpeg
2016-12-8 2:31:57:914 RESPONSE {"status":0,"value":null,"sessionId":"7e17a5b824a10acba1b371047ecd93cd25f29b67"}
2016-12-8 2:31:58:877 REQUEST [2016-12-8 2:31:58:877] POST /session/7e17a5b824a10acba1b371047ecd93cd25f29b67/element/5122/value {"value":["p","a","s","s","w","o","r","d","1","2","3"]}
2016-12-8 2:31:58:964 DEBUG https://s3.amazonaws.com/testautomation/7e17a5b824a10acba1b371047ecd93cd25f29b67/screenshot-15cb5b672a.jpeg
2016-12-8 2:31:58:964 RESPONSE {"status":0,"value":null,"sessionId":"7e17a5b824a10acba1b371047ecd93cd25f29b67"}
2016-12-8 2:31:59:651 REQUEST [2016-12-8 2:31:59:651] POST /session/7e17a5b824a10acba1b371047ecd93cd25f29b67/element {"using":"css selector","value":".login-modal-container.col-md-5.col-sm-12.col-xs-12 > div > div > div.row > div > button > span"}
2016-12-8 2:31:59:667 RESPONSE {"status":0,"value":{"ELEMENT":"5123"},"sessionId":"7e17a5b824a10acba1b371047ecd93cd25f29b67"}
2016-12-8 2:32:0:410 REQUEST [2016-12-8 2:32:0:410] POST /session/7e17a5b824a10acba1b371047ecd93cd25f29b67/touch/click {"element":"5123"}
2016-12-8 2:32:0:443 DEBUG https://s3.amazonaws.com/testautomation/7e17a5b824a10acba1b371047ecd93cd25f29b67/screenshot-7c144404f4.jpeg
2016-12-8 2:32:0:443 RESPONSE {"status":0,"value":null,"sessionId":"7e17a5b824a10acba1b371047ecd93cd25f29b67"}
2016-12-8 2:32:11:168 REQUEST [2016-12-8 2:32:11:168] POST /session/7e17a5b824a10acba1b371047ecd93cd25f29b67/element {"using":"id","value":"openMenu"}
2016-12-8 2:32:11:182 RESPONSE {"status":0,"value":{"ELEMENT":"5124"},"sessionId":"7e17a5b824a10acba1b371047ecd93cd25f29b67"}
2016-12-8 2:32:11:935 REQUEST [2016-12-8 2:32:11:935] POST /session/7e17a5b824a10acba1b371047ecd93cd25f29b67/touch/click {"element":"5124"}
2016-12-8 2:32:11:963 DEBUG https://s3.amazonaws.com/testautomation/7e17a5b824a10acba1b371047ecd93cd25f29b67/screenshot-d6e30b902e.jpeg
2016-12-8 2:32:11:963 RESPONSE {"status":0,"value":null,"sessionId":"7e17a5b824a10acba1b371047ecd93cd25f29b67"}
2016-12-8 2:32:12:671 REQUEST [2016-12-8 2:32:12:671] POST /session/7e17a5b824a10acba1b371047ecd93cd25f29b67/element {"using":"css selector","value":"#menu > div > ul > li:nth-child(5) > a"}
2016-12-8 2:32:12:686 RESPONSE {"status":7,"value":{"message":"An element could not be located on the page using the given search parameters.","screen":"https://s3.amazonaws.com/testautomation/7e17a5b824a10acba1b371047ecd93cd25f29b67/screenshot-ef2c0f4a7b.jpeg"},"sessionId":"7e17a5b824a10acba1b371047ecd93cd25f29b67"}
2016-12-8 2:32:13:433 REQUEST [2016-12-8 2:32:13:433] POST /session/7e17a5b824a10acba1b371047ecd93cd25f29b67/url {"url":"http://dev:iloveshopback14@qa.shopback.sg/logout"}
2016-12-8 2:32:15:453 DEBUG https://s3.amazonaws.com/testautomation/7e17a5b824a10acba1b371047ecd93cd25f29b67/screenshot-42e4177411.jpeg
2016-12-8 2:32:15:453 RESPONSE {"status":0,"value":"","sessionId":"7e17a5b824a10acba1b371047ecd93cd25f29b67"}
2016-12-8 2:32:19:244 REQUEST [2016-12-8 2:32:19:244] DELETE /session/7e17a5b824a10acba1b371047ecd93cd25f29b67/cookie {}



Console LOG:

1) New User Item purchase through RAF Link:
An element could not be located on the page using the given search parameters.
running iPhone on MAC
Error: An element could not be located on the page using the given search parameters.
    at new ErrorHandler.RuntimeError (node_modules/webdriverio/lib/utils/ErrorHandler.js:93:12)
    at RequestHandler.<anonymous> (node_modules/webdriverio/lib/utils/RequestHandler.js:138:25)
    at Request.self.callback (node_modules/webdriverio/node_modules/request/request.js:373:22)
    at Request.<anonymous> (node_modules/webdriverio/node_modules/request/request.js:1318:14)
    at IncomingMessage.<anonymous> (node_modules/webdriverio/node_modules/request/request.js:1266:12)

**Comment by christian-bromann** [comment]
The problem is that it can't find the element (`#menu > div > ul > li:nth-child(5) > a`) you want to click on.
