### ISSUE TITLE
Ability to Force Color Detection for Reporters

### ISSUE THREAD

**Issue by ChadKillingsworth** [webdriverio/webdriverio#1756]
Build systems like [ninja](https://ninja-build.org/) buffer output then report on completion. This thwarts most color detection. I'd like the ability to force color output rather than solely depending on TTY detection.

Most other test runners have a `--forceColor` option or allow you to add `require('chalk').enabled = true` at the top of your node script to support this functionality.

**Comment by christian-bromann** [comment]
Some of the reporters use chalk these days, so this issue should be fixed by that.
