### ISSUE TITLE
File upload with BrowserStack?

### ISSUE THREAD

**Issue by davidworkman9** [webdriverio/webdriverio#176]
Does this not work? I tried using `chooseKeys`, works locally but fails on browserstack. Browserstack's [examples](https://www.browserstack.com/automate/node#enhancements-uploads-downloads) show an example using something called "firefox_profile". Not sure if this would work with webdriverjs?

**Comment by paulg002** [comment]
> Yes, I ended up using the tunnel, I'll close this now. Thanks!

please post your solution!  @davidworkman9
