### ISSUE TITLE
Drag And Drop

### ISSUE THREAD

**Issue by Brenw10** [webdriverio/webdriverio#1761]
WebdriverIO code:
`client.element('.panel*=Something').dragAndDrop('.draggable-item', '#region');`

HTML:
```
<div class="panel">
        <span class="draggable-item"></span>
        <p>Something</p>
        <p>Something else</p>
</div>
<div id="region"></div>
```

It's not working because I entered in the first div, then the region can't be identified.
How can I ignore element in #region? Is it possible?
Can I do something like `client.dragAndDrop('.panel*=Something .draggable-item', '#region');` ? (It's not working)
Can I use element ID?
Yes, I need drag the span.draggable-item.
The classes, ids and texts are dynamics, then I can't leave fixed draggable-item (This HTML is an example)!!!

Has anything that help me to solve it?

**Comment by christian-bromann** [comment]
Here is what you could do using wdio testrunner:
```js
var something = $('p=something');
var panel = something.$('..');
var source = panel.$('.draggable-item');
var target = $('#region');

source.moveToObject();
browser.buttonDown();
target.moveToObject();
browser.buttonUp();
```

**Comment by Brenw10** [comment]
@christian-bromann Has a way without wdio testrunner?

**Comment by christian-bromann** [comment]
@Brenw10 yes, it is just a different syntax with promises

**Comment by Brenw10** [comment]
@christian-bromann Could you show me please?

**Comment by Brenw10** [comment]
@christian-bromann How can I back an element like you did above. `$('..')`. (Without wdio testrunner)

**Comment by christian-bromann** [comment]
> Without wdio testrunner

This only works with the wdio testrunner. If you use the standalone version you need to handle the execution order by yourself by chaining promises or use async/await

**Comment by Brenw10** [comment]
Ok, I can handler the async. I just need know how can I do that in standalone version. Could you show me please?
