### ISSUE TITLE
Webdriverio unconditionally when using 'call'  method after reject

### ISSUE THREAD

**Issue by eGavr** [webdriverio/webdriverio#1763]
## The problem

```js
const webdriverio = require('webdriverio');

const browser = webdriverio.remote({});

return browser
    .then(() => {
        throw new Error('I am an error!');
    })
    .call(() => console.log('Log from call'))
    .catch((e) => console.log(e));
```

In this case nodejs unconditionally exits because of an error, and this error can not be handled.

output:

```bash
Error: I am an error!
        at Object.<anonymous> (/absolute/path/wdio.js:7:15)
        at Object.exec (/absolute/path/node_modules/webdriverio/build/lib/helpers/safeExecute.js:28:24)
        at Object.resolve (/absolute/path/node_modules/webdriverio/build/lib/webdriverio.js:189:29)
        at /absolute/path/node_modules/webdriverio/build/lib/webdriverio.js:487:32
        at _fulfilled (/absolute/path/node_modules/q/q.js:834:54)
        at self.promiseDispatch.done (/absolute/path/node_modules/q/q.js:863:30)
        at Promise.promise.promiseDispatch (/absolute/path/node_modules/q/q.js:796:13)
        at /absolute/path/node_modules/q/q.js:556:49
        at runSingle (/absolute/path/node_modules/q/q.js:137:13)
        at flush (/absolute/path/node_modules/q/q.js:125:13)
```

This code works fine:

```js
const webdriverio = require('webdriverio');

const browser = webdriverio.remote({});

return browser
    .then(() => {
        throw new Error('I am an error!');
    })
    .catch((e) => console.log(e));
```

output:

```bash
[Error: I am an error!]
```

## Environment

* WebdriverIO version: latest
* Node.js version: 4.x

**Comment by j0tunn** [comment]
@christian-bromann Can you explain please the difference between `call` and `then` methods?

**Comment by CTaylor1118** [comment]
@christian-bromann @j0tunn I did some investigating here and it has to do with the underlying implementation of `call` and `then`. `call` wraps the `promise.done` method and `then` wraps the `promise.then` method. From the docs for the `q` module (https://github.com/kriskowal/q/wiki/API-Reference) `done` will throw unhandled rejections as an actually exception in the process, instead passing the rejected promise on the chain. `done` should probably not be used for the call function unless the intent is we want an exception thrown.

**Comment by christian-bromann** [comment]
> not be used for the call function unless the intent is we want an exception thrown.

Why would we not want to throw an exception if the promise within call gets rejected?

**Comment by CTaylor1118** [comment]
@christian-bromann I am not referring to the promise in `call`. The documentation for `promise.done` says that if an unhandled rejection is encountered, it throws an exception, which is not wrapped as a rejected promise, this will crash the process. It doesn't seem like that is what we would want, so `done` should not be used.

**Comment by franciskim** [comment]
@eGavr I think this is just the default behaviour of promises. The way I handle this situation is like this:

```
const webdriverio = require('webdriverio');
const browser = webdriverio.remote({});

browser
    .then(() => {
        throw new Error('I am an error!');
    })
    .catch((e) => console.log(e)) 
    .call(() => console.log('Log from call'))
    .catch((e) => console.log(e));
```

**Comment by CTaylor1118** [comment]
I think the call function should be renamed to done to make it clear that it is using the done promise under the hood. The behavior when not guarding it with a catch before it is unexpected and will cause your node process to crash unless since it throws an actual exception rather than a rejected promise.

**Comment by franciskim** [comment]
Why is there no code here? https://github.com/webdriverio/webdriverio/blob/master/lib/commands/call.js

**Comment by christian-bromann** [comment]
@franciskim the call command is defined in webdriverio.js .. this file only exists for documentation reasons

**Comment by christian-bromann** [comment]
This issue will be fixed in v5. Closing.
