### ISSUE TITLE
Selenium server stops responding after attempt to click element - Chrome v54 

### ISSUE THREAD

**Issue by dimirey** [webdriverio/webdriverio#1779]
## The problem

After the page loads and the .waitForVisible() command returns true the webdriver is unable to click on the element.

## Environment

* WebdriverIO version: 4.5.1
* Node.js version: 6.9.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): cucumber

## Details

This issue seems to only be affecting chrome 54. It appears that the click function is unable to interact with the returned element.

Stacktrace:

```
․      I wait for "#menuBarCntr > div.header.headerCompose > div" to appear
F      I click on: "#menuBarCntr > div.header.headerCompose > div"

      unknown error: cannot determine loading status
from unknown error: missing or invalid arg value


      Error: unknown error: cannot determine loading status
    at World.<anonymous> (features/step_definitions/global_steps.js:354:17)
    from unknown error: missing or invalid arg value
    at elementIdClick("0.7874685539486699-4") - click.js:20:22

```

step definitions:

```

    this.Then(/^I wait for "(.+)" to appear$/, function (accessor){
        browser.waitForVisible(accessor, 30000);
    });

    this.Then(/^I click on: "(.+)"$/, function (element){
        browser.click(element);
    });

```

**Comment by christian-bromann** [comment]
Sorry but this is not something we can fix. Please fill an issue in the chromedriver project.
