### ISSUE TITLE
doubleClick ,xoffset ,yoffset 

### ISSUE THREAD

**Issue by Mignon-han** [webdriverio/webdriverio#1781]
## The problem
I use webdriverio to test map rendering, so I might need to double-click a location on the map.
I would like to add optional parameters xoffset and yoffset to the doubleClick method.

I run the test in the browser,just like this:
````
let doubleClick = function(selector, xoffset, yoffset) {
  if (this.isMobile) {
    return this.element(selector).then((res) => {
      /**
       * check if element was found and throw error if not
       */
      if (!res.value) {
        throw new RuntimeError(7)
      }

      return this.touchDoubleClick(res.value.ELEMENT)
    })
  }

  return this.element(selector).then((res) => {
    /**
     * check if element was found and throw error if not
     */
    if (!res.value) {
      throw new RuntimeError(7)
    }

    return this.moveTo(res.value.ELEMENT, xoffset, yoffset)
  }).doDoubleClick()
}
export default doubleClick
````

**Comment by christian-bromann** [comment]
Your request seems valid so feel free to create a PR or make it a custom command in your test suite.

**Comment by ZehavitSaban** [comment]
@sep8 @christian-bromann Is it solved? I didn't see that a pr was opened about it.

**Comment by christian-bromann** [comment]
@ZehavitSaban this issue is 8 years old so either it was solved or isn't applying to the project anymore.
