### ISSUE TITLE
Proposal: browser.waitForPromise

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1784]
## browser.waitForPromise

**An abstract implementation**

```js
/**
 * @alias browser.waitForPromise
 * @param {(Promise|Function)} promise
 * @param {number} [timeout] — ms
 * @param {string} [message]
 * @returns {*}
 */
browser.addCommand('waitForPromise', (promise, timeout = 3000, message = '') => {
    let result = null;

    browser.waitUntil(function async () {
        return new Promise((resolve, reject) => {
            global.setTimeout(reject, timeout);

            if (typeof promise === 'function') {
                promise = promise();
            }

            promise.then(response => {
                result = response;
                resolve(true);
            },
            () => resolve(false));
        });
    }, timeout, `Timeout of ${timeout}ms exceeded. ${message}`);

    return result;
});
```

## Usage

1. 

```js
let result = browser.waitForPromise(() => {
    return new Promise((resolve, reject) => {
        global.setTimeout(() => {
            resolve('hello world');
        }, 3000); // will be resolved after 3s
    });
}, 1000);

result; // hello world
```

2.

```js
{
     mochaOpts: {
         timeout: 10000 // will be ignored
     }
}
```

```js
browser.waitForPromise(() => {
    return new Promise((resolve, reject) => {
        global.setTimeout(() => {
            reject();
        }, 3000);
    });
}, 5000);

// Timeout of 5000ms exceeded
```

3.

```js
{
    waitforTimeout: 10000
}
```

```js
let result = browser.waitForPromise(() => {
    return new Promise((resolve, reject) => {
        global.setTimeout(() => {
            reject();
        }, 3000);
    }); //  will be rejected after 10s
});

// Timeout of 10000ms exceeded
```

4.

```js
let result = browser.waitForPromise(Promise.resolve('Hello world'));

// Hello world
```

## Positive sides

* There are `reject` and `resolve`
* There are no any magical `resolve(true)`
* There are no any magical functions named as `async` — are not actual anymore
* `function async` can be replaced with `() =>`
* https://github.com/webdriverio/webdriverio/issues/1407
* `waitForPromise` can return a result
* `waitUntil` will be more consistent with other methods (after some code refactoring :))

@christian-bromann any thoughts on this?

**Comment by christian-bromann** [comment]
This should work too:
```js
let result = browser.call(() => {
    return new Promise((resolve, reject) => {
        global.setTimeout(() => {
            reject();
        }, 3000);
    }); //  will be rejected after 10s
});
```

**Comment by monolithed** [comment]
Oops, i didn't see that before

**Comment by monolithed** [comment]
May be `waitUntil(function async () {})` should be deprecated if It can be replaced with `call`...?

**Comment by christian-bromann** [comment]
> should be deprecated

Well if someone wants to wait until the promise was resolved at least once, `waitUntil(function async () {})` can still be useful.

Does it work with call?

**Comment by monolithed** [comment]
> if someone wants to wait until the promise was resolved at least once

it's a strange thing to wish that :) I guess it can be solved by using `call` with additional options (timeout, message)

**Comment by christian-bromann** [comment]
> it's a strange thing to wish that :)

Well, #1407 proves that 😉 

Can this be closed then?

**Comment by monolithed** [comment]
What do you think about renaming `call` in `waitForPromise`? 😄

**Comment by christian-bromann** [comment]
> What do you think about renaming call in waitForPromise?

I don't think this is a good idea ☺

**Comment by monolithed** [comment]
Maybe there is a reason to add `timeout`?

**Comment by christian-bromann** [comment]
If I get more of that same request I consider it maybe but for now I think we should keep it simple.

**Comment by monolithed** [comment]
I got it, so I close this issue.
