### ISSUE TITLE
Using Selenium Hub

### ISSUE THREAD

**Issue by pavelbinar** [webdriverio/webdriverio#1786]
Is there a way how to run tests with `wdio` on Selenium Hub (hub with more browser versions instances)?

It runs, but only excecutes one browser which is set in the `wdio.conf.js` at `browserName: 'chrome'`

Thanks.

**Comment by christian-bromann** [comment]
Just set the `host` and `port` option to your selenium hub and define multiple capabilities like here: https://gist.github.com/christian-bromann/3e2c3f8aea21f70f612650a85c50af2b#file-wdio-sauce-conf-js. Feel free to join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. 😉

**Comment by pavelbinar** [comment]
OK, thanks again for super saft reply and resolution!

I will try that. I could not find any documentation on that so there might be some room for improvement. Perhaps I could make pull request to https://github.com/webdriverio/webdriver.io with some update...

**Comment by christian-bromann** [comment]
I thought it should be clear from the docs, we have documented it here:
https://github.com/webdriverio/webdriverio/blob/master/docs/guide/getstarted/configuration.md#host or 
https://github.com/webdriverio/webdriverio/blob/master/docs/guide/testrunner/configurationfile.md#configuration-file

The https://github.com/webdriverio/webdriver.io repo doesn't contain any doc files, they are all here in this repository as markdown files.
