### ISSUE TITLE
take screenshots when test fails (not just when a webdriver command fails)

### ISSUE THREAD

**Issue by jedwards1211** [webdriverio/webdriverio#1790]
I don't understand why it isn't the default behavior for wdio to take a screenshot when a test fails.  Currently it only takes a screenshot when a webdriver command fails; but in some cases an assertion will fail the test after a bunch of webdriver commands went through successfully.  Is there something I misunderstand here?

**Comment by christian-bromann** [comment]
You can easily set this up by yourself by using the afterTest hook. Just check if the test has failed and take a screenshot. I don't see a reason why this should be a default behavior. Everyone has their own strategies to evaluate test results.

**Comment by jedwards1211** [comment]
@christian-bromann Yes, I understand, I just thought it was weird...are you saying it's because some people would not want to take a screenshot in the event of certain errors thrown from a test?

**Comment by christian-bromann** [comment]
> are you saying it's because some people would not want to take a screenshot in the event of certain errors thrown from a test?

Yeah. We shouldn't force certain behaviors when they can be reproduced easily. So other people might get confused by that.

**Comment by unformatt** [comment]
> You can easily set this up by yourself by using the afterTest hook

In afterTest, how can you tell a test failed? How can you inspect anything about the current test? I've tried to just get the description of the current test and couldn't figure out how.
