### ISSUE TITLE
`browser.keys()` ignore the current caret position

### ISSUE THREAD

**Issue by AlexandreBonneau** [webdriverio/webdriverio#1791]
## The problem

I'm trying to achieve a seemingly very simple thing :
1. Select an input
2. Set the caret position inside that input
3. Enter some numbers
4. Verify the new caret position, as well as the input value

To do this, I created this test : [The html + buggy.spec.js](http://codepen.io/AnotherLinuxUser/pen/xRoVvX?editors=1010)

Unfortunately, whenever `browser.keys(selectors.input0, ['123']);` is called, the caret position is reset to its default *on-the-far-right-of-the-input-value* place, which is really annoying, to say the least.

I think that `keys()` should not change the caret position, and just manage...key inputs. Or perhaps I'm doing something very wrong here?

## Environment
* WebdriverIO version: 4.5.2
* Node.js version: 4.6.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): `wdio`, `wdio-dot-reporter` and `wdio-jasmine-framework`

## Link to Selenium/WebdriverIO logs
https://gist.github.com/AlexandreBonneau/7c2d39056eee8f457bdd8ac140b1d294

## Code To Reproduce Issue
wdio.conf.js : https://gist.github.com/anonymous/8a6f2dd7565f8e860a96408558c03928

Note : commenting out the line 135 `browser.keys(selectors.input0, ['123']); ` does not move the caret to the far right of the input anymore, but then, how to enter numbers?

**Comment by christian-bromann** [comment]
@AlexandreBonneau please see the API: http://webdriver.io/api/protocol/keys.html the keys command just takes the value to insert value to the focused element.

**Comment by AlexandreBonneau** [comment]
@christian-bromann I've read the documenation, but nowhere in that page it mention the fact that `keys()` is not only sending keys, but also changing the caret position.

If that was the goal, then perhaps the function should be renamed to `putCaretOnFarRightThenSendKeys()`?
Or to be more clear for future readers, a small note in this doc could tell the visitor that the caret position will not be respected, and `keys` has a behavior similar to `setValue`?

Anyway, I fail to see why this issue is being closed, since `keys` should really only send...keys, not change the caret position. Or am I missing something here and such function exists?
Is that a Selenium bug I should report upstream?

**Comment by christian-bromann** [comment]
> Anyway, I fail to see why this issue is being closed, since keys should really only send...keys, not change the caret position. Or am I missing something here and such function exists?
> Is that a Selenium bug I should report upstream?

Yes! This is out of scope of this project. WebdriverIO only follows the Webdriver protocol to send commands to the browser. What actually happens in the browser is job of the browser driver. The behavior probably differentiates between different browser. So please report this bug to the driver project.

**Comment by christian-bromann** [comment]
@AlexandreBonneau all I know is that you can send key commands to manipulate the cursor position or use the execute command to get the current cursor position with some JavaScript magic. I would need more information about your use case to help you here.

**Comment by AlexandreBonneau** [comment]
Thanks for you answer @christian-bromann.

My use case is that being one of the `autoNumeric` maintener, I'd like to setup user interaction testing since those interactions are the core of autoNumeric features.

[autoNumeric](https://github.com/BobKnothe/autoNumeric) is a library that allows a user to enter some numbers in an input, and after each key stroke, the input value and caret position is updated on-the-fly to make it looks like a well-formatted currency.

Right now, I have unit testing [setup](https://github.com/BobKnothe/autoNumeric/blob/next/test/unit/autoNumeric.spec.js) with Jasmine, and this works great to test *internal* functions, or when I want to test if the whole input gets [formatted correctly](https://github.com/BobKnothe/autoNumeric/blob/next/test/unit/autoNumeric.spec.js#L490), but the core feature of autoNumeric is the input interactions, and I need to test things like :
1. Set the input value to the number `123456.78` with `input.autoNumeric('set', 123456.78)`
2. Check that the input value and caret position is now `123,456.78|` ('|' symbolizing the caret position)
3. Move the caret to `123,|456.78`
4. Input the characters `'0'`, `'7'`, `'a'`, `'b'` and `'6'`
5. Check that the input value and caret position is now `123,076|,456.78`

Since we manage a **lot** of small user experience features, this kind of test is a must-have to make sure we are not introducing regression bugs when hacking the code.

Another simple example :
1. Set the input value to the number `123456.78` with `input.autoNumeric('set', 123456.78)`
2. Check that the input value and caret position is now `123,456.78|`
3. Move the caret to `123,4|56.78`
4. Input the characters `ArrowLeft` once
5. Check that the input value and caret position is now `123|,456.78`

This is the kind of test I'm struggling to create right now.

As you can see in the link I [pasted](http://codepen.io/AnotherLinuxUser/pen/xRoVvX?editors=1010) in the initial post, I managed to retrieve the caret position from within the webdriver.io test file, but I had two problems :
- first I need to redeclare my helper function (like `myGetCaretPosition`) in each `browser.execute` block, which I do not understand why and is not DRY, and
- secondly and more importantly, entering keys via webdriver.io moves the cusor to the far right so all my tests are broken and impossible to execute.

**Comment by Lmasniuk** [comment]
Have you happened to find any alternative to setting the caret position via WebDriverIO? I'm trying to do something similar where I want to input a value at the start of an input element rather than at the end, and have ran out of ideas w.r.t. webdriverio

**Comment by AlexandreBonneau** [comment]
@Lmasniuk yes I did, you can check some examples on the AutoNumeric tests I wrote [there](https://github.com/autoNumeric/autoNumeric/blob/next/test/e2e/specs/autoNumeric.e2e.spec.js#L346).

It's quite hacky and it would just be better if Selenium/Webdriver.io supported that in a better way, but oh well...

**Comment by AlexandreBonneau** [comment]
That said, if you want to *set* the caret position at the end or at the start of an input, the easiest way is to  do:
```js
const input = $(selectors.yourInput);
input.click();
browser.keys('Home'); // Start of the input
browser.keys('End'); // End of the input
```
