### ISSUE TITLE
How to open "tor browser" using webdriverio?

### ISSUE THREAD

**Issue by byteshiva** [webdriverio/webdriverio#1792]
## The problem

How to open tor browser using nodejs-selenium in ubuntu 14.04?
Briefly describe the issue you are experiencing (or the feature you want to see added to WebdriverIO). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, join the Gitter chat room ([![Gitter](https://badges.gitter.im/Join Chat.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge))!

## Environment

* WebdriverIO version: latest
* Node.js version: stable latest 7.3.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
You can't open a Tor browser unless it provides a browser driver which afaik it doesn't.

**Comment by ceddybi** [comment]
even up to now, Tor browser doesn't provide the browser driver ? @christian-bromann

**Comment by christian-bromann** [comment]
I don't know if it does.

**Comment by ceddybi** [comment]
@christian-bromann  i wasn't able to use it with puppeteer, i ended up creating a custom extension and run my automations in the content script
