### ISSUE TITLE
Respect mochaOpts.timeout or stop tests after critical errors

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1794]
## The problem

```
chrome
Error
ERROR: Session [2f159574-7e7c-4f9c-9e3d-eedf39ae4964] was terminated due to CLIENT_STOPPED_SESSION
```

```
chrome
Error
ERROR: Session [5f159571-1u7c-hf9c-jek7-eedf87aeg94h] was terminated due to CLIENT_GONE
```

```
ERROR: Error communicating with the remote browser. It may have died.
```

```
chrome
ERROR: session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"11856.1","isDefault":true},"id":1,"name":"","origin":"://"}
```

```
Error: timeout: cannot determine loading status
    at url("/login") - from timeout: Timed out receiving message from renderer: -0,032
```

I see these errors very often and the problem is that my tests are not finished at all. `mochaOpts.timeout` is ignored for these types of errors as well.

## Environment

* WebdriverIO version: 4.5.2
* Node.js version: 7.3
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): sync
* if wdio testrunner, running synchronous or asynchronous tests: testrunner
* Additional wdio packages used (if applicable):  wdio-mocha-framework

**Comment by christian-bromann** [comment]
This has nothing to do with your mocha timeout. This happens because the grid is configured with a timeout that doesn't match the mocha timeout. See [here](https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/4566#issuecomment-192091201) for more information. WebdriverIO is not responsible for setting up the grid timeouts and it can't modify it.

**Comment by monolithed** [comment]
> WebdriverIO is not responsible for setting up the grid timeouts and it can't modify it.

I believe it's possible to catch these errors and stop test execution. 
We don't have such problems with Serenity using the same test environment and grids.

**Comment by monolithed** [comment]
> Tell me how!

These errors are displayed on the terminal, so we can catch them 😄 
Maybe it's possible to subscribe on the `message` event...
