### ISSUE TITLE
Unable to use selectByVisibleText() on drop down menu values that contain &nbsp;

### ISSUE THREAD

**Issue by adamlemisch** [webdriverio/webdriverio#1795]
## The problem
When attempting to make a selection using selectByVisibleText() from a drop down menu who's values contain &nbsp's, the following error is received:

```
An element could not be located on the page using the given search parameters.
running chrome
Error: An element could not be located on the page using the given search parameters.
    at elementIdElement("4", "./option[normalize-space(.) = "A01 - NORTHWEST"]|./optgroup/option[normalize-space(.) = "A01 - NORTHWEST"]") - selectByVisibleText.js:33:22
```

Menu structure:
![image](https://cloud.githubusercontent.com/assets/3834021/21547635/98a7750e-cda4-11e6-9eb5-950612fdb813.png)

Commands attempted:
```PageOnePage.area_drop_down.selectByVisibleText('A01&nbsp;-&nbsp;NORTHWEST');```
```PageOnePage.area_drop_down.selectByVisibleText('A01 - NORTHWEST');```
## Environment

* WebdriverIO version: ^4.5.2
* Node.js version: v7.2.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): N/A

Please let me know if more information is needed.

**Comment by AbhiMatcha** [comment]
Still im facing this issue. :(

**Comment by rohithnl007** [comment]
This worked for me, 
menuItemsOptions(element) - dropdown menu option(s)
dropDownButton(element) - dropdown arrow
textToSelect(String) - text we want to select

static selectByVisibleTextInDropdown(menuItemsOptions, dropDownButton, textToSelect) {
        browser.click(dropDownButton);
        console.log("Dropdown button clicked");
        const menuItems = browser.elements(menuItemsOptions).value;
        console.log("List of Options displayed");
        for (const item of menuItems) {
            const menuItem = browser.elementIdText(item.ELEMENT).value;
            console.log(`menuItem: ${  menuItem}`);
            if (menuItem.toLowerCase().includes(textToSelect.toLowerCase())) {
                console.log(`Clicking on ${menuItem}`);
                browser.elementIdClick(item.ELEMENT);
                break;
            }
        }
    }

**Comment by christian-bromann** [comment]
This issue was moved to webdriverio-boneyard/v4#13
