### ISSUE TITLE
SIGINT handler is not killing process

### ISSUE THREAD

**Issue by artur-michalak** [webdriverio/webdriverio#1798]
## The problem

When i setup webdriver.io with gulp watch and interrupt process with ctrl+c it's not closing.

## Environment

* WebdriverIO version: v4.5.2
* Node.js version: v4.4.5 (v6 too)
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): jasmine testrunner
* if wdio testrunner, running synchronous or asynchronous tests: asynchronous
* Additional wdio packages used (if applicable):

    "wdio-dot-reporter": "0.0.6",
    "wdio-jasmine-framework": "^0.2.19",
    "wdio-selenium-standalone-service": "0.0.7",
    "gulp-webdriver": "^2.0.3",

## Link to Selenium/WebdriverIO logs

[12:56:45] Finished 'e2e:run' after 16 s
[12:56:45] Finished 'e2e:dev' after 17 s
then on cmd + c click:

End selenium sessions properly ...
(press crtl+c again to hard kill the runner)

Killing process, bye! (on cmd + c click)
Killing process, bye! (on cmd + c click)
Killing process, bye! (on cmd + c click)
Killing process, bye! (on cmd + c click)

## Code To Reproduce Issue [ Good To Have ]

1. Setup gulp
gulp.task('e2e:run', function () {
    return gulp.src(config.e2e.config).pipe(webdriver({
        baseUrl: 'http://localhost:' + config.e2e.port,
        specs: config.e2e.specs
    })).on('error', handleErrors);
});

// production release of player
gulp.task('e2e:dev', function() {
    gulp.watch(config.e2e.specs, ['e2e:run']);
});

2. Run e2e:run task. Everything works like a charm
3. Run e2e:dev which is watching files
4. Interrupt (ctrl + c/cmd+c) twice
5. Gulp process is not killed

# Details
I would guess something is wrong with logic here
https://github.com/webdriverio/webdriverio/blob/68974ac33aa13fa099b1870d5a81ce5c6d8341db/lib/launcher.js#L418
Perhaps process.exit is not being called.

**Comment by christian-bromann** [comment]
This issue was moved to webdriverio/gulp-webdriver#56

**Comment by christian-bromann** [comment]
Moved to gulp-webdriver project.
