### ISSUE TITLE
10 is added to scenario in verbose printout.

### ISSUE THREAD

**Issue by skortch** [webdriverio/webdriverio#1799]
## The problem

Say I have a scenario in a .feature file that reads like 

Scenario: Description of the scenario

in the Terminal when I run the feature I get the printout 

Description of the scenario10

for all scenarios. I have no idea where I would even check for that error. 

## Environment

* WebdriverIO version: 4.5.1
* Node.js version: 6.9.2
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Standalone
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable): Chai 3.5.0

## Link to Selenium/WebdriverIO logs (where do I find them?)

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
Please update the WebdriverIO, framework adapter and reporter. It should be fixed then.
