### ISSUE TITLE
Support for Chrome's Network throttling

### ISSUE THREAD

**Issue by sbougon** [webdriverio/webdriverio#1803]
## The problem

Chromedriver now supports Network Throttling (https://chromedriver.storage.googleapis.com/2.27/notes.txt: Resolved issue 984: Extend ChromeDriver capabilities to cover network throttling feature from Chrome DevTools [['OS-All', 'Pri-2']])

Would be nice to expose this functionality to WebdriverIO. Or maybe an API to allow us using features not yet in webdriverIO ?

## Environment

* WebdriverIO version: latest

## Details

I was able to throttle my Chrome Network by doing this:
// get the session id
curl -X POST http://hostname:4444/wd/hub/session -d '{"desiredCapabilities":{"browserName": "chrome"}}'
// set the network condition to GPRS
curl -X POST http://hostname:4444/wd/hub/session/fe690c30b65b7d858d1485892d777796/chromium/network_conditions -d { "network_name" : "GPRS" }
// go to amazon.com
curl -X POST http://hostname:4444/wd/hub/session/fe690c30b65b7d858d1485892d777796/url -d '{"url":"http://www.amazon.com"}'
// victory, amazon.com loaded very slowly

**Comment by christian-bromann** [comment]
This is already possible with these capabilties:

```js
...
capabilities: [{
    browserName: 'chrome'
    chromeOptions: {
        mobileEmulation: {
             networkThrottle: '3G'
        }
    }
}],
...
```

I am not sure tho how to exactly apply the throttling value. I don't see it documented in the chromedriver docs (https://sites.google.com/a/chromium.org/chromedriver/capabilities). I assume it is something like this.

**Comment by sbougon** [comment]
Hi @christian-bromann , I think what you suggested works for mobile, not desktop.
See my gist for the code example/logs/observation:
https://gist.github.com/sbougon/fb0579758922c64f64a546327fe58dec

Can webdriverio offers a way to http POST to the webdriver server for unsupported/not yet developped features ?

**Comment by petole** [comment]
In other words, the new API from chromedriver to throttle Desktop Chrome is not called/executed via the:
...
capabilities: [{
    browserName: 'chrome'
    chromeOptions: {
        mobileEmulation: {
             networkThrottle: '3G'
        }
    }
}],
...
which is reserved for mobile only I think

**Comment by christian-bromann** [comment]
> Can webdriverio offers a way to http POST to the webdriver server for unsupported/not yet developped features ?

yes it can

**Comment by seanpoulter** [comment]
If anyone ends up here trying to figure out how to throttle network connections [like the Dev Tools,](https://developers.google.com/web/tools/chrome-devtools/network-performance/network-conditions#emulate_network_connectivity), there's an existing JavaScript binding. The Selenium ChromeDriver class, `Driver`, exports the `setNetworkConditions` method. Here's a link to the [source code with a usage example in the comments](https://github.com/SeleniumHQ/selenium/blob/e4696a2/javascript/node/selenium-webdriver/chrome.js#L752) from what was the tip of master at the time of writing. Hopefully it's exposed from WebDriverIO.

**Comment by joscha** [comment]
I can't seem to be able to reach this from wdio - anyone else more luck?

**Comment by christian-bromann** [comment]
> I can't seem to be able to reach this from wdio - anyone else more luck?

Yes, using the wdio-devtools-service

**Comment by joscha** [comment]
ah nice @christian-bromann 🎉 - link for all other lazy readers at home: https://github.com/webdriverio/wdio-devtools-service

**Comment by anescobar1991** [comment]
@christian-bromann any way to do this when using standalone mode or do I need to build my own based on how you set it up for wdio?

**Comment by christian-bromann** [comment]
> any way to do this when using standalone mode

sure but you need to connect to the devtools interface by yourself, the service mentioned above won't work in standalone mode

**Comment by anescobar1991** [comment]
> Can webdriverio offers a way to http POST to the webdriver server for unsupported/not yet developped features?

@christian-bromann would you accept a PR for enable said feature?

**Comment by christian-bromann** [comment]
> @christian-bromann would you accept a PR to enable said feature?

Absolutely

**Comment by diachedelic** [comment]
Now `wdio-devtools-service` is defunct, is there better good way to go about throttling Chrome?  I'm trying to use [`browser.setNetworkConditions`](https://webdriver.io/docs/api/chromium.html#setnetworkconditions) but it's prevent pages from loading in Chrome, regardless of params passed.

**Comment by diachedelic** [comment]
My bad, I was passing kbps instead of bps in the parameters, correct units are like:

```js
    browser.setNetworkConditions({
      latency: 500, // ms
      // below values are in bps
      download_throughput: 3 * 1024 * 1024 / 8, // 3MB/s
      upload_throughput: 1 * 1024 * 1024 / 8, // 1MB/s
    })
```
