### ISSUE TITLE
The README does not show the awesomeness of WDIO

### ISSUE THREAD

**Issue by tiffon** [webdriverio/webdriverio#1804]
## The sample snippet in the README does not show the awesomeness of the synchronous approach enabled by `wdio`

I'm using and loving weddriver.io, and in reality practical use of it for testing it is nothing like the small snippet in the README. The `wdio` approach is basically **awesome** and is nowhere to be seen in the README.

Instead of

```js
client
    .url('http://google.com')
    .setValue('#q', 'webdriver')
    .click('#btnG')
```

At the very least:

```js
browser.url('http://google.com');
browser.setValue('#q', 'webdriver');
browser.click('#btnG');
```

But, really, **a complex example would be ideal**, as this is where the awesomeness of the WDIO approach really shines.

**Comment by christian-bromann** [comment]
Thanks for filing the issue. I tweaked the example, how does it look now?

**Comment by tiffon** [comment]
Hey, nice, definitely improved, but TBH I think the awesomeness of webdriver.io / wdio is still not fully presented. I'll see if I can work something up and run it by you.

Thanks for the great work on webdriver.io.
