### ISSUE TITLE
How do you actually hover an element on desktop?

### ISSUE THREAD

**Issue by inspiraller** [webdriverio/webdriverio#1808]
## The problem

Currently it is possible to touch a mobile element, but nothing seems to work for desktop. I've tried moveToObject('.elem'), but this isn't an explicit hover, and no chaining methods seem to hover it. 
I want to test than a hover changes the css of the element.

**Comment by christian-bromann** [comment]
This is due to Selenium limitations. It will be improved once the [action API](https://www.w3.org/TR/webdriver/#actions) landed in all the browser driver. WebdriverIO will provide proper commands once that happened.
