### ISSUE TITLE
Error: Couldn't connect to selenium server

### ISSUE THREAD

**Issue by elimence** [webdriverio/webdriverio#1810]
I came across this project recently and I'm trying to use it to fetch a dynamic page rendered by javascript. Here's the code
```
var phantomjs = require('phantomjs-prebuilt')
var webdriverio = require('webdriverio')
var wdOpts = { desiredCapabilities: { browserName: 'phantomjs' } }

async parse(parseUrl) {
    return webdriverio.remote(wdOpts)
      .init()
      .url(parseUrl)
      .waitForVisible('#brand-index-container', 20000)
      .getHTML('html', true)
  }
```

The thing is this worked before, but all of a sudden without any reason as far as I can tell, I begin to get the following error

```
{
  "error": {
    "message": "Couldn't connect to selenium server",
    "stack": "Error: Couldn't connect to selenium server\n    at getHTML(\"html\", true) - chart-service.js:77:",
    "type": "RuntimeError",
    "seleniumStack": {
      "status": -1,
      "type": "ECONNREFUSED",
      "message": "Couldn't connect to selenium server",
      "orgStatusMessage": "Couldn't connect to selenium server"
    },
    "isBoom": true,
    "isServer": true,
    "data": null,
    "output": {
      "statusCode": 500,
      "payload": {
        "statusCode": 500,
        "error": "Internal Server Error",
        "message": "An internal server error occurred"
      },
      "headers": {}
    }
  }
}
```

Maybe I'm missing something, does the code require a connection to a selenium server to run? Why did it run the first time?

## Environment

* WebdriverIO version: 4.6.1
* Node.js version: 6.9.3

**Comment by monolithed** [comment]
Have you started the selenium server?

### package.json

```json
{
	"scripts": {
		"start": "selenium-standalone start",
		"selenium": "selenium-standalone",
	},

	"devDependencies": {
		"selenium-standalone": "^5.9.1",
		"wdio-selenium-standalone-service": "^0.0.7"
	}
}
```


### wdio.local.config.js

```js
{
	services: [
		'selenium-standalone'
	]
}
```

```
npm install
npm run selenium install
wdio wdio.local.config.js
```

If you are not going to use `wdio-selenium-standalone-service` (CI way):

### wdio.local.config.js

```js
{
	services: [ ]
}
```

```
npm install
npm start
```

Open another window in your terminal and type the following command:

```
wdio wdio.local.config.js
```

**Comment by christian-bromann** [comment]
@elimence as @monolithed mentioned make sure you run a phantomjs server. Only requiring it isn't enough. If you use webdriverios testrunner you can use the selenium standalone service which makes it pretty easy.

Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by elimence** [comment]
@christian-bromann Noted, will use gitter next time.
@monolithed Thanks, I'm using heroku though, wasn't sure I could use the standalone server there, can I?
I used the following:
```
return phantomjs.run('--webdriver=4444').then(program => {
      console.log('returning webdriverio')
      return webdriverio.remote(wdOpts)
        .init()
        .setViewportSize({ width: 360, height: 360 })
        .url(parseUrl)
        .waitForVisible('#brand-index-container', 20000)
        .getHTML('html', true)
    })
```
and it works now, but is awfully slow.
I'm going to try again with your suggestions, hopefully that works better.
Thanks
