### ISSUE TITLE
`Cannot read property 'ELEMENT' of null` when using page objects.

### ISSUE THREAD

**Issue by kevinmcdonnell** [webdriverio/webdriverio#1811]
## The problem

I get `Cannot read property 'ELEMENT' of null` when using page objects.

## Environment

* WebdriverIO version: v4.6.1
* Node.js version: v4.6.1 (same as wdio ;))
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable):
    "wdio-allure-reporter": "0.1.2",
    "wdio-junit-reporter": "0.1.0",
    "wdio-mocha-framework": "0.5.4",
    "wdio-selenium-standalone-service": "0.0.7",

## Details

> I want to wait for an element to exist, and then click another element

This works:
```
var selectors = {
    startButton: '.start-test-btn',
    startButtonReady: '.lrn-start-page .lrn-dialog-footer button[style="display: inline; opacity: 1;"]'
};

browser.addCommand("clickStartAssessment", function () {
    browser.waitForExist(selectors.startButtonReady);
    PageObjects.assessment.startButton.click();
});
```

This doesn't:
```
browser.addCommand("clickStartAssessment", function () {
    PageObjects.assessment.buttonReady.waitForExist();
    PageObjects.assessment.startButton.click();
});

```

I get `Cannot read property 'ELEMENT' of null`

This is my page object
```
var page = require('./page');

var selectors = {
    startButton: '.start-test-btn',
    startButtonReady: '.lrn-start-page .lrn-dialog-footer button[style="display: inline; opacity: 1;"]'
};

var assessment = Object.create(page, {
    /**
     * define elements
     */
    startButton: { get: function () { return browser.element(selectors.startButton); } },
    buttonReady: { get: function () { return browser.element(selectors.startButtonReady); } }
});

module.exports = assessment;
```

**Comment by rochdev** [comment]
I am having the same error on WebdriverIO 4.6.1 and Node 6.5.0. 

In my case, the following works:

```js
class MyPage {
  search (values) {
    return browser.element('.query input').setValue(values)
  }
}
```

While this doesn't:

```js
class SearchField {
  constructor (root) {
    this.root = root
  }

  search () {
    return this.root.element('input').setValue(values)
  }
}

class MyPage {
  search () {
    const searchField = new SearchField(browser.element('.query'))
  }
}
```

Event simply replacing `browser.element('.query input')` by `browser.element('.query').element('input')` in the working example actually makes it fail.

**Comment by kevinmcdonnell** [comment]
The following provides a reproducible example of one scenario I am seeing the issue.
Test:
```
describe('Given github.com', function() {
    'use strict';

    beforeEach(function () {
        browser.url('http://github.com');
    });

    it('When test uses `browser.isExisting(selector)` in waitUntil, Then no error is thrown', function() {
        var attempts = 0;

        PageObjects.assessApp.logo.waitForExist();

        browser.waitUntil(function () {
            attempts++;

            return (browser.isExisting('.header-logo-invertocat .octicon-mark-github') === false) || (attempts >= 3)
        }, 5000)
    });

    it('When test uses `PageObjects.assessApp.logo.isExisting()` in waitUntil, Then an error is thrown', function() {
        var attempts = 0;

        PageObjects.assessApp.logo.waitForExist();

        browser.waitUntil(function () {
            attempts++;

            return (PageObjects.assessApp.logo.isExisting() === false) || (attempts >= 3)
        }, 5000)
    });

});
```
Page Object:
```
var page = require('./page');

var assessApp = Object.create(page, {
    /**
     * define elements
     */
    logo:     { get: function () { return browser.element('.header-logo-invertocat .octicon-mark-github'); } }
});

module.exports = assessApp;

```

**Comment by christian-bromann** [comment]
@kevinmcdonnell can you please update your wdio-mocha-framework?

**Comment by kevinmcdonnell** [comment]
👍 nice one

**Comment by wwwwwwork** [comment]
if you are using `"webdriverio": "4.6.2"` you have to update to `"wdio-mocha-framework": "0.5.10"` to fix this issue

**Comment by Xotabu4** [comment]
Still having this issue with 
```
"webdriverio": "^4.9.11"
"wdio-mocha-framework": "^0.5.12",
```
```
  openUserGuide() {
    let someElem = browser.$('.user_bar a.ico_help')
    someElem.click()
  }
```

```
[chrome #0-0] Cannot read property 'ELEMENT' of null
[chrome #0-0] TypeError: Cannot read property 'ELEMENT' of null
[chrome #0-0]     at element(".user_bar a.ico_help") - index.js:312:3
```

**Comment by christian-bromann** [comment]
@Xotabu4 probably your element was not found. For some reason the error message is not properly thrown when calling the click command

**Comment by Xotabu4** [comment]
@christian-bromann 
I found out whats happens
In base class that i was extended, i had -
class BasePage {
 public projectList = browser.$('//*[@id="eventivals"]/div/div[2]/ul')
  public projectLink = browser.$('div#eventivals .dropdown-caption')
}
so on object creation were attempts to find elements on the page, i thought webdriverio has lazy elements. But it not, and throws unclear exceptions
i wrapped to getters, and now it is fine

**Comment by christian-bromann** [comment]
Latter example is the proper way to do the page object pattern. I think the problem was that these commands were executed right at the beginning when you required the file. In that environment you can't run WebdriverIO commands. Every command has to be located within an test or hook.

**Comment by ogiexela** [comment]
Still getting "Cannot read property 'ELEMENT' of null" if I call my findElement function a second time which I defined in browser.addCommand('findElement', function(selector) {
return browser.element(selector)
})

i'm using 
"webdriverio": "4.13.1",
 "wdio-jasmine-framework": "0.3.5",
