### ISSUE TITLE
Allow harmony flag in mochaOpts

### ISSUE THREAD

**Issue by lancecarlson** [webdriverio/webdriverio#1814]
## The problem

I want to use async/await in my specs (which the latest version of node supports with the harmony flag). I tried to set harmony: true inside of my wdio.conf.js file under mochaOpts but that didn't seem to do anything. Looking through cli.js I wasn't sure how flags proxy through to mocha options, but it seems like bool flags should be easy to set?

## Environment

* WebdriverIO version: 4.6.1
* Node.js version: 7.3.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): testrunner
* if wdio testrunner, running synchronous or asynchronous tests: async
* Additional wdio packages used (if applicable):

## Link to Selenium/WebdriverIO logs

https://gist.github.com/lancecarlson/a0e0c0bca3342ad09fc3055f794a08fd

## Code To Reproduce Issue [ Good To Have ]

Example code I'd like to run:

```
require('../spec_runner')

describe("First Spec", () => {
  it("should navigate to the WebdriverIO homepage", async () => {
    let url = await browser.url("http://webdriver.io/")
      .click("[href='/guide.html']")
      .getUrl()
    console.log(url)
  })
```

**Comment by monolithed** [comment]
I don't know a right way how this could be implemented, maybe:

```sh
#!/usr/bin/env node

process.env.NODE_ENV = process.env.NODE_ENV || 'test';

require('../build/lib/cli.js');
```

```sh
#!/usr/bin/env bash
":" //# comment; exec /usr/bin/env node --harmony "$0" "$@"

process.env.NODE_ENV = process.env.NODE_ENV || 'test';

require('../build/lib/cli.js');
```

I'm not sure we need it, but probably you can fix it yourself.

**Comment by christian-bromann** [comment]
In your wdio config do
```js
// ...
mochaOpts: {
    harmony: true,
    // ...
```
```

**Comment by lancecarlson** [comment]
@christian-bromann No, I had that config in there as I thought that was the obvious move. It didn't do anything though. Did you test this on your end and did it work? That flag doesn't work for me.

**Comment by christian-bromann** [comment]
This should be fixed by now. Please let me know if not. Another option would be to run nodejs with harmony flag: `node --harmony ./node_modules/.bin/wdio wdio.conf.js`
