### ISSUE TITLE
.getCssProperty + z-index returning null in IE11

### ISSUE THREAD

**Issue by brianjoyner** [webdriverio/webdriverio#1818]
## The problem

.getCssProperty(element,'z-index') is returning null in IE11.  Other browsers are returning values as expected.

I've tried this with a variety of elements and the results are the same.

## Environment

* WebdriverIO version: 4.6.1
* Node.js version: 6.9.2
* Using wdio testrunner and asynchronous tests

## Link to Selenium/WebdriverIO logs

Results from Chrome and Results From IE11

․{"height":{"property":"height","value":"1107px","parsed":{"type":"number","string":"1107px","unit":"px","value":1107}},"width":{"property":"width","value":"1184px","parsed":{"type":"number","string":"1184px","unit":"px","value":1184}},"zIndex":{"property":"z-Index","value":2147483647,"parsed":{"type":"number","string":"2147483647","unit":"","value":2147483647}}}

․{"height":{"property":"height","value":"1137px","parsed":{"type":"number","string":"1137px","unit":"px","value":1137}},"width":{"property":"width","value":"1184px","parsed":{"type":"number","string":"1184px","unit":"px","value":1184}},"zIndex":null}

## Code To Reproduce Issue [ Good To Have ]

Using a page-object build:

```
    shroudCSS : { value : function(cID) {
            var specs = {
                height : browser.getCssProperty('#exampleElement' + cID, 'height'),
                width : browser.getCssProperty('#exampleElement' + cID, 'width'),
                zIndex : browser.getCssProperty('#exampleElement' + cID, 'z-Index')  //z-index fails with IE11
            };
            return specs;
    }},
```

**Comment by christian-bromann** [comment]
Have you tried `zIndex` in IE?

**Comment by brianjoyner** [comment]
@christian-bromann That appears to expand the issue.  

Both IE11 and Edge fail when I seek zIndex rather than z-index.

**Comment by christian-bromann** [comment]
@brianjoyner will have to close this. It is obviously an issue with the ie/edge driver. Please file an issue there. I would be happy to implement a workaround for ie and edge but it seems to not be able to receive this data at all.
