### ISSUE TITLE
WaitForVisible command doesn't work as expected

### ISSUE THREAD

**Issue by Kosta19** [webdriverio/webdriverio#1820]
This works 
```js
browser.waitForVisible("//div[@class='activity-feed-msg l-margin-bottom-sm'][contains(.,'Incoming Email notes')]", 10000);
```
This does not work
```js
RoosterPage.incomingEmailNotesLogInteraction().waitForVisible(10000);
```
Here is an error: Unable to locate element, see screenshot  http://i.dcodeit.net/zalutsky/i/cmd_2017-01-17_11-10-26.png

## Environment
My environment http://i.dcodeit.net/zalutsky/i/cmd_2017-01-17_11-21-30.png:
* wdio runner:

## Details

Something wrong with waitForVisible and using it in page objects

**Comment by christian-bromann** [comment]
Please make sure that the element you are looking for exists on the page by using waitForExist.

**Comment by christian-bromann** [comment]
Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
