### ISSUE TITLE
Exclude "before all" hook

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1821]
![img-2017-01-17-12-26-15](https://cloud.githubusercontent.com/assets/803674/22014747/36e1b33c-dcb0-11e6-8309-5e78e97e15b3.png)

I know there were some fixes before as well for this type of issue.... let's finish. 
it's really hard to analyze test reports.

**Comment by christian-bromann** [comment]
> let's finish

any contribution is highly appreciated
