### ISSUE TITLE
Support waitforTimeout in executeAsync

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1822]
## The problem

```js
browser.timeouts('script', browser.options.waitforTimeout); // it's pain to add this line 
let { value } = browser.executeAsync(function (resolve) { };
```

I propose to use `browser.timeouts('script', browser.options.waitforTimeout);` by default.

**Comment by christian-bromann** [comment]
I don't see why having that line in the before hook of your wdio config can be a pain. These are two different timeouts and shouldn't be synced by default.

**Comment by monolithed** [comment]
> I don't see why having that line in the before hook of your wdio config can be a pain.

I didn't know about that. I'll try, thanks!
