### ISSUE TITLE
can use $$ command in REPL but not in a script. 

### ISSUE THREAD

**Issue by skortch** [webdriverio/webdriverio#1827]
## The problem

When I use the $$ command in the REPL interface it works fine. 
but when I use code like 
$$('nav a')[2].getText()

in a script file when I execute it I get an error message

can not get property of undefined. 

I am using an older version of selenium, but repl uses it and the command works fine in repl.

## Environment

* WebdriverIO version: 4.6.1
* Node.js version: 6.9.4
* [Standalone mode or wdio testrunner]Standalone 2.53.0
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable): chai  3.5.0

## Details

$$ seems to not be working. When I use the following in a script 

//$$('div.pm_product_item').forEach(function(link) {
    //    if(link.getText().includes("Text")) {
    //        b=i;
    //        console.log("COUNTER B " + b);
    //    } else {
    //        i++;}
    //});

nothing happens in this particular example not even an error message. If I parse it as a line and paste it into REPL it works as intended.

## Link to Selenium/WebdriverIO logs

https://gist.github.com/skortch/7760c46f10d4054d0fa9dc52b8026561

**Comment by christian-bromann** [comment]
Make sure you are running the wdio testrunner and have the latest WebdriverIO and framework adapter package installed. The example on the [website](http://webdriver.io/) for example works.

**Comment by skortch** [comment]
Hi thanks for the reply. So I need to use selenium with the wdio testrunner to use it.

Framework? If Selenium with wdio testrunner is not the framework what would it be then?

**Comment by christian-bromann** [comment]
The wdio testrunner is just a way how you can run tests on higher scale in a synchronous way. See [here](http://webdriver.io/guide/getstarted/modes.html) for more information.
