### ISSUE TITLE
The event attribute `key` is not set correctly

### ISSUE THREAD

**Issue by AlexandreBonneau** [webdriverio/webdriverio#1829]
## The problem

I'm using webdriver.io to enter keys (via `browser.keys('2');` for instance) into a form input.

I found out that the `event.key` attribute is not correctly populated :
```js
const pureInput = document.querySelector('#myinput');
pureInput.addEventListener('keypress', (e) => { console.warn('keypress: ', e.key, e.keyCode); }, false);
```

Entering `'2'` by hand does result in `e.key === '2'`, while when using webdriver.io, the `e.key` value is not recognized and set to `'Unidentified'`.

That's under Firefox 52.

## Environment

* WebdriverIO version: v4.5.2
* Node.js version: v4.7.2
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): standalone
* if wdio testrunner, running synchronous or asynchronous tests: -
* Additional wdio packages used (if applicable): -

## Code To Reproduce Issue

```html
<input id="myinput" type="text" value="8000">
```
Please see above for the js code.

The test :
```js
const selectors = {
    datInput: '#myinput',
};
fdescribe('the event.key', function() {
    it(`should correctly by set`, function() {
        browser.url(testUrl);

        // Test the initial value
        expect(browser.getValue(selectors.datInput)).toEqual('8000');

        // Focus in that input
        var input = $(selectors.datInput);
        input.click();

        // Change the caret position and modify its value
        browser.keys(['ArrowLeft', 'ArrowLeft']); // 2 left arrows
        browser.keys('2');
        expect(browser.getValue(selectors.datInput)).toEqual('80200');
    });
});
```

**Comment by christian-bromann** [comment]
Can you try a different browser? This is not an issue of WebdriverIO but a bug in the underlying browser driver. WebdriverIO only calls command based on the [Webdriver](https://www.w3.org/TR/webdriver/) protocol. Please file any issue in the geckodriver project. Thanks!
