### ISSUE TITLE
.click() action not always works fine in iOS simulator

### ISSUE THREAD

**Issue by jesusMT** [webdriverio/webdriverio#1830]
## The problem
When I run my tests in Android emulator, everything works fine, but when I run in iOS simulator, .click() action fails at many times.
## Environment

* WebdriverIO version: 4.4.0
* Node.js version: 6.9.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):

## Details
To describe my problem, I'm going to show two examples:
   -  The first example occurs when in my app I try to change the language. For these, I have a radio button with many options, which one with a language, and I want to change from English to Spanish or other language(line 10 custom-actions.js). The problem is that click don't change to other language option, but the response is a 200 OK(line 13 appiumLogs). The test continue but in the next step fails when checks if literals are the same(line 26 testLogs).
  - The second example happens when I want to click in a button (line 3 gb_custom-actions.js). The behaviour its the same that in the first case, but here the test crash immediately because the next button is not visible(line 22 testLogs).

I hope these helps to explain my problem.

Thanks!!

## Link to Selenium/WebdriverIO logs

- First example: https://gist.github.com/jesusMT/989520e60385a7ce5057a860f10e43e4

- Second example:https://gist.github.com/jesusMT/7de094aee6a19852c12a9f4a2add6587

## Code To Reproduce Issue [ Good To Have ]

- First example:https://gist.github.com/jesusMT/516a231e59813bb02786f1e477e57092

- Second example:https://gist.github.com/jesusMT/aeb85139a87a9950b141e655f3ca4dfc

**Comment by christian-bromann** [comment]
@jesusMT 

`still not visible after 2500ms` maybe increase waitfor timeout?

Sorry I have to close this. I don't see any issues with WebdriverIO here. Please join our
[![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for support. Try to use the debug command to see whats going on.

**Comment by jesusMT** [comment]
if you prefer I increase the time to 50000 ms --> https://gist.github.com/jesusMT/6a718d809c4d05b3e9da765220c24f68

Is not a time problem. If i put 50000 or 200000 the result its the same.

**Comment by christian-bromann** [comment]
@jesusMT well in this case your element never became visible

**Comment by jesusMT** [comment]
@christian-bromann my element is perfectly visible in Android and the click() action works correctly in all cases. Why in iOS don't?. Sorry but I don't think that it's a timeout or visibility problem.
