### ISSUE TITLE
Typedefs are missing browser.windowHandleFullscreen()

### ISSUE THREAD

**Issue by bstro** [webdriverio/webdriverio#1833]
## The problem

Attempting to use `browser.windowHandleFullscreen()` in my tests but this method is not recognized by my type definitions (`"webdriverio": "registry:dt/webdriverio#4.5.0+20170118182327"`) and thus my code will not compile.

## Environment

* WebdriverIO version: 
* Node.js version: v6.3.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: async, using async/await
* Additional wdio packages used (if applicable): `wdio-mocha-framework`, `wdio-junit-reporter`

## Details

Typescript compiler error:
```
Property 'windowHandleFullscreen' does not exist on type 'Client<void>
```

**Comment by timbru31** [comment]
Should be available in the Typings by now thanks to @monolithed's PR here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14945

**Comment by christian-bromann** [comment]
👌  perfect. Thanks @monolithed
