### ISSUE TITLE
Getpagesource alter embedded javascript

### ISSUE THREAD

**Issue by mickaelperrin** [webdriverio/webdriverio#1834]
Hi,

I use webdriver.io to run several actions on a test website and export the html page source.

I discovered today that the embedded JavaScript in script tags is altered. For examples, superior and inferior comparators are replaced by html entities `&lt;` and `&gt;`.

Is this a known issue ? Am I missing some configuration ? Does it exist some workaround ?

Thanks

**Comment by christian-bromann** [comment]
@mickaelperrin WebdriverIO just propagates the values it gets from the browser driver. It doesn't do any modifications to the code itself. You can easily search/replace all these entities.
