### ISSUE TITLE
driver.isExisting() always return {state:pending}.

### ISSUE THREAD

**Issue by vercha** [webdriverio/webdriverio#1835]
## The problem

I'm using wedriverio &  mocha to run a local test, the main code is as follows:
before:
driver
.url(url)
.then(setTimeout(done, 90000)); //wait js script execute 

it('IMSDK test'):
console.log(driver.isExisting('.fail'))     //always be {state:pending}   element ‘.fail’ is generated by js script
if(driver.isExisting('.fail')) {     //do something }    //always execute
else{   //do sonmething  }

## Environment

* WebdriverIO version: the latest version
* Node.js version: v4.4.7
* selenium2.53.1 & chromedriver

looking forward to any valuable advice, thanks!

**Comment by christian-bromann** [comment]
@vercha you seem to use WebdriverIO commands in a synchronous way which is only supported using the wdio testrunner. Please see http://webdriver.io/guide/getstarted/modes.html. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by reetou** [comment]
@christian-bromann 
People on gitter didnt have answer for this. Can you please explain it more detailed? I'm trying to make isExisting return false if element doesn't exist, instead it just stuck until mocha timeout hits and throws error.

**Comment by christian-bromann** [comment]
@reetou then please provide a broad problem description (maybe with an reproducible example) instead of some unformatted code snippets 😉

**Comment by worc** [comment]
i'm seeing a similar issue with a `setCookies` call nested inside of an isomorphic-fetch. setting the wdio conf logging output to `command`, i can see that the driver does do a get against a session for the cookie, but it comes back as `{ state: 'pending' }`. i think there might be an issue here with mixing promises in cuke/gherkin steps.

**Comment by christian-bromann** [comment]
@worc again, without an example it is impossible to know what is going on.

**Comment by worc** [comment]
well yeah, and? it's not an easy one to reduce to a bare minimum, but it does seem to exist, and i can at least leave some notes about the situation i've encountered the issue. if this keeps cropping up maybe i'll in the future find a root cause or someone else may find a similar situation.

**Comment by christian-bromann** [comment]
@worc thanks for downvoting my answers. I am not sure how I could improve these. Fact is that unless someone provides a detailed problem description with an reproducible example (if possible) I can't give any support on that matter. Maintaining an open source project of this size requires time and I am not gonna waste that time by trying to find the problem that is bad described in the first place.

Here is again me trying to address the problem: WDIO runs commands synchronously using Fibers. This only works if commands are being executed in the same eventloop as the function (in your case the gherkin step) being executed. This means this example works:

```js
it("should run synchronously", () => {
    browser.url("https://google.com")
    console.log(browser.getTitle()) // outputs "Google"
})
```

but this doesn't:

```js
it("should run synchronously", () => {
    browser.url("https://google.com")
    process.nextTick(() => {
        console.log(browser.getTitle()) // outputs "{ state: 'pending' }"
    })
})
```

There is no scenario where you need to run code in a different event loop. You can call a 3rd library that returns a promise within the `call` command to make this async call synchronous.

Again this is just an assumption if this is the issue you guys are facing. If not please actually describe it. Create a sample repo or help with whatever to illustrate the situation. If you can't do that maybe you need to investigate on your own. That being said there is a limit to what people are willing to help if the issuer is vague with the problem. Just note that if you encounter a bug your are as eligible to provide a fix than I or anyone else is. This is a community project that can be used for free. It can only survive if people sometimes also give back 😉
