### ISSUE TITLE
waitForVisible on MAC uses ES6 and causes strange failures 

### ISSUE THREAD

**Issue by UrbaniseQA** [webdriverio/webdriverio#1836]
## The problem

My tests fail with timeout when I try to waitForVisible on MAC but waitForExist works fine.

## Environment

* WebdriverIO version: 4.6.1
* Node.js version: v6.9.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): WDIO
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): 

    "wdio-allure-reporter": "^0.1.2",
    "wdio-mocha-framework": "^0.5.8",
    "wdio-selenium-standalone-service": "0.0.7",
    "webdriverio": "^4.6.1"

## Details

 Unfortunately the company uses MAC as default dev environment. What I noticed is same test and setup works just fine at home on my WINDOWS machine. After some digging I noticed that the waitForVisible.js on MAC is using ES6 syntax, and the one on WINDOWS is not. waitForExists works fine as it is not using ES6 syntax on both OS`s.

## Link to Selenium/WebdriverIO logs
```
[17:58:28]  INFO	Wait for Dashboard to load
F

0 passing (48.30s)
1 failing

1) New register creation -  Insurance register creation:
Timeout of 30000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.
```

## Code To Reproduce Issue [ Good To Have ]

Just use a waitForVisible with no ES6 support .

The content of waitForVisible.js - 
```js
import { WaitUntilTimeoutError, isTimeoutError } from '../utils/ErrorHandler'


return this.waitUntil(() => {
        return this.isVisible(selector).then((isVisible) => {
            if (!Array.isArray(isVisible)) {
                return isVisible !== reverse
            }

            let result = reverse
            for (let val of isVisible) {
                if (!reverse) {
                    result = result || val
                } else {
                    result = result && val
                }
            }

            return result !== reverse
        })
    }, ms).catch((e) => {
        selector = selector || this.lastResult.selector
```
As I do not use babel lib this code is red in Webstorm :)

**Comment by christian-bromann** [comment]
@UrbaniseQA sorry but the error is not due to es6 code. WebdriverIO gets compiled before it gets pushed to NPM. You are getting that error because your element is indeed not visible.
