### ISSUE TITLE
setValue not use context element selector

### ISSUE THREAD

**Issue by mynoheart** [webdriverio/webdriverio#1837]
## The problem

```setValue``` not use context element selector when result "NoSuchElement"

## Environment

* WebdriverIO version: 4.6.1
* Node.js version: v6.9.1
* Wdio mode
* Running synchronous tests

## Example

page:
```html
<html>
  <head>
    <meta charset="utf-8">
    <title>Test</title>
  </head>
  <body>
    <div id="div1">
      1 without input
    </div>
    <div id="div2">
      2 <input />
    </div>
    <div id="div3">
      3 <input />
    </div>
  </body>
</html>
```

```javascript
browser.$('#div1 input').setValue('value'); // ok, throw error
browser.$('#div2').$('input').setValue('value'); // ok, set value only to input in #div2
browser.$('#div1').$('input').setValue('value'); // wrong, set value to all inputs
```

**Comment by christian-bromann** [comment]
What actually happens when you execute
```js
browser.$('#div1').$('input').setValue('value');
```
?

This should do nothing. SetValue only executes an action on one single element. Only get commands can get you information about multiple elements. Action commands however only do the action one a single command.

**Comment by mynoheart** [comment]
This "value" will be set to all input's in DOM.

**Comment by christian-bromann** [comment]
> This "value" will be set to all input's in DOM.

True

**Comment by mynoheart** [comment]
Yes :-(.
Thanks you very much for beautiful testing instrument.
Feature with sync tests mega super.

**Comment by christian-bromann** [comment]
Fixed issue, will be released with next version.
