### ISSUE TITLE
test.only() function isn't working when using the Mocha TDD interface

### ISSUE THREAD

**Issue by mmcculloch15** [webdriverio/webdriverio#1838]
## The Problem

When using the Mocha TDD UI interface, tests cannot be singled out for execution by using the only() function.

## Environment

* WebdriverIO version: 4.6.1
* Node.js version: 6.6.0
* [Standalone mode or wdio testrunner] wdio
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): 

## Details

Only the TDD UI seems to be affected.  I can use the BDD interface and execute a single test with it.only(). 

## Code To Reproduce Issue [ Good To Have ]

Gist: https://gist.github.com/mmcculloch15/9d03692de1536c0d72166fbee155835c

**Comment by christian-bromann** [comment]
@mmcculloch15 I was not able to reproduce this. I downloaded the gist and ran it with success. Please let me know if you have any more information. I would be happy to reopen this issue if it turns out to be a bug in WebdriverIO.
