### ISSUE TITLE
getText and PhantomJS sometimes not working

### ISSUE THREAD

**Issue by domgolonka** [webdriverio/webdriverio#1840]
Hello, I used chrome and getText was working fine. I tried using it on PhantomJS and sometimes it doesn't get the text.

> [17:51:18]  RESULT		[{"ELEMENT":":wdc:1485276678098"}]
 [17:51:18]  COMMAND	GET 	 "/wd/hub/session/52e97d30-e255-11e6-aebd-    8153ecfed322/element/:wdc:1485276678098/text"
 [17:51:18]  DATA		{}
 [17:51:18]  COMMAND	POST 	 "/wd/hub/session/52e97d30-e255-11e6-aebd-8153ecfed322/element"
 [17:51:18]  DATA		{"using":"css selector","value":"[data-index=\"undefined\"]"}

My code: 
`.waitForExist('#divVerifyPics', 3000)
            .setValue('#Password', password)
            .waitForExist('#spanVerifyName', 3000)
            .getText('#spanVerifyName').then(function (cap) {
            return captcha(cap);`

I've set for it to wait for #spanVerifyName but it sometimes doesn't find it. Outputs a undefined.

**Comment by christian-bromann** [comment]
I don't think this is an WebdriverIO issue. Look at the selector you've passed in: `[data-index="undefined"]`. I would recommend to use the [wdio testrunner](http://webdriver.io/guide.html#Let’s-get-serious) to get rid of promise based command execution as it might be some kind of racing condition that is failing the test.
