### ISSUE TITLE
Deprecate jsonwire command

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#1841]
## The problem

The keys protocol command is not part of the Webdriver spec and should be removed. It already is not supported by Geckodriver anymore, throwing an error:

> keys did not match a known command

Let's throw a more meaningful error for 4.7.x and completely remove it `v4.8.x`

**Comment by monolithed** [comment]
> The keys protocol command is not part of the Webdriver spec and should be removed

Let's remove other commands are not part of the Webdriver spec. 😄  

> Let's throw a more meaningful error for 4.7.x

Did you mean warning?

> and completely remove it v4.8.x

If you know, the `keys` is a native event and cannot be implemented using `EventTarget.dispatchEvent`. 
We cannot emulate user input (try to create an element with `contenteditable="true"` and call `dispatchEvent` with Enter code, then press or call the `key` command and compare your results).

What is the alternative? If [Action#SendKeys](https://www.w3.org/TR/webdriver/#dfn-element-send-keys) I don't think so, because the Actions end point has not been implemented in SafariDriver and [GekoDriver / Marionette](https://github.com/mozilla/geckodriver/issues/159) yet. ☹️

**Comment by christian-bromann** [comment]
> Let's remove other commands are not part of the Webdriver spec.

Agree, I would even say let's make a majore release (v5) that only supports Webdriver commands defined in the spec. For that we need to wait until it is finalised which happens when at least two driver have implemented it.

> Did you mean warning?

Yeah

> What is the alternative? If Action#SendKeys I don't think so, because the Actions end point has not been implemented in SafariDriver and GekoDriver / Marionette yet.

I guess this is the alternative.

**Comment by christian-bromann** [comment]
Let's extend this task to deprecate all jsonwire commands.

**Comment by monolithed** [comment]
There is another problem:

```html
<div class="foo">
   <div class="bar"> text </div>
</div>

<div class="bar"> text </div>
```

```js
let element = this.page.element('.foo');
     element = this.page.elementIdElement(element.value.ELEMENT, '.bar');

element.getText(); // ['text', 'text']
```

I hate these variations and bugs.

**Comment by christian-bromann** [comment]
> There is another problem:

Please explain your problem. It makes it easier and faster for me to understand. Also it seems to be unrelated to this issue.

> I hate these variations and bugs.

There always will be bugs 😉  important is to fix them instead of complain about them.

**Comment by monolithed** [comment]
> Please explain your problem. It makes it easier and faster for me to understand. Also it seems to be unrelated to this issue

**Actual**

```js
element.getText(); // ['text', 'text']
```

**Expected**

```js
element.getText(); // 'text'
```

It's expected because the element variable returns `.foo .bar`, but used `.bar`.
Why not provide `getAllTexts` if it's expected?

>  important is to fix them instead of complain about them.

Yep, we should stay on one interface, I mean all the commands should provide a single way to do something. If I use `getText`, I want to see a text value, not `string[]` or `null`.... 
If I use the `getAttribute` method to check some attribute I expect to see `null` for elements without that attribute:

```js
<input type="ckeckbox" />
```

```js
browser.click('[type=checkbox]'); // checked
browser.isSelected('[type=checkbox]'); // true
browser.getAttribute('[type=checkbox]'); // "true", but it's not true, because there is no the `checked` attribute on the current element, there is only a property
````

```js
browser.click('[type=checkbox]'); 
browser.leftClick('[type=checkbox]'); 
browser.element('[type=checkbox]').click();
browser.element('[type=checkbox]').leftClick();
browser.element('[type=checkbox]').elementIdClick();
browser.elementIdClick(browser.element('[type=checkbox]').value.ELEMENT)
```

Why should we keep all these variations? 

So, I propose to make a new interface for all the methods. It's the only way
to provide some understanding of the current API.  The problem is I get tired to fix these moments in our tests for other developers. That's why we have started to write our tests in TypeScript...

BTW: Have you seen my [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14945/files) :)

**Comment by christian-bromann** [comment]
With version 5 we will remove all jsonwire commands that are not part of the Webdriver protocol. Again: the problem you are pointing out has nothing to do with the this issue.

**Comment by monolithed** [comment]
I hope, because we need it 👍

**Comment by timfish** [comment]
Once `keys` is removed, will there be any way to test key + click interactions?

**Comment by monolithed** [comment]
We cannot emulate user input as a native event, so wait for a new interface Actions

**Comment by k03mad** [comment]
Is there any alternative to `moveToObject()`?
We rewrote many tests due to deprecated commands, but we can't figure out how to easy test hover without this method.

For example: test for element that changes color on hover (now: move to object and wait for expected CSS property color).

**Comment by monolithed** [comment]
It will be implemented via `Action.pointerMove`

**Comment by megamindbrian** [comment]
Amazing work guys, thank you for looking in to this!

**Comment by acailly** [comment]
I made a polyfill based on this comment: https://github.com/SeleniumHQ/selenium/issues/3693#issuecomment-297212540

It is not battle tested but will do the work for my case until the official implementation.

```JavaScript
                //browser.keys(barcodeArray)
		/*
			browser.keys is part of the JSON wire protocol but not of the W3C Webdriver spec.
			Since Geckodriver (used in firefox) is only W3C compliant, we can not use browser.keys anymore.
			
			The issue has been raised here: https://github.com/webdriverio/webdriverio/issues/1841.
			At the time of writing these lines, there is no available implementation. 
			Future implementation will probably be based on https://www.w3.org/TR/webdriver/#dfn-element-send-keys.

			The code above is a polyfill to simulate key events client side.
			It is inspired by:
			- https://github.com/SeleniumHQ/selenium/issues/3693#issuecomment-297212540	
			- https://github.com/webdriverio/webdriverio/blob/master/lib/protocol/keys.js
		 */		
		browser.execute(function(value){
			
			/*
				Trigger a keyboard event 

				Note we purposely use generic 'Events' instead of 'KeyboardEvents' because it is not well supported on chrome.
				See:
				- https://stackoverflow.com/questions/8942678/keyboardevent-in-chrome-keycode-is-0/12522752#12522752
				- http://output.jsbin.com/awenaq/3
			 */
			function triggerKeyboardEvent(el, keyCode, eventType)
			{
				const eventObj = document.createEventObject ?
					document.createEventObject() : document.createEvent('Events');

				if(eventObj.initEvent){
					eventObj.initEvent(eventType, true, true);
				}
			
				eventObj.keyCode = keyCode;
				eventObj.which = keyCode;
				
				el.dispatchEvent ? el.dispatchEvent(eventObj) : el.fireEvent('on' + eventType, eventObj); 
			}

			//Simulate pressing a key 
			function simulateKey(keyCode)
			{
				triggerKeyboardEvent(document, keyCode, 'keydown')
				triggerKeyboardEvent(document, keyCode, 'keypress')
				triggerKeyboardEvent(document, keyCode, 'keyup')			  
			} 

			/**
			 * Characters types
			 * https://www.w3.org/TR/2013/WD-webdriver-20130117/#character-types
			 * https://developer.mozilla.org/fr/docs/Web/API/KeyboardEvent/keyCode#Constants_for_keyCode_value
			 */
			const KEY_CODES = {
				// 'NULL'
				// 'Unidentified'
				'Cancel': 3,
				'Help': 6,
				'Back space': 8,
				'Backspace': 8,
				'Tab': 9,
				'Clear': 12,
				'Return': 13,
				'Enter': 13,
				'Shift': 16,
				'Control': 17,
				'Alt': 18,
				'Pause': 19,
				'Escape': 27,
				'Space': 32,
				' ': 32,
				'Pageup': 33,
				'PageUp': 33,
				'Page_Up': 33,
				'Pagedown': 34,
				'PageDown': 34,
				'Page_Down': 34,
				'End': 35,
				'Home': 36,
				'Left arrow': 37,
				'Arrow_Left': 37,
				'ArrowLeft': 37,
				'Up arrow': 38,
				'Arrow_Up': 38,
				'ArrowUp': 38,
				'Right arrow': 39,
				'Arrow_Right': 39,
				'ArrowRight': 39,
				'Down arrow': 40,
				'Arrow_Down': 40,
				'ArrowDown': 40,
				'Insert': 45,
				'Delete': 46,
				'Semicolon': 59,
				'Equals': 61,
				'Numpad 0': 96,
				'Numpad 1': 97,
				'Numpad 2': 98,
				'Numpad 3': 99,
				'Numpad 4': 100,
				'Numpad 5': 101,
				'Numpad 6': 102,
				'Numpad 7': 103,
				'Numpad 8': 104,
				'Numpad 9': 105,
				'Multiply': 106,
				'Add': 107,
				'Separator': 108,
				'Subtract': 109,
				'Decimal': 110,
				'Divide': 111,
				'F1': 112,
				'F2': 113,
				'F3': 114,
				'F4': 115,
				'F5': 116,
				'F6': 117,
				'F7': 118,
				'F8': 119,
				'F9': 120,
				'F10': 121,
				'F11': 122,
				'F12': 123,
				'Command': 224,
				'Meta': 224
				// 'Zenkaku_Hankaku'
				// 'ZenkakuHankaku'
			};
			
			function getKeyCode (value) {
				return KEY_CODES.hasOwnProperty(value) ? [KEY_CODES[value]] : value.split('').map(v => v.charCodeAt(0))
			}

			let keyCodes = []
			if (typeof value === 'string') {
				keyCodes = getKeyCode(value)
			} else if (value instanceof Array) {
				for (let charSet of value) {
					keyCodes = keyCodes.concat(getKeyCode(charSet))
				}
			} else {
				throw new Error('number or type of arguments don\'t agree with keys protocol command')
			}

			for(let keyCode of keyCodes){
				simulateKey(keyCode)
			}
		}, barcodeArray)
```

**Comment by christian-bromann** [comment]
We will still support the jsonwire protocol moving forward. Closing.
