### ISSUE TITLE
isVisibleWithinViewport returned array of values

### ISSUE THREAD

**Issue by mynoheart** [webdriverio/webdriverio#1843]
## The problem

```isVisibleWithinViewport``` if selector returned one element, then ok.
But if multiple then array of values.

## Environment

* WebdriverIO version: 4.6.1
* Node.js version: v6.9.1
* Wdio mode
* Running synchronous tests

## Example
```javascript
browser.$('body').isVisibleWithinViewport(); // ok, true
browser.$('div').isVisibleWithinViewport(); // [true, true, true ...]
```

**Comment by christian-bromann** [comment]
This is expected. See also #1762

**Comment by mynoheart** [comment]
Thanks.
