### ISSUE TITLE
Trigger the debug repl via a signal (e.g. ctrl-c but not) during a test

### ISSUE THREAD

**Issue by tiffon** [webdriverio/webdriverio#1848]
## The problem

This is not a problem, it is a feature request / suggestion. Let me know if there is a better channel for a suggestion like this.

## Environment

* WebdriverIO version: **4.5.0**
* Node.js version: **v6.7.0**
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): **wdio**
* if wdio testrunner, running synchronous or asynchronous tests: **synchronous**
* Additional wdio packages used (if applicable): 
  * wdio-jasmine-framework@0.2.10
  * wdio-sync@0.6.1
  * wdio-junit-reporter@0.1.0
  * wdio-spec-reporter@0.0.3
  * wdio-dot-reporter@0.0.6

## Details

Suggestion is to be able to interrupt the current spec (maybe only works in non-parallel test runs?) and trigger the debug repl. Maybe the interrupt can be via a keyboard escape sequence to send a signal, or, basically anything along those lines. This would be infinitely handy when debugging a test.

## Link to Selenium/WebdriverIO logs

N/A

## Code To Reproduce Issue [ Good To Have ]

N/A

**Comment by christian-bromann** [comment]
Interesting idea. I doubt we can use ctrl+c for that tho

**Comment by tiffon** [comment]
@christian-bromann lol, yeah, definitely not ctrl-c, but one of those POSIX signals might fit the bill :)

**Comment by christian-bromann** [comment]
I was able to get this running within the afterCommand hook. You can make your own service or have this in your wdio.config:

```js
// wdio.conf.js

var readline = require('readline')
var hasTriggered = false

exports.config = {
    // ...
    afterCommand: () => {
        readline.emitKeypressEvents(process.stdin)
        process.stdin.setRawMode(true)
        process.stdin.on('keypress', (str, key) => {
            if (str !== 'd') {
                return
            }
            hasTriggered = true
        })

        if (hasTriggered) {
            browser.debug()
        }

        hasTriggered = false
    },
    // ...
}
```

**Comment by tiffon** [comment]
Awesome, thanks!
