### ISSUE TITLE
How to set browser window size?

### ISSUE THREAD

**Issue by akulov** [webdriverio/webdriverio#185]
newWindow ( url, windowName, windowFeatures, callback(err) ) , right?
windowFeatures
String
features of opened window (e.g. size, position, scrollbars, etc.)

How exactly set width=1280 and height=800?

**Comment by chrisbenseler** [comment]
Is it possible to set this configuration in the wdio.conf.js file?

**Comment by christian-bromann** [comment]
> Is it possible to set this configuration in the wdio.conf.js file?

Not that I am aware of. Possible that some drivers allow to set this parameter tho

**Comment by chrisbenseler** [comment]
@christian-bromann I  forget to comment here that I could do this, using the before's callback function

```
before: function (capabilities, specs) {
   browser.windowHandleSize({width: 1600, height: 768})
}
```

**Comment by Deepaksgithub** [comment]
browser.windowHandleSize({width:1280,height:800});

not working chrome version 62 and chrome driver version 34

**Comment by dudziakm** [comment]
It works perfect:
browser.setWindowSize(1920, 1080);
