### ISSUE TITLE
Change the browser language automatically

### ISSUE THREAD

**Issue by rcalabro** [webdriverio/webdriverio#1851]
Hi,

Is there any way to change the browser language automatically?

i.e. I want to test if my localized application is loading the correct content according to browser language.

Thanks,
Renato Calabro

**Comment by christian-bromann** [comment]
> Is there any way to change the browser language automatically?

I guess not. This has to be set when the browser spawns (so probably in the capabilities). In Chrome you might be able to switch it in the settings tho. Feel free to join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
