### ISSUE TITLE
browser.element(selector).hasFocus() executes with null args and returns always false

### ISSUE THREAD

**Issue by marekj** [webdriverio/webdriverio#1853]
## The problem

```cucumber
Given an input element text field that has focus on the page
When I execute `browser.hasFocus(selector) for that element
Then I receive true as expected
But when I execute `browser.element(selector).hasFocus()` command form
Then I receive false instead (unexpected)
```

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 6.9.4
* Both Standalone mode AND wdio testrunner (sync and async)
* Additional wdio packages used (if applicable): `wdio-mocha-framework`

## Details

tests for repro here:
https://gist.github.com/marekj/81c89e3d30ff5505e656b0bf603ab8de

See selenium logs. 
Notice the payload inclues `"args":["#review-email"]` selector when using a form of `browser.hasFocus(selector)`
In case of `browser.element(selector).hasFocus()` the selector is null `"args":[null]` and we get false back

## Link to Selenium/WebdriverIO logs

https://gist.github.com/marekj/81c89e3d30ff5505e656b0bf603ab8de#file-selenium-log

## Code To Reproduce Issue [ Good To Have ]

https://gist.github.com/marekj/81c89e3d30ff5505e656b0bf603ab8de

`npm i && npm test`

**Comment by christian-bromann** [comment]
Let's continue convo in #1855
