### ISSUE TITLE
alertDismiss crashes browser for alerts

### ISSUE THREAD

**Issue by thawk55** [webdriverio/webdriverio#1854]
## The problem

When the browser has an alert displayed, running `browser.alertDismiss()` crashes the browser instead of clicking 'ok'. 

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 5.6.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Standalone
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):

## Details

Using chrome as the test browser

## Code To Reproduce Issue [ Good To Have ]

```
var js = function(){
  window.alert('an alert');
};

browser.execute(js).then(function(){
  browser.alertDismiss();
//Browser crashes
});
```

**Comment by christian-bromann** [comment]
@thawk55 thanks for submitting the issue. I was able to reproduce this. However this can't be fixed in WebdriverIO and has to be tackled in the browser driver (e.g. chromedriver).

**Comment by thawk55** [comment]
@christian-bromann I figured that could be the case. Thanks for looking at it though.
