### ISSUE TITLE
webdriverio seems not working

### ISSUE THREAD

**Issue by pavel06081991** [webdriverio/webdriverio#1859]
It is my first time when I use webdriverio. I used code from your documentation:

```
var webdriverio = require('webdriverio');
var options = { desiredCapabilities: { browserName: 'chrome' } };
var client = webdriverio.remote(options);
client
    .init()
    .url('https://duckduckgo.com/')
    .setValue('#search_form_input_homepage', 'WebdriverIO')
    .click('#search_button_homepage')
    .getTitle().then(function(title) {
        console.log('Title is: ' + title);
        // outputs: "Title is: WebdriverIO (Software) at DuckDuckGo"
    })
    .end();
```
But nothing happens. Chrome browser is not opened and I see nothing in console. I also tried firefox, but the same result.
I'm using windows 8, node v6.5.0, npm v4.1.2

**Comment by christian-bromann** [comment]
@pavel06081991 make sure you have a selenium standalone server running. Check out this step by step tutorial: http://webdriver.io/guide.html

Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
