### ISSUE TITLE
How to get global browser object?

### ISSUE THREAD

**Issue by anupmanekar** [webdriverio/webdriverio#1860]
## The problem
I am not using wdio test runner but gauge bdd tool. As I understand from docs, global browser object is only available in wdio test runner. Is there any other way to get this object? The problem is I am creating page objects and need to maintain global browser instance so as to construct page objects with that browser. But if this is available, maintenance of global browser will not be required.

**Comment by christian-bromann** [comment]
I don't know how the gauge bdd tool integrates WebdriverIO. The browser object is a WebdriverIO instance. The wdio testrunner assigns that instance to the global scope so it is available in the spec files. You should ask the gauge bdd tool contributors how to access the WebdriverIO instance. 
Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
