### ISSUE TITLE
Unable to determine the orientation of the iOS application under test

### ISSUE THREAD

**Issue by pathriks** [webdriverio/webdriverio#1861]
Hi, 

I am trying to retrieve the orientation of an iOS application under test using the WebDriverIO test scripts. _(The application under test is expected to remain in PORTRAIT mode though the device is rotated to LANDSCAPE mode.)_
I am setting the device to LANDSCAPE mode using the _browser.setOrientation_ API. However, there are no specific APIs to retrieve the application orientation, the _browser.orientation_ and _browser.getOrientation_ APIs return the device orientation(LANDSCAPE) though the application is still in PORTRAIT mode.

`/**************************************************************/`
`...`
`browser.setOrientation('LANDSCAPE');`
`browser.orientation(); //Returns 'LANDSCAPE'`
`...`
`/**************************************************************/`

I tried calling Instruments API in the test script as shown below. However, this does not return the expected result and simply returns the Instruments API itself. 

`/**************************************************************/`
`...`
`browser.setOrientation('LANDSCAPE');`
`browser.orientation(); //Returns 'LANDSCAPE'`
`var res=browser.execute(function (){`
` return 'UIATarget.localTarget().frontMostApp().interfaceOrientation()'; //This line retrieves the application orientation appropriately when run on Instruments console`
`});`
`...`
`/**************************************************************/`

I am unable to get this working using the _browser.execute_, _browser.executeAsync_ or _browser.call_ APIs. Is there anyway to either retrieve the front most application's orientation details or inject the Instruments code in the test script?
Could you please let me know if there is any simplest way in retrieving the application orientation that I have been overlooking?

## Environment
* WebdriverIO version: v4.2.1
* Node.js version: v6.3.0
* iOS : 9.3
* XCode : 7.3.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: Synchronous tests
* Additional wdio packages used (if applicable): None

**Comment by christian-bromann** [comment]
> However, there are no specific APIs to retrieve the application orientation

This can't be fixed in WebdriverIO. Please create an issue in the Appium project.

**Comment by pathriks** [comment]
@christian-bromann 

> > However, there are no specific APIs to retrieve the application orientation

> This can't be fixed in WebdriverIO. Please create an issue in the Appium project.

I understand this cannot be fixed in WebdriverIO currently. 
Would you please let me know if there is a way to inject the Instruments code in the WebdriverIO based test script?

**Comment by christian-bromann** [comment]
I am not sure if you can execute Instruments code with Selenium, I doubt it. You should ask the Appium people.

**Comment by pathriks** [comment]
@christian-bromann 
Thank you. However, I have used Appium Java clients where in, we inject this kind of Instruments based snippets directly in our test scripts for scrolling elements. Hence, I asked if such a thing is possible in WebdriverIO. 

```
/**************************/
...
driver.executeScript("var target = UIATarget.localTarget(); target.frontMostApp().mainWindow().scrollViews()[0].webViews()[0].dragInsideWithOptions({startOffset:{x:0.39, y:0.00}, endOffset:{x:0.60, y:0.00}});");
...
/**************************/
```

If you have any update on this, please do let me know here. 
However, I will also raise a support request in Appium forums.
Thanks.

**Comment by christian-bromann** [comment]
If you can run this in Java you should be able to run it in WebdriverIO too with `browser.execute`.

**Comment by pathriks** [comment]
Great!! Thanks for the update.
I tried and currently seeing this error, I will work on it and update here if I find a fix. 
If you found anything that is obviously causing this error that would fix, please let me know.

## **Code:**
```
browser.execute("var target = UIATarget.localTarget(); target.frontMostApp().interfaceOrientation();");
```


## **Error Log:**
```
Error: Can't find variable: UIATarget (status: 13)
    at execute("var target = UIATarget.localTarget(); target.frontMostApp().interfaceOrientation();")

```

**Comment by christian-bromann** [comment]
@pathriks this probably will only work in native context, so make sure to switch to that

**Comment by pathriks** [comment]
@christian-bromann Thanks! That was such an overlook from my side. It did work when I switched to native view.
