### ISSUE TITLE
Revert Enter for browser.debug

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1863]
It would be nice to replace Ctrl+C with Enter for `browser.debug()`. 
First of all, it's needed for backwards compatibility. The second reason is a usability issue. After these changes we can not use Grunt and other tasks managers, because of `Ctrl+C === process.exit`.

**Comment by christian-bromann** [comment]
> First of all, it's needed for backwards compatibility.

This doesn't really break your test. `browser.debug` opens a repl interface where you use Enter to submit your command call.

> The second reason is a usability issue. After these changes we can not use Grunt and other tasks managers, because of Ctrl+C === process.exit.

That's why you can enter `.exit` as well to close the repl.

**Comment by monolithed** [comment]
> That's why you can enter .exit as well to close the repl.

@christian-bromann, what do you think about some correction:
`(To exit, press ^C again or type .exit)`  -> `(To continue, press ^C again or type next)` ?

`next` is a standard name for similar commands in [gbd](http://ftp.gnu.org/pub/old-gnu/Manuals/gdb/html_node/gdb_37.html), [node](https://nodejs.org/api/debugger.html#debugger_command_reference) an so on.

**Comment by christian-bromann** [comment]
> next [count]
> Continue to the next source line in the current (innermost) stack frame.

This doesn't really reflect what happens. I think `.exit` is a good label to "exit" the repl
