### ISSUE TITLE
The forked child processes are not closed correctly

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1865]
The problem is that forked child processes are not closed correctly when parent was killed. Also I see these zombie processes eternally on my servers (unfortunately, this problem affects me not only locally).

The screencast:

![swidpgvysa](https://cloud.githubusercontent.com/assets/803674/22793663/81e5cea0-ef01-11e6-9416-e1af084abff5.gif)

I have tried to make a fix before, but I had failed  :(

**Comment by christian-bromann** [comment]
To fix the issue we need to tell the launcher to not spawn any new processes after CTRL+C was emitted

**Comment by monolithed** [comment]
@christian-broman, I've already tried something like:

```js
    startInstance (specs, caps, cid, server) {
            if (this.hasTriggeredExitRoutine) {
                return
            }
```

The same result (

**Comment by christian-bromann** [comment]
@monolithed actually your solution should fix the problem
