### ISSUE TITLE
Flaky test not being rerun using Jasmine

### ISSUE THREAD

**Issue by andrewheppner** [webdriverio/webdriverio#1866]
We are trying to have our flaky tests rerun if they fail in our test suite, but to date we have not been able to get this going. Is this not supported in standalone mode?

an example test would be:

```
it('Can switch between the two tabs', function() {
			testUtils.click('.nav-tabs li:last-child');
			testUtils.expectIsVisible('.tab-pane [data-test="transactionsPanel"]');

			testUtils.click('.nav-tabs li:first-child');
			testUtils.expectIsVisible('.tab-pane [data-test="overviewChart"]', true);
	}, 3);
```

if we set an assertion say from true to false in order to get a failure, we are not seeing this test run again.

We are running this using gulp:

gulpfile.js
```
var gulp = require('gulp');
var selenium = require('selenium-standalone');
var webdriver = require('gulp-webdriver');
var shell = require('gulp-shell');

var httpServer, seleniumServer;

gulp.task('symlink', shell.task([
  'cd node_modules ; rm -rf tests; ln -s ../tests tests ; cd ..'
]));

gulp.task('selenium', function (done) {
  selenium.install({logger: console.log}, function () {
    selenium.start(function (err, child) {
      if (err) { return done(err); }
      seleniumServer = child;
      done();
    });
  });
});

gulp.task('e2e', ['selenium'], function () {
  return gulp.src('wdio.jasmine.conf.js')
    .pipe(webdriver()).on('error', function () {
      seleniumServer.kill();
      process.exit(1);
    });
});

gulp.task('test', ['symlink', 'e2e'], function () {
  seleniumServer.kill();
});
```
Here is our package.json
`  "devDependencies": {
    "babel-eslint": "6.0.0",
    "eslint": "2.5.3",
    "gulp": "3.9.1",
    "gulp-shell": "^0.5.2",
    "gulp-webdriver": "2.0.1",
    "jasmine": "2.4.1",
    "lodash": "^4.16.6",
    "moment": "^2.16.0",
    "request": "^2.78.0",
    "selenium-standalone": "5.8.0",
    "tap": "5.7.0",
    "tape": "4.5.1",
    "wdio-jasmine-framework": "^0.2.19",
    "webdriverio": "^4.6.2"
  }
}`

here is our wdio.jasmine.conf
`exports.config = {

	/**
	* server configurations
	*/
	host: '0.0.0.0',
	port: 4444,

	/**
	* specify test files
    * Create a file next to wdio.jasmine.conf.js named testPath.js
    * in testPath.js,
    * module.exports = [
	*  // file path here
    * ];
	*/
	specs: testPath,

	/**
	* capabilities
	*/
	capabilities: [{
		browserName: 'chrome',
	}],

	/**
	* test configurations
	*/
	logLevel: 'silent',
	coloredLogs: true,
	screenshotPath: 'shots',
	baseUrl: '<testURL>',
	waitforTimeout: 30000,
	framework: 'jasmine',
	maxInstances: 1,
	reporter: 'spec',
	reporterOptions: {
		outputDir: './'
	},

	jasmineNodeOpts: {
		defaultTimeoutInterval: 9999999
	},

	/**
	* hooks
	*/
	onPrepare: function() {
		console.log('let\'s start');
	},
	onComplete: function() {
		console.log('that\'s it');
	}

};`

* WebdriverIO version: 4.6.2
* Node.js version: 4.6
* Standalone Mode

Any help would be greatly appreciated.

**Comment by christian-bromann** [comment]
Not reproducible. You are saying that you are using `Standalone Mode` but you have defined a gulp-webdriver task which uses wdio testrunner. However I was not able to reproduce this. Please send me a mini project that demonstrates this behavior.

**Comment by andrewheppner** [comment]
Sorry you are right. I was confused. I am definitely using the test runner.
