### ISSUE TITLE
element.waitForExist(selector) returns true even if the selector does not exist on the element

### ISSUE THREAD

**Issue by macrozone** [webdriverio/webdriverio#1869]
I have this situation:

```
const sideMenu = browser.element("#mainNav);
console.log(sideMenu.isExisting(), sideMenu.isExisting("a[href='/de/profile']"));
console.log(sideMenu.waitForExist(), sideMenu.waitForExist("a[href='/de/profile']"));
```

Given that #mainNav exists and does not contain a link /de/profile i would expect webdriver to log

```
true, false

true, false
```

but instead it logs
```
true, false

true, true
```

So I assume that element.waitForExist does ignore the given selector
 
chimp 0.47.1

**Comment by christian-bromann** [comment]
@macrozone thanks for submitting the issue. I fixed the bug and will release it with the next version.
