### ISSUE TITLE
Is it possible to use multiple --tags arguments when running Cucumber?

### ISSUE THREAD

**Issue by D7Torres** [webdriverio/webdriverio#1871]
I am using an `cucumberOpts` in my configuration file, one of its properties is `tags`.

In Cucumber you can use
* `cucumber --tags @one,@two` which will run the scenarios with tags @one AND @two 
* `cucumber --tags @one --tags @two` which will run the scenarios with tags @one OR @two 

However, using a `cucumberOpts` object with the property `tags` I am not able of specifying more than one set of tags, so the second case cannot be done.

Is this perhaps a feature not supported by webdriverIO?

**Comment by broder** [comment]
I think your logic is the wrong way round https://github.com/cucumber/cucumber/wiki/Tags

- `cucumber --tags @one,@two` corresponds to OR
- `cucumber --tags @one --tags @two` corresponds to AND

**Comment by christian-bromann** [comment]
yup, looks like it:

```
cucumber --tags @billing --tags @important    # Runs the first scenario (Scenarios with @important AND @billing)
cucumber --tags @billing,@important           # Runs both scenarios (Scenarios with @important OR @billing)
```

Closing.
