### ISSUE TITLE
Running tests is not dependent on key --suite

### ISSUE THREAD

**Issue by demshin** [webdriverio/webdriverio#1872]
## The problem

I'm runing tests with wdio (also cucumber) with key --suite nameOfSuite, but all tests run.

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 6.9.5
* I run test via gulp `gulp test:remote --maxinstances 10 --suite nameOfSuite`
* it's running on remote grid
* I'm using allure report

## Details
there is part of my wdio.conf.js:
`exports.config = {

    host: argv.seleniumhost || '10.241.5.140',
    port: 4444,
    path: '/wd/hub',
    
    specs: [
        './features/**/*.feature'
    ],
    suites: {

        regression: [
            './features/nsi/kpgz-spgz/*.feature',
            './features/bktz/libcontract/*.feature',
            './features/nsi/participant/*.feature',
            './features/nsi/reference/*.feature',
            './features/normalization/*.feature',
            './features/comission/*.feature'
        ],
        scrum: [
            './features/scrum/**/*.feature'
        ],
        nsi: [
            './features/nsi/kpgz-spgz/*.feature',
            './features/nsi/participant/*.feature',
            './features/nsi/reference/*.feature'
        ],
        bktz: [
            './features/bktz/libcontract/*.feature',
            './features/bktz/criteria/*.feature'
        ],
        normalization: [
            './features/normalization/*.feature'
        ],
        comission: [
            './features/comission/*.feature'
        ]

    }`

If you need more information I will provide.

**Comment by christian-bromann** [comment]
What if you try
```sh
$ gulp test:remote -- --maxinstances 10 --suite nameOfSuite
```
?

**Comment by demshin** [comment]
Than I have `Task '--maxinstances' is not in your gulpfile` at stacktrace.

**Comment by christian-bromann** [comment]
This issue was moved to webdriverio/gulp-webdriver#60
