### ISSUE TITLE
Is there any way to reset iOS App in each test case execution?

### ISSUE THREAD

**Issue by davidrova** [webdriverio/webdriverio#1875]
## The problem

I would like to execute each test case as it would be the first access.

It is very easy in Android, using browser.reset(); but it doesn't work in iOS

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 6.2.2
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): standalone mode
* if wdio testrunner, running synchronous or asynchronous tests: N/A
* Additional wdio packages used (if applicable): N/A

## Details

I would like to reset iOS application in each scenario execution.

Tries:
- browser.closeApp().init(capabilities)
- browser.end().init(capabilities)
- noReset = false + fullReset = true

## Link to Selenium/WebdriverIO logs

N/A

## Code To Reproduce Issue [ Good To Have ]

N/A

**Comment by davidrova** [comment]
I have tried a new workaround with no sucess. In the After hook (I have tried in the Before hook too):

* Stop booted simulator --> xcrun simctl shutdown 5F102939-BDD7-40DF-9957-91ACC0A3A814
* Reset simulator's data and content --> xcrun simctl erase 5F102939-BDD7-40DF-9957-91ACC0A3A814
* Restart webdriverIO
             ...
               this.driver = remote(config.runner.plugins.webdriverio.config);
              this.driver.init()
             ....

**Comment by christian-bromann** [comment]
@davidrova can you ask in the Appium community? This is out of scope of WebdriverIO. If the [ios driver](https://github.com/appium/appium-ios-simulator) supports this kind of action then I would be happy to add the command but I almost believe that iOS doesn't support this kind of action at all.

**Comment by davidrova** [comment]
@christian-bromann thanks for your answer. 

I have tried to reinstall the app with ximctl commands with no success. 
       xcrun simctl uninstall 5F102939-BDD7-40DF-9957-91ACC0A3A814 myApp
       xcrun simctl install 5F102939-BDD7-40DF-9957-91ACC0A3A814 path-to-my-app

Regards,
