### ISSUE TITLE
Possibility to add custom find element strategy

### ISSUE THREAD

**Issue by yurii-sorokin** [webdriverio/webdriverio#1877]
## The feature

Possibility to add custom find element strategy

## Environment

* WebdriverIO version: 4.6.2

## Details

We use custom data attributes for every element we need to test. So we write something like `browser.getText('[data-test-id="some-id"]')` for each element under test. Would be nice to have possibility to extend find strategy so you can create shorthands for repeatedly used selectors, e.g. `browser.getText('@some-id')`

**Comment by WillBrock** [comment]
I disagree. There is not a built in way for css selectors to do this and the effort is minimal. 

How do you propose that you declare the custom attribute?

Closing since it's two years old.
