### ISSUE TITLE
Elements counter

### ISSUE THREAD

**Issue by iSpid3r** [webdriverio/webdriverio#1878]
Hi @christian-bromann 

I need to count the number of elements on the page, but in response I keep getting { state: 'pending' }

I tried to do this in two ways, but the result is the same:

`var constr = browser.elements('.construction', function(err, res) {
    return res.value.length;
});
console.log(constr);`

and

`var constr = browser.execute(function() {
    var construct = $('.construction');
    return construct.length;
});
console.log(constr);`

What is the problem?

**Comment by mattc41190** [comment]
constr is a promise object in a pending state.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

Are you running WDIO standalone or in the runner?

If you are running standalone the follwoing may work:

```
browser.elements('.construction', function(err, res) { return res.value.length; })
.then( function(result){
 console.log(result)
})
```

**Comment by christian-bromann** [comment]
Thanks @mattc41190

**Comment by christian-bromann** [comment]
@iSpid3r feel free to join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
