### ISSUE TITLE
When used with $$, getHTML always acts on the entire array, even when a single element is specified

### ISSUE THREAD

**Issue by ianrenauld** [webdriverio/webdriverio#1879]
When used with $$, getHTML always acts on the entire list, even when only one element has been specified.

`$$('some-selector')[2].getHTML()` gets the HTML in an array for all items matching `'some-selector'` instead of only the element at position 2.  Same command with `getText()` instead works only on the item at position 2, which is the proper behavior according to the API documentation.

**Environment**

* WebdriverIO version: 4.6.2
* Node.js version: 6.7.0
* wdio testrunner in Synchronous mode
* wdio-mocha-framework: 0.5.8

Here is the code to reproduce, I would expect the two `console.log` to output the same thing, but you will see that `getHTML` outputs both element [0] and [1] in an array, instead of just element [1]:

```javascript
describe(`Test`, () => {
  it('Test', () => {
    browser.url('http://www.google.com');
    console.log($$('.gb_P')[1].getText());
    console.log($$('.gb_P')[1].getHTML(false));
  });
});
```

**Comment by akloeber** [comment]
A similar behavior can be observed when chaining `element()` calls, see #2155 .

**Comment by rsshilli** [comment]
It's also not documented in the API, which would be nice.
