### ISSUE TITLE
Is this implementation compatible with W3C WebDriver Protocol?

### ISSUE THREAD

**Issue by harttle** [webdriverio/webdriverio#1881]
## The problem

I'm currently implementing a proxy-based webdriver wrapper for real (old mobile) browsers. I tried to get webdriverio connected to my webdriver server (via `host` and `port` configurations), but it wasn't working as expected. Does the claimed [JSONwire protocol][jsonwire] not compatible with the [W3C WebDriver][wd-w3c] Protocol? 

## Detail

As far as I understand, the response body format of the [JSONWire protocol][jsonwire] includes status and value fields, which looks like:

```
{
  "sessionId": "xxx",
  "status": 0,
  "value": "the result string or object"
}
```

While in the [W3C WebDriver][wd-w3c], the response body contains only the result (the status is represented by HTTP status code), which looks like:

```
{
  "error": "invalid session id",
  "message": "No active session with ID 1234",
  "stacktrace": ""
}
```

Is there anything missed or understood?

[wd-w3c]: https://www.w3.org/TR/webdriver/
[jsonwire]: https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol

**Comment by christian-bromann** [comment]
With Selenium 3 we are currently transitioning from the JSONWire protocol to the Webdriver protocol. Selenium 3 works like JSONWire and only adds new commands that reflect the Webdriver protocol as well as deprecates some commands that aren't in the Webdriver protocol. With Selenium 4 the Webdriver protocol will be the only supported protocol. This happens sometime this year.

So right now both protocols are supported (except using geckodriver (firefox)). WebdriverIO will release a proper update when the time has come to ensure 100% compatibility with the Webdriver spec.
