### ISSUE TITLE
Unnecessary trim to browser.getValue()

### ISSUE THREAD

**Issue by ItamarGronich** [webdriverio/webdriverio#1885]
## browser.getValue() trims spaces. :hushed: 

`browser.getValue()` trims the returned value which is not desired.
Trying to verify that a value of an input has space in it at the end. (suppose that was someones password???)
but `getValue()` that uses the unify function [automatically trims](https://github.com/webdriverio/webdriverio/blob/acdd79bff797b295d2196b3616facc9005b6f17d/lib/webdriverio.js#L463) the spaces at the end. 
## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 6.4.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous

**Comment by christian-bromann** [comment]
@ItamarGronich can you provide a reproducible example please?

**Comment by christian-bromann** [comment]
Also please see #1883

**Comment by derwok** [comment]
We were biten by this topic, also! We use chimp (with webdriver.io). When running the tests headless everything is fine. Wenn running the tests whitch chrome driver, then non-existing selectors lead to a very confusing error message.  ;-( and debugging is very hard...

I created a minimal repo that shows the error:
https://github.com/derwok/chimptest
(The comprehensive README.md gives version numbers of all tools and steps to reproduce)

When running the tests with node 7.x and we hit this line:
`browser.click("#DOES_NOT_EXIST");` then the test runner crashes with:

```
     TypeError: Cannot read property 'trim' of undefined
      at sanitizeErrorMessage (/usr/local/lib/node_modules/chimp/node_modules/wdio-sync/build/index.js:190:34)
      at Object.<anonymous> (/usr/local/lib/node_modules/chimp/node_modules/wdio-sync/build/index.js:467:23)
      at Context.<anonymous> (tests/ChimpTest.js:13:17)
      at /usr/local/lib/node_modules/chimp/dist/lib/utils/fiberize.js:25:14
```
### FunFact: node version matters!
It seems, the problem is strongly related to the used node version. Because when we switch to node 4.x (latest) or node 6.x (latest) we get the expected error:
```
 Error: An element could not be located on the page using the given search parameters.
```

**Comment by ItamarGronich** [comment]
Hey @christian-bromann,
The issue is not about an exception with the [trim() function in `client.unify`](https://github.com/webdriverio/webdriverio/blob/acdd79bff797b295d2196b3616facc9005b6f17d/lib/webdriverio.js#L463) , the issue is about the fact that `browser.getValue()` will trim spaces off the values and this is not a desired behavior. I think the user shall decide if to trim or not. Please remove the trim from all the getter functions.

To reproduce: 

stack: 
- node 6.4.0
- webdriver.io 4.6.2
- chromedriver 2.27 (not selenium)

have an HTML file with an input.
put a value in that input that has a space at the end.
use `browser.getValue()` on that input.
assert that the space was trimmed. - NOT GOOD.

my workaround was:

```javascript

      /**
       * Tackle the even weirder decision of WebDriver.io trim the spaces
       * of every property value. Even the "value" property's value.
       * I understand this for class or href properties but not for value.
       * You can see it here : https://github.com/webdriverio/webdriverio/blob/acdd79bff797b295d2196b3616facc9005b6f17d/lib/webdriverio.js#L463
       *
       * @param {String} elementId
       *   ID of a WebElement JSON object of the current element.
       *
       * @return {String}
       *   The value of the `value` attribute.
       */
      const getActualText = elementId =>
        browser
          .elementIdAttribute(elementId, 'value')
          .value;
```

**Comment by ItamarGronich** [comment]
@christian-bromann Please re-open.

**Comment by christian-bromann** [comment]
Trimming text is indeed not desired for that command. Let's add an additional option to the `unify` helper.

**Comment by ItamarGronich** [comment]
I'll open a PR with the fix.

**Comment by kajmagnus** [comment]
@ItamarGronich Would you like to check if the value is null / undefined, and, if so, not call `.trim`? There's another bug about `.trim()` being called on null / undefined. I'm wondering if your fix of this issue, will fix that bug too

**Comment by capaj** [comment]
@ItamarGronich what about that PR-do you have it in progress? Or could I take a stab at it this weekend?

**Comment by ItamarGronich** [comment]
Yeah, I was caught off with some stuff. I'll get to that 2day hopefully.

**Comment by christian-bromann** [comment]
@ItamarGronich I am working on it

**Comment by christian-bromann** [comment]
I think the reason why I did that in the first place was that some browser driver trim the value and some not. This way it is at least consistent. If CI tests don't pass because IEDriver trims the value I will leave it as is.

**Comment by umair2020** [comment]
I am on wdio 6 (sync mode) and still facing this issue where the setValue() doesn't set complete text until I add browser.pause () after it
