### ISSUE TITLE
Enable overwriting capabilities via WDIO launcher

### ISSUE THREAD

**Issue by hdattada** [webdriverio/webdriverio#1890]
## The problem

We are using grunt-webdriver to set separate capabilities for test suites. My base config file is as below and as you can see I do not have capabilities set in this base file.

[sample_wdio_conf.txt](https://github.com/webdriverio/webdriverio/files/794562/sample_wdio_conf.txt)

### Grunt task
```
suite1: {
        options: {
          specs: './tests/integration_tests/test1/test_*.js',
          capabilities: [{
            loggingPrefs: {'browser': 'OFF'},
            version: '',
            platform: 'ANY',
            javascriptEnabled: true,
            browserName: 'chrome',
            chromeOptions: {debuggerAddress: '172.7.7.35:900'}
          }],
          services: ['selenium-standalone'],
        },
configFile: './tests/integration_tests/local.conf.js' // Refer to sample config file attached
      }
```
## Environment

* WebdriverIO version: **4.6.2**
* Node.js version: **4.4.5**
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): **test runner**
* if wdio testrunner, running synchronous or asynchronous tests: **Synchronous**
* Additional wdio packages used (if applicable): **wdio-selenium-standalone-service@0.0.8, wdio-mocha-framework@0.5.8**

## Details

There is no error as such but the tests hang trying to execute scripts on the debuggerAddress. If I have the capabilities set in the configFile and do not try to set the capabilities from the grunt File the tests work.

When I look at this line https://github.com/webdriverio/webdriverio/blob/master/lib/launcher.js#L32
It uses `configParser.getCapabilities()` to pass the caps to the runner. If I print out the same I get `{}` which is not right and I believe that is the issue here

**Comment by christian-bromann** [comment]
Let's enable overwriting caps.

**Comment by akselon** [comment]
Thank you @christian-bromann ! 👍

**Comment by hdattada** [comment]
Awesome.. Thanks @christian-bromann 👍

**Comment by SassNinja** [comment]
@christian-bromann any update on this?

I'm facing the same problem as @hdattada except it's gulp in my case.

**Comment by christian-bromann** [comment]
I think this is fixed with latest version.
