### ISSUE TITLE
Can not overwrite webdriverio Launcher capabilities

### ISSUE THREAD

**Issue by akselon** [webdriverio/webdriverio#1891]
## The problem

I want to write my own javascript test luncher, so that I can run tests from CLI and choose in wich browser the tests should be run. My idea was to write a defaut webdriverio config file and overwrite it's values in the launcher. But I can not overwrite the capabilities. It always runs on the browser defined in the default webdriverio config file. 

## Environment

* WebdriverIO version: v4.6.2
* Node.js version: 6.9.5
* [Standalone mode or wdio testrunner]: wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):
`"devDependencies": {
	"allure-commandline": "^1.5.0",
	"chai": "^3.5.0",
	"selenium-standalone": "^6.0.1",
	"wdio-allure-reporter": "^0.1.2",
	"wdio-dot-reporter": "0.0.7",
	"wdio-mocha-framework": "^0.5.8",
	"wdio-phantomjs-service": "^0.2.2",
	"wdio-selenium-standalone-service": "0.0.8",
	"wdio-spec-reporter": "0.0.5",
	"webdriverio": "^4.6.2"
}`

## Details

I have following webdriverio config file:
`    exports.config = {
      ...
      capabilities: [{
          maxInstances: 5,
          browserName: 'chrome'
      }],
      ...
    }`
Here is my javascript test launcher:
`
var Launcher = require('webdriverio').Launcher;
var wdio = new Launcher("wdio.conf.js",{capabilities: [{browserName: "firefox"}], screenshotPath: "another"});
wdio.run().then(function (code) {
    process.exit(code);
}, function (error) {
    console.error('Launcher failed to start the test', error.stacktrace);
    process.exit(1);
});
`

I added this line code: `console.log(this.configParser);` [here](https://github.com/webdriverio/webdriverio/blob/master/lib/launcher.js#L12)
And got:
`ConfigParser {
  _config:
   { host: '127.0.0.1',
     port: 4444,
     sync: true,
     specs: [ 'tests/**/*.js' ],
     suites: {},
     exclude: [],
     logLevel: 'silent',
     coloredLogs: true,
     baseUrl: 'http://dev.dev',
     bail: 0,
     waitforInterval: 500,
     waitforTimeout: 10000,
     framework: 'mocha',
     reporters: [ 'dot', 'allure' ],
     reporterOptions: { allure: [Object] },
     maxInstances: 10,
     maxInstancesPerCapability: 100,
     connectionRetryTimeout: 90000,
     connectionRetryCount: 3,
     debug: false,
     execArgv: null,
     mochaOpts: { timeout: 30000, ui: 'bdd' },
     jasmineNodeOpts: { defaultTimeoutInterval: 10000 },
     onPrepare: [Function: NOOP],
     before: [],
     beforeSession: [],
     beforeSuite: [],
     beforeHook: [],
     beforeTest: [],
     beforeCommand: [],
     afterCommand: [],
     afterTest: [],
     afterHook: [],
     afterSuite: [],
     afterSession: [],
     after: [],
     onComplete: [Function: NOOP],
     onError: [],
     onReload: [],
     beforeFeature: [],
     beforeScenario: [],
     beforeStep: [],
     afterFeature: [],
     afterScenario: [],
     afterStep: [],
     screenshotPath: 'another',
     services: [ 'selenium-standalone' ],
     capabilities: [ { browserName: 'firefox' } ]
  },
  _capabilities: [ { maxInstances: 5, browserName: 'chrome' } ] }
`

As you can see `screenshotPath` is edited to 'another', and `capabilities `also, but `ConfigParser._capabilities` is still chrome. And the test runs on chrome. I think this is not correct. Am I doing any thing wrong?

**Comment by hdattada** [comment]
I opened a similar issue yesterday. Its consistent to what I am observing https://github.com/webdriverio/webdriverio/issues/1890

**Comment by christian-bromann** [comment]
Let's continue convo at #1890
