### ISSUE TITLE
The beforeTest and afterTest hooks do not work when using Cucumber?

### ISSUE THREAD

**Issue by MacDennis76** [webdriverio/webdriverio#1894]
## The problem

I would like to use the various hooks when using Cucumber. But when running my tests I do not see any output in the console of the following hooks.

     beforeTest: function (test) {
       console.log('HOOK: BEFORE TEST');
     },

     afterTest: function (test) {
       console.log('HOOK: AFTER TEST');
    },

Is this to be expected?

## Environment

* WebdriverIO version: 4,6,2
* Node.js version: 6.9.4
* [Standalone mode or wdio testrunner: wdio (sync)
* Additional wdio packages used (if applicable): none

## Details

When I include the following custom hook in a hooks.js then this hook does fire:

var AfterHooks = function () {
  this.After(function (scenario, callback) {    
    console.log('HOOKS: CUSTOM AFTER HOOK');    
    callback();
  });
};
module.exports = AfterHooks;

**Comment by christian-bromann** [comment]
@MacDennis76 these hooks are not supported since Cucumber doesn't has the concept of test. See the list of cucumber supported hooks. Also not framework related hooks work with Cucumber like `onPrepare`, `beforeSession`, `afterSession` and `onComplete`.
