### ISSUE TITLE
Failed: Timed out awaiting response to command "switchToFrame" (Safari)

### ISSUE THREAD

**Issue by ziodave** [webdriverio/webdriverio#1895]
## The problem

I am not sure if this is the right place to report this issue, but I have to start from somewhere :-)

I am using WebdriverIO with SauceLabs and a Safari configuration. Tests include a ```browser.frame( browser.element( '#content_ifr' ).value );``` call which fails with

> Failed: Timed out awaiting response to command "switchToFrame"```

Running the test on my local Safari works.

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 6.10.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio test runner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):

 *    "wdio-jasmine-framework": "^0.2.19",
 *    "wdio-sauce-service": "^0.3.1",
 *    "wdio-selenium-standalone-service": "0.0.8".

## Details

The full error:

```
Failed: Timed out awaiting response to command "switchToFrame" after 30036 ms (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 30.06 seconds
Build info: version: '2.48.0', revision: 'b7b081a', time: '2015-10-07 15:48:56'
System info: host: 'itako50112.prod.miso', ip: '172.20.50.112', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.1', java.version: '1.8.0_112'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=10.0.1, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}]
Session ID: null
running safari (vlatest) on macOS 10.12
Check out job at https://saucelabs.com/tests/f8bb3c5a34cb4d0baab0aefc5f0a1cde
Error: Timed out awaiting response to command "switchToFrame" after 30036 ms (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 30.06 seconds
    Build info: version: '2.48.0', revision: 'b7b081a', time: '2015-10-07 15:48:56'
    System info: host: 'itako50112.prod.miso', ip: '172.20.50.112', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.1', java.version: '1.8.0_112'
    Driver info: org.openqa.selenium.safari.SafariDriver
    Capabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=10.0.1, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}]
    Session ID: null
    at frame([object Object]) - at Object.<anonymous> (tests/e2e/tests/backend/indexSpec.js:177:13)
```

## Link to Selenium/WebdriverIO logs

I am not sure how to get them from SauceLabs or Travis.

**Comment by ziodave** [comment]
Some additional information:

Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=10.0.1, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}]
Session ID: null","localizedMessage":"Timed out awaiting response to command \"switchToFrame\" after 30036 ms (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 30.06 seconds
Build info: version: '2.48.0', revision: 'b7b081a', time: '2015-10-07 15:48:56'
System info: host: 'itako50112.prod.miso', ip: '172.20.50.112', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.1', java.version: '1.8.0_112'

**Comment by alesanu** [comment]
Hi. I got same behavior on Browserstack using nightwatch
`{ additionalInformation: '\nDriver info: org.openqa.selenium.safari.SafariDriver\nCapabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=9.1.3, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}]\nSession ID: null',
     localizedMessage: 'Timed out awaiting response to command "switchToFrame" after 30010 ms (WARNING: The server did not provide any stacktrace information)\nCommand duration or timeout: 30.01 seconds\nBuild info: version: \'2.45.0\', revision: \'5017cb8\', time: \'2015-02-26 23:59:50\'\nSystem info: host: \'mac-185-44-131-74.browserstack.com\', ip: \'185.44.131.74\', os.name: \'Mac OS X\', os.arch: \'x86_64\', os.version: \'10.11.6\', java.version: \'1.8.0_121\'\nDriver info: org.openqa.selenium.safari.SafariDriver\nCapabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=9.1.3, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}]\nSession ID: null',
     supportUrl: null,
     systemInformation: 'System info: host: \'mac-185-44-131-74.browserstack.com\', ip: \'185.44.131.74\', os.name: \'Mac OS X\', os.arch: \'x86_64\', os.version: \'10.11.6\', java.version: \'1.8.0_121\'',
     cause: null,
     suppressed: [],
     message: 'Timed out awaiting response to command "switchToFrame" after 30010 ms (WARNING: The server did not provide any stacktrace information)\nCommand duration or timeout: 30.01 seconds\nBuild info: version: \'2.45.0\', revision: \'5017cb8\', time: \'2015-02-26 23:59:50\'\nSystem info: host: \'mac-185-44-131-74.browserstack.com\', ip: \'185.44.131.74\', os.name: \'Mac OS X\', os.arch: \'x86_64\', os.version: \'10.11.6\', java.version: \'1.8.0_121\'\nDriver info: org.openqa.selenium.safari.SafariDriver\nCapabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=9.1.3, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}]\nSession ID: null',
     hCode: 483537747,
     class: 'org.openqa.selenium.TimeoutException',
     buildInformation: 
      { buildRevision: '5017cb8',
        buildTime: '2015-02-26 23:59:50',
        releaseLabel: '2.45.0',
        hCode: 548514608,
        class: 'org.openqa.selenium.internal.BuildInfo' },
     screen: null }`

**Comment by christian-bromann** [comment]
This command is probably not supported by Safari or there is a bug in the Safaridriver. There is nothing WebdriverIO can do about it.
