### ISSUE TITLE
`getText` trims *special* whitespaces like `'\u202f'`

### ISSUE THREAD

**Issue by AlexandreBonneau** [webdriverio/webdriverio#1896]
When I test the following statement:
```js
expect(browser.getText(selectors.issue303inputS)).toEqual('\u202f€');
```
the test fails while I'm sure to have the *thin space* before the Euro sign as the input value since I set it directly with `domElement.value = '\u202f€'` before.
```html
<input id="issue_303s" type="text" placeholder="#303" value="">
```
*(I also triple checked this manually)*

It seems `getText` trims all whitespaces, including special ones like `'\u202f'`.
Is there a way to tell `getText` to not trim those *special* spaces?

EDIT: I updated the html structure ; the tests I was running were running on basic `<input>` elements, not `<div>` with the `contenteditable` attribute.

**Comment by christian-bromann** [comment]
@AlexandreBonneau what gets actually returned? Have you tried `getHTML`?

**Comment by AlexandreBonneau** [comment]
Ah indeed, I forgot to tell the most important thing ; `'€'` is returned by `getText`, without any spaces around the Euro sign.

If I try `getHTML`, it fails since it returns...the html code, not the input value :
```text
Expected '<input id="issue_303s" type="text" placeholder="#303" value="">' to equal ' €'.
```

**Comment by dcypherthis** [comment]
what browser are you running this in?

**Comment by AlexandreBonneau** [comment]
In Chrome 56, the problem is visible.

For info, this is working as intended on Firefox 45.7.

**Comment by christian-bromann** [comment]
> For info, this is working as intended on Firefox 45.7.

I think in this case we can't really do much here. In case WebdriverIO would trim the result we could fix that by removing the trim. Apparently this is a chromedriver issue and I would recommend to not assert the whitespace.

**Comment by AlexandreBonneau** [comment]
For info, this is fixed today in v8 and the current version of chromedriver.

**Comment by industral** [comment]
Also have the same issue, even with latest v8.35. Fixed by using `element.getProperty('textContent')` instead of `element.getText()`.
