### ISSUE TITLE
Steps Running in parallel on browserstack 

### ISSUE THREAD

**Issue by ItamarGronich** [webdriverio/webdriverio#1903]
## The problem

Running tests on browserstack on ipad2 with local testing results in steps being executed in parallel.

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 6.4.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable): `browserstack` and `browserstack-local`.

## Details

I'm trying to run our tests on the ipad 2 on browserstack from my localhost but have inconsistent results.
Sometimes it work tests function properly but when they don't i can figure out that somehow the steps defined in the test run in parallel and interfere with each other. 
I debugged this for quite some time and i can see the steps running on top of each other.

## Link to Selenium/WebdriverIO logs

https://gist.github.com/ItamarGronich/6c039f065dd5c94f34db8632777412dc

## Code To Reproduce Issue

It's really hard to give code to reproduce because there's a ton of dependencies here. 

But basically what we have here is:
- a gulp running a single page navigatable app with login logout functions on a browsersync server on localhost:3000
- browserstack and browserstack local installed
- versions mentioned above ^
- I'm running the task with an npm script running supplied below: 
```JSON
  "scripts": {
    "test-browserstack-local" : "./node_modules/.bin/wdio test/configs/wdio-browserstack-local.conf.js"
  }
```
- I'm linking a gist for the code i thought relevant [here](https://gist.github.com/ItamarGronich/6253b736e333d28db1c874ed7c992b59)

**Comment by christian-bromann** [comment]
Do you have more logs (e.g. from Browserstack)? I need more data to be able to determine whats going on. Also can you instead of adding command via `addCommand` build page objects?

**Comment by ItamarGronich** [comment]
Thanks for the quick reply @christian-bromann 

[Logs from browserstack](https://gist.github.com/ItamarGronich/485264c99b7bad67bd130127ebe775cc)

And also, please expand on page objects ?

**Comment by christian-bromann** [comment]
> And also, please expand on page objects ?

Please see page objects in the docs

**Comment by christian-bromann** [comment]
Can you create a minimal reproducible example of this? I can't tell whats up without being able to run it by myself and debug the code.

**Comment by ItamarGronich** [comment]
@christian-bromann I've removed some unnecessary commands to make the code slimmer. 

I can't give you the entire code for the app. 
And i can't see a way to give you the code without cloning the entire repo and slimming it down. something that'll take a tremendous amount of time and effort.

I don't know how i can give you a reproducible example ???
I put all the configuration and specs needed to run the tests. 
Can't you just fireup a test single page webapp that has a login logout function and change the tests to suit that ?

**Comment by ItamarGronich** [comment]
@christian-bromann hold on. i might be able to set something up later today.

**Comment by christian-bromann** [comment]
If you want to file a bug and have it fixed by us (me) I need something I can run on my end that reproduces the problem. I don't have time to figure out how to reproduce the issue. If you can't provide such a reproducible example (which is absolutely understandable) we would highly appreciate if you could dig into the code to see whats up.

Closing. Happy to reopen once a reproducible example is provided.
