### ISSUE TITLE
help me how to configure and running webdriver tests in firefox and IE with WDIO testrunner

### ISSUE THREAD

**Issue by 212342148** [webdriverio/webdriverio#1906]
## The problem
We created tests using webdriver IO, those tests are working fine with chrome from wido.config testrunner but not able to execute my tests with Firefox(52v) and IE(11v). I had using drivers for Firefox and IE as well.

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 6.9.4
* Selenium standalone : 3.0.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous 
* Additional wdio packages used (if applicable):

Driver versions:
IE: 3.0.0-x64-IEDriverServer
Firefox: 0.13.0-x64-geckodriver

## Details
**Error details for Firefox:**
ERROR: Cannot find firefox binary in PATH. Make sure firefox is installed. OS ap
pears to be: VISTA
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0
700'
System info: host: 'G971LX52E', ip: '127.0.0.1', os.name: 'Windows 7', os.arch:
'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: driver.version: FirefoxDriver
firefox

**Error details for IE**

ERROR: The best matching driver provider org.openqa.selenium.edge.EdgeDriver can
't create a new driver instance for Capabilities [{rotatable=true, locationConte
xtEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@19ce
5573, browserName=internet explore, javascriptEnabled=true, handlesAlerts=true,
maxInstances=5, requestOrigins={name=webdriverio, version=4.6.2, url=http://webd
river.io}}]
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0
700'
System info: host: 'G971LX52E', ip: '127.0.0.1', os.name: 'Windows 7', os.arch:
'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: driver.version: unknown
internetexplore

**wdio.Config file**

// ============
// Capabilities
// ============
// Define your capabilities here. WebdriverIO can run multiple capabilities at the same
// time. Depending on the number of capabilities, WebdriverIO launches several test
// sessions. Within your capabilities you can overwrite the spec and exclude options in
// order to group specific specs to a specific capability.
//
// First, you can define how many instances should be started at the same time. Let's
// say you have 3 different capabilities (Chrome, Firefox, and Safari) and you have
// set maxInstances to 1; wdio will spawn 3 processes. Therefore, if you have 10 spec
// files and you set maxInstances to 10, all spec files will get tested at the same time
// and 30 processes will get spawned. The property handles how many capabilities
// from the same test should run tests.
//
  maxInstances: 10,
//
// If you have trouble getting all important capabilities together, check out the
// Sauce Labs platform configurator - a great tool to configure your capabilities:
// https://docs.saucelabs.com/reference/platforms-configurator
//
  capabilities: [{
  // maxInstances can get overwritten per capability. So if you have an in-house Selenium
  // grid with only 5 firefox instances available you can make sure that not more than
  // 5 instances get started at a time.
    maxInstances: 5,
    browserName: 'chrome',
  },
   
  {
    maxInstances: 5,
    browserName: 'internet explore'
  },
  {
    maxInstances: 5,
    browserName: 'firefox'
  }],
  //

**Comment by christian-bromann** [comment]
There are a lot of pages on the internet explaining how to set up iedriver and geckodriver. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not an issue.
