### ISSUE TITLE
$$ and elements do have an extended prototype as advertised

### ISSUE THREAD

**Issue by rikkertkoppes** [webdriverio/webdriverio#1907]
## The problem

$$ should extend the prototype of the returned results, to enable chaning like this (as per [docs](http://webdriver.io/api/utility/$$.html)):

    text.$$('li')[2].getText('a')

This does not seem to be the case

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 6.9.4
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable):

    "wdio-dot-reporter": "0.0.6",
    "wdio-mocha-framework": "^0.4.0",
    "wdio-spec-reporter": "0.0.3",

## Link to Selenium/WebdriverIO logs

Returned error message:

    browser.$$(...)[0].getText is not a function

## Code To Reproduce Issue [ Good To Have ]

Just try the code in the docs.

**Comment by christian-bromann** [comment]
It works when calling 
```js
$$(...)[0].getText
```
instead of 
```js
browser.$$(...)[0].getText
```

Also another issue is that
```js
$$('li')[0].getText()
```
would not return text of a single element (with index 0) but for all elements. We loose the scope somewhere in between.

**Comment by christian-bromann** [comment]
Not sure why I labeled this as a bug but this is fixed with latest version of WebdriverIO and framework adapter. Example:

```js
describe('suitea', function() {
    it('testa', function () {
        browser.url('http://webdriverjs.christian-bromann.com');
        var page = $('.page')
        console.log(page.$$('.box')[2].getAttribute('class'));
    })
});
```
will return the 3rd box which is yellow, so output is:
```
box yellow
```
also the Selenium logs look correct:
```
// look for page element
16:12:45.133 INFO - Executing: [find element: By.cssSelector: .page])
16:12:45.158 INFO - Done: [find element: By.cssSelector: .page]

// look for box elements within page element
16:12:45.181 INFO - Executing: [find child elements: 0 [[PhantomJSDriver: phantomjs on OS X 10.10 (6bb79510-25d3-11e7-9e84-a793a9a776ba)] -> css selector: .page], By.cssSelector: .box])
16:12:45.222 INFO - Done: [find child elements: 0 [[PhantomJSDriver: phantomjs on OS X 10.10 (6bb79510-25d3-11e7-9e84-a793a9a776ba)] -> css selector: .page], By.cssSelector: .box]

// get class attribute of that element
16:12:45.264 INFO - Executing: [get element attribute: 3 [[[[PhantomJSDriver: phantomjs on OS X 10.10 (6bb79510-25d3-11e7-9e84-a793a9a776ba)] -> css selector: .page]] -> css selector: .box], class])
16:12:45.286 INFO - Done: [get element attribute: 3 [[[[PhantomJSDriver: phantomjs on OS X 10.10 (6bb79510-25d3-11e7-9e84-a793a9a776ba)] -> css selector: .page]] -> css selector: .box], class]
```

Closing
