### ISSUE TITLE
Cannot run wdio through a SauceConnect HA proxy in later versions

### ISSUE THREAD

**Issue by brownad** [webdriverio/webdriverio#1908]
## The problem

In wdio 4.2.16 I can run wdio against a remote SauceConnect HA cluster.  Since upgrading to version 4.4.0 and latest 4.6.x I can no longer connect to the SauceConnect instance and start a session through SauceLabs.

I have tried with the sauce service and without, makes little difference.  Forced to downgrade (shucks!), does anyone have experience using wdio via SauceConnect remotely where it does not hang?

## Environment

* WebdriverIO version: 4.4.0 and latest 4.6.x
* Node.js version: 6.9.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable): wdio-sauce-service (not really used though, I inject all the values anyway)

## Details

Trying to connect to saucelabs via wdio, but fails to connect using later versions against a remote Sauce cluster

## Link to Selenium/WebdriverIO logs

$ wdio
ERROR: Couldn't connect to selenium server

**Comment by christian-bromann** [comment]
You need to set host and port in your wdio config as well as protocol back to `http`. If you have a sauce user and key in your wdio config, it switches automatically to https. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by brownad** [comment]
I did add discussion if it works on 4.2.16 but not on latest but using same and correct wdio config you sure there's no regression?

Host is set to the sauceconnect host, port to 4445. 

Nothing changed in later versions that could affect connectivity?  Where can I find the info on switching to https?

**Comment by brownad** [comment]
Fixed thanks, added protocol: http still seems a painful requirment

**Comment by christian-bromann** [comment]
ref #1911

**Comment by christian-bromann** [comment]
I didn't made the experience. If you set a host in your config WebdriverIO won't switch to https.
