### ISSUE TITLE
Session DELETE unexpectedly

### ISSUE THREAD

**Issue by picklelv** [webdriverio/webdriverio#1910]
## The problem

Running a test in Chrome seems to be killing my session unexpectedly after an iFrame is loaded.

`browser.waitForExist("iframe[id='" + id + "']");`

I've tried placing a pause after the `waitForExist`, but the browser still closes and the test fails.

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 6.2.2
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): WDIO TestRunner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable):
```
"wdio-cucumber-framework": "~0.2.15",
"wdio-phantomjs-service": "~0.1.0",
"wdio-selenium-standalone-service": "~0.0.7",
"wdio-spec-reporter": "~0.0.3",
"selenium-standalone": "~5.8.0"
```

## Link to Selenium/WebdriverIO logs
[Selenium](https://gist.github.com/picklelv/9c73792ea0dad8ecbd11b7bf9c79cf01)
[WebdriverIO](https://gist.github.com/picklelv/45d3de70d216c8255452feecb2edf178)

## Code To Reproduce Issue [ Good To Have ]

I'm not sure that this is code related.  It seems to be specific to our web application and the iFrame.  I do see some errors in the console for our app, but would that cause selenium to kill the session early?

**Comment by christian-bromann** [comment]
Can you provide a code snippet or a reproducible example?

**Comment by picklelv** [comment]
Here's the function that I'm running, but I put a `browser.pause(60000)` above the `waitForExist` and the browser still died after the iFrame loaded.

```
closeFrame: function(id) {
    browser.waitForExist("iframe[id='" + id + "']");
    var frame = browser.element("iframe[id='" + id + "']").value;
    browser.frame(frame);
    browser.click("button[aria-label='Close']");
},
```

```
15:12:58.829 INFO - Done: [click: 2 [[ChromeDriver: chrome on MAC (4e849ec2fc1ad2b003e2858ccdff434e)] -> css selector: button[id='loginButton']]]

<browser.pause(60000) HERE> Would have expected it to wait, but browser just closes

15:13:18.957 INFO - Executing: [delete session: 16ab5455-234f-4559-840b-1488d256b3bb])
15:13:19.039 INFO - Done: [delete session: 16ab5455-234f-4559-840b-1488d256b3bb]
```

**Comment by christian-bromann** [comment]
@picklelv can you check driver logs?

**Comment by christian-bromann** [comment]
According to the logs
```
14:40:24.447 INFO - Executing: [find elements: By.cssSelector: iframe[id='whatsnew']])
14:40:29.515 INFO - Done: [find elements: By.cssSelector: iframe[id='whatsnew']]
14:40:29.522 INFO - Executing: [find elements: By.cssSelector: iframe[id='whatsnew']])
14:40:43.068 INFO - Executing: [delete session: e74c5c45-96f3-4b38-a2e9-810ac5b99c1b])
14:40:43.582 INFO - Done: [find elements: By.cssSelector: iframe[id='whatsnew']]
14:40:43.592 INFO - Executing: [find element: By.cssSelector: iframe[id='whatsnew']])
14:40:43.666 INFO - Done: [delete session: e74c5c45-96f3-4b38-a2e9-810ac5b99c1b]
```
something breaks when waiting on the iframe. I can't do anything without a proper error message or a reproducible example. Can you provide any of this?

**Comment by picklelv** [comment]
Do I need to configure a path for driver logs or are they created somewhere else on my local?

**Comment by christian-bromann** [comment]
Please see https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver

**Comment by picklelv** [comment]
Closing.  `cucumberOpts.timeout` was the problem 😆
