### ISSUE TITLE
ERROR: Couldn't connect to selenium server on Sauce without Sauce Connect

### ISSUE THREAD

**Issue by asue** [webdriverio/webdriverio#1912]
## The problem

Hi there, I can't seem to get my tests to run on Sauce without having the sauce connect proxy on.  When I have it set to true, it connects and runs the tests ok.  If turning it to false or omitting the option, it idles for awhile before giving me an error about not being able to connect to the selenium server.

Below is my config file
```
{ host: 'ondemand.saucelabs.com',
  port: 80,
  path: '/wd/hub',
  specs: [ './test/accept/**/*-spec.js' ],
  exclude: [],
  maxInstances: 10,
  capabilities: 
   [ { maxInstances: 5,
       browserName: 'chrome',
       platform: 'OS X 10.11' } ],
  sync: true,
  logLevel: 'verbose',
  coloredLogs: true,
  bail: 0,
  screenshotPath: './build/acceptanceErrorShots/',
  baseUrl: 'http://mysite.com',
  waitforTimeout: 50000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  framework: 'jasmine',
  reporters: [ 'spec' ],
  jasmineNodeOpts: { defaultTimeoutInterval: 10000 },
  services: [ 'sauce' ],
  user: nconf.get('SAUCE_USER'),
  key: nconf.get('SAUCE_KEY'),
  sauceConnect: false }
```

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: v4.3.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable): wdio-sauce-service

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Selenium/WebdriverIO logs

Put in verbose as the logLevel and this is all I get.  I don't see anything on Sauce.
```
[10:59:02]  COMMAND	POST 	 "/wd/hub/session"
[10:59:02]  DATA		{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"maxInstances":5,"browserName":"chrome","platform":"OS X 10.11","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.6.2","name":"webdriverio"}}}
ERROR: Couldn't connect to selenium server
chrome.osx10_11
Error: Couldn't connect to selenium server
```

## Code To Reproduce Issue [ Good To Have ]

I'm using the grunt-webdriver to run it, but I get the same results with node_modules/.bin/wdio.  Maybe there's an extra step or configuration I missed?

Any help is appreciated!  Thanks!

**Comment by christian-bromann** [comment]
You don't need to set host and port. WebdriverIO does that for you. If you have a sauce accounts set in your config WebdriverIO will try to connect via https so if you have port set to 80 it can't connect. Either remove host and port or set protocol option to http. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
