### ISSUE TITLE
Can't scroll the element

### ISSUE THREAD

**Issue by protspace** [webdriverio/webdriverio#1913]
## The problem

I cant scroll element (i.e. Instagram list of followers https://www.instagram.com/gopro/followers/)

## Environment

* WebdriverIO version:   4.6.2
* Node.js version: 7.6.0
* [Standalone mode or wdio testrunner]: Standalone

## Details

The problem is that scrollable element (followers list popup) is not scrolling

## Code To Reproduce Issue [ Good To Have ]

    client
            .init()
            .url('https://www.instagram.com/accounts/login/')
            .getTitle().then(function(title){
            console.log("Title:" + title);
            })
            .pause(2000)
            .waitForExist('._rwf8p', 5000).then(function(isVisible){
            console.log("Login-form loaded : " + isVisible);
            })
            .setValue('*[name="username"]','username')
            .setValue('*[name="password"]','password')
            .click('button=Log in')
            .pause(3000)
            .url('http://instagram.com/gopro')
            .waitForExist('._8mm5v', 5000).then(function(isVisible) {
              console.log('User profile visible');
            })
            .click('a[href*="/followers/"]')
            .waitForExist('._4gt3b', 5000).then(function(isVisible) {
                console.log('User followers visible');
            })
            .elementActive('._4gt3b').then(function(elm) {
                console.log('this doesn't work');
                var elem = $('_4gt3b');
                elem.scroll(0, 100);
            })
            .executeAsync(function() {
               console.log('this doesn't work');
               client.element('_4gt3b').scroll(0, 100);
            })
            .element('._4gt3b').then(function (elm) {
                console.log('this doesn't work');
                elm.scroll(0, 300);
            })
            .end();

**Comment by christian-bromann** [comment]
You need to make sure to return promise chains otherwise as you treating async commands as synchronous. Apparently you are using the standalone mode where commands aren't synchronous. Also you don't need to scroll to do any action on elements. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not an issue.
