### ISSUE TITLE
Error on using import

### ISSUE THREAD

**Issue by zhenyulin** [webdriverio/webdriverio#1917]
> import webdriverio from 'webdriverio';
const wdOpts = {
	desiredCapabilities: {
		browserName: 'phantomjs'
	}
};
const client = webdriverio.remote(wdOpts);

get this error
> TypeError: Cannot read property 'remote' of undefined

tried both `webdriverio` and `webdriverio/build`, either seems to work.

It works if I do `require('webdriverio')` though.

**Comment by christian-bromann** [comment]
Do 
```js
import { webdriverio } from 'webdriverio';
```
Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by Fream** [comment]
Hello,
Have the same issue.
Tried to use import remote.
Nothing changed.

**Comment by shogunsea** [comment]
```js
import { remote } from 'webdriverio';
```
worked for me.
