### ISSUE TITLE
Count element

### ISSUE THREAD

**Issue by thibaut-sticky** [webdriverio/webdriverio#192]
Hi,

I try to play a little with this really nice library. To navigate on my site, it's really easy. But now, I want assert some properties. For the moment, webdriverjs expose a getText and a getValue methods. But to test an web app, of course it's not enough. 

For instance, if I want count the number of elements in a table, I have to use the execute method to do it and return a result to the callback. It's really verbose. 

I can add a command to reuse this code, but it would be nice to have feature to manipulate the DOM and test it directly throw webdriverjs.

Regards,

 Thibaut

**Comment by iSpid3r** [comment]
Hi @christian-bromann 

I need to count the number of elements on the page, but in response I keep getting { state: 'pending' }

I tried to do this in two ways, but the result is the same:

`var constr = browser.elements('.construction', function(err, res) {
return res.value.length;
});
console.log(constr);`

and

`var constr = browser.execute(function() {
var construct = $('.js-goto-slide:not([data-visited="true"]):not(.triangle-control)');
return construct.length;
});
console.log(constr);`

What is the problem?
