### ISSUE TITLE
Unable to trigger input event by choosing options from select elements

### ISSUE THREAD

**Issue by cmloegcmluin** [webdriverio/webdriverio#1922]
## The problem

We were writing a test which involves choosing an option from a `select` element. None of the `selectBy` methods caused the `input` event to fire. We could see that the select was being successfully changed to the desired option, but our Javascript listening for the `input` event wasn't being triggered.

## Details

We tried several different strategies for getting around this. In the end, this was what worked for us:

```
const selectOption = function (option) {
    browser.click("//select/option[contains(.,\"" + option + "\")]");
    browser.execute(function() {
        var el = document.querySelector('select');
        var event = new Event('input');
        el.dispatchEvent(event);
    });
}
```

The other strategies we tried included:
- `blur` away from the `select`
- wrapping the `select` in a `form` and submitting it
- clicking the `select` to open it, then clicking the `option`
- `sendKeys`
- `setValue`
- other events such as `change`
- `emit` the event from the webdriver client

## Environment

* WebdriverIO version: 4.2.1
* Node.js version: 7.5.0
* using `selenium-standalone`

## Link to Selenium/WebdriverIO logs

Whichever thing we tried, the logs just showed a repeated failure to find the elements we expect to be on the page after the desired Javascript ran.

**Comment by christian-bromann** [comment]
@cmloegcmluin on what page are you testing?

**Comment by cmloegcmluin** [comment]
Hi! Thanks for the prompt reply! The page is here:

http://standup-emcee-web.cfapps.io/#Pivots

**Comment by christian-bromann** [comment]
WebdriverIO is not responsible for triggering the events when clicking on elements or selecting an option. This is most likely a browserdriver issue. Closing.

**Comment by djkwagala** [comment]
@cmloegcmluin how did you resolve this issue?

**Comment by cmloegcmluin** [comment]
@djkwagala this is the helper function we wrote that ended up working for us:

```
const selectOption = function (option) {
    browser.click("//select/option[contains(.,\"" + option + "\")]");
    browser.execute(function() {
        var el = document.querySelector('select');
        var event = new Event('input');
        el.dispatchEvent(event);
    });
}
```

It's not too flexible as is... Assumes only a single select on the page. If you know/learn xpath, you can revise the selector though. Let me know if you need anything else!
