### ISSUE TITLE
mocha afterEach hook causes timeout error

### ISSUE THREAD

**Issue by avkrash** [webdriverio/webdriverio#1923]
## The problem

Tests randomly fails at mocha afterEach hook on open pages steps in CI with next error:
```
"after each" hook for "open all genres page" 	
Error: Timeout of 40000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.
```

I couldn't find reason or dependency why hook gets timeout. On WebdriverIO v.4.5.2  everything is fine with the same code, and problem starts from 4.6.0 version. I tried to change mochaOpts.timeout value but without success.

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 6.7.0
* wdio testrunner  running synchronous tests
* Additional wdio packages used:
** "wdio-mocha-framework": "^0.5.8",
** "wdio-teamcity-reporter": "^1.1.0",

**Comment by christian-bromann** [comment]
Can please provide Selenium and WebdriverIO logs?

**Comment by avkrash** [comment]
Sorry for that issue, we found that it was network problems between our CI and grid.
But there is a small error in reporting: it says that error was in after each hook (like mocha hook), but it was in wdio after test hook.

**Comment by christian-bromann** [comment]
> But there is a small error in reporting: it says that error was in after each hook (like mocha hook), but it was in wdio after test hook.

For Mocha these hooks are the same (their scope is just different). Closing then.
