### ISSUE TITLE
Opera webbrowser issue

### ISSUE THREAD

**Issue by adeleco** [webdriverio/webdriverio#1927]
## The problem

How to launch Opera with webdriverIO?
Setting the browsername doesn't seems to work.
 
## Environment

* WebdriverIO version: 6.4.2
* Node.js version: 7.5
* Selenium 3.3.0
* OperaWebdriver : 0.2.2

## Details

the browser name "opera" doesn't looks to be the good one

## Link to Selenium/WebdriverIO logs

https://gist.github.com/adeleco/a8a3b9e6224a37e6209951d0c02ac0ce

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.
var webdriverio = require('webdriverio');
var options = {
    desiredCapabilities: {
        browserName: 'opera'
    }
};
webdriverio
    .remote(options)
    .init()
    .url('http://www.google.com')
    .getTitle().then(function(title) {
        console.log('Title was: ' + title);
    })
    .end();

**Comment by christian-bromann** [comment]
Please make sure you have the opera driver installed properly. Closing as this is not an issue of WebdriverIO. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions.
