### ISSUE TITLE
Bail config doesn't work with Jasmine

### ISSUE THREAD

**Issue by ChadKillingsworth** [webdriverio/webdriverio#1928]
## The problem

Using jasmine, a `bail=1` argument seems to have no effect. It always runs the full test suite.

I've even tried adding a custom `afterTest` hook with `process.exit(1)`, but that doesn't seem to do it either. Neither does throwing and exception.

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 7.7.2
* Testrunner mode
* sync mode
* Additional wdio packages used (if applicable): wdio-jasmine-framework@0.2.19 , jasmine@2.5.3

**Comment by christian-bromann** [comment]
Please use WebdriverIOs [bail property](https://github.com/webdriverio/webdriverio/blob/master/docs/guide/getstarted/configuration.md#bail). Also please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by ChadKillingsworth** [comment]
Repo case: https://github.com/ChadKillingsworth/wdio-bail

**Comment by christian-bromann** [comment]
@ChadKillingsworth in your example you've defined bail twice and the last time with the value 0 (so no bail).

thanks @peterzal

**Comment by ChadKillingsworth** [comment]
@christian-bromann sorry - was in a hurry. I pushed a change so there is only 1 bail config. It's also set from the command line. You can comment out the config and only use the command line (or vice versa). 

All methods still execute both tests.

This is a massively simplified example. I have many tests on my production project. If the first one fails (or has a timeout error) ALL the tests still run regardless of the bail flag config.

**Comment by christian-bromann** [comment]
@ChadKillingsworth I just saw that you only run a single test. In this case you also need to pass in `bail: true` in your mocha opts. The bail property WebdriverIO provides is just so the launcher doesn't spawn more instances anymore.

**Comment by ChadKillingsworth** [comment]
@christian-bromann Mocha opts? Even with the Jasmine framework?

**Comment by christian-bromann** [comment]
> Mocha opts? Even with the Jasmine framework?

@ChadKillingsworth of course not .. don't know if jasmine has this feature. There is https://github.com/goodeggs/jasmine-bail-fast which could work

**Comment by ChadKillingsworth** [comment]
So then at a minimum some documentation on how that flag works would be great. Because it's far from clear (even in source code comments).

**Comment by christian-bromann** [comment]
> on how that flag works

What do you mean by that?

**Comment by ChadKillingsworth** [comment]
I would expect `bail=1` to stop the tests running regardless of the framework (from everything I have read). At a minimum the documentation should say exactly what you did: `The bail property WebdriverIO provides is just so the launcher doesn't spawn more instances. Testing frameworks must also support aborting after the first failure.`

I'm going to do more experimentation, but it also seems like I should be able to abort all future tests from the `afterEach` (and other) hooks. But I haven't been able to make that work either.

**Comment by christian-bromann** [comment]
I guess we could extend the section on [Stop testing after failure](http://webdriver.io/guide/testrunner/organizesuite.html#Stop-testing-after-failure). However there is a difference between WebdriverIO's bail functionality to not spawn new test runners after tests have failed and the bail functionality of a test framework to don't run any more tests within a test file after a test failed. The latter can't be handled by WebdriverIO and it is out of scope of this project (it can be a feature for the framework adapter though).

**Comment by jamesaspence** [comment]
@christian-bromann I'd suggest linking that above section in the configuration docs for "bail" as well. I found this issue after encountering a practically-identical issue with mocha and webdriverio, and found the docs lacking as well.

**Comment by christian-bromann** [comment]
@jamesaspence would you mind providing a PR with the suggested update?

**Comment by jamesaspence** [comment]
Sure thing. Forked the project, struggling a bit on the exact wording on what to write here. Right now I'm adding additional clarification to the configuration section for `bail`, as well as the `Stop testing after failure` (to link to the `bail` configuration).

**Comment by jamesaspence** [comment]
PR created here - https://github.com/webdriverio/webdriverio/pull/2561
