### ISSUE TITLE
unknown error when calling setViewportSize and windowHandleSize

### ISSUE THREAD

**Issue by cordovapolymer** [webdriverio/webdriverio#1937]
I want to change browser window or viewport size programmatically,
I'm tried doing it via wdio test specs with:

```
browser.setViewportSize({'width': 320, 'height': 500})
or
browser.windowHandleSize({width: 320, height: 500})
```
And via node standalone test with:

```
client.setViewportSize({'width': 320, 'height': 500})
or
client.windowHandleSize({width: 320, height: 500})
```

None of these functions work and I get the following error:
```
unknown error: cannot get automation extension
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
```

My setup is Chrome 56 and latest chromedriver 2.28 on Debian Stretch, I have installed webdriverio today using the tutorial at the [webdriver.io](https://webdriver.io)
**update** updated to chrome 57, and getting the same error

**Comment by christian-bromann** [comment]
Make sure your Chromedriver version is compatible with Chrome. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue because it has nothing to do with WebdriverIO.

**Comment by cordovapolymer** [comment]
@christian-bromann , yes it's compatible, [Latest Release: ChromeDriver 2.28 Supports Chrome v55-57](https://sites.google.com/a/chromium.org/chromedriver/downloads)
Well, I'm using WebdriverIO API and getting this error, that's why I have created an issue here.

**Comment by christian-bromann** [comment]
@cordovapolymer from all the information I got from you I can only say it has to be a Chromedriver issue.

**Comment by cordovapolymer** [comment]
Solved! Add 'disable-extensions' to your wdio.conf.js if you have the same issue.
```
chromeOptions: {
                      args: ['disable-extensions']
                  }
```
