### ISSUE TITLE
When doing $$('.elements')[1].$('.el1'), if el1 isn't present, it'll return all el1s on the page.

### ISSUE THREAD

**Issue by canvaspixels** [webdriverio/webdriverio#1939]
## The problem

When chaining $ off of $$, if there is nothing returned from the $ element, then is resorts to elements ($$) and looks in the global scope. This confused the hell out of me for a while, I thought I was doing something stupid.

## Environment

* WebdriverIO version: v4.6.2
* Node.js version: v5.0.0
* Standalone mode or wdio testrunner: WDIO Testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):
    "jasmine": "^2.5.3",
    "selenium-standalone": "^6.0.1",
    "wdio-jasmine-framework": "^0.3.0"

## Code To Reproduce Issue

e.g.
```
var lastSalePrice = $$('tr')[1].$('[title="my title"]');
console.log(i, lastSalePrice.getText());
```
if this element ([title="my title"]) doesn't exist in the second tr, it'll return an array of all the [title="my title"] elements on the page.

**Comment by crast** [comment]
+1, noticed same issue with the following:

* wdio 4.6.2
* node 7.4.0, 
* WDIO testrunner
* synchronous
* additional packages: 
    "wdio-browserstack-service": "^0.1.4",
    "wdio-mocha-framework": "^0.5.9",

**Comment by timbru31** [comment]
Could be related in the failing tests on Travis regarding element chaining.
https://travis-ci.org/webdriverio/webdriverio/jobs/212931593

**Comment by christian-bromann** [comment]
This is fixed with latest release:
```js
$ browser repl phantomjs
> browser.url("http://webdriver.io")
{ state: 'success',
  sessionId: 'f3739324-e3b8-4f59-b495-ddc61433b52d',
  hCode: 1995706998,
  value: null,
  class: 'org.openqa.selenium.remote.Response',
  _status: 0 }
> $$('.teaserbox')
[ { ELEMENT: '0',
    'element-6066-11e4-a52e-4f735466cecf': '0',
    selector: '.teaserbox',
    value: { ELEMENT: '0' },
    index: 0 },
  { ELEMENT: '1',
    'element-6066-11e4-a52e-4f735466cecf': '1',
    selector: '.teaserbox',
    value: { ELEMENT: '1' },
    index: 1 },
  { ELEMENT: '2',
    'element-6066-11e4-a52e-4f735466cecf': '2',
    selector: '.teaserbox',
    value: { ELEMENT: '2' },
    index: 2 } ]
> $$('.teaserbox')[1].$('p').getText()
'WebdriverIO works in combination with most of the TDD and BDD test frameworks in the JavaScript world'
```
