### ISSUE TITLE
Unable to click elements on pages with polymer's platform.js shim (stale element error)

### ISSUE THREAD

**Issue by jsoverson** [webdriverio/webdriverio#194]
Steps to reproduce : 
Go to any page that include's [polymer](http://polymer-project.org)'s platform.js feature shim (eg http://geelen.github.io/x-gif) and try to click on an element (any element, not just a web component/custom element

Expected behavior : 
Be able to click on the element as normal

Exhibited behavior :
Get a `StaleElementReference` error regardless of what attempt is made to click on an element.

Code used to reproduced this error:

```js
var webdriverjs = require('webdriverjs');
var client;

var client = webdriverjs.remote({
  host: 'localhost',
  port: 4444,
  desiredCapabilities: {
    browserName:'chrome',
  }
});

client
  .init()
  .url('http://geelen.github.io/x-gif/#/http://i.imgur.com/iKXH4E2.gif')
  .pause(3000)
  .click('.sub-nav'); // arbitrary element
```

**Comment by j03m** [comment]
I struggled with a similar issue and wrote a temp work around for my mocha tests (warning, it is very dirty, dirty, dirty):

Add a module for executing value collection on the client:
```javascript
module.exports = function(client, selector, check){
    return client.execute(function(selectorStr, check){
        console.log(selectorStr);
        var e = document.querySelector(selectorStr);
        return eval(check);
    }, selector, check);
}
```

Usage:
```javascript
var webdriverio = require('webdriverio');
var chai = require("chai");
var chaiAsPromised = require("chai-as-promised");
var executeGet = require('./executeGet.js');

chai.use(chaiAsPromised);

var options = {
    desiredCapabilities: {
        browserName: 'chrome'
    }
};

var client = webdriverio.remote(options);
client.init().url('http://localhost:8082/devtools/front_end/scratch.html');

executeGet(client, 'html /deep/ div#elem3', 'e.textContent').then(function(e){
    chai.expect(e.value).to.equal('elem 3');
});
```

Here you can collect values via eval (ew) and then write normal chai expectations. Not pretty. It obviously won't help you with manipulation, clicks etc. 

But the problem I see seems to be with selectors being run successfully, but the element ids then being stale when you want to take a follow up action. Calling an api like client.click(selector[,callback]), the first call to .element succeeds and returns an id of 0. The second call to elementIdClick fails with stale element.  (What happens in selenium, I'm unsure.).

I would imagine I can continue with the pattern for manipulation by getting position data and then calling protocol moveTo and click. 

Not pretty but workable until interacting with shadow dom is working.

**Comment by davidmaxwaterman** [comment]
I wonder if there are any more thoughts on how to solve this problem. In my mind, I need a function what waits for 'waitForEvent' in webdriver like I try to use - working from the example on (this)[http://www.webdriver.io/guide/plugins/grunt-webdriver.html] page :

```
'use strict';
var assert = require('assert');
describe('grunt-webdriver test', function () {
  it('checks if title contains the search query', function(done) {
    browser
    .url('http://localhost:8282/app/index.html')
      //.setValue('#js-command-bar-field','grunt-webdriver')
      //.submitForm('.command-bar-form')
      //.waitForVisible('body', 5000)
      .waitForEvent('polymer-ready',5000)
      .click('#projectopen')
      .pause(10000)
      .getTitle(function(err,title) {
        assert(title.indexOf('DAVE') !== -1);
      })
      .call(done);
  });
});
```

Is there such a thing? My searches suggest not :/

**Comment by indolering** [comment]
@davidmaxwaterman I think you are basically asking for a generic event checker.  You could add a listener to your code that sets a global variable and poll it using WebDriverIO by wrapping an execute function within a waitUntil function.

**Comment by indolering** [comment]
I tried working around this by detecting support for the shadow dom and removing `/deep/` and `::shadow` from my selectors:

```Javascript
  var s = {
    parent : 'custom-element::shadow'
  };

  s.child = s.parent + ' #child-element-id';
  
  browser.execute(function(){
      return typeof document.head.createShadowRoot === 'function';
    }).then(function(status){
      if(!status.value){
        for(var key in s){
          var selector = s[key];
          s[key] = selector.replace(/\/deep\/|::shadow|>>>/g,"");
        }
      }
    });
```

Unfortunately, the vanilla selectors do not work on Safari 9 or IE 11.  My codebase is not running on Edge nor Safari 7/8, but I've gotten a report that Edge rejects these selectors as well.  It's fairly difficult to debug the problem because I can't access the native query selector from the console since WebComponents.js alters `querySelector` function.

Since we are going to be migrating away from `/deep/` and friends, I think the only solution to this problem is to allow Selenium to use the query selector which webcomponents.js has pollyfilled.

I tried to create versions of functions that use the browser's native query selector, but I don't have time to re-implement every function and (as I found out) many functions rely on careful orchestration of events, such as click requiring a mouse up/down event sequence.  I think this will need to be done at a lower level.

I've included some functions below that use the native query selector in case someone finds them helpful,  they may be buggy:


```Javascript
    browser.addCommand('isVisibleNative', function(selector,reverse){
      return browser.execute(function(selectorStr){
        var e = document.querySelector(selectorStr);
        if(!e){
          return false;
        }
        var style = window.getComputedStyle(e);
        return style.display!=='none' && style.visibility!== 'hidden';
      }, selector).then(function(result){
        if(reverse){
          return !result.value;
        }
        return result.value;
      })
    });

    browser.addCommand('setValueNative', function(selector, value){
      return browser.execute(function(s, v){
        var e = document.querySelector(s);
        e.value = v;
        return true;
      }, selector, value).then(function(result){
        return result.value;
      })
    });

    browser.addCommand('clickNative', function(selector){
      return browser.execute(function(s){
        var e = document.querySelector(s);
        e.click();
        return true;
      }, selector).then(function(result){
        return result.value;
      })
    });

    browser.addCommand('waitForVisibleNative', function(selector, timeout, reverse){
      return browser.waitUntil(browser.isVisibleNative(selector),timeout);
    });
```

**Comment by kma7** [comment]
Any update or workaround yet? Still cannot locate Polymer shadow-root element:
it('go to registration page', function() {
        return client
            .click('#registration')
            .pause(500)
            .getText('#registration', function(err, text){
                console.log(text);
            });
    }); 

Got runtime error: "RuntimeError: no such window: target window already closedfrom unknown error: web view not found at element("#registration") - click.js:29:17"

**Comment by christian-bromann** [comment]
According to the chromedriver changelog shadow dom support got implemented with chromedriver version ChromeDriver 2.14. Had anyone luck with that version?

**Comment by samccone** [comment]
Yes it is working now, this can be closed

**Comment by christian-bromann** [comment]
noice, thanks@samccone
