### ISSUE TITLE
Firefox Profile works partially

### ISSUE THREAD

**Issue by sajidchingchong** [webdriverio/webdriverio#1944]
## The problem

Firefox Profile partially works locally but it doesn't work at all with services like Sauce Labs.

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 7.5.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Both
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): N/A

## Details

1) New preferences added into the profile are ineffective as 'media.navigator.streams.fake'.
2) Other preferences are working locally but they don't work with services like SauceLabs.

Test has been performed via code and configuration file. The behaviour is the same in both cases.

## Code To Reproduce Issue [ Good To Have ]

var FirefoxProfile = require('firefox-profile');

var fp = new FirefoxProfile();
fp.setPreference('media.navigator.streams.fake', true);
fp.setPreference('media.navigator.permission.disabled', true);

fp.encoded(function(profile) {
	
	desiredCapabilities: {
    	browserName: 'firefox',
    	firefox_profile: profile   
	}

});

**Comment by christian-bromann** [comment]
That for what the firefox profile service is for. See https://github.com/webdriverio/wdio-firefox-profile-service

**Comment by sajidchingchong** [comment]
I have logged an issue over there also. Since that doesn't work.

**Comment by christian-bromann** [comment]
And I replied there. You can't parse a firefox profile asynchronously in your config. The service helps you to define the profile and it injects it into your capabilities.

**Comment by sajidchingchong** [comment]
For configuration file, we are not actually parsing it. We rather wrote it into a file and paste the base64 string in the configuration file like that:

desiredCapabilities: {
	browserName: 'firefox',
	firefox_profile: 'xxxxxxxxxxxxxxxxxxxxxx'   
}

**Comment by christian-bromann** [comment]
This would work too .. but this is exactly why we have the firefox profile service
