### ISSUE TITLE
Adding extensions to mocha globally

### ISSUE THREAD

**Issue by tiriana** [webdriverio/webdriverio#1947]
## The problem

That's not so much of an issue, rather a request for help/hint. 
Is there a hook after mocha is imported but before spec is built? (see details for more info)

## Environment

* WebdriverIO version: 4.2.5
* Node.js version: v6.9.2
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Standalone
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable): framework: 'mocha', services: ['selenium-standalone'], chai

## Details

I'm trying to add ```it.each``` globally - https://www.npmjs.com/package/it-each#integration. I use mocha as test runner. 
What I tried: I added it in ```before``` and ```onPrepare``` hooks, but it's too late in execution, as tests tree is built already. I tried to add it in wdio.conf.js itself, but it's too early in runtime - mocha is not yet imported.
Is there a hook after framework was imported and before spec is read and built?

I managed to add this extension only in given spec file, but this only adds it locally, and I'd like to have ```it.each``` everywhere.

## Link to Selenium/WebdriverIO logs

https://gist.github.com/tiriana/5c6bf4ae9dd96277232fa7892cf08eb3

## Code To Reproduce Issue [ Good To Have ]

example usage (importing in before hook) https://gist.github.com/tiriana/30c5f49855ae7cc04167d5d889764860

**Comment by christian-bromann** [comment]
@tiriana the before hoo gets executed after Mocha was initialised and before test are run (see https://github.com/webdriverio/wdio-mocha-framework/blob/master/lib/adapter.js#L104)

**Comment by tiriana** [comment]
@christian-bromann Thx.

If anyone wants to know how I finally ovecame this problem - I added "helpers.js" to specs. You need to use [glob 'or' pattern](http://unix.stackexchange.com/questions/50220/using-or-patterns-in-shell-wildcards)

```
specs: [
        "{./mochaExtensions.js,./specs/**/*spec.js}"
    ],
```

mochaExtensions.js simple contains ```require("it-each")({ testPerIteration: true });```

I didn't investigate more why it wasn't working when put in wdio ```before``` hook.

**Comment by christian-bromann** [comment]
@tiriana you might be also able to use Mochas require option

**Comment by tiriana** [comment]
I need to take back what I've written in previous post. I got some success, got excited that I've find a solution and post it here. Sorry for that. tl;rd - adding helpers.js to spec doesn't help either. 

@christian-bromann thx for mochas require option. I forgot about it. 
Now I used it, and it indeed works fine (I mean - helpers file is required before), but it still does not help. It extend mocha with ```it.each``` but it's not visible in other specs. I guess it's because each spec is ran in separate [fiber contex](https://github.com/webdriverio/wdio-mocha-framework/blob/master/lib/adapter.js#L95), so they "don't" see each other.

I guess the only way to have ```it.each``` in in each spec is to either add it directly, or through some common_extension module required by all specs.

**Comment by christian-bromann** [comment]
oh I see the problem .. the `it.each` is not properly wrapped into fibers .. if you need to run a test within a loop I would recommend to just call the `it` function within a for loop or something like that. Otherwise I don't see a quick solution for that

**Comment by tiriana** [comment]
@christian-bromann thanks for your help. I'll go with ```forEach``` I guess
