### ISSUE TITLE
wdio config fails with NodeJS 7.7.3 or 7.7.4 on Windows 7

### ISSUE THREAD

**Issue by kibbled** [webdriverio/webdriverio#1953]
## The problem

Running
.\node_modules\\.bin\wdio config

Results in the following error

705 error Windows_NT 6.1.7601
706 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-D" "wdio-mocha-framework" "wdio-dot-reporter"
707 error node v7.7.3
708 error npm  v4.1.2
709 error code ELIFECYCLE
710 error fibers@1.0.15 install: `node build.js || nodejs build.js`
710 error Exit status 1
711 error Failed at the fibers@1.0.15 install script 'node build.js || nodejs build.js'.
711 error Make sure you have the latest version of node.js and npm installed.
711 error If you do, this is most likely a problem with the fibers package,
711 error not with npm itself.
711 error Tell the author that this fails on your system:
711 error     node build.js || nodejs build.js
711 error You can get information on how to open an issue for this project with:
711 error     npm bugs fibers
711 error Or if that isn't available, you can get their info via:
711 error     npm owner ls fibers
711 error There is likely additional logging output above.

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 7.7.3 or 7.7.4
* Windows 7 x64

## Details

I was able to get wdio config to work by uninstalling the current version of NodeJS (7.7.4) and installing the latest LTS version of NodeJS (6.10.1)

**Comment by christian-bromann** [comment]
Seems an issue within the fibers project. Please file an issue there.

**Comment by kibbled** [comment]
I thought that as well but I could install fibers by itself with no problem, definitely very odd

**Comment by christian-bromann** [comment]
Maybe it's fixed with latest fibers version. I will check and make sure that it's up to date.

**Comment by kibbled** [comment]
Let me know when you think it's fixed and I'll upgrade back to Node 7.x and try again. Thanks
