### ISSUE TITLE
Test fails saying "An element could not be located on the page using the given search parameters" even though all elements are present 

### ISSUE THREAD

**Issue by sumalatha1920** [webdriverio/webdriverio#1954]
# The problem

My test case fails half of the time saying that 'An element could not be located on the page using the given search parameters.' All the elements are present and visible and I'm not sure what is going wrong. (chrome or firefox on MAC)

## Environment

*"jasmine": "^2.5.3",
* "mysql": "^2.13.0",
* "selenium-standalone": "^6.1.0",,
* "wdio-jasmine-framework":"^0.3.0",
* "wdio-spec-reporter": "^0.1.0",
* "webdriverio": "^4.6.2"
* Node.js version:v7.7.1

* if wdio testrunner, running synchronous or asynchronous tests: synchronous

## Details

I've written my code in separate it blocks as well but to no avail. 

##selenium logs:
https://gist.github.com/sumalatha1920/2cb8d14c3fe7144d1e3d20c2015da956

## Code To Reproduce Issue [ Good To Have ]

it('When: User accesses the web app, he should land on the home page', function () {
 signInPage.loginPage();
signInPage.enterValueInEmailField();
signInPage.enterValueInPasswordField();
 signInPage.clickSignIn();
    }); 

page objects:
function enterValueInEmailField(){
$('input[type="email"]').setValue('test123@gmail.com');
}

function enterValueInPasswordField(){
$('input[type="password"]').setValue('Password123^');
}

function clickSignIn(){
	var signIn = $('button[type="submit"]');
	signIn.click();
}

**Comment by christian-bromann** [comment]
Sorry but this is hardly a webdriverio issue. Please use explicit waits to make sure you don't run into any race conditions. Also join our Gitter chat for these kind of questions , this is not necessary an issue.
