### ISSUE TITLE
Cannot get unique configuration per instance

### ISSUE THREAD

**Issue by GeoffreyBooth** [webdriverio/webdriverio#1957]
## The problem

I’m trying to run tests in parallel, that each download files into Chrome’s downloads folder. Sometimes a test gets confused because a file appears in the downloads folder as a result of another test. I’d like to have each instance of Chrome downloading files into a subfolder based on that instance, e.g. `downloads/3161f128-2add-4629-a6e2-ced951ebc1dd/`, or some unique subfolder that tests can watch without getting confused by results from other simultaneous tests.

Chrome’s downloads folder is set in `wdio.conf.js`, under `capabilities.chromeOptions.prefs.download.default_directory`. But even if I set this to something dynamic, say `` `downloads/${Date.now()}` ``, all of the instances of Chrome get spawned with the same value for `default_directory`. It appears that the config in this file is read once and cached, and used for each browser instance. I also don’t see a way to change `default_directory` after the instance has been started, for example in a `before` hook. See also https://gitter.im/webdriverio/webdriverio?at=58dbf60b8bb56c2d11568856.

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 7.5.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): cucumber

**Comment by christian-bromann** [comment]
@GeoffreyBooth I believe the best thing to do is to change the default directory in the beforeSession hook to a unique directory. You can set it to the session id because it requires to have a running chrome and you can change this args on runtime. Let me know if the solution works for you.

**Comment by GeoffreyBooth** [comment]
Yes! Thank you, this seems to work. I was trying `before`, but using `beforeSession` seems to be the trick.

I guess the session doesn’t exist yet at that point, hence the hook name, so there is no session ID. But if I use a unique value here it seems to carry forward:

```js
var uuid = require('uuid/v4');
// …
beforeSession: function (config, capabilities, specs) {
  capabilities.chromeOptions.prefs.download.default_directory += uuid();
}
```

**Comment by GeoffreyBooth** [comment]
@christian-bromann I might have written too soon. I have `maxInstances` set to 5, but the above code creates 17 subfolders for me. I guess 17 sessions are getting created?

Some tests are failing, saying that the downloaded files they’re watching for never appear. (These tests passed before I made this change.) I guess some of the tests are run by sessions that aren’t using the download folders that I’m specifying via this code. Is there a way to get the session ID at this point, or does it not exist yet?

**Comment by christian-bromann** [comment]
> I guess 17 sessions are getting created?

You can right

> Is there a way to get the session ID at this point, or does it not exist yet?

You can't get the session ID before you start the session :-P

> saying that the downloaded files they’re watching for never appear

Don't know what that means

**Comment by locddspkt** [comment]
> ```js
> var uuid = require('uuid/v4');
> // …
> beforeSession: function (config, capabilities, specs) {
>   capabilities.chromeOptions.prefs.download.default_directory += uuid();
> }
> ```

I've justed tried this but it didn't work.

I tried with array instead:
capabilities.chromeOptions.prefs['download.default_directory'] = '/path/to/my/folder';

It works
