### ISSUE TITLE
BUG: setViewportSize failing on safari

### ISSUE THREAD

**Issue by treaz** [webdriverio/webdriverio#1963]
## The problem

On Safari 10.1, setViewportSize doesn't work. I'm using the test from the [docs](http://webdriver.io/api/window/setViewportSize.html#Usage)
```
it('should resize the current viewport', function () {
        browser.setViewportSize({
            width: 500,
            height: 500
        });
        var windowSize = browser.windowHandleSize();
        console.log(windowSize.value); // outputs: { width: 500, height: 602 }
    });
```
## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 6.9.1
* wdio testrunner
* sync: true
* Additional wdio packages used (if applicable): see gist of wdio config

## Link to Selenium/WebdriverIO logs
https://gist.github.com/treaz/d081620c2a4913132ba33d80d0450b8f

## Code To Reproduce Issue [ Good To Have ]
I've used ./node_modules/.bin/wdio config to initialize a new project and then added the test from above.
I'm using this wdio configuration: https://gist.github.com/treaz/1328049b586b160f9292029849a7ca7a

**Comment by spacedawwwg** [comment]
I am having the same issue on Windows Chrome

```
    this.Given('I log into the site as an administrator', function() {
        browser.setViewportSize({
            width: 1400,
            height: 1050
        });
        browser.waitForVisible('#username');
        browser.setValue('#username', envCreds.cieAdmin.username)
        browser.setValue('#password', envCreds.cieAdmin.password);
        browser.submitForm('#loginForm');
        var title = browser.getTitle();
        browser.waitForExist('.header__navigation');
    })
```

**Comment by WillBrock** [comment]
I'm having the same problem but only after upgrading mac to Sierra 10.12. The previous version of mac worked fine. 

For me, upgrading to sierra has caused a few other problems that I'm still working out. 

watiForExsit() has been failing when I updated to Sierra 10.12. This might be because I was on selenium 3.0.1 and needed to update to 3.3.1 but the npm standalone doesn't automatically do that.

1) I think specifying... seleniumInstallArgs : {version : `3.3.1`} in the config file helped if using the standalone service.
If selenium is already installed it will take that version rather than the newest version.. but I could be wrong.

2) It seems like I can run selenium 3.3.1 manually without npm and the wdio service and it'll work.

**Comment by WillBrock** [comment]
The selenium-standalone package had both 3.0.1 and 3.3.1 inside it. Removing the 3.0.1 resolved my problem.

**Comment by christian-bromann** [comment]
This is a safaridriver issue that I can't fix. Please file a bug report in the safaridriver project. Thanks!

**Comment by treaz** [comment]
@christian-bromann I would gladly open a bug report in the safaridriver project, but I have no idea what to write in that bug report. Obviously, I can reuse the bug report from this bug. 

Can you explain how you reached the conclusion that this is a safaridriver issue?

**Comment by christian-bromann** [comment]
@treaz because the error comes from the safaridriver and is not from WebdriverIO. WebdriverIO just follows the JSONWire protocol (and Webdriver protocol) soon. So if an error like this happen the driver is usually to blame 😉

**Comment by burg** [comment]
This was a safaridriver bug. It was fixed in Safari Technology Preview 28. You can verify the fix in the latest Safari Technology Preview, macOS High Sierra seed, or Safari 11 beta on macOS Sierra. <https://developer.apple.com/safari/download/>

**Comment by christian-bromann** [comment]
Hey @burg,
nice to see you here. Thanks for the info.
Cheers

**Comment by burg** [comment]
No problem. Feel free to tag me if folks have similar questions in the future.
