### ISSUE TITLE
Running test without the seleniumhub with wdio runner

### ISSUE THREAD

**Issue by germanp** [webdriverio/webdriverio#1965]
Is there a way to run the test using only the chromedriver or geckodriver? I mean instead of using the selenium standalone service. I'm using the wdio runner. Thanks.

**Comment by monolithed** [comment]
See https://github.com/webdriverio/webdriverio/pull/1933

**Comment by christian-bromann** [comment]
@germanp yes. For the latest Geckodriver we need to work on the PR first because it supports Webdriver protocol only. The chromedriver however can be used as standalone. Just start it by calling:

```sh
$ chromedriver --url-base=/wd/hub --port=4444
```

And you are set. Let me know if you have any more questions.

**Comment by germanp** [comment]
Thanks for the directions, I managed to get it running with the chromedriver. I'm using chromedriver npm package and I added this to the configuration:
`
const chromedriver = require("chromedriver");

wdioConf.onPrepare = (config, capabilities) => {
  const args = ["--url-base=/wd/hub", "--port=4444"];
  chromedriver.start(args);
};

wdioConf.onComplete = (config, capabilities) => {
  chromedriver.stop();
};
`

No more need to install java, thank you!
