### ISSUE TITLE
Unable to run tests behind corporate proxy

### ISSUE THREAD

**Issue by simbro** [webdriverio/webdriverio#1967]
## The problem

I was trying to tun tests after having initializing WebDriverIO for an existing project.  I would like to specify the proxy details for connection to the internet, so that WebDriverIO can download it's dependencies to run the tests (i.e. GeckoDriver).  I'm unable these details in the docs.

## Environment

* WebdriverIO version: 4.6.2
* Node.js version:  6.9.1
* wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous

## Details

The tests fail because it can't download geckodriver, probably because of proxy restrictions.

```
A service failed in the 'onPrepare' hook
Error: Could not download https://github.com/mozilla/geckodriver/releases/download/v0.13.0/geckodriver-v0.13.0-win64.zip: Error: tunneling socket could not be established,
```

## Link to Selenium/WebdriverIO logs

No log file produced as tests were not run.

**Comment by aparna-gopalakrishnan** [comment]
@naveen thiyagarajan , are you behind a proxy? If so, you can provide the path to a specific location where your node modules are located. I have done so.
