### ISSUE TITLE
Question - difference between webdriverio and NPM selenium-webdriver

### ISSUE THREAD

**Issue by ORESoftware** [webdriverio/webdriverio#1968]
Hey all, sorry for the newb question

I am wondering what the difference is between:

`npm install webdriverio`
as in
https://www.npmjs.com/package/webdriverio

and

`npm install selenium-webdriver`
as in 
https://www.npmjs.com/package/selenium-webdriver

any insights would be helpful thanks

**Comment by ORESoftware** [comment]
my guess is that webdriverio is just a wrapper around selenium-webdriver module? or is separate?

**Comment by mattc41190** [comment]
webdriverio is an entirely different set of bindings to the selenium API.

**Comment by mattc41190** [comment]
Basically selenium at it's root level is an API to the selenium that looks like:

COMMAND /some/command
DATA {any: [post, data]}
RESULT: Success

Both selenium-webdriver and webdriverio wrap this API in different ways. Webdriverio does it more intelligently in my opinion.

**Comment by monolithed** [comment]
@ORESoftware, it seems you didn't read any documentation about these projects at all. Please, read the documentation before you ask such questions.
This project is not just a stupid wrapper around the JSONWire and WebDriver protocols.

**Comment by mattc41190** [comment]
@monolithed I totally agree it's more than that, but at a root level that is what it is.

The description on the homepage:

"It basically sends requests to a Selenium server via the WebDriver Protocol and handles its response. These requests are wrapped in useful commands and can be used to test several aspects of your site in an automated way."

**Comment by ORESoftware** [comment]
@monolithed thanks :) I have been reading about it for the last two days and it simply wasn't clear to me, this helps clarify. I have read documentation on both projects. If it's clear, a link to the documentation that answers my original question would actually make me feel stupid :)

**Comment by christian-bromann** [comment]
Thanks for jumping in. I absolutely agree with the commenters above. Thanks!

**Comment by Zearin** [comment]
Just want to say that I had this exact same question.  Glad I found this thread!

* @ORESoftware: Thanks for asking it.
* @monolithed: There’s no need to inflict shame for asking this question. As @ORESoftware [clarified](https://github.com/webdriverio/webdriverio/issues/1968#issuecomment-292003163), sometimes documentation does not give a clear answer to questions like this.

**Comment by baptx** [comment]
Isn't Webdriver.io a reimplementation of Selenium server using JavaScript instead of Java? Otherwise is there a project like this or another tool that can replace PhantomJS / SlimerJS and is not depending on a JVM?

**Comment by christian-bromann** [comment]
> Isn't Webdriver.io a reimplementation of Selenium server using JavaScript instead of Java?

No. WebdriverIO is a framework that implements the WebDriver protocol and comes with plugins that provide similar functionality as the Selenium Standalone server.

> Otherwise is there an implementation of Selenium server in JavaScript or C / C++?

Not that I know of. What is the problem with the original Selenium server?

> Or another tool that can replace PhantomJS / SlimerJS and is not depending on a JVM?

You can use Chrome headless with Chromedriver. No need for a JVM there.

**Comment by baptx** [comment]
@christian-bromann thanks for the clarification, I was looking for a web scraping tool without having a Java virtual machine as dependency, like it is possible to do with PhantomJS / SlimerJS (theses 2 tools are not maintained a lot for the moment but it may change in the future). I also have a preference for languages like JavaScript and C / C++ so I would have preferred if Selenium was written in one of these languages if I want to contribute.
After searching, it looks like the tool TestCafe does not use Selenium so it may be an alternative.
So if I understand correctly it is also possible to use WebdriverIO with ChromeDriver or even GeckoDriver and then we don't need Selenium server?

**Comment by mgrybyk** [comment]
@baptx yes, webdriverio can communicate with any browser driver that supports webdriver protocol, including chrome and gecko drivers. 
You can also use devtools automation protocol that uses puppeteer underneath, it might be even better for your purposes.
You may try both approach to understand which one works better for you

**Comment by christian-bromann** [comment]
You can find here: https://webdriver.io/blog/2019/09/16/devtools.html at the bottom an example to run these headless. Just ensure you have both drivers running.
