### ISSUE TITLE
IE 11 Not working

### ISSUE THREAD

**Issue by obender** [webdriverio/webdriverio#1969]
The issue descibed here:
http://stackoverflow.com/questions/43235474/how-i-can-start-ie-in-32bit-mode-in-webdriver-io/43248529#43248529

What is the walk around for this issue 
https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/5116

**Comment by christian-bromann** [comment]
This is not an issue of WebdriverIO but rather one of the iedriver.
