### ISSUE TITLE
Jenkins selenium webdriver io how did you work

### ISSUE THREAD

**Issue by ybozkurt12** [webdriverio/webdriverio#1973]
## The problem
Jenkins server can not run selenium webdriver io selenium 3.0 when will it or will there be a plugin
@jeresig @Vinnl @wouter

**Comment by christian-bromann** [comment]
@ybozkurt12 can you please explain in more detail what the issue is and what doesn't work? Maybe add logs or anything.

**Comment by ybozkurt12** [comment]
@christian-bromann  Problem I am writing unit tests using webdriver io I am doing this using selenium 3.0 Then I want to run it using jenkins by the server does not work  WebDriver io uses selenium 2.0 selenium 3.0 when to switch or how to run the project

**Comment by christian-bromann** [comment]
> Problem I am writing unit tests using webdriver io

You should not write unit tests with WebdriverIO

> does not work WebDriver io uses selenium 2.0 selenium 3.0 when to switch or how to run the project

WebdriverIO also works with Selenium 3.0 using selenium standalone server

**Comment by ybozkurt12** [comment]
@christian-bromann WebdriverIO also works with Selenium 3.0 using selenium standalone server
I want to run unit tests using jenkins on linux server side
But I can not integrate jenkins selenium 3.0 library.
There is no webdriver io patch on jenkins 
I can run local webdriver io but it is not working on the server side

**Comment by christian-bromann** [comment]
> I want to run unit tests using jenkins on linux server side

So why do you use WebdriverIO then? Karma might be the better tool for that. WebdriverIO is for e2e tests. Please seek support in our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) channel.
