### ISSUE TITLE
Run selenium server with nodeJS

### ISSUE THREAD

**Issue by nacimgoura** [webdriverio/webdriverio#1974]
Hello,
Thank you very much for your work.
I want to make a nodejs script that uses webdriverio and selenium-server, but I want to run the selenium server from my script nodejs. I try with selenium-standalone but I failed to make it work.
Is it possible ? If yes, how ?
Thank you!

**Comment by MS-elug** [comment]
Hello,

wdio already have a plugin to run automatically a selenium driver with tests are executed,
you should have a look at [wdio-selenium-standalone-service](https://github.com/webdriverio/wdio-selenium-standalone-service)

Best regards,
Mathieu

**Comment by nacimgoura** [comment]
Okay, thank you, I'll look. 
I do not use wdio so I would have liked a module that does not use it.
But I'll try to integrate wdio to try.

**Comment by christian-bromann** [comment]
Thanks @MS-elug! This is the answer! Also for these kind of questions please use our Gitter support channel. This is not an issue of WebdriverIO

**Comment by christian-bromann** [comment]
There is no module for that using the standalone mode. You just use selenium-standalone in this case

**Comment by nacimgoura** [comment]
Thank you, I succeeded.
Have a good day!
