### ISSUE TITLE
Watch mode keeps running old versions of a test.

### ISSUE THREAD

**Issue by d4rkr00t** [webdriverio/webdriverio#1976]
## The problem

Watch mode keeps running old versions of a test. For example I have 1 "it" in my test suite. Every time i change it i get +1 results.

<img width="907" alt="screen-shot-2017-04-05-at-1 07 01-pm" src="https://cloud.githubusercontent.com/assets/200119/24895487/fb3cbb72-1ed3-11e7-8d30-ab44adc645ac.png">

I tried with and without typescript.

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 6.10.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: async
* Additional wdio packages used (if applicable): 
  - "wdio-mocha-framework": "^0.5.9",
  - "wdio-selenium-standalone-service": "0.0.8",
  - "wdio-spec-reporter": "^0.1.0",

## Code To Reproduce Issue [ Good To Have ]

https://gist.github.com/d4rkr00t/e756c64838df60ffc4900f5f9acc273f

**Comment by fernandopasik** [comment]
I've seen the same with `wdio-jasmine-framework`

**Comment by christian-bromann** [comment]
We will reimplement the watch mode in v5 again and try to mitigate the issue.
