### ISSUE TITLE
Potential Memory Leak in Test Runner

### ISSUE THREAD

**Issue by jankcat** [webdriverio/webdriverio#1978]
## The problem

I am trying to run multiple mocha specs with several tests in each spec file, across 2-3 browsers on saucelabs. It seems that the parent node process is not releasing memory when the child process closes:

First set of child processes:
![screen shot 2017-04-11 at 1 16 50 pm](https://cloud.githubusercontent.com/assets/7744158/24927002/b90b5fce-1eba-11e7-9703-08ef208617a7.png)

Gaining memory on the parent as we send commands to the grid:
![screen shot 2017-04-11 at 1 18 11 pm](https://cloud.githubusercontent.com/assets/7744158/24927047/d2c1eb68-1eba-11e7-8cc9-ad5cbc846c3f.png)

After two of the children have completed, new ones start:
![screen shot 2017-04-11 at 1 21 10 pm](https://cloud.githubusercontent.com/assets/7744158/24927076/ef10192a-1eba-11e7-9f8e-22d02b76c26d.png)

I have built an example here: https://github.com/jankcat/wdio-example-leak
Run the ./run.sh file after setting your sauce creds in main.config.js

## Environment

* WebdriverIO version: webdriverio@4.6.2
* Node.js version: 7.7.2
* WDIO Test Runner
* running synchronous tests
* Additional wdio packages used:
  * "wdio-mocha-framework": "^0.5.9"
  * "wdio-sauce-service": "^0.3.1"
  * "wdio-screenshot": "^0.5.2"

## Link to Selenium/WebdriverIO logs

https://gist.github.com/jankcat/86758abb32156f63e8e402b308d41071

## Code To Reproduce Issue [ Good To Have ]

I have built an example here: https://github.com/jankcat/wdio-example-leak
Run the ./run.sh file after setting your sauce creds in main.config.js

**Comment by jankcat** [comment]
Also, here is the error I get in terminal once the memory hits 1.5gb on the parent process:
```
<--- Last few GCs --->

[50353:0x103801600]   952483 ms: Mark-sweep 1397.7 (1443.5) -> 1397.7 (1443.5) MB, 18.4 / 0.0 ms  allocation failure GC in old space requested
[50353:0x103801600]   952505 ms: Mark-sweep 1397.7 (1443.5) -> 1397.7 (1411.5) MB, 22.2 / 0.0 ms  last resort 
[50353:0x103801600]   952524 ms: Mark-sweep 1397.7 (1411.5) -> 1397.7 (1411.5) MB, 19.4 / 0.0 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace ========================================

Security context: 0x1a52a5f266a1 <JS Object>
    0: builtin exit frame: parse(this=0x1a52a5f1a7d1 <a JSON with map 0x32a4d8d853d9>,0x314bc6013049 <Very long string[2854302]>)

    1: onread [internal/child_process.js:471] [pc=0x20833d39f85a](this=0x8cf40bc7e01 <a Pipe with map 0x32a4d8df03b9>,nread=7328,pool=0x314bc60133a9 <an Uint8Array with map 0x2ab176ab1959>,recvHandle=0x27b3db482311 <undefined>)

==== Details ========================...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

**Comment by jankcat** [comment]
I have played around with this a bit more, investigation and what not. Here are some notes:
For both sets below, I removed wdio-screenshots and wdio-sauce-service, added wdio-selenium-standalone-service.

## browser.screenshot() instead of wdio-screenshots
I ran test cases using the browser.screenshot() function instead of wdio-screenshots.
Repo: https://github.com/jankcat/wdio-example-leak/tree/native-screenshot
Results:
I start the test suite, RAM starts out normal:
![screenshot - start](https://cloud.githubusercontent.com/assets/7744158/25155025/4b49d8c6-2450-11e7-9fb1-cf48aa397c44.png)

After roughly 60~ test cases, each taking 4 screenshots of the viewport, I run out of memory on the parent process:
![screenshot - end](https://cloud.githubusercontent.com/assets/7744158/25155027/4b4d422c-2450-11e7-844a-95acccbd9b27.png)

Console Output: https://gist.github.com/jankcat/86758abb32156f63e8e402b308d41071#file-memory-leak-log-txt

## No screenshotting, just page movement
I ran test cases using just browser.scroll(). No screenshots were taken using any means.
Repo: https://github.com/jankcat/wdio-example-leak/tree/no-extras
Results: 
I can see the memory rising slowly, much slower than when taking screenshots, but still rising. The parent process started at around 50mb:
![plain - start](https://cloud.githubusercontent.com/assets/7744158/25155024/4b496f4e-2450-11e7-8ec5-d32ee5cf11f1.png)

After roughly 1700 test cases, each test simply scrolling around the page a few times, the memory had risen from 50~mb to 150~mb. That was 15 specs, 9 test cases per spec, across 13 browsers.
![plain - end](https://cloud.githubusercontent.com/assets/7744158/25155026/4b4caf06-2450-11e7-9ab2-be6bf4d869a3.png)

**Comment by christian-bromann** [comment]
@jankcat thanks for investigating .. did you store the screenshot on the fs?

**Comment by jankcat** [comment]
I did not store the screenshot anywhere in the [browser.screenshot() example](https://github.com/jankcat/wdio-example-leak/tree/native-screenshot), just ignored the return. The [wdio-screenshot example](https://github.com/jankcat/wdio-example-leak) stores the screenshots to the fs yes.

**Comment by jankcat** [comment]
I have found my leak I believe. Every command is logged in the ReporterStats object, including the raw screenshot data, via the [output function](https://github.com/webdriverio/webdriverio/blob/master/lib/utils/ReporterStats.js#L246).

Killing off the [payload parameter](https://github.com/webdriverio/webdriverio/blob/master/lib/utils/ReporterStats.js#L251) with an empty object rapidly reduced the memory gains on the parent, the remaining gains coming only from the [type parameter](https://github.com/webdriverio/webdriverio/blob/master/lib/utils/ReporterStats.js#L250).

I am testing this out, looking for repercussions, but if it is doable I would love to add some sort of flag to the options/config to lower the ReporterStats logging levels, or alternatively completely remove screenshot data from the payload.

**Comment by christian-bromann** [comment]
> completely remove screenshot data from the payload.

I would prefer that and not make WebdriverIO overconfigurable

**Comment by jankcat** [comment]
Closed with #1993

**Comment by christian-bromann** [comment]
Thanks so much for investigating and fixing this bad boy 👍

**Comment by jankcat** [comment]
No worries! Glad to help. Plus, it was limiting my ability to parallelize my visual validation suite, so I had the proper motivation ;)

**Comment by christian-bromann** [comment]
I think I will assume what's in master right now sometime tomorrow

**Comment by jankcat** [comment]
Awesome, thanks for the update. I await your npm publish.
