### ISSUE TITLE
Unable to run webdriverio tests using phantomjs

### ISSUE THREAD

**Issue by lavanyamani-guidewire** [webdriverio/webdriverio#1981]
## The problem
I'm trying to run webdriverio tests in headless browser. So I tried using phantomjs.

Configuration in wdio.conf.js:  
=====================
capabilities: [{
    browserName: 'phantomjs'
  }],
services: ['phantomjs'],

Simple Test:
=========
describe('Simple test', () => {
  it('Simple test', () => {
    const title = browser.url('https://www.google.com/').getTitle();
    console.log(title);
    browser.click('input[id="lst-ib"]');
  });
});

## Environment
* WebdriverIO version: 4.6.2
* Node.js version: 6.9.2
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): wdio-phantomjs-service - 0.2.2

## Details
For any type of element selector, I'm getting the same error  "An element could not be located on the page using the given search parameters." I could see only browser.url().getTitle() returning value.
I'm not sure what is the problem. Please help!

## Error
0 passing (4.60s)
1 failing

1) Simple test Simple test:
An element could not be located on the page using the given search parameters.
running phantomjs
Error: An element could not be located on the page using the given search parameters.
    at Promise.F (node_modules/babel-runtime/node_modules/core-js/library/modules/_export.js:35:28)
    at element("input[id="lst-ib"]") - click.js:12:17
    at click("input[id="lst-ib"]") - at Context.<anonymous> (uiTest/tests/googleTest.js:5:13)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node@6/6.9.2/bin/node" "/usr/local/bin/npm" "run" "wdio"
npm ERR! node v6.9.2
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! gw-sbo-app2@0.1.0 wdio: `wdio`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gw-sbo-app2@0.1.0 wdio script 'wdio'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gw-sbo-app2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     wdio
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gw-sbo-app2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gw-sbo-app2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lmani/Documents/MonoRepo/dsb/submission/submission-ui/npm-debug.log

**Comment by christian-bromann** [comment]
Have you read the error message? It clearly says:

> An element could not be located on the page using the given search parameters.

So PhantomJS is running but the element you are trying to fetch doesn't exist.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
