### ISSUE TITLE
Browser.keys("Enter")/ "Return" is not working in firefox

### ISSUE THREAD

**Issue by Shahunks** [webdriverio/webdriverio#1983]
## The problem
Browser.keys("Enter")/ "Return" is not working in firefox
Briefly describe the issue you are experiencing (or the feature you want to see added to WebdriverIO). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, join the Gitter chat room ([![Gitter](https://badges.gitter.im/Join Chat.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge))!

## Environment

* WebdriverIO version: v4
* Node.js version: 6.10.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdiotestrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
Please provide more information and details about the issue or ask in the [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) channel first. I can't do anything here.

**Comment by Windso** [comment]
Why was this was closed?

I am also having this issue. When I run `browser.keys(['Enter']);` from wdio, I get error `sendKeysToActiveElement` from Selenium when running on Firefox. Running against Chrome works just fine.

**Comment by christian-bromann** [comment]
> Running against Chrome works just fine.

This is probably an issue with the Geckodriver. This issue was closed because the problem is not related to WebdriverIO and is located in the underlying automation technology. For more question please reach out in our Gitter support channel. Thanks!
