### ISSUE TITLE
Unable to pass dynamic arguments into functions , instead of hardcoded strings

### ISSUE THREAD

**Issue by sandeepv137** [webdriverio/webdriverio#1984]
Hi,
We are facing an issue while trying to pass argument stored in var .
The issue is we are storing the dynmically retrived div id in a variable and then passing it to .moveToObject function.

But the function throws back error ; 
Error: invalid selector: No selector specified

Wanted to know how we can pass arguments stored in variables into various functions.

For instance in the code below , we are retiring sectionId via execute , storing it in sectionId  variable .
then using it later on in moveToObject.

all functions seems to work when we are giving arguments inside "" quotes, but in our case we cannot do this. Please help us out how we can achieve this.

```js
it('drag and drop should work ', function () {
    var sectionId = "";
    // load page, then call function()
    return driver     
      .url('http://localhost:9000')
      .pause(7000)   
      .click('#layoutWizardButton')
      .click('#tableWizardBuild')
      .pause(3000)
      .execute(function(){
         sectionId =  window.document.getElementById('Section1');
      }  
      .moveToObject('#ribbon-radio-tile')
      .buttonDown()   
      .moveToObject(sectionId) ----> errors out here 
      .buttonUp()
      .pause(2000)     
    .end()
  });
```

**Comment by christian-bromann** [comment]
@sandeepv137 everything you do within `execute` is executed in the browser. To get the data in your node process you have to return the value and receive it from the execute command. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by sandeepv137** [comment]
Hi the gist of the issue is , i am trying to pass value stored in a say var sectionId = '#Section1123' , to .moveToObject(sectionId ) , but the error i get is --. Error: invalid selector: No selector specified
i do not want to do .moveToObect('#Section1123')
instead  need to take it from a variable sectionId, thus doing .moveToObject(sectionId ) 

how can i do it ?
