### ISSUE TITLE
Crossbrowser

### ISSUE THREAD

**Issue by vpattonjr** [webdriverio/webdriverio#1985]
Is there anyway to use WebdriverIO with Crossbrowser?
https://crossbrowsertesting.com/

**Comment by christian-bromann** [comment]
Yes, just use host and port according to their docs. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
