### ISSUE TITLE
Question: Can WebDriverIO talk to Chrome Debugging Protocol?

### ISSUE THREAD

**Issue by enapupe** [webdriverio/webdriverio#1988]
It seems it just "outputs" to selenium, is it possible to make it talk to CPD?
Considering that chrome-headless is out it might be interesting to remove selenium dependency.

**Comment by christian-bromann** [comment]
> interesting to remove selenium dependency.

WebdriverIO mainly talks the Webdriver protocol. There is no such thing as a dependency to Selenium. The remote debugging protocol is already blocked by the Chromedriver who uses the connection to translate Webdriver commands to the browser.

**Comment by enapupe** [comment]
Awesome! So I could totally run webdriverio backed by a regular chrome install running on my machine?

**Comment by christian-bromann** [comment]
> So I could totally run webdriverio backed by a regular chrome install running on my machine?

Yes but you need a running chromedriver server to do so

**Comment by wayneseymour** [comment]
I think this is a great idea, btw.  I've been looking into the CDP for a few months, off and on.

**Comment by christian-bromann** [comment]
@wayneseymour check out https://github.com/webdriverio/remotedriver where I experimented to run Chrome with Webdriver and having an open connection to the CDP at the same time
