### ISSUE TITLE
commands are not synchronous

### ISSUE THREAD

**Issue by vincentlabatut** [webdriverio/webdriverio#1990]
## The problem

When running standalone tests with mocha, the selenium commands are not send synchronously and failures are not reported. This may be a noob question, but I read everywhere that wdio v4 was now synchronous by default. And can't find any sync option for standalone mode.

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 7.2.1
* [Standalone mode]

## Details

I do mocha on the standalone examples from the webdriverio package. I'm using appium so I can watch when commands are received on the server and their results.

`mocha examples\standalone\webdriverio.with.appium.nativeapp.js`
(customized with working caps for my app)

I've added console.log in the "it" function. They are displayed synchronously when I debug. The appium commands are only received at the end of the test. The test passes even if the searched elements are not found in the current page.
I'd need synchronous execution, and synchronous fail. When I do 
`client.click("//*[contains(@text,'Search')]");`
I want this line to fail if the button is not found.

Note: I suspected mocha for a while, but it may not be because the console is logging synchronously (and I'm using mocha in synchronous mode)
Note2 : my app is launched during the init, subsequent commands looks like they are queued
Note 3: This may be an old way of writing tests (synchronous, no promises), but this is what works for us with other frameworks.

sorry if this is too noobish.. thanks for your help

## Steps To Reproduce Issue

debug the following :
`mocha examples\standalone\webdriverio.with.appium.nativeapp.js`

with a local appium running, commands are received after the test code has finished, failure of commands are ignored.

**Comment by christian-bromann** [comment]
Please see http://webdriver.io/guide/getstarted/modes.html. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by vincentlabatut** [comment]
Hi, thanks for the link, I already read quite a few pages on the web site, nothing helps. I'm looking for a synchronous mode without wdio runner.
Sorry for the issue, I found no other way to contact you, despite the few hours I spent on the site, I missed the link to the gitter, now I see It at the bottom of the page. thanks. (maybe I expected a major "DISCUSSION", "CHAT" of "FEEDBACK" link at the top of the page...)

**Comment by christian-bromann** [comment]
> I'm looking for a synchronous mode without wdio runner.

You can't run async stuff synchronous out of the box. You may want to try async/await. Then you can use the standalone version. But I recommend using the testrunner as it is way more powerful as the standalone version

> (maybe I expected a major "DISCUSSION", "CHAT" of "FEEDBACK" link at the top of the page...)

There is a big fat `Need help?` section at the bottom of the page 😉

**Comment by vincentlabatut** [comment]
Went to the gitter to chat, and now i'm using wdio, it runs synchronously and I'm getting a failure in my test, so I'm very happy :)

yes, shame on me, I missed this help block in the page. And thanks for the help!
