### ISSUE TITLE
Can I reuse the same browser instance for all specs?

### ISSUE THREAD

**Issue by karanbajaj2209** [webdriverio/webdriverio#1992]
Currently, for each spec file the browser instance opens and when all the test are done it closes the browser instance, then for the second spec file it does the same thing. Can I avoid this situation and have the same browser instance for all specs?

**Comment by christian-bromann** [comment]
@karanbajaj2209 yes, just run all tests in one spec. You can include other specs into one spec file so you still split tests up into different files. Please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by chungshaku38** [comment]
@christian-bromann : Sorry I know this was closed, but could you please tell me how we can include other specs into one spec file?

Thanks in advance.
