### ISSUE TITLE
Download a HTML test case report?

### ISSUE THREAD

**Issue by karanbajaj2209** [webdriverio/webdriverio#1995]
How can we configure to get an HTML output of the test case report rather than just logs?

**Comment by christian-bromann** [comment]
There is an HTML reporter called (wdio-allure-reporter)[https://github.com/webdriverio/wdio-allure-reporter]. Please see the docs. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
