### ISSUE TITLE
Cannot run with API 'window' of webdriverio

### ISSUE THREAD

**Issue by hant1005** [webdriverio/webdriverio#1996]
## The problem
Script as below (Learning about API browser.window):

  it('Learn window API: ', function () {
    browser.url('https://www.google.com.vn/')
    var googleHandle = browser.windowHandle()
    browser.newWindow('https://github.com/','GitHub','width=420,height=230,resizable,scrollbars=yes,status=1')
    //browser.switchTab(googleHandle);  
    browser.window(googleHandle); //change focus to Google window
    console.log('Try print title of focusing window :', browser.getTitle()) //expected output: "Google"
  })

## Environment

* Java script
* Chrome 57
* WebdriverIO version: 4.6.2
* Node.js version: 7.8.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): selenium Standalone 
* if wdio testrunner, running synchronous or asynchronous tests:

## Error log:
[chrome #0-0] no such window: target window already closed
from unknown error: web view not found
[chrome #0-0] Error: no such window: target window already closed
[chrome #0-0]     at title() - D:\FEDIT\vuejs_sample\Selenium-Sample\node_modules\webdriverio\build\lib\commands\getTitle.js:31:28
[chrome #0-0]     at getTitle() -     at D:\FEDIT\vuejs_sample\Selenium-Sample\node_modules\wdio-sync\build\from unknown error: web view not found
[chrome #0-0]

If run on Firefox (latest version) then show error log is "ERROR: Couldn't connect to selenium server"
Please help me solve this problem.

**Comment by christian-bromann** [comment]
@hant1005 windowHandle is a protocol command and its value is behind the value property, so try:
```js
browser.window(googleHandle.value); //change focus to Google window
```

Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by hant1005** [comment]
Thank  christian-bromann! Testcase is pass.
