### ISSUE TITLE
Using doubleClick command:  show error about 'mouseMoveTo' when run on Firefox

### ISSUE THREAD

**Issue by hant1005** [webdriverio/webdriverio#1997]
## The problem
Script as below (learn about API doubleClick, copy from http://webdriver.io/api/action/doubleClick.html):

  it('should demonstrate the doubleClick command', function () {
    browser.url('file:///C:/xyz/doubleClick.html')
    var myButton = $('#myButton')
    myButton.doubleClick()
    // or
    // browser.doubleClick('#myButton')
    var value = browser.getText('#someText')
    assert(value === 'I was dblclicked') // true
  })

File doubleClick.html contains:
<button id="myButton" ondblclick="document.getElementById('someText').innerHTML='I was dblclicked'">Click me</button>
<div id="someText">I was not clicked</div>

## Environment

* Java script
* FireFox latest
* WebdriverIO version: 4.6.2
* Node.js version: 7.8.0
* Standalone mode or wdio testrunner: selenium Standalone
* if wdio testrunner, running synchronous or asynchronous tests:

## Error log:
[firefox #0-0] 1) Study selenium webdriverio:  should demonstrate the doubleClick command:
[firefox #0-0] mouseMoveTo
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'CPP00006545C', ip: '10.16.63.146', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_101'
Driver info: driver.version: RemoteWebDriver
[firefox #0-0] Error: mouseMoveTo
[firefox #0-0]     Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
[firefox #0-0]     System info: host: 'CPP00006545C', ip: '10.16.63.146', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_101'
[firefox #0-0]     Driver info: driver.version: RemoteWebDriver
[firefox #0-0]     at moveTo("0") - D:\FEDIT\vuejs_sample\Selenium-Sample\node_modules\webdriverio\build\lib\commands\doubleClick.js:33:22

If run on Chrome then the testcase is pass (no error showed)
Please help me solve this problem.

**Comment by christian-bromann** [comment]
The latest Firefox uses Geckodriver which is based on the latest [Webdriver Spec](https://w3c.github.io/webdriver/webdriver-spec.html). This spec doesn't define any double click actions so this is not possible with Firefox.

**Comment by rsshilli** [comment]
I don't understand.  What's the plan for simulating a doubleClick event rather than a single click?  Do we just do 2 single clicks really quickly?

**Comment by christian-bromann** [comment]
> Do we just do 2 single clicks really quickly?

You will need to use the actions command.

**Comment by rsshilli** [comment]
This one?

http://webdriver.io/api/action/doubleClick.html

I'm sad that it doesn't allow me to specify X/Y co-ordinate, which I need to test my map.
