### ISSUE TITLE
Launcher.run() promise isn't resolved nor rejected in certain cases

### ISSUE THREAD

**Issue by FennNaten** [webdriverio/webdriverio#1998]
## The problem

Hi,
I'm currently in the process of integrating several tools in a pre-configured cli for end-to-end testing.
As I'm heavily using node.js, I decided to go with wdio runner, using it programmatically thanks to require('webdriverio').Launcher.
As part of my integration testing, I decided to feed it invalid config (as I support users overriding my defaults, I assume they may do it wrong)
And so, I've been able to see that while the .run() method executes (it produces console output), the promise isn't rejected. (letting my program hanging, as I have other child processes that I orchestrate after test run)
This is surprising behavior, and it's not easy to deal with it.
I'm currently thinking about switching to using wdio bin as a child process instead, but it's not ideal.

## Environment

* WebdriverIO version: 4.4.0
* Node.js version: 6.4.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner, programmatic mode
* OS: windows 8

## Code To Reproduce Issue

I've been able to put up a simplified case that reproduces the issue.
Having webdriverio being the only package, locally installed.

wdio.common.conf.js: this conf will cause an error because the given specs don't match anything

```javascript
console.log("Testing from local workstation");
exports.config = {
    maxInstances: 1,
    capabilities: [{
        maxInstances: 1,
        browserName: 'chrome'
    }],
    waitforTimeout: 60000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    sync: true,
    logLevel: 'verbose',
    coloredLogs: true,
    framework: 'mocha',
    reporters: ['dot'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },
    specs: [
        'useCases/*.js'
    ]
}
```

test.js
```javascript
const path = require('path');
const configFile = path.resolve(__dirname, './wdio.common.conf.js');
const Launcher = require('webdriverio').Launcher;
const wdio = new Launcher(configFile, {});
const handleError = (error) => {
	console.error('Launcher failed while running the test suite', error.stacktrace);
	return;
};
const handleSuccess = (code) => {
	console.log('test suite run is finished')
	return;
}
wdio.run().then(handleSuccess, handleError).catch(handleError);
```

when run through `node test.js`, output is:
```
Testing from local workstation
pattern useCases/*.js did not match any file
```
Then process stops, promise callbacks aren't called, neither for error nor for success.

edition: removed a test case that wasn't related

**Comment by christian-bromann** [comment]
Launcher will exit now with exitcode 0 if no spec was found

**Comment by FennNaten** [comment]
That was fast, thanks :)

**Comment by christian-bromann** [comment]
just published to NPM

**Comment by FennNaten** [comment]
got latest version, it's all good, thank you!
