### ISSUE TITLE
out of date github url in index.js

### ISSUE THREAD

**Issue by drjasonharrison** [webdriverio/webdriverio#2000]
## The problem

I noticed that the [index.js](https://github.com/webdriverio/webdriverio/blob/master/index.js) has a link to https://github.com/**Camme**/webdriverio instead of https://github.com/**webdriverio**/webdriverio

## Environment

Webdriverio master branch

## Details

See above

## Link to Selenium/WebdriverIO logs

N/A

## Code To Reproduce Issue [ Good To Have ]

N/A

**Comment by drjasonharrison** [comment]
https://github.com/drjasonharrison/webdriverio/pull/1

**Comment by christian-bromann** [comment]
@drjasonharrison please create a PR not an issue
