### ISSUE TITLE
Async custom commands do not execute async in describe block

### ISSUE THREAD

**Issue by patthiel** [webdriverio/webdriverio#2005]
## The problem

In a spec, you may have a command that makes a call out to a database, etc. that you would like to access in multiple tests. I should be able to add the command in the test or somewhere that i define the custom commands, and call the command and store it in a variable in the describe block so that it is accessible to each test block (beforeAll/beforeEach/it/afterEach/afterAll).

```javascript
describe('my test script', () => {
    browser.addCommand('getTestData', function async (params) {
        return externalLib.command(params);
    });

    const testData = browser.getTestData();
    console.log(testData);

    it('use test data', () => {
        browser.url(testData.productPage[1]);
    });
});
```

The above console.log returns promise pending. When i move the browser.getTestData call into a test block (beforeAll/beforeEach/it) it works as expected.

## Environment

* WebdriverIO version: 4.6.0
* Node.js version: 6.9.5
* [Standalone mode]
* sync
* Additional wdio packages used (if applicable):
* wdio-jasmine-framework - latest
* gulp-webdriver

**Comment by christian-bromann** [comment]
@patthiel you can't run a WebdriverIO (custom) command outside of an hook or it block. We only wrap these within fibers. Do this instead:

```js
describe('my test script', () => {
    browser.addCommand('getTestData', function async (params) {
        return externalLib.command(params);
    });

    let testData;
    console.log(testData);

    before(() => {
        testData = browser.getTestData();
        console.log(testData);
    });

    it('use test data', () => {
        browser.url(testData.productPage[1]);
    });
});
```

**Comment by patthiel** [comment]
👍  in testing i figured out this was the case. I added a short line of documentation calling out this behavior in #2010
