### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by akmanon** [webdriverio/webdriverio#2007]
Refresh page until particular element appears...
What is the syntax for it...

**Comment by monolithed** [comment]
```js
browser.waitUntil(() => {
   return browser.isExisting(selector);
});
```

Use https://gitter.im/webdriverio/webdriverio for such questions

**Comment by christian-bromann** [comment]
Thanks @monolithed

**Comment by akmanon** [comment]
Thanks @monolithed
