### ISSUE TITLE
fix inconsistent isVisible behavior

### ISSUE THREAD

**Issue by dheerajbhaskar** [webdriverio/webdriverio#2008]
## The problem

- `isVisible` seems like a boolean returning method but is not. You can't do `if(isVisible('<selector>')`. 
- It returns an array if multiple elements are found, which to be fair is documented. But it's like Array.length returning it's return values in roman numerals if length is greater than 10. It's behavior is not consistent.
- The array returned is also not consistent. It has `false` values, sometimes, meaning I can't just check for length to be equal to 0 or just for it to return false. If no elements are visible, sometimes, it returns values like [false, false]. Which is bad because, it's length is not zero (you're expecting visible elements), and it's not a falsey value so that's not easy to use either.

Briefly describe the issue you are experiencing (or the feature you want to see added to WebdriverIO). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, join the Gitter chat room ([![Gitter](https://badges.gitter.im/Join Chat.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge))!

## Environment

* WebdriverIO version: v4.6.2
* Node.js version: v6.10.2
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): 
    "wdio-mocha-framework": "^0.5.9",
    "wdio-spec-reporter": "^0.1.0",

## Details

Describe in more detail the problem you have been experiencing, if necessary.

I'd like to use if(isVisible()) like syntax because that's what it implies by the name, that it returns a boolean. I'd like to submit a PR to fix isVisible (which might be a breaking change), short of which, I'd like a new function which does this behavior.

## Link to Selenium/WebdriverIO logs

not relevant I think, I think

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]

run isVisible in a loop, waiting for elements to disappear

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by dheerajbhaskar** [comment]
This is the code I want to submit (or some form of it), how would I go about it, please guide me.

```
export function isVisibleFixed(selector: string) {
    const isVisibleRegular = browser.isVisible(selector);
    if (_.isArray(isVisibleRegular)) {
        // isVisibleRegular is equal to `[]` which is an INVALID state; should be `false`
        if (isVisibleRegular.length === 0) {
            console.log('Error:\"isVisibleRegular\" is an Array and is empty; Should be false but is []; INVALID state');
            browser.debug();
        }

        //// isVisibleRegular is an Array and contains a false value; Should NOT contain false values
        //// It DOES contain false values often
        // if (_.some(isVisibleRegular, hasFalseValue)) {
        //     console.log('Error:\"isVisibleRegular\" is an Array and contains a false value; Should NOT contain false values; INVALID state');
        //     browser.debug();
        // }

        // returns true if there no `true` values in the array
        //TODO use _.includes() instead?
        return _.some(isVisibleRegular, _.identity);
    }

    // convert to boolean and return
    return !!isVisibleRegular;
}
```

**Comment by monolithed** [comment]
This is by design 😞

I think we need something like: getText/getTexts, getValue/getValues, getAttribute/getAttributes, isVisible/areVisible, isEnabled/areEnabled, isExisting/areExisting, isSelected/areSelected, getTagName/getTagNames, getCssProperty/getCssProperties

**Comment by dheerajbhaskar** [comment]
@monolithed well that is one way to go about it ie splitting it into different methods. 

We can learn a few things from jquery and use their paradigm of not having such split methods but by returning arrays (or whatever else their paradigm is, I've not analyzed jquery deeply) 

But for methods like isVisible, the return values need to be boolean, supporting non boolean return values is some twisted argument. If it's by design, then that's bad design and needs to be fixed. It's like mutating a property in a getXYZ() function, it's unconventional and bad design.

**Comment by dheerajbhaskar** [comment]
Another simple alternative is to accept an optional argument like isVerbose to return full array results else default to booleans for boolean-looking-functions

**Comment by KOPTE3** [comment]
I can implement this and send the PR to the repository. @christian-bromann, do you accept it? I ask, to understand, whether it is necessary

**Comment by christian-bromann** [comment]
> @christian-bromann, do you accept it?

Accept what? Please define a clear proposal here first so we can discuss about it.

> fix inconsistent isVisible behavior

I wouldn't necessary say it is inconsistent because it is like that for all getXXX commands in the API. It is also documented how this behaves.

> If it's by design, then that's bad design and needs to be fixed.

This is your opinion. The behavior works in most of the use cases and was never a big issue for other developers. In general you should define an element so that you always get the expected result. If you query an element and for some reason it matches two elements than something is wrong with your expectation. I rather let the test fail instead of returning a value that is aggregated based on the results. Because then you get false positives which is more undesired then the other case.

> isVisible seems like a boolean returning method but is not.

The whole API consist of functions so you should not expect this to be a boolean.

> It returns an array if multiple elements are found, which to be fair is documented. But it's like Array.length returning it's return values in roman numerals if length is greater than 10. It's behavior is not consistent.

I am not sure what you mean by that.

> If no elements are visible, sometimes, it returns values like [false, false]. Which is bad because, it's length is not zero (you're expecting visible elements), and it's not a falsey value so that's not easy to use either.

This is consistent across all getXXX commands. When your selector matches multiple elements you will get back an array of results. The reason why a single result is not returned as array too (which I think is the design flaw you are pointing out here) is that it would be harder to assert that value. Therefor as I mentioned above: you usually have two use cases: inspect a single or multiple elements. Imo if you expect the one scenario but get the other you should get an error because your assertion will fail.

> I think we need something like: getText/getTexts, getValue/getValues, getAttribute/getAttributes, isVisible/areVisible, isEnabled/areEnabled, isExisting/areExisting, isSelected/areSelected, getTagName/getTagNames, getCssProperty/getCssProperties

More commands won't make this easier. I mentioned that many times: this API is big enough that we should be careful to add any new commands.

**Comment by KOPTE3** [comment]
I was referring to the PR with the implementation of the methods mentioned in [this](https://github.com/webdriverio/webdriverio/issues/1539#issuecomment-289527630) comment:
- `getText(s)`
- `getValue(s)`
- `getAttribute(s)`
- `getTagName(s)`
- `getCssProperty(ies)`

I want to do this because [this expedient](https://github.com/webdriverio/webdriverio/issues/1539#issuecomment-289524914) looks like a hack and very often occurs (in our tests)

It seems that this issue is not entirely suitable for discussing this problem... I can describe my proposal in details [here](https://github.com/webdriverio/webdriverio/issues/1539#issuecomment-289527630)

**Comment by christian-bromann** [comment]
> mentioned in this comment:

This is a completely different discussion.

> I want to do this because this expedient looks like a hack and very often occurs (in our tests)

Feel free to use addCommand to add these commands to your test suite. I don't think adding these to the core API makes sense.

**Comment by monolithed** [comment]
> The whole API consist of functions so you should not expect this to be a boolean.

It's expected when all the tests are written by one person. Nobody likes to read the documentation. 😞

**Comment by christian-bromann** [comment]
> Nobody likes to read the documentation.

I am happy to have a serious conversation about this API design but this is just a stupid argument. Sorry.

**Comment by monolithed** [comment]
**Expected array**

```js
let selector = <selector>;
let isVisible = browser.isVisible(selector);

if (Array.isArray(isVisible)) {
    let actual = isVisible.filter(value => value !== true);
    assert.equal(actual, 0, `Some elements "${actual}" for "${selector}" are still not visible`);
}
else {
    assert(0, `Something went wrong. Expected array for "${selector}" but received "${isVisible}"`) ;
}
```

**Expected boolean**

```js
let selector = <selector>;
let isVisible = browser.isVisible(selector);

if (Array.isArray(isVisible)) {
    assert(0, `Something went wrong. Expected boolean for "${selector}" but received "${isVisible}"`) ;
}
else {
    assert(isVisible, `"${selector}" is still not visible) ;
}
```

How many different combinations are possible for team with 20+ developers, 6 projects and 1000+ tests? I have no any chance to explain for each of them how to use the framework and review theirs code. My worries are based on a true story.

**Comment by christian-bromann** [comment]
> 20+ developers

They all should be able to look into the docs. This is the same as for any other framework.

> 7 projects and 1500+ tests

That's awesome 👏 

WebdriverIO is flexible enough to get extended in a way that you can work comfortably with. The design decision that has to be made here affects way more developers, projects and tests. Let's have this convo in #2009. Cool for you too @dheerajbhaskar?

**Comment by dheerajbhaskar** [comment]
@christian-bromann

#2009 is one possible solution to the problem. I just want to hear from you if you find that this is a problem or not worth solving at the api level and  should be a feature in our test suite level. 

Specific issues I have are:
*1) Changing of return type*
The issue is this: the function isVisible abruptly changes its behavior from returning booleans (selector matches <=1 elem)  to returning arrays (selector matches >1 elem). Changing the return type abruptly is in my humble opinion not a good paradigm, gives false positives/negatives in tests. As an example, I mentioned earlier imagine if array.length changed its return value from regular numbers to Roman numerals (X, XI, etc) after length=10 (arbitrary point) 

*2) return type not being boolean for a boolean looking function.* This is misleading to a developer. Just go read the docs is a bad answer. I understand if you day we don't want to break the api now because a lot of other libs depend on us. 

*3) inconsistent behavior even when returning the array result.*
The array contains true if an element is visible and nothing (that value is removed) if it is not visible anymore. This logic is not followed consistently. There are false values in the array sometimes. 

For example if you wanted to wait for a bunch of buttons to disappear on a site, some code for it would be:

```
waitUntil(()=>{
return !isVisible (someSelector) 
}) 
```
This doesn't work because sometimes when all buttons disappear you'll still get [false, false] which is truthy rather than false (boolean) which is falsey

**Comment by mattc41190** [comment]
@dheerajbhaskar I see where you are coming from. I know that your point is that isVisible returns something confusing, but in the interest of getting something useful in your hands have you considered using `browser.addCommand` and `browser.elementIdDisplayed` together?

An example of checking the boolean displayed (`isVisible`) value of a collection of elements could look like:

```javascript
    it('tells you which elements are displayed and which are not', function () {
        let divs = browser.elements('div').value // Get array of all div ids
        for (let div in divs) {
            console.log(browser.elementIdDisplayed(divs[div].ELEMENT).value);
            // Check the BOOLEAN displayed value of each
        }
    });
```

A pro to using the above approach is that it accomplishes your desire to have the displayed property always return the same (boolean) regardless of whether one or many elements match the selector!

A con is that it is gross to look at!

**Comment by dheerajbhaskar** [comment]
@mattc41190 thanks for taking the time to reply.

What we've done is created a function called isVisibleFixed and use that. This is very similar in concept to your suggestion of using addCommand. 

I've figured this out, I've no further qualms. I thought it would benefit other developers if isVisible returned a boolean always, but that's a suggestion and the maintainer can take the final call as I suppose he already has 🙂
