### ISSUE TITLE
hasFocus can't be chained

### ISSUE THREAD

**Issue by webOS101** [webdriverio/webdriverio#2018]
## The problem

Certain commands do not work when chained from an element request.  (e.g. `hasFocus()`). When invoked as a chained command, they throw the exception 'Cannot read property 'selector' of undefined'. This limits the usefulness of chaining and, in particular, the Pageobject approach.

## Environment

* WebdriverIO version: 4.7.1
* Node.js version: 6.8.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio test runner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): ['sauce', 'selenium-standalone', 'static-server']
* Using Mocha test

## Details

The issue appears to be related to the handling of missing parameters.  This line here is the one that throws the exception:  https://github.com/webdriverio/webdriverio/blob/master/lib/commands/hasFocus.js#L30

The `value` of the last promise is `undefined` (and there's no check against that).  Switching to use `this.lastResult.selector` seems to work OK, though I don't know enough about the code base to suggest this change globally.

## Link to Selenium/WebdriverIO logs

https://gist.github.com/webOS101/5058e80082b13e2d071d0e6446cd05c3

## Code To Reproduce Issue [ Good To Have ]

```
		browser.url('http://webdriver.io/');
		$('#docsearch').hasFocus();
```

**Comment by christian-bromann** [comment]
@webOS101 you example should work, can you provide a minimal reproducible example?

**Comment by christian-bromann** [comment]
Using the repl it shows how it works:
```sh
$ wdio repl phantomjs

[09:31:26]  DEBUG       Queue has stopped!
[09:31:26]  DEBUG       You can now go into the browser or use the command line as REPL
[09:31:26]  DEBUG       (To exit, press ^C again or type .exit)

> $('body').hasFocus()
false
```

**Comment by webOS101** [comment]
The problem does not reproduce in the REPL.  It appears to be tied to the wdio sync runner.  I disabled all of my wdio packages (added above, just in case).  I'm using mocha tests (also will add that above).  Here's the whole test body:

```
describe('crash', function () {

	it('should not crash', function () {
		browser.url('http://webdriver.io/');
		$('#docsearch').hasFocus();
	});
});
```
