### ISSUE TITLE
custom command clobbers previous output

### ISSUE THREAD

**Issue by jrobinson01** [webdriverio/webdriverio#2021]
## The problem
When using a custom command and assigning it's return value to a variable, when you use that same command a second time, the previously assigned variable is overwritten with the result of the second run.
## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 6.4.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable): 
"wdio-jasmine-framework": "^0.2.19",
"wdio-junit-reporter": "^0.2.0",
"wdio-sauce-service": "^0.3.1",
"wdio-spec-reporter": "^0.0.5",
"webdriverio": "^4.6.2"

## Details

See the example code below. The last test fails, but is essentially identical to the one before it. The example command is deliberately very simple. It's functionality could be achieved without a custom command. This is a simplified representation of the real command I'm using, which is designed to dig out elements from nested shadow dom.

## Code To Reproduce Issue
dummy-test.html
```html
<!doctype html>
<html>
<head>
  <title>Dummy Test Page</title>
</head>
<body>
  <div>div 1</div>
  <div>div 2</div>
</body>
</html>
```
test-command.js
```js
browser.addCommand("testCommand", function(selector) {
  return this.execute(function(selectors) {
    return document.querySelector(selectors);
  }, selector);
});
```
dummy-test-spec.js
```js
'use strict';
const hostname = require('./shared/hostname');

describe('Dummy test', () => {
  browser.windowHandleMaximize();
  browser.url(`https://${hostname}:8443/test/components/dummy-test.html`);

  // pass
  it('should work', () => {
    const el1 = browser.element('div:nth-of-type(1)');
    expect(el1.getText()).toBe('div 1');
    const el2 = browser.element('div:nth-of-type(2)');
    expect(el2.getText()).toBe('div 2');
  });

  // pass
  it('should work regardless of order.', () => {
    const el1 = browser.element('div:nth-of-type(1)');
    const el2 = browser.element('div:nth-of-type(2)');
    expect(el1.getText()).toBe('div 1');
    expect(el2.getText()).toBe('div 2');
  });

  // pass
  it('should work with execute regardless of order.', () => {
    const el1 = browser.execute(function() {// eslint-disable-line prefer-arrow-callback
      return document.querySelector('div:nth-of-type(1)');
    });
    const el2 = browser.execute(function() {// eslint-disable-line prefer-arrow-callback
      return document.querySelector('div:nth-of-type(2)');
    });
    expect(el1.getText()).toBe('div 1');
    expect(el2.getText()).toBe('div 2');
  });

  // pass
  it('should work with testCommand.', () => {
    const el1 = browser.testCommand('div:nth-of-type(1)');
    expect(el1.getText()).toBe('div 1');
    const el2 = browser.testCommand('div:nth-of-type(2)');
    expect(el2.getText()).toBe('div 2');
  });

  // fail
  it('should work with testCommand regardless of order.', () => {
    const el1 = browser.testCommand('div:nth-of-type(1)');
    const el2 = browser.testCommand('div:nth-of-type(2)');
    expect(el1.getText()).toBe('div 1');// "expected 'div 2' to be 'div 1'
    expect(el2.getText()).toBe('div 2');
  });
});
```

**Comment by jrobinson01** [comment]
I'm not very familiar with the web driver code but I'll take a stab at fixing this if someone can point me in the right direction. @christian-bromann ?

**Comment by shinxi** [comment]
I'm also facing the similar issue when using `querySelector` in custom command.

```js
// fail
  it('$ should work after using testCommand.', () => {
    const el1 = browser.testCommand('div:nth-of-type(1)');
    const el2 = $('div:nth-of-type(2)');
    expect(el2.getText()).toBe('div 2');// It'll report `An element could not be located on the page using the given search parameters.`
  });
```
Looks element is getting chained of result from custom command.
```
 /session/:sessionId/element/0.5929498288185353-21/element
```

**Comment by christian-bromann** [comment]
This is fixed in v5. I am working hard to get this version released asap. If you are interested in a fix feel free to propose a PR to the v4 branch. Thanks!
