### ISSUE TITLE
Contribution documentation outdated

### ISSUE THREAD

**Issue by timbru31** [webdriverio/webdriverio#2022]
The [contribution doc](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and the [website ](http://webdriver.io/contribute.html) are outdated by 

- Suggesting to download Selenium 2
- Stating that the WebdriverIO tests can be executed via grunt

---
Disclaimer: Yes I know that the grunt tasks were very recently removed, this issue is more like a "don't forget to update the docs, soon" reminder 😉

**Comment by christian-bromann** [comment]
Fixed by #2028 .. thanks @jankcat

**Comment by timbru31** [comment]
Website will be updated when you deploy the next time?

**Comment by christian-bromann** [comment]
yup, when v4.8 is published to NPM
