### ISSUE TITLE
Cannot set Chrome extension using localStorage

### ISSUE THREAD

**Issue by MartinGentleman** [webdriverio/webdriverio#2023]
## The problem

I am loading chrome extension modHeader successfully as base64 in node.js. I am not using wdio.

to setMod header I found online that you need to execute this:

```js
await client.execute(() =>
  localStorage.setItem('profiles', JSON.stringify([{
    title: 'Selenium', hideComment: true, appendMode: '',
    headers: [
      {enabled: true, name: 'MyHeader', value: 'true', comment: ''}
    ],
    respHeaders: [],
    filters: []
  }])));
```

but the extension does not seem to pick that up. No error is thrown.

I also tried using localStorage directly from Webdriver.io

```js
await client.localStorage('POST', {key: 'profiles', value: JSON.stringify([{
    title: 'Selenium', hideComment: true, appendMode: '',
    headers: [
      {enabled: true, name: 'MyHeader', value: 'true', comment: ''}
    ],
    respHeaders: [],
    filters: []
  }])});
```

Is there a different method in Webdriver.io that I should be using?

**Comment by christian-bromann** [comment]
> Is there a different method in Webdriver.io that I should be using?

@MartinGentleman no. These are correct. However it seems that chromedriver can't set local storage for some reasons. I don't think this is a bug in WebdriverIO but more one in the Chromedriver project.
