### ISSUE TITLE
how to fire a checkbox onchange event ?

### ISSUE THREAD

**Issue by RubyLouvre** [webdriverio/webdriverio#2025]
I have two radio, they add the onchange event, click on one of these, onchange event is not triggered
```
radioElement.onchange = function(){
    console.log('xxxxx')
}
```

```
 browser.click('#radio2')
 browser.waitForSelected('#radio2')

```

**Comment by christian-bromann** [comment]
@RubyLouvre depending on which browser you use this could be problematic as some driver don't propagate the events as expected. WebdriverIO can't do anything about it. Try to fire the event manually via injecting a JS script via `execute` command.
