### ISSUE TITLE
Get link attributes 

### ISSUE THREAD

**Issue by alippai** [webdriverio/webdriverio#203]
How can read the attributes (eg. 'rel') of all links ('a') on a page?
I can call client.elements('tag name', 'a', fn) but how do I get the attributes text value from res.value[0].ELEMENT ?

console.log(client.elementIdAttribute(res.value[0].ELEMENT, 'href')) doesn't work for me.

**Comment by Moin-A** [comment]
How do obtain the link text for a link,is there any code for that
