### ISSUE TITLE
Can't select a radio button through webdriver.io

### ISSUE THREAD

**Issue by zhaoyi0113** [webdriverio/webdriverio#2030]
I have below html fragment and want to select that radio input through webdriver api but failed. 
```
<label class="pt-control pt-radio">
      <input type="radio" class="radio" id="hostRadio--2" name="hostRadio" value="false" label="" placeholder="">
         <span class="pt-control-indicator"></span>
</label>
```

The code I used is shown as below:

```
try {
        await this.browser.setValue('#hostRadio--2', 'true');
      } catch (err) {
        console.error('err:', err.message);
      }
```

after run above code I got below errors. This an input element with radio type and it is editable. Why can't I select it through `setValue` method?

```
invalid element state: Element must be user-editable in order to clear it.
```

**Comment by christian-bromann** [comment]
@zhaoyi0113 just click on the radio input to enable it. Also please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by zhaoyi0113** [comment]
I have tried to use click but got below error:
```
unknown error: Element <input type="radio" class="hostRadio-radio-input hostRadio-radio" id="hostRadio--2" name="hostRadio" value="false" label="" placeholder=""> is not clickable at point (40, 155). Other element would receive the click: <span class="pt-control-indicator"></span>
```

**Comment by christian-bromann** [comment]
Well the error says it all right? An other element is lying above your radio button. So either click on that element and some JS magic activates the radio or find out what this element is.
