### ISSUE TITLE
More of a question

### ISSUE THREAD

**Issue by JEHAL81** [webdriverio/webdriverio#2033]
Hi,

I was wondering how do you show undefined steps to Implement snippets?

I can't get it to work like cucumber.js. 

![untitled](https://cloud.githubusercontent.com/assets/25979411/25557129/c6fc527c-2d02-11e7-83c9-afe1d0b5e91a.png)

**Comment by christian-bromann** [comment]
See https://github.com/webdriverio/wdio-cucumber-framework#ignoreundefineddefinitions . Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
