### ISSUE TITLE
Unit test failing in master "should not take screenshot if rejection handler is provided"

### ISSUE THREAD

**Issue by deployable** [webdriverio/webdriverio#2037]
## The problem

Unit test failing in master "should not take screenshot if rejection handler is provided"
```
## Environment

* WebdriverIO version: 4.7.1
* Node.js version: 7.9.0
* Standalone mode

## Details

```
  176 passing (9s)
  1 pending
  1 failing

  1) rejection should not take screenshot if rejection handler is provided:
     AssertionError: expected 'number or type of arguments don\'t agree with elementIdClick protocol command' to match /An element could not be located/
      at test/spec/unit/reject.js:26:38
      at Object.reject (lib/webdriverio.js:175:20)
      at Object.callErrorHandlerAndReject (lib/webdriverio.js:151:27)
      at lib/webdriverio.js:129:54
      at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

## Link to Selenium/WebdriverIO logs

n/a

## Code To Reproduce Issue [ Good To Have ]

    git clone https://github.com/webdriverio/webdriverio && npm run build && npm test

**Comment by christian-bromann** [comment]
@deployable I've recently changed some commands to be complaint to the latest Webdriver spec which caused the unit tests to fail I should have pushed it to a branch. Will fix it asap.
