### ISSUE TITLE
Watch mode only detects changes to single file

### ISSUE THREAD

**Issue by rootd00d** [webdriverio/webdriverio#2038]
## The problem

When running under watch mode, wdio seems to only respond to changes detected in a single file.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 4.4.7
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): wdio-junit-reporter, wdio-jasmine-framework

## Details

I have two specs in the same directory, and only one of them will be actually be watched.  Changing and saving this file will cause wdio to run the spec as I might have expected, but altering any other file has no effect.

I'm currently using the following definition for specs in wdio.conf.js:

``
        specs: [
            './test/specs/**/*.js',
        ],
``

which, seems to at least work for the single file, but not all of them.  I tried specifying files individually, but that had the effect of no response to any file changed.

## Link to Selenium/WebdriverIO logs

There are no logs to show, since the issue is that there are no changes detected.  It just sits at 

`WDIO is now in watch mode and is waiting for a change...`

## Code To Reproduce Issue [ Good To Have ]

wdio.conf.js
```
exports.config = {
    host: 'localhost',
    port: 4444,
    path: '/wd/hub',
    specs: [
        "./test/specs/**/*.js"
    ],
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    maxInstances: 10,
    capabilities: [{
        maxInstances: 1,
        browserName: 'chrome', // firefox does not support sendKeysToActiveElement API
        acceptInsecureCerts: true, // marionette driver
        acceptSslCerts: true // classic driver
    }],
    sync: true,
    logLevel: 'verbose',
    coloredLogs: true,
    bail: 0,
    waitforTimeout: 10000,
    connectionRetryTimeout: 60000,
    connectionRetryCount: 3,
    reporters: ['dot', 'junit'],
    reporterOptions: {
        junit: {
            outputDir: './target/test-results'
        }
    },
    jasmineNodeOpts: {
        defaultTimeoutInterval: 60000,
        expectationResultHandler: function(passed, assertion) {
            // do something
        }
    },
    afterTest: function (test) {
      if (!test.passed) {
        var mkdirp = require('mkdirp');
        mkdirp.sync('./target/screenshots');

        var screenshot = browser.saveScreenshot();
        var fs = require('fs');
        fs.writeFileSync('./target/screenshots/'+browser.desiredCapabilities.browserName+'-'+test.fullName+'.png', screenshot);
      }
    }
}

```

**Comment by rootd00d** [comment]
This issue was reported when there were only 2 files in the specs folder.  I've seen now that adding additional files will make it so that it's _possible_ that more than one file will have a change detected (though not always) but at least one of the files will never trigger wdio to relaunch.

**Comment by seriallos** [comment]
I'm seeing the same behavior with my test suites.

It looks like it only watches a single file per directory (and it seems like it's the first one lexicographically). Nested directories end up with one file actually working for change detection.

**Comment by seriallos** [comment]
Doing a bit more digging, it looks like `--watch` ends up watching as many files as `maxInstances`. Each process ends up with a single file that it's watching.

Dropping some console.logs into the code shows that each process only gets a single file resolved from the spec globbing. I played around with trying to get wdio to run in non-multiremote mode but that didn't seem to resolve anything (and it's unclear if non-multiremote is even intended at this point - most of the code around determining `isMultiRemote` relies on `capabilities` being an array - changing it to an object doesn't seem to be properly supported)

**Comment by mokkabonna** [comment]
Having this issue as well. Playing around with maxInstances seems to sometimes make it work again. But not clear why.

**Comment by thihy** [comment]
+1
