### ISSUE TITLE
Unable to set Cookie with phantomjs

### ISSUE THREAD

**Issue by xiejunfeng** [webdriverio/webdriverio#2040]
## The problem

http://stackoverflow.com/questions/43676062/webdriverio-a-request-to-set-a-cookies-value-could-not-be-satisfied

while I change the phantomjs to chrome, it works. Is there some special settings that i have missed？

**Comment by christian-bromann** [comment]
Please share your phantomjs logs, otherwise we can't tell what is going on

**Comment by christian-bromann** [comment]
Looked around [the internet](https://github.com/Codeception/Codeception/issues/2900) and this seems to be a PhantomJS issue. Closing.
