### ISSUE TITLE
MouseMoveTo error when use geckodriver.

### ISSUE THREAD

**Issue by Mignon-han** [webdriverio/webdriverio#2042]
## The problem

MouseMoveTo error when use geckodriver.
It's ok for chrome driver.

## Environment

* WebdriverIO version:4.8
* Node.js version: 6.3.1

**Comment by Mignon-han** [comment]
#2041 Aother problem for geckodriver.

**Comment by christian-bromann** [comment]
`moveTo` is deprecated. There will be proper actions commands with the release of the next version. Please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
