### ISSUE TITLE
Error: Couldn't connect to selenium server

### ISSUE THREAD

**Issue by kevinmcdonnell** [webdriverio/webdriverio#2044]
## The problem

Wdio fails occasionally with one of the following errors

```
Error: Couldn't connect to selenium server
```
or
```
ERROR: session not created exception
from no such window: window was already closed
```
## Environment

* WebdriverIO version: v4.4.0
* Node.js version: v4.8.2
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable):

## Details

There was a short thread on this in gitter https://gitter.im/webdriverio/webdriverio?at=587d5047cbcb2817707a824a

> Christian Bromann @christian-bromann Jan 17 10:25
> this is webdriverio having issues creating a session

## Link to Selenium/WebdriverIO logs

Logs dont contain a reference to the above errors

## Code To Reproduce Issue [ Good To Have ]

This happens intermittently. In our case it mostly happens on a jenkins server which is running multiple wdio jobs concurrently, each of which is using 3 browsers instances to execute the tests

**Comment by christian-bromann** [comment]
Just because I said it is WebdriverIO having issue to create a session it doesn't mean that it is WebdriverIOs fault 😉  .. it looks like a chromedriver thing: https://bugs.chromium.org/p/chromedriver/issues/detail?id=346. There is just no way WebdriverIO can fix this.

**Comment by kevinmcdonnell** [comment]
@christian-bromann what about the `Error: Couldn't connect to selenium server`?

**Comment by christian-bromann** [comment]
this is an error message printed by WebdriverIO
