### ISSUE TITLE
Typo: "depcrecated" should be "deprecated"

### ISSUE THREAD

**Issue by petegibbins** [webdriverio/webdriverio#2045]
## The problem

As per the title, there's a typo replicated throughout the project which appears on warning messages. 
The word "depcrecated" should be "deprecated".

## Environment

* WebdriverIO version: Latest

**Comment by antkazam** [comment]
@christian-bromann Can you reopen this? The change in [68e3e0c](https://github.com/webdriverio/webdriverio/commit/68e3e0c537ec93fb50a5a3030ef48e8c1871a023) breaks module imports elsewhere

**Comment by christian-bromann** [comment]
@antkazam thanks for catching and fixing this
