### ISSUE TITLE
Element chaining in REPL not working with commands that take additional arguments

### ISSUE THREAD

**Issue by webOS101** [webdriverio/webdriverio#2046]
## The problem

Element chaining does not always work.  Commands that take additional arguments throw an error.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 6.8.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): REPL
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Details

Examples:
```
browser.elements('div').getAttribute('id')
Error
    at evalmachine.<anonymous>:1:25
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.exports.runInThisContext (vm.js:77:17)
    at /Users/RoySutton/Documents/Development/webdriverio/build/lib/commands/debug.js:54:43
```
```
 browser.element('#fb-root').getCssProperty('color')
Error
```

These same commands pass in a test:

```
	it('test', () => {
		browser.url('http://webdriver.io');
		console.log(browser.element('#fb-root').getAttribute('id'));
		console.log(browser.element('#fb-root').getCssProperty('color'));
	});
```
```
․fb-root
{ property: 'color',
  value: 'rgba(0,0,0,1)',
  parsed: { hex: '#000000', alpha: 1, type: 'color', rgba: 'rgba(0,0,0,1)' } }
```

In trying to diagnose it, it seems the `browser` object is passed to the command rather than the result of the last command.  This causes `hasElementResult()` to return `false`, not allowing the chaining to occur in `client.next` 

## Link to Selenium/WebdriverIO logs

N/A?

## Code To Reproduce Issue [ Good To Have ]

See above.

**Comment by stuartcrobinson** [comment]
+1 for fixing this

**Comment by christian-bromann** [comment]
we will in v5, feel free to help out 😉

**Comment by christian-bromann** [comment]
Hey,

we update the core architecture of WebdriverIO and with that a lot of implementation details that might make this issue obsolete. Please try with the v5 version of WebdriverIO and verify if this still occurs. If so please open a new issue and we will tackle it asap.

Thanks!
