### ISSUE TITLE
WARNING: the "moveTo" command will be depcrecated soon.

### ISSUE THREAD

**Issue by anahit42** [webdriverio/webdriverio#2047]
## The problem
I'm using browser.moveToObject(selector,xoffset,yoffset) in my project.  

It started to give the following  log each time I use it in my code.  

> WARNING: the "moveTo" command will be depcrecated soon. Please use a different command in order to avoid failures in your test after updating WebdriverIO.

So the issue is that I use moveToObject, which uses moveTo inside it and there is no alternative to replace it.  How to solve this issue? Are there other ways to execute mouse move? 

## Environment

* WebdriverIO version:  ^4.6.2
* Node.js version: v7.8.0
* Standalone mode

**Comment by christian-bromann** [comment]
> How to solve this issue? Are there other ways to execute mouse move?

This has to be replaced by action commands when they are implemented and supported. Please continue to use this command until then. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by domi41** [comment]
See #1653
