### ISSUE TITLE
Question: Is there any option to run test scenarios in parallel to reduce test run time .

### ISSUE THREAD

**Issue by sajesh2686** [webdriverio/webdriverio#205]
Hi 

As mentioned in sauce labs (http://saucelabs.com/selenium/selenium-webdriver), is there any option to run test in parallel to reduce execution time.

 Is it feasible to have this feature into webdriverjs which can be defined in config file. 

What is your thought on this.

**Comment by daudt** [comment]
I think this issue should be reopened. Specifying which spec to work on which capability doesn't seem to work at the moment, as multiple concurrent browsers will run all tests in all browsers in parallel.
Parallel execution would save a significant amount of time when you have a large number of tests.

**Comment by jamesdwilson** [comment]
+1

**Comment by dcypherthis** [comment]
+1 to reopen

**Comment by christian-bromann** [comment]
WebdriverIO supports parallel execution! In v3 each capability defined in the wdio.conf.js runs in a single child process, so if you have 3 capabilities defined your tests will run 3 times faster. In v4 we even improved this by executing each spec in a separated child process. So if you have 3 capabilities and 10 specs defined, there will be 30 child processes that will run in parallel if you don't set any restrictions to this.

**Comment by dcypherthis** [comment]
Thanks Christian!  I haven't installed v4 yet, but that's exactly what I'm looking for!

**Comment by gregeinfrank** [comment]
@christian-bromann in v4, is there a way to turn off parallel execution or limit to a small number of child processes? Running too many in parallel seems to be overloading my local api and/or selenium process.

**Comment by jopdeklein** [comment]
@gregeinfrank try the `maxInstances` option.

**Comment by nullin** [comment]
sorry for resurrecting an old thread, but any thoughts on how to support running data driven tests in parallel? 

My use case entails writing tens to hundreds of data driven tests which are essentially the same it() block executed over and over with different configuration read from yaml files... From all that I have read, using webdriverio test runner, I'll only be able to run these tests sequentially.

Has anyone faced this problem and found a solution or workaround? This is one of the main sticking points that'll keep me from using webdriverio.

**Comment by darklord549** [comment]
@christian-bromann Need to run same piece of code in js file on two emulators with different capabilities

**Comment by Passsword** [comment]
@darklord549 

> Need to run same piece of code in js file on two emulators with different capabilities

You can try Multiremote functionality, as described on the webdriver.io

**Comment by goodbomb** [comment]
@nullin Did you ever find a solution to your problem? We're facing the same thing on our end.

**Comment by christian-bromann** [comment]
> i am using WdioV4

You should upgrade to the latest WebdriverIO version to ensure tests continue to work. v4 is deprecated a long time now.
