### ISSUE TITLE
I can not get the text associated to a <P>

### ISSUE THREAD

**Issue by nvega-ms** [webdriverio/webdriverio#2050]
## The problem
I'm trying to get the text related to the following element:
<div class="error__box"><p>Invalid credentials.</p></div>

In my test I have the following sentence:
browser.getText('.error__box p=Invalid credentials.')

I obtained the following error:
Error: Argument was an invalid selector (e.g. XPath/CSS).

Could you please help me with that? Thanks

**Comment by christian-bromann** [comment]
just do `browser.getText('p=Invalid credentials.')`

Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by nvega-ms** [comment]
Oh, I'm sorry! Thanks, but browser.getText('p=Invalid credentials.') is not working :(
