### ISSUE TITLE
moveToObject: extraneous behaviour for chrome and firefox

### ISSUE THREAD

**Issue by jesusMT** [webdriverio/webdriverio#2053]
## The problem
moveToObject is not working correctly in chrome and firefox

## Environment

* WebdriverIO version: 4.4.0
* Node.js version:6.9.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):

## Details

I'm trying to click in an element that is not in the scrollview. For that I have to put this element in the view with the moveToObject action, but is not possible. 
**-For chrome** I'm getting the next error `Other element would receive the click:`. This is correct, because there are one element in front of it. I think that the `xoffset` & `yoffset` parameters are not responding good. I'm setting `yoffset` getting the location of the element and adding 100 pixels for stay sure that the element that is blocking the click is at the bottom of the window, but is the same result with  `yoffset=0` or `yoffset= 200`

**-For firefox**, the error is different:
` Error: mouseMoveTo
     Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
     System info: host: 'NBMAD889.local', ip: '10.23.81.204', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_111'
     Driver info: driver.version: RemoteWebDriver
         at moveTo("12", 0, 100) - moveToObject.js:55:22`

I tried also for Safari, and directly works without moveToObject action so I don't know where the problem comes.

Any help? Thanks!!

## Code To Reproduce Issue [ Good To Have ]

**My code:**
https://gist.github.com/jesusMT/5643dad02d8489be2b5cb9b6a5d1d617

**Comment by christian-bromann** [comment]
The `moveTo` is not part of the Webdriver spec and might be working in browser differently. I will be deprecated soon and you should replace that command by using the Action API once it is implemented.

**Comment by git-jiby-me** [comment]
@christian-bromann where can i track the depreciation and the replacement ?

**Comment by christian-bromann** [comment]
I will improve the deprecation messages with the next release
