### ISSUE TITLE
Simultaneous Modifier Keys

### ISSUE THREAD

**Issue by JonasMS** [webdriverio/webdriverio#2064]
## The problem
Running the following code:

`browser.keys(["Control"]).keys(["Alt"]).keys(["s"]).keys(["NULL"]);`

fails to "press down" the "s" key.

Briefly describe the issue you are experiencing (or the feature you want to see added to WebdriverIO). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, join the Gitter chat room ([![Gitter](https://badges.gitter.im/Join Chat.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge))!

## Environment

* WebdriverIO version: 4.0.7
* Node.js version: 6.6.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Link to Selenium/WebdriverIO logs
Log shows:

{"value":[""]}
{"value":[""]}
{"value":["s"]}
{"value":[""]}

**Comment by jankcat** [comment]
@JonasMS Sounds like you're having an implementation problem, not a Webdriver.io bug... you should join our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) and ask the userbase there!

**Comment by christian-bromann** [comment]
It should be
```js
browser.keys(["Control", "Alt", "s"]);
```
And yes, please join.
