### ISSUE TITLE
stack trace isn't detailed enough when error throwing from custom commands

### ISSUE THREAD

**Issue by RachelDai** [webdriverio/webdriverio#2065]
## The problem

I have two files, 1 is defined as custom commands, the other is spec file. When the test cases failed, I only got the stack trace information from custom command other than the context of the spec file

## Environment

* WebdriverIO version: 4.4.0
* Node.js version: v4.7.3
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable):  mocha, junit reporter

## Details
the error see below
`Test: Feature: validation of math When set validation in formulaV2, preview should show it correctly
Stacktrace: Error: unknown error: Element <span class="mq-textarea">...</span> is not clickable at point (28, 621). Other element would receive the click: <span class="mq-root-block mq-empty" mathquill-block-id="515"></span>
    at Object.Future.wait (/srv/api/questioneditor/node_modules/fibers/future.js:449:15)
    at Object.click (/srv/api/questioneditor/node_modules/wdio-sync/build/index.js:387:31)
    at Object.<anonymous> (/srv/api/questioneditor/tests/ui/customCommands/waitForAndClick.js:7:13)
    at /srv/api/questioneditor/node_modules/wdio-sync/build/index.js:321:29
    - - - - -
    at elementIdClick("2") - click.js:20:22
File: /srv/api/questioneditor/tests/ui/specs/ui/questions/validation/math.spec.js`

I don't know which line in math.spec.js caused this calling of waitForAndClick.js, neither the context around this failing in math.spec.js. Would be nice to have more stack trace information can be  given on original spec file so that easy to debug.

## Link to Selenium/WebdriverIO logs
`<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="feature_validation_of_math" timestamp="2017-05-12T04:48:24" time="3.988" tests="1" failures="0" errors="1" skipped="0">
    <properties>
      <property name="specId" value="535582102314ad93e8dfffc2ae92dacb"/>
      <property name="suiteName" value="Feature: validation of math"/>
      <property name="capabilities" value="chrome"/>
    </properties>
    <testcase classname="chrome.Feature: validation of math" name="When set validation in formulaV2, preview should show it correctly" time="2.747">
      <error message="&#xA;unknown error: Element &lt;span class=&quot;mq-textarea&quot;>...&lt;/span> is not clickable at point (28, 621). Other element would receive the click: &lt;span class=&quot;mq-root-block mq-empty&quot; mathquill-block-id=&quot;515&quot;>&lt;/span>&#xA;"/>
      <system-out>
        <![CDATA[
COMMAND: POST http://127.0.0.1:4434/wd/hub/session/f04be2f6-d122-4475-bdf7-e9c27a5dd450/execute - {"script":"return (() => {\n            window.previewValidation = false;\n            window.questionEditorApp.once('validationPreview:ready', () => {\n                window.previewValidation = true;\n            });\n        }).apply(null, arguments)","args":[]}
RESULT: {"state":"success","sessionId":"f04be2f6-d122-4475-bdf7-e9c27a5dd450","hCode":2021935519,"value":null,"class":"org.openqa.selenium.remote.Response","status":0}
COMMAND: POST http://127.0.0.1:4434/wd/hub/session/f04be2f6-d122-4475-bdf7-e9c27a5dd450/execute - {"script":"return (function (initJSON) {\n        window.apiReadyForTesting = false;\n        window.questionEditorApp.once('widget:ready', function () {\n            window.apiReadyForTesting = true;\n        });\n        window.questionEditorApp.setWidget(initJSON);\n    }).apply(null, arguments)","args":[{"is_math":true,"stimulus":"<p>[This is the stem.]</p>","type":"formulaV2","validation":{"scoring_type":"exactMatch","valid_response":{"score":1,"value":[{"method":"equivSymbolic","options":{"inverseResult":false,"decimalPlaces":10},"value":""}]}},"ui_style":{"type":"floating-keyboard"}}]}
RESULT: {"state":"success","sessionId":"f04be2f6-d122-4475-bdf7-e9c27a5dd450","hCode":1789998399,"value":null,"class":"org.openqa.selenium.remote.Response","status":0}
COMMAND: POST http://127.0.0.1:4434/wd/hub/session/f04be2f6-d122-4475-bdf7-e9c27a5dd450/execute - {"script":"return (function () {\n            return window.apiReadyForTesting;\n        }).apply(null, arguments)","args":[]}
RESULT: {"state":"success","sessionId":"f04be2f6-d122-4475-bdf7-e9c27a5dd450","hCode":1989042145,"value":false,"class":"org.openqa.selenium.remote.Response","status":0}
COMMAND: POST http://127.0.0.1:4434/wd/hub/session/f04be2f6-d122-4475-bdf7-e9c27a5dd450/execute - {"script":"return (function () {\n            return window.apiReadyForTesting;\n        }).apply(null, arguments)","args":[]}
RESULT: {"state":"success","sessionId":"f04be2f6-d122-4475-bdf7-e9c27a5dd450","hCode":1262562761,"value":false,"class":"org.openqa.selenium.remote.Response","status":0}
COMMAND: POST http://127.0.0.1:4434/wd/hub/session/f04be2f6-d122-4475-bdf7-e9c27a5dd450/execute - {"script":"return (function () {\n            return window.apiReadyForTesting;\n        }).apply(null, arguments)","args":[]}
RESULT: {"state":"success","sessionId":"f04be2f6-d122-4475-bdf7-e9c27a5dd450","hCode":1328808471,"value":false,"class":"org.openqa.selenium.remote.Response","status":0}
COMMAND: POST http://127.0.0.1:4434/wd/hub/session/f04be2f6-d122-4475-bdf7-e9c27a5dd450/execute - {"script":"return (function () {\n            return window.apiReadyForTesting;\n        }).apply(null, arguments)","args":[]}
RESULT: {"state":"success","sessionId":"f04be2f6-d122-4475-bdf7-e9c27a5dd450","hCode":728987599,"value":true,"class":"org.openqa.selenium.remote.Response","status":0}
COMMAND: POST http://127.0.0.1:4434/wd/hub/session/f04be2f6-d122-4475-bdf7-e9c27a5dd450/elements - {"using":"css selector","value":".lrn-qe-wait-panel"}
RESULT: {"state":"success","sessionId":"f04be2f6-d122-4475-bdf7-e9c27a5dd450","hCode":445923175,"value":[],"class":"org.openqa.selenium.remote.Response","status":0}
COMMAND: POST http://127.0.0.1:4434/wd/hub/session/f04be2f6-d122-4475-bdf7-e9c27a5dd450/elements - {"using":"css selector","value":"[data-lrn-qe-question-container]"}
RESULT: {"state":"success","sessionId":"f04be2f6-d122-4475-bdf7-e9c27a5dd450","hCode":1492743833,"value":[{"ELEMENT":"0"},{"ELEMENT":"1"}],"class":"org.openqa.selenium.remote.Response","status":0}
COMMAND: POST http://127.0.0.1:4434/wd/hub/session/f04be2f6-d122-4475-bdf7-e9c27a5dd450/execute - {"script":"return (() => {\n                return window.previewValidation;\n            }).apply(null, arguments)","args":[]}
RESULT: {"state":"success","sessionId":"f04be2f6-d122-4475-bdf7-e9c27a5dd450","hCode":926081835,"value":true,"class":"org.openqa.selenium.remote.Response","status":0}
COMMAND: POST http://127.0.0.1:4434/wd/hub/session/f04be2f6-d122-4475-bdf7-e9c27a5dd450/execute - {"script":"return (() => {\n        window.previewTriggered = false;\n        window.questionEditorApp.once('preview:changed', () => {\n            window.previewTriggered = true;\n        });\n    }).apply(null, arguments)","args":[]}
RESULT: {"state":"success","sessionId":"f04be2f6-d122-4475-bdf7-e9c27a5dd450","hCode":131020557,"value":null,"class":"org.openqa.selenium.remote.Response","status":0}
COMMAND: POST http://127.0.0.1:4434/wd/hub/session/f04be2f6-d122-4475-bdf7-e9c27a5dd450/elements - {"using":"css selector","value":"[data-lrn-qe-input-path=\"validation.valid_response.value[0].value\"] .mq-textarea"}
RESULT: {"state":"success","sessionId":"f04be2f6-d122-4475-bdf7-e9c27a5dd450","hCode":1008422804,"value":[],"class":"org.openqa.selenium.remote.Response","status":0}
COMMAND: POST http://127.0.0.1:4434/wd/hub/session/f04be2f6-d122-4475-bdf7-e9c27a5dd450/elements - {"using":"css selector","value":"[data-lrn-qe-input-path=\"validation.valid_response.value[0].value\"] .mq-textarea"}
RESULT: {"state":"success","sessionId":"f04be2f6-d122-4475-bdf7-e9c27a5dd450","hCode":801487664,"value":[{"ELEMENT":"2"}],"class":"org.openqa.selenium.remote.Response","status":0}
COMMAND: GET http://127.0.0.1:4434/wd/hub/session/f04be2f6-d122-4475-bdf7-e9c27a5dd450/element/2/displayed - {}
RESULT: {"state":"success","sessionId":"f04be2f6-d122-4475-bdf7-e9c27a5dd450","hCode":398885280,"value":true,"class":"org.openqa.selenium.remote.Response","status":0}
COMMAND: POST http://127.0.0.1:4434/wd/hub/session/f04be2f6-d122-4475-bdf7-e9c27a5dd450/element - {"using":"css selector","value":"[data-lrn-qe-input-path=\"validation.valid_response.value[0].value\"] .mq-textarea"}
RESULT: {"state":"success","sessionId":"f04be2f6-d122-4475-bdf7-e9c27a5dd450","hCode":1805284446,"value":{"ELEMENT":"2"},"class":"org.openqa.selenium.remote.Response","status":0}
COMMAND: POST http://127.0.0.1:4434/wd/hub/session/f04be2f6-d122-4475-bdf7-e9c27a5dd450/element/2/click - {}
COMMAND: GET http://127.0.0.1:4434/wd/hub/session/f04be2f6-d122-4475-bdf7-e9c27a5dd450/log/types - {}
RESULT: {"state":"success","sessionId":"f04be2f6-d122-4475-bdf7-e9c27a5dd450","hCode":1300174786,"value":["browser","driver","client","server"],"class":"org.openqa.selenium.remote.Response","status":0}
COMMAND: POST http://127.0.0.1:4434/wd/hub/session/f04be2f6-d122-4475-bdf7-e9c27a5dd450/log - {"type":"browser"}
RESULT: {"state":"success","sessionId":"f04be2f6-d122-4475-bdf7-e9c27a5dd450","hCode":1260369835,"value":[],"class":"org.openqa.selenium.remote.Response","status":0}
COMMAND: DELETE http://127.0.0.1:4434/wd/hub/session/f04be2f6-d122-4475-bdf7-e9c27a5dd450 - {}
RESULT: {"state":"success","sessionId":"f04be2f6-d122-4475-bdf7-e9c27a5dd450","hCode":2070989885,"value":null,"class":"org.openqa.selenium.remote.Response","status":0}
]]>
      </system-out>
      <system-err>
        <![CDATA[
Error: unknown error: Element <span class="mq-textarea">...</span> is not clickable at point (28, 621). Other element would receive the click: <span class="mq-root-block mq-empty" mathquill-block-id="515"></span>
    at Object.Future.wait (/srv/api/questioneditor/node_modules/fibers/future.js:449:15)
    at Object.click (/srv/api/questioneditor/node_modules/wdio-sync/build/index.js:387:31)
    at Object.<anonymous> (/srv/api/questioneditor/tests/ui/customCommands/waitForAndClick.js:7:13)
    at /srv/api/questioneditor/node_modules/wdio-sync/build/index.js:321:29
    - - - - -
    at elementIdClick("2") - click.js:20:22
]]>
      </system-err>
    </testcase>
  </testsuite>
</testsuites>`

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
Sorry but this is not possible. There is no chance to access the line where the custom command is executed and fails. I recommend to use a page object. With page object you will se where is got executed.
