### ISSUE TITLE
Do steps only if element exist on page

### ISSUE THREAD

**Issue by netmajor** [webdriverio/webdriverio#2066]
Hi,
```
let cancelButton = browser.$(selector);
  let exist = browser.isExisting(selector);
  if (exist === true) {
    cancelButton.waitForExist();
    cancelButton.moveToObject();
    cancelButton.waitForVisible();
    cancelButton.click();
  }
```

Even if element not exist on page, code enter if and throws timeout on waitForExist :/
If is a way to conditionally execute code ?

**Comment by christian-bromann** [comment]
The above code looks fine and it should work this way. Please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
