### ISSUE TITLE
No error is reported when wdio accidentally clicks on a floating footer

### ISSUE THREAD

**Issue by mltsy** [webdriverio/webdriverio#2067]
## The problem

When trying to click a button with `browser.click` on a page that has a fixed footer, wdio-testrunner will scroll down, click on the footer (which is hiding the button) and not return any error 😮 

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 7.10.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio-testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable): `selenium-standalone`, `static-server` and `mocha` framework

## Details
I've created a simple example page here: http://jsfiddle.net/112rh4zd/1/embedded/result/

The following test uses this example and fails:
```javascript
describe.only("Testing JSFiddle", function () {
  it("breaks", function() {
    browser.url("http://jsfiddle.net/112rh4zd/1/embedded/result/");
    browser.waitForExist('iframe', 1000);
    browser.frame($('iframe').value);
    browser.waitForExist('#the-button', 1000);
    browser.click('#the-button');
    expect($('#the-button').getText()).to.eq('clicked!')
  })
});
```

## Link to Selenium/WebdriverIO logs

https://gist.github.com/mltsy/e970631e136d056bc91a08f4e21a6c30

**Comment by christian-bromann** [comment]
Sorry but this is more a Selenium issue. I would recommend to remove the footer via `execute` command (if not needed). WebdriverIO can't do really anything to fix this.

**Comment by mltsy** [comment]
Well, I did find a workaround, once I identified the issue - the problem is that wdio is basically saying it clicked the button without reporting an error, and not clicking the button so the issue is very hard to identify in the first place (took me several hours).  Is there really no way for wdio to verify what element was actually clicked and report an error?  I assumed based on this ticket (https://github.com/webdriverio/webdriverio/issues/1435) that this was already being done in most cases, and this case was just an outlier... ?

**Comment by christian-bromann** [comment]
> Is there really no way for wdio to verify what element was actually clicked and report an error?

No because WebdriverIO did what it was suppose to do

> I assumed based on this ticket (#1435) that this was already being done in most cases, and this case was just an outlier... ?

This is a different issue. Also I think it is handled differently across drivers.

**Comment by mltsy** [comment]
Aha!  I see.  And it looks like Selenium is working on a fix for this issue (although it's been over a year since it's seen any activity, so who knows when there might be a solution): https://github.com/SeleniumHQ/selenium-google-code-issue-archive/issues/4175

So yeah, I understand where you're coming from. But to be fair, the WDIO documentation for `click` just says "Click on an element based on given selector." So technically, WDIO is *not* doing "what it was supposed to do" - or at least what the documentation says it will do.  (Okay, technically it doesn't say it will click on the element *identified* by the given selector, but that is implied)

So at the least, it might be a good idea to update the documentation somewhere to mention the issue, which I'd be happy to submit a PR for, but I'm not sure where would be the best place to put it.  Maybe a section on "fixed headers and footers" in the developer guide? (which seems like the most common case for people reporting this error)  Or maybe just in the "click" and "scroll" documentation? (or both?)

Another possible solution: I don't know how WDIO implements the scroll-then-click functionality, but a practical fix would be to have an option to specify a fixed footer or header height which would tell WDIO to add or subtract that much from the scroll position before clicking.  That seems like a valuable solution that might be simple enough, and also informative of the issue just by virtue of presence of a config option... ?

**Comment by christian-bromann** [comment]
> I don't know how WDIO implements the scroll-then-click functionality

This is not a functionality that is implemented by WebdriverIO. It comes from the browser driver.

> So technically, WDIO is not doing "what it was supposed to do"

I disagree :-P .. it clicked on the element. The problem is that another element received the click due to its css properties. Usually that gets detected but not if the element has a fixed position (I don't know why).

> Or maybe just in the "click" and "scroll" documentation?

Yes, I think we could add a passage in the click command docs.

Please note that WebdriverIO only speaks the Webdriver protocol and has besides that nothing to speak to the page. If any action is not working or was misinterpreted it is not WebdriverIOs fault. The browser driver should have detected that the element which received the click doesn't match the selector that was given. We are happy to implemented smart workarounds on these kind of issues but this is hard to detect.

**Comment by mltsy** [comment]
> I disagree :-P .. it clicked on the element. The problem is that another element received the click

Well, this is a matter of perspective (not specifically mine vs yours, but user vs author).  From the perspective of a library author, yes, WDIO "issued a click command for the selected element", but from a user's perspective it did not "click the selected element," it clicked a different element.  And the user documentation should reflect a user's perspective, so I'm happy you agree on that :+1:  I'll try to submit a PR.

I agree that the root of this particular issue is something that should be addressed in Selenium!  So this is not a big deal, as long as the documentation is updated, but if you *are* interested in a smart workaround, what do you think about the idea of updating the `click` function to add `header` and `footer` parameters to indicate additional scrolling that should be done to account for fixed headers/footers?  The algorithm for `click` could then be:

1. Scroll to the element
1. Get Position of element
1. If `headerHeight > elementY`, scroll up `headerHeight`
1. If `footerHeight > (windowHeight - elementY)`,  scroll down `footerHeight`
1. Click the element

**Comment by mltsy** [comment]
Actually, a *very* simple workaround would be to just add the same xOffset and yOffset to the `click` command as are available on the `scroll` command, because the most common use case will be:

```javascript
browser.scroll('.button1', 0, -150); // 150px fixed header
browser.click('.button1');
```

so it would be nicer to just say:

```
browser.click('.button1', 0, -150); // 150px fixed header
```

I think I could even write that PR, if you'd be up for it.

**Comment by christian-bromann** [comment]
That is not possible. A click is always connected to an element id. You can't set any offset.

**Comment by mltsy** [comment]
The offset isn't for where to click, it's for where to scroll to before clicking.  The click function would be updated as:

```javascript
scroll(selector, xOffset, yOffset);
//[original function]
```

**Comment by christian-bromann** [comment]
I don't think that this is should be part of the original click command. In most cases clicking on the element works as expected.

**Comment by mltsy** [comment]
Doesn't it always scroll to and click on the element anyway? (or maybe that's just the FirefoxDriver behavior...?)  If not, I guess it could be a new `scrollToAndClick` action?

**Comment by christian-bromann** [comment]
> or maybe that's just the FirefoxDriver behavior...?

it is
