### ISSUE TITLE
Click not working on elements that appear on mouse over.

### ISSUE THREAD

**Issue by simoami** [webdriverio/webdriverio#207]
I noticed that buttonClick is not working for elements that are hidden by default and appear only on mouse over. Is the `buttonClick` function triggering a click event only or a sequence of "mouseover, mousedown, mouseup, click, mouseout'. The latter is the expected behavior.

![screen shot 2014-05-07 at 1 19 40 pm](https://cloud.githubusercontent.com/assets/2038264/2906033/f1b80de0-d60b-11e3-8cc6-33da049b885a.png)

**Comment by Alkaia** [comment]
I've tried using just a plain .click() & moveToObject().click() and in both instances I get `element not visible` error. Anyone else seeing this?

**Comment by Alkaia** [comment]
This works: ```browser.execute(() => {
         document.querySelector('.element').click();
      })```
