### ISSUE TITLE
this.client is not called when getAttribute() is used inside another getAttribute() property. Please assist

### ISSUE THREAD

**Issue by ibrahimkhaleel** [webdriverio/webdriverio#2071]
Hello All:
I am new here and this is my first issue I am facing. Please pardon any mistakes :) and please assist me with the issue I am facing below. Or route me to the any other forums where I can find some solution with this issue.

## The problem
I am wrritten following code to read a elements of specific selectors using getAttribute() property and 3 layers of loop conditions. And I have called a getAttribute() to read my array of values. I am not sure what is an issue but the browser peroperties or commands are not able to read anything inside first getAttribute(). Please check following code I have:

```js
var webdriverio = require('webdriverio');

var options = {
   desiredCapabilities: {
        browserName: 'chrome'
    }
};

webdriverio
    .remote(options)
    .init()
    .url('https://test.group/')
    .click('//*[@name="UserId"]')
    .addValue('//*[@name="UserId"]','10000')
    .click('//*[@name="Password"]')
    .addValue('//*[@name="Password"]','somepw')
    .click('//*[@name="Submit"]')
    .frameParent()
    .frame("frmMenu")
    .click('p:nth-child(33) > a:nth-child(1)')
    .frameParent()
    .frame("frmDocument")
    .click('//*[@name="FuseChange"]')
    .pause(5000)
    .getTitle().then(function(title){
    console.log(title);
    })

    //To read all elements in an array of input type by id and select required attribute for an action
        .getAttribute('input[type=hidden]','id').then(function(attr){
        console.log(attr);

        //Read each element line by line
        (attr+"").split(',').forEach(function(rec) {
            // console.log('Current fuse name '+rec);
            if (rec!=''){
                // console.log(rec);
                var brwsr=this.client;
                var i;
                var fuseId = [];   //Array is defined
                fuseId.push(rec); //Array elements are added
                var fuseIdLen = fuseId.length; // Current Array length is captured
                // console.log(fuseIdLen);
                console.log("+++++++++++++++");
                //This will read each array value of fuse and checks it's value
                for (i = 0; i < fuseIdLen; i++) {
                    // console.log(ledColrLen);
                    var fuse = fuseId[i];
                    // fuseId.push(i);
                    // console.log(fuseId.push(i));
                    // var felem = '\'#'+fuse+'\'';
                    var felem = '\'#'+fuse+'\'';
                    //console.log(felem);
                    //BELOW CODE IS NOT EXECUTED FROM HERE
                    this.client
                        .getAttribute('\'#'+fuse+'\'', 'name').then(function(attr) {
                         console.log(attr);
                            })

               }
            }
            
        })
    })
           

    console.log('Hello main');

    .pause(10000)
    .end();
```

## Environment

* WebdriverIO version: 4.2.16
* Node.js version: 4.2.4
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable): wdio-cucumber-framework 0.0.6
wdio-spec-reported 0.0.3

## Details

I have mentioned appropriate comments what I am trying to achive with this code. Please let me know if anything I could provide you more in detailed.

**Comment by christian-bromann** [comment]
You can not just loop over properties and call other commands like that. Every command returns a promise and you need to make sure that it is handled properly. I strongly recommend to switch to the wdio testrunner to work with synchronous command. There is a boilerplate section showing off how you have to setup things. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
