### ISSUE TITLE
How to hit Post api in webdriver

### ISSUE THREAD

**Issue by Bhavana23** [webdriverio/webdriverio#2072]
Hi all,

Iam new to webdriver io and iam trying to hit a rest based post end point through webdriverIo.
Could you please suggest me a way to do this?

**Comment by christian-bromann** [comment]
You should not use WebdriverIO for testing your rest endpoints. Just use a normal `request` package from NPM. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
