### ISSUE TITLE
moveTo replacements for mouse gestures

### ISSUE THREAD

**Issue by burdiuz** [webdriverio/webdriverio#2074]
## The problem
I have a drawable canvas and need to do mouse down-move-up sequences, some with command keys. I see that moveTo is deprecated and it may not work as expected and there are general actions already implemented with offset arguments. But as I can see there are no actions with offsets for buttonDown/Up or moving mouse while button pressed. Do you plan to add these or did I miss any docs? Can I use mobile gestures(was looking for performMultiAction) API for Chrome or Firefox?

Thanks!

**Comment by christian-bromann** [comment]
> Do you plan to add these or did I miss any docs?

We will implement the action API soon.

> Can I use mobile gestures(was looking for performMultiAction) API for Chrome or Firefox?

No.

Please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
