### ISSUE TITLE
Document how to migrate from deprecated commands such as "keys" or "submit"

### ISSUE THREAD

**Issue by pzrq** [webdriverio/webdriverio#2076]
## The problem

New WebdriverIO warnings recently started showing up, with no explanation of how to resolve them. This appears to have been applied inconsistently (some have instructions, some do not) in https://github.com/webdriverio/webdriverio/commit/8b12008ca8280411984c271366fb3c8da8a66ddb 

For example, what should I replace `keys` or `submit` with?

![lots of new warnings](https://cloud.githubusercontent.com/assets/1217010/26141717/a165f118-3b20-11e7-8382-9de5cc5b4118.png)

## Environment

* WebdriverIO version: `^4.0.4` (via https://github.com/mongodb-js/hadron-spectron/blob/d08c763/package.json#L42 -> https://github.com/electron/spectron/blob/0ed376ef001a62cb7a50d2d730ede4626af17393/package.json#L27 )
* Node.js version: `7.4.0` (to be paired with [Electron](https://electron.atom.io/))
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Not sure, most likely whatever [spectron](https://github.com/electron/spectron) does out of the box.
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Details

N/A - Just would like better docs, thanks 👍 

## Link to Selenium/WebdriverIO logs

N/A - Just would like better docs, thanks 👍 

## Code To Reproduce Issue [ Good To Have ]

N/A - Just would like better docs, thanks 👍

**Comment by christian-bromann** [comment]
@pzrq we actually don't know yet how we would replace the `keys` command. It won't be removed from the WebdriverIO API until there is a replacement so take this warning not super seriously. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by pzrq** [comment]
Thanks for the info @christian-bromann

**Comment by pzrq** [comment]
I disagree as I think it fails to cover the [`since it has been superseded` requirement to deprecate production code](http://docs.oracle.com/javase/1.5.0/docs/guide/javadoc/deprecation/deprecation.html), but don't really care enough about the dozens of warning spam messages the suite is now getting in this area to push it, plenty of other areas of technical debt to address. 

Often other forms of testing such as [enzyme](https://github.com/airbnb/enzyme) tests end up being more practical and easier to work with for our team.

**Comment by pzrq** [comment]
Sorry it occurred to me on the way home I forgot to include a positive example of how I'd expect something like this to be done, a good one recently was Facebook's React introducing new deprecation warnings, e.g. `We never add warnings without providing an incremental path forward.`, hope that helps in future:
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#new-deprecation-warnings

**Comment by christian-bromann** [comment]
thanks for the feedback @pzrq. I totally agree with you and will try to provide such information for these commands.

**Comment by Godsmith** [comment]
Is there any way to suppress the warning? I have set logLevel to silent but it does not make a difference.

**Comment by christian-bromann** [comment]
@Godsmith just use `v4.7.x` which doesn't contain these warnings

**Comment by Godsmith** [comment]
Ok, that will do, thanks.

**Comment by RafaelPrates** [comment]
@christian-bromann I was using the v4.8 and downgraded it, but it still showing the alerts. 
I'm using cucumber-boilerplate project

**Comment by christian-bromann** [comment]
Make sure you use the downgraded version. These message got introduced in v4.8

**Comment by nylen** [comment]
Please remove this warning until there is a path forward.

**Comment by scottrippey** [comment]
FWIW, I couldn't downgrade to WDIO 4.7, so here's the slightly brittle solution I went with: 
```
/**
 * WebDriverIO 4.8.0 outputs all kinds of "deprecation" warnings
 * for common commands like `keys` and `moveToObject`.
 * According to https://github.com/Codeception/CodeceptJS/issues/531,
 * these deprecation warnings are for Firefox, and have no alternative replacements.
 * Since we can't downgrade WDIO as suggested (it's Spectron's dep, not ours),
 * we must suppress the warning with a classic monkey-patch.
 * 
 * @see webdriverio/lib/helpers/depcrecationWarning.js
 */
// Filter out the following messages:
const wdioDeprecationWarning = /^WARNING: the "\w+" command will be depcrecated soon./; // [sic]
// Monkey patch:
const warn = console.warn;
console.warn = function suppressWebdriverWarnings(message) {
  if (message.match(wdioDeprecationWarning)) return;
  warn.apply(console, arguments);
};
```

**Comment by hexsprite** [comment]
It's kind of a useless warning if there's no action that you can take. It's just noise. It should be removed until you give people an alternative.

**Comment by hexsprite** [comment]
@scottrippey thanks for sharing your snippet, that's quite helpful!

@christian-bromann would you be open to removing the warnings until there are valid alternatives?

**Comment by christian-bromann** [comment]
> would you be open to removing the warnings until there are valid alternatives?

I would rather publish the alternative

**Comment by oliviertassinari** [comment]
6 months with those warnings. Can we please remove them now and add them back once there is a migration plan 🙏.

**Comment by campside** [comment]
+100 for @oliviertassinari

**Comment by thebarty** [comment]
Yeah, pease remove the warning. It just stole me 2 minutes :-)

**Comment by christian-bromann** [comment]
@rmngrc we are working actively on v5 which replaces the implementation of these commands using the action command which is new in the Webdriver spec. We are not able to fix browser drivers that are not supporting the latest specification yet. Also, @rmngrc @nylen, I want to emphasise that this is an open source project. If you feel that something could get improved, please provide a PR! WebdriverIO is not baked by a company, everyone who is working on this does this in his free time.

Last but not least, the latest version allows to disable this warnings.

**Comment by jiteshsojitra** [comment]
Applied solution for Spectron (which uses webdriverio) as mentioned in: https://github.com/electron/spectron/issues/286#issuecomment-393393514 and solved my issue which was pending since long.

    this.app = new Application({
         path: fullPath,
         args: ['.'],
         webdriverOptions: {
            "deprecationWarnings": false
    }});
