### ISSUE TITLE
Getting 'Custom reporters must export a unique 'reporterName' property' issue while trying to use Custom Reporters.

### ISSUE THREAD

**Issue by JaspreetBamrah** [webdriverio/webdriverio#2077]
## The problem
I am getting the following error message while trying to use the Custom Reporters. 
My config file: 
var CustomReporter = require('./reporter/my.custom.reporter');

exports.config = {
reporters: [CustomReporter],
  reporterOptions: {
        outputDir: './'
  }
}
My.custom.reporter.js contains:
var util = require('util'),
    events = require('events');
var CustomReporter = function(options) {
....
}
same as available in the project.

ERROR: Error: Custom reporters must export a unique 'reporterName' property
    at Launcher.initReporters 

## Environment

1. appium -v. 1.6.4
2. npm -v 4.2.0
3. node -v v7.10.0
4. java version "1.8.0_131"

Can someone help please.

**Comment by andriilazebnyi** [comment]
@JaspreetBamrah 

Add `reporterName` property to `CustomReporter`.

```
var CustomReporter = require('./reporter/my.custom.reporter');
CustomReporter.reporterName = 'myCustomReporter';
```

**Comment by JaspreetBamrah** [comment]
@andriilazebnyi Thank you so much for your reply. And this goes in the config file?
 Sorry I am still a new learner and I want to implement good looking HTML reports for my testing test results in Jasmine with WebDriverIO. Any suggestions please.

**Comment by JaspreetBamrah** [comment]
@andriilazebnyi Adding the following code in config file did resolve my issue
var CustomReporter = require('./reporter/my.custom.reporter');
CustomReporter.reporterName = 'myCustomReporter';

But I want to have a HTML formatted report. Can we do this using Custom Reporter in WebDriverIO or is there a plugin?

**Comment by christian-bromann** [comment]
> I want to implement good looking HTML reports for my testing test results in Jasmine with WebDriverIO

Why don't you use the [Allure](http://webdriver.io/guide/reporters/allure.html) reporter?

**Comment by JaspreetBamrah** [comment]
I did try my hands on the [Allure](http://webdriver.io/guide/reporters/allure.html) reporter:

wdio config:
reporters: [allure],
  reporterOptions: {
        allure: {
            outputDir: 'allure-results'
        }        
  },
Command I am using:
allure generate './allure-results'  && allure report open

Command Result:
Allure: Target directory /Users/jaspreet/Desktop/Jazz/Official/tests-mobileBK/tradie/allure-report for the report is already in use, add a '--clean' option to overwrite
jaspreets-mbp:tradie jaspreet$ allure generate './allure-results' --clean  && allure report open
Report successfully generated to allure-report
Could not parse arguments: Expected a command, got report
Usage: allure [options] [command] [command options]
  Options:
    --help
      Print commandline help.
    -q, --quiet
      Switch on the quiet mode.
      Default: false
    -v, --verbose
      Switch on the verbose mode.
      Default: false
    --version
      Print commandline version.
      Default: false
  Commands:
    generate      Generate the report
      Usage: generate [options] The directories with allure results
        Options:
          -c, --clean
            Clean Allure report directory before generating a new one.
            Default: false
          --profile
            Allure commandline configuration profile.
          -o, --report-dir, --output
            The directory to generate Allure report into.
            Default: allure-report

    serve      Serve the report
      Usage: serve [options] The directories with allure results
        Options:
          -p, --port
            This port will be used to start web server for the report.
            Default: 0
          --profile
            Allure commandline configuration profile.

    open      Open generated report
      Usage: open [options] The report directory
        Options:
          -p, --port
            This port will be used to start web server for the report.
            Default: 0

    plugin      Generate the report
      Usage: plugin [options]
        Options:
          --profile
            Allure commandline configuration profile.

Can you help please. What am I missing here?

**Comment by christian-bromann** [comment]
It's all in the docs 😉

**Comment by christian-bromann** [comment]
I think this can be closed now. If you have further questions on these topics come join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
