### ISSUE TITLE
Throw error in step def crashes the test

### ISSUE THREAD

**Issue by Kignuf** [webdriverio/webdriverio#2080]
## The problem
When a step definition (cucumber) throws an error, wdio fails to capture it and crashes with a meaningless error.
```
undefined
no stack available
```

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 6.10.0
* wdio testrunner
* Running synchronous tests
* Additional wdio packages used (if applicable):
	* "wdio-concise-reporter": "^0.1.2",
	* "wdio-cucumber-framework": "^0.2.16",
	* "wdio-dot-reporter": "0.0.8",
	* "wdio-spec-reporter": "^0.1.0"

## Code To Reproduce Issue
Feature file
```
Feature: Test feature
	Scenario: Test scenario
		Given test
		Then  Throw error
```

Step definition file
```
module.exports = function steps() {
	this.defineStep(
		/^test$/, function(){
			console.log('test step')
		})
	this.defineStep(
		/^Throw error$/, function(){
			throw('custom test error')
		})
}
```

**Comment by christian-bromann** [comment]
> throw('custom test error')

I guess it will work if you throw an error like `throw new Error('custom test error');`. This is not captured because Cucumber.js doesn't capture it.

**Comment by Kignuf** [comment]
Indeed, thanks for the info and appologies for the trouble !
