### ISSUE TITLE
INSTALL: NPM install within Docker failing (implicit `git clone` being executed)

### ISSUE THREAD

**Issue by guahanweb** [webdriverio/webdriverio#2081]
## The problem

When building a docker image with smoke tests running on webdriver, we noticed a failure due to an implicit `git clone` being called:

```
npm http request GET https://registry.npmjs.org/webdriverio
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:christian-bromann/dargs.git /root/.npm/_git-remotes/git-github-com-christian-bromann-dargs-git-93c653bc: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:christian-bromann/dargs.git /root/.npm/_git-remotes/git-github-com-christian-bromann-dargs-git-93c653bc: undefined
...
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ENOGIT

npm ERR! not found: git
```

This is occurring when I execute simply an `npm install --ignore-scripts` (fails with or without the ignore flag).

## Environment

* WebdriverIO version: 4.7.1
* Node.js version: 6.10.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): n/a
* if wdio testrunner, running synchronous or asynchronous tests: n/a
* Additional wdio packages used (if applicable): n/a

## Details

Due to the sandboxed Docker build, the `git` command is not installed (intentionally). It is not expected at all that there would be a supplemental `git clone` call from within an `npm install` execution.

How are we able to install within a Docker context without requiring `git` to be installed?

Thanks!

**Comment by christian-bromann** [comment]
Seems that your are installing gulp-webdriver (which would be nice to know) which used that dependency via git but not anymore. Just use the latest gulp-webdriver version and this issue should be fixed.
