### ISSUE TITLE
browser.waitForExist( ) with reverse=true fails to detect element not existing and throws exception

### ISSUE THREAD

**Issue by kirksl** [webdriverio/webdriverio#2082]
## The problem
the specific situation i'm coding is a popup element that previously didn't exist in the DOM that exists after i enter invalid credentials, waits for X seconds and then fades away and leaves the DOM.

browser.waitForExist( ) with reverse=false seems to work perfect.  it immediately returns true as soon as an element exists in the DOM.

browser.waitForExist( ) with reverse=true fails.  it loops with **POST /elements** calls while the element exists in the DOM and as soon as the element no longer exists a final **POST /elements** call is made that waits for the entire duration of the **waitForTimeout** defined, the response from the POST call returns **"value": []** and an exception is thrown **Error: element ("span=Wrong username/password. Please try again.") still  visible after 30000ms**.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: v6.10.3
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync: true
* Additional wdio packages used (if applicable): "selenium-standalone": "^6.4.1", "wdio-mocha-framework": "^0.5.10"

## Link to Selenium/WebdriverIO logs

final **POST /elements** after element has now left the DOM that waits for entire timeout before an exception is thrown

REQUEST
{
	"using": "xpath",
	"value": "//span[normalize-space() = \"Wrong username/password. Please try again.\"]"
}
RESPONSE
{
	"sessionId": "ed3da0ea-a5da-420f-bdf9-d3807702f5f8",
	"status": 0,
	"value": []
}

## Code To Reproduce Issue [ Good To Have ]

try
{
    // target locator that will get pulled from DOM before timeout_here
    return driver.waitForExist(your_locator_here, timeout_here, true);
}
catch(e)
{
    console.log(e);
    throw e;
}

**Comment by christian-bromann** [comment]
@kirksl do you have implicit timeout set?

**Comment by kirksl** [comment]
@christian-bromann i do.  first command in my mocha->before( ).  browser.timeouts('implicit', 30000);

**Comment by christian-bromann** [comment]
that is the issue .. the last wait is due to your implicit timeout.

**Comment by kirksl** [comment]
@christian-bromann any chance information like this can find it's way into the exception wdio throws or in the webdriver.io api documentation under timeouts?  information being "ensure you have not set an implicit wait" when using wait*** methods.

**Comment by christian-bromann** [comment]
Well if you explicitly set the implicit timeout to 30s why would you expect a warning then? You should not use implicit waits in general. I can't add warnings for edge cases in each exception.

**Comment by kirksl** [comment]
@christian-bromann i think it's reasonable based off the wdio documentation to see how someone could get confused.  when i goto api -> timeouts it tells me it is the timeout of when to abort locating elements.  when i goto api -> waitforexist it tells me the spec'd 'ms' or 500ms(default) is the timeout of when to abort locating elements.  it all feels complimentary and almost as though one would override the other.  likely the wait*** overriding the global implicit timeout.

coupling this with your statement that nobody should use implicit waits in general, seems to merit at least updating the documentation.  for me personally it would be great if wdio would just abstract away stuff like this to avoid there ever being a conflict.  eg if i set implicit, great.  if i then go for a wait*** command play nice and just ignore the implicit and run with the wait timeout strategy instead.

**Comment by christian-bromann** [comment]
I see your point. However if you've set an implicit timeout why do you use explicit waits then? I could change the implicit timeout to make waitForExist work but that would require to always check the implicit wait timeout. I think we can start with adding a note to the waitForExist command mentioning the problem of implicit vs explicit waits. What do you think?

**Comment by kirksl** [comment]
logically my idea was this.  set implicit to give me a method of employing global wait coverage.  recruit the wait*** methods as needed for situations that implicit does not cover.  eg a popup fades in(dom element created), popup fades out(dom element destroyed).  i need a method to wait for that popup to vanish and ensure it did.  eg some pages or elements may need a unique wait due to network, but i want to keep my wait times shorter otherwise using implicit.  eg coverage for other things non-element related, using waitUntil( ) to wait for a url to change.

i think we should definitely notate the problem of implicit/explicit waits.  it would be great if wdio could additionally abstract away this problem all together in the code.  it's a great tool that abstracts away a lot of ceremony and things that cause headaches.  this seems like another great thing to abstract away.

**Comment by christian-bromann** [comment]
> it would be great if wdio could additionally abstract away this problem all together in the code.

I doubt that this is possible. How would you want to abstract this away? Implicit timeouts are managed on the Selenium side. You could create a new `element` method that uses waitForExist to simulate implicit waiting via explicit waits.

**Comment by kirksl** [comment]
it doesn't seem possible to traverse between implicit/explicit if setting an implicit timeout in wdio equates to this https://www.w3.org/TR/webdriver/#dfn-session-implicit-wait-timeout wherein it's static for the life of the webdriver session.  the only option i can see for wdio to abstract this away is to simulate in it's code what the native selenium implicit wait tries to achieve wherein you could traverse between both strategies.  i'm just thinking out loud not sure what that entails, if it's possible and the headache it brings to implement.  might be overkill and good documentation should rule the day?
