### ISSUE TITLE
Only before, after and afterSuite hooks working in wdio.conf 

### ISSUE THREAD

**Issue by aaronbriel** [webdriverio/webdriverio#2084]
## The problem

The only hooks in wdio.conf.js that appear to be working in my configuration are 'before', 'after', and 'afterSuite'. I have console logs in all of the hooks, and these are the only ones that are printing. Note that I am using wdio-cucumber-framework.

## Environment

* WebdriverIO version: 4.7.1
* Node.js version: v7.9.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): 
wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): wdio-cucumber-framework

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Selenium/WebdriverIO logs

Logs are N/A

## Code To Reproduce Issue [ Good To Have ]

wdio.conf contains simple statements like the following for each hook:
    beforeSuite: function (suite) {
        console.log("beforeSuite");
    },

Of most importance are beforeSuite/afterSuite and also beforeTest/afterTest. I am aware of the following issue for the latter hooks:
https://github.com/webdriverio/webdriverio/issues/1894

However, is this applicable to wdio-cucumber-framework? If so, how can one implement hooks that are execute before/after scenarios using this module?

**Comment by christian-bromann** [comment]
`beforeSuite` doesn't work with Cucumber.js as there is no suite in Cucumber. For Cucumber there are other hooks you can use: https://github.com/webdriverio/webdriverio/blob/master/examples/wdio.conf.js#L316. Note that onPrepare/Complete and before/afterSession is available in all frameworks.

**Comment by aaronbriel** [comment]
I must have an older version of wdio.conf. Thanks!
