### ISSUE TITLE
Accessing browser error log from a custom reporter

### ISSUE THREAD

**Issue by tim-zhong** [webdriverio/webdriverio#2085]
I'm working on a custom reporter that records output in the browser's console when an error occurs. I couldn't figure out a way to capture the browser's error log from my custom reporter since it lives in a different process and has no access to the global browser object.

Any suggestion?
Thanks in advance!

**Comment by christian-bromann** [comment]
This is not possible. Reporter live in a different context/process. You can create an additional service to your reporter that can execute these log commands and sends them to the reporter.
