### ISSUE TITLE
dragAndDrop action is not working because of buttonUp and buttonDown commands

### ISSUE THREAD

**Issue by ilyaskl** [webdriverio/webdriverio#2092]
## The problem

I have a price range filter and tried to use dragAndDrop action to move filter values.
It seems that problem is with buttonUp and buttonDown commands which are deprecated.

**Comment by christian-bromann** [comment]
Hi @ilyaskl yes, these are deprecated and soon to be replaced with action API commands. These haven't been implemented in the browser drivers yet. Once this happened and WebdriverIO supports it you should switch to those.

**Comment by christian-bromann** [comment]
If you have more questions join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
