### ISSUE TITLE
no stack available error

### ISSUE THREAD

**Issue by Kignuf** [webdriverio/webdriverio#2093]
## The problem
Hello,

My goal is to run a login test on an android app. I'm using cucumber as a test runner. I have another mac with a basic selenium grid setup and two genymotion devices (along with two instances of appium server).

When I run the test on my computer it will most likely pass, but once every 10-20 tries the framework crashes in the middle of the run and prints "no stack available". However on a colleague's mac the error is reproduced 100%.

## Environment

* WebdriverIO version: **4.7.1**
* Node.js version: **6.10.0**
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): **testrunner**
* if wdio testrunner, running synchronous or asynchronous tests: **synchronous**
* Additional wdio packages used (if applicable): 
    * **wdio-cucumber-framework@0.2.16** (also tried with 0.3.0)
    * "wdio-concise-reporter": "^0.1.2",
    * "wdio-dot-reporter": "0.0.8",
    * "wdio-spec-reporter": "^0.1.0",

## Details
I have a cucumber hook setup to save the xml source upon scenario failure. This hook is executed as I can see the xml file gets saved however no screenshot gets saved when this error occurs.

It always occur at the exact same time: login and password have been entered, next action is to click the login button.

Looking precisely at the appium logs I see the following sequence of events
```
--> POST /wd/hub/session/[id]/element : call to find password textbox
<-- POST /wd/hub/session/[id]/element status 200 for password textbox
--> POST /wd/hub/session/[id]/element/[id]/clear : call to clear pwd textbox
<-- POST /wd/hub/session/[id]/element/[id]/clear : status 200 for clear
--> POST /wd/hub/session/[id]/element/[id]/value : call to type pwd into password textbox
--> GET /wd/hub/session/[id]/source : call to get the xml source of the UI
<-- POST /wd/hub/session/[id]/element/[id]/value : status 200 for set value in password textbox
<-- GET /wd/hub/session/[id]/source : status 200 for source
--> POST /wd/hub/session/[id]/element : call to find login button
--> DELETE /wd/hub/session/[id]
<-- POST /wd/hub/session/[id]/element : status 200 for login button
--> POST /wd/hub/session/[id]/element/[id]/click : call to click login button
<-- POST /wd/hub/session/[id]/element/[id]/click : status 404 for click login button
<-- DELETE /wd/hub/session/[id] : status 200 for delete session
```

This shows that at some point we have two things running in parrallel. The scenario continues to run normally: after the password was typed, we ask appium to click login button. But in the meantime the cucumber hook got triggered and we made calls to GET source, then wdio continued with the failing procedure, hence the call to DELETE session (I have set cucumber failFast option to true so the test terminates on 1st failure).

## Link to Selenium/WebdriverIO logs
The error is a bit different depending on the reporter being used.

https://gist.github.com/Kignuf/dbdafa293558182c22b1fc2ac90479b0

## Code To Reproduce Issue [ Good To Have ]
This occurs on my company's app, and I have setup the project using the pageObject pattern so it's a bit complicated to share code that would reproduce the issue. If you have instructions to get more verbose logs, don't hesitate and I'll proceed.

That being said, the code could be summarized as follow (supposing I concatenate all the steps from .feature file into one big step definition):
```
// click login from welcome screen
browser.element('//xpath-selector1').click()
// verify login screen is loaded
elements.forEach((el) => {
    // actually I don't wait 10s for each element, I have a pool of X seconds and I remove the waited time at each loop so in the end I wait for all elements to be found within a maximum of X seconds
    browser.waitForExist(el.selector, 10000)
})

// Now fill login, pwd and click submit
browser.element('//xpath-selector2').setValue('email@email.com').pause(500)
browser.element('//xpath-selector3').setValue('password').pause(500)
browser.element('//xpath-selector4').click()

// verify next screen gets loaded properly (same forEach loop as before)
// ...
```

/features/support/hooks.js
```
module.exports = function() {

	// ================ Scenario hooks ================	
	this.After(function(scenario){
		// this hook will be executed for all scenarios, after they are finished

		// when scenario is failed, save page xml for the report
		if(scenario.isFailed()){
			var pageSource = browser.getSource()
			fs.writeFileSync('./lasterror.xml', pageSource)
		} else {
			//
		}
	})
}
```

**Comment by christian-bromann** [comment]
Can you please share logs of WebdriverIO and Appium?

**Comment by Kignuf** [comment]
I did attach the logs in a gist, here: https://gist.github.com/Kignuf/dbdafa293558182c22b1fc2ac90479b0

**Comment by christian-bromann** [comment]
I am not sure which Appium version you are using but this one can't click on `CLASS=android.widget.Button`, see https://gist.github.com/Kignuf/dbdafa293558182c22b1fc2ac90479b0#file-appium-logs-L520

**Comment by Kignuf** [comment]
I'm using appium 1.6.4
The 404 on the click is due to a previous call that deleted the session, I explained everything in my original post.
Basically the test goes smoothly, it finds elements, clicks, types text and suddenly something goes wrong on the client side (my bet is that's a problem in either webdriverio or cucumber) and it terminates the session.

**Comment by Kignuf** [comment]
Found another person having this issue: http://stackoverflow.com/questions/41010577/undefined-error-in-wdio-cucumber-framework

**Comment by bevanhunt** [comment]
I am using wdio-cucumber-bolierplate and getting the "undefined - no stack trace available". I solved it by upping the timeout in the wdio.conf.js file to 99999 (with shorter timeouts on all my calls) because otherwise my long tests were hitting the default of 20000 (and thus raising the undefined error).

**Comment by Kignuf** [comment]
Thanks @bevanhunt, I tried your suggestion this morning and I think that was it. I need a bit more time to be 100% sure that the issue never occurs again anymore, so I'm not closing the ticket immediately.

Additionaly I am wondering if we could not improve the error with a nice message like this:
"cucumber: step timed out"

Not sure if that's something I can do myself, but I can have a look.

**Comment by Kignuf** [comment]
@christian-bromann just to let you know that I checked with a simple project with cucumber 1.3.3 only and the fail due to step timeout is correctly reported. So I guess the problem is on wdio side. Though I have no idea where to start looking and this is probably way above my current skillset.

https://gist.github.com/Kignuf/135784f380a49bdc3249999f9b108427
