### ISSUE TITLE
Add ability to execute Service hooks before matching test runner hooks

### ISSUE THREAD

**Issue by patthiel** [webdriverio/webdriverio#2097]
## The problem

When using an external service loaded via the `services` property in the wdio.config.js, I would like the methods in the service hooks to be called first, then any matching hooks defined in the wdio.config.js to be called.

**Given** a service that starts some server before each spec
**When** Defining additional behavior in the matching `before()` hook in the  wdio.config.js
**Then** I can add the additional behavior in my wdio test runner config hook that rely on that service being initialized.

This is an enhancement / feature request.

* WebdriverIO version: Latest
* Node.js version: 6.9.8
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio test runner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable): wdio-jasmine-framework

**Comment by christian-bromann** [comment]
@patthiel can you bring up a specific scenario where this feature is necessary?

**Comment by patthiel** [comment]
Sure. Since our application heavily caches api calls, when running our tests using mock services we've found it best for us to start a fresh instance of our server on every test spec and then on completion of the spec to kill the instance. 

I am initializing mock services via mountebank through a wdio service module that has its setup calls in the before hook. i am loading our server in my wdio.conf.js before hook. Since the calls i am trying to proxy are made on the start of the application, i want to make sure mountebank is running and proxying calls before i start our server.

**Comment by christian-bromann** [comment]
@patthiel why don't you start the mock service in the beforeSession hook then and the web server in the before hook?

**Comment by patthiel** [comment]
Huh.. I had no idea that was even a hook, missed https://github.com/webdriverio/webdriverio/pull/1745 a year ago i guess.. I no longer need this. Thanks @christian-bromann
