### ISSUE TITLE
How do I run a test?

### ISSUE THREAD

**Issue by megamindbrian** [webdriverio/webdriverio#2099]
## The problem
http://webdriver.io/guide/testrunner/frameworks.html
Lacking documentation.

Can you please explain on that page, how do I launch a test?

I am using:
    mocha -t 300000 --compilers js:babel-core/register --recursive ./test

But webdriverio never start, never connects to the selenium instance, and doesn't output any error information.

**Comment by christian-bromann** [comment]
Please go over the developer guide: http://webdriver.io/guide.html and have a look at the docs in general 😉 . Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
