### ISSUE TITLE
Show browser GUI with testrunner

### ISSUE THREAD

**Issue by swashcap** [webdriverio/webdriverio#2103]
Is there any way to show the Firefox GUI (non-headless) when running with the `wdio` CLI testrunner?

**Comment by swashcap** [comment]
Update: I’m running the Selenium standalone manually with chromedriver, which can spawn the Chrome browser GUI. But I get this:

```
unknown error: cannot get automation extension
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
running chrome
Error: An unknown server-side error occurred while processing the command.
    at windowHandleSize() - setViewportSize.js:72:17
```

How _does_ `wdio` spawn Firefox/Chrome/etc. and actually run tests without a GUI? Is there a hidden option to show browser windows?

**Comment by christian-bromann** [comment]
@swashcap not sure why it isn't showing the GUI for you. When I run a wdio test on my Mac it pops up a browser just normal. There error you get for chrome is a known chromedriver bug. Please update your chromedriver to the latest. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by swashcap** [comment]
:+1: Thanks for the suggestion! I’ll try upgrading.
