### ISSUE TITLE
interface touch bug??

### ISSUE THREAD

**Issue by gogoyqj** [webdriverio/webdriverio#2104]
## The problem

[lib/commands/touch.js line 23](https://github.com/webdriverio/webdriverio/blob/master/lib/commands/touch.js#L23)

```jsx
return this.getLocation(selector).then((val) =>
        this[touchCommand](val.x, val.y))
```

Should it be??
```
return this.getLocation(selector).then((val) =>
        this[touchCommand](val.ELEMENT, val.x, val.y))
```

since in doc:
```
Usage

browser.touchClick(ID);
Parameters

Param	Type	Details
ID	String	ID of a WebElement JSON object to route the command to
```
![pro](https://cloud.githubusercontent.com/assets/1776278/26444237/1b0ed1da-416e-11e7-97ba-bd661351f662.png)

actually, while using `browser.touch('#View')`, "stale element reference: element is not attached to the page document" error throws. since `this.element` returns '{ELEMENT: 1}', `this.getLocation` returns `{x: 0, y: 44}`, then calls `this.touchClick(0, 44)`.

Please inform me whether is this a real bug or just something i missed, thx.

**Comment by christian-bromann** [comment]
It should be `this.touchClick(1)`. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by gogoyqj** [comment]
well, i tried, and it seems need more modification... i change those 2 files:

`https://github.com/webdriverio/webdriverio/blob/master/lib/commands/getLocation.js#L66`
```
                            results.push({
                                x: location.value.x,
                                y: location.value.y,
                                ELEMENT: current.ELEMENT
                            })
```

`https://github.com/webdriverio/webdriverio/blob/master/lib/commands/touch.js#L22`
```
    return this.getLocation(selector).then((val) =>
        this[touchCommand](val.ELEMENT, val.x, val.y))
```
