### ISSUE TITLE
Unable to use appium locators with id

### ISSUE THREAD

**Issue by APshenkin** [webdriverio/webdriverio#2105]
## The problem

Need to modify regex for id validation. Now if there are `: . /` symbols in locator that starts with `#` WebdriverIO doesn't understand that it's `ID` locator
https://github.com/webdriverio/webdriverio/blob/master/lib/helpers/findElementStrategy.js#L41
Now:
^#-?[_a-zA-Z]+[_a-zA-Z0-9-]*$
Should be:
^#-?[_a-zA-Z]+[_a-zA-Z0-9.:/-]*$
## Environment

* WebdriverIO version: 4.7
* Node.js version: 6.9.5
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Standalone

## Code To Reproduce Issue [ Good To Have ]
here is locator to test regex `#io.selendroid.testapp:id/buttonStartWebview`

**Comment by christian-bromann** [comment]
fixed by #2156
