### ISSUE TITLE
SetCookie is not setting "HTTPOnly" flag as true.

### ISSUE THREAD

**Issue by poornimaramkumar** [webdriverio/webdriverio#2106]
## The problem
before() {
		browser.url(config.healthUrl);
		browser.addCommand('customSetCookies', () => {
			for (let i = 0; i < cookies.length; i++) {
                                console.log(cookies[i]);
				browser.setCookie(cookies[i]);
			}
		});
		browser.customSetCookies();
	}
cookies are printed correctly with httponly flag as true, but when setting it, it is not set as True. Specs run fine but it is not having the http flag - true in the cookies. No logs to show. Have attached a screenshot to show that the http is not set to true and the cookie that i have.
Sample cookie when retrieving and the same is set using browser.setCookie() : {"path":"/","domain":"***-***.****.co","name":"session","httpOnly":true,"expiry":1495807779,"hCode":1984987798,"secure":true,"value":"eee","class":"org.openqa.selenium.Cookie"}
## Environment

* WebdriverIO version: 4.6.2
* Node.js version:6.9.4
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):
	        "wdio-junit-reporter": "0.2.0",
		"wdio-mocha-framework": "0.5.8",
		"wdio-phantomjs-service": "0.2.2",
		"wdio-selenium-standalone-service": "0.0.8"

![image](https://cloud.githubusercontent.com/assets/11818208/26454697/d49639e2-4135-11e7-92f3-299cf5c6b32f.png)

Please let me know if you need any other information.

**Comment by christian-bromann** [comment]
Can you provide some logs please? As you can see [here](https://github.com/webdriverio/webdriverio/blob/master/lib/commands/setCookie.js#L35) we propagate the whole cookie object to the browser driver. If it doesn't set httpOnly flag correctly we should file an issue in the browser driver project. WebdriverIO unfortunately can't do anything here.
