### ISSUE TITLE
Can't override config for adding a chrome extension using Launcher API

### ISSUE THREAD

**Issue by oliverswitzer** [webdriverio/webdriverio#2108]
## The problem

When trying to use the Launcher class to launch webdriverio with a chrome extension loaded, my configuration override for browser capabilities isn't getting added.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: v6.10.3
* Using standalone mode

## Details

Using this configuration to launch the runner:

```.js
   const launcher = new Launcher('wdio.conf.js', {
        capabilities: [{
          chromeOptions: {extensions: [base64ConvertedExtensionCrxFile]} // 
        }]
      }
    )
```

My `wdio.conf.js` file looks like:

```.js
exports.config = {
...
    capabilities: [{
        maxInstances: 5,
        browserName: 'chrome'
    }],
...
```
When the browser spins up, no chrome extension is loaded. Upon further inspection, it seems as if [at the point in time that it calls `merge` on `ConfigParser`](https://github.com/webdriverio/webdriverio/blob/master/lib/utils/ConfigParser.js#L137), it does not update the [`_capabilites` array](https://github.com/webdriverio/webdriverio/blob/master/lib/utils/ConfigParser.js#L83), it only updates the `capabilities` key *within* `this._config.capabilities`. As a result, no chrome extension appears in the browser when launched.

E.g. at the end of the `merge` call within `ConfigParser`, `this._config`, looks like

```.js
...
capabilities:
   [ { maxInstances: 5,
       browserName: 'chrome',
       chromeOptions: [<Long Base64 Encoded Crx String>] } ] }
...
```
and `this._capabilities` still looks like

```.js
[ { maxInstances: 5, browserName: 'chrome' } ]
```

This is my interpretation of the issue, but let me know if there's something else you think that could be happening.

## Link to Selenium/WebdriverIO logs

The only proof of this happening is the lack of any chrome extension getting loaded and my tests failing to assert on javascript loaded by the extension.

**Comment by radiovisual** [comment]
@oliverswitzer, are you able to interact with Chrome Extensions that you install via the CRX path?, or are you just testing the actual loading of a specific extension?

**Comment by christian-bromann** [comment]
@radiovisual you can't interact with the popup modal of a Chrome extension with Webdriver. However you should be able to call the popup page directly and open the page in a normal browser window.
