### ISSUE TITLE
setValue() works very slowly with browser internet explorer 11(IE11)

### ISSUE THREAD

**Issue by Windyq** [webdriverio/webdriverio#2113]
## The problem
When I use setValue() to type String, i.e. 90001, it will type 9.....(about 5 seconds) 0.....0.....0.....1 in browser internet explorer 11 . It means to take about 20 seconds to complete this action. 

But it works well in Firefox and Chrome. Please help check.

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 6.9.2
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):

**Comment by christian-bromann** [comment]
This is unfortunately an IE11 issue. There is nothing WebdriverIO can do about it. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by EthanSankin** [comment]
@fogrizovic Any idea how one would specify the driver version to be 32-bit when using selenium-standalone-service?
