### ISSUE TITLE
browser.getUrl() Returning { state: 'pending' } or undefined 

### ISSUE THREAD

**Issue by Andrea-borg** [webdriverio/webdriverio#2114]
## The problem

I'm trying to create a test (with Mocha) which connects to a postgres database. I managed to connect to the database, and also returns the desired output. The problem I'm facing is that I would like to query the database by using browser.getUrl() - as one of my columns in the database is the URL i'm performing the test on. e.g. http://google.com. Unfortunately when when adding browser.getUrl() in the query it returns { state: 'pending' }. Any idea why? Code below

P.s. using phantomJS 

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 7.10.0
* if wdio testrunner, running synchronous or asynchronous tests: synchronous

## Code To Reproduce Issue [ Good To Have ]

 var pg = require('pg');

 var generateTest = function() {

    var conString = "postgres://username:password@localhost:5432/postgres";

    var client = new pg.Client(conString);

    client.connect();

    var currentUrl = browser.getUrl();
    
 //does not work 
    var query = client.query("SELECT * FROM public.credentials WHERE site = '"+currentUrl+"'");
 //works
 //var query = client.query("SELECT * FROM public.credentials WHERE site = 'http://google.com'");

    var user;
    var pass;

    query.on('row', function (row) {

        user = row.user;
        pass = row.pass;

    });

    query.on('end', function () {
        client.end();
    });

    var generateUser = function () {
       return user;
    };

    var generatePass = function () {
        return pass;
    };

    return {
        generateUser: generateUser,
        generatePass: generatePass
    };
};

 module.exports = new generateTest();

**Comment by christian-bromann** [comment]
@Andrea-borg you are using the standalone mode where all commands return a promise. So to get the url you need to do:
```js
browser.getUrl().then(function (url) {
    console.log(url);
});
```
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by andreaborgraketech** [comment]
yes that did the trick, Thank you!
