### ISSUE TITLE
Can't loop through elements and click

### ISSUE THREAD

**Issue by viennv1709** [webdriverio/webdriverio#2115]
I have a script like this:
```javascript
let webdriverio = require('webdriverio');
let options = {
    desiredCapabilities: {
        browserName: 'chrome'
    }
};
let clicks = [];
let browser = webdriverio.remote(options);
browser
    .init()
    .url('https://www.google.com/')
    .setValue('input[name="q"]', 'alphago')
    .click('button[name="btnG"]')
    .pause(5000)
    .elements('.g a')
    .then(result => {
        result.value.forEach(element => {
            browser
                .elementIdClick(element.ELEMENT)
                .back();
        });
    });
```
I can't open all links in that page. Although I tried all ways from https://github.com/webdriverio/webdriverio/issues/1043 issue

**Comment by christian-bromann** [comment]
You need to make sure to respect the returned promise each time you call click. Something like this might work:
```js
browser
    .init()
    .url('https://www.google.com/')
    .setValue('input[name="q"]', 'alphago')
    .click('button[name="btnG"]')
    .pause(5000)
    .elements('.g a')
    .then(result => {
        result.value.forEach(element => {
            browser = browser
                .elementIdClick(element.ELEMENT)
                .back();
        });
    });
```
I would recommend to switch over to the wdio testrunner where all commands are synchronous. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
