### ISSUE TITLE
Chaining on $$ result doesn't work

### ISSUE THREAD

**Issue by OliverJAsh** [webdriverio/webdriverio#2118]
v4.8.0

```
> browser.$$('div').then(x => x[0].$('a'))
TypeError: x[0].$ is not a function
```

This should work, because `x[0]` is an element:

```
>  browser.$$('div').then(console.log)
[ { ELEMENT: '15',
    'element-6066-11e4-a52e-4f735466cecf': '15',
    value: { ELEMENT: '15' },
    selector: 'div',
    index: 0 },
  { ELEMENT: '16',
    'element-6066-11e4-a52e-4f735466cecf': '16',
    value: { ELEMENT: '16' },
    selector: 'div',
    index: 1 },
```

I would expect this to work as per the docs? http://webdriver.io/api/utility/$$.html

**Comment by christian-bromann** [comment]
This only works when using wdio testrunner. Then you can do stuff like:

```js
var x = browser.$$('div');
x[0].$('a').click();
```

If you use standalone mode you will need to use the protocol commands to do that:
```js
browser.$$('div').then(x => browser.elementIdElement(x[0].ELEMENT, 'a'))
```

**Comment by OliverJAsh** [comment]
Thanks @christian-bromann. Is there any way to get an element by ID without passing a child selector? I just want `x[0].ELEMENT`.

**Comment by OliverJAsh** [comment]
> This only works when using wdio testrunner

Can we update the docs to mention this?

**Comment by christian-bromann** [comment]
> Can we update the docs to mention this?

It is already mentioned [here](http://webdriver.io/api.html#Examples):

> Each command documentation usually comes with an example that demonstrates the usage of it using WebdriverIO’s testrunner running its commands synchronously. 

> Is there any way to get an element by ID without passing a child selector? I just want x[0].ELEMENT.

What do you mean by that?

**Comment by OliverJAsh** [comment]
That section of the docs mentions how commands run synchronously with the test runner and return promises in standalone mode, but I don't see any mention of the behaviour above? (The fact that, in standalone mode, elements returned by `$$` are not automatically "wrapped".)

> Is there any way to get an element by ID without passing a child selector? I just want x[0].ELEMENT.

Is something like this possible?

``` js
browser.$$('div').then(x => x.map(browser.getElementById))
// => Promise<Array<Element>>
```

`elementIdElement` runs a query selector against the element ID, but in my case, I just want to get the "wrapped" element associated with an ID, so I can run further commands on it:

``` js
browser.$$('div').then(x => (
  x
    .map(browser.getElementById)
    .map(el => el.getAttribute('foo'))
))
```

**Comment by christian-bromann** [comment]
All element responses in standalone mode aren't wrapped. You will have to use the protocol command as mentioned above:

```js
browser.$$('div').then(x => (
  x.map(el => el.elementIdAttrubute(el.ELEMENT, 'foo'))
))
```

Note that all getXXX commands automatically return an array of results if your selector matches multiple elements, so in the example above you might just use:

```js
browser.getAttribute('div', 'foo').then((attrs) => console.log(attrs))
```

> The fact that, in standalone mode, elements returned by $$ are not automatically "wrapped".

Yes, this is actually missing. Feel free to open up a PR. Thanks

**Comment by OliverJAsh** [comment]
> You will have to use the protocol command as mentioned above:

I have a function that expects to receive a "wrapped" element and will return an attribute via `getAttribute`.

However, I can't compose this unless I have a "wrapped" element. I would need to wrap it first, but there doesn't seem to be a function that does that (and only that)?

E.g.

``` js
const getFooAttr = el => el.getAttribute('foo')

browser.$$('div').then(x => (
  x
    .map(wrapEl)
    .map(getFooAttr)
))
```

I saw there were a set of accessor functions for usage with element ID, but it would be easier to compose if you could wrap the element and then use the normal accessor functions.

**Comment by christian-bromann** [comment]
@OliverJAsh why not just use wdio testrunner where this works out of the box? I haven't planned to give the core webdriverio package a big footprint with extra syntax features. Implementing this will be definitely not an easy task.

**Comment by OliverJAsh** [comment]
I am using wdio to run a script instead of for running tests. I initially used the test runner and put everything inside an `it` function, but that felt hacky.

I am using the new async/await syntax which provides almost exactly the same syntax as wdio-sync.

**Comment by christian-bromann** [comment]
> almost exactly the same syntax as wdio-sync

Here is the glitch .. almost exactly .. the stuff you asking for is only available with wdio-sync. Why not just using it and also getting rid of all `await` in your code. Win Win 😉

**Comment by OliverJAsh** [comment]
If there was a way to use it without a test framework, I would, but I can't seem to find any documentation on this?

I don't want to use the test runner for something that is not a test.

**Comment by christian-bromann** [comment]
> I don't want to use the test runner for something that is not a test.

I see what you mean, I think it is still worth going that way if you don't want to make yourself too much work.

> I would, but I can't seem to find any documentation on this?

If you use the wdioSync method and wrap the commands manually, you probably could end up using standalone without a test framework. I don't have any docs for that tho

**Comment by OliverJAsh** [comment]
Is it worth opening a separate issue to track the doc updates we discussed? In addition to mentioning the difference in control flow when using WebdriverIO standalone, the docs should make it clear that using it standalone will not "wrap" elements returned by commands.

It would be great if WebdriverIO could be used standalone with async functions (`async`/`await`) in exactly the same way it can be used inside the test runner via wdio-sync. I think it's quite confusing that there is more difference in behaviour other than control flow.

I'm having success using async functions with the official WebDriverJs client: https://github.com/OliverJAsh/webdriverjs-chrome-headless/blob/554ea2f150e962257119703c2473753b90842087/src/index.ts#L23

**Comment by christian-bromann** [comment]
> Is it worth opening a separate issue to track the doc updates we discussed?

Better would be a PR 😉 

> It would be great if WebdriverIO could be used standalone with async functions (async/await) in exactly the same way it can be used inside the test runner via wdio-sync.

Unfortunately this is not so easy. It would be definitely nice if we could streamline the syntax for async/sync mode.

> I'm having success using async functions with the official WebDriverJs client:

Sure thing! There is also no issue with using async functions with WebdriverIO it is just that the syntax is a bit different than with the wdio testrunner. If WebdriverJS suites your expectations better, feel free to choose that.

**Comment by christian-bromann** [comment]
I think everything was discussed here.
