### ISSUE TITLE
browser.keys() does not trigger on certain points in code

### ISSUE THREAD

**Issue by DanielGJohnsen** [webdriverio/webdriverio#2119]
browser.keys(), specific for paging ('PageDown'/'PageUp'), sometimes does not trigger. I have tested it after browser.setValue() and it always trigger,
but directly after a browser.selectVisibleText() it never triggers. And after creating for example an array from browser.getText(), browser.keys() does not trigger. I unfortunately have no logs to show a error message as the action seemingly is just skipped. I am guessing this has to do with page focus?

**Comment by christian-bromann** [comment]
> I am guessing this has to do with page focus?

No idea but all I can say is that this would not be an issue of WebdriverIO. It sends the commands as desired to the browser. If the driver does not trigger the action it is most likely an issue of the browser driver. There is nothing we can do on the WebdriverIO side to fix this.
