### ISSUE TITLE
PushFile not working for the push image to mobile gallery scenario.

### ISSUE THREAD

**Issue by JaspreetBamrah** [webdriverio/webdriverio#2123]
I am trying to push an image to android phone gallery for real and simulator device. But the function pushFile doesn't seem to be working. 
Do we have another function for this purpose?

```
 data = new Buffer('Hello World').toString('base64');
browser.pushFile('//Desktop/Document1.txt', data);
```

## Environment
1. appium -v. 1.6.4
2. npm -v 4.2.0
3. node -v v7.10.0
4. java version "1.8.0_131"

Is there any other way to push images to Android emulators?

**Comment by christian-bromann** [comment]
Can you provide logs?

**Comment by JaspreetBamrah** [comment]
Here is my code and attaching logs (i dint find any particular error thats indicates that why the image wasnt uploaded to emulator). Am I missing out on anything??
Code:
describe('Go to upload image', () => {
  let data;
  beforeAll(() => {
    console.log('here in save image..------');
  });
  it('save image'), () => {
    console.log('---get image---');
    data = new Buffer('Hello World').toString('base64');
    browser.pushFile('/Users/jaspreet/Desktop/poppeye.jpg', data);
 };
 
});
Logs::

[ADB] Application '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-unlock/bin/unlock_apk-debug.apk' already installed. Continuing.
[ADB] Device API level: 24
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","appops","set","io.appium.settings","android:mock_location","allow"]
[ADB] Getting device platform version
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.build.version.release"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","wm","size"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.product.model"]
[ADB] Current device property 'ro.product.model': Android SDK built for x86
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.product.manufacturer"]
[ADB] Current device property 'ro.product.manufacturer': unknown
[AndroidDriver] Parsing package and activity from app manifest
[ADB] Checking whether aapt is present
[ADB] Using aapt from /usr/local/Caskroom/android-sdk/25.2.3/build-tools/25.0.2/aapt
[ADB] Extracting package and launch activity from manifest
[ADB] badging package: com.hip.tradie.android
[ADB] badging act: com.hip.tradie.android.ui.SplashActivity
[AndroidDriver] Parsed package and activity are: com.hip.tradie.android/com.hip.tradie.android.ui.SplashActivity
[AndroidDriver] Remote apk path is /data/local/tmp/78169be57aec9acd765bb3f4993a0160.apk
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","ls","/data/local/tmp/78169be57aec9acd765bb3f4993a0160.apk"]
[AndroidDriver] Checking if app is installed
[ADB] Getting install status for com.hip.tradie.android
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","pm","list","packages","com.hip.tradie.android"]
[ADB] App is installed
[AndroidDriver] Apk is already on remote and installed, resetting
[AndroidDriver] Running fast reset (stop and clear)
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","com.hip.tradie.android"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","pm","clear","com.hip.tradie.android"]
[ADB] Device API level: 24
[ADB] Checking whether aapt is present
[ADB] Using aapt from /usr/local/Caskroom/android-sdk/25.2.3/build-tools/25.0.2/aapt
[ADB] Extracting package and launch activity from manifest
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","pm","dump","com.hip.tradie.android"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","pm","grant","com.hip.tradie.android","android.permission.READ_EXTERNAL_STORAGE",";","pm","grant","com.hip.tradie.android","android.permission.WRITE_EXTERNAL_STORAGE",";","pm","grant","com.hip.tradie.android","android.permission.GET_ACCOUNTS",";"]
[AndroidDriver] Extracting strings from apk /Users/jaspreet/Desktop/Jazz/Official/tests-mobile/tradie/tradie.apk undefined /var/folders/m9/7sln_v1n40z3z1p7kb9_flyc0000gp/T/com.hip.tradie.android
[ADB] Extracting strings for language: default
[ADB] Device API level: 24
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","persist.sys.locale"]
[ADB] Current device property 'persist.sys.locale': 
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.product.locale"]
[ADB] Current device property 'ro.product.locale': en-US
[ADB] No strings.xml for language 'en', getting default strings.xml
[ADB] Reading strings from converted strings.json
[ADB] Running '/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","push","/var/folders/m9/7sln_v1n40z3z1p7kb9_flyc0000gp/T/com.hip.tradie.android/strings.json","/data/local/tmp"]
[AndroidBootstrap] Watching for bootstrap disconnect
[ADB] Forwarding system: 4724 to device: 4724
[ADB] Running '/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","forward","tcp:4724","tcp:4724"]
[UiAutomator] Starting UiAutomator
[UiAutomator] Moving to state 'starting'
[UiAutomator] Parsing uiautomator jar
[UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[ADB] Running '/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","push","/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-bootstrap/bootstrap/bin/AppiumBootstrap.jar","/data/local/tmp/"]
[ADB] Attempting to kill all uiautomator processes
[ADB] Getting all processes with uiautomator
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","ps"]
[ADB] No uiautomator process found to kill, continuing...
[UiAutomator] Starting UIAutomator
[ADB] Creating ADB subprocess with args: ["-P",5037,"-s","emulator-5554","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","com.hip.tradie.android","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false]
[UiAutomator] Moving to state 'online'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] json loading complete.
[AndroidBootstrap] Android bootstrap socket is now connected
[ADB] Getting connected devices...
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","dumpsys","window"]
[AndroidDriver] Screen already unlocked, doing nothing
[ADB] Device API level: 24
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","am","start","-W","-n","com.hip.tradie.android/com.hip.tradie.android.ui.SplashActivity","-S"]
[ADB] Waiting for pkg: 'com.hip.tradie.android' and activity: 'com.hip.tradie.android.ui.SplashActivity' to be focused
[ADB] Possible activities, to be checked: com.hip.tradie.android.ui.SplashActivity, com.hip.tradie.android.com.hip.tradie.android.ui.SplashActivity
[ADB] Getting focused package and activity
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","dumpsys","window","windows"]
[ADB] Found package: 'com.hip.tradie.android' and fully qualified activity name : 'com.hip.tradie.android.ui.SplashActivity'
[Appium] New AndroidDriver session created successfully, session 1268ffda-456e-42cf-bab6-a90c7c58a32c added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1496379258421 (14:54:18 GMT+1000 (AEST))
[MJSONWP] Responding to client with driver.createSession() result: {"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":true,"warnings":{},"desired":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"android","platformName":"android","deviceName":"android","autoGrantPermissions":true,"app":"/Users/jaspreet/Desktop/Jazz/Official/tests-mobile/tradie/tradie.apk","requestOrigins":{"url":"http://webdriver.io","version":"4.6.2","name":"webdriverio"}},"handlesAlerts":true,"rotatable":true,"browserName":"android","platformName":"android","deviceName":"emulator-5554","autoGrantPermissions":true,"app":"/Users/jaspreet/Desktop/Jazz/Official/tests-mobile/tradie/tradie.apk","requestOrigins":{"url":"http://webdriver.io","version":"4.6.2","name":"webdriverio"},"deviceUDID":"emulator-5554","platformVersion":"7.0","deviceScreenSize":"1440x2560","deviceModel":"Android SDK built for x86","deviceManufacturer":"unkn...
[HTTP] <-- POST /wd/hub/session 200 9635 ms - 1296 
[HTTP] --> POST /wd/hub/session/1268ffda-456e-42cf-bab6-a90c7c58a32c/elements {"using":"id","value":"imageView2"}
[MJSONWP] Calling AppiumDriver.findElements() with args: ["id","imageView2","1268ffda-456e-42cf-bab6-a90c7c58a32c"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 0 ms for condition
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"imageView2","context":"","multiple":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"imageView2","context":"","multiple":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'imageView2' using 'ID' with the contextId: '' multiple: true
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[RESOURCE_ID=com.hip.tradie.android:id/imageView2]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[RESOURCE_ID=com.hip.tradie.android:id/imageView2]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (0)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[INSTANCE=0, RESOURCE_ID=com.hip.tradie.android:id/imageView2]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[RESOURCE_ID=android:id/imageView2]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[RESOURCE_ID=android:id/imageView2]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (0)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[INSTANCE=0, RESOURCE_ID=android:id/imageView2]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[RESOURCE_ID=imageView2]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[RESOURCE_ID=imageView2]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (0)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[INSTANCE=0, RESOURCE_ID=imageView2]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[DESCRIPTION=imageView2]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[DESCRIPTION=imageView2]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (0)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[DESCRIPTION=imageView2, INSTANCE=0]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Failed to locate element. Clearing Accessibility cache and retrying.
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'imageView2' using 'ID' with the contextId: '' multiple: true
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[RESOURCE_ID=com.hip.tradie.android:id/imageView2]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[RESOURCE_ID=com.hip.tradie.android:id/imageView2]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (0)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[INSTANCE=0, RESOURCE_ID=com.hip.tradie.android:id/imageView2]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[RESOURCE_ID=android:id/imageView2]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[RESOURCE_ID=android:id/imageView2]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (0)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[INSTANCE=0, RESOURCE_ID=android:id/imageView2]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[RESOURCE_ID=imageView2]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[RESOURCE_ID=imageView2]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (0)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[INSTANCE=0, RESOURCE_ID=imageView2]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[DESCRIPTION=imageView2]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[DESCRIPTION=imageView2]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (0)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[DESCRIPTION=imageView2, INSTANCE=0]
[AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.findElements() result: []
[HTTP] <-- POST /wd/hub/session/1268ffda-456e-42cf-bab6-a90c7c58a32c/elements 200 1462 ms - 74 
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":[]}
[HTTP] --> POST /wd/hub/session/1268ffda-456e-42cf-bab6-a90c7c58a32c/elements {"using":"id","value":"login_txbEmail"}
[MJSONWP] Calling AppiumDriver.findElements() with args: ["id","login_txbEmail","1268ffda-456e-42cf-bab6-a90c7c58a32c"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 0 ms for condition
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"login_txbEmail","context":"","multiple":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"login_txbEmail","context":"","multiple":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'login_txbEmail' using 'ID' with the contextId: '' multiple: true
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[RESOURCE_ID=com.hip.tradie.android:id/login_txbEmail]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[RESOURCE_ID=com.hip.tradie.android:id/login_txbEmail]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (0)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[INSTANCE=0, RESOURCE_ID=com.hip.tradie.android:id/login_txbEmail]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[RESOURCE_ID=android:id/login_txbEmail]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[RESOURCE_ID=android:id/login_txbEmail]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (0)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[INSTANCE=0, RESOURCE_ID=android:id/login_txbEmail]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[RESOURCE_ID=login_txbEmail]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[RESOURCE_ID=login_txbEmail]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (0)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[INSTANCE=0, RESOURCE_ID=login_txbEmail]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[DESCRIPTION=login_txbEmail]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[DESCRIPTION=login_txbEmail]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (0)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[DESCRIPTION=login_txbEmail, INSTANCE=0]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Failed to locate element. Clearing Accessibility cache and retrying.
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'login_txbEmail' using 'ID' with the contextId: '' multiple: true
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[RESOURCE_ID=com.hip.tradie.android:id/login_txbEmail]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[RESOURCE_ID=com.hip.tradie.android:id/login_txbEmail]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (0)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[INSTANCE=0, RESOURCE_ID=com.hip.tradie.android:id/login_txbEmail]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[RESOURCE_ID=android:id/login_txbEmail]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[RESOURCE_ID=android:id/login_txbEmail]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (0)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[INSTANCE=0, RESOURCE_ID=android:id/login_txbEmail]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[RESOURCE_ID=login_txbEmail]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[RESOURCE_ID=login_txbEmail]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (0)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[INSTANCE=0, RESOURCE_ID=login_txbEmail]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[DESCRIPTION=login_txbEmail]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[DESCRIPTION=login_txbEmail]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (0)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[DESCRIPTION=login_txbEmail, INSTANCE=0]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":[]}
[AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.findElements() result: []
[HTTP] <-- POST /wd/hub/session/1268ffda-456e-42cf-bab6-a90c7c58a32c/elements 200 589 ms - 74 
[HTTP] --> DELETE /wd/hub/session/1268ffda-456e-42cf-bab6-a90c7c58a32c {}
[MJSONWP] Calling AppiumDriver.deleteSession() with args: ["1268ffda-456e-42cf-bab6-a90c7c58a32c"]
[BaseDriver] Event 'quitSessionRequested' logged at 1496379260835 (14:54:20 GMT+1000 (AEST))
[AndroidDriver] Shutting down Android driver
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","com.hip.tradie.android"]
[ADB] Pressing the HOME button
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","input","keyevent",3]
[AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[AndroidBootstrap] Received command result from bootstrap
[UiAutomator] Shutting down UiAutomator
[UiAutomator] Moving to state 'stopping'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Closed client connection
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: numtests=1
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=.
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: current=1
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: 0
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=
[AndroidBootstrap] [UIAUTO STDOUT] Test results for WatcherResultPrinter=.
[AndroidBootstrap] [UIAUTO STDOUT] Time: 8.236
[AndroidBootstrap] [UIAUTO STDOUT] OK (1 test)
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: -1
[UiAutomator] UiAutomator shut down normally
[UiAutomator] Moving to state 'stopped'
[ADB] Attempting to kill all uiautomator processes
[ADB] Getting all processes with uiautomator
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","ps"]
[ADB] No uiautomator process found to kill, continuing...
[UiAutomator] Moving to state 'stopped'
[Logcat] Stopping logcat capture
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","io.appium.unlock"]
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[Appium] Removing session 1268ffda-456e-42cf-bab6-a90c7c58a32c from our master session list
[BaseDriver] Event 'quitSessionFinished' logged at 1496379264542 (14:54:24 GMT+1000 (AEST))
[MJSONWP] Received response: null
[MJSONWP] But deleting session, so not returning
[MJSONWP] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/1268ffda-456e-42cf-bab6-a90c7c58a32c 200 3711 ms - 76

**Comment by christian-bromann** [comment]
@JaspreetBamrah after looking into Appium it looks like this command is not supported for the driver. Since it is not part of the W3C WebDriver protocol I am afraid it never will. Therefor this can't be fixed in WebdriverIO until there is support for it on Appium.
