### ISSUE TITLE
isVisibleWithinViewport() return false even when visible

### ISSUE THREAD

**Issue by mechtateliat** [webdriverio/webdriverio#2124]
## The problem

Hi guys, i'm trying to use IsVisibleWithinViewport() to verify if an element is currently visible. I have problems with it regarding it not always returns the correct value. Here is an example when it return false for element which is currently visible. I had issues with it also returning true when the element is not visible currently.

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 6.10.3
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):

    "wdio-cucumber-framework": "^0.2.16",
    "wdio-selenium-standalone-service": "0.0.8",
    "wdio-spec-reporter": "^0.1.0",

## Details

No more details than in the description.

## Link to Selenium/WebdriverIO logs

Here is the gist - https://gist.github.com/mechtateliat/2cb6d5a89bbd26599983f5053e65a709 

## Code To Reproduce Issue [ Good To Have ]

```javascript
browser.url("https://www.google.com/?gws_rd=ssl#q=test");
browser.waitForVisible('img[alt=Google]');
console.log("Before scroll isVisibleWithinViewport is: " + browser.element('img[alt=Google]').isVisibleWithinViewport());
console.log("Before scroll isVisible is: " + browser.element('img[alt=Google]').isVisible());
browser.scroll(0, 2000);
console.log("After scroll isVisibleWithinViewport is " + browser.element('img[alt=Google]').isVisibleWithinViewport());
console.log("After scroll isVisible is: " + browser.element('img[alt=Google]').isVisible());
```

**Comment by christian-bromann** [comment]
This is related to #1758. `waitForVisible` might not work in some cases. I would just use isVisible.
