### ISSUE TITLE
webdriverio website add chromedriver documentation

### ISSUE THREAD

**Issue by rahulmr** [webdriverio/webdriverio#2125]
Docs related

On webdriver.io under Developer Guide > Services , please add ChromeDriver (directConnect true).

It's a great implementation and working fine for me.
I see that the [chromedriver.md][1] file is available in the repository but somehow it is not shown.
Also, I see that there is one more file `webpack-dev-server` not sure how it fits into the doc but I feel the extension should be `.md`

[1]: https://github.com/webdriverio/webdriverio/blob/master/docs/guide/services/chromedriver.md

**Comment by christian-bromann** [comment]
Fixed suffix of docs file. The chromedriver doc will be deploy with the next release.

**Comment by rahulmr** [comment]
@christian-bromann great work. Thanks!
