### ISSUE TITLE
Could not find any action command for element when only class is available

### ISSUE THREAD

**Issue by ibrahimkhaleel** [webdriverio/webdriverio#2127]
## The problem

Hi,
 
I have some elements like below:
```html
<div class="com-theme-light-client-base-grid-Css3GridAppearance-GridStyle-cellInner com-sencha-gxt-widget-core-client-grid-GridView-GridStateStyles-cellInner" style="">2017-06-05 06:23:32.248 AM</div>
 
<div class="com-theme-light-client-base-grid-Css3GridAppearance-GridStyle-cellInner com-sencha-gxt-widget-core-client-grid-GridView-GridStateStyles-cellInner" style="">2017-06-05 06:23:32.248 AM</div>
 
<div class="com-theme-light-client-base-grid-Css3GridAppearance-GridStyle-cellInner com-sencha-gxt-widget-core-client-grid-GridView-GridStateStyles-cellInner" style="">2017-06-05 06:23:32.248 AM</div>
```
and so on... and sometimes these elements are hundred in count.
 
I am able to find these each element with following selector respectively:
 
 
'div.com-theme-light-client-base-grid-Css3GridAppearance-GridStyle-scroller.com- ccc-portal-client-resources-css-GeneralCSS-hideScrollBar table > tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(2) > div'
 
'div.com-theme-light-client-base-grid-Css3GridAppearance-GridStyle-scroller.com- ccc-portal-client-resources-css-GeneralCSS-hideScrollBar table > tbody:nth-child(2) > tr:nth-child(2) > td:nth-child(2) > div'
 
'div.com-theme-light-client-base-grid-Css3GridAppearance-GridStyle-scroller.com- ccc-portal-client-resources-css-GeneralCSS-hideScrollBar table > tbody:nth-child(2) > tr:nth-child(3) > td:nth-child(2) > div'
 
Now my problem are:
1. I would like to extract time stamp available in each elements
2. Total number of occurances of elements available
 
The requirement is I need to fetch most recently occured entry from all logs we have in all elements. Since these elements have only class selector I am unable find any option in WDIO commands. Please assist.
 
## Environment

* WebdriverIO version: 4.2.16
* Node.js version: 4.2.4
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable): wdio-cucumber-framework 0.0.6
wdio-spec-reported 0.0.3

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
> I would like to extract time stamp available in each elements

do `browser.getText(".com-theme-light-client-base-grid-Css3GridAppearance-GridStyle-cellInner com-sencha-gxt-widget-core-client-grid-GridView-GridStateStyles-cellInner");` .. it will return a list with all time stamps

> Total number of occurances of elements available

do `$$('.com-theme-light-client-base-grid-Css3GridAppearance-GridStyle-cellInner com-sencha-gxt-widget-core-client-grid-GridView-GridStateStyles-cellInner').length` .. returns the amount of elements

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by ibrahimkhaleel** [comment]
Hi Chris:

Thank you so much for your help on first query.

For following second query I am getting undefined or error (says - TypeError: Cannot read property 'length' of undefined) for this utility.

$$('.com-theme-light-client-base-grid-Css3GridAppearance-GridStyle-cellInner com-sencha-gxt-widget-core-client-grid-GridView-GridStateStyles-cellInner').length 

I am able to inspect element length in chrome console. But not sure what is wrong when I use same selector in code. Please assist further.

**Comment by christian-bromann** [comment]
Can you provide logs?

**Comment by ibrahimkhaleel** [comment]
Hi Chris:

I have not captured logs in webdriverio so far. Can you please let me know the process. However I have read some issues on logs using Log Preferences.
loggingPrefs: {
      'driver': 'INFO',
      'browser': 'INFO'
    }

Is it same procedure I need to follow.

Thank you for your time.

**Comment by christian-bromann** [comment]
I just need WebdriverIO logs which can be captured over stdout. Selenium logs would be great too.

**Comment by ibrahimkhaleel** [comment]
[test.zip](https://github.com/webdriverio/webdriverio/files/1057695/test.zip)
Hi Chris:

I have generated the today's logs  from test fixtures folder and attached the same. Please let me know if logs you have requested are different.

I did not work on Selenium Logs.

Thank you.

**Comment by ibrahimkhaleel** [comment]
[test.zip](https://github.com/webdriverio/webdriverio/files/1057704/test.zip)
Logs

**Comment by ibrahimkhaleel** [comment]
Hi Chris, can you please help me on this issue.
