### ISSUE TITLE
Promise was rejected with the following reason: ERROR The test with session id # has already finished, and can't receive further commands.

### ISSUE THREAD

**Issue by dimirey** [webdriverio/webdriverio#2128]
## The problem

When running a concurrent automation suite through Saucelabs (40 tests in parallel) the tests will intermittently fail. 

> Error: Promise was rejected with the following reason: ERROR The test with session id # has already finished, and can't receive further commands.
>     at Context.it (techwalla/specs_desktop/search_elastic_1.js:35:15)
>     You can learn more at https://saucelabs.com/jobs/#
>     For help, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages
>     at elements("body > main > div > section > div > article > div > h2") - isExisting.js:46:17
>     at isExisting("body > main > div > section > div > article > div > h2") - waitForExist.js:67:22
> Briefly describe the issue you are experiencing (or the feature you want to see added to WebdriverIO). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, join the Gitter chat room ([![Gitter](https://badges.gitter.im/Join Chat.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge))!
> 

## Environment

* WebdriverIO version: 4.8
* Node.js version: 6.9.5
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): WDIO
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):     "wdio-junit-reporter": "0.1.0",
    "wdio-mocha-framework": "0.5.8",
    "wdio-sauce-service": "0.3.1",
    "wdio-spec-reporter": "0.0.4",

## Link to Selenium/WebdriverIO logs

https://gist.github.com/dimirey/97d3c74bde4f483efe55e17abdcbf2b6

## Code To Reproduce Issue [ Good To Have ]

Will provide when needed

**Comment by christian-bromann** [comment]
@dimirey can you provide a reproducible example?

**Comment by dimirey** [comment]
@christian-bromann sure, give me a few moments

**Comment by dimirey** [comment]
@christian-bromann here is a link to download our framework: https://www.dropbox.com/s/tdxfd5f2k717vjk/wdio-automation.zip?dl=0

thank you for your help!

**Comment by christian-bromann** [comment]
@dimirey wow, how am I suppose to find the bug in there 😆 ? You seem to query the element `body > main > div > section > div > article > div > h2` at a point where you already closed the session. Don't call any browser commands once your spec is done. Can you check that?

**Comment by dimirey** [comment]
@christian-bromann heh, sorry about that. I can't seem to reproduce the bug without running the entire suite against saucelabs. 

The query is actually made _before_ the session is expected to be closed:

`const expect = require('chai').expect;
const _ = require('lodash');

const homepage = require('../pages/homepage');
const searchpage = require('../pages/searchpage');
const header = require('../page_objects/header');
let title;

if (!_.isEqual(browser.desiredCapabilities.browserName, 'safari')) {

  describe('Elastic Search Article results page Test ', function() {

    this.retries(3);

    before(()=> {
      homepage.open('/');
      var titles = homepage.article_title.getText();
      title = _.sample(titles);
      header.search_btn.waitForExist();
      header.search_btn.click();

      if(!header.search_box.isVisible()) {
        browser.pause(2000);
        header.search_btn.click();
        browser.pause(2000);
      }

      header.search_box.waitForVisible();
      header.search_box.setValue(title);
      header.articles_btn.waitForVisible();
      header.articles_btn.click();
    });

    it('should check if the search term is present in the results', ()=> {
      browser.waitForExist('body > main > div > section > div > article > div > h2');
      browser.waitForVisible('body > main > div > section > div > article > div > h2');
      // searchpage.article_title.waitForVisible();
      let results = searchpage.article_title.getText();
      expect(results).to.include(title);
    });
  });
}
`

**Comment by christian-bromann** [comment]
Do you see the error if you skip the complete spec?

**Comment by dimirey** [comment]
When the search_elastic_1.js spec is skipped we will not get an error for THAT spec. Chances are we will get the same error with another spec.

**Comment by dimirey** [comment]
Here's the error of another spec encountering the same issue:

> Error: Promise was rejected with the following reason: ERROR The test with session id d5d3843095444c27829308f089c7b722 has already finished, and can't receive further commands.
    at Context.it (techwalla/specs/homepage_3.js:24:15)
    You can learn more at https://saucelabs.com/jobs/d5d3843095444c27829308f089c7b722
    For help, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages
    at elements("body > main > div.container > section > div > article > a > img") - isExisting.js:46:17
    at isExisting("body > main > div.container > section > div > article > a > img") - waitForExist.js:67:22

**Comment by christian-bromann** [comment]
Something shuts down your session for some reason. The you still try to run a command which fails with that error.

**Comment by dimirey** [comment]
We spoke with saucelabs customer support and they suggested we used a browser.close command in the afterTest hook (which did not resolve the issue.) What could be shutting down the session on our end?

**Comment by christian-bromann** [comment]
> What could be shutting down the session on our end?

Please look at the logs

**Comment by dimirey** [comment]
> [15:11:23]  COMMAND	POST 	 "/wd/hub/session"
> [15:11:23]  DATA		{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"chrome","platform":"macOS 10.12","screenResolution":"1600x1200","specs":["/Users/dimitrireynaga/git/vertical-wdio-automation/techwalla/specs_desktop/search_elastic_1.js"],"tunnelIdentifier":"dimitri","loggingPrefs":{"browser":"ALL","driver":"ALL"},"_":"1 more keys: [\"requestOrigins\"]"}}
> [15:11:33]  INFO	SET SESSION ID d82e578cb6374ae28d65e902555093e2
> [15:11:33]  RESULT		{"takesScreenshot":true,"acceptSslCerts":true,"networkConnectionEnabled":false,"mobileEmulationEnabled":false,"unexpectedAlertBehaviour":"","applicationCacheEnabled":false,"locationContextEnabled":true,"rotatable":false,"chrome":{"chromedriverVersion":"2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b)","userDataDir":"/var/folders/kv/dj72kn8n4nqcfd8yghq2qh1h0000kr/T/.org.chromium.Chromium.ZXQEFC"},"hasTouchScreen":false,"platform":"Mac OS X","version":"58.0.3029.81","nativeEvents":true,"handlesAlerts":true,"takesHeapSnapshot":true,"javascriptEnabled":true,"databaseEnabled":false,"webdriver.remote.sessionid":"d82e578cb6374ae28d65e902555093e2","browserName":"chrome","hasMetadata":true,"webStorageEnabled":true,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"pageLoadStrategy":"normal"}
> [15:11:33]  COMMAND	POST 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/url"
> [15:11:33]  DATA		{"url":"https://www.techwalla.com/"}
> [15:11:38]  COMMAND	POST 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/cookie"
> [15:11:38]  DATA		{"cookie":{"name":"dmtestauto","value":"true","path":"/"}}
> [15:11:39]  COMMAND	POST 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/execute"
> [15:11:39]  DATA		{"script":"if (typeof $ !== 'undefined') {$('#email-capture').removeClass('fade');$('body > div.modal-backdrop').removeClass('fade');$('#email-capture').modal('hide');$('#email-capture').remove();$('body > div.modal-backdrop').remove();}","args":[]}
> [15:11:39]  COMMAND	POST 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/elements"
> [15:11:39]  DATA		{"using":"css selector","value":"body > main > div.container > section > div > article > div > h2 > a"}
> [15:11:39]  RESULT		[{"ELEMENT":"0.5402966943416811-1"},{"ELEMENT":"0.5402966943416811-2"},{"ELEMENT":"0.5402966943416811-3"},{"ELEMENT":"0.5402966943416811-4"},{"ELEMENT":"0.5402966943416811-5"},{"ELEMENT":"0.5402966943416811-6"},{"ELEMENT":"0.5402966943416811-7"},{"ELEMENT":"0.5402966943416811-8"},{"ELEMENT":"0.5402966943416811-9"},{"ELEMENT":"0.5402966943416811-10"},{"ELEMENT":"0.5402966943416811-11"},{"ELEMENT":"0.5402966943416811-12"},{"ELEMENT":"0.5402966943416811-13"},{"ELEMENT":"0.5402966943416811-14"},{"ELEMENT":"0.5402966943416811-15"},{"ELEMENT":"0.5402966943416811-16"},{"ELEMENT":"0.5402966943416811-17"},{"ELEMENT":"0.5402966943416811-18"},{"ELEMENT":"0.5402966943416811-19"},{"ELEMENT":"0.5402966943416811-20"},{"ELEMENT":"0.5402966943416811-21"},{"ELEMENT":"0.5402966943416811-22"},{"ELEMENT":"0.5402966943416811-23"},{"ELEMENT":"0.5402966943416811-24"}]
> [15:11:39]  COMMAND	GET 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/element/0.5402966943416811-1/text"
> [15:11:39]  DATA		{}
> [15:11:39]  COMMAND	GET 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/element/0.5402966943416811-2/text"
> [15:11:39]  DATA		{}
> [15:11:39]  COMMAND	GET 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/element/0.5402966943416811-3/text"
> [15:11:39]  DATA		{}
> [15:11:39]  COMMAND	GET 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/element/0.5402966943416811-4/text"
> [15:11:39]  DATA		{}
> [15:11:39]  COMMAND	GET 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/element/0.5402966943416811-5/text"
> [15:11:39]  DATA		{}
> [15:11:39]  COMMAND	GET 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/element/0.5402966943416811-6/text"
> [15:11:39]  DATA		{}
> [15:11:39]  COMMAND	GET 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/element/0.5402966943416811-7/text"
> [15:11:39]  DATA		{}
> [15:11:39]  COMMAND	GET 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/element/0.5402966943416811-8/text"
> [15:11:39]  DATA		{}
> [15:11:39]  COMMAND	GET 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/element/0.5402966943416811-9/text"
> [15:11:39]  DATA		{}
> [15:11:39]  COMMAND	GET 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/element/0.5402966943416811-10/text"
> [15:11:39]  DATA		{}
> [15:11:39]  COMMAND	GET 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/element/0.5402966943416811-11/text"
> [15:11:39]  DATA		{}
> [15:11:39]  COMMAND	GET 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/element/0.5402966943416811-12/text"
> [15:11:39]  DATA		{}
> [15:11:39]  COMMAND	GET 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/element/0.5402966943416811-13/text"
> [15:11:39]  DATA		{}
> [15:11:39]  COMMAND	GET 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/element/0.5402966943416811-14/text"
> [15:11:39]  DATA		{}
> [15:11:39]  COMMAND	GET 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/element/0.5402966943416811-15/text"
> [15:11:39]  DATA		{}
> [15:11:39]  COMMAND	GET 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/element/0.5402966943416811-16/text"
> [15:11:39]  DATA		{}
> [15:11:39]  COMMAND	GET 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/element/0.5402966943416811-17/text"
> [15:11:39]  DATA		{}
> [15:11:39]  COMMAND	GET 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/element/0.5402966943416811-18/text"
> [15:11:39]  DATA		{}
> [15:11:39]  COMMAND	GET 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/element/0.5402966943416811-19/text"
> [15:11:39]  DATA		{}
> [15:11:39]  COMMAND	GET 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/element/0.5402966943416811-20/text"
> [15:11:39]  DATA		{}
> [15:11:39]  COMMAND	GET 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/element/0.5402966943416811-21/text"
> [15:11:39]  DATA		{}
> [15:11:39]  COMMAND	GET 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/element/0.5402966943416811-22/text"
> [15:11:39]  DATA		{}
> [15:11:39]  COMMAND	GET 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/element/0.5402966943416811-23/text"
> [15:11:39]  DATA		{}
> [15:11:39]  COMMAND	GET 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2/element/0.5402966943416811-24/text"
> [15:11:39]  DATA		{}
> [15:11:40]  RESULT		"Amazon Offers Prime Memberships at a Discount for Low-Income Customers"
> [15:11:40]  RESULT		"Wedding Planning Apps that Make the Planning Process Easier"
> [15:11:40]  RESULT		"5 Ways Your Kids Might Be Using Technology to Cheat"
> [15:11:40]  RESULT		"Get Your Exercise on at Home With These Intense Workout DVDs"
> [15:11:40]  RESULT		"Everything Coming to Netflix in June"
> [15:11:40]  RESULT		"White Noise Apps Are the New Ear Plugs"
> [15:11:40]  RESULT		"Home Search Apps to Help Make Finding Your New Home Easier"
> [15:11:40]  RESULT		"Can't Sleep? Try One of These Relaxing Gadgets"
> [15:11:40]  RESULT		"Essential Apps for Parents of Newborns"
> [15:11:40]  RESULT		"Find Love (or a Date) With One of These Top Dating Apps"
> [15:11:40]  RESULT		"Soon You'll Be Able to Buy the Smartest Electric Bike Ever"
> [15:11:40]  RESULT		"Your Dog Can Play Fetch Alone With This Robotic Ball"
> [15:11:40]  RESULT		"In-home Massage Apps You Deserve to Know About"
> [15:11:41]  RESULT		"The Best Digital Thermometers for Your Kids"
> [15:11:41]  RESULT		"Make Learning Fun for Your Toddler With These Apps"
> [15:11:41]  RESULT		"Lady Gaga Has a New Line of Emojis, Yep"
> [15:11:41]  RESULT		"Trick Your Dog Into Taking the Perfect Selfie With This Clever Device"
> [15:11:41]  RESULT		"Start a Meal Train for Your Friends With a Newborn, and They'll Love You Forever"
> [15:11:41]  RESULT		"Download Your DVD Collection to Your Phone With This App"
> [15:11:41]  RESULT		"Apple's iOS 11 Has Finally Been Announced"
> [15:11:42]  RESULT		"Healthy Meal Delivery Services to Make Your Life Easier"
> [15:11:42]  RESULT		"Apple Has a New Wireless Magic Keyboard"
> F[15:13:10]  COMMAND	DELETE 	 "/wd/hub/session/d82e578cb6374ae28d65e902555093e2"
> [15:13:10]  DATA		{}
> ------------------------------------------------------------------
> [chrome  macOS 10.12 #0-0] Session ID: d82e578cb6374ae28d65e902555093e2
> [chrome  macOS 10.12 #0-0] Spec: /Users/dimitrireynaga/git/vertical-wdio-automation/techwalla/specs_desktop/search_elastic_1.js
> [chrome  macOS 10.12 #0-0] Running: chrome on macOS 10.12
> [chrome  macOS 10.12 #0-0]
> [chrome  macOS 10.12 #0-0] Elastic Search Article results page Test
> [chrome  macOS 10.12 #0-0]   1) "before all" hook
> [chrome  macOS 10.12 #0-0]
> [chrome  macOS 10.12 #0-0]
> [chrome  macOS 10.12 #0-0] 1 failing (1m, 47s)
> [chrome  macOS 10.12 #0-0]
> [chrome  macOS 10.12 #0-0] 1) Elastic Search Article results page Test  "before all" hook:
> [chrome  macOS 10.12 #0-0] The test with session id d82e578cb6374ae28d65e902555093e2 has already finished, and can't receive further commands.
> You can learn more at https://saucelabs.com/jobs/d82e578cb6374ae28d65e902555093e2
> For help, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages
> [chrome  macOS 10.12 #0-0] Error: The test with session id d82e578cb6374ae28d65e902555093e2 has already finished, and can't receive further commands.
> [chrome  macOS 10.12 #0-0]     at Context.before (specs_desktop/search_elastic_1.js:17:43)
> [chrome  macOS 10.12 #0-0]     at Promise.F (/Users/dimitrireynaga/.nvm/versions/node/v6.9.5/lib/node_modules/wdio-mocha-framework/node_modules/core-js/library/modules/_export.js:35:28)
> [chrome  macOS 10.12 #0-0]     You can learn more at https://saucelabs.com/jobs/d82e578cb6374ae28d65e902555093e2
> [chrome  macOS 10.12 #0-0]     For help, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages
> [chrome  macOS 10.12 #0-0]     at elementIdText("0.5402966943416811-24") - getText.js:35:50
> [chrome  macOS 10.12 #0-0]
> [chrome  macOS 10.12 #0-0] Check out job at https://saucelabs.com/tests/d82e578cb6374ae28d65e902555093e2
> [chrome  macOS 10.12 #0-0]
> 
> 
> 
> 0 passing (108.50s)
> 1 failing
> 
> 1) Elastic Search Article results page Test  "before all" hook:
> The test with session id d82e578cb6374ae28d65e902555093e2 has already finished, and can't receive further commands.
> You can learn more at https://saucelabs.com/jobs/d82e578cb6374ae28d65e902555093e2
> For help, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages
> running chrome on macOS 10.12
> Check out job at https://saucelabs.com/tests/d82e578cb6374ae28d65e902555093e2
> Error: The test with session id d82e578cb6374ae28d65e902555093e2 has already finished, and can't receive further commands.
>     at Context.before (specs_desktop/search_elastic_1.js:17:43)
>     at Promise.F (/Users/dimitrireynaga/.nvm/versions/node/v6.9.5/lib/node_modules/wdio-mocha-framework/node_modules/core-js/library/modules/_export.js:35:28)
>     You can learn more at https://saucelabs.com/jobs/d82e578cb6374ae28d65e902555093e2
>     For help, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages
>     at elementIdText("0.5402966943416811-24") - getText.js:35:50

**Comment by dimirey** [comment]
@christian-bromann There doesn't seem to be anything indicative of why the session is quitting in the logs and there are no commands within the spec file which would cause the session to end

Verbose WDIO logs:
https://gist.github.com/dimirey/ea78370ffc87f6da11a1181129fb6c44

Saucelabs selenium server logs:
https://gist.github.com/dimirey/64e26373e962554066b8af448fc2d107

**Comment by christian-bromann** [comment]
@dimirey do you still experience the issue? I don't think it is a problem within WebdriverIO and more something about the test setup. Please reach out in our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) of you need any further assistance.

**Comment by nicholasodonnell** [comment]
@dimirey did you ever figure out the problem? I'm seeing the same thing over here.

**Comment by pmerwin** [comment]
Promise was rejected with the following reason: ESOCKETTIMEDOUT seeing this a lot on sauce with chrome latest on osx .

**Comment by itssumitrai** [comment]
Still see this issue all the time in 2022

**Comment by christian-bromann** [comment]
@itssumitrai the error can not be fixed because if you send commands after you close the session you will get this error. This might be also a user error, e.g. if you forget an `await`. If you can provide a reproducible example please do and folks are happy to look into it.
