### ISSUE TITLE
How can we access emulator gallery to pick an image. Any help please 

### ISSUE THREAD

**Issue by JaspreetBamrah** [webdriverio/webdriverio#2129]
I am pushing some images to emulator gallery as part of pre-setup. But how can we access the images in gallery.

How can I access the gallery of a phone emulator?
Any suggestions please..

**Comment by christian-bromann** [comment]
Please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
