### ISSUE TITLE
Can localStorage be used to push and pull some images?

### ISSUE THREAD

**Issue by JaspreetBamrah** [webdriverio/webdriverio#2130]
Can localStorage method be used to push an image with a key and then retrieve it using the same key?
I want to push some images to emulator as part of a pre-setup. Can this function be used?

**Comment by christian-bromann** [comment]
Probably, why not. Have you tried it? Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
