### ISSUE TITLE
Getting a 404 server response with remote debugging port with webdriverio

### ISSUE THREAD

**Issue by svg7** [webdriverio/webdriverio#2131]
## The problem
I am trying to use the chrome canary feature (code coverage) and integrate with webdriver for my tests. 
The code : https://github.com/svg7/webdriversamples/blob/master/coveragetest.js

The steps i follow,
1. Start the chrome canary :  ./chrome --remote-debugging-port=6813 
2. Run the coveragetest which is mocha based

I get the following error, saying it is not able to connect to the server.

Error: unexpected server response (404)
>>     at ClientRequest.response (/Users/svg7/projects/examples/build/js/testSuites.js:419:16)
>>     at ClientRequest.g (events.js:291:16)
>>     at emitOne (events.js:96:13)
>>     at ClientRequest.emit (events.js:188:7)
>>     at HTTPParser.parserOnIncomingClient (_http_client.js:472:21)
>>     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
>>     at Socket.socketOnData (_http_client.js:361:20)
>>     at emitOne (events.js:96:13)
>>     at Socket.emit (events.js:188:7)
>>     at readableAddChunk (_stream_readable.js:176:18)

## Environment

* WebdriverIO version: 3.4
* Node.js version: 6.7.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync: false
* Additional wdio packages used (if applicable):

**Comment by christian-bromann** [comment]
I don't see how this is an error caused by WebdriverIO. Please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
