### ISSUE TITLE
WDIO runner exits before all listeners for a custom reporter complete

### ISSUE THREAD

**Issue by nullin** [webdriverio/webdriverio#2133]
## The problem

WDIO runner doesn't wait for all listeners for a custom reporter to complete before exiting. I am trying to write a custom reporter to report results to TestRail. When reporting the results to TestRail if the POST request takes too long, WDIO runner does not wait for it and exits the process. This is especially evident on tests that run very quickly.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 8.0.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable):

## Details

If I change https://github.com/webdriverio/webdriverio/blob/master/lib/runner.js#L184 from `process.exit(this.failures === 0 ? 0 : 1)` to `process.exitCode = this.failures === 0 ? 0 : 1`, and use the updated wdio to run tests, I see that the results are reported correctly to TestRail and logged to console (though wdio doesn't exit then).

-----

I also took a look at https://github.com/webdriverio/wdio-sumologic-reporter but I think (because I didn't run it) that it'll suffer from the same problem where the last sync() call in 'end' listener might not complete.

So, is this something that can be fixed? Or is there another way to report results into web services such as TestRail? (_I am now considering just writing out to a flat file and uploading results after all tests are done running_)

**Comment by christian-bromann** [comment]
> So, is this something that can be fixed?

Not really. Reporters are not designed to execute any async operations like POST requests. You can either push the results to testrail after your test manually or build an additional service to do that automatically.
