### ISSUE TITLE
No option to use BrowserMobProxy via Test Runner

### ISSUE THREAD

**Issue by kirksl** [webdriverio/webdriverio#2134]
## The problem
I'm trying to use BrowserMobProxy when using the Test Runner and don't see an option to specify it.  I realize this can be achieved in Standalone mode but want to take advantage of all of the great features that the Test Runner scaffold provides.

## Environment
NA

* WebdriverIO version: Latest
* Node.js version: Latest
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Test Runner
* if wdio testrunner, running synchronous or asynchronous tests: NA
* Additional wdio packages used (if applicable):
NA

**Comment by christian-bromann** [comment]
Why should it not be possible to use BrowserMobProxy with the testrunner? Just set the proxy property in your capabilities and you are set. Please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by kirksl** [comment]
@christian-bromann can you put a link to the documentation on webdriver.io that shows how to set the proxy property in capabilities.  Your documentation states that all capabilities are spec'd in the configuration file and i don't see an option to set the proxy there http://webdriver.io/guide/testrunner/configurationfile.html.  I only see an option by using wdio in standalone mode (eg var client = webdriverio.remote(options);)

**Comment by christian-bromann** [comment]
> if not spec'd can you turn this into a doc bug.

This capability is documented on Selenium side. It is nothing specific that only WebdriverIO offers. There are probably tons of other Selenium specific things that are not documented in our docs. We could and I would love to add more docs around such things but this should up to people for whom this is unclear.

**Comment by kirksl** [comment]
right but i'm assuming webdriverio's scaffold or api taps into what selenium offers?  i'm developing against your interface not selenium directly.  the only thing i can find is http://webdriver.io/api/protocol/init.html.   but i ask myself if that call would overwrite what i spec'd in the configuration file.

**Comment by christian-bromann** [comment]
> right but i'm assuming webdriverio's scaffold or api taps into what selenium offers?

More of what the Webdriver protocol offers.

> but i ask myself if that call would overwrite what i spec'd in the configuration file.

Not sure if I understand you here. WebdriverIOs creates (and calls this init command) a WebDriver session based on what it can find the capabilities in your config.

**Comment by kirksl** [comment]
what i'm eluding to on the first point is that likely webdriverio has a special way of accessing something selenium-based(eg browser.init( )).

what i'm eluding to on the second point is that if i'm in the middle of a session run with wdio and fire off a call to browser.init( ) to send in more capabilities, do the capabilities i previously spec'd in the wdio.config.js file get cleared?

**Comment by christian-bromann** [comment]
> what i'm eluding to on the first point is that likely webdriverio has a special way of accessing something selenium-based(eg browser.init( )).

If the usage of WebdriverIO is not clear enough in regards of what the WebDriver protocol documents there is definitely a need to improve documentation. But as I said this is up to the people to whom this is unclear to.

> if i'm in the middle of a session run with wdio and fire off a call to browser.init( )

You can't do that. The testrunner creates the session based on the capabilities it finds in your wdio.config file.

**Comment by christian-bromann** [comment]
Let's continue this conversation in our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) channel. I think this issue is answered.
