### ISSUE TITLE
moveTo alternative?

### ISSUE THREAD

**Issue by Cristy94** [webdriverio/webdriverio#2140]
Trying to use `leftClick` or `moveTo` or `moveToObject` I get this warning:
`WARNING: the "moveTo" command will be deprecated soon. Please use a different command in order to avoid failures in your test after updating WebdriverIO.`

What are the alternatives? What has `moveTo` been replaced with?

**Comment by christian-bromann** [comment]
You will probably have to use the action API if published. Please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by midgettj** [comment]
I would like to 2nd this question of alternatives until Action API is implemented. Spent all day on Gitter and noone seems to have a solution.

**Comment by christian-bromann** [comment]
There is non

**Comment by midgettj** [comment]
Is there a rough timeline when Action API will be implemented for webdriverio ?

**Comment by christian-bromann** [comment]
When Geckodriver and Chromedriver do fully support it

**Comment by johanneserber** [comment]
How comes something is deprecated when there's no alternative yet? Is it not a bit early for a deprecation warning then?

**Comment by christian-bromann** [comment]
> How comes something is deprecated when there's no alternative yet?

There is an alternative but it hasn't been supported by the browser driver.

> Is it not a bit early for a deprecation warning then?

In hindsight it was wrong to add the deprecation warnings for all browser given that only Firefox was affected. I will update this soon. If the error messages are too verbose just use latest `v4.7.x` version.

**Comment by armoucar** [comment]
> If the error messages are too verbose just use latest v4.7.x version

Cool then, I'll keep using v4.7.x while paying attention to this thread for updates. Thanks

**Comment by mherodev** [comment]
So to be clear, moveToObject will fail in Firefox?

**Comment by christian-bromann** [comment]
> So to be clear, moveToObject will fail in Firefox?

Yes, you need to use the actions command!

**Comment by gsanta** [comment]
Here is an implementation of the moveToObject, that worked for us on chrome and firefox, based on the actions protocol.

```
browser.addCommand('moveToElement', function(selector, x, y) {

       if (this.desiredCapabilities.browserName === 'firefox') {
           return this.getLocation(selector)
           .then(function(location) {
             
              // setting mouse position to the top-left corner of the browser, see this idea of @mhemesath on gitter
              // https://gitter.im/webdriverio/webdriverio?at=5a24be23cc1d527f6be94b49
              return this.execute(function () {
                  // eslint-disable-next-line no-var
                  var div = document.createElement('div');
                  document.body.appendChild(div);
                  div.id = 'wdioMouseReset';
                  div.style.position = 'absolute';
                  div.style.top = 0;
                  div.style.left = 0;
                  div.style.width = '1px';
                  div.style.height = '1px';
                  div.style.zIndex = '9999999';
                  // eslint-disable-next-line func-names, prefer-arrow-callback
                  div.addEventListener('click', function () {
                  document.body.removeChild(div);
                  })
              })
              .click('#wdioMouseReset')
              .actions(
                  [{
                      "type": "pointer",
                      "id": "finger1",
                      "parameters": {"pointerType": "mouse"},
                      "actions": [
                          {"type": "pointerMove", "duration": 0, "x": location.x + 2, "y": location.y + 2}
                      ]
                  }]
              )
          });
       } else {
           return this.moveToObject(selector, x, y);
       }
   });
```

**Comment by mherodev** [comment]
Weird, that works fine for me in Chrome locally, but fails when it's run in SauceLabs.

**Comment by mhemesath** [comment]
> Here is an implementation of the moveToObject, that worked for us on chrome and firefox, based on the actions protocol.

If the actions protocol is supported, you should be able to use that to move the mouse to (0,0) on the viewport, or not at all, if needed. The div injection hack was only used because the actions API wasn't supported in Chrome for me yet and I didn't want to rely on a deprecated API.

**Comment by gsanta** [comment]
I thought that the action's x and y coordinate will be relative to the current mouse position, thats why I used your approach to set it to zero, but I will try it without it then.
Thanks.

**Comment by mhemesath** [comment]
If you read the [doc on actions]( https://github.com/jlipps/simple-wd-spec#input-sources-and-corresponding-actions), it says that pointerMove origin defaults to viewport if omitted.

**Comment by gsanta** [comment]
True, than it should work, thanks!

**Comment by ryancat** [comment]
What if we want to click at a given offset position on an element? The method @gsanta mentioned above works for move cursor to that position, but cannot click at that position. 

I tried to dispatch a click event, but it's not clear to me how to specify where to click at. Could anyone help on this? Thanks!

**Comment by gsanta** [comment]
You can put multiple actions into the actions array, simulating a move and then a click:

```
"actions": [
            {"type": "pointerMove", "duration": 0, "x": 100, "y": 100},
            {"type": "pointerDown", "button": 0},
            {"type": "pause", "duration": 500},
            {"type": "pointerUp", "button": 0}
        ]
```

**Comment by funky17** [comment]
@gsanta:
I a newbie trying to figure out how to use your implementation. Can you please post a sample code on how to use this implementation?

**Comment by Austio** [comment]
Thought: This seems like a really good place for webdriver to provide a consistent api wrapper for these things.  As a dev, i am ok with moving down to the actions stuff if i have to, but being able to do `moveMouseTo` and it work regardless of what browser i'm testing against would be really awesome.  Internally, it would be a nested switch statement on browser to convert the commands to the supported browser api.

**Comment by rostrovsky** [comment]
This can be worked around like:
```node
browser.selectorExecute(element.selector, function (elem) {
    elem[0].scrollIntoView();
  });
```

**Comment by mhemesath** [comment]
Looks like the action API in chrome may land soon: https://bugs.chromium.org/p/chromedriver/issues/detail?id=1897

**Comment by christian-bromann** [comment]
@mhemesath that's good news

**Comment by cbou** [comment]
Why are moveTo and moveToObject still in the documentation if they do not work?
If it should stay maybe a notice that it does not work with firefox would be nice...

http://webdriver.io/api/protocol/moveTo.html
http://webdriver.io/api/action/moveToObject.html

**Comment by Aid19801** [comment]
Surprised me that it *did* but `el.moveTo` seems to work for me:

```
$('.header__yourMum').moveTo();
```

**Comment by ManikanthErukulla1** [comment]
> Surprised me that it _did_ but `el.moveTo` seems to work for me:
> 
> ```
> $('.header__yourMum').moveTo();
> ```

does it work for firefox?

**Comment by Aid19801** [comment]
@ManikanthErukulla1 not sure, i've just been using chrome so far.
