### ISSUE TITLE
pause() - waitUntil/waitForXXX behaviour

### ISSUE THREAD

**Issue by telekosmos** [webdriverio/webdriverio#2143]
## The problem
Inconsistent (AFAIK) behaviour between `browser.pause()` and `waitUntil(...)`, `waitForExist` methods
## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 6.9.4
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable):
  - "wdio-allure-reporter": "^0.1.2",
  - "wdio-json-reporter": "^0.2.1",
  - "wdio-mocha-framework": "^0.5.8",
  - "wdio-selenium-standalone-service": "0.0.8",
  - "wdio-spec-reporter": "0.0.5"

## Details
First snippet:
```javascript
        browser.url(Navigation.BASE_URL + Navigation.PATH_URL)
        browser.pause(waitFor * Navigation.MILLIS) // Recomended NOT use
        bodyEl = $("html body");
        /*
        browser.waitUntil(function() {
            return $("div#navModule.navModule").state === 'success';
        });
        */
        // browser.waitForExist("div#navModule.navModule");
        console.log('[Navigation::startup] style:' +
            JSON.stringify($("div#navModule.navModule").getCssProperty('display')));
```
Prints `[Navigation::startup] style:{"property":"display","value":"none","parsed":{"type":"ident","string":"none"}}`, which is __OK__

But, if I replace `browser.pause` for `browser.waitUntil` (or `waitForExist`), as recommended in docs, just like:
```javascript
        browser.url(Navigation.BASE_URL + Navigation.PATH_URL)
        // browser.pause(waitFor * Navigation.MILLIS) // Recomended NOT use
        bodyEl = $("html body");
        browser.waitUntil(function() {
            return $("div#navModule.navModule").state === 'success';
        });
        // browser.waitForExist("div#navModule.navModule");
        console.log('[Navigation::startup] style:' +
            JSON.stringify($("div#navModule.navModule").getCssProperty('display')));

```
it prints `[Navigation::startup] style:{"property":"display","value":"block","parsed":{"type":"ident","string":"block"}}`, which is __wrong__ as I know that element has attribute `style="display: none"` at this moment.

This is the very first step on running the suite.
So, what am I doing wrong?

thanks!!!

w

**Comment by christian-bromann** [comment]
`$("div#navModule.navModule").state === 'success'` only indicates that the Selenium request went fine. It doesn't contain any information on the element visibility. Please use the explicit wait methods (waitForXXX) to make sure a certain state is reached. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by telekosmos** [comment]
Thanks, I will try what you say!!
Also, ok about gitter :+1:
