### ISSUE TITLE
General no such element error is thrown when element doesn't have value attribute

### ISSUE THREAD

**Issue by ndimer** [webdriverio/webdriverio#2144]
## The problem

In stand-alone mode, when calling getValue method on the element that doesn't have value, such as button, a very misleading message is returned: "RuntimeError: An element could not be located on the page using the given search parameters". Appium (in my case, guess Selenium behaviour is the same) returns {"status":7,"value":"This element does not have the 'value' attribute"}. So it seems that return status is wrongly translated to a general no such element error. Suggest to throw more relevant message.

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 6.6.0
* Standalone mode against Appium

**Comment by christian-bromann** [comment]
@ndimer can you please provide the logs for both use cases?

**Comment by ndimer** [comment]
@christian-bromann what logs do you need? Appium?

**Comment by christian-bromann** [comment]
yes

**Comment by ndimer** [comment]
Please see attached.
[Appium.txt](https://github.com/webdriverio/webdriverio/files/1081720/Appium.txt)

**Comment by christian-bromann** [comment]
@ndimer the Appium logs are saying a different error: `org.json.JSONException: No value for xSpeed` which doesn't seem to be related to this issue. Are you still encounter it? Can you share the correct logs?

Closing. But happy to reopen if logs are provided.
