### ISSUE TITLE
set wdio.conf.js -> capabilities -> proxy doesn't work

### ISSUE THREAD

**Issue by straweb** [webdriverio/webdriverio#2147]
## The problem

set wdio.conf.js -> capabilities -> proxy doesn't work for BrowsermobProxy server

work around is need to set capabilities-> proxy settings in beforeSession

## Environment

* WebdriverIO version:   "_id": "webdriverio@4.8.0"
* Standalone mode

**Comment by christian-bromann** [comment]
@straweb can you please explain in a bit more detail?

**Comment by christian-bromann** [comment]
Closing due inactivity.
