### ISSUE TITLE
driver does not support org.openqa.selenium.html5.LocationContext

### ISSUE THREAD

**Issue by endor** [webdriverio/webdriverio#215]
I am not sure where the origin of the error is, so I'm filing this here in the hopes that someone might shed some light on the issue.

Here's what I am doing after installing the v2.0.0 branch as a node module:

```
client = webdriverjs.remote({
    desiredCapabilities: {
        browserName: 'firefox',
        locationContextEnabled: true
    }
});

client.init() 
    .setGeoLocation({latitude: 52, longitude: 13, altitude: 1});
```

Here's the error:

```
Uncaught RuntimeError
(UnknownError:13) An unknown server-side error occurred while processing the command.
Problem: driver (org.openqa.selenium.firefox.FirefoxDriver) does not support org.openqa.selenium.html5.LocationContext
Build info: version: '2.40.0', revision: 'fbe29a9', time: '2014-02-19 20:54:28'
System info: host: 'abc.local', ip: '1.2.3.4', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.2', java.version: '1.6.0_65'
Driver info: driver.version: unknown
```

The same issue with phantomjs and chrome as browser, even though I have enabled `locationContextEnabled` in the `desiredCapabilities` (which it is by default, as I understood). So why does this happen?

Please also note, that there seems to be an issue with the setGeoLocation code. Selenium seems to expect this: `{location: {latitude: 1, longitude: 2, altitude: 3}}` and gets this from setGeoLocation: `{latitude: 1, longitude: 2, altitude: 3}`.

**Comment by pdelanauze** [comment]
Why is this closed ? Would love to have support for this ..

**Comment by christian-bromann** [comment]
> Have you done selenium debugging by chance?

No

@pdelanauze I guess you can still use local storage on the client side using the execute command and run some javascript on the page. Support for this would be great but it's still a problem with Selenium not WebdriverIO. I am happy to accept any PR that makes this work. There definitely other issues with higher prio though

**Comment by ToniChaz** [comment]
Hi, i have the same issue with sessionStorage, i use execute command but phantom return: SecurityError: DOM Exception 18

**Comment by christian-bromann** [comment]
@ToniChaz looks like a PhantomJS issue.

**Comment by ToniChaz** [comment]
Thank you @christian-bromann

**Comment by lalka-workco** [comment]
I also get same issue when using localStorage through browser.execute()

**Comment by CrispusDH** [comment]
> I also get same issue when using localStorage through browser.execute()

do you use WebdriverIO or [selenium webdriverjs binding](https://github.com/SeleniumHQ/selenium/tree/master/javascript/webdriver)?

**Comment by lalka-workco** [comment]
I am using WebdriverIO v5. It seems to happen mostly when I try to work with localStorage on Firefox. It seems like the driver might not support the command?

**Comment by CrispusDH** [comment]
> I am using WebdriverIO v5. It seems to happen mostly when I try to work with localStorage on Firefox. It seems like the driver might not support the command?

it would be great if you create a new issue with reproducible repo

**Comment by christian-bromann** [comment]
> It seems like the driver might not support the command?

It doesn't. The local storage command was removed from the protocol. Use the execute command to access the local storage of the browser.
