### ISSUE TITLE
$("[name=q]").setValue("foo") fails with message "Error" when called from wdio REPL

### ISSUE THREAD

**Issue by mo** [webdriverio/webdriverio#2150]
Using the "wdio repl chrome" with webdriverio 4.8.0 (and node v7.7.2), I'm not able to use the $() syntax even though the corresponding "browser.SOMETHING" call works.

For example, inside the REPL when I do:

  $("[name=q]").setValue("foo")

...it just print this error message:

  Error
      unknown error line

Full log from REPL:

> browser.url("https://google.com")
{ state: 'success',
  sessionId: '23062d04-0eef-4aff-a56a-0a4fadaaa60b',
  hCode: 726359612,
  value: null,
  class: 'org.openqa.selenium.remote.Response',
  _status: 0 }
> $
[Function]
> $("[name=q]")
{ state: 'success',
  sessionId: '23062d04-0eef-4aff-a56a-0a4fadaaa60b',
  hCode: 125723387,
  value: { ELEMENT: '0', 'element-6066-11e4-a52e-4f735466cecf': '0' },
  class: 'org.openqa.selenium.remote.Response',
  selector: '[name=q]',
  _status: 0 }
> $("[name=q]").setValue("foo")
Error
    unknown error line
> browser.setValue("[name=q]", "foo")
{ state: 'success',
  sessionId: '23062d04-0eef-4aff-a56a-0a4fadaaa60b',
  hCode: 189070611,
  value: null,
  class: 'org.openqa.selenium.remote.Response',
  _status: 0 }

**Comment by christian-bromann** [comment]
You need to have wdio-sync installed to use this syntax. Please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).

**Comment by mo** [comment]
@christian-bromann thanks for the super quick response!!

It would be sweet to change the error message from "Error" to "Error: required package wdio-sync is not installed" instead if this is possible?

**Comment by mo** [comment]
I did "npm install --save wdio-sync", restarted the selenium server, and then restarted the repl using "./node_modules/.bin/wdio repl chrome" but I still get the same error.

**Comment by jeremypenner** [comment]
Definitely something wonky with selector chaining in the repl - running the following in the repl results in `Error: An element could not be located on the page using the given search parameters` - a quick peek in Wireshark shows that it's treating 'test' as a CSS selector, and not the value.
```
var HTML = '<body><select><option value="default">----</option><option value="test">Test</option></select></body>'
var uri = "data:text/html;charset=UTF-8;base64," + new Buffer(HTML).toString('base64')
browser.url(uri)
browser.selectByValue('select', 'test') // fine
$('select').selectByValue('test') // fails
```
When the same code runs in a mocha test from the wdio test runner, it works correctly.

**Comment by mikkqu** [comment]
Just ran into this, then googled out this page. Can confirm.

**Comment by jeremypenner** [comment]
For the benefit of people Googling for a workaround, I've given up on `wdio repl` and `browser.debug()` entirely, in favour of a `repl.js` "test" which can be run with `--spec` that has a `debugger` call in it. Putting it in a Mocha test means that all of my setup code from `wdio.conf.js` runs automatically, and I've found using the Node.js devtools in Chrome is more reliable and flexible than the `browser.debug()` REPL. My personal `repl.js` also has a bunch of `require` statements at the top so I can have immediate access to my page objects from the debugger.

**Comment by christian-bromann** [comment]
Hey,

we update the core architecture of WebdriverIO and with that a lot of implementation details that might make this issue obsolete. Please try with the latest version of WebdriverIO and verify if this still occurs. If so please open a new issue and we will tackle it asap.

Thanks!
