### ISSUE TITLE
Question: For grouping of actions is it better to create a custom command or just create another method in page object

### ISSUE THREAD

**Issue by swetashahi-brightplan** [webdriverio/webdriverio#2152]
## The problem
I have a question on using the Page object pattern with the wdio test runner. What is a better way to group methods?

Below are the two samples.

Sample 1:
Add a method in the page object file (login.page.js)
```js
login: { value: function(username, password) {
    page.open.call(this, 'app/login');
    this.username.waitForVisible();
    this.username.setValue(username);
    this.password.waitForVisible();
    this.password.setValue(password);
    this.submitButton.click();
    }  }
```
and call it in the spec file like LoginPage.login(creds.username, creds.password);

Sample 2:

Add it after the module.exports line in the page object file (login.page.js)
```
    browser.addCommand("loginFlow", function (username, password) {
    LoginPage.open();
    LoginPage.username.waitForExist();
    LoginPage.username.setValue(username);
    LoginPage.password.setValue(password);
    LoginPage.submit();
    })
```
And call it in the spec file as 
browser.loginFlow(creds.username, creds.password);

**Comment by christian-bromann** [comment]
Definitely Sample 1! Custom commands are a relict from times where POs were not possible with WebdriverIO. Please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
