### ISSUE TITLE
wdio runner: resolve framework in cwd

### ISSUE THREAD

**Issue by paulpflug** [webdriverio/webdriverio#2157]
when calling a globally installed wdio runner within a package folder with available framework, wdio isn't able to find it.

[current implementation](https://github.com/webdriverio/webdriverio/blob/master/lib/runner.js#L332):
```js
try {
  return require(frameworkLibrary).adapterFactory
} catch (e) {
  // fail 
  }
```
my proposal - look in cwd first:
```js
try {
  return require(path.resolve(process.cwd(),"node_modules",frameworkLibrary)).adapterFactory
} catch (e) {
  try {
    return require(frameworkLibrary).adapterFactory
  } catch (e) {
  // fail 
  }
}
```

**Comment by christian-bromann** [comment]
I am not sure if this is the right way to do this. In general you should have your wdio dependency always installed locally. If you decide to have it globally installed you should also install its 3rd party dependencies globally.

**Comment by christian-bromann** [comment]
I think switching on a the global installed webdriverio package is not a good idea and can cause other confusions. Closing.
