### ISSUE TITLE
Best way to set input[type="date"] value

### ISSUE THREAD

**Issue by wmonk** [webdriverio/webdriverio#2158]
## The problem
`input[type="date"]` doesn't accept `browser.setValue` due to the fact it tries to clear the existing value. I have taken the advice of another issue posted here that suggests using `browser.addValue` instead. This works fine, although i'm not 100% sure what is happening under the hood. 

So while this all works fine locally, having pushed to CI (circleci), the test starts failing. The error was that the expected data sent of `1990-10-12` was actually `1990-12-10` - I was very confused that the month and day were being swapped?! My code looks like:

```javascript
await browser.addValue('input[name="dob"]', '12101990')
```

Here in the UK the general date format used is `dd-MM-yyyy`. So when I use this format locally, it works fine. But on CI the localisation must be `MM-dd-yyyy`! [This article by Google](https://developers.google.com/web/updates/2012/08/Quick-FAQs-on-input-type-date-in-Google-Chrome) describes how the date field works.

I'm not really sure what the ideal way to solve this is. The quickest way is to use an identical month and day in testing - which isn't great! Do you have any thoughts about how to solve this in a nice way? I'm not sure I like the idea of having to drop down into the browser context and setting the `input.value` manually, although it'd work.

**Comment by christian-bromann** [comment]
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue. Thanks for understanding.

**Comment by faizrr** [comment]
I don't know is it good way or not, but I solved this issue this way. I made custom helper that returns formatted date depending on `LANG` env variable. Then I put this string to date input via `addValue`.

```javascript
function formatDate (date) {
  const lang = process.env.LANG.slice(0, 5).replace('_', '-') // ru_RU.utf8 -> ru-RU
  moment.locale(lang)
  let formattedDateForInput = moment(date).format('L')

  if (isNaN(Number(formattedDateForInput[4]))) {
    // for some reason, chrome allow user to specify years until 999 999
    // and if we have YYYY-MM-DD format, we will specify only year
    // so we need to apply `tab` after year had specified
    // btw, this fix will work until 31 December 9999
    // hope, chrome team will fix this bug until this year

    formattedDateForInput = formattedDateForInput.replace(/[^0-9]/, '\t') // if year is first part in formattedDate
  }

  formattedDateForInput = formattedDateForInput.replace(/[^0-9\t]/gi, '') + '\t'

  return formattedDateForInput
}
```

**Comment by vijaycs85** [comment]
just `setValue` with the exact format of the date field works too. e.g.


`$('input[name="start_date"').setValue('15-02-2021');`

**Comment by klaukl** [comment]
> just `setValue` with the exact format of the date field works too. e.g.
> 
> `$('input[name="start_date"').setValue('15-02-2021');`

I am facing the same issue and in this case if you run it on a diff timeformat it will auto transform.

I.e. setValue('15-02-2021') in UK / locally sets correctly but you run this in CI (america) it will set 02-15-2021 :'( Any ideas on how to fix?
