### ISSUE TITLE
Tests(written as sync: true) on Safari not navigating to pages that need login.

### ISSUE THREAD

**Issue by aduggirala** [webdriverio/webdriverio#2160]
## The problem
I have tests that need the user to login.
They run fine on Chrome, but will not run on Safari 10.1.1.
## Environment

* WebdriverIO version: 4.6.2
* Node.js version: v7.9.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):wdio-mocha-framework, wdio-spec-reporter

## Details

In wdio.conf.js I have sync set to true to run the tests as synchronous.
The tests will run on Safari just for the login page, but will not find any element once other pages are navigated to past login.
**Note the tests will pass on safari if sync is set to false but i would like them to work with sync:true.**

Here is the chrome output
[chrome #0-0]
[chrome #0-0] Test Header icons.
[chrome #0-0]   ✓ Add org and location.
[chrome #0-0]   ✓ Tests search feature in header
[chrome #0-0]   ✓ Tests App Share feature in header
[chrome #0-0]   ✓ Tests changing account password and email information
[chrome #0-0]   ✓ Tests logging out
[chrome #0-0]
[chrome #0-0]
[chrome #0-0] 5 passing (37s)
[chrome #0-0]
Here is the Safari output:

[safari #0-0] Session ID: ea178567-883a-4828-8dc9-d571b225c71e
[safari #0-0] Spec: /Users/duggirala/Desktop/meridian-qa-automation/wdio_test_automation/test/specs/Header.spec.js
[safari #0-0] Running: safari
[safari #0-0]
[safari #0-0] Test Header icons.
[safari #0-0]   1) Add org and location.
[safari #0-0]   2) Tests search feature in header
[safari #0-0]   3) Tests App Share feature in header
[safari #0-0]   4) Tests changing account password and email information
[safari #0-0]   5) Tests logging out
[safari #0-0]
[safari #0-0]
[safari #0-0] 5 failing (11s)
[safari #0-0]
[safari #0-0] 1) Test Header icons. Add org and location.:
[safari #0-0] An element could not be located on the page using the given search parameters ("#content-textbox-name > formsytextbox > input").
[safari #0-0] Error: An element could not be located on the page using the given search parameters ("#content-textbox-name > formsytextbox > input").
[safari #0-0]     at setValue("AutomationiSFlXx") - index.js:307:3
[safari #0-0]
[safari #0-0] 2) Test Header icons. Tests search feature in header:
[safari #0-0] An element could not be located on the page using the given search parameters ("#content-searchbox-locations > searchbox > input[type="search"]").
[safari #0-0] Error: An element could not be located on the page using the given search parameters ("#content-searchbox-locations > searchbox > input[type="search"]").
[safari #0-0]     at setValue("AutomationnzYCPG") - index.js:307:3
[safari #0-0]
[safari #0-0] 3) Test Header icons. Tests App Share feature in header:
[safari #0-0] An element could not be located on the page using the given search parameters ("#content-searchbox-locations > searchbox > input[type="search"]").
[safari #0-0] Error: An element could not be located on the page using the given search parameters ("#content-searchbox-locations > searchbox > input[type="search"]").
[safari #0-0]     at setValue("AutomationnzYCPG") - index.js:307:3
[safari #0-0]
[safari #0-0] 4) Test Header icons. Tests changing account password and email information:
[safari #0-0] An element could not be located on the page using the given search parameters ("#content-searchbox-locations > searchbox > input[type="search"]").
[safari #0-0] Error: An element could not be located on the page using the given search parameters ("#content-searchbox-locations > searchbox > input[type="search"]").
[safari #0-0]     at setValue("AutomationnzYCPG") - index.js:307:3
[safari #0-0]
[safari #0-0] 5) Test Header icons. Tests logging out:
[safari #0-0] An element could not be located on the page using the given search parameters ("#content-searchbox-locations > searchbox > input[type="search"]").
[safari #0-0] Error: An element could not be located on the page using the given search parameters ("#content-searchbox-locations > searchbox > input[type="search"]").
[safari #0-0]     at setValue("AutomationnzYCPG") - index.js:307:3
[safari #0-0]

npm ERR! Test failed.  See above for more details.

## Code To Reproduce Issue [ Good To Have ]

// login.spec.js
var expect = require('chai').expect;
var LoginPage = require('../pageobjects/Login.page.js');
var CreateOrgPage = require('../pageobjects/CreateOrg.page.js');
var AddLocation = require('../pageobjects/AddLocation.page.js');
var path = require("path");
var randomstring = require("randomstring");
var orgName ="Automation"+randomstring.generate({
  length: 6,
  charset: 'alphabetic'
})
var locationName ="Automation"+randomstring.generate({
  length: 6,
  charset: 'alphabetic'
})

describe('Test Header icons.', function () {
  before(function(){
    browser.windowHandleMaximize("current");
    LoginPage.open();
    LoginPage.username.setValue('*******');
    LoginPage.password.setValue('*******');
    LoginPage.submit();
  });

  it('Add org and location.',function(){
    // Create a new org with basic information.
    browser.windowHandleMaximize("current");
    CreateOrgPage.open();
    CreateOrgPage.name.setValue(orgName);
    CreateOrgPage.purchaseOrder.setValue(orgName);
    CreateOrgPage.salesOrder.setValue(orgName);
    CreateOrgPage.submit();
    console.log(orgName);
    // create a new location and use org created.
    AddLocation.open();
    browser.timeouts('implicit', 7000);
    AddLocation.name.setValue(locationName);
    //  click the organization field.
    AddLocation.organization.click();
    // Enter the org name that we just created.
    browser.element(".Select-input > input").setValue(orgName);
    console.log(locationName);
    // get the dropdown option.
    var option = browser.element(".Select-option");
    option.click();
    // Turn Maps feature on.
    AddLocation.appMaker_Feature.click();
    AddLocation.migrate_SKU.click();
    var submit = $(".button.save");
    submit.scroll();
    submit.click();
  });
  it("Tests search feature in header",function(){
    // Create a basic page and search for it.
    browser.windowHandleMaximize("current");
    browser.url('/');
    browser.element('#content-searchbox-locations > searchbox > input[type="search"]').setValue(locationName);
    browser.timeouts('implicit', 5000);
    browser.click('span*='+locationName);
    browser.click("#navigation-link-pages")
    browser.click("*=Add your first Page")
    browser.waitForVisible(".page-name")
    browser.element(".page-name").setValue("Page-Search-Test")
    browser.click(".button.save.short_sectionHeader")
    browser.click("#header-search")
    if (browser.isVisible('#header-search-modal > search > span:nth-child(1) > modal > content > rows > row:nth-child(7) > button')){
      console.log("Header text available")
      browser.click("#header-search-modal > search > span:nth-child(1) > modal > content > rows > row:nth-child(7) > button")
    }
    browser.element('#header-search-modal > search > span:nth-child(2) > modal > content > omnibox > div > input').setValue("Page-Search-Test")
    expect(browser.element('#header-search-modal > search > span:nth-child(2) > modal > content > omnibox > div > omniboxmenu > div > omniboxmenuitem > columns')).to.exist

  });
  it("Tests App Share feature in header",function(){
    // Create a basic page and search for it.
    browser.windowHandleMaximize("current");
    browser.url('/');
    browser.element('#content-searchbox-locations > searchbox > input[type="search"]').setValue(locationName);
    browser.timeouts('implicit', 5000);
    browser.click('span*='+locationName);
    browser.click("#header-preview")
    browser.element("#header-preview-modal > span > modal > content > rows > row:nth-child(5) > columns > column:nth-child(1) > span > input").setValue("editor.selenium.automation@gmail.com")
    browser.click('#header-preview-modal > span > modal > content > rows > row:nth-child(5) > columns > column:nth-child(2) > button > name')
    expect(browser.element('//*[contains(., "Sent")]')).to.exist;
    browser.click("#header-preview-modal > span > modal > close > icon")
  });

  it("Tests changing account password and email information",function(){
    // Create a basic page and search for it.
    browser.windowHandleMaximize("current");
    browser.url('/');
    browser.element('#content-searchbox-locations > searchbox > input[type="search"]').setValue(locationName);
    browser.timeouts('implicit', 5000);
    browser.click('span*='+locationName);
    browser.click("#header-account")
    browser.elements("input[type='password']").setValue("asdf")
    browser.click(".button.save")
    expect(browser.element('//*[contains(., "Current password is incorrect")]')).to.exist;

  });

  it("Tests logging out",function(){
    // Create a basic page and search for it.
    browser.windowHandleMaximize("current");
    browser.url('/');
    browser.element('#content-searchbox-locations > searchbox > input[type="search"]').setValue(locationName);
    browser.timeouts('implicit', 5000);
    browser.click('span*='+locationName);
    browser.click("#header-logout")
    browser.click("#header-logout-modal > span > modal > content > rows > row:nth-child(3) > columns > column:nth-child(3) > button > name")
    expect(browser.getUrl()).to.contain("/login");
  });

});

**Comment by christian-bromann** [comment]
I don't see a bug here. If your test don't work in Safari check the Safaridriver logs if it has any errors or check the WebdriverIO logs if something is odd. Also feel free to join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
