### ISSUE TITLE
CI builds for the project are failing

### ISSUE THREAD

**Issue by anjunatl** [webdriverio/webdriverio#2166]
## The problem

I think I'm seeing a bug so I wanted to check the application's tests to see if they were passing and found that they're not running - there's some error related to Sauce occurring. Following thousands of lines of something referencing `node: 0.12`

## Details

https://travis-ci.org/webdriverio/webdriverio
https://travis-ci.org/webdriverio/webdriverio/jobs/241704709

![screen shot 2017-07-01 at 5 20 07 pm](https://user-images.githubusercontent.com/157208/27765526-94187cd6-5e81-11e7-97b9-a8d2478583c3.png)

**Comment by timbru31** [comment]
If you look close enough than the CI currently fails at the ESLint stage:
https://travis-ci.org/webdriverio/webdriverio/jobs/248719470#L2009-L2012

The #2057 PR introduced this ESLint error - besides that Chrome, Firefox and Android failed the " 1) should find element with non-breaking spaces before and after the text" test asertion in https://travis-ci.org/webdriverio/webdriverio/jobs/247690165#L7220-L7221

Go ahead and fix the CI issues ;)

**Comment by christian-bromann** [comment]
CI build was fixed.
