### ISSUE TITLE
Can't perform getValue() after setValue() in custom command

### ISSUE THREAD

**Issue by faizrr** [webdriverio/webdriverio#2167]
## The problem

Here's the custom command:
```javascript
browser.addCommand('setValue2', function (value) {
  this.setValue(value)
  console.log(this.getValue())
})
```

Here's the test:
```javascript
describe('Test', () => {
    it('works', () => {
        browser.url('https://output.jsbin.com/vubowurepi')
        const input = browser.element('input')
        input.setValue2('foobar')
    })
})
```

What I get:
```
Error: selector needs to be typeof `string`
    at Object.wait (/Users/Roman/WebstormProjects/webdriverio-test/node_modules/fibers/future.js:449:15)
    at Object.getValue (/Users/Roman/WebstormProjects/webdriverio-test/node_modules/wdio-sync/build/index.js:278:31)
    at Object.<anonymous> (/Users/Roman/WebstormProjects/webdriverio-test/wdio.conf.js:168:30)
    at /Users/Roman/WebstormProjects/webdriverio-test/node_modules/wdio-sync/build/index.js:205:29
    - - - - -
    at elements() - getValue.js:18:17
    at getValue() - index.js:258:37
    at elementIdValue("0", "foobar") - setValue.js:46:80
```

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 6.7.0 (but is also reproducible in 7.10.0, 8.1.3)
* Wdio test runner
* Synchronous tests

**Comment by diachedelic** [comment]
I also have this issue, I've created an [example repo](https://github.com/diachedelic/webdriverio-examples/tree/master/wdio-phantomjs-only)

**Comment by christian-bromann** [comment]
Hey,

we update the core architecture of WebdriverIO and with that a lot of implementation details that might make this issue obsolete. Please try with the latest version of WebdriverIO and verify if this still occurs. If so please open a new issue and we will tackle it asap.

Thanks!
