### ISSUE TITLE
How to read file on the device/simulator on iOS that was pushed using PushFile API 

### ISSUE THREAD

**Issue by asoneji** [webdriverio/webdriverio#2168]
How to read file on the device/simulator on iOS that was pushed using PushFile API (http://webdriver.io/v4.0/api/mobile/pushFile.html)

**Comment by christian-bromann** [comment]
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue. Thanks!

**Comment by asoneji** [comment]
OK. thanks!

**Comment by asoneji** [comment]
Looks no answer for the question on gitter
