### ISSUE TITLE
How to pass debuggerAddress for WebDriverIO

### ISSUE THREAD

**Issue by Ankit123P** [webdriverio/webdriverio#2170]
## The problem

I am using spectron to automate an electron app, with WebDriverJS I am able to connect to remote debugger which I launched on 9222 but I cannot find a way to connect to the remote debugger in webdriverio. 

Here is what I am doing..

I first launch the chrome.exe with --remote-debugging-port=9222 and then from my script I point to this port using chromeOptions 'debuggerAddress=127.0.0.1:9222' and I am able to successfully run my script on chrome but I am unable to find a way to do the same thing in WebDriverIO. I am doing this: 
```js
 var options= { desiredCapabilities: { 
    browserName: 'chrome',
    chromeOptions: {
    	     args: ['--debuggerAddress:127.0.0.1:9222']
            
         }
    } };
```
But this isn't working. Please help.

**Comment by christian-bromann** [comment]
Please see https://sites.google.com/a/chromium.org/chromedriver/capabilities . Chromedriver has a specific chrome option for that, so do
```js
 var options= { desiredCapabilities: { 
    browserName: 'chrome',
    chromeOptions: {
    	     debuggerAddress: "127.0.0.1:9222"
            
         }
    } }
```

Also please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
