### ISSUE TITLE
Difference in JSDoc for .element and .elements methods

### ISSUE THREAD

**Issue by fobos** [webdriverio/webdriverio#2174]
Hi.

Is it ok that JSDoc for `.element` and `.elements` methods defines different base type for return value?

For `.element` it  deined as:

> `* @return {String} A WebElement JSON object for the located element.`

For `.elements` as:

> `* @return {Object[]} A list of WebElement JSON objects for the located elements.`

I suppose that more correct is using `@return {Object}` definition. Am I right? If so I can create a PR for it.

**Comment by christian-bromann** [comment]
> I suppose that more correct is using @return {Object} definition. Am I right? If so I can create a PR for it.

You are right. Would be awesome if you could open a PR for that. Thanks!
