### ISSUE TITLE
How to select a test site in a multi instance environment

### ISSUE THREAD

**Issue by sherlock1982** [webdriverio/webdriverio#2175]
Hi!

I have a number of spec files and want to run them in parallel. 
Though I can't allow more than one spec at a time on one site. So I setup two identical sites and set maxInstances to 2. I can switch sites by specifying baseUrl.

Is there a way to acquire a site in beforeSession and select baseUrl and than release it in afterSession ?

OR another similar example. What if I have two logins on the same baseUrl and I want to run a spec on a free login? So two specs never run on the same login.

Probably wdio can supply a kind of a "instance id" to a child process.

**Comment by christian-bromann** [comment]
@sherlock1982 you can assign custom options to your capabilities and access them via `browser.desiredCapabilities` ([more here](http://webdriver.io/guide/testrunner/browserobject.html)). Then you can login with different creds. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) and we can discuss this solution in more details.
