### ISSUE TITLE
Mock external Api

### ISSUE THREAD

**Issue by davidsoderberg** [webdriverio/webdriverio#2178]
Hi, can I mock external api in webdriverio with some other libary?

**Comment by gauravrajput44** [comment]
better to ask these type of question on gitter channel https://gitter.im/webdriverio/webdriverio

**Comment by christian-bromann** [comment]
As @gauravrajput44 says, our gitter support channel is the right place for such questions.

**Comment by maryMariia** [comment]
Hi, can I mock external api in webdriverio with some other libary?

**Comment by christian-bromann** [comment]
No comment 😆
