### ISSUE TITLE
Add documentation regarding shardTestFiles option. 

### ISSUE THREAD

**Issue by nickalto** [webdriverio/webdriverio#2180]
## The problem

After running into an issue that caused Sauce Labs to become swamped when two builds were submitted to it I ran across the `shardTestFiles` option which will allow you to scope the parallelization of specs to a per-file basis as opposed to a per-spec basis. 

## Environment

* WebdriverIO version: 3.10.10
* Node.js version: 6.11
* Wide Testrunner, running synchronous tests

## Details
When attempting to run tests with 5 specs spread over 3 files against 5 platforms ( Firefox, Chrome, IE, Edge, Safari) we ended up swamping Sauce Labs to the point where specs run at the same time would compete for free VM's which would ultimately result in spec timeout failures. By default it appears that the `shardTestFiles` option defaults to true, which was causing each spec to spin up a new VM. This meant that when two developers attempted to run tests each would require 25 VM's ( 5 specs * 5 platforms ). Since we only have 8 available VM's through sauce this caused quite a few jobs to be enqueued and ultimately timeout. By disabling the `shardTestFiles` option we managed to get this number down to 15 VM at a given time, but there seems to be little to no documentation explaining this option.

**Comment by christian-bromann** [comment]
@nickalto this is not a WebdriverIO option.
