### ISSUE TITLE
Implement "type" method as in wd

### ISSUE THREAD

**Issue by DudaGod** [webdriverio/webdriverio#2186]
## The problem

Hello.
I have a problem. I need to send keystroke event (Shift + ?) for the unfocused element. In fact for the whole body. It is not working:
```js
const webdriverio = require('webdriverio');

var browser = webdriverio.remote({
    host: 'some-host',
    port: '4444',
    path: '/wd/hub',
    desiredCapabilities: {
        browserName: 'firefox',
        version: '46'
    }
});

return browser
    .init()
    .url('https://github.com')
    .keys('\uE008 ?')
    .saveScreenshot('1.png')
    .catch((e) => console.log(e))
    .end();
```

This is what is saved to the image:
![2](https://user-images.githubusercontent.com/5900697/28017770-5a34fc84-6583-11e7-8620-8134923decda.png)

In turn, the client wd for such cases provides a method "type":
```js
const wd = require('wd');
const path = require('path');

const browser = wd.promiseChainRemote('http://some-host:4444/wd/hub');

browser
    .init({
        browserName: 'firefox',
        version: '46'
    })
    .get('https://github.com')
    .then(() => browser.elementByCssSelector('body'))
    .then((element) => browser.type(element, '\uE008 ?'))
    .then(() => browser.saveScreenshot(path.resolve('1.png')))
    .then(() => browser.quit())
    .done();
```

This is what is saved to the image:
![1](https://user-images.githubusercontent.com/5900697/28017857-a3fa26c8-6583-11e7-806d-6ab2791d3d94.png)

## Environment

* WebdriverIO version: ^4.8.0
* Node.js version: 4.5.0

**Comment by DudaGod** [comment]
/cc @christian-bromann what do you think about this problem?
Can we implement this method?

**Comment by christian-bromann** [comment]
This is already implemented:
```js
browser.addValue("body", ["Shift", "?"])
```

**Comment by DudaGod** [comment]
Wow, thank you, it's working 👍
