### ISSUE TITLE
browser.waitUntil timeout not respected on linux (works on Mac?)

### ISSUE THREAD

**Issue by mkj28** [webdriverio/webdriverio#2189]
## The problem

On Mac I see browser.waitUntil take the timeout. But when running on Linux (https://hub.docker.com/r/selenium/standalone-chrome/ + nodeJS etc.) I only see the defaultTimeoutInterval respected. wdio, nodejs etc. seems identical/close on both

wdio.conf.js has:
const defaultTimeoutInterval = 15000;

and

`browser.waitUntil( function() {
    return someElement.isExisting();
},120000,'Element still not existing after 120000ms');
`

## Environment

* WebdriverIO version: v4.6.2 (same on mac)
* Node.js version: v6.11.0 (vs v6.9.2 on Mac)
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):
chromedriver=2.28.455506 (same on Mac)
chrome=59.0.3071.86 (vs 59.0.3071.115 on Mac)
jasmine=2.6.0 (same on Mac)

## Details

Instead of respecting browser.waitUntil timeout I am seeing the jasmine defaultTimeoutInterval respected with:
`Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.` thrown after 15 seconds.

## Link to Selenium/WebdriverIO logs

https://gist.github.com/mkj28/32c1e284706c52a0ab8d1af55402d8b9 - selenium-standalone.txt
https://gist.github.com/mkj28/51cd98d658cc023b5fdedb31c0b8d46b - WDIO.xunit.chrome.latest.0-0.xml

## Code To Reproduce Issue [ Good To Have ]

TBD

**Comment by christian-bromann** [comment]
@mkj28 these are two different timeouts. `defaultTimeoutInterval` will make sure that your spec fails when the commands in there take too long. The waitUntil timeout makes sure that the commands within the waitUntil condition don't take too long. Please also see http://webdriver.io/guide/testrunner/timeouts.html

**Comment by mkj28** [comment]
Got it, still I don't understand when the same code running on one system respects the waitUntil timeout vs the other looks at defaultTimeoutInterval on the other?

**Comment by christian-bromann** [comment]
Hard to tell, could be many things

**Comment by mkj28** [comment]
To close the loop here - it was my timeouts misunderstanding, as @christian-bromann suggested.
I assumed `browser.waitUntil` timeout takes precedence over `jasmineNodeOpts` `defaultTimeoutInterval`. It does not. 

Jasmine's defaultTimeoutInterval sets the timeout for a single spec to finish. That's why my 2-minute wait was ignored.

The way we solved is was by adding something along [these lines](https://github.com/jasmine/jasmine/issues/483):

```
describe('My suite with long test', function() {
  let originalTimeout = jasmine.DEFAULT_TIMEOUT_INTERVAL;

  beforeAll(function() {
    // this suite requires longer timeouts
    jasmine.DEFAULT_TIMEOUT_INTERVAL = 150000;
    });

[tests be here]

afterAll(function() {
    // reverting jasmine timeout to the default
    jasmine.DEFAULT_TIMEOUT_INTERVAL = originalTimeout;
  });
});
```
