### ISSUE TITLE
Screenshots after failed test

### ISSUE THREAD

**Issue by wniemkowski** [webdriverio/webdriverio#2190]
## The problem

I'm trying to take screenshot when test fails, after configuring screenshotPath in wdio.conf.js, it is not taking pictures for exceptions form asserts, so i want to try use afterTest hook for that, but apparently all the other hook for wdio.conf.js are executed, but this one. Could you provide me solution how can i workaround this?

## Environment
* WebdriverIO version: **3.10.10**
* Node.js version: **v6.11.0**
* **Standalone mode**
* if wdio testrunner, running synchronous or asynchronous tests: **asynchronous**
* Additional wdio packages used (if applicable):

1. "wdio-cucumber-framework": "^0.3.1",
2. "wdio-selenium-standalone-service": "^0.0.9",
3. "wdio-spec-reporter": "^0.1.0",
4. "webdriverio": "^4.8.0"

## Details
When i'm configuring test with just mocha test everything works fine, problem is just with cucumber. I would be more then happy with screens taken by webdriverio, but i cannot find any details about its configuration, just to set a path as parameter. 

## Code To Reproduce Issue [ Good To Have ]
its just clean solution configured with configuration from wdio.cmd

**Comment by christian-bromann** [comment]
Cucumber doesn't support afterTest hooks because it doesn't run any "tests". It runs features and steps therefor use afterStep or afterFeature hooks. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by fgiroud** [comment]
Hi, I was able to implement this using this code in `wdio.conf.js`
```javascript
afterStep: function afterStep(stepResult) {
        if (stepResult.status != "passed") {
            var path = browser.options.screenshotPath;
            var featureName = stepResult.step.scenario.uri
                .replace(process.cwd(), "")
                .split("/")
                .join("_")
                .replace(".feature", "");

            var fileName =
                path +
                "/ERROR_" +
                browser.options.desiredCapabilities.browserName +
                featureName +
                ".png";
            browser.saveScreenshot(fileName);
        }
    }
```

**Comment by anhdung237** [comment]
I follow @fgiroud instruction and it works on Cucumber. Thanks.

**Comment by himildesai** [comment]
@fgiroud By any chance can you help make this work for Mocha?

**Comment by treyturner** [comment]
@himildesai check this post for code that works with mocha: https://github.com/webdriverio/webdriverio/issues/269#issuecomment-306342170

**Comment by himildesai** [comment]
@treyturner Thank you, I was able to implement something similar after I opened this ticket.
`  /**
   * Function to be executed after a test (in Mocha/Jasmine) or a step (in Cucumber) starts.
   * @param {Object} test test details
   */
  afterTest(test) {
    const path = require('path');

    // if test passed, ignore, else take and save screenshot.
    if (test.passed) {
      return;
    }

    /*
     * get the current date and clean it
     * const date = (new Date()).toString().replace(/\s/g, '-').replace(/-\(\w+\)/, '');
     */
    const { browserName } = browser.desiredCapabilities;
    const timestamp = new Date().toLocaleString('iso', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      hour12: false
    }).replace(/[ ]/g, '--').replace(':', '-');

    // get current test title and clean it, to use it as file name
    const filename = encodeURIComponent(
      `${
        test.fullTitle.replace(/\s+/g, '-')
      }-${browserName}-${timestamp}`.replace(/[/]/g, '__')
    ).replace(/%../, '.');

    const filePath = path.resolve(this.screenshotPath, `${filename}.png`);

    browser.saveScreenshot(filePath);
  }`

**Comment by millerick** [comment]
`test.passed` does not appear to be set any longer . Any ideas as to what happened to it?

**Comment by astunkojis** [comment]
using `passed` instead of `test.passed` worked for me

**Comment by pmerwin** [comment]
Returns an object now:

this.afterTest = (test, context, {
                error,
                passed,
                retries
            }) => {
                // console.log('err obj', error);
            if (!passed) {
                const testName = test.title.toString().split(' ').join('-');
                const testFailed = path.join(projectConfig.wdio.errors, `Pic_After_Test_Failure_${testName}.png`);
                browser.saveScreenshot(testFailed);
            }
        };

**Comment by ravireddy07** [comment]
I'm doing it in TypeScript. The `browser` variable is not getting recognized.

```
afterTest: async function (test, context, result) {
        if (!result.passed) {
            const screenshot = await browser.takeScreenshot();
            const screenshotPath = path.join(projectPath, 'screenshots', `${test.title.replace(/\s+/g, '_')}.png`);

            // Ensure the directory exists
            fs.mkdirSync(path.dirname(screenshotPath), { recursive: true });

            // Save the screenshot to a file
            fs.writeFileSync(screenshotPath, screenshot, 'base64');

            // Attach screenshot to Allure report
            addAttachment('Screenshot', Buffer.from(screenshot, 'base64'), 'image/png');
        }
    },
```

Any help

**Comment by christian-bromann** [comment]
> I'm doing it in TypeScript. The `browser` variable is not getting recognized.

Make sure you import either the variable via `import { browser } from '@wdio/globals'` or set the types correctly, see also https://webdriver.io/docs/typescript
