### ISSUE TITLE
some functions are not working after client.frame()

### ISSUE THREAD

**Issue by anahit42** [webdriverio/webdriverio#2191]
## The problem
I try to click on element inside a frame. First I switch to it, then do moveToObject() and then click(). 

The problem is, that moving and clocking give no such element error, while waitForExist and isVisible arae working fine.

Here is my code. 
This works fine:
`return browser
            .then(() => browser.waitForExist(Xpaths.frame))
            .then(() => browser.element(Xpaths.frame))
            .then((res) => {
                return browser
                    .frame(res.value)
                    .waitForExist(Xpaths.test);
            })
            .then(() => browser.isVisible(Xpaths.test))
            .then((res) => console.log(res))`

This gives error
`return browser
            .then(() => browser.waitForExist(Xpaths.frame))
            .then(() => browser.element(Xpaths.frame))
            .then((res) => {
                return browser
                    .frame(res.value)
                    .waitForExist(Xpaths.test);
            })
            .then(() => browser.moveToObject(Xpaths.test))`

Also I noticed that browser.element(Xpaths.test) gives error, while browser.elements(Xpaths.test) finds it. 

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: v7.10.0
* [Standalone mode or wdio testrunner]
Standalone
## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
This is probably an issue with moveToObject then. Without logs it is impossible to help and say anything.

**Comment by christian-bromann** [comment]
I've seen this question being posted on our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) channel. If this doesn't bring you any answers you might have asked the wrong question. There is no reason to raise an issue.

**Comment by anahit42** [comment]
I noticed that wherever we use client.element (in moveTo, moveToObject, click), it gives errors and when I try to use client.elements, it finds with the same selector (isVisible for example, waitForExist).

How come this is not an issue? I mean, if some functions work and some does not, isn't it good to understand why it is so. And all these problems raise after client.frame, they work fine in case of default view.

**Comment by anahit42** [comment]
Here is the gist link of the error case. 

https://gist.github.com/anahit42/6a20b0d50cb52cf76e8818691d7f3e25#file-gistfile1-txt

**Comment by christian-bromann** [comment]
> How come this is not an issue?

Because this is not fixable in WebdriverIO. All actions are executed by the browser driver. If this doesn't work as expected it has to be fixed in the driver and not here. Looking at the logs it looks to me as a problem in Chromedriver.

**Comment by christian-bromann** [comment]
@anahit42 one last note: if you really think this is a bug in WebdriverIO proof that it works with a different framework (provide these logs), create an example website and example code that can reproduce the issue. Just posting a couple of code lines and some sentences makes it impossible to fix this or consider this as an issue. This is why I immediately closed this.

**Comment by anahit42** [comment]
Ok, got your point. To open issue I have to provide the working code and logs. 

Just one last question, is there any code example/tests that performs these actions on frames. If they are tested on frame, maybe you could provide the version of chromedriver on which they work? Because the fact is that I'm using webdriverIO and can't perform some actions with it and the idea of using another framework is not compelling )

**Comment by christian-bromann** [comment]
> is there any code example/tests that performs these actions on frames

I don't have any.

> the idea of using another framework is not compelling

I just meant that if you can proof that this certain action works in another framework it might actually be an issue with WebdriverIO. I am not suggesting to switch.
