### ISSUE TITLE
beforeAll retry isn't executing when using a promise chain inside the function hook

### ISSUE THREAD

**Issue by klabak** [webdriverio/webdriverio#2192]
## The problem

Hi,

I'm trying to make use of the retry functionality in the beforeAll hook. I can get it to successfully retry using a generic JS `throw Error('my error')`. But the code I need to execute in the hook requires a promise chain to execute some async code in a sequential order. If I throw an error or do a `Promise.reject('my error')` within the chain the beforeAll will fail properly (so I'm pretty sure I'm not swallowing my error) but it will just fail and not retry. Please see the code below.

## Environment

* WebdriverIO version: 4.6.2,
* Node.js version: 6.9.5
* Using wdio testrunner (synchronous tests)
* Using Jasmine as the test framework (Jasmine 2.5.3)

## Code To Reproduce Issue
```
This works (runs three times, fails twice, passes third time):
var count === 0;
beforeAll(function () {
      browser.logger.info('beforeAll function - Generating test data');
      if (count !== 2) {
         browser.logger.info('beforeAll count: ' + count);
         count = count + 1;
         throw Error('threw an error in beforeAll');
      } else {
         browser.logger.info('beforeAll passed!');
      }
}, 3);

This doesn't work (just runs once and fails):
beforeAll(function () {
      browser.logger.info('beforeAll function - Generating test data');
      // All hooks in wdio are async correct? So I need to return the promise chain so wdio will wait
      return asyncDataSetup().then(function () {
         throw Error('then block error');
         // or return Promise.reject('then block error');
      });
}, 3);
```
Since we use Bluebird I've also tried adding a `.catch()` at the end of the chain and tried the same `throw Error()` or `return Promise.reject()` commands but that didn't work either.

I'm out of ideas mostly due to my lack of knowledge of promises :) Any ideas? Thanks a bunch!

**Comment by christian-bromann** [comment]
If you use sync mode you can't execute commands that return promises. You need to wrap them into a call command so it gets synchronised:

```js
beforeAll(function () {
      browser.logger.info('beforeAll function - Generating test data');
      browser.call(() => asyncDataSetup())
}, 3);
```

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by klabak** [comment]
Hi Christian thanks for the response. 

My asyncDataSetup function returns a promise and in the wdio.conf 'Hooks' section it says that if I return a promise chain in a hook wdio will wait for it. This behavior is what I'm observing running in sync mode even without using browser.call. If I place my promise chain inside the browser.call function I get an unhandled exception being thrown and wdio doesn't retry the hook (the process just exits). I'm probably doing something dumb here so my apologies in advance. I can move this discussion to Gitter if you prefer. Please let me know. Thanks again for the help.
