### ISSUE TITLE
Not possible to use `debug: true` in WDIO config

### ISSUE THREAD

**Issue by NicolasSiver** [webdriverio/webdriverio#2194]
## The problem

It is not possible to use `debug:true` flag in the configuration.

## Environment

* WebdriverIO version: `4.8.0`
* Node.js version: `8.1.4`
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable): `selenium-standalone` _service_ via Safari WebDriver.

## Details

Error: 

> (node:41307) [DEP0062] DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead.

**Comment by christian-bromann** [comment]
Please use a lower node version in the meantime.

**Comment by christian-bromann** [comment]
This will be fixed with #2200. Let's continue this convo there.
