### ISSUE TITLE
wdio configuration helper error

### ISSUE THREAD

**Issue by compostbrain** [webdriverio/webdriverio#2197]
## The problem

I am unable to install wdio using the wdio configuartion helper

## Environment

* WebdriverIO version:4.8.0
* Node.js version:7.10
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):  chai@4.1.0
├─ selenium-standalone@6.5.0

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Selenium/WebdriverIO logs

https://gist.github.com/compostbrain/af360c7be2f84afca4dc054d73e56e25

## Code To Reproduce Issue [ Good To Have ]

https://gist.github.com/compostbrain/ec9e2fa0be0695474049d64dd025b921

**Comment by christian-bromann** [comment]
I am not able to reproduce this:
```sh
$ mkdir tmp
$ cd tmp
$ npm i webdriverio
$ ./node_modules/.bin/wdio config

=========================
WDIO Configuration Helper
=========================

? Where do you want to execute your tests? On my local machine
? Which framework do you want to use? mocha
? Shall I install the framework adapter for you? Yes
? Where are your test specs located? ./test/specs/**/*.js
? Which reporter do you want to use?
? Do you want to add a service to your test setup?
? Level of logging verbosity silent
? In which directory should screenshots gets saved if a command fails? ./errorShots/
? What is the base url? http://localhost

Installing wdio packages:

Packages installed successfully, creating configuration file...

Configuration file was created successfully!
To run your tests, execute:

$ wdio wdio.conf.js
```
