### ISSUE TITLE
Function is not called within the event handler in custom reporter

### ISSUE THREAD

**Issue by Jeff406** [webdriverio/webdriverio#2198]
## The problem
I'm making a reporter to notify test results on Slack. The problem is that the reporter does not work correctly. E.g When I tried to execute 2 specs, only 1 spec result is sent to Slack even 2 outputs are console.log correctly as `console.log(output);`

## Environment

* WebdriverIO version: latest
* Node.js version: 7.10.1
* Mode: [wdio testrunner]
* Running synchronous tests: by config `sync: true`

## Details

`console.log(output)` in my reporter is working, but `slack.webhook(msg)` maybe was not called for the last event.

## Link to Selenium/WebdriverIO logs

I'm not sure this is a bug or I did something wrong with the reporter. I will add all the logs later if it's necessary.

## Code To Reproduce Issue [ Good To Have ]

Here is my custom reporter for slack notification by incoming webhook (based on wdio-spec-reporter)
https://gist.github.com/Jeff406/da130bb1eb3a84b57607f74da0b1c642

**Comment by christian-bromann** [comment]
Since the webhook function is async the process probably was already killed by the time it was about to send the info to slack. Reporter can only work with synchronous code. Might be a better idea to create a service here.

**Comment by Jeff406** [comment]
Thanks christian-bromann for your infomation
