### ISSUE TITLE
WaitForVisible method doesn't work in asynchronous mode

### ISSUE THREAD

**Issue by Ant-VAV** [webdriverio/webdriverio#2201]
## The problem

In async mode (sync: false @ wdio.conf.js) method waitForVisible doesn't work. It always throws TimioutException.

```
Timeout of 10000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.
running chrome
Error: Timeout of 10000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.
    at Timeout.<anonymous> (/Users/ant-vav/WebstormProjects/wdio/node_modules/mocha/lib/runnable.js:232:19)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

In synchronous mode this method works fine.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 6.9.5
* Standalone mode or wdio testrunner: wdio
* if wdio testrunner, running synchronous or asynchronous tests: asynchronous
* Additional wdio packages used (if applicable): wdio-mocha-framework

## Link to Selenium/WebdriverIO logs

https://gist.github.com/Ant-VAV/dd923654cc803af549638253cf8da560

## Code To Reproduce Issue [ Good To Have ]

https://github.com/Ant-VAV/wdio

**Comment by christian-bromann** [comment]
Please see error message:

> Timeout of 10000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.

This has nothing to do with the command. Your test spec is timing out. Please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by Ant-VAV** [comment]
@christian-bromann sorry.
Wrong timeout left after experiments.
I fixed the first message.

Also you can look at attached repo. 

N.B.
The problem with element.waitForVisible chain reproduced only in async mode.
In sync mode all work fine.
