### ISSUE TITLE
BrowserStack example outdated

### ISSUE THREAD

**Issue by bsandhu** [webdriverio/webdriverio#2205]
## The problem

In the new release we have the concept of a BrowserStack service. The existing samples for BrowserStack integration do not show the usage of this service. 

Additionaly, it's unclear how BrowserStack service interacts with BrowserStack local.

Can you update the sample please or give me some hints? Happy to do a PR.

https://github.com/browserstack/webdriverio-browserstack

**Comment by christian-bromann** [comment]
@bsandhu this repo is not maintained by me, please file the issue there. Thanks!
