### ISSUE TITLE
Chrome print emulation setting accessible through webdriver

### ISSUE THREAD

**Issue by rsouthgate** [webdriverio/webdriverio#2206]
Would like to use the visual regression service to check print styles in addition to screen styles. It is good enough just in chrome and I know Chrome devtools has a rendering option of emulating css print media type.

Are these chrome options available inherently through the browser object or does webdriver need to figure out a driver way of turning them on and off?

**Comment by christian-bromann** [comment]
> Are these chrome options available inherently through the browser object or does webdriver need to figure out a driver way of turning them on and off?

No, these are not accessible as long as Chromedriver doesn't allow this. Please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
