### ISSUE TITLE
browser.element.waitForVisible method doesn't work in asynchronous mode

### ISSUE THREAD

**Issue by Ant-VAV** [webdriverio/webdriverio#2208]
## The problem

In async mode (sync: false @ wdio.conf.js) method `browser.element('.selector').waitForVisible()` is broken. It always said that element is not visible.

```
1) Test suit test to fail:
element ("header .header") still not visible after 1000ms
running chrome
Error: element ("header .header") still not visible after 1000ms
    at elements("header .header") - isVisible.js:54:17
    at isVisible("header .header") - waitForVisible.js:73:22
```

In synchronous mode this method works fine.
Also method browser.waitForVisible('.selector') works fine.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 6.9.5
* Standalone mode or wdio testrunner: wdio
* if wdio testrunner, running synchronous or asynchronous tests: asynchronous
* Additional wdio packages used (if applicable): wdio-mocha-framework

## Link to Selenium/WebdriverIO logs

https://gist.github.com/Ant-VAV/dd923654cc803af549638253cf8da560

## Code To Reproduce Issue [ Good To Have ]

https://github.com/Ant-VAV/wdio

**Comment by christian-bromann** [comment]
Looks like the selector propagation is borked when doing this. According to the logs:
```
13:50:48.656 INFO - Executing: [find child elements: 0 [[ChromeDriver: chrome on MAC (37240d8015ba850d7ad878c4f2c0c998)] -> css selector: header .header], By.cssSelector: header .header])
13:50:48.684 INFO - Done: [find child elements: 0 [[ChromeDriver: chrome on MAC (37240d8015ba850d7ad878c4f2c0c998)] -> css selector: header .header], By.cssSelector: header .header]
```
it is looking for a child element `header .header` within `header .header`. Please use
```js
browser.waitForVisible('.selector')
```
in the meantime until this is fixed.

**Comment by christian-bromann** [comment]
This will be fixed in v5.

**Comment by Ant-VAV** [comment]
Wow, it's alive!
