### ISSUE TITLE
Full spec retries with new grid session creation

### ISSUE THREAD

**Issue by avkrash** [webdriverio/webdriverio#2209]
## The problem

At the moment we have it and describe retries (for mocha). 
But what if we have a network problem during test run (selenium grid session timed out or closed by any reason) and test failed, so non of current retries can help.

Is it possible to implement retry on a more global level, which will create new session and start spec again ?

**Comment by christian-bromann** [comment]
WebdriverIO already supports stuff like this, see [connectionretrytimeout](https://github.com/webdriverio/webdriverio/blob/master/docs/guide/getstarted/configuration.md#connectionretrytimeout)
