### ISSUE TITLE
elementActive fails on safari

### ISSUE THREAD

**Issue by rsouthgate** [webdriverio/webdriverio#2210]
## The problem

When using browser.elementActive() on Safari (10.1 OSX Sierra) the safari driver responds with HTTP method 'POST' not supported for command.

## Environment

* WebdriverIO version: 4.8
* Node.js version: 8
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync

## Details

Safari docs indicate that the endpoint is supported: https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/WebDriverEndpointDoc/Commands/Commands.html

POST to session/:sessionid/element/active

yet when I try it I receive the following error

```
HTTP method 'POST' is not supported for command '/session/9AD24968-5F7A-4DC8-8823-DEF49ED25BB5/element/active'.
Command duration or timeout: 13 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'Robins-MacBook-Pro.local', ip: '192.168.1.17', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_60'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, databaseEnabled=true, handlesAlerts=true, version=12603.2.4, cleanSession=true, platform=MAC, nativeEvents=true, locationContextEnabled=false, webStorageEnabled=true, browserName=safari, javascriptEnabled=true, platformName=macOS, cssSelectorsEnabled=true}]
Session ID: 9AD24968-5F7A-4DC8-8823-DEF49ED25BB5
[safari #0-0] Error: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.
[safari #0-0]     at elementActive() - index.js:307:3
```

Same error when using local instance of safari and browserstack safari.

**Comment by jannisg** [comment]
@christian-bromann Hey, I appreciate the quick action on your part here but it seems the "fix" that closes this is essentially just saying that the command isn't supported which is incorrect and not a "solution" for this issue.

The Safari docs clearly show that the endpoint (as a `POST`) is supported by their browser: https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/WebDriverEndpointDoc/Commands/Commands.html

And their docs map back to the Selenium docs which also talk about this being a POST request: https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidelementactive

I don't think the commit you referenced should be closing this ticket:

```javascript
err.message.match(/(did not match a known command|is not supported for command)/)
```

What are your thoughts on this?

**Comment by christian-bromann** [comment]
> What are your thoughts on this?

Currently some browser driver support GET but not POST and some POST and not GET. Therefor we need to have a fallback to stay backwards compatible.
