### ISSUE TITLE
buttonDown + moveToObject + buttonUp not working on browsers other than Chrome

### ISSUE THREAD

**Issue by XRayV5** [webdriverio/webdriverio#2212]
## The problem

I'm using buttonDown + moveToObject + buttonUp combination to achieve click & slide action.
I have seen the deprecation warnings but given there's no replacement for these APIs, I have to stick to this solution.

This combinition [ please see: Code To Reproduce Issue ] works beautifully on Chrome, but all other browsers( ie11, Edge, Safari, firefox ) give no reponse except the error message from firefox: 

"Error: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource. at moveTo("0", 1260, 100) - moveToObject.js:55:22"

I believe the following link refers to the same issue:

#1806 

## Environment

* WebdriverIO version:
"wdio-selenium-standalone-service": "0.0.8",
"webdriverio": "^4.8.0"
* Node.js version: "^7.10.0"
* I tried for Standalone mode and wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: not sure
* Additional wdio packages used (if applicable): "wdio-mocha-framework": "^0.5.10",

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]
```
it('should switch image frames further up on mouse drag', async () => {
		const renderElement = browser.$$('img.app_view')
		const beforeSwitch = browser.elementIdAttribute(renderElement[0].ELEMENT, 'src');
		const viewWidth =  browser.getElementSize('img.app_view', 'width')
		browser.moveToObject('img.app_view', viewWidth, 100)
		browser.buttonDown(0)
		for(let i = 0; i < 50; i++){
			wait(100)
			browser.moveToObject('img.app_view', viewWidth - i * 20, 100)
		}
		browser.buttonUp(0)
		const renderElementAfter = await browser.$$('img.app_view')
		const afterSwitch = await browser.elementIdAttribute(renderElement[0].ELEMENT, 'src');
		assert.notEqual(beforeSwitch.value, afterSwitch.value, 'image.src changes to the current frame showing.')
	})
```

**Comment by christian-bromann** [comment]
> browsers( ie11, Edge, Safari, firefox ) give no reponse except the error message from firefox:

This is because the command is not supported on these browser. There is nothing WebdriverIO can do about this. We will soon implement the Action API which will land in these browsers too.

**Comment by kewgrz** [comment]
@christian-bromann was that ever implemented for FF? I'm running across the issue now.
