### ISSUE TITLE
Intermittent failure to run specs

### ISSUE THREAD

**Issue by dangmai** [webdriverio/webdriverio#2213]
## The problem
I'm running ~400 test cases in about ~100 spec files, and sometimes they're failing with the error: `Error: A request to switch to a different window could not be satisfied because the window could not be found.
`
Here's what's in the stdout:

```
COMMAND: POST http://127.0.0.1:4444/wd/hub/session/5749dd17-650f-4170-b505-23a49b245e34/window/current/size - {"width":1920,"height":1080}
RESULT: {"message":"unknown error: unhandled inspector error: {\"code\":-32000,\"message\":\"No target with given id\"}","type":"RuntimeError","seleniumStack":{"status":13,"type":"UnknownError","message":"An unknown server-side error occurred while processing the command.","orgStatusMessage":"unknown error: unhandled inspector error: {\"code\":-32000,\"message\":\"No target with given id\"}\n  (Session info: chrome=60.0.3112.78)\n  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e ... (1178 more bytes)"}}
COMMAND: POST http://127.0.0.1:4444/wd/hub/session/5749dd17-650f-4170-b505-23a49b245e34/window/rect - {"width":1920,"height":1080}
RESULT: {"message":"unknown error: unhandled inspector error: {\"code\":-32000,\"message\":\"No target with given id\"}","type":"RuntimeError","seleniumStack":{"status":13,"type":"UnknownError","message":"An unknown server-side error occurred while processing the command.","orgStatusMessage":"unknown error: unhandled inspector error: {\"code\":-32000,\"message\":\"No target with given id\"}\n  (Session info: chrome=60.0.3112.78)\n  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e ... (1178 more bytes)"}}
COMMAND: DELETE http://127.0.0.1:4444/wd/hub/session/5749dd17-650f-4170-b505-23a49b245e34/cookie - {}
RESULT: {"message":"no such window: target window already closed\nfrom unknown error: web view not found","type":"RuntimeError","seleniumStack":{"status":23,"type":"NoSuchWindow","message":"A request to switch to a different window could not be satisfied because the window could not be found.","orgStatusMessage":"no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=60.0.3112.78)\n  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de ... (1168 more bytes)"}}
```

Basically it fails right at the beginning of running a spec file, and all the test cases inside that spec file will fail with that exact error.

I have this in my wdio.conf.js:
```
beforeTest: function(test) {
  browser.windowHandleSize({ width: 1920, height: 1080 });
},
```
So that's the first 2 `COMMAND` to Selenium, and then I have a `browser.deleteCookie()` at the beginning of my test case, which accounts for the 3rd `COMMAND`.

This might or might not be a WDIO issue - I can see it being a ChromeDriver or Selenium problem too, but I'm filing it here first in case you have seen it before.

## Environment

* WebdriverIO version: v4.8.0
* Node.js version: v8.1.3
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: asynchronous tests
* Additional wdio packages used (if applicable): `wdio-junit-reporter`, `wdio-mocha-framework`, `wdio-selenium-standalone-service`

**Comment by christian-bromann** [comment]
@dangmai this is indeed not really a WebdriverIO issue. Have you tried to rerun the command in case it fails? I am curious to know because if so we could add this to the internal rerun mechanism that gets triggered in similar cases like stale element errors.

**Comment by dangmai** [comment]
I'm using the mocha adapter, and use `this.retries(2)` for all the `describe` hooks, is that what you mean? That method doesn't work, it still fails with the same error. 

As you can see in the stdout, all 3 commands to selenium fails because the id given is not valid, I doubt that trying the same commands again would help, but I could give it another shot

**Comment by dangmai** [comment]
I'm under the impression that all test cases in a spec file runs in the same selenium session, is that true? If so, is there a way to run them in different sessions (and also run retries in different sessions), so that at least not all test cases fail when I run into this issue?

**Comment by christian-bromann** [comment]
> all test cases in a spec file runs in the same selenium session, is that true?

Yes

> If so, is there a way to run them in different sessions

What do you mean by that? You can use the `reload` command to create a new session within a spec file.

> is that what you mean?

No, I meant something like:
```js
beforeTest: function(test) {
  try {
      browser.windowHandleSize({ width: 1920, height: 1080 });
  } catch (e) {
      // handle this error
  } 
},
```

I don't think WebdriverIO can do anything about this. Feel free to reach out to me on our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have further questions. Thanks!
