### ISSUE TITLE
Location Deprecated 

### ISSUE THREAD

**Issue by anjana-sundaram** [webdriverio/webdriverio#2216]
## The problem

I am trying to use geo location api but it says it has been deprecated. What is the alternate method?

browser.setGeoLocation({latitude: 41.881832,longitude: 13.2017384, altitude: 20.23345})

What is the right method to set Geo location IPs to set and use in the application.

**Comment by christian-bromann** [comment]
> What is the alternate method?

There is non. The WebDriver spec doesn't contain a command for mocking geo locations. It might still work for some browser or mobile simulator/emulators though. I can't tell you what the alternate method is but if all browser driver don't support this command there is no reason why WebdriverIO should keep it in their API.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
