### ISSUE TITLE
Cannot use scoped packages as framework, reporter, service

### ISSUE THREAD

**Issue by dobogo** [webdriverio/webdriverio#2219]
## The problem

Scoped packages (e.g. `@scope/wdio-xxx-service`) cannot be used as a framework, a reporter, or a service.
The reason is that WebdriverIO loads packages named `wdio-xxx-{framework,reporter,service}` (`xxx` is specified in wdio.conf.js).

I tried to write full package name in the `wdio.conf.js` like below:

```javascript
exports.config = {
  ...
  services: ['@scope/wdio-xxx-service'],
  ...
}
```

But got the error:

```
ERROR: Couldn't initialise service "@scope/wdio-xxx-service".
Error: Cannot find module 'wdio-@scope/wdio-xxx-service-service'
```

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 8.2.1

**Comment by christian-bromann** [comment]
Fixed. Will be released with the next version.
