### ISSUE TITLE
Where do I add custom commands using wdio testrunner?

### ISSUE THREAD

**Issue by zig999** [webdriverio/webdriverio#2221]
Hi there!
I have a question regarding the use of custom commands when using the wdio testRunner.
I have described my tests (using mocha) and call their execution using wdio.
Where is the right place to add some custom command in this scenario?

Thanks a lot

**Comment by christian-bromann** [comment]
> Where is the right place to add some custom command in this scenario?

I would not recommend to use custom commands. You should rather put custom logic into [page objects](http://webdriver.io/guide/testrunner/pageobjects.html). However if you for some reason have to create custom commands the best place is within the before hook.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by zig999** [comment]
Thanks a lot. Page objects looks just what I need.
