### ISSUE TITLE
Specify which file (or spec) to run when you also specify the suite

### ISSUE THREAD

**Issue by JulsRicketti** [webdriverio/webdriverio#2226]
## The problem

Hello!

I would like to be able to specify the file while also specifying the suite. This doesn't seem to work right now, it simply ignores the spec I specified and runs everything in the suite.

`wdio wdio/wdio.conf --suite suiteA --spec wdio./test/modeA/someTest.js`

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 6.10.2

## Details

The reason for needing this is that I have an app that runs in different modes, so because of this I have completely different tests and would like to run them separately. 

I have created different npm commands for each mode, which runs their separate wdio.conf files. Within these npm commands, I would also like to specify from which group of files to run, so I don't have to specify them each time I want to run them, but I would like to also keep the option of choosing a single file as opposed to always having to run the entire suite.

Here is a sample of what my package.json file would look like:

   
`"tools:e2e:modeA": "./node_modules/.bin/wdio wdio/wdio.conf.modeA.js  --suite modeA",`
 `"tools:e2e:modeB": "./node_modules/.bin/wdio wdio/wdio.conf.modeB.js  --suite modeB",`

## Code To Reproduce Issue

Should probably be worth showing what my wdio.conf files look like for this specific section. Basically I specify this stuff at wdio.conf.js. So this is what is looks like:

```
...
  specs: [
    './wdio/test/specs/**/*.js'
  ],
  suites: {
    modeA: [
      './wdio/test/specs/modeA/*.js'
    ],
    modeB: [
      './wdio/test/specs/modeB/*.js'
    ]
  },
.... 
```

For wdio.conf.modeA.js and wdio.conf.modeB.js I specify other stuff that is specific to each of the apps mode.

**Comment by christian-bromann** [comment]
Why can't you just run:
```js
wdio wdio/wdio.conf --spec wdio./test/modeA/someTest.js
```
I don't think it makes much sense to specify a spec and the suite at the same time.

**Comment by JulsRicketti** [comment]
It turns out I got around the issue after some configuration changes in my wdio.conf.[mode].js files.

However, the reasoning for it originally was to instead of going through the specification of which files to run in each mode, you could simply add them to that mode's suite and then run that in a single npm command, defined in package.json. That was, later, when running that command you could specify the spec you want to run as opposed to running the whole suite, if that makes sense.

So, for example:
// (in package.json)
```"tools:e2e:modeA": "./node_modules/.bin/wdio wdio/wdio.conf.modeA.js --suite modeA"```

when running the command, you can do:

```npm run tools:e2e:modeA -- --spec wdio/test/someFileInTheSuite.js```

**Comment by christian-bromann** [comment]
I guess that makes sense. So the `spec` argument would surpass the suite argument but then what happens if someone wants to do the opposite?

**Comment by JulsRicketti** [comment]
Hum... I wouldn't think the opposite should be allowed because a suite is a group of specs, so why would you specify a single spec to be run when you want to override it with a suite?

**Comment by christian-bromann** [comment]
Fair enough, I think one way makes definitely more sense than the other. Let's get it implemented.

**Comment by hajarghaem** [comment]
Hello @christian-bromann,
I have 2 suites : "suite1" and "suite2".
In suite1 I have 2 specs: spec1-1.js and spec1-2.js
In suite2 I have 2 specs: spec2-1.js and spec2-2.js
 Now I am going to run just suite2 in a way that spec2-2.js runs before spec2-1.js:

specs: [
        './test/specs/**/*.js'
    ],
	
	    suites: {
			suite1: [
				'./test/specs/spec1-1.js', 
				'./test/specs/spec1-2.js' 
				
			],
			suite2: [
				'./test/specs/spec2-1.js', 
				'./test/specs/spec2-2.js' 
				
			]
        
    },

But the 1- it runs all specs 2- it does not consider the orders.
Could you please let me know your thought?
Thanks in advance,
Hajar

**Comment by mattc41190** [comment]
> Now I am going to run just suite2 (and not suite1 and its specs) in a way that spec2-2.js runs before spec2-1.js 

@hajarghaem typically when writing tests we want to keep them atomic and any state creation we need we would we create for each spec this way the state of the application under test is accurately recorded. Can you explain your use case?

**Comment by christian-bromann** [comment]
Hey,

we update the core architecture of WebdriverIO and with that a lot of implementation details that might make this issue obsolete. Please try with the latest version of WebdriverIO and verify if this still occurs. If so please open a new issue and we will tackle it asap.

Thanks!
