### ISSUE TITLE
Not able to use webdriver.io in VPN based intranet environment

### ISSUE THREAD

**Issue by susnigdha1** [webdriverio/webdriverio#2228]
I am supposed to access the AUT (application under test) over VPN (intranet). During test execution webdriver.io is trying to download the required browser dependencies file, as internet is not available in the VPN environment, it is throwing error message and terminating the test. But when I test any general application in normal internet environment, it is working fine. Please let me know if there is a way to update the dependencies URL for the browsers, so that we can host the required files in our JFrog server in our intranet environment and use the same. Given below the error I encountered over VPN environment.
Error: Could not request headers from https://selenium-release.storage.googleapis.com/3.4/IEDriverServer_x64_3.4.0.zip: Error: connect ECONNREFUSED

**Comment by christian-bromann** [comment]
If WebdriverIO can't access the internet you need to make sure to download at setup the browser and its corresponding driver yourself properly. If the wdio-selenium-standalone-service can find these it won't try to download them. 

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by susnigdha1** [comment]
Hi Christian,
Thank you for quick response. I tried the option too, I have downloaded and installed the browsers in npm, but wdio-selenium-standalone-service is always looking to download the browser drivers from internet. If possible, give me the steps to download and setup the browser locally, so that I can figure out if I missed out any steps.
Regards,
Susnigdha

**Comment by christian-bromann** [comment]
@susnigdha1 I am afraid it will always try to download the drivers (if not already cached). You can place the downloaded at the exact position https://github.com/vvo/selenium-standalone would expect it. Or just start the selenium-standalone server manually and not use this service.
