### ISSUE TITLE
browser.frame() fails to switch focus to different iframes in Firefox 45

### ISSUE THREAD

**Issue by npeceniak** [webdriverio/webdriverio#2232]
## The problem

I have a page with many iframes inside of iframes and the tests I am running require changing the focused iframe a lot. The issue I am running into is that browser.frame() method either fails to switch to the desired frame or it takes a really long time (30+ seconds). Since I am switching frames many times per test this long delay causes a bunch of failures. 

## Environment

* WebdriverIO version: 4.5.0
* Node.js version: Failed on both node version 7.7.3 and 6.11.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):

## Details

I am unable to select and interact with elements within different iframes because I cannot properly switch focus to those iframes when running test with Firefox 45. I am however able to run the same test in Chrome and Safari without issues. I am using the firefox driver built into webdriver. 

The error I am getting is:

> Failed: element ("div.video_control_overlay") still not existing after 5000ms
> running firefox
> Error: element ("div.video_control_overlay") still not existing after 5000ms
>     at elements("div.video_control_overlay") - isExisting.js:46:17
>     at isExisting("div.video_control_overlay") - waitForExist.js:67:22

The element that the test is looking for is inside of an iframe which is why it cannot be found. I have used the browser.debug() REPL to run the browser.frame() command that my tests use and it seems to hang on that command. Sometimes if I let run it will eventually switch to the frame but it takes a over 30 seconds. 

## Link to Selenium/WebdriverIO logs

https://gist.github.com/npeceniak/03d21a9d6a7c1f7af09dda21e97da17a

## Code To Reproduce Issue [ Good To Have ]
```
        const strSurrogateFrameSelector = 'iframe[id^=spotx_iframe]';
        browser.frame(); // Make sure we start at the top frame 
        browser.waitForExist(strSurrogateFrameSelector, 5000);
        browser.frame($(strSurrogateFrameSelector).value);
        browser.waitForExist(".video_control_overlay", 5000);
        browser.click('div.video_control_overlay');

```

**Comment by christian-bromann** [comment]
Can you provide firefoxdriver logs? I am afraid that this is an issue that can't be fixed in WebdriverIO.

**Comment by npeceniak** [comment]
Here are the regular webdriverio logs for the tests this issue is causing to fail. https://gist.github.com/npeceniak/03d21a9d6a7c1f7af09dda21e97da17a

How would I go about getting the specific logs for the firefox driver itself?

**Comment by christian-bromann** [comment]
> Here are the regular webdriverio logs for the tests this issue is causing to fail.

They don't help.

> How would I go about getting the specific logs for the firefox driver itself?

Please see Geckodriver docs

**Comment by npeceniak** [comment]
Firefoxdriver logs here - https://gist.github.com/npeceniak/2dc7520db30bcea2c4fc4c2e5de92037

**Comment by npeceniak** [comment]
I ended up updating my selenium version from 2.54 to 3.4 and using marrionette for the firefox browser which fixed my issue.
