### ISSUE TITLE
browser.click in iFrame (Chrome)

### ISSUE THREAD

**Issue by Luc-Bucher** [webdriverio/webdriverio#2233]
## The problem

Should I try to interact with an element (e.g. click) inside an iFrame using Chrome, I get the following error:

### With browser.debug:
```
Error: An unknown server-side error occurred while processing the command.
    at Object.wait (C:\tfs\Trainees\LB\Reports-Tests\node_modules\fibers\future.js:449:15)
    at Object.click (C:\tfs\Trainees\LB\Reports-Tests\node_modules\wdio-sync\build\index.js:344:27)
    at evalmachine.<anonymous>:1:9
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.runInThisContext (vm.js:97:38)
    at C:\tfs\Trainees\LB\Reports-Tests\node_modules\webdriverio\build\lib\commands\debug.js:54:43
    at C:\tfs\Trainees\LB\Reports-Tests\node_modules\wdio-sync\build\index.js:205:29
    at elementIdClick("2") - C:\tfs\Trainees\LB\Reports-Tests\node_modules\webdriverio\build\lib\commands\click.js:20:22
```
### In regular use:

```
 Element <iframe ng-show="!failureReason" seamless="seamless" frameborder="0" class="viewer" aria-hidden="false" cd_frame_id_="c34f981c26ae93c07f9481151e9d491d" ng-src="/ReportServer/Pages/ReportViewer.aspx?%2Fswissisol-dev%2FCatalog%2FExport%20Produktgruppe&amp;rc:showbackbutton=true" src="/ReportServer/Pages/ReportViewer.aspx?%2Fswissisol-dev%2FCatalog%2FExport%20Produktgruppe&amp;rc:showbackbutton=true"></iframe> is not clickable at point (151, 127). Other element would receive the click: <section class="breadcrumbs">...</section>
```

## Environment

* WebdriverIO version: 5.3.0
* Node.js version: 6.11.0
* WDIO-Standalone with Selenium-Standalone
* Chrome version: 59.0.3071.115

## Details

- [Gist Snippet](https://gist.github.com/nickytonline/e196070529670b4aba46a37c96b9ddef)

I use chrome only, but it seems to be working fine on Firefox.
The Website that I want to Test is the SQL Server Reporting Service 2016:

I already made a Test-Website consisting of an iFrame containing a Button, where everything seemed to work fine.

Depending on the Element, it  either returns the above shown error or does not do anything at all: 
As [nickytonline](https://gist.github.com/nickytonline/e196070529670b4aba46a37c96b9ddef) described in his post, the error does not always occur.

All elements inside the iFrame can be found, browser.frame() does not return errors either.

## Code To Reproduce Issue
```
browser.url(_XYZ_);

browser.waitForExist('iframe.viewer');
browser.frame(browser.element('iframe.viewer').value);

return this.waitForLoadingScreen();
console.log(browser.element('#ReportViewerControl_ctl04_ctl03_ddValue'));
var select = browser.element('#ReportViewerControl_ctl04_ctl03_ddValue');
select.click(); // Returns error
```

**Comment by christian-bromann** [comment]
Can you please provide Chromedriver logs?

> WebdriverIO version: 5.3.0

There is no such version

**Comment by Luc-Bucher** [comment]
Excuse me, i accidentaly wrote the npm-Version, 
The WDIO-Version is **4.6.2**

Log:
[chrome.2017-08-08T12-02-02.3424.log.txt](https://github.com/webdriverio/webdriverio/files/1207945/chrome.2017-08-08T12-02-02.3424.log.txt)

**Comment by christian-bromann** [comment]
> chrome.2017-08-08T12-02-02.3424.log.txt

These are not the Chromedriver logs these are the WebdriverIO logs

**Comment by Luc-Bucher** [comment]
Sorry, but I cannot find the location of my chromedriver logs.
I probably should mention that I'm using windows and thus not chromium.

**Comment by christian-bromann** [comment]
> I probably should mention that I'm using Windows and thus not chromium.

That doesn't matter. Please have a look into the Chromedriver docs.

**Comment by adamgins** [comment]
@Luc-Bucher wondering if you resolved this. 

I seem to have a similar issue. I can change into an iframe with `browser.frame` and I can see some links eg `$("a").click()` seems to work. But when I try find some ID eg `browser.click("#someID")` or some other variant I get an error, something to the effect of the query being `invalid` or `illegal`.

I can execute the same command from the console when not in an iframe.

So I am thinking perhaps it's some sort of cross domain security issue?

BTW, I am using `chimp` and `meteor` so I was not 100% clear on how to get the Chromedriver logs to show.

**Comment by christian-bromann** [comment]
I will close this because I am afraid that this is Chrome specific and WebdriverIO can not really do anything to fix this.

**Comment by adamgins** [comment]
@christian-bromann are you referring to my issue too?

**Comment by christian-bromann** [comment]
No your issue seem different

**Comment by adamgins** [comment]
ok,thanks. ... if you have a cheatsheet on how to get more logging info for my issue I can open a separate issue... if I can't find out how to resolve.

**Comment by christian-bromann** [comment]
> BTW, I am using chimp and meteor so I was not 100% clear on how to get the Chromedriver logs to show.

@adamgins id doesn't matter which webdriver client you run it matters how you run the Selenium server. There are docs for each driver describing how to capture logs.

**Comment by Luc-Bucher** [comment]
Hello again, I was able to create a chromedriver-logfile:

[chromedriver.log.txt](https://github.com/webdriverio/webdriverio/files/1248281/chromedriver.log.txt)

**Comment by christian-bromann** [comment]
@Luc-Bucher please see the log error. The click doesn't work because there is another element laying over the iframe:

```
ClickElement unknown error: Element <iframe ng-show="!failureReason" seamless="seamless" frameborder="0" class="viewer" aria-hidden="false" ng-src="/ReportServer/Pages/ReportViewer.aspx?%2F[database]%2FCatalog%2FTarif%20Berechnungsgrundlagen&amp;rc:showbackbutton=true" src="/ReportServer/Pages/ReportViewer.aspx?%2F[database]%2FCatalog%2FTarif%20Berechnungsgrundlagen&amp;rc:showbackbutton=true" cd_frame_id_="7193da6285e480452911f4a5ae63ad8b"></iframe> is not clickable at point (494, 120). Other element would receive the click: <section class="breadcrumbs">...</section>
```

Closing as this is not a WebdriverIO issue.

**Comment by Luc-Bucher** [comment]
@adamgins 
If you want a pretty unclean workaround to push your testing forward until you found a clean solution;
open the iFrame's source directly:

`browser.url(browser.getAttribute('iframe', 'src'));`

**Comment by christian-bromann** [comment]
Also if you want to interact with an element within the iframe you have to switch to that using the `frame` command. Please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have more questions.
