### ISSUE TITLE
Allow installing webdriverio without fibers

### ISSUE THREAD

**Issue by alippai** [webdriverio/webdriverio#2234]
## The problem

Fibers is a hard to manage library across various environments (see https://github.com/nodejs/node-gyp).

## Environment

Using grunt-webdriverio with *sync turned off*

## Details

We'd really appreciate if webdriverio didn't depend (npm) on fibers by default.

**Comment by alippai** [comment]
Oh, I forgot that we are using mocha tests.
The dependency chain is wdio-mocha-framework -> wdio-sync -> fibers.

**Comment by christian-bromann** [comment]
If you really don't want to install fibers just us webdriverio without testrunner. Fibers is an essential part of the test runner and we are not planning to remove it.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by alippai** [comment]
I didn't realize it's just a devDependency. Thank you!
