### ISSUE TITLE
Q: Custom commands - when does selectorExecute() return a promise an when not?

### ISSUE THREAD

**Issue by silkentrance** [webdriverio/webdriverio#2235]
## The problem

Looking at your code for isVisibileWithinViewport I decided to implement a custom command that is basically the same but also tests for an element being fully contained in the viewport and not to overflow it.

In your code lib/commands/isVisibleWithinViewport.js you call upon this.selectorExecute() and expect it to return a promise.
I have copied your code, renamed a bit here and there and then hooked the command into the browser instance using browser.addCommand().

Now, when I make use of this new command, it will give me an exception stating that the value returned by selectorExecute() does not have a method called 'then'.

Checking in on the value returned by selectorExecute() it turns out to be just a plain boolean and not a promise, meaning, that basically my routine is working just fine lest the missing promise.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 8.1.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):

## Details

see above.

## Link to Selenium/WebdriverIO logs

see above.

## Code To Reproduce Issue [ Good To Have ]

see lib/commands/isVisibleWithinViewport.js and lib/scripts/isWithinViewport.js
for the gist of it

(using the boilerplate project you provide)

plus the following boilerplate in lib/support/checks/checkFitsIntoViewport.js

```
import fitsIntoViewport from 'lib/support/commands/fitsIntoViewport';
browser.addCommand('fitsIntoViewport', fitsIntoViewport);
```

**Comment by christian-bromann** [comment]
@silkentrance custom commands work internally different that other commands from the API. All commands inside are synchronous like every other command. This is intentional.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
