### ISSUE TITLE
afterTest hook is not called when there is an exception on before hook

### ISSUE THREAD

**Issue by marcelas** [webdriverio/webdriverio#2239]
## The problem
The afterTest hook is never called if something fails on the before hook.

## Environment
* WebdriverIO version:4.8.0
* Node.js version:6.10.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: synch
* Additional wdio packages used (if applicable): selenium-standalone and mocha

## Details
I am currently using afterTest to capture logs and debugging information on failure, but a few times I get nothing logged because there is a failure on the before hook.

## Link to Selenium/WebdriverIO logs
On success:
run before test
run test
․after test called
run after test
1 passing (4.70s)

On failure:
run before test
run after test
F
0 passing (4.10s)
1 failing

1) fail on before "before all" hook:
the string "oh no" was thrown, throw an Error :)
running chrome
Error: the string "oh no" was thrown, throw an Error :)
    at Runner.fail (app/node_modules/wdio-mocha-framework/node_modules/mocha/lib/runner.js:233:11)
    at Runner.failHook (app/node_modules/wdio-mocha-framework/node_modules/mocha/lib/runner.js:273:8)
    at app/node_modules/wdio-mocha-framework/node_modules/mocha/lib/runner.js:326:16
    at done (app/node_modules/wdio-mocha-framework/node_modules/mocha/lib/runnable.js:295:5)
    at pp/node_modules/wdio-mocha-framework/node_modules/mocha/lib/runnable.js:359:11
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)

## Code To Reproduce Issue [ Good To Have ]
```js
beforeFail.js
describe('fail on before', () => {
  before(() => {
    console.log('run before test');
    throw 'oh no';
  });

  it('Can create a conversion tag', () => {
    console.log('run test');
  });

  after(() => {
    console.log('run after test');
  });
});
```

wdio.conf.js
```
exports.config = {
    host: '0.0.0.0',
    port: 4444,
    path: '/wd/hub',
    services: ['selenium-standalone'],
    specs: [
        './beforeFail.js'
    ],
    // Patterns to exclude.
    exclude: [
    ],
    maxInstances: 10,
    capabilities: [{
        browserName: 'chrome'
    }],
    sync: true,
    logLevel: 'silent',
    coloredLogs: true,
    deprecationWarnings: true,
    screenshotPath: 'shots',
    // gets prepended directly.
    baseUrl: 'http://localhost:8080',
    bail: 0,
    waitforTimeout: 1000,
    plugins: {
    },
    framework: 'mocha',
    reporters: ['dot'],
    reporterOptions: {
        outputDir: './'
    },
    mochaOpts: {
        ui: 'bdd'
    },
    afterTest: function (test) {
      console.log('after test called');
    },
};
```

**Comment by marcelas** [comment]
This turned out to be unrelated to webdriver, but related to the Mocha hooks behavior instead. According to the documentation: https://github.com/mochajs/mocha/blob/2bc9c4d1d638c8a95250757dd23724f788918abe/lib/runner.js

 * Hook failures work in the following pattern:
 * - If bail, then exit
 * - Failed `before` hook skips all tests in a suite and subsuites,
 *   but jumps to corresponding `after` hook
 * - Failed `before each` hook skips remaining tests in a
 *   suite and jumps to corresponding `after each` hook,
 *   which is run only once
 * - Failed `after` hook does not alter
 *   execution order
 * - Failed `after each` hook skips remaining tests in a
 *   suite and subsuites, but executes other `after each`
 *   hooks

So this seems to be expected from description above, but it would be nice to include this on the web driver io documentation as well.

**Comment by christian-bromann** [comment]
> So this seems to be expected from description above, but it would be nice to include this on the web driver io documentation as well.

Make a proposal and we can discuss about it
