### ISSUE TITLE
Visual Regression: BrowsersWidth coming as null

### ISSUE THREAD

**Issue by KenzoM** [webdriverio/webdriverio#2241]
## The problem

Following through the example provided by [WebDriver Dcoumentation on Visual Regression](http://webdriver.io/guide/services/visual-regression.html) as well [Kevin Lamping's YouTube tutorial](https://www.youtube.com/watch?v=nmpXe29n-YA), I am receiving `var browserWidth` as `null` in the function `VisualRegressionCompare`, which is located in the **wdio.conf.js**.

In addition, it only takes the default width snapshot to perform the Visual Regression

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 6.6.0
* [Standalone mode or wdio testrunner] wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous 
* Additional wdio packages used (if applicable): Visual Regression

## Details

Describe in more detail the problem you have been experiencing, if necessary.

The example provided in the documentation: 

```
function getScreenshotName(basePath) {
  return function(context) {
    var type = context.type;
    var testName = context.test.title;
    var browserVersion = parseInt(context.browser.version, 10);
    var browserName = context.browser.name;
    var browserWidth = context.meta.width;
    return path.join(basePath, `${testName}_${type}_${browserName}_v${browserVersion}_${browserWidth}.png`);
  };
}
```

`var browserWidth` comes as null. It appears that if I add `option {}` to `checkElement` in my tests, it lives in `context.options.width` not `context.meta.width`. Furthermore, it only takes one snap shot (the default width) to perform the visual regression.

## Code To Reproduce Issue [ Good To Have ]

**test/specs/spec.js**

```
var assert = require('assert');
let expect = require('chai').expect;


function expectGoodThings(results) {
    results.forEach((result, idx) => expect(result.isExactSameImage, `Image ${idx} is not the same`).to.be.true);
}

function assertDiff(results) {
    results.forEach((result) => assert.ok(result.isExactSameImage));
}

const width = [200, 1600];



describe('testing with Regression)', () => {

    it.only('should take comparison of screenshot and pass since they are same', () => {
        browser.pause(7000);
        // take reference
        let example = browser.checkElement('#maincontent', {
            width
        })

        let report = browser.checkElement('#maincontent', {
             width
         })

        // expectGoodThings(report)
    })	
}
```

As far as wdio.conf.js, it is pretty much default other than adding this additional properties to connect with ChromeDriver :

```
    // This is for connecting to chromedriver 
    port: '9515',
    path: '/',


    visualRegression: {
        compare: new VisualRegressionCompare.LocalCompare({
            referenceName: getScreenshotName(path.join(process.cwd(), 'screenshots/reference')),
            screenshotName: getScreenshotName(path.join(process.cwd(), 'screenshots/screen')),
            diffName: getScreenshotName(path.join(process.cwd(), 'screenshots/diff')),
            misMatchTolerance: 0.01,
        }),
        viewportChangePause: 5000,
        widths: [320, 480, 640, 1024],
        orientations: ['portrait'],
    },

```
<img width="639" alt="context console" src="https://user-images.githubusercontent.com/10217112/29295044-34e7522a-8107-11e7-92c1-73ffab6fb7ee.PNG">

**Comment by TuHuynhVan** [comment]
@KenzoM 
Please use ```context.meta.viewport.width```

To make sure, please ```console.log(context)``` , you will see more info.

**Comment by KenzoM** [comment]
@TuHuynhVan , this is will only give one width, which I believe it's the default width.

Ideally, I would like to take screenshots different screen widths (e.g. for responsive design tests)

**Comment by christian-bromann** [comment]
Please look at https://github.com/zinserjan/wdio-visual-regression-service#configuration. The configuration should be
```js
viewports: [{ width: 320, height: 480 }, { width: 480, height: 320 }, { width: 1024, height: 768 }],
```

**Comment by KenzoM** [comment]
@christian-bromann Thanks for the reply!

Perhaps we should update the documentation in the [WebdriverIO's Visual Regression Page](http://webdriver.io/guide/services/visual-regression.html) to avoid future confusion  :)

**Comment by TuHuynhVan** [comment]
@christian-bromann 
https://github.com/webdriverio/webdriverio/pull/2244
