### ISSUE TITLE
browser.getUrl(...).indexOf is not a function

### ISSUE THREAD

**Issue by rycornell** [webdriverio/webdriverio#2242]
## The problem

When running tests, sometimes the error `browser.getUrl(...).indexOf is not a function` occurs.

## Environment

* WebdriverIO version: 4.8.0 (but not sure because running `wdio --version` says 4.6.2)
* Node.js version: 7.7.2
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Standalone
* if wdio testrunner, running synchronous or asynchronous tests: 
* Additional wdio packages used (if applicable):
wdio-jasmine-framework 0.3.1
wdio-selenium-standalone-service 0.0.9
wdio-spec-reporter 0.1.0

## Details

When running tests, sometimes calls to `browser.getUrl()` results in the error `browser.getUrl(...).indexOf is not a function`.  I have tried to assign the result of browser.getUrl() to a variable, but that does not work either.  i.e. 
    
    var currentUrl = browser.getUrl();
    currentUrl.indexOf('http://test.com');  // still throws browser.getUrl(...).indexOf is not a function

   The behavior is inconsistent and I haven't been able to narrow down a way to consistently reproduce it.

## Code To Reproduce Issue [ Good To Have ]

    if (browser.getUrl().indexOf('http://test.com') === -1) {
        browser.url('http://test.com');
    }

**Comment by rycornell** [comment]
I'm going to close this issue because it is not a problem with webdriverio, but a problem with my ability to write jasmine tests.  The call to `browser.getUrl()` was floating in a `describe` block.  It needed to be wrapped in a `beforeAll` block.  Here is how to reproduce it:

This test suite will throw the error:

    describe("Test Suite", () => {
        beforeAll(() => {	
            if (browser.getUrl().indexOf('http://baseurl.com') === -1) {
                browser.url('http://baseurl.com');
            }		
        });

        describe("Test A", () => {
            // this is the line that causes the error
            // this code needs to be wrapped in a beforeAll block
            if (browser.getUrl().indexOf('http://baseurl.com') === -1) {
                browser.url('http://baseurl.com');
            }	
        });
    });

This test suite will not throw the error:

    describe("Test Suite", () => {
        beforeAll(() => {	
            if (browser.getUrl().indexOf('http://baseurl.com') === -1) {
                browser.url('http://baseurl.com');
            }		
        });

        describe("Test A", () => {
            beforeAll(() => {
                // this works because it is wrapped in a beforeAll block
                if (browser.getUrl().indexOf('http://baseurl.com') === -1) {
                    browser.url('http://baseurl.com');
                }	
            });
        });
    });

**Comment by Gobliins** [comment]
I face the same problem inside a before() block while writing mocha tests...
