### ISSUE TITLE
webdriver should follow any operations that open a new window/tab

### ISSUE THREAD

**Issue by cameronbraid** [webdriverio/webdriverio#2245]
## The problem

I am trying to test multiple tab based navigation.  Ideally I would like webdriver to follow any window creations via window.open or targeted links so that browser.windowHandle returns the current window handle as per the docs. The controlled browser does in fact show the new tab, but browser.windowHandle returns the opener window's handle which is not the current window's handle

**Comment by christian-bromann** [comment]
Feel free to propose a PR

**Comment by christian-bromann** [comment]
Closing this as I don't see any activity here. I doubt that this can be handled by WebdriverIO and should rather be addressed in the browser driver.
