### ISSUE TITLE
await in repl?

### ISSUE THREAD

**Issue by lgandecki** [webdriverio/webdriverio#2248]
## The problem

when using the repl in the async wait (without wdio runner), we can't run await/async which makes it harder to debug the code that we write using await/async.  It's a bit confusing, because, for example:
> browser.elements('p')
{ sessionId: 'ec98f130f5d25cf75d74c884a4e0551d',
  status: 0,
  value: 
   [ { ELEMENT: '0.45944770378780775-1',
       'element-6066-11e4-a52e-4f735466cecf': '0.45944770378780775-1' } ],
  selector: 'p' }
but
> browser.elements('p').value
>
is undefined. The tests are frequently written/debugged by not the most technical coders, so they can easily understand the need of adding await (especially if they write it in the code itself already), but having them write .then in the repl and use await in code makes it just weird.

Looks like this might come in a future node version:
https://github.com/nodejs/node/issues/13209
especially since google implemented it in chrome:
https://twitter.com/umaar/status/897408737694109697

Meanwhile, there are programmatic solutions to this, that overwrites the repl.eval: 
https://github.com/skyrising/await-repl/blob/master/index.js

We could use await-repl when running in async mode, or just reuse parts of this code ourselves.

Thoughts?

**Comment by christian-bromann** [comment]
Feel free to propose a PR

**Comment by christian-bromann** [comment]
I think we should rely on Node.js [experimental repl await](https://nodejs.org/dist/latest-v10.x/docs/api/repl.html#repl_await_keyword) and don't implement something custom. Closing.
