### ISSUE TITLE
init() can't override the appium Capabilities

### ISSUE THREAD

**Issue by ajaankur** [webdriverio/webdriverio#2249]
##init() function is not creating a new session

 I am working with webdriverio appium service. As webdriverio launch a default session with Capabilities which are mentioned in wdio.conf.js. But i want to run chrome(browser) while my current test is running on app. So how can I launch chrome without exiting from my current test. 

it('test', function () {

        before(function(done){
            browser.init([{
                browserName: "chrome"}]);
        });
        browser.url('https://google.com'); 
        /* code for app testing */
    });

**Comment by christian-bromann** [comment]
> So how can I launch chrome without exiting from my current test.

You can't just open a new session within your test. Why would you even want to do that? Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) so we can continue the conversation. This is not necessary an issue.
