### ISSUE TITLE
Chrome shows "data:" in address bar

### ISSUE THREAD

**Issue by ybouhjira** [webdriverio/webdriverio#2250]
## The problem

My script runs nicely on firefox but I can't make it run on chrome. I want to run it on chrome in headless mode. 
The chrome window opens with `data:` and stops.
![screenshot from 2017-08-20 16 45 59](https://user-images.githubusercontent.com/3225392/29496267-10b67d76-85c7-11e7-8b10-e3450bb503ce.png)

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 6.11.2
* `java -jar selenium-server-standalone-3.0.1.jar`
* ChromeDriver v2.9.248304 in `/usr/bin/chromedriver`
* Chrome  version 60.0.3112.101

## Details
I added `ignore-certificate-errors` because I get this:
![screenshot from 2017-08-20 16 45 06](https://user-images.githubusercontent.com/3225392/29496262-fa8b1c8c-85c6-11e7-89be-725678971a5f.png)

## Link to Selenium/WebdriverIO logs

[Selenium logs gist](https://gist.github.com/ybouhjira/6b624fc58f57cc396b3b7b08e6ef9b26)

## Code To Reproduce Issue [ Good To Have ]

```js
var webdriverio = require('webdriverio');
var options = {
    desiredCapabilities: {    
        browserName: 'chrome',
        chromeOptions: {
            binary: '/usr/bin/google-chrome',
            args: ['healdess', 'disable-gpu'],
            excludeSwitches: ["ignore-certificate-errors"]
        }
    }
};

const theClient = webdriverio
    .remote(options)
    .init()
    .url('https://www.google.com');
```

**Comment by janwiemers** [comment]
There is a typo in headless :)

**Comment by christian-bromann** [comment]
Good catch @janwiemers

**Comment by ybouhjira** [comment]
I fixed the typo and now it doesn't even start chrome

[Log gist](https://gist.github.com/ybouhjira/834ff6d103928a8e6974c014425c09cb)

**Comment by christian-bromann** [comment]
What is your chromedriver version? Make sure you have the latest.

**Comment by ybouhjira** [comment]
`v2.9.248304`

**Comment by ybouhjira** [comment]
I tested with the simple code which works with firefox but not with chrome
```js
const webdriverio = require('webdriverio');
const options = {
    desiredCapabilities: {    
        browserName: 'chrome',
        chromeOptions: {
            binary: '/usr/bin/google-chrome',
            args: ['headless', 'disable-gpu'],
            excludeSwitches: ["ignore-certificate-errors"]
        }
    }
};

webdriverio
    .remote(options)
    .init()
    .url('https://www.google.com')
    .getTitle()
    .then(title => {
        console.log(title);
    });
```
for firefox I use
```js
const firefoxOptions = {
    desiredCapabilities: {    
        browserName: 'firefox'
    }
}
```

**Comment by christian-bromann** [comment]
Please update your version to [v2.31](https://chromedriver.storage.googleapis.com/index.html?path=2.31/)

**Comment by ybouhjira** [comment]
It works :smile: Thank you very much sir

**Comment by elghailani** [comment]
I was struggling with the same issue, then I realised that I forgot to start the test with :

`$I->amOnPage('/');`

definitely to try before digging deeper.
