### ISSUE TITLE
executing js in the tested page before others <scripts> ?

### ISSUE THREAD

**Issue by jeromeetienne** [webdriverio/webdriverio#2251]
i would like to execute my own javascript in the tested page before any other javascript.

so from my spec.js i would like to do browser.url(myURL) and have my own javascript to be pushed in this page, before the javascript of the page is executed.

Not sure to be clear..

**Comment by christian-bromann** [comment]
> so from my spec.js i would like to do browser.url(myURL) and have my own javascript to be pushed in this page, before the javascript of the page is executed.

This is not possible with WebDriver. However you can start Chrome with your own extension that could contain a contentscript which will get executed before everything else.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
