### ISSUE TITLE
Browserstack tests in parallel

### ISSUE THREAD

**Issue by codeclown** [webdriverio/webdriverio#2252]
## The problem

If two or more people/machines run webdriverio-tests connected to the same Browserstack-account simultaneously, all but the latest test run begin failing. The reason seems to be port collision.

There is a note about lacking `localIdentifier` support for Browserstack:
http://webdriver.io/guide/services/browserstack.html#Known-Issues

I'm not sure if that note directly implies that it is not possible to run tests from multiple machines simultaneously, while using one Browserstack-account. Hence this issue report.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 6.11.2
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): testrunner
* if wdio testrunner, running synchronous or asynchronous tests: asynchronous tests
* Additional wdio packages used (if applicable): wdio-mocha-framework, wdio-browserstack-service

## Details

Two machines start the tests using the same Browserstack-account. One of them will start failing. Screenshots from Browserstack show the browser displaying a "Couldn't connect to localhost:12345" message.

**Comment by codeclown** [comment]
`'browserstack.local': true` is in the config.

Setting `localIdentifier` doesn't help.

```js
onPrepare: (config, capabilities) => new Promise((resolve, reject) => {
  exports.bs_local = new browserstack.Local()
  exports.bs_local.start(
    {
      key: BROWSERSTACK_KEY,
      localIdentifier: `foobar_${Date.now()}`
    },
    error => {
      if (error) return reject(error)

      // Start test
      // ...

      resolve()
    }
  )
})
```

Result:

```
ERROR: [browserstack.local] is set to true but local testing through BrowserStack is not connected.
Error: [browserstack.local] is set to true but local testing through BrowserStack is not connected.
ERROR: [browserstack.local] is set to true but local testing through BrowserStack is not connected.
[...]
```

**Comment by christian-bromann** [comment]
@codeclown it looks like you need to set host and port to bs local. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by codeclown** [comment]
Thank you for the clarification. I was not sure if this is a bug and/or documentation flaw or not, hence the issue.

**Comment by codeclown** [comment]
We managed to solve this issue. For anyone who might end up here from Google, etc., here's a minimized version of our config-file with all the relevant details:

```js
const localIdentifier = `foobar_${Date.now()}`

exports.config = {
  user: BROWSERSTACK_USER,
  key: BROWSERSTACK_KEY,
  capabilities: [
    {
      browser: 'Chrome',
      browser_version: '58.0',
      'browserstack.local': true,
      'browserstack.localIdentifier': localIdentifier
    }
  ],
  onPrepare: (config, capabilities) => new Promise((resolve, reject) => {
    exports.bs_local = new browserstack.Local()
    exports.bs_local.start({ localIdentifier, key: BROWSERSTACK_KEY }, error => {
      if (error) return reject(error)

      // Start server and tests
      // ...

      resolve()
    })
  }),
  onComplete: exitCode => {
    exports.bs_local.stop(() => ({}))
  }
}

```

**Comment by Chaoste** [comment]
Since it's no where documented and it highly relates to this ticket:

WebdriverIO supports a more elegant way of connecting local to browserstack -> `http://webdriver.io/guide/services/browserstack.html`. Basically you just define `browserstackLocal` in `exports.config` to make it work (without an identifier). If you want to add an identifier you need to do it via `browserstackOps`:

```js
const localIdentifier = `foobar_${Math.round(Math.random() * 100)}_${Date.now()}`;
export.configs = {
  user,
  key,
  // use of wdio-browserstack-service for automated local tunneling
  browserstackLocal: true,
  browserstackOpts: {
    localIdentifier,
  },
  ...
```

**Comment by ckurban** [comment]
@Chaoste I have tried above written solution and I got:
`ERROR: [browserstack.local] is set to true but local testing through BrowserStack is not connected.`

Any idea ?

**Comment by tritethunder** [comment]
@ckurban It simply means that you tunnel connection is not established. Check the network logs on browserstack

**Comment by aaron-humerickhouse** [comment]
wdio-browserstack-service does not start browserstackLocal when set to true.  I had to start up my local tunnel prior to running my tests.

**Comment by zubhav** [comment]
> We managed to solve this issue. For anyone who might end up here from Google, etc., here's a minimized version of our config-file with all the relevant details:
> 
> ```js
> const localIdentifier = `foobar_${Date.now()}`
> 
> exports.config = {
>   user: BROWSERSTACK_USER,
>   key: BROWSERSTACK_KEY,
>   capabilities: [
>     {
>       browser: 'Chrome',
>       browser_version: '58.0',
>       'browserstack.local': true,
>       'browserstack.localIdentifier': localIdentifier
>     }
>   ],
>   onPrepare: (config, capabilities) => new Promise((resolve, reject) => {
>     exports.bs_local = new browserstack.Local()
>     exports.bs_local.start({ localIdentifier, key: BROWSERSTACK_KEY }, error => {
>       if (error) return reject(error)
> 
>       // Start server and tests
>       // ...
> 
>       resolve()
>     })
>   }),
>   onComplete: exitCode => {
>     exports.bs_local.stop(() => ({}))
>   }
> }
> ```

Do you utilise a local.runner.js file at all?
