### ISSUE TITLE
Can not run wdio on standalone mode. i am getting flowing error : 

### ISSUE THREAD

**Issue by HabibulHH** [webdriverio/webdriverio#2253]
[13:50:26]  COMMAND     POST     "/wd/hub/session"
[13:50:26]  DATA                {"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":
true,"rotatable":true,"maxInstances":5,"browserName":"chrome","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":
{"url":"http://webdriver.io","version":"4.6.2","name":"webdriverio"}}}
ERROR: connect ECONNREFUSED 127.0.0.1:4444
chrome
Error: connect ECONNREFUSED 127.0.0.1:4444

npm ERR! Test failed.  See above for more details.

**Comment by christian-bromann** [comment]
@HabibulHH make sure you have a selenium server running on `localhost:4444`. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
