### ISSUE TITLE
Best Practice for using Visual Regression's reference images?

### ISSUE THREAD

**Issue by KenzoM** [webdriverio/webdriverio#2254]
I would ask over in Gitter chat room but currently at my work it is blocked :/ 

Anyway, this is more of a question rather than issue:

My current company wanted to an automation framework in their future projects and I proposed Webdriver.io. They seemed to like it, specifically the Visual Regression service.

However, one thing I wanted to know is what would be the best practice to have the reference images be consistent throughout every developer's local computer?

In other words, if we have a GitHub repository of a project, and it has several reference images, what can we do to ensure that when developers fork that repository, the reference images will remain untouched in their local computers? In doing so, it will help ensure that any changes on the styling can be detected via Visual Regression.

I am sure this is not entirely related to Visual Regression but wanted to know what practices/methods you've guys used with it at a higher scale project, especially when you have multiple developers working on the same project. 

Would integrating a third party hosting-image like Firebase would do the job?

Any inputs would be greatly appreciated.

**Comment by christian-bromann** [comment]
Hey @KenzoM,

from my experiences it is worth keeping the baseline images as part of the visual regression test. This has the advantage that every time the developer changes the UI, the visual change it committed too and changes the baseline for all future tests. I did a talk couple of years ago about this, you can watch it here: https://www.youtube.com/watch?v=7mK0QomC4ZU

Feel free to reach out in the Gitter channel for more question. I will close this issue but leave it open for others to comment on.

**Comment by KenzoM** [comment]
Hi @christian-bromann  
Thanks for the input, and thanks for the video talk.

I noticed that in the video talk, you've used WebdriverCSS. Is the WebDriverIO's Visual Regression is the replacement of WebDriverCSS?

If so, at the [talk](https://youtu.be/7mK0QomC4ZU?t=867), I noticed that GitHub was smart enough enough to recognize that the baseline has been updated. Would the Visual Regression be able to do that, despite having the same file name that was generated?

**Comment by christian-bromann** [comment]
> I noticed that in the video talk, you've used WebdriverCSS. Is the WebDriverIO's Visual Regression is the replacement of WebDriverCSS?

Yes and no. I wasn't able to continue working on WebdriverCSS and other people build based on it a new tool with better support for mobile which you might be using now. So the VRT service and plugin are are based on WebdriverCSS and maybe in near future we can build a bigger eco system around this.

> Would the Visual Regression be able to do that, despite having the same file name that was generated?

What do you mean by that? It is all about which baseline you check in and out. Based on that the VRT tool compares with the current state. The baseline is the expected state. When for some reason you change the UI the baseline should change too so that all you future tests won't fail.

**Comment by KenzoM** [comment]
@christian-bromann , sorry I worded poorly, but you basically answered my question.

Thanks again!
