### ISSUE TITLE
add documentation on the REPL and debug

### ISSUE THREAD

**Issue by jacalata** [webdriverio/webdriverio#2255]
## The problem

I don't know how to use the debugger, and I'm not planning to watch a video or a gif video to find out.  Is there any more documentation than this page? http://webdriver.io/api/utility/debug.html

**Comment by christian-bromann** [comment]
Is watching a gif video that exhausting? 😆

You find also some information here: http://webdriver.io/guide/usage/repl.html

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by jacalata** [comment]
"exhausting" isn't the word I'd use, but thanks for the condescension. I would say unsearchable, not designed to speed up, slow down, or especially to pause and refer to a specific command. The usage page you linked isn't very useful either. (All I originally wanted to know was how to continue when a debug() command has stopped the test.)

An issue is exactly the right way to track flaws in your documentation, but if you're not planning to improve them then sure, closing it is the right way to go.  If you don't like people creating issues then you should probably update that line in your footer that says "If you have questions or any problems using WebdriverIO join the Gitter Chat, hit us contributor on Twitter or just file an issue on Github".

**Comment by christian-bromann** [comment]
@jacalata sorry I didn't meant to offend you by closing the issue. You can exit the debug mode when entering `.exit` or `CTRL+C`.

> An issue is exactly the right way to track flaws in your documentation

I absolutely agree with you. Just is this issue post not helping to solve the flaw. I was not completely clear why the docs aren't helping you. That is why I've redirected you to our support channel where we could have a better conversation about this.

> If you don't like people creating issues

I like people creating issues. I just don't like unclear issue posts. Just blaming the people who work in their free time on this project doesn't help to improve it at all.
