### ISSUE TITLE
firefox rightClick not work

### ISSUE THREAD

**Issue by zrx8269** [webdriverio/webdriverio#2256]
## The problem
Hi,

rightClick() in firefox not work

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 6.11.0
* [Standalone mode or wdio testrunner]: Standalone mode
* firefox version: 55.0.2

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Selenium/WebdriverIO logs
{"message":"mouseMoveTo
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
 os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: driver.version: RemoteWebDriver","type":"RuntimeError","seleniumStack":{"status":9,"type":"UnknownCommand","message":"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.","orgStatusMessage":"mouseMoveTo"

## Code To Reproduce Issue [ Good To Have ]

browser.rightClick('#load');

**Comment by christian-bromann** [comment]
@zrx8269 this is a known issue. We are about to introduce the action API that will allow to do these things.

**Comment by git-jiby-me** [comment]
@christian-bromann i see this issue come up and same response in many issues.

Does this mean that there is no way to do a `rightClick` as of now, and users have to wait until the action API is implemented ?

**Comment by git-jiby-me** [comment]
@christian-bromann just found out that this is a limitation of safari api.
