### ISSUE TITLE
Include access to tags and examples in custom reporter

### ISSUE THREAD

**Issue by cnatis** [webdriverio/webdriverio#2261]
## The problem

I need to create a custom reporter to integrate WDIO test results with xray (a Jira plugin). My features and scenarios are tagged with IDs and my scenarios include examples, I want to be able to access the tags on a given spec as well as either the current example being used for a test and or the index and all the examples available for that test/scenario.

TLDR;
I need a way to link a scenario result to an ID preferably using a tag on the scenario or feature
I need a way to report failure/success for each example of a scenario

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 7.0.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): 
wdio-cucumber-framework: 1.0.1
wdio-selenium-standalone-service: 0.0.9
selenium-standalone: 6.7.0

## Details

The suites, specs, and tests do not include tag or example info.

Example feature file
`
@BLAH-954
Feature: Logging in
 #As a user I want to be able to login so that I can view my data

  Background:
	Given I am on the login page
 #Login with invalid user
  @BLAH-954
  Scenario Outline: Automate Login with invalid user
	When I log in with user "<username>"
	And a password "<password>"
	Then the login page displays error "<error>"

	Examples: Invalid
	  |username|password|error|
	  |admin   |password123|Incorrect username or password|
`

**Comment by christian-bromann** [comment]
This issue was moved to webdriverio/wdio-cucumber-framework#74

**Comment by cnatis** [comment]
@christian-bromann thank you for moving, should have realized that cucumber tags must be cucumber specific
