### ISSUE TITLE
scroll() api doesn't work with 

### ISSUE THREAD

**Issue by TuHuynhVan** [webdriverio/webdriverio#2265]
## The problem

scroll() api doesn't work, it can't scrool to the expected element.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 6.9.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable): 
"wdio-mocha-framework": "0.5.10",
"wdio-selenium-standalone-service": "0.0.8",
"wdio-junit-reporter": "0.3.0"

## Code To Reproduce Issue [ Good To Have ]

```
describe("Getting TOC", () => {

    const PAGE_URL = "https://www.packtpub.com/application-development/mobile-test-automation-appium";
    const COOKIE_POLICY_LNK = "=Cookie Policy";

    before("Going to the target page", () => {
        browser.url(PAGE_URL);
        browser.windowHandleMaximize("current");
        browser.pause(2000)
    });

    it("Get Content", () => {
        $(COOKIE_POLICY_LNK).scroll();
        browser.pause(2000);
    })
});

```

**Comment by christian-bromann** [comment]
@TuHuynhVan you don't need to scroll. Selenium is doing that for you (except you have some sort of scrollr page but then I'ld recommend to just click on the target element). Scroll will be deprecated soon anyway. It is relict from old times.
