### ISSUE TITLE
Can not select/setValue or get Elements. Getting { state: 'pending' }

### ISSUE THREAD

**Issue by shankarregmi** [webdriverio/webdriverio#2266]
I am using webdriver.io with selenium 
`desiredCapabilities: {
        browserName: 'chrome',
        acceptSslCerts: true,
        platform: 'LINUX',
      }`

to automate few things on our website (like form field fill up and submit)

I am connected to selenium server with vnc and can monitor what's going on :

The problem is input elements are rendered correctly and I am trying to `setValue` of the input fields .
`<input aria-label="First name" name="first_name" placeholder="First name"  type="text">`
`<input aria-label="Last name" name="last_name" placeholder="last name"  type="text">`

What I am doing is 
`browser.setValue('input[name="first_name"]', 'Shankar Regmi')` But without luck no value is set
Even If I try to get all the input elements that are there by 
`console.log(browser.elements('input[name="first_name"]')) // {state: 'pending'}`

I am tired trying all the alternatives. Is there something I am missing??

The web-app I am trying is using react, does it make any difference?

**Comment by christian-bromann** [comment]
> I am tired trying all the alternatives. Is there something I am missing??

`{state: 'pending'}` means that you are getting a promise back. You can only run commands synchronously if you run wdio testrunner. Make sure to check out the [boilerplates](http://webdriver.io/guide/getstarted/boilerplate.html) to see how to setup a project properly.

> The web-app I am trying is using react, does it make any difference?

No.

Also if you have questions, join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
