### ISSUE TITLE
closing and relaunching the app reinstalls it

### ISSUE THREAD

**Issue by mgthor** [webdriverio/webdriverio#2267]
I am using `browser.closeApp()` and `browser.launch()` to verify its on same tab. But its restarting my app. 
how do I avoid restarting. just minimize the app and launch it. 

OS : iOS

**Comment by christian-bromann** [comment]
Sorry I actually don't know. I recommend to ask this in our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) support channel or in the Appium community. Closing as this is not a WebdriverIO issue.
