### ISSUE TITLE
proxy not work

### ISSUE THREAD

**Issue by zrx8269** [webdriverio/webdriverio#2273]
## The problem

The proxy is not set in firefox.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 6.11.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): standalone

## Code To Reproduce Issue [ Good To Have ]

const webdriverio = require('webdriverio');

var opts = {
	desiredCapabilities: {
		browserName: 'firefox',
		proxy: {
                        proxyType: "manual",
	            httpProxy: "a.b.c",
	            httpProxyPort: 8080,
	            sslProxy: "a.b.c",
	            sslProxyPort: 8080
                  }
	}
},
webdriverio
        .remote(opts)
    .init()
        .url('http://www.google.com');

**Comment by christian-bromann** [comment]
Proxy seems to just have landed in Firefox Nightly: https://github.com/mozilla/geckodriver/issues/764
