### ISSUE TITLE
WebDriverIO for testing E2E applications developed in HandsonTable

### ISSUE THREAD

**Issue by vijayeendrajoshi** [webdriverio/webdriverio#2274]
Can WebDriverIO be used for E2E testing of applications developed in HandsonTable? 

[http://jsfiddle.net/begbprme/](url)

Like performing scrolling, going to the specific cell and performing operations?

**Comment by christian-bromann** [comment]
Yes

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
