### ISSUE TITLE
Switch to a specific iframe with partially known id attribute

### ISSUE THREAD

**Issue by mpj** [webdriverio/webdriverio#228]
I need to switch to a iframe that I only "roughly" know the id attribute of (the id attribute has the format "brand-application-1jkd73jnd8nm9sn" where "brand-application" is a string that I know will be the same but "1jkd73jnd8nm9sn" is some kind of hash that changes on every request.

As far as I can see, the frame command only supports id as an argument (https://github.com/camme/webdriverjs/blob/0f966dae482b52e91f44692140a69d0c4a4a83ea/lib/protocol/frame.js#L1) making something like (http://api.jquery.com/attribute-starts-with-selector/) impossible, so I need to extract the exact ID for the frame. Is there any way of extracting the id's of all the iframes on the page?

**Comment by tylucaskelley** [comment]
I tried this to no avail. Here's my code, using Mocha: 

```js
it('should switch to the iframe', function(done) {
    browser.element('iframe.foreign-data-container', function(err, el) {
        browser.frame(el.value.ELEMENT, function() {
            browser.getHTML('element inside of iframe', function(err2, html) {
                console.log(html);
                done();
            });
        });
    });
});
```

Always logs undefined for me, and I'm pretty sure the browser isn't switching to the iframe either.

**Comment by christian-bromann** [comment]
@tylucaskelley because you need to work with these promises! Each command returns a promise, this should work:

```js
it('should switch to the iframe', function() {
    return browser.element('iframe.foreign-data-container').then(function(el) {
        return browser.frame(el.value.ELEMENT).then(function() {
            return browser.getHTML('element inside of iframe').then(function(html) {
                console.log(html);
            });
        });
    });
});

// even better:

it('should switch to the iframe', function() {
    return browser.element('iframe.foreign-data-container').then(function(el) {
        return browser.frame(el.value.ELEMENT);
    }).then(function() {
        return browser.getHTML('element inside of iframe');
    }).then(function(html) {
        console.log(html);
    });
});
```

**Comment by SchwaFa** [comment]
@christian-bromann I'm currently also trying to switch to a specific iframe using your solution, but I always get
```
invalid selector: An invalid or illegal selector was specified
```

when calling "browser.frame(el.value.ELEMENT);", even though my selector for the iframe should be correct.

Any suggestions?

**Comment by SchwaFa** [comment]
okay, I found the solution:
The "el.value.ELEMENT" is wrong! I tried to use "browser.frame(el.value)" and everything works as expepcted. ;)

**Comment by ckurban** [comment]
I have similar issue where my elements live under multiple framesets and frames, is there any way to find element? I have tried above written solution but no luck

![image](https://user-images.githubusercontent.com/987277/33317949-c45174f0-d430-11e7-93f1-708f62b159a9.png)

**Comment by andreyev-oleg** [comment]
Hi @ckurban - Have you come across such a solution.  I've been dealing with an application whether the iFrames are dynamically changing due to code deploys/etc and it's a nightmare to keep track off all the frame IDs. 

I feel like the best thing to do would be to search through all frames, if the element exists, perform action and move on - but achieving that is tougher than stated.

**Comment by guna1404** [comment]
@SchwaFa Thank you, your solution its work as expected for me also.
