### ISSUE TITLE
element() will make global selector a relative one if last promise is set causing selectByAttribute() to always fail on selecting the element

### ISSUE THREAD

**Issue by silkentrance** [webdriverio/webdriverio#2281]
## The problem

selectByAttribute and clients of that function always fail when there is a lastPromise or lastResult  available as this will cause element() to turn the existing selector into a relative selector.

While it might be nice to be able to chain calls to element(), this seems to break for example selectByValue() and selectBy* in general.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 8.4.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): standalone
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Details

See problem description above.

## Link to Selenium/WebdriverIO logs

n/a

## Code To Reproduce Issue [ Good To Have ]

```
Feature: selectByValue fails
    When I wait for the page to have loaded
    Then I select the option with the value "Foo" for element "//select[@name='Bar']"
```

Where the ``WHEN`` will wait for an element ".loadingState" to not exist.
Which in turn will set lastResult, which in turn will cause the following selectByValue to fail due to 
"//select[@name='Bar']" being translated to "./select[@name='Bar']".
Consequently, this will fail. And there seems to be no way to circumvent that problem except by using a dummy step and action that will remove the lastResult and lastPromise from "this".

**Comment by silkentrance** [comment]
Oh forget this. This has already been fixed. Upgrading to newest release.

**Comment by christian-bromann** [comment]
@silkentrance can you provide a reproducible example or logs?

**Comment by silkentrance** [comment]
@christian-bromann will try to make a working example and put it into a gist.

**Comment by silkentrance** [comment]
@christian-bromann https://gist.github.com/silkentrance/fcbb8300ef626b72a72577408fc40c47
hope this helps

**Comment by christian-bromann** [comment]
@silkentrance I was not able to reproduce this in Firefox nor Chrome.

Here my repl:
```sh
wdio repl firefox
                                                                                                                      
[16:09:48]  DEBUG       Queue has stopped!
[16:09:48]  DEBUG       You can now go into the browser or use the command line as REPL
[16:09:48]  DEBUG       (To exit, press ^C again or type .exit)
                                                                                                                      
> browser.url("http://html.com/tags/select/")
{ state: 'success',
  sessionId: '9de8f12d-a96f-455a-912b-41225e233fa2',
  hCode: 510655890,
  value: null,
  class: 'org.openqa.selenium.remote.Response',
  _status: 0 }
> browser.selectByAttribute("//select", "value", "Greater")
{ state: 'success',
  sessionId: '9de8f12d-a96f-455a-912b-41225e233fa2',
  hCode: 160369460,
  value: null,
  class: 'org.openqa.selenium.remote.Response',
  _status: 0 }
>
(To exit, press ^C again or type .exit)
>
```

**Comment by silkentrance** [comment]
@christian-bromann running it from inside the repl work fine.
But running it using cucumberjs will cause it to fail.
I tried this on both Linux and Windows.

I have updated the gist and attached to it a version of webdriverio/build/lib/commands/selectByAttribute.js that will log the selector and the error returned by the first call to element().

As you can see in the output before the actual test run log, the original selector is "//select" whereas element() uses a different selector "./select".

https://gist.github.com/silkentrance/fcbb8300ef626b72a72577408fc40c47

**Comment by christian-bromann** [comment]
> As you can see in the output before the actual test run log, the original selector is "//select" whereas element() uses a different selector "./select".

Can you please post the step definition? Otherwise I can only guess here

**Comment by silkentrance** [comment]
Oh its the step definitions from the webdriverio / cucumber boilerplate project, see over here:
https://github.com/webdriverio/cucumber-boilerplate/blob/60e186f064dfeb41c6f9184b1867e59053136390/src/steps/when.js#L95

and the action here:

https://github.com/webdriverio/cucumber-boilerplate/blob/master/src/support/action/selectOption.js

The action itself uses selectByValue() directly ...

Now I see, perhaps the problem lies with selectOption calling upon element[command] where element is the select element. And selecting from that will of course make it relative...

**Comment by christian-bromann** [comment]
This issue was moved to webdriverio/cucumber-boilerplate#133
