### ISSUE TITLE
Cannot read property 'ELEMENT' of null with page objects

### ISSUE THREAD

**Issue by shylajanagineni** [webdriverio/webdriverio#2287]
## The problem

I get the below error when page object is used. I have two page objects, the generic page object file has issue.
Cannot read property 'ELEMENT' of null
 My test file:
```js
var review = require('./review.page.js');
var ReviewForm = require('./reviewform.page.js'); // this has problem
var objArr = [{'email':'e@e.com',
               'content':'simple review from e'},
              {'email':'f@f.com',
               'content':'simple review from f'},
              {'email':'g@g.com',
               'content':'simple review from g'},
              {'email':'h@h.com',
               'content':'simple review from h'}];

 it.only('Read from json object',function(){
	for (var i = 0; i < objArr.length; i++) {
    		var key = objArr[i];
           var reviewForm = new ReviewForm(i+3);
	   	review.addReview(key.email,key.content);
   	   	var isExisting =   browser.isExisting('p='+key.content+'');
   		expect(isExisting,'comment does not exist at all.').to.be.true;
      
         var email = browser.getText(".reviews > .comment:nth-of-type(" + (i + 3) + ") .email");
         var email1 = reviewForm.email.getText(); // This line throws error, if this line commented the test passes.
expect(email).to.be.equal(key.email);
         var content = browser.getText(".reviews > .comment:nth-of-type(" + (i + 3) + ") .comment");
         expect(content).to.be.equal(key.content);
       
	}
 })
```
My page object file:
```
class ReviewForm {
  constructor(id){
   this.reviewContainer = $(".reviews > .comment:nth-of-type("+id+")");
   console.log("costructor "+id);
  }  
  get email () {return this.reviewContainer.element(".email");}
  get content () {return this.reviewContainer.element(".comment");}

}
module.exports = ReviewForm;
```

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: npm 3.10.10
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):  wdio test runner
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable): mocha framework

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
This probably means that the element doesn't exist. Please check the driver logs. Just by looking at the unformatted code snippet doesn't give my any other clue. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by shylajanagineni** [comment]
Thanks Christian for the quick update.
The element exists and it works if I directly access like below without page object.
var email = browser.getText(".reviews > .comment:nth-of-type(" + (i + 3) + ") .email");
