### ISSUE TITLE
latest wdio returns v4.6.2 

### ISSUE THREAD

**Issue by sfaxino** [webdriverio/webdriverio#2293]
## The problem

I've installed the latest version of `webdriverio` `v4.8.0`
and every time I run `./node_modules/webdriverio/bin/wdio --version` 
it returns `v4.6.2`

it seems that the latest release has been shipped with an outdated build, because I cloned the webdriverio repo locally and ran `npm run build` and it gave me the correct version `v4.8.0`

## Environment

* WebdriverIO version: `v4.8.0`
* Node.js version: `v6.11.1`
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): `both`
* if wdio testrunner, running synchronous or asynchronous tests: `synchronous`
* Additional wdio packages used (if applicable): `N/A`

**Comment by andriilazebnyi** [comment]
I also checked the source code.

`webdriver/build/package.json` contains ver. 4.6.2 and there are differences between code, e.g. from `webdriver/build/lib/commands` and `webdriver/lib/commands` folders. So, I guess, @sfaxino is right and outdated code was published to the npm registry.

CC @christian-bromann

**Comment by christian-bromann** [comment]
> right and outdated build was published to the npm registry.

Nope, just an outdated package.json was copied to the build folder. You see your actual package.json in `./node_modules/webdriverio/package.json`

**Comment by christian-bromann** [comment]
Will be fixed with the next release
