### ISSUE TITLE
Error: Remote end send an unknown status code. (But the error is not consistent)

### ISSUE THREAD

**Issue by shylajanagineni** [webdriverio/webdriverio#2294]
## The problem
The below error appears , but sometimes the same code works fine.
Error: Remote end send an unknown status code. 

 //login.accDropdownMenu.click(); // page object usage, works some times, but fails majorly with above error.
var accMenu ="#headerFrameSliverContainer > div.columns.header-cart.end.header-frame-upper-right > div > div.large-10.columns > div > div:nth-child(5) > div > section > span.menu"
//$(accMenu).click(); //  works some times, but fails majorly with above error.

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 3.10.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
@shylajanagineni thanks for raising the issue. Unfortunately this is not a bug in WebdriverIO. It seems that there are connectivity issues with the selenium server that you are running. There is nothing really we can do about it.
