### ISSUE TITLE
selenium-standalone service can not handle async type commands (with jasmine framework)

### ISSUE THREAD

**Issue by gsanta** [webdriverio/webdriverio#2297]
## The problem
I try to use the async type API with selenium-standalone and jasmine framework.
The test ends immediately and does not wait for the async calls to finish.

It should wait for the `done` function to be called (at least that's how jasmine handles async), I think in 3.X it still worked but I'm not sure.

## Code To Reproduce Issue [ Good To Have ]

In this example the test should fail, but somehow it does not wait for the async calls and signals it as passing:

My wdio config:

```
exports.config = {
    specs: [ 'test_async.js' ],
    services: ['selenium-standalone'],
    maxInstances: 1,
    capabilities:  [ {  browserName: 'chrome' } ],
    sync: false,
    waitforTimeout: 10000,
    reporters: ['spec'],
    framework: 'jasmine',
    jasmineNodeOpts: { defaultTimeoutInterval: 10000 }
};

```
My sample test file:

```
var webdriverio = require('webdriverio');

describe('my webdriverio tests', function() {
    it('test it', function(done) {
        browser
            .url('https://github.com/')
            .waitForExist('.abcdefgh')
            .then(() => done())
            .catch((e) => done(e));
    });
});

```

**Comment by christian-bromann** [comment]
@gsanta WebdriverIO don't support callback functions in tests (even in jasmine). You need to work with the promise chain and return it:

```js
describe('my webdriverio tests', function() {
    it('test it', function(done) {
        return browser
            .url('https://github.com/')
            .waitForExist('.abcdefgh');
    });
});
```

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
