### ISSUE TITLE
elementIdClear() in setValue() causes extraneous change event 

### ISSUE THREAD

**Issue by silkentrance** [webdriverio/webdriverio#2298]
## The problem

I am using setValue() to set a given input field to a specific value. However, and due to the use of elementIdClear() inside setValue(), two change events will be fired for the input field, causing the existing form validation handlers to step in and complain about the now invalid empty content of the field.

https://github.com/webdriverio/webdriverio/blob/master/lib/commands/setValue.js#L54

If you remove the extraneous call to elementIdClear(), everything will work as expected and only one change event will be fired.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 8.4.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): standalone
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): wdio-cucumber-framework, wdio-sync

## Details

see above

## Link to Selenium/WebdriverIO logs

No logs required

## Code To Reproduce Issue [ Good To Have ]

Do you really need this?

**Comment by christian-bromann** [comment]
> If you remove the extraneous call to elementIdClear(), everything will work as expected and only one change event will be fired.

Please use the [addValue](http://webdriver.io/api/action/addValue.html#Usage) then.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by silkentrance** [comment]
@christian-bromann I cannot use addValue() since that will add the value to the existing data. The form field ist not empty but contains a default value. So I would have to clear it first, which in turn will cause the extraneous dom change event.

**Comment by silkentrance** [comment]
@christian-bromann We should definitely reopen this issue since

* setValue, and due to elementIdClear(), will cause an additional change event that will prevent users from testing applications where a form validation handler is in place that will reject all empty input
* setValue should mimic the user's behaviour, focus element, select all, type in new value, remove the focus from the element

e.g. something along the line of

```
import {UNICODE_CHARACTERS as UC} from '../helpers/constants';

let element = browser.element(selector);
//element.focus()
element.keys([UC.Control, 'a']);
elementIdValue(..., value);
```

**Comment by OP-Klaus** [comment]
I have just run into this problem too - I have a component that enters a value on `blur` if the entered value was invalid, and that means that `setValue` and `addValue` fail. It would be good to have a solution that can clear the input field and enter the new value without triggering a blur event, to simulate what would happen for a real user.

In the meantime I have used jQuery to do it:

```
browser.execute(function() {
  $('#theId').val('the value');
});
```
