### ISSUE TITLE
How to test if an element is focused?

### ISSUE THREAD

**Issue by syymza** [webdriverio/webdriverio#230]
I have found an example on StackOverflow using the C# API (http://stackoverflow.com/questions/7552169/test-if-an-element-is-focused-using-selenium-webdriver), but I am not sure if the same thing is doable with WebdriverJS APIs.

**Comment by binarykitchen** [comment]
I think this one is missing in the API documentation ... ?

**Comment by christian-bromann** [comment]
@binarykitchen http://webdriver.io/api/protocol/elementActive.html

**Comment by binarykitchen** [comment]
Ah, thanks

**Comment by saulshanabrook** [comment]
How would I check that this equals a certain other element?

Could I do this?

```
          var input = yield browser.element('#grandmaster .level input')
          yield browser.elementActive().should.eventually.be.equal(input)
```

When I try it `input` is undefined. I have other generators working, for example this passes:

```
          yield browser.isVisible('#grandmaster .level input').should.eventually.be.true
```
