### ISSUE TITLE
Introduce new Keys api

### ISSUE THREAD

**Issue by silkentrance** [webdriverio/webdriverio#2300]
## The problem

Sending key stroke events to the SUT is rather cumbersome and some help by the framework will be appreciated.

Similar solutions exist 

* https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/Keys.html

Here, one can use the constants defined by Keys in calls to element.keys(...). In addition, there exists the Keys.chord() method, which allows one to combine multiple keystrokes into a single character sequence (i.e. string) that is terminated by the NULL character.

## Environment

* WebdriverIO version: all versions
* Node.js version: all versions
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): all modes
* if wdio testrunner, running synchronous or asynchronous tests: all
* Additional wdio packages used (if applicable):

## Details

There already exists ``lib/helpers/constants.js#UNICODE_CHARACTERS`` which provides the required unicode character references for use with the Keys abstraction.

In order to make this work, one could provide a helper Keys object somewhere along the line of

```
import {UNICODE_CHARACTERS as UC} from './constants';

const Keys = _.extend({}, UC);
Keys.chord = (...chars) => {
  return [...chars, Keys.NULL].join('');
}

export default Keys;
```

The user would then simply

```
import Keys from 'webdriverio/lib/helpers/keys';

browser.element('#foo').keys(Keys.chord(Keys.Control, 'a')).keys('new Value');
```

## Related

#2298

**Comment by christian-bromann** [comment]
@silkentrance I don't think this is necessary. It is already possible by doing:

```js
browser.click('#foo').keys(['Control', 'a']).keys('new Value')
```

As described in the [docs](http://webdriver.io/api/protocol/keys.html#Parameters) the parameter for keys can be a string or a string array. Also there is no reason to query an element before calling keys. Afaik this won't create any focus on the element. So you need to click on it.
