### ISSUE TITLE
Appium webdriverio 404 error

### ISSUE THREAD

**Issue by Sykomaniac** [webdriverio/webdriverio#2302]
When working with webdriverio to execute tests against a local appium instance I cannot get it to find an element in the page regardless of selector strategy. 

Webdriverio is able to create a new session but subsequent calls to the appium service give a 404. I have attached my config and error log to help debug this issue. When looking in the appium server log I can also see no subsequent API calls are logged after the session create.

Webdriverio version: 4.8
Appium version: 1.6.5

Logs:
https://gist.github.com/Sykomaniac/88c6e796d6e1e488cd142db9f905dc37
https://gist.github.com/Sykomaniac/6622d7fcf7546feabb698c5ee95ee33c

**Comment by christian-bromann** [comment]
@Sykomaniac can you try settings the protocol to `http`?

```js
var path = require('path');
var testApp = path.resolve(__dirname, 'apps', 'android-debug.apk');

exports.config = {
    host: '127.0.0.1',
    port: 4723,
    specs: [
        './tests/*.js'
    ],
    exclude: [
        // 'path/to/excluded/files'
    ],
    // ...
```

**Comment by Sykomaniac** [comment]
@christian-bromann thank you for the suggestion - I have tried that but still results in a 404. Very confused with this so I appreciate any help you can offer

**Comment by Sykomaniac** [comment]
Again to try and show the issue appium server log is below. As you can see I the commands to start the session work but then we get a timeout as the other service calls to query the elements/delete the session result in a 404.

`[MJSONWP] Responding to client with driver.createSession() result: {"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":true,"warnings":{},"desired":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"","appiumVersion":"1.6.5","deviceName":"TC70_API_19","deviceOrientation":"portrait","platformVersion":"4.4","platformName":"Android","app":"C:\\Users\\a0s00os\\Documents\\Projects\\test\\apps\\android-debug.apk","requestOrigins":{"url":"http://webdriver.io","version":"4.6.2","name":"webdriverio"}},"handlesAlerts":true,"rotatable":true,"browserName":"","appiumVersion":"1.6.5","deviceName":"emulator-5554","deviceOrientation":"portrait","platformVersion":"4.4.2","platformName":"Android","app":"C:\\Users\\a0s00os\\Documents\\Projects\\test\\apps\\android-debug.apk","requestOrigins":{"url":"http://webdriver.io","version":"4.6.2","name":"webdriverio"},"deviceUDID":"emulator-5554","deviceScreenSize":"720x1...
[HTTP] <-- POST /wd/hub/session 200 15556 ms - 1335 
[BaseDriver] Shutting down because we waited 60 seconds for a command`

**Comment by christian-bromann** [comment]
How does your setup look like?

**Comment by Sykomaniac** [comment]
My wdio config is here https://gist.github.com/Sykomaniac/88c6e796d6e1e488cd142db9f905dc37

I have the appium desktop client running the server, latest version of webdriverio, latest version of android studio running an emulator. I can post my test project if it makes it easier

**Comment by christian-bromann** [comment]
> I can post my test project if it makes it easier

yes please

**Comment by Sykomaniac** [comment]
@christian-bromann here you go test project is here: https://github.com/Sykomaniac/wdio-test

**Comment by Sykomaniac** [comment]
@christian-bromann I tried capturing packets in wireshark and I can see that I do indeed get a 404 from Appium when an elements request is sent with a response of "A session is either terminated or not started"

**Comment by Sykomaniac** [comment]
Its now working :( it appears that it was an issue with me spinning up the appium server in a separate command window - if I let WDIO do this its working fine!
