### ISSUE TITLE
WebdriverIO + automated accessibility test?

### ISSUE THREAD

**Issue by KenzoM** [webdriverio/webdriverio#2303]
Hello 
I was wondering if WebdriverIO has some capability to run automated accessibility tests, similiar to [axe-webdriverjs](https://github.com/dequelabs/axe-webdriverjs)?

I know that axe-webdriverjs is the bridge between axe-core and selenium-webdriver, but is it possible for WebdriverIO to be compatible with axe-core as well?

**Comment by sshaar08** [comment]
+1 i tried to edit the npm package and was not able to get it working. I reached out to @klamping for some help. I know he is busy but I am waiting on a reply. The two issues I found were that the Switch To.defualtcontext is not the same in WDIO it is browser.frame(id), and if id is null it should switch to the page’s default content. I got that going but had an issue with the inject.js function which looks for iframes. Let me know if you want to pair program a new package i would love to have this.

**Comment by KenzoM** [comment]
@sshaar08 yeah man! I was tinkering around the npm module myself too, but couldn't get it to work either.
I've also reached out to @klamping via twitter, but he seems busy at the moment.

**Comment by klamping** [comment]
haha, y'all are awesome for trying such cool stuff! yes, i'm busy as normal (mostly the 3-year old and me spending too much time in my garden). 

I did try axe-webdriverjs with webdriverio a while back, but can't remember the results... totally useless information, I know. 

I can't make a solid time commitment to pair program on this, but I can try doing a live recording of what I'm up via my twitch stream. I'll update this thread when I do.

**Comment by KenzoM** [comment]
@klamping thanks!
Yes please, keep us posted. In the meantime, we'll see how far we can get it working

**Comment by sshaar08** [comment]
Perf! I can try to get some coding time in this weekend and see where it gets me. I'll open a branch and post it here if I make any headway

**Comment by KenzoM** [comment]
@sshaar08 Great! You probably made more progress than I did, so I'll take a look at it once you open branch.

**Comment by YmerejRedienhcs** [comment]
I'm interested, too!

**Comment by KenzoM** [comment]
@sshaar08  @YmerejRedienhcs are you all on gitter? We can chat there sometime this weekend to go over this feature

**Comment by klampingtester** [comment]
FYI, i've got an example repo here that injects Axe and runs the script: https://github.com/klamping/wdio-axe-example

**Comment by KenzoM** [comment]
@klampingtester Wow! It was much simpler than I thought...Great job man!

**Comment by klamping** [comment]
I recorded and just finished editing a live stream where I talk through figuring it all out. It'll be published in just a few minutes here if you're looking for more details on how I set things up:
https://youtu.be/6gwtqYCxNwQ
