### ISSUE TITLE
doubleClick consistently doesn't work on OS X Mavericks Safari in Browserstack

### ISSUE THREAD

**Issue by davidworkman9** [webdriverio/webdriverio#231]
When attempting to execute a `doubleClick` in Safari I will consistently get this error:

```
Move Mouse
Unknown command: mouseMoveTo (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 3 milliseconds Build info: version: '2.42.0', revision: '5e82430', time: '2014-05-22 20:18:07' System info: host: 'mac-208-52-180-112.browserstack.com', ip: '208.52.180.22', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9', java.version: '1.6.0_65' Session ID: null Driver info: org.openqa.selenium.safari.SafariDriver Capabilities [{platform=MAC, cssSelectorsEnabled=true, javascriptEnabled=true, secureSsl=true, browserName=safari, takesScreenshot=true, version=7.0}]
```

Seems to originate around the `moveToObject` function.

**Comment by msiles** [comment]
is there a workaround for this?

I'm doing something like this without luck

executor.executeScript("arguments[0].dblclick();", element);

**Comment by davidworkman9** [comment]
@msiles, that's what I ended up doing, using execute to invoke the dblclick event.

**Comment by msiles** [comment]
@davidworkman9, could you share your example? I'm getting the following error

arguments[0].dblclick is not a function. (In 'arguments[0].dblclick()', 'arguments[0].dblclick' is undefined) (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 35 milliseconds Build info: version: '2.48.0', revision: 'b7b081a4f1289f17e8ecd38bc67e137c2a12e34a', time: '2015-10-07 09:50:14' System info: host: 'MacBook-Pro.local', ip: '10.0.1.7', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11', java.version: '1.8.0_25' Driver info: org.openqa.selenium.safari.SafariDriver Capabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=9.0, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}] Session ID: null

**Comment by davidworkman9** [comment]
My project uses jQuery so I would do something like this:
```
$('.some-button').dblclick();
```
Perhaps this would work for you?
```
$(arguments[0]).dblclick();
```

**Comment by davidworkman9** [comment]
Update: according to [this](http://stackoverflow.com/questions/7557342/how-to-programmatically-fire-ondblclick-event-in-javascript), it's actually ```ondbclick``` not ```dblclick``` on the raw DOM nodes. So:
```
arguments[0].ondblclick();
```

**Comment by msiles** [comment]
@davidworkman9 this is weird,

I tried

            JavascriptExecutor executor = (JavascriptExecutor) driver;
            executor.executeScript("arguments[0].ondblclick();", element);

but I got the same error

arguments[0].ondblclick is not a function. (In 'arguments[0].ondblclick()', 'arguments[0].ondblclick' is null) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 22 milliseconds
Build info: version: '2.48.0', revision: 'b7b081a4f1289f17e8ecd38bc67e137c2a12e34a', time: '2015-10-07 09:50:14'
System info: host: 'MacBook-Pro.local', ip: '10.0.1.7', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11', java.version: '1.8.0_25'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=9.0, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}]
Session ID: null

**Comment by msiles** [comment]
The click works, but I'm having issues with the double click

**Comment by DV3D** [comment]
Maybe a stupid question, but have you tried 2 click events, immediately after each other?
Worked for me in Java + Webdriver some time ago...

You will have to NOT use promises on this occasion, I guess.

**Comment by msiles** [comment]
@DV3D yes, I already tried the click method after click using javascript and the webdriver methods but it doesn't work, basically I need to double click a cell in a grid, after this the cell will be editable. 

I'm not sure what is wrong .

**Comment by davidworkman9** [comment]
@msiles maybe [this](http://stackoverflow.com/questions/18399215/how-to-programmatically-fire-a-dblclick-event-defined-with-addeventlistener)?

**Comment by msiles** [comment]
Thanks @davidworkman9, what I don't understand is how to handle this with selenium webdriver,

I tried this on firefox console

document.querySelector("div[id='InProcessGrid']>div>table>tbody>tr.rowselected>td:nth-child(1)").dispatchEvent(ondblclick);

but it returns the error
TypeError: Argument 1 of EventTarget.dispatchEvent is not an object.

**Comment by msiles** [comment]
@davidworkman9 @DV3D Thanks guys for all your help, 

with the following code is working on Safari

var event = new MouseEvent('dblclick', {
    'view': window,
    'bubbles': true,
    'cancelable': true
  });

document.querySelector("div[id='InProcessGrid']>div>table>tbody>tr.rowselected>td:nth-child(1)").dispatchEvent(event);
