### ISSUE TITLE
boolean env variable sets an array for services but never spins up selenium-standalone

### ISSUE THREAD

**Issue by sshaar08** [webdriverio/webdriverio#2310]
## The problem

You can not set an array variable and then assign it to services. Selenium never starts,

## Environment

* WebdriverIO version: webdriverio@4.8.0
* Node.js version: 8.1.4
* Standalone mode

## Details
with the code below I am trying to make the services array match:  services: ['visual-regression','selenium-standalone'], in the wdio.config.js using array.push.  

if I just set  services: ['visual-regression','selenium-standalone'], selenium works and kicks off

but if I make the array like so: 

var services = ['visual-regression'];
var phantom = process.env.HEAD ? services.push('phantomjs') : services.push('selenium-standalone');

services: phantom,

it never starts selenium.

```

var services = ['visual-regression'];
var phantom = process.env.HEAD ? services.push('phantomjs') : services.push('selenium-standalone');
    // Test runner services
    // Services take over a specific job you don't want to take care of. They enhance
    // your test setup with almost no effort. Unlike plugins, they don't add new
    // commands. Instead, they hook themselves up into the test process.
    // services: ['sauce', 'visual-regression'],
    // services: ['visual-regression','selenium-standalone'],

    services: phantom,



```

**Comment by christian-bromann** [comment]
Sorry but can you please explain a little bit more the issue you are facing instead of just pasting a ton of unformatted code.

**Comment by sshaar08** [comment]
@christian-bromann edited let me know if you need more info. i am also running with `wdio` command

**Comment by christian-bromann** [comment]
@sshaar08 I am not sure if this is an webdriverio issue. I don't know how to help you without a reproducible example. I don't see anything wrong with what you've posted. Please make sure you apply the correct configs.

**Comment by sshaar08** [comment]
are you able to build an array and send it to services in wdio.config.js? that is the issue? with any test it doesnt matter what the test does.

**Comment by christian-bromann** [comment]
@sshaar08 yes I am. Feel free to reach out to me in our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
