### ISSUE TITLE
Custom Commands to not pass variables to browser.execute

### ISSUE THREAD

**Issue by RMcNeely** [webdriverio/webdriverio#2311]
## The problem

Custom commands do not seem to pass variables into `browser.execute`. I'm authoring custom convenience functions for others on our team to use and cannot seem to pass variables down to a function inside of `browser.execute`. Is this a bug or am I implementing something incorrectly?

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 6.9.11
* wdio testrunner synchronous 
* Additional wdio packages used (if applicable):
   - wdio-mocha-framework
   - wdio-spec-reporter
   - wdio-selenium-standalone-service
   - wdio-static-server-service

## Details

I've attached two custom commands below:
```
	browser.addCommand('loadTemplate', function(url){
		browser.url(url)
		browser.loadTestUtilityJs()
	})

	browser.addCommand('injectScript', function(url){
	browser.localStorage('POST',{key:'wdioInjectionURL', value:url})
		browser.execute(function(url){
			console.info(url)
			console.info(window.localStorage)
			var script = window.document.createElement('script')
			script.type = 'text/javascript'
			script.src = localStorage.wdioInjectionURL
			window.document.head.appendChild(script)
			console.info(script.src)
		})
	})
```
I was able to use store the variable in localStorage in the second example and access it from there, but this seems incorrect. We're authoring a JS library and use the `browser.execute(function(){....})` to run tests against templates which works fine and are having no issues passing other variables into custom commands. 

## Code To Reproduce Issue [ Good To Have ]

Samples come from wdio.config.js

**Comment by christian-bromann** [comment]
If you want to pass in variables into execute you need to add it as an argument after your function. Please have a look at the example in the [API](http://webdriver.io/api/protocol/execute.html#Example). Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by RMcNeely** [comment]
My question/concern comes from the fact that the we are passing variables in the same way we are other times when using `browser.execute` or using any browser function. There's nothing in the documentation to suggest that passing arguments to browser.execute inside of a custom command would be different. In the two above instances of our custom commands we're passing arguments into each however only one of them works as expected. See you on Gitter
