### ISSUE TITLE
Looping list in WebdriverIO

### ISSUE THREAD

**Issue by effectura** [webdriverio/webdriverio#2312]
How to following achieve by someone more from OO language like JAva?

I'm trying to loop through a list of links, and perform some actions with each one. WebdriverIO are synchronous for test code like following(mocha) for all their API. But how to integrate existing node.js code for synchronous flow. For following code

```
const assert = require('assert');
const webdriverio = require('webdriverio')

describe('webdriver.io page', function() {
    
        it('should be a pending test');
    
        before(() => {

            var options = {
                desiredCapabilities: {
                    browserName: 'chrome'
                }
            };
            
            client = webdriverio.remote(options)
            return client.init();

        })
        after(function() {
            browser.end();
        });
    
        it('should have the right title - the fancy generator way', function () {
            var list = ["https://www.google.com", "https://www.yahoo.com", "https://www.github.com"]
            
            for(var i = 0 ; i < list.length;i++){
                browser.url(list.length);
                var title = browser.getTitle();
                browser.saveScreenshot('./snapshot' + i + '.png').call(function(){
                    fs.exists(screenshotPath, function(fileExists) {
                        fileExists.should.be.true;
                        done();
                    })
                });
            }
        });
    
    });




```

**Comment by christian-bromann** [comment]
@effectura I recommend to use the [wdio testrunner](http://webdriver.io/guide.html#Let’s-get-serious) where all commands are treated synchronous. In this case you can use a for loop like this. Other options would be async/await or nest promised calls. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
