### ISSUE TITLE
supporting versions ANDROID/IOS

### ISSUE THREAD

**Issue by tastafur** [webdriverio/webdriverio#2314]
I was trying mount of stack with:
* Appium
* Cucumber + pageObjects
* webdriverio
i launch a step_definition but i don't know how launch multiples steps_definitions. So I did think in stop app y relaunch the app for each step_definition though what i could exec every steps_definitions. Then I fallen in reason that closeApp, launch or reset app working in IOS or Android not both how installApp, isAppInstalled or removeApp. How could i do launch multiples steps_definitions?

So I started to see another webdriver https://github.com/admc/wd/blob/master/doc/api.md and it seems that if it implements compatibility for both IOS / ANDROID

Why does webdriverio not implement support for previous methods (closeApp, launch, Reset app, installApp, isAppInstalled or removeApp) in ANDROID / IOS respectively?

**Comment by christian-bromann** [comment]
> Why does webdriverio not implement support for previous methods (closeApp, launch, Reset app, installApp, isAppInstalled or removeApp) in ANDROID / IOS respectively?

WebdriverIO is actually not executing these methods on the device. It is getting executed by the automation driver which differ in functionality between iOS and Android. So if one of the automation driver doesn't support one of these commands, WebdriverIO can't support it too. That is why we added the supported by image to let you know if it works on iOS or Android. Generally speaking Android allows way more functionality than iOS.

> So I started to see another webdriver https://github.com/admc/wd/blob/master/doc/api.md and it seems that if it implements compatibility for both IOS / ANDROID

No it doesn't. The WD docs just don't say which commands are supported by iOS or Android.

> How could i do launch multiples steps_definitions?

Please have a look into the boilerplate projects that we provide.

Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
