### ISSUE TITLE
When a selector matches more than 100 elements, errors occur: connect ECONNRESET 127.0.0.1:63127, write EPIPE, read ECONNRESET

### ISSUE THREAD

**Issue by Windso** [webdriverio/webdriverio#2315]
I'm using Chimp which I believe uses webdriverio version 4.4.0. These errors have been occurring during my tests at random and it has been very frustrating. They seem to happen at random, and it causes ALL proceeding tests to fail. 

I did some tests to try to isolate the issue, and found that when a selector matches a ton of elements it causes these errors. Here is the actual test I did.

I have an HTML file that consists purely of empty paragraph tags. I tested it in increments of 5. So `100 p tags`, `105 p tags`, `110 p tags`, .... `200 p tags`
```html
<p></p>
<p></p>
<p></p>
<!-- a lot more <p> tags... -->
```

And here is the code from the step definition that I was using: 
```javascript
for (var i = 1; i < 501; i++) {
    console.log(browser.isVisible("p").length + ": " + i);
}
```
What it does is it tries to log the number of elements that are on the page (and which iteration its on). It tries to log it 500 times, but it always fails. Here are some of the error messages I got:

```
Error: connect ECONNRESET 127.0.0.1:58881
Error: connect ECONNRESET 127.0.0.1:63127
Error: connect ECONNRESET 127.0.0.1:63427
Error: write EPIPE
Error: connect ECONNRESET 127.0.0.1:65240
Error: write EPIPE
Error: connect ECONNRESET 127.0.0.1:49866
Error: connect ECONNRESET 127.0.0.1:52942
Error: read ECONNRESET
Error: write EPIPE
Error: connect ECONNRESET 127.0.0.1:61475
Error: read ECONNRESET
Error: connect ECONNRESET 127.0.0.1:57277
Error: connect ECONNRESET 127.0.0.1:58126
Error: write EPIPE
Error: read ECONNRESET
Error: connect ECONNRESET 127.0.0.1:50770
Error: read ECONNRESET
Error: connect ECONNRESET 127.0.0.1:56693
Error: connect ECONNRESET 127.0.0.1:61033
```
And here are my test results. I did it with both Phantomjs and Chrome headless and both had the same errors, but Chrome seemed to handle the data much better.
![My data](https://i.imgur.com/ZgeKi5J.png)
I'm not sure if this is an issue with Chimp, Webdriverio, Selenium Webdriver, or what, but I'm really stuck. Does anyone have any ideas?

**Comment by christian-bromann** [comment]
@Windso what is your use case here? You should not query 500 elements that will just slow down or even apparently break your test.

**Comment by Windso** [comment]
@christian-bromann I am using my actual script to test the features of my web messaging app. One of the steps is to verify the text of the last message received. I don't have an ID on the last message element, so I instead query the class name and get the last value from the returned array like this:
`browser.getText(".message")[browser.getText(".message").length - 1]`
However if I have a long conversation (~100 messages in total) then it will all fail. What do you think I should do?

**Comment by christian-bromann** [comment]
> What do you think I should do?

You should try to use a xpath as selector strategy. What you do is really not a good idea.

I am closing this since I am not sure if there would be any use case where fetching 100 elements and more is necessary. Please reach out in our gitter support chat if you have any further questions. Thanks!

**Comment by Windso** [comment]
I tried using an xpath selector and am still having the same issue.

**Comment by christian-bromann** [comment]
@Windso with xpath you should be able to specify exactly the first or last element

**Comment by Windso** [comment]
I was able to specify the path to get the last element. It looks like there are multiple causes for this issue, and the selectors matching a ton of elements wasn't the only cause I was experiencing. I'll investigate further later.
