### ISSUE TITLE
Run Specific Test Before All Others - With Specific Capabilities

### ISSUE THREAD

**Issue by psmod2** [webdriverio/webdriverio#2316]
Hi,

I'm using WebDriverIO and I want to do the following:

- Run a single test before any test is run (createNewUsers)
- Use specific capabilities (proxy settings) for that first test
- Once done, use a default set of capabilities for everything else

So I can't seem to figure this out:

I've tried to add a second set of capabilities and use the exclude argument to ensure it only applies to that specific spec however I dont know whether this is actually possible and then how to call that specific test in my before block - so capabilities I use:

`exclude: [ './newUserCreationStage/newStageUsers.js' ], `

But then in my before block - how do i say run that (if its possible):

```
before: function (capabilities, specs) {     
expect = require('chai').expect;      
RUN THIS './newUserCreationStage/newStageUsers.js' },
```

**Comment by christian-bromann** [comment]
> Run a single test before any test is run (createNewUsers)

Use the wdio hooks in your config or framework hooks

> Use specific capabilities (proxy settings) for that first test

Have a separate wdio.config that you run before your actual test like

```js
$ wdio wdio.proxy.conf.js && wdio.conf.js
```

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by psmod2** [comment]
Thanks - I understand that first bit - using the beforeTest hook however I want that before test to use the specific proxy only - not any other tests.

How would `wdio wdio.proxy.conf.js && wdio.conf.js` achieve that?

**Comment by christian-bromann** [comment]
> How would wdio wdio.proxy.conf.js && wdio.conf.js achieve that?

Sorry the snippet was wrong .. it should be

```js
wdio wdio.proxy.conf.js && wdio wdio.conf.js
```

so first run the proxy suite then your normal suite.

> The other issue I face is - using that createNewUsers as above results in error message - TypeError: Cannot read property 'ELEMENT' of null. However if i run in a usual describe it block it works

Not sure but this issue has nothing to do with the beforeTest hook. 

Let's continue this convo in our gitter chat. Thanks!
