### ISSUE TITLE
Retry not working if waitFor*/waitUntil timeouts occur in custom command (SYNC mode)

### ISSUE THREAD

**Issue by eclifford** [webdriverio/webdriverio#2320]
## The problem

I'm currently experiencing an issue with [retries](http://webdriver.io/guide/testrunner/retry.html) not working when `waitFor*` or `waitUntil` commands timeout within a custom command while in sync mode.

### Expectation

If a `waitFor*` or `waitUntil` timeout occurs within a custom command while in sync mode the test runner should handle the `waitForTimeoutError` exception and retry the test if the test runner is configured to do so.

### Reality 

If a `waitFor*` or `waitUntil` command throws a `waitForTimeoutError` while in sync mode the test runner immediately exits the spec with a timeout error without retrying even if configured to do so.

If the custom command is written in async form this everything works fine.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 7.7.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio test runner + mocha
* if wdio testrunner, running synchronous or asynchronous tests: Sync
* Additional wdio packages used (if applicable): 

## Code To Reproduce Issue [ Good To Have ]

Example of the problem
https://github.com/eclifford/webdriver-test/blob/master/test/specs/google.js

**Comment by igerasimov23** [comment]
Any progress on this bug??? 6 month since bug was filed..Looks like it's not only for `waitFor*` or `waitUntil`. As an example:
` browser.addCommand('isVisible',function(element){
             element.isVisible();
// or element.waitForVisible();
        });` 
Will not retry as well

**Comment by WillBrock** [comment]
This is old and probably fixed in v5 so closing. Please re-open if you continue to have issues.
