### ISSUE TITLE
Keep-alive not working at least on node@8.4.0

### ISSUE THREAD

**Issue by Flackus** [webdriverio/webdriverio#2321]
## The problem

It seems that keep-alive is not working now.
Not sure if it's a problem _by default_, but it would be nice to have an an ability to specify that it should be enabled (or even better – to provide a custom `http.Agent`).

## Environment

* WebdriverIO version: `4.8.0`
* Node.js version: `8.4.0`
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): standalone
* if wdio testrunner, running synchronous or asynchronous tests: –
* Additional wdio packages used (if applicable): –

## Details

Setting `Connection: keep-alive` in `RequestHandler` does not trigger actual keep-alive at least in node@8.4.0 (and should not by design).

Fix is quite simple, to create and provide `http.Agent` in `RequestHandler`:
```(javascript)
const http = require('http');
const agent = new http.Agent({keepAlive: true});
...
newOptions.agent = agent;
```

For obvious reasons I can't provide you with full tcpdumps, but please have a glimpse of it.

**Before the fix**
![image](https://user-images.githubusercontent.com/644960/30904444-aef4b7ca-a37a-11e7-8176-edf0a97405cd.png)

**After the fix**
![image](https://user-images.githubusercontent.com/644960/30904458-b83d9392-a37a-11e7-91ae-ee21213397b0.png)

Also, tcp keep-alive packets will appear.
Both captures are taken with Wireshark on OSX.

## Link to Selenium/WebdriverIO logs

Does not matter much for that issue.

**Comment by christian-bromann** [comment]
Could you provide a PR if you already have a fix?

**Comment by Flackus** [comment]
@christian-bromann yes, sure.

Are you ok with enabling keep-alive by default? As `Connection: keep-alive` is already set explicilty, I guess it would be legit.

**Comment by christian-bromann** [comment]
> Are you ok with enabling keep-alive by default?

Yes!

**Comment by Flackus** [comment]
Thanks for the quick response.
I'll make a patch within a few days.
