### ISSUE TITLE
Error: ENOENT, no such file or directory '/node_modules/webdriverio/build/lib/protocol'

### ISSUE THREAD

**Issue by Gobliins** [webdriverio/webdriverio#2322]
I am writing atm some mocha tests after this guide:  https://guide.meteor.com/testing.html

My test looks just like this:

import { chai } from 'meteor/practicalmeteor:chai';
var client = require('webdriverio').remote({
    desiredCapabilities: {
    	platformName: 'iOS',
        app: 'net.company.SafariLauncher',
        udid: '123123123123abc',
        deviceName: 'iPhone',
    }
});

//i can also replace the upper code by:
//import webdriverio from 'webdriverio';
//const webdriverio = require('webdriverio');
// but the error stays the same

describe('my module', function (done) {
  it('should return -1 when the value is not present', function() {
     assert.equal(-1, [1,2,3].indexOf(4));
   });
});

The error is as in the title:
Error: ENOENT, no such file or directory '/node_modules/webdriverio/build/lib/protocol'

I run my tests as described in the guide mentioned above:
meteor --test --driver-package=practicalmeteor

**Comment by christian-bromann** [comment]
@Gobliins you need to install webdriverio from NPM with `npm install webdriverio`. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by Gobliins** [comment]
Yeah i already have installed webdriverio with npm...

npm install webdriverio --save-dev

**Comment by christian-bromann** [comment]
Well not sure what Meteor is doing but it seems to not use that package. I would recommend to use the wdio testrunner and use one of the [boilerplate](http://webdriver.io/guide/getstarted/boilerplate.html) projects. I am not a Meteor expert but the problem is not on WebdriverIO side.

**Comment by Gobliins** [comment]
That may be. The reason i need to use the Meteor test runner is because in some tests i need access to the Meteor fields which are not known by wdio and it's not possible to `import Meteor from 'meteor/meteor' ` either...
So i tried the other way round and tried to introduce webdriverio.remote  to meteor

**Comment by christian-bromann** [comment]
@Gobliins got it, I would raise an issue in the Meteor project then.

**Comment by Gobliins** [comment]
Oh i totally forgot to mention that i encountered

`├── UNMET PEER DEPENDENCY mocha@3.5.0
├── UNMET PEER DEPENDENCY react@15.4.2
├── UNMET PEER DEPENDENCY react-dom@15.4.2
├── webdriverio@4.8.0
└── UNMET PEER DEPENDENCY webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc`

on npm install...

Since i could run wdio by using the wdio test-runner without problems, i ignored this.

**Comment by christian-bromann** [comment]
> Oh i totally forgot to mention that i encountered

These packages are not required for WebdriverIO
