### ISSUE TITLE
isMobile, isIOS, isAndroid not working on BrowserStack

### ISSUE THREAD

**Issue by LKay** [webdriverio/webdriverio#2325]
## The problem

Properties to detect mobile devices not working. The properties `isMobile`, `isIOS`, `isAndroid` as always `false` even if the current device is in fact mobile device. Tried on multiple platforms on cloud services such as BrowserStack and also on android device connected to my machine. 

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio runner
* if wdio testrunner, running synchronous or asynchronous tests: sync/async

**Comment by christian-bromann** [comment]
@LKay you can still try via checking your capabilities right?

**Comment by LKay** [comment]
Yes, that's what I'm doing but these vary (especially between cloud services) yet according to docs this should works regardless selenium service used http://webdriver.io/guide/testrunner/browserobject.html#Check-if-capability-is-a-mobile-device

**Comment by christian-bromann** [comment]
I think since browserstack is using invalid capability properties the mobile detection is borked. I think this can be fixed easily.

**Comment by goatsy** [comment]
Hi, who has to fix this? Browserstack or someone in webdriverio?
If Browserstack has to change something, I would like to address it to their support. But I need some details.
Thank you!

**Comment by christian-bromann** [comment]
@goatsy feel free to provide a PR changing this file: https://github.com/webdriverio/webdriverio/blob/master/lib/helpers/mobileDetector.js

**Comment by christian-bromann** [comment]
Fixed by #2739
