### ISSUE TITLE
Force lowerCase at getCssProperty ruined case sensitive links

### ISSUE THREAD

**Issue by k03mad** [webdriverio/webdriverio#2328]
## The problem

In `parseCSS.js` helper CSS property value converted to lowercase:
https://github.com/webdriverio/webdriverio/blob/master/lib/helpers/parseCSS.js#L13

This produces some bugs with checking case sensitive links in value.

For example, this is a correct icon link:
https://st.kp.yandex.net/images/icons/arrowsRound.gif

When we get this link from CSS property `background` of the element, `getCssProperty()` converted it to:
https://st.kp.yandex.net/images/icons/arrowsround.gif
And this is not valid link, site static returns default image for not founded icon.

We can't check image response status code or anything else with such link.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 8.5.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): standalone
* if wdio testrunner, running synchronous or asynchronous tests: async

**Comment by christian-bromann** [comment]
> This produces some bugs with checking case sensitive links in value.

The problem here that some driver lowercase this value and some keep them untouched. This way at least it is a consistent result.

**Comment by k03mad** [comment]
Ok, I got it.
Thanks for answer. Maybe it's the right decision.

We will wrote custom execute command to test this cases.
