### ISSUE TITLE
waitForVisible is throws selector need to be type 'string' error

### ISSUE THREAD

**Issue by HuachuanD** [webdriverio/webdriverio#2335]
## The problem

I am running my test and once out of a few times my test will run in an opposite order and waitForVisible will complain Promise was rejected with the following reason: Error: selector needs to be typeof `string` when I hard code the string

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 6.9.5
* It is wdio testrunner
* I am running synchronous tests:
*package used wdio-jasmine-framework:

**Comment by christian-bromann** [comment]
@HuachuanD without code, a reproducible example or logs I can't do anything here. Please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
