### ISSUE TITLE
browser.timeouts does not work on IE11

### ISSUE THREAD

**Issue by germanz** [webdriverio/webdriverio#2338]
## The problem

Error is thrown when attempting to set timeout in IE11.

## Environment

* WebdriverIO version: 4.8.0

## Details

In [lib/protocol/timeouts.js](https://github.com/webdriverio/webdriverio/blob/9e0fa7e5be58afae7a60d7466b2b56a9ebf1d239/lib/protocol/timeouts.js#L16-L28) request data is not formatted according to https://www.w3.org/TR/webdriver/#set-timeouts spec. It works though in chrome, ff, edge. On IE11 however it fails, as it should be formatted for example like this:
```
{
  "script": 3000
}
```

instead of 
```
{
  "type": "script",
  "ms": 3000
}
```

hence the error below is fired.

## WebdriverIO logs

```
...
Invalid timeout type specified: ms
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:54:15.039Z'
System info: host: 'IE11WIN8_1', ip: '10.0.2.15', os.name: 'Windows 8.1', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_144'
Driver info: driver.version: unknown
Timeout expired waiting for async script
...
```

## Selenium logs
```
HTTP Status: '500' -> incorrect JSON status mapping for 'script timeout' (408 expected)
```

## Code To Reproduce Issue

```
describe('test timeout', () => {
  beforeEach(() => {
    browser.timeouts('script', 3000);
  });
});
```

## Proposed change

```
export default function timeouts (type, ms) {
    ...

    let reqData = this.desiredCapabilities.browserName === 'internet explorer' ? {
     [type]: ms
    } : {
        type: type,
        ms: ms
    };
    return this.requestHandler.create('/session/:sessionId/timeouts', reqData);
});
```

**Comment by christian-bromann** [comment]
Thanks for raising the issue. We fixed the issue and will release a new version within the next days.

**Comment by ggiunta** [comment]
Hey Guys, was this fixed already released?

**Comment by christian-bromann** [comment]
@ggiunta yes

**Comment by micschro** [comment]
If I understand the fix correctly, users would now have to set timeouts differently, depending on the driver version (pass an object for newer drivers). I think this should be documented on http://webdriver.io/api/protocol/timeouts.html

Also, while setting a timeout using an object parameter now seems to work with IEDriver 3.9.2 and selenium driver 3.3.1, retrieving the timeouts (by passing no parameter to browser.timeouts()) fails for me: 

```
GET /session/ef262c9e-b0ac-42d0-8507-dc83c8e2b24d/timeouts
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
```
