### ISSUE TITLE
browser.setValue(selector, value) gives blank error when value is undefined

### ISSUE THREAD

**Issue by UncleGus** [webdriverio/webdriverio#2339]
## The problem

I had made a call to browser.setValue() where the variable I passed as the second parameter was undefined. The error that was reported when the test failed was blank. After a little investigation and looking at the source code, I tried (in a REPL loop) the command throw new CommandError('number is bla bla bla') and the response was: ReferenceError: CommandError is not defined

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 8.4.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): default
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):

## Code To Reproduce Issue [ Good To Have ]

const selector = '#something' // need an actual input field selector here
const value; // leave as undefined
browser.setValue(selector, value);

**Comment by christian-bromann** [comment]
This would return: `Error: number or type of arguments don't agree with setValue command`. I was not able to reproduce it.
