### ISSUE TITLE
Scroll to iOS element

### ISSUE THREAD

**Issue by ericzered** [webdriverio/webdriverio#2343]
Hello,
I would like to scroll to an element on Safari mobile on my iPhone Simulator but I didn't find a way to do it. I've tried moveTo, scrollTo... nothing works.
I see that if I'm asking the location the selector name of the element, like this : browser.getLocation(selector)
it scrolls directly to the element and returns me y:0

That's a way to scroll to element, but it's not very logical... Is they're any other way to scroll to without asking for the location ?
Thanks a lot

**Comment by christian-bromann** [comment]
There is no need to scroll in WebDriver. All driver make sure that it scrolls element into the viewport. So if you really need that element in the viewport just click on it. Please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
