### ISSUE TITLE
getAttribute adds trailing / to anchor href

### ISSUE THREAD

**Issue by johnrobertallan** [webdriverio/webdriverio#2344]
## The problem

when using getAttribute instead of returning "https://www.test.com" is returns "https://www.test.com/" even though the markup is 
`<a href="https://www.test.com"></a>`

Not sure why but it is adding a trailing slash.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 6.11.0
* wdio testrunner: synchronous

## Code To Reproduce Issue [ Good To Have ]

`exports.getAttributeFromSelectorIfVisible = function (selector, attribute) {
	if (browser.isVisible(selector)) {
		return browser.getAttribute(selector, attribute);
	}
	return false;
};`

**Comment by christian-bromann** [comment]
@johnrobertallan this is not done by WebdriverIO. Not sure which browser you are running but this should be fixed in the driver.
