### ISSUE TITLE
wdio Can't visit https domain,Eg: browser.url(https://github.com/webdriverio/webdriverio/issues/new'')

### ISSUE THREAD

**Issue by lol666666** [webdriverio/webdriverio#2345]
## The problem
wdio Can't visit https domain,Eg: browser.url(https://github.com/webdriverio/webdriverio/issues/new'')

**Comment by christian-bromann** [comment]
I am sure it can open this domain. Your code misses a `"` tho. 
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
