### ISSUE TITLE
wbio is depend on selenium version 1?

### ISSUE THREAD

**Issue by zzzgit** [webdriverio/webdriverio#2348]
wbio is depend on selenium version 1?
but why there is no dependency in the package.json?

**Comment by christian-bromann** [comment]
What is wbio? What is selenium version 1? Not sure how to help u here? 
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
