### ISSUE TITLE
can I use the "POST" method?

### ISSUE THREAD

**Issue by Evoque** [webdriverio/webdriverio#2349]
the `url()` method default is "GET", can I use "POST" to send some data to my application?

**Comment by christian-bromann** [comment]
Not sure what you want to do here. If you want to send post data to your backend application use the `request` package. 
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
