### ISSUE TITLE
Multiremote doesn't work with the visual regression service

### ISSUE THREAD

**Issue by viditm** [webdriverio/webdriverio#2351]
## The problem

It seems when you try to use a multi-remote config with Visual regression service you get errors. 
Error: Please provide a visualRegression configuration with a compare method in your wdio-conf.js!

## Environment

* WebdriverIO version: 4.6.1
* Node.js version: 6.4.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: syncronous
* Additional wdio packages used (if applicable): Cucumber

Working code: 
If my conf file has capabilities of:
 ```
capabilities: [{
        browserName: "chrome",
    }],
```

Failing code:
If my conf file has capabilities of: (multi-remote)
```
capabilities: {
		myChromeBrowser: {
			desiredCapabilities: {
				browserName: 'chrome'
			}
		}
	},
```

**Comment by christian-bromann** [comment]
The service currently doesn't support multiremote. Feel free to provide a PR for the service to support it.
