### ISSUE TITLE
The filenames of screenshots cannot be changed

### ISSUE THREAD

**Issue by erwinheitzman** [webdriverio/webdriverio#2357]
## The problem

The filenames of generated screenshots cannot be changed.
Because the current filenames don't make any sense for a tester I would like to be able to change this behaviour (name of test + date + format).
It would be ideal if we could set this in the config.
Currently it is possible to use the afterTest hook to create custom behaviour the problem then is that the afterTest is triggered after the afterEach which means that the screenshots are created after any teardown methods used in the afterEach so this is not a solution.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 6.10.0
* wdio testrunner
* synchronous tests
* Additional wdio packages used (if applicable):
        wdio-junit-reporter
        wdio-mocha-framework
        wdio-selenium-standalone-service
        wdio-spec-reporter

**Comment by Efefefef** [comment]
Yes, it is a clear disadvantage
I am lucky I can do my own screenshots. But for example Allure reporter uses screenshots generated by reporter and I need to store both sets of screens. First for devs to track errors inside  travis-ci concise report and second for qa and other to have it in allure robust report.
Bad thing that taking of first screenshot takes time and second one is capturing not the same moment

**Comment by monoburn** [comment]
We create screenshots on failure only by doing nothing the afterTest method in case of non-failure. Wouldn't that work for you?:
```
#in wdio.conf:
afterTest: function (test) {
        // if test passed, ignore, else take and save screenshot.
        if (test.passed) {return;}

```

**Comment by erwinheitzman** [comment]
@monoburn no this doesn't work when using afterEach as the afterTest is triggered after the afterEach.
This means that my afterEach which resets everything runs first, and after that the afterTest is triggered which makes a screenshot of a logged out app since everything was reset.

**Comment by JulianVallee** [comment]
Here's a drop-in plugin to get that functionality.

It's a custom reporter that listens to the 'runner:screenshot' event. It then renames the error screenshots as specified via 'reporterOptions.errorshotReporter.template'. 

If you think it's missing anything give me a notice.

https://www.npmjs.com/package/wdio-errorshot-reporter

**Comment by WillBrock** [comment]
This is currently not supported in v5. Screenshots should be taken in an afterTest hook. There are upcoming plans to re-implement screenshots. Please create another ticket if this issue persists or you have concerns.
