### ISSUE TITLE
Cannot read property 'testEnv' of undefined

### ISSUE THREAD

**Issue by arunaousula9421** [webdriverio/webdriverio#2359]
Hi All,
I have added my list of URL's for different servers in a config.json file. I am trying to access them using grunt runner.

config.json
```
{
	"test":{
			"baseUrl": "http://example.com"
		},
		
	"dev":{
			"baseUrl": "http://example.ie"
		}
} 
```
And this my function for calling the **testEnv**
```
defineSupportCode(function({registerHandler}) {
	  registerHandler('BeforeFeatures', function() {
		  	var configData = require('../../data/config.json');
			console.log("Launching test in environment: ", browser.params.testEnv);
			config = configData[browser.params.testEnv];
			browser.driver.manage().window().maximize();
			browser.get(config.baseUrl);
	  });
});
```
GruntFile.js
```
module.exports = function(grunt) {
    
      // Project configuration.
      grunt.initConfig({
          webdriver: {
              test: {
                  options: {
                      configFile: "wdio.conf.js", 
                      keepAlive: false, 
                      noColor: false, 
                      args: {
                        params: {
                            testEnv: 'test'
                        },
                        verbose:false
                      }
                  }
              },
          },
      }),
    
      // Load the plugin that provides the "runner" task.
      grunt.loadNpmTasks('grunt-webdriver');
    
      // Default task(s).
      grunt.registerTask('default', ['runner']);
    
    };
```
When I am trying to run using following step it gives me above error
**ERROR: a handler errored, process exiting: src\support\hook.js:14: Cannot read property 'testEnv' of undefined**

**Comment by christian-bromann** [comment]
This doesn't work: `browser.params.testEnv` the browser object doesn't contain a `params` property. 
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by arunaousula9421** [comment]
Thanks @christian-bromann .. But I have a similar project setup in Protractor using same pattern where this actually works. Can you please tell if this works on Webdriverio as well .. if I make necessary changes.
