### ISSUE TITLE
An error occurred during running all commands

### ISSUE THREAD

**Issue by dukhanov** [webdriverio/webdriverio#2362]
## The problem

An error occurred during running all commands inside of `RequestHandler.js`

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 8.7.0
* Using [webdriver service](https://www.npmjs.com/package/wdio-webdriver-service) with geckodriver

## Details

Inside of request handler https://github.com/webdriverio/webdriverio/blob/master/lib/utils/RequestHandler.js#L227
in case of `body.value` is undefined Request Handler down with error:
![image](https://user-images.githubusercontent.com/11015670/31884846-30007378-b7f7-11e7-992a-893ba5ddd4f3.png)

## Code To fix the Issue

was:
```
if (body) {
 const errorCode = ERROR_CODES[body.status] || ERROR_CODES[body.value.error] || ERROR_CODES[-1]
...
```

can be fixed with:
```
if (body) {
  const errorCode = ERROR_CODES[body.status] || (body.value && ERROR_CODES[body.value.error]) || ERROR_CODES[-1]
...
```

**Comment by dukhanov** [comment]
Related to https://github.com/webdriverio/webdriverio/pull/2364

**Comment by christian-bromann** [comment]
Let's continue convo in #2364
