### ISSUE TITLE
JavaScript Error in IE 11 Browser

### ISSUE THREAD

**Issue by D0raemon** [webdriverio/webdriverio#2365]
## The problem

Injecting JavaScript code using WebdriverIO **_execute_** command in IE11 gives "“Error: An error occurred while executing user supplied JavaScript.”

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 6.10.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: async
* Additional wdio packages used (if applicable):
   "wdio-junit-reporter": "^0.3.0",
    "wdio-mocha-framework": "0.3.10",
    "wdio-selenium-standalone-service": "0.0.8"

## Details

Describe in more detail the problem you have been experiencing, if necessary.

Our application is being tested on multiple browsers. Test scripts are working fine on Chrome, Safari, and Firefox. However, on IE11, all of our test scripts which are injecting JavaScript code using WebdriverIO execute (http://webdriver.io/api/protocol/execute.html) command is failing with “**_Error: An error occurred while executing user supplied JavaScript._**”

Tring with different versions of Selenium and IE Driver does not seem to resolve the issue as well.

## Link to Selenium/WebdriverIO logs

WebdriverIO Error Log : 
https://gist.github.com/D0raemon/e92e59da157fa3bf3af093016db17f00

WebdriverIO Error Log Verbose: 
https://gist.github.com/D0raemon/999b43bde7119fb953abbb4ddc691183

**Comment by christian-bromann** [comment]
The code you are executing in IE seems to fail which is causing that error. 
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by fogrizovic** [comment]
Hi. I´m having the same issue when trying to inject this code

**Comment by mateen-hussain** [comment]
@D0raemon any solutions for this ?

**Comment by unickq** [comment]
Don't use arrow functions
