### ISSUE TITLE
Deprecated API functions should suggest alternatives.

### ISSUE THREAD

**Issue by thaggie** [webdriverio/webdriverio#2370]
## The problem

We currently use `buttonUp`.

In the console it writes:
> WARNING: the "buttonDown" command will be depcrecated soon. Please use a different command in order to avoid failures in your test after updating WebdriverIO.

We don't know what to use instead.

Checking the API docs http://webdriver.io/api/protocol/buttonUp.html it says:
> This command is depcrecated and will be removed soon. Make sure you don’t use it in your automation/test scripts anymore to avoid errors.

Again no help in working out what we should do instead.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: v8.8.0

## Details

We have similar issues for:
* moveTo
* buttonDown
* keys

**Comment by christian-bromann** [comment]
That is what we have planned. Feel free to propose a PR.

**Comment by thaggie** [comment]
I don't understand - are you saying you plan to remove these things and there's no alternatives?
Or are you suggesting I need to track down what the alternatives in your docs (which I have been unable to find) and submit a PR to fix your documentation and logging?

**Comment by christian-bromann** [comment]
@thaggie all these commands will be replaced with the action API which is not yet fully supported by WebdriverIO. So I think to remove these in favor of an action command.

**Comment by christian-bromann** [comment]
This is fixed and released.

**Comment by Vincento89** [comment]
Hi @thaggie did you find a way to work this around?
