### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by jochakovsky** [webdriverio/webdriverio#2371]
## The problem

When the function passed to `browser.call` returns a rejected promise, I intermittently get an error, `TypeError: Cannot read property 'split' of undefined`

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 8.7.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): wdio-mocha-framework, wdio-spec-reporter

## Details

Running the same test twice with no changes, issue only appears on second run. Worth mentioning that there is no stack trace on the first error.

```
$ ./node_modules/.bin/wdio wdio.conf.js
(node:29505) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'currentRetry' of undefined
(node:29505) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
------------------------------------------------------------------
[firefox #0-0] Session ID: 2350368f-b8a8-0748-afa8-251e7318fe94
[firefox #0-0] Spec: /Users/jochakovsky/dev/webdriverio-test/test/specs/cannotReadPropertySplitOfUndefined.js
[firefox #0-0] Running: firefox
[firefox #0-0]
[firefox #0-0] Cannot read property 'split' of undefined
[firefox #0-0]   1) should recreate the bug
[firefox #0-0]
[firefox #0-0]
[firefox #0-0] 1 failing (2s)
[firefox #0-0]
[firefox #0-0] 1) Cannot read property 'split' of undefined should recreate the bug:
[firefox #0-0] blah
[firefox #0-0] no stack available
[firefox #0-0]

$ ./node_modules/.bin/wdio wdio.conf.js
------------------------------------------------------------------
[firefox #0-0] Session ID: de6b35a8-d7d6-bf45-953e-f52a8918ad4b
[firefox #0-0] Spec: /Users/jochakovsky/dev/webdriverio-test/test/specs/cannotReadPropertySplitOfUndefined.js
[firefox #0-0] Running: firefox
[firefox #0-0]
[firefox #0-0] Cannot read property 'split' of undefined
[firefox #0-0]   1) should recreate the bug
[firefox #0-0]
[firefox #0-0]
[firefox #0-0] 2 failing (2s)
[firefox #0-0]
[firefox #0-0] 1) Cannot read property 'split' of undefined should recreate the bug:
[firefox #0-0] blah
[firefox #0-0] no stack available
[firefox #0-0]
[firefox #0-0] 2) Cannot read property 'split' of undefined should recreate the bug:
[firefox #0-0] Cannot read property 'split' of undefined
[firefox #0-0] TypeError: Cannot read property 'split' of undefined
[firefox #0-0]     at Context.<anonymous> (/Users/jochakovsky/dev/webdriverio-test/test/specs/cannotReadPropertySplitOfUndefined.js:5:17)
[firefox #0-0]     at new Promise (<anonymous>)
[firefox #0-0]     at new F (/Users/jochakovsky/dev/webdriverio-test/node_modules/core-js/library/modules/_export.js:35:28)
[firefox #0-0]
```

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

https://gist.github.com/jochakovsky/f5a2a23f111fb51eaa924d1c9be8e238

## Code To Reproduce Issue [ Good To Have ]

https://github.com/jochakovsky/webdriver-io-split-of-undefined-bug

**Comment by christian-bromann** [comment]
This issue was moved to webdriverio/wdio-sync#115

**Comment by christian-bromann** [comment]
After checking your code I discovered that your code is not quite correct:
```js
        browser.call(() => {
            return Promise.reject({
                message: "blah"
            });
        });
```
You should consider rejecting the call with an error. See also: https://github.com/petkaantonov/bluebird/blob/master/docs/docs/warning-explanations.md#warning-a-promise-was-rejected-with-a-non-error. I agree though that this should be handled more gracefully. Moving to wdio-sync where it needs to get fixed.
