### ISSUE TITLE
Synchronous calls in standalone mode?

### ISSUE THREAD

**Issue by NicoleRauch** [webdriverio/webdriverio#2372]
## The problem

I would like to be able to use synchronous calls in standalone mode as well. Are there any plans for supporting this?

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 6.7.0
* Standalone mode

## Details

From the documentation on http://webdriver.io/guide/getstarted/modes.html I take it that the synchronous test runs are only available when the tests are run with wdio. Are there any plans to support this in standalone mode as well?

(I'm asking because I want to integrate webdriver.io into tests that are being executed with FitNesse and SlimJS, therefore I cannot use the wdio runner.)

## Code To Reproduce Issue [ Good To Have ]

I would like to do this:

```
var webdriverio = require('webdriverio');
var options = {
  desiredCapabilities: {
    browserName: 'chrome' //Browser choice
  }
};

var title = webdriverio.remote(options).init().url(_url).getTitle();
console.log(title); // logs the page title to the console
```

but all I get is `{ state: 'pending' }` ...

**Comment by christian-bromann** [comment]
> I would like to be able to use synchronous calls in standalone mode as well. Are there any plans for supporting this?

This can not be supported. Please use the wdio testrunner. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by NicoleRauch** [comment]
Thanks for the quick reply!

> Please use the wdio testrunner.

As I said, this cannot be done (no need to discuss this further). Now I know how I need to proceed.

> This is not necessary an issue.

Sorry for the disruption (other projects handle this differently) and thanks for telling me!

**Comment by christian-bromann** [comment]
> Sorry for the disruption (other projects handle this differently) and thanks for telling me!

Nothing to be sorry about 😉  I recommend to use async/await syntax to make commands synchronous.

**Comment by thebarty** [comment]
@christian-bromann : I got the same wish as nicole and don't quite see how to “easily“ use the wdio-testrunner in a non-test environment. Is there a guide?
