### ISSUE TITLE
Cannot define class using Reflection

### ISSUE THREAD

**Issue by Affon** [webdriverio/webdriverio#2373]
## The problem
I can't run automated tests anymore

## Environment

OS: Linux Ubuntu 16.04
Selenium Version:  2.52.0
Browser:  Chrome

Browser Version:  Version 61.0.3163.91

* WebdriverIO version: 4.8.0
* Node.js version: 6.10.0
* Additional wdio packages used (if applicable):

wdio-cucumber-framework: 1.0.2,
wdio-dot-reporter: 0.0.9,
wdio-junit-reporter: 0.3.1,
wdio-selenium-standalone-service: 0.0.9,
wdio-spec-reporter: 0.1.2,

## Details

I'm running Selenium tests from jenkins on a linux machine. When running the tests I'm having this:
`ERROR: Cannot define class using reflection`

**Comment by christian-bromann** [comment]
@Affon Hi. This doesn't look like a WebdriverIO issue. It comes directly from the server. There is nothing we can do about this. Feel free to join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have further questions.
