### ISSUE TITLE
Do webdriverio have any method which is similar to get() in protratcor

### ISSUE THREAD

**Issue by arunaousula9421** [webdriverio/webdriverio#2379]
Hi @christian-bromann I have been trying to **getText()** by passing an index value.

For Example:
```
public get selectText() { return browser.elements('//*[@id="cc_id"]/dd/ul/li') }
public getRandomNumber(){
        var randomNumber = 1 + Math.floor(Math.random() * (this.getCount() - 1));
        console.log(randomNumber);
        return randomNumber;
    } 

    public getStaticText() : Page{
        
        var text = this.selectText.selectByIndex(this.getRandomNumber()).getText();
        console.log(text);      
        return new Page;
     }
```
which returns an error message `saying selector needs to be typeof string`.

I have used the same pattern while working on protractor using **get()** method
`this.selectText.get(this.getRandomNumber()).getText();`
which used to return me the text.

Do we have any similar method in webdriverio which I can use and get text by passing an index.

I have gone through the webdriverio documentation but didn't help me.

**Comment by christian-bromann** [comment]
I assume you want to get the text of a random option in of a select box. Do it this way:
```js
var text = $$('//*[@id="cc_id"]/dd/ul/li')[this.getRandomNumber()].getText()
```

Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
