### ISSUE TITLE
Error when running  tests on Jenkins

### ISSUE THREAD

**Issue by kiransk9** [webdriverio/webdriverio#2381]
I am trying to execute tests on Jenkins. But I am getting below errors when I try with chrome and firefox. 
Can you please let me know if we need to provide separate driver.exe file to execute in jenkins

**FireFox**
ERROR: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

**Chrome**
central entry: chromedriver
ERROR: Timed out waiting for driver server to start.

**Comment by christian-bromann** [comment]
Looks like the browser aren't installed on the default path. Closing as this is not an issue with WebdriverIO and rather a WebDriver setup. If you have further questions join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for help.

**Comment by kiransk9** [comment]
Thank you. @christian-bromann. Can you please let me know how to set the path to chromedriver.exe or firefoxdriver.exe in wdio.config file.

**Comment by christian-bromann** [comment]
@kiransk9 you can do that by specifying the path in your capabilities (e.g. chromeOptions). More info on the documentation page of the driver.

**Comment by kiransk9** [comment]
Got It thank you @christian-bromann
