### ISSUE TITLE
Unknown command when try to apply windowHandleSize method

### ISSUE THREAD

**Issue by kateyurasova** [webdriverio/webdriverio#2382]
## The problem
When I am trying to change window size by calling windowHandleSize I get unknown command error.

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 6.11.1
* wdio testrunner
* running synchronous
* Chrome Version 62.0.3202.75 (Official Build) (64-bit)

## Details

When I am trying to change window size in this way:
browser.windowHandleSize({width: 800, height: 600});
I get the following error:
Failed: unknown command: session/{sessionID}/windows/rect

I run it in Chrome browser. Previously it worked but suddenly stopped working.

## Link to Selenium/WebdriverIO logs
https://gist.github.com/kateyurasova/4a1de51f12552ef8f6e3f49c20c7f67a

## Code To Reproduce Issue [ Good To Have ]

  browser.windowHandleSize({width: 800, height: 600})
  browser.url('www.google.com')

**Comment by BorisOsipov** [comment]
@kateyurasova Which chromedriver version are you using? Have you tried to update to latest one?
If I not mistaken I ran into the same issue and the reason was old chromedriver version v2.32

**Comment by christian-bromann** [comment]
Yeah I think it has to do with the Chromedriver version you are using. Doesn't apply for me with the latest version.

**Comment by kateyurasova** [comment]
Chrome Driver version that I use is 2.33: http://icecream.me/9cea5bd056fdd983949eb36a12e27a9c

**Comment by njradford** [comment]
Encountering the same issue as well with similar environment.

**Comment by christian-bromann** [comment]
@njradford @kateyurasova have you tried using latest webdriverio version?

**Comment by kateyurasova** [comment]
I have updated webdriverio version from 4.6.2 to 4.9.6. 
For now I get the following error when I try to apply windowHandleSize method:
"Unable to connect to renderer".

By the way, there was an issue while installation. It is related to the version of Python (I have 3.10.10 installed)
http://icecream.me/a71f3381392407be5de5dbbfd206c450

**Comment by kateyurasova** [comment]
I have decreased Python version to 2.7 (it was needed for node-gyp) and performed all instructions for node-gyp (https://github.com/nodejs/node-gyp)
Then updated webdriverio to 4.9.6 version.
After that I had some troubles with chrome driver:  despite of the fact that 2.33 was installed, the version 2.31 was used while test execution. Consequently, issue with window size handing was still reproduced.
So, my next step was  re-installation of both chromedriver and selenium-standalone. 
It has resolved the issue.
