### ISSUE TITLE
How to use synchronous api outside testrunner?

### ISSUE THREAD

**Issue by thebarty** [webdriverio/webdriverio#2383]
## The problem
I'd like to use webdriverio in sync-style in my project, but there is NO switch to do it.

I read that it is possible to use wdio-testrunner's sync-feature in a standard-project (OUTSIDE test-filles) - see https://github.com/webdriverio/webdriverio/issues/2372.

Does anyone have a quick example on how to do this, especially using chromedriver?

**Comment by christian-bromann** [comment]
@codiophile you nailed the answer 👌 

If it would be easy I would have provided such a way in the docs. I you really can't use the testrunner you should consider running the code with async/await like this:

```js
(async () => {
    await browser.init()
    await browser.url("...")
})()
```
