### ISSUE TITLE
Rerun commands in case Java connection refused

### ISSUE THREAD

**Issue by lisaPthomas** [webdriverio/webdriverio#2385]
## The problem
About 10% of the time I run my tests I receive a java.net.ConnectionException Error
(Most of the time the connection is stable and my tests finish)
Error Message:
Promise was rejected with the following reason: java.net.ConnectException: Connection refused: connect
running chrome
Error: Promise was rejected with the following reason: java.net.ConnectException: Connection refused: connect
    at elementIdDisplayed("0.6421629824296522-47") - C:\_repos\Hireahelper\Hireahelper.MochaWebdriverIOTests\node_module
s\webdriverio\build\lib\commands\isVisible.js:71:55

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 8.8.1
* Java version 8 Update 151 (build 1.8.0_151-b12)
---wdio.conf.js file----

exports.config = {
    specs: [
        './test/**/*.js'
    ],
    exclude: [
    ],
    maxInstances: 10,
    capabilities: [
    {
      maxInstances: 1,
      browserName: 'chrome',
    },
     ],
    sync: true,
    logLevel: 'silent',
    coloredLogs: true,
    bail: 0,
    waitforTimeout: 3000,
    connectionRetryTimeout: 130000,
    connectionRetryCount: 5,
    services: [
      'selenium-standalone'],
    framework: 'mocha',
    mochaOpts: {
        ui: 'bdd',
        timeout: 99999999
    },
}

**Comment by christian-bromann** [comment]
> java.net.ConnectException: Connection refused: connect

It looks like the connection to the selenium server is flaky. Since I've seen this happening more and more I think it might be a good idea to rerun commands in case this happens.

**Comment by christian-bromann** [comment]
Will be further discussed in #2406
