### ISSUE TITLE
bug with getting text of multiple nodes

### ISSUE THREAD

**Issue by TrejGun** [webdriverio/webdriverio#2386]
## The problem

Looks like a problem with multiple resolved promises

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 8.3.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner + mocha
* if wdio testrunner, running synchronous or asynchronous tests: ?
* Additional wdio packages used (if applicable):
```
    "wdio-mocha-framework": "^0.5.11",
    "wdio-selenium-standalone-service": "^0.0.9",
    "webdriverio": "4.8.0",
```

## Details

When i'm trying to get text for one node it works as expected, it also sometimes works with 2-5 nodes, but definitely fails with 100

```html
<div>
<span>a</span>
<span>b</span>
<span>c</span>
<span>d</span>
<span>e</span>
<div>
```

```js
describe('Success trial', () => {
  it('contact for the first location', () => {
    browser.url("http://localhost:1337/");
    assert.equal(browser.getText("span")[0], "x");
  });
});
```

in a standalone mode

```js
const browser = remove().init();

describe('Success trial', () => {
  it('contact for the first location', () => {
    browser.url("http://localhost:1337/");
    browser.getText("span").then(text => {
       assert.equal(text[0], "x");
    });
  });
});
```
works as expected

## Link to Selenium/WebdriverIO logs

```
java.net.SocketException: Connection reset by peer (connect failed)
running chrome
Error: An unknown server-side error occurred while processing the command.
    at elementIdText("0.5827440403635895-140") - getText.js:35:50
```

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
This is actually a Selenium server issue. The server can only handle a certain amount of requests at a time. Let's make sure to throttle the amount of parallel requests to a fix number.

**Comment by christian-bromann** [comment]
Will be further discussed in #2406
