### ISSUE TITLE
After update chrome browser to the Version 62.0.3202.75 (Official Build) (64-bit) spec symbols are missed in set text and browser settings page is opening unexpectedly on enter spec symbol or capital letter.

### ISSUE THREAD

**Issue by Oksana-Eventsoft** [webdriverio/webdriverio#2387]
## The problem

After update chrome browser to the Version 62.0.3202.75 (Official Build) (64-bit) spec symbols are missed in set text and browser settings page is opening unexpectedly on enter spec symbol or capital letter.

## Environment

* WebdriverIO version: 
* Node.js version: v6.11.3
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):
"wdio-cucumber-framework": "~0.2.15",
"wdio-phantomjs-service": "~0.2.2",
"wdio-selenium-standalone-service": "0.0.8",
"wdio-spec-reporter": "~0.0.5",
 "wdio-iedriver-service": "~0.1",
 "wdio-junit-reporter": "~0.3.1",
"wdio-allure-reporter": "~0.1.2"
[selenium-standalone.txt](https://github.com/webdriverio/webdriverio/files/1433970/selenium-standalone.txt)

## Details

For example if I execute
browser.setValue(selector,"Text #1");
the result in the input will be: "Text 1" and 2 opening of settings Page
Affected MAC OS only, no issue on Windows OS
Issue reproduced on 2 devices with Sierra 10.12.6

## Link to Selenium/WebdriverIO logs - attached but seems like irrelevant to this problem.

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
@Oksana-Eventsoft sorry but this is an issue of Chromedriver not of WebdriverIO. Please raise an issue there.

**Comment by Oksana-Eventsoft** [comment]
Thanks, @christian-bromann 
https://bugs.chromium.org/p/chromedriver/issues/detail?id=2113
