### ISSUE TITLE
Yadda framework

### ISSUE THREAD

**Issue by awkwardpagong** [webdriverio/webdriverio#2388]
Is there currently support for running Yadda tests via the wdio test runner? I have a large suite of Yadda tests written using webdriverio v3 and I was hoping to migrate them over to using the wdio test runner in v4. 

I have looked around and I haven't seen any examples of the wdio test runner with yadda. And the docs only seem to mention mocha, jasmine, and cucumber for the supported frameworks. 

Any help would be much appreciated. Thanks!

**Comment by christian-bromann** [comment]
@awkwardpagong our wdio-cucumber-framework add-on provides support for Cucumber.js which I think is pretty similar to Yadda. I recommend using this. Also have a look at our cucumber boilerplate project (https://github.com/webdriverio/cucumber-boilerplate).
