### ISSUE TITLE
Update docs to reflect that this already implements the W3C version

### ISSUE THREAD

**Issue by timm-gs** [webdriverio/webdriverio#2390]
I was looking for projects that implement the W3C WebDriver spec, and came upon this one (as the `selenium-webdriver` has a problem with Firefox at the moment).

Apparently your docs at http://webdriver.io/api.html still link to the outdated version, even though `4.8.0` seems to already support the latest API according to the changelog.

**Comment by sherlock1982** [comment]
Not yet until #2392

**Comment by christian-bromann** [comment]
We already support almost all new commands and we will update the docs in every release. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
