### ISSUE TITLE
Locate elements by id is not supported in Geckodriver

### ISSUE THREAD

**Issue by sherlock1982** [webdriverio/webdriverio#2392]
## The problem

Locate elements by id is not supported in Geckodriver. So selectors like "#btnAdd" will not work.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 6.9.2
* Geckodriver 0.19.0 with Selenoid

## Details

According to [specification](https://www.w3.org/TR/webdriver/#locator-strategies) there's no locator strategy "id". Though it works in chrome. So I believe it should be removed and replaced with css selector strategy.

## Code To Reproduce Issue

```
var webdriverio = require('webdriverio');
var options = {
    host: 'selenium.3cx.test',
    desiredCapabilities: {
        enableVNC: true,
        browserName: 'firefox'
    }
};
webdriverio
    .remote(options)
    .init()
    .url('http://www.google.com')
    // Here's the issue
    .waitForVisible('#logocont').then(function(){
        console.log('Visible');
    }, function(err){
        console.log(err);
    })
    .getTitle().then(function(title) {
        console.log('Title was: ' + title);
    })
    .end();

```

Which says:

```
{ Error: Promise was rejected with the following reason: Unknown locator strategy id
  message: 'Promise was rejected with the following reason: Unknown locator strategy id',
  type: 'WaitUntilTimeoutError' }
```
#https://github.com/aerokube/selenoid/issues/261

**Comment by christian-bromann** [comment]
We can't remove the id selector just yet as it is still supported my many other drivers (also on mobile). There are two selector workarounds:
- `body #logocont`
- `css selector:#logocont`
Please use these in the meantime.

**Comment by jedwards1211** [comment]
@christian-bromann is it not possible to just have Webdriver.io use the CSS Selector strategy even if only an ID is being selected?

**Comment by christian-bromann** [comment]
@jedwards1211 theoretically yes
