### ISSUE TITLE
Web driver is still returning promise after upgrading to v4

### ISSUE THREAD

**Issue by Octavic** [webdriverio/webdriverio#2393]
After upgrading to v4, webdriver is still returning promises instead of running syncronously

$npm list webdriverio
`└── webdriverio@4.8.0`

But in code, after running
`browser.getUrl()`
results in
`{ state: 'pending' }`

I'm using selenium-standalone and mocha. Perhaps I've missed a configuration somewhere.

**Comment by christian-bromann** [comment]
@Octavic please check out the docs and use the wdio testrunner to run stuff synchronously. We also have a lot of boilerplate examples there. 
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by Octavic** [comment]
I am now using the command 
`wdio wdio.conf.js` 
to run the tests. In wdio.conf.js I have the line `{  sync: true}`, yet the getUrl() function is still returning 
`{ state: 'pending' }`

**Comment by christian-bromann** [comment]
@Octavic please have a look at our boilerplate section to get setup.
