### ISSUE TITLE
require('webdriver').remote() returns promise-like object that resolves to undefined

### ISSUE THREAD

**Issue by jedwards1211** [webdriverio/webdriverio#2397]
## The problem

Title says it all.  Whatever good intentions you may have had in doing this (making it clear to users that they don't need to `await require('webdriverio').remote(...)`?) it makes it impossible to return a webdriver client directly from any async function.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 6.5.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): standalone

## Code To Reproduce Issue [ Good To Have ]

```js
async function createBrowser(options) {
  const browser = require('webdriverio').remote(options)
  console.log(browser) // prints {fulfilled: true, value: undefined}
  await browser.init()
  ...
  return browser
}

async function doSomething() {
  const browser = await createBrowser({...})
  console.log(browser) // prints undefined
}
```

**Comment by christian-bromann** [comment]
This won't work. The `browser` variable is a promise which you can't return in an async function. I don't think this is a bug in WebdriverIO and more the way how async/await works.

**Comment by jedwards1211** [comment]
@christian-bromann what is the point of `require('webdriverio').remote(options)` returning a promise?  Of course I understand how async/await works, what I don't understand is why that function returns a promiselike object (with all of the webdriver methods attached to it).

**Comment by christian-bromann** [comment]
> I really wish the browser API object was not a promiselike thing, and I question that design decision

Well each WebDriver command makes a request which is an async operation. Those kind of things are handled with promises these days. Do you want callbacks back? 😆
