### ISSUE TITLE
Implement a request queue to avoid having to many parallel requests

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#2406]
## The problem

The Selenium server / driver can only handle a specific amount of parallel requests. If a user would run a command like `browser.getText("div")` on a page with e.g. 200 div elements, the client would try to make 200 requests at the same time. This will cause an `java.net.ConnectException: Connection refused: connect` error because the driver won't be able to handle that many parallel requests. We need a queue abstraction for making requests so that we can limit the amount of max requests we do at the same time.

**Comment by AnnemarieD** [comment]
Also happens with a div with only 3-6 elements.

**Comment by patthiel** [comment]
Need to get an idea of the changes needed to make this happen. 

* Do we know how many parallel requests selenium server can handle, or do all connections need to be queued? -- Searched and couldn't find an answer, and I know @christian-bromann had a similar question in the selenium github project.
* Do these changes only need to exist in `lib/utils/requestHandler.js`? If not, where else?
* Are the changes that in the request handler to queue requests if they're made to the same endpoint with the same session ID?

**Comment by christian-bromann** [comment]
> Do we know how many parallel requests selenium server can handle

No, it depends on the driver

> Do these changes only need to exist in lib/utils/requestHandler.js?

Yes

> Are the changes that in the request handler to queue requests if they're made to the same endpoint with the same session ID?

Not sure what you mean by that

**Comment by patthiel** [comment]
I meant, to the same command, but I'm thinking it doesn't matter if requests are made in parallel to say:
```
"/wd/hub/session/451a20439107acee47a92b29a5dddca6/screenshot"

**Comment by patthiel** [comment]
I meant, do we queue requests if they're made to the same command with the same session ID, but I think it doesn't matter if requests are made in parallel to different commands-- it'd still cause issues.

So, if understand it correctly, we want to queue all requests related that selenium session (based on [this](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2152#c9) note from chromedriver dev).



> Do we know how many parallel requests selenium server can handle

>>No, it depends on the driver

Should we queue for all or specific browsers then?

**Comment by christian-bromann** [comment]
> So, if understand it correctly, we want to queue all requests related that selenium session (based on this note from chromedriver dev).

Yes, we need to throttle requests to a specific driver running a specific session.

> Should we queue for all or specific browsers then?

I think throttle it per session would be fine.

**Comment by jedwards1211** [comment]
@christian-bromann is there any way to work around this with `browser.elements` or is the monadic structure too limiting to enable serial operations over an array of elements?

**Comment by jedwards1211** [comment]
This is the workaround I was able to figure out from the documentation...let me know if there's a better way to accomplish this that isn't documented:
```js
export default async function getText(selector: string): Promise<string | Array<string>> {
  const {value: elements} = await browser.elements(selector)
  if (elements.length === 1) return (await browser.elementIdText(elements[0].ELEMENT)).value
  const text = []
  for (let i = 0; i < elements.length; i++) {
    text.push((await browser.elementIdText(elements[i].ELEMENT)).value)
  }
  return text
}
```

**Comment by mmendieta** [comment]
Hi, new to these threads. I started using webdriver.io about 2 months ago, and just started running into these issues  java.net.ConnectException: Connection refused: connect
running chrome
Error: Promise was rejected with the following reason: java.net.ConnectException: Connection refused: connect
    at elementIdDisplayed("0.5152421407494441-8") - C:\Projects\Lego\salesforceEditReport\node_modules\webdriverio\build\lib\commands\isVisible.js:71:55.  

Has this issue been resolved or received a solution/work-around? I see the code above, not sure exactly where that would go. I've googled a lot and seem to only find this thread as a resource.

Any help is much appreciated, thanks!

**Comment by pjrwebdeveloper** [comment]
@jedwards1211 I'm fairly new to WebdriverIO and I am also getting this error when trying to get an array using getText(). Can you please explain the work around in more detail. I'm not sure where to put the code.
Thanks in advance for your reply.

**Comment by jedwards1211** [comment]
@pjrwebdeveloper you can put it in its own file, import the `getText` function in your test files, and call `getText` with the same selector as you would pass to `browser.getText`.  It gets an array of element ids first and then gets the text for each element id one after another.  If you're using `wdio-sync` (you probably are) you don't need to use the `async`/`await` keywords.

**Comment by AnnemarieD** [comment]
Workaround we use because of this issue:
`            browser.addCommand('customSynchronouslyGetTexts', selector => $$(selector).map(el => el.getText())); // eslint-disable-line no-undef
`
When using that custom command, we don't run into this issue. At least not with our div's. We do not get div's with 200 elements though.

**Comment by malliapi** [comment]
+1 can we speed this up?

**Comment by christian-bromann** [comment]
> +1 can we speed this up?

Feel free to propose a PR 😉 this would be the fastest way to get this fixed!

**Comment by ckurban** [comment]
Any update or progress on this ticket? Can someone suggest me a workaround ?

**Comment by christian-bromann** [comment]
@ckurban if you run into this issue there is probably something wrong with your testcode because you should not deal with more than 10 elements or so.

**Comment by ckurban** [comment]
@christian-bromann I am looping thru the elements and I have 2 nested loop. One to getText() from the listed items/elements and inside loop to get actual value from the list. For now, I have 5 items in each list, in total that would be 25. Any suggestion to suppress this warning ?

**Comment by luckyincode** [comment]
@christian-bromann I just want to point out that this is happening on fewer than 10 items.

**Comment by caleb005** [comment]
@luckyincode we found it happen when too many tests were running in parallel. Was this how it happened on your end or was it just a single test with 10 items?

**Comment by luckyincode** [comment]
@caleb005 When I discovered I was having this problem I was working through REPL to develop my tests.  The interesting part was having no problem getting the items returned.  When I ran the tests, however, I discovered this issue.  At the time I was dealing with roughly 6 items and 3 parallel tests (safari, chrome, firefox) locally.

When you say "too many....in parallel" what does that look like?

**Comment by caleb005** [comment]
Originally we had 10 browser windows running and when cut in half the issue was no longer there. However, reducing the possible elements to search for text in also helped. Just wondered if reducing your maxInstances would help?

**Comment by lukeowen89** [comment]
Might just be specific to my setup but I found that switching to the latest version of Chromedriver and Selenium resolved all of my connection refused issues. If you're following the setup tutorial on webdriver.io make sure you change your selenium server start up command from geckodriver to chromedriver like this...

` java -jar -Dwebdriver.chrome.driver=./chromedriver selenium-server-standalone-3.8.1.jar`

You'll also need to remember to change the browsername in wdio.conf.js from Firefox to chrome.

**Comment by KaelBaldwin** [comment]
I'm running into this problem just because I'm looping through a table and checking each row for a row that matches a certain set of data.

So I'm running a getText() on each rows cells and it's consistently failing.

Maybe a well placed sleep somewhere will fix it, but I haven't had any luck yet.

**Comment by abdullahawara** [comment]
Hi @christian-bromann 

I'm still getting this **extremely annoying exception** all the time:
```
java.net.ConnectException: Connection refused: connect
at elementIdDisplayed....
```
It happens on Windows always at the same command (in my case at least) 
```
function waitUntilTextChangesSafely(selector, oldText) {
        if (browser.isVisible(selector)) {
                console.log('element is currently visible');
                console.log('Now, wait for a text change. Do not worry, in my real example I trim the strings before comparing them'); 

                var counter = 0;
                while (browser.getText(selector) === oldText && counter++ < 10) {
                        browser.pause(1000);
                }
        }

        // I do not care if text didn't change. Do not throw an exception!
}
```.
Restarting selenium-standalone didn't help.

To solve this issue either I need to replace `isVisible()` with a 10 seconds wait (which is very bad solution) or I need to get `isVisible()` to work. Note: I think the element is available when this run, but it fails immediately for some reason.

**Comment by christian-bromann** [comment]
@abdullahawara how many elements you are querying with `selector`? If it matches 10-20 elements that even a single `isVisible` command can cause this exception as WebdriverIO is doing 10 parallel requests.

**Comment by abdullahawara** [comment]
Hmm, makes sense. There is  almost 12 elements in the page that matches this selector. Will try to figure out another selector. Thanks @christian-bromann.

**Comment by christian-bromann** [comment]
We will implement an autofix for this in v5

**Comment by christian-bromann** [comment]
Does anyone have some sort of reproducible example?

**Comment by abhimassive** [comment]
waiting eagerly for v5

**Comment by jedwards1211** [comment]
@christian-bromann I've always been confused what people mean by "autofix" in software development, how does it differ from other kinds of fixes?

**Comment by jedwards1211** [comment]
I was just asking what it means, I searched for a software engineering definition, habe es jedoch "vergooglet"

**Comment by DonnaZhang** [comment]
@christian-bromann  I always meet this issue (UnhandledPromiseRejectionWarning: Error: java.net.ConnectException: Connection refused) while I am using chrome but when I switch to firefox and the issue fixed ; But I meet different an issue , because I can't use client.frame(id ) function to help locate the elements inside iframe when using firefox.
This issue happened every time I dump into this page when using chrome. Not sure it is because there are 14 iframes in this page which caused too much parallel . Do you have any suggestions, or any walkaround ?
![image](https://user-images.githubusercontent.com/45227543/48830720-39875e80-edb0-11e8-87e1-62fcca4d937b.png)

**Comment by VKnightUT** [comment]
@christian-bromann I would like to second what @DonnaZhang has stated. I am running into this connection refused all the time. From the screenshot it looks like a page for salesforce. This is the same type of site we are trying to test and there are two pages that it comes up in randomly. One has 4 iframes and the second has 13 iframes. 

We are running with WDIO test runner on the Jasmine test framework with Chrome.

Here is what I have tried so far and have even opened a ticket with Salesforce to see if they can see what might be happening on their end.

Possible causes and results of my research and testing:
1. Too many threads running in parallel - We only run one test at a time sequentially
2. Test locators coming back with too many elements, such as over 200. - Our element locators are very specific and only come back with 1 result at any given time
3. Thread pool size needs to be increased - Set threadpool size to the max 128 in the configuration file (and verified it was setting it correctly) didn't have any effect on the error coming up.
4. Tried adding a brower.reload() between tests and browser.end() between tests. 
5. Tried the retry flaky tests suggestions both for Jasmine and Mocha listed for the WebdriverIO project on this page and neither worked. The connection refused error doesn't seem to be caught by the retries and completely jumps out of the test execution. As such the retries doesn't help at all. http://webdriver.io/guide/testrunner/retry.html
6. Tried the WebdriverIO error handling found on the following page. This wasn't catching the error at all, which it should be catching it if there was a browser error. http://webdriver.io/guide/usage/eventhandling.html
7. Added a try/catch block around each test and the catch block wasn't catching and retrying the tests. 

Everything here leads me to believe this is a Selenium issue, not an issue with the tests or the WebdriverIO framework. Have you heard anything about this coming up recently?

**Comment by abjerstedt** [comment]
@VKnightUT How many instance are you running at one time of selenium standalone on a single machine (this is the most common reason for the connection refused error)?

**Comment by VKnightUT** [comment]
@abjerstedt I'm only running one instance at a time on a single machine.

**Comment by abjerstedt** [comment]
@VKnightUT, @DonnaZhang can i get you guys to post some code in the area that your test is failing, as well as share your current chrome version and chrome driver versions?

**Comment by VKnightUT** [comment]
I would be happy to give you one example: 

Chrome Version 70.0.3538.110
Chromedriver Version 2.44.1

I use a ton of page objects and functions so let me know if you'd like to see the underlying code on any of these functions. The error always happens on the line "Job.landing.lnkRecentRecordIdFirst.click();" in my test case below. It logs in and goes to the correct page, it finds the element and clicks on it correctly. It is right after that where the test freezes and then gives me the error before the next step. 

'use strict'
var HousingUserData = require('../../testData/HousingUserData');
import { LoginPageFunctions } from '../commonFunctions/LoginPageFunctions';
var login = new LoginPageFunctions();
var Job = new sfPage(object.Job);

beforeEach(function () {
        login.loginAsFoxUser(HousingUserData.HOUSING_COORDINATOR_CHG);
        console.log("Browser session ID: " + browser.sessionId);
    });

    it('New Housing Request from Job', function() {
        console.log("Step: Navigate to a job.");
        Job.landing.load();
        Job.landing.lnkRecentRecordIdFirst.click();

        console.log("Step: Click New Housing Request Button");
        Job.detail.btnStandard("Create New Housing Request").click();

        console.log("Expected Result: User is taken to New Housing Request Page");
        expect(HR.recordType.isLoadedSelectType()).toBe(true);
        HrRecordTypeCheck();
    });

Functions from other classes that are shown above: 

load() {
        console.log("Loading the home page for the object: " + this.object.name);
        this.open(Routes.BASE_SALESFORCE_URL + this.object.id);
    }

get lnkRecentRecordIdFirst() {
        console.log("Getting the first record ID from list of recent records.");
        return browser.element("//div[@class='pbBody']//tr[contains(@class, 'first')]/th/a");
    }

btnStandard(name) {
        var selector = ".btn[value='" + name + "']";
        console.log("Getting standard button with name: " + name);
        browser.waitForExist(selector);
        return browser.element(selector);
    }

**Comment by DonnaZhang** [comment]
@abjerstedt 
ChromeDriver 2.41.578706 
Google Chrome | 70.0.3538.102 (Official Build) (64-bit)

Actually no matter I did to drump into this page I will got this issue:
```
 browser.click(`//th//a[contains(.,"${AccountName}")]`)

```

**Comment by christian-bromann** [comment]
Did someone had the same experiences with v5? It comes with a request retry which should mitigate this issue. Any feedback would be much appreciated.

**Comment by VKnightUT** [comment]
> Did someone had the same experiences with v5? It comes with a request retry which should mitigate this issue. Any feedback would be much appreciated.

I tried upgrading to check on this issue last week and ran into this issue: https://github.com/webdriverio/webdriverio/issues/3256

I will try the fix you suggested on that issue to get upgraded and see if this comes up again and will update this ticket.

**Comment by christian-bromann** [comment]
Given that I haven't heard about this problem anymore I will go ahead and close this.
