### ISSUE TITLE
waitForText does not show line number in test when element is not found

### ISSUE THREAD

**Issue by jgoldring** [webdriverio/webdriverio#2407]
## The problem

When referencing a page element with waitForText(), if the element is not found on the page, no line number is given for the offending wait in the test.

For example:
in a page.js file you have:
`example: { get: function () { return browser.element("#example"); } },`

Within a test.js file you have:
`examplePage.example.waitForText();`

If the "#example" selector is not found on the page, you will get an error indicating:
```
An element could not be located on the page using the given search parameters ("#example").
running chrome
Error: An element could not be located on the page using the given search parameters ("#example").
    at elements("#example") - getText.js:18:17
    at getText("#example") - waitForText.js:73:22
```
No line reference is given to the actual test, which makes it difficult to see which waitForText is tripping up in a test if you have multiples on the same element.

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 8.8.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable): wdio-mocha-framework

**Comment by christian-bromann** [comment]
Unfortunately we have no access to the original execution line number where the command was executed. The stacktrace is compiled by WebdriverIO by tracing the command history. This takes some more effort to fix it.

**Comment by christian-bromann** [comment]
Hey,

we update the core architecture of WebdriverIO and with that a lot of implementation details that might make this issue obsolete. Please try with the latest version of WebdriverIO and verify if this still occurs. If so please open a new issue and we will tackle it asap.

Thanks!
