### ISSUE TITLE
run webdriverio synchronously in standalone mode

### ISSUE THREAD

**Issue by troublemkr** [webdriverio/webdriverio#2408]
## The problem

I'm going absolutely nuts trying to debug a webdriverio test using Chromedriver. You simply cannot step through the code because webdriverio commands are asynchronous and the browser session is out of sync with the test.

This is frustrating because reading the docs, it seems you need a testing framework like Chai or wdio to generate tests, but this seems like a lot of work just to have procedural synchronous commands.

I just need to crawl some websites using webdriverio but this asynchronous commands are far too difficult to debug using Chrome devtools.

Is there any way to force webdriverio to behave synchronously?

ex)

`var loadedPage = webdriverio.remote(options).init().url('https://google.com');`

except `loadedPage` is not ready and is undefined by the time debug moves to next line.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 8
* [Standalone mode ]](http://webdriver.io/guide/getstarted/modes.html):

**Comment by christian-bromann** [comment]
> Is there any way to force webdriverio to behave synchronously?

Yes, as stated [in the docs](http://webdriver.io/guide/getstarted/modes.html) you need to use the wdio testrunner to run commands synchronously.
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
