### ISSUE TITLE
Custom Commands page wrong Syntax

### ISSUE THREAD

**Issue by ManuelTS** [webdriverio/webdriverio#2409]
On http://webdriver.io/guide/usage/customcommands.html two times invalid javascript syntax is displayed 
```, function async (``` in the code examples.

**Comment by christian-bromann** [comment]
@ManuelTS why not propose a PR?

**Comment by ManuelTS** [comment]
PR stands for what? I guess wildly for a solution, well this is simple just change it to
`async function' on both cases and it is done.

**Comment by TuHuynhVan** [comment]
https://github.com/webdriverio/webdriverio/pull/2411

**Comment by christian-bromann** [comment]
Thanks @TuHuynhVan

**Comment by ManuelTS** [comment]
And thanks @TuHuynhVan  and @christian-bromann to be unable to simply answer my question with _pull request_, since than I could have made a PR myself.
