### ISSUE TITLE
"Error: Remote end send an unknown status code." when checking visibility of an hidden element on firefox

### ISSUE THREAD

**Issue by Waals** [webdriverio/webdriverio#2410]
## The problem

Hi everyone,
I'm trying to check the visibility of an element on Firefox using the method "isVisible" but that's not working.
I want to check if an element '.menu' is not visible by doing `browser.isVisible('.menu')`
Everytime I try, I'm facing this error : 
```
Error: Remote end send an unknown status code.
    ...
    at Promise.F (/install/node_modules/core-js/library/modules/_export.js:35:28)
    at elementIdDisplayed("a6e74e9c-60eb-4118-9685-ef1a92cf78fd") - isVisible.js:71:55
```

After checking the logs of what have been sent to the selenium server, I find:
```
INFO - Handler thread for session 30949426-6cf8-4f08-9eb9-7757430e1d13 (firefox): Executing GET on /session/30949426-6cf8-4f08-9eb9-7757430e1d13/element/a6e74e9c-60eb-4118-9685-ef1a92cf78fd/displayed (handler: ServicedSession)
INFO - To downstream: {"value":false}
```

This error is only happening when the element is not visible. If the element is visible, I get `{"value":true}` in the downstream and everything works fine.
On chrome, everything works fine, element visible or not.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 6
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: Synchronous
* Additional wdio packages used (if applicable):

**Comment by christian-bromann** [comment]
This was just fixed with https://github.com/webdriverio/webdriverio/commit/752bb60b09cc3aeba526eae1d679a5a0fcca4e19
