### ISSUE TITLE
Unable to click label connected to hidden input

### ISSUE THREAD

**Issue by SassNinja** [webdriverio/webdriverio#2413]
I'm facing a problem while building some new tests with wdio.

There's a pseudo radio button that is a label which has got all the styling. Via the for-attribute it is bound to a native radio input which is hidden.
So triggering a click on the input naturally doesn't work. But what surprises me is that triggering a click on the connected label doesn't work either!

````
browser.click('[for="abc"]');
=> Cannot read property 'indexOf' of undefined
````
Seems to me that internally the webdriver is following the connection to the input and detects the hidden state.
A possible workaround is to use the `moveTo` method for the mouse and `leftClick` afterwards.
But I'm worried regarding the mobile devices tests we're going to do in future plus it feels like a hack.

Would be great to tell the webdriver to not follow the connection to the hidden input and just trigger the click.

Does anyone has an idea how to achieve this?

**Environment**

* WebdriverIO version: 4.6.2
* Node.js version: 8.6.0
* wdio testrunner + selenium standalone service

**Comment by christian-bromann** [comment]
@SassNinja can you please share a reproducible example and the driver logs? Otherwise it won't be possible for anyone to know what is going on.

**Comment by SassNinja** [comment]
@christian-bromann thanks for the quick reply!

While I was creating a simple example to reproduce the issue, I noticed the actual label had 0px height and its pseudo ::before element was styled instead.

So the webdriver did not follow the label's connection to the input but the label was just not clickable due to zero height. Since pseudo element selectors are not supported (yet?) I'm going to work over the styling.

I'm closing this issue because it's obviously no bug.

**Comment by christian-bromann** [comment]
> I'm closing this issue because it's obviously no bug.

Thanks for investigating this. I don't think pseudo selectors are supported yet.

**Comment by ckurban** [comment]
@SassNinja could you please share mini code snippet of solution you applied ? or what solution did you apply ? I am facing the same issue with hidden element and label. Thanks
