### ISSUE TITLE
Unable to get sessionId in before hook when using Firefox

### ISSUE THREAD

**Issue by sherlock1982** [webdriverio/webdriverio#2414]
## The problem

I'm unable to get session id in before hook for Firefox.
It equals undefined when using geckodriver. When using chromedriver it prints session identifier.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 6.9.2
* Geckodriver 1.10.0 and chromedriver 2.33.2 standalone
* synchronous tests
* framework mocha, no additional services installed

## Code To Reproduce Issue

In wdio.conf.js:

    before: function (capabilities, specs) {
        console.log(browser.sessionId);
    },

**Comment by TuHuynhVan** [comment]
You can't get that even with chromedriver. Please use ```browser.requestHandler.sessionID```

**Comment by TuHuynhVan** [comment]
@sherlock1982
I just checked again for ```browser.sessionId```. That worked for me on both ff and chrome testing.
Seems equal ```browser.requestHandler.sessionID```

**Comment by sherlock1982** [comment]
`browser.requestHandler.sessionID` works for me so I'm satisfied. Firefox doesn't work with `browser.sessionId`. You can close it if it's ok

**Comment by christian-bromann** [comment]
mhm I think that has changed with the new WebDriver spec changes. It would be definitely better to access it over the `browser` instance.
