### ISSUE TITLE
Watch mode only runs mocha hooks once

### ISSUE THREAD

**Issue by kswope** [webdriverio/webdriverio#2419]
Looks like --watch is a recently added flag and there are already some open issues with it.  Another problem is that mocha's before, beforeEach, after, afterEach are only running once. 

EDIT: I should add these hooks are defined in my own setup files and not wdio.conf.

EDIT: Tried the mocha hooks in wdio's config file, they seem to work ok.

**Comment by christian-bromann** [comment]
> EDIT: I should add these hooks are defined in my own setup files and not wdio.conf.

Can you provide a reproducible example so I see the setup?

**Comment by kswope** [comment]
I can't give you an example right away, but I found an important clue.

If the before() is in the same file as the tests then it will run again every time in watch mode.
If the before() is outside the file, like in a require('setup') it is only run for the first test modification.
This is not a problem with mocha run by itself.
Note:  I have my before() and after() hooks in a setup.js file because they are shared between e2e tests (with webdriver.io) and api tests (using just mocha and chai-http)

**Comment by christian-bromann** [comment]
This might can get fixed deleting the node cache or something.

**Comment by kswope** [comment]
Maybe another clue, test files aren't reloaded either.

**Comment by kswope** [comment]
If I have a single test, called test1, running watch mode, and I rename that test to test2, then test1 and test 2 are run, even though there is no test1 in any files.

I suspect that watch mode isn't cleaning up between runs.  In my case there are two symptoms of this.

Lingering tests: tells me that the modified file is being loaded again, but mocha related modules aren't being reloaded, so old unit tests are accumulating.

Explains why my before() in a setup file is only being run once.  maybe before() is being cleaned out, but since setup.js is cached, its not reinstalling before().

Probably a fix involves clearing out require.cache between runs.  Something like this
```
      Object.keys( require.cache ).forEach( key => { 
        delete require.cache[ key ] 
      } )
```

**Comment by christian-bromann** [comment]
We will reimplement the watch mode in v5 and try to mitigate this issue. Thanks!
