### ISSUE TITLE
Finding with a css selector of an id composed with a class no longer works since 4.9.0

### ISSUE THREAD

**Issue by lennym** [webdriverio/webdriverio#2422]
## The problem

[This commit](https://github.com/webdriverio/webdriverio/commit/a4a77be8b13ad9bad9793184e6559eecc9f2a7f1) added support for "Android ids" but as a side-effect means that any css selector with an id composed with a class will no longer work, as it is detected to be an id, and not a css selector.

For example, in our test suites we use `#field-id.validation-error` to assert that a particular field is showing as invalid. Updating from 4.8.x to 4.9.x causes all of our test suites to now fail.

I'm uncertain as to the format of the Android id locators as it's not a platform I normally work on, but looking at the test added in the commit above, it seems that they may follow a particular format (with colons and slashes). If this is the case, then it would be good to make the regex to match an Android id locator stricter, so that valid css selectors are not (incorrectly) assumed to be ids.

## Environment

* WebdriverIO version: All since 4.9.0
* Node.js version: All

**Comment by christian-bromann** [comment]
Will revert that commit then.

**Comment by christian-bromann** [comment]
Change was reverted and published as
```
 webdriverio 4.9.5 published 🎉
```

**Comment by lennym** [comment]
Amazing. Thanks so much for the quick fix!
