### ISSUE TITLE
before() hook in config not working

### ISSUE THREAD

**Issue by evan-scott-zocdoc** [webdriverio/webdriverio#2430]
## The problem

`before()` in the configuration is not being run since `4.9.x`

## Environment

* WebdriverIO version: `webdriverio@4.9.5`
* Node.js version: `8.9.1`
* Additional wdio packages used (if applicable): `wdio-framework-jasmine`, `wdio-selenium-standalone-service`

## Details

We are running a function to set up some commands in the `before()` hook. I can confirm that downgrading to `4.8.x` restores the functionality, so the regression occurred in `4.9.0`.

**Comment by christian-bromann** [comment]
Fixed by #2428

**Comment by probablyup** [comment]
@christian-bromann thank you!

**Comment by tiecongli** [comment]
I am using "webdriverio": "5.16.2" and seeing before() hook is not being called. May I know which version has the fix?

**Comment by christian-bromann** [comment]
> "webdriverio": "5.16.2

This version is deprecated for a while and I recommend to update your WebdriverIO setup as it very likely include fixes for issues you see.
