### ISSUE TITLE
Give user control of when session is started

### ISSUE THREAD

**Issue by codiophile** [webdriverio/webdriverio#2431]
## The problem

There are a few problems that would be solved by this. These are the main problems we are having:

1. **It would be possible to retry if session creation fails**
This is the main problem for us. We have devices that are temporarily unavailable, but within a few minutes they are available again. Today, this simply means that the scenarios that were supposed to run in that session never executed. If we would manually be calling `browser.init()` and `browser.end()`, we could catch the exception and try again.

2. **It would be possible to have one session per scenario**
We would like to inject test data into the app using process arguments. These are set in the capabilities and cannot be changed within a session. Today we would have to group scenarios that use the same test data in the same feature file or have one scenario per feature file. 

## Details

The main problem we need to solve is retrying when session creation fails. I know this isn't the only way to solve it, but it's an easy way to solve it and it addresses the main drawback of using the testrunner. We could introduce this in 4.X.X as a non breaking change, by hiding it behind a configuration flag or a callback, e.g. `shouldStartSession()`. Then we could make it the default behaviour in version 5.X.X if desirable. I think a callback might be nice, because different specs could have different behaviour and it would be possible to migrate one spec at a time.

If there is already a way to accomplish retry that we may have overlooked, please let me know, but we have spent quite some effort trying to find a way already. Likewise, if there's another easier or quicker solution that we could go after in the interim, I'd appreciate if you could let me know. 

If there is any reason why this isn't desirable or very hard to implement, that's something I'd like to know as well. I don't see any drawback with giving the user more options and it doesn't seem like it should be too difficult to accomplish.

**Comment by christian-bromann** [comment]
> It would be possible to retry if session creation fails

I am not sure if this should be handled by a WebDriver client library. This should rather be managed by a device pool manager that checks available devices and creates an Appium node that registers itself to a hub if a device becomes available again.



> If we would manually be calling browser.init() and browser.end(), we could catch the exception and try again.

That doesn't not sound like a good idea to me. It would mean that some of the testrunner hooks won't get executed which is an essential functionality of wdio services.

> It would be possible to have one session per scenario

Not sure what you mean by that but wdio is creating one session per scenario.

Happy to discuss this further but I don't see any necessity to change the current behavior of this.

**Comment by codiophile** [comment]
@christian-bromann 
> Happy to discuss this further but I don't see any necessity to change the current behavior of this.

Alright, here comes the discussion. :)

> I am not sure if this should be handled by a WebDriver client library. This should rather be managed by a device pool manager that checks available devices and creates an Appium node that registers itself to a hub if a device becomes available again.

This would of course be ideal, but this is not the reality. We are relying on a third party to manage the devices, so we have little control over any device pool manager and we simply can't do much about that other than reporting the issue, which has already been done. 

Even if we had more control, it still wouldn't help us much, because we are running against specific devices by providing the UDID of that device. If we want to verify that the app is working on an iPhone 5 with iOS 9, it's not like we have a whole bunch of them, we only have one. If that device isn't currently working, there's no other device that we could use and a device pool manager wouldn't help us.

We are having a lot of problems with device stability, but even when executing on a local simulator, session creation fails for no apparent reason and retrying solves the problem every time. I've never worked on a project where session creation has worked reliably every time, so I think a lot of people would benefit from this.

> That doesn't not sound like a good idea to me. It would mean that some of the testrunner hooks won't get executed which is an essential functionality of wdio services.

I assume that you are talking about the `beforeSession()` and after `afterSession()` hooks. Is there any reason why these couldn't be called by `browser.init()` and `browser.end()`?

> Not sure what you mean by that but wdio is creating one session per scenario.

This is not the primary issue, but are you sure about that? `beforeSession()` is called before `beforeFeature()`, rather than `beforeScenario()`. To me that indicates that we get one session per feature rather than scenario, but I haven't dug much deeper than that. I also remember reading something about it in the documentation. My understanding is that wdio launches one process per spec and for cucumber a spec is one feature or rather feature file and each process creates one session. If I've misunderstood this, it would be nice to get that clarified, but it wouldn't change the requirements we have for retrying.

## Alternative Solution

Upon failure we would also like to reboot the device, to increase the probability of the device being in a usable state upon retry. So if you don't want to give us this level of control, I think the second best is a callback upon failure, where we have the opportunity to reboot the device and if we return true, webdriverio tries again.

If we go for this solution, we also need a callback for when it fails to delete the session, because if a device fails in the middle of a session, that's where the problem appears.

I prefer my originally proposed solution, because it it gives us the control we need to deal with not only this issue, but future issues as well, without having to change webdriverio.
