### ISSUE TITLE
4.9.x Broke wdio-visual-regression-service

### ISSUE THREAD

**Issue by mhemesath** [webdriverio/webdriverio#2432]
## The problem

Updating from 4.8.0 to 4.9.6 broke [wdio-visual-regression-service](https://github.com/zinserjan/wdio-visual-regression-service). The calls seem to just return undefined.

All else equal, changing the version of webdriverio back to 4.8.0 fixes this issue.

## Environment

* WebdriverIO version: 4.9.x
* Node.js version: 8.4.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): wdio-visual-regression-service

## Link to Selenium/WebdriverIO logs

https://gist.github.com/mhemesath/1a0146915f128cb707e1a4b8f7eb5a47

## Code To Reproduce Issue [ Good To Have ]

```js
describe('comparing screenshots', () => {
  it('takes a picture of google', () => {
    browser.url('http://www.google.com');
    const screenshots = browser.checkDocument();
    console.log(screenshots); // [undefined]
  });
});
```

**Comment by msta** [comment]
Not going to provide a full stack-trace, but FYI this or another related issue on 4.9.x also breaks new versions of Spectron. https://github.com/electron/spectron/pull/245

**Comment by christian-bromann** [comment]
@msta this issue is unrelated to that

**Comment by mhemesath** [comment]
I'm guessing this commit broke functionality and it looks intentional https://github.com/webdriverio/webdriverio/commit/b39abc41422034beafd6a3caf524197e94c1e6ac#diff-2305aa79aa2aa89aafbe4d87e936ff28

**Comment by christian-bromann** [comment]
@jankcat can you verify this?

**Comment by mhemesath** [comment]
I reverted those changes locally and it didn't seem to fix the issue.  I'll continue digging into this but any help would be greatly appreciated.

**Comment by mhemesath** [comment]
Reverting the `package.json` fixes the issue. It seems it was a dependency update that may have caused this... still investigating

**Comment by mhemesath** [comment]
Reverting deepmerge back to 1.x fixes the issue. I passed `{ clone: false }` to every `merge()` call and can't seem to fix it.
