### ISSUE TITLE
Webdriver API are not working with an element which has more than 10 items on the page

### ISSUE THREAD

**Issue by JoeRattanamaneesilp** [webdriverio/webdriverio#2438]
## The problem

Some standard webdriver API are not working with an element which has more than 10 items on the page.

## Environment

* WebdriverIO version: Not sure how to check
* Node.js version: 6.1.0
* Run the test with phantomJs in ubuntu

## Details

This problem has started happening since Friday Morning (10th Nov 2017). It may be an effect of a commit from Thursday (9th Nov 2017). The problem is that the automation code that it used to work fine has started failing because of `function timed out after 60000 milliseconds`. Please see the screenshot below.

![image](https://user-images.githubusercontent.com/14726381/32712130-064f49ae-c897-11e7-980d-b85abf4cb6ca.png)

I have investigated and found that if I reduce the number of `a` from 14 to 7. The code will work fine.

## Code To Reproduce Issue [ Good To Have ]

Please see the above screenshot. This problem also happens with `getText`. So you can try to reproduce with `getText`.

**Comment by christian-bromann** [comment]
Hey Joe,

sorry but this doesn't necessary mean that it is an issue with WebdriverIO. It could also be a problem with the page (maybe the selector has changed). The screenshot doesn't help at all. There are no logs that could help me to understand what the issue could be. Therefor all I can do here is to close the issue until you can prove that there is indeed a regression in WebdriverIO. Also feel free to join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
