### ISSUE TITLE
Elements not returning WebElement

### ISSUE THREAD

**Issue by EndeNeu** [webdriverio/webdriverio#244]
I'm trying to get more than one element using the `.elements` function, as stated on the github page it is currently implemented as a wire protocol binding. According to the documentation [here](https://code.google.com/p/selenium/wiki/JsonWireProtocol#POST_/session/:sessionId/element/:id/elements) it should return a list of WebElements: 

> Returns:
> {Array.<{ELEMENT:string}>} A list of WebElement JSON objects for the located elements.

This is my test code:

```
var webdriverjs = require('webdriverjs'),

describe('my webdriverjs tests', function () {
  this.timeout(99999999);
  var client = {};

  before(function () {
    client = webdriverjs.remote({ desiredCapabilities: {browserName: 'chrome'} });
    client.init();
  });

  it('test', function (done) {
    client
      .url('http://www.google.com/')
      .elements('li', function (err, value) {
        console.log(value);
      });
    client.call(done);
  });

  after(function (done) {
    client.end(done);
  });
});
```

And this is the console output:

```
{ status: 0,
  sessionId: '72077321-ac96-47bc-9e6e-c14168084270',
  value: 
   [ { ELEMENT: '0' },
     { ELEMENT: '1' },
     { ELEMENT: '2' },
     { ELEMENT: '3' },
     { ELEMENT: '4' },
     { ELEMENT: '5' },
     { ELEMENT: '6' },
     { ELEMENT: '7' },
     { ELEMENT: '8' },
     { ELEMENT: '9' },
     { ELEMENT: '10' },
     { ELEMENT: '11' },
     { ELEMENT: '12' },
     { ELEMENT: '13' } ],
  state: 'success',
  class: 'org.openqa.selenium.remote.Response',
  hCode: 728716887 
}
```

Am I overlooking something or is it a WebDriver problem?

**Comment by neoadventist** [comment]
@EndeNeu @christian-bromann any pointers on how to use such a list? I'm trying to use it with the `.elementIdElement(rows[0].value.ELEMENT,rows[0].selector)` but I get a complaint saying that the element could not be located on the page :(

**Comment by roydude** [comment]
@neoadventist - the array is actually on the 'value' item (which should really be called 'values' for clarity IMO), so you'd want to do: ```... rows.value[0].ELEMENT ...```

I was also expecting .elements() to just return an array of elements (like other webdriver implementations) so I could use ```elements[0].getText()```, instead of ```client.elementIdText(elements.value[0].ELEMENT)``` which is very unintuitive (and contrary to all other webdriver implementations I've come across).

@christian-bromann I can't find any way to scroll to an element contained in this list, like ```element.scroll()``` - is there a good way to do that?
