### ISSUE TITLE
Custom services like `selenium-standalone` and `chromedriver` do not work with 4.9.6-4.9.8

### ISSUE THREAD

**Issue by dukhanov** [webdriverio/webdriverio#2441]
## The problem

Service [selenium-standalone](http://webdriver.io/guide/services/selenium-standalone.html) is not started with the latest version of WDIO

## Environment

* WebdriverIO version: 4.9.6
* Node.js version: 8.7.0
* Additional wdio packages used (if applicable): 
- selenium-standalone

## Details

It looks like `onPrepare` method is not fired for selenium-standalone: https://github.com/webdriverio/wdio-selenium-standalone-service/blob/master/lib/launcher.js#L16

**Comment by christian-bromann** [comment]
@dukhanov sorry was not able to reproduce this with latest WebdriverIO version.
