### ISSUE TITLE
Move Deprecated Selenium Commands Into a Service

### ISSUE THREAD

**Issue by mhemesath** [webdriverio/webdriverio#2443]
## The problem

Webriverio contains a number of deprecated commands that are no longer supported by the webdriver specification. These commands should be removed from the core project to remove confusion on what commands are supported with the latest webdriver.  These commands can be moved into an external package so they can be easily included for anyone that needs them:

```js
exports.config = {
  // ...
  sevices: ['depcrecated-selenium-commands']
 // ...
};
```

## Environment

* WebdriverIO version: 5.x
* Node.js version:
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
* if wdio testrunner, running synchronous or asynchronous tests: Both
* Additional wdio packages used (if applicable): Create standalone package to contain these commands.

## Details

Recommend these are moved into a custom service in a separate package with documentation available on the webdriverio site clearly indicating who should use these and where they are supported.

**Comment by christian-bromann** [comment]
@mhemesath great idea, this should be definitely ready for v5. We should make sure though that the service contains a `depecrated` in the name, maybe something like `wdio-depcrecated-selenium-commands-service` ?

**Comment by mhemesath** [comment]
I think putting deprecated in the name definitely makes sense.

**Comment by mhemesath** [comment]
Looking at the code, I'm wondering if all commands shouldn't be added through services; with existing commands being package/first class with the webdriverio repo.  It looks like there is a little redundancy in what [addCommand](https://github.com/webdriverio/webdriverio/blob/v4.9.8/lib/webdriverio.js#L511-L534) and this code is doing for [remote](https://github.com/webdriverio/webdriverio/blob/v4.9.8/index.js#L38).

**Comment by mhemesath** [comment]
@christian-bromann if you create an empty repo for deprecated selenium commands i'd be more than happy to do a PR to migrate the deprecated commands into that service.

**Comment by stsvilik** [comment]
I would start marking commands as deprecated in the current documentation to indicate future removal. You want to stick to least surprise policy.

**Comment by christian-bromann** [comment]
@mhemesath awesome! I just created https://github.com/christian-bromann/wdio-depcrecated-commands-service and added you as contributor.

**Comment by christian-bromann** [comment]
I am not convinced about this idea anymore. In v5 we will create a complete new set of commands that should be used. People will have to update the one or another command.
