### ISSUE TITLE
Selenium Webdriverio is failing to start Chrome headless in Redhat 7.4 (Maipo)

### ISSUE THREAD

**Issue by ambarbs** [webdriverio/webdriverio#2444]
## The problem

WebdriverIO is unable to launch Chrome while trying to run Chrome Headless with Selenium WebdriverIO in Redhat 7.4 (Maipo).

I have a shell script executing the following commands:

    ./node_modules/selenium-standalone/bin/selenium-standalone install; ./node_modules/selenium-standalone/bin/selenium-standalone start > /dev/null 2>&1 &
    ./node_modules/webdriverio/bin/wdio ./src/test/selenium/wdio.ci.conf.js;

The error message:

> COMMAND	POST 	 "/wd/hub/session"
> DATA		{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"maxInstances":5,"browserName":"chrome","chromeOptions":{"args":["headless","disable-gpu"]},"loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.9.8","name":"webdriverio"}}}
> 
> ERROR: unknown error: Chrome failed to start: crashed (Driver info:
> chromedriver=2.33.506092
> (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux
> 3.10.0-693.1.1.el7.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 60.27 seconds
> Build info: version: '3.6.0', revision: '6fbf3ec767', time:
> '2017-09-27T16:15:40.131Z' System info: host:
> 'ip-10-11-70-25.aws.sbsd.local', ip: '10.11.70.25', os.name: 'Linux',
> os.arch: 'amd64', os.version: '3.10.0-693.1.1.el7.x86_64',
> java.version: '1.8.0_144' Driver info: driver.version: unknown

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: v8.9.1 (LTS)
* Additional wdio packages used (if applicable):
"selenium-standalone": "^6.11.0",
  "webdriverio": "^4.8.0",
 "wdio-junit-reporter": "^0.3.1",
    "wdio-allure-reporter": "^0.1.2",
    "wdio-spec-reporter": "^0.1.2",
    "wdio-jasmine-framework": "^0.3.2",
os.name: 'Linux',
os.arch: 'amd64', os.version: '3.10.0-693.1.1.el7.x86_64',
java.version: '1.8.0_144'

## Link to Selenium/WebdriverIO logs

Error logs: https://gist.github.com/ambarbs/d1770488bdc0ff0a401261a7b17cbdcd#file-webdriverio_chrome_logs-log

Note: **With the same config it works fine in MACOS El Capitan 10.116**

**Comment by mhemesath** [comment]
I recommend you use [wdio-selenium-standalone-service](http://webdriver.io/guide/services/selenium-standalone.html) to manage selenium

**Comment by ambarbs** [comment]
Hi @mhemesath ,

Appreciate your reply. Tried with http://webdriver.io/guide/services/selenium-standalone.html but the outcome was same. 

I forgot to mention in my initial post that the driver works fine in MACOS El Capitan 10.116  but fails to work in Redhat.

**Comment by mhemesath** [comment]
Did you ensure you have the correct Java version installed https://www.npmjs.com/package/selenium-standalone#ensure-you-have-the-minimum-required-java-version

**Comment by ambarbs** [comment]
Hi @mhemesath ,

My current Java version is:

```
[root@ip-10-11-68-25 website]# java -version
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**Comment by christian-bromann** [comment]
@ambarbs it looks like there is an issue with Chrome not being able to start. This is not necessarily a WebdriverIO issue. Maybe try to boot chrome with docker or use a cloud provider.
