### ISSUE TITLE
Getting Cannot read property 'ELEMENT' of null

### ISSUE THREAD

**Issue by Kannan3400** [webdriverio/webdriverio#2446]
## The problem

I am getting the error Getting Cannot read property 'ELEMENT' of null while trying to access the elements from page objects. I am facing this error only from today morning, it was working perfectly before that.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version:6.11.5
* wdio-jasmine-framework: 0.3.1

**Comment by christian-bromann** [comment]
@Kannan3400 how do you think anyone can help you here without examples, logs or anything? 
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
