### ISSUE TITLE
Callback to allow retry when session creation fails

### ISSUE THREAD

**Issue by codiophile** [webdriverio/webdriverio#2447]
## The problem

I described the problem in detail in #2431. In summary, we are testing on mobile devices that are not always in a usable state. When this happens the session creation fails and the scenarios we were supposed to run in that session do not execute. We'd like to have the opportunity to reboot the device and retry session creation when this happens, so that we can get some reliable results.

## Details

I still think #2431 is worthy of consideration, but since we need this urgently I added a hook to allow retries when session creation fails. This is the alternative solution I presented in #2431. It's a lot less intrusive and a lot less effort to implement. We are currently running it, both to verify it and to evaluate its usefulness. I will shortly open a PR with this change.

**Comment by christian-bromann** [comment]
> I will shortly open a PR with this change.

Thanks for the info. Let's close this and have further discussions in your PR
