### ISSUE TITLE
Toggle Location Services on Desktop

### ISSUE THREAD

**Issue by bikinavisho** [webdriverio/webdriverio#2451]
## The problem

When you are emulating/automating on a desktop browser, you cannot interact with the popup window that asks the user if location services can be enabled. 

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 6.1.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): wdio-mocha-framework, wdio-sauce-service, wdio-spec-reporter

## Details

Within my web application, the user cannot continue through the flow unless they have selected to either enable or disable location services. As such, my automated tests are getting stuck on the section which prompts for location services. `alert.accept` and `alert.dismiss` do not touch the location services prompt, as it is not triggered by JavaScript. 

Within the capabilities section of my `wdio.conf.js` file, I have added `locationContextEnabled: false` to each browser, which has made Chrome and Safari be able to progress further, but not IE, MicrosoftEdge, or Firefox. I have tried to change it to `locationContextEnabled: true` for those which aren't working, as well as adding `unexpectedAlertBehaviour` (both accept and dismiss), but neither of those approaches have gotten me beyond the prompt for location services for the browsers listed above. 

## Screenshots of Issue (from SauceLabs)

Firefox
![0026screenshot](https://user-images.githubusercontent.com/8977229/32960224-c9bbfd52-cb89-11e7-9bfe-a1d5c607213b.png)
IE
![0026screenshot 1](https://user-images.githubusercontent.com/8977229/32960349-32a0c2da-cb8a-11e7-99dc-4feccdf6b38d.png)

## Proposal

Add a method similar to the mobile/android method `browser.toggleLocationServices()` for desktop.

**Comment by christian-bromann** [comment]
> but not IE, MicrosoftEdge, or Firefox.

This is not something that WebdriverIO can fix. It has to get fixed in the driver itself.
