### ISSUE TITLE
Element xpath changed to relative (./)

### ISSUE THREAD

**Issue by Tallyb** [webdriverio/webdriverio#2456]
## The problem

I am sending a selector in the format of  `//login-page//button[@type=\"submit\"]` but the   resulting request is `"/session/4ce96a8d3ae6e2bb3367cff05f74885d/element/0.1951611355819869-1/elements"
[13:35:38]  DATA		{"using":"xpath","value":"./login-page//button[@type=\"submit\"]"}` 

 **The `//` at the beginning are changed to `./`.**  

## Environment
* WebdriverIO version: 4.9.8
* Node.js version: 8.9.0
* chromedriver
* wdio-cucumber-framework: 1.0.2
sync mode. using wdio. 

## Details
this occurred because I had `browser.$('ion-app').waitForExist(300000);` in the beforeScenario hook of my config. When moved - the issue has gone. Something with the last promise not being cleaned, but not sure what.

**Comment by christian-bromann** [comment]
@Tallyb can you please provide logs and a reproducible example? We usually not modify selectors so I assume it must be something wrong on your end

**Comment by Tallyb** [comment]
@christian-bromann 
I think it is coming from here: https://github.com/webdriverio/webdriverio/blob/master/lib/protocol/element.js#L34
The condition was true. There is not really a log, but rather I could see it in the request, as shown above.

**Comment by christian-bromann** [comment]
@Tallyb can you at least share your test code?

**Comment by Tallyb** [comment]
@christian-bromann  the repo is a private one, so let me try and share relevant snippets: 
- feature file: 
```
Background:
  Given I am logged in as a "user"
  And   I click the "Basket" menu option
```
Given step file: 
```
defineSupportCode(({ Given }) => {
    Given(
        /^I am logged in as a "(user|manager|admin)"$/,
        app().doLogin
    );
});
```
App(). doLogin is 
```js
doLogin(user) {
let loginDetails = getLoginDetails(user);        
let PAGE = 'login-page';
        browser.waitForVisible (PAGE);
        let emailSelector = `//${PAGE}//input[@placeholder=\"Email\"]`;     // this line changes    browser.waitForExist(emailSelector);
        safeInput(emailSelector, loginDetails.username);
        let passwordSelector = `//${PAGE}//input[@placeholder="Password"]`;
        browser.waitForEnabled(passwordSelector);
        safeInput(passwordSelector, loginDetails.password);
        let loginButtonSelector = `//${PAGE}//button[@type="submit"]`;
        safeClick(loginButtonSelector);
        waitForPage('Available');
        if (isIOS()) {
            browser.alertDismiss();
        }
    }
```
In config file: 
```js
beforeScenario: function (){       
        browser.url('/');
        browser.execute('window.localStorage.setItem("SERVER","***Removed***");')
        browser.execute('window.localStorage.setItem("login.hideWalkthrough",true);');
        browser.$('ion-app').waitForExist(300000); //--> lastResult showed this selector and the condition was true. 
    }, 
```

**Comment by christian-bromann** [comment]
What is `safeClick` doing?

**Comment by Tallyb** [comment]
```ts
function safeClick(el, options?: IclickOptions, timeout?: number) { //clickOptions is just an interface definition
    options = options || {};
    //el = ensureElement(el);
    browser.waitForExist(el, timeout);
    if (!options.skipVisible) {
        browser.waitForVisible(el, timeout);
    }
    let tagName = browser.getTagName(el);
    if (['button', 'input', 'textarea', 'a'].indexOf(tagName) > -1 ) {
        browser.waitForEnabled(el, timeout);        
    }
    browser.pause(1000);
    if (isIOS()) {
        mobileTap(browser.$(el));
    } else {
        browser.click(el);
    }
}
```

**Comment by christian-bromann** [comment]
@Tallyb this is nearly impossible for me to reproduce. Can you nail your issue down to something that makes it possible to reproduce it independently from your environment?

**Comment by Tallyb** [comment]
@ChrisOelmueller  - https://github.com/Tallyb/wdio-test
Simple repo to reproduce. `npm run test`
You will see that the line here https://github.com/Tallyb/wdio-test/blob/master/features/steps.js#L9
is actually shown in the log as 
```
COMMAND     POST     "/session/143eb4ca0c8c2b79f13c9b12c0179432/element/0.5593922622197076-1/elements"
 DATA                {"using":"xpath","value"**:"./article/**a[.=\"Improve this doc\"]"}
RESULT              []
```

**Comment by christian-bromann** [comment]
Hey,

we update the core architecture of WebdriverIO and with that a lot of implementation details that might make this issue obsolete. Please try with the latest version of WebdriverIO and verify if this still occurs. If so please open a new issue and we will tackle it asap.

Thanks!
