### ISSUE TITLE
waitForEnabled generates multiple screenshots when used with Firefox

### ISSUE THREAD

**Issue by sherlock1982** [webdriverio/webdriverio#2457]
## The problem

When calling waitForEnabled a screenshot is generated on every call. Can't be reproduced with Chrome

## Environment

* WebdriverIO version: 4.9.8
* Node.js version: 8.9.1
* Standalone Firefox 57, Geckodriver 1.10.0
* Sync mode
* Additional wdio packages used (if applicable):

## Link to Selenium/WebdriverIO logs

```
COMMAND: POST http://localhost:4444/session/05235284-2e95-4ab3-b46a-4ed0739eca60/elements - {"using":"css selector","value":"body #btnAdd"}
RESULT: {"value":[]}
COMMAND: GET http://localhost:4444/session/05235284-2e95-4ab3-b46a-4ed0739eca60/screenshot - {}
RESULT: null
COMMAND: POST http://localhost:4444/session/05235284-2e95-4ab3-b46a-4ed0739eca60/elements - {"using":"css selector","value":"body #btnAdd"}
RESULT: {"value":[]}
COMMAND: GET http://localhost:4444/session/05235284-2e95-4ab3-b46a-4ed0739eca60/screenshot - {}
RESULT: null

```

## Code To Reproduce Issue 

```
describe('hello', () => {
    it('world', () => {
        browser.waitForEnabled('body #btnAdd');
    })
});

```

**Comment by sherlock1982** [comment]
I see that if i set `screenshotOnReject: false` than test fails. But I will not get any screenshots at all.
I expected to get at least one in the end.

**Comment by christian-bromann** [comment]
> Can't be reproduced with Chrome

This should have nothing to do in which browser it is running. Can you share the Chrome logs?

**Comment by christian-bromann** [comment]
Closing due inactivity

**Comment by briandipalma** [comment]
Might be because the element isn't enabled and thus the return is an error, it's one that you don't care about but the screenshot code doesn't know that so it generates a screenshot regardless.
