### ISSUE TITLE
Testing mobile app and passing test data between test automation (webdriverio) and test app

### ISSUE THREAD

**Issue by asoneji** [webdriverio/webdriverio#2458]
## The problem

I have mobile test app and using WebdriverIO with Appium plugin to test the mobile app. I want to pass data between the  WebdriverIO automation and test app for test validation how can I do it?

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 6.9.2
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio test runner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable): wdio-appium-service

## Details

I want send some data between the test automation and test app. So If I need to provide some dynamic value to test app from test automation how can I do this?

**Comment by christian-bromann** [comment]
@asoneji this looks like a support question rather than an actual issue. Please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions.

**Comment by asoneji** [comment]
I have posted this question multiple time on gitter and got no reply. Anything else I can try?

**Comment by christian-bromann** [comment]
> Anything else I can try?

Keep researching on the internet and checkout http://learn.webdriver.io maybe.

**Comment by asoneji** [comment]
Try that but no luck.
