### ISSUE TITLE
browser.waitForExist // Unknown locator strategy id

### ISSUE THREAD

**Issue by JochenMeier** [webdriverio/webdriverio#2462]
Hello,

i want to use webdriver.io for automated unit-tests.
Im using Jasmine as testing framework.
So i made a simple script which loads a page and checks whether a specific element is existing (in this case the element exists for sure).

```
  it('has a teaser list with a teaser', () => {
    /* a '/' leads to a failure because the path part will be replaced */
    browser.url('');
    browser.waitForExist('#teaser_list', 10000);
  });
```

Also im passing a baseUrl to my wdio config, thats why im passing an empty string to the "browser.url()" call.

Iam using a local conf, and a remote conf. For my local wdio conf this script just works fine.

Using it with the remote wdio config the following error occurs:
...
1 failing

1) ... has a teaser list with a teaser:
**Error: Unknown locator strategy id
running firefox
Error: The arguments passed to a command are either invalid or malformed.
    at isExisting("#teaser_list") - at elements("#teaser_list") - isExisting.js:46:17**

using "setTimeout" with 1s makes it work...

```
  it('has a teaser list with a teaser', () => {
    /* a '/' leads to a failure because the path part will be replaced */
    browser.url('');
    setTimeout(() => {
      browser.waitForExist('#teaser_list', 10000);
    }, 1000);
  });
```

Why does waitForExist not work as expected ? 
Is it possible to wait for the loading event via wdio ?

**Comment by christian-bromann** [comment]
> i want to use webdriver.io for automated unit-tests.

I think unit-test is the wrong term for this. You should not mix your actual unit test and integration tests with WebdriverIO

> Error: The arguments passed to a command are either invalid or malformed.

Looks like the Firefox version (which I can not specify because you didn't use the issue template). doesn't like your selector. This is not a WebdriverIO.

**Comment by christian-bromann** [comment]
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have more questions.
