### ISSUE TITLE
No error when connect unreachable selenium server

### ISSUE THREAD

**Issue by zombiecong** [webdriverio/webdriverio#2464]
## The problem

No error when connect unreachable selenium server

## Environment

* WebdriverIO version: 4.9.9
* Node.js version:6.5.0
* Standalone Chrome62

## Code To Reproduce Issue [ Good To Have ]

```
var webdriverio = require('webdriverio');


var chromeOptions = { args: [
  'use-fake-device-for-media-stream',
  'use-fake-ui-for-media-stream',
  // 'ignore-certificate-errors',
  // 'headless',
]};

var browser = webdriverio.multiremote({
  chrome1: {
    host: '110.110.110.110',
    port: 4444,
    desiredCapabilities: {
      browserName: 'chrome',
      applicationName: 'chrome1',
      chromeOptions: chromeOptions

    }
  }
});

var cb = browser.select('chrome1');

browser.on('error',function(e){
    console.log('error : ',e)
});

cb.on('error',function(e){
  console.log('error : ',e)
});

var url = 'xxxx';

// var btn = '#start';
var btn = '#bt_start';

cb.init().url(url).pause(2000).$(btn).click().pause(30000).end();

```

**Comment by christian-bromann** [comment]
How am I suppose to deal with this other than closing the issue.

**Comment by zombiecong** [comment]
What do you mean?

**Comment by christian-bromann** [comment]
Oh great, finally some more details about the issue even though it still doesn't have a description. Note that each command represents a promise and as long you don't catch it you won't see any error. 
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by zombiecong** [comment]
Sorry, my fault.  I got it, thanks.

**Comment by zombiecong** [comment]
@christian-bromann  Hey , I got the timeout  error , but it took me 5mins to get the error , and I can not find a way to change the time of timeout.  I also try to  set [Session Script Timeout](http://webdriver.io/guide/testrunner/timeouts.html#Selenium-timeouts) and [Session Page Load Timeout](http://webdriver.io/guide/testrunner/timeouts.html#Session-Page-Load-Timeout) , neither one of them works for me. I am not sure it's an issue or my mistake.

Thanks.
