### ISSUE TITLE
On Jenkins, wdio running in docker based build hangs

### ISSUE THREAD

**Issue by lowsky** [webdriverio/webdriverio#2466]
## The problem

We have Wdio UI tests running in a docker container in a Jenkins CI environment.
Since upgrading some libs the wdio command hangs forever and does not show any output.

It seems to be introduced in wdio 4.9.0 

## Requested Solution
Can there be a command line switch for disabling spec files on piped input?
Or why expecting spec file per input pipe, when that files are already specified in the config?

## Environment

* WebdriverIO version: 4.9.0
* Node.js version: 8.7
* running synchronous
* Additional wdio packages used (if applicable): wdio-sync
...
## Details

I found that our environment when running wdio in a Docker container in Jenkins hangs forever.

This is caused by an issue with detecting the stdin stream in the node process:
[background](https://nodejs.org/api/process.html#process_a_note_on_process_i_o)
which is correctly implemented in *wdio* , but seams to fail on our environment, 
because the detection of the input is _failing_

## Link to Selenium/WebdriverIO logs

There is NO log at all, even with full verbose mode, because wdio hangs without any output! I additionally propose to at lease show a message that "a list of spec files is requested" ?!)

## Code To Reproduce Issue [ Good To Have ]
```Jenkinsfile 
node('docker') {
  docker.image('mhart/alpine-node:8.7.0').inside {
    sh 'echo x | node -p "Boolean(process.stdout.isTTY)"' // returns false, as expected
    sh "echo x | node -e 'console.log(process.stdin.isTTY)' " // returns undefined, as expected
    sh 'node -p "Boolean(process.stdout.isTTY)"' // should return true, but is false !!!
    sh "node -e 'console.log(process.stdin.isTTY)'" // // should return true, but is undefined !!!
  }
}
```

**Comment by christian-bromann** [comment]
> which is correctly implemented in wdio , but seams to fail on our environment,
> because the detection of the input is failing

Not sure how I am suppose to help here and why this is a bug in WebdriverIO

**Comment by lowsky** [comment]
Okay, that was TL;DR ;-)

The interesing part is my 
> request  for the possibility to disable the feature of
> "reading the spec-files from the input-pipe"
> per command line switch or environment variable

That was a breaking change for us when migrating from 4.8 to 4.9, and had cost some time to figure out, that it was hanging because waiting forever for input :-)

I think it could be an improvement, to write a message about waiting for input, what do you think, @christian-bromann ? I could provide a PR, if you like.

**Comment by christian-bromann** [comment]
> I think it could be an improvement, to write a message about waiting for input, what do you think,

I am not sure what you mean by that

**Comment by mkj28** [comment]
> That was a breaking change for us when migrating from 4.8 to 4.9

Ha! I think I'm hitting the same but with `--suite`. With 4.9.9 `wdio --suite=my_suite` hangs forever for me.

**Comment by mkj28** [comment]
@sha1sum / @christian-bromann fwiw looks like the issue was introduced here: https://github.com/webdriverio/webdriverio/pull/2098/files

```if (process.stdin.isTTY) {
   launch()
} else {
[assume we're going to pipe in the list of specs]
```

Jenkins has no tty:
```# node -p -e Boolean(process.stdout.isTTY)
false```

so we're running into an infinite loop waiting for input...
