### ISSUE TITLE
Console output in jenkins is not correct

### ISSUE THREAD

**Issue by andrea-raabe** [webdriverio/webdriverio#2469]
## The problem

The console output with the spec reporter in jenkins is not correct.

The checkmark (and special signs) displayed not correct: **[32m✓[0m**

## Environment

* WebdriverIO version: 4.9.9
* Node.js version:
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Details

`
[chrome #0-1] Session ID: cc6195047bb0ee11656db99c50c73114

[chrome #0-1] Spec: /home/jenkins/workspace/Frontend/PortalDev-03-EndToEndChrome/tests/portal/angebotsalarm.js
[chrome #0-1] Running: chrome
[chrome #0-1]
[chrome #0-1]   Angebotsalarm
[chrome #0-1]       [32m✓[0m Bei Klick ...
[chrome #0-1]       [32m✓[0m Der Dialog ...
[chrome #0-1]
[chrome #0-1]
[chrome #0-1] [32m2[0m [32mpassing[0m (21s)
[chrome #0-1]
`

**Comment by christian-bromann** [comment]
This issue was moved to webdriverio/wdio-spec-reporter#66
