### ISSUE TITLE
Dynamically generate test cases

### ISSUE THREAD

**Issue by cervenyprofiq** [webdriverio/webdriverio#2470]
## The problem

Hi, 
I was wonder, if it is possible to generate test cases dynamically. For example I have 2 similar inputs and I want to generate test cases, which are pretty same. 

For example I have something like this:

```javascript
import LoginForm from '../../lib/login/LoginForm';

describe('LoginForm', ()=>{
    const inputs = [
        ['Email', LoginForm.email], 
        ['Password', LoginForm.password]
    ];

    
    beforeAll(()=>{
        browser.url(browser.options.baseUrl);
    });

    it('is visible', ()=>{
        expect(LoginForm.window.isVisible).toBeTruthy();
    });
    describe('Inputs', ()=>{
        inputs.map(([desc, input])=>{
            describe(desc, ()=>{
                it('default value is @test.com', ()=>{
                    expect(input.getValue()).toBe('@test.com');
                });
    
                it('is editable', ()=>{
                    input.clearElement();
                    input.setValue('test@test.com');
                    expect(input.getValue()).not.toBeFalsy();     
                });
            });
        });
    });
});
```

LoginForm.js
```javascript
export default class LoginForm  {
    static get email() { return $('input#login'); }
    static get password() { return $('input#password'); }
}

```

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 8.9.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync

## Details
Report is properly created, but it fails due problem with `Failed: Cannot read property 'ELEMENT' of null`

Not sure, if it is possible or what is a best practice for it. Can you give me some hint how to resolve it, if it is possible?

Any feedback is welcome! Thanks!

**Comment by christian-bromann** [comment]
> Not sure, if it is possible or what is a best practice for it. Can you give me some hint how to resolve it, if it is possible

Yup, such things are possible. Have you tried it? 
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
