### ISSUE TITLE
Caught promise rejection triggers error screenshot

### ISSUE THREAD

**Issue by maximilianschmitt** [webdriverio/webdriverio#2473]
## The problem

I wrote a helper to dismiss alerts if any are open that looks like this:

```
browser.alertAccept().catch(() => {})
```

The `catch` is there because a `NoAlertOpenError` is thrown when there are no alerts open. The helper does what it's supposed to. However, if there are no alerts open, an error screenshot is still taken (due to the `NoAlertOpenError` even though the promise rejection is caught).

## Environment

* WebdriverIO version: 4.9.9
* Node.js version: v6.11.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): 

    - "wdio-dot-reporter": "0.0.9"
    - "wdio-junit-reporter": "^0.3.1"
    - "wdio-mocha-framework": "^0.5.11"
    - "wdio-selenium-standalone-service": "0.0.9"
    - "wdio-spec-reporter": "^0.1.2"

## Code To Reproduce Issue

Accessing a page with an alert:

```
browser.alertAccept().catch(() => {})
```

**Comment by christian-bromann** [comment]
Hey,

we update the core architecture of WebdriverIO and with that a lot of implementation details that might make this issue obsolete. Please try with the latest version of WebdriverIO and verify if this still occurs. If so please open a new issue and we will tackle it asap.

Thanks!
