### ISSUE TITLE
Actions example does not work

### ISSUE THREAD

**Issue by SassNinja** [webdriverio/webdriverio#2478]
There are some test cases where I have to emulate a mouseover action of the user.
First I've used `moveToObject()` for this but it doesn't seem to work correctly (e.g. a dropdown closes what should not happen until mouseleave) and it doesn't seem to be supported by all browsers as I also read in another issue https://github.com/webdriverio/webdriverio/issues/2140

So I tried to go with the actions command instead.
But I wasn't able to emulate a mouseover with. Even the example in the [docs](http://webdriver.io/api/protocol/actions.html) doesn't work (tested chrome & firefox).

My simple test always fails and throws an error:
unimplemented command: session/873f30b97e472cb8dc655504648f3c93/actions

Isn't the actions api supported yet although it's in the docs?

Here's my example test

```javascript
var assert = require('chai').assert;
describe('Actions test :: ', function() {
    it('should succeed', function() {
        browser.url('https://www.google.com');
        browser.actions([{
            "type": "pointer",
            "id": "finger1",
            "parameters": {"pointerType": "touch"},
            "actions": [
                {"type": "pointerMove", "duration": 0, "x": 100, "y": 100},
                {"type": "pointerDown", "button": 0},
                {"type": "pause", "duration": 500},
                {"type": "pointerMove", "duration": 1000, "origin": "pointer", "x": -50, "y": 0},
                {"type": "pointerUp", "button": 0}
            ]
        }, {
            "type": "pointer",
            "id": "finger2",
            "parameters": {"pointerType": "touch"},
            "actions": [
                {"type": "pointerMove", "duration": 0, "x": 100, "y": 100},
                {"type": "pointerDown", "button": 0},
                {"type": "pause", "duration": 500},
                {"type": "pointerMove", "duration": 1000, "origin": "pointer", "x": 50, "y": 0},
                {"type": "pointerUp", "button": 0}
            ]
        }]);
        browser.actions();
        assert.equal(1, 1);
    });
});
```

Mac OSX 10.13.1 (High Sierra)
node v8.6.0
chrome 62.0

**Comment by christian-bromann** [comment]
@SassNinja the Chromedriver has not implemented this command yet. 
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by SassNinja** [comment]
@christian-bromann the problem with gitter is questions won't get found as easy as in the issues (at least imo)

However I feel a bit lost regarding mouseover action in my tests because neither `moveToObject` nor the actions api seem to be the solution. For now I have to live with a workaround via the  `execute` command. 
But I understand you can't do much if the browser drivers haven't implemented the necessary commands yet.

Would just be great if it was more clear in the docs if a specific command is not (fully) supported.
Maybe I'll make a PR once I've got a few minutes.

**Comment by christian-bromann** [comment]
> Would just be great if it was more clear in the docs if a specific command is not (fully) supported.

I agree. Unfortunately this is our current situation as all driver are transitioning to the WebDriver spec.

> Maybe I'll make a PR once I've got a few minutes.

I am not sure if this helps after all. Everyone who is unsure if it is supported please check out the driver project page to see.

**Comment by SassNinja** [comment]
> I am not sure if this helps after all. WebdriverIO can't be the docs for everything. Everyone who is unsure if it is supported please check out the driver project page to see.

I understand wdio can't be the docs for the whole driver specs.
But nevertheless I think it would be quite helpful to have e.g. a simple table at the end of each command page in the docs, showing if it's already fully supported.

Otherwise you have to [google](https://chromium.googlesource.com/chromium/src/+/master/docs/chromedriver_status.md) each command to be sure it's safe to use for production tests.
What does speak against this in your opinion? The task to keep it up to date?

**Comment by christian-bromann** [comment]
> showing if it's already fully supported.

If you can provide that information and agree to maintain that table, I would be happy to have this. Unfortunately this is not something I can just test out of the box in an automated way.

> The task to keep it up to date?

Yes!

**Comment by mherodev** [comment]
As a new user to WebDriverIO, it'd have been helpful for the docs to expose that hover is currently only supported with `moveToObject` in Chrome and the `actions` command in Firefox. Maybe they could both be marked as `Transitional` with a note and a date.

It'd also have been nice if `actions` was surfaced under `Action` in the documentation, if only as a link to the documentation in `Protocol`. When directed to the "Actions API" I had no idea what anyone was being referred to.

**Comment by christian-bromann** [comment]
> It'd also have been nice if actions was surfaced under Action in the documentation

@mherodev don't confuse WebdriverIO with on of the Selenium bindings, WebdriverIO is a completely independent project from Selenium and doesn't follow their API

**Comment by christian-bromann** [comment]
> Maybe they could both be marked as Transitional with a note and a date.

We can add a check to use actions in the moveToObject command, any PRs are welcome!

**Comment by mherodev** [comment]
@christian-bromann I don't know where Selenium bindings begin and WebDriverIO ends, if you don't mind being more specific.

To be clearer on my end, it was confusing to not find `actions` under the `Action` header in the WebDriverIO docs (http://webdriver.io/api.html). I'm not certain what differentiates `Action` from `Protocol`, just speaking from a "I'm trying to use WebDriverIO to test hover" perspective, and less from a technical perspective.

**Comment by funky17** [comment]
@SassNinja / @mherodev :

I am a new user of webdriverio. Can either of you help me? 

I have a chart, when a cursor is moved to a specific area in the chart (which is under <div class='.chart-container'>), a hover text appears. I want to test that hover text.  Initially, I tried to use moveToObject since I am using firefox it is not working. Then I tried to use actions based on the example you posted. Here is the sample:

browser.waitUntil(function () {
            return browser.isExisting('.chart-container') === true
        }, 60000, 'expected chart container to be there');
        
        browser.actions([{
            "type": "pointer",
            "id": "finger1",
            "parameters": {"pointerType": "touch"},
            "actions": [
                {"type": "pointerMove", "duration": 0, "x": 50, "y": 50},
                {"type": "pointerDown", "button": 0},
                {"type": "pause", "duration": 500},
                {"type": "pointerMove", "duration": 1000, "origin": "pointer", "x": 50, "y": 0},
                {"type": "pointerUp", "button": 0}
            ]
        }, {
            "type": "pointer",
            "id": "finger2",
            "parameters": {"pointerType": "touch"},
            "actions": [
                {"type": "pointerMove", "duration": 0, "x": 60, "y": 60},
                {"type": "pointerDown", "button": 0},
                {"type": "pause", "duration": 500},
                {"type": "pointerMove", "duration": 1000, "origin": "pointer", "x": 50, "y": 0},
                {"type": "pointerUp", "button": 0}
            ]
        }]);
        browser.actions();

Error:
POST /session/3369fe62-1495-4421-9641-36801559f427/actions
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:54:15.039Z'
System info: host: xxx, ip: xxxx, os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.76-0.1.ac.191.62.327.metal1.x86_64', java.version: '1.8.0_144'
Driver info: driver.version: unknown
running firefox
Error: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.
    at actions([object Object], [object Object]) - index.js:312:3

**Comment by christian-bromann** [comment]
@funky17 make sure you are running the latest Geckodriver

**Comment by funky17** [comment]
@christian-bromann : I upgraded geckodriver to latest version. I am still running into same issue.

geckodriver: v0.20.1
selenium-standalone-server: 3.9.0
firefox: 60.0
webdriverio: v4.12.0

When I run the tests, I see the below error:

Build info: version: '3.9.0', revision: '698b3178f0', time: '2018-02-05T14:56:13.134Z'
System info: host: '8c859046a667.ant.amazon.com', ip: '10.63.174.156', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_162'
Driver info: driver.version: unknown
[firefox #0-0] Error: An unknown server-side error occurred while processing the command.
[firefox #0-0]     at url("xxx") - index.js:312:3

Selenium logs:

8c859046a667:webdriverio-test akhilay$ java -jar -Dwebdriver.gecko.driver=./geckodriver selenium-server-standalone-3.9.0.jar 
11:38:36.700 INFO - Selenium build info: version: '3.9.0', revision: '698b3178f0'
11:38:36.701 INFO - Launching a standalone Selenium Server on port 4444
2018-05-14 11:38:36.771:INFO::main: Logging initialized @262ms to org.seleniumhq.jetty9.util.log.StdErrLog
2018-05-14 11:38:36.858:INFO:osjs.Server:main: jetty-9.4.7.v20170914, build timestamp: 2017-11-21T13:27:37-08:00, git hash: 82b8fb23f757335bb3329d540ce37a2a2615f0a8
2018-05-14 11:38:36.878:WARN:osjs.SecurityHandler:main: ServletContext@o.s.j.s.ServletContextHandler@4b4523f8{/,null,STARTING} has uncovered http methods for path: /
2018-05-14 11:38:36.882:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@4b4523f8{/,null,AVAILABLE}
2018-05-14 11:38:36.909:INFO:osjs.AbstractConnector:main: Started ServerConnector@131276c2{HTTP/1.1,[http/1.1]}{0.0.0.0:4444}
2018-05-14 11:38:36.910:INFO:osjs.Server:main: Started @401ms
11:38:36.910 INFO - Selenium Server is up and running on port 4444
2018-05-14 11:38:42.754:INFO:osjshC.ROOT:qtp1123225098-11: org.openqa.selenium.remote.server.WebDriverServlet-5b275dab: Initialising WebDriverServlet
11:38:42.802 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.BeginSession@80874c0
11:38:42.805 INFO - /session: Executing POST on /session (handler: BeginSession)
11:38:42.866 INFO - Capabilities are: Capabilities {browserName: firefox, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., maxInstances: 5, requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.12.0}, rotatable: true}
11:38:42.868 INFO - Capabilities {browserName: firefox, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., maxInstances: 5, requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.12.0}, rotatable: true} matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1526323122896	geckodriver	INFO	geckodriver 0.20.1
1526323122903	geckodriver	INFO	Listening on 127.0.0.1:37937
1526323123138	mozrunner::runner	INFO	Running command: "/Applications/Firefox.app/Contents/MacOS/firefox-bin" "-marionette" "-profile" "/var/folders/bw/rx0q3y6559x0ls1v56cxmqjdgl3m2w/T/rust_mozprofile.jisAWHf7UWhg"
Unable to read VR Path Registry from /Users/akhilay/Library/Application Support/OpenVR/.openvr/openvrpaths.vrpath
Unable to read VR Path Registry from /Users/akhilay/Library/Application Support/OpenVR/.openvr/openvrpaths.vrpath
2018-05-14 11:38:44.156 plugin-container[21363:192558] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9537, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
1526323124510	Marionette	INFO	Listening on port 59364
11:38:44.609 INFO - Detected dialect: W3C
11:38:44.680 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@2394c904
11:38:44.680 INFO - Handler thread for session 568d1e9a-8a43-5048-96fa-94462d0b6762 (firefox): Executing POST on /session/568d1e9a-8a43-5048-96fa-94462d0b6762/url (handler: ServicedSession)
11:38:44.841 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@2394c904
11:38:44.842 INFO - Handler thread for session 568d1e9a-8a43-5048-96fa-94462d0b6762 (firefox): Executing GET on /session/568d1e9a-8a43-5048-96fa-94462d0b6762/screenshot (handler: ServicedSession)
Unable to read VR Path Registry from /Users/akhilay/Library/Application Support/OpenVR/.openvr/openvrpaths.vrpath
2018-05-14 11:38:45.088 plugin-container[21365:192645] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9137, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
11:38:45.240 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@2394c904
11:38:45.240 INFO - Handler thread for session 568d1e9a-8a43-5048-96fa-94462d0b6762 (firefox): Executing DELETE on /session/568d1e9a-8a43-5048-96fa-94462d0b6762 (handler: ServicedSession)
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
11:38:45.715 INFO - Removing session org.openqa.selenium.remote.server.ServicedSession@2394c904

Any help is appreciated. Thanks

**Comment by michaelseno** [comment]
@SassNinja Hi, I would like to ask on how did you use the execute command to simulate a mouse hover event? I am somehow having difficulties since `moveToObject()` is not simulating a hover event in chrome. (i'm using version 4 of webdriverio) maybe the execute command will work as well. Thanks in advance.

**Comment by SassNinja** [comment]
Hi @michaelseno 

I've simply triggered a mouseover event on the target element to emulate a mouse over. Of course this only triggers JavaScript listeners and no CSS (afaik there are also ways for CSS but with bad performance – I haven't used this yet)

That's how your execute should look

```javascript
// jQuery
browser.execute(function() {
  $('selector').trigger('mouseover');
});

// non jQuery
browser.execute(function() {
  document.querySelector('selector').dispatchEvent(new MouseEvent('mouseover'));
});
```

**Comment by michaelseno** [comment]
Hi @SassNinja 

Thank you very much. I was able to make it work using jQuery syntax. Thanks for the explanation and code snippet
