### ISSUE TITLE
Error: Promise was rejected with the following reason: selector needs to be typeof `string`

### ISSUE THREAD

**Issue by ViaMay** [webdriverio/webdriverio#2482]
## The problem
Autotests didn't work which last version WebdriverIO: 4.9.10

## Environment

* WebdriverIO version: 4.9.10
* Node.js version: v6.9.2
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio 
* if wdio testrunner, running synchronous or asynchronous tests: synchronous 
* Additional wdio packages used (if applicable):

## Details
After update WebdriverIO I can have error about function isVisible or waitForExist where used it for my selector:
![screenshot_1](https://user-images.githubusercontent.com/10914859/33305729-dc985f72-d441-11e7-8703-2a8a77d232e6.png)

## Link to Selenium/WebdriverIO logs
[SongLine_Auto_tests-Webdriver_Run_Auto_test_1450.log](https://github.com/webdriverio/webdriverio/files/1508701/SongLine_Auto_tests-Webdriver_Run_Auto_test_1450.log)

## Code To Reproduce Issue [ Good To Have ]
Example error for test gallery image and movies add correct
```
Error: Promise was rejected with the following reason: selector needs to be typeof `string`     
at Page.Object.create.waitVisible.value (tests/Pages/UploadPage.js:18:52)     
at Context.<anonymous> (tests/tests/gallery.add.rename.delete.test.js:65:20)     
at new Promise (node_modules/wdio-sync/node_modules/core-js/library/modules/es6.promise.js:171:7)
at elements() - isExisting.js:46:17     
at isExisting() - waitForExist.js:67:22
```
UploadPage view:
![screenshot_2](https://user-images.githubusercontent.com/10914859/33305835-5b21c7a2-d442-11e7-8a43-55d3d4ad03ef.png)

Maybe it is duplicate https://github.com/webdriverio/webdriverio/issues/2481

**Comment by christian-bromann** [comment]
@ViaMay you need to use `this.uploadFromComputerButtom.waitForExist()` in there. 
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by ViaMay** [comment]
@christian-bromann still have this error
![screenshot_4](https://user-images.githubusercontent.com/10914859/33308403-dfcfddfe-d44c-11e7-8cc3-55e84b5f9844.png)

**Comment by ViaMay** [comment]
yesterday all work well. Now didn't

**Comment by ViaMay** [comment]
@christian-bromann set "webdriverio": "4.9.9" - all work well
![screenshot_5](https://user-images.githubusercontent.com/10914859/33309371-873e57a2-d450-11e7-8bec-66bb2af248ae.png)
