### ISSUE TITLE
Using waitForVisible on an element is causing false error

### ISSUE THREAD

**Issue by adamweeks** [webdriverio/webdriverio#2483]
## The problem

 Using waitForVisible on an element is causing false error:
>Promise was rejected with the following reason: selector needs to be typeof string

## Environment

* WebdriverIO version: 4.9.10
* Node.js version: v7.10.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable):
sauce labs

## Code To Reproduce Issue

```js
browser.element(`.myObjectClass`).waitForVisible(1500, true);
```

**Comment by adamweeks** [comment]
Setting webdriverio to 4.8.0 resolves this issue

**Comment by jgoldring** [comment]
I ran into the same thing yesterday. Upgraded to 4.9.10, all my tests using the page object pattern whereby I had:

Within somePage.js:
`example: {get: function () { return browser.element("#example"); }}`

Within test file:
`somePage.example.waitForVisible()`

It would throw the same error: 

> Promise was rejected with the following reason: selector needs to be typeof string

But within the wdio log it would complain that "#example" could not be found on the browser.element() call, and immediately fail without doing the wait. For me, 4.9.9 still works, it was when upgrading from 4.9.9 -> 4.9.10 that caused all my tests to fail.

**Comment by christian-bromann** [comment]
@jgoldring we haven't changed anything between 4.9.9 and 4.9.10 that could be related to this

**Comment by ianrenauld** [comment]
I haven't investigated the cause, but I get the same error message when my daily tests ran last night with 4.9.10. Reverting to 4.9.9 solved the issue. There is something strange going on with 4.9.10!

**Comment by ViaMay** [comment]
I had this error too

**Comment by jameso33** [comment]
No issues running 4.9.9. Got this issue running 4.9.10.

**Comment by scottrippey** [comment]
Same problem here with 4.9.10, but it seems like the problem went away with 4.9.11.  Anyone else able to verify?

**Comment by christian-bromann** [comment]
> but it seems like the problem went away with 4.9.11. Anyone else able to verify?

Thanks for verifying
