### ISSUE TITLE
Retries on a per-specfile basis

### ISSUE THREAD

**Issue by bennieswart** [webdriverio/webdriverio#2484]
We are running tests with wdio, which very nicely creates a new browser instance for each spec file. We have rigged this so that a new server+db is created for each browser that starts up, allowing tests to run in complete isolation. This all works very nicely.

Sometimes tests have false negatives, however, and in these cases we want to rerun the test, again with a new server+db. This would 'just work' if wdio had some way to do a specfile level retry.

I'm aware that describe-level and it-level (mocha) retries are possible, but since a new browser instance is created on a per-specfile basis, it would also be really handy to have retries on a per-specfile basis.

Is this possible?

**Comment by christian-bromann** [comment]
@bennieswart as described in http://webdriver.io/guide/testrunner/retry.html#Rerun-suites-in-MochaJS please use `this.retries(4)`
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by bennieswart** [comment]
@christian-bromann maybe I was not clear enough: I'm aware of the describe-level and it-level retries, and as I understand, this is what you are describing.

These kinds of retries will only rerun the test code, without launching a new browser instance and causing (in our case) a new server+db to be created. The problem here is that the first try might leave the db in an unintended state, causing all future retries to fail immediately. This is why a new db is required for each retry.

As far as I can tell this is not possible (or at least not documented - I've not looked into the code yet).
Do you not think that retries on this level may be useful? Especially in situations like the one I just described.

**Comment by christian-bromann** [comment]
Ah, so you want per file retries instead of per test/describe. No this is not possible but can get implemented. PRs welcome.

**Comment by bennieswart** [comment]
Great. I just wanted to run this by you to see if it makes sense. I intend to make a PR, but with the upcoming holidays it might be a while before I get to it.

**Comment by kokujin** [comment]
Any news on this?

**Comment by bennieswart** [comment]
@kokujin funny you should ask right now... I've literally just gotten back to this today.

Should have a PR ready before the end of the week. It works on the principle I've outlined earlier, in that when `retries > 0`, messages are buffered. This is the only downside I see, but at least it only comes when `specFileRetries` is set to a non-default value. Otherwise everything works as per normal.

**Comment by kokujin** [comment]
@bennieswart great! We have a few "flakey" suites that could benefit from your PR.

**Comment by shackijj** [comment]
Hello @christian-bromann!
What was the reason for closing #2930?
I can implement the feature in the master branch (v5) and create a PR. Is there a chance that the PR will be merged?

**Comment by christian-bromann** [comment]
> I can implement the feature in the master branch (v5) and create a PR. Is there a chance that the PR will be merged?

See my [comment here](https://github.com/webdriverio/webdriverio/pull/2930#issuecomment-445795829). Feel free to create a new PR. I will be able to merge it easier this time because I can setup a proper pipeline for v4 now.

**Comment by WillBrock** [comment]
Replaced with #3381
