### ISSUE TITLE
Browser is not defined error with webdriver IO Launcher.

### ISSUE THREAD

**Issue by Jaspreet23** [webdriverio/webdriverio#2487]
Hello,

I need to use browser in my pre-setup file but when trying to do so its failing with msg: 
ReferenceError: browser is not defined
I understand that this is because it needs the webriverIO initialisation. So I was trying to do this using the Launcher:
```
 var Launcher = require('webdriverio').Launcher;
 var optionsN = { desiredCapabilities: { browserName: 'chrome',launchTimeout:configs.desiredCapabilities.host,deviceName:i.capabilities.deviceName,platformName:i.capabilities.platformName,appPackage:'com.hip.tradie.android',appActivity:'.ui.MainActivity'},host:configs.host,port:configs.port,protocol: configs.protocol};
                                    
var wdio = new Launcher("wdio.android.conf.js", optionsN);
 wdio.run().then(function (code) {
                       const signin = browser.getObj(`signin_objects`);
                       browser.waitForExist(signin.signinEmail, 3500);
                       process.exit(code);
                   }, function (error) {
                                 console.error('Launcher failed to start the test', error.stacktrace);
                                  process.exit(1);
 });

```
I am getting this error: 
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: browser is not defined

I am running my script as: 
node preSetup.js

How can we initialise the browser object?

**Comment by christian-bromann** [comment]
> How can we initialise the browser object?

You can't! The browser variable is only available in your test specs and in your wdio.conf.js hooks. Once the run() promise is resolved it means that the test is over.
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
