### ISSUE TITLE
how to run multiple specs with launcher

### ISSUE THREAD

**Issue by dalimian** [webdriverio/webdriverio#2488]
first, http://webdriver.io/guide/testrunner/organizesuite.html#Run-Multiple-Specific-Test-Specs describes the way to run multiple specs is 
```
$ grep -r -l --include "*.js" "myText" | wdio wdio.conf.js
```

doesn't work for me, is this part correct - `grep -r -l --include "*.js" "myText"`, cause that doesn't do anything for me on my mac shell - https://www.screencast.com/t/PV6OAIGh

is it possible to do the same with the Launcher - http://webdriver.io/guide/testrunner/gettingstarted.html#Run-the-test-runner-programmatically

**Comment by WillBrock** [comment]
What if you try this?

`find "your_search_directory" -name "*.js" | wdio wdio.conf.js`

**Comment by christian-bromann** [comment]
@dalimian you can just define multiple specs in your wdio.conf.js or run
```sh
$ wdio wdio.conf.js --spec ./test1.js,./test2.js
```
