### ISSUE TITLE
Question: Feasability of introducing support for Detox

### ISSUE THREAD

**Issue by klippx** [webdriverio/webdriverio#2489]
Hello!

We are developing an app in React Native and a web app on the side.

We are using detox for our native e2e tests, and selenium directly for our web e2e tests. This means our test code bases looks fairly similar, but we have some gotchas of using selenium directly and started investigating webdriverio. 

WebdriverIO solves a couple of problems for us, but introduces the fact that now our e2e test code base has diverged. Webdriverio tests looks much nicer (good thing), while detox tests has the traditional async/await javascript testing. Our developers get the extra overhead of learning two different ways of writing code.

So either we could try to use Appium in favor of Detox, just because of WebdriverIO. But our experience with Appium is that its not very nice to work with, and [the community is quite excited about Detox](https://medium.freecodecamp.org/what-ive-learned-from-react-europe-2017-c433468890d6#dfce), and actually it is working pretty well for us.

Wouldn't it be nice if webdriverio supported Detox in addition to Appium, if this is where the future of a large part of the Native developer community want to be going?

What do you think?

**Comment by christian-bromann** [comment]
> What do you think?

I have never heard about Detox and I am not sure how that "greybox" testing looks like. Looking at the design principles it clearly states:

> Detox does not rely on WebDriver

Which means that it will never be able to get run by WebdriverIO as it heavily relies on the WebDriver protocol.

I would advise to go with the industry standard which is Appium and WebDriver. Sure the approach seems nice and might provide a better experience in the first place. This doesn't mean tho that you can't write solid flake free tests with Appium. The community behind Appium and WebDriver / WebdriverIO is huge and many people are working constantly on improving it. They are maintained by a foundation (https://js.foundation/community/projects). On the contrary Detox is written and supported by a single company. There will be a limited technical support for it and if they decide eventually to move on and stop maintain the project you'll need to rewrite your test into a different framework anyway.

I think this is up to you. If you have a small short term project, you will be fine moving forward with Detox. If you want to write your tests on a solid foundation I recommend to go with Appium and WebdriverIO.

Feel free to ask more questions in our support channel on [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)!
