### ISSUE TITLE
Search parent directories for wdio.conf.js

### ISSUE THREAD

**Issue by mhemesath** [webdriverio/webdriverio#2498]
## The problem

This is an enhancement request. It would be convenient if webdriver.io searched parent directories for `wdio.conf.js`.  Current behavior is that unless `wdio.conf.js` is in the current directory as the command executed, it won't find it.

## Environment

* WebdriverIO version: 4.9.x
* Node.js version: 8.4
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
* if wdio testrunner, running synchronous or asynchronous tests: test runner

## Details

This is just a nice to have. Makes it slightly easier when working on repos managed by lerna and only want to run tests scoped to the directory being worked in. Really this just saves me from having to type 
```json
scripts: {
    "test:wdio": "wdio ../../wdio.conf.js"
}
```
in all my sub-project folders.

**Comment by christian-bromann** [comment]
Hey,

we update the core architecture of WebdriverIO and with that a lot of implementation details that might make this issue obsolete. Please try with the latest version of WebdriverIO and verify if this still occurs. If so please open a new issue and we will tackle it asap.

Thanks!
