### ISSUE TITLE
Accept access browser geolocation popup using javascript.

### ISSUE THREAD

**Issue by abhijithqb** [webdriverio/webdriverio#2500]
## The problem

How to accept access browser geolocation popup using javascript? I need to test some app behaviors with both allowed and denied cases.

I believe [alertAccept](http://webdriver.io/api/protocol/alertAccept.html) and [alertDismiss](http://webdriver.io/api/protocol/alertDismiss.html) functions are not working since the geolocation popup is a confirmation box. Is there any way to handle this using javascript?

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 8.10
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):

## Details

> User validates geolocation settings:
> [chrome #0-0] no alert open
> [chrome #0-0] Error: An attempt was made to operate on a modal dialog when one was not open.
> [chrome #0-0]     at alertText() - index.js:307:3

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]

`
 browser.waitForLoading();
 browser.alertAccept();
`

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
@abhijithqb you can't dismiss this message with the alert command. It is not possible to do this with WebDriver. You need to set a proper browser profile I think to achieve this. This is not something WebdriverIO can fix. Therefor I am closing this. If you have further questions join the [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
