### ISSUE TITLE
browser.scroll uses selector-relative offset, element.scroll uses page-relative offset

### ISSUE THREAD

**Issue by mherodev** [webdriverio/webdriverio#2502]
## The problem
`browser.scroll` converts to an offset that is selector-relative, whereas `element.scroll` uses a static offset, scrolling irrespective of the element.

## Details
e.g. We have top and bottom fixed navigation elements, both roughly 50px tall, so we want to scroll an element to the top of the page, minus 100px, to make sure it's in view.

This works as expected:
```javascript
browser.scroll(selector, 0, -100);
```

This does nothing, as it tries to scroll above the top of the page:
```javascript
element.scroll(0, -100);
```

Since the element exists 500px down the page, we instead have to write:
```javascript
element.scroll(0, 400);
```

Which successfully scrolls us down 400px, 100px before the element. Not how we want to have to do that, of course. 

## Link to Selenium/WebdriverIO logs

```javascript
element.scroll(0, -100);
browser.scroll(element.selector, 0, -100);
```

```bash
[20:26:17]  DATA {"script":"return (function scroll(x, y) {\n    return window.scrollTo(x, y);\n}).apply(null, arguments)","args":[0,-100]}
[20:26:18]  DATA {"script":"return (function scroll(x, y) {\n    return window.scrollTo(x, y);\n}).apply(null, arguments)","args":[69.0625,401.59375]}
```

**Comment by mherodev** [comment]
Mind you, this may be intended behavior. I'm slowly coming to terms with the fact that WebDriverIO is following Selenium's API which doesn't always make the most sense to me.

**Comment by christian-bromann** [comment]
> so we want to scroll an element to the top of the page, minus 100px, to make sure it's in view.

I don't recommend to use any scrolling. The command will get removed with v5 and there is actually no need to scroll since it is part of the browser driver to do that.

That being said, the issue here is that the elementId is not propagated correctly. It could be fixed applying something similar to this: https://github.com/webdriverio/webdriverio/commit/026aff8315f012fecb0ca9df7e35d02cf0e6e748. Feel free to propose a PR. But again, scrolling should be not part of the testers concern.

**Comment by mherodev** [comment]
How will v5 handle fixed elements which overlap the elements you might need to click? Right now, our best approach is to scroll around them.

**Comment by christian-bromann** [comment]
> How will v5 handle fixed elements which overlap the elements you might need to click?

It won't. It will give you the info to just remove these elements via execute command.

**Comment by mherodev** [comment]
Isn't `browser.execute` kind of a hacky work-around? I figured the goal of the testing framework was to automate user actions. It's weird to have the user remove a page element.

Also, what about scroll events, testing infinite scrolling, etc.? It seems like a pretty fundamental interaction. Maybe I don't understand it being "part of the browser driver to do that".

**Comment by christian-bromann** [comment]
> Isn't browser.execute kind of a hacky work-around?

Yes it is.

> I figured the goal of the testing framework was to automate user actions.

Yes, but WebdriverIO can only instrument the browser driver. If the driver can't click on the element because another is lying on top of it, WebdriverIO can't click on that element.

> It seems like a pretty fundamental interaction.

Is it? The WebDriver spec doesn't contain any scrolling actions.

**Comment by mherodev** [comment]
Am I looking at the wrong document? I see a reference to `.scroll()`

WebDriver Spec: https://w3c.github.io/webdriver/webdriver-spec.html

DOM Window Scroll Y: https://drafts.csswg.org/cssom-view/#dom-window-scrolly

Either way, as someone who is writing tests, I appreciate being able tell my browser to scroll, it allows me to trigger scroll events and get elements in view for clicking. Will the click action no longer perform a scroll, either? 

I don't understand removing `scroll` from WebDriverIO. Is it an issue of responsibility? Should there be a helper library extending WebDriverIO which handles these typical use cases that aren't part of an underlying spec?

**Comment by christian-bromann** [comment]
> Is it an issue of responsibility?

Yes, there is no endpoint in the driver to actually perform a scroll.

> Should there be a helper library extending WebDriverIO which handles these typical use cases that aren't part of an underlying spec?

This is what WebdriverIO did for a while for Safari but these scroll emulations are flaky and can break in certain browser versions.

> it allows me to trigger scroll events and get elements in view for clicking

And exactly this is not necessary. The driver does the scrolling for you before clicking on the element. This is part of the spec:

```
The element interaction commands provide a high-level instruction set for manipulating form controls. Unlike Actions, they will implicitly scroll elements into view and check that it is an interactable element.
```

I don't really see a scenario where you would need to scroll in your e2e test.

**Comment by mherodev** [comment]
If the driver correctly handles scrolling an element into view (it currently does not, that is clear), I can imagine the click-scroll behavior being sufficient outside of some scroll-only edge cases.

**Comment by pmerwin** [comment]
I agree that click is not scrolling the element into view, and I have had to add /scroll to get .click to find the element.  That should be addressed because if .click is suppose to do the scrolling it is not in all cases working.

**Comment by christian-bromann** [comment]
> it is not in all cases working.

Can you describe in which environment it is not working?

**Comment by pmerwin** [comment]
I need to go back and confirm, but I had to use scroll to click on many elements... partially because some elements aren't in view until scrolled to, and partially not.  Anyway, sorry for lack of details, I will try and get specifics... also, I believe we ran into this because moveTo was deprecated and not working in ff or ie as I remember.

**Comment by joet87** [comment]
I need to scroll a div that contains terms of condition . Once I scroll the div, the check box to accept terms of condition gets enabled.  How will I handle that scenario ?

**Comment by christian-bromann** [comment]
> How will I handle that scenario ?

click on the parent element that is visible which would scroll it into viewport, then click on the checkbox

**Comment by joet87** [comment]
> click on the parent element that is visible which would scroll it into viewport, then click on the checkbox

I may not be following your suggestion properly. Clicking on the parent element for the check box is not enabling the check box.  

This is the div and in its property overflow is enabled which is creating the scroll-able view 
 **<div id="terms">TOC test thats' really long</div>**
**overflow: scroll;**

Why wouldn't one of them commands scroll the div box ? 
         _var toc = browser.element("#terms");
         toc.scroll();        
         browser.scroll('#terms',0,250);_

**Comment by christian-bromann** [comment]
The scroll command was supported but might not work anymore on every browser. You usually don't need to scroll at all when running WebDriver tests. Therefor such command is not natively in the spec. However clicking on an element actually triggers a scroll which is why I suggested to click on an element that is close to the checkbox. So first click triggers a scroll event and the second click enables the checkbox.

**Comment by joet87** [comment]
> The scroll command was supported but might not work anymore on every browser. You usually don't need to scroll at all when running WebDriver tests. Therefor such command is not natively in the spec. However clicking on an element actually triggers a scroll which is why I suggested to click on an element that is close to the checkbox. So first click triggers a scroll event and the second click enables the checkbox.

Thanks i get it, i don't think that strategy will work in this situation. When commands are not natively supported, is the suggestion to inject custom javascript ?

**Comment by christian-bromann** [comment]
> When commands are not natively supported, is the suggestion to inject custom javascript ?

This is also a good workaround

**Comment by vinicius-vilacalara** [comment]
Hello @mherodev @christian-bromann !
Are you able to use browser.scroll function?
We were using it without any problem here but suddenly it stopped working.
We could see some related issues regarding to the chromedriver version but even following the instructions to update it, the scroll is not working at all.

Just to help you understand my scenario:
I have one step that call a simple method (inside one page object class) where has the code below:

**browser.scroll(this.particleFeaturesLocator, 0, -100);**

where **this.particleFeaturesLocator** = '.particle-features-title' < an element not visible when you open the website.

Do you guys have some tip/idea/workaround to deal it this problem?

Thanks in advance.

**Comment by mherodev** [comment]
`browser.scroll` works as far as I can tell.

e.g. if I run the following code

```
describe('describe', () => {
  it('it', () => {
    browser.url('/');
    browser.waitForVisible('#some-id');
    browser.scroll('#some-id');
    browser.debug();
  });
});
```

My local Chrome instance will have scrolled to the appropriate div.

**Comment by vinicius-vilacalara** [comment]
Hello @mherodev !
We have tried again here and it is not working.
We are suspicious that the problem is related to a footer and a header that are fixed when we access the page using a mobile device.
By the way, thanks a lot!

Regards,
Vinicius Lara.

**Comment by Mort2007** [comment]
Is it possible to have something similar in V5 please?

Reason being some people have buttons to return you to X section of a page and without scroll or an alternative we are going to be forced to use some rather crude work around. (Most basic one would be a loop with sending page down till the element you wanted to stop on became isVisibleWithinViewport). 

An example a button on the page that returns you to the top to save user scrolling.

**Comment by christian-bromann** [comment]
> Is it possible to have something similar in V5 please?

Feel free to participate in make this happen

**Comment by sivis26** [comment]
Anyone help me to scroll the elements which is present on top of overlay.

In browser.elements(selector) it will return the set of elementIDs.
here selector is an dropdown.
I need to scroll to the next index when the previous index got clicked.I am unable to scroll using the elementID.  Without scrolling other element got clicked.it throws 'Element <a> is not clickable at point (245,712) because another element <button class="button" name="filter-btn"> obscures it'.

I tried with element elementIdLocation and then scroll using co-ordinates it doesn't work.Actually its scroll behind the overlay.


Thanks in advance!!!

**Comment by jasp402** [comment]
I have read the thread completely and I understand the reasons. But Scroll is super important when you want to try an infinite Scroll or pages that are rendered at the time of desplazarse as naturally does REACT. I do not see anything wrong leaving the function as it was and offering others its alternative scrollIntoView (). Whenever possible to establish the coordinates.

**Comment by christian-bromann** [comment]
> Any update on this one? I still vote to keep the scroll on the next version.

scroll is in v5 https://webdriver.io/docs/api/element/scrollIntoView.html. This command doesn't exist anymore. I don't know why someone would need to absolute scroll the browser. Please open a feature request if you have a solid use case for this.
