### ISSUE TITLE
.keys is deprecated according to docs, but does not produce a deprecation warning

### ISSUE THREAD

**Issue by mherodev** [webdriverio/webdriverio#2503]
Deprecation notice: http://webdriver.io/api/protocol/keys.html

And yet calling 

```
location.textbox.keys('Enter');
```

I do not see the same error I would otherwise see calling something like

```
location.textbox.submitForm();
```

**Comment by christian-bromann** [comment]
@mherodev WebdriverIO is transforming key commands into keyboard actions automatically, therefor no deprecation warning. The API of v5 will probably contain a keys command as it is a common use case and easy to abstract away.
