### ISSUE TITLE
doubleClick command refers to touchDoubleClick which no longer exists

### ISSUE THREAD

**Issue by erwinheitzman** [webdriverio/webdriverio#2506]
## The problem

The doubleClick command tries to execute to the touchDoubleClick command which is removed from the api when testing mobile.
This should be replaced with touchAction for mobile native testing or actions for mobile desktop testing.

## Environment

* WebdriverIO version: 4.9.11

## Link to Selenium/WebdriverIO logs

TypeError: _this.touchDoubleClick is not a function at doubleClick("[data-el="edit-filters"]") - at element("[data-el="edit-filters"]") - doubleClick.js:13:21

## Code To Reproduce Issue [ Good To Have ]

I didn't see a unit test for this under the mobile test folder, would be nice to include one I'd say.

**Comment by christian-bromann** [comment]
Hey,

we update the core architecture of WebdriverIO and with that a lot of implementation details that might make this issue obsolete. Please try with the latest version of WebdriverIO and verify if this still occurs. If so please open a new issue and we will tackle it asap.

Thanks!
