### ISSUE TITLE
After hook running after every session

### ISSUE THREAD

**Issue by moriahmaney** [webdriverio/webdriverio#2507]
## The problem

When using an `after` hook in my wdio.conf.js file, the `after` hook now runs after each browser session/spec file completes instead of once after all tests/sessions are complete. This behavior started occurring after updating webdriverio from version 4.8.0 to version 4.9.11. This behavior occurs on local runs and when running on SauceLabs.

## Environment

* WebdriverIO version: 4.9.11
* Node.js version: tested using v6.9.1 and v8.7.0
* wdio test runner
* synchronous 

## Code To Reproduce Issue [ Good To Have ]
```
after: () => {
    console.log('in after');
}

**Comment by christian-bromann** [comment]
> This behavior started occurring after updating webdriverio from version 4.8.0 to version 4.9.11

This was always the intended behaviour. I think the hook you are looking for is [onComplete](https://github.com/webdriverio/webdriverio/blob/master/examples/wdio.conf.js#L306-L313)
