### ISSUE TITLE
moveToObject error: 'x' must be an integer

### ISSUE THREAD

**Issue by diachedelic** [webdriverio/webdriverio#2508]
## The problem

I have been trying to drag an element to a new location: simply depress the left mouse button on an element, move to a new location and release.

However, I am impeded by the fact that I cannot use moveToObject - why?  Because calling `el.moveToObject()`, for me,  passes the underlying `touchMove` command params as floats - which results in this error:

```
[chrome #0-0] unknown error: 'x' must be an integer
[chrome #0-0] Error: An unknown server-side error occurred while processing the command.
[chrome #0-0]     at touchMove(611.0234375, 387.265625) - moveToObject.js:43:26
```

## Environment

* WebdriverIO version:  v4.7.1
* Node.js version: v8.9.0
* wdio testrunner sync
* wdio-chromedriver-service@^0.1.1
* MacOS v10.12.6

## Details

My workaround for dragging, for anyone having the same issue, is thus:

```
// hopefully located at (0, 0)
const BODY_ELEMENT = browser.element('body').value.ELEMENT

const location = browser.element('.my-handle').getLocation()

const from = {
  // centre on element and round floats
  x: Math.round(location.x) + 5,
  y: Math.round(location.y) + 5,
}

const to = {
  x: from.x + 100,
  y: from.y + 100,
}

browser.moveTo(BODY_ELEMENT, from.x, from.y)
browser.buttonDown(0)
browser.moveTo(BODY_ELEMENT, to.x, to.y)
browser.buttonUp(0)
```

## Link to Selenium/WebdriverIO logs

https://gist.github.com/diachedelic/e4078cfed98229c906d553f440758760

## Code To Reproduce Issue [ Good To Have ]

```
// .my-handle MUST have a non-integer location on the page
const el = browser.element('.my-handle')
el.moveToObject()
// throws error
```

**Comment by Efefefef** [comment]
+1 Thanks for workaround

**Comment by christian-bromann** [comment]
Hey,

we update the core architecture of WebdriverIO and with that a lot of implementation details that might make this issue obsolete. Please try with the latest version of WebdriverIO and verify if this still occurs. If so please open a new issue and we will tackle it asap.

Thanks!

**Comment by diachedelic** [comment]
Do you mean test it with v5 beta?

**Comment by christian-bromann** [comment]
> Do you mean test it with v5 beta?

@diachedelic yes

**Comment by YashMonetate** [comment]
This issue still exists. moveTo() sometimes work and sometimes not. see below:
![image](https://user-images.githubusercontent.com/70005957/122373521-2bf1df80-cf7f-11eb-887a-c3b7ca7b37e1.png)

**Comment by christian-bromann** [comment]
@YashMonetate `moveTo` is a deprecated JSONWP command, we recommend to use [`performActions`](https://webdriver.io/docs/api/webdriver#performactions)

**Comment by YashMonetate** [comment]
where do we define which element to move to in performActions? i am trying to define xpath in 'id' but it's not working. Pls put some code here
