### ISSUE TITLE
Forms With No Submit Button. 

### ISSUE THREAD

**Issue by GarrettS** [webdriverio/webdriverio#2509]
Dear SJWs, there is a challenge with submitting forms that have no submit button. 

```
1. using .SendKeys(Keys.Enter) on a form submit button with Firefox RemoteWebDriver doesn't submit the form #2079 
```
And `submitForm` is apparently scheduled for removal and/or unofficially implemented in Selenium.

```
2. WARNING: the "submit" command will be deprecated soon. If you have further questions, reach out in the WebdriverIO Gitter support channel (https://gitter.im/webdriverio/webdriverio).
```
Due to historical browser behavior, forms without submit buttons should be avoided. But in practice, the web developer did this.

**Comment by christian-bromann** [comment]
> Dear SJWs

Please stay respectful to others here in this project! If you don't like how I maintain this community feel free to use another tool.

To answer your question: you need to use the [actions](http://webdriver.io/api/protocol/actions.html) command to send keys like `Enter` to the page without directing it to a particular element.
