### ISSUE TITLE
HAR file generation in Protractor/Phantom using netsniff.js

### ISSUE THREAD

**Issue by h4wlt** [webdriverio/webdriverio#251]
Hi,

I am currently running a version of Protractor along with webdriverjs and Phantomjs.  There is an example js script included With Phantomjs called Netsniffjs which is a HAR file generator.  I have been pulling my hair out trying to get this working from within my tests, is there a way I can call Netsniff.js from within my test? It can be called from commandline like so:
bin/phantomjs examples/netsniff.js http://www.google.co.uk > test.har

Regards,
Craig

**Comment by harsheshbhakta** [comment]
Hi @christian-bromann 

How can I use browserMob with webdriverIO? And how can set new custom headers on browsers REST requests?

Any idea?

**Comment by christian-bromann** [comment]
@harsheshbhakta hi! Like I mentioned in one of my posts above I was able to get the HAR file using BrowsermobProxy but I don't know in what current state of development this project is. I was thinking anyway to build a Selenium Proxy using NodeJS which could enable things like custom headers or profiling. It's on a long ToDo list ;-)

For now I don't know how you could achieve custom headers in your browser requests. AFAIK it is not possible with Selenium.

**Comment by christian-bromann** [comment]
Ok closing this. It is definitely possible to grab har files with WebdriverIO and browsermob. Might be a nice integration project. However there is nothing right now in WebdriverIO I can do about it. It should be either a service or a plugin.
