### ISSUE TITLE
setValue error handling

### ISSUE THREAD

**Issue by simi823** [webdriverio/webdriverio#2511]
## The problem

In node shell testing setValue:
browser.setValue(input.selector, 'qa-testuser');
gives me the following error:
Error: An unknown server-side error occurred while processing the command.
    at evalmachine.<anonymous>:1:9
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.runInThisContext (vm.js:97:38)
    at node_modules/webdriverio/build/lib/commands/debug.js:54:43
    at elementIdValue("0.14105197243750278-13", "blahblah") - setValue.js:46:80

But it does add the text in the input textbox. Probably a stupid question, but as I am quite new with javascript/node, I am not sure the correct syntax to handle this error or understand why this is happening, even though it does work. The script fails because of the error.

## Environment

* WebdriverIO version: 4.9.11
* Node.js version: 6.10.3
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
standalone when testing on my computer
testrunner testing on browserstack
* if wdio testrunner, running synchronous or asynchronous tests:
I am not sure????
* Additional wdio packages used (if applicable):

## Details

Within the test script setValue produces error and fails the test completely.

## Link to Selenium/WebdriverIO logs

Error: An unknown server-side error occurred while processing the command.
    at evalmachine.<anonymous>:1:9
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.runInThisContext (vm.js:97:38)
    at node_modules/webdriverio/build/lib/commands/debug.js:54:43
    at elementIdValue("0.14105197243750278-13", "blahblah") - setValue.js:46:80

## Code To Reproduce Issue [ Good To Have ]

browser.setValue('.some-class-name', 'blahblah');

**Comment by christian-bromann** [comment]
Please check the logs of the browser driver. This error was not cause by WebdriverIO. The syntax looks ok.
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
