### ISSUE TITLE
--spec param ignored in presence of --suite

### ISSUE THREAD

**Issue by dalimian** [webdriverio/webdriverio#2514]
`--spec` param seems to be ignored in presence of `--suite` param. I assume this is by design. While I understand that `specs` property in the config is ignored in presence of `--suite` param I do feel that `--spec` is more specific param then `--suite` so `--spec` should take precedence

**Comment by WillBrock** [comment]
@dalimian https://github.com/webdriverio/webdriverio/pull/2505

**Comment by dalimian** [comment]
interesting, that pull request does opposite of how i would expect. so for  `--suite a --spec b` it runs both, i would expect it to only run `b` or find the overlap and run that

**Comment by WillBrock** [comment]
@dalimian Then don't specify the suite.

**Comment by webOS101** [comment]
I was going to poke around in this area myself.  For one, I was hoping we could change the spec into a regex instead of a string match, which would allow a lot more flexibility.  And two, add support for specifying `--exclude` on the command line.

**Comment by webOS101** [comment]
I forgot to add, I think suite should take precedence over spec, particularly for the change to spec I envision.

**Comment by christian-bromann** [comment]
Please see #2505 to see the current behavior.

> I was hoping we could change the spec into a regex instead of a string match, which would allow a lot more flexibility. And two, add support for specifying --exclude on the command line.

@webOS101 great idea, do you mind adding that to the v5 wish list?

**Comment by dalimian** [comment]
i can live with current design

> @dalimian Then don't specify the suite.

I have an npm/yarn shortcut  

"e2e-mobile": "wdio ./archetype/config/webdriver/wdio.mobile.conf.js ...<other params> --suite mobile",

so when people do `yarn e2e-mobile` i want it to run the whole mobile suite, but if they do `yarn e2e-mobile --spec a.js` only run a.js

but the current implementation is prob fine, no biggy

**Comment by dalimian** [comment]
@webOS101 regex for spec is a great idea, but even then the most common use case I feel would be running a single file

**Comment by webOS101** [comment]
I agree, but what's easier to type?   `--spec ./tests/mycomponent/mysuite/myTestCase-spec.js` or `--spec myTestCase`? :)

**Comment by dalimian** [comment]
`--spec myTestCase` is easier to type, but even in that example you meant to run a single file - myTestCase-spec.js

**Comment by webOS101** [comment]
well, yes, I just meant by making it a match, you don't have to supply a fully qualified path.
