### ISSUE TITLE
browser.isExisting() intermittently throws server side error on IE11

### ISSUE THREAD

**Issue by crisslyjames** [webdriverio/webdriverio#2523]
## The problem

When invoking browser.isExisting(), we are intermittently getting "An unknown server-side error occurred while processing the command. (UnknownError:13)", on IE11

## Environment

* WebdriverIO version: 4.8.0 
* Node.js version: v6.3.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):  wdio-sauce-service@0.4.6 

## Details

On IE11, browser.isExisting() is intermittently returning server-side error. The same test passes on occasion, when run with the same configurations.
[log.txt](https://github.com/webdriverio/webdriverio/files/1569662/log.txt)
[SauceLog.txt](https://github.com/webdriverio/webdriverio/files/1569666/SauceLog.txt)

## Link to Selenium/WebdriverIO logs

Added log files from Sauce and Jenkins for reference.

## Code To Reproduce Issue [ Good To Have ]

browser.waitUntil(() => {
      return browser.getUrl() !== currentUrl
        || browser.isExisting(".some-valid-class")
    }, 360000, "The URL not redirect to expected url")

**Comment by christian-bromann** [comment]
The error is thrown when fetching the `.wwsui-message-text` element. Without IEDriver error it is impossible to say why but it is unlikely that it is an WebdriverIO issue. Therefor I am closing this. Feel free to reach out in our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have further questions.
