### ISSUE TITLE
getTabIds / windowHandles doesn't work on IE11 driver 3.8.0

### ISSUE THREAD

**Issue by ronkorland** [webdriverio/webdriverio#2524]
## The problem

getTabIds and windowHandles commands throw error when I'm working on Selenium version 3.8.1 with IE driver 3.8.0

Error:
details: undefined,
message: '',
type: 'RuntimeError',
seleniumStack:
{ type: 'Unknown',
  message: 'Remote end send an unknown status code.',
  orgStatusMessage: '' } }

## Environment

* WebdriverIO version: 4.9.11
* Node.js version: v6.11.2
* WebdriverIO standalone

### Selenium logs:

07:41:38.941 INFO - Handler thread for session e29f6e74-f694-4cb9-938c-5eee58c38b81 (internet explorer): Executing GET on /session/e29f6e74-f694-4cb9-938c-5eee58c38b81/window_handles (handler: ServicedSession)

07:41:38.941 INFO - To downstream: { "error" : "unknown method", "message" : "Command not found: GET /session/e29f6e74-f694-4cb9-938c-5eee58c38b81/window_handles" }

### WebdriverIO logs
COMMAND	POST 	 "/wd/hub/session"
DATA {"desiredCapabilities"....
INFO SET SESSION ID e29f6e74-f694-4cb9-938c-5eee58c38b81
RESULT {"sessionId":"e29f6e74-f694-4cb9-938c-5eee58c38b81"....
COMMAND GET "/wd/hub/session/e29f6e74-f694-4cb9-938c-5eee58c38b81/window_handles"
DATA {}

## Code reference
Selenium return error message has empty string instead of  did not match a known command
```
if (err.message.match(/did not match a known command/)) {
```

**Comment by ronkorland** [comment]
The same issue occurs also in executeAsync and execute commands

**Comment by christian-bromann** [comment]
This should be fixed by now
