### ISSUE TITLE
Clarify in docs whether browser.url always triggers a page reload

### ISSUE THREAD

**Issue by jedwards1211** [webdriverio/webdriverio#2526]
It seems like `browser.url` always causes the page to reload, even if it's called with the same url as last time, but it's never good to *assume* something is true just because it *seems* to be true, so can we say explicitly how it behaves in the docs?

Or is Webdriverio at the mercy of Selenium, or worse individual browsers or browser drivers, on this point?

**Comment by christian-bromann** [comment]
> even if it's called with the same url as last time

Why would you assume this behavior? The command always triggers a page load.

> Or is Webdriverio at the mercy of Selenium

No

> or worse individual browsers or browser drivers, on this point?

No

WebdriverIO just follows the protocol. The actual browser behavior is up to the browser driver which usually follow the WebDriver spec.

**Comment by jedwards1211** [comment]
> The actual browser behavior is up to the browser driver which usually follow the WebDriver spec.
Ah, that's what I meant by "at the mercy of individual browser drivers".

**Comment by yuri-scarbaci-lenio** [comment]
I agree that the documentation should be explictly saying so

searching for the functionality on google leads to cached pages like http://v4.webdriver.io/v4.9/api/protocol/refresh.html and can be misleading

having an additional line at https://webdriver.io/docs/api/browser/url.html stating that when invoked with the same url it acts a refresh would be a good idea to me...

**Comment by christian-bromann** [comment]
@yuri-scarbaci-lenio please provide a PR with a patch to the docs, such insights are very helpful.

**Comment by jedwards1211** [comment]
I just made the PR 👍  I must have forgotten to after you answered my questions in OP
