### ISSUE TITLE
 Why do we need Selenium standalone server? 

### ISSUE THREAD

**Issue by apdarshan** [webdriverio/webdriverio#2527]
## The problem

Documentation is not clear about selenium standalone server. 

## Details

I am able to run tests in chrome headless mode using just [chromedriver](https://www.npmjs.com/package/chromedriver) & webdriverio. I didn't install/start selenium standalone server. But both of these links http://webdriver.io/guide.html http://webdriver.io/guide/getstarted/install.html tells us to download and start `selenium-standalone-server` not sure why it is required. Is it required in case of `firefox` only ? If yes, why it is needed ?

**Comment by christian-bromann** [comment]
It is just one of many ways to setup a browser driver. Given the endless possibilities we can't document all ways of running WebDriver tests. You can of course run a browser driver directly. 
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
