### ISSUE TITLE
Using geckodriver in standalone mode(without selenium server)

### ISSUE THREAD

**Issue by apdarshan** [webdriverio/webdriverio#2528]
## The problem

As per https://github.com/mozilla/geckodriver#standalone we can use geckodriver without any selenium server. But when I try to run tests after starting `geckodriver`. Webdriverio fails with following error.

```
Error: POST /wd/hub/session did not match a known command
      at new RuntimeError (node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
      at Request._callback (node_modules/webdriverio/build/lib/utils/RequestHandler.js:313:39)
      at Request.self.callback (node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/request/request.js:1163:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1085:12)
      at endReadableNT (_stream_readable.js:1059:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

## Environment

* WebdriverIO version: 4.9.11
* Node.js version: 8.6.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Standalone Mode

## Link to Selenium/WebdriverIO logs

I was able to achieve the same in **Chrome** using chromedriver. Here is the gist FYI:
https://gist.github.com/apdarshan/2f22cd4612db3748c149da9215cc51fe

## Code To Reproduce Issue [ Good To Have ]

```
    const opts = {
        desiredCapabilities: {
            browserName: 'firefox',
            "moz:firefoxOptions": {args: ["-headless"]}
        }
    };
      
    browser = webdriverio.remote(opts).init();
```

**Comment by christian-bromann** [comment]
For some reason the WebDriver endpoints are located on a different path in Geckodriver. If you run

```js
    const opts = {
        path: '/',
        desiredCapabilities: {
            browserName: 'firefox',
            "moz:firefoxOptions": {args: ["-headless"]}
        }
    };
      
    browser = webdriverio.remote(opts).init();
```

... it will work. Yes this could be better documented but WebdriverIO can't document all aspects from setting up a e2e test suite to how drivers work in particular. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. You will find help there in such cases.

**Comment by apdarshan** [comment]
Thanks @christian-bromann 👍  It works! I joined Gitter.
