### ISSUE TITLE
No way to shut off screenshots on error.

### ISSUE THREAD

**Issue by pmerwin** [webdriverio/webdriverio#2529]
## The problem

There is no way to shut off taking a screenshot on error.  We are using Try/Catch and expect errors, and do not need screenshots when that happens, as this slows down the test, and creates more possibility for something to go wrong.

## Environment

* WebdriverIO version: "webdriverio": "^4.9.9",
* Node.js version: v6.10.3
*testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable):

## Details

I want to set take screenshot to false inside of try blocks, as when we get an error in a try block, wdio is still taking a screenshot.  I want to turn this off/on in my function called from my tes.t

## Link to Selenium/WebdriverIO logs
AVailable if needed

## Code To Reproduce Issue [ Good To Have ]

available if needed, I have posted on gitter chat for any suggestions and have not received a response.  Thanks in advance!

"// Saves a screenshot to a given path if a command fails.
screenshotPath: config.wdio.errors,
//

Anyone know how to shut this off at spec/function level. We use Try/Catch and don't need a screen shot when an error is expected. The only option I see to change is the above. Tried setting this to null, did not work.

Any help? Just wondering what value to set in a local function try/catch that will shut off snapshots on error as I am expecting an error and do not need a snapshot. I thought if the error happened in the try block it should not trigger a snapshot but it does."

**Comment by pmerwin** [comment]
I tried setting browser.takesScreenshot = false; but a screenshot is still taken

**Comment by vbyjsue** [comment]
This is the workaround I'm using in v.4.8. Disables screenshot if first attempt failes, enables it for second attempt.
```javascript
const currentScreenshotPath = browser.options.screenshotPath;
    try {
      browser.options.screenshotPath = null;
      browser.click(selector);
      browser.options.screenshotPath = currentScreenshotPath;
    } catch(e) {
      browser.options.screenshotPath = currentScreenshotPath;
      browser.execute(`scrollBy(0, ${yOffset})`);
      browser.click(selector);
    }
```

**Comment by Alkaia** [comment]
Try commenting out the 

> screenshotPath: './errorShots/',

 line of the wdio.conf.js, that worked for me.

**Comment by pmerwin** [comment]
Awesome thanks, I will give this a try ^^^

**Comment by pmerwin** [comment]
That is working for me!  Thanks @vbyjsue  !

**Comment by endqwerty** [comment]
@vbyjsue thanks for sharing your solution. Its a usable workaround for now.

This issue is particularly annoying when interacting with iOS system messages. Using the documentation recommended solution, we get an error whenever an alert isn't open.
````
if (browser.alertText()) {
  browser.alertDismiss();
}
````

**Comment by mherodev** [comment]
Thanks @vbyjsue! This was also a workable solution for me.

**Comment by worc** [comment]
this issue has a wider impact when the tests are unable to create screenshots, like in [this issue](https://github.com/atti187/wdio-chromedriver-service/issues/9) the screenshot failure blocks logging of the failed test case. so now i have dozens of browser instances running, no screenshots, and no way to tell which tests failed.

**Comment by christian-bromann** [comment]
This issue was moved to webdriverio-boneyard/v4#15
