### ISSUE TITLE
Set UserAgent

### ISSUE THREAD

**Issue by nobleach** [webdriverio/webdriverio#253]
Is there a way to set the Browser's UserAgent other than using the browserName, version, platform method? Unfortunately, those do not work for setting my UserAgent as iOS, Mobile Safari version 7.0... and my app uses the browser string to decide whether to deliver the mobile version vs the desktop version.

**Comment by sean-hill** [comment]
Is this possible with firefox also?

**Comment by christian-bromann** [comment]
in Firefox you need to create a browser profile. Use https://github.com/saadtazi/firefox-profile-js to generate that and then add it to the capabilities:
```js
 var client = webdriverio.remote({
    desiredCapabilities: {
        browserName: ‘firefox’,
        firefox_profile: encodedProfile
    }
})
```

**Comment by sean-hill** [comment]
Oh wow, all right then! Thanks :)

**Comment by mrft** [comment]
And does someone also know how to do this for PhantomJS?

**Comment by rafis** [comment]
For PhantomJS perhaps this will work:

    var options = {
        desiredCapabilities: {
            browserName: 'phantomjs',
            'phantomjs.page.settings.userAgent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 1095) AppleWebKit/535.1 (KHTML like Gecko) Chrome/13.0.782.220 Safari/535.1'
        }
    };
    var client = webdriverio.remote(options);

**Comment by Kenith** [comment]
And does someone also know how to do this for firefox?

**Comment by bhanuagarwal73** [comment]
Any idea how to do it for safari browser ?
