### ISSUE TITLE
WDIO testrunner crashing when executing large number of tests

### ISSUE THREAD

**Issue by npeceniak** [webdriverio/webdriverio#2531]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to WebdriverIO). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, join the Gitter chat room ([![Gitter](https://badges.gitter.im/Join Chat.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge))!

I am having trouble with the WDIO testrunner crashing when I try to run a large number of tests in one suite. The current suite I have contains over 6000 tests but every time I try to run it crashes when it reaches 2500-3000 tests. Below is the error I get when it fails:

```
<--- Last few GCs --->

[20953:0x102801600]  6983708 ms: Mark-sweep 1403.2 (1464.8) -> 1403.2 (1433.8) MB, 1197.9 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1198 ms) last resort 
[20953:0x102801600]  6984920 ms: Mark-sweep 1403.2 (1433.8) -> 1403.2 (1433.8) MB, 1211.3 / 0.0 ms  last resort 

Error: channel closed
    at process.target.send (internal/child_process.js:562:16)
    at /Users/developers/repoman/repositories/spotx-js-e2e/node_modules/webdriverio/build/lib/runner.js:486:25
    at execHook (/Users/developers/repoman/repositories/spotx-js-e2e/node_modules/wdio-sync/build/index.js:166:35)
Error: channel closed
    at process.target.send (internal/child_process.js:562:16)
    at /Users/developers/repoman/repositories/spotx-js-e2e/node_modules/webdriverio/build/lib/runner.js:498:25
    at execHook (/Users/developers/repoman/repositories/spotx-js-e2e/node_modules/wdio-sync/build/index.js:166:35)
Error: channel closed
    at process.target.send (internal/child_process.js:562:16)
    at /Users/developers/repoman/repositories/spotx-js-e2e/node_modules/webdriverio/build/lib/runner.js:486:25
    at execHook (/Users/developers/repoman/repositories/spotx-js-e2e/node_modules/wdio-sync/build/index.js:166:35)
Error: channel closed
    at process.target.send (internal/child_process.js:562:16)
    at /Users/developers/repoman/repositories/spotx-js-e2e/node_modules/webdriverio/build/lib/runner.js:498:25
    at execHook (/Users/developers/repoman/repositories/spotx-js-e2e/node_modules/wdio-sync/build/index.js:166:35)
Error: channel closed
    at process.target.send (internal/child_process.js:562:16)
    at /Users/developers/repoman/repositories/spotx-js-e2e/node_modules/webdriverio/build/lib/runner.js:486:25
    at execHook (/Users/developers/repoman/repositories/spotx-js-e2e/node_modules/wdio-sync/build/index.js:166:35)
Error: channel closed
    at process.target.send (internal/child_process.js:562:16)
    at /Users/developers/repoman/repositories/spotx-js-e2e/node_modules/webdriverio/build/lib/runner.js:498:25
    at execHook (/Users/developers/repoman/repositories/spotx-js-e2e/node_modules/wdio-sync/build/index.js:166:35)
Error: channel closed
    at process.target.send (internal/child_process.js:562:16)
    at /Users/developers/repoman/repositories/spotx-js-e2e/node_modules/webdriverio/build/lib/runner.js:486:25
    at execHook (/Users/developers/repoman/repositories/spotx-js-e2e/node_modules/wdio-sync/build/index.js:166:35)
Error: channel closed
    at process.target.send (internal/child_process.js:562:16)
    at /Users/developers/repoman/repositories/spotx-js-e2e/node_modules/webdriverio/build/lib/runner.js:498:25
    at execHook (/Users/developers/repoman/repositories/spotx-js-e2e/node_modules/wdio-sync/build/index.js:166:35)
(node:20998) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4616): Error: channel closed
(node:20998) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 7.7.3
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): WDIO Testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):
    wdio-browserstack-service
    wdio-jasmine-framework
    wdio-json-reporter
    wdio-selenium-standalone-service

## Details

I have a suite of 6000+ tests that I am trying to run but the testrunner crashes when it reaches 2500-3000 tests. 

## Link to Selenium/WebdriverIO logs

https://gist.github.com/npeceniak/c7a8970a28b37f1f496d159407dc9974

**Comment by npeceniak** [comment]
I did find a pretty similar issue from a while ago but my issue occurs when running a high number of tests and it seems like this issue https://github.com/webdriverio/webdriverio/issues/1549 only was happening when the user was interupting execution.

**Comment by christian-bromann** [comment]
2500-3000 tests is a lot of stuff you want to run in parallel and your machine is probably not able to cope with that amount of work. In v5 we are planning support running tests on external machines (e.g. on [AWS Fargate](https://aws.amazon.com/de/fargate/), see [v5 discussion](https://github.com/webdriverio/webdriverio/issues/2403#issuecomment-349990987)). I recommend to [limit](https://github.com/webdriverio/webdriverio/blob/master/examples/wdio.conf.js#L60) the number of instances so that your machine can deal with the load.

Closing as I don't see any imminent action that can be done here. To scale it in a way as you require it we need to have a different architecture in place that we are building up in v5 of WebdriverIO

**Comment by npeceniak** [comment]
@christian-bromann I might have been unclear with my original post. I have 6000 total tests but I am not trying to run them all in parallel. I am using browserstack to run the actual tests and I have the number of parallel tests set to 5. The problem seems to be with the testrunner and the child process getting disconnected/ not closing. 

I do get the same error if I limit the parallelization to 1 and it still fails around the same number of tests it just takes way longer to actually reach that point running a single test at a time.

**Comment by npeceniak** [comment]
I have rerun my suite using a different reporter just to make sure that the reporter was not the thing that was causing issues and I got the same results using the built in dot reporter. I did get a little clearer error message. It seems that the node process is running out of memory. 
@christian-bromann Please let me know if there is any additional information I can provide to figure out what is causing this issue and get it resolved. Thanks.

```
<--- Last few GCs --->

[22973:0x103000000]  6493837 ms: Mark-sweep 1402.1 (1461.5) -> 1402.0 (1433.5) MB, 1184.8 / 0.0 ms  last resort 
[22973:0x103000000]  6495063 ms: Mark-sweep 1402.0 (1433.5) -> 1402.0 (1433.0) MB, 1226.2 / 0.0 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3e6af7e266a1 <JS Object>
    2: output [/Users/developers/repoman/repositories/spotx-js-e2e/node_modules/webdriverio/build/lib/utils/ReporterStats.js:406] [pc=0x21694d5b3326](this=0x159dbbf1b0d9 <a ReporterStats with map 0x2aa1c78764a9>,type=0x2d3af74cf289 <String[12]: aftercommand>,runner=0x26a23f250d81 <an Object with map 0x2aa1c7876241>)
    3: /* anonymous */ [/Users/developers/repoman/repositories/spotx-js-e2e/nod...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewUninitializedFixedArray(int) [/usr/local/bin/node]
 5: v8::internal::(anonymous namespace)::FastElementsAccessor<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2> >::AddArguments(v8::internal::Handle<v8::internal::JSArray>, v8::internal::Handle<v8::internal::FixedArrayBase>, v8::internal::Arguments*, unsigned int, v8::internal::(anonymous namespace)::Where) [/usr/local/bin/node]
 6: v8::internal::(anonymous namespace)::DoArrayPush(v8::internal::Isolate*, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 7: 0x21694cf8ed46
 8: 0x21694cfa7e05
Error: channel closed
    at process.target.send (internal/child_process.js:562:16)
    at /Users/developers/repoman/repositories/spotx-js-e2e/node_modules/webdriverio/build/lib/runner.js:498:25
    at execHook (/Users/developers/repoman/repositories/spotx-js-e2e/node_modules/wdio-sync/build/index.js:166:35)
Error: channel closed
    at process.target.send (internal/child_process.js:562:16)
    at /Users/developers/repoman/repositories/spotx-js-e2e/node_modules/webdriverio/build/lib/runner.js:486:25
    at execHook (/Users/developers/repoman/repositories/spotx-js-e2e/node_modules/wdio-sync/build/index.js:166:35)
...
```

**Comment by npeceniak** [comment]
I have found a workaround for this issue. Node has a memory limit of ~1.5GB by default and I was hitting this limit when trying to run thousands of tests on a single run. This memory limit can be increased with the --max-old-space-size flag on the node process. It seems there is still some sort of memory leak because of how much memory it uses but if you need to run thousands of tests increasing the memory limit is a good workaround.

**Comment by christian-bromann** [comment]
> It seems there is still some sort of memory leak because of how much memory it uses but if you need to run thousands of tests increasing the memory limit is a good workaround.

Yes! We will improve this in v5 where single tests run their own reporters and don't report events upstream which will reduce the amount of RPC messages drastically. Also you will be able to run tests serverless on AWS or Google Cloud and will be able to run thousand of tests in parallel.

**Comment by jliebrand** [comment]
@npeceniak can you tell me how you passed the --max-old-space-size=4096 to the node process that wdio launches?

**Comment by WillBrock** [comment]
@npeceniak You can just do ```node --max-old-space-size=4096 ./node_modules/.bin/wdio ....```

Or like Christian said in v5 you probably won't need to do this anymore.

**Comment by jliebrand** [comment]
@WillBrock thanks! It doesn't look like this was my problem though - even with a high mem limit, it still fails. My tests are uploading small'ish files (70mb) but after three uploads, things fall over. I'm going to for now try to work around this by only uploading one file each test run and just restarting the entire test run until all files are uploaded... not ideal, but hopefully will unblock me
