### ISSUE TITLE
Getting the url of tab not in focus

### ISSUE THREAD

**Issue by me12722** [webdriverio/webdriverio#2532]
## The problem
I am clicking on an element on my page which opens a new tab then trying to grab the url of the newly opened tab but I am still getting the url of the previous tab. I am using BrowserStack so I am able to confirm that I am currently on the tab that I want to be on. 
## Environment

* WebdriverIO version: 4.6.1
* Node.js version: 6.9.2
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): WDIO
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Code To Reproduce Issue [ Good To Have ]
 client
        .click('#wrpr_1431108056877h')
        .pause(3000)
        .refresh()
        .getUrl()
        .then((url: any) => {
            console.log(url);
        })

**Comment by christian-bromann** [comment]
@me12722 you need to switch to the created tab using [switchTab](http://webdriver.io/api/window/switchTab.html#Usage). 
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
