### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [webdriverio/webdriverio#2533]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature,

It's  55 times faster than EJS, so it may be a good idea to use it instead of EJS 😀

**Comment by christian-bromann** [comment]
@Drulac you are absolutely right, feel free to propose a PR. Since it isn't really that important to generate the wdio.conf.js template quickly I don't see that as a major issue tho.

**Comment by mhemesath** [comment]
> it isn't really that important to generate the wdio.conf.js template quickly

The larger benefit is probably removing an additional external dependency in the project

**Comment by christian-bromann** [comment]
We still use ejs in v5. It seems to be simpler especially since we have a bunch of logic in the templates that would make it complex when used with ES6 literals.
