### ISSUE TITLE
 Error: An element could not be located on the page using the given search parameters ("input[Search_Query_Term1="R"]")

### ISSUE THREAD

**Issue by neville4529** [webdriverio/webdriverio#2537]
My code:
module.exports = function() {

  this.Given(/^I have visited bct-test.ucdavis.edu$/, function () {
    browser.url('https://bct-test.ucdavis.edu/bct_nation/home.seam');
  });
  this.When(/^I click Browse Trials$/, function () {
    browser.click('#HomeBrowseButton');
  });
  this.Then(/^I see All Trials$/, function () {
    browser.screenshot('BrowseTrialsMetastaticLink.png');
  });

 this.When(/^I search All Trials for "([^"]*)" or "([^"]*)"$/, function (SearchTerm1, SearchTerm2) {
         // Write code here that turns the phrase above into concrete actions
    browser.setValue('input[Search_Query_Term1="R"]', SearchTerm1);
    browser.setValue('input[Search_Query_Term2="O"]', SearchTerm2);
    browser.click(['#searchGo']);
  });

  this.Then(/^I see All Trials for "Reproductive" and "Online"$/, function () {
    var my_expected_text='Trials contain';
    var my_displayed_text = document.getElementsByClassName('ContentHeaderText');
    expect(my_displayed_text).toBe(my_expected_text);
  });
}

Error Message below when run the chimp
[chimp] Running...
Feature: Search All Trials

    As a breast canceer patient
    I want to search the All Trials on the web
    So I can find information

  Scenario: Search for Reproductive or Online
  ✔ Given I have visited bct-test.ucdavis.edu
  ✖ When I search All Trials for "Reproductive" or "Online"
  - Then I see All Trials for "Reproductive" and "Online"

Failures:

1) Scenario: Search for Reproductive or Online - features/searchalltrials.feature:7
   Step: When I search All Trials for "Reproductive" or "Online" - features/searchalltrials.feature:9
   Step Definition: features/support/searchalltrials.js:13
   Message:
     Error: An element could not be located on the page using the given search parameters ("input[Search_Query_Term1="R"]").
         at World.<anonymous> (features/support/searchalltrials.js:15:13)
         at _combinedTickCallback (internal/process/next_tick.js:73:7)
         at process._tickDomainCallback (internal/process/next_tick.js:128:9)

1 scenario (1 failed)
3 steps (1 failed, 1 skipped, 1 passed)
0m02.189s

**Comment by christian-bromann** [comment]
@neville4529 I think the error message is clear. Not sure how this is an issue in WebdriverIO. 
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
