### ISSUE TITLE
Chrome not reachable

### ISSUE THREAD

**Issue by mathis7875** [webdriverio/webdriverio#2539]
## The problem

Chrome driver is not reachable when running codecepjs test. Instead using npm chromedriver and also install manually .using latest version of chrome and standalone server is running

## Environment

* WebdriverIO version: lastet sierra high
* Node.js version: latest
* Selenium -Standalone
* wdio backend

## Details
My config codecept.JS
"tests": "./*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "WebDriverIO": {
      "url": "http://www.mysite.com",
      "browser": "chrome",
      "windowSize": "1152x1000",
      "show": true,
      "desiredCapabilities": {
        "browsername": "chrome",
        "chromeOptions": {
          "binary": "/Projects/testautomation/node_modules/chromedriver/lib/chromedriver/chromedriver"
        }
      }

## error message

 chrome not reachable
  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.13.2 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.10 seconds
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:07:36.161Z'
System info: host: 'ip-192-168-2-3.us-west-1.compute.internal', ip: 'fe80:0:0:0:d3:d396:e9b1:9724%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.2', java.version: '9.0.1'
Driver info: driver.version: unknown
  rror: chrome not reachable
    (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.13.2 x86_64) (WARNING: The server did not provide any stacktrace information)
  Command duration or timeout: 60.10 seconds
  Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:07:36.161Z'
  System info: host: 'ip-192-168-2-3.us-west-1.compute.internal', ip: 'fe80:0:0:0:d3:d396:e9b1:9724%en0',os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.2', java.version: '9.0.1'
  Driver info: driver.version: unknown
      at new RuntimeError (/usr/local/lib/node_modules/codeceptjs-webdriverio/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
      at Request._callback (/usr/local/lib/node_modules/codeceptjs-webdriverio/node_modules/webdriverio/build/lib/utils/RequestHandler.js:313:39)
      at Request.self.callback (/usr/local/lib/node_modules/codeceptjs-webdriverio/node_modules/request/request.js:186:22)
      at Request.<anonymous> (/usr/local/lib/node_modules/codeceptjs-webdriverio/node_modules/request/request.js:1163:10)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/codeceptjs-webdriverio/node_modules/request/request.js:1085:12)

**Comment by christian-bromann** [comment]
@mathis7875 this is a setup issue and is not related to WebdriverIO. I assume that Chrome crashes when you start it. There is nothing WebdriverIO can do here.
