### ISSUE TITLE
Disable warnings for internal calls to deprecated functions

### ISSUE THREAD

**Issue by rubenlg** [webdriverio/webdriverio#2541]
## The problem

I get the following error message:

```
WARNING: the "moveTo" command will be deprecated soon. If you have further questions, reach out in the WebdriverIO Gitter support channel (https://gitter.im/webdriverio/webdriverio).
Note: This command is not part of the W3C WebDriver spec and won't be supported in future versions of the driver. It is recommended to use the actions command to emulate pointer events.

(You can disable this warning by setting `"deprecationWarnings": false` in your WebdriverIO config)

WARNING: the "buttonPress" command will be deprecated soon. If you have further questions, reach out in the WebdriverIO Gitter support channel (https://gitter.im/webdriverio/webdriverio).
Note: This command is not part of the W3C WebDriver spec and won't be supported in future versions of the driver. It is recommended to use the action command as a replacement for this.

(You can disable this warning by setting `"deprecationWarnings": false` in your WebdriverIO config)
```
## Environment

* WebdriverIO version:4.10.0
* Node.js version: 7.10.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): testrunner
* if wdio testrunner, running synchronous or asynchronous tests: asynchronous
* Additional wdio packages used (if applicable): n/a

## Details

I wasn't calling moveTo or buttonPress. I was calling leftClick, which is not deprecated.

Disabling deprecation warnings is not an option, because I do want to know if I'm calling a deprecated API and migrate to the new one. But the fact is I'm not calling any deprecated API, so these messages add a lot of spam to my logs that make it hard to spot real problems in my tests. Specifically, they make it hard to notice real deprecated method calls from my test code.

### Proposal 1:

Have two versions of these methods, the internal one that doesn't log errors, and the public one that logs them and then calls the internal version to do the actual work. Internal calls like the one done from leftClick would call the internal version only and don't log anything, and external (test) calls would log the error message. This way, developers would get actionable warnings if they have a problem in their test code.

### Proposal 2:

Have another flag `internalDeprecationWarnings` set to false by default and allow developers to enable it if they want. webdriverio tests could enable it to make sure you don't forget to migrate your own code.

## Code To Reproduce Issue [ Good To Have ]

let canvas = browser.$('#game-canvas');
canvas.leftClick(100, 100);

**Comment by christian-bromann** [comment]
@rubenlg feel free to open a PR that uses the action command to do the leftClick. I rather have that fixed instead making the deprecation logic more complex.

**Comment by christian-bromann** [comment]
I think we will keep the way things are for v4. In v5 there won't be any deprecation warnings anymore and a lot of commands that are currently marked as deprecated will still be around but implemented with the right W3C Webdriver command. Closing this.
