### ISSUE TITLE
isMobile, isIOS, isAndroid are not documented in apis

### ISSUE THREAD

**Issue by Tallyb** [webdriverio/webdriverio#2543]
## The problem
missing documentation for the above actions.

**Comment by christian-bromann** [comment]
They are: http://webdriver.io/guide/testrunner/browserobject.html#Check-if-capability-is-a-mobile-device. Feel free to propose a PR that makes it easier to find.

**Comment by Tallyb** [comment]
I believe they should be in the Apis. How are those being generated?

**Comment by christian-bromann** [comment]
> How are those being generated?

They are being set when an instance is created

**Comment by Tallyb** [comment]
Sorry, my bad. I meant, how does the Apis docs are being generated.

**Comment by christian-bromann** [comment]
see https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md#documentation
