### ISSUE TITLE
File is not uploaded on chrome/mac - using "uploadFile" 

### ISSUE THREAD

**Issue by saritanzu** [webdriverio/webdriverio#2545]
I am trying to upload a file using "uploadFile" function, it opens the modal, does not show any error. Yet when form is complete, the file is not uploaded

## Environment
* WebdriverIO version:
* Node.js version: 6.12.3
* Selenium stand alone
*framework: mocha
macOS
Chrome

## Code To Reproduce Issue [ Good To Have ]
```
appsPage.appLogo_dialog.click();
        appsPage.appLogo_dialog.waitForExist(5000);
        appsPage.appLogo_dialog.uploadFile(dataInput.appLogoPath);

```
The path is read from a module.exports file:
`  "appLogoPath": "/Users/saritvakrat/Documents/upload_fiels_for_dashboard/pepsi.png"
`

**Comment by christian-bromann** [comment]
Can you provide any error logs or reproducible examples?

**Comment by saritanzu** [comment]
I have managed to solve the issue. Thanks

**Comment by cameronking4** [comment]
> I have managed to solve the issue. Thanks

How did you manage to solve the issue? I'm having the same problem

**Comment by thuvvashan20** [comment]
> I have managed to solve the issue. Thanks

I am facing the same issue, May I know how did you managed to solve the issue ?
