### ISSUE TITLE
wdio 5 could exit with error code, if no files found?

### ISSUE THREAD

**Issue by kajmagnus** [webdriverio/webdriverio#2547]
## The problem

wdio exits with status code 0 = all fine, if no files found. But most likely this means the user typed a typo or the wrong file name — because one wouldn't start wdio at all, if one didn't intend to run any tests?

The result is that a few times, I've started wdio as part of an automatic script, and incorrectly believed all tests were OK, although in fact some of the tests were never run.

Maybe change this, in upcoming Webdriver.io version 5? So no-files-found = error exit code?

(I asked about this in the Gitter chat, result: one person agreed that it'd be good with an error exit code, like 1; no other person replied)

## Environment

* WebdriverIO version: `wdio -v` says v4.9.11
* Node.js version: v7.10.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): `wdio`
* if wdio testrunner, running synchronous or asynchronous tests: Synchronous
* Additional wdio packages used (if applicable): wdio-mocha-framework

## Code To Reproduce Issue [ Good To Have ]

Here you can see that wdio exits with code 0: (apparently there're two different ways to trigger exit code 0? 1) exact file name that isn't found, and 2) a pattern that matches nothing)

```
09:12:40 39 ~/dev/ed/ed-server[master*]$ cat no-files-found-exact.conf.js
"use strict";
var api = {
	config: {
    specs: ['no-files-found.js'],
    exclude: [],
    capabilities: [{
      browserName: 'chrome'
    }]
  }
};
module.exports = api;
09:12:48 40 ~/dev/ed/ed-server[master*]$ ./node_modules/.bin/wdio no-files-found-exact.conf.js

pattern no-files-found.js did not match any file

09:12:58 41 ~/dev/ed/ed-server[master*]$ echo $?
0

09:13:15 42 ~/dev/ed/ed-server[master*]$ cat no-files-found-pattern.conf.js
"use strict";
var api = {
	config: {
    specs: ['*no-files-found-pattern*.js'],
    exclude: [],
    capabilities: [{
      browserName: 'chrome'
    }]
  }
};
module.exports = api;

09:13:22 43 ~/dev/ed/ed-server[master*]$ ./node_modules/.bin/wdio no-files-found-pattern.conf.js
0 passing (1.60s)

09:13:32 44 ~/dev/ed/ed-server[master*]$ echo $?
0
```

**Comment by christian-bromann** [comment]
@kajmagnus how are other testrunner behave in that situation?

**Comment by kajmagnus** [comment]
The testrunner, that's `./node_modules/.bin/wdio`?

Or do you mean "test runner framework", like Jasmine and Cucumber and Mocha?
Or maybe test-result-reporter?

Should I try with different  `framework: 'mocha',`  or `jasmine` combinations, or maybe different reporters?: `reporters: ['dot', 'allure'],`

**Comment by kajmagnus** [comment]
@christian-bromann   The testrunner, that's `./node_modules/.bin/wdio`?

Or do you mean "test runner framework", like Jasmine and Cucumber and Mocha?
Or maybe test-result-reporter?

Should I try with different  `framework: 'mocha',`  or `jasmine` combinations, or maybe different reporters?: `reporters: ['dot', 'allure'],`

**Comment by christian-bromann** [comment]
This issue was moved to webdriverio/v5#81
