### ISSUE TITLE
getUrl/getHTML method naming inconsistent

### ISSUE THREAD

**Issue by efx** [webdriverio/webdriverio#2549]
## The problem

In the API, `getUrl` is at odds with `getHTML` (or vice versa). I think both need to be consistent.
## Environment

* WebdriverIO version:
* Node.js version:

## Details

I think there are 2 possible naming scenarios:
1. capitalize both:  `getURL` and `getHTML`
2. camel case both: `getUrl` and `getHtml`

**Comment by codeclown** [comment]
Agreed. I vote for `getUrl` and `getHtml`.

**Comment by christian-bromann** [comment]
I will make sure to have the second solution implemented right in v5. Thanks for the suggestion!
