### ISSUE TITLE
Safari - windowHandleFullscreen - keeps failing on "The command was not found"

### ISSUE THREAD

**Issue by saritanzu** [webdriverio/webdriverio#2552]
## The problem
Safari - windowHandleFullscreen - keeps failing on "The command was not found".
I have a test that uses safari, it opens the URL and maximizes the screen. But it keeps failing due to the following error and stops the test:
```
The command 'POST /session/EC0CD2C5-E8DD-4C50-BECD-DC33AF71B2F8/window/fullscreen' was not found.
running safari
Error: The command 'POST /session/EC0CD2C5-E8DD-4C50-BECD-DC33AF71B2F8/window/fullscreen' was not found.
    at Context.<anonymous> (test/TestCases/AppsPage.js:11:14)
    at Promise.F (node_modules/core-js/library/modules/_export.js:35:28)
    at windowHandleFullscreen() - at Object.beforeInit (test/Utilities/Utilities.js:10:17)
```

Any idea what can I use instead in the meantime? I am running chrome, firefox, safari and edge

## Environment

* WebdriverIO version:
* Node.js version: 6.12.3
*  wdio testrunner
*Mac, Safari latest version -11.0

Capabilities:
     capabilities: [{
         browserName: 'chrome',
         maxInstances:2,
         cssSelectorsEnabled: true,
        applicationCacheEnabled: true,
         webStorageEnabled: true,
     } , {
         browserName: 'firefox',
       maxInstances:2,
        cssSelectorsEnabled: true,
         applicationCacheEnabled: true,
       webStorageEnabled: true,
    }, {
         browserName: 'explorer',
         maxInstances:2,
           cssSelectorsEnabled: true,
      applicationCacheEnabled: true,
     webStorageEnabled: true,
     }, {
        browserName: 'safari',
        maxInstances:1,
        cssSelectorsEnabled: true,
        applicationCacheEnabled: true,
        webStorageEnabled: true,
    }],

**Comment by christian-bromann** [comment]
This is because Safari hasn't fully implemented the [W3C spec](https://w3c.github.io/webdriver/webdriver-spec.html#fullscreen-window) yet. I would just not use the command in safari in the meantime.

**Comment by saritanzu** [comment]
Is there another command to increase the screen size? It's too small and aborts the operations of the tests

**Comment by christian-bromann** [comment]
Not sure what beforeInit is but you should be able to access the capabilities somehow
