### ISSUE TITLE
Not possible to setValue in to the input.

### ISSUE THREAD

**Issue by nazarposhta** [webdriverio/webdriverio#2553]
I can't setValue in to the input which doesn't have any value from the beginning. 
`Error: element (".tabs_component:nth-child(3) .body_of_tabs .date_premium .DayPickerInput input") still without a value after 30000ms`
This error I receive and what to do with that?
Any idea?

**Comment by christian-bromann** [comment]
@nazarposhta without any example code or error message this is impossible to say. Please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
