### ISSUE TITLE
Monadic nature of browser is barely documented

### ISSUE THREAD

**Issue by jedwards1211** [webdriverio/webdriverio#2554]
According to http://webdriver.io/api/protocol/elements.html, `browser.elements` returns
> `<Object[]>`: A list of WebElement JSON objects for the located elements.

Maybe it does return an array when using `fibers` with webdriverio, but I only use the async methods, and `browser.elements` resolves to a monad instead:
```js
{
  state: 'success',
  value: [
    // elements
  ]
}
```

Same goes for a lot of other methods like `execute`, `executeAsync`, `elementIdText`, etc.

Nowhere is this discussed in the docs.  Typing "monad" into the search on the WebdriverIO homepage returns no results.

**Is there any method I can call at the end of the chain to resolve to the `value` of the monad instead of the full object, and reject if `state` is failure?**

Furthermore, I know that one can do `browser.element(...).getText()` because of the monadic structure, but this is not prominently documented anywhere that I can see.  The best I've found is `http://webdriver.io/guide/usage/selectors.html#Chain-Selectors`, which doesn't mention that `browser` is a monad and that *all* methods are chainable in this way.

But another thing is unclear from the docs: would `browser.elements(...).getText()` successfully get the text of multiple elements?  Would it get the text in parallel or serially?

**Comment by christian-bromann** [comment]
With v5 we moved away from the monadic structure in v4. The API is much more simplified now.

**Comment by jedwards1211** [comment]
Awesome, looking forward to it!
