### ISSUE TITLE
capabilities should still be a list, not a dictionary

### ISSUE THREAD

**Issue by slysenko** [webdriverio/webdriverio#2557]
https://github.com/webdriverio/webdriverio/blob/07eaae4ad9163a468bf5e259485201a9089b88fc/examples/wdio/wdio.multiremote.conf.js#L23

this should be the correct code:

```javascript 
capabilities: [{
  browserA: {
    desiredCapabilities: {
      browserName: 'firefox',
      platform: 'WINDOWS'
    }
  },
  browserB: {
    desiredCapabilities: {
      browserName: 'chrome',
      platform: 'WINDOWS'
    }
  }
}];
```

**Comment by christian-bromann** [comment]
@slysenko no. The example demonstrates running WebdriverIO in multiremote mode. Please also see http://webdriver.io/guide/usage/multiremote.html. 
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
