### ISSUE TITLE
Handle loop

### ISSUE THREAD

**Issue by phuna** [webdriverio/webdriverio#256]
Hi,
I'm sorry if this place is for issues reporting only. I don't find any forum link on webdriver.io so I think I can ask here.
I'm trying to use webdriverjs to in my project but due to its async nature I don't know how to handle this case:
I have a page dislay an issue list. I want to write a loop for all issues in the list, click on each issue and change it's type and refresh. After an issue's type is changed it will not be displayed in issue list any more. Below is the sample code:

``` javascript
var finished = false;
while (!finished) {
    client
        .buttonClick('#refresh')
        .waitFor('#issue_link', 2000, function(err, res) {
            if (err != null) {
                console.log("Got empty result, just quit")
                finished = true;
                return;
            }
            client
                .buttonClick('#issue_link')
                //... Change issue type here
        });
}
```

When I run the script, it seems entering infinite loop and do nothing. If I remove while loop then code runs fine but only 1 issue is changed.

Thanks,
Phu

**Comment by StephaneP** [comment]
Sorry for commenting on a closed issue but I tried in a recursive way and it chokes with chainit basically hitting the max listeners for eventemitter.

**Comment by christian-bromann** [comment]
You are right. At one point it will crash. But usually you don't reach that point in your test unless there is a problem with it. What are you trying to do?
