### ISSUE TITLE
Unable to create a variable that keeps it state regardless of number of sessions

### ISSUE THREAD

**Issue by psmod2** [webdriverio/webdriverio#2562]
## The problem

I have a pool of users that I'm trying to keep track of as each of my tests execute in parallel. 
However each time a new session opens anything I have declared is replaced.

For example, in wdio conf if i have do

```
exports.config = {
  myVar: ['a', 'b', 'c']
}
```

If 3 sessions are opened up to run in parallel, and on each one I pop from this myVar array, I would expect them to use `a` then `b` then `c` however they all use `a`.

Is this an issue or have misunderstood something. I can't figure out where I can have suhc variables that keep the state as I use them.

## Environment

* WebdriverIO version: 4.10.1
* Node.js version: 6.8.4
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
* if wdio testrunner, running synchronous or asynchronous tests: wdioTestRunner
* Additional wdio packages used (if applicable):

**Comment by christian-bromann** [comment]
@psmod2 every testrun gets a copy of the wdio config. So if you change it in one test run it won't affect other test runs. If you want to store a state across testruns I would recommend to create a temprary json file on the file system and import it in the test.

**Comment by psmod2** [comment]
@christian-bromann - Thanks - so the reason I need this is because:
- I have 80 tests
- Each tests requires the login of some user. And i can't use the same user in 2 parallel tests.
- I can't create users on the fly, so I have a pool of users
- Now as my tests run in parallel, I can either create a unique user for each test, or (I prefer) do a push and pop of users I've used from my pool

-> So to confirm, to do the latter (push and pop), you suggest that this array of availableUsers I use `fS` (File Stream) to write to a file and keep track? I guess I would need to use promises carefully as my parallel tests could easy begin at the exact same time??
