### ISSUE TITLE
capabilities - applicationCacheEnabled: true - not working

### ISSUE THREAD

**Issue by saritanzu** [webdriverio/webdriverio#2563]
## The problem

I am running  the following capabilities:
```
    capabilities: [{
        browserName: 'chrome',
        maxInstances:3,
        cssSelectorsEnabled: true,
        applicationCacheEnabled: true,
        webStorageEnabled: true,
```
Yey, when my site runs it's super slow and it does not save the cache. I have to use production site which relays on cache since the first launch is very heavy. All my tests are failing if I am running more than one test at a time.
## Environment

* WebdriverIO version:
* Node.js version: 6.12.3
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): selenium stand alone + wdio testrunner

**Comment by christian-bromann** [comment]
Hi @saritanzu , thanks for raising the issue. Unfortunately WebdriverIO is just passing along the settings and it is up to the browser driver to respect it. Afaik `applicationCacheEnabled` is depcrecated and doesn't work in most of the browser.

If you have further questions please reach out to our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). Thanks!
