### ISSUE TITLE
how to upload file when element is not input

### ISSUE THREAD

**Issue by jiangyd** [webdriverio/webdriverio#2564]
this is my element :

  ```           
   <a ng-disabled="licUpload" ngf-select="selectLicense($file)" name="licenseImageFile" class="btn btn-success">请选择附件 </a>
  ```

use choosefile is don't work     ， What API should I use

**Comment by christian-bromann** [comment]
I am not sure..usually you should find a input#type=file element that is created by this angular element. You can't use chooseFile on a link element.
