### ISSUE TITLE
support for assertions?

### ISSUE THREAD

**Issue by sharmarahul** [webdriverio/webdriverio#2566]
I am making a switch from using Capybara/Rspec in to WebdriverIO so please let me know if the following is not an issue or doesn't belong to `webdriverio`

rspec `expect` style assertions are great and capybara patched in a few custom matchers/assertions as syntactic sugar to improve readability. So, it supported something like

`expect(page).to have_selector(.css-selector)`

Is it possible to do something like this is chai when using webdriverio?

e.g.

`expect(browser).to.have.selector(.css-selector)`

what I gather from the docs is that the first part should actually be a selector. Is it possible to assert a selector on the whole page? If not, can this be supported?

**Comment by christian-bromann** [comment]
> a selector on the whole page?

Yes, check out https://www.npmjs.com/package/chai-webdriverio

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
