### ISSUE TITLE
If the browser crashes during initialization, WDIO does not attempt to recover

### ISSUE THREAD

**Issue by kashinross** [webdriverio/webdriverio#2568]
## The problem
If the browser (tested in Chrome and Firefox) crashes during initialization, the error `session not created exception` (chrome) or `Failed to decode response from marionette` (Firefox)  is thrown. However, once this error is thrown there is no way to handle the error without WDIO returning with exit code 1. I have found the line where `reject()` is called with the error and commenting the line out allows WDIO to recover in this situation. https://github.com/webdriverio/webdriverio/blob/master/lib/utils/RequestHandler.js#L250

## Environment

* WebdriverIO version: 4.10.1
* Node.js version: 8.6.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): WDIO Testrunner - Synchronous

## Details
This is an issue for me because I intermittently see this failure happening in our CI system. Chrome crashes for whatever reason before the 

## Steps To Reproduce Issue
1. Run a spec file
2. Close the browser immediately after it opens 

Expected: An error for `session not created exception` should be thrown and the browser should attempt to reload.

Actual: An error for `session not created exception` is thrown and the WDIO process exits with exit code 1.

Is there any reason the original `reject()` should not be removed or replaced with something else that will attempt to retry on failure?

**Comment by christian-bromann** [comment]
Hey @kashinross,
thanks for raising the issue. Retrying to load a browser would not be the responsibility of WebdriverIO. If the browser driver is not able to start the browser, WebdriverIO is not able to detect this. What WebdriverIO could do is just to retry creating the session if it fails no matter what reason. Feel free to open a discussion in our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). Thanks!

**Comment by kashinross** [comment]
@christian-bromann commenting this line out will cause the browser to reopen https://github.com/webdriverio/webdriverio/blob/master/lib/utils/RequestHandler.js#L250

**Comment by christian-bromann** [comment]
@kashinross feel free to provide a PR with a fix that checks if the browser crashes
