### ISSUE TITLE
How can I replace "timeout" error messages with something more descriptive?

### ISSUE THREAD

**Issue by parris** [webdriverio/webdriverio#2569]
## The problem

Every message tends to look like a timeout error even if the actual error is that a certain selector never showed up on the page.

## Environment

* WebdriverIO version:
* Node.js version:
* Standalone mode and browserstack
* Synchronous tests
* Mocha framework

## Details

Sooo often when there is an error, the test runner will say something like: 
```
1) my suite will have a passing test:
Timeout of 30000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.
```

However, what would be useful is if the runner said something like:

```
1) my suite will have a passing test:
waitForExist('someId') timed out in 30000ms. 
```

Every test failure tends to look like a timeout, and it is hard to figure out which step in the process timed out. Am I missing some piece of configuration or some error reporter that may give me more details like this?

**Comment by christian-bromann** [comment]
Feel free to propose a PR with a patch for this. Afaik the browser instance has a command list where it tracks the latest running commands. We could leverage from that information.

**Comment by parris** [comment]
@christian-bromann thanks for the quick response. I was digging through the code a bit and it looks like the error messages do exist they just aren't really showing up. For instance: https://github.com/webdriverio/webdriverio/blob/85f957ece25c228ec273b9c1447e49f9f622ae54/lib/commands/waitForExist.js#L50 . Is there some configuration option to enable to make those sorts of errors be raised in the console?

**Comment by christian-bromann** [comment]
@parris this is a different error message. Your timeout is thrown by the test framework because your test contains to much commands and exceeds a limit of 30 seconds. You should increase your timeout in the mochaOpts or make smaller tests with less commands.

**Comment by parris** [comment]
Ahh makes sense - I think this highlights the interplay between different timeouts. I'm formulating possible solutions to this.

Here are some scenarios:

```
Test 1 starts with a 30s timeout
  waitFor command issued also with a 30s timeout, it never finds what it is waiting for

> Your error message is likely to be, "Timeout of 30000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves."
```

```
Test 2 starts with a 30s timeout
   waitFor command issued with a 5s timeout, it never finds what it's looking for

> You're likely to get an error for the waitsFor
```

```
Test 3 starts with a 30s timeout
  a few waitFor commands issued, the last times out after the 30s timeout.

> Your error message is likely to be, "Timeout of 30000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves."
```

I guess test #3 is a variant of test #1.

Hmm question: is it useful to state what the last command issued was for a test timeout? Sometimes this is going to be a red herring.

**Comment by abjerstedt** [comment]
@parris I recommend that you up your framework timeout to something more along the lines of 5,10,30 minutes versus 30 seconds. 

This will allow you the flexibility of using browser.debug(), and you should never actually hit a framework timeout unless you somehow encounter an infinite recursion or you made FAR too long of a test.

In my experience its also better to use selenium's implictWait versus explictly calling the waitfor functions.

**Comment by parris** [comment]
I think this is resolved (at least for me). I think this was mostly a problem with my timeouts all being identical.

**Comment by stuartcrobinson** [comment]
It would be nice if timeout messages indicated what step timed out.

**Comment by cg-tester** [comment]
Hello, everyone, How can I fix protocolTimout error?
I increased protocolTimeout value in config file, but no effect.
