### ISSUE TITLE
browser.url is hanging on chrome 64 when transition to a page hash

### ISSUE THREAD

**Issue by jhoguet** [webdriverio/webdriverio#2575]
## The problem

I am unable to use `browser.url()` to go to a hash of the current page. Webdriver.io seems to get stuck. Reverting back to chrome 43 resolves the issue. 

## Environment

* WebdriverIO version: 4.10.1
* Node.js version: v7.10.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Standalone mode
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Details

Recently we noticed our tests started blocking. They would navigate to the page we requested, but the promise would not resolve or reject. We isolated this to when we were using `browser.url()` to go to a hash url. 

Here we can see it getting to the page we requested

![image](https://user-images.githubusercontent.com/1234146/35633806-28ddab0e-0678-11e8-9843-fece73d1c599.png)

and the webdriverio logs 
```
[11:15:35]  COMMAND	POST 	 "/session/e00594537a51dcfd2c610cdad8f89d8c/url"
[11:15:35]  DATA		{"url":"https://en.wikipedia.org/wiki/Cat"}
[11:15:37]  COMMAND	POST 	 "/session/e00594537a51dcfd2c610cdad8f89d8c/url"
[11:15:37]  DATA		{"url":"https://en.wikipedia.org/wiki/Cat#Taxonomy_and_evolution"}
```
and it hangs here indefinitely (until our test runner timesout) 

This issue is happening on the latest version of chrome (64) but does not happen on the previous version of chrome (63). 

## Link to Selenium/WebdriverIO logs

https://gist.github.com/jhoguet/a3a93d3ce92eebb3b980ce78e7dc01f5

Here is a link to the diff (https://www.diffchecker.com/rzaK4Gcu). 

## Code To Reproduce Issue [ Good To Have ]

```js
const webdriverio = require('webdriverio');

webdriverio.remote({
        desiredCapabilities: { browserName: "chrome" },
        host: 'localhost',
        port: 9515,
        path: '/',
        logLevel: process.env.LOG_LEVEL || 'silent',
        coloredLogs: true
    })
    .init()
    .url('https://en.wikipedia.org/wiki/Cat')
    .url('https://en.wikipedia.org/wiki/Cat#Taxonomy_and_evolution')
    .then(() => console.log('resolved'))
    .catch(err => console.log('rejected', err))
```

Please let me know if there is any way I can help further narrow this down.

**Comment by christian-bromann** [comment]
@jhoguet I had no issues with this using latest Chrome. Is there a specific reason why you need to use Chrome v43? Are people even use that version anymore? Note that these kind of issues are not WebdriverIO related and might be a problem in Chrome or Chromedriver.

**Comment by jhoguet** [comment]
@christian-bromann Thanks for the response. 

43 was a typo, I am having the issue with latest, 64. 

What are you using for chromedriver? Was it local or through something like sauce labs? Was it the mac build?

I am having this issue on all 3 workstations I have tried it on. 

Based on the diff I provided, I agree that this probably isn't webdriver.io, but the diff doesn't mean a lot to me. Where should I go next, chrome or chromedriver?

![image](https://user-images.githubusercontent.com/1234146/35643248-bb9c155a-0693-11e8-8a16-4c056e0448fd.png)

Notice that on chrome 63 (left) it gets a dev tools response, and on 64 (right) nothing even happens (until I kill the webdriver process).

**Comment by christian-bromann** [comment]
@jhoguet this would be definitely a ChromeDriver issue

> What are you using for chromedriver? Was it local or through something like sauce labs? Was it the mac build?

It was a local Chrome 64 on mac using ChromeDriver 2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2)

**Comment by jhoguet** [comment]
thanks for that info, reverting back to ChromeDriver 2.33.506106 also works for me... I'll get something logged in chromedriver - Many thanks for your help!

**Comment by artemv** [comment]
Could be caused by this Chromedriver [issue](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2251&q=hash&colspec=ID%20Status%20Pri%20Owner%20Summary).

**Comment by Windso** [comment]
I am also having this problem.

**Comment by webOS101** [comment]
According to https://bugs.chromium.org/p/chromedriver/issues/detail?id=2239 this should be fixed in Chrome 65.

**Comment by arenacheck** [comment]
I have the same problem. Very strange :( This plain js workaround do the trick for me!

          client.execute(() => {

                  location.href = window.location.href + '#trends-overallRating';
                  location.reload()

          })
