### ISSUE TITLE
Facing issue with the page object model using webdriverio

### ISSUE THREAD

**Issue by sumeetp4** [webdriverio/webdriverio#2577]
I have created a sample calculator test to add numbers on calculator app in my Android device.
I have followed the pageobject example available in webdriverio.

My app is getting launched and the test is passed but no actions are being performed

## Environment

* WebdriverIO version: 4.10.1
* Node.js version: 9.4.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Standalone
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Here is my CalcTest.js**

var webdriverio = require('webdriverio');
var expect = require('chai').expect;
var CalcMainPage = require('./PageObject/CalculatorMain.page');
var config = require('./helpers/desiredCapabilities').options;
var client = webdriverio.remote(config);

describe('Calculator Test', function () {
	 before(function () {
	        this.timeout(50000);
			console.log("Inside before method, launching application...")
	        return client.init();
	    });
	
	
    it('Adding 2 numbers', function () { 
    	CalcMainPage.clickDigit4;
    	CalcMainPage.clickDigit_2;
    	CalcMainPage.clickAdd;
    	CalcMainPage.clickDigit_3;
    	CalcMainPage.clickEqual;
    });
});
        

**Here is my CalcMainPage.page.js**

var CalcPage = Object.create({
    /**
     * define elements
     */
    addButton: { get: function () { 
    	return $('#com.google.android.calculator:id/op_add'); 
    	} },
    equals: { get: function () { return $('#com.google.android.calculator:id/eq'); } },
    multiplication: { get: function () { return $('#com.google.android.calculator:id/op_mul'); }},
    digit_3: { get: function () { return $('#com.google.android.calculator:id/digit_3'); } },
    digit_4: { get: function () { return $('#com.google.android.calculator:id/digit_4'); } },
    digit_2: { get: function () { return $('#com.google.android.calculator:id/digit_2'); } },

    /**
     * define or overwrite page methods
     */
    clickAdd: { value: function() {
        this.addButton.click();
    } }
    ,
    clickEqual: { value: function(){
    	equals.click();
    }}
    ,
    clickDigit_3 : {value: function(){
    	this.digit_3.click();
    }}
    ,
    clickDigit4 : {value: function(){
    	this.digit_4.click();
    }}
    ,
    clickDigit_2 : {value: function(){
    	this.digit_2.click();
    }}
});

module.exports = CalcPage;

**Comment by sumeetp4** [comment]
**Here is my package.json**

{
  "name": "appiumnode",
  "version": "1.0.0",
  "description": "Demo project",
  "dependencies": {
    "appium-uiautomator2-driver": "^1.1.0",
    "chai": "^4.1.2",
    "chai-as-promised": "^7.1.1",
    "mocha": "^5.0.0",
    "wd": "^1.5.0",
    "wdio-appium-service": "^0.2.3",
    "webdriverio": "^4.10.1"
  },
  "devDependencies": {},
  "scripts": {
    "CalculatorTest": "mocha CalcTest.js"
  },
  "author": "Sumeet",
  "license": "ISC"
}

**Comment by christian-bromann** [comment]
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
