### ISSUE TITLE
How do I use touchAction here!

### ISSUE THREAD

**Issue by sumeetp4** [webdriverio/webdriverio#2578]
## The problem

I'm trying to tap on a element in my calculator app in Android.
I am using webdriverio here. Test is passed but tap does not work!!!

## Environment

* WebdriverIO version:4.10.1
* Node.js version:9.4.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):Standalone
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Details

There are no examples available for touchAction, how do I use your functions in lib folder!!!

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]

**Here is my test file**

var webdriverio = require('webdriverio');
var expect = require('chai').expect;
var config = require('./helpers/desiredCapabilities').options;
var client = webdriverio.remote(config);

describe('Calculator Test', function () {
	 before(function () {
	        this.timeout(50000);
			console.log("Inside before method, launching application...")
	        return client.init();
	    });
	
	
    it('Adding 2 numbers', function () { 
    	client.touchAction('com.google.android.calculator:id/digit_4', 'tap');
    	client.touchAction('com.google.android.calculator:id/digit_2', 'tap');
    });
});
    
Please help

**Comment by christian-bromann** [comment]
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
