### ISSUE TITLE
Chrome 64: browser.url("old/path#new-hash") gets stuck if only hash part is changed

### ISSUE THREAD

**Issue by artemv** [webdriverio/webdriverio#2579]
## The problem
This code:
```
browser.url("my/path")
browser.url("my/path#new-hash")
```
on fresh Chrome 64 gets stuck on second line until runner times out with message like `Timeout of 300000ms exceeded`

## Environment

* WebdriverIO version: 4.10.1
* Node.js version: any (tried on 7.0.0)
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): -

## Details

This is similar to https://github.com/GoogleChrome/puppeteer/issues/257#issuecomment-355674062
The workaround I came to is to use JS navigation instead of browser.url in case only hash changes: `browser.execute((newHash) => location.hash = newHash)` 

## Link to Selenium/WebdriverIO logs
```
Timeout of 300000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.
```
I'll make a logs link a bit later.

## Code To Reproduce Issue [ Good To Have ]

See [## The problem] section.

**Comment by artemv** [comment]
@christian-bromann let me know if workaround (see Details) is worth including to browser.url code, or this just needs documenting - I'm up to creating PR for either.

**Comment by christian-bromann** [comment]
@artemv let's add this to the url command documentation

**Comment by artemv** [comment]
@christian-bromann I'm not sure re docs now because this doesn't reproduce with Chromedriver 2.33 - so it could be Chromedriver 2.34+ bug ([this](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2251&q=hash&colspec=ID%20Status%20Pri%20Owner%20Summary) one?) visible only on Chrome 64+.

**Comment by artemv** [comment]
as per https://bugs.chromium.org/p/chromedriver/issues/detail?id=2239 this will be fixed in Chrome v65

**Comment by dirwin517** [comment]
Anyone looking for a work around till its fixed in Chrome 65

the work around we've used successfully so far is 

      browser.url('data;');

before any browser.url() calls you may do
its kind of sucky, but it does the job


      browser.url('data;');
      browser.url(`${theUrlIWantedToGoTo}`);

**Comment by christian-bromann** [comment]
Thanks for sharing @dirwin517
