### ISSUE TITLE
Headless mode isn't working in Firefox

### ISSUE THREAD

**Issue by WarleyGabriel** [webdriverio/webdriverio#2581]
## The problem

When I use firefoxProfile for install the extension in browser, the headless mode isn't working. 
Together with parameters, the option headless isn't env.
I tried [gitter](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge), but without success.

## Environment

* WebdriverIO version: 4.10.1
* Node.js version: 5.6.0
* WebdriverIO Testrunner

## Details

If I use the firefoxProfile.
````
firefoxProfile: {
        extensions: ['Extension.xpi']
    }
````

The driver is created without headless mode.
````
 {"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,
"handlesAlerts":true,"rotatable":true,"maxInstances":1,
"browserName":"firefox","moz:firefoxOptions":{"profile":"[base64] 218368 bytes"},
"zal:recordVideo":true,"firefox_profile":"[base64] 218368 bytes",
"loggingPrefs":{"browser":"ALL","driver":"ALL"},"_":"1 more keys: [\"requestOrigins\"]"}}
````

If I comment the firefoxProfile.
The driver is created with headless mode.
````
{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,
"handlesAlerts":true,"rotatable":true,"maxInstances":1,"browserName":"firefox",
"moz:firefoxOptions":{"args":["-headless"]},"zal:recordVideo":false,
"loggingPrefs":{"browser":"ALL","driver":"ALL"},
"requestOrigins":{"url":"http://webdriver.io","version":"4.10.1","name":"webdriverio"}}}
````

## Code To Reproduce Issue [ Good To Have ]
It's necessary use firefoxProfile.
````
{
        maxInstances: 1,
        browserName: 'firefox',
        "moz:firefoxOptions":{
            "args":["-headless"]
        },
        "zal:recordVideo": false
}
````

**Comment by christian-bromann** [comment]
Hey @WarleyGabriel , sorry this is not a WebdriverIO issue. Please raise an issue in the [geckodriver](https://github.com/mozilla/geckodriver) project.

**Comment by WarleyGabriel** [comment]
Oh, sorry.
I did [1155](https://github.com/mozilla/geckodriver/issues/1155).
Thanks!

**Comment by christian-bromann** [comment]
Thanks @WarleyGabriel
