### ISSUE TITLE
How to exit a debug session is not ducumented

### ISSUE THREAD

**Issue by harryi3t** [webdriverio/webdriverio#2585]
## The problem

Once the users land in the REPL after using `browser.debug`, it's not mentioned in the docs that how should the user exit the debug session and continue the normal flow

Typing `.exit` in the terminal does this and this fact should be documented

**Comment by christian-bromann** [comment]
When you enter the debug mode it literally says:

```
[10:40:04]  DEBUG       Queue has stopped!
[10:40:04]  DEBUG       You can now go into the browser or use the command line as REPL
[10:40:04]  DEBUG       (To exit, press ^C again or type .exit)

>
```

I was thinking that this is enough info. If you disagree feel free to propose a PR.

**Comment by livemixlove** [comment]
I think it could still be added to the docs.  This is now the second result on google and helped me figure it out.  I had missed it being printing on the console.

**Comment by christian-bromann** [comment]
> I think it could still be added to the docs.

@livemixlove would you mind proposing a change where you have found it earlier?
