### ISSUE TITLE
Mix of remote/multiremote tests

### ISSUE THREAD

**Issue by andresmatasuarez** [webdriverio/webdriverio#2587]
I am adding E2E tests for all the critical parts of the app I'm working on, using `wdio` test runner. The tool is superb, so I want to begin this post with a big thank you to all of you who contribute to this project.

Now, the issue: I need to test the messaging part. The app has a built-in messenger for users to send and receive messages while navigating the app. I read about `multiremote` and I know that's what I need to do to test a live chat between two or more users.

The thing is, I couldn't find a way to specify that ONLY SOME of my tests use the `multiremote` options/capabilities, leaving the rest of them as single browser ones. I have tests for everything else and I have been doing well using just a single browser for them. Now I want to test sending/receiving messages between multiple users and I dont want to make ALL the tests use two or more browsers, because that's quite likely going to decrease performance dramatically and it simply doesnt make sense.

Maybe what I need to do is using standalone webdriver for those tests and keep using the runner for the rest of them. But that means I wont be able to take advantage of the facilities that using the runner bring to the table (I would need to init/end the multiremote browser, use async commands, etc)

Maybe Im missing something, but do you have any idea on this?

**Comment by christian-bromann** [comment]
> but do you have any idea on this?

Yes, I recommend to have an extra wdio.conf for your multiremote tests only and run these as last step in your tests, meaning:

1. run ESLint checks, if pass then
2. run Unit tests, if pass then
3. run WDIO single browser tests, if pass then
4. run WDIO multiremote test

Let me know if you have further question.

**Comment by andresmatasuarez** [comment]
Thanks for the answer! Cool, that totally works for me.

It has some disadvantages though:
   1) In my specific case, I had 3 wdio.confs: one for running/reporting on jenkins, one for running on saucelabs and one for doing everything locally. For each of them, I had to add a *.multiremote version, which added the multiremote capabilities to each. So i ended up having 6 config files.

  2) Lets suppose an app that has hundreds of e2e suites (not unreasonable at all). Some of them are single-browser ones, some of them use two browsers, some of them use three, some maybe four, etc. The thing is that that for each test that presents a new combination of browser quantities I need to write a multiremote config file.

  3) A similar idea goes if I have to test multiple combinations of browser capabilities. For example, the same test HAVE to pass using two chromes, a chrome and a firefox, two firefoxes, a firefox a chrome and a opera, etc etc etc. I would end up having dozens of specific config files, it just doesn't scale.

Again, the solution you propose does the trick for me, because I dont have much tests and its a relatively small app still. But as small app as it is, I ended up having 6 config files.

**Comment by christian-bromann** [comment]
> So i ended up having 6 config files.

You could set the environment you running your tests in as environment variable and change the wdio.conf dependning on what is set, e.g.

```sh
$ CI=1 wdio wdio.conf.js # for jenkins
$ CI=1 SAUCE=1 wdio.wdio.conf.js # for jenkins using saucelabs
# ...
```

> The thing is that that for each test that presents a new combination of browser quantities I need to write a multiremote config file

I guess, you could just start all browser for all multiremote tests and only use the necessary ones but that might cause delays when you start the session and is a waste of capabilities. What would you suggest instead? I can't think of anything that would allow to simplify that.

> it just doesn't scale.

Do you really need to test on all combinations?
