### ISSUE TITLE
Include a suite inside another suite

### ISSUE THREAD

**Issue by mariosimao** [webdriverio/webdriverio#2590]
I am a beginner WebdriverIO, so I think that is more questions than an issues.

### Question 1
It is possible to to add a suite inside another suite?

### Example
I have suite1 (with the specs spec-a, spec-b and spec-c) and suite2 (with spec-d, spec-e) and I want to create the suite3 with (suite1, suite2, spec-f and spec-g).

I was thinking in something like:

```javascript
// wdio.conf.js
...
    suites: {
        suite1: [
            '.test/specs/spec-a.js',
            '.test/specs/spec-b.js',
            '.test/specs/spec-c.js'
        ],
        suite2: [
            '.test/specs/spec-d.js',
            '.test/specs/spec-e.js'
        ],
        suite3: [
            suite1,
            suite2,
            '.test/specs/spec-f.js',
            '.test/specs/spec-g.js'
        ]
    },
...
```

### Question 2
Are test suites synchronous? As in the example above, in the suite1, the test orders will be the same as the following list?
1. spec-a
2. spec-b
3. spec-c

**Comment by christian-bromann** [comment]
> Are test suites synchronous? As in the example above, in the suite1, the test orders will be the same as the following list?

yes

> I have suite1 (with the specs spec-a, spec-b and spec-c) and suite2 (with spec-d, spec-e) and I want to create the suite3 with (suite1, suite2, spec-f and spec-g).

Just define them as variables before and concat them in your config like
```js
const suite1 = [
    '.test/specs/spec-a.js',
    '.test/specs/spec-b.js',
    '.test/specs/spec-c.js'
]
const suite2 = [
    '.test/specs/spec-d.js',
    '.test/specs/spec-e.js'
]
// wdio.conf.js
...
    suites: {
        suite1: suite1,
        suite2: suite2,
        suite3: [...suite1, suite2]
    },
...
```
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
