### ISSUE TITLE
Cannot read property 'setValue' of undefined

### ISSUE THREAD

**Issue by kevinsv** [webdriverio/webdriverio#2592]
## The problem

I get the following error using Page Object Model: 
**Cannot read property 'setValue' of undefined
TypeError: Cannot read property 'setValue' of undefined**

## Environment

* WebdriverIO version: 4.10.1
* Node.js version: 8.9.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio test runner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable):
        "wdio-browserstack-service": "0.1.14",
        "wdio-cucumber-framework": "~0.3.0",
        "wdio-cucumber-reporter": "0.0.2",
        "wdio-dot-reporter": "0.0.9",
        "wdio-selenium-standalone-service": "~0.0.9",
        "wdio-spec-reporter": "~0.0.5",
        "wdio-teamcity-reporter": "^1.1.0",
        "webdriverio": "4.10.1"

## Details

I am using the Page Model Pattern describe in http://webdriver.io/guide/testrunner/pageobjects.html but I get the error Cannot read property 'setValue' of undefined.

_**This is my Page Object class:**_

```
export default class basePage {
	constructor() {
		this.title = 'Login';
	}

	open() {
	   let base = browser.options.vrmUrl;
       browser.url(base);
	}
}
```

**_And this is my loginPage class:_** 

```
// login.page.js
import basePage from './basePage';

class loginPage extends basePage {

    get username_txt()  { return browser.element('#username'); }
    get password_txt()  { return browser.element('#password'); }
    get submit_btn()      { return browser.element('#submitButton'); }

    open() {
        super.open('Login');
    }

    login() {
        this.username_txt.setValue('riskmanager@complianceasaservice.net');
        this.password_txt.setValue('vrmP4ssw0rd');
        this.submit_btn.click();
    }

}

export default new loginPage();
```

setValue method works if I do:

```
  login() {
       var elem = browser.element('#username');
       elem.setValue('Max Mustermann');
    }
```

but it doesn't work using get function to define the elements.

**Comment by christian-bromann** [comment]
Code looks fine to me. Did you try to debug your code? E.g. check what `this` is in the login method? This is not a WebdriverIO issue. For questions like this please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).

**Comment by Jyoti2190-Test** [comment]
Hi I am facing the same issue, were you able to fix it ?
