### ISSUE TITLE
`waitUntil` breaks `this` context

### ISSUE THREAD

**Issue by jasonk** [webdriverio/webdriverio#2594]
## The problem

I've been encountering strange issues with a test suite that I finally tracked down to differences in the way that `execute` works when you call it from inside `waitUntil` vs when you call it from outside.  When called from inside `waitUntil` it seems that `execute` returns it's promise instead of the resolved value of the promise, and also that the `this` context is lost for code running inside the `waitUntil`.

## Environment

* WebdriverIO version: v4.10.2
* Node.js version: v8.9.3
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable):

## Details

I'm not sure if this is the way it's intended to work or not (if it is then you should probably at least add a note about it to the `waitUntil` docs).

Basically I was trying to use `addCommand` to define a a function that waited for a variable to become defined and then returned it's value.

```
browser.addCommand( 'getVar', function( name ) {
  const code = `return ${name};`;
  this.waitUntil( function() { return typeof this.execute( code ).value !== 'undefined'; } );
  return this.execute( code ).value;
} );
```
What I found is that when I log the return value of `this.execute()` inside the `waitUntil`, it always logs `{ state: 'pending' }`, even though when I set the logLevel to verbose I can see that it actually got the right value back from Selenium.  Further, when I log `this` inside the `waitUntil` callback, it *also* always logs `{ state: 'pending' }`, so it appears that the `this` context of the waitUntil callback is set to the promise rather than to the browser instance.

What *does* work is if you use `browser.execute` instead of `this.execute` inside the `waitUntil` callback.  The `waitUntil` docs actually show using `browser.execute` in the example code, but since the documentation for `addCommand` has examples with both, it took me a while to realize that in this one instance they aren't interchangeable.

If nothing else, hopefully this report will help people who are trying to Google for this problem and run across issues that seem to be the same problem but without any real resolution (such as: #1359 #1377 #1407)

**Comment by mherodev** [comment]
Ran across this issue today, but just assumed `browser.execute` always returned an object and that I misremembered how it worked, hahaha

I'm also running into other funkiness that may be `waitUntil`-related:

When calling `browser.execute()` or `browser.getAttribute('body', 'example-attribute')` inside `waitUntil` I am occasionally seeing a `Stale Element Reference Exception`, which shouldn't be possible based on the syntax (`execute` doesn't use an element,  and `getAttribute` is being passed a string).

It's such a rare, intermittent error that I'm not quite sure how I'd even create a reproducible example around it, the best I have is what my console gave me:

```
stale element reference: element is not attached to the page document
running Chrome on OS X 10.10
Check out job at *snip*
Error: An element command failed because the referenced element is no longer attached to the DOM.
    at execute(<Function>) - index.js:263:37
    at execute(<Function>) - index.js:263:37
    at elementIdDisplayed("0.11117520653210189-4") - isVisible.js:71:55
```

**Comment by mattc41190** [comment]
@jasonk does the code work if you refer to `browser` consistently rather than `this`?

**Comment by Gary-Osteen-Q2** [comment]
Try changing
function()
to
() =>

The change somehow magically passes in the this context.
```
browser.addCommand( 'getVar', function( name ) {
  const code = `return ${name};`;
  this.waitUntil(() => { return typeof this.execute( code ).value !== 'undefined'; } );
  return this.execute( code ).value;
} );
```

**Comment by Gary-Osteen-Q2** [comment]
@jasonk Have you tried the code I posted above?

**Comment by christian-bromann** [comment]
I can confirm that this issue does not exist anymore in v5. Closing.
