### ISSUE TITLE
Quite BaseReporter's test.err.stack Failure Output

### ISSUE THREAD

**Issue by emilyrohrbough** [webdriverio/webdriverio#2595]
## The problem
Overly bloated error output when utilizing reporters and custom chai assertions. On a test failure, I only want to view the chai assertion message. Instead I am seeing the chai assertion message, as well as a full stack trace, which in my instance repeats the error message.

#### Issue
![screen shot 2018-02-13 at 7 47 29 am](https://user-images.githubusercontent.com/14099737/36152924-36f336fe-1092-11e8-99f7-2372850ecde5.png)

#### Desirable
![screen shot 2018-02-13 at 7 47 37 am](https://user-images.githubusercontent.com/14099737/36152928-3bd5d7ee-1092-11e8-9e95-d027b7207e43.png)

## Environment

* WebdriverIO version: v4.9.11
* Node.js version: v8.4.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): wdio-mocha-framework (^0.5.11) & wdio-visual-regression-service (^0.8.0)

## Details

On a test failure, I only want to view the chai assertion message. Instead I am seeing the chai assertion message, as well as a full stack trace, which in my instance repeats the error message (see image above). It would be nice to have an option to quiet the `test.err.stack` failure output. 

I expect this would be an enhancement test reporters utilizing the BaseReporter directly, will automatically have access given their wdio configuration or reporters could utilize this option.

## Code That Reproduces The Issue [ Good To Have ]
[Here is the code](https://github.com/webdriverio/webdriverio/blob/master/lib/utils/BaseReporter.js#L221) producing the extraneous output.

**Comment by mjhenkes** [comment]
+1 This would help me out too, especially when there are a lot of failures.

**Comment by WillBrock** [comment]
Is this still and issue in v5? #3565 might help with this. If you still have issues please re-open this ticket.
