### ISSUE TITLE
Update browser.pause() documentation

### ISSUE THREAD

**Issue by Chaoste** [webdriverio/webdriverio#2597]
## The problem
I wanted to wait for a second before taking screenshots. I followed the documentation but I figured out that it's not working that way.

## Environment

* WebdriverIO version: 4.10.2 (Current master branch)

## Details

I just called `browser.pause(1000)` as suggested in the example. But after looking into the actual code I recognized that it returns a Promise and executed a timeout asynchronously. So I guess you could use async functions and call `await browser.pause(1000)` or you use it as a Promise and call `browser.pause(1000).then(...)`. The documentation should be updated regarding this functionality.

## Code To Reproduce Issue [ Good To Have ]

Current documentation:
```
it('should pause the execution', function () {
        var starttime = new Date().getTime();
        browser.pause(3000);
        var endtime = new Date().getTime();
        console.log(endtime - starttime); // outputs: 3000
    });
```

**Comment by christian-bromann** [comment]
@Chaoste as explained [here](http://webdriver.io/api.html#Examples)

> Each command documentation usually comes with an example that demonstrates the usage of it using WebdriverIO’s testrunner running its commands synchronously. If you run WebdriverIO in standalone mode you still can use all commands but need to make sure that the execution order is handled properly by chaining the commands and resolving the promise chain.

**Comment by Chaoste** [comment]
Thanks for the hint :)
But would you keep this example which just not working in any case as suggested.

**Comment by christian-bromann** [comment]
Not sure if I can follow. The pause command works as described in the example when running wdio testrunner in sync mode (which is the default). If you use WebdriverIO as standalone package or in async mode you need to use async/await or other ways to handle the promise behind it.

**Comment by Chaoste** [comment]
Ah I see! Sorry for the confusion - I wasn't aware of the two different modes because I always worked with one of them.

**Comment by christian-bromann** [comment]
There is more on this [here](http://webdriver.io/guide/getstarted/modes.html)
