### ISSUE TITLE
How do I perform touchAction from element to element rather than passing x and y

### ISSUE THREAD

**Issue by sumeetp4** [webdriverio/webdriverio#2599]
## The problem

I am trying yo scroll from an element to element. I am using webdriverio and appium
How do I scroll from an element to element rather than passing x and y as in like this example

// multi action using x y variables
        // moveTo location is relative from the starting coordinate
        browser.touchAction([
            { action: 'press', x: 20, y: 550 },
            { action: 'moveTo', x: 0, y: -500},
            'release'
        ])

## Environment

* WebdriverIO version: 4.10.1
* Node.js version: v9.4.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Standalone
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
How should someone respond to this without logs or any information about the browser environment?

**Comment by sumeetp4** [comment]
Well it's not an issue to report logs.
And there is no browser involved as in all your examples. I'm trying to automate an Android native application using Appium and webdriverio and I want to scroll from one element to another.
So going through examples of webdriverio I found the above mentioned code which takes x and y coordinate for press and moveTo
What I'm trying to ask here is there any other way to pass element rather than sending the x and y coordinates
I hope you understand what my query is

**Comment by christian-bromann** [comment]
> is there any other way to pass element rather than sending the x and y coordinates

Yes, you can also just pass in a selector like:
```js
    browser.touchAction({
        action: 'tap', x: 30, y:20, selector: '//UIAApplication[1]/UIAElement[2]'
    })
```
