### ISSUE TITLE
WebdriverIO tries to create a screenshot on cloud service timeout

### ISSUE THREAD

**Issue by erwinheitzman** [webdriverio/webdriverio#2601]
## The problem

When I run my WebdriverIO tests at Browserstack and they take longer then the timeout that is set in the mochaOpts => timeout.
Then WebdriverIO tries to create an screenshot on reject.
This fails, because the session has been stopped and this there's no ID for the screenshot command to use.
This results in the following two errors:
Failed to take screenshot on reject: 	 {"type":"NoSessionIdError","message":"A session id is required for this command but wasn't found in the response payload"}
Error: A session id is required for this command but wasn't found in the response payload
    at Object.wait (/apps/jenkins/workspace/grip_e2e_login_acc/node_modules/fibers/future.js:449:15)
    at Object.log (/apps/jenkins/workspace/grip_e2e_login_acc/node_modules/wdio-sync/build/index.js:283:31)
    at Object.afterTest (/apps/jenkins/workspace/grip_e2e_login_acc/wdio.conf.js:175:39)

________________

Timeout of 120000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.

## Environment

* WebdriverIO version: 4.10.2
* Node.js version: 8.9.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): wdio-selenium-standalone-service, wdio-mocha-framework

## Details

WebdriverIO tries to take a screenshot on timeout, this screenshot method should not be triggered on timeout in my opinion.

## Link to Selenium/WebdriverIO logs

Partial log: https://gist.github.com/erwinheitzman/861c1ac3cfef815fe2ea0caf64f98d4c

## Code To Reproduce Issue [ Good To Have ]

Run any test file/suite that takes longer then the set mochaOpts timeout

**Comment by AnnemarieD** [comment]
I got the same issue, when I run the tests (one set of several test files) on multiple instances, I get this error. If I reduce the number of instances to run the tests this issue doesn't seem to occur.

**Comment by christian-bromann** [comment]
This can have various reasons and is not necessarily to WebdriverIO. Since this issue has been hanging around for a long time without activity I will close it.
