### ISSUE TITLE
timeouts problem on browserstack

### ISSUE THREAD

**Issue by igorcherednyk** [webdriverio/webdriverio#2604]
## The problem

Tests are not waiting for the elements to appear after setting timeouts

## Environment

* WebdriverIO version: 4.10.2
* Node.js version: 9.3.0
* wdio testrunner

## Details

Tests are interacting with elements without waiting for the elements to be visible. 
I tried to set timeout with browser.timeouts('implicit', 10 * 1000) but it didn't help.

The working solution was to use waitUntil e.g
browser.waitUntil(() => page.testPageLabel.isVisible(), 2000);

## logs

`
Appium error: An unknown server-side error occurred while processing the command. Original error: Error while executing atom: Element is not currently visible and may not be manipulated (status: 11)
Error: An unknown server-side error occurred while processing the command.
at elementIdClick("5003")
`

## Code 

  before(_ => browser.timeouts('implicit', 5 * 1000));

  beforeEach(_ => browser.url('https://testpage.io'));

  it('navigation test', function () {

    page.menuButton.click();

    // browser.waitUntil(() => page.testMenuItem.isVisible(), 2000);

    page.testMenuItem.click();

    // browser.waitUntil(() => page.testPageLabel.isVisible(), 2000);

    expect(page.testPageLabel.getText()).to.be.equal('expected test');

  });

**Comment by christian-bromann** [comment]
Try:
```js
  beforeEach(_ => browser.url('https://testpage.io'));

  it('navigation test', function () {
    page.menuButton.click();
	page.testMenuItem.waitForVisible(10000);
    page.testMenuItem.click();
    page.testPageLabel.waitForVisible(10000);
    expect(page.testPageLabel.getText()).to.be.equal('expected test');
  });
```
If timeouts are not respected on the remote side there is nothing WebdriverIO can do about it. Please contact the browserstack support. I strongly recommend to __not__ use implicit waits and instead use commands like waitForVisible and other commands like this.
