### ISSUE TITLE
beforeTest failure in config not causing test to fail

### ISSUE THREAD

**Issue by mhardin** [webdriverio/webdriverio#2606]
## The problem

We have a beforeTest() method in our webdriverio config file.  We have some setup stuff we perform in here we want performed for all tests (does some reporting for tests, and other setup stuff).  We then have a test in a standalone JS file.  If an error happens in the config file's beforeTest() (e.g. `throw new Error()`), we see the error in the console, but the corresponding test still runs and shows as successfully completed.  I would expect the test to fail if an associated "setup" method fails. 

If we put the beforeTest() directly in the test file, the error seems to be handled appropriately, but we do not want to go this route as we need the beforeTest() to apply to _every_ test in our suite and do not want to have to remember to copy/paste code into every test file. 

## Environment

* WebdriverIO version: 4.10.2
* Node.js version: 8.9.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): test runner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):

**Comment by christian-bromann** [comment]
@mhardin this is intentional, all hooks don't cause the test to fail. Otherwise if some plugin is broken for some reason it would cause the whole test to fail even though that plugin just reports or does some house keeping things.

**Comment by mhardin** [comment]
@christian-bromann so how does one handle test setup in an abstracted fashion that will cause the test to fail?

**Comment by mhardin** [comment]
`Otherwise if some plugin is broken for some reason it would cause the whole test to fail even though that plugin just reports or does some house keeping things.` I figure one would have error handling around this to prevent this from causing the test to fail if that is not desired behavior.

**Comment by christian-bromann** [comment]
> so how does one handle required test setup in an abstracted fashion that will fail the test if it does not complete successfully?

What do you mean by that?

**Comment by mhardin** [comment]
@christian-bromann we have test setup we want to perform for every test in a large test suite.  The setup is the same for every test.  If this setup fails, its considered fatal as the test will not be able to continue.  So, we would like the test to fail and not attempt to run.  We want to be able to have this code in one place (e.g. in the beforeTest of the config file) and not have to copy this into every test file that we have.

How would you recommend doing this?

**Comment by christian-bromann** [comment]
You can do it this way and set a global variables that stores if the setup was successfully or not. You will need a check in front of each test being like
```js
describe('some test', () => {
    it('should be setup correctly', () => {
        expect(global.setupSuccessful).toBe(true)
    })

    // other tests
})
```
You need to set [`bail: true`](https://mochajs.org/#-b---bail) in your mochaOpts as well.

**Comment by christian-bromann** [comment]
You can also try this in your beforeTest hook:
```js
process.send({
  event: 'runner:end',
  failures: 1
})
process.exit(1)
```

> Could what we're asking for not be a feature request?

No, as I mentioned this is an intentional behavior which we can't change just like that.

**Comment by kunwardeep** [comment]
This would have been really useful :(.

**Comment by kunwardeep** [comment]
@mhardin Did you find a solution?

**Comment by cfoxcfox** [comment]
@christian-bromann 

> You can also try this in your beforeTest hook:
> 
> ```js
> process.send({
>   event: 'runner:end',
>   failures: 1
> })
> process.exit(1)
> ```

This solution would not work if the case is that the beforeTest error should fail the test but not the suite or whole process. It would be great if this failure can be handled, fail the test, and move on to the next. Is there a solution to that? This would be very useful.

**Comment by christian-bromann** [comment]
@cfoxcfox hooks are not designed to interfere with the test lifecycle. Also this issue is almost a year old and we had a major upgrade since then.

**Comment by rameshraja1988** [comment]
Hi @christian-bromann,

I can able to skip the **next** test-case using `beforeHook`:

```
    beforeHook(test, context) {
        if (this._forceSkip) {
            context.currentTest.pending = true;
            context.skip();
        }
    },
```

but the **problem** is `beforeHook` executed only if **suite** has `beforeEach`.

Also, I can't do the same thing in `beforeTest`, it is not skipping the next test-case!

Here is my question:
- Is there any way to execute the `beforeHook` even if  **suite** doesn't have `beforeEach`?
[OR]
-Is there any way to `skip` the test-case using `beforeTest`?

Thanks a lot for your help,
Ramesh

**Comment by mgrybyk** [comment]
@rameshraja1988 neither beforeHook nor beforeTest hooks are designed to skip tests. I suggest to look for a better solution to skip tests.

**Comment by rameshraja1988** [comment]
Okay :(
