### ISSUE TITLE
AddValue does not work correctly

### ISSUE THREAD

**Issue by trix0** [webdriverio/webdriverio#2608]
## The problem

addValue() does not add Value. It saves current state of input field, deletes everything from input field. Concatenates saved value with new value and writes it back to input field.

What should it do ?
Write a new value to input field after current value

**Comment by christian-bromann** [comment]
Not sure what you are describing here but addValue __adds__ a value to an input. If you want to clear the value before setting use setValue.

**Comment by trix0** [comment]
It does not. It deletes value and then inserts old value + new value.

**Comment by christian-bromann** [comment]
can you provide any logs or any proove?

**Comment by trix0** [comment]
Yeah, Give me sec tho. I need to record it. I ll give logs and code as well

**Comment by trix0** [comment]
https://youtu.be/vq41sTVmnFI?t=13s

[Code](https://gist.github.com/trix0/1f53db42509dafeffa32aed279e3a6c5)
[Log](https://gist.github.com/trix0/f6f21e7b83a85e0ce536ab33685da356)

**Comment by christian-bromann** [comment]
Can you point at which position in the video an logs you think the error happens? It is not up to WebdriverIO how the value actually gets populated to the app. Chances are that the automation driver isn't able to properly set the value. There is nothing much WebdriverIO can do about that.

**Comment by trix0** [comment]
Well what should happened is.
1."testName" is written
2."Test" is added after "testName"


What happened:
1."testName" is written
2.Value of input is cleared.
3. "testNameTest" is written 


Do you see difference ? 



Log
`2018-02-22 11:58:05:012 - info: [debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:setText","params":{"elementId":"4","text":"Test","replace":false}}
2018-02-22 11:58:05:020 - info: [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"4","text":"Test","replace":false}}
2018-02-22 11:58:05:020 - info: [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
2018-02-22 11:58:05:020 - info: [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: setText
2018-02-22 11:58:05:020 - info: [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using element passed in: 4
2018-02-22 11:58:05:062 - info: [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Attempting to clear using UiObject.clearText().
2018-02-22 11:58:08:449 - info: [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Sending plain text to element: testNameTest`

**Comment by christian-bromann** [comment]
> Do you see difference ?

Yeah but it after all did what it suppose to do right?

**Comment by trix0** [comment]
Well, not really but if you cant do nothing about it, Its okey I am already writing method to go over that without using it.

**Comment by pmerwin** [comment]
@trix0 

I was having the same issue, our React pages do this, so I use this to clear the input filed.

Page.prototype.clearTextFieldForReact = function (textFieldSelector) {
    browser.waitForExist(textFieldSelector);
    browser.click(textFieldSelector);
    let x = browser.getValue(textFieldSelector);
    for (let i = 0; i < x.length; i++) {
        browser.setValue(textFieldSelector, '\uE003').pause(100);
    }
};

**Comment by trix0** [comment]
Great solution. I had older version and setValue was not implemented there. I used brute force/ regex validation and recrusion to do it. Thx for ur solution

**Comment by trix0** [comment]
I just feel like its useless to have a function that just combines already available functions in main project and confuses other ppl with its functionality. Implement it correctly or dont implement it at all.

**Comment by christian-bromann** [comment]
> Implement it correctly or dont implement it at all.

You can't blame WebdriverIO for that. It is an issue with Appium.

**Comment by trix0** [comment]
Yes, Christian Its my bad I should have posted to Appium I got it from your previous comment already :) You are all good at least its documented here how to solve this . I ll write issue to appium tomorrow :)
