### ISSUE TITLE
Do we need to pass capabilities when running with 

### ISSUE THREAD

**Issue by Github248** [webdriverio/webdriverio#2611]
Hi Christian, We're using WebdriverIO with Node JS for our automation testing. Trying to run our tests on Saucelabs browsers and devices. So, Ive used Multi-Configuration Jenkins Project to do the set up. Do I need to explicitly pass the capabilities from the project when I use Configuration Matrix->Add Axis->Saucelabs Webdriver Tests/Saucelabs Appium Tests  ? How do I do this ? Do I need to dynamically read Jenkins Global variables and pass to saucelabs?

My initial set up was to access Saucelabs from local machine and passing the capabilities when running on Sauce otherwise default to run on Stand alone server and use local Chrome browser. I'm passing the browser type from the command line as, capability=BROWSERTYPE npm run byLargeView . Setup the logic in the project to map the BROWSERTYPE capabilities from saucelabs configurator and pass. if no capability is sent it defaults to Chrome. 

Can you please suggest what's the best way to run tests on multiple browsers and devices by using the same workspace on jenkins and create Allure Report ? I'm looking for better ideas. Since, I'm running into couple of issues with the Multi-Configuration Jenkins Project and adding Matrix from Saucelabs.

1. Passing the Dynamic capability conguration
2. The tests are running fine for the first selection from the grid selection and failing to run from second one onwards. 
The Allure report is created fine after the first build but it's being supdated as NAN with the second build failure result

The reason for Second build failure is it's trying to install Phantom js as it's not available in my PATH. I've specified my browsername as 'Browser' not phantom js. Not sure why's my job looking for Phantom js for IPAD 
Please see the log below.

05:43:10 > phantomjs-prebuilt@2.1.16 install /home/jenkins/workspace/IntegrationSL/SELENIUM_DRIVER/iPad_Simulatorportraitipad11_1_/node_modules/phantomjs-prebuilt
05:43:10 > node install.js
05:43:10 
05:43:11 PhantomJS not found on PATH
05:43:11 Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
05:43:11 Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
05:43:11 Receiving...
05:43:17 
05:43:17 Received 22866K total.
05:43:17 Extracting tar contents (via spawned process)
05:43:17 Error extracting archive
05:43:17 Phantom installation failed { Error: Command failed: tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
05:43:17 tar (child): bzip2: Cannot exec: No such file or directory
05:43:17 tar (child): Error is not recoverable: exiting now
05:43:17 tar: Child returned status 2
05:43:17 tar: Error is not recoverable: exiting now
05:43:17 
05:43:17     at ChildProcess.exithandler (child_process.js:275:12)
05:43:17     at emitTwo (events.js:126:13)
05:43:17     at ChildProcess.emit (events.js:214:7)
05:43:17     at maybeClose (internal/child_process.js:925:16)
05:43:17     at Socket.stream.socket.on (internal/child_process.js:346:11)
05:43:17     at emitOne (events.js:116:13)
05:43:17     at Socket.emit (events.js:211:7)
05:43:17     at Pipe._handle.close [as _onclose] (net.js:554:12)
05:43:17   killed: false,
05:43:17   code: 2,

## Environment
Linux - Jenkins

* WebdriverIO version: 4.10.2
* Node.js version: 5.6.0
* Sauce Service

**Comment by christian-bromann** [comment]
> Do I need to explicitly pass the capabilities from the project when I use Configuration Matrix->Add Axis->Saucelabs Webdriver Tests/Saucelabs Appium Tests ?

I am not sure what you mean by this but you should have defined your capabilities in your wdio.conf.js

> Do I need to dynamically read Jenkins Global variables and pass to saucelabs?

Yes, store your saucelabs credentials safely in Jenkins and define user and key in your wdio.conf.js like this:
```js
user: process.env.SAUCE_USERNAME,
key: process.env.SAUCE_ACCESS_KEY,
```

> Can you please suggest what's the best way to run tests on multiple browsers and devices by using the same workspace on jenkins

The wdio.conf.js is a normal JavaScript file so you can define your capabilities based on what you find in the environment. You can have an environment variable like `browserset` that defines e.g. `setA` or `setB` and in your wdio.conf you check what environment variable was passed in and define the capabilities based on that.

> Not sure why's my job looking for Phantom js for IPAD

Not sure either, that does not look like WebdriverIO is doing that

Please reach out to our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have further questions.
