### ISSUE TITLE
wdio config errors out with a "Error: ENOENT: no such file or directory" error

### ISSUE THREAD

**Issue by benjaminapetersen** [webdriverio/webdriverio#2612]
## The problem

```bash 
yarn add webdriver.io
$(npm bin)/wdio config 
```
Will then ask the 9 questions, start to install packages, then error out with:

```bash
Installing wdio packages:

Packages installed successfully, creating configuration file...
fs.js:663
  return binding.open(pathModule.toNamespacedPath(path),
                 ^

Error: ENOENT: no such file or directory, open '~/my-project/node_modules/webdriverio/build/lib/helpers/wdio.conf.ejs'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
    at renderConfigurationFile (~/my-project/node_modules/webdriverio/build/lib/cli.js:304:28)
    at ~/my-project/node_modules/webdriverio/build/lib/cli.js:294:17
    at ~/my-project/node_modules/npm-install-package/index.js:31:5
    at ChildProcess.exithandler (child_process.js:264:7)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
error Command failed with exit code 1.
```

## Environment

* WebdriverIO version: "webdriverio": "^4.10.2"
* Node.js version: v9.4.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): n/a
* if wdio testrunner, running synchronous or asynchronous tests: n/a
* Additional wdio packages used (if applicable): n/a

## Details

n/a

## Link to Selenium/WebdriverIO logs

n/a, above cli output is all that i have as it is an install error.

## Code To Reproduce Issue [ Good To Have ]

n/a, see above cli output

thanks!

**Comment by christian-bromann** [comment]
Can you zip the directory `~/my-project/node_modules/webdriverio` and attach it to this thread?

**Comment by benjaminapetersen** [comment]
Sure thing ~

[webdriverio.zip](https://github.com/webdriverio/webdriverio/files/1758922/webdriverio.zip)

**Comment by christian-bromann** [comment]
@benjaminapetersen looks like `node_modules/webdriverio/build/lib/helpers/wdio.conf.ejs` is available. So no idea why that error is thrown. Can you reproduce it and check why it is not finding it?

**Comment by benjaminapetersen** [comment]
Is a good Q.  I ended up just manually creating a config file to work around the problem...

**Comment by christian-bromann** [comment]
@benjaminapetersen people have raised this issue couple of times but I was never able to reproduce it so can you try to do it?

**Comment by benjaminapetersen** [comment]
I probably can. I hit the problem numerous times before creating this issue.  What would you find helpful for me to report back besides the above stack trace?

**Comment by christian-bromann** [comment]
@benjaminapetersen if you can reproduce it, it would be super helpful if you can check in `node_modules/webdriverio/build/lib/cli.js:304:28` why it can't find the file. Apparently it is there but the error is still thrown. Maybe we are looking in the wrong directory there.

**Comment by WillBrock** [comment]
I was able to reproduce this with npm 5.6.0 installed. Doing `yarn add webdriverio -D`. At this point all the webdriver files were there. Once it went through the all the steps and at the end it calls npmInstallPackage() which at that point the webdriver files would be gone. Updating npm to 5.7.1 fixed the issue. Although it might be good to have an option for using yarn or npm on the setup.

https://github.com/npm/npm/issues/17379#issuecomment-367924115

**Comment by aamorozov** [comment]
I'm experiencing the same issue with `yarn v. 1.5.1` with the exact same error log. Everything works when installing with `npm > 5.5.0`

**Comment by patthiel** [comment]
I just encountered the issue as well with `yarn v 1.5.1` and `npm v 5.6.0`. I think this commit in `npm` fixed it in verions > `npm 5.6.0`: https://github.com/npm/npm/commit/8279515903cfa3026cf7096189485cdf29f74a8f

**Comment by Flavien-Pensato** [comment]
I experience the same issue. It seems like `yarn wdio` removed every files folders in `node_modules/webdriverio/ ` ^^

**Comment by christian-bromann** [comment]
Hey,

we update the core architecture of WebdriverIO and with that a lot of implementation details that might make this issue obsolete. Please try with the v5 version of WebdriverIO and verify if this still occurs. If so please open a new issue and we will tackle it asap.

Thanks!
