### ISSUE TITLE
Launcher should accept config as json object

### ISSUE THREAD

**Issue by MS-elug** [webdriverio/webdriverio#2615]
## The problem

Webdriver Launcher should accept configuration file as a json object.

```javascript
const config= require('wdio.conf.js')).config;
const wdio = new Launcher(config, opts);
```

**Comment by christian-bromann** [comment]
Thanks for the suggestion, can you at least bake it with any arguments?

**Comment by christian-bromann** [comment]
Let's move convo to #2616
