### ISSUE TITLE
wdio-allure-framework results in allure report with steps from different TCs in a Scenario Outline scrambled together

### ISSUE THREAD

**Issue by osmolyar** [webdriverio/webdriverio#2619]
## The problem

The Gherkin steps for Scenario Outlines are completely scrambled in the Allure report resulting from the use of wdio-allure-reporter@0.3.2,, with steps from different test cases combined together into a numbered list and not ordered on display, e.g., see 'License Key test Invalid License Key FIles' in

http://172.16.4.109:64354/index.html#suites 

Also wdio-allure-reporter (0.3.2/latest) appears to use allure v1 (allure-js-commons@1.3.1) rather than allure2, which is the supported version - not sure whether this is related to the issue or not.

## Environment

* WebdriverIO version: 1.0.3
* Node.js version: 6.5.0
* Standalone
* wdio-cucumber-framework ^1.1.0"
*wdio-allure-reporter 0.3.2
allure-js-commons@1.3.1 (installed with wdio-allure-reporter)

## Details
wdio-allure-reporter (0.3.2/latest) appears to use allure v1 (allure-js-commons@1.3.1) rather than allure2, which is the supported version.

Possibly as a result, Gherkin steps for Scenario Outlines are completely scrambled in the Allure report, with steps from different test cases combined together into a numbered list and not ordered on display, e.g., see 'License Key test Invalid License Key FIles' in

http://172.16.4.109:64354/index.html#suites 

C:\selenium\qdtools\AUTF\selenium\webdriverio\jenkins\Cucumber1>npm install -g wdio-allure-reporter
C:\Program Files\nodejs
`-- wdio-allure-reporter@0.3.2
  +-- allure-js-commons@1.3.1
  | +-- file-type@4.4.0
  | +-- fs-extra@3.0.1
  | | +-- graceful-fs@4.1.11
  | | +-- jsonfile@3.0.1
  | | `-- universalify@0.1.1
  | +-- js2xmlparser@3.0.0
  | | `-- xmlcreate@1.0.2
  | +-- mime@1.3.4
  | +-- object-assign@4.1.1
  | `-- uuid@3.2.1
  `-- babel-runtime@6.26.0
    +-- core-js@2.5.3
    `-- regenerator-runtime@0.11.1

Link to Allure report:  http://172.16.4.109:64354/index.html#suites 

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
This issue was moved to webdriverio/wdio-allure-reporter#97
