### ISSUE TITLE
The placeholder is still displaying when setValue on textField with Webview Appium hybridapp on iOS real device

### ISSUE THREAD

**Issue by miendt** [webdriverio/webdriverio#2620]
## The problem
- The placeholder is still displaying when setValue on textField with Webview Appium hybridapp on iOS real device.
- Currently, i'm using ```browser.setValue(selector,values);``` to setValue for textField

## Environment

* WebdriverIO version: 4.11.0
* Node.js version: v8.9.3
* Chimp version: 0.50.2
* Appium version: 1.7.1

## Details

- I'm using iOS WebKit Debug Proxy to switch to Webview to run iOS real device for hybridapp
However, I have problem relate to the placeholder is still displaying when setValue on textField 

For example: 
Login screen after inputting the id and password ==> id and password's textfield still is displaying placeholder text, so it cannot login to app.
![placeholder](https://user-images.githubusercontent.com/22675530/36776675-32ee9324-1c99-11e8-87f4-afd96518bf54.png)

**Comment by christian-bromann** [comment]
Hi @miendt,
this looks like an automation issue and can't be fixed by WebdriverIO. Seems that some input events aren't fired. You can try to click on the input field after you entered the text. I recommend filling an issue on the Appium project. Thanks!
