### ISSUE TITLE
webdriver-io link redirection in mobile version

### ISSUE THREAD

**Issue by venkathere** [webdriverio/webdriverio#2621]
I am writing test cases using Webdriver-io for mobile version and on a page when link is clicked it is redirecting to other window but my selectors are not working on opened window ..giving error "" unknown server-side error occured""" is this expected or any other solution?

Selectors are working fine if the click redirects to same page. but if the click opens another window result is error.

**Comment by christian-bromann** [comment]
> is this expected or any other solution?

Hard to tell without logs or code example. You probably want to make sure you are in the right window context and if you need to want to change it using switchTab. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
