### ISSUE TITLE
Using await in sync mode seems to break fibers

### ISSUE THREAD

**Issue by jardakotesovec** [webdriverio/webdriverio#2622]
## The problem

When using await, it seems to break the automatic wdio driver syncing. There are use cases when I need to do asynchronous calls (network request, updating dummy database) within the test, so I used `async/await` for it.

Here is example:
```
function delay(t, v) {
  return new Promise(function(resolve) {
    setTimeout(resolve.bind(null, v), t);
  });
}

describe('test', function() {
  it.only('async1', async function() {
    console.time('delay');
    await delay(5000);
    console.timeEnd('delay');
    console.time('pause');
    browser.pause(10000);
    console.timeEnd('pause');
  });
});
```
Result:
```
delay: 5003.473ms
pause: 9.161ms
```
But if I remove the await delay part, than browser.pause works as expected (takes 10s).  So wondering how to approach that or if that could be somehow addressed. I can't just switch off sync mode and use await everywhere, because than I loose beforeCommand hook (they are not called when sync is false).

## Environment

* WebdriverIO version: 4.10.2
* Node.js version: 8.9.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio test runner
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

**Comment by christian-bromann** [comment]
@jardakotesovec if you need to do async calls use the [`call`](http://webdriver.io/api/utility/call.html#Example) method.
