### ISSUE TITLE
WebdriverIO documentation for wdio-allure-reporter should mention that it does not currently support wdio-cucumber-framework

### ISSUE THREAD

**Issue by osmolyar** [webdriverio/webdriverio#2623]
## The problem

The WebdriverIO Developer Guide Reporters section lists Allure as a compatible reporter without any caveat that it does not currently support wdio-cucumber-framework (with Scenario Outlines).

In fact the Allure reporting hierarchy does not support a Feature -> Scenario Outline -> Test-> Step hierarchy as it is missing a level.

Either it reports all the steps from all the tests in a Scenario Outline as individual tests, combined into a single numbered list, which is in random order in the report display (behavior of current latest version, @0.3.2), 

Or, using a one-off GitHub package provided by one of the authors, it can report a Scenario Outline as a single 'test' with one set of Steps, without reporting the individual tests.

Please see https://github.com/webdriverio/wdio-allure-reporter/issues/97 for status of issue and screenshots.

## Environment

WebdriverIO version: 1.0.3
Node.js version: 6.5.0
Standalone
wdio-cucumber-framework ^1.1.0"
*wdio-allure-reporter 0.3.2
allure-js-commons@1.3.1 

OR
*wdio-allure-reporter 0.3.0 (custom version provided by @BorisOsipov )
allure-js-commons@1.3.1

## Details

See  https://github.com/webdriverio/wdio-allure-reporter/issues/97 for details.

**Comment by christian-bromann** [comment]
I don't think updating the docs saying that it doesn't support the allure reporter will help us at all getting this issue fixed. We want to provide support for all reporters using all frameworks but it is a lot of work especially for me. So if you are interested in using the reporter with cucumber it would be super helpful if you could help us out here. Thanks!

**Comment by osmolyar** [comment]
@christian-bromann, agree that ideally the support would be available, and perhaps documenting the current state is not helpful towards achieving this goal.  Unfortunately I would have no idea how to approach this (though could try, given some direction).  

@BorisOsipov in the original issue provided a custom package which attempts to fix the problem, saying that the only reason full support was not yet provided in the published package was that he didn't want to break jasmine/mocha reports, so I would think he would be the best person to provide a package that is compatible with wdio-cucumber-framework.
