### ISSUE TITLE
Not able to launch multiple sessions to work on parallel testing

### ISSUE THREAD

**Issue by darklord549** [webdriverio/webdriverio#2627]
## The problem

I need to launch two appium sessions with different ports for emulators with different Google API's.
How to write that in wdio.config.js file. This is required because i want to ran my code on two different platforms in parallel.

Could you please help me with this?

**Comment by christian-bromann** [comment]
@darklord549 you can define host and port properties in the desired capabilities of your wdio.conf.js to point each capability to a different Appium server, e.g.
```js
// wdio.conf.js
exports.config = {
  // ...
  capabilities: [{
     host: 'somewhere',
     port: 4723,
     platformName: '...'
  }, {
     host: 'somewhere-else',
     port: 4723,
     platformName: '...'
  }],
  // ...
}
```
If you have further questions, join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
