### ISSUE TITLE
Error generating mochawesome html report

### ISSUE THREAD

**Issue by biz786** [webdriverio/webdriverio#2628]
## The problem

Hi im having an issue generation html report using the wdio-mochawesome-reporter. The JSON file is generated fine but when i run - "generateMochawesome":"marge <path/to/results.json> --reportTitle 'My Project Results'" ; i get an error

## Environment
Typescript,nodejs,mocha,webdriverio

* WebdriverIO version:
* Node.js version: 6.0.0
* wdio testrunner - running synchronous tests:
* Additional wdio packages used (if applicable):see attached image

**Comment by biz786** [comment]
![error_mochawesome_webdriverio](https://user-images.githubusercontent.com/4602480/36993133-00789896-207b-11e8-8f55-872ad8841182.jpg)

![package json](https://user-images.githubusercontent.com/4602480/36993149-099deaac-207b-11e8-9524-3aa3ce75b6c6.jpg)

**Comment by biz786** [comment]
![error_mochawesomereporter_webdriverio](https://user-images.githubusercontent.com/4602480/36993417-c2b13850-207b-11e8-9436-0c5caed4b16c.jpg)

**Comment by biz786** [comment]
![package json](https://user-images.githubusercontent.com/4602480/36993824-2516f600-207d-11e8-8faa-a903ce4b313e.jpg)

**Comment by biz786** [comment]
![error_mochawesome-reporter_webdriverio](https://user-images.githubusercontent.com/4602480/36993850-43aca7fe-207d-11e8-8da8-83defe5ae547.jpg)

**Comment by christian-bromann** [comment]
Can you please file an issue [here](https://github.com/fijijavis/wdio-mochawesome-reporter)? Thanks!

**Comment by biz786** [comment]
![json_report](https://user-images.githubusercontent.com/4602480/37000151-74965848-2090-11e8-96e1-58c89d079d67.jpg)

**Comment by samwarwick** [comment]
Possible work-around is to use an older version of mochawesome-report-generator. e.g. 2.3.2 works for me.

**Comment by fijijavis** [comment]
Yeah...we are in the process of getting the wdio-mocha-awesome reporter so it can support both the 2.x and 3.x versions of the report generator

**Comment by biz786** [comment]
@samwarwick  thanks! @christian-bromann created a new issue [here|https://github.com/fijijavis/wdio-mochawesome-reporter/issues/23]
