### ISSUE TITLE
setValue used for multiple Text Fields on Android crashes and breaks test

### ISSUE THREAD

**Issue by DalianaD** [webdriverio/webdriverio#2629]
## The problem

I am trying to fill in 4 Text Fields, on a NativeScript app for Android, using the browser.setValue(selector,values);

If I have 3 Text Fields on the screen, the test runs successfully. 
If I have 4 Text Fields on the screen, the test fails.

In the console, at the failure point, I can see this trace:

`COMMAND	POST 	 "/wd/hub/session/f1c33191-528b-4b12-bdb3-3dfef1d4f18b/element"
[14:48:03]  DATA		{"using":"accessibility id","value":"inputUserEmail"}
F․ [14:48:03]  COMMAND	DELETE 	 "/wd/hub/session/f1c33191-528b-4b12-bdb3-3dfef1d4f18b"
[14:48:03]  DATA		{}
[14:48:03]  RESULT		{"ELEMENT":"7"}
[14:48:03]  COMMAND	POST 	 "/wd/hub/session/f1c33191-528b-4b12-bdb3-3dfef1d4f18b/element/7/clear"
[14:48:03]  DATA		{}
[14:48:04]  RESULT		undefined`

It always fails at the 4rd Text Field (even if I switch the order of the fields in the demo app, so it is not the fields issue).

## Environment

* WebdriverIO version: 4.7.1
* Node.js version: 8.1.4
* wdio TestRunner Mode
* Additional wdio packages used (if applicable):
    "wdio-appium-service": "^0.2.3",
    "wdio-cucumber-framework": "^0.2.15",
    "wdio-junit-reporter": "0.2.0",
    "wdio-screenshot": "^0.4.0",
    "wdio-selenium-standalone-service": "0.0.8",
    "wdio-spec-reporter": "0.0.5",
    "webdriverio": “4.7.1"

    "appium-controller": "1.1.5",
    "appium-uiautomator": "1.1.5”,
    "cucumber": "~1.3.1",
    "cucumber-expressions": "^5.0.7",
    "cucumber-tag-expressions": "^1.1.1",

## Details
To reproduce the issue, make sure you have an Android Emulator open.

In the provided test app run:
`npm install`
`npm run test-only-smoke-android`

## Code To Reproduce Issue [ Good To Have ]

Please take a look into this example repository, as it contains a test app and UI integration test where we see the issue:

https://github.com/surdu/TNSTravisTest.git

**Comment by christian-bromann** [comment]
This sounds more like an Appium issue than a bug in WebdriverIO. Can you provide Appium logs to verify this?

**Comment by DalianaD** [comment]
Thanks Christian for the fast response.
I have attached the Appium log.
[appium.log](https://github.com/webdriverio/webdriverio/files/1785660/appium.log)

**Comment by DalianaD** [comment]
@christian-bromann Do have any news regarding this issue? Do you still feel it’s an Appium issue rather than a WebdriverIO?

**Comment by christian-bromann** [comment]
> Do you still feel it’s an Appium issue rather than a WebdriverIO?

This is probably the case. I don't have any insights on this.

**Comment by DalianaD** [comment]
I will raise this in the Appium github issues. Thanks for taking the time to take a look into this.

**Comment by christian-bromann** [comment]
> I will raise this in the Appium github issues. Thanks for taking the time to take a look into this.

Alright, let me know if it turns out to be a WebdriverIO issue. Closing this until then.
