### ISSUE TITLE
Validate that string included reporters also carry a reportName function

### ISSUE THREAD

**Issue by mattc41190** [webdriverio/webdriverio#2633]
It seems like once the package has been required we should incorporate the same level of validation that we do for local function based reporters.

```
const pkgName = reporterName.startsWith('@') ? reporterName : `wdio-${reporterName}-reporter` 

Reporter = require(pkgName)

if (!Reporter.reporterName) {
    throw new Error('Custom reporters must export a unique \'reporterName\' property')
}
```
https://github.com/webdriverio/webdriverio/blob/1405c0296c94779ccba3a89cfcabda2c20cf12f9/lib/launcher.js#L64

**Comment by mattc41190** [comment]
Sorry missed this:

'Custom reporters must export a unique \'reporterName\' property'

I am guessing this means that reporters coming from a package are not required to adhere to the same format as local function reporters. Feel free to close if this is the case.

**Comment by christian-bromann** [comment]
> I am guessing this means that reporters coming from a package are not required to adhere to the same format as local function reporters

Yes. We need to know the name of your reporter in order to apply the correct function for it.
