### ISSUE TITLE
Support for Shadow DOM

### ISSUE THREAD

**Issue by shafh** [webdriverio/webdriverio#2634]
At this moment does WebdriverIO (v. 4.12.0) not support the Shadow DOM.

This means that `browser.element(selector);` will fail if the selector is querying elements in the Shadow DOM.
 [A third party library was made]( https://github.com/Morlack/wdio-webcomponents) but doesn't work well with WebDriverIO's API: Its new `element` function does not implement the same interface. It returns a JS object while the native `element` function returns a WebElement JSON.

Shadow DOM is a standard. It would be nice if WebdriverIO would support it.

**Comment by christian-bromann** [comment]
> Shadow DOM is a standard. It would be nice if WebdriverIO would support it.

I agree, however support should be added in the browser driver not necessarily in Chrome. The third party library is just a workaround.

> but doesn't work well with WebDriverIO's API

Probably due to #1796.

**Comment by shafh** [comment]
I'm not optimistic about the WebDriver protocol (if that what you refers to) adding support recently. What holds WebdriverIO back to implement its own a solution. 
The solution should work well with the rest of the framework as long as it return as it returns a WebElement JSON.

**Comment by christian-bromann** [comment]
> What holds WebdriverIO back to implement its own a solution

Well ultimately WebdriverIO should only send the element command to the browser driver and the browser driver should be able to find the element within the shadow DOM. I am not oppose to implement that workaround and the third party library already does that.

**Comment by junguchina** [comment]
Is there any roadmap to support Shadow DOM?
Our team think Shadow DOM is useful for UX and developer team paired working.
With Shadow DOM, UX team can join the develop working and they can design the UI directily.

**Comment by christian-bromann** [comment]
Added it to the roadmap for v5 (webdriverio/v5#44). Everyone is welcome to add this functionality to v4 if someone doesn't want to wait until v5 is released.
