### ISSUE TITLE
Tests Fail On Fresh Install

### ISSUE THREAD

**Issue by mattc41190** [webdriverio/webdriverio#2636]
## The problem

`npm run test:desktop`
Tests fail on initial clone. 

## Environment

* WebdriverIO version: 
4.12.0
* Node.js version: 
node -v // v8.9.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
* if wdio testrunner, running synchronous or asynchronous tests: 
Local Dev
* Additional wdio packages used (if applicable): 
None

## Details

When running the commands in Contributing.md before any code has been modified tests still fail

## Link to Selenium/WebdriverIO logs

https://gist.github.com/mattc41190/153b4f97470ec96eeedf041e8919f885

## Code To Reproduce Issue [ Good To Have ]

The commands inside of Contributing.md

**Comment by christian-bromann** [comment]
Hard to tell what issue you are experiencing. Seems that the connection to the driver crashes for some reason. Don't see this being related to WebdriverIO though. Therefor closing this.
