### ISSUE TITLE
QUESTION: Does Launcher.run append a resolve to the class? 

### ISSUE THREAD

**Issue by mattc41190** [webdriverio/webdriverio#2640]
## The Question

This question pertains to the flow of the runner:

I am looking at `lib/runner.js` and trying to get a feel for how `run` works.  It appears that it is setting the resolve function from `exitCode` Promise to a class level `this.resolve` then it uses the `runSpecs` method to kick off the actual test run. 

My question is, is the above explanation of what is occurring in the run method correct?

**Comment by christian-bromann** [comment]
> My question is, is the above explanation of what is occurring in the run method correct?

I guess so. 
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by mattc41190** [comment]
I agree, however, the gitter chat seems to be geared more towards implementation of tests written suing and less towards how webdriverio itself is actually made. 

Is there a dev channel for webdriverio concerned with the the program itself works rather than how to use it? Or do you guys have any architectural docs. Reading through the source code from entry point is leaving me with a bunch of questions.

**Comment by christian-bromann** [comment]
> Is there a dev channel for webdriverio concerned with the the program itself works rather than how to use it?

We have: gitter.im/webdriverio/v5 but we are more discussing the new architecture we will build with v5. The current one will be overhauled eventually.

**Comment by mattc41190** [comment]
That is kind of sad. I think it's pretty intelligently structured as is. Thanks for the direction.

**Comment by christian-bromann** [comment]
> I think it's pretty intelligently structured as is.

Thanks but it isn't scaleable and WebdriverIO wants to grow. With the current setup it can't.

**Comment by christian-bromann** [comment]
If you are interested being more involved into the development of WebdriverIO checkout the [new v5 codebase](https://github.com/webdriverio/v5) and [some of the issues](https://github.com/webdriverio/v5/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+pick%22) that are good when you want to get started.
