### ISSUE TITLE
Chrome options not being passed to selenium grid node

### ISSUE THREAD

**Issue by jlseeto101** [webdriverio/webdriverio#2645]
## The problem

The chrome options are not being sent to the selenium grid node. 

capabilities: [{
maxInstances: 5,
browserName: 'chrome',
chromeOptions: {
"useAutomationExtension":false,
"args":['--start-maximized']
}
}],

## Environment

* WebdriverIO version: 4.10.2
* Node.js version: v8.9.4
* Chromedriver version: 2.36

## Details

The chrome options does work when running locally (selenium-standalone start) however chrome options are not being set when using the hub / node setup.

## Code To Reproduce Issue [ Good To Have ]

commands used for starting up selenium-standalone:
* selenium-standalone start -- -role hub
* selenium-standalone start -- -role node -hub http://<ip>/grid/register etc..

**Comment by christian-bromann** [comment]
@jlseeto101 this is not an issue with WebdriverIO. It properly sends these chrome options however they might not be accepted which is not a problem WebdriverIO can solve. For further questions please reach out to our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).

**Comment by AnnikaNissen** [comment]
I came across the same issue today and was abled to fix it / find a workaround:

To pass chrome options to the Grid / RemoteWebdriver you need to pass `goog:chromeOptions` instead of `chromeOptions` in the capabilities.

So instead of this:
```javascript
capabilities: [{
    browserName: 'chrome',
    chromeOptions: { // for local ChromeDriver
        args: ["--headless", "user-agent=...","--window-size=375,667"]
    }
 }],
```

You just write this:
```javascript
capabilities: [{
    browserName: 'chrome',
    'goog:chromeOptions': { // ffor RemoteWebdriver
        args: ["--headless", "user-agent=...","--window-size=375,667"]
    }
 }],
```

You can also pass both, so that you can run on the grid or local without modifying the configuration:
```javascript
capabilities: [{
    browserName: 'chrome',
    chromeOptions: { // for local ChromeDriver
        args: getChromeOptions() // function returns the args-array, so that the values aren't duplicated
    },
   'goog:chromeOptions': { // ffor RemoteWebdriver
        args: getChromeOptions() // function returns the args-array, so that the values aren't duplicated
    }
 }],
```

Hope this helps others, who find this old issue when googling ;-)
