### ISSUE TITLE
Error: invalid argument at waitUntil

### ISSUE THREAD

**Issue by KumarSunil20** [webdriverio/webdriverio#2653]
## The problem

Error: invalid argument at waitUntil
I have a custom method called waitUntilPageLoad() where I have used browser.waitUntil method.
I am getting the error message mentioned below:

{ Error: invalid argument
    at waitUntil([object Object], 60000, "Page is still loading") -     at C:\Users\sunil.kumar\Documents\MedForce_QA_Exec_Env\node_modules\wdio-sync\build\index.js:316:3
  details: undefined,
  message: 'invalid argument',
  type: 'CommandError',
  shotTaken: true }

## Environment

* WebdriverIO version: 4.12.0
* Node.js version: 8.9.1
* wdio testrunner
* if wdio testrunner, running synchronous (wdio-sync)

## Details
{ Error: invalid argument
    at waitUntil([object Object], 60000, "Page is still loading") -     at C:\Users\sunil.kumar\Documents\MedForce_QA_Exec_Env\node_modules\wdio-sync\build\index.js:316:3
  details: undefined,
  message: 'invalid argument',
  type: 'CommandError',
  shotTaken: true }

## Code To Reproduce Issue [ Good To Have ]
Function:
module.exports = () => {
    try {
        browser.waitUntil(browser.execute(() => {
            return jQuery.active == 0;
        }), browser.options.waitforTimeout, 'Page is still loading');
    } catch (err) {
        console.log(err);
        assert.fail(err);
    }
};

**Comment by christian-bromann** [comment]
As described in [the docs](http://webdriver.io/api/protocol/execute.html#Parameters) the execute command takes a function or a string as parameter not an object. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
