### ISSUE TITLE
java.io.IOException: Error writing to server

### ISSUE THREAD

**Issue by KumarSunil20** [webdriverio/webdriverio#2654]
## The problem

I am experiencing this error most of the time when I run the script (not all the time).
cause: browser.getAttribute() function

## Error Details

java.io.IOException: Error writing to server
[chrome #0-0] Error: An unknown server-side error occurred while processing the command.
[chrome #0-0]     at elementIdAttribute("0.31804148897353457-28", "class") - C:\Users\sunil.kumar\Documents\MedForce_QA_Exec_Env\node_modules\webdriverio\build\lib\commands\getAttribute.js:43:55

java.net.ConnectException: Connection refused: connect
[chrome #0-0] Error: An unknown server-side error occurred while processing the command.
[chrome #0-0]     at elementIdAttribute("0.022919823191283495-28", "class") - C:\Users\sunil.kumar\Documents\MedForce_QA_Exec_Env\node_modules\webdriverio\build\lib\commands\getAttribute.js:43:55

## Environment

* WebdriverIO version: 4.12.0
* Node.js version: 8.9.1
* wdio testrunner
* wdio testrunner, running synchronous (wdio-sync):
*chromedriver: 2.36.0
*selenium-standalone: 6.13.0
*wdio: 1.0.3
*wdio-chromedriver-service: 0.1.2
*wdio-selenium-standalone-service: 0.0.10
*Chrome - 65.0.3325.162
*Window  - 10

## Code To Reproduce Issue [ Good To Have ]
import { CommandError } from '../utils/ErrorHandler'

let getAttribute = (selector, attributeName) => {
    /*!
     * parameter check
     */
    if (typeof attributeName !== 'string') {
        throw new CommandError('number or type of arguments don\'t agree with getAttribute command')
    }

    return this.elements(selector).then((res) => {
        /**
         * throw NoSuchElement error if no element was found
         */
        if (!res.value || res.value.length === 0) {
            throw new CommandError(7, selector || this.lastResult.selector)
        }

        let elementIdAttributeCommands = []

        for (let elem of res.value) {
            elementIdAttributeCommands.push(this.elementIdAttribute(elem.ELEMENT, attributeName))
        }

        return this.unify(elementIdAttributeCommands, {
            extractValue: true
        })
    })
}

export default getAttribute

Is there any solution to the problem stated

**Comment by KumarSunil20** [comment]
Experiencing this error only in latest Chrome browser. Earlier It was working fine.

**Comment by christian-bromann** [comment]
> Experiencing this error only in latest Chrome browser. Earlier It was working fine.

Sorry but this is not an error in WebdriverIO. Looks like a Chromedriver issue: https://bugs.chromium.org/p/chromedriver/issues/detail?id=114

**Comment by phil-lgr** [comment]
Same error here: https://github.com/webdriverio/wdio-selenium-standalone-service/issues/39

**Comment by phil-lgr** [comment]
Are you sure it's related? The issue you linked is from 2012..

**Comment by phil-lgr** [comment]
@KumarSunil20 any news on your side?

**Comment by phil-lgr** [comment]
I put together a sample repo: https://github.com/phil-lgr/wdio-issue-repro
