### ISSUE TITLE
browser.frameParent() is no longer working for me

### ISSUE THREAD

**Issue by krisraven** [webdriverio/webdriverio#2656]
## The problem

browser.frameParent() is no longer working

## Environment

* WebdriverIO version 4.6.2
* Node.js version 6.11.0
* wdio testrunner
* I'm running the tests using gulp with additional verification of tests using mocha and chai

## Details

I recently updated my Chromedriver and now browser.frameParent() to navigate to the parent frame of a page has stopped working.

```
    browser.frameParent();
    var menuframe = $('[name="fraMainMenu"]').value;
    browser.frame(menuframe);
    console.log(menuframe);
    browser.click(varlist.treeview);
```

But the problem is that `console.log(menuframe)` returns null and the late `browser.click(varlist.treeview);` cannot  be found.
Previously, `varlist.treeview` could be found, as it is part of the `fraMainMenu` frame.

## Code To Reproduce Issue

Full code of the test...
```
var VariablesListObject = require('./page-objects/ListObject.js')

var TestScope = {}; // Single Variable Scope

describe('Runs a report', function() {
  before(function() {
    varlist = new VariablesListObject();
  });

  it('Checks All Transaction report', function() {
    browser.url(varlist.url);
    browser.waitForExist(varlist.usernametag);
    browser.setValue(varlist.usernametag, varlist.username);
    browser.setValue(varlist.passwordtag, varlist.password);
    browser.click(varlist.logonbutton);
    browser.waitForExist(varlist.framecontentstag);
    var contentframe = $(varlist.framecontentstag).value; // switches frame
    browser.frame(contentframe); // switches frame
    var toolbarframe = $(varlist.frametoolbartag).value; // switches frame
    browser.frame(toolbarframe); // switches frame
    browser.click(varlist.selectcompanytag);
    browser.waitForVisible(varlist.companyid);
    browser.click(varlist.companyid);
    browser.frameParent(); // goes up a level level
    var menuframe = $('[name="fraMainMenu"]').value; // switches frame
    browser.frame(menuframe); // switches frame
    console.log(menuframe);
    browser.click(varlist.treeview);
    });
});
```

**Comment by christian-bromann** [comment]
Without logs it is impossible to know what is going on :-(

**Comment by krisraven** [comment]
Thanks; gist of the npm-debug log is here https://gist.github.com/krisraven/edd9af9dcf2b63ccf57c910151b13fa6
Is this correct log, or is there another one

**Comment by christian-bromann** [comment]
> Is this correct log, or is there another log that is needed?

I need either some webdriverio logs or the logs of the browser driver

**Comment by krisraven** [comment]
Hi Christian, thanks for your reply. Webdriver IO logs from setting log level to VERBOSE in the wdio.conf are here; https://gist.github.com/krisraven/d5716b228fffd9ff3c3c2f5c0c766b8f

**Comment by christian-bromann** [comment]
As you can see in the logs it can't find the element you are looking for (`{"using":"id","value":"upVMenuH2I2"}`). This is the reason why it might fail. This is not a WebdriverIO bug closing. If you have further questions join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
