### ISSUE TITLE
Hi team, I am having problem with browser authentication popup.

### ISSUE THREAD

**Issue by mr-nilesh** [webdriverio/webdriverio#2659]
I have tried, passing username:password in URL and I am getting error like
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:54:15.039Z'
System info: host: 'nilesh', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-116-generic', java.version: '1.8.0_161'
Driver info: driver.version: unknown

Can you guys help me to fix this issue?

Thanks in advance.

**Comment by christian-bromann** [comment]
Join our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue of WebdriverIO.
