### ISSUE TITLE
Test summary not reported when a script / nodejs error occurs

### ISSUE THREAD

**Issue by erwinheitzman** [webdriverio/webdriverio#2660]
## The problem

When there's a non test related error such as "ERROR: Unexpected strict mode reserved word" then the test summary is missing from the test result when using the dot and spec reporters.

## Environment

* WebdriverIO version: 4.12.0
* Node.js version: 8.10.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): 
    "wdio-junit-reporter": "^0.4.2",
    "wdio-mocha-framework": "^0.5.13",
    "wdio-selenium-standalone-service": "0.0.10",
    "wdio-spec-reporter": "^0.1.4",

## Details

Errors outside of the test scope cause the test result summary to not be logged to the console.
I still expect a summary so that when multiple tests are ran there's still a summary of the testrun.

Console output:
```
> wdio ./configs/wdio.conf.js


ERROR: Unexpected strict mode reserved word
chrome
/Users/example-username/Documents/dev/project/test/some-example-path/search.e2e-spec.js:9
    static get something () { return '' }
    ^^^^^^

Syntax    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /Users/example-username/Documents/dev/grip-at/node_modules/mocha/lib/mocha.js:231:27


Wrote xunit report "WDIO.xunit.chrome.0-0.xml" to [./artifacts].
npm ERR! Test failed.  See above for more details.
```

## Code To Reproduce Issue [ Good To Have ]

```
'use strict'

class Example {

  constructor() {
    static get something () { return '' }
  }

  open() {
    browser.url(Example.something)
  }

}

const example = new Example()

describe('it should break', () => {
  it('causes the reporter to not show the test result summary', () => {
    example.open()
  })
})
```

**Comment by christian-bromann** [comment]
@erwinheitzman this is a parsing error which is much more severe than an assertion error. I can't give you any summary because the test can't even be run with that error.
