### ISSUE TITLE
setValue broken on Chrome browser

### ISSUE THREAD

**Issue by guilean** [webdriverio/webdriverio#2661]
## The problem

The setValue function is not working correctly in Chrome browser, throw an exception. Same method works properly in Firefox.

## Environment

* WebdriverIO version: **4.8.0**
* Node.js version: **8.9.1**
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): **WDIO**
* if wdio testrunner, running synchronous or asynchronous tests: **Synchronous**

## Details

Exception:

`unknown error: call function result missing 'value'
running chrome
Error: An unknown server-side error occurred while processing the command.
    at elementIdValue("0.6703527834424823-1", "This should go there") - setValue.js:46:80`

## STR

```
describe('This test will crash', () => {

	it('Testing error case', () => {
              browser.url(`http://www.google.com`);
              browser.setValue('#lst-ib', 'This should go there');
	});

})

```

This case works on Firefox and raises an exception on Chrome.

**Comment by erwinheitzman** [comment]
This is very little information, please add more info such as the exception you are getting.
This also sounds more like a problem with an outdated Chromedriver.

**Comment by marcelas** [comment]
If you updated your browser, but not the driver that would happen. I had a similar issue a couple of weeks ago.

**Comment by christian-bromann** [comment]
@guilean please try the solution of @marcelas (thanks!) and let us know if it doesn't work out.
