### ISSUE TITLE
Error on browser.click(): selector needs to be typeof `string`

### ISSUE THREAD

**Issue by naheller** [webdriverio/webdriverio#2662]
## The problem

I am attempting to automate the submission of an email/password form. The email field has `name=email`, the password field has `name=password`, and the submit button has `type=submit`. Using the code in the Details section below, the email and password fields receive my input correctly.

However, attempting to click the Submit button yields the following error:
```
selector needs to be typeof `string`
running chrome
Error: selector needs to be typeof `string`
    at Promise.F (node_modules/core-js/library/modules/_export.js:35:28)
    at element([object Object]) - click.js:12:17
    at click([object Object]) - at Context.<anonymous> (systemTests/spec/myTestPage.js:67:17)
```
Line 67 is the `browser.click` line in the code below.

## Environment

* WebdriverIO version: 4.12.0
* Node.js version: 6.11.4

## Details

Here is the code in question:

```
const emailField = browser.element('[name="email"]');
const passwordField = browser.element('[name="password"]');
const loginButton = browser.element('[type="submit"]');
        
emailField.setValue('emailString'); // success
passwordField.setValue('passwordString'); // success
browser.click(loginButton); // fail
```
How do I fix this issue? Your advice is appreciated!

**Comment by christian-bromann** [comment]
> How do I fix this issue?

Please see [API](http://webdriver.io/api/action/click.html#Usage) this way of using the click function is not supported. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
