### ISSUE TITLE
Debug() REPL repeats characters in multiremote mode

### ISSUE THREAD

**Issue by zmorris** [webdriverio/webdriverio#2672]
## The problem

If there is more than one client specified in wdio.conf.js.capabilities then browser.debug() causes duplicate characters to get entered in its REPL mode.  I couldn't find anything on the web about it so figured I'd post the issue **(and 2 workarounds)** here.  More info:

http://webdriver.io/api/utility/debug.html which mentions:
```
Also avoid to execute the command with multiple capabilities running at the same time.
```

http://webdriver.io/guide/usage/repl.html

I access the REPL by calling `debug()`.  I haven't tried `$ wdio repl ...` yet.

## Environment

* WebdriverIO version: v4.12.0
* Node.js version: v9.8.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):
    "chai": "~4.0.1",
    "chai-webdriverio": "^0.4.3",
    "wdio": "^1.0.3",
    "wdio-appium-service": "^0.2.3",
    "wdio-mocha-framework": "^0.5.13",
    "wdio-spec-reporter": "^0.1.4"

## Code To Reproduce Issue [ Good To Have ]

wdio.conf.js:
```
...
capabilities: {
        androidClient: {
            port: 4723,
            desiredCapabilities: {}
            }
        },

        iosClient: {
            port: 4723,
            desiredCapabilities: {}
            }
        },
}
...
```

I'm testing this with Appium but it likely happens in any multiremote setup.  If I call `browser.debug()` like in the following:
```
describe('Simple cases', function() {
    this.timeout(6000000);
    // this.timeout(300000);

    before(function() {});

    describe("Test native App", function() {
        it("test-function", function() {
            browser.debug();
        });
    });

    after(function() {});
});
```

I see something like this:

```
$ ./node_modules/.bin/wdio wdio.conf.js

[14:28:32]  DEBUG	Queue has stopped!
[14:28:32]  DEBUG	You can now go into the browser or use the command line as REPL
[14:28:32]  DEBUG	(To exit, press ^C again or type .exit)

> 
[14:28:32]  DEBUG	Queue has stopped!
[14:28:32]  DEBUG	You can now go into the browser or use the command line as REPL
[14:28:32]  DEBUG	(To exit, press ^C again or type .exit)

> ccoonnssoollee..lloogg((bbrroowwsseerr))
{ state: 'fulfilled', value: undefined }
> 
{ state: 'fulfilled', value: undefined }
> 
```

For now the workaround is to either:

1) Comment out one of the `wdio.conf.js.capabilities` (so there is `androidClient` or `iosClient` but not both)

Or:

2) Call `browser.select('androidClient').debug();` so that only one of clients is put into REPL mode.  Then I see the correct:

```
$ ./node_modules/.bin/wdio wdio.conf.js

[14:31:08]  DEBUG	Queue has stopped!
[14:31:08]  DEBUG	You can now go into the browser or use the command line as REPL
[14:31:08]  DEBUG	(To exit, press ^C again or type .exit)

> console.log(browser)
{ state: 'fulfilled', value: undefined }
> console.log(browser.select('androidClient'))
{ state: 'fulfilled', value: undefined }
> console.log(browser.select('iosClient'))
{ state: 'fulfilled', value: undefined }
> 
```

As far as I can tell, everything works normally after that.  It seems like option 2 is best because it doesn't involve modifying `wdio.conf.js`, so maybe the documentation could just be updated.

But if the functionality of calling `browser.debug()` and `browser.select(<client>)` are identical except for the repeating characters, then maybe `webdriverio/lib/commands/debug.js` could be updated to call the browser's first client's `debug()` instead.

Hope this helps someone, thanks and keep up the great work!

**Comment by christian-bromann** [comment]
We rebuild the repl in v5. Please verify if this issue still exists there. Happy to reopen in case it is still a bug.
