### ISSUE TITLE
Error: Unrecognised hook ["after each" hook] for suite ["suite name"]

### ISSUE THREAD

**Issue by mrdanimal** [webdriverio/webdriverio#2673]
## The problem

I recently started getting the following error: **"Error: Unrecognised hook ["after each" hook] for suite ["suite name"]** for one set of my tests. The error happens intermittently and doesn't always occur on the same exact test.

## Environment

* WebdriverIO version: 4.12.0
* Node.js version: v7.7.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): testrunner
* synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):
  * wdio-mocha-framework
  * wdio-selenium-standalone-service
  * wdio-spec-reporter

## Link to Selenium/WebdriverIO logs
https://gist.github.com/mrdanimal/c5970cbdf95b2d08b413bcfc5b0ae53f

## Code To Reproduce Issue

Unfortunately, I can't share this code publicly. I'm attempting to create an isolated test case that exhibits the issue, but haven't been successful yet.  

Let me know if there's any other info that would be helpful to know.

**Comment by mrdanimal** [comment]
So, I’ve been digging around in the code and logging stuff to the console to see if I can figure out what’s going on. Somewhere between `hookStart` and `hookEnd`, the hook is removed from `suiteStats.hooks`. I confirmed that it is actually there at the end of `hookStart` and it really isn’t there at the beginning of `hookEnd`. Is there any other process between `hookStart` and `hookEnd` that can modify the `hooks` object? Can anyone provide more info that might help me debug? Thanks.

**Comment by christian-bromann** [comment]
> Is there any other process between hookStart and hookEnd that can modify the hooks object? Can anyone provide more info that might help me debug?

Not sure, nothing should get deleted.

Can you provide a minimal reproducible example?

**Comment by mrdanimal** [comment]
Trying, but I haven't been able to yet.

**Comment by mrdanimal** [comment]
I was able to work around this and I'm not able to create an isolated example, so I'm going to close this.

**Comment by number33** [comment]
@mrdanimal What was your solution/work-around?

**Comment by mrdanimal** [comment]
@number33, unfortunately, I'm not sure it will help anyone else. If I recall correctly, I found I was getting the error because some other dependent package (can't remember what) was updated to a new version when installing my app in a CI environment. Turned out that package didn't need to be updated, so once I fixed that dependency version, the problem was resolved.
