### ISSUE TITLE
Unable to throw error to catch block from custom command 

### ISSUE THREAD

**Issue by prakashomp** [webdriverio/webdriverio#2676]
## The problem

We are unable to throw error to catch block from shared command.
I wrote custom commands like below
the function command is add to browser command 
module.exports = function nameA(options) {
try{
code for nameA 
....
}
catch(error){
throw error
}
};

//Calling function 
function B(){
try{
browser.nameA(options);
code for Function B;
}
catch(error){
error Handle ....
}
}

Form above sample code if we got error in nameA we got error and aborting script.
Error is not catching in FunctionB.
We are able to catch in FunctionA then aborting.

**Comment by christian-bromann** [comment]
I am not sure if this is an WebdriverIO issue or a JS related question. Please reach out on our support [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) to explain your issue in a little more detail. Thanks!
