### ISSUE TITLE
Incorrect Epilogue Due To Hook Methods 

### ISSUE THREAD

**Issue by mattc41190** [webdriverio/webdriverio#2682]
https://github.com/webdriverio/webdriverio/blob/295e71380caa99e5d018f373a6d1ba4701e3867f/lib/utils/ReporterStats.js#L169

This line is being called an incorrect number of times.

`hookStart` and `getHookStats` both call this before the test starts 

This causes the count to increment twice before test one begins. It messes with the Epilogue suite count. Unless there is something I am missing this is incorrect behavior.

**Comment by christian-bromann** [comment]
Hey,

we update the core architecture of WebdriverIO and with that a lot of implementation details that might make this issue obsolete. Please try with the v5 version of WebdriverIO and verify if this still occurs. If so please open a new issue and we will tackle it asap.

Thanks!
