### ISSUE TITLE
When running selected tests using the --spec option, the pattern match is done on the directories as well.

### ISSUE THREAD

**Issue by kmnaid** [webdriverio/webdriverio#2684]
## The problem
When a pattern is passed to the --spec option for filtering, the pattern is matched with directory names as well. [here](https://github.com/webdriverio/webdriverio/blob/master/lib/utils/ConfigParser.js#L166)

When Configparser matches the pattern with directory names and there is a case where the pattern matches a directory name this error occurs:
"<working_directory/pattern>did not match any file"

## Environment

* WebdriverIO version: v4.12.0
* Node.js version: v8.0.0

## Details

Using the webdriverio repo: examples/pageobject
```
bin/wdio examples/pageobject/wdio.conf.js --spec test

pattern ~/webdriverio/test did not match any file
```
The error above is because the '~/webdriverio/test' file which it matched to is a sub-directory in the location from where the test was started and not a spec file as expected.

**Comment by christian-bromann** [comment]
@kmnaid feel free to propose a PR with a fix that checks if the spec is not matching a directory.

**Comment by webOS101** [comment]
Currently, the matching is done before loading the specs all in.  If you were to try to do this any other way, all the specs would have to be loaded and parsed to get the spec names.  To be clear, it -only- matches on directory name.

**Comment by kmnaid** [comment]
It does contain a spec file, but it thinks that the directory itself is a test file and throws the error.
You could reproduce the issue by adding a test file (checkthistest.spec.js) into the test directory in the root directory of the webdriverio repo  and then trying to run a spec file.

``` 
ls
CHANGELOG.md      CONTRIBUTING.md   LICENSE-MIT       bin               docs              index.js          match.js          package-lock.json test
CONDUCT.md        GOVERNANCE.md     README.md         build             examples          lib               node_modules      package.json

ls test/
checkthistest.spec.js conf                  fixtures              mocha.opts            setup-unit.js         setup.js              site                  spec

bin/wdio examples/pageobject/wdio.conf.js --spec test```

**Comment by webOS101** [comment]
I am able to reproduce this problem using `--spec test`.  The default handling of checking if the specified spec exists could be expanded to reject directories.  I'll whip that up.

**Comment by kmnaid** [comment]
@webOS101 : Do you mind if I open a PR for it, I was working on it.
