### ISSUE TITLE
phantomjs not working in webdriverio together with selenium-standalon 6.13.0

### ISSUE THREAD

**Issue by Emilez** [webdriverio/webdriverio#2686]
## The problem

The problem is that when I run phantomjs with the combination of webdriverio and selenium-standalone it launches chrome instead together with an error message. 

I have posted the complete issue in selenium-standalone:
https://github.com/vvo/selenium-standalone/issues/355

Is this an integration issue between webdriverio and selenium-standalone or simply a selenium-standalone issue?

**Comment by christian-bromann** [comment]
> I verified that it is between version 6.12.0 and 6.13.0 that this issue is introduced.

Definitely a selenium-standalone issue
