### ISSUE TITLE
Automatic screenshots on error?

### ISSUE THREAD

**Issue by max-degterev** [webdriverio/webdriverio#269]
Hi!

I'm trying to set up automatic screenshots creation on error. I have following folder structure:

```
test/
  screenshots/
  suite/
```

I am creating a webdriverio client passing `screenshotPath: "./test/screenshots"` as an option, but that doesn't seem to affect anything.

I was trying to add 

``` coffeescript
client.on('error', (err)-> @capture('error'))
```

but this doesn't get called at all.

The only thing that actually works is 

``` coffeescript
process.on('uncaughtException', (err)-> client?.capture('error'))
```

but sometimes it fails too.

This is an example if a test that fails:

``` coffeescript
  it 'should have correct number of cards', (done)->
    client
      .waitForExist('.p-h-promoted .b-p-list', 3000)
      .isVisible cards, (err, isVisible)-> expect(isVisible).to.have.length(25)
      .isVisible doubleCards, (err, isVisible)-> expect(isVisible).to.have.length(5)
      .call(done)
```

What would be the best way to handle this?

**Comment by shadiabuhilal** [comment]
@suprMax , you can do it by using `afterTest` function in `wdio.conf.js` file, like this:
```JS
/**
     * Function to be executed after a test (in Mocha/Jasmine) or a step (in Cucumber) starts.
     * @param {Object} test test details
     */
    afterTest: function (test) {
        // if test passed, ignore, else take and save screenshot.
        if (test.passed) {
            return;
        }
        // get current test title and clean it, to use it as file name
        var filename = encodeURIComponent(test.title.replace(/\s+/g, '-'));
        // build file path
        var filePath = this.screenshotPath + filename + '.png';
        // save screenshot
        browser.saveScreenshot(filePath);
        console.log('\n\tScreenshot location:', filePath, '\n');
    },
```

**Comment by zeljkofilipin** [comment]
For anybody landing here after a search, @christian-bromann said today at https://gitter.im/webdriverio/webdriverio "the last comment actually nailed it" cc @shadiabuhilal

**Comment by alexandlazaris** [comment]
@shadiabuhilal  - Ahh nice work! This worked for me (albeit, if I had 2 browsers within capabilities, it would error out and screenshot the failure from only 1 browser). 

This code was on webdriver.io however it didn't work for me, no screenshot found:
```
jasmineNodeOpts: {
        defaultTimeoutInterval: 10000,
        expectationResultHandler: function(passed, assertion) {
            if(passed){ return; }
            browser.screenshot('assertionError_' + assertion.error.message + '.png');
        }
    },
```

**Comment by vincebowdren** [comment]
@shadiabuhilal Thanks for that code suggestion. I've got a revised version, after I ran into a problem with saving screenshots like that( if a file already exists with that name, it fails to save the screenshot). The important change is to use a timestamp in the filename:

```
    var path = require('path');
    ...
    afterTest: function (test) {
        // if test passed, ignore, else take and save screenshot.
        if (test.passed) {
            return;
        }
        // Construct file name:
        var browserName = browser.desiredCapabilities.browserName;
        var timestamp = new Date().toJSON().replace(/:/g, '-');
        var filename = 'TESTFAIL_' + browserName + '_' + timestamp + '.png';
        var filePath = path.join(this.screenshotPath, filename);
        // save screenshot
        browser.saveScreenshot(filePath);
        console.log('\tSaved screenshot: ', filePath);
    }
```

Note: I based this code on the webdriverio code (function saveScreenshotSync in webdriverio.js) which takes screenshots when a command errors.

**Comment by jcollum-autodesk** [comment]
I can't get this to work. I'm using Mocha 

```
"@wdio/allure-reporter": "^5.12.0",
        "@wdio/cli": "^5.11.13",
        "@wdio/junit-reporter": "^5.12.1",
        "@wdio/local-runner": "^5.11.13",
        "@wdio/mocha-framework": "^5.11.0",
        "@wdio/runner": "^5.11.13",
        "@wdio/sauce-service": "^5.11.1",
        "@wdio/spec-reporter": "^5.11.7",
        "@wdio/sync": "^5.11.13",
        "chai": "^4.2.0",
        "chromedriver": "^77.0.0",
        "deepmerge": "^4.0.0",
        "geckodriver": "^1.16.2",
        "mocha": "^6.2.0",
        "wdio-chromedriver-service": "^5.0.2",
        "wdio-geckodriver-service": "^1.0.2",
        "wdio-video-reporter": "^1.4.4",
        "wdio-webdriver-service": "^0.1.7",
        "webdriverio": "^5.11.13"
``` 

my code looks like this: 

```
afterTest: function(test) {
		console.log('firing afterTest', '\ntest', test);
		// if test passed, ignore, else take and save screenshot.
		if (test.passed) {
			return;
		}
		console.log('test failed, taking screenshot');
... 
```

But the second `console.log` is never reached, despite 3 of my tests failing. Does this not work with Mocha or something?

**Comment by mgrybyk** [comment]
Why do you think it should work?

Please see an example in docs https://webdriver.io/docs/allure-reporter.html#add-screenshots

**Comment by Shreya76** [comment]
> @suprMax , you can do it by using `afterTest` function in `wdio.conf.js` file, like this:
> 
> ```js
> /**
>      * Function to be executed after a test (in Mocha/Jasmine) or a step (in Cucumber) starts.
>      * @param {Object} test test details
>      */
>     afterTest: function (test) {
>         // if test passed, ignore, else take and save screenshot.
>         if (test.passed) {
>             return;
>         }
>         // get current test title and clean it, to use it as file name
>         var filename = encodeURIComponent(test.title.replace(/\s+/g, '-'));
>         // build file path
>         var filePath = this.screenshotPath + filename + '.png';
>         // save screenshot
>         browser.saveScreenshot(filePath);
>         console.log('\n\tScreenshot location:', filePath, '\n');
>     },
> ```

Hi I am using this code to take screenshot of the failed test. But I see there are few more screenshots taken for the passes tests as well. It starts with the name ERRORCHROME.
I tried to comment AtrerTest{} ,  still the screenshot is been taken and stored in the same location.
Please help me on this.
