### ISSUE TITLE
Unexpected Element Scoping in Custom Command

### ISSUE THREAD

**Issue by NicholasRoge** [webdriverio/webdriverio#2690]
## The Problem

Element command being scoped when another element command was the last command to be issued on the same wdio client instance from within a custom command.

## Environment

* WebdriverIO version:  4.12.0
* Node.js version: 9.3.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): wdio-screenshot

## Details

N/A

## Link to Selenium/WebdriverIO logs

[Log](https://gist.github.com/NicholasRoge/9171e7463560f8f2991b948789f7b5ae)

## Code To Reproduce Issue
Test Case
```js
describe('Element command', function () {
    before(() => browser.url('https://www.google.com/'))

    it('should not scope unchained, consecutive element commands', function () {
        expect(browser.element('body').state).to.equal('success')
        expect(browser.element('body').state).to.equal('success') 
    })

    it('should not scope unchained, consecutive element commands in custom commands', function () {
        browser.foo(function () {
            expect(browser.element('body').state).to.equal('success')
            expect(browser.element('body').state).to.equal('success') // Assertion fails here with error "expected 'failure' to equal 'success'"
        })
    })
})
```

Test Runner Config File
```js
exports.config = {
    ...
    before() {
        browser.addCommand('foo', function (callback) {
            callback.apply(this, [])
        })
    }
    ...
}
```

**Comment by NicholasRoge** [comment]
Currently using `this.execute(function(){})` between consecutive element commands to cause lastResult to no longer be an element result and mask the issue.

**Comment by christian-bromann** [comment]
Hey,

we update the core architecture of WebdriverIO and with that a lot of implementation details that might make this issue obsolete. Please try with the latest version of WebdriverIO and verify if this still occurs. If so please open a new issue and we will tackle it asap.

Thanks!
