### ISSUE TITLE
waitForVisible() does not work with multiple elements selected by selector and reverse=true

### ISSUE THREAD

**Issue by dolezaljan** [webdriverio/webdriverio#2692]
## The problem

I used waitForVisible with the reverse set to true and with the selector selecting multiple elements.

I guess waitForVisible uses internally isVisible which returns array of booleans representing visibility of elements matched by selector.

Now I expected waitForVisible to check this array not to contain any truthy value (i.e. no element matches) and only then it should proceed further or fail after timeout, so when I console.log the isVisible applied on the same selector right after the call to waitForVisible, I should get [false, false] but instead it does not wait for all the elements not to be visible so e.g. [true, false] appears in the console.

The [documentation](http://webdriver.io/api/utility/waitForVisible.html#Parameters) states in details of the selector 'element to wait for' not 'element/s to wait for', but still I would expect the call to work on multiple values as well.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: v8.9.3
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable): N/A

## Original Code
```
browser.waitForVisible(this.selector.dropdown, 1000, true);
```
## Expected Behavior of the waitForVisible rewritten with waitUntil (utilizing lodash)
```
browser.waitUntil(() => {
      let dropdownVisibility = browser.isVisible(this.selector.dropdown);
      if (Array.isArray(dropdownVisibility)) {
        return !_.includes(dropdownVisibility, true);
      } else {
        return !dropdownVisibility;
      }
    }, 1000, 'Dropdown should have disappeared');
};
```

**Comment by christian-bromann** [comment]
@dolezaljan thanks for reporting this issue. We are currently working on releasing a new version (v5) which will make this issue obsolete. In v5 you need to fetch an element first to call specific element methods on them. You the only way you are able to wait until a list of elements will be visible is the following:

```js
const elems = $$('.someElems')
browser.waitUntil(() => {
  return elems.map((elem) => elem.isDisplayed()).length > 1
})
```

**Comment by razielron** [comment]
HI there, so I faced this issue as well and also saw it here (please let me know what you think of it and if you have better suggestions) under limitations.
I think I have a solution for this by adding an array prototype you can wait until you get the specific index of an element you need.
```
Array.prototype.get = function(i, timeout = 60000) {
            return browser.waitUntil(() => {
                const elems = $$(this.selector);
                return (elems.length >= i - 1) ? elems[i] : false;
            }, {timeout});
        };
```

Let me know what you think and if it's helpful.
To use it all you need is to do this:
```
$$(locator).get(2).click() //will wait until there are 3 or more elements in that array and than clicking the 3rd one
```

**Comment by justsolarry** [comment]
> @dolezaljan thanks for reporting this issue. We are currently working on releasing a new version (v5) which will make this issue obsolete. In v5 you need to fetch an element first to call specific element methods on them. You the only way you are able to wait until a list of elements will be visible is the following:
> 
> ```js
> const elems = $$('.someElems')
> browser.waitUntil(() => {
>   return elems.map((elem) => elem.isDisplayed()).length > 1
> })
> ```

@christian-bromann Hi - You mention that this is done in v5. Would you mind pointing me in the right direction in how to implement this in v7?

Thanks

**Comment by christian-bromann** [comment]
> Would you mind pointing me in the right direction in how to implement this in v7?

If you run WDIO testrunner in sync mode this should still work as is.
