### ISSUE TITLE
getHTML() doesn't poll when browser.timeouts('implicit', X) is set

### ISSUE THREAD

**Issue by glukki** [webdriverio/webdriverio#2694]
## The problem
When `browser.timeouts('implicit', X)` is set, [`getHTML(selector)`](https://github.com/webdriverio/webdriverio/blob/master/lib/commands/getHTML.js#L54) doesn't wait for element.
Because it doesn't call `this.element(selector)`, as [`click()`](https://github.com/webdriverio/webdriverio/blob/master/lib/commands/click.js#L54) does, for example.

Workaround is `browser.element(selector).getHTML()`, but it's longer than it could be.

Is it by design?
Will fix of it make tests less stable, as dynamic block may be rendered gradually, instead of atomic?

## Runtime error
```
An element could not be located on the page using the given search parameters (".test").
```

## Environment
* WebdriverIO version: 4.12.0
* Node.js version: v6.13.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable): `wdio-chromedriver-service`, `wdio-mocha-framework`, `wdio-spec-reporter`

## Code To Reproduce Issue
```js
// page
setTimeout(() => {
  const node = document.createElement('div');
  node.className = 'test';
  node.innerHTML = '<a href="#">click me</a>';
  document.body.appendChild(node);
}, 1000)

// test.spec.js
it('expected to pass, but fail', () => {
  browser.timeouts('implicit', 5000);
  assert.ok(browser.getHTML('.test'))
})
it('workaround will pass', () => {
  browser.timeouts('implicit', 5000);
  assert.ok(browser.element('.test').getHTML())
})
```

**Comment by christian-bromann** [comment]
> Is it by design?

In the first place yes. Now it can be changed so we pass in the queried element into the execute command to get the html. We will fix this with the upcomming version v5
