### ISSUE TITLE
Getting selected values from multi select

### ISSUE THREAD

**Issue by helenwilliamson** [webdriverio/webdriverio#2696]
## The problem

I have a multi select on a page that I'm testing with webdriver.io. How do I get the selected options from that element? I can't see anything obvious in the webdriver API documentation for dealing with multi selects.

## Environment

* WebdriverIO version: 4.12.0
* Node.js version: 8.11.1
* Standalone mode or wdio testrunner: standalone

**Comment by christian-bromann** [comment]
Try `getValue`. 
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
