### ISSUE TITLE
Unable to use swipe on webpage

### ISSUE THREAD

**Issue by psmod2** [webdriverio/webdriverio#2699]
## The problem

I have a webpage that allows swiping left and right over elements to remove them - think the swipe left on iOS Mail app to delete a message.

However I can't seem to perform this action. I'm unable to use the mobile emulation mode as it effects a specific user agent I need to set.

I've tried a variety of things assuming it would have been as simple as using `swipeLeft()` however nothing worked. Interesting I found that `swipeLeft(170)` - where 170 was approx half the screen's width partially worked however when it got to the end and the item was removed (as expected) I get an error along the lines the element is not available (but I'd expect this).

It's as if I need a method that just swipes over that part of the screen I specify then ignore whatever it is swiping over.

Is this an issue with WDIO or is there something more I need to understand here?

## Environment

* WebdriverIO version: 4.10.1
* Node.js version: 8.10.0
* wdio testrunner - synchronous

**Comment by christian-bromann** [comment]
@psmod2 have you tried to use the touchAction command? Depending on the automation backend some commands might not be supported.

**Comment by psmod2** [comment]
@christian-bromann Thanks - I'll give it a go however am skeptical it may not work as stated here:

http://webdriver.io/api/mobile/touchAction.html

"can not be used to interact with webapps"

Wish there was some way.
