### ISSUE TITLE
waitForPopup?

### ISSUE THREAD

**Issue by max-degterev** [webdriverio/webdriverio#270]
I'm trying to figure out, is it possible to have a waitForPopup command somehow? I know that it's impossible to get opened popups from browser console without having a reference first, but maybe there is another way? This would be very useful for scenarios including facebook login

**Comment by aaronbriel** [comment]
Hi everybody - sorry if I'm late to the party with this comment!  I seem to be having issues here when I attempt to switch back to the main window tab.  Namely, subsequent webdriverio calls fail with "Uncaught RuntimeError: no such window: target window already closedfrom unknown error: web view not found".  Have any of you seen this and / or know of a possible resolution?  Thanks!
