### ISSUE TITLE
How to click on print button of print window in chrome browser ?

### ISSUE THREAD

**Issue by nitinsharma09** [webdriverio/webdriverio#2700]
## The problem
How to click on print or save button of printing window in chrome browser using webdriverio.

## Environment
* WebdriverIO version: 4.9.11

**Comment by christian-bromann** [comment]
@nitinsharma09 not sure what you want to automate but you can't and shouldn't test the print functionality of the browser. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
