### ISSUE TITLE
Running a bunch of suites in a single command sequentially

### ISSUE THREAD

**Issue by ArnauRius** [webdriverio/webdriverio#2703]
Hello,
I am not able to run one suite after another (without executing manually one after the other). If I execute: ./node_modules/.bin/wdio wdio.dev.conf.js --suite login,register,song,song_play. It opens 4 browsers (one per suite). Actually I have more than 30 suites, so running all the suites results in a computer stuck. There is some way to do that? 
Thanks.

**Comment by christian-bromann** [comment]
> There is some way to do that?

Well as you imagine, opening 30 browser at the same time will heavily impact your CPU if you run it locally. You can use the `maxInstances` option to make sure only a certain amount of browser are opened at the same time.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
