### ISSUE TITLE
Error: Cannot find module '../../build/index'

### ISSUE THREAD

**Issue by x011** [webdriverio/webdriverio#2705]
I'm getting   `Error: Cannot find module '../../build/index'`  while executing:
`node /webdriver.io/examples/commands/webdriverio.waitForVisible.js`

> module.js:472
>     throw err;
>     ^
> 
> Error: Cannot find module '../../build/index'
>     at Function.Module._resolveFilename (module.js:470:15)
>     at Function.Module._load (module.js:418:25)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/mnt/d/Dropbox/programming/node/webdriver.io/examples/commands/webdriverio.waitForVisible.js:1:81)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)

Any idea why?
```

Node@v7.10.1
webdriverio@v4.12.0
```

**Comment by christian-bromann** [comment]
> Any idea why?

You need to build the project first. 

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
