### ISSUE TITLE
selectByIndex doesn't work on safari browser

### ISSUE THREAD

**Issue by suwi** [webdriverio/webdriverio#2706]
## The problem

selectByIndex fails with error: _An element command could not be completed because the element is not visible on the page._
works fine for chrome, firefox, even IE, **fails on safari browser**

## Environment

* WebdriverIO version: 4.12.0
* Node.js version: v6.13.0
* Additional wdio packages used (if applicable): "wdio-visual-regression-service": "^0.8.0"
I run tests on browserstack

## Code To Reproduce Issue

browser.selectByIndex(dropDownSelector, 1);

**Comment by christian-bromann** [comment]
Looks like a safaridriver related issue. Please open a bug in the safaridriver project.
