### ISSUE TITLE
driver.performTouchAction(new TouchAction(driver).press((int) (coords.getX() / 2), (int) (coords.getY() / 2)).release());

### ISSUE THREAD

**Issue by RenanChagas** [webdriverio/webdriverio#2709]
## The problem

I would like to click an element on the screen solely based on coordinates. I cant inspect elements on the app because was created on unity.
## Environment

WebDri
* WebdriverIO version: Latest
* Node.js version: Latest

## Details

I found examples for Java, C# but not for webdriverIO...

Is that possible?? or a missing feature?

**Comment by christian-bromann** [comment]
Please see the [API](http://webdriver.io/api/mobile/touchAction.html). Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
