### ISSUE TITLE
TouchAction - An unknown server-side error occurred while processing the command

### ISSUE THREAD

**Issue by RenanChagas** [webdriverio/webdriverio#2713]
## The problem

When I try to execute the following command:

```
browser.touchAction({
            action: 'tap', x: 30, y:20
        })
```
The action doesn't do anything and the app closes after.

The log is showed below

## Environment

* WebdriverIO version: Latest
* Node.js version: v8.11.1
* wdio

## Link to Selenium/WebdriverIO logs

Error: An unknown server-side error occurred while processing the command.
    at url() - index.js:267:37
    at init() - runner.js:235:55

**Comment by rtmalone** [comment]
@RenanChagas did you solve this? I receive the same error when using `touchMultiPerform`

**Comment by RenanChagas** [comment]
Hi @rtmalone, Yes, I manage to make it work with this command: 
```
browser.touchPerform([
      { action: 'press', options: { x: 36, y: 335 }},
      { action: 'release' }
    ]);
```
