### ISSUE TITLE
Adding parameters to wdio config file

### ISSUE THREAD

**Issue by kandarp1691** [webdriverio/webdriverio#2714]
## The problem
I am trying to give parameters in my package.json file so when I do a 
`npm run e2e`
it runs with those configurations. However, when i use process.env.VARIABLE, it does not recognize those values. When I set them in my config file, it accepts and runs as expected.
## Environment

* WebdriverIO version: 4.12.0
* Node.js version: 8.9.0
* wdio test runner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):

## Details

I have additional parameters which i specify when doing running the wdio test runner. However, the config file doesn't seem to recognize them. I am unsure why the problem occurs.

## Code To Reproduce Issue [ Good To Have ]

Below are my additional fields in wdio file:

`uri: process.env.uri,
username: process.env.username,
password: process.env.password,`

How I call tests from my wdio file:
`npm run e2e`

`"e2e": "./node_modules/.bin/wdio ./e2e/wdio.conf.local.js --suite functional --uri=uri --username=uname --password=pw"`

[package_json.txt](https://github.com/webdriverio/webdriverio/files/1956500/package_json.txt)

What am I missing here ?

**Comment by christian-bromann** [comment]
> If WDIO doesn't have some argv->env mapping

there is no such mapping.

If you want to parameterise your tests I recommend to use environment variables as @glukki mentions:

```
URI=uri wdio ./e2e/wdio.conf.local.js --suite functional
```

and then access it via `process.env.uri`.

**Comment by kandarp1691** [comment]
```

uri=http://xx.engprod-xx.net/api wdio ./e2e/wdio.conf.local.js --suite functional

'uri' is not recognized as an internal or external command,
operable program or batch file.
```
As mentioned earlier, I am declaring uri in my wdio file 
`uri: process.env.uri`

**Comment by glukki** [comment]
Learning how to set environment variables in your OS might help

**Comment by kandarp1691** [comment]
My purpose is to avoid setting env variables locally so I do not need to
set them while running via CI/CD

**Comment by Sashtim** [comment]
> ```
> 
> uri=http://xx.engprod-xx.net/api wdio ./e2e/wdio.conf.local.js --suite functional
> 
> 'uri' is not recognized as an internal or external command,
> operable program or batch file.
> ```
> 
Hello
I just had the same problem and the cause of it is that Windows doesn't work with such a command line.
There is a solution here:
https://www.npmjs.com/package/cross-env
Hopefully, it will be helpful for somebody else.
