### ISSUE TITLE
[Feature] Only run Caps that are passed thru Argv for Launcher. 

### ISSUE THREAD

**Issue by rajapanidepu** [webdriverio/webdriverio#2715]
## The problem

Feature request:
Only run tests on capabilities that are being passed as agrv to Launcher. 
Instead of merging, I would like to run tests on capabilities that are read from Argv.

https://github.com/webdriverio/webdriverio/blob/master/lib/launcher.js#L11
https://github.com/webdriverio/webdriverio/blob/master/lib/utils/ConfigParser.js#L150

Or is there a specific reason for merging the capabilities. 

## Environment

* WebdriverIO version: webdriverio@4.12.0
* Node.js version: v8.9.4
*  wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable):

## Details
- ConfigFile contains caps: {browser: 'firefox'};
- I would like to do: 
new Launcher(configFile, {capabilities: [{browser: 'chrome'}]);
So that the tests are only ran on new Caps that are passed. 

Current behavior:  Caps get merged and tests are run on both the caps.

**Comment by christian-bromann** [comment]
Hey,

we update the core architecture of WebdriverIO and with that a lot of implementation details that might make this issue obsolete. Please try with the v5 version of WebdriverIO and verify if this still occurs. If so please open a new issue and we will tackle it asap.

Thanks!
