### ISSUE TITLE
Disable Chrome clipboard popup/notification WebdriverIO

### ISSUE THREAD

**Issue by vallabhpingle** [webdriverio/webdriverio#2718]
I'm trying to disable the chrome clipboard popup/notification using webdriverIO (Selenium) for automation. I tried setting chrome options/preferences but still it doesn't disable it. I want to click a web element that is behind this popup, so I don't want this popup to appear in automation. I tried disabling the clipboard settings manually but selenium opens a new session every time which refreshes the settings. Also, it is not possible to inspect using developer tools. It is not an alert so accepting/dismissing alert does not work either.

Versions i’m using:
Chrome Browser: 66.0.3359.117
Node: 8.9.4
npm: 5.8.0
chrome driver: 2.38

    browser.alertAccept();
or
    browser.alertDismiss();

    chromeOptions: {
        args: [
            'disable-infobars',
            'disable-popup-blocking',
            'disable-notifications'
        ],
        prefs: {
            'profile.default_content_settings.popups' : 2,
            'profile.default_content_settings.notifications' : 2,
        }
    }

Please help me with this issue, any help would be really appreciated.
![chromeclipboardissue](https://user-images.githubusercontent.com/26423071/39443787-7ecc01f4-4c6a-11e8-9e8e-5ed7f4f4f434.png)

**Comment by vallabhpingle** [comment]
Anyone found any solution? please help!

**Comment by christian-bromann** [comment]
I will close this since it is not a WebdriverIO related issue. I am not sure how to manage Chrome to disable such pop ups. I recommend to open an issue in Chromium. If anyone finds a solution please let us know.

**Comment by huaphuoctruong** [comment]
@vallabhpingle have you solved the issue? Just find out that you need to do as follows

```
chromeOptions           : {
            prefs: {
                'profile.managed_default_content_settings.popups' : 2,
                'profile.managed_default_content_settings.notifications' : 2,
            }
        }
```

**Comment by tompipl** [comment]
any updates on this? none of what was offered here is working for me.

**Comment by xparpx** [comment]
Hi,

This working for me. I want accept notifications and Pop Ups. There are no notifications on my tests now. I insert these options inside wdio.conf.js :

`capabilities: [{
        maxInstances: 1,

        browserName: 'chrome',
        'goog:chromeOptions': {
            prefs: {
                'profile.managed_default_content_settings.popups' : 1,
                'profile.managed_default_content_settings.notifications' : 1,
            }
        }

    }],`

I found on https://github.com/dinuduke/Selenium-chrome-firefox-tips that if you want allow popus and notifications you should define with **1**.

**Comment by nanomosfet** [comment]
None of these worked for me....

**Comment by mangena-dave** [comment]
Hi all

I managed getting it working for me, I insert these options inside wdio.conf.js 
`    capabilities: [{
        browserName: 'chrome',
        'goog:chromeOptions': {
            args: [
                'disable-infobars',
                'disable-popup-blocking',
                'disable-notifications'
            ],
        }   
    }],`

**Comment by Sk27** [comment]
@mangena-dave you are the true MVP

**Comment by mangena-dave** [comment]
Thanks @Sk27 :)

**Comment by pedro-perez-islas** [comment]
Thanks **@xparpx**

It works for me :D

**Comment by AtishAmrit** [comment]
> Hi,
> 
> This working for me. I want accept notifications and Pop Ups. There are no notifications on my tests now. I insert these options inside wdio.conf.js :
> 
> ```
> capabilities: [{
>         maxInstances: 1,
>         browserName: 'chrome',
>         'goog:chromeOptions': {
>             prefs: {
>                 'profile.managed_default_content_settings.popups' : 1,
>                 'profile.managed_default_content_settings.notifications' : 1,
>             }
>         }
> 
>     }], ... 
> ```
> 
> I found on https://github.com/dinuduke/Selenium-chrome-firefox-tips that if you want allow popus and notifications you should define with **1**.

This worked perfectly for me. Thanks

**Comment by AtishAmrit** [comment]
> goog:chromeOptions': { args: [ 'disable-infobars', 'disable-popup-blocking', 'disable-notifications' ], }

It disabled the popup but infobar is still getting displayed

**Comment by mangena-dave** [comment]
> > goog:chromeOptions': { args: [ 'disable-infobars', 'disable-popup-blocking', 'disable-notifications' ], }
> 
> It disabled the popup but infobar is still getting displayed

Try adding 'profile.managed_default_content_settings.infobar : 1, in the prefs scope.
Although I have not tried the above line, but reading the code should work.

**Comment by AtishAmrit** [comment]
> > > goog:chromeOptions': { args: [ 'disable-infobars', 'disable-popup-blocking', 'disable-notifications' ], }
> > 
> > 
> > It disabled the popup but infobar is still getting displayed
> 
> Try adding 'profile.managed_default_content_settings.infobar : 1, in the prefs scope.
> Although I have not tried the above line, but reading the code should work.

Tried, still the infobar "Chrome is being controlled by automated test software" is present

**Comment by tonychangcheng** [comment]
How can I disable a dialog that would open an app? As you can see from the below screenshot.

[Chrome external dialog](https://i.stack.imgur.com/5drKO.png)

**Comment by amekhedka** [comment]
capabilities: [{
        maxInstances: 1,
        browserName: 'chrome',
        "goog:chromeOptions": {
            args:[
                'disable-infobars',
                'disable-popup-blocking',
                'disable-notifications'
            ],
            prefs: {
                'profile.managed_default_content_settings.popups' : 2,
                'profile.managed_default_content_settings.notifications' : 2,
            }
        }
    }],
    
    I tried and it doesn't work for me :(

**Comment by louis57** [comment]
For the latest Chrome version, I use this:

```
'goog:chromeOptions': {
     excludeSwitches: [
         'enable-automation',
     ],
 },
```
and the info bar "Chrome is being controlled by ..."  is no longer displayed.

**Comment by VladSelikh** [comment]
@amekhedka Try using puppeteer browser to set this permission:
```
const puppeteerBrowser = await browser.getPuppeteer();
  await browser.call(async () => {
    const context = puppeteerBrowser.browserContexts()[0];
    await context.overridePermissions(await browser.getUrl(), ['clipboard-read']);
  });
```
You can use this code in the hooks for example of directly before the action that triggers Share Clipboard popup
More info here:
https://github.com/webdriverio/webdriverio/discussions/10810

**Comment by christian-bromann** [comment]
You should be able to allow this without Puppeteer in the mix, check out `setPermission` command, I don't have an example for this yet though.

**Comment by VladSelikh** [comment]
@christian-bromann Yes, here it is:
```
// set clipboard permissions
browser.setPermissions({ name: 'clipboard-read' }, 'granted');
// now you can read the clipboard via, e.g.
const clipboardText = await browser.execute(() => navigator.clipboard.readText());
```
As per:
https://webdriver.io/docs/api/webdriver/#setpermissions

**Comment by Mongoid3raylan** [comment]
https://lnkr.fun/297bdcb I tackled the same difficulty and arrived at a solution
