### ISSUE TITLE
 client.logs('browser') only works with chrome browser

### ISSUE THREAD

**Issue by DDeepu** [webdriverio/webdriverio#2719]
## The problem

 client.logs('browser') only works with chrome . Is there a way to check java script console errors in edge browser??

## Environment

* WebdriverIO version: 4.12.0
* Node.js version: 5.5.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): standalone mode

code snippet that i am using for catching chrome console errors.

browser.log('browser').then((res) => {
                    res.value.forEach( (element) => {
                        expect(element.level).not.toBe('ERROR');
                    });
                    console.log('result: ', res)
                })
                .catch( (err) => {
                    console.log(err);
                })

**Comment by erwinheitzman** [comment]
Join our  Gitter for these kind of questions. This is not necessary an issue.
