### ISSUE TITLE
Safari: probably xPath functions contains() and/or text() not work

### ISSUE THREAD

**Issue by rdpanek** [webdriverio/webdriverio#2720]
## The problem

Hi, any idea why this xpath not function in Safari webdriver? but in chrome is OK.
`"//text()[contains(.,'SomeText')]/parent::*"`
`"//h2[text()[contains(.,'SomeText')]]"`
`"//h2[contains(text(),'SomeText')]"`

but directly in Safari ( open manually Safari > Develop > Show Javascript Console) these xpaths work?
I have suspicious of a faulty implementation feature contains or/and text.

## Environment
 
*  "webdriverio": "^4.12.0"
* "wdio-mocha-framework": "^0.5.13",
* node -v = v9.8.0
* [wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
* wdio testrunner, running synchronous:

## Link to Selenium/WebdriverIO logs
https://gist.github.com/rdpanek/48bb5dba9d86a9a9308e736a273bec06

## Code To Reproduce Issue [ Good To Have ]
```
it("test step", () => {
  const xpathSelector = "//h2[contains(text(),'SomeText ')]"
  browser.waitForExist(xpathSelector)

  browser.scroll(xpathSelector, 0, -250)
  browser.pause(3000)
  browser.waitForVisible(xpathSelector)
  browser.click(xpathSelector)
})
```
Commands waitForExist and scroll work correctly, but waitForVisible and click no.
```
00:50:46.202 INFO - To upstream: {"using":"xpath","value":"//h2[contains(text(),'SomeText')]"}
00:50:46.205 INFO - To downstream: {"status":0,"sessionId":"5490DE85-4B33-4EA7-BCE2-9501EEEA62C8","value":[{"ELEMENT":"node-66B75EB7-F972-4421-BE79-C9688BC2C472"}]}
00:50:46.207 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@61726b5a
00:50:46.208 INFO - Handler thread for session 5490DE85-4B33-4EA7-BCE2-9501EEEA62C8 (safari): Executing GET on /session/5490DE85-4B33-4EA7-BCE2-9501EEEA62C8/element/node-66B75EB7-F972-4421-BE79-C9688BC2C472/displayed (handler: ServicedSession)
00:50:46.211 INFO - To downstream: {"status":0,"sessionId":"5490DE85-4B33-4EA7-BCE2-9501EEEA62C8","value":false}
00:50:46.308 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@61726b5a
00:50:46.308 INFO - Handler thread for session 5490DE85-4B33-4EA7-BCE2-9501EEEA62C8 (safari): Executing DELETE on /session/5490DE85-4B33-4EA7-BCE2-9501EEEA62C8 (handler: ServicedSession)
00:50:46.310 INFO - To downstream: {"status":0,"sessionId":"5490DE85-4B33-4EA7-BCE2-9501EEEA62C8","value":{}}
00:50:46.310 INFO - Removing session org.openqa.selenium.remote.server.ServicedSession@61726b5a
00:50:46.312 INFO - To downstream: A session with id = '5490DE85-4B33-4EA7-BCE2-9501EEEA62C8' was not found.
```

**Comment by honzakubis** [comment]
Hi, i have same problem.. @christian-bromann pls can you check?

**Comment by christian-bromann** [comment]
@rdpanek @honzakubis if things work in Chrome but not in Safari it is a good indicator that the driver does something wrong. Please report this bug in the Safaridriver project. Thanks!
