### ISSUE TITLE
Safari screenshots generated when using Chrome with --headless

### ISSUE THREAD

**Issue by yebrahim** [webdriverio/webdriverio#2722]
## The problem
I'm running visual regression tests with the following section in my wdio.config.js:
```
  capabilities: [{
    maxInstances: 5,
    browserName: 'chrome',
    chromeOptions: {
      args: headless ? ['--headless', '--disable-gpu', '--window-size=1024,800'] : [],
    },
  }],
```
If and only if `headless` is true, adding the argument to the Chrome process, screenshots get generated for both Chrome and Safari.

## Environment

* WebdriverIO version: 4.12.0
* Node.js version: 8.11.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Standalone
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):
  * wdio-dot-reporter
  * wdio-jasmine-framework
  * wdio-selenium-standalone-service
  * wdio-visual-regression-service
  * wdio-webcomponents
  * webdrivercss

## Link to Selenium/WebdriverIO logs
https://gist.github.com/yebrahim/f1662da9f2081a984bc7b0dc6abaf896

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]
See above

**Comment by christian-bromann** [comment]
@yebrahim hey! I think chrome args have to be set without `--` like:

```js
  capabilities: [{
    maxInstances: 5,
    browserName: 'chrome',
    chromeOptions: {
      args: headless ? ['headless', 'disable-gpu', 'window-size=1024,800'] : [],
    },
  }],
```

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by yebrahim** [comment]
Will do, thanks.

**Comment by anto-wahanda** [comment]
This is happening to me as well. I am passing the `chromeOptions` like this (by the way, the wdio documentation needs updating to reflect the change to `goog:chromeOptions`.

```
{
  "args": [
    "--headless",
    "--disable-gpu"
  ]
}
```

I can see the options are passed through and working, but `context.browser.name` returns Safari.

**Comment by anto-wahanda** [comment]
Issue also reported here: https://github.com/webdriverio/webdriverio/issues/2798

**Comment by christian-bromann** [comment]
where does `context.browser.name` comes from?

**Comment by anto-wahanda** [comment]
Good question. I would have to look into it, but it is what the example in the documentation uses:

http://webdriver.io/guide/services/visual-regression.html#Configuration

**Comment by christian-bromann** [comment]
so it does not come from WebdriverIO and can't be fixed here

**Comment by anto-wahanda** [comment]
Right. It's an issue with https://github.com/zinserjan/wdio-visual-regression-service

**Comment by yebrahim** [comment]
Yup, +1 for closing this one.
