### ISSUE TITLE
find element by view id for android

### ISSUE THREAD

**Issue by fantasyRqg** [webdriverio/webdriverio#2723]
Why not support find element by view id

**Comment by christian-bromann** [comment]
Are you talking about accessibility id? Please see [here](http://webdriver.io/guide/usage/selectors.html#Accessibility-ID). You can also just choose a selector strategy, e.g.

```js
browser.click("<strategy>:<selector>")
```

**Comment by christian-bromann** [comment]
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
