### ISSUE TITLE
Trouble locating element using moveToObject

### ISSUE THREAD

**Issue by akhilabs** [webdriverio/webdriverio#2729]
## The problem

div:

<div class="chart-container" data-reactid=".8.$content.1:$sheet.1.0.0.0:$e91a92ac-187b-4f08-bc3a-1c50c2678210.1.0.0.3.1.2.0" _echarts_instance_="1525986143967" style="-webkit-tap-highlight-color: transparent; user-select: none; cursor: default; background-color: rgba(0, 0, 0, 0);">

webdriverio:
browser.moveToObject('.chart-container', 0, 0).then(callback); 

error:
An element could not be located on the page using the given search parameters.
running firefox
Error: An element could not be located on the page using the given search parameters.
    at moveToObject(".chart-container", 0, 0) - at element(".chart-container") - moveToObject.js:47:17

## Environment

* WebdriverIO version: v4.12.0
* Node.js version: v8.11.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Details

I am unable to access this div by using moveToObject. I tried accessing using xPath, class name and nothing worked. Any help is appreciated.

## Code To Reproduce Issue [ Good To Have ]

browser.moveToObject('.chart-container', 0, 0).then(callback);

**Comment by christian-bromann** [comment]
Looks like the element with the selector `.chart-container` doesn't exist. This is not an issue. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have further questions.
