### ISSUE TITLE
Can't iterate over elements

### ISSUE THREAD

**Issue by jgauna** [webdriverio/webdriverio#273]
I read many times the documentation but I can't iterate over elements:

```
var runner = webdriverjs
    .remote(options)
    .init()
    .url("http://www.google.com")
    .getTagName('a')
```

And after that I want to perform an action on every 'a' tag.

Is there a way to do this?

Thanks!

**Comment by vdineva** [comment]
The right syntax is below. Hope this helps somebody in the future

var runner = webdriverjs
    .remote(options)
    .init()
    .url("http://www.google.com")

     // fetch elements
    .elements('a', function(err, res){
        // iterate through elements
        res.value.forEach(function(elem) {
            // execute specific action
            runner.elementIdClick(elem.ELEMENT, function(err, res) {
                 // callback logic here
                 // ...
            })
        })
    })

**Comment by christian-bromann** [comment]
@vdineva thanks. Corrected my version as well

**Comment by binarykitchen** [comment]
Mmmmh, and do you have a promises-oriented version handy for the above? @vdineva @christian-bromann ... somehow I fail to do the same with promises. Thx

**Comment by zerbons** [comment]
did you figure it out @binarykitchen ? would also be interested @christian-bromann

**Comment by christian-bromann** [comment]
here is a version that should work in the current version:

```js
var q = require('q');
var clicks = [];
var runner = webdriverjs.remote(options);

runner
    .init()
    .url("http://www.google.com")

     // fetch elements
    .elements('a').then(function(res){
        // iterate through elements
        res.value.forEach(function(elem) {
            clicks.push(runner.elementIdClick(elem.ELEMENT));
        });

        return q.all(clicks);
    })
```

**Comment by binarykitchen** [comment]
thanks @christian-bromann, your example works like a charm

**Comment by cruiser12** [comment]
how could i run this sequential. q.all is running them all at once.

**Comment by christian-bromann** [comment]
@cruiser12 join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions.
