### ISSUE TITLE
Requirement: Distribute test to available devices

### ISSUE THREAD

**Issue by Vishnu1067** [webdriverio/webdriverio#2740]
## The problem

I have 100 test cases and 5 simulators. Instead of running all 100 test in 5 simulators, i would need to distribute the test cases to available simulators.

## Details

Can we have a following keywords in config file;

Parallel - Run all test in all available devices parallel.
Distribute - Run all test in available devices distributed to save time.

**Comment by christian-bromann** [comment]
This should be done by using a Selenium Hub server which can distribute the tests to all devices. If not all devices are available you should use the `maxInstances` option to limit the number of parallel runs. If you have more questions join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
