### ISSUE TITLE
Needs New Argument Parser Dependency for  CLI Runner

### ISSUE THREAD

**Issue by emilyrohrbough** [webdriverio/webdriverio#2742]
## The problem

The CLI runner uses the npm package [optimist](https://www.npmjs.com/package/optimist) to parse the process arguments, however this package is deprecated and the owner suggests the use of [minimist](https://www.npmjs.com/package/minimist). Wdio needs to update to this, or a non-deprecated dependency.

## Environment

* WebdriverIO version: 4.12.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): CLI Runner

**Comment by christian-bromann** [comment]
This is fixed in v5 of WebdriverIO. I am not planning to update this for v4.x. Feel free to propose a PR though. Thanks for pointing this out.

**Comment by emilyrohrbough** [comment]
Great. I have read at one point that the timeline for v5 is unannounced. Is this still the case? Additionally, is there an issue to track or a PR to link to for this work?

**Comment by christian-bromann** [comment]
> Is this still the case?

Yes. We hope sometime within the next month.

> Additionally, is there an issue to track or a PR to link to for this work?

We have already implemented the `wdio-cli` package that uses the `yargs` package. No issue required.
