### ISSUE TITLE
Use attribute as an element selector for "element with certain text" strategy

### ISSUE THREAD

**Issue by glukki** [webdriverio/webdriverio#2743]
## The problem

We rely on `[data-test-*]` selectors in our tests, as it's a common and recommended pattern: https://embermap.com/video/ember-test-selectors
Current strategies doesn't support selectors like `[data-test-button]*=Submit`.
Instead I get `Error: invalid selector: An invalid or illegal selector was specified`.

I could make a PR fixing that, if it would be accepted.

## Environment

* WebdriverIO version: 4.12.0
* Node.js version: 10.1.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous

**Comment by christian-bromann** [comment]
> I could make a PR fixing that, if it would be accepted.

Feel free to do so. This custom selector only supports a class or element before the equal sign (e.g. `.foobar*=Submit`). For more extended use cases feel free to just create an xPath.

**Comment by iamatharva** [comment]
> ## The problem
> We rely on `[data-test-*]` selectors in our tests, as it's a common and recommended pattern: https://embermap.com/video/ember-test-selectors
> Current strategies doesn't support selectors like `[data-test-button]*=Submit`.
> Instead I get `Error: invalid selector: An invalid or illegal selector was specified`.
> 
> I could make a PR fixing that, if it would be accepted.
> 
> ## Environment
> * WebdriverIO version: 4.12.0
> * Node.js version: 10.1.0
> * [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
> * if wdio testrunner, running synchronous or asynchronous tests: synchronous

Is this fixed in v.6?
