### ISSUE TITLE
dragAndDrop() not performing the task

### ISSUE THREAD

**Issue by karthik1407s** [webdriverio/webdriverio#2744]
## The problem
I am trying perform drag and drop on desktop application. The test is getting passed (with deprecation warnings for moveTo, buttonDown and buttonUp commands) but the drag and drop task is not performed. I can see that mouse is pointing to the source element and buttonDown task is performed after that nothing is happening. As actions command is not yet supported by chromedriver, I can not use that too. 
How can I make dragAndDrop work on my application. Or any other alternatives for drag and drop functionality.?
 
Thanks in advance
Karthik
## Environment

* WebdriverIO version:4.12.0
* Node.js version: 8.11.1
* OS: windows 10

## Code To Reproduce Issue [ Good To Have ]
[dragAndDrop.txt](https://github.com/webdriverio/webdriverio/files/2030577/dragAndDrop.txt)

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
> How can I make dragAndDrop work on my application. Or any other alternatives for drag and drop functionality.?

If you automate a Firefox you want to use the action command. In Chrome the dragAndDrop command sometimes work depending on how it is implemented. We are working on getting it working cross browser with the next version. If you have more questions join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). Thanks!
