### ISSUE TITLE
`Cannot read property 'ELEMENT' of null` when using page objects in hooks.

### ISSUE THREAD

**Issue by yeou** [webdriverio/webdriverio#2745]
## The problem
When I try to use beforeSuite I always receive the error: `Cannot read property 'ELEMENT' of null`
Together with @ringods we have already filed an issue at cucumber: https://github.com/webdriverio/wdio-cucumber-framework/issues/124

## Environment
Same as the livecoding repo.
Node: v8.11.1
Npm: 5.6.0

## Code To Reproduce Issue 
https://github.com/yeou/saucecon-talk-2018-livecoding

**Comment by yeou** [comment]
@christian-bromann Could you reproduce the issue? 
Feel free to ask if you need additional information.

**Comment by christian-bromann** [comment]
I was not and I don't have the time to look into this. Feel free to propose a fix for this. I think this will be resolved in v5 on which I am mostly working atm.

**Comment by yeou** [comment]
Where can we find the code for v5?
Is there any documentation if I want to investigate this bug myself? Or could you point us in the right direction? Which would be the first place to start investigating?

**Comment by christian-bromann** [comment]
> Is there any documentation if I want to investigate this bug myself?

The code ;-)

> Or could you point us in the right direction? Which would be the first place to start investigating?

Not really.

**Comment by christian-bromann** [comment]
Hey,

we update the core architecture of WebdriverIO and with that a lot of implementation details that might make this issue obsolete. Please try with the v5 version of WebdriverIO and verify if this still occurs. If so please open a new issue and we will tackle it asap.

Thanks!

**Comment by ringods** [comment]
@christian-bromann any ETA you have in mind for v5?

**Comment by christian-bromann** [comment]
Soon 😉
