### ISSUE TITLE
Docs improvement

### ISSUE THREAD

**Issue by js-kyle** [webdriverio/webdriverio#2748]
I'd like to submit a PR to improve the documentation for `alertAccept()`, `alertDismiss()` and `alertText()`

https://github.com/webdriverio/webdriverio/blob/e346f59b767ed8c192844671de838c28f230ff94/lib/protocol/alertText.js#L8
Current:
```
    it('demonstrate the alertDismiss command', function () {
        if (browser.alertText()) {
            browser.alertDismiss();
        }
        // ...
    });
```
Problem:

To me, it seems like the above example implies that code execution will continue if `browser.alertText()` returns a falsey value, however it would return a runtime error.

To achieve a similar functionality, I used the below, however I'm not sure if that is the best example to include in the documentation. Thoughts? I can submit a PR once the preferred approach to document is agreed

```
try {
   browser.alertDismiss();
} catch (e) {
  // no alert was open, continue
}
```

**Comment by christian-bromann** [comment]
Feel free to propose a PR
