### ISSUE TITLE
Marking each test in a suite as a test on Sauce Labs

### ISSUE THREAD

**Issue by kandarp1691** [webdriverio/webdriverio#2750]
## The problem

I have a suite of test which has 10 tests. Each suite starts with a describe() and each test starts with an it() as shown below:

```
describe('Suite of test', function(){
  it('Test 1', function(){
  
  }),

  it('Test 2', function(){
  
  }),

  it('Test 3', function(){
  
  })
})
```
Now in a case where Test 3 fails, sauce shows status failed with 
`Test Failed : Test 1`

Is there any way to make sure that the failure message shows the correct message ?

## Environment

* WebdriverIO version: 4.12.0
* Node.js version: 10.0.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):

**Comment by christian-bromann** [comment]
> sauce shows status failed with

What do you mean by that? Screenshots? Do you use wdio-sauce-service?

**Comment by kandarp1691** [comment]
￼￼￼
<img width="1298" alt="screen shot 2018-05-25 at 9 22 36 am" src="https://user-images.githubusercontent.com/10793598/40552601-72500a28-5ffd-11e8-9e65-addd2e860012.png">
<img width="662" alt="screen shot 2018-05-25 at 9 25 54 am" src="https://user-images.githubusercontent.com/10793598/40552681-ad3805fa-5ffd-11e8-8592-2fe1e533a459.png">

I am using wdio-sauce-service 0.4.8. Even though the first test case doesnt fail, it bubbles it up on the failure message.

**Comment by christian-bromann** [comment]
This issue was moved to webdriverio/wdio-sauce-service#51
