### ISSUE TITLE
Test runner fails to resolve or hangs if an error occurred on SauceLabs

### ISSUE THREAD

**Issue by s-mendez-criteo** [webdriverio/webdriverio#2751]
## The problem
When running the test runner programmatically, you can create multiple instances of the launcher in order to launch specific tests with different configurations. However, if structured in a synchronous manner and an error while testing on SauceLabs occurs, the launcher may or may not continue testing and eventually resolve. If it does resolve, when the next instance is started it becomes immediately unresponsive, does not run any tests and does not appear to throw any errors. If it does not resolve, it just hangs and never finishes executing.

## Environment

* WebdriverIO version: 4.2.16
* Node.js version: v8.9.1
* [Standalone mode or wdio testrunner]: Test Runner
* if wdio testrunner, running synchronous or asynchronous tests: Synchronous
* Additional wdio packages used (if applicable): wdio-sauce-service & wdio-mocha-framework

## Details

The problem became noticeable when running large quantities (> 100) of tests concurrently (10 at a time) on SauceLabs. If the problem occurs, you have to manually kill the process or it will just hang. However, even after manually killing it, sometimes it still hangs and then you have to terminate the entire running process.

## Link to Selenium/WebdriverIO logs
Selenium-Server.log
https://gist.github.com/s-mendez-criteo/88b7eb9db9c387621131a096c8407aa4

Automator.log
https://gist.github.com/s-mendez-criteo/3876815d7026d44df4ab13d4200fc655

WebdriverIO Log
https://gist.github.com/s-mendez-criteo/f4c455e99aa729747d7fcf492dc07e64

SauceLabs
Error: Test did not see a new command for 90 seconds. Timing out.

## Code To Reproduce Issue [ Good To Have ]
`var Launcher = require('webdriverio').Launcher;

var wdioOne = new Launcher(opts.configFile, opts);
try{
await wdioOne.run();
}catch(err){}

var wdioTwo = new Launcher(opts.configFile, opts);
try{
await wdioTwo.run();
}catch(err){}`

**Comment by s-mendez-criteo** [comment]
@christian-bromann Unfortunately, there has not been a simple way to reproduce the issue as I am not fully sure of the cause. It seems to only occur frequently with a larger quantity of tests and appears to be related to when a test errors on SauceLabs.

As requested, [https://github.com/s-mendez-criteo/webdriverio-2751](url) is an example which has been observed to possibly highlight the issue. I would recommend trying different cases which may make the problem evident:
1) Run `npm test` and let all tests run
2) Run `npm test` and manually cancel a few tests on SauceLabs
3) Run `npm test`, wait some time and crtl+c twice. Then run `npm test` again.

**Comment by s-mendez-criteo** [comment]
Following up on this with some additional observations:
- Our tests contained multiple `execute` & `executeAsync` calls. When we narrowed down the test to just one large `executeAsync` the frequency of the testing hangs was **unchanged** and continued to cause problems
- Setting `extendedDebugging: false` in the capabilities for Sauce Labs seems to reduce the frequency but does not remove the problem
- Adding `process.kill(process.pid);` at the end of a test, such as in `browser.on('end', ...`, seems to alleviate the issue

**Comment by WillBrock** [comment]
@s-mendez-criteo is this still and issue? Have you tried it with v5?
