### ISSUE TITLE
Need a browser.frame() variant that uses getSVGDocument() instead of contentDocument to work with svg embedded documents; no way to click on elements in an <svg> inside an <embed> tag

### ISSUE THREAD

**Issue by osmolyar** [webdriverio/webdriverio#2753]
## The problem

There is currently no way to click on elements inside an <svg> element inside of a #document in an \<svg\> \<embed\> tag, wuth html as seen in example #3 at http://srufaculty.sru.edu/david.dailey/javascript/frames/objectTest.html.

The elements inside the svg are not accessible to Selenium/Webdriverio because they are not in the main document DOM but are relative to the #document inside the embed tag.  Any attempt to access them normally results in 'element not found'.

Trying to use browser.execute as described in examples #2 or #4 at http://aksahu.blogspot.com/2015/05/dealing-with-object-tags-in-selenium-webdriver.html doesn't work either (using getSVGDocument() in place of .contentDocument); any variant of example #2, using a JS click() inside the execute script, results in a "***.click() is not a function" error, even though the element the click is being called on is retrieved successfully either manually in the console via the same command or at runtime.

Trying to use variant #4, first retrieving the element into a variable and then calling browser.elementIdclick() on its .value.ELEMENT results in a "Element is no longer attached to the DOM" error, I assume because it is looking for the element relative to the main document again.

Trying to use browser.frame to switch to the 2nd 'document' as if it's a frame doesn't work either, giving  the error  "no such frame: element is not a frame" Error: A request to switch to a frame could not be satisfied because the frame could not be found.[chrome #0-0]     at frame([object Object])".

This should be supported via an analog to browser.frame() that allows switching to a document that is not defined inside an IFrame, e.g., using "getSVGDocument()" to switch to the internal document frame instead of "contentDocument" (or some other way).

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 8.9.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):  standalone
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):

## Details

Describe in more detail the problem you have been experiencing, if necessary.

In addition to the above information, here are examples of the code used in the described attempts. 

html is like:
 `<embed` style="overflow:hidden;" id="frame_15" type="image/svg+xml" src="%25ZEN.SVGComponent.svgPage.cls?$HEIGHT=100%25&$NAMESPACE=%25SYS&$PAGECLASS=%25CSP.UI.Portal.User&$PARENTIDX=15&$SVGCLASSES=%25ZEN.SVGComponent.tabBar%2C%25CSP.UI.Portal.User&$USERSVGPACKAGES=&$WIDTH=100%25" height="32" width="1300">
#document== $0
xml-stylesheet
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="zenRoot" x="0" y="0" width="1300" height="32" onload="zenLoad();" onunload="zenUnload();" zoomAndPan="disable">`

Example browser.execute command used:
browser.execute("return (document.getElementById('frame_15').getSVGDocument().getElementsByTagName('g')[8]).click()")

(says "document.getElementById('frame_15').getSVGDocument().getElementsByTagName('g')[8]).click() is not a function" even though typing document.getElementById('frame_15').getSVGDocument().getElementsByTagName('g')[8] into the console correctly retrieves the element, and the correct element id is output if logged while running script)

var tab =browser.execute("return (document.getElementById('frame_15').getSVGDocument().getElementsByTagName('g')[8])",this.elements.embedFrame);
       var  tabValueId=tab.value.ELEMENT;
       console.log(JSON.stringify(tabValueId));
       browser.elementIdClick(tabValueId);

(says "Error: An element command failed because the referenced element is no longer attached to the DOM.")

Or: 

var myFrame=browser.execute("return (document.getElementById('frame_15').getSVGDocument())");
console.log(JSON.stringify(myFrame));
browser.frame(myFrame.value);
  //      Error: An element command failed because the referenced element is no longer attached to the DOM.
  //          at frame([object Object])

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by osmolyar** [comment]
@christian-bromann , do you have any thoughts on this, by chance?  Or a pointer as to where in the package code I could customize this?

**Comment by christian-bromann** [comment]
@osmolyar let's get this standardised in WebDriver (https://github.com/w3c/webdriver/issues/1266) first and see how we can build logic on top of it. Currently it seems not possible.

**Comment by osmolyar** [comment]
This works in webdriver I believe, but not in webdriverio. E.g., this works in Webdriver

SingletonInstancesRepo.getCurrentWebDriver().switchTo().frame(element);

where element is the embed element in the svg frame. Elements inside the frame are then subsequently found.   But browser.frame(element) to the same embed element still doesn't allow child elements to be subsequently found.

**Comment by christian-bromann** [comment]
> Hence I think this issue needs to be reopened

WebdriverIO provides bare protocol commands that should allow any interaction with the protocol. So it also works with WebdriverIO.

**Comment by osmolyar** [comment]
Hi @christian-bromann , are you referring to the commands described here, https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol ?

If so, it looks like browser.frame(element) is still the relevant one, but in fact WebdriverIO is still unable to find the child elements after switching to the embed frame.

If not, could you please point me to the corresponding command?

**Comment by osmolyar** [comment]
Couple more findings:
 
- Inside the embed element (which is the only other Frame other than 'top' according to Chrome's console), there is an <svg> element.  
- This is the last element that can be located using xpath Chrome's console, with Frame=the embed element.  No other child elements inside it are returned by the console
- However css selectors *can* be used to locate elements inside the svg using Chrome's console

- Using one of these working css selectors, the error returned by Webdriverio is different than the 'element still not existing' error that the xpath selectors result in.  Instead, the error is "Cannot read property 'scrollLeft' of null"

        <this.switchToEmbedFrame();
        browser._click('#tabBar > g:nth-child(10) > text',speed.slow);  //unknown error: Cannot read property 'scrollLeft' of null>

Researching this error, it seems to have something to do with wait times.  However even adding a long wait time doesn't fix it.  Any further hints appreciated.

**Comment by osmolyar** [comment]
Also the above error occurs on Chrome, but on Firefox the error when attempting to click on the child element is

[firefox #0-0] Promise was rejected with the following reason: TypeError: container.frame is undefined
Build info: version: '3.141.0', revision: '2ecb7d9a', time: '2018-10-31T20:22:52'
System info: host: 'USP5520OSMOLYAR', ip: '172.16.14.18', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
Driver info: driver.version: unknown
[firefox #0-0] Error: Promise was rejected with the following reason: TypeError: container.frame is undefined
[firefox #0-0]     Build info: version: '3.141.0', revision: '2ecb7d9a', time: '2018-10-31T20:22:52'
[firefox #0-0]     System info: host: 'USP5520OSMOLYAR', ip: '172.16.14.18', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
[firefox #0-0]     Driver info: driver.version: unknown
[firefox #0-0]     at elements("#tabBar > g:nth-child(10) > text") - C:\Users\osmolyar\AppData\Roaming\npm\node_modules\webdriverio\build\lib\commands\isExisting.js:46:17
[firefox #0-0]     at isExisting("#tabBar > g:nth-child(10) > text") - C:\Users\osmolyar\AppData\Roaming\npm\node_modules\webdriverio\build\lib\commands\waitForExist.js:67:22

**Comment by osmolyar** [comment]
Also, an attempt to switch to browse.frame(1) yields the following error.  Even though chrome browser shows 2 frames on the page, the top frame and the embed frame.  Based on the above error "container.frame is undefined" and this one, it seems like Webdriverio doesn't recognize the svg embed frame.   But Webdriver apparently does.

Unable to locate frame: 1
Build info: version: '3.141.0', revision: '2ecb7d9a', time: '2018-10-31T20:22:52'
System info: host: 'USP5520OSMOLYAR', ip: '172.16.14.18', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
Driver info: driver.version: unknown
running firefox
Error: A request to switch to a frame could not be satisfied because the frame could not be found.
    at frame(1) -     at C:\Users\osmolyar\AppData\Roaming\npm\node_modules\wdio-cucumber-framework\node_modules\wdio-sync\build\index.js:316:3

**Comment by christian-bromann** [comment]
> it seems like Webdriverio doesn't recognize the svg embed frame

Again WebdriverIO doesn't do anything here other than sending the command to the driver. If the driver doesn't work properly there is nothing WebdriverIO can do about it.

**Comment by osmolyar** [comment]
Somehow webdriver is able to do it with this sequence of commands:

try {
            org.openqa.selenium.WebElement element=elem.toWebElement();
            SingletonInstancesRepo.getCurrentWebDriver().switchTo().frame(element);
        } catch (Exception ex) {
            SingletonInstancesRepo.getAqLogUtils().error("Error Occured while trying to switch to embed: "+ex.getLocalizedMessage());
         
        }
        SingletonInstancesRepo.getAqUtils().injectJQuery(SingletonInstancesRepo.getCurrentWebDriver());
        JavascriptExecutor jsexec=(JavascriptExecutor) SingletonInstancesRepo.getCurrentWebDriver();
         try {
             jsexec.executeScript("aq__JQuery('#tabBar > g> text:contains("+TitleText+")').click();");

**Comment by christian-bromann** [comment]
> Somehow webdriver is able to do it with this sequence of commands:

I am not sure what this code is doing but you are able to do the exact thing with WebdriverIO too. WebdriverIO allows you to make any kind of request that any other Selenium binding could do.

**Comment by osmolyar** [comment]
Would it be possible to humor me and say how?  Are you suggesting using something other than browser.frame() to switch frames?

**Comment by christian-bromann** [comment]
> Would it be possible to humor me and say how?

Check the requests that are being made with the Java binding and run them with WebdriverIO.

**Comment by osmolyar** [comment]
That's exactly what I'm trying to do -

.getCurrentWebDriver().switchTo().frame(element);  = browser.frame(element) 

where element is the same exact embed fame, then click on an element containing text inside the frame.

What are the 'bare protocol commands' if they're different from the above?

**Comment by osmolyar** [comment]
In case anyone is following along:

This syntax works, executed against example #3 at http://srufaculty.sru.edu/david.dailey/javascript/frames/objectTest.html:

browser.execute("(document.getElementById('em').getSVGDocument().getElementsByTagName('text')[0]).click");

or, if first using brower.frame() to switch to the embed element frame (#em), then this also works:

 browser.execute("(document.getElementsByTagName('text')[0]).click");

It doesn't work without using browser.execute().

working code sample attached:
[svg.zip](https://github.com/webdriverio/webdriverio/files/3233696/svg.zip)

**Comment by osmolyar** [comment]
@christian-bromann, @abjerstedt just fyi there is now simple code to reproduce, (above) against a publically-accessible page, going around and around in the same circles as delineated above.

**Comment by osmolyar** [comment]
>WebdriverIO provides bare protocol commands that should allow any interaction with the protocol. So it also works with WebdriverIO.

I believe the above shows that it does not in fact work with WebdriverIO using the same browser.frame() and jQuery click as appears to work in WebdriverIO.  So still believe this issue should be reopened.
[svg.zip](https://github.com/webdriverio/webdriverio/files/3248404/svg.zip)

**Comment by christian-bromann** [comment]
> it does not in fact work with WebdriverIO

vs.

> appears to work in WebdriverIO

Not sure what you mean here

**Comment by osmolyar** [comment]
Sorry, the 2nd one is a typo; edited.  It appears to work in WebdriverIO (using accelQ's java bindings) as described in this comment, https://github.com/webdriverio/webdriverio/issues/2753#issuecomment-478052477, but given all the attempts to reproduce the same commands using WebdriverIO above seem to provide evidence that it is not currently possible with WebdriverIO.

**Comment by christian-bromann** [comment]
> it is not currently possible with WebdriverIO

That is not correct. WebdriverIO allows you do make the same HTTP requests to the browser driver as any other binding. You just don't call the exact commands or not in the right order. The automation is done by the browser driver and if you can automate it in Java you can automate it with WebdriverIO too.

That said, I agree that WebdriverIO can simplify interacting with SVG elements. Any contribution in that direction would be highly appreciated.

**Comment by osmolyar** [comment]
> You just don't call the exact commands or not in the right order. 

That is very possible.  The commands I see being called (with accelQ) are 1) switchTo().Frame(element) and 2) executing a jQuery select followed by click.

Is this not the same as 

browser.frame(my_frame);
$('circle').click();

in the code to reproduce .zip?

**Comment by christian-bromann** [comment]
@osmolyar this is just a different interface, check which commands (HTTP requests) are actually send to the driver and call them in the same way using pure protocol commands in WebdriverIO.

**Comment by osmolyar** [comment]
What would be the best way to check this?

**Comment by osmolyar** [comment]
Attached is a java Webdriver project that reproduces the exact same "Cannot read property 'scrollLeft' of null" error with the following commands:
[SeleniumWebdriver_notWorking.zip](https://github.com/webdriverio/webdriverio/files/3258491/SeleniumWebdriver_notWorking.zip)

 driver.switchTo().frame(driver.findElement(By.xpath("//*[@id=\"em\"]")));
        WebElement circle = (WebElement) ((JavascriptExecutor)driver).executeScript("return (document.getElementsByTagName('circle')[0])");
        circle.click();

(or just   driver.findElement(By.cssSelector("circle")).click();)

However the following modified java Webdriver attachment, instead importing jQuery and using its click() command as follows,

  URL jqueryUrl = Resources.getResource("resources\\jquery-3.4.1.min.js");
        System.out.println(jqueryUrl.getPath());
        String jqueryText = Resources.toString(jqueryUrl, Charsets.UTF_8);
       ((JavascriptExecutor)driver).executeScript(jqueryText);
         ((JavascriptExecutor)driver).executeScript("return $('circle').click()");

does work.  Working .zip with imported jquery:
[SeleniumWebdriver_workingWithJQueryMinJs.zip](https://github.com/webdriverio/webdriverio/files/3258490/SeleniumWebdriver_workingWithJQueryMinJs.zip)

Trying to do the exact same thing with an imported jQuery with WebdriverIO as in the attached using something like

       var jquery_string = jQuery+"('circle').click();";
       browser.execute(jquery_string);

throws the Error("jQuery requires a window with a document"). [WebdriverIO_svg_withJQuery_attempt.zip](https://github.com/webdriverio/webdriverio/files/3258531/WebdriverIO_svg_withJQuery_attempt.zip)

I do not know what you mean by looking at the actual http requests sent, but would like to know how to execute a jQuery click in WebdriverIO, if it is possible just as it is in Webdriver.

**Comment by osmolyar** [comment]
Http requests sent for interacting with circle element in Webdriverio:

sun.net.www.MessageHeader@1a5a88899 pairs: {POST /session/4927d91d1b27bc49877028442ce1bdb6/execute HTTP/1.1: null}{User-Agent: webdriverio/webdriverio/4.14.3}{Accept: application/json}{Content-Type: application/json; charset=utf-8}{Cache-Control: no-cache}{Pragma: no-cache}{Host: localhost:38691}{Connection: keep-alive}{Content-Length: 74}
19:04:37.785 DEBUG [HttpURLConnection.getInputStream0] - sun.net.www.MessageHeader@17f170723 pairs: {null: HTTP/1.1 200 OK}{Content-Length: 103}{Content-Type: application/json; charset=utf-8}
19:04:37.786 DEBUG [ReverseProxyHandler.execute] - To downstream: {"sessionId":"4927d91d1b27bc49877028442ce1bdb6","status":0,"value":{"ELEMENT":"0.18344166712057808-1"}}
19:04:37.791 DEBUG [WebDriverServlet.handle] - Found handler: 4927d91d1b27bc49877028442ce1bdb6 (org.openqa.selenium.chrome.ChromeDriverService)
19:04:37.792 DEBUG [WebDriverServlet.lambda$handle$0] - Handler thread for session 4927d91d1b27bc49877028442ce1bdb6 (chrome): Executing POST on /session/4927d91d1b27bc49877028442ce1bdb6/element (handler: ServicedSession)
19:04:37.793 DEBUG [ReverseProxyHandler.execute] - To upstream: {"using":"css selector","value":"circle"}
19:04:37.793 DEBUG [HttpURLConnection.writeRequests] - sun.net.www.MessageHeader@3c040c159 pairs: {POST /session/4927d91d1b27bc49877028442ce1bdb6/element HTTP/1.1: null}{User-Agent: webdriverio/webdriverio/4.14.3}{Accept: application/json}{Content-Type: application/json; charset=utf-8}{Cache-Control: no-cache}{Pragma: no-cache}{Host: localhost:38691}{Connection: keep-alive}{Content-Length: 41}
19:04:37.808 DEBUG [HttpURLConnection.getInputStream0] - sun.net.www.MessageHeader@406e67823 pairs: {null: HTTP/1.1 200 OK}{Content-Length: 103}{Content-Type: application/json; charset=utf-8}
19:04:37.809 DEBUG [ReverseProxyHandler.execute] - To downstream: {"sessionId":"4927d91d1b27bc49877028442ce1bdb6","status":0,"value":{"ELEMENT":"0.18344166712057808-1"}}
19:04:37.820 DEBUG [WebDriverServlet.handle] - Found handler: 4927d91d1b27bc49877028442ce1bdb6 (org.openqa.selenium.chrome.ChromeDriverService)
19:04:37.820 DEBUG [WebDriverServlet.lambda$handle$0] - Handler thread for session 4927d91d1b27bc49877028442ce1bdb6 (chrome): Executing POST on /session/4927d91d1b27bc49877028442ce1bdb6/element/0.18344166712057808-1/click (handler: ServicedSession)
19:04:37.822 DEBUG [ReverseProxyHandler.execute] - To upstream: {}
19:04:37.822 DEBUG [HttpURLConnection.writeRequests] - sun.net.www.MessageHeader@e3eb1c69 pairs: {POST /session/4927d91d1b27bc49877028442ce1bdb6/element/0.18344166712057808-1/click HTTP/1.1: null}{User-Agent: webdriverio/webdriverio/4.14.3}{Accept: application/json}{Content-Type: application/json; charset=utf-8}{Cache-Control: no-cache}{Pragma: no-cache}{Host: localhost:38691}{Connection: keep-alive}{Content-Length: 2}
19:04:37.851 DEBUG [HttpURLConnection.getInputStream0] - sun.net.www.MessageHeader@125022933 pairs: {null: HTTP/1.1 200 OK}{Content-Length: 303}{Content-Type: application/json; charset=utf-8}
19:04:37.851 DEBUG [ReverseProxyHandler.execute] - To downstream: {"sessionId":"4927d91d1b27bc49877028442ce1bdb6","status":13,"value":{"message":"unknown error: Cannot read property 'scrollLeft' of null\n  (Session info: chrome=74.0.3729.169)\n  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17134 x86_64)"}}
19:04:37.970 DEBUG [WebDriverServlet.handle] - Found handler: 4927d91d1b27bc49877028442ce1bdb6 (org.openqa.selenium.chrome.ChromeDriverService)

**Comment by osmolyar** [comment]
The workaround with WebdriverIO is to use this function provided by @klamping to inject jQuery into the browser's page

<injectJQuery() {
        browser.execute(`function l(u, i) 
        {   var d = document; 
            if (!d.getElementById(i)) 
            {   
                var s = d.createElement('script'); 
                s.src = u; 
                s.id = i; 
                d.body.appendChild(s); 
             } 
         } l('//code.jquery.com/jquery-3.2.1.min.js', 'jquery')`);
    }>

and then call it using browser.execute as

browser.execute(`jQuery(document.getElementById('em').getSVGDocument().querySelector('circle')).click()`)

**Comment by mgrybyk** [comment]
Haven't tried circle example, but had no problems with svg before.
In order to traverse through svg I used xpath `//*[local-name()='path']`. Please note that not all attributes are supported, also, it is required to find parent, and then proceed search from parent. 
I didn't have iframes inside svg, can try later on.

**Comment by osmolyar** [comment]
I think the frame may be the issue because it is not even possible to click on the elements inside it using javascript in developer tools console.  jQuery click is the only way we have found in either Webdriver or WebdriverIO.  (Also even the console for some reason can't find the elements inside the svg frame using xpath after using getSVGDocument(), only css locators.)

**Comment by osmolyar** [comment]
> @osmolyar let's get this standardised in WebDriver ([w3c/webdriver#1266](https://github.com/w3c/webdriver/issues/1266)) first and see how we can build logic on top of it. Currently it seems not possible.

Hi @christian-bromann , does the merge of this fix to webdriver have any impact on WebdriverIO's ability to handle frames inside svgs?  https://github.com/w3c/webdriver/pull/1565 

(traced via https://github.com/w3c/webdriver/issues/1266 ->  https://github.com/w3c/webdriver/pull/1320 )

**Comment by christian-bromann** [comment]
What got merged?

**Comment by osmolyar** [comment]
Supposedly Shadow DOM support:  https://github.com/w3c/webdriver/pull/1320#issuecomment-802200542

**Comment by christian-bromann** [comment]
Not, sure if this issue you posted works now however WebdriverIO now uses these endpoints.

**Comment by osmolyar** [comment]
It is not able to interact with elements inside an SVG directly, no.  I would imagine there needs to be some command similar to browser.frame() to switch to the svg context?
