### ISSUE TITLE
TypeError: rows[1].$$ is not a function

### ISSUE THREAD

**Issue by basickarl** [webdriverio/webdriverio#2755]
From the example at: http://webdriver.io/api/property/getText.html
```
    it.only('get content from table cell', async function () {
        browser.url('http://the-internet.herokuapp.com/tables');
        var rows = await browser.$$('#table1 tr');
        var columns = rows[1].$$('td'); // get columns of 2nd row
        console.log(columns[2].getText()); // get text of 3rd column
    });
```
Results in `TypeError: rows[1].$$ is not a function`. The documentation is not clear when not using the global object. How does the same example look when using the browser object for the $$ function?

E.g. `text.$$('li')[2].$('a').getText();`?

Using 4.12.0.

**Comment by christian-bromann** [comment]
@basickarl you are using wdio in async mode which doesn't support such chaining. This is a problem we have tackled and fixed with the upcoming major release (v5). I recommend to use wdio in sync mode until then.
