### ISSUE TITLE
browser.click() doesn't work on Chrome v67 (Mac only)

### ISSUE THREAD

**Issue by bkvaughan** [webdriverio/webdriverio#2757]
## The problem

After updating to Chrome v67 for Mac my browser.click() calls failed to click a login button. Specifically the selector failing to be hit takes the form of: _browser.click('.login_form_action_submit button');_. Rolling back my Chrome to 65 or 66 fixed the issue. Other selectors seem to work so I'm not sure if this is limited to class -> element selectors. _**Note:** this does not affect Windows/Chrome computers._

## Environment

* WebdriverIO version: 4.12.0
* Node.js version: 8.11.2
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Testrunner
* if wdio testrunner, running synchronous or asynchronous tests: Synchronous
* Additional wdio packages used (if applicable):
    "wdio-allure-addons-reporter": "0.0.4",
    "wdio-allure-reporter": "^0.5.0",
    "wdio-junit-reporter": "^0.4.2",
    "wdio-mocha-framework": "~0.5.13",
    "wdio-sauce-service": "~0.4.8",
    "wdio-selenium-standalone-grid-service": "0.0.2",
    "wdio-selenium-standalone-service": "0.0.10",
    "wdio-spec-reporter": "0.1.4"

**Comment by christian-bromann** [comment]
Without any logs it is impossible to assume any reason for this. Since it seems to work on other platforms this looks like an issue with the automation code or with Chromedriver. WebbdriverIO can't do much here to fix this.
