### ISSUE TITLE
Class inheritance issue

### ISSUE THREAD

**Issue by deep9** [webdriverio/webdriverio#2758]
## The problem

When using utils.ErrorHandler descendants, it is not possible to use `instanceOf ErrorHandler` due to a problem in babel / the way the babel works.

This problem is not when transpiling to node 6 (6.10) as there is a native support for classes.

So, while node@4 is officially dead, is there any reason for the 4.4 support?

## Environment

* WebdriverIO version: 4.12 / master
* Node.js version: 8
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): standalone
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

```javascript
const ErrorHandler = require('webdriverio/build/lib/utils/ErrorHandler');
const error = new ErrorHandler('RuntimeError');

console.log(error instanceof ErrorHandler ? "true" : "false"); // logs false
console.log(error instanceof Error ? "true" : "false"); // logs true
```

**Comment by christian-bromann** [comment]
> is there any reason for the 4.4 support?

No and we upgraded in v5. Feel free to provide a PR with necessary changes!
