### ISSUE TITLE
http headers

### ISSUE THREAD

**Issue by impnguyen** [webdriverio/webdriverio#2759]
## The problem

I'm trying to use the http header in the wdio config file. After setting the authorization header in the config file, the backend does not get the base auth. 

## Environment
I'm using the chrome driver with the webdriverio version 4.12. 

## Details
I tried this example: [headers](http://webdriver.io/guide/getstarted/configuration.html#headers)

with this coding: 
`exports.config = {
    specs: [
        './webapp/test/webdriveriotest/specs/**/*.js'
    ],
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    
    headers: {
    	  Authorization: 'Basic .........='
    },
    
    debug: true,
    `
I do not understand the functionality of the webdriver io headers

**Comment by Eduard-iCH** [comment]
Just a tip - you can path basic-auth inside URL, like:

https://gooduser:secretpassword@www.example.com/webcallback?foo=bar

**Comment by impnguyen** [comment]
Hi Eduard-iCH,
I already tried it. The back end system is a SAP Netweaver Gateway. It does not work.

**Comment by christian-bromann** [comment]
These headers are for the selenium server requests not for the browser. The webdriver protoocol doesn't allow to modify browser headers. There are ways to achieve this using the `wdio-devtools-protocol` and Chrome DevTools request intercept functionality but there is no cross browser way. This can't be fixed by WebdriverIO therefor closing.

**Comment by sosnet** [comment]
Came along this as well, as I can`t pass basic auth via url. I think because of this: https://medium.com/@lmakarov/say-goodbye-to-urls-with-embedded-credentials-b051f6c7b6a3
