### ISSUE TITLE
Error thrown in beforeSuite does not stop the execution of the testsuite.

### ISSUE THREAD

**Issue by kmnaid** [webdriverio/webdriverio#2760]
## Environment

* WebdriverIO version: v4.12.0
* Node.js version: v8.0.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync

## Details

When there is a failure in `beforeSuite` the `it` blocks in the test suite should not be executed. However the error in beforeSuite isn't caught and the test execution  continues. The result will show that the test is passing.

## Code To Reproduce Issue

wdio.conf.js:

```
beforeSuite: function (suite) {
    throw new Error("This is an error in beforeSuite");
}
```
example/test/beforeSuiteFailureTest.js:
```
describe('Test Suite for demonstrating error not being caught in beforeSuite', function () {
    it('A simple assertion', function () {
        assert.strictEqual('Hello','Hello');
    });
})
```

## Logs

```
wdio example/wdio.conf.js "--spec" "example/test/beforeSuiteFailureTest.js"

Error: This is an error in beforeSuite
    at Object.beforeSuite (/example/wdio.conf.js:346:15)
    at execHook (/usr/local/lib/node_modules/wdio-mocha-framework/node_modules/wdio-sync/build/index.js:162:35)

․1 passing (9.40s)
```

**Comment by christian-bromann** [comment]
@kmnaid this is intentional .. wdio hooks will not cause the test to fail. If you run something critical for your test you need to run the hook within the test file.
