### ISSUE TITLE
Returning browser version without setting it in capabilities

### ISSUE THREAD

**Issue by javacoldbrew** [webdriverio/webdriverio#2761]
I understand that if I define browser version in capabilities, I can simply do:

` return browser.desiredCapabilities.version`

But I don't have it defined because I am running the tests on several different versions of docker-selenium (Which have their own Chrome/Firefox versions).

How would I be able to return the current version of the browser?

**Comment by christian-bromann** [comment]
You can use the [`session()`](http://webdriver.io/api/protocol/session.html#Example) command to do so. 
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by javacoldbrew** [comment]
@christian-bromann Thank you! I will use gitter for any further questions like this.
