### ISSUE TITLE
browser.click() in chrome browser on Android device does not seem to work.

### ISSUE THREAD

**Issue by sumeetp4** [webdriverio/webdriverio#2766]
## The problem

Using webdriverio with mocha tests on Android device. I am trying to open a URL in chrome browser in Android device and perform some actions. The problem is I'm not able to perform any action, for example click with any locator strategies. Tried the one mentioned here(https://github.com/webdriverio/webdriverio/blob/master/examples/standalone/webdriverio.with.appium.chrome.js) but does not seem to work. It always returns with  error no such element: Unable to locate element

## Environment

* WebdriverIO version: 4.10.1
* Node.js version: 8.10.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Standalone
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable): chrome version on android device: 66.0

## Details

Can I use UiSelector strategy here? I even tried to switch context to CHROMIUM by using
browser.context('CHROMIUM');
but nothing seems to work

## Link to Appium logs

[Appium] Creating new AndroidDriver (v2.6.0) session
[Appium] Capabilities:
[Appium]   javascriptEnabled: true
[Appium]   locationContextEnabled: true
[Appium]   handlesAlerts: true
[Appium]   rotatable: true
[Appium]   platformName: Android
[Appium]   platformVersion: 7.0
[Appium]   browserName: Chrome
[Appium]   deviceName: Moto G5
[Appium]   udid: ZY223XTC9Q
[Appium]   requestOrigins: {
[Appium]     url: http://webdriver.io
[Appium]     version: 4.10.1
[Appium]     name: webdriverio
[Appium]   }
[BaseDriver] Creating session with MJSONWP desired capabilities: {"javascriptEnabled":true,"...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: javascriptEnabled, locationContextEnabled, handlesAlerts, rotatable, requestOrigins.
[BaseDriver] Session created with session id: e97b486e-de19-40a2-a1e7-f34d2ffe502f
[AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_162
[AndroidDriver] We're going to run a Chrome-based session
[AndroidDriver] Chrome-type package and activity are com.android.chrome and com.google.android.apps.chrome.Main
[ADB] Checking whether adb is present
[ADB] Using adb.exe from E:\android-sdk\platform-tools\adb.exe
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[AndroidDriver] Using device: ZY223XTC9Q
[ADB] Checking whether adb is present
[ADB] Using adb.exe from E:\android-sdk\platform-tools\adb.exe
[ADB] Setting device id to ZY223XTC9Q
[AndroidDriver] App file was not listed, instead we're going to run com.android.chrome directly on the device
[AndroidDriver] Checking whether package is present on the device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'E:\android-sdk\platform-tools\adb.exe -P 5037 -s ZY223XTC9Q shell pm list packages com.android.chrome'
[AndroidDriver] Starting Android session
[ADB] Running 'E:\android-sdk\platform-tools\adb.exe -P 5037 -s ZY223XTC9Q wait-for-device'
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'E:\android-sdk\platform-tools\adb.exe -P 5037 -s ZY223XTC9Q shell echo ping'
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting install status for io.appium.settings
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'E:\android-sdk\platform-tools\adb.exe -P 5037 -s ZY223XTC9Q shell pm list packages io.appium.settings'
[ADB] App is installed
[ADB] Getting package info for 'io.appium.settings'
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'E:\android-sdk\platform-tools\adb.exe -P 5037 -s ZY223XTC9Q shell dumpsys package io.appium.settings'
[ADB] Checking whether aapt is present
[ADB] Using aapt.exe from E:\android-sdk\build-tools\24.0.1\aapt.exe
[ADB] The installed 'io.appium.settings' package does not require upgrade ('2.3.0' >= '2.3.0')
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'E:\android-sdk\platform-tools\adb.exe -P 5037 -s ZY223XTC9Q shell ps'
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'E:\android-sdk\platform-tools\adb.exe -P 5037 -s ZY223XTC9Q shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 24
[ADB] Device API level: 24
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'E:\android-sdk\platform-tools\adb.exe -P 5037 -s ZY223XTC9Q shell am start -W -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[ADB] Device API level: 24
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'E:\android-sdk\platform-tools\adb.exe -P 5037 -s ZY223XTC9Q shell appops set io.appium.settings android\:mock_location allow'
[AndroidDriver] setDeviceLanguageCountry requires language or country.
[AndroidDriver] Got language: 'undefined' and country: 'undefined'
[Logcat] Starting logcat capture
[AndroidDriver] Pushing unlock helper app to device...
[ADB] Getting install status for io.appium.unlock
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'E:\android-sdk\platform-tools\adb.exe -P 5037 -s ZY223XTC9Q shell pm list packages io.appium.unlock'
[ADB] App is installed
[ADB] Getting package info for 'io.appium.unlock'
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'E:\android-sdk\platform-tools\adb.exe -P 5037 -s ZY223XTC9Q shell dumpsys package io.appium.unlock'
[ADB] Checking whether aapt is present
[ADB] Using aapt.exe from E:\android-sdk\build-tools\24.0.1\aapt.exe
[ADB] The installed 'io.appium.unlock' package does not require upgrade ('2.0.0' >= '2.0.0')
[ADB] Getting device platform version
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'E:\android-sdk\platform-tools\adb.exe -P 5037 -s ZY223XTC9Q shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 7.0
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'E:\android-sdk\platform-tools\adb.exe -P 5037 -s ZY223XTC9Q shell wm size'
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'E:\android-sdk\platform-tools\adb.exe -P 5037 -s ZY223XTC9Q shell getprop ro.product.model'
[ADB] Current device property 'ro.product.model': Moto G (5) Plus
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'E:\android-sdk\platform-tools\adb.exe -P 5037 -s ZY223XTC9Q shell getprop ro.product.manufacturer'
[ADB] Current device property 'ro.product.manufacturer': motorola
[AndroidDriver] No app sent in, not parsing package/activity
[AndroidDriver] No app capability. Assuming it is already on the device
[ADB] Getting install status for com.android.chrome
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'E:\android-sdk\platform-tools\adb.exe -P 5037 -s ZY223XTC9Q shell pm list packages com.android.chrome'
[ADB] App is installed
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'E:\android-sdk\platform-tools\adb.exe -P 5037 -s ZY223XTC9Q shell am force-stop com.android.chrome'
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'E:\android-sdk\platform-tools\adb.exe -P 5037 -s ZY223XTC9Q shell pm clear com.android.chrome'
[AndroidDriver] Performed fast reset on the installed 'com.android.chrome' application (stop and clear)
[AndroidBootstrap] Watching for bootstrap disconnect
[ADB] Forwarding system: 100 to device: 4724
[ADB] Running 'E:\android-sdk\platform-tools\adb.exe -P 5037 -s ZY223XTC9Q forward tcp\:100 tcp\:4724'
[UiAutomator] Starting UiAutomator
[UiAutomator] Moving to state 'starting'
[UiAutomator] Parsing uiautomator jar
[UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[ADB] Running 'E:\android-sdk\platform-tools\adb.exe -P 5037 -s ZY223XTC9Q push C\:\\Users\\SP00540006\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium-android-bootstrap\\bootstrap\\bin\\AppiumBootstrap.jar /data/local/tmp/'
[ADB] Attempting to kill all uiautomator processes
[ADB] Getting all processes with uiautomator
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'E:\android-sdk\platform-tools\adb.exe -P 5037 -s ZY223XTC9Q shell ps'
[ADB] No uiautomator process found to kill, continuing...
[UiAutomator] Starting UIAutomator
[ADB] Creating ADB subprocess with args: ["-P",5037,"-s","ZY223XTC9Q","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","com.android.chrome","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false]
[UiAutomator] Moving to state 'online'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[AndroidBootstrap] Android bootstrap socket is now connected
[ADB] Getting connected devices...
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[ADB] 1 device(s) connected
[ADB] Running 'E:\android-sdk\platform-tools\adb.exe -P 5037 -s ZY223XTC9Q shell dumpsys window'
[AndroidDriver] Screen already unlocked, doing nothing
[AndroidDriver] Starting a chrome-based browser session
[AndroidDriver] A port was not given, using random port: 8000
[Chromedriver] Changed state to 'starting'
[Chromedriver] The following Chromedriver executables were found:
[Chromedriver]     C:/Users/SP00540006/AppData/Local/Programs/Appium/resources/app/node_modules/appium-chromedriver/chromedriver/win/chromedriver.exe (minimum Chrome version '64.0.3282')
[ADB] Getting package info for 'com.android.chrome'
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'E:\android-sdk\platform-tools\adb.exe -P 5037 -s ZY223XTC9Q shell dumpsys package com.android.chrome'
[Chromedriver] Found 1 Chromedriver executable
[Chromedriver] capable of automating Chrome '66.0.3359'. Choosing the most recent, 'C:/Users/SP00540006/AppData/Local/Programs/Appium/resources/app/node_modules/appium-chromedriver/chromedriver/win/chromedriver.exe'.
[Chromedriver] If a specific version is required, specify it with the `chromedriverExecutable`desired capability.
[Chromedriver] Set chromedriver binary as: C:/Users/SP00540006/AppData/Local/Programs/Appium/resources/app/node_modules/appium-chromedriver/chromedriver/win/chromedriver.exe
[Chromedriver] Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"8000 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
[Chromedriver] No old chromedrivers seemed to exist
[Chromedriver] Cleaning any old adb forwarded port socket connections
[ADB] List forwarding ports
[ADB] Running 'E:\android-sdk\platform-tools\adb.exe -P 5037 -s ZY223XTC9Q forward --list'
[Chromedriver] Spawning chromedriver with: C:/Users/SP00540006/AppData/Local/Programs/Appium/resources/app/node_modules/appium-chromedriver/chromedriver/win/chromedriver.exe --url-base=wd/hub --port=8000 --adb-port=5037 --verbose
[Chromedriver] Chromedriver version: '2.37.544315'
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Windows NT\",\"version\":\"6.1.7601 SP1\"}}}"
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"ZY223XTC9Q"}}}
[Chromedriver] Webview version: 'Chrome/66.0.3359.158'
[JSONWP Proxy] Got response with status 200: {"sessionId":"db50416675f7715d0c75bce9ac672939","status":0,"value":{"acceptInsecureCerts":false,"acceptSslCerts":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{"chromedriverVersion":"2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7)"},"cssSelectorsEnabled":true,"databaseEnabled":false,"handlesAlerts":true,"hasTouchScreen":true,"javascriptEnabled":true,"locationContextEnabled":true,"mobileEmulationEnabled":false,"nativeEvents":true,"pageLoadStrategy":"normal","platform":"ANDROID","rotatable":false,"setWindowRect":false,"takesHeapSnapshot":true,"takesScreenshot":true,"unexpectedAlertBehaviour":"","version":"66.0.3359.158","webStorageEnabled":true}}
[Chromedriver] Changed state to 'online'
[Appium] New AndroidDriver session created successfully, session e97b486e-de19-40a2-a1e7-f34d2ffe502f added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1528439949846 (12:09:09 GMT+0530 (India Standard Time))
[MJSONWP] Responding to client with driver.createSession() result: {"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":true,"warnings":{},"desired":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"platformName":"Android","platformVersion":"7.0","browserName":"Chrome","deviceName":"Moto G5","udid":"ZY223XTC9Q","requestOrigins":{"url":"http://webdriver.io","version":"4.10.1","name":"webdriverio"}},"handlesAlerts":true,"rotatable":true,"platformName":"Android","platformVersion":"7.0","browserName":"Chrome","deviceName":"ZY223XTC9Q","udid":"ZY223XTC9Q","requestOrigins":{"url":"http://webdriver.io","version":"4.10.1","name":"webdriverio"},"deviceUDID":"ZY223XTC9Q","deviceScreenSize":"1080x1920","deviceModel":"Moto G (5) Plus","deviceManufacturer":"motorola"}
[HTTP] <-- POST /wd/hub/session 200 23824 ms - 937
[HTTP] 
[HTTP] --> POST /wd/hub/session/e97b486e-de19-40a2-a1e7-f34d2ffe502f/url
[HTTP] {"url":"https://www.ea.com"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/e97b486e-de19-40a2-a1e7-f34d2ffe502f/url] to [POST http://127.0.0.1:8000/wd/hub/session/db50416675f7715d0c75bce9ac672939/url] with body: {"url":"https://www.ea.com"}
[JSONWP Proxy] Got response with status 200: {"sessionId":"db50416675f7715d0c75bce9ac672939","status":0,"value":null}
[JSONWP Proxy] Replacing sessionId db50416675f7715d0c75bce9ac672939 with e97b486e-de19-40a2-a1e7-f34d2ffe502f
[HTTP] <-- POST /wd/hub/session/e97b486e-de19-40a2-a1e7-f34d2ffe502f/url 200 10903 ms - 76
[HTTP] 
[HTTP] --> POST /wd/hub/session/e97b486e-de19-40a2-a1e7-f34d2ffe502f/context
[HTTP] {"name":"CHROMIUM"}
[MJSONWP] Calling AppiumDriver.setContext() with args: ["CHROMIUM","e97b486e-de19-40a2-a1e7-f34d2ffe502f"]
[AndroidDriver] Available contexts: ["NATIVE_APP","CHROMIUM"]
[MJSONWP] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/e97b486e-de19-40a2-a1e7-f34d2ffe502f/context 200 12 ms - 76
[HTTP] 
[HTTP] --> POST /wd/hub/session/e97b486e-de19-40a2-a1e7-f34d2ffe502f/element
[HTTP] {"using":"css selector","value":"*[id=Label]"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/e97b486e-de19-40a2-a1e7-f34d2ffe502f/element] to [POST http://127.0.0.1:8000/wd/hub/session/db50416675f7715d0c75bce9ac672939/element] with body: {"using":"css selector","value":"*[id=Label]"}
[JSONWP Proxy] Got response with status 200: {"sessionId":"db50416675f7715d0c75bce9ac672939","status":7,"value":{"message":"no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"*[id=Label]\"}\n  (Session info: chrome=66.0.3359.158)\n  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 6.1.7601 SP1 x86_64)"}}

## Code To Reproduce Issue [ Good To Have ]

I'm trying to click the element
using browser.click('*[id="Label"]')
even tried with class name
browser.click('*[class="eapl-cta__label"]')

 as you can see here I have identified in chrome inspect
![image](https://user-images.githubusercontent.com/29970107/41143465-ff83d2b6-6b16-11e8-9bf0-2689008a6de9.png)

**Comment by erwinheitzman** [comment]
This is because the element is a shadow dom element. There's a webdriverio plugin that adds easy handling of these elements and the next version of webdriverio will have this funtionality baked in by default.

**Comment by sumeetp4** [comment]
Great. Thank you @erwinheitzman
