### ISSUE TITLE
Selenium W3C Capabilities

### ISSUE THREAD

**Issue by nbabii** [webdriverio/webdriverio#2767]
Hi Guys,

In Apr Sauce Labs added support for new w3c possibilities, in order to get them worked we need to have specific capabilities set up (described in link below)
https://wiki.saucelabs.com/display/DOCS/Selenium+W3C+Capabilities+Support+-+Beta

Could you please help with providing an example or guidance for wdio.conf.js which will allow us to create capabilities described above?

**Comment by abjerstedt** [comment]
If i'm understanding the request - you are asking for information on how to submit those types of capabilities.

Unless I'm misunderstanding, the answer is to just put new key value pair with the capability name you want. (You will need to encapsulate anything with a period like sauce.blah in quotes).

**Comment by smccarthy** [comment]
@abjerstedt Does this work for you for SauceLabs ? It didn't work for me when I tried a few weeks ago.

**Comment by nbabii** [comment]
@abjerstedt Yes, I tried, but unfortunately it doesn't work with SauceLabs.

**Comment by abjerstedt** [comment]
To clarify, you guys tried adding a nested node?:
capabilities: {
 "sauce:options": {
   "username": "myuser", 
   "accesskey": "XXXXXXXX"
 }
}

I can try to take a look later this afternoon, but i'm flip flopping between sauce, browserstack and our internal grid. Our trials for browserstack and sauce both expire tonight.

**Comment by christian-bromann** [comment]
> in order to get them worked we need to have specific capabilities set up

I don't think this is necessary. In WebdriverIO you specify your caps as standard JSON format which gets passed over directly to SauceLabs. I don't see any necessaty chances to be done here. The example @abjerstedt provided should do the trick.

**Comment by smccarthy** [comment]
I was unable to get this to work with Webdriver.IO as-is. I am on webdriver.io 4.13.2 . I was able to get around it by modifying my webdriverio in my node_modules : https://gist.github.com/smccarthy/8579f774ea14a6296c5e6d9224ce7dfb . This is obviously just a hack, but one thing to point out is `rotatable: true` will cause it to fail since its not a W3C spec. I am not sure of the others, but I removed all the ones that I didn't want/need. Should this ticket be re-opened, or is there a correct way for me to use the correct capabilities for W3C on Saucelabs ?

**Comment by smccarthy** [comment]
Thanks for re-opening. I’ll try and work together a PR in the next couple of days.

**Comment by piotr-s-brainhub** [comment]
@smccarthy 

thanks for your help 🍔
could you give some info about your progress?

**Comment by smccarthy** [comment]
@piotr-s-brainhub I talked with Christian, and he said v5 already has this capability, so I didn't want to spend extra time fixing v4. You are free to use my gist I posted to make a PR if you like though.
