### ISSUE TITLE
Unable to swipe up page with browser.touchAction

### ISSUE THREAD

**Issue by bnoel77** [webdriverio/webdriverio#2770]
## The problem

I am currently able to swipe down a page using the javascript command:
"use strict";

module.exports.run = function() {
	return browser.touchAction([
        { action: 'press', x: 185, y: 125},
        { action: 'moveTo', x: 185, y: 500},
        'release'
        ]);
};

However, if I switch the Y positions I am not able to swipe back up the page. I don't get any errors, the page just doesn't move:

"use strict";

module.exports.run = function() {
	return browser.touchAction([
        { action: 'press', x: 185, y: 500},
        { action: 'moveTo', x: 185, y: 125},
        'release'
        ]);
};

## Environment

* WebdriverIO version: 4.12.0
* Node.js version: unsure
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): standalone
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable): aura

**Comment by christian-bromann** [comment]
I am not sure why the page doesn't move but I doubt this is an issue with WebdriverIO as it just passes on your params. Try to fiddle around with the debug command or join our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) and ask people that might have run into such an issue. Thanks!
