### ISSUE TITLE
getCssProperty() throw: "given color isn't a valid rgb or rgba color"

### ISSUE THREAD

**Issue by kfirzuberi** [webdriverio/webdriverio#2773]
## The problem
When using `getCssProperty` to get color,
according to http://webdriver.io/api/property/getCssProperty.html, 
it uses **rgb2hex**  module.
yesterday a new version of the module was [published ](https://www.npmjs.com/package/rgb2hex)and I started getting this error:
![image](https://user-images.githubusercontent.com/6490785/41409144-db8b917a-6fdd-11e8-91d6-60626f5b71f6.png)

I didn't change anything in my code. is it a Bug? do I need to change something in order to fix it?

**Comment by benichismo** [comment]
We started getting the same error as well:
Error: given color (rgb(0,0,0)0px0px8px) isn't a valid rgb or rgba color
    at elementIdCssProperty("0.5586522252173367-8", "text-shadow") - getCssProperty.js:117:57

**Comment by erwinheitzman** [comment]
Thank you for submitting the issue, this is indeed a bug caused by the change. However I do believe the change to be correct.
This means that the implementation in webdriverio needs to be adjusted to match the expectations of the module.

It seems that in the past this meant that getting the `text-shadow` would only return the color but not the full text / property.
I think we should change the logic so that it will actually return the full value.

**Comment by kfirzuberi** [comment]
Is there any workaround that we can use?
Because we are using webdio for e2e testing to some parts of the CI/CD in our app. and we turned it off...

**Comment by christian-bromann** [comment]
due to security issues we had to make the rgb2hex package a bit more restrictive to this. We will fix this in the webdriverio package.

**Comment by christian-bromann** [comment]
@kfirzuberi fixed this issue in rgb2hex, please update the package and you should be good to go

**Comment by radiovisual** [comment]
@christian-bromann I am still experiencing this issue with webdriverio version `4.13.1` which has rgb2hex version:

See my versions here:

```
❯ npm list rgb2hex
web-integration-tests@1.0.0 /Users/mw/gitprojects/web-integration-tests
└─┬ webdriverio@4.13.1
  └── rgb2hex@0.1.4 
```

and the error I get
```
 I customize a background on the Account Theming page with the following data

      given color (rgb(226,230,233)url("https://bb6dcf512b33241ef106-b12771d2b2eb9c49cc5bd30e7bd6a290.ssl.cf2.rackcdn.com/5q2ppv8j1dld9di26je03y9k77arp45b")no-repeatscroll0%0%/100%padding-boxborder-box) isn't a valid rgb or rgba color
```

Could it be that upgrading to 4.13.1 was not enough to solve this problem, or could I be missing something?

**Comment by christian-bromann** [comment]
> or could I be missing something?

probably still a bug in rgb2hex, feel free to provide a PR with fix. Thanks!

**Comment by radiovisual** [comment]
So, technically this issue should be re-opened until the new version of rgb2hex are brought into webdriverio?

**Comment by christian-bromann** [comment]
@radiovisual just released the new rgb2hex package. Try to reinstall your node_modules. Thanks!
