### ISSUE TITLE
browser.pressKeycode(22) not taking effect sometimes

### ISSUE THREAD

**Issue by gitkav** [webdriverio/webdriverio#2778]
Hi,

I am testing a android TV application. I need to navigate the items on the page. For that I am using 
browser.pressKeycode(22) to navigate to the next item( towards the right hand side of the page). Sometimes I observe that the focus on the page does not shift towards the next item on the right and I need to execute the browser.pressKeycode(22) again. There is no error/failure in the appium logs. 
Could you please help me in resolving this.

**Comment by christian-bromann** [comment]
> Could you please help me in resolving this.

There is nothing WebdriverIO can do about this. Appium is responsible to execute the command it gets from this library. If it doesn't do it properly it has probably to do with Appium. Feel free to join our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have further questions but this is not necessary an issue in WebdriverIO.
