### ISSUE TITLE
Cant get output from browser.execute() promise object

### ISSUE THREAD

**Issue by JimmyMai13** [webdriverio/webdriverio#2779]
## The problem

I have a hosted js sdk and I am using browser.execute() to inject some js code into the chrome browser console to be able to call some functions from the js sdk and I cant seem to get the response output from the sdk functions.

## Environment

* WebdriverIO version: v4.12.0
* Node.js version: v9.5.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio test runner
* if wdio testrunner, running synchronous or asynchronous tests: "sync: true"

## Details
The screenshot below shows how I am calling the js sdk functions from my chrome console. As you can see, when I call sdk.loadUser() , that returns a promise and i am not sure how to get the response output from this promise.

<img width="1001" alt="screen shot 2018-06-19 at 10 42 53 pm" src="https://user-images.githubusercontent.com/38169874/41634934-076d92d6-7414-11e8-99ec-fd6514579bfc.png">

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]

        var data = browser.execute(function() {
            var IonicSDK = new window.IonicSdk.ISAgent(arguments[0]);
            var version = IonicSDK.version;
            var loaduser = IonicSDK.loadUser({"appId": "testapp", "userId": "testuser", "userAuth": "PASS"});
            return [version, loaduser, window];
        }, sdkUrl);
       
        console.log(data.value); // this outputs ["2.0.0",{},[[],[]]]

I am able to get the expected sdk version output 2.0.0 , but anything that returns a promise i just get empty {}, I also tried returning the window object to try to get the output as well but no luck. I have my wdio config file "sync: true". 

Please let me know what I am doing wrong as I am new to js and webdriverio. Thanks for your help!

**Comment by christian-bromann** [comment]
You need to make sure that the promise gets resolved. You can use `executeAsync` for this.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by JimmyMai13** [comment]
I did try executeAsync and I got the output ["2.0.0",{}] and the message "Failed: asynchronous script timeout: result was not received in 30 seconds" Is there anything I need to add when using executeAsync?

**Comment by christian-bromann** [comment]
do something like
```js
    var data = browser.executeAsync(function(cb) {
        var IonicSDK = new window.IonicSdk.ISAgent(arguments[0]);
        var version = IonicSDK.version;
        var loaduser = IonicSDK.loadUser({"appId": "testapp", "userId": "testuser", "userAuth": "PASS"});
        return loaduser.then(res => cb({ loaduser: res, version: version, loaduser: loaduser});
    }, sdkUrl);
```

**Comment by JimmyMai13** [comment]
@christian-bromann  I just gave that a try, and same result with no output and the timeout error.

**Comment by christian-bromann** [comment]
well it either takes too long then or `IonicSDK.loadUser` fails. I recommend to fiddle around a bit.

**Comment by JimmyMai13** [comment]
IonicSDK.loadUser doesnt fail bc I tried manually as attached in the screenshot above and that does return an object. It must be it takes to long , where can i increase the 30 second asynchronous script timeout? Im assuming i would use browser.timeouts('script', 60000); in the beginning of my test?

**Comment by christian-bromann** [comment]
> i would use browser.timeouts('script', 60000); in the beginning of my test?

yes

**Comment by JimmyMai13** [comment]
I think there has to be an issue with executeAsync() as with the simple code below, we know that using execute(), it returns the version 2.0.0, and this does not return anything. I also noticed when i hover over .executeAsync in webstorm ide i get the message "Unresolved function or method executeAsync()" and the text coloring is in white, with functions all text should be in yellow similarly with .execute() i see it is a valid function in yellow text.


     var data = browser.executeAsync(async function() {        
         var IonicSDK = new window.IonicSdk.ISAgent(arguments[0]);
         var version = IonicSDK.version;
         return version;
        }, sdkUrl);

**Comment by JimmyMai13** [comment]
![screen shot 2018-06-20 at 9 56 58 am](https://user-images.githubusercontent.com/38169874/41662956-4d1f9fac-7470-11e8-9209-15197d6c2fb1.png)

**Comment by christian-bromann** [comment]
```js
 var data = browser.executeAsync(async function() {      
```
this `async` above is not valid

> I also noticed when i hover over .executeAsync in webstorm ide i get the message "Unresolved function or method executeAsync()" and the text coloring is in white

Not sure what your WebStorm setup is but `executeAsync` is a function in WebdriverIO.

As I said, try a simpler version like
```js
    var data = browser.executeAsync(function(cb) {
        cb(IonicSDK.version);
    }, sdkUrl);
```
and see what you can. If it works, iterate on it. It is impossible for me to know what is going on without having the code in front of me. After all this is not an issue with WebdriverIO. If you have further questions, reach out in our support channel on [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). Thanks!
