### ISSUE TITLE
Unknown locator strategy ID on setValue with CSS-selector on firefox

### ISSUE THREAD

**Issue by metareven** [webdriverio/webdriverio#2780]
## The problem

When using: `browser.setValue('#my_input_id', 'My cool text'\uE007')`
You get the following error message on firefox: `Unknown locator strategy id`
Looking at the requests and responses I see that this is the request you make to the selenium grid:
` COMMAND     POST     "/wd/hub/session/0f10e8f6-066d-4a9c-bced-24ccf21cc2f7/elements"
DATA                {"using":"id","value":"username_input"}`

According to mozilla, `id` is not a supported locator strategy which is why this fails.
https://github.com/aerokube/selenoid/issues/261
https://www.w3.org/TR/webdriver/#locator-strategies
 
Can you make sure that you use the correct locator strategy which should be `css selector`? 

## Environment

* WebdriverIO version: 4.13.0
* Node.js version: 8.11.2
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Selenium grid + browser version: Selenium: v3.12, firefox: 60.0.2

**Comment by metareven** [comment]
@christian-bromann Thanks for the tip. I can do that for now, but that makes the selectors look kind of ugly. These types of tests currently have a bad rep where I currently work. My theory is that some of our tests today are poorly implemented, but having to instruct the other developers to use such workarounds to make things work won't help the reputation of this framework any.

I sure hope are planning on fixing this instead of relying on this workaround for the foreseeable future

**Comment by christian-bromann** [comment]
> I sure hope are planning on fixing this instead of relying on this workaround for the foreseeable future

The foreseeable future won't have an id as selector type 😉

**Comment by christian-bromann** [comment]
This is fixed in v5. As long as you use v4 please use my workaround from above.

**Comment by fijijavis** [comment]
@christian-bromann If I do the work would you be opposed to having this fixed in v4?  

I don't know how we survived this long but we finally started running into this problem with our FF tests that run in Browserstack.  My guess is they probably updated their version of Geckodriver.

**Comment by blobcat** [comment]
@fijijavis seeing the same thing as you with browserstack, but I have verified that the same geckodriver version (0.21.0) is still being used. I will let you know if I can find out more.

**Comment by christian-bromann** [comment]
@fijijavis sure, if you can provide a fix I would be happy to make a v4 release

**Comment by fijijavis** [comment]
@blobcat got a response from browserstack

> I reviewed the details with the team and confirmed that we have deployed updates related to W3C. These updates allow the browsers to follow strict W3C pattern.

> In the shared session, the Firefox browser is strictly following the W3C mode. You can verify the same from the Selenium logs of the session (search for 'Detected dialect: W3C'). However, the Selenium-bindings at your end are forwarding the command in OSS format.

> Since the browser is running in W3C mode, it could not understand OSS endpoints. Hence the exception was thrown in the tests.

> I have forwarded this behaviour to the team and they will be checking it

**Comment by blobcat** [comment]
@fijijavis I also got a similar response from browserstack, sounds like our issue is specific to a change they made to enforce W3C compliant commands. On our side we were able to refactor our tests to use only compliant commands and everything is working now. For example, we used a variation of the workaround called out in this thread above to solve the ID locator issue: `browser.element('[id=my_input_id]')`

**Comment by usmonster** [comment]
Hello! FYI, this was a breaking change (see [my comment](https://github.com/webdriverio-boneyard/v4/pull/5#issuecomment-457920526)).
