### ISSUE TITLE
isVisible causes server-side error and disconnects

### ISSUE THREAD

**Issue by codeunifier** [webdriverio/webdriverio#2782]
## The problem

isVisible causes server-side error and disconnects.

## Environment

* WebdriverIO version: 4.13.0
* Node.js version: 5.8.0
* Selenium Standalone: 6.15.1

## Details

This problems occurs inconsistently, but when it does occur it's always from using isVisible. The error below is returned, saying that the connection refused to connect, but when running multiple tests, the following test continues without connection errors. I've had this happen on multiple tests at different times, some throw this error more often than others, but it's always on the call to isVisible.

<pre>
{ Error: An unknown server-side error occurred while processing the command.
    at elementIdDisplayed("0.5565900215051574-34") - C:\path\node_modules\webdriverio\build\lib\commands\isVisible.js:71:55
  details: undefined,
  message: 'java.net.ConnectException: Connection refused: connect',
  type: 'RuntimeError',
  seleniumStack: 
   { type: 'UnknownError',
     message: 'An unknown server-side error occurred while processing the command.',
     orgStatusMessage: 'java.net.ConnectException: Connection refused: connect' },
  shotTaken: true }
</pre>

## Code To Reproduce Issue [ Good To Have ]

<pre>
expect(browser.isVisible("#element")).toBeTruthy();
</pre>

**Comment by christian-bromann** [comment]
This issue is not necessary connected to WebdriverIO. I can't really tell why this is happening but from my understanding it usually occurs if you make too many requests to the automation driver.

**Comment by codeunifier** [comment]
How is "too many requests" defined? I'm still getting this issue on several of my tests. Do you mean the length of the test? I have several pauses to add space between calls, and it still occurs, so I'm not really overloading the driver with a ton of requests all at once.
