### ISSUE TITLE
Detecting system dialogs in iOS using alertText()

### ISSUE THREAD

**Issue by endqwerty** [webdriverio/webdriverio#2783]
## The problem

the waitUntil() -> alertText() strategy doesn't work for mobile iOS (possibly android too?)

## Environment

* WebdriverIO version: 4.13.0
* Node.js version:  8.9.4
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):
  * wdio-mocha-framework
  * wdio-appium-service

## Details

I am using the waitUntil() keyword for alertText() to check for when a system dialog has popped up for a native app.

I always run into an error with the alertText() command. It seems that just attempting to get the alert will throw an error. It definitely doesn't wait the full 30seconds. Should I be using a different method for native dialogs?

````
browser.waitUntil(() => {
  browser.alertText().then(text => text, () => false);
}, 30000).then(text => text.should.contain('User credentials are invalid'));
````

````
[iPhone 8 Plus iOS 11.1 #0-0] An unknown server-side error occurred while processing the command. Original error: An attempt was made to operate on a modal dialog when one was not open.
[iPhone 8 Plus iOS 11.1 #0-0] Error: An unknown server-side error occurred while processing the command.
[iPhone 8 Plus iOS 11.1 #0-0]     at alertText() - index.js:312:3
````

## Link to Selenium/WebdriverIO logs

[wdio-logs](https://gist.github.com/endqwerty/ea8adcab89b3bbd96b89082e65200999)

**Comment by erwinheitzman** [comment]
Like the error suggests, it cannot process the command on a alert that is not there.
This is not a bug, if you want to wait for the alert you can use the following example:
`const waitForAlert = (timeout, msg, interval) =>
    browser.waitUntil(function() {
        return this.alertText().then(() => true, () => false);
    }, timeout, msg, interval);`

**Comment by endqwerty** [comment]
Am I not doing that? I don't have it saving to a variable, but I thought I was using the browser.waitUntil function? and only checking the text value after the waitUntil resolves.

**Comment by erwinheitzman** [comment]
You aren't returning the alertText to the waitUntil so it will always timeout / error.
