### ISSUE TITLE
moveTo(Object) offset can't be decimal

### ISSUE THREAD

**Issue by shinxi** [webdriverio/webdriverio#2785]
## The problem

offsetX(Y) of moveTo(Object) can't be decimal, only can be integer.

## Environment

* WebdriverIO version: v4.13.0
* Node.js version: v10.5.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): wdio-jasmine-framework

## Details
```html
<div class="test"></div>
```
Let's say test div is 200px width, 50px height.
```js
$('.test').moveToObject(0, 25.5);
```
will move to the center, i.e., (100, 50), instead of (0, 25.5). However 
```js
$('.test').moveToObject(0, 25);
```
works correctly and move to (0, 25)
## Link to Selenium/WebdriverIO logs
```
...
[20:11:48]  COMMAND	POST 	 "/wd/hub/session/af3adcc3577e844e9a86c129aa6e4615/moveto"
[20:11:48]  DATA		{"element":"0.5306660304766193-7","xoffset":0,"yoffset":25.5}
...
```

**Comment by erwinheitzman** [comment]
This is not possible because you move per pixel

**Comment by christian-bromann** [comment]
I think this is the answer @erwinheitzman , thanks!
