### ISSUE TITLE
Current version (4.13.0) in npm has a broken REPL

### ISSUE THREAD

**Issue by vitalybe** [webdriverio/webdriverio#2788]
## Reproduction steps

1. Create a new folder, e.g **temp**
1. `yarn init`
1. `yarn add webdriverio`
1. Run `node_modules/.bin/wdio repl`

REPL comes up, but $ global is unavailable and everything is working in async mode.

## Workaround

1. Download the latest release (4.13.1) from GitHub
1. Unzip and CD to the folder
1. Install dependencies`yarn`
1. Build `yarn run build`
1. Replace the **webdriverio** folder in the previous **temp** project.
1. Run REPL again and everything is working as it should

**Comment by christian-bromann** [comment]
> REPL comes up, but $ global is unavailable and everything is working in async mode.

This is because the `wdio-sync` isn't installed. REPL only runs in sync mode if that package is installed.
