### ISSUE TITLE
There is no report generated when using cucumber reporter.

### ISSUE THREAD

**Issue by ibmalan** [webdriverio/webdriverio#2789]
## The problem
When using cucumber reporter, there is no report generated.
 
wdio.conf.js
 framework: 'cucumber',
  reporters: ['spec','cucumber'],
  reporterOptions: {
      outputDir: 'reports/test/',
  },

cucumberOpts: {
 format: ['json:reports/test/cucumber.json'],
## Environment

* WebdriverIO version:   4.9.9
* Node.js version:   6.10.2
* [wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
* if wdio testrunner, running synchronous tests:
* Additional wdio packages used (if applicable):

  "dependencies": {
    "babel-preset-es2015": "~6.24.0",
    "babel-register": "~6.24.0",
    "chai": "~3.5.0",
    "cucumber": "^1.3.1",
    "gulp": "^3.9.1",
    "minimist": "^1.2.0",
    "eslint-plugin-webdriverio": "^1.0.1",
    "wdio-cucumber-framework": "~0.3.1",
    "wdio-cucumber-reporter": "0.0.2",
    "wdio-firefox-profile-service": "0.0.3",
    "wdio-junit-reporter": "^0.3.0",
    "wdio-sauce-service": "^0.4.0",
    "wdio-selenium-standalone-service": "0.0.9",
    "wdio-spec-reporter": "~0.1.0",
    "webdriverio": "~4.9.9"
  },
  "devDependencies": {
    "babel-core": "^6.18.2",
    "babel-eslint": "^7.1.0",
    "babel-jest": "^20.0.3",
    "babel-loader": "^6.2.7",
    "babel-plugin-istanbul": "^4.1.1",
    "babel-polyfill": "~6.23.0",
    "babel-preset-react": "^6.16.0",
    "cucumber-html-reporter": "^4.0.3",
    "eslint": "~3.19.0",
    "eslint-config-airbnb-base": "~11.1.0",
    "eslint-plugin-import": "~2.2.0",
    "wdio-cucumber-framework": "^0.3.1",
    "wdio-cucumber-json-reporter": "0.0.4",
    "wdio-json-reporter": "^0.3.1"
  }

## Details

There is no report generated after executing script.

[chrome #0-0]
[chrome #0-0] 4 passing (11s)
[chrome #0-0]

4 steps (4 passed, 0 failed, 0 pending)

**Comment by christian-bromann** [comment]
@ibmalan WebdriverIO doesn't support native cucumber reporter for various reasons. Please use https://www.npmjs.com/package/wdio-json-reporter or another wdio-reporter. Thanks!
