### ISSUE TITLE
Another DoS dependency in rgb2hex

### ISSUE THREAD

**Issue by rjacoby** [webdriverio/webdriverio#2790]
## The problem

DoS issue in rgb2hex. I think this is new and not a duplicate of [#2747](https://github.com/webdriverio/webdriverio/issues/2747)

I've opened [an issue](https://github.com/christian-bromann/rgb2hex/issues/6) on `rgb2hex` to request fix there, but since this is appears to be 2nd time maybe a different library like [rgb-hex](https://github.com/sindresorhus/rgb-hex) would be a solve?

## Environment

* WebdriverIO version: 4.13.1
* Node.js version: 8.11.3
* NPM version: 6.1.0

## Details

`npm audit` reports:

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ rgb2hex                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ webdriverio [dev]                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ webdriverio > rgb2hex                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/647                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
```
## Link to Selenium/WebdriverIO logs

n/a

## Code To Reproduce Issue [ Good To Have ]

1. Install `npm` 6.1.0.
1. Install latest `webdriverio`
1. Run `npm audit`

**Comment by tnoonan-salesforce** [comment]
@christian-bromann Any chance the change to remove rgb2hex can be backported to 4.x?
