### ISSUE TITLE
Cannot ignore certificate errors in firefox profile service

### ISSUE THREAD

**Issue by Nandish47** [webdriverio/webdriverio#2791]
## The problem

Hi,

I tried to ignore a firefox certificate error 'Your connection is not secure' which usually occurs if certificate is not trusted by using wdio-firefox-profile-service from wdio.conf.js.

services: ['firefox-profile'],

firefoxProfile: {
    assumeUntrustedCertIssuer: true,
    canAssumeUntrustedCertIssuer: true
},

But WebdriverIO fails to get past these errors. Are the key values ignoring certificates changed?

## Environment

* WebdriverIO version: ^2.0.2
* Node.js version: v8.11.2
* if wdio testrunner, running synchronous or asynchronous tests: running synchronous 
* Additional wdio packages used (if applicable):
 wdio-firefox-profile-service: ^0.1.2

**Comment by christian-bromann** [comment]
This issue was moved to webdriverio/wdio-firefox-profile-service#17

**Comment by Nandish47** [comment]
Mr. Bromann,

I found a fix for this issue. But it was not via **wdio-firefox-profile-service** but **wdio.conf.js capabilities** by setting option **_acceptInsecureCerts_** to **_true_**

`capabilities: [
        {
            // maxInstances can get overwritten per capability. So if you have an in-house Selenium
            // grid with only 5 firefox instances available you can make sure that not more than
            // 5 instances get started at a time.
            maxInstances: 1,
            //
            browserName: 'firefox',
  
            acceptInsecureCerts : true,
        },
]`

**Comment by ejames17** [comment]
@Nandish47  thanks this worked for me!
