### ISSUE TITLE
getCssProperty() throw: "given color isn't a valid rgb or rgba color"

### ISSUE THREAD

**Issue by anvmn** [webdriverio/webdriverio#2792]
## The problem

Similar to #2773, and caused by a problem in regular expression of  `reg2hex`.

## Details

![selection_999 1311](https://user-images.githubusercontent.com/17882245/42335681-ce067af8-8089-11e8-826b-5649edf05e60.png)

**Comment by erwinheitzman** [comment]
We released a new version with a fix yesterday, is this the version you are using? If not, please reinstall the package.

**Comment by christian-bromann** [comment]
I modified the package today again and seems that I created an edge case. One sec

**Comment by anvmn** [comment]
![selection_999 1313](https://user-images.githubusercontent.com/17882245/42336263-de52312a-808b-11e8-800c-e463a60c8f9c.png)

**Comment by anvmn** [comment]
I have a fix for it.

![selection_999 1312](https://user-images.githubusercontent.com/17882245/42336305-f62e15ca-808b-11e8-8a64-bb21ceb6085f.png)

**Comment by christian-bromann** [comment]
What is the regex change?

**Comment by anvmn** [comment]
`var digits = /(.*?)rgb(a)??\((\d{1,3}),(\d{1,3}),(\d{1,3})(,(1|0??\.([0-9]{0,3})))??\)/.exec(strippedColor)`

**Comment by christian-bromann** [comment]
with that change the following isn't matching anymore: `rgba(12,173,22,1.67)`

**Comment by anvmn** [comment]
Oh... I'm not rgb expert :)
So, I thought alpha can be between 0 and 1.

**Comment by christian-bromann** [comment]
yeah it can .. you right, we should have this failed then

**Comment by anvmn** [comment]
In this case, I think this one:

`/(.*?)rgb(a)??\((\d{1,3}),(\d{1,3}),(\d{1,3})(,[01]??(\.([0-9]{1,3})??))??\);

**Comment by christian-bromann** [comment]
Published fixed version as v0.1.8 .. please reinstall this dependency and all should be good again.

**Comment by christian-bromann** [comment]
(.*?)rgb(a)??((\d{1,3}),(\d{1,3}),(\d{1,3})(,[01]??(.([0-9]{1,3})??))??);
(.*?)rgb(a)??\((\d{1,3}),(\d{1,3}),(\d{1,3})(,(1|0??\.([0-9]{0,3})))??\)

**Comment by anvmn** [comment]
Verified 0.18 works well.
Thanks @christian-bromann!
