### ISSUE TITLE
browser.* commands behave asynchronously in "sync: true" mode

### ISSUE THREAD

**Issue by edwardspec** [webdriverio/webdriverio#2793]
## The problem

When synchoronous mode is enabled, methods like `browser.getCookie()` will
unexpectedly return a Promise if they were called from `anotherPromise.then( /* here */ )`.

See "Code To Reproduce Issue" below (100% reproducible).

Expected behavior: in synchoronous mode, methods should behave synchronously (block until the result is available, then return it).

## Environment

* WebdriverIO version: **v4.12.0**
* Node.js version: **v8.11.3**
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): **wdio testrunner**
* if wdio testrunner, running synchronous or asynchronous tests: **synchronous mode** (sync=true in wdio.conf.js)
* Additional wdio packages used (if applicable): N/A

## Code To Reproduce Issue

```
var resultOfGetCookie;

describe( 'browser.getCookie() in sync mode', function () {
	before( function() {
		browser.url( 'http://127.0.0.1/' );

		var promise = new Promise( function ( resolve, reject ) { resolve(); } );

		return promise.then( function() {
			browser.setCookie( { name: 'lol', value: 'wow' } );
			resultOfGetCookie = browser.getCookie();
		} );
	} );

	it( "shouldn't return a Promise", function () {
		require( 'chai' ).expect( resultOfGetCookie, 'Return value of browser.getCookie() in sync mode' )
			.to.not.respondTo( 'then' );
	} );
} );
```

**Comment by christian-bromann** [comment]
If you need to run promise code you need to wrap it within `browser.call`. All commands only run synchronous when executed in the same eventloop.

```js
var resultOfGetCookie;

describe( 'browser.getCookie() in sync mode', function () {
	before( function() {
		browser.url( 'http://127.0.0.1/' );

		var promise = browser.call(() => new Promise( function ( resolve, reject ) { resolve(); } ));

		browser.setCookie( { name: 'lol', value: 'wow' } );
		resultOfGetCookie = browser.getCookie();
	} );

	it( "shouldn't return a Promise", function () {
		require( 'chai' ).expect( resultOfGetCookie, 'Return value of browser.getCookie() in sync mode' )
			.to.not.respondTo( 'then' );
	} );
} );
```

**Comment by worc** [comment]
this would be a good addition to the cookie docs.
