### ISSUE TITLE
Timeout of 10000ms exceeded while running webdriver with mocha

### ISSUE THREAD

**Issue by pratheeshrajan** [webdriverio/webdriverio#2794]
## The problem
I am getting the below error while running my first test

Timeout of 10000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves. (/Users/a-7657/webdriverio-test/test/specs/test.js)

## Environment

* WebdriverIO version: "webdriverio": "^4.13.1"
* Node.js version: v10.6.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: **sync: true,**
* Additional wdio packages used (if applicable):

## Details

Tried increasing the timeouts in mocha, but it didnt help 

   mochaOpts: {
        timeout:9000000
    },

## Link to Selenium/WebdriverIO logs

0 passing (61.60s)
1 failing

1) webdriver.io page should have the right title - the fancy generator way:
Timeout of 10000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves. (/Users/a-7657/webdriverio-test/test/specs/test.js)
running firefox
Error: Timeout of 10000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves. (/Users/a-7657/webdriverio-test/test/specs/test.js)
    at Test.Runnable._timeoutError (/Users/a-7657/webdriverio-test/node_modules/mocha/lib/runnable.js:440:10)
    at Timeout.<anonymous> (/Users/a-7657/webdriverio-test/node_modules/mocha/lib/runnable.js:251:24)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
> mochaOpts: {
> timeout:9000000
> },

This should actually do it. Not sure how you setup your tests. Maybe something in the config is not correct or a wrong config file was chosen or the value gets overwritten somewhere. Without having a reproducible example I only can close this issue.
