### ISSUE TITLE
Tests Run Even When Config Throws Error

### ISSUE THREAD

**Issue by silne30** [webdriverio/webdriverio#2797]
## The problem

Error thrown in config file (for instance in one of the hooks), does not stop test execution. Tests should not run if config fails. 

## Environment

* WebdriverIO version: 4.12.0
* Node.js version: 8.11.3
* WDIO runner
* Synchronous
```
"wdio-chromedriver-service": "^0.1.2",
"wdio-iedriver-service": "^0.1.0",
"wdio-junit-reporter": "~0.3.0",
"wdio-mocha-framework": "^0.5.13",
"wdio-sauce-service": "^0.4.8",
"wdio-selenium-standalone-service": "^0.0.10",
"wdio-spec-reporter": "^0.1.4",
```

Just throw an error in your wdio.config.js. 

**Expected Result:** Test Suite fails to start due to failure in configuration.

**Actual Result:**  Error is `console.log()`ed and tests continue to run. 

We debugged the issue and it showed up in `wdio-sync/build/index.js:172` in this block: 

```javascript
if (result && typeof result.then === 'function') {
                    return result.then(resolve, function (e) {
                        console.error(e.stack);
                        resolve(e);
                    });
                }
```

If this is desired behavior, is there a flag to make it so the tests bail on config failure?

**Comment by christian-bromann** [comment]
> If this is desired behavior

Yes

> is there a flag to make it so the tests bail on config failure?

No. You can call `process.exit(1)` though.

**Comment by christian-bromann** [comment]
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by silne30** [comment]
Thanks, @christian-bromann.
