### ISSUE TITLE
Visual Regression: Screenshots are saved with browserName as Safari when the tests are actually ran on headless Chrome

### ISSUE THREAD

**Issue by deepakvstavant** [webdriverio/webdriverio#2798]
## The problem
When running tests in chrome headless, the screenshots saved with Visual-Regression service is having browserName as Safari instead of Chrome

## Environment

* WebdriverIO version: v4.12.0
* Node.js version: v9.4.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): Visual Regression

## Details

Trying to run the tests on headless chrome on my desktop, config below

wdio.conf.js:
   ```
 {
      browserName: 'chrome',
      chromeOptions: {
        args: ['headless'],
      },
      platform: '',
      version: '',
      maxInstances: '1',
   },
```

Trying to capture screenshot of the page using Visual Regression.
wdio.conf.js:
`services: [ 'selenium-standalone', 'visual-regression'], 
`
testscript:
`var images = browser.checkViewport();`

Screenshot is captured successfully but the browserName in the screenshot saved is coming as Safari.

Did some poking around and the method getScreenshotName() in wdio.conf.js is where the browserName is set to the screenshot saved i.e.

```
function getScreenshotName(basePath) {
  return function (context) {
    var type = context.type;
    var testName = context.test.title;
    var browserVersion = parseInt(context.browser.version, 10);
   
    //This is where the browserName is set
    var browserName = context.browser.name;                 

    var browserViewport = context.meta.viewport;
    var browserWidth = browserViewport.width;
    var browserHeight = browserViewport.height;
    return path.join(basePath,`${testName}_${type}_${browserName}_v${browserVersion}_${browserWidth}x${browserHeight}.png`);
  };
}
```

This line is returning browserName as Safari for some reason. Very minor issue but might cause confusions.

## Link to Selenium/WebdriverIO logs

https://gist.github.com/deepakvstavant/d791c70725b251918faca7ef57139b2d

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
This needs to get fixed in https://github.com/zinserjan/wdio-visual-regression-service. WebdriverIO is not causing this issue.
