### ISSUE TITLE
How to paste file?

### ISSUE THREAD

**Issue by flypie2** [webdriverio/webdriverio#2799]
## The problem

Can I copy a file and paste?

**Comment by deepakvstavant** [comment]
Open the file 'Ctrl+C' and then 'Ctrl+V' ;). Sorry about the bad joke, i do not think you can do that with Webdriver you have to use other js libraries.

**Comment by christian-bromann** [comment]
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by flypie2** [comment]
Ok, 😂Thanks!
