### ISSUE TITLE
How do you scroll within a scrollable element?

### ISSUE THREAD

**Issue by ctumolosus** [webdriverio/webdriverio#280]
I have an element with `{ overflow: scroll }` and fixed dimension. How would I scroll that element to a contained element? I think the `client.scroll(...)` method is only meant to scroll the viewport.

**Comment by deepakpahwa19** [comment]
Hi @christian-bromann 
Could you please provide which JS code snippet will work in browser.execute to scroll. I tried below code but it did not work out.

let elementLocator = item.selector + ":nth-of-type(" + index + ")";
let elementToScroll = $(elementLocator);
browser.execute(function (ele) {
                    ("arguments[0].scrollIntoView(true);", ele);
                }, elementToScroll);

**Comment by christian-bromann** [comment]
> Could you please provide which JS code snippet will work in browser.execute to scroll

I don't have any by hand, there are probably tons of scroll example on the internet
