### ISSUE TITLE
how we can run webdriver.io chrome browser user Ui (user control interface tests) with TFS CI job ?

### ISSUE THREAD

**Issue by ridhamalik** [webdriverio/webdriverio#2804]
I want to run webdriver.io chrome browser tests with TFS CI job but It will hung my job.

**Comment by christian-bromann** [comment]
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
