### ISSUE TITLE
How to Run differents Testcases in different browsers

### ISSUE THREAD

**Issue by Ankith3796** [webdriverio/webdriverio#2806]
I am working with webdriverio and i have a wdio.config file with 4 browser capabilities.
I want to dynamically allocate browsers for different test cases how to i do it?
I want the tests to run in parallel as well so please help me out with it
WebdriverIO version: 4.13
Node.js version: 6.12.3
Standalone mode : Selenium standalone server

**Comment by christian-bromann** [comment]
See https://github.com/webdriverio/webdriverio/issues/1068#issuecomment-405243163

**Comment by Ankith3796** [comment]
Should i have any kind of condition or any function for doing it because i tried using if clause to filter the browser based on the input from a json in the before session
