### ISSUE TITLE
how to run test cases onMultiple browser 

### ISSUE THREAD

**Issue by Ankith3796** [webdriverio/webdriverio#2807]
I am working with webdriverio and i have a wdio.config file with 4 browser capabilities.
I want to dynamically allocate browsers for different test cases how to i do it?
I want the tests to run in parallel as well so please help me out with it
WebdriverIO version: 4.13
Node.js version: 6.12.3
Standalone mode : Selenium standalone server

Should i have any kind of condition or any function for doing it because i tried using if clause to filter the browser based on the input from a json in the before session but it dint work for me as the testcases run in all browsers despite have a if condition

**Comment by christian-bromann** [comment]
> I want to dynamically allocate browsers for different test cases how to i do it?

You can't do this. With the wdio testrunner you can run "n" capabilities on "x" spec files in parallel. You can skip tests for certain browser by having
```js
if (browser.desiredCapabilities.browserName === 'x') {
    process.exit(0)
}
```
in your spec file but it will still create the WebDriver session. Best approach here is to define suites for each browser and run multiple wdio commands at the same time:
```sh
$ wdio wdio.conf.js --suite chromeTests
$ wdio wdio.conf.js --suite firefoxTests
$ wdio wdio.conf.js --suite ieTests
...
```
We are working to make this easier in v5.

Please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
