### ISSUE TITLE
Tests are failing randomly for making api calls

### ISSUE THREAD

**Issue by valaydesai3** [webdriverio/webdriverio#2808]
## The problem
The whole test suit has more than 300 tests and it seems that while executing some of the scenario, the api call response is slower and so failing test randomly on jenkins pipeline. It's not like same test fails everytime.  Even tried with `wrapperOptions: { retry: 2 }`. Timeout using 10000ms.

[https://stackoverflow.com/questions/51379621/webdriverio-element-exists-after-api-call-test-is-flaky](url)

## Environment

    "wdio": "2.0.2",
    "wdio-cucumber-framework": "2.1.0",
    "wdio-selenium-standalone-service": "0.0.10",
    "wdio-spec-reporter": "0.1.4",
    "webpack": "4.12.0",
    "webpack-cli": "3.0.6",
    "webpack-dev-server": "3.1.4"

## Details

        `npm` scripts to be executed:
        "test": "npm run test:run && npm run test:report",
        "test:report": "nyc report --temp-directory=test/coverage --reporter=lcov --report-dir=test/report",
        "test:run": "cross-env BABEL_ENV=test wdio test/wdio.conf.js"

Below is the output from jenkins:

   342 passing (329.10s)    
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! edsp-ui@0.119.0-0 test:run: `cross-env BABEL_ENV=test wdio test/wdio.conf.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the edsp-ui@0.119.0-0 test:run script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Please find below code:

```
`async function iWaitForTheComponentToContain(
  subElement,
  subElementType,
  component,
  componentType,
  isRequired,
  matchType,
  expected,
) {
  isRequired = isRequired === 'eventually';
  expected = parseTemplateString(expected);
  const { selectors } = generateSelectors(componentType, component);
  if (subElement) {
    const selector = generateSelectors(subElementType, subElement).selectors;
    selectors.push(...selector);
  }
  // wait until the containing element exists
  const id = await getElementId(selectors);
  return browser.waitUntil(async () => {
    const actual = await browser.elementIdText(id);
    const isMatch = {
      match: actual.value === expected,
      contain: !!actual.value.match(expected),
    }[matchType];
    return isMatch === isRequired;
  });
}

When(
  /^I (?:wait for|expect) the (?:"([^"]*)" (component|element|item|button) in the )?"([^"]*)" (component|element|item) to (eventually|not) (match|contain) "([^"]*)"$/,
  { wrapperOptions: { retry: 2 }, timeout },
  iWaitForTheComponentToContain,
);

When(
  /^The number of "([^"]*)" elements in the "([^"]*)" (component|element|dropdown) should eventually be (more than|less than|equal to) "([^"]*)"$/,
  { wrapperOptions: { retry: 2 }, timeout },
  (elementsToCount, parent, parentType, comparator, name) => {
    const { selectors } = generateSelectors(parentType, parent);
    const expected = parseFloat(parseTemplateString(name));
    return browser.waitUntil(async () => {
      const actual = await countElements(selectors, elementsToCount);
      return {
        'more than': actual > expected,
        'less than': actual < expected,
        'equal to': actual === expected,
      }[comparator];
    });
  },
);`
```

**Comment by christian-bromann** [comment]
How is this suppose to be a wdio error? Not sure how I can help here?

**Comment by valaydesai3** [comment]
The tests are failing randomly. It would be great if anyone can help out here on how to make sure api call is made successfully and received response. Otherwise it throws 
```
function timed out, ensure the promise resolves within 10000 milliseconds

running chrome

Error: function timed out, ensure the promise resolves within 10000 milliseconds
```

**Comment by christian-bromann** [comment]
You code looks like you are mixing async and sync. Are you running wdio in sync mode (default)? That being said the error message seems to be clear. Your waitUntil condition never resolves. I doubt this is a bug. Please investigate, it is impossible for me to make any assumptions.

**Comment by christian-bromann** [comment]
> "wdio": "2.0.2",

Also this is not a supported package from WebdriverIO, you shouldn't use it if you are not really intend to do.

**Comment by valaydesai3** [comment]
`sync: false` in wdio.config.js and which version of wdio should I use ? `Your waitUntil condition never resolves.` - may I know what could be the solution for that ?

**Comment by christian-bromann** [comment]
> which version of wdio should I use ?

wdio is the cli command that comes with webdriverio .. that dependency is obsolete!

> may I know what could be the solution for that ?

something you run in the waitUntil condition never returns and times out. No idea what this can be as I don't know your code. Try to debug it (set some console.logs) to understand the issue.

**Comment by valaydesai3** [comment]
Tried to find the issue with wait Until in my code but couldn't able to. On local system, all tests are working fine. It fails only while running in Jenkins pipeline.

**Comment by erwinheitzman** [comment]
@valaydesai3 have you tried to simply increase the waitforTimeout to a pretty high number (60000) to see if it still fails? Remote VM's are almost always slower then your desktop/laptop.

**Comment by valaydesai3** [comment]
Yes I tried timeout of 1 minute but it's still same result.

**Comment by valaydesai3** [comment]
As per @christian-bromann, what's wrong with waitUntil in the code ?

**Comment by christian-bromann** [comment]
@valaydesai3 the condition never resolves because something takes too long. Please try to narrow down the issue to the test that is failing. Chances are that a command promise is not handled properly. I also recommend to use wdio with sync:true for exact this reason.
