### ISSUE TITLE
Support isKeyboardShown command

### ISSUE THREAD

**Issue by huaphuoctruong** [webdriverio/webdriverio#2810]
## The problem

Currently Appium has support isKeyboardShow (http://appium.io/docs/en/commands/device/keys/is-keyboard-shown/) which is very useful in case of someone would like to detect the keyboard is present or not as an test case. What is more, some service like browserstack also auto capture a screenshot everytime appium throw an error and it make the logs a little bit noisy because in order to follow the POM, sometime our button will be hidden by the keyboard and we need to make sure that the button is visible before doing click action, so we always call the hidedevicekeyboard and always see an error screenshot before every click.

**Comment by christian-bromann** [comment]
@huaphuoctruong agree, feel free to propose a PR

**Comment by khanhdodang** [comment]
@christian-bromann @huaphuoctruong I fixed on https://github.com/webdriverio/webdriverio/pull/2848

**Comment by christian-bromann** [comment]
Let's continue convo in #2848
