### ISSUE TITLE
Automate Fingerprint Authentication in Android emulator

### ISSUE THREAD

**Issue by mahatosourav91** [webdriverio/webdriverio#2812]
## The problem
I want to automate Fingerprint Authentication in Android emulator. How to do it using webdriverio? I tried to use touchId but it says 'Method not implemented'.

## Environment
Android

* WebdriverIO version: ^4.12.0
* Node.js version: v8.9.4
* WDIO Testrunner mode
* if wdio testrunner, running synchronous or asynchronous tests: synchronous tests
* Additional wdio packages used (if applicable):
    "wdio-appium-service": "^0.2.3",
    "wdio-mocha-framework": "^0.5.13",
    "wdio-sauce-service": "^0.4.8",
    "chai-webdriverio": "^0.4.3",

## Details
I want to automate Fingerprint Authentication in Android emulator. How to do it using webdriverio? I tried to use touchId but it says 'Method not implemented'.

Also, I am using saucelabs, so is there any requirements to set anything in desired capabilities?

**Comment by wswebcreation** [comment]
There is only a [touchID](http://appium.io/docs/en/commands/device/simulator/touch-id/) endpoint for iOS not for Android . It's currently not supported by Appium so a PR will not help

**Comment by wswebcreation** [comment]
@christian-bromann 

This might be fixed by a new release for Appium, see this commit for `1.9.2.-beta.1`, see [this commit](https://github.com/appium/appium/commit/c6be5fe9d219aaf4e31acbc5a0325986ae3cfd18)

So maybe keep it open and wait for Appium to make a new release

**Comment by christian-bromann** [comment]
This command will be supported with the next Webdriver package release. If you want to add support for v4, feel free to provide a PR to the v4 branch.
