### ISSUE TITLE
URL won't open with wdio test runner

### ISSUE THREAD

**Issue by Meerkat123890** [webdriverio/webdriverio#2815]
## The problem

While running wdio test runner, URL is not opening either on Firefox or on Chrome. Browser opens but URL does no open.

Disabled Firewall and tried. But, URL still won't open.

var webdriverio = require('webdriverio')
describe("Test Jasmine", function(){
	it("Test1", function(){
		browser.url("https:\\webdriver.io\\api.html")
		console.log("Test1")	
	})	
})

## Environment

* WebdriverIO version: 4.13.1
* Node.js version: 8.11.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): 
wdio-jasmine-framework
* Selenium-standalone running: 3.12.0
* Windows: 10
* Chrome : 67.0.3396.99
* Firefox : 61.0.1

## Details
Config file:
exports.config = {
    
    //
    // ==================
    // Specify Test Files
    // ==================
    // Define which test specs should run. The pattern is relative to the directory
    // from which `wdio` was called. Notice that, if you are calling `wdio` from an
    // NPM script (see https://docs.npmjs.com/cli/run-script) then the current working
    // directory is where your package.json resides, so `wdio` will be called from there.
    //
    specs: [
        '../../scripts/Junk_testScript1.spec.js'
    ],
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    //
    // ============
    // Capabilities
    // ============
    // Define your capabilities here. WebdriverIO can run multiple capabilities at the same
    // time. Depending on the number of capabilities, WebdriverIO launches several test
    // sessions. Within your capabilities you can overwrite the spec and exclude options in
    // order to group specific specs to a specific capability.
    //
    // First, you can define how many instances should be started at the same time. Let's
    // say you have 3 different capabilities (Chrome, Firefox, and Safari) and you have
    // set maxInstances to 1; wdio will spawn 3 processes. Therefore, if you have 10 spec
    // files and you set maxInstances to 10, all spec files will get tested at the same time
    // and 30 processes will get spawned. The property handles how many capabilities
    // from the same test should run tests.
    //
    maxInstances: 10,
    //
    // If you have trouble getting all important capabilities together, check out the
    // Sauce Labs platform configurator - a great tool to configure your capabilities:
    // https://docs.saucelabs.com/reference/platforms-configurator
    //
    capabilities: [{
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        maxInstances: 5,
        //
        browserName: 'chrome',

        port: 4444
    }],
    //
    // ===================
    // Test Configurations
    // ===================
    // Define all options that are relevant for the WebdriverIO instance here
    //
    // By default WebdriverIO commands are executed in a synchronous way using
    // the wdio-sync package. If you still want to run your tests in an async way
    // e.g. using promises you can set the sync option to false.
    sync: true,
    //
    // Level of logging verbosity: silent | verbose | command | data | result | error
    logLevel: 'silent',
    //
    // Enables colors for log output.
    coloredLogs: true,
    //
    // Warns when a deprecated command is used
    deprecationWarnings: true,
    //
    // If you only want to run your tests until a specific amount of tests have failed use
    // bail (default is 0 - don't bail, run all tests).
    bail: 0,
    //
    // Saves a screenshot to a given path if a command fails.
    screenshotPath: './errorShots/',
    //
    // Set a base URL in order to shorten url command calls. If your `url` parameter starts
    // with `/`, the base url gets prepended, not including the path portion of your baseUrl.
    // If your `url` parameter starts without a scheme or `/` (like `some/path`), the base url
    // gets prepended directly.
    baseUrl: 'https://webdriver.io/api.html',
    //
    // Default timeout for all waitFor* commands.
    waitforTimeout: 10000,
    //
    // Default timeout in milliseconds for request
    // if Selenium Grid doesn't send response
    connectionRetryTimeout: 90000,
    //
    // Default request retries count
    connectionRetryCount: 3,
    //
    // Initialize the browser instance with a WebdriverIO plugin. The object should have the
    // plugin name as key and the desired plugin options as properties. Make sure you have
    // the plugin installed before running any tests. The following plugins are currently
    // available:
    // WebdriverCSS: https://github.com/webdriverio/webdrivercss
    // WebdriverRTC: https://github.com/webdriverio/webdriverrtc
    // Browserevent: https://github.com/webdriverio/browserevent
    // plugins: {
    //     webdrivercss: {
    //         screenshotRoot: 'my-shots',
    //         failedComparisonsRoot: 'diffs',
    //         misMatchTolerance: 0.05,
    //         screenWidth: [320,480,640,1024]
    //     },
    //     webdriverrtc: {},
    //     browserevent: {}
    // },
    //
    // Test runner services
    // Services take over a specific job you don't want to take care of. They enhance
    // your test setup with almost no effort. Unlike plugins, they don't add new
    // commands. Instead, they hook themselves up into the test process.
    // services: [],//
    // Framework you want to run your specs with.
    // The following are supported: Mocha, Jasmine, and Cucumber
    // see also: http://webdriver.io/guide/testrunner/frameworks.html
    //
    // Make sure you have the wdio adapter package for the specific framework installed
    // before running any tests.
    framework: 'jasmine',
    //
    // Test reporter for stdout.
    // The only one supported by default is 'dot'
    // see also: http://webdriver.io/guide/reporters/dot.html
    // reporters: ['dot'],
    //
    // Options to be passed to Jasmine.
    jasmineNodeOpts: {
        //
        // Jasmine default timeout
        defaultTimeoutInterval: 9999999,
        //
        // The Jasmine framework allows interception of each assertion in order to log the state of the application
        // or website depending on the result. For example, it is pretty handy to take a screenshot every time
        // an assertion fails.
        expectationResultHandler: function(passed, assertion) {
            // do something
        }
    }
}

Selenium standalone log:
D:\JasmineFramework\node_modules\.bin>selenium-standalone start
13:02:17.299 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.12.0', revision: '7c6e0b3'
13:02:17.300 INFO [GridLauncherV3$1.launch] - Launching a standalone Selenium Server on port 4444
2018-07-22 13:02:17.369:INFO::main: Logging initialized @251ms to org.seleniumhq.jetty9.util.log.StdErrLog
13:02:17.583 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
Selenium started
13:02:45.995 INFO [ActiveSessionFactory.apply] - Capabilities are: Capabilities {browserName: chrome, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., maxInstances: 5, requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.13.1}, rotatable: true}
13:02:45.996 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab) on port 32979
Only local connections are allowed.
13:02:48.312 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
13:02:48.514 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 4752365be39266f0e3ef43113754fc38 (org.openqa.selenium.chrome.ChromeDriverService)
13:03:09.868 INFO [ActiveSessions$1.onStop] - Removing session 4752365be39266f0e3ef43113754fc38 (org.openqa.selenium.chrome.ChromeDriverService)
13:06:56.315 INFO [ActiveSessionFactory.apply] - Capabilities are: Capabilities {browserName: chrome, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., maxInstances: 5, requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.13.1}, rotatable: true}
13:06:56.315 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab) on port 42328
Only local connections are allowed.
13:06:58.353 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
13:06:58.388 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session e52df38b41c85fdbbc5161d34a3e8d35 (org.openqa.selenium.chrome.ChromeDriverService)
13:07:19.750 INFO [ActiveSessions$1.onStop] - Removing session e52df38b41c85fdbbc5161d34a3e8d35 (org.openqa.selenium.chrome.ChromeDriverService)
13:07:48.962 INFO [ActiveSessionFactory.apply] - Capabilities are: Capabilities {browserName: chrome, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., maxInstances: 5, requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.13.1}, rotatable: true}
13:07:48.963 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab) on port 14643
Only local connections are allowed.
13:07:50.950 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
13:07:50.973 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 96ef69cec6483da478ffe0d72d576c8b (org.openqa.selenium.chrome.ChromeDriverService)
13:07:51.193 INFO [ActiveSessions$1.onStop] - Removing session 96ef69cec6483da478ffe0d72d576c8b (org.openqa.selenium.chrome.ChromeDriverService)
13:10:06.819 INFO [ActiveSessionFactory.apply] - Capabilities are: Capabilities {browserName: chrome, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., maxInstances: 5, requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.13.1}, rotatable: true}
13:10:06.819 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab) on port 27516
Only local connections are allowed.
13:10:08.848 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
13:10:08.874 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session b867a26b65a5617e8c6065a2ce50d677 (org.openqa.selenium.chrome.ChromeDriverService)
13:10:09.097 INFO [ActiveSessions$1.onStop] - Removing session b867a26b65a5617e8c6065a2ce50d677 (org.openqa.selenium.chrome.ChromeDriverService)
13:11:58.716 INFO [ActiveSessionFactory.apply] - Capabilities are: Capabilities {browserName: chrome, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., maxInstances: 5, port: 4444, requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.13.1}, rotatable: true}
13:11:58.716 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab) on port 13490
Only local connections are allowed.
13:12:00.702 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
13:12:00.746 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 57eda3d36fc2a7803a76863cb2633046 (org.openqa.selenium.chrome.ChromeDriverService)
13:12:22.145 INFO [ActiveSessions$1.onStop] - Removing session 57eda3d36fc2a7803a76863cb2633046 (org.openqa.selenium.chrome.ChromeDriverService)
13:17:55.834 INFO [ActiveSessionFactory.apply] - Capabilities are: Capabilities {browserName: chrome, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., maxInstances: 5, port: 4444, requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.13.1}, rotatable: true}
13:17:55.834 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab) on port 2620
Only local connections are allowed.
13:17:57.865 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
13:17:57.899 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session fe74f294d61743d7fb03ea79ca874e58 (org.openqa.selenium.chrome.ChromeDriverService)
13:18:19.254 INFO [ActiveSessions$1.onStop] - Removing session fe74f294d61743d7fb03ea79ca874e58 (org.openqa.selenium.chrome.ChromeDriverService)

**Comment by erwinheitzman** [comment]
Your url is invalid as the site does not use https, use this instead (and use forward slashes, backslashes are never used in url's): http://webdriver.io/api.html
