### ISSUE TITLE
Can't access the selenium-standalone service behind a proxy.

### ISSUE THREAD

**Issue by teelicht** [webdriverio/webdriverio#2817]
## The problem

At work, I need to run a local Squid proxy in order to circumvent the NTLM proxy authentication of our corporate proxy. As mentioned in the webdriverIO documentation, I added the following line to my wdio.conf file: `proxy: 'http://localhost:4321',`. However, when starting the test session, I receive the following error:
`A service failed in the 'onPrepare' hook
Error: Could not request headers from https://download.microsoft.com/download/F/8/A/F8AF50AB-3C3A-4BC4-8773-DC27B32988DD/MicrosoftWebDriver.exe: Error: getaddrinfo ENOTFOUND download.microsoft.com download.microsoft.com:443
    at Request.<anonymous> (C:\Users\AT0686689\Code\wdio-starter-kit\node_modules\selenium-standalone\lib\install.js:552:8)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Request.onRequestError (C:\Users\AT0686689\Code\wdio-starter-kit\node_modules\selenium-standalone\node_modules\request\request.js:877:8)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)`

More interestingly, In the same output, I get some Squid html output where the essential line is: `<p>The following error was encountered while trying to retrieve the URL: <a href="http://127.0.0.1:4444/wd/hub/session">http://127.0.0.1:4444/wd/hub/session</a></p>`.

Everything works as it should though, if I start selenium-standalone in a separate terminal and start the webdriverIO tests without using `services: ['selenium-standalone'],`.

Now, what is the difference between running selenium-standalone through the service hook or manually?

## Environment

* WebdriverIO version: 4.13.1
* Node.js version: 8.5.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: sync

**Comment by christian-bromann** [comment]
@teelicht running selenium standalone has nothing to do with your proxy. Depending on your proxy you need to set up this in your capabilities. Please have a look here: https://github.com/webdriverio/webdriverio/issues/324

If you can't find a solution please reach out in our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)] support channel. Thanks!

**Comment by teelicht** [comment]
@christian-bromann : probably I have not explained myself clearly enough. I'm aware of the possibility to add username:password to the proxy config but this is not the issue here.

The question boils down to why I'm not able to connect to selenium-standalone through the local proxy when starting it via `services: ['selenium-standalone']` while this works when starting it manually in a second terminal window.

**Comment by christian-bromann** [comment]
> why I'm not able to connect to selenium-standalone

Not sure what you mean by that. You can also pass a proxy property to the selenium-standalone options: https://github.com/vvo/selenium-standalone#example
