### ISSUE TITLE
An unknown server-side error occurred after while setValue in Chrome

### ISSUE THREAD

**Issue by ManaliPatel** [webdriverio/webdriverio#2821]
## The problem

When I use browser.setValue in chrome - it throws error stating Error: An unknown server-side error occurred while processing the command.

Only happens in chrome, works in Safari.

 > browser.setValue('.email-input', 'manali')
Error: An unknown server-side error occurred while processing the command.
    at evalmachine.<anonymous>:1:9
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.exports.runInThisContext (vm.js:77:17)
    at node_modules/webdriverio/build/lib/commands/debug.js:54:43
    at elementIdValue("0.9590483459116679-1", "manali") - setValue.js:46:80

## Environment

* WebdriverIO version: 4.13.1
* Node.js version: v6.9.2
* using wdio testrunner
* ChromeDriver 2.40.565386
* browser chrome V. 67

**Comment by christian-bromann** [comment]
This is probably connected to a Chrome issue. Please check the Chromedriver logs. If you have further questions, feel free to join our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) support channel. Cheers!
