### ISSUE TITLE
Multiremote support for multiple specs 

### ISSUE THREAD

**Issue by adrian-brown** [webdriverio/webdriverio#2825]
## The problem

Missing feature of being able to run multiremote tests in locally and cloud services like Saucelabs or Browserstack correctly.  When you have more than one spec defined as multiremote test then you want Saucelabs or BrowserStack to spin up new VMs per spec. Currently it uses the same VM for all the multiremote specs, and soon exhausts itself.  This is seen locally also.

## Environment

* WebdriverIO version: 4.13.1 and v5
* Node.js version: 8.6.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable):  `wdio-sauce-service`

## Details

Run multiremote tests (more than 1 spec) on saucelabs or browserstack and the wdio launcher will use the initial pair (or however many you declare) of VMs across all your tests.  It should dispose of the VMs at the end of the test and create new ones by default.  It is not expected to run the tests in parallel so this is not required (maxInstances support).  Looking at `launcher.js` multiremote tests will only every run one `processNumber` with a single `cid` despite different tests starting.  The process count remains the same.

## Link to Selenium/WebdriverIO logs

N/A

## Code To Reproduce Issue [ Good To Have ]

Run the example multiremote in saucelabs from wdio runner, but duplicate the test to have more than 1 multiremote spec to run.

**Comment by kevinmcdonnell** [comment]
We're interested in using multiremote but wondering if we will run into issues like this where features are built only for the normal one browser session.

Are there known gaps other than open issues?

**Comment by adrian-brown** [comment]
Running on saucelabs is the bit I'd like to work correctly.  But I can see why it may not fit.

Apart from that if you run on your own grid or local setup it's absolutely fine, and a very elaborate way of performing real integration testing with more than 1 user in a test flow.  I've remained on latest version of v4 so I can't comment on v5 issues.  We're stable with v4.

**Comment by mgpsp** [comment]
I'm also facing the same problem. Will this be implemented anytime soon?

**Comment by christian-bromann** [comment]
> Will this be implemented anytime soon?

Please see the `help wanted` label 😉

**Comment by mgrybyk** [comment]
@adrian-brown @mgpsp @kevinmcdonnell 

You are saying that in case there are, lets say 10 spec files, you want to run them in parallel in all your browsers it is not possible?
Tests are running only one by one?

Have I understood the problem correctly?

**Comment by kevinmcdonnell** [comment]
Apologies for the delay. Yes that's correct

**Comment by adrian-brown** [comment]
But also running on saucelabs will mean it won't spin up new instances per test, intead uses the same VM and that won't work (time will run out eventually).

**Comment by mgrybyk** [comment]
Let's fix main issue first and rise another one for saucelabs if the issue persists there

**Comment by adrian-brown** [comment]
by fixing this, running in Sauce / browserstack will just work.

**Comment by mgrybyk** [comment]
@adrian-brown amazing!

**Comment by adrian-brown** [comment]
is this for v4 / v5? @mgrybyk

**Comment by mgrybyk** [comment]
V5 only

**Comment by adrian-brown** [comment]
:+1:
