### ISSUE TITLE
Safari issue with iframe and pushState

### ISSUE THREAD

**Issue by sfishel18** [webdriverio/webdriverio#2826]
## The problem

My application is a hybrid of a parent window and iframe.  Some user interactions inside the iframe can result in a pushState update to the URL of the parent window.  When I try to write a webdriverio test that performs those actions, I get errors in Safari.

## Environment

* WebdriverIO version: 4.13.1
* Node.js version: 8.4.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): none

## Details

This is the error I see:

```
A request to switch to a frame could not be satisfied because the frame could not be found.
```

It always happens the first time the test code tries to interact with iframe contents after performing an action that causes URL update to the parent window.  This error always happens in Safari, never in Chrome or Firefox.

## Link to Selenium/WebdriverIO logs

How do I capture these?

## Code To Reproduce Issue [ Good To Have ]

index.html (assume this file is being served at localhost:8081):

```
<!DOCTYPE html>
<html>

<head>
    <title>WebdriverIO Example</title>
    <script>
        window.updateUrl = function() {
            var newUrl = window.location.protocol + "//" + window.location.host + '/' + Date.now();
            window.history.pushState({}, '', newUrl)
        }
    </script>
</head>

<body>
    <iframe name="my-iframe" src="./frame.html"></iframe>
</body>

</html>
```

frame.html:

```
<!DOCTYPE html>
<html>

<body>
    <h1 id="heading-inside-frame">Heading Text</h1>
    <button id="button-inside-frame" onClick="javascript:window.parent.updateUrl()">Click Here</button>
</body>

</html>
```

test.js:

```
var assert = require('assert');

describe('iframe bug', function() {
    it('should be able to preserve iframe context even if URL changes', function () {
        // Load the page and change to the iframe context
        browser.url('http://localhost:8081');
        const frame = browser.$('iframe[name="my-iframe"]').value;
        browser.frame(frame);

        // Clicking this button will result in a pushState change to the URL in the parent window
        browser.click('#button-inside-frame');

        // Safari will will throw a "frame could not be found error" here
        var headingText = browser.getText('#heading-inside-frame');
        assert.equal(headingText, 'Heading Text');
    });
});
```

**Comment by christian-bromann** [comment]
This is not an issue of WebdriverIO. It can only send the commands to the driver. It looks like this is more related to Safaridriver. Please raise an issue there. Thanks!
