### ISSUE TITLE
execute() fails on IEDriver >= 3.5

### ISSUE THREAD

**Issue by savsav** [webdriverio/webdriverio#2833]
## The problem

execute() fails to execute js code on IE11 as IEDriver >= 3.5 expects requests to be sent to:

> /session/[session-id]/execute/sync

instead of:

> /session/[session-id]/execute

(it has become W3C compliant - https://www.w3.org/TR/webdriver/#execute-script).

WebdriverIO sends the payload to '/ssessionid/execute' and there is an error message in the IE driver log:
`{ "value" : { "error" : "unknown method", "message" : "Command not found: POST /session/<session-id>/execute" }`

The error displayed in the console is:

> Error: Remote end send an unknown status code.

## Environment

* WebdriverIO version: 4.13.1
* Node.js version: 8.9.3
* wdio testrunner synchronous test
* Browser: IE11
* Driver: latest IEDriver (3.5 - 3.14) (works on 3.4)

## Details

<details>
  <summary>
    Show IEDriver log
  </summary>
  D 2018-08-07 13:45:29:822 c:\projects\webdriver\cpp\webdriver-server\server.cc(340) Command: POST /session/93b5767b-238f-445b-9365-65d377e98863/execute {"script":"var test = 777","args":[]}
  D 2018-08-07 13:45:29:822 c:\projects\webdriver\cpp\webdriver-server\server.cc(416) Response: { "value" : { "error" : "unknown method", "message" : "Command not found: POST /session/93b5767b-238f-445b-9365-65d377e98863/execute" }
</details>

[Full IEDriver log](https://gist.github.com/savsav/4e780e95724217a730254e52d5310fd2#file-iedriver-log)

## Code To Reproduce Issue

```javascript
describe('IE suite', function() {
  it('IE test', function() {
    browser.url('http://www.example.com');
    browser.execute('var test = 777');
  });
});
```

## Notes

Reproduces for executeAsync() as well.

**Comment by DarkKnight711** [comment]
I think this is related to [Issue 2828](https://github.com/webdriverio/webdriverio/issues/2828).
