### ISSUE TITLE
[Typescript] Outdated type definitions

### ISSUE THREAD

**Issue by ania-s** [webdriverio/webdriverio#2836]
## The problem
The type definitions seems to be outdated, for example: touchAction:
touchAction(selector: string, action: 'tap' | 'press'): Client<T>;
while the othe actions can be used according to webdriver.io documentation
http://webdriver.io/api/mobile/touchAction.html

## Environment

* WebdriverIO version: 4.13.1
* @types/webdriverio@^4.10.3
* "wdio": "^2.0.2",
* "wdio-appium-service": "^0.2.3",
* "wdio-cucumber-framework": "^2.1.0",
* "wdio-json-reporter": "^0.3.1"

**Comment by christian-bromann** [comment]
This will be covered in #2862
