### ISSUE TITLE
Calling a 3rd party method with callback is not working

### ISSUE THREAD

**Issue by NaveenThiyagarajan** [webdriverio/webdriverio#2842]
I have a 3rd method to make API calls. The npm-module used is `request`. The method that makes the post call takes callback as argument. So i was told that i need to wrap the 3rd party callback methods inside promise to make it work in WDIO. I tried the below but it did not worked.

## Environment:

- WDIO version: 4.13.1
- nodejs version: 8.6.0
- Using wdio runner with `sync:true` option
- Using cucumber framework and the problem i am facing is with `request` npm module.
- Using babel compiler

## Details

Here is the code details:

The `makepost` method which makes use of the `request` module's `post` method(which takes callback as parameter) and which is wrapped promise and returning a promise.

```
makePost(env, userAccount, canonical, isItQuery){
    let options = { ..... };
    return new Promise(function(resolve, reject){
        request.post(options,function(error, response){
            logger.info('In to the callback of request post');
            if(!error){
                resolve(response);
            }
            else{
                reject(error);
            }                
        });
    });
}
```
And i tried calling the above method inside stepDefinition like this:
```
import {defineSupportCode} from 'cucumber';
import config from 'config';
import fs from 'fs';
import rm from '../utills/restMaker';
require('request').debug = true;

defineSupportCode(function({Given, When, Then}){
    Given(/^Run the "([^"]*)" with user_session of "([^"]*)"$/, (canonical, user_session) => {
rm.makePost(env,userAccountID,payloadName,true).then(function(resp) {
        console.log('Response: ' + resp);
    })
    .catch(function(error){
        console.log("ERROR: " + error);
    })
    });
});
```

During the execution the script is not waiting for the response from `request.post` method ... and execution is getting completed without its response ... Please help me how i can make this work ...

Sorry, i am not sure this is an issue but i tried fixing it by some research and then posted the question in stachOverflow: https://stackoverflow.com/questions/51791594/how-to-use-3rd-party-method-that-takes-callback-in-webdriverio

and in the https://gitter.im/webdriverio/webdriverio . but i did not get any working response.. so came to wdio issues list as a final resort/rescue with your expert commands. 

If you can help me sample code how to make this work will be a great help. Thank you so much!! and once again sorry for posting as issue.

**Comment by christian-bromann** [comment]
try
```js
makePost(env, userAccount, canonical, isItQuery){
    let options = { ..... };
    browser.call(() => {
	    return new Promise(function(resolve, reject){
	        request.post(options,function(error, response){
	            logger.info('In to the callback of request post');
	            if(!error){
	                resolve(response);
	            }
	            else{
	                reject(error);
	            }                
	        });
	    });
	})
}
```

Let me know if that works.

**Comment by NaveenThiyagarajan** [comment]
thanks a lot @christian-bromann .. it worked .. :) 👍
