### ISSUE TITLE
[Typescript] Multiremote support

### ISSUE THREAD

**Issue by ania-s** [webdriverio/webdriverio#2847]
## The problem

I wanted to have the tests running between two or more devices to support e.g. the following scenario: make a change on an account on Android, sync, check in browser using the same account that the change was synced. 
I have the tests written in typescript and they work fine on one device, however, when I added the second device in wdio config file I am not sure how to select a specific device afterwards from the tests. According to the docs (http://webdriver.io/guide/usage/multiremote.html) `select` method should be used for that but it doesn't work for me in typescript. I tried to see what multiremote provides in typescript but cannot find anything that would let me access a specific device from multiple defined in the config file. 
Is it exposed in typescript and if yes can you please help me saying how I can use it?

## Environment

- WebdriverIO version: 4.13.1
- @types/webdriverio@^4.10.3
- "wdio": "^2.0.2",
- "wdio-appium-service": "^0.2.3",
- "wdio-cucumber-framework": "^2.1.0",
- "wdio-json-reporter": "^0.3.1"

**Comment by christian-bromann** [comment]
@ania-s our typescript support for multiremote could be better. Feel free to make improvements to the definitelytyped repo.

**Comment by christian-bromann** [comment]
This will be covered in #2862
