### ISSUE TITLE
NoSuchElement is not thrown as error

### ISSUE THREAD

**Issue by deep9** [webdriverio/webdriverio#2849]
## The problem

Nonexistent element does not throw error, as described in (http://webdriver.io/api/protocol/element.html) Is there a reason for that? It was changed 2 years ago in the code.

## Environment

* WebdriverIO version: 4.12.0
* Node.js version: 8.9.4
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): standalone
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable): N/A

## Details

While trying to locate element using /element endpoint, non-existent element returns seleniumStack object with status: 'failure'.

## Code To Reproduce Issue [ Good To Have ]

browser.element('hello').then(result => { console.log(result); });

**Comment by christian-bromann** [comment]
> Is there a reason for that?

Yes, it allows to lazy load elements like:
```js
var elem = $("#elem")
// do other stuff until elem is available or call elem.waitForExist()
elem.click()
```

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by deep9** [comment]
Understood, but then the docs should be updated, this is misleading.

**Comment by christian-bromann** [comment]
@deep9 feel free to propose a PR
