### ISSUE TITLE
Vulnerability with wdio-iedriver-service

### ISSUE THREAD

**Issue by krisraven** [webdriverio/webdriverio#2850]
## The problem

The wdio-iedriver-service package is using Arbitrary File Write via Archive Extraction (adm-zip) but the current 0.1 version of wdio-iedriver-service is using a version that is below the recommended version 0.4.9 of adm-zip. For more info: https://nodesecurity.io/advisories/681

Is there a workaround available or fix for this?

**Comment by christian-bromann** [comment]
Please propose a fix in the service project (https://github.com/atti187/wdio-iedriver-service#readme). Thanks!

**Comment by krisraven** [comment]
Thanks. For future reference, I've created this; https://github.com/atti187/wdio-iedriver-service/issues/3
