### ISSUE TITLE
Looking for POM example with multiple pages

### ISSUE THREAD

**Issue by shridharkalagi** [webdriverio/webdriverio#2851]
Can someone pls share an example with Page Object Pattern with navigation to multiple pages?

**Comment by christian-bromann** [comment]
You can find an example with a PO pattern here: https://github.com/webdriverio/webdriverio/tree/master/examples/pageobject

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
