### ISSUE TITLE
command keys fails in firefox

### ISSUE THREAD

**Issue by rostik404** [webdriverio/webdriverio#2855]
## The problem

I have a problem with keys command in the firefox
My code:
```js
return browser
        .init()
        .url('https://yandex.ru')
        .keys('\uE00C')
        .catch((e) => console.log(e))
        .end();
```

this example fails on command keys with error: `The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.`

## Environment

* WebdriverIO version: 4.13.2
* Node.js version: 8.4.0
* selenium standalone version: 6.15.1
* firefox driver version: 0.21.0

## Link to Selenium/WebdriverIO logs

https://gist.github.com/rostik404/ae49f90f266cf714ba788e0c8b85d991

## Code To Reproduce Issue [ Good To Have ]

```js
const webdriverio = require('webdriverio');
 
var browser = webdriverio.remote({
    host: 'localhost',
    port: '4444',
    path: '/wd/hub',
    desiredCapabilities: {
        browserName: 'firefox',
        version: '61',
        acceptInsecureCerts: true
    },
    connectionRetryTimeout: 60000,
    connectionRetryCount: 0
});
 
function testLocal() {
    return browser
        .init()
        .url('https://yandex.ru')
        .keys('\uE00C')
        .catch((e) => console.log(e))
        .end();
}
 
testLocal();
```

**Comment by christian-bromann** [comment]
@rostik404 `keys` is not part of the WebDriver protocol and a depcrecated command in v4. It will be available again in v5. Use addValue or the actions command instead.
