### ISSUE TITLE
Add native support for shadow DOM

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#2858]
_From @christian-bromann on March 20, 2018 9:53_

Currently browser driver still have issues fetching shadow DOM elements. Support for this can enabled by a custom element call as implemented in [this plugin](https://github.com/Morlack/wdio-webcomponents). Let's bring this functionality into v5 as native support until drivers do fully support it.

_Copied from original issue: webdriverio/v5#44_

**Comment by christian-bromann** [comment]
_From @wolfoo2931 on March 25, 2018 16:17_

Would appreciate that, currently using a hacky solution ... https://twitter.com/WolfOliver/status/977941851327123457

**Comment by christian-bromann** [comment]
@wolfoo2931 feel free to propose a PR, for me this a low priority.

**Comment by christian-bromann** [comment]
_From @luckyincode on May 30, 2018 14:44_

Curious what the workaround is for now?  Is everyone using `wdio-webcomponents`?

**Comment by christian-bromann** [comment]
_From @junguchina on June 1, 2018 1:38_

@luckyincode No, I still not use `wdio-webcomponents`.

**Comment by christian-bromann** [comment]
_From @cheungkayip on June 22, 2018 8:55_

@luckyincode and @junguchina 
Did you get wdio-webcomponents to work with multi remote (I couldn't really get it to work)
everything starts with browser.getText('') or browser.setValue('') instead of browser.element('your-element')
I've tried doing myChromeBrowser en myFirefoxBrowser in the wdio.conf.js but it seems it responds differently than the original WebdriverIO implementation.

so i'm only using chrome right now...penny for your thoughts?

**Comment by christian-bromann** [comment]
> penny for your thoughts?

This is not the right place for this question. Please join the [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) channel.

**Comment by christian-bromann** [comment]
_From @diego-fernandez-santos on August 14, 2018 10:59_

I have a polymer application which I currently test in shady mode. I would like to be able to test my application in shadow mode without have to change my app selectors.

With the current version of wdio-webcomponents I have to change the selectors because I have to add the selectors of the parent web components. 

I think this make my tests flakier because any change in the web-components hierarchy has an impact in my test code.

I would like to be able to select any element I a similar way we did with "deep" or "shadow".

I did the following pull request to wdio-webcomponents to change this.
https://github.com/Morlack/wdio-webcomponents/pull/3

**Comment by christian-bromann** [comment]
_From @junguchina on August 16, 2018 2:25_

@diego-fernandez-santos Good idea！
Now our team use a hack way to locate the elements with current version of web components.

**Comment by diego-fernandez-santos** [comment]
I send you an extended version. This version has support to chain commands and also make easier the interaction with shadow elements through a new function (shadowExecute).

In the repository there are two samples:

- The first one (test1) add two new functions (shadowElement and shadowExecute) but not overwrite the existing element wdio command so the use of other wdio functions is little more complicated.

- The second one (test2) overwrite the element command and makes easier the interactions.

https://github.com/diego-fernandez-santos/wdio-shadow

**Comment by christian-bromann** [comment]
Let's wait until the working group has decided on how to move forward with shadow dom: https://github.com/w3c/webdriver/pull/1320

**Comment by ToygarM** [comment]
Hello @christian-bromann,

When are you planning to pick up this issue? My company is moving to Polymer applications and for now on webdriverio v5 there is no native solution for catching shadowDOM properties. It's way to hard to make it work! Is there a temporarily solution for this?

**Comment by abjerstedt** [comment]
@ToygarM feel free to propose a PR. We'll review it

**Comment by ToygarM** [comment]
Hello @diego-fernandez-santos after cloning your solution i can only run the tests on node.js. When trying to run in combination with mocha/wdio config.js the test is not running! I tried this with V4.8.0 and V5 and higher. Is there a reason for. I will appreciate when this pretty solution is running for V5 and higher in combination with wdio config.js.

**Comment by ToygarM** [comment]
@abjerstedt Will try to do my best! Thx!

**Comment by christian-bromann** [comment]
Landed in [`v5.5.0`](https://github.com/webdriverio/webdriverio/blob/master/CHANGELOG.md#550-2019-02-20)

**Comment by ToygarM** [comment]
Excellent work @christian-bromann! This will help our team enormous! Now we can move to version 5 :)

**Comment by junguchina** [comment]
@ToygarM Did you move to version 5.x and use the `shadow$$` or `shadow$` in your code?

**Comment by ToygarM** [comment]
@junguchina Yes! We moved to version 5.9.0 and we are using shadow$$ or shadow$ in our testcode. Goodluck! :)

**Comment by junguchina** [comment]
> @junguchina Yes! We moved to version 5.9.0 and we are using shadow$$ or shadow$ in our testcode. Goodluck! :)

Could you provide me simple code template？
I can not use shadow$$ or shadow$ with codeceptjs structure and I want to resolve this problem recentlly.
Thank you.

**Comment by ToygarM** [comment]
@junguchina I'm not sure if you can use shadow$$ or shadow$ in codeceptjs. There is a big chance that codeceptjs doesn't support Shadow Query en it doesn't make any sense to use it. Next to that what i know is that WebdriverIO is the only functional test automation framework which is supporting Shadow Dom Elements. If not possible you need to create a workaround or use plugin like web components.

I am not allowed to provide some sample code of the project, but i can deliver your the documentation which is pretty much almost the same. See: https://webdriver.io/docs/pageobjects.html

Investigation which framework fits the best in your project is important. Good luck! : 😉
