### ISSUE TITLE
Implement tag management for all frameworks

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#2859]
_From @christian-bromann on May 14, 2018 8:36_

Many people want to run tests having a specific set of tags. In v4 there was no tag detection and if you would use the framework functionality it would spawn up a browser and immediately close it.

Let's implement native support for this.

_Copied from original issue: webdriverio/v5#68_

**Comment by christian-bromann** [comment]
_From @BorisOsipov on May 14, 2018 8:37_

am I right, it is related to issue https://github.com/webdriverio/webdriverio/issues/1247 ?

**Comment by christian-bromann** [comment]
@BorisOsipov yes

**Comment by christian-bromann** [comment]
I doubt this is possible by using framework native capabilities. However if we could do that it would be amazing and way faster than some sort of file content regex matching.

**Comment by christian-bromann** [comment]
_From @id4automation on August 14, 2018 23:31_

Hiya, Any inputs on this is much appreciated.

**Comment by christian-bromann** [comment]
@id4automation Please see webdriverio/webdriverio#1247

**Comment by mgrybyk** [comment]
hey guys, I'm using simple wrapper function to manage tags like this:
```
it("my test", () => {
    // some test
}, { tags: [browser.isMobileApp] })

// or 

describe("my suite", () => {
    it("my test 1", () => { })
    it("my test 2", () => { })
}, { tags: [APP_REGION !== REGIONS.ASIA, !browser.isIOS] })
```

I'm passing optional array of booleans to `it` and `describe` blocks to control if suite/test should be executed. If one of condition is **false** test/suite is excluded from run, it is not marked as skipped.

It helps me a lot to organize tests in functional way and avoid grouping them by platforms, reports for different test configurations won't contain skipped reports of unsupported platforms.

**Comment by baruchvlz** [comment]
@christian-bromann Are we still thinking about implementing this?

**Comment by mgrybyk** [comment]
I'd say yes! And now it's finally possible thanks to #4531 

You wanna deal with it?

**Comment by baruchvlz** [comment]
@mgrybyk I'll try, will let you know if I come up across any roadblocks.

**Comment by mgrybyk** [comment]
Do you have any vision on how it should work in the end?

**Comment by christian-bromann** [comment]
it would be great if we could leverage the tagging functionality of the frameworks and combine it with the use case of cross browser testing, e.g. allow to tag specific tests to be only run in browserX and skipped in other browser. This is just an idea though, first we should really define what we want to do here.

**Comment by christian-bromann** [comment]
This issue has derived from the original problem which is partially solved. Closing as #4887 describes outstanding issue in better detail.
