### ISSUE TITLE
Sanitize error stack

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#2865]
_From @christian-bromann on March 19, 2018 16:5_

## The problem

Stack traces are usually filled with lines that neither belong to WebdriverIO nor to the test spec. Let's make sure we clean the stack trace to only include traces from the test spec and within WebdriverIO.

_Copied from original issue: webdriverio/v5#43_

**Comment by emilyrohrbough** [comment]
Can we have an opt-in logging config option if this is implemented? There are a few instances where this is pretty useful. For example:

- New selenium session failed - This one **could be** indicated by webdriver.io,  though I wouldn't say is webdriver.io's responsibility. We have experienced selenium-grid timeout issues and the stack track as confirmed the issue wasn't test or webdriver.io configuration issues
- wdio-screenshot / wdio-visual-regression-service -- errors are often seen from these 3rd party tools which have no clear indication as to why an error occurred and digging through the stack trace / source code uncovered the reason
- Custom services errors - while writing custom commands, injecting chia assertion helpers, etc into a service this trace is helpful. Not sure how or if this might be differentiated as trace that should be included

**Comment by rsinghi** [comment]
When will this issue be resolved? We have been hearing feedback in the team around how having the exact lines in stack trace will be useful in debugging.

**Comment by caoxu2000** [comment]
@christian-bromann I'd like to work on this but can I get some pointers to where to start from you whenever you get a chance?  I haven't been able to understand the whole picture of error handling architecture of wdio yet

**Comment by christian-bromann** [comment]
Duplicate of #2711
