### ISSUE TITLE
GOVERNANCE.md changes

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#2868]
_From @BorisOsipov on April 24, 2018 19:28_

## The problem

Webdriverio v5 is going to be monorepo project. It will require appropriate changes in [GOVERNANCE.md](https://github.com/webdriverio/v5/blob/master/GOVERNANCE.md#project-committers) document to handle PR\issues.

e.g.:

> WebdriverIO has a large ecosystem of repositories. Some are 'core' in the sense of being central subpackages with a lot of traffic like webdriverio/webdriverio. Others are 'peripheral' in the sense of receiving few changes, being maintained by 1 person or no one, etc..., like webdriverio/cucumber-boilerplate or webdriverio/jasmine-boilerplate. For 'core' repos, committers should not merge their own code straightaway. Like all contributors they should open a PR and get a +1 from another committer. For 'peripheral' repos for which they are the sole maintainer or for which they have a good understanding, it is obtuse to insist on another contributor's +1 and this rule should be relaxed in that case. In sum: use good judgment and don't ram code through without a review when you can help it.

_Copied from original issue: webdriverio/v5#63_

**Comment by christian-bromann** [comment]
_From @BorisOsipov on April 24, 2018 19:30_

just to don't forget.

**Comment by christian-bromann** [comment]
@BorisOsipov can you elaborate what exactly you are missing in the governance.md?

**Comment by BorisOsipov** [comment]
Hmm I read again this doc and it is ok.

**Comment by christian-bromann** [comment]
Closing then.
