### ISSUE TITLE
Validate capabilities

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#2870]
_From @christian-bromann on May 8, 2018 13:12_

The W3C protocol only accepts certain type of capabilities and throws an error if these are not existing or unknown are added. Let's make sure we handle this gracefully.

_Copied from original issue: webdriverio/v5#66_

**Comment by christian-bromann** [comment]
_From @kmnaid on June 12, 2018 18:11_

@christian-bromann : Is there validation of capabilities currently? If so which file is the check in? I wasn't able to locate it.
Some references to start working on this would be helpful.

**Comment by christian-bromann** [comment]
I guess a good start is https://github.com/webdriverio/v5/blob/master/packages/wdio-config/src/utils.js#L76 I can see it being implemented somewhere else in the `webdriver` package. I think there isn't necessary this one position where it should implemented.

**Comment by emilyrohrbough** [comment]
https://www.w3.org/TR/webdriver1/#capabilities

**Comment by baruchvlz** [comment]
Essentially what you're trying to validate is the same as defined [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webdriverio/index.d.ts#L173-L327)?

**Comment by christian-bromann** [comment]
We now maintain the typings within [this](https://github.com/webdriverio/webdriverio/blob/master/scripts/templates/webdriver.tpl.d.ts#L86-L96) repository. But no ... the check should 

- check if only allowed capabilities are set
  - for jsonwp: https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#capabilities-json-object
  - for webdriver: w3.org/TR/webdriver1/#capabilities
- check if capability is a protocol extension (e.g. `goog:chromeOptions` is a valid capability)
- should notify the problem gracefully and direct user to the documentation page

What worries me is that cloud provider like Browserstack don't follow the protocol (e.g. they have capabilities like `os` 🙈). Therefor I would suggest to allow to turn this validation of (should be enabled by default though).

**Comment by christian-bromann** [comment]
Given the complexity of checking capabilities and the fact that it is already done on the driver side I am changing my mind about this. A better approach is to let the driver do this checks and provide better error messages in case of failures.
