### ISSUE TITLE
browser.setValue() is 'typing' very slow

### ISSUE THREAD

**Issue by johnrobertallan** [webdriverio/webdriverio#2876]
## The problem

This morning I started seeing browser.setValue 'type' super slow, about 2 characters per second.

## Environment

* WebdriverIO version: 4.13.2
* Node.js version: 6.11.2
* testrunner / synchronous
* Additional wdio packages used (if applicable): wdio-chromedriver-service, wdio-jasmine-framework, wdio-junit-reporter, wdio-spec-reporter
* Chrome 68.0.3440.106 (latest)
* Windows 10 Enterprise N (Azure VM)

## Details

This morning I started seeing browser.setValue 'type' super slow, about 2 characters per second. For most tests this is not an issue but we do have 1 which enters over 1000 characters into a text field and this seems not only to be running slow but to be failing.

## Link to Selenium/WebdriverIO logs

https://gist.github.com/johnrobertallan/dc1e8fe5673f74b49822bd0bc110a001

## Code To Reproduce Issue [ Good To Have ]

https://gist.github.com/johnrobertallan/9854c707cf4f5778fbe2088c571bef02

**Comment by christian-bromann** [comment]
Can you check if you updated the browser or browser driver? This can't be an issue with WebdriverIO.

**Comment by johnrobertallan** [comment]
both the browser and the driver are up to date, latest.

**Comment by christian-bromann** [comment]
Without a reproducible example there is nothing I can do here. This issue is most likely located in the driver.

**Comment by patthiel** [comment]
@johnrobertallan We ran into this as well on our ReactJS app. Turns out, we were re-rendering the component on each key press. Copy+Pasting a value doesn't reproduce the issue, but typing a bunch of values in the text field did. Selenium tests reproduced it because the driver sends each key to the text field / input individually. 

Example: "Text" gets transformed into ["T","e","x"t"] and each entry in the array is sent to the target element.

If you're testing a React App, I would use the React Dev tools and check if you are having a similar re-render issue. Hope this helps.

**Comment by johnrobertallan** [comment]
Thanks @patthiel  but I that wasn't my situation. Anyway I never figured it out but it seems to have resolved itself. Very strange. Anyway I am closing the issue.

**Comment by jedwards1211** [comment]
@christian-bromann after upgrading to `webdriverio` v9 all `setValue` calls are running horribly slow for me.  I ran the profiler in the browser and all I see is a bunch of long running tasks after the keyboard interaction.  But there are no JavaScript call traces in the flame graph under these tasks; they appear to be something internal.  This seems to have something to do with the new BiDi protocol but I can't tell what's going on...do you have any idea?

<img width="647" alt="Image" src="https://github.com/user-attachments/assets/93ca307d-8ec5-4129-b027-cf447ee77c6e" />

**Comment by christian-bromann** [comment]
Thank you for letting us know, I honestly am not sure why there are such long running tasks.
