### ISSUE TITLE
Error message when running

### ISSUE THREAD

**Issue by sirjohannes** [webdriverio/webdriverio#2886]
## The problem

When executing npm test from webdriverio-master\examples\pageobject

The following error message is displayed each time:

webdriverio-master\examples\pageobject > ../../packages/wdio-cli/bin/wdio.js ./wdio.conf.js
'..' is not recognized as an internal or external command,
operable program or batch file.

I have not done anything else than downloading the repository. 

## Environment

* WebdriverIO version: 6.4.0
* Node.js version: 6.4.0
* Standalone mode or WDIO Testrunner: standalone

**Comment by christian-bromann** [comment]
> I have not done anything else than downloading the repository.

Make sure you read the [`CONTRIBUTING.md`](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and setup the project.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
