### ISSUE TITLE
Update Algolia search after beta website is live

### ISSUE THREAD

**Issue by woolter** [webdriverio/webdriverio#2889]
## The problem
New web perform search in old one

### Steps
1. go to http://beta.webdriver.io/
2. in search write 'url'
3. Make click in  url > Usage

**Expected**
http://beta.webdriver.io/docs/api/browser/url.html

**Actual**
http://webdriver.io/api/protocol/url.html#Usage

**Comment by wildaces215** [comment]
Is this open? I would like to tackle this!

**Comment by christian-bromann** [comment]
@wildaces215 please take it. If you have any questions feel free to reach out in our v5 gitter channel

**Comment by wildaces215** [comment]
Will do!

**Comment by wildaces215** [comment]
@christian-bromann Besides the chat are you able to point me in the right direction?

**Comment by christian-bromann** [comment]
not really, maybe it is something that needs to be setup in Angolia.
@vvo any input on this?

**Comment by vvo** [comment]
Hi @wildaces215, happy to help, to summarize the issue: new search on https://beta.webdriver.io tackles old website.

The search is provided by Algolia and DocSearch: https://community.algolia.com/docsearch/

The configuration file for your website is https://github.com/algolia/docsearch-configs/blob/master/configs/webdriver.json

@s-pace what's the best way to have different configurations for a DocSearch implementation when dealing with new versions of websites?

Thanks!

**Comment by s-pace** [comment]
👋 @wildaces215 

Please [apply to DocSearch](https://community.algolia.com/docsearch/#join-docsearch-program), we will provide you the credential to add to your [latest docusaurus website](http://beta.webdriver.io/docs/api/browser/url.html) along with the analytics we do provide for your search. You will need to [follow these instructions then](https://docusaurus.io/docs/en/search#enabling-the-search-bar).

We will provide you a new DocSearch index until it goes live. Once it is done, we will override [your current configuration](https://github.com/algolia/docsearch-configs/blob/master/configs/webdriver.json) with the newest one.

Waiting for your reply :)

**Comment by wildaces215** [comment]
Thanks! I'll do it when I can I just applied for the DocSearch! I'll comment if I need any help!

**Comment by caoxu2000** [comment]
I applied and waiting for the credential

**Comment by christian-bromann** [comment]
@vvo @s-pace we update the page and I applied at DocSearch. What is the next step?

**Comment by christian-bromann** [comment]
@s-pace thanks for the quick response, how do I make Algolia to update the references?

**Comment by s-pace** [comment]
Update references? WDYM? We crawl it every 24h

**Comment by christian-bromann** [comment]
@s-pace currently the search still references the old API pages .. let's see if that is fixed tomorrow. That would be amazing

**Comment by christian-bromann** [comment]
@s-pace thanks! It now goes to the beta page `beta.webdriver.io` and also some commands (all non protocol commands) are not within the search result.

**Comment by s-pace** [comment]
Yes expected, feel to PR your configuration and give more precise example

**Comment by christian-bromann** [comment]
@s-pace see https://github.com/algolia/docsearch-configs/pull/685

**Comment by christian-bromann** [comment]
@s-pace when are the changes gonna be deployed?

**Comment by s-pace** [comment]
We are facing this issue:
```sh
Traceback (most recent call last):
  File "/Users/sylvain.pace/.local/share/virtualenvs/docsearch-scraper-KRjOPOMw/lib/python2.7/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.>]
```

**Comment by christian-bromann** [comment]
@s-pace last outstanding issue: it seems that neither browser nor element commands are indexed. These are all the links on this page: http://webdriver.io/docs/api.html on the left side. I see them in the sidemap. Any reason why they are not listed?

**Comment by s-pace** [comment]
Only needed to update selectors, everything ✅ with ⬆️

**Comment by christian-bromann** [comment]
@s-pace looks good to me 👍

**Comment by christian-bromann** [comment]
This seems to be fixed for me now. Thanks for all the support @s-pace 👏
