### ISSUE TITLE
Links problems new web - THE BROWSER OBJECT

### ISSUE THREAD

**Issue by woolter** [webdriverio/webdriverio#2890]
## The problem
Wrong links in new web

### Steps
1. go to http://beta.webdriver.io/docs/browserobject.html
3. click on "api"

**Expected**
http://beta.webdriver.io/docs/api.html

**Actual**
http://beta.webdriver.io/api.html

**Comment by christian-bromann** [comment]
See https://github.com/webdriverio/webdriverio/issues/2893#issuecomment-416944808

**Comment by christian-bromann** [comment]
This is actually still valid

**Comment by woolter** [comment]
@christian-bromann  #2891, #2892 and #2893 are working as expected
This one no.

**Comment by woolter** [comment]
@christian-bromann we need to reopen

**Actual:**
http://beta.webdriver.io/docs/api

**Expected:**
http://beta.webdriver.io/docs/api.html
