### ISSUE TITLE
Links problems new web - TESTRUNNER FRAMEWORKS call

### ISSUE THREAD

**Issue by woolter** [webdriverio/webdriverio#2891]
## The problem
Wrong links in new web

### Steps
1. go to http://beta.webdriver.io/docs/frameworks.html#using-mocha
3. click on "call"

**Expected**
http://beta.webdriver.io/docs/api/browser/call.html

**Actual**
http://beta.webdriver.io/api/utility/call.html

**Comment by christian-bromann** [comment]
https://github.com/webdriverio/webdriverio/issues/2893#issuecomment-416944808
