### ISSUE TITLE
Links problems new web - TESTRUNNER FRAMEWORKS custom commands

### ISSUE THREAD

**Issue by woolter** [webdriverio/webdriverio#2892]
## The problem
Wrong links in new web

### Steps
1. go to http://beta.webdriver.io/docs/frameworks.html#using-mocha
3. click on "custom commands"

**Expected**
http://beta.webdriver.io/docs/customcommands.html

**Actual**
http://beta.webdriver.io/guide/usage/customcommands.html

**Comment by christian-bromann** [comment]
see https://github.com/webdriverio/webdriverio/issues/2893#issuecomment-416944808
