### ISSUE TITLE
Links problems new web - TESTRUNNER FRAMEWORKS config file

### ISSUE THREAD

**Issue by woolter** [webdriverio/webdriverio#2893]
Links problems new web - TESTRUNNER FRAMEWORKS config file

## The problem
Wrong links in new web

### Steps
1. go to http://beta.webdriver.io/docs/frameworks.html#using-cucumber
3. click on "config file"

**Expected**
http://beta.webdriver.io/docs/configurationfile.html

**Actual**
http://beta.webdriver.io/guide/testrunner/configurationfile.html

**Comment by christian-bromann** [comment]
@woolter I haven't updated the website but fixed all these errors

**Comment by christian-bromann** [comment]
Please check again now
