### ISSUE TITLE
Links problems new web - CUSTOM SERVICES wdio-sauce-service

### ISSUE THREAD

**Issue by woolter** [webdriverio/webdriverio#2897]
## The problem
Wrong links in new web

### Steps
1. go to http://beta.webdriver.io/docs/customservices.html#npm
3. click on "wdio-sauce-service"

**Expected**
https://github.com/webdriverio-boneyard/wdio-sauce-service
Or
https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-sauce-service
I don't know

**Actual**
https://github.com/webdriverio/packages/wdio-sauce-service

**Comment by christian-bromann** [comment]
Fixed.
