### ISSUE TITLE
Links problems new web - CONCISE REPORTER

### ISSUE THREAD

**Issue by woolter** [webdriverio/webdriverio#2901]
## The problem
Wrong links in new web

### Steps
1. go to http://beta.webdriver.io/docs/concise-reporter.html#installation
2. click on "here"

**Expected**
http://beta.webdriver.io/docs/gettingstarted.html#download-webdriverio

**Actual**
http://webdriver.io/guide/getstarted/install.html

**Comment by christian-bromann** [comment]
Fixed.
