### ISSUE TITLE
Links problems new web - JUNIT REPORTER homepage

### ISSUE THREAD

**Issue by woolter** [webdriverio/webdriverio#2904]
## The problem
Wrong links in new web

### Steps
1. go to http://beta.webdriver.io/docs/junit-reporter.html#jenkins-setup
2. click on "homepage"

**Expected**
http://beta.webdriver.io/

**Actual**
http://webdriver.io/

**Comment by christian-bromann** [comment]
Once we moved the page to the real domain this will be fixed.
