### ISSUE TITLE
Links problems new web - SUMOLOGIC REPORTER here

### ISSUE THREAD

**Issue by woolter** [webdriverio/webdriverio#2905]
## The problem
Wrong links in new web

### Steps
1. go to http://beta.webdriver.io/docs/sumologic-reporter.html#installation
2. click on "here"

**Expected**
http://beta.webdriver.io/docs/gettingstarted.html#download-webdriverio

**Actual**
http://webdriver.io/guide/getstarted/install.html

**Comment by christian-bromann** [comment]
Once we moved the page to the real domain this will be fixed.

**Comment by woolter** [comment]
@christian-bromann we need to reopen this.

**Actual:**
http://webdriver.io/docs/gettingstarted.html

**Comment by christian-bromann** [comment]
Why? The page is currently deployed on a temporary subdomain. Once we release v5 we will move the page to `https://webdriver.io` where all these links will work.

**Comment by woolter** [comment]
Ok! I thought that needs to works like the others links.
