### ISSUE TITLE
Links problems new web - SUMOLOGIC REPORTER homepage

### ISSUE THREAD

**Issue by woolter** [webdriverio/webdriverio#2906]
## The problem
Wrong links in new web

### Steps
1. go to http://beta.webdriver.io/docs/sumologic-reporter.htm
2. click on "homepage"

**Expected**
http://beta.webdriver.io/

**Actual**
http://webdriver.io/

**Comment by christian-bromann** [comment]
Once we moved the page to the main domain, this will be fixed.
