### ISSUE TITLE
Links problems new web - DEVTOOLS SERVICE homepage

### ISSUE THREAD

**Issue by woolter** [webdriverio/webdriverio#2909]
## The problem
Wrong links in new web

### Steps
1. go to http://beta.webdriver.io/docs/devtools-service.html#via-event-listener
2. click on "homepage"

**Expected**
http://beta.webdriver.io/

**Actual**
http://webdriver.io/

**Comment by christian-bromann** [comment]
Again, this link will work once we moved the page from the sub domain to the main domain.
