### ISSUE TITLE
Links problems new web - FIREFOX PROFILE SERVICE wdio testrunner

### ISSUE THREAD

**Issue by woolter** [webdriverio/webdriverio#2911]
## The problem
Wrong links in new web

### Steps
1. go to http://beta.webdriver.io/docs/firefox-profile-service.html
2. click on "wdio testrunner"

**Expected**
http://beta.webdriver.io/docs/clioptions.html

**Actual**
http://webdriver.io/guide/testrunner/gettingstarted.html

**Comment by christian-bromann** [comment]
Fixed.
