### ISSUE TITLE
Links problems new web - SELENIUM STANDALONE SERVICE wdio testrunner

### ISSUE THREAD

**Issue by woolter** [webdriverio/webdriverio#2913]
## The problem
Wrong links in new web

### Steps
1. go to http://beta.webdriver.io/docs/selenium-standalone-service.html
2. click on "WDIO testrunner"

**Expected**
http://beta.webdriver.io/docs/clioptions.html

**Actual**
http://webdriver.io/guide/testrunner/gettingstarted.html

**Comment by christian-bromann** [comment]
Fixed.
