### ISSUE TITLE
Links problems new web - SELENIUM STANDALONE SERVICE homepage

### ISSUE THREAD

**Issue by woolter** [webdriverio/webdriverio#2915]
## The problem
Wrong links in new web

### Steps
1. go to http://beta.webdriver.io/docs/selenium-standalone-service.html#seleniuminstallargs
2. click on "homepage"

**Expected**
http://beta.webdriver.io/

**Actual**
http://webdriver.io/

**Comment by christian-bromann** [comment]
This is fine. Once we deploy the page to the webdriver.io domain this is fixed. No need to implement like link fixing functions for the beta page.
