### ISSUE TITLE
wdio-cli latest release missing build directory (Mostly a FYI, alpha is fine)

### ISSUE THREAD

**Issue by halkeye** [webdriverio/webdriverio#2919]
## The problem

When trying out the new wdio-cli@latest (5.0.0-alpha.7) package, i noticed it complains about loading ../build

## Code To Reproduce Issue [ Good To Have ]
```
npx wdio-cli
npx: installed 162 in 9.718s
Cannot find module '../build'
Time: 0h:00m:10s
```

```
$ npm info wdio-cli@latest dist.tarball | xargs curl -qs | tar tvzf -
-rw-r--r-- 0/0            1443 1985-10-26 01:15 package/package.json
-rw-r--r-- 0/0              67 1985-10-26 01:15 package/README.md
-rwxr-xr-x 0/0             248 1985-10-26 01:15 package/bin/wdio.js
```

Note: Alpha and beta are fine, just scarier titles

$ npm info wdio-cli@alpha dist.tarball | xargs curl -qs | tar tvzf -
-rw-r--r-- 0/0            1448 1985-10-26 01:15 package/package.json
-rw-r--r-- 0/0              67 1985-10-26 01:15 package/README.md
-rwxr-xr-x 0/0             248 1985-10-26 01:15 package/bin/wdio.js
-rw-r--r-- 0/0            1457 1985-10-26 01:15 package/build/commands/repl.js
-rw-r--r-- 0/0           10287 1985-10-26 01:15 package/build/config.js
-rw-r--r-- 0/0            1682 1985-10-26 01:15 package/build/index.js
-rw-r--r-- 0/0            8276 1985-10-26 01:15 package/build/interface.js
-rw-r--r-- 0/0           15216 1985-10-26 01:15 package/build/launcher.js
-rw-r--r-- 0/0            2650 1985-10-26 01:15 package/build/run.js
-rw-r--r-- 0/0            2649 1985-10-26 01:15 package/build/setup.js
-rw-r--r-- 0/0           15336 1985-10-26 01:15 package/build/templates/wdio.conf.tpl.ejs
-rw-r--r-- 0/0            3399 1985-10-26 01:15 package/build/utils.js

 $ npm info wdio-cli@beta dist.tarball | xargs curl -qs | tar tvzf -
-rw-r--r-- 0/0            1438 1985-10-26 01:15 package/package.json
-rw-r--r-- 0/0              67 1985-10-26 01:15 package/README.md
-rwxr-xr-x 0/0             254 1985-10-26 01:15 package/bin/wdio.js
-rw-r--r-- 0/0            1457 1985-10-26 01:15 package/build/commands/repl.js
-rw-r--r-- 0/0            9999 1985-10-26 01:15 package/build/config.js
-rw-r--r-- 0/0            2090 1985-10-26 01:15 package/build/index.js
-rw-r--r-- 0/0            8276 1985-10-26 01:15 package/build/interface.js
-rw-r--r-- 0/0           15216 1985-10-26 01:15 package/build/launcher.js
-rw-r--r-- 0/0            2650 1985-10-26 01:15 package/build/run.js
-rw-r--r-- 0/0            2649 1985-10-26 01:15 package/build/setup.js
-rw-r--r-- 0/0           14884 1985-10-26 01:15 package/build/templates/wdio.conf.tpl.ejs
-rw-r--r-- 0/0            3399 1985-10-26 01:15 package/build/utils.js

**Comment by christian-bromann** [comment]
Just released a version with `@next` tag. This should fix the issue. Thanks for reporting.
