### ISSUE TITLE
Doubt command as link or code - example with $ and findElement

### ISSUE THREAD

**Issue by woolter** [webdriverio/webdriverio#2928]
## The problem
In other bug this was changed this is the reason of my question

### Steps
1. go to http://beta.webdriver.io/docs/api/browser/$.html

The $ command is a short way to call the findElement command in order to fetch a single element on the page.

**Doubt**
$ is in code format
findElement is in link format

Do we have any reason to have in this way?

**Comment by christian-bromann** [comment]
Not sure what the issue here is. I just linked the `findElement` command. This is on purpose.
