### ISSUE TITLE
How to run Selenium WebDriver test cases from  an angular web app using TypeScript

### ISSUE THREAD

**Issue by bitquality** [webdriverio/webdriverio#2934]
## The problem

I want to run selenium tests from an angular web app. We developed a web Test Reporting tool and want to integrate running selenium tests from it. when i use the browser object from webdriverio or protractor in my TypeScript project it gives me browser object not found error .

Does webDriverIO supports running selenium tests from a web app ? Do we still need jar files ?

## Environment

* WebdriverIO version: 4.2.3
* Node.js version: 5.6.x
* Standalone mode or WDIO Testrunner: stand alone web app
* if wdio testrunner, running synchronous or asynchronous tests: NA
* Additional wdio packages used (if applicable): NA

## Details

I want to run selenium tests from an angular web app. We developed a Test Reporting tool and want to integrate running selenium tests from it. when i use the browser object from webdriverio or protractor in my TypeScript project it gives me browser error.

## Code To Reproduce Issue [ Good To Have ]

import { browser, ProtractorBrowser } from 'protractor';

var webdriverio = require("webdriverio");

**Comment by christian-bromann** [comment]
> I want to run selenium tests from an angular web app.

Currently WebdriverIO tests can only be run from Node.js. However I know people already working on tweaking the WebDriverRequestHandler to work on the browser so this will be eventually be supported.

That being said, I am not sure why you want to run your WebDriver tests from an web app. What you can do is to build a Node.js service that can kick of a test when you send a request to it from an angular app.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have more questions. Thanks!

**Comment by bitquality** [comment]
Thanks for your reply christian. How does SeleniumIDE does this when it playback recordings from chrome or firefox browser extension ?
