### ISSUE TITLE
Documentation Links are broken

### ISSUE THREAD

**Issue by sujayvenaik** [webdriverio/webdriverio#2939]
## The problem
Links are broken in the documentation
eg: http://webdriver.io/api/action/middleClick.html

The top buttons : source and imrpove this doc

## Code To Reproduce Issue [ Good To Have ]

Go to : http://webdriver.io/api/action/middleClick.html

**Comment by christian-bromann** [comment]
@sujayvenaik thanks for reporting. We are about to launch the [beta page](http://beta.webdriver.io/) which has this issue fixed.
