### ISSUE TITLE
404 on the 'View Source' button of the chooseFile API document page

### ISSUE THREAD

**Issue by xcao-riffyn** [webdriverio/webdriverio#2942]
## The problem

I was trying to view source on the http://webdriver.io/api/utility/chooseFile.html page. The page is linked to https://github.com/webdriverio/webdriverio/blob/master/lib/commands/chooseFile.js which led to a 404

## Environment

http://webdriver.io/api/utility/chooseFile.html

**Comment by caoxu2000** [comment]
The view source links on wdio site should point the v4 branch rather than master which is currently gone through transition to v5, I think. So close this to not distract the team for this small issue
