### ISSUE TITLE
ECONNREFUSED 0.0.0.0:4444 from remote and multiremote examples

### ISSUE THREAD

**Issue by aamorozov** [webdriverio/webdriverio#2950]
## The problem
To replicate
1. `yarn add webdriverio@next` or `npm i webdriverio@next`
2. copy example into index.js
3. run `node index.js`

## Environment

* WebdriverIO version: 5.0.0-beta.2
* Node.js version: v10.10.0
* Standalone mode or WDIO Testrunner: Standalone
* if wdio testrunner, running synchronous or asynchronous tests: -
* Additional wdio packages used (if applicable): -
* MacOS High Sierra 

## Details

The error is thrown for both remote&multiremote examples when running in standalone mode.

## Link to Selenium/WebdriverIO logs
```
Error: Error: connect ECONNREFUSED 0.0.0.0:4444
    at Request._callback (./dev/wdio/node_modules/webdriver/src/request.js:85:27)
    at self.callback (./dev/wdio/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:442:20)
    at Request.onRequestError (./dev/wdio/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:182:13)
    at ClientRequest.EventEmitter.emit (domain.js:442:20)
    at Socket.socketErrorListener (_http_client.js:391:9)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
```
## Code To Reproduce Issue [ Good To Have ]

```
const {remote} = require('webdriverio');

(async () => {
  const browser = await remote({
    capabilities: {
      browserName: 'chrome',
    },
  });

  await browser.url('https://duckduckgo.com/');

  const inputElem = await browser.$('#search_form_input_homepage');
  await inputElem.setValue('WebdriverIO');

  const submitBtn = await browser.$('#search_button_homepage');
  await submitBtn.click();

  console.log(await browser.getTitle()); // outputs: "Title is: WebdriverIO (Software) at DuckDuckGo"

  await browser.deleteSession();
})().catch(e => console.error(e));
```

**Comment by christian-bromann** [comment]
@aamorozov as with all examples you need to have a browser driver running on port 4444. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by aamorozov** [comment]
@christian-bromann Would it be beneficial to document it for the new api version?
