### ISSUE TITLE
Rest-API status session is always green/passed when mochaOpt settings bail: "true" 

### ISSUE THREAD

**Issue by goatsy** [webdriverio/webdriverio#2954]
## The problem

I have mentioned this already at https://github.com/itszero/wdio-browserstack-service/issues/24 but now I found out that in SauceLabs Service the same problem occurs. 
If you have several tests and one fails with `bailing: true` in mochaOpts and `bail: 1` in the config the session is marked as "passed" on Browserstack/SauceLabs

## Environment

* WebdriverIO version: v4.11
* Node.js version: v9.5.0
* Standalone mode or WDIO Testrunner: Mocha
* if wdio testrunner, running synchronous or asynchronous tests: synch
* Additional wdio packages used (if applicable): wdio-browserstack-service

## Details

I have several tests in my spec-File.

Example below.

In my config-File I have set the mochaOpts parameter

`bail: true`

and also in the Webdriverio Config Parameter

`bail: 1`

The first test fails, and the other tests are not executed (which is right) but on Browserstack API apparently "passed" is sent.
The session has the green tick https://www.browserstack.com/images/layout/sp-success.png

## Code To Reproduce Issue [ Good To Have ]

```
describe('Bail Test', function () {

it('description', function () {
    Page.open("www.google.de")
    expect(Page.getUrl).to.have.string("abcde");
});

it('description 2', function () {
    Page.open("www.google.de")
    expect(Page.getUrl).to.have.string("abcde");
});

it('description 3', function () {
    Page.open("www.google.de")
    expect(Page.getUrl).to.have.string("abcde");
});
```

**Comment by pmerwin** [comment]
Thanks for opening this!  I am seeing this issue too, and would love to help get it fixed.

**Comment by christian-bromann** [comment]
I think this is unrelated to WebdriverIO. It doesn't handle the job state in Browserstack. This should be handled in the service.

@abjerstedt can you confirm that this works?

**Comment by abjerstedt** [comment]
@christian-bromann I just reproduced it and debugged it. This is an issue for sauce, testingbot and browerstack due to the fact that the after() hook is called BEFORE the afterTest()/etc hook in the event of a bail. 

I'll take a look and see if i have some context to tell that a bail occurred and increment failures.

**Comment by christian-bromann** [comment]
Reopening the ticket then

**Comment by abjerstedt** [comment]
I'm gonna drill some more into this, and see if i can track down why the hook order is messed up.
