### ISSUE TITLE
Integrate typescript definitions in the project

### ISSUE THREAD

**Issue by Bamieh** [webdriverio/webdriverio#2959]
To keep the typescript definition upto date, it would be nice to have them in the project instead of installing them separately.

Many projects are doing this now ([winston](https://github.com/winstonjs/winston) for example), it is much easier to maintain and this feature is important for all javascript users regardless whether they are using typescript or not, since vs code and sublime read the typescript types to do things such as autocomplete.

**Comment by christian-bromann** [comment]
@Bamieh I already started implementing a [generator script](https://github.com/webdriverio/webdriverio/pull/2862) for all typescript definitions. I absolutely agree with you that having this within the project would be better than having to copy paste it to the definitely typed repo where someone else has to review it.

Can you elaborate on how winston pushes its type definitions to NPM and how it can be consumed by the user?

**Comment by christian-bromann** [comment]
I guess this describes it pretty much https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20418#issuecomment-399531344 .. awesome, we will do it this way for sure!
