### ISSUE TITLE
selenium-standalone 6.15.3 + webdriver.io 4.13.0

### ISSUE THREAD

**Issue by kimek** [webdriverio/webdriverio#2960]
## The problem

Webdriver cannot run tests. Chrome is opening and stack on ;data in address bar.

## Environment

* WebdriverIO version: 4.13.0
* Node.js version: 5.0.3
* Standalone mode or WDIO Testrunner: Standalone mode 
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): 
    "wdio-allure-reporter": "0.1.3",
    "wdio-browserstack-service": "0.1.14",
    "wdio-json-reporter": "0.3.1",
    "wdio-junit-reporter": "0.3.1",
    "wdio-mocha-framework": "0.5.13",
    "wdio-mochawesome-reporter": "1.3.0",
    "wdio-sauce-service": "0.4.8",
    "wdio-selenium-standalone-service": "0.0.9",
    "wdio-spec-reporter": "0.1.4",
    "wdio-visual-regression-service": "0.8.0",

## Link to Selenium/WebdriverIO logs

https://gist.github.com/kimek/b79ad38352bcfaeab7fb0e1f3d399f0f

## Code To Reproduce Issue [ Good To Have ]

  "devDependencies": {
    "allure-commandline": "^2.5.0",
    "allure-js-commons": "^1.3.1",
    "babel-cli": "^6.26.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-preset-env": "^1.6.1",
    "babel-register": "^6.26.0",
    "chai": "^4.1.2",
    "date.format": "latest",
    "junit-viewer": "^4.11.1",
    "lodash": "^4.17.5",
    "mochawesome-report-generator": "^2.3.2",
    "npm-run-all": "^4.1.2",
    "selenium-standalone": "6.15.3",
    "string.format": "1.3.1",
    "wdio-allure-reporter": "0.1.3",
    "wdio-browserstack-service": "0.1.14",
    "wdio-json-reporter": "0.3.1",
    "wdio-junit-reporter": "0.3.1",
    "wdio-mocha-framework": "0.5.13",
    "wdio-mochawesome-reporter": "1.3.0",
    "wdio-sauce-service": "0.4.8",
    "wdio-selenium-standalone-service": "0.0.9",
    "wdio-spec-reporter": "0.1.4",
    "wdio-visual-regression-service": "0.8.0",
    "webdriverio": "4.13.0"
  },
  "babel": {
    "presets": [
      "env"
    ],
    "plugins": [
      "transform-class-properties"
    ]
  },
}

**Comment by christian-bromann** [comment]
This is not an issue with WebdriverIO. It is probably an inoperability between Chrome and Chromedriver. It could be that the `wdio-selenium-standalone-service` installs the wrong versions or something else. Without any reproducible example it is impossible to say more details. Therefor closing this issue.
