### ISSUE TITLE
Move away from calling Element Is Displayed endpoint for W3C-compliant drivers

### ISSUE THREAD

**Issue by burg** [webdriverio/webdriverio#2962]
## The problem

WebDriverIO currently expects to be able to use the endpoint GET /session/:sessionId/element/:elementId/displayed with W3C-compliant drivers. As this endpoint is not defined in the W3C specification, this is an invalid assumption. As a result, the request will return a 404. This is a serious functionality regression from non-W3C drivers.

The Selenium project has taken the approach of using the isDisplayed.js atom directly if the driver is speaking the W3C protocol dialect. I recommend taking this approach to maintain functionality for Safari 12 and other drivers that speak W3C protocol.

Selenium change: https://github.com/SeleniumHQ/selenium/commit/253fc6b579f23c799b618cfc778ddf1eed4f0d90

**Comment by christian-bromann** [comment]
Thanks for notifying. I wasn't aware of this.

**Comment by emilyrohrbough** [comment]
We have are experiencing this issue with using webdriver.io 4.13 while running against a selenium grid with IE nodes (v 3.14).

**Comment by abjerstedt** [comment]
@burg - What am I missing on this? The endpoint listed above is indeed listed in the spec as the defacto method to ascertain element displayedness:
https://www.w3.org/TR/webdriver1/#element-displayedness
```
This function is typically exposed to GET requests with a URI Template of /session/{session id}/element/{element id}/displayed.
```

**Comment by burg** [comment]
The algorithm is not specified with any semantics outside code, namely, the existing Selenium atom. There is no reason for drivers to implement a non-normative endpoint that can be polyfilled.

**Comment by christian-bromann** [comment]
@burg what do you suggest? If the driver uses the Selenium atom anyway why should I need to polyfill it by myself?

**Comment by christian-bromann** [comment]
Moving this out from v5 release as it doesn't block any functionality that needs to be ported.

**Comment by christian-bromann** [comment]
@burg embedding Selenium Atoms into this project is not worthwhile. It adds too much unnecessary and undocumented code. Imo the definition of if an element is displayed or not should live on some sort of protocol level (maybe referencing it from a different spec). I understand that defining displayedness is not the job of the WebDriver protocol neither is it the job of the protocol consumer though.

**Comment by burg** [comment]
Feel free to bring it up in the working group.

**Comment by abjerstedt** [comment]
@burg If we are truly removing a displayedness check from the spec/driver and expect frameworks to use the atom, can we get the core selenium team to make this atom standalone? Its woven pretty deep atm.

**Comment by burg** [comment]
I wrote this stripped down version for WebKit-based drivers:

https://trac.webkit.org/browser/webkit/trunk/Source/WebKit/UIProcess/Automation/atoms/ElementDisplayed.js <https://trac.webkit.org/browser/webkit/trunk/Source/WebKit/UIProcess/Automation/atoms/ElementDisplayed.js>

You might be able to use it. I am not an expert on your licensing situation, so ask someone who is ;-)

**Comment by abjerstedt** [comment]
@burg Thank you! Do you foresee any changes in this file (or the atom behavior in general) going forward? I can work on implementing this, but I'm wondering if we are gonna have issues with diverging with the ongoing norms.

**Comment by burg** [comment]
It does not replicate all of the cases in the Selenium atom. That said, we haven’t received many Element Displayed bugs in the past year, so it’s probably only going to change in order to fix minor test failures.

I believe Selenium atom is not taking changes. Might be worth asking a core member from that project.

**Comment by christian-bromann** [comment]
Let's continue convo in #3601
