### ISSUE TITLE
Counting number of child elements under root element

### ISSUE THREAD

**Issue by rtran25** [webdriverio/webdriverio#2967]
I'm trying to count the number of child elements underneath a parent element, but I can only seem to get 1 element type at a time. An example is:
```
<div id="parent">
        <div id="child">
                <a></a>
                <div></div>
                <a></a>
                <a></a>
                <span></span>
        </div>
</div>
```
The idea is
`browser.elements(#parent > div)`
or
`browser.elements(#parent > div).value.length`
would return 5 but instead it returns 1 because it takes the last given element (#parent > **div**) and searched for all of those elements underneath the previous element (**#parent** > div). If I run
`browser.elements(#parent > div > a).value.length`
it would return 3 because it is searching for all **a** underneath the div.id=child.
How can I find the length/value/number of child elements of all types underneath a selector?

**Comment by rtran25** [comment]
On another note, would there be a way to place all types of elements into a list? Besides counting the number of child elements, it would see what type the elements were (a, div, span) and place into a list.

**Comment by christian-bromann** [comment]
if you want to count all child elements and their child elements you need to do a reverse look up. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
