### ISSUE TITLE
Unable to use id from elementJson

### ISSUE THREAD

**Issue by ajspencer** [webdriverio/webdriverio#2971]
## The problem

I'm trying to use the ID field from an elementJson as described in the documentation. Specifically, I'm trying to call brower.elementIdRect. I get an error when doing so. 

## Environment

* WebdriverIO version:6.4.1
* Node.js version:10.11.0
* Standalone mode or WDIO Testrunner: standalone mode
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Details

Sample error message:
> { Error: No active session with ID e6d2e5dc-08cd-44f1-b3bc-686be146c2a2
>     at new RuntimeError (/home/ubuntu/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
>     at Request._callback (/home/ubuntu/node_modules/webdriverio/build/lib/utils/RequestHandler.js:316:39)
>     at Request.self.callback (/home/ubuntu/node_modules/request/request.js:185:22)
>     at Request.emit (events.js:182:13)
>     at Request.EventEmitter.emit (domain.js:442:20)
>     at Request.<anonymous> (/home/ubuntu/node_modules/request/request.js:1161:10)
>     at Request.emit (events.js:182:13)
>     at Request.EventEmitter.emit (domain.js:442:20)
>     at IncomingMessage.<anonymous> (/home/ubuntu/node_modules/request/request.js:1083:12)
>     at Object.onceWrapper (events.js:273:13)
>   details: undefined,
>   message:
>    'No active session with ID e6d2e5dc-08cd-44f1-b3bc-686be146c2a2',
>   type: 'RuntimeError',
>   seleniumStack:
>    { type: 'NoSuchDriver',
>      message: 'A session is either terminated or not started',
>      orgStatusMessage:
>       'No active session with ID e6d2e5dc-08cd-44f1-b3bc-686be146c2a2' } }
> 

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

Not sure what you're referring to but here's my call stack: https://gist.github.com/ajspencer/2bd5b5085b88eb38d31600ef168a46de. 

## Code To Reproduce Issue [ Good To Have ]

```
browser = webdriverio.remote(options).init().url('http://mataro.escolapia.cat/')
browser.setViewportSize({
        width: 375,
        height: 812
        });


elements = browser.elements('*').then(function(elements) {
        elements.value.forEach(function(elementJson) {
                console.log(elementJson)
                foo = browser.elementIdRect(elementJson.ELEMENT)
                foo.catch(function(err) {
                        console.log(err)
                });
        });
});

```
Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
Something happened with your session: A session is either terminated or not started. Feel free to re-open if you can provide a reproducible example. Thanks!
