### ISSUE TITLE
npm run setup failed in the Windows 10 environment; HERE IS THE LINK - https://pastebin.com/msRuAd2y

### ISSUE THREAD

**Issue by spjrc** [webdriverio/webdriverio#2973]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to WebdriverIO). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, join the Gitter chat room ([![Gitter](https://badges.gitter.im/Join Chat.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge))!

## Environment

* WebdriverIO version:
* Node.js version:
* Standalone mode or WDIO Testrunner:
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by spjrc** [comment]
WINDOWS 10 Version 1803 (build 17134.320)
WebdriveIO - latest version as of 09/30/2018 10:am EST.
node --version - v10.11.0
HERE IS THE LINK - https://pastebin.com/msRuAd2y
The above link will display all errors.
contact me (spjrc) at chenjr98@outlook.com if you have more questions.
Thank you.

**Comment by BorisOsipov** [comment]
from log
```
lerna ERR! build Errored while running script in 'wdio-firefox-profile-service'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run build
lerna ERR! 'rm' is not recognized as an internal or external command,
````

**Comment by perhenrikandersson** [comment]
I think I might have a related problem when trying to run the mocha examples tests using windows.
https://github.com/webdriverio/webdriverio/tree/master/examples/wdio
C:\projects\demo\webdriverio\examples\wdio>npm run test:mocha
> @ test:mocha C:\projects\demo\webdriverio\examples\wdio
> ../../packages/wdio-cli/bin/wdio.js ./mocha/wdio.conf.js
'..' is not recognized as an internal or external command,
operable program or batch file.

**Comment by spjrc** [comment]
Let me know if you guys need more info on this issue.  After I run 'npm run setup', I received the following log files.  Please let me know if you need these log files; I can combine the 10 files into a single file and then create a link for it thru PASTEBIN URL.  
or contact me at chenjr98@outlook.com
Thank you.
Directory of C:\Users\spjrc\AppData\Roaming\npm-cache\_logs
10/02/2018  05:28 AM             3,890 2018-10-02T09_28_39_109Z-debug.log
10/02/2018  05:28 AM             3,767 2018-10-02T09_28_39_392Z-debug.log
10/02/2018  05:28 AM             3,567 2018-10-02T09_28_39_441Z-debug.log
10/02/2018  05:28 AM             3,461 2018-10-02T09_28_39_565Z-debug.log
10/02/2018  05:28 AM             3,624 2018-10-02T09_28_39_680Z-debug.log
10/02/2018  05:28 AM             3,515 2018-10-02T09_28_39_815Z-debug.log
10/02/2018  05:28 AM             3,719 2018-10-02T09_28_39_931Z-debug.log
10/02/2018  05:28 AM             3,605 2018-10-02T09_28_39_999Z-debug.log
10/02/2018  05:28 AM             2,804 2018-10-02T09_28_40_168Z-debug.log
10/02/2018  05:28 AM             2,722 2018-10-02T09_28_41_411Z-debug.log
              10 File(s)         34,674 bytes

**Comment by christian-bromann** [comment]
@spjrc I don't use windows .. feel free to propose a PR with a fix.

**Comment by spjrc** [comment]
My bad – what is a PR?  I already submitted a ticket on your GitHub. Thank you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by christian-bromann** [comment]
> My bad – what is a PR?

A PR is a pull request to fix this issue. As I said, I don't use Windows therefor this is not critical for me.

**Comment by christian-bromann** [comment]
This issue has been fixed as we released `wdio-sync` that supports node v10
