### ISSUE TITLE
Impossible to run multiple feature files with one wdio invocation

### ISSUE THREAD

**Issue by osmolyar** [webdriverio/webdriverio#2979]
## The problem

None of the following configurations work to run multiple feature files with one wdio call:

 specs: [
       // './features/*.feature',   //this doesn't seem to work either - picks one feature file at random to run
        //     './features/**/*.feature',   //this should work but it doesn't
        //Can also specify each feature file individually here and run all (also only runs 1)
        './features/Login.feature',
        './features/GenericTests.feature',
        './features/SystemAdministration/Security/UserManagement.feature',
        './features/SystemAdministration/Security/RoleManagement.feature',
        './features/SystemAdministration/Security/LicenseKey.feature',
        './features/SystemAdministration/Security/AccessControl.feature'
    ],

The only thing that works is using --suite <featureFile> to run one specific file at a time.

Using the same tag on multiple feature files are trying to run using --tags @test only runs one of the tagged files as well.

To clarify, the concern is not that the files are not running in parallel, but that only one file is ever attempted to be run at all.  Running all the files serially would be fine.

## Environment

* WebdriverIO version: webdriverio@4.13.2
* Node.js version:  5.6.0
* Standalone mode or WDIO Testrunner: Standalone 
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):  wdio-cucumber-framework

## Details

See above

**Comment by christian-bromann** [comment]
Like other test framework with spec files you should be able to run feature files in parallel. Can you provide a reproducible example?

**Comment by osmolyar** [comment]
Here's a zip file of my config file.  The features are in the listed directories, either in a flat or a tree structure (with the same result).  
[wdio.config.js.zip](https://github.com/webdriverio/webdriverio/files/2435626/wdio.config.js.zip)

Here's a zip file of the entire suite (though it points to servers behind firewalls):
[ManagementPortal.zip](https://github.com/webdriverio/webdriverio/files/2435635/ManagementPortal.zip)

None of us here have been able to get more than one file to run at a time using any method - listing all the files sequentially in the specs, using a wildcard, using tags, etc.

**Comment by BorisOsipov** [comment]
@osmolyar 	
are you sure that is ok to share all your test code by `ManagementPortal.zip` ?
don't you have some legal issues after that?

**Comment by BorisOsipov** [comment]
For your question, what is your selenium server setup? I see `maxInstances:5` so it is automatically run 5 browser in parallel.

**Comment by osmolyar** [comment]
Yes I should probably remove it.  If you could let me know what files are relevant to the 'reproducible example', I'll include those.  Basically they're feature files that run fine using the --suite argument, but without it only one randomly selected file runs.

**Comment by christian-bromann** [comment]
@osmolyar I would be great to get a _minimal_ reproducible example. Something that I can run on my end to test the issue by myself.

**Comment by osmolyar** [comment]
@BorisOsipov , It just runs the one feature file happily on one browser., does not attempt to run any other feature files, either serially or in parallel.

**Comment by osmolyar** [comment]
@christian-bromann , I would think that the same issue would be readily apparent in the wdio-cucumber-framework boilerplate project, as this is what the suite it based off of.  But will try to come up with an example.

**Comment by christian-bromann** [comment]
See https://github.com/webdriverio/webdriverio/blob/master/examples/wdio.conf.js#L54-L62. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by osmolyar** [comment]
As stated above this question  is NOT about running files in parallel. It is about running with ONE browser in capabilities, and I expect, as with Jasmine specs, to have all my feature files run one at a time, serially, such that all files matching the wildcard spec, and/or listed out explicitly in the spec, are eventually run. Instead, only one file is EVER run, with the run terminating after completing a single feature file.

**Comment by christian-bromann** [comment]
> such that all files matching the wildcard spec, and/or listed out explicitly in the spec, are eventually run.

Please use `maxInstances` for this! Not that you can apply that to specific capabilities as well as for all capabilities.

**Comment by osmolyar** [comment]
We already have maxInstances set to 5, and my understanding is that maxInstances governs parallel execution, (which we are NOT asking about). Is this understanding incorrect?

**Comment by christian-bromann** [comment]
> Is this understanding incorrect?

Yes, so set it to `1` to run one job at a time.

**Comment by osmolyar** [comment]
ok...…..but the issue not that they are all running in parallel, but that only one (at random) is recognized as a feature file.   I do see it is working as expected in the cucumber_boilerplate_project so will need to do some work to get you a reproducible example of our situation without providing all the code.

**Comment by osmolyar** [comment]
@christian-bromann , you are correct, setting maxInstances =1 for our project causes the files to all run!  Thank you.   I am just a bit confused as to why, in the cucumber_boilerplate_project, it apepars to run all the feature files one after the other (with some in parallel) even though maxInstances=5, rather than stopping after 1 (or 5?) files.

**Comment by christian-bromann** [comment]
> setting maxInstances =1 for our project causes the files to all run!

Yes, it runs all files one after one as you expect right?

> in the cucumber_boilerplate_project, it apepars to run all the feature files one after the other (with some in parallel) even though maxInstances=5

Not sure how it is set up there

**Comment by osmolyar** [comment]
@christian-bromann , yes, now it runs all the files (one after the other).  So we are all set.   Thank you for your help,  

Would just have thought it would eventually get to running more than one file regardless of maxInstances (as it appears to in the boilerplate project, and as it did for us when we were using Jasmine with wdio).

**Comment by osmolyar** [comment]
@christian-bromann , @BorisOsipov , for what it's worth, here's a minimal suite to reproduce the issue that with maxInstances>1, it never runs more than one feature file. 

[cucumber-boilerplate-master.zip](https://github.com/webdriverio/webdriverio/files/2438393/cucumber-boilerplate-master.zip)

Command to run is 'wdio common/config/wdio.config.js'.   Right now maxInstances is set to 5 to reproduce the issue, but if you change to 1, it will happily find and run the 2 specs.

**Comment by BorisOsipov** [comment]
@osmolyar comment or remove `//execArgv: ['--inspect']`, in your wdio.conf.js.

does it help?
