### ISSUE TITLE
In combination with Mocha and Jenkins XUnit XML Parse Error

### ISSUE THREAD

**Issue by maciossek** [webdriverio/webdriverio#298]
I updated to the most recent version of webdriver.io. When a test throws an error, the whole XUnit cant be read anymore:

```
Failed to read test report file /var/lib/jenkins/workspace/wag-rwd/test-reports.xml
org.dom4j.DocumentException: Error on line 5 of document file:///var/lib/jenkins/workspace/wag-rwd/test-reports.xml : An invalid XML character (Unicode: 0x{2}) was found in the value of attribute "{1}" and element is "1b". Nested exception: An invalid XML character (Unicode: 0x{2}) was found in the value of attribute "{1}" and element is "1b".
```

**Comment by zauberpony** [comment]
We're having the same/a simliar issue, jenkins and xmllint are moaning an invalid character "^[[1;30m" in the generated XML-Output. Even without xmlunit-reporting this sequence (color-code for dark-grey) is printed.

But I'm not sure if it's really webdriverio's fault. The only code from webdriverio that prints that code to the console is https://github.com/webdriverio/webdriverio/blob/25afca5806ae56327505e41d2ce733ab114c0a57/lib/utils/Logger.js#L76 but I'm running webdriver with log-level silent.

I also run mocha without colors (mocha -C), so I'm not sure who's really printing the sequence (with the invalid character).

As a workaround, use sed to filter out invalid chars:

    mocha -C --recursive test/e2e -R xunit | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g" > e2e.xml

(See http://www.commandlinefu.com/commands/view/3584/remove-color-codes-special-characters-with-sed for sed command).

**Comment by christian-bromann** [comment]
Will make colored logs optional. This will solve this issue hopefully

**Comment by christian-bromann** [comment]
Pretty sure that fixes the problem. Feel free to reopen issue if not.

@zauberpony thx for your input, helped me a lot ;)
