### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by petrvecera** [webdriverio/webdriverio#2982]
## The problem

The links in the docs to the code doesn't work. http://webdriver.io/guide/services/chromedriver.html

![image](https://user-images.githubusercontent.com/8086995/46362325-3f927600-c670-11e8-9c2c-dcb3f561b205.png)
These links doesn't work anywhere in the docs. The links in the API also doesn't work.

I wanted to contribute to the docs. Write a config how to use Chrome headless. 
Am I in the wrong repo? Thanks

## Environment

* http://webdriver.io

## Code To Reproduce Issue

1. Go to http://webdriver.io/api/action/leftClick.html
2. Click on View Source button

**Comment by christian-bromann** [comment]
This is because we will be update WebdriverIO to the v5 docs (http://beta.webdriver.io) soon.
