### ISSUE TITLE
browser.setvalue fail if too many characters and infinite loops appeared

### ISSUE THREAD

**Issue by USB-internet** [webdriverio/webdriverio#2985]
fail :( !!!!!!!!!!!!! browser.setvalue('20000 bytes') I cannot setvalue input 20000 bytes, I realize it only works with 2 ^ 14 bytes :( please help me setvalue 20000 bytes
I need setvalue 1 paragraph text over 20000 characters
The browser.setvalue failed if too many characters and infinite loops appeared

**Comment by christian-bromann** [comment]
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
