### ISSUE TITLE
'class name' selector is hardcoded to iOS and Android naming conventions

### ISSUE THREAD

**Issue by simongranger** [webdriverio/webdriverio#2987]
## The problem

Currently, the 'class name' selector is hardcoded to only support iOS and Android naming conventions. 
https://github.com/webdriverio/webdriverio/blob/1a172d1f05b0d6fde9acdd3ed77c4a19d978ec07/packages/webdriverio/src/utils.js#L71

This means it cannot be used by other Appium drivers: macOS, Windows10, youiengine, etc.
https://github.com/YOU-i-Labs/appium-youiengine-driver
https://github.com/appium/appium-mac-driver
https://github.com/appium/appium-windows-driver

Can we add a generic way of sending a 'class name' query similar to what is done for 'accessibility id' which uses '~'?

https://github.com/webdriverio/webdriverio/blob/1a172d1f05b0d6fde9acdd3ed77c4a19d978ec07/packages/webdriverio/src/utils.js#L64

## Environment

* WebdriverIO version: 4.13.2
* Node.js version: v10.8.0
* Standalone mode or WDIO Testrunner: Testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):

## Details

See Problem above

## Link to Selenium/WebdriverIO logs

No logs required

## Code To Reproduce Issue [ Good To Have ]

No code

**Comment by christian-bromann** [comment]
Yes, do

```js
const elem = $('css selector:.mySelector')
```

**Comment by simongranger** [comment]
'css selector' != 'class name'

**Comment by christian-bromann** [comment]
sorry then:
```js
const elem = $('class name:.mySelector')
```

**Comment by simongranger** [comment]
Awesome!
Thanks!
