### ISSUE TITLE
Add Allure Issue / TMS links support

### ISSUE THREAD

**Issue by sskorol** [webdriverio/webdriverio#2988]
## The problem

Currently Allure Issue / TMS links are not supported by wdio-allure-reporter. I've created PR in a related repository with these features: https://github.com/webdriverio-boneyard/wdio-allure-reporter/pull/141

Going to do the same within corresponding webdriverio package.

**Comment by BorisOsipov** [comment]
Implemented in https://github.com/webdriverio/webdriverio/pull/2989
