### ISSUE TITLE
No readme/setup documentation for wdio-lambda-runner

### ISSUE THREAD

**Issue by mjschlosser8** [webdriverio/webdriverio#2994]
## The problem

I'm in the beginning stages of setting up WDIO to run in an AWS Lambda environment, but there is no documentation on how to set up/run WDIO with the  wdio-lambda-runner plugin (https://www.npmjs.com/package/wdio-lambda-runner). Does anyone have any insight into how this is done?

**Comment by pmerwin** [comment]
That service is still beta, probably have better luck posting here:

https://gitter.im/webdriverio/v5

**Comment by BorisOsipov** [comment]
I think it is ok to post it here.
But yes, try to check history on gitter.im/webdriverio/v5. I remebered someone already asked about wdio-lambda-runner there

**Comment by mjschlosser8** [comment]
I see, thanks for the update. Hope we can see a fully working version in the future!
