### ISSUE TITLE
WDIO packages not installing

### ISSUE THREAD

**Issue by sriramcse31** [webdriverio/webdriverio#3003]
I was able to launch the 'WDIO configuration Helper' wizard from the command prompt and had given all the inputs. Then there is a message saying 'Installing WDIO packages' but there is no progress even after an hour.

Could anyone help me with this issue.

![wdio issue](https://user-images.githubusercontent.com/41834079/46817089-44dd7800-cd76-11e8-8d8c-227aeec8039a.png)

**Comment by FlashBytes** [comment]
Hello Community, I am having exactly the same issue.

Here are the steps to reproduce:

1. Have Windows 10 64Bit installed
2. Install Node 10 or 11 ( I tried different versions of node 10.xx as I thought some version will work)
3. Create a folder
4. Run npm init and get something like

```
{
  "name": "selenium-cucumber",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "webdriverio": "^4.14.0"
  }
}
```

5. Install with "npm install webdriverio"
6. Install selenium and start the standalone server
6. Create a node test.js and run it "node test.js" -> Works for me
7. run "./node_modules/.bin/wdio config"
8. Answer the setup questions
9. Now it hangs exactly as shown in the screenshot

I tried this on different Notebooks and I have Phyton 2.7 and VS 2017 community edition installed.

**Comment by Dan-ders** [comment]
Managed to get around this by using Git Bash terminal.

**Comment by nextlevelbeard** [comment]
Can confirm the issue.

**Environment:**
 - **WebdriverIO version:5.0.0-beta.7**
 - **Mode: WDIO Testrunner**
 - **Running sync**
 - **Node.js version: 10.13.0**
 - **NPM version: 6.4.1**
 - **Browser name and version: N/A**
 - **Platform name and version: Windows 10**
 - **Additional wdio packages used (if applicable): N/A**

**Config of WebdriverIO**
N/A

**Describe the bug**
Running `wdio config`, the selected packages are never installed.

**To Reproduce**
Input the same options as per files attached or answer Y whenever the config utility asks to install the packages for you.

![wdio forever](https://user-images.githubusercontent.com/3788982/48891142-ed353080-ee3a-11e8-8bc5-d9d6eeca367c.PNG)
![wdio forever 2](https://user-images.githubusercontent.com/3788982/48891143-ed353080-ee3a-11e8-83cc-cfa3da97ae3c.png)

**Expected behavior**
Packages should be installed.

**Comment by sriramcse31** [comment]
Resolved the issue by downgrading to node version 8.9.4.

**Comment by sriramcse31** [comment]
The issue with version 10.13.0 still exist.

**Comment by And93** [comment]
So, I have checked on the windows machine.
Unfortunately I can't launch the config generator. [Gist](https://gist.github.com/And93/a3451ffe4a3e02bb6bf0c96fb53a2152)

**Comment by christian-bromann** [comment]
@And93 what project did you try to install?

**Comment by And93** [comment]
It's a new project only with `"@wdio/cli": "^5.0.0-beta.5"` in dependency.

**Comment by abjerstedt** [comment]
@And93 beta.16 is the current version.  You also need webdriverio and webdriver

**Comment by christian-bromann** [comment]
@And93 also note we haven't released v5 yet so the config wizard will install latest instead of @next. Make sure you update all packages to `^5.0.0-beta.16`

**Comment by And93** [comment]
I have update my dependency to `"@wdio/cli": "^5.0.0-beta.16"` and after configure config file, the install process stopped.

(_look at screenshot_)
![screenshot_1](https://user-images.githubusercontent.com/26678405/50360658-cec57080-0571-11e9-8ea2-1d96e5ba2d0d.png)

**Comment by abjerstedt** [comment]
@and93 you shouldn't be using dos prompt for stuff like this. Use gitbash instead. 

Also, wdio went live today with v5 so use 5.0.1.

**Comment by BorisOsipov** [comment]
@And93 can you check with `"@wdio/cli": "^5.0.2"`?

**Comment by SlavaLysjuk** [comment]
Hi folks! I have the same problem when trying to install wdio packages on Windows 10, there stoping.

Do I need to open a new issue? or you can answer in this issue? Thanks!

{
  "name": "webdriverio-tutorial",
  "version": "1.0.0",
  "description": "Thuis is a webdriverIO tutorial",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Slava Lysjuk",
  "license": "ISC",
  "devDependencies": {
    "@wdio/cli": "^6.5.2",
    "webdriverio": "^6.5.2"
  },
  "dependencies": {}
}

![image](https://user-images.githubusercontent.com/30052608/94694133-2d21a480-033d-11eb-8051-2dc00ddb3f7e.png)

after 25 minutes nothing changes...

**Comment by christian-bromann** [comment]
@SlavaLysjuk are you behind a firewall? It seems like your computer can't connect to the NPM registry.

**Comment by SlavaLysjuk** [comment]
> @SlavaLysjuk are you behind a firewall? It seems like your computer can't connect to the NPM registry.

Yes, I have a firewall on my machine, but proxy works for another app...
