### ISSUE TITLE
Chrome extension loading issue

### ISSUE THREAD

**Issue by gurunanakdevji** [webdriverio/webdriverio#3007]
I am not able to load below chrome extension using webdirverio configuration. Could you please help how to load additional chrome extensions when webdriverio is launching chrome browser through test runner. 

capabilities: [{
        maxInstances: 1,
        browserName: 'chrome',
        version: '69.0.3497.100',
        chromeOptions: {
          args: ['--disable-infobars','--start-maximized', '--load-extension=path of extension']
        }

++++++Below is the detail about extension+++++++++++++++++++
Extension Icon
Modify Headers for Google Chrome™
On
Description
Modify Headers for Google Chrome™
Version
2.0.7
Size
9.1 MB
ID
innpjfdalfhpcoinfnehdnbkglpmogdi
Inspect views
background page
options.html
Permissions
Read and change all your data on the websites you visit
Display notifications
Allow in incognito
Warning: Google Chrome cannot prevent extensions from recording your browsing history. To disable this extension in incognito mode, unselect this option.
Allow access to file URLs
Collect errors

Extension options
View in Chrome Web Store
Source
Chrome Web Store

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 5.6.0]
 - **Mode:** [ WDIO Testrunner]
 - **Node.js version: [e.g. 8.11.3]
 - **NPM version:** [e.g. 5.6.0]
 - **Browser name and version:** [e.g. Chrome 69]
 - **Platform name and version:** [e.g. Windows 7]

**Comment by christian-bromann** [comment]
Try:

```js
capabilities: [{
        maxInstances: 1,
        browserName: 'chrome',
        version: '69.0.3497.100',
        'goog:chromeOptions': {
          args: ['--disable-infobars','--start-maximized', '--load-extension=path of extension']
        }
```

**Comment by christian-bromann** [comment]
Also extensions are applied differently, see http://chromedriver.chromium.org/capabilities

**Comment by sanjayprop** [comment]
> Try:
> 
> ```js
> capabilities: [{
>         maxInstances: 1,
>         browserName: 'chrome',
>         version: '69.0.3497.100',
>         'goog:chromeOptions': {
>           args: ['--disable-infobars','--start-maximized', '--load-extension=path of extension']
>         }
> ``

I am getting the alert that . Manifest file is missing or unreadable.
