### ISSUE TITLE
First expect.toBe(true) statement in a test get executed twice if it returned False

### ISSUE THREAD

**Issue by nareshnayini** [webdriverio/webdriverio#3009]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [4.13.2]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running :** [sync]
 - **Node.js version: [10.5.0]
 - **NPM version:** [6.1.0]
 - **Browser name and version:** [Chrome 69]
 - **Platform name and version:** [macOS High Sierra 10.13.5]
 - **Additional wdio packages used (if applicable):** [wdio-json-reporter, wdio-selenium-standalone-service]

**Config of WebdriverIO**
- framework: 'jasmine',
- services: ['selenium-standalone']
maxInstances: 10,
  capabilities: [
    {
      maxInstances: 5,
      browserName: 'chrome',
    },
  ],

**Describe the bug**
First expect.toBe(true) statement in a test executing twice if returns False

**To Reproduce**

I have WebDriverIO Jasmine test like below. When **first** expect statement in the test (here **emailObj**) returning false, test waiting for 45 sec (implicit wait) twice (45+45 = 90 sec) which is unexpected.
it('Should show the login page', () => {
    expect(LoginPage.emailObj.isExisting()).toBe(true);
    expect(LoginPage.passObj.isExisting()).toBe(true);
  });

**Console log**:
[11:39:40]  DATA		{"using":"css selector","value":"div[input=\"email\"]"}
[11:39:40]  DATA		{}
[11:40:25]  DATA		{"using":"css selector","value":"div[input=\"email\"]"}
[11:41:10]  DATA		{"using":"css selector","value":"div[input=\"password\"]"}
**F**

**Expected behavior**
Expect statement should be executed once and waited for implicit wait (45 sec) only once instead twice (90sec)

**Comment by christian-bromann** [comment]
First of, don't use implicit waits. It is much more efficient to use explicit waits. I can't tell why your test is fetching the element twice. I doesn't look like an issue with WebdriverIO. Please use the debug command to find out where that code is being exeucted. It is impossible for people to give advice that are not familiar with the test setup.

Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have further questions. Thanks!
