### ISSUE TITLE
Error  using touchAction moveTo

### ISSUE THREAD

**Issue by leonidas999** [webdriverio/webdriverio#3015]
I'm trying to use the "moveTo"  gesture in the touchAction api, but always get this error 

An unknown server-side error occurred while processing the command. Original error: Failed to execute touch event
running
Error: An unknown server-side error occurred while processing the command.
    at performTouchAction([object Object]) -     at C:\Users\user\Documents\test\node_modules\webdriverio\build\lib\commands\touchAction.js:136:2

**i've tried of several ways**

browser.touchAction(homePage.inputEmail,'moveTo');
browser.touchAction({action:'moveTo',selector:homePage.inputEmail});
browser.touchAction({action:'moveTo',x:200,y:760});

**Environment:**
 - **WebdriverIO version:** v4.13.2
 - **Mode:** WDIO Testrunner
 - **IWDIO Testrunner, running :** sync
 - **Node.js version:** v8.12.0
 - **NPM version:** 6.4.1
 - **Platform name and version:**  android 7.0 
 - **Additional wdio packages used (if applicable):**  wdio-cucumber-framework: 2.2.7,  chai: 4.2.0

**appium server log**
[HTTP] --> POST /wd/hub/session/a962b122-5c47-446d-a92e-114f3381e2db/element
[HTTP] {"using":"-android uiautomator","value":"new UiSelector().className(\"android.widget.EditText\")"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["-android uiautomator","new UiSelector().className(\"android.widget.EditText\")","a962b122-5c47-446d-a92e-114f3381e2db"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 0 ms for condition
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"-android uiautomator","selector":"new UiSelector().className(\"android.widget.EditText\")","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"-android uiautomator","selector":"new UiSelector().className(\"android.widget.EditText\")","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'new UiSelector().className("android.widget.EditText")' using 'ANDROID_UIAUTOMATOR' with the contextId: '' multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Parsing selector: new UiSelector().className("android.widget.EditText")
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] UiSelector coerce type: java.lang.Class arg: "android.widget.EditText"
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] UiSelector coerce type: class java.lang.String arg: "android.widget.EditText"
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=android.widget.EditText]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"ELEMENT":"5"}}
[AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"5"}
[HTTP] <-- POST /wd/hub/session/a962b122-5c47-446d-a92e-114f3381e2db/element 200 34 ms - 87
[HTTP] 
[HTTP] --> POST /wd/hub/session/a962b122-5c47-446d-a92e-114f3381e2db/touch/perform
[HTTP] {"actions":[{"action":"moveTo","options":{"element":"5"}}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"moveTo","options":{"element":"5"}}],"a962b122-5c47-446d-a92e-114f3381e2db"]
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:getLocation","params":{"elementId":"5"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:getLocation","params":{"elementId":"5"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: getLocation
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"x":42,"y":696}}
[AndroidBootstrap] Received command result from bootstrap
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:getSize","params":{"elementId":"5"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:getSize","params":{"elementId":"5"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: getSize
[AndroidBootstrap] Received command result from bootstrap
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:touchMove","params":{"elementId":"5","x":240,"y":711}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"width":396,"height":30}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:touchMove","params":{"elementId":"5","x":240,"y":711}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: touchMove
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Performing TouchMove using element? true x: 240, y: 711
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":13,"value":"Failed to execute touch event"}
[AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[MJSONWP] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Failed to execute touch event
[MJSONWP]     at errorFromMJSONWPStatusCode (C:\Users\jhonny.melo\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:789:10)
[MJSONWP]     at Socket. (C:\Users\jhonny.melo\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\bootstrap.js:139:18)
[MJSONWP]     at emitOne (events.js:116:13)
[MJSONWP]     at Socket.emit (events.js:211:7)
[MJSONWP]     at addChunk (_stream_readable.js:263:12)
[MJSONWP]     at readableAddChunk (_stream_readable.js:246:13)
[MJSONWP]     at Socket.Readable.push (_stream_readable.js:208:10)
[MJSONWP]     at TCP.onread (net.js:594:20)
[HTTP] <-- POST /wd/hub/session/a962b122-5c47-446d-a92e-114f3381e2db/touch/perform 500 170 ms - 200
[HTTP] 
[HTTP] --> GET /wd/hub/session/a962b122-5c47-446d-a92e-114f3381e2db/screenshot
[HTTP] {}
[MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["a962b122-5c47-446d-a92e-114f3381e2db"]
[ADB] Device API level: 24
[MJSONWP] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAAAeAAAANWCAYAAAAm2F/UAACAAElEQVR4AezBC5ScZWH4/+/zPO87992dbO7ktski4aJxAiIQhUzgZ/9WXLMcm59Sq7MgWOHYZlOLoKeatfWI0h6yHOVoAc1o9cff/A5msrFeWmBnC/8gBsxGKJIgMpsLEJLszl5mZ+Z93+d5/ow0xzQngVw2W4nz+QjAUldXV1dXVzepJHV1dXV1dXWTTlJXV1dXV1c36SR1dXV1dXV1k05SV1dXV1dXN+kkdXV1dXV1dZPOoa6urq7uTWvp0qUkEgkONzY2xrPPPku5XKbuD5dDXV3dH5xkMkmxWGSipVIp3v72t5NKpUilUhypv7+f/v5+tm/fTn9/Pyejra2Nms2bN3PIsmXLmDp1KseyefNmZs2axQUXXEAsFuNwO3fuZMeOHZxuqVSK/v5+Jks2m6Wjo4NTlUgkSCaTHE4IgVKKuj9sDqdJLBajUqlgjOFEhcNhqtUqdWeedDpNJpOhpaWFdDpNPp+nUCjwne98h3w+z+mQTqdZvnw5x6uvr498Ps9ESSaTrF+/nk2bNpHNZnkjHR0drF69mhUrVlAsFjlVqVSKTCZDe3s7LS0tvJ50Os0hhUKBXC7Hd77zHfr7+zmdmpqauPjii/mfkkqlmDdvHv39/UyGbDZLJpOho6ODE7V06VISiQSHNDQ0cKREIsE73vEOtNbUjI2NsW3bNur+sDhMsNbWVjo6Orj44ov58pe/zH/8x39wvBKJBO9+97tZsmQJd9xxB3VnjmQyycaNG0mn0xwunU5T09HRQS6X47rrrqNYLDJRWlpa6O3t5UQtXLiQQqHAqWppaWHjxo2kUimWLl1KNpvl9SSTSbq7u2lqamLbtm1cc8019Pf3czLS6TRr164lnU5zMlpaWujs7KSzs5N8Ps8Xv/hF8vk8J2PLli0csmzZMqZOncrmzZs5ZPHixdTs3LmTHTt2MJlSqRTz5s1jsmSzWTKZDCcrkUiQTCZ5PUop...
[HTTP] <-- GET /wd/hub/session/a962b122-5c47-446d-a92e-114f3381e2db/screenshot 200 1390 ms - 366354
[HTTP] 
[HTTP] --> DELETE /wd/hub/session/a962b122-5c47-446d-a92e-114f3381e2db
[HTTP] {}
[MJSONWP] Calling AppiumDriver.deleteSession() with args: ["a962b122-5c47-446d-a92e-114f3381e2db"]
[BaseDriver] Event 'quitSessionRequested' logged at 1539989397185 (17:49:57 GMT-0500 (SA Pacific Standard Time))
[Appium] Removing session a962b122-5c47-446d-a92e-114f3381e2db from our master session list
[AndroidDriver] Shutting down Android driver
[ADB] Running 'C:\android_sdk\platform-tools\adb.exe -P 5037 -s ZY3234MLCJ shell am force-stop com.disney.wdw.android'
[ADB] Pressing the HOME button
[ADB] Running 'C:\android_sdk\platform-tools\adb.exe -P 5037 -s ZY3234MLCJ shell input keyevent 3'
[AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
[AndroidBootstrap] Received command result from bootstrap
[UiAutomator] Shutting down UiAutomator
[UiAutomator] Moving to state 'stopping'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
[AndroidBootstrap] [UIAUTO STDOUT] close [socket][::/:::4724]
[UiAutomator] UiAutomator shut down normally
[UiAutomator] Moving to state 'stopped'
[ADB] Attempting to kill all uiautomator processes
[ADB] Getting all processes with uiautomator
[ADB] Running 'C:\android_sdk\platform-tools\adb.exe -P 5037 -s ZY3234MLCJ shell ps'
[ADB] No uiautomator process found to kill, continuing...
[UiAutomator] Moving to state 'stopped'
[Logcat] Stopping logcat capture
[ADB] Running 'C:\android_sdk\platform-tools\adb.exe -P 5037 -s ZY3234MLCJ shell am force-stop io.appium.unlock'
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[BaseDriver] Event 'quitSessionFinished' logged at 1539989402820 (17:50:02 GMT-0500 (SA Pacific Standard Time))
[MJSONWP] Received response: null
[MJSONWP] But deleting session, so not returning
[MJSONWP] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/a962b122-5c47-446d-a92e-114f3381e2db 200 5639 ms - 76
[HTTP]

**Comment by erwinheitzman** [comment]
Please try the following:
homePage.inputEmail.touchAction('moveTo');

And report if the issue is solved or not, thank you :)

**Comment by saikrishna321** [comment]
Please set automationName as UIAutomator2 and give it a try

**Comment by mgrybyk** [comment]
Please re-open if this is still actual
