### ISSUE TITLE
 An unknown server-side error occurred while processing the command for edge

### ISSUE THREAD

**Issue by DDeepu** [webdriverio/webdriverio#3021]
I am getting  "An unknown server-side error occurred while processing the command " while running the tests on edge browser using selenium grid. tests are running fine on other browsers (chrome and ie) with selenium grid.

wdio config file: 

export default {
  sync: false,
  host:'xxxx.com', (remote host)
    seleniumProtocol: 'WebDriver',
    throwOnCapabilityNotPresent: true,
	logLevel : 'verbose',
	logOutput : '../logs/',
  desiredCapabilities: {
    maxInstances: 2,
    browserName: 'MicrosoftEdge',//Browser choice
	platform: 'WIN10',  
  }
};

Environment 
 - **WebdriverIO version: 4.13.1
 - **Mode: standalone mode
 - **Node.js version: 10.11.0
 - **NPM version: 6.4.1
 - **Browser name and version: Edge 42.17134.1.0
 -** Edge driver version : 17.17134 
 - **Platform name and version: window 10
 - **Selenium server version: 3.12

selenium hub and nodes are configured through jenkins, node is registered fine to hub .

**Comment by christian-bromann** [comment]
@DDeepu without any logs there is no chance that anyone can help you. If you have further questions join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
