### ISSUE TITLE
getText returns array of empty strings when there is a text

### ISSUE THREAD

**Issue by rtran25** [webdriverio/webdriverio#3022]
**Describe the bug**
When using getText(), it returns an array of empty strings instead of the requested string

**To Reproduce**
HTML file
~~~
<div>
        <div>
                <tbody>
                        <div>
                                <table>
                                        <td></td>
                                        <td></td>
                                        <td>
                                                <tr>
                                                        <div>
                                                                <span>
                                                                        <a>test1</a>
                                                                </span>
                                                                <span>
                                                                        <a>test2</a>
                                                                </span>
                                                                <span>
                                                                        <a>test3</a>
                                                                </span>
                                                                <span>
                                                                        <a>test4</a>
                                                                </span>
                                                                <span>
                                                                        <a>test5</a>
                                                                </span>
                                                        </div>
                                                </tr>
                                        </td>
                                </table>
                        </div>
                </tbody>
        </div>
</div>
~~~

JAVASCRIPT file
~~~
let string = await client.getText('div > div > tbody > div > table > td:nth-child(3) > tr > div > span > a');
console.log(string) 
~~~

**Expected behavior**
Returns test1

**Actual behavior**
Returns an empty array of
~~~
[ "", "", "", "", ""]
~~~

**Other Tests**
~~~
let string = await client.getText('div > div > tbody > div > table > td:nth-child(3) > tr:nth-child(1) > div:nth-child(1) > span:nth-child(1) > a:nth-child(1)');
console.log(string) //Returns [ ""]

let string = await client.getHTML('div > div > tbody > div > table > td:nth-child(3) > tr > div > span > a', false);
console.log(string) //Returns [ "test1", "test2", "test3", "test4", "test5"]

let string = await client.getHTML('div > div > tbody > div > table > td:nth-child(3) > tr:nth-child(1) > div:nth-child(1) > span:nth-child(1) > a:nth-child(1)', false);
console.log(string) //Returns "test1"
~~~

**Additional context**
For this instance I will have to use getHTML with emphasis on nth-childs but I know getText does work in other areas. Any reason why it wouldn't in this case?
https://github.com/webdriverio/webdriverio/issues/726
This contains the same question, but I believe it should be a different issue. I could be wrong. When inspecting (ctrl + shift + I) the element on dev tool, "span" is highlighted on the page but "a" is not. Is that a factor?

**Comment by erwinheitzman** [comment]
Are you running webdriverio as standalone or with the wdio testrunner?

**Comment by rtran25** [comment]
> Are you running webdriverio as standalone or with the wdio testrunner?

I am running webdriverio as a standalone

**Comment by erwinheitzman** [comment]
Thank you for your quick reply, I'll look into it when I have the time to do so to see if I can reproduce the issue with the examples given.

**Comment by rtran25** [comment]
> @rtran25 it would help tremendously if you can provide a minimal reproducible example. Thanks!

While I would love to link you the specific url for this, I am unable to as the page is running off a local server and inaccessible outside of the network. I can provide a more detailed example though, one that closely reproduces what I've seen.

The page is a document upload page that has an upload button and table for all documents uploaded. The code for it is:
~~~
<table class="dataTable">
    <thead>
    <tbody>
        <tr role="row" class="even">
            <td class="checkbox"></td>
            <td class="doc_num"></td>
            <td class="doc_name">
                <a href="#">
                    <span>
                        <span>DOCUMENT NAME</span>
                    </span>
                </a>
            </td>
        </tr>
        <tr role="row" class="odd"></tr>
    </tbody>
    </thead>
</table>
~~~
I am attempting to use 

`let test = await browser.getText('table.dataTable > tbody > tr > td:nth-child(3) > a > span > span');` to acquire the document name. In the dev console, hovering over the `span` that contains DOCUMENT NAME does not highlight anything on the web page, but hovering over the prior span will. Below is a small excerpt from the web page if that is more helpful than my prior example.

![example](https://user-images.githubusercontent.com/22303079/47795596-0df8e300-dce0-11e8-998a-130d2547b194.PNG)

Please let me know if you need anything else. I'm not sure what more I can add.

**Comment by christian-bromann** [comment]
> Please let me know if you need anything else. I'm not sure what more I can add.

With minimal reproducible example I don't mean you need to give us access to your page. All we need is a simple HTML page and a test that we can run against that page. If this problem only occurs on your page we can't fix this. However if you can prove that this is a general problem by creating a reproducible example we can definitely take a look.

**Comment by rtran25** [comment]
> > Please let me know if you need anything else. I'm not sure what more I can add.
> 
> With minimal reproducible example I don't mean you need to give us access to your page. All we need is a simple HTML page and a test that we can run against that page. If this problem only occurs on your page we can't fix this. However if you can prove that this is a general problem by creating a reproducible example we can definitely take a look.

I think at this point it is not possible to reproduce the problem with a simple HTML page. There may be some JS involved that causes this issue to occur. I will research more into the JS of this page to see if I can pin point why. As you can see from my previous attachment, the element is not disabled/not invisible so it should work, but doesn't. There may be an underlying JS code that completely messes with it. I will close this issue and reopen it if I can reproduce it or comment if I found a reason why this happens. Thanks!
