### ISSUE TITLE
getting Type Error: Cannot read property 'trim' of undefined while using selectByVisibleText() command 

### ISSUE THREAD

**Issue by skg1214** [webdriverio/webdriverio#3023]
exact stack trace:TypeError: Cannot read property of 'trim' of undefined at Object.selectByVisibleText(---------);

**Comment by christian-bromann** [comment]
@skg1214 can you please create a reproducible example?

**Comment by mounicaparupalli** [comment]
I was using the following code for selectByVIsibleText. please find HTML code and logic 

<select id="VTPTselectedIndividual" name="VTPTselectedIndividual" required="required" style="">
                                                        <option value="SFR" selected="selected">SFR</option>
                                                        <option value="TwoFourFamily">2-4 Family</option>
                                                        <option value="Condo">Condo</option>
                                                        <option value="Townhouse">Townhouse</option>
                                                        <option value="Coop">Co-op</option>
                                                    </select>
the code i have used is 

alaCarte.getPropertyAdditionalModal().waitForVisible(90000);
    if(alaCarte.getPropertyAdditionalModal().isVisible()){
        console.log(alaCarte.getPropertyType());
        var config = alaCarte.getPropertyType();
            config.selectByVisibleText(propertytype);

throwing below error. please find stack trace here:
Cannot read property 'trim' of undefined
running chrome
TypeError: Cannot read property 'trim' of undefined
    at Object.selectByVisibleText


thanks
