### ISSUE TITLE
Add 'browsers' to config wizard options

### ISSUE THREAD

**Issue by klamping** [webdriverio/webdriverio#3025]
**Is your feature request related to a problem? Please describe.**
I usually run my tests using Chrome, due it having really great support via Chromedriver. That means every time I create a new project, I need to open the wdio.conf.js file after creation and change 'firefox' to 'chrome'.

**Describe the solution you'd like**
I think it'd be useful to allow for browsers to be selected when going through the configuration wizard. You can select multiple browsers, similar to how services are done.

![screen shot 2018-10-26 at 5 09 28 pm](https://user-images.githubusercontent.com/706039/47594655-fae1be00-d941-11e8-8f79-b9c5e411ef1a.png)

**Describe alternatives you've considered**
haven't thought of any alternatives, aside from not making the change.

**Additional context**
What browsers should we include in the options by default? Chrome and Firefox makes sense to me. Maybe IE/Edge? Safari has poor webdriver support in my experience, so maybe leave that out?

If this sounds good, I'd like to take a stab at writing the code to make it happen. Seems like I could copy what's being done for services/reporters pretty easily.

**Comment by pmerwin** [comment]
I think firefox and chrome are sufficient.  imho

**Comment by kasyed245** [comment]
Please include IE support too. As many public/govt services still relying heavily on IE and it is one of the automation regression test requirement. Thanks :)

**Comment by christian-bromann** [comment]
Let's continue convo in #3026
