### ISSUE TITLE
Getting error after deploy server on heroku

### ISSUE THREAD

**Issue by MuhammadMohsin** [webdriverio/webdriverio#3031]
**Environment (please complete the following information):**
 -dependencies:
    "chrome": "^0.1.0",
    "chromedriver": "^2.43.1",
    "dotenv": "^5.0.1",
    "express": "^4.16.3",
    "nodemon": "^1.17.4",
    "selenium-webdriver": "^4.0.0-alpha.1",
    "wdio-devtools-service": "^0.1.5

**Comment by christian-bromann** [comment]
Sorry I have to close this. If you have issues please fill a proper issue report.
