### ISSUE TITLE
Request Handler doesn't wait for `connectionRetryTimeout`

### ISSUE THREAD

**Issue by emilyrohrbough** [webdriverio/webdriverio#3037]
**Environment (please complete the following information):**
 - **WebdriverIO version:** v4.14.0 (have not test in v5, but code appears to be implemented similarly)
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v8.4.0
 - **NPM version:** v5.3.0
 - **Browser name and version:** Selenium Grid v2.53.1 and Selenium Grid v3.14.0
    - Docker Selenium Chrome (both versions)
    - Docker Selenium Firefox (both versions)
    - IE 11 on Windows 10 machine (both versions)
 - **Platform name and version:** N/A but macOS 10.12.6, Windows, and/or Linux

 - **Additional wdio packages used (if applicable):** N/A

**Config of WebdriverIO**
```js
const config = {
  specs: path.join('test*', 'wdio', '**', '*-spec.js'),
  maxInstances: 1,
  sync: true,

  baseUrl: `http://${ip}:8080`,
  capabilities: [{  browserName: 'chrome' }],

  connectionRetryTimeout: 900,
  connectionRetryCount: 2,
 
  framework: 'mocha',
  mochaOpts: { ui: 'bdd', timeout: 200 },
};
```

**Describe the bug**
The launcher will request a new session and if an session does not immediately return a success or error response, the Request Handler will send another request if the retry count has not been reached. [The Request Handler is not waiting for the `connectionRetryTimeout` to expire before sending a new session request](https://github.com/webdriverio/webdriverio/blob/v4/lib/utils/RequestHandler.js#L278).

The issue was noticed when using webdriver.io to run integration tests against a selenium grid that is not build and torn down for each test run but continuously exists for CI pipeline runs.

For an example, lets say the selenium grid with one Chrome node and we are using the wdio config from above. Now lets say the Chrome node is currently in-use by a test run started by CI Node A. When CI Node B starts it's test run:
1. The webdriver.io request handler will send a request for a new session with the Chrome node.
2. The node is busy, the Selenium Grid stores the session request in it's Request queue.
3. The webdriver.io Request Handler did not receive a response and the request count is less than 2 so it immediately sends another session request. It should have waited for 900.
4. CI Node A has not finished. Chome Node is still busy. Selenium Grid Request queue now has two session requests.

I would expect if CI Node A takes a really long time to finish it's test run and CI Node B times out, then the second request would be sent to attempt to recover the test run.

**Expected behavior**
The Request Handler should wait for the retryConnectionTimeout to expire before sending a new request session.

**Comment by christian-bromann** [comment]
Hey,

we updated the core architecture of WebdriverIO and with that a lot of implementation details that might make this issue obsolete. Please try with the latest version of WebdriverIO and verify if this still occurs. If so please open a new issue and we will tackle it asap.

Thanks!
