### ISSUE TITLE
How to get process id (pid) of running browser instance?

### ISSUE THREAD

**Issue by TheHalcyonSavant** [webdriverio/webdriverio#3038]

**Comment by christian-bromann** [comment]
try
```js
console.log('This process is your pid ' + process.pid);
```

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
