### ISSUE TITLE
Drag and drop issue

### ISSUE THREAD

**Issue by gurunanakdevji** [webdriverio/webdriverio#3040]
I am trying to do drag and drop using the command "browser.dragAndDrop(sourceElem,destinationElem);" in the test runner based wdio execution on latest version of Chrome browser. The drag and drop is not working. I have read somewhere that this will be fixed across browsers. Is it fixed? I have latest version of wdio running in my setup. 

**Environment (please complete the following information):**
 "webdriverio": "4.13.0"
 - **Mode:**  WDIO Testrunner]
 - **Node.js version: [e.g. 8.11.3]
 - **NPM version:** [e.g. 5.6.0]
    "wdio-cucumber-framework": "~2.2.0",

**Comment by christian-bromann** [comment]
> this will be fixed across browsers. Is it fixed?

No. You can try the `actions` command to emulate drag&drop. We are still waiting on the browser vendors to support this behavior.
