### ISSUE TITLE
Browser can't change frame

### ISSUE THREAD

**Issue by FishSaidNo** [webdriverio/webdriverio#3041]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 4.14.0
 - **Mode:** Standalone
 - **Node.js version:** 8.11.4
 - **NPM version:** 6.3.0
 - **Browser name and version:** Chrome 69.0.3497.100
 - **Platform name and version:** MacOS 10.14

**Config of WebdriverIO**
```
    desiredCapabilities: {
        chromeOptions: {
            args: ["no-sandbox", "disable-dev-shm-usage"]
        },
    },
    host: '127.0.0.1',
    port: 4444,
    path: '/wd/hub',
    baseUrl: null,
    coloredLogs: true,
    screenshotPath: null,
    waitforTimeout: 500,
    waitforInterval: 250
```

**Describe the bug**
Using browser.frame() to change the frame, then trying to interact with content within the frame results in an error. The iframe is located in a new window (if that is relevant).

**To Reproduce**
Code snippet:
```
    ...
    browser.click("#continueToWirecard"); // This opens a new window which contains an iframe and other content

    var tabIds = browser.getTabIds();
    browser.window(tabIds[tabIds.length-1]); // change to new window

    browser.waitForExist('.wirecard-seamless-frame', 10000);
    browser.pause(10000); // ensure content in iframe has fully loaded
    var wirecardIframe = browser.element('.wirecard-seamless-frame').value;

    browser.frame(wirecardIframe); // enter iframe
    browser.pause(1000);
    browser.setValue("#first_name", "My Name");
```

This results in `Uncaught Error: An element could not be located on the page using the given search parameters ("#first_name").`

**Expected behavior**
Expected that the element in the iframe would be found.

**Log**
[Webdriver log](https://gist.github.com/FishSaidNo/edb0de97def4fbd0a2d83c430196e64a)

**Additional context**
Can provide more details as required.

**Comment by christian-bromann** [comment]
@FishSaidNo have you tried with a parameter, e.g. `browser.frame(0)`. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by FishSaidNo** [comment]
A suggestion in Gitter was to use `browser.frame(0)`, this did not work either.
It appears this issue is only present when using Chrome, works fine in Firefox.
