### ISSUE TITLE
Unable to dismiss "turn off popup blocker" in webdriverIo safari browser

### ISSUE THREAD

**Issue by logakarthi** [webdriverio/webdriverio#3042]
I tried to dismiss the popup using capabilities and javascript code but couldn't and I'm using cross-browser testing cloud tool for webdriverIO. But that popup does not come up in Android devices.
Please provide the solution for the issue.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2]
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version: v8.11.3
 - **NPM version:** 5.6.0
 - **Browser name and version:** [e.g. Safari]
 - **Platform name and version:** [e.g. iOS]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Comment by logakarthi** [comment]
![image](https://user-images.githubusercontent.com/42075235/48250768-67ba8500-e425-11e8-8f57-d702653030d7.png)

**Comment by christian-bromann** [comment]
Please use `alertDismiss` when this happens. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
