### ISSUE TITLE
windowHandleMaximize() does not work on Chrome 70+

### ISSUE THREAD

**Issue by PetrJandak** [webdriverio/webdriverio#3043]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.12]
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **Node.js version: [8.12.0]
 - **NPM version:** [6.4.1]
 - **Browser name and version:** [ Chrome 70]
 - **Platform name and version:** [MAC OSX HighSierra]
 - **Additional wdio packages used (if applicable):** [@wdio/spec reporter, @wdio/selenium-standalone service]

**Describe the bug**
Error: An unknown server-side error occurred while processing the command.
    at windowHandleMaximize() - index.js:312:3
fails the test
**To Reproduce**
with given setup as above

browser.windowHandleMaximize()
**Expected behavior**
browser should maximize the window
**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Comment by abjerstedt** [comment]
ChromeDriver 2.44

Supports Chrome v69-71
Fixed WindowMaximize on Mac
Fixed Incorrect 'alert open error' for window handle call
Fixed Element Send Keys should get "text" property in W3C mode
Fixed XML special case of Is Element Enabled is not handled as per spec
Fixed XML special case of Get Element CSS Value is not handled as per spec
Fixed Set Window Rect needs to check for invalid input
Fixed Support new unhandledPromptBehavior modes
