### ISSUE TITLE
browser.timeouts('implicit', 5000) returns "Error: Remote end send an unknown status code"

### ISSUE THREAD

**Issue by sanjeethgwd** [webdriverio/webdriverio#3044]
On webdriverIO with FireFox browser(gecko), `browser.timeouts('implicit', 5000);` returns "Error: Remote end send an unknown status code"

But, this works fine with chrome client and driver
same goes to `browser.timeouts('script', 60000);`, `browser.timeouts('pageLoad', 10000);`

**Environment (please complete the following information):**
 - **WebdriverIO version :4.12.0
 - **Mode: Standalone mode 
 - **If WDIO Testrunner, running sync/async: sync
 - **Node.js version: v8.9.4
 - **NPM version: 5.6.0
 - **Browser name and version: Firefox 63.0.1
 - **Platform name and version: Windows 10

**SPEC Report**
[firefox #0-0] unknown field ms, expected one of implicit, pageLoad, script at line 1 column 5
Build info: version: '3.9.0', revision: '698b3178f0', time: '2018-02-05T14:56:13.134Z'
System info: host: 'XXXX', ip: 'XX.XX.XX.XX', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: unknown
[firefox #0-0] Error: Remote end send an unknown status code.
[firefox #0-0] at timeouts("implicit", 5000) - at D:\XXX\node_modules\wdio-sync\build\index.js:316:3
[firefox #0-0]
error Command failed with exit code 1.

**Comment by khanhdodang** [comment]
Hi @sanjeethgwd,

Please try with this

`browser.timeouts({
  'script': 60000,
  'pageLoad': 60000,
  'implicit': 60000
})`

Or

`browser.timeouts({'type': 'script', 'ms': 60000})`
`browser.timeouts({'type': 'page load', 'ms': 60000})`
`browser.timeouts({'type': 'implicit', 'ms': 60000})`

**Comment by sanjeethgwd** [comment]
@khanhdodang Thanks, I could resolve with below 

```.js
browser.timeouts({ 'implicit': 5000 });
