### ISSUE TITLE
Bug: Missing encoding in deleteCookie('name')

### ISSUE THREAD

**Issue by shafh** [webdriverio/webdriverio#3045]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 4.12.0
 - **Mode:** Standalone
 - **Node.js 8.12.0
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome 67
 - **Platform name and version:** Ubuntu

**Describe the bug**
`this.browser.deleteCookie('cookieName');` is having an encoding issue.

Following code works:
```
this.browser.setCookie({ name: 'test', value: 'bla', path: '/' });
this.browser.deleteCookie('test');
```
But if I add a '/' to the name is it failing:
```
this.browser.setCookie({ name: '/test', value: 'bla', path: '/' });
this.browser.deleteCookie('/test');
```
Output: 

> unknown command: session/9b7821796bf81d4bd97db05cf5862120/cookie//test
running chrome
Error: unknown command: session/9b7821796bf81d4bd97db05cf5862120/cookie//test
    at deleteCookie("/test") - at cookie("DELETE", "/test") - deleteCookie.js:56:17

The reasons seems to be because deleteCookie is doing a HTTP DELETE request where the '/' gets interpreted as part of the url. 

A double URI encoding seems to do the trick but its a workaround:
```
this.browser.setCookie({ name: '/test', value: 'bla', path: '/' });
this.browser.deleteCookie(encodeURIComponent(encodeURIComponent('/test')));
```

**To Reproduce**

```
this.browser.setCookie({ name: '/test', value: 'bla', path: '/' });
this.browser.deleteCookie('/test');
```

**Expected behavior**
I expect WebdriverIO to encode data for me.

**Comment by dmhalejr** [comment]
@christian-bromann Hey I'd love to claim this. Is the above double encoding workaround define above be the proper solution for the code base?

**Comment by christian-bromann** [comment]
@dmhalejr of course, thanks! We moved the v4 code base to https://github.com/webdriverio-boneyard/v4. I am not sure if this bug still applies for v5

**Comment by dmhalejr** [comment]
@christian-bromann Per the PRTemplate -- I don't mind proposing the same change to the v5 repo for this proposal as well and will follow your lead if you think it's necessary. Thanks for all you do! 🙇

**Comment by christian-bromann** [comment]
@dmhalejr can we have such patch for v5 too?

**Comment by christian-bromann** [comment]
@dmhalejr can you propose the same PR for v5 too?
