### ISSUE TITLE
I click on export button in my web application and then Windows's7 Save As file window opens then how can I choose the file path and enter the name in non-browser window using webdriverIO? Please let me know.

### ISSUE THREAD

**Issue by gurunanakdevji** [webdriverio/webdriverio#3048]
**Describe your question with as much detail as possible**
A clear and concise question that doesn't require too much conversation. Need more help? [Find us on Gitter](https://gitter.im/webdriverio/webdriverio)

**If it's about a specific piece of code, try and include some of it to support your question.**
[...]

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2]
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version: [e.g. 8.9.1]
 - **NPM version:** [e.g. 5.8.0]
 - **Browser name and version:** [e.g. Chrome 68]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Additional context**

**Comment by christian-bromann** [comment]
You can set default directories for downloads as `chrome:options`, not sure about Firefox. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
