### ISSUE TITLE
Console.logs in custom commands are swallowed by the test runner

### ISSUE THREAD

**Issue by goodbomb** [webdriverio/webdriverio#3050]
**Describe your question with as much detail as possible**
I'm trying to debug a custom command that I've made in order to verify the output of some internal logic. However, I'm unable to log anything to console in these custom commands. It seems that console.log gets swallowed by the test runner and I am never able to see the output. More specifically, if I'm using the `execute` command, any console logs inside of the script I am executing never surface in the console.

for example:

```
function myFunction(message) {

    function doSomething() {
        console.log(message);
    }

    return doSomething(message);
}

module.exports = (function() {
    browser.addCommand('myCommand', function(message) {

        return this.execute(myFunction, message);
    });
})();
```

In the above scenario `console.log(message);` never shows the message in the console. How can I surface all console logs in my test output?

**Comment by christian-bromann** [comment]
What version of webdriverio are you using? Can you provide a minimal reproducible project?

**Comment by goodbomb** [comment]
Sorry, we're using v4.13.2 of webdriver.io.

I'll put together a basic project that can reproduce this behaviour.

**Comment by goodbomb** [comment]
@christian-bromann here is a working example: https://github.com/goodbomb/wdio-issue3050-example

I would expect my `console.log` to appear in the output to console, but it only appears in the "args" output in the "DATA" block.

**Comment by christian-bromann** [comment]
@goodbomb thanks for creating the example. It makes sense to me now. You are running the console.log in the browser and WebdriverIO can't get that data until you call the `log` command. As log type you need to specify `browser` to get all logs from the browser. So WebdriverIO is not swallowing these logs they are just not executed in Node.JS but in the browser. This is not an issue with WebdriverIO.

**Comment by goodbomb** [comment]
@christian-bromann Ah, thanks. That makes more sense now. So the console.log at that point is being output to the browser, which is why it's not showing up in the command prompt. I appreciate the help.
