### ISSUE TITLE
Node fiber issue is raised when start the automation test using Test Runner. Chrome browser is not launched.

### ISSUE THREAD

**Issue by gurunanakdevji** [webdriverio/webdriverio#3054]
When running the automation tests using test runner; I am getting below issue related to node fibers and Chrome browser is not launched

Issue Details:

PS D:\dev\temp\test\wdf-automation> npm run test

> wdfautomation@1.3.2 test D:\dev\temp\test\wdf-automation
> wdio wdio.conf.js

## There is an issue with `node-fibers` ##
`D:\dev\temp\test\wdf-automation\node_modules\fibers\bin\win32-x64-67\fibers.node` is missing.

Try running this to fix the issue: C:\Program Files\nodejs\node.exe D:\dev\temp\test\wdf-automation\node_modules\fibers/
build
Error: Cannot find module 'D:\dev\temp\test\wdf-automation\node_modules\fibers\bin\win32-x64-67\fibers'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\dev\temp\test\wdf-automation\node_modules\fibers\fibers.js:13:39)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\dev\temp\test\wdf-automation\node_modules\fibers\future.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
ERROR: Couldn't initialise framework "wdio-cucumber-framework".
Error: Missing binary. See message above.
    at Object.<anonymous> (D:\dev\temp\test\wdf-automation\node_modules\fibers\fibers.js:22:9)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\dev\temp\test\wdf-automation\node_modules\fibers\future.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)

    at Runner.initialiseFramework (D:\dev\temp\test\wdf-automation\node_modules\webdriverio\build\lib\runner.js:534:27)
    at Runner._callee$ (D:\dev\temp\test\wdf-automation\node_modules\webdriverio\build\lib\runner.js:101:55)
    at tryCatch (D:\dev\temp\test\wdf-automation\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\dev\temp\test\wdf-automation\node_modules\regenerator-runtime\runtime.js:296:22
)
    at Generator.prototype.(anonymous function) [as next] (D:\dev\temp\test\wdf-automation\node_modules\regenerator-runt
ime\runtime.js:114:21)
    at step (D:\dev\temp\test\wdf-automation\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at D:\dev\temp\test\wdf-automation\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.0]
 - **Mode: WDIO Testrunner
  - **Node.js version: 11.1.0
 - **NPM version:** 6.3.0
 - **Browser name and version: Chrome 69
 - **Platform name and version: Windows 7

**Comment by christian-bromann** [comment]
Please use Node v10 until we have updated fibers.

**Comment by christian-bromann** [comment]
Fibers was updated. This issue should be resolved now.

**Comment by ukolovpk** [comment]
@olegkqa , did you find any solution?

**Comment by christian-bromann** [comment]
@ukolovpk @olegkqa this issue is fixed with WebdriverIO v5

**Comment by AmarjeetSinghMatharu** [comment]
Hi  I am seeing this issue with fibers when installing on Node 15! is this defect is fixed or I am still seeing it ?

**Comment by christian-bromann** [comment]
> Hi I am seeing this issue with fibers when installing on Node 15!

I don't. To reproduce:

```sh
$ nvm install 15
$ mkdir wdiotest
$ cd wdiotest
$ npm i @wdio/cli
$ npx wdio config --yes
$ npx wdio
```

works fine.

**Comment by MikoSh95** [comment]
Hi. 

I have the same issue with Node v15.3.0 installed with nvm 0.37.2. Doing exactly the same same steps as @christian-bromann 

```
pm@XPS15-PM:~/workspace/wdio-ts$ npx wdio config -y
2020-12-08T14:43:28.798Z DEBUG @wdio/sync: Couldn't load fibers package for Node v10 and above

=========================
WDIO Configuration Helper
=========================


Installing wdio packages:
- @wdio/local-runner
- @wdio/mocha-framework
- @wdio/spec-reporter
- wdio-chromedriver-service
- @wdio/sync
- chromedriver
npm WARN deprecated debug@4.2.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm ERR! code 127
npm ERR! path /home/pm/workspace/wdio-ts/node_modules/fibers
npm ERR! command failed
npm ERR! command sh -c node build.js || nodejs build.js
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.3.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.6.9 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/pm/.nvm/versions/node/v15.3.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/pm/workspace/wdio-ts/node_modules/fibers/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/pm/.nvm/versions/node/v15.3.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/pm/.cache/node-gyp/15.3.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/pm/.cache/node-gyp/15.3.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/pm/.nvm/versions/node/v15.3.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/pm/.cache/node-gyp/15.3.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/pm/workspace/wdio-ts/node_modules/fibers',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/home/pm/.nvm/versions/node/v15.3.0/lib/node_modules/npm/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /home/pm/.nvm/versions/node/v15.3.0/lib/node_modules/npm/node_modules/which/which.js:57:18
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/home/pm/.nvm/versions/node/v15.3.0/lib/node_modules/npm/node_modules/which/which.js:54:21)
npm ERR! gyp ERR! stack     at /home/pm/.nvm/versions/node/v15.3.0/lib/node_modules/npm/node_modules/which/which.js:71:22
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/home/pm/.nvm/versions/node/v15.3.0/lib/node_modules/npm/node_modules/which/which.js:69:33)
npm ERR! gyp ERR! stack     at /home/pm/.nvm/versions/node/v15.3.0/lib/node_modules/npm/node_modules/which/which.js:80:22
npm ERR! gyp ERR! stack     at /home/pm/.nvm/versions/node/v15.3.0/lib/node_modules/npm/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /home/pm/.nvm/versions/node/v15.3.0/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! System Linux 4.4.0-19041-Microsoft
npm ERR! gyp ERR! command "/home/pm/.nvm/versions/node/v15.3.0/bin/node" "/home/pm/.nvm/versions/node/v15.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
npm ERR! gyp ERR! cwd /home/pm/workspace/wdio-ts/node_modules/fibers
npm ERR! gyp ERR! node -v v15.3.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok 
npm ERR! node-gyp exited with code: 1
npm ERR! Please make sure you are using a supported platform and node version. If you
npm ERR! would like to compile fibers on this machine please make sure you have setup your
npm ERR! build environment--
npm ERR! Windows + OS X instructions here: https://github.com/nodejs/node-gyp
npm ERR! Ubuntu users please run: `sudo apt-get install g++ build-essential`
npm ERR! RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
npm ERR! Alpine users please run: `sudo apk add python make g++`
npm ERR! sh: 1: nodejs: not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pm/.npm/_logs/2020-12-08T14_43_38_382Z-debug.log
```

Not sure if this is relevant but I'm running it on Ubuntu 18.04 using WSL2

**Comment by christian-bromann** [comment]
> npm ERR! gyp ERR! stack Error: not found: make

@MikoSh95 seems you have `make` not installed on your machine.

**Comment by PavelHerasimov** [comment]
Hi.
I have the same issue as MikoSh95.

Description:
The full error log output - https://paste.gg/p/anonymous/774c5fb63df24b34a011cc5884e1f5a0/files/fb4fe50b23514997aacb79e729340407/raw
What version of WebdriverIO you have installed - "^6.10.5"
What version of NodeJS you're using - v15.3.0
The contents of your package.json - https://paste.gg/p/anonymous/e712cc04cac94da381956bcb44d6fbee/files/accbaca39fb5488ba324e00116d844fd/raw

**Comment by MikoSh95** [comment]
> > npm ERR! gyp ERR! stack Error: not found: make
> 
> @MikoSh95 seems you have `make` not installed on your machine.

Life would be easier of only I could read... That was the problem, thank you!

**Comment by MikoSh95** [comment]
@PavelHerasimov I assume that you have installed Node on Windows using installer and the errors points out that you have skipped one of the installation steps. See print screen below (option "Automatically install the necessary tools..." should be checked)

![image](https://user-images.githubusercontent.com/23083053/101604355-18c6eb80-3a01-11eb-91af-364f37ac7c08.png)

To solve it you can either reinstall Node with that checkbox checked or follow the instruction how to install dependencies manually from that link: https://github.com/nodejs/node-gyp#on-windows

**Comment by PavelHerasimov** [comment]
> @PavelHerasimov I assume that you have installed Node on Windows using installer and the errors points out that you have skipped one of the installation steps. See print screen below (option "Automatically install the necessary tools..." should be checked)
> 
> ![image](https://user-images.githubusercontent.com/23083053/101604355-18c6eb80-3a01-11eb-91af-364f37ac7c08.png)
> 
> To solve it you can either reinstall Node with that checkbox checked or follow the instruction how to install dependencies manually from that link: https://github.com/nodejs/node-gyp#on-windows

Thank you so much man, I resolve it with your advice! I so appreciated!

**Comment by DenysBarkan** [comment]
```
"node -v" : "v14.15.4"
"@wdio/cli": "^6.6.6"
```
returns the exception : 
`"DEBUG @wdio/sync: Couldn't load fibers package for Node v10 and above"`

instead of the 
```
"node -v" : "v12.20.1"
"@wdio/cli": "^6.6.6"
```
works without any additional messages.
