### ISSUE TITLE
Clean up v4 branch after v5 release to reduce repo size

### ISSUE THREAD

**Issue by Bamieh** [webdriverio/webdriverio#3056]
When cloning the repo, the size of the repo is `127.18 MiB`! Here is a simple breakdown of where this is coming from (mostly from the `.git` folder)

```
3.1M	./website
168K	./docs
200K	./examples
 40K	./scripts
3.6M	./packages
 12K	./.github
129M	./.git
136M	.
```

I believe we should try to reduce the git history size someway or another.

**Comment by christian-bromann** [comment]
> I believe we should try to reduce the git history size someway or another.

@Bamieh that size is due to the history of the v4 branch because in the early days this project used to check in the selenium-server bundles. Once we get rid of that branch when we release v5 this size should go down drastically.

**Comment by christian-bromann** [comment]
Moved v4 repo to https://github.com/webdriverio-boneyard/v4. Used [bfg-repo-cleaner](https://rtyley.github.io/bfg-repo-cleaner/) to remove:

```
9746cca5984c9550525105202c393a5d3d62bdf1 27360570 selenium-server-standalone-2.11.0.jar
7a7f88006e46a85f3c9eeb6c2216f1b7d6a2e11c 30449496 selenium-server-standalone-2.21.0.jar
92be8bae1eb81f8881f236a17366fa158737f9e6 31748367 selenium-server-standalone-2.22.0.jar
95fc5027eae2ddf768c904b951cf965ea7cbeb63 34289992 selenium-server-standalone-2.31.0.jar
c28f57c16a59805c35f2506a43c3522aa753b174 34392526 selenium-server-standalone-2.34.0.jar
d934702325d4cc83c8c40374e4c30532827e557f 25251715 selenium-server-standalone-2.5.0.jar
55fe4d6a750204683760bc796273a7a1d0207ee2 26569549 selenium-server-standalone-2.7.0.jar
```

Checkout out fresh repo and size is now by 9.7mb which is reasonable. I will attach the bfg reports:

[cache-stats.txt](https://github.com/webdriverio/webdriverio/files/2663119/cache-stats.txt)
[deleted-files.txt](https://github.com/webdriverio/webdriverio/files/2663121/deleted-files.txt)
[object-id-map.old-new.txt](https://github.com/webdriverio/webdriverio/files/2663122/object-id-map.old-new.txt)

**Comment by Bamieh** [comment]
Awesome
