### ISSUE TITLE
importing @wdio/logger throws an error.

### ISSUE THREAD

**Issue by Bamieh** [webdriverio/webdriverio#3057]
Simply importing `@wdio/logger` version `beta.5` throws the following error:

```js
import getLogger from '@wdio/logger'
```

```
<..>/node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:49
      throw new Error("You can't reassign a plugin after appling another plugin");
```

This error started happening after switching from the package `wdio-logger`.

For context; I am using this logger in my e2e wrapper to do the following:

```js
import getLogger from '@wdio/logger'
// Error is thrown upon import before reaching the rest of the code.

...

browser.logger = getLogger('client');
```

This way the client has a simple logger that my team can use in our tests to log things. Any idea on what's causing this? I tried tracing it down but `@wdio/logger` is using an older version of `loglevel-plugin-prefix`.

**Comment by christian-bromann** [comment]
@Bamieh can you provide a reproducible example? Using wdio testrunner I was just able to import the logger and do some random logging.

**Comment by Bamieh** [comment]
@ChrisOelmueller 	thanks for your time. The following script causes the error:

```js
const {
  remote,
  RemoteOptions,
} = require('webdriverio');

const getLogger = require('@wdio/logger').default


const myLogger = getLogger('E2E')
myLogger.debug('Hello')
```


I'm using the following package versions:

```
"@wdio/logger": "5.0.0-beta.5",
"webdriverio": "5.0.0-beta.5"
```

**Comment by Bamieh** [comment]
@ChrisOelmueller 	I've just updated `webdriverio` to `beta.5` and it works so I believe its not a big issue anymore especially since we have exact versions now so this should not break again in the future just by doing a new npm install. Feel free to close this.

**Comment by ChrisOelmueller** [comment]
You probably wanted @christian-bromann :-)

**Comment by Bamieh** [comment]
@ChrisOelmueller haha yes my bad ❤️

**Comment by christian-bromann** [comment]
Glad it is fixed.
