### ISSUE TITLE
Add retries option will allow to retry framework's hooks

### ISSUE THREAD

**Issue by shackijj** [webdriverio/webdriverio#3070]
**Problem**
The webdriverio supports the retries option which is described [here](http://webdriver.io/guide/testrunner/retry.html). The problem is that using the feature in a big project causes a lot of boilerplate code.

For example, one decides to use retry options in all beforeEach in a codebase. It means that he will either create a constant and use it in tests or create a helper function.
Using the constant
```
import {RETRIES_COUNT} from "./constants";
describe('some description', () => {
    beforeEach(() => {
       // some implementation
    }, RETRIES_COUNT);
})
```

Using a helper function

/beforeEachWithRetries.js
```
const RETRIES_COUNT = 1;
function beforeEachWithRetries(fn) {
    beforeEach(fn, RETRIES_COUNT);
}
 ```

```
import beforeEachWithRetries from './beforeEachWithRetries';
describe('some description', () => {
     beforeEachWithRetries(() => {
         // implementation;
     })
    it('some tests');
})
```

**Solution**
I suggest to add an option which will allow to specify the hook name and the number of retries.

```
{
    frameworkOpts: {
        hookRetries: {
            beforeEach: 4,
            aftereEach: 2
       }
    }
}
```

**Alternatives**
I researched Mocha's documentation and codebase and found out that it doesnt support the retries for beforeEach and afterEach hooks. 

It seems like that the feature is not difficult to implement. The config should be passed somehow to [this](https://github.com/webdriverio/webdriverio/blob/6d5e90a29903eb5097377488de76701f0aa36aa4/packages/wdio-sync/src/index.js#L111) function. Then the retriesCnt will use either the value given as a function parameter or from the frameworkOpts.reties.

**Comment by christian-bromann** [comment]
@shackijj I don't know if it is a good idea to allow setting retries globally. You usually don't want to retry and rather see if you can fix the flaky behavior. You can also set retries always via a global environment variable, e.g. in your wdio.conf. I don't see how an extra config property is useful here. Thanks for the suggestion though!

**Comment by shackijj** [comment]
Thanks for your response.

> You usually don't want to retry and rather see if you can fix the flaky behavior

Regarding unit tests, I absolutely agree.
But for functional tests, it is not always the case. For example, the problems of a cloud testing platform could cause failure of tests. Moreover, if one has to support hundreds of functional tests, occasional failures could become a real pain.

Consider the most frequent problem I face in the production environment. I use a page object which encapsulates some setup actions. 

The suite will be like:

./suite.spec.js
```
describe('user opens the page', () => {
     let page;
     beforeEach(() => {
         page = new Page();
         page.open('http://test.com');
     });
     it('will have a title', () => {
          expect(title).to.equal('something');
     });
     describe('user submits the form', () => {
         beforeEach(() => {
              page.submitForm();
         })
         // some assertions
     })
     describe('user clicks the button', () => {
          beforeEach(() => {
               page.clickButton();
          });
          // some assertions
     });
});
```

The whole suite will fail If the first hook, where we initialize the page object, will return an error (e.g network timeout in the browser, a problem with selenium session etc.). In this case, not only the code defines the result of the test, but also testing infrastructure.

> You can also set retries always via a global environment variable, e.g. in your wdio.conf. I don't see how an extra config property is useful here.

I don't suggest to add a global variable and use it everywhere in a code. Adding retries to each hook is tedious.

> I don't know if it is a good idea to allow setting retries globally.

@christian-bromann what potential problems do you see?

**Comment by shackijj** [comment]
> If you run WebdriverIO there is no such thing like a Selenium session. WebdriverIO is an own implementation of the WebDriver spec, so you might be referring to a WebDriver session here.

You're right.

> Why? I think you can overwrite the Mocha hooks so that you automatically apply a retry mechanism to it. Also Mocha has an integrated retry functionality that you can set up in your mochaOpts.

Unfortunately, Mocha doesn't retry hooks. It retires only suites and tests. wdio-sync package allows retrying hooks of frameworks. It's the main reason why I suggest the feature here.

> Making it a configuration option suggests the user it is ok to just retry when things fail which is not ok imo and should not be the default.

I could mention that in the docs, as like [http://webdriver.io/guide/testrunner/retry.html](here)
