### ISSUE TITLE
Is the hooks in wdio conf file runs async

### ISSUE THREAD

**Issue by NaveenThiyagarajan** [webdriverio/webdriverio#3074]
Hi Guys, I have the code to take screenshot in the afterStep if the step fails in cucumber framework 

From the logs i can see the `screenShot` api call to `selenium server` triggered as part of `afterStep` ... but the problem is `DELETE` session call is triggered before getting the response for `screenshot` call ...

Because of this behavior the allure-reports are not showing screenShots for some cases of mine ...

The question i have is:  Is this expected for afterStep to run async .. if yes .. how to make it sync..

This is the code i have in afterStep:
```
   afterStep: async function (myStepResult) {
        if (myStepResult.status === 'failed') {
            const path = './reports/'+Date.now()+'.png';
            await browser.saveScreenshot(path);
            console.log("Step status: "+ myStepResult.status);
        }
    },
```

**Environment:**
 - **WebdriverIO version:** 4.14.0
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version: 8.6.0
 - **NPM version:** 5.4.2
 - **Browser name and version:** chrome 70
 - **Platform name and version:** mac 10.13.3

Logs:
![image](https://user-images.githubusercontent.com/26540915/49020031-75a62f00-f1b5-11e8-9c78-4e23244fd1fb.png)

**Comment by christian-bromann** [comment]
Hooks automatically run every command in sync mode if you have it enabled, try:
```js
   afterStep: function (myStepResult) {
        if (myStepResult.status === 'failed') {
            const path = './reports/'+Date.now()+'.png';
            browser.saveScreenshot(path);
            console.log("Step status: "+ myStepResult.status);
        }
    },
```

**Comment by NaveenThiyagarajan** [comment]
hi @christian-bromann .. initially i tried as mentioned by you. It did not worked. That is why i added `async await` to see whether it makes any difference.

**Comment by christian-bromann** [comment]
@NaveenThiyagarajan if all other commands run synchronous , this should work too

**Comment by NaveenThiyagarajan** [comment]
Ok.. may be is it like we are triggering `afterStep` and `DELETE` call(might be from onComplete hook) 
 asynchronously  when there are failures ... sorry .. this is not working for me ... :( so trying to find out what mistake i am doing ... may be i can create some sample project for you to reproduce ..
