### ISSUE TITLE
Setting Text Not Working Properly on Firefox

### ISSUE THREAD

**Issue by joshgrantsauce** [webdriverio/webdriverio#3078]
**Environment:**
 - **WebdriverIO version:** 4.10.0
 - **Mode:** WDIO Testrunner, sync
 - **Node.js version**: 8.10.0
 - **Yarn version:** 1.5.1
 - **Browser name and version:** Firefox 57.0 and 59.0
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** wdio/spec reporter, wdio-sauce-service

**Config of WebdriverIO**
```
exports.config = {
    
    user: process.env.SAUCE_USERNAME,
    key: process.env.SAUCE_ACCESS_KEY,
    
    specs: [
	    './tests/**/*.js'
    ],
    
    capabilities: [
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instance available you can make sure that not more than
        // 5 instance gets started at a time.
        //maxInstances: 5,
        //
      {browserName: 'firefox', 
       platform: 'Windows 10', 
       version: '57.0',
       seleniumVersion: "3.4.0"
      }
    ],
    
    sync: true,
    logLevel: 'error',
    coloredLogs: true,
    screenshotPath: './errorShots/',
    baseUrl: 'http://the-internet.herokuapp.com',
   
    waitforTimeout: 10000,
   
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    services: ['sauce'],
    framework: 'mocha',
    reporters: ['dot'],
    reporterOptions: {
        outputDir: './'
    },

    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    }
}
```

**Describe the bug**
Setting text on input fields, using either regular text strings or a Tab key, is not working properly. The text is not getting set as expected and left blank. The test also hangs for an unusual amount of time before finishing.

**To Reproduce**

```
var expect = require('chai').expect;
describe('the hanging test problem', function() {
	
	it('should enter a tab key', function() {
		browser.url('http://the-internet.herokuapp.com/login')
		var elem = browser.element('#username');
		elem.keys('hello');
		elem.keys('Tab');
	});
});
```

**Expected behavior**
The page is visited and the text in the username field is set.

**Log**
Selenium log from Sauce - https://gist.github.com/joshgrantsauce/e138d5201a62f761913ecddea1cc7ad9

**Comment by joshgrantsauce** [comment]
Just tried this with wdio version 4.14.0 and it appears to be fixed. Perhaps it's still interesting though :)

**Comment by christian-bromann** [comment]
@joshgrantsauce please use `setValue` to set text in an element. `keys` has been deprecated but we implemented some sort of workaround.

**Comment by joshgrantsauce** [comment]
@christian-bromann what is the workaround? Is there a doc or example somewhere?

**Comment by christian-bromann** [comment]
> @christian-bromann what is the workaround?

To set values for input elements please use setValue. `keys` is for triggering a keyboard action on non focused elements (e.g. pressing key to submit forms).
