### ISSUE TITLE
How is wdio-cli packaged with the webdriverio package?

### ISSUE THREAD

**Issue by naddison** [webdriverio/webdriverio#3083]
When I npm install webdriverio that package contains the wdio-cli compiled code and binary, but when I look inside this repository it is its own module. I cannot find any packaging logic which merges/combines the wdio-cli package and webdriverio package before publishing.

**Comment by christian-bromann** [comment]
@naddison if you npm install webdriverio you get v4 which you can find here: https://github.com/webdriverio/webdriverio/tree/v4. The current master is v5 which is already in beta and will be released soon. See http://beta.webdriver.io

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
