### ISSUE TITLE
When does the before hook get executed?

### ISSUE THREAD

**Issue by naddison** [webdriverio/webdriverio#3089]
I am interested to know when the the **before** hooks get called when using the WDIO Test Runner, is it run inside before control is passed to the underlying framework adapter (like wdio-jasmine-framework) or is it run in the wdio-cli launcher code?

```javascript
/**
     * Gets executed before test execution begins. At this point you can access to all global
     * variables like `browser`. It is the perfect place to define custom commands.
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     */
    before: function() {
      ...code here...
    },
```

**Comment by christian-bromann** [comment]
> or is it run in the wdio-cli launcher code?

It is run after the framework was initialised but before it is being run.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
