### ISSUE TITLE
webdriver sent a DELETE after the POST command to click and app terminated

### ISSUE THREAD

**Issue by LayMuiToh** [webdriverio/webdriverio#3093]
**Environment (please complete the following information):**
WebDriverio version
 -node_modules/.bin/wdio --version
v4.14.0
Mode:WDIO Testrunner
 sync
node --version
v9.1.0
npm --version
6.4.1
Platform: iOS 12.1
 - **Platform name and version:** [e.g. Windows 10]

 capabilities: [{
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        browserName: '',
        appiumVersion: '1.9.1',
        platformVersion: '12.1',
        platformName: 'iOS',
        deviceName: 'Lay muis iPhone',
	    udid: 'xxxxx,
        app: '/Users/xxxxi/Desktop/xxx/xxx.ipa',
        bundleId: 'xxx',
       // xcodeOrgId: 'iPhone Developer',
       // xcodeSigningId: 'R3Q5NQ5RLG',
       // updatedWDABundleId: 'com.apple.test.WebDriverAgentRunner-Runner',
        //wdaConnectionTimeout: 1000,
        //useCarthageSsl: true,
        //useNewWDA: true,
        //appPackage: 'com.ios.pa',             // Package name of the app
        //appActivity: 'com.ios.pa', // App activity of the app
        automationName: 'XCUITests',
        noReset: true,
      //  printPageSourceOnFindFailure: true,
        //launchTimeout: 20000
        //autoLaunch: true,
        newCommandTimeout: 1000
       *Config of WebdriverIO**

 sync: true,
    //
    // Level of logging verbosity: silent | verbose | command | data | result | error
    logLevel: 'verbose',
    //
    // Enables colors for log output.
    coloredLogs: true,
    //
    // Warns when a deprecated command is used
    deprecationWarnings: true,
    //
    // If you only want to run your tests until a specific amount of tests have failed use
    // bail (default is 0 - don't bail, run all tests).
    bail: 0,
    //
    // Saves a screenshot to a given path if a command fails.
    screenshotPath: './errorShots/',
    //
    // Set a base URL in order to shorten url command calls. If your `url` parameter starts
    // with `/`, the base url gets prepended, not including the path portion of your baseUrl.
    // If your `url` parameter starts without a scheme or `/` (like `some/path`), the base url
    // gets prepended directly.
    //baseUrl: 'http://localhost',
    //
    // Default timeout for all waitFor* commands.
    waitforTimeout: 10000,
    //
    // Default timeout in milliseconds for request
    // if Selenium Grid doesn't send response
    connectionRetryTimeout: 90000,
    //
    // Default request retries count
    connectionRetryCount: 3,
    //
    // Initialize the browser instance with a WebdriverIO plugin. The object should have the
    // plugin name as key and the desired plugin options as properties. Make sure you have
    // the plugin installed before running any tests. The following plugins are currently
    // available:
    // WebdriverCSS: https://github.com/webdriverio/webdrivercss
    // WebdriverRTC: https://github.com/webdriverio/webdriverrtc
    // Browserevent: https://github.com/webdriverio/browserevent
    // plugins: {
    //     webdrivercss: {
    //         screenshotRoot: 'my-shots',
    //         failedComparisonsRoot: 'diffs',
    //         misMatchTolerance: 0.05,
    //         screenWidth: [320,480,640,1024]
    //     },
    //     webdriverrtc: {},
    //     browserevent: {}
    // },
    //
    // Test runner services
    // Services take over a specific job you don't want to take care of. They enhance
    // your test setup with almost no effort. Unlike plugins, they don't add new
    // commands. Instead, they hook themselves up into the test process.

    services: ['appium'],

    appium: {
        args: {
            address: '127.0.0.1',
            commandTimeout: '11000',
            sessionOverride: true,
            debugLogSpacing: true,
            platformVersion: '12.1',
            platformName: 'iOS',
            showIosLog: true,
            deviceName: 'iPhone 6s',
            nativeInstrumentsLib: true,
         //   isolateSimDevice: true,
            app: '/xxx/xx.ipa',
        },
    },

When running the xcodebuild

WebDriverAgentRunner failed
Test session results and logs:
	/Users/tohlaymui/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2018.12.04_15-32-42-+0800.xcresult

2018-12-04 15:33:04.569 xcodebuild[11200:66823] [MT] IDETestOperationsObserverDebug: 21.157 elapsed -- Testing started completed.
2018-12-04 15:33:04.569 xcodebuild[11200:66823] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2018-12-04 15:33:04.569 xcodebuild[11200:66823] [MT] IDETestOperationsObserverDebug: 21.157 sec, +21.157 sec -- end
Failing tests:
	-[UITestingUITests testRunner]
** TEST FAILED **

Also the steps in this url https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md didn't mention if I need to build IntegrationApp, IntegrationTests_1, IntegrationTests_2, IntegrationTests_3 which are seen the in WebDriverAgent.xcode.proj
Do I need install IntegrationApp or simply WebDriverAgentRunner

In the xcode, I select WebDriverAgentRunner -> iphone (the real device to run on)
Go to Product -> Test to install the WebDriverAgentRunner on the device
Go To Window -> Devices and Simulators, the installed App is WebDriverAgentRunner-Runner with identifier: com.apple.test.WebDriverAgentRunner-Runner

with appium server started, run the test using 
node_modules/.bin/wdio
but app terminate instead of go to the next page after sign-in click
 [15:45:20]  DATA		{"using":"accessibility id","value":"signin"}
[15:45:21]  RESULT		{"ELEMENT":"30000000-0000-0000-080F-000000000000"}
[15:45:21]  COMMAND	POST 	 "/wd/hub/session/11b7c7df-9fa3-4321-9e82-0b4201db6f00/element/30000000-0000-0000-080F-000000000000/click"
[15:45:21]  DATA		{}
․[15:45:21]  COMMAND	DELETE 	 "/wd/hub/session/11b7c7df-9fa3-4321-9e82-0b4201db6f00"
[15:45:21]  DATA		{}

1 passing (24.30s)

Here is my test code:describe('Login Test', function () {
    beforeEach(() => {
        Login.open();
       
    });

    it('should not login with a invalid email ID', function () {
      Login.username.setValue('all.access@dev.telepathy.ai');
      Login.password.setValue('Tonu6710!');
      if (browser.isKeyboardShown()) {
        browser.hideDeviceKeyboard();
      }
      Login.submit();
    });

wonder where does the DELETE command comes from?
this cause the app to terminate instead of continue to the next page.

**Comment by christian-bromann** [comment]
> Do I need install IntegrationApp or simply WebDriverAgentRunner

You just need to install Appium, this is it.

> wonder where does the DELETE command comes from?

When the test has finished, WebdriverIO closes the session with that DELETE command.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
