### ISSUE TITLE
[iOS, Appium] Closing and reopening application within the same session

### ISSUE THREAD

**Issue by sanyco92** [webdriverio/webdriverio#3096]
Hello everyone! I'm trying to write some test for the iOS application (iOS 12) using Appium. The question is the following: is there any way to close the app and reopen it within the same session (without losing it)?

The test is like this:
1) Start an appium session -> application opened -> some steps performed.
2) Close the application
3) Reopen the same application (without losing the session)
4) Continue performing other steps.

Tried to execute browser.closeApp(), but then I can't open the same app because the session doesn't exist anymore.

**Comment by christian-bromann** [comment]
> Tried to execute browser.closeApp()

That should do the trick. 

> the session doesn't exist anymore.

That should not happen.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by alexandrubradfortech** [comment]
+1
