### ISSUE TITLE
Add the ability to refetch an entire element chain to v5

### ISSUE THREAD

**Issue by abjerstedt** [webdriverio/webdriverio#3097]
**Is your feature request related to a problem? Please describe.**
I would like to add the ability to v5 for wdio to refetch an element via refetching the whole chain. 
Currently Given:
$('a').$('b').$('c')
If 'a' or 'b' fall stale, the system will try to fetch 'c', but it will never be successful as it is scoped to an element that is no longer in the DOM (and therefore the rest of the chain is stale).

**Describe the solution you'd like**
I will be adding something similar to the following code.
```
export default function refetch () {
    let currentElement = this;

    // Generate selector array
    let selectors = [];
    do {
        selectors.push(currentElement.selector);
        currentElement = currentElement.parent || {};
    } while (currentElement.elementId);
    // Iterator is currently set to Browser
    selectors.reverse();

    // Chain elements through the array
    return selectors.reduce( (elementPromise, selector) =>
        elementPromise.then((element) => element.$(selector)), Promise.resolve(currentElement));
}
```

**Comment by abjerstedt** [comment]
@christian-bromann The question is whether i add this as an element command, and have the middleware call it (so it can be adhoc invoked by the wdio consumer); or just to the middleware. 
I propose the first.

**Comment by christian-bromann** [comment]
> The question is whether i add this as an element command, and have the middleware call it (so it can be adhoc invoked by the wdio consumer); or just to the middleware.

I would suggest to do it only in the middleware because the wdio user doesn't know that an element might has become stale and why to ask the user to call an extra command if we can hide this internally.
