### ISSUE TITLE
Iframe doesn't work on firefox while works on chrome? get "Error: data did not match any variant of untagged enum FrameId at line 1 column 21"

### ISSUE THREAD

**Issue by DonnaZhang** [webdriverio/webdriverio#3100]
** questions**

Why iframe doesn't work on firefox while works on chrome?
The following code works on chrome (options1) and not works on firefox(options2)

(node:27720) UnhandledPromiseRejectionWarning: Error: data did not match any variant of untagged enum FrameId at line 1 column 21

**code**
```
var webdriverio = require('webdriverio')
var co = require('co')
var options1 = {
    desiredCapabilities: {
        browserName: 'chrome'
    }
}

var options2 = {
    desiredCapabilities: {
        browserName: 'firefox'
    }
}

function main() {
    co(function* () {
        let mainBrowser = webdriverio
            .remote(options1)
            .init()
            .url('https://www.w3schools.com/TAgs/tryit.asp?filename=tryhtml_button_test')
            .catch(function (err) {
                console.log(err)
            })
            yield mainBrowser.waitForExist('iframe[name="iframeResult"]',50000)
            var frameid = yield mainBrowser.getAttribute('iframe[name="iframeResult"]', 'id')
            console.log("########id:" + frameid)
            yield mainBrowser.frame(frameid);
            yield mainBrowser.click('[type="button"]')
        })}
        main()
```

**Environment (please complete the following information):**
Package
```
{
  "name": "webdriverTest",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "start": "node test.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {},
  "dependencies": {
    "Q": "^1.0.0",
    "co": "^4.6.0",
    "webdriverio": "^4.14.0"
  }
}
```

 - **WebdriverIO version:** "^4.14.0"
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **Node.js version: [e.g. v10.8.0]
 - **NPM version:** [e.g. 6.2.0]
 - **Browser name and version:** [e.g. FireFox version 62.0(64-bit) ]
[Google Chrome | 70.0.3538.102 (Official Build) (64-bit)] 
 - **Platform name and version:** [e.g. Mac OS X]

**Comment by christian-bromann** [comment]
This code you provided can't work as you are mixing synchronous with asynchronous code. Please use one of the [boilerplate](http://webdriver.io/guide/getstarted/boilerplate.html) code samples to get up and running.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
