### ISSUE TITLE
master is missing the libs folder which is breaking links on webdriverio.io

### ISSUE THREAD

**Issue by HairyMaclary** [webdriverio/webdriverio#3103]
**Pre-check**
- [y] I'm aware that I can [edit the docs]

**Describe the improvement**

I'd like to report
- [ ] Other: links to documentation not working from http://webdriver.io/

**Description of the improvement / report**
1. Navigate to a command on http://webdriver.io/. E.g. leftClick: http://webdriver.io/api/action/leftClick.html

2. Click on either of these buttons: "Improve this doc" or "View Source". For example clicking on "View Source" for leftClick() will send you to: 
https://github.com/webdriverio/webdriverio/blob/master/lib/commands/leftClick.js

3. You are then directed to a broken link message. 

4. It appears that the link is following the github directory structure. Specifically it is looking for the libs folder in master. However, unlike other branches, master does not have a libs folder.

**Comment by christian-bromann** [comment]
@HairyMaclary we are currently transitioning from v4 to v5. The new docs page is at http://beta.webdriver.io and once we released v5 and the docs page all links will work.
