### ISSUE TITLE
Process silently fails if local runner isn't installed

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#3104]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. v5]
 - **Mode:** [WDIO Testrunner]
 - **running sync
 - **Node.js version: [e.g. 8.9.1]
 - **NPM version:** [e.g. 5.8.0]
 - **Browser name and version:** [e.g. Chrome 68]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
If the wdio runner isn't installed, the test fails without error message.

**Comment by abjerstedt** [comment]
We should just make this a dependency of webdriver.

**Comment by christian-bromann** [comment]
I think it is fine to make the local runner a dependency of `@wdio/cli` as long as there is no second runner (e.g. lambda runner) available.

**Comment by SivanMehta** [comment]
@christian-bromann I can reproduce this issue **with** `wdio-local-runner`


WebdriverIO version: `5.0.0-beta.15`
Mode: `mocha` test runner
- running sync
- Node.js version: 8.9.4
- NPM version: 6.4.1

Browser name and version: never gets to browser, just exits before browser launches
Platform name and version: MacOSX High Sierra
Additional `wdio` packages used (if applicable):

```json
    "@wdio/cli": "^5.0.0-beta.15",
    "wdio-local-runner": "^5.0.0-beta.3",
    "wdio-mocha-framework": "^0.5.13",
    "wdio-selenium-standalone-service": "0.0.10",
    "wdio-spec-reporter": "^0.1.5",
    "webdriverio": "^5.0.0-beta.15"
```

When digging down with `ndb`, this error is being thrown

```
You can't reassign a plugin after appling another plugin"
```

on [this line](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-config/src/utils.js#L75-L84)

**Comment by christian-bromann** [comment]
```

**Comment by abjerstedt** [comment]
@SivanMehta All INTERNAL wdio packages (except webdriverio and webdriver) are under the @wdio namespace now.
@wdio/local-runner
@wdio/mocha-framework
etc

**Comment by SivanMehta** [comment]
Thanks guys that resolved _my_ issues. Now I just have wrestle with the API differences in `wdio@5`

**Comment by abjerstedt** [comment]
@SivanMehta https://github.com/webdriverio/webdriverio/blob/master/CHANGELOG.md

**Comment by christian-bromann** [comment]
Closing this then.
