### ISSUE TITLE
Button down, moveToObject, buttonUp does not work

### ISSUE THREAD

**Issue by liuallen1981** [webdriverio/webdriverio#3107]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [4.12.0]
 - **Mode:** [Mocha test runner]
 - **Node.js version: [10.9.0]
 - **NPM version:** [ 6.4.1]
 - **Browser name and version:** [Chrome]
 - **Platform name and version:** [MacOS High Sierra]

**Describe the bug**
Below code does not do the button down, drag, button up action.  I don't see any mouse cursor moving while the test is running. 
In the console, I only see warming message and no error: 
(You can disable this warning by setting `"deprecationWarnings": false` in your WebdriverIO config)
[18:20:37]  DATA		{"element":"0.29001278854466617-1","xoffset":5,"yoffset":100}
[18:20:37]  DATA		{"using":"css selector","value":"img"}
WARNING: the "moveTo" command will be deprecated soon. If you have further questions, reach out in the WebdriverIO Gitter support channel (https://gitter.im/webdriverio/webdriverio).
Note: This command is not part of the W3C WebDriver spec and won't be supported in future versions of the driver. It is recommended to use the actions command to emulate pointer events.

(You can disable this warning by setting `"deprecationWarnings": false` in your WebdriverIO config)
[18:20:37]  DATA		{"element":"0.29001278854466617-1","xoffset":-15,"yoffset":100}
WARNING: the "buttonUp" command will be deprecated soon. If you have further questions, reach out in the WebdriverIO Gitter support channel (https://gitter.im/webdriverio/webdriverio).
Note: This command is not part of the W3C WebDriver spec and won't be supported in future versions of the driver. It is recommended to use the action command as a replacement for this.

`
      
       browser.leftClick('img');

        const viewWidth =  browser.getElementSize('img', 'width');

        browser.moveToObject('img', viewWidth, 100);

        browser.buttonDown(0);

        for(let i = 0; i < 30; i++){

            browser.pause(100);

            browser.moveToObject('img', viewWidth - i * 10, 100);

        }
        browser.buttonUp(0);`

Is there something wrong with the code? Or do I need to do any configuration for it to work?

**Expected behavior**
I am expecting the above code would do the button down, drag and button up on the 'img' selected.

**Log**
No error as shown in the console log above

**Additional context**

> Please use the correct markdown

**Comment by abjerstedt** [comment]
This is not going to do what you think it does. Move to object doesn't move the actual cursor, it basically pretend focuses on an element.

**Comment by liuallen1981** [comment]
@abjerstedt  do you have an example that would do the button down, drag, button up ? I can't seem to find any working example online.

**Comment by erwinheitzman** [comment]
@liuallen1981 the dragAndDrop command or actions command is used for this.
Keep in mind that the actions command isn't fully supported yet and that the dragAndDrop command doesn't work with all implementations due to a limitation of Selenium.

**Comment by liuallen1981** [comment]
@erwinheitzman I also tried dragAndDrop 
browser.dragAndDrop('img', '.layout-panel-header');  
and it seems like it's doing ButtonDown, moveTo, ButtonUp internally when I check the console log which doesn't seem to work for me. 
Do you have an example of actions command that I can try? I can't seem to find any example online.

**Comment by raketenolli** [comment]
It should work. Try it locally and do not touch the mouse while the test is executing. You should be able to witness the intended behavior. What you will not see is a mouse cursor moving around, only the effects of the mouse being clicked and moved.

**Comment by liuallen1981** [comment]
@raketenolli is there something wrong with my code, see my first post. I ran it many times without touching the mouse while the test is executing but I still don't see any effects of the mouse being clicked or moved. Does the version of the selenium, webdriverio, test runner matter? How about the UI framework? I use my company's internal UI framework which is based on foundation framework.

**Comment by raketenolli** [comment]
@liuallen1981 I don't know the website or your UI framework, so it's hard to guess what should be happening. One problem might be that your `moveToObject` selector is the object which is being dragged itself.

**Comment by allentsliu** [comment]
@raketenolli do you know if there is a way to draw a line on the selected object (img). It might be what you pointed out that the moveToObject just drag the selected object which is not what I want. But I am not quite sure how to check it.

**Comment by liuallen1981** [comment]
I have tried using action 
`        browser.actions([{
            "type": "pointer",
            "id": "src",
            "actions": [
                {"type": "pointerMove", "duration": 0, "x": viewWidth, "y": 100},
                {"type": "pointerDown", "button": 0},
                {"type": "pause", "duration": 500},
                {"type": "pointerMove", "duration": 1000, "origin": "pointer", "x": -50, "y": 0},
                {"type": "pointerUp", "button": 0}
            ]
        }]);`

and I got this error: unimplemented command: session/ec1238bbc0567d5e1a49bf89d9cd8f46/actions

Is there an alternative solution?

**Comment by christian-bromann** [comment]
> and I got this error: unimplemented command

actions API doesn't work in Chrome yet, just fyi.

**Comment by christian-bromann** [comment]
Please file an issue in https://github.com/webdriverio-boneyard/v4 .. I don't see how this is related to v5
