### ISSUE TITLE
Report all failed expectations, not just first

### ISSUE THREAD

**Issue by GCHQDeveloper911** [webdriverio/webdriverio#3125]
If I have a test:

describe('my suite', () => {
it ('tests something', () => {
expect(1).toEqual(2);
expect(2).toEqual(3);
console.log('oh dear');
})
})

Then obviously this fails - but only the "1=2" expectation is reported. It would be good to see all failed expectations. The test IS running through, because I see my console log output.

**Comment by christian-bromann** [comment]
> It would be good to see all failed expectations.

Not sure which framework you are using here, I am guessing it is Jasmine. This is a behavior that Jasmine has implemented and if you want to change it you need to make a feature request there. WebdriverIO can't detect the second failure.

**Comment by GCHQDeveloper911** [comment]
Hi Christian,
You guessed correctly - we're using Jasmine. I've been able to modify:

webdriverio/build/lib/utils/ReporterStats.js (4.14)
webdriverio/build/lib/utils/BaseReporter.js (4.14)
wdio-jasmine-framework/build/reporter.js (0.3.8)

to provide the functionality I was describing - with additional changes to wdio-spec-reporter (0.1.5) by way of an example reporter to display this "expanded" output. 

Obviously I can see you are currently in the middle of a fairly major rewrite for v5. Shall I create a PR against 4.14 (with 0.3.8 and 0.1.5 as above) for my changes for you to try out?

**Comment by christian-bromann** [comment]
> Shall I create a PR against 4.14 (with 0.3.8 and 0.1.5 as above) for my changes for you to try out?

Yes please, we still support v4 but don't do any active development on it due to the work in v5. So it would be amazing if the changes can be applied to both code bases.

**Comment by abjerstedt** [comment]
@GCHQDeveloper911 An assertion is simply a method that compares something, and ft it fails, throws an exception. An it() block is simply a reporting block of code that has a try catch, and if it catches something - flags the block as failed. You are asking to completely change the expected behavior of a well established framework to fit bad functional test writing practice. 

You are supposed to create an individual it() per assertion... and use nested describes to organize them.

@christian-bromann I recommend against adding this to the repo.

**Comment by christian-bromann** [comment]
> and if it fails, throws an exception

That how it works in Mocha. In Jasmine the test continues which is why this actually is a well point made by @GCHQDeveloper911 

> @christian-bromann I recommend against adding this to the repo.

I still like to see the changes to see what the fix will bring.

**Comment by abjerstedt** [comment]
I talked to christian outside of this, and he set me straight. I'm thinking in a mocha context.

**Comment by GCHQDeveloper911** [comment]
Hi Christian, I've submitted PRs for wdio-spec-reporter and wdio-jasmine-framework. For webdriverio changes themselves, I wasn't so sure what to do. On my fork I have created a 4.14.2 branch and the changes are in there - but can you advise what you want me to do to submit a request for master - from what I can see both 4.x and 5.x are all on master, just tagged? Thanks!
