### ISSUE TITLE
Add the ability to send custom error messages to wait commands.

### ISSUE THREAD

**Issue by StephenABoyd** [webdriverio/webdriverio#3127]
**Is your feature request related to a problem? Please describe.**
I would like to add the ability to pass custom error messages to the ```wait``` commands. So instead of ```element still not visible after 10000ms```, we could have something like ```That option never appeared in the dropdown```

**Describe the solution you'd like**
With v5 I would recommend something like this:

```
export default async function waitForDisplayed (ms, error = '', reverse = false) {

    if (!this.elementId && !reverse) {
        await this.waitForExist(ms)
    }


    if (typeof ms !== 'number') {
        ms = this.options.waitforTimeout
    }

    const isReversed = reverse ? '' : 'not '
    const errorMsg = error !== '' ? error : `element ("${this.selector}") still ${isReversed}displayed after ${ms}ms`

    return this.waitUntil(async () => {
        const isVisible = await this.isElementDisplayed(this.elementId)

        return isVisible !== reverse
    }, ms, errorMsg)
}
``` 

**Describe alternatives you've considered**
I've tried to find a way to do this in my project, but I could not figure out a way to do it.

**Comment by abjerstedt** [comment]
Personally,  I'd rather put the message at the end if we do this. I find a negative check more useful than this,  and don't want to have to fill in an extra undefined for every negative test.

**Comment by StephenABoyd** [comment]
Yeah I wouldn't mind adding false to the parameters for the custom messages.

**Comment by christian-bromann** [comment]
@StephenABoyd feel free to provide a PR with this enhancement

**Comment by abjerstedt** [comment]
This issue has been resolved by https://github.com/webdriverio/webdriverio/pull/3128
