### ISSUE TITLE
Question about API getAttribute 

### ISSUE THREAD

**Issue by TE-jp12973** [webdriverio/webdriverio#3129]
**Pre-check**
- [ ] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [x] Unclear documentation
- [ ] A typo
- [ ] Missing documentation
- [ ] Other

**Description of the improvement / report**
API getAttribute()
### Example
```
<form action="/submit" method="post" class="loginForm">
    <input type="text" name="name" placeholder="username"></input>
    <input type="text" name="password" placeholder="password"></input>
    <input type="submit" name="submit" value="submit"></input>
</form>
````
### getAttribute\.js
```
it('should demonstrate the getAttribute command', function () {
    var form = $('form')

    var attr = form.getAttribute('method')
    console.log(attr) // outputs: "post"
    // or
    console.log(browser.getAttribute('form', 'method')) // outputs: "post"

    // if your selector matches multiple elements it returns an array of results
    var allInputs = $$('.loginForm input')
    console.log(allInputs.map(function(el) { return el.getAttribute('name'); })) // outputs: ['name', 'password', 'submit']
})
```
**What if ther are many `form` ?**

**Comment by christian-bromann** [comment]
Like in jQuery or with `document.querySelector` it will fetch the first element it can find. To find the other form you need to either provide a better selector or do `$$('form')[1]`.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
