### ISSUE TITLE
Headless Chrome causing tests to fail?

### ISSUE THREAD

**Issue by kkjdaniel** [webdriverio/webdriverio#3130]
I have written a number of tests that successfully pass when running through the Chrome Driver normally, however if running with Headless Chrome, all of the tests fail. As they cannot find the element and instead timeout. I have tried passing the `window-size` argument, but that didn't resolve the issue.

```
capabilities: [{
    browserName: 'chrome',
    chromeOptions: {
      args: ['--headless', '--disable-gpu', '--window-size=1920,1080'],
    }
  }],
```

The error thrown by Jasmine...

`An element could not be located on the page using the given search parameters.`

 - **WebdriverIO version:** 4.14.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v8.11.2
 - **NPM version:** 5.6.0
 - **Browser name and version:** Chrome 66
 - **Platform name and version:** Windows 7
 - **Additional wdio packages used (if applicable):** wdio-jasmine-framework

**Comment by abjerstedt** [comment]
@kkjdaniel - As a heads up, you are using a driver that is 6 versions behind. ChromeDriver 2.39 only supports Supports Chrome v66-68 and production chrome is 71.

But more importantly, you need to give more details. Are you running this headless version locally? Are you running it on the grid? Are you running it on a docker container? 

Thats a very generic error.

**Comment by kkjdaniel** [comment]
You're right about the outdated versions, unfortunately, I am in a sort of slightly locked down enviroment. Which means Chrome was pinned at v66. Which required the use of the older Chrome Driver. I will probably upgrade this if it proves to be an issue. However, as far as I'm aware support for Headless Chrome was introduced back in Chrome 59?

The environment is purely local at this stage. I have been using the Selenium Standalone Server.

I agree the error is very generic, which is part of the issue for myself in trying to get to the bottom of it. Apologies! It appears to be related to any commands checking or awaiting the visibility of any selected elements.

Thanks!

**Comment by christian-bromann** [comment]
I think we can close this. I can't identify an issue with WebdriverIO here.

**Comment by CharuDattPimple** [comment]
I am facing the same issue and above solution does not solve my problem.

 config file ====>
    browserName: 'chrome',
              maxInstances: '5',
              'goog:chromeOptions': {
                      // run in headless mode
                      args: ['headless', 'disable-gpu','--no-sandbox'],
                    },}],  

chrome version:72.0.3626.119

**Comment by mgrybyk** [comment]
@CharuDattPimple without any logs it is impossible to say what is going wrong.
I'd recommend to capture as much logs as possible, quite often at this point it is clear enough what is going wrong. 
Also, running chrome in headless depends on the environment, are you running it in docker?

Here is my config:
```
'goog:chromeOptions': {
  args: ['--headless', '--no-sandbox', '--disable-gpu', '--disable-dev-shm-usage', '--window-size=1920,1080']
}
```

**Comment by CharuDattPimple** [comment]
Although its working , I am able to set values in field but unable to perform operation (click ).And finally it throws timeout error . 
When I checked screenshot its shows UI in blurred state and the button I am going to perform an operation is disabled.(Which is not happening when I am running the cases in normal mode )

**Comment by christian-bromann** [comment]
@CharuDattPimple it is impossible to help you here. I recommend to use the debugging capabilities of WebdriverIO to fiddle around with the browser. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have further questions.

**Comment by stsvilik** [comment]
@CharuDattPimple it just might be that w/ `--disable-gpu` certain transitions take longer to render, have you tried waiting for few milliseconds longer or until subject element is present?

**Comment by afsarali273** [comment]
https://github.com/webdriverio/webdriverio/issues/3130#issuecomment-508385388 solved my issue.

**Comment by nit0s** [comment]
hey all, I was facing this issue as well I notice this got solved once I used `'--no-sandbox'` along with `--headless' '--disable-gpu'` this can helps

**Comment by excise-notable44** [comment]
@Acksakal https://stackdev.space/questions/when-a-test-fails-the-browser-will-not-automatically-close
