### ISSUE TITLE
How to send Selenium commands?

### ISSUE THREAD

**Issue by SeanHayes** [webdriverio/webdriverio#3131]
I'm trying to enable downloads in headless Chrome and some posts online indicated I should do the following:

        const command = require('selenium-webdriver/lib/command');

        const cmd = new command.Command("SEND_COMMAND")
        .setParameter("cmd", "Page.setDownloadBehavior")
        .setParameter("params", {'behavior': 'allow', 'downloadPath': process.env.DOWNLOAD_DIR});
        driver.getExecutor().defineCommand("SEND_COMMAND", "POST", `/session/${browser.sessionId}/chromium/send_command`);
        return driver.execute(cmd);

How do I access the driver and executor in wdio?

**Environment (please complete the following information):**
 - **WebdriverIO version:** 4.14.0
 - **Mode:** Standalone mode
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version: 10.14.2
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome
 - **Platform name and version:** Debian 4
 - **Additional wdio packages used (if applicable):** wdio-jasmine-framework, wdio-selenium-standalone-service

**Comment by abjerstedt** [comment]
Selenium-webdriver has nothing to do with wdio.

**Comment by christian-bromann** [comment]
see #3135

**Comment by UsharaniA** [comment]
@SeanHayes 
Is this issue fixed , am  trying to download a file in headless mode  and this is my setup

const wdioConfig = require('./wdio.conf.js');

wdioConfig.config.capabilities = [{
    //maxInstances: 1,
        browserName: 'chrome',
        chromedriverVersion: '2.43',
        chromeOptions: {
           
            args: ['--headless', '--disable-gpu', '--window-size=1366,768'],
            prefs: {    
               // 'download.default_directory': $'C:\\Users\\n276546\\Downloads',
                'download.prompt_for_download':"false",
                'download.directory_upgrade':"true",
                'Page.set_download_behavior': { 'behavior': 'allow', 'downloadPath': '${workspaceRoot}\\resource' },
              },
            // args: ['--headless', '--disable-gpu'],
                    
            // 'args': "['start-maximized']",
       
        }
    }];

wdioConfig.config.services =  ['selenium-standalone','chromedriver']
wdioConfig.config.seleniumLogs ='./Seleniumlogs'

exports.config = wdioConfig.config;

**Comment by UsharaniA** [comment]
I tired the above piece of code and the files are not donloading ,pls help

**Comment by SeanHayes** [comment]
I never got it working.

**Comment by dimaQA31** [comment]
having the same issue with webdriverIO 5 and Chrome driver 78
