### ISSUE TITLE
ERROR: jest is not defined

### ISSUE THREAD

**Issue by LayMuiToh** [webdriverio/webdriverio#3132]
**Environment (please complete the following information):**
 - **WebdriverIO version:** "^4.13.2"
 - **Mode:** : WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:**  : sync
 - **Node.js version: v9.1.0
 - **NPM version:** :6.4.1
 - **Browser name and version:** NA
 - **Platform name and version:** iOS 12.0
 - **Additional wdio packages used (if applicable):** : NA

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

package.json:
```
"scripts": {
    "test": "jest",
    "start": "babel-node index.js --presets es2015,stage-2"
  },
  "jest": {
    "preset": "react-native"
  },
```

my code snippet at Showcust.spec.js:jest.mock('react-native-sound');

```
function playAudio()
{
  const sound = new Sound('./testdata/audio/show_me_basf.wav', null, (error) => {
    if (error) {
      // do something
    }
  
    // play when loaded
    sound.play();
  });
  console.log('play wave file');
}
```

**Comment by christian-bromann** [comment]
Not sure how this is related to WebdriverIO at all.
