### ISSUE TITLE
Add the ability to add commands to the element prototype in v5

### ISSUE THREAD

**Issue by abjerstedt** [webdriverio/webdriverio#3134]
**Is your feature request related to a problem? Please describe.**
At the moment, v5 does not support adding commands to an element that get universally applied. You can either add a browser command, or you can add a command to the instance of an element.

This will likely be a serious regression for many people trying to upgrade from v4 to v5.

**Describe the solution you'd like**
I would like to see addCommand having an implementation that allows you to add the function universally to all element objects.

**Describe alternatives you've considered**

**Additional context**

**Comment by abjerstedt** [comment]
@webdriverio/technical-committee I'm thinking something like this:
*Add a new command called addElementCommand.
*Create an object (or array) in the browser object and attach all elementCommands to it (browser.elementCommands)
*Update the element generation to grab all functions attached to the above referenced object and attach them to the newly generated element.

**Comment by klamping** [comment]
I second this idea. There are definitely times when I'd like to add an element-generic command that's used throughout my tests. As a simple example, for visual regression testing, I could see myself creating a `takeScreenshot` command for a specific element. Something like:

```
$('#mySelector').takeScreenshot()
```

That would be trouble to have to add the command to every element created, versus it being available widely.

**Comment by christian-bromann** [comment]
This was implemented with #3271. I updated the docs here: https://webdriver.io/docs/customcommands.html

The current "issue" is that you need an element to register a custom command to it. Which kind of makes sense but is also problematic if you have a test suite and want to pre-register commands to the element prototype. This should be a different issue though.

@klamping it is implemented in a way that once you add a custom command to an element it is added to its prototype and all elements will have it.

**Comment by klamping** [comment]
Could probably do `$('body').addCommand(...)` in the before hook in wdio.conf.js. Would make a good YouTube video :)
