### ISSUE TITLE
ERROR: Cannot find module 'NativeModules'

### ISSUE THREAD

**Issue by LayMuiToh** [webdriverio/webdriverio#3136]
**Environment (please complete the following information):**
 - *./wdio --version
v4.14.0

Mode: WDIO Testrunner]

**If WDIO Testrunner, running sync/

**Node.js version:node --version
v9.1.0

**NPM version:npm --version
6.4.1

Browser name and version: NA (mobile native app) browser= "" in wdio.config.js

Platform name and version: macOS High Sierra 10.13.6

**Additional wdio packages used (if applicable):**NA

 
**Config of WebdriverIO**
 // Make sure you have the wdio adapter package for the specific framework installed
    // before running any tests.
    framework: 'mocha',
    //
    // Test reporter for stdout.
    // The only one supported by default is 'dot'
    // see also: http://webdriver.io/guide/reporters/dot.html
    // reporters: ['dot'],
    //
    // Options to be passed to Mocha.
    // See the full list at http://mochajs.org/
    mochaOpts: {
        ui: 'bdd',
        timeout:99999999,
 	    compilers: ['js:babel-register'],
    },

*Describe the bug**

**To Reproduce**

[Include code or an example repository that can easily be set up]
in my <test>.spec.js file, I import the react-native-sound module

import { Sound }  from 'react-native-sound';
function playAudio()
{}

module.exports = () => {
  describe('Voice input test at Main Page', function() {
    it('should able to speak show me basf and go to Main Page', function () {
      if(Main.mic.waitForExist()) {
        browser
        .touchAction('~f', 'longPress')
        .call(playAudio)
        .touchAction('~f', 'release');

**Comment by christian-bromann** [comment]
Not sure how this is related to WebdriverIO. Closing
