### ISSUE TITLE
npm install wdio-iedriver-service --save-dev is FAILING

### ISSUE THREAD

**Issue by gurunanakdevji** [webdriverio/webdriverio#3137]
Already running tests on Chrome and I urgently need to run my automation test on IE Browser, so I tried installing iedriver using "npm install wdio-iedriver-service --save-dev", but it failed with below error (mentioned error from both command line and log file). Please help.

COMMAND LINE ERROR DETAILS:

PS C:\NotBackedUp\WDF_Automation> npm install wdio-iedriver-service --save-dev
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/barretts/node-iedriver.git
npm ERR!
npm ERR! fatal: unable to access 'https://github.com/barretts/node-iedriver.git/': Could not resolve host: github.com
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\NotBackedUp\npm-cache\_logs\2018-12-17T06_42_41_480Z-debug.log
PS C:\NotBackedUp\WDF_Automation>

LOG FILE ERROR DETAILS:

20 verbose cwd C:\NotBackedUp\WDF_Automation
21 verbose Windows_NT 6.1.7601
22 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "wdio-iedriver-service" "--save-dev"
23 verbose node v8.11.3
24 verbose npm  v5.6.0
25 error Error while executing:
25 error C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/barretts/node-iedriver.git
25 error
25 error fatal: unable to access 'https://github.com/barretts/node-iedriver.git/': Could not resolve host: github.com
25 error
25 error exited with error code: 128
26 verbose exit [ 1, true ]

**Comment by gurunanakdevji** [comment]
Please let me know if there is any other way to install. Thanks

**Comment by abjerstedt** [comment]
This has nothing to do with webdriverio. 

Also, the error tells you the problem - read it again.
