### ISSUE TITLE
Unable to send key events such as "Enter"

### ISSUE THREAD

**Issue by fjaguero** [webdriverio/webdriverio#314]
Hi,

The issue I'm having is that I'm not able to emulate the "Enter" event with Selenium. I'm using keys() but, as I see in the code, this is expected since it calls `/session/:sessionId/keys` instead of `/session/:sessionId/element/:id/value`. This last one can be use to emulate this events.

I've spend some time hacking the keys.js file to make it work (check the data sent, pass the ID needed, etc) but it doesn't work.

Am I missing something? Is there another way to do this?

Thanks in advance.

_I've written many test so far with WebdriverIO. Thanks and great work!_

**Comment by RayeesMir** [comment]
client.keys('Enter') is not working with firefox.

**Comment by EdvinOlofsson** [comment]
@christian-bromann Any solution for this in firefox ??
Thanks for the great work!

**Comment by christian-bromann** [comment]
use the action command

**Comment by chandanrayarm** [comment]
Hi there I'm trying to work Option+Command+W key to work but its not working can someone help me here as client.keys(['Option, 'Command', 'W']);

**Comment by EdvinOlofsson** [comment]
Have you tested the action command as mentioned above? Make sure to hold down the keys. I think that client.keys sends a key press/release event and doesn't hold down the button to perform a combination of key presses

**Comment by chandanrayarm** [comment]
Hi @EdvinOlofsson  thanks for response, but it works fine for keys(['Command','q']) which is to quit the window

**Comment by EdvinOlofsson** [comment]
Humm interesting. You got me at a lose then :)
