### ISSUE TITLE
Execute command doesn't use W3C with Edge Webdriver

### ISSUE THREAD

**Issue by dylanlive** [webdriverio/webdriverio#3143]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [4.14.0]
 - **Mode:** [TestRunner mode]
 - **If WDIO Testrunner, running sync/async:** [Sync]
 - **Node.js version:** [8.14.0]
 - **NPM version:** [6.4.1]
 - **Browser name and version:** [Edge 44.17763.1.0]
 - **Platform name and version:** [Windows 10 Build 1809]
 - **Additional wdio packages used (if applicable):** [n/a]
- MicrosoftWebDriver Version 10.0.17763.1
- Microsoft Edge 44.17763.1.0
- Microsoft EdgeHTML 18.17763
- Windows 10 build 1809

**Config of WebdriverIO**
```
reporters: ['spec'],
    host: `<redacted>`,
    port: '<redacted>',
    protocol: '<redacted>',
    maxInstances: 1,

    capabilities: [
        {
            browserName: 'MicrosoftEdge',
            osPlatform: 'Windows',
            osVersion: '10',
        },
    ],
```

**Describe the bug**
In Windows 10 build 1809, MicrosoftWebDriver (Edge) now defaults to W3C Mode. It will not accept Json Wire Protocol commands.

Unfortunately, instead of returning Unknown Command when it receives a JWP command in W3C Mode, MicrosoftWebDriver returns Unknown Error. A bug report has been filed here:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/19917561/

Due to this, WDIO will not retry the JWP request as a W3C Request because it didn't return Unknown Command
https://github.com/webdriverio-boneyard/v4/blob/767a0cb7796c0635034bfe991fa851ff6f711ff1/lib/protocol/execute.js#L63-L65

While I believe Edge WebDriver should return the proper error, is there any patch that can be done in WDIO in the meantime to retry Unknown Errors with Edge? I'm concerned how long it may take for MicrosoftWebdriver to change this.

**To Reproduce**
1) Update to Windows 10 build 1809
2) Install Edge WebDriver (In an elevated command prompt, `DISM.exe /Online /Add-Capability /CapabilityName:Microsoft.WebDriver~~~~0.0.1.0` ) 
3) Set WDIO capabilities to run against Edge
4) Use the following example script
```
  it('should inject javascript on the page', function () {
    browser.url('http://webdriver.io');
    var result = browser.execute(function(a, b, c, d) {
        return a + b + c + d;
    }, 1, 2, 3, 4)
    console.log(result.value);
  });
```

**Expected behavior**
The test case should pass.
WebdriverIO should retry `/execute` (JWP) with `/execute/sync` (W3C)

**Log**
WebDriverIO & Edge WebDriver logs:
https://gist.github.com/dylanlive/8b1a5db3213433d6e61384e6adf09d5f
(note, the scripts are slightly different in the logs as the edge log I used from an earlier test).

**Additional context**
Related tickets:
- https://github.com/SeleniumHQ/selenium/issues/6464
- https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/19917561/

**Comment by christian-bromann** [comment]
> Would you accept a PR allowing "Unknown Error" as an acceptable error to retry the request, particularly for Edge?

Yes, absolutely!
