### ISSUE TITLE
rightClick issue in Internet Explorer

### ISSUE THREAD

**Issue by gurunanakdevji** [webdriverio/webdriverio#3146]
The statement browser.elements(elementselector).value[1].rightClick() is working fine in Google Chrome but this is not working in Internet Explorer 11 i.e. right click is not happening in IE 11. Please check.

**Comment by abjerstedt** [comment]
I'm going to close this PR, and ask that you open a new one actually using the template.

You are missing a significant number of details, including logs, what versions you are using, etc.
