### ISSUE TITLE
Allow to pick different documentation versions with Docusaurus

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#3147]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Description of the improvement / report**

The new documentation page misses a dropdown to pick from past versions. Similar to the v4 docs we should generate a new docs version for every minor version bump. The dropdown should also contain a link to the deprecated v4 docs.

**Comment by sethuster** [comment]
The documentation page does still miss a dropdown to select documentation from previous versions.  However there is now a versions page that serves the same purpose.  

[Versions.md](https://github.com/webdriverio/webdriverio/blob/master/docs/Versions.md)
