### ISSUE TITLE
rightClick is working fine in Chrome but not in Internet Explorer

### ISSUE THREAD

**Issue by gurunanakdevji** [webdriverio/webdriverio#3151]
**Environment (please complete the following information):**
 - **WebdriverIO version: 4.13.0
 - **Mode: WDIO Testrunner
 - **Node.js version: 8.11.3
 - **NPM version: 5.6.0
 - **Browser name and version: Internet Explorer 11
 - **Platform name and version: Windows 7
 - Multiple-cucumber-reporter
 - Chai library
 - moment library
 - Latest 32 bit IE driver
 
**Config of WebdriverIO**
Configured for IE and testing of IE is working fine except rightclick 

**Describe the bug**
The statement browser.elements(selector).value[0].rightClick();  is working fine in CHROME Browser but it is not working in Internet Explorer. Instead of right click only simple click is happening. Please help in resolving the issue.

**To Reproduce**
Just try to do right click in the application opened in IE. Use browser.elements(selector).value[0].rightClick();  This statement is doing rightClick in Chrome as expected.

**Expected behavior**
Statement browser.elements(selector).value[0].rightClick(); should for IE also as it is working in Chrome

**Log**
No error is coming. Just simple click happens instead of right click in IE

**Comment by christian-bromann** [comment]
@gurunanakdevji for IE you need to use the [actions command](http://webdriver.io/api/protocol/actions.html). Please join our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have further questions.
