### ISSUE TITLE
the touchAction's longPress is not able to hold for the duration of the wait's value in ms

### ISSUE THREAD

**Issue by LayMuiToh** [webdriverio/webdriverio#3153]
**Is your feature request related to a problem? Please describe.**
I need to use to have the equivalent API for the hold() method in the mobile app
however, when I use the touchAction's longPress, the button does not seem to "hold" for as the duration I set. I have tried a big value for the time duration for the wait, it appear to be like a press and release.
I want to achieve the user action to press down (hold) the button and execute another function to play a wave file (for example) and release the button

my code snippet as follows:
 browser
   .touchAction('~f', 'longPress')
   .touchAction('~f', 'moveTo')
   .touchAction('~f', 'wait', 1000000000)
  // .touchAction('~f', 'moveTo')
   .touchAction('~f', 'release');

**Describe the solution you'd like**
can this be a feature request to allow user to insert a function between the longPress and release actions?

**Describe alternatives you've considered**
Can I add a event handler to the longPress and release action?

**Additional context**
NA

**Comment by christian-bromann** [comment]
If you call the command over and over again it won't work, try
```js
    browser.touchAction('~f', [
        'longPress',
        { action: 'moveTo', x: 200, y: 0},
        { action: 'wait', ms: 5000 },
        { action: 'moveTo', x: 0, y: 0},
        'release'
    ])
```

**Comment by LayMuiToh** [comment]
I like to check if I can make changes to customise the touchActions API?
Do I need the re install webdriverio after the changes ?

Thanks
Lay Mui

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by LayMuiToh** [comment]
I like to perform this command as separate command call. 
I used touchPerform but the longPress does not seem to recogised

**Comment by christian-bromann** [comment]
@LayMuiToh not sure .. WebdriverIO allows you to send the command to the device. If the driver or the device doesn't recognise the action this is most likely a problem with the driver not WebdriverIO.
