### ISSUE TITLE
iOS Webdriver Appium tests run very seldom

### ISSUE THREAD

**Issue by chaotive** [webdriverio/webdriverio#3154]
**Environment:**
 - **WebdriverIO version:** 4.13.2
 - **Mode:** Standalone mode
 - **Node.js version:** 10.1.0
 - **NPM version:** 5.6.0
 - **Browser name and version:** Appium 1.9.1 and 1.10.0
 - **Platform name and version:** macOS 10.14.1
 - **Additional wdio packages used (if applicable):** wdio-appium-service, wdio-cucumber-framework, wdio-spec-reporter, wdio-allure-reporter, 

**Config of WebdriverIO**
We are using webdriver.io javascript configuration files to run Appium as CLI:

```javascript
const host = '127.0.0.1';   // default appium host
const port = 4730;          // default appium port

const waitforTimeout = 30 * 60000;
const commandTimeout = 30 * 60000;

exports.buildConfig = (features, steps, capabilitiesOptions) => ({
    debug: true,
    specs: features,

    reporters: ['allure','spec'],
    reporterOptions: {
        allure: {
            outputDir: './allure-results/'
        }
    },

    host: host,
    port: port,

    maxInstances: 1,

    capabilities: [
        {
            appiumVersion: '1.10.0',                 // Appium module version
            browserName: '',                        // browser name is empty for native apps
            waitforTimeout: waitforTimeout,
            commandTimeout: commandTimeout,
            newCommandTimeout: 30 * 60000,
            ...capabilitiesOptions,
        }
    ],

    services: ['appium'],
    appium: {
        waitStartTime: 6000,
        waitforTimeout: waitforTimeout,
        command: 'appium',
        logFileName: 'appium.log',
        args: {
            address: host,
            port: port,
            commandTimeout: commandTimeout,
            sessionOverride: true,
            debugLogSpacing: true,
            nativeInstrumentsLib: true
        }
    },

    /**
     * test configurations
     */
    logLevel: 'verbose',
    coloredLogs: true,
    framework: 'cucumber',          // cucumber framework specified 
    cucumberOpts: {
        compiler: ['ts:ts-node/register'],
        backtrace: true,
        failFast: false,
        timeout: 5 * 60 * 60000,
        require: steps      // importing/requiring step definition files
    },

    /**
     * hooks help us execute the repeatitive and common utilities 
     * of the project.
     */
    onPrepare: function () {
        console.log('<<< NATIVE APP TESTS STARTED >>>');
    },

    afterScenario: function (scenario) {
        browser.screenshot();
     },

    onComplete: function () {
        console.log('<<< TESTING FINISHED >>>');
    }

});
```

**Describe the bug**
Testing an iOS mobile app using Appium, trough WebDriverAgent, works very seldom. It successfully gets to run tests maybe 1 of 5 times we have tried. 

It manages to install the app and WebDriverAgent, and then start the application. After that, it just stucks and after a while it seems to attempt restarting the whole process again. Most times it just repeats itself and after a couple of minutes it just quits. If we were lucky, it actually started running the tests. Logs show that communication with WebDriverAgent is very flaky.

**To Reproduce**
- define 'scripts' command on package.json as '"ios-local-test": "wdio ./config/ios-local.config.js"'
- npm run ios-local-test

**Expected behavior**
Run Appium tests correctly everytime. 

**Log**
[GIST](https://gist.github.com/chaotive/0dbe0dab509dfa29499c4be8f8faae4c)
[GIST](https://gist.github.com/chaotive/8a57b0c3e4b9a5266a7f261513532d45)

**Comment by christian-bromann** [comment]
@chaotive sorry but this seems like a stability issue in Appium. Would you mind creating the issue there? You can also try to increase the `connectionRetryTimeout` property in your wdio.conf as it seems that Appium takes too long to set up the app. Thanks!

**Comment by chaotive** [comment]
Thank you. I have already opened an issue ticket on Appium for this. I have also opened one on WebDriverAgent, which is the component that I think is most closely related to the problem.

Right now, I'm not 100% clear about where the issue is, but any feedback is welcomed. Will let you know how this goes.
