### ISSUE TITLE
touchPerform's longPress does not work 

### ISSUE THREAD

**Issue by LayMuiToh** [webdriverio/webdriverio#3159]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - "webdriverio": "^4.14.1"
 - **Mode:** [ standalone]
 - sync
 - **Node.js version:**9.1.0
 - **NPM version:** 6.4.1
 - **Browser name and version:** NA (mobile native)
 - **Platform name and version:**  iOS 10.13.6
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
An unknown server-side error occurred while processing the command. Original error: *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]

**To Reproduce**
 var mic_x = browser.getLocation('~f', 'x');
 var mic_y = browser.getLocation('~f', 'y');

browser.touchPerform([{
        action: 'longPress',
        options: {
            x: mic_x,
            y: mic_y
        }
    }]);
 
    browser.touchPerform([{
      action: 'moveTo',
      options: {
          x: mic_x,
          y: mic_y
      }
    }]);

    browser.touchPerform([{
      action: 'wait',
      options: {
          ms: 5000
      }
    }]);

**Comment by LayMuiToh** [comment]
function playAudio()
{
  const player = require('node-wav-player');
  console.log('play wave file');
  player.play({
    path: 'xxxx/testdata/audio/show_me_basf.wav',
    sync: true
  }).then(() => {
    console.log('The wav file was played through.');
  }).catch((error) => {
    console.error(error);
  });
}

function holdToTalk(callback) {
  if(Main.mic.waitForExist()) {
      var mic_x = browser.getLocation('~f', 'x');
      var mic_y = browser.getLocation('~f', 'y');
      browser.touchAction('~f', [
        'longPress',
        { action: 'moveTo', x: mic_x, y: mic_y},
        { action: 'wait', ms: 5000},
        { action: 'moveTo', x: mic_x + 1, y: mic_y + 1},
         'release'
      ]);

      callback();
  }
}

module.exports = () => {
  describe('Voice input test at Main Page', function() {
    it('should able to speak xxx and go to Main Page', function () {
      if(Main.mic.waitForExist()) {
        // Get rid of the pop up alert to enable the microphone
        browser.touchAction('~f', 'tap');
        try {
          browser.alertAccept();
        } catch(e)
        {
          //no alert error
        }
      } 
    
      holdToTalk(playAudio);
      

My command sent to appium is:
[17:57:09]  COMMAND	POST 	 "/wd/hub/session/d45a072f-790b-4485-bf11-bd5c26cebd4e/touch/perform"
[17:57:09]  DATA		{"actions":[{"action":"longPress","options":{"element":"B5000000-0000-0000-B945-000000000000"}},{"action":"moveTo","options":{"x":120,"y":458}},{"action":"wait","options":{"ms":5000}},{"action":"moveTo","options":{"x":121,"y":459}},{"action":"release"}]}
[17:57:15]  RESULT		{}
play wave file


Instead of playing the wave file during the wait of the touchAction, it play after the POST command is sent.

can I use touchPerform API to send the user actions separately?
using the touchAction chain commands with callback does not seem to work for my use case.

**Comment by LayMuiToh** [comment]
browser.touchPerform([{
      action: 'longPress',
      options: {
        element: '~f'
      },
      action: 'moveTo', 
      options: {
        x: mic_x,
        y: mic_y
      },
      action: 'wait', 
      options: {
       ms: 1000
      }
    }]);


I got the error:An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "'wait' action should be preceded by an item with absolute positioning" UserInfo={NSLocalizedDescription='wait' action should be preceded by an item with absolute positioning}
running
Error: An unknown server-side error occurred while processing the command.
    at touchPerform([object Object]) - index.js:312:3

**Comment by christian-bromann** [comment]
see https://github.com/webdriverio/webdriverio/issues/3153#issuecomment-449356664

**Comment by LayMuiToh** [comment]
@christian-bromann 
The issue is not the longPress does not work. it's the touchPerform API ,I have updated the title.
Either the documentation at http://webdriver.io/api/mobile/touchPerform.html is not clear enough for me to call it or I made some mistake in my code
my code snippet:

browser.touchPerform([{
          action: 'longPress',
          options: {
              x: mic_x,
              y: mic_y
          },
          action: 'moveTo',
          options: {
              x: mic_x,
              y: mic_y
          },
          action: 'wait',
          options: {
              ms: 1000
          },
      }]);

I got this error when I run the test:
An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "'wait' action should be preceded by an item with absolute positioning" UserInfo={NSLocalizedDescription='wait' action should be preceded by an item with absolute positioning}

**Comment by christian-bromann** [comment]
> action should be preceded by an item with absolute positioning

I neither know what this error means nor what is causing it. Feel free to provide a PR with a patch that improves this.

**Comment by sumanthvakacharla** [comment]
actions.move_to(element, x,y) and actions.perform() produces the exception mentioned in the below:

Exception: Message: An unknown server-side error occurred while processing the command. Original error: *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]

(
	0   CoreFoundation                      0x0000000106e0a1e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x0000000109bb0031 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000106e4a0bc _CFThrowFormattedException + 194
	3   CoreFoundation                      0x0000000106d1745d -[__NSPlaceholderArray initWithObjects:count:] + 237
	4   CoreFoundation                      0x0000000106d1de24 +[NSArray arrayWithObjects:count:] + 52
	5   WebDriverAgentLib                   0x000000011cedfbb7 -[FBMoveToItem addToEventPath:allItems:currentItemIndex:error:] + 279
	6   WebDriverAgentLib                   0x000000011cf049a1 -[FBBaseGestureItemsChain asEventPathsWithError:] + 929
	7   WebDriverAgentLib                   0x000000011cee1280 -[FBAppiumActionsSynthesizer eventPathsWithAction:error:] + 2640
	8   WebDriverAgentLib                   0x000000011cee1ae8 -[FBAppiumActionsSynthesizer synthesizeWithError:] + 1112
	9   WebDriverAgentLib                   0x000000011cf07c93 -[XCUIApplication(FBTouchAction) fb_performActionsWithSynthesizerType:actions:elementCache:error:] + 195
	10  WebDriverAgentLib                   0x000000011cf07dfc -[XCUIApplication(FBTouchAction) fb_performAppiumTouchActions:elementCache:error:] + 156
	11  WebDriverAgentLib                   0x000000011cf08bfc +[FBTouchActionCommands handlePerformAppiumTouchActions:] + 332
	12  WebDriverAgentLib                   0x000000011cef6d86 -[FBRoute_TargetAction mountRequest:intoResponse:] + 182
	13  WebDriverAgentLib                   0x000000011cee3fa9 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 553
	14  RoutingHTTPServer                   0x000000011cfdac18 -[RoutingHTTPServer handleRoute:withRequest:response:] + 136
	15  RoutingHTTPServer                   0x000000011cfdb4fa __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 47
	16  libdispatch.dylib                   0x000000010e77a779 _dispatch_client_callout + 8
	17  libdispatch.dylib                   0x000000010e785c3f _dispatch_sync_thread_bound_invoke + 108
	18  libdispatch.dylib                   0x000000010e77a779 _dispatch_client_callout + 8
	19  libdispatch.dylib                   0x000000010e784778 _dispatch_main_queue_callback_4CF + 1279
	20  CoreFoundation                      0x0000000106dccc99 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	21  CoreFoundation                      0x0000000106d90ea6 __CFRunLoopRun + 2342
	22  CoreFoundation                      0x0000000106d9030b CFRunLoopRunSpecific + 635
	23  Foundation                          0x00000001095abb4a -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 274
	24  WebDriverAgentLib                   0x000000011cee2880 -[FBWebServer startServing] + 368
	25  WebDriverAgentRunner                0x000000011cecf03a -[UITestingUITests testRunner] + 122
	26  CoreFoundation                      0x0000000106d8dccc __invoking___ + 140
	27  CoreFoundation                      0x0000000106d8db84 -[NSInvocation invoke] + 308
	28  XCTest                              0x0000000106b9fb74 __24-[XCTestCase invokeTest]_block_invoke.194 + 78
	29  XCTest                              0x0000000106bf78a4 -[XCTestCase(Failures) performFailableBlock:testCaseRun:shouldInterruptTest:] + 57
	30  XCTest                              0x0000000106bf77c2 -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 96
	31  XCTest                              0x0000000106b9f804 __24-[XCTestCase invokeTest]_block_invoke + 848
	32  XCTest                              0x0000000106bfdd01 -[XCUITestContext performInScope:] + 128
	33  XCTest                              0x0000000106b9f3f1 -[XCTestCase testContextPerformInScope:] + 116
	34  XCTest                              0x0000000106b9f4a7 -[XCTestCase invokeTest] + 137
	35  XCTest                              0x0000000106ba0f73 __26-[XCTestCase performTest:]_block_invoke_2 + 43
	36  XCTest                              0x0000000106bf78a4 -[XCTestCase(Failures) performFailableBlock:testCaseRun:shouldInterruptTest:] + 57
	37  XCTest                              0x0000000106bf77c2 -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 96
	38  XCTest                              0x0000000106ba0e8a __26-[XCTestCase performTest:]_block_invoke.316 + 88
	39  XCTest                              0x0000000106c083b7 +[XCTContext runInContextForTestCase:block:] + 225
	40  XCTest                              0x0000000106ba05f8 -[XCTestCase performTest:] + 676
	41  XCTest                              0x0000000106be3d6c -[XCTest runTest] + 57
	42  XCTest                              0x0000000106b9b0d7 __27-[XCTestSuite performTest:]_block_invoke + 365
	43  XCTest                              0x0000000106b9a8b3 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 54
	44  XCTest                              0x0000000106b9ab6f -[XCTestSuite performTest:] + 290
	45  XCTest                              0x0000000106be3d6c -[XCTest runTest] + 57
	46  XCTest                              0x0000000106b9b0d7 __27-[XCTestSuite performTest:]_block_invoke + 365
	47  XCTest                              0x0000000106b9a8b3 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 54
	48  XCTest                              0x0000000106b9ab6f -[XCTestSuite performTest:] + 290
	49  XCTest                              0x0000000106be3d6c -[XCTest runTest] + 57
	50  XCTest                              0x0000000106b9b0d7 __27-[XCTestSuite performTest:]_block_invoke + 365
	51  XCTest                              0x0000000106b9a8b3 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 54
	52  XCTest                              0x0000000106b9ab6f -[XCTestSuite performTest:] + 290
	53  XCTest                              0x0000000106be3d6c -[XCTest runTest] + 57
	54  XCTest                              0x0000000106c12986 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 171
	55  XCTest                              0x0000000106c12a57 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke.80 + 68
	56  XCTest                              0x0000000106bb2474 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 588
	57  XCTest                              0x0000000106c1273d -[XCTTestRunSession runTestsAndReturnError:] + 623
	58  XCTest                              0x0000000106b7f41c -[XCTestDriver runTestsAndReturnError:] + 446
	59  XCTest                              0x0000000106c0456f _XCTestMain + 2333
	60  WebDriverAgentRunner-Runner         0x00000001068b8053 -[_XCTRunnerAppDelegate applicationWillResignActive:] + 0
	61  WebDriverAgentRunner-Runner         0x00000001068b7f51 _XCTRunnerRunTests + 0
	62  CoreFoundation                      0x0000000106dacb0c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	63  CoreFoundation                      0x0000000106d912db __CFRunLoopDoBlocks + 331
	64  CoreFoundation                      0x0000000106d90a84 __CFRunLoopRun + 1284
	65  CoreFoundation                      0x0000000106d9030b CFRunLoopRunSpecific + 635
	66  GraphicsServices                    0x000000010b5c0a73 GSEventRunModal + 62
	67  UIKit                               0x00000001073f50b7 UIApplicationMain + 159
	68  WebDriverAgentRunner-Runner         0x00000001068b821b main + 183
	69  libdyld.dylib                       0x000000010e7ef955 start + 1
	70  ???                                 0x0000000000000005 0x0 + 5
)

**Comment by Sumanth9318** [comment]
TouchAction() class
actions.move_to(element, x,y) and actions.perform() produces the exception mentioned in the below:

Exception: Message: An unknown server-side error occurred while processing the command. Original error: *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]

(
0 CoreFoundation 0x0000000106e0a1e6 __exceptionPreprocess + 294
1 libobjc.A.dylib 0x0000000109bb0031 objc_exception_throw + 48
2 CoreFoundation 0x0000000106e4a0bc _CFThrowFormattedException + 194
3 CoreFoundation 0x0000000106d1745d -[__NSPlaceholderArray initWithObjects:count:] + 237
4 CoreFoundation 0x0000000106d1de24 +[NSArray arrayWithObjects:count:] + 52
5 WebDriverAgentLib 0x000000011cedfbb7 -[FBMoveToItem addToEventPath:allItems:currentItemIndex:error:] + 279
6 WebDriverAgentLib 0x000000011cf049a1 -[FBBaseGestureItemsChain asEventPathsWithError:] + 929
7 WebDriverAgentLib 0x000000011cee1280 -[FBAppiumActionsSynthesizer eventPathsWithAction:error:] + 2640
8 WebDriverAgentLib 0x000000011cee1ae8 -[FBAppiumActionsSynthesizer synthesizeWithError:] + 1112
9 WebDriverAgentLib 0x000000011cf07c93 -[XCUIApplication(FBTouchAction) fb_performActionsWithSynthesizerType:actions:elementCache:error:] + 195
10 WebDriverAgentLib 0x000000011cf07dfc -[XCUIApplication(FBTouchAction) fb_performAppiumTouchActions:elementCache:error:] + 156
11 WebDriverAgentLib 0x000000011cf08bfc +[FBTouchActionCommands handlePerformAppiumTouchActions:] + 332
12 WebDriverAgentLib 0x000000011cef6d86 -[FBRoute_TargetAction mountRequest:intoResponse:] + 182
13 WebDriverAgentLib 0x000000011cee3fa9 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 553
14 RoutingHTTPServer 0x000000011cfdac18 -[RoutingHTTPServer handleRoute:withRequest:response:] + 136
15 RoutingHTTPServer 0x000000011cfdb4fa __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 47
16 libdispatch.dylib 0x000000010e77a779 _dispatch_client_callout + 8
17 libdispatch.dylib 0x000000010e785c3f _dispatch_sync_thread_bound_invoke + 108
18 libdispatch.dylib 0x000000010e77a779 _dispatch_client_callout + 8
19 libdispatch.dylib 0x000000010e784778 _dispatch_main_queue_callback_4CF + 1279
20 CoreFoundation 0x0000000106dccc99 CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE + 9
21 CoreFoundation 0x0000000106d90ea6 _CFRunLoopRun + 2342
22 CoreFoundation 0x0000000106d9030b CFRunLoopRunSpecific + 635
23 Foundation 0x00000001095abb4a -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 274
24 WebDriverAgentLib 0x000000011cee2880 -[FBWebServer startServing] + 368
25 WebDriverAgentRunner 0x000000011cecf03a -[UITestingUITests testRunner] + 122
26 CoreFoundation 0x0000000106d8dccc invoking + 140
27 CoreFoundation 0x0000000106d8db84 -[NSInvocation invoke] + 308
28 XCTest 0x0000000106b9fb74 __24-[XCTestCase invokeTest]_block_invoke.194 + 78
29 XCTest 0x0000000106bf78a4 -[XCTestCase(Failures) performFailableBlock:testCaseRun:shouldInterruptTest:] + 57
30 XCTest 0x0000000106bf77c2 -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 96
31 XCTest 0x0000000106b9f804 __24-[XCTestCase invokeTest]_block_invoke + 848
32 XCTest 0x0000000106bfdd01 -[XCUITestContext performInScope:] + 128
33 XCTest 0x0000000106b9f3f1 -[XCTestCase testContextPerformInScope:] + 116
34 XCTest 0x0000000106b9f4a7 -[XCTestCase invokeTest] + 137
35 XCTest 0x0000000106ba0f73 __26-[XCTestCase performTest:]_block_invoke_2 + 43
36 XCTest 0x0000000106bf78a4 -[XCTestCase(Failures) performFailableBlock:testCaseRun:shouldInterruptTest:] + 57
37 XCTest 0x0000000106bf77c2 -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 96
38 XCTest 0x0000000106ba0e8a __26-[XCTestCase performTest:]_block_invoke.316 + 88
39 XCTest 0x0000000106c083b7 +[XCTContext runInContextForTestCase:block:] + 225
40 XCTest 0x0000000106ba05f8 -[XCTestCase performTest:] + 676
41 XCTest 0x0000000106be3d6c -[XCTest runTest] + 57
42 XCTest 0x0000000106b9b0d7 __27-[XCTestSuite performTest:]_block_invoke + 365
43 XCTest 0x0000000106b9a8b3 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 54
44 XCTest 0x0000000106b9ab6f -[XCTestSuite performTest:] + 290
45 XCTest 0x0000000106be3d6c -[XCTest runTest] + 57
46 XCTest 0x0000000106b9b0d7 __27-[XCTestSuite performTest:]_block_invoke + 365
47 XCTest 0x0000000106b9a8b3 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 54
48 XCTest 0x0000000106b9ab6f -[XCTestSuite performTest:] + 290
49 XCTest 0x0000000106be3d6c -[XCTest runTest] + 57
50 XCTest 0x0000000106b9b0d7 __27-[XCTestSuite performTest:]_block_invoke + 365
51 XCTest 0x0000000106b9a8b3 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 54
52 XCTest 0x0000000106b9ab6f -[XCTestSuite performTest:] + 290
53 XCTest 0x0000000106be3d6c -[XCTest runTest] + 57
54 XCTest 0x0000000106c12986 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 171
55 XCTest 0x0000000106c12a57 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke.80 + 68
56 XCTest 0x0000000106bb2474 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 588
57 XCTest 0x0000000106c1273d -[XCTTestRunSession runTestsAndReturnError:] + 623
58 XCTest 0x0000000106b7f41c -[XCTestDriver runTestsAndReturnError:] + 446
59 XCTest 0x0000000106c0456f _XCTestMain + 2333
60 WebDriverAgentRunner-Runner 0x00000001068b8053 -[_XCTRunnerAppDelegate applicationWillResignActive:] + 0
61 WebDriverAgentRunner-Runner 0x00000001068b7f51 _XCTRunnerRunTests + 0
62 CoreFoundation 0x0000000106dacb0c CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK + 12
63 CoreFoundation 0x0000000106d912db __CFRunLoopDoBlocks + 331
64 CoreFoundation 0x0000000106d90a84 __CFRunLoopRun + 1284
65 CoreFoundation 0x0000000106d9030b CFRunLoopRunSpecific + 635
66 GraphicsServices 0x000000010b5c0a73 GSEventRunModal + 62
67 UIKit 0x00000001073f50b7 UIApplicationMain + 159
68 WebDriverAgentRunner-Runner 0x00000001068b821b main + 183
69 libdyld.dylib 0x000000010e7ef955 start + 1
70 ??? 0x0000000000000005 0x0 + 5
)
