### ISSUE TITLE
V5: getText() / getAttribute() return as promises not text

### ISSUE THREAD

**Issue by jdavis61** [webdriverio/webdriverio#3166]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [5.0.0]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running async.sync** [sync]
 - **Node.js version:** [10.14,2]
 - **NPM version:** [6.4.1]
 - **Browser name and version:** [Chrome 71.0.3578.98 (Official Build) (64-bit) (cohort: Stable)]
 - **Platform name and version:** [Windows 10 Home]
 - **Additional wdio packages used (if applicable):** [@wdio/cli, @wdio/local-runner, @wdio/mocha-framework, @wdio/selenium-standalone-service, @wdio/spec-reporter, @wdio/sync]

**Config of WebdriverIO**
The wdio config is found at https://gist.github.com/jdavis61/885f827a27cea69b8923420ea68231e5#file-wdio-conf-js.

**Describe the bug**
Calling the `getText()` and `getAttribute()` methods are returning a promise instead of a string.

**To Reproduce**
1. Download this gist by running `git clone https://gist.github.com/jdavis61/885f827a27cea69b8923420ea68231e5 v5example`
2. cd v5example
3. npm install
4. npm run test

The below assertion fails with `Promise { <pending> } == 'WEBDRIVER I/O'`
```
const element = $('.projectTitle');
assert.equal(element.getText(), 'WEBDRIVER I/O');
```

The below assertion fails with `Promise { <pending> } == '.tagline'`
```
const e = browser.$('.tagline');
const attribute = e.getAttribute('class');
assert.equal(attribute, '.tagline');
```

**Expected behavior**
Calling `getText()` and `getAttribute()` returns a string and not a promise.

**Additional context**
This behavior does not happen in v4.

**Comment by WillBrock** [comment]
I noticed this as well with getValue but haven't had the chance to look into it yet.

**Comment by christian-bromann** [comment]
Will look into this

**Comment by MoniRaj1** [comment]
Hi , 
is this issue fixed ?

Thanks

**Comment by mgrybyk** [comment]
Of course.
