### ISSUE TITLE
webdriver.io doc site SERP and CLI error indexed pages broken

### ISSUE THREAD

**Issue by srescio** [webdriverio/webdriverio#3168]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [ ] Missing documentation
- [x] Other

**Description of the improvement / report**
Most of google indexed Webdriver.io documentation pages, as well documentation links provided in console in case of errors for v4, end up in 404 server page error with `NoSuchKey`,
sample SERP: https://www.google.com/search?q=wevdriverio+get+started&oq=wevdriverio+get+started&aqs=chrome..69i57j0.3143j0j7&sourceid=chrome&ie=UTF-8

the very first result link is http://webdriver.io/guide.html but the 404 page is hit:
```
404 Not Found
Code: NoSuchKey
Message: The specified key does not exist.
Key: guide.html
RequestId: BDBD1F7DC48B34F5
HostId: pb6BqwDz8evZjtX2KtbxwXXC/PMB3j67vMne8YTJawV3PiYvZXvQevCdcbuIYcANP2ZNnEHEHu0=
```

also on a project using version 4.14.0, when a timeout happens the error message is:
```
Timeout of 10000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html);if returning a Promise, ensure it resolves. (/Applications/MAMP/htdocs/SimoneRescio.it/test/specs/homepage.js)
running chrome
Error: Timeout of 10000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves. 
```

but again the linked doc page ends in 404:
```
404 Not Found
Code: NoSuchKey
Message: The specified key does not exist.
Key: guide/testrunner/timeouts.html
RequestId: EACD153B5A4E18FA
HostId: WDDHWOmof1ssfOTpjLPZ3aJyYGzISnZNf9RnhFSBHXhEw1k3cAkxsjku4wnPr5o7+lC8arSnu4Y=
```

issue is browser/device independent

**Comment by christian-bromann** [comment]
I setup redirects for all legacy pages. We should receive no 404 errors more.
