### ISSUE TITLE
Transfer promiseness

### ISSUE THREAD

**Issue by kkartunov** [webdriverio/webdriverio#317]
Is there any way to transfer the promiseness and use [chai-as-promised](http://chaijs.com/plugins/chai-as-promised) plugin for chai?

Like for instance the [admc/wd](https://github.com/admc/wd/blob/master/examples/promise/chrome.js#L15) library supports?

So one can use the should etc directly on the chain instead of wrapping everything in `some_async().then(function(err, res){ do something with res here });`
which will become
`some_async().should.become(res)`

**Comment by corbinu** [comment]
Is this working now? 
My test can't find 'should'.

Using
`Node 11.14`
`OS X 10.10`
`webdriverio@2.4.3`
`chai@1.10.0`
`chai-as-promised@4.1.1`
`selenium-standalone@3.0.2`

Code sample
```
var chai = require('chai');
var chaiAsPromised = require("chai-as-promised");
var webdriverio = require('webdriverio');

chai.use(chaiAsPromised);
var assert = chai.assert;
var expect = chai.expect;

var client =  webdriverio.remote({
    desiredCapabilities: {
        browserName: 'chrome'
    }
});

describe('As Promised', function() {

    before(function() {

        return client.init().url('http://webdriverjs.christian-bromann.com/');

    });

    it('view homepage', function () {

        return client.getTitle().should.become('WebdriverJS Testpage').isVisible('body').should.eventually.be.true;

    });

    after(function() {
        return client.end();
    });

});
```
Error:
```
As Promised
    1) view homepage

  0 passing (10s)
  1 failing

  1) As Promised view homepage:
     TypeError: Cannot read property 'become' of undefined
      at Context.<anonymous> (/Users/corbinu/Developer/acceptance-tests/test/aspromised.js:25:40)
      at callFn (/Users/corbinu/Developer/acceptance-tests/node_modules/mocha/lib/runnable.js:251:21)
      at Test.Runnable.run (/Users/corbinu/Developer/acceptance-tests/node_modules/mocha/lib/runnable.js:244:7)
      at Runner.runTest (/Users/corbinu/Developer/acceptance-tests/node_modules/mocha/lib/runner.js:374:10)
      at /Users/corbinu/Developer/acceptance-tests/node_modules/mocha/lib/runner.js:452:12
      at next (/Users/corbinu/Developer/acceptance-tests/node_modules/mocha/lib/runner.js:299:14)
      at /Users/corbinu/Developer/acceptance-tests/node_modules/mocha/lib/runner.js:309:7
      at next (/Users/corbinu/Developer/acceptance-tests/node_modules/mocha/lib/runner.js:248:23)
      at Immediate._onImmediate (/Users/corbinu/Developer/acceptance-tests/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:374:17)
```

**Comment by Yanchek99** [comment]
@corbinu 

Make sure you include:
chai.should();
chaiAsPromised.transferPromiseness = client.transferPromiseness;

**Comment by corbinu** [comment]
@Yanchek99 Thanks... honestly just ended up building the tests in a callback manner. Would be nice of somebody could commit a version of the mocha chai examples that uses promises.

**Comment by Robinfr** [comment]
Yes, with @Yanchek99 's comment about the transferPromiseness I would have never figured this out.

**Comment by Robinfr** [comment]
Also, the transferPromiseness doesn't work in combination with addCommand. If you've added a command, it will not recognize the command after the the assertion, e.g.:

    client.addCommand('doSomething', helper.doSomething.bind(client));
    
    client
            .isExisting('#intro').should.become(true)
            .doSomething()

You will get the error that object does not have the method doSomething.

**Comment by rjurado01** [comment]
@Yanchek99  +1

Please add it to README.

**Comment by silvenon** [comment]
Suggested in #509.
