### ISSUE TITLE
Remote file upload

### ISSUE THREAD

**Issue by DavertMik** [webdriverio/webdriverio#3170]
**Is your feature request related to a problem? Please describe.**

When I test `input[type=file]` I can provide a filename to test uploading file. 
It's fine until your Selenium Server runs on a different machine or inside a container.
So to run tests with remote Selenium and test file uploads there should be a way to move that files to that machine.

**Describe the solution you'd like**
In webdriverio v4 there was `file` command which used undocumented Selenium API (/file) to transfer files and return a path from a remote machine. We can backport that functionality.

This API -> https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/command.js#L171

Also, I still think there should be API for creating custom requests like this one in `webdriver` package. 
Right now only spec requests allowed and no API like requestHandler in webdriver v4 available

**Describe alternatives you've considered**
Making standalone package.

**Comment by christian-bromann** [comment]
Will be tackled by #3135
