### ISSUE TITLE
Using JUnit Reporter results in an error

### ISSUE THREAD

**Issue by callmekatootie** [webdriverio/webdriverio#3173]
**Environment**
 - **WebdriverIO version: 5.0.3**
 - **Mode: WDIO Testrunner**
 - **If WDIO Testrunner, running sync/async: sync**
 - **Node.js version: 10.12.0**
 - **NPM version: 6.4.1**
 - **Browser name and version: Chrome Version 70.0.3538.67 (Official Build) (64-bit)**
 - **Platform name and version: Ubuntu 18.04**
 - **Additional wdio packages used (if applicable): Pasting the devDependencies package.json below:** 
```
    "@wdio/cli": "^5.0.3",
    "@wdio/junit-reporter": "^5.0.3",
    "@wdio/local-runner": "^5.0.3",
    "@wdio/mocha-framework": "^5.0.3",
    "@wdio/selenium-standalone-service": "^5.0.3",
    "@wdio/spec-reporter": "^5.0.3",
    "@wdio/sync": "^5.0.3"
```

**Config of WebdriverIO**
I ran the CLI and pretty much followed the responses mentioned [here](https://webdriver.io/docs/gettingstarted.html), except, set both Spec and JUnit for my reporter and used selenium standalone server under service

**Describe the bug**
When I execute the command `./node_modules/.bin/wdio wdio.conf.js`, it gives an error:

```
ERROR wdio-local-runner: Failed launching test session: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at Object.open (fs.js:406:3)
    at WriteStream.open (internal/fs/streams.js:268:12)
    at new WriteStream (internal/fs/streams.js:255:10)
    at Object.createWriteStream (fs.js:1729:10)
    at new WDIOReporter (/redacted/node_modules/@wdio/reporter/src/index.js:20:9)
    at new JunitReporter (/redacted/node_modules/@wdio/junit-reporter/src/index.js:8:9)
    at BaseReporter.initReporter (/redacted/node_modules/@wdio/runner/src/reporter.js:154:20)
    at Array.map (<anonymous>)
    at new map (/redacted/node_modules/@wdio/runner/src/reporter.js:20:43)
    at Runner.run (/redacted/node_modules/@wdio/runner/src/index.js:54:25)
```

I have configured the `outputDir` for JUnit and I still get the error. My configuration is:

```
reporters: ['spec', ['junit', { outputDir: './' }]],
```

**To Reproduce**
Generate the `wdio.conf.js` using the CLI - use JUnit as the reporter and selenium standalone server for service. Execute the test.

**Expected behavior**
For there to be no errors

**Log**
Mentioned above

**NOTE**
If I remove junit from the `reporters` list, the command runs successfully.

**Comment by callmekatootie** [comment]
Debugged this and found the cause to be the `wdio.conf.js` file, which needs to have the `logDir` configuration. I set it to a folder (that needs to exist, it does not seem to create one if its does not exist) and then was able to run it successfully.

I guess the question now is what is `logDir` config  and I am guessing it needs to be documented?

**Comment by BorisOsipov** [comment]
@callmekatootie as quick fix I may suggest you add
`logDir: './'` in your wdio.conf.js.
Like this

```
reporters: ['spec', ['junit', { outputDir: './' }]],
logDir: './'
```
