### ISSUE TITLE
Suddenly webdriverio stopped working

### ISSUE THREAD

**Issue by postmeback** [webdriverio/webdriverio#3185]
I have done all the necessary things to run webdriverio in my application. Even, it was running till yesterday. But, today a new error has came up. I have uninstalled and reinstalled webdriver-manager & webdriver-manager-replacement but it did not work. Below is the error message appearing

    Cannot read property 'tests' of undefined
    at ReporterStats.testStart (C:\NodeCode\MIS.ACT.Angular\node_modules\webdriverio\build\lib\utils\ReporterStats.js:345:74)
    at BaseReporter.<anonymous> (C:\NodeCode\MIS.ACT.Angular\node_modules\webdriverio\build\lib\utils\BaseReporter.js:151:25)
    at emitOne (events.js:116:13)
    at BaseReporter.emit (events.js:211:7)
    at BaseReporter.handleEvent (C:\NodeCode\MIS.ACT.Angular\node_modules\webdriverio\build\lib\utils\BaseReporter.js:300:27)
    at Launcher.messageHandler (C:\NodeCode\MIS.ACT.Angular\node_modules\webdriverio\build\lib\launcher.js:688:28)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)

Below are details from **package.json**

      "private": true,
      "dependencies": {
    "@angular/animations": "^5.2.1",
    "@angular/cdk": "^5.1.0",
    "@angular/common": "^5.1.0",
    "@angular/compiler": "^5.1.0",
    "@angular/core": "^5.2.9",
    "@angular/flex-layout": "^5.0.0-beta.14",
    "@angular/forms": "^5.1.0",
    "@angular/http": "^5.1.0",
    "@angular/material": "^5.1.0",
    "@angular/platform-browser": "^5.1.0",
    "@angular/platform-browser-dynamic": "^5.1.0",
    "@angular/router": "^5.1.0",
    "@types/pdfmake": "^0.1.2",
    "angular-bootstrap-md": "^5.1.2",
    "chromedriver": "^2.44.0",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "mocha": "^5.2.0",
    "pdfmake": "^0.1.39",
    "rxjs": "^5.5.2",
    "webdriver-manager-replacement": "^1.1.3",
    "webdriverio": "^4.14.1",
    "zone.js": "^0.8.19"
     },
    "devDependencies": {
    "@angular/cli": "^1.6.7",
    "@angular/compiler-cli": "^5.1.0",
    "@angular/language-service": "^5.1.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "^5.4.1",
    "ts-node": "~3.2.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3",
    "wdio-dot-reporter": "0.0.10",
    "wdio-mocha-framework": "^0.6.4",
    "wdio-selenium-standalone-service": "0.0.10"
       }
      }

Please let me know, what am i missing and feel free to ask questions.

Thanks Arka

**Comment by postmeback** [comment]
Feel free to ask questions as i am new to webdriverio...

**Comment by christian-bromann** [comment]
@postmeback can you provide a minimal reproducible example? Otherwise this is impossible to analyze.

**Comment by postmeback** [comment]
As, the webdriverio recently had a major update (which i found later), it was not working at my end. Now, it's working fine.


Sorry for late update
