### ISSUE TITLE
When debugging using VS Code, the test passes but the report says it is failed in overall reporting -- WebdriverIO 5.0

### ISSUE THREAD

**Issue by smarigowda** [webdriverio/webdriverio#3191]
- **WebdriverIO version:** "webdriverio": "^5.0.3"
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v10.14.2
 - **NPM version:** 6.4.1
 - **Browser name and version:** Version 71.0.3578.98 (Official Build) (64-bit)
 - **Platform name and version:** Mac Mojave 10.14.2
 - **Additional wdio packages used (if applicable):** 
https://github.com/smarigowda/wdio5POC/blob/syncVersionRaisingIssueWithWebdriverIO/package.json

**Config of WebdriverIO**
An example of how you configured WebdriverIO config
https://github.com/smarigowda/wdio5POC/blob/syncVersionRaisingIssueWithWebdriverIO/wdio.conf.js

**Describe the bug**
When debugging the test using VS Code. The test passes but the overall report says it as fail. See attached screenshot.

**To Reproduce**
1. Clone the repository: https://github.com/smarigowda/wdio5POC/tree/syncVersionRaisingIssueWithWebdriverIO

2. npm install

3. Open the repository in VS Code. Open the test spec file. Click on debug icon on the left hand side of VS navigation. Click on green arrow at the top to run/ debug the test. Test should pass and you should see that the spec reporter reports the overall test as fail though the tests are passing.

[Include code or an example repository that can easily be set up]

**Expected behavior**
Overall report should report the status properly.

**Log**
Refer attached screenshot.

**Comment by smarigowda** [comment]
<img width="1100" alt="test_spec_js_ _wdio5poc" src="https://user-images.githubusercontent.com/1831259/50489101-bafc8d00-09fd-11e9-8c85-2d378f96fb26.png">

**Comment by Mort2007** [comment]
As a small note if you unlink  the debugger it will show as passed. You won't be able to use break points anymore so is not a work around but been pulling my hair on the same issue.
![image](https://user-images.githubusercontent.com/30624361/50568307-c6c2b900-0d47-11e9-9507-bce50004b88c.png)

**Comment by stoneCC** [comment]
i have same issues, need to be fixed

**Comment by christian-bromann** [comment]
> need to be fixed

Please provide a PR, thanks!

**Comment by stoneCC** [comment]
@christian-bromann  sorry, today ,i am try,but can't fix it.  i can't understand why 
> childProcess.on('exit' (...args) => {})
receive 
args = [ null, 'SIGKILL' ]
,,,,,
i am try to listen childProcess.on('SIGKILL',   but nothing to happen...

**Comment by mgrybyk** [comment]
ok, I know how to fix it, will do PR soon

**Comment by MaheshGooner** [comment]
Doesn't look like it is fixed. i still have the same issue with below setup

    "@wdio/cli": "5.7.15",
    "@wdio/local-runner": "5.7.15",
    "@wdio/selenium-standalone-service": "^5.7.8",
    "wdio-cucumber-framework": "^2.2.8"

**Comment by sup-engineer** [comment]
still seeing the same issue
`    @wdio/cli": "^5.11.0",
    "@wdio/config": "^5.11.0",
    "@wdio/cucumber-framework": "^5.11.0",
    "@wdio/local-runner": "^5.11.0",`

**Comment by mgrybyk** [comment]
@MaheshGooner @sup-engineer please provide with steps to reproduce .

**Comment by michael-confiant** [comment]
@mgrybyk 
used this project to reproduce it:
https://github.com/webdriverio/cucumber-boilerplate
added 
```
    debug: true,
    execArgv: ['--inspect-brk=127.0.0.1:5859'],
```
to wdio.BUILD.conf.js
my launch.json is:
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "wdio",
      "port": 5859,
      "cwd": "${workspaceFolder}",
      "program": "${workspaceFolder}/node_modules/.bin/wdio",
      "args": [
        "wdio.BUILD.conf.js",
        "--spec=${relativeFile}"
      ],
      "internalConsoleOptions": "neverOpen",
      "console": "externalTerminal",
    },
  ]
}
```
npm install
npm run local-webserver
then focus on any feature file and start debugging

The issue is still actual
![image](https://user-images.githubusercontent.com/51997249/62617669-0c1d1980-b91b-11e9-9636-d822a165909b.png)

**Comment by mgrybyk** [comment]
Remove execArgv and port

**Comment by michael-confiant** [comment]
> Remove execArgv and port

@mgrybyk then I can't use breakpoints

**Comment by mgrybyk** [comment]
Yeah, you need to add auto attach to child processes

**Comment by michael-confiant** [comment]
> Yeah, you need to add auto attach to child processes

VS code says 'Property autoAttachChildProcess is not allowed.'

**Comment by mgrybyk** [comment]
Add `debug: true` to wdio conf, remove execArgv, here is launch.json snippet 

```
    {
      "name": "single test,
      "env": {},
      "type": "node",
      "request": "launch",
      "args": [
        "wdio.BUILD.conf.js",
        "--spec",
        "${file}",
      ],
      "cwd": "${workspaceFolder}",
      "autoAttachChildProcesses": true,
      "program": "${workspaceRoot}/node_modules/.bin/wdio",
      "console": "integratedTerminal"
    },
```

**Comment by michael-confiant** [comment]
Ah, so the correct property to add to launch.json is "autoAttachChildProcesses": true. Now it works! Thanks @mgrybyk for the help!

**Comment by sup-engineer** [comment]
Hi @mgrybyk ,
I am using the webdriverIO - cucumberJS project (with some changes) to try this out.

I followed your recommendation. I get the correct 'pass' report in the terminal now. However, the debugger is now failing to connect to the runtime process.
![image](https://user-images.githubusercontent.com/20064961/62724339-ac9e3700-ba0a-11e9-8ff8-f92f19295899.png)
(after execution of the launch.json, the wdio command executed in the terminal to run the spec file  has '--inspect-brk=43964' appended which I believe is the correct behaviour)

The launch.json I have used is as follows:
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

      {
        "name": "single test",
        "env": {},
        "type": "node",
        "request": "launch",
        "cwd": "${workspaceFolder}",
        "autoAttachChildProcesses": true,
        //"program": "${workspaceFolder}/node_modules/.bin/wdio",
        "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/wdio",
        "runtimeArgs": [
          "wdio.conf.js",
          "--spec=${relativeFile}"
        ],
        "timeout": 60000,
        "console": "integratedTerminal"
      },

    ]
  }`
The "program" does not work for me for some reason and hence I ended up using the "runtimeExecutable" with "runtimeArgs"

I have used the following 'wdio.conf.js' file:
`const path = require('path');

exports.config = {
    debug: true,
    // ==================
    // Specify Test Files
    // ==================
    // Define which test specs should run. The pattern is relative to the
    // directory from which `wdio` was called. Notice that, if you are calling
    // `wdio` from an NPM script (see https://docs.npmjs.com/cli/run-script)
    // then the current working directory is where your package.json resides, so
    // `wdio` will be called from there.
    //
    specs: [
        './src/features/test/*.feature',
    ],
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    //
    // ============
    // Capabilities
    // ============
    // Define your capabilities here. WebdriverIO can run multiple capabilities
    // at the same time. Depending on the number of capabilities, WebdriverIO
    // launches several test sessions. Within your capabilities you can
    // overwrite the spec and exclude options in order to group specific specs
    // to a specific capability.
    //
    // First, you can define how many instances should be started at the same
    // time. Let's say you have 3 different capabilities (Chrome, Firefox, and
    // Safari) and you have set maxInstances to 1; wdio will spawn 3 processes.
    // Therefore, if you have 10 spec files and you set maxInstances to 10, all
    // spec files will get tested at the same time and 30 processes will get
    // spawned. The property handles how many capabilities from the same test
    // should run tests.
    //
    maxInstances: 1,
    //
    // If you have trouble getting all important capabilities together, check
    // out the Sauce Labs platform configurator - a great tool to configure your
    // capabilities: https://docs.saucelabs.com/reference/platforms-configurator
    //
    capabilities: [{
        // maxInstances can get overwritten per capability. So if you have an
        // in-house Selenium grid with only 5 firefox instance available you can
        // make sure that not more than 5 instance gets started at a time.
        maxInstances: 5,
        //
        browserName: 'chrome',
    }],
    //
    // ===================
    // Test Configurations
    // ===================
    // Define all options that are relevant for the WebdriverIO instance here
    //
    // Level of logging verbosity: silent | verbose | command | data | result |
    // error
    logLevel: 'trace',
    //
    // Enables colors for log output.
    coloredLogs: true,
    //
    // Saves a screenshot to a given path if a command fails.
    screenshotPath: './errorShots/',
    //
    // Set a base URL in order to shorten getUrl command calls. If your getUrl
    // parameter starts with "/", then the base getUrl gets prepended.
    baseUrl: 'http://localhost:8080',
    //
    // Default timeout for all waitFor* commands.
    waitforTimeout: 10000,
    //
    // Default timeout in milliseconds for request
    // if Selenium Grid doesn't send response
    connectionRetryTimeout: 90000,
    //
    // Default request retries count
    connectionRetryCount: 3,
    //
    // Initialize the browser instance with a WebdriverIO plugin. The object
    // should have the plugin name as key and the desired plugin options as
    // properties. Make sure you have the plugin installed before running any
    // tests. The following plugins are currently available:
    // WebdriverCSS: https://github.com/webdriverio/webdrivercss
    // WebdriverRTC: https://github.com/webdriverio/webdriverrtc
    // Browserevent: https://github.com/webdriverio/browserevent
    // plugins: {
    //     webdrivercss: {
    //         screenshotRoot: 'my-shots',
    //         failedComparisonsRoot: 'diffs',
    //         misMatchTolerance: 0.05,
    //         screenWidth: [320,480,640,1024]
    //     },
    //     webdriverrtc: {},
    //     browserevent: {}
    // },
    //
    // Test runner services
    // Services take over a specific job you don't want to take care of. They
    // enhance your test setup with almost no effort. Unlike plugins, they don't
    // add new commands. Instead, they hook themselves up into the test process.
    services: ['selenium-standalone'],
    outputDir: path.join(__dirname, 'logs'),
    //
    // Framework you want to run your specs with.
    // The following are supported: Mocha, Jasmine, and Cucumber
    // see also: http://webdriver.io/guide/testrunner/frameworks.html
    //
    // Make sure you have the wdio adapter package for the specific framework
    // installed before running any tests.
    framework: 'cucumber',
    //
    // Test reporter for stdout.
    // The only one supported by default is 'dot'
    // see also: http://webdriver.io/guide/testrunner/reporters.html
    reporters: ['spec'],
    //
    // If you are using Cucumber you need to specify the location of your step
    // definitions.
    cucumberOpts: {
        // <boolean> show full backtrace for errors
        backtrace: false,
        // <string[]> module used for processing required features
        requireModule: ['@babel/register'],
        // <boolean< Treat ambiguous definitions as errors
        failAmbiguousDefinitions: true,
        // <boolean> invoke formatters without executing steps
        // dryRun: false,
        // <boolean> abort the run on first failure
        failFast: false,
        // <boolean> Enable this config to treat undefined definitions as
        // warnings
        ignoreUndefinedDefinitions: false,
        // <string[]> ("extension:module") require files with the given
        // EXTENSION after requiring MODULE (repeatable)
        name: [],
        // <boolean> hide step definition snippets for pending steps
        snippets: true,
        // <boolean> hide source uris
        source: true,
        // <string[]> (name) specify the profile to use
        profile: [],
        // <string[]> (file/dir) require files before executing features
        require: [
            './src/steps/given.js',
            './src/steps/then.js',
            './src/steps/when.js',
            // Or search a (sub)folder for JS files with a wildcard
            // works since version 1.1 of the wdio-cucumber-framework
            // './src/**/*.js',
        ],
        // <string> specify a custom snippet syntax
        snippetSyntax: undefined,
        // <boolean> fail if there are any undefined or pending steps
        strict: true,
        // <string> (expression) only execute the features or scenarios with
        // tags matching the expression, see
        // https://docs.cucumber.io/tag-expressions/
        tagExpression: 'not @Pending',
        // <boolean> add cucumber tags to feature or scenario name
        tagsInTitle: false,
        // <number> timeout for step definitions
        timeout: 20000,
    },

    //
    // =====
    // Hooks
    // =====
    // WebdriverIO provides several hooks you can use to interfere with the test
    // process in order to enhance it and to build services around it. You can
    // either apply a single function or an array of methods to it. If one of
    // them returns with a promise, WebdriverIO will wait until that promise got
    // resolved to continue.
    //
    // Gets executed once before all workers get launched.
    // onPrepare: function onPrepare(config, capabilities) {
    // },
    //
    // Gets executed before test execution begins. At this point you can access
    // all global variables, such as `browser`. It is the perfect place to
    // define custom commands.
    before: function before() {
        /**
         * Setup the Chai assertion framework
         */
        const chai = require('chai');

        global.expect = chai.expect;
        global.assert = chai.assert;
        global.should = chai.should();
    },
    //
    // Hook that gets executed before the suite starts
    // beforeSuite: function beforeSuite(suite) {
    // },
    //
    // Hook that gets executed _before_ a hook within the suite starts (e.g.
    // runs before calling beforeEach in Mocha)
    // beforeHook: function beforeHook() {
    // },
    //
    // Hook that gets executed _after_ a hook within the suite starts (e.g. runs
    // after calling afterEach in Mocha)
    // afterHook: function afterHook() {
    // },
    //
    // beforeSession: function beforeTest() {
    // },
    //
    // Runs before a WebdriverIO command gets executed.
    // beforeCommand: function beforeCommand(commandName, args) {
    // },
    //
    // Runs after a WebdriverIO command gets executed
    // afterCommand: function afterCommand(commandName, args, result, error) {
    // },
    //
    // Function to be executed after a test (in Mocha/Jasmine) or a step (in
    // Cucumber) starts.
    // afterTest: function afterTest(test) {
    // },
    //
    // Hook that gets executed after the suite has ended
    // afterSuite: function afterSuite(suite) {
    // },
    //
    // Gets executed after all tests are done. You still have access to all
    // global variables from the test.
    // after: function after(result, capabilities, specs) {
    // },
    //
    // Gets executed after all workers got shut down and the process is about to
    // exit. It is not possible to defer the end of the process using a promise.
    // onComplete: function onComplete(exitCode) {
    // }
};`

**Comment by mgrybyk** [comment]
I think this is some windows related issue

**Comment by mgrybyk** [comment]
ah, we should change program to `"program": "${workspaceRoot}/node_modules/@wdio/cli/bin/wdio.js",`

**Comment by mgrybyk** [comment]
```
{
  "name": "single test,
  "env": {},
  "type": "node",
  "request": "launch",
  "args": [
    "wdio.BUILD.conf.js",
    "--spec",
    "${file}",
  ],
  "cwd": "${workspaceFolder}",
  "autoAttachChildProcesses": true,
  "program": "${workspaceRoot}/node_modules/@wdio/cli/bin/wdio.js",
  "console": "integratedTerminal"
},
```
