### ISSUE TITLE
Not taking screenshots on test failure on WebdriverIO v5

### ISSUE THREAD

**Issue by carlos-gva** [webdriverio/webdriverio#3192]
On previous version (v4) a screenshot was automatically taken on test failure, now it doesn't.

I also noticed that when generating the new **wdio.conf.js**, it didn't ask for that config, but the Getting Started Guide says it should.

```
Q: In which directory should screenshots gets saved if a command fails?
A: ./errorShots/ (just press enter)
```

**Comment by christian-bromann** [comment]
This should be updated in the docs then. In v4 a screenshot was only taken when a WebDriver request failed.

**Comment by carlos-gva** [comment]
@christian-bromann Thanks!
But now I'm a bit confused. Do you mean that in this **v5** we won't have that feature by default?

**Comment by carlos-gva** [comment]
@christian-bromann
Understood. My mistake.
Many thanks! 🙏
