### ISSUE TITLE
browser.getUrl() is missing

### ISSUE THREAD

**Issue by tbradley-sans** [webdriverio/webdriverio#3194]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.0.3
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.14.1
 - **NPM version:** 6.4.1
 - **Browser name and version:** irrelevant
 - **Platform name and version:** irrelevant
 - **Additional wdio packages used (if applicable):** irrelevant

**Describe the bug**
The webdriverio code and documentation and unit tests are in disagreement about how to get the current URL of the browser. [The code](https://github.com/webdriverio/webdriverio/blob/367f53e826362f83fef41cf1d8c3abe388e0c58f/packages/webdriverio/src/commands/browser/url.js) doesn't appear to implement such a command. But the documentation there says the ```url``` command is used to "load or get the URL of the browser". When I try to use ```url()``` without an argument, I get this error:

```browser.getUrl is not a function```

Similarly, there is no unit test for either getUrl() or for url(). The tests only check ```url``` with a string argument.

**To Reproduce**

Use the code in the example comments in url.js...

```
// navigate to a new URL
browser.url('https://webdriver.io');
// receive url
console.log(browser.getUrl()); // outputs: "https://webdriver.io"
```

...and then try to run it using the ```wdio``` test runner.

**Expected behavior**

I don't know what to expect. If you believe the documentation, you should be able to call url() to get the current URL. If you believe the example code, you should be able to call getUrl() to get the current URL.

Either way, the documentation, the example, and the implementation should all match. And there should be a unit test to cover this.

**Additional context**

See also: https://github.com/webdriverio/webdriverio/issues/1240 and https://github.com/webdriverio/webdriverio/pull/3176

**Comment by jlchereau** [comment]
Use browser.getCurrentUrl() with v5.0.3

**Comment by christian-bromann** [comment]
The command will be re-established with the next version release, see #3176
