### ISSUE TITLE
Unable to run basic  getting started script

### ISSUE THREAD

**Issue by maruthisunil** [webdriverio/webdriverio#3204]
i am trying  setup using  https://webdriver.io/docs/gettingstarted.html

**Environment (please complete the following information):**
 - **WebdriverIO version:** webdriverio@^4.14.1
 - **Mode:** [Standalone WINDOWS OS]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:** [8.15]
 - **NPM version:** [e6.4.1]
 - **Browser name and version:** [firefox 64]
 - **Platform name and version:** [Windows 10
![nodejserror](https://user-images.githubusercontent.com/12495916/50537634-4bff6f80-0b88-11e9-9c47-41d29f75b709.jpg)
]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
Runing node test.js which contains below code:---------------------------
var webdriverio = require('webdriverio');
var options = {
    desiredCapabilities: {
        browserName: 'firefox'
    }
};

webdriverio
    .remote(options)
    .init()
    .url('http://www.google.com')
    .getTitle().then(function(title) {
        console.log('Title was: ' + title);
    })
    .end()
    .catch(function(err) {
        console.log(err);
    });
-------------------------------------------
 Getting below error

TypeError: Cannot read property 'url' of undefined
    at C:\Users\xxxx\Downloads\wdioPOC-master\wdioPOC-master\test123\test1.js:12:19
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

**Comment by christian-bromann** [comment]
If you use WebdriverIO v4 please read the v4 docs: http://v4.webdriver.io/guide.html
