### ISSUE TITLE
Opening default browser profile

### ISSUE THREAD

**Issue by brettm523** [webdriverio/webdriverio#321]
I'm trying to test a page that uses some browser extensions and plugins. However, the browser instance that Webdriverio opens has all extensions removed by default and my tests fail. In Chrome I've tried passing --user-data-dir to chromeOptions to load the default profile, but while chrome://version/ verifies that the profile loaded, there seem to be a bunch of command line options that override that and my extensions are still gone. In Firefox my extensions are removed and all plugins are set to "Ask to Activate". Is there a workaround for this?

**Comment by christian-bromann** [comment]
Closing as this is more an issue of Selenium then WebdriverIO

**Comment by USTAADCOM** [comment]
Hi, @matthieugayon You mentioned a solution to add an extension to the default browser while working with the Chrome driver. Could you please give me a suggestion on how to do this? Below is my code load default Chrome profile and it's working.

from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from webdriver_manager.chrome import ChromeDriverManager
import undetected_chromedriver as uc
import time
# How to get default browser path on Windows, macOS, Ubantu

# On Windows: C:\Users\<YourUsername>\AppData\Local\Google\Chrome\User Data
# On macOS: /Users/<YourUsername>/Library/Application Support/Google/Chrome
# On Ubuntu/Linux: /home/<YourUsername>/.config/google-chrome

import undetected_chromedriver as uc
options = uc.ChromeOptions()
user_data_dir = '/home/aamir/.config/google-chrome/Default'
options.add_argument('--no-default-browser-check')
options.add_argument('--profile-directory=Default')

browser = uc.Chrome(
    driver_executable_path=ChromeDriverManager(driver_version = "127.0.6533.72").install(),
    user_data_dir = user_data_dir,
    options= options,
    desired_capabilities=DesiredCapabilities.CHROME
    )
time.sleep(6)
browser.get("https://mail.google.com/mail/u/0/?tab=rm&ogbl#inbox")
time.sleep(30)
