### ISSUE TITLE
collapse menu does not respond to click

### ISSUE THREAD

**Issue by LayMuiToh** [webdriverio/webdriverio#3223]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 4.14.1
 - **Mode:** WDIO Testrunner]
 - **If WDIO Testrunner, running sync
 - **Node.js version:** 9.1.0
 - **NPM version:** 6.4.1
 - **Browser name and version:**NA
 - **Platform name and version:** iOS 12.1
 - **Additional wdio packages used (if applicable): NA
**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**

**To Reproduce**

[Include code or an example repository that can easily be set up]
module.exports = () => {
 describe('Menu test', () => {
    it('should able to select collapse menu icon and go to the Menu page', () => {
        Main.menu.waitForVisible() &&
        Main.menu.click();

*Expected behavior**
Able to click on the selector (element) 
Main.menu is defined in Menu.page.js
get menu() { return browser.element(SELECTORS.MENU); }

const SELECTORS = {
   
    MENU: '~menu', 
   
};

**Log**
11:47:19]  COMMAND	POST 	 "/wd/hub/session/f1403b6f-6a08-4f38-97a5-c0882f9a93c2/element"
[11:47:19]  DATA		{"using":"accessibility id","value":"menu"}
[11:47:20]  RESULT		{"ELEMENT":"8A000000-0000-0000-B40C-000000000000"}
[11:47:20]  COMMAND	POST 	 "/wd/hub/session/f1403b6f-6a08-4f38-97a5-c0882f9a93c2/element/8A000000-0000-0000-B40C-000000000000/click"
[11:47:20]  DATA		{}

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
According to the logs the click was executed. I don’t see a bug here.

**Comment by LayMuiToh** [comment]
Yes, but the screen didn't appear. there is no response on the screen

**Comment by LayMuiToh** [comment]
@christian-bromann I saw this in the appium.log
^[[35m[HTTP]^[[39m ^[[90m{"using":"accessibility id","value":"menu"}^[[39m
[debug] ^[[35m[MJSONWP]^[[39m Calling AppiumDriver.findElement() with args: ["accessibility id","menu","9682b387-b283-4e02-8604-3c6d9cc7273b"]
[debug] ^[[35m[XCUITest]^[[39m Executing command 'findElement'
[debug] ^[[35m[BaseDriver]^[[39m Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] ^[[35m[BaseDriver]^[[39m Waiting up to 0 ms for condition
[debug] ^[[35m[JSONWP Proxy]^[[39m Matched '/element' to command name 'findElement'
[debug] ^[[35m[JSONWP Proxy]^[[39m Proxying [POST /element] to [POST http://localhost:8100/session/B596940B-035D-4D77-BF47-14558F53F4AB/element] with body: {"using":"accessibility id","value":"menu"}
[debug] ^[[35m[JSONWP Proxy]^[[39m Got response with status 200: {"value":{"using":"accessibility id","value":"menu","description":"unable to find an element"},"sessionId":"B596940B-035D-4D77-BF47-14558F53F4AB","status":7}
[debug] ^[[35m[MJSONWP]^[[39m Matched JSONWP error code 7 to NoSuchElementError
[debug] ^[[35m[MJSONWP]^[[39m Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[debug] ^[[35m[MJSONWP]^[[39m     at XCUITestDriver.callee$0$0$ (/Users/tohlaymui/.nvm/versions/node/v9.1.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:130:13)

**Comment by wswebcreation** [comment]
@LayMuiToh 

First of all please use proper markdown, so it makes it easier to read.
Secondly, the click has been executed on the first log you provided, but it could be that the iOS app hasn't seen this click. This has to do with _Appium_, iOS, your app and the way they handle the clicks. This has been explained in [this Appium Pro Newsletter](https://appiumpro.com/editions/36).

The second log is about trying to find an element that is not there. Please wait for the element or handle it properly.

Last but not least, the last question is more of a usage question, please feel free to ask those questions on our Gitter channel instead of in an issue.

**Comment by LayMuiToh** [comment]
@wswebcreation I added nativeWebTap: true at the capabilities setting at wdio.conf.js, it didn't fix the problem.
I change my usage to use mobile: tap command
if (Main.menu.waitForVisible()) {
        //   Main.menu.click();
        const menu_x = browser.getLocation('~menu', 'x');
        const menu_y = browser.getLocation('~menu', 'y');
        browser.execute('mobile: tap', {element: Main.menu, x: menu_x, y: menu_y});

it didn't respond to the tap action neither. I don't see any issue on the appium.log

**Comment by LayMuiToh** [comment]
https://gist.github.com/LayMuiToh/6c5c5c734dc03cc6f420281b58e81ef3
