### ISSUE TITLE
Ability to use custom attributes to select elements

### ISSUE THREAD

**Issue by dimirey** [webdriverio/webdriverio#3228]
**Is your feature request related to a problem? Please describe.**
In the previous version of webdriverio (4.x.x) I was able to select elements using custom attributes. With the new version (5.x.x) I am unable to.

**Describe the solution you'd like**
I would like to be able to select the following element:
```
<div name="firstName"> </div> 
```
using the following command: 

```
$('[name="firstName"]')
```

**Comment by BorisOsipov** [comment]
> With the new version (5.x.x) I am unable to.

why? what error do you recieve?

**Comment by dimirey** [comment]
> > With the new version (5.x.x) I am unable to.
> 
> why? what error do you recieve?

InvalidSelectorStrategy

**Comment by dimirey** [comment]
believe this is a duplicate of 2780 
https://github.com/webdriverio/webdriverio/issues/2780
