### ISSUE TITLE
element.waitForDisplayed(true) does not throw error if element remains visible

### ISSUE THREAD

**Issue by jdavis61** [webdriverio/webdriverio#3229]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.1.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.14.2
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome 71
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/cli, @wdio/mocha-framework, @wdio/selenium-standalone-service, @wdio/spec-reporter, @wdio/sync 

**Config of WebdriverIO**
The wdio config is found at https://gist.github.com/jdavis61/885f827a27cea69b8923420ea68231e5#file-wdio-conf-js.

**Describe the bug**
Using waitForVisible with reverse = true and without timeout does not throw an error after the default timeout has been reached. 

For example  `$('.heading).waitForVisible(true)` will not throw an error if `$('.heading)` is not hidden after 10000 ms.

**To Reproduce**

1. Download the example [gist](https://gist.github.com/jdavis61/885f827a27cea69b8923420ea68231e5) by running `git clone https://gist.github.com/885f827a27cea69b8923420ea68231e5.git v5example`
2. cd v5example
3. npm install
4. npm run test
5. The test with `assert.throws(() => { $('.heading').waitForDisplayed(true)}, Error, 'Fail exception not thrown.');` does not throw an exception and fails. The error message is `Missing expected exception (Error): Fail exception not thrown.`. 

The test should pass because $('.heading') is always visible on the http://the-internet.herokuapp.com/ home page.

**Expected behavior**
`$('.heading').waitForVisible(true)` should have the same result as `$('.heading').waitForVisible(10000, true)`. 

**Log**
The log files for the example gist are found at https://gist.github.com/jdavis61/6fe8068a3e7fc20cf043d3e0313990d9

**Comment by abjerstedt** [comment]
@jdavis61 I'm closing this as you were running the code wrong:
https://webdriver.io/docs/api/element/waitForDisplayed.html

If you read the documents you aren't actually telling it to do a negative test as true should be the 3rd parameter.
element.waitForDisplayed(undefined,undefined,true) would tell it to negative test.

**Comment by jdavis61** [comment]
Hi @abjerstedt I have one more question for you about the docs. Should all optional parameters be passed as null?

**Comment by abjerstedt** [comment]
@jdavis61... nope undefined for defaults

**Comment by abjerstedt** [comment]
@jdavis61 I apologize... its waitForDisplayed(undefined,true). v5 removed the interval param.

**Comment by jdavis61** [comment]
Hi @abjerstedt for the follow up response. I also confirmed in v4 `element.waitForVisible(true)` does not work at all (as you mentioned earlier). Thank you for calling this out, I always thought `element.waitForVisible(true)` worked for whatever reason.
