### ISSUE TITLE
Custom Command without Callback

### ISSUE THREAD

**Issue by ak5** [webdriverio/webdriverio#323]
Hi!

I am trying to create a command without a callback, but it doesn't chain like the built in methods for some reason.

I got it running like in the example here: https://github.com/webdriverio/webdriverio#adding-custom-commands, now I just need to get rid of the callback. I tried simply returning the this object, to no avail.

The method I want to implement is used to wait until a certain elements text matches a regex. There might be something better, but basically my idea was to continuously poll elements matching selector until at least one matches regex. The next command in the chain will only execute once this method exits successfully. Please let me know if what I am trying to do can be solved more simply.

Thanks in advance.

**Comment by sean-hill** [comment]
I was wondering how you'd do this with v3 and promises. Thanks!

**Comment by christian-bromann** [comment]
in `v3` we have a new nice command called waitUntil. It expects a function that returns a promise. Once that promise is fulfilled it continues with the queue. It executes the function every 500ms or so until a timeout got reached. All waitForX commands are using that command. As far as I can see `waitUntilElementMatchesRegex` is pretty much the same as `waitForExist`, so just use that command!
