### ISSUE TITLE
TypeError: Cannot read property 'browserName' of undefined

### ISSUE THREAD

**Issue by nkrishna79** [webdriverio/webdriverio#3232]
CodeceptJS v2.0.1
"webdriverio": "5.2.0"
When running tests via npm run codeceptjs, i get the following error 
 × "after each" hook: codeceptjs.after for "Feature flag is ON @reg82_1" in 6ms
    [1] Error | TypeError: Cannot read property 'browserName' of undefined
TypeError: Cannot read property 'browserName' of undefined
    Emitted | suite.after ([object Object])

-- FAILURES:

  1) Build new Registration form @newregistration
       "after each" hook: codeceptjs.after for "Feature flag is ON @reg82_1":
     Cannot read property 'browserName' of undefined
  ypeError: Cannot read property 'browserName' of undefined
      at WebDriver._after (node_modules\codeceptjs\lib\helper\WebDriver.js:389:71)
      at recorder.add (node_modules\codeceptjs\lib\listener\helpers.js:21:69)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)

codecept config
*****************
{
  "output": "./output",
  "helpers": {
    "WebDriver": {
      "url": "http://localhost",
      "smartWait": 5000,
      "browser": "chrome",
      "restart": false,
      "windowSize": "maximize",
      "timeouts": {
        "script": 60000,
        "page load": 10000
      }
    }
  },
  "include": {
    "I": "./steps_file.js",
    
  },
  "mocha": {
    "reporterOptions": {
      "reportDir": "output"
    }
  },
  "bootstrap": false,
  "teardown": null,
  "hooks": [],
  "gherkin": {
    "features": "./features/*.feature",
    "steps": [
      "./step_definitions/steps.js"
    ]
  },
  "plugins": {
    "screenshotOnFail": {
      "enabled": true
    },
    "allure": {
      "outputDir": "output",
      "enabled": true
    }
  },
  "multiple": {
    "parallel": {
      "chunks": 10
    }
  },
  "tests": "./**/*_test.js",
  "timeout": 10000,
  "name": "codeceptwdio"
}

**Comment by christian-bromann** [comment]
This looks like an issue with codeceptjs, please create an issue in that project. Thanks!
