### ISSUE TITLE
How to use webdriverio via proxy?

### ISSUE THREAD

**Issue by Shtirlits** [webdriverio/webdriverio#324]
Is there any way I can use webdriverio via proxy, which looks like `username:password@ip:port` ?

**Comment by vinnitu** [comment]
phantom js works with

```coffeescript
options =
  desiredCapabilities:
    browserName: "phantomjs"
    "phantomjs.cli.args": [
      "--proxy-type=socks5"
      "--proxy=localhost:1080"
    ]
```

but how to set up proxy socks5 for chromdriver?

I have tryid such variants

```coffeescript
options =
  desiredCapabilities:
    browserName: "chrome"
    
    # proxy:
    #   proxyType: "manual"
    #   socksProxy: "localhost:1080"

    # "chrome.cli.args": [
    #   "--proxy-type=socks5"
    #   "--proxy=localhost:1080"
    # ]

    # chromeOptions:
    #   args: [
    #     "--proxy-type=socks5"
    #     "--proxy=localhost:1080"
    #   ]

```

without result ((

**Comment by sean-hill** [comment]
@christian-bromann Your solution didn't work, I got this huge error when I tried it.



	     Callstack:
	     -> init()
	]
	  message: 'RuntimeError\n     Problem: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">\n<html><head>\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\n<title>ERROR: The requested URL could not be retrieved</title>\n<style type="text/css"></style>\n</head><body id=ERR_INVALID_URL>\n<div id="titles">\n<h1>ERROR</h1>\n<h2>The requested URL could not be retrieved</h2>\n</div>\n<hr>\n\n<div id="content">\n<p>The following error was encountered while trying to retrieve the URL: <a href="/wd/hub/session">/wd/hub/session</a></p>\n\n<blockquote id="error">\n<p><b>Invalid URL</b></p>\n</blockquote>\n\n<p>Some aspect of the requested URL is incorrect.</p>\n\n<p>Some possible problems are:</p>\n<ul>\n<li><p>Missing or incorrect access protocol (should be <q>http://</q> or similar)</p></li>\n<li><p>Missing hostname</p></li>\n<li><p>Illegal double-escape in the URL-Path</p></li>\n<li><p>Illegal character in hostname; underscores are not allowed.</p></li>\n</ul>\n\n<p>Your cache administrator is <a href="mailto:webmaster?subject=CacheErrorInfo%20-%20ERR_INVALID_URL&amp;body=CacheHost%3A%20cloud-server-12%0D%0AErrPage%3A%20ERR_INVALID_URL%0D%0AErr%3A%20%5Bnone%5D%0D%0ATimeStamp%3A%20Tue,%2014%20Apr%202015%2017%3A09%3A32%20GMT%0D%0A%0D%0AClientIP%3A%2010.182.129.6%0D%0A%0D%0AHTTP%20Request%3A%0D%0A%0D%0A%0D%0A">webmaster</a>.</p>\n<br>\n</div>\n\n<hr>\n<div id="footer">\n<p>Generated Tue, 14 Apr 2015 17:09:32 GMT by cloud-server-12 (squid/3.3.8)</p>\n\n</div>\n</body></html>\n\u001b[1;30m\n\n     Callstack:\n     -> init()\n',
	  name: 'RuntimeError',
	  hasCallStack: true }

**Comment by christian-bromann** [comment]
@sean-hill have you tried @vinnitu example?

**Comment by sean-hill** [comment]
Hey there @christian-bromann, thanks for the quick response!

So I've tried this:

    desiredCapabilities: { 
        browserName: 'chrome'
        , proxy: {
        	proxyType: 'manual'
        	, httpProxy: 'http://username:password@domain.com:port'
        }
    } 

But it made no difference when selenium hit the server I am testing against. The IP was still my local machine's IP.

**Comment by sean-hill** [comment]
Hey @christian-bromann,

I've tried following the instructions [here](https://code.google.com/p/selenium/wiki/DesiredCapabilities#Object_structures), but my IP is still not being masked with the following options:

    var options = {
        desiredCapabilities: { 
            browserName: 'chrome'
             , proxy: {
                proxyType: 'manual'
                , httpProxy: 'http://username:password@domain.com:port'
                , sslProxy: 'http://username:password@domain.com:port'
            }
        } 
    };

**Comment by christian-bromann** [comment]
@sean-hill I don't actually know how to configure Selenium to make it working using manual proxy settings. I can remember that I've got a simple http proxy working though. I checked the source code and it seems that the proxy type should be uppercase characters. Could you try:

```js
    var options = {
        desiredCapabilities: { 
            browserName: 'chrome'
             , proxy: {
                proxyType: 'manual'
                , httpProxy: 'http://username:password@domain.com:port'
                , sslProxy: 'http://username:password@domain.com:port'
            }
        } 
    };
```

**Comment by christian-bromann** [comment]
ahh never-mind they make it uppercase

**Comment by sean-hill** [comment]
Haha, yeah, just tried it, same deal. I've honestly tried a hundred ways to get selenium + webdriverio to use my proxy server, but I've had no luck :frowning:

**Comment by sean-hill** [comment]
Where are you "checking the source code"?

**Comment by christian-bromann** [comment]
I was looking [here](https://code.google.com/p/selenium/source/browse/py/selenium/webdriver/common/proxy.py?spec=svn4a6e28b5ed4270780a181b739c8d1459b9d2bece&name=4a6e28b5ed42&r=4a6e28b5ed4270780a181b739c8d1459b9d2bece).
Have you tried it with other libraries? Since these information are within the desiredCapabilities I doubt that it has something to do with WebdriverIO and is rather a problem caused by missing documentations by Selenium

**Comment by christian-bromann** [comment]
According to the Python docs:

```py
from selenium import webdriver

PROXY = "localhost:8080"

# Create a copy of desired capabilities object.
desired_capabilities = webdriver.DesiredCapabilities.INTERNETEXPLORER.copy()
# Change the proxy properties of that copy.
desired_capabilities['proxy'] = {
    "httpProxy":PROXY,
    "ftpProxy":PROXY,
    "sslProxy":PROXY,
    "noProxy":None,
    "proxyType":"MANUAL",
    "class":"org.openqa.selenium.Proxy",
    "autodetect":False
}

# you have to use remote, otherwise you'll have to code it yourself in python to 
# dynamically changing the system proxy preferences
driver = webdriver.Remote("http://localhost:4444/wd/hub", desired_capabilities)
```
it seems that you can pass in username + password in your proxy uri

**Comment by christian-bromann** [comment]
proxy uris only consist of hostname + port, you could try to use `socksUsername` and `socksPassword`

**Comment by christian-bromann** [comment]
```js
    var options = {
        desiredCapabilities: { 
            browserName: 'chrome'
             , proxy: {
                proxyType: 'MANUAL'
                , httpProxy: 'domain.com:port'
                , sslProxy: '@domain.com:port'
                , socksUsername: 'username'
                , socksPassword: '**************'
            }
        } 
    };
```

**Comment by sean-hill** [comment]
YOU'RE A GENIUS!!! THAT TOTALLY WORKEDDDDDDDD!!! THANK YOU THANK YOU!!! :D :D :D :D :D

**Comment by christian-bromann** [comment]
:+1: awesome!

**Comment by sean-hill** [comment]
Hey everyone,

By the way, the `socksUsername` and `socksPassword` wasn't what fixed it for me. It was removing `http://username:password` from the `httpProxy` and `sslProxy` params. I also had to login into my proxy provider, which in this case was Proxymesh, and whitelist the IP's of the my machines. This is what solved it! 

Final example: 

	// Selenium

	var webdriverio = require('webdriverio');

	module.exports = function(isMobile) {

		var options = {
		    desiredCapabilities: { 
		        browserName: 'chrome'
		        , proxy: {
		            proxyType: 'MANUAL'
		            , httpProxy: 'us.proxymesh.com:12345'
		            , sslProxy: 'us.proxymesh.com:12345'
		        }
		    } 
		};

		if (isMobile) {
			options.desiredCapabilities.chromeOptions = {
	            args: ['use-mobile-user-agent', 'user-agent=Mozilla/5.0 (iPhone; CPU iPhone OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A334 Safari/7534.48.3']
	        }
		}

		return webdriverio.remote(options);
		
	};

**Comment by christian-bromann** [comment]
@sean-hill thanks for sharing :+1:

**Comment by intergleam** [comment]
hm, just tried and it doesn't work. a window pops up asking for credentials

**Comment by Albertmoiseev** [comment]
@intergleam Unfortunetely, the same... 

Who anybody managed to solve the authentication in http proxy with login/password?

**Comment by intergleam** [comment]
the only way is to write an extension and populate it with password. But it works only in C# for me

**Comment by alykoshin** [comment]
If it may help somebody, I made a package [selenium-chrome-proxy-plugin](https://www.npmjs.com/package/selenium-chrome-proxy-plugin) which builds Chrome plugin for Selenium with proxy basic authorization (though idea is not mine, it is based on https://github.com/RobinDev/Selenium-Chrome-HTTP-Private-Proxy).

**Comment by povtasci** [comment]
Hey anyone :)

I want to open this topic again - has anyone solved this issue?

"a window pops up asking for credentials"
