### ISSUE TITLE
WebDriver crashing when using Appium node with grid

### ISSUE THREAD

**Issue by xlenz** [webdriverio/webdriverio#3252]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.2.2
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.15.0
 - **NPM version:** 6.5.0
 - **Browser name and version:** N/A
 - **Platform name and version:** Mac
 - **Additional wdio packages used (if applicable):** 
    "@types/mocha": "^5.2.5",
    "@types/node": "^10.12.18",
    "@types/webdriverio": "^4.13.1",
    "@wdio/cli": "^5.2.2",
    "@wdio/dot-reporter": "^5.2.2",
    "@wdio/local-runner": "^5.2.2",
    "@wdio/mocha-framework": "^5.2.2",
    "@wdio/sync": "^5.2.2",
    "ts-node": "^7.0.1",
    "tsconfig-paths": "^3.7.0",
    "typescript": "^3.2.2"

**Config of WebdriverIO**
```exports.config = {
  hostname: '127.0.0.1',
  port: 4441,
  maxInstances: 1,
  capabilities: [{
    maxInstances: 1,
    platformName: 'Android',
    platformVersion: '9.0.0',
    deviceName: 'Pixel 2',
    udid: 'FA8131A03509',
    chromeDriverPort: 8723,
    systemPort: 27723,
    browserName: 'chrome',
    chromeOptions: {
      args: ['--no-first-run'],
    },
    newCommandTimeout: 240,
  }],
  specs: [
    './test/specs/**/*.ts'
  ],
  framework: 'mocha',
  reporters: ['dot'],
  mochaOpts: {
    ui: 'bdd',
    timeout: 60000,
    compilers: [
      'ts-node/register',
      'tsconfig-paths/register'
    ]
  },
  before: function (capabilities, specs) {
    require('ts-node/register');
  }
}
```

**Describe the bug**
Webdriver crashes when trying to make connection to grid server with 500 error.

**To Reproduce**
1. start selenium-server-standalone in grid mode
2. connect appium node to grid
3. run any test

**Expected behavior**
Appium started browser/app on mobile device;

instead of 500 error it should be 200 with body like
```
   body:
   { value:
      { capabilities: [Object],
        sessionId: '1ee14a7d-ead5-41f1-baa4-f137b1561195' } } }
```

**Log**
https://gist.github.com/xlenz/2f24464e629761742d5ce218f05a48d0

added console.logs to `node_modules/webdriver/build/request.js:113:21` to get full request options 
https://gist.github.com/xlenz/cca35e874e2843aa351867657c00da1b

Also, added full request options from webdriver 4 to make a proper comparison
https://gist.github.com/xlenz/46d4677bfdbf67bc757f5388988560a6

**Additional context**
I've tried following cases:
webdriver 4.14.1
- appium standalone  - works
- appium over grid - works 

webdriver 5.2.2
- appium standalone - works
- appium over grids - doesn't work (current issue)

haven't tried other 5.x.x versions.

**Comment by christian-bromann** [comment]
@xlenz can you provide logs from Appium or the grid?

**Comment by mgrybyk** [comment]
@christian-bromann sorry to say no, there is nothing in grid logs even with debug set to true.
What else might be helpful for you? I can try build zip with grid, some sources and instructions on how to run grid and appium node, however it is not trivial.

You may start with comparison of what request webdrivero 4 and webdrivero 5 are sending to grid. Request bodies differ and it might be an issue.

**Comment by xlenz** [comment]
@christian-bromann just found out the problem.
It is failing due to `fullRequestOptions.body.capabilities.alwaysMatch`
`params.capabilities` was missing in webdriver 4 and appears in webdriver 5.

if I just simply remove params.capabilities.alwaysMatch - tests are starting on appium node via grid

this is because of https://github.com/webdriverio/webdriverio/commit/22bbadfaa90e5d8266cd7af39353d377fc3f9826#diff-ca695d6881fcf1d2eadda3d4f6042779

**Comment by xlenz** [comment]
Closing issue, it is necessary to pass capabilities like this:
capabilities: [{
    "appium:platformName": 'Android',
    "appium:platformVersion": '9.0.0',
    "appium:deviceName": 'Pixel 2',
    "appium:browserName": 'chrome',
  }]

**Comment by christian-bromann** [comment]
ah nice, we should document this somewhere
