### ISSUE TITLE
browser.waitUntil fails with MS Edge driver

### ISSUE THREAD

**Issue by jlchereau** [webdriverio/webdriverio#3255]
#### Environment:

 - **WebdriverIO version:** 5.2.2
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 11.6.0
 - **NPM version:** 6.5.0
 - **Browser name and version:** MS Edge 18.17763
 - **Platform name and version:** Windows 10 verion 1809 (OS Build 17763.195)
 - **Additional wdio packages used (if applicable):** @wdio/spec reporter, @wdio/selenium-standalone service

#### Describe the bug

Tests using `browser.waitUntil` work in chrome, firefox and internet explorer but not in MS Edge:

```
[MicrosoftEdge  windows #0-0] 2) When navigating pages it should find and navigate faqs
[MicrosoftEdge  windows #0-0] Promise was rejected with the following reason: Error: Unknown error
[MicrosoftEdge  windows #0-0] Error: Promise was rejected with the following reason: Error: Unknown error
[MicrosoftEdge  windows #0-0]     at timer.catch.e (.\node_modules\webdriverio\build\commands\browser\waitUntil.js:71:11)
```

Note that all timeouts in wdio.conf.js are above 10000 including mochaOpts.timeout.

#### To Reproduce

Even the simplest of conditions fails and after adding logs with @wdio/logger, it seems that the arrow function is not even executed:

```
that.waitUntil(() => true, 2000);
```

All information at:
- https://github.com/webdriverio/webdriverio/issues/3196#issuecomment-450656116
- https://github.com/webdriverio/webdriverio/issues/3196#issuecomment-450864974

**Comment by christian-bromann** [comment]
No reason to create a new issue, let's continue convo in #3196
