### ISSUE TITLE
Request failed due to Error: POST /ssion/d0e7fbd3-8f18-4cd2-8a60-47390bb96c95/url did not match a known command

### ISSUE THREAD

**Issue by WoJoinGitHub** [webdriverio/webdriverio#3267]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:5.2.4
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:10.4.0
 - **NPM version:6.5.0
 - **Browser name and version:firefox 64.0
 - **Platform name and version:windows 7

**Config of WebdriverIO**
 const browser = await remote({
    logLevel: 'error',
    path: '/',
    capabilities: {
      browserName: 'firefox',
    },
  })

**Describe the bug**
the code is work on the linux plateform，but not work on the window plateform

**Comment by christian-bromann** [comment]
Please check your setup and follow the step by step instruction explained here: https://webdriver.io/docs/gettingstarted.html. Just creating an issue saying something doesn't work doesn't help us to identify a problem.
