### ISSUE TITLE
Using ESM with Mocha

### ISSUE THREAD

**Issue by niksy** [webdriverio/webdriverio#3269]
**Environment (please complete the following information):**

 - **WebdriverIO version:** 4.14.1
 - **Mode:** Standalone mode
 - **Node.js version:** 8.11.2
 - **NPM version:** 6.5.0
 - **Platform name and version:** macOS Mojave

**Describe the bug**

I’m trying to use ES Modules with Mocha and [esm](https://github.com/standard-things/esm) following recommended way - by using Mocha `require` to load ESM loader, and I’m loading it with `mochaOpts` but I’m getting error described in log below. Is this normal behavior when using ESM loader? Is this something related to Mocha or WebDriverIO? When using just Mocha to run tests (e.g. `mocha --require esm ...` everything works fine).

**Config of WebdriverIO**

```json
{
	specs: [
		'./test/integration/**/*.js'
	],
	mochaOpts: {
		require: ['esm']
	},
	// ...
}
```

**Log**

```
ERROR: Unexpected token import
chrome
.../test/integration/index.js:5
import assert from 'assert';
^^^^^^

Syntax    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Module._compile (.../node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (.../node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
```

**Comment by dictav** [comment]
I have the same problem too.
Now, I’m using [reify](https://www.npmjs.com/package/reify) and it works fine.

```
{
	specs: [
		'./test/integration/**/*.js'
	],
	mochaOpts: {
		require: 'reify'
	}
}
```

However, it is not maintained so I want to replace reify with esm.

**Comment by motss** [comment]
@dictav Cool. Never know it works. `mocha` should work just fine with `esm` now according to https://github.com/mochajs/mocha/issues/3975.

```ts
{
  ...
  specs: ['./test/**/*.js'],
  mochaOpts: {
    require: ['esm'],
  },
  ...
}
```

**Comment by christian-bromann** [comment]
Looks like this works now as expected, closing.

**Comment by motss** [comment]
@christian-bromann I've got the time to do a testing using `esm`. Unfortunately it does not work but `reify` works just fine.

Anyone got any luck to get `esm` working with `webdriverio` and `mocha`?

**Comment by motss** [comment]
Just to update this issue with some other workaround that might work for folks out there. Here's my attempt to instead use `@babel/register`:

```json
/** package.json */
{
  "devDependencies": {
    "@babel/preset-env": "^7.9.6",
    "@babel/register": "^7.9.0"
  }
}
```

```json
/** babel.config.json */
{
  "presets": [
    ["@babel/preset-env", {
      "targets": {
        "node": 12
      }
    }]
  ]
}
```

```js
// wdio.config.js
module.exports = {
  ...
  mochaOpts: {
    ...
    require: ['@babel/register'],
  },
};
```

This might increase the install size of your package/ project but this could be another more reliable alternative as compared to using `esm` as I found out that `esm` tends not to work reliably for Node.js that support native ES Modules (Please don't quote me on that. I could be wrong),

The upside of using `babel` with `@babel/preset-env` is that you do not have to worry much on your code anymore. Babel will take care of this even when you are running your tests with latest ES features.

So, no more using `esm` or `reify`. 😌 

Hope this helps.

**Comment by diachedelic** [comment]
None of these solutions worked for me on Node v14.4.0, webdriverio v6.4.5. I am able to run ESM unit tests with mocha, just not ESM specs with wdio.
