### ISSUE TITLE
Error after upgrading to v5. Services is not a constructor, ReporterClass is not a constructor

### ISSUE THREAD

**Issue by aiosifelis** [webdriverio/webdriverio#3274]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:^5.2.4
 - **Mode:** [Standalone mode]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:** [11.3.0]
 - **NPM version:** [6.4.1]
 - **Browser name and version:** [e.g. Chrome 71]
 - **Platform name and version:** [e.g. MacOS Monjave]
 - **Additional wdio packages used (if applicable):** ["@wdio/cli": "^5.2.4",
    "@wdio/dot-reporter": "^5.2.3",
    "@wdio/local-runner": "^5.2.4",
    "@wdio/sync": "^5.2.3",]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
After upgrading to v5 I get the logs at the end of this message

**To Reproduce**

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

Gist logs

https://gist.github.com/aiosifelis/ad21e376da0476e646ca26a0d71a0367

Update: We use cucumber with TypeScript.

**Comment by BorisOsipov** [comment]
@aiosifelis how your wdio config looks like?

**Comment by aiosifelis** [comment]
Hey, thanks for responding. I was just making the gist for them.

https://gist.github.com/aiosifelis/f89b85b5adff6234026fe9c12078c779

**Comment by aiosifelis** [comment]
@BorisOsipov and here is the command we run, 

`"test:integration": "TS_NODE_PROJECT=tsconfig.wdio.json wdio wdio.conf.js",`

**Comment by BorisOsipov** [comment]
@aiosifelis at least `framework: 'cucumber'` cucumber adapter isn't ported to v5 yet. See https://github.com/webdriverio/webdriverio/issues/2872

**Comment by christian-bromann** [comment]
Closing since cucumber isn't ported yet.

**Comment by aiosifelis** [comment]
I appreciate your quick response.
