### ISSUE TITLE
captureNetworkTraffic

### ISSUE THREAD

**Issue by thibaut-sticky** [webdriverio/webdriverio#328]
Hi,

According to the [capabilities](https://code.google.com/p/selenium/wiki/DesiredCapabilities) page, there is an option `captureNetworkTraffic` to register the traffic. 
Do you know how to use it with _WebdriverIO_? I have to test a player sending request.

**Comment by harsheshbhakta** [comment]
Hi @thibaut-sticky,

I'm have the same issue, but the thing is .HAR generated is empty, actually there is not logs for req,res.

Do you have any idea what could be the issue?

Thanks!

**Comment by thibaut-sticky** [comment]
@harsheshbhakta If you try my example, does it work on your machine?

**Comment by harsheshbhakta** [comment]
@thibaut-sticky  Yes, but as a matter of fact I'm using ```webdriverIO``` not ```grunt-webdriver``` with ```selenium-standalone-2.44``` it does goes through ```port:9091``` but the thing is when the ```.har``` is generated, I'm getting empty ```entries``` in generated .har, even though the test runs completely as expected.

Any idea what could be the issue?

**Comment by FFFFFF** [comment]
Hi guys! @thibaut-sticky, @harshes53 Were you able to process the logs (.har files) and capture traffic?

**Comment by thibaut-sticky** [comment]
@harshes53 I cannot help you anymore, I migrate to Java version of Selenium where browsermob is also working fine.

**Comment by eyalzek** [comment]
@christian-bromann has there been any progress on this? Or do we know atm if it's at all possible?

**Comment by christian-bromann** [comment]
@eyalzek WebDriver won't allow you to capture network traffic anymore. There are workarounds for it that I might share at some point.

**Comment by eyalzek** [comment]
Care to point in the right direction anyway? :)

**Comment by christian-bromann** [comment]
multiplex chromedriver connection to Chrome in order to access the devtools protocol

**Comment by thibaut-sticky** [comment]
An other solution, is to record the traffic of the machine/docker instead of the browser. So no more issue with any browsers.

**Comment by eyalzek** [comment]
Just for future reference, I'm running the following setup with docker (but it can probably be configured without it), docker-compose running:
- 1 x selenium hub
- 2 x selenium chrome nodes
- 1 x application server
- 1 x browsermob-proxy container

after it's all running, a proxy can be started on the browsermob-proxy container:

`curl -XPOST -s -d port=${proxy_port} http://browsermob-proxy:9090/proxy`

then we enable capturing for that proxy:

`curl -XPUT -s -d captureHeaders=true http://browsermob-proxy:9090/proxy/${proxy_port}/har`

now we can configure the proxy in the `desiredCapabilities` of our runner:
```
proxy: {
            proxyType: "MANUAL",
            httpProxy: "browsermob-proxy:${proxy_port}",
            sslProxy: "browsermob-proxy:${proxy_port}"
};
```

eventually to dump the HAR:

`curl -s http://browsermob-proxy:9090/proxy/${proxy_port}/har | jq . > har.json`

**Comment by neilD2** [comment]
@christian-bromann be great to get multiplex chromedriver connection to Chrome solution shared, keenly awaiting. 👍

**Comment by poojachoudhary13** [comment]
@christian-bromann  Can you please guide how to capture network traffic with webdriverio
