### ISSUE TITLE
getElementProperty is not a function

### ISSUE THREAD

**Issue by marthinus-engelbrecht** [webdriverio/webdriverio#3280]
- **WebdriverIO version:** 5.2.2
 - **Mode:** Standalone
 - **Node.js version:** v10.13.0
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome 70.0.3538.77 
 - **Platform name and version:** Ubuntu 18.04

**Config of WebdriverIO**
````javascript
 const client = await remote({
        hostname: "127.0.0.1",
        logLevel: 'trace',
        capabilities:
            {
                browserName: 'chrome',
            }

    })
````

**Describe the bug**
Function should exist. It doesn't.  See below filltered `client` properties at runtime

````javascript 
Object.getOwnPropertyNames(client).filter((key) => key.startsWith("get"))
// produces
[ 'getSessions',
  'getSession',
  'getUrl',
  'getTitle',
  'getWindowHandle',
  'getWindowHandles',
  'getWindowPosition',
  'getWindowSize',
  'getActiveElement',
  'getElementAttribute',
  'getElementCSSValue',
  'getElementText',
  'getElementTagName',
  'getElementLocation',
  'getElementLocationInView',
  'getElementSize',
  'getPageSource',
  'getAllCookies',
  'getAlertText',
  'getAvailableEngines',
  'getActiveEngine',
  'getOrientation',
  'getGeoLocation',
  'getLocalStorage',
  'getLocalStorageItem',
  'getLocalStorageSize',
  'getSessionStorage',
  'getSessionStorageItem',
  'getSessionStorageSize',
  'getLogs',
  'getLogTypes',
  'getApplicationCacheStatus',
  'getContext',
  'getContexts',
  'getPageIndex',
  'getNetworkConnection',
  'getPerformanceDataTypes',
  'getPerformanceData',
  'getCurrentActivity',
  'getCurrentPackage',
  'getSystemBars',
  'getDeviceTime',
  'getDisplayDensity',
  'getStrings',
  'getSettings',
  'getNetworkConditions',
  'getCookies' ]
````
As you can see the property is not present.

**To Reproduce**
Execute the code below against `selenium server standalone 3.141.59` using `chrome driver 2.44.609551`

````javascript
const client = await remote({
        hostname: "127.0.0.1",
        logLevel: 'trace',
        capabilities:
            {
                browserName: 'chrome',
            }

    });

const input = await client.findElement("tag name", "input");
const property = await client.getElementProperty(input.ELEMENT, "magic");
````

**Expected behavior**
Expected the function to be present

**Additional context**
Not sure why this is happening. Took a quick look at the Webdriver code and it seems that the `client.getElementProperty` method should be generated from https://github.com/webdriverio/webdriverio/blob/master/packages/webdriver/protocol/webdriver.json#L450. I doubled checked the version I have installed and the presence of `getElementProperty` in the `webdriver.json` in my node_modules.

**Comment by abjerstedt** [comment]
https://webdriver.io/docs/api/jsonwp.html

You are running on jsonwp not webdriver. This property does not exist for this protocol.

**Comment by marthinus-engelbrecht** [comment]
Thanks, it does seem to be the case. But how do I configure it then to use "Webdriver"? I don't see anything in the docs.

**Comment by abjerstedt** [comment]
@marthinus-engelbrecht You don't. Webdriverio v5 determines which protocol to use based on the driver you are using, and if supports it.

The commands listed on the left side of the page work on all protocols, and you should be using these when possible.

https://webdriver.io/docs/api/element/getProperty.html <- Try that, and if that doesn't work try:
https://webdriver.io/docs/api/element/getCSSProperty.html

**Comment by marthinus-engelbrecht** [comment]
Thanks, suspected as much. Was looking for a way to force it before I created the issue. What I don't get is I'm using the latest chrome driver and according to the [this](https://chromium.googlesource.com/chromium/src/+/master/docs/chromedriver_status.md) it's implemented.

**Comment by marthinus-engelbrecht** [comment]
Seems like the latest `geckodriver` is happy. So I guess `chromedriver` doesn't conform enough yet. Would have been nice if it was a per-method basis.
