### ISSUE TITLE
Invalid typescript definition for $ and $$ 

### ISSUE THREAD

**Issue by xlenz** [webdriverio/webdriverio#3282]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.2.6

**Config of WebdriverIO**
Using TypeScript

**Describe the bug**
Invalid typescript definition for $ and $$ 
Not possible to traverse and pass callbacks 

**To Reproduce**

case1
```
// Property '$' does not exist on type 'Element<void>'.
$('body').$('a')
```

case2
```
Argument of type '() => any' is not assignable to parameter of type 'string'.
$('a').$(() => this.nextSibling.nextSibling)
```

**Expected behavior**
proper definition for $ and $$

**Additional context**
current definition looks like
```
declare function $(selector: string): WebdriverIO.Element<void>;
declare function $$(selector: string): WebdriverIO.Element<void>[];
```
Obviously cases described above won't work here.

**Comment by xlenz** [comment]
workaround
declare namespace WebdriverIO {
  interface Element<T> {
    $(selector: string): WebdriverIO.Element<void>
    $$(selector: string): WebdriverIO.Element<void>[]
  }
}

**Comment by christian-bromann** [comment]
@xlenz mind making a PR?

**Comment by xlenz** [comment]
@christian-bromann 
Fighting now with `$(() => this.nextSibling.nextSibling)`.
Have to understand what is this and how to pass either string or callback function

**Comment by StephenABoyd** [comment]
@xlenz just remove the exclusion of ```$``` and ```$$``` from the definition generation script to bring those two in automatically. You can also add defaults to the existing template Element interface above the comments

**Comment by christian-bromann** [comment]
> for element and elements.

These commands don't exist anymore in v5.

**Comment by timmywil** [comment]
While you're editing the type definitions, I think `execute` should be able to take [any number of arguments](https://webdriver.io/docs/api/browser/execute.html), just like `executeAsync`.

```typescript
      execute(
          script: string | Function
      ): undefined;
      executeAsync(
          script: string | Function,
          arguments: any
      ): undefined;
```

Note the missing `arguments:any`.

**Comment by StephenABoyd** [comment]
@timmywil That would just be a JS Docs update on ```execute.js``` in the browser commands so the auto-generate script can work properly.

Currently it's:

```
 * @param {String|Function} script                     The script to execute.
 * @param {*}               [argument1,...,argumentN]  script arguments
```

It should probably be changed to:
```
 * @param {String|Function} script     The script to execute.
 * @param {*}               arguments  script arguments
```

**Comment by mgrybyk** [comment]
will do

**Comment by ablok** [comment]
> While you're editing the type definitions, I think `execute` should be able to take [any number of arguments](https://webdriver.io/docs/api/browser/execute.html), just like `executeAsync`.
> 
> ```ts
>       execute(
>           script: string | Function
>       ): undefined;
>       executeAsync(
>           script: string | Function,
>           arguments: any
>       ): undefined;
> ```
> 
> Note the missing `arguments:any`.

Actually, it should also have `any` as return type. Because it can return a result.

**Comment by wswebcreation** [comment]
Well regarding the `execute`-typing, I think if we are going to do it, we need to do something like this:

```ts
type Execute = <T>(script: string | Function, ...var_args: any[]) => Promise<T>;
```

Then people can also template their outcome and TS can do it's magic like it should do

**Comment by wswebcreation** [comment]
@mgrybyk

To be honest, I still don't think it should be any, as a user you know what the result should be, so provide it. Any should be, IMHO,  prevented as much as possible because its not what TS stands for (even though it's supported by TS

**Comment by mgrybyk** [comment]
@wswebcreation I've closed PR because it is mostly about $ and $$.

Anyway, we need to improve execute and executeAsync types.

it is easy to improve execute function
`type Execute = <T>(script: string | ((...arguments: any[]) => T), ...arguments: any[]) => T;`

however I have problems with executeAsync function.
Here is how it works:
```
// in this case return type of executeAsync should be string because string is passed to done
// arg1 type should be number (passed 1 to executeAsync)
// arg2 type should be string (passed '2' to executeAsync)
browser.executeAsync(function(arg1, arg2, done) { // NOTE: done callback is the last arg!!
    // passing string to done callback function
    done(`${arg1} ${arg2}`)
}, 1, '2')
```
1st: callback<T>
2nd: args
where <T> is (args, done: (res) => void) // note args length and types should match to args that were passed to executeAsync


i think it is not solvable with typescript at this point
