### ISSUE TITLE
"No test found" when running npm run test in Windows

### ISSUE THREAD

**Issue by urig** [webdriverio/webdriverio#3283]
**Environment:**
 - **WebdriverIO version:** v5.2.0
 - **Mode:** Not relevant
 - **If WDIO Testrunner, running sync/async:** Not relevant
 - **Node.js version:** v10.14.1
 - **NPM version:** v6.4.1
 - **Browser name and version:** Not Relevant
 - **Platform name and version:** Windows 10 Home 
 - **Additional wdio packages used (if applicable):** All

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
When running the project's tests in Windows, Jest is unable to find the test.js files.

**To Reproduce**

1. Fork the project (from https://github.com/webdriverio/webdriverio/)

2. Clone the project somewhere on your computer
    $ git clone git@github.com:<your-username>/webdriverio.git

3. Setup project:
```
$ cd ./webdriverio
$ npm install
$ npm run setup
```

4. Run Tests to ensure that everything is set up correctly
```
$ npm run test
```

**Expected behavior**
All 775 tests should run. Ex:
```
Test Suites: 6 failed, 111 passed, 117 total
Tests:       14 failed, 2 skipped, 759 passed, 775 total
Snapshots:   0 total
Time:        24.512s
Ran all test suites.
```

**Log**
Gist: https://gist.github.com/urig/f916f6657518779424253daa5468d6ac

**Comment by abjerstedt** [comment]
Closing per the referenced PR.
@urig i think the syntax to close issues with a pr is "Resolves <issue>".
