### ISSUE TITLE
`getValue` command must use `getElementAttribute` for all browsers

### ISSUE THREAD

**Issue by ZainabSalameh** [webdriverio/webdriverio#3287]
**Environment :**
 - **WebdriverIO version:** [5.0.0-beta.6]
 - **Browser name and version:** 
	- **Chrome** on Linux v.66.0.3359.117(selenium/node-chrome docker image).
 	- **Safari** on iPhone 6 v.12.1(iphone simulator, appium-version: 1.10)
	- **Firefox** on Linux (selenium/node-firefox docker image)

### **Describe the bug**
The implementation of **getValue** command for an `<input>` shows that for web browsers the command uses `getElementProperty` _(elementIdProperty protocol)_, and for native apps the command uses `getElementAttribute` _(elementIdAttribute protocol)_.
I found that for all browsers and native apps the function that gets the value of an  `<input>` is `getElementAttribute`. 

### **Description**
In `webdriverio/src/commands/element/getValue.js` in **5.0.0-beta.6** version, Chrome fails at condition **isW3C**, so the fallback **getElementAttribute** get executed and no errors are shown here, while Safari and Firefox satisfy the condition isW3C, so the function **getElementProperty** get executed, here webdriver throws the error _this.getElementProperty is not a function_ 

I couldn't check the issue with the latest version of webdriverio in my environment, cause upgrading to a newer version of webdriverio requires releasing other npm packages, my question is: is it a known issue? if yes, did you fix it in the new release, or should I submit a PR to fix the issue?

**Comment by christian-bromann** [comment]
> here webdriver throws the error _this.getElementProperty is not a function_

That should not be the case anymore. I just ran the following script:
```js
browser.url('https://the-internet.herokuapp.com/login')

$('#username').setValue('foobar')
console.log($('#username').getValue())
```
and got an expected result `foobar`

**Comment by abjerstedt** [comment]
@ZainabSalameh Just to note, you are about 30 or so versions behind the current release. Please upgrade all your dependencies to @latest.

**Comment by ZainabSalameh** [comment]
@christian-bromann thanks. Okay @abjerstedt will do.
