### ISSUE TITLE
appium get current activity error

### ISSUE THREAD

**Issue by denonzhu** [webdriverio/webdriverio#3295]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:5.+
 - **Mode:Standalone mode 
 - **Node.js version: 10.+
 - **NPM version:*5.8.0
 - **Platform name and version:android
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**

**Describe the bug**
appiun current_activity is not post 
please fixex it to get.

old:
  "/session/:sessionId/appium/device/current_activity": {
    "POST": {
      "command": "getCurrentActivity",
      "description": "Get the name of the current Android activity.",
      "ref": "http://appium.io/docs/en/commands/device/activity/current-activity/",
      "parameters": [],
      "support": {
        "android": {
          "UiAutomator": "4.2+"
        }
      }
    }
  },
change to this 
  "/session/:sessionId/appium/device/current_activity": {
    "GET": {
      "command": "getCurrentActivity",
      "description": "Get the name of the current Android activity.",
      "ref": "http://appium.io/docs/en/commands/device/activity/current-activity/",
      "parameters": [],
      "support": {
        "android": {
          "UiAutomator": "4.2+"
        }
      }
    }
  },
can work, please fix webdrive protocol/appium.json

**To Reproduce**

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
@denonzhu thanks! Next time don't be afraid to make a PR by yourself 😉

**Comment by denonzhu** [comment]
thanks
