### ISSUE TITLE
Cannot use browser.alertAccept() with TypeScript

### ISSUE THREAD

**Issue by dalenguyen** [webdriverio/webdriverio#3300]
I'm trying to test and accept an alert with TypeScript. However, when I use it, it shows an error and couldn't compile. Same with **browser.alertText()**.

`error TS2339: Property 'acceptAlert' does not exist on type 'Client<void>'.`

Webdriverio: "@types/webdriverio": "^4.13.1"

**Comment by christian-bromann** [comment]
@dalenguyen please raise an issue or make a PR in the [definitely typed repo](https://github.com/DefinitelyTyped/DefinitelyTyped). This project doesn't maintain the types for v4.

**Comment by dalenguyen** [comment]
Thanks @christian-bromann
