### ISSUE TITLE
WebDriverIO V5.2.8 via CodeCept.io-  TypeError: webdriverio.remote(...).init is not a function

### ISSUE THREAD

**Issue by TiaanAuto** [webdriverio/webdriverio#3306]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version: 5.2.8
 - **Mode:** WDIO Testrunner with CodeCept.io
 - **If WDIO Testrunner, running sync/async: async
 - **Node.js version: 8.10
 - **NPM version: 5.6
 - **Browser name and version: Chrome 71
 - **Platform name and version: Windows 10
 - **Additional wdio packages used (if applicable): selenium-standalone

**Config of WebdriverIO**
CodeCept Config:

	"output": "output",
	"helpers": {
		"WebDriverIO": {
			"url": "",
			"browser": "chrome",
			"waitForTimeout": 30000
		},
		"Table": {
			"require": "./Helpers/table_helper.js"
		},
		"LocalStorage": {
			"require": "./Helpers/local_storage_helper.js"
		},
		"NetworkHelper":{
			"require": "./Helpers/network_tab_helper.js"
		},
		"ConfigHelper":{
			"require":"./Helpers/config_helper.js"
		}
	},
	"include": {
		"I": "./Helpers/custom_steps.js",
		"loginDialogComponent": "./PageObjectModels/LoginDialogComponent.js",
		"tableComponent": "./PageObjectModels/TableComponent.js"
	},
	"mocha": {
		"reporterOptions": {
			"reportDir": "./reports",
			"reportFilename": "desktop-results",
			"html": false,
			"json": true,
			"quiet": true
		}
	},
	"bootstrap": false,
	"teardown": null,
	"hooks": [],
	"timeout": 10000,
	"name": "Automation"
}

**Describe the bug**
TypeError: webdriverio.remote(...).init is not a function is thrown on running of automation. This happened recently after WebDriverio update, rolling back wdio version (eg 4.14) causes tests to execute and pass again

**To Reproduce**
Run test runner via Gulp Task to Start Selenium and run tests via CodeCept.io with WebDriverIO as helper. 

[Include code or an example repository that can easily be set up]

**Expected behavior**
Test execute and control the Web Browser ensuring UI aspects are tested. 

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

![erroerwdio](https://user-images.githubusercontent.com/46592417/51023518-c91ae380-158f-11e9-807b-a4fd03cab0c5.JPG)

> Please use the correct markdown

**Comment by BorisOsipov** [comment]
@TiaanAuto Please file this isssue to codeceptjs repo https://github.com/Codeception/CodeceptJS/issues/new

Also pay attention wdio v5 implemented in Codeceptjs 2+ version.
