### ISSUE TITLE
Browser is not opening on Manjaro Linux

### ISSUE THREAD

**Issue by marinakuranda** [webdriverio/webdriverio#3310]
Hello!

Thanks for the WebdriverIO!

I'm using the v5 with Manjaro Linux and everything seems to work fine except one thing. It appears that the browser is not being launched even though I did not specify any configuration that would do so. The test works fine, it's the browser window that I'm missing for debugging purposes.

I've tested this on Windows 7 and it seems to work just fine.

Any ideas what I might be doing wrong?

**Environment:**

**OS:**

```
  Operating System: Manjaro Linux
  Kernel: Linux 4.19.13-1-MANJARO
  Architecture: x86-64
```

**Dependencies:**

```json
...
  "dependencies": {
    "@wdio/cli": "^5.2.8"
    "@wdio/local-runner": "^5.2.8",
    "@wdio/mocha-framework": "^5.2.8",
    "@wdio/selenium-standalone-service": "^5.2.2",
    "@wdio/spec-reporter": "^5.2.3",
    "@wdio/sync": "^5.2.8"
  }
...
```

**wdio.conf.js**

Pretty-much the default from the CLI, but here's the browser setup:

```
    capabilities: [{
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        maxInstances: 5,
        //
        browserName: 'chrome'
    }],
```

**Comment by christian-bromann** [comment]
> Any ideas what I might be doing wrong?

No. This must be an issue with Linux and the browser. Maybe try to run
```sh
Xvfb :1 -screen 5 1024x768x8 &
export DISPLAY=:1.5
```

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by marinakuranda** [comment]
It actually helped, thank you for the suggestion!
