### ISSUE TITLE
When do you plan to migrate Cucumber to WebdriverIO v5?

### ISSUE THREAD

**Issue by HannaMakarava** [webdriverio/webdriverio#3318]
**Environment:**
 - **WebdriverIO version:**5.2.8
 - **Node.js version: 10.15.0
 - **NPM version:** 6.5.0
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/selenium-standalone service

**Comment by BorisOsipov** [comment]
See https://github.com/webdriverio/webdriverio/issues/2872

**Comment by christian-bromann** [comment]
@HannaMakarava also if you are interested in it don't wait until it is done by someone else and rather participate in making it happen!
