### ISSUE TITLE
Can anyone give an example of how to use dragAndDrop in WebdriverIO (v5.3)

### ISSUE THREAD

**Issue by dalenguyen** [webdriverio/webdriverio#3323]
I'm trying to apply **dragAndDrop** function to rearrange the order of a list. 

Here is my code:

**function(test) {
   $('#first-item').dragAndDrop('#third-item', 1000);
}**

This function suppose to move **#first-item** to under **#third-item**. However, it doesn't drag #first-item to #third-item position. It just focuses on the #third-item at the end of the script.

Any ideas? Thanks,

**Comment by christian-bromann** [comment]
@dalenguyen you need to provide much more information that this:
- do you have a reproducible example?
- which environment are you running?
- any logs?
- any output?

Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
