### ISSUE TITLE
does `browser.keys(['Meta', 'v'])` works with chrome?

### ISSUE THREAD

**Issue by michaelseno** [webdriverio/webdriverio#3327]
**Describe your question with as much detail as possible**
I am currently automating web browsers using webdriverio commands and I would like to know if the `keys` command that will be given a `'Meta'` parameter is still working on version 4 of webdriverio since there is no response nor error when this command is trigger its just doing nothing. (i can say since i'm not doing headless browser and I think it executed in backend). All I want to do is to do a `Command + v` to test if the clipboard button is working as we are expecting it to be.

If the `'Meta'` is not working. do you have any alternate implementation?

**If it's about a specific piece of code, try and include some of it to support your question.**
`browser.keys(['Meta', 'v'])`

**Environment (please complete the following information):**
 - **WebdriverIO version:** `4.13.2`
 - **If WDIO Testrunner, running sync/async:** `async`
 - **Browser name and version:** `Chrome 71.0.3578.98`
 - **Platform name and version:** `Mac OSX 10.13.6`

Additional note:
1. I haven't use any other browsers aside from chrome

**Comment by martomo** [comment]
@michaelseno I believe this is an issue with Chrome, managed to reproduce the issue with chromedriver 2.43 and 2.45, by using `['Meta', 'Z']` key sequence.

It seems that any key combination with 'Meta' is not working as expected in Chrome, however 'Meta' with mouse click combination is respected.

**Comment by michaelseno** [comment]
Thank you very much for the clarification. do you happen to have a code snippet for the meta combination with click?

**Comment by martomo** [comment]
@michaelseno Here is a basic example that you can run in standalone mode, which opens the URL in a new tab by Command (Meta) clicking an anchor element:

```js
const { remote } = require('webdriverio');

(async () => {
    const browser = await remote({
        capabilities: {
            browserName: 'chrome',
        }
    });

    await browser.url('https://webdriver.io');

    const elem = await browser.$('.pluginWrapper');
    await elem.waitForEnabled(3000);

    // Open "GET STARTED" in new tab
    await browser.keys('Meta'); // If you comment this line "GET STARTED" is opened in same tab
    await browser.elementClick(elem.elementId);

    await browser.pause(3000);
    await browser.deleteSession();
})().catch((e) => console.error(e));
```
