### ISSUE TITLE
onPrepare and onComplete hooks: this._config[hookName].push is not a function

### ISSUE THREAD

**Issue by xlenz** [webdriverio/webdriverio#3333]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.3.1
 - **Mode:** Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10

**Config of WebdriverIO**
use onComplete
```
  onPrepare: function (config, capabilities) {
  },
  onComplete: function (exitCode, config, capabilities, results) {
  },
``` 
in `wdio.conf.js`

**Describe the bug**
crash when using onPrepare hook

**To Reproduce**

1. create wdio.conf.js with onPrepare hook
2. run

**Expected behavior**
- should be possible to run tests
- there should be appropriate error if hook name is invalid

**Log**
```
onPrepare
2019-01-15T11:41:00.977Z ERROR wdio-config:ConfigParser: Failed loading configuration file: sources/e2e/wdio.chrome.conf.js
sources/e2e/node_modules/@wdio/config/build/lib/ConfigParser.js:76
      throw e;
      ^

TypeError: this._config[hookName].push is not a function
```

**Comment by christian-bromann** [comment]
@xlenz can you please provide more details. This doesn't help.

**Comment by xlenz** [comment]
@christian-bromann sorry, just posted it with default template for some reason

**Comment by xlenz** [comment]
@christian-bromann my fault, updated issue, don't know what has happened to my browser or whatever.
