### ISSUE TITLE
Webdriver.io Version 5 doesn't support 'wdio-visual-regression-service'.

### ISSUE THREAD

**Issue by GineaPig** [webdriverio/webdriverio#3337]
Webdriver.io Version 5 doesn't support 'wdio-visual-regression-service'.

Environment (please complete the following information):

**WebdriverIO version: 5.3.0
**Mode: WDIO Testrunner
If WDIO Testrunner, running sync/async: sync
Browser name and version: [e.g. Chrome 71]
Platform name and version: [e.g. Windows 10]
Additional wdio packages used (if applicable): [ @wdio/spec reporter, @wdio/selenium-standalone service]

**Comment by BorisOsipov** [comment]
NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages).

**Comment by BorisOsipov** [comment]
Create issue here https://github.com/zinserjan/wdio-visual-regression-service/issues/new
