### ISSUE TITLE
Missing typings for addCommand(name, func, attachToElement)

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#3339]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.3.2

**Config of WebdriverIO**
Using TypeScript

**Describe the bug**
Missing typings definition for addCommand(name, func, attachToElement)

**To Reproduce**
1. addCommand(name, func, attachToElement)

**Expected behavior**
valid typings should exist

**Additional context**
can do PR for this really soon

**Comment by christian-bromann** [comment]
Fixed in ##3343
