### ISSUE TITLE
Multiremote does not work in standalone mode

### ISSUE THREAD

**Issue by cuki** [webdriverio/webdriverio#3342]
**Environment:**
 - **WebdriverIO version:** 5.3.2
 - **Mode:** Standalone
 - **Node.js version:** 10.14.2
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome 71.0.3578.98, Firefox 64.0.2
 - **Platform name and version:** macOS 10.13.6

**Describe the bug**
Following the instructions for the multiremote standalone example as documented in [docs/Multiremote.md](https://github.com/webdriverio/webdriverio/blob/0518fa7fc18a577fe94c646fd0e487446f594fae/docs/Multiremote.md) fails to execute due to the following error:
```
UnhandledPromiseRejectionWarning: log.setLevel() called with invalid level: undefined
```

**To Reproduce**
Basically the same as in [docs/Multiremote.md](https://github.com/webdriverio/webdriverio/blob/0518fa7fc18a577fe94c646fd0e487446f594fae/docs/Multiremote.md)

1. Install webdriverio
```
npm install webdriverio@5.3.2
```

2. Create simple example file (e.g. multiremote.js)
```js
const { multiremote } = require('webdriverio');

(async () => {
    const browser = await multiremote({
        myChromeBrowser: {
            logLevel: 'debug',
            capabilities: {
                browserName: 'chrome'
            }
        },
        myFirefoxBrowser: {
            logLevel: 'debug',
            capabilities: {
                browserName: 'firefox'
            }
        }
    });

    // open url with both browser at the same time
    await browser.url('http://json.org');

    // click on an element at the same time
    const elem = await browser.$('#someElem');
    await elem.click();

    // only click with one browser (Firefox)
    await elem.myFirefoxBrowser.click();
})()
```

3. Start necessary drivers.
With the above example I used geckodriver v0.23.0 and chromedriver v2.45.

4. Run simple example file within node
```
node multiremote.js
```

**Expected behavior**
For the documented example to work in standalone mode as expected.
Or at least update the example to work without the error being thrown.

**Log**
Output when running above specified example file:
```
$ node multiremote.js
2019-01-15T21:10:48.242Z DEBUG wdio-config: @wdio/sync not found, running tests asynchronous
2019-01-15T21:10:48.497Z INFO webdriver: [POST] http://0.0.0.0:4444/wd/hub/session
2019-01-15T21:10:48.497Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { browserName: 'chrome' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'chrome' } }
2019-01-15T21:10:48.503Z INFO webdriver: [POST] http://0.0.0.0:4444/wd/hub/session
2019-01-15T21:10:48.503Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { browserName: 'firefox' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'firefox' } }
(node:97665) UnhandledPromiseRejectionWarning: log.setLevel() called with invalid level: undefined
(node:97665) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:97665) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Additional context**
When checking out [docs/Multiremote.md](https://github.com/webdriverio/webdriverio/blob/0518fa7fc18a577fe94c646fd0e487446f594fae/docs/Multiremote.md), the provided example for standalone mode does work as expected.

It is necessary to change the import:
```js
import { multiremote } from 'webdriverio';
```
To the following require:
```js
const { multiremote } = require('webdriverio');
```

Also the error persists when `logLevel` is defined per browser configuration as shown in the above example.

**Comment by martomo** [comment]
@cuki This should be resolved with #3288, you are getting the error because there are no default values defined when using `multiremote` and `logLevel` is defined non the less since #3116, even though there is no way possible of defining the `logLevel` for `multiremote` in standalone mode.

I've also changed the documentation to use `require` instead of `import` within the same pull request.

**Comment by cuki** [comment]
@christian-bromann Thanks for the quick fix!
However I'm confused regarding the `import` in [docs/Multiremote.md](https://github.com/webdriverio/webdriverio/blob/fdbbc559d5e4d6dc0132d5c8d3efab7fd04cc2bc/docs/Multiremote.md), is this correct or should it be changed to `require` like @martomo said he did in #3288? Because for me the `import` does not work.

**Comment by christian-bromann** [comment]
> Because for me the `import` does not work.

It does work if you use babel correctly

**Comment by cuki** [comment]
How is babel related to running multiremote standalone?

**Comment by christian-bromann** [comment]
> How is babel related to running multiremote standalone?

That script example is using imports which is not supported by recent node versions. When I would run the script I would install `@babel/node` and run it with it.
