### ISSUE TITLE
Passing additional options

### ISSUE THREAD

**Issue by buberdds** [webdriverio/webdriverio#335]
Hi!

I'm using webdriverio and it's awsome! Currently I have a problem with running tests using phantom. Do you know how can I pass cli arguments to phantom via webdriverio options? To be more precise: I have to override default --ssl-protocol value and set it to 'any' due to poodle vulnerability 'fixes' on servers ;)

thanks!

**Comment by pavloo** [comment]
@christian-bromann is there any way of passing cli args to chrome browser? thanks.

**Comment by christian-bromann** [comment]
No, how would you propose this should work?

**Comment by christian-bromann** [comment]
oh wait, yeah that is possible (sorry didn't understand the question in the first place) .. one sec

**Comment by christian-bromann** [comment]
do this way:
```js
client = webdriverio.remote({
    desiredCapabilities: {
        browserName: 'chrome',

        /*
         * Command line args to pass to ghostdriver, phantomjs's browser driver.
         * See https://github.com/detro/ghostdriver#faq
         */
        chromeOptions: {
            args: ['allow-file-access', '...'] // you can find a list of args here: https://sites.google.com/a/chromium.org/chromedriver/capabilities
        }
    }
})
```

**Comment by pavloo** [comment]
@christian-bromann awesome man, thanks
