### ISSUE TITLE
WebdriverIO v5 test fails on Travis CI with "DevToolsActivePort file doesn't exist"

### ISSUE THREAD

**Issue by halfzebra** [webdriverio/webdriverio#3350]
Hello friends!

Thanks for WebdriverIO!

I'm having the following problem, please let me know what am I doing wrong 🙏 

**Environment**

Running inside Travis CI with Node LTS.

_travis.yml_

```yml
language: node_js

node_js:
  - '10.15'
```

_package.json_

```json
{
  "name": "wdio-starter",
  "private": true,
  "scripts": {
    "postinstall": "selenium-standalone install",
    "test": "wdio wdio.conf.js"
  },
  "dependencies": {
    "@wdio/cli": "^5.2.8",
    "@wdio/local-runner": "^5.2.8",
    "@wdio/mocha-framework": "^5.2.8",
    "@wdio/selenium-standalone-service": "^5.2.2",
    "@wdio/spec-reporter": "^5.2.3",
    "@wdio/sync": "^5.2.8"
  }
}
```

**Config of WebdriverIO**
I have pretty much default setup from `wdio config`
https://github.com/halfzebra/wdio-starter/blob/master/wdio.conf.js

**Describe the bug**
Please check out the log from Travis CI https://travis-ci.org/halfzebra/wdio-starter/builds/480278039
```sh
ERROR webdriver: Request failed due to Error: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

https://travis-ci.org/halfzebra/wdio-starter

**To Reproduce**
Fork https://github.com/halfzebra/wdio-starter and run on Travis CI.

**Expected behavior**
Should work on Travis CI

**Comment by BorisOsipov** [comment]
@halfzebra There is no UI to run chrome on Travis build. You should configure xvfb in your travis.yaml file or use headless chrome


Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by halfzebra** [comment]
Thanks for the advice, it worked out well for me!
