### ISSUE TITLE
End test gracefully in case of mocha timeout reached

### ISSUE THREAD

**Issue by skudasov** [webdriverio/webdriverio#3351]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.3.0
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v10.14.2
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome 71
 - **Platform name and version:** macOS mojave 10.14.2
 - **Additional wdio packages used (if applicable):**
```
"dependencies": {
    "@wdio/cli": "^5.3.0",
    "@wdio/local-runner": "^5.3.3",
    "allure-commandline": "^2.7.0",
    "axios": "^0.18.0",
    "chai": "^4.2.0",
    "ramda": "^0.25.0",
    "rimraf": "^2.6.2",
    "wdio-allure-reporter": "^0.7.0",
    "webdriver-manager": "^12.1.0",
    "webdriverio": "^5.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.1.2",
    "@babel/preset-env": "^7.1.0",
    "@babel/preset-typescript": "^7.1.0",
    "@babel/register": "^7.0.0",
    "@wdio/mocha-framework": "^5.2.8",
    "@wdio/sync": "^5.2.8",
    "eslint": "^5.6.1",
    "eslint-plugin-typescript": "^0.12.0",
    "eslint-plugin-vue": "^4.7.1",
    "lint-staged": "^8.1.0",
    "typescript": "^3.1.1",
    "typescript-eslint-parser": "^20.0.0"
  }]
```

**Config of WebdriverIO**
```
exports.config = {

    hostname: '0.0.0.0',
    port: 4444,
    specs: [
        './mocha.test.js'
    ],
    before: function () {
        require('@babel/register');
    },
    maxInstances: 5,
    capabilities: [{
        maxInstances: 5,
        browserName: 'chrome',
    }],
    logLevel: 'debug',
    deprecationWarnings: true,
    bail: 0,
    waitforTimeout: 10000,
    connectionRetryTimeout: 30000,
    connectionRetryCount: 3,
    mochaOpts: {
        ui: 'bdd',
        timeout: 10000
    },
}
```

**Describe the bug**
Mocha-framework do not end test gracefully after timeout is reached, http requests in our case are still executed after delete session command.

**To Reproduce**
MWE: https://github.com/f4hrenh9it/mocha-timeout-non-graceful

**Expected behavior**
Test ended with timeout exception.

**Log**
[0-0] 2019-01-16T10:46:37.242Z INFO webdriver: RESULT { ELEMENT: '0.7351839454397016-2' }
[0-0] 2019-01-16T10:46:37.249Z INFO webdriver: COMMAND elementClick("0.7351839454397016-2")
[0-0] 2019-01-16T10:46:37.249Z INFO webdriver: [POST] http://0.0.0.0:4444/wd/hub/session/9f0d246e0d78e088c335926be04139c2/element/0.7351839454397016-2/click
[0-0] 2019-01-16T10:46:37.746Z INFO webdriver: COMMAND deleteSession()
[0-0] 2019-01-16T10:46:37.746Z INFO webdriver: [DELETE] http://0.0.0.0:4444/wd/hub/session/9f0d246e0d78e088c335926be04139c2
[0-0] request loop: 1
2019-01-16T10:46:40.029Z INFO webdriver: COMMAND getUrl()
2019-01-16T10:46:40.029Z INFO webdriver: [GET] http://0.0.0.0:4444/wd/hub/session/9f0d246e0d78e088c335926be04139c2/url
2019-01-16T10:46:40.243Z DEBUG wdio-local-runner: Runner 0-0 finished with exit code 1

Test Suites:     0 passed, 1 failed, 1 total (100% completed)
Time:            🕚  14.41s

**Comment by cjatkinson** [comment]
@skudasov, I was unable to replicate the bug. Would you mind upgrading to version 6 of the project and seeing if this is still an issue?

**Comment by christian-bromann** [comment]
Let's close the issue and re-open in case it is still an issue.
