### ISSUE TITLE
Fix typings for getContext(s), getNetworkConnection, waitUntil, setTimeout, touchAction

### ISSUE THREAD

**Issue by xlenz** [webdriverio/webdriverio#3354]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.3.3

**Describe the bug**
Invalid/missing typings for some of methods and properties

**Expected behavior**
- there should be proper typings for: getContext(s), getNetworkConnection, waitUntil, setTimeout, touchAction
- Appium specific desired capabilities should be available

**Comment by christian-bromann** [comment]
Merged.
