### ISSUE TITLE
If using babel, is it possible to setup source maps to retrieve the correct line numbers in stack traces?

### ISSUE THREAD

**Issue by Matthematic** [webdriverio/webdriverio#3358]
**Describe your question with as much detail as possible**
If an error occurs in a webdriver test, the line number reported in the stack isn't quite right. It's always a few lines off. For example: if I 
`throw new Error()`
 on line 42, I will get the following stack trace for line 45.

`running chrome
Error
    at Context.<anonymous> (/home/matt/code/mar-js/tests/wdio/mar-js/slide-panel-view-spec.js:45:13)
    at new Promise (<anonymous>)
    at new F (/home/matt/code/mar-js/node_modules/babel-runtime/node_modules/core-js/library/modules/_export.js:36:28)
`
I'm aware this is probably because I'm using
`
mochaOpts: {
  compilers: ['js:babel-register'],
  ...
}
`

in my wdio configuration, so it's likely reporting the line number of the compiled file. **Is it possible to get the correct line number using some source-map setup?** I'm not too familiar with source maps or how they would work in a webdriver scenario since it goes through multiple different frameworks.

**Environment (please complete the following information):**
 - **WebdriverIO version:** ^4.10.2
 - **Mode:** [Standalone mode or WDIO Testrunner] WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async] async
 - **Node.js version: 8.9.4
 - **NPM version:** 5.6.0
 - **Browser name and version:** [e.g. Chrome 68] Chrome
 - **Platform name and version:** [e.g. Windows 10] Windows

**Comment by christian-bromann** [comment]
@Matthematic yes, check for example the babel setup of the webdriverio project.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
