### ISSUE TITLE
On Specifying one of the driver details under `drivers` argument in `seleniumArgs` and `seleniumInstallArgs`; forces the user to add the driver arguments for other drivers as well. 

### ISSUE THREAD

**Issue by nami-varthakavi** [webdriverio/webdriverio#3359]
To provide an example of the above scenario. 

In my config File I add 
```
seleniumArgs: {
        drivers: {
            edge: {
                version: '<version of edge>',
                arch: process.arch
            }
        }
    },
    seleniumInstallArgs: {
        drivers: {
            edge: {
                version: '<version of edge>',
                arch: process.arch,
                baseURL: 'https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/'
            }
        }
    }
```
And if I'm running Edge and Chrome browser in the same test. I get an error for not able to create a `ChromeDriver Service`.

Assume Chrome version is 71 and Edge at 14(Not the latest). So I have to specify the driver version for Edge and expects the wdio to pick the latest version for Chrome out of the box.  Is there any way I can skip providing the versions of other browsers like this 

```
seleniumArgs: {
        drivers: {
            chrome: {
                version: '<version of chrome>',
                arch: process.arch
            },
            firefox: {
                version: '<version of firefox>',
                arch: process.arch
            },
            edge: {
                version: '<version of edge>',
                arch: process.arch
            }
        }
    },
    seleniumInstallArgs: {
        drivers: {
            chrome: {
                version: '<version of chrome>',
                arch: process.arch,
                baseURL: 'https://chromedriver.storage.googleapis.com'
            },
            firefox: {
                version: '<version of firefox>',
                arch: process.arch,
                baseURL: 'https://github.com/mozilla/geckodriver/releases'
            },
            edge: {
                version: '<version of edge>',
                arch: process.arch,
                baseURL: 'https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/'
            }
        }
    },
```

**Comment by christian-bromann** [comment]
I am not sure if this can be fixed in the standalone service. I think this issue belongs to https://github.com/vvo/selenium-standalone

**Comment by nami-varthakavi** [comment]
> I am not sure if this can be fixed in the standalone service. I think this issue belongs to https://github.com/vvo/selenium-standalone

@christian-bromann Maybe you can modify how you pass in the `seleniumArgs` and `seleniumArgsInstall` by merging the JSON string in the config file the user has provided and anything missing can be replaced from the standalone default config provided by selenium?

**Comment by abjerstedt** [comment]
I really don't see an issue with this honestly:

args = {}
seleniumArgs: args;
seleniumInstallArgs: args;

You set the drivers once and forget about them until you manually want to update them. Its also way better than dealing with whatever driver selenium-standalone decides to assign you based on whatever criteria they use.

**Comment by nami-varthakavi** [comment]
> I really don't see an issue with this honestly:
> 
> args = {}
> seleniumArgs: args;
> seleniumInstallArgs: args;
> 
> You set the drivers once and forget about them until you manually want to update them. Its also way better than dealing with whatever driver selenium-standalone decides to assign you based on whatever criteria they use; and even if you wanted to just go with the default... it will never update until the selenium-standalone npm version increments.

These are just suggestions that I noticed in v5. Because in v4 `javaArgs` gave us the liberty to give only the ones required and not to worry about anything that is not using.

**Comment by abjerstedt** [comment]
@nami-varthakavi - Okay, so i dove into both our code, and the selenium-standalone code. They are using:
```
  if (opts.drivers) {
    // Merge in missing driver options for those specified
    opts.drivers = mapValues(opts.drivers, function(config, name) {
      return merge({}, defaultConfig.drivers[name], config);
    });
  } else {
    opts.drivers = defaultConfig.drivers;
  }
```

This has 2 side effects:
1.) You will not pull drivers for browsers not referenced (this is good - you don't have to worry about the upkeep on drivers you aren't using)
2.) You do not need to specify the version, only an empty object and it will pull down the default driver.

For example:
```
    "seleniumArgs": {
      "version": "3.141.0",
      "drivers": {
        "chrome": {
        },
        "firefox": {
          "version": "0.24.0"
        }
      }
    },
    "seleniumInstallArgs": {
      "version": "3.141.0",
      "drivers": {
        "chrome": {
        },
        "firefox": {
          "version": "0.24.0"
        }
      }
    }
```

**Comment by nami-varthakavi** [comment]
> @nami-varthakavi - Okay, so i dove into both our code, and the selenium-standalone code. They are using:
> 
> ```
>   if (opts.drivers) {
>     // Merge in missing driver options for those specified
>     opts.drivers = mapValues(opts.drivers, function(config, name) {
>       return merge({}, defaultConfig.drivers[name], config);
>     });
>   } else {
>     opts.drivers = defaultConfig.drivers;
>   }
> ```
> This has 2 side effects:
> 1.) You will not pull drivers for browsers not referenced (this is good - you don't have to worry about the upkeep on drivers you aren't using)
> 2.) You do not need to specify the version, only an empty object and it will pull down the default driver.
> 
> For example:
> 
> ```
>     "seleniumArgs": {
>       "version": "3.141.0",
>       "drivers": {
>         "chrome": {
>         },
>         "firefox": {
>           "version": "0.24.0"
>         }
>       }
>     },
>     "seleniumInstallArgs": {
>       "version": "3.141.0",
>       "drivers": {
>         "chrome": {
>         },
>         "firefox": {
>           "version": "0.24.0"
>         }
>       }
>     }
> ```

OK thanks for the reply @abjerstedt
