### ISSUE TITLE
code ELIFECYCLE - Tell the author that this fails on your system: WebDriverIO and Jasmine

### ISSUE THREAD

**Issue by Alek5andr** [webdriverio/webdriverio#3361]
Hello, comrades!

I have some suites, where all tests pass successfully while running. However, they give out the following error eventually:

> npm ERR! code ELIFECYCLE
> npm ERR! tests@0.0.1 test-admin: `wdio wdio.conf.js --suite admin || true`
> npm ERR! Exit status 1

I have one suite that does NOT give out such error.
Honestly, I'm out of ideas and trials&errors to figure out the difference. Tests and suites are build in the same way. Only difference is parts of SUT.

**_What could you suggest me?_**

**Environment:**
 - **WebdriverIO version:** [4.10.2]
- **Jasmine version:** [0.3.4]
 - **Mode:** [Selenium Standalone mode]
 - **Node.js version:** [6.11.2]
 - **NPM version:** [3.10.10]
 - **Browser name and version:** [Chrome 63]
 - **Platform name and version:** [Windows 10]

**Generated debug log file:**

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'test-admin',
> 1 verbose cli   '--scripts-prepend-node-path=auto' ]
> 2 info using npm@3.10.10
> 3 info using node@v6.11.2
> 4 verbose run-script [ 'pretest-admin', 'test-admin', 'posttest-admin' ]
> 5 info lifecycle tests@0.0.1~pretest-admin: tests@0.0.1
> 6 silly lifecycle tests@0.0.1~pretest-admin: no script for pretest-admin, continuing
> 7 info lifecycle tests@0.0.1~test-admin: tests@0.0.1
> 8 verbose lifecycle tests@0.0.1~test-admin: unsafe-perm in lifecycle true
> 9 verbose lifecycle tests@0.0.1~test-admin: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\HotChick\WebstormProjects\gui-test\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\oraclexe\app\oracle\product\11.2.0\server\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Java\jdk1.8.0_161\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\apache-maven-3.5.0\bin\;C:\Program Files (x86)\IDEMIA\AWP\Dlls;"C:\Program Files (x86)\ngrok\";C:\Users\HotChick\AppData\Local\Microsoft\WindowsApps;C:\Users\HotChick\AppData\Roaming\npm
> 10 verbose lifecycle tests@0.0.1~test-admin: CWD: C:\Users\HotChick\WebstormProjects\gui-test
> 11 silly lifecycle tests@0.0.1~test-admin: Args: [ '/d /s /c', 'wdio wdio.conf.js --suite admin || true' ]
> 12 silly lifecycle tests@0.0.1~test-admin: Returned: code: 1  signal: null
> 13 info lifecycle tests@0.0.1~test-admin: Failed to exec test-admin script
> 14 verbose stack Error: tests@0.0.1 test-admin: `wdio wdio.conf.js --suite admin || true`
> 14 verbose stack Exit status 1
> 14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
> 14 verbose stack     at emitTwo (events.js:106:13)
> 14 verbose stack     at EventEmitter.emit (events.js:191:7)
> 14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
> 14 verbose stack     at emitTwo (events.js:106:13)
> 14 verbose stack     at ChildProcess.emit (events.js:191:7)
> 14 verbose stack     at maybeClose (internal/child_process.js:891:16)
> 14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> 15 verbose pkgid tests@0.0.1
> 16 verbose cwd C:\Users\HotChick\WebstormProjects\gui-test
> 17 error Windows_NT 10.0.14393
> 18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test-admin" "--scripts-prepend-node-path=auto"
> 19 error node v6.11.2
> 20 error npm  v3.10.10
> 21 error code ELIFECYCLE
> 22 error tests@0.0.1 test-admin: `wdio wdio.conf.js --suite admin || true`
> 22 error Exit status 1
> 23 error Failed at the tests@0.0.1 test-admin script 'wdio wdio.conf.js --suite admin || true'.
> 23 error Make sure you have the latest version of node.js and npm installed.
> 23 error If you do, this is most likely a problem with the tests package,
> 23 error not with npm itself.
> 23 error Tell the author that this fails on your system:
> 23 error     wdio wdio.conf.js --suite admin || true
> 23 error You can get information on how to open an issue for this project with:
> 23 error     npm bugs tests
> 23 error Or if that isn't available, you can get their info via:
> 23 error     npm owner ls tests
> 23 error There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

**Comment by abjerstedt** [comment]
@Alek5andr Someone else might pipe in, but i'm not going to debug/troubleshoot this. You are running a very old node version, npm version; and old webdriverio (even in the v4 space) and jasmine versions.

While v4 is still supported, the majority of effort is going into v5 which requires node 8.11.2.

**Comment by christian-bromann** [comment]
I agree with @abjerstedt. It is impossible to help here without having a reproducible example or anything we can look into.
