### ISSUE TITLE
Truncate Screenshot webdriver command result in log

### ISSUE THREAD

**Issue by xlenz** [webdriverio/webdriverio#3362]
screenshot binary data is posted into log which is not helpful at all, makes it size huge and not readable. 

`webdriver/src/command.js` line `log.info('RESULT', result.value)`

**Describe the solution you'd like**
Truncate `result.value` in case **command** name includes _screenshot_ and has result of proper type
```
                log.info('RESULT',
                    command.toLowerCase().includes('screenshot') && typeof result.value === 'string' ?
                        `${result.value.substr(0, 64)}...` : result.value)
```

**Additional context**
Can do PR for this.

**Comment by abjerstedt** [comment]
I like this! Maybe we should determine if its base64, and just replace that value with something like <base64 object> ?

**Comment by christian-bromann** [comment]
I like it too. In v4 we had a limit helper for this. Feel free to propose a PR. Thanks!

**Comment by xlenz** [comment]
@abjerstedt I'm afraid is an overkill to determine if it is a base64 in terms of resources.
