### ISSUE TITLE
Error: unknown error: at getErrorFromResponseBody

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [webdriverio/webdriverio#3366]
Hi! I'm completely new to Webdriver; and I've been assigned a task involving a legacy codebase with some automated interface-tests that use it. I've spent the day trying to get up to speed on the docs and what I can suss out of Google, and I've made *some* progress towards getting our existing tests to run; but now I've run up against a wall that I can't Google my way past. Most of our tests are currently spitting up an error something like this one (full logs linked below.)

```
[chrome #0-1] unknown error: 
  (Session info: chrome=71.0.3578.98)
  (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.14.2 x86_64)
[chrome #0-1] Error: unknown error: 
[chrome #0-1]   (Session info: chrome=71.0.3578.98)
[chrome #0-1]   (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.14.2 x86_64)
[chrome #0-1]     at getErrorFromResponseBody (/Users/ec/Work/game-engine/node_modules/webdriver/build/utils.js:336:10)
[chrome #0-1]     at Request._callback (/Users/ec/Work/game-engine/node_modules/webdriver/build/request.js:113:64)
[chrome #0-1]     at Request.self.callback (/Users/ec/Work/game-engine/node_modules/request/request.js:185:22)
[chrome #0-1]     at emitTwo (events.js:126:13)
[chrome #0-1]     at Request.emit (events.js:214:7)
[chrome #0-1]     at Request.<anonymous> (/Users/ec/Work/game-engine/node_modules/request/request.js:1161:10)
[chrome #0-1]     at emitOne (events.js:116:13)
[chrome #0-1]     at Request.emit (events.js:211:7)
[chrome #0-1]     at IncomingMessage.<anonymous> (/Users/ec/Work/game-engine/node_modules/request/request.js:1083:12)
[chrome #0-1]     at Object.onceWrapper (events.js:313:30)
```
I'd appreciate any tips on how to get *more information* about what this ‘unknown error’ in `getErrorFromResponseBody` may be; or how to get past it. Is this a bug in WebdriverIO v5, or am I using it wrong somehow?

Thanks!

----

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.3.3
 - **Mode:** WDIO Testrunner (I think?)
 - **If WDIO Testrunner, running sync/async:** tried both? not sure
 - **Node.js version:** v8.11.4
 - **NPM version:** 6.5.0
 - **Browser name and version:** Chrome 71 (… .0.3578.98)
 - **Platform name and version:** macOS “Mojave” 10.14.2
 - **Additional wdio packages used (if applicable):** @wdio/cli@5.3.3, @wdio/local-runner@5.3.3, @wdio/mocha-framework@5.3.2, @wdio/selenium-standalone-service@5.2.2, @wdio/spec-reporter@5.2.3, @wdio/sync@5.3.2

**Config of WebdriverIO**
```js
exports.config = {
  specs: [ './test/interface/**/*test.js' ],
  maxInstances: 10,
  capabilities: [{ maxInstances: 1, browserName: 'chrome' }],
  sync: true,
  logLevel: 'info',
  coloredLogs: true,
  screenshotPath: './test/error-shots/',
  baseUrl: 'http://localhost:8080/test/interface/',
  waitforTimeout: 10000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  services: ['selenium-standalone'],
  framework: 'mocha',
  reporters: ['spec'],
  mochaOpts: {
    ui: 'bdd',
    require: './test/setup/interface.js',
    compilers: ['js:@babel/register'],
    timeout: 3000 },
  before: function (capabilities, specs) {
    var chai = require('chai');
    global.expect = chai.expect;
    chai.Should();
    browser.url(''); },
}
```

**Log**
[Here are the logs](https://gist.github.com/ELLIOTTCABLE/52d683cc1dabf8ef76725ea96c5e8475) from `selenium-standalone` and `wdio`.

**Additional context**
The code I'm debugging is propietary, but at the very least, [here's](https://gist.github.com/ELLIOTTCABLE/ade26c7328fd6f36548953c98278e58f) parts of the `/test/setup/interface.js` file mentioned in the config above.

**Comment by abjerstedt** [comment]
This isn't an explicit issue or bug, and will require research and troubleshooting. 

Please ask questions like this in our gitter channel, as we can help you in near real time.
