### ISSUE TITLE
how to close browser after RuntimeError?

### ISSUE THREAD

**Issue by vinnitu** [webdriverio/webdriverio#337]
Have such a ptoblem

client.on('error', function() {
    client.end(); //no effect
    client.session('delete'); //no effect
}

client
  .click('#no-exists-selector')
  .end() //doesn't call because error

**Comment by binarykitchen** [comment]
@christian-bromann I am interested in a code example for what you have said. Just curious here. Thanks

**Comment by SchwaFa** [comment]
This doesn't work for me. 
I added "browser.end()" inside the after hook in the config.js, but if a RuntimeError occures (e.g. "no such element") the browser still stays open.

**Comment by bmxpala** [comment]
@SchwaFa I had the same, so I put 'client.end()' to the 'after' hook and in 'it' section:

    describe('test site', function() {
       after(function() {
         client.end();
       });


      it('get link value', function(done) {

          client
              .init()
              .url('http://webdriver.io/')
              .getText('h1.header').should.eventually.exist
              .call(done)
              .end();
       });

    
     });

**Comment by pietrovismara** [comment]
I'm having the same issue, client.end() called in an error handling function doesn't work. 
I'm not using webdriverio for testing but more for scraping, so i don't have a proper after hook.
Can someone explain why it doesn't work and give some suggestion?

**Comment by christian-bromann** [comment]
@pietrovismara you can't execute async methods in hook callbacks. I would recommend to execute your scrapper code within mocha to have hooks enabled.
