### ISSUE TITLE
Different behaviours for remote() function regarding to way how you import it

### ISSUE THREAD

**Issue by CrispusDH** [webdriverio/webdriverio#3373]
**Environment:**
 - **WebdriverIO version**: 5.3.5
 - **Mode**: Standalone mode
 - **Node.js version**: 11.7.0
 - **NPM version**: 6.6.0
 - **Browser name and version:** chrome 72.0.3626.53
 - **Platform name and version:** macOS Mojave 10.14.2

**Describe the bug**
At the start, I run the [Getting Started](https://webdriver.io/docs/gettingstarted.html#create-test-file) example. I import `remote` as `const { remote } = require('webdriverio');`. In this case `remote()` function does not have typings. I see that function returns `: any`. Also in example I see that function gets only one argument. Nethertheless, the example works. But I don't have any support by types that is sad.
But, when I go deeper in in `webdriverio.d.ts` I see that `remote()` function has Two arguments and both are Not optional. 
```js
function remote(
        options: any,
        modifier: any
    ): WebDriver.Client<void>;
```
So, it is obvious difference! Okay, for getting types support I decided to import `remote()` as `import { remote } from'webdriverio';`. In this way, I get types support. But I should put `modifier`. I put `undefined`: 
```js
const browser = await remote({
    logLevel: 'error',
    path: '/',
    capabilities: {
      browserName: 'chrome'
    }
  }, undefined);
```
But **I can't work with this browser instance**! `remote()` function returns `WebDriver.Client<void>`. And when I want to use `browser.url()` function I see `TS2339: property 'url' does not exist on type 'WebDriver.Client<void>'`. But the same works when I import `remote()` in a different way.

So, my question is how to use `remote()` for getting type support and how initialise browser because `WebDriver.Client<void>` it is not browser... Thanks a lot.
I have suggestion that types are wrong because, definitely, it works without types.

**To Reproduce**
- for reproducing `any` just import `remote()` as `const { remote } = require('webdriverio');`
- for reproducing issue with "how to use browser" and two required arguments instead of one just import `remote()` as `const { remote } = require('webdriverio');`

[Include code or an example repository that can easily be set up]

**Expected behavior**
I want to use `remote()` with type support and then use `browser` as usual.

**Comment by CrispusDH** [comment]
@abjerstedt could you take a look at it, please. Or just tell me how could I help here?

**Comment by christian-bromann** [comment]
> Nethertheless, the example works. But I don't have any support by types that is sad.

We are maintaining the typings within this repository. Feel free to provide a patch that fixes the issue.

**Comment by CrispusDH** [comment]
@christian-bromann it would be nice if you add some entry points how to change some methods in `.js` file to achieve needed types after running type generation command. Because it is totally unclear from reading [these](https://github.com/webdriverio/webdriverio/blob/421176f3d5e6875cd654ff2122a314c47134d477/package.json#L21) script files. For example how I could change `remote()` [method arguments](https://github.com/webdriverio/webdriverio/blob/421176f3d5e6875cd654ff2122a314c47134d477/packages/webdriverio/src/index.js#L15) to make `remoteModifier ` optional and how to add proper type?

**Comment by christian-bromann** [comment]
> For example how I could change `remote()` [method arguments](https://github.com/webdriverio/webdriverio/blob/421176f3d5e6875cd654ff2122a314c47134d477/packages/webdriverio/src/index.js#L15) to make `remoteModifier ` optional and how to add proper type?

All type definition of the protocol commands are grabbed from the protocol json file like https://github.com/webdriverio/webdriverio/blob/master/packages/webdriver/protocol/appium.json. For browser and element scoped commands it is directly in the webdriverio js file of the command, e.g. https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/commands/browser/deleteCookies.js. The rest you find here: https://github.com/webdriverio/webdriverio/tree/master/scripts/templates (e.g. the remote definition: https://github.com/webdriverio/webdriverio/blob/master/scripts/templates/webdriverio.tpl.d.ts#L5)
