### ISSUE TITLE
V5 saveScreenshot functionality

### ISSUE THREAD

**Issue by AsteaDevelopment** [webdriverio/webdriverio#3384]
**Is your feature request related to a problem? Please describe.**
The problem I have is I would like to provide an absolute path that is outside the execution directory for filepath parameter, but it doesn't seem to support this.

**Describe the solution you'd like**
Support for absolute path outside of the execution directory.

**Describe alternatives you've considered**
I wouldn't mind updating the saveScreenshot function to support this, for now I have just modified the saveScreeshot.js file directly.

**Additional context**
Unless I am overlooking the functionality, it seems that if you pass a relative path that starts with slashes or without, it assumes you are within the execution directory either way? I recall when using v4 I think you had to provide the full path yourself where the image would be saved, but correct me if I am wrong.

Thank you, much appreciated!

**Comment by christian-bromann** [comment]
> Support for absolute path outside of the execution directory.

This should already work if you do `saveScreenshot("/myscreenshot.png")` or in Windows `saveScreenshot("\\something")` I don't know about Windows.

**Comment by AsteaDevelopment** [comment]
I am working with Windows, I don't think it works because \\ wouldn't work right? It would have to be something like C:\\, wherever the file is actually stored?

Here is what I tested, and what I got back:

`\\appium_screenshots\\test_2019-01-22_19-34-09`

directory (\\appium_screenshots\\test_2019-01-22_19-34-09) doesn't exist.
