### ISSUE TITLE
Create outputDir directory in case it doesn't exist

### ISSUE THREAD

**Issue by nami-varthakavi** [webdriverio/webdriverio#3389]
On a fresh start of running the tests, we expect the WDIO tester runner will be creating the folder mentioned in the  `outputDir` arg for `allure`. 
This is how I provided in the config file, 

```
reporters: [
        'spec',
        ['allure', {
            outputDir: './test-reporters/allure-results'
        }]
    ]
``` 
 On running my test I get the following error 
```
[0-0] events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: ENOENT: no such file or directory, open 'C:\path\to\my\package\test-reports\allure-results\wdio-0-0-allure-reporter.log'
````

I also tried giving the default value like this 
```
reporters: [
        'spec',
        ['allure', {
            outputDir: 'allure-results'
        }]
    ]
``` 
but the error persists.

**Comment by christian-bromann** [comment]
@nami-varthakavi if the directory doesn't exist it can't put files in there. I would agree however that wdio should create the folder in case it doesn't exit.

**Comment by nami-varthakavi** [comment]
Can you also update `outputDir` in config file(https://webdriver.io/docs/options.html#outputdir) also to incorporate the same idea?

**Comment by tendonstrength** [comment]
Should this issue be closed since there is a merged PR for it?

**Comment by WillBrock** [comment]
@tendonstrength yes, closing.

**Comment by atti187** [comment]
@WillBrock - not working, at least not on Windows. I moved the ensureDirSync-call to before the call to createWriteStream in the constructor and it starts working, which seems reasonable?

wdio.conf looks like:
`
reporters: ['spec',
        ['junit', {
            outputDir: './reports',
            outputFileFormat: function (opts) { // optional
                return `wdio-${opts.cid}-junit-report.xml`
            }
        }]
    ]
`

Options-object looks like:

`
{ logLevel: 'silent',                                                                                                                                                                                                         setLogFile: [Function: NOOP],                                                                                                                                                                                                     outputDir: './reports',                                                                                                                                                                                                           outputFileFormat: [Function: outputFileFormat],                                                                                                                                                                                   logFile: 'reports\\wdio-0-0-junit-report.xml',                                                                                                                                                                                    writeStream: { write: [Function: write] } }
`

**Comment by WillBrock** [comment]
@atti187 That might be OK but not sure why that would change creating the directory. I don't have windows so I don't have a way to test. Mind creating a pr so someone can test with windows?

**Comment by klamping** [comment]
Looks like my fix resolved the issue in junit, but not allure... working on an update in #3578

**Comment by nami-varthakavi** [comment]
> Looks like my fix resolved the issue in junit, but not allure... working on an update in #3578

Haven't really had time to follow up on your changes. Anyways thanks for checking this out for me :)

**Comment by atti187** [comment]
@WillBrock - guess @klamping beat me to it! Anyway, thx.
