### ISSUE TITLE
Click on a flash element

### ISSUE THREAD

**Issue by thibaut-sticky** [webdriverio/webdriverio#339]
Hi,

I'm currently testing a flash player. But, Selenium does not handle natively Flash. Do you know a workaround to simply click on a play button within a player for instance?
In the java world, _sikuli_ came often. It's based on image recognition.

**Comment by Cartonmarc** [comment]
@thibaut-sticky https://embroidered88.github.io/-wKQWSaEvVipKL0cP02GNGLb17kREHYni9bbdA42jbod_EF39vU/
