### ISSUE TITLE
Compatibility check if used Chromedriver version matches with used Chrome version.

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#3390]
**Is your feature request related to a problem? Please describe.**
There are a lot of bugs reported due to issues that are based on using an obsolete/outdated Chromedriver version. Users should really use latest chrome and chromedriver and it should be a hard requirement that the Chromedriver version is compatible with the Chrome version it wants to automate.

**Describe the solution you'd like**
The Chromedriver [session response](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriver/tests/__fixtures__/chromedriver.response.json) contains the Chromedriver and Chrome version. The `webdriver` package should contain a check if the versions are compatible (based on the map defined [here](https://sites.google.com/a/chromium.org/chromedriver/downloads)) and should fail the session if both are incompatible. Optionally it would make sense to print a warning that the user is not using latest Chrome/Chromedriver (there should be no reason why someone would have to test on an older Chrome version).

**Describe alternatives you've considered**
None considered.

**Additional context**
The following PR (https://github.com/webdriverio/webdriverio/pull/3347) was made due to the fact that an outdated Chromedriver version was used.

**Comment by RajaBellebon** [comment]
@christian-bromann sorry to jump in on this issue but we are facing an issue related to incompatibility check for Chrome.

In our repository, we have this setup:
 ```"chromedriver": "^74.0.0",
  ....
 "webdriverio": "^5.8.3",
```
We are using Chrome driver locally as standalone to run our test but we face some issues with https://webdriver.io/docs/api/webdriver.html#maximizewindow and we can see in the logs:
```onsole.error node_modules/@wdio/logger/build/node.js:112
    2019-05-13T04:23:36.070Z ERROR webdriver: Request failed due to Error: unknown error: failed to driver: Request failed due to Error: uent state is normal
      (Session info: chrome=74.0.3729.131)
      (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac600229 (3fae4d0cda5334b4f533bede5a4787```

The Chromedriver version is `2.43.XXX` how is it possible and how can we update it?

Thanks,

Regards,

Raja

(Ps: If I need to raise a different issue, let me know !)

**Comment by abjerstedt** [comment]
@RajaBellebon you need to use chromedriver 74. They started naming the drivers the same as the primary version it supports.

**Comment by RajaBellebon** [comment]
hello @abjerstedt , yes I know, see my message above. In my package.json, we have installed the latest chromedriver and when I type in my repo `chromedriver --version`, I got 74.XXX.

My issue is with Webdriverio, I don't understand why when failing on this particular command, it uses chromedriver 2.43. I have no reference of this version in our repository.

**Comment by abjerstedt** [comment]
@RajaBellebon Because you are likely using selenium-standalone-service and that has absolutely nothing to do with the chromedriver npm package.

**Comment by RajaBellebon** [comment]
@abjerstedt , I checked all my repository and we are no longer using this package at all. Feel free to have a look : https://bitbucket.org/atlassian/atlaskit-mk-2/src/master/

**Comment by abjerstedt** [comment]
@RajaBellebon you are using wdio-chromedriver-service and chromedriver 2.43.

**Comment by RajaBellebon** [comment]
Sorry @abjerstedt , I should have precise on my branch `https://bitbucket.org/atlassian/atlaskit-mk-2/branch/skip-website/BUILDTOOLS-113`. Ok, I'll retry again by removing wdio-chromedriver-service and bumping chromedriver to latest.

Cheers!

**Comment by christian-bromann** [comment]
No need for this anymore as Chromedriver automatically fails with a proper error message.
