### ISSUE TITLE
Multiremote start browser/load page different time

### ISSUE THREAD

**Issue by amiznikov** [webdriverio/webdriverio#3393]
**Describe your question with as much detail as possible**
Hello, i use multiremote for test my webrtc app. I need to start browsers not at the same time, that browser start some interval between each other

**Environment (please complete the following information):**
 - **WebdriverIO version:** 4.14.0

`
const WebdriverIO = require('webdriverio')
const WebdriverRTC = require('webdriverrtc')
const child_process = require('child_process');
const path = require('path')
let browserList = {
        desiredCapabilities: {
            browserName: 'chrome',
        }        
        desiredCapabilities: {
            browserName: 'chrome',
        }                
    };

let matrix = WebdriverIO.multiremote(browserList)

WebdriverRTC.init(matrix, {
    browser: 'browser0'
})

let browsersA = matrix.select(`browser0`);

matrix
    .init()
    .url('https://demostream.whenspeak.ru/public/index.html?server=wss%3A%2F%2Fstream.whenspeak.ru%3A9081%2F&type=viewer&autoplay=false')
    .pause(30000)
    .call(() => {
        return browsersA.startAnalyzing(() => {
            return player.player.webRtcPeer.peerConnection
        }).getConnectionInformation().then((connectionType) => {
            console.log(connectionType)
        }).pause(2000).getStats(2000).then(({err, mean, median, max, min, rawdata}) => {       
            console.log('error:', err)
            console.log('mean:', mean);
            console.log('median:', median);
            console.log('max:', max);
            console.log('min:', min);
            console.log('rawdata', rawdata); 
            })
    })
    .end();
`

**Comment by christian-bromann** [comment]
Instead of using mutiremote you can still initiate two simple remote sessions in your custom test script.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by christian-bromann** [comment]
You can have as much sessions as you want:
```js
const browser = await remote({
    logLevel: 'error',
    path: '/',
    capabilities: {
        browserName: 'firefox'
    }
})
const browser2 = await remote({
    logLevel: 'error',
    path: '/',
    capabilities: {
        browserName: 'firefox'
    }
})
const browser3 = await remote({
    logLevel: 'error',
    path: '/',
    capabilities: {
        browserName: 'firefox'
    }
})
const browser4 = await remote({
    logLevel: 'error',
    path: '/',
    capabilities: {
        browserName: 'firefox'
    }
})
```

**Comment by christian-bromann** [comment]
With multiremote all session have to start at the same time.

**Comment by christian-bromann** [comment]
Not sure what you mean exactly. Please join our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for further questions. Thanks!
