### ISSUE TITLE
Use Custom Commands for database calls doesn't return value, but Promise { <pending> }

### ISSUE THREAD

**Issue by namnt14** [webdriverio/webdriverio#3399]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.3.5
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.4.1
 - **NPM version:** 6.5.0
 - **Browser name and version:** N/A
 - **Platform name and version:** Android Pie and macOS Mojave
 - **Additional wdio packages used (if applicable):** @wdio/spec reporter/jasmine/appium

**Config of WebdriverIO**
exports.config = {
  port: 4723,
  address: "0.0.0.0",
  runner: "local",
  specs: ["./app/\*/specs/\*.js"],
  exclude: [
    // 'path/to/excluded/files'
  ],
  suites: {
    android: [
      "./app/android/specs/login.spec.js",
    ],
    otherFeature: [
      // ...
    ],
  },
  capabilities: [
    {
      // maxInstances can get overwritten per capability. So if you have an in-house Selenium
      // grid with only 5 firefox instances available you can make sure that not more than
      // 5 instances get started at a time.
      maxInstances: 3,
      appiumVersion: "1.9.1",
      automationName: "UiAutomator2",
      platformVersion: "9",
      platformName: "Android",
      deviceName: "Pixel_2_XL_API_28",
      app:
        "~/company/app/native-app/android/app/build/outputs/apk/staging/release/app-staging-release.apk",
      appWaitActivity: "ca.company.*",
      appPackage: "ca.company.companyapp.staging",
    },
  ],
  logLevel: "error",
  deprecationWarnings: true,
  bail: 0,
  baseUrl: "http://localhost",
  waitforTimeout: 60 * 1000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  framework: "jasmine",
  reporters: ["spec"],
  jasmineNodeOpts: {
    defaultTimeoutInterval: 30 * 60000,
    expectationResultHandler: function(passed, assertion) {
      // do something
    },
  },
  /**
   * Gets executed before test execution begins. At this point you can access to all global
   * variables like `browser`. It is the perfect place to define custom commands.
   * @param {Array.<Object>} capabilities List of capabilities details.
   * @param {Array.<String>} specs List of spec file paths that are to be run
   */
 before: function(capabilities, specs) {
    const { getAccount } = require("./utilities/retrieveData")
    browser.addCommand("getAccount", function(picture) {
      return getAccount(picture)
    })
  },
 
**Describe the bug**
function getAccount(picture = false) {
  return new Promise(resolve => {
  ......
  })
}
When I was attempting to call the function by browser.getAccount(false) from my test scripts and executing the script, it always returned Promise { <pending> }, instead of the result from the DB. This code used to work properly in WebdriverIO V4. Just right after I upgraded to V5, it stopped working as expected. The issue seems to be similar to the following one https://github.com/webdriverio/webdriverio/issues/3209 but somehow it's not working in my case.

**To Reproduce**

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
Ensure you do the call within an `it` block or hook.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
