### ISSUE TITLE
Update typescript setup according to mocha 6

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#3404]
**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Description of the improvement / report**

1. Update setup according to mocha 6

- changed compilers to require
- no need to require ts-node/register twice (in before hook and require blocks)

```
// wdio.conf.js
mochaOpts: {
    ui: 'bdd',
    require: [
        'tsconfig-paths/register'
    ]
},
```

2. Update ts-node register command to respect files in tsconfig.json

```
// wdio.conf.js
before: function() {
    require('ts-node').register({ files: true });
},
```

**Comment by mgrybyk** [comment]
From official ts-node doc
```
--files Load files from tsconfig.json on startup (TS_NODE_FILES, default: false)
```

From mocha 6
```
--compilers is no longer supported; 
```
Have to use require instead

**Comment by mgrybyk** [comment]
Will do PR later on today

**Comment by mgrybyk** [comment]
Oops, seems I missed this one, will do it soon

**Comment by christian-bromann** [comment]
thanks

**Comment by mgrybyk** [comment]
@christian-bromann  I see that https://github.com/webdriverio/webdriverio/blob/master/docs/TypeScript.md is up to date however https://webdriver.io/docs/typescript.html is not.

**Comment by christian-bromann** [comment]
Please check again, website deploy is not automated yet (see https://github.com/webdriverio/webdriverio/issues/3053)

**Comment by mgrybyk** [comment]
Thank you, closing
