### ISSUE TITLE
Scripts works with chrome but fails with safari browser 

### ISSUE THREAD

**Issue by PhaniJRavindra** [webdriverio/webdriverio#3406]
Please find the environment as follows,

**Environment (please complete the following information):**
 - **WebdriverIO version:** 4.13.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [8.12.0]
 - **NPM version:** [6.4.1]
 - **Browser name and version:** [safari 12.0.3]
 - **Platform name and version:** [mac os 10.13.6]
 - **Additional wdio packages used (if applicable):** 
 "wdio-allure-reporter": "^0.6.3",
 "wdio-selenium-standalone-service": "0.0.10",
  "wdio-spec-reporter": "^0.1.5",
  "wdio-visual-regression-service": "^0.9.0",
   "webdriverio": "^4.13.1"

**Describe the bug**

While executing the scripts on chrome it works fine without any issues, however few issues are observed in safari,

1. Safari browser not working in headless mode
code:
 safariOptions: {
        args: ['--disable-gpu', '--window-size=1440,800']
    }

2. once the script is executed safari browser is not closing the instance 
3. Elements/popup  not displayed when user mouse hover on an element

code:
browser.moveToObject('selector');
browser.click('selector');

Can any one help on these issues.

**Comment by abjerstedt** [comment]
Issues should only be logges for actual wdio issues. Please reach out on gitter for questions like this.

**Comment by christian-bromann** [comment]
You can find the [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) here.
