### ISSUE TITLE
wdio displays test targets as "undefined" during runtime when testing native apps on mobile devices

### ISSUE THREAD

**Issue by LasseHall** [webdriverio/webdriverio#3408]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.3.0
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v10.13.0
 - **NPM version:** 6.7.0
 - **Browser name and version:** n/a
 - **Platform name and version:** Any mobile device

**Config of WebdriverIO**
Native App testing on mobile devices.

**Describe the bug**
<img width="504" alt="screenshot 2019-01-24 at 20 21 09" src="https://user-images.githubusercontent.com/9463062/51703400-8983db00-2016-11e9-8fde-1b3ef10b4044.png">

**To Reproduce**
Configure wdio to launch native app tests on mobile devices & use the spec reporter

**Expected behavior**
Instead of "undefined" should probably show the value of deviceName desired capability.

**Comment by christian-bromann** [comment]
fixed in #3413
