### ISSUE TITLE
mocha-framework complaining that done() is not called in 5.4.2

### ISSUE THREAD

**Issue by jgoldring** [webdriverio/webdriverio#3410]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.4.2
 - **Mode:** WDIO test runner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 11.6.0
 - **NPM version:** 6.5.0
 - **Additional wdio packages used (if applicable):** @wdio/mocha-framework (5.4.2), @wdio/sync (5.4.2)

**Describe the bug**
While trying to run a test that was working with 5.4.1, I am now getting an error:

> chrome #0-0] Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/noderoot/vod/tests/ui/smoke/simple.home.page.test.js)
> [chrome #0-0] Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/noderoot/vod/tests/ui/smoke/simple.home.page.test.js)
> [chrome #0-0]     at Test.Runnable._timeoutError (/noderoot/node_modules/@wdio/mocha-framework/node_modules/mocha/lib/runnable.js:451:10)
> [chrome #0-0]     at Timeout.<anonymous> (/noderoot/node_modules/@wdio/mocha-framework/node_modules/mocha/lib/runnable.js:262:24)
> [chrome #0-0]     at listOnTimeout (timers.js:324:15)
> [chrome #0-0]     at processTimers (timers.js:268:5)

Looking through the wdio logs (set to trace) the test does everything properly in ~5-10s, but fails due to the overall mocha timeout of 2 minutes. Looking at the changes from 5.4.1 -> 5.4.2, it looks like the fiber wrapper function removed the done() callback in favour of resolving as a promise (in packages/wdio-config/src/shim.js):

```
export let runFnInFiberContext = (fn) => {
    return function (...args) {
        return Promise.resolve(fn.apply(this, args))
    }
}
```
I think mocha-framework needs to be updated to conform to this new behavior, as I think it is still passing in a done() function that never gets called. Can anyone confirm this? I would love to take a crack at issuing a pull request, but I'm not sure I will have time for it, and this issue will cause anyone using wdio 5.4.2 with mocha-framework 5.4.2 in sync mode to error out. 

**To Reproduce**
Run a test using sync mode, wdio test runner, and mocha-framework on version 5.4.2

**Comment by christian-bromann** [comment]
> Looking through the wdio logs (set to trace) the test does everything properly in ~5-10s, but fails due to the overall mocha timeout of 2 minutes.

Your test exceeds the mocha timeout for tests. You need to increase that timeout, see https://webdriver.io/docs/timeouts.html

**Comment by jgoldring** [comment]
It doesn't, my mocha timeout is set to 2 minutes, and I can see in the browser logs that the entirety of the test (which is just a simple navigate to website) completes in less than 10 seconds.

More to the point, this simple test works just fine as is in 5.4.1, but fails in 5.4.2, and I'm fairly certain it is because the node fibre context is not calling done() like mocha expects.

**Comment by jgoldring** [comment]
I'll post comparison trace logs of 5.4.1 and 5.4.2 to show that the test does the exact same thing in both versions, but in 5.4.2 (with the changes I indicated in my initial report) just hangs for the full 2 minutes

**Comment by jgoldring** [comment]
Instead of logs, here is an easily reproducible example:
1. mkdir wdiologs
2. npm install: 
```
    "dependencies": {
        "@wdio/cli": "5.4.1",
        "@wdio/local-runner": "5.4.1",
        "@wdio/mocha-framework": "5.4.1",
        "@wdio/spec-reporter": "^5.2.3",
        "@wdio/sync": "5.4.1",
        "chai": "*",
        "webdriverio": "5.4.1"
    }
```
3. Run selenium locally
**Config gist: https://gist.github.com/jgoldring/ce49362adb0ef133edbb0014dbb8f035**
**Test gist: https://gist.github.com/jgoldring/98e1a78f63844be99d4d1b185a260c51**
4. node_modules/.bin/wdio --hostname=127.0.0.1 --port=4444 wdio.conf.js

It will work no problem. Now repeat the exact same steps, except npm install:
    "dependencies": {
        "@wdio/cli": "5.4.2",
        "@wdio/local-runner": "5.4.2",
        "@wdio/mocha-framework": "5.4.2",
        "@wdio/spec-reporter": "^5.2.3",
        "@wdio/sync": "5.4.2",
        "chai": "*",
        "webdriverio": "5.4.2"
    }

Look at the logs in wdiologs. The test does the exact same thing in the same amount of time, but the entire test will timeout claiming you have hit your mocha timeout. @christian-bromann
