### ISSUE TITLE
Allow to replace heavy request module with something more simplified

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#3426]
**Is your feature request related to a problem? Please describe.**
Currently the `webdriver` package relies on the request package to connect with the automation driver. The desire of the `webdriver` package is to be lightweight, non opinionated and allow to be run in any environment (e.g. not only Node.js). The request module that is currently a hard dependency prevents this due to the huge amount of dependencies is adds to the package.

**Describe the solution you'd like**
Allow to strip out the request module with something simpler and more lightweight.

**Additional context**
Currently @jlipps is working on a project that would allow to run `webdriver` tests from the browser. Bundling the current `webdriver` package via WebPack creates a 1.5mb big file due to all the request dependencies.

**Comment by abjerstedt** [comment]
Depending on what you mean by this, I'm not in favor (unless its an optional execution method).

Running requests via the browser opens up significant vulnerabilities.

I recently experimented with moving all of our backend api calls into the browser (figured it was more production like and cookie handling was easier). I quickly learned that cloud service providers were logging everything including sensitive api keys.

**Comment by christian-bromann** [comment]
> Running requests via the browser opens up significant vulnerabilities.

Probably but this isn't supposed to be used on a production website. This should allow someone to make webdriver request from the browser to control a different browser. If we can strip the amount of dependencies down without loosing any features I think this is a considerable value add.

**Comment by abjerstedt** [comment]
Again - If this is OPTIONAL feature, I'm not opposed to it. If the problem is specifically with 'request', we can look into 'node-fetch' or 'isomorphic-fetch'. 

If this becomes a core change (running requests in a browser), I can with absolute certainty tell you that my company will abandon webdriverio, as will almost all financial institutions.

Also: the assumption that this isn't supposed to be used on a production website is overstep. The definition of production is changing as CICD evolves; For example: In a blue-green environment you may still run your tests against www.production.com, but use a cookie or a header to determine which origin you get.

**Comment by jlipps** [comment]
It opens up lots of possibilities, like web apps that can run Appium tests, etc... Of course one should always be careful not to run proprietary test code on an untrusted website.

And yes, this is an optional, marginal use case. There would be no plan to change the default (node) execution or expose the default execution to a browser context.

**Comment by Antonius-S** [comment]
Upvote this. Request has 60 (!) dependencies most of which are useless for WD.

**Comment by CrispusDH** [comment]
One of option - [GOT](https://github.com/sindresorhus/got) from Sindre Sorhus maintainer with install size `302 kB`.

**Comment by Antonius-S** [comment]
Axios has only 5 deps
Got has 24

**Comment by jlipps** [comment]
@abjerstedt the idea behind this feature is not to make wdio run through a browser. only to make the wdio package amenable to other implementations who might want to use it in a browser. wdio itself would remain purely node-based and involve no browser usage whatsoever.

**Comment by abjerstedt** [comment]
I retracted my thumbs down during our last discussion on this :D, you don't need to sell this to me anymore.

**Comment by jlipps** [comment]
@abjerstedt whoops I also forgot that I had already replied above, sorry for the extra convincing :-p

**Comment by christian-bromann** [comment]
I am happy to replace `request` with a more lightweight package, I consider using

- https://github.com/bitinn/node-fetch
- https://github.com/sindresorhus/got#readme

Any PR would be appreciated 😊

**Comment by wswebcreation** [comment]
I vote for node-fetch, no dependencies and my favorite 😊

**Comment by CrispusDH** [comment]
You should aware about https://github.com/bitinn/node-fetch/issues/567 if you choose `node-fetch`

**Comment by CrispusDH** [comment]
> The desire of the `webdriver` package is to be lightweight, non opinionated and allow to be run in any environment (e.g. not only Node.js).

> Currently @jlipps is working on a project that would allow to run `webdriver` tests from the browser.

I see **two** main points:
- library should be **lightweight**
- library approach should work **on both** Node.js and Browser

1) `Got` is for `Node.js` only
2) `node-fetch` library does not have maintenance a long time and as I understood it is for `Node.js`

After some research I think it would be better to separate code for `Node.js` and for browsers. What do you think?

**Comment by jlipps** [comment]
@CrispusDH that was my original idea, too, to have two different request classes that implement the same interface, one for node and one for web.

**Comment by CrispusDH** [comment]
@christian-bromann could you share your opinion?

**Comment by christian-bromann** [comment]
My interest in this has increased due to the fact that I want to build a web socket on version for connecting with the browser. So it would be ideal to not only replace the request lib but also allow a different kind of connection.

**Comment by baruchvlz** [comment]
I would vote for axios over node-fetch or got. It's only [12kb](https://bundlephobia.com/result?p=axios@0.18.0) and has [2 dps](https://github.com/axios/axios/blob/master/package.json#L75-L78).

**Comment by christian-bromann** [comment]
Added to the `WebdriverIO Fiddle Platform` project as it is required to run tests on e.g. Sauce Labs directly from the browser.

**Comment by christian-bromann** [comment]
> @christian-bromann could you share your opinion?

I would keep it simple and replace the current requirement on `request` with `axios` given that `node-fetch` is not maintained anymore.

**Comment by christian-bromann** [comment]
Started with this effort. Progress can be found here: #4708
