### ISSUE TITLE
Be able to configure / disable particular logger

### ISSUE THREAD

**Issue by xlenz** [webdriverio/webdriverio#3440]
**Is your feature request related to a problem? Please describe.**
There is no way to enable/disable or configure specific logger.

Example: it is not possible to disable one of or all driver logs.

**Describe the solution you'd like**
it should be possible to do something like:
```
    // Set specific log levels per logger. Use 'silent' level to disable logger
    logLevels: {
        webdriver: 'info',
        'wdio-applitools-service': 'info'
    },

    // If outputDir is provided WebdriverIO can capture driver session logs
    // it is possible to configure which logTypes to include/exclude.
    driverLog: {
        // include: ['logcat'], // only include certain types of logs
        exclude: ['bugreport', 'server']
    }
```
**Describe alternatives you've considered**
be able to enable / disable particular logger at least somehow

**Comment by christian-bromann** [comment]
I would not want to introduce a new `logger` option for this but I agree that it would be helpful to disable log types.

**Comment by mgrybyk** [comment]
Shall I do a PR for this?
