### ISSUE TITLE
Tests does not fail on not called method in async mode

### ISSUE THREAD

**Issue by sipayRT** [webdriverio/webdriverio#3447]
**Environment:**
 - **WebdriverIO version: 4.14.1|5.4.7 (both)**
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async: async**
 - **Node.js version: 8.6.0**
 - **NPM version: 6.2.0**
 - **Browser name and version: Chrome 71**
 - **Platform name and version: MacOS Mojave (10.14.2)**
 - **Additional wdio packages used (if applicable):
    - @wdio/local-runner
    - @wdio/mocha-framework
    - @wdio/spec-reporter
    - @wdio/cli

**Config of WebdriverIO**
```js
exports.config = {
    runner: 'local',
    specs: ['common.test.js'],
    maxInstances: 10,
    capabilities: [{
        maxInstances: 5,
        browserName: 'chrome'
    }],
    logLevel: 'info',
    deprecationWarnings: true,
    bail: 0,
    baseUrl: 'http://yandex.ru',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    }
}

```

**Describe the bug**
If someone will add to test (in async mode) command without calling it test always will be marked as successfully passed.

**To Reproduce**
1. install wdio with autogenerated config (run `wdio config` command) without `@wdio/sync` package
2. write test with mistake:

```js
describe('Common describe', function() {
    it('some it', function() {
        return browser
            .url('')
            .then(() => {
                throw new Error('ololo');
            })
            .unknownCommand; // <-- not called command
    });
});
```
3. Run test
As a result this test will be marked as successfully passed, not failed. In logs I can see warning about unhandled promise rejection, but tests are green.

**Expected behavior**
Test should be marked as failed.

**Log**
[testrunner log](https://gist.github.com/sipayRT/e02ade3e45de9e014ed4a0d02f37825a)
[selenium-standalone logs](https://gist.github.com/sipayRT/4f784da4d5e79cf25f8d202a178c429f)

**Comment by sipayRT** [comment]
yes, and as I know in wdio it's not clear promises, but some custom realization. And it reproduced in v4 too

**Comment by christian-bromann** [comment]
@sipayRT this looks like a Mocha thing. I am not even saying that this is a bug because you return undefined which can't be detected by WebdriverIO nor Mocha. I recommend use the sync version of the testrunner or work with async/await.

**Comment by sipayRT** [comment]
> this looks like a Mocha thing

what the different if I use your project now? :)

> I am not even saying that this is a bug because you return undefined which can't be detected by WebdriverIO nor Mocha

node notice about test error in logs (wdio groups such logs to `Stderr` section). Why don't you try to handle such errors?

```
Stderr:
[0-0] (node:63485) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ololo
```

**Comment by christian-bromann** [comment]
> what the different if I use your project now? :)

There is no difference in running unit tests using mocha or e2e tests using webdriverio with mocha

> Why don't you try to handle such errors?

Because I can't. You return undefined so I don't know whether there is a promise in the test. The error is thrown on next tick and causes this error to appear.
