### ISSUE TITLE
Ability to add custom command without promisifying it

### ISSUE THREAD

**Issue by xlenz** [webdriverio/webdriverio#3449]
**Is your feature request related to a problem? Please describe.**

I want to add sync commands like isMobileApp, isMobileWeb, etc and use them in class constructors or similar, without resolving them as promises 

**Describe the solution you'd like**

add additional argument promisify = true to 
`browser.addCommand(name, function, attachToElement = false, promisify = true)`

**Describe alternatives you've considered**

- instead of adding argument to addCommand introduce method browser.addCommandSync (or something like that)

- Alternatively, add isMobileApp and isMobileWeb to webdriverio 

**Additional context**

my command looks like
```
browser.addCommand("isMobileApp", (): boolean => browser.isMobile && !browser.capabilities.browserName)
```

and I want it to return true/false instead of Promise

**Comment by mgrybyk** [comment]
Can do PR if needed for whatever approach is chosen or suggested

**Comment by christian-bromann** [comment]
You can just assign it directly to the browser like

```js
browser.isMobileApp = browser.isMobile && !browser.capabilities.browserName
``` 

This should do the trick. Until there is a need to use this flag internally in commands or whatever I don't see a need for this.

**Comment by mgrybyk** [comment]
Stupid me, thanks
