### ISSUE TITLE
Feature request: add SL RDC option to the config

### ISSUE THREAD

**Issue by wswebcreation** [webdriverio/webdriverio#3451]
**Is your feature request related to a problem? Please describe.**
Currently we use the `@wdio/config` package to determine the proper hostname for the EU/US DC VM-cloud. WDIO doesn't have a option to preselect the SL RDC urls.
We currently also don't have a proper way for the `@wdio/sauce-service` to check which url and data is needed to start a SC-tunnel for the RDC. Having a SL RDC option would also solve that problem.

**Describe the solution you'd like**
I'd like to add an option to the `wdio.conf.js`-file that will tell the `@wdio/config` that this config is being used for the SL RDC. Still need to come up with a proper name, but it could look like this in the config

```js
    // =================
    // Service Providers
    // =================
    // WebdriverIO supports Sauce Labs, Browserstack, and Testing Bot (other cloud providers
    // should work too though). These services define specific user and key (or access key)
    // values you need to put in here in order to connect to these services.
    //
    user: 'webdriverio',
    // If this is a Sauce Labs Real Device test this key should not be provided.
    key:  'xxxxxxxxxxxxxxxx-xxxxxx-xxxxx-xxxxxxxxx',
    //
    // If you run your tests on the SauceLabs real device cloud you can enable this with this option.
    // This will automatically set the correct hostname based on the region you've provided
    realDeviceTest: true,
    //
    // If you run your tests on SauceLabs you can specify the region you want to run your tests
    // in via the `region` property. Available short handles for regions are:
    // us: us-west-1 (default)
    // eu: eu-central-1
    // This also handles the selection of the US / EU Real Device cloud of Sauce Labs
    region: 'us',
```

I can pick this up if you want me to, this can then be used to update the `@wdio/sauce-service` to support a SC-tunnel for the RDC.

There's already a PR open for updating the status of the running testjob in the SL RDC, see https://github.com/webdriverio/webdriverio/pull/3446

Please let me know if you have different thoughts about it

**Comment by wswebcreation** [comment]
@christian-bromann
 I was looking into that but as far I could see we are not able to to determine that based on the capabilities, because they are not available there. But correct me if I'm wrong and if I'm checking the wrong files.

If we have access to the capabilities, we can check if we have the 'testobject_api_key', if so we can use the region and determine the correct url

**Comment by wswebcreation** [comment]
This can be closed, the PR has been merged https://github.com/webdriverio/webdriverio/pull/3468

**Comment by christian-bromann** [comment]
Thanks for implementing it 👍
