### ISSUE TITLE
Chain after waitForExist and waitForDisplayed

### ISSUE THREAD

**Issue by xlenz** [webdriverio/webdriverio#3455]
**Is your feature request related to a problem? Please describe.**
I want to be able to chain after waiting for element
```
$("a").waitForDisplayed(20000).click()
// or
$("div").waitForExist().getAttribute("class")
```

**Describe the solution you'd like**
await for waitUntil in waitForExist and waitForDisplayed functions and return elementInstance

**Describe alternatives you've considered**
close this feature request in case it is not helpful / usage is invalid or suggest your version

**Additional context**
can do PR if feature request is approved

**Comment by christian-bromann** [comment]
Thanks for making the request @xlenz .. I deliberately moved away from chaining commands because it created confusion around which commands are chainable and which not. I don't see a value add from being able to do:
```js
$("a").waitForDisplayed(20000).click()
```
instead of
```
const elem = $("a")
elem.waitForDisplayed(20000)
elem.click()
```
