### ISSUE TITLE
Devtools Service - Couldn't connect to chrome (Remote Device)

### ISSUE THREAD

**Issue by ml497** [webdriverio/webdriverio#3458]
Hi, I've been trying to get devtools-service working with some remote devices on testobject.  I've followed the instructions in the readme, but it seems I am still missing something.  The error that I get specifically is this:

`wdio-devtools-service: 
Couldn't connect to chrome: TypeError: Cannot read property '1' of null
    at findCDPInterface (/Users/matthias.lenz/IdeaProjects/mocha-js-example/node_modules/@wdio/devtools-service/build/utils.js:51:75)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)`

I can see that findCDPInterface is first attempting to resolve whether or not global.browser.capabilities['goog:chromeOptions'] contains a debuggerAddress.  Should I be providing this through wdio.conf.js and point to the device ip and chrome port there?  The reason I ask is that I thought this kind of information might be resolved by the service itself.  

Many thanks in advance!

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.4.8
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 7.10.1
 - **NPM version:** 4.2.0
 - **Browser name and version:** Chrome 71
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** 
    "@wdio/cli": "5.4.8",
    "@wdio/devtools-service": "5.4.6",
    "@wdio/local-runner": "5.4.8",
    "@wdio/mocha-framework": "5.4.8",
    "@wdio/sync": "5.4.6"

**Comment by christian-bromann** [comment]
> with some remote devices on testobject

This service only works if you run tests locally on your machine meaning that you use a Chrome browser that is installed on your machine. I am working extending the WebDriver protocol to allow using the browsers devtools interface but it will take a little bit more until I can release something.

**Comment by lukefox-distilled** [comment]
> > with some remote devices on testobject
> 
> This service only works if you run tests locally on your machine meaning that you use a Chrome browser that is installed on your machine. I am working extending the WebDriver protocol to allow using the browsers devtools interface but it will take a little bit more until I can release something.

Hi, is there any update on this feature?

**Comment by christian-bromann** [comment]
> Hi, is there any update on this feature?

What kind of updates you are hoping for here?

**Comment by lukefox-distilled** [comment]
Just if it's possible to connect to chrome remotely while using the DevTools service.

**Comment by christian-bromann** [comment]
Technically it should be possible. The only problem is to find the IP of the machine where Chrome is running and ensure that you have access to access the devtools port. While it seems possible to get that data it often turns out to be not applicable due to security restrictions.
