### ISSUE TITLE
browser.url does not update history state with react-router / cordova

### ISSUE THREAD

**Issue by maurocolella** [webdriverio/webdriverio#3459]
I am trying to use `browser.url(`${baseUrl}${path}`);` with React in a Cordova application.

In my desktop browser, changing the location updates routes and state as expected. The test suite is run with appium, and while the url itself is changed (I can waitUntil for it, test it), the change doesn't seem to reflect on the state of react-router.

**Environment:**
 - **WebdriverIO version:** `^4.14.2`
 - **Mode:** `wdio-appium-service`
 - **If WDIO Testrunner, running sync/async:** `sync`
 - **Node.js version:** `9.3.0`
 - **NPM version:** `5.5.1`
 - **Browser name and version:** `Chrome/Webview 69.0.3497.100` 
 - **Platform name and version:** `Android 28`

**Additional context**
`react-router: "4.1.2"`, `"react": "16.2.0"`, `"redux": "3.7.2"`

The type of react-router history is a `BrowserHistory`. 

Although this is probably not a "bug", the fact that the behavior diverges between manual browser use   and automated tests has me stumped. How can I produce output that I can use to debug?

**Comment by maurocolella** [comment]
Apologies. I found this:
https://webdriver.io/docs/api/browser/debug.html

And seem to have sorted issues out. In my case, due to an incorrect base url.

**Comment by maurocolella** [comment]
Actually:

urls are reported as `file:///`.

But if I try to explicitly set a url using this format, it doesn't load. I get a 404 and tests fail.

**Comment by christian-bromann** [comment]
> urls are reported as `file:///`.

What do you mean by that?

I don't really see a problem in WebdriverIO here. It can only send request to the driver to change the url but if the driver is not capable to do that the bug needs to be reported there.

**Comment by maurocolella** [comment]
@christian-bromann what I mean is: on Cordova for Android, all urls are relative to
`file:///android_asset/www`

Which causes errors of the type:
`"Cannot navigate to invalid URL"`

For documentation purposes, I believe it's related to:
https://github.com/ReactTraining/react-router/issues/2161

So, indeed, possibly a driver issue, and a workaround is to use `HashHistory` for Cordova.
