### ISSUE TITLE
'Socket hang up' errors started occurring consistently (but intermittently on different tests/steps) after 8-11 sceanarios in a wdio-cucumber-framework feature file

### ISSUE THREAD

**Issue by osmolyar** [webdriverio/webdriverio#3460]
The following 'socket hang up' error occurs on different steps starting on the 8th to 11th scenario in a given feature file, where the previous scenarios, usually with the same sequence of steps as the failing one, run fine.  Up until last November, all were running fine and passing, for ~1yr.

The subsequent  4 tests also fail with 'socket hang up', while the following few tests will fail with error 'A session id is required for this command but wasn't found in the response payload', and then will start passing again.

A new session is started with each scenario, as browser.reload() gets called on starting a scenario.  The initial 'socket hang up' error occurs usually 4-5 steps into the scenario, while subsequent ones occur on the first step of the scenario.

This is on Chrome, and was working perfectly until ~last November.   Similar intermittent 'A session id is required for this command but wasn't found in the response payload' errors had always occurred on IE10 and IE11 (with no 'socket hang up').

Concurrent with the error, a browser window gets opened but doesn't get resized or attempt to navigate to the application url, and stays open while new windows get generated for new scenarios.

It happens with every feature file run, both using selenium-standalone locally, wdio testrunner and Selenium Grid Extras via Jenkins.

"Error: socket hang up
                    at createHangUpError (_http_client.js:302:15)
                    at Socket.socketOnEnd (_http_client.js:394:23)
                    at emitNone (events.js:91:20)
                    at Socket.emit (events.js:186:7)
                    at endReadableNT (_stream_readable.js:974:12)
                    at _combinedTickCallback (internal/process/next_tick.js:74:11)
                    at process._tickDomainCallback (internal/process/next_tick.js:122:9)"

**Environment (please complete the following information):**

selenium-standalone 3.141.0
 - **WebdriverIO version:** 4.8.0
 - **Mode:** Both 
 - **If WDIO Testrunner, running sync/async:**  sync
 - **Node.js version:**  8.9.0
 - **NPM version:** 5.6.0
 - **Browser name and version:**  Chrome 71.0.3578.98
   --Driver:  Chromedriver 2.45.0
 - **Platform name and version:** Any : Windows 10, Windows 8.1
 - **Additional wdio packages used (if applicable):** 
wdio-cucumber-framework:  1.1.0

**Additional context**

With chromedriver versions <=2.43, the following concurrent error also occurs in the selenium log as noted below, with trace:  "java.lang.IllegalStateException: Committed".

With chromedriver 2.45, the same 'Socket hang up' error occurs as the step error in the wdio output, but the java.lang.illegalStateException: Committed is not output, and instead the selenium-standalone log shows multiple sessions created and removed without intervening output, as follows:

Starting ChromeDriver 2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387) on port 42068
Only local connections are allowed.
15:51:45.018 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
15:51:45.033 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session ee949d62bb60cec80c97246fe5f21c13 (org.openqa.selenium.chrome.ChromeDriverService)
15:51:45.506 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
15:51:45.538 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session ff3758d7f2582b39ee02e3f6657ebabd (org.openqa.selenium.chrome.ChromeDriverService)
15:51:46.887 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
15:51:46.921 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 40e0db5140996cd8a2e044f1901aeea6 (org.openqa.selenium.chrome.ChromeDriverService)
15:51:52.438 INFO [ActiveSessions$1.onStop] - Removing session 

This corresponds to logger output of messages being logged in before and after-scenario hooks, like

"in beforeScenario
in afterScenario
in beforeScenario
in afterScnenario"

without intervening logging, which normally occurs while a scenario is executed.  (The 'Socket hang up' error is output at then end of the run, as the Step/scenario error trace).

With the 'code to reproduce' zip file, as the application being tested is not available due to a firewall, a different baseUrl (with a valid server) is substituted.  In this case the 'Socket hang up' error is not, unfortunately, reproduced, but the same behavior with intermittent scenarios being aborted with an 'ECONNECT refused' error and a blank browser generated, while other scenarios attempt to get executed and only fail when failing to find specified selectors.  

Allure-report.zip where, if you filter out all passing and failed TCs, you can see each feature file with >9 scenarios hits the 'socket hang up' at TC8,9,10,11 or12:
[allure-report.zip](https://github.com/webdriverio/webdriverio/files/2828491/allure-report.zip)

**Comment by christian-bromann** [comment]
Can you try with the latest WebdriverIO version? Also could you provide all logs that are available to you?

**Comment by osmolyar** [comment]
Just installed latest webdriverio and wdio globally, and now 'wdio is not recognized' despite deleting, reinstalling, etc. (Someone else just ran into the same issue as well after installing these.)

**Comment by abjerstedt** [comment]
@osmolyar just to clarify - you didn't install v5 did you? V5 does NOT support cucumber yet.

**Comment by osmolyar** [comment]
you mean webdriverio v5?

Binary is fine; exiting
+ webdriverio@5.4.8
+ wdio@3.0.0

**Comment by osmolyar** [comment]
Ok, got it, 

+ webdriverio@4.14.2

and now wdio works.  Will update further.

**Comment by abjerstedt** [comment]
@osmolyar wdio is completely usable in v5... your npm script is just broken (hence the reason it says its not found).

But again, v5 doesn't currently support cucumber.

**Comment by osmolyar** [comment]
ok, thank you, it seems to be running now (and wdio batch script appeared under npm/ upon installing webdriverio@4)

**Comment by osmolyar** [comment]
Hi, sorry for the confusion.  I just meant that wdio is now runnable, not that the original issue is resolved.

**Comment by BorisOsipov** [comment]
@osmolyar in issue you wrote
>Browser name and version: Chrome 71.0.3578.98
>--Driver: Chromedriver 2.45.0

but in log `Starting ChromeDriver 2.43.600210`

try to update chromedriver. it may help.

**Comment by osmolyar** [comment]
After making sure selenium-standalone was starting with chromedriver 2.45, the 'socket hang up' still occurred but an error like the above didn't occur in the selenium-standalone output, in which all Start session entries look like

}
15:15:11.223 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387) on port 43601
Only local connections are allowed.
15:15:13.531 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
15:15:13.547 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 174fc42cca5b5ae3b854c04bddedfc84 (org.openqa.selenium.chrome.ChromeDriverService)
15:16:10.089 INFO [ActiveSessions$1.onStop] - Removing session 174fc42cca5b5ae3b854c04bddedfc84 (org.openqa.selenium.chrome.ChromeDriverService)
15:16:10.105 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "chrome",
  "chromeOptions": {
    "prefs": {
      "credentials_enable_service": false,
      "profile": {
        "password_manager_enabled": false
      }
    },
    "args": [
      "--no-sandbox",
      "--start-maximized",
      "--disable-cache",
      "--disable-application-cache",
      "--disable-offline-load-stale-cache",
      "--disk-cache-size=0",
      "--v8-cache-options=off",
      "--disable-infobars"
    ]
  },


But in the wdio output, the following is found: 
"In beforeScenario
Setting viewport size
F.....In afterScenario
In beforeScenario
F.....In afterScenario
In beforeScenario
F.....In afterScenario
In beforeScenario
[15:02:21]      Failed to take screenshot on reject:     {"type":"NoSessionIdError","message":"A session id is required for this command but wasn't found in the response payload"}
Error in onReload hook: "Error: Don't call the 'init' command when using the wdio test runner. Your session will get initialised and closed automatically.
    at execute(<Function>) - C:\Users\osmolyar\AppData\Roaming\npm\node_modules\webdriverio\build\lib\commands\setViewportSize.js:87:12"
Setting viewport size
[15:02:21]      Failed to take screenshot on reject:     {"type":"NoSessionIdError","message":"A session id is required for this command but wasn't found in the response payload"}
[15:02:21]      Failed to take screenshot on reject:     {"type":"NoSessionIdError","message":"A session id is required for this command but wasn't found in the response payload"}
[15:02:21]      Failed to take screenshot on reject:     {"type":"NoSessionIdError","message":"A session id is required for this command but wasn't found in the response payload"}
Error in onReload hook: "Error: Don't call the 'init' command when using the wdio test runner. Your session will get initialised and closed automatically.
    at windowHandleSize() - C:\Users\osmolyar\AppData\Roaming\npm\node_modules\webdriverio\build\lib\commands\setViewportSize.js:72:17"
Setting viewport size
[15:02:21]      Failed to take screenshot on reject:     {"type":"NoSessionIdError","message":"A session id is required for this command but wasn't found in the response payload"}
[15:02:21]      Failed to take screenshot on reject:     {"type":"NoSessionIdError","message":"A session id is required for this command but wasn't found in the response payload"}
Error in onReload hook: "Error: Don't call the 'init' command when using the wdio test runner. Your session will get initialised and closed automatically.
    at windowHandleSize() - C:\Users\osmolyar\AppData\Roaming\npm\node_modules\webdriverio\build\lib\commands\setViewportSize.js:72:17"
Setting viewport size
[15:02:21]      Failed to take screenshot on reject:     {"type":"NoSessionIdError","message":"A session id is required for this command but wasn't found in the response payload"}"


Other things I've tried: 
-setting 'DBUS_SESSION_BUS_ADDRESS=/dev/null', supposedly to prevent chrome deadlock
-adding --no-sandbox to chrome options args.

**Comment by abjerstedt** [comment]
You aren't actually passing ANY chromeOptions to chromedriver at the moment; and you should be treating the output as such.

chromeOptions is no longer the correct object name, and you need to pass 'goog:chromeOptions' instead.

**Comment by osmolyar** [comment]
Thanks; updated.  Still the same behavior though - when the issue occurs, the log shows 3 new instances of 'Started a new session', but without the subsequent ActiveSessions:onStop and ActiveSessionFactoryApply messages for the first two, and two empty browser windows are opened and not closed.

15:51:43.809 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387) on port 42068
Only local connections are allowed.
15:51:45.018 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
15:51:45.033 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session ee949d62bb60cec80c97246fe5f21c13 (org.openqa.selenium.chrome.ChromeDriverService)
15:51:45.506 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
15:51:45.538 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session ff3758d7f2582b39ee02e3f6657ebabd (org.openqa.selenium.chrome.ChromeDriverService)
15:51:46.887 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
15:51:46.921 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 40e0db5140996cd8a2e044f1901aeea6 (org.openqa.selenium.chrome.ChromeDriverService)
15:51:52.438 INFO [ActiveSessions$1.onStop] - Removing session ee949d62bb60cec80c97246fe5f21c13 (org.openqa.selenium.chrome.ChromeDriverService)
15:51:52.478 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "chrome",
  "goog:chromeOptions": {
    "prefs": {
      "credentials_enable_service": false,
      "profile": {
        "password_manager_enabled": false
      }
    },
    "args": [
      "--no-sandbox",
      "--start-maximized",
      "--disable-cache",
      "--disable-application-cache",
      "--disable-offline-load-stale-cache",
      "--disk-cache-size=0",
      "--v8-cache-options=off",
      "--disable-infobars"
    ]
  },

I'll try to create a minified version of code to reproduce the issue.

**Comment by osmolyar** [comment]
Code to reproduce the issue, temporarily attached.  Run 'wdio testConfig/wdio.local.config.js --suite users' to reproduce.  Not 100% sure it will work without having an application to hit, though. (checking)
[CodeToReproduceSocketHangUp.zip](https://github.com/webdriverio/webdriverio/files/2814422/CodeToReproduceSocketHangUp.zip)

**Comment by osmolyar** [comment]
Confirming that the code in the currently attached zip file above (updated) amply reproduces the issue by running

wdio testConfig/wdio.local.config.js --suite namespace

or one of the above commands, even while failing at the first step of every TC (since the url doesn't exist).

**Comment by osmolyar** [comment]
The zip file attached above (updated) does reproduce the same behavior with multiple blank chrome browsers being opened and not closed for random test cases, (looks like screenshot here)
![image](https://user-images.githubusercontent.com/15637471/52070692-62199a80-254f-11e9-8a97-8e3f944fb406.png),

 and the selenium-standlaone log concurrently outputs the same  output as seen yesterday concurrently with the 'socket hang up' errors, with multiple sessions being started without intervening output - however the actual 'Socket hang up' error is not reproduced.

The behavior is remarkably similar in that multiple test cases before and after this intermittent failure successfully navigate to the url (and subsequently fail as expected, because locators are incorrect).  

}
11:56:30.816 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387) on port 21848
Only local connections are allowed.
11:56:33.227 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
11:56:33.243 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session f53b311add5aab1474d1e95782f93726 (org.openqa.selenium.chrome.ChromeDriverService)
11:56:33.243 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
11:56:33.259 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 4c1ffbd331b8f8dc6e6ac60188e1b6d5 (org.openqa.selenium.chrome.ChromeDriverService)
11:56:49.021 INFO [ActiveSessions$1.onStop] - Removing session f53b311add5aab1474d1e95782f93726 (org.openqa.selenium.chrome.ChromeDriverService)
11:56:49.036 INFO [ActiveSessionFactory.apply] - Capabilities are: {

**Comment by osmolyar** [comment]
After enabling debug on selenium-standalone and verbose logging on wdio:

selenium-standalone log looks the same as yesterday after upgrading driver (back to back 'Started new session' messages; no initial 'java.lang.IllegalStateException: Committed' trace from chromedriver:

Starting ChromeDriver 2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387) on port 13302
Only local connections are allowed.
15:47:11.260 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
15:47:11.277 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 7e72a95574f50ba4d77639fbf345f9fe (org.openqa.selenium.chrome.ChromeDriverService)
15:47:12.219 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
15:47:12.238 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session f92f1d0bdcc1eb54776b9e168393f96c (org.openqa.selenium.chrome.ChromeDriverService)

and the verbose wdio output for the corresponding sessions looks like:


  Checking for existence of:   //*[@id="zenhint_26"]
[15:47:08]  COMMAND     POST     "/wd/hub/session/c97478cd45452594a923f351c8d01cc5/elements"
[15:47:08]  DATA                {"using":"xpath","value":"//*[@id=\"zenhint_26\"]"}
F[15:47:08]  RESULT             [{"ELEMENT":"0.7309975356086673-8"}]
[15:47:08]  COMMAND     POST     "/wd/hub/session/c97478cd45452594a923f351c8d01cc5/elements"
[15:47:08]  DATA                {"using":"xpath","value":"//*[@id=\"zenhint_26\"]"}
**...In afterScenario
In beforeScenario**
[15:47:08]  RESULT              [{"ELEMENT":"0.7309975356086673-8"}]
[15:47:08]  COMMAND     GET      "/wd/hub/session/c97478cd45452594a923f351c8d01cc5/element/0.7309975356086673-8/attribute/class"
[15:47:08]  DATA                {}
[15:47:08]  COMMAND     DELETE   "/wd/hub/session/c97478cd45452594a923f351c8d01cc5"
[15:47:08]  DATA                {}
[15:47:08]  RESULT              "helpText"
  Checking for existence of:   //*[@id="zenhint_35"]
[15:47:08]  COMMAND     POST     "/wd/hub/session/c97478cd45452594a923f351c8d01cc5/elements"
[15:47:08]  DATA                {"using":"xpath","value":"//*[@id=\"zenhint_35\"]"}
[15:47:08]  RESULT              []
  Checking for existence of:   //*[@id="zenhint_34"]
[15:47:08]  COMMAND     POST     "/wd/hub/session/c97478cd45452594a923f351c8d01cc5/elements"
[15:47:08]  DATA                {"using":"xpath","value":"//*[@id=\"zenhint_34\"]"}
**F.....In afterScenario
In beforeScenario**
_[15:47:08]  COMMAND     DELETE   "/wd/hub/session/c97478cd45452594a923f351c8d01cc5"_
[15:47:08]  DATA                {}
**F.....In afterScenario
In beforeScenario**
_[15:47:08]  COMMAND     DELETE   "/wd/hub/session/c97478cd45452594a923f351c8d01cc5"_
[15:47:08]  DATA                {}
[15:47:08]  COMMAND     POST     "/wd/hub/session"
[15:47:08]  DATA                {"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"chrome","goog:chromeOptions":{"prefs":{"credentials_enable_service":false,"profile":{"password_manager_enabled":false}},"args":["--no-sandbox","--start-maximized","--disable-cache","--disable-application-cache","--disable-offline-load-stale-cache","--disk-cache-size=0","--v8-cache-options=off","--disable-infobars"]},"linkToAllureReport":"undefined/allure","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.14.2","name":"webdriverio"}}}
[15:47:08]      Failed to take screenshot on reject:     {"type":"NoSessionIdError","message":"A session id is required for this command but wasn't found in the response payload"}
[15:47:08]      Failed to take screenshot on reject:     {"type":"NoSessionIdError","message":"A session id is required for this command but wasn't found in the response payload"}
Error in onReload hook: "Error: Don't call the 'init' command when using the wdio test runner. Your session will get initialised and closed automatically.
    at session("delete") - C:\Users\osmolyar\AppData\Roaming\npm\node_modules\webdriverio\build\lib\commands\end.js:31:17
    at init() - C:\Users\osmolyar\AppData\Roaming\npm\node_modules\webdriverio\build\lib\commands\reload.js:40:23
    at end() - C:\Users\osmolyar\AppData\Roaming\npm\node_modules\webdriverio\build\lib\commands\reload.js:40:17
    at reload() -     at C:\Users\osmolyar\AppData\Roaming\npm\node_modules\wdio-cucumber-framework\node_modules\wdio-sync\build\index.js:316:3"
Setting viewport size
[15:47:08]      Failed to take screenshot on reject:     {"type":"NoSessionIdError","message":"A session id is required for this command but wasn't found in the response payload"}
[15:47:08]      Failed to take screenshot on reject:     {"type":"NoSessionIdError","message":"A session id is required for this command but wasn't found in the response payload"}
Error in onReload hook: "Error: Don't call the 'init' command when using the wdio test runner. Your session will get initialised and closed automatically.
    at windowHandleSize() - C:\Users\osmolyar\AppData\Roaming\npm\node_modules\webdriverio\build\lib\commands\setViewportSize.js:72:17"
Setting viewport size
[15:47:08]      Failed to take screenshot on reject:     {"type":"NoSessionIdError","message":"A session id is required for this command but wasn't found in the response payload"}
F.....In afterScenario

**Comment by osmolyar** [comment]
Got some additional logging from selenium-server.jar with logging set to ALL - I have caught the following log output multiple times concurrent with just when the empty browser/Socket hung up error occurs - it spits out a SessionId with a VERY long 'value'.   Here are two instances of it, attached,
[selenium-standalone error output1.txt](https://github.com/webdriverio/webdriverio/files/2819177/selenium-standalone.error.output1.txt)
[selenium-server error output2.txt](https://github.com/webdriverio/webdriverio/files/2819178/selenium-server.error.output2.txt)

@christian-bromann , is it possible to remove the 'missing info' tags, since code to reproduce and all logs I'm aware of have been provided?

**Comment by osmolyar** [comment]
Additional comment re. 'code to reproduce': with this version, hitting a non-existent url address, the 'very long session id' occurs with each scenario, regardless of whether it's a normal 'selector not found' or an abnormal intermittent 'ECONNECT refused' error that occurs when blank browsers are generated, so maybe that is a downstream occurrence of the actual problem.

**Comment by osmolyar** [comment]
Attaching allure-report.zip where, if you filter out all passing and failed TCs, you can see each feature file with >9 scenarios hits the 'socket hang up' at TC8,9,10,11 or12  

[allure-report.zip](https://github.com/webdriverio/webdriverio/files/2823321/allure-report.zip)

**Comment by osmolyar** [comment]
Error also occurred using Firefox.  Attaching selenium-standalone output and corresponding wdio testrunner spec reporter output showing only the second test case failing with the 'socket hang up' error, the rest passing (despite  a bunch of warnings about unreachable code in the application and channel errors about send/receive for all the test cases)

[firefox selenium standalone output.txt](https://github.com/webdriverio/webdriverio/files/2823361/firefox.selenium.standalone.output.txt)
[spec reporter output.txt](https://github.com/webdriverio/webdriverio/files/2823362/spec.reporter.output.txt)

**Comment by mariocasciaro** [comment]
Having a similar issue here, getting a 'Socket hang up', but for me it's consistently happening when sending a getUrl() command just after a simple navigateTo(). With v4 it's working perfectly.
I'll try to create a reproducible scenario when I have some spare time.

**Comment by osmolyar** [comment]
Resubmitted as https://github.com/webdriverio-boneyard/v4/issues/21 since the original issue pertains to webdriver v4 (and v5 doesn't support wdio-cucumber-framework yet)

**Comment by christian-bromann** [comment]
> and v5 doesn't support wdio-cucumber-framework yet

Please participate in the development of it otherwise it will never be supported and we will stop at some point to maintain v4

**Comment by osmolyar** [comment]
@christian-bromann 
> Please participate in the development of it otherwise it will never be supported and we will stop at some point to maintain v4

I'm game to try but would need guidance

**Comment by osmolyar** [comment]
@christian-bromann , re.
>Please participate in the development of it otherwise it will never be supported and we will stop at some point to maintain v4
 
am a bit stuck in the water with working with the packages at all  because when I install a modified webdriveriov4 package either from GitHub or from the local directory, when wdio is run it can't find '../build/lib/cli.js', since https://github.com/webdriverio-boneyard/v4 (and therefore its fork) doesn't have a /build directory.:

C:\Share\aml_wdio_v4\aml_wdio_v4\demo>npm list -g webdriverio
C:\Users\osmolyar\AppData\Roaming\npm
`-- webdriverio@4.14.2  (git+https://github.com/osmolyar/v4.git#6679e5e52e377e3c56181cea19cc0c0cadb7076b) 

C:\Share\aml_wdio_v4\aml_wdio_v4\demo>wdio config\wdio.conf.js --suite search
module.js:538
    throw err;
    ^

Error: Cannot find module '../build/lib/cli.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\osmolyar\AppData\Roaming\npm\node_modules\webdriverio\bin\wdio:5:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by christian-bromann** [comment]
> doesn't have a /build directory.:

you need to build the project then with `npm run build` .. see scripts in package.json

**Comment by osmolyar** [comment]
@christian-bromann , thanks very much for the tip.

Unfortunately, running with the modified package as in the pull request doesn't fix the issue as the socket hang up still occurs.

With the change, the bolded line in build/lib/RequestHandler is updated with the extra empty object to merge, 
          if ((0, _keys2.default)(data).length > 0) {
                newOptions.json = data;
                newOptions.method = 'POST';
                **newOptions.headers = (0, _deepmerge2.default)({},newOptions.headers, {**
                    'Content-Type': 'application/json; charset=UTF-8',
                    'Content-Length': Buffer.byteLength((0, _stringify2.default)(data), 'UTF-8')
                });
            } else if (requestOptions.method === 'POST') {
                newOptions.json = {};
            }

And when printing out newOptions.headers as follows
if(newOptions){
            console.log("************newOptions.headers is *************"+JSON.stringify(newOptions.headers));
			}
            return newOptions;

When the socket hang up occurs, the following Error on reload is sometimes output (same as before the fix), but there doesn't seem to be any issue with the request headers:

************newOptions.headers is *************{"Connection":"keep-alive","Accept":"application/json","User-Agent":"webdriverio/webdriverio/4.14.2"}
************newOptions.headers is *************{"Connection":"keep-alive","Accept":"application/json","User-Agent":"webdriverio/webdriverio/4.14.2"}
Setting viewport size
************newOptions.headers is *************{"Connection":"keep-alive","Accept":"application/json","User-Agent":"webdriverio/webdriverio/4.14.2"}
F.............In beforeScenario
.............************newOptions.headers is *************{"Connection":"keep-alive","Accept":"application/json","User-Agent":"webdriverio/webdriverio/4.14.2"}
.........************newOptions.headers is *************{"Connection":"keep-alive","Accept":"application/json","User-Agent":"webdriverio/webdriverio/4.14.2"}
**Error in onReload hook: "Error: Don't call the 'init' command when using the wdio test runner. Your session will get initialised and closed automatically.
    at execute(<Function>) - C:\Users\osmolyar\AppData\Roaming\npm\node_modules\webdriverio\build\lib\commands\setViewportSize.js:87:12"**
F........In beforeScenario
...............************newOptions.headers is *************{"Connection":"keep-alive","Accept":"application/json","User-Agent":"webdriverio/webdriverio/4.14.2"}

Here is the zip file that reproduces the issue against the Google search page,,
[google_search_reproduce_socket_hangup_with_isc_folders.zip](https://github.com/webdriverio/webdriverio/files/2937391/google_search_reproduce_socket_hangup_with_isc_folders.zip)

running 'wdio config\wdio.conf.js --suite search' (error occurs usually during 1st test case, sometimes 2nd or 3rd).

(For contrast, here is a zip file where running the exact same command with the exact same feature file, config file  and underlying code does *not* reproduce the error- which I am currently mystified by. )
[google_search__no_reproduce_socket_hang_up.zip](https://github.com/webdriverio/webdriverio/files/2937407/google_search__no_reproduce_socket_hang_up.zip)

**Comment by osmolyar** [comment]
@christian-bromann , finally got the issue; it was the mere presence of a step definition file that contained this line

var req = http.request(testConfig.config.httpOptions, callback);

at the beginning of the file (rather than within a step definition) that was causing the issue, even if no steps defined in the file were being run.
(Closed the issue in v4 repo. )  Thank you for the help.
