### ISSUE TITLE
Commands attempting to run again

### ISSUE THREAD

**Issue by hborawski** [webdriverio/webdriverio#3462]
**Describe your question with as much detail as possible**
I'm running into an issue where some commands are attempted to be rerun after the last command has been sent and completed. This results in a test failure as it can't click the element since the page has long since transitioned. The click is preceded by waiting for visibility, but that command doesn't seem to be rerun.

When this issue occurs, the command that is being rerun takes an abnormal amount of time to fail:
Successful test run: ~277 seconds
Failure test run: ~520 Seconds
This is with my mocha timeout set to 300 seconds ( `300000`ms in `mochaOpts` in `wdio.conf.js`)

This is an intermittent issue, but generally happens one out of every 3-4 runs. It seems to only happen when run from Jenkins in our AWS environment (RHEL7, and Amazon Linux), as I have not been able to reproduce locally against `@wdio/selenium-standalone-service`, or against the `selenium/standalone-chrome` container.

Also tried driving the tests from a container to the chrome container, but I was still able to reproduce even in the AWS environment(s). 

Mostly posting this to see if anyone else has run into this situation. It only seems to happen with chrome, but I'm not sure how to go about finding what part of the stack is causing the issue (webdriverio, chromedriver, selenium, chrome, client application).

Also, peculiarly, running the same test against the `selenium/standalone-firefox` container ran almost 5x faster and I have been unable to trigger this scenario against firefox.

**If it's about a specific piece of code, try and include some of it to support your question.**
N/A

**Environment (please complete the following information):**
 - **WebdriverIO version:** `4.14.1+`, `5.0+`
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** `8.15`, `10.15`, `11.8`
 - **NPM version:** `5.6`, `6.4`
 - **Browser name and version:** Chrome 70/Chrome 71
 - **Platform name and version:** Linux Container (https://github.com/SeleniumHQ/docker-selenium)
 - **Additional wdio packages used (if applicable):** `@wdio/spec-reporter` `@wdio/junit-reporter` `@wdio/mocha-framework` `@wdio/local-runner` `@wdio/cli` (and webdriverio 4.X equivalents)

**Comment by abjerstedt** [comment]
@hborawski based on the information you provided, you are encountered an asynch race condition, which has nothing to do with webdriverio itself, but instead with your tests. I'm going to go ahead and close this issue.

Feel free to reach out for further assistance in our gitter channel for further help:
https://gitter.im/webdriverio/webdriverio

**Comment by hborawski** [comment]
@abjerstedt Thanks for taking a look. I do have some outstanding questions, but I'd like to discuss them here, so all the info is in one place, should someone else run into a similar issue and find this thread.

1. How does a race condition occur when the test consists of a single promise chain?
  a. And if the promise chain consists of only webdriverio commands, what makes it not an issue with webdriverio?
2. If it is indeed a race condition, how is it that the command is run twice, and not just out of order? 
3. If my test is the problem, why does this never happen in Firefox?

Thanks in advance for the insight!

**Comment by christian-bromann** [comment]
@hborawski can you provide logs or a minimal reproducible example for us to reproduce?
