### ISSUE TITLE
Lost logging data when printing to much at once

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#3466]
When the interface prints all the logs at the end of the test in can happen (e.g. in Jenkins) that the node process ends before everything was printed resulting in missing some logs like stdout or worker errors.

**Comment by mgrybyk** [comment]
Can you provide an example of truncated log, which logger(s) are truncated

**Comment by christian-bromann** [comment]
@mgrybyk I can't. Think about it as a normal outout that at some point continues with the NPM error log. You can reproduce it by yourself when running more than 15 tests in parallel or so. I was able to hot patch it by doing:

```js
launcher.run().then(
  code => setTimeout(() => process.exit(code), 100),
  e => process.nextTick(() => {
    throw e;
  })
);
```
in `wdio-cli/src/run.js` but I am not sure if this is the ultimate fix. Normally console.logs are synchronous and I don't understand why these aren't. For CI I was thinking to log the reporter messages when they come in anyway since we can't show anything interactive as in the dev console.

**Comment by mgrybyk** [comment]
@christian-bromann I was able to reproduce it with

```

const bigStr = "_!__$%01234567890^&__!_".repeat(5000) + "WWW\n\n\n"

describe("m", () => {
  it("t", () => {
    browser.url("http://adam.goucher.ca/parkcalc/")
    browser.execute((str) => {
      this.document.querySelector('body').appendChild(this.document.createElement('textarea'))
      this.document.querySelector('textarea').value = str
    }, bigStr)
    $("textarea").getValue()
  })
})
```

I'm not getting full value of $("textarea").getValue() in log.

In case I add `outputDir: __dirname,` to wdio conf value appears in `wdio-0-0.log` as expected.

Are you working right now on this issue or logger improvements / refactoring? Does it make sense to dive deeper at the moment?

**Comment by christian-bromann** [comment]
This should be fixed now with the rewritten interface.
