### ISSUE TITLE
browser.close() instead browser.closeWindow()

### ISSUE THREAD

**Issue by balukov** [webdriverio/webdriverio#3472]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [x] A typo
- [ ] Missing documentation
- [ ] Other

**Description of the improvement / report**

1. https://webdriver.io/docs/api/browser/newWindow.html
2. `browser.close()` in Example

expected:
`browser.closeWindow()`

**Comment by abjerstedt** [comment]
Feel free to submit a PR!

**Comment by balukov** [comment]
https://github.com/webdriverio/webdriverio/pull/3478
