### ISSUE TITLE
Wrong CSSProperty Type in Webdriverio.d.ts

### ISSUE THREAD

**Issue by dalenguyen** [webdriverio/webdriverio#3473]
There is a typo that I found in webdriverio.d.ts. 

The current version is: 

```
interface CSSProperty {
        property: string,
        value: any,
        parse: {
            type: string,
            string: string,
            unit: string,
            value: any
        }
    }
```

I should be:

```
interface CSSProperty {
        property: string,
        value: any,
        **parsed**: {
            hex: string,
            alpha: number,
            type: string,
            rgba: string
        }
    }
```

Please help to check. Thanks,

Webdriverio: ^5.4.9

**Comment by christian-bromann** [comment]
@dalenguyen please make a PR with a change here: https://github.com/webdriverio/webdriverio/blob/master/scripts/templates/webdriverio.tpl.d.ts#L48

**Comment by dalenguyen** [comment]
Thanks @christian-bromann. I made a PR here: https://github.com/webdriverio/webdriverio/pull/3474

**Comment by christian-bromann** [comment]
Let's continue convo in #3474
