### ISSUE TITLE
getText of browser is throwing { state: 'pending' } error while using it inside a promise

### ISSUE THREAD

**Issue by cvchalla** [webdriverio/webdriverio#3475]
Hello - I am new to wdio.

I am trying to automate a scenario - where I connect to a rest API - which is a promise

1) call the function - which returns a promise that contains the service response.
2) While I loop through the service I retrieve certain values from the service, and trying to compare the corresponding browser text.

Now the problem is - I am getting the right service details - and while trying to get the browser.getText(some locator) - and trying to compare with the service data - I am always getting { state: 'pending' } for browser.getText.

Please help me to resolve this.

Thank you for the help.
Chandra.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [4.13.2]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [8.11.3]
 - **NPM version:** [5.6.0]
 - **Browser name and version:** [Chrome 71.0.3578.98]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [@wdio-mochawesome-reporter, @wdio/selenium-standalone service]

**Additional context**

**Comment by christian-bromann** [comment]
Please use the [`call`](https://webdriver.io/docs/api/browser/call.html) command to make async calls synchronous.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
