### ISSUE TITLE
iOS XCUITest predicate string and class chain selectors are treated like UIAutomation

### ISSUE THREAD

**Issue by ptthuong** [webdriverio/webdriverio#3476]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [5.4.9]
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync:** sync
 - **Node.js version:** 10.14.1
 - **NPM version:** 6.4.1
 - **Platform name and version:** iOS

**Config of WebdriverIO**
capabilities: [
      {
        platformName: 'iOS',
        bundleId: 'com.xxx.xxxx',
        automationName: 'XCUITest',
        wdaLocalPort: 8101,
        deviceName: 'xxxx,
        udid: process.env.UDID,
        maxInstances: 1
      }
    ]

**Describe the bug**
iOS XCUITest predicate string and class chain selectors are treated like UIAutomation. This error occurred when using class chain selector:
```
2019-02-01T06:28:34.004Z INFO webdriver: DATA { using: '-ios uiautomation',
  value: 'chain=**/XCUIElementTypeToolbar/**/XCUIElementTypeButton[5]' }
2019-02-01T06:28:34.015Z ERROR webdriver: Request failed due to Error: Locator Strategy '-ios uiautomation' is not supported for this session
```

**To Reproduce**
- Finding an XCUIElementType element by predicate string or class chain selector (follow [document here](https://webdriver.io/docs/selectors.html#ios-xcuitest-predicate-strings-and-class-chains)
Example: `selector = 'ios=chain=**/XCUIElementTypeToolbar/**/XCUIElementTypeButton[5]'`
- Error occurred with message "Error: Locator Strategy '-ios uiautomation' is not supported for this session"

**Expected behavior**
Predicate string and class chain selectors are treated like they should be.

**Additional comment**
Not sure if I got the code right, but it seems to not support XCUITest class chain & predicate string selectors now.
https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/utils.js#L10
https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/utils.js#L59

**Comment by christian-bromann** [comment]
> * Error: Locator Strategy '-ios uiautomation' is not supported for this session

It seems that this error comes from Appium and shows that class chain selectors are not supported for the environment you run your tests in.

**Comment by ptthuong** [comment]
@christian-bromann 
In wdio v4, the POST command for XCUITest class chain selectors looks like:
```
[1;30m[17:25:56] [0m [0;35mCOMMAND	[0mPOST 	 "/wd/hub/session/a716abc8-e7e7-4635-a83a-4e477f4af3d3/element"
[1;30m[17:25:56] [0m [0;33mDATA		[0m{"using":"-ios class chain","value":"**/XCUIElementTypeToolbar/**/XCUIElementTypeButton[5]"}
[1;30m[17:25:56] [0m [0;36mRESULT		[0m{"element-6066-11e4-a52e-4f735466cecf":"23000000-0000-0000-6D01-000000000000","ELEMENT":"23000000-0000-0000-6D01-000000000000"}
[1;30m[17:25:56] [0m [0;35mCOMMAND	[0mGET 	 "/wd/hub/session/a716abc8-e7e7-4635-a83a-4e477f4af3d3/element/23000000-0000-0000-6D01-000000000000/displayed"
[1;30m[17:25:56] [0m [0;33mDATA		[0m{}
[1;30m[17:25:56] [0m [0;36mRESULT		[0mtrue
```
In v4:
{ 
 "using":"-ios class chain",
 "value":"**/XCUIElementTypeToolbar/**/XCUIElementTypeButton[5]"
}
In v5:
{ 
 "using": "-ios uiautomation",
  "value": "chain=**/XCUIElementTypeToolbar/**/XCUIElementTypeButton[5]"
}
This command is sent from wdio, right?

**Comment by janvennemann** [comment]
I'm having similar issues. Trying to run the following selector `ios=predicate=type == 'XCUIElementTypeTextField'` will result in `invalid selector: Locator Strategy '-ios uiautomation' is not supported for this session`,

I guess this is because every selector starting with `ios=` get rewritten to `-ios uiautomation` here:
https://github.com/webdriverio/webdriverio/blob/6a6e5ba36d849fe279451d5217f6e74e1862967b/packages/webdriverio/src/utils.js#L60

How do i use predicate selectors in iOS 10+ where the format should be `-ios predicate string` instead of `-ios uiautomation`. I couldn't find anything in the docs.

**Comment by ptthuong** [comment]
https://github.com/webdriverio/webdriverio/pull/3558
