### ISSUE TITLE
Errors thrown from custom command after using a webdriverio command are not caught

### ISSUE THREAD

**Issue by GHanehoj** [webdriverio/webdriverio#3479]
**Environment:**
 - **WebdriverIO version:** 5.4.9
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.15.1
 - **NPM version:** 6.7.0
 - **Browser name and version:** Chrome 72
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used:** 
@wdio/cli: 5.4.9
@wdio/local-runner: 5.4.9
@wdio/mocha-framework: 5.4.8
@wdio/selenium-standalone-service: 5.2.2
@wdio/spec-reporter: 5.4.3
@wdio/sync: 5.4.6

**Describe the bug**
Throwing an error in a custom command (made with browser.AddCommand()) after using the $$ method, results in the error not being caught when the custom command is called from a try-catch statement.

**To Reproduce**
In config file, define these function:
```
before: function (capabilities, specs) {
        browser.addCommand("testFunction1", function () {
            throw new Error("Something went wrong");
        }

        browser.addCommand("testFunction2", function () {
            var a = $$('div');
            throw new Error("Something went wrong");
        }
}
```
Then in some test, call the functions through try-catch statements;
```
...
try {
    browser.testFunction1();
}
catch {
    console.log("Error1 caught");
}

try {
    browser.testFunction2();
}
catch {
    console.log("Error2 caught");
}
...
```
**Expected behavior**
As both functions throws an error which is returned to the try-catch statement, the errors should be caught and the console log statements should be called and test execution continues. The first function's error is caught as expected, _however_, the second function's error is thrown fully and the test stops.

**Additional context**
It should be noted that this only happens in functions defined using addCommand(). Defining a function inside the script with the same logic works as expected.

**Comment by abjerstedt** [comment]
```
        test('should properly throw exceptions on the browser scope', async () => {
            const browser = await remote(remoteConfig)
            browser.addCommand('function1', function () {
                throw error1
            })

            browser.addCommand('function2', function () {
                browser.$('#foo')
                throw error2
            })

            await expect(() => browser.function1()).toThrow(error1)
            await expect(() => browser.function2()).toThrow(error2)

            try {
                await browser.function1()
            } catch (error) {
                expect(error).toBe(error1)
            }

            try {
                await browser.function2()
            } catch (error) {
                expect(error).toBe(error2)
            }
        })

        test('should properly throw exceptions on the element scope', async () => {
            const browser = await remote(remoteConfig)
            browser.addCommand('function1', function () {
                throw error1
            }, true)
            browser.addCommand('function2', function () {
                browser.$('#foo')
                throw error2
            }, true)
            const elem = await browser.$('#foo')

            await expect(() => elem.function1()).toThrow(error1)
            await expect(() => elem.function2()).toThrow(error2)

            try {
                await elem.function1()
            } catch (error) {
                expect(error).toBe(error1)
            }

            try {
                await elem.function2()
            } catch (error) {
                expect(error).toBe(error2)
            }

        })
```

I created the above unit tests and cannot reproduce the issue above.

**Comment by abjerstedt** [comment]
Erwin investigated, and it looks like it has something to do with the before() hook being the area where addCommand is invoked.

**Comment by christian-bromann** [comment]
You are missing a `)` in your before hook in both addCommand function calls, so instead of 
```js
        browser.addCommand("testFunction1", function () {
            throw new Error("Something went wrong");
        }
```
do
```js
        browser.addCommand("testFunction1", function () {
            throw new Error("Something went wrong");
        })
```

**Comment by GHanehoj** [comment]
@christian-bromann you're right, however that is just a typo in my bug report (the issue is there even if that is fixed).

**Comment by GHanehoj** [comment]
@abjerstedt I am also able to reproduce this when adding the command from some other environment than the before() hook (eg. the constructor of my main page object). So i think its unrelated to the hooks

**Comment by GHanehoj** [comment]
Hm, that said i have tried to reproduce in one of the boilerplate projects, and its not there, so you're probably right in that its on my end.

**Comment by diachedelic** [comment]
I am also seeing this issue, my workaround is to duplicate code everywhere instead of using custom commands :(

**Comment by diachedelic** [comment]
I tried to follow @GHanehoj 's instructions to reproduce, but cannot.  It now seems to be errors thrown from within `waitUntil` that are escaping `try...catch` blocks, I will create a new issue if I can reproduce.
