### ISSUE TITLE
failed to save screenshot in windows

### ISSUE THREAD

**Issue by needforspeed** [webdriverio/webdriverio#3480]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [5.4.9]
 - **Mode:** [Standalone mode]
 - **Node.js version:** [8.11.2]
 - **NPM version:** [5.6.0]
 - **Browser name and version:** [Chrome 71]
 - **Platform name and version:** [Windows server 2008 R2]
 - **Additional wdio packages used (if applicable):** []

**Config of WebdriverIO**
An example of how you configured WebdriverIO config
```
{
  url: 'http://localhost',
  browser: 'chrome',
  timeouts: {
    scripts: 60000,
    "page load": 60000
  }
}
```
**Describe the bug**
CodeceptJS tries to save the screenshot to following location:

```
E:\app\eclipse\dev\codecept\output\test_welco_fed579d2-d41a-473b-b927-48d64839389c.failed.png, size: 921x570

failed to save screenshot: Error: directory (E:\app\eclipse\dev\codeceptE:\app\eclipse\dev\codecept\output\) doesn't exists
at Browser.saveScreenshot (E:\app\eclipse\dev\codecept\node_modules\webdriverio\build\commands\browser\saveScreenshot.js:51:11)
...
...
```

**To Reproduce**
Run something wrong into CodeceptJS 2.0.4 and it capture the screenshot by default

**Expected behavior**
save screenshot to `E:\app\eclipse\dev\codecept\output\test_welco_fed579d2-d41a-473b-b927-48d64839389c.failed.png`

**Log**

```
E:\app\eclipse\dev\codecept\output\test_welco_fed579d2-d41a-473b-b927-48d64839389c.failed.png, size: 921x570

failed to save screenshot: Error: directory (E:\app\eclipse\dev\codeceptE:\app\eclipse\dev\codecept\output\) doesn't exists
at Browser.saveScreenshot (E:\app\eclipse\dev\codecept\node_modules\webdriverio\build\commands\browser\saveScreenshot.js:51:11)
...
...
```

**Additional context**

It appears that absoluteFilepath didn't exclude windows file path that starts with something like "E:\" as absolute path.

**Comment by christian-bromann** [comment]
> (E:\app\eclipse\dev\codeceptE:\app\eclipse\dev\codecept\output\) doesn't exists

It seems that the directory you provided doesn't exist. Can you verify that this directory is set before you want to save a screenshot?

**Comment by needforspeed** [comment]
It was due to windows absolute path not recognized, as you can see the relative path `E:\app\eclipse\dev\codecept` was prepend to the output dir
