### ISSUE TITLE
addCommand does not allow override of existing commands

### ISSUE THREAD

**Issue by sgreener** [webdriverio/webdriverio#3483]
**Environment (please complete the following information):**
 - **WebdriverIO version:**  5.4.7
 - **Mode:** Standalone
 - **If WDIO Testrunner, running sync/async:** Sync
 - **Node.js version:** 8.11.2
 - **NPM version:** 5.6.0
 - **Browser name and version:** chrome/firefox
 - **Platform name and version:** windows 10
 - **Additional wdio packages used (if applicable):** n/a

**Describe the bug**
Using the browser.addCommand() function to override existing v5 commands does not work. This used to work in v4.

**To Reproduce**
```
browser.addCommand('scrollIntoView', function() {
    console.log('custom scrollIntoView() called');
    return browser.execute("arguments[0].scrollIntoView();", this);
}, true);

$(someSelector).scrollIntoView();
```

**Expected behaviour**
When .scrollIntoView(); is called you should see the console log string saved out because it's executing our overridden command. However its still calling the official .scrollIntoView() command.

**Additional context**
I am trying to use this to fix an issue with the firefox webdriver to do with scrolling! (a known webdriver bug).

If you rename the addCommand to 'scrollIntoView2' and then call that, this snippet works as expected.

**Comment by christian-bromann** [comment]
I honestly don't see much value in allowing to overwrite core commands in WebdriverIO. For someone who doesn't know that a command is overwritten it is nearly impossible to find out why a certain command is behaving differently as described in the official docs.

**Comment by sgreener** [comment]
One such reason for being able to do this is fix browser bugs that effect only one vendor. 

In the current case of scrollIntoView(), it does not work on firefox but does in chrome. A bug has been logged for it on geckodriver bug log. Now if we could override the command, then we could do a browser.execute to mimic the same behaviour when in firefox and use the intended command when in all other browsers. If this is applied in the conf, we do not need to change any tests to fix them all.

**Comment by christian-bromann** [comment]
> A bug has been logged for it on geckodriver bug log

I am not sure how this is connected to Geckodriver. The WebdriverIO `scrollIntoView` commands calls `scrollIntoView` on the element in the browser.

**Comment by christian-bromann** [comment]
Also I don't see a reason why this can't be part of WebdriverIO if it is helpful for others too.

**Comment by sgreener** [comment]
Well [this](https://github.com/mozilla/geckodriver/issues/776) is the gecko driver bug I refer too, was just trying to implement a solution for it that had the least impact on all my tests.
