### ISSUE TITLE
missing import of 'Test' and "Suite" in webdriverio.d.ts

### ISSUE THREAD

**Issue by FelixZilber** [webdriverio/webdriverio#3489]
Getting:
node_modules/webdriverio/webdriverio.d.ts:113:27 - error TS2304: Cannot find name 'Test'.
beforeTest?(test: Test): void;
node_modules/webdriverio/webdriverio.d.ts:135:28 - error TS2304: Cannot find name 'Suite'.
 afterSuite?(suite: Suite): void;
Using: 
"webdriverio": "^5.4.13",

**Comment by christian-bromann** [comment]
Please see https://webdriver.io/docs/typescript.html

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
