### ISSUE TITLE
sessionId is not updated after creating new session

### ISSUE THREAD

**Issue by xlenz** [webdriverio/webdriverio#3491]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.4.13
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10
 - **Browser name and version:** any browser or appium

**Config of WebdriverIO**
`{ capabilities: { browserName: "chrome" } }`

**Describe the bug**
sessionId is not updated after creating new one

**To Reproduce**
```
browser.deleteSession()
browser.newSession({ browserName: "chrome" })
$("body").isExisting()
```

**Expected behavior**
should be possible to delete / create sessions and proceed using newly created session

**Log**
```
// delete session
INFO webdriver: COMMAND deleteSession()
INFO webdriver: [DELETE] http://127.0.0.1:4441/wd/hub/session/85072702ecf93c6d5011ff1956438ec5

// create session (nonW3C as far as chrome is not W3C)
INFO webdriver: DATA { desiredCapabilities: { browserName: 'chrome' } }
[0-0] 2019-02-04T13:26:42.242Z INFO webdriver: RESULT {
  ... 
  'webdriver.remote.sessionid': '03b4027552ceb006553eaa95df23b375'
}

// find element, notice that session id was not updated
INFO webdriver: [POST] http://127.0.0.1:4441/wd/hub/session/85072702ecf93c6d5011ff1956438ec5/element

ERROR webdriver: Request failed due to unknown error: Session [85072702ecf93c6d5011ff1956438ec5] was terminated due to CLIENT_STOPPED_SESSION
```

**Additional context**

for W3C clients, like Appium, newSession result is
```
{
  capabilities: { ... },
  sessionId: 'f2298a78-adb7-4afe-9c9f-5fd296d594e7'
}
```

**Comment by xlenz** [comment]
**Why is it useful?**

Have to restart app in almost same state but with some differences in capabilities.

**Suggested fixes**

- add ability to pass capabilities parameters to reloadSession
- add new command newSession and update sessionId 

or even do both

**Comment by christian-bromann** [comment]
Please use [reloadSession](https://webdriver.io/docs/api/browser/reloadSession.html)

**Comment by mgrybyk** [comment]
Reload session doesn't support parameters @https://research.hackerrank.com/developer-skills/2019

**Comment by christian-bromann** [comment]
What parameters do you think should it take?

**Comment by mgrybyk** [comment]
Capabilities

**Comment by mgrybyk** [comment]
It should be optional param so we don't break anything. It was super useful to restart appium session with slightly different capabilities in v4

**Comment by mgrybyk** [comment]
Sorry to say multiremote won't help with single real iOS device
