### ISSUE TITLE
Wrong webdriverio.d.ts content

### ISSUE THREAD

**Issue by gitowiec** [webdriverio/webdriverio#3493]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [5.4.9]
 - **Mode:** [local]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [8.15]
 - **Browser name and version:** [Chromium 71.0.3578.98]
 - **Platform name and version:** [Ubuntu 18.04]
 - **Additional wdio packages used (if applicable):** [
    "@wdio/cli": "5.4.9",
    "@wdio/local-runner": "5.4.9",
    "@wdio/mocha-framework": "5.4.8",
    "@wdio/selenium-standalone-service": "5.2.2",
    "@wdio/spec-reporter": "5.4.3",
    "@wdio/sync": "5.4.6",
]

**Describe the bug**
Can't use `switchToFrame` method without casting browser to any
```
    (browser as any).switchToFrame(this.iframeElement);
```
**Expected behavior**
TypeScript files are well formed and up to date.

**Comment by xlenz** [comment]
@gitowiec I don't have such problem.
Maybe you have some problems with your tsconfig?
`browser.switchToFrame("foo")` - works fine
