### ISSUE TITLE
Browser/Device capability management within webdriverio

### ISSUE THREAD

**Issue by PippoRaimondi** [webdriverio/webdriverio#3498]
I've been setting up test suites for a while and I find myself using third party services like saucelabs and browserstack... which means I need to create a good way to manage the capabilities and write code each time to invoke these capabilities dynamically via some CI pipeline...

I am thinking of having a command line argument that reads from some json file within root of the test suite and overrides the capabilities from wdio.config to deal with this without having to write custom code each time...

An alternative is have a standalone @wdio package that you can import and use if you wished... something similar to this: https://www.npmjs.com/package/@uktrade/client-matrix-js

I was hoping to get some feedback whether you find it ok for me to go ahead and implement this feature... @christian-bromann

**Comment by christian-bromann** [comment]
> I am thinking of having a command line argument that reads from some json file within root of the test suite and overrides the capabilities from wdio.config to deal with this without having to write custom code each time...

Can you please explain in further detail?

**Comment by PippoRaimondi** [comment]
When doing compatibility testing, it's very common that a subset of tests are run in multiple browsers and devices... without any thought to it, you can simply hardcode the capabilities within your `wdio.conf.js` that will roughly look like this:

```
export.config = {
// ...
  capabilities: [
    firefox_latest: {
      browserName: 'Firefox',
      os: 'Windows',
      os_version: '7',
    },
    chrome_latest: {
      browserName: 'Chrome',
      os: 'Windows',
      os_version: '10',
    },
    ...
  ],
// ...
}
```

The problem is that the list of capabilities is very large, think about multiple chrome, firefox, ie, safari versions then think about different breakpoints (desktop, tablet, mobile) and devices...

Having the ability to dynamically invoke the test run (hence insert the capabilities dynamically) you want to run against rather than trigger your test suite against 30+ browsers/devices is a must... 

that allows you to run a subset of the suite against a combination of devices, another subset of the suite against a combination of browsers and so on... also, best practice is to have the capabilities you'd like to run as a configurable so you can change as pleased without having to push code every time...

and in order to do that you need to write custom code to deal with it... which is not a huge amount of work, but just repetitive and annoying (you can get the sense of how much code is needed by looking at the package)... so similar to having the ability to run your tests against a local driver i.e `wdio --browser=chrome` it would be nice to have the ability to do something like `wdio --remoteBrowser=chrome_latest --remoteBrowser=firefox_latest`...

Let me know if it's still unclear!

**Comment by Oshalom-OP** [comment]
@PippoRaimondi  I was looking into this too. I noticed that it can be run 
programmatically like so: http://v4.webdriver.io/guide/testrunner/gettingstarted.html

When doing so, you can override some parameters but it doesn't look like capabilities is one of them

**Comment by PippoRaimondi** [comment]
right, it is not one of them and if agreed by christian I will work in adding it!

**Comment by PippoRaimondi** [comment]
I will go ahead and create a small PR for this as I don't imagine it will be too much work... then we can use that as a discussion point... keep you posted!

**Comment by christian-bromann** [comment]
@PippoRaimondi I don't think that adding more parameter to the wdio command is a good solution to this, you can already do this by calling the wdio command as

```
REMOTE_BROWSER="chrome_latest,firefox_latest" wdio
```

and build you capabilities based on this using `process.env.REMOTE_BROWSER`

**Comment by PippoRaimondi** [comment]
I will stick with using the `uktrade@client-matrix` to "build" the capabilities based on an environment variable... which seemed like a neat thing to have within wdio cli but I guess if we can work around it, then you are right, we don't need to add more code/options...

**Comment by christian-bromann** [comment]
Sounds good!
