### ISSUE TITLE
Add support for json report in v5

### ISSUE THREAD

**Issue by AnandGanesh-Reflektion** [webdriverio/webdriverio#3499]
**Is your feature request related to a problem? Please describe.**
Migrated to v5 but json report is not available. Need support for the same as we need it for internal dashboard.

**Describe alternatives you've considered**
I used to have mocha-multi-reporters in cypress.

**Comment by christian-bromann** [comment]
see https://github.com/fijijavis/wdio-json-reporter/issues/22
