### ISSUE TITLE
missing allure-reporter typings

### ISSUE THREAD

**Issue by xlenz** [webdriverio/webdriverio#3504]
**Environment (please complete the following information):**
 - **@wdio/allure-reporter version:** 5.4.9

**Describe the bug**
allure-reporter.d.ts is missing

**To Reproduce**
install @wdio/allure-reporter from npm

**Expected behavior**
package should be shipped with allure-reporter.d.ts 

**Additional context**

we have a proper a way to generate valid allure-reporter.d.ts however it is not shipped along with package.

should we release new version of this package? Can somebody please help?

**Comment by christian-bromann** [comment]
Is this done by #3495 ?

**Comment by xlenz** [comment]
@christian-bromann issue has been fixed by https://github.com/webdriverio/webdriverio/pull/3510

looks like typings were generated automatically with new release of allure plugin (5.4.15), which is cool.
