### ISSUE TITLE
Ability to set capabilities for next session to be created

### ISSUE THREAD

**Issue by xlenz** [webdriverio/webdriverio#3505]
**Is your feature request related to a problem? Please describe.**
ability to set capabilities programmatically for next session to be created

**Describe the solution you'd like**
```
const originalCapabilities = { app: 'com.my.app' }
it('test', () => {
  $('~NATIVE_SELECTOR')
  browser.setNextSessionCapabilities({ browserName: 'safari' })
  browser.reloadSession()
  browser.url('https://my.app.com')
})
after(() => {
  browser.setNextSessionCapabilities(originalCapabilities)
})
```
**Describe alternatives you've considered**
any possible solution to change capabilities within same test

**Additional context**

**Comment by christian-bromann** [comment]
Let's continue convo in #3507
