### ISSUE TITLE
Bad response code: Expected (200), Received (404)

### ISSUE THREAD

**Issue by theMaxiiim** [webdriverio/webdriverio#3512]
**Describe your question with as much detail as possible**
When wdio config is run, it properly sends the request to Browserstack, and Browserstack marks it as complete. But, a message printed by the Browserstack module reads "Bad response code: Expected (200), Received 404!" I believe that this might be caused by an erroneous API endpoint.

**ERROR LOG**
Stderr:
[0-0] 2019-02-06T05:09:14.997Z ERROR wdio-sync: Error: Bad response code: Expected (200), Received (404)!
    at Request._request.default.get [as _callback] (/Users/themaxiiim/Desktop/utencilio/node_modules/@wdio/browserstack-service/build/service.js:109:23)
    at Request.self.callback (/Users/themaxiiim/Desktop/utencilio/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/Users/themaxiiim/Desktop/utencilio/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/Users/themaxiiim/Desktop/utencilio/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2]
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 11.0.0
 - **NPM version:** [e.g. 5.8.0] 6.4.1
 - **Browser name and version:** [e.g. Chrome 68] - Samsung Galaxy S7
 - **Platform name and version:** [e.g. Windows 10]- Android Live Device Browserstack
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Comment by abjerstedt** [comment]
@theMaxiiim we need more info, including a reproducible result - or I cannot do anything.

**Comment by goatsy** [comment]
I would suggest you try to run your tests with the latest appium version and try again.

https://www.browserstack.com/automate/capabilities

For example:

var capabilities = {
'os_version' : '6.0',
'device' : 'Samsung Galaxy S7',
'real_mobile' : 'true',
'browserstack.local' : 'false',
'browserstack.appium_version' : '1.9.1'
}

Browserstack has a pretty old default appium version.

**Comment by theMaxiiim** [comment]
Hi goatsy,

Thank you for the suggestion. The error no longer appears. Now I am onto the next step, which is to create the test file. I've created the test file, and tested around with it but it is not able to locate elements, and most commands do not work. Commands such as driver.getDeviceTime(), or driver.isLocked() work perfectly. When the latter commands are used, the tests are displayed as successful. When I try to use driver.element("~SomeAccessibilityId") or driver.timeoutsImplicitWait(5000), the test appear as failed and when I check the Browserstack video screen capture the device does not do the expected actions. 

Please specify if you need any more information.

Thank you very much :)

**Comment by christian-bromann** [comment]
> I've created the test file, and tested around with it but it is not able to locate elements, and most commands do not work.

Make sure you use the right context. There is "web" and "native" contexts in Appium and you need to use specific selectors in either of them. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
