### ISSUE TITLE
TypeError while trying to save element screenshot

### ISSUE THREAD

**Issue by kirkopov** [webdriverio/webdriverio#3513]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.4.14
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.15.0
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome 71
 - **Platform name and version:** MacOs 10.14.2

**Describe the bug**
Getting exception while calling element.saveScreenshot(path), browser.saveScreenshot(path) works fine.

**To Reproduce**
call saveScreenshot method of element
 $(selectorString).saveScreenshot(filePath)

ex:
it('foo',()=>{
        $('.bar').saveScreenshot('./shot.png')
    })

**Expected behavior**
screenshot of element saved to filesystem as described [here](https://webdriver.io/docs/api/element/saveScreenshot.html)

**Log**
[chrome #0-0] TypeError: this.takeElementScreenshot is not a function
[chrome #0-0]     at Element.saveScreenshot (/Users/Kopov/repos/wdio/node_modules/webdriverio/build/commands/element/saveScreenshot.js:51:35)
[chrome #0-0]     at Element.runCommand (/Users/Kopov/repos/wdio/node_modules/@wdio/sync/build/wrapCommand.js:32:32)
[chrome #0-0]     at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by abjerstedt** [comment]
Already fixed and will be in the next release.
