### ISSUE TITLE
Missing readme on aws-lambda runner

### ISSUE THREAD

**Issue by shridharkalagi** [webdriverio/webdriverio#3514]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

I'd like to report the the aws-lambd running is missing the readme file. Can you please help me trigger tests on lambda? I can contribute on improving this doc once I get to know. Thanks
- [ ] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Comment by christian-bromann** [comment]
@shridharkalagi this runner is still work in progress and not ready to be used yet
