### ISSUE TITLE
beforeAll and afterAll (mocha + chai) failures are not captured in report

### ISSUE THREAD

**Issue by AnandGanesh-Reflektion** [webdriverio/webdriverio#3517]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2]
    "@wdio/cli": "^5.4.3",
    "@wdio/dot-reporter": "^5.4.3",
    "@wdio/junit-reporter": "^5.4.3",
    "@wdio/local-runner": "^5.4.3",
    "@wdio/mocha-framework": "^5.4.3",
    "@wdio/selenium-standalone-service": "^5.4.3",
    "@wdio/spec-reporter": "^5.4.3",
    "@wdio/sync": "^5.4.3",
    "webdriverio": "^5.4.3"

 - **Mode:** [Standalone mode or WDIO Testrunner] - WDIO Test Runner
 - **If WDIO Testrunner, running sync/async:** - sync
 - **Node.js version:** - v10.14.2
 - **NPM version:** - 6.4.1
 - **Browser name and version:** - chrome 71
 - **Platform name and version:** - Mac OS Mojave 10.14.1

**Config of WebdriverIO**
```exports.config = {
  runner: 'local',
  specs: ['./test/rfk/**/*.ts'],
  exclude: [
  ],
  maxInstances: 2,
  capabilities: [
    {
      maxInstances: 2,
      browserName: 'chrome',
    },
  ],
  sync: true,
  logLevel: 'error',
  deprecationWarnings: true,
  bail: 0,
  baseUrl: '',
  waitforTimeout: 35000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 1,
  services: ['selenium-standalone'],
  framework: 'mocha',
  mochaOpts: {
    ui: 'bdd',
    timeout: 35000,
    compilers: ['ts-node/register', 'tsconfig-paths/register'],
  },
  reporters: [
    'spec',
    [
      'allure',
      {
        outputDir: './target/allure-results/',
        disableWebdriverStepsReporting: true,
        disableWebdriverScreenshotsReporting: false,
      },
    ],
    [
      'junit',
      {
        outputDir: './target/junit-results/',
        outputFileFormat: function(opts) {
          // optional
          return `results.xml`
        },
      },
    ],
  ],
}
```

**Describe the bug**
When running tests using mocha framework, system fails to capture beforeAll() or afterAll() failures in report. The issue is seen in the console but the same is missing from reports. Also when tests are run in parallel few results are missing from report.

![wdio-error-01](https://user-images.githubusercontent.com/29747350/52403051-d1f9c900-2aeb-11e9-80a4-16fe7de9553b.png)
![wdio-error-02](https://user-images.githubusercontent.com/29747350/52403052-d1f9c900-2aeb-11e9-8979-06018b5b8a7b.png)
![wdio-error-03](https://user-images.githubusercontent.com/29747350/52403053-d1f9c900-2aeb-11e9-888e-6b50de4d5b8d.png)

**Comment by xlenz** [comment]
@AnandGanesh-Reflektion there is no beforeAll() or afterAll() in Mocha.

How are you using hooks?

**Comment by AnandGanesh-Reflektion** [comment]
@xlenz, I meant before() and after() hooks.

**Comment by mgrybyk** [comment]
Just faced another problem that skipped tests are not handled properly, doing pr for that.

I'll check your case as well

**Comment by AnandGanesh-Reflektion** [comment]
Thanks for the update @mgrybyk.

**Comment by mgrybyk** [comment]
@AnandGanesh-Reflektion reporter is designed so that all the hooks are ignored.

**Comment by mgrybyk** [comment]
what will be decision on this?

We can add all the hooks to report, or only add failed hooks

**Comment by AnandGanesh-Reflektion** [comment]
@mgrybyk is it a good idea to ignore hooks for reporter? If that's the case, how can we track errors occurred in before and after hooks. There are some common checks that gets executed in before or after hooks. wdio v4 had the support for before and after hooks.

**Comment by mgrybyk** [comment]
Ok, so before and after should be added as tests, and beforeEach and afterEach as test steps.
Correct?

**Comment by AnandGanesh-Reflektion** [comment]
Yeah right. Any error in beforeEach and afterEach also should be captured in report.

**Comment by mgrybyk** [comment]
@AnandGanesh-Reflektion  upd, I think there is no need to capture passed before(Each)/after(Each) hooks at this point, but it is possible.

If beforeEach or afterEach hook is failed test is marked as failed, which is good.

I've managed to capture before/after hooks failures like this

```
    <test-cases>
        <test-case start='1549582108535' status='broken' stop='1549582108535'>
            <name>"before all" hook</name>
            <title>"before all" hook</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>before failure message!!</message>
                <stack-trace>Error: before failure message!!
                    at Context.before (debug/debug.spec.ts:7:11)
                    at new Promise (&lt;anonymous>)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
```

I still have to do some testing around, will do PR in next days.
@christian-bromann do you think it is find to have this? It would be really really helpful!

**Comment by AnandGanesh-Reflektion** [comment]
@mgrybyk I verified the issue with latest releases 5.4.17 and 5.4.14. Issue is not resolved yet. Is the fix available in latest release?

**Comment by mgrybyk** [comment]
@AnandGanesh-Reflektion not yet, waiting for a PR to be merged.

https://github.com/webdriverio/webdriverio/pull/3536
It is open, but have to be merged. Once it is merged it will be available in next wdio version.

Btw, if you are facing issues others than missing hooks in report, please submit as different issue.

**Comment by christian-bromann** [comment]
PR is merged and will be released any second. Thanks @mgrybyk for looking into this.

**Comment by AnandGanesh-Reflektion** [comment]
Thanks @mgrybyk for the fix.

**Comment by Sourabhmochagit** [comment]
Hi Do we have similar feature for mocha-allure-reporter (logging messages from before and after hooks)

**Comment by BorisOsipov** [comment]
it seems to be fixed only for Allure reports and not junit.

**Comment by mgrybyk** [comment]
@Sourabhmochagit if you are talking about hooks defined in wdio.conf file then no.

**Comment by mgrybyk** [comment]
lets proceed convo in https://github.com/webdriverio/webdriverio/pull/3993
