### ISSUE TITLE
Test failure without error message

### ISSUE THREAD

**Issue by UnicodeSnowman** [webdriverio/webdriverio#3518]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.4.15
 - **Mode:** standalone
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.10.10
 - **NPM version:** 6.5.0-next.0
 - **Browser name and version:** Chrome Version 71.0.3578.98 (Official Build) (64-bit)
 - **Platform name and version:** Mac OS 10.12.6
 - **Additional wdio packages used (if applicable):**  ["@wdio/cli": "^5.4.14", "@wdio/jasmine-framework": "^5.4.14", "@wdio/local-runner": "^5.4.14", "@wdio/selenium-standalone-service": "^5.4.14", "@wdio/sync": "^5.4.14"]

**Config of WebdriverIO**
```js
exports.config = {

    runner: 'local',

    specs: [
        './test/specs/**/*.js'
    ],

    exclude: [
        // 'path/to/excluded/files'
    ],

    maxInstances: 10,

    capabilities: [{
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        maxInstances: 5,
        //
        browserName: 'chrome',
        'goog:chromeOptions': {
          // to run chrome headless the following flags are required
          // (see https://developers.google.com/web/updates/2017/04/headless-chrome)
          // args: ['--headless', '--disable-gpu'],
        }
    }],

    logLevel: 'trace',
 
    deprecationWarnings: true,
 
    bail: 0,
 
    baseUrl: 'http://localhost:8001',
 
    waitforTimeout: 10000,

    connectionRetryTimeout: 90000,

    connectionRetryCount: 3,

    jasmineNodeOpts: {
        defaultTimeoutInterval: 60000,
        expectationResultHandler: function(passed, assertion) {
            // do something
        }
    },
}
```

**Describe the bug**
When I run a test that is expected to fail, I don't see any error output describing the failure. I simply receive a message of the form `Test Suites: 0 passed, 1 failed, 1 total (100% completed)`

**To Reproduce**
run `wdio`, with the following files for context.

`package.json`
```json
{
  "devDependencies": {
    "@wdio/cli": "^5.4.14",
    "@wdio/jasmine-framework": "^5.4.14",
    "@wdio/local-runner": "^5.4.14",
    "@wdio/selenium-standalone-service": "^5.4.14",
    "@wdio/sync": "^5.4.14",
    "webdriverio": "^5.4.14"
  }
}
```

`test/spec/my_test.js`
```js
describe('stuff', () => {
  it('should work', () => {
    browser.url('/');
    expect(true).toBe(false);
  });
});
```

**Expected behavior**
The resulting log should explain what failed and where the failure took place

**Log**
https://gist.github.com/UnicodeSnowman/03dcc6c0d31bb9f257befc6ec5cf6c1c

**Comment by christian-bromann** [comment]
> The resulting log should explain what failed and where the failure took place

Without any reporter it just shows the results.

**Comment by damonpam** [comment]
I have the same issue... in my case, I do have reporters configured.

Also, I'm using typescript. Check the image below and see that there are no errors during compilation. Only the test is marked as FAILED.

<img width="980" alt="google steps ts 2019-11-28 14-50-01" src="https://user-images.githubusercontent.com/12949398/69811490-76b9d400-11ee-11ea-9ac0-2eb4549357b2.png">

Any idea?

**Comment by christian-bromann** [comment]
@damonpam did you add a reporter to your `wdio.conf.js`?

**Comment by damonpam** [comment]
Yes

<img width="499" alt="wdio conf js 2019-11-28 15-30-18" src="https://user-images.githubusercontent.com/12949398/69814213-001fd500-11f4-11ea-90c9-359e08c3ee00.png">

**Comment by christian-bromann** [comment]
ok, check the wdio logs then, it seems a problem with a worker. Your tests probably never started.

**Comment by damonpam** [comment]
![Uploading wdio.log 2019-11-28 15-40-10.png…]()

**Comment by damonpam** [comment]
Ok, It seems it was caused because I had `outputDir` defined in `wdio.conf.js`. So that's why I didn't see anything in the console.
