### ISSUE TITLE
wrong test is marked as skipped

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#3520]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.4.15

**Describe the bug**
test before skipped one is marked as skipped, skipped test is missing in report

**To Reproduce**
```
describe(() => {
    it("regular pass 1", () => { })
    it.skip("regular skip", () => { })
})
```
[Include code or an example repository that can easily be set up]

**Expected behavior**
skipped test should appear in report and has no affect on other tests

**Comment by christian-bromann** [comment]
@mgrybyk can this be closed based on the PR?

**Comment by mgrybyk** [comment]
@christian-bromann yes, of course! Closing it, thanks
