### ISSUE TITLE
Using elementId with browser object

### ISSUE THREAD

**Issue by kumangxxx** [webdriverio/webdriverio#3523]
Came here from botium webdriverio connector (https://github.com/codeforequity-at/botium-connector-webdriverio)

basically, i have an elementId (something like: 0.7756214136984221-3) and a browser object.
how do i get the element from the id ? my goal is to see if the element contain something specific, like a div#reply or div#image

at first i thought its an id attribute, so i tried browser.$('#0.7756214136984221-3'). didnt work.
also tried browser.element(0.7756214136984221-3), it returned a promise, but never get resolved

got this error
```
{ Error: Argument was an invalid selector (e.g. XPath/CSS).
    at elements(".vcw-message-container") - index.js:102:34
    at waitUntil(<Function>, 5000) - index.js:102:10
  details: undefined,
  message: 'invalid selector: An invalid or illegal selector was specified',
  type: 'RuntimeError',
  seleniumStack: 
   { type: 'InvalidSelector',
     message: 'Argument was an invalid selector (e.g. XPath/CSS).',
     orgStatusMessage: 'invalid selector: An invalid or illegal selector was specified\n  (Session info: chrome=72.0.3626.96)\n  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.15.0-43-generic x86_64)' } }
```

also i cant seem to find anything about elementId on the doc, if i missed something to read, can help to direct me ?

**Environment:**
 - **WebdriverIO version:** 4.1.42
 - **Mode:** Standalone i guess
 - **Node.js version:** 8.11
 - **NPM version:** 6.7.0
 - **Browser name and version:** chrome 72
 - **Platform name and version:** ubuntu 16

**Additional context**

my code:
```
module.exports = (container, browser, elementId) => {
    console.log('ELEMENT ID', typeof elementId, elementId);
    browser.element(elementId)
    .then(element => {
        console.log('element', element)
    }).catch(console.log)
}
```

botium
https://github.com/codeforequity-at/botium-connector-webdriverio#webdriverio_getbotmessage

thanks!

**Comment by WillBrock** [comment]
You can try using the elementIdElement command. I would probably try to find a different way instead of using the id though. 

http://v4.webdriver.io/api/protocol/elementIdElement.html
