### ISSUE TITLE
selector for selectByVisibleText not always work correctly

### ISSUE THREAD

**Issue by frg-tarasov** [webdriverio/webdriverio#3529]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.4.17
 - **Mode:** WDIO Testrunne
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v10.15.1
 - **NPM version:** 6.4.1
 - **Platform name and version:** Linux

**Describe the bug**
Now element method ```selectByVisibleText``` use XPath selector: ```[normalize-space(text()) = ${formatted}]```.

If option tag contains only one text node then it work correctly, but if text nodes multiple, then selector not find target option tag.

Multiple text nodes with void strings produce for example Ember.js framework when render template.

**To Reproduce**
index.html:
```html
<select>
  <option value="0">test</option>
</select>

<script type="text/javascript">
   document.querySelector('option').prepend(
      document.createTextNode('')
   );
</script>
```

test.js:
```js
$('select').selectByVisibleText('test'); //  'no such element: Unable to locate element...
```

Browser dev console:
```js
$x('.//option[normalize-space(text()) = "test"]') // []
```

But if not add text nodes then

Browser dev console:
```js
$x('.//option[normalize-space(text()) = "test"]') // [option]
```

**Expected behavior**
Select option with target text.

**Log**
[0-0] text: Test { message:
   'no such element: Unable to locate element: {"method":"xpath","selector":"./option[normalize-space(text()) = "Test"]|./optgroup/option[normalize-space(text()) = "Test"]"}\n  (Session info: chrome=72.0.3626.81)\n  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)' }

**Comment by mgrybyk** [comment]
What will be your suggestion on how to handle this? @frg-tarasov

**Comment by erwinheitzman** [comment]
@frg-tarasov this seems an issue with your code instead of webdriverio, can you confirm this?

Navigate to:
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select

And add the code:
`
<!DOCTYPE html>
<html>
<body>

<select>
  <option value="bar">bar</option>
</select>
  
</body>
<script type="text/javascript">
   document.querySelector('option').prepend(
      document.createTextNode('foo')
   );
</script>
</html>
`

Run the code
You should see a option with the text "foobar"

This means that "test" is replaced with and empty string ""

**Comment by frg-tarasov** [comment]
> What will be your suggestion on how to handle this? @frg-tarasov
> 
> Doesn't look like a problem with wdio itself

Now i add custom command with selector ```[normalize-space(text()) = ${formatted}]``` and this work in my case.

**Comment by frg-tarasov** [comment]
@erwinheitzman In your example in result option node have two childNodes.
![image](https://user-images.githubusercontent.com/40637876/52530895-f2a96500-2d1d-11e9-8587-c6bfc84018c1.png)

And selector from webdriverio result empty array.
![image](https://user-images.githubusercontent.com/40637876/52530899-297f7b00-2d1e-11e9-901a-7a53fe973ef9.png)

This happens because add new text not replace all text in option tag but add additional node.
But webdriverio selector ```[normalize-space(text()) = ${formatted}]``` work with one text node, this do function ```text()```

**Comment by erwinheitzman** [comment]
Created a fix and also fixed a number of other issues. The changes can be found here: https://github.com/webdriverio/webdriverio/pull/3540
