### ISSUE TITLE
Support for touch in Chrome mobile emulation

### ISSUE THREAD

**Issue by mpienkowski** [webdriverio/webdriverio#353]
Since ChromeDriver 2.11 it's possible to run Chrome in mobile emulation mode (more info https://sites.google.com/a/chromium.org/chromedriver/mobile-emulation). It's now possible to provide this option like this:

 `desiredCapabilities: {
					browserName: 'chrome',
					chromeOptions: {
						mobileEmulation: {
							deviceName: 'Apple iPad 3 / 4'
						}
					}
				}`

However when I try to execute commands reserved for mobile (like touch or hold) I get this error:
`Problem: touch command is not supported on non mobile platforms 0 passing`

It'd nice to have support for this.

**Comment by fat-troll** [comment]
It's not a webdriverio issue. Chromedriver does not support touch, flicks, etc

**Comment by christian-bromann** [comment]
> It's not a webdriverio issue. Chromedriver does not support touch, flicks, etc

closing
