### ISSUE TITLE
The browser.close() inside each test cases or hook will cause invalid session id

### ISSUE THREAD

**Issue by learningandworking** [webdriverio/webdriverio#3530]
**Describe your question with as much detail as possible**
Following the command line:
`npm test -- --spec=tests/<filename>.js `

The browser is opened with the defined url in code below, but then it stopped and generated issue "invalid session ID", and all test cases failed.

 - From what I observed, all test cases (it blocks) use the same browser sessionID, so if one of test case applies browser.close(), it kill the sessionID and the next test cases (or next 'it' block) is failed - Is that correct? 
 - If my think in question#1 is correct, why the first test case is failed ?

**If it's about a specific piece of code, try and include some of it to support your question.**
```
describe('Test elements exist', function () {
  beforeEach(function () {
    browser.url("/elements/index.html");
    browser.pause(1500);
  });

  afterEach(function (done) {
  });

  it('Button1  should return true', function (done) {
    var isEnabled = browser.isExisting('#not-displayed');
    console.log("the element is enable?:" + isEnabled);
    expect(isEnabled).to.equal(true);
    browser.close();
    
  });

  it('Button2 should return true', function (done) {
    var isEnabled = browser.isExisting('#visibility-hidden');
    console.log("the element is enable?:" + isEnabled);
    expect(isEnabled).to.equal(true);
  });
})
```

**Environment (please complete the following information):**
 - **WebdriverIO version:** [4.13.2]
 - **Mode:** [standalone]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [8.15.0]
 - **NPM version:** [6.7.0]
 - **Browser name and version:** [Chrome (latest)]
 - **Platform name and version:** [Windows 10]

**Comment by christian-bromann** [comment]
Don't use close if you have only one tab/window open. That will break your webdriver session. There is no need for you in this test to call this command.

**Comment by christian-bromann** [comment]
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by Awukam** [comment]
I thing what **learningandworking** is trying to say its that, how the browser is fired up and teared down. We have an issue where it is reusing a browser for multiple tests when a cucumber feature file has multiple examples. We want it to tear down the browser and recreate between tests

**Comment by christian-bromann** [comment]
> We want it to tear down the browser and recreate between tests

You can use [`reloadSession`](https://webdriver.io/docs/api/browser/reloadSession/) for this.
