### ISSUE TITLE
Remove assumption of tab/window order back from browsers

### ISSUE THREAD

**Issue by mikesalvia** [webdriverio/webdriverio#3531]
The code in`close.js` assumes order is the order of creation and [0] is the "original" tab, this is not true and can cause race conditions when closing a new tab that is presented at [0] in the "windowsHandles()" return.

**Environment (please complete the following information):**
 - **WebdriverIO version:**  4.14.3
 - **Mode:** N/A
 - **If WDIO Testrunner, running sync/async:** N/A
 - **Node.js version:** N/A
 - **NPM version:** N/A
 - **Browser name and version:** IE 11
 - **Platform name and version:** macOS (Mojave)
 - **Additional wdio packages used (if applicable):** Lots

**Config of WebdriverIO**
N/A

**Describe the bug**
IE doesn't return tabs/windows in the order created this will cause issues with places that assume order (i.e. `close.js`)

**To Reproduce**
Not exactly easy as we need to wait for IE to give back the tabs in different orders

**Expected behavior**

**Log**
N/A

**Additional context**
N/A

> Please use the correct markdown

**Comment by christian-bromann** [comment]
This issue was moved to webdriverio-boneyard/v4#17

**Comment by mikesalvia** [comment]
Thank you! I assume this has been addressed in v5?

**Comment by christian-bromann** [comment]
v5 doesn't have such a command
