### ISSUE TITLE
Webdriverio commands are not overridable

### ISSUE THREAD

**Issue by just-boris** [webdriverio/webdriverio#3532]
**Environment (please complete the following information):**
 - **WebdriverIO version:** v5.4.17
 - **Mode:** Standalone
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 8.9.4
 - **NPM version:** 6.4.1
 - **Browser name and version:** n/a
 - **Platform name and version:** n/a
 - **Additional wdio packages used (if applicable):** n/a

**Config of WebdriverIO**
n/a

**Describe the bug**
I am trying to use `jest.spyOn(browser, 'deleteSession')` and it fails with the error

```
TypeError: Cannot assign to read only property 'deleteSession' of object '[object Object]'
```

**To Reproduce**
The minimal code to reproduce:

```js
import { remote } from 'webdriverio'

const browser = await remote({});
browser.deleteSession = () => {}; // throws
```

**Expected behavior**
I expect prototype functions to be overridable

**Additional context**

I am developing a set of utils on top of webdriverio in standalone mode. The most simplified version is here:

```js
async function tryWithBrowser(fn) {
   const browser = await remote({});
   try {
     await fn(browser);
   } finally {
     browser.deleteSession();
   }
}

// usage
tryWithBrowser(await browser => {
  await (await browser.$('#button')).click();
});
```

Then I am trying to write a test for this:

```js
test('should close session after execution', async () => {
   let deleteSpy;
   await tryWithBrowser(browser => {
      deleteSpy = jest.spyOn(browser, 'deleteSession'); // here it fails
   });
   expect(deleteSpy).toHaveBeenCalled();
})
```

The test does not work, because there is no way to spy on deleteSession function. If you also have other ideas how to test this behavior, I would be happy to learn.

**Comment by christian-bromann** [comment]
For testing purposes you would want to return a stub for the `remote` function. Ideally stub the whole webdriverio package.

I don't think it is a good idea to allow to overwrite core functions for various reasons. For this testing purpose it is not required and for the general usage purpose I would heavily argue against it.
