### ISSUE TITLE
startRecordingScreen and stopRecordingScreen don't work as expected

### ISSUE THREAD

**Issue by Gilad-WT** [webdriverio/webdriverio#3537]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.2.8
 - **Mode:** [Standalone mode or WDIO Testrunner] Standalone 
 - **Node.js version:** 10.14.2
 - **NPM version:** 6.4.1
 - **Platform name and version:** Windows 10

**Config of WebdriverIO**
wdio.remote({
        hostname : opts.hostIp,
        port : opts.hostPort,
        logLevel : "silent",
        capabilities : {
            platformName: "Android",
            platformVersion: "8.1",
            deviceName: "Android Emulator",
            app: opts.app,
            automationName: "UiAutomator2",
            newCommandTimeout : 600
        }
    });

**Describe the bug**
startRecordingScreen and stopRecordingScreen don't work as expected

**To Reproduce**
```
async function test(){
let driver = await wdio.remote({
        hostname : opts.hostIp,
        port : opts.hostPort,
        logLevel : "silent",
        capabilities : {
            platformName: "Android",
            platformVersion: "8.1",
            deviceName: "Android Emulator",
            app: opts.app,
            automationName: "UiAutomator2",
            newCommandTimeout : 600
        }
    });
await driver.startRecordingScreen('./video.mp4', 20000000 *181, 1, 20000000)
await new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve();
            }, 10000);
        });
await driver.stopRecordingScreen()
}
test()
```
The above code should according to the documentation here (https://webdriver.io/docs/api/appium.html) create a mp4 file named video.mp4 in the current dir but it does not 

Instead I have to use the following code to generate the file

```
async function test(){
let driver = await wdio.remote({
        hostname : opts.hostIp,
        port : opts.hostPort,
        logLevel : "silent",
        capabilities : {
            platformName: "Android",
            platformVersion: "8.1",
            deviceName: "Android Emulator",
            app: opts.app,
            automationName: "UiAutomator2",
            newCommandTimeout : 600
        }
    });
await driver.startRecordingScreen('./video.mp4', 20000000 *181, 1, 20000000)
await new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve();
            }, 10000);
        });
let recordingAsBase64Str = await driver.stopRecordingScreen()
let videoBinary = Buffer.from(recordingAsBase64Str, 'base64')
await fs.writeFileSync('./video.mp4', videoBinary)
}
test()
```
this code does create the file

**Expected behavior**
should create a file with the video

**Comment by mgrybyk** [comment]
Appium itself is not recording file, see http://appium.io/docs/en/commands/device/recording-screen/stop-recording-screen/
```
remotePath
The path to the remote location, where the resulting video should be uploaded. The following protocols are supported http/https, ftp. Null or empty string value (the default setting) means the content of resulting file should be encoded as Base64 and passed as the endpoint response value. An exception will be thrown if the generated media file is too big to fit into the available process memory.
```
Have to update documentation.

**Comment by Gilad-WT** [comment]
@mgrybyk according to the wdio docs https://webdriver.io/docs/api/appium.html#startrecordingscreen the first parm of the function startrecordingscreen is filePath which is a string representing the path to the location where the video file should be saved. I passed in './video.mp4' aka create a file named video.mp4 in the current dir. I also tried it with './' aka this dir because I thought it may need a dir and not a file but that didn't work either.

To the best of my knowledge (and according to the logs appium is printing) appium is creating a mp4 file on the phone / emulator and once we tell it to stop recording it returns the contents of the file to whoever is talking to appium as a base64 encoded string and then deletes the file from the phone / emulator.

**Comment by christian-bromann** [comment]
@Gilad-WT tbh I just copied the docs over to my best knowledge. I never used that command and I am not sure what it does exactly so the WDIO docs might be not correct here.

**Comment by mgrybyk** [comment]
We can update doc to match appium doc and add new command to wdio that will save file in same way as screenshot.
Do we need both?

**Comment by christian-bromann** [comment]
> Do we need both?

What is both?

**Comment by Gilad-WT** [comment]
@christian-bromann the appium docs are different so It think you may have copied an old version.

@mgrybyk  I think we should just match the appium spec. If you want we can add a function startSimpleScreenRecord() that starts the recording and stopSimpleScreenRecord(path) which decodes the string appium returns from base64 to a normal mp4 string and saves it according to the path param

**Comment by mgrybyk** [comment]
@christian-bromann I suggest to do the following
- fix our docs to match Appium for these recording commands 
- introduce new command: saveRecordingScreen that will stop recording and write recorded video to file.

@Gilad-WT I'd better avoid adding something like startSimpleScreenRecord, I think it is better to update docs and make these recording commands work according to Appium API and introduce new command (optional, if we really need it) for saving video

**Comment by Gilad-WT** [comment]
@mgrybyk agreed

**Comment by christian-bromann** [comment]
> I suggest to do the following

I am fine with that

**Comment by sachinvermacs** [comment]
> We can update doc to match appium doc and add new command to wdio that will save file in same way as screenshot.
> Do we need both?


Can you please confirm if either of these two works with emulators( with any android API level)
