### ISSUE TITLE
add wdio-cli command line switch / option to skip "clear screen" when wdio starts

### ISSUE THREAD

**Issue by mo** [webdriverio/webdriverio#3542]
In my projects I often have a single "npm run check-all-the-things" script that runs unittests, eslint, cli testcases, e2e tests in chrome and then e2e tests in firefox.

In webdriver 4.x I could kick off this script and then go fetch some coffee and then inspect the full log output when I got back. However, in webdriver 5.x wdio-cli _ALWAYS_ clears the screen and drops all previous terminal output when it starts being that I cannot see failures in unittests, eslint... the only errors I can see are from the last "e2e tests in firefox" part.

It would be very nice to have a wdio-cli command line switch / option that skipped clearing the screen on startup so that all logs are left on the screen.

Also the number of stdout lines that are visible on the screen seems hardcoded in packages/wdio-cli/src/interface.js of wdio-cli right now i.e. this.printStdout(5), and I think it would be useful to have some config or command line switch to control how many lines it shows.

**Comment by wildergonzo** [comment]
Same problem here. Is there any way to avoid stdout clearing?

**Comment by christian-bromann** [comment]
> in webdriver 5.x wdio-cli _ALWAYS_ clears the screen and drops all previous terminal output when it starts being that I cannot see failures in unittests, eslint

Shouldn't your pipeline stop if you have eslint or unit test errors?

We are currently working on improving the CLI output and we are planning to have a CI conform version where it just prints all results as they arrive.

**Comment by christian-bromann** [comment]
With the rewritten interface it won't clear the terminal anymore.

**Comment by mo** [comment]
Thank you for fixing this @christian-bromann
