### ISSUE TITLE
custom service plugin to automate the start/stop of the server during a wdio test session.

### ISSUE THREAD

**Issue by LayMuiToh** [webdriverio/webdriverio#3543]
**Pre-check**
I refer to this link https://webdriver.io/docs/customservices.html
but unable to know what and how to add to the wdio.conf.js and service class onPrepare and onComplete method
what should I put to start the server in jar file
the command is java -jar VoiceAutomationServer-1.0.1.jar

**Describe the improvement**

I'd like to report
- [ x] Unclear documentation
- [ ] A typo
- [ ] Missing documentation
- [ x] Other

**Description of the improvement / report**
will be good to have a simple example on how to use.
including configuration settings
for example: in the java client I need to add this setting
 System.setProperty("VoiceAutomationServerEndpoint","<VoiceAutomationServerIP:Port>");
        //Signup to voicerss and get your api key
        System.setProperty("VoiceRssKey","<VoiceRSSAPIKEy>");

how does it look like in webdriver.io (wdio.conf.js)?

**Comment by WillBrock** [comment]
You can take a look at how the selenium-standalone service is setup to get an idea or feel free to ask these types of questions on the [Gitter Channel](https://gitter.im/webdriverio/webdriverio). This is not necessarily a bug with WebdriverIO.

https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-selenium-standalone-service/src/launcher.js

**Comment by LayMuiToh** [comment]
Hi Will, I was asked to look at this link earlier but I still can't figure how this is being setup in wdio.conf.js. Do I need to create a npm package?
this is not a bug but it's the documentation I am requesting to be clear on how to configure and setup and with a simple example
the link https://webdriver.io/docs/customservices.html is not clear
