### ISSUE TITLE
Ability to add custom wait* / is* commands

### ISSUE THREAD

**Issue by xlenz** [webdriverio/webdriverio#3545]
- **WebdriverIO version:** 5.4.17

**Is your feature request related to a problem? Please describe.**
I want to be able to add custom commands to element like
`const isDisplayed = $('myElem').isDiplayedWithin(5000)`

command example
```
browser.addCommand("isDisplayedWithin", function (timeout = TIMEOUTS.wait) {
   // also we have access here to this.selector, this.parent.$, this.parent.$$ which is cool!

    try {
        this.waitForDisplayed(timeout)
        return true
    } catch (err) {
        return false
    }
}, true)
```

that will wait for element visibility for some time if it is not visible and will return true or false afterwards.

It is super helpful when doing various assertions like
```
login()
expect($(header.username).toBeDisplayedWithin()).toBe(true)
```

waitForDisplayed is not suitable here.

**Describe the solution you'd like**

adjust
https://github.com/webdriverio/webdriverio/blob/6a6e5ba36d849fe279451d5217f6e74e1862967b/packages/webdriverio/src/middlewares.js#L21

so that it will be possible to add custom waitFor commands

```
.match(/(wait(Until|ForDisplayed|ForExist|ForEnabled)|waitFor(.*)|is(.*)Existing(.*)|is(.*)Displayed(.*))/)
```
So that user can add commands like:
- waitForSomething
- isFooDisplayed
- isExistingBar

**Describe alternatives you've considered**

- ability to suppress waitFor* exceptions and return value instead (true/false)
- pass params to isExisting, isDisplayed commands so that we will wait for element to be visible/existing if it is not visible/existing. And be able to invert it

**Additional context**

i'd better allow user to add custom commands

**Comment by abjerstedt** [comment]
To clarify - the main request here is to be able to add a custom command that can skip the implicit wait in the middleware?

**Comment by mgrybyk** [comment]
@abjerstedt  skip waitForExist in middlewere https://github.com/webdriverio/webdriverio/blob/6a6e5ba36d849fe279451d5217f6e74e1862967b/packages/webdriverio/src/middlewares.js#L31

I'm doing PR for hits

**Comment by christian-bromann** [comment]
> waitForDisplayed is not suitable here.

Why?

**Comment by mgrybyk** [comment]
waitForDisplayed doesn't return true/false and throws exception in case element is not found, behavior is correct, have no objections.

This request is not about waitForDisplayed, it is about possibility to skip calling waitForExist for custom element commands so user can add commands like.
There is some possibility already however it is limited by certain command names.

**Comment by mgrybyk** [comment]
@abjerstedt @christian-bromann also, it is not possible to add alias like **waitForNotExisting** right now because of same reason.

**Comment by christian-bromann** [comment]
Let's continue convo in #3548
