### ISSUE TITLE
Add support for file patterns and test suites

### ISSUE THREAD

**Issue by bclinkinbeard** [webdriverio/webdriverio#355]
Another feature of the CLI should be to support globbing patterns of test files to run, as well as grouping into "suites" as Protractor does. Suites are used to divide tests into sub-groups, to enable running only the tests you are interested in.

```js
var config = {
    specs: [
        './e2e/**/*.spec.js'
    ],
    // OR
    suites: {
        basics: './e2e/index.spec.js',
        locators: './e2e/locators.spec.js'
    },

    baseUrl: 'http://localhost:3333'
};
```

**Comment by thedeeno** [comment]
@christian-bromann if you do this please implement it via another project or via plugins. One of my biggest gripes with this ecosystem is that too many projects are mixing concerns and increasing their scope needlessly . For example, your comment above makes me nervous: If I want cucmber, mocha shouldn't be coming along for the ride. It'd be surprising to me if this driver knew anything about cucumber.

Awesome work on this project btw, it looks very cool. I think I'll be testing it out on my team next week.

**Comment by christian-bromann** [comment]
@thedeeno thanks for your comment. It makes perfectly sense to have an own project for the CLI. Still haven't quite figured out how I put everything together. The CLI needs a custom runner for each framework to assign capabilities to each child process.

**Comment by christian-bromann** [comment]
implemented
