### ISSUE TITLE
Unable to use JSON as an input to run browser.execute() with addCommand()

### ISSUE THREAD

**Issue by danielyoun82** [webdriverio/webdriverio#3551]
**Environment:**
 - **WebdriverIO version:** 5.4.17
 - **Mode:** WDIO Testrunner - Mocha
 - **Browser name and version:** Chrome 72
 - **Platform name and version:** CentOS Linux release 7.6.1810 (Core) 
 - wdio-chromedriver-service is being used to launch chrome

**Describe the bug**
Malformed type error was generated when browser.execute try to run with JSON input

**To Reproduce**
```
const testJSON1 = {
            abc: 'abc'
        };
browser.execute(function (testJSON) {
            console.log(testJSON);
        }, testJSON1);
const testJSON2 = {
            'abc': true
        };
browser.execute(function (testJSON) {
            console.log(testJSON);
        }, testJSON2);
```

**Expected behavior**
browser.execute() to be allowed to be called with JSON input like in WDIO v4

**Log**
Stacktrace: Error: Malformed type for "args" parameter of command executeScript
Expected: (string|object|number|boolean)[]
Actual: object

For more info see https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidexecute

    at Browser.<anonymous> (/srv/api/author/node_modules/webdriver/build/command.js:66:15)
    at Browser.runCommand (/srv/api/author/node_modules/@wdio/sync/build/wrapCommand.js:32:32)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)

**Comment by mgrybyk** [comment]
```
    const testJSON1 = {
      abc: 'abc'
    };
    browser.execute(function (testJSON) {
      console.log(testJSON);
    }, testJSON1);
```
works fine for me, browser chrome

**Comment by danielyoun82** [comment]
Ah my bad, It seems browser execute was changed to accept one argument only which can be array in V5. I was passing multiple arguments to browser execute which was the cause of failure, as that is the way how was using it in V4

**Comment by WillBrock** [comment]
@danielyoun82 I can't reproduce the error you're describing when adding a custom command. Can you provide more information on what is going wrong, an example repo would be nice?

**Comment by danielyoun82** [comment]
@WillBrock It was nothing to do with JSON, it seems execute just can't seem to accept **undefined** as a value. I am not sure how best to report this issue, do you want me to create a new issue and close this one?

**Comment by WillBrock** [comment]
@danielyoun82 I think you should do some checks before passing undefined or null to browser.execute. It doesn't really make sense to execute on nothing. If you have a use case to do it let me know.

**Comment by danielyoun82** [comment]
@WillBrock I use it to call public method from browser as it accepts undefined as input which omits the second argument
e.g. 
```
browser.execute(function(a, b) {
    window.myapp.mypublicmethod(a, b);
}, myJSON, undefined);
```
This can definitely be changed, just a little inconvenience on my side as I need to write few extra code to it, that's all.
