### ISSUE TITLE
Cannot read property 'name' of null

### ISSUE THREAD

**Issue by ilyubin** [webdriverio/webdriverio#3552]
**Environment:**
 - **WebdriverIO version:** 5.4
- **Mode:** remote Moon
- **If WDIO Testrunner, running sync:** sync
 - **Node.js version:** 10.15.0
 - **NPM version:** 6.7.0
 - **Browser name and version:** Chrome 72
 - **Platform name and version:** linux - alpine
 - **Additional wdio packages used:** 
    "@wdio/allure-reporter": "^5.4.16",
    "@wdio/cli": "^5.4.17",
    "@wdio/dot-reporter": "^5.4.15",
    "@wdio/local-runner": "^5.4.17",
    "@wdio/mocha-framework": "^5.4.14",
    "@wdio/spec-reporter": "^5.4.15",
    "@wdio/sync": "^5.4.14",

**Config of WebdriverIO**
https://gist.github.com/ilyubin/97aff46b5fb8150465cfca5948ca2f0f

**Describe the bug**
The error occurs when trying open the URLs with:

```js
	browser.url(path);
```

In allure.report it looks like:

	POST /session/:sessionId/url
	{
		"url": "https:/<our_site>/search?text=носки"
	}

**Error:**

	Cannot read property 'name' of null
	TypeError: Cannot read property 'name' of null
	at Request._callback (/tests/node_modules/webdriver/build/request.js:130:17)
	at Request.self.callback (/tests/node_modules/request/request.js:185:22)
	at Request.emit (events.js:182:13)
	at Request.EventEmitter.emit (domain.js:442:20)
	at Request.<anonymous> (/tests/node_modules/request/request.js:1161:10)
	at Request.emit (events.js:182:13)
	at Request.EventEmitter.emit (domain.js:442:20)
	at IncomingMessage.<anonymous> (/tests/node_modules/request/request.js:1083:12)
	at Object.onceWrapper (events.js:273:13)
	at IncomingMessage.emit (events.js:187:15)

**Log**
-

**Additional context**
-

**Comment by ianwalter** [comment]
Don't see where crome is defined in your wdio.conf.js, maybe you meant `browserName: 'chrome'` instead.

**Comment by mgrybyk** [comment]
How to reproduce this? @ilyubin

**Comment by yepninja** [comment]
@ianwalter 
<details>
<summary>Compiled config</summary>

```json
{
	"config": {
		"hostname": "localhost",
		"port": 4444,
		"runner": "local",
		"specs": [
			"./test/specs/**/*.js"
		],
		"suites": {
			"analytics": [
				"./test/specs/analytics/**/*.js"
			],
			"analytics.mobile": [
				"./test/specs/analytics.mobile/**/*.js"
			],
			"catalog": [
				"./test/specs/catalog/**/*.js"
			],
			"catalog.mobile": [
				"./test/specs/catalog.mobile/**/*.js"
			],
			"checkcart": [
				"./test/specs/cart/**/*.js",
				"./test/specs/checkout/**/*.js"
			],
			"payments": [
				"./test/specs/payments/**/*.js"
			],
			"pdp": [
				"./test/specs/pdp/**/*.js"
			],
			"csma": [
				"./test/specs/csma/**/*.js"
			],
			"marketing": [
				"./test/specs/bx-marketing-1/**/*.js"
			],
			"infra": [
				"./test/specs/infra/**/*.js"
			],
			"storefront": [
				"./test/specs/storefront/**/*.js"
			]
		},
		"exclude": [],
		"maxInstances": 1,
		"capabilities": [
			{
				"maxInstances": 10,
				"browserName": "chrome",
				"goog:chromeOptions": {
					"args": [
						"incognito",
						"disable-notifications",
						"disable-extensions",
						"disable-infobars"
					]
				}
			}
		],
		"logLevel": "warn",
		"deprecationWarnings": true,
		"bail": 0,
		"baseUrl": "<our_site>",
		"waitforTimeout": 6000,
		"connectionRetryTimeout": 90000,
		"connectionRetryCount": 3,
		"services": [
			"selenium-standalone"
		],
		"framework": "mocha",
		"reporters": [
			"spec",
			[
				"allure",
				{
					"outputDir": "reports/allure-results"
				}
			],
			"dot"
		],
		"mochaOpts": {
			"ui": "bdd",
			"timeout": 90000000
		}
	}
}
```

</details>

**Comment by mgrybyk** [comment]
@ilyubin tried 
`browser.url("/search?q=носки")`
having baseUrl 'https://google.com'

works fine. Can you help with reproducing this please?

**Comment by yepninja** [comment]
@mgrybyk PR explains issue
