### ISSUE TITLE
Configuring WebdriverIO 4 with babel

### ISSUE THREAD

**Issue by dariaszmajduch** [webdriverio/webdriverio#3553]
Hello,

I'm trying to run a simple test using WebdriverIO in version 4, Page Objects, Cucumber framework and additionally some elements from ES6. 

For now I have a blocking problem with configuring babel to compile ES6. 

I installed some babel packages (listed below) and prepared:
1) in file .babelrc:
```
{
    "presets": [
        ["env", {
            "targets": {
                "node": "current"
            }
        }]
    ]
}
```
2) in wdio.conf.js:
```
before: function() {
        require('babel-register');
}
```

To run test I use this command:
```
"scripts": {
    "test": "./node_modules/.bin/wdio wdio.conf.js"
},
```

When I tried to run test I have console error (in other file) when I want to import something so I suppose that changing ES6 to ES5 doesn't work:
```
import { defineSupportCode } from 'cucumber';
import LoginPage from '../page_objects/login.page';
import SportListPage from '../page_objects/sport_list.page';

defineSupportCode(function({ Given }) {
    Given('user is log in', () => {
        LoginPage.openUrl();
        LoginPage.login();
    });
});
``` 

Below I add also information about my environment and devDependencies which I use.

Just for information I try to complete a solution visible here: https://webdriver.io/docs/babel.html and similar solution used in boilerplate projects, but without success.

I will be very grateful for any help.

**Environment:**
 - **WebdriverIO version:** 4.14.1
 - **Mode:** Standalone
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.15.0
 - **NPM version:** 6.7.0
 - **Browser name and version:** Chrome
 - **Platform name and version:** macOS 10.13.6
 - **Additional wdio packages used (if applicable):** 
"devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "babel-register": "^6.26.0",
    "wdio-allure-reporter": "^0.8.3",
    "wdio-cucumber-framework": "^2.2.8",
    "wdio-selenium-standalone-service": "0.0.12",
    "wdio-spec-reporter": "^0.1.5",
    "webdriverio": "^4.14.1"
  },

**Comment by TuHuynhVan** [comment]
I don't think this's WebdriverIO bug, join our gitter channel for this kind of question
https://gitter.im/webdriverio/webdriverio
