### ISSUE TITLE
Switch To Parent Frame after immediate page redirection

### ISSUE THREAD

**Issue by charan2628** [webdriverio/webdriverio#3554]
Browser: Firefox
Driver: geckodriver-v0.23.0-win64 (running in localhost)
WebdriverIO: v5.4.15
NodeJs: v10.15.0

Q: I had a page with overlay whose contents are in iframe, I have to click close button in that iframe, the moment I click the close button the page goes to next page. 
So for closing the overlay I'm switching to that overlay iframe (using: browser.switchToFrame($('some css selector')) ) and clicking the close button, now if I use 'browser.switchToParentFrame()' it keep on running nothing happening (I left it, it keep on running for 20 minutes and still running) no error messages or anything it's running with browser opened.
I tried without switching to parent frame and tried accessing elements in next page (the redirected page after clicking close button in iframe) it showing ERROR as 'webdriver: Request failed due to unknown error: TypeError: can't access dead object'.
Please anyone help me with this?

**Comment by WillBrock** [comment]
@charan2628 Can you turn on your ```logLevel``` in wdio.conf.js to trace and see if you get more output and post it here? Also post the code you're trying to use. I did a basic test and was able to have the test pass.

**Comment by charan2628** [comment]
@WillBrock I solved it by waiting for the next page to load and using 'browser.switchToFrame(null)' but 'browser.switchToParentFrame()' is not working even after next page completely loaded . I can able to access the elements in the next page after that.
My code is in my repository 'THD-Automation' in that please check the 'switch to parent frame bug fixed' commit, in that changes made to 'test/pageobjects/ThdOverlayWrapper.js' line 20 caused me the issue.
My issue is solved you can close it. Thanks @WillBrock
