### ISSUE TITLE
Cannot extract a capabilities from the request for custom capabilities

### ISSUE THREAD

**Issue by lukaszfryc** [webdriverio/webdriverio#3556]
**Describe your question with as much detail as possible**
I use Zalenium as my Selenium Grid. It has an option to set `name` in `capabilities` to name a test that is executed (https://github.com/zalando/zalenium/issues/480#issuecomment-380156515). But, when I try to set it in WebdriverIO I get an error from the Grid:

```
20:48:04.781 [qtp79290250-17] WARN  o.s.jetty9.server.HttpChannel - /wd/hub/session java.io.IOException: org.openqa.grid.common.exception.GridException: Cannot extract a capabilities from the request: {"capabilities":{"alwaysMatch":{"browserName":"chrome","goog:chromeOptions":{"args":["--disable-gpu","--window-size=1280,800","--window-size=1280,800"]},"name":"test1"},"firstMatch":[{}]},"desiredCapabilities":{"browserName":"chrome","goog:chromeOptions":{"args":["--disable-gpu","--window-size=1280,800","--window-size=1280,800"]},"name":"test1"}}
```

Do you have any idea how to set it up?

**If it's about a specific piece of code, try and include some of it to support your question.**
My wdio.conf.js:

```
   capabilities: [{
        browserName: 'chrome',
        "goog:chromeOptions": {
            args: ['--headless', '--disable-gpu', '--window-size=1280,800'],
        },
        name: 'test1'
    }],
```

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.4.9
 - **Node.js version:** v8.9.1

**Comment by lukaszfryc** [comment]
I just found out that I need to use `zal` prefix. E.g. `"zal:name": "test1"`.

**Comment by theduykh** [comment]
I'm using webdriverio. It helps me when running multiremote browser and mobile 😃 
`capabilities: {
    firefox: {
      capabilities: {
        browserName: 'firefox',
        'moz:firefoxOptions': {
          'args': ['-headless'
        }
      }
    },
    mobile: {
      capabilities: {
        'zal:deviceName': 'Nexus_5X_26',
        'zal:platformName': 'Android',
        'zal:noReset': true,
        'zal:app': 'pathToAPK',
        'zal:appPackage': 'com.demo.myApp',
        'zal:appActivity': 'myApp.activity.MainActivity'
      }
    },
  },`

keywords: webdriverio multiremote browser appium
