### ISSUE TITLE
WebdriverIO and page object pattern

### ISSUE THREAD

**Issue by thibaut-sticky** [webdriverio/webdriverio#356]
Hi, 

In the Java or protractor world, we can implement the [Page Object](https://code.google.com/p/selenium/wiki/PageObjects) pattern.

With protractor which use WebdriverJS, it looks like

```Javascript
var LoginPage = function() {
    this.userName = element(by.input('login.userName'));
    this.password = element(by.input('login.password'));
    this.loginButton = element(by.css('Button[ng-click^="login"]'));
    this.logoutButton = element(by.css('Button[ng-click^="logout"]'));
    this.registerButton = element(by.css('Button[ng-click^="register"]'));
    this.greeting = element(by.binding("Welcome, {{currentBrewer.FirstName}}"));
    this.gravatarImage = element(by.tagName('img'));
};

module.exports = new LoginPage();
```

```JS
it('should allow a user to log in', function () {
        loginPage.userName.sendKeys('test_user');
        loginPage.password.sendKeys('abc123');
        loginPage.loginButton.click();
        browser.waitForAngular();
        expect(loginPage.greeting.getText()).toContain('Welcome, Test User');
    });
```

As you can see, `element(by.css('Button[ng-click^="register"]'));` returns an object on which we can send again a command with a new scope.

Is it possible to have the same approach using WebdriverIO? This pattern could be really helpful.

**Comment by christian-bromann** [comment]
POs should be easy to do now with a solid promise foundation like in `v3`. This issue is requires only a solid documentation to be resolved

**Comment by christian-bromann** [comment]
Closing since we have a separate ticket for documentation (see #524).

**Comment by christian-bromann** [comment]
reopening as we scratched that for the release.

**Comment by christian-bromann** [comment]
no specific examples out yet but I put together some samples which are also not done yet, but I will definitely have something published with the next release

**Comment by christian-bromann** [comment]
all examples above aren't working with WebdriverIO `v3`

**Comment by rocketsue** [comment]
Is there any way I can help with this? I want to move our tests from nightwatchjs to webdriverio, but atm I have no idea what the page objects should look like.

**Comment by christian-bromann** [comment]
@rocketsue currently the best way to do that is using yields and ES6 classes (maybe using babel). Haven't put up a proper tutorial but will follow soon

**Comment by dandv** [comment]
Looks like [the Xolvio guys](https://github.com/webdriverio/webdriverio/issues/583) have implemented a combo of WebdriverIO + PageObject pattern + CucumberJS + Chai into the [ChimpJS module](https://chimp.readme.io/docs).

**Comment by mmrko** [comment]
+1

**Comment by rocketsue** [comment]
@christian-bromann since I am fairly new to programming, I will leave this up to people who know how to ;) but thanks!

@dandv If I'm right you're referring to the [Chimp Widgets](https://chimp.readme.io/docs/chimp-widgets) section. I'm going to look into it tomorrow.

**Comment by ebenezer29** [comment]
I've been writing tests in java and python and following the same pattern I was able to automate the beginnings of a functional cart test using webdriverio and es6 classes. I installed io.js and can run this from the command line. Note the use of strict mode at the top of the program, you can't use classes without that. This could probably be accomplished in es5 using objects and functions but I couldn't get that to work. The reason for the pauses in the 2nd class is because in my use case there is an animated menu that requires the wait. Hope this helps even though it barely does anything.

"use strict"
var webdriverio = require("webdriverio");
var options = {
    desiredCapabilities: {
        browserName: "chrome"
    }
};

var driver = webdriverio.remote(options);

class StartPage {
    setup(){
        driver.init().windowHandleSize({width: 1280, height: 720})
        .url("http://www.yoursite.com")
        .getTitle().then(function(results){
            console.log(results)
        });
    }
}

class MainPage {
    helpMeChoose(){
        driver.pause(10000)
        .click(".has-dropdown")
        .pause(1000)
        .click("=Help Me Choose")
        .pause(1000)
        .url(function(error, result){ 
            console.log(result.value) 
        });
        return 0;
    }
}

let page1 = new StartPage();
let page2 = new MainPage();

page1.setup();
page2.helpMeChoose();

driver.end();

**Comment by ebenezer29** [comment]
I got the example above to work in es5 syntax using an IIFE instead of all of the classes. This allows access to the function in a static way, no page object instantiation and no longer requires io.js or "use strict". This method is better then the es6 example above, note the pause commands, without those I get strings of errors about elements not being found.

```javascript
var webdriverio = require("webdriverio");
var options = {
    desiredCapabilities: {
        browserName: "chrome"
    }
};

var driver = webdriverio.remote(options);

(function () { 

var MainPage = function() { };

MainPage.setup = function() {
    driver.init().windowHandleSize({width: 1280, height: 720})
    .url("http://www.webroot.com")
    .getTitle().then(function(results){
        console.log(results)
    });
};

MainPage.helpMeChoose = function() {
    driver.pause(4000)
    .click(".has-dropdown")
    .pause(1000)
    .click("=Help Me Choose")
    .pause(2000)
    .url(function(error, result){ 
        console.log(result.value) 
    });
};

MainPage.setup();
driver.pause(5000);
MainPage.helpMeChoose();

})();
```

**Comment by Kabalas** [comment]
@ebenezer29 I like your page object example. However I'd really love a bit different approach I'd like to show. Here is my example with using mocha (it doesn't work though).

```javascript
var LoginPage = (function() {

	var emailInput = '#login',
		passwordInput = '#password',
		signInButton = '#signbutton';

	var LoginPage = {
		goToWebsite: function() {
			browser
				.url('http://somewebsite.com', function() {
					console.log('went to http://somewebsite.com');
				});
		},

		setEmail: function(strEmail) {
			browser
				.setValue(emailInput, strEmail, function() {
					console.log('set email');
				});
		},

		setPassword: function(strPassword) {
			browser
				.setValue(passwordInput, strPassword, function() {
					console.log('set password');
				});
		},

		clickSignIn: function() {
			browser
				.click(signInButton, function() {
					console.log('clicked signin button');
				});
		},

		loginToWebsite: function(strEmail, strPassword) {
			LoginPage.goToWebsite();
			LoginPage.setEmail(strEmail);
			LoginPage.setPassword(strPassword);
			LoginPage.clickSignIn();
		}
	};

	return LoginPage;

})();

describe('login test', function () {

	this.timeout(99999999);

    it('should login to the page', function(done) {
        LoginPage.loginToWebsite('email', 'secret_password');
        
    });
});
```
The problem with this test is that loginToWebsite method executes asynchronously so I'm getting sequence like "goToWebsite -> clickSingIn  -> setPassword -> setEmail" which will fail the test and it's not what I want.
Do you have idea how to execute it synchronously one by one and what am I doing wrong?
thanks! :)

**Comment by ebenezer29** [comment]
I completely understand your difficulty with parts of the program executing out of order and causing unpredictable behavior. I wanted to run my tests in a loop that iterates through all of the different product options, and I could not manage to get my main test running function to exist in any kind of loop without it executing all iterations at once and messing up the program. I referred to a separate issue on github which recommended "async.js", which may be what your program needs to prevent the unwanted behavior.

https://github.com/webdriverio/webdriverio/issues/256   

Unfortunately, this didn't work for me and I rewrote my tests using webdriverjs, which can use the exact same page object patterns above but will wait until my main testRunner function has completed before moving to the next iteration.

There is an example on the webdriverjs getting started page that describes how to use mocha and that framework to achieve what you are trying to do.

https://code.google.com/p/selenium/wiki/WebDriverJs#Writing_Tests

I think the question about using webdriverio, page object model, mocha, and async.js to avoid the unwanted asynchronous behavior has yet to be provided.

**Comment by christian-bromann** [comment]
@ebenezer29 your example above aren't working because you try to execute asynchronous commands in a synchronous way. Commands get executed in order when they are chained, so

```js
browser.click("#elemA").click("#elemB");
```

clicks on elemA first before it clicks on elemB whereas

```js
browser.click("#elemA")
browser.click("#elemB");
```

clicks on both elements at (almost) the same time. You need to keep that in mind when using WebdriverIO. `selenium-webdriver` let's you execute commands in a specific context (the `it` blocks) which will ensure that each command will executed in order as if you write synchronous code in java. We are almost there to write such tests as well. Right now WebdriverIO supports generators, so using the wdio test runner:

```js
describe("myFeature", function() {
    it("does something", function() {
        yield browser.click("#elemA");
        yield browser.click("#elemB");
    });
});
```

allows you to do everything synchronous (like in selenium-webdriver). With all the ES2015 features you can write pretty nice page objects even with WebdriverIO! I haven't had the time yet to propose you guys a fully proof example of how to build that up.

**Comment by ebenezer29** [comment]
I've had some difficulties getting the timing right when doing a series of actions in a sequence which were solved by "padding" out the steps with liberal pauses. I found that these pauses were actually really sensitive because of the speed of nodejs.

```javascript
MainPage.selectBusinessProduct = function() {
        driver.pause(10000)
        .click(".business")
        .pause(1000)
        .click("=Business Package")
        .pause(2000)
        .url(function(error, result){
            console.log(result.value)
        });
}	
```
Unfortunately, when webdriverio crashes, it will seem to indicate that there were problems with all of the commands in the program, which makes debugging confusing.
I considered using a chain of "waitForVisible" commands instead of the pauses. Maybe that is what your program needs to avoid failing.

http://webdriver.io/api/utility/waitForVisible.html

**Comment by ebenezer29** [comment]
@christian-bromann 
I think that's the part I was missing when I was trying to iterate my test in a loop and ran into a problem.

**Comment by johntowell** [comment]
So what is the best example to follow for page objects in webdriver.io? Or is that still in the works?

**Comment by kabirsikand** [comment]
@christian-bromann and @johntowell asked me to share:

Here's how I organized my page object pattern. I created a base page with a bunch of common methods. Most important one here is the `validate` method. You'll see why in the sample test at the end.

*Page.coffee*
```coffeescript
 module.exports = class Page
  url: null
  browser: null
  timeouts: null

  constructor: (@browser) ->

  toString: -> "Page"

  open: ->
    @browser.url(@url)

  getUrl: ->
    @browser.url()

  validateUrl: ->
    url = yield @getUrl()
    url.indexOf(@url) isnt -1

  setOptions: (options) ->
    for key, value of options
      @[key] = value

  self: ->
    return @

  validate: (name) ->
    new RSVP.Promise (resolve, reject) =>
      unless name is @toString()
        reject("#{@toString()} is not a #{name}")
      else
        @validatePage().then(-> resolve(true))
```


In this Page Object, we extend the base Page class, and define a `validatePage` method, which finds some characteristic attribute of this page and validates that it is on the page. We also define some Actions/Services that the page can perform.

*SignInPage.coffee*
```coffeescript
 Page = require './page'

module.exports = class SignInPage extends Page
  url: '/users/sign_in'
  timeouts: {
    open: 5000
    loading_screen: 20000
    warning: 2000
    error: 30000
  }

  # Members
  username: "#user_email"
  password: "#user_password"
  login: 'a=Log in'
  error_notification: '.error'

  validatePage: ->
    @browser
      .waitForVisible(@username)
      .isVisible(@password)

  toString: -> 'SignInPage'

  # Services
  loginAs: (user) ->
    console.log chalk.yellow("action: login")
    console.log chalk.cyan("email: #{user.email}")
    console.log chalk.magenta("password: #{user.password}")
    @open()
      .waitForVisible(@username, @timeouts.open)
      .setValue(@username, user.email)
      .setValue(@password, user.password)
      .click(@login)
      .then(@self)

  errorState: ->
    try
      @browser.waitForVisible(@error_notification, @timeouts.error)
      return true
    catch e
      return false
```



In our tests, we navigate through our pages using a combination of action & validation:
```coffeescript
it "logs in", ->
    page = new SignInPage(browser)
    yield expect(page.validate("SignInPage")).to.eventually.be.ok
    user = {email: "valid_email", password: "valid_password"}
    yield page.loginAs(user)
    page = new FirstApplicationPage(browser)
    yield expect(page.validate("FirstApplicationPage")).to.eventually.be.ok
```

*Every time* we switch pages, we validate that the page we switched to is actually the one we say it is in the test. explaining in english:
 - Without the validations, your test says "okay, go to Page A, then do A.X(), then we will be at Page B, and then do B.Y(), then we will be at Page C, etc..."
 - With validations, your test says "okay, go to this url, now verify that this url is Page A; now do A.X(), and this should take us to Page B; now verify that we are on Page B, and now do B.Y(), and this should take us to Page C; now verify we are now on Page C, etc..."


Of course, the validation language could be better, but for now this works.

For completeness, here's an example of a failed login:
```coffeescript
it "shows an error for invalid logins", ->
    page = new SignInPage(browser)
    yield expect(page.validate("SignInPage")).to.eventually.be.ok
    user = {email: "valid_email", password: "invalid_password"}
    yield page.loginAs(user)
    expect(page.errorState()).to.be.true
```

**Comment by christian-bromann** [comment]
WebdriverIO v4 now perfectly supports page objects. Check out [the docs](https://github.com/webdriverio/webdriverio/blob/master/docs/guide/testrunner/pageobjects.md) and our [example suite](https://github.com/webdriverio/webdriverio/tree/master/examples/pageobject) for more information.

**Comment by thibaut-sticky** [comment]
I migrate to the Java word to write my tests since almost one year now but I can only congrats you about the work you did. Page object is really a good thing.

**Comment by christian-bromann** [comment]
Well now you can migrate back to Webdriverio :-P
