### ISSUE TITLE
Unable to use Custom Service 

### ISSUE THREAD

**Issue by finelord** [webdriverio/webdriverio#3561]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.4.17
 - **Mode:** Standalone
 - **Node.js version:** 8.9.4
 - **NPM version:** 6.4.0
 - **Browser name and version:** Chrome 72
 - **Platform name and version:** Windows 10 / macOS 10.14
 - **Additional wdio packages used (if applicable):** 
``` json
  "dependencies": {
    "@wdio/cli": "5.4.17",
    "webdriverio": "5.4.17"
  },
  "devDependencies": {
    "@wdio/dot-reporter": "5.4.15",
    "@wdio/jasmine-framework": "5.4.14",
    "@wdio/local-runner": "5.4.17",
    "@wdio/selenium-standalone-service": "5.4.14",
    "@wdio/spec-reporter": "5.4.15",
    "@wdio/sync": "5.4.14"
  }
```

**Config of WebdriverIO**
``` js
const CustomService = require('./custom-service');

exports.config = {
    runner: 'local',
    specs: [
        './specs/*.spec.js'
    ],
    maxInstances: 10,
    capabilities: [{
        maxInstances: 5,
        browserName: 'chrome'
    }],
    logLevel: 'info',
    deprecationWarnings: true,
    bail: 0,
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    // this line causes the issue
    services: ['selenium-standalone', [CustomService]],
    // following old-style service declaration doesn't work as well
    // services: ['selenium-standalone', CustomService],
    framework: 'jasmine',
    reporters: ['dot','spec'],
    jasmineNodeOpts: {
        defaultTimeoutInterval: 60000,
        expectationResultHandler: function(passed, assertion) {
        }
    }
}
```

**Describe the bug**
Trying to use custom service from the same repo (`services: ['selenium-standalone', [CustomService]]`) causes `ERROR wdio-local-runner:utils: TypeError: name.toLowerCase is not a function`. 

Old-style custom service service usage (`services: ['selenium-standalone', CustomService]`) causes another `ERROR wdio-runner: Error: Type check for option "services" failed: the "services" options needs to be a list of strings and/or arrays`

**To Reproduce**

- `npm i webdriverio @wdio/cli`
- `wdio` then setup very basic local, jasmine, selenium-standalone config
- create simpliest spec
- copypaste custom service as described in docs here [Custom Services](https://webdriver.io/docs/customservices.html)
- add it to the `wdio.conf.js`
- try to run test

See example here: https://github.com/finelord/wdio-custom-service
- first commit is a working example without custom service
- 2nd and 3rd commits are broken by custom service usage (old and new way respectively)
- 4th one just to lock versions of packages

**Expected behavior**
Custom service should not be rejected by the framework

**Log**
https://gist.github.com/finelord/f4424f95e3b6e7006dee327612f6adbf

**Additional context**
Seems there's a conflict between config validator vs service initializer

**Comment by WillBrock** [comment]
@finelord The custom service should be exported without being initialized. I'll update the docs to reflect this.

**Comment by finelord** [comment]
thanks for helping with this but mentioned change didn't really resolve the issue, stdout errors disappeared but the service itself still doesn't work - silently. Just committed the change to the repo + placed the service itself on top of the config file to avoid any import/export issue.

https://github.com/finelord/wdio-custom-service

Am I missing anything else here?

**Comment by WillBrock** [comment]
I see. I'm looking into this a little bit more. It looks like you can use ```before``` and ```after``` methods instead right now.

**Comment by christian-bromann** [comment]
Looking into it now.
