### ISSUE TITLE
Not able to use V5 with Jasmine

### ISSUE THREAD

**Issue by tritethunder** [webdriverio/webdriverio#3562]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [5.4.17]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [8.10.0]
 - **Yarn version:** [1.6.0]
 - **Platform name and version:** [MacOS Mojave]
 - **Additional wdio packages used (if applicable):** ["@wdio/cli": "^5.4.17",
    "@wdio/dot-reporter": "^5.4.15",
    "@wdio/jasmine-framework": "^5.4.14",
    "@wdio/local-runner": "^5.4.17",
    "@wdio/runner": "^5.4.17",
    "@wdio/sync": "^5.4.14"]

**Config of WebdriverIO**
https://gist.github.com/tritethunder/c2ea1a5bf7077494bce1685d125acfd4#file-wdio-conf-js

**Describe the bug**
`TypeError: jasmineEnv.configure is not a function
    at JasmineAdapter.run (/Users/anonymous/app-repo/klarna-app/clients/node_modules/@wdio/jasmine-framework/build/index.js:69:16)
    at Object.adapterFactory.run (/Users/anonymous/app-repo/klarna-app/clients/node_modules/@wdio/jasmine-framework/build/index.js:251:32)
    at Runner.run (/Users/anonymous/app-repo/klarna-app/clients/node_modules/@wdio/runner/build/index.js:161:50)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)``

**Log**
https://gist.github.com/tritethunder/c2ea1a5bf7077494bce1685d125acfd4#file-output-logs

**Comment by WillBrock** [comment]
@tritethunder I'm not able to reproduce the error you're receiving. Can you together a simple repo that I can checkout?

Thanks

**Comment by BorisOsipov** [comment]
@tritethunder please make sure you didn't add `jasmine: 2.x` in dependencies. Wdio uses `jasmine: 3.x`, but looks like you install 2.x.

**Comment by tritethunder** [comment]
@BorisOsipov I am using 3.X in dependencies @WillBrock I will try to upload some small repo. Could you guys point me to some working examples where V5 used with jasmine 3.X

**Comment by BorisOsipov** [comment]
@tritethunder https://github.com/BorisOsipov/wdio-v5-jasmine

**Comment by christian-bromann** [comment]
if `"jasmine": "^3.2.0"` is defined in the package.json you will download `"jasmine": "^3.3.0"` automatically via NPM

**Comment by tritethunder** [comment]
@christian-bromann Somehow it's not downloading 3.3.0 for me as I am using yarn in a massive monorepo and there may be other packages that require 3.2.0. isn't this useful to bump the version instead of having the wrong dependency at first place? IMHO we shouldn't rely on NPM to fix this issue by downloading the latest version.

**Comment by BorisOsipov** [comment]
@tritethunder would you mind making a PR? I think it will resolve your issue :)

**Comment by tritethunder** [comment]
@christian-bromann Thanks for accepting the PR. Bumping version solved the issue 👍
