### ISSUE TITLE
Can't set up dev environment due to geckodriver error

### ISSUE THREAD

**Issue by tendonstrength** [webdriverio/webdriverio#3568]
I'm trying to set up my dev environment but when I try to run `npm run setup` (npm v6.4.1 & node v8.15.0) I get an error like:

```
npm ERR! path /dev/webdriverio/packages/wdio-applitools-service/node_modules/geckodriver/bin/geckodriver
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/dev/webdriverio/packages/wdio-applitools-service/node_modules/geckodriver/bin/geckodriver'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

```

This is happening both on Mac and a linux docker image. Has anybody seen this recently?

**Comment by mgrybyk** [comment]
@tendonstrength hello, yes. This is because defect in geckodriver.
Workaround is to switch to previous version. https://github.com/webdriverio/webdriverio/pull/3565/files

https://github.com/vladikoff/node-geckodriver/issues/59

**Comment by tendonstrength** [comment]
@mgrybyk Working. Thanks! 🎉
