### ISSUE TITLE
Getting errors while loading chrome extensions

### ISSUE THREAD

**Issue by udattuh** [webdriverio/webdriverio#3569]
Hi,

I am not able to load chrome extension using webdirverio configuration. Could you please help how to load chrome extensions when webdriverio is launching chrome browser through test runner.

capabilities: [
    {
      maxInstances: 1,
      browserName: 'chrome',
      version : '69.0.3497.100',
      pageLoadStrategy: 'normal',
      'goog:chromeOptions': {
        args: [
          '--disable-infobars',
          '--start-maximized',
          '--load-extension=path to extensions'
        ].filter(Boolean),
      },
    },
  ],

But the following is error is displayed when I execute the code.

![image](https://user-images.githubusercontent.com/26872238/52918994-61c22300-32f5-11e9-81b4-f7f5ab1ec063.png)

Could you please help me in resolving this issue.

Thanks,
Hemalatha Udattu

**Comment by mgrybyk** [comment]
@udattuh most likely you can't load packed extensions (or there is some switch to load packed extensions).
Extract you extension first, provide path to folder with extension, it should contain mainfest.json file.

**Comment by mgrybyk** [comment]
lets close this one
