### ISSUE TITLE
base64 extension is printed to log along with capabilities 

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#3570]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.4.17
 - **logLevel:** info

**Config of WebdriverIO**
```
const fs = require('fs')
const extension = fs.readFileSync('/full-path-to-extension-crx/ext.crx')
const base64 = Buffer.from(extension).toString('base64');

exports.config = {
  capabilities: [{
    browserName: 'chrome',
    'goog:chromeOptions': {
      extensions: [base64],
    }
  }]
}
```

**Describe the bug**
base64 file is printed to log

**To Reproduce**
run any test with config provided

**Expected behavior**
instead of posting base64 file to log just print something like: extensions: [ base64str, base64str ]

**Log**
capabilities are logged along with base64 file

**Additional context**
download extension from https://chrome-extension-downloader.com/

**Comment by christian-bromann** [comment]
This issue is not reproducible anymore. The logs automatically shorten the output:

```
2020-04-17T13:17:32.777Z INFO webdriver: [POST] http://localhost:4444/session
2020-04-17T13:17:32.778Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
     firstMatch: [ {} ] },
  desiredCapabilities:
   { browserName: 'chrome',
     'goog:chromeOptions': { extensions: [Array] } } }
```
