### ISSUE TITLE
Missing type definitions for `@wdio/reporter` package

### ISSUE THREAD

**Issue by AnnikaNissen** [webdriverio/webdriverio#3572]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [5.4.17
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Additional wdio packages used (if applicable):** @wdio/reporter

**Describe the bug**
When trying to compile a custom reporter class from TypeScript to JS, the TS compiler complains about missing type definitions for the @wdio/reporter.

My code:
```
import WDIOReporter from '@wdio/reporter';

export default class CustomReporter extends WDIOReporter {
   constructor (options) {
       options = Object.assign(options, { stdout: true });
       super(options);
   }
};
```

The compiler error: 
```
error TS7016: Could not find a declaration file for module '@wdio/reporter'. './node_modules/@wdio/reporter/build/index.js' implicitly has an 'any' type.
 Try `npm install @types/wdio__reporter` if it exists or add a new declaration (.d.ts) file containing `declare module '@wdio/reporter';`
``` 

**Expected behavior**
There should be type definitions available for the `@wdio/reporter` package, so that the compiler passes and the development gets easier because of proper code completion.

**Comment by dziraf** [comment]
I personally got it compile by using `require` instead of `import`:
```
// tslint:disable-next-line:no-var-requires
const WDIOReporter = require("@wdio/reporter").default;
```
However, it would be nice to have type definitions.

**Comment by mgrybyk** [comment]
@lamkovod thank you for dealing with it
