### ISSUE TITLE
Type definitions for webdriverio package missed a Promise<> as a return type for a lot of functions

### ISSUE THREAD

**Issue by CrispusDH** [webdriverio/webdriverio#3574]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**
`webdriverio.d.ts` and `webdriver.d.ts` don't have `Promise<>` at all as a return type. But I have two points:
1) All commands return `Promise<someValue>` as we [can see here](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriver/src/command.js#L80). So, for example `.click()` by `webdriverio.d.ts` is `click(): undefined;`. But if you don't use `wdio/sync` library you should definitely resolve promise (for example `await someElement.click()`. And for sure return type should be `Promise<void>` instead of `undefined`. And it is true for each function that use `webdriver` command inside implementation 
2) Some function as `browser.pause()` returns `Promise` in the implementation:
```
export default function pause (milliseconds = 1000) {
    return new Promise((resolve) => setTimeout(resolve, milliseconds))
}
```
and return type here should be Promise<void> instead of `undefined;` as I see now in `webdriverio.d.ts`

I'd like to report
- [ ] Unclear documentation
- [x] A typo
- [ ] Missing documentation
- [ ] Other

**Description of the improvement / report**
I see that definitions for all commands are generated inside `webdriverio-generate-typings.js` and `webdriverio-generate-typings.js` files. So, it would be nice if someone figure out how to fix it. If I will have a clue how to do it I will write a comment that I can create a PR. By now it could grab someone who know how to deal with it.

**Comment by CrispusDH** [comment]
Am I right that I can add `@return` type in a functions docs and type generation will grab it? For example for `.click()` in the `packages/webdriverio/src/commands/element/click.js` file I can add to:
```
...
 *
 * @alias element.click
 * @uses protocol/element, protocol/elementIdClick
 * @type action
 *
 */
```
this one:
```
 *
 * @alias element.click
*  @return {Promise<void>}
 * @uses protocol/element, protocol/elementIdClick
 * @type action
 *
 */
```
If it is true I can go though all commands and add correct return type

**Comment by christian-bromann** [comment]
@CrispusDH I think the problem is that the return value changes depending on the fact how you run WDIO (with or without @wdio/sync). I am not sure what would be the best solution here.

**Comment by CrispusDH** [comment]
> @CrispusDH I think the problem is that the return value changes depending on the fact how you run WDIO (with or without @wdio/sync). I am not sure what would be the best solution here.

Return type does not change. If your using `@wdio/sync` it just handle instead of you. If you run without it you have to resolve Promise by yourself. But return type the same. Do you agree with it?

**Comment by BorisOsipov** [comment]
>But return type the same. Do you agree with it?

`Promise<string>` and `string` are not the same...

I think there is nothing to change in current typings generation. For v4 we have the same "official" typings - without Promises.

As solution may propose to create an additional package with generated typings for async version. If someone wants to use `async` version he will be able to install such typings.

**Comment by christian-bromann** [comment]
> I think that return types in type definition should not rely on some `magic` mechanism that `@wdio/sync` library do.

I agree on that.

Can we have it in a way that if you use async you need to set
```js
"types": ["node", "webdriverio"]
```
and if using @wdio/sync you would need to put
```js
"types": ["node", "webdriverio/sync"]
```
or like that

**Comment by mgrybyk** [comment]
I can take a look at this if you want

**Comment by mgrybyk** [comment]
there is cool feature in typeScript called mapped types https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html

we can do something like this
```
type ElementPromised = {
    [K in keyof Element]: (...args: any[]) => Promise<Element[K]>
}
```

it will wrap every member of Element with Promise.

**Comment by CrispusDH** [comment]
@mgrybyk should I create PR with added `@return`, as I wrote before? I could base it from your branch. Or it will be not helpful for you?

**Comment by mgrybyk** [comment]
Let me think, at the first glance I don't think it is needed. However in case I'd that I let you know :)

**Comment by mgrybyk** [comment]
lets proceed conversation in PR
