### ISSUE TITLE
logOutput doesn't work

### ISSUE THREAD

**Issue by Gilad-WT** [webdriverio/webdriverio#3580]
**Environment (please complete the following information):**

* **WebdriverIO version:** 5.2.8
* **Mode:** Standalone
* **Node.js version:** 10.14.2
* **NPM version:** 6.4.1
* **Platform name and version:** Windows 10

**Config of WebdriverIO**
wdio.remote({ 
        host: 'localhost', 
        logOutput: "./",
        port: 4444,
        logLevel : "info",
        capabilities:{ 
            browserName: 'chrome',
        }
    });

**Describe the bug**
No matter what I pass into logOutput the logs are always printed to the console and not to a file. I tried passing in a path to a file ("./logs/log.txt") a path to a dir ("./logs") and a stream (fs.createWriteStream("./log.txt", {flags:'a'}) and none of them worked. I even tried using outputDir but that didn't work either.

**To Reproduce**
The easiest way is to just run this with with nothing listing on port 4444
```
let browser = wdio.remote({ 
        host: 'localhost', 
        logOutput: "./",
        port: 4444,
        logLevel : "info",
        capabilities:{ 
            browserName: 'chrome',
        }
    });
```
It will print out to the console:
2019-02-20T09:12:08.244Z INFO webdriver: [POST] http://0.0.0.0:4444/wd/hub/session
2019-02-20T09:12:08.247Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { browserName: 'chrome' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'chrome' } }
2019-02-20T09:12:09.264Z WARN webdriver: Request failed due to Error: connect ECONNREFUSED 0.0.0.0:4444
2019-02-20T09:12:09.265Z INFO webdriver: Retrying 1/2
2019-02-20T09:12:09.266Z INFO webdriver: [POST] http://0.0.0.0:4444/wd/hub/session
2019-02-20T09:12:09.267Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { browserName: 'chrome' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'chrome' } }
2019-02-20T09:12:10.272Z WARN webdriver: Request failed due to Error: connect ECONNREFUSED 0.0.0.0:4444
2019-02-20T09:12:10.273Z INFO webdriver: Retrying 2/2
2019-02-20T09:12:10.275Z INFO webdriver: [POST] http://0.0.0.0:4444/wd/hub/session
2019-02-20T09:12:10.283Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { browserName: 'chrome' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'chrome' } }

**Expected behavior**
The logs should be printed to the file and not to the console

**Comment by Gilad-WT** [comment]
@christian-bromann I saw you said this is an old v4 option. What replaces it?

**Comment by christian-bromann** [comment]
> What replaces it?

https://webdriver.io/docs/options.html#outputdir

**Comment by Gilad-WT** [comment]
@christian-bromann I tried it but it doesn't work. The log still gets printed to the console

**Comment by christian-bromann** [comment]
> The log still gets printed to the console

`outputDir` is a wdio option, so you need to use the testrunner. If you don't wish logs in your output, set the logLevel to `silent`.

**Comment by Gilad-WT** [comment]
@christian-bromann I can't use the testrunner and even when the logs are set to "silent" I still get error print outs to the console. Is there a way to get the "info" level logs to log to a file or do I have to implement it?

**Comment by christian-bromann** [comment]
> Is there a way to get the "info" level logs to log to a file or do I have to implement it?

This would be a new feature. Any help is appreciated.
