### ISSUE TITLE
Set user-agent for IE

### ISSUE THREAD

**Issue by ywangii** [webdriverio/webdriverio#3588]
Is there a way to set the `user-agent` for IE to be out-dated?

We are trying to use this way to test a warning feature when the browser is deprecated.

**Comment by christian-bromann** [comment]
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
