### ISSUE TITLE
Shadow DOM + IE11

### ISSUE THREAD

**Issue by vogloblinsky** [webdriverio/webdriverio#3592]
**Environment:**
 - **WebdriverIO version:** 5.6
 - **Mode:** WDIO
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.15.1
 - **NPM version:** 6.4.1
 - **Browser name and version:** IE11
 - **Platform name and version:** Windows 10

**Config of WebdriverIO**
https://github.com/vogloblinsky/webdriverio-stencil

**Describe the bug**
The usage of shadow$ works fine in a browser that supports SD, but for IE11, i got an error.
The web component is generated with Stencil.

**To Reproduce**

https://github.com/vogloblinsky/webdriverio-stencil

**Expected behavior**

**Log**
https://travis-ci.org/vogloblinsky/webdriverio-stencil/builds/496525281

**Comment by christian-bromann** [comment]
Can you provide some logs?

**Comment by jrobinson01** [comment]
https://travis-ci.org/vogloblinsky/webdriverio-stencil/jobs/496525282#L743
@christian-bromann IE11 does not support arrow functions, yet we're sending it one. I assume this is babel converting it for us. Can we annotate it such that babel ignores it and sends a normal function?

**Comment by christian-bromann** [comment]
mhm .. good catch! I wonder if it is actually Babel doing this 🤔 afaik it doesn't intentionally convert functions to arrow functions.

**Comment by christian-bromann** [comment]
This is fixed and released

**Comment by vogloblinsky** [comment]
Cool guys, thanks for the quick response. 👏

**Comment by jrobinson01** [comment]
I haven’t tried IE yet. Can you verify that it’s working now?

**Comment by vogloblinsky** [comment]
It works : https://travis-ci.org/vogloblinsky/webdriverio-stencil/builds/497396261
