### ISSUE TITLE
COMMAND, DATA, RESULT are not colored

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#3593]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.6.0

**Describe the bug**
COMMAND, DATA, RESULT are not colored

**To Reproduce**
`browser.url("/")`

**Expected behavior**
color COMMAND, DATA, RESULT or remove unused code

**Log**
[0-0] 2019-02-21T23:08:09.675Z INFO webdriver: COMMAND navigateTo("...")

**Additional context**

this is happening because loglevel-plugin-prefix appends data to the first message so that 'COMMAND' will be '%t %l %n: COMMAND'. As a result condition like  `log === 'COMMAND'` won't work.
```
const SERIALIZERS = [{...}, {
    matches: (log) => log === 'COMMAND',
    serialize: (log) => chalk.magenta(log)
}, {
    matches: (log) => log === 'DATA',
    serialize: (log) => chalk.yellow(log)
}, {
    matches: (log) => log === 'RESULT',
    serialize: (log) => chalk.cyan(log)
}]
```

---

to fix this we can change matcher or pass an empty string as a first variable to log function, ex
`log.info('COMMAND', commandCallStructure(command, args))`
will become
`log.info('', 'COMMAND', commandCallStructure(command, args))`

**Comment by mgrybyk** [comment]
Can do PR for this if one of proposed solutions is suitable:
- change matches to `matches: (log) => typeof log === string && log.endsWith('COMMAND')` and slightly change loglevel-plugin-prefix template to avoid changing colour for ':' that goes before COMMAND
- change printing of COMMAND, RESULT and DATA like this `log.info('', 'COMMAND', commandCallStructure(command, args))`

I'm not really amazed of any of them. First one is hacky, second one is not obvious :)

**Comment by christian-bromann** [comment]
Seems like the second one is more plausible if we add a comment as to why this is.

**Comment by christian-bromann** [comment]
@mgrybyk can this be closed now?

**Comment by mgrybyk** [comment]
I haven't fixed it yet ))

**Comment by mgrybyk** [comment]
If this is urgent let someone help me with it, or I can do it in next couple of days

**Comment by christian-bromann** [comment]
it's not urgent

**Comment by mgrybyk** [comment]
let's proceed conversation in the pull request
