### ISSUE TITLE
Strip down element object when passed into execute commands

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#3602]
## Problem

With WebdriverIO you can pass in an element into the execute command to use it in the script , e.g.
```js
const body = $('body')
console.log(browser.execute((el) => el.nodeName, body)) // returns "BODY"
```
Right now WebdriverIO would serialize the whole element object including all properties and methods. This is unnecessary and requires to much bandwidth.

## Solution

In execute and executeAsync, check if any of the parameters is an element object and strip the object down to elementId (jsonwp and w3c conform).

**Comment by baruchvlz** [comment]
Right now the callback returns the element id by default, no?

```javascript
const body = $('body')
console.log(browser.execute((el) => el, body))
// returns { 'element-6066-11e4-a52e-4f735466cecf': 'some-elem-123' }
```

Do you want this return to change to? (with all the other properties stripped)

```javascript
const body = $('body')
console.log(browser.execute((el) => el, body))
// returns { elementId: 'some-elem-123' }
```

**Comment by christian-bromann** [comment]
@baruchvlz interesting point, I am not sure if we need to because if people want to fetch an element with a execute function they can just do:

```js
const body = $(() => document.body)
```

However I wonder if it would make sense to automatically transform an element response from execute into an actual wdio element. This would be valuable if you want to pass in parameters into the function call as you showed above. This would be definitely better handled in a different PR.

**Comment by baruchvlz** [comment]
@christian-bromann This can be closed, eh?

**Comment by christian-bromann** [comment]
jup .. thanks!
