### ISSUE TITLE
Allow to overwrite native WebdriverIO commands

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#3604]
**Is your feature request related to a problem? Please describe.**

There are still a lot of cross driver issues around (e.g. saveElementScreenshot not being supported in Chrome but in FF) which teams try to solve by overwriting existing native API commands. It is a valid approach because it allows them to just remove the overwrites once cross driver support is ensured.

The argument against overwriting custom commands was that if a custom commands behaves slightly different than the native command it can confuse people that are not aware of the overwrite.

After getting more feedback on this issue I think being able to overwrite them makes more sense at the end because it allows people to build in hacky workarounds (e.g. using imagemagic to crop the screenshot) that would never be accepted as addition to the native commands as they add too much overhead or other reasons.

**Describe the solution you'd like**

Allow the ability to overwrite commands. No extra flag needed. The documentation should make it clear though that users should be careful with this due to above reasons.

**Comment by mgrybyk** [comment]
There is such ability in Cypress, they are adding original command to callback.
Something like this:
```
browser.addCommand('click', (origCommand, ...args) => {
  // do something here
  // call original command
  origCommand()
}, true)
```

**Comment by christian-bromann** [comment]
That's neat but it would be difficult to have it as first parameter as it would break all existing user tests .. I wouldn't mind adding it as last parameter though.

**Comment by CrispusDH** [comment]
I don't know why `webdriverio` package was implemented in a such way, but if `Browser` and `Element` were classes it will be so easy to extend it and create own wrappers.

**Comment by christian-bromann** [comment]
> but if `Browser` and `Element` were classes it will be so easy to extend it and create own wrappers.

This would be a terrible thing to maintain and a lot of duplicated code though 😉. WebdriverIO generates it's interface based on json and js files. You can always build your own Wrapper around WebdriverIO. A great example for that is [web2driver](https://github.com/projectxyzio/web2driver#readme).

**Comment by mgrybyk** [comment]
Hey,
I have started working on this one.
My idea is to add `overwriteCommand` in addition to `addCommand`.

I'm doing this to:
- reduce complexity 
- overwrite commands explicitly 
- do not introduce breaking changes
- do not introduce possible limitations or unexpected behavior with arguments handling. I want original command to be first argument to avoid possible errors, but this will introduce braking changes in case we want to extend `addCommand`.

**Example**
```
// change waitUntil behavior to return false on timeout instead of throwing an Exception
browser.overwriteCommand('waitUntil', async function (origCmd, condition, timeout, timeoutMsg, interval) {
    const waitUntil = origCmd
    try {
        return waitUntil(condition, timeout, timeoutMsg, interval)
    } catch (errIgnored) {
        return false
    }
})

// usage
browser.waitUntil(() => false) // returns false after timeout
```

**Implementation details**
I want to make instance object properties of function type to be configurable, so that they can be deleted from instance. https://github.com/webdriverio/webdriverio/blob/28e69cb4dbc4764870f2827c93f4290826ae634a/packages/webdriver/src/monad.js#L43

We are still protected against accidental commands redefinitions like browser.pause = 123, but it would be possible to `delete browser.pause`.

**Comment by CrispusDH** [comment]
@mgrybyk could you add example how it would look for async mode. What happens now if you try to addCommand with existing command's name?

I think would be helpful to add some error message if user will try to add existing command via `browser.addCommand()`, something like "For overriding existing command use browser.ovverideCommand( ) method". 

If regarding on technical reason would be clearer/easier implement overriding feature thought new method I'm ok with it.

**Comment by mgrybyk** [comment]
What is the decision on this? Shall I proceed with implementation?

**Comment by christian-bromann** [comment]
@mgrybyk let's move forward with the suggestion you made. I like it!

**Comment by mgrybyk** [comment]
Let's proceed discussion here https://github.com/webdriverio/webdriverio/pull/4049
