### ISSUE TITLE
setValue doesn't work on Safari and Firefox

### ISSUE THREAD

**Issue by anxious-confidence** [webdriverio/webdriverio#3605]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.6.1
 - **Mode:** Mocha
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.15
 - **NPM version:** Not sure
 - **Browser name and version:** Safari 12 and Firefox 65
 - **Platform name and version:** Mac 10.14 (for Safari) and Windows 7
 - **Additional wdio packages used (if applicable):** @wdio/sauce-service (not sure if this matters) and basically all of the default packages

**Config of WebdriverIO**
bdd for mochaOpts and sauceConnect is true (everything else is standard)

**Describe the bug**
the setValue command won't do anything in Safari and Firefox. It works in Chrome and Internet Explorer.

**To Reproduce**

```
const assert = require('assert');

describe('Bing Search', () => {
  it('Sets Value', () => {
    browser.url('https://www.bing.com/');
    $('#sb_form_q').setValue('WebdriverIO');
    $('#sb_form_go').click();
    assert($('#b_results').isDisplayed());
  });
});

```

**Expected behavior**
Expect it to type in something into an input tag (like a search bar)

**Additional context**

> Please use the correct markdown

**Comment by mgrybyk** [comment]
@anxious-confidence this code works fine in Firefox 66, geckodriver v0.24.0
```
    browser.url("http://adam.goucher.ca/parkcalc/")
    const i = $('input')
    i.setValue('foo')
    const val = i.getValue()
    console.log(val)
```

**Comment by anxious-confidence** [comment]
@mgrybyk Ah, unfortunately saucelabs does not have those versions. Hopefully they'll include them soon. I'll close this issue for now and then open up a new one if FF 66 and Safari 12.0.3 still doesn't work

**Comment by kishan-maheshkumar** [comment]
I am gettin same issue. May I know solution for this issue ?
