### ISSUE TITLE
Async Types: inside a Promise should be just return value instead of whole structure

### ISSUE THREAD

**Issue by CrispusDH** [webdriverio/webdriverio#3607]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**
Currently, I see inside a Promise whole method structure but should be only return. 
For example method `.click()` has such type 
```js
(method) click(): Promise<() => void>
```
but I expect (and such type is for `sync`, of course without `Promise`)
```js
(method) click(): Promise<void>
```

Stranger looks like methods with parameters, let's take a look at `.url()`, return value is
```js
(method) url(url?: string | undefined): Promise<(url?: string | undefined) => string>
```
but I expect
```js
(method) url(url?: string | undefined): Promise<string>
```

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [ ] Missing documentation
- [x] Other

**Comment by CrispusDH** [comment]
@mgrybyk I'm not sure why it happens. I think it might be here:
```js
type ArgumentTypes<T> = T extends (...args: infer U) => infer R ? U : never;
type WrapWithPromise<T> = (...args: ArgumentTypes<T>) => Promise<[T]>;
```

**Comment by mgrybyk** [comment]
I'll double check it on Monday

**Comment by mgrybyk** [comment]
fixing it

**Comment by CrispusDH** [comment]
could you link a PR? Want to see how you fix it :)

**Comment by mgrybyk** [comment]
@CrispusDH take a look.

**Comment by mgrybyk** [comment]
I'm think on adding some testing for these all these types, don't have much time right now, hopefully somewhere later we can have tests for typings.

**Comment by mgrybyk** [comment]
Please don't forget to generate:typings and publish webdriverio, webdriver, @wdio/sync !
