### ISSUE TITLE
setValue broken with safaridriver in --legacy mode

### ISSUE THREAD

**Issue by grazzini** [webdriverio/webdriverio#3611]
**Environment:**
 - **WebdriverIO version:** 5.6.2
 - **Mode:** Both
 - **Node.js version:** 10.15.0
 - **NPM version:** 6.7.0
 - **Browser name and version:** Safari 12
 - **Platform name and version:** OSX 10.13, 10.14

**Describe the bug**
When safaridriver is in `--legacy` mode, `setValue` breaks with the following error:

```
Request body does not contain required parameter 'value'.
```

This is particularly inconvenient because wdio doesn't currently work well with safaridriver's W3C mode, either. (See #2962.)

**To Reproduce**
```javascript
const { remote } = require('webdriverio');

(async () => {
    const browser = await remote({
        logLevel: 'warn',
        path: '/',
        capabilities: {
            browserName: 'safari'
        }
    });

    await browser.url('https://www.google.com');
    const elt = await browser.$('input[name="q"]');

    // See #2962: This fails with safaridriver in w3c mode
    //   Error: The command 'GET /session/:id/element/:nodeId/displayed' was not found.
    await elt.waitForDisplayed();

    // This fails with safaridriver in --legacy mode:
    //   Error: Request body does not contain required parameter 'value'.
    await elt.setValue("webdriver");

    await browser.deleteSession();
})().catch((e) => console.error(e));
```

**Expected behavior**
When safaridriver is running in `--legacy` mode, I expected webdriver to recognize that and use the jsonwp version of `setValue`. (Which would have the parameter as `value`, not `text`.)

Couple of other thoughts:

- As a workaround, being able to specify the protocol directly (with `--protocol=jsonwp` or something) would be handy.
- But if there's some other way to force it to use jsonwp in the meantime, that would be really helpful.

Thanks!

**Comment by christian-bromann** [comment]
Fixed in #3615
