### ISSUE TITLE
Using performActions in custom commands

### ISSUE THREAD

**Issue by cammanderson** [webdriverio/webdriverio#3613]
**Describe your question with as much detail as possible**
The standard commands use this.performActions(). Using addCommand('custom', function() {}, true) does not provide scope to the this.performAction (returning undefined).

Is it possible to issue actions via performActions() directly from a custom command? If so what is the correct way to do this?

Running WebdriverIO cli: 5.4.17 with Chrome.

Thanks,

**Comment by christian-bromann** [comment]
> Is it possible to issue actions via performActions() directly from a custom command? If so what is the correct way to do this?

[`performActions`](https://webdriver.io/docs/api/webdriver.html#performactions) is accessible only from the browser scope as it is a protocol command. So instead of `this.performActions` use `browser.performActions`.

**Comment by cammanderson** [comment]
Thanks for the response. When calling it though, I receive:
"TypeError: browser.performActions is not a function". Is there an alternative scope to call this function?

**Comment by christian-bromann** [comment]
> Is there an alternative scope to call this function?

It is probably because you are using Chrome which doesn't support this W3C command yet.

**Comment by arr0nax** [comment]
Hi! We are running in to almost exactly the same issue while trying to use performActions inside addCommand. Does anyone know if this should be supported yet?
