### ISSUE TITLE
Cannot install latest version due to Control Character in the package

### ISSUE THREAD

**Issue by xMutaGenx** [webdriverio/webdriverio#3620]
Noticed this morning as our Artifactory cannot pull from remote anymore:
```
[ERROR] (o.a.a.n.r.NpmRemoteRepoHandler:470) - Error while parsing the response of a remote npm JSON query on 'https://registry.npmjs.org/webdriverio': Illegal unquoted character ((CTRL-CHAR, code 0)): has to be escaped using backslash to be included in string value
```

**Comment by christian-bromann** [comment]
I don't think this is related to WebdriverIO.

**Comment by steerben** [comment]
I do think so that this might be related to webdriver io.
Same error message since today.

Download works when done directly from npm, but not via artifactory remote repo anymore.
Granted, artifactory might not handle the characters in a correct way.

Still the file retrieved at `https://registry.npmjs.org/webdriverio` seems to contain illegal unquoted characters since one of your latest releases, which might have been introduced when updating the meta data which gets merged with the structure provided by npm here

```
2019-02-26 10:16:15,414 [http-nio-8081-exec-16388] [ERROR] (o.a.a.n.r.NpmRemoteRepoHandler:440) - Error while parsing the response of a remote npm JSON query on 'https://registry.npmjs.org/webdriverio': Illegal unquoted character ((CTRL-CHAR, code 0)): has to be escaped using backslash to be included in string value
 at [Source: org.jfrog.storage.binstore.common.ReaderTrackingInputStream@2c7e373b; line: 1, column: 2100]
```

**Comment by christian-bromann** [comment]
> Download works when done directly from npm, but not via artifactory remote repo anymore.

I don't know how you have setup artifactory nor how it is connected to NPM to download the package. That being said, there is nothing I can do to investigate this. We also haven't changed anything in the package.json that could have caused this. Feel free to provide a PR with a fix.

**Comment by xMutaGenx** [comment]
@steerben in the meantime you can:
1. `npm login` to your artifactory
2.  `wget https://registry.npmjs.org/webdriverio/-/webdriverio-<version number here>.tgz`
3.  `npm publish webdriverio-<version number here>.tgz`

this will manually publish the package for you.

**Comment by christian-bromann** [comment]
> this will manually publish the package for you.

@xMutaGenx Why would you want to publish the package for a specific version? Can you please investigate what kind of file you receive and report back?

**Comment by xMutaGenx** [comment]
@christian-bromann We use specific versions for our nightly builds of the framework before we start using them in live, will do if I find the time, ta.
