### ISSUE TITLE
Execute function does not seem to work in Safari

### ISSUE THREAD

**Issue by anxious-confidence** [webdriverio/webdriverio#3623]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.6.2
 - **Mode:** Mocha
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.15
 - **NPM version:** Not sure
 - **Browser name and version:** Safari 12
 - **Platform name and version:** Mac 10.14
 - **Additional wdio packages used (if applicable):** Most up to date standard packages (using SauceLabs if that makes a difference)

**Describe the bug**
Execute function doesn't work in Safari

**To Reproduce**

`describe('Execute',function() {
  it('should inject javascript on the page', function() {
    const result = browser.execute(function(a, b, c, d) {
      // browser context - you may not access client or console
      return a + b + c + d
    }, 1, 2, 3, 4)
    // node.js context - client and console are available
    console.log(result) // outputs: 10
  });
});
`

**Expected behavior**
Expect it to not throw an error

Current error that's being thrown:
POST /session/XXXXXXXX-XXXX-XXXX-XXXX-XXXX1DB3A7D3/execute/sync
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
System info: host: 'itako48177.prod.miso', ip: 'fe80:0:0:0:d4:6f3:a668:6a46%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14', java.version: '9.0.4'
Driver info: driver.version: unknown

> Please use the correct markdown

**Comment by christian-bromann** [comment]
Will be fixed with #3615
