### ISSUE TITLE
Session shuts down immediately after launching app

### ISSUE THREAD

**Issue by lucialuzuriaga** [webdriverio/webdriverio#3626]
## The problem

I'm trying to test an Android app using WebdriverIO. I followed the guidelines of the Appium boilerplate project, and have been struggling ever since. At first I thought that my issues were related to ES6 (syntax error on imports, exports, declaring constants, etc.) but I realized that my test is simply failing even before that because the app closes immediately after being launched.
Appium logs say literally nothing about it asides from session deleted. 
Terminal doesn't show anything either. All I see is that the tests aren't being executed. The app simply opens and then the session shuts down.

I'm new to using WebdriverIO and Javascript for native mobile testing, but at this point I am out of ideas of what is wrong. 

## Environment

* Appium version (or git revision) that exhibits the issue: v1.10.0
* Desktop OS/version used to run Appium: Mac OSX 10.14.3 Mojave
* Node.js version (unless using Appium.app|exe): 10.15.1
* Mobile platform/version under test: Android
* Real device or emulator/simulator: emulator

## Link to Appium logs
https://gist.github.com/lucialuzuriaga/1cc912c97f6e8f60ff9a7a64dae86f09

## Code 
package.json
```
{
  "name": "wikipedia-android",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "./node_modules/.bin/wdio ./wdio.android.conf.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.3.4",
    "@babel/preset-env": "^7.3.4",
    "@babel/register": "^7.0.0",
    "@wdio/cli": "^5.6.2",
    "@wdio/jasmine-framework": "^5.6.0",
    "@wdio/local-runner": "^5.6.2",
    "@wdio/sync": "^5.6.0"
  },
  "dependencies": {
    "babel-cli": "^6.26.0",
    "babel-register": "^6.26.0"
  }
}
```

wdio.android.conf.js

```
const { join } = require('path');
const { config } = require('./wdio.conf');

// ============
// Specs
// ============
config.specs = [
    './test/specs/**/*.js',
];

// ============
// Capabilities
// ============
// For all capabilities please check
// http://appium.io/docs/en/writing-running-appium/caps/#general-capabilities
config.capabilities = [
    {
        // The defaults you need to have in your config
        automationName: 'UiAutomator2',
        deviceName: 'emulator-554',
        platformName: 'Android',
        platformVersion: '7.0',
        orientation: 'PORTRAIT',
        app: join(process.cwd()+"/wikipedia-alpha-universal-debug.apk"),
        // Read the reset strategies very well, they differ per platform, see
        // http://appium.io/docs/en/writing-running-appium/other/reset-strategies/
        noReset: true,
        newCommandTimeout: 400,
    },
];

// ====================
// Appium Configuration
// ====================
// Default port for Appium
config.port = 4723;

exports.config = config;
```

wikipedia.js (tried with this code from another guide, as it is the same app that I'm testing, but I also tried with literally the same code from the Appium boilerplate )
```
describe('Search Wikipedia Functionality', function () {
  it('can find search results', function () {
    var searchSelector = `~Search Wikipedia`;
    client.waitForVisible(searchSelector, 30000);
    client
      .element(searchSelector)
      .click();

    var insertTextSelector = 'android=new UiSelector().resourceId("org.wikipedia.alpha:id/search_src_text")';
    client.waitForVisible(insertTextSelector);
    client
      .element(insertTextSelector)
      .keys('BrowserStack')
      .pause(5000);

    var allProductsName = client.elements(`android.widget.TextView`).value;
    assert(allProductsName.length > 0);
  });
});
```

Thank you in advance.

**Comment by mgrybyk** [comment]
First of all second guide is for v4, it won't work in v5.

Then, can you please provide webdriverio logs and the test you are running, please.

Here are some more questions
- do you have tests in './test/specs/**/*.js', ?
- do you have sync: true in wdio.conf.js ?
- is something happening on emulator? Is app being installed or at least something?

**Comment by christian-bromann** [comment]
Can you provide wdio logs?

**Comment by lucialuzuriaga** [comment]
Thank you for replying. 

Here are the wdio logs (I'm assuming that you're asking for the console output):
`Stdout:
2019-02-26T15:59:53.004Z INFO wdio-cli:Launcher: Run onPrepare hook
2019-02-26T15:59:53.008Z INFO wdio-local-runner: Start worker 0-0 with arg: ./wdio.android.conf.js
[0-0] 2019-02-26T15:59:53.153Z DEBUG wdio-config: @wdio/sync found, running tests synchronous
[0-0] 2019-02-26T15:59:53.343Z INFO wdio-local-runner: Run worker command: run
[0-0] 2019-02-26T15:59:53.495Z DEBUG wdio-local-runner:utils: init remote session
[0-0] 2019-02-26T15:59:53.545Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session
[0-0] 2019-02-26T15:59:53.545Z INFO webdriver: DATA { capabilities:
   { alwaysMatch:
      { automationName: 'UiAutomator2',
        deviceName: 'emulator-554',
        platformName: 'Android',
        platformVersion: '7.0',
        orientation: 'PORTRAIT',
        app:
         '/Users/themermaid/git_repos/wikipedia-android/wikipedia-alpha-universal-debug.apk',
        noReset: true,
        newCommandTimeout: 400 },
     firstMatch: [ {} ] },
  desiredCapabilities:
   { automationName: 'UiAutomator2',
     deviceName: 'emulator-554',
     platformName: 'Android',
     platformVersion: '7.0',
     orientation: 'PORTRAIT',
     app:
      '/Users/themermaid/git_repos/wikipedia-android/wikipedia-alpha-universal-debug.apk',
     noReset: true,
     newCommandTimeout: 400 } }
[0-0] 2019-02-26T16:00:05.115Z INFO webdriver: COMMAND deleteSession()
[0-0] 2019-02-26T16:00:05.116Z INFO webdriver: [DELETE] http://127.0.0.1:4723/wd/hub/session/4f9cee22-ddc9-4a51-92ae-5cae4d55f065
2019-02-26T16:00:05.572Z DEBUG wdio-local-runner: Runner 0-0 finished with exit code 1
2019-02-26T16:00:05.574Z INFO wdio-cli:Launcher: Run onComplete hook

Test Suites:	 0 passed, 1 failed, 1 total (100% completed)
Time:		 🕘  12.60s

npm ERR! Test failed.  See above for more details.`

Regarding the questions:

* do you have tests in './test/specs/**/*.js', ?
My tests are in the specs folder (no sub folders), so this seems to be correct.
* do you have sync: true in wdio.conf.js ?
I don't have this in my wdio.conf.js nor on the android.conf.js. This is what I got in wdio.conf.js:

`exports.config = {
    //
    // ====================
    // Runner Configuration
    // ====================
    //
    // WebdriverIO allows it to run your tests in arbitrary locations (e.g. locally or
    // on a remote machine).
    runner: 'local',

    //
    // ==================
    // Specify Test Files
    // ==================
    //
    specs: [
        './test/specs/**/*.js'
    ],
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    //
    // ============
    // Capabilities
    // ============
    //
    maxInstances: 10,
    capabilities: [{
        maxInstances: 5,
        browserName: 'firefox'
    }],
    //
    // ===================
    // Test Configurations
    // ===================
    // Define all options that are relevant for the WebdriverIO instance here
    //
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    logLevel: 'trace',
    //
    // If you only want to run your tests until a specific amount of tests have failed use
    // bail (default is 0 - don't bail, run all tests).
    bail: 0,
    //
    // Set a base URL in order to shorten url command calls. If your `url` parameter starts
    // with `/`, the base url gets prepended, not including the path portion of your baseUrl.
    // If your `url` parameter starts without a scheme or `/` (like `some/path`), the base url
    // gets prepended directly.
    baseUrl: 'http://localhost',
    //
    // Default timeout for all waitFor* commands.
    waitforTimeout: 10000,
    //
    // Default timeout in milliseconds for request
    // if Selenium Grid doesn't send response
    connectionRetryTimeout: 90000,
    //
    // Default request retries count
    connectionRetryCount: 3,
    //
    // Test runner services
    // Services take over a specific job you don't want to take care of. They enhance
    // your test setup with almost no effort. Unlike plugins, they don't add new
    // commands. Instead, they hook themselves up into the test process.
    //services: [],//
    // Framework you want to run your specs with.
    // The following are supported: Mocha, Jasmine, and Cucumber
    // see also: https://webdriver.io/docs/frameworks.html
    //
    // Make sure you have the wdio adapter package for the specific framework installed
    // before running any tests.
    framework: 'jasmine',
    //
    // Test reporter for stdout.
    // The only one supported by default is 'dot'
    // see also: https://webdriver.io/docs/dot-reporter.html
    // reporters: ['dot'],
    //
    // Options to be passed to Jasmine.
    jasmineNodeOpts: {
        //
        // Jasmine default timeout
        defaultTimeoutInterval: 60000,
        //
        // The Jasmine framework allows interception of each assertion in order to log the state of the application
        // or website depending on the result. For example, it is pretty handy to take a screenshot every time
        // an assertion fails.
        expectationResultHandler: function(passed, assertion) {
            // do something
        }
    },
    //
    // =====
    // Hooks
    // =====
    beforeSession: (config, capabilities, specs) => {
        require('@babel/register');
    },
}
`
* is something happening on emulator? Is app being installed or at least something?
The app launches and opens. As soon as the app opens, the test stops running.

**Comment by mgrybyk** [comment]
So, can you please provide with simple test that is failing for you?

**Comment by christian-bromann** [comment]
@lucialuzuriaga maybe add a reporter like spec reporter to get an idea about an error. With no reporter you will see no errors.

**Comment by lucialuzuriaga** [comment]
It seems that you were right and indeed the code was not working due to being compatible with v4 only. I modified the code to match a page object pattern and it is not being taken. Thank you all for the quick replies.
