### ISSUE TITLE
npm ERR! {"_id":"webdriverio",

### ISSUE THREAD

**Issue by mustaphakd** [webdriverio/webdriverio#3627]
**platform** => node:10.12.0-alpine

**package.json dependencies entry contains** => "webdriverio": "4.6.2",

executing the command: **npm install -ddd** throws the following exception:

npm ERR! registry error parsing json
npm ERR! Unexpected token  in JSON at position 2098
npm ERR! {"_id":"webdriverio","_rev":"232-f255b719a1d4f7b32f9d5cca29b24efe","name":"webdriverio","description":"Next-gen WebDriver test automation framework for Node.js","dist-tags":{"latest":"5.6.2", ....

**Comment by christian-bromann** [comment]
> **package.json dependencies entry contains** => "webdriverio": "4.6.2",

I don't know what you referring to but we don't have that as a dependency also not sure what you did to get this error but I was able to successfully install WebdriverIO.

**Comment by mustaphakd** [comment]
don't know  why you closed it; 
webdriverio npm package is a dependency that gets installed when npm install is invoked.
however, I get the error mentioned above.

I am only getting this error on Alpine Linux and not on the windows 10 platform.
do you happen to a token inside your registration json file that's unrecognizable under Linux ?

**Comment by christian-bromann** [comment]
Could be related to #3620
