### ISSUE TITLE
How to listen to custom events?

### ISSUE THREAD

**Issue by vbyjsue** [webdriverio/webdriverio#3631]
Upgrading from v4 to 5.6.0 I have a problem with custom events. In v4 I could do:
`process.send('custom:event', data)`
and then in custom reporter listen to it like:

```
this.on('custom:event', function(data) {
    addToReportOutput(data);
}
```
In V5 it seems all events must have origin "reporter" or "worker" to be processed, but even so I cant get custom events to be passed to reporter.
Can't find anything in in docs on how to handle custom events in V5?

- WebdriverIO version:5.6.0
- Mode:Testrunner sync
 - Node.js version: 8.9.0
 - NPM version: 5.5.1
 - Browser name and version:Chrome 71
 - Platform name and version: macOS Mojave 10.14.2 
 - Additional wdio packages used : @wdio/spec reporter

**Additional context**

**Comment by christian-bromann** [comment]
@vbyjsue reporter live in v5 in the same process than the worker so you can just register a global eventlistener to transfer events to the custom reporter. Does this make sense?

**Comment by vbyjsue** [comment]
I'm sorry but I'm  not able to listen to anything apart from wdio events.
Not in reporter constructor with this.on('custom:event').
Not in wdio beforeHook with browser.on('custom:event').
I'm launching wdio programmatically but that should not matter I guess.
Perhaps you can give som example on how to proceed?

**Comment by vbyjsue** [comment]
This is what I found this far: 
Childprocess is forked in "local-runner/worker" which then listens to all child events and re-send them with 
``` 
this.emit('message', Object.assign(payload, {
      cid
    }));
```
I guess that means you could register a listener, but would have to listen to "message" and then filter out event? 
But how would I register a listener on the parent process?
The only instance I have access to is `const wdio = new Launcher(opts.configFile, opts);`

If I use process.emit() instead of process.send() I can listen to the event and process it, but then I get no cid and can't determine from which child the data was sent.

Again my goal here is to add custom steps to reporters wich in v4 was fairly easy.
Sorry for my lacking experience in node events.

**Comment by vbyjsue** [comment]
Never figured out how to really solve it but ended up with this solution:
Send message in tests with `process.emit('my:event' data)`
In reporter, set up listener in constructor and set current test uid in beforeTest hook:
```
constructor() {
  this.logs = {};
  this.currentTest = '';  
  process.on('my:event', data => {
      this.logs[this.currentTest].push(data.message);
    });
  }
  onTestStart(test) {
    this.currentTest = test.uid;
    this.logs[test.uid] = [];
  }
```
At finish just loop through logs and output to reporter.
![image](https://user-images.githubusercontent.com/3033505/53575228-6d251200-3b71-11e9-8eb1-7154a4e569c0.png)

**Comment by StephenEsser** [comment]
@christian-bromann 

Is the solution provided by @vbyjsue what you were recommending? We're looking into ways to send custom events to our custom reporter and so far `process.on` and `process.send` have been the only successful solutions. 

Are there any alternatives that are supported and recommended to use for creating custom reporter events?
