### ISSUE TITLE
browser.reload() failing to reload the session when this was called after a failed test

### ISSUE THREAD

**Issue by nareshnayini** [webdriverio/webdriverio#3634]
I am encountering issues when trying to use `reload` after every test when preceding test fails.

**Environment:**
 - **WebdriverIO version:** 4.13.2
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 10.5.0
 - **NPM version:** 6.1.0
 - **Browser name and version:** Chrome 69
 - **Platform name and version:** macOS 10.13.5
 - **Additional wdio packages used (if applicable):** * wdio-jasmine-framework

**Describe the bug**
When a test fails, browser.reload() function inside `afterTest` failing with the below mentioned error. So, browser session is not deleted and it's reloading with session session. 

**To Reproduce**
WDIO config:
afterTest: () => {
    browser.reload();
  },
  afterSession: async () => {
    await browser.end().pause(1000);
  },
  after: async () => {
    await browser.pause(1000);
  },

**Expected behavior**
It is expected that, upon reload() call, user will be logged out from application and application relaunches.

**Log**
Error in onReload hook: "Error: Don't end the session manually. This will be done automatically.
    at session("delete") - end.js:31:17
    at init() - reload.js:40:23
    at end() - reload.js:40:17
    at screenshot() - saveScreenshot.js:52:17
    at reload() - index.js:312:3"

I have looked into other tickets related to this issue but nowhere found the solution. Most of the tickets were closed saying they are inactive.

**Comment by christian-bromann** [comment]
This issue was moved to webdriverio-boneyard/v4#20

**Comment by christian-bromann** [comment]
We don't actively fix bugs for v4 anymore but we are happy to release new versions with fixes for bugs.
