### ISSUE TITLE
Server logs errors while running with appium 1.9.1 on browserstack

### ISSUE THREAD

**Issue by tritethunder** [webdriverio/webdriverio#3637]
**Describe your question with as much detail as possible**

 I am trying to use v5.6.2 with brwoserstack serverice app-autoamte to run my appium test and they only support appium version 1.7~ 1.9.1 but while running test I am getting this error 

`[debug] [MJSONWP] Encountered internal error running command: Error: Appium server must have relaxed security flag set in order to be able to get server logs`

 is there any way to disable these sever logs call or this is a known issue. While running same test with v4 with appium 1.9.1 not have any issue. 

**Logs snippet**

https://gist.github.com/tritethunder/08a4c63598abba633ff61a3636a7367e

**Environment (please complete the following information):**
 - **WebdriverIO version:**  5.6.2
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 8.10.0
 - **Yarn version:** 1.6.0
 - **Browser name and version:** Appium 1.9.0
 - **Platform name and version:**  Linux 
 - **Additional wdio packages used (if applicable):**  "@wdio/cli": "^5.6.2",
    "@wdio/dot-reporter": "^5.6.0",
    "@wdio/jasmine-framework": "^5.6.0",
    "@wdio/junit-reporter": "^5.6.0",
    "@wdio/local-runner": "^5.6.2",
    "@wdio/spec-reporter": "^5.6.0",
    "@wdio/sync": "^5.6.0"

**Comment by christian-bromann** [comment]
With #3467 we added the ability to disable this. It will be released in the next version (maybe today or tomorrow).
