### ISSUE TITLE
[Possible BUG] MJSONWP protocol requires type and ms" and you sent {"script": 1000}

### ISSUE THREAD

**Issue by raquelgs** [webdriverio/webdriverio#3641]
Hello!

I'm using Codeceptjs with webdriverio and browserstack (automate) and I’m facing an issue related with MJSONWP endpoint to fetch the timeouts and makes my test suite to crash.

My setup is:
> **webdriverio 5.6.3
> codeceptjs 2.0.4
> appium_version: 1.9.1 (Tried with 1.6.5, 1.7.1, etc...)**

```Error: Parameters were incorrect. We wanted "MJSONWP protocol requires type and ms" and you sent {"script":1000}```

What I found interesting is that Inside my config file (codeceptjs config file) I do not specify any timeout option.

```
exports.config = {
  tests: './test_codecept/*.js',
  output: './test_codecept/output',
  helpers: {
    WebDriver: {
      host: 'hub.browserstack.com',
      path: '/wd/hub',
      url: 'http://WEBSITE:8080/renderer',
      user: 'xx',
      key: 'xx',
      browser: 'iphone',
      desiredCapabilities: {
        'os_version' : '11',
        'device' : 'iPhone 8',
        'real_mobile' : 'true',
        'browserstack.local' : 'true',
        'browserstack.debug' : 'true',
        'browserstack.networkLogs' : 'true',
        'browserstack.appium_version' : '1.9.1',
        'browserstack.user' : 'xx',
        'browserstack.key' : 'xx'
      }
    }
  }
}
```

After failing a few times, I tried to specify a timeout option inside the helper like mention in the [w3c WebDriver spec](https://www.w3.org/TR/webdriver/#set-timeouts)
and didn't work neither, appeared that I was sending an empty object to the `sessionId/timeouts`.

```
timeouts: {
  type: 'script',
  ms: 1000
}
```

After that I tried to setup the timeouts like the error message propose: "type" and "ms", didn't work neither.

```
timeouts: {
  type: 'script',
  ms: 1000
}
```

I'm not completly sure that this issue is entirely related with webdriverio, I just jumped into here since I was debugging the MJSONWP.

Thanks for reading

**Comment by christian-bromann** [comment]
@raquelgs this is not a WebdriverIO error and it should be reported in the codeceptjs project. Thanks!

**Comment by raquelgs** [comment]
Thanks for responding so fast!
