### ISSUE TITLE
webdriverio: refetch doesn't work for shadow DOM elements in Safari

### ISSUE THREAD

**Issue by jrobinson01** [webdriverio/webdriverio#3645]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.6.2
 - **Mode:** testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 8.9.1
 - **NPM version:** 5.5.1
 - **Browser name and version:** Safari 12.0.3
 - **Platform name and version:** OSX 10.13
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
After deleting an element and creating a new one, the refetchElement logic fails to find the new element.

**To Reproduce**
An example test in jasmine:
```javascript
it('shadow$ works with refetch', () => {
  const blogApp = browser.$('blog-app');
  const header = blogApp.shadow$('header');
  expect(header.$('a-link').getAttribute('href')).toEqual('/');
  // remove the main element and recreate
  browser.execute(() => {
    const oldEl = document.querySelector('blog-app');
    oldEl.parentElement.removeChild(oldEl);// removes the main element
    const newEl = document.createElement('blog-app');// create a new one, which contains header
    document.body.appendChild(newEl);
  });
  // header should be a stale reference at this point and invoke refetch
  expect(header.$('a-link').getAttribute('href')).toEqual('/');
});
```

**Expected behavior**
Safari webdriver should return a 'stale element reference' error response which wdio uses to invoke the refetch logic.

**Log**
https://gist.github.com/jrobinson01/7093fa9e53009c8bf20d6a0a30f5788a

**Additional context**

> Please use the correct markdown

**Comment by abjerstedt** [comment]
@jrobinson01 Can you do me a favor get me some data on this?  
Set your logLevel to 'info' and paste the response the driver gives you for the stale element into this issue. I'll update the matcher to handle this case.

**Comment by jrobinson01** [comment]
Well that's what's weird (I think)... the logs don't ever mention a stale element. check out the logs here: https://gist.github.com/jrobinson01/7093fa9e53009c8bf20d6a0a30f5788a#file-wdio-0-0-log-L50-L62

The dom looks like this:

<img width="445" alt="screen shot 2019-03-01 at 1 26 47 pm" src="https://user-images.githubusercontent.com/1584296/53658032-b9318e80-3c25-11e9-9c0e-d1d3029c6b4c.png">

The next command after the execute removes the `<blog-app>` element is trying to find the `<a-link>` element and failing to find anything, using the `findElementFromElement` command on line 59. I think in Chrome, that is where you'd expect a stale element reference, but it never happens. With Safari, it just keeps repeating that same command over and over until it times out. I'll get the logs from Chrome so we can compare.

**Comment by abjerstedt** [comment]
Yeah - if it doesn't distinguish between a missing element and a dead element, theres nothing i can do to refetch it.

**Comment by jrobinson01** [comment]
Is it a opening a whole new can of worms to try to refetch when an element is not found?

**Comment by abjerstedt** [comment]
@jrobinson01 So, i was playing with safari yesterday, and I think this is a symptom of a bigger issue tbh. Element not found was throwing an exception vs generating the "element not found" object.

**Comment by jrobinson01** [comment]
where did you see that it was throwing?

**Comment by abjerstedt** [comment]
Ignore what i said... i got confused with edge :-/.

**Comment by abjerstedt** [comment]
@jrobinson01 Do you mind retesting with 5.7.1? I'm doubting that this fixed it, but it'd be nice to see.

**Comment by jrobinson01** [comment]
@abjerstedt yeah I'll give it a shot this afternoon.

**Comment by jrobinson01** [comment]
@abjerstedt no change in 5.7.1

**Comment by mgrybyk** [comment]
@jrobinson01 working on fix for this issue.

**Comment by mgrybyk** [comment]
Should be fixed with https://github.com/webdriverio/webdriverio/pull/3701
