### ISSUE TITLE
Add "name" and "reason" to update request to Browserstack API

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#3648]
**Is your feature request related to a problem? Please describe.**
It seems that Browserstack now supports modifying the name of the session as well as the reason for the failure in [their API](https://www.browserstack.com/automate/rest-api).

**Describe the solution you'd like**
Let's enhance the `@wdio/browserstack-service` to update the session name as well as give the reason for a test failure.

**Comment by OriTheMan** [comment]
Hi,
I can give a try to handle it (its my first time here).
1. there is way to get the error in the service? (for "reason" field)
2. who decide what is the session name? the user or automatically

**Comment by christian-bromann** [comment]
> 1. there is way to get the error in the service? (for "reason" field)

The afterTest hook should have information about test name and error, please check the sauce service where we already store the test name
