### ISSUE TITLE
Webpack the WebdriverIO for Node

### ISSUE THREAD

**Issue by Antonius-S** [webdriverio/webdriverio#3652]
I'd like to webpack webdriverio to use in my Node project.
Commit https://github.com/webdriverio/webdriverio/commit/dfc73b9acceac1ef59e366e106879bc904919257 fixed bundling excess stuff for web but it broke bundling for Node. Currently webpack can't bundle `./node` module so test project using the packed file fails with following message:
```
C:\Node.js\_test-webdriver\packed.js:127
 */var i,o,r,n=a(148),s=a(9).extname,c=/^\s*([^;\s]*)(?:;|\s|$)/,p=/^text\//i;fu
nction u(e){if(!e||"string"!=typeof e)return!1;var t=c.exec(e),a=t&&n[t[1].toLow
erCase()];return a&&a.charset?a.charset:!(!t||!p.test(t[1]))&&"UTF-8"}t.charset=
u,t.charsets={lookup:u},t.contentType=function(e){if(!e||"string"!=typeof e)retu
rn!1;var a=-1===e.indexOf("/")?t.lookup(e):e;if(!a)return!1;if(-1===a.indexOf("c
harset")){var i=t.charset(a);i&&(a+="; charset="+i.toLowerCase())}return a},t.ex
tension=function(e){if(!e||"string"!=typeof e)return!1;var a=c.exec(e),i=a&&t.ex
tensions[a[1].toLowerCase()];if(!i||!i.length)return!1;return i[0]},t.extensions
=Object.create(null),t.lookup=function(e){if(!e||"string"!=typeof e)return!1;var
 a=s("x."+e).toLowerCase().substr(1);if(!a)return!1;return t.types[a]||!1},t.typ
es=Object.create(null),i=t.extensions,o=t.types,r=["nginx","apache",void 0,"iana
"],Object.keys(n).forEach(function(e){var t=n[e],a=t.extensions;if(a&&a.length){
i[e]=

Error: Cannot find module './node'
    at a (C:\Node.js\_test-webdriver\packed.js:127:135113)
    at Object.<anonymous> (C:\Node.js\_test-webdriver\packed.js:
1:34183)
    at a (C:\Node.js\_test-webdriver\packed.js:1:172)
    at Object.<anonymous> (C:\Node.js\_test-webdriver\packed.js:
127:133159)
    at a (C:\Node.js\_test-webdriver\packed.js:1:172)
    at Object.<anonymous> (C:\Node.js\_test-webdriver\packed.js:
127:132863)
    at a (C:\Node.js\_test-webdriver\packed.js:1:172)
    at C:\Node.js\_test-webdriver\packed.js:1:964
    at Object.<anonymous> (C:\Node.js\_test-webdriver\packed.js:
1:975)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
```
If there's no means to fix the issue in the code, how can I pack a working bundle?

**Comment by christian-bromann** [comment]
> I'd like to webpack webdriverio to use in my Node project.

You don't need to bundle webdriverio for your node project. Just install it and require it, no webpack necessary.

**Comment by Antonius-S** [comment]
@christian-bromann  why not? I like one file much much more than 894 files scattered in 173 folders. And except the above mentioned change things seem working (I reverted change by that commit and got Webpack generate working file).

**Comment by christian-bromann** [comment]
In NodeJS it doesn’t matter if your files are scattered or in one file .. in fact I never seen someone using webpack when running the code with NodeJS anyway

**Comment by Antonius-S** [comment]
It does matter anywhere. Tons of files make many processes slower. I came from native binary world so thousands of bundled files make me very sad. Webpack seems very promising and it works in fact except for this change

**Comment by christian-bromann** [comment]
> Tons of files make many processes slower.

if you run node it runs in a single process no matter if you run one js file or throusands, it will always require the same CPU. In fact Node is optimize to have large dependency trees across many files.

**Comment by Antonius-S** [comment]
I'm not talking about run time. I mean creating and especially extracting tarballs and so on. Anyway, if you don't wish to support packing, it's up to you. Just in case someone comes to this page with the same issue: solution is to change
```
   mode = require(nodeMode).default
```
to
```
   mode = require('./node').default
```
