### ISSUE TITLE
Execute function still not working in v5.6.4 despite merge in of JSONWP thing

### ISSUE THREAD

**Issue by anxious-confidence** [webdriverio/webdriverio#3655]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.6.4
 - **Mode:** [Standalone mode or WDIO Testrunner] Mocha
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async] sync
 - **Node.js version:** [e.g. 8.11.2] 10.15
 - **NPM version:** [e.g. 5.8.0] Not sure
 - **Browser name and version:** [e.g. Chrome 68] Safari 12
 - **Platform name and version:** [e.g. Windows 10] Mac 10.14
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

All standard stuff, but using SauceLabs. all v5.6.4

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
browser.execute() function does not work in Safari despite the merging in of the JSONWP thing. I just want to bring this to your attention in case you did not know. Feel free to close this if this was already known.

**To Reproduce**
https://webdriver.io/docs/api/browser/execute.html

^Example from the API docs
**Expected behavior**
Should not throw error

> Please use the correct markdown

**Comment by christian-bromann** [comment]
This can't be fixed in WebdriverIO as it is a bug with SauceLabs. I reported it to the cloud team here at sauce and they will look into it.
