### ISSUE TITLE
Any plans to implement full page screenshot to replace wdio-screenshot

### ISSUE THREAD

**Issue by sinapsist** [webdriverio/webdriverio#3668]
I am just wonder if there is any plan to build something similar to https://github.com/zinserjan/wdio-screenshot as build-in function, because it seems that it is not longer maintained by owner and it does not support v5 (and has no clear plan to support: https://github.com/zinserjan/wdio-screenshot/issues/89)?

I tried to use it with v5, but from what I understand I cannot inject and use plugin anymore, because when I try to do this one
    plugins: {
        'wdio-screenshot': {}
    },
and then
browser.saveDocumentScreenshot('test.jpg');
I am getting this error:
TypeError: browser.saveDocumentScreenshot is not a function

Would be nice to get a function to build a full page screenshot, that can be used for visual regression and manual verification

As alternative I am considering to stay on V4 and use this tool from the same author 
https://github.com/zinserjan/wdio-visual-regression-service

**Comment by christian-bromann** [comment]
@sinapsist we do not have any plans to make this build-in. Plugins like this (`wdio-screenshot`) also won't work anymore in v5. At this point I would recommend to fork the project and build a new service.
