### ISSUE TITLE
yield statement instead of nested callback

### ISSUE THREAD

**Issue by bitcity** [webdriverio/webdriverio#367]
Writing tests is quite painless with `Webdriverio`, thanks to the well documented API. Although after a while, I feel my code could be more succinct & readable if there was something like [Yiewd](https://github.com/jlipps/yiewd) for `WebdriverIO`, It gets rid of nested callbacks with `yield` statements. The library is quite small and on the surface it looks like it might be straightforward to port it. Any thoughts?

Here's an example of its usage with `wd` : https://github.com/admc/wd#yiewd

P.S. I'm sure the developers are well aware of this but I couldn't find any reference in the issues section, hence bringing it up.

**Comment by christian-bromann** [comment]
Since each command returns with a unique promise in `v3` now, it won't be much effort to make yielding work with WebdriverIO. We should add something in our docs though to make people clear about how to use it properly.

**Comment by christian-bromann** [comment]
Got following example working:

```js
var run = require('monocle-js').run;
var webdriverio = require('./index');
var client = webdriverio.remote({
    desiredCapabilities: {
        browserName: 'phantomjs'
    }
});

run(function*() {
    yield client.init().url('http://localhost:8080/test/site/www/');
    var title = yield client.getTitle();
    console.log(title);
    yield client.end();
});
```

The runner basically just need to overwrite the `it` as well as the hook methods.

**Comment by christian-bromann** [comment]
Ok so this will be available in `v3`. All child processes will run in harmony mode automatically. People have three different methods to handle asynchronicity:

__the good old callback way:__
```js
describe('my feature', function() {
    it('will do something', function(done) {
        browser
             .url('http://google.com')
             .getTitle().then(function(title) {
                 console.log(title);
              })
              .call(done);
    });
});
```

__using promises:__
```js
describe('my feature', function() {
    it('will do something', function() {
        return browser
             .url('http://google.com')
             .getTitle().then(function(title) {
                 console.log(title);
              });
    });
});
```

__the new fancy generator way:__
```js
describe('my feature', function() {
    it('will do something', function* () {
        yield browser.url('http://google.com');
        var title = yield browser.getTitle()
        console.log(title);
    });
});
```

**Comment by bitcity** [comment]
:+1: for generators ! Would love to try it out for my next project. Thank you for the good work.

**Comment by steveharman** [comment]
+1 for generators Christian :-)

**Comment by talarari** [comment]
are generators supported in v4? or is the fiber implementation used instead?

**Comment by christian-bromann** [comment]
We use fibers in v4
