### ISSUE TITLE
Passing user credentials as options prevents connections to Sauce Labs

### ISSUE THREAD

**Issue by DylanLacey** [webdriverio/webdriverio#3671]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 5.6.2]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync]
 - **Node.js version:** [e.g. 8.9.0]
 - **NPM version:** [e.g. 6.8.0]
 - **Browser name and version:** [N/A]
 - **Platform name and version:** [N/A]
 - **Additional wdio packages used (if applicable):** [@wdio/cli]

**Config of WebdriverIO**
https://gist.github.com/DylanLacey/c39c0e561ef5507306e6b6966c1561ce

**Describe the bug**
Using the WDIO Runner, passing user credentials for Sauce Labs as options causes the following error:

`[0-0] 2019-03-04T01:46:31.507Z WARN webdriver: Request failed due to socket hang up`
**To Reproduce**

Run a Sauce Labs targeted test with credentials passed via the command line:

`./node_modules/.bin/wdio --user fake --key 'mad-hacks-123' wdio.conf.js`

**Expected behavior**
Tests run as they would if credentials were passed via config file.

**Additional context**
I figured the server detection code was mis-firing when providing credentials via cmd options, so I tried including fake credentials in the config file, knowing they'd be over-written.  Inspecting the options object showed they _were_, but the connection to Sauce still wasn't established correctly.

I also tried specifying the host and port via cmd options, trying to force a good config.  This didn't work.

**Comment by christian-bromann** [comment]
Fixed in #3705
