### ISSUE TITLE
Worker Error: connect ECONNEFUSED 127.0.0.1 WDIO 5.6.4

### ISSUE THREAD

**Issue by alessandronoceraspx** [webdriverio/webdriverio#3673]
Hi all,
I've a very strange issue with run wdio appium test on remote machine (by changing the IP address). The console give me this output:

```
Worker Error:
Error: connect ECONNREFUSED 127.0.0.1:4723
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
Test Suites:     0 passed, 1 failed, 1 total (100% completed)
Time:            🕖  1.87s
```
Below my settings:

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.6.4
 - **Mode:** Standalone
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.15.0
 - **NPM version:** 6.7.0
 - **Browser name and version:** n/a
 - **Platform name and version:** macOs last version
 - **Additional wdio packages used (if applicable):** wdio-appium-service 0.2.3

**Config of WebdriverIO**
```
[ { platform: 'android',
    service:
     { services: 'appium',
       protocol: 'http',
       host: '192.168.34.253',
       port: 4723 },
    smartphone:
     { deviceName: 'Pixel 2',
       platformVersion: '9',
       platformName: 'Android',
       automationName: 'UIAutomator2',
       app: 'myApp.apk',
       autoGrantPermissions: true },
    defaultMaxInstance: 1,
    type: 'realDevice' } ]
```

**Describe the bug**
The worker go in error. Connection refuse.

**To Reproduce**
Use Appium not in localhost.

**Expected behavior**
Start the test session on remote device connected to another mac.

**Log**
```
2019-03-04T17:01:07.338Z DEBUG @wdio/config: @wdio/sync found, running tests synchronous
2019-03-04T17:01:08.968Z DEBUG @wdio/cli:run: Run suite with config wdio.conf.js and params { _: [ 'wdio.conf.js' ],
  spec: [ './dist/epic/epic-0/epic-0.js' ],
  '$0':'/Users/ale/Documents/TestingFactory/test-automation/node_modules/.bin/wdio' }
2019-03-04T17:01:09.086Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "appium"
2019-03-04T17:01:09.098Z INFO @wdio/cli:Launcher: Run onPrepare hook
2019-03-04T17:01:09.101Z INFO @wdio/local-runner: Start worker 0-0 with arg: wdio.conf.js,--spec,./dist/epic/epic-0/epic-0.js
2019-03-04T17:01:10.263Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
```

**Additional context**
With the last version of wdio 4 the remote session was completed correctly and I'm able to run test from mac to another mac (that have appium running). I don't know why because the 127.0.0.1 appear in wdio 5. 

My package.json config:
```
"devDependencies": {
    "@wdio/allure-reporter": "^5.6.3",
    "@wdio/cli": "^5.6.3",
    "@wdio/devtools-service": "^5.6.3",
    "@wdio/firefox-profile-service": "^5.6.0",
    "@wdio/jasmine-framework": "^5.6.3",
    "@wdio/junit-reporter": "^5.6.0",
    "@wdio/local-runner": "^5.6.3",
    "@wdio/sauce-service": "^5.6.3",
    "@wdio/selenium-standalone-service": "^5.6.3",
    "@wdio/spec-reporter": "^5.6.0",
    "@wdio/sync": "^5.6.3",
    "babel-cli": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "eslint": "^5.14.1",
    "eslint-config-airbnb-base": "^13.1.0",
    "eslint-plugin-import": "^2.16.0",
    "eslint-plugin-jasmine": "^2.10.1",
    "firefox-profile": "^1.1.0",
    "husky": "^1.3.1",
    "rimraf": "^2.6.3",
    "wdio-appium-service": "^0.2.3",
    "wdio-chromedriver-service": "^5.0.1",
    "wdio-iedriver-service": "^0.1.0",
    "webdriverio": "5.6.4"
  },
```

Start appium normally on remote machine with:
```
bash appium
[Appium] Welcome to Appium v1.11.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
```
Tried also with:
`bash appium -a 192.168.34.253 -p 4723`
and with
`bash appium -a 127.0.0.1 -p 4723`

Tried also to start on different port, but anything. Issue persist.

Thank you very much guys, I hope to fix this issue.
Alex

**Comment by wswebcreation** [comment]
Hi @alessandronoceraspx 

First of all the `wdio-appium-service` is not working with V5, so that's the first issue.
Secondly you need to set the `hostname` to the ip you want it to connect to and the `port` to your matching port.
Last but not least you need Appium to run on the machine where the em/simulator/real device is connected to.

You get the `127.0.0.1` error because there is no `hostname` provided so it will default to the localhost

**Comment by alessandronoceraspx** [comment]
> Hi @alessandronoceraspx
> 
> First of all the `wdio-appium-service` is not working with V5, so that's the first issue.
> Secondly you need to set the `hostname` to the ip you want it to connect to and the `port` to your matching port.
> Last but not least you need Appium to run on the machine where the em/simulator/real device is connected to.
> 
> You get the `127.0.0.1` error because there is no `hostname` provided so it will default to the localhost

Hi @wswebcreation,
thank you for the response!I'm confused because in my conf. the host, port and protocol are correctly set:
```
{ services: 'appium',
       protocol: 'http',
       host: '192.168.34.253',
       port: 4723 },
```
How can I use Appium service in wdio 5? Locally all works fine, only when I ran in remote mode the error appear. There is a new pkg that I must be to use? Can you help me? 

Is something missing from me?

Many thanks!!

**Comment by wswebcreation** [comment]
Hi @alessandronoceraspx 

It's `hostname`, not `host`, see the config file [here](https://webdriver.io/docs/configurationfile.html).

> How can I use Appium service in wdio 5? Locally all works fine, only when I ran in remote mode the error appear. There is a new pkg that I must be to use? Can you help me?

You officially can't use the `appium-service` with V5, it's not supported. If it works then you're lucky

**Comment by alessandronoceraspx** [comment]
> It's `hostname`, not `host`, see the config file [here](https://webdriver.io/docs/configurationfile.html).
>
Yes I saw now the changes on webdriverIO options page (for v5 API). For appium-service, I've removed the devDependeces from package.json as you told me. Thank you. Tomorrow I'll try this changes and I hope it will work. 
So Appium is now used only from @wdio/utils? 
I think that also this package are not support for v5?

- "wdio-chromedriver-service": "^5.0.1"
- "wdio-iedriver-service": "^0.1.0"

Have you info about this? Thank you for your support, it's really appreciated.

**Comment by wswebcreation** [comment]
Everything that starts with '@wdio/..' is maintained by the WDIO-team
All the 'wdio-..' are "not" maintained (anymore).

Regarding Appium, you now need to run it on the machine that connects to the em/simulator/real devices. 

If you have some more questions or need some guidance you can also check https://github.com/webdriverio/appium-boilerplate or check the Gitter channel

**Comment by alessandronoceraspx** [comment]
All works perfect. Remote run is possibile without any problems. I've ran all specs also from Jenkins pipeline and my DevOps is correctly ran all automation test on physical devices.
Thank you very much for all.

Have a nice day!

Alex

**Comment by wswebcreation** [comment]
@alessandronoceraspx 

You're welcome.

**Comment by raditotev** [comment]
I had very similar error for tests running on BrowserStack. It took me some time to realise where is the problem. I pass my BS credentials as environmental variables in the config file and I forgot to import them before running the tests.
Decided to put this here in case someone else has the same problem.
