### ISSUE TITLE
Using `^` for any wdio packages within any wdio sub-packages causes a dependency clash if the user uses a specific version of wdio packages.

### ISSUE THREAD

**Issue by nami-varthakavi** [webdriverio/webdriverio#3682]
As the title states, whenever we use a specific version of webdriver.io and it's sub-packages we expect to be stable. But whenever webdriver.io upgrades to newer versions, and also upgrade the versions in its dependent packages we run into this issue. 

To provide an example, 
Let's say our package .json has the following list of webdriver.io packages

```
        "@wdio/allure-reporter": "5.6.4",
        "@wdio/cli": "5.6.4",
        "@wdio/jasmine-framework": "5.6.4",
        "@wdio/local-runner": "5.6.4",
        "@wdio/logger": "5.6.4",
        "@wdio/selenium-standalone-service": "5.6.4",
        "@wdio/spec-reporter": "5.6.4",
        "@wdio/sync": "5.6.4",
        "webdriverio": "5.6.4"
```

All of the packages are at 5.6.4,c and we expect that version to be stable. We only need to upgrade to newer versions only if we requires any features/fixes provided by webdriver.io. But, If webdriver.io upgrades its versions to 5.7.0, the `@wdio/logger` we use is 5.6.4 but the dependency in `@wdio/config` uses 5.7.0 causing a version mismatch in the node-modules. 

The only solution for the above issue would be to not use `^` in your sub-packages for any webdriver.io packages or upgrade webdriver.io changes as major version instead of minor versions so that the user doesn't grab these breaking changes(Even though they may not be breaking changes but it actually breaks the users who use specific versions of webdriver.io).

**Comment by christian-bromann** [comment]
> The only solution for the above issue would be to not use `^` in your sub-packages

These package version are updated by lerna and the actual solution would be to have `^` in your package.json. Every time we update a package it requires other packages to be updated as well, you can't just update a single package as this will cause problems.
