### ISSUE TITLE
Wait not working in multiremote tests

### ISSUE THREAD

**Issue by kevinmcdonnell** [webdriverio/webdriverio#3683]
**Environment (please complete the following information):**
 - **WebdriverIO version:** v5.6.3
 - **Mode:** wdio
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v11.8.0
 - **NPM version:** 6.5.0
 - **Browser name and version:** chrome 71
 - **Platform name and version:** macos
 - **Additional wdio packages used (if applicable):** @wdio/spec reporter, @wdio/selenium-standalone service

**Config of WebdriverIO**
An example of how you configured WebdriverIO config
```
    capabilities: {
        managerOne: {
            capabilities: {
                browserName: 'chrome'
            }
        },
        employeeOne: {
            capabilities: {
                browserName: 'chrome'
            }
        }
    },
```
**Describe the bug**
`waitForExist` and `waitUntil` do not behave as expected in multiremote

**To Reproduce**
```

describe('describe', function () {
    after(function () {
        // ManagerOne sends newsfeed post
        console.log(new Date().getTime() / 1000);
    });

    it('it', function () {
        browser.url('https://google.com');

        console.log(new Date().getTime() / 1000);
        $('.foobar').waitForExist(10000);
    });
});

```

**Expected behavior**
The test should wait for 10 seconds before timing out. I observe that it times out immediated

**Log**
https://gist.github.com/kevinmcdonnell/708b5e018b7c6c2e564efdebcd083019
https://gist.github.com/kevinmcdonnell/ca2d85fc3ce276a1e1081a19fe2ed65b

**Additional context**

> Please use the correct markdown

**Comment by mgrybyk** [comment]
yeap, reproducible for me as well

**Comment by kevinmcdonnell** [comment]
any thoughts on a workaround? or a pointer on how I could try to fix this?

can I manually achieve the same by using `browser.newSession()` to create multiple browser sessions?

e.g.
```
one = browser.newSession(options);
two = browser.newSession(options);

one.url('htt]://google.com')
```

**Comment by mgrybyk** [comment]
@kevinmcdonnell I don't know right now how to fix it in framework. 
You can workaround it like this

```

        const waitForExist = (condition, timeout = 10000, interval = 750) => {
            const endTime = Date.now() + timeout

            let result = condition()
            // some magic is here. 
            // in multiremote functions return Array instead of result 
            // so $('foo').isExisting() returns [ true, true ] or  [ false, true ], etc...
            while (Date.now() < endTime && !(Array.isArray(result) ? !result.some(res => res !== true) : result)) {
                // console.log(endTime - Date.now())
                browser.pause(interval)
                result = condition()
            }
        }

        waitForExist(() => $('foo').isExisting(), 15000)
```

**Comment by mgrybyk** [comment]
you can even go further and pass managerOne or employeeOne instead of browser to waitForExist if you need to wait for something within particular browser instance.

Also, you may temporary introduce new command for it.

Sorry to say you won't be able to add custom command to element level because of https://github.com/webdriverio/webdriverio/issues/3445

**Comment by mgrybyk** [comment]
@kevinmcdonnell pass all parameters explicitly, including interval. Some default values are ignored in multiremote mode.
