### ISSUE TITLE
switchTab not working

### ISSUE THREAD

**Issue by tvnking** [webdriverio/webdriverio#3685]
I can't switch tab on iOS. my code:
    popupO365 = browser.windowHandles().value.filter((handle) => handle !== loginScreen)[0];
    browser.switchTab(popupO365)
p/s: WebdriverIOs version 4.14.3

**Comment by christian-bromann** [comment]
This issue was moved to webdriverio-boneyard/v4#26

**Comment by christian-bromann** [comment]
We don't fix issues in v4 anymore but we are happy to merge fixes that you can provide that prevents this bug from happening.
