### ISSUE TITLE
Cant run on Safari local browser

### ISSUE THREAD

**Issue by mirza-ae** [webdriverio/webdriverio#3686]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.3.5 and latest (5.7.0)
 - **Mode:** Standalone mode
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** latest
 - **NPM version:**  latest
 - **Browser name and version:** Safari 12
 - **Platform name and version:** Mac OSX  10.14
 - **Additional wdio packages used (if applicable):** @wdio/selenium-standalone service

**Config of WebdriverIO**
https://gist.github.com/mirza-ae/04ff5ca24d7d9a2cae3a09b108b29908

**Describe the bug**
Every time I attempt to run on an Safari local browser using the Selenium stand alone service, I get the following errors:
[safari #0-0] 1) navigating to contact-us page should allow user to navigating contact-us page
[safari #0-0] The command 'GET /session/7F688BA9-7F4F-4F89-B4A1-4C839A36A0F2/element/node-7C11BF90-559F-41D3-9419-881D8803648B/displayed' was not found.

**To Reproduce**
Clone https://github.com/amiya-pattnaik/webdriverIO-with-mochaBDD.
Replace the test/config/suite.mocha.conf.js file's contents with the code from https://gist.github.com/mirza-ae/04ff5ca24d7d9a2cae3a09b108b29908.
Execute the command, "npm install".
Execute the command, "npm test".

**Expected behavior**
The tests should run locally on the Safari browser.

**Log**
https://gist.github.com/mirza-ae/700dce82dd456a3fcdc058db56d0b1e1

**Comment by christian-bromann** [comment]
Apparently the logs show that the session was initiated, so Safari runs just fine. The actual issue you are facing is already logged and about to be fixed at #3601
