### ISSUE TITLE
function reusability

### ISSUE THREAD

**Issue by rostgoat** [webdriverio/webdriverio#3689]
**Describe your question with as much detail as possible**
I am transitioning from Selenium to WebdriverIO and I'm running into some difficulty regarding function reusability. Let me demonstrate with an example:

    <nav>
      <div><a>Clients</a></div>
      <div><a>Accounts</a></div>
      <div><a>Packages</a></div>
    </nav>

lets say I have a navigation bar with 3 links above. When I land on this page, I want to check if each link exists. My function may look something like this:

    class LoginPage extends Page {
    
      get clientsLink() { return $('//a[contains(., "Clients")]'); }
    
    
      isTabDisplayed() {
        if (this.clientsLink.isDisplayed()) {
          return true;
        } else {
          false
        }
      }
    }

this is fine except I would have to write 2 more getters for `Accounts` and `Packages` and so my class would look like this:

    class LoginPage extends Page {
    
      get clientsLink() { return $('//a[contains(., "Clients")]'); }
      get accountsLink() { return $('//a[contains(., "Accounts")]'); }
      get packagesLink() { return $('//a[contains(., "Packages")]'); }
    
      isClientTabDisplayed(tab) {
        if (this.clientsLink.isDisplayed()) {
          return true;
        } else {
          false
        }
      }
    
      isAccountsTabDisplayed(tab) {
        if (this.accountsLink.isDisplayed()) {
          return true;
        } else {
          false
        }
      }
    
      isPackagesTabDisplayed(tab) {
        if (this.packagesLink.isDisplayed()) {
          return true;
        } else {
          false
        }
      }
    }

at this point, my anxiety kicks in and I start to think of ways I can reuse the `isTabDisplayed` function where I can pass a string to the getter with my tab name, or something along the lines of that. 

Unfortunately, getters do not accept parameters and so far I have not found any resources on google that can help me to solve this issue (most common being Page Object Model which doesn't seem to address this problem)

Is my thought process out of line that I am striving for reusable code in UI testing or am I not googling for correct patterns?

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.3.5
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 8.10.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Chrome 72.0.3626.119 (Official Build) (64-bit) 
 - **Platform name and version:** 72.0.3626.119 (Official Build) (64-bit)
 - **Additional wdio packages used (if applicable):**"@wdio/selenium-standalone-service": "^5.2.2", "selenium-standalone": "^6.15.6"

**Comment by abjerstedt** [comment]
You are overloading the concept of a getter... a getter in essence is simply a function that doesn't require a param. Just put a plain old function in your test:
getLink (text) { return $(text) }

In the future please use our gitter for questions like this. This shouldn't be an issue.

**Comment by christian-bromann** [comment]
> I am transitioning from Selenium to WebdriverIO

❤️ it!
