### ISSUE TITLE
Port wdio-appium-service

### ISSUE THREAD

**Issue by abjerstedt** [webdriverio/webdriverio#3693]
**Describe the solution you'd like**

In order to better support our native app customers, we should absorb wdio-appium-service into the monorepo. This would allow these users to get started on webdriverio with less overhead.

**Comment by wswebcreation** [comment]
If we are going to do that, can we also make it a parallel solution, meaning that each Appium instance will get it's own port if multiple capabilities are provided?

**Comment by saikrishna321** [comment]
@wswebcreation  

>meaning that each Appium instance will get it's own port if multiple capabilities are provided

We wouldn't need that as appium server can handle multiple capabilities request in single session

**Comment by wswebcreation** [comment]
@saikrishna321 
Tnx, didn't knew that

**Comment by christian-bromann** [comment]
We merged that service, great work by @MortenGregersen
