### ISSUE TITLE
Conflict between the @wdio-sync and the webdriverio typings

### ISSUE THREAD

**Issue by erwinheitzman** [webdriverio/webdriverio#3694]
**Environment (please complete the following information):**
 - **WebdriverIO version: 5.7.1
 - **Mode: WDIO Testrunner
 - **If WDIO Testrunner, running sync/async: sync
 - **Node.js version: 10.15.0
 - **NPM version: 6.4.1 -> 6.8.0
 - **Browser name and version: Chrome 73
 - **Platform name and version: OSX 10.14
 - **Additional wdio packages used (if applicable): [@wdio/junit-reporter, @wdio/mocha-framework]

**Config of WebdriverIO**
```
// wdio.conf.ts
const { register } = require('ts-node');
register({ files: true });
module.exports = require("./config")
```

```
// config.ts
import { Config } from '@wdio/sync';

const config: Config = {
    runner: 'local',
    specs: [
        './test/specs/**/*.ts'
    ],
    exclude: [],
    maxInstances: 10,
    capabilities: [{
        maxInstances: 5,
        browserName: 'chrome'
    }],
    logLevel: 'warn',
    bail: 0,
    baseUrl: 'localhost:4200',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    services: ['chromedriver'],
    path: '/',
    port: 9515,
    // @ts-ignore
    chromeDriverArgs: ['--port=9515'],
    // @ts-ignore
    chromeDriverLogs: './',
    framework: 'mocha',
    reporters: [
        'dot',
        ['junit', {
            outputDir: './junit-output'
        }]
    ],
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000,
        compilers: [
            'tsconfig-paths/register'
        ]
    },
    before: function (capabilities, specs) {
        if (process.env.THROTTLE) {
            // @ts-ignore
            browser.setNetworkConditions({ latency: 1500, throughput: 0, offline: false });
        }
    },
    onComplete: function(exitCode, config, capabilities, results) {
        console.log('config is: ', config);
        console.log('capabilities are: ', capabilities);
        console.log('exitCode is: ', exitCode);
        console.log('results are: ', results);
    }
}

export { config }
```

```
// tsconfig.json
{
  "compilerOptions": {
    "target": "es2017",
    "baseUrl": ".",
    "paths": {
        "*": [ "./*" ],
        "src/*": ["./src/*"]
    },
    "types": ["node", "@wdio/mocha-framework", "@wdio/sync"],
    "lib": ["es2017", "dom"]
  },
  "include": [
      "./test/**/*.ts",
      "./src/**/*.ts"
  ]
}
```

**Describe the bug**
There's a conflict between the @wdio-sync and the webdriverio typings in the same namespace.

Example:
<img width="1022" alt="screenshot 2019-03-07 at 11 59 13" src="https://user-images.githubusercontent.com/15839059/53966008-97874a00-40f2-11e9-8950-469555e6baab.png">
<img width="673" alt="screenshot 2019-03-07 at 11 58 58" src="https://user-images.githubusercontent.com/15839059/53966009-97874a00-40f2-11e9-9b30-2fd2b53187c6.png">

**To Reproduce**

Create a typescript project and use the following:
```
browser.waitUntil(() => browser.getUrl().includes('some-value'));
```

Will result in error:
`test/specs/login/login.spec.ts(45,50): error TS2570: Property 'includes' does not exist on type 'Promise<string>'. Did you forget to use 'await'?`

**Expected behavior**
I expect the compiler not to error.

**Comment by erwinheitzman** [comment]
@mgrybyk would you mind to take a look at this?

**Comment by xlenz** [comment]
@erwinheitzman 
![image](https://user-images.githubusercontent.com/3816609/53970802-cd7cfc00-40fb-11e9-9e2f-dc51b577fedb.png)

**Comment by xlenz** [comment]
@erwinheitzman do you have imports of webdriverio somewhere in the code? 
If yes - remove them

**Comment by erwinheitzman** [comment]
@xlenz Oh damn, I completely forgot about a single import statement somewhere in the project. shit, I feel stupid now..
Thanks for pointing that out, been bashing my head against the wall with this one and this is one to note down to never forget again!

Will close the issue since the problem was me and not the code.

**Comment by mgrybyk** [comment]
No worries :)
