### ISSUE TITLE
blocker: isDisplayed doesn't work in Appium in 5.7.1

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#3699]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.7.1

**Config of WebdriverIO**
Using Appium 1.11.1

```
capabilities: [{
...
    "appium:app": __dirname + '/../../apps/MoPlay.apk',
    "appium:appPackage": 'com.addisongloballtd.moplay.adhoc',
    "appium:appActivity": 'com.moplay.MainActivity',
}]
```

**Describe the bug**
isDisplayed doesn't work, works fine in 5.7.0

**To Reproduce**
`$('~BUTTON').waitForDisplayed()`

**Expected behavior**
isDisplayed, waitForDisplayed should work

**Log**
```
Error: waitUntil condition failed with the following reason: Cannot read property 'toLowerCase' of undefined
    at timer.catch.e (/e2e/node_modules/webdriverio/build/commands/browser/waitUntil.js:75:11)
    at Element.waitForDisplayed (/e2e/node_modules/webdriverio/build/commands/element/waitForDisplayed.js:51:15)
```

**Additional context**

> Please use the correct markdown

**Comment by mgrybyk** [comment]
@abjerstedt can you please help?
Looks like it is because of https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/commands/element/isDisplayed.js#L73

**Comment by mgrybyk** [comment]
changed it locally to `browser.isW3C && !browser.isMobile && ...` and isDisplayed working again.

**Comment by christian-bromann** [comment]
let's make a PR and exclude Appium sessions from this tweak.
