### ISSUE TITLE
How do I access the document object?

### ISSUE THREAD

**Issue by S-Voss** [webdriverio/webdriverio#3703]
**I need a way to access the document so that I can return a list of elements to obtain their nodeType**
The issue I am having though is that the element's being returned don't include all the of the key/values that they would if I ran 'document.querySelectorAll('div')' inside of the Chrome Debugger Console.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [4.13.2]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [8.9.1]
 - **NPM version:** [5.8.0]
 - **Browser name and version:** [Chrome 68]
 - **Platform name and version:** [OSX 10.13.6]
 - **Additional wdio packages used (if applicable):** @wdio/spec reporter, @wdio/selenium-standalone service

My code looks like this:
const elementsToCheck = browser.execute(function() { return window.document.querySelectorAll('input') });

**Comment by erwinheitzman** [comment]
`const elem = browser.execute(() => document.querySelector('some-selector'))`

**Comment by erwinheitzman** [comment]
And if you miss something, then please state what you are missing. Else we're just guessing..

**Comment by S-Voss** [comment]
I've tried that but it only returns: {"sessionId":"06ba4b9f6c760a13b371c9ed37c0c136","value":{"ELEMENT":"0.14538048399761405-1"},"_status":0}

However, I am looking for the full object: NodeList(12) [input.s-input.js-search-field., input#post-id, input#qualityBanWarningShown, input, input#fkey, input#author, input.use-facebook, input.use-google, input.submit-openid, input#display-name.s-input, input#m-address.s-input, input]

**Comment by wangrenyn** [comment]
for the full object: NodeList(12) [input.s-input.js-search-field., input#post-id, input#qualityBanWarningShown, input, input#fkey, ??

**Comment by S-Voss** [comment]
So if you run `document.querySelector('some-selector')` inside of a browser.execute call, you get a different result than simply pasting that in Chrome Developer Console. I need the Developer Console result.

**Comment by CrispusDH** [comment]
Probably, you want `document.querySelectorAll()`
Here some view example:

![image](https://user-images.githubusercontent.com/12623263/54053886-5cb80b80-41f1-11e9-80b5-d5da26a8ba54.png)

**Comment by S-Voss** [comment]
My apologies, I mean document.querySelectorAll('some-selector') in my other comment. If I run your suggestion within Webdriver's execute function it is a different result? I cannot figure out why that is the case though.

**Comment by baruchvlz** [comment]
@S-Voss `browser.execute` will only return the JSONWP or WebDriver key for the element as that is all the driver needs to run, this was changed here #3612. Try using the `$` or `$$` functions to get the documents, you can see an example [here](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/commands/element/%24%24.js#L8-L32).

**Comment by christian-bromann** [comment]
I think this can be closed. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have further questions.
