### ISSUE TITLE
waitForDisplayed with revers=true does not work properly 

### ISSUE THREAD

**Issue by FelixZilber** [webdriverio/webdriverio#3709]
$(selector).waitForDisplayed(10000, true); not working properly.
In case of not visible element at the first place, it will pass as expected.

But when the element first visible and disappear during the test, it will fail.
for validation I used:
 `<div>
        <button id="disappearing-btn" onclick="disappearBtn()">DISAPPEAR ON CLICK</button>
        <script>
            function disappearBtn() {
                    window.setTimeout(()=>{document.getElementById("disappearing-btn").style.display = "none"},5*1000);
                };
        </script>
    </div>`

**Comment by mgrybyk** [comment]
@FelixZilber I'm fixing isDisplayed atm.
Anyway, can you provide steps to reproduce and log.
What browser are u using?

**Comment by FelixZilber** [comment]
Using latest chrome and firefox with 
```js
$(selector).waitForDisplayed(DEFAULT_TIME_OUT, true);
```

and sample html element:
```js
<div>
<button id="disappearing-btn" onclick="disappearBtn()">DISAPPEAR ON CLICK</button>
    <script>
    function disappearBtn() {
        window.setTimeout(()=>{
            document.getElementById("disappearing-btn").style.display = "none"
            },5*1000);
        };
    </script>
</div>
```

**Comment by mgrybyk** [comment]
yes, confirming issue, it has been fixed with https://github.com/webdriverio/webdriverio/pull/3701

**Comment by mgrybyk** [comment]
Used following code for testing, btw:
```
browser.url("http://adam.goucher.ca/parkcalc/")
const inputSelector = "input[type='submit']"

// already not existing
$("not-existing").waitForDisplayed(2000, true)
const el = $(inputSelector)
console.log(el.isDisplayed()) // true

// remove element in 3 seconds
browser.execute(function (selector) {
    const window = this
    window.setTimeout(() => {
        window.document.querySelector(selector).remove()
    }, 3000);
}, inputSelector)

// first existing, then not existing
$(inputSelector).waitForDisplayed(8000, true)
console.log(el.isDisplayed()) // false
```

works fine in chrome and safari in my PR

**Comment by abjerstedt** [comment]
Until we put the fix out use waitForExist for negative checks.
