### ISSUE TITLE
@wdio/eyes.webdriverio missing src directory 

### ISSUE THREAD

**Issue by khsd** [webdriverio/webdriverio#3711]
**Describe the bug**
src directory is missing from npm @wdio/eyes.webdriverio

**To Reproduce**
goto https://npm.runkit.com/@wdio/eyes.webdriverio
press run 
it will give an error in line 1 : exports.Eyes = require('./src/Eyes');

**Comment by christian-bromann** [comment]
I just released a new version with a fix for this.
