### ISSUE TITLE
Are there issues with waitForExist with chrome?

### ISSUE THREAD

**Issue by adamsjoe** [webdriverio/webdriverio#3713]
I have an issue where a "loading" screen will appear at certain points of an application.  

So far, with firefox, I've been using element.waitForExist(10000, true) to hold the test until the loading screen dissapears. This blocks the tests and things will run with no issues.

I've tested this in Chrome and am finding that the tests fail due to the loading screen being present.

Observing the test, it can be seen to be moving too quickly through.

I can't see any reports of issses with Chrome, so thought I'd ask a question first.

**Comment by christian-bromann** [comment]
@adamsjoe can you try with the latest WebdriverIO version. We recently fixed some bugs that might be connected with it.

**Comment by adamsjoe** [comment]
@christian-bromann I updated to latest last week (5.7.0) - there is a thought that things could be working as expected - that firefox has a slower rendering engine compared to chrome?

**Comment by christian-bromann** [comment]
could be .. without any logs here it is impossible to do more than guessing.

**Comment by adamsjoe** [comment]
Have tried going to the latest (5.7.2) still the same. 

What logs do you need / would be helpful ?

**Comment by mgrybyk** [comment]
You are seeing the problem if there element is not existing when you are calling waitForExist or if there is element first and then it disappears?

It is difficult to guess

**Comment by adamsjoe** [comment]
So the sequence is like this.
Login - loading screen appears - loading screen disappears - menu is on screen.

using firefox, I can get to the menu.
On chrome, I get a fail at loading screen appears as it thinks the screen isn't there and the test rolls onto the "menu on screen" section.

(not sure if that's cleared things up or made things worse?)

**Comment by mgrybyk** [comment]
Are you sure selector is valid for chrome?
Why don't you wait for login form to appear?

**Comment by mgrybyk** [comment]
Ok, I've just double checked, waitForExist works fine in both cases:
- when element is not existing
- when element first exists and then disappears 

Most likely you are either using wrong selector or waitForExist('loading screen') is called when it is no longer exist, so there is nothing to do with webdriverio itself.

For questions like this use https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by adamsjoe** [comment]
No the selector is valid - if I put in a long browser.pause (about 2 seconds) then things work as expected.

I suspect that firefox is rendering things slower than Chrome on this element, so wait for not exist is being triggered prematurely.
