### ISSUE TITLE
minimizeWindow not defined (TypeError: browser.minimizeWindow is not a function)

### ISSUE THREAD

**Issue by Antonius-S** [webdriverio/webdriverio#3714]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2] 5.7.2
 - **Mode:** [Standalone mode or WDIO Testrunner] Standalone
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async] async
 - **Node.js version:** [e.g. 8.11.2] 10.15.1
 - **NPM version:** [e.g. 5.8.0] 6.9.0
 - **Browser name and version:** [e.g. Chrome 68] Chrome 73
 - **Platform name and version:** [e.g. Windows 10] Win7
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config
```
module.exports.config = {
	browserName: 'chrome',
	hostname: 'localhost',
	port: 4444,
	logLevel: 'trace',
	coloredLogs: true,
	waitforTimeout: 5000,

	path: '/',
	capabilities:
		{
			browserName: 'chrome',
			chromeOptions:
			{
			}
	}
};
```
**Describe the bug**
`minimizeWindow` function is not defined for browser

**To Reproduce**
```js
'use strict';

const wdio = require('webdriverio');

async function main()
{
	const options = require('./wdio.conf.js').config;
	const browser = await wdio.remote(options);

	try
	{
		await browser.url('https://google.com');
		await browser.minimizeWindow();
	}
	finally
	{
		await browser.deleteSession();
	}
}

main();
```

[Include code or an example repository that can easily be set up]

**Expected behavior**
Browser window to minimize

**Log**
```2019-03-11T15:59:00.884Z DEBUG @wdio/config: @wdio/sync not found, running tests asynchronous
2019-03-11T15:59:01.151Z INFO webdriver: [POST] http://localhost:4444/session
2019-03-11T15:59:01.152Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { browserName: 'chrome', chromeOptions: {} },
     firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'chrome', chromeOptions: {} } }
2019-03-11T15:59:02.707Z INFO webdriver: COMMAND navigateTo("https://google.com")
2019-03-11T15:59:02.709Z INFO webdriver: [POST] http://localhost:4444/session/9d7e81107c1daa4d915d3569d732d96f/url
2019-03-11T15:59:02.710Z INFO webdriver: DATA { url: 'https://google.com' }
2019-03-11T15:59:03.874Z INFO webdriver: COMMAND deleteSession()
2019-03-11T15:59:03.876Z INFO webdriver: [DELETE] http://localhost:4444/session/9d7e81107c1daa4d915d3569d732d96f
(node:9136) UnhandledPromiseRejectionWarning: TypeError: browser.minimizeWindow is not a function
    at main (D:\Coding\Projects\Node.js\_test-webdriver\testwdio.js:13:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
Chrome is still using the JSONWire Protocol for the most part which doesn't support this command. There is nothing WebdriverIO can do about it. The Chromedriver team is working on bringing their driver up to date.
