### ISSUE TITLE
Screenshot after delay

### ISSUE THREAD

**Issue by aparna1413** [webdriverio/webdriverio#3715]
**Describe your question with as much detail as possible**
Hello, 
I need to take screenshot after a delay. The page takes a while to load.

**If it's about a specific piece of code, try and include some of it to support your question.**
`describe('componentParent', () => {
  describe('component1', () => {
    beforeEach(() => browser.goToStory(path));
    describe('component1 renders correctly', () => {
      ....
    });
  });
});
`
Whats the syntax for that. Couldn't find any examples 

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2]
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:** [e.g. 8.9.1]
 - **NPM version:** [e.g. 5.8.0]
 - **Browser name and version:** [e.g. Chrome 68]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Additional context**

**Comment by emilyrohrbough** [comment]
Have you tried adding utilizing of of these commands?
- https://webdriver.io/docs/api/element/waitForDisplayed.html
- https://webdriver.io/docs/api/element/waitForEnabled.html
- https://webdriver.io/docs/api/element/waitForExist.html
- https://webdriver.io/docs/api/element/waitUntil.html
- https://webdriver.io/docs/api/browser/pause.html

**Comment by christian-bromann** [comment]
Please see @emilyrohrbough suggestion. If you have further questions, join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). Thanks!
