### ISSUE TITLE
How to extend Element class method in TypeScript using webdriverio?

### ISSUE THREAD

**Issue by draganrakas** [webdriverio/webdriverio#3719]
**Stack: TypeScript, WDIO, Cucumber**

We are having an issue with the click() functionality not working on buttons in SauceLabs only, and on FireFox only. We tested other combinations (local, CI, Docker, etc.) and our tests work on both FireFox and Chrome for all of those combinations. However, on SauceLabs, clicking a button in FireFox is very flaky. 

We have tested a JavaScript workaround that works, on SauceLabs on FireFox, and as a result, we would like the element click() method to behave differently depending if the browser capability is either chrome or firefox.

To do this, we would like to extend the WebDriver Element, and override the click method with our own. Basically, use super.click() for chrome, and our own click for firefox.

Currently, our BasePage exports this, which is just a typedef that the page objects use:
`export type WDIOElement = WebdriverIO.Client<WebdriverIO.RawResult<WebdriverIO.Element>>`

Instead of this, we would like to create a `WDIOElement` definition that implements the `WebdriverIO.Client<WebdriverIO.RawResult<WebdriverIO.Element>>` interface, re-implements click() and export that instead.

Is this even possible?  What would be the recommended way to do this? 
If this is pretty bad practice, is there something better we could do? 

Thanks!

**Comment by mgrybyk** [comment]
You can add typings for new commands like this

```
declare namespace WebdriverIO {
    interface Browser {
        customCommand (): void
    }

    interface Element {
        optAttribute (attributeName: string): string
    }
}
```

**Comment by mgrybyk** [comment]
At this moment there is no way to override commands, there is planned work to do it #3604

**Comment by draganrakas** [comment]
@mgrybyk We're currently using Webdriver 4.x due to compatibility issues with TypeScript & Cucumber. Is there an equivalent for 4.x?

**Comment by mgrybyk** [comment]
At this point I can't help you, I was using v4 with js.

**Comment by christian-bromann** [comment]
@mgrybyk if people use addCommand can they somehow extend the existing typescript definition with their command?

**Comment by mgrybyk** [comment]
Yes, as it mentioned here https://github.com/webdriverio/webdriverio/issues/3719#issuecomment-472080469

**Comment by christian-bromann** [comment]
Ah ok, now I see that @draganrakas is using v4. Moving the issue there then.

**Comment by christian-bromann** [comment]
This issue was moved to webdriverio-boneyard/v4#29
