### ISSUE TITLE
getViewportSize no longer exists

### ISSUE THREAD

**Issue by kennyw12** [webdriverio/webdriverio#3724]
**Describe your question with as much detail as possible**
It seems like browser.getViewportSize no longer exists. 
It was documented in http://v4.webdriver.io/v3.4/api/window/getViewportSize.html
and is no longer documented in the most recent docs. https://webdriver.io/docs/api.html

But I don't see any entry of this change in the [changelog](https://github.com/webdriverio/webdriverio/blob/master/CHANGELOG.md)

Is there another way to get at the viewport size?

 - **WebdriverIO version:** 5.7.2

**Comment by christian-bromann** [comment]
Sorry, it seems we missed to put this into the changelog. We modifed a lot of commands and this slipped through. Please use addCommand to readd this to your browser object based on this implementation: https://github.com/webdriverio-boneyard/v4/blob/master/lib/commands/getViewportSize.js
