### ISSUE TITLE
Will emit error if use webdriverio promise with Q.all

### ISSUE THREAD

**Issue by jonakyd** [webdriverio/webdriverio#373]
emailPromise = @setValue '#email', userData.email
      passwordPromise = @setValue '#password', userData.password
      
      Q.all [emailPromise, passwordPromise]
      .then ->
        console.log 'ok'

the `ok` log will still success, but will emit following error

    Message:
        Object [object Promise] has no method 'getPromise'
    Details:
        domain: [object Object]
        domainThrown: true
    Stack:
    TypeError: Object [object Promise] has no method 'getPromise'
      at .../node_modules/webdriverio/lib/utils/PromiseHandler.js:84:53
      at process._tickDomainCallback (node.js:463:13)

Is there anything I miss?

**Comment by syzer** [comment]
@christian-bromann Except that waitFor() in use with promises witch dosent wait for

**Comment by christian-bromann** [comment]
Promise support will be way more stable in `v3`
