### ISSUE TITLE
Possible to disable updateClock() in updateView() in interface.js file?

### ISSUE THREAD

**Issue by ruiquanwu** [webdriverio/webdriverio#3732]
**Is your feature request related to a problem? Please describe.**
The updateClock() is nice and connivence when running tests manually. However, when using CD/CI tool like CircleCI, the output is full of time counting. It makes result hard to read and take a little more time to execute.

**Describe the solution you'd like**
Can we have a environment variable to disabled the timer in terminal output.

**Describe alternatives you've considered**
remove the updateClock() method? like v4 we don't have that.

**Additional context**
It is a very nice feature to have when running script manually, but considering most of the test execution happens in CI/CD tool, I don't like it.

<img width="1265" alt="Screen Shot 2019-03-17 at 12 17 21 AM" src="https://user-images.githubusercontent.com/9355437/54485633-1a727800-484a-11e9-8620-7605c49edc08.png">

**Comment by christian-bromann** [comment]
We are working on this in #3638
