### ISSUE TITLE
Incorrect string template in 4.14.3 release

### ISSUE THREAD

**Issue by cschwebk** [webdriverio/webdriverio#3737]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 4.14.3
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.15.1
 - **NPM version:** 6.9.0
 - **Browser name and version:** Firefox
 - **Platform name and version:** Mac OS 10.14.3
 - **Additional wdio packages used (if applicable):** wdio-sauce-service@0.4.14

**Config of WebdriverIO**

```
  ...
  services: ['sauce'],
  user: process.env.SAUCE_USERNAME,
  key: process.env.SAUCE_ACCESS_KEY,
  capabilities: [
    {
      maxInstances: 3,
      acceptInsecureCerts: true,
      browserName: 'firefox',
      version: '65.0',
      screenResolution: '1280x1024',
      platform: 'Windows 10'
    }
  ],
  ...
```

**Describe the bug**
When trying to run via saucelabs, there is an error.

```
ERROR: getaddrinfo ENOTFOUND ondemand. ondemand.:443
```

**To Reproduce**
`wdio wdio.conf.js`

**Expected behavior**
It should run correctly.

**Log**

**Additional context**
Looks like the problem is in `lib/helpers/detectSeleniumBackend.js`. There is an incorrect string template. Since there is no release/tag for `v4.14.3`, I'm unable to link you to the file, but it was correct in [`v4.14.1`](https://github.com/webdriverio/webdriverio/blob/v4.14.1/lib/helpers/detectSeleniumBackend.js#L68)
```
    /**
     * Sauce Labs
     * e.g. 50aa152c-1932-B2f0-9707-18z46q2n1mb0
     */
    return {
        protocol: 'https',
        host: capabilities.host || "ondemand.${getSauceEndpoint(capabilities.region)}",
        port: 443
    };
```

**Comment by cschwebk** [comment]
Just found the boneyard. Looks like this issue is already [there](https://github.com/webdriverio-boneyard/v4/issues/27). Please fix it :)

**Comment by christian-bromann** [comment]
> Please fix it :)

Please provide a fix for this :)

**Comment by cschwebk** [comment]
> > Please fix it :)
> 
> Please provide a fix for this :)

There are already two PRs open, didn't think we needed a third ;)
https://github.com/webdriverio-boneyard/v4/pull/28
https://github.com/webdriverio-boneyard/v4/pull/23
