### ISSUE TITLE
Request failed due to Illegal key values seen in w3c capabilities

### ISSUE THREAD

**Issue by rolandjitsu** [webdriverio/webdriverio#3743]
**Environment:**
 - **WebdriverIO version:** v5.7.2
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** v8.15.1
 - **NPM version:** v6.4.1
 - **Browser name and version:** Firefox 65
 - **Platform name and version:** macOS 10.14
 - **Additional wdio packages used (if applicable):** @wdio/cli, @wdio/dot-reporter, @wdio/jasmine-framework, @wdio/local-runner, @wdio/sauce-service, @wdio/spec-reporter, @wdio/sync

**Config of WebdriverIO**
Check [rolandjitsu/react-dropzone/wdio.conf.js](https://github.com/rolandjitsu/react-dropzone/blob/test/e2e/wdio.conf.js).

**Describe the bug**
Running tests on TravisCI fails with:
```
[0-0] 2019-03-20T15:26:02.642Z ERROR webdriver: Request failed due to unknown error: Illegal key values seen in w3c capabilities: [build, platform, tags, tunnel-identifier, version]
    at getErrorFromResponseBody (/home/travis/build/react-dropzone/react-dropzone/node_modules/webdriver/build/utils.js:343:10)
    at Request._callback (/home/travis/build/react-dropzone/react-dropzone/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/home/travis/build/react-dropzone/react-dropzone/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/travis/build/react-dropzone/react-dropzone/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/travis/build/react-dropzone/react-dropzone/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
```

The full log can be seen at [#508989487](https://travis-ci.org/react-dropzone/react-dropzone/builds/508989487).

**To Reproduce**

Code can be found at [rolandjitsu/react-dropzone](https://github.com/rolandjitsu/react-dropzone/tree/test/e2e).
Running locally with SauceLabs works (well, not really, getting 500 when trying to reach localhost), but on Travis it fails to start the tests.

**Expected behavior**
It should start the tests on Travis with the desired capabilities.

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by juliamaksimchik** [comment]
Hi,

I have the same issue but with Browserstack service on my Jenkins pipeline. In the end, I've figured out that user and key for BS wasn't passed correctly to the config (process.env variables wasn't populated in my case)

I hardcoded my user & key to check if it solves the issue and it did. The message of the error should be clearer :(

**Comment by rolandjitsu** [comment]
Hmm, could be. But Travis does pick up on them because it manages to establish a tunnel using sauce connect.

**Comment by christian-bromann** [comment]
@rolandjitsu how do you run your tests, it seems you are running against a local driver and not SauceLabs. Looking at the config it seems that you have both in there:

```js
services: ['sauce', 'selenium-standalone']
```

You only need on of these, you either run the tests locally or on Sauce. As you can see in the logs in tries to access a local driver:

```
[0-0] 2019-03-20T15:26:02.438Z INFO webdriver: DATA { capabilities: 
   { alwaysMatch: 
      { browserName: 'firefox',
        platform: 'macOS 10.14',
        version: '65.0',
        'tunnel-identifier': '1233.1',
        build: 'Dropzone - 1233',
        tags: [Array] },
     firstMatch: [ {} ] },
  desiredCapabilities: 
   { browserName: 'firefox',
     platform: 'macOS 10.14',
     version: '65.0',
     'tunnel-identifier': '1233.1',
     build: 'Dropzone - 1233',
     tags: [ 'e2e', 'dropzone' ] } }
[0-0] 2019-03-20T15:26:02.566Z INFO webdriver: Retrying 1/3
2019-03-20T15:26:02.566Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
```

Maybe it couldn't propagate the sauce user name and access key into the config.

**Comment by rolandjitsu** [comment]
@christian-bromann I don't think that having both services there was an issue as I get the same behavior if I remove the standalone selenium.

You can see the config in the repo, the username and access key are set from the env. I also tested locally where I'm sure I have them set. On top of that, it is able to setup the sauce connect tunnel, which means the credentials are there.

I'm not sure why it tries to connect to a local driver, I don't have that in my config.

**Comment by rolandjitsu** [comment]
I'm actually getting a different issue now after I removed 'selenium-standalone' from services and left just sauce (see [#509781847](https://travis-ci.org/react-dropzone/react-dropzone/builds/509781847)).

But what I don't really understand is why is it trying to connect to a local driver anyway? Or is it trying to establish a connection with SL through a local selenium server?

**Comment by rolandjitsu** [comment]
I'm starting to think this might be an issue with the testrunner or the sauce service.

**Comment by rolandjitsu** [comment]
Opened https://github.com/webdriverio/webdriverio/issues/3754 to illustrate the issue. Unless my config is wrong, there must be something wrong with the way the hostname is setup.
