### ISSUE TITLE
Allow to manually configure address+port for "devtools" service

### ISSUE THREAD

**Issue by njam** [webdriverio/webdriverio#3744]
**Is your feature request related to a problem? Please describe.**
I was struggling to configure the correct DevTools address, when running chrome in a docker container, on a different IP than where I run the tests.

The auto detection in [`findCDPInterface()`](https://github.com/webdriverio/webdriverio/blob/b7ab39f46d896a6ac671080e11f420dd56ea08d2/packages/wdio-devtools-service/src/utils.js#L15) can successfully detect the DevTools _port_, but not the _IP address_.

**Describe the solution you'd like**
Allow to configure the DevTools address + port via the service configuration.  
For example:
```
  services: [
    ['devtools', {
      debuggerAddress: '10.0.0.3:9222'
    }],
  ]
```

**Describe alternatives you've considered**
The auto detection could be improved, but as a last resort it's still better to have direct control over the remote address imo.

**Additional context**
As a workaround I can set `chromeOptions.debuggerAddress` delayed in `before()`, so it will be picked up by the auto detection. If I don't delay the configuration until `before()` the DevTools connections seems to get established _before_ chrome is running, and obviously fails.
```
  before: function(capabilities, specs) {
    global.browser.capabilities['goog:chromeOptions'].debuggerAddress = `10.0.0.3:9222`
  },
```

**Comment by njam** [comment]
Here's a one-liner to start a docker container with chromedriver and chrome (and the [code repo with the Dockerfile](https://gitlab.com/denkmal/docker-chromedriver)):
```
docker run --rm -p 4444:4444 -p 9222:9222 registry.gitlab.com/denkmal/docker-chromedriver chromedriver --port=4444 --whitelisted-ips= --url-base=/wd/hub --verbose
```

**Comment by prathameshnyt** [comment]
I am running into the following issue while running dev tools against Chrome running inside the docker container. 

```
[0-0] This test will run using docker service provided by WebDriverIO using standalone-chrome-debug image.
[0-0] (node:93741) UnhandledPromiseRejectionWarning: Error: socket hang up
```

I have the following config:
```
services = ['docker', ['devtools', { debuggerAddress: 'localhost:9222'}]];
```

```
    dockerOptions = {
        image: 'selenium/standalone-chrome-debug',
        // If healthCheck is not configured, Webdriver will start running tests immediately after Docker container starts, which maybe too early considering that it takes time for web service to start inside a Docker container.
        healthCheck: {
            url: 'http://localhost:4444',
            maxRetries: 3,
            inspectInterval: 1000,
            startDelay: 2000
        },
        options: {
            p: ['4444:4444',  '9222:9222'],
            shmSize: '2g'
        }
    };
```

Do I have to add any other setting in configs? Please let me know.

**Comment by njam** [comment]
@prathameshnyt you can find my full configs here:
- [wdio.conf.js](https://gitlab.com/denkmal/denkmal-website/blob/master/wdio.conf.js)
- [docker-compose.yml](https://gitlab.com/denkmal/denkmal-website/blob/master/docker-compose.yml)

The repo is open-source, you can also take a look at the README and the CI config. Hope it helps!

**Comment by prathameshnyt** [comment]
Thanks @njam 

Can you please try with https://github.com/stsvilik/wdio-docker-service/  when you get a chance and see if it works for you?

I will go over your files.

Thanks,
Prathamesh

**Comment by njam** [comment]
@prathameshnyt ah I didn't know about this project, thanks for the link! I don't have the time to test it unfortunately, sorry. Good luck with the debugging!

**Comment by prathameshnyt** [comment]
No problem. Thanks for looking into.

**Comment by prathameshnyt** [comment]
@christian-bromann @valenso I can open a new ticket. Are you able to get it to work? I am trying to connect to the docker container. Please let me know.
