### ISSUE TITLE
multiremote fails when spec are given inside capabilities 

### ISSUE THREAD

**Issue by meruga-java** [webdriverio/webdriverio#3748]
When `specs:[]` are distributed among capabilities in multiremote then webdriverIO crashes when either one of the capabilities finished running their `specs:[]`

Environment:
WebdriverIO Version: 4.14.1

my wdio.conf.js
=================================

 host:'127.0.0.1',
 port:4723,
 maxInstances:2,
  config.cucumberOpts= {
    require: [
      './test/support/common/step_definitions/*.js',
      './test/support/ios/pages/**/*.js',
      './test/support/common/api/**/*.js',
    ],
tagExpression:'@automated',
  };
{
      app: `app_path`,
      platformVersion: "12.1.4",
      deviceName: "iPhone One",
      udid: 'XXXXXX-XXXXXX',
      xcodeOrgId: "XXXXXXXXXX",
      xcodeSigningId: "iPhone Developer",
      updatedWDABundleId: "com.xxx",
      waitForQuiescence: true,
      fullReset: true,
      startIWDP: false,
      useNewWDA: true,
      wdaLocalPort: 8100,
      skipLogCapture: true,
      mjpegServerPort:9100,
      platformName:'iOS',
      specs: [
         './test/features/common/folder1/*.feature',
         './test/features/common/folder2/*.feature'
      ],
    },
{
      app: `app_path`,
      platformVersion: "12.1.4",
      deviceName: "iPhone Two",
      udid: 'XXXXXX-XXXXXX',
      xcodeOrgId: "XXXXXXXXXX",
      xcodeSigningId: "iPhone Developer",
      updatedWDABundleId: "com.xxx",
      waitForQuiescence: true,
      fullReset: true,
      startIWDP: false,
      useNewWDA: true,
      wdaLocalPort: 8200,
      skipLogCapture: true,
      mjpegServerPort:9200,
      platformName:'iOS',
      specs: [
         './test/features/common/folder3/*.feature',
         './test/features/common/folder4/*.feature',
         './test/features/common/folder5/*.feature'
      ],
    }

So when i run this config it runs perfectly launching two devices running their respective features from their spec[] folder, but the issue comes when either one of the capability is finished with running spec and only the other is running i see error `Failed to take screenshot on reject: 	 {"message":"A session is either terminated or not started","type":"RuntimeError","seleniumStack":{"type":"NoSuchDriver","message":"A session is either terminated or not started","orgStatusMessage":"A session is either terminated or not started"}}` 

@christian-bromann can you comment on this

**Comment by christian-bromann** [comment]
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
