### ISSUE TITLE
OnScreenshot reporter fuction never called

### ISSUE THREAD

**Issue by rpii** [webdriverio/webdriverio#3749]
[config.txt](https://github.com/webdriverio/webdriverio/files/2993984/config.txt)

 I am evaluating webdriverio as a replacement for a large selenium java test suite.  We need a solid html report that can appear in Jenkins.  Seeing as wdio-html-format-reporter doesnt not work with webdriverio v5, I forked it and  ported it to 5.0
 See this at https://github.com/rpii/wdio-html-reporter.  When debugging this reporter, I find that saveScreenshot does not fire the onScreenshot event in the WDIOReporter, or any 'runner:screenshot' event.  

Environment
 - WebdriverIO version:5.7.3
 - Mode: WDIO Testrunner
 - WDIO Testrunner, running sync
 - Node.js version:v11.10.0
 - NPM version:6.7.0
 - Browser name and version Chrome
 - Platform name and version: Windows 10
 - Additional wdio packages used (if applicable): wdio-html-reporter  https://github.com/rpii/wdio-html-reporter

my findings:

	No existing reporters do anything with this event
 	
 	I scanned the webdriverio code and dont find it fired directly.  It is proxied from the 'screenshot' event in @wdio/cli, but I never see it appear.

 	I tried to fire it from where I call browser.saveScreenshot, using the following permutations:

 	...
 	    browser.saveScreenshot(filepath);
            browser.emit({
            event: 'runner:screenshot',
            output: message,
            filename: filepath
        });

        or
            browser.saveScreenshot(filepath);
           process.send({
            event: 'screenshot',
            output: message,
            filename: filepath
        });
 	...

 	However it never arrives in the reporter.  Can anyone help me make this work?
 	Screenshots are critical for auditing in the report. 

        The bug as I see it would be the event is never fired.

 	thanks
 	Rich

**Comment by BorisOsipov** [comment]
Hi @rpii 

There is no particular `onScreenshot` event in v5.
If you want to intercept screenshots in your reporter you may do in `onAfterCommand` see example in 
https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-allure-reporter/src/index.js#L121

**Comment by rpii** [comment]
Boris,

So be it.  The onScreenshot overload in WDIOReporter should be removed as it makes one believe it is fired.

Rich

**Comment by rpii** [comment]
for https://webdriver.io/docs/api/element/saveScreenshot.html

It seems that the screenshot filename in saveScreenshot(filename ) is not used then.  Probably should be removed.

**Comment by christian-bromann** [comment]
> The onScreenshot overload in WDIOReporter should be removed

What onScreenshot overload do you mean?

> It seems that the screenshot filename in saveScreenshot(filename ) is not used then. Probably should be removed.

I don't understand, what is where not used?

**Comment by rpii** [comment]
If the only way to save a screenshot is in the onAfterCommand() overload like Boris is showing, that command is a selenuim command and the filename is gone at that point and the data is base64.
The onScreenshot event is the one in WDIOReporter that is never called.

**Comment by rpii** [comment]
Christian,
After trying to implement the  onAfterCommand(command)  function as Boris mentioned,  I think that that is not the correct solution.  for two reasons:

1 a file is written by saveScreenshot, and that work has to be redone in onAfterCommand but we dont know what the desired filename was.

2.  Its a bit of a hack.  I need the cid, suite uid and test uid to properly correlate the screenshot with where it is in the test.  That information should come in the onScreenshot event. Its not available in onAfterCommand.

So there could be two paths forward:

1 reimplement the firing of the onScreenshot event.
2. manually fire that event and let the code that is there work .  I tried to fire the event manually but cant it to sink in the reporter.  I tried the two methods mentioned in the original post.  perhaps you have some suggestions about that. 

I think the issue should be reopened

**Comment by christian-bromann** [comment]
> 1. come in the onScreenshot event

There is no such event.

> 1. I need the cid, suite uid and test uid to properly correlate the screenshot with where it is in the test

That should be no problem to get ahold of. You are receiving these information in e.g. the beforeTest hook that will be executed before.

**Comment by rpii** [comment]
The documentation for WDIOReporter does show such an event, so it would need to be updated.  
At https://webdriver.io/docs/customreporter.html.

**Comment by arvere** [comment]
Not to mention it exists in the "WDIOReporter" class (both in js and the ts interface)

**Comment by rpii** [comment]
It is there but is never called in version 5.  I worked around this by  firing an event for in widio-html-reporter
