### ISSUE TITLE
Handling ntlm authentication

### ISSUE THREAD

**Issue by survot** [webdriverio/webdriverio#376]
Hi,

(note: I am using Firefox as the browser right now, but I would also want the solution to work with IE and phantom)

I'm having a problem filling out the NTLM (windows) authentication popup on sites and was wondering what the best way of dealing with them is?

This would appear to be a general problem for Selenium, but there are workarounds:
Put the username and password in the get request (https://user:password@example.com)
[Switch to the authentication popup and type the username and password](http://stackoverflow.com/questions/23143348/getting-past-ie-authentication-with-webdriver)
[It might also be possible to handle this in the firefox profile settings](http://stackoverflow.com/questions/3021602/http-basic-auth-via-url-in-firefox-does-not-work)
[Another possibly useful link](http://sqa.stackexchange.com/questions/2277/using-selenium-webdriver-with-windows-authentication)

I have not yet managed to find a method that works with webdriverio. It seems to stop running when the authentication popup appears. If I manually close it then the script will continue.
Sorry if this is a little vague, let me know what other details you need.

Thanks

**Comment by christian-bromann** [comment]
I am afraid that this is more an issue of Selenium and not WebdriverIO. I've found a [couple of blog posts](http://www.360logica.com/blog/2014/08/http-authentication-selenium-webdriver.html) which got that issue solved by requesting the url like this:

```js
client
    .init()
    .url('http://user:pass@abc.com')
    // ...
```
