### ISSUE TITLE
setValue appends instead of overwriting the value in Chrome

### ISSUE THREAD

**Issue by zw301** [webdriverio/webdriverio#3761]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version: 5.7.2
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:sync
 - **Node.js version: 8.12.0
 - **NPM version: 6.4.1
 - **Browser name and version: Chrome 73.0.3683.75
 - **Platform name and version: macOS Mojave 10.14.3
 - **Additional wdio packages used (if applicable):

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**

I have an input with some text in it. 
$(input').getValue();
// => '000'; 

I want to use setValue to change the value
$(input').setValue('666'); 

Then If you get the value. It should be "666". However,
$(input').getValue();
// => '000666'; 

I found the same issue with the old version of wdio:
https://github.com/webdriverio/webdriverio/issues/1140
I think it is a regression.

Only happens in Chrome. FF is fine.

**Comment by christian-bromann** [comment]
This is a problem with Chromedriver and can't be fixed in WebdriverIO. Please report the problem in the Chromedriver project. Thanks!
