### ISSUE TITLE
webdriverio moveToObject()

### ISSUE THREAD

**Issue by michaelseno** [webdriverio/webdriverio#3763]
**Describe your question with as much detail as possible**
I am trying to simulate a `mouse over` on a bootstrap menu in a browser. the issue is that I'm not able to do a click command because the menu will only open if you hover the mouse pointer and when the time that you will try to click it. the menu disapear. 

I can verify that the element is there because when using a click Command, it will open and close the menu. so when using the `moveToObject()` it doesn't have any error. only warning on the deprication and it will pass the test but it did not open the menu. Below is the code/function I created. I also did the actions command and touchAction but seems not working as well.

**If it's about a specific piece of code, try and include some of it to support your question.**
```
async hover(locator) {
    const errorMsg = UNSUCCESSFULL_MESSAGE + locator;
    await this.executeWithErrorHandling(async () => {
      await this.browser.waitForExist(locator, 20000);
      await this.browser.moveToObject(locator);
    }, errorMsg);
    await this.pauseForInSeconds(1);
  }
```
inside the `executeWithErrorHandling()` is just a try/catch.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 4.14.2
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** v8.11.2
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome Version 71.0.3578.98 (Official Build) (64-bit)
 - **Platform name and version:** MacOSX 10.13.6 (remotely)

Additional Information:
I tried the `dragAndDrop()` function and supplied 2 locators (locator to be dragged into another locator) but I'm having this error.

```
     unknown error: 'x' must be an integer
  Error: An unknown server-side error occurred while processing the command.
      at touchDown(338.90625, 148.515625) - dragAndDrop.js:24:26
```

**Comment by christian-bromann** [comment]
Thanks for filing the issue. We are not maintaining v4 within this repository anymore. Please create an issue here: https://github.com/webdriverio-boneyard/v4. Thanks!

**Comment by michaelseno** [comment]
This is noted. Thank you very much. I've already created an issue in the link you provided.

**Comment by michaelseno** [comment]
@christian-bromann I have an additional question. in version 5 of webdriverio, the moveToElement() will work as a mouse over? we are taking into consideration to move to version 5 if that works. since the moveToObject() in version 4 doesn't work somehow.

**Comment by christian-bromann** [comment]
> since the moveToObject() in version 4 doesn't work somehow.

If you use Firefox this command also won't work in v5 but you can use the actions command in v5 do automate hover effects.

**Comment by michaelseno** [comment]
how about chrome. will action commands work in v5 for chrome as well?

**Comment by christian-bromann** [comment]
no, actions doesn't work in Chrome yet

**Comment by michaelseno** [comment]
ok thanks for the info. I'll check on firefox actions
