### ISSUE TITLE
Error types for "setWindowSize"

### ISSUE THREAD

**Issue by ScenK** [webdriverio/webdriverio#3769]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version: 5.7.5
 - **Mode: Standalone mode
 - **Node.js version: 10.15.2
 - **NPM version: 6.9.0
 - **Platform name and version: mac 10.14

**Describe the bug**
Type definition errors in webdriverio-core.d.ts

**To Reproduce**
Our source code:
`client.setWindowSize(+browserOptions.width,  +browserOptions.height)`

The definition code (webdriverio-core.d.ts):
` setWindowSize(
            width,: number,
            height,: number
        ): null | object;
`

**Comment by christian-bromann** [comment]
I don't see any explanation of problem therefor closing!

**Comment by ScenK** [comment]
Hi, @christian-bromann, sorry I didn't know what explanations you were looking for. I thought the description was clear enough.
Did you notice the "comma" before the "colon" which is not correct grammar? 
It breaks the compile progress when using TypeScript in our project.

**Comment by christian-bromann** [comment]
> Did you notice the "comma" before the "colon" which is not correct grammar?

Might making a PR?

**Comment by WillBrock** [comment]
@ScenK This should be fixed with #3752 in the next release.

**Comment by christian-bromann** [comment]
Once #3768 is approved I will cut a new release.
