### ISSUE TITLE
how to set input type checkbox into checked state?

### ISSUE THREAD

**Issue by vinnitu** [webdriverio/webdriverio#377]
subj

Thanks.

**Comment by jedwards1211** [comment]
@christian-bromann in my experience, clicking on the checkbox doesn't always work...even when the error screenshot shows it as visible and enabled.

**Comment by cg-tester** [comment]
@christian-bromann in my case  clicking <input type="checkbox"> occurs not interactable error, and this checkbox has no label.
What other way can I use ?  Could you help me ?

**Comment by christian-bromann** [comment]
> What other way can I use ? Could you help me ?

Make sure the actual checkbox element is visible and interactable by the user and not obscured by another element for styling purposes. You can also use the action API to click on an x , y location.

**Comment by cg-tester** [comment]
@christian-bromann  first of all, thank you for replying.  To click on x, y location, I need x, y coordinate. 
How to get it ?  and it may be different in different devices. How to solve it ?

**Comment by christian-bromann** [comment]
> How to get it ?

See API docs: https://webdriver.io/docs/api/element/getLocation

> and it may be different in different devices. How to solve it ?

No idea what your requirements are.
