### ISSUE TITLE
The Proxy setup document issue

### ISSUE THREAD

**Issue by HTWTest** [webdriverio/webdriverio#3771]
I work behind a corporate proxy and I followed the steps under https://webdriver.io/docs/proxy.html to enter the details in wdio.conf.js. However when I gave "http://coporate proxy", it threw an error:  ERROR @wdio/runner: invalid argument: httpProxy must not contain a scheme
When I changed it to use "corporate proxy" without the http:// , it went through fine.

**Comment by christian-bromann** [comment]
@HTWTest do you mind create a PR to fix the docs?

**Comment by HTWTest** [comment]
@christian-bromann  : Sure I will.

**Comment by HTWTest** [comment]
@christian-bromann  Raised the PR#3772  from @harithah
