### ISSUE TITLE
browser.switchToFrame throws Unsupported frame locator: java.util.HashMap

### ISSUE THREAD

**Issue by ArunChockalingam** [webdriverio/webdriverio#3774]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2] 5.7.6
 - **Mode:** [Standalone mode or WDIO Testrunner] using WDIO local-runner
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async] sync
 - **Node.js version:** [e.g. 8.11.2] v10.1.0
 - **NPM version:** [e.g. 5.8.0] 5.6.0
 - **Browser name and version:** [e.g. Chrome 68] Chrome Version 72.0.3626.121
 - **Platform name and version:** [e.g. Windows 10] MacOS High Sierra V10.13.2
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service] 
    "@wdio/allure-reporter": "^5.7.2",
    "@wdio/browserstack-service": "^5.7.6",
    "@wdio/dot-reporter": "^5.7.2",
    "@wdio/jasmine-framework": "^5.7.6",
    "@wdio/junit-reporter": "^5.7.2",
    "@wdio/sauce-service": "^5.7.6",
    "@wdio/selenium-standalone-service": "^5.7.2",
    "@wdio/spec-reporter": "^5.7.2",
    "@wdio/sync": "^5.7.6",
    "@wdio/cli": "^5.7.6",
    "@wdio/local-runner": "^5.7.6"

**Config of WebdriverIO**
runner: 'local',
    specs: [
        './test/specs/test.specs.js'
    ],   
    exclude: [
        // './test/specs/file-to-exclude.js'
    ],
    maxInstances: 15,   
    capabilities: [
      {        
        maxInstances: 5,
        browserName: 'chrome',
        'goog:chromeOptions': {          
          prefs: {
            'profile.managed_default_content_settings.popups' : 2,
            'profile.managed_default_content_settings.notifications' : 2,
            'download.default_directory': downloadDir
          }
        }
      },
  ],    
    logLevel: 'silent',    
    deprecationWarnings: true,    
    bail: 0,    
    baseUrl: 'http://www.phptravels.net',
    waitforTimeout: 10000,            // Default timeout for all waitFor* commands.
    connectionRetryTimeout: 90000,    // Default timeout in milliseconds for request  // if Selenium Grid doesn't send response
    connectionRetryCount: 3,          // Default request retries count
    services: ['selenium-standalone'],
    seleniumInstallArgs: { version: '3.4.0' },
    seleniumArgs: { version: '3.4.0' },    
    framework: 'jasmine',    
    jasmineNodeOpts: {        
        defaultTimeoutInterval: (24 * 60 * 60 * 1000),        
        expectationResultHandler: function(passed, assertion) {            
        }
    },
    reporters: [
        'spec',
        ['junit', {
            outputDir: './test/reports/junit-results/',
            outputFileFormat: function(opts) { // optional
                return `results-${opts.cid}.${opts.capabilities}.xml`
            }
          }
        ],
        ['allure', {
            outputDir: './test/reports/allure-results/',
            disableWebdriverStepsReporting: true,
            disableWebdriverScreenshotsReporting: false,
          }
        ],
    ],

**Describe the bug**
browser.switchToFrame throws Unsupported frame locator: java.util.HashMap when passing the iframe element as input. 
Elements are structured as follows https://github.com/ArunChockalingam/temp/blob/master/Screen%20Shot%202019-03-26%20at%207.49.18%20AM.png
```
const myFrame = $('.active iframe');
browser.switchToFrame(myFrame); //throws the error.
```
**To Reproduce**

Have an iframe inside nested divs, select the iframe through the div's classname and call browser.switchToFrame.

**Expected behavior**
Successfully  switch to the Iframe

**Log**
[chrome #0-0] Error: Unsupported frame locator: java.util.HashMap
[chrome #0-0] Error: Unsupported frame locator: java.util.HashMap
[chrome #0-0]     at TestPage.switchToFrame [as switchToIframe] (/Users/arunchockalingam/autoRepo/test/pageobjects/test_page.js:76:17)
[chrome #0-0]     at UserContext.switchToIframe (/Users/arunchockalingam/autoRepo/test/specs/test.specs.js:35:18)

**Additional context**
Also reached out to gitter for help and upgraded webdriverio and the related libraries to the latest version

**Comment by ArunChockalingam** [comment]
We solved it by passing in the name attribute from the selector into the SwitchToFrame method. But passing the element does not work as indicated above

**Comment by BorisOsipov** [comment]
@ArunChockalingam could you point as where in docs 
```
const myFrame = $('.active iframe');
browser.switchToFrame(myFrame);
```

described as solution  to work with iframes?

**Comment by BorisOsipov** [comment]
btw I agree with @ArunChockalingam. `browser.switchToFrame()` wants 

`
id | number, string, object, null | one of three possible types: null: this represents the top-level browsing context (i.e., not an iframe), a Number, representing the index of the window object corresponding to a frame, a string representing an element id. The element must be the frame or iframe to be selected
`

>a string representing an element id

but I didn't see a way how to get elementId from $()

**Comment by ArunChockalingam** [comment]
@BorisOsipov we did `browser.switchToFrame( $('.active iframe').getAttribute('name'));` you could do the same to get id. 

the docs as you pointed out and the gitter community seemed to expect the switchToFrame to accept iframes as input

**Comment by christian-bromann** [comment]
This command is a protocol command so it expects an element id which can be received by doing `$('.active iframe').elementId`.. I can see value having a command that also accepts an element object (similar to `switchWindow`). However I don't see a bug here. We no where state that:
```js
const myFrame = $('.active iframe');
browser.switchToFrame(myFrame);
```
is the way to switch to a frame. Closing.
