### ISSUE TITLE
Should reporters be instantiated as services?

### ISSUE THREAD

**Issue by naddison** [webdriverio/webdriverio#3780]
With the v5 refactor, reporters are now initialized per instance (runner) and only generate reports for the spec file(s) that are run on that instance.

Take junit-reporter for example. Given a run of 10 spec files, I will have 10 separate xml results files. I can combine these after the fact, but it would be nice to have access to all the results inside the reporter.

Would it make sense to convert some reporters into "services" so that they have access to all the test events? Are services even privy to test events (like testStart, testPass, etc).

**Comment by christian-bromann** [comment]
> Would it make sense to convert some reporters into "services" so that they have access to all the test events?

No, but you are right, we should allow reporters to have an onPrepare and onComplete step.

**Comment by naddison** [comment]
Where they are instantiated now they cannot support an onComplete step. Their "life" ends when the runner completes after the onRunnerEnd event is fired. 

And if we send all test events down to each runner, you now have multiple reporters trying to do the same thing on the same files.

**Comment by kmnaid** [comment]
As the reporter does not have access to the "end" event which was available in v4 it's now not possible to aggregate results and make one report after all the instances complete. For cases like the [wdio-slack-reporter](https://github.com/kmnaid/wdio-slack-reporter) where you would want to send the aggregated results in one message it makes sense to re-think of where the reporter may live.
See [issue.](https://github.com/kmnaid/wdio-slack-reporter/issues/3#issuecomment-484344448)

**Comment by kmnaid** [comment]
@christian-bromann : Is there any update about this discussion? Thanks.

**Comment by christian-bromann** [comment]
> Is there any update about this discussion? Thanks.

No updates. I have seen people adding a complementary service to their reporters to achieve these things.
