### ISSUE TITLE
Typing problems

### ISSUE THREAD

**Issue by brochetteoptel** [webdriverio/webdriverio#3798]
1. Is it normal that in JavaScript browserObject.waituntil returns a boolean and that in TypeScript it returns a promise-void?

2. Can waitUntil accept a () => Promise-Boolean in condition parameter?

3. On the same idea in javascript the $ selector may return the element or an Object with an .error but in TypeScript it says 'error' does not exist on type Element

**Comment by christian-bromann** [comment]
@brochetteoptel can you please provide some screenshots with the exact issues you see?

**Comment by brochetteoptel** [comment]
1. In javascript I could do this and "ele" was true if it was found and displayed<br>
![image](https://user-images.githubusercontent.com/46902576/55351270-dc9d6280-548b-11e9-9ccf-568104f0b0d9.png)<br>
but the typing in typescript don't let me do it, it says return void <br>
![image](https://user-images.githubusercontent.com/46902576/55351365-1ff7d100-548c-11e9-8111-cf8021c8e104.png)


2. Let say I want to create a wait Until Selector is found and displayed<br>
![image](https://user-images.githubusercontent.com/46902576/55349988-fe491a80-5488-11e9-9be7-7c8fcd1fbd5a.png)<br>
![image](https://user-images.githubusercontent.com/46902576/55350495-3e5ccd00-548a-11e9-9518-66259ffdb567.png)

3. from $.js<br>
![image](https://user-images.githubusercontent.com/46902576/55349650-38fe8300-5488-11e9-90b6-f25eeed9ae4e.png)<br>
but in typescript i get the error mesasge "Property 'error' does not exist on type 'Element'."<br>
![image](https://user-images.githubusercontent.com/46902576/55352037-efb13200-548d-11e9-8c59-6f5d30b32d35.png)<br>
![image](https://user-images.githubusercontent.com/46902576/55349888-c5a94100-5488-11e9-9d5d-cfa53088d3e4.png)

**Comment by christian-bromann** [comment]
@brochetteoptel why aren't you using `browser.waitForDisplayed()`?

**Comment by CrispusDH** [comment]
@brochetteoptel when you want to insert code just use 
![image](https://user-images.githubusercontent.com/12623263/55355498-22304e80-54d1-11e9-888d-b9e99f741605.png)
it is much more better than screenshots with code :)

**Comment by christian-bromann** [comment]
@CrispusDH do his defense I was asking for screenshot 🤷‍♂️ 

![Screenshot 2019-04-01 at 22 04 23](https://user-images.githubusercontent.com/731337/55356036-2dcc4700-54ca-11e9-82b2-3450e8d3e9be.png)

**Comment by brochetteoptel** [comment]
@christian-bromann `brower.waitForDisplayed()` does not exist... but `element.waitForDisplayed()` fixed my issue thanks 😉 

When I was exploring with webdriverio `waitForDisplayed()` seem not to work fine for me but the problem was probably on my side. 🤷‍♂️ 

But still, shouldn't the code behave the same in js and ts? 

@CrispusDH thanks still getting use to github

**Comment by christian-bromann** [comment]
> But still, shouldn't the code behave the same in js and ts?

Yes. ts is just a different way to write js.

**Comment by ReinAkane** [comment]
@christian-bromann I think this was closed prematurely. On webdriverio@5.12.5 and at the least the issue with `$` typings on errors is not resolved. Specifically this one:
> On the same idea in javascript the $ selector may return the element or an Object with an .error but in TypeScript it says 'error' does not exist on type Element

Should I open a separate issue that's specific to the problems with the typings, as opposed to the problem of waiting for an element to be displayed?
