### ISSUE TITLE
sample code is inconsistent in doc for getSize

### ISSUE THREAD

**Issue by systembugtj** [webdriverio/webdriverio#3799]
**Pre-check**
- [X] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**
![getElementSize should be getSize](https://user-images.githubusercontent.com/777576/55357441-dc986500-5481-11e9-81c9-95ab889cc26a.png)

I'd like to report
- [ ] Unclear documentation
- [X] A typo
- [ ] Missing documentation
- [ ] Other

**Description of the improvement / report**
A clear and concise description.

**Comment by christian-bromann** [comment]
I don't know how you expect anyone to understand what you want to say with this issue post.

**Comment by christian-bromann** [comment]
Next time just write what you expect to see and what you are actually seeing or even better propose a PR.
