### ISSUE TITLE
Microsoft Edge browser cannot be started using Microsoft Edge driver. 

### ISSUE THREAD

**Issue by GineaPig** [webdriverio/webdriverio#3800]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 5.7.0]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync]
 - **Browser name and version:** [e.g. Microsoft Edge 41.16299.1004.0, Microsoft EdgeHTML 16.16299]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**

`capabilities: [{
        maxInstances: 5,
        browserName: 'MicrosoftEdge',

    },
    ],

    seleniumArgs: {
        javaArgs: [
            '-Dwebdriver.edge.driver=path\\MicrosoftWebDriver.exe'

        ]
    },`

**Describe the bug**

The Edge browser cannot be initiated using the Microsoft Edge driver.

**To Reproduce**
just start a simple test using the config above in Microsfot Edge browser and driver.

**Log**

` RUNNING  0-0 in MicrosoftEdge - \test\test.js

Worker Error:
session not created: Unable to create session from {
  "desiredCapabilities": {
    "browserName": "MicrosoftEdge"
  },
  "capabilities": {
    "firstMatch": [
      {
        "browserName": "MicrosoftEdge"
      }
    ]
  }
}
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'
System info: host: '', ip: ', os.name: 'Windows 10', os.arch: '', os.version: '10.0', java.version: '1.8.0_201'

Driver info: driver.version: unknown
    at getErrorFromResponseBody (C:\test\node_modules\webdriver\build\utils.js:343:10)
    at Request._callback (C:\test\node_modules\webdriver\build\request.js:121:64)
    at Request.self.callback (C:\test\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\test\node_modules\request\request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\test\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)

`

**Comment by christian-bromann** [comment]
Join our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue of WebdriverIO and rather a configuration issue.

**Comment by GineaPig** [comment]
It worked before but recently it doesn't work.

**Comment by christian-bromann** [comment]
@GineaPig unfortunately all the information you have provided don't help anyone to give you any clue. Please check that you have the correct version of the driver installed (32 v2 64bit) or provide at least a reproducible example on Travis or something like this.
