### ISSUE TITLE
browser.maximizeWindow() doesn't work for Microsoft Edge browser.

### ISSUE THREAD

**Issue by GineaPig** [webdriverio/webdriverio#3802]
**Environment** (please complete the following information):

WebdriverIO version: [e.g. 5.7.0]
Mode: [WDIO Testrunner]
If WDIO Testrunner, running sync/async: [e.g. sync]
Browser name and version: [e.g. Microsoft Edge 41.16299.1004.0, Microsoft EdgeHTML 16.16299]
Platform name and version: [e.g. Windows 10]
Additional wdio packages used (if applicable): [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**

`capabilities: [{
maxInstances: 5,
browserName: 'MicrosoftEdge',

},
],

seleniumArgs: {
    javaArgs: [
        '-Dwebdriver.edge.driver=path\\MicrosoftWebDriver.exe'

    ]
},`
**Describe the bug**

The test failed with an error of "Unknown command received" when in the line browser.maximizeWindow();

**To Reproduce**
just start a simple test browser.url() and then browser.maximizeWindow() 

**Log**
`[MicrosoftEdge #0-0] Error: Unknown command received

[MicrosoftEdge #0-0]     at getErrorFromResponseBody (C:\test\node_modules\webdriver\build\utils.js:336:12)
[MicrosoftEdge #0-0]     at Request._callback (C:\test\node_modules\webdriver\build\request.js:121:64)
[MicrosoftEdge #0-0]     at Request.self.callback (C:\test\node_modules\request\request.js:185:22)
[MicrosoftEdge #0-0]     at Request.<anonymous> (C:\test\node_modules\request\request.js:1161:10)
[MicrosoftEdge #0-0]     at IncomingMessage.<anonymous> (C:\test\node_modules\request\request.js:1083:12)
[MicrosoftEdge #0-0]     at Browser.runCommand (C:\test\node_modules\@wdio\sync\build\wrapCommand.js:31:24)
[MicrosoftEdge #0-0]     at Browser.<anonymous> (C:\test\node_modules\@wdio\sync\build\wrapCommand.js:53:31)
[MicrosoftEdge #0-0]     at Context.<anonymous> (C:\test\test\test.js:14:17)
[MicrosoftEdge #0-0]     at Promise (C:\test\node_modules\@wdio\sync\build\index.js:58:22)
[MicrosoftEdge #0-0]     at Context.executeSync (C:\test\node_modules\@wdio\sync\build\index.js:56:10)
[MicrosoftEdge #0-0]     at C:\test\node_modules\@wdio\sync\build\index.js:202:70
`
**setWindowRect() for Edge has the same issue.**

**Comment by christian-bromann** [comment]
Please make sure you are using the latest version of [MS Edgedriver](https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/). 
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by areejw** [comment]
I am seeing the same issue. Running the test via browserstack service. What Edgedriver version is picked up when running via browserstack? I have also tried specifying the driver version in capabilities but maximizeWindow() still fails with "unknown command".

**Comment by afsalkh** [comment]
Any update on this.
Facing the same issue with Edge browser. Browserstack is using Edge version 90.
The same code works for other browsers. 
The stack trace is 
```
stacktrace: 'org.openqa.selenium.UnsupportedCommandException: POST /session/39819caae0269fdd3a39274365bd770c8d8defa4/window/maximize\n' +
      "Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'\n" +
      "System info: host: '10-168-33-240', ip: '10.168.33.240', os.name: 'windows', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_181'\n" +
      'Driver info: driver.version: unknown\r\n' +
      '\tat org.openqa.selenium.remote.http.AbstractHttpCommandCodec.decode(AbstractHttpCommandCodec.java:261)\r\n' +
      '\tat org.openqa.selenium.remote.http.AbstractHttpCommandCodec.decode(AbstractHttpCommandCodec.java:117)\r\n' +
      '\tat org.openqa.selenium.grid.session.remote.ProtocolConverter.handle(ProtocolConverter.java:74)\r\n' +
      '\tat org.openqa.selenium.grid.session.remote.RemoteSession.execute(RemoteSession.java:129)\r\n' +
      '\tat org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0(WebDriverServlet.java:235)\r\n' +
      '\tat java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)\r\n' +
      '\tat java.util.concurrent.FutureTask.run(Unknown Source)\r\n' +
      '\tat java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\r\n' +
      '\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\r\n' +
      '\tat java.lang.Thread.run(Unknown Source)\r\n',
    stackTrace: [
      [Object], [Object],
      [Object], [Object]
    ],
    message: 'POST /session/39819caae0269fdd3a39274365bd770c8d8defa4/window/maximize\n' +
      "Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'\n" +
      "System info: host: '10-168-33-240', ip: '10.168.33.240', os.name: 'windows', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_181'\n" +
      'Driver info: driver.version: unknown',
```
    error: 'unknown command'

**Comment by christian-bromann** [comment]
@afsalkh I would reach out to the BS support given that this endpoint is a WebDriver protocol command and suppose to work.

**Comment by afsalkh** [comment]
"browserstack.use_w3c": true
did the trick. Thank you
