### ISSUE TITLE
How can i switch to iframe

### ISSUE THREAD

**Issue by aish-blr** [webdriverio/webdriverio#3803]
The application i am testing has an iframe and button inside the iframe
<iframe id="storybook-preview-iframe" title="main" src="iframe.html?id=undefined" allowfullscreen=""></iframe>

I am not able to interact with the button directly. So I wanted to switch to the inframe first. To do it
I used the code
 browser.switchToFrame('storybook-preview-iframe')
I am seeing error  browser.switchToFrame() is not a function.

Here is the list of packages i am using
"dependencies": {
    "@types/webdriverio": "^5.0.0",
    "chai": "^4.2.0",
    "chai-webdriverio": "^0.4.3",
    "geckodriver": "^1.14.1",
    "html-dnd": "^1.2.0",
    "selenium-webdriver": "^4.0.0-alpha.1"
  }

**Comment by christian-bromann** [comment]
The id (as property) is not supported in the latest spec anymore. Use `browser.switchToFrame($('#storybook-preview-iframe').elementId)`.

**Comment by rajatsm** [comment]
I tried using the above solution. 
browser.switchToFrame($('#storybook-preview-iframe').elementId).
It didn't worked. Still i am seeing error browser.switchToFrame() is not a function.
can you please let me know what version i should use to make it work ?

**Comment by christian-bromann** [comment]
> browser.switchToFrame() is not a function.

This function should be available to all browser:

https://webdriver.io/docs/api/jsonwp.html#switchtoframe
https://webdriver.io/docs/api/webdriver.html#switchtoframe

You need to provide more info!

**Comment by christian-bromann** [comment]
> We are using this version of webdriverio : "webdriverio": "^4.14.0"

And exact this information is missing. For v4 please check the corresponding docs: http://v4.webdriver.io/api/protocol/frame.html

**Comment by rajatsm** [comment]
I checked with v4 it worked perfectly. 
I tried updating my webdriverio to the latest version i.e : 5.7.8.
Even after that i am getting the same error message.
Do i need to update anything else ? what am i missing ...
Please find the versions which i am using .. 
    "chai": "^4.2.0",
    "chai-webdriverio": "^0.4.3",
    "geckodriver": "^1.14.1",
    "html-dnd": "^1.2.0",
    "selenium-webdriver": "^4.0.0-alpha.1",
    "wdio": "^3.0.3"
    "webdriverio": "^5.7.8"

**Comment by christian-bromann** [comment]
> "wdio": "^3.0.3"

Remove this dependency, it is not part of WebdriverIO

**Comment by Antonius-S** [comment]
There's something confusing here. I have WD 5.7.8 with Firefox refused to operate on a frame by name though Chrome allowed this. Contrary to WD docs, I got things working only when I passed the frame object itself as function parameter. `elementId` was refused by driver.
```js
	const LOGINBOX_PATH = '#login-box'; // <iframe id="login-box"...

	await browser.url(LOGIN_URL);

	const frame = await browser.$(LOGINBOX_PATH);

	await browser.switchToFrame(frame); // OK! Firefox and Chrome
	//await browser.switchToFrame(frame.elementId); // Fail! Firefox and Chrome
	await browser.switchToFrame(null); // OK! Firefox and Chrome
	await browser.switchToFrame(0); // OK! Firefox and Chrome
```
[W3C specs](https://w3c.github.io/webdriver/#dfn-switch-to-frame) clearly say id must be null, number or frame object itself

**Comment by ericaprieto** [comment]
Any news about this?

**Comment by tripleratamacue** [comment]
This is all working fine, I tested in v5 to be more specific: 5.16.7
browser.switchtoframe($('.report__iframe'))
doc: https://webdriver.io/docs/api/jsonwp.html#switchtoframe

v4 you can check do Chris already sent:
http://v4.webdriver.io/api/protocol/frame.html

Regards.
@ericaprieto
