### ISSUE TITLE
Docs: v4 Protocols alertAccept is Forbidden

### ISSUE THREAD

**Issue by jsbm** [webdriverio/webdriverio#3805]
I'd like to report
- Missing documentation

**Description of the improvement / report**
the page for v4 Protocols alertAccept is Forbidden

http://v4.webdriver.io/api/protocol/alertAccept.html

**Comment by christian-bromann** [comment]
Thanks for reporting. We are aware that some pages in the v4 docs are corrupted and we are working on getting this fixed. However we recommend to move to v5 as we deprecate v4 at some point.
