### ISSUE TITLE
how can I add many attachments to a step into Allure repor?

### ISSUE THREAD

**Issue by raulcabero** [webdriverio/webdriverio#3806]
Hello I want to add two attachments to a step in allure, basically I want to attach in a failed step an error message and the screenshot, If I create a step for each one it works like this:
```
     addStep(title, {
            content : content,
            name : 'error message',
            type : 'text/plain'
        }, status);
     addStep(title, {
            content : Buffer.from(this.browser.takeScreenshot(), 'base64'),
            name : 'Screenshots',
            type : 'image/png'
        }, status);
```
but I would like to have only one step with the two attachments I tried this but it did not work the result has none attahcment:

     addStep(title, [
        {
            content : content,
            name : 'error message',
            type : 'text/plain'
        },
        {              
            content : Buffer.from(this.browser.takeScreenshot(), 'base64'),
            name : 'Screenshots',
            type : 'image/png'
        }], status);

**Comment by christian-bromann** [comment]
@BorisOsipov ?

**Comment by BorisOsipov** [comment]
Hi @raulcabero 

>how can I add many attachments to a step into Allure report?

Currently nohow

If you confused by docs
>addStep(title, [{content, name = 'attachment'}], [status])

`[]` here means this options is optional, not array of params.

We should think about such API - add way to add several attachements to step.

If everyone wants to make such changes, feel free to make PR.

**Comment by raulcabero** [comment]
Hi @BorisOsipov , ok thanks for the help.

**Comment by BorisOsipov** [comment]
@raulcabero Thanks for feedback :)
also you can use add `addAttachment(name, content, [type])`. It will add attach to test, but  I think it is good workaround.

**Comment by xlenz** [comment]
@BorisOsipov @raulcabero it works for me

code
```
        allureReporter.startStep("my-step")
        allureReporter.addAttachment("attachment-1", "foo")
        allureReporter.addAttachment("attachment-2", "bar")
        allureReporter.endStep("passed")
```

![image](https://user-images.githubusercontent.com/3816609/55555809-63e61280-56e6-11e9-840f-bf8d5962b807.png)

**Comment by xlenz** [comment]
one problem is that it seems to be a bit broken, I'll test with latest code and if it is, I'll raise PR.
