### ISSUE TITLE
possible to highlight element?

### ISSUE THREAD

**Issue by huei90** [webdriverio/webdriverio#381]
Is there any method to highlight element while click/text or any action.

like the selenium ide add-ons Highlight Elements
https://addons.mozilla.org/en-US/firefox/addon/highlight-elements-selenium-id/

If not, how do I customise this.

Thanks for this great work! :smile:

**Comment by christian-bromann** [comment]
@huei90 it's not that easy to do that, sorry

**Comment by huei90** [comment]
I suppose this is a definitely useful features for develop.

Looking forward to hearing from you about this. 

Thanks

**Comment by ctumolosus** [comment]
Hey, so I accomplish this by adding my own custom command to the WebDriverIO instance. I'm relying on jQuery because our site is using it. It could also be done with plain vanilla javascript to ensure compatibility. The background of certain elements cannot be modified, so I get the parent element. But you could also modify it to change the styles of other properties (e.g. border) if you don't want to deal with that.

```js
'use strict';

var _ = require('underscore');
var async = require('async');

var highlight = function (elements, callback) {

    if (!window.jQuery) {
        return callback();
    }

    var unhighlightable = [
        ':checkbox',
        ':radio'
    ];

    var $element = window.jQuery(elements).first();

    for (var i = 0, l = unhighlightable.length; i < l; i++) {

        if ($element.is(unhighlightable[i])) {
            $element = $element.parent();
            break;
        }
    }

    var restore = {
        backgroundColor: $element.css('backgroundColor')
    };

    $element.animate({
        backgroundColor: '#ffff00'
    }, 200, function () {
        $element.delay(100).animate(restore, 200, callback);
    });
};

/**
 * Wait for an element, selected by CSS or XPath selector, for the provided
 * amount of milliseconds to be highlighted with jQuery. If multiple elements
 * get queryied by the given selector, only the first element will be animated.
 * If jQuery is not installed in the host system, nothing happens.
 * @param {String} selector Selector that matches elements to hightlight
 */
module.exports = function (selector) {

    // Make sure that callback contains chainit callback
    var callback = _.last(arguments);

    if (!_.isString(selector)) {
        return callback(new Error('Number or type of arguments do not agree with "highlight" command.'));
    }

    var self = this;
    var timeout = 5000;
    var payload = {};

    async.waterfall([

        function (callback) {
            self.timeoutsAsyncScript(timeout, callback);
        },

        function (response, callback) {
            payload.timeoutsAsyncScript = response;
            self.moveToObject(selector, callback);
        },

        function (value, response, callback) {
            payload.moveToObject = response;
            self.selectorExecuteAsync(selector, highlight, callback);
        }

    ], function (error, value, response) {
        payload.selectorExecuteAsync = response;
        callback(error, payload);
    });
};

```

Then you could do this:

```js
this.client.addCommand('highlight', require('./path/to/above/module'));
this.client.highlight('#element').click('#element');
```

You could also add another command that does both things:

```js
// not tested
module.exports = function (selector) {
    var callback = _.last(arguments);
    async.waterfall([
        this.highlight.bind(this, selector), 
        this.click.bind(this, selector)
    ], callback);
}

// later on...
this.client.addCommand('press', require('path/to/module/that/highlights/and/clicks'));
// later on..
this.client.press('#element');
```

Hope it helps.

**Comment by christian-bromann** [comment]
Created a service that will do that. Will take it from there. Thanks for sharing your code

**Comment by kiransk9** [comment]
Hi,
Can you please let me know if there was any update on highlight functionality. Code snippet would help.
Thank you.

**Comment by christian-bromann** [comment]
> Can you please let me know if there was any update on highlight functionality

There isn't.

> Code snippet would help.

Please see code example above.

**Comment by kiransk9** [comment]
Got it thank you.

**Comment by jpratt2** [comment]
Another option, simpler:

```
    browser.addCommand('highlightElement',function (element){
      browser.execute('arguments[0].style.backgroundColor = "#FDFF47";', element);//provide a yellow background 
      browser.execute('arguments[0].style.outline = "#f00 solid 4px";', element); //provide a red outline
    });  
    
    browser.highlightElement(element);
```

**Comment by erwinheitzman** [comment]
@jpratt2 FYI you can even utilize the `onCommand` hook to automatically apply this if the command name is `click` for example. Just a quick tip 😉

**Comment by StuMinch** [comment]
> Another option, simpler:
> 
> ```
>     browser.addCommand('highlightElement',function (element){
>       browser.execute('arguments[0].style.backgroundColor = "#FDFF47";', element);//provide a yellow background 
>       browser.execute('arguments[0].style.outline = "#f00 solid 4px";', element); //provide a red outline
>     });  
>     
>     browser.highlightElement(element);
> ```

Super helpful. Thank you!

**Comment by Jayaseelanramalingam** [comment]
When I was using highlightElement ( element ) function, getting unexpected token error in browser.addCommand().
Kindly help me for the same.
