### ISSUE TITLE
Error on setCookie?

### ISSUE THREAD

**Issue by huei90** [webdriverio/webdriverio#382]
When using `.setCookie({"lang": "en"})`

I get this error

```
Uncaught RuntimeError
     (UnknownError:13) An unknown server-side error occurred while processing the command.
     Problem: Required attributes are not set or any non-null attribute set to null

     Callstack:
     -> cookie("POST",{"lang":"en"})
     -> setCookie({"lang":"en"})
```

How do I fix this.

**Comment by fat-troll** [comment]
Seems like not a webdriverio problem

https://code.google.com/p/selenium/source/diff?spec=svn546209825f8dab6e5a222e5b93f9e3265eb9b6f7&r=546209825f8dab6e5a222e5b93f9e3265eb9b6f7&format=side&path=/java/client/src/org/openqa/selenium/Cookie.java

Do youi have lower version of Selenium?

**Comment by christian-bromann** [comment]
@huei90 what browser/OS combination?
@fat-troll it's time to update the standalone browser in the build to catch these problems O.o

**Comment by fat-troll** [comment]
Hmm, is that syntax in your example is correct? Documents tell that we should use
```javascript
.setCookie({name: 'lang', value: 'en'})
```

and for me that works perfectly

**Comment by christian-bromann** [comment]
@huei90 the cookie object needs to have a `name` and `value` attribute. See [`setCookie`](http://webdriver.io/api/cookie/setCookie.html)

@fat-troll thanks!
