### ISSUE TITLE
npm vulnerability from outdated version of js-yaml 

### ISSUE THREAD

**Issue by thelgevold** [webdriverio/webdriverio#3820]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2]
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:** [e.g. 8.11.2]
 - **NPM version:** [e.g. 5.8.0]
 - **Browser name and version:** [e.g. Chrome 68]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
Getting an npm vulnerability from outdated version of js-yaml in the latest version
@wdio/mocha-framework: 5.7.8

**To Reproduce**
run an npm install of version 5.7.8

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by baruchvlz** [comment]
[None](https://github.com/webdriverio/webdriverio/search?q=js-yaml&type=Code) of the WDIO packages use `js-yaml` as a dependency. This might be coming from another package outside of this library.

**Comment by thelgevold** [comment]
Ah Ok. Probably just have to upgrade one the WDIO dependencies dependencies then.
Running `npm ls js-yaml` should reveal which one.

**Comment by christian-bromann** [comment]
`js-yaml` is used by Mocha and they have fixed it already but haven't released it yet.

**Comment by tadashi0713** [comment]
https://github.com/webdriverio/webdriverio/pull/3856
@christian-bromann We already merged this PR, so I believe this problem is solved
