### ISSUE TITLE
Logs not outputting in real-time + duplication at end 

### ISSUE THREAD

**Issue by klamping** [webdriverio/webdriverio#3826]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.7.10
 - **Mode:** Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v8.11.3
 - **NPM version:** 6.8.0
 - **Browser name and version:** Chrome 73.0.3683.86/Firefox 65.0.1
 - **Platform name and version:** OSX 10.13.6
 - **Additional wdio packages used (if applicable):**
```
"@wdio/local-runner": "^5.7.9",
"@wdio/mocha-framework": "^5.7.8",
"@wdio/selenium-standalone-service": "^5.7.8",
"@wdio/spec-reporter": "^5.7.9",
"@wdio/sync": "^5.7.9"
```

**Config of WebdriverIO**
https://github.com/klamping/wdio-log-issue/blob/master/wdio.conf.js

**Describe the bug**
Two issues:
1. Most of the messages don't log until the end
2. I'm still getting some duplication at the end

![](https://thumbs.gfycat.com/OptimalAngelicAardwolf-size_restricted.gif)
Full version: https://gfycat.com/ifr/OptimalAngelicAardwolf

**To Reproduce**
1. Download/Clone https://github.com/klamping/wdio-log-issue
2. `npm install`
3. `npx wdio`

**Expected behavior**
Logs output as steps are completed, no duplicate logs at the end

**Additional context**
Tried this using iTerm 2, Build 3.2.8, run through oh-my-zsh. Also was able to duplicate the issue using just Mac's Terminal

Related PR
https://github.com/webdriverio/webdriverio/pull/3638

**Comment by vgrigoruk** [comment]
Output looks very bad when you run tests on CircleCI. There is a lot of duplication and `CI=true` env variable is not respected for some reason.
See example job here: https://circleci.com/gh/vgrigoruk/wdio-circleci-example/4
Source code is here: https://github.com/vgrigoruk/wdio-circleci-example

**Comment by christian-bromann** [comment]
I guess we need to check CI using https://github.com/watson/ci-info#ci-info

**Comment by SubJunk** [comment]
Just to add to the comment about Circle-CI, my builds fail on Travis recently because of the logspam. Travis ends with:

`The job exceeded the maximum log length, and has been terminated.`

It started happening sometime between 5.4 (which is the version I'm successfully still using) and 5.7

I'd be happy to make a different issue for it if this is too off topic.

**Comment by luckyincode** [comment]
@SubJunk The default time a travis build can run is 50 minutes.  So likely that's the failure there.

**Comment by SubJunk** [comment]
There are full logs from one of the failed runs at https://api.travis-ci.com/v3/job/193550784/log.txt
Travis says the job ran for 1m51s, and I was watching it at the time so that seems accurate, definitely not longer than a few minutes.
There's a lot of detail in the logs so maybe I'm wrong but it seems that there is only about 90 seconds between the first and last timestamps and it's printing a log every 0.1s, e.g.

```
Test Suites:	 [32m0 passed[39m, 6 total (0% completed)
Time:		 ðŸ•›  3.71s
[?25l[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
[43m[30mRUNNING [39m[49m 0-0 in chrome - /test/specs/collections.spec.js
[33m... 5 pending test suites[39m

Test Suites:	 [32m0 passed[39m, 6 total (0% completed)
Time:		 ðŸ•  3.81s
[?25l[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
[43m[30mRUNNING [39m[49m 0-0 in chrome - /test/specs/collections.spec.js
[33m... 5 pending test suites[39m

Test Suites:	 [32m0 passed[39m, 6 total (0% completed)
Time:		 ðŸ•‘  3.91s
[?25l[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
[43m[30mRUNNING [39m[49m 0-0 in chrome - /test/specs/collections.spec.js
[33m... 5 pending test suites[39m
```

5.4 still works nicely so I'm sticking with that and trying newer ones as they're released.

**Comment by SubJunk** [comment]
Probably this https://github.com/webdriverio/webdriverio/issues/3867

**Comment by SubJunk** [comment]
I spent some time looking into this today and found the behaviour change happened in `wdio-cli` 5.7.9 so I think it is likely related to https://github.com/webdriverio/webdriverio/pull/3638

**Comment by CrispusDH** [comment]
In my work project I have `try ... catch` construction. In console at the end:
1. I see these errors (if it were during test) in `Stderr` section. I'm not sure that I want it because definitely I want to hide them.
2. `Stdout` and `Stderr` duplicate three times in console.

**Comment by SubJunk** [comment]
Confirmed my issue is still happening in `5.8.1`

**Comment by ericzered** [comment]
Hello, I have this issue about logs from console.log() not outputting in real time but I didn't get how to make a work around, can you explain me ? Thanks

**Comment by mgrybyk** [comment]
wait for the fix!

**Comment by ericzered** [comment]
> wait for the fix!

ok, good luck for the fix and thanks for the good job !
