### ISSUE TITLE
Screenshot is created too late

### ISSUE THREAD

**Issue by balukov** [webdriverio/webdriverio#3827]
I has this type of problem:
```
** test.ts **

afterEach(() => {
  do2
})

it(()=> {
  do1
  expect(smth)
})

** wdio.conf **

afterTest: function(test) {
  if (test.error !== undefined) {
    browser.takeScreenshot();
  }
}
```
If test fail after expect(smth) I see the screenshot after do2.
This is bad because app has not actual state.
How can I has screenshot right after expect or other falling step?
Unfortunately "expect" is not wdio command and I can't do `browser.takeScreenshot()` in `afterCommand` hook.
Maybe hook `afterTest` should works before `afterEach`?

**Comment by christian-bromann** [comment]
> I can't do `browser.takeScreenshot()` in `afterCommand` hook.

You can!

> How can I has screenshot right after expect or other falling step?

The afterTest hook is executed before the afterEach hook in the test. So I don't see a reason why this shouldn't work.
