### ISSUE TITLE
.execute() failure with v2.4 upgrade ...

### ISSUE THREAD

**Issue by blobhouse** [webdriverio/webdriverio#383]
Hello, 

I just updated to v2.4.0, and am seeing a weird problem.

When we call `client.execute(function)` with none of the optional arguments, the provided function is not sent to execute in the browser.  Instead, selenium sends this callback method from line 159 of lib/utils/PromiseHandler.js:

`
function(error, value) {
            var newArgs = array_slice(arguments);
            if(callback) {
                callback.apply(self, newArgs);
            } else if(error && !hasErrorHandling) {
                throw error;
            }
            if (error) {
                deferred.reject(error);
            } else if (arguments.length > 2) {
                deferred.resolve(array_slice(arguments, 1));
            } else {
                deferred.resolve(value);
            }
        }
`

This fails with `Exception: array_slice is not defined`.   (Reading PromiseHandler.js, I get the impression array_slice is defined on the Node side, not in the browser.)

If we call client.execute(function, undefined), then all behaves properly.  This appears to be a problem with every invocation of execute(function) in our tests.  We're reverting to 2.3 for now.

**Comment by fat-troll** [comment]
I found out that in the latest version of webdriverio if you define function() or return anything, but not undefined in execute(), you should always "catch" the callback. If you dont need it, you can just add "function(){}" and it works perfectly. Sure, error is very strange and should be fixed, but I think the behaviour is not so wrong as seems to be.

**Comment by christian-bromann** [comment]
I missed that case when implementing the PromiseHandler. I've added a test to make sure that never happens again.
