### ISSUE TITLE
$ and $$ is not defined if I use webdriverio with different test runner

### ISSUE THREAD

**Issue by CrispusDH** [webdriverio/webdriverio#3831]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [5.7.9]
 - **Mode:** [Standalone mode]
 - **running sync/async:** [async]
 - **Node.js version:** [e.g. 11.7.0]
 - **NPM version:** [e.g. 6.9.0]
 - **Browser name and version:** [Chrome 74]
 - **Platform name and version:** [MacOS]

**Describe the bug**
I see an error `$$ is not defined` or `$ is not defined` when use `$` or `$$` in some Page Object files. I want to notice that it code works when I use the same code with Webdriver TestRunner. I'm not sure how to fix it but I feel that it should be simple :). It would be great if you can help me.

**To Reproduce**
- clone repo https://github.com/CrispusDH/wdio-ava-selenoid
- install dependencies `npm i`
- run tests `npm run test`

**Expected behavior**
All global `webdriverio` variables should be defined

**Log**
```js
  ReferenceError {
    message: '$$ is not defined',
  }
```

**Comment by christian-bromann** [comment]
@CrispusDH the globals are only populated using the wdio testrunner. The [docs](https://webdriver.io/docs/api/browser/$.html) say:

> Using the wdio testrunner this command is a global variable else it will be located on the browser object instead.
