### ISSUE TITLE
Unable to access file in project workspace when running tests on browserStack

### ISSUE THREAD

**Issue by AutomationGuru** [webdriverio/webdriverio#3838]
**Environment (please complete the following information):**
 - **WebdriverIO version:** ["webdriverio": "^5.7.8"]
 - **Mode:** [Standalone mode/ WDIO Testrunner/BROWSERSTACK]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [10+]
 - **NPM version:** [6.4.1]
 - **Browser name and version:** [Chrome 73]
 - **Platform name and version:** [mac]

**Config of WebdriverIO**
The framework is currently using Browserstack service with the user and key and the service updated as browserstack. The test run remotely on browserstack.

**Describe the bug**
We need to upload a test file on the remote browser when the test runs. 
when the test run, the workspace with the test file are not accessible to the remote browserstack VM and hence the upload of test fails. 

**To Reproduce**
- Create a test file : example.png in your project. 
- Make sure you can run you test against browserstack and your wdio is configured to do so,
- Given i navigate to a website, which has an input box(file tag) to upload an image
- on the input box, using setValue add the absolute path of the  test file created in step 1, this will fail to be recognised as on browserstack VM the file does not exists. 

Given i also add browser.setFileDetector(..) its indicated that the browser does not support that

**Expected behavior**
This can be overcome easily if we can please set the `driver.setFileDetector(new remote.FileDetector);` but i fail to see the support for the same on global.browser or global.driver.
If this is set, selenium will use the test file to upload wherever the browser is run remotely. 
This can be done with node js, but currently not possible with webdriverIO. Example 
https://www.browserstack.com/automate/node#enhancements-uploads-downloads

**Additional context**

**Comment by Biswajeet11** [comment]
please update me when this issue is resolved @AutomationGuru

**Comment by christian-bromann** [comment]
This needs to get finished for this https://github.com/webdriverio/webdriverio/pull/3632

**Comment by christian-bromann** [comment]
This is done with the new upload command. For more info, see https://webdriver.io/blog/2019/06/25/file-upload.html

**Comment by AutomationGuru** [comment]
@christian-bromann thanks for fixing it works fine on 5.11.7, saves 30-40 seconds on each test which were using a hack to download the fixture file ! Thank you so much !
