### ISSUE TITLE
Cannot connect to Selenium Grid using the test runner

### ISSUE THREAD

**Issue by rodrigo-garcia-leon** [webdriverio/webdriverio#3842]
**Environment:**
 - **WebdriverIO version:** 5.17.2
 - **Mode:** WDIO Testrunner
 - **Node.js version:** 8.15.1
 - **NPM version:** 6.9.0
 - **Platform name and version:** macOS Mojave 10.14.3
 - **Selenium Grid version:** 3.14.0

**Config of WebdriverIO**
Note: `hostname` left empty on purpose.

```js
exports.config = {
    protocol: 'https',
    hostname: '',
    port: 443,
    path: '/wd/hub',

    runner: 'local',
    specs: [ './test/spec/grid.js' ],
    exclude: [],
    maxInstances: 1,
    capabilities: [{
        maxInstances: 1,
        browserName: 'chrome',
        platform: 'ANY'
    }],
    logLevel: 'error',
    bail: 0,
    baseUrl: '',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    }
};

```

**Describe the bug**
WebdriverIO cannot create a session with Selenium Grid since W3C capabilities are not supported by Selenium Grid. The following exception appears on the response body:

```java
Caused by: org.openqa.grid.common.exception.GridException: Cannot extract a capabilities from the request: {
                &quot;capabilities&quot;: {
                                &quot;alwaysMatch&quot;: {
                                                &quot;browserName&quot;: &quot;chrome&quot;,
                                                &quot;platform&quot;: &quot;ANY&quot;
                                },
                                &quot;firstMatch&quot;: [{}]
                },
                &quot;desiredCapabilities&quot;: {
                                &quot;browserName&quot;: &quot;chrome&quot;,
                                &quot;platform&quot;: &quot;ANY&quot;
                }
}
```

When using the test runner the session is created using the `newSession` function in the file `packages/webdriver/src/index.js`, which adds the W3C capabilities.

**To Reproduce**
Try to run a spec file using a Selenium Grid and the test runner.

**Expected behavior**
I expect to be able to run tests using the test runner.

**Comment by christian-bromann** [comment]
I can't reproduce the issue:

__wdio.conf.log__
```
2019-04-12T09:33:29.776Z INFO webdriver: [POST] http://0.0.0.0:4444/wd/hub/session
2019-04-12T09:33:29.778Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { browserName: 'chrome' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'chrome' } }
2019-04-12T09:33:31.666Z INFO webdriver: COMMAND navigateTo("http://json.org/")
2019-04-12T09:33:31.667Z INFO webdriver: [POST] http://0.0.0.0:4444/wd/hub/session/f0662e17349d3861c7c68af81bf6aa89/url
2019-04-12T09:33:31.667Z INFO webdriver: DATA { url: 'http://json.org/' }
2019-04-12T09:33:32.724Z INFO webdriver: COMMAND deleteSession()
2019-04-12T09:33:32.725Z INFO webdriver: [DELETE] http://0.0.0.0:4444/wd/hub/session/f0662e17349d3861c7c68af81bf6aa89
```

__selenium-standalone.log__
```
java -jar selenium.jar -role node -hub http://localhost:4444/grid/register -port 5555
11:33:26.937 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
11:33:27.018 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Launching a Selenium Grid node on port 5555
2019-04-12 11:33:27.099:INFO::main: Logging initialized @343ms to org.seleniumhq.jetty9.util.log.StdErrLog
11:33:27.264 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
11:33:27.388 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 5555
11:33:27.388 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Selenium Grid node is up and ready to register to the hub
11:33:27.426 INFO [SelfRegisteringRemote$1.run] - Starting auto registration thread. Will try to register every 5000 ms.
11:33:27.703 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://localhost:4444/grid/register
11:33:27.722 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to use
11:33:29.867 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "chrome"
}
11:33:29.868 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189) on port 6900
Only local connections are allowed.
11:33:31.304 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
11:33:31.629 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session f0662e17349d3861c7c68af81bf6aa89 (org.openqa.selenium.chrome.ChromeDriverService)
11:33:32.793 INFO [ActiveSessions$1.onStop] - Removing session f0662e17349d3861c7c68af81bf6aa89 (org.openqa.selenium.chrome.ChromeDriverService)
```

**Comment by thulasipavankumar** [comment]
Facing the same issue
webdriverio: 5.8.3
selenium version : 3.14.0
npm: 6.4.1
node: v10.15.1
### WebDriverIO error log
ERROR webdriver: Request failed due to Error: Response has empty body

### Selenium error log
java.io.IOException: org.openqa.grid.common.exception.GridException: Cannot extract a capabilities from the request: {"capabilities":{"alwaysMatch":{"browserName":"chrome","version":74,"platform":"WINDOWS"},"firstMatch":[{}]},"desiredCapabilities":{"browserName":"chrome","version":74,"platform":"WINDOWS"}}

### webdriverio config file
exports.config = {
    runner: 'local',
     hostname:'10.243.80.182',
    protocol:'http',
    port:4444,
    path: '/wd/hub',
    specs: [
        './test/specs/**/*.js'
    ],
    exclude: [
        // 'path/to/excluded/files'
    ],
    maxInstances: 1,
    capabilities: [{
        'browserName': 'chrome',
       'version':74,
    'platform':'WINDOWS'
    }],
    logLevel: 'error',
    bail: 0,
    baseUrl: '',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 1,
    reporters: [],
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },

}

**Comment by thulasipavankumar** [comment]
@rodrigo-garcia-leon 
From my observation i have understood the only selenium supported capabilities are listed [here](https://www.w3.org/TR/webdriver/#capabilities)
instead use this in your config file
```
capabilities: [{
        browserName: 'chrome',
        platformName: 'ANY'
    }],
```

**Comment by tulasirm** [comment]
can anyone guide why i am getting this issue, i have a selenium grid hub with Android devices, but somehow session not getting created, unfortunately i am not able to find any example for this
here is the log that i am getting:

[0-0] 2019-06-12T19:01:30.416Z INFO webdriver: [POST] http://18.237.225.48:80/wd/hub/session
[0-0] 2019-06-12T19:01:30.416Z INFO webdriver: DATA { capabilities:
    { alwaysMatch:
       { browserName: 'chrome',
         platformName: 'ANDROID',
         deviceName: 'SAMSUNG' },
      firstMatch: [ {} ] },
   desiredCapabilities:
    { browserName: 'chrome',
      platformName: 'ANDROID',
      deviceName: 'SAMSUNG' } }
[0-0] 2019-06-12T19:01:30.483Z DEBUG webdriver: request failed due to missing body

Stderr:
[0-0] 2019-06-12T19:01:30.270Z WARN webdriver: Request failed due to Response has an empty body

here is my configfile:

const wdioConfig = require('./wdio.mocha.master.conf.js').config;

const webConfig = {
    ...wdioConfig,
    baseUrl: 'https://tos-shop-dev.stg.kube.t-mobile.com/cell-phones',
    specs: [
        './test/specs/shopUnoHome.spec.ts'
    ],
    maxInstances: 1,
    protocol: 'http',
    hostname: '18.237.225.48',
    port: 80,
    //path: '/wd/hub',
    capabilities: [{
        browserName: 'chrome',
        platformName: 'ANDROID',
        deviceName:'SAMSUNG'
    }],
}
exports.config = webConfig;

**Comment by mgrybyk** [comment]
Hey @tulasirm, as it have been mentioned, you can't use custom capabilities, for more information see https://www.w3.org/TR/webdriver/#capabilities

Your custom (appium) capabilities should be prefixed.
```
"appium:platformVersion": "Android",
"appium:udid": "...",
"appium:deviceName": "Pixel 4"
```

NOTE: you might also need to use custom capability matcher for your grid server, but it depends.

**Comment by Kaidenintelligible6** [comment]
> Facing the same issue webdriverio: 5.8.3 selenium version : 3.14.0 npm: 6.4.1 node: v10.15.1
> 
> ### WebDriverIO error log
> ERROR webdriver: Request failed due to Error: Response has empty body
> 
> ### Selenium error log
> java.io.IOException: org.openqa.grid.common.exception.GridException: Cannot extract a capabilities from the request: {"capabilities":{"alwaysMatch":{"browserName":"chrome","version":74,"platform":"WINDOWS"},"firstMatch":[{}]},"desiredCapabilities":{"browserName":"chrome","version":74,"platform":"WINDOWS"}}
> 
> ### webdriverio config file
> exports.config = { runner: 'local', hostname:'10.243.80.182', protocol:'http', port:4444, path: '/wd/hub', specs: [ './test/specs/**/*.js' ], exclude: [ // 'path/to/excluded/files' ], maxInstances: 1, capabilities: [{ 'browserName': 'chrome', 'version':74, 'platform':'WINDOWS' }], logLevel: 'error', bail: 0, baseUrl: '', waitforTimeout: 10000, connectionRetryTimeout: 90000, connectionRetryCount: 1, reporters: [], mochaOpts: { ui: 'bdd', timeout: 60000 },
> 
> }





https://stackdev.space/questions/grid-cannot-establish-a-connection-with-the-node
