### ISSUE TITLE
Unable to use chai-webdriverio assertions after moving Webdriver v5

### ISSUE THREAD

**Issue by aish-blr** [webdriverio/webdriverio#3847]
I using following packages
"chai": "^4.2.0",
 chai-webdriverio": "^1.0.0",
 "@types/webdriverio": "^5.0.0"

Added  before: function() {
            var chai = require('chai');
            global.expect = chai.expect;
            chai.expect();
        }
    in wdio.conf.js

This is the piece of code in my script
it('Should render button with default properties and styling', function () {    
        storyBook.switchToiFrame();
        var isEnabled= button.primaryButton.isEnabled()
        expect(isEnabled).to.be.true;   _//chai-assertion
        expect('button[class="hcl-btn hcl-btn-primary"]').to.be.there(); _//chai-webdriverio-assertion
})

The first expect passed. The second expect which is a webdriverio specific chai assertion is failing. Attached screenshot of terminal output.

The same code was working when I was using Webdriver V4

**Comment by christian-bromann** [comment]
v5 support was added here: https://github.com/marcodejongh/chai-webdriverio/pull/50 please update you chai-webdriverio package. If you still encounter issues, please raise an issue in that project. Thanks!
