### ISSUE TITLE
Testrunner certain files

### ISSUE THREAD

**Issue by elliotlings** [webdriverio/webdriverio#3852]
Apologies if the terminology I am using is incorrect.

I have some unit tests which do not require the browser, however, the testrunner appears to launch a new instance for each test file/spec.

What is the best way to get around this? Is it better than I run webdriver tests and mocha tests separately?

webdriverio@^4.12.0
wdio-mocha-framework@^0.5.13

**Comment by christian-bromann** [comment]
> What is the best way to get around this? Is it better than I run webdriver tests and mocha tests separately?

Yes, run unit tests first and if they pass run e2e tests. Never both together nor in a different order.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
