### ISSUE TITLE
Node RAM Usage increase by using .getHTML in endless loop

### ISSUE THREAD

**Issue by arenacheck** [webdriverio/webdriverio#3853]
# Issue description
> I have a node.js bot which gets data from pages and on each page we use getHTML. I always restart the script with a new loop with process.nextTick like below and then fetch again the new HTML from the page.

The code below is just a sample. In my original script I did in between steps like saving data to databases.

I figured out that my scripts get always increased memory over time and it gets only caused by fetching the HTML with getHTML! The code below should show/reproduce the problem.

The problem comes on any WDIO version for me!

Did I write wrong endless loops?
Is there a memory leak in getHTML?
How do I write correctly a endless loop with getHTML if my writing is wrong?

# Steps to reproduce
```javascript
             getfreshHTML();
    function getfreshHTML(){

       client.getHTML(':root').then(function(data) {
            $ = cheerio.load(data);
            process.nextTick( getfreshHTML );
       }); 

     } 

```

# Expected behavior
> Always comes with getHTML in endless loop usage.

# Actual behavior
> Memory increase endless.

# Issue occurred on browser/platform 
> Node.js on all platforms! Windows, Linux & MAC

**Comment by christian-bromann** [comment]
Since you didn't provide a WebdriverIO version number I assume you are running v4 in which we store past result in the browser object which an cause an increase in memory usage. Update to v5 and this issue will be gone.
