### ISSUE TITLE
Broken link on `docs/api.html`

### ISSUE THREAD

**Issue by PicoCreator** [webdriverio/webdriverio#3854]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

The broken link is inside the template, and not the markdown itself. See: https://github.com/webdriverio/webdriverio/blob/master/docs/API.md

**Describe the improvement**

I'd like to report
- [x] Other

**Description of the improvement / report**

The following is the replication steps (in Uilicious)

```
// 🌐 Lets load up from webdriver.io
I.goTo("https://webdriver.io")
I.click("API")

// 😎 Lets check the api.html page
I.amAt("https://webdriver.io/docs/api.html")
I.see("API DOCS");
I.see("Make sure you understand the way we write these docs by checking the Contribute section.")

// 👉 Lets click on the link, and make sure its alright
I.click("WEBDRIVER PROTOCOL")
I.dontSee("404 Not Found")
```

Replay link: https://snippet.uilicious.com/test/public/BEyxBxyAF1yH9r5YVz3KUz

[![webdriver-io-doc-bug](https://user-images.githubusercontent.com/17175484/56175307-417ac000-6029-11e9-8fb9-fbb17371d3cd.gif)](https://snippet.uilicious.com/test/public/BEyxBxyAF1yH9r5YVz3KUz)

**Comment by mgrybyk** [comment]
@PicoCreator looks like the issue has been fixed.
