### ISSUE TITLE
switchToFrame No longer excepts 'object' and now fails on FireFox

### ISSUE THREAD

**Issue by Ad1B3nAr0ya** [webdriverio/webdriverio#3860]
**Environment (please complete the following information):**
 - **WebdriverIO version: 5.7.9** 
 - **Mode: Standalone mode** 
 - **If WDIO Testrunner, running sync/async: sync** 
 - **Node.js version: v10.11.0**
 - **NPM version: 6.9.0** 

**Describe the bug**
Passing Element object in switcToFrame now fails on FireFox

**To Reproduce**
code: 
browser.switchToFrame($(selector))

**Expected behavior**
 "/session/:sessionId/frame": {
    "POST": {
      "command": "switchToFrame",
      "description": "The Switch To Frame command is used to select the current top-level browsing context or a child browsing context of the current browsing context to use as the current browsing context for subsequent commands.",
      "ref": "https://w3c.github.io/webdriver/#dfn-switch-to-frame",
      "parameters": [{
        "name": "id",
        "type": "(number|**object**|string|null)",
        "description": "one of three possible types: null: this represents the top-level browsing context (i.e., not an iframe), a Number, representing the index of the window object corresponding to a frame, a string representing an element id that can be received using `findElement`.",
        "required": true
      }]
    }

**Additional context**
PR it was changed: 
https://github.com/webdriverio/webdriverio/commit/7364ceb10249b961e4f8a7a2fa96c612447e0cd8

**Comment by mgrybyk** [comment]
@Ad1B3nAr0ya can this one be closed?

**Comment by christian-bromann** [comment]
I think it can
