### ISSUE TITLE
Webdirverio commands not working.

### ISSUE THREAD

**Issue by srishti77** [webdriverio/webdriverio#3863]
I am using Webdriverio(5.7.14), node(v8.12.0) and npm(6.4.1).  I am trying to test simple Android application's button click operation. My code is given below and I am getting "**client.click() is not a function error**"
 
        const wdio = require('webdriverio');
        const assert = require('chai').assert;
        const path = require('path')

        const opts = {
              port: 4723,
              capabilities: {
                     platformName: "Android",
                     platformVersion: "8.1.0",
                     deviceName: "device_name",
                     app: "/Users/simvelop/Desktop/webdriverio/appdemo.apk",
                     automationName: "UiAutomator2"
              }
           };

            const client = wdio.remote(opts);

         describe('Start Testing', function () {

           it('should create a session', async function () {
  	             console.log("Create session")
                     client.click('android=new UiSelector().resourceId("some_id")');
                 });
        });

Any help would be highly appreciated. Thank you.

**Comment by christian-bromann** [comment]
`wdio.remote(opts)` returns a promise and you need to wait until it resolves. Please check out our [docs](https://webdriver.io/docs/gettingstarted.html) to get started. Thanks!

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
