### ISSUE TITLE
sauce-service does not set test result on Sauce RDC

### ISSUE THREAD

**Issue by ragog** [webdriverio/webdriverio#3864]
**Environment**
 - **WebdriverIO** version: 5.7.6
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 11.14.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Chrome 73
 - **Platform name and version:** Different Android versions
 - **Additional wdio packages used (if applicable):** 
    "@wdio/cli": "^5.7.6",
    "@wdio/jasmine-framework": "^5.7.6",
    "@wdio/local-runner": "^5.7.6",
    "@wdio/sauce-service": "^5.7.8",
    "@wdio/spec-reporter": "^5.7.2",
    "@wdio/sync": "^5.7.6",

**Config of WebdriverIO**
See https://github.com/webdriverio/appium-boilerplate, only changes are in the two attached files: [config.zip](https://github.com/webdriverio/webdriverio/files/3090458/config.zip)

**Describe the bug**
Test result is not set on Sauce Labs RDC using sauce-service 5.7.8.

**To Reproduce**
1. `export SAUCE_RDC_EU_ACCESS_KEY_ANDROID_WDIO=<SAUCE_RDC_API_KEY>`
2. `npm run android.sauce.rdc.app`
3. log into Sauce Labs RDC, visualise test results

**Expected behavior**
The tests are executed and their status is set to either "passed" or "failed", showing also in the respective icons.

**Log**
https://gist.github.com/ragog/80c3036c53dfc33ec352d37a0d1aa837
Not sure whether the above is enough. Happy to provide more.

**Comment by christian-bromann** [comment]
fixed by https://github.com/saucelabs/node-saucelabs/pull/55

**Comment by wswebcreation** [comment]
@ragog 

As @christian-bromann said, it's just fixed.

- remove `node_modules`
- remove `package|yarn-lock.json`
- `npm i | yarn install`

And it should work
