### ISSUE TITLE
 When loglevel for specific loggers are set to silent, info and debug logs appear

### ISSUE THREAD

**Issue by kmnaid** [webdriverio/webdriverio#3867]
**Environment:**
 - **WebdriverIO version:** @wdio/cli@5.7.14
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v10.15.2
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome Version 73.0.3683.86 
 - **Platform name and version:** OSX 10.14.4 
 - **Additional wdio packages used (if applicable):** 
```
├─┬ @wdio/cli@5.7.14
│ ├─┬ @wdio/config@5.7.13
│ │ ├── @wdio/logger@5.7.8 deduped
│ ├─┬ @wdio/logger@5.7.8
│ ├─┬ @wdio/utils@5.7.8
│ │ ├── @wdio/logger@5.7.8 deduped
│ │ ├── @wdio/config@5.7.13 deduped
│ │ ├── @wdio/logger@5.7.8 deduped
│ │ ├── @wdio/repl@5.7.13 deduped
│ │   ├── @wdio/config@5.7.13 deduped
│ │   ├── @wdio/logger@5.7.8 deduped
├─┬ @wdio/dot-reporter@5.7.8
│ ├── @wdio/reporter@5.7.8 deduped
├─┬ @wdio/local-runner@5.7.14
│ ├── @wdio/logger@5.7.8 deduped
│ ├─┬ @wdio/repl@5.7.13
│ │ └── @wdio/config@5.7.13 deduped
│ ├─┬ @wdio/runner@5.7.14
│ │ ├── @wdio/config@5.7.13 deduped
│ │ ├── @wdio/logger@5.7.8 deduped
│ │ ├── @wdio/utils@5.7.8 deduped
├─┬ @wdio/mocha-framework@5.7.14
│ ├── @wdio/config@5.7.13 deduped
│ ├── @wdio/logger@5.7.8 deduped
├─┬ @wdio/reporter@5.7.8
├─┬ @wdio/sauce-service@5.7.8
│ ├── @wdio/logger@5.7.8 deduped
├─┬ @wdio/selenium-standalone-service@5.7.8
├─┬ @wdio/spec-reporter@5.7.13
│ ├── @wdio/reporter@5.7.8 deduped
├─┬ @wdio/sync@5.7.13
│ ├── @wdio/config@5.7.13 deduped
│ ├── @wdio/logger@5.7.8 deduped
├── eslint-plugin-wdio@5.7.8
```

**Config of WebdriverIO**
```
logLevel: 'silent',
logLevels: {
        webdriver: 'silent',
        webdriverio: 'silent',
        'wdio-local-runner': 'silent',
        'wdio-cli': 'silent',
        'wdio-sauce-service': 'silent',
        'wdio-utils': 'silent'
    }
``` 

**Describe the bug**
loglevels are set to silent but info and debug logs still appear on the console.
This is the case with `loglevel` set to silent or not set at all.

**To Reproduce**
With the above loglevels set run a test.

**Expected behavior**
No info or debug logs should appear on the console when loglevel is specific loggers are set to silent.

**Log**
```
> wdio example/wdio.conf.js
2019-04-18T18:54:01.530Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "sauce"
2019-04-18T18:54:01.606Z INFO @wdio/cli:Launcher: Run onPrepare hook
2019-04-18T18:54:01.609Z INFO @wdio/local-runner: Start worker 0-0 with arg: example/wdio.conf.js

Test Suites:	 2 passed, 2 total (100% completed)
Time:		 🕒  27.42s
```

**Comment by SubJunk** [comment]
Likely caused by https://github.com/webdriverio/webdriverio/pull/3565/files

**Comment by mgrybyk** [comment]
@kmnaid to hide output of @wdio/cli:Launcher, etc, you should use proper package names:
```
    logLevels: {
        webdriver: 'silent',
        webdriverio: 'silent',
        '@wdio/local-runner': 'silent', // instead of wdio-local-runner
        '@wdio/cli': 'silent' // instead of wdio-cli
    },
```

regarding messages like:
```
Test Suites:	 2 passed, 2 total (100% completed)
Time:		 🕒  27.42s
```

I'm not sure. Do we have ability to hide wdio-interface output or any plans for this @christian-bromann ?

**Comment by kmnaid** [comment]
Thanks @mgrybyk.
That worked but I had to specify specific modules.

`'@wdio/cli:Launcher': 'silent'` for `2019-04-22T15:33:41.870Z INFO @wdio/cli:Launcher: Run onPrepare hook`. 
Just `'@wdio/cl': 'silent' ` does not silence the log.

 Similarly for  `'@wdio/utils': 'silent'`, I still see the below log appearing 
 `2019-04-22T15:24:14.820Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "sauce"`.
 This is what works: `@wdio/utils:initialiseServices`

Don't you think log levels should apply for the entire entire package when specified?
 
It would also be nice for [this](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-cli/src/templates/wdio.conf.tpl.ejs#L107) to be updated.

**Comment by mgrybyk** [comment]
that's strange!
Is there a typo in `'@wdio/cl': 'silent'` ? should be '@wdio/cli': 'silent'

**Comment by kmnaid** [comment]
Typo here, I must have erased it when deleting the 'Launcher' but in the actual file it is correct and logs still appear. 
Here is an example from a recent run:
```
2019-04-22T18:00:17.023Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "sauce"
2019-04-22T18:00:17.082Z INFO @wdio/cli:Launcher: Run onPrepare hook```

**Comment by mgrybyk** [comment]
Thank you for your help, I'll check it tomorrow

**Comment by mgrybyk** [comment]
@kmnaid https://github.com/webdriverio/webdriverio/pull/3871 fixes issue that setting log level for loggers like @wdio/cli won't affect its subloggers (@wdio/cli:Launcher).

However this doesn't affect interface, so you will see 
```
Test Suites:	 2 passed, 2 total (100% completed)
Time:		 🕒  27.42s
```

Can you please describe desired behaviour? 
You don't want to see summary and time but still want to see reporters output. Is that correct?

**Comment by CrispusDH** [comment]
@mgrybyk am I right that if I set `logLevel: silent` it should set such log level for all wdio libraries?

**Comment by mgrybyk** [comment]
yes, you are right

**Comment by mgrybyk** [comment]
it should, but it doesn't work for `@wdio/local-runner`, checking right now what is going wrong

**Comment by mgrybyk** [comment]
the problem is that first loggers are initialised, then custom log levels are applied, and only then global log level is set.

This is happening because we need to parse config before setting log levels, but config parser using logger as well.

At this point I'll change behaviour a bit to workaround this problem

**Comment by kmnaid** [comment]
> @kmnaid #3871 fixes issue that setting log level for loggers like @wdio/cli won't affect its subloggers (@wdio/cli:Launcher).
> 
> However this doesn't affect interface, so you will see
> 
> ```
> Test Suites:	 2 passed, 2 total (100% completed)
> Time:		 🕒  27.42s
> ```
> Can you please describe desired behaviour?
> You don't want to see summary and time but still want to see reporters output. Is that correct?

@mgrybyk: Summary is fine, but I think these two lines should not appear when `@wdio/utils:silent` and `@wdio/cli:silent` is set.

```
2019-04-22T18:00:17.023Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "sauce"
2019-04-22T18:00:17.082Z INFO @wdio/cli:Launcher: Run onPrepare hook```
```

**Comment by mgrybyk** [comment]
with last PR it should be fixed
