### ISSUE TITLE
Webdriverio and Appium android scripts failing if i run all of my test scripts together

### ISSUE THREAD

**Issue by gauravgandhi15** [webdriverio/webdriverio#3875]
**Environment (please complete the following information):**
 - **WebdriverIO version: 5.4.14
 - **Node.js version: 8.9.4
 - **NPM version: 5.6.0
 - **Browser name and version: Chrome
 - **Platform name and version: Android

**Config of WebdriverIO**
`"devDependencies": {
    "@wdio/sauce-service": "^5.4.14"`

**Describe the bug** : 

> I am using webdriver.io and Appium for android and iOS web scripts. I am running through one issue, when ever i try to run all the scripts together, some of the test cases are randomly failing after the first successful script on Android. This is only happening on android, iOS all the scripts are passing successfully. 

**Log** : https://gist.github.com/gauravgandhi15/3b5f9589d113d4595ebbdb5306e47569

**Additional context** : Capabilities -
      `platformName: "Android",
        platformVersion: "8.0.0",
        deviceName: "Samsung",
        browserName: "Chrome"`

**Comment by gauravgandhi15** [comment]
@christian-bromann Please help me on this issue.

**Comment by christian-bromann** [comment]
@gauravgandhi15 without a reproducible example I can't help here.

**Comment by gauravgandhi15** [comment]
> @gauravgandhi15 without a reproducible example I can't help here.

What kind of reproducible example you need?

**Comment by gauravgandhi15** [comment]
> @gauravgandhi15 without a reproducible example I can't help here.

I can give you whatever you need. I am just trying to see all the scripts together.

**Comment by gauravgandhi15** [comment]
> > @gauravgandhi15 without a reproducible example I can't help here.
> 
> @christian-bromann What kind of reproducible example you need?

@christian-bromann Not sure how to give you reproducible example. I have my scripts and i am trying to run them all together. Just failing on Android

**Comment by christian-bromann** [comment]
> If i run them separately, they all passing

This seems to be a setup issue with Appium and the Simulators / Emulators and not WebdriverIO.
