### ISSUE TITLE
Junit outputDir and filename gets set incorrectly when defined as an option

### ISSUE THREAD

**Issue by ergbouncex** [webdriverio/webdriverio#3879]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.7.15
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v10.15.3
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome 71
 - **Platform name and version:** macOS 10.14.3
 - **Additional wdio packages used (if applicable):** 
    "@wdio/cli": "^5.7.15",
    "@wdio/dot-reporter": "^5.7.8",
    "@wdio/junit-reporter": "^5.7.16",
    "@wdio/local-runner": "^5.7.15",
    "@wdio/mocha-framework": "^5.7.14",
    "@wdio/sauce-service": "^5.7.15",
    "@wdio/selenium-standalone-service": "^5.7.8",
    "@wdio/spec-reporter": "^5.7.13",
    "@wdio/sync": "^5.7.13",

**Config of WebdriverIO**
```
exports.config = {
	services: [
		'selenium-standalone',
	],
	seleniumLogs: './logs/selenium',
	specs: [
		'test/spec/mytest.spec.js',
	],
	maxInstances: 1,
	capabilities: [
		{
			browserName: 'chrome',
		},
	],
	sync: true,
	logLevel: 'info',
	outputDir: './logs/wdio/',
	coloredLogs: true,
	bail: 0,
	waitforTimeout: 5000,
	framework: 'mocha',
	specFileRetries: 1,
	reporters: [
		'dot',
		['junit', {
			outputDir: './reports/junit',
		}],
	],
	mochaOpts: {
		ui: 'bdd',
		timeout: 20000,
		compilers: ['js:@babel/register'],
	},
	before(capabilities, specs) {
		const chai = require('chai');
		global.expect = chai.expect;
		global.assert = chai.assert;
	},
};
```

**Describe the bug**
- When defining the outputDir for the Junit reporter, all logs from wdio go to that directory in addition to the defined outputDir from the config (outside of the junit options). The junit outputDIr contains. (wdio-0-0-browser.log, wdio-0-0-server.log)
- The default filename is wdio-0-0-junit-reporter.log not .xml
- When trying to explicitly name the file, as in the docs, opts.capabilities is undefined

**To Reproduce**

1. Define an outputDir in your main config
1. Define an outputDir within your junit reporter options
1. Run wdio (ie `npm test`)

**Expected behavior**
- The default filename to be .xml
- If setting the name explicitly, opts.capabilities should not be undefined
- Junit outputDir should only write junit xml files, all other logs should be saved to the outputDir defined within the main config.

**Comment by naddison** [comment]
The default filename will be log (if should be XML, but it defaults to .log). Can you share your options when you set the **outputFileFormat** property?

**Comment by naddison** [comment]
I have tried the following scenarios:

```javscript
outputDir: './logs',
reporters: [
	'spec',
	['junit', {
		outputDir: './test/reports/junit-results/',
		outputFileFormat: function(opts) { // optional
			return `results-${opts.cid}.${opts.capabilities}.xml`
		}
	  }
	]
],
```

**Outcome**
- results-0-0.undefined.xml created in /test/reports/junit-results/. The argument given to the function does not seem to have capabilities as a defined property.
- wdio-0-0-server.log is created. This is the log file retrieved from the Selenium server. This should be put into the ./logs folder and not a reporter directory.

**Changes required**
- Ensure that the this.caps is set in wdio-runner reporter.js before the reporters are initialized.
- Ensure that this.config.outputDir is not modified when initializing the reporters.

**Comment by naddison** [comment]
@christian-bromann this is fixed and can be closed.

**Comment by christian-bromann** [comment]
Thanks for fixing this @naddison
