### ISSUE TITLE
Unable to get element's new background color

### ISSUE THREAD

**Issue by goberflunk** [webdriverio/webdriverio#388]
I'm working with a site where I need to get the background color of an object. When i use the getCSSproperty() function it sometimes works fine but other times it will retrieve an overwritten background color rather than the current background color that i'm looking for. Example: A field has a background color of grey. This background color is overwritten in the code to be green but the getCSSproperty('#id', 'background-color') still returns it as grey.

**Comment by christian-bromann** [comment]
I am not sure but I think Selenium has something like an internal cache, so when running the same command twice it will reuse the result of the previous command. Could you check the selenium logs to make sure that two requests have been sent to the server?
To be 100% sure just use the execute command and return the background value if the desired element.

**Comment by goberflunk** [comment]
It looks like it does send the request twice looking at the logs i have 

10:32:27.626 INFO - Executing: [get value of css property: 21 [[ChromeDriver: chrome on MAC (77920716ec9b4c7f51302d8a36fa3f33)] -> id: equationBox], background-color])
10:32:27.631 INFO - Done: [get value of css property: 21 [[ChromeDriver: chrome on MAC (77920716ec9b4c7f51302d8a36fa3f33)] -> id: equationBox], background-color]

And then later 

10:35:20.376 INFO - Executing: [get value of css property: 21 [[ChromeDriver: chrome on MAC (ac85e26b4478953eaeac0174471f0e0f)] -> id: equationBox], background-color])
10:35:20.383 INFO - Done: [get value of css property: 21 [[ChromeDriver: chrome on MAC (ac85e26b4478953eaeac0174471f0e0f)] -> id: equationBox], background-color]

**Comment by christian-bromann** [comment]
Could you enable the WebdriverIO logs (in the options: `logLevel: "verbose"`) to check what actual results we get back?

**Comment by christian-bromann** [comment]
Damn..sorry accidentally deleted your post

**Comment by goberflunk** [comment]
I turned on the logs, where should the logs be outputting to?

**Comment by christian-bromann** [comment]
in your terminal (stdout)

**Comment by goberflunk** [comment]
Is this the correct place to put the logLevel option?

var client = require('webdriverio').remote({
    desiredCapabilities: {
        browserName: 'chrome',
        logLevel: 'verbose'
    }
});

**Comment by christian-bromann** [comment]
no it's:

```js
var client = require('webdriverio').remote({
    logLevel: 'verbose',
    desiredCapabilities: {
        browserName: 'chrome'
    }
});
```

**Comment by goberflunk** [comment]
[10:57:01]:  COMMAND	GET 	 "/wd/hub/session/bd154ea3-52d1-416c-ae46-d0b4f28745c7/element/21/css/background-color"
[10:57:01]:  DATA		 {}
[10:57:02]:  RESULT		 rgba(255, 255, 255, 1)

This is the result for the getting the background-color call

**Comment by christian-bromann** [comment]
That looks about right. So you said the problem is that you get grey even though you changed the background color on the page to black?

**Comment by goberflunk** [comment]
![screen shot 2015-01-08 at 11 02 48 am](https://cloud.githubusercontent.com/assets/3801495/5667619/791ca3e6-9726-11e4-8356-3b35cd1047e0.png)

Green instead of black but correct, here's what inspecting the element looks like in google chrome

**Comment by goberflunk** [comment]
Actually it looks like rgba(255,255,255,1) is white. This is further down in the google chrome inspect panel

![screen shot 2015-01-08 at 11 05 17 am](https://cloud.githubusercontent.com/assets/3801495/5667660/d8c0d4fc-9726-11e4-89ba-6b6bf9ff00ee.png)
 
So there are 3 colors to choose from and its choosing the white one

**Comment by christian-bromann** [comment]
interesting, could you try this instead:

```js
client.execute(function() {
    return document.getElementById('equationBox').style.backgroundColor;
}, function(err, res) {
    console.log(res.value);
});
```

**Comment by goberflunk** [comment]
That logs and empty string, using .style instead of .style.background color returns "[]"

**Comment by christian-bromann** [comment]
oh right, do this:

```js
client.execute(function() {
    return window.getComputedStyle(document.getElementById('equationBox'), null)["background-color"];
}, function(err, res) {
    console.log(res.value);
});
```

**Comment by goberflunk** [comment]
That one gave me rgb(255, 255, 255). So, white again

**Comment by christian-bromann** [comment]
Well then it has to be something to do with the selector. On the element you assign the green background color try to inspect that element with your dev tools, then do right click and click on "Copy CSS Path" and use that as selector

**Comment by goberflunk** [comment]
When i do that it give me #equationBox as the path

 the strange part is, when I check the html on the page i get 

<textarea data-dojo-attach-point="focusNode,containerNode,textbox" autocomplete="off" class="dijitTextBox dijitTextArea dijitTextBoxDisabled dijitTextAreaDisabled dijitDisabled" tabindex="-1" lang="en" id="equationBox" rows="2" cols="30" widgetid="equationBox" value="" aria-disabled="true" disabled="" style="background-color: rgb(144, 238, 144);"></textarea>


But when I use the webdriverio .getHtml it returns this 

<textarea data-dojo-attach-point="focusNode,containerNode,textbox" autocomplete="off" class="dijitTextBox dijitTextArea" tabindex="0" lang="en" id="equationBox" rows="2" cols="30" widgetid="equationBox" value="" aria-disabled="false"></textarea>

**Comment by christian-bromann** [comment]
ok, well there is definitely something strange going on but, maybe test setup (is the browser running in a correct environment etc.?).

**Comment by goberflunk** [comment]
Not that I know of, using the latest version of Chrome and the Chrome driver

**Comment by christian-bromann** [comment]
@goberflunk sorry at this point I can't help you anymore, if you have questions or anything, let me know. Would be cool if you could post a solution once you got it
