### ISSUE TITLE
Support Appiums Settings command

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#3883]
**Is your feature request related to a problem? Please describe.**
It seems that Appium has a settings command which is currently not on our Appium spec.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wswebcreation** [comment]
@christian-bromann 

What do you mean with this? It's in the docs [here](https://webdriver.io/docs/api/appium.html#getsettings) and [here](https://webdriver.io/docs/api/appium.html#updatesettings)

**Comment by christian-bromann** [comment]
Ah you right, closing then!
