### ISSUE TITLE
FR: Add possibility to resize browser window to desired dimensions for webdriverio [v5]

### ISSUE THREAD

**Issue by erinev** [webdriverio/webdriverio#3888]
**Is your feature request related to a problem? Please describe.**
I was not able to find a way how to resize browser to desired dimensions. We need that so our tests would run in maximum allowed dimensions (which is 1280x1024 - Windows VM limitation) because our UI supports 1200 minimum dimensions (it is not mobile friendly).

**Describe the solution you'd like**
Single method on browser which allows to resize window. For example `angular/protractor` framework lets to do it this way: `browser.driver.manage().window().setSize(1280, 1024);`

**Describe alternatives you've considered**
We did a hack inside our code so browser opens with initial dimensions we open new window with proper dimensions and continue execution in that new window. Hack is implemented this way: `browser.newWindow(`${browser.config.baseUrl}/login`, 'Title', 'width=1280,height=1024,scrollbars=yes,status=1');`. And all other test case is executed in that new window with proper dimensions.

**Comment by baruchvlz** [comment]
Have you tried [browser.setWindowSize](https://webdriver.io/docs/api/browser/setWindowSize.html) ?

**Comment by erinev** [comment]
@baruchvlz thanks, i don't know how i missed this in API documentation..
