### ISSUE TITLE
Usage Example Clarification On Selectors By Text

### ISSUE THREAD

**Issue by cdaringe** [webdriverio/webdriverio#389]
Hi all:

I read through the docs and have done some tinkering, but am uncertain as to why the following errors when trying to select an anchor tag:

```js
 client
    ... some things ...
    .click('#submitBtn') // loads my new page
    .waitFor('=Sites', 8000)
    .click('=Sites')
    .end(done);
```
where on the page I have 

```html
<li>
    <a href="#" 
        title="List and add sites" 
        onclick="someGoofyFunction();">
        Sites
    </a>
</li>
```
The selectors doc seems to imply that the Sites anchor should be caught, but I receive the following

```
  (NoSuchElement:7) An element could not be located on the page using the given search parameters.
     Problem: no such element
     Callstack:
     -> element("=Sites")
     -> waitFor("=Sites",8000)
 has no method 'click'
```

**Comment by christian-bromann** [comment]
I am curious, could you change your like so it has no white spaces in it?

```html
<li>
    <a href="#" 
        title="List and add sites" 
        onclick="someGoofyFunction();">Sites</a>
</li>
```

**Comment by cdaringe** [comment]
Indeed it actually doesn't, I just formatted. For the post. It's true form:

```html
<a href="#" title="List and add sites" onclick="someGoofyFunction();">Sites</a>
```

**Comment by cdaringe** [comment]
Also, I would like to select by other attrs, but my teamsters have added no other attr except for `title`.  I'm curious why the `name` selector, per the docs, is only `name` friendly, vs any other `attr` string?

**Comment by christian-bromann** [comment]
@cdaringe you could try to query that element like `client.waitFor('[title="List and add sites"]', 8000)`

**Comment by cdaringe** [comment]
That one seemed to do the trick.  Much appreciated!
