### ISSUE TITLE
BUG: isEnabled & waitForEnabled actions doesn't work correctly for disabled a (link) elements

### ISSUE THREAD

**Issue by erinev** [webdriverio/webdriverio#3890]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.7.15
 - **Mode:** standalone
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [v10.15.0]
 - **NPM version:** [6.5.0]
 - **Browser name and version:** Chrome [74]
 - **Platform name and version:** [WIN_10]
 - **Additional wdio packages used (if applicable):** "@wdio/cli": "5.7.15", "@wdio/devtools-service": "5.7.13", "@wdio/local-runner": "5.7.15", "@wdio/mocha-framework": "5.7.14", 
 "@wdio/spec-reporter": "5.7.13", "@wdio/sync": "5.7.13" 
([package.json](https://github.com/erinev/wdio-selenium-tests-playground/blob/reproduce_isEnabled_bug/package.json))

**Config of WebdriverIO**
[wdio.conf.js](https://github.com/erinev/wdio-selenium-tests-playground/blob/master/wdio.conf.js)  

**Describe the bug**
Element actions [isEnabled](https://webdriver.io/docs/api/element/isEnabled.html) & [waitForEnabled](https://webdriver.io/docs/api/element/waitForEnabled.html) works incorrectly for disabled `a` (link) element. It says that a element is enabled even though it has disabled attribute (`disabled="disabled"`)

**To Reproduce**
100 % reproduce scenario is replicated in this [repository](https://github.com/erinev/wdio-selenium-tests-playground/tree/reproduce_isEnabled_bug) branch `reproduce_isEnabled_bug`.   

1) we have imaginary application == simple html [page](https://github.com/erinev/wdio-selenium-tests-playground/blob/reproduce_isEnabled_bug/app/index.html)
2) one `a` element (in real life it is styled as button) is enabled and other `a` element is disabled
3) We have 2 tests written in this spec [file](https://github.com/erinev/wdio-selenium-tests-playground/blob/reproduce_isEnabled_bug/specs/test.spec.js)
4) names in this file is really explicit so its easy to understand the problem  
These tests can be easily runned locally, just read [readme](https://github.com/erinev/wdio-selenium-tests-playground/blob/reproduce_isEnabled_bug/README.md)

**Expected behavior**
isEnabled() & waitForEnabled() actions works as expected for all element types (including `a` elements)  

**Log**
![image](https://user-images.githubusercontent.com/4118417/56818560-8afcb380-6850-11e9-8053-c6b5aa0f49e3.png)

**Comment by abjerstedt** [comment]
@erinev I appreciate the work you put into the report, but this isn't a WDIO problem. We literally use the result from the driver endpoints without any custom logic.

The driver then implements https://www.w3.org/TR/webdriver1/#is-element-enabled, and if the result you are seeing differs from this, then the bug is on the driver.

**Comment by erinev** [comment]
@abjerstedt webdriver.io documentation is lying then. It says `Return true or false if the selected DOM-element is enabled.` (source: https://webdriver.io/docs/api/element/isEnabled.html).  

`a` is an element and it does not work for `a` element.  

Don't be so quick to close the issue without resolving it fully.  

i will create new issue which will ask to update documentation what isEnabled and waitForEnabled actually does (for which elements it works should be listed in webdriver.io documentation otherwise its misleading and causing confusion for lib users)

**Comment by mgrybyk** [comment]
@erinev  **disabled** for `a` element tag is not a part of standard as far as I know. 
For that case you may use **getAttribute** in combination with **waitUntil**.

**isEnabled** returns true or false depending on situation. 
**waitForEnabled** (actually all waitFor*) waits for condition to be true otherwise throws an exception when timeout is reached.

**Comment by erinev** [comment]
@mgrybyk maybe you have some docs link for the standard of disabeable elements ?  

i'm reading provided webdriver docs: https://www.w3.org/TR/webdriver1/#is-element-enabled

5 step -> `Set enabled to false if a form control is disabled.`  
could it be that webdriver is able to detect disabled element if its supported in form ? (like button, input, etc) ? maybe you have some knowledge here ? (if only form elements is supported then webdriver-io docs coul state this info

**Comment by mgrybyk** [comment]
https://www.w3schools.com/tags/att_disabled.asp

**Comment by abjerstedt** [comment]
To reiterate @erinev, this issue has nothing to do with >webdriverio<. Webdriver is a specification/contract that the drivers adhere to. We simply consume the response that the drivers give us; and so, this issue is not representative of anything we need to do (aka should be closed).

As @mgrybyk stated, feel free to update documentation if you believe it to be inaccurate or misleading.

**Comment by erinev** [comment]
ok got it now and i agree with closing the issue.  

i just tested and i can confirm that isEnabled works only for form elements, output after printi various element isEnabled flag:  
```
[0-0] isEnabled() result for DISABLED link:         true <- doesn't work for disabled link elements (because link is not form element)
[0-0] isEnabled() result for DISABLED text input:   false
[0-0] isEnabled() result for DISABLED button input: false
[0-0] isEnabled() result for DISABLED select:       false
[0-0] isEnabled() result for DISABLED textarea:     false
[0-0] isEnabled() result for DISABLED button:       false
```

so i will provide PR for ducomentation update that isEnabled and waitForEnabled works only for form elements

**Comment by erinev** [comment]
just one question where i can find documentation which is shown in webdriver.io UI as docs ? @abjerstedt

**Comment by treyturner** [comment]
If it helps, I detect our application's use of disabled links via a custom element command:
```
browser.addCommand('isEnabledLink', function() {
      return this.getAttribute('disabled') === null;
    }, true);
```

**Comment by erinev** [comment]
@treyturner yes, we did the same as workarround our not standard link with disabled attribute, thanks for note
