### ISSUE TITLE
Watch mode is not working correctly

### ISSUE THREAD

**Issue by artur-michalak** [webdriverio/webdriverio#3896]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2]
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v8.14.0/v10.15.5
 - **NPM version:** 6.4.1
 - **Browser name and version:** 73.0.3683.103
 - **Platform name and version:** OSX 10.14
 - **Additional wdio packages used (if applicable):**
    "@wdio/cli": "^5.7.15",
    "@wdio/dot-reporter": "^5.7.8",
    "@wdio/jasmine-framework": "^5.7.13",
    "@wdio/local-runner": "^5.7.15",
    "@wdio/selenium-standalone-service": "^5.7.8",
    "@wdio/sync": "^5.7.13",

**Config of WebdriverIO**
https://pastebin.com/iZkkwWF8

**Describe the bug**
I can't use watch mode  wdio `npx wdio wdio.config.js --watch' to write test for development.
On first run i'm getting correct results however re-run gives wrong response.
My directory structure looks like that
![image](https://user-images.githubusercontent.com/2443904/56956851-a06e2800-6b45-11e9-8bdc-54ab73218631.png)

**To Reproduce**
1. Use this packages.json https://pastebin.com/9zcb3ac4
2. npm i
3. create two files with tests (basic.js && basic-1.js)
3. npx wdio wdio.conf.js --watch
4. edit one file with tests to make it failing
5. re run results will be wrong

**Expected behavior**
Watch mode should work the same way as single run.

**Comment by christian-bromann** [comment]
@artur-michalak can you please elaborate on what is not working and what do you expect?

**Comment by artur-michalak** [comment]
Sure, i'll do my best.
In first run all tests completes and everything works correctly
![image](https://user-images.githubusercontent.com/2443904/57208181-b612a000-6fd2-11e9-87e5-ea6b0d824292.png)

When i'm modifying one of tests i'm getting this error:
![image](https://user-images.githubusercontent.com/2443904/57208350-a5165e80-6fd3-11e9-84f5-d1aa9f7f5ab9.png)

When i rerun `npx wdio wdio.conf.js --watch` again it shows correct result
![image](https://user-images.githubusercontent.com/2443904/57208219-fb36d200-6fd2-11e9-8d37-94c0cdee45ca.png)

I presume that on reruns result shows only for modified file. Is this correct behaviour?

**Comment by mgrybyk** [comment]
@artur-michalak 
Only modified spec file is restarted in watch mode. This is works as designed. 

Spec re-run message will be updated soon to avoid confusion.
