### ISSUE TITLE
Examples for performActions command

### ISSUE THREAD

**Issue by sgauruseu** [webdriverio/webdriverio#3899]
`rightClick` command is removed in v5
Could you please add sample code for  `performActions `?

This is my code :
[ await this.browser.performActions([{
            type: 'pointer',
            id: 'pointer1',
            parameters: {
                pointerType: 'mouse'
            },
            actions: [{
                type: 'pointerDown',
                button: 2
            },  {
                type: 'pointerUp',
                button: 2
            }]
        }]);
        return await this.browser.releaseActions();]

But I got  the exception  ` TypeError: this.browser.performActions is not a function`

Environment:
 - **WebdriverIO version:**  ^5.7.15,
 - **Mode:**  Standalone mode
 - **NPM version:**  5.6.0
 - **Browser name and version:**  Chrome 68
 - **Platform name and version:** Windows 10

**Comment by christian-bromann** [comment]
> But I got the exception ` TypeError: this.browser.performActions is not a function`

This is because Chrome v68 doesn't support this command (yet). In Chrome continue to use the [`positionClick`](https://webdriver.io/docs/api/jsonwp.html#positionclick) command.

**Comment by sgauruseu** [comment]
I am sorry , browser's  version is  73.0.3683.103 (Official Build) (64-bit)

**Comment by industral** [comment]
Same here, with Chrome 76 on Browserstack. locally works fine.

**Comment by chirag-farfetch** [comment]
I am having this issue, i have latest versions installed but not able to run this. getting performActions function not found. I have also tried drag and drop but i am not able to click and hold onto a element. can anyone help?

**Comment by dalecreativ** [comment]
@chirag-farfetch 

I've found updating the capabilities helped get this running.
Updating the `seleniumVersion` to a more recent version. 

Found this useful for building different capabilities to try: [Browserstack capabilities builder](https://www.browserstack.com/automate/capabilities)


### w3c capabilites:
```json
   'bstack:options' : {
    "os" : "Windows",
    "osVersion" : "10",
    "local" : "false",
    "seleniumVersion" : "3.14.0",
    },
    "browserName" : "Chrome",
    "browserVersion" : "79.0",
}
```


### legacy capabilities:

```json
{
    "os" : "Windows",
    "os_version" : "10",
    "browserName" : "Chrome",
    "browser_version" : "79.0",
    "resolution" : "1440x900",
    "browserstack.selenium_version" : "3.14.0",
}
```
