### ISSUE TITLE
option to automatically pause after each command

### ISSUE THREAD

**Issue by christopherbalz** [webdriverio/webdriverio#390]
I would like to optionally run my tests so that they execute slowly enough for a person to see visually what is happening on the web browser screen (for example, to better troubleshoot a failure).

I tried `client.timeoutsImplicitWait(5000);` but it seems to have no effect.

**Comment by Robinfr** [comment]
I think the only way to do this is to add .pause in between all actions..

**Comment by thibaut-sticky** [comment]
You can use the Eventhandling.

```JS
client.on('command', function(e) {
    client.pause(1000);
})
```

**Comment by christian-bromann** [comment]
Thanks @thibaut-sticky .. There is no need for introduce something new if this works too.

**Comment by christopherbalz** [comment]
But this way requires modifying the test code itself for each (per) command - is there a way, like there used to be with old Selenium, to set the client to pause between each command from the beginning of the test?

**Comment by christian-bromann** [comment]
> requires modifying the test code itself for each (per) command

@christopherbalz not quite, you only have to register that eventhandler one time (e.g. after you set up your client instance) and it works with all commands ;-)

**Comment by christopherbalz** [comment]
Ah, okay thank you!

**Comment by ayoolaao** [comment]
> requires modifying the test code itself for each (per) command

@christian-bromann @nottoseethesun Where would register the eventhandler if I using the wdio test runner?

**Comment by christian-bromann** [comment]
@ayoolaao this can't be done within the event listener, you can use the after command hook for it

**Comment by ayoolaao** [comment]
@christian-bromann Thank you!
