### ISSUE TITLE
Exception in performActions command (WebdriverIO v5)

### ISSUE THREAD

**Issue by sgauruseu** [webdriverio/webdriverio#3901]
I updated my chrome browser(73.0.3683.103), but I got the exception again

Environment:
 - **WebdriverIO version:**  ^5.7.15,
 - **Mode:**  Standalone mode
 - **NPM version:**  5.6.0
 - **Browser name and version:**  Version 73.0.3683.103 (Official Build) (64-bit)
 - **Platform name and version:** Windows 10

this is my code for the right click : 
[ await this.browser.performActions([{
            type: 'pointer',
            id: 'pointer1',
            parameters: {
                pointerType: 'mouse'
            },
            actions: [{
                type: 'pointerDown',
                button: 2
            },  {
                type: 'pointerUp',
                button: 2
            }]
        }]);
        return await this.browser.releaseActions();]

**Comment by christian-bromann** [comment]
As I told you in the other thread Chrome doesn't support that command.

**Comment by jedwards1211** [comment]
Is there currently any API or 3rd party package that papers over the annoying differences between browsers like this?

**Comment by jedwards1211** [comment]
Actually, I guess `keys` works in both Chrome and FF in webdriverio v5?  I was confused because it didn't work in v4 and back then you were saying to use actions instead.

**Comment by christian-bromann** [comment]
> I was confused because it didn't work in v4 and back then you were saying to use actions instead.

You are right. In v5 we automatically use actions now if you browser supports it.
