### ISSUE TITLE
Confused different drivers need {get,set}WindowSize() vs {get,set}WindowRect()

### ISSUE THREAD

**Issue by ratbeard** [webdriverio/webdriverio#3905]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [x] Unclear documentation
- [ ] A typo
- [ ] Missing documentation
- [x] Other

**Description of the improvement / report**

To run some tests against a smaller sized window, I added the following helper function to my tests:

```ts
function onSmallScreen(callback: () => void) {
  const smallWidth = 500;
  const smallHeight = 600;

  // Firefox…
  if ('getWindowRect' in browser) {
    const { x, y, width, height } = browser.getWindowRect() as any; 
    browser.setWindowRect(x, y, smallWidth, smallHeight);
    callback();
    browser.setWindowRect(x, y, width, height);

  } else { // Chrome………
    const { width, height } = browser.getWindowSize() as any;
    browser.setWindowSize(smallWidth, smallHeight);
    callback();
    browser.setWindowSize(width, height);
  }
}
```

I am unclear why I need to use different api's to resize the window for different drivers.  I suspect it has something to do with firefox runs in `w3c mode', as I had to do a similar change for a drag and drop test where I had to use a different api for firefox.

I'm not sure exactly at what level the bug(s) lie, so I'll just list some statements here:

- The sidebar in the docs include setWindowSize() but not getWindowSize(), getWindowRect, or setWindowRect().  Since setWindowSize is there I would at least expect getWindowSize to be there too.

- The typescript definitions contain all 4.

- Searching on google is hard as webdriver brings up other languages, or v4 code which contains methods that were removed, or you assume a function like getWindowRect() was removed since its not in the sidebar.

- If you try to call the function on a driver that doesn't support it you don't get an error like `This driver doesnt support this use getWindowRect() instead`, you get something like `getWindowSize is not a function`.

- The docs don't indicate https://webdriver.io/docs/api/browser/setWindowSize.html only works in some drivers.

- I found getWindowRect inside the protocols section https://webdriver.io/docs/api/webdriver.html I probably wouldn't have checked there unless I ran into that drag and drop issue before.  And that one I resolved by searching the code and saw a `this.isW3c` variable.  I would think getWindowSize would mention its only for some drivers and link to getWindowSize(), for example.

- It's not really clear to me users of the library **should** have to know about the differences between drivers?  It seems like getWindowSize() could be implemented on firefox in terms of getWindowRect, or vice-versa. 

I'd be willing to help improve the docs, just not really sure where to begin.  I would say currently using the library assumes you must have a fair bit of background knowledge on selenium/webdriver etc., which is probably not a very safe assumption for most web developers who just want to write browser-based tests.  Maybe the main api page could talk about the difference, and then these pages could have a little explanatory paragraph at the top too:

https://webdriver.io/docs/api/webdriver.html
https://webdriver.io/docs/api/jsonwp.html

And then similar methods like the above could be cross-linked, as well as a better error message too?

Thanks :)

**Comment by sdserage** [comment]
Same issue here.

**Comment by mgrybyk** [comment]
@ratbeard @sdserage `setWindowSize` works both for Chrome and Firefox. However you are right regarding `getWindowSize`.
I think it would be good idea to have `getWindowSize` command as well to make it consistent.
