### ISSUE TITLE
Mac key - command fails to work

### ISSUE THREAD

**Issue by AutomationGuru** [webdriverio/webdriverio#3906]
**Environment (please complete the following information):**
 - **WebdriverIO version:** ^5.7.8
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v10.12.0
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome 73
 - **Platform name and version:** Mac

**Describe the bug**
Given i try to use Command key on mac i fail to see it working,
browser.keys(value) fails to support Mac **command** key
Example:
browser.keys(['META','v']); or browser.keys(['COMMAND','v']); or browser.keys(['Meta','v']); or browser.keys(['command','v']); 
fails to work
on V5

**To Reproduce**
Paste from Clipboard:  
```browser.keys(['META','v']); ```
OR 
```browser.keys(['COMMAND','v']); ```
OR
```browser.keys(['Meta','v']); ```
**Expected behavior**
Expect to be able to pass command on mac instead of Ctrl !

**Comment by christian-bromann** [comment]
@AutomationGuru do you have a reproducible example?

**Comment by AutomationGuru** [comment]
> @AutomationGuru do you have a reproducible example?

Yep i have updated the bug, its simply using the browser.keys , not sure if you need more information ?

**Comment by christian-bromann** [comment]
> not sure if you need more information ?

Do you have a whole testscript I can run?

**Comment by AutomationGuru** [comment]
:( unfortunately i dont ... its an internal tool i run the tests against and although i could share the script you will not be able to run it against

**Comment by christian-bromann** [comment]
@AutomationGuru can you create an example that is using an arbitrary public app?

**Comment by AutomationGuru** [comment]
> @AutomationGuru can you create an example that is using an arbitrary public app?

Sorry for the delay managed to do that now:
Given i navigate to the website and when i copy a value to clipboard, when i try to paste the same with command button i see it fails to work :

```
browser.url('https://clipboardjs.com/');    
        $('//*[@id="example-target"]/div').moveTo();
        $('//*[@id="example-target"]/div/span/button').click();
        $('//*[@id="example-target"]/div/input').click();
        browser.keys(['Command','v']);
        browser.keys(['Command','v']);
        browser.keys(['COMMAND','v']);
        browser.keys(['COMMAND','v']);
        browser.keys(['META','v']);
        browser.keys(['META','v']);
        console.log($('//*[@id="example-target"]/div/input').getAttribute('value'))  // Expect to have the value copied on clipboard to be printed but fails 
```
This was a random website i picked, hope this should be allright ?

**Comment by mgrybyk** [comment]
I think this one is not WebdriverIO related but is how webdriver works. 
Can it be closed in such case?

**Comment by mgrybyk** [comment]
Closing this one as far as it is not WDIO related. Feel free to re-open if my consumption is wrong.

Thanks

**Comment by pauravp** [comment]
@AutomationGuru Did it eventually worked for you ? I am also facing same issue . browser.key(['Escape']) isn't working with wdiov5 .

**Comment by pauravp** [comment]
@mgrybyk  why do you think its not related to webdriverio? I am trying to use browser.keys(['Escape']) and its not working . Documentation of .keys is also not very detailed too. I am not sure if I need to use META with Esc while passing this to keys command.

**Comment by AutomationGuru** [comment]
> @AutomationGuru Did it eventually worked for you ? I am also facing same issue . browser.key(['Escape']) isn't working with wdiov5 .

The defect raised was specific to mac where command is used instead of Ctrl, which did not work. I cannot understand how the issue you see is similar sorry. ![bitmoji](https://render.bitstrips.com/v2/cpanel/214e2e2c-3a98-46f6-9b61-50c57a0d8fca-ce32ec73-ad26-4e42-a27a-728893de9e6b-v1.png?transparent=1&palette=1&width=246)

I suggest you try the following twice:

browser.keys(['Escape'])
browser.keys(['Escape']) 

Modifier like Ctrl, Shift, Alt and Meta will stay pressed so you need to trigger them again to release them.

**Comment by pauravp** [comment]
Thanks for getting back. I didn't use modifiers like Ctrl, Shift, Alt and Meta then how are they gonna stay pressed. and even if they are implicitly pressed how do I release them?

**Comment by mgrybyk** [comment]
This is how browser drivers work on mac
