### ISSUE TITLE
Incorrect TypeScript definition for shadow$ and shadow$$

### ISSUE THREAD

**Issue by JamesGennoy** [webdriverio/webdriverio#3911]
**Environment:**
 - **WebdriverIO version:** 5.8.0
 - **Node.js version:** 10.15.0
 - **NPM version:** 6.4.1
 - **TypeScript version:** 3.4.4

**Describe the bug**
The type definition for the `shadow$` and `shadow$$` functions on `Element` are incorrect.

**To Reproduce**
```js
// TS Error: Expected 0 arguments, but got 1.
$('.input').shadow$('#innerEl');
```

**Expected behavior**
The type definitions for `shadow$` and `shadow$$` function on `Element` are:
```js
shadow$$(): void;
shadow$(): void;
```

The type definitions for `shadow$` and `shadow$$` function on `Element` should be:
```js
shadow$(selector: string | Function): Element;
shadow$$(selector: string | Function): Element[];
```

**Workaround**
```js
declare namespace WebdriverIO {
  interface Element {
    shadow$(selector: string | Function): WebdriverIO.Element;
    shadow$$(selector: string | Function): WebdriverIO.Element[];
  }
}
```

**Comment by tadashi0713** [comment]
https://github.com/webdriverio/webdriverio/pull/3913
@JamesGennoy From next release, types will be fixed

**Comment by christian-bromann** [comment]
Thanks for fixing @tadashi0713
