### ISSUE TITLE
Introduce Renovate or greenkeeper to make npm dependencies up-to-date

### ISSUE THREAD

**Issue by tadashi0713** [webdriverio/webdriverio#3912]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [ ] Missing documentation
- [x] Other

**Description of the improvement / report**
I believe it`s better to introduce tools such as Renovate or greenkeeper to make npm dependencies up-to-date.
They are free to use for OSS project, and they also help us to avoid dependencies security issue.
I can do some help for introducing if needed.

**Comment by mgrybyk** [comment]
I think this one can be closed after merging https://github.com/webdriverio/webdriverio/pull/4013 

Feel free to reopen if I misunderstood something
