### ISSUE TITLE
Add Webdriver Manager as a service

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#3914]
**Is your feature request related to a problem? Please describe.**
There is a different driver manager available that is well maintained called [webdriver-manager](https://www.npmjs.com/package/webdriver-manager-replacement). We should offer both as a service.

**Describe the solution you'd like**
Add a `webdriver-manager` as a service.

**Describe alternatives you've considered**
Nome

**Additional context**

**Comment by wswebcreation** [comment]
@christian-bromann 

I've been talking to @cnishina about this one, I can pick it up if I have a bit more time, but don't you mean [this](https://www.npmjs.com/package/webdriver-manager) one?

**Comment by cnishina** [comment]
I replaced cnishina/webdriver-manager-replacement to be angular/webdriver-manager. Some status updates on this: I have a few PRs in flight that will need to be merged in before I get a release out. There were a few issues this week with chromedriver 75 being released and everyone being on the newly released chrome 74.

Let me ping you when I get 13.0.1-beta.1 released.

Also, let me know what I can do to help.

**Comment by christian-bromann** [comment]
It seems that `webdriver-manager` hasn't been maintained for a year. Closing.
