### ISSUE TITLE
@wdio-sauce-service: set tunnel indentifier in `sauce:options`

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#3917]
Currently if people use `sauce:options` the `tunnelIdentifier` is set on the global capability level which will cause the test to fail at startup. We should prefer `sauce:options` from the beginning.

**Comment by wswebcreation** [comment]
@christian-bromann 

This means that we need to deliver all options to the `sauce:options`, otherwise it will not work and the instance will not start, or only move it to the `sauce:options` if they are available

**Comment by christian-bromann** [comment]
> This means that we need to deliver all options to the `sauce:options`

yes

**Comment by yamkay** [comment]
I guess this issue is similar to #4021

**Comment by christian-bromann** [comment]
yes, this has been fixed by this PR
