### ISSUE TITLE
how to start selenium server automatiacally through code

### ISSUE THREAD

**Issue by amiya-pattnaik** [webdriverio/webdriverio#392]
Hi,
My test script is Jasmine webdriver IO based. before running the script I need to start the selenium server manually and it is working fine. But my requirement is : how to start the server automatically befor start of the execution I  mean inside the script so that I need not to start the server manually. Is there any way? id so how we can do it in a Jasmine.spec.js script file? Please advise

**Comment by christian-bromann** [comment]
hi @amiya-pattnaik 

I would recommend to use [selenium-standalone](https://github.com/vvo/selenium-standalone) in one of your hooks.

Cheers
