### ISSUE TITLE
chooseFile API removed from v5.x.x

### ISSUE THREAD

**Issue by sanjeethgwd** [webdriverio/webdriverio#3920]
* What was the reason to remove the support for chooseFile api in v5?
* Would there be any chance to include the support in future to v5?

From change logs
>with no replacements: init, buttonPress, file, **chooseFile**, **uploadFile**, endAll, getCommandHistory, waitForSelected, waitForText, waitForValue, getGridNodeDetails, gridProxyDetails, gridTestSession, hold

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. v5.x.x]

**Comment by sanjeethgwd** [comment]
@hardikdiyora FYI

**Comment by christian-bromann** [comment]
Duplicate of #3632
