### ISSUE TITLE
How to click the element under other element with "display: contents" property of CSS3

### ISSUE THREAD

**Issue by pactera-testing-PanRenping** [webdriverio/webdriverio#3921]
Hi all, 
I can see an element in the page with my eyes.
I want to click this element and invoke click() function.
But there is an error: 
> element not visible
> Error: An element command could not be completed because the element is not visible on the page.

I am confused, **I found its parent element has "display: contents" property**, I guess this is root cause. 

Please help me, how can I click such element?

**Comment by wswebcreation** [comment]
Please ask these type of questions on our gitter channel

<a href="https://gitter.im/webdriverio/webdriverio">
        <img alt="Gitter" src="https://badges.gitter.im/webdriverio/webdriverio.svg">
    </a>
