### ISSUE TITLE
using w3c capabilities with chrome over saucelabs, .waitForDisplayed(); is broken

### ISSUE THREAD

**Issue by pmerwin** [webdriverio/webdriverio#3924]
when passing w3c caps to saucelabs, waitForDisplayed returns error:

"waitUntil condition failed with the following reason: Cannot call non W3C standard command 
while in W3C mode"

Environment (please complete the following information):

WebdriverIO version: [5.8.1]
Mode: [ WDIO Testrunner]
If WDIO Testrunner, running sync/async: [sync]
Node.js version: [8.10]
NPM version: [6.5.0]
Browser name and version: [chrome latest]
Platform name and version: [osx]
Additional wdio packages used (if applicable): [@wdio/sauce]

**Config of WebdriverIO**
```js
const defaultBrowserSauceOptions = {
    screenResolution: '1600x1200',
    seleniumVersion: '3.141.59'
};
const chromeOptions = {
    'goog:chromeOptions': {
        w3c: true,
    },
};

 {
            // w3c -> not working with isDisplayed , use jsonwp^
            browserName: 'googlechrome',
            platformName: 'Windows 10',
            browserVersion: 'latest',
            'sauce:options': {
                ...defaultBrowserSauceOptions,
            },
            ...chromeOptions,
        },
retruns =
   { alwaysMatch: 
      { browserName: 'googlechrome',
        platformName: 'Windows 10',
        browserVersion: 'latest',
        'sauce:options': [Object],
        'goog:chromeOptions': [Object] },
     firstMatch: [ {} ] },
  desiredCapabilities: 
   { browserName: 'googlechrome',
     platformName: 'Windows 10',
     browserVersion: 'latest',
     'sauce:options': { screenResolution: '1600x1200', seleniumVersion: '3.141.59' },
     'goog:chromeOptions': { w3c: true } } }
```

**Describe the bug**
w3c caps do not work with chrome and waitForDisplayed()

**To Reproduce**
create a test that uses waitForDisplayed and pass w3c caps to saucelabs for chrome, run test, fails with error:

"waitUntil condition failed with the following reason: Cannot call non W3C standard command 
while in W3C mode"

**Expected behavior**
`waitForDisplayed()` should work wtih w3c protocol and chrome, as it does with jsonwp

**Log**
https://gist.github.com/pmerwin/97a385b0cef1592b79bf6b0b6cbe01d6
failed sauce job:
https://app.saucelabs.com/tests/ff2224acc9484b1f938be2821e0548b4

**Additional context**
when using jsonwp caps, all is well:

this may be because we need chrome 75 and its driver and sauce is on 74 .etc
"ChromeDriver 75.0.3770.8
Supports Chrome version 75

The most noticeable change is ChromeDriver now runs in W3C standard compliant mode by default. "

**Updated with proper markdown**

**Comment by wswebcreation** [comment]
@christian-bromann @pmerwin 

This is not only happening with Canary, but also with Mac OSX on Chrome 74, see https://app.eu-central-1.saucelabs.com/tests/336e32d1c363432b88eb38b3f1c455d3

**Comment by wswebcreation** [comment]
This needs to be fixed in WebdriverIO, the is displayed has been removed from the W3C, we need to fix it the same way as for Safari 🤦🏼‍♂️
