### ISSUE TITLE
Specs & exclude configuration under capabilities are ignored and hence not working well with suite and spec command line args.

### ISSUE THREAD

**Issue by yamkay** [webdriverio/webdriverio#3925]
**Environment:**
 - **WebdriverIO version:** 5.8.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 8.11.2
 - **NPM version:** 5.8.0
 - **Additional wdio packages used (if applicable):** wdio-spec-reporter, wdio-allure-reporter, wdio-sauce-service

**Config of WebdriverIO**
```
exports.config = {
    suites: {
        p0: [
            './tests/**/*.p0.test.js'
        ],
       p1: [
            './tests/**/*.p1.test.js'
        ],

    },
    capabilities = [
      {
    browserName: "googlechrome",
    platformName: "macOS 10.13",
    browserVersion: "72.0",
    exclude: ["./tests/mobile/**"]
    },
  {
    browserName: "Chrome",
    appiumVersion: "1.9.1",
    deviceName: "Samsung Galaxy S9 WQHD GoogleAPI Emulator",
    deviceOrientation: "portrait",
    platformVersion: "8.0",
    platformName: "Android",
    exclude: ["./tests/desktop/**"]
  }
]
}
```

**Describe the bug**
Whenever we pass the command line arguments (such as --suite, --spec), the specs & exclude configurations under each capability are ignored.

**To Reproduce**

1. Create a folder "tests"
2. Under tests folder, create 2 folders - desktop, mobile
3. Under desktop folder, add a spec file with the name "file1.p0.test.js"
4. Under mobile folder, add a spec file with the name "file2.p1.test.js"
5. Say you are using the above configuration in a config file called "wdio.config.js"
6. Now run only p0 tests with command line arguments - **wdio wdio.config.js --suite p0**
7. **You can observe that file1.p0.test.js (under desktop folder) will be run on both of the above capabilities though it has been excluded from the 2nd capability.**

**Expected behavior**
If the spec file from a suite/spec, which is passed from command line, is excluded under a capability, then it should not execute on it.

Similarly, if there are specific specs configured under a capability, then only those specs should be run on the same capability without running the other tests.

**Additional context**

If the method "getSpec" in the below file is refactored to the following solution, then I guess it should work. Please confirm.

https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-config/src/lib/ConfigParser.js

**Solution**

```
getSpecs (capSpecs, capExclude) {
        let specs = ConfigParser.getFilePaths(this._config.specs)
        let spec  = Array.isArray(this._config.spec) ? this._config.spec : []
        let exclude = ConfigParser.getFilePaths(this._config.exclude)
        let suites = Array.isArray(this._config.suite) ? this._config.suite : []  
        let suiteSpecs = []

        /**
         * check if user has specified a specific suites to run
         */
        if (suites.length > 0) {
            for (let suiteName of suites) {
                // ToDo: log warning if suite was not found
                let suite = this._config.suites[suiteName]
                if (suite && Array.isArray(suite)) {
                    suiteSpecs = suiteSpecs.concat(ConfigParser.getFilePaths(suite))
                }
            }

            if (suiteSpecs.length === 0) {
                throw new Error(`The suite(s) "${suites.join('", "')}" you specified don't exist ` +
                                'in your config file or doesn\'t contain any files!')
            }
        }

        // Allow --suite and --spec to both be defined on the command line
         if (suites.length > 0 || spec.length > 0) {
            
            // Removing any duplicate tests that could be included
            const tmpSpecs = spec.length > 0 ? [...spec, ...suiteSpecs] : suiteSpecs
            let commandLineSpecs = [...new Set(tmpSpecs)]
            specs = specs.filter(spec => commandLineSpecs.indexOf(spec) > 0)
        }

         /**
         * if there is specs configuration under a capability, 
         * then it should take only this specs and filter against the main specs
         */
        if (Array.isArray(capSpecs)) {
            const cSpecs = ConfigParser.getFilePaths(capSpecs)
            specs = specs.filter(spec => cSpecs.indexOf(spec) > 0)
        }

        if (Array.isArray(capExclude)) {
            exclude = exclude.concat(ConfigParser.getFilePaths(capExclude))
        }

        return specs.filter(spec => exclude.indexOf(spec) < 0)
    }
```

**Comment by yamkay** [comment]
@christian-bromann : This seems to be an issue according to the documentation. Could you please confirm it so that I can raise the PR.

**Comment by klamping** [comment]
Where in the documentation did you see that you can use `exclude` in the capabilities? I'm pretty sure you can only use `specs`. Raising a PR is a great idea if you want to get this feature added! 👍

**Comment by yamkay** [comment]
@klamping : Even specs under capabilities are ignored when suite and specs are provided from commandline. By the way, please find below the documentation for
 exclude option under capabilities - https://webdriver.io/docs/configurationfile.html

<img width="1259" alt="Screenshot 2019-05-08 10 25 09" src="https://user-images.githubusercontent.com/17017971/57395196-57892580-717c-11e9-81fe-0b0b541777b5.png">

**Comment by klamping** [comment]
@yamkay 👍 thanks for sending that along

**Comment by ergbouncex** [comment]
This seems to be working for me:
```
  getSpecs(capSpecs, capExclude) {
    let specs = ConfigParser.getFilePaths(this._config.specs);
    let spec = Array.isArray(this._config.spec) ? this._config.spec : [];
    let exclude = ConfigParser.getFilePaths(this._config.exclude);
    let suites = Array.isArray(this._config.suite) ? this._config.suite : [];
    /**
     * check if user has specified a specific suites to run
     */

    if (suites.length > 0) {
      let suiteSpecs = [];

      for (let suiteName of suites) {
        // ToDo: log warning if suite was not found
        let suite = this._config.suites[suiteName];

        if (suite && Array.isArray(suite)) {
          suiteSpecs = suiteSpecs.concat(ConfigParser.getFilePaths(suite));
        }
      }

      if (suiteSpecs.length === 0) {
        throw new Error(`The suite(s) "${suites.join('", "')}" you specified don't exist ` + 'in your config file or doesn\'t contain any files!');
      } // Allow --suite and --spec to both be defined on the command line
      // Removing any duplicate tests that could be included

      let tmpSpecs = spec.length > 0 ? [...specs, ...suiteSpecs] : suiteSpecs;

      if (Array.isArray(capSpecs)) {
        tmpSpecs.push(ConfigParser.getFilePaths(capSpecs));
      }

      if (Array.isArray(capExclude)) {
        exclude = exclude.concat(ConfigParser.getFilePaths(capExclude));
      }

      specs = [...new Set(tmpSpecs)]
      return specs.filter(spec => exclude.indexOf(spec) < 0);
    }

    if (Array.isArray(capSpecs)) {
      specs = specs.concat(ConfigParser.getFilePaths(capSpecs));
    }

    if (Array.isArray(capExclude)) {
      exclude = exclude.concat(ConfigParser.getFilePaths(capExclude));
    }

    return specs.filter(spec => exclude.indexOf(spec) < 0);
  }
```

**Comment by afsarali273** [comment]
@christian-bromann  In webdriverio v4.14.4 am facing similar issue with cucumber . seems multiple browsers instance opens up then closes whichever is not included in the cucumber tags option.

can this issue be fixed with  v4 for cucumber feature files  ?

**Comment by wswebcreation** [comment]
@afsarali273

Your question is not releated to this topic, I already saw you used Gitter and that's the right place. For the future please only ask questions on Gitter.
