### ISSUE TITLE
webdriver.io says "1 failed" but waits 30-40 seconds before tell me what specifically failed

### ISSUE THREAD

**Issue by mo** [webdriverio/webdriverio#3926]
![image](https://user-images.githubusercontent.com/7117/57185211-888d0000-6ec7-11e9-80f1-6ee49fc6f7bb.png)

When a fail happens you only see (above) this for a while and only once the suite/file has finished does it actually tell you what specifically the fail was. When iterating on testcases, this get a bit annoying after a while; I just want to know what the fail was immediately when it happens so I can CTRL-C the rest of the test run and just fix the issue instead.

**Comment by CrispusDH** [comment]
Please, show your test, config and dependencies.

**Comment by klamping** [comment]
FYI, you can also set `bail` to 1, which will automatically end the tests on the first failure:
https://webdriver.io/docs/options.html#bail

**Comment by mgrybyk** [comment]
Please try in next release again.

Console messages and failures are now printing out immediately
