### ISSUE TITLE
Typescript typing for waitUntil method

### ISSUE THREAD

**Issue by MunGell** [webdriverio/webdriverio#3927]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.7.15
 - **Mode:** Standalone mode
 - **Node.js version:** v10.4.1
 - **NPM version:** 6.9.0
 - **Browser name and version:** Chrome
 - **Platform name and version:** Linux
 - **Additional wdio packages used (if applicable):** @wdio/selenium-standalone service

**Config of WebdriverIO**

N/A

**Describe the bug**

At the moment typing for `waitUntil` method is [like this](https://github.com/webdriverio/webdriverio/blob/8dc24c4f4cf4ccf774f2b0c15fc57550a3ba0af4/scripts/templates/webdriverio.tpl.d.ts#L179):

```typescript
waitUntil(
    condition: () => boolean,
    timeout?: number,
    timeoutMsg?: string,
    interval?: number
): void
```

However, in `waitForDisplayed` method it is used [like this](https://github.com/webdriverio/webdriverio/blob/8dc24c4f4cf4ccf774f2b0c15fc57550a3ba0af4/packages/webdriverio/src/commands/element/waitForDisplayed.js#L48):

```
return this.waitUntil(async () => reverse !== (await this.isDisplayed()), ms, errorMsg);
```

In this implementation it returns `Promise<boolean>`, while typing suggests it needs to be just `boolean`.

When I try to implement similar logic in my code - it throws an error.

I believe typing needs to be updated.

**To Reproduce**

N/A

**Expected behavior**

N/A

**Log**

N/A

**Additional context**

N/A

**Comment by MunGell** [comment]
Also, I believe `waitForDisplayed` typing needs to be updated as well:

```typescript
waitForDisplayed(
    ms?: number,
    reverse?: boolean,
    error?: string
): boolean;
```

While it's implementation is returns the output of `waitUntil` method.

`waitUntil` is a void method, so `waitForDisplayed` will return the same

Correct me if I am wrong. Can create a separate issue if needed.

**Comment by mgrybyk** [comment]
Closed via https://github.com/webdriverio/webdriverio/pull/3928
