### ISSUE TITLE
OnComplete hook is not working

### ISSUE THREAD

**Issue by alexisrouse** [webdriverio/webdriverio#3931]
**Environment**
 - **WebdriverIO version:** 5.7.14
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 11.14.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Chrome 73.0
 - **Platform name and version:** macOS 10.14.3
 - **Additional wdio packages used (if applicable):** @wdio/spec reporter, @wdio/selenium-standalone service, @wdio/allure-reporter, @wdio/mocha-framework

**Config of WebdriverIO**
See "suite.mocha.conf.js" in  https://github.com/blueimp/wdio

**Describe the bug**
The "OnComplete" hook is not being executed after the execution is finished. You can use this boilerplate project to run it and test: https://github.com/blueimp/wdio. I tried the same in my project and it doesn't work either. You can see that when you run the test with the command : "npm run test" the "that's it" text is never showed in the command-line. 

**To Reproduce**

1 - Download the boilerplate project : https://github.com/blueimp/wdio
2 - Run the command : npm run test

**Expected behavior**
The text "that's it" must be displayed in the command-line

**Comment by baruchvlz** [comment]
Dup #3869
