### ISSUE TITLE
isW3C can't be determined for Browserstack responce

### ISSUE THREAD

**Issue by wswebcreation** [webdriverio/webdriverio#3935]
**Environment (please complete the following information):**
 - **WebdriverIO version:** latest
 - **Mode:** Testrunner
 - **If WDIO Testrunner, running sync/async:** both
 - **Node.js version:** -
 - **NPM version:** -
 - **Browser name and version:** Edge
 - **Platform name and version:** Windows
 - **Additional wdio packages used (if applicable):** `@wdio/webdriver`

**Config of WebdriverIO**
```js
    capabilities: [{
        'bstack:options': {
            'os': 'Windows',
            'osVersion': '10',
            'local': 'false',
            'seleniumVersion': '3.14.0'           
        },
        'browserName': 'Edge',
        'browserVersion': '18.0',
    }],
```

**Describe the bug**
Browserstack is not providing the _right_ capabilities to determine if the instance is a W3C instance. The response contains the following data

```js
const response = {
    'acceptInsecureCerts': false,
    'browserName': 'MicrosoftEdge',
    'browserVersion': '44.17763.1.0',
    'pageLoadStrategy': 'normal',
    'platformName': 'windows',
    'setWindowRect': false,
    'timeouts': { 'implicit': 0, 'pageLoad': 300000, 'script': 30000 },
    'proxy': {},
    'webdriver.remote.sessionid': '993e34c09b8e0d9317347980ab4e186ddc6c06b2'
}
```
We don't get back a `platformVersion` and the `setWindowRect` is `false` meaning BrowserStack will never be seen as a W3C instance, see also

https://github.com/webdriverio/webdriverio/blob/master/packages/webdriver/src/utils.js#L193

**To Reproduce**
-

**Expected behavior**
Or BrowserStack needs to fix this, or WebdriverIO needs to come with a patch

**Log**
see above

**Comment by christian-bromann** [comment]
The fix for this should be in https://github.com/webdriverio/webdriverio/blob/master/packages/webdriver/src/utils.js#L216 by changing it to:

```
Object.keys(capabilities).includes('setWindowRect')
```
