### ISSUE TITLE
Provide smart assertion library specialised on working with elements

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#3937]
Let's provide a native embedded assertion library that helps people to work and assert on elements. Suggestions on functionality are welcome. 

So far there is a chai extension for WebdriverIO and @abjerstedt already works on improving this.

Any suggestions on how this should look like are welcome 😊

**Comment by vbyjsue** [comment]
I like the concept of the chai extension, but when you use page objects it doesn't make sense to use the locator when asserting, since it's most likely defined only to return an element.
I have implemented my own assertions, based on chai extension, that uses the element it's chained on.
This makes assertions more intuitive I think:
`StartPage.components.stickyMenu.elements.searchItem.should.be.visible` 
`Bomben.components.alert.should.have.text(Bomben.data.paymentConfirmationText)`
A native assertion that could be used like this would be a nice feature.

**Comment by abjerstedt** [comment]
@vbyjsue UNLESS you are using a robot model, why would your assertions beside in the pageObject? Also, calling the assertion natively on the element isn't very explicit. Personally, I want my assertions to be very explicit.

I'm planning on doing something like this:
expect( () => StartPage.searchItem).to.eventually.be.visible() <- Retries the assert
expect(StartPage.searchItem).to.eventually.be.visible() <- No Retry

Note: The actual parameter needs to be a callback/delegate. If we don't wrapper this in a function, the parameter will be resolved prior to being passed into the expect, and will NEVER properly retry.

**Comment by christian-bromann** [comment]
> expect( () => StartPage.searchItem).to.eventually.be.visible() <- Retries the assert
> expect(StartPage.searchItem).to.eventually.be.visible() <- No Retry

I like that 👍

**Comment by abjerstedt** [comment]
Oops.... i meant:
expect( () => StartPage.searchItem).to.eventually.be.visible() <- Retries the assert
expect(StartPage.searchItem).to.be.visible() <- No Retry

**Comment by CrispusDH** [comment]
almost the same logic I have implemented in my own library that helps me when I want retrying assert something with re-fetching mechanism. https://github.com/CrispusDH/oi-verify
It was a little bit tricky as for me to implement useful error messages)

**Comment by vbyjsue** [comment]
> @vbyjsue UNLESS you are using a robot model, why would your assertions be inside the pageObject? Also, calling the assertion natively on the element isn't very explicit. Personally, I want my assertions to be very explicit.
> 
> I'm planning on doing something like this:
> expect( () => StartPage.searchItem).to.eventually.be.visible() <- Retries the assert
> expect(StartPage.searchItem).to.eventually.be.visible() <- No Retry
> 
> Note: The actual parameter needs to be a callback/delegate. If we don't wrapper this in a function, the parameter will NEVER properly retry.

The assertion is in the test, not in the Page object.  I have retries by default but I like your idea, makes it more clear.

**Comment by mgrybyk** [comment]
@abjerstedt do you have any plans to proceed working on this one?

**Comment by mgrybyk** [comment]
Having https://github.com/webdriverio/webdriverio/issues/4765 it should be a bit easier to implement. 
I've recently started to use jasmine's expect in mocha project and it looks really good. Should be even better with lazy load

**Comment by mgrybyk** [comment]
I have something already
https://www.npmjs.com/package/expect-webdriverio
