### ISSUE TITLE
Cannot access custom commands through multi-remote browser objects.

### ISSUE THREAD

**Issue by nami-varthakavi** [webdriverio/webdriverio#3939]
I have the following config file, 
```
capabilities: {
        chromeDriver: {
            capabilities: {
                browserName: 'chrome',
                platformName: 'Windows'
            }
        },
        firefoxDriver: {
            capabilities: {
                browserName: 'firefox',
                platformName: 'Windows'
            }
        }
    }
```
and I have the following custom command in a file called `test-id.js` 

```
const getElementByTestIdWeb = function(testId) {
    return $(`[data-testid = '${testId}']`);
};
module.exports = (function() {
    browser.addCommand('getElementByTestIdWeb', function(testId) {
        return getElementByTestIdWeb(testId);
    });
})();
```
The custom commands are added to the config, before block like this. 

```
 before: function() {
           require('../../custom-commands/test-id');
    }
```

In my test when I try to access the custom command for my `chromeDriver` browser object, I get an error saying `TypeError: chromeDriver.getElementByTestIdWeb is not a function`. Seems like the custom command is not attached to a multi-remote object but works fine with the `browser` object. This happens for every custom command I have, the above is just an example.

**Comment by christian-bromann** [comment]
You need to set the custom commands to the single browser itself if you want to access it, this way you only can do `chromeDriver.getElementByTestIdWeb()`.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by nami-varthakavi** [comment]
> You need to set the custom commands to the single browser itself if you want to access it, this way you only can do `chromeDriver.getElementByTestIdWeb()`.
> 
> Join our [![Gitter](https://camo.githubusercontent.com/f99733b13256cf0443f9186ebee1a11fae2bbd9a/68747470733a2f2f6261646765732e6769747465722e696d2f776562647269766572696f2f776562647269766572696f2e737667)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

I did post a question regarding this in the channel and was suggested to create an issue up here. Anyway thanks for the input.
