### ISSUE TITLE
Trouble using `element` functionality

### ISSUE THREAD

**Issue by hellatan** [webdriverio/webdriverio#394]
I've been struggling with using the `element` functionality and am always getting an error like the following:

    {
    message: 'RuntimeError\n(UnknownError: 13)Anunknownserver-sideerroroccurredwhileprocessingthecommand.\nProblem: eisnull\nBuildinfo: version: \'2.44.0\',
    revision: \'76d78cf\',
    time: \'2014-10-2320: 02: 37\'\nSysteminfo: host: \'hella.home\',
    ip: \'192.168.1.6\',
    os.name: \'MacOSX\',
    os.arch: \'x86_64\',
    os.version: \'10.10.1\',
    java.version": \'1.7.0_55\'\nDriverinfo: driver.version: unknown\u001b[
        1;30m\n\nCallstack: \n->element(".my-class-name")\n',
        name: 'RuntimeError',
        hasCallStack: true
    }

Even when using an id value or a regular tag name, i get a similar error message. This is what some of the code looks like i'm trying to test:

    client
        .url('https://site.com/')
        .element('.my-class-name',function (err, result) {
            console.log(err, result);
        })
        .call(done);

The `client` is setup similar to the mocha/chai/jasmine examples and I am seeing my other code run so  that configuration I'm not concerned about.

thoughts?

**Comment by christian-bromann** [comment]
`Problem: eisnull` sounds definitely weird. Could you try to run this simple script:

```js
var client = require('webdriverio').remote({
  desiredCapabilities: {
    browserName: 'firefox'
  }
});

client
  .init()
  .url('http://google.com')
  .element('input', function(err, res) {
    console.log(res.value);
  })
  .end();
```
It should return `{ ELEMENT: '0' }`

**Comment by hellatan** [comment]
@christian-bromann your code worked. It's my `client` instance that's messed up b/c I wrapped some basic setup stuff in a different module.  thanks!
