### ISSUE TITLE
Typescript types for waitUntil

### ISSUE THREAD

**Issue by jwalton** [webdriverio/webdriverio#3940]
**Environment (please complete the following information):**
 - **WebdriverIO version:** master
 - **Mode:** Standalone
 - **Node.js version:** 10.14.1
 - **NPM version:** 6.9.0
 - **Browser name and version:** Firefox 66.0.3
 - **Platform name and version:** OS/X Mojave 10.14.4

**Describe the bug**

```ts
        waitUntil(
            condition: () => boolean,
            timeout?: number,
            timeoutMsg?: string,
            interval?: number
        ): boolean
```

`condition` here is a function that returns a boolean, but in order for this to be useful in standalone mode, I want to write a function like:

```js
browser.waitUntil(
            function() {
                return browser.execute("return document.readyState;")
                    .then(function(result) {
                        state = result.value;
                        return result.value === 'complete';
                    });
            },
            ms,
            `Page did not load after ${ms} - ${state}`
        );
```

So this should probably be:

```ts
waitUntil(
    condition: () => boolean | Promise<boolean>,
    timeout?: number,
    timeoutMsg?: string,
    interval?: number
): boolean
```

Also, why is the return type `boolean` instead of `Promise<boolean>`?  Or, is there perhaps some way to get a different set of types for standalone mode?

**Comment by christian-bromann** [comment]
Feel free to propose a PR

**Comment by christian-bromann** [comment]
fyi: you never need to check for the readyState of the page, at least not if you open an url with the navigate/url command. This already happens in the browser.

**Comment by jwalton** [comment]
Does this currently return a `boolean` because that's what's expected when using this with the wdio runner?

**Comment by christian-bromann** [comment]
I am not totally sure but I think so yes. Of course if you use wdio testrunner with `@wdio/sync` installed it will return a boolean and without or using standalone it will return a promise containing a boolean.

**Comment by erwinheitzman** [comment]
This would be a wider change as all commands return a Promise in standalone does it not?

**Comment by jwalton** [comment]
I think the problem here is really that there are two different types here.

We have the global `browser` object when you're using the wdio runner, which is of type `BrowserObject`, but then when you're not using wdio and you call `const browser = await remote(...)`, the object you get back should be a different type.

I'd have to look into exactly what's defined on BrowserObject in a little more detail - make sure there's no functions that return a non-promise even in the "async" version - but you could generate the async object in TS with something along the lines of:

```ts
type BrowserObjectAsync = {
    [K in keyof BrowserObject]:
        (...params: Parameters<BrowserObject[K]>) => Promise<ReturnType<BrowserObject[K]>>;
}
```

**Comment by mgrybyk** [comment]
@jwalton yeah, sounds like a good idea, have to try it one day.
If you can help with PR it would be awesome!

**Comment by jwalton** [comment]
A bit swamped right now, but it's on my "sometime this month" todo list.  :)

**Comment by mgrybyk** [comment]
same for me, summer is busy time :)

I'll close this ticket for now because I'm going to do fix for waitUntil function only. Keep in mind that this have to be resolved globally in a good way. Thank you for mentioning that, feel free to raise PR or contact me if you have some questions
