### ISSUE TITLE
removeApp() not working for Android

### ISSUE THREAD

**Issue by srishti77** [webdriverio/webdriverio#3948]
What are you trying to achieve?
I want to be able to uninstall an Android app when the test cases are finished executing. I do not want to use the fullReset = 'true' because I have some test cases that would close the app using closeApp() and open Again. Hence I am using noReset= true. 

Since I am using noReset instead of fullReset I have to manually uninstall the app. For that, I want to use removeApp(). 

I tried the following version of removeApp:
1. removeApp('com.example.AppName'):
Error: Expected Parameter is String[]
2.  removeApp(['com.example.AppName']): 

unknown error: An unknown server-side error occurred while processing the command. Original error: Error finding if 'com.example.AppName' is installed. Original error: Error executing adbExec. Original error: 'Cannot read property 'replace' of undefined'; Stderr: ''; Code: 'undefined'

Details: 
Appium v1.12.1
node version: 8.12
webdriver io: 5.8.3

**Comment by christian-bromann** [comment]
> Error finding if 'com.example.AppName' is installed. Original error: Error executing adbExec. Original error: 'Cannot read property 'replace' of undefined'; Stderr: ''; Code: 'undefined'

Can you report this bug in Appium? This is not coming from WebdriverIO. Thanks!

**Comment by mykola-mokhnach** [comment]
@christian-bromann I checked the issue and it seems like the problem is on the client side. The server expects application id to be passed as a string, but the client passes an array of strings instead:

> [HTTP] --> POST /wd/hub/session/28ec83f1-5ca6-456c-8133-d05b7b46ece3/appium/device/remove_app
> [HTTP] {"appId":["com.example.AppName"]}

**Comment by christian-bromann** [comment]
@mykola-mokhnach so it is a spec issue?

**Comment by mykola-mokhnach** [comment]
Which spec do you mean? http://appium.io/docs/en/commands/device/app/remove-app/ says the argument should be a string

**Comment by christian-bromann** [comment]
I mean the WebdriverIO spec: https://github.com/webdriverio/webdriverio/blob/master/packages/webdriver/protocol/appium.json#L458 .. it also states that it should be a string. @srishti77 can you make sure to run WebdriverIO with the latest version?

**Comment by srishti77** [comment]
Yes, I updated the webdriverio to 5.8.3 and it works now. Thank you very much to both of you.
