### ISSUE TITLE
Chaining promises

### ISSUE THREAD

**Issue by Dremora** [webdriverio/webdriverio#395]
I've recently started using Webdriver.io, and one of the first issues I've faced is how to reuse common functionality between tests.

Let's say I have a panel in my application which I want to open/close in numerous places across the test suite. In a synchronous world, one would extract the code into a function called `togglePanel()`. However, let's say there is a short animation performed to transition panel from closed to opened state and backwards. The operation becomes asynchronous (as, generally speaking, would be most UI-related operations). In a node.js world, one would resolve this by relying on callbacks: `togglePanel(cb)`.

However, in case of Webdriver.io, it seems that the only *documented* way to have shared asynchronous code is to create a custom command. Registering a custom command essentially makes it global, being a property of the `client` object. It's possible to put commands into different files, however, they have to bear unique names as they will share the same namespace.

There is one trick I thought could work. Each command returns a promise, so I tried to do something quite common in the promise world: return another promise from the `.then` handler. Consider the following code:

```javascript
function togglePanel () {
  return client
    .click('#panel button.toggle')
    .pause(500)
}
```
(this block is running within a Mocha test):
```javascript
...
client
  .url('http://localhost:3000/')
  .then(togglePanel)
  .then(togglePanel)
  .then(togglePanel)
  .call(done)
```

What happens is panel gets properly toggled twice, but as soon as the 3rd toggle begins, `done()` executes immediately. It doesn't matter which command I use instead of `call` - they all seem to execute in parallel with the last `then()` handler.

I understand there might have been no intention to make this work, but I'd like to be able to chain promises as shown above (which would be Promises/A+-compliant) or have something similar for modularizing my code without polluting global `client` object.

**Comment by christian-bromann** [comment]
hi @Dremora,
there seems to be a problem with WebdriverIOs promise chaining. If a `call` command gets executed after a `then` method, the PromiseHandler doesn't wait until the promise gets full filled.

You have two options:
1. use `call` instead of `then`, if you execute commands within a `call` function, WebdriverIO (chainit) is smart enough to chain these commands properly. Checkout [this example](https://github.com/webdriverio/webdriverio/blob/master/test/spec/functional/chaining.js).
2. execute any random function (like `url` without any parameters) between the last `then` and `call`

In general, if you want to extract common used command steps to reuse them in your test and without using `addCommand`, I would recommend the following scheme:

__togglePanel.js__
```js
module.exports = function() {
    this.click("#panel button.toggle").pause(500);
};
```
in your test:
```js
var togglePanel = require('./fixtures/togglePanel');
// ...
client
    .click('#button')
    .call(togglePanel);
    // ...
```

**Comment by christian-bromann** [comment]
Seems that commands get chained properly .. problem is the `pause` command. It is not effective at this position because there is no command after `pause`. ;-)

**Comment by Dremora** [comment]
Thanks for the reply.
There is nothing special about the `pause` command - the last promise in a chain is always ignored, no matter what is executed afterwards. It's also not just the `call` that gets executed immediately, not waiting for the previous promise to resolve. See example below.

I've been using 2nd option up until now (in a form of empty .then call, `.then(function () {})`). However, remembering to add it it's a quite error-prone procedure, acting more as a workaround than as a proper solution.
I've tried to replace .then calls with .call and it seems to work in *most* cases. There is one case where it didn't help. Consider the following code:

```javascript
it('should create workspaces', function (done) {
  browser
    .element('.swimlane')
    .then(function (info) {
      return browser.moveTo(info.value.ELEMENT, 1, 40)
    })
    // .then(function () {})
    .buttonPress()
    .setValue('.workspace input', 'Test Workspace')
    .keys(['\ue007'])
    .call(done)
});
```

Here I need to use results of a previous command to perform another asynchronous operation, and promises fully support this flow. The code above will fail the test, however, because buttonPress() will occur before mouse is moved, unless line 7 is commented out.
Plain callbacks would work, as shown in your example, but I prefer to stay away from them as much as possible, especially given the fact that promise support is *almost* there.

**Comment by christian-bromann** [comment]
[moveTo](http://webdriver.io/api/protocol/moveTo.html) actually takes a query string, so you don't need to call element first. Also is this whole routine of move to an element and do a button press action handled by the [`leftClick`](http://webdriver.io/api/action/leftClick.html) command. Try this code example, it should do the same trick:

```js
it('should create workspaces', function (done) {
  client
    .leftClick('.swimlane') // just `click` should work as well
    .setValue('.workspace input', 'Test Workspace')
    .keys('Enter')
    .call(done)
});

Yesterday I tried your example with a slightly change:

```js
var webdriverio = require('webdriverio'),
    client = webdriverio.remote({
        desiredCapabilities: {
            browserName: 'firefox'
        }
    });


function togglePanel(text) {
    return function() {
        return client
            .execute(function(text, done) {
                document.body.innerHTML += text + "<br>";
            }, text);
    }
}

describe("test", function() {

    before(function(done) {
        client.init(done);
    });

    it('test', function(done) {

        client
            .url('http://google.com/')
            .execute(function() {
                document.body.innerHTML = "";
            })
            .then(togglePanel("then #1"))
            .then(togglePanel("then #2"))
            .then(togglePanel("then #3"))
            // .pause(3000) // enable this to see everything
            .call(done)

    });

    after(function(done) {
        client.end(done);
    });

});
```
When executing this script with `mocha example.js -t 9999999` I can't see the `then #3` either but according to the selenium logs it got executed before the session was deleted:

```txt
14:02:28.764 INFO - Executing: [execute script: return (function (text, done) {
                document.body.innerHTML += text + "<br>";
            }).apply(null, arguments);, [das ist nummer 3]])
14:02:28.771 INFO - Executing: [delete session: 2d98c111-61bd-41e2-a5da-c60b3102e802])
14:02:28.780 INFO - Done: [execute script: return (function (text, done) {
                document.body.innerHTML += text + "<br>";
            }).apply(null, arguments);, [das ist nummer 3]]
14:02:28.919 INFO - Done: [delete session: 2d98c111-61bd-41e2-a5da-c60b3102e802]
```

But since the browser closes after that last command he isn't able to render that change to the page anymore, maybe the same applies to the click reaction.

Do you have a small example script that proves the fact that the last then command doesn't get executed?

**Comment by Dremora** [comment]
Well, the execution happens, the execution order is wrong though.
See the following example:

```javascript
var webdriverio = require('webdriverio'),
client = webdriverio.remote({
  desiredCapabilities: {
    browserName: 'chrome'
  }
});


function togglePanel(text) {
  return function() {
    return client
    .execute(function(text, done) {
      document.body.innerHTML += text + "<br>";
    }, text);
  }
}

describe("webdriverio", function() {

  before(function(done) {
    client.init(done);
  });

  it('should follow promise order semantics', function(done) {
    client
    .url('http://google.com/')
    .execute(function() {
      document.body.innerHTML = "";
    })
    .then(function () {
      return client
      .pause(2000)
      .then(togglePanel("then #1"))
    })
    .then(togglePanel("then #2"))
    .pause(3000)
    .call(done);
  });

  after(function(done) {
    client.end(done);
  });

});

```

I expect to see **'then 1'** followed by **'then 2'**, but the text appears in reverse order.

**Comment by christian-bromann** [comment]
ohh gotcha, yeah that seems not about to be right.

**Comment by syzer** [comment]
is it possible to use bluebird promise wrapper... is much better

```js
TypeError: Object #<WebdriverIO> has no method 'apply'
    at c:\xampp\htdocs\testJS\html-scrapers\node_modules\webdriverio\lib\utils\PromiseHandler.js:82:52
```

**Comment by christian-bromann** [comment]
See #402
