### ISSUE TITLE
Decrease the amount of installation questions by having automatic defaults that you feel are most popular

### ISSUE THREAD

**Issue by nadvolod** [webdriverio/webdriverio#3951]
**Is your feature request related to a problem? Please describe.**
When setting up webdriverio it's a bit annoying to keep providing the same values to the installation steps. There are several like all of the installation questions and the logging verbosity that I feel could be a default value that could later be overridden. Then, just don't even ask these questions. As a result, setup will be faster and easier

**Describe the solution you'd like**
Here is what I feel will provide a better user experience with less confusion.

- When someone picks a framework like mocha, reporter, extra services like sauce, it should be assumed that we want to install it. Why wouldn't we want to automatically install it?
- Automatically just pick a reporter for us, just default to spec maybe. I don't believe we need the option to decide which one we want, especially to get started
- Also, just default to a logging level as well that you feel is most useful.

This will reduce the installation process by about 4 or 5 questions and make setup even easier and a little less confusing :)

**Describe alternatives you've considered**

**Additional context**
https://screencast.com/t/jtt0ltU2

**Comment by WillBrock** [comment]
I agree.

**Comment by baruchvlz** [comment]
@christian-bromann Is this something that you might want? I'm was going to start working on #3915, figured I could take care of this as well since it's all sort of related.

**Comment by christian-bromann** [comment]
@baruchvlz yes we want this

**Comment by baruchvlz** [comment]
@christian-bromann  This was merged as part of #4010.

**Comment by christian-bromann** [comment]
closing
