### ISSUE TITLE
Can i run several appium server with different phones at the same time?

### ISSUE THREAD

**Issue by adadale** [webdriverio/webdriverio#3956]
Do i need to change the appiumlancher?To make it have several process?
export class AppiumLauncher {
    constructor() {
        this.logPath = null
        this.command = ''
        this.appiumArgs = []
    }

    async onPrepare(config) {
        const appiumConfig = config.appium || {}

        this.logPath = appiumConfig.logPath
        this.command = appiumConfig.command || this._getAppiumCommand()
        this.appiumArgs = this._cliArgsFromKeyValue(appiumConfig.args || {})

        const asyncStartAppium = promisify(this._startAppium)
        this.process = await asyncStartAppium(this.command, this.appiumArgs, this.waitStartTime)

        if (typeof this.logPath === 'string') {
            this._redirectLogStream(this.logPath)
        }
}

**Comment by wswebcreation** [comment]
Please ask these kinds of questions on the Gitter channel.

Going to close it now
