### ISSUE TITLE
Missing source code for 4.14.2, 4.14.3, and 4.14.4

### ISSUE THREAD

**Issue by nolanlawson** [webdriverio/webdriverio#3960]
Hi folks, I just wanted to let you know that there don't appear to be git tags associated with these npm releases:

- [4.14.2](https://www.npmjs.com/package/webdriverio/v/4.14.2)
- [4.14.3](https://www.npmjs.com/package/webdriverio/v/4.14.3)
- [4.14.4](https://www.npmjs.com/package/webdriverio/v/4.14.4)

The last 4.x release for which the git tag is available is [4.14.1](https://www.npmjs.com/package/webdriverio/v/4.14.1) ([git tag](https://github.com/webdriverio/webdriverio/releases/tag/v4.14.1)).

I did a diff of the npm tarballs and they don't appear to be malicious. However, it may make some folks suspicious not to be able to find source code for the code they're running. 🙂

**Comment by BorisOsipov** [comment]
Hi @nolanlawson 

v4 code here moved in boneyard. See https://github.com/webdriverio-boneyard/v4/tree/v4.14.4
