### ISSUE TITLE
`browser.alertAccept()` not working on Android

### ISSUE THREAD

**Issue by gabriele-sacchi** [webdriverio/webdriverio#3961]
I'm using [webdriver.io][1] to write a suite of [Appium][2] tests for a hybrid [Cordova][3] App.

    "appium": "^1.10.0",
    "wdio-appium-service": "^0.2.3",
    "wdio-jasmine-framework": "^0.3.8",
    "webdriverio": "^4.14.1",

I am trying to programmatically dismiss the **Location Permissions native modal** presented on App launch on top of the WebView.

I can easily do so in iOS using [browser.alertAccept()][4] but the latter does not seem to work for Android.

I also tried to switch to the native context to dismiss it but had no luck.

    function dismissLocationPermissions() {
      if (browser.isAndroid) {
        new WebView().switchToContext();
        browser.pause(2000);
        const ANDROID_ACCEPT_ALERT_SELECTOR = "//*[@class='android.widget.Button'][2]";
        // OR '*//android.widget.Button[@text="OK"]' ?
        $(ANDROID_ACCEPT_ALERT_SELECTOR).click();
        WebView().switchToContext();
      } else {
        browser.alertAccept();
      }
    }

How can I dismiss the native alert on Android using wdio?

[![enter image description here][5]][5]

  [1]: https://webdriver.io/
  [2]: http://appium.io/
  [3]: https://cordova.apache.org/
  [4]: http://v4.webdriver.io/v4.12/api/protocol/alertAccept.html
  [5]: https://i.stack.imgur.com/vM8zO.png

npm -v: 6.4.1
node -v: v11.2.0

**Comment by wswebcreation** [comment]
@gabriele-sacchi 

Please ask these kind of questions on Gitter, and not file it as an issue

**Comment by gabriele-sacchi** [comment]
`browser.alertAccept()` not working on Android is not an issue?

**Comment by wswebcreation** [comment]
No, it's not an issue

**Comment by christian-bromann** [comment]
> not working on Android is not an issue?

It is impossible to say without any logs

**Comment by wswebcreation** [comment]
@christian-bromann 

It was an issue in the xpath selector, we figured it out on Gitter
