### ISSUE TITLE
Ability to chain react selectors in large apps

### ISSUE THREAD

**Issue by simo-eskalera** [webdriverio/webdriverio#3965]
This may already be supported but I couldn't identify from the docs if one can chain multiple `.react$()` or `.react$$()` commands. The example listed in the docs is good for illustration, but real world apps have complex hierarchies with specific components reused across the component tree. In such case the ability to chain selector commands is needed.

Also, can we mix regular selectors with with react selectors to refine selection down to a specific non-component tag?

**Comment by baruchvlz** [comment]
Currently the react selectors do not support chaining commands as it is only a browser command. I have discussed this with @christian-bromann, and we agree that it would be a good addition. I am currently figuring out if there are any changes that need to be done to the [resq](https://github.com/baruchvlz/resq) library in order for WDIO to support this and what changes have to be done in WDIO as well.

**Comment by simo-eskalera** [comment]
@baruchvlz Thanks for the update and I'm glad this is on your radar. I'm surprised direct support for react selectors isn't popular yet with automation tools. I get that it's not a universal method but React is one of the leading techs driving web development today.

**Comment by baruchvlz** [comment]
> Also, can we mix regular selectors with with react selectors to refine selection down to a specific non-component tag?

Well, since the WDIO commands return WDIO Elements you can do something like `browser.react$('MyComponent').$('div.foo').shadow$('blah').react$('OtherComponent')`

The final React selector requires the additions of `react$` and `react$$` to the element commands, I started working on this, hopefully be done by the end of the week.

**Comment by baruchvlz** [comment]
@christian-bromann this can be closed since #3986 is merged.

**Comment by akornato** [comment]
Hey guys, mixing regular selectors with react selectors was @simo-eskalera 's merely additional question, the main functionality requested in this issue, i.e. chaining react selectors, is still not supported, so this shouldn't have been closed.

**Comment by christian-bromann** [comment]
> i.e. chaining react selectors, is still not supported

It should be. According to the PR things like `browser.react$('foo').react$('bar')` should be possible. If not please provide an example where it fails so we can investigate. Cheers!
