### ISSUE TITLE
Tests with browserstack

### ISSUE THREAD

**Issue by tschuliiia** [webdriverio/webdriverio#397]
Hey Christian!

If i'm trying to execute the examples, i got the following error message: i tried to install it, but that doesn't help.

module.js:340
    throw err;
          ^
Error: Cannot find module 'pragma-singleton'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/July/Documents/wdio/index.js:18:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

the good thing is, i managed to get my own code to run, there was a problem with the capabilities, the settings are a bit different to your example

**Comment by christian-bromann** [comment]
Hi @tschuliiia 

could you try to execute the following:

```sh
$ mkdir webdriveriotest
$ cd webdriveriotest
$ npm install webdriverio
$ BROWSERSTACK_USERNAME=<your-browserstack-username> BROWSERSTACK_ACCESS_KEY=<your-browserstack-key> node node_modules/webdriverio/examples/webdriverio.browserstack.js
```

it should output

```
webdriverio - Google zoeken
```

Make sure you replace `<your-browserstack-username> ` and `<your-browserstack-key>` with your real username and key.

**Comment by tschuliiia** [comment]
i also get the error message, that it can't find pragma singleton

**Comment by christian-bromann** [comment]
that should get installed by NPM automatically

**Comment by tschuliiia** [comment]
ok.. hmm strange

**Comment by christian-bromann** [comment]
yeah .. Maybe there was just a problem with the server connectivity. pragma-singleton is a dependency of WebdriverIO and should get installed when installing WebdriverIO
