### ISSUE TITLE
session not created  from disconnected: unable to connect to renderer.

### ISSUE THREAD

**Issue by kon8381** [webdriverio/webdriverio#3971]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version: 5.7.1
 - **Mode: WDIO TestRunner
 - **If WDIO Testrunner, running sync/async: sync
 - **Node.js version: 8.16.0
 - **NPM version: 6.4.1
 - **Browser name and version: Chrome 74.0.3729.131
 - **Platform name and version: Apple MacOS High Sierra, Version: 10.13.6
 - **Additional wdio packages used (if applicable): 
    "@wdio/cli": "5.7.1",
    "@wdio/local-runner": "5.7.1",
    "@wdio/mocha-framework": "5.7.0",
    "@wdio/spec-reporter": "5.7.0",
    "@wdio/selenium-standalone-service": "5.7.0",
    "@wdio/sync": "5.7.2",

**Config of WebdriverIO**
require('@babel/register');

exports.config = {
  runner: 'local',
  sync: true,
  specs: [
    //path to the functional tests
  ],
  mochawesomeOpts: {
    includeScreenshots: true,
    screenshotUseRelativePath: true
  },
  // ===================
  // Test Configurations
  // ===================
  logLevel: 'trace',
  coloredLogs: true,
  deprecationWarnings: true,
  bail: 0,
  screenshotPath: 'Tests/ScreenShots/',
  baseUrl: process.env.ci_url || 'https://www-test.xxx.com',
  waitforTimeout: 20000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  services: ['selenium-standalone'],
  host: 'localhost',
  port: 4444,
  maxInstances: 1,
  capabilities: [
    {
      browserName: 'chrome',
      'goog:chromeOptions': {
        args: [
          '--proxy-server=http://127.0.0.1:3128',
          '--proxy-bypass-list=localhost,127.0.0.1,*.xxx.com'
        ]
      }
    }
  ],

  framework: 'mocha',
  reporters: [
    'spec'
    // , 'mochawesome'
  ],
  reporterOptions: {
    outputDir: 'Tests/Reports'
  },
  mochaOpts: {
    ui: 'tdd',
    timeout: 600000,
    grep: '',
    retries: 1
  },
  onPrepare: function() {
    console.log('Running against ' + this.baseUrl);
    const fs = require('fs');

    // Create Report Directory
    if (!fs.existsSync(this.reporterOptions.outputDir)) {
      fs.mkdirSync(this.reporterOptions.outputDir);
    }

    // Create Screenshot Directory
    if (!fs.existsSync(this.screenshotPath)) {
      fs.mkdirSync(this.screenshotPath);
    }
  },
  before: function(capabilities, specs) {
    require('@babel/register');
    assert = require('chai').assert;
    wdioCommands = require('../helpers/wdioHelper').default;

    // Helper Variables
    helpers = require('accounts-tests-helpers');
    ecsbServices = helpers.ecsb;
    general = random = helpers.general;
    bannersDetails = helpers.banners;
    omniHelper = helpers.omniture;
  },
  afterTest: function(test) {
    // capture screenprint for assertion errors.  verify errors capture their own screenprint.
    if (
      test.passed === false &&
      test.err &&
      test.err.message.indexOf('Verify') === -1
    ) {
      const screenshotName =
        this.screenshotPath +
        test.parent +
        '_' +
        test.title +
        '_' +
        browser.capabilities.browserName +
        '.png';
      browser.saveScreenshot(screenshotName);
    }
  }
};

**Describe the bug**
****Chrome session is not created.****
session not created: session not created
from disconnected: unable to connect to renderer
  (Session info: chrome=74.0.3729.131)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Mac OS X 10.13.6 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 834 milliseconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'OF060VV3YEHTD6N', ip: '10.139.126.87', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_202'
Driver info: driver.version: unknown
    at getErrorFromResponseBody (/Users/kon8381/rx-qa/node_modules/webdriver/build/utils.js:343:10)
    at Request._callback (/Users/kon8381/rx-qa/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/Users/kon8381/rx-qa/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/kon8381/rx-qa/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/kon8381/rx-qa/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)

I have tried using the SeleniumArgs() and SeleniumInstallArgs() method to specify the version of chromedriver and selenium standalone service, but the Selenium Standalone service i have is trying to download the chromedriver version 2.43 everytime i run the scripts, (the chrome version i have is 74.0.3729.131)

**To Reproduce**

[Include code or an example repository that can easily be set up]

**Expected behavior**
The new chrome session has to be created and it should navigate me to the desired website.

**Log**
https://gist.github.com/kon8381/1e0b09dc8e38130ba2a4eec528e6513d

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
> i have is trying to download the chromedriver version 2.43 everytime i run the scripts, (the chrome version i have is 74.0.3729.131)

This is the wrong Chromedriver version. Please download the correct one here: http://chromedriver.chromium.org/downloads

**Comment by Pavithra24x7** [comment]
I'm also facing same kind of issue do we have any solution for it, here is the console logs

org.openqa.selenium.SessionNotCreatedException: 
session not created
from disconnected: unable to connect to renderer
  (Session info: chrome=87.0.4280.67)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Pavithra-prakasm.local', ip: 'fe80:0:0:0:c63:b597:4a14:4093%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.2', java.version: '11.0.8'
Driver info: driver.version: ChromeDriver
remote stacktrace: 0   chromedriver                        0x00000001047b31c9 chromedriver + 2261449
1   chromedriver                        0x0000000104db2623 chromedriver + 8549923
2   chromedriver                        0x0000000104629333 chromedriver + 647987
3   chromedriver                        0x0000000104616d65 chromedriver + 572773
4   chromedriver                        0x000000010462a673 chromedriver + 652915
5   chromedriver                        0x00000001045d2893 chromedriver + 293011
6   chromedriver                        0x00000001045cc7f3 chromedriver + 268275
7   chromedriver                        0x00000001045a5eca chromedriver + 110282
8   chromedriver                        0x00000001045a6e87 chromedriver + 114311
9   chromedriver                        0x0000000104784e19 chromedriver + 2072089
10  chromedriver                        0x0000000104790d62 chromedriver + 2121058
11  chromedriver                        0x000000010479095e chromedriver + 2120030
12  chromedriver                        0x000000010476be80 chromedriver + 1969792
13  chromedriver                        0x00000001047912e1 chromedriver + 2122465
14  chromedriver                        0x000000010477a6d9 chromedriver + 2029273
15  chromedriver                        0x00000001047a778f chromedriver + 2213775
16  chromedriver                        0x00000001047b8733 chromedriver + 2283315
17  libsystem_pthread.dylib             0x00007fff69e9be65 _pthread_start + 148
18  libsystem_pthread.dylib             0x00007fff69e9783b thread_start + 15
