### ISSUE TITLE
I am unable to use dragAndDrop on chrome browsers. Is that still not supported. 

### ISSUE THREAD

**Issue by BalpreetKaur1** [webdriverio/webdriverio#3972]
**Describe your question with as much detail as possible**
A clear and concise question that doesn't require too much conversation. Need more help? [Find us on Gitter](https://gitter.im/webdriverio/webdriverio)

**If it's about a specific piece of code, try and include some of it to support your question.**
[...]

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2]
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:** [e.g. 8.9.1]
 - **NPM version:** [e.g. 5.8.0]
 - **Browser name and version:** [e.g. Chrome 68]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Additional context**

**Comment by BalpreetKaur1** [comment]
selector needs to be typeof `string`
[chrome #0-0] Error: selector needs to be typeof `string`
[chrome #0-0]     at buttonUp() - dragAndDrop.js:30:83
[chrome #0-0]     at moveToObject([object Object]) - dragAndDrop.js:30:53
[chrome #0-0]     at buttonDown() - dragAndDrop.js:30:40
[chrome #0-0]     at moveToObject([object Object]) - dragAndDrop.js:30:17
[chrome #0-0]     at dragAndDrop([object Object], [object Object], 2000) - at element([object Object]) - moveToObject.js:47:17

**Comment by BalpreetKaur1** [comment]
Details:
"webdriverio": "^4.12.0"
npm- 5.6.0

**Comment by christian-bromann** [comment]
> selector needs to be typeof `string`

The error clearly states what the error here is. Since I don't have any additional info I will close.

**Comment by BalpreetKaur1** [comment]
well... if it was that simple, i would not have created the issue. The locators are all good and i have verified them in browser and in code as well.
Just wanted to check if dragAndDrop is all good to be used for chrome browsers? it was buggy until november last year.

**Comment by christian-bromann** [comment]
> Just wanted to check if dragAndDrop is all good to be used for chrome browsers?

It is, however it is difficult to give a better answer without logs nor a reproducible example. I can just assume what the problem here is and based on the error it seems that the command doesn't get a string as selector.

**Comment by BalpreetKaur1** [comment]
Never mind, it worked when i removed the refernce of web elements from another file and put it straightaway in command as below:browser.dragAndDrop("//div[@data-qa='btn:property-type:text']", "//section[contains(@data-qa,'page:')]//div//li");
