### ISSUE TITLE
Unable to swipe to the left on element - swiping inconsistencies

### ISSUE THREAD

**Issue by lucialuzuriaga** [webdriverio/webdriverio#3973]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.7.12
 - **Mode:** WDIO Test runner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.15.1
 - **NPM version:** 6.9.0
 - **Platform name and version:** iOS Simulator 12.1
 - **Additional wdio packages used (if applicable):** @wdio/jasmine-framework

**Describe the bug**
I have two test cases which interact with sliders. One swipes to the right, the other one to the left.

For the test that swipes right, I noticed that in order to actually swipe on the element I had to add some pixels of margin, otherwise it wouldn't work:

```
const yLocation = FiltersPage.rightSlider.getLocation('y');
const xLocation = FiltersPage.rightSlider.getLocation('x');
CategoriesPage.gestures.swipe({ x: xLocation + 5, y: yLocation + 5 }, { x: 400, y: yLocation + 5 });
```

However, I am unable to perform the swipe to the left even when adding or subtracting pixels. Needless to say, I have tried it without any addition or subtraction, and it doesn’t work either. There are no errors in the logs. What is even stranger, the test passes despite having the assertion failing -as it’s not finding the text that is displayed when you slide to the minimum.

I have tried the following:

```
const yLocation = FiltersPage.leftSlider.getLocation('y');
const xLocation = FiltersPage.leftSlider.getLocation('x');
CategoriesPage.gestures.swipe({ x: xLocation + 300, y: yLocation + 5}, { x: xLocation, y: yLocation + 5 });
```
and also without using the xLocation:
```
const yLocation = FiltersPage.leftSlider.getLocation('y');
const xLocation = FiltersPage.leftSlider.getLocation('x');
CategoriesPage.gestures.swipe({ x: 400, y: yLocation + 5}, { x: 20, y: yLocation + 5 });
```
```
const yLocation = FiltersPage.leftSlider.getLocation('y');
const xLocation = FiltersPage.leftSlider.getLocation('x');
CategoriesPage.gestures.swipe({ x: 400, y: yLocation + 5}, { x: -300, y: yLocation + 5 });
```

**Expected behavior**
Swiping on the element to the left should work as expected. 
Swiping to the right should work without the need to add or modify any pixel margin. 

**Additional context**
The Appium boilerplate provides several swiping gestures, but none of them swipe over an element, only on coordinates. I was expecting to be able to use the .swipeLeft() function shown on the API docs, but it's for v4. It would be nice to have all those features in v5 as well. Nevertheless, this still looks like a bug to me, unless I am not implementing the swipe properly. 

**Log**

> [0-0] 2019-05-15T09:43:14.238Z INFO webdriver: DATA { using: 'accessibility id', value: 'nearMeCell_slider' }
> [0-0] 2019-05-15T09:43:14.414Z INFO webdriver: RESULT { 'element-6066-11e4-a52e-4f735466cecf': '4D010000-0000-0000-2708-0000000
> 00000',
>    ELEMENT: '4D010000-0000-0000-2708-000000000000' }
> [0-0] 2019-05-15T09:43:14.418Z INFO webdriver: COMMAND getElementRect("4D010000-0000-0000-2708-000000000000")
> [0-0] 2019-05-15T09:43:14.419Z INFO webdriver: [GET] http://127.0.0.1:4723/wd/hub/session/cb46b39e-6005-4b14-9112-3c2fd31b68c3/
> element/4D010000-0000-0000-2708-000000000000/rect
> [0-0] 2019-05-15T09:43:14.514Z INFO webdriver: RESULT { y: 217, x: 7, width: 360, height: 32 }
> [0-0] 2019-05-15T09:43:14.515Z INFO webdriver: COMMAND touchPerform(<object>)
> [0-0] 2019-05-15T09:43:14.515Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session/cb46b39e-6005-4b14-9112-3c2fd31b68c3
> /touch/perform
> [0-0] 2019-05-15T09:43:14.515Z INFO webdriver: DATA { actions:
>     [ { action: 'press', options: [Object] },
>       { action: 'wait', options: [Object] },
>       { action: 'moveTo', options: [Object] },
>       { action: 'release' } ] }
> [0-0] 2019-05-15T09:43:15.611Z INFO webdriver: RESULT {}
> [0-0] 2019-05-15T09:43:16.612Z INFO webdriver: COMMAND findElement("accessibility id", "nearMeCell_slider")
> 2019-05-15T09:43:16.612Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session/cb46b39e-6005-4b14-9112-3c2fd31b68c3/eleme
> nt
> 2019-05-15T09:43:16.613Z INFO webdriver: DATA { using: 'accessibility id', value: 'cell_slider' }
> [0-0] 2019-05-15T09:43:16.781Z INFO webdriver: RESULT { 'element-6066-11e4-a52e-4f735466cecf': '4D010000-0000-0000-2708-0000000
> 00000',
>    ELEMENT: '4D010000-0000-0000-2708-000000000000' }
> [0-0] 2019-05-15T09:43:16.784Z INFO webdriver: COMMAND findElement("accessibility id", "20 km")
> [0-0] 2019-05-15T09:43:16.784Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session/cb46b39e-6005-4b14-9112-3c2fd31b68c3
> /element
> [0-0] 2019-05-15T09:43:16.784Z INFO webdriver: DATA { using: 'accessibility id', value: '20 km' }
> [0-0] 2019-05-15T09:43:16.875Z INFO webdriver: RESULT { error: 'no such element',
>    message:
>     'An element could not be located on the page using the given search parameters.',
>    stacktrace:
>     'NoSuchElementError: An element could not be located on the page using the given search parameters.\n    at XCUITestDriver.
> doNativeFind (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:130:13)' }
> [0-0] 2019-05-15T09:43:16.880Z INFO webdriver: COMMAND deleteSession()
> [0-0] 2019-05-15T09:43:16.880Z INFO webdriver: [DELETE] http://127.0.0.1:4723/wd/hub/session/cb46b39e-6005-4b14-9112-3c2fd31b68
> c3

Test Suites:	 1 passed, 1 total (100% completed)

**Comment by mgrybyk** [comment]
@lucialuzuriaga can you please provide wdio code instead of code from your test framework?

Please also see http://appium.io/docs/en/writing-running-appium/touch-actions/

WebdriverIO has no additional logic in terms of swiping

**Comment by lucialuzuriaga** [comment]
@mgrybyk I am using the swipe action provided in the Gestures helper:
https://github.com/webdriverio/appium-boilerplate/blob/master/tests/helpers/Gestures.js

For getting the location of X and Y, I'm using:
https://webdriver.io/docs/api/element/getLocation.html

Both URLs are provided by WebdriverIO. Do you have any suggestion as on how swiping on an element should be implemented in the code?

**Comment by wswebcreation** [comment]
@lucialuzuriaga 

Based on the log you provided the element is found 

```log
[0-0] 2019-05-15T09:43:16.784Z INFO webdriver: DATA { using: 'accessibility id', value: '20 km' }
[0-0] 2019-05-15T09:43:16.875Z INFO webdriver: RESULT { error: 'no such element',
message:
'An element could not be located on the page using the given search parameters.',
stacktrace:
'NoSuchElementError: An element could not be located on the page using the given search parameters.\n at XCUITestDriver.
```

This should work (if you have the proper selector

```js
// Get the element center position
const elmRectangles = browser.getElementRect($('~accessibilityID').elementId);
const elementXCenter = Math.round(elmRectangles.x + (elmRectangles.width /2))
const elementYCenter = Math.round(elmRectangles.y + (elmRectangles.height / 2));

// Determine the new position, in this case 10, because we are going to swipe it from it's position
// to the left, the new x position should always be between the 0 and the most right of the screen
// maybe use `brwoser.getWindowRect()` to get back the width and height of the screen
const newXPosition = 10;

Gestures.swipe(
  // Take the center of the element
  { x: elementXCenter, y:elementYCenter },
  // Swipe to the new position
  { x: newXPosition, y:elementYCenter },
);
```

I'm going to close this issue now because it's not an issue with WebdriverIO, it;s still open for discussion
