### ISSUE TITLE
failing to execute test cases with selenium 

### ISSUE THREAD

**Issue by thulasipavankumar** [webdriverio/webdriverio#3974]
**Environment (please complete the following information):**
 - **WebdriverIO version:**5.8.4
 - **Mode:** WDIO Testrunner
 - ****If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v10.15.1
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome 74
 - **Platform name and version: windows 7
 - **Additional wdio packages used (if applicable):** 
+-- @wdio/cli@5.8.3
+-- @wdio/local-runner@5.8.3
+-- wdio-local-runner@5.0.0-alpha.7
+-- wdio-mocha-framework@0.6.1

**Config of WebdriverIO**
```
exports.config = {
    runner: 'local',
    hostname: 'localhost',
    protocol: 'http',
    port: 4444,
    path: '/wd/hub',
    specs: ['./test/specs/**/*.js' ],
    exclude: [ ],
    maxInstances: 1,
    capabilities: [{
        browserName: 'chrome',
        version: 74,
        custom: true,
        platform: 'WINDOWS'
    }],
    logLevel: 'error',
    bail: 0,
    baseUrl: '',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 1,
    reporters: [],
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },
}

```
**Describe the bug**
webdriverio is not able to create a session  with the hub

**To Reproduce**
run webdriverio to run test cases on browser using selenium standalone hub with a node

**Expected behavior**
Test case should be able to run on the intended browser

**Log**
[config file wdio](https://gist.github.com/thulasipavankumar/561066cb158a9c6b794905d268c687dc
)

[selenium logs](https://gist.github.com/thulasipavankumar/e724efc11ad7b9a40089b19a3d4bcc94)

[webdriverlogs](https://gist.github.com/thulasipavankumar/5bc0fb479c469bacca8ff56af5c51e1f)

[node json](https://gist.github.com/thulasipavankumar/98fb066f5f5fd30e9493fdad15f14a63)

[test file](https://gist.github.com/thulasipavankumar/2ad97802494e7fe4a5e5ab0ec358a4ab)

**Additional context**
Command used to run selenium hub
`java -jar selenium-server-standalone-3.14.0.jar -role hub -debug`
Command used to run selenium node
`java -jar selenium-server-standalone-3.14.0.jar -role node -nodeConfig node.json`
Command used to run webdriverio tests
` #.\node_modules\.bin\wdio wdio.conf.js`

**Comment by mgrybyk** [comment]
Get familiarized with supported capabilities https://www.w3.org/TR/webdriver/#capabilities 

custom is not a part of w3c.

**Comment by thulasipavankumar** [comment]
@mgrybyk  can you please suggest me how to pass the values as non w3c capabilites in webdriverio because it is needed to decide my execution to a particular node

**Comment by mgrybyk** [comment]
@thulasipavankumar there is nothing to do with WebdriverIO itself, as it is mentioned here https://www.w3.org/TR/webdriver/#capabilities you have to use vendor prefixes.
