### ISSUE TITLE
Error element is no longer attached to the dom

### ISSUE THREAD

**Issue by houria** [webdriverio/webdriverio#3975]
I have an automation suite that runs on a desktop application devloped on C#, and our Windows apps using Appium Windowsdriver. 
Below the code executed after every test case to return to start page

		public virtual void StartPage()
		{
			Thread.Sleep(3000);
			// return a la page d'accueil
			// Click on "Affichage" 
			MySession.FindElementByXPath("/Pane[@Name=\"Bureau 1\"][@ClassName=\"#32769\"]/Window[@AutomationId=\"HostForm\"]/Group[@Name=\"Arrimer en haut\"][starts-with(@ClassName,\"WindowsForms10\")]/MenuBar[@Name=\"Menu principal\"][starts-with(@ClassName,\"WindowsForms10\")]/MenuItem[@Name=\"Affichage\"]").Click();

			//Click on  "Écran de demarage"
			MySession.FindElementByXPath("/Pane[@Name=\"Bureau 1\"][@ClassName=\"#32769\"]/Pane[starts-with(@ClassName,\"WindowsForms10\")]/Menu[starts-with(@ClassName,\"WindowsForms10\")]/MenuItem[@Name=\"Écran de démarrage\"]").Click();
		}

This is the automation suite :		
Launch application
1- Exucute first Test      test successed
2- Return to StartPage     test successed
3- Exucute second Test     test successed
4- Return to StartPage     test not successed "error message "element is no longer attached to the dom"
5- Exucute third Test
6- Return to StartPage
Close application

At step 4 the excucution is stoped with error that the element "Écran de demarage" in no longer attached to the dom.

can you help me plz on that.

**Comment by christian-bromann** [comment]
> can you help me plz on that.

No, we can only help out if you use WebdriverIO.
