### ISSUE TITLE
queryAppState not working correctly

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#3976]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.8.4
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10
 - **Browser name and version:** Chrome
 - **Platform name and version:** Android
 - **Appium version:** 1.13.0

**Describe the bug**
The `queryAppState` command is not sending the required parameters due to using an outdated method. It is trying to send a parameters payload for a GET command.
The command was changed from a GET to a POST 
=> https://github.com/appium/appium-base-driver/pull/185

**To Reproduce**
```javascript
    it.only('should return status 4 when invoking queryAppState on Android', function() {
        browser.isAndroid || this.skip();
        browser.url(`https://www.webdriver.io`);
        const state = browser.queryAppState('com.android.chrome');
        expect(state).to.be.eql(4);
    });
```

**Expected behavior**
The command should be executed successfully by sending the correct payload to Appium.
The reproducible test should pass.

**Log**
Using the command `browser.queryAppState('com.android.app')` sends a GET command to Appium with no payload, Appium spits out:
```
[HTTP] --> GET /wd/hub/session/[REDACTED]/appium/device/app_state {}
[debug] [W3C] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":[["appId"],["bundleId"]]} and you sent []
[HTTP] <-- GET /wd/hub/session/[REDACTED]/appium/device/app_state 400 15 ms - 11695 
```

**Comment by christian-bromann** [comment]
Let's continue convo in #3977
