### ISSUE TITLE
touchClick doesn't work with Appium

### ISSUE THREAD

**Issue by thevinci** [webdriverio/webdriverio#398]
I tested this out on 2 sites and I get this error. I thought the element became stale because of something specific to that site, but that looks like it is not the case. I am going to try to do a tap on the coordinates to see if that does anything.

```
info: --> POST /wd/hub/session {"desiredCapabilities":{"browserName":"chrome","version":"","javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"platform":"ANY","platformName":"Android","deviceName":"0123456789ABCDEF","requestOrigins":{"url":"http://webdriver.io","version":"2.4.3","name":"webdriverio"}}}
info: Client User-Agent string: webdriverio/webdriverio/2.4.3

...

RuntimeError: RuntimeError
     (StaleElementReference:10) An element command failed because the referenced element is no longer attached to the DOM.
     Problem: An element command failed because the referenced element is no longer attached to the DOM.

     Callstack:
     -> touchClick(".qbtn")
```

**Comment by christian-bromann** [comment]
@thevinci in which mode are you running your tests? Could you try to use an xPath selector?

**Comment by christian-bromann** [comment]
Struggled with the same problem today. Will fix this when tackling mobile on WebdriverIO again.

**Comment by tomasznapieralski** [comment]
Stale element exception comes when you are trying access WebElement when it is no longer in DOM.
Doing `init()` on object is not good enough. Before you are trying to use WebElement you should wait by this [waitForExist](http://webdriver.io/api/utility/waitForExist.html)(or other wait variation) before `click()`. If the element is truly not in DOM you will get better exception. You can mix implicit and explicit wait using [waitUntil](http://webdriver.io/api/utility/waitUntil.html) and [timeoutsImplicitWait](http://webdriver.io/api/protocol/timeoutsImplicitWait.html) by controling this you can calculate how many attempts will driver do.

**Comment by christian-bromann** [comment]
`touchClick` works with Appium (only Android though). Great answer @tomasznapieralski , thanks!
