### ISSUE TITLE
Accept array of functions for onPrepare and onComplete

### ISSUE THREAD

**Issue by wellwellmissesanderson** [webdriverio/webdriverio#3980]
It would be beneficial for the onPrepare and onComplete hooks to accept an array of functions instead of a single function.

I'm proposing using the ConfigParser to add any functions (or array of functions, if user passes as array) to an array on these hooks, as they do for the other capabilities hooks. 

This would require a Promise.all() in the launcher.js file inside wdio-cli as well.

**Comment by mgrybyk** [comment]
@wellwellmissesanderson why can't you just call multiple functions in these hooks instead?

**Comment by wellwellmissesanderson** [comment]
@mgrybyk My use case is as follows:

I am using object inheritance with our configuration objects inside my project. For the other hooks, I am able to grab the existing arrays in a parent object and append new function(s) to them, however I am unable to do this with these properties. 

ex. Obj2 is a capabilities object that inherits from Obj1. Obj1 has several methods listed under each hook. If I want to add a new method to the onPrepare or onComplete, I am forced to call super.onPrepare() in order to gain access to any methods listed on its parent. If I don't, and declare a new function value for the onPrepare/onComplete, my new method will override any existing ones and they will not be called. 

I would like the behaviours for these two hooks to be consistent with the other hooks. I have scoured the codebase and see where the improvements could be made. I would like to know if the decision to NOT provide multiple functions as an array to these two hooks was made or if their location inside the launcher.js has not been updated to behave like the hooks handled inside runner.js.

**Comment by mgrybyk** [comment]
```
const parentConf = { hook () {} }
const hook = parent.hook

const childConf = {
    ...parentConf,
    hook() {
        // do whatever needed here
        parent.hook()
        // do whatever needed here
    }
}
```

**Comment by mgrybyk** [comment]
To be honest I can't see any benefit in changing function to functions array at this point. 
It will be a breaking change for all existing users and is even more complex to handle

**Comment by wellwellmissesanderson** [comment]
I understand your solution, however if this feature follows the existing pattern it will not break existing users' implementation (at least the way I imagine). 

Currently users can pass EITHER a function OR an array of functions to a hook. 

I'm proposing we allow them the same options for the onPrepare and onComplete. So users that are currently passing a function will still be able to do so.

**Comment by naddison** [comment]
> To be honest I can't see any benefit in changing function to functions array at this point.
> It will be a breaking change for all existing users and is even more complex to handle

How would this be a breaking change, and its not complex. We already handle this in the other hooks?

**Comment by mgrybyk** [comment]
Mind proposing PR for that?

**Comment by naddison** [comment]
Will get PR for weekend.

**Comment by christian-bromann** [comment]
Please make it in a way that it is backwards compatible.
