### ISSUE TITLE
automationName missing in DesiredCapabilities type definitions

### ISSUE THREAD

**Issue by ost12666** [webdriverio/webdriverio#3984]

**Comment by aha-oretama** [comment]
I recognized that only some desiredCapabilities are defined by comparing follows.
* https://github.com/webdriverio/webdriverio/blob/master/scripts/templates/webdriver.tpl.d.ts#L211
* http://appium.io/docs/en/writing-running-appium/caps/

If it is ok to add all the appium DesiredCapabilities to webdriverio's type definition, I'll make PR for it.

**Comment by christian-bromann** [comment]
@ost12666 can you please elaborate further? What miss-behavior do you see and what do you expect!

**Comment by ost12666** [comment]
Nothing related to behavior of the code just at least one missing property in the type definitions.

I expect not having to do this:       (this.config.capabilities as any).automationName = "XCUITest"
