### ISSUE TITLE
Wrong typings for react$ and react$$

### ISSUE THREAD

**Issue by balukov** [webdriverio/webdriverio#3985]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.8.5
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** sync
 - **Additional wdio packages used (if applicable):** @wdio/sync

**Describe the bug**
file webdriverio-core.d.ts contains typings:
```
        react$$(
            props?: object,
            state?: object
        ): Element;
        react$(
            props?: object,
            state?: object
        ): Element;
```

**Expected behavior**
should be like
```
        react$$(
->        selector: string,
            props?: object,
            state?: object
->      ): Element[];
        react$(
->        selector: string,
            props?: object,
            state?: object
        ): Element;
```

In sync mode I can't use "react$" and "react$$"

Same problem for shadow:
```
        shadow$$(): void;
        shadow$(): void;
```

Should be:
```
        shadow$$(
            selector: string | Function
        ): Element[];
        shadow$(
            selector: string | Function
        ): Element;
```

**Comment by christian-bromann** [comment]
Mind making a PR?

**Comment by baruchvlz** [comment]
Wasn't this fixed [here](https://github.com/webdriverio/webdriverio/pull/3944/files)?

**Comment by mgrybyk** [comment]
Here is what we have in `webdriverio-core.d.ts`

```
react$$(
    selector?: string,
    props?: object,
    state?: object
): Element[];
react$(
    selector?: string,
    props?: object,
    state?: object
): Element;

...

shadow$$(
    selector: string | Function
): Element[];
shadow$(
    selector: string | Function
): Element;
```

Following works for me
```
const el6 = $('')
const shadowElem = el6.shadow$('')
const shadowElems = el6.shadow$$('')

const reactElem = browser.react$('')
const reactElems = browser.react$$('')
```

There is also some work ongoing on "React selectors to element commands" https://github.com/webdriverio/webdriverio/pull/3986

**Comment by mgrybyk** [comment]
The issue persists because we haven't released @wdio/sync !
Can you assist on that @christian-bromann , please ?

I think we have to release webdriver, webdriverio and @wdio/sync on every typings change.

**Comment by baruchvlz** [comment]
Hmm, the React selector types are still wrong. The `selector` parameter is not optional. Not really sure how these types are generated otherwise I could fix them in #3986

**Comment by mgrybyk** [comment]
I'll take a look

**Comment by mgrybyk** [comment]
@baruchvlz here is what I've found
```
 * @alias browser.react$
 * @param {String=} selector of React component
 * @param {Object=} props  React props the element should contain
 * @param {Object=} state  React state the element should be in
 * @return {Element}
```

changing it to 
```
 * @alias browser.react$
 * @param {string} selector of React component
 * @param {object=} props  React props the element should contain
 * @param {Array<any>|number|string|object|boolean=} state  React state the element should be in
 * @return {Element}
```
should do the trick. Similar for react$$

**Comment by baruchvlz** [comment]
Is there a way to do something like

```js
react$<P = object, S = any>(
  selector: string,
  props?: P,
  state?: Array<S> | string | object | number | boolean
): Element
```

Or do you think this might be overkill?

**Comment by mgrybyk** [comment]
So props maybe not be an object? 
I'd avoid doing that unless really needed because it might lead to some issues with Promise wrapping in async mode. 

The way to do it is exclude command from automatic types generation and move it to template file.

If you think it's really needed, you may try doing that, ping me in case you need some help.

Btw, array any

**Comment by baruchvlz** [comment]
Well, props can only be objects, but state can be any type other than functions.

The idea was more to be able to do something like:

```typescript
interface MyComponentProps {
  someProps: 'foo bar';
  
}

type MyComponentState = Array<Pick<SomeOtherInterface, 'someProp'>>

react$<MyComponentProps, MyComponentState>('MyComponent', props, state)

```

But yea, I guess since it just returns the Element, having these generic doesn't really make any sense.

**Comment by christian-bromann** [comment]
I will release @wdio/sync

**Comment by balukov** [comment]
Sorry for my absent, I tried with new @wdio/sync - everything is ok.
