### ISSUE TITLE
Element is not  clickable at point

### ISSUE THREAD

**Issue by utpal30** [webdriverio/webdriverio#3991]
- WebdriverIO version: [webdriverio@5.4.1]
 - Mode:  WDIO Testrunner
 - WDIO Testrunner, running sync/async: sync;
 - Node.js version: v8.9.0
 - NPM version: 6.4.1
 - Browser name and version: Chrome 74
 - Platform name and version: Ubuntu 16
 
when i click on the login button of the admin pannel it does not click and it gives the error as:

unknown error: Element <button class="md-raised submit-button md-primary md-button" type="submit" ng-transclude="" md-no-ink="" style="margin-top: 5px!important" ng-disabled="login.$invalid" ng-submit="adminLogin()" aria-disabled="false">...</button> is not clickable at point (578, 411). Other element would receive the click: <div ng-if="providersAvailable" class="ng-scope" style="">...</div>
  (Session info: chrome=74.0.3729.131)
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.4.0-148-generic x86_64)

Here is the screenshot of the loginh page.
![issueon](https://user-images.githubusercontent.com/49718045/58015260-6b3b7100-7b18-11e9-9023-d182f8bf0865.png)

This is the code which i m trying..
 it('Clicking on login button',async function(){
   
       const button = $('//*[@id="login-v2-form"]/form/button');
        button.click();
        browser.pause(3000);
    });

Expected behavior
I expected to clcik on the login button and move to the next page but it does not happen as it is not clicking on the login button.

Here is the link :
https://msdtest.devhippo.com/admin/

> Please use the correct markdown

**Comment by CrispusDH** [comment]
1. Could you show entire error message
2. Change your locator to `const button = $('[type="submit"]');`

**Comment by utpal30** [comment]
this is the entire error message..

error: Element <button class="md-raised submit-button md-primary md-button" type="submit" ng-transclude="" md-no-ink="" style="margin-top: 5px!important" ng-disabled="login.$invalid" ng-submit="adminLogin()" aria-disabled="false">...</button> is not clickable at point (578, 411). Other element would receive the click: <div ng-if="providersAvailable" class="ng-scope" style="">...</div>
  (Session info: chrome=74.0.3729.131)
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.4.0-148-generic x86_64).


I have tried const button = $(' [ type = "submit" ] ' );
but it is showing same error message.
Here is the screenshot
![loginissue](https://user-images.githubusercontent.com/49718045/58021505-acd41800-7b28-11e9-8b9f-daa15773a7bf.png)

**Comment by CrispusDH** [comment]
Thanks, screenshot is helpful.
Try to change locator to `const button = $('[type="submit"] .ng-scope' );

**Comment by erwinheitzman** [comment]
Normally there's no element inside a button.
Because the text is put inside of a <b> tag instead of being style directly with css you have to click this element instead.
So it's not a bug but instead it's expected behaviour as the text is indeed on top of the button.

**Comment by christian-bromann** [comment]
We will tackle this in #2866
