### ISSUE TITLE
custom capability support in webdriverio

### ISSUE THREAD

**Issue by thulasipavankumar** [webdriverio/webdriverio#3998]
**Describe your question with as much detail as possible**
I have custom capability set in my selenium nodes you can view the screen shot attached.
webdriverio is not able to execute the tests, whereas in selenium java client its executing.
 Please refer the payload  for both the request.

Can someone suggest me how to pass the custom capability in webdriverio config file

**Environment (please complete the following information):**
**WebdriverIO version:**5.8.4
Mode: WDIO Testrunner
**If WDIO Testrunner, running sync/async: sync
Node.js version: v10.15.1
NPM version: 6.4.1
Browser name and version: Chrome 74
**Platform name and version: windows 7
Additional wdio packages used (if applicable):
+-- @wdio/cli@5.8.3
+-- @wdio/local-runner@5.8.3
+-- wdio-local-runner@5.0.0-alpha.7
+-- wdio-mocha-framework@0.6.1

**Additional context**
### payload request done by webdriverio
```
{
	"capabilities":
	{
		"alwaysMatch":
		{
			"browserName":"chrome",
			"custom":true,
			"platformName":"WINDOWS"
		},
		"firstMatch":[{}]
	},
	"desiredCapabilities":
	{
		"browserName":"chrome",
		"custom":true,
		"platformName":"WINDOWS"
	}
}
```

### payload request done by selenium java client
```
{  
	"desiredCapabilities": 
	{
		"browserName": "chrome",
		"platform": "WINDOWS",
		"custom": true  
	},
	"capabilities": 
	{
		"firstMatch": 
		[{
			"browserName": "chrome",
			"platformName": "windows"
		 }]  
    }
}
```
![image](https://user-images.githubusercontent.com/3539745/58089082-47356980-7bc4-11e9-9892-049c3dc332de.png)

**Comment by mgrybyk** [comment]
There is nothing to do with webdriverio, please use vendor prefixes approach forced by https://www.w3.org/TR/webdriver/#capabilities
