### ISSUE TITLE
POST entries appearing in test body on report

### ISSUE THREAD

**Issue by adamsjoe** [webdriverio/webdriverio#3999]
**Environment (please complete the following information):**
```js
    "@wdio/allure-reporter": "^5.7.0",
    "@wdio/cli": "^5.7.0",
    "@wdio/local-runner": "^5.7.0",
    "@wdio/mocha-framework": "^5.7.0",
```
**Config of WebdriverIO**
```js
  reporters: ['allure'],
  reporterOptions: {
    allure: {
      outputDir: 'allure-results',
      disableWebdriverStepsReporting: false,
      disableWebdriverScreenshotsReporting: false,
      useCucumberStepReporter: true,
    },
  },
```

**Describe the bug**
Not sure if this is a bug or a new feature.  I upgraded to the above version of `allure-reporter` and now I get lots of "POST xx" entries in the test body of my report 
(example: `POST /session/:sessionId/window/maximize"`)
These weren't preset in the previous report version.
Is there a config to suppress these?

**Comment by erwinheitzman** [comment]
What's your logLevel set to? This is a property part of the config.

**Comment by adamsjoe** [comment]
@erwinheitzman I had it set at various levels, "info", "debug" and just tried it on "silent" - the same info appears in the log (I made  sure to clean out my allure results between each run.)

**Comment by BorisOsipov** [comment]
@adamsjoe As I said in previos issue please configure your reporter properly. See docs here https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-allure-reporter#configuration

In v5 there is no `config.reporterOptions`

**Comment by adamsjoe** [comment]
ah - i had missed the subtle change.
