### ISSUE TITLE
selectByValue, selectByIndex, selectByVisibleText doesn't work

### ISSUE THREAD

**Issue by fat-troll** [webdriverio/webdriverio#400]
Hello, Chris!
Seems like these methods don't work

```
TypeError: Object #<WebdriverIO> has no method 'selectByValue'
```

You can try to add it to any test
```
client.init().url('http://google.com/').selectByValue('anything').end();
```

**Comment by christian-bromann** [comment]
They should .. mhm .. which version are you running?

**Comment by fat-troll** [comment]
update whole project to the latest one 2 weeks ago -  "webdriverio": "2.0.1"

**Comment by christian-bromann** [comment]
I recommend to have a `~` character in front of the version number so it updates when I fixed bugs. You need to update that version to `"webdriverio": "~2.4.4"

**Comment by fat-troll** [comment]
Oh sorry.. Updates are so fast :D
