### ISSUE TITLE
Safari unknown error when clicking a link with an inner span element

### ISSUE THREAD

**Issue by jensbodal** [webdriverio/webdriverio#4001]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.9.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 8.15.1
 - **NPM version:** 6.4.1
 - **Browser name and version:** Safari 12.1.1
 - **Platform name and version:** macOS High Sierra 10.13.6
 - **Additional wdio packages used (if applicable):** @wdio/selenium-standalone service

**Config of WebdriverIO**
https://github.com/jensbodal/wdio-typescript/blob/master/wdio.conf.js

**Describe the bug**
Cannot click an anchor tag in safari when it has an inner span element

```
<a href="http://www.google.com"><span>Inner span element</span></a>
```

```
const aSpanElement = await $('//a[span[text()="Inner span element"]]');
await aSpanElement.click();
```

Results in 

```
[Safari  macOS #1-0] Spec: /Volumes/case/github/wdio-typescript/src/tests/angular.spec.ts
[Safari  macOS #1-0] Running: Safari on macOS
[Safari  macOS #1-0]
[Safari  macOS #1-0] Fails in safari
[Safari  macOS #1-0]    ✖ cannot click anchor tag when trying to select by inner span text
[Safari  macOS #1-0]
[Safari  macOS #1-0] 1 failing (1.9s)
[Safari  macOS #1-0]
[Safari  macOS #1-0] 1) Fails in safari cannot click anchor tag when trying to select by inner span text
[Safari  macOS #1-0] unknown error
[Safari  macOS #1-0] element not interactable: unknown error
[Safari  macOS #1-0]     at getErrorFromResponseBody (/Volumes/case/github/wdio-typescript/node_modules/webdriver/build/utils.js:349:10)
[Safari  macOS #1-0]     at Request._callback (/Volumes/case/github/wdio-typescript/node_modules/webdriver/build/request.js:121:64)
[Safari  macOS #1-0]     at Request.self.callback (/Volumes/case/github/wdio-typescript/node_modules/request/request.js:185:22)
[Safari  macOS #1-0]     at emitTwo (events.js:126:13)
[Safari  macOS #1-0]     at Request.emit (events.js:214:7)
[Safari  macOS #1-0]     at Request.<anonymous> (/Volumes/case/github/wdio-typescript/node_modules/request/request.js:1161:10)
[Safari  macOS #1-0]     at emitOne (events.js:116:13)
[Safari  macOS #1-0]     at Request.emit (events.js:211:7)
[Safari  macOS #1-0]     at IncomingMessage.<anonymous> (/Volumes/case/github/wdio-typescript/node_modules/request/request.js:1083:12)
[Safari  macOS #1-0]     at Object.onceWrapper (events.js:313:30)
```

**To Reproduce**

The following will run the test against locally installed chrome, safari, and firefox. Observe the failure in safari.

Clone this repo: https://github.com/jensbodal/wdio-typescript

```
yarn install

# open two tabs
## tab 1
yarn start:angular

## tab 2
yarn safari-test-case
```

**Expected behavior**
The link is clickable in both firefox and chrome but not safari.

**Comment by jensbodal** [comment]
I'm able to click the link if I target the `span` element

```
const aSpanElement = await $('//a//span[text()="Inner span element"]');
await aSpanElement.click();
```

If this is expected behavior it can be closed, but seems odd this works everywhere but Safari.

**Comment by naddison** [comment]
> I'm able to click the link if I target the `span` element
> 
> ```
> const aSpanElement = await $('//a//span[text()="Inner span element"]');
> await aSpanElement.click();
> ```
> 
> If this is expected behavior it can be closed, but seems odd this works everywhere but Safari.

This sounds like an issue with Safari and/or Webkit itself and not necessarily WDIO?

**Comment by jensbodal** [comment]
That could very well be, I don't know enough about the implementation details to know where the point of failure lies. Based on your comment I'm guessing this is wrong, but my understanding was that WDIO provides a wrapper around the `safaridriver` which led me to believe WDIO might have some influence on this failure. 

I guess I should have said if this issue is not related to WDIO, then please close it (or I can close it).

**Comment by erwinheitzman** [comment]
See my reply to https://github.com/webdriverio/webdriverio/issues/3991 it's basically the same thing.

**Comment by christian-bromann** [comment]
We will tackle this in #2866
