### ISSUE TITLE
browser.maximizeWindow() doesn't work with chromedriver 2.43 and Chrome older v72

### ISSUE THREAD

**Issue by BelovAleksey** [webdriverio/webdriverio#4003]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [5.8.6]
 - **Mode:** [Standalone mode]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [10.15.3]
 - **NPM version:** [6.4.1]
 - **Browser name and version:** [Chrome >= 72]
 - **Platform name and version:** [macOs Mojave 10.14.4 ]
 - **Additional wdio packages used (if applicable):** [@wdio/selenium-standalone service]

**Describe the bug**
chromedriver version 2.43 (automatically installed by webdriverio) does not support maximizeWindow command for Chrome version older than 72.

unknown error: failed to change window state to maximized, current state is normal
  (Session info: chrome=74.0.3729.169)
  (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.14.4 x86_64)
[chrome 74.0.3729.169 Mac OS X #0-0] Error: unknown error: failed to change window state to maximized, current state is normal
[chrome 74.0.3729.169 Mac OS X #0-0]   (Session info: chrome=74.0.3729.169)
[chrome 74.0.3729.169 Mac OS X #0-0]   (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.14.4 x86_64)
[chrome 74.0.3729.169 Mac OS X #0-0]     at getErrorFromResponseBody (/Users/remotetester/Documents/Projects/ui-tests/node_modules/webdriver/build/utils.js:349:10)
[chrome 74.0.3729.169 Mac OS X #0-0]     at Request._callback (/Users/remotetester/Documents/Projects/ui-tests/node_modules/webdriver/build/request.js:121:64)
[chrome 74.0.3729.169 Mac OS X #0-0]     at Request.self.callback (/Users/remotetester/Documents/Projects/ui-tests/node_modules/request/request.js:185:22)
[chrome 74.0.3729.169 Mac OS X #0-0]     at Request.<anonymous> (/Users/remotetester/Documents/Projects/ui-tests/node_modules/request/request.js:1161:10)
[chrome 74.0.3729.169 Mac OS X #0-0]     at IncomingMessage.<anonymous> (/Users/remotetester/Documents/Projects/ui-tests/node_modules/request/request.js:1083:12)

**To Reproduce**
Try to run browser.maximizeWindow() on Chrome >=72 version

**Fixing Problem**
Changing chrome version to 2.46 in node_modules/selenium-standalone/lib/default-config.js resolve this problem

**Comment by christian-bromann** [comment]
This is an issue with the selenium-standalone package. Please raise this issue there. Thanks!

**Comment by kavyashree088** [comment]
@BelovAleksey I'm also facing the same issue, even after changing the version in default-config.js. After Changing do we need to do anything like restarting the server or something?

**Comment by MauriceWebb** [comment]
> @BelovAleksey I'm also facing the same issue, even after changing the version in default-config.js. After Changing do we need to do anything like restarting the server or something?

@BelovAleksey I found a working answer [here](https://github.com/webdriverio/webdriverio/issues/3043#issuecomment-449099825) that suggested changing the version in `node_modules/selenium-standalone/lib/default-config.js` to `2.44`. Hope that works for you as it did for me. Still feels kinda "hacky." 🤨
