### ISSUE TITLE
WDIO hook for it blocks

### ISSUE THREAD

**Issue by BelovAleksey** [webdriverio/webdriverio#4004]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [5.8.6]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [10.15.3]
 - **NPM version:** [6.4.1]
 - **Browser name and version:** [Chrome 64]
 - **Platform name and version:** [macOs Mojave]
 - **Additional wdio packages used (if applicable):** [@wdio/mocha-framework": "5.8.1"]

**Describe the bug**
It's very difficult to take screenshot in test failing time because if I have next test structure
```js
describe('test', () => {
afterEach(() => {
 after commands block
})
```

```js
it('step1', ()=> {
  commands block
  expect(smth)
})
})
```

And in `wdio.conf`:
```js
afterTest: function (test) {
    if (test.error !== undefined) {
      browser.takeScreenshot();
    }
  }
```

Screenshot makes after "after commands block" and I can't see test failing reasons

**To Reproduce**
You can reproduce it by next steps:

***test.js***
```js
describe('test', () => {
afterEach(() => {
 browser.pause(2000)
})

it('step1', ()=> {
  console.log('into test ', new Date())
  expect(false).to.be.true
})
})
```

***wdio.conf.js***
```js
...
  afterTest: function (test) {
    console.log('after test ', new Date())
  },
...
```

So you see something like:
```
[0-0] into test 2019-05-22T09:20:35.450Z
[0-0] after test  2019-05-22T09:20:37.521Z
```

And

**Expected behavior**
`afterTest` function runs after "it"

**Comment by christian-bromann** [comment]
> afterTest function runs after "it"

This can't be handled in WebdriverIO because `afterEach` of an `it` in Mocha runs before `afterEach` of a suite. We would need to implement a new hook in wdio that is called in `@wdio/sync` or wraps the it block somehow else. Suggestions for such a hook are welcome!

**Comment by mgrybyk** [comment]
@christian-bromann it can be done same as in Cucumber, where we don't have native before/after test hooks at all, by wrapping `it` function itself with before/after test hooks and that's it.
Should be relatively easy, I can take a look if it sounds good

**Comment by mgrybyk** [comment]
Going to start working on it this or next week as far as it affects my project. If anyone has any concerns please let me know.

**Comment by mgrybyk** [comment]
let's proceed conversation in https://github.com/webdriverio/webdriverio/pull/4354
