### ISSUE TITLE
waitFor Promise error

### ISSUE THREAD

**Issue by syzer** [webdriverio/webdriverio#401]
Valid A+ promise code:
```js
client
            .url(sid.url)
            .then(client.waitFor('.result', 5000))
            .then(client.getValue(isi.sidInput))
```

Throws this error:
```
error: TypeError: Object #<WebdriverIO> has no method 'apply'
    at c:\xampp\htdocs\testJS\html-scrapers\node_modules\webdriverio\lib\utils\PromiseHandler.js:82:52
```

Would use of bluebird instead of promiseHandler be any help

**Comment by christian-bromann** [comment]
You don't need then here. WebdriverIO comes with an own queue library (chainit) to chain commands properly. Try this:

```js
client
    .url(sid.url)
    .waitFor('.result', 5000)
    .getValue(isi.sidInput)
```

Your example is valid promise code though. Therefor I fixed this problem and published a new version to npm.

Let me know if there are any other questions ;-)

**Comment by syzer** [comment]
thanks!.
i prefer `then` version better since i can push resulting promise to other libraries
not only the webdriver.

also in old version of webdriv erio i get

```client
    .url(sid.url)
    .waitFor('.result', 5000)
    .getValue(isi.sidInput)
```


```TypeError: Cannot call method 'waitFor' of undefined```
