### ISSUE TITLE
Can't find element

### ISSUE THREAD

**Issue by yuriieasternpeak** [webdriverio/webdriverio#4011]
I want to create service to wrap @applitools/eyes.webdriverio (my repo - https://github.com/yuriieasternpeak/eyes.wdio4.service.git). 

When I execute 
`browser.eyesCheckWindow('main', Target.region(By.id("overflowing-div")));`
I got error 
`{ Error: no such element: Unable to locate element: {"method":"tag name","selector":"html"}`

logs:
```
[12:45:44]  COMMAND	POST 	 "/wd/hub/session/45bfd9fc9fa06a72bc3c91bbd9f7c166/element"
[12:45:44]  DATA		{"using":"css selector","value":"body #overflowing-div"}
[12:45:44]  RESULT		{"ELEMENT":"0.7572395395786702-1"}
[12:45:44]  COMMAND	POST 	 "/wd/hub/session/45bfd9fc9fa06a72bc3c91bbd9f7c166/element/0.7572395395786702-1/element"
[12:45:44]  DATA		{"using":"tag name","value":"html"}
```

wdio uses wrong request
`[12:45:44]  COMMAND	POST 	 "/wd/hub/session/45bfd9fc9fa06a72bc3c91bbd9f7c166/element/0.7572395395786702-1/element"
`
but it should be 
`[12:45:44]  COMMAND	POST 	 "/wd/hub/session/45bfd9fc9fa06a72bc3c91bbd9f7c166/element"`

I found the bug but I can't create Pull Request
`node_modules/webdriverio/build/lib/protocol/element.js`

need to replace 
`if (lastPromise.state === 'fulfilled' && (0, _hasElementResultHelper2.default)(lastPromise.value) === 1) {
`
to 
`if (lastPromise.state === 'fulfilled' && (0, _hasElementResultHelper2.default)(lastPromise.value) === 1 && selector === lastPromise.value.selector) {
`

in file `webdriverio/build/lib/protocol/element.js`

**Comment by christian-bromann** [comment]
Feel free to provide a PR in https://github.com/webdriverio-boneyard/v4 .. I highly recommend to switch to v5 as we don't actively work on v4 anymore.
