### ISSUE TITLE
Issue running webdriverio tests on IE11 using selenium grid

### ISSUE THREAD

**Issue by pk-saxena** [webdriverio/webdriverio#4012]
**Environment:**
 - **WebdriverIO version:** 4.14.2
 - **Mode:** WDIO Testrunner (sync)
 - **Browser name and version:** IE 11
 - **Host machine:** Mac 10.13.6
 - **Guest machine:** Windows 8.1
- **selenium standalone**: selenium-server-standalone-3.141.59.jar
- **IE driver**: 32 bit 3.14.0

**Config of WebdriverIO**
```js
  host: '<host machine ip >',
  port: 4444,
  path: '/wd/hub',
  specs: [`${pathToTests}*.js`],
  deprecationWarnings: false,
  maxInstances: 1,
  capabilities: [
    {
      browserName: 'internet explorer',
      version: 11,
      platformName: 'windows 8.1',
    }
  ],
  sync: true,
```

**Describe the bug**
Unable to execute webdriverio tests on IE using selenium grid. Getting exception:
```js
org.openqa.grid.common.exception.CapabilityNotPresentOnTheGridException: cannot find : Capabilities {browserName: internet explorer, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., platformName: windows 8.1, requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.14.2}, rotatable: true, version: 11}
```

**To Reproduce**
I am running windows 8.1 VM inside virtualbox on mac host. This is done in order to be able to run IE tests on mac.
The Mac is running a Selenium-Grid hub.
The Windows VM on Mac is running a Selenium node that hooks up to the hub.
I have tested that VM is able to ping my Mac. This is done by changing the value of 'Attached To' in the Network setting of VM to Bridged Adapter. 
The whole set up is described here: 
http://kprakobkit.github.io/how-to-setup-selenium-webdriver-to-run-in-ie-on-a-mac/
On my host machine, when I go to `http://localhost:4444/grid/console`, I can see IE node as well.

**Expected behavior**
IE browser should get launched inside windows VM

**Actual behavior**
Getting the exception mentioned above

**Comment by christian-bromann** [comment]
It seems that your grid is not configured properly. I am not sure how this is an issue of WebdriverIO. Closing therefor but happy to assist you.
