### ISSUE TITLE
How can I close all tabWindow in browser

### ISSUE THREAD

**Issue by sgauruseu** [webdriverio/webdriverio#4016]
Several tabs are opened in my browser. I want to close all except for HomePage , for example.
How to close browser tabs if I do not know all titles ?
I can call `switchWindow`  but it requires `urlOrTitleToMatch` . Is it possible to switch to a tab 
using `getWindowHandles`? 

**Environment (please complete the following information):**
 - **WebdriverIO  v5**
 - **Standalone mode:** 

 - **Node.js version: 8.11.1** 
 - **NPM version: 5.6.0** 
 - **Chrome 74** 
 - **Platform name and version: Windows 10**

**Comment by christian-bromann** [comment]
Yes, see API: https://webdriver.io/docs/api/webdriver.html#switchtowindow

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by sgauruseu** [comment]
I got the exception 
 No window found with title or url matching "CDwindow-C8956DA3C99CED753F7B7FB98649F3B3"

**Comment by sgauruseu** [comment]
at Browser.switchWindow (testing\node_modules\webdriverio\build\commands\browser\switchWindow.js:68:9)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

**Comment by christian-bromann** [comment]
you have to use `browser.switchToWindow(handle)`

**Comment by sgauruseu** [comment]
Thanks! I confused with 2 different names -   `switchToWindow` and `switchWindow`
