### ISSUE TITLE
Custom Reporter: Wrong data provided to onTestEnd when last test is a skipped test

### ISSUE THREAD

**Issue by fijijavis** [webdriverio/webdriverio#4018]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.9.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 11.9.0
 - **NPM version:** Using yarn 1.15.2
 - **Browser name and version:** Chrome
 - **Platform name and version:** MacOS 
 - **Additional wdio packages used (if applicable):**

```
"devDependencies": {
    "@wdio/cli": "^5.7.1",
    "@wdio/dot-reporter": "^5.7.0",
    "@wdio/local-runner": "^5.7.1",
    "@wdio/mocha-framework": "^5.7.0",
    "@wdio/sync": "^5.7.2",
    "jest-matchers": "^20.0.3",
    "webdriverio": "^5.7.1",
     "wdio-json-reporter": "^1.1.0",
    "wdio-mochawesome-reporter": "^3.0.0"
  },
```

**Config of WebdriverIO**
Pretty much defaults except the reporters and my spec file
```
reporters: [
        'dot',
        ['mochawesome',{ 
            outputDir: './Results', 
            includeScreenshots: true,
            outputFileFormat: function(opts) { 
            return `wdio-mochawesome-${opts.cid}.${opts.capabilities.browserName}.json`
        }}]
    ],
```

**Describe the bug**
When the last test in a suite is a skipped test, the test object provided to `onTestEnd` has the same information as the test run just prior to the skipped test.

**To Reproduce**
Minimal Spec File:
```
const expect = require('jest-matchers')
describe('Sample Suite 1',function(){

    it('should report fail',function(){
        browser.url('https://www.google.com')
        expect(true).toBe(false)
    })

    it.skip('should report skip',function(){
        browser.url('https://www.google.com')
    })
})
```

Minimal Custom Reporter:
```
const WDIOReporter = require('@wdio/reporter').default

export default class CustomReporter extends WDIOReporter {
    onTestStart (test) { console.log('onTestStart',test) }
    onTestSkip (test) { console.log('onTestSkip',test) }
    onTestEnd (test) { console.log('onTestEnd',test) }
};
```

**Expected behavior**
One of two behaviors:

1) A onTestEnd event for a skipped test should provide a test object that matches the skipped test

2) No onTestEnd event should be raised for skipped tests.  This seems logical because the onTestStart is not raised.

**Log**
https://gist.github.com/fijijavis/504e684dcfa2a760f17d6f298d4f3e25

There are 2 log files in this gist.

emit.log
I added a console.log to the `emit` function in @ wdio/mocha-framework/index.js.  In the log you will see 2 `test:end` events.  One for the failed test and a second for the skipped test.  What is interesting to me is that BOTH have the same `uid` value.

reporter.log
The result of the console.log statements from a custom reporter (like above).  You will see 2 log statements for `onTestEnd` and they have the same test object.

**Additional context**
I think the ideal state would be to not emit a `onTestEnd` event for a skipped test.  
* The `onTestStart` event is not emitted so this would match.
* The test didn't run so logically it couldn't have "ended"

I tried (unsuccessfully) to figure out where that change should be made.  If there are any pointers then I can try to submit a PR for a fix.

Thanks!

> Please use the correct markdown

**Comment by mgrybyk** [comment]
@fijijavis thank you so much for really detailed description, it saved me lot's of time!

Let's proceed discussion in https://github.com/webdriverio/webdriverio/pull/4056
