### ISSUE TITLE
Implement methods to navigate through the DOM easier

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#4019]
**Is your feature request related to a problem? Please describe.**
Sometimes it is not possible to directly fetch an element. Knowing the DOM structure though it could be possible to navigate to the desired element. This navigation is currently not possible due to lack of commands.

**Describe the solution you'd like**
I think it could be useful to implement `prev`, `next` and `parent` commands for the element scope that do the following:

`element.prev()`:
```js
browser.execute((elem) => elem.previousElementSibling, this)
// make it an element instance
```

`element.next()`:
```js
browser.execute((elem) => elem.nextElementSibling, this)
// make it an element instance
```

`element.parent()`:
```js
this.$('..')
```

**Comment by erwinheitzman** [comment]
We should think about how we attach this to our middleware (waitForExist when interacting with the element, error handling) to prevent issues when the main element or any element further down the DOM tree doesn't exist yet.

**Comment by pandasanjay** [comment]
Thanks @christian-bromann posting this enhancement and ideas how we can achieve that.

Adding to that, below are some custom command which will help to add the same feature until the release is take care.

Below is working for me 
```
//onBefore() -- wdio.config.js file
const {  getElement } = require("webdriverio/build/utils/getElementObject.js")

browser.addCommand(
    "prev",
    function() {
      let res = browser.execute((elem) => elem.previousElementSibling, this);
      return getElement.call(this, "prev", res)
    },
    true
  );

  browser.addCommand(
    "next",
    function() {
      let res = browser.execute((elem) => elem.nextElementSibling, this);
      return getElement.call(this, "next", res)
    },
    true
  );

```
Ref: https://webdriver.io/docs/customcommands.html

**Comment by dagoud** [comment]
@christian-bromann I tried renaming parentEl to parent but ran into issues - is there something happening where parent is already being used elsewhere?

Error message I got when i tried:

` FAIL  packages/webdriverio/tests/commands/element/parent.test.js (19.32 s)
  parent element test
    ✕ should return parent element of an element (31 ms)

  ● parent element test › should return parent element of an element

    TypeError: Cannot assign to read only property 'parent' of object '#<Element>'

      42 | 
      43 |         client.selector = selector
    > 44 |         client.parent = this
         |         ^
      45 |         client.emit = this.emit.bind(this)
      46 |         client.isReactElement = isReactElement
      47 | 

      at utils_1.webdriverMonad.client (packages/webdriverio/src/utils/getElementObject.js:44:9)
      at unit (packages/wdio-utils/src/monad.js:76:22)
      at Browser.findElement (packages/webdriverio/src/utils/getElementObject.js:51:29)
      at Browser.$ (packages/webdriverio/src/commands/browser/$.js:64:23)`

which leads to in _getElementObject.js:44:9 :_
`client.selector = selector
        client.parent = this
        client.emit = this.emit.bind(this)
        client.isReactElement = isReactElement`

**Comment by christian-bromann** [comment]
@dagoud ah yes, this is actually not very well documented or used. If you fetch and element from an element you can always go back to the root element:

```js
const elem = $('#someElem')
const subElem = elem.$('#subElem')
console.log(subElem.parent.selector) // #someElem
```

This parent property and your parent method are not quite the same. The property refers to the element the current element was queried from (which can be a higher level parent) while the command should return the direct parent. I think it is safe to rename this property which is defined [here](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/utils/getElementObject.js#L99) and used in the following places:

- /packages/wdio-sync/src/wrapCommand.js
- /packages/wdio-sync/tests/wrapCommand.test.js
- /packages/webdriverio/src/middlewares.js
- /packages/webdriverio/src/commands/element/isExisting.js
- /packages/webdriverio/src/commands/element/scrollIntoView.js
- /packages/webdriverio/src/utils/implicitWait.js
- /packages/webdriverio/src/utils/index.js
- /packages/webdriverio/src/utils/refetchElement.js
- /packages/webdriverio/tests/commands/browser/$$.test.js
- /tests/typings/sync/sync.ts
- /tests/typings/webdriverio/async.ts

The question is what should be the new name for this property? My suggestions would be: `sourceElem` or `queryElem`. Any feedback @webdriverio/technical-steering-committee ?

**Comment by christian-bromann** [comment]
@dagoud after discussing this with the TSC team we decided to call the new commands `prevElement`, `parentElement` and `nextElement`. This should resolve this naming conflict.

**Comment by dagoud** [comment]
Thanks for clarifying @christian-bromann - will make these changes and submit PR

**Comment by dagoud** [comment]
Have submitted PR for this issue here:
https://github.com/webdriverio/webdriverio/pull/6030
