### ISSUE TITLE
Not able to run tests on Sauce Labs with W3C capabilities and Sauce Connect Options

### ISSUE THREAD

**Issue by yamkay** [webdriverio/webdriverio#4021]
**Environment:**
 - **WebdriverIO version:** 5.8.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 8.11.2
 - **NPM version:** 5.8.0
 - **Additional wdio packages used (if applicable):** wdio-spec-reporter, wdio-allure-reporter, wdio-sauce-service

**Config of WebdriverIO**
```
exports.config = {
    user: 'valid_user',
    key: 'valid_key',
    region: "us",
    sauceConnect: true,
    services: ["sauce"],
    sauceConnectOpts: {
            port: 4446,
            tunnelIdentifier: 'my-tunnel'
    },
    capabilities = [
      {
        browserName: "googlechrome",
        platformName: "macOS 10.13",
        browserVersion: "72.0",
        'sauce:options': {
          commandTimeout: 600,
        },
        'goog:chromeOptions': {
          w3c:true
        }
    }
  ]
}
```

**Describe the bug**
Whenever I use W3C capabilities and Sauce Connect Options to run the tests, it results the error due to missing tunnel identifier.

For more details on W3C support from Sauce Labs - https://wiki.saucelabs.com/display/DOCS/Selenium+W3C+Capabilities+Support+-+Beta

**To Reproduce**

1. Run the tests on Sauce Labs with the above config 
2. It would fail due to missing tunnel identifier.

**Expected behavior**
It should run the tests without any errors with Sauce Connect tunnel.

**Comment by christian-bromann** [comment]
This got merged and will be released soon!

**Comment by yamkay** [comment]
Thank you, @christian-bromann !
