### ISSUE TITLE
jamine-framework: Implement jamineOpts.stopSpecOnExpectationFailure

### ISSUE THREAD

**Issue by mike-d-davydov** [webdriverio/webdriverio#4024]
**Is your feature request related to a problem? Please describe.**

Please see https://github.com/webdriverio-boneyard/wdio-jasmine-framework/issues/99,

Currrently Jasmine's "stopSpecOnExpectationFailure" configuration option is not supported. As a result, 
   1) tests can not be stopped on expectation/assertion failure, which means that instead of assertions one may have to throw Errors which is not quite correct and pretty counter-intuitive.
   2) exception is not being thrown in test if it fails with expectation failure. As a result, one can't  wrap a test callback in a function with try/catch, expecting to intercept test failures.
 
**Describe the solution you'd like**

Implement `stopSpecOnExpectationFailure` configuration option in the same way as a currently supported `stopOnFirstSpecFailure`.

**Describe alternatives you've considered**

Possible workaround is to configure Jasmine options from test. It is possible, but it is a hack.

**Additional context**

Please see comments to original issue. I am submitting this issue in order to contribute an implementation.

**Comment by christian-bromann** [comment]
Merged PR
