### ISSUE TITLE
TouchAction: cannot read property 'action' of null

### ISSUE THREAD

**Issue by sanyco92** [webdriverio/webdriverio#4028]
**Environment:**
 - **WebdriverIO version:** [4.14.1]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [10.11.0]
 - **NPM version:** [6.9.0]
 - **Platform name and version:** [iOS 12.1]
 - **Additional wdio packages used (if applicable):** ["wdio-appium-service": "~0.2.3",
    "wdio-mocha-framework": "~0.6.4",
    "wdio-spec-reporter": "~0.1.5", "appium": "~1.13.0"]

Hello guys, got a weird problem. I have 2 methods:

```
scrollUpAlertsAttachmentsSection() {
        let attachmentsSectionRect = browser.elementIdRect(browser.element(this.alertAttachmentsSectionsTable).value.ELEMENT);
        this.scrollUpInsideWindow(attachmentsSectionRect, 200);
        return this;
    }
```

and
```
scrollUpInsideWindow(windowRect, step) {
        browser.touchAction([
            {
                action: 'press',
                x: windowRect.value["x"] + windowRect.value["width"] / 2,
                y: windowRect.value["y"] + windowRect.value["height"] - 5 - step
            },
            {action: 'wait', ms: 2000},
            {
                action: 'moveTo',
                x: windowRect.value["x"] + windowRect.value["width"] / 2,
                y: windowRect.value["y"] + windowRect.value["height"] - 5
            },
            'release',
        ]);
        return this;
    }
```
But when I run the code, it's getting element rect correctly, I see the result with object {x,y,width, height}, writing this result into variable attachmentsSectionRect and even able to console.log this variable. And then, unfortunately getting the error message on TouchAction method:
```
Cannot read property 'action' of null
running
TypeError: Cannot read property 'action' of null
    at touchAction([object Object], [object Object], [object Object], release) - index.js:312:3
```

How to solve it? Interesting fact, **these methods worked when I used 'before' and 'beforeEach' hooks of mocha**. But now I changed these hooks to wdio hooks 'beforeSuite' and 'beforeTest', (the code of hooks remain the same, but I moved them from spec file to wdio config file), and TouchAction become failing

**Comment by christian-bromann** [comment]
For issues in WebdriverIO v4 please raise an issue here: https://github.com/webdriverio-boneyard/v4
