### ISSUE TITLE
elements can't be found by CSS selector if PORTRAIT orientation is set for mobile safari.

### ISSUE THREAD

**Issue by artemmorshchak** [webdriverio/webdriverio#4029]
**Question**
Currently i'm working on automation of our web application testing on real devices ( i use appium + webdriver.io) And encountered an issue with mobile Safari - for some reason tests are failing because webdriver can't find elements by CSS selectors, if portrait orientation is set. In landscape everything is fine. (On android devices in chrome everything works perfectly well so it's not web app issue for sure). Have anyone encountered similar issues, and if yes, is there any kind of workaround/fix?

**Details**
Next capabilities are set for safari:
            browserName: 'Safari', 
            platformName: 'iOS',
            platformVersion: '11.4',
            deviceName: 'iPhone 6s+'
            udid: 'deviceudid',
            orientation : 'PORTRAIT',

Tests fail on next line 

browser.waitForVisible(npPage.locator) 

with error that element has not become visible in 15seconds

**Environment (please complete the following information):**
 - **WebdriverIO version:** 4.3.12
 - **Mode:** standalone
 - **Node.js version:** 10.12.0
 - **NPM version:** 6.4.1
 - **Browser name and version:** safari 11.4
 - **Platform name and version:** iOS 11.4
 - **Additional wdio packages used (if applicable):** 
    "wdio-dot-reporter": "0.0.10",
    "wdio-jasmine-framework": "^0.3.5",
    "wdio-junit-reporter": "^0.4.4",
    "wdio-visual-regression-service": "^0.9.0",

**Comment by christian-bromann** [comment]
> Have anyone encountered similar issues, and if yes, is there any kind of workaround/fix?

No. Can you provide logs and a reproducible example? Without it is almost impossible to help out here.

**Comment by mgrybyk** [comment]
If anyone can share logs and reproducible example feel free to reopen
