### ISSUE TITLE
How to call webdriverio using phantomjs

### ISSUE THREAD

**Issue by byteshiva** [webdriverio/webdriverio#403]
I'm trying to execute webdriverio in phantomjs, but its throwing error. How can i make it work in phantom?

``var webdriverio = require('webdriverio');
var options = {
    desiredCapabilities: {
        browserName: 'phantomjs'
    }
};``

**Comment by christian-bromann** [comment]
Could you provide some logs from your selenium server? That would help to chase down the problem.  I guess you are running a selenium standalone server version 2.44. In that case you won't get it running with phantomjs (see #342). You have two options: use selenium standalone version 2.43 or instead running a standalone server, start phantomjs as webdriver `phantomjs --webdriver=4444`

**Comment by byteshiva** [comment]
$phantomjs --webdriver=4444 got it working,

But any higher version of selenium-standalone its not working.

Here are some details.
I have installed npm install selenium-standalone ("version": "3.2.0")
and started selenium standalone using 

``$ selenium-standalone start ,

**Comment by christian-bromann** [comment]
ah ok, yes selenium-standalone is using v2.44 which has problems running phantomjs. I've just seen that phantomjs v2.0 is out and it is coming with a fix for this problem.
