### ISSUE TITLE
`browser.getLogs` is not a function

### ISSUE THREAD

**Issue by jackTheRipper** [webdriverio/webdriverio#4032]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 10.15.3
 - **NPM version:** 6.9.0
 - **Browser name and version:** Chrome 74
 - **Platform name and version:** Linux (Selenium Grid in K8S)
 - **Additional wdio packages used (if applicable):** @wdio/spec, @wdio/local-runner, @wdio/mocha-framework, @wdio/runner (but it cannot be loaded for some reasons - only the local-runner works)

**Config of WebdriverIO**
My config targets my Selenium Grid and it works

**Describe the bug**
When calling `browser.getPageLogs` or `browser.getLogs`, my tests fail saying `ERROR @wdio/config: TypeError: browser.getLogs is not a function`. However, based on the API documentation, it should be existing.

**To Reproduce**
```
browser.getLogs('browser').then(console.log)
```

**Expected behavior**
I expect to have the function defined and to return logs

**Comment by jackTheRipper** [comment]
Found out - I was missing one of the core package (`webdriver`). Closing the issue since it was related to my setup.

**Comment by heyheyjean** [comment]
Hey you! when you gonna change the pic which you did on my bed after we finished our sexual activities?? Does Irina know about this fact btw? Honestly how dare you to keep it after another try to kill me via leading to a suicide action??

**Comment by heyheyjean** [comment]
Hey you! when you gonna change the pic which you did on my bed after we finished our sexual activities?? Does Irina know about this fact btw? Honestly how dare you to keep it after another try to kill me via leading to a suicide action??

**Comment by dieSalatTaste** [comment]
HELLO!! LOOKING FOR A GREAT BLOWJOB?? CALL CAROLINE +33661818188 OR VERO +33667301419!! OR CONTACT THEIR SLUTTY FRIEND @IRINAKS1 ;) THEY KNOW HOW TO SUCK WELL!! JEAN BAUDIN KNOWS THAT FOR SURE! HE ENJOYED THE CAROLINE THE MOST !! DON’T BELIVE? CALL HIM AND ASK +31657697635 XOXO

**Comment by rsshilli** [comment]
I'm having the same issue. Which npm package were you missing?

**Comment by christian-bromann** [comment]
@rsshilli if `getLogs` doesn't work it likely means it is not supported in the environment you are running.

**Comment by rsshilli** [comment]
Well, I updated `webdriverio` (https://www.npmjs.com/package/webdriverio) from 7.7.3 to 7.10.1 and that seemed to do it. Weird.
