### ISSUE TITLE
Documentation on selecting android elements

### ISSUE THREAD

**Issue by dtboy1995** [webdriverio/webdriverio#4035]
i'm sorry that I didn't find the document about how to find the android elements in your library. Could you tell me where it is or you can supplement the relevant document? Thank you very much

**Comment by christian-bromann** [comment]
Can you elaborate what specifically you mean by "android element"? Does this help you: https://webdriver.io/docs/selectors.html#android-uiautomator ?

**Comment by dtboy1995** [comment]
@christian-bromann, thank you very much and god bless you
