### ISSUE TITLE
Remove browser commands element instance

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#4038]
Since element commands can't be called on the browser object we should also not allow to call browser commands on elements. At the same time protocol commands should be available to every instance type.

**Comment by christian-bromann** [comment]
I believe this change needs to be done [where we define the element prototype](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/utils/getElementObject.ts#L23-L27). I believe we can save some memory if we actually keep the scope as small as possible. This would be a breaking change which is why we should consider it for `v8`.

**Comment by jmalvinez** [comment]
Hi @christian-bromann! I'd like to give this issue a try. Btw, I'm a newbie contributor in Hacktoberfest. 😅

Based on your tip, it seems the browser commands are coming from `...clone(browser.__propertiesObject__)` when I printed that out. Is this as simple as removing that line or do I need to only whitelist certain props in that object?

Please let me know if my understanding is wrong though. I'm happy to discuss here or send you a message in Gitter. 🙏

**Comment by christian-bromann** [comment]
@jmalvinez thanks for taking a stab at it. Note that this issue is marked as `v8` milestone because it would be a breaking change, therefore we won't be able to merge it in time. I recommend picking a different issue.

**Comment by christian-bromann** [comment]
fixed in https://github.com/webdriverio/webdriverio/pull/8578
