### ISSUE TITLE
onComplete hook does not wait for async/await operations like the other hooks

### ISSUE THREAD

**Issue by jgoldring** [webdriverio/webdriverio#4042]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.9.4
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 11.12.0
 - **NPM version:** 6.7.0

**Config of WebdriverIO**
Config Gist: "https://gist.github.com/jgoldring/b2cd473773fe51ca8d517012e8508af4.js"

Test.js:
`describe('Suite', () => {
    it('Test', () => {
        console.log("Hi");
    });
});`

**Describe the bug**
The onComplete hook will not wait for async output before completing. In my config gist, you can see that I've setup both the onPrepare and onComplete hook to print, wait 10s, and print again. The onPrepare (and all other config hooks) wait the appropriate time, and then print the second statement. The onComplete hook does not print the second line, and the Testrunner exits. Running the above config/test produces:

![image](https://user-images.githubusercontent.com/3430378/58664296-94fc5100-82eb-11e9-8c22-3f623ef76873.png)

**To Reproduce**
Run the above config/test with /path/to/wdio /path/to/wdio.conf.js

**Expected behavior**
onComplete() declared as async waits for the timeout and prints the second console.log

**Comment by hananurrehman** [comment]
I suspect this is still an issue. I'm trying to make an API call in the oncomplete hook but it finishes before the API call is complete.

**Comment by christian-bromann** [comment]
I just tested this and `onComplete` handles async code properly, please provide a reproducible example.
