### ISSUE TITLE
WebElement not found 

### ISSUE THREAD

**Issue by byteshiva** [webdriverio/webdriverio#405]
Any idea why I'm getting this error noElement found error
Sample code 
```
var webdriverio = require('webdriverio'),
    options = {
        bail:false,
        desiredCapabilities: {
            browserName: 'phantomjs'
        }
    };

webdriverio
    .remote(options)
    .init()
    .url('http://www.naukri.com')
    .pause(3000)
    .click('#login_Layer')
```

```
$phantomjs --webdriver=4444 

[ERROR - 2015-02-01T17:23:23.646Z] WebElementLocator - _handleLocateCommand - El
ement(s) NOT Found: GAVE UP. Search Stop Time: 1422811403625


$node index.js 
RuntimeError: RuntimeError
     (NoSuchElement:7) An element could not be located on the page using the giv
en search parameters.
     Problem: Unable to find element with id 'login_Layer'←[1;30m

     Callstack:
     -> element("#login_Layer")
     -> click("#login_Layer")
```

**Comment by christian-bromann** [comment]
Tried it by myself and it was working. Might be a network issue on your machine maybe? Try to run the `getTitle` command and you will see if you are really on that page.

**Comment by byteshiva** [comment]
Yes its working, But what I noticed is in selenium-standalone, the end() methods works as expected but the same end() method is not clearing up phantomjs server session at once.

**Comment by EllenChiu** [comment]
@byteshiva  I'm using webdriver i.o with phantomjs, too. And I also notice when the process end, the port sometimes will not really killed. So I have use `process.kill(process.pid, 'SIGTERM');`. Now look is working good. By the way.. I also meet that problem about my page is ready, but the testing will be error, and tell me can't found element..... :( . But I will try Chris's way, should be make sure I have on the page. Thanks for sharing.
