### ISSUE TITLE
Microsoft Edge timeout 

### ISSUE THREAD

**Issue by iamyohann** [webdriverio/webdriverio#4054]
**Microsoft Edge set timeout error**
I'm running a simple e2e test using webdriverio on crossbrowsertesting.com / browserstack.com and I noticed that it fails just after getting the session. Here's the selenium logs:

First request to get selenium session works fine
![image](https://user-images.githubusercontent.com/1330242/58840504-377c5180-86a9-11e9-8a42-0a4a641c5964.png)

Next request to set script timeout fails. It retries this 3 times in total before failing
![image](https://user-images.githubusercontent.com/1330242/58840533-524ec600-86a9-11e9-94ec-5d0f07b50394.png)

My test just visits google.com and waits for the word "Google Search" or "Advertising". I can confirm this is an issue with only Microsoft Edge (all versions). I've tested all other browsers (FF, Chrome, IE 11, Samsung S8 Chrome, Safari etc...

**If it's about a specific piece of code, try and include some of it to support your question.**
[...]

**Environment (please complete the following information):**
 - **WebdriverIO version:*5.9.6* [e.g. 4.13.2]
 - **Mode:*Testrunner* [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:*Async* [e.g. sync/async]
 - **Node.js version:*v10.15.3* [e.g. 8.9.1]
 - **NPM version:*6.9.0* [e.g. 5.8.0]
 - **Browser name and version:*Microsoft Edge 14/15/16* [e.g. Chrome 68]
 - **Platform name and version:*Windows 10* [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):*CodeceptJS* [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Additional context**

**Comment by christian-bromann** [comment]
> I can confirm this is an issue with only Microsoft Edge (all versions)

This can't be fixed in WebdriverIO. It needs to be reported to the cloud vendor or in the Edgedriver project.
