### ISSUE TITLE
.setValue must be a string

### ISSUE THREAD

**Issue by CrispusDH** [webdriverio/webdriverio#4059]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**
Currently, `.setValue()` argument has wrong argument type (`any`). When I put a number as argument I got such error:
```js
  Error {
    message: `Malformed type for "text" parameter of command elementSendKeys␊
    Expected: string␊
    Actual: number␊
    ␊
    For more info see https://w3c.github.io/webdriver/#dfn-element-send-keys␊
    `,
  }
```
So, I see two options:
1) Change argument type from `any` to `string`
2) Change argument type to `string | number`, if argument is a `number` make `.toString()` inside the `.setValue()` method.

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [ ] Missing documentation
- [x] Other

**Comment by christian-bromann** [comment]
@CrispusDH we need to stringify the input in the `setValue` command then.

**Comment by mgrybyk** [comment]
I'm going to
- stringify value
- change type from any to `number | boolean | object | string | any[] | null`
is that ok?

**Comment by christian-bromann** [comment]
> * change type from any to `number | boolean | object | string | any[] | null`

Why this change? We should check what the spec supports

**Comment by CrispusDH** [comment]
@mgrybyk I think type of argument should be either `string` or `number`. I don't think that user would set some `object` in input field

**Comment by mgrybyk** [comment]
@christian-bromann that's because we also support nonW3C `elementSendKeys` that accepts char array, and also our `transformToCharString` accepts number, boolean, object and array.

Also, according to spec we should support `null`. Have I understood it correctly?

> The key input state used for input may be cleared mid-way through “typing” by sending the null key, which is U+E000 (NULL).

**Comment by mgrybyk** [comment]
@CrispusDH our `transformToCharString` supports object, we do `JSON.stringify` if object is passed.

**Comment by mgrybyk** [comment]
@CrispusDH are you going to fix it? Just noticed that you have reassgined this issue to yourself

**Comment by mgrybyk** [comment]
in case you are, here is what I did locally:
changed @param in `addValue.js` and `setValue.js` files
from `@param {*}`
to `@param {string | number | boolean | object | Array<any>}`

changed return value in `addValue.js` file
`return this.elementSendKeys(this.elementId, transformToCharString(value).join(''))`

And of course we need tests :)

**Comment by CrispusDH** [comment]
I will create PR tomorrow :)
