### ISSUE TITLE
Deeplinking on iOS

### ISSUE THREAD

**Issue by martinfrancois** [webdriverio/webdriverio#4061]
**Describe your question with as much detail as possible**
We're testing an app for iOS and Android. We recently implemented deeplinking functionality into the app and need to test it. On Android, we can easily do this: `browser.execute('mobile: deepLink', {url: deeplink, package: 'package'});`, however this doesn't work for iOS per Appium's spec.
Is it possible to call a deeplink from WebdriverIO for iOS, to open an app? We would need a solution which we could use in a test case itself, like the command above. Using a separate config file with the deeplink and safari hardcoded in the capabilities would not be an option, since we don't want webdriverio commands for every different case.
It would be ideal if there was a way with WebdriverIO to leave the app in the config so that the app would be installed on the device initially, the app would then be closed in the test and then we would in some way open Safari, enter the deeplink and open it. However, I didn't figure out how we could switch the context to "Web" at runtime, so that we can simply use `browser.url(...)` to make it easier.

**Comment by wswebcreation** [comment]
Hi @martinfrancois 

Can you provide some logs of why it is not working for iOS?

**Comment by martinfrancois** [comment]
Hi @wswebcreation , thanks for the quick response!
As I mentioned, this is per Appium's spec: http://appium.io/docs/en/commands/mobile-command/ search for: "mobile:deepLink", and then you'll see that it's in the category: Android (UiAutomator2 only). I could in theory provide you the exact message we're getting but as it's not supported by Appium I hardly believe this would help.

**Comment by mgrybyk** [comment]
I was also struggling with deeplinks on iOS but made it work by first installing my native app, then deleting `app` from capabilities and setting `browser` to safari, then opening some site, locally hosted or hosted somewhere in cloud, ex https://codepen.io/xlenz/pen/MLwRzO and finally open link from there :)

**Comment by martinfrancois** [comment]
@mgrybyk sounds good! Did you do this in a separate config file or at runtime? If it's at runtime, I would be interested in the code necessary to delete `app` from capabilities and set `browser` to safari.

**Comment by mgrybyk** [comment]
@martinfrancois btw, if you are opening deeplinks when app is opened, you can just do something like this
```
    if (browser.isIOS) {
        // switch to webview
    } else {
        // switch to native context
    }
    browser.url('your deeplink here')
```

**Comment by mgrybyk** [comment]
here is how I'm changing capabilities in runtime:

```
// this function will set capabilities for next browser session
// ex: you have started with capability `app`
// then you can remove it and add capability `browser`
// then you have to do `browser.reloadSession()`
// NOTE: this works only inside single spec files, other spec files should not be affected!
browser.addCommand("setNextSessionCapabilities", function (capabilities: { alwaysMatch: {} }) {
    const { w3cCaps, jsonwpCaps } = buildCapabilities(capabilities)
    this.options.requestedCapabilities = { w3cCaps, jsonwpCaps }
})

function buildCapabilities (capabilities: { alwaysMatch: {} }) {
    /**
     * the user could have passed in either w3c style or jsonwp style caps
     * and we want to pass both styles to the server, which means we need
     * to check what style the user sent in so we know how to construct the
     * object for the other style
     */
    const [w3cCaps, jsonwpCaps] = capabilities && capabilities.alwaysMatch
        /**
         * in case W3C compliant capabilities are provided
         */
        ? [capabilities, capabilities.alwaysMatch]
        /**
         * otherwise assume they passed in jsonwp-style caps (flat object)
         */
        : [{ alwaysMatch: capabilities, firstMatch: [{}] }, capabilities]

    return { w3cCaps, jsonwpCaps }
}
```

**Comment by martinfrancois** [comment]
Thanks @mgrybyk for now, I'll try that and report back!

**Comment by mgrybyk** [comment]
You welcome.
@wswebcreation do you know a better solution for this?

**Comment by wswebcreation** [comment]
Sorry for my late response.

See [here](https://github.com/wswebcreation/wswebcreation-react-native-app/blob/master/README.md#deep-linking) what I did at a previous project
What I did was calling this `browser.url('applinkName://deeplinkurl');`. This worked for iOS and Android for emu/sim in the native app context, but not with real devices, so I needed to think about a new solution for real devices that didn't use deeplinks but a test nexus, see [here](https://www.slideshare.net/WimSelles/how-react-native-appium-and-me-made-each-other-shine-frontmani-16112018/23?src=clipshare).

I'm going to close this issue because it's not an issue for WebdriverIO, it's still open for conversation

**Comment by mgrybyk** [comment]
My solution worked for me on real devices, both android and iOS.

**Comment by martinfrancois** [comment]
@mgrybyk Thanks a lot! I used your solution and it works very well! Maybe we should consider porting this to Appium / WebdriverIO in order to make it easier for other users to use it as well.

**Comment by wswebcreation** [comment]
@martinfrancois and @mgrybyk 

I wanted to get back to . this when I had the time, but this is what I'm using now. It's working stable, doesn't need to refresh  / reload sessions and works on real devices.

Here's an execution on [Android](https://app.testobject.com/#/share/361beaec-c467-42a8-8a88-f10deccfee47/appium) and here on [iOS](https://app.testobject.com/#/share/90cd5b83-ed95-48a4-b33d-e06ad163c3fe/appium) (iOS failed due to s incorrect assertion, but I think you get the idea).

Android is much faster because of less Appium calls, but this has been running stable now for a lot or tests.

```js

/**
 * Create a  cross platform solution for opening a deep link
 *
 * @param {string} url
 */
export function openDeepLinkUrl(url) {
	const prefix = 'swaglabs://';

	if (driver.isIOS) {
		driver.terminateApp('org.reactjs.native.example.SwagLabsMobileApp');

		driver.execute('mobile: launchApp', { bundleId: 'com.apple.mobilesafari' });

		// This can be 2 different elements, or the button, or the text field
		// checking that it is visible gives us the idea that the browser at least started
		$('~URL').waitForDisplayed(DEFAULT_TIMEOUT);

		// Use the predicate string because  the accessibility label will return 2 different types
		// of elements making it flaky to use. With predicate string we can be more precise
		const urlButtonSelector = 'type == \'XCUIElementTypeButton\' && name CONTAINS \'URL\'';
		const urlFieldSelector = 'type == \'XCUIElementTypeTextField\' && name CONTAINS \'URL\'';
		const urlButton = $(`-ios predicate string:${ urlButtonSelector }`);
		const urlField = $(`-ios predicate string:${ urlFieldSelector }`);

		// If for some reason the url button field is there click on it to trigger the text field
		if (urlButton.isDisplayed()) {
			urlButton.click();
		}

		// Submit the url and add a break
		urlField.setValue(`${ prefix }${ url }\uE007`);

		// Wait for the alert and accept it
		$('~Open').waitForDisplayed(DEFAULT_TIMEOUT);

		return $('~Open').click();
	}

	return driver.execute('mobile:deepLink', {
		url: `${ prefix }${ url }`,
		package: 'com.swaglabsmobileapp',
	});
}
```

**Comment by wswebcreation** [comment]
That's not a deep link, please check the response you get back

**Comment by WesleySarceno** [comment]
Is there any solution for this at the moment? I am using this for Android, iOS:
`async function openAppWithDeepLink(url) {
  if (driver.isIOS) {
    await driver.execute('mobile: openUrl', {
      url,
      package: platforms.Package
    });
  } else if (driver.isAndroid) {
    await driver.execute('mobile: deepLink', {
      url,
      package: platforms.Package,
    });
  }
}`

 however I am getting the error message in the image.

![CleanShot 2023-11-20 at 15 58 30](https://github.com/webdriverio/webdriverio/assets/143039798/fa25f0cb-0676-420a-8914-b9a6fba37c85)

**Comment by cparello** [comment]
Call it what you want but either way it is a valid mobile link and its weird that webdriverio doesn't recognize it when it works on all ios devices

**Comment by wswebcreation** [comment]
Thanks for giving very constructive feedback @cparello and helping the product get better
