### ISSUE TITLE
report details of all passed and failed expectations in Webdriverio 5

### ISSUE THREAD

**Issue by GCHQDeveloper911** [webdriverio/webdriverio#4066]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.10.0
 - **Mode:** Testrunner
 - **If WDIO Testrunner, running sync/async:** Sync
 - **Node.js version:** 10.15.3
 - **NPM version:** 6.2.0
 - **Browser name and version:** Chrome 70
 - **Platform name and version:** Centos 7
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service, @wdio/allure reporter, ]

**Config of WebdriverIO**
Unable to paste from other machine. Fairly standard wdio.conf.js

**Describe the bug**
Some time ago Christian merged my changes for v4 in issue 3125. It would be good to see these replicated in v5.

**To Reproduce**
Create a test with > 1 failing expectation, and 1+ passing. You'll only see the first failure reported. It would be nice to see all expectations reported, including details of "what happened" in passing expectations (eg expected 1 to be greater than 0)

**Expected behavior**
As above

**Log**
N/A

**Comment by christian-bromann** [comment]
> Some time ago Christian merged my changes for v4 in issue 3125. It would be good to see these replicated in v5.

Can you propose a PR here too?

**Comment by GCHQDeveloper911** [comment]
So, given the follow noddy sample test:
```
describe('suite name here', () => {
  it('is a simple demo test', () => {
    expect(1).toEqual(1);
    expect(2).toEqual(2);
    expect(3).toEqual(4);
    expect(5).toEqual(6);
  })
})
```

The good news is that some of the work from #3125 seems to have already made it through from V4 - where only the "3 equals 4" failure would have been reported. Currently in V5 both fails are reported:

```
 "spec" Reporter:
------------------------------------------------------------------
[firefox 3.10.0-957.1.3.el7.x86_64 linux #0-0] Spec: /home/myuser/NewWDIOInst/test/specs/test.js
[firefox 3.10.0-957.1.3.el7.x86_64 linux #0-0] Running: firefox (v3.10.0-957.1.3.el7.x86_64) on linux
[firefox 3.10.0-957.1.3.el7.x86_64 linux #0-0]
[firefox 3.10.0-957.1.3.el7.x86_64 linux #0-0] suite name here
[firefox 3.10.0-957.1.3.el7.x86_64 linux #0-0]    ✖ is a simple demo test
[firefox 3.10.0-957.1.3.el7.x86_64 linux #0-0]
[firefox 3.10.0-957.1.3.el7.x86_64 linux #0-0] 1 failing (822ms)
[firefox 3.10.0-957.1.3.el7.x86_64 linux #0-0]
[firefox 3.10.0-957.1.3.el7.x86_64 linux #0-0] 1) suite name here is a simple demo test
[firefox 3.10.0-957.1.3.el7.x86_64 linux #0-0] Expected 3 to equal 4.
[firefox 3.10.0-957.1.3.el7.x86_64 linux #0-0] Error: Expected 3 to equal 4.
[firefox 3.10.0-957.1.3.el7.x86_64 linux #0-0]     at <Jasmine>
[firefox 3.10.0-957.1.3.el7.x86_64 linux #0-0]     at <Jasmine>
[firefox 3.10.0-957.1.3.el7.x86_64 linux #0-0]     at UserContext.it (/home/myuser/NewWDIOInst/test/specs/test.js:5:15)
[firefox 3.10.0-957.1.3.el7.x86_64 linux #0-0] Expected 5 to equal 6.
[firefox 3.10.0-957.1.3.el7.x86_64 linux #0-0] Error: Expected 5 to equal 6.
[firefox 3.10.0-957.1.3.el7.x86_64 linux #0-0]     at <Jasmine>
[firefox 3.10.0-957.1.3.el7.x86_64 linux #0-0]     at <Jasmine>
[firefox 3.10.0-957.1.3.el7.x86_64 linux #0-0]     at UserContext.it (/home/myuser/NewWDIOInst/test/specs/test.js:6:15)

Spec Files:	 0 passed, 1 failed, 1 total (100% completed) in 00:00:16 
```

So I guess in V5, all I want to add is output along the lines of:
```
[firefox 3.10.0-957.1.3.el7.x86_64 linux #0-0]     Passed - expected 1 to equal 1
[firefox 3.10.0-957.1.3.el7.x86_64 linux #0-0]     Passed - expected 2 to equal 2
```

I'll have a bit of a play, and get a PR in when I can.

**Comment by christian-bromann** [comment]
> [firefox 3.10.0-957.1.3.el7.x86_64 linux #0-0]     Passed - expected 1 to equal 1
> [firefox 3.10.0-957.1.3.el7.x86_64 linux #0-0]     Passed - expected 2 to equal 2

We won't report all passing assertions, that would be too much and I don't really see the value in it. I also think this can't be implemented. Happy to be convinced otherwise.

**Comment by GCHQDeveloper911** [comment]
The agreed change to V4 in #3125 brought in pass reporting? The reason for this (especially when used with "withContext" in jasmine was to aid traceability of faults. Now, admittedly I'm having a struggle persuading the owner of jasmine-core about the benefits, but that's a different battle for me

The example test above is of course, about as contrived and trivial as it could be! Realistically a test may well have a sequence of assertions where one or other value is calculated, or extracted from the application being tested. While a fail assertion will obviously show the failing values, there is benefit in knowing values used throughout the test, both good and bad. 

Ultimately it would be ideal if we could have some sort of "Jasmine reporting detail" config option!
