### ISSUE TITLE
@wdio/sync - Type Declaration Issue

### ISSUE THREAD

**Issue by vladjerca** [webdriverio/webdriverio#4067]
**Describe the bug**
In #4050 the `webdriverio.tpl.d.ts` was modified incorrectly. The `Omit` interface is not part of the `standard` collection of declarations that come with `typescript`.

**Expected behavior**
L37:

```ts
interface RemoteOptions extends WebDriver.Options, Omit<Options, 'capabilities'> { }
```

L189:

```ts
interface Config extends Options, Omit<WebDriver.Options, "capabilities">, Hooks {}
```

Should be updated to use in order to offer proper `typescript` support out of the box.

`Omit<T, K>` can be written as `Pick<T, Diff<keyof T, K>>` 

**Affected Version**: `@wdio/sync@5.10.0`

**Comment by mgrybyk** [comment]
@vladjerca please upgrade to typescript 3.5.1

**Comment by christian-bromann** [comment]
We can close this I guess.
