### ISSUE TITLE
Json Wire Protocol local and session storage methods are now working

### ISSUE THREAD

**Issue by anto-ac** [webdriverio/webdriverio#4068]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version: 5.10.0**
 - **Mode: WDIO Testrunner**
 - **If WDIO Testrunner, running sync/async: sync**
 - **Node.js version: 8.11.4**
 - **Browser name and version:** [e.g. Chrome 75.0.3770.8 and Firefox 67.0]
 - **Platform name and version:** [e.g. Debian Jessie]

**Config of WebdriverIO**
See below for repo with example.

**Describe the bug**

When running the example on both browsers:
- `browser.clearLocalStorage is not a function`
- `browser.clearSessionStorage is not a function`

**To Reproduce**
https://github.com/anto-ac/wdio-sessionStorage-issue

**Expected behavior**
`browser.clearSessionStorage` and `browser.clearSessionStorage` should work.

**Log**
```
ui-test_1             | [1-0] TypeError in "Storage should clear sessionStorage"
ui-test_1             | browser.clearSessionStorage is not a function
```

> Please use the correct markdown

**Comment by anto-ac** [comment]
I have a feeling that this might be because neither browser support the JSON Wire Protocol anymore. Could someone confirm?

**Comment by erwinheitzman** [comment]
This is not an issue with WebdriverIO as indeed both browsers are now using the w3c protocol instead of the json wire protocol. You can use `browser.execute(() => localStorage.clear())` in both browsers instead and the same goes for the sessionStorage.
