### ISSUE TITLE
Request to Feature webdriverio on Docusaurus webpage

### ISSUE THREAD

**Issue by ericbuss** [webdriverio/webdriverio#4072]
Hello, we would like to feature your project to the Docusaurus [users](https://docusaurus.io/en/users) page.

If you are okay with it, are you able to provide a logo we can use? Additional information can be found [here](https://github.com/facebook/Docusaurus/issues/1437)

**Comment by christian-bromann** [comment]
@ericbuss I would be absolutely fine with that! You can use this logo: https://webdriver.io/img/webdriverio.png. If you need an SVG let me know I can provide that too.
