### ISSUE TITLE
how to make browser.debug() REPL repeat last command with uparrow and and autocomplete with tab?

### ISSUE THREAD

**Issue by xwvArmour** [webdriverio/webdriverio#4074]
**Describe your question with as much detail as possible**
When I run wdio repl chrome in the REPL mode, I am able to:
* up-arrow key to repeat the last command
* left-arrow key to move cursor and make correction
* tab to auto-complete

However this capability is lost when I enter REPL mode with browser.debug() command.
The REPL terminal is still functioning, except I have to type each command correctly.

**If it's about a specific piece of code, try and include some of it to support your question.**
```
    this.When(/^I debug browser$/, {timeout: 3600*1000},() => {
       browser.debug() // enter REPL mode;
    } );

[20:31:37]  DEBUG	Queue has stopped!
[20:31:37]  DEBUG	You can now go into the browser or use the command line as REPL
[20:31:37]  DEBUG	(To exit, press ^C again or type .exit)

> (REPL mode, can not use arrow keys and tab key if browser.debug() is used to get here)
```

**Environment (please complete the following information):**
 - **WebdriverIO version:** [webdriverio@4.14.2]
 - **Mode:** [REPL from browser.debug()]
 - **Node.js version:** [v8.16.0]
 - **NPM version:** [6.4.1]
 - **Browser name and version:** [Google Chrome 75.0.3770.80]
 - **Platform name and version:** [ubuntu 18.04]

**Comment by tobeliketree** [comment]
I don't know if I should piggy back on this or create a separate issue but in addition to the above searching for a selector - in my case a nested shadow element -- if the item can not be found the terminal dies / hangs.  

Hitting the escape key bring the prompt back but any new commands you give it will not work and changes as well.  The only way to remedy is to reinitiate the test to get back into debug mode and a clean debug prompt.

**Comment by rkokhatskyi** [comment]
@tobeliketree I think you should go ahead and create a separate issue.

**Comment by perillai** [comment]
With the latest webdriverio, able to get the previous command when the 'up' key is pressed and go left with the 'left' key, but autocomplete on the 'tab' key is not working.

**Comment by erwinheitzman** [comment]
Using the tab key now also works =]
