### ISSUE TITLE
Data Provider - Parallelize tests with multiple data sets 

### ISSUE THREAD

**Issue by yamkay** [webdriverio/webdriverio#4078]
**Is your feature request related to a problem? Please describe.**

If we want to test the same feature for different kinds of data in E2E tests, then we cannot run the same test for different data sets concurrently using current WebDriverIO. 

**Describe the solution you'd like**

This feature, which is similar to Data Provider in TestNG, was developed to make the state of the test known only to the process in which the current test is running in. It is important for UI tests while running in parallel to run in isolation so that the state of the test is not known outside the process the test is running in. Since the state is contained within the process, the state can hold extra information such as test data which allows authors to regress the same test with different set of data in parallel. This will also allow each test to have a fresh instance of browser and hence state of one test will not interfere with any other test running on the same VM. So any cookie/session object/local storage of one test will not be accessible or known to any other tests running in parallel.

This takes the parallel execution of test to the next level by running all the combination in parallel rather than running them in sequence. This also frees up the authors from the responsibility to make sure to flush the browser when multiple tests are running in sequence on the same browser instance.

**Describe alternatives you've considered**

We tried to iterate the same tests in the spec file over different data sets, but the tests were running in sequential fashion which will incur longer execution time and also each subsequent test run will carry forward the state (such as cookie, cache etc) from the previous run/session.

**Additional context**
We have been using this feature for past 6 months. So far, we haven’t discovered any issue with the feature. Our company is interested to open source it to the community.

Also, we have presented this feature in WebDriverIO meet up at Sauce Labs office in San Francisco on Feb 5, 2019. The following are the links for the same presentation.

[YouTube](https://www.youtube.com/watch?v=0YQCVJk8K_Q)
[PowerPoint](https://docs.google.com/presentation/d/1Q-XHIg2XKGxuSNaQsUwqPeA9Eohe0ve1oIgtiN_wPMU/edit?usp=sharing)

For further questions, we can be contacted at our below email addresses.
Kumar.Vikram@move.com
Mohan.Selvaraj@move.com

**Comment by christian-bromann** [comment]
I think this is a really interesting feature and can be implemented into WebdriverIO. Let's continue convo in the PR #4096. Happy to reopen this thread if someone has serious objections. Cheers.

**Comment by SRKarumuri** [comment]
Hi 
I am more interested in using data Provider, do i need to install any packages, what changes do I need to do in wdio.conf in order to cater for dataprovider.
