### ISSUE TITLE
refetch elements for $$

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4080]
**Is your feature request related to a problem? Please describe.**
currently there is no way to do something like:
```
expect( () => $$('foo').length ).eq(2)
$$('foo').waitForExist()
$$('foo').getAttribute('class')
```

**Describe the solution you'd like**
I'd like to wrap $$ response with some smart collection and minimal (but extendable) set of actions that will allow to interact all elements.
```
$$('foo').waitForSize(5) // default equal, but also there should be comparators like less than, greater than, not equal.

// also filters!
$$('foo').filter(el => el.isDisplayed()).map(el => el.getAttribute('class'))
```

not sure about __minimal__ set of actions. I think there is no need to allow some methods to be called for every element (not sure yet)

**Describe alternatives you've considered**
Any other working solution.

**Additional context**
It would be really helpful in assertions and will help users to write much less code!

**Comment by christian-bromann** [comment]
The following is possible:

```js
expect($$('foo').length).eq(2)
```

as well as

```js
$$('foo').filter(el => el.isDisplayed()).map(el => el.getAttribute('class'))
```

I am not sure about `$$('foo').waitForSize(5)` because it really only applies for a set of elements, I rather would advocate to do

```js
browser.waitUntil() => $$('foo').length === 5)
```

I however think it is worth adding all `getX` commands to the `$$` result and extend the array that is being returned.

**Comment by CrispusDH** [comment]
For `async` usage situation is different. Because `Array<Element>` is common js array, so `.map()`, `.filter()` will not work properly with `async ... await`. I use small library for it.

**Comment by christian-bromann** [comment]
Given there has been no further conversation on this issue I will go ahead and close. Happy to re-open if the proposal is more clear. Here are some things that are very confusing to me:

> `$$('foo').getAttribute('class')`

What is the return value suppose to be like?

> `$$('foo').waitForExist()`

This is possible with expect-webdriverio these days, right?
