### ISSUE TITLE
Allure-reporting for wdio with addStep and addFeature

### ISSUE THREAD

**Issue by shridharkalagi** [webdriverio/webdriverio#4082]
Allure-reporting for wdio with addStep and addFeature doesn't seem to be working. 

I have followed the steps as mentioned here [https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-allure-reporter](https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-allure-reporter)

**Below is the code**
`describe('Suite', () => {
    it('Case', () => {
        addFeature('Feature')
    })
})`
and its giving `(0 , _allureReporter.addFeature) is not a function` error

**Environment (please complete the following information):**
 - **WebdriverIO version:*5.10.1* 
 - **Mode:*Standalone* [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:*10.10.0* 
 - **NPM version:** 
 - **Browser name and version:*Chrome 71* 
 - **Platform name and version:*Linux* 
 - **Additional wdio packages used (if applicable):*@wdio/allure-reporter* 

**Additional context**

**Comment by mgrybyk** [comment]
That's strange, have you imported allure package? 
These functions work fine for me

**Comment by shridharkalagi** [comment]
Yes I have imported them as `import { addFeature } from '@wdio/allure-reporter'`

**Comment by shridharkalagi** [comment]
Can you share the sample code please?

**Comment by mgrybyk** [comment]
```
// I'm using TypeScript so import style may differs
import allureReporter from "@wdio/allure-reporter"

describe('foo', () => {
  it('bar', () => {
    // should be called inside it block
    allureReporter.addFeature('feature')
  })
})
```

generated allure results
```
<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1560348160352' stop='1560348160367'>
    <name>chrome: foo</name>
    <title>chrome: foo</title>
    <test-cases>
        <test-case start='1560348160353' status='passed' stop='1560348160361'>
            <name>bar</name>
            <title>bar</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
                <label name='feature' value='feature'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome'/>
            </parameters>
            <steps/>
            <attachments/>
        </test-case>
    </test-cases>
</ns2:test-suite>
```

package.json
```
"devDependencies": {
    "@types/mocha": "^5.2.7",
    "@types/node": "^10.14.8",
    "@wdio/allure-reporter": "^5.9.3",
    "@wdio/cli": "^5.10.3",
    "@wdio/local-runner": "^5.10.1",
    "@wdio/mocha-framework": "^5.10.1",
    "@wdio/reporter": "^5.9.3",
    "@wdio/selenium-standalone-service": "^5.9.3",
    "@wdio/sync": "^5.10.1",
    "mocha": "^6.1.4"
    "ts-node": "^8.2.0",
    "tsconfig-paths": "^3.8.0",
    "typescript": "^3.5.1"
}
```

**Comment by mgrybyk** [comment]
Also, just updated to latest versions and still working fine. Diff:
```
+ husky@2.4.1
+ @wdio/local-runner@5.10.4
+ @wdio/cli@5.10.4
+ @types/node@10.14.9
```

**Comment by mgrybyk** [comment]
try `import allureReporter from "@wdio/allure-reporter"` instead of `import { addFeature } from '@wdio/allure-reporter'`

**Comment by DeepTom** [comment]
> Example, just pasted from my spec file.
> 
> ```
> // I'm using TypeScript so import style may differs
> import allureReporter from "@wdio/allure-reporter"
> 
> // also using @wdio/sync so I'm not using async/await
> describe('foo', () => {
>   it('bar', () => {
>     // should be called inside it block
>     allureReporter.addFeature('feature')
>   })
> })
> ```
> 
> generated allure results
> 
> ```
> <?xml version='1.0'?>
> <ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1560348160352' stop='1560348160367'>
>     <name>chrome: foo</name>
>     <title>chrome: foo</title>
>     <test-cases>
>         <test-case start='1560348160353' status='passed' stop='1560348160361'>
>             <name>bar</name>
>             <title>bar</title>
>             <labels>
>                 <label name='language' value='javascript'/>
>                 <label name='framework' value='wdio'/>
>                 <label name='thread' value='0-0'/>
>                 <label name='feature' value='feature'/>
>             </labels>
>             <parameters>
>                 <parameter kind='argument' name='browser' value='chrome'/>
>             </parameters>
>             <steps/>
>             <attachments/>
>         </test-case>
>     </test-cases>
> </ns2:test-suite>
> ```
> 
> package.json
> 
> ```
> "devDependencies": {
>     "@types/mocha": "^5.2.7",
>     "@types/node": "^10.14.8",
>     "@wdio/allure-reporter": "^5.9.3",
>     "@wdio/cli": "^5.10.3",
>     "@wdio/local-runner": "^5.10.1",
>     "@wdio/mocha-framework": "^5.10.1",
>     "@wdio/reporter": "^5.9.3",
>     "@wdio/selenium-standalone-service": "^5.9.3",
>     "@wdio/sync": "^5.10.1",
>     "mocha": "^6.1.4"
>     "ts-node": "^8.2.0",
>     "tsconfig-paths": "^3.8.0",
>     "typescript": "^3.5.1"
> }
> ```

Hello 
Could you also give an example of addStep where the result of an assertion or an action(like click) would be the result of the addStep status.
