### ISSUE TITLE
Cannot call non W3C standard command while in W3C mode

### ISSUE THREAD

**Issue by imranazad** [webdriverio/webdriverio#4087]
WebdriverIO version: 4.14.4
Mode: WDIO Testrunner
If WDIO Testrunner, running sync/async: sync
Node.js version: 10.15.0
NPM version: 6.4.1
Browser name and version: google-chrome-stable_75.0.3770.80-1
Platform name and version: LINUX
** "wdio-cucumber-framework": "^1.1.0", "wdio-selenium-standalone-service": "0.0.10",

**Describe the bug**
I'm getting the following error attempting to use https://webdriver.io/docs/api/element/waitForExist.html with a chrome instance using the W3C protocol using WebDriverIO:

Cannot call non W3C standard command while in W3C mode

I can obviously set the client to talk to chrome via JSONWP by settings w3c to false. I have done this and I can confirm the error isn't thrown. However my understanding was that webdriverio's waitForExist should be able to handle the underlying translation whether that be JSONWP or W3C

**To Reproduce**
Setup a test environment with the above details

**Expected behavior**
Tests should run without the error Cannot call non W3C standard command while in W3C mode

**Logs**
https://gist.github.com/imranazad/afa3e6c358cd9ad10870d8c49b4db75a

**Comment by christian-bromann** [comment]
@imranazad can you please use the issue template to provide us all necessary information to work with this? I also need logs otherwise this is a guessing game.

**Comment by imranazad** [comment]
@christian-bromann  Sorry about that, I've used the template. Is that OK?

**Comment by imranazad** [comment]
@christian-bromann Where do I get the logs from?

**Comment by imranazad** [comment]
@wswebcreation  Thank you so much for the instructions, really appreciate that. I've updated the original question with a link to the logs. Please let me know if you need anything else.

Thanks

**Comment by wswebcreation** [comment]
@imranazad 

You are using V4, only V5 can do what you expect it to do. For now you need to provide the capability to chrome to disable W3C.

Going to close this because as said this is not something that is related to V5

**Comment by imranazad** [comment]
@wswebcreation That's great thank you. I'm just wanting to deeper understand the issue so am I right in thinking that V5 uses the W3C protocol whereas V4 uses JSONWP?

Also the commands listed here: 
https://webdriver.io/docs/api/element/waitForExist.html

For example waitForExist is that a JSWONP command?

Many Thanks

**Comment by christian-bromann** [comment]
> For example waitForExist is that a JSWONP command?

That command should work for both w3c and jsonwp .. I am sure this error comes from a different command. I recommend to update to v5 as it provides better handling for these protocol issues.

**Comment by imranazad** [comment]
@christian-bromann  OK thank you!
