### ISSUE TITLE
isDisplayed() returning False with Chrome Driver 75.0.3770.8

### ISSUE THREAD

**Issue by caseycantwell** [webdriverio/webdriverio#4090]
Using  "webdriverio": "^5.10.4", we have seen a change in behavior with isDisplayed() after upgrading to the latest version of Chrome Driver.

isDisplayed() using Chrome Driver 74.0.3729.6 will Return True.  

Chrome Driver to version 75.0.3770.8, isDisplayed() will then return false.

Code to reproduce the problem.  I put a long pause to ensure the element is shown before performing the isDisplayed() check.

describe('Debug isDisplayed', function () {
  it('Debug isDisplayed', function () {
    browser.url(`https://dev.nebula.care/practice/`);
    browser.pause(5000);
    const element = $(`neb-practice-app`).shadow$('neb-login-page').shadow$(`#username`);
    console.log(element); 
    console.log(`isDisplayed Debugging:  ${element.isDisplayed()}`);
  });

Console Log Results when running this code using.  Result of isDisplayed() is false with version 75, and true with Chrome Driver 74.
[0-0] Element {
  sessionId: 'c8997e4e69fde46edc9a910ca0d110e0',
  elementId: '11f9d7e4-0789-4e75-adb6-a1110d48bb53',
  'element-6066-11e4-a52e-4f735466cecf': '11f9d7e4-0789-4e75-adb6-a1110d48bb53',
  selector: [Function],
 
[0-0] isDisplayed Debugging:  false

**Comment by CrispusDH** [comment]
@caseycantwell could you use common template?

**Comment by caseycantwell** [comment]
@CrispusDH What do you mean by a common template?  That code is all that's required to replicate the issue using mocha.

**Comment by mgrybyk** [comment]
@caseycantwell may you please format your code properly? You may use the template for it.

The code provided is not working at all

**Comment by mgrybyk** [comment]
anyway, it returns true, saying that element is visible.

![image](https://user-images.githubusercontent.com/25589559/59468469-683f5200-8e32-11e9-9745-d715e5b13ab9.png)


Closing issue for now. Please provide more details and feel free to re-open

**Comment by caseycantwell** [comment]
Did you run that with Chrome Driver 75.0.3770.8?  With 74, it returns true.

**Comment by mgrybyk** [comment]
Used code for testing 
```
it("some test", () => {
    browser.url("https://dev.nebula.care/practice/")
    browser.pause(5000)
    const element = $("neb-practice-app")
        .shadow$('neb-login-page')
        .shadow$("#username");

    console.log(`isDisplayed Debugging: ${ element.isDisplayed() }`);
})
```

![image](https://user-images.githubusercontent.com/25589559/59468690-f74c6a00-8e32-11e9-825e-b4eba6567995.png)

**Comment by caseycantwell** [comment]
If we run with 75.0.3770.8 it returns false.  If we downgrade to 74, it returns true.

**Comment by mgrybyk** [comment]
@caseycantwell can you please also see https://github.com/webdriverio/webdriverio/issues/4073 

maybe the following will help?
```
'goog:chromeOptions': {
        'w3c': false,
        args: ["--headless", "--window-size=1366,768"]
},
```

**Comment by caseycantwell** [comment]
Let me try that... I just did it again, and it came back false :) . [0-0] isDisplayed Debugging: false

**Comment by caseycantwell** [comment]
Thank you!  That solved the problem.  Any thoughts as to why w3c: true would cause this to break?

**Comment by mgrybyk** [comment]
I think this is a defect or expected behavior (?!) of https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/scripts/isElementDisplayed.js

it returns false for react elements.

@christian-bromann @wswebcreation does any of you aware of it?

**Comment by mgrybyk** [comment]
as far as I can see the script cannot handle shadow root elements.

**Comment by DevSide** [comment]
@mgrybyk 
I have a regression too, isElementDisplayed doesn't seem to check the height of parents
```html
<form style="height: 0;">
    <input type="text" data-testid="is_invisible" />
  </form>
```

`is_invisible` is actually considered visible...

**Comment by christian-bromann** [comment]
> The `input` is actually considered visible...

I am not sure about that. Elements were also considered visible if they had a `opacity: 0` property connected to it.

**Comment by DevSide** [comment]
Sorry about that, I figured out where did the problem come from.
My use case was actually:
```html
<form style="height: 0; overflow:hidden; ">
   <input type="text" />
</form>
```
The library normalizer.css add an `overflow:visible` on all buttons and inputs.

**Comment by CrispusDH** [comment]
It might be better to close this one and open new clean issue

**Comment by christian-bromann** [comment]
@vkota4 happy to look into this if you have a minimal reproducible example.
