### ISSUE TITLE
Cannot click on button in Safari

### ISSUE THREAD

**Issue by ilyubin** [webdriverio/webdriverio#4091]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.6.3
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.15.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Safari 11
 - **Platform name and version:** Mac OS High Sierra
 - **Additional wdio packages used (if applicable):**
    "@wdio/allure-reporter": "^5.6.3",
    "@wdio/browserstack-service": "^5.7.2",
    "@wdio/cli": "^5.6.3",
    "@wdio/concise-reporter": "^5.7.8",
    "@wdio/dot-reporter": "^5.6.0",
    "@wdio/local-runner": "^5.6.3",
    "@wdio/mocha-framework": "^5.6.3",
    "@wdio/spec-reporter": "^5.6.0",
    "@wdio/sync": "^5.6.3",

**Config of WebdriverIO**
```
export const wdioConfig: Config = {
  runner: 'local',
  specs: ['./src/specs/**/*.ts'],
  suites: suites,
  logLevel: 'silent',
  bail: 0,
  baseUrl: String(cfg.BASE_URL),
  waitforTimeout: 6000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  user: cfg.BROWSERSTACK_USER,
  key: cfg.BROWSERSTACK_KEY,
  services: ['browserstack'],
  capabilities: [
    {
      maxInstances: 10,
      os: 'OS X',
      os_version: 'High Sierra',
      resolution: '1920x1080',
      browserName: 'safari',
      browserVersion: '11.0',
    },
  ],
  framework: 'mocha',
  reporters: [
    'spec',
    [
      'allure',
      {
        outputDir: 'reports/allure-results',
        disableWebdriverStepsReporting: true,
      },
    ],
  ],
  mochaOpts: {
    ui: 'bdd',
    timeout: 90000000,
  },
  beforeSuite: (): void => {
    browser.setWindowSize(1440, 900);
    browser.setWindowPosition(0, 0);
  },
};

```

**Describe the bug**
Not click on button Добавить в корзину in Safari

**To Reproduce**
open: https://www.ozon.ru/context/detail/id/136147421/
click button: Добавить в корзину
```
  static open(path: string): void {
    allure.addStep(`Открываем ${path}`);
    browser.url(path); // eslint-disable-line
  }

  clickAddToCart(): void {
    browser.pause(2000);
    allure.addStep('Нажимаем "Добавить в корзину"');
    this.addToCart.click();
  }
```
it try to click, button change colour (a little) - but nothing happens

**Expected behavior**
Button clicked and become green

**Log**
https://automate.browserstack.com/builds/260721ceb2f3234f4799ff291e5e2e603eec1d9a/sessions/1aea3e6333be58776d82422ccae05eaf6dda8a87#automate_button

**Comment by mgrybyk** [comment]
@ilyubin first of all there is nothing to do with webdriverio itself, please use gitter for such questions.

There might be multiple issues with your code:
- problems with viewport (by default Safari is not maximized, site maybe shown in mobile view)
- wrong selectors
- wrong anchors (you have to way for something before button is in proper state)
- you haven't scrolled to element
- other

here is rough but working example, it is just for demo purposes!
```
browser.url("https://www.ozon.ru/context/detail/id/136147421/")
// browser.maximizeWindow() // uncomment if you need desktop mode instead of mobile
const el = $("button[data-test-id='saleblock-add-to-cart-button']")
el.scrollIntoView()

el.click()
/** 
* click until item is not added to basket
*/
// I'd better look for some proper anchor saying that button is clickable...
// and then wait for item to be added to basket and for button to change its state.
// Have no time to debug your site.
browser.waitUntil(() => {
    // selectors for both mobile and web
    const counter = $("[data-test-id='counter'],.item-counter")

    // if counter is missing or basket is empty - click again
    if (!counter.isExisting() || +counter.getText().trim() === 0) {
        el.click()
        return false
    }
    return true
}, undefined, undefined, 1000) // 1 second delay between attempts. Site is slow.
```
