### ISSUE TITLE
isDisplayed() doesn't work for element in shadow dom in Chrome 75

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4098]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.10.7
- **Browser:** Chrome 75 in w3c mode, chromedriver 75

**Describe the bug**
`isDisplayed()` doesn't work in Chrome 75 for element in shadow dow.

**To Reproduce**
Use latest chrome (75) in w3c mode set to true (it is true by default).

```
it("some test", () => {
    browser.url("https://dev.nebula.care/practice/")
    browser.pause(5000)
    const element = $("neb-practice-app")
        .shadow$('neb-login-page')
        .shadow$("#username");

    console.log(`isDisplayed Debugging: ${ element.isDisplayed() }`);
})
```

**Expected behavior**
should return true

**Additional context**
https://github.com/webdriverio/webdriverio/issues/4090

**Comment by vlad-vinogradov** [comment]
See [Bug: chromedriver:2943](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2943#c9):
> The Is Element Displayed command is not part of W3C spec, but is still used by some APIs, and its functionality can be difficult to replicate in those APIs. This CL re-enables this command in W3C mode to ease transition to W3C mode
> ...
>In addition, ChromeDriver 76.0.3809.25 and beyond will accept Is Displayed command in both W3C and OSS modes.

**Comment by mgrybyk** [comment]
No longer reproducible, if anyone faces the issue, please provide with detailed steps to reproduce

**Comment by asif-m** [comment]
Im facing similar issue. And using the example already given above, i just modified the code to reflect current state of the UI and for me isDisplayed prints false. 

        browser.url("https://dev.nebula.care/practice/");
        browser.pause(5000);
        const element = $("neb-practice-app").shadow$('#login')        

        console.log(element.isDisplayed());

These are my dependencies in package.json
"devDependencies": {
    "@babel/cli": "^7.8.4",
    "@babel/core": "^7.9.6",
    "@babel/preset-env": "^7.9.6",
    "@babel/register": "^7.9.0",
    "@wdio/allure-reporter": "^6.1.12",
    "@wdio/cli": "^6.1.17",
    "@wdio/jasmine-framework": "^6.1.17",
    "@wdio/junit-reporter": "^6.1.9",
    "@wdio/local-runner": "^6.1.20",
    "@wdio/mocha-framework": "^6.1.19",
    "@wdio/selenium-standalone-service": "^6.1.14",
    "@wdio/spec-reporter": "^6.1.14",
    "@wdio/sync": "^6.1.14",
    "chai": "^4.2.0",
    "chromedriver": "^81.0.0",
    "papaparse": "^5.2.0",
    "wdio-chromedriver-service": "^6.0.3",
    "webdriverio": "^6.1.17"
  },
  "dependencies": {
    "allure": "0.0.0",
    "allure-commandline": "^2.13.0",
    "btoa": "^1.2.1",
    "form-data": "^3.0.0",
    "junit-report-merger": "0.0.6",
    "lodash": "latest",
    "navifiwebd": "^1.0.1",
    "qs": "^6.9.4",
    "request": "^2.88.2",
    "wdio": "^4.0.0"
  }
