### ISSUE TITLE
Browser doesn't perform Arrow commands through browser.keys() method

### ISSUE THREAD

**Issue by Viterzgir666** [webdriverio/webdriverio#4101]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.9.6
 - **Mode:** Standalone
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 8.16.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Chrome, 74
 - **Platform name and version:** MacOS 10.14.5
 - **Additional wdio packages used (if applicable):** ["@wdio/cli": "^5.8.3",
    "@wdio/local-runner",
    "@wdio/mocha-framework",
    "@wdio/selenium-standalone-service",
    "@wdio/spec-reporter",
    "@wdio/sync"]

**Describe the bug**
browser.keys('Down arrow') ('\uE015', 'ArrowDown') doesn't perform press Arrow button action in browser. 

**To Reproduce**
Navigate to the page with a dropdown list with selectable options.
Click that dropdown to expand it. 
User ArrowDown to move through the options of dropdown.

Actual result: Nothing happened. Option focus is not changed on ArrowDown action.

**Expected behavior**
I should be able to move through dropdown options using Arrows.

**Log**
[gist](https://gist.github.com/Viterzgir666/5f0d29718a5bf64eded0c7da1d6b2423)

**Comment by christian-bromann** [comment]
Thanks for submitting the issue. Unfortunately this should be reported in the Chromedriver project. Cheers!

**Comment by Viterzgir666** [comment]
Got it. Thanks!
