### ISSUE TITLE
unable to pass hook typechecks after upgrading to version 5.10.7

### ISSUE THREAD

**Issue by flurmbo** [webdriverio/webdriverio#4104]
**Environment:**
 - **WebdriverIO version:** 5.10.7
 - **Mode:** wdio CLI with mocha
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 10.15.1
 - **NPM version:** 6.9.0
 - **Platform name and version:** Ubuntu 18.04

**Config of WebdriverIO**
```
exports.config = {
  user: credentials.user
  key: credentials.key,
  specs: [
    // specs
  ],
  capabilities: [
    // capabilities
  ],
  framework: 'mocha',
  mochaOpts: {
    ui: 'bdd',
    timeout: 180000, // 3 minutes
  },
};
```
**Describe the bug**
Hi! I tried to upgrade our Webdriverio test script to the latest version, 5.10.7, from 5.7.8. When I tried running the script, I got an error that onPrepare needs to be a list of functions (we currently do not use any hooks). After adding a list containing a dummy function to the config (`onPrepare: [() => {}]`), I got an error saying that config.onPrepare is not a function! Not sure if this is a bug or if I'm misunderstanding how to correctly configure my script, any help would be appreciated!

**To Reproduce**

I think it's fairly clear how to reproduce, but I will make an example if requested

**Expected behavior**
Config should validate successfully with no hooks defined, or with dummy hooks defined

**Log**
```
Worker Error:
Error: Type check for option "onPrepare" failed: a hook option needs to be a list of functions
     at validateConfig 
```
After adding in a list containing 1 dummy function, I get:

```
node_modules/@wdio/cli/build/run.js:89
    throw e;
    ^

TypeError: config.onPrepare is not a function
```

**Comment by christian-bromann** [comment]
> After adding a list containing a dummy function to the config (`onPrepare: [() => {}]`), I got an error saying that config.onPrepare is not a function

Can you try to update all packages in your package.json? Do you have a minimal reproducible example?

**Comment by mgrybyk** [comment]
@christian-bromann @flurmbo I can confirm the issue.

It is possible to pass plain function but it is not possible to pass an array of functions.

**Comment by mgrybyk** [comment]
```
// works fine
const conf: WebdriverIO.Config = {
    onPrepare: (config, caps) => { }
}
```

```
// throws an error
const conf: WebdriverIO.Config = {
    onPrepare: [() => { }]
}
```

**Comment by Laxmipb28** [comment]
Hi All, 

I'm facing the same issue. Is there any solution for this?

**Comment by mgrybyk** [comment]
What exactly are you facing? The solution is to upgrade to the latest versions of all wdio packages

**Comment by Laxmipb28** [comment]
My code is failing when reaches resolve(), it throws
 message:                                                                                         
  'Type check for option "onPrepare" failed: a hook option needs to be a list of functions',      
 stack:                                                                                           
  'Error: Type check for option "onPrepare" failed: a hook option needs to be a list of functions

Can anyone help me with this?

**Comment by mgrybyk** [comment]
Make it a functions list. Does it help?

**Comment by Laxmipb28** [comment]
It was working fine for 1 window, but it was not able to open a new Window. So, I updated the selenium server version using 'java -jar -Dwebdriver.gecko.driver=./geckodriver selenium-server-standalone-3.5.3.jar'. After that, it started giving "Type check for option "onPrepare" failed: a hook option needs to be a list of functions' " . My onprepare method is function list only.

**Comment by mgrybyk** [comment]
It should work fine, both with functions and function list.
Please upgrade to latest versions, try deleting package lock json and nodr modules, and try again.
If it still doesn't work rise an issue with reproducible example in some repo.

**Comment by Laxmipb28** [comment]
Please confirm if these steps correct:
1. Delete node modules folder
2. Delete package-lock.json file
3. npm install
4. npm install webdriverio@latest
5. npm install @wdio/cli --save-dev

I'm not sure if I'm missing something

**Comment by mgrybyk** [comment]
It works for me

**Comment by Laxmipb28** [comment]
Hey,

Thank you so much. It worked for me too.

**Comment by mgrybyk** [comment]
Nice!

**Comment by sytolk** [comment]
Hi All

afterTest hook throw Error: Type check for option "afterTest" failed: a hook option needs to be a list of functions
```javascript
let options = {
      host: 'localhost', // Use localhost as chrome driver server
      port: 9515, // "9515" is the port opened by chrome driver.
      capabilities: {
        browserName: 'chrome',
        'goog:chromeOptions': {
          args: [
            '--no-sandbox',
            '--window-size=1920,1080',
            '--disable-dev-shm-usage'
          ]
        },
        timeouts: {
          script: 60000
        }
      },
      afterTest: async (
        test,
        context,
        { error, result, duration, passed, retries }
      ) => {
        await takeScreenshot();
        await clearLocalStorage();
      },
      waitforTimeout: 5000,
      maxInstances: 1,
      logLevel: 'silent',
      coloredLogs: true
    };

global.client = await webdriverio.remote(options);
```
I have try to change 
```
afterTest: [async (
        test,
        context,
        { error, result, duration, passed, retries }
      ) => {
        await takeScreenshot();
        await clearLocalStorage();
      }],
```
now the error disapers but afterTest hook is newer called. What can be the reason for this ?
