### ISSUE TITLE
Best way to implement 'waitForCondition'

### ISSUE THREAD

**Issue by dylancwood** [webdriverio/webdriverio#411]
Hi, I am just getting started with Selenium and Webdriverio. Thank you for creating and maintaining such a powerful tool.

One feature that exists in the Selenium IDE and Java Webdriver, but appears to be lacking in webdriverio is `waitForCondition` (http://www.seleniumwiki.com/selenium-rc/using-selenium-waitforcondition/). For our purposes, it allows us to evaluate a javascript expression in the **browser's scope** over and over, until it returns a truthy value. 

## More context
Our web application is a single page application with a home-grown pagination system. When the user clicks a link, an AJAX request retrieves the requested page. When the response is received, jQuery is used to evaluate the response and the resulting HTML is placed in the DOM. We need to be able to know when the new page has been successfully rendered, and have created some global variables on the window to help track it. Namely, the function `coinsUtils.seleniumUtils.testNetworkAndPageReady()` will test whether the page has completed rendering. We would like to **wait** for the above function to return true.

## Implementation
I was able to implement this using a recursive call to `client.execute`, but would like your thoughts on whether this is the best way. 
```js
/**
     * waitForCondition
     * performs a busy-wait, while polling for a condition to return true in the browser
     * @param condition {string|Function} required. a string or function to be executed in the browser.
     *   This function will be recursively executed until it returns true, or until timeout
     * @param options {object} an (optional) object containing properties for timeout and interval:
     *   options.interval = the amount of time to wait between polling (default 500ms)
     *   options.timeout = the maximum amount of time to wait
     * Note: this function will be wrapped by webdriverio, and will always be passed a callback
     *   as the last parameter. We use the `vargs` library to extract that callback even though it is
     *   not in the function signature.
     *   TODO: use vargs-callback to wrap this function instead
     */
    client.addCommand('waitForCondition', function(condition, options) {
        //locate callback (always last param)
        var args = new Vargs(arguments);
        cb = args.callback;

        options = args.all[1] || {};
        var timeout = options.timeout || 9000;
        var interval = options.interval || 500;

        var startTime = new Date();
        var self = this;
        var exec = function() {
            return self.pause(interval)
            .execute(condition,
                function(err, ret) {
                    var duration = +new Date() - startTime;
                    var err;
                    if (err) {
                        cb(err);
                    }
                    if (ret.value) {
                        cb();
                    } else {
                        if (duration > timeout) {
                            console.log(timeout);
                            console.log(duration);

                            err = new Error('waitForCondition timeout of ' + timeout + ' exceeded');
                            cb(err);
                            return;
                        }
                        return exec();
                    }
                }
            );
        };
        // call exec to set off the recursive waiting
        return exec();
    });
```

Excited to hear your thoughts on how to improve this, and whether you think this could be a native command.

**Comment by christian-bromann** [comment]
@dylancwood thanks again for that very clear and descriptive issue!

Yes, `waitForCondition` could be a helpful tool to avoid race conditions in the browser. But I would implement it slightly different.

1. instead of looping over the condition using Selenium commands, I would rather use `setInterval` on client side because then you don't need to send http request all the time which are kind of heavy depending on your network conditions. Have a look how we achieved that in [`waitForVisible`](https://github.com/webdriverio/webdriverio/blob/master/lib/helpers/_isVisible.js)
2. once we are on client side we don't really need to care about the interval. I use 100ms for all waitFor commands running in the browser and never had any problems with it. Therefor I would suggest using the same command structure as the other waitFor commands `waitForCondition( <Function>, timeout, reverse)`. If `reverse` is set to true (default is false) it should return once the conditions returns with false.
3. Does the example above work? You defined `exec` in nodejs context and used it in the `execute` command in the browser

What do you think? You can orient yourself on the existing waitFor commands which are implemented after the same idea. Maybe we will be able to refactor some of these to use waitForCondition. If you could tie up a pull request that would be great :+1:

**Comment by dylancwood** [comment]
Thanks! I'll orient using the existing waitFor commands (not sure why I
didn't do that in the first place). Look for a PR from me soon :-)

Respectfully,
Dylan Wood
The Mind Research Network
Neuroinformatics
+1.505.480.5346
dwood@mrn.org

**Comment by christian-bromann** [comment]
awesome looking forward :+1:

**Comment by tobli** [comment]
This would be awesome!
@dylancwood - I'd be happy to help out in getting this PR in place (by implementing and/or testing). Ping me if needed.

**Comment by dylancwood** [comment]
@tobli- thanks. I won't have an opportunity to write the new feature for at least a few days. If you can get to it before then, go for it!

**Comment by cdaringe** [comment]
just for others, I modified @dylancwood 's code above to handle args to the condition function.  see below.  still studying how to xfer this functionality to client.

```js
var _ = require('lodash');
var waitForCondition = function(condition, conditionArgs, options, cb) {
    if (!_.isArray(conditionArgs)) {
        conditionArgs = [conditionArgs];
    }
    options = options || {};
    var timeout = options.timeout || config.defaultTimeout; // you may not have this defined :)
    var interval = options.interval || 500;

    var startTime = new Date();
    var self = this;
    var exec = function() {
        var executeArgs;
        var poll = function(err, ret) {
            var duration = +new Date() - startTime;
            if (err) {
                cb(err);
            }
            if (ret.value) {  // you may want ret.value !== undefined
                cb();
            } else {
                if (duration > timeout) {
                    console.log(timeout);
                    console.log(duration);

                    err = new Error('waitForCondition timeout of ' + timeout + ' exceeded');
                    cb(err);
                    return;
                }
                return exec();
            }
        };
        executeArgs = _.flatten([condition, conditionArgs, poll]);
        return self.pause(interval).execute.apply(self, executeArgs);
    };
    // call exec to set off the recursive waiting
    return exec();
};
```

**Comment by christian-bromann** [comment]
@dylancwood @tobli  could you please check the implementation of [waitUntil](https://github.com/webdriverio/webdriverio/issues/505) it is basically the same like your proposal but I think a bit more easier to work with. If you have ever worked with Protractors wait command. That is the WebdriverIO version of it.

**Comment by christian-bromann** [comment]
Closing as I will forward with the `waitUntil` solution. Thanks @dylancwood for the proposal!

**Comment by dylancwood** [comment]
Thank you for waiting for my input. I apologize for the delay. I am very glad that there is an implementation available now, and look forward to using it :+1:

**Comment by christian-bromann** [comment]
No worries. Will get shipped with `v3` so stay tuned :wink:
