### ISSUE TITLE
Selector doc to update for "id" ?

### ISSUE THREAD

**Issue by reds71** [webdriverio/webdriverio#4112]
Hi !
I'm new to WedbdriverIO so maybe I'm mistaking, but it seems that the syntax for _id_ selectors that is described in main documentation is outdated : `[id=<my id>]` and `#<my id>` seem to work fine, but `id=<my id>` leads to _"Error: InvalidSelectorStrategy"_. Too new to say if this does not apply to other kinds of selectors.
Thanks for the work done !
Stéphane

**Comment by christian-bromann** [comment]
@reds71 can you specify which part in the documentation you are talking about?

**Comment by reds71** [comment]
This one : https://webdriver.io/docs/selectors.html

**Comment by christian-bromann** [comment]
@reds71 yes, but which part?

**Comment by reds71** [comment]
This one ?
```
You can query this element with id by calling:

const id = $('id=driver');
console.log(id.getText()); // outputs: "WebdriverIO"

```

**Comment by christian-bromann** [comment]
Yeah it was added because it is used by a [TV driver](https://github.com/webdriverio/webdriverio/pull/3964/files) but is deprecated when using WebDriver protocol. I think we should add a deprecate sentence to it.

**Comment by christian-bromann** [comment]
@reds71 mind creating a PR?

**Comment by reds71** [comment]
Done.

**Comment by christian-bromann** [comment]
@reds71 do you mind proposing the PR upstream?

**Comment by reds71** [comment]
Thought it was done automatically and that I lost my update ! First time I'm doing a PR on GitHub...

**Comment by christian-bromann** [comment]
> First time I'm doing a PR on GitHub

Awesome!
