### ISSUE TITLE
How to display webdriver run error?

### ISSUE THREAD

**Issue by gitowiec** [webdriverio/webdriverio#4113]
**Describe your question with as much detail as possible**
I have a working setup of webdriver.io in my repository. It uses TypeScript (ts-node), Chromium browser, selenium-standalone and @wdio/mocha-framework and @wdio/dot-reporter, @wdio/spec-reporter and Allure reporter.
The problem shows up on another computer where I have to configure running e2e tests (VM). Whenever I try to run I see first two lines of webdriver.io output and then it just shuts down.
Where I could check what is the error message?
```
TS_NODE_PROJECT=./e2e/tsconfig.json node_modules/.bin/wdio ./e2e/wdio.bootstrap.js --logLevel=debug --spec=e2e/src/specs/authentication/userLoginWithClick-e2e.ts
```
Here is short clip of the result

**If it's about a specific piece of code, try and include some of it to support your question.**
[...]

**Environment (please complete the following information):**
 - **WebdriverIO version:** "webdriverio": "5.6.3",
 - **Mode:** I dont know where to check
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 8.15
 - **NPM version:** 6.4.1
 - **Browser name and version:** [e.g. Chrome 68]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):**     "@wdio/allure-reporter": "5.9.3",
    "@wdio/cli": "5.6.3",
    "@wdio/dot-reporter": "5.6.0",
    "@wdio/junit-reporter": "5.9.3",
    "@wdio/local-runner": "5.6.3",
    "@wdio/mocha-framework": "5.6.3",
    "@wdio/selenium-standalone-service": "5.6.3",
    "@wdio/spec-reporter": "5.6.0",
    "@wdio/sync": "5.6.3",

**Additional context**
Video:
![Peek 2019-06-24 17-25](https://user-images.githubusercontent.com/1553195/60031963-ee1a9300-96a5-11e9-8eda-05a12c1cce9a.gif)

**Comment by christian-bromann** [comment]
Please update all packages. It should solve the issue.

**Comment by gitowiec** [comment]
I just can't make update all wdio packages because when I update @wdio/sync I get error 
````
fibers@4.0.1: The engine "node" is incompatible with this module. Expected version ">=10.0.0". Got "8.16.0"
````
And I need to use NodeJS 8.16 version... could you help me more please? @christian-bromann and reopen this issue?

**Comment by christian-bromann** [comment]
> And I need to use NodeJS 8.16 version

You should look into updating that version. It is not supported anymore. Besides that, you can still use an older `@wdio/sync` version however make sure all other packages are up to date.

**Comment by gitowiec** [comment]
OK, I'll try that,
And where webdriverio keeps its logs? I can't find information about logging to file. Only `--logLevel=debug` does not help me at all because console screen gets wiped out.
Thank you very much for such fast response!

**Comment by christian-bromann** [comment]
https://webdriver.io/docs/options.html#outputdir
