### ISSUE TITLE
Issue with element locators in Internet Explorer 11

### ISSUE THREAD

**Issue by pk-saxena** [webdriverio/webdriverio#4115]
**Environment:**
WebdriverIO version: 4.14.2
Mode: WDIO Testrunner (sync)
Browser name and version: IE 11
selenium standalone: selenium-server-standalone-3.141.59.jar
IE driver: 32 bit 3.14.0

**Config of WebdriverIO:**
specs: [${pathToTests}*.js],
deprecationWarnings: false,
maxInstances: 1,
capabilities: [
{
browserName: 'internet explorer',
platform: 'WINDOWS',
platformName: 'windows',
logLevel: 'trace',
'se:ieOptions': {
'ie.ensureCleanSession': true,
ignoreZoomSetting: true,
ignoreProtectedModeSettings: true
}
}
],
sync: true,

**Issue Description:**
I have following line of code that works perfectly fine in chrome browser but fails when running on IE:
`browser.waitForVisible('tbody tr #recruiter_application_status')`
Getting error:
Error: Promise was rejected with the following reason: result.value.map is not a function
at elementIdDisplayed

Did anyone face similar issue?

**Comment by christian-bromann** [comment]
Please provide the whole tracelog and also a reproducible example. This doesn't help us at all to identify the problem 😞

**Comment by pk-saxena** [comment]
Hi @christian-bromann 
Please find attached logfile. 
[ielog.docx](https://github.com/webdriverio/webdriverio/files/3360026/ielog.docx)
I have also attached the snippet of html in question
[html.docx](https://github.com/webdriverio/webdriverio/files/3360029/html.docx)

The problem is somehow related to interpreting descendent selectors. If I use, `browser.waitForVisible('#recruiter_application_status')`, it works, but `browser.waitForVisible('tbody tr #recruiter_application_status')` doesn't works

**Comment by pk-saxena** [comment]
@christian-bromann Hi. Any update on this issue? Are these logs helpful? If you need some more information from my side please let me know. Thanks

**Comment by christian-bromann** [comment]
@pk-saxena nope .. I don't have Windows so I can't help with this. I also just see that this issue is for v4 which we don't actively maintain anymore. We recommend to upgrade to v5 or if that is not possible try to provide a fix that we can release. Thanks!
