### ISSUE TITLE
Generate sample project files on first setup

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4118]
**Is your feature request related to a problem? Please describe.**
As a WebdriverIO newcomer I'd like to quickly jump into code by skipping initial configuration.

There should be project structure with:
- page objects
- tests
- other required files and folders (?)

Configuration should reflect user choice and differ depending on
- framework: mocha, jasmine, jest, cucumber, ava;
- test target: browsers, mobile; (maybe also grid, browser+mobile, etc)

**Describe the solution you'd like**
TBD

**Describe alternatives you've considered**
Any solution to achieve main goal

**Additional context**
- there should be an ability to skip project files generation
- generated project files should respect user files (do not overwrite them)
- there should be tests to proof that generated files work for a particular framework/etc.

**Comment by christian-bromann** [comment]
I think we need to split this up into multiple issues.

**Comment by CrispusDH** [comment]
It might be better to not specify `page objects`. It could be just `src` and `test`.

**Comment by christian-bromann** [comment]
> It might be better to not specify `page objects`. It could be just `src` and `test`.

Why is that?

**Comment by CrispusDH** [comment]
Someone does not use page object pattern. It is not mandatory for project makes abstraction using page objects. It could be domain based model or roles model etc. So, I suppose make initial naming more non-aligned

**Comment by christian-bromann** [comment]
This has been implemented with #5590
