### ISSUE TITLE
Configure allure reporter with wdio cli for Cucumber users

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4119]
**Is your feature request related to a problem? Please describe.**
As a Cucumber user I'd like to install `@wdio-allure-reporter` package and have it working with screenshots attached to my report.

The following should happen on initial setup at least.

**Describe the solution you'd like**
I'd like allure config to be added depending on framework.
If Cucumber - if should be `beforeStep`
Otherwise - `beforeTest`

**Describe alternatives you've considered**
Alternatively we can make `beforeTest` hook working for Cucumber users as well.

**Additional context**

**Comment by mgrybyk** [comment]
Currently allure reporter is configured for mocha/jasmine users only.
It should be working for Cucumber users out of the box as well.

**Comment by christian-bromann** [comment]
This has been added to the [docs](https://webdriver.io/docs/allure-reporter.html#add-screenshots) and works well: 

![Screenshot 2020-09-15 at 12 27 51](https://user-images.githubusercontent.com/731337/93199640-e59cf500-f74e-11ea-9d4f-b7d8cdad0b65.png)
