### ISSUE TITLE
[Feature Request] Suspend Utility

### ISSUE THREAD

**Issue by iwanjunaid** [webdriverio/webdriverio#413]
Isn't it would be nice if webdriverio implements suspend utility ?

```javascript
client
    .url('http://x.y.z')
    .suspend(callback) {
        'do something like external asynchronous api call'
        callback();
    }
    .end();
```

The end() command would never be called until suspend's callback() is called. I think this would be usefull for asynchronous operations.

**Comment by christian-bromann** [comment]
yeah I was thinking about that. It is like call but with an optional callback. I wouldn't call it `suspend` because I want to avoid to add another command. I would do it like Mocha where all `it` blocks are async once they have a callback parameter:

```js
client.call(function() {
    // sync stuff here because no parameter
});
```
```js
client.call(function(done) {
    // async stuff here because of done parameter
});
```

__Note:__ WebdriverIO supports promises so you could do something like this:

```js
client
    .url("...")
    .then(function() {
        return http.get({...});
    })
    .then(function(response) {
        // ...
     })
```

**Comment by christian-bromann** [comment]
After a thinking about this I decided to not implement this feature as it promotes a bad testing pattern. Try to keep your tests as simple as possible without much logic in it. If you need to do an asynchronous call, just do it in another `it` block:

```js
it('do something with WebdriverIO', function(done) {
    // ....
    client.call(done);
});

it('do an async call', function(done) {
    http.get('...', {}, done);
});

it('do the next thing with WebdriverIO', function(done) {
    // ....
    client.call(done);
});
```

Does that make sense?
