### ISSUE TITLE
Sync mode work slow in some situations when defined hooks beforeCommand and afterCommand

### ISSUE THREAD

**Issue by frg-tarasov** [webdriverio/webdriverio#4133]
**Environment:**
 - **@wdio/cli: 5.10.9**
 - **@wdio/local-runner: 5.10.9**
 - **@wdio/mocha-framework: 5.10.8**
 - **@wdio/selenium-standalone-service: 5.0.2**
 - **@wdio/spec-reporter: 5.9.3**
 - **Node.js version: 10.16.0**
 - **NPM version: 6.9.0**
 - **Browser name and version: Chromium 75.0.3770.100 Linux**
 - **Platform name and version: Linux archlinux 5.1.15-arch1-1-ARCH**

**Config of WebdriverIO and etc**
I prepared repository with full example for reproduce problem
https://github.com/frg-tarasov/webdriverio-sync-slow-example

**Describe the bug**
Sync mode work slow in some situations when defined hooks beforeCommand and afterCommand. Query element by selector may work very slow if elements many.

**Expected behavior**
Time of query element should not dependency hooks and run mode tests.

**Comment by BorisOsipov** [comment]
@frg-tarasov can you set  `logLevel: 'trace'` in wdio.conf.js and add updated logs?

**Comment by frg-tarasov** [comment]
I'm added logs.

**Comment by christian-bromann** [comment]
> I'm added logs.

where?

**Comment by frg-tarasov** [comment]
In repository. https://github.com/frg-tarasov/webdriverio-sync-slow-example/tree/master/slow/logs
As soon as asked added.

**Comment by christian-bromann** [comment]
Can you provide logs using `sync` and without?

**Comment by BorisOsipov** [comment]
Logs are in repo with sample project

**Comment by frg-tarasov** [comment]
Normal folder is without sync mode, slow folder with sync mode. Each folder contains logs.

**Comment by mgrybyk** [comment]
@frg-tarasov first of all there are some problems with your example, not all promises are properly resolved.
Secondly there are no big difference between sync mode and normal mode.

For sure sync mode is a bit slower because we need to wrap functions and / or maybe because of Fibers.

I'm posting my results:

![image](https://user-images.githubusercontent.com/25589559/61234457-67505780-a733-11e9-899c-51b2d166d4aa.png)

![image](https://user-images.githubusercontent.com/25589559/61234482-7505dd00-a733-11e9-80bd-eb375e77261e.png)

**Comment by christian-bromann** [comment]
As @mgrybyk mentioned it could be related to the fact that this goes through the Fibers plugin which runs in C

**Comment by mgrybyk** [comment]
@christian-bromann I found what is causing the problem.
The issue is that we are calling before/after command for every command, even the ones from protocol and internal ones. 
In this particular case `findElementFromElement` spams a lot, it might be called 20-30 per `el.$('span');`

**Comment by frg-tarasov** [comment]
@mgrybyk I see in your output few rows, less than me. Problem more clearly when elements about two hundred.
Because time growing in direct proportion with increase element count.
It is for this i add ```reverse``` because more slow query last elements in dom.

**Comment by frg-tarasov** [comment]
But even in your output have difference between last elements and first.

**Comment by mgrybyk** [comment]
The only workaround for now is to avoid using that hooks

**Comment by frg-tarasov** [comment]
Yes, now i using Webdriver IO without that hooks.

**Comment by christian-bromann** [comment]
Let's continue convo in #4221

**Comment by frg-tarasov** [comment]
Thank you very much!
