### ISSUE TITLE
image comparison: postponed image saved in workspace (mobile)

### ISSUE THREAD

**Issue by tuan91** [webdriverio/webdriverio#4135]
- **WebdriverIO version: 5.7.15
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.15.1
 - **NPM version:** 6.4.1
 - **Platform name and version:** Browserstack
	{
            "os_version": "9.0",
            "device": "Google Pixel 3",
            "real_mobile": "true",
            "browserstack.appium_version": "1.12.1"
        }
 - **Additional wdio packages used (if applicable):** "@wdio/browserstack-service": "^5.7.13", "wdio-image-comparison-service": "^1.1.0"

**Describe the bug**

Visual Regression Test:
expectation:
I want to scroll to an element and save the layout of the element as an image.

Problem only on Mobile:
The image is stored incorrectly. Browserstack indicates that the image was properly saved, but a postponed image is saved in the workspace.
Problem only occurs when several ITs running. If only one IT is running then it will work.

Element:".prod-info__box-container.js-prod-info-box"
URL: https://www.mytoys.de/birkmann-kekskunst-zum-selbermachen-4283014.html

Image Workspace	
![Mobile-info_Box_with_action_banner-393x658](https://user-images.githubusercontent.com/46566423/60518910-c13c3080-9ce2-11e9-8025-e9ed3a39c820.png)

Image Browserstack
![image](https://user-images.githubusercontent.com/46566423/60518743-69052e80-9ce2-11e9-9559-c194249fc5b4.png)

approach:
-browser.pause(3000), before save Picture
-Instead of searching at the search bar, we went directly to the specific URL.

**To Reproduce**

element.scrollIntoView();
browser.saveElement(element, imageNameMobile, {});

browser.checkElement(element, imageNameMobile, {});

**Comment by tuan91** [comment]
wdio.conf
services: [["image-comparison",
        {
            baselineFolder: join(process.cwd(), "./visualRegressionReferenceImages/"),
            formatImageName: "{logName}-{tag}-{width}x{height}",
            screenshotPath: join(process.cwd(), ".tmp/"),
            clearRuntimeFolder: true,
            savePerInstance: true,
            autoSaveBaseline: true,
            blockOutStatusBar: true,
            blockOutToolBar: true
        }], "browserstack"],

**Comment by christian-bromann** [comment]
@tuan91 I am afraid we can't do anything here as this issue is connected to how the screenshot is taken. So please raise an issue in the plugin project: https://github.com/wswebcreation/wdio-image-comparison-service#readme. Thanks!
