### ISSUE TITLE
browser.url returns null instead of string

### ISSUE THREAD

**Issue by zewa666** [webdriverio/webdriverio#4138]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [x] Unclear documentation
- [ ] A typo
- [ ] Missing documentation
- [ ] Other

**Description of the improvement / report**
The browser.url command, documented [here](https://webdriver.io/docs/api/browser/url.html), states that there is no result of the function. Looking at the typescript definitions and the [jsdocs](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/commands/browser/url.js#L28) though its supposed to return a string, namely the current url. First of all it's not quite clear what `current url` means. Is it the one before the navigation or the one applied afterwards.

Yet no matter how consumed I do get `null` as a result, which is not expected.

**Comment by zewa666** [comment]
Oh wow that was quick. Can we safely assume that `null` has here the meaning of `void`?

**Comment by mgrybyk** [comment]
@zewa666 please use https://webdriver.io/docs/api/webdriver.html#geturl for getting url

**Comment by zewa666** [comment]
@mgrybyk thanks I figured that from the documentation, my question was not how to get the URL but rather to see why `url()` actually returns anything. All good and clarified with the latest commit from @christian-bromann. Thx guys
