### ISSUE TITLE
TypeError: browser.clearSessionStorage is not a function in FireFox browser

### ISSUE THREAD

**Issue by 9zemel** [webdriverio/webdriverio#4139]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

WebdriverIO version: 5.6.3
Mode: WDIO Testrunner
If WDIO Testrunner, running sync/async: sync
Node.js version: 10.15.0
NPM version: 6.4.1
Browser name and version: FireFox 67.0.4 (64-bit)
Platform name and version: Mac OS High Sierra 10.13.6
Additional wdio packages used (if applicable):
"@wdio/allure-reporter": "^5.6.3",
"@wdio/browserstack-service": "^5.7.2",
"@wdio/cli": "^5.6.3",
"@wdio/concise-reporter": "^5.7.8",
"@wdio/dot-reporter": "^5.6.0",
"@wdio/local-runner": "^5.6.3",
"@wdio/mocha-framework": "^5.6.3",
"@wdio/spec-reporter": "^5.6.0",
"@wdio/sync": "^5.6.3",

**Config of WebdriverIO**
```
export const wdioConfig: Config = {
  runner: 'local',
  specs: ['./src/specs/**/*.ts'],
  suites: suites,
  logLevel: 'silent',
  bail: 0,
  baseUrl: String(cfg.BASE_URL),
  waitforTimeout: 6000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  user: cfg.BROWSERSTACK_USER,
  key: cfg.BROWSERSTACK_KEY,
  services: ['browserstack'],
  capabilities: [
    {
      maxInstances: 10,
      os: 'OS X',
      os_version: 'High Sierra',
      resolution: '1920x1080',
      browserName: 'safari',
      browserVersion: '11.0',
    },
  ],
  framework: 'mocha',
  reporters: [
    'spec',
    [
      'allure',
      {
        outputDir: 'reports/allure-results',
        disableWebdriverStepsReporting: true,
      },
    ],
  ],
  mochaOpts: {
    ui: 'bdd',
    timeout: 90000000,
  },
  beforeSuite: (): void => {
    browser.setWindowSize(1440, 900);
    browser.setWindowPosition(0, 0);
  },
};
```
**Describe the bug**
Error `TypeError: browser.clearSessionStorage is not a function`
in FireFox WebBrowser
**To Reproduce**
Use in test browser.clearSessionStorage(). Launch test in FireFox Browser.

**Expected behavior**
The storage will be clear.
**Log**

```
 TypeError: browser.clearSessionStorage is not a function
    at Object.clearSessionStorage 
```

**Comment by christian-bromann** [comment]
> Error `TypeError: browser.clearSessionStorage is not a function`
> in FireFox WebBrowser

This function is not supported anymore. Please use the `execute` command and use the web APIs to deal with session storage.

If you have further questions join our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).

**Comment by mgrybyk** [comment]
@christian-bromann if the command is not supported shall we remove it?

**Comment by christian-bromann** [comment]
@mgrybyk for WebDriver sessions it is removed (or not defined for the client), therefor: `browser.clearSessionStorage is not a function`

**Comment by shridharkalagi** [comment]
This method is still in the [API docs ](https://webdriver.io/docs/api/jsonwp.html#clearsessionstorage) Can this be updated please?

**Comment by mgrybyk** [comment]
@shridharkalagi docs are valid

**Comment by shridharkalagi** [comment]
Thanks for the response. `browser.clearSessionStorage()` didn't work for me on Safari 12.1. Is this because its W3C and not JSONWP anymore?

**Comment by christian-bromann** [comment]
> Thanks for the response. `browser.clearSessionStorage()` didn't work for me on Safari 12.1. Is this because its W3C and not JSONWP anymore?

Exact!
