### ISSUE TITLE
saveScreenshot and viewport dimensions

### ISSUE THREAD

**Issue by ff-franciscotavares** [webdriverio/webdriverio#4141]
Hi! 
I'm using `$(selector).saveScreenshot(filename)` to save a screenshot of a specific selector. However, the dimensions of the screenshot that I got were bigger than my viewport.

e.g: 
viewport dimensions: **width: 414,** height: 800,
screenshot dimensions: **width: 485**, height: 499

Is there any explanation for this situation?

**Comment by christian-bromann** [comment]
No, unfortunately it is what WebdriverIO gets from the driver and we can't do much here. Please report this in the driver project. Thanks!
