### ISSUE TITLE
Problems when using wdio launcher programmatically

### ISSUE THREAD

**Issue by Kignuf** [webdriverio/webdriverio#4143]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 5.10.7]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [e.g. 10.15.3]
 - **NPM version:** [e.g. 6.10.0]
 - **Browser name and version:** [e.g. Chrome 75.0.3770.100]
 - **Platform name and version:** [e.g. Macosx Mojave 10.14.5]
 - **Additional wdio packages used (if applicable):** "@wdio/allure-reporter": "^5.10.10",
    "@wdio/cli": "^5.10.7",
    "@wdio/config": "next",
    "@wdio/cucumber-framework": "^5.0.0",
    "@wdio/local-runner": "^5.7.15",
    "@wdio/selenium-standalone-service": "^5.7.8",
    "@wdio/spec-reporter": "^5.7.13",
    "@wdio/sync": "^5.7.13",

**Config of WebdriverIO**
The config can be found [in the following repository](https://github.com/Kignuf/wdio-v5-with-cucumber-test-setup) which can be cloned to reproduce the issue.

**Describe the bug**
When running wdio launcher programmatically, [as explained in the doc](https://webdriver.io/docs/clioptions.html#run-the-test-runner-programmatically), my test fails, whereas the same test is successfull when launched through wdio cli.

**To Reproduce**
* git clone https://github.com/Kignuf/wdio-v5-with-cucumber-test-setup
* npm i
* ./node_modules/.bin/wdio wdio.conf.js
* Test is successfull
* node launcher.js
* Test fails
* hook "afterSession" does not run
* Chrome browser and selenium session are not killed

[Include code or an example repository that can easily be set up]
https://github.com/Kignuf/wdio-v5-with-cucumber-test-setup

**Expected behavior**
Tests results are consistent regardless of running through wdio cli or through wdio launcher programmatically. "afterSession" hook runs properly. Chrome and selenium session are properly closed.

**Log**
Unfortunately logs are not very usefull. I don't get the stdout from the runner, so I don't have the detailed report from spec reporter.
```
node launcher.js

Execution of 1 spec files started at 2019-07-05T14:44:42.425Z

Starting tests
[0-0] RUNNING in chrome - /src/features/login.feature
[0-0] (node:18114) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[0-0] DEBUG - from before hook 0
[0-0] DEBUG - from after hook 1
Result: passed
[0-0] Wdio After:
[0-0] FAILED in chrome - /src/features/login.feature
onComplete: 1

Spec Files:	 0 passed, 1 failed, 1 total (100% completed) in 00:00:06

Exiting with code 1
```

**Additional context**
I've used the wdio cucumber boilerplate project to try cucumber with wdio v5.
I've not tested that issue with mocha or jasmine.

> Please use the correct markdown

**Comment by Kignuf** [comment]
Note: I've tested this issue with wdio configured to use mocha framework and this also is reproducible. So this indicates that the issue is not related to the framework being used.

**Comment by WillBrock** [comment]
@Kignuf You can add an empty object as the second parameter and it'll fix it. I'll have a PR up shortly with the fix.

`const wdio = new Launcher(`${__dirname}/wdio.conf.js`, {});`

**Comment by Kignuf** [comment]
Nice catch, thanks @WillBrock !
Should I close the ticket then ?

**Comment by WillBrock** [comment]
No problem. Once we get the fix merged we can close this.
