### ISSUE TITLE
"CustomRequestError" is hard to track

### ISSUE THREAD

**Issue by CrispusDH** [webdriverio/webdriverio#4144]
**Is your feature request related to a problem? Please describe.**
`CustomRequestError` does not have element's selector in message, that's why it's kind of tricky to understand what exactly element brought it. Take a look at example of `CustomRequestError`:
```js
  Error (CustomRequestError) {
    message: `element not interactable␊
      (Session info: chrome=74.0.3729.157)␊
      (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.9.125-linuxkit x86_64)`,
  }
```

**Describe the solution you'd like**
I think we should wrap this kind of error and add element's selector. With it find root of issue would be easier

**Comment by christian-bromann** [comment]
Let's continue conversation in #4145
