### ISSUE TITLE
Cannot switch iframe due to 'id' can not be string.

### ISSUE THREAD

**Issue by naohashizume** [webdriverio/webdriverio#4154]
**Environment (please complete the following information):**
 - **WebdriverIO version:** ^5.10.9
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v10.15.3
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome 75
 - **Platform name and version:** MacOS 10.14.5
 - **Additional wdio packages used (if applicable):**  @wdio/spec reporter, @wdio-chromedriver-service

**Describe the bug**

I would like to switch browser to `frame source` from `page source`. I'm using [Storybook](https://storybook.js.org/) for testing.

The following flow is what I would like to test:
1. A user clicks button which locates in page source
2. A user can see the result changes in iframe 

In order to get UI element in `iframe`, I need to switch browser to iframe from page source. 
So, using webdriverIO, I would like to `load page source -> click button -> switch to iframe`. 

**To Reproduce**

The use of webdriverIO is
  ``` javascript
  const storyBookFrameId = 'storybook-preview-iframe';
  browser.url(pageSourceUrlName); // load URL(page source) of the browser
 $(uiSelectorName).click(); // click button in page source 
 browser.switchToFrame(storyBookFrameId) // switch to iframe to get UI element in iframe;
```

**Log**

I'm getting a following error:
`invalid argument: 'id' can not be string
  (Session info: chrome=75.0.3770.100)`

From documentation of webdriverIO, I thought that I can use string for id of frame. Any suggestion will be very helpful. Thanks!

**Comment by naohashizume** [comment]
I tried 
```javascript 
browser.switchToFrame($('#storybook-preview-iframe').elementId).
```

But it didn't work =(

**Comment by CrispusDH** [comment]
Try just `browser.switchToFrame($('#storybook-preview-iframe')`

**Comment by naohashizume** [comment]
> Try just `browser.switchToFrame($('#storybook-preview-iframe')`

It worked! Also it worked with `browser.switchToFrame(0);` too. Thanks! 😆

**Comment by Ayodeji31** [comment]
I used `browser.switchToFrame("[data-testid='cybersource-iframe']");` this didn't work even tried 
`browser.frame("[data-testid='cybersource-iframe']"); still didn't work for me. using webdriverio with mocha and appium framework. am getting this error `browser.switchToFrame is not a function`

**Comment by CrispusDH** [comment]
@Ayodeji31 please ask such question in our [gitter channel](https://gitter.im/webdriverio/webdriverio)
