### ISSUE TITLE
setValue for iOS does not clear the text before setting values

### ISSUE THREAD

**Issue by scsannallitw** [webdriverio/webdriverio#4155]
- **WebdriverIO version:** 5.10.10
 - **Node.js version:** 12.1.0
 - **Platform name and version:** ios 12.2 app

** Description**
I'm trying to use setValue() functionality. For android, by default  it does clearValue() and then addValue(). Where as for iOS it does not clear the Value. It just appends the value to the existing;

**Expected behavior**
It should clearValue() before appending value

**Comment by christian-bromann** [comment]
Please provide the Appium logs. This doesn't help at all.

**Comment by scsannallitw** [comment]
[appiumlogs.txt](https://github.com/webdriverio/webdriverio/files/3371868/appiumlogs.txt)

Thanks Chris for quick response. Adding log file

**Comment by christian-bromann** [comment]
As you can see in the logs a clear command was sent:
```
[debug] [35m[WD Proxy][39m Proxying [POST /element/E7010000-0000-0000-E368-000000000000/clear] to [POST http://localhost:8100/session/EDE470AB-9B13-43BC-B1C1-D6081EEB9070/element/E7010000-0000-0000-E368-000000000000/clear] with no body[debug] [35m[WD Proxy][39m Got response with status 200: "{\n  \"status\" : 0,\n  \"id\" : \"E7010000-0000-0000-E368-000000000000\",\n  \"value\" : \"\",\n  \"sessionId\" : \"EDE470AB-9B13-43BC-B1C1-D6081EEB9070\"\n}"
[debug] [35m[W3C (84bd933e)][39m Responding to client with driver.clear() result: null
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/84bd933e-fa5a-4b0c-be15-4a327b93aee5/element/E7010000-0000-0000-E368-000000000000/clear [39m[32m200[39m [90m439 ms - 14[39m
```
This is a bug in Appium or the automation framework that is being used. Closing.
