### ISSUE TITLE
Cucumber: compile options in not recognised

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#4157]
With the latest Cucumber release it seems like the compile option is not recognize and is being ignored. For people that want to integrate Babel you can use this workaround in your config:

```js
    beforeSession: function beforeTest() {
        require('@babel/register');
    },
```

**Comment by mgrybyk** [comment]
@christian-bromann have you tried using `requireModule` ?

**Comment by christian-bromann** [comment]
you mentioned that this works, we should remove all `compile` properties in `cucumberOpts` the docs then.

**Comment by mgrybyk** [comment]
I tested it only for TypeScript.

**Comment by mgrybyk** [comment]
aha, this doc should be updated https://webdriver.io/docs/configurationfile.html

**Comment by christian-bromann** [comment]
> but missed [webdriver.io/docs/configurationfile.html](https://webdriver.io/docs/configurationfile.html)

Let's have it there too

**Comment by mgrybyk** [comment]
We need a volunteer that can make sure docs are valid, I'm updating right now
