### ISSUE TITLE
SetValue to input elements

### ISSUE THREAD

**Issue by jivanova** [webdriverio/webdriverio#416]
Hey, 

I started using WebDriverIO, but I am not able to setValue to multiple elements. Here's my code:

```js
var webdriverio = require('webdriverio');
var options = {
    desiredCapabilities: {
        browserName: 'firefox'
    }
};

webdriverio
    .remote(options)
    .init()
    .url('http://localhost:4000/index.html')
    .elements('.inputs', function (err, res) {
        res.value.forEach(function (input) {
           webdriverio.setValue(input, 'das');
         })
    })
    .end();
```

The error states that webdriverio doesn't have setValue function. When I debug the test only remote is available in the webdriverio..somehow it's not accessible. If i replace .init() with webdriverio.init() it will also throw the error that there is no init method.

Thanks in advance!
Joana

**Comment by byteshiva** [comment]
Your same goal can be acheived in this way, the below example sets multiple values for any html elements.

index.html
~~~
<html>
<body>
        <input type="text" class="inputs"></input>
        <input type="text" class="inputs"></input>
        <input type="text" class="inputs"></input>
</body>
</html>
~~~

package.json
~~~
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "webdriverio": "^2.4.5"
  }
}

~~~


app.js
~~~
var webdriverio = require('webdriverio');
var options = {
     desiredCapabilities: {
            browserName: 'firefox'
    }
};

webdriverio
.remote(options)
.init()
.url('http://localhost:4000/index.html')
.setValue('.inputs',"das");
~~~

**Comment by christian-bromann** [comment]
Hi Joana,

when calling the `elements` it will query these elements and returns a list of WebElement JSON objects. You can use these to click on them but you also need to use a protocol command ([elementIdClick](http://webdriver.io/api/protocol/elementIdClick.html)).

@byteshiva thanks, yes that should work :+1:

**Comment by jivanova** [comment]
Thanks for your replies.

@byteshiva I know that this approach will work, but the values in the inputs will be different. For my example I left just one value in order to be clear where's the issue.

@christian-bromann So this means that my way to setValue is incorrect, right? Using any command(elementIdClick too) on this level will end with error that webdriverio doesn't have such function.

Regards, 
Joana

**Comment by christian-bromann** [comment]
@jivanova you need to first initialise your instance and then use that variable to execute WebdriverIO tests, so try:

```js
var webdriverio = require('webdriverio');
var options = {
     desiredCapabilities: {
            browserName: 'firefox'
    }
};

var client = webdriverio.remote(options);

client
    .init()
    .url('http://localhost:4000/index.html')
    .setValue('.inputs',"das", function() {
         client
              .getTitle()
              // ....
     })
);
```

**Comment by jivanova** [comment]
Thanks, now I understand. However, I still cannot manage to add action command to the test. How could I get the dom element(not Web ELement Json object) and make modifications? I could use the execute method, but I would like to understand the Actions and use them instead. Update of my code:

var client = webdriverio
    .remote(options);

client.init()
    .url('http://localhost:4000/index.html')

    .elements('.inputs', function (err, res) {
        var i=0,
            columns = ['FirstName', 'LastName', 'City'];
        res.value.forEach(function (result) {
            if (result.ELEMENT != "0" ) {                
                client.setValue(result, columns[i]);    
                i++;
            }
         })
    })


Error:

CommandError: CommandError
     Problem: number or type of arguments don't agree with setValue command←[1;3
0m

     Callstack:
     -> setValue({"ELEMENT":"1"},"FirstName")

I receive the error for any action commands.

Thanks for your help!!!

**Comment by christian-bromann** [comment]
In WebdriverIO we have two kind of commands:

1. __protocol commands__: they are the basic implementation of the JSONWire protocol interface. So setting a value on an element using protocol commands would look like this:

```js
client.elements('.inputs', function(err, res) {
    var columns = ['FirstName', 'LastName', 'City'];
    res.value.forEach(function (input, i) {
        if (result.ELEMENT != "0" ) {                
            client.elementIdValue(input, columns[i]);
        }
    })
});
```

As you can see I use [`elementIdValue`](http://webdriver.io/api/protocol/elementIdValue.html) which is also a protocol command and requires a Web Element JSON object

2. __action commands__: these commands are an abstraction on top of all protocol commands. They are using protocol commands to achieve a complex task. So instead of calling `element` and then another command to set the value, you can combine that to use `setValue`

```js
client
    .setValue('input.firstname', 'FirstName')
    .setValue('input.lastname', 'LastName')
    .setValue('input.city', 'City');
```

this looks way cleaner right? You can also use a loop to achieve that:

```js
var inputs = ['FirstName', 'LastName', 'City'];
inputs.forEach(function(input) {
    client.setValue('input.' + input.toLowerCase(), input);
});
```

Hope makes it more clear.
