### ISSUE TITLE
How to disable log output?

### ISSUE THREAD

**Issue by dtboy1995** [webdriverio/webdriverio#4161]
When the script runs, it will output a lot of logs. How to not output? Any help will be appreciated

**Comment by christian-bromann** [comment]
Just set [`logLevel`](https://webdriver.io/docs/options.html#loglevel) to `silent`.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
