### ISSUE TITLE
afterStep function parameters are undefined

### ISSUE THREAD

**Issue by popescunsergiu** [webdriverio/webdriverio#4163]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [5.11.0]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [v10.16.0 LTS]
 - **NPM version:** [v6.9.0]
 - **Browser name and version:** [Any]
 - **Platform name and version:** [Any]
 - **Additional wdio packages used (if applicable):** 
[
     "@wdio/appium-service": "~5.11.0",
    "@wdio/browserstack-service": "~5.11.0",
    "@wdio/cli": "~5.11.0",
    "@wdio/cucumber-framework": "~5.11.0",
    "@wdio/local-runner": "~5.11.0",
    "@wdio/selenium-standalone-service": "~5.11.0",
    "@wdio/spec-reporter": "~5.11.0",
    "@wdio/sync": "~5.11.0",
]

**Config of WebdriverIO**
```
require('@babel/register');

const implicit = 30000, pageLoad = 30000, script = 15000;

exports.config = {
    specs: ['./features/**/*.feature'],
    exclude: [],
    capabilities: [],
    logLevel: 'silent',
    coloredLogs: true,
    bail: 0,
    baseUrl: process.env.baseUrl || 'http://localhost:3000',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    sync: true,
    framework: 'cucumber',
    reporters: [
        'spec'
    ],
    cucumberOpts: {
        require: ['./step-definitions/*.js'],
        backtrace: false,
        compiler: [],
        dryRun: false,
        failFast: false,
        format: ['pretty'],
        colors: true,
        snippets: true,
        source: true,
        profile: [],
        strict: false,
        tags: ['@automated'],
        tagExpression: '',
        timeout: 20000,
        ignoreUndefinedDefinitions: false,
    },
    /**
     * Gets executed before test execution begins. At this point you can access to all global
     * variables like `browser`. It is the perfect place to define custom commands.
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     */
    before: function (capabilities, specs) {
        require('@babel/register');

        browser.setTimeout({
            'implicit': implicit,
            'pageLoad': pageLoad,
            'script': script
        });
    },
    /**
     * Runs after a Cucumber step
     * @param {Object} stepResult step result
     */
    afterStep: function (uri, feature, scenario, step, result) {
        // HERE feature, scenario, step, result are all undefined
    },
    /**
     * Runs after a Cucumber scenario
     * @param {Object} scenario scenario details
     */
    afterScenario: function (uri, feature, scenario) {
    },
};
```

**Describe the bug**
afterStep: function (uri, feature, scenario, step, result)
All parameters are undefined exept uri

**To Reproduce**
Run any cucumber test and inspect the afterStep parameter values

[Include code or an example repository that can easily be set up]

**Expected behavior**
afterStep: function (uri, feature, scenario, step, result) shall have correct value

**Log**

**Additional context**

If you use versions from: https://github.com/webdriverio/webdriverio/pull/3667 
[
    "@wdio/appium-service": "5.10.10",
    "@wdio/browserstack-service": "5.10.8",
    "@wdio/cli": "5.10.10",
    "@wdio/cucumber-framework": "5.6.4",
    "@wdio/local-runner": "5.10.10",
    "@wdio/selenium-standalone-service": "5.9.3",
    "@wdio/spec-reporter": "5.9.3",
    "@wdio/sync": "5.10.8",
]

and 
```
afterStep: function (stepResult) {
```
Then stepResult object has all the expected values
> Please use the correct markdown

**Comment by mgrybyk** [comment]
Will be fixed with https://github.com/webdriverio/webdriverio/pull/4166
