### ISSUE TITLE
How to scroll in android?

### ISSUE THREAD

**Issue by dtboy1995** [webdriverio/webdriverio#4164]
**Thanks for the great library**
*On an Android phone with a height of 1920*
```js
await client.touchPerform([
            { action: 'press', options: { x: 0, y: 1900 } },
            { action: 'moveTo', options: { x: 0, y: 0 } },
            { action: 'release' }
        ])
```
above code not works.
and other question
Can you tell me how to use this function?
```ts
 touchScroll(xoffset: number, yoffset: number, element?: string): void;
```
### Any help would be greatly appreciated

**Comment by christian-bromann** [comment]
Please check the gesture helpers we have in our [Appium Boilerplate](https://github.com/webdriverio/appium-boilerplate/blob/master/tests/helpers/Gestures.js) project. Cheers!
