### ISSUE TITLE
Not possible to call original function on different element in overwriteCommand

### ISSUE THREAD

**Issue by akloeber** [webdriverio/webdriverio#4165]
**Environment (please complete the following information):**
 - **WebdriverIO version:** @5.10.7
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.16.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Chrome 75
 - **Platform name and version:** Mac OS 10.14.5
 - **Additional wdio packages used (if applicable):**
```
 $ yarn list --pattern wdio
yarn list v1.16.0
├─ @wdio/cli@5.10.7
├─ @wdio/config@5.9.4
├─ @wdio/junit-reporter@5.9.3
├─ @wdio/local-runner@5.10.7
├─ @wdio/logger@5.9.3
├─ @wdio/mocha-framework@5.10.1
├─ @wdio/repl@5.9.4
├─ @wdio/reporter@5.9.3
├─ @wdio/runner@5.10.7
├─ @wdio/spec-reporter@5.9.3
├─ @wdio/sync@5.10.1
├─ @wdio/utils@5.9.3
├─ wdio-chromedriver-service@5.0.2
├─ wdio-mochawesome-reporter@3.1.0
├─ webdriver@5.10.9
│  └─ @wdio/config@5.10.8
└─ webdriverio@5.10.9
   ├─ @wdio/config@5.10.8
   └─ @wdio/repl@5.10.8
✨  Done in 0.34s.
```

**Describe the bug**
We are using Kendo UI components and want to override `getValue()` to deliver corrects values for those components. In oder to do this we have to invoke the orginal `getValue()` function on a nested element:
```js
browser.overwriteCommand('getValue', function (origGetValueFn) {
  switch (this.getTagName()) {
    case 'kendo-numerictextbox':
    case 'kendo-datepicker': {
      return origGetValueFn.call(this.$('.k-input'));
    }
    case 'kendo-dropdownlist':
      return this.$('.k-input').getText();
    default:
      return origGetValueFn.call(this);
  }
}, true);
```

Unfortunately it looks like `origGetValueFn` is always bound to the original element und thus the the call of `origGetValueFn` returns `null` in this case as the main element of the Kendo component (e.g. `<kendo-numerictextbox>`) does not have a value itself.

**Expected behavior**
It should be possible to "reuse" `origGetValueFn` on a different element determined inside the override-function.

**Comment by mgrybyk** [comment]
It's work as designed, original function is bound to original element.

**Comment by mgrybyk** [comment]
You may add some command instead of overwriting existing.

**Comment by akloeber** [comment]
Has that been a specific design decision? To me it feels like an unnecessary limitation. There might be a technical reason to prevent rebinding but from a "design" perspective only I can't see a reason why that should be forbidden.
Still, I think it's a valid use case to extended the value resolution in order to also cover custom rich components.
Of course I could add a custom command but in this case it's hard to find a name for it as the straight forward name would be `getValue()`.

**Comment by mgrybyk** [comment]
It was way easier to implement the way it is currently working. It is not a design limitation.
I agree that having more flexibility is better.

PRs are welcomed!

**Comment by akloeber** [comment]
@mgrybyk OK, I try to provide a backwards compatible PR.
