### ISSUE TITLE
I am currently using latest WebdriverIO. I am not able to find the a way or method to close a tab in a browser  using WebdriverIO. Could someone please help me to know if such method exist or how can I achieve this.

### ISSUE THREAD

**Issue by DeepTom** [webdriverio/webdriverio#4168]
**Describe your question with as much detail as possible**
A clear and concise question that doesn't require too much conversation. Need more help? [Find us on Gitter](https://gitter.im/webdriverio/webdriverio)

**If it's about a specific piece of code, try and include some of it to support your question.**
[...]

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2]
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:** [e.g. 8.9.1]
 - **NPM version:** [e.g. 5.8.0]
 - **Browser name and version:** [e.g. Chrome 68]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Additional context**

**Comment by christian-bromann** [comment]
See https://webdriver.io/docs/api/webdriver.html#closewindow

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by DeepTom** [comment]
> See https://webdriver.io/docs/api/webdriver.html#closewindow
> 
> Join our [![Gitter](https://camo.githubusercontent.com/f99733b13256cf0443f9186ebee1a11fae2bbd9a/68747470733a2f2f6261646765732e6769747465722e696d2f776562647269766572696f2f776562647269766572696f2e737667)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

The webdriver link you gave is not helpful in my case as I am looking for closing a tab not a Window. Please correct me if I am incorrect. Anyways, I will go to gitter .

**Comment by christian-bromann** [comment]
> as I am looking for closing a tab not a Window

You will close a top level browsing context which can be both. In WebDriver there is no differentiation between them. Only when you open a new top level browsing context you have to specify tab or window.

**Comment by jurecka** [comment]
Don't forget to call switchToWindow after closeWindow is done, otherwise you will get an error 'target window already closed'. It was not needed to do it in webdriver v4.
```
const originalWindowHandle = await browser.getWindowHandle();
await browser.newWindow(url);
await browser.closeWindow();
await browser.switchToWindow(originalWindowHandler);
```
