### ISSUE TITLE
.execute() script undefined argument

### ISSUE THREAD

**Issue by haoliu119** [webdriverio/webdriverio#417]
I created a custom command as such
```
client.addCommand( 'customCommand', function (opts, callback) {
    return this.execute( function (opts) {
            console.log(opts.name);
        },
        opts,
        function (err, result) {
            if (err) throw err;
            console.log(result);
        }
    ).call(callback);
});
```

However every time I call that custom command such as 
```
client.init()
    .url(someUrl)
    .customCommand( {name: 'foo'} )
    .end();
```
I get an error basically saying argument `opts` is undefined in the script function
```
13:45:56.203 INFO - Executing: [execute script: return (function (opts) {
            console.log(opts.name);
        }).apply(null, arguments);, [{name=foo}] ])
13:45:58.869 WARN - Exception thrown
org.openqa.selenium.WebDriverException: opts is undefined
```

**Comment by christian-bromann** [comment]
@haoliu119 you've forgot a single quotation mark at `addCommand`, this should work:

```js
client.addCommand( 'customCommand', function (opts, callback) {
    return this.execute( function (opts) {
            console.log(opts.name);
        },
        opts,
        function (err, result) {
            if (err) throw err;
            console.log(result);
        }
    ).call(callback);
});
```

**Comment by haoliu119** [comment]
@christian-bromann, it was a typo in my comment which I apologize, It doesn't solve my issue, please re-open this discussion

**Comment by christian-bromann** [comment]
@haoliu119 are you using Firefox? Seems to be only reproducible there

**Comment by haoliu119** [comment]
@christian-bromann, you are correct, I'm running it in Firefox

**Comment by christian-bromann** [comment]
ok, this is [an issue](https://code.google.com/p/selenium/issues/detail?id=8390&q=2.44%20arguments&colspec=ID%20Stars%20Type%20Status%20Priority%20Milestone%20Owner%20Summary) with the current firefoxdriver. I quote:

> Thanks, but this is caused by a change in FF35 and will impact that browser on all platforms.

Please use a firefox version below 35. That should fix the issue.

**Comment by haoliu119** [comment]
Thank you @christian-bromann, looking forward to a fix in current firefox, we need firefox 35 for mp4 in video tags
