### ISSUE TITLE
Can't use moveTo() & positionClick() or buttonDown() on Chrome

### ISSUE THREAD

**Issue by naohashizume** [webdriverio/webdriverio#4171]
**Environment (please complete the following information):**
 - **WebdriverIO version:** ^5.10.9
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v10.15.3
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome 75
 - **Platform name and version:** MacOS 10.14.5
 - **Additional wdio packages used (if applicable):**  @wdio/spec reporter, @wdio-chromedriver-service

**Describe the bug**

I would like to move mouse to the right on slider and click that location. I'm using [Storybook](https://storybook.js.org/) for testing.

Also, I would like to know how to know what `(x,y)` coordinates we want to move when using `moveTo()`.

**To Reproduce**

The use of webdriverIO is
  ``` javascript
 $(selector).moveTo(10,0); // move mouse on slider
 browser.positionClick();
```

**Log**

I'm getting a following error:
`browser.positionClick is not a function`

Also, when I `console.log($(selector).moveTo(10,0));`, it returns `null`.

I also tried `buttonDown()`, but I get same error as above. Thanks!

**Comment by christian-bromann** [comment]
The `positionClick` command is not supported in many browsers anymore. Use the [`performAction`](https://webdriver.io/docs/api/webdriver.html#performactions) to do similar things with the WebDriver protocol. If you have further questions please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).

**Comment by sathyasri123222** [comment]
Hi @christian-bromann, MoveTo() function is not working in Safari Browser. Could you help me in resolving this issue ASAP.

**Comment by UsmanGhani-Emumba** [comment]
Hi @sathyasri123222 did you get any solution for it? I am facing the same problem.
