### ISSUE TITLE
CucumberJS: `before` and `after` hook are printed to the console as `undefined`

### ISSUE THREAD

**Issue by wswebcreation** [webdriverio/webdriverio#4175]
**Environment (please complete the following information):**
 - **WebdriverIO version:** `5.11.1`
 - **Mode:** Testrunner
 - **If WDIO Testrunner, running sync/async:** Sync
 - **Node.js version:** `v10.15.2`
 - **NPM version:** `6.9.0`
 - **Browser name and version:** -
 - **Platform name and version:** -
 - **Additional wdio packages used (if applicable):** `@wdio/spec-reporter`, `@wdio/cucumber-framework`

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
The `before` and `after`-hook are printed in the reporter, see below, but they should be hidden because they don't have a step description

**To Reproduce**
Use the V5 version of WDIO and the latest version of `@wdio/cucumber-framework` (`5.11.1`) and create a simple feature file, add a `before` and` after` hook like this

```js
import { After, Before, Given, Then, When } from 'cucumber';

Before(() => {
  // do nothing
});
After(() => {
  // do nothing
});

Given(/I'm a given step/, () => {});
When(/I'm a when step/, () => {});
Then(/I'm a scenario then step/, () => {});
```

**Expected behavior**
`before` and `after`-hook are not printed

**Log**

```shell
[chrome 75.0.3770.100 Mac OS X #0-0] Spec: /Users/wimselles/Sauce/Git/webdriverio-cucumberjs/__tests__/features/passed.feature
[chrome 75.0.3770.100 Mac OS X #0-0] Running: chrome (v75.0.3770.100) on Mac OS X
[chrome 75.0.3770.100 Mac OS X #0-0]
[chrome 75.0.3770.100 Mac OS X #0-0] Create passed feature
[chrome 75.0.3770.100 Mac OS X #0-0]     Open website
[chrome 75.0.3770.100 Mac OS X #0-0]        ? HookUndefined Step
[chrome 75.0.3770.100 Mac OS X #0-0]        ✓ Given I open "http://webdriver.io/"
[chrome 75.0.3770.100 Mac OS X #0-0]        ✓ Then the title would say "WebdriverIO · Next-gen WebDriver test framework for Node.js"
[chrome 75.0.3770.100 Mac OS X #0-0]        ? HookUndefined Step
[chrome 75.0.3770.100 Mac OS X #0-0]
[chrome 75.0.3770.100 Mac OS X #0-0] 2 passing (2.4s)

Spec Files:      1 passed, 1 total (100% completed) in 00:00:04 
```

**Comment by mgrybyk** [comment]
I can take a look later on today

**Comment by wswebcreation** [comment]
@mgrybyk Awesome and thanks. It's not high priority, it's only a little bit verbose 😉
