### ISSUE TITLE
safe-buffer not in package.json for WebdriverIO package

### ISSUE THREAD

**Issue by nemisj** [webdriverio/webdriverio#4177]
Hi Guys,

Is there a reason why safe-buffer is not included as dependency inside webdriverio (v5) package.json? It's used here https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/commands/browser/saveRecordingScreen.js#L23

I'm using now yarn [pnp](https://yarnpkg.com/lang/en/docs/pnp/) and it's more strict with dependencies

**Comment by christian-bromann** [comment]
This seems to be a bug.

**Comment by nemisj** [comment]
ok, cool, I'll make a PR for that

**Comment by christian-bromann** [comment]
I am on it already

**Comment by christian-bromann** [comment]
Created follow up ticket: https://github.com/webdriverio/webdriverio/issues/4179
