### ISSUE TITLE
Upload coverage report for every PR

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#4180]
In order to better document how well we are doing in terms of code coverage let's update the final report made by Jest to S3 and make it accessible to reviewers. The codecov we use for checking feels a bit clunky to scroll around the files.

_AC_:
- write a script that uploads the directory (`/coverage/lcov-report`) to the `coverage.webdriver.io` S3 bucket
- register after test hook in travis.yml to upload it everytime we do a branch build
- new PRs should upload their reports to `s3://coverage.webdriver.io/<pr_number>`

S3 access credentials are available in Travis.

**Comment by drewctate** [comment]
I've done S3 stuff before. I can work on this

**Comment by christian-bromann** [comment]
Thanks @drewctate , let's continue convo in #4225 then
