### ISSUE TITLE
How do I use regular expressions in xpath selectors?

### ISSUE THREAD

**Issue by dtboy1995** [webdriverio/webdriverio#4184]
```xpath
//android.view.View[@content-desc="somekey-somevalue"]
```

Is there any syntax like this?

```xpath
//android.view.View[contains(@content-desc,"somekey")]
```
How can I dynamically match content-desc?
thanks a lot!

**Comment by christian-bromann** [comment]
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
