### ISSUE TITLE
Should a test fail if error thrown in beforeTest()?

### ISSUE THREAD

**Issue by lukaszfryc** [webdriverio/webdriverio#4185]
A test does not fail if an error is thrown in `beforeTest()`. Is it the correct behavior? I'd expect it to fail.

**To Reproduce**
```
beforeTest: function (test) {
    throw new Error('should die');
}
```
```
it('add new task', function () {
    DashboardPage.open();
});
```

**Comment by christian-bromann** [comment]
> Is it the correct behavior?

Yes, wdio hooks are not interfering with the result of the test. If you want to let your test fail use the framework hooks.
