### ISSUE TITLE
waitForExist returns (null, false) on a timeout

### ISSUE THREAD

**Issue by notnarb** [webdriverio/webdriverio#419]
It seems that most commands will return an error (breaking the chain) when an attempted element is not found, but it seems like waitForExist acts a little differently:
```javascript
if(now - start > ms) {
    return cb(null, false);
}
```
Which allows the chain to continue unless a specific callback is in place to catch a 'false' result value.

e.g.:
```javascript
client()
    .waitForExist('.loadingIcon')
    .click('.loadingIcon')
```
will continue (without failure) to the click event even if the waitForExist loop times out.

---
Perhaps a new error type should be defined and thrown in this instance?
Or maybe the documentation could more clearly reflect that it is not supposed to error on a failure to find an element, and instead return false as a result

**Comment by christian-bromann** [comment]
You're right, it's not completely clear in our docs. According to similar commands in other Selenium libraries and other commands in this project, all waitFor commands should break the chain if no callback is given and return value would be false. I will mark this as enhancement and will tackle it once I got time. Any PRs are welcome of course.

**Comment by notnarb** [comment]
Before writing a new error for waitForExist, what do you think of creating a new standardized error type/message to be thrown when something fails to be found in a timeout?  Currently, if a waitForVisible fails, you get this somewhat unhelpful message:
```
Uncaught RuntimeError
     (ScriptTimeout:28) A script did not complete before its timeout expired.
     Problem: Timed out waiting for async script result after 501ms
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: '', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-44-generic', java.version: '1.7.0_65'
Driver info: driver.version: unknown
```
I feel that readability of errors could be improved if we caught and re-served those sorts of errors instead of letting them bubble up from selenium to your testing framework as somewhat obscure errors. For example, we could instead have an error with a message like:
```
SelectorTimeoutError: Selector "<.whatever.your.selector.is>" could not be found to be <visible|invisible> within the alloted time frame
```
with a syntax of
```javascript
new errors.SelectorTimeoutError(<commandName>, <selector>, <existent|nonexistent|visible|invisible>);
```

**Comment by christian-bromann** [comment]
Sounds good, :+1:
