### ISSUE TITLE
[Cucumber +v5] How to get step/scenario feature status using hooks?

### ISSUE THREAD

**Issue by jorgepOktana** [webdriverio/webdriverio#4190]
Hey, i have a minor issue finding step/scenario/feature status and i use them on my projects as part of wdio hooks.
I am using the **cucumber** framework and i  do certain actions when a step fails (like take a screenshot)
On wdio v4 i used to do this as an after step but now its not working:
```
afterStep: function (stepResult) {
        if (stepResult.getStatus() != 'failed') {
            console.log("Step " + stepResult.getStep().getName() + " " + stepResult.getStatus())
            return;
        } else { browser.saveScreenshot();  } 
}
```

I have tried passing(and logging) step, stepResult, scenario or feature but i dont see anything referring to a status anywhere... so i cant know if step is failed or passed.
Any ideas to where /how i can find this??

**Environment (please complete the following information):**
 - **WebdriverIO version: v5.11.2
 - **Mode:Selenium Standalone
 - **If WDIO Testrunner, running sync/async: sync
 - **Node.js version: v10.16.0
 - **NPM version: v6.9.0
 - **Browser name and version: Chrome
 - **Platform name and version: MacOS

**Comment by mgrybyk** [comment]
@jorgepOktana 
Step Result is the fifth argument, see here https://github.com/webdriverio/webdriverio/pull/4166

**Comment by jorgepOktana** [comment]
Thanks for your answer, yet i dont think im getting the same logs as you...
im doing this: 
``
afterStep: function () {
        console.log('result ', result)
    },
``
and im getting this on the console:
``
result  tests/cucumber/features/createjob.feature
``

**Comment by mgrybyk** [comment]
@jorgepOktana  please see message about, you are passing first arg, but it should be fifth

**Comment by christian-bromann** [comment]
@jorgepOktana please see the docs, the parameter have changed: https://webdriver.io/docs/configurationfile.html
