### ISSUE TITLE
Smart Selectors

### ISSUE THREAD

**Issue by psubrambe** [webdriverio/webdriverio#4191]
**Is your feature request related to a problem? Please describe.**
No it is not a problem ,It is a feature enhancements and more user friendly

**Describe the solution you'd like**
A method for WDIO which doesn't need any Xpath/CSS(locators) instead of that by providing the existing text to find the elements.
**Describe alternatives you've considered**
Taiko 1.0(Gauge) is providing the Smart Selectors were users directly provide the visible text in browser to code to find the elements.

Example 

Go to google search
Click on the google search button.

Instead of checking the DOM elements of site. Instead of that .click("Google Search") it must find the locators.

**Comment by CrispusDH** [comment]
Do you understand how it works in Gauge?

**Comment by christian-bromann** [comment]
Can you please describe in more detail what you describe?

**Comment by psubrambe** [comment]
The proposal is instead of using Xpath/CSS can we just simply provide the text which is visible in browser
For Example 
Launch the Google Search Page
There is two buttons Google Search and I'm Feeling Lucky

In Normal Sceanrio we will provide the
 xpath : (//input[contains(@value,"Google Search")])[2] 
to the .click(xpath).

Instead of above scenario user will provide only visible text or links like Google Search
to the .click(Google Search)

So no need to dig the DOM elements of browser.

**Comment by christian-bromann** [comment]
@psubrambe if you want to take a stab at this great! Something like smart selectors definitely sounds like useful thing for the community. If you expect this to be implemented by someone else you need to provide much more information than this simple example.

**Comment by psubrambe** [comment]
Sure ,I am trying to explore more on this subject .In soon i will come up with more details.

**Comment by CrispusDH** [comment]
I don't see nothing smart in finding Element by text :).

**Comment by psubrambe** [comment]
@CrispusDH : I think you don't understand the smart selectors working .Kindly go-through the below functionality you may get better understanding :) .

https://taiko.gauge.org/?utm_campaign=tw_gauge_taiko&utm_medium=PR&utm_source=PR%20Newswire&utm_content=taiko_release&utm_term=#smart-selectors

https://www.prnewswire.com/news-releases/thoughtworks-releases-taiko---a-free-and-open-source-browser-automation-tool-300882714.html

**Comment by christian-bromann** [comment]
> I think you don't understand the smart selectors working

How can he if you don't explain them. We can all read the docs but their example of `click("Google Search")` is not that "smart" to be honest. It works similar in WebdriverIO already by doing: `$('button=Google Search')`. Just finding out if it is a `button` or any other element to click on is not much magic.

Please provide some more detailed description about what you understand about "smart" selectors, how they are suppose to work and what benefits they bring to user. I currently don't see a problem with the types of selectors WebdriverIO provides and don't see a value to copy the "smart" selector idea from Taiko.
