### ISSUE TITLE
Cannot find module Undefined when using latest cucumber framework in v5

### ISSUE THREAD

**Issue by jlin-namely** [webdriverio/webdriverio#4193]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.11.3
 - **Mode:** cucumber
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.16.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** 75
 - **Platform name and version:** Mac 10.15.5
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
const path = require('path');

exports.config = {
  //
  // ==================
  // Specify Test Files
  // ==================
  // Define which test specs should run. The pattern is relative to the
  // directory from which `wdio` was called. Notice that, if you are calling
  // `wdio` from an NPM script (see https://docs.npmjs.com/cli/run-script)
  // then the current working directory is where your package.json resides, so
  // `wdio` will be called from there.
  //
  specs: ['./app/features/**/*.feature'],
  // Patterns to exclude.
  exclude: [
    // 'path/to/excluded/files'
  ],
  //
  // ============
  // Capabilities
  // ============
  // Define your capabilities here. WebdriverIO can run multiple capabilities
  // at the same time. Depending on the number of capabilities, WebdriverIO
  // launches several test sessions. Within your capabilities you can
  // overwrite the spec and exclude options in order to group specific specs
  // to a specific capability.
  //
  // First, you can define how many instances should be started at the same
  // time. Let's say you have 3 different capabilities (Chrome, Firefox, and
  // Safari) and you have set maxInstances to 1; wdio will spawn 3 processes.
  // Therefore, if you have 10 spec files and you set maxInstances to 10, all
  // spec files will get tested at the same time and 30 processes will get
  // spawned. The property handles how many capabilities from the same test
  // should run tests.
  //
  maxInstances: 1,
  //
  // If you have trouble getting all important capabilities together, check
  // out the Sauce Labs platform configurator - a great tool to configure your
  // capabilities: https://docs.saucelabs.com/reference/platforms-configurator
  //
  capabilities: [
    {
      // maxInstances can get overwritten per capability. So if you have an
      // in-house Selenium grid with only 5 firefox instance available you can
      // make sure that not more than 5 instance gets started at a time.
      maxInstances: 5,
      //
      browserName: 'chrome',
    },
  ],
  //
  // ===================
  // Test Configurations
  // ===================
  // Define all options that are relevant for the WebdriverIO instance here
  //
  // Level of logging verbosity: silent | verbose | command | data | result |
  // error
  logLevel: 'error',
  //
  // Enables colors for log output.
  coloredLogs: true,
  //
  // Saves a screenshot to a given path if a command fails.
  screenshotPath: './errorShots/',
  //
  // Set a base URL in order to shorten getUrl command calls. If your getUrl
  // parameter starts with "/", then the base getUrl gets prepended.
  // baseUrl: 'http://localhost:8080',
  //
  // Default timeout for all waitFor* commands.
  waitforTimeout: 10000,
  //
  // Default timeout in milliseconds for request
  // if Selenium Grid doesn't send response
  connectionRetryTimeout: 90000,
  //
  // Default request retries count
  connectionRetryCount: 3,
  //
  // Initialize the browser instance with a WebdriverIO plugin. The object
  // should have the plugin name as key and the desired plugin options as
  // properties. Make sure you have the plugin installed before running any
  // tests. The following plugins are currently available:
  // WebdriverCSS: https://github.com/webdriverio/webdrivercss
  // WebdriverRTC: https://github.com/webdriverio/webdriverrtc
  // Browserevent: https://github.com/webdriverio/browserevent
  // plugins: {
  //     webdrivercss: {
  //         screenshotRoot: 'my-shots',
  //         failedComparisonsRoot: 'diffs',
  //         misMatchTolerance: 0.05,
  //         screenWidth: [320,480,640,1024]
  //     },
  //     webdriverrtc: {},
  //     browserevent: {}
  // },
  //
  // Test runner services
  // Services take over a specific job you don't want to take care of. They
  // enhance your test setup with almost no effort. Unlike plugins, they don't
  // add new commands. Instead, they hook themselves up into the test process.
  services: ['selenium-standalone'],
  outputDir: path.join(__dirname, 'logs'),
  //
  // Framework you want to run your specs with.
  // The following are supported: Mocha, Jasmine, and Cucumber
  // see also: http://webdriver.io/guide/testrunner/frameworks.html
  //
  // Make sure you have the wdio adapter package for the specific framework
  // installed before running any tests.
  framework: 'cucumber',
  //
  // Test reporter for stdout.
  // The only one supported by default is 'dot'
  // see also: http://webdriver.io/guide/testrunner/reporters.html
  reporters: ['spec'],
  //
  // If you are using Cucumber you need to specify the location of your step
  // definitions.
  cucumberOpts: {
    // <boolean> show full backtrace for errors
    backtrace: true,
    // <string[]> filetype:compiler used for processing required features
    compiler: [],
    // <boolean< Treat ambiguous definitions as errors
    failAmbiguousDefinitions: true,
    // <boolean> invoke formatters without executing steps
    // dryRun: false,
    // <boolean> abort the run on first failure
    failFast: false,
    // <boolean> Enable this config to treat undefined definitions as
    // warnings
    ignoreUndefinedDefinitions: false,
    // <string[]> ("extension:module") require files with the given
    // EXTENSION after requiring MODULE (repeatable)
    name: [],
    // <boolean> hide step definition snippets for pending steps
    snippets: true,
    // <boolean> hide source uris
    source: true,
    // <string[]> (name) specify the profile to use
    profile: [],
    // <string[]> (file/dir) require files before executing features
    require: [
      './app/features/**/*.steps.js',
      // './app/features/**/*.hooks.js',
      // Or search a (sub)folder for JS files with a wildcard
      // works since version 1.1 of the wdio-cucumber-framework
      // './src/**/*.js',
    ],
    // <string> specify a custom snippet syntax
    snippetSyntax: undefined,
    // <boolean> fail if there are any undefined or pending steps
    strict: true,
    // <string> (expression) only execute the features or scenarios with
    // tags matching the expression, see
    // https://docs.cucumber.io/tag-expressions/
    tagExpression: 'not @Pending',
    // <boolean> add cucumber tags to feature or scenario name
    tagsInTitle: false,
    // <number> timeout for step definitions
    timeout: 20000,
  },

  //
  // =====
  // Hooks
  // =====
  // WebdriverIO provides several hooks you can use to interfere with the test
  // process in order to enhance it and to build services around it. You can
  // either apply a single function or an array of methods to it. If one of
  // them returns with a promise, WebdriverIO will wait until that promise got
  // resolved to continue.
  //
  // Gets executed once before all workers get launched.
  // onPrepare: function onPrepare(config, capabilities) {
  // },
  //
  // Gets executed before test execution begins. At this point you can access
  // all global variables, such as `browser`. It is the perfect place to
  // define custom commands.
  before: function before() {
    /**
     * Setup the Chai assertion framework
     */
    // eslint-disable-next-line global-require
    const chai = require('chai');

    global.expect = chai.expect;
    global.assert = chai.assert;
    global.should = chai.should();
  },
  //
  // Hook that gets executed before the suite starts
  // beforeSuite: function beforeSuite(suite) {
  // },
  //
  // Hook that gets executed _before_ a hook within the suite starts (e.g.
  // runs before calling beforeEach in Mocha)
  // beforeHook: function beforeHook() {
  // },
  //
  // Hook that gets executed _after_ a hook within the suite starts (e.g. runs
  // after calling afterEach in Mocha)
  // afterHook: function afterHook() {
  // },
  //
  beforeSession: function beforeTest() {
    // eslint-disable-next-line global-require
    require('@babel/register');
  },
  //
  // Runs before a WebdriverIO command gets executed.
  // beforeCommand: function beforeCommand(commandName, args) {
  // },
  //
  // Runs after a WebdriverIO command gets executed
  // afterCommand: function afterCommand(commandName, args, result, error) {
  // },
  //
  // Function to be executed after a test (in Mocha/Jasmine) or a step (in
  // Cucumber) starts.
  // afterTest: function afterTest(test) {
  // },
  //
  // Hook that gets executed after the suite has ended
  // afterSuite: function afterSuite(suite) {
  // },
  //
  // Gets executed after all tests are done. You still have access to all
  // global variables from the test.
  // after: function after(result, capabilities, specs) {
  // },
  //
  // Gets executed after all workers got shut down and the process is about to
  // exit. It is not possible to defer the end of the process using a promise.
  // onComplete: function onComplete(exitCode) {
  // }
};

**Describe the bug**
When attempt to add my first step definition.  It fails some weird errors.  I used the same dependencies from cucumber-v5 branch in cucumber-boilerpate repo.  When I am running directly in boilerpate, it is working.  When I port it to my project, it is failing with the following error.

[0-0] RUNNING in chrome - /app/features/hcm/login.feature
0-0 worker error { name: 'Error',
  message: 'Cannot find module \'./undefined\'',
  stack:
   'Error: Cannot find module \'./undefined\'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\n    at Module._load (internal/modules/cjs/loader.js:562:25)\n    at Function.hookedLoader [as _load] (/Users/jasonlin/testeng-webdriverio/node_modules/mockery/mockery.js:111:12)\n    at Module.require (internal/modules/cjs/loader.js:690:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.require (/Users/jasonlin/testeng-webdriverio/app/config/configHelper.js:2:19)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Module._compile (/Users/jasonlin/testeng-webdriverio/node_modules/pirates/lib/index.js:99:24)\n    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Object.newLoader [as .js] (/Users/jasonlin/testeng-webdriverio/node_modules/pirates/lib/index.js:104:7)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Module._load (internal/modules/cjs/loader.js:585:3)\n    at Function.hookedLoader [as _load] (/Users/jasonlin/testeng-webdriverio/node_modules/mockery/mockery.js:111:12)\n    at Module.require (internal/modules/cjs/loader.js:690:17)\n    at require (internal/modules/cjs/helpers.js:25:18)' }

**To Reproduce**

import loginPage from '../../../pageObjectModel/hcm/login/login.page';

const {Given, Then, When, And} = require('cucumber');

Given(/^I am on the hcm login page$/, function() {
  loginPage.navigate();
  expect(loginPage.waitForPage()).to.equal(true);
});

**Expected behavior**

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
I am not sure what to do with this. I only see a bunch of unformatted code and no description about the error. Please have a look at our [Cucumber Boilerplate](https://github.com/webdriverio/cucumber-boilerplate) project to get up and running.

**Comment by jlin-namely** [comment]
@christian-bromann It is my first time logging a defect so I am not sure if I file it well.  As I has described that I have used the same package.json and config from cucumber boilerplate but the getting the following error:

```
[0-0] RUNNING in chrome - /app/features/hcm/login.feature
0-0 worker error { name: 'Error',
  message: 'Cannot find module \'./undefined\'',
  stack:
   'Error: Cannot find module \'./undefined\'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\n    at Module._load (internal/modules/cjs/loader.js:562:25)\n    at Function.hookedLoader [as _load] (/Users/jasonlin/testeng-webdriverio/node_modules/mockery/mockery.js:111:12)\n    at Module.require (internal/modules/cjs/loader.js:690:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.require (/Users/jasonlin/testeng-webdriverio/app/config/configHelper.js:2:19)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Module._compile (/Users/jasonlin/testeng-webdriverio/node_modules/pirates/lib/index.js:99:24)\n    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Object.newLoader [as .js] (/Users/jasonlin/testeng-webdriverio/node_modules/pirates/lib/index.js:104:7)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Module._load (internal/modules/cjs/loader.js:585:3)\n    at Function.hookedLoader [as _load] (/Users/jasonlin/testeng-webdriverio/node_modules/mockery/mockery.js:111:12)\n    at Module.require (internal/modules/cjs/loader.js:690:17)\n    at require (internal/modules/cjs/helpers.js:25:18)' }
```
