### ISSUE TITLE
ERROR: Cannot read property 'steps' of undefined after nodejs update from 6 to 10

### ISSUE THREAD

**Issue by gtilekar** [webdriverio/webdriverio#4195]
**Environment (please complete the following information):**
 - WebdriverIO version: 4.14.1
 - Mode: Standalone mode
 - Node.js version: v10.15.1
 - NPM version: 6.4.1
 - Browser name and version: Chrome v68
 - Platform name and version:  Windows 7
 - Additional wdio packages used (if applicable):
    "wdio-allure-reporter": "^0.8.3",
    "wdio-browserstack-service": "^0.1.18",
    "wdio-cucumber-framework": "^2.2.6",
    "wdio-dot-reporter": "^0.0.10",
    "wdio-spec-reporter": "^0.1.5",
    "webdriverio": "^4.14.1",

Hi,
        we have recently update our framework from nodejs v6.9.1 to nodejs v10.

I have updated the package.json to include all the latest versions of packages we are using.

Change i see that defineSupportCode is deprecated in latest version of cucumber framework.
I have made changes in stepDef file to import individual statement from cucumber
const { Given, When, Then } = require('cucumber')

But after this change,when i run my test i see below error
 ERROR: Cannot read property 'steps' of undefined
chrome

I see that this issue was fixed in wdio-cucumber-framework 2.2.1
https://github.com/webdriverio-boneyard/wdio-cucumber-framework/pull/137

We are using scenario Outline,since we have multiple set of examples.

Any idea what could be wrong?

**Comment by christian-bromann** [comment]
> Any idea what could be wrong?

Not really without reproducible example. We recommend to update to v5 of WebdriverIO and follow allow [this boilerplate](https://github.com/webdriverio/cucumber-boilerplate) to setup the project. Let us know in the [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) channel if you need further help. Cheers!

**Comment by gtilekar** [comment]
I have tried with webdriverio": "5.11.2 but it showed below error so i downgraded it to 4. 
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'C:\...... node_modules\webdriverio\build\lib\launcher'

Gitter is blocked in our company :(
so cannot chat on that.

**Comment by christian-bromann** [comment]
> Gitter is blocked in our company :(

That is unfortunate. Maybe your IT team can whitelist it? As this is a setup issue we only can refer you to our boilerplates which are tested and work.

**Comment by gtilekar** [comment]
I found that some scenarios are running while some are not.

so i created a simple scenario from my findings.

below scenario runs with example 1. but throws error for example 2

    Scenario Outline: User can Login
        Given User <user> with <password> and is logged in

       1. Examples:
            | user         | password | 
            | 1234         |                |  
			
	
       2. Examples:
            | user   |
            | 1234  |


login_step.js:
Given(/^User (.*) with (.*) and is logged in$/, function (userId, password) {
    LoginPage.login(userId, password)
})

**Comment by gtilekar** [comment]
Scenario Outline: Login to Portal
        Given User <userId> with <password> and <ID> is logged in
        When User logs out
        Then User is on the login page

    @smoke @country
        Examples:
            | userId   | password | ID  |
            | 12345678 |          | 336 |

    @country @full
        Examples:
            | userId    | password | ID  |
            | 12345678  |          | 336 |
            | 526985478 |          | 337 |

@christian-bromann  when i run the above scenario with tags @county and @full i get the error
Type    at CucumberEventListener.onTestCasePrepared (C:\....\....\node_modules\wdio-cucumber-framework\build\cucumberEventListener.js:211:45)
    at EventEmitter.emit (events.js:194:15)
    at EventEmitter.emit (domain.js:441:20)

When running the scenario with tags @county and @full  while commenting the 1st set of example,
scenario runs successfully.
#    @smoke @country
#        Examples:
#            | userId   | password | ID  |
#            | 12345678 |          | 336 |

Some help would be highly appreciated. :)

**Comment by christian-bromann** [comment]
> Some help would be highly appreciated. :)

Sorry but I don't have the time to help out here. We don't maintain v4 and recommend to update to v5. However we are still happy to merge and release bug fixes for v4.

**Comment by gtilekar** [comment]
we are using  "gulp-webdriver": "^2.0.3" and with v5 it throws below error.

internal/modules/cjs/loader.js:583
throw err;
^

Error: Cannot find module 'C:...... node_modules\webdriverio\build\lib\launcher'

so is gulp-webdriver": "^2.0.3" compatible with v5?

**Comment by christian-bromann** [comment]
> so is gulp-webdriver": "^2.0.3" compatible with v5?

no

**Comment by gtilekar** [comment]
Ok ..then we cannot upgrade to nodejs 10.

Are there any plans of getting newer version of gulp-webdriver rolled out in future.

If not, this pretty much puts us in tight spot.

**Comment by christian-bromann** [comment]
> If not, this pretty much puts us in tight spot

You don't need to us gulp in order to use wdio. I am not using Gulp either so I don't have an interest in updating it but if you have please help us getting it updated.

**Comment by gtilekar** [comment]
@christian-bromann 

we have moved to wdio 5 and landed into same error 

  "@wdio/spec-reporter": "^5.11.7",
    "@wdio/allure-reporter": "^5.11.0",
    "@wdio/cli": "^5.11.7",
    "@wdio/cucumber-framework": "^5.11.6",
    "@wdio/local-runner": "^5.11.6",
    "@wdio/selenium-standalone-service": "^5.11.2",
    "@wdio/sync": "^5.11.0",
    "@wdio/config": "^5.11.0",
	
	
	
	0-0] 2019-07-31T12:36:50.308Z ERROR @wdio/runner: TypeError: Cannot read property 'steps' of undefined
    at CucumberEventListener.onTestCasePrepared (C:\...\...\node_modules\@wdio\cucumber-framework\build\cucumberEventListener.js:132:42)
    at EventEmitter.emit (events.js:187:15)
    at EventEmitter.emit (domain.js:441:20)
    at TestCaseRunner.emit (C:\...\...\node_modules\cucumber\lib\runtime\test_case_runner.js:85:27)
    at TestCaseRunner.emitPrepared (C:\...\...\node_modules\cucumber\lib\runtime\test_case_runner.js:127:10)
    at C:\...\...\node_modules\cucumber\lib\runtime\test_case_runner.js:208:14
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\...\...\node_modules\cucumber\lib\runtime\test_case_runner.js:22:103)
    at _next (C:\...\...\node_modules\cucumber\lib\runtime\test_case_runner.js:24:194)
    at C:\...\...\node_modules\cucumber\lib\runtime\test_case_runner.js:24:364
    at new Promise (<anonymous>)
    at C:\...\...\node_modules\cucumber\lib\runtime\test_case_runner.js:24:97
    at TestCaseRunner.run (C:\...\...\node_modules\cucumber\lib\runtime\test_case_runner.js:228:7)
    at C:\...\...\node_modules\cucumber\lib\runtime\index.js:91:51
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\...\...\node_modules\cucumber\lib\runtime\index.js:26:103)

**Comment by mgrybyk** [comment]
Same reply, remove node modules folder and package lock json file, run npm install

**Comment by gtilekar** [comment]
Tried. Same Error

**Comment by mgrybyk** [comment]
Steps to reproduce are welcomed!

**Comment by gtilekar** [comment]
I have made a simplest example .since I cannot past real example

Feature: Testing login

    Scenario Outline: Login to portal
        Given User <userId> with <password> is logged in
        When User logs out
        Then User is on the login page

    @first
        Examples:
            | userId    | password |
            | 123       | pwd      |

    @second
        Examples:
            | userId       | password |
            | 456          |  pwd     |


when I execute "wdio  config\wdio.conf.js  --cucumberOpts.tagExpression="@first" " it runs successfully.

when I execute "wdio  config\wdio.conf.js  --cucumberOpts.tagExpression="@second" " it throws error.

**Comment by mgrybyk** [comment]
Can you please share step definition?

**Comment by gtilekar** [comment]
const { Given, When, Then } = require('cucumber')

/* GIVEN */
Given(/^User (.*) with (.*) is logged in$/, { wrapperOptions: { retry: 2 } }, function (userId, password) {
    LoginPage.login(userId, password)
})

**Comment by mgrybyk** [comment]
@gtilekar example provided by you is not working at all, it has wrong formatting, invalid regexp, etc.
Can you please share properly working one?

**Comment by mgrybyk** [comment]
aha, make it finally run
```
Feature: Foo
    foobar

    Scenario Outline: Bar
        Given User 123 with qwe is logged in

        @first
        Examples:
                | userId    | password |
                | 123       | pwd      |

        @second
        Examples:
                | userId    | password |
                | 456       | qwe      |
```

```
import { Given } from "cucumber"

Given(/^User (.*) with (.*) is logged in$/, { wrapperOptions: { retry: 2 } }, function (userId, password) {
    console.log(userId, password)
})
```

**Comment by mgrybyk** [comment]
and now it fails for me

**Comment by mgrybyk** [comment]
this is definitely absolutely different issue than original one, @gtilekar can you please submit it?

**Comment by gtilekar** [comment]
Thank you . Appreciate your time. :)
