### ISSUE TITLE
Safari 12.1: isDisplayed() and "text-overflow: ellipsis;" in div

### ISSUE THREAD

**Issue by zhq745w** [webdriverio/webdriverio#4200]
- **WebdriverIO version:** 5.11.5
 - **Mode:** WDIO Testrunner (sync)
 - **Node.js version:** 10.16.0 LTS
 - **NPM version:** 6.9.0
 - **Browser name and version:** Safari 12.1.1
 - **Platform name and version:** MacOS Mojave 10.14.5

![win](https://user-images.githubusercontent.com/26140460/61272073-e8990000-a7ae-11e9-8590-86156b57f2c2.png)

Simple test:
```
describe('test', () => {
  it('test', () => {
    browser.url('https://support.microsoft.com/en-us')
    $('//div[@class="product-name"]//div[text()="Windows"]').waitForDisplayed()
  })
})
```

> 
> [Safari  macOS #0-0] Running: Safari on macOS
> [Safari  macOS #0-0]
> [Safari  macOS #0-0] test
> [Safari  macOS #0-0]    ✖ test
> [Safari  macOS #0-0]
> [Safari  macOS #0-0] 1 failing (13.4s)
> [Safari  macOS #0-0]
> [Safari  macOS #0-0] 1) test test
> [Safari  macOS #0-0] element ("//div[@class="product-name"]//div[text()="Windows"]") still not displayed after 10000ms

WDIO does not work correctly with visibility where div with "text-overflow" attribute in Safari

**Comment by mgrybyk** [comment]
it doesn't work for Chrome as well in w3c mode (w3c: true)
