### ISSUE TITLE
Specifying cucumber scenario line number doesn't work in v5

### ISSUE THREAD

**Issue by michael-confiant** [webdriverio/webdriverio#4205]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.11
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.16.0
 - **NPM version:** 6.9.2
 - **Browser name and version:** chrome v75
 - **Platform name and version:**  macos Mojave 10.14.5
 - **Additional wdio packages used (if applicable):** @wdio/cli, @wdio/selenium-standalone-service, @wdio/spec reporter, @wdio/cucumber-framework

**Describe the bug**
When I specify a cucumber scenario line number I get Error: spec file(s) ./src/features/buttonPress.feature:9 not found

**To Reproduce**
run a wdio with a spec parameter specifying a line number of particular scenario to run
* clone https://github.com/webdriverio/cucumber-boilerplate
* npm i
* npm run local-webserver
* ./node_modules/.bin/wdio wdio.BUILD.conf.js --spec ./src/features/buttonPress.feature:9

**Expected behavior**
Should run a scenario on line 9

**Actual behaviour:**
lib/ConfigParser.js:250
      throw new Error("spec file(s) ${cliArgFileList.join(', ')} not found");
      ^

Error: spec file(s) ./src/features/buttonPress.feature:9 not found

**Comment by d7my11** [comment]
i can look into this and open a PR if nobody did yet

**Comment by christian-bromann** [comment]
> i can look into this and open a PR if nobody did yet

@d7my11 please do

**Comment by michael-confiant** [comment]
@d7my11 @christian-bromann any ideas, guys?

**Comment by christian-bromann** [comment]
> any ideas, guys?

See me comment above

**Comment by mikesalvia** [comment]
@christian-bromann @d7my11 @michael-confiant My PR https://github.com/webdriverio/webdriverio/pull/4696 should add this functionality! Let me know your thoughts, it may actually require a `cucumber-js` update. I am checking that out right now.

**Comment by christian-bromann** [comment]
let's continue convo in PR
