### ISSUE TITLE
moveTo() without arguments throws out of bounds error for scrolled page

### ISSUE THREAD

**Issue by elukoyanov** [webdriverio/webdriverio#4206]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.11.5
 - **Mode:** standalone
 - **Node.js version:** 8.12.0
 - **YARN version:** 1.16
 - **Browser name and version:** Chrome 75
 - **Platform name and version:** MacOS 10.14.5

**Config of WebdriverIO**
does not matter

**Describe the bug**
In W3C mode, when use `element`'s function `moveTo` without any arguments and page is scrolled down more than page height, `move target out of bounds` error is thrown.

`getElementRect` method returns `x` and `y` values as an [absolute y position](https://w3c.github.io/webdriver/#get-element-rect).
```js
  const {
    x,
    y,
    width,
    height
  } = await (0, _utils.getElementRect)(this);
```
Then, if arguments (`xoffset` and `yoffset`) are not passed, then `moveTo` tries to calculate offset as sum of this absolute `y` and element's `height`
```
  const newXoffset = parseInt(x + (typeof xoffset === 'number' ? xoffset : width / 2), 10);
  const newYoffset = parseInt(y + (typeof yoffset === 'number' ? yoffset : height / 2), 10);
```

If page is not scrolled, then method works.
If scrolled for one whole screen, then it tries to move cursor for `(screen height + (element's height/ 2))` from current pointer position. 

**To Reproduce**
Let's suppose we have a page with length of 2 screens, each of 800px. So total length of page is 1600px.
We have a button with height of 100px and width of 200px, started on 900px.

Test scrolls page to second screen. Now it show 801-1600px of page.
We try to move pointer to this button.

So first step is `getElementRect`.
We get `x: 0, y:900, height: 100px, width: 200px`.

Second step is to evaluate `y + (typeof yoffset === 'number' ? yoffset : height / 2)`
900 + 100 / 2 = 950

Third step is to perform action, but it tries to move pointer to current position of pointer + 950px.
This value is more than screen height (800px), so `move target out of bounds` error is thrown

**Additional context**
I use Codeceptjs with WebDriver, so when I try to use `rightClick`, which uses `moveTo` method. It fails.
But in context. This does not matter.

> Please use the correct markdown

**Comment by wizzfizz94** [comment]
I can also confirm this error. Even tried work around by using `scrollIntoView` on element below it and pausing browser for a couple of seconds before executing `moveTo` and still get the error. Pretty annoying, makes interacting with anything besides buttons and basic input elements impossible.

**Comment by mgrybyk** [comment]
@wizzfizz94 what browser are you using?

**Comment by wizzfizz94** [comment]
@mgrybyk im using firefox version 68.0 and selenium-standalone test service.

**Comment by theduykh** [comment]
I'm facing this error also. Have to workaround
Solution A:
1.  Use `scrollIntoView`
2. Then get the element location by executing the script:
```
let elementLocations = browser.execute((selector) => {
        return document.querySelector(selector).getBoundingClientRect();
      }, selector);
```
3. Use the element location to move to the element

Solution B:
Run the test in headless mode and set the window size very large
```
// Chrome
'goog:chromeOptions': {
        'args': ['--window-size=1366,2160']
      },
```
```
// Firefox
browser.setWindowSize(1366, 2160);
```

**Comment by igerasimov23** [comment]
I can reproduce the same bug on :
1. chrome v76, chromedriver 76, selenium-standalone:3.141.59
2. firefox v68, geckodriver 24, selenium-standalone:3.141.59

I did my work around this way:
``` 
element.scrollIntoView();
const yCoordinate = element.getLocation('y');
 element.moveTo(0, -(parseInt(yCoordinate) - 250));
```
But I will use @theduykh solution A which I like

**Comment by mgrybyk** [comment]
this gonna be fixed with https://github.com/webdriverio/webdriverio/pull/4302

**Comment by igerasimov23** [comment]
@mgrybyk Tested on Microsoft Edge 18 and getting error `The target for mouse interaction is not in the browser's viewport and cannot be brought into that viewport.`

Chrome and Firefox look great!

**Comment by mgrybyk** [comment]
I don't know what is going on with Edge, you may submit issue for it with steps to reproduce
