### ISSUE TITLE
Add seleniumArgs and seleniumInstallArgs to WebdriverIO.Config

### ISSUE THREAD

**Issue by anto-ac** [webdriverio/webdriverio#4208]
**Is your feature request related to a problem? Please describe.**
The `WebdriverIO.Config` interface does not include definitions for `seleniumArgs` and `seleniumInstallArgs`, which makes it harder to use `wdio-selenium-standalone-service` when you need to be in control of the browser and driver versions.

**Describe the solution you'd like**
Add `seleniumArgs` and `seleniumInstallArgs` to `WebdriverIO.Config`

**Describe alternatives you've considered**
One alternative is to create your own type that extends `WebdriverIO.Config` `BaseConfig` (which is defined in selenium-standalone)

**Comment by mgrybyk** [comment]
@anto-ac may you rise a PR for this? Please don't forget about `seleniumLogs?: string`

**Comment by anto-ac** [comment]
@mgrybyk I can have a look, but I may need help.

However, I'm thinking, is this something that we should do? In other words, should WebdriverIO.Config include the selenium-standalone configuration?

Or is doing the following on your own project a better approach?

```
import { Config } from '@wdio/sync';
import { BaseConfig } from '@wdio/selenium-standalone-service';

export interface MyConfig extends Config, BaseConfig {}
```

**Comment by christian-bromann** [comment]
@anto-ac it seems to me that they have been added in #3633. Happy to re-open if something is broken with that.
