### ISSUE TITLE
Clarity On Command Process and .call Callback

### ISSUE THREAD

**Issue by cdaringe** [webdriverio/webdriverio#421]
https://github.com/webdriverio/webdriverio/blob/6f9420cb0481355486c541c48eaf691ff56bb848/lib/commands/call.js#L1

is there documentation in the docs on how the wdio commands get chained together?  `.call` takes two args `(cmd, cb)` per the docs, but `cb` isn't shown in the src (perhaps the func is overriden?).  It took a while to debug, but if `cb` is not defined/callable, boy howdy you get an unhelpful error!

**Comment by christian-bromann** [comment]
@cdaringe thanks for reporting this. Yes that's an error in our docs. `call` only takes a single function parameter.

**Comment by cdaringe** [comment]
Thanks @christian-bromann.  How do these all get chained/promisified?  Even a pointer to the code would help if it's easier to just state "look here!"

**Comment by christian-bromann** [comment]
WebdriverIO uses [chainIt](https://github.com/vvo/chainit) to chain the commands and I wrote an [wrapper (PromiseHandler)](https://github.com/webdriverio/webdriverio/blob/master/lib/utils/PromiseHandler.js) around all commands to promisify them. Lets keep this issue open so I don't forget to fix the documentation of call

**Comment by christian-bromann** [comment]
[docu fixed](https://github.com/webdriverio/webdriverio/commit/36607cde226ae066de327e1b106a338264e1f106)
