### ISSUE TITLE
WebDriverIO v5 cucumberOpts is not included in WebdriverIO.Config typescript

### ISSUE THREAD

**Issue by espekkaya** [webdriverio/webdriverio#4215]
**Is your feature request related to a problem? Please describe.**
WebDriverIO v5 cucumberOpts is not included in typescript . I have added wdio.d.ts file but it is nice to have adding in webdriverio package.

WebDriverIO version : 5.11.5

```
    interface Options {
        cucumberOpts?: {
            require: string[],
            backtrace: boolean,
            requireModule: (string | object)[],
            dryRun: boolean,
            failFast: boolean,
            format: string[],
            colors: boolean,
            snippets: boolean,
            source: boolean,
            profile: string[],
            strict: boolean,
            tagExpression: string,
            timeout: number,
            ignoreUndefinedDefinitions: boolean
        }
    }
```

**Comment by mgrybyk** [comment]
@espekkaya may you please rise a PR for this?

**Comment by espekkaya** [comment]
@mgrybyk I have opened PR. Thanks.

**Comment by jayrepo** [comment]
@espekkaya @mgrybyk 
`tags: string[]` shoud be `tagExpression: string`
https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-cucumber-framework/src/constants.js

It also occurs with config generated by wdio cli

**Comment by espekkaya** [comment]
@jayrepo , you are right. I have just edited right now.
