### ISSUE TITLE
uploadFile has return type void, making it not possible to use with eg. typescript.

### ISSUE THREAD

**Issue by erduna** [webdriverio/webdriverio#4217]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.11.6
 - **Mode:** Standalone mode
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.15.1
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome 75
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/spec reporter, @wdio/sync, wdio/selenium-standalone-service, wdio/reporter, wdio/mocha-framework, wdio/cli, wdio/allure-reporter, 

**Config of WebdriverIO**
Using TypeScript. Config indicates usage of @wdio/sync

**Describe the bug**
After saving output from browser.upload, the setValue command reports following error:
*Argument of type 'void' is not assignable to parameter of type 'string | number | boolean | object | any[]'.*

After some investigation it turns out the type definition returns void (as the error indicates). This makes the upload file not usable in this case. When changing the return type to string in the type definitions the test cases using remote upload pass as expected. 

Current type definition in webdriverio-core.d.ts:
`uploadFile(
            localPath: string
        ): void;`

**To Reproduce**
1. Use typescript in sync mode
2. Use output of of browser.uploadFile in a field which expects a string (eg. using setValue)

`const remoteFile = browser.uploadFile(pathToLocalFile);
            uploadPage.uploadButton.setValue(remoteFile);`

**Expected behavior**
We expect the output of browser.uploadFile to return a string, not void. 

**Log**
Not applicable

**Additional context**
Everything should be included in description

**Comment by drewctate** [comment]
Made a PR: https://github.com/webdriverio/webdriverio/pull/4224
Adding `// @ts-ignore` to the line above `uploadPage.uploadButton.setValue(remoteFile);` will fix the problem until the typing is fixed (in case you didn't already know that).

**Comment by erduna** [comment]
I do, but others might not, so thanks for the comment (and the PR) :)

**Comment by christian-bromann** [comment]
Closing as this gets released with the next package publish
