### ISSUE TITLE
wdio 5 Typescript cucumber "$(...).isDisplayed is not a function" error

### ISSUE THREAD

**Issue by espekkaya** [webdriverio/webdriverio#4227]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
WebdriverIO version: 5.11.5
Mode: Standalone mode
WDIO Testrunner, running sync/async: async
Node.js version: v10.15.3
NPM version: 6.10.0
Browser name and version: chrome
Platform name and version: Windows 10

**Describe the bug**
When I run wrote my code below, it throwed an error "$(...).isDisplayed is not a function"

```
    let elm = $(GooglePageObject.searchInput);
    await elm.setValue("test");
    console.log($(GooglePageObject.searchInput).isDisplayed(), "hello");
```

When I do not use twice $ element for same tag, everything is fine.

```
    let elm = $(GooglePageObject.searchInput);
    await elm.setValue("test");
    console.log(elm.isDisplayed(), "hello");
```

Here is my GooglePageObject class;

```
class GooglePageObject extends WorldPageObject {

    public get searchInput(): string { return "input[type='text']"; }

}
```

Is this a bug or what am I missing?

**Comment by mgrybyk** [comment]
You are are not awaiting element. 
Please use gitter for such questions

**Comment by espekkaya** [comment]
Hi @mgrybyk ,

Thank you for quick reply. Yes you are right for using gitter. Sorry about that.
