### ISSUE TITLE
404 Not Found => http://webdriver.io/guide/usage/multiremote.html

### ISSUE THREAD

**Issue by SerkanSipahi** [webdriverio/webdriverio#423]
The URL to http://webdriver.io/guide/usage/multiremote.html is broken !

For the first( if you have not any doc about multiremote ) we could link this: https://github.com/webdriverio/webdriverio/blob/4817616143d0498e9a766ef488e3190c18917c74/examples/webdriverio.multiremote.js

**Comment by christian-bromann** [comment]
@SerkanSipahi yeah sorry about that .. it is already merged into master but still not quite ready for release as I gonna need to change some minor parts. Might be good idea to be more clear about it in the readme.

thanks!
