### ISSUE TITLE
Speedup build

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4231]
**Is your feature request related to a problem? Please describe.**
`npm run build` takes much time

**Describe the solution you'd like**
`npm run build` should not take that much time. 
We might think on speeding up build by tuning babel config and/or moving some packages outside of monorepo.

I think packages lots of packages can be moved out, like reporters, or/and only be built under certain condition (locally, I mean).

Maybe we can tag packages somehow, ex: core-package, feature-packages, or something.

**Describe alternatives you've considered**
Any alternative to speedup build

**Comment by christian-bromann** [comment]
> I think packages lots of packages can be moved out

There are definitely packages that haven't changed a lot but given all the advantages we got from moving them into a mono-repo would get lost if we would move them out again. I agree that setting up the project by running `npm run setup` is slow and uses a lot of CPU but moving out packages would be my last option. I rather would see if we can build something that improves our current situation (NPM cache, build improvements etc.).
