### ISSUE TITLE
setImmediateValue is missing in WDIO-5

### ISSUE THREAD

**Issue by tejasv02** [webdriverio/webdriverio#4238]
**Describe your question with as much detail as possible**
setImmediateValue was useful in inputting long string in WDIO-4 but now it WDIO we use setValue which maps to - `elementSendKeys`, hence strings becomes array of characters

**Environment (please complete the following information):**
 - **WebdriverIO version:5.11.7**

**Comment by christian-bromann** [comment]
The command is available here: https://webdriver.io/docs/api/appium.html#setvalueimmediate

**Comment by tejasv02** [comment]
Thanks totally missed the driver
