### ISSUE TITLE
multiRemote is not implemented !?!

### ISSUE THREAD

**Issue by SerkanSipahi** [webdriverio/webdriverio#424]
it seem that multiRemote is not implemented:

```shell
webdriverio$ node test.js

webdriverio/test.js:3
    matrix = webdriverio.multiRemote({
                         ^
TypeError: Object #<Object> has no method 'multiRemote'
```
```shell
webdriverio$ grep -Hirn multiRemote
node_modules/webdriverio/test.js:4:var client = webdriverio.multiremote({
node_modules/webdriverio/testaaaa.js:10:        matrix = webdriverio.multiremote({
test.js:3:    matrix = webdriverio.multiRemote({
```

furthermore the method name is inconsistent: multiremote < = > multiRemote

**Comment by christian-bromann** [comment]
As I mentioned in #423 this feature isn't released yet but you can checkout the master branch to play around with it. Sorry for the confusion.

**Comment by SerkanSipahi** [comment]
it is possible to use( on master branch ) multiRemote in combination with webdrivercss

```js
var webdriverio = require('webdriverio'),
    matrix = webdriverio.multiRemote({
       ...
       ...
       ...
    }).init();

var webdrivercss = require('webdrivercss').init(matrix);

...
...
...
...

```

**Comment by christian-bromann** [comment]
I haven't tested it yet but it should

**Comment by Skoks** [comment]
@christian-bromann  Any approximate date of implementation ?

**Comment by christian-bromann** [comment]
multiremote is implemented and tested on master. I am currently working on some additional features coming in v2.5.0 + docs. I am looking to push everything out on the 27th .. so please be a little bit more patient and stay tuned ;-)

**Comment by Skoks** [comment]
@christian-bromann Sounds awesome! Thanks a lot for your hard work :+1:

**Comment by EvanHahn** [comment]
I see `multiremote` examples but the `multiremote` method is undefined. I'd love this feature—will it be released soon? Is there anything I can do to help it along?

**Comment by christian-bromann** [comment]
@EvanHahn sorry that this isn't released yet. Didn't get as much time to work on it as expected. Feel free to use the current master version if you want to try it out. I am still not 100% happy with specific edge cases and I don't want to publish something that isn't ready yet.
