### ISSUE TITLE
wdio-sync getAlertText unloads synchronous commands?

### ISSUE THREAD

**Issue by Lusito** [webdriverio/webdriverio#4244]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.11.7
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.15.1
 - **NPM version:** 6.9.0
 - **Browser name and version:** chrome 75
 - **Platform name and version:** ubuntu 18.04
 - **Additional wdio packages used (if applicable):**

```
"@wdio/config": "^5.11.0",
"@wdio/cucumber-framework": "^5.11.7",
"@wdio/junit-reporter": "^5.11.7",
"@wdio/local-runner": "^5.11.7",
"@wdio/selenium-standalone-service": "^5.11.2",
"@wdio/spec-reporter": "^5.11.7",
"@wdio/sync": "^5.11.7",
"chromedriver": "^75.1.0",
"cucumber": "^5.1.0",
"wdio-chromedriver-service": "^5.0.2",
"wdio-cucumber-selected-steps": "file:../wdio-cucumber-selected-steps",
```

**Config of WebdriverIO**

```
    services: ['selenium-standalone'],
    framework: 'cucumber',
    sync: true,
```

**Describe the bug**
After using `getAlertText()` in a no-alert situation, `$(...).click`, etc. don't work anymore, since `$(...)` returns a promise.

**To Reproduce**

- open a page with no alertbox
- call `browser.getAlertText()`
- click on an element that exists. => boom, `$(...)click` is not a function.

https://github.com/Lusito/wdio-issues

**Expected behavior**
Even when the alert doesn't exist, it should not break the following `$(...)`.
Obviously, when I use `isAlertOpen()`, I can prevent the "wrong" call to `getAlertText()`, but I wouldn't expect this kind of behavior in the first place.

**Comment by christian-bromann** [comment]
Can you provide your test code?

**Comment by Lusito** [comment]
Here you go:
https://bitbucket.jambit.com/users/spfingsten/repos/wdio-issues/browse

The setup has been hacked together since I can't release my original code here right now.

**Comment by christian-bromann** [comment]
@Lusito can you just share a gist? I can't access that page.

**Comment by Lusito** [comment]
ah, damnit, the page is only accessible from inside the company lan.. gimme a second

**Comment by mgrybyk** [comment]
I'll fix it today

**Comment by christian-bromann** [comment]
Let's make sure to apply a smoke test for this to ensure it doesn't happen again.

**Comment by mgrybyk** [comment]
@Lusito this gonna be released soon in new version

**Comment by Lusito** [comment]
Thanks for the quick fix, I can confirm it works :)
