### ISSUE TITLE
dragAndDrop and moveTo don't seem to work on chrome headless

### ISSUE THREAD

**Issue by Lusito** [webdriverio/webdriverio#4246]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.11.7
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.15.1
 - **NPM version:** 6.9.0
 - **Browser name and version:** chrome 75
 - **Platform name and version:** ubuntu 18.04
 - **Additional wdio packages used (if applicable):**

```
"@wdio/config": "^5.11.0",
"@wdio/cucumber-framework": "^5.11.7",
"@wdio/junit-reporter": "^5.11.7",
"@wdio/local-runner": "^5.11.7",
"@wdio/selenium-standalone-service": "^5.11.2",
"@wdio/spec-reporter": "^5.11.7",
"@wdio/sync": "^5.11.7",
"chromedriver": "^75.1.0",
"cucumber": "^5.1.0",
"wdio-chromedriver-service": "^5.0.2",
"wdio-cucumber-selected-steps": "file:../wdio-cucumber-selected-steps",
```

**Config of WebdriverIO**

```
    services: ['selenium-standalone'],
    framework: 'cucumber',
    sync: true,
```

**Describe the bug**
When using chrome normally everything is fine, but in headless mode, dragAndDrop() and moveTo() fail.

dragAndDrop fails silently, moveTo says "move target out of bounds"

**To Reproduce**

- npm run test => works
- npm run test:ci => fails

https://github.com/Lusito/wdio-issues/tree/drag-and-drop

**Expected behavior**
Should work in both.

**Comment by erwinheitzman** [comment]
What is the issue? Are you receiving any errors? More info is much appreciated.

**Comment by Lusito** [comment]
Not sure what more information you expect. As said, the drag event doesn't happen. The moveTo call says "move target out of bounds". No other errors are printed.

The sample repository shows the issue. Checkout the repo, run `npm install`, `npm start` (for the server) and then `npm test` for the tests.

**Comment by ducle91** [comment]
There is an open ticket for draganddrop function here. https://github.com/webdriverio/webdriverio/issues/4134

**Comment by mgrybyk** [comment]
@Lusito this is not headless problem, it is failing starting from chromedriver 75.

In your config you use selenium without specifying version, so it is uses chromedriver 2.43 which was non w3c compliant.
In headless config you use chromedriver 75 which is w3c compliant, so this is a defect in chromedriver.

**Comment by mgrybyk** [comment]
@Lusito thanks a lot for providing with great reproducible example!

closing according to https://github.com/webdriverio/webdriverio/pull/4302

**Comment by Lusito** [comment]
@mgrybyk thanks for clarifying and providing a fix. Though your PR only covers dragAndDrop, not moveTo or is there a connection between the two?
Will try using a different chromedriver version on monday.

**Comment by mgrybyk** [comment]
@Lusito can you please help with reproducing moveTo issue?

**Comment by mgrybyk** [comment]
@Lusito fixed moveTo as well

**Comment by Johannes-B-stock** [comment]
It is still not working for me, running webdriverio with mocha on the latest versions and chromedriver on 85.0.1. It works fine in non-headless mode but when running in headless mode I get a "move target out of bounds" exception when calling moveTo().
I don't have any selenium config and I'm using the standard webdriverio config generated from wdio cli.

**Comment by christian-bromann** [comment]
> move target out of bounds

I assume the headless browser is rendering in a smaller viewport and you are trying to drag and drop it out of the viewport. I recommend to set a specific viewport size when starting the session.
