### ISSUE TITLE
WDIO hooks don't populate Cucumber's World

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#4248]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.11.7
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12
 - **NPM version:** 6.9.0

**Describe the bug**
Cucumber-specific hooks of webdriverIO cannot populate the World of Cucumber.
~~Additionally, Cucumber hooks resolve promises no matter what.~~

**Expected behavior**

Example: In the _beforeSenario_ (wdio hook for Cucumber) or in the _Before_ hook (Cucumber) we might want to start a request for an account creation. 

The hook should not wait for the promise to resolve.
A user can simply call `browser.call` if he wishes to wait for a promise to resolve.

By not waiting for the promise to resolve we can begin the test as quickly as possible, opening pages, performing actions, etc. and when the user really needs the account information, he can await for the account creation promise to be resolved. It his likely that by the time he calls await, the promise is long resolved since we've been performing actions in the meantime.

This is what I'm experiencing right now.

With the wdio hook _beforeScenario_:

```js
  beforeScenario: async function(uri, feature, scenario) {
    if (scenario.tags.find(tag => tag.name === "@newAccount")) {
      this.user = scenario.user = feature.user = createAccount(); // Start a request that creates an account
      // This hook will not resolve the promise before continuing, that's cool
      // ... but this.user, scenario.user or feature.user will not populate Cucumber's world
      // ... therefore the eventually created user will not be available in tests/steps
    }
  }
```

~~With the Cucumber hook _Before_~~
**Edit:** 
_Can no longer reproduce this behavior (5.11.10).
Cucumber hooks seem to be functioning well and they don't resolve promises unless you return them._

```js
  const { Before } = require("cucumber");

  Before("@newAccount", async function() {
    this.user = createAccount(); // Start a request that creates an account
    // This hook WILL resolve the promise before continuing, not cool!
    // This means I can't start opening the page, performing actions, etc until the new account promise is resolved
    // On the plus side, this.user is available for Cucumber steps, yay
});
```

**Comment by jbblanchet** [comment]
Your second example doesn't seem to be right. I've tried reproducing it, and promise resolution seems to be fine.

This is my code:
```javascript
Before(async () => {
  console.log(this)
  this.foo = delay(1000).then(() => { console.log('Promise 1 resolved') })
})

Before(async () => {
  this.bar = delay(500).then(() => { console.log('Promise 2 resolved') })
  return this.titi
})

Then('it works', () => {
  console.log('Step working')
  console.log(this.foo)
  console.log(this.bar)
})
```

will give the following output:
```
[0-0] Promise 2 resolved
[0-0] Step working
[0-0] Promise { <pending> }
[0-0] Promise { undefined }
```

Promise 2 is resolved because it's returned from the second before as an async function. The first one is not, even if the function is declared async, since it's not returned. I believe this is the right behavior.

**Comment by jbblanchet** [comment]
By the way, I believe this should also be the behavior of the webdriver hooks:

1. Wait for promise to resolve if (and only if) it's returned.
2. Have the right `this`, or at least get the world as a param, as currently changing this would be breaking.

I was looking into fixing 1. yesterday, but I believe it would require a full re-write of the current runner being an EventEmitter. I'll try looking at it later today. Any opinion about 2.? Would a breaking change of `this` be ok?

**Comment by nextlevelbeard** [comment]
Correct me if I'm wrong, I'm not an expert in JavaScript, but I believe the only reason your example is working is due to the hooks and the step definitions being declared on the same block level and sharing the same scope.

Your example is using arrow functions for both your _Then_ and your _Before_ hooks. The scope for `this` is not the World. You can test by separating the hooks and the step definition into separate files or by trying to reference `this.foo` and `this.bar` in another step definition that's not using arrow functions:
```js
Before(async () => {
  this.foo = delay(1000).then(() => { console.log('Promise 1 resolved') })
})

Before(async () => {
  this.bar = delay(500).then(() => { console.log('Promise 2 resolved') })
  return this.bar
})

Then('it works', () => {
  console.log('Step working')
  console.log(this.foo)
  console.log(this.bar)
})

Then('it does not work', function() {
  console.log(this.foo) // this being World, foo is undefined
  console.log(this.bar) // bar is undefined
// isn't a bug, hooks are using arrow functions
})
```

Therefore to reproduce my second example that uses the Cucumber hooks you should do:
`hooks.js`
```js
const { Before } = require("cucumber");

  Before(async function() {
    this.user = delay(30000).then(() => { 
      console.log('30 seconds have passed!');
      return 'cooluser';
    })
    // This hook WILL resolve the promise before continuing, not cool!
    // This means I can't start opening the page, performing actions, etc until the promise is resolved
    // On the plus side, this.user is available for Cucumber steps, yay
});
```
`steps.js`
```js
  Given("it resolves the promise", function() {
    console.log(this.user) //cooluser, 30 seconds have passed
    /*
     Bunch of actions we could already be performing if the promise wasn't forcefully being resolved
    */
});
```

**Comment by jbblanchet** [comment]
@nextlevelbeard You are perfectly right, but this updated code:

```javascript


Before(async function () {
  this.foo = delay(1000).then(() => { console.log('Promise 1 resolved') })
})

Before(async function () {
  this.bar = delay(500).then(() => { console.log('Promise 2 resolved') })
  return this.bar
})

Then('it works', async function () {
  console.log('Step working')
  console.log(this)
})
```

and its output:
```
[0-0] Promise 2 resolved
[0-0] Step working
[0-0] World {
  attach: [Function: bound create],
  parameters: undefined,
  foo: Promise { <pending> },
  bar: Promise { undefined } }
```

should demonstrate that the behavior is still correct when attached to the World object.

**Comment by jbblanchet** [comment]
This is running by using the following `wdio config`:

```
? Where should your tests be launched?  local - https://www.npmjs.com/package/@wdio/local-runner
? Where is your automation backend located? On my local machine
? Which framework do you want to use?  cucumber - https://www.npmjs.com/package/@wdio/cucumber-frame
work
? Do you want to run WebdriverIO commands synchronous or asynchronous? sync
? Where are your feature files located? ./features/**/*.feature
? Where are your step definitions located? ./features/step-definitions
? Which reporter do you want to use? (Press <space> to select, <a> to toggle all, <i> to invert sele
ction) spec - https://www.npmjs.com/package/@wdio/spec-reporter
? Do you want to add a service to your test setup? (Press <space> to select, <a> to toggle all, <i> 
to invert selection) chromedriver - https://www.npmjs.com/package/wdio-chromedriver-service
? What is the base url? http://localhost
```

These are the versions of wdio I'm using:
```
{
  "dependencies": {
    "@wdio/cli": "^5.11.10"
  },
  "devDependencies": {
    "@wdio/cucumber-framework": "^5.11.11",
    "@wdio/local-runner": "^5.11.11",
    "@wdio/spec-reporter": "^5.11.7",
    "@wdio/sync": "^5.11.11",
    "chromedriver": "^75.1.0",
    "wdio-chromedriver-service": "^5.0.2"
  }
}
```

I've tried with both `sync` and `async` setup, but it seems to have no influence on the config file, only on the inclusion of `@wdio/sync` in the package.json, but even with async it's included as a dependency of `@wdio/cucumber-framework`.

I've also tried to make the Then step async or not, didn't change anything.

I can create a repo with my setup if you want.

**Comment by nextlevelbeard** [comment]
@jbblanchet I've just retested with my config and you are right: Cucumber hooks have no problem. 

`async function` hooks do not resolve Promises and `this` is scoped to World.

I've since updated my webdriverIO dependencies 5.11.7 → 5.11.10.
Either updating has fixed the problem for me or I had some logic I wasn't seeing.

Thanks for looking into this with me though, I'll update the issue.

That said, I think the first example/issue still stands: webdriverio-specfic hooks (_beforeScenario_, _beforeTest_, etc) don't populate the World.

**Comment by jbblanchet** [comment]
@nextlevelbeard My pleasure. Just wanted to make sure the behavior of the Cucumber hooks wasn't changed :smile: 

Personally, I'd deprecate or at least discourage usage of the config hooks with Cucumber:
- The critical ones (after, before, afterScenario, beforeScenario) are redundant with stuff already supported by Cucumber.
- The hooks themselves are confusing, since for example `after` maps to `AfterAll`, not `After`.
- They cannot be reliably hooked in to support async, since they're tied to fire-and-forget events in the Cucumber framework.
- They are not handled by Cucumber, so they don't support World.

Is there a strong use case to support those?

**Comment by mgrybyk** [comment]
There were sync related fixed, @nextlevelbeard. I recomend to update to 5.11.11

**Comment by mgrybyk** [comment]
I'll have to ask you to try again once https://github.com/webdriverio/webdriverio/pull/4288 is released,  hopefully somewhere next week.

Please also note that hooks signature will be changed

**Comment by mgrybyk** [comment]
Currently all WDIO hooks have config as context, not Cucumber World.
I don't know if we should change it for WDIO' Cucumber hooks like beforeStep, etc.

**Comment by mgrybyk** [comment]
before/after Step/Hook will have Cucumber World as 5th argument, see related PR

**Comment by osmolyar** [comment]
@mgrybyk  question, is this only for beforeStep/afterStep or for beforeScenario/afterScenario also?  Because beforeScenario is really where it makes sense to change/initialize cucumber world state, since its intention is to share state between steps (but not carry over between scenarios).

**Comment by erwinheitzman** [comment]
@osmolyar if you had checked the change you'd have seen that it indeed only for those hooks as he described: https://github.com/webdriverio/webdriverio/pull/4545/files

**Comment by osmolyar** [comment]
@erwinheitzman , yes based on experimenting with the hooks it appeared that before/afterScenario are not affected - just entered issue https://github.com/webdriverio/webdriverio/issues/5394 to extend to before/afterScenario hooks.
