### ISSUE TITLE
Truncate screen record command result log

### ISSUE THREAD

**Issue by mooyoul** [webdriverio/webdriverio#4251]
**Is your feature request related to a problem? Please describe.**
A base64-encoded video data of screen record is posted into log which is not helpful at all, bloats log output

**Describe the solution you'd like**
Truncate `result.value` in case command name includes record
```js
                log.info('RESULT',
                    /screenshot|record/i.test(command) && typeof result.value === 'string' ?
                        `${result.value.substr(0, 64)}...` : result.value)
```

**Describe alternatives you've considered**
At this moment, Just use `warn` log level to rescue my terminal

**Additional context**
#3362 is similar issue :)

**Comment by christian-bromann** [comment]
@mooyoul mind making a PR?

**Comment by mooyoul** [comment]
@christian-bromann Sure. I just opened a PR #4252 :)
