### ISSUE TITLE
When running scripts in Jenkins for headless Firefox, using wdio testrunner, I am receiving the error "Type Error in Before all hook...."  $(...).click is not a function.

### ISSUE THREAD

**Issue by gayathri12aug** [webdriverio/webdriverio#4257]
I am using webdriverio-mocha-chai framework and running the test scripts through Jenkins, in firefox headless mode. The scripts run fine in local machine (Windows 10, 64 bit) 3 out of 5 test cases passing ( I have 'cannot scroll element into view" error for 2 test cases involving file upload)
I am receiving the following error when I run the scripts in Jenkins:
**Issue 1:**
"[0-0] **TypeError** in "Test LDhap form submission "before all" hook for "should display LDhap results from sample file with RS and genomic coordinate queries""
$(...).click is not a function"
**Issue 2:**
It always mentions "...is not a function"  when it reaches <<locator>>.click()  or any function.

I have the driver binaries installed through npm install in the package.json file. This is triggered by the shell script in Jenkins. Note: I am using webdriverio v5

**Environment (please complete the following information):**
 - **WebdriverIO version:**  "^5.10.9"
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:**  sync
 - **Node.js version:** v12.1.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Firefox 60.8.0
 - **Platform name and version:**  Linux 64 bit remote slave server in Jenkins.
 - **Additional wdio packages used (if applicable):** 

**---my wdio config file has these---**
"dependencies": {
    "chromedriver": "^75.1.0",
    "fibers": "^4.0.1",
    "geckodriver": "^1.16.2",
    "nodejs": "0.0.0",
    "selenium-webdriver": "^4.0.0-alpha.4",
    "webdriverio": 
  },
  "devDependencies": {
    "@babel/cli": "^7.5.0",
    "@babel/core": "^7.5.0",
    "@babel/preset-env": "^7.5.3",
    "@babel/register": "^7.4.4",
    "@wdio/cli": "^5.10.9",
    "@wdio/junit-reporter": "^5.11.0",
    "@wdio/local-runner": "^5.10.9",
    "@wdio/mocha-framework": "^5.10.8",
    "@wdio/selenium-standalone-service": "^5.9.3",
    "@wdio/spec-reporter": "^5.9.3",
    "@wdio/sync": "^5.10.8",
    "chai": "^4.2.0",
    "node-gyp": "^5.0.3"
  }

Please let me know where I am going wrong.

**Comment by gayathri12aug** [comment]
capabilities: [{
         browserName: 'firefox', 
         "moz:firefoxOptions": {
         args: ['--headless', '--disable-gpu', '--window-size=1280,800']
         }
  }],

I am using these capabilities in my config file.  
{Note: In my original post I have posted the dependencies as present in package.json file..  Sorry, I have wrongly mentioned it as wdio.config file)

**Comment by mgrybyk** [comment]
@gayathri12aug reproducible example for each issue would be helpful!

**Comment by gayathri12aug** [comment]
I will add one today.. Thank you

**Comment by mgrybyk** [comment]
If you have steps to reproduce, fill free to re-open @gayathri12aug
