### ISSUE TITLE
browser.addCommand is not sync anymore

### ISSUE THREAD

**Issue by wswebcreation** [webdriverio/webdriverio#4259]
**Environment (please complete the following information):**
 - **WebdriverIO version:** `5.11.10`
 - **Mode:** testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** `10.15.2`
 - **NPM version:** `6.9.0`
 - **Browser name and version:** -
 - **Platform name and version:** OSX Mojave 
 - **Additional wdio packages used (if applicable):** See image below

**Config of WebdriverIO**
Default config

**Describe the bug**
In version `5.9.2` all `browser.addCommand` were sync. My module `wdio-image-comparison-service`, which uses `browser.addCommand` a lot, was working perfectly. Why . I update to all the latest versions, see image below, will not log a result anymore but `browser.saveScreen(examplePage) =  Promise { <pending> }`

**To Reproduce**
Create a `browser.addCommand`. 

> I'll add a sample project this weekend that shows the bug

**Expected behavior**
The behaviour should be sync

**Log**
![image](https://user-images.githubusercontent.com/11979740/61990504-4563a880-b042-11e9-8638-ddf8d3214918.png)

**Additional context**
@klamping also mentioned that `browser.call` is not sync anymore

**Comment by mgrybyk** [comment]
@klamping @wswebcreation please add reproducible example

**Comment by mgrybyk** [comment]
@wswebcreation here is what I have tried 
```
browser.url("http://adam.goucher.ca/parkcalc/")

console.log($('td').customElementCommand())

console.log(browser.customBrowserCommand({ longitude: 0, latitude: 0 }))

console.log(browser.call(() => new Promise(resolve => {
            browser.pause(500)
            console.log('after pause')
            setTimeout(() => resolve(555), 500)
})))

console.log(browser.saveScreen('examplePaged'))
```

Works just perfect!

**Comment by mgrybyk** [comment]
Make sure there are no older versions of webdriverio saved in your `package-lock.json`

**Comment by mgrybyk** [comment]
@wswebcreation please also see https://github.com/wswebcreation/wdio-image-comparison-service/issues/10

**Comment by mgrybyk** [comment]
```
describe("main suite", () => {
    beforeEach(async () => {
        await browser.url("http://adam.goucher.ca/parkcalc/")
        await browser.pause(500)
    })
    it("some test", () => {
        // it doesn't matter what goes here.
        // First command here returns a Promise, in this case $('body')
        // it can be also anything else, custom command, browser.call or whatever 
        $('body').getText()
    })
})
```

**Comment by WillBrock** [comment]
I noticed some odd behavior with the latest version as well. I haven't had a chance to look into it though. An async issue would make sense. I won't be able to look into it until tomorrow.

**Comment by wswebcreation** [comment]
🤦‍♂ I thought I checked everything, but you were right @mgrybyk , it was the async part that was breaking. I'm going to close it. Sorry and thanks for pointing out to that part

**Comment by mgrybyk** [comment]
If you guys still have any issues, let me know

**Comment by wswebcreation** [comment]
@mgrybyk 

I was my own fault, and I think a dependency upgrade in the new version triggered the issue. Please add a label to this issue like _shame on you Wim_. Man that was stupid

**Comment by mgrybyk** [comment]
@wswebcreation actually not stupid, it worked before my recent changes. I mean it was possible to mix async await and @wdio/sync

**Comment by mgrybyk** [comment]
@WillBrock have you been able to take a look?

**Comment by WillBrock** [comment]
@mgrybyk I think our problem was with the issue in #4269

**Comment by mgrybyk** [comment]
Hope so, let me know if you are seeing something else
