### ISSUE TITLE
What is the difference between waitFor and waitForExist?

### ISSUE THREAD

**Issue by notnarb** [webdriverio/webdriverio#426]
http://webdriver.io/api/utility/waitForExist.html

> Wait for an element (selected by css selector) for the provided amount of milliseconds to be existent within DOM. If multiple elements get queryied by given selector, it returns true (or false if reverse flag is set) if at least one element is visible.

http://webdriver.io/api/utility/waitFor.html

> Wait for an object in the DOM (selected by given selector) for the provided amount of milliseconds. The callback is called with false if the object isnt found.

The 'if at least one element is visible' seems to be a copy/paste from waitForVisible so I presume they are intended to do the same thing.  Oddly the implementation for the two seems completely different.

Are they redundant commands or should the documentation maybe be a little clearer on what specific roles they are meant to fill?

**Comment by christian-bromann** [comment]
`waitFor` is the native Selenium `waitFor` command and all the other waitFors are a litte bit more sophisticated as they using executeAsync and other commands to wait on elements. But you're right this should get mentioned in the docs.

**Comment by notnarb** [comment]
I re-looked at the source and it seems the waitFor command uses the 'element' command and the 'waitForExist'  uses the elements command.  The waitFor command resolves with null and the waitForExist resolves with true.

It also looks like the waitFor command uses the depreciated 'implicitWait' webdriver.io command which applies the timeoutsImplicitWait command which calls the implicit_wait selenium command

**Comment by christian-bromann** [comment]
Will get tackled by #524

**Comment by christian-bromann** [comment]
Ok just looked into the code and apparently `waitFor` is just a simple version of `waitForExists`. Therefor I remove the `waitFor` command
