### ISSUE TITLE
chromeOptions stopped working after upgrade

### ISSUE THREAD

**Issue by d668** [webdriverio/webdriverio#4262]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 4.14.4
 - **Mode:** Standalone 
 - **Node.js version:** v8.11.1
 - **NPM version:** 5.6.0
 - **Browser name and version:** Chrome 75
 - **Platform name and version:** Ubuntu 18.04.1 LTS

**Describe the bug**
After upgrade to Chrome 75 the code stopped working 

**To Reproduce**
`java -jar -Dwebdriver.chrome.driver=.selenium/chromedriver .selenium/selenium-server-standalone-3.141.59.jar`
and
https://gist.github.com/d668/0b1e65317cda7727a3984caf8796ee06

**Expected behavior**
Browser should start and go to URL

**Log**
https://gist.github.com/d668/cd3e7fe6441ee6148e66e1c8475fd3cc

**Comment by christian-bromann** [comment]
> * **WebdriverIO version:** 4.14.4

This is fixed in v5. Please either update or provide a PR with a fix at https://github.com/webdriverio-boneyard/v4. Thanks!

**Comment by d668** [comment]
is it possible to use v5 with selenium-server-standalone-3.0.1.jar? I didn't find any examples

**Comment by christian-bromann** [comment]
> selenium-server-standalone-3.0.1.jar

This is a super old version if the selenium jar

> I didn't find any examples

**Comment by d668** [comment]
OK the latest would be selenium-server-standalone-3.141.59.
I can't follow getting started because it is a very old and big project, I need to migrate it
