### ISSUE TITLE
CucumberJS - Quality of life

### ISSUE THREAD

**Issue by jbblanchet** [webdriverio/webdriverio#4263]
Hi!

First of all, thanks for the hard work.

I'm currently migrating a project from Chimp (which used webdriver.io under the hood) to using webdriver.io directly We're using CucumberJs as our framework with Chai expects.

While I prefer this new, simpler stack to the old chimp one, it broke a few of our workflows.

1. When using the --watch option, all features start their own selenium session. This is an issue, because the --watch option keeps the browser open. Thus, 20 feature files equals 20 browsers staying open. This is especially a problem because we're using `@watch` tags to only run a subset of test when we use watch, mainly in the context of actually building or debugging a test, so 20 open browsers doing nothing make finding the right one harder, in addition to taking a lot of RAM.

2. When steps are undefined, we used to have some code snippet listed in the terminal output. This is not a deal breaker for us, but it was pretty nice UX.

3. reporter runs all tests, then dumps the results in the terminal at the end. I'd prefer to have steps listed as they run, which is especially nice when used with the watch pattern detailed in (1) to know where you are currently in the test.

4. pause on fail: this wasn't actually a feature in chimp, but the ability to pause the execution of the tests on failure when in watch mode would be very helpful. That way I can look at the page currently in the browser to try and find the issue.

Some of them might not be possible in the current architecture. I'm open to contributing for some of these if you think they are worthwhile features, but I'd like to get some feedback first from the community.

Thanks.

**Comment by mgrybyk** [comment]
Hello @jbblanchet,

1. you may reduce `maxInstances` to whatever value needed. 
2. Can `ignoreUndefinedDefinitions` help you? See cucumberOpts here https://webdriver.io/docs/configurationfile.html
3. this can be changed, please submit separate feature request for this one!
4. Can `afterCommand` help you in this case? You may put breakpoint if some command fails. Sorry to say `afterTest` hook is not current working as expected, so you can't put breakpoint there.

I hope to clarify at least something, cheers!

**Comment by jbblanchet** [comment]
@mgrybyk Thanks for the feedback.

1. I've created a simple demo of the problem in https://github.com/jbblanchet/2-browsers. If you run it with `yarn wdio ./wdio.conf.js --watch`, you will see that 2 chrome browsers are open, even if my max instance is 1. It opens one, runs the test in the first feature, keeps it open because of watch mode, opens a second one, runs the second feature, keeps it open.

2. I know about this option. I'm talking about outputting to the terminal something like
```
Step "Then it works" is not defined.
Please add the following code to your step definitions:
Then("it works", () => {
  return 'pending'
})
```

It is especially useful for step definition with parameters.

3. Will do.

4. Good idea. Thanks.

**Comment by mgrybyk** [comment]
1. Please rise an issue 
2. Please submit a feature request

Please note that we are working on some fixes for hooks, you might be interested as well https://github.com/webdriverio/webdriverio/pull/4288

Closing this one for now in advance to issues you might want to rise.

Thank you
