### ISSUE TITLE
Calling $ or $$ on an element while running in synchronous mode returns a promise.

### ISSUE THREAD

**Issue by nicholasbaileyrally** [webdriverio/webdriverio#4264]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.11.8
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** synch
 - **Node.js version:** 10.15.3
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome
 - **Platform name and version:** OSX
 - **Additional wdio packages used (if applicable):** @wdio/selenium-standalone service, @wdio/jasmine-framework

**Config of WebdriverIO**
Working on getting this, we have an abstraction layer around our config that takes a bit to work through

**Describe the bug**
We have a test suite running in synch mode.

We have certain 'component' wrappers that take a root element returned from a $ or $$ call and wrap it, providing extra functionality. Think of them a stateful page objects. A simple example might look like this

```
class SearchResultComponent {
    constructor(rootElement) {
         this.rootElement = rootElement;
    }

    goToResult() {
         this.rootElement.$('.result-link').click();
    }
}
```

We might return these from a page object like this

```
get searchResults() {
   return $$('.search-result-container').map(x => new SearchResultComponent(x));
}
```
When we try to invoke goToResult, we get a 'click is not a function' error, which inspection shows is because 
```
this.rootElement.$('.result-link);
```
is a promise, rather than an element.

If we invoke the global $ function in our SearchResultComponent, we get an element rather than a promise, but then loose all the value of being able to drill down on the rootElement.

**To Reproduce**
Working on getting a minimum viable repository example

**Expected behavior**
When running in synch mode, I'd expect all command on elements to be synchronous 'all the way down' regardless of context.

**Comment by mgrybyk** [comment]
@nicholasbaileyrally please update to the latest versions of webdriverio and @wdio/sync
