### ISSUE TITLE
switchToFrame doesn't work in mobile chrome

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4265]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.11.10
 - **Appium version:** 1.14.0
 - **Chrome version:** 75
 - **Chromedriver version:** 75

**Config of WebdriverIO**
Android, chrome

**Describe the bug**
`browser.swithToFrame('iframe')` returns `ELEMENT is missing in request`

**To Reproduce**
`browser.swithToFrame('iframe')`

**Expected behavior**
should be possible to switch to iframe

**Suggested solution**
Wrap protocol's `swithToFrame` to send 
```
{
    [_constants.ELEMENT_KEY]: this.elementId,
    ELEMENT: this.elementId
}
```
instead of WebdriverIO element. Tested solution locally, works fine both for mobile and desktop.

**Comment by mgrybyk** [comment]
@christian-bromann if you are fine with suggested approach, I can do it.

Alternatively I can suggest to change `command.js` to verify every argument.
If `instanceOf argument Element` then changed it to 
```
{
    [_constants.ELEMENT_KEY]: this.elementId,
    ELEMENT: this.elementId
}
```

It should be more flexible and we would not need to wrap more and more commands

**Comment by christian-bromann** [comment]
> returns `ELEMENT is missing in request`

Something is off here. It seems that WebdriverIO thinks it is running w3c but Appium don't supports it. Can you check the environment flags? Chances are that this is a bug in Appium.

**Comment by mgrybyk** [comment]
Issue has been resolved on Appium side, all credits to @mykola-mokhnach
