### ISSUE TITLE
Unable to run 'setvalue' in firefox and safari

### ISSUE THREAD

**Issue by ranjaniSourceDay** [webdriverio/webdriverio#4267]
Here is the link to my repo

https://gitlab.com/ranjani.amirth/webdriverio-crossbrowser

Run `npm run test`

This is a test just to open https://google.com and enter a value in the search box. You will see the test passes in chrome, but fails in firefox and safari

Browserversions i tested this

chrome: Version 75.0.3770.142 
firefox: 68.0.1 (64-bit)
safari:  12.1.1 (14607.2.6.1.1)

This is the error thrown in firefox and safari: `java.lang.NullPointerException`

**Comment by mgrybyk** [comment]
Please remove conflicting packages like selenium standalone vs @wdio/selenium standalone, wdio, etc.
You can use getting started guide for it.

**Comment by ranjaniSourceDay** [comment]
I tried starting the project from scratch again and this is the package.json

```"devDependencies": {
    "@types/mocha": "^5.2.7",
    "@wdio/allure-reporter": "^5.11.7",
    "@wdio/cli": "^5.11.12",
    "@wdio/concise-reporter": "^5.11.7",
    "@wdio/dot-reporter": "^5.11.7",
    "@wdio/junit-reporter": "^5.11.7",
    "@wdio/local-runner": "^5.11.12",
    "@wdio/mocha-framework": "^5.11.0",
    "@wdio/selenium-standalone-service": "^5.11.2",
    "@wdio/spec-reporter": "^5.11.7",
    "@wdio/sync": "^5.11.11",
    "chai": "^4.2.0",
    "dotenv": "^8.0.0",
    "ts-node": "^8.3.0",
    "tsconfig-paths": "^3.8.0",
    "typescript": "^3.5.3",
    "wdio-image-comparison-service": "^1.5.0",
    "wdio-video-reporter": "^1.4.4"
  },
  "dependencies": {}```

**Comment by ranjaniSourceDay** [comment]
does the jdk version matter?

**Comment by mgrybyk** [comment]
Might be! I'm on latest java8
