### ISSUE TITLE
How to handle datepicker in android ..I want to select specific year and Iam facing scrolling issue ..not scrolling I have tried many function still not working plzzz help me

### ISSUE THREAD

**Issue by bhavyagowda144** [webdriverio/webdriverio#4268]
https://discuss.appium.io/uploads/default/original/2X/6/658f7a6115e14696a093f5ba109e24f47be865f2.JPG

Trying to scroll on a calendar to select a particular year
  

 - **WebdriverIO version:** [e.g. 4.13.2]
 -appium version :1.13.0
 - **Node.js version:** [e.g. 10.16]
 - **NPM version:** [e.g.6.0]
 -
 -

.

**Comment by mgrybyk** [comment]
Please use gitter for such questions.

If you are sure this is an issue please provide with details steps to reproduce and fill issue details properly
