### ISSUE TITLE
elements fetched with $$ lose their context

### ISSUE THREAD

**Issue by diachedelic** [webdriverio/webdriverio#4270]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.11.10
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v11.15.0
 - **NPM version:** yarn 1.15.2
 - **Browser name and version:** 75.0.3770.142 (Official Build) (64-bit)
 - **Platform name and version:** MacOS 10.14.5
 - **Additional wdio packages used (if applicable):** 
```
@wdio/cli
@wdio/local-runner
@wdio/mocha-framework
@wdio/spec-reporter
@wdio/sync
wdio-chromedriver-service
```

**Config of WebdriverIO**
See repro

**Describe the bug**
After calling commands on non-existant children of the nth Element returned from
`$$`, the Element "loses it's place" in the array, and reverts to the first
item.

**To Reproduce**
```
git clone git@github.com:diachedelic/wdio-repros.git &&
  cd wdio-repros &&
  git checkout elements-context &&
  yarn &&
  yarn test
```

**Expected behavior**
Elements fetched with `$$` retain their ordering context no matter what.

**Log**
https://gist.github.com/diachedelic/303a3eddfdee4aa9dce9d2f491061563

** Additional context **
I was only able to reproduce using `wdio-chromedriver-service`, rather than Selenium, so it may be a bug in that package but I don't know how to tell.

**Comment by mgrybyk** [comment]
@diachedelic thank you for providing with detailed steps!

Reproduced it locally with the following
```
browser.url("http://adam.goucher.ca/parkcalc/")

const el = browser.$('body')

const results: any[] = []
el.$$('input').forEach(el => {
    const r1 = {
        // @ts-ignore
        index: el.index,
        id: el.elementId,
    }

    el.$('.i-do-not-exist').isExisting()

    const r2 = {
        // @ts-ignore
        index: el.index,
        id: el.elementId, // this one is always the same
    }

    results.push(r1, r2, '----')
})
console.log(results)
```

**Comment by mgrybyk** [comment]
Let's proceed conversation in PR.

**Comment by diachedelic** [comment]
@mgrybyk oh sorry, I failed to mention that I had `index.html` served at localhost:3456, glad you figured it out!
