### ISSUE TITLE
buttonDown & buttonUp not workinng with docker service

### ISSUE THREAD

**Issue by sabarishnarain** [webdriverio/webdriverio#4271]
- **WebdriverIO version:** [5.11.2]
- **Typescript:** [3.5.3]
 - **Mode:** [ WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync/]
 - **Node.js version:** [8]
 - **NPM version:** [e.g. 6.5]
 - **Browser name and version:** [e.g. Chrome 75]
 - **Platform name and version:** [e.g. Windows 10/Mac os]
 - **Additional wdio packages used (if applicable):** [wdio-docker-service@2.1.2, @wdio/cli@5.11.2]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
`browser.buttonDown() is not a function` when running tests in docker service. This works in standalone mode

**To Reproduce**

**Expected behavior**
I assume this should work the same as when running in standalone mode.

**Comment by christian-bromann** [comment]
> This works in standalone mode

Whatever WebDriver endpoint you are accessing in the Docker container it seem to not speak old JSONWire but runs the latest WebDriver protocol where this command doesn't exist anymore.
