### ISSUE TITLE
iOS Appium on BrowserStack Falls Back to MSONWP instead of Using Expected W3C Protocol

### ISSUE THREAD

**Issue by pablopaul** [webdriverio/webdriverio#4273]
**Environment:**

- **WebdriverIO version:** 5.7.12
- **Mode:** WDIO Testrunner
- **If WDIO Testrunner, running sync/async:** async
- **Node.js version:** v11.13.0
  **NPM version:** 6.10.1
- **Platform name and version:** iOS 11.2
- **Additional wdio packages used (if applicable):** appium service

**Config of WebdriverIO**

Local capabilities set through webdriverio which are working

```
config.capabilities = [
    {
        // The defaults you need to have in your config
        browserName: 'safari',
        platformName: 'iOS',
        maxInstances: 1,
        // For W3C the appium capabilities need to have an extension prefix
        // This is `appium:` for all Appium Capabilities which can be found here
        // http://appium.io/docs/en/writing-running-appium/caps/
        'appium:deviceName': 'iPhone X',
        'appium:platformVersion': '12.0',
        'appium:orientation': 'PORTRAIT',
        // `automationName` will be mandatory, see
        // https://github.com/appium/appium/releases/tag/v1.13.0
        'appium:automationName': 'XCUITest',
        'appium:newCommandTimeout': 240,
    },
];
```

The capabilities for BrowserStack are looking like this:

```
config.capabilities = [
    {   
        platformName: "iOS",
        deviceName: "iPhone X",
        browserName: "safari",
        'appium:automationName': 'XCUITest',
        'bstack:options' : {
            'deviceName' : 'iPhone X',
            'realMobile' : 'true',
        },
    },
];
```

**Describe the bug**

I try to run a test which sets timeouts (`/timeouts` endpoint) on iOS on BrowserStack through Appium 1.9.1. 
I am using WebdriverIO as client library.

The test looks like:

```
describe('timeouts', () => {
    it('should be configurable', () => {
        browser.setTimeouts(1000, 2000, 3000);
    });
});
```

The test fails with `Error: Parameters were incorrect. We wanted {"required":["type","ms"]} and you sent ["implicit","pageLoad","script"]`.

This is because on BrowserStack Appium detects MSONWP protocol, but the timeout format is only compatible with W3C protocol.

**To Reproduce**

Execute the test above against a real iOS device on BrowserStack.

**Expected behavior**

No error appears when using `setTimeouts`.

**Log**

Link to WebdriverIO log: https://gist.github.com/pablopaul/08f10125d67fccc54e612834bc51ef73

Link to Appium log: https://gist.github.com/pablopaul/6c2141d5023e65532ae838da84f15c10

**Comment by wswebcreation** [comment]
@pablopaul 

Is there a reason for using Appium `1.9.1`? I know there is a fix with W3C and timeouts in `1.10.0`, I don't know if that is related to this issue

**Comment by christian-bromann** [comment]
It is. WebdriverIO sends a w3c command as it suppose to do with Appium given they support w3c within the latest versions. Please reach out to BS and ask how to use the latest version of Appium.

**Comment by pablopaul** [comment]
@wswebcreation for the record I added the debug log to the issue (https://gist.github.com/pablopaul/e08b68aaf6d4e622936eabc338e7bf0c).

Currently the latest Appium version available on BrowserStack is `v1.9.1`.

@christian-bromann BS want to provide newer Appium version, but no ETA.

**Comment by wswebcreation** [comment]
@pablopaul 

It's a pity that BS isn't supporting the latest versions, Appium is already on version `1.14.0`, meaning they are back behind a lot

**Comment by pablopaul** [comment]
@wswebcreation 

Yes, Appium `1.9.1` is almost a year old.

I contacted sales again.

**Comment by pablopaul** [comment]
@wswebcreation 

Anyway, locally I ran successfully `setTimeouts()` inside an iOS simulator and Appium `1.9.1` with WebdriverIO, meaning I could not even reproduce the error locally with the same Appium Version.

Maybe its the simulator vs real device, what do you think?

**Comment by wswebcreation** [comment]
@pablopaul 

I don't think it's related, I think it's more a BS thing, but maybe that's also because I'm a SL guy 😉

**Comment by amit-punjabi** [comment]
On Android execution, I am not facing this. However, on iOS this error is displayed. 

Review the attached Appium logs - [#iOS](https://gist.github.com/amit-punjabi/fb2ca73c5e0e41693f79cfa7d84e8c44), [#Android](https://gist.github.com/amit-punjabi/94d70fa5093646ad2e22e7f97b625d34)

seems like Safari cares about exact parameter string and Chrome does not. Check [this](https://github.com/theintern/leadfoot/issues/166#issuecomment-460245781)

**Comment by pablopaul** [comment]
@christian-bromann the issue is still existing, also with `appium 1.14.0` which is now available on BrowserStack. What can I contribute / prepare to get this fixed?

**Comment by christian-bromann** [comment]
The error is either in Appium in their iOS driver or still on BS
