### ISSUE TITLE
PhantomJs support

### ISSUE THREAD

**Issue by DustinRoundy** [webdriverio/webdriverio#4277]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [ ] Missing documentation
- [x] Other

**Description of the improvement / report**
The WebDriverIO documentation says PhantomJS is supported. @mgrybyk has stated that WebDriverIO does not support PhantomJS.

Pages that need to be updated: 
https://webdriver.io/docs/selenium-standalone-service.html#installation
https://webdriver.io/docs/wdio-docker-service.html#configuration

**Comment by christian-bromann** [comment]
PhantomJS is supported but you need to have it installed on your machine. That said, I would not recommend to use PhantomJS these days and rather use Chrome headless.

**Comment by mgrybyk** [comment]
Can we remove it from docs as far as it is not recommended so that newcomers won't try using it without a reason? 
@christian-bromann

**Comment by christian-bromann** [comment]
> Can we remove it from docs as far as it is not recommended so that newcomers won't try using it without a reason?

Absolutely
