### ISSUE TITLE
Is chaining required?

### ISSUE THREAD

**Issue by travisperson** [webdriverio/webdriverio#428]
In the readme it states "WebdriverIO supports callback and promise based chaining", does this also mean I can simple do the following since it appears it would still be using the same object?

```javascript
var webdriverio = require('../index');
var options = {
    desiredCapabilities: {
        browserName: 'chrome'
    }
};

webdriverio.remote(options)
webdriverio.init()
webdriverio.url('http://www.google.com')
webdriverio.title(function(err, res) {
        console.log('Title was: ' + res.value);
    })
webdriverio.end();
```

**Comment by christian-bromann** [comment]
Hi @travisperson,
no, you need to create a WebdriverIO instance like this:

```js
var webdriverio = require('../index');
var options = {
    desiredCapabilities: {
        browserName: 'chrome'
    }
};

var client = webdriverio.remote(options);
```

Then you can use this instance (client) to make either callback based or promise based chaining:

__callback based__
```js
client
    .setValue('#input', 'test123')
    .getValue('#input, function(err, value) {
         console.log(value); // test123
    });
```

__promise based__
```js
client.setValue('#input', 'test123').then(function() {
    return client.getValue('#input');
}).then(function() {
    console.log(value); // test123
});
```

The docs are not clear about that but I hope it will be soon.

**Comment by travisperson** [comment]
Sorry @christian-bromann, poorly illustrated example. I had written out my own example, but figured using one from the example folder would of been easier, thought I didn't actually run the code and now I see an issue with `webdriverio.remote(options)`.

Basically I'm curious if webdriver.io has Control Flow similar to WebdriverJS.

https://code.google.com/p/selenium/wiki/WebDriverJs#Control_Flows

**Comment by christian-bromann** [comment]
When it comes to promises then yes. But this createFlow thing is a bit different then in selenium-webdriver. Since you chain each command in WebdriverIO and it will executed one after each other you actually don't need that. Do you have an example where you wouldn't know how to translate that into WebdriverIO code?

**Comment by travisperson** [comment]
I'm currently doing research to decided between WebdriverIO and the selenium-webdriver. I really like WebdriverIO, the API documentation is absolutely amazing and easy to read, and the code is very clean for each command. You guys did an amazing job, and I really want to use it.

Right now I'm trying to find some of the key difference. selenium-webdriver is nice because it acts similarly to that of native javascript in the browser using the `document` object.

Here is a login command I currently have in WebdriverIO.
```javascript
function(url, user, pw, cb) {
        this.url(url)
        // Wait for the username input to appear from ExtJS
        .waitForExist(local.elems.USERNAME_INPUT, 5000)
        .setValue(local.elems.USERNAME_INPUT, user)
        .setValue(local.elems.PASSWORD_INPUT, pw)
        .click(local.elems.LOGIN_BUTTON)
        // Wait for the login to 'finish' by expecting the
        // username in the bar to appear after the page reloads
        .waitForExist(gub.elems.USERNAME, 5000)
        .call(cb);
    }
```

In some other places I do not chain, and I'm wondering if it's just a race I'm always winning due to queueing on the selenium side, and not something built into WebdriverIO.

So, could I do the following and be guaranteed execution order by WebdriverIO, or am I in a race with myself, and just appear to usually win?

```javascript
var login = function(url, user, pw, cb) {
        this.url(url)
        // Wait for the username input to appear from ExtJS
        this.waitForExist(local.elems.USERNAME_INPUT, 5000)
        this.setValue(local.elems.USERNAME_INPUT, user)
        this.setValue(local.elems.PASSWORD_INPUT, pw)
        this.click(local.elems.LOGIN_BUTTON)
        // Wait for the login to 'finish' by expecting the
        // username in the bar to appear
        this.waitForExist(gub.elems.USERNAME, 5000)
        this.call(cb);
    }
``` 

Here is an example I have in another place:

```javascript
var waitForThenMove = function(selector, done) {
    this.waitForExist(selector, 2000)
    this.moveToObject(selector)
    this.call(done)
}
```

The `waitForThenMove` example **appears** to execute synchronously without the chaining.

**Comment by christian-bromann** [comment]
WebdriverIO uses [ChainIt](https://github.com/vvo/chainit) for chaining. It puts all commands in a queue. If one command finished executing it starts the next one. So

```js
client
    .setValue('#input', 'test')
    .getValue('#input', function(err, value) {
        console.log(value); // will always output "test"
    })
```

This works also with nested command chaining:

```js
client
    .setValue('#input', 'test', function() {
        client.getValue('#input', function(err, value) {
            console.log(value); // will always output "test"
        });
    })
    .setValue('#input', 'I will get set later')
```

And then it has promise support so you could do:

```
client.setValue('#input', 'test').then(client.getValue('#input')).then(function(value) {
    console.log(value); // will output "test"
    return client.getTitle()
}).then(function(title) {
    console.log(title); // outputs current title
})
```

Since it understand promises you could do

```
chaiAsPromised.transferPromiseness = client.transferPromiseness;
client.setValue('#input', 'test')
        .getValue('#input').should.become.equal('test'); // true
```

I will work on the documentation page soonish to get that better described.

**Comment by travisperson** [comment]
Thanks! The second example answers my questions.
