### ISSUE TITLE
How to get an access to manually configured address+port for "devtools" service

### ISSUE THREAD

**Issue by valenso** [webdriverio/webdriverio#4282]
**Describe your question with as much detail as possible**
My question is similar to #3744 but with a couple of differences.
How my setup looks like:

1. The local machine runs tests and config
```
services: [
    'devtools', {
      debuggerAddress: `34.249.214.36:9222`,
    }
  ],
capabilities: [
    {
      browserName: 'chrome'
    }
  ],
maxInstances: 30,
port: '4444',
host: '34.249.214.36'
```
2. Remote machine is Selenium Grid with opened ports 4444, 9222
3. Code 
```
browser.cdp('Network', 'enable');
```

Result:
```
Could not connect to chrome
(node:56890) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:9222
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1121:14)
(node:56890) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:56890) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C
```

What do I need to add to use of devtool remotely (locally it works fine)?

**Environment (please complete the following information):**
 - **WebdriverIO version:** 4.14.4
 - **Mode:** Standalone mode
 - **Node.js version:** 11.2.0
 - **NPM version:** 6.4.1
 - **Browser name and version:**  Chrome 71
 - **Additional wdio packages used (if applicable):** @wdio/devtools-service

**Comment by christian-bromann** [comment]
> What do I need to add to use of devtool remotely (locally it works fine)?

It seems that WebdriverIO can't connect to the socket port on the remote machine. Make sure the machine that is running the test can access the port in the machine where the browser is running.

If you have further question join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions.

**Comment by valenso** [comment]
>Make sure the machine that is running the test can access the port in the machine where the browser is running.

Absolutely agree, it was my first step. I checked twice, the test works properly without `devtools`.
I will ask the question in Gitter. Thanks)
