### ISSUE TITLE
Add standalone REPL for Appium

### ISSUE THREAD

**Issue by simongranger** [webdriverio/webdriverio#4286]
**Is your feature request related to a problem? Please describe.**
At the moment we can use the webdriver.io REPL interface by adding driver.debug() in our tests. Unfortunately it's not super easy to use when all you want it try out commands or make a manual demo.

**Describe the solution you'd like**
There is a standalone console app for ruby lib that reads your caps from a appium.txt file. It would be great if we could have a similar solution for webdriver.io

https://github.com/appium/ruby_console

**Describe alternatives you've considered**
I write my tests with webdriver.io but always use Appium Ruby Console for sending manual commands or doing demos. I'd rather be able to do it in webdriver.io

**Comment by christian-bromann** [comment]
This will land in #4286. Let's continue the conversation there.
