### ISSUE TITLE
Cucumber: Scenario Outline fails if there is more than one table

### ISSUE THREAD

**Issue by gtilekar** [webdriverio/webdriverio#4287]
**Environment:**
"@wdio/cucumber-framework": "^5.11.11

**Log:**
```
ERROR @wdio/runner: TypeError: Cannot read property 'steps' of undefined
at CucumberEventListener.onTestCasePrepared (ode_modules\@wdio\cucumber-framework\build\cucumberEventListener.js:132:42)
```

**Steps to reproduce:**
Step definition:
```
Given(/^User (.*) with (.*) is logged in$/, { wrapperOptions: { retry: 2 } }, function (userId, password) {
    console.log(userId, password)
})
```
Feature
```
Feature: Foo
    foobar

    Scenario Outline: Bar
        Given User <userId> with <password> is logged in

        @first
        Examples:
                | userId    | password |
                | 345       | pw3      |

        @second
        Examples:
                | userId    | password |
                | 456       | pw4      |
```

More information on below thread:
https://github.com/webdriverio/webdriverio/issues/4195

**Comment by christian-bromann** [comment]
I looked into this for quite a while and couldn't find the reason why this is failing. First of, your example is wrong it should be something along these lines:
```feature
Scenario Outline: Bar
    Given User <userId> with <password> is logged in

    @first
    Examples:
        | userId    | password |
        | 123       | pwd      |
        | 456       | pwd123   |
```

with a step definition like:
```
Given(/^User (.+) with (.+) is logged in/g, {}, function (userId, password) {
    console.log(userId, password)
})
```
but even then I don't get a proper result. It seems that the regex is wrong or something like that. I am not a Cucumber expert, nor do I use Cucumber. If someone knows the solution please provide guidance.

**Comment by gtilekar** [comment]
below stepdef should work .If that is what you are looking for. Don't use '/g' at the end.

Given(/^User (.+) with (.+) is logged in$/, {}, function (userId, password) {
    console.log(userId, password)
})

**Comment by mgrybyk** [comment]
Working example here https://github.com/webdriverio/webdriverio/issues/4195#issuecomment-516901032

**Comment by mgrybyk** [comment]
@gtilekar so you know some docs where I can get acquainted with the feature that allows using @first @second tags in the way you use it?

**Comment by gtilekar** [comment]
Our current framework with node 6.9.1 uses  "wdio-cucumber-framework": "1.0.2" and it works fine with it.

**Comment by mgrybyk** [comment]
This is not helpful at all, that old versions use old cucumberJs.
Anyway, I mean do you know if it is officially supported by cucumber? Some documentation about it

**Comment by mgrybyk** [comment]
I'll fix it soon

**Comment by gtilekar** [comment]
Sorry .I don't know have reference of any document.

**Comment by mgrybyk** [comment]
@gtilekar me neither, I was looks for some examples, etc, but failed.

**Comment by mgrybyk** [comment]
if necessary, let's proceed discussion in PR https://github.com/webdriverio/webdriverio/pull/4290

**Comment by jonn-set** [comment]
This was already fixed, https://github.com/webdriverio-boneyard/wdio-cucumber-framework/issues/162

Looks like it never got released, can someone just release a new version, please?

**Comment by mgrybyk** [comment]
@jonn-set it was fixed and released long time ago, the repository you are referring to is not a webdriverio v5 repository

**Comment by jonn-set** [comment]
It's not released yet, if you check https://www.npmjs.com/package/wdio-cucumber-framework, the last release was on 30-Oct-2018 and my changes were merged only in March, would really appreciate if the maintainer of that library release my changes.

**Comment by mgrybyk** [comment]
@jonn-set the package you've mentioned is wdio v4 package and is no longer supported, it's not a part of webdriverio 5 project .

**Comment by jonn-set** [comment]
> @jonn-set the package you've mentioned is wdio v4 package and is no longer supported, it's not a part of webdriverio 5 project .

I know, but in your previous comment, you mentioned it was released long back, hence clarifying. BTW what's stopping you from releasing merged changes, not going to harm in doing a release to npmjs?

**Comment by mgrybyk** [comment]
It is released to @wdio/cucumber-framework. I can't understand what do you want to be honest. 
You are talking about another repository here, report issue to that project

**Comment by jonn-set** [comment]
Sorry my bad, I thought you meant released to the other repo, I mistook this fix was for v4. Ignore me
