### ISSUE TITLE
Ability to click with particular button, ex right mouse button

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4289]
**Is your feature request related to a problem? Please describe.**
I want to be able to click on element with right, middle or any other buttons

**Describe the solution you'd like**
Click with desired mouse button on element with `performActions`
Example:
`$('selector').click({ button: 'right' })` same as `$('selector').click({ button: 1 })`

There should be no changes to `$('selector').click()`, it should use `elementClick` as before.

**Describe alternatives you've considered**
Do not modify click, add new command to click with perform actions.

**Additional context**

**Comment by lexeek** [comment]
I hope this feature will be implemented soon.

**Comment by christian-bromann** [comment]
@lexeek please don't wait until it happens and rather help us getting in implemented ;-)

**Comment by caoxu2000** [comment]
@christian-bromann I can tackle this but can't promise anything yet.  Do you have any insight on how this should be implemented?  2 ways at high level I can think of: 1) call protocol api directly 2) just call performActions command.  Please let me know your thoughts when you get a chance.

**Comment by caoxu2000** [comment]
Here is all the research I did from v4 & v5:
in v4 https://github.com/webdriverio-boneyard/v4/blob/master/lib/commands/rightClick.js
it uses handleMouseButtonCommand.js below
https://github.com/webdriverio-boneyard/v4/blob/master/lib/helpers/handleMouseButtonCommand.js
but there is protocol js:
https://github.com/webdriverio-boneyard/v4/blob/master/lib/helpers/handleMouseButtonProtocol.js
not sure which one to use for v5 if we need this helper

in v5 for example this doubleClick uses performActions:
https://github.com/webdriverio/webdriverio/blob/e7770403ed1ed41e976b3e04ef7325ea878328e5/packages/webdriverio/src/commands/element/doubleClick.js

**Comment by christian-bromann** [comment]
@caoxu2000 you have to use performAction is the `isW3C` flag is set to `true` otherwise you can use the logic that you've found in v4.

**Comment by jprateek** [comment]
is there any plan to implement this soon?

**Comment by mgrybyk** [comment]
@jprateek @lexeek there are plans to do it, will try to provide with some details soon.

Until that you may just add custom command

**Comment by christian-bromann** [comment]
This landed in #4592 and will be released next.

**Comment by lexeek** [comment]
Thank you for implementation! Despite we have this feature implemented on our own we are really happy with these improvements!
