### ISSUE TITLE
Add unit tests for @wdio/sync - executeAsync

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4292]
**Is your feature request related to a problem? Please describe.**
I'd like to add tests for @wdio/sync, these files in particular:
- `executeAsync` in `index.js`

**Describe the solution you'd like**
Currently most of the functions are marked with `/* istanbul ignore next */`. 
We have to remove that and test all that functions.

**Comment by MatthewBurstein** [comment]
Do the tests for executeAsync still need adding? I'd be happy to pick this up :)

**Comment by mgrybyk** [comment]
gonna be fixed with https://github.com/webdriverio/webdriverio/pull/4612

@MatthewBurstein thank you
