### ISSUE TITLE
webpack dropping wdio dependencies

### ISSUE THREAD

**Issue by Drewster727** [webdriverio/webdriverio#4293]
**Describe your question with as much detail as possible**
I posted [here](https://github.com/serverless-heaven/serverless-webpack/issues/528) on the serverless webpack issues -- as I thought perhaps it could be a webpack and/or serverless issue, but I'm not entirely sure.

I have a node project using serverless + webpack. I am having an issue where my lambda cannot find certain wdio node dependencies even though they are specified in my package.json and getting loaded locally. I'm not having any issues running these tests locally, but webpack just ignores packages that are needed by my project!

package.json dependencies
```
  "devDependencies": {
    "@babel/cli": "^7.5.5",
    "@babel/core": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "@babel/register": "^7.5.5",
    "babel-loader": "^8.0.6",
    "babel-plugin-source-map-support": "^2.1.1",
    "chromedriver": "^75.1.0",
    "geckodriver": "^1.16.2",
    "serverless": "^1.48.4",
    "serverless-offline": "^5.8.0",
    "serverless-offline-scheduler": "^0.3.8",
    "serverless-webpack": "^5.3.1",
    "webpack": "^4.38.0",
    "webpack-node-externals": "^1.7.2",
    "copy-webpack-plugin": "^5.0.4"
  },
  "dependencies": {
    "aws-sdk": "^2.503.0",
    "chai": "^4.2.0",
    "@wdio/logger": "^5.11.0",
    "find-node-modules": "^2.0.0",
    "shelljs": "^0.8.3",
    "tmp": "^0.1.0",
    "@wdio/cli": "^5.11.10",
    "@wdio/sync": "^5.11.0",
    "@wdio/dot-reporter": "^5.11.0",
    "@wdio/local-runner": "^5.11.1",
    "@wdio/mocha-framework": "^5.11.0",
    "@wdio/reporter": "^5.11.7",
    "@wdio/spec-reporter": "^5.11.0",
    "wdio-chromedriver-service": "^5.0.2",
    "wdio-mochawesome-reporter": "^3.1.0",
    "wdio-json-reporter": "^1.3.1",
    "wdio-reporter": "^5.0.0-alpha.7",
    "wdio-timeline-reporter": "^5.0.10",
    "source-map-support": "0.5.12",
    "fs-extra": "^8.1.0",
    "prom-client": "^11.5.3",
    "dateformat": "^3.0.3"
  }
```

In my local node_modules folder, I see these wdio dependency folders as expected:
![image](https://user-images.githubusercontent.com/4528753/62386889-c0cfc900-b51e-11e9-9130-75e86cced74a.png)

However, when I run `serverless package` (which executes webpack) and inspect the zip file produced, I see the node_modules folder is missing those key dependencies:
![image](https://user-images.githubusercontent.com/4528753/62386982-012f4700-b51f-11e9-9efa-cb61000a424e.png)

Where is everything else?

Finally, here is my webpack.config.js file:
```
const slsw = require('serverless-webpack');
const nodeExternals = require('webpack-node-externals');
const CopyPlugin = require('copy-webpack-plugin');

module.exports = {
  entry: slsw.lib.entries,
  target: 'node',
  // Generate sourcemaps for proper error messages
  devtool: 'source-map',
  // Since 'aws-sdk' is not compatible with webpack,
  // we exclude all node dependencies
  externals: [nodeExternals()],
  mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
  optimization: {
    // We no not want to minimize our code.
    minimize: false,
  },
  performance: {
    // Turn off size warnings for entry points
    hints: false,
  },
  // Run babel on all .js files and skip those in node_modules
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: __dirname,
        exclude: /node_modules/,
      },
    ],
  },
  plugins: [
    new CopyPlugin([
      {
        from: 'test/**/*',
        to: '.'
      },
      {
        from: 'reporters/**/*',
        to: '.'
      },
      {
        from: 'wdio.conf.js',
        to: 'wdio.conf.js'
      },
    ]),
  ],
};
```

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.11.0 / latest as of Aug 2019
 - **Mode:** wdio? local
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.16.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Chrome 75
 - **Platform name and version:** mac osx high sierra / latest as of Aug 2019
 - **Additional wdio packages used (if applicable):**  See package.json file above

**Additional context**
I don't see any output indicating a problem. This is definitely not related to serverless, and I believe, everything to do with webpack/wdio

Thanks in advance!
-Drew

**Comment by Drewster727** [comment]
I may have figured out at least partially why this is happening -- wdio.conf.js references these reporters, but webpack apparently doesn't see that they are needed. If I add a dummy requirements.js file to my lambda entrypoint file, and import that reqs file, it loads the dependencies. Like this:

handler.js
```
import { reqs } from './requirements';
...
```

requirements.js
```
import { wdiosync } from '@wdio/sync';
import { wdiodr } from '@wdio/dot-reporter';
import { wdiolr } from '@wdio/local-runner';
import { wdiomfr } from '@wdio/mocha-framework';
import { wdiorep } from '@wdio/reporter';
import { wdiospecrep } from '@wdio/spec-reporter';
import { wdiocd } from 'wdio-chromedriver-service';
import { wdiotlr } from 'wdio-timeline-reporter';
import { wdiotlrtls } from 'wdio-timeline-reporter/timeline-service';
import { wdiomar } from 'wdio-mochawesome-reporter';
import { wdiojr } from 'wdio-json-reporter';
```

Seems pretty hacky to me. Anyone know how to force these dependencies into my package with webpack?

**Comment by christian-bromann** [comment]
This is because wdio imports these packages dynamically based on a package name pattern. The same will happen with services too. I am not sure how to force webpack to stop doing that.

Closing as this doesn't seem to be an issue with WebdriverIO.
