### ISSUE TITLE
Android :Calendar Datepicker scrolling up and down

### ISSUE THREAD

**Issue by bhavyagowda144** [webdriverio/webdriverio#4294]
Hello friends,
I want to select year like “1993” but i am not able to select with this code. It’s not able to scroll up to 1993. Please help me…!!
How to scroll for  previous year
$(android=“new UiScrollable(”
+ “new UiSelector().scrollable(true)).scrollIntoView(”
+ “new UiSelector().textContains(“1993”));”);

**Comment by mgrybyk** [comment]
Hey, I've noticed you asked the question in gitter with no luck.
Not sure if anyone can help you here unless you provide us with something reproducible where someone can play around.

Also, I don't think scroll onto view can work in Android native app, maybe you should try performActions instead.

Try asking in the channel how to scroll in android native app.

**Comment by bhavyagowda144** [comment]
Hi mgrybyk I tried  many functions ..it's not able to scroll upto to specific year.....I had  asked many people still I did not get answer anywhere ..I am working  on WebdriverIO project in native app  from last 2 month ...still I did not get answser ,,, this is different datepicker , not a normal datepicker..

**Comment by mgrybyk** [comment]
Ok, so I have couple of questions: 
- wdio  version 
- appium version
- detailed examples of what you have tried. What errors are you getting per example. I'm especially interested in how you tried to scroll with perform actions 
- finally, no one will be able to help you without your apk

**Comment by bhavyagowda144** [comment]
WebdriverIO version--4.14.3
Appium --1.13.0


I want  to select a specific date of birth year in a datepicker but it's not scrolling and Iam not getting error ..

**Comment by mgrybyk** [comment]
@bhavyagowda144 please provide detailed steps to reproduce and detailed information on what is not working.
