### ISSUE TITLE
How to get browser logs in Chromedriver version 76 ?

### ISSUE THREAD

**Issue by SanthoshBonala** [webdriverio/webdriverio#4297]
How do we get browser console logs in chromedriver v76. Since getLogs does not exist anymore as mentioned over [here ](https://github.com/webdriverio/webdriverio/issues/4275). Is there workaround to get browser console logs?

Thanks in advance!!

**Comment by mgrybyk** [comment]
@SanthoshBonala you have to upgrade to chromedriver 76 and then may temporary use `w3c: false`.
I'm going to provide small fix soon so that getLogs will work for you even in w3c mode (`w3c: true`)

**Comment by mgrybyk** [comment]
ref: https://bugs.chromium.org/p/chromedriver/issues/detail?id=2947

**Comment by mgrybyk** [comment]
Let's track this issue in PR https://github.com/webdriverio/webdriverio/pull/4299
