### ISSUE TITLE
Typings for webdriver commands are not correct if `elemenId` in `variables`

### ISSUE THREAD

**Issue by jayrepo** [webdriverio/webdriverio#4298]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.11.7
 - **Mode:**  WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.6.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Chrome 68
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/sync

**Config of WebdriverIO**
 Using TypeScript.

**Describe the bug**
For commands require `elementId`, the corresponding typings do not have `elementId` as first arg

**To Reproduce**
e.g.
```js
// command
browser.getElementRect(elementId)

// typing in webdriver.d.ts
getElementRect(): object;
```

**Expected behavior**
 if a command has `elementId` in `variables` array, `elementId` should be prepend as first arg. 

**Additional context**
I just checked a few commands.

If all commands in `webdriverio/packages/webdriver/protocol/*.json` are binding to browser/driver, remove filtering of `elementId` in `webdriverio/scripts/type-generation/webdriver-generate-typings.js` should fix this issue

> Please use the correct markdown

**Comment by mgrybyk** [comment]
@jayrepo please avoid using protocol commands, use `$('elem').getSize()`

Question, does `browser.getElementRect($('elem'))` work at all? In all browsers?

**Comment by jayrepo** [comment]
@mgrybyk 
Yes I can use `getSize()` and `getLocation()` for `getElementRect()`.
Does all protocol commands have variants on Element? I can't find that for `browser.takeElementScreenshot()`

`browser.getElementRect($('elem').elementId)` works on native Android app. not sure about browsers.

I'm experimenting on typescript with webdriverio. Another problem with the auto generated typing is browser commands return `object`.
```
// Property 'height' does not exist on type '{}'.ts(2339)
const { height, width } = browser.getWindowRect()

// Have to workaround with
const { height, width }: any = browser.getWindowRect()
```

**Comment by mgrybyk** [comment]
@jayrepo all W3C compliant commands have variants on Element, if not please let us know.
To take element screenshot you can just `$('').saveScreenshot('')`

Regarding issue with rect please raise another defect, you may describe it really shortly, just put webdrverio version for history

**Comment by mgrybyk** [comment]
closing this one according to https://github.com/webdriverio/webdriverio/pull/4300
