### ISSUE TITLE
Property does not exist on type if commands' type def return `object`

### ISSUE THREAD

**Issue by jayrepo** [webdriverio/webdriverio#4301]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.11.7

**Config of WebdriverIO**
Typescript

**Describe the bug**
getWindowRect() for example. It occur on all commands which have return type as `obejct` in type def.

```js
// Property 'height' does not exist on type '{}'.ts(2339)
const { height, width } = browser.getWindowRect()

// type in webdriver.d.ts
getWindowRect(): object;

// Have to workaround with
const { height, width }: any = browser.getWindowRect()
```

**Comment by mgrybyk** [comment]
@jayrepo thank you for submitting this one

**Comment by mgrybyk** [comment]
Adding also couple of issues:

- `browser.getNamedCookie("bar")` // return type should be `Cookie`

- `const wHandle = browser.createWindow("tab")`
`wHandle.handle` // `wHandle` has no proprerty `handle`

- `const timeouts = browser.getTimeouts()` // return type should be `Timeouts`

- `browser.getWindowSize()` // return type should be `SizeReturn`

- `const status = browser.status()`
`status.ready`  // `status` has no property `handle`

**Comment by mgrybyk** [comment]
We may workaround this temporary by changing return type from `object` to 
```
interface ProtocolCommandResponse {
    [key: string]: ProtocolCommandResponse;
}
```

that allows us to do
```
const foo: ProtocolCommandResponse = {}
foo.bar.foobar
```

It is not safe of course, but may unblock users for now
