### ISSUE TITLE
chromedriver binary fails to start

### ISSUE THREAD

**Issue by Drewster727** [webdriverio/webdriverio#4303]
**Describe your question with as much detail as possible**
I have node project that is utilizing wdio to run tests, and am attempting to get it to work inside of an AWS lambda.
I can get everything to work locally and worked through some issues with loading dependencies. Now I'm to the point where the chromedriver fails to spin up when the lambda is executed in AWS.
This is very likely due to the binary getting compiled on my mac and the lambdas execute under a linux platform.

I'm attempting to solve this by packing platform-specific chromedriver binaries with my project, downloaded from: https://chromedriver.chromium.org/downloads

# ***The problem***
The wdio execution of tests yields the following output:
```
./node_modules/.bin/wdio wdio.conf.js --spec ./test/projectx/e2e/specs/**/cfa*.js

Execution of 1 spec files started at 2019-08-03T21:12:11.380Z

Starting ChromeDriver 76.0.3809.68 (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864}) on port 4444
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[0-0] RUNNING in chrome - /test/brandgeek/e2e/specs/cfa_analysis.js
Starting ChromeDriver 76.0.3809.68 (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864}) on port 4444
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Invalid --log-level value.
Unable to initialize logging. Exiting...
[0-0] 2019-08-03T21:12:13.048Z WARN webdriver: Request failed due to unknown error: Chrome failed to start: exited abnormally
  (chrome not reachable)
  (The process started from chrome location ./drivers/chromedriver_mac64 is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Starting ChromeDriver 76.0.3809.68 (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864}) on port 4444
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Invalid --log-level value.
Unable to initialize logging. Exiting...
[0-0] 2019-08-03T21:12:14.099Z WARN webdriver: Request failed due to unknown error: Chrome failed to start: exited abnormally
  (chrome not reachable)
  (The process started from chrome location ./drivers/chromedriver_mac64 is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Starting ChromeDriver 76.0.3809.68 (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864}) on port 4444
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Invalid --log-level value.
Unable to initialize logging. Exiting...
[0-0] 2019-08-03T21:12:15.149Z WARN webdriver: Request failed due to unknown error: Chrome failed to start: exited abnormally
  (chrome not reachable)
  (The process started from chrome location ./drivers/chromedriver_mac64 is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Starting ChromeDriver 76.0.3809.68 (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864}) on port 4444
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Invalid --log-level value.
Unable to initialize logging. Exiting...
[0-0] 2019-08-03T21:12:16.193Z ERROR webdriver: Request failed due to unknown error: unknown error: Chrome failed to start: exited abnormally
  (chrome not reachable)
  (The process started from chrome location ./drivers/chromedriver_mac64 is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
    at getErrorFromResponseBody (/Users/drew/Desktop/repos/project.Synthetics/node_modules/webdriver/build/utils.js:215:10)
    at Request._callback (/Users/drew/Desktop/repos/project.Synthetics/node_modules/webdriver/build/request.js:103:64)
    at Request.self.callback (/Users/drew/Desktop/repos/project.Synthetics/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.<anonymous> (/Users/drew/Desktop/repos/project.Synthetics/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at IncomingMessage.<anonymous> (/Users/drew/Desktop/repos/project.Synthetics/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
[0-0] 2019-08-03T21:12:16.194Z ERROR @wdio/runner: unknown error: unknown error: Chrome failed to start: exited abnormally
  (chrome not reachable)
  (The process started from chrome location ./drivers/chromedriver_mac64 is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
    at getErrorFromResponseBody (/Users/drew/Desktop/repos/project.Synthetics/node_modules/webdriver/build/utils.js:215:10)
    at Request._callback (/Users/drew/Desktop/repos/project.Synthetics/node_modules/webdriver/build/request.js:103:64)
    at Request.self.callback (/Users/drew/Desktop/repos/project.Synthetics/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.<anonymous> (/Users/drew/Desktop/repos/project.Synthetics/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at IncomingMessage.<anonymous> (/Users/drew/Desktop/repos/project.Synthetics/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
0-0 worker error { name: 'unknown error',
  message:
   'unknown error: Chrome failed to start: exited abnormally\n  (chrome not reachable)\n  (The process started from chrome location ./drivers/chromedriver_mac64 is no longer running, so ChromeDriver is assuming that Chrome has crashed.)',
  stack:
   'unknown error: unknown error: Chrome failed to start: exited abnormally\n  (chrome not reachable)\n  (The process started from chrome location ./drivers/chromedriver_mac64 is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\n    at getErrorFromResponseBody (/Users/drew/Desktop/repos/project.Synthetics/node_modules/webdriver/build/utils.js:215:10)\n    at Request._callback (/Users/drew/Desktop/repos/project.Synthetics/node_modules/webdriver/build/request.js:103:64)\n    at Request.self.callback (/Users/drew/Desktop/repos/project.Synthetics/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:198:13)\n    at Request.EventEmitter.emit (domain.js:448:20)\n    at Request.<anonymous> (/Users/drew/Desktop/repos/project.Synthetics/node_modules/request/request.js:1161:10)\n    at Request.emit (events.js:198:13)\n    at Request.EventEmitter.emit (domain.js:448:20)\n    at IncomingMessage.<anonymous> (/Users/drew/Desktop/repos/project.Synthetics/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:286:20)' }
[0-0] 2019-08-03T21:12:16.195Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'capabilities' of null
    at Runner.run (/Users/drew/Desktop/repos/project.Synthetics/node_modules/@wdio/runner/build/index.js:68:74)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

In the wdio.conf.js file I am referencing the downloaded platform-specific binary -- in this case I referenced the mac binary to ensure things work locally:
```
exports.config = {
    runner: 'local',
    port: 4444,
    path: '/',
    specs: [
        './test/projectx/e2e/specs/**/*.js',
    ],
    exclude: [],
    maxInstances: 1,
    capabilities: [{
        maxInstances: 5,
        browserName: 'chrome',
        'goog:chromeOptions': {
            binary: "./drivers/chromedriver_mac64",
            args: [
                'headless'
                ,'port=4444'
                ,'no-sandbox'
                ,'disable-gpu'
                ,'disable-logging'
                ,'disable-plugins'
                ,'disable-extensions'
                ,'disable-dev-shm-usage'
                ,'homedir=/tmp/chrome'
                ,'disk-cache-dir=/tmp/chrome/cache-dir'
                ,'remote-debugging-port=9222'
                ,'window-size=1680,2400'
                ,'verbose'
                ,'log-path=./drivers/chromedriver.log'
            ],
        },
    }],
```

If I execute the chromedriver manually from the command line via:
`./drivers/chromedriver_mac64 --verbose --no-sandbox --headless --port=4444`
It spins up as expected, and then if I comment out the part in my wdio.conf.js that tells wdio to use a custom binary, it connects to my 4444 session I just spun up manually and executes tests.

So there appears to be some issue with spinning up the chromedriver binary and I can't get an information as to why no matter how verbose I set the logging on wdio and the driver itself.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.11.0 / latest as of Aug 2019
 - **Mode:** wdio? local
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.16.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Chrome 75
 - **Platform name and version:** mac osx high sierra / latest as of Aug 2019
 - **Additional wdio packages used (if applicable):**  See package.json file above

**Additional context**
My goal is to use the mac chromedriver binary locally and tell my lambda when I deploy it to use the linux binary. I didn't really see any other reasonable ways to do this. Open for suggestions to this.

Thanks,
Drew

**Comment by mgrybyk** [comment]
Why don't you pass args as you do manually, with two dash syntax, --headless, etc. 
Can you please also enable selenium logs, and share them?

In the latest chrome I had an issue with network service, so I disabled it --disable-features=NetworkService

**Comment by Drewster727** [comment]
@mgrybyk thanks for the response. 
I have not seen anyone use the dashes in the args in wdio.conf.js capabilities, it appears to work both ways.
I'm not actually using selenium. I'm relying upon the chromedriver service to spin up the listener. I can't seem to get anything useful out of it.
I will attempt to shut off the network service feature, but don't think that;s my issue here.

-Drew

**Comment by mgrybyk** [comment]
What is in chromedriver service logs https://www.npmjs.com/package/wdio-chromedriver-service#configuration ?

It doesn't look to me like wdio issue, sounds like some configuration issue on your side

**Comment by TamasSzalisznyi** [comment]
java openjdk15, chromedriver 87. ..., selenium-java 3.14.59   

with that simple driver method:

public static WebDriver getDriver() {
        System.setProperty("webdriver.chrome.driver", "/home/user/snap/webdriver/chromedriver87");
        final WebDriver driver = new ChromeDriver();
        return driver;
    }

I get the same issue with invalid log level:

Starting ChromeDriver 87.0.4280.88 (89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}) on port 1653
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Starting ChromeDriver 88.0.4324.27 (6347fe8bf1e48bd0c54d07dc55ca011cf40861c9-refs/branch-heads/4324@{#450}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
Invalid --log-level value.
Unable to initialize logging. Exiting...
Exception in thread "main" org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'user-ThinkPad-T440', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-58-generic', java.version: '15.0.1'
Driver info: driver.version: ChromeDriver
remote stacktrace: #0 0x564a52f9fe79 <unknown>

**Comment by wuyongzheng** [comment]
I just came across this error and fixed it. The "Invalid --log-level value" error is caused by using ChromeDriver as Chrome. Selenium runs ChromeDriver, then ChromeDriver runs Chrome. Chrome recognise "--log-level=0", but not ChromeDriver.

What's happening here is that you try to use ChromeDriver to run ChromeDriver. The reason can be specifying ChromeDriver's path as Chrome. E.g. symbolic link chromedriver as chrome.
