### ISSUE TITLE
Property 'startTracing' does not exist on type 'BrowserObject'.ts

### ISSUE THREAD

**Issue by DimitryRd** [webdriverio/webdriverio#4315]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.11.11
 - **Mode:** Snadalone
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.12
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome 75
 - **Platform name and version:** MacOs 10.14
 - **Additional wdio packages used (if applicable):** Devtool, webdriver

**Config of WebdriverIO**
exports.config = {
    //
    // ====================
    // Runner Configuration
    // ====================
    //
    // WebdriverIO allows it to run your tests in arbitrary locations (e.g. locally or
    // on a remote machine).
    runner: 'local',
    //
    // Override default path ('/wd/hub') for chromedriver service.
    path: '/',
    //
    // ==================
    // Specify Test Files
    // ==================
    // Define which test specs should run. The pattern is relative to the directory
    // from which `wdio` was called. Notice that, if you are calling `wdio` from an
    // NPM script (see https://docs.npmjs.com/cli/run-script) then the current working
    // directory is where your package.json resides, so `wdio` will be called from there.
    //
    specs: [
        './test/specs/**/*.js'
    ],
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    //
    // ============
    // Capabilities
    // ============
    // Define your capabilities here. WebdriverIO can run multiple capabilities at the same
    // time. Depending on the number of capabilities, WebdriverIO launches several test
    // sessions. Within your capabilities you can overwrite the spec and exclude options in
    // order to group specific specs to a specific capability.
    //
    // First, you can define how many instances should be started at the same time. Let's
    // say you have 3 different capabilities (Chrome, Firefox, and Safari) and you have
    // set maxInstances to 1; wdio will spawn 3 processes. Therefore, if you have 10 spec
    // files and you set maxInstances to 10, all spec files will get tested at the same time
    // and 30 processes will get spawned. The property handles how many capabilities
    // from the same test should run tests.
    //
    maxInstances: 10,
    //
    // If you have trouble getting all important capabilities together, check out the
    // Sauce Labs platform configurator - a great tool to configure your capabilities:
    // https://docs.saucelabs.com/reference/platforms-configurator
    //
    capabilities: [{
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        maxInstances: 5,
        //
        browserName: 'chrome',
        // If outputDir is provided WebdriverIO can capture driver session logs
        // it is possible to configure which logTypes to include/exclude.
        // excludeDriverLogs: ['*'], // pass '*' to exclude all driver session logs
        // excludeDriverLogs: ['bugreport', 'server'],
    }],
    //
    // ===================
    // Test Configurations
    // ===================
    // Define all options that are relevant for the WebdriverIO instance here
    //
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    logLevel: 'info',
    //
    // Set specific log levels per logger
    // loggers:
    // - webdriver, webdriverio
    // - @wdio/applitools-service, @wdio/browserstack-service, @wdio/devtools-service, @wdio/sauce-service
    // - @wdio/mocha-framework, @wdio/jasmine-framework
    // - @wdio/local-runner, @wdio/lambda-runner
    // - @wdio/sumologic-reporter
    // - @wdio/cli, @wdio/config, @wdio/sync, @wdio/utils
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    // logLevels: {
    //     webdriver: 'info',
    //     '@wdio/applitools-service': 'info'
    // },
    //
    // If you only want to run your tests until a specific amount of tests have failed use
    // bail (default is 0 - don't bail, run all tests).
    bail: 0,
    //
    // Set a base URL in order to shorten url command calls. If your `url` parameter starts
    // with `/`, the base url gets prepended, not including the path portion of your baseUrl.
    // If your `url` parameter starts without a scheme or `/` (like `some/path`), the base url
    // gets prepended directly.
    baseUrl: '0.0.0.0:8080',
    //
    // Default timeout for all waitFor* commands.
    waitforTimeout: 10000,
    //
    // Default timeout in milliseconds for request
    // if Selenium Grid doesn't send response
    connectionRetryTimeout: 90000,
    //
    // Default request retries count
    connectionRetryCount: 3,
    //
    // Test runner services
    // Services take over a specific job you don't want to take care of. They enhance
    // your test setup with almost no effort. Unlike plugins, they don't add new
    // commands. Instead, they hook themselves up into the test process.
    services: ['selenium-standalone','chromedriver','devtools'],
    
    // Framework you want to run your specs with.
    // The following are supported: Mocha, Jasmine, and Cucumber
    // see also: https://webdriver.io/docs/frameworks.html
    //
    // Make sure you have the wdio adapter package for the specific framework installed
    // before running any tests.
    framework: 'mocha',
    //
    // The number of times to retry the entire specfile when it fails as a whole
    // specFileRetries: 1,
    //
    // Test reporter for stdout.
    // The only one supported by default is 'dot'
    // see also: https://webdriver.io/docs/dot-reporter.html
    reporters: ['spec'],
    
    //
    // Options to be passed to Mocha.
    // See the full list at http://mochajs.org/
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },
    //
    // =====
    // Hooks
    // =====
    // WebdriverIO provides several hooks you can use to interfere with the test process in order to enhance
    // it and to build services around it. You can either apply a single function or an array of
    // methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
    // resolved to continue.
    /**
     * Gets executed once before all workers get launched.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     */
    // onPrepare: function (config, capabilities) {
    // },
    /**
     * Gets executed just before initialising the webdriver session and test framework. It allows you
     * to manipulate configurations depending on the capability or spec.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     */
    // beforeSession: function (config, capabilities, specs) {
    // },
    /**
     * Gets executed before test execution begins. At this point you can access to all global
     * variables like `browser`. It is the perfect place to define custom commands.
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     */
    // before: function (capabilities, specs) {
    // },
    /**
     * Runs before a WebdriverIO command gets executed.
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     */
    // beforeCommand: function (commandName, args) {
    // },
    /**
     * Hook that gets executed before the suite starts
     * @param {Object} suite suite details
     */
    // beforeSuite: function (suite) {
    // },
    /**
     * Function to be executed before a test (in Mocha/Jasmine) or a step (in Cucumber) starts.
     * @param {Object} test test details
     */
    // beforeTest: function (test) {
    // },
    /**
     * Hook that gets executed _before_ a hook within the suite starts (e.g. runs before calling
     * beforeEach in Mocha)
     */
    // beforeHook: function () {
    // },
    /**
     * Hook that gets executed _after_ a hook within the suite starts (e.g. runs after calling
     * afterEach in Mocha)
     */
    // afterHook: function () {
    // },
    /**
     * Function to be executed after a test (in Mocha/Jasmine) or a step (in Cucumber) starts.
     * @param {Object} test test details
     */
    // afterTest: function (test) {
    // },
    /**
     * Hook that gets executed after the suite has ended
     * @param {Object} suite suite details
     */
    // afterSuite: function (suite) {
    // },
    /**
     * Runs after a WebdriverIO command gets executed
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     * @param {Number} result 0 - command success, 1 - command error
     * @param {Object} error error object if any
     */
    // afterCommand: function (commandName, args, result, error) {
    // },
    /**
     * Gets executed after all tests are done. You still have access to all global variables from
     * the test.
     * @param {Number} result 0 - test pass, 1 - test fail
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // after: function (result, capabilities, specs) {
    // },
    /**
     * Gets executed right after terminating the webdriver session.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // afterSession: function (config, capabilities, specs) {
    // },
    /**
     * Gets executed after all workers got shut down and the process is about to exit. An error
     * thrown in the onComplete hook will result in the test run failing.
     * @param {Object} exitCode 0 - success, 1 - fail
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {<Object>} results object containing test results
     */
    // onComplete: function(exitCode, config, capabilities, results) {
    // },
    /**
    * Gets executed when a refresh happens.
    * @param {String} oldSessionId session ID of the old session
    * @param {String} newSessionId session ID of the new session
    */
    //onReload: function(oldSessionId, newSessionId) {
    //}
}

**Describe the bug**
All API whic is related to performance and CDP is not presented in BrowserObject types

**To Reproduce**
tsconfig.json
{
    "compilerOptions": {
        "target": "es2017",
        "lib": [
            "es2017",
            "dom"
        ],
        "baseUrl": ".",
        "paths": {
            "*": [ "./*" ],
            "src/*": ["./src/*"]
        },
        "types": ["node", "@wdio/sync", "@wdio/mocha-framework","@types/mapbox-gl", "@types/googlemaps"]
    },
    "include": ["./*"],
    "exclude": ["node_modules", "dist"]
}

**Expected behavior**
browser.startTracing working as intended

**Log**
 ./node_modules/.bin/wdio wdio.conf.js --spec ./tests/google_spec.ts

Execution of 1 spec files started at 2019-08-05T14:06:36.657Z

2019-08-05T14:06:38.049Z INFO @wdio/cli:Launcher: Run onPrepare hook
2019-08-05T14:06:42.029Z INFO @wdio/local-runner: Start worker 0-0 with arg: wdio.conf.js,--spec,./tests/google_spec.ts
[0-0] RUNNING in chrome - /tests/google_spec.ts
[0-0] 2019-08-05T14:06:42.950Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2019-08-05T14:06:43.425Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2019-08-05T14:06:43.425Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
     firstMatch: [ {} ] },
  desiredCapabilities:
   { browserName: 'chrome',
     'goog:chromeOptions': { args: [Array] } } }
[0-0] 2019-08-05T14:06:51.652Z INFO webdriver: COMMAND setTimeouts("script", 120000)
[0-0] 2019-08-05T14:06:51.653Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session/ef09cdf15806bfc58a583c9f5daf7c00/timeouts
[0-0] 2019-08-05T14:06:51.653Z INFO webdriver: DATA { type: 'script', ms: 120000 }
[0-0] TypeError in "Google Maps should init map and execute flyover"
browser.startTracing is not a function
[0-0] 2019-08-05T14:06:51.701Z INFO webdriver: COMMAND deleteSession()
[0-0] 2019-08-05T14:06:51.701Z INFO webdriver: [DELETE] http://127.0.0.1:4444/wd/hub/session/ef09cdf15806bfc58a583c9f5daf7c00
[0-0] FAILED in chrome - /tests/google_spec.ts
2019-08-05T14:06:51.921Z INFO @wdio/cli:Launcher: Run onComplete hook
2019-08-05T14:06:51.921Z INFO @wdio/selenium-standalone-service: shutting down all browsers

 "spec" Reporter:
------------------------------------------------------------------
[chrome 75.0.3770.142 Mac OS X #0-0] Spec: /Users/drudakov/Projects/benchmark/tests/google_spec.ts
[chrome 75.0.3770.142 Mac OS X #0-0] Running: chrome (v75.0.3770.142) on Mac OS X
[chrome 75.0.3770.142 Mac OS X #0-0]
[chrome 75.0.3770.142 Mac OS X #0-0] Google Maps
[chrome 75.0.3770.142 Mac OS X #0-0]    ✖ should init map and execute flyover
[chrome 75.0.3770.142 Mac OS X #0-0]
[chrome 75.0.3770.142 Mac OS X #0-0] 1 failing (3.7s)
[chrome 75.0.3770.142 Mac OS X #0-0]
[chrome 75.0.3770.142 Mac OS X #0-0] 1) Google Maps should init map and execute flyover
[chrome 75.0.3770.142 Mac OS X #0-0] browser.startTracing is not a function
[chrome 75.0.3770.142 Mac OS X #0-0] TypeError: browser.startTracing is not a function
[chrome 75.0.3770.142 Mac OS X #0-0]     at Context.it (/Users/drudakov/Projects/benchmark/tests/google_spec.ts:15:32)
[chrome 75.0.3770.142 Mac OS X #0-0]     at Promise (/Users/drudakov/Projects/benchmark/node_modules/@wdio/sync/build/index.js:65:22)
[chrome 75.0.3770.142 Mac OS X #0-0]     at new Promise (<anonymous>)
[chrome 75.0.3770.142 Mac OS X #0-0]     at Context.executeSync (/Users/drudakov/Projects/benchmark/node_modules/@wdio/sync/build/index.js:63:10)
[chrome 75.0.3770.142 Mac OS X #0-0]     at /Users/drudakov/Projects/benchmark/node_modules/@wdio/sync/build/index.js:209:70

Spec Files:	 0 passed, 1 failed, 1 total (100% completed) in 00:00:15
**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
We haven't updated our type definitions for these service. Any PR is appreciated!

**Comment by mgrybyk** [comment]
@DimitryRd have you run `browser.enablePerformanceAudits()` before using `startTracing` ?

**Comment by christian-bromann** [comment]
Please check if above solution works for you and report back if not. Closing.
