### ISSUE TITLE
waitForExist does not work in async/await mode

### ISSUE THREAD

**Issue by jensbodal** [webdriverio/webdriverio#4319]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.11.10
 - **Mode:** standalone?
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 10.16.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** chrome headless
 - **Platform name and version:** Linux 4.9.184-linuxkit
 - **Additional wdio packages used (if applicable):** chromedriver

**Config of WebdriverIO**
```
{
  waitForTimeout: 3000,
}
```

**Describe the bug**
Since `$` returns a promise, you need to await it in order to use `waitForExist` function from the returned element. The initial `await` makes it impossible to wait for the element unless it already exists. 

**To Reproduce**
```
// have to await the element as '$' returns a promise
// at this point the waitForTimeout setting is implicitly used to wait for the element
const element = await $('foo'); 

// we won't get to this point unless the element already exists
await element.waitForExist(10000); 
```

**Expected behavior**
I'm not sure what else can be done, but I think the docs for things like https://webdriver.io/docs/api/element/waitForExist.html should call out the unintended behavior when using async/await mode.

Is there a way I can override the `waitForTimeout` at runtime?

**Comment by jensbodal** [comment]
I think I had something misconfigured, this appears to work as intended.

**Comment by balazserdeszlogmein** [comment]
I am having the same issue, and it would have been if you had put the misconfiguration reason here.

**Comment by jensbodal** [comment]
Unfortunately this is a case of I don't know what solved the issue and I didn't end up using this library after all.  

Re-reading the docs now 

> As opposed to other element commands WebdriverIO will not wait for the element to exist to execute this command.

I can only assume what ended up working for me was

```
await $('foo').waitForExist(10000); 
```
