### ISSUE TITLE
$(element).moveTo() moves cursor to [0, 0] on Safari

### ISSUE THREAD

**Issue by thephilwells** [webdriverio/webdriverio#4322]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.11.7
 - **Mode:** Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 8.9.0
 - **NPM version:** 5.5.1
 - **Browser name and version:** Safari 12.1.2
 - **Platform name and version:** MacOS 10.13
 - **Additional wdio packages used (if applicable):** @wdio/sauce-service (reproduced in Sauce and on local)

**Config of WebdriverIO**
Sauce config (W3C spec compliant):

```js
if (config.get('SAUCE_ACCESS_KEY')) {
  services.push('sauce')
  user = config.get('SAUCE_USERNAME')
  key = config.get('SAUCE_ACCESS_KEY')
  capability['sauce:options'] = {
    build: `${config.get('PROJECT_NAME')}:${config.get('BUILD_NUMBER') || new Date()}`,
    platform: config.get('PLATFORM_OS'),
    version: config.get('PLATFORM_BROWSER_VERSION').toString(),
    screenResolution: config.get('PLATFORM_SCREEN_RESOLUTION'),
    parentTunnel: config.get('PLATFORM_PARENT_TUNNEL'),
    tunnelIdentifier: config.get('PLATFORM_TUNNEL_ID'),
    extendedDebugging: config.get('PLATFORM_EXTEND_DEBUG'),
    commandTimeout: config.get('PLATFORM_COMMAND_TIMEOUT'),
    idleTimeout: config.get('PLATFORM_IDLE_TIMEOUT'),
    timeZone: config.get('PLATFORM_TIME_ZONE'),
  }
}
```

from package.json:

```
    "@wdio/cli": "^5.11.13",
    "@wdio/local-runner": "^5.11.0",
    "@wdio/mocha-framework": "^5.11.0",
    "@wdio/reporter": "^5.11.0",
    "@wdio/sauce-service": "^5.11.0",
    "@wdio/selenium-standalone-service": "^5.11.0",
    "@wdio/spec-reporter": "^5.11.0",
    "@wdio/sync": "^5.11.0",
    "webdriverio": "^5.11.0"
```

**Describe the bug**
`$(element).moveTo()` moves the cursor to `{x: 0, y: 0}` on Safari, even though when I debug `moveTo.js` and evaluate the values for `newXoffset` and `newYoffset` before and after the action is performed, they contain the correct coordinates.

**To Reproduce**
Run using latest Safari:

```js
const pauseIcon = `[class*='Icon-pause']`
const modalButton = `[class*='buttons-modalButton'] div`

describe('pause button opacity change on hover', () => {
  it("Should change XWD pause button's opacity on hover", () => {
    // Arrange
    browser.navigateTo('https://www.nytimes.com/crosswords/game/mini')
    $(modalButton).click()

    // Act
    $('body').scrollIntoView()
    $(pauseIcon).moveTo(1, 1)
    browser.waitUntil(() => {
      return $(pauseIcon).getCSSProperty('opacity').value - 1 < 0.01  // changes on hover
    })
    pauseButtonOpacityAfter = $(pauseIcon).getCSSProperty('opacity').value

    // Assert
    expect(
      pauseButtonOpacityAfter,
      'Expect Pause button opacity to equal 1 with hover'
    ).to.equal(1)
  })
})
```

**Expected behavior**
The cursor should move to the coordinates of the Pause button, causing its opacity to change, and the test to pass.

**Log**
Check the log here:
https://gist.github.com/thephilwells/df72a5beed90cdc50e1ca0940b77fd50

NB: `Line 36` shows the the correct X, Y values for the element are returned.

**Additional context**
Was able to draw the mouse cursor on the screen to help figure out where it was ending up, using this code:
```js
function drawCursor () {
    browser.execute(function () {
    var seleniumFollowerImg = document.createElement('img')
    seleniumFollowerImg.setAttribute(
      'src',
      'data:image/png;base64,' +
        'iVBORw0KGgoAAAANSUhEUgAAABQAAAAeCAQAAACGG/bgAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAA' +
        'HsYAAB7GAZEt8iwAAAAHdElNRQfgAwgMIwdxU/i7AAABZklEQVQ4y43TsU4UURSH8W+XmYwkS2I0' +
        '9CRKpKGhsvIJjG9giQmliHFZlkUIGnEF7KTiCagpsYHWhoTQaiUUxLixYZb5KAAZZhbunu7O/PKf' +
        'e+fcA+/pqwb4DuximEqXhT4iI8dMpBWEsWsuGYdpZFttiLSSgTvhZ1W/SvfO1CvYdV1kPghV68a3' +
        '0zzUWZH5pBqEui7dnqlFmLoq0gxC1XfGZdoLal2kea8ahLoqKXNAJQBT2yJzwUTVt0bS6ANqy1ga' +
        'VCEq/oVTtjji4hQVhhnlYBH4WIJV9vlkXLm+10R8oJb79Jl1j9UdazJRGpkrmNkSF9SOz2T71s7M' +
        'SIfD2lmmfjGSRz3hK8l4w1P+bah/HJLN0sys2JSMZQB+jKo6KSc8vLlLn5ikzF4268Wg2+pPOWW6' +
        'ONcpr3PrXy9VfS473M/D7H+TLmrqsXtOGctvxvMv2oVNP+Av0uHbzbxyJaywyUjx8TlnPY2YxqkD' +
        'dAAAAABJRU5ErkJggg=='
    )
    seleniumFollowerImg.setAttribute('id', 'selenium_mouse_follower')
    seleniumFollowerImg.setAttribute(
      'style',
      'position: absolute; z-index: 99999999999; pointer-events: none; left:0; top:0'
    )
    document.body.appendChild(seleniumFollowerImg)
    document.onmousemove = function (e) {
      document.getElementById('selenium_mouse_follower').style.left = e.pageX + 'px'
      document.getElementById('selenium_mouse_follower').style.top = e.pageY + 'px'
    }
  })
}

module.exports = drawCursor
```

Here's what that ended up looking like when the test ends:

![moveToScreenshot](https://user-images.githubusercontent.com/1882060/62497967-99416080-b7ab-11e9-89d0-2086bb3c0b7c.png)

**Comment by mgrybyk** [comment]
@thephilwells  I'm getting the following assertion error in safari
```
Expect Pause button opacity to equal 0.3 without hover: expected 0.30692338943481445 to equal 1
[Safari  macOS #0-0] AssertionError: Expect Pause button opacity to equal 0.3 without hover: expected 0.306923389434814
```

Sounds reasonable!

**Comment by thephilwells** [comment]
Looks like I mixed up the messaging in the asserts. The wCrux of the
failure is not decimal rounding, though. At the end that opacity should be
1 (like it is on chrome and ff) or within .01 of that (what I'd expect on
safari.)

None of that happens though because the pointer ends up hovering over 0,0
instead of the element's location.

I'm on the bus now but I'll try to clean up the sample code.

**Comment by mgrybyk** [comment]
No worries, I think I've got your point, the code is passing in Chrome and Firefox, but doesn't work as expected in Safari

**Comment by thephilwells** [comment]
Yep!

**Comment by mgrybyk** [comment]
I have reproduced the issue but have no idea how to fix it, it might be some issue with Safari and/or Safari driver itself.

**Comment by jayrepo** [comment]
@thephilwells @mgrybyk 
I can see a blink on the pauseIcon with $(element).moveTo()

As safari does not support `/session/<seesionId>/moveto` endpoint like chrome.
from the log, I can see it get the rect of element, perform w3c `pointerMove` action, then delete the action
```log
REQUEST GET /session/<sessionId>/element/node-BBAADDC0-9B54-4479-854B-18FEDA618A49/rect {}
RESPONSE {"value":{"y":523,"x":486,"width":13,"height":15}}
REQUEST POST /session/<sessionId>/actions {"actions":[{"type":"pointer","id":"finger1","parameters":{"pointerType":"mouse"},"actions":[{"type":"pointerMove","duration":0,"x":487,"y":524}]}]}
RESPONSE {"value":null}
REQUEST DELETE /session/<sessionId>/actions {}
RESPONSE {"value":null}
```

It should be issue with `$(element).moveTo()` command for safari. 
A workaround:
```js
  const { x, y } = $('ele').getLocation();
  browser.performActions([
    {
      type: "pointer",
      id: "finger1",
      parameters: {
        pointerType: "mouse"
      },
      actions: [
        {
          type: "pointerMove",
          duration: 0,
          x: x + 1,
          y: y + 1
        },
        { type: "pointerUp", button: 0 }
      ]
    }
  ]);

```
The snippet above add a `pointerUp` action, without delete the action. Please have a try, I don't if it works for you.

**Comment by thephilwells** [comment]
I agree that the pointer does seem to actually be in transit during the action; it just stops at (or hops to?) the wrong coordinates. The `pointerUp` workaround did not work for me on Safari.

**Comment by thephilwells** [comment]
I can confirm that it's a hop after the action is done. If I up the duration of the `mouseMove` action to 5000ms, I can see the hover state on the button for 5 seconds. Then, the cursor hops back to `0,0`.

So, maybe not a bug? What do we expect the state of the pointer to be after the action is released?

**Comment by thephilwells** [comment]
If I remove the call to release the action from `moveTo()` (`.then(() => this.releaseActions());`), the pointer stays in its place after the action is complete and the test passes. Is this an acceptable change?

**Comment by mgrybyk** [comment]
Does it work for all the browsers?

**Comment by thephilwells** [comment]
It's looked fine on Chrome, FF, Safari, and MS Edge. IE is giving me trouble with this reproduction case before it ever gets to the actions part. 🙄

**Comment by thephilwells** [comment]
But then are W3C actions expected to work on IE?

**Comment by mgrybyk** [comment]
I'm fine it it works everywhere except of IE.

Will you be able to rise PR for this one?

**Comment by thephilwells** [comment]
Yeah, let me try to get it done now. Today is lots of meetings! 🏃

**Comment by thephilwells** [comment]
Build failures. 😪 

Hold please.

**Comment by mgrybyk** [comment]
No rush, man, take tour time!

**Comment by thephilwells** [comment]
Hey @mgrybyk I'm getting eslint errors when I build after my changes, 

```
Unable to resolve path to module '...'
```

..over and over. When I ignore that issue in eslint the tests pass fine, but I don't want to mess with the eslint config as part of my PR. Any idea what I'm doing wrong?

I have eslint 6.1.0 installed, running node 8.9.0.

**Comment by christian-bromann** [comment]
Let's continue convo in #4330

**Comment by sathyasri123222** [comment]
Hi @christian-bromann, MoveTo() function is not working in Safari Browser. Could you help me in resolving this issue .
I tried all the different way suggested in link " https://github.com/webdriverio/webdriverio/issues/4322" . Kindly need your help in resolving
