### ISSUE TITLE
Automatically set test name for Sauce Labs RDC

### ISSUE THREAD

**Issue by martinfrancois** [webdriverio/webdriverio#4323]
**Is your feature request related to a problem? Please describe.**
When we run tests on Sauce Labs RDC, we are always struggling with correlating the right execution on Sauce Labs with the spec file. The capability `testobject_test_name` can be set to define a test name, but the problem is that this is not specific per spec file, and it appears as if there is no lifecycle method in WebdriverIO I could use where I have access to the name of the test and where I can still change the capabilities.

**Describe the solution you'd like**
If no capability `testobject_test_name` is provided, automatically set it to the name of the spec. For example:
```
describe('Navigation', () => {
  ...
});
```
Would result in the name `Navigation` when clicking on the execution on Sauce Labs RDC.
This could be done by finding a way to modify the `testobject_test_name` with the corresponding name and send that one out during test execution or updating the job on Sauce Labs afterwards.

**Describe alternatives you've considered**
- Uploading a separate app per spec file with different version number / name to differentiate them would work, but would dramatically slow down the tests
- Having one config file per spec and include capabilities per spec file, setting the `testobject_test_name` in each and compiling them together would work, even without penalties, but is not a very pretty solution and would require us to update config files every time we add a new spec.
- As mentioned, it would be nice if there was a way to modify the capabilities with the test name in a lifecycle method hook, but I didn't find any that would provide the test name with still the possibility to change the capabilities.

**Additional context**
I had looked into how to fix the issue myself and found that this is indeed implemented for tests without RDC (see `service.js` the method `beforeTest`. As far as I understood, it uses `sauce:context` to provide context for the job. I'm not sure if this is also possible with RDC, maybe there is some preparation work necessary on Sauce Labs' end.

**Comment by wswebcreation** [comment]
Hi @martinfrancois

To give you some context for "the future", Sauce Labs is busy with the unified platform. This means that the real devices will use the "standard" API's from Sauce Labs that are also used for the Virtual Machines and 99% sure the testname can also be updated during tests. This means no adjustment to the current way of working and updating of tests as it is done now for Virtual Machines.

The migration to the Unified Platform will be done in steps (first private then public devices) which in the end will solve this problem for you.

I don't know if this will help in determining if this feature is needed or not. (Can't pinpoint exact dates, but the unified platform for private devices is in beta now for EU)

**Comment by christian-bromann** [comment]
The migration to the unified platform has mostly been completed by now. Closing.
