### ISSUE TITLE
screenshots are not attached to allure for webdriverIO 5.x.x in cucumber

### ISSUE THREAD

**Issue by meruga92** [webdriverio/webdriverio#4335]
**Environment:**
 - **WebdriverIO version: 5.11.13**
 - **Mode: WDIO Testrunner**
 - **If WDIO Testrunner, running sync/async: sync**
 - **Node.js version: 10.13.0**
 - **NPM version:6.4.1** 
 - **Platform name and version: mobile iOS and Android** 
 - **Additional wdio packages used (if applicable): @wdio/allure-reporter, @wdio/appium-service, @wdio/cucumber-framework** 

**Config of WebdriverIO**
   reporters: ['spec', ['allure', {
      outputDir: 'allure-results',
      disableWebdriverStepsReporting: true,
      disableWebdriverScreenshotsReporting: false,
      useCucumberStepReporter: true
    }]],
    afterStep: function (uri, feature, scenario, step, result, sourceLocation) {
      if (result.status.includes('failed')) {
        console.log(result.status);
        browser.takeScreenshot();
      }
    }

**Describe the bug**
As mentioned in docs https://webdriver.io/docs/allure-reporter.html#add-screenshots i tried the same code snippet but since i am using cucumber i dont have `afterTest` hook i added the code in the `afterStep` hook so that it will take screenshots and attach when any step fails. The issue with `browser.takeScreenshot()` is that it does not work as expected. In the code above the appium deletes the session right after test fail and `browser.takeScreenshot()` fails on appium since the session is deleted

**APPIUM LOGS**
[debug] [WD Proxy] Matched '/elements' to command name 'findElements'
[debug] [WD Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/FA768B15-82BB-45DF-B011-5C130929DE35/elements] with body: {"using":"accessibility id","value":"Main Menu"}
[debug] [WD Proxy] Got response with status 200: {"value":[],"sessionId":"FA768B15-82BB-45DF-B011-5C130929DE35","status":0}
[debug] [BaseDriver] Waited for 28354 ms so far
[debug] [WD Proxy] Matched '/elements' to command name 'findElements'
[debug] [WD Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/FA768B15-82BB-45DF-B011-5C130929DE35/elements] with body: {"using":"accessibility id","value":"Main Menu"}
[debug] [WD Proxy] Got response with status 200: {"value":[],"sessionId":"FA768B15-82BB-45DF-B011-5C130929DE35","status":0}
[debug] [BaseDriver] Waited for 28940 ms so far
[HTTP] --> GET /wd/hub/session/bb5fafa9-acb6-4a87-9926-8d8fdd25b15a/screenshot
[HTTP] {}
[debug] [W3C (bb5fafa9)] Calling AppiumDriver.getScreenshot() with args: ["bb5fafa9-acb6-4a87-9926-8d8fdd25b15a"]
[debug] [XCUITest] Executing command 'getScreenshot'
[debug] [WD Proxy] Matched '/elements' to command name 'findElements'
[debug] [WD Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/FA768B15-82BB-45DF-B011-5C130929DE35/elements] with body: {"using":"accessibility id","value":"Main Menu"}
[HTTP] --> DELETE /wd/hub/session/bb5fafa9-acb6-4a87-9926-8d8fdd25b15a
[HTTP] {}
[debug] [W3C (bb5fafa9)] Calling AppiumDriver.deleteSession() with args: ["bb5fafa9-acb6-4a87-9926-8d8fdd25b15a"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1565226142145 (21:02:22 GMT-0400 (Eastern Daylight Time))
[Appium] Removing session bb5fafa9-acb6-4a87-9926-8d8fdd25b15a from our master session list
[debug] [WD Proxy] Matched '/session/bb5fafa9-acb6-4a87-9926-8d8fdd25b15a' to command name 'deleteSession'
[debug] [WD Proxy] Proxying [DELETE /session/bb5fafa9-acb6-4a87-9926-8d8fdd25b15a] to [DELETE http://localhost:8100/session/FA768B15-82BB-45DF-B011-5C130929DE35] with no body
[debug] [WD Proxy] Got response with status 200: {"value":[],"sessionId":"FA768B15-82BB-45DF-B011-5C130929DE35","status":0}
[debug] [BaseDriver] Waited for 29531 ms so far
[debug] [WD Proxy] Matched '/elements' to command name 'findElements'
[debug] [WD Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/FA768B15-82BB-45DF-B011-5C130929DE35/elements] with body: {"using":"accessibility id","value":"Main Menu"}
[debug] [WD Proxy] Got response with status 200: {
[debug] [WD Proxy]   "value" : {
[debug] [WD Proxy] 
[debug] [WD Proxy]   },
[debug] [WD Proxy]   "sessionId" : "7689BB3D-BE6F-4FA3-99EC-4782D21ACF3C",
[debug] [WD Proxy]   "status" : 0
[debug] [WD Proxy] }
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down xcodebuild process (pid 44623)
[debug] [WD Proxy] Got response with status 200: {"value":"Session does not exist","sessionId":"7689BB3D-BE6F-4FA3-99EC-4782D21ACF3C","status":6}
[WD Proxy] Got an unexpected response: {"value":"Session does not exist","sessionId":"7689BB3D-BE6F-4FA3-99EC-4782D21ACF3C","status":6}
[debug] [MJSONWP] Matched JSONWP error code 6 to NoSuchDriverError
[debug] [XCUITest] Taking screenshot with WDA
[debug] [WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
[debug] [WD Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/FA768B15-82BB-45DF-B011-5C130929DE35/screenshot] with no body
[debug] [W3C (bb5fafa9)] Responding to client with driver.findElements() result: []
[HTTP] <-- POST /wd/hub/session/bb5fafa9-acb6-4a87-9926-8d8fdd25b15a/elements 200 30550 ms - 12
[HTTP] 
[debug] [WD Proxy] Got response with status 200: {
[debug] [WD Proxy]   "value" : "Session does not exist",
[debug] [WD Proxy]   "sessionId" : "7689BB3D-BE6F-4FA3-99EC-4782D21ACF3C",
[debug] [WD Proxy]   "status" : 6
[debug] [WD Proxy] }
[WD Proxy] Got an unexpected response: {"value":"Session does not exist","sessionId":"7689BB3D-BE6F-4FA3-99EC-4782D21ACF3C","status":6}

I also tried browser.saveScreenshot('/path.png') but it does not take screenshot after test fail.

**Comment by mgrybyk** [comment]
Known issue, will be fixed with https://github.com/webdriverio/webdriverio/pull/4288
