### ISSUE TITLE
`browser.getCookies([...])` does not work in IE 11. 

### ISSUE THREAD

**Issue by tung-dang** [webdriverio/webdriverio#4336]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [^5.11.7]
 - **Node.js version:** [10.15.3]
 - **NPM version:** [6.4.1]
 - **Mode:** [using BrowserStack]
 - **Browser name and version:** [IE 11]
 - **Platform name and version:** [Windows 10]

**Config of WebdriverIO**

**Describe the bug**

I have this code to get a cookie value by name
```
 static async getToken() {
    try {
      const token = await browser.getCookies([
        'session.token',
      ]);

      return cloudToken.length ? cloudToken[0].value : '';
    } catch (e) {
      console.error('ERROR in getCloudToken', e);
    }

    return '';
  }
```

It works in other browsers: 

```
capabilities: [
    // capabilities.IE11,
    capabilities.EDGE,
    capabilities.FIREFOX,
    capabilities.SAFARI,
    capabilities.CHROME,
  ],
```

But it does not work in IE 11 with the capability of IE 11 is :

```

capabilities.IE11 ={ 
    os: 'Windows',
    os_version: '10',
    browserName: 'IE',
    browser: 'IE',
    browser_version: '11.0',
    project: 'PTC webdriver tests',
    name: 'WIN_IE11',
    platform: 'Windows 10',
    'browserstack.ie.enablePopups': true,
    'browserstack.debug': true,
    resolution: '1280x1024',
    build: 'webdriver-browserstack',
    acceptSslCerts: true,
    'browserstack.local': false 
} 
```

- `browser.getCookies([...])` just returns an empty array `[]` in IE 11. 
- If I run `browser.getCookies([...]))` after finishing log-in process, `browser.getCookies([...])` throws an exception: 

```
 [0-0] TypeError in "User profile page loads and renders"
 | allCookies.filter is not a function
 | [0-0] FAILED in IE - /test/webdriver/profilepage.test.js
```

**To Reproduce**

- Use `browser.getCookies()` to read a cookie which is set by a production app and the cookie has HttpOnly flag

**Expected behavior**
- `browser.getCookies([...])` should return correct cookie value like other browsers.

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

- I tried this code and *only* IE 11 returns `[ null, null, null, null, null ]`. But in other browsers, the code returns a correct value.

```
const localStorage = await browser.execute(function() {
 return window.localStorage;
});
 console.log('==================localStorage', localStorage);
```

> Please use the correct markdown

**Comment by mgrybyk** [comment]
works fine for me
```
browser.addCookie({ name: 'foo', value: 'bar' })
browser.getCookies()
```

**Comment by tung-dang** [comment]
@mgrybyk it works for me if I use WD API to add cookies than read the cookie. But it does not work for me when trying to get cookie which is set in our prod app. I am doubting that cookie I try to get is HttpOnly which it's impossible to read it from JS. I will try my assumption today.

**Comment by tung-dang** [comment]
As I said in the above comment. `browser. getCookies` cannot read cookie which has HttpOnly flag.

**Comment by mgrybyk** [comment]
You can always use `execute` and get whatever needed with javascript

**Comment by mgrybyk** [comment]
@tung-dang do you know any site that uses HttpOnly so I can reproduce the defect?

**Comment by mgrybyk** [comment]
this is not an issue of webdriverio, you may submit a ticket to iedriver
