### ISSUE TITLE
Add unit tests for @wdio/cli

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4339]
**Is your feature request related to a problem? Please describe.**
I'd like to add tests for @wdio/cli, these files in particular:
- `setup.js`
- `config.js`
- and `run` function in `run.js`

**Describe the solution you'd like**
Currently most of the functions are marked with `/* istanbul ignore next */`. 
We have to remove that and test all that functions.

**Comment by baruchvlz** [comment]
I have added some tests to wdio-cli packages here #4402.

**Comment by christian-bromann** [comment]
Thanks @baruchvlz , I think we can close this now.
