### ISSUE TITLE
chromedriver version >= 75 doesn't support browser.setLocalStorage command

### ISSUE THREAD

**Issue by BelovAleksey** [webdriverio/webdriverio#4340]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [5.11.13]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [10.16.0]
 - **NPM version:** [6.9.0]
 - **Browser name and version:** [Chrome 76]
 - **Platform name and version:** [macOs mojave 10.14.6]
 - **Additional wdio packages used (if applicable):** [
    "@wdio/cli": "5.11.2",
    "@wdio/local-runner": "5.11.13",
    "@wdio/mocha-framework": "5.11.0",
    "@wdio/spec-reporter": "5.11.7",
    "@wdio/sync": "5.11.13"]

**Config of WebdriverIO**
hostname: 'localhost',
  services: ['selenium-standalone'],
  capabilities: [
    {
      browserName: 'chrome',
      'goog:chromeOptions': {
        args: ['--no-sandbox']
      }
    }
  ],
  mochaOpts: {
    ui: 'bdd',
    require: ['tsconfig-paths/register'],
    timeout: 600000,
    retries: 0
  },
  seleniumArgs: {
    version: "3.141.5",
    drivers: {
      chrome: {
        version: "76.0.3809.68",
        arch: process.arch,
      }
    }
  },
**Describe the bug**
When I try to run command browser.getLocalStorage() command I see error for chromedriver "76.0.3809.68"... But If I delete  seleniumArgs options it works correctly, because default version for selenium-standalone is 2.43...

browser.getLocalStorageItem is not a function
[chrome  mac os x #0-0] TypeError: browser.getLocalStorageItem is not a function

[Include code or an example repository that can easily be set up]

**Expected behavior**
getLocalStorageItem is recognized correctly

**Step to Reproduce**
I suppose to reproduce this bug you should use Chrome 75 or 76, and add 
 seleniumArgs: {
    version: "3.141.5",
    drivers: {
      chrome: {
        version: "76.0.3809.68",
        arch: process.arch,
      }
    }
  },
when you use 
services: ['selenium-standalone'],

**Comment by mgrybyk** [comment]
That's not an issue of wdio, chrome switched to w3c protocol, use browser execute, and get whatever needed from DOM.
Additionally you may overwrite local storage commands with your implementation.

**Comment by mgrybyk** [comment]
Examples
```
browser.execute(function () {
    this.localStorage.clear()
})
browser.execute(function (key) {
    this.localStorage.getItem(key)
}, 'foo')
browser.execute(function (key, value) {
    this.localStorage.setItem(key, value)
}, 'foo', 'bar')
```

See also

**Comment by BelovAleksey** [comment]
Thank You!

**Comment by mgrybyk** [comment]
You welcome, if you think that these commands should exist out of the box, you may submit a feature request / PR.
Then community will decide whether it makes sense or not
