### ISSUE TITLE
http request within onComplete hook fails

### ISSUE THREAD

**Issue by JJFrampton** [webdriverio/webdriverio#4341]
Using Nodejs and 'http' lib, requests within the "onComplete" hook do not fire while console logs before and after the request succeed. 'await' does not have any affect and the last line in the onComplete hook is 
`await global.server.finish()`
The awaiting server never gets the request.

**Comment by mgrybyk** [comment]
@JJFrampton can you please update ticket according to template and provide with reproducible example?
Most likely you have some error in your code and hook fails, the error might not be printed out depending on your logging configuration. Try setting it trace, if you writing logs to some folder see wdio.log.

Here is an example that works fine for me
```
// it might be also functions array
onComplete: async () => {
    const start = Date.now()
    console.log('onComplete pause start');
    // same as `await global.server.finish()` in your case
    await new Promise(resolve => setTimeout(resolve, 1000))
    console.log('onComplete', Date.now() - start, 'since start');
    await new Promise(resolve => setTimeout(resolve, 1000))
    console.log('onComplete', Date.now() - start, 'since start');
}
```
Output
```
onComplete pause start
onComplete 1005 since start
onComplete 2009 since start
```

**Comment by JJFrampton** [comment]
Yeah like I said, the hook fires and I can successfully use console log. The issue is specifically with making a "http" request within the onComplete hook. If you can successfully make a request, and confirm the reception of the request on the target server, please let me know.

    ```
onComplete: async function (exitCode, config, capabilities, results) {
        try {
            var http = require('http');
            console.log('BEFORE');
            await http.get({
              hostname: <server ip>,
              port: 8080,
              path: '/stop',
              agent: false
            }, (res) => {
              console.log('received response');
              let data = '';
              res.on('data', (chunk) => {
                data += chunk;
              });
              res.on('error', (err) => {
                console.log(err);
              });
              res.on('end', () => {
                console.log(JSON.parse(data).msg);
              });
            });
            console.log('AFTER');
```

**Comment by JJFrampton** [comment]
Looks like this issue was due to the fact that http lib does not return a promise which is needed for async/await.

**Comment by arifzaidi992** [comment]
Here is the solution for this issue.
- We can put required code which needs to be executed in a function along with seperate Test.js file 
- onComplete : Run Test.js using cmd with the help of ShellJS(Implementation of Unix shell commands on top of the Node.js API)

**Comment by arifzaidi992** [comment]
<img width="538" alt="Screenshot 2023-03-23 at 1 17 14 AM" src="https://user-images.githubusercontent.com/52001728/227019446-f03b0c81-9b34-4fdf-880f-fc5d2b82a405.png">

**Comment by arifzaidi992** [comment]
Here is the solution for this issue.
- We can put required code which needs to be executed(http) in a function along with seperate Test.js file.
- onComplete : Run Test.js using cmd with the help of ShellJS(Implementation of Unix shell commands on top of the Node.js API)

**Comment by arifzaidi992** [comment]
<img width="571" alt="Screenshot 2023-03-23 at 2 03 35 AM" src="https://user-images.githubusercontent.com/52001728/227031242-187da6d8-b96c-409c-9947-2dd7365da205.png">
