### ISSUE TITLE
Does all minor versions of webdriverio v5 require nodejs >=10.0.0 ?

### ISSUE THREAD

**Issue by pk-saxena** [webdriverio/webdriverio#4346]
The documentation says v5 requires nodejs version v8.11.2 or higher. But on building the project, I see an error that one of the dependency of wdio-sync, namely fibers 4.0.1 requires nodejs 10 or higher. Does any minor version of v5 supports running with nodejs < 10 ?

The `package.json` file in our project has following content
```
  "engines": {
    "node": ">=8.x",
    "yarn": ">=1.9.x"
  }
  "dependencies": {
    "@wdio/cli": "^5.11.0",
 }
  "devDependencies": {
    "@wdio/dot-reporter": "^5.11.0",
    "@wdio/local-runner": "^5.11.2",
    "@wdio/mocha-framework": "^5.11.0",
    "@wdio/selenium-standalone-service": "^5.11.2",
    "@wdio/spec-reporter": "^5.11.0",
    "@wdio/sync": "^5.11.0",
    "wdio-chromedriver-service": "^5.0.2",
    "webdriverio": "^5.11.0",
 }
```
As part of building the project on CI, we run the command:
`yarn install --frozen-lockfile`
On doing this, I see the error:
`error fibers@4.0.1: The engine "node" is incompatible with this module. Expected version ">=10.0.0". Got "8.16.0"`

yarn.lock file contains:
```
"@wdio/sync@^5.11.0":
  version "5.11.0"
  resolved "https://registry.yarnpkg.com/@wdio/sync/-/sync-5.11.0.tgz#aec0dfd75c8b1cc7a1de6276fa5fd66c9e8aad51"
  integrity sha512-YRrdmLtJaRvJV4h9Bg33oI90g8qbPFechLBGjq4cPEohJa+gIS3vabcyjZ7kvHxEST+/ITieSV/CNXnGA7u44w==
  dependencies:
    "@wdio/config" "^5.11.0"
    "@wdio/logger" "^5.11.0"
    fibers "^4.0.0"
```

**Comment by patthiel** [comment]
Encountered this as well. Mentioned in here: https://github.com/webdriverio/webdriverio/pull/4305

The CI build should have caught this, as it uses node8. 

I'm happy to submit a PR to downgrade Fibers to 3, which should make the project compatible with node 8 again. However, I do not know if there is specific stuff we want / need from Fibers ^4.

**Comment by mgrybyk** [comment]
I'd just drop node8

**Comment by mgrybyk** [comment]
closed due to https://github.com/webdriverio/webdriverio/pull/4356
