### ISSUE TITLE
wdio allure report support for multiple example

### ISSUE THREAD

**Issue by gtilekar** [webdriverio/webdriverio#4348]
@wdio/spec-reporter": "^5.11.7",
"@wdio/allure-reporter": "^5.11.0",
"@wdio/cli": "^5.11.12",
"@wdio/cucumber-framework": "^5.11.12",
"@wdio/local-runner": "^5.11.12",
"@wdio/selenium-standalone-service": "^5.11.2",
"@wdio/sync": "^5.11.0",
"@wdio/config": "^5.11.0",
"webdriverio": "^5.11.12",

Current the wdio allure report does not support multiple Cucumber examples with version 5.

Would be good to see that we can see report for scenario that has multiple examples.

Scenario Outline: Bar
Given User with is logged in

@first
Examples:
    | userId    | password |
    | 123       | pwd      |
    | 456       | pwd123   |
    | 456       | pwd123   |

Allure report shows only first example result.

**Comment by gtilekar** [comment]
![Screen Shot 2019-08-11 at 10 14 31](https://user-images.githubusercontent.com/52917254/62831518-109a4880-bc21-11e9-9977-6567a320b2cb.png)
![Screen Shot 2019-08-11 at 10 14 45](https://user-images.githubusercontent.com/52917254/62831519-12640c00-bc21-11e9-81e4-2861521c4546.png)



[wdioTest.zip](https://github.com/webdriverio/webdriverio/files/3489683/wdioTest.zip)


@mgrybyk  I have attached screenshot of allure report & Test Project

**Comment by gtilekar** [comment]
@mgrybyk this looks actually like a defect with useCucumberStepReporter. Only report for last example is shown. useCucumberStepReporter is not able to add multiple examples to report with below allure options. 

       disableWebdriverStepsReporting: false,
        disableWebdriverScreenshotsReporting: false,
        useCucumberStepReporter: true,

**Comment by jpaolini** [comment]
I had the same issue and was able to use a workaround to get past it for the short term.  In the `afterScenario` cucumber hook, I added `allureReporter.addArgument('timestamp', Date.now());`.  

The other option I looked at was to write the example scenario like

```
Scenario Outline: Bar <userId>
Given User with is logged in
Examples:
| userId | password |
| 123 | pwd |
| 456 | pwd123 |
| 456 | pwd123 |
```

This will make each scenario that is created unique and won't have them overwritten.  For now I went with the first approach of the timestamp since I already had a lot of tests written.

**Comment by gtilekar** [comment]
@jpaolini Thanks...That worked for me. :)

**Comment by BorisOsipov** [comment]
>this looks actually like a defect with useCucumberStepReporter. Only report for last example is shown. 

@gtilekar it is not a defect. Rest of scenarios are displayed on `retries` tab. It is allure standard behaviour for test with the same attributes. As @jpaolini mentioned you have to make scenarios unique somehow e.g. add params from examples to scenario outline section.

**Comment by grpratap69** [comment]
Hi.... can anyone tell me why 2 allure output result.xml getting created when a feature file consists of 2 scenario. actually i need 1 common xml for entire run... Using Cucumber js framework with wdio

**Comment by mgrybyk** [comment]
Thats how allure reporter works. Why do you need single xml file? It doesn't matter how many xml files are generated
