### ISSUE TITLE
@wdio/devtools-service": "5.11.13" return timeToFirstByte: NaN

### ISSUE THREAD

**Issue by rdpanek** [webdriverio/webdriverio#4349]
**Environment (please complete the following information):**
 - **WebdriverIO version:** "webdriverio": "5.9.4"
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running** sync
 - **Node.js version:** v11.10.1
 - **NPM version:** 6.7.0
 - **Browser name and version:** Chrome 76.0.3809.100
 - **Platform name and version:** OSX 10.14.5
 - **Additional wdio packages used (if applicable):** 
    "@babel/cli": "7.2.3",
    "@babel/core": "7.4.0",
    "@babel/preset-env": "7.4.2",
    "@babel/register": "7.4.0",
    "@wdio/cli": "5.9.4",
    "@wdio/devtools-service": "5.11.13",
    "@wdio/local-runner": "5.9.4",
    "@wdio/mocha-framework": "5.9.4",
    "@wdio/spec-reporter": "5.7.2",
    "@wdio/sync": "5.9.4",
    "aws-sdk": "2.0.9",
    "chai": "4.2.0",
    "node-uuid": "1.4.8",
    "webdriverio": "5.9.4"

**Config of WebdriverIO**
services: ['devtools', {debuggerAddresss: 'localhost:9222'}]

**Describe the bug**
output method `browser.getMetrics()` return
```
{ estimatedInputLatency: 16,
  timeToFirstByte: NaN,
  domContentLoaded: 2013,
  firstVisualChange: 1748,
  firstPaint: 1729,
  firstContentfulPaint: 1729,
  firstMeaningfulPaint: 2080,
  lastVisualChange: 12000,
  firstCPUIdle: 2328,
  firstInteractive: 2328,
  load: 2359,
  speedIndex: 2167 }
```

**Expected behavior**
`timeToFirstByte` return some value`ms`

> Please use the correct markdown

**Comment by mgrybyk** [comment]
will be fixed with https://github.com/webdriverio/webdriverio/pull/4350
