### ISSUE TITLE
Add proxy capabilitie to webdriverio

### ISSUE THREAD

**Issue by mcortinas** [webdriverio/webdriverio#435]
Hi,
 I think it could be interesting if we could add proxy setting from node-webdriverio to apply it.
 Furthermore, if it let us use proxy with authentification it will be better
Marc

**Comment by christian-bromann** [comment]
Haven't heard about a project called `node-webdriverio`. I already started a project called [proxo](https://github.com/webdriverio/proxo) to do network analysis stuff but haven't got a change to actually work on that. Check out [browsermob-node](https://github.com/zzo/browsermob-node). They got that working. Also this [issue](https://github.com/webdriverio/webdriverio/issues/251) could interest you.

Cheers
