### ISSUE TITLE
Update @wdio/applitools-service with command to take region snapshot.

### ISSUE THREAD

**Issue by crutledgejr** [webdriverio/webdriverio#4355]
**Is your feature request related to a problem? Please describe.**
I am unable to take a region-based snapshot with the applitools-serivce. I would like to be able to do so.

**Describe the solution you'd like**
Update the *index.js* of *@wdio/applitools-service* to add a command in the *before* function that takes a region snapshot based on parameters *title* and *region*.

**Describe alternatives you've considered**
1) Updating the current command to take both suggested params and only take region snapshot if *region* parameter is neither *null* or *undefined*.
2) Use Applitools SDK directly to achieve this if *@wdio/applitools-service* is not an option.

**Additional context**
N/A

**Comment by christian-bromann** [comment]
This was merged and will go into the next release.
