### ISSUE TITLE
When crashed, the chromedriver is still running

### ISSUE THREAD

**Issue by binarykitchen** [webdriverio/webdriverio#436]
I figured out that when a fatal error occured in the middle of my tests, i.E. a TypeError, then it crashes of course. But the `ps -aux | grep selenium` command has shown that the Selenium instance is still running.

So I put this ugly hack in my Gulp:

```coffee
process.on 'exit', ->
  if seleniumProcess then seleniumProcess.kill()
```

and that solved. But there is still one process remaining: the chromedriver!

```
/node_modules/selenium-standalone/.selenium/chromedriver/2.14-x64-chromedriver --port=16277
```

How can I kill it as well? Why isn't selenium killing it?

**Comment by christian-bromann** [comment]
WebdriverIO isn't supposed to close any of these processes. It is better to have a different workflow for starting and closing Selenium. Check out [selenium-standalone](https://github.com/vvo/selenium-standalone) for example. In generell the standalone server picks up running chromedriver sessions and closes them after a while.

**Comment by binarykitchen** [comment]
Right, sorry. Moving this issue here https://github.com/vvo/selenium-standalone/issues/72

**Comment by intergleam** [comment]
it doesn't seem to be "closing them after a while"
