### ISSUE TITLE
wdio cucumber json report shows screenshot as broken image in html report

### ISSUE THREAD

**Issue by gtilekar** [webdriverio/webdriverio#4366]
"devDependencies": {
    "@wdio/allure-reporter": "^5.12.1",
    "@wdio/cli": "^5.12.1",
    "@wdio/config": "^5.12.1",
    "@wdio/cucumber-framework": "^5.12.1",
    "@wdio/local-runner": "^5.12.1",
    "@wdio/selenium-standalone-service": "^5.12.1",
    "@wdio/spec-reporter": "^5.12.1",
    "@wdio/sync": "^5.12.1",
    "allure-commandline": "^2.9.0",
    "multiple-cucumber-html-reporter": "^1.12.0",
    "wdio-cucumberjs-json-reporter": "^1.0.8",
    "webdriverio": "^5.12.1"
  }
}

feature file
Feature: Example feature

  Scenario Outline: Get title of website
    Given I go on the website "<website>"
    
    Examples:
    |website|
    |www.google.com|
    |www.github.com|
    |www.gmail.com|

stepdef file:

var assert = require('assert')
const { Given, When, Then } = require('cucumber')
const cucumberJson = require('wdio-cucumberjs-json-reporter').default

Given(/^I go on the website "([^"]*)"$/, (url) => {
    browser.url(url)
    cucumberJson.attach(browser.saveScreenshot('Test.png'), 'image/png')
})

wdio.conf
onComplete: function() {
        generate({
    
      jsonDir: '.tmp/json/',
      reportPath: '.tmp/report/',
    });
    },

Report Screenshot:
![Screen Shot 2019-08-15 at 12 59 10](https://user-images.githubusercontent.com/52917254/63090766-963d3180-bf5c-11e9-8606-cff3d8c4c605.png)

**Comment by christian-bromann** [comment]
Please report this issue in the `wdio-cucumberjs-json-reporter` project. Thanks!
