### ISSUE TITLE
Propagate Rejections in Promise Chain

### ISSUE THREAD

**Issue by mminder** [webdriverio/webdriverio#437]
Rejections in promise chains are not propagated if a thenResolver has been defined somewhere in the chain. This is really confusing, especially when comparing the webdriver.io promise api with popular apis like Q. 

Example:
```
var promise = webdriver.getText('.my-item') //selector .my-item does not match any element
  .then(function (text) {
    assert(text, 'expectedText');
  }); // I do not care about rejections in this place. They should be handled later.

promise.catch(function(error){
  // I would expect catch to be called with a NoSuchElement error
  // however it is not called. only if i do not specify the .then( handler above, catch gets called.
});
```
See this plunker for how Q handles this situation: http://jsfiddle.net/nad07tvh/

Another example:
```
var promise = webdriver.getText('.my-item') //selector .my-item does not match any element
  .then(function (text) {
    assert(text, 'expectedText');
  }, function (error) {
    // error is a NoSuchElement error
    throw error; //even if an error is thrown here
  });

promise.catch(function (error) {
  // the succeeding catch handler is not called
});

promise.then(function () {
   // instead we get here
}, function (error) {
  // neither a succeeding reject handler
});
```

**Sidenote:** Why am I even chaining the webdriver promise in such a way?
In my project we wrote a mocha DSL which enables us to report test errors in a generic way:
```
describeStep('text should be correct', function () {
  return webdriver.getText('.my-item')
    .then(function (text) {
      assert(text, 'expectedText');
    });
});
```
The .then and .catch handlers are defined in the DSL defining describeStep. Promise rejections lead to screenshots and error md files which help us debug errors in our CI environment.

**Comment by christian-bromann** [comment]
Promises are emulated in WebdriverIO as it actually is a callback based framework. There is still a lot of work to make promises 100% functional. How about asserting the results using callbacks?

```js
describeStep('text should be correct', function (done) {
    webdriver.getText('.my-item', function (text) {
        assert(text, 'expectedText');
    })
    .call(done);
});

**Comment by mminder** [comment]
For our error reporting it is much nicer if we can use a promise chain. For now I wrap the webdriver calls with Q.nbind whenever I need them in promise chains.

```
var getTextQ = Q.nbind(webdriver.getText, webdriver);
```

**Comment by christian-bromann** [comment]
@mminder this will be fixed in `v3` as we using proper Promises here.
