### ISSUE TITLE
Cucumber scenario hook parameter return [{...}, [Function]] in 5.12.1

### ISSUE THREAD

**Issue by kwokfu** [webdriverio/webdriverio#4370]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.12.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.8.0
 - **NPM version:** 6.10.3
 - **Browser name and version:** Chrome 76
 - **Platform name and version:** macOS 10.14.6
 - **Additional wdio packages used (if applicable):** @wdio/cucumber-framework

**Config of WebdriverIO**
Generic with `cucumberOpts`.

```javascript
{
  specs: ['./features/**/*.feature'],
  framework: 'cucumber',
  cucumberOpts: {
    backtrace: true,
    requireModule: [],
    require: ['./src/step/**/*'],
    dryRun: false,
    failFast: false,
    format: ['pretty'],
    colors: true,
    snippets: true,
    source: true,
    profile: [],
    strict: true,
    tagExpression: 'not (@draft or ignore)', // https://cucumber.io/docs/cucumber/api/#tag-expressions
    timeout: 60000,
    ignoreUndefinedDefinitions: true
  }
}
```

**Describe the bug**
Tests starting to fail miserably after updating to `5.12.1` .

1. `scenario` was `HookScenarioResult` prior to `5.12.1`, and now it is `[{...}, [Function]]`.

**To Reproduce**
Snippet that will log `scenario` as `[]`, hence can't direct access to `scenario.pickle.tags`.

```javascript
Before(function(scenario) {
  console.log(scenario)
});
```

**Expected behavior**
Expecting `scenario` to be `HookScenarioResult`.

**Log**
Following is the console log for `scenario` after `5.12.1`.

```javascript
[
  {
    sourceLocation: { uri: 'features/Sign Up.feature', line: 21 },
    pickle: {
      tags: [Array],
      name: 'Successfully sign up',
      language: 'en',
      locations: [Array],
      steps: [Array]
    }
  },
  [Function]
]
```

**Comment by nextlevelbeard** [comment]
@kwokfu this is to be fixed by https://github.com/webdriverio/webdriverio/pull/4367

**Comment by mgrybyk** [comment]
that's correct, already fixed by that PR

**Comment by christian-bromann** [comment]
Let's continue convo there
