### ISSUE TITLE
How to get Browser logs in Firefox ?

### ISSUE THREAD

**Issue by SanthoshBonala** [webdriverio/webdriverio#4371]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.11.13
 - **Mode:** Standalone mode
 - **If WDIO Testrunner, running sync/async:**async
 - **Node.js version:** 8.11.2
 - **NPM version:** 5.8.0
 - **Browser name and version:** firefox 68.2
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):**  @wdio/spec reporter, @wdio/selenium-standalone service

**Describe the bug**
Unable to get browser logs as described over [here](https://github.com/mozilla/geckodriver/issues/1596)

Do you have any workaround as described [here](https://github.com/webdriverio/webdriverio/issues/4297)

**Expected behavior**
Should receive browser logs as a response

**Comment by mgrybyk** [comment]
Assuming you are using sync mode.
```
browser.url("http://adam.goucher.ca/parkcalc/")
const logTypes = browser.getLogTypes()
logTypes.forEach(logType => {
    console.log(browser.getLogs(logType))
})
```
sample output
```
[0-0] [ { level: 'SEVERE',
    message:
     'http://adam.goucher.ca/parkcalc/NavImages/spacer.gif - Failed to load resource: the server responded with a status of 404 (Not Found)',
    source: 'network',
    timestamp: 1565994394829 } ]
[0-0] []
```

Please use gitter for such questions

**Comment by SanthoshBonala** [comment]
I think its working fine in chrome.
In firefox the protocol command getLogtypes() is not available at all.
How can we specify what protocol we would like to use in firefoxoptions ? 
Are you using firefox ?
Thanks in advance

**Comment by pmerwin** [comment]
I reproduced this. only works on chrome.

**Comment by SanthoshBonala** [comment]
Debugged the issue and found that firefox loads webdriver protocol by default. The solution could be
1. specify a param in firefox options so that driver loads jsonwireprotocol (unsure whether some parameter like this exists or not). similar to the solution specified over [here](https://github.com/webdriverio/webdriverio/issues/4297)
2. Specifying the required bindings in webdriver.json. Tried this but got only "server" as response for getLogTypes() (Note: no browser logs avaialble)
3. Introduce a new protocol file for firefox and load it using some switch (like we load chromium.json)
However even after adding the bindings also we cannot get browser logs.
Awaiting for @mgrybyk response
Thanks

**Comment by christian-bromann** [comment]
> 1. specify a param in firefox options so that driver loads jsonwireprotocol

This doesn't help if the driver doesn't the jsonwire protocol.

> 2\. Specifying the required bindings in webdriver.json

Not sure what you mean by that.

> 3\. Introduce a new protocol file for firefox and load it using some switch (like we load chromium.json)

Again, Geckodriver afaik doesn't support the log command.
