### ISSUE TITLE
On Jenkins (Linux), $ command is returning Promise { <pending> } instead of Element

### ISSUE THREAD

**Issue by wluu** [webdriverio/webdriverio#4372]
**Environment:**
 - **WebdriverIO version:** 5.12.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.15.3
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome 75
 - **Platform name and version:** Linux  x86_64; sorry, this is a jslave on our aws instance and I don't have full access to it.
 - **Additional wdio packages used (if applicable):** 
"@wdio/cli": "5.12.1",
"@wdio/jasmine-framework": "5.12.1",
"@wdio/local-runner": "5.12.1",
"@wdio/selenium-standalone-service": "5.12.1",
"@wdio/spec-reporter": "5.12.1",
"@wdio/sync": "5.12.1"

**Config of WebdriverIO**
```
exports.config = {
    specs: [
        './specs/**/foo.spec.js'
    ],

    capabilities: [
        {
            maxInstances: 4,
            browserName: 'chrome'
        }
    ],

    runner: 'local',

    // ===================
    // Test Configurations
    // ===================
    // Define all options that are relevant for the WebdriverIO instance here
    //
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    logLevel: 'silent',

    coloredLogs: false,

    // If you only want to run your tests until a specific amount of tests have failed use
    // bail (default is 0 - don't bail, run all tests).
    bail: 0,

    // Default timeout for all waitFor* commands.
    waitforTimeout: 15 * 1000,

    // Default timeout in milliseconds for request
    // if Selenium Grid doesn't send response
    connectionRetryTimeout: 90000,

    // Default request retries count
    connectionRetryCount: 3,

    // Test runner services
    // Services take over a specific job you don't want to take care of. They enhance
    // your test setup with almost no effort. Unlike plugins, they don't add new
    // commands. Instead, they hook themselves up into the test process.
    services: ['selenium-standalone'],

    // Test reporters.
    // For stdout: spec
    reporters: ['spec'],

    // Test framework
    framework: 'jasmine',

    // Options to be passed to Jasmine.
    jasmineNodeOpts: {
        // Jasmine default timeout
        defaultTimeoutInterval: 5 * 60 * 1000
    }
};
```

**Describe the bug**
On our Jenkins, with above configuration and where our automation suite runs nightly, `$` command will return `Promise { <pending> }` instead of `Element`. Interestingly, we do not see this issue on our macOS Mojave 10.14.6.

It was working with wdio 5.7.15 on node 8.10.0 and npm 5.6.0. Here are the wdio packages for this setup:

"@wdio/cli": "5.7.15",
"@wdio/jasmine-framework": "5.7.13",
"@wdio/local-runner": "5.7.15",
"@wdio/selenium-standalone-service": "5.7.8",
"@wdio/spec-reporter": "5.7.13",
"@wdio/sync": "5.7.13",

**To Reproduce**
```
describe('foo', () => {
    beforeAll(() => {
        browser.url('https://webdriver.io');
    });

    it('bar', () => {
        console.log('####', $('.headerTitle'));
        $('.headerTitle').waitForExist();
    });
});
```

**Expected behavior**
`Element` should be returned instead of Promise.

**Log**
https://gist.github.com/wluu/b86ec9903b18c53f3f66ea4200091d94

**Comment by mgrybyk** [comment]
If it works for you locally, how can I reproduce this one?
Are you deleting node nodules folder on jenkins? Maybe something is cached?
Maybe fibers package is not installed there properly?

**Comment by wluu** [comment]
@mgrybyk The only time we delete the `node_modules` folder is during the checkout of our repo; the  `Clean before checkout` step in Jenkins.

For caching, I've just added `npm cache verify` in the shell script to see if that will help, but I still get the reproducible bug.  And it seems like (I think) the fibers package is installed correctly; I see the `Installing fibers v4` entry in the logs and no other errors after that.

I've updated my log link to show the `npm cache verify` command and `npm install --verbose`.

Also, I'll try adding the temporary fibers package when I'm back in the office on Monday (PST). Should I be using this fibers: https://github.com/webdriverio/node-fibers or this one: https://github.com/laverdet/node-fibers ?

**Comment by mgrybyk** [comment]
Nodejs 10 https://github.com/laverdet/node-fibers

Nodejs 8 https://github.com/webdriverio/node-fibers

**Comment by mgrybyk** [comment]
Please try latest version of webdriverio, it should be fixed.
Feel free to reopen if it is still reproducible

**Comment by wluu** [comment]
@mgrybyk Can still reproduce with `"@wdio/sync": "5.12.3"`; updated the log link with latest logs.

**Comment by mgrybyk** [comment]
Have you tried to delete package lock json and node modules folder, and then install packages?

**Comment by wluu** [comment]
Yup, still the same issue.

**Comment by mgrybyk** [comment]
That's strange, what if you install fibers?

**Comment by mgrybyk** [comment]
Are you sure you have updated all the modules? There were no wdio sync related changes last couple of releases, only an attempt to make fibers work with all the nodejs versions

**Comment by wluu** [comment]
Yup, pretty sure the modules are updated because in our Jenkins, it cleans out the workspace first before running `npm install`. 

Also, I tried adding fibers package and I get this error in the logs: https://gist.github.com/wluu/246270289965e4144dc9476173409579

**Comment by mgrybyk** [comment]
So, you have to fix your build system to be capable to install fibers

**Comment by mgrybyk** [comment]
There is even message in logs saying what to do `sudo apk add python make g++`

**Comment by wluu** [comment]
Thanks @mgrybyk for looking into this. I'll coordinate with my Jenkins team to get my build system in proper order before installing fibers.
