### ISSUE TITLE
Cannot read property 'status' of undefined of Cucumber step result

### ISSUE THREAD

**Issue by senovsky** [webdriverio/webdriverio#4373]
**Environment:**
 - **WebdriverIO version:** 5.12.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.16.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Chrome 76.0.3809.100
 - **Platform name and version:** Window Server 2012 6.2.9200
 - **Additional wdio packages used (if applicable):** [Cucumber boilerplate](https://github.com/webdriverio/cucumber-boilerplate) with chromedriver service

**Config of WebdriverIO**
local runner, tests run only in Chrome via chromedriver (Selenium-less)
`wdio-cucumberjs-json-reporter` v1.0.8 used to generate CucumberJS JSON
```
afterStep: function (uri, feature, scenario, step, result) {
    const cucumberJson = require('wdio-cucumberjs-json-reporter').default;
    if (result.status === 'failed') {
        cucumberJson.attach(browser.takeScreenshot(), 'image/png');
    }
},
```

**Describe the bug**
When I run this configuration on my laptop with Windows 10 Pro 1903 (with the same versions of Node.js and NPM), everything works fine. However, once it's run on a Window Server 2012 6.2.9200, the property `status` of `result` becomes unavailable. So the screenshots aren't taken.

**To Reproduce**
[Cucumber boilerplate](https://github.com/webdriverio/cucumber-boilerplate) run on Windows 6.2.9200 (UAC set to Never notify) with the described config.

**Expected behavior**
I'd like the property `status` of `result` to be available, to know if the cucumber step passed or failed.

**Log**
```
[0-0] 2019-08-17T09:24:18.210Z ERROR @wdio/sync: TypeError: Cannot read property 'status' of undefined
    at Object.afterStep (C:\GitLab-Runner\builds\path\to\repo\e2e\wdio.conf.js:265:20)
    at execHook (C:\GitLab-Runner\builds\path\to\repo\e2e\node_modules\@wdio\sync\build\executeHooksWithArgs.js:30:23)
[0-0] Error in "AfterStep Hook"
Cannot read property 'status' of undefined
```

**Comment by mgrybyk** [comment]
You have passed wrong args, see how it should be https://github.com/webdriverio/webdriverio/blob/0f0c612413f8216db3fe19cb7dba7e877e470187/packages/wdio-cucumber-framework/cucumber-framework.d.ts#L28

**Comment by mgrybyk** [comment]
We need to update boilerplate plate https://github.com/webdriverio/cucumber-boilerplate/issues/278
