### ISSUE TITLE
Wrong typings in VSCode for sync testrunner

### ISSUE THREAD

**Issue by Volcomix** [webdriverio/webdriverio#4376]
**Environment**
 - **WebdriverIO version:** 5.12.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 11.15.0
 - **NPM version:** 6.10.3
 - **Browser name and version:** electron 6.0.2 (Chromium 76.0.3809.110)
 - **Platform name and version:** Linux 5.2.9-arch1-1-ARCH
 - **Additional wdio packages used (if applicable):** wdio-chromedriver-service 5.0.2

**Config of WebdriverIO**
```js
const electronPath = require('electron')

exports.config = {
  runner: 'local',
  path: '/',
  specs: ['**/*[sS]pec.js'],
  exclude: ['node_modules/**'],
  maxInstances: 10,
  capabilities: [
    {
      maxInstances: 5,
      browserName: 'chrome',
      'goog:chromeOptions': {
        binary: electronPath,
        args: [`app=${__dirname}`],
      },
    },
  ],
  logLevel: 'info',
  bail: 0,
  baseUrl: 'http://localhost',
  waitforTimeout: 10000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  services: ['chromedriver'],
  framework: 'jasmine',
  reporters: ['spec'],
  jasmineNodeOpts: {
    defaultTimeoutInterval: 60000,
    expectationResultHandler: function(passed, assertion) {},
  },
}
```

**Describe the bug**
In VSCode, the intellisense displays the async version of typings, meaning it uses the definition file from `node_modules/webdriverio` instead of `node_modules/@wdio/sync`.

![image](https://user-images.githubusercontent.com/7324857/63225566-972ac900-c1d1-11e9-83aa-39d32dc3186f.png)

After reviewing the documentation, I cannot find a clean way to setup VSCode intellisense for a JavaScript project.

**To Reproduce**
Here is an example spec file: https://github.com/volcomix/youtube-music/blob/master/main.spec.js
You can reproduce the issue by cloning the repo: https://github.com/volcomix/youtube-music

**Expected behavior**
The intellisense should find the right definition file. It might be some IDE configuration to add and describe in the documentation or maybe we can find a way to avoid downloading 2 definition files for the same js module.

**Log**
Not relevant because the issue is related to IDE usage. Everything works fine with the test runner.

**Comment by mgrybyk** [comment]
If you use sync version typings are in wdio sync. Otherwise in webdriverio. 
You have to use either sync mode or async. 

So, you have to add either @wdio sync to your types or webdriverio

**Comment by Volcomix** [comment]
Are you referring to the `types` property of the `tsconfig.json` file?
Isn't this file for TypeScript projects only?

Actually my issue happens in a JavaScript project. VSCode seems to ignore the `tsconfig.json` in js projects (unless I have a totally wrong config).

**Comment by mgrybyk** [comment]
Types have to be ignored in non ts project. Avoid importing wdio sync if you are not using it

**Comment by Volcomix** [comment]
I don't import `@wdio/sync` in my code but `browser` and `$` are globally declared variables which I use in my spec file.
VSCode provides intellisense for JavaScript projects by discovering `*.d.ts` files in `node_modules`. In my case, I just followed the basic getting started from [the documentation](https://webdriver.io/docs/gettingstarted.html). After following this getting started, VSCode has 2 possible definition files to autocomplete `browser` and `$` variables, which are in `node_modules/webdriverio` and `node_modules/@wdio/sync`.
It obviously uses the former which would be really misleading when developing complex e2e tests in a JavaScript project.

**Comment by Volcomix** [comment]
FYI, I achieved to have the Intellisense showing up the correct typings by adding a `jsconfig.json` file with the following content (volcomix/youtube-music@025d7bd):
```json
{
  "include": ["*.js", "node_modules/@wdio/sync/*.d.ts"]
}
```
> "*.js" refer to the js files in the root directory of my project only, it will not be suitable for most of real projects.
