### ISSUE TITLE
How to get failed step description

### ISSUE THREAD

**Issue by tamil777selvan** [webdriverio/webdriverio#4377]
Hi, i have an issue in getting the failed step description by using afterStep hook.

Previously i used below snippet to get the failed step description, but when i updated wdio to latest i couldn't able to get the step description as the args has been updated.
config.afterStep = function (uri, feature, scenario, step, result) {
        console.log('Failed step -- ', step.keyword + step.text)
    };

Environment:
WebdriverIO version: 5.12.1
Mode: WDIO Testrunner
If WDIO Testrunner, running sync/async: sync
Node.js version: 8.12.0
NPM version: 6.10.3
Browser name and version: Chrome 76.0.3809.100
Platform name and version: Mac 10.13.4

**Comment by christian-bromann** [comment]
We made some changes to the Cucumber hooks (see https://github.com/webdriverio/webdriverio/pull/4288/files).

**Comment by mgrybyk** [comment]
There is no way to get step this way anymore.
If you want to print failed step description you may build a custom reporter, see https://github.com/webdriverio/webdriverio/pull/4361
See also https://github.com/webdriverio/webdriverio/blob/34c7623d683b4e94cf7cbcb4eb6cb2798210be7b/packages/wdio-cucumber-framework/src/reporter.js#L63

Maybe there is someway to pass step to wdio afterStep hook, PRs are welcomed, entry point is here https://github.com/webdriverio/webdriverio/blob/34c7623d683b4e94cf7cbcb4eb6cb2798210be7b/packages/wdio-cucumber-framework/src/utils.js#L221
