### ISSUE TITLE
client.attachToSession() does not accept defaults for AttachSessionOptions

### ISSUE THREAD

**Issue by andy-schulz** [webdriverio/webdriverio#4378]
**Environment:**
 - **WebdriverIO version:** 5.11.13
 - **Mode:** Standalone mode
 - **Node.js version:** 8.11.3
 - **NPM version:** 5.6.0
 - **Browser name and version:** Chrome 75
 - **Platform name and version:** Windows 10

**Config of WebdriverIO**
```typescript
import WebDriver from "webdriver"

(async () => {

    const conf: WebDriver.Options = {
        capabilities: {
            browserName: `firefox`
        }
    };

    const client = await WebDriver.newSession(conf);

    // @ts-ignore
    const sessionId = client.sessionId;

    const attachConfNOK: WebDriver.AttachSessionOptions = {
        sessionId: sessionId,
        capabilities: conf.capabilities
    };

    const attachConfOK: WebDriver.AttachSessionOptions = {
        hostname: `localhost`,
        protocol: `http`,
        port: 4444,
        path:`/wd/hub/`,
        sessionId: sessionId,
        capabilities: conf.capabilities
    };

    await client.navigateTo('http://www.google.de/');

    const attachedClient = await WebDriver.attachToSession(attachConfNOK);

    await attachedClient.navigateTo(`https://www.google.com/`);

    await client.deleteSession();

})().catch((e) => console.error(e));
```

**Describe the bug**
Whereas client.newSession() accepts undefined / defaults for the server attributes (hostname, port, protocol and path) client.attachSession() does not. See Error below.

If all attributes are set client.attachToSession() works as expected.

As it seems only the typings were changed in #3942  and the referenced PR #3953 

**To Reproduce**
see script above

**Expected behavior**
I would expect attachToSession() and newSession() behaving the same regarding the passed config because AttachSessionOptions is a super set of Options and should allow default values for path, port, protocol and hostname.

**Log**
```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:489:7)

```

**Comment by andy-schulz** [comment]
@christian-bromann I tried to fix the issue by using the validateConfig() function as its used for newSession() as well.

When I run the following test:

```javascript
        test.only('see what validateConfig() is doing', () => {
            const sessOptions = {
                sessionId: 'testId'
            }

            const params = validateConfig(DEFAULTS, sessOptions)
            const params2 = validateConfig(DEFAULTS, {})
            expect(params2.sessionId).not.toEqual('testId')
        })
```

the tests fails as  params2 contains the sessionId from sessOptions from the first call. If I comment the first validateConfig() call the test passes. 

Is that supposed to work this way?

Thanks for you help.

**Comment by christian-bromann** [comment]
This error got resolved in WebdriverIO v6.
