### ISSUE TITLE
@wdio/local-runner does not end process if running more than one instance of @wdio/cli

### ISSUE THREAD

**Issue by danielamaia** [webdriverio/webdriverio#4379]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.12.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 10.16.0
 - **NPM version:** yarn 1.15.2
 - **Browser name and version:** Chrome 76
 - **Platform name and version:** macOS 10.14.5
 - **Additional wdio packages used (if applicable):** @wdio/cli, @wdio/local-runner, @wdio/mocha-framework, @wdio/spec-reporter

**Config of WebdriverIO**
https://gist.github.com/danielamaia/b2085b41189adbff1032bda5f169ef79#file-wdio-conf-js

**Describe the bug**
When running two instances of @wdio/cli concurrently, @wdio/local-runner cannot end process.

**To Reproduce**
https://github.com/danielamaia/wdio-reproduce-local-runner-issue
* npm i
* npm run test

**Expected behavior**
I expect that @wdio/local-runner is able to end process normally when I'm running two instances of @wdio/cli concurrently.
Can be related to #4328 

**Log**
running wdio and not exiting:
https://gist.github.com/danielamaia/a6ccd0daf2c4581aa08c02fd0a1a872f
forcing wdio to exit by hitting `ctrl+c`:
https://gist.github.com/danielamaia/d3df547ba04b610555c5c1314b449996

**Comment by mgrybyk** [comment]
You should either run test sequentially or start chromedriver manually.
ex1:
```
async function foo () {
  await main('specs.js');
  await main('specs1.js');
}

foo()
```

ex2:
_Assuming you have started chromedriver manually_
```
async function foo () {
  await Promise.all([main('specs.js'), main('specs1.js')])
}

foo()
```

Alternatively feel free to raise PR to change the behaviour

**Comment by danielamaia** [comment]
Ok, thank you for your answer and for fixing the previous issue 🙂

**Comment by mgrybyk** [comment]
You welcome!
Thank you for detailed steps to reproduce, it saves tons of time

**Comment by mgrybyk** [comment]
@danielamaia FYI https://github.com/webdriverio/webdriverio/issues/4368#issuecomment-522938239
