### ISSUE TITLE
Firefox blocks passed arguments for .execute

### ISSUE THREAD

**Issue by snovak** [webdriverio/webdriverio#438]
I have noticed, with updated versions of Firefox, that my arguments are not getting through to the browser by passing them as such:

```javascript
client.execute(function(config){
    //config is undefined in firefox.. works with chrome.
}, config, function(res,err){});
```

is there a work around for this?

**Comment by christian-bromann** [comment]
@snovak have you tried `executeAsync` or `selectorExecute`?

**Comment by snovak** [comment]
I haven't... I'll take a look.

**Comment by christian-bromann** [comment]
@snovak was able to reproduce this. The current selenium standalone version `v2.45.0` has [a fix](https://code.google.com/p/selenium/issues/detail?id=8390) for that though there still seems to be [issues](https://code.google.com/p/selenium/issues/detail?id=8551) with Firefox versions on Windows and Linux platforms. In the end not a WebdriverIO problem.
