### ISSUE TITLE
selectByAttribute/selectByVisibleText returns non descriptive error when option is not found

### ISSUE THREAD

**Issue by romovs** [webdriverio/webdriverio#4383]
**Environment**
 - **WebdriverIO version:** 5.12.1
- **@wdio/sync:** 5.12.3
 - **Mode:** Standalone / sync
 - **Node.js version:** 8.16.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Chrome 76
 - **Platform name and version:** Windows 10

**Description**

`selectByAttribute` and `selectByVisibleText` return non descriptive error if the specified option is not found. For example:

```javascript
$('select').selectByAttribute('value', 'this_value_doesnt_exist');
$('select').selectByVisibleText('this_text_doesnt_exist');
```
Both produce the following error:
`Malformed type for "elementId" parameter of command elementClick`.

While `selectByIndex` seems to return a human-readable message: 
`Option with index "99" not found. Select element only contains 4 option elements`

**Comment by christian-bromann** [comment]
Let's continue convo in #4393
