### ISSUE TITLE
Property 'config' does not exist on type 'BrowserObject'

### ISSUE THREAD

**Issue by ania-s** [webdriverio/webdriverio#4384]
**Environment (please complete the following information):**
 - **WebdriverIO version:5.11.12
 - **Mode: Standalone
 - **If WDIO Testrunner, running sync/async:sync
 - **Node.js version:v10.15.3
 - **NPM version:6.4.21
 - **Browser name and version:Chrome 76
 - **Platform name and version:MacOS Mojave

**Config of WebdriverIO**
exports.config = {
...
    params: {
      scenarioContext: {}
    },
...
...
...

**Describe the bug**
After defining custom options in wdio.conf.js as described in https://webdriver.io/docs/browserobject.html and accessing it from tests I get the error:
"Property 'config' does not exist on type 'BrowserObject'"

**Comment by hijazi** [comment]
I'm facing the same issue too.

**Comment by jontxo** [comment]
I have the same problem. In this report [githug](https://github.com/jontxo/webdriverio-cucumber-typescript) the problem can be reproduced debugging with the configuration launch wdio in vscode

**Comment by mgrybyk** [comment]
I assume this one has beed fixed already. Closing

**Comment by sschalley** [comment]
Unless I'm doing something wrong this doesn't appear to be fixed.

**WebdriverIO version:5.18.6
**Mode: Standalone
**If WDIO Testrunner, running sync/async:sync
**Node.js version:v10.15.1
**NPM version:6.4.1
**Browser name and version:Chrome 80
**Platform name and version:Windows 10 Enterprise

wdio.conf.js:
  exports.config = {
    userName: 'testUser',
    userPwd: 'tuxxxxxx',

In the test case:
  loginPage.setUserName(browser.config.userName);
  loginPage.setUserPassword(browser.config.userPwd);

Error message:
   specs/SmokeTests/SmokeTestDriver.ts(15,42): error TS2339: Property 'userName' does not exist on 
   type 'Config'.
   specs/SmokeTests/SmokeTestDriver.ts(16,46): error TS2339: Property 'userPwd' does not exist on 
   type 'Config'.

**Comment by christian-bromann** [comment]
@sschalley where do you see the properties `userName` and `userPwd` exist in WebdriverIO?

**Comment by sschalley** [comment]
There are defined in wdio.conf.js:
exports.config = {
userName: 'testUser',
userPwd: 'tuxxxxxx',
..
..
..

**Comment by christian-bromann** [comment]
WebdriverIO doesn't support these configurations and I don't know where you got them from.

**Comment by sschalley** [comment]
Check this link out. Isn't it stating that properties can be defined in wdio.conf.js and used in the test suite?
https://webdriver.io/docs/browserobject.html

**Comment by christian-bromann** [comment]
Sure, but then you need to extend typings for the WebdriverIO config with your own properties that you want to add.

**Comment by sschalley** [comment]
I'm not sure how to do this. Can you point me to an example?

**Comment by weronikazoltaniecka** [comment]
Hi, I am also wondering how to do that, have you found any solution? I can use console.log to get custom properties and it works fine, but if I try to use them in my test I get an error 'Property ... does not exist on type 'WebdriverIO | Testrunner'.'

**Comment by bhanuagarwal73** [comment]
Hey @weronikazoltaniecka 

I am also facing same issue, any resolution you found?
