### ISSUE TITLE
Suggested change for @wdio/cli

### ISSUE THREAD

**Issue by baruchvlz** [webdriverio/webdriverio#4388]
While I was adding the `install` command to the CLI I noticed a few things that could be improved, here're some of them. 

- add `run` command
    - currently the CLI has 2 commands `install` and `repl`. By adding `run` we can: 
      - facilitate the addition of new commands in the future
      - easier testing each of individual command (related #4339)
      - `run` command is basically what `wdio path/to/wdio.conf.js` does
      - `wdio path/to/wdio.conf.js` should call `run` internally and display a deprecation warning (maybe)
  
    - by doing this we will be able to move the `--help` flag to each command thus making it less confusing for the user
      - `wdio --help` displays the commands the descriptions
      - `wdio <command> --help` will display the command's usage and flags (if any)
    

- move `config.js`, `utils.js`, and `setup.js` to `utils/` folder
    - these files are shared utilities between core files (launcher, interface, index) and commands
    - consistency with other packages

- change the arrays of supported services, frameworks, reporters, etc to one collection
    - type definition:
    ```typescript
    [
      {
        name: string;
        type: 'reporter' | 'framework' | 'service';
        // package starts with @wdio or wdio-
        internal: boolean;
      }
    ]
    ```
    - easier mapping to the EJS template files
    - easier to select the package names on installation
    - easier addition of new packages

**Comment by christian-bromann** [comment]
I like these suggestions!

**Comment by baruchvlz** [comment]
@mgrybyk Quick question, [this console log](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-cli/src/utils.js#L188-L196) says to add the appium command, but it seems to be added [here](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-cli/src/templates/wdio.conf.tpl.ejs#L162-L164) by us anyway. Is it safe to remove this? Or am I missing something?

**Comment by mgrybyk** [comment]
Please don't remove console log, not everyone uses wdio cli, also config might be broken manually, etc
