### ISSUE TITLE
Add support for webdriver-sizzle

### ISSUE THREAD

**Issue by waddles** [webdriverio/webdriverio#439]
It would be nice to be able to use [chai-webdriver](http://chaijs.com/plugins/chai-webdriver) to do asynchronous BDD style tests but it requires [webdriver-sizzle](https://github.com/goodeggs/webdriver-sizzle) which is not able to use a webdriverio driver, it only works with selenium-webdriver.

I may be wrong but I think what is required is to enhance webdriverio to implement the methods required by webdriver-sizzle.

**Comment by christian-bromann** [comment]
webdriver-sizzle and chai-webdriver using selenium-webdriver to do their assertions and are not compatible with WebdriverIO at all. However, you can still do all these assertions. If you like chai I would recommend to use [chai-as-promised](http://chaijs.com/plugins/chai-as-promised) write similar code. It won't work for all commands though. Here are a couple of examples:

```js
var client = webdriverio.remote({
    desiredCapabilities: {
        browserName: 'phantomjs'
    }
});

chaiAsPromised.transferPromiseness = client.transferPromiseness;

// chai-webdriver: expect(selector).dom.to.have.text('string')
expect(client.getText(selector)).should.become('string');

// chai-webdriver: expect(selector).dom.to.contain.text('string')
expect(client.getText(selector)).should.eventually.include('string');

// chai-webdriver: expect(selector).dom.to.be.visible()
expect(client.isVisible(selector)).should.become.true;

// chai-webdriver: expect(selector).dom.to.have.value('string')
expect(client.getValue(selector)).should.become('string');
```

As you can see, using transferPromiseness makes it almost identical. As promises are still a little but buggy in WebdriverIO I haven't published any documentation for that but I will do it soon.

**Comment by theorygeek** [comment]
@christian-bromann Just thought I'd mention that this solution is not quite the same, because the error messages that you get when the assertion fails are quite different:

```js
expect('.some-element').dom.to.be.visible();
// error: Expected '.some-element' to be visible, but it is not
```

Compared to:
```js
expect(client.isVisible(selector)).should.become.true;
// error: Expected false to be true
```

The latter error message is tremendously unhelpful when you're trying to figure out _why_ the test failed.

**Comment by christian-bromann** [comment]
@theorygeek I agree. The assertion message is not really descriptive. However I don't see place for assertion helpers within the WebdriverIO core. It could be an interesting project to create a plugin though.
