### ISSUE TITLE
afterStep result and error undefined

### ISSUE THREAD

**Issue by fege** [webdriverio/webdriverio#4392]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [5.12.4]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [10.15.2]
 - **NPM version:** [6.4.1]
 - **Browser name and version:** [Any]
 - **Platform name and version:** [Any]
 - **Additional wdio packages used (if applicable):**
 [    "@wdio/appium-service": "5.12.1",
    "@wdio/cli": "5.12.4",
    "@wdio/config": "5.12.1",
    "@wdio/cucumber-framework": "5.12.3",
    "@wdio/dot-reporter": "5.12.1",
    "@wdio/firefox-profile-service": "5.12.1",
    "@wdio/local-runner": "5.12.4",
    "@wdio/selenium-standalone-service": "5.12.1",
    "@wdio/sync": "5.12.3",
    "@wdio/utils": "5.12.1",]

**Config of WebdriverIO**
```
var fs = require("fs");
var glob = require("glob");
var path = require("path");
var debug = require("debug");
var shelljs = require("shelljs");
var cucumber = require("cucumber");
var execSync = require("child_process").execSync;
var generate = require('multiple-cucumber-html-reporter').generate;
var logger = {
  info: debug("hnod:test:wdio.conf:info")
};
exports.config = {
    specs: [
        './features/**/*.feature'
    ],
    suites: {
        PSV: ["./features/bat.feature"],
        SV_SDK: ["./features/sdk.feature"],
        SV: [
        "./features/app_startup.feature",
        "./features/search.feature",
        "./features/route_preferences.feature"
        ],
        NIGHTLY: [
        "./features/app_startup.feature",
        "./features/demo.feature",
        "./features/routes.feature",
        "./features/route_preferences.feature",
        "./features/search.feature",
        "./features/settings.feature",
        "./features/drg.feature",
        "./features/sp_launcher.feature"
        ],
        NV_SDK: ["./features/sdk.feature"],
        cluster: ["./features/cluster.feature"]
    },
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    reportDir: "./build/reports/",
    logLevel: 'debug',
    outputDir: "./build/reports/logs/",
   @wdio/sauce-service
    bail: 0,
    baseUrl: 'http://localhost',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    framework: 'cucumber',
    
    reporters: [
      'dot',
      [ 'cucumberjs-json', { 
        jsonFolder: "./build/reports/",
      },
      ],
    ],
    
    cucumberOpts: {
        require: ["./build/**/*.js"],        // <string[]> (file/dir) require files before executing features
        backtrace: false,   // <boolean> show full backtrace for errors
        requireModule: [],  // <string[]> ("extension:module") require files with the given EXTENSION after requiring MODULE (repeatable)
        dryRun: false,      // <boolean> invoke formatters without executing steps
        failFast: false,    // <boolean> abort the run on first failure
        format: ['pretty'], // <string[]> (type[:path]) specify the output format, optionally supply PATH to redirect formatter output (repeatable)
        colors: true,       // <boolean> disable colors in formatter output
        snippets: true,     // <boolean> hide step definition snippets for pending steps
        source: true,       // <boolean> hide source uris
        profile: [],        // <string[]> (name) specify the profile to use
        strict: false,      // <boolean> fail if there are any undefined or pending steps
        tagExpression: [],  // <string[]> (expression) only execute the features or scenarios with tags matching the expression
        name: [],           // REGEXP[] Only execute the scenarios with name matching the expression (repeatable).
        timeout: 60000,     // <number> timeout for step definitions
        ignoreUndefinedDefinitions: false, // <boolean> Enable this config to treat undefined definitions as warnings.
        tagsInTitle: true   // Add cucumber tags to feature or scenario name
    },
    
    //
    // =====
    // Hooks
    // =====
   
    /**
     * Runs after a Cucumber step
     */
    afterStep: function (uri, feature, result) {
      // Saving screenshot in case of test failure
      logger.info(result)
    }
}
```
**Describe the bug**
the 3 parameter of the afterStep hook contains 
`{ error: undefined, result: undefined }`

**To Reproduce**
Run any cucumber test and inspect the afterStep result values
`
   afterStep: function (uri, feature, result) {
      // Saving screenshot in case of test failure
      logger.info(result)
`

**Expected behavior**
error and result contains value and not undefined

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by mgrybyk** [comment]
That's an expected result. If a step is not throwing an error or not returning anything then both error and result are undefined.

If you an error is undefined in case of failure feel free to reopen
