### ISSUE TITLE
`isExisting` on chained child element with missing parent throws error

### ISSUE THREAD

**Issue by klamping** [webdriverio/webdriverio#4394]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.12.4
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.16.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Chrome 76
 - **Platform name and version:** OSX 10.13.6
 - **Additional wdio packages used (if applicable):** n/a

**Config of WebdriverIO**
https://github.com/klamping/wdio-chained-issue/blob/master/wdio.conf.js

**Describe the bug**
If you try calling `isExisting` on an element that is selected via a chained selector and the parent doesn't exist, an error will be thrown.

For example:
```
const doesChildExist = $('#missing-parent').$('.child').isExisting();
```

throws:

```
Can't call $ on element with selector "#missing-parent" because element wasn't found
```

**To Reproduce**
https://github.com/klamping/wdio-chained-issue

**Expected behavior**
`isExisting` should handle the missing parent gracefully and return `false`, as the child element does not exist. 

**Log**
https://paste.gg/p/anonymous/6cbb08df955440a9a7d0a7ea4e9f40e9

**Comment by christian-bromann** [comment]
I would argue that this is the behavior I would expect. Any command on a nested element where the parent is not being found should throw this way. I don't think making an exception here for `isExisting` makes sense. Like the error happens even with: `$('#missing-parent').$('.child')` which also makes sense.

**Comment by erwinheitzman** [comment]
Does this mean that our middleware doesn't correctly retry until the nested elements exist?

**Comment by christian-bromann** [comment]
@erwinheitzman if you see in the logs there is a retry:

```

  | [0-0] 2019-08-21T18:11:17.084Z INFO webdriver: COMMAND findElements("css selector", "#missing-parent")
  | [0-0] 2019-08-21T18:11:17.084Z INFO webdriver: [POST] http://127.0.0.1:4444/session/fc25f3791388a375aa3d0ce281a4fd1e/elements
  | [0-0] 2019-08-21T18:11:17.084Z INFO webdriver: DATA { using: 'css selector', value: '#missing-parent' }
  | [0-0] 2019-08-21T18:11:17.093Z INFO webdriver: RESULT []
```

any comments @klamping ?

**Comment by christian-bromann** [comment]
In my opinion the current behavior is correct because if the element is not found it can also mean that the selector is wrong. I think we can make no decision on any child of an element that doesn't exist. Therefor I rather throw an error instead of "silently" return false. Because what happens if: the element shows up shortly after we return false for the child element and apparently the child is existing. This would be super hard to debug and can confuse user.

**Comment by christian-bromann** [comment]
Any more feedback on this? Otherwise I would close this.

**Comment by mgrybyk** [comment]
I'd like to have ability to check existence of child element somehow.
`$('q').$('w').$('e').isExisting()`

Maybe pass some param, like `{ strict: false }`, or any other ideas

I'd say same applicable to isDisplayed, isClickable, isDisplayedInViewport, maybe some other commands

**Comment by christian-bromann** [comment]
@mgrybyk I agree and it currently does that already .. however it would fail if `w` is not existing which automatically implies that `e` doesn't exist either. The question here is whether to have `$('q').$('w').$('e').isExisting()` return `false` or let it fail. My opinion is to have it fail as it is more strict and is less magic. If you think about implementing it you will realise that it is not straight forward to allow this kind of functionality. For me it doesn't provide enough failure to add the complexity.

**Comment by mgrybyk** [comment]
can't we just await https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/commands/element/isExisting.js#L46 and return false in case of failure? At least if we pass some param to explicitly do that.

**Comment by christian-bromann** [comment]
No, because the statement already fails when running `$('q').$('w')`. We don't even execute `isExisting`.

**Comment by christian-bromann** [comment]
Closing then. I am happy to reopen this discussion but so far it looks like implementing it would make the code base tremendously more complex for something that results in the same.

Thanks for raising the issue Kevin!

**Comment by klamping** [comment]
I'm cool with seeing this closed. I mainly wanted to note it as a thing, and you're right that implementation would likely be complex. Plus there are easy enough solutions/workarounds in the test code itself 👍🏻
