### ISSUE TITLE
[0-0] Error in "undefined" TypeError: $(...).waitForDisplayed is not a function

### ISSUE THREAD

**Issue by cjmme** [webdriverio/webdriverio#4395]
I download the boiler project https://github.com/webdriverio/appium-boilerplate/, 
And try run the test case by below command, but shows error :
./node_modules/.bin/wido ./config/wdio.android.app.conf.js --spec ./tests/specs/app.forms.spec.js

![image](https://user-images.githubusercontent.com/20895790/63490795-1c6ef000-c4e8-11e9-86fd-2775e37d9d1b.png)

**Environment:**
 - **WebdriverIO version:** 5.12.1
 - **Mode:** [Standalone mode or WDIO Testrunner]: wdio test runer
 - **If WDIO Testrunner, running sync/async:**  sync
 - **Node.js version:** 8.16.1
 - **NPM version:**  6.11.1
 - **Browser name and version:**  Android 9 emulator 
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** 
    "@wdio/appium-service": "^5.7.9",
    "@wdio/cli": "^5.7.12",
    "@wdio/jasmine-framework": "^5.7.8",
    "@wdio/local-runner": "^5.7.12",
    "@wdio/sauce-service": "^5.7.8",
    "@wdio/spec-reporter": "^5.7.9",
    "@wdio/sync": "^5.7.9",
    "@wdio/mocha-framework": "^5.12.1",
    "@wdio/selenium-standalone-service": "^5.12.1",

**Additional context**
wido config files:

[config.zip](https://github.com/webdriverio/webdriverio/files/3528595/config.zip)

**Comment by mgrybyk** [comment]
Update all wdio packages to latest versions

**Comment by wswebcreation** [comment]
@cjmme 

I've tested this with the latest version of WDIO on the boilerplate and this just works fine. Please update to the latest versions as @mgrybyk mentioned.
I'm going to close it for now because it's not an issue with WDIO

**Comment by Ranjithsamalla** [comment]
> @cjmme
> 
> I've tested this with the latest version of WDIO on the boilerplate and this just works fine. Please update to the latest versions as @mgrybyk mentioned.
> I'm going to close it for now because it's not an issue with WDIO

@cjmme 

I'm also facing same issue
For all wdio function
Ex getText, isDisplayed,etc not a function

**Comment by christian-bromann** [comment]
@Ranjithsamalla make sure you use `@wdio/sync` in your project.

**Comment by Duane11003** [comment]
@Ranjithsamalla did that solve the issue? Bc i'm having the same problem.  `$(...).waitForVisible is not a function`

**Comment by mlynch** [comment]
@Duane11003 I just ran into this as well and it's because I am in async mode so `$` returns a promise. This isn't obvious from the docs. Just need to `await` the selector and then `waitForVisible` will exist: https://webdriver.io/docs/sync-vs-async/#async-mode

**Comment by christian-bromann** [comment]
We are working on an improved async interface based on this discussion: #6702

**Comment by nagajyostna-eate** [comment]
even i am facing the same issues 

this.mobile.waitForDisplayed is not a function... can i know how to solve this

**Comment by choudhurym2** [comment]
> @Duane11003 I just ran into this as well and realized it's because I am in async mode so `$` returns a promise. This isn't obvious from the docs. Just need to `await` the selector and then `waitForVisible` will exist: https://webdriver.io/docs/sync-vs-async/#async-mode

have used await  still getting the error: await this.searchResult.waitForDisplayed();
