### ISSUE TITLE
How to access to step in the afterStep hook

### ISSUE THREAD

**Issue by fege** [webdriverio/webdriverio#4396]
**Describe your question with as much detail as possible**
Given the new afterStep hook

```
afterStep: function (uri, feature, result) {
    }
```

How I can access the step that triggered hook?
So that I can call `step.type` or `step.text` or any similar attribute
Or is there something else that I can use?

**Environment (please complete the following information):**
 - **WebdriverIO version:** [5.12.4]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [10.15.2]
 - **NPM version:** [6.4.1]
 - **Browser name and version:** [Any]
 - **Platform name and version:** [Any]
 - **Additional wdio packages used (if applicable):** [ "@wdio/appium-service": "5.12.1",
"@wdio/cli": "5.12.4",
"@wdio/config": "5.12.1",
"@wdio/cucumber-framework": "5.12.3",
"@wdio/dot-reporter": "5.12.1",
"@wdio/firefox-profile-service": "5.12.1",
"@wdio/local-runner": "5.12.4",
"@wdio/selenium-standalone-service": "5.12.1",
"@wdio/sync": "5.12.3",
"@wdio/utils": "5.12.1"]

**Additional context**

**Comment by mgrybyk** [comment]
There is no way to do it, feel free to raise PR

**Comment by christian-bromann** [comment]
@mgrybyk do we have this object available when calling the hook?

**Comment by mgrybyk** [comment]
No, we have only args passed to step and cucumber done function. Also this object which is Cucumber World.
There should be some other ways to do it, maybe parse step function itself, look for some cucumber helpers, record cucumber before step reporter event and use this data in wdio before after step hooks.

I want to say it's not something easy like pass argument and it is not something that is impossible to do, but still requires spending some time on investigation

**Comment by gtilekar** [comment]
@mgrybyk  can we read result in afterstep ..I am using 

afterStep: function (uri, feature, scenario, step, result) {
        console.log('--->' + result);
    },

I get undefined for result.  "@wdio/cucumber-framework": "^5.12.3",

**Comment by mgrybyk** [comment]
You are using after step hook incorrectly, please see docs or examples. 
Anyway, it's not a place to discuss it, @gtilekar

**Comment by mgrybyk** [comment]
@wswebcreation @christian-bromann 
I'm working on some changes that allows getting cucumber step name and other data (`{ uri, feature, scenario, step, sourceLocation }`).

However it would be a **breaking** change in terms of signature for before/after Test/Hook.

Currently we have:
```
afterStep (uri, feature, result) {
// uri - string
// feature - string
// result is always in the end
```
proposal is to change it to:
```
afterStep (stepData, context, result) {
// stepData is an object like { uri, feature, scenario, step, sourceLocation }

// context is an object containing Cucumber World that was requested before by someone
```

In such case before/after test/hook gonna look similar for all test frameworks: `data, context, result`

Will focus on it right after https://github.com/webdriverio/webdriverio/pull/4354

**Comment by christian-bromann** [comment]
> However it would be a **breaking** change in terms of signature for before/after Test/Hook.

Can we make it somehow backwards compatible (e.g. by adding it as a 4th parameter) and create an issue with "planned breaking changes" for v6?

**Comment by mgrybyk** [comment]
Yes, with some ugly if else conditions.

**Comment by goldengecko** [comment]
@mgrybyk I presume this will also be available for beforeStep? This would be very helpful.

+1 on making it backward compatible - just add more args to the existing ones, rather than a config object - either `(uri, feature, scenario, step, sourceLocation)` or `(uri, feature, {scenario, step, sourceLocation})` for beforeStep

**Comment by mgrybyk** [comment]
let's proceed convo in the PR
