### ISSUE TITLE
How to use 3rd party method that takes callback in “onComplete” hook

### ISSUE THREAD

**Issue by alexisrouse** [webdriverio/webdriverio#4397]
I need to put a Promise in the "onComplete" hook to use a 3rd party method there. I know that to do this I have to use browser.call before the promise, but I don't have a browser in the "onComplete" hook, right? What can I use instead of browser.call?

```onComplete() {
    browser.call(() => {
      return new Promise(function(resolve, reject) {
        testrail.getTests(content.runId, function(
          otherErr,
          responseTests,
          runTests
        ) {
          console.log(`Othererr : ${otherErr}`);
          console.log(`responseTests${responseTests}`);
          console.log(`RunTests: ${runTests}`);
          runTests.forEach(function(element) {
            console.log(`testCaseid ${testCaseId}`);
            if (element.case_id === content.testId) {
              testCaseId = element.id;
              if (
                content.result === 'failed' ||
                content.result === 'skipped'
              ) {
                statusTestCase = 5;
              } else if (content.result === 'passed') {
                statusTestCase = 1;
              }
            }
            if (otherErr) {
              return reject();
            }
            return resolve();
          });
        });
      });
    });
```

**Environment:**
 - **WebdriverIO version:** [5.11.12]
 - **Mode:** [WDIO Testrunner]
 - **sync/async:** [sync]
 - **Node.js version:** [11.14.0]
 - **NPM version:** [6.9.0]
 - **Browser name and version:** [Chrome 76]
 - **Platform name and version:** [MacOs Mojave]
 - **Additional wdio packages used: ** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

Thanks!

**Comment by mgrybyk** [comment]
You can use async await in onComplete hook.

**Comment by christian-bromann** [comment]
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
