### ISSUE TITLE
Add option to install TypeScript dependencies and configuration using the CLI

### ISSUE THREAD

**Issue by erwinheitzman** [webdriverio/webdriverio#4399]
**Is your feature request related to a problem? Please describe.**
Some people struggle with creating a TypeScript setup for wdio.

**Describe the solution you'd like**
I think we can help them by adding a question in the CLI that asks if they want to use TypeScript.
If they answer with yes, it could install TypeScript and any other required packages (ts-node, tsconfig-paths, @types/node) and generate a tsconfig.json file with the settings already correct for the packages installed.

**Additional context**
An example of a config we could generate for people that choose to use Mocha:
```
{
    "compilerOptions": {
        "target": "es5",
        "baseUrl": ".",
        "paths": {
            "*": ["./*"],
        },
        "types": ["node", "@wdio/mocha-framework", "@wdio/sync"],
        "lib": ["es2017", "dom"],
        "removeComments": true,
        "alwaysStrict": true,
        "forceConsistentCasingInFileNames": true
    },
    "include": ["./test/**/*.ts"] // not "./test/specs/**/*.ts" because you might have other testfiles you might want to compile
}
```

**Comment by christian-bromann** [comment]
This got implement in #5438
