### ISSUE TITLE
Missing some wdio commands

### ISSUE THREAD

**Issue by erwinheitzman** [webdriverio/webdriverio#4401]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Description of the improvement / report**
Currently we have listed all protocols and all wdio commands that communicate with these protocols though we don't have the commands listed that do not cummunicate with any of these protocols.
Like for example the `addCommand` and `overwriteCommand` commands missing. It would be great if we could generate documentation for these commands as well to make them more visible for new people.

**Comment by christian-bromann** [comment]
`addCommand` and `overwriteCommand` are missing here because they are implemented into the core logic and not as extra commands.

I suggest to add a file similar to the [`call command`](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/commands/browser/call.js) and just add a documentation piece and no code. This way the docs are properly generated. Any help on this would be very appreciated. If anyone has questions or needs support please let me know.

**Comment by AutomationReddy** [comment]
@christian-bromann I would like to work on it. But need some insights.

**Comment by erwinheitzman** [comment]
@AutomationReddy what kind of insight do you need?

**Comment by AutomationReddy** [comment]
@erwinheitzman I see this issue was opened for missing documents on `addCommand `and `overwriteCommand`. But this page has the info on these two: https://webdriver.io/docs/customcommands.html#adding-custom-commands.

Are you looking for separate doc for both or how?

**Comment by mgrybyk** [comment]
You can inspect browser object in debug and checkout what properties (like browser.parent) are missing in the API doc, and list them here.
Take a look how docs are generated, see `npm run docs:generate`.
Talking about adding and overwriting commands it's still good to have them in API doc with a reference to the "adding custom commands" guide.

**Comment by christian-bromann** [comment]
@AutomationReddy thanks for taking this on, you find some documentation on how to generate the page here: https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md#setting-up-and-deploying-the-docs. I think we should add 3 pages into the API docs:

- addCommand: add command
- overwriteCommand: overwrite command
- parent: get the element the current element was queried from

The first two should be rather high level description with a reference to the custom command page in the guide. Given that these commands are implemented in the webdriverio core you just create a file with the jsdocs and nothing else, similar as with the [mock commands](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/commands/mock/respond.js).

**Comment by AutomationReddy** [comment]
@mgrybyk @christian-bromann Thanks for the info. I have started writing it. Please have a look at the below image on `addCommand`. If you are good with that, I will proceed with the other items.
![image](https://user-images.githubusercontent.com/42345623/94345281-71adf700-0042-11eb-92c5-3a811fde0503.png)

**Comment by erwinheitzman** [comment]
I'd say, `name` would suffice, also it's not a function name but the name of the command ;)

When using variable / parameter names that consist of multiple words I'd say to use something like `elementScope` instead of `elementscope`.

I'd change the details for the element scope to something along the lines of `extend the Element object instead of the Browser object`

Regarding the description of the command, just keep it simple and descriptive. You're not trying to sell the command but trying to explain the user what the API offers them.

Hope this helps, thanks for the contribution 👍

**Comment by AutomationReddy** [comment]
@erwinheitzman Gotcha!! Thanks! I will follow the same for other items.

![image](https://user-images.githubusercontent.com/42345623/94347083-fa329480-004e-11eb-88ca-da5e63d4a096.png)

**Comment by erwinheitzman** [comment]
Looks good although I just noticed the `customVar` in the example, that's just a regular parameter so I'd use a different example like:
```
browser.addCommand('getUrlAndTitleAndId', function (randomId) {
    return {
        url: this.getUrl(),
        title: this.getTitle(),
        id: randomId,
    };
});
```

**Comment by AutomationReddy** [comment]
@erwinheitzman Thanks. Here is the image for `overwriteCommand`. I will go ahead and raise PR for these two items. For `parent`, I need to see the usage as I haven't experienced it myself. I will debug it and create a new issue, and work on it soon. Just let me know, if you are okay with this.
![image](https://user-images.githubusercontent.com/42345623/94348140-77fa9e00-0057-11eb-9ddd-50b18462fd6c.png)

**Comment by christian-bromann** [comment]
Looks great. Thanks!

Let's continue convo in #5891
