### ISSUE TITLE
multiremote with cucumber how to use it?

### ISSUE THREAD

**Issue by fege** [webdriverio/webdriverio#4404]
**Describe your question with as much detail as possible**
Trying to use multiremote with cucumber but browser name is not found

**If it's about a specific piece of code, try and include some of it to support your question.**
 //
```
    capabilities: {
        browserA: {
            capabilities: {
                browserName: 'chrome',
            }
        },
        browserB: {
            capabilities: {
                browserName: 'chrome'
            }
        }
    },
```

in my step definition I have

```
When(/^I open "([^"]*)"$/, function (url) {
  browser.url(url);
  browserA.addValue("AAAA")
});

```

and `browserA` is not defined
**Environment (please complete the following information):**
- **WebdriverIO version**: [5.12.4]
- **Mode**: [WDIO Testrunner]
- **If WDIO Testrunner, running sync/async**: [sync]
- **Node.js version**: [10.15.2]
- **NPM version**: [6.4.1]
- **Browser name and version**: [Chrome]
- **Platform name and version**: [Any]
 - **Additional wdio packages used (if applicable):** 
[  "@wdio/cli": "^5.12.4",
    "@wdio/cucumber-framework": "^5.12.3",
    "@wdio/local-runner": "^5.12.4",
    "@wdio/selenium-standalone-service": "^5.12.1",
    "@wdio/sync": "^5.12.3",]

**Additional context**

logs
```

stepDefinitions/starting.ts:6:3 - error TS2552: Cannot find name 'browserA'. Did you mean 'browser'?

6   browserA.addValue("AAAA")
    ~~~~~~~~

  node_modules/@wdio/sync/webdriverio.d.ts:27:13
    27 declare var browser: WebdriverIO.BrowserObject;
                   ~~~~~~~
    'browser' is declared here.


Found 1 error.

```

**Comment by christian-bromann** [comment]
Can you please provide logs and a minimal reproducible example?

**Comment by christian-bromann** [comment]
@fege ah .. so you need to extend the TS definition of the `WebdriverIO.BrowserObject` so that it includes also your defined browser names. I am gonna close that because it is not an issue with WebDriverIO.

**Comment by ania-s** [comment]
> @fege ah .. so you need to extend the TS definition of the `WebdriverIO.BrowserObject` so that it includes also your defined browser names. I am gonna close that because it is not an issue with WebDriverIO.

@christian-bromann why doesn't it work out of the box like described in the documentation? Won't it be supported for TS? Or is it a general case?

**Comment by christian-bromann** [comment]
> why doesn't it work out of the box like described in the documentation?

I does work out of the box. You are using TypeScript though which in many cases requires some extra steps.

> Won't it be supported for TS? Or is it a general case?

You can use Typescript of course. However we impossibly provide a TS definition for a browser name that you define in the config. You call your browser `browserA` others call it `chromeBrowser` , how are we suppose to know that?

**Comment by volodymyrk3** [comment]
> @fege ah .. so you need to extend the TS definition of the `WebdriverIO.BrowserObject` so that it includes also your defined browser names. I am gonna close that because it is not an issue with WebDriverIO.

can you please give an example of how to implement it, cannot find it in the documentation anywhere, thanks

**Comment by christian-bromann** [comment]
@volodymyrk3 did you take a look into the [docs](https://webdriver.io/docs/boilerplates#warleygabrieldemo-webdriverio-cucumber)?

**Comment by volodymyrk3** [comment]
> @volodymyrk3 did you take a look into the [docs](https://webdriver.io/docs/boilerplates#warleygabrieldemo-webdriverio-cucumber)?

@christian-bromann umm yes, I checked all the boilerplate projects, and unfortunately cannot find at least one example of usage of ts + multiremote feature, thanks anyway

**Comment by christian-bromann** [comment]
The example [I linked](https://webdriver.io/docs/boilerplates#warleygabrieldemo-webdriverio-cucumber) is Cucumber with TS. There should be nothing special to be aware of in order to make this a multiremote project. If so please let me know and we can work on the docs.
