### ISSUE TITLE
waitForVisible not working in Firefox

### ISSUE THREAD

**Issue by johnsonw** [webdriverio/webdriverio#442]
I was having some difficulty getting waitForVisible to work in one of my tests so I tried this simple block:

    var webdriverio = require('webdriverio');
    var options = {
      desiredCapabilities: {
        browserName: 'firefox'
      }
    };

    webdriverio
      .remote(options)
      .init()
      .url('http://www.google.com')
      .getTitle(function(err, title) {
        console.log('Title was: ' + title);
      })
      .waitForVisible('#hplogo')
      .end(done);

In this case the browser just hangs on the google home page until the test times out. If you change the browserName property to 'chrome'; however, and run the same test, the test will complete successfully. Is anyone else experiencing this issue?

**Comment by cruiser12** [comment]
i experience the same

**Comment by notnarb** [comment]
There seems to be some bugginess in recent versions of Firefox (35+) and Selenium https://code.google.com/p/selenium/issues/detail?id=8390
I believe that this is an issue with Firefox and Selenium interactions and not WebdriverIO

**Comment by johnsonw** [comment]
I ended up using selenium-webdriver and the wait behavior seems to be working fine with firefox. Might be worth investigating.

**Comment by notnarb** [comment]
WebdriverIO's implementation of waitForVisible uses executeAsync: the command that is reported to not work in Firefox35+ in the link above.

**Comment by BernardoGO** [comment]
@johnsonw 
Is there a way to use it with executeAsync?

**Comment by Sharpe23** [comment]
@BernardoGO 
i think its impossible

**Comment by christian-bromann** [comment]
It is possible implement that command without using `executeAsync`. I've used `executeAsync` as it allows me to do more sophisticated checks if an element is actually visible (being in the viewport vs. just being displayed somewhere).

**Comment by zdfs** [comment]
Could this Firefox issue possibly affect `moveTo()` as well? I seem to have problems with the command in Firefox, but not Chrome.

**Comment by christian-bromann** [comment]
@johnsonw could you give me some Selenium logs? This would help me to have a better understanding what happens

**Comment by christian-bromann** [comment]
@zdfs mhm .. rather no as moveTo is a plain Selenium command and doesn't use any execute helpers

**Comment by zdfs** [comment]
@christian-bromann: I know that this is outside the scope of this issue, but would you mind just take a cursory glance at the following code and let me know if I'm utilizing the webdriver.io API correctly?

```javascript
browser
  .element(selector, function(err, data) {
    browser
      .moveTo(data.value.ELEMENT, 0, 0)
      .pause(750)
      .getCssProperty(selector, propKey, function(err, data) {
        helpers.testProperty(err, data, prop, chaiMethod);
       })
       .call(done);
});

**Comment by zdfs** [comment]
Interesting, in Firefox I'm getting a null pointer. Need to see if the Selenium project has a bug for this.

```shell
java.lang.NullPointerException
	at org.openqa.selenium.remote.server.handler.interactions.MouseMoveToLocation.call(MouseMoveToLocation.java:52)
	at org.openqa.selenium.remote.server.handler.interactions.MouseMoveToLocation.call(MouseMoveToLocation.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by christian-bromann** [comment]
@zdfs why do you use `moveTo` here? There is no need for that if you just want to get a css property.

```js
browser
    .getCssProperty(selector, propKey, function(err, data) {
        helpers.testProperty(err, data, prop, chaiMethod);
    })
    .call(done);
```

... should do it too

**Comment by zdfs** [comment]
It's for links that change color on hover.

**Comment by waddles** [comment]
@zdfs I don't think .moveTo is causing your problem. I get a failure in Firefox with this code (using chai-as-promised):

    it('should display a home icon', function(done) {
        browser
            .getCssProperty('.nav .inner a:first-child span', 'background')
            .then(function(prop){
                chai.expect(prop.value).to.match(/images\/homepage\/sprite\.png/)
            })
            .call(done)
    });

**Comment by zdfs** [comment]
@waddles - Interesting.

**Comment by christian-bromann** [comment]
@waddles @zdfs Selenium magic ;-)

Seems that this will be fixed with the next Selenium release. Still unfortunate though that this happened. I  think having a fallback might be a good idea if `executeAsync` fails. Will put it into the v3 release.

**Comment by christian-bromann** [comment]
All waitFor* commands don't use execute anymore (see #502). Closing.
