### ISSUE TITLE
setWindowSize sets wrong size

### ISSUE THREAD

**Issue by CarlosUvaSilva** [webdriverio/webdriverio#4421]
Hello

I'm trying to set my screen size to 500x500 and then screenshot said screen but when I use `browser.setWindowSize(500, 500)` the screenshot is 500x456.

Every screen size I try the final size is always off by a couple of pixels

I really need the size to be precise, any help?
Thank you

**Comment by christian-bromann** [comment]
In v4 we had something called [setViewportSize](http://v4.webdriver.io/api/window/setViewportSize.html) which we didn't ported due to the lack of usage. You can use the [implementation](https://github.com/webdriverio-boneyard/v4/blob/master/lib/commands/setViewportSize.js) we used for that for your project.

**Comment by CarlosUvaSilva** [comment]
@christian-bromann what's even "worse" is that the difference between the value I want and the one I get is not the same between platforms. On my computer I get 44 pixels if I run the exact same code inside an AWS instance the difference is around 100.

Can I just copy the code from [implementation](https://github.com/webdriverio-boneyard/v4/blob/master/lib/commands/setViewportSize.js) and use it instead of `setWindowSize` or do I need to do something else?

**Comment by christian-bromann** [comment]
> Can I just copy the code from [implementation](https://github.com/webdriverio-boneyard/v4/blob/master/lib/commands/setViewportSize.js) [](/webdriverio-boneyard/v4/blob/HEAD@{2019-08-29T15:18:14Z}/lib/commands/setViewportSize.js) and use it instead of `setWindowSize` or do I need to do something else?

yes, just do that. `setWindowSize` changes the browser window not the viewport. This is an expected behavior.

**Comment by CarlosUvaSilva** [comment]
@christian-bromann sorry to bother you but can you help me port this method? 
I'm getting `getViewportSize` undefined, I tried to replace `this` with my `browser` object but its still not working

**Comment by christian-bromann** [comment]
Make sure to port also the imported scripts. Sorry but I don't have further capacities to help individuals.

**Comment by CarlosUvaSilva** [comment]
ok, i'll try to port everything.
Thank you

**Comment by dpoetzsch** [comment]
In case anyone is still struggling with this I created a service that ports the functionality: https://github.com/mondata-dev/wdio-viewport-size
