### ISSUE TITLE
bail option is not stopping after 1st failure with cucumber

### ISSUE THREAD

**Issue by fege** [webdriverio/webdriverio#4422]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [5.12.4]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [10.15.2]
 - **NPM version:** [6.4.1]
 - **Browser name and version:** [ANY]
 - **Platform name and version:** [ANY]
 - **Additional wdio packages used (if applicable):** [
   "@wdio/appium-service": "5.12.1",
    "@wdio/cli": "5.12.4",
    "@wdio/config": "5.12.1",
    "@wdio/cucumber-framework": "5.12.3",
    "@wdio/dot-reporter": "5.12.1",
    "@wdio/firefox-profile-service": "5.12.1",
    "@wdio/local-runner": "5.12.4",
    "@wdio/selenium-standalone-service": "5.12.1",
    "@wdio/sync": "5.12.3",
    "@wdio/utils": "5.12.1",
]

**Config of WebdriverIO**
    bail: 1

**Describe the bug**
Test run is not stopping after first failure

**To Reproduce**
Run a suite with cucumber that has at least 1 failure

[Include code or an example repository that can easily be set up]

**Expected behavior**
Test run stops after the first failure

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by fege** [comment]
if it helps I also tried to use the cucumber option 
`cucumberOpts. failFast=true `

and it is not working as well

**Comment by christian-bromann** [comment]
@fege please help us investigate this issue.

**Comment by fege** [comment]
@christian-bromann here a sample project where bail is not working but the cucumber option does https://github.com/fege/webdriverio-bail

**Comment by chemanth** [comment]
@christian-bromann @fege i have tested the issue using the above repo. 
I could see that for bail =1, the count 1 applies to number of .feature files and not the scenarios within a feature file.

For example:- in the above repo, if you add one more .feature file and put bail=1, it stops after the first feature file fails. 
But if you have only one .feature file in the whole repo and you want the run to stop once single scenario fails, it doesn't stop.

**Comment by mgrybyk** [comment]
`bail` works just fine. If you set it to 1, have 2 features and the first one fails, 2nd won't start.

**Comment by mgrybyk** [comment]
closing this for now as far as `bail` options was used improperly.

Feel free to raise an issue to cucumber-js if you want to have bail option implemented for scenarios.

**Comment by Pandicool** [comment]
@mgrybyk  bail is not working properly for me i have two feature files and add bail is 1 both files are executing both files
