### ISSUE TITLE
browserstack automation

### ISSUE THREAD

**Issue by SassNinja** [webdriverio/webdriverio#4423]
**Is your feature request related to a problem? Please describe.**
We've built all our tests with webdriverio and run them internally.
Now we want to use browserstack to be able to test more browsers/devices.
However I was disappointed quite fast when I realized browserstack does not mark tests as failed (when they fail) and does use session IDs as names and not the test names (saucelabs does both automatically)

After some research I've found out there's apparently no other solution than using browserstacks's Rest API to fix this. That's where my frustration has started because it's not completely working and I've no idea what's the best way to fix this.

**Describe the solution you'd like**
I'd expect webdriverio to take care of this since it claims to support browserstack out-of-the-box.

**Describe alternatives you've considered**
I've created a `beforeTest` hook, that changes the name:
```javascript
beforeTest: function(test) {
	if (firstFinished[test.parent] !== true) {
		console.log('>>> set name');
		firstFinished[test.parent] = true;
		const opts = {
			url: `https://api.browserstack.com/automate/sessions/${browser.sessionId}.json`,
            method: 'PUT',
            headers: {
	            'Content-Type': 'application/json'
            },
            body: `{"name":"${test.parent}"}`,
            auth: {
    	        user: 'xxxx',
                pass: 'xxxx'
            }
        };
        request(opts);
}
```
However this feels bad.
Apart from that I've created an `afterTest` hook that sets the status:
```javascript
afterTest: function(test) {
    if (test.passed === false && test.err) {
        const opts = {
            url: `https://api.browserstack.com/automate/sessions/${browser.sessionId}.json`,
            method: 'PUT',
            headers: {
                'Content-Type': 'application/json'
            },
            body: `{"status":"error"}`,
            auth: {
                user: 'xxxx',
                pass: 'xxxx'
            }
        };
        request(opts);
    }
}
```

Again this feels bad. Requesting the api for every single test will probably reach the limit of 800 requests / 5 min quite fast.
I tried to set multiple status with one api call but had no success.

@christian-bromann any chance a better browserstack integration gets added?
Or do you think it's not webdriverio's job to take care of it?

**Comment by christian-bromann** [comment]
> However I was disappointed quite fast when I realized browserstack does not mark tests as failed (when they fail) and does use session IDs as names and not the test names (saucelabs does both automatically)

BrowserStack as much as Sauce Labs doesn't know anything about the test you are running. The only information you send to BrowserStack are automation steps. That is why cloud vendors provide an API to set the test state and name.

> I'd expect webdriverio to take care of this since it claims to support browserstack out-of-the-box.

It does, please see [@wdio/browserstack-service](https://www.npmjs.com/package/@wdio/browserstack-service).

I hope this answers all questions. If you have more feel free to join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).

**Comment by SassNinja** [comment]
ah ok, when I add the browserstack service in my config, the state is set correctly

maybe the docs should point this out because out-of-the-box browserstack support is a bit confusing then in my opinion
