### ISSUE TITLE
Deep Linking within iOS Native Mobile Application

### ISSUE THREAD

**Issue by awhisler** [webdriverio/webdriverio#4425]
**Describe your question with as much detail as possible**
 
I cant seem to figure out how to open a deep linked location in an iOS native mobile application. I have tried something like this: `await browser.url(`${__dirname}/xxx.app`+"://password-reset");` but that just opens a browser and does not open the deep link within the app on iOS simulator. Please help!

**If it's about a specific piece of code, try and include some of it to support your question.**

 - **WebdriverIO version:** 5.11.7
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 12.6.0
 - **NPM version:** 6.9.0
 - **Tool and version:** Appium 1.14.0
 - **Mobile type:** iOS Native

**Comment by christian-bromann** [comment]
@awhisler please take a look at https://appiumpro.com/editions/84. If you have further questions join our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). Thanks!

**Comment by awhisler** [comment]
@christian-bromann I have already read this and that is exactly what I did as you can see in my code snippet and it opens a browser, like I mentioned.
