### ISSUE TITLE
Unable to generate wdio.conf.js file based on getting started guide

### ISSUE THREAD

**Issue by adnanmc** [webdriverio/webdriverio#4426]
Hi All,

I was following the getting started guide. It seems I cannot generate wdio.conf.js. Yarn throws an EPERM error and there is an unhanded promise rejection from setup.js

I'm unclear as to what is the problem.

I'm able to reproduce it in windows 10 pro 64 bit with fresh install of node version 8.16 and 10.16 just by following the getting started guide in https://webdriver.io/docs/gettingstarted.html
**Environment :**
 - "@wdio/cli": "^5.12.5"
 - **Node.js 8.16.x and 10.16.x
 - **NPM version: 6.11.2
 - **Platform name and version: Windows 10 pro

? Where should your tests be launched?  local - https://www.npmjs.com/package/@wdio/local-runner
? Where is your automation backend located? On my local machine
? Which framework do you want to use?  mocha - https://www.npmjs.com/package/@wdio/mocha-framework
? Do you want to run WebdriverIO commands synchronous or asynchronous? sync
? Where are your test specs located? ./test/specs/**/*.js
? Which reporter do you want to use?  spec - https://www.npmjs.com/package/@wdio/spec-reporter
? Do you want to add a service to your test setup?  chromedriver - https://www.npmjs.com/package/wdio-chromedriver-service
? What is the base url? http://localhost

Installing wdio packages:
- @wdio/local-runner
- @wdio/mocha-framework
- @wdio/spec-reporter
- wdio-chromedriver-service
- @wdio/sync
- chromedriver
yarn add v1.0.2
(node:1180) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.0.7: The platform "win32" is incompatible with this module.
info "fsevents@2.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info fibers_node_v8@3.1.4: The engine "node" is incompatible with this module. Expected version ">=8.0.0 <10.0.0".
info "fibers_node_v8@3.1.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@wdio/mocha-framework@5.12.1" has incorrect peer dependency "webdriverio@^5.0.0".
error An unexpected error occurred: "EPERM: operation not permitted, unlink 'C:\\Users\\Adnan\\Desktop\\selenium\\webdriverio-test\\node_modules\\.bin\\wdio'".info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\Adnan\\Desktop\\selenium\\webdriverio-test\\yarn-error.log".info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.(node:13624) UnhandledPromiseRejectionWarning: Error: Error: null
    at setup (C:\Users\Adnan\Desktop\selenium\webdriverio-test\node_modules\@wdio\cli\build\setup.js:67:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:13624) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which 
was not handled with .catch(). (rejection id: 1)
(node:13624) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
![image](https://user-images.githubusercontent.com/12175770/63992731-46617d00-cabb-11e9-954f-6e9152166417.png)

**Comment by adnanmc** [comment]
Anyone, have any idea whats the reason for this?

**Comment by christian-bromann** [comment]
Can you share the yarn error log in C:\Users\Adnan\Desktop\selenium\webdriverio-test\yarn-error.log?

**Comment by adnanmc** [comment]
Sure. Yarn Error log.
Arguments: 
  C:\Program Files\nodejs\node.exe C:\Program Files (x86)\Yarn\bin\yarn.js add --dev @wdio/local-runner @wdio/mocha-framework @wdio/spec-reporter wdio-chromedriver-service @wdio/sync chromedriver

PATH: 
  C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Adnan\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files\Python37\Scripts;C:\Program Files\Python37;C:\Program Files (x86)\TRICENTIS\Tosca Testsuite;C:\Tosca_Projects;C:\Program Files (x86)\TRICENTIS\Tosca Testsuite\dll;C:\Program Files (x86)\TRICENTIS\Tosca Testsuite\dll\GuptaEngine;C:\Program Files (x86)\TRICENTIS\Tosca Testsuite;C:\Program Files (x86)\TRICENTIS\Tosca Testsuite\dll\DelphiEngine;C:\Program Files (x86)\TRICENTIS\Tosca Testsuite\dll\PBEngine;C:\Program Files (x86)\TRICENTIS\Tosca Testsuite\dll\VBEngine;C:\Program Files (x86)\TRICENTIS\Tosca Testsuite\dll\DotNetHooking;C:\Program Files (x86)\TRICENTIS\Tosca Testsuite\Resources\Mobile\Tools;C:\Program Files (x86)\PC Connectivity Solution;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Brackets\command;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files (x86)\Skype\Phone;C:\Users\Adnan\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Yarn\bin;C:\Program Files\PuTTY;C:\Windows\System32\OpenSSH;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\AOMEI Backupper;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\nodejs;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0;%SYSTEMROOT%\System32\OpenSSH;C:\Ruby22\bin;C:\Users\Adnan\AppData\Local\.meteor;C:\Users\Adnan\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\Adnan\AppData\Local\atom\bin;C:\Users\Adnan\AppData\Local\Yarn\bin;C:\Users\Adnan\AppData\Local\GitHubDesktop\bin;C:\Program Files\Java\jdk-9.0.1\bin;C:\DevTools\apache-maven-3.5.2\bin;C:\Users\Adnan\AppData\Local\Microsoft\WindowsApps;C:\Users\Adnan\AppData\Roaming\Python\Python37\Scripts;C:\Users\Adnan\AppData\Roaming\npm

Yarn version: 
  1.0.2

Node version: 
  10.16.3

Platform: 
  win32 x64

npm manifest: 
  {
    "name": "webdriverio-test",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
      "test": "echo \"Error: no test specified\" && exit 1"
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "devDependencies": {
      "@wdio/cli": "^5.12.5"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: EPERM: operation not permitted, unlink 'C:\Users\Adnan\Desktop\selenium\webdriverio-test\node_modules\.bin\wdio'

**Comment by rajjeet** [comment]
install via yarn gave me issues. Npm didn't. Because of this, I'm unable to generate the config file as well. Here's my `yarn-error.log`.
```bash
Arguments: 
  /home/raj/.nvm/versions/node/v12.9.1/bin/node /usr/local/bin/yarn

PATH: 
  /home/raj/.nvm/versions/node/v12.9.1/bin:/home/raj/dev/WebStorm-183.4284.130/bin:/home/raj/.rbenv/shims:/home/raj/.rbenv/bin:/usr/local/aws/bin:/home/raj/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/raj/.dotnet/tools

Yarn version: 
  1.12.3

Node version: 
  12.9.1

Platform: 
  linux x64

Trace: 
  Error: EACCES: permission denied, mkdir '/home/raj/dev/try-wdio/node_modules/archiver-utils/node_modules/safe-buffer'

npm manifest: 
  {
    "name": "try-wdio",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
      "test": "echo \"Error: no test specified\" && exit 1"
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "devDependencies": {
      "@wdio/cli": "^5.12.5"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

```

**Comment by rajjeet** [comment]
Getting this error for setup:
```
error @wdio/cli@5.12.5: The engine "node" is incompatible with this module. Expected version ">= 8.11.0". Got "8.10.0"
error Found incompatible module
```
however when i run `npm --version` I see this
`v12.9.1`

**Comment by adnanmc** [comment]
Ok so after much digging, it turns out it only happens with git bash, even with admin privilege.
Workaround is use windows cmd for the initial setup process instead of git bash.

**Comment by christian-bromann** [comment]
Thanks for the info @adnanmc. I don't think this is an issue we can fix within the project, therefor closing!

**Comment by adnanmc** [comment]
@christian-bromann No problem. I later discovered it has to do with permission when using git bash. Even when running as admin problem persisted. But when I use windows cmd it works fine. 
Thanks for looking into it anyway.

**Comment by Ravindraayata** [comment]
Hi,
Unable to open the browser.


[0-0] RETRYING
[0-0] FAILED (1 retries)

Spec Files:      0 passed, 1 retries, 1 failed, 1 total (100% completed) in 00:00:00

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webdriveriotest@1.0.0 test: `wdio`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webdriveriotest@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ravindra\AppData\Roaming\npm-cache\_logs\2020-11-11T12_51_09_441Z-debug.log
