### ISSUE TITLE
Missing documentation on runner option

### ISSUE THREAD

**Issue by GimpMaster** [webdriverio/webdriverio#4427]
**Pre-check**
- [X ] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [ X] Missing documentation
- [ ] Other

**Description of the improvement / report**
On the Options page there are clear definitions of almost all the options. However I could not find any documentation on runner. Is "local" the only option?

**Comment by christian-bromann** [comment]
> Is "local" the only option?

Yes. If there will be more options we will add more documentation on this.
