### ISSUE TITLE
executeAsync does not work in the Forefox

### ISSUE THREAD

**Issue by kusha1988** [webdriverio/webdriverio#443]
I tried to run the this script in Chrome  and Firefox on a Mac OS. In the Chrome it works correct. In the Firefox it throws RunTimeError.

### Script
```javascript
var webdriverio = require('webdriverio');
var options = {
    desiredCapabilities: {
        browserName: 'firefox'
    }
};

webdriverio
    .remote(options)
    .init()
    .timeoutsAsyncScript(5000)
    .executeAsync(function(a, b, c, d, done) {
        setTimeout(function() {
            done(a + b + c + d);
        }, 3000);
    }, 1, 2, 3, 4, function(err, ret) {
        console.log(ret.value); 
    });
```

### Error
```javascript
RuntimeError: RuntimeError
     (UnknownError:13) An unknown server-side error occurred while processing the command.
     Problem: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. 
```

### Infos
Chrome (Version 40.0.2214.115 (64-bit))
Firefox (36.0) 
webdriverio (2.4.5)
selenium-standalone (https://www.npmjs.com/package/selenium-standalone).

**Comment by notnarb** [comment]
Looks like a bug in Selenium https://code.google.com/p/selenium/issues/detail?id=8390

**Comment by kusha1988** [comment]
Yes. It was a problem of the selenium-standalone server. I have updated to the 2.45. Now it works correct,
