### ISSUE TITLE
Unable to switch to page opened in new window

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4435]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.12.5 
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10
 - **Browser name and version:** Chrome 76

**Config of WebdriverIO**
Add `devtools` package from master (pre-release version).
Then enable devtools: `automationProtocol: 'devtools'`

**Describe the bug**
`getWindowHandles` ignored new popup windows.

**To Reproduce**
```
const assert = require("assert")

describe("main suite", () => {
    it("some test", () => {
        browser.url("http://guinea-pig.webdriver.io/")
        browser.execute(function () {
            const popupLink = this.document.createElement("a")
            popupLink.id = 'newPopupWindow'
            popupLink.innerText = 'open new window'
            popupLink.target = 'popup'
            popupLink.setAttribute('onclick', "window.open('/three.html', 'name', 'width=600, height=400')")
            popupLink.classList.add('clearfix')
            this.document.querySelector('.page').insertBefore(popupLink, this.document.querySelector('#newWindow').nextSibling)
        })
        $("#newPopupWindow").click()
        assert.strictEqual(browser.getWindowHandles().length, 2)
    })
})
```

**Expected behavior**
- should be possible to switch to popup window same as without `automationProtocol: 'devtools'`
- please add smoke test

**Log**

**Comment by mgrybyk** [comment]
I've managed to add such windows to `windows` object like this:
```
// devtoolsdriver.js, right after page.on('framenavigated', ...
browser.on('targetcreated', target => {
    if (target.type() === 'page') {
        target.page()
            .then(newPage => {
                this.windows.set(uuidv4(), newPage)
            })
            .catch(() => { })
    }
})
```

**Comment by mgrybyk** [comment]
However it is not reliable because page may be closed with javascript.
It is way more reliable to use `const pages = await this.browser.pages()` to get pages in `getWindowHandles`, the problem here is that I don't know how to map puppeteer pages with `windows` Map.

**Comment by mgrybyk** [comment]
Ok, here is what is working for me:
```
async function getWindowHandles() {
    let newPages = await this.browser.pages()
    const stalePageIds = []
    this.windows.forEach((page, id) => {
        if (newPages.includes(page)) {
            newPages = newPages.filter(newPage => page !== newPage)
        } else {
            stalePageIds.push(id)
        }
    })
    stalePageIds.forEach(pageId => this.windows.delete(pageId))
    newPages.forEach(page => this.windows.set(uuidv4(), page))

    return Array.from(this.windows.keys());
}
```

**Comment by christian-bromann** [comment]
> If it's ok can do PR

sounds good to me

**Comment by mgrybyk** [comment]
will be fixed with the PR
