### ISSUE TITLE
can't find sendKeys

### ISSUE THREAD

**Issue by cruiser12** [webdriverio/webdriverio#444]
i was looking for the implementation of this one here:

https://selenium.googlecode.com/git/docs/api/java/org/openqa/selenium/interactions/Actions.html#sendKeys-org.openqa.selenium.WebElement-java.lang.CharSequence...-

**Comment by cruiser12** [comment]
ok i got it working with browser.chooseFile

**Comment by christian-bromann** [comment]
To send keys use the [keys](http://webdriver.io/api/protocol/keys.html) command
