### ISSUE TITLE
waitForExists on React element uses CSS Selector

### ISSUE THREAD

**Issue by baruchvlz** [webdriverio/webdriverio#4442]
**Config of WebdriverIO**
An example of how you configured WebdriverIO config

Default configuration

**Describe the bug**
When using element methods like `waitForExist` or `isExisting` in elements selected via `react$` or `react$$` the method will try to find the elements using CSS selectors. This won't work as these elements were selected using React components names.

**To Reproduce**
https://github.com/baruchvlz/wdio-wait-for-exist-react-cmp

**Expected behavior**
When running these methods on a React component, internally we should use `react$` or `react$$` instead of `$` or `$$`.

**Additional context**

Possible solution would be to pass a flag to these methods so they understand that it's a React component.

Example:

```js
const cmp = browser.react$('Cmp')
cmp.waitForExist(4000, { isReact: true })
```

**Comment by mgrybyk** [comment]
We may set flag to element itself to avoid passing flag to commands because it's not really convenient.
