### ISSUE TITLE
getSize() works when using $(selector) but not browser.findElement(selector)

### ISSUE THREAD

**Issue by mikesalvia** [webdriverio/webdriverio#4445]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.12.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.16.2
 - **NPM version:** 6.9.0
 - **Browser name and version:** Hybrid app
 - **Platform name and version:** Android OS
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
To be provided.

**Describe the bug**
Calling `getSize()` on result of `$(selector)` and `browser.findElement(selector)` behave differently even though $(...) is said to be a "shortcut".

**To Reproduce**

1.) Go to http://google.com via automated test
2.) Use `browser.debug()` to drop into REPL console
3.) Execute `$("*[name='q']")`, observe result
4.) Execute `browser.findElement('css', "*[name='q']")`, observe result
5.) Execute `$("*[name='q']").getSize()`, observe result
6.) Execute `browser.findElement('css', "*[name='q']").getSize()`, observe error

**Expected behavior**
`getSize()` should work on returned value from `$` as well as `findElement`, as `$` is documented to be a shortcut

**Log**
To be provided.

**Additional context**

Sample responses:
`$(selector)`: ```{ sessionId: '79818095-b326-4810-b187-baa5d3682107',
  elementId: '0.07467406605677596-1',
  'element-6066-11e4-a52e-4f735466cecf': '0.07467406605677596-1',
  selector: '#container div.jw-icon-display',
  parent:
   { sessionId: '79818095-b326-4810-b187-baa5d3682107',
     capabilities:
      { platform: 'LINUX',
        webStorageEnabled: false,
        takesScreenshot: true,
        javascriptEnabled: true,
        databaseEnabled: false,
        networkConnectionEnabled: true,
        locationContextEnabled: false,
        warnings: {},
        desired: [Object],
        platformName: 'Android',
        automationName: 'UIAutomator2',
        app:
         '/Users/msalvia/repos/jwplayer-mobile-sdk-workspace/jwplayer-android-sdk-bishop/app-test/build/outputs/apk/generic/debug/app-test-generic-debug.apk',
        disableWindowAnimation: true,
        platformVersion: '9',
        deviceName: 'emulator-5554',
        commandTimeout: 1800000,
        newCommandTimeout: 1800000,
        nativeWebScreenshot: true,
        allowInvisibleElements: true,
        deviceUDID: 'emulator-5554',
        appPackage: 'com.longtailvideo.jwplayer.testapp',
        deviceApiLevel: 28,
        deviceScreenSize: '1800x2560',
        deviceScreenDensity: 320,
        deviceModel: 'Android SDK built for x86',
        deviceManufacturer: 'Google',
        pixelRatio: 2,
        statBarHeight: 48,
        viewportRect: [Object] }, [truncated]```

`browser.findElement(selector)`: ```{ ELEMENT: '0.07467406605677596-1' }```

`$(selector).getSize()`: ```{ width: 88, height: 88 }```

`browser.findElement(selector).getSize()`: ```TypeError: browser.findElement(...).getSize is not a function```

> Please use the correct markdown

**Comment by mgrybyk** [comment]
This is an expected behaviour. `browser.findElement(...)` is a protocol command, use `browser.$` instead

**Comment by mikesalvia** [comment]
Just want to confirm we are required to use `$` in order to use `getSize()` in WDIO v5? This was a design choice? In the older versions `$` and `browser.element` would both respond to `getElementSize()`.

**Comment by mgrybyk** [comment]
Correct, it is mentioned in changelog

**Comment by christian-bromann** [comment]
@mikesalvia we changed some things in v5. While it was possible to do `browser.getSize(selector)` in v4 you can only use that command with an element instance in v5: `$(selector).getSize()`. Also, as @mgrybyk pointed out `findElement` is a protocol command and returns the driver response. If you want to use `getSize` which is only known in WebdriverIO, you need to use the element command of WebdriverIO which is `$` or `$$`. So tldr:

```js
const element = browser.findElement('css selector', '.myElem')
const { width, height } = browser.getElementRect(element['element-6066-11e4-a52e-4f735466cecf'])
```
is the same in WebDriver as the following in WebdriverIO:
```js
const { width, height } = $('.myElem').getSize()
```

**Comment by mgrybyk** [comment]
Maybe we should document this somewhere? It's not the first time people asking same questions

**Comment by mikesalvia** [comment]
@mgrybyk I think the best place to update documentation would be for `$`. https://webdriver.io/docs/api/browser/$.html

> The $ command is a short way to call the findElement command in order to fetch a single element on the page.

The above is misleading and "short way" seems to me like `$` is a convenience method to findElement which would return a similar if not the same response to work with. Maybe there calling out that `findElement` and `$` do not return the same usable item.
