### ISSUE TITLE
isDisplayedInViewport fails if element doesn't exist

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4448]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.12.5 
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10
 - **Browser name and version:** Chrome 76

**Config of WebdriverIO**
Add `devtools` package from master (pre-release version).
Then enable devtools: `automationProtocol: 'devtools'`

**Describe the bug**
isDisplayedInViewport fails if element doesn't exist.

**To Reproduce**
```
describe("main suite", () => {
    it("some test", () => {
        browser.url("http://guinea-pig.webdriver.io")
        $('foobar').isDisplayedInViewport()
    })
})
```

**Expected behavior**
should work same as without `automationProtocol: 'devtools'`.

**Log**
```
Error: Malformed type for "elementId" parameter of command isElementDisplayed
Expected: string
Actual: undefined
For more info see https://w3c.github.io/webdriver/#element-displayedness
    at validate (/e2e/node_modules/devtools/build/utils.js:52:13)
    at Element.<anonymous> (/e2e/node_modules/devtools/build/devtoolsdriver.js:79:43)
```

**Comment by christian-bromann** [comment]
Fixed by #4459
