### ISSUE TITLE
explicitWait, how can i waitUntil

### ISSUE THREAD

**Issue by cruiser12** [webdriverio/webdriverio#445]
i found this one here, and its also implemented in 'selenium-webdriver'

http://docs.seleniumhq.org/docs/04_webdriver_advanced.jsp

how can i use that with webdriverIO ?
For example i would like to wait, till a certain css-property has a certain value.

Regards

**Comment by christian-bromann** [comment]
WebdriverIO has the following wait utilities: [waitFor](http://webdriver.io/api/utility/waitFor.html), [waitForChecked](http://webdriver.io/api/utility/waitForChecked.html), [waitForEnabled](http://webdriver.io/api/utility/waitForEnabled.html), [waitForExist](http://webdriver.io/api/utility/waitForExist.html), [waitForSelected](http://webdriver.io/api/utility/waitForSelected.html), [waitForText](http://webdriver.io/api/utility/waitForText.html), [waitForValue](http://webdriver.io/api/utility/waitForValue.html) and [waitForVisible](http://webdriver.io/api/utility/waitForVisible.html). These are the most common wait for commands. To catch use cases like yours WebdriverIO is gonna introduce a `waitForCondition` command. There is already [an issue](https://github.com/webdriverio/webdriverio/issues/411) opened for that. I think I gonna put this into the `v2.5.0` release. Until then you can do a workaround. Use the `execute` command to check that condition on the browser side and return the value to assert it on node side.
