### ISSUE TITLE
Error: Remote end send an unknown status code getting this error while switching the tab in Android 8.0

### ISSUE THREAD

**Issue by logakarthi** [webdriverio/webdriverio#4453]
**Describe your question with as much detail as possible**
"Error: Remote end send an unknown status code" error gets while switching the tab from the parent window. I'm getting this error specifically in the Android v8.0(Galaxy S8). I can able to switch the tabs in the Android v6.0, v7.0 in the cross-browser cloud.

**If it's about a specific piece of code, try and include some of it to support your question.**
[...]

**Environment (please complete the following information):**
 - **WebdriverIO version:** [ 4.14.0 =
 - **Mode:** [Standalone mode or WDIO Testrunner] : [WDIO Testrunner ]
 - **If WDIO Testrunner, running sync/async:**[ Sync ]
 - **Node.js version:** [8.11.3]
 - **NPM version:** [5.6.0]
 - **Browser name and version:** [ Chrome 75]
 - **Platform name and version:** Android S8 v(8.0)
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Code
browser.waitUntil(() => browser.windowHandles().value.length > 1);
      var popWindow = browser.windowHandles().value.filter((handle) => handle !== mainTab)[0];
      console.log(popWindow);
      browser.switchTab(popWindow);
      browser.pause(5000);

**Please find the below exception,

[Galaxy S8 Android 8.0 #0-0] invalid argument: 'name' must be a string
[Galaxy S8 Android 8.0 #0-0] Error: Remote end send an unknown status code.
[Galaxy S8 Android 8.0 #0-0]     at window("CDwindow-1") - index.js:312:3
[Galaxy S8 Android 8.0 #0-0]

**Please find the below APIs and its response

GET window_handles
200

Command Request Body

No request body captured
Command Response Body

{"sessionId":"5580f5f8-c7e1-4063-9010-992d21749b5b", "status":0, "value":["CDwindow-0", "CDwindow-1"]}

POST window
200

Command Request Body

{"handle":"CDwindow-1"}
Command Response Body

{"sessionId":"5580f5f8-c7e1-4063-9010-992d21749b5b", "status":61, "value":{"message":"invalid argument: 'name' must be a string\n (Session info: chrome=75.0.3770.67)\n (Driver info: chromedriver=75.0.3770.8 (681f24ea911fe754973dda2fdc6d2a2e159dd300-refs/branch-heads/3770@{#40}), platform=Linux 4.4.0-116-generic x86_64)"}}

**Comment by mgrybyk** [comment]
This is webdriverio v5 backlog. Webdriverio v4 is here https://github.com/webdriverio-boneyard/webdriver.io

I'd suggest upgrading to v5,  you may also try asking the question in gitter channel.
