### ISSUE TITLE
Massive log pollution when executing scripts

### ISSUE THREAD

**Issue by baruchvlz** [webdriverio/webdriverio#4455]
**Config of WebdriverIO**

Default configuration

**Describe the bug**

When using `react$` or `react$$` commands in either browser or element the log output gets polluted with the code from the scripts being executed.

Example test:

```js
const { expect } = require('chai')

it('waitForExist', () => {
    browser.url('/')
    browser.pause(2000)
    const cmp = browser.react$('Cmp')

    expect(cmp.isDisplayed()).to.be.true
})
```

```
npm run test
```
Result:

https://pastebin.com/BNAk83SH (280 lines long)

**To Reproduce**
https://github.com/baruchvlz/wdio-log-pollution

**Additional context**

Log levels which I've seen this happen: trace, debug, info

Currently the `executeScript` is logging out the complete script code to the console, should probably just log the name of the script (or file).

**Comment by mgrybyk** [comment]
It's not only with react selectors but also with javascript code execution.

Protocol command knows nothing about the file, it knows only about content. 
What if we normalize string, remove redundant whitespaces and finally shorten it if it's too long?

**Comment by baruchvlz** [comment]
I'm not 100% sure where this is being logged, it seems that `executeScript` logs before executing. So wouldn't shorting the string affect the execution of the script?

**Comment by mgrybyk** [comment]
No, if we shorten it for logging purposes only

**Comment by mgrybyk** [comment]
One of the places is here https://github.com/webdriverio/webdriverio/blob/74e6a170855b2b010da32c5d1686dced808f52de/packages/webdriver/src/command.js#L80

**Comment by baruchvlz** [comment]
Would it make more sense to log these manually before executing the script instead of having the log inside the command function?

For example:

```js
export default async function react$(selector, props = {}, state = {}) {
    log.info('Executing RESQ Script') // <-- here
    await this.executeScript(resqScript.toString(), [])
    await this.execute(waitToLoadReact)
    const res = await this.execute(react$Script, selector, props, state, this)
    return getElement.call(this, selector, res)
}
```

I know this will bring in more manual work but I think this way we can provide a better message to the user.

**Comment by christian-bromann** [comment]
We can modify `commandCallStructure` so that it checks if the payload contains a script property and if so just replace the script with `<fn>` or something like that

**Comment by christian-bromann** [comment]
see PR with fix
