### ISSUE TITLE
Execution hangs if clicked on anchor link

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4461]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.12.5 
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10
 - **Browser name and version:** Chrome 76

**Config of WebdriverIO**
Add `devtools` package from master (pre-release version).
Then enable devtools: `automationProtocol: 'devtools'`

**Describe the bug**
`e.click()` hangs forever if `framenavigated` event raised but `load` was not, ex: when link is an anchor.
Maybe we can somehow detect if page loading has started or not within certain timeout?

**To Reproduce**
```
describe("remote driver", () => {
    it("foobar - 0416", () => {
        browser.url("http://guinea-pig.webdriver.io/")
        browser.execute(function () {
            const anchorLink = this.document.createElement("a")
            anchorLink.id = 'anchor'
            anchorLink.href = '#anchor'
            anchorLink.innerText = 'anchor'
            this.document.querySelector('body').appendChild(anchorLink)
        })

        const el = $("#anchor").click()
        console.log('the end')
    })
})
```

**Expected behavior**
should work same as without `automationProtocol: 'devtools'`.

**Log**

**Comment by christian-bromann** [comment]
Fixed by #4459
