### ISSUE TITLE
Dynamic variables based on node variables

### ISSUE THREAD

**Issue by Khrove** [webdriverio/webdriverio#4465]
**Describe your question with as much detail as possible**
Ideally I would like to set my test variables dynamically based on node variables sent from an npm command. So my question is how are people controlling which variable sets to use? Credentials to login with would be an example variable.

Error I'm receiving:
"More than one config file was specified: NODE_ENV=int, USER_TYPE=admin, config/apps/partner_portal.conf.js
Error: You can only run one wdio config file!"

**If it's about a specific piece of code, try and include some of it to support your question.**
"test:partner:admin": "./node_modules/.bin/wdio NODE_ENV=int USER_TYPE=admin config/apps/partner_portal.conf.js",
"test:partner:owner": "./node_modules/.bin/wdio NODE_ENV=int USER_TYPE=owner config/apps/partner_portal.conf.js",
"test:partner:user": "./node_modules/.bin/wdio NODE_ENV=int USER_TYPE=user config/apps/partner_portal.conf.js",

Example use that I would like to expose:

in a config file's before function:

```
before: function() {
   const chai = require('chai');
   global.expect = chai.expect;
   chai.should();

   const USER_TYPE=process.env.USER_TYPE;
   const NODE_ENV = process.env.NODE_ENV;

   global.userType = USER_TYPE;
   global.env = NODE_ENV;
}
```

This would then drive which variable config to import in later on...how I have it setup is in a config folder's index.js

```
if (!env) {
    console.log('The \'NODE_ENV\' environment variable is not set. A valid value is required to load the application config.');
};

let environmentConfig;
try {
    environmentConfig = require(`./${env}`);
} catch(err) {
    console.error(`Unrecognized NODE_ENV: ${env}`);
    console.log('Please use the following variables: prod, int, stage, dev');
}

module.exports = {
    environmentConfig
};
```

If more is needed I can put together a codepen.

**Environment (please complete the following information):**
 - **WebdriverIO version:** v5

**Comment by christian-bromann** [comment]
Try: 

```sh
$ NODE_ENV=int USER_TYPE=admin ./node_modules/.bin/wdio config/apps/partner_portal.conf.js
```

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by Khrove** [comment]
Apologies, thought the "Question" setting on the New Issue page would add a filter of sorts. I tried your above solution and a new error occurred:

```
'.' is not recognized as an internal or external command,
operable program or batch file.
```

Fix to this is...no ./node_modules required I guess:

`NODE_ENV=int USER_TYPE=admin wdio config/apps/partner_portal.conf.js`
