### ISSUE TITLE
Scroll not working in android native app

### ISSUE THREAD

**Issue by dm-cracked-mitchellthomas** [webdriverio/webdriverio#447]
Trying to scroll a scrollable view in a native android app with webdriverio and appium throws the following error:
<code>
  Android Menu Automation
@before
    Drawer Layout Test
      √ Click menu icon
      - Menu Labels
      √ Scroll Menu
@after
CKWaitElementTouchClick
menuButton - result: null error:undefined
Click - result: true error:undefined
element - err: null result: [object Object]
scroll - err: RuntimeError: RuntimeError
     (UnknownError:13) An unknown server-side error occurred while processing the command.
     Problem: Not yet implemented. Please help us: http://appium.io/get-involved.html

     Callstack:
     -> touchScroll(null,0,100)
     -> scroll(0,100)
 result: null
</code>

Here is the code for my test:
<code>
describe("Android Menu Automation", function ()
{    
    this.timeout(999999999);
    var client,
        options,
        menuButton,
        drawerLabels,
        baseMenuElement,
        textElement;    

    before( function( done ) 
    {
        console.log("@before");
        options = 
        {
            desiredCapabilities: 
            {
                        "appium-version": "1.3.4",
                        platformName: "Android",
                        platformVersion: "4.4",
                        deviceName: "Android Emulator",
                        deviceType: "phone",
                        app: "sauce-storage:app-release.apk",
                        appWaitActivity : '.Home',
                        tags: ['android'],
                        name: "test.js",
                        browserName: ''
                    },
            host: 'ondemand.saucelabs.com',
            port: 80,
            user: "SimonJia",
            key: "4401e4d2-de29-4d62-99f2-f8447e2a16f9"
        };

        client = webdriverio.remote(options);
        client.init();
        client.addCommand("CKWaitElementTouchClick", function(el, cb) 
        {
            console.log("CKWaitElementTouchClick");

            this.waitFor(el, 10000, function(err, result)
            {
                console.log('menuButton - result: ' + result + ' error:'+err);
                this.click(el, function(err, result) 
                {
                    var results = true;
                    cb(err,results);                    
                })                
            })            
        });

        menuButton      = drawerElements["menu_button"];
        drawerLabels    = drawerElements["labels"];
        baseMenuElement = drawerElements["base_menu_element"];
        textElement     = drawerElements["text_element"];

        done();        
    });

    /**
     * @after
     *
     * @description
     *  End the client once all the tests are done
     */
    after( function (done)
    {
        console.log('@after');
        client.end(done);
    }); 

    describe("Drawer Layout Test", function()
    {
        /**
        * @CLick menu icon
        * - opens the drawer menu after waiting for the Home screen to load
        */
        it("Click menu icon", function() 
        {
            client
                .timeoutsImplicitWait(5000)
                .CKWaitElementTouchClick(menuButton,
                    function(err,result) 
                    {
                        // assert some stuff
                        console.log('Click - result: ' + result + ' error:'+err);
                    }
                );
        });

        it.skip("Menu Labels", function() 
        {
            // tests visible labels - need to scroll the list to get the last 2 items
            var i;
            for (i = 0; i < drawerLabels.length-2; i++)
            {
                var menuItem = baseMenuElement.replace('<index>',i+1);
                var labelElement = menuItem + textElement;
                var labelText = drawerLabels[i];

                console.log('menuItem: '+menuItem);
                console.log('labelText: '+labelText);

                client
                    .timeoutsImplicitWait(1000)
                    .waitFor(menuItem, 1000, function(err, result)
                    {
                        if (err != null) {
                            console.log('Find element - result:'+result);   
                        }           
                    })
                    .getText(labelElement, function(err, result) 
                    {
                        console.log('Text for element - result:'+result); 
                    });
            }
        });

        it('Scroll Menu', function () 
        {
            // need to scroll menu up to access the items at the bottom
            var menu = drawerElements['menu'];

            client
                .timeoutsImplicitWait(1000)
                .element(menu, function (err, result) {
                    console.log('element - err: '+err+' result: '+result);
                })
                .scroll(0,100, function (err, result) {
                    console.log('scroll - err: '+err+' result: '+result);
                })
                .done();
        });
    });   
});
</code>

**Comment by christian-bromann** [comment]
@dm-cracked-mitchellthomas `Problem: Not yet implemented.` some commands you can use on desktop browser are not implemented in Appium yet. Honestly speaking: WebdriverIO does not a good job on mobile. Many commands are deprecated or have changed. Wasn't able to catch up on this but it's already on my roadmap ;-)

**Comment by iDVB** [comment]
Why is this closed? Has this been implemented yet?

**Comment by christian-bromann** [comment]
According to the latest Appium docs it isn't but seems that there is a workaround for that:

```js
client.execute("mobile: scroll", {direction: 'down'})
```
