### ISSUE TITLE
Not able to switch to child iframe

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4471]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.12.5 
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10
 - **Browser name and version:** Chrome 76

**Config of WebdriverIO**
Add `devtools` package from master (pre-release version).
Then enable devtools: `automationProtocol: 'devtools'`

**Describe the bug**
Have iframe in iframe on a page. Unable to switch to child iframe.

**To Reproduce**
Have iframe in iframe on a page. Switch to iframe then switch to child iframe.
```
import { expect } from "chai"

describe("main suite", () => {
    it("iframe", () => {
        browser.url("https://fiddle.jshell.net/westonruter/3e61f0z9/show/")
        $("#result iframe").waitForDisplayed()
        browser.pause(1000)
        expect($("iframe").getAttribute("src")).contain("fiddle")

        browser.switchToFrame($("#result iframe"))
        expect($("iframe").getAttribute("src")).contain("webdriver")

        const iframes = $$("iframe")
        iframes[0].waitForDisplayed()

        // the issue is here, not able to switch to child iframe
        browser.switchToFrame(iframes[0])
        browser.pause(1000)
        const header = $("h2").getText()
        expect(header.toLowerCase()).contain("webdriver")

        browser.switchToParentFrame()
        expect($("iframe").getAttribute("src")).contain("webdriver")
        browser.switchToParentFrame()
        expect($("iframe").getAttribute("sandbox")).contain("allow")
    })
})
```

**Expected behavior**
the test is passing with webdriver and I expect it to pass with devtools protocol.

**Log**
not much in wdio logs
```
// result of is displayed
INFO devtools: RESULT true
INFO devtools: COMMAND switchToFrame(<object>)
// test failed
INFO devtools: COMMAND takeScreenshot()
```

spec reporter logs
```
Error: no such frame
[Chrome 17.7.0 darwin #0-0]     at DevToolsDriver.switchToFrame (e2e/node_modules/devtools/build/commands/switchToFrame.js:27:13)
```

**Comment by mgrybyk** [comment]
@christian-bromann I've found out what is the root cause of the issue.
It's because we don't have `'--disable-features=site-per-process,TranslateUI,BlinkGenPropertyTrees'` flag in default args, especially this one `site-per-process`.
Because of that `page.frames()` doesn't work as expected. 

I "love" such issues.

Now I'm going to add it to default args and then merge default args with user args

**Comment by christian-bromann** [comment]
Sounds good, nice found!
