### ISSUE TITLE
Click is not defined error

### ISSUE THREAD

**Issue by tmalhotra30** [webdriverio/webdriverio#4480]
Hi, 

I am using webdriver.io v5 for react native applications. I am getting error at the below step. Any idea why?

const elem = $('#Get Started'); 
elem.click();

It is throwing an error:
 
TypeError: elem.click is not a function

Thanks!

**Comment by mgrybyk** [comment]
you are either not using @wdio/sync or have not awaited the promise

**Comment by tmalhotra30** [comment]
After changing the click to have await. It still fails with same error. Can you please explain how to use @wdio/sync?

**Comment by mgrybyk** [comment]
I'd suggest starting project from scratch 
and following getting started guide with default values https://webdriver.io/docs/gettingstarted.html

After that apply your changes gradually and see what is causing the error.

**Comment by tmalhotra30** [comment]
This is the exact same guide I followed in the first place. Also, the example there is of a browser app, and my case is a native app.

Below is my basic.js file. It runs successfully till "await elem.click();" step and then throws click is not defined error. 


describe('Login flow', () => {
  it('should launch the app successfully', async () => {
    console.log('Hey, I ran!');
    await browser.execute('mobile: scroll', { direction: 'right' });
    await browser.execute('mobile: scroll', { direction: 'right' });
 
    const elem = $('#Get Started');
    await elem.click();
  });
});

**Comment by mgrybyk** [comment]
@tmalhotra30 this is not helpful at all.
Please either follow tge guide or provide with project with minimal reproduce example

**Comment by tmalhotra30** [comment]
Basic.js file

describe('Login flow', () => {
  it('should launch the app successfully', async () => {
    console.log('Hey, I ran!');
    await browser.execute('mobile: scroll', { direction: 'right' });
    await browser.execute('mobile: scroll', { direction: 'right' });
    const elem = $('#Get Started');
    await elem.click();
  });
});


exports.config = {
  runner: 'local',
  port: 4723, // default appium port
  specs: ['./test/specs/*.js'],
  exclude: [
    // 'path/to/excluded/files'
  ],
  //
  // ============
  // Capabilities
  // ============
  // Define your capabilities here. WebdriverIO can run multiple capabilities at the same
  // time. Depending on the number of capabilities, WebdriverIO launches several test
  // sessions. Within your capabilities you can overwrite the spec and exclude options in
  // order to group specific specs to a specific capability.
  //
  // First, you can define how many instances should be started at the same time. Let's
  // say you have 3 different capabilities (Chrome, Firefox, and Safari) and you have
  // set maxInstances to 1; wdio will spawn 3 processes. Therefore, if you have 10 spec
  // files and you set maxInstances to 10, all spec files will get tested at the same time
  // and 30 processes will get spawned. The property handles how many capabilities
  // from the same test should run tests.
  //
  maxInstances: 10,
  //
  // If you have trouble getting alant capabilities together, check out the
  // Sauce Labs platform configurator - a great tool to configure your capabilities:
  // https://docs.saucelabs.com/reference/platforms-configurator
  //
  capabilities: [
    {
      maxInstances: 1,
      browserName: '',
      url: 'http://127.0.0.1:4723/wd/hub',
      automationName: 'XCUITest',
      appiumVersion: '1.13.0',
      platformName: 'iOS',
      platformVersion: '12.4',
      deviceName: 'iPhone XS',
      autoAcceptAlerts: 'true',
      app: '/*/Release-iphonesimulator/*.app',

    },
  ],
  //
  // ===================
  // Test Configurations
  // ===================
  // Define all options that are relevant for the WebdriverIO instance here
  //
  // Level of logging verbosity: trace | debug | info | warn | error | silent
  logLevel: 'trace',
  sync: 'true',
  //
  // Set specific log levels per logger
  // loggers:
  // - webdriver, webdriverio
  // - @wdio/applitools-service, @wdio/browserstack-service, @wdio/devtools-service, @wdio/sauce-service
  // - @wdio/mocha-framework, @wdio/jasmine-framework
  // - @wdio/local-runner, @wdio/lambda-runner
  // - @wdio/sumologic-reporter
  // - @wdio/cli, @wdio/config, @wdio/sync, @wdio/utils
  // Level of logging verbosity: trace | debug | info | warn | error | silent
  // logLevels: {
  //     webdriver: 'info',
  //     '@wdio/applitools-service': 'info'
  // },
  //
  // If you only want to run your tests until a specific amount of tests have failed use
  // bail (default is 0 - don't bail, run all tests).
  bail: 0,
  //
  // Default timeout for all waitFor* commands.
  waitforTimeout: 10000,
  //
  // Default timeout in milliseconds for request
  // if Selenium Grid doesn't send response
  connectionRetryTimeout: 90000,
  //
  // Default request retries count
  connectionRetryCount: 3,
  //

  // Framework you want to run your specs with.
  // The following are supported: Mocha, Jasmine, and Cucumber
  // see also: https://webdriver.io/docs/frameworks.html
  //
  // Make sure you have the wdio adapter package for the specific framework installed
  // before running any tests.
  framework: 'jasmine',
  //
  // The number of times to retry the entire specfile when it fails as a whole
  // specFileRetries: 1,
  //
  // Test reporter for stdout.
  // The only one supported by default is 'dot'
  // see also: https://webdriver.io/docs/dot-reporter.html
  reporters: ['spec'],

  //
  // Options to be passed to Jasmine.
  jasmineNodeOpts: {
    //
    // Jasmine default timeout
    defaultTimeoutInterval: 60000,
    //
    // The Jasmine framework allows interception of each assertion in order to log the state of the application
    // or website depending on the result. For example, it is pretty handy to take a screenshot every time
    // an assertion fails.
    expectationResultHandler: function(passed, assertion) {
      // do something
    },
  },

  //
  // =====
  // Hooks
  // =====
  // WebdriverIO provides several hooks you can use to interfere with the test process in order to enhance
  // it and to build services around it. You can either apply a single function or an array of
  // methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
  // resolved to continue.
  /**
   * Gets executed once before all workers get launched.
   * @param {Object} config wdio configuration object
   * @param {Array.<Object>} capabilities list of capabilities details
   */
  // onPrepare: function (config, capabilities) {
  // },
  /**
   * Gets executed just before initialising the webdriver session and test framework. It allows you
   * to manipulate configurations depending on the capability or spec.
   * @param {Object} config wdio configuration object
   * @param {Array.<Object>} capabilities list of capabilities details
   * @param {Array.<String>} specs List of spec file paths that are to be run
   */
  // beforeSession: function (config, capabilities, specs) {
  // },
  /**
   * Gets executed before test execution begins. At this point you can access to all global
   * variables like `browser`. It is the perfect place to define custom commands.
   * @param {Array.<Object>} capabilities list of capabilities details
   * @param {Array.<String>} specs List of spec file paths that are to be run
   */
  // before: function (capabilities, specs) {
  // },
  /**
   * Runs before a WebdriverIO command gets executed.
   * @param {String} commandName hook command name
   * @param {Array} args arguments that command would receive
   */
  // beforeCommand: function (commandName, args) {
  // },
  /**
   * Hook that gets executed before the suite starts
   * @param {Object} suite suite details
   */
  // beforeSuite: function (suite) {
  // },
  /**
   * Function to be executed before a test (in Mocha/Jasmine) or a step (in Cucumber) starts.
   * @param {Object} test test details
   */
  // beforeTest: function (test) {
  // },
  /**
   * Hook that gets executed _before_ a hook within the suite starts (e.g. runs before calling
   * beforeEach in Mocha)
   */
  // beforeHook: function () {
  // },
  /**
   * Hook that gets executed _after_ a hook within the suite starts (e.g. runs after calling
   * afterEach in Mocha)
   */
  // afterHook: function () {
  // },
  /**
   * Function to be executed after a test (in Mocha/Jasmine) or a step (in Cucumber) starts.
   * @param {Object} test test details
   */
  // afterTest: function (test) {
  // },
  /**
   * Hook that gets executed after the suite has ended
   * @param {Object} suite suite details
   */
  // afterSuite: function (suite) {
  // },
  /**
   * Runs after a WebdriverIO command gets executed
   * @param {String} commandName hook command name
   * @param {Array} args arguments that command would receive
   * @param {Number} result 0 - command success, 1 - command error
   * @param {Object} error error object if any
   */
  // afterCommand: function (commandName, args, result, error) {
  // },
  /**
   * Gets executed after all tests are done. You still have access to all global variables from
   * the test.
   * @param {Number} result 0 - test pass, 1 - test fail
   * @param {Array.<Object>} capabilities list of capabilities details
   * @param {Array.<String>} specs List of spec file paths that ran
   */
  // after: function (result, capabilities, specs) {
  // },
  /**
   * Gets executed right after terminating the webdriver session.
   * @param {Object} config wdio configuration object
   * @param {Array.<Object>} capabilities list of capabilities details
   * @param {Array.<String>} specs List of spec file paths that ran
   */
  // afterSession: function (config, capabilities, specs) {
  // },
  /**
   * Gets executed after all workers got shut down and the process is about to exit. An error
   * thrown in the onComplete hook will result in the test run failing.
   * @param {Object} exitCode 0 - success, 1 - fail
   * @param {Object} config wdio configuration object
   * @param {Array.<Object>} capabilities list of capabilities details
   * @param {<Object>} results object containing test results
   */
  // onComplete: function(exitCode, config, capabilities, results) {
  // },
  /**
   * Gets executed when a refresh happens.
   * @param {String} oldSessionId session ID of the old session
   * @param {String} newSessionId session ID of the new session
   */
  //onReload: function(oldSessionId, newSessionId) {
  //}
};

**Comment by tmalhotra30** [comment]
Package.json contains:

    "@wdio/appium-service": "^5.11.4",
    "@wdio/cli": "^5.11.13",
    "@wdio/jasmine-framework": "^5.12.1",
    "@wdio/local-runner": "^5.12.1",
    "@wdio/sauce-service": "^5.11.1",
    "@wdio/selenium-standalone-service": "^5.11.2",
    "@wdio/spec-reporter": "^5.12.1",
    "@wdio/sync": "^5.12.3",

**Comment by mgrybyk** [comment]
@tmalhotra30 the issue is not reproducible for me when using my own appium setup.

Please provide with fully reproducible project or start from scratch using getting started guide and apply your changes gradually.

**Comment by tmalhotra30** [comment]
I do not have permission to provide the entire reproducible project. Can you please share your example for a native app which is working so I can compare?

**Comment by mgrybyk** [comment]
So make a simple project open safari browser instead of app.

**Comment by tmalhotra30** [comment]
I do not want to test against Safari browser as it works in my current setup. I am trying to click on an element within a react native app. Can you please provide a webdriverio native app example clicking elements.

**Comment by mgrybyk** [comment]
it works for me with my app, the setup has no difference except of capabilities.

**Comment by mgrybyk** [comment]
I did the following:
1. followed getting started guide, has chosen jasmine and appium there.
2. changed capabilities.
that's it, project works

**Comment by mgrybyk** [comment]
you may try app from here https://github.com/webdriverio/native-demo-app/releases

**Comment by tmalhotra30** [comment]
When running with native app, is your browserName: 'safari' still this?

**Comment by mgrybyk** [comment]
Of course no, it should be either app or browserName

**Comment by tmalhotra30** [comment]
I built webdriver io from scratch config and I still see that same problem of click not defined error. 

These are the options I chose:

./node_modules/.bin/wdio config

=========================
WDIO Configuration Helper
=========================

? Where should your tests be launched?  local - https://www.npmjs.com/p
ackage/@wdio/local-runner
? Where is your automation backend located? On my local machine
? Which framework do you want to use?  jasmine - https://www.npmjs.com/
package/@wdio/jasmine-framework
? Do you want to run WebdriverIO commands synchronous or asynchronous? 
async
? Where are your test specs located? ./test/specs/**/*.js
? Which reporter do you want to use? (Press <space> to select, <a> to t
oggle all, <i> to invert selection) spec - https://www.npmjs.com/packag
e/@wdio/spec-reporter
? Do you want to add a service to your test setup?  chromedriver - http
s://www.npmjs.com/package/wdio-chromedriver-service,  appium - https://
www.npmjs.com/package/@wdio/appium-service
? What is the base url? http://localhost

Installing wdio packages:
- @wdio/local-runner
- @wdio/jasmine-framework
- @wdio/spec-reporter
- wdio-chromedriver-service
- @wdio/appium-service
- chromedriver

**Comment by tmalhotra30** [comment]
Actually now the error I see is: 

  name: 'invalid argument',
  message: 'invalid argument: unrecognized capability: app',

**Comment by christian-bromann** [comment]
@tmalhotra30 you might want to check out our [appium-boilerplate](https://github.com/webdriverio/appium-boilerplate/) project to see how other people have done it.

**Comment by tmalhotra30** [comment]
@christian-bromann: I got it working. I had to remove async from my it function then it worked.

**Comment by PrinceZX** [comment]
![2021-05-31 23_18_19-npm install @wdio_local-runner @wdio_mocha-framework @wdio_spec-reporter wdio-ch](https://user-images.githubusercontent.com/42911122/120227446-cf947d80-c266-11eb-8aa7-0366bd8ab593.png)

I am not able to get the Sync and Async option while configure the Wdio file.

Would you please suggest how I can add Sync option in my Wdio file?

**Comment by christian-bromann** [comment]
> So, Would you please suggest how I can add Sync option in my Wdio file?

Just install the `@wdio/sync` package but note that we are likely to depcrecate WDIO sync.
