### ISSUE TITLE
Install devtools protocol without puppeteer-firefox

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4481]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to install `devtools` without `puppeteer-firefox` package because it takes an additional time to install and uses extra 180Mb of disk space.

It would be nice to have firefox, edge, etc packages optional to install.

**Describe the solution you'd like**
I don't have any solution at this point

**Comment by christian-bromann** [comment]
> It would be nice to have firefox, edge, etc packages optional to install.

It requires to download a Firefox binary right now because it is not yet supported with the latest Firefox stable version. I assume we will have a puppeteer-core to connect to Firefox soon.

**Comment by Krinkle** [comment]
I assume the use case is for someone using it to operate Chrome (instead of Firefox). In that case, the requirement of Firefox compatibility does not apply.

**Comment by just-boris** [comment]
As an option, we could move `puppeteer-firefox` to peerDependencies, so only folks who want to use Firefox would download it.

@christian-bromann @mgrybyk would you accept such pull request?

**Comment by pmerwin** [comment]
great idea.  we would love this to be decoupled.

**Comment by pmerwin** [comment]
@christian-bromann I started this PR to help with this.

https://github.com/webdriverio/webdriverio/issues/4481

**Comment by christian-bromann** [comment]
Closing giving that #4924 got merged.
