### ISSUE TITLE
Can't get react element with devtools

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4485]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.12.5 
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10
 - **Browser name and version:** Chrome 77
- **Devtools:** 5.13.0-alpha.0

**Config of WebdriverIO**
Then enable devtools: `automationProtocol: 'devtools'`

**Describe the bug**
Unable to get react element

**To Reproduce**
try get any react element 
```
describe("main suite", () => {
    it("some test", () => {
        browser.url("https://fiddle.jshell.net/reactjs/69z2wepo/show/")
        $("#result iframe").waitForDisplayed()
        browser.switchToFrame($("#result iframe"))

        const myComponent1 = browser.react$('Hello')
        const myComponent2 = browser.react$('Hello', { name: 'World' })

        console.log(myComponent1.isExisting())
        console.log(myComponent2.isDisplayed())
    })
})
```

**Expected behavior**
should be possible to interact with react elements

**Log**

```
Evaluation failed: SyntaxError: Unexpected token '{'
    at __puppeteer_evaluation_script__:3:30
    at Frame.<anonymous> (/e2e/node_modules/puppeteer-core/lib/helper.js:111:15)
    at DevToolsDriver.executeScript (/e2e/node_modules/devtools/build/commands/executeScript.js:22:31)
    at Browser.wrappedCommand (/e2e/node_modules/devtools/build/devtoolsdriver.js:84:47)
```

**Comment by christian-bromann** [comment]
Fixed by #4829
