### ISSUE TITLE
Add meaningful README.md for all sub packages

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#4488]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

Create some decent `README.md` for every package so it doesn't look undocumented on NPM.

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Description of the improvement / report**

It should contain:

- some description about responsibilities of the package
- a minor example of how to use it (not all exported functions or classes but the important ones)
- a link to documentation in order to understand how to contribute

**Comment by jdavis61** [comment]
I would be interested in helping with this task but would like to iterate, e.g. one PR per package, instead of creating README's for all packages at once.

Unless someone objects I will start with `wdio-utils`, `wdio-sync` and `wdio-config` and `wdio-logger`.

**Comment by christian-bromann** [comment]
> one PR per package, instead of creating README's for all packages at once.

That is fine with me.

For internal packages I would say it would be nice to have a description for everything that is being exported, where it is being used and a code example on how.
