### ISSUE TITLE
webdriverIO not compatible with Firexox V 36 onwards

### ISSUE THREAD

**Issue by amiya-pattnaik** [webdriverio/webdriverio#449]
Hi,
I have webdriverIO script up and running in my two test machine which has Firefox version 33 and 35. But in my another machine which has Firefox 36. It does not work. It just opens the FireFox browser and after that it could not able to load the URL it hangs there it self.

Could you suggest the workaround ?

I appreciate your help.
Thanks,
Amiya

**Comment by notnarb** [comment]
What version of Selenium are you using?
There are multiple documented issues about recent builds of Firefox not working with Selenium
e.g. https://code.google.com/p/selenium/issues/detail?id=8399

**Comment by amiya-pattnaik** [comment]
Thanks for you input.. But Selenium is bundled with WebdriverIO package. Please suggest where can I replace the latest Selenium inside the webdriver package ?
Please suggest.
Thanks - Amiya

**Comment by jameseisenhauer** [comment]
Where is selenium bundled at?  I can't see where it is.  How are you running your selenium server?

**Comment by amiya-pattnaik** [comment]
Sorry, actually I have packaged in my framework. 
I am using 'selenium-standalone' module from the NPM. it is 3 months old one, The latest  'selenium-standalone' from NPM does not work . Any suggestion on this to replace 'selenium-standalone' module with latest selenium through code or any other means?

Regards,
Amiya

**Comment by jameseisenhauer** [comment]
to me looks like selenium-standalone npm has updated to latest version.  Look in your package json file and make sure you are specifying the latest version and make sure you do a npm install of it.  Also looks like that package you can specify any version you want for selenium.
https://github.com/vvo/selenium-standalone/commit/b5ed9b1953de35b5d25a12dc9a39e84ec2ed1f3d

**Comment by amiya-pattnaik** [comment]
Thanks a lot for your support. I appreciate your help and guidance
Regards,
Amiya
