### ISSUE TITLE
Add diagram(s) for faster grokking

### ISSUE THREAD

**Issue by UnityOfFairfax** [webdriverio/webdriverio#4490]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Description of the improvement / report**
A clear and concise description.

Diagrams, done properly, can communicate a lot of information in a short amount of time.

As a new user to WebdriverIO, I am still trying to understand how all these pieces fit together:

* TestRunner
* Driver(s) / Services
* Reporters
* [ etc. ]

I know that these pieces _do_ fit together, but not necessarily _how_.  

For example, I’m trying to test some code for a browser extension.  I updated the config file with:

```js
chromeDriverArgs: [`--load-extension=${path.resolve(__dirname, '/build')}`]
```
, but I do not see the extension present when the driver spins up Chrome.  So, I set the `logLevel` to `debug` to see if I could spot whether the `--load-extension` option is getting passed to the driver.  I did not see it in the logs.  

Don’t worry about addressing that example issue for now.  (I’ll keep tinkering.)  But when issues like this happen, sometimes a picture of how the components of this system fit together would help a lot of people by pointing them in the right direction when they start debugging. 

----
**EDIT:** Fixed formatting SNAFU in the `chromeDriverArgs` snippet.

**Comment by christian-bromann** [comment]
Closing as we are already working on such a graph in #3387

**Comment by jdavis61** [comment]
@UnityOfFairfax please see my 9/20/2019 comment in [3887](https://github.com/webdriverio/webdriverio/issues/3387) for the latest version of the WebdriverIO 5 flow charts. Still a work in process but maybe they will help you grok this system.

Also please review all pdf's I have created in this issue and offer feedback on how they may be improved. Please provide suggestions, feedback is needed!!!

**Comment by jdavis61** [comment]
@UnityOfFairfax I would suggest reviewing the `index.js` and `run.js` files in the [wdio/cli](https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-cli) and [wdio/local-runner](https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-local-runner) repos, `index.js` in [wdio/runner](https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-runner), [wdio/repl](https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-repl) and [webdriverio](https://github.com/webdriverio/webdriverio/tree/master/packages/webdriverio) ones if you want to understand WebdriverIO better. 

As far as I know these are the WebdriverIO core packages.
