### ISSUE TITLE
How to execute test from gitlab ci?

### ISSUE THREAD

**Issue by pipeddev** [webdriverio/webdriverio#4495]
I need execute the tests in gitlab ci, but not find the solution, i create one pipeline with a services of selenium-standalone, npm run test, but the messages error is not connect with services.
example gitlab-ci.yml
image: node:8

stages:
  - test
  
test:
  stage: test  
  services:
    - selenium/standalone-chrome:3.13
  script:    
    - npm install
    #- type=docker  npm run test-example
    - npm run test --host=selenium__standalone-chrome
    #- npm run test-ci

A clear and concise question that doesn't require too much conversation. Need more help? [Find us on Gitter](https://gitter.im/webdriverio/webdriverio)

**If it's about a specific piece of code, try and include some of it to support your question.**
[...]

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 5.12.5]
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version: 11.13.0
 - **NPM version:6.10.3
 - **Browser name and version: 76
 - **Platform name and version: Mac Mojave 10.14.6 (18G95)
 - **Additional wdio packages used (if applicable):** "@wdio/cli": "^5.11.13",
    "@wdio/dot-reporter": "^5.11.7",
    "@wdio/local-runner": "^5.11.13",
    "@wdio/mocha-framework": "^5.11.0",
    "@wdio/selenium-standalone-service": "^5.11.2",
    "@wdio/sync": "^5.11.13",
    "chromedriver": "^76.0.1",
    "wdio-chromedriver-service": "^5.0.2",
    "wdio-docker-service": "^2.1.2"

**Additional context**

**Comment by GuruMahadev999** [comment]
@fcarrasco92,

Did you resolve the issue. I tried to integrate webdriver.io with giltlab. But couldn't do it.

**Comment by mgrybyk** [comment]
@GuruMahadev999 there is nothing specific with GitLab pipelines in comparison to any others.
Please see example https://gitlab.com/bar_foo/wdio-cucumber-typescript

**Comment by fcarrasco92** [comment]
@GuruMahadev999  I integrated another tool called Selenoid and I did the configuration.

@mgrybyk thanks friend, I will check that repository

**Comment by GuruMahadev999** [comment]
@mgrybyk  Thank you.

**Comment by syamphaneendra** [comment]
@GuruMahadev999 Could you please share the Selenoid integration with webdriverio. I am struggling to setup the gitlab pipeline with webdriverio. Looks like the selenium standalone chome image requires some more configurations.
