### ISSUE TITLE
Failure in background section of cucumber are not passed to the right step 

### ISSUE THREAD

**Issue by fege** [webdriverio/webdriverio#4500]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [5.12.4]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [10.15.2]
 - **NPM version:** [6.4.1]
 - **Browser name and version:** [ANY]
 - **Platform name and version:** [ANY]
 - **Additional wdio packages used (if applicable):** [
"chai": "4.2.0"
"@wdio/cucumber-framework": "5.12.3",
"@wdio/dot-reporter": "5.12.1",
"@wdio/spec-reporter": "5.12.1",
"@wdio/local-runner": "5.12.4",
"@wdio/sync": "5.12.3",
"@wdio/utils": "5.12.1",
"@wdio/cli": "5.12.4",
"@wdio/config": "5.12.1"]

**Config of WebdriverIO**
```
    reporters: [
      'dot'
      ],
```

same with

```
    reporters: [
      'spec'
    ],

```
**Describe the bug**
When chai fails the assertion in the background section the error is showed for the successive step assertion

**To Reproduce**
```
Feature: Find

	Background:
		Given I am on the "Login" page
		When I type "test2" username
		Then the username text input has value "test234"
		When I type "doe" password
		Then the password text input is not empty
		When I click the "Login" button on the "Login" page

	@bug
	Scenario: Reproduce bug
		When I click the "bug" button on the "Bug" page
		Then I see a "bug" category
```
![Screen Shot 2019-09-16 at 4 09 47 PM](https://user-images.githubusercontent.com/2109860/64965185-d3b71680-d89c-11e9-9093-f2632783b6bf.png)

![Screen Shot 2019-09-16 at 4 14 20 PM](https://user-images.githubusercontent.com/2109860/64965348-17118500-d89d-11e9-8288-bc64726ed1b0.png)

![Screen Shot 2019-09-16 at 4 16 11 PM](https://user-images.githubusercontent.com/2109860/64965466-57710300-d89d-11e9-9bed-b5886c067495.png)

same for dot reporter 

![Screen Shot 2019-09-16 at 4 16 53 PM](https://user-images.githubusercontent.com/2109860/64965503-6b1c6980-d89d-11e9-8df5-d2a8e90084a8.png)

**Expected behavior**
Mark red the the correct step where the assertion failed
`Then the username text input has value "test234" 
`
for the spec reporter
or the 3rd dot in the dot reporter 

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by mgrybyk** [comment]
gonna be fixed with the PR
