### ISSUE TITLE
Logging with logLevel "trace", "debug" or "info" shows basically no difference, and absolutely no difference between "warn", "error" and "silent"

### ISSUE THREAD

**Issue by raketenolli** [webdriverio/webdriverio#4513]
**Environment (please complete the following information):**
 - **WebdriverIO version:** ^5.12.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.15.3
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome 76
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/cli, @wdio/jasmine-framework, @wdio/local-runner, @wdio/selenium-standalone-service, @wdio/spec-reporter, @wdio/reporter, @wdio/sync
- **Test framework:** jasmine

**Config of WebdriverIO**
relevant part of `wdio.conf.js` is IMO
`logLevel: 'error', // trace | debug | info | warn | error | silent`

**Describe the bug**
The console output for the `trace`, `debug` and `info` log levels only vary by three lines starting with "DEBUG" between debug and info, trace and debug produce exactly the same output. In all three cases the output for the example spec is ~125 lines, a lot of it seems to be the complete source executed for certain commands (which includes further, non-parsed, line breaks), like `executeScript("return (function isElementDisplayed(element) { [...]`.
For `warn`, `error` and `silent` the output is exactly the same, consisting of
```
[0-0] RUNNING in chrome - C:\dev\eclipse-workspace\minimum_wp_example\spec\wp.spec.js
[0-0] Error in "undefined"
Expected 'Selenium' to contain '(software)'.
[0-0] FAILED in chrome - C:\dev\eclipse-workspace\minimum_wp_example\spec\wp.spec.js
```
and the spec reporter output.

**To Reproduce**

- `git clone https://github.com/raketenolli/minimum_wp_example.git`
- `npm install`
- `npm run test -- --spec wp`

**Expected behavior**
Maybe my spec does not produce any other output, but I would expect more variation in the level of detail of the output depending on the log level.
For example less detailed output about the commands that were executed, or only command without data etc.

**Log**
See the `w.*.log` files for the respective log levels in the repo.

**Additional context**
(none)

**Comment by christian-bromann** [comment]
There is not much variation in our log levels right now. I don't necessarily see this as a bug. We have a couple of `warn` messages which are usually not hit a lot.

**Comment by mhio** [comment]
I guess https://github.com/webdriverio/webdriverio/issues/4433 is a dupe of this. 

I'm getting a lot of:
```
2019-09-23T08:55:10.354Z INFO webdriverio: Initiate new session using the webdriver protocol
```
in my spec output. It would be useful if at least `silent` turned it off.

**Comment by dtboy1995** [comment]
After the log level is set to silence, there will still be a lot of log output

**Comment by rpii** [comment]
I set the log level to debug.  not much else was generated.  
[wdio-0-0.log](https://github.com/webdriverio/webdriverio/files/12443725/wdio-0-0.log)

So I assume you would need a sample project?

**Comment by rpii** [comment]
[wdio-e2e-test.zip](https://github.com/webdriverio/webdriverio/files/12443885/wdio-e2e-test.zip)
Thats wasnt so bad.  this should reproduce it.
