### ISSUE TITLE
Allure option `useCucumberStepReporter: true` providing `undefined` status with skipped test

### ISSUE THREAD

**Issue by espekkaya** [webdriverio/webdriverio#4514]
**Environment (please complete the following information):**
WebdriverIO version: 5.13.1
Mode: WDIO Testrunner
If WDIO Testrunner, running sync/async: sync
Node.js version: 10.15.3
NPM version: 6.10.2
Browser name and version: Chrome 68
Platform name and version: Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/allure-reporter, @wdio/cucumber-framework

**Describe the bug**

When the Allure report with the option useCucumberStepReporter: true is used, the status of a skipped test becomes undefined, then the useCucumberStepReporter: true is not provided the status of the skipped test is skipped which is correct.

I think that generated xml file has somtihng wrong.

`` <test-case start='1568990549787' status='undefined'> `` 

**To Reproduce**

```
exports.config = {
  //...
     reporters: [
        'spec',
        ['allure', {
            outputDir: '.tmp/allure-result',
            disableWebdriverStepsReporting: true,
            disableWebdriverScreenshotsReporting: true,
            useCucumberStepReporter: true
        }],
    ],
  //...
}
```

```
@feature-tag
Feature: Create passed feature
    the description

    @scenario-tag
    Scenario: Open website
        Given I open "http://webdriver.io/"
        Then the title would say "WebdriverIO · Next-gen WebDriver test framework for Node.js"

    @scenario-tag
    Scenario: Open other website
        Given I open "https://developer.mozilla.org/nl/"
        Then the title would say "MDN-webdocumenten"
```

```
// Steps
import { Given,Then } from 'cucumber';

Given(/I open "(.*)"/, function (url) {
    return 'skipped';
});
Then(/the title would say "(.*)"/, title => {
    expect(browser.getTitle()).to.equal(title);
});
```

**Expected behavior**
Test case status is skipped not unknown like when the Allure option useCucumberStepReporter: false

**Additional context**
@Kignuf added  [Pull Request](https://github.com/webdriverio/webdriverio/pull/4420) but it was not resolved the bug.

**Comment by mgrybyk** [comment]
I think it might be  because allure reporter package version was not bumped and the fix is in version 5.13.1 alpha
