### ISSUE TITLE
Does `browser.execute()` only return primitives?

### ISSUE THREAD

**Issue by Zearin** [webdriverio/webdriverio#4515]
## Caveats

* Omitting version info (as it’s irrelevant to question)
* I’ve been learning WebdriverIO lately, so I’m inexperienced. Go easy on me. :)

## Background

I’ve been trying to return a JavaScript object from the result of a call to `browser.execute()`.

Using the `--inspect` flag on the command line with longer timeouts, and the ever-so-handy `browser.debug()` method, I verified that the object is being created in the browser context.  It’s just not being returned by `browser.execute()`.

The errors I’m getting show that the returned value is `[ null ]`.

After some frustration, it occurred to me that the error was showing _an array_ containing `null`—not `null` by itself.  

Although I am doing all my testing locally, I finally remembered that a lot of this style of testing is based around distributing tests to lots of machines. And I began to wonder…

## THE QUESTION

**Does `browser.execute()` return only primitives and/or JSON-serializable values?**

## The Implication

I read and re-read and re-re-read the [`API docs for `browser.execute()`](https://webdriver.io/docs/api/browser/execute.html).  

If the answer to my question is “Yes”, then the docs should make this crystal clear. Maybe these documents were written from the perspective of someone who is already familiar with the Selenium Webdriver + friends that WebdriverIO is based on.  But I’m not familiar with those things.  

 I think this is a good project, and I want it to do well.  In _any_ project, if the docs omit some critical piece of information that would have saved me a lot of time and frustration, it makes me less likely to stick with that project.

Don’t worry—I want to stick with this project!  I’m saying that it’s important to prevent that situation in order to provide newcomers with the positive experience that we all want.

Of course, if the answer to my question is “No”…then, I am baffled!  And I’ll open a separate Issue with more details specific to my situation.

**Comment by mgrybyk** [comment]
Browser execute may return objects, what are you trying to achieve? 

I'd suggest using gitter for such questions

**Comment by christian-bromann** [comment]
> The errors I’m getting show that the returned value is `[ null ]`.

Can you provide an example of what you exactly did?

> Does `browser.execute()` return only primitives and/or JSON-serializable values?

Short answer: yes! As the script is being executed in the context of a browser, WebDriver (the protocol) serializes the result to get it over the wire. If an object is not serializable you will receive `{}`.

> with the Selenium Webdriver + friends that WebdriverIO is based on

WebdriverIO is __not__ based on Selenium Webdriver! It is an independent implementation of the WebDriver protocol.

> if the docs omit some critical piece of information that would have saved me a lot of time and frustration

I am not sure if these kind of primitive information should be in the WebdriverIO docs given that user can read about it in [the spec](https://w3c.github.io/webdriver/). I am not saying the docs are perfect and we can sure improve on them. Please provide a PR or let us know where and we are happy to work on it.

> Of course, if the answer to my question is “No”…then, I am baffled!

Which question?
