### ISSUE TITLE
multiremote is not working with browserstack

### ISSUE THREAD

**Issue by SuchitraK** [webdriverio/webdriverio#4519]
**Logs when switch to frame works fine with capability used as an array :**
capabilities: [
    {
      'os' : 'OS X',
      'os_version' : 'Mojave',
      'browserName' : 'Chrome',
      'browser_version' : '72.0',
      'browserstack.local' : 'true',
      'browserstack.selenium_version' : '3.5.2'
    }]
[1-0] 2019-09-19T21:05:27.596Z INFO webdriver: COMMAND findElement("css selector", "body #tfs_interaction_iframe")
[1-0] 2019-09-19T21:05:27.596Z INFO webdriver: [POST] https://hub-cloud.browserstack.com:443/wd/hub/session/b56d7865a0944ece3acd4a2cbc33364844389af6/element

[1-0] 2019-09-19T21:05:27.596Z INFO webdriver: DATA { using: 'css selector', value: 'body #tfs_interaction_iframe' }
[1-0] 2019-09-19T21:05:27.726Z INFO webdriver: RESULT { ELEMENT: '2' }
[1-0] 2019-09-19T21:05:27.729Z INFO webdriver: COMMAND switchToFrame(<object>)
[1-0] 2019-09-19T21:05:27.729Z INFO webdriver: [POST] https://hub-cloud.browserstack.com:443/wd/hub/session/b56d7865a0944ece3acd4a2cbc33364844389af6/frame
[1-0] 2019-09-19T21:05:27.729Z INFO webdriver: DATA { id:
   Element {
     sessionId: 'b56d7865a0944ece3acd4a2cbc33364844389af6',
     elementId: '2',
     ELEMENT: '2',
     selector: 'body #tfs_interaction_iframe',
     parent:
      Browser {
        sessionId: 'b56d7865a0944ece3acd4a2cbc33364844389af6',
        capabilities: [Object],
        addCommand: [Function],
        overwriteCommand: [Function],
        config: [Object],
        _NOT_FIBER: true },
     emit: [Function: bound ],
     addCommand: [Function],
     overwriteCommand: [Function] } }

**When capabilities is used as an object as in multiremote.** 
capabilities: {
    clientBrowser: {
         desiredCapabilities: {
           browserName: 'chrome'
         }
       },
       agent: {
         desiredCapabilities: {
           browserName: 'firefox'
         }
       }
     },
**following error is displayed**
[0-0] 2019-09-19T20:58:21.252Z INFO webdriver: COMMAND findElement("css selector", "#tfs_interaction_iframe")
[0-0] 2019-09-19T20:58:21.254Z INFO webdriver: [POST] http://127.0.0.1:4444/session/da7778914476c67de2c03f17b20aa602/element
[0-0] 2019-09-19T20:58:21.254Z INFO webdriver: DATA { using: 'css selector', value: '#tfs_interaction_iframe' }
[0-0] 2019-09-19T20:58:21.265Z INFO webdriver: RESULT { error: 'no such element',
  message:
   'no such element: Unable to locate element: {"method":"css selector","selector":"#tfs_interaction_iframe"}\

0-0] 2019-09-19T20:58:21.283Z INFO webdriver: [POST] http://127.0.0.1:4444/session/3f9f86f716b5541c3c84d17c7cfc230a/frame
[0-0] 2019-09-19T20:58:21.283Z INFO webdriver: DATA { id:
   Element {
     client:
      Element {
        sessionId: '3f9f86f716b5541c3c84d17c7cfc230a',
        elementId: 'f1df6fba-9ea3-4bea-85bd-fd607cac1bce',
        'element-6066-11e4-a52e-4f735466cecf': 'f1df6fba-9ea3-4bea-85bd-fd607cac1bce',
        selector: '#tfs_interaction_iframe',
        parent: [Browser],
        emit: [Function: bound ],
        addCommand: [Function],
        overwriteCommand: [Function] },
     agent:
      Element {
        sessionId: 'da7778914476c67de2c03f17b20aa602',
        error: [Object],
        selector: '#tfs_interaction_iframe',
        parent: [Browser],
        emit: [Function: bound ],
        addCommand: [Function],
        overwriteCommand: [Function] },
     instances: [ 'client', 'agent' ],
     addCommand: [Function],
     overwriteCommand: [Function] } }
[0-0] 2019-09-19T20:58:21.287Z ERROR webdriver: Request failed due to invalid argument: invalid argument: missing 'ELEMENT'
  (Session info: chrome=77.0.3865.75)
    at getErrorFromResponseBody (/Users/suchitra.kunnath/udeforks/assist-agent-driver/node_modules/webdriver/build/utils.js:215:10)
    at Request._callback (/Users/suchitra.kunnath/udeforks/assist-agent-driver/node_modules/webdriver/build/request.js:103:64)
    at Request.self.callback (/Users/suchitra.kunnath/udeforks/assist-agent-driver/node_modules/request/request.js:185:22)
    at Request.emit (events.js:197:13)
    at Request.EventEmitter.emit (domain.js:439:20)
    at Request.<anonymous> (/Users/suchitra.kunnath/udeforks/assist-agent-driver/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:197:13)
    at Request.EventEmitter.emit (domain.js:439:20)
    at IncomingMessage.<anonymous> (/Users/suchitra.kunnath/udeforks/assist-agent-driver/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:285:13)
[0-0] invalid argument in "Validate Assist Methods setAgentStatusToavailable"
invalid argument: missing 'ELEMENT'
  (Session info: chrome=77.0.3865.75)

**Comment by mgrybyk** [comment]
Can you please provide with reproducible example?
Here is how it works for me
```
describe("main suite", () => {
    it("some test", () => {
        browser.url("http://guinea-pig.webdriver.io/two.html")

        const chromeFrame = CH.$('iframe[name="vimeoframe"]')
        const firefoxFrame = FF.$('iframe[name="vimeoframe"]')

        CH.switchToFrame(chromeFrame)
        FF.switchToFrame(firefoxFrame)

        $('#player').waitForDisplayed()
    })
})
```

**Comment by SuchitraK** [comment]
Here is the example code

capabilities: {
    client: {
        capabilities: {
          'os' : 'OS X',
                'os_version' : 'Mojave',
                'browserName' : 'Chrome',
                'browser_version' : '72.0',
                'browserstack.local' : 'true',
                'browserstack.selenium_version' : '3.5.2'
        }
    },
    agent: {
        capabilities: {
          'os' : 'OS X',
                'os_version' : 'Mojave',
                'browserName' : 'Chrome',
                'browser_version' : '75.0',
                'browserstack.local' : 'true',
                'browserstack.selenium_version' : '3.5.2'
        }
    }
    } 
 client.url("");
 client.$("#initialized").waitForExist(5000);
 client.$("#existingchat").click();
client.switchToFrame($('body #tfs_interaction_iframe'));

**Comment by mgrybyk** [comment]
@SuchitraK unable to reproduce it locally.
Does it work for you locally? If yes then you have configured browserstack incorrectly, if no - there are some issues with your setup

**Comment by mgrybyk** [comment]
@SuchitraK according to the log element is not found, can't see any browserstack / multiremote specific issues

**Comment by SuchitraK** [comment]
Works fine after using it in the way suggested by @mgrybyk . You could close the issue

const frame = client.$('iframe[id="idOfFrame"]');
       client.switchToFrame(frame);

**Comment by mgrybyk** [comment]
Amazing!

**Comment by RajaBellebon** [comment]
Hello, I have somehow the same issue.

We are using WebdriverIo v5 and browserstack, it works fine locally and on browserstack but we are recently trying to use `multiremote` and not sure why but it keeps trying to connect to `selenium-hub`.
The function below returns the config, we are using for remote.

We have a function that connects to browserstack-local
```
async function startServer() {
  const spinner = ora(chalk.cyan('Connecting to BrowserStack')).start();
  return new Promise((resolve, reject) => {
    bsLocal.start(
      { key: bsKey, localIdentifier: commit, forceLocal: true },
      // eslint-disable-next-line consistent-return
      error => {
        if (error) {
          spinner.fail(chalk.red('Failed to connect to BrowserStack:', error));
          return reject(error);
        }
        if (commit) {
          spinner.succeed(
            chalk.cyan(`Connected to BrowserStack with identifier: ${commit}`),
          );
        }
        resolve();
      },
    );
  });
}
```
We created a dedicated function to create the client for mulit-remote

```
function setBrowserstackClientForRemote() /*: Array<?Object>*/ {
  const RESOLUTION = '1920x1080';
  return [
    {
      browserName: 'chrome',
      options: {
        capabilities: {
          os: 'Windows',
          os_version: '10',
          browserName: 'chrome',
          browser_version: '80.0',
          resolution: RESOLUTION,
          project: 'Atlaskit Webdriver Tests',
          build: BUILD_BRANCH_NAME,
          'browserstack.local': true,
          'browserstack.debug': true,
          'browserstack.idleTimeout': 300,
          'browserstack.localIdentifier': commit,
          user: process.env.BROWSERSTACK_USERNAME,
          key: process.env.BROWSERSTACK_KEY,
        },
      },
      services: ['browserstack'],
      logLevel: 'error',
      user: process.env.BROWSERSTACK_USERNAME,
      key: process.env.BROWSERSTACK_KEY,
      waitforTimeout: 3000,
    },
  ];
}```


When running with logging the command


  console.info node_modules/@wdio/logger/build/node.js:114
    2020-04-14T06:51:05.989Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session

  console.info node_modules/@wdio/logger/build/node.js:114
    2020-04-14T06:51:05.990Z INFO webdriver: DATA {
      capabilities: {
        alwaysMatch: {
          os: 'Windows',
          os_version: '10',
          browserName: 'chrome',
          browser_version: '80.0',
          resolution: '1920x1080',
          project: 'Atlaskit Webdriver Tests',
          build: 'rbellebon_local_run',
          'browserstack.local': true,
          'browserstack.debug': true,
          'browserstack.idleTimeout': 300,
          'browserstack.localIdentifier': 'rbellebon',
           user: xxxxx,
          key:xxxxxx,
          services: [Array],
          name: 'collab.ts'
        },
        firstMatch: [ {} ]
      },
      desiredCapabilities: {
        os: 'Windows',
        os_version: '10',
        browserName: 'chrome',
        browser_version: '80.0',
        resolution: '1920x1080',
        project: 'Atlaskit Webdriver Tests',
        build: 'rbellebon_local_run',
        'browserstack.local': true,
        'browserstack.debug': true,
        'browserstack.idleTimeout': 300,
        'browserstack.localIdentifier': 'rbellebon',
        user: xxxxx,
          key:xxxxxx,
        services: [ 'browserstack' ],
        name: 'collab.ts'
      }
    }

  console.info node_modules/@wdio/logger/build/node.js:114
    2020-04-14T06:51:05.993Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session

  console.info node_modules/@wdio/logger/build/node.js:114
    2020-04-14T06:51:05.993Z INFO webdriver: DATA {
      capabilities: {
        alwaysMatch: {
          os: 'Windows',
          os_version: '10',
          browserName: 'chrome',
          browser_version: '80.0',
          resolution: '1920x1080',
          project: 'Atlaskit Webdriver Tests',
          build: 'rbellebon_local_run',
          'browserstack.local': true,
          'browserstack.debug': true,
          'browserstack.idleTimeout': 300,
          'browserstack.localIdentifier': 'rbellebon',
           user: xxxxx,
          key:xxxxxx,
          services: [Array],
          name: 'collab.ts'
        },
        firstMatch: [ {} ]
      },
      desiredCapabilities: {
        os: 'Windows',
        os_version: '10',
        browserName: 'chrome',
        browser_version: '80.0',
        resolution: '1920x1080',
        project: 'Atlaskit Webdriver Tests',
        build: 'rbellebon_local_run',
        'browserstack.local': true,
        'browserstack.debug': true,
        'browserstack.idleTimeout': 300,
        'browserstack.localIdentifier': 'rbellebon',
         user: xxxxx,
          key:xxxxxx,
        services: [ 'browserstack' ],
        name: 'collab.ts'
      }
    }


  ●  Cannot log after tests are done. Did you forget to wait for som
ething async in your test?
    Attempted to log "REJECTION Error: connect ECONNREFUSED 127.0.0.1:4444
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14) {
      errno: 'ECONNREFUSED',
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 4444
    }".

      37 | // Node promise rejection are now logged for debbugging
      38 | process.on('unhandledRejection', reason => {
    > 39 |   console.log('REJECTION', reason);
         |           ^
      40 | });
      41 | 
      42 | // We need to ensure that each test has at least one assertion.

      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14) {
        errno: 'ECONNREFUSED',
        code: 'ECONNREFUSED',
        syscall: 'connect',
        address: '127.0.0.1',
        port: 4444
      }".
      at CustomConsole.log (node_modules/@jest/console/build/CustomConsole.js:186:10)
      at process.<anonymous> (jestFrameworkSetup.js:39:11)
      at processEmit [as emit] (node_modules/signal-exit/index.js:155:32)

 FAIL  packages/editor/collab-provider/src/__tests__/integration/col
lab.ts (6.867s)
  collab.ts
    Chrome
      ✕ Enter simple strings between 2 tabs (23ms)

  ● collab.ts › Chrome › Enter simple strings between 2 tabs

    connect ECONNREFUSED 127.0.0.1:4444



Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        10.767s
Ran all test suites matching /\/Users\/rbellebon\/atlassian-frontend\/packages\/editor\/collab-provider\/src\/__tests__\/integration\/collab.ts/i.
Exiting tests with exit code: 1
Disconnecting from BrowserStack
error Error
error     at ChildProcess.<anonymous> (/Users/rbellebon/.config/yarn/global/node_modules/bolt/dist/modern/utils/processes.js:124:16)
➜  atlassian-frontend git:(master) ✗ 
```
