### ISSUE TITLE
Add 'yes' flag to wdio/cli config command

### ISSUE THREAD

**Issue by baruchvlz** [webdriverio/webdriverio#4522]
**Is your feature request related to a problem? Please describe.**
If we want to minimise the time it takes to create a WDIO project, adding a `--yes` flag to the config command might help.

Similar to `npm init -y`

**Describe the solution you'd like**
Running `wdio config --yes` or `wdio config -y` should ignore the questionnaire and use the default values to create a wdio.conf.js file 

**Additional context**
Should wait for #4402 to be merged.

**Comment by schuttsm** [comment]
@baruchvlz @christian-bromann  https://github.com/webdriverio/webdriverio/pull/4546

See my question about where to add a test for that feature

**Comment by baruchvlz** [comment]
@schuttsm 

Thanks for taking time to do this. As it is mentioned in the issue, this is better to do __after__ #4402  is merged since that PR is changing the structure of the wdio/cli package and also adding tests to the commands.

**Comment by schuttsm** [comment]
@baruchvlz @christian-bromann thank you for the feedback on #4546.  I closed that one due to all the merge conflicts & copied the changes into https://github.com/webdriverio/webdriverio/pull/4576.  Can you take a look?

**Comment by christian-bromann** [comment]
Let's continue convo in the PR
