### ISSUE TITLE
When run the test runner programmatically, reporters outputFileFormat not worked

### ISSUE THREAD

**Issue by ForeverSc** [webdriverio/webdriverio#4525]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.12.5
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.15.1
 - **NPM version:** 6.4.1
 - **Browser name and version:** Appium 1.14.2
 - **Platform name and version:** MacOS 10.13.3
 - **Additional wdio packages used (if applicable):** @wdio/cli

**Config of WebdriverIO**
```js
const Launcher = require('@wdio/cli').default

new Launcher('wdio.conf.js', {
  reporters: [
    'spec',
    ['mochawesome',{
      outputDir: './Results',
      outputFileFormat: function(opts) {
          // not worked, output filename is default wdio-0-0-mochawesome-reporter.log
          return `results-${opts.cid}.${opts.capabilities}.json`
      }
    }]
  ]
})
```

**Describe the bug**
When i use `Launcher` from `@wdio/cli`, i found `outputFileFormat` in `reporters` config not worked, output filename is default `wdio-0-0-mochawesome-reporter.log`.

Then I found the problem in `@wdio/local-runner`: [wdio-local-runner/src/worker.js#L159-L176](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-local-runner/src/worker.js#L159-L176), after `postMessage`, `outputFileFormat` lost.

`postMessage` use `child_process.send` method, but `child_process.send` can only post json object and  function will be lost.

**To Reproduce**
just use `Launcher` to run test programmatically
```js
const Launcher = require('@wdio/cli').default

new Launcher('wdio.conf.js', {
  reporters: [
    'spec',
    ['mochawesome',{
      outputDir: './Results',
      outputFileFormat: function(opts) {  // not worked
          return `results-${opts.cid}.${opts.capabilities}.json`
      }
    }]
  ]
})
```

**Expected behavior**
`outputFileFormat` worked or some other options like `outputFileName` can used to custom output filename  programmatically

**Comment by christian-bromann** [comment]
> ```js
> return `results-${opts.cid}.${opts.capabilities}.json`
> ```

This will result in `results-0-0.[Object].json`. Why do you need this function?

**Comment by christian-bromann** [comment]
> `postMessage` use `child_process.send` method, but `child_process.send` can only post json object and function will be lost.

Yeah, we won't be able to serialize this function properly. Why do you have to use the Launcher instead of calling wdio on a config file directly? Have you considered creating multiple config files?

**Comment by ForeverSc** [comment]
> > `postMessage` use `child_process.send` method, but `child_process.send` can only post json object and function will be lost.
> 
> Yeah, we won't be able to serialize this function properly. Why do you have to use the Launcher instead of calling wdio on a config file directly? Have you considered creating multiple config files?
> 
> I am closing this as I don't see this as a bug and more as a technical limitation that can be fixed by creating an extra config file.

Because i  use wdio in another node application,  `outputDir ` and `outputFileFormat` will be defined dynamically， so i can't use a static wdio config.
