### ISSUE TITLE
Is it cheaper to re-use same instance or create new one for each test within a suite?

### ISSUE THREAD

**Issue by grofit** [webdriverio/webdriverio#453]
I noticed an issue thread on using singleton, but it didnt really seem to address the benefits of either approach.

So currently in CucumberJS I have a `BeforeFeatures` and `AfterFeatures` which are run before any tests and after any tests. I will end up having quite a few tests, so would it be better to spawn up once with singleton and somehow just remove all cookies/local storage before each individual test or is it just cheaper to keep spawning a new client for each individual test?

I would have assumed the former is more performant but I could not find any info on my brief look as to how to clear all cookies and local storage so was wondering if someone could offer some direction here.

**Comment by christian-bromann** [comment]
@grofit Selenium doesn't really support to clear cache data (cookies or local storage) of a local Selenium session. I would recommend to create a new one every-time when cookies are involved. Even though it is not really performant but it is the best way to start a new clean test. In Safari for instance you can't even delete cookies as they get stored on OS level.
If you don't pick up any session data it is no problem to keep your existing Selenium session running.

**Comment by grofit** [comment]
I make heavy use of local storage and cookies, so no problem. I can get around the local storage issue by just doing a javascript execute to clear the local cache of my app, however there only seemed to be a delete cookie, not a delete all cookies method, which again is doable for me, but I would need to be a bit more manual about it.

Anyway thanks for the info.

**Comment by christian-bromann** [comment]
@grofit you can delete all cookies:

```js
// check out the deleteMultipleCookies.js example on http://webdriver.io/api/cookie/deleteCookie.html
client.deleteCookie()
```

However that doesn't work sufficient enough for couple of OS/browser combinations. Therefor creating a new session would be the best way.
