### ISSUE TITLE
I want to be able to write E2E tests with webdriver.io

### ISSUE THREAD

**Issue by christianhjelmslund** [webdriverio/webdriverio#4536]
What I want is the following:

Be able to create E2E tests, so each time I do something on the frontend I want to see if the backend received the expected value. This is going to be a part of CI and it needs to be as efficient as possible. When accessing our website one has to login. I have tried to split up my test suite into 11 files, but that means that 11 independent browser instances loads up and logs in. It simply doesn't work, I run this on a VM with docker containers and it crashes - it is not effective enough.

So to a start, I want to avoid having to login 11 times. I DON'T want to test the login function, I only have to do it to access the site. I think I would probably have a bash script running like this:
```
wdio wdio.conf.js --spec like_post.js
./check_if_post_was_liked.ex

wdio wdio.conf.js --spec write_post.js
./check_if_post_was_written.ex

wdio wdio.conf.js --spec send_message.js
./check_if_message_was_sent.ex
```
etc.

So here are 4 different ways I have thought about approaching this.

1) I want to be able to log in only once - so can I invoke a login.js and once that it finished execute the rest of the tests from that instance of a browser? How do I avoid to login 11 times parallely if I have 11 seperate files? So it would be like this:
```
wdio wdio.conf.js -- specc login.js // ONLY TO BE ABLE TO RUN THE REST OF THE COMMANDS

wdio wdio.conf.js --spec like_post.js
./check_if_post_was_liked.ex

wdio wdio.conf.js --spec write_post.js
./check_if_post_was_written.ex

wdio wdio.conf.js --spec send_message.js
./check_if_message_was_sent.ex
```
2) Otherwise, the another solution for me is to login and keep that browser open - then run:

`wdio wdio.conf.js --spec like_post.js`
which doesn't start a new session but just executes the commands on that browser I already have open and logged in with through login.js. So when the tests are done the browser is still alive.

and the backend test is run:

`./check_if_post_was_liked.ex`
and when that it executed it continues etc.

3) This could be cool for me: Have 1 browser, have 1 file like this and invoke each method individually. Is that possible? So if my test file looks like this:
```
describe('social network', () => {

    // Handles the process of logging in automatically - no assertions here
    it('login',() => {
        // logs in
    });

    // Testing the Minimum Time on Broadband
    it('like',() => {
        // like
    });

    it('writes',() => {
        // write
    });

    it('send',() => {
        // send
    });
});
```
and then run commands like this (if it is possible) without starting a new browser. Is there somehow a way I can call an "it" function? or a "describe"?

```
wdio wdio.conf.js .write()
wdio wdio.conf.js .like()
wdio wdio.conf.js .send()
```
4) The ideal solution is to login, keep the browser open and run all the tests in parallel on a single browser - so all of the above functions are ran in parallel in one browser.

**Comment by mgrybyk** [comment]
@christianhjelmslund if you want to avoid login 11 times there are multiple ways to do it with WebdriverIO same as with any other framework:
- run tests sequentially in one session
- login once*, save cookies/etc, reuse cookies in other tests
- I think you should be able to mock login with `devtools` automation protocol

* you can do it in whichever way works better for you:
- login with backend and save cookies 
- login with webdriverio before starting other tests, write cookies to file, reuse cookies in other tests


Closing the issue for now because it's not a defect
