### ISSUE TITLE
Watch mode broken using external chromedriver

### ISSUE THREAD

**Issue by jbblanchet** [webdriverio/webdriverio#4537]
**Environment:**
 - **WebdriverIO version:** 5.13.2 (but seems to have broken in cli >5.12.1)
 - **Mode:** Standalone
 - **If WDIO Testrunner, running sync/async:** N/A
 - **Node.js version:** 10.16.3
 - **NPM version:** yarn 1.17.3
 - **Browser name and version:** Chrome 76
 - **Platform name and version:** Ubuntu
 - **Additional wdio packages used (if applicable):** @wdio/cucumber-framework, @wdio/local-runner, @wdio/spec-reporter, wdio/sync

**Config of WebdriverIO**
See https://github.com/jbblanchet/2-browsers/tree/broken-watch from full repro example

**Describe the bug**
When running in watch mode, with chromedriver running independently, session is shut down with error message:
```
@wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'waitForSync' of undefined
    at Runner._shutdown (/home/jbb/temp/2-browsers/node_modules/@wdio/runner/build/index.js:207:25)
    at Runner.endSession (/home/jbb/temp/2-browsers/node_modules/@wdio/runner/build/index.js:254:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**To Reproduce**
With a chromedriver running on port 4444
```
git clone git@github.com:jbblanchet/2-browsers.git
cd 2-browsers
git checkout broken-watch
yarn
yarn test
```

**Expected behavior**
Browser session should stay open, like it does with the chromedriver service or it did prior to cli 5.12.2

**Comment by christian-bromann** [comment]
> * **WebdriverIO version:** 4.13.2 (but seems to have broken in cli >4.12.1)

Which version you exactly using? WebdriverIO v4.x doesn't work with `@wdio` packages

**Comment by jbblanchet** [comment]
Sorry about that, it should be 5.x everywhere.

From the package.json in the repro repo:
```

  "devDependencies": {
    "@wdio/cli": "^5.13.2",
    "@wdio/cucumber-framework": "^5.13.2",
    "@wdio/local-runner": "^5.13.2",
    "@wdio/spec-reporter": "^5.13.2",
    "@wdio/sync": "^5.13.2",
    "cucumber": "^5.1.0"
  }
```

I'll update the description

**Comment by christian-bromann** [comment]
PRs with a fix for this are appreciated.

**Comment by mgrybyk** [comment]
gonna be fixed with the PR and released afterwards, cheers!
