### ISSUE TITLE
How do you check for ajax http status code responses?

### ISSUE THREAD

**Issue by grofit** [webdriverio/webdriverio#454]
I have a lot of ajax based requests to a restful API and upon clicking a button it triggers an ajax call and I want to see if it returns a 200 (everythings ok) or a 401,403,404 etc.

I am sorry if this is a simple question but I cannot find anything around this area in the docs so is there a way to check what the status code was?

**Comment by christian-bromann** [comment]
@grofit using Selenium (and WebdriverIO) is not the right approach to test your API service. If a 401 appears and creates a warning message, you can check if that warning message is shown in the UI. In general try to test the result of that ajax request and not the ajax request itself.

**Comment by grofit** [comment]
I am not doing API testing in this scenario, I just wanted to do it as a shorthand way of verifying if the login was unsuccessful, as previously I have had problems with dynamic DOM elements (which act like growl style popups) previously as they would seemingly not be noticed when querying the DOM so I was historically (in another framework) looking for http status codes as a way to check it had failed and bomb out early if it failed.

I will see if I can do it the standard UI driven way here and come back if I have any issues.

**Comment by christian-bromann** [comment]
There is no command or general way to test if an ajax request was successful with Selenium. If you are testing a login form for instance you can try the following way: submit the form and wait for login form to be hidden. If login (and its corresponding ajax request) was successful the login form should disappear. If you want to check if a certain growl message appears just wait for that specific element.

**Comment by scabbiaza** [comment]
Agree with the author of this issue. I think before testing the text or element, it's better first to check the response.

For example: I want to ping some pages on the site to know they are accessible. I don't want to check the text on these pages, because it can be changed or I may don't know this text. So checking that server answered with `200` would be enough.
