### ISSUE TITLE
wdi-cli: chromedriver and selenium-standalone services are not exclusive 

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4540]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.13.2

**Describe the bug**
chromedriver and selenium-standalone are not exclusive anymore.
This is a regression.

**To Reproduce**
1. run `wdio config`
2. choose chromedriver and selenium-standalone on services

Actual Result:
it is allowed to choose both chromedriver and selenium-standalone

**Expected behavior**
chromedriver and selenium-standalone should be exclusive

**Comment by mgrybyk** [comment]
@baruchvlz can you please take a look?
It is a regression after https://github.com/webdriverio/webdriverio/commit/5272de38dfeb4f4fc0232a81fff116f6725d6c4a

I think it is somehow related to package filtering, not sure

**Comment by baruchvlz** [comment]
@mgrybyk Yea I'll take a look at it.

Are chromedriver and selenium-standalone the only ones that are exclusive? Or are there other combinations?

**Comment by mgrybyk** [comment]
@baruchvlz well, choosing these two together is a common mistake.
There gonna be different cases for sure, can't provide you with such information right now

**Comment by christian-bromann** [comment]
I think general cases are choosing 2 drivers (e.g. chromedriver and selenium standalone service) or having two or more cloud provider services also makes no sense. I guess this is difficult to generalise. Maybe we can add categories to them to help better identify their potential usage.

**Comment by baruchvlz** [comment]
> It is a regression after 5272de3 

I was looking at the commit to see if I could find what was removed, but I can't find it.

> I think it is somehow related to package filtering, not sure

Not quite, this can easily be done via inquirer with the `validate` option on the answers that require this type of check.

I have started working on this, but we'll need to merge #4402 first.
