### ISSUE TITLE
Control interface output

### ISSUE THREAD

**Issue by Krinkle** [webdriverio/webdriverio#4547]
**Environment:**
 - **WebdriverIO version:** 5.13.2
 - **If WDIO Testrunner, running mode:** sync
 - **Node.js:** 10.15.2 (with npm 6.5.0)
 - **Browser name and version:** Chromium 71
 - **Platform name and version:** Debian 9 Stretch

```
    "@wdio/cli": "5.13.2",
    "@wdio/devtools-service": "5.13.2",
    "@wdio/dot-reporter": "5.13.2",
    "@wdio/junit-reporter": "5.13.2",
    "@wdio/local-runner": "5.13.2",
    "@wdio/mocha-framework": "5.13.2",
    "@wdio/sauce-service": "5.13.2",
    "@wdio/sync": "5.13.2",
    "chromedriver": "73.0.0",
    …
    "wdio-chromedriver-service": "5.0.2",
    "webdriverio": "5.13.2"
```

**Config of WebdriverIO**
```
	logLevel: 'error',
	framework: 'mocha',
	reporters: [
		'dot',
		[ 'junit', {
			outputDir: logPath
		} ]
	],
```

Full config at [gerrit.wikimedia.org/g/mediawiki/core/+/refs/changes/41/539441/9](https://gerrit.wikimedia.org/g/mediawiki/core/+/refs/changes/41/539441/9/tests/selenium/wdio.conf.js).

**Describe the bug**

There is some other unknown reporter active and it appears to be preventing the "dot" reporter from reporting anything until everything is done, at which point a  `"dot" Reporter` section appears with all the output printed at once.

```
$ npm run selenium
> wdio ./tests/selenium/wdio.conf.js

Execution of 6 spec files started at 2019-09-29T03:24:45.248Z

Starting ChromeDriver 73.0.3683.20 (8e2b610813e167eee3619ac4ce6e42e3ec622017) on port 4444
[0-1] RUNNING in chrome - /tests/selenium/specs/page.js
[0-1] PASSED in chrome - /tests/selenium/specs/page.js
[0-2] RUNNING in chrome - /tests/selenium/specs/rollback.js
[0-2] PASSED in chrome - /tests/selenium/specs/rollback.js
[0-3] RUNNING in chrome - /tests/selenium/specs/specialrecentchanges.js
[0-3] PASSED in chrome - /tests/selenium/specs/specialrecentchanges.js
[0-4] RUNNING in chrome - /tests/selenium/specs/specialwatchlist.js
[0-4] PASSED in chrome - /tests/selenium/specs/specialwatchlist.js
[0-5] RUNNING in chrome - /tests/selenium/specs/user.js
[0-5] PASSED in chrome - /tests/selenium/specs/user.js

 "dot" Reporter:
....................

Spec Files:	 6 passed, 6 total (100% completed) in 00:03:50 
```

**To Reproduce**

`wdio ./tests/wdio.conf.js`

Full code at [gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/core/+/refs/changes/41/539441/9](https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/core/+/refs/changes/41/539441/9/tests/selenium).

**Expected behavior**

When developers run the test locally or in a CI environment, it is expected that the build output regularly reports progress from the chosen reporter (e.g. dots, or mocha).

I expect there to be little to no other output, and for the reporter's dots to gradually appear as each test case is being executed. Currently the output is silent until the suite is completed at which point all "progress" dots appear at once.

**Comment by mgrybyk** [comment]
This is an expected behaviour. Dot and spec reporters are printing out result in the end

**Comment by larstippmann** [comment]
It would be very useful to suppress all output with loglevel = silent (see #4840)

**Comment by RafalSkorka** [comment]
Looking into the history of the [interface.js](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-cli/src/interface.js) file, there was a console.log statement introduced in [this commit](https://github.com/webdriverio/webdriverio/commit/e27e6b6ad4d3f02872f48c6da804884edf96fdb6#diff-133e004860738e01d2d59eba1f9e88e3)
but later on multiple other places started to use it (`this.log`) even though there is a '@wdio/cli' logger defined and used.
I would also expect to silence any output from wdio-cli if I set the logLevel of it to 'silent'.

**Comment by christian-bromann** [comment]
Moving this discussion to #6730
