### ISSUE TITLE
devtools: e2e tests are failing occasionally 

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4548]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.13.2

**Describe the bug**
Our devtools e2e tests are failing occasionally (locally and in CI), we should identify the issue and resolve it.

**Log**
https://travis-ci.org/webdriverio/webdriverio/jobs/591519737

**Comment by mgrybyk** [comment]
After some analysis it appears that test `should switch to window created by DOM interaction` fails due to Puppeteer intermittent defect `We either navigate top level or have old version of the navigated frame` https://github.com/GoogleChrome/puppeteer/issues/3309
-

**Comment by christian-bromann** [comment]
It seems like we haven't seen a lot of these failure recently. I will close this.

**Comment by mgrybyk** [comment]
Actually the last failure was couple of days ago
