### ISSUE TITLE
How to test width in getElementSize() when using promises?

### ISSUE THREAD

**Issue by binarykitchen** [webdriverio/webdriverio#455]
Currently I have this

```
.getElementSize('.public_fixedDataTable_main').should.eventually.contain.keys('width')
```

but how can I test the width, i.E. making sure it's greater than 200px, within a promise?

**Comment by christian-bromann** [comment]
We might need to introduce other commands for that (e.g. `getHeight` and `getWidth`). This also might apply to some other commands as well.

**Comment by christian-bromann** [comment]
This will be solved with `v3` in the following way:

```js
client.getElementSize('.public_fixedDataTable_main').then(function(res) {
    return res.width;
}).should.eventually.be.equal(200)
```

Does this work for you? Don't like to introduce new (unnecessary) commands as we already have a pretty big API

**Comment by christian-bromann** [comment]
@binarykitchen so instead of introducing new commands I've chooses to rather add parameters to that command. Usage now looks like:

```js
client
        .getElementSize('.header-logo-wordmark').then(function(size) {
            console.log(size) // outputs: { width: 100, height: 200 }
        })
        .getElementSize('.header-logo-wordmark', 'width').then(function(width) {
            console.log(width) // outputs: 100
        })
        .getElementSize('.header-logo-wordmark', 'height').then(function(height) {
            console.log(height) // outputs: 200
        });
```

to assert something with one line just do

```js
client.getElementSize('.public_fixedDataTable_main', 'width').should.eventually.be.equal(200);
client.getElementSize('.public_fixedDataTable_main', 'height').should.eventually.be.equal(200);
```

Will get released with `v3`

**Comment by binarykitchen** [comment]
i think it's better to close the ticket when `v3` is out?

**Comment by christian-bromann** [comment]
Not sure but I think it is better to close the ticket so we have an idea how much we've accomplished in our [milestone](https://github.com/webdriverio/webdriverio/milestones)

**Comment by binarykitchen** [comment]
fair enough but i'd like to get notified when it's out. the only way i can think of are notifications from tickets i am subscribed to.
