### ISSUE TITLE
driver.startRecordingScreen() does not send parameters to Appium correctly

### ISSUE THREAD

**Issue by grant-mccarriagher** [webdriverio/webdriverio#4551]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.13.2
 - **Mode:** Standalone
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:** v12.10.0
 - **NPM version:** npm 6.10.3
 - **Browser name and version:** Appium v1.15.0, iOS 13.1
 - **Platform name and version:** macOS 10.14.5
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Describe the bug**
Webdriverio is sending the `startRecordingScreen()` parameters to the `start_recording_screen` Appium endpoint as individual params, but they need to be inside of an `options` argument.

Incorrect (current behavior):
`{"timeLimit":"1800","videoType":"libx264","videoQuality":"medium","videoFps":"30","bitRate":"20" }`

Correct:
`{"options": { "timeLimit":"1800","videoType":"libx264","videoQuality":"medium","videoFps":"30","bitRate":"20" } }`

**To Reproduce**

Try to start a screen recording like `driver.startRecordingScreen(undefined, undefined, undefined, undefined, undefined, '20000', 'libx264', 'medium', '30', '20');` and notice that the video recording does not use any of the params.

**Log**
Here's the appium log, CTRL-F for `ffmpeg` to see the relevant bits.
https://gist.github.com/grant-mccarriagher/9e3b8aba8b0bbdd37402a8e0f9b2f3fd

**Comment by christian-bromann** [comment]
fixed in PR
