### ISSUE TITLE
cucumber-framework: unbound step definition in background

### ISSUE THREAD

**Issue by de-robat** [webdriverio/webdriverio#4555]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.13.2
 - **Mode:** local runner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** tested on 10.15.3
 - **NPM version:** 6.4.1
 - **Browser name and version:** chrome 77
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/cucumber-framework, @wdio/selenium-standalone service

**Config of WebdriverIO**
to be seen in https://github.com/de-robat/example-wdio5-cucumber-tests

**Describe the bug**
When a step, that has not been defined in any of the step files is used in a Gherkin Background, than not the actual missing step is beeing reported as an error but the next step that acutally is bound.
This makes troubelshooting extremly difficult. I debugged it down to cucumber it self which is reporting the stepDefinition for the step in question as not existent and therefore returns a result for the step of beeing "undefined". But somwhere later down the pipe this simply is not beeing properly displayed. When the same setup is used as a scenario without the background desctiption, then the reporting is as expected.

**To Reproduce**
https://github.com/de-robat/example-wdio5-cucumber-tests#2nd-scenario

Disclaimer: I haven't got any good idea by now of how to properly catch the erroneously reported step, therefore the testsetup only shows the problem when running it and looking at the console output. I haven't managed to get a hook on seemingly sucessfully run steps and therefore could not setup the expectations programatically. Still the provided scenario should be sufficient to get an understanding of the problem.

This screenshot should help clarifying it further

![image](https://user-images.githubusercontent.com/7009867/65942703-23194d00-e42e-11e9-8793-fcc064f1c8c3.png)

**Expected behavior**
I would have expected that missing steps used in a background are reported properly too.

**Comment by mgrybyk** [comment]
Should be fixed with https://github.com/webdriverio/webdriverio/pull/4545

**Comment by de-robat** [comment]
Haha, that was a lot of work for this short and very pleasing answer :D Ty for the quick reply.

**Comment by christian-bromann** [comment]
Thanks for the great issue post! I wish it would have been an actual issue 😛 .. doing a release now
