### ISSUE TITLE
Promises in Jasmine?

### ISSUE THREAD

**Issue by binarykitchen** [webdriverio/webdriverio#456]
We are running our WebdriverIO based-Jasmine tests through a gulp-jasmine tasks. I am not so sure how to add promises here. I have included `require('chai-as-promised')` but I think this is wrong. Because Jasmine and Chai are different runners.

Can you advise me please what's the recommended way to run WebdriverIO-tests through gulp with promises?

**Comment by christian-bromann** [comment]
Not sure but Jasmine should support promised based test. If not you could use `chai-as-promised` and use that. This is not necessarily wrong because Jasmine is your test runner and `chai-as-promised` just an assertion library. Make sure you assign transferPromises in the following way:

```js
var chai = require("chai");
var chaiAsPromised = require("chai-as-promised");
chai.use(chaiAsPromised);
chai.should();

var client = require('webdriverio').remote({
    desiredCapabilities: {
        browserName: 'firefox'
    }
});
chaiAsPromised.transferPromiseness = client.transferPromiseness;

client.init().url('http://google.com');
client.getTitle().should.become('Google');
//...
```

**Comment by binarykitchen** [comment]
All good, I switched to Mocha and then the above did work for me.

**Comment by christian-bromann** [comment]
nice

**Comment by surekhacdk** [comment]
I tried using chai-as-promised but it didnt work for me

**Comment by christian-bromann** [comment]
@surekhacdk all commands are synchronous with wdio so no need to use chai-as-promised
