### ISSUE TITLE
Hooks are no longer passed the same object shape for the test parameter (missing fullTitle)

### ISSUE THREAD

**Issue by barrett-vegas-com** [webdriverio/webdriverio#4569]
**Environment:**
 - **WebdriverIO version:** introduced in 5.14.0
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 11.15.0
 - **NPM version:** 6.10.0
 - **Browser name and version:** Chrome 77 N/A
 - **Platform name and version:** macOS 10.14.6 N/A
 - **Additional wdio packages used (if applicable):** N/A

**Config of WebdriverIO**
Add an afterTest hook that uses https://github.com/blueimp/wdio-screen-commands to call `cmds.saveScreenshotByTest(test)`.

**Describe the bug**
Previously the test object instance that is passed into the afterTest hook had a `fullTitle` property. It no longer has that property so the screenshot filenames are getting output as `undefined`.

**To Reproduce**

Use https://github.com/blueimp/wdio-screen-commands `cmds.saveScreenshotByTest(test)` in and afterTest hook, or just try logging test.fullTitle directly from the afterTest hook.

**Expected behavior**
The `fullTitle` should exist on the test instance as it did prior to 5.14.0.

**Additional context**
I [first filed a bug in the wdio-screen-commands library](https://github.com/blueimp/wdio-screen-commands/issues/1) since it seemed like this was an intentional changed related to https://github.com/webdriverio/webdriverio/pull/4354

**Comment by mgrybyk** [comment]
@barrett-vegas-com gonna be fixed with the PR
