### ISSUE TITLE
Correct use of promises with webdriver io

### ISSUE THREAD

**Issue by grofit** [webdriverio/webdriverio#457]
So I keep getting some strange issues which *may* be down to certain webdriver io issues which are mentioned elsewhere (such as using `call` instead of `then` etc).

So I am using cucumberjs and have to adhere to callbacks, but within the scope I use promises, so here is an example handler:

```
this.When(/^I visit (.*)$/, function(url, callback) {
        var self = this;

        function isPageLoaded(timeout, callback) {
            // keep checking predicate until timeout or true
			// then do callback(true) or callback(false)
        };

        var completeUrl = "{1}{2}".assign(this.clientRoot, url);

        this.browser
            .url(completeUrl)
            .executeAsync(isPageLoaded, 5000, function(error, result) {
                if(error) { throw new Error(error); }
                if(!result.value) { throw new Error("Page did not load."); }
            })
            .then(callback)
            .catch(callback.fail);
    });
```

So in the above example I did try replacing it with:

```
        this.browser
            .url(completeUrl)
            .executeAsync(isPageLoaded, 5000)
			.should.eventually.be.true
			.then(callback)
			.catch(callback.fail)
```

However that blew up saying that the arguments could not be compared to true, as it returns session state stuff etc, anyway so I reverted back but noticed that in some cases the next step seems to get triggered even while I am still within this one which causes weird errors.

So my main question is around the last 2 lines where I tell cucumber that it has succeeded. Is the best practice to use `call` here and a `catch` or is there some other way to achieve the above?

(The page has lots of external templates so the isPageLoaded checks for a JS value on the page which indicates it has loaded all its content, each pages DOM content is different so this approach works on all our pages)

**Comment by grofit** [comment]
Anyone able to offer any guidance as it is touted as promises being a key aspect of this but I cannot find any information on how to best handle the quirks of the promise handling.

**Comment by grofit** [comment]
just a bump as this seems like something that should be pretty easy to answer, yet not clearly documented.

**Comment by christian-bromann** [comment]
@grofit sorry for not responding.

I recommend to just do:

```js
this.browser
            .url(completeUrl)
            .executeAsync(isPageLoaded, 5000, callback)
```

If `executeAsync` errors the first argument will be an object an your cucumber library should be smart enough to let the test fail. If you are interested in Cucumber tests, check out the [cucumber-boilerplate](https://github.com/webdriverio/cucumber-boilerplate) project ;-). Let me know if you have further questions.

**Comment by grofit** [comment]
Thanks for getting back to me, just one other thing. The question is more around the best way to handle the promise aspect of this, as currently I am using `then` everywhere, but I saw some mentions that `call` should be used, so should I be using `call` instead of `then` or should it all be ok with normal promise syntax?

**Comment by christian-bromann** [comment]
The only difference between `call` and `then` is that you have access to the result of the command you call then on. `call` just executes a sync function within the chain.

So if your use case is to notify your async test block that your command chain is done I would recommend to use `call`.

**Comment by christian-bromann** [comment]
In general the promise implementation in WebdriverIO is pretty much rudimental and its only purpose was to support async assertion libraries like [chai-as-promised](https://github.com/domenic/chai-as-promised/). I am currently working on `v3` which will have a new core and a way better promise support.

**Comment by grofit** [comment]
oh that sounds good, will keep my eye out for v3 then. Thanks again!

**Comment by amyjen** [comment]
so now v4 doesn't have promises?
