### ISSUE TITLE
Would be great to add a custom locator strategy

### ISSUE THREAD

**Issue by gemelgb** [webdriverio/webdriverio#4578]
**Is your feature request related to a problem? Please describe.**
I m using a UI framework that generates a virtual dom and I want to be able to add a new locator or custom strategy to achieve the retrieval of the dom elements based on the virtual dom properties and attributes.

**Describe the solution you'd like**
More or less an implementation exists for protractor called addLocator, something similiar for WDIO would be awesome.

**Describe alternatives you've considered**
Custom commands are limited and does not help me to achieve this. More or less would be possible if I can use the standard WDJS locator by.js. The WDIO provides an alternative to use js functions but I cannot pass any parameters. On the other hand if I use browser.execute still seem not to work because it cannot return an element which I can use especially for an Array of elements. Any alternative that i might not known?

**Comment by mgrybyk** [comment]
Can you please be more specific and provide with some detailed examples?

**Comment by christian-bromann** [comment]
> Any alternative that i might not known?

You can always create an element object by having a reference of it, e.g.

```js
const elemRef = browser.execute(() => ...)
const elem = $(elemRef)
```

> More or less an implementation exists for protractor called addLocator

I am not aware what Protractor is doing. Can you please explain?

**Comment by CrispusDH** [comment]
Here documentation from source:
```js
  /**
   * Add a locator to this instance of ProtractorBy. This locator can then be
   * used with element(by.locatorName(args)).
   *
   * @view
   * <button ng-click="doAddition()">Go!</button>
   *
   * @example
   * // Add the custom locator.
   * by.addLocator('buttonTextSimple',
   *     function(buttonText, opt_parentElement, opt_rootSelector) {
   *   // This function will be serialized as a string and will execute in the
   *   // browser. The first argument is the text for the button. The second
   *   // argument is the parent element, if any.
   *   var using = opt_parentElement || document,
   *       buttons = using.querySelectorAll('button');
   *
   *   // Return an array of buttons with the text.
   *   return Array.prototype.filter.call(buttons, function(button) {
   *     return button.textContent === buttonText;
   *   });
   * });
   *
   * // Use the custom locator.
   * await element(by.buttonTextSimple('Go!')).click();
   *
   * @alias by.addLocator(locatorName, functionOrScript)
   * @param {string} name The name of the new locator.
   * @param {Function|string} script A script to be run in the context of
   *     the browser. This script will be passed an array of arguments
   *     that contains any args passed into the locator followed by the
   *     element scoping the search and the css selector for the root angular
   *     element. It should return an array of elements.
   */
  addLocator(name: string, script: Function|string) {
  ...
   }
```
So, the main idea to add somewhere custom locator strategy, and then write smthg like:
```js
const element = $('customSelectorStrategyByButtonText: Search');
```
and it will launch custom method `customSelectorStrategyByButtonText('Search')` and return element at the end.

**Comment by baruchvlz** [comment]
@CrispusDH Wouldn't it better to add a method to the browser object that allows to add custom locators? Kind of like protractor does.

```ts
browser.customLocator(name: string, callback: (customArg: any, parentEl?: HTMLELement): WDIOElement
```

This way we don't have parse the selector string.

**Comment by christian-bromann** [comment]
@CrispusDH @gemelgb does my suggestion above helps to solve your use case? If so how would you propose to register and execute custom selector strategies. I would propose something along the lines of:

- have a addLocatorStrategy method as @baruchvlz suggested
```js
browser.addLocatorStrategy('myCustomStrategy',
    (selector) => document.querySelector(selector))
```
- and then be able to call it as follows:
```js
const elem = $('myCustomStrategy:body')
```
Note that this solution has the limitation of allowing only a single selector parameter that has to be from type string.

**Comment by gemelgb** [comment]
Hi @christian-bromann  yes that would be great, sorry for the delay!

When do you think you could provide it?

Thanks!

**Comment by gemelgb** [comment]
Can the single selector parameter be also a json object?

I have multiple properties which I want to pass:

var prop = { "property1": "value1", "property2": [ {"path": "valuePath"}, {"path": "valuePath"}, ...] }

**Comment by baruchvlz** [comment]
@gemelgb Yes, you will be able to pass any type to your arguments. That's what I'm suggesting [here](https://github.com/webdriverio/webdriverio/pull/4603#issuecomment-541207632).

Example:

```js
browser.addLocatorStrategy('myStrat', (stratArguments) => {
  const { selector } = stratArguments
  return document.querySelector(selector)
})

const divElement = browser.useLocatorStrategy('myStrat', { selector: 'div' })
```

Could also do `useLocatorStrategy` against an element, this will add a second argument to your strategy.

Example:

```js

browser.addLocatorStrategy('myStrat', (stratArguments, parentElement) => {
  console.log(stratArguments)
  console.log(parentElement)
})

const divEl = browser.$('div')

divEl.useLocatorStrategy('myStrat', 'foo-bar')
/**
  * output:
  * 'foo-bar'
  * DivElement {}
*/
```

**Comment by christian-bromann** [comment]
> ```js
> useLocatorStrategy
> ```

@baruchvlz what is the reason for switching to `useLocatorStrategy` instead of using `custom$` and `custom$$`? How do people know whether the function return one or multiple elements?

**Comment by christian-bromann** [comment]
Let's continue discussion in #4603
