### ISSUE TITLE
can not change focus to another frame on the page in the Internet Explorer

### ISSUE THREAD

**Issue by kusha1988** [webdriverio/webdriverio#458]
In my project I have a page with an iframe element. It is necessary to change focus on this frame and execute some tests. In the Chrome and Firefox all works correct. In the Internet Explorer it throws an error. As I understood, it wants to switch to the frame with id equals 8. But I have only one frame on the page, and its id should be equal 0.

Is it also a new Bug of the Selenium, as it was previously with the Firefox and 2.44 version of the Selenium server, or something else?

### Script
```javscript
var webdriverio = require('webdriverio');
var options = {
    desiredCapabilities: {
        browserName: 'internet explorer'
    }
};

webdriverio
    .remote(options)
    .init()
    .url(".....")
    .frame(0)
```

### Error
```javscript
(NoSuchFrame:8) A request to switch to a frame could not be satisfied because the frame could not be found.
     Problem: No frame found (WARNING: The server did not provide any stacktrace information)
```

### Browser and libs
```javscript
Internet Explorer 11
WebdriverIO v. 2.4.5
selenium-standalone v. 4.2.0 (this version uses Selenium standalone server 2.45)
```

**Comment by christian-bromann** [comment]
@kusha1988 interesting, have you tried a different approach to switch to the frame (e.g. using frame name or query it by using `element` command before)?

**Comment by kusha1988** [comment]
I have tried to user name of the frame. It was the same result.

**Comment by christian-bromann** [comment]
just curious, could you try to call the frame command twice? 

```js
webdriverio
    .remote(options)
    .init()
    .url(".....")
    .frame(0)
    .frame(0)
```

**Comment by kusha1988** [comment]
It does not work. It prints the same error message.

**Comment by EvanHahn** [comment]
I've had luck with IE9 on Sauce Labs, but I've had to specify the frame by its `name` attribute.

To clarify, if I have a frame like this:

```html
<iframe name="my-cool-frame"></iframe>
```

I can enter it like this:

```js
webdriverio
  .remote(options)
  .init()
  .url('...')
  .frame('my-cool-frame')
```

**Comment by christian-bromann** [comment]
@EvanHahn thanks for sharing. I think this is more iedriver related then WebdriverIO. Closing
