### ISSUE TITLE
root level tests are not shown in reporters in Jasmine

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4582]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.14.4

**Config of WebdriverIO**
```
framework: 'jasmine',
reporters: ['spec]'
```

**Describe the bug**
test added in root scope is ignored in reporters

**To Reproduce**
create file with `it('root level test', () => {})`

**Expected behavior**
root level test should be shown in reporter

**Log**
`Cannot read property 'tests' of undefined`

**Comment by christian-bromann** [comment]
see #5790
