### ISSUE TITLE
Devtools: Reporter hooks are not working

### ISSUE THREAD

**Issue by SanthoshBonala** [webdriverio/webdriverio#4583]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.14.3
 - **Mode:**  WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 10.15.1
 - **NPM version:** 5.6.0
 - **Browser name and version:** chrome 76
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
Default config from getting started guide

**Describe the bug**
Reporter hooks are not firing for events beforecommand and aftercommand.
I see that we do not emit any events in register function at https://github.com/webdriverio/webdriverio/blob/master/packages/devtools/src/devtoolsdriver.js
but when using webdriver protocol we do fire the reporter hooks here (protocolCommand function at line 83 and 92)
https://github.com/webdriverio/webdriverio/blob/master/packages/webdriver/src/command.js

please let me know if this is implemented at any other place or not yet implemented.
If this needs an implementation I am happy to send out a pr

**To Reproduce**
you can use any wdio reporter 

**Expected behavior**
should fire the reporter hooks with required args

**Comment by christian-bromann** [comment]
This should be an easy fix. The emit function needs to be called here: https://github.com/webdriverio/webdriverio/blob/master/packages/devtools/src/devtoolsdriver.js#L68-L107. Mind taking a stab at it @SanthoshBonala ?

**Comment by SanthoshBonala** [comment]
Sure. Will be sending the pr ASAP

**Comment by christian-bromann** [comment]
A fix was proposed in #4828
