### ISSUE TITLE
Can no longer use absolute paths for config file in 5.14.x

### ISSUE THREAD

**Issue by diachedelic** [webdriverio/webdriverio#4585]
It appears [a recent change](https://github.com/webdriverio/webdriverio/pull/4557/files/490a65193ac66a925dff44e74216edc0fdd21649#diff-7a7619b7da49bfc975df94ab8009ba14R34) means WDIO expects the path for the config (i.e. `wdio.conf.js`) to always be relative to CWD, although it accepted absolute paths previously.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.14.4

**Config of WebdriverIO**
`wdio run /Users/me/project/wdio.conf.js`

**Describe the bug**
I am prompted with `Error: Could not execute "run" due to missing configuration. Would you like to create one?` and tests do not run

**Expected behavior**
Absolute paths to be acceptable

**Comment by baruchvlz** [comment]
Thanks for bringing this up. I'll take a look at it today as I work on https://github.com/webdriverio/webdriverio/pull/4570

**Comment by christian-bromann** [comment]
This will be fixed by #4587
