### ISSUE TITLE
Retry (whole) scenario on failure for handling flaky tests

### ISSUE THREAD

**Issue by syedasadulhaq** [webdriverio/webdriverio#4588]
**Is your feature request related to a problem? Please describe.**
I'm using wdio cucumber. It supports retry on steps now. But it is very common that when a step failed, i need to re-execute previous step(s) as well.

**Comment by mgrybyk** [comment]
Please use gitter for such questions.
See https://webdriver.io/docs/retry.html#add-retries-on-a-per-specfile-basis

**Comment by syedasadulhaq** [comment]
OK, sure. Is specFileRetries applicable for cucumber?
