### ISSUE TITLE
Using with node-inspector

### ISSUE THREAD

**Issue by thedeeno** [webdriverio/webdriverio#459]
I'm trying to attach node-inspector to my test run and drop a debugger in one of my steps. I can successfully attach the inspector, but I can't drive the browser one execution has stopped.

If I hit the debugger in the following example and type `client.url('http://hello.com')` I get a `WebdriverIO` promise back, but my selenium-standalone never receives get message.

    debugger;
    // try to use client from node inspector here
    client.url('http://google.com').call(done);

What am I doing wrong?

**Comment by christian-bromann** [comment]
@thedeeno could you paste in some Selenium / WebdriverIO logs?

**Comment by zerbons** [comment]
@christian-bromann it seems to not execute until you exit the debugger. Any ideas on how to achieve a REPL interface for webdriverio?

**Comment by christian-bromann** [comment]
@zerbons WebdriverIO doesn't have a REPL interface yet. `v3` will introduce a method called `debug` that allows you to stop the queue and fiddle around in the browser. However I would like to see support for that in the future

**Comment by stoffeastrom** [comment]
@christian-bromann 

As I reported on gitter [here](https://gitter.im/webdriverio/webdriverio?at=55e6a90ce55df6ee79bf29cf). It's possible but maybe not the easiest way. I think it would be really nice to have a way of running the capabilities in the same process. This would make the debugging experience so much better. We could introduce a `debug` argument to the `cli`. This would just run them in the same process instead of forking child processes. Does this make sense?

**Comment by marthinus-engelbrecht** [comment]
@stoffeastrom Thanks for the tip :+1: , got it working for me. @christian-bromann would really be awesome to see a more integrated solution tough.

**Comment by georgecrawford** [comment]
Just adding my :+1: - a REPL to send webdriverio commands to the browser would be _amazingly_ useful.

**Comment by christian-bromann** [comment]
Debugging ability just got published with v4.0.9. For info see http://webdriver.io/guide/testrunner/debugging.html.

@georgecrawford I believe a repl functionality is a different topic but definitely nice to have.

**Comment by kurtharriger** [comment]
For those interested in a repl.  I hacked this together https://github.com/kurtharriger/wdio-repl as an alternative to the debugger.  Supports es6 and await which is useful for writing tests and experimenting.

**Comment by christian-bromann** [comment]
@kurtharriger 👏  this is so awesome.

**Comment by Viky-zhang** [comment]
But how can I use in WebStorm or PhpStorm like : http://blog.jetbrains.com/webide/files/2011/11/NodeJSDebugging.png
