### ISSUE TITLE
Promise-related errors when using webdriverio w/Chrome 76+

### ISSUE THREAD

**Issue by paulbrom** [webdriverio/webdriverio#4590]
**Environment:**
 - **WebdriverIO version: 5.4.13** 
 - **Mode:Standalone** 
 - **If WDIO Testrunner, running sync/async:N/A** 
 - **Node.js version:** 8.11.1
 - **NPM version:** 5.6.0
 - **Browser name and version:** Chrome 77
 - **Platform name and version:** MacOSX Mojave 10.14.3
 - **Additional wdio packages used (if applicable):** N/A

**Config of WebdriverIO**
Please see attached code snippet

**Describe the bug**
Starting in Chrome 76, webdriver tests we built at PureCars LLC against webdriverio began to fail sporadically with errors like this one:

> Request failed due to javascript error: javascript error: Method Promise.prototype.then called on incompatible receiver function(t){this._c=[],this._a=void 0,this._s=0,this._d=!1,this._v=void 0,this._h=0,this._n=!1}

(full stack trace below with log output)

**To Reproduce**
Run this node.js code, which has distilled the issue:
```
const { remote } = require('webdriverio');

const navigateAndReload = async browser => {
  await browser.url('http://griffinford.com/searchused.aspx');
  const element = await browser.$('div.srpVehicle p a');
  await element.waitForExist(5000);
  await browser.execute(function(selectorStr, scrollAmt) {
    // EMCA5 inside execute()
    var elem = document.querySelector(selectorStr);
    if (elem && scrollAmt) {
      elem.scrollIntoView(false);
      window.scrollBy(0, scrollAmt);
    }
    // EMCA5 restriction ended
  }, 'div.srpVehicle p a', 0);
  const title = await browser.getTitle();
  console.log('no error yet - page title is', title);
};

const keepNavigatingAndReloading = async (browser, navigationsRemain) => {
  await navigateAndReload(browser);
  if (navigationsRemain) {
    return await keepNavigatingAndReloading(browser, --navigationsRemain);
  }
};

(async () => {
  const browser = await remote({
    logLevel: 'error',
    path: '/', // remove `path` if you decided using something different from driver binaries.
    capabilities: {
      browserName: 'chrome'
    },
    port: 9515,
  });

  await keepNavigatingAndReloading(browser, 50);
  await browser.deleteSession();
})().catch((e) => console.error(e));
```

**Expected behavior**
Eventually you will see the above error occur in the console if you run the above code snippet.   Repro can be intermittent but is 75%+ reproducible with the above code snippet.

**Log**

> Here is the 'trace' level debugging output from running the above script:
> 2019-10-08T17:41:19.902Z INFO webdriverio: Initiate new session using the webdriver protocol
> 2019-10-08T17:41:19.907Z INFO webdriver: [POST] http://localhost:9515/session
> 2019-10-08T17:41:19.907Z INFO webdriver: DATA { capabilities: { alwaysMatch: { browserName: 'chrome' }, firstMatch: [ {} ] },
>   desiredCapabilities: { browserName: 'chrome' } }
> 2019-10-08T17:41:21.025Z INFO webdriver: COMMAND navigateTo("http://griffinford.com/searchused.aspx")
> 2019-10-08T17:41:21.026Z INFO webdriver: [POST] http://localhost:9515/session/e41676a0a9a86a5cca2ed8ae8b371fb8/url
> 2019-10-08T17:41:21.026Z INFO webdriver: DATA { url: 'http://griffinford.com/searchused.aspx' }
> 2019-10-08T17:41:27.782Z INFO webdriver: COMMAND findElement("css selector", "div.srpVehicle p a")
> 2019-10-08T17:41:27.782Z INFO webdriver: [POST] http://localhost:9515/session/e41676a0a9a86a5cca2ed8ae8b371fb8/element
> 2019-10-08T17:41:27.783Z INFO webdriver: DATA { using: 'css selector', value: 'div.srpVehicle p a' }
> 2019-10-08T17:41:27.817Z INFO webdriver: RESULT { 'element-6066-11e4-a52e-4f735466cecf': 'b2cbbaad-bf76-4f7a-ae93-95d2244cfce1' }
> 2019-10-08T17:41:27.823Z INFO webdriver: COMMAND findElements("css selector", "div.srpVehicle p a")
> 2019-10-08T17:41:27.823Z INFO webdriver: [POST] http://localhost:9515/session/e41676a0a9a86a5cca2ed8ae8b371fb8/elements
> 2019-10-08T17:41:27.823Z INFO webdriver: DATA { using: 'css selector', value: 'div.srpVehicle p a' }
> 2019-10-08T17:41:27.835Z INFO webdriver: RESULT [ { 'element-6066-11e4-a52e-4f735466cecf': 'b2cbbaad-bf76-4f7a-ae93-95d2244cfce1' },
>   { 'element-6066-11e4-a52e-4f735466cecf': '4811a7cd-bde3-4006-b5da-73a8202f223b' },
>   { 'element-6066-11e4-a52e-4f735466cecf': 'b3ae4079-f74f-4f73-b0d3-f7686bd2519e' },
>   { 'element-6066-11e4-a52e-4f735466cecf': '4b792a51-7253-4d5c-9d23-74938844d70d' },
>   { 'element-6066-11e4-a52e-4f735466cecf': '8871b6c3-18ee-440e-a068-466235e5a701' },
>   { 'element-6066-11e4-a52e-4f735466cecf': '8b61b52b-e12f-49c8-8100-1e62ba5d7e9a' },
>   { 'element-6066-11e4-a52e-4f735466cecf': '8cfa5467-7072-4dbc-a731-9f592544e6c4' },
>   { 'element-6066-11e4-a52e-4f735466cecf': 'd7563262-4101-4921-b07f-6eb3fbe0cc96' },
>   { 'element-6066-11e4-a52e-4f735466cecf': '2f665ce1-7729-46f4-9f48-97e25d8e5de2' },
>   { 'element-6066-11e4-a52e-4f735466cecf': 'a5aefa6f-c921-4efd-9134-6c6014984ee9' },
>   { 'element-6066-11e4-a52e-4f735466cecf': '843f2c99-6b19-469a-8a7f-a8b127ec71f3' },
>   { 'element-6066-11e4-a52e-4f735466cecf': 'cf4cf497-0d16-44d3-8f92-baf550869d08' },
>   { 'element-6066-11e4-a52e-4f735466cecf': '252c545f-621c-4102-ab33-e71f1b86557c' },
>   { 'element-6066-11e4-a52e-4f735466cecf': '5b0506da-0e79-439c-a949-9c8f10951599' },
>   { 'element-6066-11e4-a52e-4f735466cecf': 'ee248f94-1177-4b5f-9437-ef0e092d56a7' },
>   { 'element-6066-11e4-a52e-4f735466cecf': '42696979-3469-4f2d-80b8-252c38efc2f7' },
>   { 'element-6066-11e4-a52e-4f735466cecf': 'e6935252-3707-49fa-a215-59246c95a187' },
>   { 'element-6066-11e4-a52e-4f735466cecf': 'b25e1dfc-8d26-4360-9472-3e0a98af2746' },
>   { 'element-6066-11e4-a52e-4f735466cecf': '37b64f5a-6351-4717-a62b-1ba655c820ad' },
>   { 'element-6066-11e4-a52e-4f735466cecf': 'b4c3047d-a74b-415d-863f-f891c3f3cbe5' },
>   { 'element-6066-11e4-a52e-4f735466cecf': '285a9f2c-ff2a-4656-8002-970a5b9578e9' },
>   { 'element-6066-11e4-a52e-4f735466cecf': '4669f905-ea6f-4848-9774-7739f083e2bd' },
>   { 'element-6066-11e4-a52e-4f735466cecf': '4ff2bef2-547c-4255-b66a-d3067c224948' },
>   { 'element-6066-11e4-a52e-4f735466cecf': 'b5bd4416-3233-49ae-b2be-093025b2df08' },
>   { 'element-6066-11e4-a52e-4f735466cecf': '98c93501-4e0a-4aa1-8244-deccec6f2b29' } ]
> 2019-10-08T17:41:27.875Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
> 2019-10-08T17:41:27.875Z INFO webdriver: [POST] http://localhost:9515/session/e41676a0a9a86a5cca2ed8ae8b371fb8/execute/sync
> 2019-10-08T17:41:27.875Z INFO webdriver: DATA { script: 'return (function (selectorStr, scrollAmt) {\n    // EMCA5 inside execute()\n    var elem = document.querySelector(selectorStr);\n    if (elem && scrollAmt) {\n      elem.scrollIntoView(false);\n      window.scrollBy(0, scrollAmt);\n    }\n    // EMCA5 restriction ended\n  }).apply(null, arguments)',
>   args: [ 'div.srpVehicle p a', 0 ] }
> 2019-10-08T17:41:27.888Z DEBUG webdriver: request failed due to response error: javascript error
> 2019-10-08T17:41:27.889Z WARN webdriver: Request failed due to javascript error: Method Promise.prototype.then called on incompatible receiver function(t){this._c=[],this._a=void 0,this._s=0,this._d=!1,this._v=void 0,this._h=0,this._n=!1}
>   (Session info: chrome=77.0.3865.90)
> 2019-10-08T17:41:27.889Z INFO webdriver: Retrying 1/3
> 2019-10-08T17:41:27.889Z INFO webdriver: [POST] http://localhost:9515/session/e41676a0a9a86a5cca2ed8ae8b371fb8/execute/sync
> 2019-10-08T17:41:27.889Z INFO webdriver: DATA { script: 'return (function (selectorStr, scrollAmt) {\n    // EMCA5 inside execute()\n    var elem = document.querySelector(selectorStr);\n    if (elem && scrollAmt) {\n      elem.scrollIntoView(false);\n      window.scrollBy(0, scrollAmt);\n    }\n    // EMCA5 restriction ended\n  }).apply(null, arguments)',
>   args: [ 'div.srpVehicle p a', 0 ] }
> 2019-10-08T17:41:27.894Z DEBUG webdriver: request failed due to response error: javascript error
> 2019-10-08T17:41:27.894Z WARN webdriver: Request failed due to javascript error: Method Promise.prototype.then called on incompatible receiver function(t){this._c=[],this._a=void 0,this._s=0,this._d=!1,this._v=void 0,this._h=0,this._n=!1}
>   (Session info: chrome=77.0.3865.90)
> 2019-10-08T17:41:27.894Z INFO webdriver: Retrying 2/3
> 2019-10-08T17:41:27.894Z INFO webdriver: [POST] http://localhost:9515/session/e41676a0a9a86a5cca2ed8ae8b371fb8/execute/sync
> 2019-10-08T17:41:27.894Z INFO webdriver: DATA { script: 'return (function (selectorStr, scrollAmt) {\n    // EMCA5 inside execute()\n    var elem = document.querySelector(selectorStr);\n    if (elem && scrollAmt) {\n      elem.scrollIntoView(false);\n      window.scrollBy(0, scrollAmt);\n    }\n    // EMCA5 restriction ended\n  }).apply(null, arguments)',
>   args: [ 'div.srpVehicle p a', 0 ] }
> 2019-10-08T17:41:27.906Z DEBUG webdriver: request failed due to response error: javascript error
> 2019-10-08T17:41:27.906Z WARN webdriver: Request failed due to javascript error: Method Promise.prototype.then called on incompatible receiver function(t){this._c=[],this._a=void 0,this._s=0,this._d=!1,this._v=void 0,this._h=0,this._n=!1}
>   (Session info: chrome=77.0.3865.90)
> 2019-10-08T17:41:27.906Z INFO webdriver: Retrying 3/3
> 2019-10-08T17:41:27.906Z INFO webdriver: [POST] http://localhost:9515/session/e41676a0a9a86a5cca2ed8ae8b371fb8/execute/sync
> 2019-10-08T17:41:27.906Z INFO webdriver: DATA { script: 'return (function (selectorStr, scrollAmt) {\n    // EMCA5 inside execute()\n    var elem = document.querySelector(selectorStr);\n    if (elem && scrollAmt) {\n      elem.scrollIntoView(false);\n      window.scrollBy(0, scrollAmt);\n    }\n    // EMCA5 restriction ended\n  }).apply(null, arguments)',
>   args: [ 'div.srpVehicle p a', 0 ] }
> 2019-10-08T17:41:27.911Z DEBUG webdriver: request failed due to response error: javascript error
> 2019-10-08T17:41:27.911Z ERROR webdriver: Request failed due to javascript error: javascript error: Method Promise.prototype.then called on incompatible receiver function(t){this._c=[],this._a=void 0,this._s=0,this._d=!1,this._v=void 0,this._h=0,this._n=!1}
>   (Session info: chrome=77.0.3865.90)
>     at getErrorFromResponseBody (/Users/paulb/dev/AnalyticsMVHScript/node_modules/webdriver/build/utils.js:175:10)
>     at Request._callback (/Users/paulb/dev/AnalyticsMVHScript/node_modules/webdriver/build/request.js:110:64)
>     at Request.self.callback (/Users/paulb/dev/AnalyticsMVHScript/node_modules/webdriver/node_modules/request/request.js:185:22)
>     at emitTwo (events.js:126:13)
>     at Request.emit (events.js:214:7)
>     at Request.<anonymous> (/Users/paulb/dev/AnalyticsMVHScript/node_modules/webdriver/node_modules/request/request.js:1161:10)
>     at emitOne (events.js:116:13)
>     at Request.emit (events.js:211:7)
>     at IncomingMessage.<anonymous> (/Users/paulb/dev/AnalyticsMVHScript/node_modules/webdriver/node_modules/request/request.js:1083:12)
>     at Object.onceWrapper (events.js:313:30)
> { javascript error: javascript error: Method Promise.prototype.then called on incompatible receiver function(t){this._c=[],this._a=void 0,this._s=0,this._d=!1,this._v=void 0,this._h=0,this._n=!1}
>   (Session info: chrome=77.0.3865.90)
>     at getErrorFromResponseBody (/Users/paulb/dev/AnalyticsMVHScript/node_modules/webdriver/build/utils.js:175:10)
>     at Request._callback (/Users/paulb/dev/AnalyticsMVHScript/node_modules/webdriver/build/request.js:110:64)
>     at Request.self.callback (/Users/paulb/dev/AnalyticsMVHScript/node_modules/webdriver/node_modules/request/request.js:185:22)
>     at emitTwo (events.js:126:13)
>     at Request.emit (events.js:214:7)
>     at Request.<anonymous> (/Users/paulb/dev/AnalyticsMVHScript/node_modules/webdriver/node_modules/request/request.js:1161:10)
>     at emitOne (events.js:116:13)
>     at Request.emit (events.js:211:7)
>     at IncomingMessage.<anonymous> (/Users/paulb/dev/AnalyticsMVHScript/node_modules/webdriver/node_modules/request/request.js:1083:12)
>     at Object.onceWrapper (events.js:313:30) name: 'javascript error' }

**Additional context**
This problem only seems to occur if you use **execute** or **executeAsync** in your scripts. but using them does not always fail immediately, sometimes the failure will happen later when making a different kind of call into the browser context.

This problem began in Chrome 76, or the chromedriver compatible with Chrome 76.   I am not entirely sure where the problem resides; whether it lives in webdriverio, chromedriver, or Chrome, but this issue is blocking our ability to use the webdriver tests we built so I am raiding it here first.

Right now I am only able to run my webdriver scripts properly without seeing the above error if I force my machine to use Chrome 75.

Also, FYI, I directly execute chromedriver as my webdriver server.

**Comment by mgrybyk** [comment]
there is nothing to do with webdriverio.
Ask your developers to disable [dialeron.js](https://www.griffinford.com/dealeron.js?v=3d3658b143d7) or raise an issue to chromedriver project is you think it's an issue.

**Comment by paulbrom** [comment]
Suppressing third party scripts is not feasible for us, we need our automated test to run against live dealer sites whose script contents (beyond ours which we are testing) vary without our control.   I will raise this issue against chromedriver.   Thanks.

**Comment by paulbrom** [comment]
Just wanted to let you guys know I found a work-around for this issue.   If I do this immediately after page load, then I can sidestep this issue:

```
browser.execute(function() {
  // ECMA5 inside of execute
  var iframe = document.createElement('iframe');
  iframe.style.display = 'none';
  document.body.appendChild(iframe);
  var newWindow = iframe.contentWindow;
  window.Promise = newWindow.Promise; // get rid of any Promise polyfill
})
```
Somewhat amazingly, this solves the error I was seeing... for now anyway 😆
