### ISSUE TITLE
"Cannot read property 'bind' of undefined" when using touchAction

### ISSUE THREAD

**Issue by rubenlg** [webdriverio/webdriverio#4595]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.14.5
 - **Mode:** No idea
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** v12.10.0
 - **NPM version:** 6.12.0
 - **Browser name and version:** Chrome 77.0.3865.90
 - **Platform name and version:** Ubuntu 19.04
 - **Additional wdio packages used (if applicable):** @wdio/cli,  @wdio/jasmine-framework, @wdio/local-runner, @wdio/spec-reporter

**Config of WebdriverIO**
Here are the steps, in a clean environment without any npm module installed:
```shell
$ npm init
$ npm install @wdio/cli
$ node_modules/.bin/wdio config

? Where should your tests be launched? local
? Where is your automation backend located? On my local machine
? Which framework do you want to use? jasmine
? Do you want to run WebdriverIO commands synchronous or asynchronous? async
? Where are your test specs located? test.js
? Which reporter do you want to use? spec
? Do you want to add a service to your test setup? chromedriver
? What is the base url? http://localhost
```

**Describe the bug**
Unable to use touchAction because it throws an exception:
```
[chrome  linux #0-0] TypeError: Cannot read property 'bind' of undefined
[chrome  linux #0-0]     at <Jasmine>
[chrome  linux #0-0]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[chrome  linux #0-0]     at async UserContext.<anonymous> (/tmp/repro-bug/test.js:5:5)
```
**To Reproduce**
1. Install and configure wdio as indicated above.
2. Write the following `test.js` file:
```javascript
describe('test', () => {
  it('works', async () => {
    await browser.url('https://www.google.com');
    const input = await browser.$('input[name="q"]');
    await input.touchAction('press');
  });
});
```
3. Run it as follows: `node_modules/.bin/wdio wdio.conf.js`

**Expected behavior**
The google search bar is tapped.

**Log**
The stack trace is already above. Happy to provide my logs if you fail to reproduce the issue.

**Additional context**
What I provided above is just a minimal repro case. The reason I need to use touchAction is to test a canvas-based game.

**Comment by mgrybyk** [comment]
`touchAction` can be only used with Appium https://webdriver.io/docs/api/element/touchAction.html

You might want to use https://webdriver.io/docs/api/webdriver.html#performactions instead.

However I agree that error message can be improved

**Comment by rubenlg** [comment]
Thanks for the workaround. For others landing on this bug, here is how you do it:

```javascript
  browser.performActions([{
    'type': 'pointer',
    'id': 'finger1',
    'parameters': {'pointerType': 'mouse'},
    'actions': [
      {'type': 'pointerMove', 'duration': 0, 'x': x, 'y': y},
      {'type': 'pointerDown', 'button': 0},
    ]
  }]);
```
