### ISSUE TITLE
isExisting returns object instead of boolean

### ISSUE THREAD

**Issue by diachedelic** [webdriverio/webdriverio#4599]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.14.5
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v11.15.0
 - **NPM version:** v6.7.0
 - **Browser name and version:** 77.0.3865.90 (Official Build) (64-bit)
 - **Platform name and version:** MacOS 10.14.6
 - **Additional wdio packages used (if applicable):**
```
@wdio/cli
@wdio/local-runner
@wdio/mocha-framework
@wdio/spec-reporter
@wdio/sync
wdio-chromedriver-service
```

**Config of WebdriverIO**
See repro

**Describe the bug**
In certain circumstances, `element.isExisting()` returns an object instead of a boolean value.

**To Reproduce**
```
git clone git@github.com:diachedelic/wdio-repros.git &&
  cd wdio-repros &&
  git checkout zombie-existing &&
  npm i &&
  npm run test

```

**Log**
See `logs/` directory in repro

**Comment by mgrybyk** [comment]
Can you please try update packages to the latest versions @diachedelic

**Comment by mgrybyk** [comment]
Maybe it's just https://github.com/diachedelic/wdio-repros/blob/zombie-existing/package.json is not updated but package lock json is ok?

**Comment by diachedelic** [comment]
the packages were all updated but I have updated package.json anyway

**Comment by mgrybyk** [comment]
Nice catch @diachedelic 

Thanks a lot for steps to reproduce!

**Comment by mgrybyk** [comment]
will be fixed with the PR
