### ISSUE TITLE
Unable to run the scripts in CBT using the WebDriverIO v5

### ISSUE THREAD

**Issue by praveen-4705** [webdriverio/webdriverio#4600]
When I try to run the tests in CBT using the WebDriverIO v5 I am following the exception

Error: A "user" or "key" was provided but could not be connected to a known cloud service (SauceLabs, Browerstack or Testingbot). Please check if given user and key properties are correct!

services: [['crossbrowsertesting']],

user: '',
key: '',
cbtTunnel: false,
cbtTunnelOpts: {
    // any additional options from cbt_tunnels
},

**Comment by christian-bromann** [comment]
> user: '',
> key: '',

Please remove these and it should work. 

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by praveen-4705** [comment]
Than from where it will fetch the user and key detalis

**Comment by christian-bromann** [comment]
> From where it will fetch the user and key details

From the capabilities

**Comment by praveen-4705** [comment]
user: '',
key: '',

do I need to add these things in capabilities

**Comment by christian-bromann** [comment]
> do I need to add these things in capabilities

Please check out the crossbrowsertesting docs

**Comment by nikunj1977** [comment]
@christian-bromann - Thank you for swift response, As I said I am aiming to run a test on chrome on my local without having "@wdio/crossbrowsertesting-service": "^7.20.7" because in v4 we could run without having this dependency.

**Comment by christian-bromann** [comment]
@nikunj1977 if you want to run tests locally, remove the `user` and `key` options in your config and the CBT service from the service list.

**Comment by nikunj1977** [comment]
@christian-bromann - I removed them but still getting the same error. We are running test on NW,js and browser mode, following to upgrade to V5 all tests are running in NW.js but on browser it throws above given error.

**Comment by nikunj1977** [comment]
@christian-bromann - This is the error log

 2022-07-19T10:08:46.673Z ERROR @wdio/runner: Error: A "user" or "key" was provided but could not be connected to a known cloud service (Sauce Labs, Browerstack, Testingbot or Lambdatest). Please check if given user and key
properties are correct!
[0-0]     at detectBackend (C:\dev\git\-\-\node_modules\@wdio\runner\node_modules\webdriverio\build\utils\detectBackend.js:98:15)
[0-0]     at remote (C:\dev\git\-\-\node_modules\@wdio\runner\node_modules\webdriverio\build\index.js:75:60)
[0-0]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[0-0]     at async Runner._startSession (C:\dev\git\-\-\node_modules\@wdio\runner\build\index.js:223:56)
[0-0]     at async Runner.run (C:\dev\git\-\-\node_modules\@wdio\runner\build\index.js:66:23)
[0-0] 2022-07-19T10:08:46.676Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot convert undefined or null to object
[0-0]     at execHook (C:\dev\git\-\-\node_modules\@wdio\sync\build\executeHooksWithArgs.js:34:27)
[0-0] FAILED

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:00


Process finished with exit code 1

**Comment by christian-bromann** [comment]
@nikunj1977 the error still says that you have `user` and `key` set in your config or that a service might have set it. Please debug.

**Comment by nikunj1977** [comment]
@christian-bromann I debugged but have not noticed anything but the same error. I simply upgraded the version from 4 to 5 and have not added anything about CBT services unless it adds these services secretly when upgrading the version to 5?

**Comment by christian-bromann** [comment]
Not sure what else to recommend here. Given that we soon release v8 of WebdriverIO I would not only update to v5 but to v7. It is hard to say what is up with that old version.

**Comment by nikunj1977** [comment]
@christian-bromann thank you, In that case, I will skip to upgrade browser-oriented tests in v5 and jump up our entire test suit to upgrade from v5 to v7.

**Comment by nikunj1977** [comment]
@christian-bromann I upgraded the version from 5 to 7 successfully but unfortunately got the same error when running tests on google chrome locally. Have you had the same issue reported form from anyone following migration?

**Comment by christian-bromann** [comment]
> Have you had the same issue reported form from anyone following migration?

no

**Comment by nikunj1977** [comment]
@christian-bromann Thanks for sync with me on this issue. It was fixed since my upgrade requires to have this "hostname: 'localhost'," in the config file. This is not added itself post successful upgrade from 5 to 7. On a separate note, from V5 has chooseFile command changed to uploadFile or both are valid with the latest version?

**Comment by christian-bromann** [comment]
> or both are valid with the latest version?

Please check the webdriver.io docs.
