### ISSUE TITLE
Firefox extension is not loaded with firefox-profile-service

### ISSUE THREAD

**Issue by ersefuril** [webdriverio/webdriverio#4602]
**Environment:**
 - **WebdriverIO version:** [5.14.3]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [10.15.2]
 - **NPM version:** [6.4.1]
 - **Browser name and version:** [Firefox Quantum 69.0.2 (64-bit)]
 - **Platform name and version:** [macOS Mojave]
 - **Additional wdio packages used (if applicable):** [@wdio/selenium-standalone-service@5.13.2, @wdio/firefox-profile-service@5.13.2]

**Config of WebdriverIO**
```
exports.config = {
    runner: 'local',
    specs: [
        './test/specs/**/*.js'
    ],
    capabilities: [
        {
            browserName: 'firefox'
        }
    ],
    firefoxProfile: {
        extensions: [
            "./test/extensions/adblock_plus-3.6.3-an+fx.xpi" // Not loaded for some unknown reasons
        ]
    },
    logLevel: 'debug',
    baseUrl: 'http://localhost:9000',
    services: ['firefox-profile', 'selenium-standalone'],
    framework: 'jasmine',
    reporters: ['spec']
};
```

**Describe the bug**
I'm trying to load an adblocker extension for firefox with `@wdio/firefox-profile-service`. I just followed the official doc (see configuration before). According to the log, a firefox profile is loaded but I can't see any extension installed in my browser during the tests.

I've probably missed something, maybe it can be linked to my firefox version or just because I'm using `selenium-standalone` ?

**Expected behavior**
I expect to see my adblocker extension loaded in the browser.

**Log**
Logs seems to be okay, we can see here that a firefox profile has been loaded.
[see my gist here](https://gist.github.com/ersefuril/63f35b4f9c96092c21ebe57aa18b5cf5)

**Comment by mgrybyk** [comment]
@ersefuril may you please check if anything else except of extension works for you in firefox profile?

**Comment by ersefuril** [comment]
I tried to remove my extension and change the default homepage: my profile is totally ignored (but according to the logs, I still can see it loaded with a big base64 string)

`firefoxProfile: {
        'browser.startup.homepage': 'https://webdriver.io'
 }`

**Comment by ersefuril** [comment]
@mgrybyk Any idea why ?

**Comment by cookieslab** [comment]
I face similar issue, Extensions are not installed with firefoxProfile.

I have created a firefox extension to add custom request headers. While running tests from webdriver io v.5 in firefox, I need to install the extension first. I tried with firefox profile service to install the extension. 
I have added the below code to wdio.conf.js . But the test runs without installing the extension. Please help. I do not get any error message in the logs , But the base64 string of extension is added to desiredCapabilities. 

``
...
services: ['selenium-standalone', 'firefox-profile'], 
seleniumLogs: './logs', 
skipSeleniumInstall: false, 
firefoxProfile: { 
           extensions: [ './extensions/firefox/custom-headers'], // or path to unpacked Firefox extension  
},
...
``

**Comment by arun-14feb** [comment]
@ersefuril , @mgrybyk , I got it working by adding an extra preference ,

``
 'xpinstall.signatures.required': false,
``

Now my wdio.conf.js,
``
... services: ['selenium-standalone', 'firefox-profile'], seleniumLogs: './logs',  firefoxProfile: { extensions: [ './extensions/firefox/custom-headers'], // or path to unpacked Firefox extension 
'xpinstall.signatures.required': false,
legacy: false
}, ...
``
Ref:
https://wiki.mozilla.org/Add-ons/Extension_Signing

**Comment by christian-bromann** [comment]
Added note to the docs in #4821. Thanks for sharing @arun-14feb!

**Comment by ersefuril** [comment]
Thanks for your support !
