### ISSUE TITLE
Custom Reporter: onSuiteEnd fires when Mocha test suite ends, not wdio suite

### ISSUE THREAD

**Issue by Khrove** [webdriverio/webdriverio#4604]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.12.4
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** Sync
 - **Node.js version:** v10.16.2
 - **NPM version:** 6.11.3
 - **Browser name and version:** Chrome 76
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/reporter, @wdio/mocha-framework

**Config of WebdriverIO**
```
suites: {
        admin: [
            './tests/partner_portal/authenticated_home_page/admin_primary_flows.spec.js',
            './tests/partner_portal/login/login_primary_flows.spec.js',
            './tests/partner_portal/portal_quoting/quote_primary_flows.spec.js',
            './tests/partner_portal/policies/policy_primary_flows.spec.js',
            './tests/partner_portal/orders/orders_primary_flows.spec.js',
            './tests/partner_portal/group_enrollment/group_primary_flows.spec.js',
            './tests/partner_portal/claims/claims_primary_flows.spec.js',
            './tests/partner_portal/account/account_primary_flows.spec.js',
        ],
},
reporters: ['spec', [CustomReporter, {
        someOption: 'foobar'
    }]],
```

reporter.js
```
import WDIOReporter from '@wdio/reporter';
import { results } from './results';

module.exports = class CustomReporter extends WDIOReporter {
    constructor(options) {
        super(options)
        console.log('initialised custom reporter with the following reporter options:', options)

        console.log('Some log line')
    }

    onRunnerStart() {
        console.log(`We are beginning the test!`);
    }

    onTestStart(test) {
        console.log(`${test.title} has begun running!`);
    }

    onTestFail(test) {
        console.log(`${test.title} has failed! Oh no! Incrementing test fail count now.`);
        // Increment test fail count
        console.log(`The test failed because of: ${JSON.stringify(test.error.message)}`);
        console.log(test.duration);
        results.addDuration(test.duration);
        results.addFail(test.title);
    }

    onTestPass(test) {
        console.log(`${test.title} has ended! Incrementing test pass count now.`);
        // Increment test pass count
        results.addDuration(test.duration);
        results.addPass(test.title);
    }

    onSuiteEnd() {
        console.log(`We've completed the suite!`);
        results.logResults();
    }

    onRunnerEnd() {
        console.log(`We should now be sending the slack result log and saving stats to file.`);
    }
}
```

**Describe the bug**
When using a custom reporter I want the onSuiteEnd hook to be hit when the suite in my wdio config ends, not mocha. onRunnerEnd hook is not viable because after each spec file ends my Browserstack instance is killed, so that hook gets hit.

This bug may be a configuration error on my part. Overall the goal for this is that when I send an update to Slack I want it to fire off only once, not everytime onSuiteEnd is hit.

**To Reproduce**
I can provide a custom Github repo on request if what I've provided is not enough info...

**Expected behavior**
onSuiteEnd reporter hook should only fire once a WDIO suite ends, not Mocha.

**Log**
No error logs to provide.

**Comment by mgrybyk** [comment]
It's not a bug or configuration error, it works as designed. 
You can  verify that it is the last suite in mocha's onSuiteEnd

**Comment by mgrybyk** [comment]
Additionally, please avoid using browser commands in reporter

**Comment by Khrove** [comment]
@mgrybyk not sure I follow you? "You can verify that it is the last suite in mocha's onSuiteEnd"

My issue here is that the onSuiteEnd command is being hit at the end of each describe statement in each spec file? Is that expected?

Also I'm not making any browser command calls...I don't think? The result.addFail, addPass are functions declared in another file, not additional WebDriverIO files.

**Comment by mgrybyk** [comment]
> this hook was external from Mocha and strictly a WDIO hook

No, onSuiteEnd reporter hook is  called on every mocha suite end

**Comment by mgrybyk** [comment]
What is the problem with onRunnerEnd() ?

**Comment by mgrybyk** [comment]
If you are making an async call use `this.isSynchronised = false` before and `this.isSynchronised = true` after

**Comment by Khrove** [comment]
onRunnerEnd gets hit when my Browserstack instance gets killed. Currently I have my browserstack local instance being killed in a wdio configs onComplete function:

```
onPrepare: function (config, capabilities) {
        console.log("Connecting local");
        return new Promise(function (resolve, reject) {
            exports.bs_local = new browserstack.Local();
            exports.bs_local.start({
                'key': exports.config.key
            }, function (error) {
                if (error) return reject(error);
                console.log('Connected. Now testing...');

                resolve();
            });
        });
    },
    // Code to stop browserstack local after end of test
    onComplete: function () {
        exports.bs_local.stop(function () {});
    }
```

The problem with this is that onComplete is called everytime a spec file ends.

**Comment by mgrybyk** [comment]
Why don't you use browserstack service or not handling your custom bs instance like a service? 

It's not a problem with reporter but with the way you've organized the flow

**Comment by mgrybyk** [comment]
You may think on using wdio afterSuite hook instead of reporter's onSuiteEnd

**Comment by Khrove** [comment]
@mgrybyk  I've never been able to get the browserstack service to work by following the docs. Not sure if they're missing some important configuration steps, but I already enabled Browserstack's local testing API (https://www.browserstack.com/local-testing/api#enabling-local-testing-api). I comment out my onPrepare and onComplete BS related code and get the following error:

`webdriver: Request failed due to [browserstack.local] is set to true but local testing through BrowserStack is not connected.`

So that's why I haven't been using it. I'll try out the afterSuite hook right now

**Comment by Khrove** [comment]
```
afterSuite: function () {
        console.log('running after suite command now')
    },
```

added to my wdio config and it runs in the same spot as my custom reporter onSuiteEnd hook...
