### ISSUE TITLE
How to handle branching chain?

### ISSUE THREAD

**Issue by thedeeno** [webdriverio/webdriverio#461]
How would you model this (pseudo coded) synchronous test with webdriverio?

    var el = browser.getElement('button');
    if (el.getAttribute('state') === 'on') {
       el.click()
    }

**Comment by christian-bromann** [comment]
Hi @thedeeno,
you could do the following:

```js
browser.getAttribute('button', 'state', function(err, state) {
    if(state === 'on') {
        browser.click('button');
    }
})
```

**Comment by thedeeno** [comment]
Thanks!
