### ISSUE TITLE
The value of `passed` parameter of Jasmine expectationResultHandler is always true

### ISSUE THREAD

**Issue by shinxi** [webdriverio/webdriverio#4611]
**Environment:**
 - **WebdriverIO version:** 5.15.0
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v10.4.1
 - **NPM version:** 6.1.0
 - **Browser name and version:** Chrome 77
 - **Platform name and version:** MacOS
 - **Additional wdio packages used (if applicable):** 
    > "@wdio/allure-reporter": "^5.14.5",
    "@wdio/cli": "^5.15.0",
    "@wdio/jasmine-framework": "^5.15.0",
    "@wdio/junit-reporter": "^5.15.0",
    "@wdio/local-runner": "^5.15.0",
    "@wdio/spec-reporter": "^5.14.5",
    "@wdio/sync": "^5.14.4",
    "webdriverio": "^5.15.0"

**Describe the bug**
The value of the first parameter - `passed` of Jasmine expectationResultHandler is incorrect, and always be true.

**To Reproduce**

```js
// wdio.conf.js
....
  jasmineNodeOpts: {
    //
    // Jasmine default timeout
    defaultTimeoutInterval: 9999999,
    //
    // The Jasmine framework allows interception of each assertion in order to log the state of the application
    // or website depending on the result. For example, it is pretty handy to take a screenshot every time
    // an assertion fails.
    expectationResultHandler(passed, assertion) {
      console.log('expectationResultHandler passed', passed);
    }
  },
...
// test case js file
describe('jasmineNodeOpts', () => {
  it('the passed parameter should be correct', () => {
    expect(3).toBe(3); // prints "expectationResultHandler passed true"
    expect(1).toBe(2); // prints "expectationResultHandler passed true"
  })
})
```

**Expected behavior**
when assertion failure, e.g., `expect(1).toBe(2);`, the value of the passed parameter should be `false`.

**Comment by mgrybyk** [comment]
try deleting package-lock.json, node_modules folder and then npm install.
Looks like the issue has been fixed on jasmine's side.

Feel free to ping me or reopen the issue if you are still facing the problem.

**Comment by shinxi** [comment]
@mgrybyk Can you share your devDependencies at package.json? Here is mine.
```js
  "devDependencies": {
    "@wdio/allure-reporter": "^5.14.5",
    "@wdio/cli": "^5.15.0",
    "@wdio/dot-reporter": "^5.14.5",
    "@wdio/jasmine-framework": "^5.15.0",
    "@wdio/junit-reporter": "^5.15.0",
    "@wdio/local-runner": "^5.15.0",
    "@wdio/spec-reporter": "^5.14.5",
    "@wdio/sync": "^5.14.4",
    "babel-eslint": "^8.2.3",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-register": "^6.26.0",
    "eslint": "^4.19.1",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-plugin-import": "^2.12.0",
    "husky": "^0.14.3",
    "lint-staged": "^7.2.0",
    "moment": "^2.22.2",
    "moment-timezone": "^0.5.23",
    "prettier-eslint": "^6.4.3",
    "selenium-standalone": "^6.16.0",
    "shelljs": "^0.8.2",
    "webdriverio": "^5.15.0"
  },
```
Also what's your selenium server version? mine is `3.141.59`.

Thanks.

**Comment by mgrybyk** [comment]
Replied in another issue. Please take attention to not just package json but to package lock json as well

**Comment by razielron** [comment]
can we control the spec in that case?
I mean can we stop the 'describe' when assertion fails?
like to get the spec in the function and use spec.stop() or something? is it possible?
It would really help to gain more control on the suites/specs and manipulate it our way
