### ISSUE TITLE
replace table with something more lightweight in wdio-spec-reporter

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4614]
**Is your feature request related to a problem? Please describe.**
`table` package consumes 7.4Mb of space, while wdio-spec-reporter should be loaded for every child process it leads to memory overhead (3-4Mb) for every spawned worker

**Describe the solution you'd like**
replace `table` with something else

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by christian-bromann** [comment]
> replace `table` with something else

Given that this is only used to render the cucumber table definitions we should get rid of it and render it by ourself
