### ISSUE TITLE
Avoid starting some services in worker processes

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4615]
**Is your feature request related to a problem? Please describe.**
Currently we load all the services in child processes that leads to increasing memory consumption.

**Describe the solution you'd like**
Avoid starting selenium-standalone and appium services in worker processes

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by christian-bromann** [comment]
Let's remove all services from the services list if they don't have any class for the worker.

**Comment by mgrybyk** [comment]
@christian-bromann I'll remove services according to

| Service  | Load in worker |
| ------------- | ------------- |
| chromedriver  | no  |
| selenium-standalone  | no  |
| appium  | no  |
| reportportal  | no |
| firefox-profile  | no  |
| sauce  | **yes**  |
| testingbot  | **yes** |
| browserstack  | **yes** |
| crossbrowsertesting  | **yes** |
| docker  | **yes** |
| zafira-listener  | **yes** |
| devtools  | **yes** |
| applitools  | **yes**  |
