### ISSUE TITLE
Webdriverio launches new browser session for each feature file to execute

### ISSUE THREAD

**Issue by rangavenu** [webdriverio/webdriverio#4616]
- **WebdriverIO version:** - 5.15.0
 - **Mode:**  - WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:**  - sync
 - **Node.js version:** - 10.16.3
 - **NPM version:** - 6.9.0
 - **Browser name and version:** - Any (chrome / ff/safari/edge etc)
 - **Platform name and version:** -  Windows 10 or Any
 - **Additional wdio packages used (if applicable):** -  (@wdio/selenium-standalone service, @wdio/cucumber-framework, @wdio/allure-reporter)

**Config of WebdriverIO**
module.exports.config = {
  services: ['selenium-standalone'],
  exclude: [],
  sync: true,
  maxInstances: 1,
  logLevel: 'error',
  bail: 0,
  waitforTimeout: 10000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  capabilities: [{ maxInstances: 1, browserName: 'chrome' }],
  // before: [Function: before],
  // afterSession: [AsyncFunction: afterSession],
  // beforeFeature: [Function: beforeFeature],
  // beforeScenario: [Function: beforeScenario],
  // afterStep: [Function: afterStep],
  // afterScenario: [Function: afterScenario],
  // afterFeature: [AsyncFunction: afterFeature],
  specs: ['./features/Functional/**/*.feature'],
  framework: 'cucumber',
  cucumberOpts:
  {
    backtrace: true,
    requireModule: [
      'tsconfig-paths/register',
      () => {
        require('ts-node').register({ files: true });
      },
    ],

    failAmbiguousDefinitions: true,
    failFast: false,
    format: ['pretty'],
    colors: true,
    ignoreUndefinedDefinitions: false,
    source: true,
    profile: [],
    require: ['./stepDefinitions/*.ts'],
    snippets: undefined,
    strict: true,
    tagExpression: '',
    tagsInTitle: true,
    timeout: 20000,
    dryRun: false,
  },
  reporters: [[
    'allure',
    {
      outputDir: './FunctionalTests/allure-results/',
      disableWebdriverStepsReporting: true,
      disableWebdriverScreenshotsReporting: false,
      useCucumberStepReporter: true,
    },
  ]],
  deprecationWarnings: false,
  screenshotPath: './allure-results/',
  baseUrl: '<test url>',
};

**Describe the bug**
when running tests, new browser opens  and closes for every feature file executed.

**To Reproduce**
wdio -- <path to config file>

**Expected behavior**
Browser should open once before executing any feature file and should remain open for the remaining of feature files and close after executing all feature files.

**Additional context**
We have around 40 feature files currently and expected to grow in count and when running tests new browser opens and closes for every feature file executed. This adds a lot of performance overhead especially when you have to login to the application to test.

**Comment by mgrybyk** [comment]
Wdio spawns new child process instance for every spec file (feature).
It makes tests more isolated and stable. 

You may save cookies in the first test and reuse further if it takes much time for your app

**Comment by rangavenu** [comment]
Hi mgrybyk

I understand very well how webdriverio works and yes it definitely seems like this behavior is intended and I would like to question that.
I'm not sure how convenient it is for users that face similar perf issues, as we are all very well aware of the natural delay involved in opening new browser session every time.
We also have to keep in mind that even though we are testing the functionality of application, no one wants to see their tests run for a long time and everyone these days are working 
towards reducing test execution time as much as possible to get a faster feedback and this behavior of wdio is definitely not helpful in that way.

I'm also a little surprised about the issue being closed without further conversation. 

This behavior could also make users move away from using webdriverio and go back to using custom frameworks.

There should be a better way than reusing cookie between feature files which still doesn't allow us from reusing browser session.

At the least consumers should have the ability to at least use a flag to reuse browser session that way we are not imposing performance overhead.

**Comment by mgrybyk** [comment]
> run for a long time

you may run tests in parallel.

Regarding other points the only thing we can do right now is to build another launcher. If you would like to help with that feel free to raise a feature/pull request.
With current implementation there it's not possible to reuse sessions because each spec runs in own child process that runs test framework, browser session, etc.

> There should be a better way than reusing cookie

Do you have any other ideas besides of keeping same session?
Ideally each test should not rely on anything from another test, including session, to achieve that you may try to speed up test Background somehow.

Alternatively you may try switching to mocha, it allows to run multiple tests in same session.

Even though the issue is closed I'm happy to answer your questions / discuss it further so that you have a working solution.

**Comment by rangavenu** [comment]
Thanks. I will have to think about an alternative since it is not easy to solve with wdio. either a new launcher or something else. but Mocha cant replace our needs as we use cucumber to share test scenarios with different non technical stake holders too within the company.

**Comment by mgrybyk** [comment]
Well, a new launcher will work for sure. However I'd suggest to have some way to open your app faster in desired state (already logged in, on some page, etc).

In my opinion spending 3 seconds per feature file to bootstrap everything and open browser is not a huge overhead, especially taking into account that I can run tests in parallel easily in different multiple browsers just by providing capabilities/maxInstances.

Hope you can find a solution that would work for you perfectly 

P.S.
With mocha it is possible to import multiple spec files into single spec file, sorry to say I don't know to achieve that with Cucumber's feature files.

**Comment by christian-bromann** [comment]
> everyone these days are working
> towards reducing test execution time as much as possible to get a faster feedback and this behavior of wdio is definitely not helpful in that way.

@rangavenu can you please help us to understand how wdio is not helpful? Running one spec file per session is a design choice and there are workarounds how you can tweak this behavior. However most of the time this works very well. In situations where e.g. bootstrapping a test takes 3 minutes and running a new session for every spec seem daunting it forces you to tweak the app under test to allow better bootstrapping vs. running all tests in one session.

If you have any specific suggestions or more details about your use case please let us know. Cheers!

**Comment by rangavenu** [comment]
Hi Mykola
Yes, new launcher will definitely be useful and since it is difficult at this point to change the behavior in wdio I feel new launcher is the way to go.

@christian-bromann There are different ways to achieve what wdio is doing now by default (opening new browser for every feature file) and we can talk more and more on justifying the current design vs what it should be. And I'm sure each side will have some sound points.  

We have cucumber hooks, wdio hooks that can be used to open a new browser session for every feature file which is the simplest solution to mimic the current default  behavior but currently the framework is imposing this on users which to my opinion is bad. 

We have been using cucumber framework with java, We have also been using specflow with .net etc and I have not come across any example framework that recommends opening and closing browser with each feature file as a best practice or is imposing this behavior on users.

And even though it takes just 3 secs to launch a browser,  we have 42 feature files so far which means we spent a little over 2 mins just for opening and closing new browsers.

I do strongly believe in parallel test execution and we are planning to do it shortly but I feel that should be done regardless to bring down execution time to the very minimum. And shouldn't be a replacement for the ask.

I see you have mentioned that there are workarounds to tweak this behavior. Can you please provide me your thoughts so we can see how straight forward it is and go from there.

Else we should implement a new launcher which does not close browsers for each spec / feature file. 

I really appreciate you guys reacting to issues so fast  and sorry for getting back late on this. Please keep the healthy discussions going.

**Comment by mgrybyk** [comment]
> And even though it takes just 3 secs to launch a browser

Just checked, it took 14 seconds to start/stop browser 42 times.

**Comment by rangavenu** [comment]
@christian-bromann / @mgrybyk  Thanks for all the feedback. No, I don't have anymore comments regarding this.
Just one small clarification, So how are we proceeding from here ? As you had commented on time which is very understandable. Should I create a PR with the change?

**Comment by christian-bromann** [comment]
> Just one small clarification, So how are we proceeding from here ?

I think the best way to move forward is to build a runner that does allow the session management that you describe. I would be happy review it. No PR to this repository needed. Cheers!

**Comment by rangavenu** [comment]
Sure. Thanks

**Comment by azinchenko91** [comment]
Hey @christian-bromann . Do you have any updates about runner that allows to run all feature files in one browser?

**Comment by christian-bromann** [comment]
@azinchenko91 yeah .. I have an idea to allow specifying the specs per runner better as it is possible right now, you can read up more of it here: #4974

**Comment by rp-eduardoantunez** [comment]
What about the opposite situation @mgrybyk , in my company we wish that we could run each scenario contained in a feature file in separate sessions on Browserstack, to have separate videos and logs. Do you think that would be possible somehow? What about having a retry strategy per scenario, not feature?

**Comment by christian-bromann** [comment]
> Do you think that would be possible somehow?

Not at the moment. There are efforts like https://github.com/SimitTomar/wdio-cucumber-parallel-execution which I am not sure if they still work with latest WebdriverIO since it is not maintained by the core team.

> What about having a retry strategy per scenario, not feature?

That should be possible with Cucumbers build in [Rerun](https://github.com/cucumber/cucumber-js/blob/main/docs/rerun.md) capabilities.

**Comment by HareAvenger** [comment]
> Hi mgrybyk
> 
> I understand very well how webdriverio works and yes it definitely seems like this behavior is intended and I would like to question that. I'm not sure how convenient it is for users that face similar perf issues, as we are all very well aware of the natural delay involved in opening new browser session every time. We also have to keep in mind that even though we are testing the functionality of application, no one wants to see their tests run for a long time and everyone these days are working towards reducing test execution time as much as possible to get a faster feedback and this behavior of wdio is definitely not helpful in that way.
> 
> I'm also a little surprised about the issue being closed without further conversation.
> 
> This behavior could also make users move away from using webdriverio and go back to using custom frameworks.
> 
> There should be a better way than reusing cookie between feature files which still doesn't allow us from reusing browser session.
> 
> At the least consumers should have the ability to at least use a flag to reuse browser session that way we are not imposing performance overhead.


Hi , You can use this approach to avoid closing browser in between tests.. describe('---Test Case: 001', async() => {		
    it('TestCase - Sample', async() => {	
     const a = require('../bookride/TC001.js');
     const b = require('../bookride/TC002.js');
      a();
      b();
    });
});

**Comment by christian-bromann** [comment]
> You can use this approach to avoid closing browser in between tests

No.
