### ISSUE TITLE
waitForContent, is this a good way of doing it?

### ISSUE THREAD

**Issue by wackazong** [webdriverio/webdriverio#462]
I needed a procedure that waits for some text to appear in a div. waitForText would not work since there is text in the div but more text appears later. 

I wrote the following custom command. Is this an acceptable way of doing it, are there more elegant ways? Thanks for some insights.

    waitForContent: function (selector, text) {
      var timedOut = false;
      var callback = arguments[arguments.length - 1];
      var timeOut = setTimeout(function () {
        assert(false, 'content "' + text + '" not found in selector "' + selector + '"');
        timedOut = true;
        callback(null, false);
      }, 5000);
      var browser = this;
      var search = function () {
        if (timedOut) {
          return;
        }
        browser.
            pause(250).
            getText(selector, function (err, result) {
              if (err) {
                callback(err, null);
              }
              if (result && result.indexOf(text) !== -1) {
                clearTimeout(timeOut);
                callback(null, true);
              } else {
                search();
              }
            });
      };
      search();
    }

**Comment by cdaringe** [comment]
@wackazong, check out https://github.com/webdriverio/webdriverio/issues/411

**Comment by wackazong** [comment]
Ok, thanks, I read that but thought it would be another usecase, I will go through it again.

**Comment by christian-bromann** [comment]
@wackazong I was thinking of enhancing the waitForText command with an additional attribute that represents the already existing text. The command would finish once that text has changed (or timeout). What do you think about that?

**Comment by wackazong** [comment]
Sounds good to me!
