### ISSUE TITLE
Is it possible to set the timezone for timestamps?

### ISSUE THREAD

**Issue by spartanhooah** [webdriverio/webdriverio#4621]
**Describe your question with as much detail as possible**
Our WDIO scripts using this reporting module generate XML files with timestamps in the local time zone. We then upload these files to qTest, which assumes GMT timestamps. Is there a way to set the time zone for the timestamps?

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.11.11
 - **Mode:** I think standalone
 - **Node.js version:** 10.15.3
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chromedriver 76.0.0
 - **Platform name and version:** MacOS and some form of Linux (on a GitLab runner)
 - **Additional wdio packages used (if applicable):** "@wdio/cli": "^5.11.11",
    "@wdio/junit-reporter": "^5.11.7",
    "@wdio/local-runner": "^5.6.4",
    "@wdio/mocha-framework": "^5.6.4",
    "@wdio/sauce-service": "^5.6.4",
    "@wdio/spec-reporter": "^5.6.4",
    "@wdio/sync": "^5.6.4",

**Comment by christian-bromann** [comment]
Hey @spartanhooah , no there is no built in way to change timezones. You will have to change the dates in the reports with a script.

If you have further questions, please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). Cheers!
