### ISSUE TITLE
Reification of of JSON WebElement changes

### ISSUE THREAD

**Issue by diervo** [webdriverio/webdriverio#4622]
Not sure if this is working as design in WebdriverIO 5.x but I haven't found any documentation about it, and since the behavior is different from 4.0 would like to ask:

```js
it('test', async function() {
  const element = await browser.execute(function() {
    return document.body;
  });

  console.log(x); // This is a regular JSON with the Element Id from WebDriver
  x.getValue(); // throws since this is not an "Element" from WebdriverIO perspective
});
```
In the 4.x version any Element was automatically converted to a "WebElemenet" from webdriverIO perspective (so all APIs work). In 5.x the return is a JSON object with the Element ID from the webdriver protocol.

The only docs I could find:

> Arguments may be any JSON-primitive, array, or JSON object. JSON objects that define a WebElement reference will be converted to the corresponding DOM element. Likewise, any WebElements in the script result will be returned to the client as WebElement JSON objects.

So the question is: Is this expected, and if so, how can I programmatically get a regular WebdriverIO element.

**Comment by diervo** [comment]
I have found an issue where it seems that this should work: 
https://github.com/webdriverio/webdriverio/issues/4578#issuecomment-538762175

Maybe @christian-bromann might be able to trivially clarify? :)

**Comment by mgrybyk** [comment]
@diervo is it something you are looking for
```
const body = await $(async function () {
    return this.document.body
})
const val = await body.getValue()
```
?

**Comment by mgrybyk** [comment]
closing it as it's not an issue, please use gitter for such questions

**Comment by diervo** [comment]
@mgrybyk there is a specific template on your Github issues called `questions`, which points to no gitter at all, hence my question here...

As a maintainer of a lot of open source projects, I think if you treat everyone first issue or interaction this way (no answer and closing the issue for an orthogonal semantical procedure) it won't be long until people wont contribute anymore.

My humble 2 cents.

**Comment by christian-bromann** [comment]
@diervo you can fetch elements using execute via, e.g. 

```js
const body = $(() => document.body)
console.log(body.getTagName()) // returns "body" 
```

Not sure how the behavior was in v4 but this is how things are done in v5. Happy to answer further questions on Gitter. We definitely appreciate all questions also in this format. But on Gitter things are more interactive and we can answer more questions.

Cheers!

**Comment by mgrybyk** [comment]
Sorry for that, @diervo. I have provided the answer before closing the issue https://github.com/webdriverio/webdriverio/issues/4622#issuecomment-541857585

Even though it's closed I'm still happy to help however it's usually way faster to get help in gitter.

Thank you for your feedback
