### ISSUE TITLE
browser.getCurrentTabId is not a function - WDIO 5.13

### ISSUE THREAD

**Issue by jcollum-autodesk** [webdriverio/webdriverio#4625]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.13.1
 - **Mode:** CLI
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:** 12.7
 - **NPM version:** 6.10
 - **Browser name and version:** Chrome 77
 - **Platform name and version:** OSX 10.14.6
 - **Additional wdio packages used (if applicable):**      
<details> <summary>packages</summary> 
 
        "@wdio/allure-reporter": "^5.12.0",
        "@wdio/cli": "^5.11.13",
        "@wdio/junit-reporter": "^5.12.1",
        "@wdio/local-runner": "^5.11.13",
        "@wdio/mocha-framework": "^5.11.0",
        "@wdio/runner": "^5.11.13",
        "@wdio/sauce-service": "^5.11.1",
        "@wdio/spec-reporter": "^5.11.7",
        "@wdio/sync": "^5.11.13",
        "chai": "^4.2.0",
        "chromedriver": "^77.0.0",
        "deepmerge": "^4.0.0",
        "geckodriver": "^1.16.2",
        "mocha": "^6.2.0",
        "wdio-chromedriver-service": "^5.0.2",
        "wdio-geckodriver-service": "^1.0.2",
        "wdio-intercept-service": "^3.0.2",
        "wdio-video-reporter": "^1.4.4",
        "wdio-webdriver-service": "^0.1.7",
        "webdriverio": "^5.11.13"

</details>

**Config of WebdriverIO**
<details> <summary>config</summary> 

```
{
  baseUrl: 'https://staging.instructables.com',
  sync: true,
  specs: [ '**/**/project.spec.js' ],
  suites: {
    …  },
  timeout: 90000,
  waitforTimeout: 20000,
  logLevel: 'error',
  bail: 0,
  maxInstances: 1,
  services: [ 'chromedriver', 'intercept' ],
  reporters: [
    [ 'junit', [Object] ],
    [ [Function: Video], [Object] ],
    [ 'allure', [Object] ],
    'spec'
  ],
  afterTest: [Function: afterTest],
  framework: 'mocha',
  mochaOpts: { ui: 'bdd', timeout: 20000 },
  execArgv: [ '--inspect-brk=127.0.0.1:5859' ],
  capabilities: [ { browserName: 'chrome', 'goog:chromeOptions': [Object] } ],
  path: '/'
}
```

</details>

**Describe the bug**

Pretty simple: `browser.getCurrentTabId is not a function` when I run `browser.getCurrentTabId();`

**To Reproduce**

```       
 it('Share a project', () => {
            const mainTabId = browser.getCurrentTabId();
```

**Expected behavior**
The documented function exists. http://v4.webdriver.io/api/window/getCurrentTabId.html

**Comment by mgrybyk** [comment]
Get current tab id is wdio v4 command, in v5 please use https://webdriver.io/docs/api/webdriver.html#getwindowhandle

**Comment by jcollum-autodesk** [comment]
Your docs should say what version they apply to on the page instead of in the url.

**Comment by christian-bromann** [comment]
Please see the comment at the top of this page: https://webdriver.io/docs/api.html

> Note: These are the docs for the latest version (v5.0.0) of WebdriverIO. If you are still using v4 or older please use the legacy docs website v4.webdriver.io!

This is probably not prominent enough. If you have any ideas on improvements, please let us know!

**Comment by jcollum-autodesk** [comment]
http://v4.webdriver.io/api/window/getCurrentTabId.html -- this page says nothing about not being applicable for v5.

**Comment by christian-bromann** [comment]
I thought having `v4` in the url would make it clear enough. Thanks for the feedback.

**Comment by jcollum-autodesk** [comment]
Why would someone look at a url for documentation? If it doesn't say the version on the page I'm going to assume it's for the current version.
