### ISSUE TITLE
Question about webdriverio 'retry flaky tests' feature

### ISSUE THREAD

**Issue by pk-saxena** [webdriverio/webdriverio#4628]
I am using `@wdio/sync": "^5.11.0`. 
Can I pass an extra argument to `before` method which specifies number of re-runs in case of a failure?
The documentation states that I can pass it to hooks too but it doesn't work for me. 
https://webdriver.io/docs/retry.html
This is how I'm doing it
```
  before(async () => {
    const respJobList = await executeScriptFromPathToGenerateBaseData(
      __dirname,
      '../',
      'data',
      'job_list',
      'jobList.yml'
    )
    expect(respJobList).to.not.equal(undefined)
    recruiterJobListTest = {
      email: respJobList.recruiterJobList.email,
      password: respJobList.recruiterJobList.password
    }
  }, 2)
```

**Comment by mgrybyk** [comment]
@pk-saxena are you using Jasmine or Mocha?

**Comment by mgrybyk** [comment]
for mocha `this.retries(2)` works only for `describe` and `it` blocks.
If you want to use `before(() => {}, 2)` you have to use sync mode

**Comment by mgrybyk** [comment]
If you have any questions feel free to reopen or ping me, cheers!

**Comment by pharaoh-11** [comment]
@mgrybyk is there a way to understand that test is on retry? I want to take screenshots on each step but on for retried tests. If it's not possible right now can you prepare such functionality for the next releases?

**Comment by christian-bromann** [comment]
> If it's not possible right now can you prepare such functionality for the next releases?

Feel free to make a feature proposal and send along a PR.
