### ISSUE TITLE
waitForText() broken when using promises

### ISSUE THREAD

**Issue by binarykitchen** [webdriverio/webdriverio#463]
```js
.waitForText('button').should.become('Login')
```

does not work and always times out whereas

```js
      .waitFor('button')
      .getText('button').should.become('Login')
```

works fine. Why?

**Comment by christian-bromann** [comment]
`waitForText` doesn't suppose to return the text of the button. The commands waits until the element contains some text (or the opposite if reverse is set to true) and returns with a boolean. `getText` is the correct command to retrieve the text of an element.

**Comment by binarykitchen** [comment]
Oh, that wasn't so obvious in the documentation, a bit misleading. `waitForTextExist()` or something would be more clear.
