### ISSUE TITLE
browser.execute can't return -1 or less than -1

### ISSUE THREAD

**Issue by shinxi** [webdriverio/webdriverio#4630]
**Environment:**
 - **WebdriverIO version:** 5.15.0
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v10.4.1
 - **NPM version:** 6.1.0
 - **Browser name and version:** Chrome 77
 - **Platform name and version:** MacOS
 - **Additional wdio packages used (if applicable):** 
    > "@wdio/allure-reporter": "^5.14.5",
    "@wdio/cli": "^5.15.0",
    "@wdio/jasmine-framework": "^5.15.0",
    "@wdio/junit-reporter": "^5.15.0",
    "@wdio/local-runner": "^5.15.0",
    "@wdio/spec-reporter": "^5.14.5",
    "@wdio/sync": "^5.14.4",
    "webdriverio": "^5.15.0"

**Describe the bug**
browser.execute can't return -1 or less than -1.

**To Reproduce**

```js
browser.execute(() => {
  return -1;
});
```
This will report `RangeError: Invalid typed array length: -1`.

**Expected behavior**
browser.execute should be able to return -1. wdio v4 works fine.

**Comment by mgrybyk** [comment]
@shinxi can't reproduce this. May you please provide with some reproducible example? Maybe it depends on your environment?

my test
```
describe("Main suite", () => {
    it("some test", () => {
        console.log('exec', browser.execute(() => {
            return -1;
        }))
    })
})
```

Tested with `selenium-standalone` and just `chromedriver`.

ENV:
- chromedriver: '77.0.3865.40'
- chrome: '77.0.3865.120'
- nodejs: v10.16.3
- OS: MacOS

**Comment by shinxi** [comment]
@mgrybyk Can you share your devDependencies at package.json? Here is mine.
```js
  "devDependencies": {
    "@wdio/allure-reporter": "^5.14.5",
    "@wdio/cli": "^5.15.0",
    "@wdio/dot-reporter": "^5.14.5",
    "@wdio/jasmine-framework": "^5.15.0",
    "@wdio/junit-reporter": "^5.15.0",
    "@wdio/local-runner": "^5.15.0",
    "@wdio/spec-reporter": "^5.14.5",
    "@wdio/sync": "^5.14.4",
    "babel-eslint": "^8.2.3",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-register": "^6.26.0",
    "eslint": "^4.19.1",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-plugin-import": "^2.12.0",
    "husky": "^0.14.3",
    "lint-staged": "^7.2.0",
    "moment": "^2.22.2",
    "moment-timezone": "^0.5.23",
    "prettier-eslint": "^6.4.3",
    "selenium-standalone": "^6.16.0",
    "shelljs": "^0.8.2",
    "webdriverio": "^5.15.0"
  },
```
Also what's your selenium server version? mine is `3.141.59`.

Thanks.

**Comment by mgrybyk** [comment]
Looks pretty much the same but two points. I'm not using babel but it should not be an issue.
And why are you using selenium-standalone instead of https://webdriver.io/docs/selenium-standalone-service.html

I have the same selenium version

**Comment by mgrybyk** [comment]
Can you please try building project according to the getting started guide and see if issue replicates for you?
If no move your code gradually to understand what exactly is causing the issue

**Comment by christian-bromann** [comment]
I was also not able to reproduce this. Please provide a reproducible example. I am happy to reopen this case then.
