### ISSUE TITLE
Hooks are executed twice for it.only function

### ISSUE THREAD

**Issue by ArminasKaz** [webdriverio/webdriverio#4631]
`it.only` is wrapped twice with `wrapTestFunction`

### env
- wdio: 5.15.0

### Steps to reproduce
1. add console log to before/after test/hook
2. run test
```
describe("Main suite", () => {
    it.only("some test 2", () => {
        browser.pause(100)
    })
})
```

### Actual result
hooks are executed twice

**Comment by mgrybyk** [comment]
@ArminasKaz it depends on the test framework you use. If it's mocha then you have mocha test and context, otherwise jasmine. 

Does it answers your question or I've misunderstood you?

**Comment by ArminasKaz** [comment]
Thanks for the fast answer. Hmm, ok I will explain my issue in more detail:
 I use mocha framework (but I do not use mocha `afterEach` in my suites). In wdio.conf I use `afterTest` to do some general logging/cleanup/screenshoting once every test finishes. But since this new release - `afterTest` is called 2 times and it seems it has same test and context every time and all my after-tasks are executed twice.... Is it correct behaviour?

**Comment by mgrybyk** [comment]
No, afterTest should be executed once after every it block.
Are you sure you are not mixing afterTest and afterHook or don't have two afterTest hooks?

**Comment by mgrybyk** [comment]
Example:
my test:
```
describe("Main suite", () => {
    beforeEach(() => {
        console.log('beforeEach')
    })
    afterEach(() => {
        console.log('afterEach')
    })
    it("some test", () => {
        console.log("test")
    })
})
```

my hooks in wdio.conf
```
beforeTest (test, context) {
    console.log('WDIO_HOOK: before test')
},
beforeHook (test, context) {
    console.log('WDIO_HOOK: before hook')
},
afterTest (test, context, { passed }) {
    console.log('WDIO_HOOK: after test\n')
},
afterHook (test, context, { passed }) {
    console.log('WDIO_HOOK: after hook\n')
},
```

test run output
```
[0-0] WDIO_HOOK: before hook
[0-0] beforeEach
[0-0] WDIO_HOOK: after hook

[0-0] WDIO_HOOK: before test
[0-0] test
[0-0] WDIO_HOOK: after test

[0-0] WDIO_HOOK: before hook
[0-0] afterEach
[0-0] WDIO_HOOK: after hook
```

which is correct

**Comment by ArminasKaz** [comment]
ok, I have investigated this more and have found that this behaviour exists only if I run mocha test as `it.only()` . So in such case beforeTest/afterTest hooks are executed 2 times each. Such behaviuor was absent in v.5.13.2. Is it correct how the new version works?

**Comment by mgrybyk** [comment]
@ArminasKaz looks like a defect to me

**Comment by mgrybyk** [comment]
should be fixed with the PR, let's proceed discussion there if you like.
