### ISSUE TITLE
Jasmine test object breaking change

### ISSUE THREAD

**Issue by carlos-gva** [webdriverio/webdriverio#4632]
**Environment:**
 - **WebdriverIO version:** [5.14.5]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [10.16.0]
 - **NPM version:** [6.9.0]
 - **Browser name and version:** [Chrome 77]
 - **Platform name and version:** [macOS Mojave 10.14.6]
 - **Additional wdio packages used (if applicable):** [@wdio/jasmine-framework, @wdio/spec-reporter]

**Describe the bug**
When updating webdriverio to **v5.14.5** version (from **v5.13.2**), I noticed that jasmine had a breaking change.
I'm handling the **test object** on the `AfterTest` hook and the property `title` disappeared and now it's called `description` and I had to update my scripts.

**To Reproduce**
Try to handle `test.title` inside the `AfterTest` hook on this version.

**Expected behavior**
I shouldn't expect a breaking change on this update.

**Comment by mgrybyk** [comment]
should be fixed with the PR
