### ISSUE TITLE
Get the browser's console output?

### ISSUE THREAD

**Issue by binarykitchen** [webdriverio/webdriverio#464]
Hello again

Would be good to get the output of the browser's console. I'd like to add another check in my tests whether there is an error output in the console or not.

Preferable an event handler like 

```js
client.on('console', function(level, output) {
});
```

or better have an event for each level.

Not sure if something like this is already implemented. Searched in your documentation but found no clues.

**Comment by christian-bromann** [comment]
Hi @binarykitchen ,
this won't be possible. There is no way WebdriverIO can interfere the console.log method in the browser. You could file [a new issue](https://github.com/SeleniumHQ/selenium/issues/new) to the Selenium project and propose this idea. This has to get implemented on Selenium level.

**Comment by xbill82** [comment]
Apparently Selenium provides a way to catch `console.log` calls. It is possible to intercept them with the selenium java bindings.
http://stackoverflow.com/questions/19225532/is-there-a-way-to-view-phantomjs-console-log-messages-via-selenium-ghostdriver
Do you think this would be implementable in webdriver.io?

**Comment by graingert** [comment]
@xbill82 this should be available in `client.logs('browser')` http://webdriver.io/api/protocol/log.html

**Comment by DDeepu** [comment]
@graingert  client.logs('browser') only works with chrome. How do i check for edge browser??

**Comment by danielantelo** [comment]
any way of getting `client.logs('browser')` to work in safari?

**Comment by mpayne-swm** [comment]
Looks like the protocol no longer supports client.logs() at all - https://webdriver.io/api/protocol/log.html does a redirect to https://webdriver.io/api/protocol/log.html.

Here's a hint - next time that you deprecate something, leave a page that details the deprecation and includes a strategy that can be used in its place.

**Comment by mgrybyk** [comment]
@mpayne-swm there is such page, it is changelog.

**Comment by christian-bromann** [comment]
> Here's a hint

@mpayne-swm thanks a lot for your input. Unfortunately it wasn't our decision to deprecate this functionality. With the WebDriver protocol this command was removed and it started to have an effect with certain browser version. Some browser like Chrome however still support it. Please elaborate on how this could have been better handled?

**Comment by graingert** [comment]
A vendor specific command to access the logs would have worked

**Comment by mpayne-swm** [comment]
@christian-bromann, as I mentioned above, please don't remove pages for deprecated functionality - leave them there with an explanation and/or alternative strategies.

**Comment by christian-bromann** [comment]
We did not remove any page. You can still find the command for:

v5: https://webdriver.io/docs/api/jsonwp.html#getlogs
v4: http://v4.webdriver.io/api/protocol/log.html

If there would be an alternative solution we would never have removed the command.

**Comment by davidcoleman007** [comment]
> @mpayne-swm there is such page, it is changelog.

i heartily disagree. Those who find pages linked on issues like this or have them saved in browser bookmarks will have no way of knowing why the link is broken.
