### ISSUE TITLE
A Test framework made for tailored for WebDriver

### ISSUE THREAD

**Issue by b1zzu** [webdriverio/webdriverio#4643]
**Is your feature request related to a problem? Please describe.**

This is what I usually do when I write a test:
1. I go to an URL
2. then I wait for a button, and I click on it
3. then again I wait for a form, I fill it up, I wait for the submit button, and I click on it.

But even in these very easy steps, there are too many points where it could fail, for example:
* The button is visible but it was in a transaction, so the click go hit the wrong place
* The button is visible but the on click event has not yet been bounded to the button

So if I run the test 1000 times it always fails a couple or more times making the test unstable.

Also, another common reason of flaky tests are degradation of performance on the client or backend side.

**Describe the solution you'd like**

I would like to have a framework where I could define a `step` made by a `precondition`, an `action`, and a `postcondition`. So the first thing is waiting for the `precodition`, then perform the `action`, and wait for the `postcodition` to be satisfied, if the `postcodition` is within a timeout, check again if the `precodition` is valid (otherwise fail), then perform again the `action` and wait again for the `postcondition` but maybe with an increased timeout, and so one for a two or three times. 

**Describe alternatives you've considered**

I've tried to use `mocha` with `it` and `retries` but I can't apply the same logic to `before` or I can not put this logic inside a method (for example a login method has multiple steps).

I've tried to create a `step` function that implements my logic and take the three methods (`precodition`, `action`, `postcodition`), but I can not be notified of degradation (multiple retries) in the process. (but it still remain a valid solution) 

**Additional context**

So my question is, would it make sense to have a test framework (like mocha) but tailored for UI tests to solve my above issues but also many others?

**Comment by mgrybyk** [comment]
@b1zzu go ahead and add / overwrite custom commands that would wait for visibility or certain anchors, or even retries https://webdriver.io/docs/customcommands.html

Framework has also support flacky test retrying in whichever way you like

**Comment by christian-bromann** [comment]
I agree with @mgrybyk .. with custom commands WebdriverIO allows you to create steps with certain pre/post conditions. We also have before/afterCommand hooks that allow you to place specific checks. So overall I think WebdriverIO provides opportunities to do that.

**Comment by b1zzu** [comment]
@christian-bromann @mgrybyk I understand it's possible to do it, but I just wanted to understand if it is a common problem and for this reason would make sense to solve it one for everyone instant of everyone solving it on his own.

I didn't open this issue as a bug, or enhancement requirements, I just wanted to hear the opinion of the community.

**Comment by mgrybyk** [comment]
Can it be made like a pluggable extension for mocha? I mean a standalone package that extends mocha functionality ?

**Comment by christian-bromann** [comment]
@b1zzu we already have some post command steps that e.g. fixes stale element exception issues or waits for element. If you have some specific examples that you think can solve common issues please let us know.

**Comment by b1zzu** [comment]
@mgrybyk maybe, I didn't investigate in that direction, thanks

@christian-bromann sure I will make some more experiment and maybe come back with some real example
