### ISSUE TITLE
isDisplayedInViewport returns true for non existing element or for hidden element

### ISSUE THREAD

**Issue by igerasimov23** [webdriverio/webdriverio#4646]
**Environment (please complete the following information):**
 - **WebdriverIO version:**5.15.1
 - **Mode:** wdio
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v10.16.0
 - **NPM version:** v.6.9.0
 - **Browser name and version:** chrome 77
 - **Platform name and version:** mac/windows

**Describe the bug**
isDisplayedInViewport() method returns true for non existing element in DOM or for hidden element

**To Reproduce**
~**Scenario 1**~ should be fixed with https://github.com/webdriverio/webdriverio/pull/4647
``` 
browser.url('https://www.google.com/');
console.log($('.hello-world').isDisplayedInViewport()); // returns true
```

~*Expected behavior*~
~Should return false as element does not exist and not displayed~

**Scenario 2**
When element in DOM, but hidden under dropdown. element.isDisplayed() returns true, but element.isDisplayedInViewport() should return false as element not in viewport

**Comment by mgrybyk** [comment]
@igerasimov23 clarification regarding scenario 2. Why do you think `isDisplayed` should return `true` is the element is actually not visible?
I think both `isDisplayed` and `isDisplayedInViewport` should return `false`

**Comment by igerasimov23** [comment]
I agree with you but unfortunately this is not how `isDisplayed()` works this days for all cases. I attached 2 screenshots. one 1st and on 2nd screenshot `isDisplayed()` returns true even when on 2nd screenshot element in DOM but not actually visible on the screen(hidden). Let me know if I'm missing here something
<img width="1024" alt="Screen Shot 2019-10-17 at 5 11 29 PM" src="https://user-images.githubusercontent.com/15241367/67048249-de660500-f101-11e9-848b-78d6bf5557b7.png">
<img width="1015" alt="Screen Shot 2019-10-17 at 5 11 50 PM" src="https://user-images.githubusercontent.com/15241367/67048262-e58d1300-f101-11e9-8df8-a3833715966f.png">

**Comment by mgrybyk** [comment]
@igerasimov23 don't you think it is wrong behavior?

**Comment by mgrybyk** [comment]
at least in such case I think both isDisplayed commands should return false

![image](https://user-images.githubusercontent.com/25589559/67048786-20f50500-f135-11e9-899b-165f7223aa58.png)

**Comment by igerasimov23** [comment]
@mgrybyk I agree it should return false! if element not displayed

**Comment by mgrybyk** [comment]
let's proceed convo in the PR.

**Comment by mgrybyk** [comment]
@igerasimov23 instead of changing behavior of `isDisplayedInViewport` command we'll introduce new command `isClickable` to check if element is clickable.

So, in your case
```
// still true here, nothing changd
console.log($('.hello-world').isDisplayedInViewport()); // returns true

// new command will be added
console.log($('.hello-world').isClickable()); // returns false
```
