### ISSUE TITLE
Sauce Service don't update correctly the test status

### ISSUE THREAD

**Issue by alessandronoceraspx** [webdriverio/webdriverio#4648]
Hi all,
I've the last version of wdio and my tests are run on testobject cloud with RDC devices. 
All works fine but with the last updated  that I made (below my current framework structure), the sc don't update the status correctly when the test failed (every test result is marked PASSED but the report show me the FAILED assertion).

```
"devDependencies": {
    "webdriverio": "5.15.1",
    "@wdio/allure-reporter": "^5.14.5",
    "@wdio/cli": "^5.15.1",
    "@wdio/devtools-service": "^5.15.1",
    "@wdio/firefox-profile-service": "^5.13.2",
    "@wdio/jasmine-framework": "^5.15.1",
    "@wdio/junit-reporter": "^5.15.1",
    "@wdio/local-runner": "^5.15.1",
    "@wdio/sauce-service": "^5.14.0",
    "@wdio/selenium-standalone-service": "^5.15.0",
    "@wdio/spec-reporter": "^5.15.1",
    "@wdio/sync": "^5.15.1",
    "babel-cli": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "eslint": "^6.5.0",
    "eslint-config-airbnb-base": "^14.0.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jasmine": "^2.10.1",
    "husky": "^3.0.9",
    "rimraf": "^3.0.0",
    "wdio-chromedriver-service": "^5.0.2",
    "wdio-iedriver-service": "^0.1.0"
  },
  "dependencies": {
    "appium": "^1.15.0",
    "chromedriver": "^77.0.0",
    "iedriver": "^3.14.1",
    "shelljs": "^0.8.3"
  }
```

Last, I've tried to run the script in two ways:
- simple npm command from CLI;
- from Jenkins pipeline with some jobs (all work very well but the status is every time set to PASSED).

This is a simple spec reporter produced by automation execution:

```
> wdio wdio.conf.js --spec ./dist/testcases/epic0/user-story-0.01.js


Execution of 1 spec files started at 2019-10-17T21:25:44.958Z

[0-0] RUNNING in Android - C:\jenkins\workspace\no-regression-suite\dist\testcases\epic0\user-story-0.01.js
[0-0] elX: 16  |  elY: 340
[0-0] Error in "EPIC-0: UI Showcases - List items User Story 0.01 - 03.02 Left icon advanced Checking carIcon presence in the div and its position"
Expected false to be true, 'The element carIcon has position { 16; 340}, instead of { 16; 1317}'.
[0-0] elX: 320  |  elY: 340
[0-0] elX: 320  |  elY: 340
[0-0] Error in "EPIC-0: UI Showcases - List items User Story 0.01 - 03.02 Left icon advanced Checking arrowIcon position in the div"
Expected false to be true, 'The element arrowIcon has position { 320; 340}, instead of { 372; 1317}'.
[0-0] FAILED in Android - C:\jenkins\workspace\no-regression-suite\dist\testcases\epic0\user-story-0.01.js
```

Thanks guy for the help. This is very strange issue.

**Comment by alessandronoceraspx** [comment]
Little update:
I've rollbacked the wdio sauce service to the previous version (5.13.2) but error remains. I don't know why the status is set every time to PASSED. It make no sense. I've tried to run the script via jenkins and cli also.
Same results. 

I'm still on finding a solution but I think that the issue is releated to the sauce service package, I mean.

**Comment by alessandronoceraspx** [comment]
Hi all, after some checking and try and retry...I've found a strange case in my framework (I think). Inside wdio.conf in `after` method, the `result` value when the test is marked to FAILED is one time set to 1 and in other time set to 2. But, inside the official wdio.conf documentation is explained this:

```
/**
   * Gets executed after all tests are done. You still have access to all global variables from
   * the test.
   * **@param {Number} result 0 - test pass, 1 - test fail**
   * @param {Array.<Object>} capabilities list of capabilities details
   * @param {Array.<String>} specs List of spec file paths that ran
*/
```

0 if test is **PASSED**, 1 if test is **FAILED**...but if **result** is set to 2...obliviously the after method is not used correctly. 

I ask you: it's a bug otherwise the "result 2" is correct in some way? Where is the logic respect the documentation? I'm very courious to know if it is my mistake or it truly is a bug. 

For the moment, I have fix this by using this piece of code (let me say it's a workaround):

 ```
after: function (result, capabilities, specs) {
    result = (result === 2) ? 1 : result;
    if (result === 1) {
      //my logic code
    };
  },
```

Thank you all!

**Comment by christian-bromann** [comment]
> @param {Number} result 0 - test pass, 1 - test fail

This is wrong documentation. The `result` variable gives you the amount of errors of your test suite (amount of failing specs). So just change your code as following:

```js
after: function (result, capabilities, specs) {
   if (result !== 0) {
     //my logic code
   };
 },
```

Are there any other issues?

**Comment by alessandronoceraspx** [comment]
Now is more clear! The outdated documentation has confused me. Ok Christian, of course I will change the logic in order to have all correct.
But I have last question for you:
I have the last version of WDIO and the last version of Sauce Service and I think that in the sauce there is an issue releated to this `results` because before my updated the result is every time updated correctly but now not. 
So, there is a new version incoming scheduled? And last: where is possible to find the wdio documentation updated in order to integrate in my framework? 

In the past, I've migrated from wdio v4 to v5 but I suppose that the wdio.conf was untouched from my side (just some few little adjustment in order to continue to use).

Thank and I hope that my issue can help some other peoples.
