### ISSUE TITLE
Session capabilities are lost when re-attaching to session

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4651]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.15.1
 - **Mode:** test runner

**Config of WebdriverIO**
watch mode, maybe some other mode where we need to re-attach to session.

**Describe the bug**
User defined capabilities

**To Reproduce**
1. run wdio in watch mode
2. see capabilities on first test run (it's session capabilities)
```
{
  "acceptInsecureCerts": false,
  "browserName": "chrome",
  "browserVersion": "77.0.3865.120",
  "chrome": {
    "chromedriverVersion": "77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442})",
    "userDataDir": "/var/folders/bf/1m__bf0d0y51tvtbdk50vz5m0000gn/T/.com.google.Chrome.zL9cvN"
  },
  "goog:chromeOptions": {
    "debuggerAddress": "localhost:60658"
  },
  "networkConnectionEnabled": false,
  "pageLoadStrategy": "normal",
  "platformName": "mac os x",
  "proxy": {},
  "setWindowRect": true,
  "strictFileInteractability": false,
  "timeouts": {...},
  "unhandledPromptBehavior": "dismiss and notify",
  "webdriver.remote.sessionid": "d98b0012763a10c82dd2a0dc0a7e2600"
}
```
3. change something in test 
4. see capabilities (now it's user defined capabilities)
```
{
  "browserName": "chrome",
  "goog:chromeOptions": {
    "args": []
  },
  "excludeDriverLogs": [
    "*"
  ],
  "maxInstances": 4
}
```

**Expected behavior**
store session capabilities and then reuse them when reattaching to session.

**Additional context**

**Comment by mgrybyk** [comment]
To use `sharedStore` service to save session capabilities the service has to be added to dependencies of `wdio-cli` package. Is it ok?
Or we should look for some alternatives?

**Comment by christian-bromann** [comment]
I am not sure about this. I would rather fix this in the protocol. The driver should be capable to store the capabilities it returns when initiating the session.

**Comment by mgrybyk** [comment]
Yeah, sounds good

**Comment by christian-bromann** [comment]
An issue was made in the protocol. Closing this.
