### ISSUE TITLE
@wdio/browserstack-reporter

### ISSUE THREAD

**Issue by sschweigert11** [webdriverio/webdriverio#4657]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** v5.15.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.15.3
 - **NPM version:** 6.4.1
 - **Browser name and version:** N/A
 - **Platform name and version:** N/A
 - **Additional wdio packages used (if applicable):** @wdio/browserstack-reporter

**Describe the bug**
I'm attempting to load this package, which is indicated in an error message when I attempt to run the older wdio-browserstack-reporter to try to load @wdio/browserstack-reporter but no package current exists.

**To Reproduce**
Add @wdio/browserstack-reporter as a dependency and try to configure a verion.

**Expected behavior**
The package loads.

**Additional context**
I'm unable to display the output results to ADO using the BrowserStack extension.

**Comment by christian-bromann** [comment]
The `wdio-browserstack-reporter` reporter is not compatible with WebdriverIO v5. The error message is a generated error message that we show in case a package fails to load. Even though it states to try to install `@wdio/browserstack-reporter` it doesn't know whether or not that package exists. Please report the error in the `wdio-browserstack-reporter` project. Cheers!
