### ISSUE TITLE
Send number of retries to afterTest() hook

### ISSUE THREAD

**Issue by igerasimov23** [webdriverio/webdriverio#4662]
**Is your feature request related to a problem? Please describe.**
Mocha and WebdriverIO now does not report number of retries in afterTest() hook in which test right now during execution. But it will be very useful to help identify **flaky** tests. Many reporting system support retry option (such as https://reportportal.io/) but we can not send anything to that from WebdriverIO during execution

**Describe the solution you'd like**
afterTest() hook should send number of retry in which test during execution. For example, if we have globally set Retry option to `3`, test failed on 2nd we should send number `2` and so on.

**Comment by mgrybyk** [comment]
It's possible however there are two levels of retires:
- spec file retires (webdriverio)
- test retries (particular test framework, ex mocha)

spec file retries can be added to `config` while test retries can be added to after hook, something like this:
```
afterTest (_, __, result) {
    console.log(result.repeatTest) // test retries amount defined by user
    console.log(result.testRetryAttempts) // test retry attempts

    console.log(this.config.specFileRetries) // spec retries amount defined by user
    console.log(this.config.specRetryAttempts) // spec retry attempts
},
```

**Comment by igerasimov23** [comment]
@mgrybyk Sorry, I was not clear here. I meant `test retries (particular test framework, ex mocha)`.
If we would have this 
```
afterTest (_, __, result) {
// require some internal signature changes
    console.log(result.repeatTest) // test retries amount defined by user
    console.log(result.testRetryAttempts) // test retry attempts
```
I think it would be a game change in identifying on early stage flaky tests

**Comment by mgrybyk** [comment]
Got it, I'd add both test and spec retries counter to let user deal with it

**Comment by mgrybyk** [comment]
should be implemented with the pr
