### ISSUE TITLE
How to use different login users in different test instances

### ISSUE THREAD

**Issue by benjaminliugang** [webdriverio/webdriverio#4665]
Hi,

Now we try to set `maxInstances` > 1 to run multiple instances at the same time, but we could not specify a different user for different instance.

Do we have a global variable that can help to lock/unlock the users? Then when starting a new instance, it could base on the lock list to get an unlocked user.

**Comment by mgrybyk** [comment]
I think you should be able to set user to capabilities and then get it in test.
Does it work for you?

**Comment by mgrybyk** [comment]
One more question, can you have a list of users and then just query each of them before starting the test. If user is locked, query next one, do until you get user in a proper state

**Comment by benjaminliugang** [comment]
Thanks, @mgrybyk!
For capabilities, it seems we could not specify a user for each instance.
Now I just do it as you mentioned, lock/unlock the user before/after running each suite by persisting the user status in file(use `fx-extra` to read/write).

**Comment by christian-bromann** [comment]
> For capabilities, it seems we could not specify a user for each instance.

Why is that? I am not sure what your scenario looks like but I would order my tests based on the user type you are testing. Then you can specify the user as part of your capabilities and also just run a specific set of specs based on that capability.
