### ISSUE TITLE
Unable to run WDIO v5 Cucumber Framework  - Getting Timeouts issues after launching the link

### ISSUE THREAD

**Issue by psubrambe** [webdriverio/webdriverio#4667]
Error : function timed out, ensure the promise resolves within 360000 milliseconds
 
Attached Package.json

Node : 10.15.0
npm : 6.4.1
OS : Windows 7 x64

dependencies": {
  "@types/node": "12.7.5",
  "@wdio/reporter": "5.12.1",
  "eslint": "^6.4.0",
  "faker": "^4.1.0",
  "fs": "0.0.2",
  "fs-extra": "8.1.0",
  "gherkin-lint": "3.3.6",
  "glob": "^7.1.4",
  "gulp": "^4.0.2",
  "gulp-sequence": "1.0.0",
  "lodash": "4.17.15",
  "make-dir": "^3.0.0",
  "multiple-cucumber-html-reporter": "1.13.1",
  "os": "^0.1.1",
  "path": "0.12.7",
  "pre-commit": "1.2.2",
  "resolve": "1.12.0",
  "selenium-standalone": "6.16.0",
  "sync-request": "^6.1.0",
  "system-sleep": "^1.3.6",
  "wdio-reportportal-reporter": "^5.0.1",
  "wdio-reportportal-service": "^5.0.2",
  "webdriverio": "5.15.2",
  "xmldom": "0.1.27",
  "yaml-lint": "^1.2.4",
  "yaml-merge": "0.0.2"
},
"devDependencies": {
  "@wdio/cli": "5.15.2",
  "@wdio/cucumber-framework": "5.15.1",
  "@wdio/local-runner": "5.15.2",
  "@wdio/sauce-service": "5.12.5",
  "@wdio/spec-reporter": "5.12.1",
  "@wdio/sync": "5.15.1",
  "wdio-cucumberjs-json-reporter": "1.1.1"
}

Error While running scripts in above eniv : 

[chrome 77.0.3865.120 Windows NT #0-0] function timed out, ensure the promise resolves within 360000 milliseconds
[chrome 77.0.3865.120 Windows NT #0-0] Error: function timed out, ensure the promise resolves within 360000 milliseconds
[chrome 77.0.3865.120 Windows NT #0-0] at Timeout._time.default.setTimeout [as _onTimeout] (C:\Users\8783460\Desktop\test\br-sync\node_modules\cucumber\lib\user_code_runner.js:81:20
)
[chrome 77.0.3865.120 Windows NT #0-0] at ontimeout (timers.js:436:11)
[chrome 77.0.3865.120 Windows NT #0-0] at tryOnTimeout (timers.js:300:5)
[chrome 77.0.3865.120 Windows NT #0-0] at listOnTimeout (timers.js:263:5)
[chrome 77.0.3865.120 Windows NT #0-0] at Timer.processTimers (timers.js:223:10)
[chrome 77.0.3865.120 Windows NT #0-0] at module.exports.runLoopOnce (C:\Users\8783460\Desktop\test\br-sync\node_modules\deasync\index.js:65:10)
[chrome 77.0.3865.120 Windows NT #0-0] at module.exports (C:\Users\8783460\Desktop\test\br-sync\node_modules\deasync-promise\index.js:13:9)
[chrome 77.0.3865.120 Windows NT #0-0] at module.exports.interval (C:\Users\8783460\Desktop\test\br-sync\node_modules\system-sleep\module.js:24:36)

**Comment by mgrybyk** [comment]
Can't help without reproducible example

**Comment by psubrambe** [comment]
What kind of example required ? .

We are using WDIO V5 - Cucumber framework in Windows 7 Enterprise with Node Version 10.15.0.

Please let me know what is required in framework side

**Comment by christian-bromann** [comment]
> Please let me know what is required in framework side

Something that we can run that reproduces the issue. We don't know whether you are using WebdriverIO wrong or what the issue is about.

**Comment by psubrambe** [comment]
PFB  for https://github.com/psubrambe/wdio-cucumber-framework-5

**Comment by mgrybyk** [comment]
@psubrambe may I ask you for a bit help here please. It would be very helpful if you can create some branch with minimal reproducible example containing only minor changes in comparison to default config and just one feature/action, without pages, actions, etc. 
It helps debugging a lot and issue might be resolved way faster!

**Comment by psubrambe** [comment]
Could you please provide info what you exactly required i need to remove actions and pages ?

**Comment by mgrybyk** [comment]
To be short remove as much of your code as possible but still be able to reproduce the issue

**Comment by christian-bromann** [comment]
@psubrambe a minimal reproducible example is something like this: https://github.com/webdriverio/webdriverio/tree/master/examples/wdio/cucumber.

**Comment by psubrambe** [comment]
https://github.com/psubrambe/wdio-cucumber-framework-5/tree/minimalCode . updated in branch
this POM model were i can able to reduce only this much

**Comment by mgrybyk** [comment]
fix infinite loop in your `objectCollector`

Such issues will be closed automatically in the future without minimal reproducible example with lots of user code.
