### ISSUE TITLE
click method does not work on Android device (interaction WebdriverIO with Hammer JS) 

### ISSUE THREAD

**Issue by kusha1988** [webdriverio/webdriverio#467]
I want to click on the button. 
```javscript
client.init()
    .url('...')
    .setValue('.username', 'userbame')
    .setValue('.password', 'pwd')
    .click('.button', function(err, data){
        console.log(err);
        console.log(data);
        console.log("hello");
    })
```
It Chrome and Firefox this code executes correct. I can sign in to the site, but on the Android devices it does not work correct. The callback function executes and prints this:
```javscript
undefined
null
hello
```
In the old issues I have found how to fix it (https://github.com/webdriverio/webdriverio/issues/181):
```javscript
client.addCommand('click', function(selector, cb) {
    client.execute(function(cssSelector) {

        var clickEvent = document.createEvent("MouseEvent");
        clickEvent.initMouseEvent("click", true, true, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null);

        var elements = document.querySelectorAll(cssSelector);
        for(var i = 0; i < elements.length; ++i) {
            elements[0].dispatchEvent(clickEvent);
        }

    },selector, cb);
});
```
Ok. Now it works, but in my project I have elements which should trigger gesture events on a page.
For this I am using the Hammer JS library (https://github.com/hammerjs/hammer.js/wiki/Getting-Started).
```javscript
var hammer = new Hammer.Manager(this.el);
hammer.add(new Hammer.Tap());
hammer.on('tap', function (e) {
    var $el = $(e.target);
	if( $el.hasClass('touch-element') ) {
            doTouch(e);
    }
});
```
With the '.touch-element' I have the same problem on Android devices as previously with the '.button' :  the callback method executes and prints the same message, but doTouch() method does not executes. 
Then I tried to use touchClick(). The result was the same. It prints only message
```javscript
client.init()
    .url('...')
    .setValue('.username', 'userbame')
    .setValue('.password', 'pwd')
    .touchClick('.button', function(err, data){
        console.log(err);
        console.log(data);
        console.log("hello");
    })
```
I thought that the bug with the click() method was fixed previously.   
And how can I trigger 'tap' event, which will be compatible with the Hammer JS? 
### Browser and libs
```javscript
Nexus 7/9
Androin 5.0.1
WebdriverIO v. 2.4.5
Appium 1.3.4.1
Hammer JS 2.0.4
```

**Comment by christian-bromann** [comment]
@kusha1988 haven't done any work to improve support for mobile tests at all in the last time. Here is a lot of room for improvements

**Comment by christian-bromann** [comment]
removing from `v3` milestone as mobile improvements will have its own milestone

**Comment by christian-bromann** [comment]
We will have this issue fixed in v4. Depending in which context (webview or native view) you are in you can use click (webview) or touch (native) to click on an element. We added tests to make sure this works:

webview: https://github.com/webdriverio/webdriverio/blob/v4.0/test/spec/click.js
native: https://github.com/webdriverio/webdriverio/blob/v4.0/test/spec/mobile/android/touch.js
