### ISSUE TITLE
JSDoc for IDE's

### ISSUE THREAD

**Issue by pako88** [webdriverio/webdriverio#4674]
**Is your feature request related to a problem? Please describe.**
It would be nice to have the JSDoc documentation visible in IDE's like Visual Studio Code.

**Describe the solution you'd like**
I want documentation of every command visible in IDE's.

**Additional context**
![image](https://user-images.githubusercontent.com/28978631/67466122-ca149180-f646-11e9-8925-7a239f6ad148.png)
Documentation should be available in webdriverio-core.d.ts

**Comment by mgrybyk** [comment]
will be implemented with the PR
