### ISSUE TITLE
Saucelabs inputs invalid characters

### ISSUE THREAD

**Issue by cwilson0005** [webdriverio/webdriverio#4675]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 4.8
 - **Mode:** WDIO test runner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.15.3
 - **NPM version:** 6.11.3
 - **Browser name and version:** Saucelabs, Safari v11
 - **Platform name and version:** Saucelabs, iPad Air 2 Simulator, v11
 - **Additional wdio packages used (if applicable):**  "wdio-allure-reporter": "^0.8.2",
        "wdio-cucumber-framework": "^2.2.8",
        "wdio-firefox-profile-service": "^0.1.3",
        "wdio-sauce-service": "^0.4.14",
        "wdio-screenshot": "^0.6.0",
        "wdio-spec-reporter": "^0.1.5",
        "wdio-sync": "^0.7.3",
        "wdio-visual-regression-service": "^0.9.0",
        "webdrivercss-custom-v4-compatible": "^2.0.0-beta-rc1.1",
        "selenium-server-standalone": "^2.53.1",
        "selenium-server-standalone-jar": "^3.141.5",

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
Expected: WebdriverIO framework should run automated tests without inputting invalid characters in form field when using Saucelabs.

Actual: WebdriverIO framework inputs invalid characters in form field when running automation with Saucelabs

**To Reproduce**

1). Run wdio without saucelabs and invalid characters will not be input into form fields
2). Run wdio with saucelabs and invalid characters will be input into form fields

**Additional context**
Screenshot without saucelabs
![wdio-bug](https://user-images.githubusercontent.com/36211708/67467457-aa7a6a80-f640-11e9-86b6-2c9217367cac.png)
Screenshot with Saucelabs
![wdio-saucelabs-bug](https://user-images.githubusercontent.com/36211708/67467481-b36b3c00-f640-11e9-84b2-2258ab5825c4.png)

**Comment by christian-bromann** [comment]
> when running automation with Saucelabs

Sorry but this can't be fixed at the WebdriverIO level. Please reach out to the [Saucelabs Support Team](mailto:help@saucelabs.com) to get this fixed. Cheers!
