### ISSUE TITLE
I am able to view elements that are not in viewport 

### ISSUE THREAD

**Issue by gromanas** [webdriverio/webdriverio#4677]
**Describe your question with as much detail as possible**
After updating to latest wdio with the latest react-native we are able to see all application elements of all our screens (even if we have never navigated to them). Meaning we can search for an `accessibilityID` that is not used on the current screen and I can find it using Appium desktop. I have tried using the same configuration of wdio with react `0.60.5` and the issue is not reproducible.

**Environment (please complete the following information):**
     **react-native**: "0.61.2",
     **react-navigation**: "4.0.10",
     **@wdio/appium-service**: "5.12.1",
     **@wdio/cli:** "5.12.5",
    **@wdio/cucumber-framework:** "5.12.3",
    **@wdio/local-runner:** "5.12.5",
    **@wdio/sauce-service:** "5.12.5",
    **@wdio/spec-reporter:** "5.12.1",
    **@wdio/sync:** "5.12.3",
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.16.3
 - **Yarn version:** 1.17.3
 - **Platform name and version:** Android v8
 - **Additional wdio packages used:**   
    **wdio-cucumber-snippet-reporter**: "0.0.5",
    **wdio-cucumberjs-json-reporter**: "1.1.1",
    **wdio-native-app-compare-service**: "1.1.0",
    **wdio-reportportal-reporter**: "5.2.2",
    **wdio-reportportal-service**: "5.2.2",
    **multiple-cucumber-html-reporter**: "1.13.1",

**Additional context**
Sorry I cannot provide any screenshots or code cause it is in coorporated system
Any questions for clarifications are welcome.

Thank you in advance!

**Comment by wswebcreation** [comment]
Hi @gromanas 

Based on your own info you already give the answer. 

> After updating to latest wdio with the latest react-native we are able to see all application elements of all our screens 

and then 

> I have tried using the same configuration of wdio with react 0.60.5 and the issue is not reproducible.

This is not something that WebdriverIO does, WebdriverIO uses Appium and Appium provides all the data to WebdriverIO. You also mention that this is related to the upgrade from RN `0.60.5` to `0.61.2`. Therefor I'm going to close this issue

I also don't think this is not directly Appium related but RN related, but I would advice creating an issue there and provide some more context and logs where you remove the product sensitive information, but show the XML between the 2 versions

**Comment by gromanas** [comment]
Thank you @wswebcreation! Indeed it was an issue on our app and not related to WebdriverIO or Appium. I will come back when we fix it so everyone that has this issue can find a solution.
