### ISSUE TITLE
JUnit Reporter overrides xml report file after each test suite

### ISSUE THREAD

**Issue by uno-dos** [webdriverio/webdriverio#4679]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.15.1
 - **Mode:** Standalone mode 
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.16.3
 - **NPM version:** 6.9.0
 - **Browser name and version:** Chromium 61 (AFAIK)
 - **Platform name and version:** Mac High Sierra and Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/spec reporter, @wdio/selenium-standalone service, 

**Config of WebdriverIO**

wdio.conf.js:
```
exports.config = {
  host: '0.0.0.0',
  port: 4444,
  path: '/wd/hub',
  services: ['selenium-standalone'],
  maxInstances: 1,
  sync: true,
  logLevel: 'info',
  coloredLogs: true,
  deprecationWarnings: true,
  bail: 0,
  screenshotPath: './errorShots/',
  waitforTimeout: 60000,
  connectionRetryTimeout: 1700000,
  connectionRetryCount: 3,
  seleniumInstallArgs: {
    version: '3.4.0'
  },
  seleniumArgs: {
    version: '3.4.0'
  },
  framework: 'jasmine',
  jasmineNodeOpts: {
    defaultTimeoutInterval: 1700000,
    expectationResultHandler: function(passed, assertion) {
    }
  },
};
```

wdio.conf_product.js
```
const wdioConfig = require('./wdio.conf.js');
const merge = require('deepmerge');

exports.config = merge(wdioConfig.config, {
  specs: [
    './specs/test-A.js',
    './specs/test-B.js',
    './specs/test-C.js',
    './specs/test-D.js',
  ],
  capabilities: {
    librariesPanel: {
      capabilities: {
        maxInstances: 1,
        browserName: 'chrome',
        chromeOptions: {
          debuggerAddress: '127.0.0.1:123456'
        }
      },
    },
  },
  reporters: [
    'spec',
    ['junit', {
      outputDir: './output/',
      outputFileFormat: function(opts) {
        return `results_myproduct.xml`;
      }
    }]
  ],
}, {
  arrayMerge: (destination, source) => source
});
```

sample spec file **test-A.js**:
```
describe('TestSuiteA', function() {

  beforeAll(() => {
     console.log('\n-- Tests started --');
  });

  it('TestCase1', () => {
    let xyz = $('somelocator').getText();
    expect(xyz).toBe('sometext');
  });

  it('TestCase2', () => {
    let xyz2 = $('somelocator').getText();
    expect(xyz2).toBe('sometext2');
  });

  afterAll(function() {
    console.log('\n-- Tests finished --');
  });
});
```

sample spec file **test-B.js**:
```
describe('TestSuiteB', function() {

  beforeAll(() => {
     console.log('\n-- Tests started --');
  });

  it('TestCase1', () => {
    let val = $('somelocator').getValue();
    expect(val).toBe(123);
  });

  afterAll(function() {
    console.log('\n-- Tests finished --');
  });
});
```

package.json
```
{
...
"main": "wdio.conf.js",
  "dependencies": {
    "expect": "latest",
    "webdriverio": "^5.15.1"
  },
  "devDependencies": {
    "@wdio/cli": "^5.15.2",
    "@wdio/devtools-service": "^5.15.1",
    "@wdio/dot-reporter": "^5.15.2",
    "@wdio/jasmine-framework": "^5.15.1",
    "@wdio/junit-reporter": "^5.15.2",
    "@wdio/local-runner": "^5.15.2",
    "@wdio/selenium-standalone-service": "^5.15.0",
    "@wdio/spec-reporter": "^5.15.2",
    "@wdio/sync": "^5.15.1",
    "jasmine-expect": "^4.0.3"
  },
...
}

```

**Describe the bug**
JUnit reporter overrides xml report file after each test suite.

When I run wdio wdio.conf_product.js, during execution first results for test-A are written to results_myproduct.xml, then after test-B is executed  

**To Reproduce**
1. Create multiple spec files
2. Run all your tests
3. Go to output folder and check the contents of xml file

Ex of an actual output I get in **results_myproduct.xml**:
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="TestSuiteD" timestamp="2019-10-24T17:13:11" time="11.526" tests="3" failures="0" errors="0" skipped="0">
    <properties>
      <property name="specId" value="0"/>
      <property name="suiteName" value="TestSuiteD"/>
      <property name="capabilities" value=""/>
      <property name="file" value="./specs/test-D.js"/>
    </properties>
    <testcase classname=".TestSuiteD" name="TestCase1" time="2.105"/>
    <testcase classname=".TestSuiteD" name="TestCase2" time="2.139"/>
    <testcase classname=".TestSuiteD" name="TestCase3" time="7.282"/>
  </testsuite>
</testsuites>
```

**Expected behavior**
XML report file should contain all the test suites that were executed and results of those executions. Test suites should be appended to the file and not replaced.
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="TestSuiteA" >
...
  </testsuite>
  <testsuite name="TestSuiteB" >
...
  </testsuite>
  <testsuite name="TestSuiteC" >
...
  </testsuite>
  <testsuite name="TestSuiteD" >
...
 </testsuite>
</testsuites>
```

**Log**
Log doesn't show any errors and it actually shows all the tests executed correctly and in correct order, but report file is not correct. 

**Additional context**

> Please use the correct markdown

**Comment by mgrybyk** [comment]
It works as expected, write every test result to another file, see https://webdriver.io/docs/junit-reporter.html#configuration

**Comment by uno-dos** [comment]
@mgrybyk Thanks for looking into this. You are right, but I also see in that section you have a this line: 
```
outputFileFormat: function (options) {
    return 'mycustomfilename.xml';
}
``` 
that a bit misleading in this case. Should it be updated? 

Also, should I open a feature suggestion/enhancement request for this? There many tools/scripts that do this merge, but it would be much nicer to have a flag that you can enable to output to single file.
Thanks!

**Comment by mgrybyk** [comment]
Correct, we already have issues opened for that

**Comment by rostrovsky** [comment]
You can consolidate partial result xmls using one-liner after the test:
```bash
$ tcs=''; for f in results-*.xml; do tcs=${tcs}$(sed -e '/<testsuite /,/testsuite>/!d' $f); done; echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><testsuites>$tcs</testsuites>" > results.xml
```
