### ISSUE TITLE
How can I run internet explorer in webdriver.io, version 4 documentation no longer seems to apply?

### ISSUE THREAD

**Issue by tugend** [webdriverio/webdriverio#4681]
**Describe the improvement**
I'd like to report
- [x ] Unclear documentation

**Description of the improvement / report**
There is a guide in [version 4](http://v4.webdriver.io/guide/services/iedriver.html) that seems to indicate IE should be possible to use. I think I have tried all possible combinations of options and configurations, but nothing does. The best I can get is `ERROR webdriver: Request failed due to session not created: session not created: No matching capabilities found`. 

There isn't any guide on .webdriver.io, which somewhat hints at maybe IE is no longer supported. If IE is no longer supported, I think you should document it clearly, and if it is, please, oh... please update the documentation with a working example. 

Cheers

**Comment by baruchvlz** [comment]
Is there a specific reason you're using v4 instead of v5?

**Comment by tugend** [comment]
That might have been badly formulated. I'm running v5, but the best official documentation I could find was from v4. It doesn't seem like that applies any longer, and I can't find something similar in the new official docs  at https://webdriver.io/docs.

**Comment by christian-bromann** [comment]
@tugend the urls have changed: https://webdriver.io/docs/gettingstarted.html

**Comment by tugend** [comment]
@christian-bromann. Of course I have actually looked before creating an issue. Just pointing me to the introduction is kinda condescending. 

What I cannot find is an example or a proper explanation for getting internet explorer to work with wdio, nor does searching for 'internet explorer or ie' in the api docs yield any matches. Hence the claim that a part of the documentation can be improved.

**Comment by baruchvlz** [comment]
@tugend It's really hard to help you with missing information. How do your capabilities look? Are you running the IEDriver in the correct port? What have you tried so far?

**Comment by tugend** [comment]
Hey @baruchvlz ,  thank you for asking. I created this issue as a '**Suggest improvements or report missing/unclear documentation**.'. I had assumed that some label where prepended, but it looks like that's just a matter of the template instead - so I understand your confusion, sorry about that. =p.

**I'm simply requesting you to include in the documentation for wdio v5 how and if tests can be run in internet explorer.**

**Comment by christian-bromann** [comment]
> I'm simply requesting you to include in the documentation for wdio v5 how and if tests can be run in internet explorer.

Sorry, for the sake of simplicity we only cover one browser. Given the endless possibilities how you can run things (e.g. in the cloud, local or using a Selenium grid) we kind of keep it limited to a single browser since the concept is similar to other browser. This is why we offer to join the [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) where people get help for such questions much quicker.

**Comment by tugend** [comment]
Okay. I'll try that, thank you for the suggestion. 
I still think it is something that belongs in the documentation, but eh.

Cheers.
