### ISSUE TITLE
acceptAlert throws if not present

### ISSUE THREAD

**Issue by kellyselden** [webdriverio/webdriverio#4683]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.15.1
 - **Mode:** Standalone mode
 - **Node.js version:** 10.15.1
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome 78
 - **Platform name and version:** OSX

**Describe the bug**

The docs say "The Accept Alert command accepts a simple dialog *if present*." If you try to accept an alert that isn't there, you get the error

```
no such alert: no such alert\n  (Session info: chrome=78.0.3904.70)
```

I'm curious is this a docs fix, or is this an unexpected scenario with the recent chromedriver 76 alert changes?

**Expected behavior**
not sure

**Comment by christian-bromann** [comment]
Please see https://w3c.github.io/webdriver/#accept-alert point 2

> If there is no current user prompt, return error with error code no such alert.

While I understand that it might not be straightforward to read through the WebDriver spec I also want to point out that we can't document everything that is in the spec on WebdriverIO given that we have limited resources. Any contribution to the docs that help us in that matter is welcome! Cheers!

**Comment by kellyselden** [comment]
Thanks @christian-bromann
