### ISSUE TITLE
@wdio/selenium-standalone-service cannot find IE driver

### ISSUE THREAD

**Issue by tugend** [webdriverio/webdriverio#4688]
**Config of WebdriverIO**
I followed the vanilla getting started example here; https://webdriver.io/docs/gettingstarted.html.
Using a Windows 10 machine, that runs IE smoothly using Nightwatch and Selenium, or even webdriver via codecept. 

```
npm init -y
npm i @wdio/cli
.\node_modules\.bin\wdio config (yes to all and pick selenium-standalone)
Manualle chagne capabilities to `{browserName: 'internet explorer'}`
.\node_modules\.bin\wdio wdio.conf.js
```

As far as I understand this should work.
I then spent 5 hours trying various blog post suggestions to no avail.

I have tried to manually update selenium with the right driver
`.\node_modules\.bin\selenium-standalone install --drivers.ie.arch=ia32 --version=3.0.0 --drivers.ie.baseURL=https://selenium-release.storage.googleapis.com`

I have tried to add options to the selenium standalone sevice

```
services: [
      [
          'selenium-standalone',
          {
              seleniumLogs: "./",
              seleniumArgs: { 
                  drivers: {
                      ie: {
                          version: "3.141.0",
                          arch: "ia32", // forces use of 32 bit driver
                          baseURL: "https://selenium-release.storage.googleapis.com"
                      },
                  },
              },
              seleniumInstallArgs: {
                  drivers: {
                      ie: {
                          version: "3.141.0",
                          arch: "ia32", // forces use of 32 bit driver
                          baseURL: "https://selenium-release.storage.googleapis.com"
                      },
                  },
              }
          }
      ]
  ],
 ``` 

I have also tried various options for the ie driver it self

```
maxInstances: 5,
version: '3.0.0',
version: 11,
browserName: 'internet explorer',
acceptUntrustedCertificates: true,
ignoreProtectedModeSettings: true,    //only applicable to IE browser
ignoreZoomSetting: true,              //only applicable to IE browser
ensureCleanSession: true,
``` 

**Describe the bug**
Regardless of what I do, I get the same error as if I misspell the browser name, i.e. `"browserName": "internet explorer"` or `"browserName": "Vanilla Sandwich"` results in the same stacktrace which basically boils down to `Cannot read property 'capabilities' of null` and a bunch of default error page html from selenium.

See https://gist.github.com/tugend/7812b343177c1305496dc6cf93397ca4 for the full stacktrace

**To Reproduce**
See the above. 

[Include code or an example repository that can easily be set up]
See the above

**Expected behavior**
I expected IE to either work pretty painlessly or an official documentation or reference to a git example that works.

**Comment by mgrybyk** [comment]
Can you please follow https://webdriver.io/docs/selenium-standalone-service.html

If you have any issues with driver installation or running report an issue to selenium standalone service itself or iedriver project

**Comment by mgrybyk** [comment]
Closing it for now because there are some issues with setup. I'm still glad to answer further questions.

**Comment by tugend** [comment]
Could you possible share a configuration that should work, and any additional steps of installation if any, please?

If I change the configuration to something like below, the same problem occurs. I'm literally cycling through different permutations of suggestions from your documentation, the documentation of selenium and various blogposts. To the best of my knowledge, it should be trivial to add the right lines to the config, I just haven't managed to guess the right configuration, and the documentation is not clear enough for me to figure it out myself.  

```
    services: ['selenium-standalone'],
    seleniumLogs: 'logs',
    seleniumInstallArgs: {
        drivers: {
            chrome: { version: '77.0.3865.40' },
            ie: { version: "11.0", arch: "ia32", baseURL: "https://selenium-release.storage.googleapis.com" },
        }
    },
    seleniumArgs: {
        drivers: {
            chrome: { version: '77.0.3865.40' },
            ie: { version: "11.0", arch: "ia32", baseURL: "https://selenium-release.storage.googleapis.com" },
        }
    },
```

**Comment by tugend** [comment]
And of course, everything works easily enough if I just target Chrome instead. =p

**Comment by mgrybyk** [comment]
Chrome, firefox, safari works easily, iedriver and edge it's a pain.
Anyway your config still looks wrong. You may remove baseurl and have to specify proper version of ie driver, it should be 3.141 something

**Comment by tugend** [comment]
I appriciate the effort. Something like this? I still get the same error. Just seems it can't find the driver by name somehow.

```
    capabilities: [{ browserName: 'internet explorer'}],
    services: ['selenium-standalone'],
    seleniumLogs: 'logs',
    seleniumInstallArgs: {
        drivers: { ie: { arch: "ia32", version: "3.141" } }
    },
    seleniumArgs: { drivers: { ie: {arch: "ia32", version: "3.141" }}},
```

**Comment by tugend** [comment]
Aha! No! That worked.
Now I get another error, which might be easier to figure out. I'll report in a while. #happyface

```
Error: Could not download https://selenium-release.storage.googleapis.com/3/IEDriverServer_Win32_3.141.zip
```

**Comment by tugend** [comment]
Nope. If I look up the version and change it to newest (I think), I get the same old error of .


``` 
services: ['selenium-standalone'],
    seleniumLogs: 'logs',
    seleniumInstallArgs: {
        drivers: { ie: { arch: "ia32", version: "3.9.0" } }
    },
    seleniumArgs: { drivers: { ie: {arch: "ia32", version: "3.9.0" }}},
```

`Failed launching test session: TypeError: Cannot read property 'capabilities' of null`

**Comment by tugend** [comment]
I kept trying. Other versions, like '3.141.0' does not work either.

**Comment by tugend** [comment]
Yes! It's working for both edge and ie now.
The trick was to remove the default settings for path! By default when installing the path is set to '/' which apparently breaks everything. The comment kinda hints at it, but hadn't spotted that particular bug. Sigh. Only took about 8 hours og guesswork to figure out. Guess I'm just that tired. 

Please consider adding an explicit example, clarifying documentation or an installer option. 
Anyhow, wdio looks really promising, so I'm just really happy it works now. Thanks.

```
// Override default path ('/wd/hub') for chromedriver service.
// path: '/',
capabilities: [{ browserName: 'internet explorer' }],
services: ['selenium-standalone'],
// everything else pure vanilla config
```

**Comment by tugend** [comment]
I'd also like to point out, that the following does not seem to be required.

```
    // seleniumLogs: 'logs',
    // seleniumInstallArgs: {
    //     drivers: { ie: {
    //         // check for more recent versions of internet explorer driver here:
    //         // https://selenium-release.storage.googleapis.com/index.html
    //         version: '3.9.0',
    //         arch: process.arch,
    //         // baseURL: 'https://selenium-release.storage.googleapis.com'
    //       } }
    // },
    // seleniumArgs: { drivers: { ie: {
    //     // check for more recent versions of internet explorer driver here:
    //     // https://selenium-release.storage.googleapis.com/index.html
    //     version: '3.9.0',
    //     arch: process.arch,
    //     // baseURL: 'https://selenium-release.storage.googleapis.com'
    //   }}},
```

**Comment by baruchvlz** [comment]
> Please consider adding an explicit example, clarifying documentation or an installer option.
Anyhow, wdio looks really promising, so I'm just really happy it works now. Thanks.

PRs are always welcome.

**Comment by tugend** [comment]
There you go.

https://github.com/webdriverio/webdriverio/pull/4689
