### ISSUE TITLE
Unscoped API, just one huge interface

### ISSUE THREAD

**Issue by masi** [webdriverio/webdriverio#469]
WebdriverIO is great and I am happy to have stumbled upon it. It has many nifty features, but IMHO the flat API is not on the plus side.

Broadly speaking WebdriverIO offers "raw" JsonWireProtocol, an easy to use API built around the protocol and a "special interest" API for Appium.

How about breaking this up into these 3 parts? Not in 2.x, but in a futue 3.x release of course. I suggest to move all of the protocol API and the Appium API into a separate interface:

var webdriverio = require('webdriverio');

webdriverio.protocol.cookie()
webdriverio.appium.rotate()

Of ocurse all methods of protocol and appium will chain back to the client object. 

webdriverio.protocol.cookie('get').protocol.submit('id')

One of my issued is that the "raw" protcol is inconsitent. For most but not all JsonWireProtocol commands you don't have to set the HTTP method as GET/POST is derived implicetly by the presence of an id argument.

And as there are already helpers like setCookie() you don't need to have cookie() on its own to enlarge WebdriverIO's main API.

Cheers, no offence meant, thank you for all the great work,
Masi

**Comment by EvanHahn** [comment]
Personally, I like the flatter API. Good to discuss this, though.

**Comment by christian-bromann** [comment]
@masi thanks for sharing your idea with us. I will let this open for discussion. Though I like a flatter API as well.

**Comment by christian-bromann** [comment]
@masi again thanks for proposing your idea. I think it is better to go with a flatten API, so people won't have to think about which category the command belongs to use it. I think it complicates things more.
