### ISSUE TITLE
browser.getLogs did not map to a valid resource 

### ISSUE THREAD

**Issue by menahemso** [webdriverio/webdriverio#4691]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:**5.15.2
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:**  sync
 - **Platform name and version:** Windows 10

**Describe the bug**
getLogs sends a POST with the format '/wd/hub/session/sessionID/se/log',
while the correct URL (according appium's API) is : '/wd/hub/session/sessionID/log

**To Reproduce**
remove '/se'

> Please use the correct markdown

**Comment by mgrybyk** [comment]
Please upgrade to the latest versions of chromedriver and chrome browser
