### ISSUE TITLE
Using browser.react$ return "Method is not implemented"

### ISSUE THREAD

**Issue by cjmme** [webdriverio/webdriverio#4693]
Environment:
 - WebdriverIO version: 5.15.1
 - Mode: WDIO Testrunner
 - If WDIO Testrunner, running sync/async: running sync,
 - Node.js version: 8.16.0
 - NPM version: 6.11.1
 - Platform name and version: Android emulator on Win10, android version 8.1.
 - Appium version: 1.13.0
 - Additional wdio packages used :
```
        "@wdio/cli": "^5.15.0",
        "@wdio/local-runner": "^5.15.1",
        "@wdio/mocha-framework": "^5.15.1",
        "@wdio/reporter": "^5.14.5",
        "@wdio/selenium-standalone-service": "^5.15.0",
        "@wdio/spec-reporter": "^5.15.1",
        "@wdio/sync": "^5.15.1",
```

When I try to run the `browser.react$('MyComponent')`, it gives 

![image](https://user-images.githubusercontent.com/20895790/67654330-23066180-f988-11e9-9ad2-fc866e763075.png)

I found it go into the `react$` function, but throw exception when it run the highlight line.
```
 async function react$(selector, props = {}, state = {}) {
  await this.executeScript(resqScript.toString(), []);   // <<<-------------
  await this.execute(_resq.waitToLoadReact);
  const res = await this.execute(_resq.react$, selector, props, state);
  return _getElementObject.getElement.call(this, selector, res, true);
}
```

script comes from `const resqScript = _fs.default.readFileSync(require.resolve('resq'));`
the `resq` version is 1.6.0

After start the session, the config is: 

```
value":{
"platform":"LINUX",
"webStorageEnabled":false,
"takesScreenshot":true,
"javascriptEnabled":true,
"databaseEnabled":false,
"networkConnectionEnabled":true,
"locationContextEnabled":false,
"warnings":{

},
"desired":{
"platformName":"Android",
"deviceName":"Pixel28",
"orientation":"PORTRAIT",
"app":"./apps/app-debug.apk",
"noReset":true,
"avd":"Pixel28",
"chromedriverExecutableDir":"./config/chromedriver"
},
"platformName":"Android",
"deviceName":"emulator-5556",
"orientation":"PORTRAIT",
"app":"./apps/app-debug.apk",
"noReset":true,
"avd":"Pixel28",
"chromedriverExecutableDir":"./config/chromedriver",
"deviceUDID":"emulator-5556",
"platformVersion":"9",
"deviceScreenSize":"1080x1920",
"deviceModel":"Android SDK built for x86_64",
"deviceManufacturer":"Google",
"appPackage":"com.reactnativeclient",
"appWaitPackage":"com.reactnativeclient",
"appActivity":"com.reactnativeclient.MainActivity",
"appWaitActivity":"com.reactnativeclient.MainActivity"
}
```

Anyone have any idea? please help, thanks!

**Comment by baruchvlz** [comment]
That's interesting, I've been working on a project using stand-alone WDIO 5.15.1 with RESQ 1.6.1 and it works fine.

Could you update your packages and try again?

**Comment by cjmme** [comment]
Hi @baruchvlz , thank you for your reply, I tried 1.6.1 also, no luckly..
here is the generated package-lock.json file. (it not support to upload a json file, I change the type to txt).
[package-lock.txt](https://github.com/webdriverio/webdriverio/files/3777511/package-lock.txt)

**Comment by baruchvlz** [comment]
I wonder if this is an issue when trying to execute the script on Appium. This is beyond my knowledge.

cc/ @mgrybyk @christian-bromann

**Comment by cjmme** [comment]
here is the appium log.
https://gist.github.com/cjmme/68a5e7ac3edfb4e52d241580d8cdfba6

**Comment by cjmme** [comment]
@baruchvlz  looked from Appium side, Appium is not supported react$() in react native app. their is an open issue there. thank you! we can close this. : )
https://github.com/appium/appium/issues/12600
