### ISSUE TITLE
this.skip() in async tests causes "Cannot read property 'split' of undefined"

### ISSUE THREAD

**Issue by colinbendell** [webdriverio/webdriverio#4697]
Prior to 5.15.1, calls to `this.skip()` in an async mocha test would properly pass through as a skipped test. However, now with the asyncTest refactoring to use async/await, all calls to `this.skip()` result in:
> Cannot read property 'split' of undefined

This is because `this.skip()` calls `throw new Pending('sync skip')`. This used to fall out of executeAsync() by being wrapped in a Promise.reject(). How, it is caught and rethrown after prettying the `e.stack`. However, `e.stack` doesn't exist and thus causes a new error.

**Comment by christian-bromann** [comment]
Let's continue convo in #4698
