### ISSUE TITLE
Unable to drag and drop using Google Chrome and xvfb

### ISSUE THREAD

**Issue by Robinfr** [webdriverio/webdriverio#470]
As the title mentions, using webdriverio, it seems I'm unable to drag and drop in Google Chrome using xvfb. Clicking however, works fine..

Any idea on what could be the issue?

**Comment by jameseisenhauer** [comment]
screen resolution maybe?

**Comment by Robinfr** [comment]
No it makes a screen shot when it doesn't work and you can clearly see that simply nothing happened. Does no one else have this problem?

James Eisenhauer <notifications@github.com>schreef:

screen resolution maybe?

---

**Comment by Robinfr** [comment]
No, I've figured it out. It's actually because on my version I've fixed this (https://github.com/webdriverio/webdriverio/pull/466). But it's ofcourse not in NPM yet..
