### ISSUE TITLE
Defining `specs` within a capability does not override `specs` declared at config level.

### ISSUE THREAD

**Issue by kevingraber** [webdriverio/webdriverio#4703]
**Environment:**
 - **WebdriverIO version:** 5.15.6
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 8.11.0
 - **NPM version:** 5.6.0
 - **Browser name and version:** Chrome 78
 - **Platform name and version:** Ubuntu 19.04

**Config of WebdriverIO**
```
specs: ['./test/specs/spec_one.js'],
capabilities: [{
    specs: ['./test/specs/spec_two.js'],
    browserName: 'chrome'
}],
```

**Describe the bug**
Defining the `specs` property within a capability does not override `specs` defined at config level for that capability.

**To Reproduce**
Define a spec or specs at the config level, and then define a different spec or specs at the capability level. Run tests.

**Expected behavior**
As outlined in the `capabilities` section of the [Testrunner Config](https://webdriver.io/docs/configurationfile.html) documentation:

> Within your `capabilities`, you can overwrite the `spec` and `exclude` options in order to group specific specs to a specific capability.

I would expect to be able to define capability level `specs` that override general config level `specs`.  Instead of running just `spec_two.js` in the above example, both specs are run. 

**Additional context**
I was able to reproduce this by modifying the `webdriverIO-with-mochaBDD` boilerplate example. If this is indeed an issue I believe I have a PR to fix it.

**Comment by mgrybyk** [comment]
let's discuss  it in the PR
