### ISSUE TITLE
I would like to be responsible for the Korean translation of webdriverio.

### ISSUE THREAD

**Issue by dogemad** [webdriverio/webdriverio#4705]
**Pre-check**
- [ * ] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [ ] Missing documentation
- [ * ] Other

**Description of the improvement / report**

I'm a webdriverio user and I'm translating a document for personal use. But I hope the web driver community is in Korea. How about creating an official Hangul document project in one of these ways? The translated document can be found at the following link: [getting started/ko](https://dogemad.github.io/docs/wdio/v5/ko/guide/introduction/gettingstarted/)

**Comment by baruchvlz** [comment]
@christian-bromann Would have to add the language on Crowdin for this.

**Comment by christian-bromann** [comment]
@dogemad we are using Crowdin as translation tool. It would be amazing if you could help us translating the docs into this language. Just go to this link: https://crowdin.com/project/webdriverio/ko#. Thanks!
