### ISSUE TITLE
remove compatibility functions from testFrameworkFnWrapper

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4711]
**Is your feature request related to a problem? Please describe.**
let's remove all compatibility stuff from `testFrameworkFnWrapper` function.

**Describe the solution you'd like**
I'd like signature to be consistent for every framework, before/after test/step:

1st arg: test (for cucumber it's an object containing uri, feature, step, ...)
2nd arg: test context
3rd arg: webdriverio object containing result, duration and other fields (we may move title, fullTitle and some other common fields here as well)

**Describe alternatives you've considered**
- consistent signature for hooks
- remove complex logic introduced to avoid breaking changes

**Additional context**

**Comment by christian-bromann** [comment]
Let's continue conversation in #4937
