### ISSUE TITLE
Replace args with options object in some methods

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4715]
**Is your feature request related to a problem? Please describe.**
it's not convenient to have `browser.waitUntil(() => $(''foo).isExisting(), null, null, 1000)`

**Describe the solution you'd like**
I'd like to use options instead, ex:
`browser.waitUntil(() => $(''foo).isExisting(), { interval: 1000 })`

**Describe alternatives you've considered**

**Additional context**

affected `browser` methods:
- browser.addCommand (shall we move `attachToSession` to options?)
- newWindow
- react$
- react$$
- waitUntil

affected `element` methods:
- dragAndDrop
- moveTo
- react$
- react$$
- waitForClickable
- waitForDisplayed
- waitForEnabled
- waitForExist
- waitUntil

**Comment by baruchvlz** [comment]
I think `custom$/$$` commands would be affected as well once #4603 is merged.

**Comment by christian-bromann** [comment]
Fixed by #4928

> I think `custom$/$$` commands would be affected as well once #4603 is merged.

@baruchvlz I didn't see a reason to change the interface there as the parameters are not options to the command but actual required parameters.
