### ISSUE TITLE
Is it possible run tests with devtools in browserstack?

### ISSUE THREAD

**Issue by ilyubin** [webdriverio/webdriverio#4716]
I'll try to run tests with `devtools`. 
When I run locally it works well. 
```
  services: ['selenium-standalone', 'devtools'],
```
But when I've run tests in BrowserStack
```
services: ['browserstack', 'devtools'],
```
I've got error:
```
[0-0] (node:15558) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:1630
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
(node:15558) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15558) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

*Question:* is it possible to run tests with `devtools` service in BrowserStack or another remote hub? How?

**Environment (please complete the following information):**
 - **WebdriverIO version:**
```
    "@wdio/allure-reporter": "^5.6.3",
    "@wdio/browserstack-service": "^5.7.2",
    "@wdio/cli": "^5.6.3",
    "@wdio/concise-reporter": "^5.7.8",
    "@wdio/devtools-service": "^5.13.2",
    "@wdio/dot-reporter": "^5.6.0",
    "@wdio/local-runner": "^5.6.3",
    "@wdio/mocha-framework": "^5.6.3",
    "@wdio/spec-reporter": "^5.6.0",
    "@wdio/sync": "^5.6.3",
```

 - **Node.js version:** v10.15.0
 - **NPM version:** 6.11.3
 - **Browser name and version:** 
```
      os: 'Windows',
      os_version: '10',
      resolution: '1440x900',
      browserName: 'chrome',
      browserVersion: '73.0',
```

**Comment by christian-bromann** [comment]
> s it possible to run tests with `devtools` service in BrowserStack or another remote hub? How?

No. This currently only works locally. I haven't heart any cloud vendor supporting this yet. I just know that it is on the roadmap at Sauce Labs. Let me know if you have any further questions.

**Comment by ilyubin** [comment]
Ok, maybe we'll try locally run. Please, help. How to create an image to run tests with
```  services: ['selenium-standalone', 'devtools'],```
?
What we should install?

**Comment by ilyubin** [comment]
@christian-bromann help

**Comment by christian-bromann** [comment]
@ilyubin sorry but I never did set it up with Docker. It should be possible though.
