### ISSUE TITLE
Pass more config properties from main process to workers

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4721]
**Is your feature request related to a problem? Please describe.**
Currently we can only pass capabilities to workers, I'd like to pass also other properties like:
- `path`, `hostname`, `port` and other connection information so that services can control it
- test framework config (ex cucumberOpts) to be able to pass tags/grep and other important data from main process to capabilities
- be able to easily extend data that can be passed to worker without introducing a breaking change

Maybe we should have only one object in capabilities instead of many properties like we have now? Example instead of having maxInstances, driverLogs, etc directly in capabilities it can be `wdio` object in capabilities with everything we need. (it would be a breaking change!)
It might be easier to understand if a property is an actual capability or something to control webdriverio.

**Describe the solution you'd like**
instead of passing just capabilities pass an object containing capabilities, host, port, etc so that we can easily extend it later on

**Describe alternatives you've considered**
any other alternative to be able to configure each capability instance

**Additional context**
added breaking change but I'm not sure if it's gonna be actually breaking or not

**Comment by christian-bromann** [comment]
Done in #4926
