### ISSUE TITLE
Access sharedStore in onPrepare and onComplete hooks

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4723]
**Is your feature request related to a problem? Please describe.**
Make shared store services accessible in `onPrepare` and `onComplete` hooks (and other hooks where `browser` object is not available like before/after Session)

**Describe the solution you'd like**
add sharedStore directly to config?
```
onPrepare: [function (config, capabilities) {
    config.sharedStore.get('foo')
}],
```
UPD: it won't work currently :(

**Describe alternatives you've considered**
any suggestions are welcomed

**Additional context**
shared store is accessible from browser object `browser.sharedStore`. However `browser` is not available in some hooks like onPrepare, onComplete and others when session is not available.

**Comment by mgrybyk** [comment]
ah, there is another issue here. User defined hooks run same time (or before) service hooks, as a result there is currently no way to use service at this point.

**Comment by erwinheitzman** [comment]
I would add it to the `browser` object instead or even better, import it separately as it's not part of the config nor the browser.

**Comment by mgrybyk** [comment]
It is in browser object but the browser object is not always available. 

We can import it in launcher in wdio cli package, but the shared store won't be a service anymore. I don't mind but not sure it's acceptable

**Comment by tomasfly** [comment]
Hi,

I installed shared-store-service:

npm i @wdio/shared-store-service

I have added the following to my wdio.conf.js:

services: ['appium','shared-store'],

But when I try call it from browser:

browser.sharedStore().set('key','value');

I get an error:

browser.sharedStore is not a function

Am I missing any step?

**Comment by mgrybyk** [comment]
@tomasfly absolutely. sharedStore is not a function, it's an an object! Thanks for finding typo in docs.

**Comment by brightsider** [comment]
Trying to access in onComplete and get error:
Error in onCompleteHook: ReferenceError: browser is not defined

**Comment by christian-bromann** [comment]
I suggest to have the shared service expose its `getValue` and `setValue` function which both don't need any `browser` context. Then do it this way:

```ts
import { addValue } from '@wdio/shared-store-service'

// ...
onPrepare: [function (config, capabilities) {
    addValue('foo', 'bar')
}],
```

Any contributions would be appreciated. Please let us know if anything is unclear.
