### ISSUE TITLE
Getting error: @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'capabilities' of null

### ISSUE THREAD

**Issue by droozd15** [webdriverio/webdriverio#4728]
I am trying to run webdriverio tests 

Config of WebdriverIO:

```
exports.config = {

    runner: 'local',

    path: '/',
    port: 9515,
    specs: [
        './test/specs/**/*.js'
    ],

    exclude: [
        // 'path/to/excluded/files'
    ],
    maxInstances: 10,

    capabilities: [{

        maxInstances: 5,
        //
        browserName: 'chrome',
    }],

    logLevel: 'info',

    bail: 0,
    baseUrl: 'http://localhost',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    services: ['chromedriver'],
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },

}
```
```

Test with Chromedriver and local runner is not running.

[0-0] 2019-11-04T18:48:49.589Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'capabilities' of null
    at Runner.run (/home/zanovich/webdriverio-test/node_modules/@wdio/runner/build/index.js:69:74)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[0-0] FAILED in chrome - /test/specs/basic.js

```

This should work as described in the manual

https://webdriver.io/docs/gettingstarted.html

**Comment by mgrybyk** [comment]
Thank you for submitting 

Can you share more info please:

- deps from package json
- enable debug logs and attach here if there is something chromedriver or service specific 

This is some configuration issue, I'd like to know how to reproduce it and print better message to help dealing with it

**Comment by mgrybyk** [comment]
ok, I was able to reproduce it.

You've missed to install `chromedriver`.

**Comment by droozd15** [comment]
I really missed the chromedriver installation. I fixed it but the test still does not start.

nothing is running on port 9515.

I will not mind what I'm doing wrong

**Comment by mgrybyk** [comment]
@droozd15 let's investigate further! I'm really interested to find our the root cause. 

Can you attach more logs please? It would help everyone else who have faced the same problem 

If you've managed to make it work please let me know how

**Comment by mgrybyk** [comment]
@droozd15 improved error message a bit, now it looks like this
![image](https://user-images.githubusercontent.com/25589559/68156814-cc32f600-ff4c-11e9-9ca6-7fa37bf74f9e.png)

**Comment by shivakadhuluri** [comment]
Unable to connect to "127.0.0.1:4444", make sure browser driver is running on that address.
If you use services like chromedriver see initialiseServices logs above or in wdio.log file.

Can you please help out on this?
