### ISSUE TITLE
Mention isSynchronised in Custom Reporter doc

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4731]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [x] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Description of the improvement / report**
There is no information about `isSynchronised` in https://webdriver.io/docs/customreporter.html

It would be good to mention it or refer to https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-reporter/README.md#synchronization

**Comment by christian-bromann** [comment]
See #4814
