### ISSUE TITLE
Add types for click options

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4735]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.15.6

**Describe the bug**
types for `click` options are missing and have to be added based on https://github.com/webdriverio/webdriverio/blob/902ea1fe6711e742f53e9ac7e62bcd2a6f7c518f/packages/webdriverio/src/commands/element/click.js#L66

mention: @erwinheitzman

**Comment by BorisOsipov** [comment]
@mgrybyk I suppose PR checklist should be extended with new item about typings changes :)

**Comment by christian-bromann** [comment]
@BorisOsipov how about #4813?

**Comment by christian-bromann** [comment]
See #5005
