### ISSUE TITLE
Test fails with v5.16.0 and junit reporter with outputFileFormat parameter

### ISSUE THREAD

**Issue by pako88** [webdriverio/webdriverio#4738]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.16.0
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.17.0
 - **NPM version:** 6.11.3
 - **Browser name and version:** doesn't matter
 - **Platform name and version:** doesn't matter
 - **Additional wdio packages used (if applicable):** doesn't matter

**Config of WebdriverIO**
```
...
reporters: [
        'spec',
        ['junit', {
            outputDir: './junit-results',
            outputFileFormat: function (options) {
                return `results-${options.cid}.${options.capabilities.browserName}.xml`
            },
        }]
    ],
...
```
**Describe the bug**
Tests will not run with outputFileFormat set. when i comment out this line, test runs fine.
This bug occurs since v5.16.0
**To Reproduce**

see above

**Expected behavior**
test runs
**Log**
https://gist.github.com/pako88/92e7c774befe9f1c675e163793ce1153

**Additional context**
-

**Comment by mgrybyk** [comment]
thanks for raising it, let's proceed convo in the PR
