### ISSUE TITLE
Chaining getText seems a bit nondeterministic

### ISSUE THREAD

**Issue by farmdawgnation** [webdriverio/webdriverio#474]
I can't pinpoint exactly why, but it looks like chaining `getText` calls may not work consistently. My guess is that in the guts of `getText` there's somewhere that needs a closure that doesn't have one and as a result weird things are happening.

So, I've got code structured like so:

```coffee
createdName = "ABC"
createdDescription = "DEF
```

Then some tests and other code that create my things... Then...

```coffee
client
  .getText('#name', (err, name) ->
    assert.equal(name, createdName)
  )
  .getText('#description > .label', (err, description) ->
    assert.equal(description, createdDescription)
  )
  .call(done)
```

Periodically, these assertions fail with this error:

```
Uncaught AssertionError: expected 'ABCDEF' to equal 'ABC'
```

Am I doing something wrong in how I've formatted my test or is there a bug in how `getText` is behaving?

**Comment by christian-bromann** [comment]
hi @farmdawgnation,
mhm .. that's strange. I've never encountered such a problem. `getText` calls queries the given selector and calls `elementIdText` on that. The results should be always the same unless there is a problem in the app you are testing.
Could you paste in some Selenium logs? Maybe they give a clue whats going wrong here.

Cheers

**Comment by farmdawgnation** [comment]
I'll paste in the logs the next time I get some.

**Comment by farmdawgnation** [comment]
Haven't been able to reproduce it this afternoon. :/

**Comment by farmdawgnation** [comment]
Okay, got it to happen again

```
14:41:03.170 INFO - Executing: [find elements: By.id: name])
14:41:03.180 INFO - Done: [find elements: By.id: name]
14:41:03.184 INFO - Executing: [get text: 14 [[PhantomJSDriver: phantomjs on OS X 10.10 (50613b00-d255-11e4-a294-d1e699d6c723)] -> id: name]])
14:41:03.196 INFO - Done: [get text: 14 [[PhantomJSDriver: phantomjs on OS X 10.10 (50613b00-d255-11e4-a294-d1e699d6c723)] -> id: name]]
```

And I had some code in place to log the protocol response from Phantom when this test fails:

```
{ elements:
   { state: 'success',
     sessionId: '2a7867d4-61e7-4272-b908-edd05b0ead01',
     hCode: 853837547,
     value: [ [Object] ],
     class: 'org.openqa.selenium.remote.Response',
     status: 0 },
  elementIdText:
   [ { state: 'success',
       sessionId: '2a7867d4-61e7-4272-b908-edd05b0ead01',
       hCode: 1931806089,
       value: 'ABCDEF',
       class: 'org.openqa.selenium.remote.Response',
       status: 0 } ] }
```

Does this mean the issue is actually in the Phantom webdriver itself? o.O

**Comment by christian-bromann** [comment]
@farmdawgnation everything looks good. The element `#name´ contains `ABCDEF`. Note that nested elements will be part of that response, so:

```html
<div id="name">
    ABC
    <span>DEF</span>
</div>
```

is equal to:

```html
<div id="name">
    ABCDEF
</div>
```

**Comment by farmdawgnation** [comment]
Yeah. That's not the structure though. These two nodes are on entirely disparate parts of the page. :/

**Comment by christian-bromann** [comment]
Could you try to use `getHTML` instead?

**Comment by farmdawgnation** [comment]
Sure, this is only failing intermittently so I'll have to wait until it fails again to see what we get.

**Comment by christian-bromann** [comment]
@farmdawgnation is still problem still valid?
Will close this issue. Feel free to reopen it at any time.

**Comment by Zougi** [comment]
I get the same getText behavior with chromedriver

09:27:18.585 INFO - Executing: [get text: 3 [[ChromeDriver: chrome on MAC (5ad082c012996aeb20231c7d0b90315b)] -> css selector: table.deg5 tr:nth-child(2) b]])
09:27:18.605 INFO - Done: [get text: 3 [[ChromeDriver: chrome on MAC (5ad082c012996aeb20231c7d0b90315b)] -> css selector: table.deg5 tr:nth-child(2) b]]

it returns systematicaly

{ elements: 
   { status: 0,
     sessionId: '3029cb5c-816b-46f7-8810-6b518576e181',
     state: 'success',
     value: [ [Object] ],
     class: 'org.openqa.selenium.remote.Response',
     hCode: 576939464 },
  elementIdText: 
   [ { status: 0,
       sessionId: '3029cb5c-816b-46f7-8810-6b518576e181',
       state: 'success',
       value: 'lundi 06 juillet 2015 à 12h00',
       class: 'org.openqa.selenium.remote.Response',
       hCode: 1251445609 } ] }

  "dependencies": {
    ...
    "webdrivercss": "1.1.3",
    "webdriverio": "2.4.5"
  },

**Comment by christian-bromann** [comment]
@Zougi are you saying that `text.elementIdText[0].value` returns the right value whereas the second parameter of the callback formats the result in a way that it is not the same?

Did you try it with `v3`?
