### ISSUE TITLE
Run Concurrent instances of test runner for different servers?

### ISSUE THREAD

**Issue by olioli2345** [webdriverio/webdriverio#4741]
- **WebdriverIO version:** Latest
 - **Mode:** WDIO Test Runner
 - **If WDIO Testrunner, running sync/async:** Sync
 - **Node.js version:** Latest
 - **NPM version:** Latest
 - **Browser name and version:** Chrome 77.0
 - **Platform name and version:** Win10
 - **Additional wdio packages used (if applicable):** selenium-standalone, mocha, allure-reporter

Situation,

We have 5 servers all running the same web app, however currently we are only testing one server at a time, and each test run takes 1hr20mins. We want to be able to run all tests on all servers concurrently from our local machine.

I have tried to run them at the same before, however I get a Worker Error: connect ECONNEFUSED 127.0.0.1 and both the original runner and the new instance fail and stop working altogether.

The test package is made up of 15 suites with a total of 170 test cases. The tests have to be run in order because of the way the data is inputed and then validated.

Is this possible?

**Comment by christian-bromann** [comment]
> Is this possible?

The current local runner can only spawn workers on the machine where you run the `wdio` command. We planned to build a lambda runner that would spin up workers in a cloud (as lambda functions) but this is still super experimental.

**Comment by olioli2345** [comment]
> > Is this possible?
> 
> The current local runner can only spawn workers on the machine where you run the `wdio` command. We planned to build a lambda runner that would spin up workers in a cloud (as lambda functions) but this is still super experimental.

Sorry that's not really what I menat. All the testing is done on the machine in our office, it spawns the workers one after the other which test the 5 servers synchronously. I want to essentially spawn 5 workers at the same time on the office PC which tests all 5 servers at the same time.

**Comment by christian-bromann** [comment]
You can just define 5 capabilities that all run the same tests but every capability opens the website from a different server. Just define some custom options in your capabilities as follows:

```js
// wdio.conf.js
capabilities: [{
  browserName: 'chrome'
  baseServer: 'https://foobar1.com'
  // ...
}, {
  browserName: 'chrome'
  baseServer: 'https://foobar2.com'
  // ...
}, {
  // ...
}]
// ...
```

and then have a test like this:

```js
it('should open the app', () => {
  browser.url(browser.options.requestedCapabilities.baseServer)
  // ...
```

I will close this issue but happy to help with further questions.

**Comment by olioli2345** [comment]
> You can just define 5 capabilities that all run the same tests but every capability opens the website from a different server. Just define some custom options in your capabilities as follows:
> 
> ```js
> // wdio.conf.js
> capabilities: [{
>   browserName: 'chrome'
>   baseServer: 'https://foobar1.com'
>   // ...
> }, {
>   browserName: 'chrome'
>   baseServer: 'https://foobar2.com'
>   // ...
> }, {
>   // ...
> }]
> // ...
> ```
> 
> and then have a test like this:
> 
> ```js
> it('should open the app', () => {
>   browser.url(browser.options.requestedCapabilities.baseServer)
>   // ...
> ```
> 
> I will close this issue but happy to help with further questions.

I've changed my wdio.conf.js to now include:

    capabilities: [{
        maxInstances: 1, 
        browserName: 'chrome',
        "goog:chromeOptions": {
            args: ['--window-size=1920,1080']
        },
        baseUrl: 'http://oneserver.com'
}, {
        maxInstances: 1,
        browserName: 'chrome',
        "goog:chromeOptions": {
            args: ['--window-size=1920,1080']
        },
        baseUrl: 'https://twoserver.com'
}], 

and whilst it is now spawning two instances of chrome, I can't see to get the base url of each instance. I've tried browser.options.requestedCapabilities.baseUrl but that's not working.

**Comment by christian-bromann** [comment]
Your capabilities look ok. Make sure that whatever Selenium Grid , Browser driver or cloud provider allows you to run multiple sessions in parallel. Remove the “maxInstances” option if set. Also you need to explain what exactly is not working otherwise it is impossible to provide support.

**Comment by olioli2345** [comment]
> Your capabilities look ok. Make sure that whatever Selenium Grid , Browser driver or cloud provider allows you to run multiple sessions in parallel. Remove the “maxInstances” option if set. Also you need to explain what exactly is not working otherwise it is impossible to provide support.

I'm using wdio-testrunner

When I add the two capabilities mentioned above, two chrome instances are then spawned. The spec that is then ran tries to visit the baseUrls in it's respective capability.

For instance, worker 1 is spawned with baseUrl http://oneserver.com, I would expect it to visit http://oneserver.com, but when doing browser.url(browser.options.desiredCapabilities.baseUrl), the worker doesn't visit the url. I've console.log(browser.options.desiredCapabilities.baseUrl) and the output is undefined.

I've commented out maxInstances from the exports.config{} object, however it's nessecary to keep the maxInstances in each of the capabilities as the test specs **must run synchronously**.

**Comment by christian-bromann** [comment]
> I've console.log(browser.options.desiredCapabilities.baseUrl) and the output is undefined.

Can you inspect the `browser.options` object to see where the property is?

> as the test specs **must run synchronously**.

I think this is impossible to guarantee.

You can also have a look in the multiremote feature where you can control multiple instances in one test.

**Comment by olioli2345** [comment]
`[0-0] { protocol: 'http',
   hostname: '127.0.0.1',
   port: 4444,
   path: '/wd/hub',
   capabilities:
    { browserName: 'chrome',
      'goog:chromeOptions': { args: [Array] } },
   logLevel: 'debug',
   connectionRetryTimeout: 90000,
   connectionRetryCount: 3,
   requestedCapabilities:
    { w3cCaps: { alwaysMatch: [Object], firstMatch: [Array] },
      jsonwpCaps: { browserName: 'chrome', 'goog:chromeOptions': [Object] } },
   specs: [ 'C:/B***/W***/test/specs/*.js' ],
   exclude: [],
   suites: {},
   baseUrl: 'http://localhost',
   bail: 0,
   waitforInterval: 500,
   waitforTimeout: 10000,
   framework: 'mocha',
   reporters: [ [ 'json', [Object] ], [ 'allure', [Object] ] ],
   services: [ 'selenium-standalone' ],
   execArgv: [],
   maxInstances: 100,
   maxInstancesPerCapability: 100,
   outputDir: 'allure-results/dev/07.11.2019/',
   filesToWatch: [],
   onPrepare: [Function: NOOP],
   before: [],
   beforeSession: [],
   beforeSuite: [],
   beforeHook: [],
   beforeTest: [],
   beforeCommand: [],
   afterCommand: [],
   afterTest: [],
   afterHook: [],
   afterSuite: [],
   afterSession: [],
   after: [],
   onComplete: [Function: NOOP],
   onReload: [],
   beforeFeature: [],
   beforeScenario: [],
   beforeStep: [],
   afterFeature: [],
   afterScenario: [],
   afterStep: [] }
[1-0] { protocol: 'http',
   hostname: '127.0.0.1',
   port: 4444,
   path: '/wd/hub',
   capabilities:
    { browserName: 'chrome',
      'goog:chromeOptions': { args: [Array] } },
   logLevel: 'debug',
   connectionRetryTimeout: 90000,
   connectionRetryCount: 3,
   requestedCapabilities:
    { w3cCaps: { alwaysMatch: [Object], firstMatch: [Array] },
      jsonwpCaps: { browserName: 'chrome', 'goog:chromeOptions': [Object] } },
   specs: [ 'C:/B***/W***/test/specs/*.js' ],
   exclude: [],
   suites: {},
   baseUrl: 'http://localhost',
   bail: 0,
   waitforInterval: 500,
   waitforTimeout: 10000,
   framework: 'mocha',
   reporters: [ [ 'json', [Object] ], [ 'allure', [Object] ] ],
   services: [ 'selenium-standalone' ],
   execArgv: [],
   maxInstances: 100,
   maxInstancesPerCapability: 100,
   outputDir: 'allure-results/dev/07.11.2019/',
   filesToWatch: [],
   onPrepare: [Function: NOOP],
   before: [],
   beforeSession: [],
   beforeSuite: [],
   beforeHook: [],
   beforeTest: [],
   beforeCommand: [],
   afterCommand: [],
   afterTest: [],
   afterHook: [],
   afterSuite: [],
   afterSession: [],
   after: [],
   onComplete: [Function: NOOP],
   onReload: [],
   beforeFeature: [],
   beforeScenario: [],
   beforeStep: [],
   afterFeature: [],
   afterScenario: [],
   afterStep: [] }`

It doesn't seem to appear. There is indeed a requestedCapabilities property but console.log of that provides: 

`[0-0] { w3cCaps:
    { alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
      firstMatch: [ {} ] },
   jsonwpCaps:
    { browserName: 'chrome',
      'goog:chromeOptions': { args: [Array] } } }
[1-0] { w3cCaps:
    { alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
      firstMatch: [ {} ] },
   jsonwpCaps:
    { browserName: 'chrome',
      'goog:chromeOptions': { args: [Array] } } }`

**Comment by mgrybyk** [comment]
Hey guys, sorry for jumping in but I think you've missed something.
First of all you can't use `baseUrl` in capabilities, it's gonna be filtered out. Instead use prefixed property `'my:baseUrl'` of whatever.

```
{
        'my:baseUrl': 'https://google.com',
        browserName: 'chrome',
}
```

Then overwrite `baseUrl` in `before` hook
```
baseUrl: 'https://github.com', // overwrite with 'my:baseUrl'
before (capabilities, specs) {
    if (capabilities["my:baseUrl"]) {
        browser.options.baseUrl = capabilities["my:baseUrl"]
    }
},
```

Nothing special have to be done in the test
```
browser.url("")
console.log(browser.getUrl()) // https://google.com' (or https://github.com if `my:baseUrl` was not provided in capabilities)
```

@olioli2345

**Comment by olioli2345** [comment]
> Hey guys, sorry for jumping in but I think you've missed something.
> First of all you can't use `baseUrl` in capabilities, it's gonna be filtered out. Instead use prefixed property `'my:baseUrl'` of whatever.
> 
> ```
> {
>         'my:baseUrl': 'https://google.com',
>         browserName: 'chrome',
> }
> ```
> 
> Then overwrite `baseUrl` in `before` hook
> 
> ```
> baseUrl: 'https://github.com', // overwrite with 'my:baseUrl'
> 
> before (capabilities, specs) {
>     // overwrite `baseUrl` if `"my:baseUrl"` exists in capabilities
>     if (capabilities["my:baseUrl"]) {
>         browser.options.baseUrl = capabilities["my:baseUrl"]
>     }
> },
> ```
> 
> Nothing special have to be done in the test
> 
> ```
> browser.url("")
> console.log(browser.getUrl()) // https://google.com' (or https://github.com if `my:baseUrl` was not provided in capabilities)
> ```
> 
> @olioli2345

That's it!!!! Thank you both very much, this is exactly what I need.

**Comment by mgrybyk** [comment]
You welcome

**Comment by olioli2345** [comment]
> You welcome

Is it possible to set the output directory using the browser capabilities?

As mentioned, I have 5 servers that are now (thanks to you both) testing concurrently. However I'd like for each server to have it's own report - so was wondering if I could set the outputDir depending on the server?

**Comment by mgrybyk** [comment]
Not sure to be honest

**Comment by christian-bromann** [comment]
> so was wondering if I could set the outputDir depending on the server?

I think it can work the same way you changed `baseUrl` you just change the `outputDir` property.
