### ISSUE TITLE
wdio-config feature "start specs with linenumbers" breaks test execution on windows

### ISSUE THREAD

**Issue by schoera** [webdriverio/webdriverio#4748]
the problem was introduced with the new feature of specifying line numbers via "--spec" command line option
see commit 9ac2af1bf672a897a685d391a7464f9cbf0ca360

even while using only relative paths on the command line (e.g. "wdio run wdio.conf.js --spec ./tests/e2e/a.spec.js") the method ConfigParser.getFilePaths gets a list of _absolute_ file paths as the first argument "patterns".

since paths on windows start with the device 'index' and a colon (e.g. "C:" / "D:") there is a colon in the path even without giving any line number ...

this leads to the problem, that the pattern/file list will be reduced to a list in which every entry is only the device index (e.g. "['C', 'C', ....]" )
and to the result that no tests can be executed giving a spec

it produces the following output:
> WARN @wdio/config:ConfigParser: pattern C did not match any file     (... for every file in the list)
> Execution of 0 spec files started at ...

IMHO the implementation of function "removeLineNumbers" (and potentially "isCucumberFeatureWithLineNumber") in "wdio-config/src/utils.js" needs some changes

**Comment by mgrybyk** [comment]
@schoera thank you for submitting, raise PR to fix it, will do release once it approved and merged
