### ISSUE TITLE
connectionRetryTimeout has no effect

### ISSUE THREAD

**Issue by Antict** [webdriverio/webdriverio#4749]
**Environment:**
 - **WebdriverIO version:** 5.9.6
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v10.15.3
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome 78
 - **Platform name and version:** MacOS Mojave

**Config of WebdriverIO**
```
exports.config = {
    runner: 'local',
    baseUrl: 'http://localhost',
    path: '/',
    port: 9515,
    maxInstances: 1,
    logLevel: 'debug',
    coloredLogs: true,
    bail: 0,
    waitforTimeout: 20000,
    connectionRetryTimeout: 1,
    connectionRetryCount: 3,
    framework: 'mocha',
    mochaOpts: {
        ui: 'bdd',
        compilers: ['js:babel-register'],
        timeout: 60000
    },
    capabilities: [{
        browserName: 'chrome',
        'goog:chromeOptions': {
            binary: process.env.CHROME_BINARY
        }
    }],
    services: ['chromedriver']
}
```

**Describe the bug**
Setting connectionRetryTimeout has no effect. I have set `connectionRetryTimeout` to 1 millisecond, but still the requests are not aborted, although the answer comes later than 1 millisecond.
In the [request.js](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriver/src/request.js) file of webdriver no timeout is set for a request. 

**To Reproduce**

Setup a project and change the `connectionRetryTimeout` to 1 or a very low value. The test will pass as normal.
Additionally, set a breakpoint at [this](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriver/src/request.js#L104) line in request.js and look into fullRequestOptions. No timeout is set.

**Expected behavior**
If the server does not respond in time `connectionRetryTimeout`, the request should be repeated `connectionRetryCount` times and then the test aborted.

**Log**
[wdio-0-0.log](https://gist.github.com/Antict/9eebb7f1c65a8c2d4381ff403b2446cc)

**Comment by baruchvlz** [comment]
@christian-bromann Maybe this is something we can look at while changing request for got?

**Comment by Antict** [comment]
I came across this behavior because sometimes it seems as if Browserstack does not receive requests. Take a look at [these](https://gist.github.com/Antict/43fea68aae20247fe197edd099339cc8) two log files. In this case, `connectionRetryTimeout` was set to 30s. I execute WebdriverIO in Bitbucket Pipelines and use Browserstack.

First, WebdriverIO sends a request to execute a script with the `pageHeight` function. This request is received and a response is returned (see `browserstack_log.log`).
Then another request is sent to Browserstack (script with the function `virtualScroll`). In the `browserstack_log.log` you can see that it never arrives there. WebdriverIO now simply waits and only when the mocha timeout is reached the next request is sent (delete cookies). The test failed due to mocha timeout.

Has anyone had similar experiences?

**Comment by christian-bromann** [comment]
@Antict looking into the code we indeed killed this functionality without realising it. I created a PR to remove all occurrences in the doc.

I will close this issue as we have identified that the option isn't implemented anymore and removed it in the PR. Happy to discuss the idea of retrying request in a separate feature request.

> Has anyone had similar experiences?

I definitely did but it was mostly connected with problems in the network and not WebdriverIO.

**Comment by Antict** [comment]
@christian-bromann 

> I definitely did but it was mostly connected with problems in the network and not WebdriverIO.
How did you handle this problem? I would like to know if my test failed due to a network problem or if a test case really failed.

**Comment by christian-bromann** [comment]
> How did you handle this problem?

Please reach out to the BS support team to identify if it is an issue with the network or the way the command is handled in their VMs.
