### ISSUE TITLE
moveToObject defaults to (0,0) offset if no offset provided

### ISSUE THREAD

**Issue by ifilatov** [webdriverio/webdriverio#475]
According to documentation (http://webdriver.io/api/action/moveToObject.html): "If an element is provided but no offset, the mouse will be moved to the center of the element"

But with non-mobile driver no-offset call get (0,0) as default offset values - it leads my test to fail, since no popup appears (I have to call .moveToObject(locator,5,5) instead of .moveToObject(locator) to let the tests pass).

**Comment by Robinfr** [comment]
I've already fixed this https://github.com/webdriverio/webdriverio/pull/466 but it's still not pulled..

**Comment by christian-bromann** [comment]
please see #466

**Comment by michahell** [comment]
Still not fixed though.
