### ISSUE TITLE
Select n matching element in mobile 

### ISSUE THREAD

**Issue by lucialuzuriaga** [webdriverio/webdriverio#4757]
I’m looking for a way to select a random or specific matching element for my mobile suites (iOS and Android). 
According to the documentation, there’s a selectByIndex call which does exactly what I need, but it’s not supported for mobile. 
https://webdriver.io/docs/api/element/selectByIndex.html

Is there any workaround or alternative? This is blocking me from making my tests more dynamic and robust, as I am always interacting with the first matching element. 

In case it matters, my dependencies are:

```
  "devDependencies": {
    "@babel/cli": "^7.4.3",
    "@babel/core": "^7.4.3",
    "@babel/preset-env": "^7.4.3",
    "@babel/register": "^7.4.0",
    "@wdio/allure-reporter": "^5.9.3",
    "@wdio/cli": "^5.7.12",
    "@wdio/jasmine-framework": "^5.7.8",
    "@wdio/local-runner": "^5.7.12",
    "@wdio/sync": "^5.7.9"
  },
  "dependencies": {
    "allure-commandline": "^2.9.0",
    "chai": "^4.2.0"
  }
```

Thank you in advance.

**Comment by lucialuzuriaga** [comment]
Apologies, but it's been 10 days and still no replies.

**Comment by christian-bromann** [comment]
> Is there any workaround or alternative?

There probably is but there are no information on how your app looks like and what UI elements you are using. I recommend to check out the Appium Inspector to see how the elements are defined. `selectByIndex` is for web only as we use an xPath on `<option />` elements which don't exist for native apps.

Let me know if you have more questions.
