### ISSUE TITLE
Is it possible to enable ChromeDriver performance logging in desired Capabilities?

### ISSUE THREAD

**Issue by darnold24** [webdriverio/webdriverio#476]
This is what I have so far:

```js
var webdriverio = require('webdriverio');
var options = {
    desiredCapabilities: {
    	loggingPrefs: 'ALL',
        browserName: 'chrome',
        chromeOptions: {
        	perfLoggingPrefs: {
        		enableNetwork: true,
        		enablepage: true
            }
        }
     }    
 };
```
 There is a performance capabilitiy in chromedriver, sample code java is here:
https://sites.google.com/a/chromium.org/chromedriver/logging/performance-log
This is also trying to access performance logging, but we keep getting error, Logging not enabled. Is there any possible solution?

**Comment by christian-bromann** [comment]
mhm .. haven't used that yet. Could you paste in the linke for the sample code?

**Comment by darnold24** [comment]
Sure, that was in javascript. You can see the performance logging capability for chromedriver here:
https://sites.google.com/a/chromium.org/chromedriver/logging/performance-log
Which is written in java, although my code above is written in javascript. My colleague also tried enabling performance logging with java and got same error, logging is not enabled. You can see the chrome option here:
https://sites.google.com/a/chromium.org/chromedriver/capabilities
Its the perfLoggingPrefs object.
It would be very powerful if we could get performance logs from our test runs. We've been running hundreds of tests using your code with cucumber.

**Comment by hy9be** [comment]
+1 on the proposal of @darnold24

**Comment by georgecrawford** [comment]
Try this:

```js
			loggingPrefs: {
				'browser':     'ALL',
				'driver':      'ALL',
				'performance': 'ALL'
			},
			chromeOptions: {
				perfLoggingPrefs: {
					traceCategories: 'blink.console,disabled-by-default-devtools.timeline'
				},
...
```
From https://github.com/cabbiepete/browser-perf/commit/046f65f02db418c17ec2d59c43abcc0de642a60f

**Comment by hy9be** [comment]
@georgecrawford that worked. My inserted a space after ``blink.console`` by mistake.

**Comment by christian-bromann** [comment]
@georgecrawford @darnold24 I created #590 to tackle this. How about I add

```js
            loggingPrefs: {
                'browser':     'ALL',
                'driver':      'ALL',
                'performance': 'ALL'
            },
            chromeOptions: {
                perfLoggingPrefs: {
                    traceCategories: 'v8,blink.console,disabled-by-default-devtools.timeline'
                },
```

to the desired capabilities per default if the is browserName is chrome?

**Comment by christian-bromann** [comment]
Seems that `performance` is somehow deprecated. Performance analysis would be a great plugin for WebdriverIO.

**Comment by intergleam** [comment]
so `performance` logs are not available?

**Comment by christian-bromann** [comment]
This should be possible with latest Chromedriver. Note that this thread is almost 2 years old.

**Comment by christian-bromann** [comment]
@intergleam please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions.

**Comment by d668** [comment]
Hm, `performance` is gone with Chrome 75

**Comment by christian-bromann** [comment]
> Hm, `performance` is gone with Chrome 75

What do you mean by that?

**Comment by d668** [comment]
```
    var options = {
        desiredCapabilities: {
            browserName: 'chrome',
            loggingPrefs: {
                'browser': 'ALL',
                'driver': 'ALL',
                'performance': 'ALL'
            },
            chromeOptions: {
                perfLoggingPrefs: {
                     traceCategories: 'performance'
                 },
                }
            }
        }
    }
```
This cases error now in my existing app after upgrading to chrome 75

**Comment by christian-bromann** [comment]
instead of `chromeOptions` write `'goog:chromeOptions'`

**Comment by d668** [comment]
Doesn't seem to work https://gist.github.com/d668/0b1e65317cda7727a3984caf8796ee06
```
(node:10833) UnhandledPromiseRejectionWarning: Error: Unable to create session from {
  "desiredCapabilities": {
...
```

**Comment by christian-bromann** [comment]
@d668 please update to v5

**Comment by rostrovsky** [comment]
Capabilities that work for me with wdio `v4.13.0` and chromedriver `75` & `76`:
```js
   {
      browserName: 'chrome',
      maxInstances: 1,
      'goog:loggingPrefs': {
        browser: 'ALL',
        performance: 'ALL',
      },
      chromeOptions: {
        useAutomationExtension: false,
        args: ['--disable-extensions', '--start-maximized', '--enable-automation', '--disable-infobars'],
        perfLoggingPrefs: {
          traceCategories: 'browser,devtools.timeline,devtools',
          enableNetwork: true,
        },
      },
    },
```

Apparently what was needed is `goog:loggingPrefs` due to the stricter w3c specs (source: https://stackoverflow.com/a/56536604)

**Comment by christian-bromann** [comment]
@rostrovsky we recommend to upgrade to WebdriverIO v5 and use the [@wdio/devtools-service](https://www.npmjs.com/package/@wdio/devtools-service) to get performance data from page loads. See how it works in action here: https://github.com/christian-bromann/webdriverio-performance-testing
