### ISSUE TITLE
Lazy loading of elements and element chains

### ISSUE THREAD

**Issue by vgrigoruk** [webdriverio/webdriverio#4765]
**Is your feature request related to a problem? Please describe.**

Consider the following simplified example test:

```js
describe('webdriverio', () => {
  it('passes', () => {
    browser.url('https://google.com');
    const form = $('form[role=search]');
    const firstButton = form.$('input[type=submit]');
    console.log(firstButton.getAttribute('value'));
  });
 it('fails', () => {
    const form = $('form[role=search]');
    const firstButton = form.$('input[type=submit]');
    browser.url('https://google.com');
    console.log(firstButton.getAttribute('value'));
  });
});
```

Second test fails, as `form` element need to be on the page at the moment when this code is executed: `const firstButton = form.$('input[type=submit]');`

This was just a simple example showing that `webdriverio` doesn't truly support lazy loading of elements. 
- This enforces certain limitation to the design of your tests / page objects (element definitions only inside methods and getters). 
- Also due to behavior described above, it is not currently possible to implement nicely looking chai expectations that accept `Element`. And that's why `chai-webdriverio` still uses selectors in expectations (like `expect('.foo').to.have.text('bar')`)

**Describe the solution you'd like**

- All calls to `$`, `$$` should create an instance of `Proxy` instead of `Element` (without performing a search for element).
- `Proxy` has `$` and `$$` methods (as well as other `locator` methods implemented) which will also return `Proxy` instances. All other properties / methods should be proxied to an `Element` that is lazy-loaded at the moment when this method is called. This allows to define elements anywhere in the code (not only inside methods or page object getters).

With the solution described above, it will be possible to defined elements anywhere, as there is no search performed until you try to perform an action on the element itself:

```js
require('./monkey-patch.js');

const form = $('form[role=search]');
const firstButton = form.$('input[type=submit]');

describe('webdriverio', () => {
  it('should not fail', () => {
    browser.url('https://google.com');
    console.log(firstButton.getAttribute('value'));
    // now we can also extends chai-webdriverio to support this without hacks:
    // expect(firstButton).to.have.attribute('value', 'foo");
  });
});
```

```js
//monkey-patch.js

class LazyElement {
  constructor(selector, parent) {
    this.selector = selector;
    this.parent = parent;
  }

  asProxy() {
    return new Proxy(this, {
      get(target, propName) {
        if (propName in target) {
          return target[propName];
        }
        return args => {
          const resolved = target.fetch();
          return resolved[propName](args);
        };
      }
    });
  }

  fetch() {
    const searchContext = this.parent ? this.parent.fetch() : browser;
    return searchContext.$(this.selector);
  }

  $(selector) {
    return new LazyElement(selector, this).asProxy();
  }

  toString() {
    return this.parent
      ? `${this.parent.toString()} > ${this.selector}`
      : this.selector;
  }
}

global.$ = function(selector) {
  return new LazyElement(selector).asProxy();
};
```

**Describe alternatives you've considered**

Alternative solution would be to use page objects with getters and methods to defer element search to the moment when method or getter is called. However, this still doesn't solve the problem of nicely looking chai expectations.

**Additional context**
Conversation about this with @mgrybyk in gitter: https://gitter.im/webdriverio/webdriverio?at=5dc2923efb4dab784a72ec5b

**Comment by CrispusDH** [comment]
I don't like `lazy elements` idea. I understand that it's just opinion based thing. I think it's adding extra "magic" to framework working. Agree that write PO easier with implemented laziness but it's would have own pitfalls that will be difficult to understand and find.

**Comment by vgrigoruk** [comment]
I think I didn't explain the issue properly. Сurrently WDIO already has a limited version of lazy-loading in place. And it doesn't work consistently, and that is what confuses me:

Here is how lazy-loading works now:
```js
describe('webdriverio', () => {
  it('lazy-loads an element with parent=browser', () => {
    // returns Element instance with error property = "Not found" (element will be reloaded later if you try to perform an action on it)
    const form = $('form[role=search]');
    browser.url('https://google.com');
    // now form is on the page, and `form` element could be reloaded
    const firstButton = form.$('input[type=submit]');
    console.log(firstButton.getAttribute('value')); // outputs "Google Search"
  });
});
```

but this is not gonna work:
```js
describe('webdriverio', () => {
  it('does not lazy-loads an element with parent=element_that_does_not_exist', () => {
    // returns Element instance with error property = "Not found" (element will be reloaded later if you try to perform an action on it)
    const form = $('form[role=search]');
    const firstButton = form.$('input[type=submit]') // test fails here
    browser.url('https://google.com');
  });
});
```

When we move `$` up and put it before `describe` here is what we get (wdio/sync doesn't handle this code I guess):

```js
const form = $('form[role=search]');

describe('webdriverio', () => {
  it('lazy-loads an element with context=browser', () => {
    console.log(form.constructor.name); //outputs Promise
  });
});
```

also, lazy loading doesn't work for $$:
```js
describe('webdriverio', () => {
  it('lazy-loading an element collections is not possible', () => {
    // return Array with length = 0; No reloading is possible.
    $$('.does-not-exist');
  });
});
```

My concern, is that current lazy-loading behavior is very inconsistent. It works only for top-level `$` (with browser search context) but only if browser is launched already at the moment when `$` is executed.

The goal of above proposal is to:
- make lazy-loading to work consistently for `browser.$`, `browser.$$`, `element.$` and `element.$$`
- allow to define elements anywhere in the code

Alternatively, WDIO can have no lazy-loading at all, and then everybody can implement a wrapper that implements lazy-loading on their end.

**Comment by christian-bromann** [comment]
@vgrigoruk can you give us more insights on why you need to fetch elements before you are on the actual site?

**Comment by pedrorfernandes** [comment]
I would delegate the element laziness to a wdio package, this would allow for greater control.

I've created a simple repo with a LazyElement class, mimicking the protractor selector API (still missing readme, tests, usage details, etc). It allows for element composition and array selection

https://github.com/pedrorfernandes/wdio-lazy-element

**Comment by erwinheitzman** [comment]
I like the idea of this but I'm unsure of the possible impact of a change like this. I will have a look at your lazy loading examples later as well :)

**Comment by mgrybyk** [comment]
To fetch element immediately we can add fetch method `$().fetch()`, so that it can work as before.

Even having it, the feature going to be breaking and really painful to refactor. 

What if we keep existing behavior for $ and $$ and add $l and $$l (for example)? I want make migration to newer major version easier for users.

Additionally I see another great benefit!
It should be helpful to improve assertions, especially when it's required to refetch element. Currently we have to wrap $ and $$ with functions that looks ugly.

**Comment by christian-bromann** [comment]
> Even having it, the feature going to be breaking and really painful to refactor.

Why do you think it requires refactoring?

**Comment by mgrybyk** [comment]
At least because everyone relies on current behavior of $ where result of $() is already fetched element. Secondly $$ gonna be array like Proxy object and might also break something .

Despite of that I'd really excited to have this if there are no blockers or objections

**Comment by vgrigoruk** [comment]
The idea is exactly the opposite, @christian-bromann
I don't want elements to be fetched immediately when $ and $$ are executed. 
Instead I would like to have an ability to define elements anywhere in the code and then to get it fetched (lazy-loaded) automatically when I try to access some property of the element (except $ and $$).

Here is a bit of context. We use WDIO in several projects of different complexity / size. 

1. In bigger projects it is more convenient to define page objects and components in order to make tests maintainable and reduce code duplication. Page objects are basically a composition of components. Components can consist of other components. This means that test contain lines of code like this: 
    ```js
    page.component.subComponent.actionThatClicksOnElementInsideComponent();
    // e.g. page.contextSwitcher.menu.select('someMenuItem')
    ```
1. In smaller projects it makes no sense to create separate page objects, so we're inlining `$()` and `$$()` inside tests (plus we use chai-webdriverio for expectations). In this case, our tests look brittle, as the only way to reduce copy-paste is to extract selectors into constants and place them at the top of file.

The benefits we can get switching to lazy-loaded elements:

1. The main one is - no enforcement how to structure your test code.
Currently, you need to be on the page that contains `#foo` in order to define this: `const a = $('#foo').$('#bar')`. With lazy element loading, elements could be defined in any place, which fits the best for specific case (at the top of spec file, page object constructor, exported from other module, inlined in test, etc). This gives much more flexibility to test developer.
1.  no need to wrap elements with functions when we want to implement custom assertions (like chai-webdriverio). E.g. 
```js
// so instead of this:
expect(() => page.element).to.have.text('baz')
// it will be possible to implement custom chai expectations that allow to do this:
expect(page.element).to.have.text('baz')
```
1.  Also as a result, we can potentially reduce an amount of http requests to webdriver backend in case of complex page/component hierarchies (`page.component.component.element`). However, this requires that lazy-loading implemented in a way, that we don't re-fetch the element every time action is performed on it and store a cached version until it becomes stale.
According to https://webdriver.io/docs/pageobjects.html, it is recommended to use getters to define elements (or methods I guess), as defining elements in constructor won't work. This means, that WDIO re-fetches the element every time we call `pageObject.elementGetter`. Removing unnecessary HTTP requests from your tests will definitely make tests faster (especially when you run them e.g in IE11 on SauceLabs). Example (considering we have a page object defined here: https://webdriver.io/docs/pageobjects.html):   
   current behavior:
    ```js
    LoginPage.username.clearValue() // 1 findElement request, followed by 1 request to clear text field value
    LoginPage.username.addValue('foo') // 1 findElement request (there is no need to fetch it one more time unless it is became stale), followed by request to set text field value

    // so, if we don't want to re-fetch element between 2 actions, we need to write code like this:
    const username = LoginPage.username; // 1 findElement request
    username.clearValue(); // 1 request
    username.addValue('foo'); // 1 request, as we use already fetched element.
    ```
    
    with lazy-loading, it will be possible to define `this.username = $('...')` inside `LoginPage` constructor and then:
    ```js
    LoginPage.username.clear() // 1 findElement request, followed by 1 request to clear text field value
    LoginPage.username.setValue('foo') // only 1 request to set text field value (if username element didn't become stale
    ```

**Comment by christian-bromann** [comment]
ok, so let's look into the specific use cases, e.g.

```js
    const form = $('form[role=search]');
    const firstButton = form.$('input[type=submit]') // test fails here
    browser.url('https://google.com');
    firstButton.click()
```

I think this is possible to get implemented. However I don't think this should be ever possible to work:

```js
const form = $('form[role=search]');

describe('webdriverio', () => {
  it('lazy-loads an element with context=browser', () => {
    console.log(form.constructor.name); //outputs Promise
  });
});
```

It will end up having all elements defined like that at the top of the page which will not work anyway because we will make the browser instance available after the describe is called. I could see this being abused a lot. Next is:

```js
describe('webdriverio', () => {
  it('lazy-loading an element collections is not possible', () => {
    // return Array with length = 0; No reloading is possible.
    $$('.does-not-exist');
  });
});
```

We can't do anything lazy here because we have to check whether elements with that selector exist or not. I also don't see a scenario where this is useful.

**Comment by christian-bromann** [comment]
> 1. The main one is - no enforcement how to structure your test code.

I am challenging that. I think enforcing some sort of structure is a good thing and avoids users to write horrible code. That said, I am a friend of keeping a lot of that to the users decision but what you describe is 2. sounds like you are too "lazy" to abstract elements into POs and want a hacky way around it.

> 3\. Also as a result, we can potentially reduce an amount of http requests to webdriver backend

This makes sense and I am happy to explore that.

Overall, something we need to be careful of here is that we don't introduce some sort of lazy load magic that makes it hard to tell when an element is actually be fetched and when not. This needs to be clearly defined and should not make the code too complex to understand.

**Comment by vgrigoruk** [comment]
>  but what you describe is 2. sounds like you are too "lazy" to abstract elements into POs and want a hacky way around it.

I understand why making page objects is the only/recommended way to reuse wdio elements in tests now. 
However, page object abstraction is not a silver bullet, and IMHO wdio could provide more flexibility to test developers (in case they need it).
Creating a page object for a tiny projects with tests that manipulate 2-3 elements looks like an overkill, and instead of 1 file with test that contains everything you now need to jump between 2 files.

**Comment by vgrigoruk** [comment]
Is it feasible to keep both behaviors in place (with and without lazy loading) and activate lazy loading only in case when wdio.config contains some specific flag?

**Comment by erwinheitzman** [comment]
I believe that this would also allow us to write page object models like this (without them breaking):
```
export class ExampleComponent {
    constructor(container) {
        this.container = container;
    }

    get someElement() {
        return this.container.$(`#some-sub-element`);
    }
}
```
Currently this doesn't work when the class is initialised before the element (`container`) exists.

**Comment by christian-bromann** [comment]
> and instead of 1 file with test that contains everything you now need to jump between 2 files.

You can also just have the PO in the same file. It is just about how it is structured.

> Is it feasible to keep both behaviors in place (with and without lazy loading) and activate lazy loading only in case when wdio.config contains some specific flag?

Not sure. Ultimately we should decide on one solution here and not an opt-in version because then code examples are shared that have different behavior and confuse people.

**Comment by nklemiata** [comment]
> 
> 
> I believe that this would also allow us to write page object models like this (without them breaking):
> 
> ```
> export class ExampleComponent {
>     constructor(container) {
>         this.container = container;
>     }
> 
>     get someElement() {
>         return this.container.$(`#some-sub-element`);
>     }
> }
> ```
> 
> Currently this doesn't work when the class is initialised before the element (`container`) exists.

Hi all, 
I've just came across this issue after a long googling on this very question - how to implement 'containers' in WebdriverIO 7.9+ async?
In particular, we are migrating some Protractor repos to WebdriverIO, so ability to reuse the same approach (`return this.container.$(`#some-sub-element`);` would be perfect instead of reinventing a new one!

_Protractor_ example: 

```
export class AutocompleteControl {
  constructor(private container: ElementFinder) {}

  get input() {
    return this.container.$('input[type=text]');
  }
}
```

Our currently used _WebdriverIO_ example:
 
```
export class AutocompleteControl {
  constructor(selector = 'body') {
        this.selector = selector;
    }
  async getWebElement(): Promise<WebdriverIO.Element> {
        return $(this.selector);
    }
    get input() {
        return this.getWebElement().then(e => e.$('input[type=text]'));
    }
}
```

So please review this thread again and give it a chance to be a part of WebdriverIO :)

Otherwise, could you please suggest a better way to implement such chained element getters now, as the new async API is released?

**Comment by christian-bromann** [comment]
> So please review this thread again and give it a chance to be a part of WebdriverIO :)

Not sure if you have seen the labels but we all want this to be part of WebdriverIO. There hasn't been anyone who started implement this. If you are interested in this feature please get involved in the project and help us. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by christian-bromann** [comment]
I will go ahead and close this as the issue has become outdated. You can chain element calls nowadays, e.g. `$('foo').$$('bar')[1].$('loo').click()`. If someone has further suggestions how to improve this, please raise a new issue.

Thank you all for your conversations!
