### ISSUE TITLE
wdio allure reporter does not save stacktrace/screenshot when a test fails on a "before/after" hook using Mocha

### ISSUE THREAD

**Issue by luiscspinho** [webdriverio/webdriverio#4767]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [5.16.0]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [async]
 - **Node.js version:** [10.14.0]
 - **NPM version:** [6.11.3]
 - **Browser name and version:** [Chrome 78]
 - **Platform name and version:** [Mojave 10.14]
 - **Additional wdio packages used (if applicable):** [@wdio/allure-reporter]

**Config of WebdriverIO**
Just add this to the `afterTest` hook:
```js
  afterTest: async test => {
    if (test.error !== undefined) {
      await browser.takeScreenshot();
    }
  },
```

**Describe the bug**
When a test fails on a `before` or `after` hook in mocha, the allure reporter doesn't show the stacktrace or the screenshot available as it would if the test failed on a `it` instruction.
![Screenshot 2019-11-11 at 10 34 56](https://user-images.githubusercontent.com/2779419/68581059-966f9f00-046f-11ea-8a05-b967dd184bf2.png)
![Screenshot 2019-11-11 at 10 35 11](https://user-images.githubusercontent.com/2779419/68581069-9bcce980-046f-11ea-94a0-c18c9b8f4910.png)

**To Reproduce**
Just make a test fail on a `before` and open the report.
I've created a small example on how to reproduce this behaviour.
https://github.com/luiscspinho/wdio-allure-bug

**Expected behavior**
I was expecting to have the stacktrace/screenshot like what happens when a test fails on an `it`

**Comment by mgrybyk** [comment]
Before is not a test, move add screenshot to afterHook as well

**Comment by luiscspinho** [comment]
I've updated the repo to have the `takeScreenshot` in the afterHook but the result is the same.

I reckon that the before is not a test, but shouldn't we register the stacktrace/screenshot in the report? There are some cases were `before` can be used to setup a test and something can go wrong there.

**Comment by mgrybyk** [comment]
May you help investigating it?

**Comment by luiscspinho** [comment]
Yes I'm glad to do it, I'm looking into the code but I need some directions. You can find me on gitter

**Comment by mgrybyk** [comment]
I think https://github.com/webdriverio/webdriverio/blob/a15f442c2481531317b91784a635088fcd9dd046/packages/wdio-allure-reporter/src/index.js#L179 have to be adopted to capture screenshots in case of before or after hook failure. Maybe the issue is that no tests are running at that moment or something. 
P.s. Please note that screenshot should be captured in afterHook

**Comment by luiscspinho** [comment]
Thanks a lot.
I've briefly tested it and it looks like that there are 2 main problems here. The first is exactly what you said, the test is not yet "running", so it breaks right away. The second one is that when it breaks, the `this.allure.getCurrentSuite()` instruction doesn't retrieve an object initialised, so the `suite` object will be empty and that is why the report doesn't show any stacktrace/screenshot despite calling the window api to have the screenshot and everything in local vars.

Not sure on how to go from here, you do you think @mgrybyk ?

**Comment by mgrybyk** [comment]
Take a look how before hook appears in the report. Maybe you can temporary store screenshot taken in after command to reuse later on?

**Comment by luiscspinho** [comment]
Hey @mgrybyk ,
So, I just found out why the actions are not being recorded on the before/after, it was because of this change https://github.com/webdriverio/webdriverio/pull/4406

I understand the reasoning behind this PR but I think that at least we should have stacktrace/screenshots in case our tests fail. So maybe I can have a new `option` that turns off this option? What do you think?

**Comment by mgrybyk** [comment]
I don't mind, you may try if it works for you.

Additionally it would be great if we allow to take screenshot in failed mocha's `before` hooks without introducing any additional options

**Comment by luiscspinho** [comment]
I agree @mgrybyk , the default behaviour should be to have screenshots/stacktrace for `before/after` mocha hooks. This means that the work done on that PR that I linked should be behind an option/throttle. The way the reporting is working right now I think that its not possible to do that without an option, or reverting that code.

I'll put that code behind an option, something like `disableMochaHooks`, do you agree?

**Comment by kopax-polyconseil** [comment]
Hi, we have the exact same issue, did you solve it? I would gladly want to know how.

Our tests looks as follow:

```tsx
describe('TabBar', () => {
  before(async () => {
    await FirstLaunch.proceed()
    await TabBar.waitForIsShown(true)
  })

  it('should click on home', async () => {
    await TabBar.home.click()
  })

  it('should click on search', async () => {
    await TabBar.search.click()
  })
})
```
