### ISSUE TITLE
How to bypass basic authentication with https

### ISSUE THREAD

**Issue by LexiPham** [webdriverio/webdriverio#4768]
I have asked on gitter but no one knows the answer. For example:

I can by pass http but can't not with https

http://guest:guest@jigsaw.w3.org/HTTP/Basic/ --> this works.

https://guest:guest@jigsaw.w3.org/HTTP/Basic/ --> this doesn't work.

My test server redirect http to https so I alway use https, I don't know how to by pass this https, if you know something please let me know. Thanks.

**Comment by mgrybyk** [comment]
Closing according to https://github.com/webdriverio/webdriverio/issues/837#issuecomment-554691672
