### ISSUE TITLE
How to perform an action on an element with given text?

### ISSUE THREAD

**Issue by binarykitchen** [webdriverio/webdriverio#477]
I would like to perform a double click on an element that has a certain text, i.E.

```
.doubleClick('hit me')
```

this on

```html
<button>hit me</button>
```

Looks like there are no CSS nor Xpath selectors capable of selecting an element based on text. Either this is a feature request or I am missing something?

**Comment by hanneshal** [comment]
you can have a look here, maybe this helps. I would use jquery oder JS code if I had to select such kind of elemenets. I don't know what kind of structure you are dealing with but selectors for the last, first, nearest element of another element I always found what I need. 

http://stackoverflow.com/questions/7321896/jquery-find-element-by-text

regards

**Comment by binarykitchen** [comment]
We currently do not use jQuery and do not want to add it to our dependencies. Isn't there a native solution or a trick? Too bad that it's not working with CSS3 or Xpath selectors.

**Comment by christian-bromann** [comment]
@binarykitchen the current master version already has that kind of selector strategy implemented (it would be `=hit me`). I'll go publish everything that's in master today or tomorrow as waiting for v3.0 would take too long

@hanneshal we can't use jquery here as we are relying on the webdriver protocol and its selector strategies. __But__ we can create those kind selector strategies, parse them and transform them into xPaths

**Comment by binarykitchen** [comment]
@christian-bromann wonderful, looking forward to that. Keep me updated on this ticket. Thx

**Comment by christian-bromann** [comment]
resolved by https://github.com/webdriverio/webdriverio/commit/879a4e9

**Comment by binarykitchen** [comment]
cool, when is this available on npm?

**Comment by christian-bromann** [comment]
@binarykitchen It will get shipped with `v3`. We are currently working on that to get that out asap. Can't predict any date though
