### ISSUE TITLE
isClickable() returns false even if webdriver can click on it

### ISSUE THREAD

**Issue by igerasimov23** [webdriverio/webdriverio#4770]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.16.6
 - **Mode:** [Standalone mode or WDIO Testrunner] WDIO
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async] sync
 - **Node.js version:** 10.16.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Chrome 78
 - **Platform name and version:** mac 10.13

**Describe the bug**
isClickable() method returns false even if webdriver can click on it

**To Reproduce**
SauceLab session: https://app.saucelabs.com/tests/f1ba7fd84f754a68b7064982bd926f8f
```
it('Verify save recap header navigation -feature save-recap', () => {
    // preparing a state
    browser.url('https://cooking.nytimes.com');
    browser.setCookies({
      name: 'NYT-S',
      value: '1wgudaaCk1pEnpqRO8JdfCRc6g2K2eEyqD1ygWQZvgFkqeKfL5Rg.vnJ8Rub.mpPw/alTpzrtSHSEKCTZP5x4liKozoREjQA0Se2hZqDu7n/Berrf3ZQA4MXU.nZCvmPL4',
      domain: '.nytimes.com',
      path: '/',
    });

    browser.refresh();

    let el = $('a.nytc---saverecap---recipeName');

    el.scrollIntoView();
    console.log(el.isDisplayed());  // true
    console.log(el.isDisplayedInViewport()); // true
    console.log(el.isEnabled()); // true
    console.log(el.isClickable()); // false
    el.waitForClickable();
  });
```

**Expected behavior**
Should return true as element clearly clickable and webdriver can click on it

**Log**
```
[0-0] RUNNING in chrome - /test/features/save-recap/save-recap.js
[0-0] true
[0-0] true
[0-0] true
[0-0] false
[0-0] ******* TEST 'Verify save recap header navigation -feature save-recap' FAILED *******
[0-0] Error in "save-recap functionality Verify save recap header navigation -feature save-recap"
element ("a.nytc---saverecap---recipeName") still not clickable after 10000ms
[0-0] FAILED in chrome - /test/features/save-recap/save-recap.js
[slack-reporter] Slack Webhook URL is not configured, notifications will not be sent to slack.

 "dot" Reporter:
F

 "spec" Reporter:
------------------------------------------------------------------
[chrome  mac os x #0-0] Spec: /Users/208821/Projects/np-cooking/api/test/e2e/test/features/save-recap/save-recap.js
[chrome  mac os x #0-0] Running: chrome on mac os x
[chrome  mac os x #0-0]
[chrome  mac os x #0-0] save-recap functionality
[chrome  mac os x #0-0]    ✖ Verify save recap header navigation -feature save-recap
[chrome  mac os x #0-0]
[chrome  mac os x #0-0] 1 failing (28.7s)
[chrome  mac os x #0-0]
[chrome  mac os x #0-0] 1) save-recap functionality Verify save recap header navigation -feature save-recap
[chrome  mac os x #0-0] element ("a.nytc---saverecap---recipeName") still not clickable after 10000ms
[chrome  mac os x #0-0] Error: element ("a.nytc---saverecap---recipeName") still not clickable after 10000ms
[chrome  mac os x #0-0]     at Context.<anonymous> (/Users/208821/Projects/np-cooking/api/test/e2e/test/features/save-recap/save-recap.js:94:8)
```

**Comment by igerasimov23** [comment]
@mgrybyk I see this command still failing in some cases

**Comment by mgrybyk** [comment]
@igerasimov23 it works as designed, `<span>` element receives the click event instead of <a>

I need to think a bit if we can improve it

**Comment by igerasimov23** [comment]
But in this case no one will receive click() if `el.waitForClickable();` will fail which will cause  test to fail as well. But `<span>` is clickable as well, why it returns false then?

**Comment by igerasimov23** [comment]
I though by definition element is clickable if it:
displayed,
enabled,
in viewport,
not overlapped
In my case it follows above criteria and can be even `clicked` but `isClickable` returns false. Very confused here, what is `isClickable()` for then?

**Comment by mgrybyk** [comment]
no need to worry, I absolutely agree, just need time to investigate what is going on, why SPAN is returned.

I think I get that already, there is an issue with center position calculation, don't know how to deal with atm, will think

**Comment by mgrybyk** [comment]
@igerasimov23 ok, I think I know how to fix that.

Thanks for submitting, it's an interesting case and should be handled by isClickable for sure!

**Comment by mgrybyk** [comment]
will be fixed with the PR

**Comment by YashMonetate** [comment]
Hi @mgrybyk, this still seems an issue. When i am calling isClickable() or isEnabled(), it returns true even my element is disabled. Please see below SS
![image](https://user-images.githubusercontent.com/70005957/99511867-d0428200-29ae-11eb-9575-82f99ab1a4bb.png)

**Comment by mgrybyk** [comment]
@YashMonetate your element is not disabled, it's just a class

**Comment by YashMonetate** [comment]
@mgrybyk Pls see below property of class(what you were referring to) when button is enabled. I guess webdriverio just look for <span> tab for deciding that button is enabled or not. But in this case <span> tag doesn't contain any info about enabled/disabled.
![image](https://user-images.githubusercontent.com/70005957/99518710-f8ce7a00-29b6-11eb-8563-9d70ddc7db4b.png)

**Comment by mgrybyk** [comment]
@YashMonetate there is a standard approach on how to an input, if you are not following it (or using such UI framework)  you have to implement your custom way to check if an element is enabled. 
There are tons of ways to disable an element from end user point of view however, there is only one way to do it according to the specification.
