### ISSUE TITLE
No system output in junit reporter

### ISSUE THREAD

**Issue by pauravp** [webdriverio/webdriverio#4774]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [5.12.1]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [10.15.1]
 - **NPM version:** [6.4.1]
 - **Browser name and version:** [e.g. Chrome 78.0.3904.70]
 - **Platform name and version:** [Mac OSX High Seirra ]
 - **Additional wdio packages used (if applicable):** []

**Describe the bug**
In v4 , even if logLevel of wdio was silent but in case of error junit reports used to have system output like this
`<testcase classname="chrome.gallery/gallery_view_test_spec" name="gallery_grid_view" time="0.955">
      <system-out>
        <![CDATA[
COMMAND: POST http://127.0.0.1:4444/wd/hub/session/40246d547833c9353af00d3f6eb59371/elements - {"using":"css selector","value":"#public-gallery-switch > div:nth-child(2) > div"}
RESULT: {"sessionId":"40246d547833c9353af00d3f6eb59371","status":0,"value":[]}
COMMAND: POST http://127.0.0.1:4444/wd/hub/session/40246d547833c9353af00d3f6eb59371/elements - {"using":"css selector","value":"#public-gallery-switch > div:nth-child(2) > div"}
RESULT: {"sessionId":"40246d547833c9353af00d3f6eb59371","status":0,"value":[{"ELEMENT":"0.669699042200689-3"}]}
]]>
     </system-out>
    </testcase>`

but now in v5 , there is only system-err which doesn't contains COMMAND and RESULT which were very helpful. Is it possible to being system output back in reports using any config option?

`<testcase classname="chrome.77_0_3865_120.macosx.video" name="remove_uploaded_video_from_adhoc" time="30.006">
     <error message="Couldn't find div[class*=&quot;grid-asset&quot;][style*=&quot;visible&quot;] at 0 position"/>
     <system-err>
       <![CDATA[
Error: Couldn't find div[class*="grid-asset"][style*="visible"] at 0 position
   at Object.waitForElementAt (/Users/pallvipaurav/Git/lrwebdriverio/test/helpers/common_functions.js:64:11)
   at Object.select_img (/Users/pallvipaurav/Git/lrwebdriverio/test/helpers/common_functions.js:556:29)
   at Context.it (/Users/pallvipaurav/Git/lrwebdriverio/test/specs/video/video_adhoc_upload_test_spec.js:71:10)
]]>
     </system-err>
   </testcase>`

**To Reproduce**
Run any test case which can fail 

**Expected behavior**
I would like to have  <system-out> in junit reporter if test fails irrespective of what logLevel was set in wdio config. Else please advise how can I access  <system-out> data without using `Info` log level which is super noisy.

**Comment by VladimirCW** [comment]
Hello, guys, this issue is strongly affects us, will it be resolved?

**Comment by christian-bromann** [comment]
@VladimirCW as you can see we appreciate any contributions that would fix this issue. Cheers!

**Comment by christian-bromann** [comment]
@VladimirCW I have fixed the issue in #5544
