### ISSUE TITLE
Extra capabilities without prefix.

### ISSUE THREAD

**Issue by viktor-silakov** [webdriverio/webdriverio#4778]
If there is a workaround to pass extra capabilities without vendor-specific prefix? The www.lambdatest.com and crossbrowsertesting.com services don't support prefixes, how can I use them via Webdriver I/O?

**Comment by mgrybyk** [comment]
Just dont use prefixes for that services

**Comment by christian-bromann** [comment]
@viktor-silakov you should reach out to these services and report this. Almost all WebDriver based tools and frameworks require prefixed capabilities. You can just try to use non prefixed capabilities and see if their infrastructure picks these up.

Closing as this is not something WebdriverIO can fix.
