### ISSUE TITLE
how create new session with same browser ?

### ISSUE THREAD

**Issue by nchintu** [webdriverio/webdriverio#4779]
I have "webdriverio": "^4.9.9", version and Running testing on Windows 10.

I have a case where I am launching 2 chrome browsers but since both the browsers are sharing sessionid, the 2nd browser does not open a new clean browser session.
this behavior is reproducible only on the latest version of chrome 78.0.3904.97 (Official Build) (64-
bit), I have set the browser to open in incognito mode.

STeps I am following:
1. launch chrome browser.
2. go to application url and login into application as a user forex : testuser1. After successful login now the application in on the landing page.
3. launch 2nd chrome browser.
4. navigate to application url. the application is already in landing page and logged in as testuser1.
I am expecting it to open a new clean window and navigate to login page so I can login as new user. 

How can open 2 same browsers to have newsession ?
Please advise

**Comment by christian-bromann** [comment]
Please see the [multiremote](https://webdriver.io/docs/multiremote.html) functionality. Also we strongly recommend to update to v5. WebdriverIO v4 is not supported anymore.

**Comment by nchintu** [comment]
Hi thankyou for your reply.
   I looked at multiremote functionality and it does not launch the browser.
currently my code works with below capability in my wdio.conf.js file
capabilities: [	 	
	 	{
	 		browserName: `chrome`,
	 		unexpectedAlertBehaviour: 'ignore',
	 		ignoreProtectedModeSettings: true,
	 		/* chromeOptions: {
				args: ["incognito"]
			} */
	 	},
	 ], 

I cannot change wdio file. all I wanted is launch 2nd browser and run tasks on my 2nd browser. 
My test method has below code. it executes fine but does not launch new browser window:

var browser2 = webdriverio.multiremote({
        browserB: { desiredCapabilities: { browserName: 'chrome' } }
    });
     browser2.url('http://google.com')
    console.log(browser2.getTitle()) // outputs: "Google"
    browser2.close()
    console.log(browser2.getTitle()) // outputs: "Google"
    console.log("closed browser");

I am new to wdio and any help would be appreciated.
