### ISSUE TITLE
mochaOpts question

### ISSUE THREAD

**Issue by unickq** [webdriverio/webdriverio#4780]
**Describe your question with as much detail as possible**
I want to add native **mocha** reporter to wdio configs using following code:
```javascript
 mochaOpts: {
    require: ["ts-node/register"],
    reporter: "mochawesome",
  },
```
but can't make it work. Do I do something wrong, or wdio has own mocha context and that's why I can use reporter there?

The thing is - I don't wanna use wdio-mochawesome because of https://github.com/fijijavis/wdio-mochawesome-reporter/issues/52 . So according to mocha and wdio docs, I expected to make it work using **reporter** in **mochaOpts**. And if I use `reporter: "mochawesome"` without installing mochawesome - wdio doesn't start. So it registers it somehow

Is there any options about how to make reporter work in mochaOpts?

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.16.7
 - **Mochawesome version:** 4.10.1

**Comment by christian-bromann** [comment]
> Is there any options about how to make reporter work in mochaOpts?

No. Native framework reporter addons don't work which is why WebdriverIO provides its own set of reporters. The reason is that native reporter are not designed to run in a concurrent environment, they provide no context to which capability ran the test nor can they create different files for different workers.

**Comment by christian-bromann** [comment]
I would recommend to fix the issue (fijijavis/wdio-mochawesome-reporter#52) in the  wdio reporter and continue using that. Cheers!
