### ISSUE TITLE
.setValue and .addValue don't work for MicrosoftEdge or FireFox browsers in app using redux-forms

### ISSUE THREAD

**Issue by leongaban** [webdriverio/webdriverio#4782]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. ^5.6.2]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync:** [e.g. sync]
 - **Node.js version:** [e.g. 10.15.3]
 - **NPM version:** [e.g. 6.4.1]
 - **Browser name and version:** [e.g. MicrosoftEdge / FireFox latest]
 - **Platform name and version:** [e.g. Windows 10]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config
```
const specs = require('./specs');
const capabilities = require('./capabilities');

exports.config = {
    user: 'xxx',
    key: 'xxxxx...',
    specs: specs[process.env.SAUCE_TEST_TYPE],
    exclude: specs.exclude,
    maxInstances: 15,
    capabilities: capabilities[process.env.SAUCE_BROWSER],
    sync: true,
    logLevel: 'silent',
    coloredLogs: true,
    hostname: 'xxx...',
    protocol: 'https',
    port: 443,
    path: '/wd/hub',
    baseUrl: 'http://localhost:8080',
    waitforTimeout: 90000,
    services: ['sauce'],
    framework: 'mocha',
    reporters: [
        'spec',
        [
            'junit',
            {
                outputDir: `./test/wdio-xml-results/${process.env.SAUCE_TEST_TYPE}-xml/`,
                outputFileFormat: options => {
                    let browser =
                        // fix whitespace breaking file-path in script files
                        options.capabilities.browserName === 'internet explorer'
                            ? 'internetExplorer'
                            : options.capabilities.browserName;
                    return `results-${options.cid}.${browser}.xml`;
                }
            }
        ]
    ],
    mochaOpts: {
        ui: 'bdd',
        compilers: ['js:@babel/register'],
        timeout: 900000 // 15 minutes
    }
};
```

**Describe the bug**
Webdriver cannot fill in inputs in a React app using redux-forms.

**To Reproduce**
Stackoverflow question: https://stackoverflow.com/questions/58860806/how-to-fill-in-redux-form-inputs-in-firefox-edge-via-webdriver-automated-tests

With a React app an redux-forms component, using `setValue` or `addValue` will not update the input values:

```
setFirstName: value => {
    const xpath = "//input[@name='firstName']";
    browser.setInputValue(xpath, value); // <- Looks like inputs are filled in the UI, but are not actually filled in the form
    // $(xpath).setValue(value); // <- normal webdriver method which doesn't work
}
```

**Comment by mgrybyk** [comment]
It works like it should, that's how the form controls in your app are implemented and how browser drivers behave, nothing can be done to addValue.
You may implement your own custom commands to fill custom controls like that or even overwrite add/set value and depending on control type, standard or custom, decide either to use built in add/set value or your implementation. 

If you still have some question feel free to ask.
