### ISSUE TITLE
Element.getProperty(string) return type is incomplete

### ISSUE THREAD

**Issue by jrobinson01** [webdriverio/webdriverio#4786]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.16
 - **If WDIO Testrunner, running sync/async:** sync

**Describe the bug**
The webdriverio.core.d.ts defines `Element.getProperty(string):object|string`. It should also include at least `boolean` as a possible return value. I'm guessing but haven't tested, that `number` is also possible. 

**To Reproduce**
Use typescript or JSDoc'd JS in your test files. Do something like this:
`expect(someElement.getProperty('someBool') === true).toBe(false);`
typescript will complain that `object|string` is always `true`.

**Expected behavior**
typescript shouldn't complain about the above.

**Comment by jrobinson01** [comment]
How are the .d.ts files generated? Are they built from code or hand written?

**Comment by christian-bromann** [comment]
They are generated so you most likely want to change it here: https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/commands/element/getProperty.js#L15

**Comment by christian-bromann** [comment]
fixed by #4797
