### ISSUE TITLE
WDIO freezes VS Code debugger upon use of WDIO commands

### ISSUE THREAD

**Issue by Khromchenko** [webdriverio/webdriverio#4788]
I'm able to use VS Code debugger but with no ability to use WDIO commands. Any use of WDIO apis such as browser.$()... freezes VS Code debugger.

Here is my launch.json

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "WDIO",
            "program": "${workspaceFolder}/node_modules/.bin/wdio",
            "port": 5859,
            "autoAttachChildProcesses": true,
            "protocol": "inspector",
            "args": [
                "wdio.conf.js",
                "--spec",
                "spec/login/login-spec.js" // File which you would like to debug
            ],
            "internalConsoleOptions": "openOnSessionStart",
            "cwd": "${workspaceRoot}",
            "env": {
                "DEBUG": "1" 
                // use an environment variable to be able
                // to toggle debug mode on and off
            }
        }
    ]
}
```

wdio.conf.js inludes following:

```
debug: true,
execArgv: ['--inspect-brk=127.0.0.1:5859'],
```

**Is there a way to set up VS Code to be able to use all WDIO apis?** 
Just like we would use browser.debug()

**Environment:**
 - **WebdriverIO version:** 5.16.6
 - **Node.js version:** v12.12.0
 - **NPM version:** 6.13.0
 - **Browser name and version:** Chrome
 - **Platform name and version:** UNIX

**Comment by Khromchenko** [comment]
Just FYI, Looks like it worked in WDIO 4 for this guy:
http://blog.likewise.org/2017/02/debugging-a-javascript-webdriverio-project-in-vscode/

**Comment by mgrybyk** [comment]
You may use browser.debug instead. The behavior you see is how fibers work. I think there is nothing can be done here

**Comment by christian-bromann** [comment]
Being able to use VSCode debugger capabilities should be something that is suppose to work. Any help on this is appreciated.

**Comment by mgrybyk** [comment]
Don't know how to deal with it, let's ask node-fibers team to help https://github.com/laverdet/node-fibers/issues/425

**Comment by mgrybyk** [comment]
closing because @christian-bromann replaces node-fibers with deasync https://github.com/webdriverio/webdriverio/pull/4886

**Comment by johnnymo87** [comment]
Since @christian-bromann closed that PR without merging it, should we open this issue back up @mgrybyk ?

**Comment by christian-bromann** [comment]
Any help on this would be highly appreciated!

**Comment by christian-bromann** [comment]
As we deprecated and now removed `fibers` with `v8` we can close the issue as the problem doesn't exist anymore.
