### ISSUE TITLE
wdio sync mode works slow in windows

### ISSUE THREAD

**Issue by tamil777selvan** [webdriverio/webdriverio#4789]
While executing tests in wdio using sync mode, tests are too slow and gets hanged.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.16.7
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10
 - **NPM version:** 6.9
 - **Browser name and version:** Chrome 78
 - **Platform name and version:** Windows 7
 - **Additional wdio packages used (if applicable):** 
    "@wdio/cli": "5.16.7",
    "@wdio/cucumber-framework": "5.16.6",
    "@wdio/local-runner": "5.16.7",
    "@wdio/reporter": "5.15.2",
    "@wdio/spec-reporter": "5.16.5",
    "@wdio/sync": "5.16.5",

**Additional context**
Attaching wdio log and selenium server log for reference. Kindly check line num 151 and 152 in wdio log where it gets hanged.
[wdioTest.log](https://github.com/webdriverio/webdriverio/files/3866962/wdioTest.log)
[selenium.log](https://github.com/webdriverio/webdriverio/files/3866965/selenium.log)

**Comment by christian-bromann** [comment]
@tamil777selvan can you provide us a log file that was run without sync mode? Also is there a reproducible example we can use?

**Comment by tamil777selvan** [comment]
@christian-bromann Please find the logs attached for async run.
[wdioAsyncTest.log](https://github.com/webdriverio/webdriverio/files/3875861/wdioAsyncTest.log)

Reproducible example can be found in https://github.com/tamil777selvan/OSEAN

**Comment by mgrybyk** [comment]
@tamil777selvan please remove all your code and provide with minimal reproducible example.
It's extremely time consuming to understand if it's some issue in your code or wdio

**Comment by tamil777selvan** [comment]
@mgrybyk since the original setup is behind corporate firewall, created this sample. I have removed all the un wanted file and just have the skeleton with single feature in https://github.com/tamil777selvan/OSEAN/tree/slowness

**Comment by mgrybyk** [comment]
@tamil777selvan that's better! If you can leave only one feature file with just one action and remove all your pages, selectors and so on it would be even better

**Comment by tamil777selvan** [comment]
@mgrybyk as per your comments have removed all selectors and yargs, also have kept one scenario which does just login to provided url. Also removed all other actions which is not used.

**Comment by mgrybyk** [comment]
Thanks a lot

**Comment by mgrybyk** [comment]
Closing as not reproducible.
You have to update all wdio packages to the latest versions. In your repo both in master and slowness branch packages are outdated and lots of them have hardcoded version.

Test is passing well on both windows and mac os for me.

![image](https://user-images.githubusercontent.com/25589559/69480878-d0e02100-0e0b-11ea-91a8-9b2f4506751b.png)
