### ISSUE TITLE
isClickable() returns false on MS Edge only

### ISSUE THREAD

**Issue by igerasimov23** [webdriverio/webdriverio#4790]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.16.7
 - **Mode:** [Standalone mode or WDIO Testrunner] WDIO
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async] sync
 - **Node.js version:** 10.16.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Chrome 78 / MS Edge 18
 - **Platform name and version:** Windows 10

**Describe the bug**
isClickable() returns false on MS Edge. After investigation I see that adding `element.scrollIntoView(false);` solves issue for most of the cases. Looks like on Ms Edge isClickable() does not scrolls into view

**To Reproduce**
```
it.only('Verify \'See all recipes\' link on Sam\'s suggestions', () => {
    browser.url('https://cooking.nytimes.com');

    let element = $("#sams-suggestions [class='owl-next']");
    browser.waitUntil(() => element.isClickable(), null, 'message');
  });
```
MS Edge: https://app.saucelabs.com/tests/c5a54f972c894a7997eca742bdc64bef#31
fails on MS edge

Chrome: https://app.saucelabs.com/tests/51ffe88e0dc04b33af7ced3e1fa19b65#7
Passing on Chrome

**Expected behavior**
isClickable() should scroll into view first if element visible

**Comment by mgrybyk** [comment]
That's because edge 18 doesn't fully support scrollIntoView. 
I don't know if it makes sense to fix it. May you try upgrading to edge that goes after 18? I think it should be based on chromium

**Comment by mgrybyk** [comment]
To do: try in safari

**Comment by igerasimov23** [comment]
I think 18 is the latest one, at least on Saucelab.  They are planning on release on early 2020. Yep, the same on safari. I will just add scrollIntoView() then in my custom command:
```
waitAndClick(element, msg) {
    const message = (typeof msg === 'undefined') ? element.selector : msg;
    element.scrollIntoView(false);
    browser.waitUntil(() => element.isClickable(), null, message);
    element.click();
    sendLog(`Clicked element '${message}'`);
    return this;
  }
```

Thank you

**Comment by mgrybyk** [comment]
@igerasimov23 if the same is in safari it makes sense to fix the issue.
I'll take a look soon. Just need to understand somehow if scrollIntoView is fully supported by specific browser.

**Comment by mgrybyk** [comment]
@igerasimov23 the issue is not reproducible for me in Safari 12

**Comment by mgrybyk** [comment]
let's proceed convo in the pr
