### ISSUE TITLE
isClickable() returns false on elements inside a shadowRoot

### ISSUE THREAD

**Issue by lacell75** [webdriverio/webdriverio#4796]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.16.7 
 - **Mode:** WDIO
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.6.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** ALL (Chrome 78 / firefox /Microsoft Edge 44.17763.771.0)
 - **Platform name and version:**  Windows 10
 - **Additional wdio packages used (if applicable):** "@wdio/cli": "^5.16.0",
    "@wdio/cucumber-framework": "^5.16.6",
    "@wdio/dot-reporter": "^5.16.5",
    "@wdio/local-runner": "^5.16.7",
    "@wdio/mocha-framework": "^5.16.5",
    "@wdio/selenium-standalone-service": "^5.16.5",
    "@wdio/spec-reporter": "^5.16.5",
    "@wdio/sync": "^5.16.5",

**Describe the bug**
isClickable() method returns false even if webdriver can click on it (I use an element's shadowRoot)

**To Reproduce**
```
describe('Try to click button in shadowRoot', () => {
  it('Try to click button in shadowRoot', () => {
      browser.url('http://www.kaidez.com/samples/template-shadowdom-practice/');
  const allbooks = browser.$('#allBooks');
  const button = allbooks.shadow$('#btnPurchase');
  console.log(button.isDisplayed()); // true
  console.log(button.isDisplayedInViewport()); // true
  console.log(button.isEnabled()); // true
  console.log(button.isClickable()); // false
  button.waitForClickable({ timeout: 10000 });
  button.click();
  });
});
```

**Expected behavior**
Should return true as element clearly clickable and webdriver can click on it

**Log**
```
Execution of 1 spec files started at 2019-11-22T11:11:30.481Z

[0-0] RUNNING in chrome - C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\features\test.feature
[0-0] true
[0-0] true
[0-0] true
[0-0] false
[0-0] Error in "Try to click button in shadowRoot: Try to click button in shadowRoot: Given Try to click button in shadowRoot"
element ("function() {
      // element has a shadowRoot property
      if (this.shadowRoot) {
        return this.shadowRoot.querySelector('#btnPurchase')
      }
      // fall back to querying the element directly if not
      return this.querySelector('#btnPurchase')
    }") still not clickable after 10000ms
[0-0] Save a screenshot
[0-0] FAILED in chrome - C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\features\test.feature
```

**Comment by jrobinson01** [comment]
I'm not sure what the solution is yet, but the problem seems to be that `document.elementFromPoint(x,y)` is returning the outermost element and not the element inside the shadowDom. An example: 
```html
<my-element>
    <!-- my-element's shadow root -->
    <button>Hello!</button>
</my-element>
```
```javascript
document.addEventListener('click', event => console.log(document.elementFromPoint(event.clientX, event.clientY)));
```
logs `<my-element>` instead of `<button>`

**Comment by jimmy-collazos** [comment]
Hi.
The problem is with "element.contains()" function; because this don't found in shadow Root.

I'm sending pull request to fix this problem...

**Comment by mgrybyk** [comment]
I'm not sure that it is the issue, raise another PR.

Let's proceed convo in the PR
