### ISSUE TITLE
isClickable shadow root support (#4800) doesn't work on Edge

### ISSUE THREAD

**Issue by lacell75** [webdriverio/webdriverio#4804]
*Environment (please complete the following information):**
 - **WebdriverIO version:** 5.16.9
 - **Mode:** WDIO
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.6.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Microsoft Edge 44.17763.831.0 Microsoft EdgeHTML 18.17763
 - **Platform name and version:**  Windows 10
 - **Additional wdio packages used (if applicable):** "@wdio/cli": "^5.16.9",
    "@wdio/cucumber-framework": "^5.16.9",
    "@wdio/dot-reporter": "^5.16.5",
    "@wdio/local-runner": "^5.16.9",
    "@wdio/mocha-framework": "^5.16.5",
    "@wdio/selenium-standalone-service": "^5.16.5",
    "@wdio/spec-reporter": "^5.16.5",
    "@wdio/sync": "^5.16.9",

**Describe the bug**
- With Microsoft Edge : isClickable() method returns false even if webdriver can click on it (I use an element's shadowRoot)
- With Chrome And Firefox : That works correctly
**To Reproduce**
```
describe('Try to click button in shadowRoot', () => {
  it('Try to click button in shadowRoot', () => {
    browser.url('https://shop.polymer-project.org/');
    const app = browser.$('shop-app');
    const home = app.shadow$('shop-home');
    const button = home.shadow$('[href="/list/mens_outerwear"]');
    button.waitForDisplayed(5000);
    console.log(button.isDisplayed()); // true
    console.log(button.isDisplayedInViewport()); // true
    console.log(button.isEnabled()); // true
    console.log(button.isClickable()); // false
    button.waitForClickable({ timeout: 10000 });
    button.click();
  });
});
```

**Expected behavior**
Should return true as element clearly clickable and webdriver can click on it

**capabilities:**
```
capabilities: [

    {
      maxInstances: 4,
      browserName: 'MicrosoftEdge',
      unhandledPromptBehavior: 'accept',
    },
]
```

**Log**
TEST KO on Edge:
```
Execution of 1 spec files started at 2019-11-25T10:54:42.317Z

[0-0] RUNNING in MicrosoftEdge - C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\features\test.feature
[0-0] true
[0-0] true
[0-0] true
[0-0] false
[0-0] Error in "Try to click button in shadowRoot: Try to click button in shadowR: Given Example"
element ("function() {
      // element has a shadowRoot property
      if (this.shadowRoot) {
        return this.shadowRoot.querySelector('[href="/list/mens_outerwear"]')
      }
      // fall back to querying the element directly if not
      return this.querySelector('[href="/list/mens_outerwear"]')
    }") still not clickable after 10000ms
[0-0] Save a screenshot
[0-0] FAILED in MicrosoftEdge - C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\features\test.feature
```

TEST OK on Chrome:
```
Execution of 1 spec files started at 2019-11-25T10:56:25.647Z

[0-0] RUNNING in chrome - C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\features\test.feature
[0-0] true
[0-0] true
[0-0] true
[0-0] true
[0-0] PASSED in chrome - C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\features\test.feature
```

**Comment by mgrybyk** [comment]
Edge doesn't support shadow root. 
There is some issue with contains function in edge that's why is clickable is not working.

It's great that is clickable works well in chrome, firefox and safari at least.

**Comment by lacell75** [comment]
Are you sure? because I use all others wdio APis and I have never seen some issue with shadow Root and Edge.  
I'm running tests on 3 browsers (Chrome, firefox and Edge), and I can't use waitForClickable API due to this Edge issue. I'm disappointed because , it would have helped me on several points. Do you have any solution to do a workaround in isClickable function or may be in my code? 

Before the development of waitForClickable, I used a custom function but it's not perfect: `  browser.addCommand('waitAndClick', function () {
    this.waitForExist(10000);
    this.waitForDisplayed(60000);
    this.waitForEnabled(2000);
    this.click();
  }, true);`

**Comment by mgrybyk** [comment]
Yeah, pretty much sure.

**Comment by mgrybyk** [comment]
will be fixed with the PR

**Comment by lacell75** [comment]
Great !!
