### ISSUE TITLE
beforeEach mocha hook executes before beforeTest

### ISSUE THREAD

**Issue by ndebogory** [webdriverio/webdriverio#4806]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 3.0.3]
 - **Mode:** [standalone 5.6.3]
 - **Node.js version:** [e.g. 10.15.0]
 - **NPM version:** [e.g. 6.4.1]
 - **Browser name and version:** [e.g. Chrome 78]
 - **Additional wdio packages used (if applicable):** @wdio/mocha-framework [e.g. 5.16.5]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
In a project we have some settings that run in beforeSuit (some browser settings) and beforeTest (some allure reporter settings). When I add a beforeEach mocha hook for a test, it executes in an order:
beforeSuit
beforeEach
beforeTest

Is there any way that I can apply method execution before each tests by hooks functionality?

**Expected behavior**
By adding beforeEach mocha hook I can add some preconditions, that will be executed, for each test in describe()

**Comment by christian-bromann** [comment]
I am not sure if I understand you correctly. Can you please explain your issue in more detail?

**Comment by ndebogory** [comment]
We have `wdio.conf.ts` like that:
```
beforeSuite: (): void => {
    browser.setWindowSize(1440, 900);
    ...
}
beforeTest: (test): void => {
    // here we set cookies for our environment - that is very important for us!
    ...
}
```
In test we want to use `beforeEach` hook, where specific cookies will be added. But the consequence of execution for test rewrite and delete them. Because `beforeEach` Mocha hook executes before `beforeTest` hook.

**Comment by christian-bromann** [comment]
Why can't you just use the `beforeTest` WebdriverIO hook?

**Comment by ndebogory** [comment]
We have a need for additional preconditions in some test suites, that can be executed foe every test it a suite. I can use `beforeTest` hook only once in `wdio.conf.ts`, isn't it?

**Comment by mgrybyk** [comment]
What do you mean by saying only once?

Closing the issue for now but we are happy to proceed conversation

**Comment by ndebogory** [comment]
We can use `beforeTest ` in `wdio.conf.ts`, but we cannt reuse it with some different set of actions inside function. So  can not have 2 different `beforeTest` for different test classes inside project.

**Comment by christian-bromann** [comment]
@ndebogory you can export the function of `beforeTest` to use it anywhere else.

**Comment by mvindahl** [comment]
We are facing the same issue. Having instrumented our code with simple console.log statements, we see the following order of execution.
```
executing MyTest::beforeEach
executing wdio.conf.js::beforeTest
executing MyTest::test1
executing MyTest::beforeEach
executing wdio.conf.js::beforeTest
executing MyTest::test2
```
In our specific case we have a profile which sets the browser URL to the root of our web app and we have a beforeEach function which depends upon the browser pointing to the right place. I was surprised to discover that MyTest::beforeEach would be executed before wdio.conf.js::beforeTest.

Since I'm unaware of any way to hook in before our beforeEach, this will be our workaround:
```
describe('MyTest', () => {
  // Handling beforeEach as workaround for: https://github.com/webdriverio/webdriverio/issues/4806
  const _beforeEach = async () => {
    // do stuff
  };

  it('should be nice', async () => {
    await _beforeEach();
    // do stuff
  });

  it('should not be naughty', async () => {
    await _beforeEach();
    // do stuff
  });
});
```

**Comment by mgrybyk** [comment]
@mvindahl beforeTest executes before a test, not before a hook, nothing to be surprised with.
Use beforeHook if you want something to be executed before a hook.

The code example you have can be easily replaced with mocha beforeEach

**Comment by mvindahl** [comment]
Ah.. thanks for correcting me. Will try beforeHook() instead.
