### ISSUE TITLE
Reporter.onHookEnd not called if beforeEach- or afterEach-hook throws error

### ISSUE THREAD

**Issue by akloeber** [webdriverio/webdriverio#4807]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 5.16.9]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync]
 - **Node.js version:** [e.g. 10.16.3]
 - **NPM version:** [e.g. 6.9.0]
 - **Browser name and version:** [e.g. Chrome 78]
 - **Platform name and version:** [e.g. Mac OS 10.15.1]
 - **Additional wdio packages used (if applicable):**
```
❯ yarn list --pattern wdio
yarn list v1.19.1
├─ @wdio/cli@5.16.9
├─ @wdio/config@5.16.6
├─ @wdio/dot-reporter@5.16.5
├─ @wdio/local-runner@5.16.9
├─ @wdio/logger@5.16.5
├─ @wdio/mocha-framework@5.16.5
├─ @wdio/protocols@5.16.7
├─ @wdio/repl@5.16.5
├─ @wdio/reporter@5.15.2
├─ @wdio/runner@5.16.9
├─ @wdio/spec-reporter@5.16.5
├─ @wdio/sync@5.16.9
├─ @wdio/utils@5.16.5
└─ wdio-chromedriver-service@5.0.2
```

**Config of WebdriverIO**
```ts
import HookReporter from './hook-reporter'

const config = {
    runner: 'local',
    path: '/',
    specs: ['./test/specs/*.ts'],
    capabilities: [{
        browserName: 'chrome',
    }],
    logLevel: 'silent',
    baseUrl: 'http://localhost',
    services: ['chromedriver'],
    framework: 'mocha',
    reporters: [
        'spec',
        HookReporter,
    ],
    mochaOpts: {
        require: [
            'tsconfig-paths/register'
        ]
    },
};
export {config}
```

**Describe the bug**
A reporter's `onHookEnd`-callback is not invoked, if a `beforeEach`- or `afterEach`-hook throws an error. As a consequence, reporters are not able to provide error details about failed hooks.

**To Reproduce**
Create the following test case:
```ts
describe('suite A', () => {

  beforeEach(() => {
    throw new Error('Hook error');
  });

  it('should succeed', () => {
    // noop
  });

});
```

Run the test with the following reporter:
```ts
export default class HookReporter extends WDIOReporter {
    onHookStart = (hookStats: any) => console.log('HookReporter:onHookStart', hookStats.uid);
    onHookEnd = (hookStats: any) => console.log('HookReporter:onHookEnd  ', hookStats.uid);
}
```

**Expected behavior**
The reporter's `onHookEnd`-callback should be invoked with HookStats that describe the error that has been thrown in the hook.

**Log**
```
[0-0] RUNNING in chrome - /test/specs/basic.ts
[0-0] HookReporter:onHookStart hook-0-0
[0-0] HookReporter:onHookEnd   hook-0-0
[0-0] HookReporter:onHookStart hook-00-0
[0-0] Error in "suite A "before each" hook for "should succeed""
Hook error
[0-0] HookReporter:onHookStart hook-0-1
[0-0] HookReporter:onHookEnd   hook-0-1
[0-0] FAILED in chrome - /test/specs/basic.ts
```

-> The `onHookEnd`-call for `hook-00-0` is missing.

**Additional context**

There is only an issue with `beforeEach`and `afterEach`. `before` and `after` behave as expected. This is the output if `before` ist used instead:

```
[0-0] RUNNING in chrome - /test/specs/basic.ts
[0-0] HookReporter:onHookStart hook-0-0
[0-0] HookReporter:onHookEnd   hook-0-0
[0-0] HookReporter:onHookStart hook-00-0
[0-0] Error in "suite A "before all" hook for "should succeed""
Hook error
[0-0] HookReporter:onHookEnd   hook-00-0
[0-0] HookReporter:onHookStart hook-0-1
[0-0] HookReporter:onHookEnd   hook-0-1
[0-0] FAILED in chrome - /test/specs/basic.ts
```

**Comment by mgrybyk** [comment]
I don't think it's a defect but is the way how Mocha works.
If beforeEach or afterEach hook fails it fails the test itself

**Comment by akloeber** [comment]
The issue is not about the test case itself. It is correct that the test case fails.

The problem is, that for the hook which throws the error only `onHookStart` is called on the reporter but the corresponding `onHookEnd` is missing. With `before`-hook it works as expected and `onHookEnd` is called with a `HookStats`-object that contains information about the error.

This makes it impossible track all failed hooks and list them in generated reports.

__A little bit more background:__
We have this issue with `wdio-mochawesome-reporter` which unfortunately does not track hooks at all. Right now I'm using an extended version that respects hooks but due to this issue I'm not able to track errors in `beforeEach`-hooks correctly. I don't think that this is a limitation of Mocha itself as with vanilla Mocha in conjunction with the mochawesome reporter I get a correct report for the test case above.
