### ISSUE TITLE
Issue with performance in IE11

### ISSUE THREAD

**Issue by pk-saxena** [webdriverio/webdriverio#4816]
Has anyone faced performance issues running tests in IE11? I know it could be an issue with 32 bit IEDriver that I am using but also quite possible that its wdio framwework issue. 
So I want to check if anyone else faced similar issue using webdriverio to run tests in IE11? 
To give an idea my tests in IE11 are 20x slower compared to chrome. I expect IE tests to be slower but this level of slowness is a matter of concern. 

**Things I am doing:**

    1. Using css selectors

    2. Using 32 bit IE driver (3.14.0) in 64 bit windows 10 machine.

    3. The capabilities object which is being used:
    capabilities: [
    {
    browserName: 'internet explorer',
    platformName: 'WINDOWS',
    logLevel: debug,
    'se:ieOptions': {
    'ie.ensureCleanSession': true,
    'ie.requireWindowFocus': true,
    'ie.enablePersistentHover': false,
    'ie.nativeEvents': false,
    ignoreZoomSetting: true,
    ignoreProtectedModeSettings: true
    }
    }
    ]

**Environment:**
 - **WebdriverIO version:** 5.11.0
 - **Mode:** WDIO Testrunner
 - **Node.js version:** 10.7.0
 - **Browser name and version:** IE11
 - **Platform name and version:** Windows 10

**Additional context**
From infrastructure standpoint, our UI tests are executed against localhost. So its not a publicly accessible url. We are exposing port 3000 in our local machine to be accessible to a remote windows instance in AWS. This is done through dynamic port forwarding with ssh.

**Comment by mgrybyk** [comment]
This is the issue with IEDriver
