### ISSUE TITLE
element - saveScreenshot

### ISSUE THREAD

**Issue by ff-franciscotavares** [webdriverio/webdriverio#4820]
I've updated the chrome version from 74 to other else above (e.g v.78) recently.

Now when I use [saveSreenshot](https://webdriver.io/docs/api/element/saveScreenshot.html) method to take a screenshot to the element, I'll get only what's under my viewport instead of all my element.

Let's imagine my element size has width:1000, height:700 if my viewport is (800,600), the screenshot will be ~800,600, instead of 1000,700.

It means that take a screenshot on the browser or element is exactly the same, when the element is bigger than the viewport. It doesn't happen on chrome v.74

**Comment by christian-bromann** [comment]
@ff-franciscotavares sorry this is something that can not be fixed in WebdriverIO. It only sends along the command to the browser and just passes through what it gets from it.
