### ISSUE TITLE
Why I don't have uploadFile function for non-chrome browsers using BrowserStack?

### ISSUE THREAD

**Issue by soswow** [webdriverio/webdriverio#4826]
**Describe your question with as much detail as possible**
When running my tests against Browserstack I get `TypeError: this.browser.uploadFile is not a function` for all but Chrome browsers for some reason. I am not sure if it's webdriverio's problem or BrowserStack one. Documentation says
> Note: that this command is only supported if you use a Selenium Hub or Chromedriver directly.

And I assumed browserstack uses Selenium Hub. What I might be missing here?

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.7.14,
 - **Mode:** Browserstack
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** v10.13.0
 - **NPM version:** v6.4.1
 - **Browser name and version:** IE, Firefox, Chrome (on Windows), Safari (on Mac)

**Comment by christian-bromann** [comment]
> And I assumed browserstack uses Selenium Hub. What I might be missing here?

Please reach out to the Browserstack support and ask if they support this endpoint. Currently it is only known that Selenium Hub or Chromedriver directly support it.

Happy re-open in case Browserstack supports it.

**Comment by soswow** [comment]
For other users who might find this, it was fixed in `5.11.0`
