### ISSUE TITLE
browser.getLogTypes fails when using selenium instead of chromedriver

### ISSUE THREAD

**Issue by Kignuf** [webdriverio/webdriverio#4827]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.16.10
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.12.0
 - **NPM version:** 6.13.0
 - **Browser name and version:** Chrome 78
 - **Platform name and version:** OSX 10.14.6
 - **Additional wdio packages used (if applicable):** @wdio/cucumber-framework, @wdio/selenium-standalone-service, @wdio/spec-reporter

**Config of WebdriverIO**
```javascript
exports.config = {
    //
    // ====================
    // Runner Configuration
    // ====================
    //
    runner: 'local',
    path: '/wd/hub',
    specs: [
        './features/**/*.feature'
    ],
    exclude: [],
    maxInstances: 10,
    capabilities: [{
        maxInstances: 5,
        browserName: 'chrome',
    }],
    //
    // ===================
    // Test Configurations
    // ===================
    logLevel: 'info',
    bail: 0,
    baseUrl: 'http://localhost:3000/',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    services: ['selenium-standalone'],
    outputDir: './logs',
    framework: 'cucumber',
    reporters: ['spec'],
    // If you are using Cucumber you need to specify the location of your step definitions.
    cucumberOpts: {
        require: ['./features/step-definitions/**/*.js'],        // <string[]> (file/dir) require files before executing features
        backtrace: false,   // <boolean> show full backtrace for errors
        requireModule: [],  // <string[]> ("extension:module") require files with the given EXTENSION after requiring MODULE (repeatable)
        dryRun: false,      // <boolean> invoke formatters without executing steps
        failFast: false,    // <boolean> abort the run on first failure
        format: ['pretty'], // <string[]> (type[:path]) specify the output format, optionally supply PATH to redirect formatter output (repeatable)
        colors: true,       // <boolean> disable colors in formatter output
        snippets: true,     // <boolean> hide step definition snippets for pending steps
        source: true,       // <boolean> hide source uris
        profile: [],        // <string[]> (name) specify the profile to use
        strict: false,      // <boolean> fail if there are any undefined or pending steps
        tagExpression: '',  // <string> (expression) only execute the features or scenarios with tags matching the expression
        timeout: 60000,     // <number> timeout for step definitions
        ignoreUndefinedDefinitions: false, // <boolean> Enable this config to treat undefined definitions as warnings.
    },
}
```

**Describe the bug**
Webdriverio is trying to gather logs from selenium server, but fails to do so.
```
2019-11-28T13:40:09.686Z INFO webdriver: COMMAND getLogTypes()
2019-11-28T13:40:09.686Z INFO webdriver: [GET] http://127.0.0.1:4444/wd/hub/session/323c119de7d8ae2edb534da562ac1819/se/log/types
2019-11-28T13:40:09.691Z WARN webdriver: Request failed due to unknown command: session/323c119de7d8ae2edb534da562ac1819/se/log/types
```

**To Reproduce**
Steps to reproduce the behaviour:
It is rather straight forward. There are two main criteria involved:
* `config.outputDir` should be string, it must not be undefined.
* You should target a selenium server, using selenium-service is the easiest way

Setup a new project and chose to add selenium-standalone service, use the above configuration. Run tests and read logs in wdio-0-0.log

**Expected behaviour**
Calls to `browser.getLogTypes()` and `browser.getLog(<type>)` should not fail.

**Additional context**
It seems the bug was introduced by  #4299, which works when using chromedriver, but does not seem compatible with selenium.
Doing a manual curl to http://localhost:4444/wd/hub/session/_sessionId_/log/types works fine, the culprit is the additional **/se** in the url (which you can see in the logs I've added to the 'describe the bug section').

**Comment by mgrybyk** [comment]
please use latest **chromedriver** in combination with chrome 78, see selenium standalone docs on https://webdriver.io (guides)

**Comment by AdeelZahir** [comment]
@mgrybyk How to update chromedriver when we are using selenium-standalone serive?

**Comment by mgrybyk** [comment]
See selenium standalone docs @AdeelZahir
