### ISSUE TITLE
[wdio-cli]: Allow custom config name or path in install command

### ISSUE THREAD

**Issue by baruchvlz** [webdriverio/webdriverio#4832]
Currently when trying to use `wdio install` and the config file is not named `wdio.conf.js` or is located in a different folder, the command would fail. This is happening because we're [hardcoding the name](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-cli/src/commands/install.js#L78)

**Possible solution**

Allow user to pass the name or path of their configuration file to the command in case it's different from default:

```bash
$ wdio install service chromedriver --config="./myconf.js" 
# or
$ wdio install service chromedriver --config="./path/to/confi.file.js" 
```

**Comment by christian-bromann** [comment]
> Allow user to pass the name or path of their configuration file to the command in case it's different from default:

Sounds good to me, let's ensure this parameter is only valid for the `install` command.
