### ISSUE TITLE
[wdio-spec-reporter]: SessionID missing in wdio 5

### ISSUE THREAD

**Issue by Smashman** [webdriverio/webdriverio#4834]
Good afternoon,
We have recently upgraded from wdio 4 -> wdio 5 and we have noticed that the @wdio/spec-reporter is no longer reporting the Session ID.
Does anyone know if this is an intentional change, or a mistake?
I am happy to create a PR to add this feature back in, as I have managed to branch and do so, just wanted to check if this was intentional before I did so.

Session ID can be seen here in the boneyard spec-reporter: https://github.com/webdriverio-boneyard/wdio-spec-reporter/blob/master/lib/reporter.js#L305
But is completely missing from the current version of the spec reporter: https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-spec-reporter/src/index.js#L129

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.10.16
 - **Mode:** -
 - **If WDIO Testrunner, running sync/async:** -
 - **Node.js version:** 12.13.10
 - **NPM version:** 6.12.0
 - **Browser name and version:** Chrome
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/spec-reporter

Thanks.

**Comment by christian-bromann** [comment]
I will fix that as part of #4833

**Comment by Smashman** [comment]
@christian-bromann, I'm afraid that #4833 did not resolve this issue.
In non-`Multiremote` mode, `sessionId` is not added to `capabilities` here: https://github.com/webdriverio/webdriverio/pull/4833/files#diff-dca4ef3e3d12bbf097372d8409e1d9aeR132

As such, I believe that `wdio-runner/src/index.js:135` should be `: {...browser.capabilities, sessionId: browser.sessionId},` or similar.

Happy to make a PR if you do not want to make this change.

Thanks.

**Comment by christian-bromann** [comment]
> In non-`Multiremote` mode, `sessionId` is not added to `capabilities` here:

In non multiremote we are having multiple sessions for one spec file. How should this look like in your opinion?

**Comment by Smashman** [comment]
Is that the case with `@wdio/sync`?
I'm able to extract one `sessionId` per spec file in our environment.

**Comment by christian-bromann** [comment]
Without multiremote the spec report looks as follows:

```js
------------------------------------------------------------------
[loremipsum #0-0] Spec: /foo/bar/baz.js
[loremipsum #0-0] Running: loremipsum
[loremipsum #0-0] Session ID: foobar
[loremipsum #0-0]
[loremipsum #0-0] Foo test
[loremipsum #0-0]    green ✓ foo
[loremipsum #0-0]    green ✓ bar
[loremipsum #0-0]
[loremipsum #0-0] Bar test
[loremipsum #0-0]    green ✓ some test
[loremipsum #0-0]    red ✖ a failed test
[loremipsum #0-0]    red ✖ a failed test with no stack
[loremipsum #0-0]
[loremipsum #0-0] Baz test
[loremipsum #0-0]    green ✓ foo bar baz
[loremipsum #0-0]    cyan - a skipped test
[loremipsum #0-0]
[loremipsum #0-0] green 4 passing (5s)
[loremipsum #0-0] red 1 failing
[loremipsum #0-0] cyan 1 skipped
[loremipsum #0-0]
[loremipsum #0-0] 1) Bar test a failed test
[loremipsum #0-0] red expected foo to equal bar
[loremipsum #0-0] gray Failed test stack trace
[loremipsum #0-0]
[loremipsum #0-0] 2) Bar test a failed test with no stack
[loremipsum #0-0] red expected foo to equal bar
[loremipsum #0-0]
[loremipsum #0-0] Check out job at https://app.eu-central-1.saucelabs.com/tests/ba86cbcb70774ef8a0757c1702c3bdf9
```

How it should look for multiremote then?

**Comment by Smashman** [comment]
Perhaps we can discuss this on Gitter? I think we're getting crossed wires, here.
