### ISSUE TITLE
Property 'setupInterceptor' does not exist on type 'BrowserObject'.

### ISSUE THREAD

**Issue by annu13aquar** [webdriverio/webdriverio#4839]
**Environment information:**

"wdio-chromedriver-service": "^5.0.2",
"wdio-intercept-service": "^3.0.2",
 "webdriverajax": "^2.2.0",
 "@wdio/allure-reporter": "^5.10.10",
 "@wdio/cli": "^5.12.5",
 "@wdio/devtools-service": "^5.16.10",
 "@wdio/local-runner": "^5.10.10",
 "@wdio/mocha-framework": "^5.10.10",
 "@wdio/spec-reporter": "^5.15.2",
 "@wdio/sync": "^5.12.3"

**wdio config**

exports.config = {
  runner: 'local',
  hostname: 'localhost',
  path: '/', // Override default path ('/wd/hub') for chromedriver service.
  specs: [''],
  exclude: [
    // 'path/to/excluded/files'
  ],
  // adding wdio-intercept-service to intercept http calls

  capabilities: [
    {
      browserName: 'chrome',
      maxInstances: 1,
      'goog:chromeOptions': {
        // to run chrome headless the following flags are required
        // (see https://developers.google.com/web/updates/2017/04/headless-chrome)
        // args: ['--kiosk'],
       args: ['--headless', '--no-sandbox', '--disable-gpu', '--whitelisted-ips', '--window-size=1920,1080'],
      },
    },
  ],
  plugins: {
    webdriverajax: {}
  },

  maxInstances: 1,
  // Level of logging verbosity: trace | debug | info | warn | error
  logLevel: 'error',
  logLevels: {
    webdriver: 'error',
  },
  baseUrl: 'http://localhost:4204',
  waitforTimeout: 5000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  services: ['chromedriver', 'intercept'],
  framework: 'mocha',
  reporters: [
    'spec',
    [
      'allure',
      {
        outputDir: 'e2e/allure-results',
        disableWebdriverStepsReporting: false,
        disableWebdriverScreenshotsReporting: false,
      },
    ],
  ],
  mochaOpts: {
    ui: 'bdd',
    timeout: 60000,
    //  timeout:  (24 * 60 * 60 * 1000) // use this for debugging mode: put browser.debug()and npm run test:e2e --inspect to get it working
  },
  onPrepare: function(config, capabilities) {},
  afterTest: function(test) {
    if (test.error !== undefined) {
      browser.takeScreenshot();
    }
  },
  afterSession: async function() {
    // workaround to make sure the chromedriver shuts down
    try {
      if (browser && browser.sessionId) {
        await browser.deleteSession();
      }
    } catch (err) {
      console.log(err);
    }
  },
};

**Comment by mgrybyk** [comment]
Can you please be more specific? How to reproduce the issue? Are there any errors in logs saying that service has failed to start?

**Comment by youngckuw** [comment]
Not sure if this was reproduced using TypeScript but same result can be seen when using TypeScript. https://github.com/chmanie/wdio-intercept-service/issues/64

**Comment by chmanie** [comment]
v4.0.0 of the wdio-intercept-service comes with TypeScript support: https://github.com/chmanie/wdio-intercept-service/releases/tag/v4.0.0
