### ISSUE TITLE
Why the parameters of callback is error plus response ?

### ISSUE THREAD

**Issue by freizl** [webdriverio/webdriverio#484]
By default, callback for each command has parameters `error, body`.
https://github.com/webdriverio/webdriverio/blob/master/lib/utils/RequestHandler.js#L223

Could you like to share its design intention.

According to the API doc,
> callback function that contains command results and gets called when the command finishes

I though it's first parameter for response and it's null actually (no error). and I though it could be either bug to my testing scripts or bug to webdriverio until I dig into source code.
It looks like not a _common sense_.

**Comment by DavidCaabeiro** [comment]
This is standard practice in node.js, check https://docs.nodejitsu.com/articles/errors/what-are-the-error-conventions or any other book or tutorial.

**Comment by christian-bromann** [comment]
@freizl check out http://webdriver.io/guide/usage/bindingscommands.html

also @DavidCaabeiro thanks for clarifying

**Comment by freizl** [comment]
Thank you so much!!
