### ISSUE TITLE
Loglevel silent continues to write to message to console logs 

### ISSUE THREAD

**Issue by AutomationGuru** [webdriverio/webdriverio#4840]
Given i have wdio config updated with 
logLevel: 'silent' and maxInstance populated to more than 1
When i run all the specs
then i see the output does show me every time a spec is started/retried/passed

`[0-0] RUNNING in chrome - /tests/selenium/specs/1.spec.js
[0-0] PASSED in chrome - /tests/selenium/specs/1.spec.js`

Expected:  as we have silent log level we should not see that

**Comment by mgrybyk** [comment]
Thanks for submitting, we have discussion here https://github.com/webdriverio/webdriverio/issues/4547
