### ISSUE TITLE
isEnabled() returns true on paper-button disabled

### ISSUE THREAD

**Issue by lacell75** [webdriverio/webdriverio#4841]
*Environment (please complete the following information):**
 - **WebdriverIO version:** 5.16.10
 - **Mode:** WDIO
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.6.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** chrome/firefox/edge
 - **Platform name and version:**  Windows 10
 - **Additional wdio packages used (if applicable):** "@wdio/cli": "^5.16.9",
    "@wdio/cucumber-framework": "^5.16.9",
    "@wdio/dot-reporter": "^5.16.5",
    "@wdio/local-runner": "^5.16.9",
    "@wdio/mocha-framework": "^5.16.5",
    "@wdio/selenium-standalone-service": "^5.16.5",
    "@wdio/spec-reporter": "^5.16.5",
    "@wdio/sync": "^5.16.10",

**Describe the bug**
- isEnable() returns true while the button is disabled

**To Reproduce**
```
describe('Check if button is disabled', () => {
  it('Check if button is disabled'', () => {
    browser.url('https://codepen.io/phasjim/pen/oZgYWB');
    browser.switchToFrame(0);
    const button = browser.$('paper-button:nth-of-type(2)');
    button.waitForDisplayed(10000);
    console.log(button.isEnabled()); // true
    console.log(button.getHTML());
  });
});
```

**Expected behavior**
Should return false as element is clearly disabled

**Log**

```
[0-0] RUNNING in chrome - C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\features\test.feature
[0-0] true
[0-0] <paper-button disabled="">Disabled Paper Button</paper-button>
```

**Comment by mgrybyk** [comment]
Looks like paper button is not a standard element. You have to write your own function to identify if it's enabled or not.

**Comment by lacell75** [comment]
paper button is a polymer element https://www.webcomponents.org/element/@polymer/paper-button.
It is not a custom or craft element. I think it would be nice to support

**Comment by christian-bromann** [comment]
> I think it would be nice to support these elements

I absolutely agree. I don't think so that this is a defect. It would be more an plugin or a service that simplifies the interaction with Polymer elements. Any contributions in this area would be highly appreciated.

**Comment by lacell75** [comment]
Maybe I can contribute to that, but I need you to define how to do it.
