### ISSUE TITLE
A session is either terminated or not started with latest @wdio/appium-service 

### ISSUE THREAD

**Issue by meruga92** [webdriverio/webdriverio#4844]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.16.11
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.16.3
 - **NPM version:** 6.9.0
 - **Browser name and version:** ANDROID NATIVE
 - **appium version:** 1.15.1
 - **Additional wdio packages used (if applicable):** @wdio/appium-service

**Config of WebdriverIO**
```javascript
  runner: 'local',
  port: 4723,
 services: ['selenium-standalone', 'appium'],
  appium: {
    logPath: './',
    args: {
      address: '127.0.0.1',
      port: 4723,
    },
  },
  capabilities: [{
    app: appPath,
    avd: 'Pixel_XL_API_P',
    deviceName: 'emulator-5554',
    platformVersion: '26',
    platformName: 'android',
    automationName: 'uiautomator2',
    systemPort: Math.floor(Math.random() * (8200 - 8100 + 1)) + 8100,
    avdArgs: '-wipe-data',
  }],
```

**Describe the bug**
Not able to run appium tests with latest version of @wdio/appium-service
Which is weird because it used to work for previous versions
It launches the app on the device and then I get an error message saying `Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started`

I tried by disabling `appium-service` and started using appium-desktop and it worked fine

**Log**
https://gist.github.com/meruga92/b4977d1dc5a7fdc2162dacbfdfbe38fd

**Comment by christian-bromann** [comment]
This is an issue related to Appium and can't be fixed in WebdriverIO. Please create a ticket in the Appium project.

**Comment by meruga92** [comment]
I dont think the issue is with appium because it works fine when i remove ['appium'] from services and start a another instance of appium from terminal

**Comment by mgrybyk** [comment]
Do you have appium installed locally? If you you have to point appium service to global appium.
Are there any other errors in logs?
Have you tried running service without your config?

**Comment by meruga92** [comment]
I dont have any local instance of appium, but i tried installing latest version and used `  command: "appium",` in the appium config to use global instance but then i got this error
```
2019-12-02T20:29:26.278Z ERROR @wdio/appium-service: appium is not installed locally.
If you use globally installed appium please add
appium: { command: 'appium' }
to your wdio.conf.js!
```
Other solution i tried is by removing `appium` from services in the config and started a local instance and tried running then the test ran as expected.

you can look for log here: https://gist.github.com/meruga92/b4977d1dc5a7fdc2162dacbfdfbe38fd#file-appium_service_crash_latest_version-L288

**Comment by christian-bromann** [comment]
> I dont think the issue is with appium because it works fine when i remove ['appium'] from services and start a another instance of appium from terminal

It could be that the local Appium has a different version than the one installed by the service. From what I see in the logs is that Appium is started by the service successfully which is all the service is doing.

**Comment by meruga92** [comment]
no local appium version is present and also even if there is another version in local it will use that only if I use the `command: 'appium'` in the config.
appium-service successfully creates a new session and launches the app but as soon as the app is launched the session is crashed with message `Unexpected shutdown`
https://gist.github.com/meruga92/b4977d1dc5a7fdc2162dacbfdfbe38fd#file-appium_service_crash_latest_version-L289

**Comment by christian-bromann** [comment]
@meruga92 not sure why it shuts down like that but I can't connect it to WebdriverIO being responsible for it. Can you help us finding the reason for the shutdown?

**Comment by yukinotech** [comment]
I use `wdio@cli` and `wdio.conf.js` and `appium`.
I have the same problem, only when I use appium Desktop,appium server can work successfully. If I use `yarn add global appium` and start appium server with `appium`.
then I run `./node_modules/.bin/wdio wdio.conf.js`
then session will `Unexpected shutdown`.

version
```
"appium":"1.15.1"
"@wdio/appium-service": "^5.16.11",
"@wdio/cli": "^5.16.15",
"@wdio/jasmine-framework": "^5.16.15",
"@wdio/local-runner": "^5.16.15",
"@wdio/spec-reporter": "^5.16.11",
"@wdio/sync": "^5.16.15",
```

**Comment by yukinotech** [comment]
> no local appium version is present and also even if there is another version in local it will use that only if I use the `command: 'appium'` in the config.
> appium-service successfully creates a new session and launches the app but as soon as the app is launched the session is crashed with message `Unexpected shutdown`
> https://gist.github.com/meruga92/b4977d1dc5a7fdc2162dacbfdfbe38fd#file-appium_service_crash_latest_version-L289

I have the same problem,but i cant use appium desktop version because i have to run appium server on a linux server , I have to use node to run it. Do you know which version can work?

**Comment by meruga92** [comment]
I think i found what is the issue here. I have two config files of which one is main config and the other is sub config and in the subconfig i have the configuration regarding appium and i think it need to override the parent config but it is not so i removed it from the sub config and put that in parent config and that worked
