### ISSUE TITLE
Devtools: upgrade puppeteer-core to v2

### ISSUE THREAD

**Issue by dylang** [webdriverio/webdriverio#4848]
**Is your feature request related to a problem? Please describe.**

`@types/puppeteer-core` v1's package.json imports `puppeteer@*`, so it's getting the v2 API, which is not what we're exporting in `devtools`. 

**Describe the solution you'd like**

* Upgrade to puppeteer-core v2.

**Describe alternatives you've considered**

`yarn` lets us overwrite the version it installs using `resolutions` field in our package.json, but this feels like a hack.

**Additional context**
*  https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/puppeteer-core/index.d.ts
* No package.json to specify the version, so DefinitelyTyped uses `*` when publishing.

**Comment by dylang** [comment]
Can we do include this for the v6 release?

Puppeteer v2.1.0 now includes Firefox support too.

**Comment by pmerwin** [comment]
FYI: I found 2.1 breaks the devtools backend ->

https://github.com/webdriverio/webdriverio/issues/4982#issuecomment-580662104

**Comment by pmerwin** [comment]
Puppeteer-core 2.1.1 is working, so I think we can go fo to that.

**Comment by christian-bromann** [comment]
Let's continue convo in #4997
