### ISSUE TITLE
Devtools: Close browser when process is killed.

### ISSUE THREAD

**Issue by dylang** [webdriverio/webdriverio#4850]
**Is your feature request related to a problem? Please describe.**

Hit control-c while tests are running. All the browsers stay open until manually closed.

**Describe the solution you'd like**

Handle it like Puppeteer Launcher does.

https://github.com/puppeteer/puppeteer/blob/master/lib/Launcher.js#L95-L152

**Describe alternatives you've considered**

I tried calling browser.close but that's async so it doesn't work.

**Comment by christian-bromann** [comment]
@dylang I can't reproduce it. The browser closes for me (see Chrome Canary logo not showing up anymore):

![cdp2](https://user-images.githubusercontent.com/731337/70224452-951f5280-174d-11ea-9d78-bef194765891.gif)

**Comment by dylang** [comment]
@christian-bromann Thanks for giving that a try!

I should have specified that I am using 

```
automationProtocol: 'devtools'
```

but not `wdio-devtools-service` because I'm using a custom Jest test proxy.

**Comment by christian-bromann** [comment]
> I should have specified that I am using

I did in the example showed by the screenshot too.

**Comment by christian-bromann** [comment]
Closing as it was not reproducible. Happy to re-open if people still run into this issue.
