### ISSUE TITLE
Access number of retries per test automatically 

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#4851]
**Is your feature request related to a problem? Please describe.**

If someone would be interested how often the retry happened within the test he would have to build his own counter. Given that we have the data we should provide that data automatically.

**Describe the solution you'd like**
Add number of retries to the function scope , e.g. `this.retries`

**Describe alternatives you've considered**
none.

**Comment by mgrybyk** [comment]
You want to have it in a test scope? I think we have such counter already in after test hook

**Comment by christian-bromann** [comment]
The use case here is that the user wants to access the amount of retries within the test. I don't think it is a big issue to attach it to the framework function scope.

**Comment by christian-bromann** [comment]
fixed in #4853
