### ISSUE TITLE
executeAsync not working correctly in IE11 inside BrowserStack in async mode

### ISSUE THREAD

**Issue by vrockai** [webdriverio/webdriverio#4855]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** ^5.16.11
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** v11.13.0
 - **NPM version:** 6.13.1
 - **Browser name and version:** IE11
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** [@wdio/browserstack-service, @wdio/spec-reporter]

**Config of WebdriverIO**
```json
{
  "runner": "local",
  "specs": [
    "./test/e2e/commands/async.spec.js"
  ],
  "exclude": [],
  "maxInstances": 3,
  "logLevel": "error",
  "bail": 0,
  "baseUrl": "https://www.google.com/",
  "waitforTimeout": 30000,
  "connectionRetryTimeout": 90000,
  "framework": "jasmine",
  "reporters": [
    "spec",
    [
      "junit",
      {
        "outputDir": "./reports"
      }
    ]
  ],
  "jasmineNodeOpts": {
    "defaultTimeoutInterval": 60000
  },
  "capabilities": [
    {
      "base": "BrowserStack",
      "browserstack.local": true,
      "browserName": "ie",
      "browserVersion": "11.0",
      "os": "Windows",
      "os_version": "10",
      "browser": "ie",
      "device": null,
      "browser_version": "11.0",
      "real_mobile": null,
      "project": "xxx",
      "build": "xxx"
    }
  ],
  "user": "****",
  "key": "****",
  "browserstackLocal": true,
  "services": [
    "browserstack"
  ]
}
```

**Describe the bug**
The `browser.executeAsync` doesn't work cprrectly with IE11 using `async` mode. It doesn't return the expected value passed to the `done` function and sometimes it executes its function several times. Often the title of the page is returned inside an array as the result of `browser.executeAsync`, i.e.: `["complete", "Google"]`.

**To Reproduce**
Simple test like:
```javascript
describe('Async', () => {
    beforeEach(() => {
        browser.url('');
    });

    it('should support async function', async () => {
        browser.setTimeout({ 'script': 10000 });
        const success = await browser.executeAsync(
            function(done) {
                setTimeout(function(){done('success')}, 2000);
            }
        );

        console.warn(JSON.stringify(success, null, '\t'));

        expect(success).toBe('success');
    });
});

```

**Expected behavior**
Passing test && the function inside `executeAsync` executed once.

**Log**
Spec report:
https://gist.github.com/vrockai/0fe35377fe85082ff89c16c63ac438db

**Additional context**
This problem is intermittent (cca 1 out of 10 runs pass) and only happens with IE11. It doesn't happen in other browsers. Only happens in the `async` mode. Sometimes the function inside `executeAsync` is run several times.

Complete set of my versions:
```json
"@wdio/browserstack-service": "^5.16.10",
    "@wdio/cli": "^5.16.11",
    "@wdio/jasmine-framework": "^5.16.11",
    "@wdio/junit-reporter": "^5.16.11",
    "@wdio/local-runner": "^5.16.11",
    "@wdio/spec-reporter": "^5.16.11",
    "@wdio/sync": "^5.16.11",
```

**Comment by christian-bromann** [comment]
Please reach out to the Browserstack support. It seems the way how IE is automated causes some problems here. Also are you sure that the value you return has no cross browser bugs? I unfortunately have to close this because such issues can't be fixed in WebdriverIO. I am happy to further assist though!

**Comment by vrockai** [comment]
thanks @christian-bromann , i've reached out to the browserstack support.
