### ISSUE TITLE
Run web test (WebdriverIO) and ios app test (Appium) in the same test

### ISSUE THREAD

**Issue by chirag-farfetch** [webdriverio/webdriverio#4865]
I am trying to automate test cases where I have to do some stuff in the mobile app then move to a desktop browser and do other stuff.

Mobile tests works, I can open a browser within the Simulator or automate the app.I have tried adding multiple configurations but it does not help

I have noticed that it is always using the Appium driver,  Is there a way to switch drivers? if there aren't any, what do you think is the best solution aside from rewriting the test cases themselves?

This is what I have so far:

Config file

```
const { join } = require('path');
const { config } = require('./wdio.shared.conf');

// ============
// Specs
// ============
config.specs = [
    './tests/specs/**/*.spec.js',
];


capabilities = [
    {
        // The defaults you need to have in your config
        browserName: 'chrome',
        url: 'http://localhost:5000',
        maxInstances: 1,
        smartWait: 5000,
    },
];

// ============
// Capabilities
// ============
// For all capabilities please check
// http://appium.io/docs/en/writing-running-appium/caps/#general-capabilities
config.capabilities = [
    {
        // The defaults you need to have in your config
        platformName: 'iOS',
        maxInstances: 1,
        smartWait: 5000,
        // For W3C the appium capabilities need to have an extension prefix
        // This is `appium:` for all Appium Capabilities which can be found here
        // http://appium.io/docs/en/writing-running-appium/caps/
        'appium:deviceName': 'iPhone 8',
        'appium:platformVersion': '12.4',
        'appium:orientation': 'PORTRAIT',
        // `automationName` will be mandatory, see
        // https://github.com/appium/appium/releases/tag/v1.13.0
        // The path to the app
        'appium:app': join(process.cwd(), './apps/iOS-Simulator-NativeDemoApp-0.2.1.app.zip'),
        // Read the reset strategies very well, they differ per platform, see
        // http://appium.io/docs/en/writing-running-appium/other/reset-strategies/
        'appium:noReset': true,
        'appium:newCommandTimeout': 240,
        "appium:platformName": "iOS",
        "appium:deviceName": "iPhone 8",
        "appium:bundleId": "com.farfetch.sof.shopfloor.chanel.debug",
    },
];

exports.config = config;
```

test case:

```
import ClientScreen from '../screenobjects/client.screen';
import SearchScreen from '../screenobjects/search.screen';
import HomeScreen from '../screenobjects/home.screen';
import FormScreen from '../screenobjects/forms.screen';
import CommonPage from '../pageobjects/common.page';

describe('Sending the item to the mirror successfully,', () => {

    beforeEach(() => {
        CommonPage.login()
    });

    afterEach(() => {
        CommonPage.logout()
    });

    it('should be able to send the item to the mirror', () => {
        ClientScreen.clientTab.click();
        ClientScreen.searchButon.click();
        ClientScreen.searchButon.setValue('tester@test.com')
        CommonPage.hideKeyboard()
        ClientScreen.customerlabelButton.click();
        driver.pause(5000)
        if (ClientScreen.assignmentButton.getText() == 'Assign to me') {
            ClientScreen.assignmentButton.click();
        };
        driver.pause(8000)
        ClientScreen.fittingRoomButton.touchAction('press')
        ClientScreen.mirrorName.click();
        ClientScreen.assignMirrorButton.click();
        HomeScreen.productsearchButton.click();
        driver.pause(3000)
        SearchScreen.handbags.click();
        driver.pause(3000)
        SearchScreen.viewAll.click()
        SearchScreen.actionListButton.click();
        FormScreen.alert.pressButton('Send to mirror');

    });

});

```

**Comment by mgrybyk** [comment]
You can do it for sure with Multiremote feature, see docs.

Also, you might need to use selenium grid for that (I haven't tried other approaches by myself) so that you can use single entry port, a grid that is running on port 4444 that would handle your nodes, either selenium standalone or appium.

**Comment by chirag-farfetch** [comment]
@mgrybyk , sorry but i am not following i tried following this - https://webdriver.io/docs/multiremote.html

But i am confused if i need to create a seprate conf.js?

**Comment by mgrybyk** [comment]
@chirag-farfetch start with something simple and follow the doc. Let's say start with firefox and chrome. If it works great!
Then try replacing one of the browsers with appium.
A gotcha here is to specify different ports for appium and browser driver (selenium standalone?)

**Comment by chirag-farfetch** [comment]
@mgrybyk , thank you i will try that and let you know if i face any issues

**Comment by chirag-farfetch** [comment]
@mgrybyk , i tried a small test but i am getting this following error

`Request failed due to connect ECONNREFUSED 127.0.0.1:4444
[0-0] 2019-12-10T23:36:40.062Z INFO webdriver: Retrying 2/3
[0-0] 2019-12-10T23:36:40.063Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2019-12-10T23:36:40.063Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { myChromeBrowser: [Object], myFirefoxBrowser: [Object] },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    myChromeBrowser: { desiredCapabilities: [Object] },
    myFirefoxBrowser: { desiredCapabilities: [Object] }
  }
}
2019-12-10T23:36:40.064Z INFO webdriver: Retrying 3/3
2019-12-10T23:36:40.064Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
2019-12-10T23:36:40.064Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { myChromeBrowser: [Object], myFirefoxBrowser: [Object] },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    myChromeBrowser: { desiredCapabilities: [Object] },
    myFirefoxBrowser: { desiredCapabilities: [Object] }
  }
}
[0-0] 2019-12-10T23:36:40.064Z WARN webdriver: Request failed due to connect ECONNREFUSED 127.0.0.1:4444
2019-12-10T23:36:40.065Z ERROR webdriver: Request failed due to Error: connect ECONNREFUSED 127.0.0.1:4444
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)
2019-12-10T23:36:40.066Z ERROR webdriver: Error: connect ECONNREFUSED 127.0.0.1:4444
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)
2019-12-10T23:36:40.066Z ERROR @wdio/runner: Error: Failed to create session.
Unable to connect to "127.0.0.1:4444", make sure browser driver is running on that address.`


This is what i tried:

Here is my wdio.config.js

`exports.config = {
    // Here are all of my common/default settings. Things like:
    baseUrl: "http://example.com",
    specs: [
        "test.js"
    ],
    capabilities: [{
        myChromeBrowser: {
            desiredCapabilities: {
                browserName: 'chrome'
            }
        },
        myFirefoxBrowser: {
            desiredCapabilities: {
                browserName: 'chrome'
            }
        }        
    }
]
    // and many other options found here: http://webdriver.io/guide/testrunner/configurationfile.html
};`


Here is my test file i wrote:

`describe('create article', function() {
    it('should do something with two browser', function () {
        browser.url('http://google.com');
        console.log(browser.getTitle()); // returns {myChromeBrowser: 'Google', myFirefoxBrowser: 'Google'}

        myFirefoxBrowser.url('http://yahoo.com');
        console.log(myFirefoxBrowser.getTitle()); // return 'Yahoo'

        console.log(browser.getTitle()); // returns {myChromeBrowser: 'Google', myFirefoxBrowser: 'Yahoo'}
    });
});`

and Here is my package.json and i have added all the information

`{
  "name": "appium-boilerplate",
  "version": "5.3.1",
  "description": "Run end to end tests with using the webapp and the mobile app",
  "scripts": {
    "android.sauce.rdc.app": "./node_modules/.bin/wdio ./config/saucelabs/wdio.android.rdc.app.conf.js",
    "android.app": "./node_modules/.bin/wdio ./config/wdio.android.app.conf.js",
    "android.browser": "./node_modules/.bin/wdio ./config/wdio.android.browser.conf.js",
    "ios.app": "./node_modules/.bin/wdio ./config/wdio.ios.app.conf.js",
    "ios.sauce.rdc.app": "./node_modules/.bin/wdio ./config/saucelabs/wdio.ios.rdc.app.conf.js",
    "ios.browser": "./node_modules/.bin/wdio ./wdio.conf.js",
    "real.browser": "./node_modules/.bin/wdio ./config/wdio.browser.conf.js",
    "lint": "eslint config tests"
  },
  "dependencies": {},
  "devDependencies": {
    "@babel/cli": "^7.5.5",
    "@babel/core": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "@babel/register": "^7.5.5",
    "@babel/traverse": "^7.5.5",
    "@babel/types": "^7.5.5",
    "@wdio/appium-service": "^5.12.1",
    "@wdio/cli": "^5.12.4",
    "@wdio/jasmine-framework": "^5.16.15",
    "@wdio/local-runner": "^5.16.15",
    "@wdio/mocha-framework": "^5.16.15",
    "@wdio/sauce-service": "^5.12.1",
    "@wdio/spec-reporter": "^5.16.11",
    "@wdio/sync": "^5.16.15",
    "babel-eslint": "^10.0.2",
    "chromedriver": "^78.0.1",
    "eslint": "^5.16.0",
    "eslint-config-standard": "^12.0.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-node": "^7.0.1",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1",
    "eslint-plugin-wdio": "^5.12.1",
    "mocha": "^6.2.2",
    "node-fetch": "^2.3.0",
    "spectron": "^9.0.0",
    "wdio-chromedriver-service": "^5.0.2",
    "webdriverio": "^5.12.4"
  }
}`

I am not able to figure out what is wrong

**Comment by christian-bromann** [comment]
> Error: connect ECONNREFUSED 127.0.0.1:4444

Please make sure you run a browser driver, e.g. via `wdio-chromedriver-service`.

**Comment by chirag-farfetch** [comment]
@christian-bromann , i added that in my dependency and also added a service in my code but still the same issue:

```
exports.config = {
	// Here are all of my common/default settings. Things like:
	baseUrl: "http://example.com",
	specs: [
    	"test.js"
    ],
    services: ['chromedriver'],
    capabilities: [{
        myChromeBrowser: {
            desiredCapabilities: {
                browserName: 'chrome'
            }
        },
        myFirefoxBrowser: {
            desiredCapabilities: {
                browserName: 'safari'
            }
        }        
    }
]
	// and many other options found here: http://webdriver.io/guide/testrunner/configurationfile.html
};
```

**Comment by mgrybyk** [comment]
@chirag-farfetch the issue here is that you have to run appium and selenium standalone (chromedriver) on different ports.
And then connect to different posts.

**Comment by mgrybyk** [comment]
Also, chromedriver is only for chrome, you need selenium standalone for running both chrome and firefox

**Comment by chirag-farfetch** [comment]
@mgrybyk , i am confused here. But the tutorial here does not talk anything about standalone selenium. I am following this tutorial and trying to run exactly as this - https://webdriver.io/docs/multiremote.html

**Comment by mgrybyk** [comment]
It does talk only about multiremote. It is assumed that you are already able to run tests in chrome and firefox, and just want to run them in multiremote mode.

**Comment by chirag-farfetch** [comment]
@mgrybyk , i tried to change my config.js but not sure if i am going in a right direction

```
exports.config = {
    runner: 'local',
    //
    specs: [
        'test.js'
    ],
    //
    exclude: [
        // 'path/to/excluded/files'
    ],
    //
    maxInstances: 2,
    //
    capabilities: [{
        myChromeBrowser: {
            desiredCapabilities: {
                browserName: 'chrome'
            }
        },
        myFirefoxBrowser: {
            desiredCapabilities: {
                browserName: 'firefox'
            }
        }
    },
],
    //
    logLevel: 'trace',
    //
    deprecationWarnings: true,
    //
    bail: 0,
    //
    baseUrl: 'google.com/',
    //
    waitforTimeout: 10000,
    //
    connectionRetryTimeout: 90000,
    //
    connectionRetryCount: 3,
    //
    services: ['selenium-standalone'],
    //
    framework: 'jasmine',
    //
    //
}
```

**Comment by mgrybyk** [comment]
nope, you are not, see https://webdriver.io/docs/multiremote.html

you are passing capabilities incorrectly.

**Comment by chirag-farfetch** [comment]
@mgrybyk , i realized my mistake i was using [] in capabilities. it works now. thank you

**Comment by chirag-farfetch** [comment]
I achieved the same with the appium as well. closing this now

**Comment by mgrybyk** [comment]
Great!

**Comment by chirag-farfetch** [comment]
Putting my solution here so it is helpful for others:

```
exports.config = {
    runner: 'local',
    //
    specs: [
        'test.js'
    ],
    //
    exclude: [
        // 'path/to/excluded/files'
    ],
    //
    //
    capabilities: {
        myChromeBrowser: {
            capabilities: {
                browserName: 'chrome',
            }
        },
        myFirefoxBrowser: {
            port: 4723,
            capabilities: {
                platformName: 'iOS',
                'appium:deviceName': 'iPhone 8',
                'appium:platformVersion': '12.4',
                'appium:orientation': 'PORTRAIT',
                'appium:noReset': true,
                'appium:newCommandTimeout': 240,
                "appium:platformName": "iOS",
                "appium:deviceName": "iPhone 8",
                "appium:bundleId": "com.abc.debug",
            }
        }
    },
    services: ['appium'],
    appium: {
        args: {
            address: '127.0.0.1',
            commandTimeout: '7200',
            sessionOverride: true,
            debugLogSpacing: true,
            platformVersion: '4.4',
            platformName: 'iOS',
            deviceName: 'emulator-5554',
            nativeInstrumentsLib: true,
            isolateSimDevice: true,
            app: "com.abc.debug"
        }
    },
    //
    logLevel: 'trace',
    //
    deprecationWarnings: true,
    //
    bail: 0,
    //
    baseUrl: 'google.com/',
    //
    waitforTimeout: 10000,
    //
    connectionRetryTimeout: 90000,
    //
    connectionRetryCount: 3,
    //
    services: ['selenium-standalone'],
    //
    framework: 'jasmine',
    //
    //
}
```

**Comment by mgrybyk** [comment]
Thank you

**Comment by chirag-farfetch** [comment]
@mgrybyk , quick question I want to convert the above format to this format below. Because with that format i am starting to get errors like : 

```
import ClientScreen from '../screenobjects/client.screen';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```


```
const { join } = require('path');
const { config } = require('./wdio.shared.conf');

// ============
// Specs
// ============
config.specs = [
    './tests/specs/**/*.spec.js',
];

// ============
// Capabilities
// ============
// For all capabilities please check
// http://appium.io/docs/en/writing-running-appium/caps/#general-capabilities
config.capabilities = [
    {
        // The defaults you need to have in your config
        platformName: 'iOS',
        maxInstances: 1,
        smartWait: 5000,
        // For W3C the appium capabilities need to have an extension prefix
        // This is `appium:` for all Appium Capabilities which can be found here
        // http://appium.io/docs/en/writing-running-appium/caps/
        'appium:deviceName': 'iPhone 8',
        'appium:platformVersion': '12.4',
        'appium:orientation': 'PORTRAIT',
        // `automationName` will be mandatory, see
        // https://github.com/appium/appium/releases/tag/v1.13.0
        // The path to the app
        'appium:app': join(process.cwd(), './apps/iOS-Simulator-NativeDemoApp-0.2.1.app.zip'),
        // Read the reset strategies very well, they differ per platform, see
        // http://appium.io/docs/en/writing-running-appium/other/reset-strategies/
        'appium:noReset': true,
        'appium:newCommandTimeout': 240,
        "appium:platformName": "iOS",
        "appium:deviceName": "iPhone 8",
        "appium:bundleId": "com.farfetch.sof.shopfloor.chanel.debug",
    },
];

exports.config = config;
```

**Comment by mgrybyk** [comment]
Import keyword can be used in babel, typescript. It's not yet supported officially in nodejs.
If you do already please refer to the docs.
Please use gitter for such questions

**Comment by Amrkamel1** [comment]
@chirag-farfetch  @mgrybyk

**Comment by hananconnectavo** [comment]
> @chirag-farfetch @mgrybyk
> is there way maybe to execute some it blocks on appium (mobile app) explicitly and some work against chrome desktop
> lets say i have this scenario i need to make some action on mobile app using appium then verify it reflects on web desktop app

To achieve that you have to use your capabilities objects when referring to anything like for example:
`myChromerBrowser.url('/')`
`myiOS.$('XCUI selector')`
`myChromeBrowser.$('xpath selector')`

**Comment by subashinih** [comment]
Hello, I am trying to automate mobile and browser app e2e tests. My application is similar to Zoom where users can join the meeting through browser client and mobile app (ios). My automation goal is after the user joins the meeting through a browser client, the mobile app should join the same meeting.I have added the capabilities like above and my ios app is launching, but my tests are not running. I am not sure how to pass the capabilities object like myChromeBrowser and myAppiumAppr in webdriverio tests, please let me know if I am missing anything or how I can use the capabilities in the test cases(webdriverio) ? Thanks

**Comment by testluminpdf** [comment]
Hi I have used sample config provided by @christian-bromann but it does not seem to work. Could you @mgrybyk  provide another sample config instead?

**Comment by andycarson182** [comment]
@chirag-farfetch , I having the same issue, using your configuration allows me to open a desktop browser and mobile, but now the test case is throwing me errors because seems like the context is wrong, what did u do for changing the context from web to mobile, and vice-versa. I'm using the same Appium and Webdriverio.
