### ISSUE TITLE
Trying to run launcher, but it executes the test only if specs is there in config file , is there any other way to pass specs outside the config file???

### ISSUE THREAD

**Issue by sourabhahg** [webdriverio/webdriverio#4868]
```
 const wdio = new Launcher(_cmd, {
            spec: '/test/csdmobileverification.js'
        });
wdio.run();
```
not able to launch the app or run any tests.

**Comment by christian-bromann** [comment]
As mentioned in the issue template, please provide logs or a reproducible example otherwise we can't help with your inquiry.

**Comment by FelixZilber** [comment]
@sourabhahg shouldn't it be ` specs: [
        ' /test/csdmobileverification.js'
    ]` 
you use "spec" instead of "specs" and it is a string instead of array...

**Comment by baruchvlz** [comment]
As @FelixZilber mentioned, the launcher expects `spec` [to be an array](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-config/src/lib/ConfigParser.js#L85), but I think the configuration helper could be changed to something like this instead:

```js
let spec = Array.isArray(object.spec) ? object.spec : [object.spec]
```

**Comment by christian-bromann** [comment]
`spec` is a cli option that can be passed in as an argument. This issue is still lacking in logs or a reproducible example. I will go ahead and close this. Happy to reopen if missing assets are provided. Cheers!
