### ISSUE TITLE
Possibility to use test file name on report name

### ISSUE THREAD

**Issue by iagowp** [webdriverio/webdriverio#4869]
**Is your feature request related to a problem? Please describe.**
I need a clearer way to identify my reports without opening the file

**Describe the solution you'd like**
When using `outputFileFormat` on a reporter, I'd like to receive the name of the file being tested from the `options` object, as an alternative to `cid`

**Describe alternatives you've considered**
I'm using `cid`, but people are not finding it very intuitive looking at our CI tool and seeing test 3-1 to know which test failed, without looking at it

**Comment by christian-bromann** [comment]
> I'd like to receive the name of the file being tested from the `options` object

Where exactly do you need that data?

**Comment by iagowp** [comment]
Most reporters have an option `outputFileFormat` that receives a function.
That function, seems to have a default `options` object, including wdio.conf options, `cid`, and couple other things. I'd like this information to be on the same level as `cid`

**Comment by iagowp** [comment]
Ok, I've mostly figured out how to make the changes. Only part that I'd still need to figure out is fixing the path to be relative to the project, instead of absolute and test everything to see if nothing breaks from that change.

@christian-bromann  should I contribute? Do you think this is a good addon to this project?

**Comment by christian-bromann** [comment]
> should I contribute? Do you think this is a good addon to this project?

Yes, please do. If the solution to this is exposing more data to the user that is sounds good to me.

**Comment by christian-bromann** [comment]
I will close this feature request due to inactivity. If someone is still interested in this, let me know here and I am happy to re-open.
