### ISSUE TITLE
CORS issue when testing via webdriver

### ISSUE THREAD

**Issue by grofit** [webdriverio/webdriverio#487]
I know this is not going to be webdriverio's fault, but I was wondering if there was any guidance available as to how to enable CORS when testing?

I currently use firefox for manually testing, and I am using firefox for the webdriver tests and I keep getting the error about CORS, but I have setup all the xhr config in the client to allow CORS etc (otherwise it wouldnt work when I manually test), so is there anything I am missing?

And I apologize for posting the question here knowing that it will probably end up with me having to do something with the standalone webdriver thing.

**Comment by christian-bromann** [comment]
no worries @grofit .. so it is working if you open your browser manually but not if you running the same browser with Selenium?

**Comment by grofit** [comment]
yep, the site HEAVILY uses CORS (webservice on another domain), and like I say works fine if I do it normally via the browser. Although the xhr object has cors enabled and the server returns the headers for the client.

I have tried chrome and firefox and both work fine when browsing normally, but as you say via webdriver it just has a CORS based console error. I know that webdriver runs FF (and other browsers) in its own profile, but not quite sure if I need to pass over certain `desiredCapabilities` for it to run, or i need to set something on the `selenium-standalone` to allow CORS (and probably certs)

**Comment by grofit** [comment]
The question was answered here:

http://stackoverflow.com/questions/29457206/selenium-standalone-with-cors
