### ISSUE TITLE
Webdriverio + Appium throws error for beforeAll method

### ISSUE THREAD

**Issue by flexin777** [webdriverio/webdriverio#4877]
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2018",
    "baseUrl": ".",
    "paths": {
      "*": [
        "./*"
      ],
      "src/*": [
        "./src/*"
      ]
    },
    "types": [
      "@wdio/sync",
      "@wdio/mocha-framework",
      "node",
      "webdriverio"
    ],
    "moduleResolution": "node",
    "lib": [
      "es2019"
    ]
  },
  "strict": true,
  "esModuleInterop": true,
  "allowSyntheticDefaultImports": true,
  "include": [
    "test/**/*.ts"
  ]
}

**Comment by flexin777** [comment]
I get error
@wdio/runner: ReferenceError: beforeAll is not defined

**Comment by christian-bromann** [comment]
@flexin777 Mocha doesn't support `beforeAll`, it should be `before`.
