### ISSUE TITLE
Let framework filter specs before worker is spawned

### ISSUE THREAD

**Issue by gustavohenke** [webdriverio/webdriverio#4887]
**Is your feature request related to a problem? Please describe.**
For context, I'm testing with the cucumber framework + local-runner.

I have 250+ spec files + a tag expression that filters that down to 2 files. The time to run each spec is of about 40 seconds. I'm afraid that the time to run the full suite would grow exponentially.

The flow of the CLI that I have identified is this*:
- [It loops through every spec file](https://github.com/webdriverio/webdriverio/blob/92de2edb5c07ddca34e70f743ae3b663a5a6f5b5/packages/wdio-cli/src/launcher.js#L203-L246);
- Launches local-runner, which in turn spawns its worker, [first here](https://github.com/webdriverio/webdriverio/blob/92de2edb5c07ddca34e70f743ae3b663a5a6f5b5/packages/wdio-local-runner/src/index.js#L37-L39) then [here](https://github.com/webdriverio/webdriverio/blob/92de2edb5c07ddca34e70f743ae3b663a5a6f5b5/packages/wdio-local-runner/src/worker.js#L166-L172);
- Inside the new worker process, [the framework is finally initialised and it determines if there are any tests to run](https://github.com/webdriverio/webdriverio/blob/92de2edb5c07ddca34e70f743ae3b663a5a6f5b5/packages/wdio-runner/src/index.js#L83-L86). If not, it stops the child process.

It seems that WDIO is spawning ~248 Node.js processes needlessly.

<sub>* I may lack context of the internals of WDIO, sorry if I miss the point of something here 🙂 </sub>

**Describe the solution you'd like**
Similarly to #4531, can the framework be initialised by an early step of that flow (e.g. the CLI)? So to avoid spawning processes that will be discarded immediately.

**Describe alternatives you've considered**
Writing my own CLI with chokidar + cucumber.
Feels like we could be going down the path of having another [chimp.js](https://chimp.readme.io/) 💩 

**Additional context**
Node.js v10.16.3

`@wdio` packages used:
```json
    "@wdio/cli": "^5.16.10",
    "@wdio/cucumber-framework": "^5.16.10",
    "@wdio/local-runner": "^5.16.10",
    "@wdio/selenium-standalone-service": "^5.16.10",
    "@wdio/spec-reporter": "^5.16.10",
    "@wdio/sync": "^5.16.10",
```

**Comment by mgrybyk** [comment]
It really works like you have described and can be improved. We can initialize framework in main process to get list of specs before spawning any process.
Good one for v6

**Comment by gustavohenke** [comment]
I'm not sure how the integration of webdriverio and those frameworks is, but I have used them for unit tests, and they can take a string to grep tests, or use syntax like `describe.skip`. If the framework reports 0 tests in a spec file, then spawning the worker is skipped.

The framework could tell if it has been configured to maybe filter the tests -- in the case of cucumber, whether `cucumberOpts.tagExpression` is set.

**Comment by christian-bromann** [comment]
I think this is for what we #2859 logged for (though much worst described then this). I will go ahead and close #2859 and reference it to this.

**Comment by christian-bromann** [comment]
This will be the default behavior in v6 thanks to the work of @mgrybyk !
