### ISSUE TITLE
Typings of some webdriver commands are not accurate

### ISSUE THREAD

**Issue by just-boris** [webdriverio/webdriverio#4889]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.16.15
 - **Mode:** standalone
 - **Node.js version:** n/a
 - **NPM version:** n/a
 - **Browser name and version:** Chrome 79.0 with selenium-standalone 3.141.5
 - **Platform name and version:** MacOS 10.14.6

**Describe the bug**
The return type of `browser.getActiveElement()` is declared as `string`, but in fact it is an element object.

I guess the same applies to all methods at these lines: 
https://github.com/webdriverio/webdriverio/blob/master/packages/webdriver/webdriver.d.ts#L1446-L1479, they all return element objects, not strings.

**To Reproduce**

I have the following code in my test

```js
await browser.url('http://google.com');
const activeElement = await browser.getActiveElement();
console.log('active element', activeElement); // logs `active element { ELEMENT: '0.5354555166508148-1' }`
// typescript is complaining about this line, saying that activeElement is a string, not an object
const tagName = await browser.getElementTagName(activeElement.ELEMENT);
console.log('active tag', tagName);
```

The code runs well, but Typescript complains about incorrect `activeElement` type.

I worked this around via `await browser.getActiveElement() as Element` casting.

**Expected behavior**

I expect that the typings from library will match with the actual return value of the functions.

**Comment by christian-bromann** [comment]
The `getActiveElement` is a protocol command and returns the raw server response, e.g.:

```js
{
  'element-6066-11e4-a52e-4f735466cecf': '7c2a6ddd-c505-4734-baf7-5b4b9bfd74f0'
}
```

So in order to convert it into an WebdriverIO Element you have to do this:

```js
const activeElement = $(await browser.getActiveElement());
// or browser.$ in standalone
```

That said, I think the TypeScript definition is correct.

**Comment by just-boris** [comment]
I see. The issue was that selenium-standalone pulls an older chrome driver version: https://github.com/vvo/selenium-standalone/issues/434

With the latest version your solution works.
