### ISSUE TITLE
onAlert functionality

### ISSUE THREAD

**Issue by sean-hill** [webdriverio/webdriverio#489]
I'm testing a page where I show an error `alert()` after a user clicks a button to submit a form. Is there a way to detect when this alert is shown? I've tried

    .click('input[type="submit"]')
    .alertText(function(text){
        console.log('Alert text', text);
    })

But the alert text is `null`. Thanks.

**Comment by christian-bromann** [comment]
Could you try to pause the execution for a bit to make sure the alert is visible? Try:

```js
.click('input[type="submit"]')
.pause(500)
.alertText(function(text){
    console.log('Alert text', text);
})
```

**Comment by sean-hill** [comment]
Hey Christian, I solved this issue [here](https://github.com/webdriverio/webdriverio/issues/490).

**Comment by christian-bromann** [comment]
great!
