### ISSUE TITLE
Automatic cloud platform detection logic breaks my project

### ISSUE THREAD

**Issue by vania-pooh** [webdriverio/webdriverio#4892]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.16.15
 - **Mode:** testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.3.1
 - **NPM version:** 6.9.0
 - **Browser name and version:** any
 - **Platform name and version:** any
 - **Additional wdio packages used (if applicable):** 
```
  "dependencies": {
    "chai": "*",
    "mocha": "^6.2.2",
    "webdriverio": "^5.16.15"
  },
  "devDependencies": {
    "@wdio/cli": "^5.16.15",
    "@wdio/dot-reporter": "^5.16.5",
    "@wdio/local-runner": "^5.16.15",
    "@wdio/mocha-framework": "^5.16.15",
    "@wdio/spec-reporter": "^5.16.11",
    "@wdio/sync": "^5.16.15"
  }
```

**Config of WebdriverIO**
```
exports.config = {
    runner: 'local',
    protocol: 'https',
    host: 'browsers.aerokube.com',
    port: 4444,
    user: 'some-username', // Username, 32 symbols
    key: 'some-password', // Password, 32 symbols
    specs: [
        'tests/**/*js'
    ],
    maxInstances: 1,
    capabilities: [
      {browserName: 'chrome', browserVersion: '78.0'}
    ],
    logLevel: 'debug',
    framework: 'mocha',
    reporters: ['dot','spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    }
};

```

**Describe the bug**
Whenever password length in configuration file is 32 symbols webdriver.io always considers such configuration related to `hub.testingbot.com:` service. We are creators and maintainers of an alternative cloud platform called [Browsers](https://browsers.aerokube.com/) and by coincidence we also have 32 symbol passwords in our service. So we expect that webdriver.io will use host from `host` configuration field but it always goes to `hub.testingbot.com`. This should be because of automatic cloud platform detection implemented here: https://github.com/webdriverio/webdriverio/blob/f27800dd18470e9164db60834bd59bc34b68a909/packages/wdio-config/src/utils.js#L67-L72

**To Reproduce**
An example repository:
https://github.com/aerokube/browsers-webdriverio-example

**Expected behavior**
We expect that webdriver.io always goes to the host specified in configuration file or some way to disable automatic selection of cloud provider.

**Log**
```
2019-12-16T17:09:18.572Z INFO webdriver: [POST] https://hub.testingbot.com:4444/wd/hub/session
[0-0] 2019-12-16T17:09:18.572Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'chrome', browserVersion: '78.0' },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'chrome', browserVersion: '78.0' }
}
```

**Comment by vania-pooh** [comment]
We could send a PR if you clarify a recommended way to fix this.

**Comment by christian-bromann** [comment]
> We expect that webdriver.io always goes to the host specified in configuration file or some way to disable automatic selection of cloud provider.

We only automatically set `hostname` for these providers if `name` and `key` options are set. If you are not using Sauce Labs, Browserstack or Testingbot, there is no reason for you to set the `name` and `key` options in the first place. To properly connect with your backend your capabilities should be as follows:

```js
exports.config = {
    // ...
    protocol: 'https',
    hostname: 'browsers.aerokube.com',
    port: 4444,
    capabilities: [{
        browserName: 'chrome',
        browserVersion: '78.0',
        'aerokube:options': {
            user: 'some-username', // Username, 32 symbols
            key: 'some-password', // Password, 32 symbols
            // other vendor specific options
        }
        // ...
    }],
    // ...
}
```

A couple of notes here:

- to set the host name you should use [`hostname`](https://webdriver.io/docs/options.html#hostname) as option
- you should define vendor specific options like username and key into a WebDriver compatible capability like e.g. `aerokube:options`

I would be happy to auto detect the aerokube backend if it has something unique defined.

**Comment by vania-pooh** [comment]
@christian-bromann you don't get - we are just the same online cloud platform as SauceLabs, BrowserStack or TestingBot thus requiring just the same basic authentication scheme. Introducing third-party capabilities in case where standard Basic HTTP Auth will work seems to be an overkill.

**Comment by BorisOsipov** [comment]
I see two options:
1. We can add config key to disable backed autodetection
2. @vania-pooh if you use basic auth, can you send credentials directly in headers see https://webdriver.io/docs/options.html#headers ?

**Comment by vania-pooh** [comment]
@BorisOsipov All Selenium clients and all Selenium cloud platforms in fact support only one authentication method - basic HTTP auth. This is already supported and working out of the box in webdriver.io (when `user` and `key` parameters are specified). All this stuff was already working for us like a charm before auto-detection logic was introduced. So the only issue is this weird auto-detection code with hard-coded password size corresponding to a concrete cloud platform. I would do one of the following:
1) Add some configuration key to disable autodetection
2) Improve auto-detection and base on hostname value instead of username and password
3) Add some kind of support for our online platform

Whenever you decide - we could provide a respective PR to fix this as soon as possible.

**Comment by christian-bromann** [comment]
I propose to prefer a manual set `hostname` and `key` property if set in the config. So that you could do:

```js
exports.config = {
    // ...
    protocol: 'https',
    hostname: 'browsers.aerokube.com',
    port: 4444,
    user: 'some-username', // Username, 32 symbols
    key: 'some-password', // Password, 32 symbols
    capabilities: [{
        browserName: 'chrome',
        browserVersion: '78.0',
        // ...
    }],
    // ...
}
```

@vania-pooh would that work for you?

**Comment by vania-pooh** [comment]
@christian-bromann yes, definitely. Any combination of existing parameters having bigger priority than auto-detection would solve the issue.

**Comment by vania-pooh** [comment]
@christian-bromann thank you!
