### ISSUE TITLE
Couldn't Parse Cookie SameSite Attribute

### ISSUE THREAD

**Issue by imcoddy** [webdriverio/webdriverio#4893]
As Google Chrome will change the cookie policy to next Feb, it would be necessary that WebDriver.io can support SameSite attribute in `getAllCookies` method. More detail of this attribute can be found in here https://web.dev/samesite-cookies-explained/

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.16.16
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v12.9.0
 - **NPM version:** 6.11.3
 - **Browser name and version:** Chrome 79
 - **Platform name and version:** Mac

**Config of WebdriverIO**
see https://github.com/amiya-pattnaik/webdriverIO-with-jasmineBDD/blob/master/test/config/suite.jasmine.conf.js

**Describe the bug**
`getAllCookies()` method cannot parse SameSite cookie attribute

**To Reproduce**
Set up the server with SameSite=Strict enabled
```
var express = require('express')

var app = express()

app.get('/', function (req, res) {
  res.cookie('foo', 'bar', {
    sameSite: true
  })
  res.end()
})

app.listen(4000)
```

Make a request
```
    browser.url(getUrl())
    let url = 'http://localhost:4000'
    browser.url(url)
    let cookie = browser.getAllCookies()
    console.log(cookie)
    var request = require("request");
    request(url, {
      method: "HEAD"
    }, function (
      err,
      res,
      body
    ) {

      let c = res.headers['set-cookie']
      console.log(c);
    });
```
[Include code or an example repository that can easily be set up]

**Expected behavior**
Expected cookie with SameSite attribute as follow:
```
  {
    domain: 'localhost',
    httpOnly: false,
    name: 'foo',
    path: '/',
    secure: false,
    samesite: 'strict'
    value: 'bar'
  }
```

**Log**

**Additional context**
If check the raw request headers the value for `set-cookie` is `[ 'foo=bar; Path=/; SameSite=Strict' ]`

**Comment by christian-bromann** [comment]
This has to be implemented in the protocol. I made the necessary pull requests in https://github.com/w3c/webdriver/pull/1473. Once approved and implemented in the browser driver it should be automatically available in WebdriverIO.
