### ISSUE TITLE
[wdio-cli] Browser capabilities are merged instead of overridden in @wdio/config

### ISSUE THREAD

**Issue by pedromateo** [webdriverio/webdriverio#4894]
**Environment:**
 - **WebdriverIO version:** 5.16.15
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.16.3
 - **NPM version:** 6.9.0
 - **Browser name and version:** -
 - **Platform name and version:** MacOs 10.14.6
 - **Additional wdio packages used (if applicable):** @wdio/config, @wdio/cli

**Config of WebdriverIO**
CLI runner of Wdio is used with a spec file plus an opts object with some options to be overridden. The options to be overridden are "specs" and "capabilities".

**Describe the bug**
While "specs" property is properly overridden,  new "capabilities" are appended to the old ones when the expected behavior is the replacement. 

**To Reproduce**
1. Run wdio test runner programmatically as indicated here: https://webdriver.io/docs/clioptions.html
2. As first parameter, use a spec file including, e.g., the following capabilities:
```
    capabilities: [{
          maxInstances: 2,
          browserName: 'firefox',
          'goog:chromeOptions': {
             args: [
               'incognito', '--no-sandbox', '--disable-gpu',
             ], }, }, ],
```
3. As second parameter use, e.g., the following capabilities: 
```
    capabilities: [{
          maxInstances: 6,
          browserName: 'chrome',
          'goog:chromeOptions': {
            args: [
              'incognito', '--no-sandbox', '--disable-gpu',
            ], }, }, ],
```
As a result, the two different capabilities are included in the capabilities array.

**Expected behavior**
Old capabilities should be replaced by new capabilities so, as result, only one item should be included in the resulting capabilities array. 

**Log**
-

**Additional context**
-

> Please use the correct markdown

**Comment by baruchvlz** [comment]
I think this is the [expected behaviour](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-config/src/lib/ConfigParser.js#L101) of the WDIO's configuration parser helper. If you can make a good case as to why this should be different we could consider changing it but it might be a big breaking change.

cc/ @christian-bromann

**Comment by pedromateo** [comment]
As I described above, the behavior is different depending on the properties I pass as second parameter (_opts_). For example:
- if I define "specs" property in _opts_, the actual behavior is **_replacing_** the old specs by the new ones.
- if I define "capabilities" property in _opts_, the actual behavior is **_appending_** the new capabilities to the old ones.

So, what is the expected behavior? Replacing or overriding? In my opinion, these two actions are not coherent.

Some examples of situations in which replacing behavior is useful are the following:
- run the tests momentary in no-headless mode to see what's happening.
- try the current development in a different browser.
- allow more instances temporarily.

Thank you very much in advance for your time.

**Comment by baruchvlz** [comment]
I see, I think the best way to go about this is to add an `overwriteCaps` flag to the opts object.

```js
new Launcher(pathToConfig, { capabilities: [...], overwriteCaps: true });
```

I opened a PR, waiting for review.

**Comment by christian-bromann** [comment]
Let's continue conversations in #4930
