### ISSUE TITLE
Change default path from /wd/hub to just /

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4896]
**Is your feature request related to a problem? Please describe.**
by default path is `/` in all browser drivers and selenium standalone v4, let's change it in our code!

**Describe the solution you'd like**
- change default path from /wd/hub to /
- update all docs accordingly
- mention somewhere that users who have selenium standalone v3 or using grid have to change path to /wd/hub

**Comment by christian-bromann** [comment]
Fixed in #4907
