### ISSUE TITLE
alertVisible functionality

### ISSUE THREAD

**Issue by sean-hill** [webdriverio/webdriverio#490]
Is there a way to check if an alert is present on the page?

**Comment by christian-bromann** [comment]
@sean-hill I thing [alertText](http://webdriver.io/api/protocol/alertText.html) should do the trick. Not sure if it throws an error or not.

**Comment by sean-hill** [comment]
Hey @christian-bromann, 

I found a solution

    .alertText().then(
        function(data){
            console.log('Got alert text:', data.value);
        }, function(err){
            console.log('There was no alert, but handled gracefully:', err)
        })

**Comment by christian-bromann** [comment]
nice!
