### ISSUE TITLE
log('browser') doesn't work correctly under chrome driver

### ISSUE THREAD

**Issue by huei90** [webdriverio/webdriverio#491]
When using the log('browser') protocol

Here's the snippet

```js
// ...
it('blablabla when using browser log', function(done) {
    browser
        .log('browser', function(err, msg,a) {
            console.log(msg);
            // under phantomjs, it shows correctly
            // under chrome it shows null log
        })
        .call(done);
})
// ...
```

Did someone having the same problem?

**Comment by apendua** [comment]
I think that for chromedriver, the default "log level" is not set "INFO", so you will not receive the output from `console.log`, but on the other hand `console.warn` should work - try it!

To fix it, you will probably need to use the following capabilities:
```javascript
capabilities.loggingPrefs = { "driver": "INFO", "browser": "INFO" }
```

**Comment by christian-bromann** [comment]
@huei90 haven't used the log command to be honest ;-) .. Have you tried @apendua solution?

@apendua Thanks!

**Comment by apendua** [comment]
@christian-bromann No problem!

I think it's really hard to find in the Internet, so I just though this "trick" is worth spreading.

**Comment by huei90** [comment]
@christian-bromann I haven't tested it yet. I will tell you after testing it =)

**Comment by huei90** [comment]
@apendua @christian-bromann It's work after adding to the options
```js
            options: {
                desiredCapabilities: {
                    browserName: 'chrome', // chrome, firefox
                    loggingPrefs: {
                      'driver': 'INFO',
                      'browser': 'INFO'
                    }
                }
            }
```

**Comment by christian-bromann** [comment]
Awesome! Will put some documentation of it on the website with release of `v3`

**Comment by huei90** [comment]
:smile:

**Comment by spatchamatla** [comment]
can we also get the browser debug logs as well with the above, when we set **"browser": "DEBUG"** ?
