### ISSUE TITLE
@wdio/appium-service not working on Windows

### ISSUE THREAD

**Issue by wswebcreation** [webdriverio/webdriverio#4914]
**Environment (please complete the following information):**
 - **WebdriverIO version:** `5.18.0`
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** `12.0.0`
 - **NPM version:** `6.9.0`
 - **Browser name and version:** -
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** `@wdio/appium-service`

**Config of WebdriverIO**
See [appium-boilerplate](https://github.com/webdriverio/appium-boilerplate)

**Describe the bug**
The Appium server will not be started on Windows

**To Reproduce**
See [appium-boilerplate](https://github.com/webdriverio/appium-boilerplate)

**Log**
```log
$ ./node_modules/.bin/wdio ./config/wdio.android.app.conf.js --logLevel=debug

Execution of 6 spec files started at 2019-12-24T09:01:51.465Z

2019-12-24T09:01:51.471Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "appium"
2019-12-24T09:01:51.573Z INFO @wdio/cli:launcher: Run onPrepare hook
2019-12-24T09:01:51.574Z DEBUG @wdio/appium-service: Will spawn Appium process: appium
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: spawn appium ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:19)
    at onErrorNT (internal/child_process.js:431:16)
    at processTicksAndRejections (internal/process/task_queues.js:83:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:58:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:828:11)
    at internal/main/run_main_module.js:17:11
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
    at onErrorNT (internal/child_process.js:431:16)
    [... lines matching original stack trace ...]
    at internal/main/run_main_module.js:17:11
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

``

**Comment by wswebcreation** [comment]
Found the problem,

For Windows we need to start the server with 

```js
let process = spawn('cmd', ['/c','appium'], { stdio: ['ignore', 'pipe', 'pipe'] })
```

See https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-appium-service/src/launcher.js#L52

**Comment by erwinheitzman** [comment]
I believe you can remove the `command` from the options like so:
```
    appium: {
        // For options see
        // https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-appium-service
        args: {
            // For arguments see
            // https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-appium-service
        },
    },
```

and use `npm link appium` once to fix this like so:
```
PS C:\dev\appium-boilerplate> npm link appium 
C:\dev\appium-boilerplate\node_modules\appium -> c:\Program Files\nodejs\node_modules\appium
```

Now it will look for appium in the global node_modules directory.

**Comment by wswebcreation** [comment]
Tnx @erwinheitzman , but that's not the case here. We need to be able to use the global installed version of Appium if people provide it in their caps. I've already created a PR for it but struggling with my UT

**Comment by christian-bromann** [comment]
Closing given that #4915 got merged and released.
