### ISSUE TITLE
Tag Name selector throwing error "invalid selector: An invalid or illegal selector was specified"

### ISSUE THREAD

**Issue by neerajkumar-lad** [webdriverio/webdriverio#4917]
**Environment (please complete the following information):**
 - **WebdriverIO version:** ^5.16.11
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v8.9.4
 - **NPM version:** 5.6.0
 - **Browser name and version:** chrome=79.0.3945.88
 - **Platform name and version:** Mac 10.13.6 
 - **Additional wdio packages used (if applicable):** 
     "@wdio/cli": "^5.16.11",
    "@wdio/local-runner": "^5.16.11",
    "@wdio/mocha-framework": "^5.16.11",
    "@wdio/selenium-standalone-service": "^5.16.10",
    "@wdio/spec-reporter": "^5.16.11",
    "@wdio/sync": "^5.16.11",
    "chromedriver": "^78.0.1",
    "wdio-chromedriver-service": "^5.0.2"

**Config of WebdriverIO**
[From WebdriverIO Guild](https://webdriver.io/docs/gettingstarted.html)

**Describe the bug**
I am trying to find and read `<h1>` tag value using Tag Name selector. So I have written the following statement

```
const x = $("<h1>").getText();
const x1 =$("<h1 />").getText();
```

But it showing following error in the console

**To Reproduce**
```
const assert = require("assert");
describe("Example", function() {
	it("Open URL", function() {
		driver.url("https://www.lambdatest.com/");
	});

	it("TC Example", function() {
		const x = $("<h1>");
                 console.log(x);
	});
});
```

**Expected behavior**
As per the document, the selector should find an element using HTML tag and perform an action

**Log**
```
[0-0] 2019-12-24T19:30:02.327Z INFO webdriver: Retrying 3/3
2019-12-24T19:30:02.327Z INFO webdriver: [POST] http://127.0.0.1:4444/session/6b1ac039afae202b26aa9d709bd6d605/element
[0-0] 2019-12-24T19:30:02.328Z INFO webdriver: DATA { using: 'css selector', value: '<h1 />' }
[0-0] 2019-12-24T19:30:02.334Z ERROR webdriver: Request failed due to invalid selector: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=79.0.3945.88)
    at getErrorFromResponseBody (/Users/xxx/webdriverTutorial/Demo_1/TestProject/node_modules/webdriver/build/utils.js:124:10)
    at Request._callback (/Users/xxx/webdriverTutorial/Demo_1/TestProject/node_modules/webdriver/build/request.js:110:64)
    at Request.self.callback (/Users/xxx/webdriverTutorial/Demo_1/TestProject/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/xxx/webdriverTutorial/Demo_1/TestProject/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/xxx/webdriverTutorial/Demo_1/TestProject/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
[0-0] invalid selector in "Selector Example Tag Name Example"
invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=79.0.3945.88)
```
**Additional context**
N/A

**Comment by baruchvlz** [comment]
```
const x = $("<h1>");
```

This is not a valid selector, it should be `$('h1')`;

**Comment by neerajkumar-lad** [comment]
> ```
> const x = $("<h1>");
> ```
> 
> This is not a valid selector, it should be `$('h1')`;

Why it's invalid, I tried a similar example shown on the official website. Refer to this link: https://webdriver.io/docs/selectors.html#tag-name

**Comment by mgrybyk** [comment]
Looks like a typo in the docs,  the selector is invalid, you can see valid selectors types supported by browser drivers

**Comment by neerajkumar-lad** [comment]
@mgrybyk Thanks for the update, would that be possible to update the document? 
And would like to know that WebdriverIO supports XPath functions and Xpath axes? if so, any reference for webdriverIO?

**Comment by neerajkumar-lad** [comment]
Also, finding an element with help of name is not supported 

e.g 
**HTML DOM:** 
`<input type="text" class="inputtext _58mg _5dba _2ph-" data-type="text" **name="firstname"** value="" aria-required="true" placeholder="" aria-label="First name" id="u_0_q" autocomplete="off" aria-describedby="js_1x">`

If the user wants to find an element using name directly without writing XPath

e.g 
**In Java**
`driver.findElement(By.name='firstname');`

**Comment by christian-bromann** [comment]
> would that be possible to update the document?

Which document?

**Comment by christian-bromann** [comment]
For more informations on selectors, please see https://webdriver.io/docs/selectors.html

**Comment by neerajkumar-lad** [comment]
> > would that be possible to update the document?
> 
> Which document?

https://webdriver.io/docs/selectors.html#tag-name

**Comment by neerajkumar-lad** [comment]
> For more informations on selectors, please see https://webdriver.io/docs/selectors.html

I am referring that only, but could not find the selector for the name attribute

**Comment by christian-bromann** [comment]
@neerajkumar-lad fixed issue in https://github.com/webdriverio/webdriverio/pull/4918
