### ISSUE TITLE
elementIdDoubleClick is missing

### ISSUE THREAD

**Issue by binarykitchen** [webdriverio/webdriverio#492]
We have elementIdClick at http://webdriver.io/api/protocol/elementIdClick.html but none for double click actions on the protocol layer. Could this be added anytime soon?

**Comment by Robinfr** [comment]
There is no doubleClick in the JsonWireProtocol (https://code.google.com/p/selenium/wiki/JsonWireProtocol#/session/:sessionId/element/:id/click). What you could do for now is  ``client.moveTo(element).doDoubleClick()``

**Comment by christian-bromann** [comment]
There a double click endpoint in the JSON wire protocol https://code.google.com/p/selenium/wiki/JsonWireProtocol#/session/:sessionId/doubleclick

If you want to do a double click use http://webdriver.io/api/action/doubleClick.html

**Comment by Robinfr** [comment]
Yes but that works on a selector, not an element ID.

**Comment by christian-bromann** [comment]
@binarykitchen please use the approach @Robinfr has provided.

@Robinfr right, I see. I was thinking about allowing to pass element IDs as selectors for v3

**Comment by binarykitchen** [comment]
thanks guys
