### ISSUE TITLE
Name strategy description is missing in the selector section

### ISSUE THREAD

**Issue by neerajkumar-lad** [webdriverio/webdriverio#4921]
**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Description of the improvement / report**
I could see that on [selector page](https://webdriver.io/docs/selectors.html) there is no information about **Name selector** . I think we should add a description, usage, and example for the reader. 

Here is the working example of reference:
`$("[name = 'email']").getText();`

please find the attached screenshot for your reference. 
<img width="271" alt="Screen Shot 2019-12-26 at 4 19 39 PM" src="https://user-images.githubusercontent.com/41137182/71473080-96e3af80-27fb-11ea-8ee1-d99c2816122b.png">

**Comment by mgrybyk** [comment]
The example is just a css selector, not name selector

**Comment by neerajkumar-lad** [comment]
@mgrybyk Then how to use name selector without using name attribute in xpath?

**Comment by mgrybyk** [comment]
The selector you have provided is a css selector to look for element by attribute, you can look for guides on how to use css selectors.
Xpath example gonna be `//*[@name="email"]`, same as with css selectors, you may look for some guides.

**Comment by neerajkumar-lad** [comment]
@majaklajic With XPath I can use it easily. I want to use by name like in Java `driver.findElement(By.name("name attribute")).click();`

Blow code found in the file `findStrategy.js` of webdriverIO and why this is returning 'name"

  ```
if (selector.search(/^\[name=("|')([a-zA-z0-9\-_.@=[\] ']+)("|')]$/) >= 0) {
    return 'name';
  }
```

Many selectors calling internally using CSS selector and this might be.

**Comment by christian-bromann** [comment]
@neerajkumar-lad do you mind adding some docs under the `Mobile Selectors` section given that this selector strategy is only valid for running tests on Appium?

**Comment by neerajkumar-lad** [comment]
> @neerajkumar-lad do you mind adding some docs under the `Mobile Selectors` section given that this selector strategy is only valid for running tests on Appium?

@christian-bromann I would love to try

**Comment by christian-bromann** [comment]
@neerajkumar-lad any updates on this?

**Comment by menahemso** [comment]
WinAppDriver supports only : name, class name, accessibility id, and XPath. wdio supports only XPath and accessibility id(~)?

**Comment by christian-bromann** [comment]
@menahemso WebdriverIO also supports tag name: https://webdriver.io/docs/selectors.html#tag-name

**Comment by menahemso** [comment]
@christian-bromann You're right. 
Would be very helpful if you would complete the "name" and "class-name" strategies, the current use of WinAppDriver using WDIO is very limited!

**Comment by christian-bromann** [comment]
> Would be very helpful if you would complete the "name" and "class-name" strategies

These are invalid selector strategies. This is an issue that should be raised in WinAppDriver. You can also use arbitrary selector strategies via `selector-strategy:selector` , e.g. `$("name:some name")`
