### ISSUE TITLE
Using Launcher api more then once in the same execution

### ISSUE THREAD

**Issue by naorzr** [webdriverio/webdriverio#4922]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 5+]
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync
 - **Node.js version:** [e.g. 12.13.0]
 - **NPM version:** [e.g. 6.13.1]

**Describe the bug**
When running the wdio.conf.js files using the launcher api, if ran more than once, on the consecutive run, wdio launcher will run all the current hooks + the hooks of the previous launch configs, and in the next consecutive run it will run all the current hooks + the hooks of the previous launch and the one before, and so on and so forth. 

**To Reproduce**
Assuming you have the basic setup with a config file and a test file, simply create an index.js file
with the following content:
```
 const Launcher = require('@wdio/cli').default;
 new Launcher('./wdio.conf.js').run().then(() => {
   new Launcher('./wdio.conf2.js').run()
 })
```
and run it.

**Expected behavior**
Only the configuration file of the current runner should be read and invoked.

**Additional Info**
The cause for this issue lies with the DEFAULT_CONFIGS constant under wdio-config/constants.
It is being exported out of the file, but as a constant, in this manner the config file is actually not being redefined on different imports, so the information persists between launchers.
It can be easily solved by wrapping it with a function, which will act as a factory for the default configurations.

**Comment by christian-bromann** [comment]
Fixed in #4923
