### ISSUE TITLE
Random error about 1 in 5 tests

### ISSUE THREAD

**Issue by grofit** [webdriverio/webdriverio#493]
For some reason I get a weird error which stops execution about once in every 5 tests I run, where the error:

```
C:\Code\Web\<some-project>\node_modules\webdriverio\lib\utils\PromiseHandler.js:154
                throw error;
                      ^
RuntimeError: RuntimeError
     (UnknownError:13) An unknown server-side error occurred while processing the command.
     Problem: POST /session//url
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'somePcName', ip: '192.168.1.79', os.name: 'Windows 8.1', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_40'
Driver info: driver.version: unknown[1;30m

     Callstack:
     -> url("http://localhost:3000/")
```

I am running windows 8.1 pro and testing with firefox currently in Cucumber JS, my init and shutdown looks like:

```
var setupBrowser = function() {
    var browser = webdriverio.remote({
        desiredCapabilities: {
            "browserName": 'firefox',
            "acceptSslCerts": true,
            "security.fileuri.strict_origin_policy": false
        }
    });
    browser.init();
    return browser;
};

this.Before(function (callback) {
        var self = this;
        // setup some other stuff
        this.testData = {};

        this.browser = setupBrowser();
        this.browser.rootUrl = this.clientRoot;

        this.clearAllData(function () {
            callback();
        });
    });

this.After(function(callback){
        this.browser.end();
        callback();
    });
```

The actual logic being run is:

```
this.When(/^I visit (.*)$/, function(url, callback) {
        var completeUrl = "{1}{2}".assign(this.clientRoot, url);

        this.browser
            .url(completeUrl)
            .waitForPageLoad() // Custom command which polls JS for loaded flag but it doesnt get this far
            .then(callback)
            .catch(callback.fail);
    });
```

The selenium standalone output has no errors and just shows:

```
11:03:38.390 INFO - Done: [new session: Capabilities [{rotatable=true, acceptSslCerts=true, security.fileuri.strict_origin_policy=false, locationContextEnabled=true, browserName=firefox, ja
vascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]]
```

Then has nothing after it... I apologise for not having more information, but if you want me to do anything specific to yield better info I am more than happy to.

**Comment by christian-bromann** [comment]
According to the error message you loose your session id somewhere. That happens when you call end and continue using your webdriverio instance to execute commands. Make sure you don't reuse the webdriverio instance once you called `end`.

Is this problem still valid?

**Comment by grofit** [comment]
Yeah still having it, `browser.end` is a sync method right? it doesnt pass back a promise or anything?

The only thing I can think of is that I have had previous issues where promises sometimes end up firing incorrectly (hence my other question around then/call usage), so maybe one of the promises is not waiting for a step to finish and then ends up triggering the after method even though it is still actually in use. That would explain why it is seemingly random in nature, as it would be a race condition of sorts.

I noticed a while ago someone was pushing for better promise handling, is that anywhere near release?

**Comment by christian-bromann** [comment]
@grofit ohh `end` is async like all other commands too. I sends a request to the server to end the Selenium session. Could you check if that is the problem?

**Comment by grofit** [comment]
Hey,

I have run the tests a few times and so far no trace of the error so that would make sense. Thanks for the info.
