### ISSUE TITLE
Description of scenarios not exposed in reporter

### ISSUE THREAD

**Issue by senovsky** [webdriverio/webdriverio#4942]
Can you please add a feature into `@wdio/cucumber-framework`, so that it's exposing description of scenarios in `@wdio/reporter`? Related info is here: https://github.com/wswebcreation/wdio-cucumberjs-json-reporter/issues/18

**Comment by christian-bromann** [comment]
@senovsky can you please describe what information do you want to have being expose where?

**Comment by senovsky** [comment]
When I'm talking about description of scenarios, I mean text such as these three lines of code starting [here](https://github.com/webdriverio/cucumber-boilerplate/blob/9e6e6b5c6e74db196aa1f6972cec38265c5a4747/src/features/githubSearch.feature#L2).
In WDIO v4, this text was apparently available to reporter modules, because it was included in the files they generated.
Now I don't see this text in the JSONs generated by [CucumberJS JSON Reporter](https://webdriver.io/docs/wdio-cucumberjs-json-reporter.html), there's a name `description` with empty value instead. When I asked the author to add the value, he [pointed me to you](https://github.com/wswebcreation/wdio-cucumberjs-json-reporter/issues/18#issuecomment-554718504) guys.

**Comment by christian-bromann** [comment]
Yes, feel free to provide a PR.
