### ISSUE TITLE
WebdriverIO can't send keys on Sauce Labs

### ISSUE THREAD

**Issue by rgauthier-sauce** [webdriverio/webdriverio#4945]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.11.5 (also 5.15.1)
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.8.0
 - **NPM version:** 6.2.0
 - **Browser name and version:** Safari 12
 - **Platform name and version:** Mac 10.14
 - **Additional wdio packages used (if applicable):** NA

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

```
    capabilities: [{
        "browserName": "safari",
        "platform": "macOS 10.14",
        "version": "12.0",
    }],
    timeouts: {
        "pageLoad": 10000
    },
```

**Describe the bug**
When running a simple test sending keys **on Sauce Labs**, it fails because the wrong format is sent (W3C is expected by Sauce Labs, but JSON Wire Protocol is sent).

**To Reproduce**

```
describe('send keys on google.com', () => {
  it('should send keys', () => {
      browser.url('https://google.com/');
      let el = $("[name=\"q\"]")
      el.setValue("BN13AD")
  });
});
```

**Expected behavior**

Sending keys to the element should work here.

**Additional context**

We suspect the problem come from a mismatch between the expected protocol (W3C) and the sent format (JSONP).

**Comment by wswebcreation** [comment]
Hi @rgauthier-sauce 

You are not using the correct capabilities, this will start a JSONWP session which is failing with Safari 12

Here's an example of how you could do it https://github.com/wswebcreation/wdio-image-comparison-service/blob/master/tests/configs/wdio.saucelabs.conf.js#L353

The latest here refers to Safari 12

**Comment by christian-bromann** [comment]
Closing as @wswebcreation answers provides a solution. Capabilities need to be:

```js
capabilities: {
            browserName: 'safari',
            platformName: 'macOS 10.15',
            browserVersion: 'latest',
            ...sauceOptions
        }
```
