### ISSUE TITLE
WheelEvent

### ISSUE THREAD

**Issue by benjaminbours** [webdriverio/webdriverio#4947]
**Is your feature request related to a problem? Please describe.**
I couldn't find a way to simulate a proper mouse wheel event on a specific HTMLElement.

**Describe the solution you'd like**
There is an API for drag and drop for exemple. I would like something as simple about the WheelEvent. Or maybe there is a hidden way, in this case I would like to know it and see it well documented.

**Describe alternatives you've considered**
An explanation about doing this with browser.execute for exemple. But I have already tried a lot of stuff and nothing seems working.

**Additional context**
None

**Comment by christian-bromann** [comment]
This was [proposed to the spec](https://github.com/w3c/webdriver/pull/1410) and will be available once merged and implemented by the drivers. There is nothing we can do about this now. As a workaround you can try to run `execute` and emulate the event with JS.
