### ISSUE TITLE
setInterval only runs once in selectorExecuteAsync

### ISSUE THREAD

**Issue by richsilv** [webdriverio/webdriverio#495]
Whilst the context is quite verbose, I am essentially finding that running the following code results in the `setInterval` callback running only once (at which point the single element matching the selector has `display: none;` in its inline style), and never running again, regardless of the interval delay.

```
      browser.selectorExecuteAsync(selector, function(elements, thisCB) {
        if(elements.length === 0) {thisCB(false);}

        var interval = setInterval(function() {

          for (var i = 0; i < elements.length; i += 1) {
            var elem = elements[i];

            if (!elem.style || (elem.style.visibility !== 'hidden' && elem.style.display !== 'none')) {
              clearInterval(interval);
              return thisCB(true);
            }
          }

        }, 100);
      }, innerCB);
```

I have modified the function in various ways to ensure the following:

1. The set of elements has length 1.
2. The element is originally hidden with inline styling (i.e. `elem.style.display` is `none`).
3. I can then query the browser instance to see that the single element returned by the selector is displayed (i.e. has its inline styling removed) after about 3 seconds.
4. The interval callback never runs more than once (which I can see by using a simple counter).

I'm running `browser.timeoutsAsyncScript(20000);` prior to this, and indeed I get a timeout error from Selenium after 20 seconds, despite the element having been visible for 17 of them.

Can anybody explain this behavior?

**Comment by zukalt** [comment]
Check out [implemenentation of waitForVisible](https://github.com/webdriverio/webdriverio/blob/master/lib/commands/waitForVisible.js) where it uses similar approach (setInterval + some checks). [here](https://github.com/webdriverio/webdriverio/blob/master/lib/helpers/_isVisible.js) is the browser side running callback code.  I guess this problem either no longer exist or maybe you have  done some other stuff wrong then.

**Comment by christian-bromann** [comment]
@zukalt is right, this looks like you are trying to implement waitForVisible again. Try that command. I think it does the same thing.
