### ISSUE TITLE
Is there a way to get a non-computed css-property?

### ISSUE THREAD

**Issue by AnikoBorosova** [webdriverio/webdriverio#4950]
Use case: I need to get an element's `'width'` property that is set to `'auto'.` 

Both `element.getCSSProperty('width')` and` element.getSize('width')` gives back the computed value in 'px', however I need to get the non-computed value 'auto'.

Is there a way for this in webdriverio?

**Comment by christian-bromann** [comment]
> Is there a way for this in webdriverio?

WebdriverIO only returns the value it gets from the browser driver. You can try use the `execute` method to return the original value, e.g.

```js
const value = browser.execute((el) => el.style.width, element)
```

Let me know if that works. Happy to reopen.

**Comment by AnikoBorosova** [comment]
> Let me know if that works. Happy to reopen.

Unfortunately not, it gives me nothing back. 

If I understand correctly, `el.style.width` gets inline style attributes only. But my `'auto' ` value is not set inline. They suggest to use the `getComputedStyle()` method instead, but that brings me back to square one.

**Comment by christian-bromann** [comment]
> But my `'auto' ` value is not set inline.

How is it set instead? Why do you want to have this value in the first place?

**Comment by AnikoBorosova** [comment]
> Why do you want to have this value in the first place?

I need this value to test a functionality of an email editor.

There are 2 buttons to set the width of an element within this editor:

- One of my buttons sets the width to be `fixed,` and sets it in `px`.
- The second button sets the width to `auto`.

The difference can be clearly seen under the `Styles` tab in devTools, but the` Computed` tab shows the same exact amount in px in both cases, therefore it doesn't help me differentiate between the two way of width setting.

> How is it set instead? 

By clicking any of those buttons, a css style rule is generated and it is injected into the DOM within `<style> `tags. So it is not inline style.

I hope this helps you understand my problem.

**Comment by gustavohenke** [comment]
I'm not sure this is in any way related to webdriverio.
The DOM only exposes a ways to get
- The final computed value (`getComputedStyle`)
- What is in the `style` HTML attribute (`element.style`)

So if you're trying to find out the value of an attribute set by one of the classes on your element, you'll have to start by fetching the CSS file, then try to parse it to find out your class' attributes. And it only gets worse from there (specificity!).

So really, reframe the way that you're using webdriverio, that doesn't sound good in any way.

**Comment by AnikoBorosova** [comment]
Thanks, helpful info, I will find an other way.

> So really, reframe the way that you're using webdriverio, that doesn't sound good in any way.
Could you specify what do you mean by this?
