### ISSUE TITLE
Match elements by text content in case insensitive way

### ISSUE THREAD

**Issue by iongion** [webdriverio/webdriverio#4951]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to match elements by their text content in a **case insensitive** manner.

**Describe the solution you'd like**
A clear documented way to be able to match elements by their text value in case insensitive way.
CSS can apply text transforms and for many cases (not all) - tests can be written in clear way by avoiding to deal with casing and styling.

**Describe alternatives you've considered**
Tried xpath 1.0 (no working) - this

`const sanitizedValue = value.replace(/'/gmi, "\\'");`

```
//*[contains(translate(text(), 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz') , '${sanitizedValue}')]
```
neither this

```
//*[contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz') , '${sanitizedValue}')]
```

Tried xpath 2.0 (no supported by all browser) - NO GO

**Additional context**
No additional context

**Comment by iongion** [comment]
Meanwhile finally found a working alternative using xpath 1.0 (Tested in Chrome and Firefox on Linux)

```
Then(
  /(an|a) element containing "(.*)" text (should exist|exists)/,
  (_wording1, value, _wording2) => {
    const sanitizedValue = value.replace(/'/gmi, "\\'").toLowerCase();
    const selector = `//*[contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz') , '${sanitizedValue}')]`;
    const element = $(selector);
    element.waitForExist(5000, false, `Expected containing text \`${value}\` does not exists!`);
  }
);
```

**Comment by christian-bromann** [comment]
I would suggest to enhance the [selector strategy logic](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/utils/findStrategy.js) to include this when a certain parameter (this is open for suggestions) is provided. If anyone wants to help on that, please reach out we are happy to support!

**Comment by dagoud** [comment]
@christian-bromann now that I am a bit more familiar with the codebase would like to take a look at this one

**Comment by christian-bromann** [comment]
@dagoud any updates on this issue?

**Comment by dagoud** [comment]
Hi @christian-bromann , I have started looking at this but haven't yet got a final solution. Was hoping to look at it in the next week or so.

**Comment by jmalvinez** [comment]
Hi @christian-bromann! I'd like to give this issue a try if it's okay with the original assignee. Btw, I'm a newbie contributor in Hacktoberfest. 😅

iongion's and your tips are very helpful in giving me an idea on how to implement this enhancement.

What does the parameter for enabling case-insensitive text match look like? My guesses are below.
- a new boolean parameter passed to `$` and `$$` which is false by default
- selector ([link text](https://webdriver.io/docs/selectors#link-text), [partial link text](https://webdriver.io/docs/selectors#partial-link-text), [element with certain text](https://webdriver.io/docs/selectors#element-with-certain-text)) is a string that ends with `/i`(similar to regex)

Please let me know if my understanding is wrong though. I'm happy to discuss here or send you a message in Gitter. 🙏

**Comment by christian-bromann** [comment]
> **$('h1.*=Welcome to my Page')**

I suggest this ^^^

**Comment by jmalvinez** [comment]
Thanks @christian-bromann! I'll start working on a PR and let you know if I have any other questions. 😉

**Comment by abubakarafzal** [comment]
Why dont you just add ignoreCase:true

const element = $("h1=Welcome tO mY pAge", { ignoreCase: true})

**Comment by christian-bromann** [comment]
An option property to the `$` and `$$` and other element fetch commands is a viable options as well.

**Comment by lacell75** [comment]
any news on this topic? I am interested in this feature

**Comment by christian-bromann** [comment]
This is a great issue to pick up @lacell75 , any contributions are welcome!

**Comment by AnthonyQuy** [comment]
@christian-bromann I created a PR for this feature which using the .= or .*= approach. Please help reviewing!

If all good, could you help pointing out which document need to be update accordingly (website selectors / example project guide...)

**Comment by AnthonyQuy** [comment]
PR for sample project:
https://github.com/webdriverio/example-recipes/pull/213

**Comment by erwinheitzman** [comment]
Resolved by https://github.com/webdriverio/example-recipes/pull/213
