### ISSUE TITLE
@wdio/allure-reporter v5.10.0 introduced bug with passing status information

### ISSUE THREAD

**Issue by klamping** [webdriverio/webdriverio#4953]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.18.5
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.14.1
 - **NPM version:** 6.13.4
 - **Browser name and version:** Chrome 78
 - **Platform name and version:** OSX 10.13.6
 - **Additional wdio packages used (if applicable):** @wdio/allure-reporter version 5.16.10+

**Config of WebdriverIO**
An example of how you configured WebdriverIO config
https://github.com/klamping/wdio-allure-issue/blob/master/wdio.conf.js

**Describe the bug**
In the latest two versions of `@wdio/allure-reporter`, successful tests are not being reported correctly. 

![failing](https://user-images.githubusercontent.com/706039/72184667-91b76080-33b6-11ea-9b14-01a7fe8a9610.png)

**To Reproduce**
https://github.com/klamping/wdio-allure-issue

**Expected behavior**
Passing tests are reported as passing and all associated steps are reported with them:

![passing](https://user-images.githubusercontent.com/706039/72184683-9bd95f00-33b6-11ea-8336-2356a66bb2dd.png)

**Log**
n/a

**Additional context**
This bug does not occur in wdio/allure-reporter  v5.16.0 or earlier

Related:
https://github.com/webdriverio/webdriverio/pull/4773
https://github.com/webdriverio/webdriverio/pull/4875

**Comment by anto-ac** [comment]
I am experiencing this issue as well. It happened when upgrading to 5.18.6 (from 5.15.3).

It seems to happen only when the spec has a `beforeEach` block.

**Comment by christian-bromann** [comment]
assigned to @sakhi-sl

**Comment by satyasreem** [comment]
I am experiencing the same. Using version 5.18.6
if there is beforeEach or beforeAll in the test spec, the test reporter thinks that the actual test never stops and status becomes undefined
Actual data in the xml generated: 
 `        <test-case start='1582059044616' status='undefined'>
`
Expected:
`        <test-case start='1582059044620' status='passed' stop='1582059057121'>
`

**Comment by satyasreem** [comment]
version 5.16.0 works. So any versions later than that has the bug

**Comment by sakhisheikh** [comment]
I have tested it locally and changed

**Comment by adrian-brown** [comment]
Is this fixed in v6? or v5 will have an update?

**Comment by christian-bromann** [comment]
@adrian-brown please see the label! Help on this issue is appreciated.

**Comment by IlliaSmolin** [comment]
Had the same issue and that's the fix I found:
Add "disableMochaHooks: true" parameter to your wdio.conf.js to the "reporters" array when your allure parameters are described.

The example straight from my wdio.conf.js:

```
//wdio.conf.js
exports.config = {

//...

reporters: ['spec', ['allure', {
    outputDir: 'allure-results',
    disableWebdriverStepsReporting: true,
    disableWebdriverScreenshotsReporting: true,
    disableMochaHooks: true,
  }]],

//...

};
```

Versions (latest on the 03 June 2020 moment):
"webdriverio": "^6.1.12"
"@wdio/allure-reporter": "^6.1.14"
"@wdio/mocha-framework": "^6.1.8"
"mocha": "^7.2.0"

**Comment by anto-ac** [comment]
@IlliaSmolin It's not really a fix, just a workaround.

**Comment by 7artur7** [comment]
Same issue with `beforeEach` hook

"@wdio/allure-reporter": "^6.7.2",
"@wdio/cli": "^6.7.0",
"@wdio/mocha-framework": "^6.7.0",

**Comment by christian-bromann** [comment]
#6076 was merged and hopefully has fixed the issue. Closing. Thank you @oversizedhat

**Comment by hsntngr** [comment]
> Had the same issue and that's the fix I found: Add "disableMochaHooks: true" parameter to your wdio.conf.js to the "reporters" array when your allure parameters are described.
> 
> The example straight from my wdio.conf.js:
> 
> ```
> //wdio.conf.js
> exports.config = {
> 
> //...
> 
> reporters: ['spec', ['allure', {
>     outputDir: 'allure-results',
>     disableWebdriverStepsReporting: true,
>     disableWebdriverScreenshotsReporting: true,
>     disableMochaHooks: true,
>   }]],
> 
> //...
> 
> };
> ```
> 
> Versions (latest on the 03 June 2020 moment): "webdriverio": "^6.1.12" "@wdio/allure-reporter": "^6.1.14" "@wdio/mocha-framework": "^6.1.8" "mocha": "^7.2.0"

thats a quite clever workaround
