### ISSUE TITLE
Update sync with fibers

### ISSUE THREAD

**Issue by matthewcoxx** [webdriverio/webdriverio#4955]
Please update https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-sync/package.json with Fibers 4.0.2 

failing dependency for react-native-windows fresh install.

**Comment by christian-bromann** [comment]
By setting `"fibers": "^4.0.1"` it will automatically install fibers 4.0.2.

**Comment by matthewcoxx** [comment]
This is not the case. 

Fibers is installed in the root node_modules folder as 4.0.2 - /node_modules/fibers/)

but only 4.0.1 is loaded in - /node_modules/@wdio/sync/node_modules/fibers

Clean windows install, clean install.

See below for output:

`error C:\Users\Seventh Knight\SK01\react-native-windows\node_modules\@wdio\sync\node_modules\fibers: Command failed.
Exit code: 1
Command: node build.js || nodejs build.js
Arguments:
Directory: C:\Users\Seventh Knight\SK01\react-native-windows\node_modules\@wdio\sync\node_modules\fibers
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@13.5.0 | win32 | x64
gyp info find Python using Python version 2.7.15 found at "C:\Users\Seventh Knight\.windows-build-tools\python27\python.exe"
gyp info find VS using VS2017 (15.9.28307.960) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\Seventh Knight\.windows-build-tools\python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\Seventh Knight\\SK01\\react-native-windows\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Seventh Knight\\SK01\\react-native-windows\\node_modules\\@wdio\\sync\\node_modules\\fibers\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Seventh Knight\\SK01\\react-native-windows\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Seventh Knight\\AppData\\Local\\node-gyp\\Cache\\13.5.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Seventh Knight\\AppData\\Local\\node-gyp\\Cache\\13.5.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Seventh Knight\\SK01\\react-native-windows\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Seventh Knight\\AppData\\Local\\node-gyp\\Cache\\13.5.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Seventh Knight\\SK01\\react-native-windows\\node_modules\\@wdio\\sync\\node_modules\\fibers',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\Seventh Knight\\SK01\\react-native-windows\\node_modules\\@wdio\\sync\\node_modules\\fibers\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  fibers.cc
  coroutine.cc
c:\users\seventh knight\sk01\react-native-windows\node_modules\@wdio\sync\node_modules\fibers\src\fibers.cc(899): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Seventh Knight\SK01\react-native-windows\node_modules\@wdio\sync\node_modules\fibers\build\fibers.vcxproj]
c:\users\seventh knight\sk01\react-native-windows\node_modules\@wdio\sync\node_modules\fibers\src\fibers.cc(903): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Seventh Knight\SK01\react-native-windows\node_modules\@wdio\sync\node_modules\fibers\build\fibers.vcxproj]
c:\users\seventh knight\sk01\react-native-windows\node_modules\@wdio\sync\node_modules\fibers\src\fibers.cc(909): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\Seventh Knight\SK01\react-native-windows\node_modules\@wdio\sync\node_modules\fibers\build\fibers.vcxproj]
c:\users\seventh knight\sk01\react-native-windows\node_modules\@wdio\sync\node_modules\fibers\src\fibers.cc(927): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments [C:\Users\Seventh Knight\SK01\react-native-windows\node_modules\@wdio\sync\node_modules\fibers\build\fibers.vcxproj]
  win_delay_load_hook.cc
c:\users\seventh knight\sk01\react-native-windows\node_modules\@wdio\sync\node_modules\fibers\src\coroutine.cc(153): warning C4552: '!': result of expression not used [C:\Users\Seventh Knight\SK01\react-native-windows\node_modules\@wdio\sync\node_modules\fibers\build\fibers.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Seventh Knight\SK01\react-native-windows\node_modules\node-gyp\lib\build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:305:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Seventh Knight\\SK01\\react-native-windows\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\Seventh Knight\SK01\react-native-windows\node_modules\@wdio\sync\node_modules\fibers
gyp ERR! node -v v13.5.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'``

**Comment by matthewcoxx** [comment]
This is not the case. 

Fibers is installed in the root node_modules folder as 4.0.2 - /node_modules/fibers/)

but only 4.0.1 is loaded in - /node_modules/@wdio/sync/node_modules/fibers

Clean windows install, clean install.

See below for output:

error C:\Users\xxx\SK01\react-native-windows\node_modules\@wdio\sync\node_modules\fibers: Command failed.
Exit code: 1
Command: node build.js || nodejs build.js
Arguments:
Directory: C:\Users\xxx\SK01\react-native-windows\node_modules\@wdio\sync\node_modules\fibers
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@13.5.0 | win32 | x64
gyp info find Python using Python version 2.7.15 found at "C:\Users\xxx\.windows-build-tools\python27\python.exe"
gyp info find VS using VS2017 (15.9.28307.960) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\xxx\.windows-build-tools\python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\xxx\\SK01\\react-native-windows\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\xxx\\SK01\\react-native-windows\\node_modules\\@wdio\\sync\\node_modules\\fibers\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\xxx\\SK01\\react-native-windows\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\xxx\\AppData\\Local\\node-gyp\\Cache\\13.5.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\xxx\\AppData\\Local\\node-gyp\\Cache\\13.5.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\xxx\\SK01\\react-native-windows\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\xxx\\AppData\\Local\\node-gyp\\Cache\\13.5.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\xxx\\SK01\\react-native-windows\\node_modules\\@wdio\\sync\\node_modules\\fibers',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\xxx\\SK01\\react-native-windows\\node_modules\\@wdio\\sync\\node_modules\\fibers\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  fibers.cc
  coroutine.cc
c:\users\xxx\sk01\react-native-windows\node_modules\@wdio\sync\node_modules\fibers\src\fibers.cc(899): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\xxx\SK01\react-native-windows\node_modules\@wdio\sync\node_modules\fibers\build\fibers.vcxproj]
c:\users\xxx\sk01\react-native-windows\node_modules\@wdio\sync\node_modules\fibers\src\fibers.cc(903): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\xxx\SK01\react-native-windows\node_modules\@wdio\sync\node_modules\fibers\build\fibers.vcxproj]
c:\users\xxx\sk01\react-native-windows\node_modules\@wdio\sync\node_modules\fibers\src\fibers.cc(909): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\Users\xxx\SK01\react-native-windows\node_modules\@wdio\sync\node_modules\fibers\build\fibers.vcxproj]
c:\users\sxxx\sk01\react-native-windows\node_modules\@wdio\sync\node_modules\fibers\src\fibers.cc(927): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments [C:\Users\xxx\SK01\react-native-windows\node_modules\@wdio\sync\node_modules\fibers\build\fibers.vcxproj]
  win_delay_load_hook.cc
c:\users\xxx\sk01\react-native-windows\node_modules\@wdio\sync\node_modules\fibers\src\coroutine.cc(153): warning C4552: '!': result of expression not used [C:\Users\xxx\SK01\react-native-windows\node_modules\@wdio\sync\node_modules\fibers\build\fibers.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\xxx\SK01\react-native-windows\node_modules\node-gyp\lib\build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:305:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxx\\SK01\\react-native-windows\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\xxx\SK01\react-native-windows\node_modules\@wdio\sync\node_modules\fibers
gyp ERR! node -v v13.5.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'`

**Comment by christian-bromann** [comment]
> Fibers is installed in the root node_modules folder as 4.0.2 - /node_modules/fibers/)

Do you have fibers installed as dependency?

**Comment by matthewcoxx** [comment]
Yes, I do. I went to Fibers, they recommended upgrading to 4.0.2 which I did for the main dependency and that works fine but when I do yarn install since this is a sub dependency it overwrites every time to 4.0.1 which breaks everything.

**Comment by christian-bromann** [comment]
If you don't need Fibers as part of your project you don't need to have it as part of your dependency. WebdriverIO uses [latest fibers](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-sync/package.json#L38).
