### ISSUE TITLE
'WARN @wdio/config:ConfigParser: pattern refs/heads/master did not match any file' error encountered

### ISSUE THREAD

**Issue by Geloloboy** [webdriverio/webdriverio#4957]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.16.16
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 13.4.0
 - **NPM version:** 6.13.1
 - **Browser name and version:** Chrome 79.0.3945
 - **Platform name and version:** MacOs 10.14.6
 - **Additional wdio packages used (if applicable):** @wdio/allur-reporter, @wdio/cli, @wdio/local-runner, @wdio/mocha-framework, @wdio/spec-reporter, @wdio/sync, wdio-chromedriver-service

**Config of WebdriverIO**
`
specs: [
        'tests/webdriverio/specs/*.js'
    ],
`

**Describe the bug**
I've added the 'wdio wdio.conf.js' command as part of git's pre-push hook. After creating a commit and trying to push, I'm getting no spec files found because the pattern it sees is not the one I entered. An example of the error is:
`2020-01-14T02:40:29.246Z WARN @wdio/config:ConfigParser: pattern refs/heads/master 7ccac50637a37eca229762092b4d00d79e3efc2e refs/heads/master a4336b7840ec532da1f3abd7b33305575d72dc64 did not match any file`

**To Reproduce**
a. Clone the following repo: https://github.com/Geloloboy/wdioParserIssue.git
b. Copy the contents on the file `/scripts/git-hooks/pre-push copy` to `/scripts/git-hooks/pre-push`
c. run `npm install`
d. commit the changes you did
e. run `git push`

**Expected behavior**
Wdio finds the spec files and runs the tests

**Additional context**
Wdio works properly when there are no commits before running `git push`
Also works properly outside the pre-push hooks

**Comment by christian-bromann** [comment]
@Geloloboy can you provide a minimal reproducible example?

**Comment by Geloloboy** [comment]
@christian-bromann I've added a reproducible example for reference

**Comment by christian-bromann** [comment]
This happens because when you run wdio from within a git hook, it will pipe in the changed git object which is the same as if you would:

```js
echo 'some git objects' | wdio wdio.conf.js
```

WebdriverIO then reads the spec data from stdin. In order to avoid that you can do the following in your `e2e` npm script:

```js
"e2e": "wdio wdio.conf.js < /dev/null",
```
