### ISSUE TITLE
Provide with meaningful message if path is invalid

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4958]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6

**Config of WebdriverIO**
- using selenium-standalone 
- have no value for `path` in config (or set it to `'/'`)

**Describe the bug**
Since https://github.com/webdriverio/webdriverio/pull/4907 is implemented we need to handle `path` related error more nicely.
Instead of the error in logs we can guide user to check `path` in config.

**To Reproduce**
1. run any test

**Log**
```
[0-0] Error: Failed to create session.
The `url` option cannot be used if the input is a valid URL.
```

**Comment by christian-bromann** [comment]
The error was caused because `got` tempered the params object I passed in. Proposed a fixed.
