### ISSUE TITLE
Unable to generate autocomplete suggestions for Devtools Service

### ISSUE THREAD

**Issue by Dileep17** [webdriverio/webdriverio#4962]
**Pre-check**
- [x ] I'm aware that I can [edit the docs](https://webdriver.io/docs/autocompletion.html) and submit a pull request

**Describe the improvement**

I'd like to report
- [x] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Description of the improvement / report**
[Auto Completion](https://webdriver.io/docs/autocompletion.html) page suggests how to set jsconfig.json. But this doesn't provide example on how to set auto complete for webdriverio services such as Devtools. 

Steps
1. Create a project with steps described in https://webdriver.io/docs/gettingstarted.html
2. Add jsconfig.json as described in https://webdriver.io/docs/autocompletion.html
   --- autocomplete works fine as expected in visual code
3. run
         ```
          npm install @wdio/devtools-service --save-dev
         ```
autocomplete or autosuggest for methods offered by devtools is not working in visual code.
 ex:- browser.enablePerformanceAudits() or  browser. getMetrics()

I tried to check if autosuggest is working by adding "node_modules/@wdio/devtools-service" to jsconfig.json, without any luck.

Please add documentation on how to get autocomplete working for webdriverio services

Thank you!

**Comment by christian-bromann** [comment]
> Please add documentation on how to get autocomplete working for webdriverio services

Any help would be much appreciated!

**Comment by christian-bromann** [comment]
For anyone who likes to pick this up, the following needs to be done: for every command implemented in the [devtools package](https://github.com/webdriverio/webdriverio/tree/master/packages/devtools/src/commands) a comment needs to be placed in front of every exposed function - similar to how it is implemented with all [WebdriverIO commands](https://github.com/webdriverio/webdriverio/tree/master/packages/webdriverio/src/commands/browser). The information describing each command can be obtained from the [protocol docs](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-protocols/protocols/webdriver.json). Please reply if anything is unclear.

**Comment by thescripted** [comment]
Hey! I'd be happy to pick this up if no one has been assigned yet.

**Comment by christian-bromann** [comment]
@thescripted it's now assigned to you 😉

**Comment by christian-bromann** [comment]
@thescripted how are things going? Is there anything I can help you with?

**Comment by thescripted** [comment]
Hey, I greatly apologize. I got my priorities mixed up. 

I've made some progress and l should be able to finish it up within a few days!

I'll reach out if I have any questions.

**Comment by christian-bromann** [comment]
Let's continue discussions in #5395
