### ISSUE TITLE
document touchPerform with my example

### ISSUE THREAD

**Issue by MagicPoulp** [webdriverio/webdriverio#4968]
**Pre-check**
- [ x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [x ] Missing documentation
- [ ] Other

**Description of the improvement / report**

I could not find where the doc for the website lies in your repository. So please tell me where I can request to update this doc. Is it somewhere on the webdriver.io website?

THis doc on the webdriver io website lacks a working example for touchPerform. I made one below and it works 100%.
https://webdriver.io/docs/api/appium.html#touchperform

If you tell me wheere this link above lies in your repo, I can make a PR on it. But I searched a lot and I cannot find it.

```
  // the anchor represents the vertical location
  async horizontalSwipeByPercentage({ startPercentage, endPercentage, anchorPercentage }) {
    const driver = this.driver;
    const { width, height } = await driver.getWindowSize();
    const anchor = height * anchorPercentage / 100;
    const startPoint = width * startPercentage / 100;
    const endPoint = width * endPercentage / 100;
    await driver.touchPerform([
      {
        action: 'press',
        options: {
          x: startPoint,
          y: anchor,
        },
      },
      {
        action: 'wait',
        options: {
          ms: 1000,
        },
      },
      {
        action: 'moveTo',
        options: {
          x: endPoint,
          y: anchor,
        },
      },
      {
        action: 'release',
        options: {},
      },
    ]);
  }

  async swipeScreenToLeft() {
    await this.horizontalSwipeByPercentage({
      startPercentage: 90,
      endPercentage: 10,
      anchorPercentage: 50
    });
  }

```

**Comment by christian-bromann** [comment]
There should be an "Edit" button at the top of the page:

![Screen Shot 2020-02-10 at 10 13 57 AM](https://user-images.githubusercontent.com/731337/74136440-547d0300-4bee-11ea-9193-1cb5428e4134.png)

It seems that it didn't link correctly to the right place so I fixed it in my PR.
