### ISSUE TITLE
How to integrate APPIUM with WDio?

### ISSUE THREAD

**Issue by Taimur-rasheed** [webdriverio/webdriverio#4969]
I am new to mobile testing and I am working on integrating WDio with APPIUM as per the demand of one of my clients. Please provide any insight into this. 

Thanks.

**Comment by wswebcreation** [comment]
Please check the boilerplates here https://webdriver.io/docs/boilerplate.html and of join our Gitter channel

**Comment by Taimur-rasheed** [comment]
I am more than fine with joining your gitter channel but does the link you
sent contains everything that it takes to make a successful integration?

**Comment by wswebcreation** [comment]
Yes, it refers to the Appium-boilerplate 🎉

**Comment by Taimur-rasheed** [comment]
Let me go through it again. And if I encounter an error, I will let you
know.
Thanks :)
