### ISSUE TITLE
dragAndDrop not working in version 2.4.5

### ISSUE THREAD

**Issue by nileshrapidops** [webdriverio/webdriverio#497]
{ [RuntimeError: RuntimeError
     (ElementNotScrollable:34) Element cannot be scrolled into view.
     Problem: Offset within element cannot be scrolled into view: (0, 0): [object HTMLLIElement]
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'ashish-desktop', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.8.0-44-generic', java.version: '1.7.0_75'
Driver info: driver.version: unknown

**Comment by christian-bromann** [comment]
What browser / OS combination are you using?

**Comment by nileshrapidops** [comment]
i am using firefox-11.0 in ubuntu. I took clone of master branch than it is working fine. Can you tell me what is the problem?

**Comment by christian-bromann** [comment]
oh so with the master branch clone it works but not with the NPM version?

**Comment by Robinfr** [comment]
It's probably fixed by the moveTo fix I made a whole back.

**Comment by christian-bromann** [comment]
I see, well seems to be a good idea to release `v2.5.0` before continuing with `v3`
@nileshrapidops I will put that together asap

**Comment by nileshrapidops** [comment]
yes, with NPM version it is not working but with master branch it is working. thank you christian

**Comment by nileshrapidops** [comment]
@christian-bromann please release 2.5.0 as soon as possible

**Comment by christian-bromann** [comment]
@nileshrapidops feel free to grab the master version via NPM directly. Don't really want to publish something that isn't stable yet

**Comment by ggiunta** [comment]
Hi @christian-bromann dragAndDrop is not working for me either (v2.5.0, OSX firefox/chrome driver)

I'm not getting an error, but the element is just not being drop for some reason.

Are you planning to release 2.5.0 any time soon?

**Comment by Robinfr** [comment]
Should be fixed in v3.
