### ISSUE TITLE
Add multiremote commands to allure reporter 

### ISSUE THREAD

**Issue by kevinmcdonnell** [webdriverio/webdriverio#4973]
**Is your feature request related to a problem? Please describe.**
Allure reporter currently excludes multiremote commands from being shown in the reporter. It would be useful to have this data

**Describe the solution you'd like**
Multiremote commands would be logged in allure with their request JSON

**Describe alternatives you've considered**

**Additional context**
The exclusion seems to occur here https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-allure-reporter/src/index.js#L187-L189

By removing the check for multiremote  we could have the requests logged. Some data eg the sessionId is missing though so we cannot not attribute the request to a session. 

`browser.sessionId` here is returning `undefined` and I'm not sure how to fix this to return the sessionId of the correct multiremote browser: https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-runner/src/index.js#L216

Any pointers to getting the correct sessionId and I think I can fix this

**Comment by ccharnkij** [comment]
<img width="1244" alt="Screen Shot 2020-02-14 at 1 39 51 @kevinmcdonnell M" src="https://user-images.githubusercontent.com/13144677/74569736-f6268c00-4f2f-11ea-9791-961fea15fa36.png">
@kevinmcdonnell Is this what you're referring to? This was done with multiremote of Chrome and Firefox.

**Comment by christian-bromann** [comment]
@kevinmcdonnell any feedback on this? Otherwise I will close as it seems to be work as intended.

**Comment by kevinmcdonnell** [comment]
This is still an issue, the code exits if multiremote rather than trying to log commands

**Comment by kevinmcdonnell** [comment]
🤔 I don't see how that is possible
https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-allure-reporter/src/index.js#L202-L204

@ccharnkij can you provide the wdio.conf for that test run.

**Comment by christian-bromann** [comment]
@kevinmcdonnell can you maybe provide a reproducible example?

**Comment by BorisOsipov** [comment]
Hi! We have rewritten the reporter to the new allure-js version. Please try version 8.5.0 of wdio-allure-reporter and provide more details if the issue still persists. Feel free to create a new issue with actual details if it reproduces.
