### ISSUE TITLE
test.error is not a valid object

### ISSUE THREAD

**Issue by wazp** [webdriverio/webdriverio#4979]
**Environment (please complete the following information):**
 - **WebdriverIO version:** `5.18.6`
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** `13.1.0`
 - **NPM version:** `6.12.1`
 - **Browser name and version:** -
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** -

**Config of WebdriverIO**
See https://github.com/wazp/wdio_test/blob/master/wdio.conf.js

**Describe the bug**
When accessing the `test` argument from various hooks, like `afterTest()`, it gives a malformed object as the error key.

**To Reproduce**

Clone repo and run test case

```bash
> git clone https://github.com/wazp/wdio_test.git
> npm i
> npx wdio run ./wdio.conf.js
```

**Expected behavior**
The `console.log` output of `test.error` should have the actual error printout as a key, and not just dangling before the actual object that now only includes one key, `test.error.name`.

**Log**
https://gist.github.com/wazp/0bb646fe7810625f34f5feb9c043d9cf

I added some console.log's to the output in `afterTest()` to show the malformed object, so it's visible in these logs. Look for the `--------------------` to find the relevant output.

**Additional context**
In v.4 the error information used to be available under `test.err` with two keys, `message` and `type`. We used this information to write special descriptions that we post to the CrossBrowserTesting api for marking snapshots with the error message etc.

Thanks!

**Comment by BorisOsipov** [comment]
It isnt "malformed" object. Just `error` property isn't enumerable.
Check by `console.log(JSON.stringify(test.error, Object.getOwnPropertyNames(test.error)))`

From the docs of [JSON.stringify()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify),

> For all the other Object instances (including Map, Set, WeakMap and WeakSet), only their enumerable properties will be serialized.

**Comment by wazp** [comment]
Ah, right. That is super cool, I didn't think of it being a non-enumerable property at all, first time I see it used on non-browser builtin objects.

However, I do still think it is a bug as it used to be enumerable on previous versions, and you have to jump through some hoops to get the value of it now. Something that used to be very trivial. Maybe some documentation around it? When printing it out you can't even see that the property key in question is called `message` without going through `Object.getOwnPropertyNames()`.

At least I learned something new today! :)

Thanks!

**Comment by erwinheitzman** [comment]
@wazp that's because the error you mention is in instance of the [Error object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) which works like this.
When using TypeScript you'd (probably) be able to see this or you will be when you assign the Error type.
In the link you find all the properties that live on the object/prototype :)

Glad you learned something but as the Error type is a well known standard I wouldn't like to change this personally.

**Comment by wazp** [comment]
Sounds good, thanks!
