### ISSUE TITLE
use native Promise in v3

### ISSUE THREAD

**Issue by Emigre** [webdriverio/webdriverio#498]
The v3 branch uses Q as a promises library. Why not to use Promises instead? 

Updating the Node version would allow webdriver.io to use the native Promises. They are available from 0.11.13 on.

**Comment by christian-bromann** [comment]
mhm .. I don't see anything in the docs. Do you have a link? Probably only with harmony flag set, right?

**Comment by grofit** [comment]
I believe the OP is correct, they did add them as native, but there are one or two problems with them:

http://stackoverflow.com/questions/21564993/native-support-for-promises-in-node-js

**Comment by Emigre** [comment]
Hey, hello. You don't need the harmony flag to use them. Check them, you can open the REPL and play around if you have the right version of node.
This link lists the ES6 stuff in node: [ES6 (a.k.a. Harmony) Features Implemented in V8 and Available in Node](https://github.com/joyent/node/wiki/ES6-%28a.k.a.-Harmony%29-Features-Implemented-in-V8-and-Available-in-Node)
I didn't know of any memory leak issues, though!

**Comment by mnichols** [comment]
+1 for a promise lib that tries to implement ES6 proposal instead of its own

**Comment by lwhorton** [comment]
Might I recommend [bluebird](https://github.com/petkaantonov/bluebird)? It's been proven time and time again as one of the fastest and most feature-rich implementations yet.

**Comment by grofit** [comment]
+1 as I never did it before, I use Bluebird for my promise handling and it is very performant and stable, however as long as you use any standards based promise lib you are going to be onto a winner.

**Comment by christian-bromann** [comment]
Thanks for your suggestions. I totally +1 to go with anything that is ES6 compliant. The current implementation is based on the q library. I am kind of afraid to use the native promise implementation as it forces everyone to update their node version and I know that there are many people still running node 10.x or maybe lower.

**Comment by AndreTheHunter** [comment]
I've used ```require('es6-promise').polyfill()``` in production on node 10.x without any trouble.
+1 for [native Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)

**Comment by tnguyen14** [comment]
Using [babel](http://babeljs.io) might help with the node environment issue.

**Comment by christian-bromann** [comment]
To release `v3` faster I will skip this for now and move it to the `v3.1` milestone. I am actually pretty happy with the Q library. I actually don't really see a reason to switch to bluebird or native promises now. This might get more interesting when running multiple jobs at once in regards of performance.

**Comment by georgecrawford** [comment]
Another vote for `require('es6-promise').polyfill()`

**Comment by christian-bromann** [comment]
Just wanna let u guys know that `v4` will be written in ES2016 and makes use of native promises. Until we get to the point where everyone has proper support for it we will transpiled to ES5 using Babel

**Comment by Emigre** [comment]
sounds good! :+1:

**Comment by alistair** [comment]
Basically q doesn't work in combination with native Promises anyway.  See #1252

**Comment by christian-bromann** [comment]
> Basically q doesn't work in combination with native Promises anyway

not true! Problem was if you reject with a string it doesn't count as error. This is fixed though with the current version.

**Comment by christian-bromann** [comment]
Will close this issue. We moved to native promises throughout the whole project besides the core webdriverio.js file. I don't think it is possible to replace q here as I need to have some kind of defer object. I also don't see a reason why we should completely get rid of `q`. I won't affect the performance afterall.
