### ISSUE TITLE
Setup a suite for TestObject (SauceLabs RDC) to show results grouped

### ISSUE THREAD

**Issue by jaFerrazza** [webdriverio/webdriverio#4980]
Hey there, I'm trying to set up the test suites results in TestObject (SauceLabs RDC) and the tutorial it's only available for Java and I couldn't find any leads on how to set it up with wdio, was wondering if it's possible to do it. 

**Environment (please complete the following information):**
 - **WebdriverIO version: 5.10.9
 - **Mode:** Appium / Sauce service
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.16.0
 - **NPM version:** 6.9.0
 - **Platform name and version:** Android / iOS

**Additional context**
If it's possible to hand me a boiler plate project, it would be nice, thanks in advance.

**Comment by wswebcreation** [comment]
Hi @jaFerrazza 

Test suites are deprecated in Test Object/Sauce Labs so this will not work. Please contact your CSM about this.

Going to close this issue, but it's still open for discussion

**Comment by jaFerrazza** [comment]
Thanks for the quick response @wswebcreation ! I'll contact my CSM as you suggest.
