### ISSUE TITLE
using webdriverIO to get elements without attribute

### ISSUE THREAD

**Issue by wallage1216** [webdriverio/webdriverio#4983]
i am trying to find all elements on the GUI of an electron app that have a class 'tick-icon' and no attribute 'hidden'. I can't figure out the webdriverIO selector to do this. also i tried looping over all 'tick-icon' elements and get the 'hidden' attribute but that didn't work either.

a portion of the GUI code looks like this:

`<div _ngcontent-xte-c17="" class="light_shaping_cct_output_1-tick-icon tick-icon active" hidden=""><img _ngcontent-xte-c17="" alt="Tick" src="assets/icons/green_tick.png"></div>`

`<div _ngcontent-xte-c17="" class="light_shaping_cct_output_1-tick-icon tick-icon active"><img _ngcontent-xte-c17="" alt="Tick" src="assets/icons/green_tick.png"></div>`

with the following code i get all the elements including the ones with hidden attribute:

`const CheckMarks = await app.client.$$('.tick-icon')`

**Comment by christian-bromann** [comment]
try:

```js
const CheckMarks = await app.client.$$('div[hidden=""]')
```

**Comment by wallage1216** [comment]
> try:
> 
> ```js
> const CheckMarks = await app.client.$$('div[hidden=""]')
> ```

Hi Christian, that would have worked if I only had these two lines of html. Hoever the application is much large with more div lines was hidden. I need a query for all I stances with class=tick-icon and not having a hidden attribute

**Comment by christian-bromann** [comment]
> I need a query for all instances with class=tick-icon and not having a hidden attribute

Ah, then this:

```js
const CheckMarks = await app.client.$$('.tick-icon')
const notHidden = (
    await Promise.all(CheckMarks.map(
        async (el) => await el.getAttribute('hidden') !== null)
    )
).filter(Boolean)
```

**Comment by wallage1216** [comment]
> > I need a query for all instances with class=tick-icon and not having a hidden attribute
> 
> Ah, then this:
> 
> ```js
> const CheckMarks = await app.client.$$('.tick-icon')
> const notHidden = (
>     await Promise.all(CheckMarks.map(
>         async (el) => await el.getAttribute('hidden') !== null)
>     )
> ).filter(Boolean)
> ```

thanks again for your support.
if I implement this code i get an error:

"TypeError: el.getAttribute is not a function"
