### ISSUE TITLE
Not able to skip session start for excluded specs using Mocha

### ISSUE THREAD

**Issue by kapilag** [webdriverio/webdriverio#4987]
**Environment (please complete the following information):**
 - **WebdriverIO version:**^5.18.6
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v12.5.0
 - **NPM version:** 6.10.2
 - **Browser name and version:** 79.0.39
 - **Platform name and version:** Mac
 - **Additional wdio packages used (if applicable):** chromeservice

**Config of WebdriverIO**
./node_modules/.bin/wdio config -y

**Describe the bug**
Webdriverio in not able to skip session starting if specs are skipped  using `xdescribe()` or `describe.skip()` or any other option.

As mentioned in [this](https://webdriver.io/blog/2019/11/01/spec-filtering.html) blog post, i have added spec filtering to wdio config file 

**To Reproduce**

1. Create sample project with mocha,chromedriver service using [this](https://webdriver.io/docs/gettingstarted.html) guide
2. Add few more spec files, simply by copy pasting basicspec.js to basicspecs_1.js
3. Mark specs in other spec file which is basicspec_1.js as `xdescribe` or `describe.skip()`
4. Run spec and observe chrome session

```
exports.config = {
    runner: 'local',
    path: '/',
    specs: [
        './test/specs/**/*.js'
    ],
    maxInstances: 10,
    capabilities: [{
        maxInstances: 5,
        browserName: 'chrome',
    }],
    logLevel: 'trace',
    bail: 0,
    baseUrl: 'http://localhost',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    services: ['chromedriver'],
    
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },
    featureFlags: {
        specFiltering: true // enable spec filtering feature
    }
}

```

**Expected behavior**
Only one chrome session to be opened

**Log**

**Additional context**

**Comment by kapilag** [comment]
@christian-bromann , @mgrybyk , I am bit lost over here, there is another related issue raised: [here](https://github.com/webdriverio/webdriverio/issues/5061) and seems over there it is working, whereas this issue is marked as good first pick, is there some problem with my config file ?

**Comment by christian-bromann** [comment]
I haven't had a chance to look into this therefor I am not sure if these issues are related. Any help on this is appreciated.

**Comment by christian-bromann** [comment]
@kapilag this has been fixed with v6 of WebdriverIO. Closing.
