### ISSUE TITLE
performActions on click doesn't work in Firefox.

### ISSUE THREAD

**Issue by GineaPig** [webdriverio/webdriverio#4988]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 5.10.9]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync]
 - **Node.js version:** [e.g. 10.15.3]
 - **NPM version:** [e.g. 6.4.1]
 - **Browser name and version:** [e.g. Firefox 72.0.2 (64-bit)]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Describe the bug**
I use the browser.performActions() function to do a click in a position in Firefox, but the click action is not executed on this position.

**To Reproduce**

var action=[
    {
        "type": "pointer",
        "id": "finger",
        "parameters": {"pointerType": "mouse"},
        "actions": [
            {"type": "pointerDown", "button": 0},
            {"type": "pointerUp", "button": 0}
        ]
    }
]

 $('selector').moveTo();
 browser.performActions(action);

**Expected behavior**
The mouse should click on the position in Firefox.

**Additional context**
browser.positionClick() can successfully click on the position in Chrome, but when I use this browser.performActions() function to click on a position in Firefox, the position is not clicked.

> Please use the correct markdown

**Comment by christian-bromann** [comment]
@GineaPig I recommend to have a small pause in the middle. Unfortunately I have to close this issue as this can't be fixed in WebdriverIO. If my suggestion doesn't work I recommend to create a ticket in the GeckoDriver project. Cheers!
