### ISSUE TITLE
Fix type for ChromeDriver refs

### ISSUE THREAD

**Issue by lamkovod** [webdriverio/webdriverio#4989]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 5.18.6]

**Describe the bug**
Type for `'goog:chromeOptions'.refs` is not valid.
In Chrome documentation (https://chromedriver.chromium.org/capabilities) code example can be found: 
```
Map<String, Object> prefs = new HashMap<String, Object>();
prefs.put("profile.default_content_settings.popups", 0);
```
Just replace `prefs?: string[]` -> `prefs?: { [name: string]: string | number | boolean }`

**Comment by christian-bromann** [comment]
@lamkovod feel free to provide a PR with a fix. Thanks!

**Comment by christian-bromann** [comment]
PR got merged. Closing. Thanks for the contribution!
