### ISSUE TITLE
AWS Device Farm (remote) URL config is being parsed incorrectly.

### ISSUE THREAD

**Issue by kapoorlakshya** [webdriverio/webdriverio#4991]
**Environment:**

 - **WebdriverIO version:** 5.18.6
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 13.3.0
 - **NPM version:** 6.13.6
 - **Browser name and version:** Chrome 79 (defined as `latest` in config)
 - **Platform name and version:** macOS Catalina 10.15.2 (local runner)
 - **Additional wdio packages used (if applicable):**

```
"@wdio/cli": "^5.18.6",
"@wdio/local-runner": "^5.18.6",
"@wdio/mocha-framework": "^5.18.6",
"@wdio/selenium-standalone-service": "^5.0.0",
"@wdio/spec-reporter": "^5.18.6",
"@wdio/sync": "^5.18.6",
```

**Config of WebdriverIO**

I'm following the AWS guide here to get the `hostname` and `path` below: https://docs.aws.amazon.com/devicefarm/latest/testgrid/testing-frameworks-nodejs.html

```
exports.config = {
  runner: 'local',
  hostname: 'testgrid-devicefarm.us-west-2.amazonaws.com',
  path: 'AQICAHiRxhO-<redacted-long-string>_s1KzZx_a4zfHB2YtrdnY=/wd/hub',
  port: 443,
  protocol: 'https',
  specs: ['./specs/**/*.js'],
  maxInstances: 1,
  capabilities: [
    {
      browserName: 'chrome',
      browserVersion: 'latest',
      platform: 'windows'
    },
  ],
  sync: true,
  deprecationWarnings: true, // Warns when a deprecated command is used
  logLevel: 'debug',
  bail: 0,
  framework: 'mocha',
  reporters: ['spec'],
  mochaOpts: {
    ui: 'bdd',
    timeout: 60000
  }
}
```

**Describe the bug**

Based on the config shared above, the expected remote URL should have the `port` placed correctly after the `hostname`, but it is instead placed right before the `path`:

```
Expected: https://testgrid-devicefarm.us-west-2.amazonaws.com:443/AQICAHiRxhO-<redacted-long-string>_s1KzZx_a4zfHB2YtrdnY=/wd/hub

Actual: https://testgrid-devicefarm.us-west-2.amazonaws.com/:443AQICAHiRxhO-<redacted-long-string>_s1KzZx_a4zfHB2YtrdnY=/wd/hub/session
```

**To Reproduce**

1. Setup AWS Device Farm for Desktop browser testing. Follow [this guide](https://docs.aws.amazon.com/devicefarm/latest/testgrid/getting-started-migration.html) to set up a Project and get the project ARN.
2. Using AWS CLI, generate the remote hub URL. Steps are in [this guide](https://docs.aws.amazon.com/devicefarm/latest/testgrid/testing-frameworks-nodejs.html).
3. Configure `webdriverio` to use the remote hub URL as instructed in the guide linked in step 2.

**Expected behavior**

The remote URL should be properly parsed as:

`https://testgrid-devicefarm.us-west-2.amazonaws.com:443/AQICAHiRxhO-<redacted_long_string>_s1KzZx_a4zfHB2YtrdnY=/wd/hub`

**Log**

See lines 9 and 29 here: https://gist.github.com/kapoorlakshya/a3ced4d98f2d03300e3b230a1211b852

**Additional context**

I am new to both `webdriverio` and AWS Device Farm. Unfortunately, there is no service available for Device Farm as the desktop browser feature was only recently launched (01/14). I am trying to follow the doc on AWS and look at examples of the various `conf` files to make this work. My understanding is that once the `protocol`, `hostname`, `port`, and `path` are correctly configured, a browser session should start on AWS.

It's quite possible I am not doing this correctly, so any guidance will be appreciated.

**Comment by kapoorlakshya** [comment]
@christian-bromann Can you please take a look and tell me if I need to provide any other information to classify this as a bug or an invalid report if I am doing something incorrectly?

**Comment by christian-bromann** [comment]
@kapoorlakshya a path needs to start with an `/` so if you update your options to:

```js
  hostname: 'testgrid-devicefarm.us-west-2.amazonaws.com',
  path: '/AQICAHiRxhO-<redacted-long-string>_s1KzZx_a4zfHB2YtrdnY=/wd/hub',
  port: 443,
  protocol: 'https',
``` 

it should work.

**Comment by kapoorlakshya** [comment]
@christian-bromann Thank you very much! Adding "/" makes it work perfectly.

I have notified AWS to update their doc.

**Comment by kapoorlakshya** [comment]
I have finally figured out and documented how I got WebdriverIO to work with the desktop browser service by the AWS Device Farm - https://kapoorlakshya.github.io/executing-webdriverio-browser-tests-aws-device-farm

Hoping to create a service soon, but this works for now :)
