### ISSUE TITLE
element/getCSSProperty examples

### ISSUE THREAD

**Issue by lisli1** [webdriverio/webdriverio#4998]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [x] A typo
- [ ] Missing documentation
- [ ] Other

**Description of the improvement / report**
A clear and concise description.

The [documentation for getCSSProperty](https://webdriver.io/docs/api/element/getCSSProperty.html) shows examples with `element.getCSSProperty('[property-name]')`, but I get the following error when I try to use getCSSProperty in this way: `element.getCSSProperty is not a function`.

However, `element.getCssProperty('[property-name]')` _does_ work (the `s` in CSS are lowercase). I haven't tried to edit the docs directly, since I am unsure which version of the function (getCSSProperty vs getCssProperty) is intended.

**Comment by WillBrock** [comment]
@lisli1 you're likely on version 4 of WebdriverIO and looking at the wrong version of the docs. In v5 it was changed to uppercase.
