### ISSUE TITLE
'client.click' on 'input' of 'type' 'submit' does not work to submit a form

### ISSUE THREAD

**Issue by nottoseethesun** [webdriverio/webdriverio#50]
For me, only 'submitForm' will work here.  So, this is a perfectly fine way to do it, except that a click on a form submit button should work.

**Comment by Nikhil-Wagh** [comment]
@christian-bromann The link is not working. 
I'm still facing the issue.

**Comment by erwinheitzman** [comment]
Still? This issue was in closed in 2013 and doesn't exist today
