### ISSUE TITLE
Multiple sessions at a time

### ISSUE THREAD

**Issue by sean-hill** [webdriverio/webdriverio#500]
Hey does webdriverio support multiple instances at the same time. AKA, running multiple tests asynchronously. I keep getting the error

    Cannot init a new session, please end your current session first

I was wondering if there was a way I could `init()` multiple times for a parallel execution. Thanks!

**Comment by sean-hill** [comment]
I ended up figuring this out by wrapping my selenium / webdriverio script in a separate file, and then from my main file I `require('child_process').fork` that script file and used the `.send()` and `.on()` methods to communicate between the two processes. This allowed webdriverio to `init()` multiple browsers at a time, since they were all in different processes.

**Comment by vbence** [comment]
This is still a valid feature request. It is very misleading that on the main site you can see the following code:
```
var client = webdriverio.remote(options);

client
    .init()
```

...which suggests that there is a point in using a variable for client (if it static, as it is,  then there is none).

**Comment by christian-bromann** [comment]
> This is still a valid feature request

no it is not. You can use wdio to run multiple browser session at a time to test one thing or you can use multiremote to run multiple session in one test

**Comment by dustinboston** [comment]
I have a scenario where this could be useful. I have a Jenkins job that runs integration tests on every commit (by calling webdriverio). When a second commit comes in it will throw the error that @sean-hill mentioned. Do you think there is a better way to do this that would avoid conflicts?

**Comment by christian-bromann** [comment]
@dustinboston I am not sure if this is related. This error is thrown if you try to call init with the same object like 
```js
client.init().init()
```
If you trigger a build with each commit you recreate the object and then it depends if your Selenium server can spawn more instances.

**Comment by dustinboston** [comment]
Yeah I think you're right - sorry about that. Thanks for the help!

**Comment by megamindbrian** [comment]
Weird, if I try to init() after a session fails to reconnect (i.e. lost track of sessionId on my end).  I call init() and it just keeps opening new windows and never returns.  Has anyone seen this before?

**Comment by megamindbrian** [comment]
Stranger, I went to try this again today and found if I did not clear require.cache, I kept getting a single instance from webdriver.remote():

```
Object.keys(require.cache).filter(k => k.includes('webdriver') || k.includes('wdio'))
        .forEach(k => delete require.cache[k]);
```
