### ISSUE TITLE
Initialize new driver instance in spec if needed

### ISSUE THREAD

**Issue by NeONRAcE** [webdriverio/webdriverio#5009]
**Is your feature request related to a problem? Please describe.**
Our team project needs to launch 2 browsers by default and, sometimes, 3 and more driver instances (to check sync with users and other checks). WebdriverIO lets only launch fixed amount of instances using config file (we always have to launch only 2 browsers or only 3 browsers etc.)

**Describe the solution you'd like**
We want to have an opportunity to launch a new driver instance in single .spec file

**Describe alternatives you've considered**
e.g. Protractor supports this format using **forkNewDriverInstance** method (const browser3 = browser.forkNewDriverInstance();), it would be great to have one in WebdriverIO <3

**Additional context**
-

**Comment by christian-bromann** [comment]
@NeONRAcE can you describe a bit more the use case here? For what do you need a new browser in the middle of a test?

**Comment by NeONRAcE** [comment]
> @NeONRAcE can you describe a bit more the use case here? For what do you need a new browser in the middle of a test?
@christian-bromann 
Hello! Our project by-default uses 2 browsers (I know, there is an opportunity to launch them in wdio by-default too). But there are a lot of cases (mb 40%), that need to launch one or two and more additional browsers, for example, to check sync with 2 or more users in one room. That's why we don't launch 5 browsers by default, only two and the others if needed

**Comment by AndrewQA777** [comment]
@christian-bromann Hi! Do you need any additional information to clarify our use-cases? In fact we need something like Protractor's **forkNewDriverInstance()** (https://www.protractortest.org/#/api?view=ProtractorBrowser.prototype.forkNewDriverInstance)

**Comment by christian-bromann** [comment]
@AndrewQA777 clarifying the use case always helps but we already agreed that this feature would be useful for folks which is why we added the labels. Would you be interested helping implementing this?

**Comment by colleenhobbs** [comment]
Hi @christian-bromann -- we are also looking at potentially moving from Protractor to WebdriverIO this year for our E2E tests, but not having an equivalent `forkNewDriverInstance()` would be a bit of a problem for us since we do multi-user E2E testing of our web apps all the time.  Do you know if this is still on the WDIO roadmap?

**Comment by christian-bromann** [comment]
> Do you know if this is still on the WDIO roadmap?

I think this issue is solved as anyone can import WebdriverIO to create a new instance when running the testrunner, e.g.:

```ts
import { remote } from 'webdriverio'

describe('foo', () => {
  it('bar', async () => {
    await browser.url("https://google.com")
    const newBrowser = await remote(browser.options)
    //...
  })
})
```

I think I haven't closed this earlier because this would not work with synchronous execution which we deprecated.

**Comment by colleenhobbs** [comment]
> I think this issue is solved as anyone can import WebdriverIO to create a new instance when running the testrunner

Fantastic news!  Thanks for the info, @christian-bromann :)

**Comment by wyhmichael** [comment]
> > Do you know if this is still on the WDIO roadmap?
> 
> I think this issue is solved as anyone can import WebdriverIO to create a new instance when running the testrunner, e.g.:
> 
> ```ts
> import { remote } from 'webdriverio'
> 
> describe('foo', () => {
>   it('bar', async () => {
>     await browser.url("https://google.com")
>     const newBrowser = await remote(browser.options)
>     //...
>   })
> })
> ```
> 
> I think I haven't closed this earlier because this would not work with synchronous execution which we deprecated.

Hi @christian-bromann double confirm if new instance is initialized like this, is logging going to be aggregated and working directly with setting defined in the wido config?

**Comment by christian-bromann** [comment]
I haven't tried it myself but don't see why not. If issues with reporting can be identified I am happy to support to help working on a bug fix.
