### ISSUE TITLE
How to attach screenshot as an attachment with createStep() API 

### ISSUE THREAD

**Issue by AartiJ** [webdriverio/webdriverio#5010]
**Describe your question with as much detail as possible**
A clear and concise question that doesn't require too much conversation. Need more help? [Find us on Gitter](https://gitter.im/webdriverio/webdriverio)

**If it's about a specific piece of code, try and include some of it to support your question.**
[...]

**Environment (please complete the following information):**
 - **WebdriverIO version:** [4.13.2]
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync/async]
 - **Node.js version:** [8.11.1]
 - **NPM version:** [ 5.6.0]
 - **Browser name and version:** [ Chrome 68]
 - **Platform name and version:** [MAC]
 - **Additional wdio packages used (if applicable):** [@wdio/spec reporter, @wdio/selenium-standalone service]

**Additional context**

**Comment by christian-bromann** [comment]
Sorry but this is not a sufficient issue description. Closing!
