### ISSUE TITLE
How to attach screenshot with Failed Test Case

### ISSUE THREAD

**Issue by AartiJ** [webdriverio/webdriverio#5011]
**Describe your question with as much detail as possible**
I want to know how can I attach screenshot with particular failed test case. Currently all the screenshot comes together at the end.

Currently I am using below code to add screenshot with failed test case. But somehow the screenshots comes all the way at the end instead with the failed test case.

**If it's about a specific piece of code, try and include some of it to support your question.**

       if (loggingEvent.level.levelStr === 'ERROR') {
            if (browser) {reporter.createAttachment('Screenshot', new 
                                     Buffer(browser.screenshot().value, 'base64'), 'image/png');
            }
           reporter.default.addStep(layout(loggingEvent, timezoneOffset), '', 'failed');
       } 

*****************************************************************
I also tried using below code in afterTest() for wdio.conf.js but still it comes at the end instead with the test case

**If it's about a specific piece of code, try and include some of it to support your question.**

      afterTest: function (test) {
        // meta.afterTest++;
        logger.debug('afterTest');

        // if test passed, ignore, else take and save screenshot.
        if (test.passed) {
            return;
        }
        logger.error('Test Failed');
        //ACE-3101 commenting below line since capture screenshot is done in WdioAppender
        let browserName = browser.desiredCapabilities.browserName;
        let timestamp = new Date().toJSON().replace(/:/g, '-');
        let filename = 'TESTFAIL_' + browserName + '_' + timestamp + '.png';
        let filePath = path.join(this.screenshotPath, filename);
        // save screenshot
        browser.saveScreenshot(filePath);
        logger.debug('\tSaved screenshot: ', filePath);
    }

**Environment (please complete the following information):**
 - **WebdriverIO version:** [4.13.2]
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync/async]
 - **Node.js version:** [ 8.11.1]
 - **NPM version:** [5.6.0]
 - **Browser name and version:** [ Chrome 68]
 - **Platform name and version:** [MAC]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Comment by christian-bromann** [comment]
> I want to know how can I attach screenshot with particular failed test case.

You want to attach it to what?

**Comment by AartiJ** [comment]
> > I want to know how can I attach screenshot with particular failed test case.
> 
> You want to attach it to what?

I want to add to the failed test case in allure report. In attached report you can see there are few failed test but all the screenshots are coming at the end instead coming with that particular failed test
<img width="1438" alt="Screen Shot 2020-02-12 at 11 29 57 AM" src="https://user-images.githubusercontent.com/16345762/74355578-0c471780-4d8b-11ea-992e-005ec4cdfced.png">

**Comment by christian-bromann** [comment]
@BorisOsipov any idea?

**Comment by mgrybyk** [comment]
If you want to handle steps manually then you need to add screenshots as attachments to the steps manually as well.
@AartiJ 
Can you share how does your test with steps look like?

**Comment by AartiJ** [comment]
> If you want to handle steps manually then you need to add screenshots as attachments to the steps manually as well.
> @AartiJ
> Can you share how does your test with steps look like?

@majaklajic I am using WebdriverIO with Mocha. So my test is with describe and it blocks. Inside the it block I am calling the method to perform certain action on browser which fails and invokes the Custom WdioAppender implemented using log4JS where I have code to print out the failure with screenshot attachment.

Test 
describe('Test', function() {

    before(function() {
        logger.info('--- Baseline Data initialization ---');
    });

    it(`User should be able to search by Last Week.`,
        function () {
            DocumentActions.refreshTreeToTop(si);
            let page = DocumentsAndFoldersList.getInstance(si);
            let grid = page.documentGrid.find();
            grid.isPopulated(5);
            let filterBtn = page.filterButton.find();
            filterBtn.click();
            waitForPage(si, [DocFilterBox], 10);
            let box = DocFilterBox.getInstance(si);
            box.byDateBtn.click();
            box.lastWeek.click();
            box.applyBtn.click();
            grid.isPopulated(5);
            let files = '';
            try {
                files = grid.scrapeCellContent(CONSTANT_DOC.TITLE, 0);
            } catch (e) {
                logger.info('search result is empty.');
            }

            expect(files !== '', 'search result is not correct.').to.equal(true);
        });
    
    after(async function () {
        // clean up and log off
    });
});

WdioAppender which has code to mark the test fail and do screenshot as an attachment

if (loggingEvent.level.levelStr === 'ERROR') {
            if (browser) {
                    if (browser.screenshot().value !== undefined) {
                        reporter.createAttachment('Screenshot', new Buffer(browser.screenshot().value, 'base64'), 'image/png');
                    }
                }
                reporter.createStep(layout(loggingEvent, timezoneOffset), JSON.stringify(params, null, 2), '', 'failed');
}

**Comment by AartiJ** [comment]
May be if I know that how can I attach screenshot with reporter.createStep(layout(loggingEvent, timezoneOffset), JSON.stringify(params, null, 2), '', 'failed'), then I can get this working. So far I was only able to attach the String and in Wdio documentation also it says that with createStep() I can only do the String type attachment.

**Comment by AartiJ** [comment]
Any help/suggestion on this issue?

**Comment by xywang68** [comment]
`
var cucumberJsReporter = require('wdio-cucumberjs-json-reporter').default;

const myRelativePath = 'relativePath/fromHtmlDir/toImageDir';
const myImageFilename = 'test1-step1-screenshot.png';
const myMp4Filename = 'test1-movie.mp4';
const image_tag = `<img src="${myRelativePath}/${encodeURIComponent(myImageFilename)}" style="max-width: 100%; height: auto;" alt="${myImageFilename}">`;
const video_tag = `<video src="${myRelativePath}/${encodeURIComponent(myMp4Filename)}" style="max-width: 100%; height: auto;" controls/>Your browser does not support the video tag.</video>`; 

cucumberJsReporter.attach(image_tag , 'text/html');
cucumberJsReporter.attach(video_tag , 'text/html');

`

**Comment by mgrybyk** [comment]
I think this one should be fixed now, please let me know if it's still an issue
