### ISSUE TITLE
How to set nativeEvents capability

### ISSUE THREAD

**Issue by xuanzhaopeng** [webdriverio/webdriverio#5013]
**Describe your question with as much detail as possible**
How to set nativeEvents capability, which is NOT in w3c protocol,  but in json wire protocol

**If it's about a specific piece of code, try and include some of it to support your question.**

```
  const [w3cCaps, jsonwpCaps] = params.capabilities && params.capabilities.alwaysMatch ? [params.capabilities, params.capabilities.alwaysMatch] : [{
    alwaysMatch: params.capabilities,
    firstMatch: [{}]
  }, params.capabilities];
```
#refer to https://github.com/webdriverio/webdriverio/blob/2eefa34d71485a956e7b02efa0324c590506a077/packages/webdriver/src/utils.js#L30

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.18.6
 - **Mode:** Standalone 
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 10.15.3
 - **NPM version:** 6.9.0

**Additional context**
1) Is it possible I pass json wire protocol and w3c protocol in the same time?
2) How could pass `nativeEvents ` or other Json wire protocol capabilities

**Comment by christian-bromann** [comment]
The json wire protocol is not supported anymore. `nativeEvents` seems to be a custom capability that needs to get prefixed.
