### ISSUE TITLE
TouchAction not behaving as expected

### ISSUE THREAD

**Issue by fottin** [webdriverio/webdriverio#5017]
**Describe your question with as much detail as possible**
I’m using touchAction as described here https://webdriver.io/docs/api/element/touchAction.html.
There’s no movement when I execute touchAction, other than I see the press occur. Why do the logs not reflect the code being executed?
The logs appear to show the same element used in the 'press' is also used in 'moveTo'
I have the same issue if a different element is specified in 'moveTo'.

**If it's about a specific piece of code, try and include some of it to support your question.**
I implemented the following code.
$('~help').waitForDisplayed(3000);
$('~help').touchAction([
         { action: 'press' },
         { action: 'moveTo', options: { x: 0, y: -232 } },
         { action: 'release' }
 ]);
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.12.4
 - **Mode:** @wdio/local-runner
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:** 10.16.3
 - **NPM version:** 6.9.0
 - **Browser name and version:** 
 - **Platform name and version:** Android 7.0
 - **Additional wdio packages used (if applicable):** @wdio/appium-service, @wdio/cli, @wdio/jasmine-framework, @wdio/local-runner, @wdio/sync, @wdio/spec-reporter

**Additional context**
[HTTP] {"using":"accessibility id","value":"help"}
[debug] [W3C (32d09282)] Calling AppiumDriver.findElement() with args: ["accessibility id","help","32d09282-1db6-41dc-a6e7-b0aa07316277"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/0be38f60-286d-4f3a-8b63-785656d8a3b7/element] with body: {"strategy":"accessibility id","selector":"help","context":"","multiple":false}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"0be38f60-286d-4f3a-8b63-785656d8a3b7","value":{"ELEMENT":"5fa1bb20-7c3f-44cd-b06c-9c279634c896","element-6066-11e4-a52e-4f735466cecf":"5fa1bb20-7c3f-44cd-b06c-9c279634c896"}}
[debug] [W3C (32d09282)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"5fa1bb20-7c3f-44cd-b06c-9c279634c896","ELEMENT":"5fa1bb20-7c3f-44cd-b06c-9c279634c896"}
[HTTP] <-- POST /wd/hub/session/32d09282-1db6-41dc-a6e7-b0aa07316277/element 200 85 ms - 137
[HTTP] 
[HTTP] --> POST /wd/hub/session/32d09282-1db6-41dc-a6e7-b0aa07316277/touch/perform
[HTTP] {"actions":[{"action":"press","options":{"element":"5fa1bb20-7c3f-44cd-b06c-9c279634c896"}},{"action":"moveTo","options":{"element":"5fa1bb20-7c3f-44cd-b06c-9c279634c896"}},{"action":"release"}]}
[debug] [W3C (32d09282)] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"element":"5fa1bb20-7c3f-44cd-b06c-9c279634c896"}},{"action":"moveTo","options":{"element":"5fa1bb20-7c3f-44cd-b06c-9c279634c896"}},{"action":"release"}],"32d09282-1db6-41dc-a6e7-b0aa07316277"]
[UiAutomator2] calling get location: 5fa1bb20-7c3f-44cd-b06c-9c279634c896
[debug] [WD Proxy] Matched '/element/5fa1bb20-7c3f-44cd-b06c-9c279634c896/location' to command name 'getLocation'
[debug] [WD Proxy] Proxying [GET /element/5fa1bb20-7c3f-44cd-b06c-9c279634c896/location] to [GET http://localhost:8200/wd/hub/session/0be38f60-286d-4f3a-8b63-785656d8a3b7/element/5fa1bb20-7c3f-44cd-b06c-9c279634c896/location] with body: {}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"0be38f60-286d-4f3a-8b63-785656d8a3b7","value":{"x":0,"y":1679}}
[debug] [WD Proxy] Matched '/element/5fa1bb20-7c3f-44cd-b06c-9c279634c896/size' to command name 'getSize'
[debug] [WD Proxy] Proxying [GET /element/5fa1bb20-7c3f-44cd-b06c-9c279634c896/size] to [GET http://localhost:8200/wd/hub/session/0be38f60-286d-4f3a-8b63-785656d8a3b7/element/5fa1bb20-7c3f-44cd-b06c-9c279634c896/size] with body: {}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"0be38f60-286d-4f3a-8b63-785656d8a3b7","value":{"width":1440,"height":232}}
[UiAutomator2] calling get location: 5fa1bb20-7c3f-44cd-b06c-9c279634c896
[debug] [WD Proxy] Matched '/element/5fa1bb20-7c3f-44cd-b06c-9c279634c896/location' to command name 'getLocation'
[debug] [WD Proxy] Proxying [GET /element/5fa1bb20-7c3f-44cd-b06c-9c279634c896/location] to [GET http://localhost:8200/wd/hub/session/0be38f60-286d-4f3a-8b63-785656d8a3b7/element/5fa1bb20-7c3f-44cd-b06c-9c279634c896/location] with body: {}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"0be38f60-286d-4f3a-8b63-785656d8a3b7","value":{"x":0,"y":1679}}
[debug] [WD Proxy] Matched '/element/5fa1bb20-7c3f-44cd-b06c-9c279634c896/size' to command name 'getSize'
[debug] [WD Proxy] Proxying [GET /element/5fa1bb20-7c3f-44cd-b06c-9c279634c896/size] to [GET http://localhost:8200/wd/hub/session/0be38f60-286d-4f3a-8b63-785656d8a3b7/element/5fa1bb20-7c3f-44cd-b06c-9c279634c896/size] with body: {}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"0be38f60-286d-4f3a-8b63-785656d8a3b7","value":{"width":1440,"height":232}}
[UiAutomator2] calling get location: 5fa1bb20-7c3f-44cd-b06c-9c279634c896
[debug] [WD Proxy] Matched '/element/5fa1bb20-7c3f-44cd-b06c-9c279634c896/location' to command name 'getLocation'
[debug] [WD Proxy] Proxying [GET /element/5fa1bb20-7c3f-44cd-b06c-9c279634c896/location] to [GET http://localhost:8200/wd/hub/session/0be38f60-286d-4f3a-8b63-785656d8a3b7/element/5fa1bb20-7c3f-44cd-b06c-9c279634c896/location] with body: {}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"0be38f60-286d-4f3a-8b63-785656d8a3b7","value":{"x":0,"y":1679}}
[debug] [WD Proxy] Matched '/touch/down' to command name 'touchDown'
[debug] [WD Proxy] Proxying [POST /touch/down] to [POST http://localhost:8200/wd/hub/session/0be38f60-286d-4f3a-8b63-785656d8a3b7/touch/down] with body: {"params":{"element":"5fa1bb20-7c3f-44cd-b06c-9c279634c896","x":720,"y":1795}}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"0be38f60-286d-4f3a-8b63-785656d8a3b7","value":null}
[debug] [WD Proxy] Matched '/touch/move' to command name 'touchMove'
[debug] [WD Proxy] Proxying [POST /touch/move] to [POST http://localhost:8200/wd/hub/session/0be38f60-286d-4f3a-8b63-785656d8a3b7/touch/move] with body: {"params":{"element":"5fa1bb20-7c3f-44cd-b06c-9c279634c896","x":720,"y":1795}}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"0be38f60-286d-4f3a-8b63-785656d8a3b7","value":null}
[debug] [WD Proxy] Matched '/touch/up' to command name 'touchUp'
[debug] [WD Proxy] Proxying [POST /touch/up] to [POST http://localhost:8200/wd/hub/session/0be38f60-286d-4f3a-8b63-785656d8a3b7/touch/up] with body: {"params":{"x":720,"y":1795}}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"0be38f60-286d-4f3a-8b63-785656d8a3b7","value":null}
[debug] [W3C (32d09282)] Responding to client with driver.performTouch() result: null
[HTTP] <-- POST /wd/hub/session/32d09282-1db6-41dc-a6e7-b0aa07316277/touch/perform 200 2625 ms - 14

**Comment by christian-bromann** [comment]
@fottin looking into the Appium logs it doesn't seem to pass in the right parameters:

```
[POST /touch/down] to [POST .../touch/down] with body: {"params":{"element":"5fa1bb20-7c3f-44cd-b06c-9c279634c896","x":720,"y":1795}}
[POST /touch/move] to [POST .../touch/move] with body: {"params":{"element":"5fa1bb20-7c3f-44cd-b06c-9c279634c896","x":720,"y":1795}}
[POST /touch/up]   to [POST .../touch/up]   with body: {"params":{"x":720,"y":1795}}
```

Without a reproducible example it is hard to say what you are doing. I will close this as I don't see how WebdriverIO is doing something wrong here. Please provide concrete examples otherwise it is impossible for use to debug this.

**Comment by fottin** [comment]
Where would this code:
$('~help').touchAction([
{ action: 'press' },
{ action: 'moveTo', options: { x: 0, y: -232 } },
{ action: 'release' }
]);
be translated to this:
[HTTP] --> POST /wd/hub/session/32d09282-1db6-41dc-a6e7-b0aa07316277/touch/perform
[HTTP] {"actions":[{"action":"press","options":{"element":"5fa1bb20-7c3f-44cd-b06c-9c279634c896"}},{"action":"moveTo","options":{"element":"5fa1bb20-7c3f-44cd-b06c-9c279634c896"}},{"action":"release"}]}

**Comment by christian-bromann** [comment]
the command `$('~help')` seem to resolve into `5fa1bb20-7c3f-44cd-b06c-9c279634c896`

**Comment by fottin** [comment]
Yes, I agree. So I'm trying to understand why moveTo is using 5fa1bb20-7c3f-44cd-b06c-9c279634c896 instead of the coordinates.

**Comment by christian-bromann** [comment]
The code of it is here: https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/commands/constant.js
