### ISSUE TITLE
Update flowcharts

### ISSUE THREAD

**Issue by jdavis61** [webdriverio/webdriverio#5018]
**Pre-check**
- [X ] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**
1. Review the v6.0.0-alpha.1 and update the flow charts.
2. Review the existing flow charts and make them better, easier to understand.

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [ ] Missing documentation
- [X ] Other
Follow up on previous PR [(4873).](https://github.com/webdriverio/webdriverio/pull/4873) 

**Description of the improvement / report**
1. Review the v6.0.0-alpha.1 code base and update the flow charts. Focus on @wdio/cli and other packages suggested by the WebdriverIO team.
2. Review the existing flow charts and make them better, easier to understand.

Feel free to assign this issue to me. (jdavis61)

**Comment by jdavis61** [comment]
Sorry the delay, I will start looking at this ticket soon.

**Comment by jdavis61** [comment]
mermaid.js has introduced a new subroutine shape. I will update the flow charts once this shape is working in the mermaid library. Introducing a subroutine shape into the WebdriverIO flow chart will hopefully make them easier to understand. 

Please see https://github.com/mermaid-js/mermaid/pull/1345 for more information regarding the mermaid.js subroutine shape.

Cheers!

**Comment by jdavis61** [comment]
The mermaid.js team has made the subroutine shape available in their latest release. This is awesome because any method/function call may be represented by a polygon that starts with `[||`, ends with `||]` in the charts.

The ability to express a method/function call in this manner will hopefully make the flowcharts easier to read (when implemented). Also they will be better aligned with current flowchart standards.

See below for example graph, will get a PR in as soon as I can.

Cheers!

![image](https://user-images.githubusercontent.com/16749810/82396153-3576e400-9a1b-11ea-8342-a0134b6d6779.png)

Example mermaid.js code
```
graph TD
  CALLRUN[["@wdio/cli:index run"]]-->
  LAUNCHTESTRUNNER2[Test runner is launched]-->
  CALLRUNCMDHANDLER[["@wdio/cli/commands:run launcher()"]]-->
  INSTANTIATELAUNCHER["Creates @wdio/cli:launcher instance<br>1) Set log level<br>2) Worker count equals number<br>of specs * caps array length<br>3)Create a new runnner instance<br>using @wdio/utils:initialisePlugin<br>4. Create CLI Interface instance.<br>5. Setup interface job:start,<br>job:end event listeners"]-->
  CALLLAUNCHERINSTANCERUN[["@wdio/cli:launcher run()"]]-->
  INITLAUNCHERINSTANCE["Create instance of all services<br>listed in the config services property."]	
```

**Comment by christian-bromann** [comment]
@jdavis61 is there anything left to for this ticket or can it be closed?

**Comment by jdavis61** [comment]
Hi @christian-bromann it can be closed. At some point I want to update the content of the flow charts but not sure when I will have time. I will close now.
