### ISSUE TITLE
make waitForVisible helper less strict

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#502]
__Problem:__
Currently all visibility checks are pretty strict as they check if an element is within the viewport. Mostly people just want to know if something is visible regardless that.

__Proposal:__
Let's have a strict flag for that command. If not set (default) the command just checks `display`, `opacity` and `visibility` css properties otherwise check more strictly (is or is not within the viewport)

**Comment by Robinfr** [comment]
We should also check if the width and height is more than 0 of the element in case of not strict.

**Comment by christian-bromann** [comment]
:+1:

**Comment by christian-bromann** [comment]
Reimplemented all waitFor* commands. They're all using the new `waitUntil` command to check the state of an element. This way you can use the commands on desktop and mobile. In addition I added an command called `isVisibleWithinViewport` that can check whether or not an element is visible and within the viewport. I waived to implement a `waitForVisibleWithinViewport` command as I doubt that this will get used often. If someone wants to have that command it won't cost much effort to add it since it is the same command like `waitForVisible`
