### ISSUE TITLE
Add documentation for running tests in Github Actions

### ISSUE THREAD

**Issue by WilliamFClarke** [webdriverio/webdriverio#5020]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Description of the improvement / report**
Add documentation for running tests using Github Actions.

**Comment by christian-bromann** [comment]
An example how to use GitHub Actions was added to the [Jasmine Boilerplate](https://github.com/webdriverio/jasmine-boilerplate).

**Comment by christian-bromann** [comment]
For anyone interested in helping out improving the docs on this:

- an example on how GitHub Actions can be used to run WebdriverIO tests is demonstrated in the Jasmine Boilerplate (see link in last post)
- I would suggest to create a new documentation page for documenting integration with GitHub actions here: https://github.com/webdriverio/webdriverio/tree/master/docs
- WebdriverIO is using [Docusaurus](https://docusaurus.io/) as static page generator - we don't have any explicit docs on how to work with the docs, it is not much to it besides changing into the [docs directory](https://github.com/webdriverio/webdriverio/tree/master/website) and start the webserver, e.g.:
    ```sh
    $ cd website
    $ npm start
    ```
- the page should be added under the [guide section](https://github.com/webdriverio/webdriverio/blob/master/website/_sidebars.json#L32-L44)
- content wise I am not sure what needs to be documented (maybe @WilliamFClarke can elaborate here) but any kind of documentation would be helpful

This is an excellent chance for someone new to get familiar with code and how the docs are generated.

**Comment by jugalj05hi** [comment]
Hello there, I'm totally new to the world of Open Source and I'd like to give this a try. This would be my first meaningful contribution to the open-source community. 
Thank you.

**Comment by christian-bromann** [comment]
I assigned this task to you! I am super stoked you help us out. Let me know if you have any questions along the way.

**Comment by jugalj05hi** [comment]
Hello there, just to be clear, the documentation should be similar to the one provided in [Jasmine Boilerplate](https://github.com/webdriverio/jasmine-boilerplate/blob/master/README.md) i.e the three points mentioned in quick start section. And what shall be the name of the file be? Pardon me asking silly questions, this is my first contribution and I may find simplest of the task very challenging. Thank you.

**Comment by christian-bromann** [comment]
There are no silly questions!

In the Jasmine Boilerplate I just added an example how such a [GitHub action](https://github.com/webdriverio/jasmine-boilerplate/blob/master/.github/workflows/ci.yaml) could look like. I think the issue authors intention was to have a general documentation page how someone would use WebdriverIO using GitHub actions. So I would create new docs page by adding a markdown file to the [docs directory](https://github.com/webdriverio/webdriverio/tree/master/website) and include a guide how someone would do that (e.g. create a yaml file in `.github/workflows` etc). Feel free to reference the Jasmine Boilerplate as reference.

**Comment by christian-bromann** [comment]
@jugalj05hi any progress so far? Anything I can do to help?

**Comment by jdavis61** [comment]
> * WebdriverIO is using [Docusaurus](https://docusaurus.io/) as static page generator - we don't have any explicit docs on how to work with the docs, it is not much to it besides changing into the [docs directory](https://github.com/webdriverio/webdriverio/tree/master/website) and start the webserver, e.g.:
>   ```shell
>   $ cd website
>   $ npm start
>   ```
When adding the flowcharts I found the below process made creating documentation much easier. Before trying to add documentation, make sure you have [sass](https://sass-lang.com/install) installed in your development environment. Otherwise you will not be able to create the docs.

Once these dependencies have been added, run the below bash commands to create the doc and start the docusaurus server.
```
# At webdriverio root
cd docs
touch mydocument.md
vi mydocument.md or nano mydocument.md
# Add the below code using vi or nano. Include all five lines including --- at the beginning and end of example.
---
id: mydocument
title: My document test
This is a test!
---
# Save file
cd ../
node scripts/docs-generation/generateDocs.js 
npm run docs:build
cd website/
npm run start
```
Once the website server is running it is really easy to see your changes. Go to `http://localhost:8080/docs/mypage.html.`, e.g. `http://localbuild/docs/mydocument.html.`. You will see the original text.

Afterwards, add text to the document, e.g. "This is another test", save `mydocument.md` then refresh page. The new sentence will be visible. 

Hope this helps anyone new to the WebdriverIO documentation system.

**Comment by christian-bromann** [comment]
@jugalj05hi given that we haven't heard from you in a while I will un-assign this issue to allow other people to pick it up. If you haven't found time, no problem! Just let us know 😉

**Comment by ilamparithiNatarajan** [comment]
@christian-bromann I had a go at this #5674 please review. let me know if you think more information needs to be added.

PS. thanks for actively engaging first timers. inspiring work!
