### ISSUE TITLE
Unable to capture browser screenshot on SauceLabs when Mocha's 'bail' is set to true

### ISSUE THREAD

**Issue by rembeckyb** [webdriverio/webdriverio#5021]
**Environment:**
 - **WebdriverIO version:** 4.14.4
 - **Mode:** Testrunner - Mocha and SauceLabs
 - **If WDIO Testrunner, running sync/async:** Sync
 - **Node.js version:** 10.16.0
 - **NPM version:** 6.10.0
 - **Browser name and version:** Chrome v80 
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):**

"dependencies": {
    "rimraf": "^2.6.3",
    "webdriverio": "^4.14.4"
},
"devDependencies": {
    "chai": "^4.2.0",
    "mocha": "^7.0.1",
    "wdio-mocha-framework": "^0.6.4",
    "wdio-sauce-service": "^0.4.14",
    "wdio-spec-reporter": "^0.1.5"
}

**Config of WebdriverIO**

**wdio.conf.json:**

    /*
        The 'global.screenshots' field sets the behavior of which tests capture screenshots
        "both" = Capture screenshots of both passed and failed steps
        "pass" = Capture screenshots of only passed steps
        "fail" = Capture screenshots of only failed steps
        "none" = Do not capture screenshots
    */

    global.screenshots = "both";

    //============================================================

    let mocha = require("mocha");
    global.describe = mocha.describe;
    global.it = mocha.it;

    let chai = require("chai");
    global.expect = chai.expect;
    global.to = chai.to;

    exports.config = {

        user: process.env.SAUCE_USERNAME,
        key: process.env.SAUCE_ACCESS_KEY,
   
        suites: {
            Login: [
                './tests/login/validLogin.js',
            ],
        },

        maxInstances: 40,

        capabilities: [
            {platform: 'Windows 10', browserName: 'chrome', version: '80'},
        ],

        sync: true,

        baseUrl: 'https://www.test.com',

        waitforTimeout: 20000,

        services: ['sauce'],

        framework: 'mocha',

        reporters: ['spec'],

        mochaOpts: {
            ui: 'bdd',
            timeout: 300000,
            bail: true
        },

        afterTest: function (test) {
            let lifecycle = require('./utils/lifecycle');
            lifecycle.endTest(test);
        },

    };

**lifecycle.js:**

    let fs = require('fs');

    let Lifecycle = Object.create(null, {

        endTest: {
            value: function (test) {

                let screenshot = screenshots.toLowerCase().trim();
                let screenshotPath = './reporting/reports/screenshots/';

                if (!fs.existsSync(screenshotPath)) {
                    fs.mkdirSync(screenshotPath, {recursive: true});
                }
                if (screenshot === "both") {
                    let filename = test.title.replace(/ /g, "_").replace(/[\/:*?"<>|']/g, '');
                    let filePath = screenshotPath + filename + '.png';
                    browser.saveScreenshot(filePath);
                } else if (screenshot === "pass") {
                    if (test.passed) {
                        let filename = test.title.replace(/ /g, "_").replace(/[\/:*?"<>|']/g, '');
                        let filePath = screenshotPath + filename + '.png';
                        browser.saveScreenshot(filePath);
                    }
                } else if (screenshot === "fail") {
                    if (!test.passed) {
                        let filename = test.title.replace(/ /g, "_").replace(/[\/:*?"<>|']/g, '');
                        let filePath = screenshotPath + filename + '.png';
                        browser.saveScreenshot(filePath);
                    }
                } else if (screenshot === "none") {
                    //Do nothing
                } else {
                    console.log('Screenshots improperly configured! Please correctly configure the "screenshots" variable located in "wdio.conf.js"');
                }
            }
        },

    });

    module.exports = Lifecycle;

**validLogin.js:**

    let page = require("../../pages/page");
    let home = require("../../pages/home.page");
    let header = require("../../pages/header.page");

    describe("Login - Valid Login", function () {

        it("Access 'login' page", function () {
            expect(page.open()).to.equal(true);
        });

        it("Log into site", function () {
            expect(home.login("username", "password")).to.equal(true);
        });

    });

**Describe the bug**
> I need to terminate the suite once a single test fails.  I accomplish this by setting Mocha's `bail` option to `true`.  I also need to capture a screenshot whenever a test finishes, whether is passes or fails.  However, when `bail` is set to `true`, no screenshots are taken of failed tests. Only passed tests are able to capture a screenshot.  When `bail` is set to `false`, or removed from `wdio.conf.js`, screenshots *are* taken of failed tests, but all tests in the suite are run.

**Expected behavior**
> When a test finishes, a screenshot of the browser should be captured.  When a test fails, the suite should terminate and not execute any remaining tests.

**Log**
> No error of any kind is captured in the logs.

**Comment by erwinheitzman** [comment]
You are running WebdriverIO v4 which is no longer supported. We are actually close to releasing v6 by now so I am sorry to say that you will either have to upgrade or I will have to close this issue.
