### ISSUE TITLE
WaitForOptions link takes you to a 404 page

### ISSUE THREAD

**Issue by wluu** [webdriverio/webdriverio#5024]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Description of the improvement / report**
If you go to `waitForClickable` doc (https://webdriver.io/docs/api/element/waitForClickable.html) and click on `WaitForOptions` link, then you will be taken to a 404 page (https://webdriver.io/docs/api/element/WaitForOptions.html).

![Screen Shot 2020-02-14 at 4 52 33 PM](https://user-images.githubusercontent.com/1141338/74578630-c5078500-4f4a-11ea-91f5-fb2675698b66.png)

**Comment by christian-bromann** [comment]
That must be an issue with the way we generate the markdown for the docs. Any help would be appreciated!

**Comment by christian-bromann** [comment]
Fixed in #5046
