### ISSUE TITLE
Changelog for recent releases

### ISSUE THREAD

**Issue by pathmapper** [webdriverio/webdriverio#5036]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Description of the improvement / report**
Seems like there is no changelog available since `v5.16.16` (except for `v6.0.0-...`):
https://github.com/webdriverio/webdriverio/blob/master/CHANGELOG.md#v51616-2019-12-14

**Comment by christian-bromann** [comment]
@pathmapper this is because we are currently working on v6 on the `master` branch. For v5 please have a look here: https://github.com/webdriverio/webdriverio/blob/v5/CHANGELOG.md
