### ISSUE TITLE
jQuery events don't work?

### ISSUE THREAD

**Issue by silvenon** [webdriverio/webdriverio#504]
I'm not sure if this is a bug, but for some reason a `click` handler assigned by jQuery (v2) doesn't get triggered with`client.click()`. It works if I assign the handler via `addEventListener`.

**Comment by silvenon** [comment]
I think this is a Selenium thing, my bad.

**Comment by silvenon** [comment]
I was sure there is going to be something on the internet about it, but I couldn't find anything, so I'm reopening this.

**Comment by christian-bromann** [comment]
@silvenon are you sure your click gets applied on that particular element?

**Comment by silvenon** [comment]
I'm terribly sorry, my assets didn't load properly. I should've checked my console.

**Comment by christian-bromann** [comment]
no worries .. happy testing :wink:

**Comment by silvenon** [comment]
Thanks, I love WebdriverIO :+1:
