### ISSUE TITLE
How To setup Safari capabilities in wdio

### ISSUE THREAD

**Issue by spatchamatla** [webdriverio/webdriverio#5041]
im trying to test safari using WebDriver io. my ```wdio.conf.js```

```  
    capabilities: [
        {
            'browserName': 'chrome',
            'goog:chromeOptions': {
                // to run chrome headless the following flags are required
                // (see https://developers.google.com/web/updates/2017/04/headless-chrome)
                args: ['--headless', '--disable-gpu']
            }
        },
        {
            browserName: 'safari'
        }
    ],
```

and when run **Safari Technology Preview** 
```
$ /Applications/Safari\ Technology\ Preview.app/Contents/MacOS/safaridriver -p 4444
```

when run wdio test, it says:
```
Starting ChromeDriver 80.0.3987.16 (320f6526c1632ad4f205ebce69b99a062ed78647-refs/branch-heads/3987@{#185}) on port 4444
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[1582069593.807][WARNING]: FromSockAddr failed on netmask
[1582069593.817][SEVERE]: bind() failed: Address already in use (48)
IPv4 port not available. Exiting...
```

since **Safari Technology Preview**, is already running on port ```4444```, how can I run chromedriver on different port?

When I try to run just **Safari Technology Preview**, on ```4444``` (without chrome by commenting out **Test runner services**), it sits there for a while before **Safari Technology Preview** open a window, but tests didn't got excuted. These tests gets executed and passed when run on chrome

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.18.0
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** v12.12.0
 - **NPM version:** 6.11.3
 - **Browser name and version:** safari 13.0.5, Safari Technology Preview 13.2
 - **Platform name and version:** macOS Catalina 10.15.3
 - **Additional wdio packages used (if applicable):**   "wdio-chromedriver-service": "^5.0.2",
    "@wdio/cli": "^5.18.7",
    "@wdio/jasmine-framework": "^5.18.6",
    "@wdio/local-runner": "^5.18.7",
    "@wdio/spec-reporter": "^5.16.11",
    "chromedriver": "^80.0.1",
    "@wdio/allure-reporter": "^5.18.6",
    "@wdio/selenium-standalone-service": "^5.16.10",
    "@wdio/sync": "^5.18.7"

**Comment by christian-bromann** [comment]
If you need to run it like this you need two drivers running (Safaridriver and Chromedriver) on different ports, then set the port in your capabilities like:

```js
    capabilities: [
        {
            'browserName': 'chrome',
            port: 4444,
            'goog:chromeOptions': {
                // to run chrome headless the following flags are required
                // (see https://developers.google.com/web/updates/2017/04/headless-chrome)
                args: ['--headless', '--disable-gpu']
            }
        },
        {
            browserName: 'safari',
            port: 4445
        }
    ],
```
