### ISSUE TITLE
Javascript error: shell is not defined

### ISSUE THREAD

**Issue by ania-s** [webdriverio/webdriverio#5051]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment**
 - **WebdriverIO version:** 5.11.12
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v10.15.3
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome
 - **Platform name and version:** Mac
 - **Additional wdio packages used (if applicable):** 
    "@wdio/appium-service": "5.12.1",
    "appium": "^1.14.2",
    "appium-chromedriver": "^4.16.0",
    "appium-doctor": "^1.11.1",

**Describe the bug**
When running below command on android:
```
const args_list = ["am", "broadcast", "-a", "android.intent.action.VIEW", "-d", "xxxx://xxxx.ext.yyyy.com/?type=cancel_navigation"];
const output = browser.executeScript("mobile: shell", args_list);
```

I get an error

> javascript error: shell is not defined
>   (Session info: chrome=80.0.3987.99)

**Log**
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/8e5232a7-7c5a-433f-9917-c70598fc93da/execute/sync[39m
[35m[HTTP][39m [90m{"script":"mobile: shell","args":["echo","1"]}[39m
[35m[W3C (8e5232a7)][39m Driver proxy active, passing request on via HTTP proxy
[debug] [35m[WD Proxy][39m Matched '/wd/hub/session/8e5232a7-7c5a-433f-9917-c70598fc93da/execute/sync' to command name 'execute'
[debug] [35m[Protocol Converter][39m Did not know how to rewrite the original URL '/wd/hub/session/8e5232a7-7c5a-433f-9917-c70598fc93da/execute/sync' for W3C protocol
[debug] [35m[WD Proxy][39m Proxying [POST /wd/hub/session/8e5232a7-7c5a-433f-9917-c70598fc93da/execute/sync] to [POST http://127.0.0.1:8000/wd/hub/session/aec66d2aa32ff7f3b778821e638517ce/execute/sync] with body: {"script":"mobile: shell","args":["echo","1"]}
[35m[WD Proxy][39m Got an unexpected response with status 500: {"value":{"error":"javascript error","message":"javascript error: shell is not defined\n  (Session info: chrome=80.0.3987.99)","stacktrace":"0   chromedriver_mac64_v80.0.3987.106   0x0000000102342329 chromedriver_mac64_v80.0.3987.106 + 3838761\n1   chromedriver_mac64_v80.0.3987.106   0x00000001022dc123 chromedriver_mac64_v80.0.3987.106 + 3420451\n2   chromedriver_mac64_v80.0.3987.106   0x000000010205062f chromedriver_mac64_v80.0.3987.106 + 751151\n3   chromedriver_mac64_v80.0.3987.106   0x0000000102053505 chromedriver_mac64_v80.0.3987.106 + 763141\n4   chromedriver_mac64_v80.0.3987.106   0x000000010205331e chromedriver_mac64_v80.0.3987.106 + 762654\n5   chromedriver_mac64_v80.0.3987.106   0x0000000102053e67 chromedriver_mac64_v80.0.3987.106 + 765543\n6   chromedriver_mac64_v80.0.3987.106   0x0000000101fe7de9 chromedriver_mac64_v80.0.3987.106 + 323049\n7   chromedriver_mac64_v80.0.3987.106   0x0000000101fda4a2 chromedriver_mac64_v80.0.3987.106 + 267426\n8   chromedriver_mac64_v80.0.3987.106   0x0000000101fe...
[debug] [35m[W3C (8e5232a7)][39m Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: 500 - {"value":{"error":"javascript error","message":"javascript error: shell is not defined\n  (Session info: chrome=80.0.3987.99)","stacktrace":"0   chromedriver_mac64_v80.0.3987.106   0x0000000102342329 chromedriver_mac64_v80.0.3987.106 + 3838761\n1   chromedriver_mac64_v80.0.3987.106   0x00000001022dc123 chromedriver_mac64_v80.0.3987.106 + 3420451\n2   chromedriver_mac64_v80.0.3987.106   0x000000010205062f chromedriver_mac64_v80.0.3987.106 + 751151\n3   chromedriver_mac64_v80.0.3987.106   0x0000000102053505 chromedriver_mac64_v80.0.3987.106 + 763141\n4   chromedriver_mac64_v80.0.3987.106   0x000000010205331e chromedriver_mac64_v80.0.3987.106 + 762654\n5   chromedriver_mac64_v80.0.3987.106   0x0000000102053e67 chromedriver_mac64_v80.0.3987.106 + 765543\n6   chromedriver_mac64_v80.0.3987.106   0x0000000101fe7de9 chromedriver_mac64_v80.0.3987.106 + 323049\n7   chromedriver_mac64_v80.0.3987.106   0x0000000101fda4a2 chromedriver_mac64_v80.0.3987.106 + 267426\n8   chromedriver_mac64_v80.0.3987.106   0x0000000101fe738b chromedriver_mac64_v80.0.3987.106 + 320395\n9   chromedriver_mac64_v80.0.3987.106   0x0000000101fda7b3 chromedriver_mac64_v80.0.3987.106 + 268211\n10  chromedriver_mac64_v80.0.3987.106   0x0000000101fb40bd chromedriver_mac64_v80.0.3987.106 + 110781\n11  chromedriver_mac64_v80.0.3987.106   0x0000000101fb5055 chromedriver_mac64_v80.0.3987.106 + 114773\n12  chromedriver_mac64_v80.0.3987.106   0x0000000102303ebf chromedriver_mac64_v80.0.3987.106 + 3583679\n13  chromedriver_mac64_v80.0.3987.106   0x0000000102310e4a chromedriver_mac64_v80.0.3987.106 + 3636810\n14  chromedriver_mac64_v80.0.3987.106   0x0000000102310be7 chromedriver_mac64_v80.0.3987.106 + 3636199\n15  chromedriver_mac64_v80.0.3987.106   0x00000001022e7839 chromedriver_mac64_v80.0.3987.106 + 3467321\n16  chromedriver_mac64_v80.0.3987.106   0x0000000102311707 chromedriver_mac64_v80.0.3987.106 + 3639047\n17  chromedriver_mac64_v80.0.3987.106   0x00000001022f9cc7 chromedriver_mac64_v80.0.3987.106 + 3542215\n18  chromedriver_mac64_v80.0.3987.106   0x0000000102327324 chromedriver_mac64_v80.0.3987.106 + 3728164\n19  chromedriver_mac64_v80.0.3987.106   0x0000000102348387 chromedriver_mac64_v80.0.3987.106 + 3863431\n20  libsystem_pthread.dylib             0x00007fff7febb2eb _pthread_body + 126\n21  libsystem_pthread.dylib             0x00007fff7febe249 _pthread_start + 66\n22  libsystem_pthread.dylib             0x00007fff7feba40d thread_start + 13\n"}}
[debug] [35m[W3C (8e5232a7)][39m     at JWProxy.proxy (/Users/myuser/app/test/acceptance/app/node_modules/appium-chromedriver/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:213:13)
[debug] [35m[W3C][39m Matched W3C error code 'javascript error' to JavaScriptError

**Comment by christian-bromann** [comment]
This doesn't seem to be a WebdriverIO issue and probably is connected to the environment you are running in. Appium only supports this command in specific environments. Afaik it only works if you run tests on an actual read device or emulator.

**Comment by ania-s** [comment]
Well I am running it on the real device with the "insecure feature" being enabled. Any clue why I could still get it?

**Comment by christian-bromann** [comment]
> Any clue why I could still get it?

Given your information you seem to use `appium-chromedriver` which runs tests on appium in a web context which might not allow to use this command. I would recommend to reach out to the Appium community to ask what is going on.
