### ISSUE TITLE
devtools: Killing Jest doesn't close and kill the browsers.

### ISSUE THREAD

**Issue by dylang** [webdriverio/webdriverio#5052]
**Environment:**
 - **WebdriverIO version:** webdriverio@5.18.7
 - **Mode:** standalone
 - **Node.js version:** 10.16.0
 - **yarn version:** 1.22.0
 - **Browser name and version:** 80
 - **Platform name and version:** MacOS 10.14
 - **Additional wdio packages used (if applicable):** devtools

**Config of WebdriverIO**
`browserName: chrome`

**Describe the bug**

1. Start a browser in a Jest test. 
1. Hit `control-c` to kill the test before it finishes.
1. Jest exits, but the browser is still running.

**To Reproduce**

`yarn test` in this repo: https://github.com/dylang/webdriverio-issue-repo

**Expected behavior**

Close all browsers open when the parent process is killed.

**Comment by christian-bromann** [comment]
@dylang I don't think this is possible. If you use the Jest testrunner there is nothing WebdriverIO can do to make sure that the browser gets closed. If you hit `control-c` the process is killed without sending a `deleteSession` command. I recommend to use the `@wdio/jasmine-testrunner` together with `expect-webdriverio` which allows you to write e2e test similar to Jest. 

Closing as I don't see that there is something we can do about this. Happy to reopen if you can make a valid suggestion.

**Comment by dylang** [comment]
Hi @christian-bromann - 

In the devtools driver, we can check that the parent process is still alive (`proces.ppid > 1`). If it's not, then kill the browser and process.exit.

I don't think this has anything to do with Jest, as it's reproducible without Jest, as seen in this ticket: https://github.com/webdriverio/webdriverio/issues/5048

**Comment by christian-bromann** [comment]
@dylang I don't think there is a parent process if you run a node script or a jest test run so I am not sure if your proposed solution works.

> I don't think this has anything to do with Jest, as it's reproducible without Jest, as seen in this ticket:

These are identical scenarios since you run a script by yourself and WebdriverIO has no control over it. If you use the testrunner WebdriverIO can (and does) close the browser if someone sends a SIGINT signal.

**Comment by dylang** [comment]
@christian-bromann Thanks for the unexpected quick response!

> I don't think there is a parent process if you run a node script 
Correct. There is a parent process in Jest, it spawns workers for each test, but I thought webdriver was spawning a new process for the devtools driver. That's not the case. 

I'll give the testrunner a try and and try to figure out how it's handling control-c cleanly.

**Comment by christian-bromann** [comment]
@dylang if you don't use the wdio testrunner you will have to implement such edge cases by yourself. The wdio testrunner covers these things , e.g. handling control-c.

**Comment by dylang** [comment]
@christian-bromann It appears that the local-runner is not handling `control-c` gracefully either:

`handleExit(exitCode)` in `worker.js` is never called. I'm not sure if that is intentional.

On `control-c`, devtools throws an unhandled promise rejection, which is [caught by jasmine](https://github.com/jasmine/jasmine/blob/master/src/core/GlobalErrors.js#L61):

```
 error:
      { matcherName: '',
        message: 'Unhandled promise rejection: Error: Page crashed!',
        stack:
         'Error: Page crashed!\n    at CDPSession.emit (events.js:198:13)\n    at CDPSession.EventEmitter.emit (domain.js:448:20)\n    at WebSocket.emit (events.js:198:13)\n    at WebSocket.EventEmitter.emit (domain.js:448:20)',
        passed: false,
        expected: '',
        actual: '' },
```

This causes Jasmine to kill the worker, but not before growing in memory usage from calling `this.checkPendingNavigations` thousands of times recursively. This can cause node to run out of memory, as demonstrated in #5048.

The [potentially unreliable](https://github.com/tapppi/async-exit-hook/issues) `async-exit-hook` is used to keep the process open until the worker is done exiting. This might be what i need, however I don't think this module can be used with Jest because Jest may call `process.exit` on `SIGINT`. I will give it a try and let you know.

It's possible this is why `INFO @wdio/local-runner: Waiting for 1 to shut down gracefully` keeps printing even after the OS gives us a new prompt (at least in MacOS).

**Comment by dylang** [comment]
It looks like chrome-launcher has a [killAll](https://github.com/GoogleChrome/chrome-launcher#killall) method that we can take advantage of in Jest, but they haven't published a new version that has this feature (or any updates in 6 months...)

I'll revisit this after they publish a new version.
