### ISSUE TITLE
Enable absolute paths for specs in Testrunner Configuration

### ISSUE THREAD

**Issue by Jakuska** [webdriverio/webdriverio#5053]
**Is your feature request related to a problem?**
In my case (electron app), the feature files are not located in the same directory as the rest of the code is. So it's inconvenient to have to use a relative path to describe what specs WDIO should run.  

I also think that absolute paths will allow people to integrate WDIO with other software better as well. 

**Describe the solution you'd like**
There should be a way to make a distinction between absolute and relative paths in specs: 
https://webdriver.io/docs/configurationfile.html

**Comment by Primajin** [comment]
Hey how did you solve it? I'm currently trying to find the docs on that ...

**Comment by Primajin** [comment]
I found a way via enabling Babel http://beta.webdriver.io/docs/babel.html and then adding https://www.npmjs.com/package/babel-plugin-module-resolver with

```json
{
  "plugins": ["@babel/plugin-proposal-object-rest-spread", ["module-resolver", { "root": ["./test"] }]],
  "presets": ["@babel/preset-env"]
}
```

**Comment by Jakuska** [comment]
> Hey how did you solve it? I'm currently trying to find the docs on that ...

Turns out that you can use absolute paths. I don't remember why I thought I couldn't.
