### ISSUE TITLE
Autocomplete not returning results in Webstorm for page object elements

### ISSUE THREAD

**Issue by danrose77** [webdriverio/webdriverio#5054]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.18.7
 - **Mode:** WDIO Testrunner sync
 - **Node.js version:** v12.15.0
 - **NPM version:** 6.11.2
 - **Browser name and version:** Browser N/A
 - **Platform name and version:** Win 10 on Webstorm 2019.3.2

**Config of WebdriverIO**
Issue is with Webstorm autocomplete so not relevant, I can provide details if needed, but is happening across multiple projects

**Describe the bug**
Autocomplete works as expected if using an element declared in the test, but fails to autocomplete when using page objects.

**To Reproduce**
In the code below autocomplete functioned for `element`, but not for `Account.backButton`. The same is not true in VSCode where it autocompletes in both:
```
import Account from "../../Pages/Account";

describe('Test', () => {
    it('should test something', () => {
        browser.url("/");
        const element = $('Some_element');
        element.click();
        Account.backButton.click();
    });
});
```

**Expected behavior**
Autocomplete should function for a getter the same as any element does.

**Log**
None of use

**Additional context**
Jetbrains suggested:
'File > Invalidate Caches/Restart > Invalidate and Restart'
and also tested on a fresh project with no luck

**Comment by mgrybyk** [comment]
Can you please share your Account page? Looks like you have some issues there. Anyway it's not webdriverio related...

**Comment by danrose77** [comment]
It's a big file... cutting it down (removing extra getters and functions leaves me with this):

```
import Page from './Page'

class Account extends Page {
    get backButton() {
        return $(".button.button--grey");
    }
}

clickTheBackButton() {
	this.backButton.click();
}

export default new Account();
```

I have a fuction in there to test whether autocomplete was working within the page object.

**Comment by christian-bromann** [comment]
@mgrybyk for context, I asked in the support chat to create a ticket to follow up on this. We should ensure that we provide some sort of autocomplete for IDEs. We ideally can only guarantee this if someone uses TypeScript.

**Comment by mgrybyk** [comment]
@danrose77 that should work perfectly with Typescript. For js you have to use jsdoc format to declare types.

**Comment by danrose77** [comment]
@mgrybyk Do you mean like the VSCode example on https://webdriver.io/docs/autocompletion.html ?

I have that done already... 

If it's not those instructions does something need to be added to that page to explain it? Sorry if my ignorance is making this more difficult, I'm afraid I'm more test focussed than dev :-)

**Comment by mgrybyk** [comment]
@danrose77 do you have a typescript or javascript project? If it's a javascript project you have to declare types manually for your classes

**Comment by danrose77** [comment]
javascript... I'm not sure how I would declare types manually. Do you know if there is a quide anywhere? Or is it worth making the jump to typescript?

**Comment by mgrybyk** [comment]
@danrose77 see my previous comment. You need to define types in jsdoc format and might have to switch to named exports instead of default

**Comment by mgrybyk** [comment]
@danrose77 have you managed to resolve the issue?

**Comment by danrose77** [comment]
@mgrybyk Not really, I may have misunderstood, but I thought you meant I need to switch the project to typescript, but I can't do that right now. Additionally someone at Webstorm has failed to recreate the issue so it must be something related to my config... https://intellij-support.jetbrains.com/hc/en-us/community/posts/360007641459-Webdriver-io-autocomplete-not-functioning-since-2019-3-2

Adding:
```
  /**  
   * @return {WebdriverIO.Element}
   */
```
before the getter made it work, but only for that one... I can't go through and set the return before every single one. So I think I'm either using VSCode or switching the project to typescript when I can to ensure autocomplete works (along with other typescript benefits).
