### ISSUE TITLE
Can;t properly setValue to input textfield on ios safari

### ISSUE THREAD

**Issue by abaybabaydabudidabuday** [webdriverio/webdriverio#5055]
**Describe your question with as much detail as possible**
setValue command - after ending of typing doesn't send 'Enter' key command to input text field. So could someone please help me - how to send "Done" trigger to my input text field on IOS + SAFARI.

**If it's about a specific piece of code, try and include some of it to support your question.**
Tried different solutions but can't send "Done" to my setValue command: 
1) element.setValue(value, ['CTRL', 'M']); - solved my problem only for Web browser Testing (doesn't work for ios safari) 
2) browser.hideKeyboard('pressKey', 'Done');  - doesn''t work for ios safari
3) touchAction()  - also doesn't work
4) pressKeyEvent/pressKeyKode - also doesn;t work
5) addValue('Enter'); - doesn't work

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.18.7
 - **Mode:** WDIO TestRunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.16.3
 - **NPM version:** 6.9.0
 - **Browser name and version:** Safari
 - **Platform name and version:** Iphone X (12.4) 
 - **Additional wdio packages used (if applicable):** 
 "@wdio/allure-reporter": "^5.18.6",
    "@wdio/appium-service": "^5.16.11",
    "@wdio/browserstack-service": "^5.3.4",
    "@wdio/cli": "^5.18.7",
    "@wdio/junit-reporter": "^5.3.1",
    "@wdio/local-runner": "^5.18.7",
    "@wdio/mocha-framework": "^5.18.7",
    "@wdio/sauce-service": "^5.16.10",
    "@wdio/selenium-standalone-service": "^5.2.2",
    "@wdio/spec-reporter": "^5.18.7",
    "@wdio/sync": "^5.18.7",

**Comment by christian-bromann** [comment]
@abaybabaydabudidabuday have you tried to click on a different element?

**Comment by abaybabaydabudidabuday** [comment]
> @abaybabaydabudidabuday have you tried to click on a different element?

@christian-bromann yes, sure. Input field was cleared after clicking to another element. Added loom video with full test case in attach. 
Also I had the same issue for browser and solved it by adding CTRL+M command. Dunno how to make similar solution for appium. 
Using this selector for settingvalue: 
element = `*[data-qa="text-itemCost"]  input[type="text"]`
setValue(element) (and also tried approaches above)  
https://www.loom.com/share/0fe3d48f4cdf4a20a9b94352d7811262

**Comment by wswebcreation** [comment]
@abaybabaydabudidabuday 

What stack is used to create the app, react/angular/Vue? There are some issues with updating the internal state of React components with Safari and Appium, please check this thread https://github.com/appium/appium/issues/9002#issuecomment-587922123
It might have been solved with the latest beta.

If it is a React/Vua/Angular app then this is an Appium issue and not a WebdriverIO issue

**Comment by abaybabaydabudidabuday** [comment]
> @abaybabaydabudidabuday
> 
> What stack is used to create the app, react/angular/Vue? There are some issues with updating the internal state of React components with Safari and Appium, please check this thread [appium/appium#9002 (comment)](https://github.com/appium/appium/issues/9002#issuecomment-587922123)
> It might have been solved with the latest beta.
> 
> If it is a React/Vua/Angular app then this is an Appium issue and not a WebdriverIO issue

Thx for u answer, it makes sense, cuz we are using React. Hope in will be fixed soon..

**Comment by wswebcreation** [comment]
It will be fixed in the newest Appium release and thus not related to WebdriverIO. Going to close it for now but it's still open for discussion
