### ISSUE TITLE
v6 release blog post misses breaking change

### ISSUE THREAD

**Issue by wswebcreation** [webdriverio/webdriverio#5058]
**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Description of the improvement / report**
I've been reading this blogpost https://webdriver.io/blog/2019/11/01/spec-filtering.html because I need to do a framework review for a customer.

Then I read this last part

...Please note that the feature will be enabled for all test frameworks in v6 so it's recommended to start preparation in advance....

And I also read the [blogpost for V6](https://github.com/webdriverio/webdriverio/pull/5042) again, but correct me if I'm wrong, this breaking change isn't mentioned in the blogpost

**Comment by christian-bromann** [comment]
fixed in #5143
