### ISSUE TITLE
Sauce Connect / Tunneling Example

### ISSUE THREAD

**Issue by BGarretson** [webdriverio/webdriverio#506]
I just wanted to point out a hole in the documentation @ http://webdriver.io/guide/plugins/grunt-webdriver.html that I think would improve the experience for incoming users of Webdriver.io / Grunt-Webdriver

The documentation makes a reference to the 'tunnel-identifier' parameter, and mentions that if it is populated then the task will automatically try to use Sauce Connect - this is true, however, if you use that desriedCapability and leave the host and port configured as in the example you will get the following error:

[D] init WebdriverIO instance
[13:09:38]:  COMMAND	POST 	 "/wd/hub/session"
[13:09:38]:  DATA		 {"desiredCapabilities":{"browserName":"chrome","version":"","javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"platform":"ANY","tunnel-identifier":"test","requestOrigins":{"url":"http://webdriver.io","version":"2.4.5","name":"webdriverio"}}}
[13:10:54]:  ERROR	Unknown	Remote end send an unknown status code.

/Users/bgarrets/code/iodocs/node_modules/grunt-webdriver/node_modules/webdriverio/lib/utils/PromiseHandler.js:154
                throw error;
                      ^
RuntimeError: RuntimeError
     (ECONNREFUSED:-1) Couldn't connect to selenium server
     Problem: Couldn't connect to selenium server

     Callstack:
     -> init()

-----------------

After a lot of troubleshooting I came to realize that the port needed to be configured to the port of the Selenium Listener attached to the Sauce Connect tunnel, and the host name could be omitted entirely. 

The config in the tunneling example should be more like this:

```
grunt.initConfig({
  webdriver: {
    options: {
        port: 4445, // the anticipated port of the Selenium Listener generated by the task
        user: SAUCE_USERNAME,
        key: SAUCE_ACCESS_KEY,
        desiredCapabilities: {
            browserName: 'chrome',
            version: '27',
            platform: 'XP',
            'tunnel-identifier': 'my-tunnel'
        }
    },
    login: {
        tests: ['test/spec/login/*.js']
    },
    form: {
        tests: ['test/spec/form/*.js']
    }
    // ...
  },
})
```

**Comment by christian-bromann** [comment]
@BGarretson thanks for posting the issue. You are right that wasn't handled well by grunt-webdriver. I fixed that. Now once you have an tunnel-identifier set your host and port capabilities will get modified to the right port `4445`.

Published to NPM `v0.5.1`
