### ISSUE TITLE
Appium throws an error when trying find an element based on index in a loop

### ISSUE THREAD

**Issue by viralkpanchal** [webdriverio/webdriverio#5063]
This issue is related to Appium Service when running a test case on native Android Application.

**Environment:**
    "dependencies": {
        "@wdio/appium-service": "^5.18.2",
        "@wdio/browserstack-service": "5.16.10",
        "@wdio/cli": "^5.18.6",
        "@wdio/local-runner": "^5.18.6",
        "@wdio/mocha-framework": "^5.18.6",
        "@wdio/spec-reporter": "^5.18.6",
        "@wdio/sync": "^5.18.6",
        "assert": "^2.0.0",
        "aws-sdk": "^2.613.0",
        "config": "^1.28.1",
        "fs": "0.0.1-security",
        "mocha": "^6.0.0",
        "prettier": "^1.19.1",
        "request": "^2.88.0",
        "request-promise": "^4.2.5",
        "webdriverio": "^5.18.6",
        "xml2js": "^0.4.23"
    }
 - **Mode:** Running Android Test on BrowserStack
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:** 12.13.0
 - **NPM version:** 6.12.0
 - **Browser name and version:** Samsung Galaxy S9 Plus, Android 9.0

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
In my Android application, there are multiple expandable/collapsable sections on a screen. 
I wrote code to identify those elements using $$ keyword. I then get maximum index of this element (array.length - 1) and click on it.
During test execution, it works well with first iteration and clicks on first collapse button.
As soon as second collapse button appears on the screen, test terminates with following exception. 
Despite using Try - Catch block, test terminates by throwing an exception.

This issue does not occur when test is run locally. It is only reproducible when test is run on BrowserStack Android Device.

**To Reproduce**
Have an Android device on BrowserStack.
Identify an element that appears more than once so you can use $$.
Loop through all elements found in an array and click on maximum index.

**Expected behavior**
WebdriverIO identifies all elements and be able to click on them when using in a loop (for loop / while loop). 
**Log**
https://gist.github.com/viralkpanchal/697340fcbed4eed7b8e6cf097a6b9a92

**Additional context**
This issue is reproducible even if you do not use for loop, but just try to click on the maximum index.

**Comment by wswebcreation** [comment]
@viralkpanchal 

Based on the info you say this

> This issue does not occur when test is run locally. It is only reproducible when test is run on BrowserStack Android Device.

For cloud executions you don't use the `2wdio/appium-service`, you use the Appium server on BrowserStack. Can you check and align the versions you have running of Appium on your local machine and on the BrowserStack cloud?

Because it works locally and not on the BrowserStack cloud this is more likely to be an issue with BrowserStack and the version they are using. This is not related to WebdriverIO or the `@wdio/appium-service` and thus going to close it for now.

It's still open for discussion
