### ISSUE TITLE
beforeCommand and afterCommand hooks throw error in standalone mode

### ISSUE THREAD

**Issue by artyompvl** [webdriverio/webdriverio#5066]
**Environment:**
 - **WebdriverIO version: 5.18.7
 - **Mode: Standalone mode
 - **If WDIO Testrunner, running sync/async: async
 - **Node.js version: v12.15.0
 - **NPM version: 6.13.4
 - **Browser name and version: chrome
 - **Platform name and version: macOS 10.14.6

**Config of WebdriverIO**
{
            hostname: 'localhost',
            port: 4444,
            path: '/',
            capabilities: {
                browserName: 'chrome'
            },
            beforeCommand: [async () => {
                await sleep(100)
                ++beforeCmdCounter
            }],
            afterCommand: [async () => {
                await sleep(100)
                ++afterCmdCounter
            }]
}
**Describe the bug**
beforeCommand and afterCommand hooks throw TypeError: Cannot convert undefined or null to object in the latest webdriverio version. Not reproducible with wdio test runner

**To Reproduce**
1. run code below:
const { remote } = require('webdriverio');

(async () => {
  let beforeCmdCounter = 0;
  let afterCmdCounter = 0;
  const remoteBrowser = await remote({
    capabilities: {
      browserName: 'chrome'
    },
    beforeCommand: [async () => {
      console.log('this is beforeCommand hook');
      ++beforeCmdCounter
    }],
    afterCommand: [async () => {
      console.log('this is afterCommand hook');
      ++afterCmdCounter
    }]
  })
  await remoteBrowser.getUrl();
  console.log(beforeCmdCounter);
  console.log(afterCmdCounter);
})().catch(error => {
  console.log(error);
});

2. Observe console output(it will throw TypeError)

**Expected behavior**
This code should log:
this is beforeCommand hook
this is afterCommand hook
1
1

**Log**
https://gist.github.com/artyompvl/c40f97dc5c6d40648af396a3c00798db

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
The concept of hooks don't exist when running WebdriverIO in standalone mode. If you want to use them please use the [wdio testrunner](https://webdriver.io/docs/clioptions.html).
