### ISSUE TITLE
Use touchActions for dragAndDrop command if user is running on mobile

### ISSUE THREAD

**Issue by abaybabaydabudidabuday** [webdriverio/webdriverio#5068]
**Environment (please complete the following information):**
 - **WebdriverIO version:**  ^5.18.7
 - **Mode:**  test Runner
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async] sync
 - **Node.js version:** 10.16.3
 - **NPM version:** 6.9.0
 - **Browser name and version:** safari
 - **Platform name and version:** iOS (12.4)
 - **Additional wdio packages used (if applicable):** 

**Describe the bug**
using simple example with dragAndDrop command and getting this kind of error (it works on firefox): 
**the URL '/wd/hub/session/b6d1e05a-246f-4673-9151-a095c570aa74/actions' did not map to a valid resource**

**To Reproduce**
Just try to run dragAndDrop command on ios Safari command. 

My example of using: 
const draggableElement = $(`*[data-qa="formElement-select"]`);
const droppableElement = $(`*[data-rbd-droppable-id="ea55b6aa_1583141924777"]`);
draggableElement.dragAndDrop(droppableElement, 1000);

**Expected behavior**
Work as in desktop browsers

**Comment by christian-bromann** [comment]
The actions command that `dragAndDrop` is using is not supported for mobile. We should check if `isMobile` is true and use `touchActions` instead.

**Comment by erwinheitzman** [comment]
As the command now uses the `action` command under the hood, this should now be fixed
