### ISSUE TITLE
Sauce Labs Jobs are not correctly updated if you're using "browser.reloadSession()"

### ISSUE THREAD

**Issue by pako88** [webdriverio/webdriverio#5071]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.18.7
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v12.16.1
 - **NPM version:** 6.13.4
 - **Browser name and version:** Chrome 80
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/spec reporter, @wdio/sauce service

**Config of WebdriverIO**
doesn't matter

**Describe the bug**
- Sauce Service updates all jobs as failed
- Sauce Service names all jobs with the first describe name
- Spec Reporter just prints out one Sauce Labs job link

**To Reproduce**
1. Execute following test in Sauce Labs.
```
describe('Test 1', () => {
  it('should fail', () => {
    browser.url('https://webdriver.io/');
    expect(browser.getTitle()).toContain('Selenium');
  });
});

describe('Test 2', () => {
  before(() => {
    browser.reloadSession(); // create a new session in sauce labs to have separate videos for each describe block
  });

  it('should pass', () => {
    browser.url('https://webdriver.io/');
    expect(browser.getTitle()).toContain('WebdriverIO');
  });
});
```

**Expected behavior**
- Jobs are correctly updated in Sauce Labs
- All Sauce Labs Job-Links are printed in Spec Reporter

**Log**
If applicable, add logs to help explain your problem.

**Additional context**
Folders/Files in Source Code:
https://github.com/webdriverio/webdriverio/blob/ee0b7b3fc82662037cd52691204ae89148858dda/packages/wdio-spec-reporter/src/index.js#L130
https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-sauce-service/src
> Please use the correct markdown

**Comment by constantinsuiu** [comment]
Does someone know if there is any workaround to this? It's a blocker for my project and hoping for a solution.
Thank you in advance.

**Comment by christian-bromann** [comment]
@constantinsuiu there is no workaround, we need an enhancement to the spec reporter to address this. Any help would be appreciated.

**Comment by constantinsuiu** [comment]
@christian-bromann happy to, but I'm not very experienced with WebDriverIO itself (using a framework that uses WebDriverIO under the hood)

**Comment by nadvolod** [comment]
@pako88 I took a look at the issue together with @christian-bromann and there is actually a [limitation from the Mocha side](https://mochajs.org/#hooks) about the `beforeAll()` and `afterAll()` hooks being called only once per file, regardless of how many `describe` blocks we have. As a result, it's not possible to to update any information after a `describe` block has been executed such as whether a suite has failed or the test name. Hence, the misbehavior in your 2nd `describe` example.

Our recommendation is to simply not place more than 1 `describe` block in a single file. This is the typical pattern for test files and using it will prevent these issues from happening.

**Comment by pako88** [comment]
Thanks for digging into it
