### ISSUE TITLE
ERROR @wdio/runner: Error: connect ECONNREFUSED 127.0.0.1: at TCPConnectWrap.afterConnect [as oncomplete]

### ISSUE THREAD

**Issue by zdman135** [webdriverio/webdriverio#5072]
I am currently getting this error: 
`[0-8] 2020-03-03T21:15:20.187Z ERROR @wdio/runner: Error: connect ECONNREFUSED 127.0.0.1:34713
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)`

This error started happening right after I enabled devtools by adding the following line inside of my wdio configuration file:
`automationProtocol: "devtools",`
I currently use a gridhub to run all my spec tests.
Please assist in troubleshooting this issue. Thanks!

**WebdriverIO version:** `"webdriverio": "5.18.4"`
**Mode:** [WDIO Testrunner]
[sync]
**Node.js version:** [11.10.1]
**Yarn version:** [1.19.1]
[Chrome Version 79]
[Linux]

 Related packages and versions:
`    "@wdio/cli": "5.18.4",
    "@wdio/devtools-service": "5.16.16",
    "@wdio/local-runner": "^5.18.4",
    "@wdio/mocha-framework": "^5.16.15",
    "@wdio/selenium-standalone-service": "5.16.10",
    "@wdio/spec-reporter": "^5.16.11",
    "@wdio/sync": "^5.17.0",
    "chromedriver": "^80.0.0",
    "puppeteer": "1.15.0",
    "wdio-chromedriver-service": "^5.0.2",
    "webdriverio": "5.18.4",`

wdio config file:
const regressionConfig = require("./wdio.defaults").regressionConfig;
const localIp = process.env.LOCAL_IP;
const webPort = process.env.WEB_PORT;

regressionConfig.mochaOpts.timeout = 240000;

exports.config = Object.assign(regressionConfig, {
  // runner: "local",
  hostname: "some-gridhub-site.com",
  port: 9000,
  path: "/wd/hub",
  capabilities: [
    {
      maxInstances: 9,
      browserName: "chrome",
      "goog:chromeOptions": {
        args: ["--headless", "--disable-gpu", "--window-size=9999,9999"],
      },
    },
  ],
  logLevel: "error",
  coloredLogs: false,
  screenshotPath: null,
  baseUrl: `http://${localIp}:${webPort}/`,
  automationProtocol: "devtools",
});

**Comment by pmerwin** [comment]
Do you have sample spec that can reproduce this?

**Comment by mgrybyk** [comment]
@zdman135 have you installed devtools protocol? Can't see it in the list of packages you have provided

**Comment by zdman135** [comment]
> @zdman135 have you installed devtools protocol? Can't see it in the list of packages you have provided

Yeah, I forgot to include it, but it's in my package.json
    `"devtools": "5.18.6",`

I used this documentation to set up the puppeteer mocking - https://webdriver.io/docs/automationProtocols.html

**Comment by zdman135** [comment]
> Do you have sample spec that can reproduce this?

I don't think the spec is the issue or help, but here is a gist to the working spec file that causes the issue when ran against gridhub - https://gist.github.com/zdman135/af20193f37c58a5e06ca8b49c1d47fc4

So, the spec runs fine locally:
I start the webserver up
then I run my specs against the local webserver

Then I run the same specs and send it to gridhub, and gridhub and everything runs fine, it is using selenium webdriver.
It was only when I started adding puppeteer using devtools, did I start seeing this errror. I don't fully understand what is happening, and was looking for troubleshooting help.

**Comment by nextlevelbeard** [comment]
Might be related to this since webdriverio uses got.
https://github.com/sindresorhus/got/issues/951

Solution is to update all `agent-base` to version 5.

`npm-shrinkwrap.json`:
```json
{
  "dependencies": {
    "agent-base": {
      "version": "5.0.0"
    }
  }
}
```

**Comment by christian-bromann** [comment]
Using `devtools` protocol is only supported when running tests locally. If you use a cloud provider like gridhub it won't work.
