### ISSUE TITLE
browser.keys(['Enter']) doesn't work with puppeteer

### ISSUE THREAD

**Issue by KBPratap** [webdriverio/webdriverio#5073]
I am trying to enable puppeteer with webdriverio using "devtools": "^5.18.6".
 
After filling in my login credentials, I want to press Enter key. `browser.keys('Enter')` doesn't seem to work. 
This works perfectly fine when using webdriver protocol.

**Comment by christian-bromann** [comment]
This might be fixed with the `devtools` package in v6.

**Comment by christian-bromann** [comment]
This issue is not reproducible anymore:

```js
    browser = await remote({
        automationProtocol: 'devtools',
        capabilities: {
            browserName: 'chrome'
        }
    })

    await browser.url('http://todomvc.com/examples/react/#/')
    await browser.pause(2000)
    await browser.keys('Get Milk')
    await browser.keys('Enter')
    await browser.pause(2000)
```
