### ISSUE TITLE
Cannot end session Safari when the popup is opening

### ISSUE THREAD

**Issue by khoingo-lg** [webdriverio/webdriverio#5074]
I have the test case that only check text of the popup on Safari browser. After that, I end my test case. (The popup is still opening on Safari browser when I end my test case)
The problem is Webdriver cannot end session after end the test. I assume the problem come from the popup does not close before end session.

Environment :
 - WebdriverIO version: 5.18.5
 - Mode: WDIO Testrunner
 - Running sync
 - Node.js version: v10.16.0
 - NPM version: 6.13.7
 - Safari: 13.0.5
 - MACOS: 10.15.3
 - @wdio/selenium-standalone-service: 5.16.10
- Reporter: Mochawesome 4.1.0

Step to reproduce my issue:
1. Go to the page that contains the popup.
e.g.: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_ev_onload
It's just only example in my case.
2. Check text of the popup.

**Important point**: the popup is still opening on safari browser when I end my test case.

Actual observe: The webdriver cannot end session after end the test case.

Note:
1. After I wait over 30 minutes, the webdriver can end session and generate report.
2. I call "closePopup" at the end of test case, the webdriver works normally.

This issue does not happen on chrome and Firefox.

Could anyone give me some advises?

**Comment by christian-bromann** [comment]
I tried running this code:

```js
const { remote } = require('./packages/webdriverio')

;(async () => {
    const browser = await remote({
        capabilities: {
            browserName: 'safari'
        }
    })

    await browser.navigateTo('https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_ev_onload')
    await browser.deleteSession()
})().catch((e) => console.error(e))
```

and it worked without problems. The session and browser was closed normally.
