### ISSUE TITLE
Firefox devtools - fails on switchWindow() with error `page.bringToFront is not a function`

### ISSUE THREAD

**Issue by abaybabaydabudidabuday** [webdriverio/webdriverio#5075]
**Environment:**
 - **WebdriverIO version:** ^5.18.7
 - **Mode:** WDIO TestRunner
 - **If WDIO Testrunner, running sync/async:** sync
- **Node.js version:** 10.16.3
 - **NPM version:** 6.9.0
 - **Browser name and version:** Firefox
 - **Platform name and version:** darwin (devtools)
 - "devtools": "^5.18.7"

**Config of WebdriverIO**
Chrome config configured in the same way, and working correctly
const { config } = require('@config/desktop_shared_conf');
config.automationProtocol = 'devtools';
config.capabilities = [
  {
    browserName: 'firefox',
    maxInstances: 1,
  },
];

exports.config = config;

**Describe the bug**
on Firefox browser trying to switchWindow to new popup window (new browser instance) and getting the error `page.bringToFront is not a function` (On chrome working correctly)

**To Reproduce**
1) configure devtools for Firefox
2) switchWindow (to new browser instance)

**Log**
![image](https://user-images.githubusercontent.com/50987561/76071782-fd860600-5fc0-11ea-8579-155605d06adb.png)

**Comment by christian-bromann** [comment]
This bug is not reproducible anymore with latest `devtools` package:

```js
(async function () {
    browser = await remote({
        automationProtocol: 'devtools',
        capabilities: {
            browserName: 'firefox',
            'moz:firefoxOptions': {
                headless: false,
                binary: '/Applications/Firefox Nightly.app/Contents/MacOS/firefox'
            }
        }
    })

    await browser.url('https://webdriver.io')
    await browser.newWindow('http://json.org')
    console.log(await browser.getTitle())
    await browser.pause(2000)

    browser.switchWindow('webdriver.io')
    await browser.pause(2000)
    console.log(await browser.getTitle())

    await browser.deleteSession()
})().catch(async (e) => {
    console.error(e.stack)
    await browser.deleteSession()
})
```
