### ISSUE TITLE
Unable to click on web element in Safari browser

### ISSUE THREAD

**Issue by pradeepnyk** [webdriverio/webdriverio#5077]
**Environment:**
 - **WebdriverIO version:** 5.18.6
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [11.9.0]
 - **NPM version:** [6.10.1]
 - **Browser name and version:** [Safari 13.0.3]
 - **Platform name and version:** [Mac OS Catalina 10.15.1]
 - **Additional wdio packages used (if applicable):** [@wdio/selenium-standalone service]

**Additional context**
I am unable to click on any web element, not getting any error if the click does not happen. It is working fine in Chrome and Firefox without any additional browser options. Here is my capability object that I tried for Safari:

```
capabilities: [
        {
            browserName: 'safari',
            'safari:options':{
                technologyPreview: true,
            }
        }
    ]
```

**Comment by christian-bromann** [comment]
@pradeepnyk please file a bug on the Safari [project page](https://webkit.org/reporting-bugs/). This is an issue in Safaridriver and needs to be resolved there. There is nothing WebdriverIO can do to fix this.
