### ISSUE TITLE
Greenkeeper is stopping 

### ISSUE THREAD

**Issue by wswebcreation** [webdriverio/webdriverio#5083]
I saw on the Slack channel of Appium that Greenkeeper was stopping. If you go to the website https://greenkeeper.io/ you will also see they stop on the 3rd of June.

The Appium team was discussing to use dependabot which comes with GitHub, but I don't know what you all want to do

**Comment by christian-bromann** [comment]
Thanks for notifying @wswebcreation !

Let's find out which tool works best for our Lerna structure here.

**Comment by christian-bromann** [comment]
I installed Dependabot for all necessary WebdriverIO repositories.
