### ISSUE TITLE
What is this error connect and port mean?

### ISSUE THREAD

**Issue by zdman135** [webdriverio/webdriverio#5085]
1583892444.507][SEVERE]: bind() failed: Cannot assign requested address (99)
[0-0] RUNNING in chrome - /e2e/regression/devTools/...
[0-0] 2020-03-11T02:07:50.667Z ERROR @wdio/runner: Error: connect ECONNREFUSED 127.0.0.1:40583
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
[0-0] Error: connect ECONNREFUSED 127.0.0.1:40583

I am getting the following error in the console.
I am running the spec locally.

My main question is what is this ECONNREFUSED 127.0.0.1:40583. How does it know what port to use? Is there a way to set it to a certain port? What is this port number it is trying to use?

**Comment by christian-bromann** [comment]
> How does it know what port to use?

Not sure what you are doing here but this is WebdriverIO failing to connect to the DevTools interface. The port usually is received from the Chromedriver session response.

I hope this answers your question. While I feel this deserves a more concrete error message, your information aren't sufficient to understand how this error is being caused. A reproducible example would be helpful.
