### ISSUE TITLE
Browser.WaitUntil Error message change with variable

### ISSUE THREAD

**Issue by Nemeritz** [webdriverio/webdriverio#5086]
**Is your feature request related to a problem? Please describe.**
I have a browser.waitUntil with timeout and interval. A variable gets updated in the fn (first arg of waitUntil) and I would like to have the error message contain that variable when the waitUntil times out. But currently waitUntil makes a copy of the timeoutMsg and won't update it every tick because of how js works.

**Describe the solution you'd like**
Maybe another argument in the waitUntil that takes in another function and in that function I can return the value of the variable?

**Describe alternatives you've considered**
I don't really see any alternatives. I would need to pass in the variables as an array or json to be passed by reference but then waitUntil only expects the msg to be a string and that would be a shitty way of solving it anyway.

**Additional context**
If you need anything else I can provide them on request.

**Comment by christian-bromann** [comment]
Can you provide a code example?

**Comment by Nemeritz** [comment]
The original problem was setValue/clearValue doesn't work in Chrome so we had to implement our own implementations of it. 

```
    browser.overwriteCommand('setValue', function(origFunction, text) {
      var currentString;
      this.clearValue();
      
      const characterArray = String(text).split('');
      characterArray.forEach((character, index) => {
        this.addValue(character);
        browser.waitUntil(() => {
          currentString = characterArray.slice(0, index + 1).join('');
          return this.getValue() === currentString;
        }, 500, `failed to input char "${this.getValue()}" "${currentString}"`, 10);
      })
    }, true);
```

The `currentString` (expected string value) variable gets updated and the error message needs to reflect the most recent `currentString`. But I think it only updates when this.getValue() === currentString returns true. 

For example if I was trying to do $('input').setValue('ab') and it failed to enter anything the error message would say 'failed to input char "" undefined' instead of 'failed to input char "" "a"'

**Comment by christian-bromann** [comment]
@Nemeritz I think the problem here is that you can't use a `forEach` here because it would be executed in the next eventloop and breaks the sync behavior of WebdriverIO. I might be wrong about that. However, why do you set current string in the `waitUntil` condition? Have you tried:

```js
    browser.overwriteCommand('setValue', function(origFunction, text) {
      var currentString;
      this.clearValue();
      
      const characterArray = String(text).split('');
      characterArray.forEach((character, index) => {
        this.addValue(character);
        currentString = characterArray.slice(0, index + 1).join('');
        browser.waitUntil(() => {
          return this.getValue() === currentString;
        }, 500, `failed to input char "${this.getValue()}" "${currentString}"`, 10);
      })
    }, true);
```

This should work as expected. Let me know so I can re-open the issue.
