### ISSUE TITLE
devtools: Cannot upload files though input elements

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#5090]
**Environment:**
 - **WebdriverIO version:** latest v5
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Browser name and version:** chrome, firefox
 - **Platform name and version:** Mac OSX

**Config of WebdriverIO**
Any v5 with devtools `automationProtocol`

**Describe the bug**
Cannot upload files through`addValue`/`setValue` command on`type="file"` `input` fields.
It's possible with selenium-standalone, driver services, but not devtools `automationProtocol`.
`elementSendKeys` is successfully executed/ logged with the proper value (the file(s) path) but file upload is not triggered.

**To Reproduce**
Execute`setValue`/`addValue`to file input element.
Example found here: https://github.com/nextlevelbeard/wdio-repro-devtools-input

**Expected behavior**
Should trigger element's onChange event and upload files.

**Comment by christian-bromann** [comment]
Can you provide a minimal reproducible example?

**Comment by nextlevelbeard** [comment]
@christian-bromann you can find one here
https://github.com/nextlevelbeard/wdio-repro-devtools-input

**Comment by takeya0x86** [comment]
I guess we should use `uploadFile()` instead of `type()` when `input type="file"`.

https://pptr.dev/#?product=Puppeteer&version=v2.1.1&show=api-elementhandleuploadfilefilepaths

https://github.com/webdriverio/webdriverio/blob/d485e2c3a7dc5967038833fe960a8fa267632d26/packages/devtools/src/commands/elementSendKeys.js#L10-L12

This Puppeteer code works fine.

```javascript
const path = require("path");
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://the-internet.herokuapp.com/upload');
  const upload = await page.$('#file-upload');
  await upload.uploadFile(path.resolve('sample.txt'));
  await (await page.$("#file-submit")).click();
  await page.waitForNavigation();
  const uploadFiles = await page.$eval('#uploaded-files', (elm) => elm.innerText);
  console.log(uploadFiles);  // => sample.txt
  await browser.close();
})();
```

**Comment by nextlevelbeard** [comment]
I see we've updated puppeteer in #5331.
From the changelog:
> File uploads are generally more reliable (#5363) and elementHandle.uploadFile(...filePaths) now triggers a change event, matching the old behavior in Puppeteer v1.20.0. (#5389)`

It likely fixes this issue.

**Comment by christian-bromann** [comment]
@nextlevelbeard can you check?

**Comment by nextlevelbeard** [comment]
Checked and problem persists. Just like @takeya0x86 said, implementation needs to change to use `uploadFile` instead of typing the text.

**Comment by SivasubramanianV** [comment]
@christian-bromann How do i upload if the element type is button instead of input? uploadFile does not seem to work in this case?
