### ISSUE TITLE
@wdio/firefox-profile-service does not properly load web extension

### ISSUE THREAD

**Issue by Photonios** [webdriverio/webdriverio#5095]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.20.1
 - **Mode:** wdio test runner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.15.0
 - **Yarn version:** 1.22.0
 - **Browser name and version:** Firefox 73.0b12
 - **Platform name and version:** macOS Mojave 10.14.5 (18F203)
 - **Additional wdio packages used (if applicable):** `@wdio/firefox-profile-service@5.16.11`

**Describe the bug**
`@wdio/firefox-profile-service` does not properly load web extensions. Web extensions are a newer form of extensions that can be loaded in all major browsers.

**To Reproduce**
Repository with a very simple set up that reproduces the issue. The test case tries to load the latest version of the AdBlock Plus extension. Which is a valid Web Extension.

https://github.com/Photonios/wdio-firefox-extension-issue-repro

ZIP of the repo in case it disappears: [wdio-firefox-extension-issue-repro-master.zip](https://github.com/webdriverio/webdriverio/files/4327201/wdio-firefox-extension-issue-repro-master.zip)

**Expected behavior**
The extension to be loaded.

**Additional context**
I did some digging to figure out what's happening. And yes, I did read the docs and added `xpinstall.signatures.required: true`.

`@wdio/firefox-profile-service` depends on a now deprecated NPM package [`firefox-profile`](https://www.npmjs.com/package/firefox-profile). This package was originally developed for Selenium and handles managing the Firefox profile and loading extensions.

`firefox-profile`'s mechanism for loading extensions is outdated and incorrect. In order to install an extension, it needs some metadata such as the extension ID, name and version. It attempts this by trying to read three files, in a particular order, falling back to the next one if it fails:

1. `install.rdf`, a file associated with old style extensions. This fails in the example repo I added.
2. `package.json`, almost any serious extension has this and it is generally not documented to be an important file for extensions. Not sure why it tries.
3. `manifest.json`, a file associated with Web-Extensions. This should work.

See: https://github.com/saadtazi/firefox-profile-js/blob/2e3f4fc6b9ad3583bd13dc1a9dec2329715ed15a/lib/firefox_profile.js#L638

The problem here is the order. The AdBlock Plus extension has a `package.json` file and a `manifest.json` file. `firefox-profile` reads the `package.json` files and moves on. It then fails to load the extension because it couldn't extract a proper extension ID from the `package.json`. If we comment out some code and force it to read `manifest.json`, it all works fine.

Selenium is no longer using `firefox-profile` and uses a built-in implementation. This built-in implementation only supports Web Extensions: https://github.com/SeleniumHQ/selenium/blob/d9f7cefca4de175206bdd2b86cd1b4149b08c224/javascript/node/selenium-webdriver/firefox.js#L158

**The road to a fix**
I'd open a PR with a fix to the upstream `firefox-profile` package, but I am not sure what the intention was behind trying to load the `package.json` file. There must have been a reason for that. Without understanding why, I am not sure if removing that or changing the order is a good idea.

Since the upstream package (`firefox-profile`) is deprecated and no longer actively worked on, I am also not sure that a fix would be accepted.

**Comment by christian-bromann** [comment]
First off, great issue write up. Thank you!

> Since the upstream package (`firefox-profile`) is deprecated and no longer actively worked on, I am also not sure that a fix would be accepted.

I don't think it is deprecated. The last release was 19 days ago so it seems the maintainer is still accepting PRs. I would advise to make a PR upstream.

@Photonios let me know if I can assist with something. A PR to `firefox-profile` seems like the right approach to me.

**Comment by Photonios** [comment]
> @Photonios let me know if I can assist with something. A PR to firefox-profile seems like the right approach to me.

Good point. Thanks!

I've opened two PR's to address issues with WebExtensions compatibility:

https://github.com/saadtazi/firefox-profile-js/pull/106
https://github.com/saadtazi/firefox-profile-js/pull/107

The CI is failing due to a test that also fails on master. I'll report back here when the author has had a look at them.

**Comment by Photonios** [comment]
The author of `firefox-profile` just merged my fixes and released a new version on NPM: https://www.npmjs.com/package/firefox-profile/v/2.0.0

I'll open a PR in webdriverio somewhere today or tomorrow.

**Comment by christian-bromann** [comment]
This should be picked up by Greenkeeper. Thanks for the fix. Doing a release now.
