### ISSUE TITLE
Persisting Session Among Different Tests

### ISSUE THREAD

**Issue by tunix** [webdriverio/webdriverio#51]
This would be very usefull for authentication required tests.

**Comment by monolithed** [comment]
@christian-bromann, It seems I have the same problem. 

{
	capabilities: [
		{
			browserName: 'firefox',

			specs: [
				'tests/get_session.js',
				'tests/use_session.js',
 				...
			]
		}
	]
};

How to keep the session for my authentication required tests with test-runner?

**Comment by christian-bromann** [comment]
@monolithed if you use the test runner you don't need to create or end the session. It does that for you! In your case you should have the same session within both spec files

**Comment by monolithed** [comment]
@christian-bromann, it seems you are right


#### 1st test

```js
// auth/regular.js
let config = require('./config');

module.exports = () => {
	return browser.url('/user/login')
		...
};

```js
module.exports = type => {
	describe('Auth', () => {
		it(type, () => require('./auth/' + type)());
	});
```

#### 2nd test
	describe('Auth', () => {
		it(type, () => require('./auth/' + type)());
	});

**Comment by anshulsahni** [comment]
does setting singleton as true in wdio config file still works? I can't find anything related to that in documentation

**Comment by christian-bromann** [comment]
@tunix why do you still need this?

**Comment by anshulsahni** [comment]
For every spec it is running a different opens a new session of browser After I login test it should successfully run tests which require authentication but it doesn't

**Comment by christian-bromann** [comment]
if you run the wdio test runner you can't avoid that. I would recommend to create some page that logs you in automatically and is only reachable in your test environment or write all tests in a single spec where you login first

**Comment by monolithed** [comment]
After some time, I realized that using persistent session is not so good idea, but It can be implemented (as you please). 

@tunix, it's important to encapsulate your data and avoid any side-effects. The state of your interface should not be kept after each test. 
Real-world experience shows that you should have a simple Account service to create or get new sessions. Of course, you can have reusable accounts (in my practice, we have about 9 000 such accounts). But these accounts should be locked for parallel testing and cleaned / reseted after each test.  
For example, my Account service can work with different schemes like a new registered and reusable accounts. We also implemented different types of verification like Basic, OAuth and Multi-factor authentication.
I hope you will reconsider your testing practices and existing architecture.

**Comment by tunix** [comment]
Hi All,

A lot has passed since I've created this issue. I'm no longer interested in it as I can't even remember which project I asked this for.
