### ISSUE TITLE
Transfer promiseness takes only the 1st element of result array

### ISSUE THREAD

**Issue by silvenon** [webdriverio/webdriverio#510]
```html
<!-- index.html -->

<!-- ... -->
<div class="foo">Item 1</div>
<div class="foo">Item 2</div>
<div class="foo">Item 3</div>
<!-- ... -->
```

This works fine:

```js
// test.js

var assert = require('assert');
var client = require('webdriverio').remote({
  desiredCapabilities: {
    browserName: 'phantomjs'
  }
});

client.init().url('http://localhost:9000/index.html');
client.getText('.foo').then(function(text) {
  assert.deepEqual(text, ['Item 1', 'Item 2', 'Item 3']);
});
client.end();
```

But this compares only the 1st element of the array:

```js
// test.js

var chai = require('chai');
var chaiAsPromised = require('chai-as-promised');
var client = require('webdriverio').remote({
  desiredCapabilities: {
    browserName: 'phantomjs'
  }
});

chai.use(chaiAsPromised);
chai.should();
chaiAsPromised.transferPromiseness = client.transferPromiseness;

client.init().url('http://localhost:9000/index.html');
client.getText('.foo').should.become(['Item 1', 'Item 2', 'Item 3']);
// Uncaught AssertionError: expected 'Item 1' to deeply equal [ 'Item 1', 'Item 2', 'Item 3' ]
client.end();
```

Not sure if this is an issue in WebdriverIO or chai-as-promised, but haven't found anything on Google.

**Comment by Robinfr** [comment]
Yes, you're right. There are massive improvements being done using promises in the v3 branch that will be hopefully be released soon, and this is definitely something that should be a use-case.

**Comment by christian-bromann** [comment]
Todo here:
- make sure example above works (maybe include chai-as-promised to functional test suite)
- implement `transferPromiseness` method
- document it on website

**Comment by bryan-coursera** [comment]
One more thing here to note: on v3, the `client` prototype extends from `null`, which means that when `chai.should()` adds the `should` handler to `Object.prototype`, it doesn't get added to webdriverio clients. 

I've been able to work around this in v3 by changing

```var prototype = Object.create(null)``` to  ```var prototype = Object.create(Object.prototype)```

I'm not sure if this is the best approach, but it might be necessary to continue using `chai.should`

**Comment by christian-bromann** [comment]
good catch @bryan-coursera .. I will fix that

**Comment by christian-bromann** [comment]
Thanks again @bryan-coursera, awesome stuff!!
Closing this as there is only the documentation part left which will get tackled in #524.

**Comment by silvenon** [comment]
Wow, good job, guys :+1:
