### ISSUE TITLE
unknown error: missing or invalid 'entry.level'

### ISSUE THREAD

**Issue by srikanth654** [webdriverio/webdriverio#5105]
while trying to send the values for login through send_keys(),
 i am getting below error can any one help me for solving this.
i am using pycharm for automation and linux system.

raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status
from unknown error: missing or invalid 'entry.level'
  (Session info: chrome=80.0.3987.132)
  (Driver info: chromedriver=2.26.436382 (70eb799287ce4c2208441fc057053a5b07ceabac),platform=Linux 4.4.0-174-generic x86_64)

**Comment by christian-bromann** [comment]
I am sorry but it seems you are not using WebdriverIO. For Selenium issues please out their support channels. Thanks!
