### ISSUE TITLE
How to run multiple spec files sequentially on Multiremote with jasmine framework?

### ISSUE THREAD

**Issue by fottin** [webdriverio/webdriverio#5107]
**Describe your question with as much detail as possible**
I’m using Multiremote to test react native app on real iOS devices, with jasmine framework. Works fine with one spec file, but if I specify more than one file in the wdio.config.js it fails with the following error messages (see gist url below)

specs: [
       // './src/specs/**/notifications.ts',
        './src/specs/**/login.ts'
        //'./src/specs/**/*.ts'
    ],

The behaviour I would like to see it that each device run each spec sequentially. Currently, a spec is assigned to each device.

**If it's about a specific piece of code, try and include some of it to support your question.**
[...]

**Environment (please complete the following information):**
 - **WebdriverIO version:**  5.18.17
 - **Mode:**  WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:**  sync
 - **Node.js version:**  v10.16.3
 - **NPM version:**  6.9.0
 - **Browser name and version:** 
 - **Platform name and version:**  macOS Catalina 10.15.2 
 - **Additional wdio packages used (if applicable):** @wdio/appium-service, @wdio/cli, @wdio/dot-reporter, @wdio/jasmine-framework, @wdio/local-runner, @wdio/spec-reporter, @wdio/sync,

**Additional context**

<script src="https://gist.github.com/fottin/bc4264ca84b3d8a81d1ce81a8e2f99b6.js"></script>

**Comment by christian-bromann** [comment]
@fottin multiremote doesn't allow to run specs in parallel. I think there was an issue for this to implement such functionality but I couldn't find it.

**Comment by christian-bromann** [comment]
See also #1695

**Comment by fottin** [comment]
I am not trying to run the specs (spec A and spec B) in parallel. I am able to run spec A with multiremote where the two phone are communicating with each other. It works fine. I would like to run spec B after spec A has completed.

**Comment by christian-bromann** [comment]
@fottin that should work already if you have multiple specs defined.

**Comment by fottin** [comment]
Yes, I would have thought so. But, I looking for guidance on how to figure out what I'm doing incorrectly. Were you able to review the logs I attached in gist?

**Comment by christian-bromann** [comment]
It seems that your Appium server isn't running: `ECONNREFUSED 127.0.0.1:4723`

**Comment by fottin** [comment]
Yes, the Appium server stops running.
[debug] [XCUITest] Installing '/var/folders/x1/wbwr7jyx2rddp6533jlst90c0000gn/T/2020217-68681-9s7d4g.wdsw/myapp.app' on device with UUID 'f4a85a88bb94f725ac8bd22222b9b3355f938e42'...
uncaughtException: write EPIPE
Error: write EPIPE
    at WriteWrap.afterWrite (net.js:788:14)

**Comment by christian-bromann** [comment]
Not sure why that happens. I don't think this GitHub thread is the right channel to find a solution. I recommend to join the WebdriverIO or Appium support channels.

**Comment by fottin** [comment]
Why would @wdio/local-runner create worker threads (Runner) for each spec file immediately on start up? And then create a new session using the Webdriver protocol for each device?
2020-03-17T19:22:41.497Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in MultiRemote - /src/specs/basicCall.ts
2020-03-17T19:22:41.499Z DEBUG @wdio/local-runner: Runner 0-1 finished with exit code 1
[0-1] FAILED in MultiRemote - /src/specs/login.ts
2020-03-17T19:22:41.500Z DEBUG @wdio/local-runner: Runner 0-2 finished with exit code 1
[0-2] FAILED in MultiRemote - /src/specs/notifications.ts

**Comment by christian-bromann** [comment]
@fottin this is how the testrunner works. You can limit the amount of parallel sessions by the `maxInstances` option.

**Comment by fottin** [comment]
That's it! I did not realize I took maxInstances out. Thanks for for your assistance.
