### ISSUE TITLE
client.click <input> does not trigger keyboard to appear on Android

### ISSUE THREAD

**Issue by idw111** [webdriverio/webdriverio#511]
I'm testing hybrid app with webdriverio.

client
   .click('some input box')
   .keys('test')
   .call(done)

if I write code like this
keyboard does not show up even after click
keys method works fine in iOS anyway, 
but it does not work properly in Android.
nothing is typed in the input box and test fails.

**Comment by christian-bromann** [comment]
@idw111 have you tried `setInput` ?

**Comment by idw111** [comment]
It works with setValue
Thank you very much!
