### ISSUE TITLE
v5: recent typing update breaks typing,  "@types/request" should be a dependency.

### ISSUE THREAD

**Issue by dylang** [webdriverio/webdriverio#5110]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.22.1

**Describe the bug**

Typechecking broken.

```
tsc:
node_modules/webdriver/webdriver.d.ts:12:42 - error TS7016: Could not find a declaration file for module 'request'. '.../node_modules/request/index.js' implicitly has an 'any' type.
  Try `npm install @types/request` if it exists or add a new declaration (.d.ts) file containing `declare module 'request';`

12 declare type HTTPRequestOptions = import('request').CoreOptions;
                                            ~~~~~~~~~

node_modules/webdriver/webdriver.d.ts:13:36 - error TS7016: Could not find a declaration file for module 'request'. '.../node_modules/request/index.js' implicitly has an 'any' type.
  Try `npm install @types/request` if it exists or add a new declaration (.d.ts) file containing `declare module 'request';`

13 declare type HTTPResponse = import('request').Response;
                                      ~~~~~~~~~
```

**To Reproduce**

`yarn tsc` (in a project using this as a dependency)

**Expected behavior**

No errors. :)

**Additional context**

Caused by this change:

https://github.com/webdriverio/webdriverio/commit/b4964725e9959613c19a05f96d5d3bb82cb7dcc6#diff-12554ac08fae297f252f73877af06761

`"@types/request"` was mistakenly put in `devDependencies`:
https://github.com/webdriverio/webdriverio/commit/b4964725e9959613c19a05f96d5d3bb82cb7dcc6#diff-4ec534f89c7973240062931c8a15199dR40

**Comment by christian-bromann** [comment]
Deployed in `webdriver@5.22.3`
