### ISSUE TITLE
Drag and drop is not performing the expected action

### ISSUE THREAD

**Issue by deekshachaudhary** [webdriverio/webdriverio#5111]
I'm getting an element, calling dragAndDrop on it while passing in the target element, but it's not performing the drag and drop action. I'm using @wdio/cli version 5.16.7, Chrome version 80.0, also tried it in Firefox.
The documentation has this usage information:
`$(selector).dragAndDrop({ duration })`

I assume we'll also have to pass in the target element as the source code suggests. Here is how I'm using it: `await draggableElement.dragAndDrop(targetElement)`. I verified that I'm able to do other actions like doubleClick and getText on these elements. Any idea what might be going wrong?

**Comment by christian-bromann** [comment]
> Any idea what might be going wrong?

Not without any logs or a reproducible example.

**Comment by deekshachaudhary** [comment]
Everything I'm facing is summarized in [https://github.com/webdriverio/webdriverio/issues/4134](url), would be great to get a solution
