### ISSUE TITLE
Getting error:@wdio/runner: Error: Failed to create session.

### ISSUE THREAD

**Issue by GavinSun9527** [webdriverio/webdriverio#5112]
I used nodejs (wdio) to do a web application test  with AWS device farm(https://docs.aws.amazon.com/devicefarm/latest/testgrid/testing-frameworks-nodejs.html),

and my wdio.conf.js like this:
exports.config = {
    hostname: "testgrid-devicefarm.us-west-2.amazonws.com",        // This should match the host portion of the URL
    port: 443,    // This must be 443
    path: "xxxxxxx",
    protocol: "https",
    runner: 'local',
    capabilities: [{
        browserName: 'chrome', // options: `firefox`, `chrome`, `opera`, `safari`
        browserVersion: '80.0', // browser version
        platformName: 'windows' // OS platform
    }],
 
     xxxxxxxxxxxxxx
}

and my package.json like this:
xxxxxxxxxxxxxxxxxxxxx
"dependencies": {
    "@wdio/appium-service": "^5.11.4",
    "@wdio/cli": "^5.11.6",
    "@wdio/dot-reporter": "^5.11.0",
    "@wdio/local-runner": "^5.11.6",
    "@wdio/mocha-framework": "^5.11.0",
    "@wdio/sync": "^5.11.0",
    "appium-windows-driver": "^1.10.0",
    "fibers": "^4.0.2"
  },
  "bundledDependencies": [
    "@wdio/appium-service",
    "@wdio/cli",
    "@wdio/dot-reporter",
    "@wdio/local-runner",
    "@wdio/mocha-framework",
    "@wdio/sync"
  ]
xxxxxxxxxxxxxxxx

When I run command '."/node_modules/.bin/wdio" wdio.conf.js'.

I will get the error:
 "ERROR @wdio/runner: Error: Failed to create session.".
getaddrinfo ENOTFOUND testgrid-devicefarm.us-west-2.amazonws.com
    at startWebDriverSession (D:\github\appium\devicefarm-web-nodejs-test\node_modules\webdriver\build\utils.js:45:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0-0] FAILED in chrome - D:\github\appium\devicefarm-web-nodejs-test\test\specs\basic.js
2020-03-19T08:37:10.556Z INFO @wdio/cli:launcher: Run onComplete hook

2020-03-19T08:37:10.560Z INFO @wdio/local-runner: Shutting down spawned worker
2020-03-19T08:37:10.812Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2020-03-19T08:37:10.813Z INFO @wdio/local-runner: shutting down

Should I change 'runner' from local to xxxx(any else) ? or some other errors ?

**Comment by christian-bromann** [comment]
As you can see from the error message:

```
getaddrinfo ENOTFOUND testgrid-devicefarm.us-west-2.amazonws.com
```

it seems that it can't find your test farm. This looks like a AWS configuration issue. Therefor closing this issue.
