### ISSUE TITLE
Can path be modified in onPrepare hook in wdio.config file?

### ISSUE THREAD

**Issue by mrahman2327** [webdriverio/webdriverio#5113]
**Describe your question with as much detail as possible**
Is it expected that path cannot be modified in the onPrepare hook? Here is what I am experiencing - 
I set the hostname, port, protocol, and path in the onPrepare hook, while the hostname, port, and protocol is updated, path is ignored. More details on code below. 

**If it's about a specific piece of code, try and include some of it to support your question.**
```
onPrepare(config, capabilities) {
        console.log(config);
        // Outputs default config -
        // hostname: '127.0.0.1',
        // port: 4444,
        // protocol: 'http',
        console.log(config.path); // outputs undefined

        config.hostname = 'newHost';
        config.port = 1234;
        config.protocol = 'https';
        config.path = '/newPath';
        
        console.log(config);
        // Outputs updated config -
        // hostname: 'newHost',
        // port: 1234,
        // protocol: 'https',
        //  ...other_config options
        // path: '/newPath'
}
```
Can see that the path is updated in the config at the end. However, when the worker starts, I see this log - 
```
[0-0]  INFO @wdio/local-runner: Run worker command: run
[0-0]  RUNNING in chrome - <path-to-file>
[0-0]  DEBUG @wdio/local-runner:utils: init remote session
[0-0]  INFO webdriverio: Initiate new session using the webdriver protocol
[0-0]  INFO webdriver: [POST] https://newhost:1234/wd/hub/session
```
Notice the POST, the path is not updated. 
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.18.6
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:**  13.9.0
 - **NPM version:** 6.13.7
 - **Browser name and version:** Chrome 80
 - **Platform name and version:** MacOS Catalina 10.15.3
 - **Additional wdio packages used (if applicable):** @wdio/spec reporter, @wdio/cli, @wdio/devtools-service, @wdio/jasmine-framework, @wdio/local-runner, @wdio/sync

**Comment by christian-bromann** [comment]
Can you try the `beforeSession` hook to modify connection details?

**Comment by mrahman2327** [comment]
> Can you try the `beforeSession` hook to modify connection details?

Just tried it and it works! 🎉beforeSession is the right place to do that. Thank you @christian-bromann!
