### ISSUE TITLE
invalid argument: unrecognized capability: enableVNC

### ISSUE THREAD

**Issue by fedika** [webdriverio/webdriverio#5119]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.22.3
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v12.13.0
 - **NPM version:** v6.12.0
 - **Browser name and version:** Docker selenoid/vnc_chrome:79
 - **Platform name and version:** Linux
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
  hostname: 'localhost',
  port: 4004,
...
{
      browserName: 'chrome',
      // platform: 'Windows 10',
      // version: '79.0',
      maxInstances: 2,
      'goog:chromeOptions': {
        args: [
          '--enable-automation',
          '--fullscreen',
          // '--headless',
          '--no-sandbox',
          '--disable-webgl=true',
          '--disable-3d-apis=true',
        ],
      },
      enableVNC: true,
    },

**Describe the bug**
We use selenoid for env to run tests, but we unable to use enableVNC: true on conf.
The error is "invalid argument: unrecognized capability: enableVNC"
When enableVNC commented (not set to false), the tests run successfully

**To Reproduce**
turn on the selenoid and selenoid ui
run the test on selenoid

**Expected behavior**
The test run successfully and we able to see the test progress using VNC on selenoid UI

**Log**
[0-0] RUNNING in chrome - /test/features/login.feature
[0-1] RUNNING in chrome - /test/features/menu/earn.feature
[0-0] Error: Failed to create session.
invalid argument: unrecognized capability: enableVNC
[0-0] FAILED in chrome - /test/features/login.feature
[0-1] Error: Failed to create session.
invalid argument: unrecognized capability: enableVNC
[0-1] FAILED in chrome - /test/features/menu/earn.feature

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
> When enableVNC commented (not set to false), the tests run successfully

You need to set Selenioid capabilities accordingly like this:
```
    {
      browserName: 'chrome',
      // platform: 'Windows 10',
      // version: '79.0',
      maxInstances: 2,
      'goog:chromeOptions': {
        args: [
          '--enable-automation',
          '--fullscreen',
          // '--headless',
          '--no-sandbox',
          '--disable-webgl=true',
          '--disable-3d-apis=true',
        ],
      },
      "selenoid:options" : { enableVNC: true }
    }
```
