### ISSUE TITLE
Switching between sync and async mode

### ISSUE THREAD

**Issue by alfonso-presa** [webdriverio/webdriverio#5120]
**Is your feature request related to a problem? Please describe.**

In some situations, parallel execution of commands in needed in shake of efficiency. For example, reading a big table, checking if multiple elements are visible, etc. Having the commands executed sequentially can be a time hog in this situations.

**Describe the solution you'd like**
I would like a way to toggle between both modes. Maybe something like `browser.sync(true/false)`, or even better something like:

```
browser.call(async () => {
    //as true was pased for the async parameter, all commands here would be async.
}, true);
```

**Describe alternatives you've considered**

Right now I've been able to get this behaviour by setting the `_NOT_FIBER` flag on browser and elements. I would also like some feedback on whether this would consistently work as a workarround or if it might have some edge cases.

I guess that it would be relatively easy to set a global flag that is also checked just like the  `_NOT_FIBER` flag (would happily PR if this solution is good for you).

**Comment by alfonso-presa** [comment]
I'm doing some tries and it seems like browser.call turns everything into async. Is this the intended behaviour? If so then it's great :-). Anyway I would like to see a way to turn on or off the sync mode globally for a test execution, because we have a bunch of tests already developed in async mode, but we would like to start using sync for new ones, so we were also trying to switch between both modes during test execution without having to wrap everything in a single block.

**Comment by christian-bromann** [comment]
> Is this the intended behaviour?

Yes, if the function you pass in is an `async` function then yes.

> Anyway I would like to see a way to turn on or off the sync mode globally for a test execution, because we have a bunch of tests already developed in async mode

This should already work if you use `async/await`, like:

```
it("...", async () => {
  // ...
})
```

**Comment by alfonso-presa** [comment]
Great! I've checked that it was not working because we had wrongly wrapped the cucumber keyword  functions... But when done correctly it works :-). Only thing I'm missing, and that would make this perfect, is a way to turn on the sync mode when the step (or it) started in async mode. Is that possible?

**Comment by alfonso-presa** [comment]
Would it make sense to use the runSync shim from utils for this usecase?

**Comment by christian-bromann** [comment]
> Is that possible?

Why don't you just do all async things within a `browser.call` callback? If you want to switch to async use that.

I will close this issue but happy to assist further.

**Comment by christian-bromann** [comment]
If:
```js
await new Promise(require('@wdio/sync').runSync(() => {
  browser.pause(1000); 
}));
```
works for you I think you should be fine to use it.

**Comment by alfonso-presa** [comment]
Great! Thank you!!
