### ISSUE TITLE
Need support for positional CSS selectors (:first-child, :first-of-type, :nth-child etc)

### ISSUE THREAD

**Issue by vdineva** [webdriverio/webdriverio#513]
Currently WebdriverIO does not support a positional CSS selector which follows an id selector, e.g. `'#someId:first-child'`.

Suppose I need to get to the `#purplebox` div only if it is a first-child of its parent.
In a browser `document.querySelector('#purplebox:first-child')` returns 
1. either the element (if it's a first child of it's parent element) 
```html
<div>
    <div id="purplebox"></div>
</div>
```
OR 
2. null, if #purplebox is not the first child of it's parent element
```html
<div>
    <div class="box black"></div>
    <div id="purplebox"></div>
</div>
````

Currently WebdriverIO throws and uncaughtException for when trying to locate `'#purplebox:first-child'` with the second html structure

**Comment by Robinfr** [comment]
``:first`` is also a jQuery selector actually. You could try using ``first-child`` or ``nth-child``.

**Comment by christian-bromann** [comment]
As I don't think it is a big effort to transform the xPath for those pseudo selectors I guess we can add that for the `v3` milestone

**Comment by vdineva** [comment]
@Robinfr : yes `:first` is not a CSS specification selector but a jQuery syntactic sugar. I've updated the issue. However currently `:first-child` or `nth-child` do not work

**Comment by christian-bromann** [comment]
See #514
