### ISSUE TITLE
Typings of write method in @wdio/reporter missing

### ISSUE THREAD

**Issue by dpoetzsch** [webdriverio/webdriverio#5136]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.18.6
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.16.1
 - **NPM version:** 6.13.4
 - **Browser name and version:** doesnt matter
 - **Platform name and version:** Fedora Linux 31
 - **Additional wdio packages used (if applicable):** @wdio/reporter

**Describe the bug**
The typings for the `write` method of the `Reporter` base class are missing.

**To Reproduce**
1. Create a custom reporter as described here: https://webdriver.io/docs/customreporter.html
2. When using typescript, there is an error when calling the `write` method.

An example of the behavior is here: https://github.com/mondata-dev/wdio-visual-regression-reporter. `npm run build` will produce the error.

**Expected behavior**
I'd expect the write method to be in the [typings](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-reporter/reporter.d.ts)

**Comment by christian-bromann** [comment]
@dpoetzsch interested making a PR for this? I would be happy to assist you!

**Comment by dpoetzsch** [comment]
Definitely, I was about to add the method to the `report.d.ts` file and create a PR, but I got confused of this rather complex entry here: https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md#typescript-definitions.

Now I'm not exactly sure what I have to do.. Am I correct to just add the type followed a run of `npm run generate:typings`?

**Comment by christian-bromann** [comment]
> Am I correct to just add the type followed a run of `npm run generate:typings`?

The type definitions for the reporter are not autogenerated so you can modify https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-reporter/reporter.d.ts directly.

**Comment by dpoetzsch** [comment]
Thanks for the help :)
