### ISSUE TITLE
webdriverio standalone mode not working in react

### ISSUE THREAD

**Issue by utadachiren** [webdriverio/webdriverio#5139]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.22.4
 - **Mode:** Standalone mode
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 13.9.0
 - **NPM version:** 6.13.7
 - **Browser name and version:** Chrome 80
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** none

**Config of WebdriverIO**
Please look at my repo https://github.com/utadachiren/try-react-webdriverio-standalone-mode-ts.git

**Describe the bug**
When `yarn start`, Failed to compile.

**To Reproduce**

```
git clone https://github.com/utadachiren/try-react-webdriverio-standalone-mode-ts.git
cd try-react-webdriverio-standalone-mode-ts
yarn
yarn start
```

**Expected behavior**
Success to compile

**Log**

```
Failed to compile.

./node_modules/@wdio/repl/build/index.js
Module not found: Can't resolve 'repl' in 'C:\Users\ut\Documents\workspace\try-react-webdriverio-ts\node_modules\@wdio\repl\build'\try-react-webdriverio-ts\node_modules\@wdio\repl\build'
```

**Comment by christian-bromann** [comment]
Why would you want to run WebdriverIO in the browser?

**Comment by utadachiren** [comment]
> Why would you want to run WebdriverIO in the browser?

We want to run WDIO with some parameters, but some of us can't use CLI tools.
Do you have any good way?

**Comment by christian-bromann** [comment]
> but some of us can't use CLI tools

I am not sure what you mean by that. WebdriverIO has to be used from the command line. We are experimenting with running it in the browser but you will need a cloud provider to run tests then. I will close this as it is not really an issue of WebdriverIO.
