### ISSUE TITLE
clearValue and setValue do not clear input fields in wdio v5

### ISSUE THREAD

**Issue by urilevy2** [webdriverio/webdriverio#5141]
**Environment:**
 - **WebdriverIO version:** 5.22.3
 - **chromedriver version:** 79.0.1
 - **Node.js version:** 10.15.3
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome 80
 - **Platform name and version:** Mac OS 10.14.6

I've recently updated webdriverio from 4.13.2 to 5.22.3 and chromedriver from 2.45.0 to 79.0.1.
Since the update clearValue (previously clearElement) is not working at all.
setValue also not clearing fields before setting new values (it just appends it to the existing value).
I'm not getting any errors.

I read somewhere that it is a chromedriver issue, but couldn't find any good workarounds.

I found this issue:
https://github.com/webdriverio/webdriverio/issues/1140
which seems the same as mine, and i tried each and every workarounds suggested in it.
Some of them didn't work at all (`browser.keys(['Meta',a])` for example), some of them worked on regular text fields, but didn't on formatted fields like phone number which adds parentheses and dashes as you type (like using backspace or double clicking and deleting)

I'm all out of clever workarounds.

Any ideas on why it is happening / maybe using different combination of versions to make it work with WebdriverIO v5?

**Comment by christian-bromann** [comment]
This is indeed an issue of Chromedriver and WebdriverIO has to rely on the fact that Chromedriver is doing things correctly. Please report an issue in the Chromedriver project. As a workaround you can try to set values using JavaScript and the `execute` command. Will close this issue but I am happy to assist further.
