### ISSUE TITLE
Unable to use in TS project: webdriver.d.ts references outdated @types/got package

### ISSUE THREAD

**Issue by adierkens** [webdriverio/webdriverio#5157]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.0.2
 - **Mode:** Standalone
 - **Node.js version:** 12.16.1
 - **NPM version:** 6.13.4
- **TS version:** 3.8.3

The `webdriver.d.ts` types file [here](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriver/webdriver.d.ts#L13) references the `got` package, using generics for `GotOptions` and `Response`: 

```ts
declare type HTTPRequestOptions = import('got').GotOptions<any>;
declare type HTTPResponse = import('got').Response<any>;
```

These generics come from the `@types/got` package, but the version of `got` requested by `webdriver` already ships with types; and doesn't use generics for either type. This causes a typescript compilation error:

```sh
@proof-ui/browser: $ tsc
@proof-ui/browser: ../../node_modules/webdriver/webdriver.d.ts(13,35): error TS2315: Type 'GotOptions' is not generic.
```

The current suite of tests copies the `@types/got` declaration into the testing folder, and the root `node_modules` contains an older (non-typed) version of `got`, so the types don't conflict, and the tests pass. The [copy](https://github.com/webdriverio/webdriverio/blob/master/tests/typings/copy.js#L54) utility also fails to copy `.d.ts` files nested in a sub-folder (as they are for the `got` package, and many natively typescript packages)

**Comment by christian-bromann** [comment]
Fixed in #5160
