### ISSUE TITLE
devtools: Cannot find module puppeteer-core/node_modules/debug

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#5167]
**Environment:**
 - **WebdriverIO version:** 6.0.5
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.16.1
 - **NPM version:** 6.14.4
 - **Browser name and version:** any
 - **Platform name and version:** any

**Config of WebdriverIO**
Any.

**Describe the bug**
Test runner crashes, see logs.
Possible cause: 
https://github.com/webdriverio/webdriverio/pull/5007/files#diff-ac866ff0354e029d2ba18bc72e991988R19
Locking puppeteer-core to 2.1.1 with npm shrinkwrap does not help.

**To Reproduce**
???
Upgrade to v6.

**Expected behavior**
Test runner should not not crash.

**Log**
```js
(node:10834) UnhandledPromiseRejectionWarning: Error: Cannot find module '/Users/[REDACTED]/Repos/wdio-v6/node_modules/puppeteer-core/node_modules/debug'
Require stack:
- /Users/[REDACTED]/Repos/wdio-v6/node_modules/devtools/build/index.js
- /Users/[REDACTED]/Repos/wdio-v6/node_modules/webdriverio/build/utils.js
- /Users/[REDACTED]/Repos/wdio-v6/node_modules/webdriverio/build/multiremote.js
- /Users/[REDACTED]/Repos/wdio-v6/node_modules/webdriverio/build/index.js
- /Users/[REDACTED]/Repos/wdio-v6/node_modules/@wdio/cli/build/commands/repl.js
- /Users/[REDACTED]/Repos/wdio-v6/node_modules/yargs/index.js
- /Users/[REDACTED]/Repos/wdio-v6/node_modules/@wdio/cli/build/index.js
- /Users/[REDACTED]/Repos/wdio-v6/node_modules/@wdio/cli/bin/wdio.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/[REDACTED]/Repos/wdio-v6/node_modules/devtools/build/index.js:47:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)

```

**Comment by j320** [comment]
I'm also experiencing this

**Comment by JustSittinHere** [comment]
I started a new project and can recreate the issue with the below files, but if I swap out `@wdio/selenium-standalone-service` for `chromedriver` and `wdio-chromedriver-service` everything is fine. 

**package.json**
```{
  "name": "wdio-v6-devtools",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "wdio"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@wdio/cli": "6.0.5",
    "@wdio/jasmine-framework": "6.0.4",
    "@wdio/local-runner": "6.0.5",
    "@wdio/selenium-standalone-service": "6.0.4",
    "@wdio/spec-reporter": "6.0.4",
    "@wdio/sync": "6.0.1",
    "npm-check-updates": "4.1.0"
  }
}
```

**wdio.conf.js**
```exports.config = {
    runner: 'local',
    automationProtocol: 'webdriver',
    specs: [
        './tests/**/*.js'
    ],
    maxInstances: 1,
    capabilities: [{
        maxInstances: 1,
        browserName: 'chrome',
    }],
    logLevel: 'trace',
    bail: 0,
    baseUrl: 'https://webdriver.io',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    services: ['selenium-standalone'],
    framework: 'jasmine',
    reporters: ['spec'],
}
```

**Comment by EllieMaeUI** [comment]
the issue is happening because of this line https://github.com/webdriverio/webdriverio/blob/master/packages/devtools/src/index.js#L19

**Comment by vinothvk** [comment]
issue is happening because of this line https://github.com/webdriverio/webdriverio/blob/master/packages/devtools/src/index.js#L19

**Comment by christian-bromann** [comment]
@nextlevelbeard can you provide a reproducible example? I installed a fresh version of WebdriverIO and was able to run tests using the devtools package without this error.

**Comment by matthew-johnston** [comment]
I also hit the same issue, but managed to make it disappear after trying a few things. I deleted node_modules and package-lock.json, then ran `npm install`. Somewhere along the line I installed "puppeteer-core": "^2.1.1" as a dev dependency, may or may not be needed.

**Comment by WasiqB** [comment]
@christian-bromann , any solution or workaround for this issue? I just upgraded my office project from v5 to v6, and it threw the above error when I executed any of my test. With v5, it was working fine. Any quick help will be highly appreciated.

**Steps to reproduce:** 
- In existing v5 project, upgrade all wdio dependencies to v6.
- Delete `node_modules` and `package-lock.json`
- Run `npm install`
- Run any existing spec / suite.

**Comment by christian-bromann** [comment]
@WasiqB can you provide a minimal reproducible example?

**Comment by WasiqB** [comment]
@christian-bromann , I'll try to reproduce the issue in my [repo](https://github.com/WasiqB/my-wdio) and update you soon.

**Comment by WasiqB** [comment]
@christian-bromann , issue is not replicated in my project, however, in my office project I'm still facing same issue.

**Comment by Xotabu4** [comment]
> @christian-bromann , issue is not replicated in my project, however, in my office project I'm still facing same issue.

Can you check your nodejs versions? For me it is clearly reproducible with v13.10.1 and yarn - 1.22.4

**Comment by Xotabu4** [comment]
Added debug line to see what is trying to be imported:

```

const puppeteerDebugPkg = _path.default.resolve(_path.default.dirname(require.resolve('puppeteer-core')), 'node_modules', 'debug');

console.log('####', puppeteerDebugPkg)

#### /Users/oleksandr.khotemskyi/Documents/ClearMove/application/node_modules/puppeteer-core/node_modules/debug
```


But my structure of this package is following:

![image](https://user-images.githubusercontent.com/3033972/77906648-f5a04580-7290-11ea-8a53-52e180f6f2be.png)

**Comment by Xotabu4** [comment]
@christian-bromann i think i found root cause, but not quite sure how to fix it. Maybe just move debug package to own wdio dependenices?
