### ISSUE TITLE
@wdio/applitools-service  - test.parent is undefined cause eys.open to fail

### ISSUE THREAD

**Issue by igivon** [webdriverio/webdriverio#5169]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.18.0
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:**sync
 - **Node.js version:** v12.16.1
 - **NPM version:** 6.14.2
 - **Browser name and version:** Chrome 80
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** 
    "@wdio/appium-service": "^5.16.11",
    "@wdio/applitools-service": "^6.0.4",
    "@wdio/cli": "^5.18.1",
    "@wdio/jasmine-framework": "^5.16.15",
    "@wdio/local-runner": "^5.18.0",
    "@wdio/sauce-service": "^5.16.10",
    "@wdio/spec-reporter": "^5.16.11",
    "@wdio/sync": "

**Config of WebdriverIO**
exports.config = {
    //Enable debug 
    debug: true,
    execArgv: ['--inspect=127.0.0.1:5861'],

    // ====================
    // Runner and framework
    // Configuration
    // ====================
    runner: 'local',
    framework: 'jasmine',
    jasmineNodeOpts: {
        // Updated the timeout to 30 seconds due to possible longer appium calls
        // When using XPATH
        defaultTimeoutInterval: 400000,
    },
    sync: true,
    logLevel: 'info',
    deprecationWarnings: true,
    bail: 0,
    baseUrl: 'REDUCTED',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    reporters: [ 'spec',[reportportal, rpConf] ],

    // ====================
    // Appium Configuration
    // ====================
    services: [ 
        ['applitools', {
            key: 'REDUCTED'
        }],
        'appium',
        [RpService, {}],
    ],
    applitools:{
        key: 'REDUCTED',
        isConfigured: true
    },

    // services: [ 'appium' ],
    appium: {
        // For options see
        // https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-appium-service
        args: {
            'log-level':'info',
            'log-timestamp':true,
            'debug-log-spacing':true
            // For arguments see
            // https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-appium-service
        },
        command : 'appium'
    },

**Describe the bug**
The service try to open eye's (open.eyes - index.js line 89) with test.parent that is **undefined** in the beforeTest hook when using Jasmine framework. 
this result with service not working (eyes is not initialized) 
also the test.title should be the third parameter and not the seconde and the seconde is the app name (eyes.open(driver, appName, testName, viewportSize);) - currently there is a mismatch between them.

suggested solution: 
1. use app name from **options** and if undefined use test.fullName

 // global.browser.call(() => this.eyes.open(global.browser, test.title, test.parent, this.viewport));
    global.browser.call(() => this.eyes.open(global.browser, test.fullName.replace(test.title,''), test.title, this.viewport))

**To Reproduce**
use the service with **Jasmine** framework

**Expected behavior**
* don't use undefined when trying to initialize eye's object.
* App name should be from options
* batch name should be the spec name (test.fullName.replace(test.title,'')) - recommended to add configuration (const {Configuration} = require('@applitools/eyes-selenium'))
* should work on all wdio supported framework including cucumber

**Comment by christian-bromann** [comment]
@igivon thanks for raising the issue. It seems that your are using the Applitools version in `v6.0.4` which is not compatible with all your other wdio packages which all still on v5. Please install v5 of the Applitools service or upgrade completely to v6.

Closing the issue as I think the comment above is the reason for this issue. Happy to assist further.

**Comment by igivon** [comment]
the same with: @wdio/applitools-service": "^5.16.11
also note that test.title should be the 3rd parameter and not the 2nd. the 2nd is the app name eyes.open(driver, appName, testName, viewportSize) - currently there is a mismatch between them.
also app name i recommend taken from the options (user defined)

[0-0] 2020-03-30T14:12:56.752Z INFO @wdio/applitools-service: Open eyes for undefined Wrong activation key
[0-0] 2020-03-30T14:12:56.768Z ERROR @wdio/sync: Error: IllegalArgument: testName is null or undefined
    at Function.notNull (C:\Users\iddang\Source\Repos\Frontline\systemtestingfrontline\node_modules\@applitools\eyes-common\lib\utils\ArgumentGuard.js:44:13)
    at EyesWDIO.open (C:\Users\iddang\Source\Repos\Frontline\systemtestingfrontline\node_modules\@applitools\eyes-webdriverio\src\EyesWDIO.js:164:19)
    at C:\Users\iddang\Source\Repos\Frontline\systemtestingfrontline\node_modules\@wdio\applitools-service\build\index.js:83:41
    at Browser.call (C:\Users\iddang\Source\Repos\Frontline\systemtestingfrontline\node_modules\webdriverio\build\commands\browser\call.js:9:10)
    at Browser.runCommandWithHooks (C:\Users\iddang\Source\Repos\Frontline\systemtestingfrontline\node_modules\@wdio\sync\build\wrapCommand.js:88:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Browser.runCommandWithHooks (C:\Users\iddang\Source\Repos\Frontline\systemtestingfrontline\node_modules\@wdio\sync\build\wrapCommand.js:82:22)
    at Browser.wrapCommandFn (C:\Users\iddang\Source\Repos\Frontline\systemtestingfrontline\node_modules\@wdio\sync\build\wrapCommand.js:59:40)
    at ApplitoolsService.beforeTest (C:\Users\iddang\Source\Repos\Frontline\systemtestingfrontline\node_modules\@wdio\applitools-service\build\index.js:83:20)
    at execHook (C:\Users\iddang\Source\Repos\Frontline\systemtestingfrontline\node_modules\@wdio\sync\build\executeHooksWithArgs.js:32:23)
[0-0] Error in "BeforeTest Hook"
IllegalArgument: testName is null or undefined


    "@babel/cli": "^7.7.7",
    "@babel/core": "^7.7.7",
    "@babel/preset-env": "^7.7.7",
    "@babel/register": "^7.7.7",
    "@babel/traverse": "^7.7.4",
    "@babel/types": "^7.7.4",
    "@wdio/appium-service": "^5.16.11",
    "@wdio/applitools-service": "^5.16.11",
    "@wdio/cli": "^5.18.1",
    "@wdio/jasmine-framework": "^5.16.15",
    "@wdio/local-runner": "^5.18.0",
    "@wdio/sauce-service": "^5.16.10",
    "@wdio/spec-reporter": "^5.16.11",
    "@wdio/sync": "^5.17.0",
    "babel-eslint": "^10.0.3",
    "eslint": "^6.8.0",
    "eslint-config-standard": "^14.1.0",
    "eslint-plugin-import": "^2.19.1",
    "eslint-plugin-node": "^10.0.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1",
    "eslint-plugin-wdio": "^5.13.2",
    "node-fetch": "^2.6.0",
    "wdio-reportportal-reporter": "^5.2.3",
    "wdio-reportportal-service": "^5.2.3",
    "webdriverio": "^5.18.0"

**Comment by christian-bromann** [comment]
Feel free to provide a PR. Thanks!

**Comment by christian-bromann** [comment]
We have deprecated the `@wdio/applitools-service` in favor of `@applitools/eyes-webdriverio`. This issue is therefor not relevant anymore.
