### ISSUE TITLE
Click $(selector).click({ x, y }) is performed on wrong coordinates

### ISSUE THREAD

**Issue by katerina-stepanova** [webdriverio/webdriverio#5178]
**Environment:**
 - **WebdriverIO version:** 6.0.1
 - **Mode:** WDIO Testrunner, sync
 - **Node.js version:** v12.16.1
 - **NPM version:** 6.13.4
 - **Browser name and version:** Chrome 80
 - **Platform name and version:** MacOs 10.14.6 (other OSes not checked)
 - **Additional wdio packages used (if applicable):** n/a

**Config of WebdriverIO**
Nothing special, default config.

**Describe the bug**
Click $(selector).click({ x, y }) is performed x horizontal and y vertical pixels away from the top left corner of the page, instead of x horizontal and y vertical pixels away from the location of an element found by selector.

**To Reproduce**
browser.url('https://webdriver.io/')
let size = $('.pluginRowBlock div:first-child').getSize() //size is ~115x40
$('.pluginRowBlock div:first-child').click({x: 25, y: 10}) 

**Expected behavior**
Click should be performed x horizontal pixels and y vertical pixels away from the elements location.
In the example above, 'Get started' button should be clicked 25 pixels horizontally and 10 pixels vertically from its top left corner

**Comment by christian-bromann** [comment]
@katerina-stepanova I assume you were using the `devtools` package as automation layer which indeed differed from the `webdriver` way of doing things. This is being fixed by #5193.
