### ISSUE TITLE
Logs are missing after browser.uploadFile function call

### ISSUE THREAD

**Issue by IgorSasovets** [webdriverio/webdriverio#5185]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.22.4
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** v10.15.0
 - **NPM version:** 6.4.1
 - **Browser name and version:** Version 80.0.3987.149 (Official Build) (64-bit)
 - **Platform name and version:** Ubuntu 19.04 (Disco Dingo)
 - **Additional wdio packages used (if applicable):** 
```
    "@wdio/cli": "5.22.4",
    "@wdio/dot-reporter": "5.22.4",
    "@wdio/local-runner": "5.22.4",
    "@wdio/mocha-framework": "5.18.7",
    "@wdio/sauce-service": "6.0.8",
    "@wdio/selenium-standalone-service": "^5.9.3",
    "@wdio/spec-reporter": "^5.22.4",
    "@wdio/sync": "^5.20.1"
```

**Config of WebdriverIO**
[config file](https://github.com/IgorSasovets/wdio-file-upload/blob/master/wdio.conf.js)

**Describe the bug**
I want to test an image upload functionality of the application. When I run the test that uses file upload functionality, I cannot see any logs after upload file command was called. In some cases, for example when I run it on the project that has a lot of modal windows, angular-material components, it just freezes and I can stop it only using Ctrl + C command. I run the tests in debug mode and logs
would help me to investigate the root cause of failures, but I cannot get them

**To Reproduce**

[Sample project](https://github.com/IgorSasovets/wdio-file-upload)

**Expected behavior**
Logs are available in the console after `uploadFile` command was executed.

**Log**
Logs of the run with an enabled upload spec:
[logs-with-upload.txt](https://github.com/webdriverio/webdriverio/files/4410076/logs-with-upload.txt)

Logs of the run with a disabled upload spec:
[logs-without-upload.txt](https://github.com/webdriverio/webdriverio/files/4410082/logs-without-upload.txt)

**Comment by christian-bromann** [comment]
Thanks for your well written issue. I was not able to reproduce the issue. Your test case pass for me all the time (I am on MacOS).

**Comment by IgorSasovets** [comment]
@christian-bromann , thank you for the quick response. The test case pass for me to, but the reason is that I am not able to get the other logs after `browser.uploadFile` function was called. Please see two attached log files. Could you please attach your log file?

**Comment by christian-bromann** [comment]
Here is my log file:
[log1.txt](https://github.com/webdriverio/webdriverio/files/4437093/log1.txt)

**Comment by IgorSasovets** [comment]
@christian-bromann , thank you for your time. I'll keep investigating this issue on my local environment. BTW, I managed to solve it on firefox using JS scripts for file upload
