### ISSUE TITLE
[Browserstack Service] App Automate URL not being set correctly, function deprecation warnings

### ISSUE THREAD

**Issue by esaari** [webdriverio/webdriverio#5189]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [6.0.8]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [12.8.1]
 - **NPM version:** [6.10.2]
 - **Browser name and version:** [Chrome 80]
 - **Platform name and version:** [Mac OS.X 12.15.4]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/browserstack-service]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**

Constant warnings being emitted, but also the base URL for App Automate sessions won't be correctly set unless the 'app' property is read from browser capabilities.
`ERROR @wdio/sync: TypeError: Cannot read property 'app' of undefined
    at BrowserstackService.before (/Users/ericsaari/code/jwplayer-commercial/test/jwp-wdio/node_modules/@wdio/browserstack-service/build/service.js:41:34)`

Constant warnings in logs regarding: 
`ERROR @wdio/sync: TypeError: Parameter `auth` is deprecated. Use `username` / `password` instead.`
**To Reproduce**
Run any test using browserstack-service on webdriverio 6.x

[Include code or an example repository that can easily be set up]

**Expected behavior**
For these warnings not to happen.

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**
Proposed fix in https://github.com/webdriverio/webdriverio/pull/5188

> Please use the correct markdown

**Comment by christian-bromann** [comment]
Let's continue convo in #5188
