### ISSUE TITLE
chain selectors (or filtering, or context selector)

### ISSUE THREAD

**Issue by obsidianart** [webdriverio/webdriverio#519]
I'm trying to select an area and then filter inside it but it seems chaining only return the original object

//I want to search for the text 'Learn more' inside the element, but this code actually consider the click as a new search in the entire document. I know I can use a different selector for the click but please understand that is a simplified example.
browser.element('#beta-request-form').click('=Learn more').call(done)

Is there any way to do that?

**Comment by christian-bromann** [comment]
Hi @obsidianart ,
in WebdriverIO all commands are independent from each other. You could do

```js
browser.click('#beta-request-form=Learn more');
```

but as far as I can see I haven't published that selector yet as it is part of the `v2.5.0` release. In this case you have to go the more verbose way:

```js
browser.element('#beta-request-form', function(err, res) {
    browser.elementIdElement(res.value, '=Learn more', function(err, res) {
        browser.elementIdClick(res.value);
    });
});
```

**Comment by obsidianart** [comment]
that makes quite hard to have pageObjects...
Thank you for your answer.

**Comment by christian-bromann** [comment]
Let's put that on the `v3` milestone and see what we can do about that.

**Comment by christian-bromann** [comment]
Actually this will be straightforward to implement in our promise chaining system in `v3`, even such things as:

```
browser.element('#nested1').element('#nested2').click('=Learn more');
```

**Comment by christian-bromann** [comment]
@obsidianart this will land in `v3`. Check out the [test](https://github.com/webdriverio/webdriverio/commit/bd9a9aba6210c0f92059ab38302630807cfe3b12#diff-ab51083ff59d6ac72e5d5081f8c83644R1) for it. It works exactly how you assumed it.

**Comment by dandv** [comment]
Would be nice to have a page object pattern example. Right now the only search result for "pageObject" in this repo is this issue.
