### ISSUE TITLE
Unable to turn WebElement JSON object into Selector ($)

### ISSUE THREAD

**Issue by rembeckyb** [webdriverio/webdriverio#5190]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.0.9
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** Sync
 - **Node.js version:** 13.12.0
 - **NPM version:** 6.14.4
 - **Browser name and version:** Chrome 80
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used :**

```
"dependencies": {
  "rimraf": "^2.6.3",
  "webdriverio": "^6.0.9"
},
"devDependencies": {
  "@wdio/cli": "^6.0.9",
  "@wdio/local-runner": "^6.0.9",
  "@wdio/mocha-framework": "^6.0.8",
  "@wdio/sauce-service": "^6.0.8",
  "@wdio/spec-reporter": "^6.0.8",
  "@wdio/sync": "^6.0.8",
  "aws-sdk": "^2.501.0",
  "chai": "^4.2.0",
  "mocha": "^7.0.1"
}
```

**Config of WebdriverIO**

```
exports.config = {

    runner: 'local',

    user: process.env.SAUCE_USERNAME,
    key: process.env.SAUCE_ACCESS_KEY,

    region: 'us',

    suites: {
        Login: [
            './tests/login/validLogin.js',
        ],
    },

    maxInstances: 40,

    capabilities: [
        {platform: 'Windows 10', browserName: 'chrome', version: '80', screenResolution: '1280x960', build: 'WDIO', maxDuration: '3600'},
    ],

    logLevel: 'error',

    bail: 0,

    //Omitted
    baseUrl: '***',

    waitforTimeout: 20000,

    services: ['sauce'],

    framework: 'mocha',

    reporters: ['spec'],

    mochaOpts: {
        ui: 'bdd',
        timeout: 300000,
        bail: true
    },
};
```

**Describe the bug**

I am running my tests on SauceLabs exclusively.  Whenever I am expecting to interact with an active element by converting it to a selector, an error is thrown.

The code:

```
console.log(browser.getActiveElement());
console.log($(browser.getActiveElement()));
```

The error:
```
Error: selector needs to be typeof `string` or `function`
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at global.$ (/Users/Me/WDIO/webdriverio/node_modules/@wdio/runner/build/index.js:195:36)
    at Page.value (/Users/Me/WDIO/webdriverio/pages/login.page.js:408:42)
    at Context.<anonymous> (/Users/Me/WDIO/webdriverio/tests/login/validLogin.js:48:26)
```

This error is pointing to the line `console.log($(browser.getActiveElement()));`

In my log, the line `console.log(browser.getActiveElement());` is being printed as `{ ELEMENT: '0.18897515563500789-1' }` which is a WebElement JSON object.

**Expected behavior**

I expect `$(browser.getActiveElement());` to convert the WebElement JSON object into a WDIO Selector in order to pull values from the active element, such as text and HTML.

**Additional context**

Ultimately, I am trying to get the text and HTML of active elements.  I am expecting to accomplish this with the code `let text = $(browser.getActiveElement()).getText();` and `let html = $(browser.getActiveElement()).getHTML();` however this error is preventing me from accomplishing that.

**Comment by christian-bromann** [comment]
I am not able to reproduce this with latest WebdriverIO. Can you please provide a reproducible example?

**Comment by rembeckyb** [comment]
I've created a repo which demonstrates the behavior I'm experiencing.  It's been shared with you @christian-bromann and is called "WDIOSelectorTest".

Please let me know if anything else is needed on my end.  Thank you.

**Comment by christian-bromann** [comment]
> I've created a repo which demonstrates the behavior I'm experiencing

Where can I find this repository?

**Comment by rembeckyb** [comment]
I believe you can find the invitation in your e-mail, or by clicking here: https://github.com/rembeckyb/WDIOSelectorTest/invitations

**Comment by christian-bromann** [comment]
@rembeckyb please add `"sauce:options": {}` to your capabilities and it will resolve the issue. This is an internal bug in Sauce on which people already working on a fix. Cheers!
