### ISSUE TITLE
"binary" field of moz:firefoxOptions is ignored by devtools launcher

### ISSUE THREAD

**Issue by Writhe** [webdriverio/webdriverio#5197]
**Environment:**
 - **WebdriverIO version:** 6.0.5
 - **Mode:** WDIO Testrunner, sync
 - **Node.js version:** 12.11.1
 - **NPM version:** 6.4.1
 - **Browser name and version:** Firefox Nightly 76
 - **Platform name and version:** MacOS 10.14.1

**Config of WebdriverIO**
Pertinent part:
```
capabilities: [
  {
    maxInstances: 5,
    browserName: 'firefox',
    'moz:firefoxOptions': {
      binary: '/Applications/Firefox Nightly.app/Contents/MacOS/firefox-bin',
    }
  }
]
```

**What happens**
Launcher tries to fire up Firefox - the default executable, instead of Firefox Nightly, ignoring the `binary` field in `moz:firefoxOptions`. It's a problem, since devtools requires Nightly, and Nightly does not, by default, get installed where launcher expects regular Firefox. The runner times out trying to connect to the browser and gives up.

**To Reproduce**
- follow the [quickstart guide](https://webdriver.io/docs/gettingstarted.html) for WebdriverIO v6
- in `capabilities` section of the config, replace `browserName: 'chrome' ` with `browserName: 'firefox'` and add `'moz:firefoxOptions': { binary: [path-to-your-ff-nightly] }`.
- run it

Unless your Firefox Nightly happens to be installed in Firefox stable's default directory (or unless you're running Linux, where the launcher may search for it more actively, I don't know) - it'll fail. You'll note that the runner will log out that it tries to run the default, hardcoded executable for your platform instead of what you put in as `binary`.

**Expected behavior**
The launcher should respect the value of `binary` setting, if available.

**Log**
```
[0-0] 2020-04-01T21:23:56.221Z INFO devtools: Launch /Applications/Firefox.app/Contents/MacOS/firefox-bin with config: {"executablePath":"/Applications/Firefox.app/Contents/MacOS/firefox-bin","defaultViewport":{"width":1200,"height":900},"binary":"/Applications/Firefox Nightly.app/Contents/MacOS/firefox-bin","product":"firefox"}
[0-0] 2020-04-01T21:24:26.347Z ERROR @wdio/runner: TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r722234 is guaranteed to work.
```

**Comment by christian-bromann** [comment]
@Writhe are you up to providing a PR for this?

**Comment by Writhe** [comment]
@christian-bromann Almost ahead of you. Almost. ;)
