### ISSUE TITLE
Errors don't propagate through custom commands

### ISSUE THREAD

**Issue by bryan-coursera** [webdriverio/webdriverio#520]
When two custom commands are chained, an error in the first command doesn't propagate through the second command. I've been able to narrow it down to this test case (but unfortunately couldn't figure out a fix):
```
it('should propagate errors on custom commands', function() {

    this.client.addCommand('successfulCommand', function(param) {
        return param;
    });

    this.client.addCommand('failedCommand', function(param) {
        throw new Error('error from failed command');
    });

    return this.client
        .failedCommand()
        .successfulCommand()
        .then(function() {
            throw new Error('should not be in onResolve fn')
        }, function() {
            done()
        });
});
```

I believe that the error that the `failedCommand` throws should mean that the `successfulCommand` is skipped entirely, and the error should instead be returned to the `onRejected` part of the following `then`. Instead, the `successfulCommand` is actually executed, and whatever value / promise that command returns is propagated through.

**Comment by christian-bromann** [comment]
got it all working now :+1:
