### ISSUE TITLE
[Logs Provided] wdioV6: .moveTo() not working with [chromedriver] as a service

### ISSUE THREAD

**Issue by guptapranay** [webdriverio/webdriverio#5212]
Hi Team,
.moveTo() feature is not working if element is not visible in given view port size when used with service as ['chromedriver']. Erros out with message ```move target out of bounds```

But .moveTo() works when used with service as ['selenium-standalone']. In this case page scrolls down augtomatically to the location with help of locator.

**Comment by christian-bromann** [comment]
Can you please provide logs for both cases?

**Comment by guptapranay** [comment]
@christian-bromann 
Please find the attached log for
Error:  ['chromedriver']  - Error occurs at line number : 876
Success ['selenium-standalone']

[chromedriver_error.log](https://github.com/webdriverio/webdriverio/files/4438818/chromedriver_error.log)
[selenium-standaloe_success.log](https://github.com/webdriverio/webdriverio/files/4438820/selenium-standaloe_success.log)

**Comment by guptapranay** [comment]
Hi Team,
Any updates on this?

**Comment by christian-bromann** [comment]
@guptapranay this is likely to be a limitation of WebDriver as you are trying to interact with an element that is outside the viewport. Can you provide a reproducible example?

**Comment by guptapranay** [comment]
@christian-bromann 

I have attached a zip folder. 

Steps to reproduce:
1) npm i
2) npm i gulp (if needed)
3) gulp cucumber --ff site

If services: ['chromedriver'] - moves out of bound error
If services: ['selenium-standalone'] - Page auto scroll  and click the link.
[wdiov6.zip](https://github.com/webdriverio/webdriverio/files/4449600/wdiov6.zip)

**Comment by christian-bromann** [comment]
@guptapranay to set clear expectations: this is a WebDriver issue. While I am interested in providing a workaround in WebdriverIO for such cases it is definitely not the highest priority for me or other maintainer. This is an excellent chance to get involved and provide a contribution. Thanks!

**Comment by guptapranay** [comment]
@christian-bromann , Thanks so much for the clarification. Was having little doubt with respect to issue being webdriveio or chromedriver. 

Would be happy to explore and contribute in this. I will try to get involved and provide a contribution. 

Thanks so much for your time on this :)

**Comment by erwinheitzman** [comment]
I think a scrollIntoView before executing it when `isW3C` is true should be enough for a fix @guptapranay but this is from the top of my head so no guarantees :)

**Comment by christian-bromann** [comment]
Closing as I don't see much activity here. If anyone wants to get involved please let me know.
