### ISSUE TITLE
Getting started example not working

### ISSUE THREAD

**Issue by mrooftho** [webdriverio/webdriverio#5213]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**

- wdio test runner
- Packages
    "@wdio/cli": "^6.0.13",
    "@wdio/local-runner": "^6.0.13",
    "@wdio/mocha-framework": "^6.0.13",
    "@wdio/spec-reporter": "^6.0.12",
    "chromedriver": "^80.0.2",
    "wdio-chromedriver-service": "^6.0.1"

- Node / NPM
node --version
v13.10.1
npm --version
6.13.7

**Config of WebdriverIO**
An example of how you configured WebdriverIO config
- Local runner
- MOCHA
- Chromedriver service
- Chrome

**Describe the bug**
Followed step-by-step the getting started example (https://webdriver.io/docs/gettingstarted.html). When starting the test (like described) the chrome instance opens but afterwards nothing happens, tests do not run, no error message.

**To Reproduce**
Steps to reproduce the behavior: follow get started

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Log**
Following sdout, stops at the end.

npx wdio wdio.conf.js
Execution of 1 spec files started at 2020-04-05T19:57:22.836Z
2020-04-05T19:57:22.847Z INFO @wdio/cli:launcher: Run onPrepare hook
Starting ChromeDriver 80.0.3987.16 (320f6526c1632ad4f205ebce69b99a062ed78647-refs/branch-heads/3987@{
#185}) on port 9515
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious 
code.
2020-04-05T19:57:22.958Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2020-04-05T19:57:22.959Z INFO @wdio/local-runner: Start worker 0-0 with arg: wdio.conf.js
[0-0] 2020-04-05T19:57:23.285Z INFO @wdio/local-runner: Run worker command: run
2020-04-05T19:57:23.291Z INFO webdriverio: Initiate new session using the ./protocol-stub protocol
[0-0] RUNNING in chrome - /test/specs/basic.js
[0-0] 2020-04-05T19:57:23.380Z INFO webdriverio: Initiate new session using the webdriver protocol
[0-0] 2020-04-05T19:57:23.382Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2020-04-05T19:57:23.382Z INFO webdriver: DATA {
  capabilities: { alwaysMatch: { browserName: 'chrome' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'chrome' }
}

**Additional context**
Same problem (symptom) when running against selenium grid (local / docker). Attached source.
[WDIO.zip](https://github.com/webdriverio/webdriverio/files/4434678/WDIO.zip)

> Please use the correct markdown

**Comment by christian-bromann** [comment]
Thanks for writing up this issue report. After I installed the dependencies I ran:

```sh
$ npx wdio
```

And everything ran as expected. Make sure you have Chrome v80 installed as you are using Chromedriver in v80.

I will close this issue as it doesn't seem to be reproducible. Happy to assist further.

**Comment by adamjmcgrath** [comment]
FWIW I hit this issue using Node 13, using Node 12 fixed it for me
