### ISSUE TITLE
Cucumber framework has peerDependency of @wdio/cli@^5.0.0

### ISSUE THREAD

**Issue by colinrotherham** [webdriverio/webdriverio#5216]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.0.13
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 12.16.1
 - **NPM version:** 6.14.4
 - **Browser name and version:** Chrome 80
 - **Platform name and version:** macOS 10.15.4
 - **Additional wdio packages used (if applicable):** @wdio/cucumber-framework@6.0.13

**Describe the bug**
Looks like `@wdio/cucumber-framework@6.0.13` has been left on the old version of `@wdio/cli@^5.0.0`.

See old peerDependency here:  
https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-cucumber-framework/package.json#L44

**To Reproduce**
Install `@wdio/cucumber-framework@6.0.13`

```
npm WARN @wdio/cucumber-framework@6.0.13 requires a peer of @wdio/cli@^5.0.0 but none is installed. You must install peer dependencies yourself.
```

**Expected behavior**
Latest `@wdio/cucumber-framework@6.0.13` should be ready for `@wdio/cli@6.0.13`

Would you like me to open a pull request?

Thanks

**Comment by christian-bromann** [comment]
Added a quick fix by myself, thanks!
