### ISSUE TITLE
wdio v6: Inconsistency between webdriver and devtools in execute

### ISSUE THREAD

**Issue by amitzur** [webdriverio/webdriverio#5217]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 6.0.13]
 - **Mode:** Standalone
 - **Node.js version:** 12.13.1
 - **NPM version:** 6.12.1
 - **Browser name and version:** Chrome 80
 - **Platform name and version:** Ubuntu 18.04

**Config of WebdriverIO**
```
{
    capabilities: {
      browserName: 'chrome'
    }
}
```

**Describe the bug**
There's a difference between running with puppeteer and webdriver when evaluating scripts. When I run with devtools protocol I get an exception, and with webdriver it works fine.

**To Reproduce**
Run the following:
```
const {remote} = require('webdriverio')
;(async () => {
  const browser = await remote({capabilities: {browserName: 'chrome'}})
  const el = await browser.$('html')
  await browser.execute(`const x = 3; return 4`)
})()
```

**Expected behavior**
devtools should not throw an error in this case. I did notice that using plain puppeteer throws an exception in the following case:
```
const puppeteer = require('puppeteer');

(async function() {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.evaluate('return 4');
})();
```
But I think webdriver.io version 6 aims to be consistent between webdriver and puppeteer.

**Comment by christian-bromann** [comment]
@amitzur it fails because you are using a string as argument instead of a function. This way WebdriverIO has no chance to properly wrap your logic. I am not sure if we can fix this as we recommend ultimately to pass in a function, e.g.:

```js
    const el = await browser.$('html')
    await browser.execute(() => {
        const x = 3;
        return 4;
    })
```

**Comment by christian-bromann** [comment]
For more context: if the user provides a string we directly pass it through the protocol driver. This fails in Puppeteer but passes in WebDriver because Chromedriver wraps the provided script argument again.

**Comment by amitzur** [comment]
I was under the impression webdriverio does do something with the input, since passing `browser.execute('return 3')` doesn't fail in wdio v6 but **does** fail in puppeteer

**Comment by christian-bromann** [comment]
> I was under the impression webdriverio does do something with the input

You are right. WebdriverIO also transforms a script as a string into something that can be executed by WebDriver and Puppeteer.

> There's a difference between running with puppeteer and webdriver when evaluating scripts.

To clarify: WebdriverIO tries to provide the same behavior of a WebDriver command execution for Puppeteer. Therefor if you use Puppeteer directly you will experience Puppeteer behavior. However if you use the WebDriver/WebdriverIO APIs using Puppeteer as an automation protocol, the behavior should be the same as running with e.g. Geckodriver.

**Comment by amitzur** [comment]
Ok. Thanks for the clarification.
> WebdriverIO also transforms a script as a string into something that can be executed by WebDriver and Puppeteer.
Is it not `new Function(script)`? I believe doing that would fix this issue. Is it not the correct thing to do?

**Comment by christian-bromann** [comment]
If a script starts with `return` we do this: https://github.com/webdriverio/webdriverio/blob/master/packages/devtools/src/commands/executeScript.js#L14-L16
