### ISSUE TITLE
wdio v5.x: failures in the jasmine beforeAll hook do not stop spec executing 

### ISSUE THREAD

**Issue by mshykov** [webdriverio/webdriverio#5227]
**Environment:**
 - **WebdriverIO version:** [5.22.4]
 - **Mode:** [Standalone mode]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [10.19.0]
 - **NPM version:** [6.14.4]
 - **Browser name and version:** [Chrome 80.0.3987.163]
 - **Platform name and version:** [Mac OS X]
 - **Additional wdio packages used (if applicable):** 
```
 "devDependencies": {
    "@wdio/allure-reporter": "^5.22.4",
    "@wdio/cli": "^5.22.4",
    "@wdio/jasmine-framework": "^5.18.6",
    "@wdio/local-runner": "^5.22.4",
    "@wdio/selenium-standalone-service": "^5.16.10",
    "@wdio/spec-reporter": "^5.22.4",
    "@wdio/sync": "^5.18.7",
    "webdriverio": "5.22.4",
},
"dependencies": {
    "@wdio/browserstack-service": "^5.22.1",
},
```

**Config of WebdriverIO**
An example of how you configured WebdriverIO config
```javascript
exports.config = {
  bail: 0,
  framework: 'jasmine',
  jasmineNodeOpts: {
    defaultTimeoutInterval: 100000,
    stopSpecOnExpectationFailure: true,
    grep: null,
    invertGrep: null,
  },
};
```

**Describe the bug**
Failures in the jasmine `beforeAll` hook do not stop executing of `beforeEach`, `it` and `afterEach` hooks

**To Reproduce**
```javascript
describe('My test: describe', () => {
  beforeAll(() => {
    console.log('beforeAll');
    throw new Error('before all error');
  });
  beforeEach(() => {
    console.log('beforeEach');
  });
  it('My test: it #1', () => {
    console.log('My test: it #1');
  });
  it('My test: it #2', () => {
    console.log('My test: it #2');
  });
  afterEach(() => {
    console.log('afterEach');
  });
  afterAll(() => {
    console.log('afterAll');
  });
});
```

**Actual result**
The `beforeAll` is failed but all other hooks are executed and `spec` has been reported as passed

```
Execution of 1 spec files started at 2020-04-06T17:07:09.465Z

[0-0] RUNNING in chrome  - /my-test.js
[0-0] beforeAll
[0-0] Error in ""before all" hook"
before all error
[0-0] beforeEach
[0-0] My test: it #1
[0-0] afterEach
[0-0] beforeEach
[0-0] My test: it #2
[0-0] afterEach
[0-0] afterAll
[0-0] PASSED in chrome - /my-test.js

 "spec" Reporter:
------------------------------------------------------------------
[chrome 80.0.3987.163 Mac OS X #0-0] Running: chrome (v80.0.3987.163) on Mac OS X
[chrome 80.0.3987.163 Mac OS X #0-0] Session ID: 14544c3cbade7608a81bb23564cca017
[chrome 80.0.3987.163 Mac OS X #0-0]
[chrome 80.0.3987.163 Mac OS X #0-0] My test: describe
[chrome 80.0.3987.163 Mac OS X #0-0]    ✖ "before all" hook
[chrome 80.0.3987.163 Mac OS X #0-0]    ✓ My test: it #1
[chrome 80.0.3987.163 Mac OS X #0-0]    ✓ My test: it #2
[chrome 80.0.3987.163 Mac OS X #0-0]
[chrome 80.0.3987.163 Mac OS X #0-0] 2 passing (5.3s)
[chrome 80.0.3987.163 Mac OS X #0-0] 1 failing
[chrome 80.0.3987.163 Mac OS X #0-0]
[chrome 80.0.3987.163 Mac OS X #0-0] 1) My test: describe "before all" hook
[chrome 80.0.3987.163 Mac OS X #0-0] before all error

Spec Files:      1 passed, 1 total (100% completed) in 00:00:10 
```

**Expected behavior**
In case `beforeAll` failed the `beforeEach`,  `it`, and `afterEach` hooks should not be executed, but `beforeAll` should be

**Comment by christian-bromann** [comment]
This is a Jasmine specific behavior that is not influenced by WebdriverIO. It seems that they have introduced a `completeOnFirstError` options to make this configurable. See also: https://github.com/jasmine/jasmine/commit/585287b9d6e03dc546be7269e1ea569f4bd9ca0d

**Comment by christian-bromann** [comment]
Looks like setting `failFast: true` in your jasmineNodeOpts will do the trick. I am working on documenting this better.

**Comment by mshykov** [comment]
Thank you Christian!

The setting `failFast: true` help me, but still there are not ideal behavior:
1. `afterAll()` hook is not executed with this setting
2. With the same code to reproduce, it is not a clear output in the line: ` Error in "<unknown test>"`

```
[0-0] RUNNING in chrome - /my-test.js
[0-0] beforeAll
[0-0] Error in ""before all" hook"
before all error
[0-0] Error in "<unknown test>"
Error: before all error
[0-0] FAILED in chrome - /my-test.js
```

**Comment by christian-bromann** [comment]
> 1. `afterAll()` hook is not executed with this setting

This is Jasmines behavior. Feel free to raise an issue in the Jasmine project as this is not handled by WebdriverIO.

> 2\. With the same code to reproduce, it is not a clear output in the line: ` Error in "<unknown test>"`

We could technical fix that. Feel free to raise a new issue for it. Thanks!
