### ISSUE TITLE
@wdio/local-runner: Failed launching test session: TypeError: ReporterClass is not a constructor

### ISSUE THREAD

**Issue by PaliwalArpit** [webdriverio/webdriverio#5229]
**Environment (please complete the following information):**
 - **WebdriverIO version:**6.13.4
 - **Mode:** Standalone
 - **Node.js version:** 10.19.0
 - **NPM version:** 6.13.4
 - **Browser name and version:** Chrome 78
 - **Platform name and version:** Fedora

 - **Additional wdio packages used (if applicable):** 
```
"devDependencies": {
    "@wdio/allure-reporter": "^5.18.6",
    "@wdio/browserstack-service": "^5.18.7",
    "wdio-browserstack-reporter": "~0.1.1",
    "@wdio/cli": "^5.18.7",
    "@wdio/dot-reporter": "^5.18.6",
    "@wdio/local-runner": "^6.0.5",
    "@wdio/mocha-framework": "^5.18.7",
    "@wdio/selenium-standalone-service": "^5.16.10",
    "@wdio/spec-reporter": "^5.18.7",
    "@wdio/sync": "^5.18.7",
    "chai": "^3.5.0",
    "chromedriver": "^75.1.0",
    "mocha": "^6.2.2",
    "wdio-chromedriver-service": "^5.0.2",
    "wdio-docker-service": "^2.3.0",
    "protractor-browserstack-reporter": "~0.1.1"
  },

```
**Config of WebdriverIO**
```
exports.config = {
    runner: 'local',
    specs: [
      // specs files
    ],
    reporters: ['browserstack'],
    reporterOptions: {
        browserstack: {
            outputDir: './'
        }
    }, 
     services: ['browserstack'],
    user: '*******',
    key: '******',
    capabilities: [
        {
        'os': 'Windows',
        'os_version': '10',
        'browser': 'Chrome',
        'browser_version': '79',
        'acceptSslCerts': 'true',
        'browserstack.local': 'true',
        'browserstack.debug':'true',
        'browserstack.networkLogs':'true',
        'resolution' : '1920x1080'
      },
     {
        'os': 'Windows',
        'os_version': '10',
        'browser': 'Firefox',
        'browser_version': '70',
        'acceptSslCerts': 'true',
        'browserstack.local': 'true',
        'browserstack.debug':'true',
        'resolution' : '1920x1080'
      }
 ],
      maxInstances: 1,
      'browserstack.local':'true',
}

```
**Describe the bug**
Running test as per the script provided giving an error in wdio-local-runner. I have updated the version of the reporter as well to 6.0.0, still getting the same error while running the test. 

This seems to be a similar issue as:[https://github.com/sullenor/wdio-teamcity-reporter/issues/12]( https://github.com/sullenor/wdio-teamcity-reporter/issues/12)

**To Reproduce**
Add 'Browserstack reporter' in conf file and try running test.

**Expected behavior**
Should run test without error in Reporter class

**Log**
```
[0-3] 2020-04-07T05:01:21.189Z ERROR @wdio/local-runner: Failed launching test session: TypeError: ReporterClass is not a constructor
    at BaseReporter.initReporter (/home/apaliwal/Solution-engine-test/solution-engine-test-ui/node_modules/@wdio/runner/build/reporter.js:124:14)
    at Array.map (<anonymous>)
    at new BaseReporter (/home/apaliwal/Solution-engine-test/solution-engine-test-ui/node_modules/@wdio/runner/build/reporter.js:32:39)
    at Runner.run (/home/apaliwal/Solution-engine-test/solution-engine-test-ui/node_modules/@wdio/runner/build/index.js:77:21)
    at process.on.m (/home/apaliwal/Solution-engine-test/solution-engine-test-ui/node_modules/@wdio/local-runner/build/run.js:37:20)
    at process.emit (events.js:203:15)
    at process.EventEmitter.emit (domain.js:448:20)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by christian-bromann** [comment]
You are using the `wdio-browserstack-reporter` which is not compatible with v6 of WebdriverIO. Please raise an issue in the `wdio-browserstack-reporter` project. Thanks!

**Comment by breburdaTom** [comment]
Hi Christian, I am encountering the same error message when using cucumber reporter. I am using v7 WDIO.

**Comment by christian-bromann** [comment]
@breburdaTom not sure what to say about it. See [my comment](https://github.com/webdriverio/webdriverio/issues/5229#issuecomment-610218341) above.

**Comment by breburdaTom** [comment]
Sorry Christian, not that experienced SW developer as you are :) I was just stuck, first day of fiddling with wdio cli and it wasn't working when it should. Couldn't find answer anywhere after hours of googling. This was the closest trace similar to my issue.

I just did a clean install with less plugins. For the reporter I chose just **allure** and it started working just fine 👍 
Maybe I had 2 or 3 reporter plugins that were not happy fighting with each other.
Thx for this wonderful project!

**Comment by fatihtx** [comment]
I agreed with @breburdaTom . This is the first time that I am installing WebdriverIO and selected several reporting plugins. Getting  an error at your first try is not good. I will clena my area and re-start the installation. At least there should be a warning sample test case not working with so and so.

**Comment by christian-bromann** [comment]
@fatihtx which reporter did throw this error?

**Comment by fatihtx** [comment]
I selected at config window: spec, allure, cucumber

**Comment by christian-bromann** [comment]
Thanks for letting me know, I will kick out the Cucumber reporter as it is not supported.
