### ISSUE TITLE
(multi remote) Ability to pass different information to different remotes

### ISSUE THREAD

**Issue by plessbd** [webdriverio/webdriverio#523]
Not sure if I just dont know how to do it or if it does not exist, but I would like to be able to pass different information to the different remotes.

For instance if I want to test some sort of a chat app with multiple browsers, I would like to be able to login with two different users

for instances

on browserA I would like to login an John on browserB I would like to login with Jane

How would this be accomplished?

**Comment by plessbd** [comment]
Nevermind, it helps if I look more carefully at the different examples.  sorry for the fail.

**Comment by christian-bromann** [comment]
No worries! Please note that I haven't and won't publish `v2.5.0` as it is unstable and not really ready for production. If you still want to use and play around with it feel free to use the master branch.

**Comment by plessbd** [comment]
I have been.  So far it is working wonderfully.  We have been using it for testing between firefox, chrome and an iOS simulator.  I feel it is very stable and working well.
