### ISSUE TITLE
Unable to use the 'ignoreZoomSetting' capability

### ISSUE THREAD

**Issue by j320** [webdriverio/webdriverio#5231]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.22.4
 - **Mode:** Standalone
 - **Browser name and version:** IE11
 - **Platform name and version:** Windows 7/8/10

**Config of WebdriverIO**
```
capabilities: [{
    browserName: 'internet explorer',
    ignoreZoomSetting:true
  }
],
```

**Describe the bug**
When running tests on IE, I'm getting the issue:

> Unexpected error launching Internet Explorer. Browser zoom level was set to 125%. It should be set to 100% 

On selenium the way to fix this is to set the `ignoreZoomSetting:true` capability, however, when attempting this in different ways (with double quotes, without them) I always get the following error:

> Request failed due to Illegal key values seen in w3c capabilities: [ignoreZoomSetting]

What can it be done for this? I'm running IE on the CI so I can't manually set the zoom level to a 100%.

**Comment by christian-bromann** [comment]
> ignoreZoomSetting:true

Please use proper vendor capabilities: `"ie:ignoreZoomSetting": true`.

Join our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have further questions.

**Comment by j320** [comment]
With that capability I'm getting:

`Unable to match capability set 0: ie:ignoreZoomSetting is an unknown extension capability for IE`

**Comment by christian-bromann** [comment]
> With that capability I'm getting:

Please check the IEDriver docs which capabilities are supported and what the vendor prefix is.

**Comment by j320** [comment]
This fixed it for me:

```
capabilities: [
  {
    browserName: 'internet explorer',
    "se:ieOptions": {
      ignoreZoomSetting: true
    }
  }
],
```
