### ISSUE TITLE
Removed field test.passed removed in afterTest hook

### ISSUE THREAD

**Issue by joshgrantsauce** [webdriverio/webdriverio#5232]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.0.8
 - **Mode:** WDIO test runner
- **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.14.1
 - **NPM version:** 6.13.4
 - **Browser name and version:** multiple
 - **Platform name and version:** multiple
 - **Additional wdio packages used (if applicable):** @wdio/sauce-service

**Config of WebdriverIO**
Configuration is a standard config for running tests against Sauce Labs.

**Describe the bug**
In WDIO 5.x, this `afterTest` hook had a field under the `test` parameter of `test.passed` which returned whether the test passed or failed. In WDIO, 6.x the `test.passed` field appears to be removed.

**To Reproduce**
Steps to reproduce the behaviour:

- Use WDIO 6.0.8
- Execute tests on Sauce Labs with @wdio/sauce-service added
- In the `wdio.conf.js` file, add the following `afterTest` hook:

```javascript
afterTest: function(test) {
    if (test.passed === false){
        console.log("TEST FAILED");
    }
}
```

- Execute tests

**Expected behaviour**
In the console logging of the executed tests, there should be a line with "TEST FAILED". The actual behaviour does not include this logging.

**Log**
The `test` object does appear in the `afterTest` hook with the following fields:

```
test: Test {
      title: 'basic',
      fn: [Function],
      body: 'function (...specFnArgs) {\n' +
        "    return _testFnWrapper.testFnWrapper.call(this, 'Test', {\n" +
        '      specFn,\n' +
        '      specFnArgs: (0, _utils.filterSpecArgs)(specFnArgs)\n' +
        '    }, {\n' +
        '      beforeFn,\n' +
        '      beforeFnArgs\n' +
        '    }, {\n' +
        '      afterFn,\n' +
        '      afterFnArgs\n' +
        '    }, cid, repeatTest);\n' +
        '  }',
      async: 0,
      sync: true,
      _timeout: 60000,
      _slow: 75,
      _enableTimeouts: true,
      timedOut: false,
      _retries: -1,
      _currentRetry: 0,
      pending: false,
      type: 'test',
      file: '/Users/me/Document/my-wdio-project/tests/basic.js',
      parent: [Suite],
      ctx: [Circular],
      _events: [Object: null prototype],
      _eventsCount: 1,
      callback: [Function: done],
      timer: Timeout {
        _idleTimeout: 60000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 28625,
        _onTimeout: [Function],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: true,
        [Symbol(asyncId)]: 59,
        [Symbol(triggerId)]: 58
      }
    },
    wdioRetries: 0
```

**Comment by christian-bromann** [comment]
@joshgrantsauce the parameter has changed as described in our release blog post:

> Modified Hook Signature: we modified the signature of our before/after test/hook hooks to allow you to access the frameworks native event objects - please have a look into the config file documentation and update your hooks accordingly

See the new structure: https://github.com/webdriverio/webdriverio/blob/master/examples/wdio.conf.js#L271
