### ISSUE TITLE
Improve documentation for v3 release

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#524]
this includes:

- [x] what has changed from v2 to v3
- [x] how transfer promises works (chai-as-promise example)
- [x] selector chaining
- [x] runner documentation
- [x] showcase example how to use yield in test specs
- ~~page object pattern with WebdriverIO~~
- [x] `addCommand` now without callback
- [x] multiremote
- [x] see #426 
- tbd

**Comment by Zolmeister** [comment]
Excited to see v3 so close to release! :+1:

**Comment by christian-bromann** [comment]
@Zolmeister we are done with our work on the new core but currently implementing a whole new runner cli with own reporter and config interface. So still quite a way to go but will get released soon I hope.

**Comment by christian-bromann** [comment]
Gonna skip page object pattern as it requires extra functionality in WebdriverIO, will create a new issue to make this work for `v3.1`

**Comment by christian-bromann** [comment]
Done! Let's :shipit:

**Comment by Zolmeister** [comment]
:tada:

**Comment by miguelrivera** [comment]
@christian-bromann Did you guy get the Page Object Pattern working?

**Comment by christian-bromann** [comment]
@miguelrivera see #356
