### ISSUE TITLE
UNMET PEER DEPENDENCY @wdio/cli@6.0.15

### ISSUE THREAD

**Issue by pmerwin** [webdriverio/webdriverio#5242]
"@wdio/config": "6.0.12",
    "@wdio/logger": "6.0.12",
    "@wdio/utils": "6.0.13",

in wdio/cli these are locked on a version, is the what we want?  I belive this is causing us issues installing on AWS Linux lambda env... ?  shouldn;t these use ^ ?

**Comment by christian-bromann** [comment]
> is the what we want?

Yes. `@wdio/cli` is tested with exactly these versions. Ensure that if you update WebdriverIO packages, always update all of them.
