### ISSUE TITLE
@wdio/appium-service not starting appium or related appium-* services 

### ISSUE THREAD

**Issue by mel-OR** [webdriverio/webdriverio#5243]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.0.13
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync 
 - **Node.js version:**12.8.1
 - **NPM version:** 6.10.2
 - **Browser name and version:** n/a mobile iOS and Android
 - **Platform name and version:** Mac OS 10.15.3, Xcode 11.4
 - **Additional wdio packages used (if applicable):** All up-to-date at run time: 
    "@wdio/appium-service": "^6.0.15",
    "@wdio/cli": "^6.0.13",
    "@wdio/jasmine-framework": "^6.0.13",
    "@wdio/local-runner": "^6.0.13",
    "@wdio/spec-reporter": "^6.0.12",
    "@wdio/sync": "^6.0.12",
     "appium": "^1.15.1",

**Config of WebdriverIO**
```
hostname: 'localhost',
  path: '/wd/hub',
  services: ['appium'],
  appium: {
    args: {
      logTimestamp: true,
    },
    logPath: 'test-results/appium.log',
  },
  runner: 'local',
  port: 4723,
framework: 'jasmine',
  jasmineNodeOpts: {
    defaultTimeoutInterval: 500000,
  },
  maxInstances: 4,
  sync: true,
  deprecationWarnings: true,
  bail: 0,
  baseUrl: 'http://localhost:3000',
  waitforTimeout: 60000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  reporters: [
    'spec',
    [
      'allure',
      {
        outputDir: './test-results/allure-results',
        disableWebdriverStepsReporting: true,
      },
    ],
  ],
  specs: ['e2e/specs/*.ts'],
  capabilities: [
    {
      platformName: 'iOS',
      platformVersion: '13.1',
      deviceName: 'iPhone X',
      app: appPathIOS,
      automationName: 'XCUITest',
    },
    // {
    //   platformName: 'Android',
    //   platformVersion: '10.0',
    //   deviceName: 'Android Emulator',
    //   app: appPathAndroid,
    //   appWaitDuration: '50000',
    //   appActivity: 'MainActivity',
    // },
  ],
  logLevel: 'trace',
};

```

**Describe the bug**
Appium and all of its related services do not get spawned using @wdio/appium-service.

**To Reproduce**
Invoking wdio ./e2e/wdio.conf.js on MacOS 10.15.3
with the packages listed above.
No Appium.log is created and my tests fail since the appium service isn't running.

**Expected behavior**
Appium-service spawns appium and related services before any test commands are run.

**Log**
Logs are not produced because Appium is not spawned.
If I start Appium manually, this is the output from my test command:
```
[Appium] Welcome to Appium v1.17.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /session
[HTTP] {"capabilities":{"alwaysMatch":{"platformName":"iOS","platformVersion":"13.1","deviceName":"iPhone X","app":"/Users/mp/Code/bumped-app/ios/build/BumpedApp/Build/Products/Debug-iphonesimulator/BumpedApp.app","automationName":"XCUITest"},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"iOS","platformVersion":"13.1","deviceName":"iPhone X","app":"/Users/mp/Code/bumped-app/ios/build/BumpedApp/Build/Products/Debug-iphonesimulator/BumpedApp.app","automationName":"XCUITest"}}
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- POST /session 404 10 ms - 50 
```

**Additional context**
Downgrading only @wdio/appium-service to 5.18.2 works for Android, but there are additional issues for iOS around building XCode projects for RoutingHTTPServer and YYCache (probably related to Xcode 11.4 and a bug for Appium) so that is not a workaround I can use.

**Comment by christian-bromann** [comment]
@mel-OR you are applying Appium configs in your wdio config wrong. In v6 this has changed, please see the docs: https://webdriver.io/docs/appium-service.html#args
