### ISSUE TITLE
Allure Report causes failed expect assertion to not close test nor browser

### ISSUE THREAD

**Issue by Kriskof** [webdriverio/webdriverio#5247]
Running latest WDIO v6 and installed Allure Report as described through the webdriver.io site.

**Describe the bug**
Test does not exit nor close browser if your expect assertion fails.

**To Reproduce**
```
const assert = require('assert')

describe('webdriver.io page', () => {
    it('should have the right title', () => {
        browser.url('https://webdriver.io')
        const title = browser.getTitle()

        // expect this to fail
        const $button = $('//div[contains(text(),"login test")]') 
        expect($button).toBeDisplayed()
        //

        assert.strictEqual(title, 'WebdriverIO · Next-gen browser automation test framework for Node.js')
    })
})

```

**Expected behavior**
close browser and generate results for report

Sorry if I posted in wrong section, not quite sure if I report this on WDIO or Allure Report.

**Comment by tawfiknouri** [comment]
i'm not sure but it seem allure.endCase function does not support this kind of message
may be not able to handel utf-16

it's ok when i test with faked object 
{ "message":data, "stack":"allure error .............", "type":"Error"}

{
   "message":"Expect $(`//div[contains(text(),\"login test\")]`) to be displayed\n\nExpected: \u001b[32m\"displayed\"\u001b[39m\nReceived: \u001b[31m\"\u001b[7mnot \u001b[27mdisplayed\"\u001b[39m",
   "stack":"Error: Expect $(`//div[contains(text(),\"login test\")]`) to be displayed\n\nExpected: \u001b[32m\"displayed\"\u001b[39m\nReceived: \u001b[31m\"\u001b[7mnot \u001b[27mdisplayed\"\u001b[39m\n    at Context.<anonymous> (C:\\bugs_webdriverio\\bug_allure_5247\\test\\bug.allure.spec.js:17:25)\n    at Context.executeSync (C:\\bugs_webdriverio\\bug_allure_5247\\node_modules\\@wdio\\sync\\build\\index.js:56:18)\n    at C:\\bugs_webdriverio\\bug_allure_5247\\node_modules\\@wdio\\sync\\build\\index.js:82:70",
   "type":"Error"
}

this object is returned by  getErrorFromFailedTest  (@wdio\allure-reporter\utils.js)

@christian-bromann

**Comment by tawfiknouri** [comment]
@Kriskof you need to install  expect-webdriverio 
without this line "expect($button).toBeDisplayed()" is not right 

try adding expect-webdriverio and retry again It should work
npm install expect-webdriverio

@christian-bromann we need to update https://webdriver.io/docs/api/expect.html for mocha users

**Comment by christian-bromann** [comment]
@tawfiknouri in v6 this package is a dependency of the runner so no need to install in v6

**Comment by tawfiknouri** [comment]
@christian-bromann thanks !
And should add this in wdio.conf.js ?

beforeSession () { 
    require('expect-webdriverio')
}

my tests

wdio v5.16.11 without install expect-webdriverio with  "require('expect-webdriverio')" : OK
wdio v5.16.11 without install expect-webdriverio  without  "require('expect-webdriverio')" : KO

***********************************************************
wdio v6 without install expect-webdriverio with "require('expect-webdriverio')" : OK
wdio v6 without install expect-webdriverio without "require('expect-webdriverio')" : KO

**Comment by christian-bromann** [comment]
> wdio v6 without install expect-webdriverio + without "require('expect-webdriverio')" : KO

There is no need to manually require it, this already happens as shown in this Mocha example. https://github.com/webdriverio/webdriverio/blob/master/examples/wdio/mocha/mocha.test.js

**Comment by Kriskof** [comment]
So is this an actual issue that's gonna get fixed? Or is this only for allure report team?

**Comment by christian-bromann** [comment]
Feel free to propose a PR with a fix @Kriskof

**Comment by Kriskof** [comment]
for anybody stumbling across this and wondering, looks like they implemented a fix but I haven't tested it out yet.

https://github.com/webdriverio/webdriverio/pull/5283

**Comment by christian-bromann** [comment]
I tried to reproduce this and all browser sessions close for me properly. This seems to be resolved for me. Happy to re-open if anyone could provide a reproducible example Thanks!

**Comment by Kriskof** [comment]
> I tried to reproduce this and all browser sessions close for me properly. This seems to be resolved for me. Happy to re-open if anyone could provide a reproducible example Thanks!

It was working before but now it doesn't after latest update if I do parallel testing.

**Comment by mgrybyk** [comment]
Please provide with reproducible example, it works properly for me in the latest version
