### ISSUE TITLE
Navigation Timeout when using automation protocol: devtools

### ISSUE THREAD

**Issue by jacekbj** [webdriverio/webdriverio#5248]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.0.14
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.13.1
 - **NPM version:** 6.12.1
 - **Browser name and version:** Chrome 80.0.3987.163
 - **Platform name and version:** Mac (and Docker)
 - **Additional wdio packages used (if applicable):** 

- @wdio/devtools-service
- @wdio/selenium-standalone-service
- @wdio/sync
- chromedriver
- devtools
- selenium-standalone

**Describe the bug**
WDIO tests fail with Navigation Timeout when run with `automationProtocol: 'devtools'` and page loads a lot of assets.

**To Reproduce**
I created a repository to show this problem: https://github.com/jacekbj/ad-tests-docker-demo (branch: master).
Tests setup:

- 6 tests; each loads the same page 3 times,
- maxInstances: 5,
- devtools service enabled.

Run the code below to see the problem.

When tests are run with the automation protocol webdriver and Selenium they pass (I used selenium-standalone-service).
```
npm run wdio -- wdio-webdriver.conf.js
```

When run with automation protocol devtools, they fail with navigation timeout. 
```
npm run wdio -- wdio-devtools.conf.js
```

**Expected behavior**
Tests do not fail when using automation protocol devtools.

**Additional context**
I came across this problem when running tests in Docker with automation protocol devtools. I initally blamed the devtools automation protocol + devtools service but it's not the case.

I can provide more context if the repo is not enough.

**Comment by christian-bromann** [comment]
Thanks for writing this thorough issue. I checked out your demo repository and running 6 Chrome instances just freezes the Chrome browser at some point. Running 6 independent browser sessions can put heavy memory and CPU load on the host machine and might cause timeouts.

Can you point out where exactly what the issue in WebdriverIO is here? Running tests using devtools is not the same as running tests with WebDriver and cumber the CPU and memory of ones machine differently.

**Comment by jacekbj** [comment]
There is no other error printed than `Navigation Timeout`. I did not measure it but it definitely took more than 300000ms (5 mins). 

I'm running the same code on Jenkins with headless  Chrome in Docker (automation protocol devtools) and using Selenium.
Using devtools I am getting a quite a few `stale element reference: The element with reference ELEMENT-17 is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed` errors. Oftentimes it breaks in `element.scrollIntoView` method. I've thoroughly inspected these tests with an experienced colleague (QA) and we can't see any spot where it might fail. What is more, these tests are very reliable when run in separation. Are there any known issues regarding `element.scrollIntoView` and devtools protocol?

How is webdriver protocol vs devtools protocol different when it comes to the required resources?

**Comment by christian-bromann** [comment]
> How is webdriver protocol vs devtools protocol different when it comes to the required resources?

With WebDriver the browser is started by an external driver e.g. Chromedriver and handled by that. With DevTools we start the browser as part of the work process and communicate with the browser directly. Not sure if this has performance implications.

I will close this as I can't really identify if this is an error is WebdriverIO. Running many browser on the local machine has performance implications. Why they might be different between running tests on WebDriver or DevTools is different story.
