### ISSUE TITLE
Click with phantomjs

### ISSUE THREAD

**Issue by mike-suggitt** [webdriverio/webdriverio#525]
I'm sure this is a classic but I've noticed that when using PhantomJS (and GhostDriver) with WebdriverIO there is no click event propagation happening. For example if I have a link inside an `<li>` element. Clicking the `<li>` does nothing, clicking the link does.

Also needs to be mentioned that when I run the same test in chrome it does propagate.

Thoughts?

**Comment by christian-bromann** [comment]
Have you tried PhantomJS v2.0? This is an issue for PhantomJS. I am not sure if ariya/phantomjs#10375 is related to that. Is there a reason why you want to click on the `li` instead of the link itself?

**Comment by mike-suggitt** [comment]
I haven't as last time I tried 2.0 it was incredibly buggy. Could maybe give it another go. The reason I'm looking to do what I'm doing is because it's a series of tabs (`<li>`) with links inside to redirect to seperate pages. I can obviously change the implementation to use events or change the HTML but wouldn't be my first choice (if i had any!)

**Comment by christian-bromann** [comment]
And why do you can't click on the link in your test?

**Comment by mike-suggitt** [comment]
Sorry, I can if needs be but due to styling, and the fact we're supposedly representing a real user it's just not perfect. I raised this to see if I was actually correct in thinking this was buggy behaviour and not just something I was missing. If it's verified as a bug then I can change it to target to link

**Comment by christian-bromann** [comment]
It is a bug for sure, you're right. Since it is working in Chrome I don't see anything I can do here. It is probably related to the way how PhantomJS/GhostDriver simulates the click. I bet there are plenty of other similar issues in which PhantomJS acts differently then Chrome or other WebKit browser. What do you think?

**Comment by mike-suggitt** [comment]
I would say that event propagation is quite a big thing in web development and often links are wrapped by some other content which makes targetting them slightly brittle IMO. That all being said I've seen a few things online about "clicks" with selenium and people having to implement their own so it's not neccessarily a quick fix. I'm currently having a quick look at executing client script to do it so i can keep you posted. Did you say that this isn't an issue in PhantomJS 2.0?

**Comment by christian-bromann** [comment]
> i can keep you posted

Yes please! Thanks!

> Did you say that this isn't an issue in PhantomJS 2.0?

PhantomJS got almost completely rewritten with v2. So there are chances that it handles event propagation better then before. It's worth a try. Let me know if it works out.

> often links are wrapped by some other content which makes targetting them slightly brittle IMO.

Do you have an example? I am sure you can always query links no matter where it is located in the DOM using Seleniums different selector strategies.

**Comment by mike-suggitt** [comment]
> Do you have an example? I am sure you can always query links no matter where it is located in the DOM using Seleniums different selector strategies.

Sorry I wasn't being clear. Yes absolutely we can target links and if we do it all works fine. However, we use attribute handles within our code to logically split, seperate, and drill into various sections of the page. This allows us to apply semantic labels on things and do things like "and i click on 'first-thing-in-a-table' etc. I was only meaning it would be nicer for us NOT to have to change that too much but obviously we can :)

**Comment by christian-bromann** [comment]
Querying elements will be a lot easier in `v3` using selector chaining, e.g.:

```js
client.element('ul.myList').element('li:first-child').click('=some Link');
```

What do you think we should do about this issue?

**Comment by mike-suggitt** [comment]
Ah chaining would be a nice touch. Will it be more or less performant that creating longer CSS selectors?

> What do you think we should do about this issue?
I'm not sure TBH as it sounds like it's more an issue with PhantomJS than it is WebDriverIO. I'm pretty sure though that I didn't have such issues on a previous project using Protractor with CucumberJS. I know Protractor does a lot of extra work on top so its possible they might do something around this as well. I'd have to check.

**Comment by christian-bromann** [comment]
> Ah chaining would be a nice touch.

We introduced that with `v3`

> Will it be more or less performant than creating longer CSS selectors?

Yes, each element call is an extra request to the selenium server (though you won't recognise the difference)

I am always looking forward to ensure that all Selenium driver behave the same way. I don't think I can do something here. I think it will be fixed with PhantomJS `v2`. Closing
