### ISSUE TITLE
Browserstack Plugin not counting certain unsuccessful tests as failures

### ISSUE THREAD

**Issue by esaari** [webdriverio/webdriverio#5256]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [6.0.15]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync]
 - **Node.js version:** [12.16.1]
 - **NPM version:** [6.13.4]
 - **Browser name and version:** [Chrome 80]
 - **Platform name and version:** [OS X Catalina]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
Browserstack may occasionally return a `timeout` test status in addition to `passed` and `failed`. For Cucumber JS, these types of test failures haven't been recognized as failures in the `afterScenario()` hook. 

**To Reproduce**
Force any test to somehow timeout or not establish connection with Browserstack - here's API output from an example test.  I'll have a PR up shortly.

`curl -u "xxxx:yyyy" https://api.browserstack.com/automate/sessions/<my_session_id>.json
{"automation_session":{"name":"","duration":375,"os":"Windows","os_version":"10","browser_version":"80.0","browser":"chrome","device":null,"status":"timeout", ... }`

**Comment by esaari** [comment]
https://github.com/webdriverio/webdriverio/pull/5259

**Comment by christian-bromann** [comment]
PR with a fix got merged. Closing.
