### ISSUE TITLE
Screener.io session creation not working with vs 6

### ISSUE THREAD

**Issue by pmerwin** [webdriverio/webdriverio#5257]
fyi : screener is not working with WDIO vs 6:

these options use to work, and do work in vs 5:

this.hostname = 'hub.screener.io';
this.port = 443;
this.protocol = 'https';

vs 5 creates this:
https://hub.screener.io:443/wd/hub/session
vs 6 does this:
https://hub.screener.io/session

and this returns a 404 and session is not created ^

any ideas on how to make this work in vs 6?

"WebDriver Default Path: we changed default WebDriver path to from /wd/hub to / as most of the browser drivers now default to this, this should have now affect for you - however if you have trouble connecting to a WebDriver endpoint after the upgrade, this could be a reason for that issue."

How to set config for screener to work now?

**Comment by wswebcreation** [comment]
Hi @pmerwin 

This has to do with the fact that in V6 the default path changed from `/wd/hub` to `/`, if you add that to your Screener config it will work. also check https://webdriver.io/blog/#other-changes

Going to close it for now, but it's still open for discussion

**Comment by pmerwin** [comment]
changing that does not work, thus I opened this ticket.  It has to be changed in launcher I believe

**Comment by wswebcreation** [comment]
@pmerwin 

Can you share your config?

**Comment by pmerwin** [comment]
I got it!

this.path = '/wd/hub';

have to add that path param to config.  Thanks!!!

**Comment by wswebcreation** [comment]
You're welcome!
