### ISSUE TITLE
@wdio/selenium-standalone-service ignores selenium server parameters

### ISSUE THREAD

**Issue by NBukuri** [webdriverio/webdriverio#5264]
I was trying to use selenium server that is running remotely.

**Environment:**

- **Mode:** WDIO Testrunner
- **running sync** 
- **Node.js version:** 12.16.1
- **NPM version:** 6.13.4
-    "@wdio/cli": "^6.0.13",
-    "@wdio/local-runner": "^6.0.13",
-   "@wdio/mocha-framework": "^6.0.13",
-   "@wdio/selenium-standalone-service": "^6.0.15",
-   "@wdio/spec-reporter": "^6.0.12",
-   "@wdio/sync": "^6.0.12"

**Config of WebdriverIO**
exports.config = {
  //
  // ====================
  // Runner Configuration
  // ====================
  //
  // WebdriverIO allows it to run your tests in arbitrary locations (e.g. locally or
  // on a remote machine).
  runner: "local",
  // =====================
  // Selenium Server Configurations
  // =====================
  hostname: "IP_OF_REMOTE_SELENIUM_SERVER",
  port: 4444,
  path: "/wd/hub",
...

**Describe the bug**

when I run my tester **hostname specified in wdio.conf.js is ignored** and testrunner uses local selenium server anyway:
![image](https://user-images.githubusercontent.com/16242794/79240627-1668bd80-7e83-11ea-836c-8180457b6fc7.png)

The only way to use the remote selenium server is to uninstall `@wdio/selenium-standalone-service`.

After removing`@wdio/selenium-standalone-service`  I run the tester and it uses remote selenium server. 
Tests are passed as they are expected. But  ERRORs appear in logs:

![image](https://user-images.githubusercontent.com/16242794/79243243-6c8b3000-7e86-11ea-889a-72d503079f42.png)

**To Reproduce**

- set up wdio test runner with selenium-standalone-service 
- set up remote instance where selenium server will be running (for example I am using selenium server in docker container using `selenium/standalone-chrome:latest` image
- modify selenium server configuration in wdio.conf.js
- change hostname with IP of remote selenium server
- set the logLevel:trace in wdio.conf.js
- run test with `npx wdio`
- in output you will see the request url to selenium server

**Expected behavior**

- when `hostname `is modified in `wdio.conf.js`  tester should send requests to:
   remote selenium server (if remote IP address is assigned) 
   or 
   local selenium server ( if localhost is specified)

- [IF PREVIOUS ONE IS NOT ISSUE] If I uninstalled `@wdio/selenium-standalone-service` and use remote selenium server Errors should not occur.

**Comment by ronhorm** [comment]
I'm having  a similar issue when I use the chromedriver service.   it used to be ignored when selenium server params were defined.  no longer the case.   I removed it and now only load it conditionally in something like this.   
```
if (process.env.DEV) {
    config.services = ['chromedriver'];

**Comment by christian-bromann** [comment]
The driver services modify the connection parameter if not specified differently - therefor if you are about to use a remote driver on e.g. a different server don't use the service. If you have capabilities that run on a remote server and some that run local you can specify this as follows:

```js
exports.config = {
  // ...
  services: ['selenium-standalone'],
  capabilities: [{
    browserName: 'chrome' // runs on local selenium standalone server started by service
  }, {
    browserName: 'firefox',
    hostname: '196.1.2.3', // runs on a remote server
    port: 4445
  }]
  // ...
```

Please let me know if you have any more questions.

**Comment by NBukuri** [comment]
I modified capabilities as shown:
```
  capabilities: [
    {
      maxInstances: 1,
      browserName: "chrome",
      hostname: "3.12.3.12", // remote selenium server
      port: 4444,
      "goog:chromeOptions": {
        args: ["headless", "disable-gpu", "--enable-precise-memory-info"],
      },
    },
  ],
```
Request url is correct:
![image](https://user-images.githubusercontent.com/16242794/79321597-aa3a9800-7f1c-11ea-9854-35469afba453.png)


but getting the following error:
```
[0-0] (node:5184) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:45185
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
[0-0] (node:5184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5184) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Tried also discarding selenium server configuration:
```

  // =====================
  // Selenium Server Configurations
  // =====================
  // hostname: "localhost",
  // port: 4444,
  // path: "/wd/hub",
```
 
Getting the same error only for remote selenium.
