### ISSUE TITLE
Capabilities are not binded to the browser

### ISSUE THREAD

**Issue by luiscspinho** [webdriverio/webdriverio#5265]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.0.16
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** v12.8.0
 - **NPM version:** v6.10.2
 - **Browser name and version:** Chrome 80
 - **Platform name and version:** macOS Mojave

**Config of WebdriverIO**
```
{
  runner: "local",
  maxInstances: 1,
  capabilities: [
    {
      browserName: "chrome",
      proxy: {
        proxyType: "manual",
        httpProxy: "ProxyHTTP",
        sslProxy: "proxySSL."
      },

      "goog:chromeOptions": {
        args: [
          "--disable-web-security"
        ],
        mobileEmulation: {
          deviceName: "iPhone 6"
        }
      }
    }
  ]
```
**Describe the bug**
The `capabilities` object is not binded to the browser instance. Once a wdio.conf is launched with this `capabilities`, just print the browser instance in any hook to see this happening.

**To Reproduce**
- Have a `capabilities` object on your wdio.conf
- In any test, print the `browser` instance. Evertything in the wdio.conf will be there, but the `capabilities` (inside the conf object) is not

**Expected behavior**
The browser instance has the capabilities object, so I can access my previously configured proxy.

P.S. I'm migrating from version 5.18.0, where this behaviour is working as intended. Might be related to https://github.com/webdriverio/webdriverio/pull/4930 ?

**Comment by luiscspinho** [comment]
From a quick debug, I got here: https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/index.js#L25

`options` has the correct capabilities when we get here, but when executing `client = remoteModifier(client, options)` it seems that the client loses the information about
```{
      browserName: "chrome",
      proxy: {
        proxyType: "manual",
        httpProxy: "ProxyHTTP",
        sslProxy: "proxySSL."
      },

      "goog:chromeOptions": {
        args: [
          "--disable-web-security"
        ],
        mobileEmulation: {
          deviceName: "iPhone 6"
        }
      }
   ```
as per my example.

**Comment by christian-bromann** [comment]
@luiscspinho note that `browser.capabilities` represents the capabilities the driver reports back when requesting a WebDriver session. It is a known issue that Chromedriver doesn't send back it's `goog:chromeOptions`. You can access what you have send by using `browser.options.requestedCapabilities`.

**Comment by luiscspinho** [comment]
@christian-bromann thanks a lot. Sorry for reporting this as a bug, but the behaviour indeed changed which lead me to false assumptions. Thanks for the clarification 👍

**Comment by christian-bromann** [comment]
> but the behaviour indeed changed which lead me to false assumptions.

Yeah it did and we didn't communicated that because I thought that Chromedriver would return these configs. Happy that provided solution works!
