### ISSUE TITLE
Attach chromium protocol commands to msedge sessions

### ISSUE THREAD

**Issue by ronhorm** [webdriverio/webdriverio#5266]
**Environment:**
 - **WebdriverIO version:** 6.0.15
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 13.1.0
 - **NPM version:** 6.14.4
 - **Browser name and version:** msedge 81.0.416.53
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** N/A

**Config of WebdriverIO**
N/A

**Describe the bug**
Unable to use the Chromium Protocol commands in Edge v81.   
Returning:
[msedge  windows #0-19] browser.setNetworkConditions is not a function
[msedge  windows #0-19] TypeError: browser.setNetworkConditions is not a function

**To Reproduce**

browser.url(loginEndpoint);
browser.debug();
//try any of the chromium protocol commands listed in https://webdriver.io/docs/api/chromium.html

**Expected behavior**
command is found and executed

**Log**

**Additional context**
I noticed when testing against Edge v80 the chromium commands worked.   Not sure why wdio thinks Edge v80 is chrome and not Edge v81. 

> Please use the correct markdown

**Comment by ronhorm** [comment]
modify isChrome in envDetector.js to something like maybe?

`function isChrome(caps) {
  if (!caps) {
    return false;
  }
    return Boolean(caps.chrome || caps.msedge) || Boolean(caps['goog:chromeOptions']);
}`

**Comment by ronhorm** [comment]
Also it probably would read a little more clearer if isChrome was renamed isChromium

**Comment by christian-bromann** [comment]
I wonder how much Edge and Chrome differ these days anymore. Does Edgedriver support all these commands described in https://webdriver.io/docs/api/chromium.html ?

**Comment by ronhorm** [comment]
I believe so

**Comment by christian-bromann** [comment]
> I believe so

Can you check?

**Comment by ronhorm** [comment]
Tested them out today.  The answer is yes.  Submitted PR with fix

**Comment by christian-bromann** [comment]
Let's continue convo in #5272
