### ISSUE TITLE
404 on config documentation link on blog

### ISSUE THREAD

**Issue by pmerwin** [webdriverio/webdriverio#5267]
**Pre-check**
- [ X] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [X ] Missing documentation
- [ ] Other

**Description of the improvement / report**
A clear and concise description.

open blog and click the documentation link:

https://webdriver.io/blog/ConfigurationFile.md = 404

<img width="830" alt="Screen Shot 2020-04-14 at 5 08 15 PM" src="https://user-images.githubusercontent.com/26633165/79279086-db5e8e00-7e72-11ea-8bd9-bd12afd1e2f4.png">

**Comment by christian-bromann** [comment]
Thanks for reporting!
