### ISSUE TITLE
Possible to run from browser?

### ISSUE THREAD

**Issue by jongbeau** [webdriverio/webdriverio#527]
I know webdriverio was built to be run server side with node. Has anyone had success executing inside a browser? My use case would be having a local standalone selenium server running, but be able to run the browser automation from inside a web app.

**Comment by christian-bromann** [comment]
Sorry but I need to ask: why do you want to do this?

**Comment by christian-bromann** [comment]
To answer your question: I tried to browserify WebdriverIO and ran into some problems. I think it is possible with a bunch of workarounds but didn't spend much time on it since I don't see why somebody could need this. Please note that you won't be able to automate the browser in which you would run webdriverio because you can't initialise a Selenium session on a running browser instance.

**Comment by jongbeau** [comment]
I want to have some partially automated tasks/tests that a non technical operator can easily kick off. For example, from a management web interface, click a button which initiates webdriver to launch a new web browser instance and automatically login and click a few things. The operator would then do a couple things manually in the new browser instance to complete the task. I would obviously have to install and run the selenium server on each operator's computer.

**Comment by christian-bromann** [comment]
Ahh I see. I would propose instead of running WebdriverIO in the browser just write a little server that starts WebdriverIO for you. If you click on a button a request gets send to the server (maybe with couple configurations) and kicks off the test for you.

**Comment by jongbeau** [comment]
That's sort of a last resort as it would be a much higher management burden. The operators would have to pull code frequently, the versions would have to match between web interface and the node server, different operators may not be in sync, code secrets would have to be managed, etc..

I love the webdriverio API, but if anyone knows of another webdriver binding that can run directly in a browser, it would be much appreciated!

**Comment by christian-bromann** [comment]
The code could be in a central repository and you can pull it whenever the server gets a request. You can actually pass the desired version number in the request and checkout exact git version using the [git package](https://www.npmjs.com/package/git).

I will close this issue as it is currently not possible to run WebdriverIO in the browser. I also wouldn't recommend to do so.
