### ISSUE TITLE
IE doesn't clear session when reloading

### ISSUE THREAD

**Issue by j320** [webdriverio/webdriverio#5270]
**Environment (please complete the following information):**
 - **WebdriverIO version:**  6.0.16 | Also reproduced in v5
 - **Mode:** Standalone
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.16.1
 - **Browser name and version:** IE11

**Config of WebdriverIO**
```
capabilities: [{
    browserName: 'internet explorer',
    "se:ieOptions": {
      ignoreZoomSetting: true,
      nativeEvents: false
    }
  }
]
```
**To Reproduce**

Run a test that requires you to, for example, log in into an account somewhere and then either run the test again or execute more than one test with the login one

Attempts of using: `browser.reloadSession()`, `browser.deleteCookie(),` `browser.deleteAllCookies()`, `browser.clearLocalStorage()` were made at the `before` or `after` hooks with no success. 

**Expected behavior**
The browser starts a fresh session every time.

**Actual behaviour**
The browser saves the data from the previous session

**Additional context**
`"ie.ensureCleanSession": true` capability fixes the issue, however it does take a few seconds to complete (can vary every time) and start the tests which slows down the overall run when executed in parallel with other browsers, especially the bigger the framework is. Sometimes IE is several tests behind Chrome and Firefox.

**Comment by christian-bromann** [comment]
> `"ie.ensureCleanSession": true` capability fixes the issue, however it does take a few seconds to complete (can vary every time) and start the tests which slows down the overall run when executed in parallel with other browsers, especially the bigger the framework is. Sometimes IE is several tests behind Chrome and Firefox.

This is a limitation of IE and can't be fixed in WebdriverIO. There is no way WebdriverIO can clean the session or make IE run faster.
