### ISSUE TITLE
Webdriver package doesn't use proxy provided

### ISSUE THREAD

**Issue by Stetchy** [webdriverio/webdriverio#5276]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2] 6.0.12
 - **Mode:** [Standalone mode or WDIO Testrunner] WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async] sync
 - **Node.js version:** [e.g. 8.11.2] 12.13.0
 - **NPM version:** [e.g. 5.8.0] 6.12.0
 - **Browser name and version:** [e.g. Chrome 68] Chrome 80, Firefox 75
 - **Platform name and version:** [e.g. Windows 10] macOS High Sierra, Windows 10, RHEL
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service] N/A

**Config of WebdriverIO**
An example of how you configured WebdriverIO config
```js
var browserstack = require("browserstack-local");

const commonCapabilities = {
  "browserstack.local": true,
  "browserstack.networkLogs": true,
  "browserstack.console": true,
  build: "WebDriverIO",
  acceptSslCerts: true,
  proxy: {
    proxyType: "manual",
    httpProxy: "<corporate proxy>",
    sslProxy: "<corporate proxy>",
    noProxy:
      "<corp no proxy>"
  }
};

exports.config = {
  specs: ["wdio/features/*.feature"],

  user: process.env.BROWSERSTACK_USERNAME,
  key: process.env.BROWSERSTACK_PASSWORD,

  exclude: [],

  maxInstances: 2,

  capabilities: [
    {
      browserName: "chrome",
      ...commonCapabilities
    },
    {
      browserName: "firefox",
      ...commonCapabilities
    },
    {
      browserName: "safari",
      ...commonCapabilities
    },
    {
      browserName: "edge",
      ...commonCapabilities
    },
    {
      browserName: "IE",
      ...commonCapabilities
    }
  ],

  logLevel: "debug",
  outputDir: "./logs",

  bail: 0,

  baseUrl: "http://localhost:3000/",

  waitforTimeout: 60000,

  connectionRetryTimeout: 90000,

  connectionRetryCount: 3,

  framework: "cucumber",

  reporters: ["spec"],

  cucumberOpts: {
    requireModule: ["@babel/register"],
    require: ["wdio/steps/scenario/*.js"],
    failFast: true
  },

  onPrepare: function(config, capabilities) {
    console.log("Connecting local");
    return new Promise(function(resolve, reject) {
      exports.bs_local = new browserstack.Local();
      exports.bs_local.start(
        {
          key: exports.config.key,
          onlyAutomate: true,
          forceLocal: true,
          verbose: true,
          proxyHost: "<corporate-proxy>",
          proxyPort: "80"
        },
        function(error) {
          if (error) return reject(error);
          console.log("Connected. Now testing...");

          resolve();
        }
      );
    });
  },

  // Code to stop browserstack local after end of test
  onComplete: function(capabilties, specs) {
    exports.bs_local.stop(function() {});
  },

  beforeSession: function(config, capabilities, specs) {
    require("expect-webdriverio").setOptions({ wait: 30000 });
  },

  before: function(capabilities, specs) {
    global.baseUrl = this.baseUrl.toString();
  }
};

```

**Describe the bug**

When connecting using a corporate proxy, the webdriver package doesn't use any proxy settings set, either by environment variables such as HTTP_PROXY, HTTPS_PROXY, NO_PROXY etc or proxy settings configured in capabilities. It does this because the webdriver package uses [got](https://github.com/sindresorhus/got) which [doesn't support proxies](https://github.com/sindresorhus/got/issues/79) unless it is done like [this](https://github.com/sindresorhus/got#proxies).

Browserstack will connect fine as it goes through the proxy, but when a session is being created, it will timeout as the webdriver package isn't connecting through the proxy, as explained above.

This behaviour does not change whether you use browserstack-local directly, or the @wdio/browserstack-service package.

**To Reproduce**

As I haven't used any other external services similar to browserstack I cannot say for definite that the behaviour is the exact same, but I am 99% sure it will do the same.

To reproduce this, you only need to be 1. behind a proxy, and 2. using a basic browserstack setup, either with the wdio package, or the browserstack-local package as above.

**Expected behavior**

I expect that the session to browserstack would be created, and the tests will be run,  the same as when working without a corporate proxy.

**Log**
If applicable, add logs to help explain your problem.
[Logs](https://gist.github.com/Stetchy/3a6713973e22436397330418c0f6efbc) 

**Additional context**
The current workaround for this is to follow [this](https://github.com/sindresorhus/got#proxies) and install [global agent](https://github.com/gajus/global-agent), then at the top of your config put
```js
require("global-agent/bootstrap");
```
and then use the environment variables `GLOBAL_AGENT_HTTP_PROXY` and `GLOBAL_AGENT_NO_PROXY` when running your wdio tests.

Suggested fix is to pass a proxy when defined to the agent object, as described in the got docs.
The proxy would be passed in [here](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriver/src/request.js#L20)

**Comment by christian-bromann** [comment]
Couple of notes:

- `expect-webdriverio` is already embedded and doesn't need to be explicitly setup anymore
- you start BS local manually which can be done automatically through the @wdio/browserstack-service

The `proxy` docs are indeed outdated. Can you propose an update?

**Comment by Stetchy** [comment]
@christian-bromann thanks for the tips - was using the BS service, but when I was debugging I tried the manual way just in case it was that service that was causing it.

The current proxy docs for passing the `proxy: {}` object, is that object being passed to the capabilities so that selenium/other runners pick it up, or where does it actually get picked up? It's hard to know from the docs. The same with the HTTP_PROXY environment variables - what package uses these?

For now, I would suggest adding a section on the `global-agent` package I spoke about above, suggesting to use it if you are behind a corporate proxy, as (correct me if I'm wrong) the HTTP_PROXY environment variables won't affect anything, due to the use of the `got` npm package.

I'll create a PR for proposed docs, if you'd like and we can then review it.

As the above is really just a workaround, in the future, it might be good to have native support for this - I can create a feature request and subsequent PR for that if you think it's within the scope for the project.

**Comment by christian-bromann** [comment]
> or where does it actually get picked up?

`proxy` is a WebDriver [capability](https://w3c.github.io/webdriver/#proxy).

> The same with the HTTP_PROXY environment variables - what package uses these?

This used to be picked up by `request` which now does't work anymore since we have replaced it with `got`.

> I'll create a PR for proposed docs, if you'd like and we can then review it.

Awesome!

> As the above is really just a workaround, in the future, it might be good to have native support for this - I can create a feature request and subsequent PR for that if you think it's within the scope for the project.

Please send a feature request with your ideas in mind.

**Comment by Stetchy** [comment]
Cool, will do the above, thanks for the info!

**Comment by Stetchy** [comment]
@christian-bromann I'm going to close this in favour of sticking with #5287 instead of a new feature, reading back over it I think it makes more sense to stick with the docs for now. Reopen if you think otherwise.
