### ISSUE TITLE
webdriverio.with.jasmine.spec.js; describe is not defined

### ISSUE THREAD

**Issue by SerkanSipahi** [webdriverio/webdriverio#528]
1.) Did you tested your jasmine example? How can i get jasmine methods( describe, it, except, etc.. ) globally? I get always an error "describe is not defined".

2.) What is the right to use this example? `node test.js` or `jasmine-node test.js` or with karma-runner?

```js
webdriverio = require('webdriverio');
jasmine = require('jasmine');

describe('my webdriverio tests', function() {

    var client = {};
    jasmine.DEFAULT_TIMEOUT_INTERVAL = 9999999;

    beforeEach(function() {
        client = webdriverio.remote({ desiredCapabilities: {browserName: 'phantomjs'} });
        client.init();
    });

    it('test it', function(done) {
        client
            .url('https://github.com/')
            .getElementSize('.header-logo-wordmark', function(err, result) {
                expect(err).toBeFalsy();
                expect(result.height).toBe(26);
                expect(result.width).toBe(37);
            })
            .getTitle(function(err, title) {
                expect(err).toBeFalsy();
                expect(title).toBe('GitHub · Build software better, together.');
            })
            .getCssProperty('a[href="/plans"]', 'color', function(err, color){
                expect(err).toBeFalsy();
                expect(color).toBe('rgba(65,131,196,1)');
            })
            .call(done);
    });

    afterEach(function(done) {
        client.end(done);
    });
});
```

**Comment by SerkanSipahi** [comment]
@christian-bromann thanks for doc improvement :) My question, do you any idea how to get globally describe, beforeEach, etc?

**Comment by christian-bromann** [comment]
I didn't get a chance to look into it but I am sure that you need [yasmine](https://www.npmjs.com/package/jasmine) globally installed on your system and then run something like `$ jasmine jasmine.test.js`. `describe` should be available then.

**Comment by SerkanSipahi** [comment]
@christian-bromann thank you it works :)

**Comment by SerkanSipahi** [comment]
@christian-bromann "suggestion for improvement for documentation"

If you does not pass the function argument all `Webdriverio instance` methods(e.g.: click, waitFor, getText, etc) in combination with `jasmine` the test breaks off completely and does not run further to e.g afterEach, or to next it. You get a fatal error !! I hope you unterstand what i mean.

```js
it('Test', function(done){
    //e.g click
   client.click('.some-selector', function(err, result){});
});
```

**Comment by christian-bromann** [comment]
@SerkanSipahi good point, thanks for pointing it out. I will check if this is also the case in `v3`.
