### ISSUE TITLE
WebdriverIO stopped working for firefox since version 6

### ISSUE THREAD

**Issue by edi9999** [webdriverio/webdriverio#5284]
This bug started after upgrading from webdriver IO 5 to webdriver IO 6.

On webdriverIO 5 I had no issues at all.
With webdriverIO 6 the Chrome tests are still working, but the firefox test do not seem to work at all.

 - **WebdriverIO version:**  6.0.16
 - **Mode:** Standalone
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 12.16.1
 - **NPM version:** 6.14.4
 - **Browser name and version:** Firefox 75
 - **Platform name and version:** Ubuntu 18
 - **Additional wdio packages used (if applicable):** N/A

**Config of WebdriverIO**

```
const webdriverio = require("webdriverio");
options = { capabilities : { browserName: "firefox",
		"moz:firefoxOptions": {
			args: ["-headless"],
		}};
const client = await webdriverio.remote(options);
```

**Describe the bug**

The firefox instance is not started, or cannot be reached. Here is the stack trace that shows up : 

```
2020-04-17T14:54:33.332Z INFO webdriverio: Initiate new session using the devtools protocol
2020-04-17T14:54:33.387Z INFO devtools: Launch /usr/bin/firefox with config: {"product":"firefox","executablePath":"/usr/bin/firefox","defaultViewport":{"width":1200,"height":900},"args":["-headless"]}
(node:26661) UnhandledPromiseRejectionWarning: TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r722234 is guaranteed to work.
    at Timeout.onTimeout (/media/edgar/11782abc-7f16-4830-8414-6dd6bdaf1dd4/edgar/projects/dx/xt/node_modules/puppeteer-core/lib/Launcher.js:761:14)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:26661) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:26661) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The message `Only Chrome at revision r722234 is guaranteed to work.` seems quite odd because I'm using firefox, not chrome...

**To Reproduce**

I've added an example here : 

```
git clone https://github.com/open-xml-templating/docxtemplater.git
cd docxtemplater
git checkout webdriver-io-update
npm install
npm run preversion
```

The npm run preversion script will run all tests, and at the end, run the firefox/chrome tests.

**Expected behavior**

The test should continue working after upgrading to webdriver IO 6

**Comment by christian-bromann** [comment]
> The test should continue working after upgrading to webdriver IO 6

This assumption is true if it wouldn't be a major version change. In v6 we automatically spin up the browser using Puppeteer if no browser driver is provided. So your example doesn't work because running Firefox on Puppeteer requires to run it on FirefoxDev. It is likely to work with Chrome. Please see all changes here: https://webdriver.io/blog/2020/03/26/webdriverio-v6-released.html

Closing as there is no obvious error.

**Comment by edi9999** [comment]
It would be cool to have an explicit error message say that the error comes from an "unsupported" firefox version.

I don't want to run the tests on firefox dev, I would like to test on firefox stable.

Can you explain how I can provide a browser driver that is other than puppeteer ?

**Comment by christian-bromann** [comment]
> Can you explain how I can provide a browser driver that is other than puppeteer ?

Simplest is to change your capabilities as follows:
```js
options = {
  automationProtocol: 'webdriver',
  capabilities : {
    browserName: "firefox",
	"moz:firefoxOptions": {
	  args: ["-headless"],
    }
  }
};
```
But note: this will likely fail too because it only defaulted to Puppeteer because no driver was found. So you have to start Geckodriver to run tests using WebDriver and Firefox.

**Comment by edi9999** [comment]
From what I understand this is an autodetection : 

```
WebdriverIO checks if a browser driver is running and accessible at localhost:4444/ and uses Puppeteer as fallback if not. If you use the WebdriverIO API the experience using WebDriver vs Puppeteer should be the same, running commands on Puppeteer might even be a little faster.
```

It seems that I have a webdriver server running on port 4444 : 

```
$ netstat -tnlp | grep --color=always -E 4444
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp6       0      0 :::4444                 :::*                    LISTEN      17622/java
```

With this sample code : 

```
git clone https://github.com/open-xml-templating/docxtemplater.git
cd docxtemplater
git checkout webdriver-io-update
npm install
npm run preversion
```

The preversion script will call a bash script of mine called webdriver.bash (readable here : https://github.com/open-xml-templating/docxtemplater/blob/webdriver-io-update/webdriver.bash), which starts a selenium-webdriver.

**Comment by edi9999** [comment]
When using the `automationProtocol: 'webdriver'` option, I now get the following

```
2020-04-17T15:33:44.765Z INFO webdriverio: Initiate new session using the webdriver protocol
2020-04-17T15:33:44.766Z INFO webdriver: [POST] http://localhost:4444/session
2020-04-17T15:33:44.767Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'firefox', 'moz:firefoxOptions': [Object] },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'firefox', 'moz:firefoxOptions': { headless: true } }
}
2020-04-17T15:33:44.796Z WARN webdriver: Request failed with status 404 due to <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" type="text/css" href="/assets/displayhelpservlet.css" media="all"/>
  <link href="/assets/favicon.ico" rel="icon" type="image/x-icon" />
  <script src="/assets/jquery-3.1.1.min.js" type="text/javascript"></script>
  <script src="/assets/displayhelpservlet.js" type="text/javascript"></script>
  <script type="text/javascript">
    var json = Object.freeze('{"consoleLink": "\u002fwd\u002fhub","type": "Standalone","class": "org.openqa.grid.web.servlet.DisplayHelpHandler$DisplayHelpServletConfig","version": "3.141.5"}');
  </script>
</head>
<body>

<div id="content">
  <div id="help-heading">
    <h1><span id="logo"></span></h1>
    <h2>Selenium <span class="se-type"></span>&nbsp;v.<span class="se-version"></span></h2>
  </div>

  <div id="content-body">
    <p>
      Whoops! The URL specified routes to this help page.
    </p>
    <p>
      For more information about Selenium <span class="se-type"></span> please see the
      <a class="se-docs">docs</a> and/or visit the <a class="se-wiki">wiki</a>.
      <span id="console-item">
        Or perhaps you are looking for the Selenium <span class="se-type"></span> <a class="se-console">console</a>.
      </span>
    </p>
    <p>
      Happy Testing!
    </p>
  </div>

  <div>
    <footer id="help-footer">
      Selenium is made possible through the efforts of our open source community, contributions from
      these <a href="https://github.com/SeleniumHQ/selenium/blob/master/AUTHORS">people</a>, and our
      <a href="http://www.seleniumhq.org/sponsors/">sponsors</a>.
   </footer>
  </div>
 </div>

</body>
</html>
2020-04-17T15:33:44.796Z INFO webdriver: Retrying 1/3
```

**Comment by christian-bromann** [comment]
@edi9999 to fix your issue you need to set `path: "/"`.

**Comment by christian-bromann** [comment]
I recommend to use the wdio testrunner, this would make your setup much cleaner as you wouldn't need custom scripts to start selenium standalone etc. The reason why devtools has been chosen was because selenium-standalone by default is started on an custom path `/wd/hub/` which was mentioned in the blog post:

> WebDriver Default Path: we changed default WebDriver path to from /wd/hub to / as most of the browser drivers now default to this, this should have now affect for you - however if you have trouble connecting to a WebDriver endpoint after the upgrade, this could be a reason for that issue.\

**Comment by edi9999** [comment]
I changed to this : 

```
+   path: "/wd/hub/",
+   automationProtocol: "webdriver",
```

and it now works.
