### ISSUE TITLE
TypeError: expect(...).toBeDisplayed is not a function - when using wdio v6 with Jasmine 

### ISSUE THREAD

**Issue by apkatsikas** [webdriverio/webdriverio#5285]
**Environment:**
 - **WebdriverIO version:** 6.0.4 or higher
 - **Mode:**  WDIO Testrunner sync
 - **Node.js version:** 10.16.0 or 12
 - **NPM version:** 6.9.0
 - **Browser name and version:** Chrome 81
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** v6 jasmine boilerplate project

**Config of WebdriverIO**
[jasmine-boilerplate.zip](https://github.com/webdriverio/webdriverio/files/4494466/jasmine-boilerplate.zip)

**Describe the bug**
Trying to use new wdio v6 assert lib functions fail with `TypeError: expect(...).toBeDisplayed is not a function`

**To Reproduce**
`npm run test`

**Expected behavior**
Ability to use new assertions.

**Comment by christian-bromann** [comment]
This was fixed with the last release.

**Comment by apkatsikas** [comment]
thanks @christian-bromann !
