### ISSUE TITLE
create-react-app with typescript causes syntax errors when using webdriverio with typescript

### ISSUE THREAD

**Issue by Stetchy** [webdriverio/webdriverio#5288]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2] 6.0.18
 - **Mode:** [Standalone mode or WDIO Testrunner] WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async] sync
 - **Node.js version:** [e.g. 8.11.2] 12.16.1
 - **NPM version:** [e.g. 5.8.0] 6.14.4
 - **Browser name and version:** [e.g. Chrome 68] Any browser, example uses Chrome
 - **Platform name and version:** [e.g. Windows 10] Windows 10, macOS High Sierra
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service] chromedriver

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

[wdio.conf.js](https://gist.github.com/Stetchy/33ec98d0ef9d24c9b88ef513f3a12c1c)

**Describe the bug**

ES6 syntax causes errors when pairing create-react-app with TypeScript, and WebdriverIO with TypeScript.

**To Reproduce**

1. `yarn create react-app test --template typescript`
2. Follow docs instructions for setting up WebDriverIO
3. Follow docs instructions for setting up TypeScript with WebDriverIO
4. Run `wdio wdio.conf.js`

Example repo:
https://github.com/Stetchy/webdriverio-react-typescript

**Expected behavior**
The tests should compile without errors and run similar to when using JavaScript with babel.

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

[wdio.log](https://gist.github.com/Stetchy/a2c73e6cb8df306438dfd41dda017dfe)

**Additional context**

> Please use the correct markdown

**Comment by tawfiknouri** [comment]
@Stetchy You have this error because you use **"module": "esnext"**  in tsconfig.json
You can

1. Create a new typescript config file for wdio ( tsconfig.wdio.json)
2. Update tsconfig.wdio.json and replace **"module": "esnext"** with **"module": "CommonJS"**
3. Use **env TS_NODE_PROJECT=tsconfig.wdio.json npx wdio** to run wdio test

**Comment by Stetchy** [comment]
Thanks @tawfiknouri! Is it possible to get this added into the docs? I can submit a PR if you think they fit in here.

**Comment by tawfiknouri** [comment]
Hi @Stetchy 
This is one use case, and absolutely there are several other cases.
I'm not sure if we can cover all possible cases ...

**Comment by Stetchy** [comment]
That's a fair point! This issue will be here for anyone who encounters the same problem anyway. Thanks @tawfiknouri!
