### ISSUE TITLE
Sauce Labs tunnel-identifier

### ISSUE THREAD

**Issue by KidkArolis** [webdriverio/webdriverio#529]
I need to use Sauce Connect when connecting to Sauce Labs so that I could connect to a local server started by my tests. But if I provide the `tunnel-identifier` option I get the following error:

```
Problem: Tunnel identifier provided: 'my-tunnel-123', didn't match any running tunnel for your account. Please remove or specify a different tunnel-identifier
For more info, please check https://docs.saucelabs.com/reference/sauce-connect/#managing-multiple-tunnels
```

I can't find any docs/examples on how to use this from webdriverio. I know that karma-sauce-launcher works out of the box.

My webdriverio options are

```js
{
    host: 'ondemand.saucelabs.com',
    port: 80,
    user: process.env.SAUCE_USERNAME,
    key: process.env.SAUCE_ACCESS_KEY,
    desiredCapabilities: {
      browserName: 'chrome',
      version: '27',
      platform: 'XP',
      name: 'My project',
      'tunnel-identifier': 'my-tunnel-123'
    }
  }
```

**Comment by christian-bromann** [comment]
Your capabilities are looking good. Have you tried using the shared tunnel flag?

```sh
$ sc -u USERNAME -k ACCESS_KEY --shared-tunnel
```

**Comment by KidkArolis** [comment]
I think I just didn't realize that webdriverio itself doesn't create the
tunnel. I didn't know that's what karma-sauce-launcher does behind the
scenes. I'm now trying to use sauce-connect-launcher to get that going.

**Comment by christian-bromann** [comment]
@KidkArolis right. WebdriverIO doesn't create a tunnel for you. But tools like `sauce-connect-launcher` are easy to configure with WebdriverIO. Closing.
