### ISSUE TITLE
Add support in wdio-allure-reporter to display flaky tests

### ISSUE THREAD

**Issue by damonpam** [webdriverio/webdriverio#5295]
**Is your feature request related to a problem? Please describe.**
I'm trying to filter some scenarios depending on their flakiness but I can't make it work.... every time I press the filter nothing is displayed. Is that already implemented but I'm using it incorrectly?

**Describe the solution you'd like**
Add `@flaky` tags in order to mark scenarios/features as flaky.
![image](https://user-images.githubusercontent.com/12949398/79754511-f8cea480-8317-11ea-92ef-5fbebe46d159.png)

**Additional context**
![image](https://user-images.githubusercontent.com/12949398/79753982-19e2c580-8317-11ea-802f-487e9c79db02.png)

Pages where flaky filter can be used:
![image](https://user-images.githubusercontent.com/12949398/79753608-7e515500-8316-11ea-8f05-f94b0002be2b.png)

![image](https://user-images.githubusercontent.com/12949398/79753737-b48ed480-8316-11ea-8212-d6738abb1571.png)

**Comment by BorisOsipov** [comment]
Hi! We have rewritten the reporter to the new allure-js version. Please try version 8.5.0 of wdio-allure-reporter and provide more details if the issue still persists. Feel free to create a new issue with actual details if it reproduces.
