### ISSUE TITLE
Explicit wait timeout not respected during element lookup on real devices

### ISSUE THREAD

**Issue by esaari** [webdriverio/webdriverio#5307]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [6.0.17]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [12.16.1]
 - **NPM version:** [latest]
 - **Browser name and version:** [mobiel Safari/Android Chrome]
 - **Additional wdio packages used (if applicable):** [@wdio/browserstack-service]

**Config of WebdriverIO**
```exports.config = {

    maxInstances: argv.nodes || parseInt(TEST_NODES) || 1,
    sync: true,
    coloredLogs: true,
    deprecationWarnings: false,
    baseUrl,
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    logLevel: LOG_LEVEL || 'debug',
    //
    // Set specific log levels per logger
    // loggers:
    // - webdriver, webdriverio
    // - @wdio/applitools-service, @wdio/browserstack-service, @wdio/devtools-service, @wdio/sauce-service
    // - @wdio/mocha-framework, @wdio/jasmine-framework
    // - @wdio/local-runner, @wdio/lambda-runner
    // - @wdio/sumologic-reporter
    // - @wdio/cli, @wdio/config, @wdio/sync, @wdio/utils
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    // logLevels: {
    //     webdriver: 'info',
    //     '@wdio/applitools-service': 'info'
    // },
    waitforTimeout: 10000,
    //
    // Default timeout in milliseconds for request
    // if Selenium Grid doesn't send response
    connectionRetryTimeout: 60000,
    //
    // Default request retries count
    connectionRetryCount: 1,
    reporters,
    services,
    specs: filterFeaturesByTags(tags, global.cucumberFeatures),
    framework: 'cucumber',
    cucumberOpts: {
        tagExpression: tags,
        require: ['./src/step_definitions/**/*.js'],
        backtrace: true,
        compiler: ['js:babel-core/register'],
        dryRun: false,
        failFast: false,
        failAmbiguousDefinitions: true,
        format: ['pretty'],
        colors: true,
        snippets: true,
        source: true,
        profile: [],
        strict: false,
        timeout: 180000,
        ignoreUndefinedDefinitions: false
    }
};
```

**Describe the bug**
On real devices, the `waitFor` timeout does not appear to be respected. 
From what I've observed, `$('#element').waitForDisplayed({ timeout: 10000 )}` is failing immediately when the webdriver protocol `findElement` is fired, rather than continually polling throughout the duration. 

Caveats: 
 - Android simulators on local runs seem to intermittently run into the issue
-  I'm having difficulty running local iOS simulator tests with wdio v6 and the very latest MacOS, so I can't verify/repro on local simulators
- The "real devices" I've been testing are the ones available from my cloud provider (browserstack)
**To Reproduce**
Run any kind of element lookup on a real device: 

```        const selector = `#${this.id} div.jw-skippable`;
        $(selector).waitForExist({ timeout: 10000, timeoutMsg: `Expected ${selector} to be displayed` });
        return $(selector);```

[Include code or an example repository that can easily be set up]

**Expected behavior**
Continually polls for 10 seconds until element is displayed.

**Log**
ios and Android Appium logs (from Browserstack cloud service) are attached 

**Additional context**
Android Chrome is running the latest Appium 1.17; iOS is running Appium 1.16 during these executions in `w3c/webdriver` mode. 
[browserstack-android-chrome.txt](https://github.com/webdriverio/webdriverio/files/4511599/browserstack-android-chrome.txt)
[browserstack-ios.txt](https://github.com/webdriverio/webdriverio/files/4511600/browserstack-ios.txt)

> Please use the correct markdown

**Comment by christian-bromann** [comment]
@esaari this seems like something that should be reproducible independently from the capability. Can you try to create a minimal reproducible example with e.g. Chrome?

**Comment by esaari** [comment]
@christian-bromann Will try to have this for you asap - though it should be fairily easily reproducible by doing an element lookup on any non-existent element while in a webview context.

**Comment by christian-bromann** [comment]
Please provide a reproducible example in a web browser if possible.

**Comment by esaari** [comment]
Adding a log from a Chrome desktop run - it seems that after the initial `findElement`lookup, it never enters the `findElements` loop which continually polls until element is found.

**Comment by esaari** [comment]
[desktop-chrome.txt](https://github.com/webdriverio/webdriverio/files/4524313/desktop-chrome.txt)

**Comment by ntulele** [comment]
I'm also seeing explicit timeout being ignored in favor of the default waitforTimeout value, on Chrome desktop, using wdio 6.0.16
With waitforTimeout = 3500 , this fails in 3.5s instead of 10s (as it did in wdio 5.x):
```
$('div.notdisplayed').waitForDisplayed(10000);

Error: element ("div.notdisplayed") still not displayed after 3500ms
```

**Comment by esaari** [comment]
> Not just devices, occurs on Chrome desktop, too:
> I'm also seeing explicit timeout being ignored in favor of the default waitforTimeout value, using wdio 6.0.16
> With waitforTimeout = 3500 , this fails in 3.5s instead of 10s (as it did in wdio 5.x):
> 
> ```
> $('div.notdisplayed').waitForDisplayed(10000);
> 
> Error: element ("div.notdisplayed") still not displayed after 3500ms
> ```

@ntulele I think it needs to be `$('div.notdisplayed').waitForDisplayed({ timeout: 10000 });` to work in v6.

**Comment by ntulele** [comment]
@esaari  Oh! Thanks! Did not notice that change. (Too bad it doesn't throw any error about my misuse)

**Comment by christian-bromann** [comment]
> Too bad it doesn't throw any error about my misuse

That's why many people use TypeScript 😉

**Comment by esaari** [comment]
@christian-bromann I finally have a repro for. you, sorry that took so long. 

1. Unzip
2. `npm install`
3. `npx wdio desktop-chrome.conf.js`: I'm actually seeing behavior @ntulele described on the Chrome desktop here.  However, in this example, you can at least see the default 10 second element lookup timeout kick in, even though it doesn't appear to enter my 20 second timeout `waitForExist` loop. 
4. `npx wdio RDC-android.conf.js`: In this example you'll see the element lookup fail immediately, no timeout kicking in at all, which is the original problem I described here. This is configured to run on Browserstack RDC cloud - I can provide you some temp credentials for help debugging this. 

Thank you!!!
[wdio6.zip](https://github.com/webdriverio/webdriverio/files/4595901/wdio6.zip)

**Comment by esaari** [comment]
At least as of Appium 1.18, this issue seems to be resolved. I can run W3C sessions in the cloud provider without issue. Not sure if the newer version of Appium fixed it or it was a newer browser version (mobile Safari 14 is what I verified it with).
