### ISSUE TITLE
Is ther a way to open first chrome browser as regular browser and second browser as incognito?

### ISSUE THREAD

**Issue by umairnazeer** [webdriverio/webdriverio#5313]
## 💬 Questions and Help
I pretty much tried everything to figure it out but I am unable to figure it out. I have tried adding multimore but that didn't work out as the documentation on webdriverio is with async mode and I am using sync. I tried to follow other ways to make it work but no luck.
The scenario I am testing is a chat between two users, and for that I need two browser windows with different session as the app doesn't allow different users on same browser at the same time. So I need to use one regular chrome window and the other one as incognito. Firefox is also not working for me otherwise I could try second browser as firefox.

### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [WebdriverIO Gitter Support Channel](https://gitter.im/webdriverio/webdriverio)
- [#webdriverio channel om SeleniumHQ Slack](https://seleniumhq.slack.com/join/shared_invite/enQtODAwOTUzOTM5OTEwLTZjZjgzN2ExOTBmZGE0NjkwYzA2Nzc0MjczMGYwYjdiNGQ5YjI0ZjdjYjFhMjVlMjFkZWJmNDYyMmU1OTYyM2Y)

**Comment by christian-bromann** [comment]
> I pretty much tried everything to figure it out but I am unable to figure it out.

Why do create an issue for this when it clearly says that for questions one should use the Gitter support channel?

> I have tried adding multimore but that didn't work out as the documentation on webdriverio is with async mode and I am using sync.

Have you tried to just make the code synchronous by removing all `async/await`.

Also a tip: saying that something isn't working doesn't help anyone to understand what is not working , so please always provide a stack trace or logs.

I am closing this issue as we do answer support question on Gitter only. Please understand. Cheers!
