### ISSUE TITLE
Missing typescript methods for browser and others

### ISSUE THREAD

**Issue by diervo** [webdriverio/webdriverio#5314]
The typescript definitions for some of the primitives are not complete.

For example the operation `browser.findElement` which is [publicly documented](https://webdriver.io/docs/api/webdriver.html#findelement) is not part of the browser object definition, which means a typescript user will have to coerce the value:

```js
await (browser as any).findElement(value);
```

Whoever can help addressing this should look at other potential missing operations such as findElements.

If someone can point me to the code where the definitions are generated will be more than happy to do a PR.

**Comment by christian-bromann** [comment]
@diervo do you have a reproducible example? As you can see in https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/webdriverio.d.ts#L42 the browser object receives the WebDriver protocol commands as well as the WebdriverIO API commands. I was also not able to reproduce it.

**Comment by diervo** [comment]
@christian-bromann I apologize for wasting your time, you are 100% correct, the APIs for `findElement` is indeed there. I believe I was using an old version of the webdriverio package.

On my defense, I did create a repo to help further questions, like why `'selenium-standalone'` doesn't work in v6 :)

https://github.com/diervo/wdio-repro-example
