### ISSUE TITLE
Using selenium-standalone in v6 never starts - node v14

### ISSUE THREAD

**Issue by diervo** [webdriverio/webdriverio#5319]
Trying to use webdriver protocol with selenium-standalone hangs (the browser opens with a white screen but no operations are performed).

Here is a minimal repo with the exact configuration ready to `yarn test`:
https://github.com/diervo/wdio-repro-example

Note that changing the `automationProtocol` to `devtools` make everything work (by using pupetteer instead).

~~My intuition is that some code has change that enabled the webdriver protocol to start somehow, but I haven't found the exact code where that happens.~~

This is a bug on Node v14:
https://github.com/nodejs/node/issues/33130

**Comment by diervo** [comment]
I found the problem but not the root cause: Using node v14 causes the selenium to hang, possibly due to some internal API that its silently failing.

**Comment by diervo** [comment]
This was fixed in node 14.1.0

**Comment by christian-bromann** [comment]
Thanks for following up on this!
