### ISSUE TITLE
add HTML reporter

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#532]
Implement epic HTML reporter for test runner. If running tests on Sauce Labs report should get enhanced with all kinds of useful job assets like screenshots or logs.

**Comment by christian-bromann** [comment]
Decided to not put that into `v3` in order to release the new version sooner.

**Comment by klamping** [comment]
Could webdriver-adminpanel be broken out in to two modules, one a reporter and another the api? On a side note, I dream of a reporter that all visual regression tests tools share and can be worked on in unison outside of the specific test runners.

**Comment by pazone** [comment]
I'm already creating the adapter for [Allure](http://allure.qatools.ru). It allows to attach screenshots and other types of data. And also has a lot of other cool features. Definitely it's no reason to create absolutely new report.

**Comment by christian-bromann** [comment]
@pazone awesome, looking forward to check that out! I still think that an html reporter can be really valuable for people using jenkins or other CI systems in their own CI infrastructure. What do you think?

**Comment by pazone** [comment]
Allure has [TeamCity plugin](https://github.com/allure-framework/allure-teamcity-plugin) and [Jenkins plugin](https://github.com/jenkinsci/allure-plugin)

**Comment by christian-bromann** [comment]
Oh, didn't know that. Well in this case an html report would be kinda obsolete. It would be just a case of proper documentation on our website. Please keep me posted.

**Comment by pazone** [comment]
I'm using it with mocha + webdriverio. Now making easy way to attach screenshots.

**Comment by dhoulker** [comment]
@pazone Allure looks great - trying to get it working with webdriverio, are there any steps to follow?

I'm using webdriver 3.0, i've installed the npm package and changed the reporter - but when i run the test (with wdio) i get:

````
Error: Cannot find module './reporter/mocha-allure-reporter'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.init (/usr/local/lib/node_modules/webdriverio/lib/launcher.js:16:20)
````

**Comment by christian-bromann** [comment]
I guess Allure needs and xml so you need to use the xunit reporter

**Comment by dhoulker** [comment]
It looks like allure is an adaptor for mocha - so it writes out its own xml report format. Well, thats what i've understood but i might be wrong!

**Comment by pazone** [comment]
[Here](https://github.com/allure-examples/mocha-allure-example) is little example with Allure and WebDriverIO. There are several important scripts in [package.json](https://github.com/allure-examples/mocha-allure-example/blob/master/package.json#L13) : ```test``` and ```report```. @dhoulker, can you show how are you using mocha-allure-reporter?

**Comment by just-boris** [comment]
@dhoulker have you got a report from your tests? I can help if you still have some errors

**Comment by dhoulker** [comment]
@just-boris, @pazone thanks for getting back to me - sorry for slow reply.

I did get the reporter working, using a custom reporter like the one below:

````javascript
"use strict";
var Base = require("mocha").reporters.Base;
var Allure = require("allure-js-commons");
var allureReporter = new Allure();
var Runtime = require("allure-js-commons/runtime");
var util = require('util');
var events = require('events');
global.allure = new Runtime(allureReporter);

var CustomAllureReporter = function(options) {

    allureReporter.setOptions(options.reporterOptions || {});
    console.log('Allure reporter started with the following reporter options:', options.reporterOptions);

    this.on('start', function() {
        console.log('start');
    });

    this.on('end', function() {
        console.log('end');
    });

    this.on('suite:start', function(suite) {
        console.log('suite:start: ' + suite.title);
        allureReporter.startSuite(suite.title);
    });

    this.on('suite:end', function(suite) {
        console.log('suite:end: ' + suite.title);
        //console.log(suite);
        if(suite.title !== '') {
          allureReporter.endSuite();
        }
    });

    this.on('test:start', function(test) {
        //console.log(test)
        console.log('test:start' + test.title);

        allureReporter.startCase(test.title);
    });

    this.on('test:end', function() {
        console.log('test:end');
    });

    this.on('hook:start', function() {
        console.log('hook:start');
    });

    this.on('hook:end', function() {
        console.log('hook:end');
    });

    this.on('test:pass', function() {
        console.log('test:pass');
        allureReporter.endCase("passed");
    });

    this.on('test:fail', function(test) {
      //console.log('test:fail - ', test);

      if(global.onError) {
         global.onError(test.err);
      }
      allureReporter.endCase("failed", test.err);

    });

    this.on('test:pending', function(test) {
        console.log('test:pending: ' + test.title);
        allureReporter.pendingCase(test.title);
    });
};

/**
 * Inherit from EventEmitter
 */
util.inherits(CustomAllureReporter, events.EventEmitter);

/**
 * Expose Custom Reporter
 */
//exports =
exports = module.exports = CustomAllureReporter;

````
The part i'm having trouble with is getting the global allure object into my tests, any ideas of how i can do that?

**Comment by just-boris** [comment]
@dhoulker that code too similar to original `mocha-allure-reporter`. Are you trying to rewrite it for your needs? How do you add it for your tests?

**Comment by dhoulker** [comment]
Yes, I tried to use mocha-allure-reporter and fit that into the new webdriver custom reporter approach, documented below:

https://github.com/webdriverio/webdriverio/blob/master/examples/wdio/reporter/my.custom.reporter.js
http://webdriver.io/guide/testrunner/customreporter.html

Using that approach I can make use of the new wdio config files, and add my custom reporter as below:

https://github.com/webdriverio/webdriverio/blob/master/examples/wdio/wdio.customreporter.conf.js

As you can see i've got part of the way there, my reports work, but i don't understand how to get to the global allure object, so i can't make use of all the features.

Do you have any ideas of whats else i need to do?

Thanks,

Dave

**Comment by just-boris** [comment]
Hello again. Sorry for delay, only now I found a time for it.

Found that `wdio` works on multiprocess model: there is a `wdio` main process and `runner.js` as child. The thing is we inject `global.allure` object in the main process and children can't get access to it.

I have the same thing with Karma reporter, so I am going to do the same. I will create special runtime module for `wdio` launcher, and it will utilize your `process.message` bus for my types of events, like `step:start`, `step:end`.  Is it valid solution for it?

@christian-bromann 
can I send via `process.message` my special event for reporter? with a special naming convention, of course.

**Comment by georgecrawford** [comment]
As you know, I'm working on https://github.com/webdriverio/wdio-allure-reporter/. Let's discuss further in https://github.com/webdriverio/wdio-allure-reporter/issues/1.

**Comment by christian-bromann** [comment]
Cool, thanks guys. Let's close this then.

**Comment by rahulmr** [comment]
Hello @christian-bromann , I am not happy with the allure reporter as it requires external processing. As I see there is no plan to create single file html reporter like [mochawesome](http://adamgruber.github.io/mochawesome/), I need some help on how to create custom reporter similar to [mochawesome ](http://adamgruber.github.io/mochawesome/) or use mochawesome (or say any reporter which is mocha based). Is there any way in which we can bypass the reporter from wdio using the `wdio.conf.js` file use the mocha reporters directly.

**Comment by christian-bromann** [comment]
> As I see there is no plan to create single file html reporter

Why is that a requirements / restriction?

> it requires external processing

You can process the files in the onComplete hook or call the processing command after the testrun. I don't really see why this is a limitation

**Comment by rahulmr** [comment]
Yes, I used onComplete to convert junit results to html using jasmine-xml2html-converter but that html is very poor in features. If you have seen report generated using mochawesome, you will see that it is very appealing and it is single html file, which is easy to share. It looks cool :). 

wdio is such great, I would be happy to get some great reporting to impress my bosses. I am not good with programming so finding it difficult to write something like wdio-mochawesome-reporter and when I asked mochawesome developer if there was any plan, he simply rejected it :(

I am already doing lot of stuff in onPrepare and onComplete as wdio-appium-service is not able to start /stop appium server on windows , I somehow got a way to start it but now it is not stopping after tests are completed.

**Comment by christian-bromann** [comment]
Why you don't use onComplete to generate the HTML from the allure files?

**Comment by rahulmr** [comment]
:( I will have to be satisfied with allure it seems. I will try to generate the html reports using onComplete. But still if you ever get some free time please provide me some pointers on how I can integrate mochawesome with wdio. Thanks. Is it necessary for allure to have local server to see the files in browser?

**Comment by christian-bromann** [comment]
> if you ever get some free time please provide me some pointers on how I can integrate mochawesome with wdio

Please see how other reporters are implemented.

> Is it necessary for allure to have local server to see the files in browser?

No! Afaik the allure cli command generates static html files which can be displayed in jenkins (with the jenkins integration for allure)

**Comment by christian-bromann** [comment]
> :( I will have to be satisfied with allure it seems.

To be clear here: I am not against having a mochaawesome reporter. I just not invest my free time to implement such reporter as I am happy with the allure reporter. If you want a mochaawesome reporter please contribute to the wdio community 😉

**Comment by rahulmr** [comment]
Thanks @christian-bromann  , I will try ;) . Anyways, enjoying `wdio`, though facing some issue with `wdio-appium-service` but not sure if it windows specific. The appium server is not shutting down after tests are completed. So I am doing start/stop using onPrepare and onComplete. Got go from client as well. Thanks again.
