### ISSUE TITLE
webdriverIO 6.1.3 +jasmine+typescript shwoing "WARN @wdio/jasmine-framework: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised."

### ISSUE THREAD

**Issue by dipti-code** [webdriverio/webdriverio#5325]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2] 6.1.3
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async] syn
 - **Node.js version:** [e.g. 8.11.2] 12.16.x
 - **NPM version:** [e.g. 5.8.0] 6.3.4
 - **Browser name and version:** [e.g. Chrome 68]
 - **Platform name and version:** [e.g. Windows 10] iOS
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]
Mu package.json
"devDependencies": {
    "@types/jasmine": "^3.5.10",
    "@types/jasminewd2": "2.0.8",
    "@types/node": "^12.12.37",
    "@wdio/allure-reporter": "^6.1.1",
    "@wdio/appium-service": "^6.1.0",
    "@wdio/browserstack-service": "^6.0.17",
    "@wdio/cli": "^6.1.3",
    "@wdio/jasmine-framework": "^6.1.3",
    "jasmine": "^3.5.0",
    "@wdio/local-runner": "^6.1.3",
    "@wdio/spec-reporter": "^6.0.16",
    "@wdio/sync": "^6.1.0",
    "chromedriver": "^80.0.2",
    "node-fetch": "^2.6.0",
    "ts-node": "^8.9.0",
    "tsconfig-paths": "^3.9.0",
    "tslint": "^5.20.1",
    "typescript": "^3.8.3",
    "wdio-chromedriver-service": "^6.0.2",
    "webdriverio": "^6.0.13"
  }

tsconfig .json has 

{
  "compilerOptions": {
     "target": "es5",
     "module": "commonjs",
     "baseUrl": ".",
     "paths": {
        "*": [
           "./*"
        ],
        "src/*": [
           "./src/*"
        ],
        "test/*": [
           "./test/*"
        ]
     },
     "types": [
         "node",
         "@wdio/sync",
         "@wdio/jasmine-framework"
      ],
      "allowSyntheticDefaultImports": true,
       "esModuleInterop": true
  },
  "include": [
   ["./**/*.ts"]
  ]
}

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**

**To Reproduce**

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

Log:-
ARN @wdio/jasmine-framework: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
`browser` object has only `capabilities` and some flags like `isMobile`.
Helper files that use other `browser` commands have to be moved to `before` hook.
Spec file(s): /Users/drlenka/Documents/Dipti_OnbaseMobile_Appium/Onbase_Mobile_Appium/tests/specs/app.iOS.spec.ts
 Error:  TSError: ⨯ Unable to compile TypeScript:
tests/specs/app.iOS.spec.ts(113,26): error TS2345: Argument of type '() => {}' is not assignable to parameter of type '() => Boolean'.
  Call signature return types '{}' and 'Boolean' are incompatible.
    The types returned by 'valueOf()' are incompatible between these types.
      Type 'Object' is not assignable to type 'boolean'.
tests/specs/app.iOS.spec.ts(119,37): error TS2339: Property 'id' does not exist on type 'string'.
tests/specs/app.iOS.spec.ts(123,36): error TS2339: Property 'title' does not exist on type 'string'.
tests/specs/app.iOS.spec.ts(128,40): error TS2339: Property 'id' does not exist on type '{}'.
tests/specs/app.iOS.spec.ts(166,16): error TS2552: Cannot find name 'header'. Did you mean 'Headers'?

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
This is not a WebdriverIO error but an error in your test, see:

```ts
 Error:  TSError: ⨯ Unable to compile TypeScript:
tests/specs/app.iOS.spec.ts(113,26): error TS2345: Argument of type '() => {}' is not assignable to parameter of type '() => Boolean'.
```

**Comment by Rahut-5771** [comment]
I am facing the same issue in mocha framework. Following are the error details

Error: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
desktop-profile: `browser` object has only `capabilities` and some flags like `isMobile`.
desktop-profile: Helper files that use other `browser` commands have to be moved to `before` hook.
desktop-profile: Spec file(s): C:\Users\rraut\source\repos\orxe-core-ui\apps\desktop-profile\tests\functional-tests\specs\profileTest.ts
desktop-profile: Error: TypeError: browser.url is not a function

**Comment by DoctorDerek** [comment]
Same here 👍
