### ISSUE TITLE
Promote support for React components and Shadow DOM on the front page

### ISSUE THREAD

**Issue by mardukbp** [webdriverio/webdriverio#5333]
As far as I know, WebDriverIO is the only open-source test automation framework that provides straightforward access to shadow-DOM elements. 

If I am not mistaken, the implementation of the WebDriver specification it relies on can be used as a standalone component. 

I believe it would be very valuable for the software-testing community to make this component more visible and widely usable by maintaining it in its own repository.

Moreover, I think it would be great to be able to run it inside of a web browser. Would it take a lot of work to make it work without NodeJS?

**Comment by christian-bromann** [comment]
First of, thanks for posting the issue!

> I believe it would be very valuable for the software-testing community to make this component more visible and widely usable by maintaining it in its own repository.

How does it become more visible and usable if it is maintained in an own repository? People can make contributions to this repository. In addition to that the WebDriver package contains of 5 files that aren't modified often.

> Moreover, I think it would be great to be able to run it inside of a web browser. Would it take a lot of work to make it work without NodeJS?

Yeah, we are slightly working towards this idea to be able to have a [fiddle platform](https://github.com/webdriverio/webdriverio/projects/8) to share WebdriverIO test code. Note that running WebdriverIO in the browser will only allow you to run remote tests (e.g. on a vendor like Sauce Labs).

Please provide more information as to why your request would help make the WebDriver package more visible, otherwise I will close the issue. Thanks!

**Comment by mardukbp** [comment]
> How does it become more visible and usable if it is maintained in an own repository?

The first page of a Google search for "access shadow dom javascript" does not contain any reference to WebDriverIO or WebDriver. Instead, the top results involve hacky solutions that circumvent the shortcomings of Selenium and other libraries.

I think that if WebDriver had its own repository with a README file advertising its API for accessing shadow DOM elements it would become more widely known. In my opinion, keeping it inside a subdirectory makes it less relevant for search engines and thus harder to find. Whereas, git submodules allow foreign repositories to be embedded within a dedicated subdirectory of the source tree.

> Note that running WebdriverIO in the browser will only allow you to run remote tests

I am thinking of integrating WebDriver (not WebDriverIO) with Robot Framework. This could be accomplished using Mozilla Iodide: a project that compiles CPython to WebAssembly and allows transparently calling JS functions from Python. JavaScript libraries can be fetched using a CDN. That is why I am interested in running WebDriver without NodeJS.

**Comment by christian-bromann** [comment]
> The first page of a Google search for "access shadow dom javascript" does not contain any reference to WebDriverIO or WebDriver

I am not sure if this is a good query. Note that WebDriver is for browser automation which is a difference from being a JavaScript API. Also, accessing shadow DOM is only available using the [webdriverio](https://www.npmjs.com/package/webdriverio) package, not [webdriver](https://www.npmjs.com/package/webdriver).

> advertising its API for accessing shadow DOM elements it would become more widely known.

I am not sure how many people actually need to access shadow DOM elements as part of their browser tests.

**Comment by mardukbp** [comment]
> I am not sure if this is a good query

The first page of "testing shadow DOM" also has no mention of WebDriverIO.

> Also, accessing shadow DOM is only available using the webdriverio package, not webdriver.

My bad. And I know it makes sense because the WebDriver specification does not (yet?) include Shadow DOM. But maybe that functionality can be made available in a separate module that does not need NodeJS. Thus providing a WebDriver implementation augmented with shadow DOM support.

> I am not sure how many people actually need to access shadow DOM elements as part of their browser tests.

A possible way to find out is to advertise the shadowDOM capabilities of WebDriverIO and measure how that affects its popularity (downloads, website visits, etc.). Assuming that most people do not need it and therefore it should not be more visible is a self-fulfilling prophecy.

**Comment by christian-bromann** [comment]
> The first page of "testing shadow DOM" also has no mention of WebDriverIO.

There are sure some SEO improvements we can make. Any ideas?

> But maybe that functionality can be made available in a separate module that does not need NodeJS.

I assume you want to use it in the Robot framework? If so, feel free to use the [small script](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/scripts/shadowFnFactory.js) we use for that.

> Thus providing a WebDriver implementation augmented with shadow DOM support.

WebdriverIO is a WebDriver implementation with shadow DOM support.

I still can't follow how moving any of the packages out of the repo will drive more visibility to WebdriverIOs capability of shadow DOM support. I agree though that we could extend our docs and improve the SEO.

**Comment by mardukbp** [comment]
> There are sure some SEO improvements we can make. Any ideas?

Maybe add a page highlighting the shadow-DOM capabilities of WebDriverIO. Of course including all the meta tags that lead to a higher rank in search engines.

> I assume you want to use it in the Robot framework?

Yes, indeed! Actually my idea is to use [Mozilla Pyodide](https://github.com/iodide-project/pyodide) which compiles CPython to WebAssembly thus enabling any Python code to run on a web browser and seamlessly interact with JavaScript. What I would like to do is to have an interactive platform for testing web pages directly in a web browser.

> Feel free to use the small script we use for that

Thank you. I already used it to enhance the Selenium Library. But Selenium does not work inside a web browser. That is why I am interested in WebDriverIO.

> I still can't follow how moving any of the packages out of the repo will drive more visibility to WebdriverIOs capability of shadow DOM support. I agree though that we could extend our docs and improve the SEO.

You are right. But thanks to your interest and patience we have come to discuss the issues that actually matter. Learning to communicate effectively is a skill that takes years. I am working on that.

**Comment by christian-bromann** [comment]
> What I would like to do is to have an interactive platform for testing web pages directly in a web browser.

Note that you can't control the browser you are in, you can only control a remote browser in e.g. the cloud.

So if you agree, we should rename this issue to promote shadow DOM support and eventually support for react elements on the front page. Running WebdriverIO in the browser still takes longer than initially expected as there are still a lot of dependencies to Node which need cleanup.

**Comment by mardukbp** [comment]
> Note that you can't control the browser you are in, you can only control a remote browser in e.g. the cloud.

I guess that also includes a browser running on the same machine. First I would setup the tests locally and then execute them on the cloud.

> So if you agree, we should rename this issue to promote shadow DOM support and eventually support for react elements on the front page

Of course I agree :)

> Running WebdriverIO in the browser still takes longer than initially expected as there are still a lot of dependencies to Node which need cleanup.

Alright. If there is an issue I can subscribe to to follow the development it would be great.

**Comment by christian-bromann** [comment]
> I guess that also includes a browser running on the same machine. First I would setup the tests locally and then execute them on the cloud.

No. You __only__ will be able to control browsers in the cloud since you don't have any permissions to spin up apps from a browser.

**Comment by mardukbp** [comment]
> You only will be able to control browsers in the cloud since you don't have any permissions to spin up apps from a browser.

What is so special about the cloud? I can run a server locally, open a browser manually, etc.

**Comment by christian-bromann** [comment]
@mardukbp if you run JS in the browser you run it in a sandbox that has no access to your machine environment. You will need some sort of service that can spin up the browser and proxy commands to it.

**Comment by mardukbp** [comment]
Yeah, I am aware of that. Thanks for the explanation :)

**Comment by christian-bromann** [comment]
fixed by #5431
