### ISSUE TITLE
Proposal: Adding network primitives to the browser object

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#5336]
# Proposal

As we have better cross browser support for Puppeteer we should move forward and provide better network primitives for WebdriverIO to help user access the network layer. In addition to that these features are likely to be supported once WebDriver moves to a BiDi protocol (which is a new version of WebDriver that is currently designed by the W3C working group and browser vendors). Here are some of my ideas:

## Goal

The goal of this proposal is to simplify network primitives for users without exposing them to too much detail. Commands should allow to do the majority over normal use cases with as less coding as possible while always providing the ability to access Puppeteer native APIs.
Additionally we should create useful commands that help with the testing flow, e.g.: integrate it into our assertion library.

## Compatibility

These features will be only supported in Chrome, Firefox (beta) and Edge when running locally as well as on Sauce Labs (using extended debugging capabilities). With release of Selenium 4 this can be also supported if someone has an internal grid or uses the selenium standalone service.

## State

The state of these mocked network resources will stay for the live time of the session. So if the user switches between windows, opens and closes pages, the mocked resources stays as defined. Adding the ability to reset a certain mocked resources makes sense here. Again a power user will be always able to use Puppeteer directly if he desires more granular access to CDP.

### Network Mocking

See proposal: https://github.com/webdriverio/webdriverio/pull/5471

### Throttling

See proposal: https://github.com/webdriverio/webdriverio/pull/5472

### Events

See (rejected) proposal: https://github.com/webdriverio/webdriverio/issues/5473

Not considered for implementation anymore.

### Wait Commands

See proposal: https://github.com/webdriverio/webdriverio/issues/5474

### Overwriting User Agent

See (rejected) proposal: https://github.com/webdriverio/webdriverio/issues/5475

Not considered for implementation anymore.

### Recording

See proposal: https://github.com/webdriverio/webdriverio/issues/5476

**Comment by erwinheitzman** [comment]
I love this idea and am wondering how the state of these mocks work, are they lost after the test, do they stay and have to be cleaned or reset?

**Comment by christian-bromann** [comment]
@erwinheitzman added a section to the state of mocks

**Comment by erwinheitzman** [comment]
Would it be possible to extend the given examples further like so?
```js
browser.network.waitForResponse({
  url: '/foo/**/bar',
  method: 'post',
  statusCode: 400,
  // maybe a specific body that equals or matches, etc
  // etc..
}, 4000)
```

**Comment by erwinheitzman** [comment]
I would love to be able to set mocks that are applied to all my sessions as well so that I do not have to define them for each session.

**Comment by christian-bromann** [comment]
> Would it be possible to extend the given examples further like so?

Yes, updated the example.

> I would love to be able to set mocks that are applied to all my sessions as well so that I do not have to define them for each session.

I think this could be a WDIO testrunner config option where mocks for specific urls can be defined for all sessions up front.

**Comment by wswebcreation** [comment]
Love the idea @christian-bromann , that would make WDIO even better 🔥 

I've used this [ng-apimock](https://github.com/mdasberg/ng-apimock#howto-write-mocks) a lot in the past and it gave you the ability to also change the:

- headers
- add a delay

What would also be great is if we can support something like fixtures which Cypress also has. Meaning that you load a (large) response, but are able to adjust some properties in 1 sessions so you don't need to maintain x amount of JSON responses. This limits the amount of work and maintenance for users who want to mock when they need different results based on 1 API response

**Comment by mgrybyk** [comment]
I also like that response can be a function so I can slightly adjust it for every call. It's very useful when multiple async or background calls happens and there is a need to calculate something every time

**Comment by christian-bromann** [comment]
@wswebcreation added an example for header modification and delay to the proposal. I also added a "Recording" section. I would love to have the ability to just capture network activity as a snapshot.

**Comment by erwinheitzman** [comment]
I think we should also add an example to the documentation which shows how you can use the devtools to create a data set

**Comment by jtibble** [comment]
Please consider adding not just bandwidth throttling but also latency and packet loss percentage. It is extremely valuable to test a website not just on a slow connection but a lossy connection, like satellite, which drops packets and has 100-500ms latency. Thanks!!

**Comment by christian-bromann** [comment]
> Please consider adding not just bandwidth throttling but also latency and packet loss percentage.

Unfortunately this kind of throttling is not supported by browsers atm. Only certain proxy projects like Charles can do that afaik. But definitely worth considering as improvement.

**Comment by Xotabu4** [comment]
That's an awesome and natural further step of puppeteer+wdio combo!

Have some idea for Events:

At one of my projects I had to wait until some event has happened on the page. Thats was protractorJS project, so i was dealing with async/await. But i wonder how this can look like with wdio?

```
const data = browser.network.waitFor('request', (request) => {...})
```

or maybe - 

```
browser.waitForPageEvent((eventName, data) => eventName === 'request'})
```

**Comment by christian-bromann** [comment]
@Xotabu4 I am not sure what the concept of an "page event" is here but this should be possible with the wait commands proposed above.

**Comment by christian-bromann** [comment]
Implementations for above proposals have been issues as pull requests. Closing and moving this to done.
