### ISSUE TITLE
debug module overwritten by puppeteer logging

### ISSUE THREAD

**Issue by jpaolini** [webdriverio/webdriverio#5338]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** v6.0.0
 - **Mode:** Standalone Mode
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v13.7.0
 - **NPM version:** 6.13.6
 - **Browser name and version:** Chrome 81
 - **Platform name and version:** macOS
 - **Additional wdio packages used (if applicable):** ["@wdio/allure-reporter": "^6.0.0",
    "@wdio/cli": "^6.0.0",
    "@wdio/config": "^6.0.0",
    "@wdio/cucumber-framework": "^6.0.0",
    "@wdio/junit-reporter": "^6.0.0",
    "@wdio/local-runner": "^6.0.0",
    "@wdio/selenium-standalone-service": "^6.0.0",
    "@wdio/spec-reporter": "^6.0.0",
    "@wdio/sync": "^6.0.0",]

**Config of WebdriverIO**
Standard config from the documentation [here](https://webdriver.io/docs/configurationfile.html)

**Describe the bug**
For our setup we use the `debug` module to show console logs of our step definitions and info in page objects.  

**To Reproduce**
Import the `debug` module into any project and attempt to log output using it.

**Expected behavior**
The `debug` module logs to the console as expected

**Additional context**
This appears to be introduced with the integration of puppeteer.  In [devtools/src/index.js](https://github.com/webdriverio/webdriverio/blob/master/packages/devtools/src/index.js), line 19 calls `patchDebug`.  In the `patchDebug` functions, if it can't find the puppeteer version of debug, it overwrites the debug log function for all packages.  
```
/**
   * check if Puppeteer has its own version of debug, if not use the
   * one that is installed for all packages
   */
    if (!fs.existsSync(puppeteerDebugPkg)) {
        /**
         * let's not get caught by our dep checker, therefor
         * define package name in variable first
         */
        const pkgName = 'debug'
        puppeteerDebugPkg = require.resolve(pkgName)
    }
```

> Please use the correct markdown

**Comment by christian-bromann** [comment]
We have to do this hack to allow fetching log data from Puppeteer. Can you see a `debug` package in the Puppeteer node modules?

**Comment by jpaolini** [comment]
Yeah, all it good, makes sense so that it works with the logging. I checked the Puppeteer node modules and there isn't a debug package in there.  While waiting for [Add first level logging capability](https://github.com/puppeteer/puppeteer/issues/5786), maybe we can look into short term work arounds?  Thinking maybe a way to check if Puppeteer is being used, if it is, continue with the current patching, if not, then skip that part.  Not sure if that's possible though.  What are your thoughts?

**Comment by christian-bromann** [comment]
> What are your thoughts?

I would suggest 2 things:

1) install the `debug` package with a different version in your project (e.g. pinned to 4.1.0)
2) move the patching inside the `newSession` and `reloadSession` function and ensure that it only is patched once

**Comment by jpaolini** [comment]
@christian-bromann, great idea on the 1st option.  That works for us as a short term solution.

**Comment by christian-bromann** [comment]
As we get rid of the `devtools` package in `v9` I will go ahead and close this issue.
