### ISSUE TITLE
Allow Devtools to launch Chrome without default flags and/or Puppeteer default args

### ISSUE THREAD

**Issue by anemer** [webdriverio/webdriverio#5339]
**Is your feature request related to a problem? Please describe.**
Some of default flags shipped in [devtools/constants.js](https://github.com/webdriverio/webdriverio/blob/master/packages/devtools/src/constants.js#L8)  hinder opening some websites.
Indeed, some websites that can be used **only with Chrome** make (radical) controls like this one:
```javascript
var isChrome = !!window.chrome && (!!window.chrome.webstore || !!window.chrome.runtime);
if (!isChrome){ window.location.href = "/NotCompatibleBrowser";}
```

**Describe the solution you'd like**
Add an optional parameter (in `wdio.conf.js`) that allow to launch Google Chrome: 
* without the default flags. 
* and/or without the default Puppeteer arguments.

**Comment by anemer** [comment]
I'm preparing a PR for this

**Comment by christian-bromann** [comment]
An enhancement to this was merged and released. Closing!
