### ISSUE TITLE
TypeError in getText which causes a "fatal error"

### ISSUE THREAD

**Issue by SerkanSipahi** [webdriverio/webdriverio#534]
Sometimes we get a TypeError in getText which causes a "fatal error" ! Is this a bug or not?

`
TypeError: Cannot read property 'value' of null at /webdriverio/lib/commands/getText.js:75
`

If we change [this line to](https://github.com/webdriverio/webdriverio/blob/master/lib/commands/getText.js#L75) to ` value = response.elementIdText[0] && response.elementIdText[0].value;` it works as expected

**Comment by christian-bromann** [comment]
@SerkanSipahi is this the case in all browser or just is specific ones? Also is the text actually "" or is the element not available? Just check with codebase in `v3` and those kind of error can't not happen anymore. Will close this issue as I don't release any new version before `v3`. Thanks for reporting!
