### ISSUE TITLE
clearValue adds cleared value to input field

### ISSUE THREAD

**Issue by toienMT** [webdriverio/webdriverio#5343]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.0.13
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** v12.14.1
 - **NPM version:** 6.13.4
 - **Browser name and version:** Chrome 81.0.4044.129
 - **Platform name and version:** MacOS Mojave
 - **Additional wdio packages used (if applicable):** 
    "@types/jasmine": "^3.5.8",
    "@typescript-eslint/eslint-plugin": "^2.24.0",
    "@wdio/cli": "^6.0.15",
    "@wdio/jasmine-framework": "^6.0.15",
    "@wdio/local-runner": "^6.0.15",
    "@wdio/selenium-standalone-service": "^6.0.15",
    "@wdio/spec-reporter": "^6.0.14",
    "@wdio/sync": "^6.0.15",

**Config of WebdriverIO**
Using a pretty standard version of WDIO.config

**Describe the bug**
In a form input field. I have an array of strings that I input then use `.clearValue()` and it clears the value however when I enter the next string in the array is the first value and the second value.

**To Reproduce**
Add an array of strings and loop through the array on an input field
```
array = ['one', 'two', 'three']

array.ForEach((txt) => {
      browser.inputEmail.setValue(txt);
      browser.inputPassword.click();
      browser.invalidEmailError.waitForDisplayed();
      browser.inputEmail.clearValue();
});
```
**Expected behavior**
I would have expected the clearValue to remove the text from the input field and then on the 2nd iteration of the loop enter only the 2nd item in the array. I am using doubleClick() to highlight an remove the previous text

**Comment by christian-bromann** [comment]
Can you provide a reproducible example?

**Comment by toienMT** [comment]
Could be related to this? https://github.com/webdriverio/webdriverio/issues/1140

**Comment by christian-bromann** [comment]
@tobli maybe.

I think this error is because sync mode doesn't work in foreach like that. I recommend to try:

```js
array = ['one', 'two', 'three']

for (const txt of array) {
      browser.inputEmail.setValue(txt);
      browser.inputPassword.click();
      browser.invalidEmailError.waitForDisplayed();
      browser.inputEmail.clearValue();
}
```

This should work as expected.
