### ISSUE TITLE
isVisibleWithinViewport does not work correctly with fixed elements

### ISSUE THREAD

**Issue by DudaGod** [webdriverio/webdriverio#5346]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 4.14.4
 - **Mode:** Standalone mode
 - **Node.js version:** 8.6.0
 - **NPM version:** 6.2.0
 - **Browser name and version:** Chrome 72.1
 - **Platform name and version:** Linux

**Describe the bug**
Page https://yandex.ru/search/?text=test has fixed header element with selector - `.serp-header__wrapper`. After scrolling page on 100px (height of element) I still see it in the viewport. To test it I use command `isVisibleWithinViewport` but it returns false in this case. I don't understand why we check all parent elements here - https://github.com/webdriverio/webdriverio/blob/v4.14.0/lib/scripts/isWithinViewport.js#L21. It seems that in the case of a fixed element, we do not need to check its parents.

**To Reproduce**
Code:
```
'use strict';

const webdriverio = require('webdriverio');

const browser = webdriverio.remote({
    host: 'localhost',
    port: '4444',
    path: '/wd/hub',
    desiredCapabilities: {
        browserName: 'chrome',
        version: '72.1'
    }
});

(async () => {
    const selector = '.serp-header__wrapper';

    try {
        await browser.init();
        await browser.url('http://yandex.ru/search/?text=test');

        await browser.pause(3000);

        await browser.execute(() => {
            window.scrollTo(0, 100);
        });

        const result = await browser.isVisibleWithinViewport(selector);
        console.log('RESULT:', result);

        await browser.end();
    } catch (e) {
        console.log('erorr:', e);
        await browser.end();
    }
})();
```

**Comment by DudaGod** [comment]
@christian-bromann Hello, can you look at this issue? Is v4 still supported?

**Comment by christian-bromann** [comment]
> Is v4 still supported?

No. v4 is not supported anymore. I will close the issue as I don't think anyone would be interested in fixing this. If so, please make a PR here: https://github.com/webdriverio-boneyard/v4
