### ISSUE TITLE
New feature request- Add Largest contentful paint (LCP) to devtools service getMetrics() function.

### ISSUE THREAD

**Issue by Pratikhanagodimath** [webdriverio/webdriverio#5358]
**Is your feature request related to a problem? Please describe.**
The feature ask is not related to any problem. Currently, getMetrics() function does not include LCP (largest contentful paint) metric. With the performance evaluation moving towards LCP, this metric is important. It will be great to have this metric.
 
**Describe the solution you'd like**
I was told that webdriverIO is still not using the version to support addition for LCP metric. I guess bumping the version might be the way to go. I am not sure myself what needs to be bumped. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by christian-bromann** [comment]
This is something that should be made possible by updating the Lighthouse version in the devtools service. Any help on this would be appreciated.

**Comment by thomaschaplin** [comment]
In theory this should be fixed now as lighthouse was bumped 9 days ago in this PR: https://github.com/webdriverio/webdriverio/pull/5925

@Pratikhanagodimath can you confirm if your issue is now resolved?

**Comment by thomaschaplin** [comment]
If not I'd be happy to take a look into this further.

**Comment by christian-bromann** [comment]
@thomaschaplin I think we need to update LH in the `@wdio/devtools-service` to get this feature. That would be a nice contribution.

**Comment by thomaschaplin** [comment]
@christian-bromann please could you assign this to me? How can I best discuss this with you as my first contribution?

**Comment by christian-bromann** [comment]
> How can I best discuss this with you as my first contribution?

Let's keep conversations in this thread.

**Comment by thomaschaplin** [comment]
> > How can I best discuss this with you as my first contribution?
> 
> Let's keep conversations in this thread.

Great. I'll have a dig/play around and will comment if I need any help. Thanks

**Comment by pmerwin** [comment]
devtools is on "lighthouse": "^6.4.1" which has LCP:

example:

  metrics: {
    "estimatedInputLatency": 1815,
    "timeToFirstByte": 23,
    "serverResponseTime": 23,
    "domContentLoaded": 1421,
    "firstVisualChange": 928,
    "firstPaint": 938,
    "firstContentfulPaint": 938,
    "firstMeaningfulPaint": 938,
    "largestContentfulPaint": 4563,
    "lastVisualChange": 4944,
    "firstCPUIdle": 7061,
    "firstInteractive": 7061,
    "load": 5301,
    "speedIndex": 2223,
    "totalBlockingTime": 6020,
    "cumulativeLayoutShift": 0,
  },

**Comment by thomaschaplin** [comment]
Looks like this metric is already included in `getMetrics()` as seen [here](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-devtools-service/src/auditor.js#L97) which was implemented in the PR below

https://github.com/webdriverio/webdriverio/pull/5646

**Comment by thomaschaplin** [comment]
@christian-bromann am I right in saying this can be closed then? Or am I missing something?

**Comment by christian-bromann** [comment]
@thomaschaplin we can close this indeed. Thanks!
