### ISSUE TITLE
Region ignored in sauce service

### ISSUE THREAD

**Issue by Masadow** [webdriverio/webdriverio#5363]
**Environment (please complete the following information):**
 - **WebdriverIO version:** latest
 - **Mode:** testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v12.16.1
 - **NPM version:** 6.13.4
 - **Browser name and version:** NC
 - **Platform name and version:** NC
 - **Additional wdio packages used (if applicable):** @wdio/sauce-service

**Config of WebdriverIO**
```
config.user = USERNAME;
config.key = SECRET_KEY;
config.capabilities = [caps];
config.services = [
    ['sauce', {
        region: 'eu',
        sauceConnect: true,
        sauceConnectOpts: {
            // ...
        },
    }],
];
```

**Describe the bug**
Sauce service is configured with `us` region and target `ondemand.saucelabs.com/wd/hub`

**To Reproduce**
Just run the testrunner

**Expected behavior**
It should target `ondemand.eu-central-1.saucelabs.com/wd/hub`

**Fix**
It is actually an easy fix, as a workaround, I can add `config.region = 'eu';` in the json config (same level as user and key) so saucelabs is instanciated with the appropriate region parameter.

Otherwise, you just need to grab region from options in saucelabs service constructor and blend it into the config used to instantiate saucelabs API.

**Comment by christian-bromann** [comment]
@Masadow I don't see `region` being documented as option for the [Sauce Service](https://webdriver.io/docs/sauce-service.html#sauce-service-options). As you already pointed out (as "workaround") the proper way to define it is via the [options](https://webdriver.io/docs/options.html#region).

**Comment by Masadow** [comment]
@christian-bromann It is under configuration on the page you provided

**Comment by christian-bromann** [comment]
Ah, I was blind I guess, anyway it is wrong documented, will fix it.
