### ISSUE TITLE
Add api for appium image comparison features

### ISSUE THREAD

**Issue by sanlengjingvv** [webdriverio/webdriverio#5372]
**Is your feature request related to a problem? Please describe.**
I'm trying use appium's image comparison function via this document:
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/image-comparison.md
but can't find api for this.

**Describe the solution you'd like**
Maybe a new api like browser.compare_images(mode, firstImage, secondImage, {options})

**Comment by christian-bromann** [comment]
According to Appiums [Base Driver](https://github.com/appium/appium-base-driver/blob/master/lib/protocol/routes.js#L694-L702) the command is defined under the route `[POST] /session/$sessionId/appium/compare_images`. This feature can be easily added by adding it to the Appium [protocol definition](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-protocols/protocols/appium.json) in the `@wdio/protocols` package.

This is a fairly easy change and a great chance for someone making his first contribution to WebdriverIO.
