### ISSUE TITLE
WDIO settings browserName to value not listed as permitted in its constants

### ISSUE THREAD

**Issue by snoblenet** [webdriverio/webdriverio#5376]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.1.5
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 14.1.0
 - **NPM version:** 6.14.4
 - **Browser name and version:** Chromium 78.0.3882.0 (installed by Puppeteer)
 - **Platform name and version:** Mac OS X 10.15.4
 - **Additional wdio packages used (if applicable):** 
       @wdio/devtools-service v6.1.8
       puppeteer v3.0.4

**Config of WebdriverIO**
An example of how you configured WebdriverIO config:

```
  capabilities: [{
    browserName: 'chrome',
    'goog:chromeOptions': {
      w3c: false,
      binary: puppeteer.executablePath(),
      args: [
        '--aggressive-cache-discard',
        '--disable-application-cache',
        '--disable-cache',
        '--disable-dev-shm-usage',
        '--disable-extensions',
        '--disable-gpu',
        '--disable-notifications',
        '--disable-reading-from-canvas',
        '--disable-offline-load-stale-cache',
        '--disk-cache-size=0',
        '--enable-aggressive-domstorage-flushing',
        '--headless',
        '--no-sandbox',
        '--whitelisted-ips',
      ],
    },
  }],

```

**Describe the bug**
On a variety of occasions, including but not limited to `browser.reloadSession()`, devtools will check the browser name against a list of acceptable browser names in the constants file and then throw an error because WDIO (presumably) has set the browser name to a value not in that file. It will then often time out with a memory leak.

in `node_modules/devtools/build/launcher.js`:

```
function launch(capabilities) {
  console.log(JSON.stringify({ capabilities }, null, 2));
  console.log(new Error().stack);
```

In log:

```
  "capabilities": {
    "browserName": "Chrome Headless",
    "browserVersion": "78.0.3882.0",
    "platformName": "darwin",
    "platformVersion": "19.4.0",
    "goog:chromeOptions": {
      "debuggerAddress": "localhost:60726",
      "w3c": false,
      "binary": "/Users/steven/code/webapp/node_modules/puppeteer/.local-chromium/mac-686378/chrome-mac/Chromium.app/Contents/MacOS/Chromium",
      "args": [
        "--aggressive-cache-discard",
        "--disable-application-cache",
        "--disable-cache",
        "--disable-dev-shm-usage",
        "--disable-extensions",
        "--disable-gpu",
        "--disable-notifications",
        "--disable-reading-from-canvas",
        "--disable-offline-load-stale-cache",
        "--disk-cache-size=0",
        "--enable-aggressive-domstorage-flushing",
        "--headless",
        "--no-sandbox",
        "--whitelisted-ips"
      ]
    }
  }
}
[0-0] Error
    at launch (/Users/steven/code/webapp/node_modules/devtools/build/launcher.js:117:15)
    at Function.reloadSession (/Users/steven/code/webapp/node_modules/devtools/build/index.js:109:49)
    at Browser.reloadSession (/Users/steven/code/webapp/node_modules/webdriverio/build/commands/browser/reloadSession.js:25:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Browser.runCommandWithHooks (/Users/steven/code/webapp/node_modules/@wdio/sync/build/wrapCommand.js:88:21)
[0-0] [WDIO]: The step "should let the new user login" failed
[0-0] Error in "User Management Flow should let the new user login"
Couldn't identify browserName chrome headless
[0-0] Error in ""after all" hook in "{root}""
Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a <--- Last few GCs --->

[34690:0x10411b000]   226491 ms: Scavenge 2043.1 (2047.2) -> 2042.3 (2047.2) MB, 9.2 / 0.7 ms  (average mu = 0.297, current mu = 0.318) allocation failure
[34690:0x10411b000]   226564 ms: Scavenge 2043.2 (2047.2) -> 2042.5 (2047.8) MB, 8.5 / 0.7 ms  (average mu = 0.297, current mu = 0.318) allocation failure
[34690:0x10411b000]   226631 ms: Scavenge 2043.3 (2047.8) -> 2042.5 (2047.8) MB, 5.8 / 0.7 ms  (average mu = 0.297, current mu = 0.318) allocation failure

<--- JS stacktrace --->
```

**To Reproduce**
Steps to reproduce the behavior: as above

**Expected behavior**
Either (1) `chrome headless` is in the constants file, or (2) WDIO (presumably) does not change the name of the browser to `Chrome Headless`. Either way, there is then (1) no error, (2) no timeout and (3) no memory leak.

**Comment by snoblenet** [comment]
confirmed the problem also exists when you set `browserName: 'chromium` in `wdio.conf.js`

**Comment by christian-bromann** [comment]
@snoblenet WebdriverIO stores perceived capabilities in `browser.capabilities` and original requested capabilities in `browser.requestedCapabilities`. For the reload procedure we should use the requested capabilities (without a changed browser name). Not sure why it doesn't. Mind taking a look?

**Comment by sethuster** [comment]
I've been trying to reproduce this one, but haven't had any luck.

**Comment by christian-bromann** [comment]
@snoblenet can you provide a reproducible example?

**Comment by Harkunwar** [comment]
I fixed it by using browseName as 'chrome'

**Comment by pjcalvo** [comment]
Based on the error logs on the fist post would that be fixed by adding: `chrome headless` to the list?

https://github.com/webdriverio/webdriverio/blob/9f9e345fb1062d07358b4a4f1b28ba528cfb395a/packages/devtools/src/constants.js#L45

**Comment by jonesh66** [comment]
I have investigated the issue and it seems that this doesn't happen with the latest version of WebdriverIO. In case you face this again, I request you to provide a reproducible script and this will be opened again.

Thanks
