### ISSUE TITLE
devtools protocol: crash call getWindowHandles() after window.close()

### ISSUE THREAD

**Issue by takeya0x86** [webdriverio/webdriverio#5380]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.1.9
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.16.3
 - **NPM version:** 6.14.4
 - **Browser name and version:** Chrome 81
 - **Platform name and version:** macOS 10.15.4
 - **Additional wdio packages used (if applicable):** 

**Config of WebdriverIO**
`automationProtocol: 'devtools'`

**Describe the bug**
https://takeya0x86.github.io/playground/0510_base.html
This page contains a link which open the new window. The new window has a button which close window by JavaScript `window.close()`.
The problem is that after close window, calling getWindowHandles() causes webdriverio crash.

**To Reproduce**
```javascript
it('Window Handles', () => {
  browser.url('https://takeya0x86.github.io/playground/0510_base.html');
  expect($('h1')).toHaveText('Base page');
  expect(browser.getWindowHandles()).toHaveLength(1);

  $('#open-window').click();
  browser.pause(2000);
  browser.switchWindow('0510_new');
  expect($('h1')).toHaveText('New page');
  expect(browser.getWindowHandles()).toHaveLength(2);

  $('#close-window').click();
  browser.pause(2000);
  expect(browser.getWindowHandles()).toHaveLength(1); // => crash!!
});
```

**Expected behavior**
does not occur a crash. 

**Log**
https://gist.github.com/takeya0x86/527e0bcfc9ff920b8d7449d8c6395163

**Additional context**
When automationProtocol: 'webdriver', it works fine.
https://gist.github.com/takeya0x86/ec8e9d75ddd1d4d72f87efa8b5a7e623

**Comment by kajmagnus** [comment]
Sounds similar to: https://github.com/webdriverio/webdriverio/issues/5241  — and, in [this comment](https://github.com/webdriverio/webdriverio/issues/5241#issuecomment-611717280): *"node does use more and more memory (I didn't notice until now), like that other issue does too, eventually 1.5G before I killed -9 it"*

**Comment by dylang** [comment]
Could be related to #5048.

**Comment by christian-bromann** [comment]
@takeya0x86 do you still experience this?

**Comment by takeya0x86** [comment]
@christian-bromann Yes. I still have a same problem after update to latest version (v6.5.0).

**Comment by TannaciousXP** [comment]
Hello, I'm currently on 6.12.1 and I'm experiencing the same issue. Is there a workaround for this?

**Comment by christian-bromann** [comment]
This issue doesn't seem to be reproducible with the latest Chromedriver and WebdriverIO. Closing!
