### ISSUE TITLE
Cannot use mocha-parallel-tests with selenium-webdriver

### ISSUE THREAD

**Issue by gfinzerScotts** [webdriverio/webdriverio#5388]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 4.0.0-alpha.5
 - **Mode:** Standalone
 - **If WDIO Testrunner, running sync/async:** n/a
 - **Node.js version:** v12.13.1
 - **NPM version:** 6.12.1
 - **Browser name and version:** Version 81.0.4044.138 (Official Build) (64-bit)
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** n/a

**Config of WebdriverIO**
    static async CreateChromeIncognitoDriver(): Promise<WebDriver> {
        const options = new chrome.Options();
        options.addArguments("--test-type");
        options.addArguments("--incognito");

        //Override the normal incognito user agent string
        options.addArguments(
            "--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"
        );

        const driver = await new Builder()
            .forBrowser("chrome")
            .setChromeOptions(options)
            .build();

        //Maximize the window
        await driver
            .manage()
            .window()
            .maximize();
        return driver;
    }

**Describe the bug**
"before all" hook for "https://scotts.testrail.io/index.php?/cases/view/18337":
     TypeError: Cannot read property 'split' of undefined
      at Object.exports.findInPath (node_modules\selenium-webdriver\io\index.js:242:45)

**To Reproduce**
mocha-parallel-tests "./lib/LawnSubscription/Full UAT/Smoke Tests/Billing Information.js"  --timeout 0 --reporter mochawesome --reporter-options reportDir=TestResults,timestamp=true,reportFilename=report

**Expected behavior**
An exception should not be thrown in the selenium-webdriver

**Comment by christian-bromann** [comment]
@gfinzerScotts thanks for filing the issue. Unfortunately you are using `selenium-standalone` and not WebdriverIO so I can't really help you. I recommend to create the issue in the [Selenium project](https://github.com/SeleniumHQ/selenium).

**Comment by gfinzerScotts** [comment]
Thanks so much Christian for the quick reply.  I will post to that project.
