### ISSUE TITLE
Cannot use cucumberOpts scenarioLevelReporter: true with @wdio/allure-reporter^6

### ISSUE THREAD

**Issue by osmolyar** [webdriverio/webdriverio#5389]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.0.15
 - **Mode:** selenium-standalone-service
 - **Node.js version:**  12.9.0
 - **NPM version:**  6.14.4
 - **Browser name and version:** Any (Firefox 75.0)
 - **Platform name and version:**. Windows 10
 - **Additional wdio packages used (if applicable):**:
 "@wdio/allure-reporter": "^6.1.9",
    "@wdio/cli": "^6.0.15",
    "@wdio/cucumber-framework": "^6.0.15",
    "@wdio/dot-reporter": "^6.0.14",
    "@wdio/junit-reporter": "^6.0.15",
    "@wdio/local-runner": "^6.0.15",
    "@wdio/selenium-standalone-service": "^6.0.15",
    "@wdio/spec-reporter": "^6.0.15",
    "@wdio/sync": "^6.0.15",
    "wdio-cucumberjs-json-reporter": "^1.2.4",
    "webdriverio": "^6.0.15",

**Config of WebdriverIO**
Allure reporter config:
            "allure",
            {
                outputDir: "allure-results",
                useCucumberStepReporter: true,
                disableWebdriverStepsReporting: true,
                disableMochaHooks: true
            },
relevant Cucumber Opts config:
    scenarioLevelReporter: true,  //treat scenarios as tests instead of steps; needed to use retry
      retry: 1,

**Describe the bug**
The following errors occur at the beginning and end of each scenario:
[0-0] allure-js-commons: Unexpected startStep() of Log in as _SYSTEM to access Home. There is no parent step

and

 allure-js-commons: Unexpected endStep(). There are no any steps running.

No allure report is generated.

**To Reproduce**

Add cucumberOpts scenarioLevelReporter: true => Produces errors
Comment out cucumberOpts scenarioLevelReporter: true => errors disappear

**Expected behavior**
Expect to be able to use @wdio/allure-reporter with wdio v6 and scenarioLevelReporter: true in order to use the scenario-level retries functionality

**Comment by qvalero** [comment]
Hello, I confirm this issue. Is there any workaround waiting for a fix ? I wanted to implement and use the scenario-level retries functionality for my test suites

**Comment by BorisOsipov** [comment]
@osmolyar @qvalero can you try `useCucumberStepReporter: false,` in allure reporter config?

**Comment by qvalero** [comment]
Thanks for your suggestion Boris, there is no error anymore but report is not really readable:

> useCucumberStepReporter: false
![image](https://user-images.githubusercontent.com/63647610/82418420-43f5e780-9a7d-11ea-937f-c3204892ea28.png)

> useCucumberStepReporter: true
![image](https://user-images.githubusercontent.com/63647610/82418536-66880080-9a7d-11ea-8f43-ad0a8c8cb4ac.png)

**Comment by qvalero** [comment]
Hello, any other suggestion on this issue ? 
This issue is blocking the retry functionality on scenario level, hence loosing a lot of time using the retry on full feature.

**Comment by christian-bromann** [comment]
> Hello, any other suggestion on this issue ?

More input from your side would be appreciated. You are saying that `It does not seem to be a correct solution`, what is then? Have you tried to look into the code? We would appreciated any support on this.

**Comment by qvalero** [comment]
With `useCucumberStepReporter: false` in allure reporter config we are loosing the gherkin scenario in the report as you can see in my screenshots, so it is not really readable.
I haven't looked at the code, I don't think I am enough experienced in development to figure out this issue :/

**Comment by christian-bromann** [comment]
If you use Cucumber you should have `useCucumberStepReporter` set to true to have the step defintions reported.

**Comment by qvalero** [comment]
Yes I have, but now if you add also `cucumberOpts: scenarioLevelReporter: true`, we have an issue with allure report (see original issue).
We cannot have both option in the same run:

`useCucumberStepReporter:true` and `scenarioLevelReporter: true`

**Comment by michael-confiant** [comment]
> Yes I have, but now if you add also `cucumberOpts: scenarioLevelReporter: true`, we have an issue with allure report (see original issue).
> We cannot have both option in the same run:
> 
> `useCucumberStepReporter:true` and `scenarioLevelReporter: true`

Seems like that behavior is common for every reporter - when you set scenarioLevelReporter you don't have access to the steps. For me, a spec reporter also shows just scenario names after setting ```scenarioLevelReporter: true```

So when I have a scenario outline with 2 examples and another one simple scenario - both with 3 different steps - I get a report which I've attached as a screenshot
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/51997249/90329779-397db800-dfb0-11ea-81be-c5a5b41f6d8c.png">

@christian-bromann is that expected behavior and is there a possibility to pass steps to the reporter with scenarioLevelReporter set to true?

**Comment by christian-bromann** [comment]
> @christian-bromann is that an expected behavior and is there a possibility to pass steps to the reporter with scenarioLevelReporter being set to true?

Yes. See https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-cucumber-framework/src/reporter.js#L25-L29

**Comment by christian-bromann** [comment]
@michael-confiant it seems like

> `useCucumberStepReporter:true` and `scenarioLevelReporter: true`

would be the solution, no?

**Comment by christian-bromann** [comment]
If I run the example suite it properly prints out the scenario outlines:

```
 "spec" Reporter:
------------------------------------------------------------------
[chrome 85.0.4183.102 mac os x #0-0] Spec: /Users/christianbromann/Sites/WebdriverIO/webdriverio/examples/wdio/cucumber/features/my-feature.feature
[chrome 85.0.4183.102 mac os x #0-0] Running: chrome (v85.0.4183.102) on mac os x
[chrome 85.0.4183.102 mac os x #0-0] Session ID: 87874f8585a16f51047018743301ca7a
[chrome 85.0.4183.102 mac os x #0-0]
[chrome 85.0.4183.102 mac os x #0-0] Example feature
[chrome 85.0.4183.102 mac os x #0-0] As a user of WebdriverIO
[chrome 85.0.4183.102 mac os x #0-0] I should be able to use different commands
[chrome 85.0.4183.102 mac os x #0-0] to get informations about elements on the page
[chrome 85.0.4183.102 mac os x #0-0]
[chrome 85.0.4183.102 mac os x #0-0]     Get size of an element
[chrome 85.0.4183.102 mac os x #0-0]     As a user of WebdriverIO
[chrome 85.0.4183.102 mac os x #0-0]     I should be able to use different commands
[chrome 85.0.4183.102 mac os x #0-0]     to get informations about elements on the page
[chrome 85.0.4183.102 mac os x #0-0]
[chrome 85.0.4183.102 mac os x #0-0]        ✓ Given I go on the website "https://github.com/"
[chrome 85.0.4183.102 mac os x #0-0]        ✓ Then should the element ".header-logged-out a" be 32px wide and 35px high
[chrome 85.0.4183.102 mac os x #0-0]
[chrome 85.0.4183.102 mac os x #0-0]     Get title of website
[chrome 85.0.4183.102 mac os x #0-0]     As a user of WebdriverIO
[chrome 85.0.4183.102 mac os x #0-0]     I should be able to use different commands
[chrome 85.0.4183.102 mac os x #0-0]     to get informations about elements on the page
[chrome 85.0.4183.102 mac os x #0-0]
[chrome 85.0.4183.102 mac os x #0-0]        ✓ Given I go on the website "https://github.com/"
[chrome 85.0.4183.102 mac os x #0-0]        ✓ Then should the title of the page be "The world’s leading software development platform · GitHub"
[chrome 85.0.4183.102 mac os x #0-0]
[chrome 85.0.4183.102 mac os x #0-0]     Data Tables
[chrome 85.0.4183.102 mac os x #0-0]     As a user of WebdriverIO
[chrome 85.0.4183.102 mac os x #0-0]     I should be able to use different commands
[chrome 85.0.4183.102 mac os x #0-0]     to get informations about elements on the page
[chrome 85.0.4183.102 mac os x #0-0]
[chrome 85.0.4183.102 mac os x #0-0]        ✓ Given I go on the website "http://todomvc.com/examples/react/#/"
[chrome 85.0.4183.102 mac os x #0-0]        ✓ When I add the following grocieries
[chrome 85.0.4183.102 mac os x #0-0]          │ Item       │ Amount │
[chrome 85.0.4183.102 mac os x #0-0]          │ Milk       │ 2      │
[chrome 85.0.4183.102 mac os x #0-0]          │ Butter     │ 1      │
[chrome 85.0.4183.102 mac os x #0-0]          │ Noodles    │ 1      │
[chrome 85.0.4183.102 mac os x #0-0]          │ Schocolate │ 3      │
[chrome 85.0.4183.102 mac os x #0-0]        ✓ Then I should have a list of 4 items
[chrome 85.0.4183.102 mac os x #0-0]
[chrome 85.0.4183.102 mac os x #0-0] 7 passing (4s)


Spec Files:      1 passed, 1 total (100% completed) in 00:00:06
```

**Comment by qvalero** [comment]
HI @christian-bromann 
On my side using:

> useCucumberStepReporter:true and scenarioLevelReporter: true

will generate a report where steps are not displayed, only title of scenario.

For example:

`Feature: Landing

Scenario: SignIn
    Given I am on "landing" view
    When  I click on "sign in button"
    Then  I am on "sign in" view

Scenario: SignUp
    Given I am on "landing" view
    When  I click on "sign up button"
    Then  I am on "sign up tuto" view
`

Will generate report:

`[iPhone 11 iOS undefined #0-0] Spec: /Users/quentin.valero/e2e_mobileapp_tests/src/features/landing.feature
[iPhone 11 iOS undefined #0-0] Running: iPhone 11 on iOS undefined
[iPhone 11 iOS undefined #0-0] Session ID: 21dd900b-6806-493a-8d90-51365e901a3c
[iPhone 11 iOS undefined #0-0]
[iPhone 11 iOS undefined #0-0] Landing
[iPhone 11 iOS undefined #0-0]    ✓ SignIn
[iPhone 11 iOS undefined #0-0]    ✓ SignUp
[iPhone 11 iOS undefined #0-0]
[iPhone 11 iOS undefined #0-0] 2 passing (10.7s)


Spec Files:      1 passed, 1 total (100% completed) in 00:00:21 `

**Comment by christian-bromann** [comment]
@qvalero set `scenarioLevelReporter: false` in your cucumberOpts and you will see the steps as well.

**Comment by qvalero** [comment]
Yes yes I know but the question of @michael-confiant was: _is there a possibility to pass steps to the reporter with scenarioLevelReporter being set to true?_

**Comment by christian-bromann** [comment]
No. This is [handled by Cucumber](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-cucumber-framework/src/index.js#L36) and something we can't change. If you want to see steps within your report you have to have `scenarioLevelReporter` set to `false`.

**Comment by osmolyar** [comment]
With Allure reporter the issue is not that we can't see the steps but that no report is produced due to the error "allure-js-commons: Unexpected endStep(). There are no any steps running" (original issue)

Why can scenario-level retries not be used without scenarioLevelReporter set to true?

**Comment by BorisOsipov** [comment]
Please do test with actual repotrer version and feel free to reopen the issue
