### ISSUE TITLE
Uploading large files throws RangeError

### ISSUE THREAD

**Issue by AndreTheHunter** [webdriverio/webdriverio#539]
Uploading large (1.8G) file throws a RangeError:
```
RangeError: Attempt to allocate Buffer larger than maximum size: 0x3fffffff bytes
      at new Buffer (buffer.js:71:11)
      at Function.Buffer.concat (buffer.js:211:16)
      at _stream_readable.js:908:16
```
This seems to be caused by the Buffer allocating an array that's too large at https://github.com/webdriverio/webdriverio/blob/master/lib/commands/uploadFile.js#L41

**Comment by christian-bromann** [comment]
@AndreTheHunter after revisiting this issue more than 3 times I think there is nothing I can do in WebdriverIO to fix this. Closing.
