### ISSUE TITLE
Context of before/afterScenario @wdio/cucumber-framework hooks should be cucumber this

### ISSUE THREAD

**Issue by osmolyar** [webdriverio/webdriverio#5394]
**Is your feature request related to a problem? Please describe.**

In https://github.com/webdriverio/webdriverio/pull/4545, the context of the before/after Step hooks was changed to be the cucumber world object, as requested in https://github.com/webdriverio/webdriverio/issues/4248.  However this was not done for the before/afterScenario hooks.  The context of before/afterScenario @wdio/cucumber-framework hooks should be cucumber this because the intent of the cucumber world object is to share share among steps in a single scenario so it would make sense to initialize world attributes in beforeScenario.

**Describe the solution you'd like**
Make context of before/afterScenario @wdio/cucumber-framework hooks correspond to cucumber world/this object.

[edit]
**Reproducible Example**
Available at https://github.com/osmolyar/Reproducible-Example/

**Comment by erwinheitzman** [comment]
Please provide a reproducible example when creating issues

**Comment by christian-bromann** [comment]
@osmolyar would you like to take this on and propose a fix?

**Comment by osmolyar** [comment]
@christian-bromann , @erwinheitzman,  thanks; Ok I can plan to take this on.

**Comment by christian-bromann** [comment]
This was fixed by @osmolyar and can be closed now.
