### ISSUE TITLE
Failure in onPrepare does not stop execution

### ISSUE THREAD

**Issue by StephenEsser** [webdriverio/webdriverio#5398]
**Environment:**
 - **WebdriverIO version:** [6.1.11]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [v10.20.0]
 - **NPM version:** [6.14.4]
 - **Browser name and version:** [e.g. Chrome 68]
 - **Platform name and version:** [Mac OS Catalina]
 - **Additional wdio packages used (if applicable):** [Setup was done 1-1 using the [Getting Started Page](https://webdriver.io/docs/gettingstarted.html).]

**Config of WebdriverIO**

This project was generated using the steps on the [Getting Started Page](https://webdriver.io/docs/gettingstarted.html) and then adding an example custom service.

https://github.com/StephenEsser/wdio-custom-service/blob/master/wdio.conf.js

**Describe the bug**

A failure in the onPrepare lifecycle of a service does not stop the test runner execution.

**To Reproduce**

This can be reproduced with any service by throwing an error in the onPrepare hook. Providing an example project for step by step reproduction.

1. git clone https://github.com/StephenEsser/wdio-custom-service
2. cd wdio-custom-service
3. npx wdio wdio.conf.js

Observe the onPrepare hook fails, but does not stop the test runner from executing against the tests.

https://github.com/StephenEsser/wdio-custom-service

**Expected behavior**

If a service fails in the onPrepare hook the test run is not prepared to be executed. The test run and process should be terminated with a non-zero exit code. Currently, if a service fails in the onPrepare hook the test execution will attempt to continue. If the service failed to prepare, the testing stack is unstable/broken and should not attempt to continue.

**Log**

https://gist.github.com/StephenEsser/3cedc45fda813ffc3ab35a51271370c2

**Additional context**

I am working on integrating a custom service that initializes a docker swarm container. Similar in nature to the [wdio-docker-service](https://github.com/stsvilik/wdio-docker-service). If the swarm fails to initialize in the onPrepare hook the test runner should cease execution. 

I've added an example CustomService that throws an error in onPrepare.

https://github.com/StephenEsser/wdio-custom-service/blob/master/lib/wdio-example-service.js

**Comment by pmerwin** [comment]
FWIW, I am seeing any error thrown in a hook set at the config level, does not fail the test run either, and onComplete hook does not appear to run at all.  Could be related to this issue is why I mention it.

**Comment by StephenEsser** [comment]
That's a good point and helps simplify the test-case. Throwing an error directly in the `wdio.conf.js` onPrepare hook has the same outcome as an onPrepare in a service. The failure is logged, but the execution continues to attempt to run the tests.

**Comment by christian-bromann** [comment]
Not failing the test even though a hook in a service fails was a design choice so that broken code would not interfere with the test process. If e.g. a driver service fails to start the test will fail immediately anyway. Another example is if the Sauce service fails to report to Sauce because e.g. there is an incident, the tests should still pass but show error for failing reporting.

I think it is reasonable though that critical services should be able to stop the test process with a meaningful error. If you have a custom service that starts your application under test, it would be nicer to fail the test saying that the application couldn't start rather than start running e2e tests and have a bunch of them failing for various reason.

Please suggest how you would see an interface that allows to stop the process. Again: I don't think it is a good idea to kill the process if any of the hooks fail but maybe it makes sense for at least certain hooks like onPrepare or onComplete.

**Comment by dimkin-eu** [comment]
i think it must be configurable, as could cause false positives because of silently failed prepare and going in Volkswagen ( always green ) style :)

**Comment by christian-bromann** [comment]
> going in Volkswagen ( always green ) style :)

I don't think this is a correct analogy. A service should not contain any tests of some sort. It meant to setup your environment. If all services silently fail your test should fail as well since the expected state of the environment is invalid. If that is not the case your tests are bad.

On the contrary it would be super annoying if your 30min e2e test fail because a service trying to send data to a service had a network blip.

**Comment by dimkin-eu** [comment]
this is really the issue in https://github.com/webdriverio/webdriverio/issues/5396 - wdio tests are the separate stage in Jenkins, and due not staring tests, the stage is superfast and green and proceeding to next stage in CI/CD pipeline.
As a QA I'd even go for commenting out the stage, not having it always green, despite (not running) tests state.

**Comment by christian-bromann** [comment]
I am not sure how these are related and why this doesn't break the stage but it is independent from the fact that services don't let the test run fail.

**Comment by emilyrohrbough** [comment]
Would it be possible to [check if a specific error message was thrown](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-cli/src/utils.js) when the runServiceHook is executed?
For example the service could do:
```js
onPrepare() {
    throw new Error('Essential Service')
}
```
and the [onServiceHook](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-cli/src/utils.js) could check for that message
```diff
export async function runServiceHook (launcher, hookName, ...args) {
    try {
        return await Promise.all(launcher.map((service) => {
            if (typeof service[hookName] === 'function') {
                return service[hookName](...args)
            }
        }))
    } catch (e) {
+       if (e.message.includes('Essential Service') {
+           throw e;
+       }
        log.error(`A service failed in the '${hookName}' hook\n${e.stack}\n\nContinue...`)
    }
}
```

**Comment by StephenEsser** [comment]
> I think it is reasonable though that critical services should be able to stop the test process with a meaningful error.

I agree that services should be able to stop the test process. Specifically services within the `onPrepare` hook prior to starting the test run.

I've done some additional testing locally and I may have stumbled onto another issue. It appears that once a custom service fails in the onPrepare hook the other services are not initialized at all.

I've added additional services to the example project. If Service 1 fails in the `onPrepare` hook then `onPrepare` is never invoked at all for Service 2 or Service 3.

https://github.com/StephenEsser/wdio-custom-service

**Comment by emilyrohrbough** [comment]
@christian-bromann Have you been able to think of how you'd expect this to behave?

**Comment by christian-bromann** [comment]
> Have you been able to think of how you'd expect this to behave?

@emilyrohrbough your suggestion seams reasonable to me. I am not sure about the error message yet but that should be a minor detail. Can you take this on?

**Comment by emilyrohrbough** [comment]
@christian-bromann Yes no problem!

**Comment by emilyrohrbough** [comment]
@christian-bromann I've done some further investigation into the issues @StephenEsser as pointed out in this issue. There are two things at play here:

1. In regard to the intention for wdio to continue, even if a service fails. The `runServiceHook` used Promise.all which will fail fast if one of the promises are rejected / throw and error. This is preventing/bailing the same hook for any other services that has not yet completed its execution. Moving the try-catch from around the `runServiceHook` to around each service hook execution resolves this issue no problem.

2. I agree with your hesitation on the error message. Relying on consumers to throw an error with a specific message would be brittle and a bit hacky. An idea to solidify this concept is to allow a service to define whether or not a hook is essential like:
```js
class MyService {
  constructor(options = {}) {
    this.essentialHooks = ['onPrepare'];
  }
```
What are your thoughts on this? As @pmdartus, there are multiple hooks levels that will continue when the hook fails. However, depending on the intention of that hook, it could be crucial to the setup/tear down of the tests and affect the test results. Adding this config option would expand scope beyond the onPrepare service if we allows and array of hook names.

**Comment by christian-bromann** [comment]
@emilyrohrbough what do you think of exposing an error class from the WebdriverIO project that allows us to identify an essential error for that service, something like:

```js
import { SevereServiceError } from 'webdriverio';

export default class MyService {
  // ...
  onPrepare () {
    // ...
    if (error) {
       throw new SevereServiceError('Could not start, stopping test execution')
    }
    // ...
  }
}
```

I find this to be a bit more expressive.
