### ISSUE TITLE
Improve mobile commands

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#5399]
**Is your feature request related to a problem? Please describe.**
At [SauceCon](https://saucecon.com/) @martinfrancois has presented a talk on testing mobile apps on Android and iOS using a single test framework. As part of the presentation he released a [WebdriverIO utility pack](https://github.com/martinfrancois/wdio-mobile-utils) that helps with certain mobile use cases, like swiping or deeplinking.

**Describe the solution you'd like**
I think it makes sense to think about bringing this natively into WebdriverIO. The API already has a bunch of browser focused helper commands and there is no reason to not add also ones for mobile. Questions to answer are:

- does the package author (@martinfrancois) agree to move the code "in-house"
- the code is written in TypeScript while the WebdriverIO code base is not - in case we would embed the code how do we resolve this?
- who can take up this work?

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by erwinheitzman** [comment]
Sounds great Christian! I'm not sure how large the framework is but we could rewrite the files to js or we could transpile it to js and use that.

Do you happen to have a link to the project?

**Comment by christian-bromann** [comment]
Sorry, totally forgot the link: https://github.com/martinfrancois/wdio-mobile-utils

**Comment by martinfrancois** [comment]
I would be willing to contribute the code to WebdriverIO and would also take up the work. I don't think it should be a big effort to do so.

Considering typescript: would it also be an option to think about converting webdriverio into a typescript project? Of course, I would still transpile it to JS when building (just as I do in wdio-mobile-utils), but it would provide the advantage that there would be no need anymore to maintain separate typescript type definitions in the project, since they would already automatically be generated by typescript. Also, I can imagine it wouldn't be a big effort, since the migration could just start by renaming all files to `.ts` followed by a lazy migration of the codebase itself over time. What do you think?

**Comment by erwinheitzman** [comment]
I am all for moving to TypeScript @martinfrancois :)

**Comment by christian-bromann** [comment]
@martinfrancois after syncing with the @webdriverio/technical-steering-committee team there has been no objections to move to TypeScript. I would suggest as a first task that we need to setup TypeScript in this project properly so that we can transition over fluently.

Then I suggest to integrate the commands that already exist, e.g. `dismissAlert`. We need to find a way how to access protocol commands if we overwrite them. The command is currently already defined as protocol command. Now it needs to be implemented into WebdriverIO and make a switch for mobile vs. browser access.

Lastly we can add mobile missing, e.g. swiping etc.

**Comment by martinfrancois** [comment]
> @martinfrancois after syncing with the @webdriverio/technical-steering-committee team there has been no objections to move to TypeScript. I would suggest as a first task that we need to setup TypeScript in this project properly so that we can transition over fluently.

Sounds great, thanks! I agree with this approach. How should we track the progress there @christian-bromann, in a separate issue?

> Then I suggest to integrate the commands that already exist, e.g. `dismissAlert`. We need to find a way how to access protocol commands if we overwrite them. The command is currently already defined as protocol command. Now it needs to be implemented into WebdriverIO and make a switch for mobile vs. browser access.

Mhm, yes I see what you mean, here I could imagine different approaches:
- Easiest but least pretty solution would be to simply use something like `dismissMobileAlert`
- Turn the protocol command into a regular command and call the protocol command as a result
  - We could rename the command to something like `dismissDesktopAlert` and provide a method called `dismissAlert` which will use a switch internally to determine which command to use (mobile or desktop)
  - I'm not sure though if renaming the command would present a breaking change - as there would still be a method in place with the same signature I think it technically shouldn't, but I'm not sure if there's any other ways people use to access protocol commands directly in a different way?
- Introduce a possibility to define mobile alternatives of protocol commands
  - This may be useful for other cases as well, but may also introduce unnecessary complexity

Maybe anyone has any better ideas here.

**Comment by christian-bromann** [comment]
> How should we track the progress there @christian-bromann, in a separate issue?

Yes let's do that. I will create some issues.

> Maybe anyone has any better ideas here.

I would like to keep the command names as is (if possible) because it should be handled by WebdriverIO. Introducing breaking changes would be suboptimal as we just had major release. It should be possible to rename protocol commands when we create the WebdriverIO command structure and rename protocol commands so they start with an underscore. We have already done this for [`getWindowSize`](https://webdriver.io/docs/api/jsonwp.html#_getwindowsize) which was a JSOMWP command and got renamed to accommodate the new WebDriver command `getWindowRect`. So we created a new command that simply does the routing between different protocol commands:

```js
export default function getWindowSize() {
    const browser = getBrowserObject(this)

    if (!browser.isW3C) {
        return browser._getWindowSize()
    }
    return browser.getWindowRect()
}
```

It is important however that the functionality stays somewhat similar between original protocol command and WebdriverIO command.

@martinfrancois can you list all features that wdio-mobile-utils offers and we could start thinking about how we integrate them, e.g. how we extend the current selector method `$` and `$$` to integrate the mobile selector features etc. I will also create 2 issues to tackle a) setting up TypeScript in this project and b) allow to overwrite protocol commands while retain access to them. Since you have been working with TypeScript already in your project feel free to grab the first ticket right away.

**Comment by christian-bromann** [comment]
I looked over the utilities and would suggest to make the following enhancements:

- `swipe(from, to)` where parameters `from` and `to` are either pixels if > 1 or percentage otherwise - I doubt anyone wants swipe 1 pixel to the left so we could use this differentiation to have one command for both
- integrate `checkIfDisplayedWithScrollDown` into `isDisplayed`
- add new mobile commands for `swipeUp`, `swipeRight`, `swipeDown` and `swipeLeft` either by percentage if first parameter is a number or on element if its an element object
- integrate `acceptAlert`, `dismissAlert` and `getAlertText` into WebdriverIO (as described above) - maybe also have a mobile [`sendAlertText`](https://webdriver.io/docs/api/webdriver.html#sendalerttext)
- add new mobile command for `openDeeplink`

With the following commands I am not sure why they differ:

- `queryAppState` where you do `browser.execute('mobile: queryAppState', { bundleId: bundleId })` for iOS and `browser.queryAppState(appId)` in Android - isn't this something we could unify in Appium?
- same goes for `activateApp` and `queryAppState`

Is there a functionality I am missing?

**Comment by christian-bromann** [comment]
> * integrate `acceptAlert`, `dismissAlert` and `getAlertText` into WebdriverIO (as described above) - maybe also have a mobile [`sendAlertText`](https://webdriver.io/docs/api/webdriver.html#sendalerttext)

Actually I am wondering if we can't just integrate these into Appium.

**Comment by christian-bromann** [comment]
@martinfrancois we are making slowly progress with the TS conversion. We only need #5804 approved and merged. Then we can start working on [rewriting individual packages](https://github.com/webdriverio/webdriverio/projects/14). Interested in giving us a hand?

**Comment by martinfrancois** [comment]
@christian-bromann cool! Sure, I just saw the issues, I'll work on some :)

**Comment by christian-bromann** [comment]
@martinfrancois now as we moved to TypeScript, shall we move forward porting these commands over?

**Comment by christian-bromann** [comment]
Issues for this have been created: #6538 #6537 and #6536. If I missed anything from this proposal feel free to create a new issue.
