### ISSUE TITLE
Error "browser.setWindowRect is not a function" when trying to use @wdio/selenium-standalone-service

### ISSUE THREAD

**Issue by ivanixgames** [webdriverio/webdriverio#5400]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**

from package.json:
   "@wdio/cli": "^5.22.4",
    "@wdio/local-runner": "^5.22.4",
    "@wdio/mocha-framework": "^5.18.7",
    "@wdio/spec-reporter": "^5.22.4",
    "@wdio/static-server-service": "^5.16.10",
    "@wdio/sync": "^5.20.1",
    "@wdio/selenium-standalone-service": "5.16.10",
    "chai": "^4.2.0",
    "esm": "^3.2.25",
    "mocha-each": "^2.0.1",
    "wdio-image-comparison-service": "^1.12.2"

 - **If WDIO Testrunner, running sync
 - **Node.js version:** 12.6.3
 - **NPM version:** 6.14.4
 - **Browser name and version:** chrome 81.0
 - **Platform name Windows 10
 - ** @types/selenium-standalone*:**  6.15.0 (from yarn.lock)

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
get error when trying to use the browser.setWindowRect()

**To Reproduce**

[Include code or an example repository that can easily be set up]

**Expected behavior**
expect browser to work with out error as it did using wdio-chromedriver-service

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by ivanixgames** [comment]
In my wdio.conf.js I tried to log the props of 'browser'
it shows that setWindowRect is a boolean property with value of true instead of being a function:


[0-0] browser props:  Browser {
  sessionId: '8d34d7c0c7636f5da68c8c257f40741d',
  capabilities: {
    acceptInsecureCerts: false,
    acceptSslCerts: false,
    applicationCacheEnabled: false,
    browserConnectionEnabled: false,
    browserName: 'chrome',
    chrome: {
      chromedriverVersion: '2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a)',
      userDataDir: 'C:\\Users\\xxxx\\AppData\\Local\\Temp\\scoped_dir2496_31035'
    },
    cssSelectorsEnabled: true,
    databaseEnabled: false,
    'goog:chromeOptions': { debuggerAddress: 'localhost:49878' },
    handlesAlerts: true,
    hasTouchScreen: false,
    javascriptEnabled: true,
    locationContextEnabled: true,
    mobileEmulationEnabled: false,
    nativeEvents: true,
    networkConnectionEnabled: false,
    pageLoadStrategy: 'normal',
    platform: 'Windows NT',
    rotatable: false,
    setWindowRect: true,
    takesHeapSnapshot: true,
    takesScreenshot: true,
    unexpectedAlertBehaviour: '',
    version: '81.0.4044.138',
    webStorageEnabled: true,
    'webdriver.remote.sessionid': '8d34d7c0c7636f5da68c8c257f40741d'
  },
  addCommand: [Function],
  overwriteCommand: [Function],
  addLocatorStrategy: [Function],
  config: {
    hostname: '127.0.0.1',
    port: 4444,
    protocol: 'http',
    specs: [ './specs/**/*.js' ],
    suites: {},
    exclude: [],
    outputDir: undefined,
    logLevel: 'error',
    logLevels: {},
    excludeDriverLogs: [],
    baseUrl: 'http://localhost',
    bail: 0,
    waitforInterval: 500,
    waitforTimeout: 100000,
    framework: 'mocha',
    reporters: [ 'spec' ],
    maxInstances: 1,
    maxInstancesPerCapability: 100,
    filesToWatch: [ './specs/**/*.js' ],
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    execArgv: [ '-r', 'esm' ],
    runnerEnv: {},
    runner: 'local',
    featureFlags: { specFiltering: undefined },
    mochaOpts: { timeout: 999999999, ui: 'bdd' },
    jasmineNodeOpts: { defaultTimeoutInterval: 10000 },
    cucumberOpts: { timeout: 10000 },
    onPrepare: [],
    before: [ [Function: bound before], [Function: bound before] ],
    beforeSession: [],
    beforeSuite: [],
    beforeHook: [],
    beforeTest: [],
    beforeCommand: [],
    afterCommand: [],
    afterTest: [],
    afterHook: [],
    afterSuite: [],
    afterSession: [],
    after: [],
    onComplete: [],
    onReload: [],
    beforeFeature: [],
    beforeScenario: [],
    beforeStep: [],
    afterStep: [],
    afterScenario: [],
    afterFeature: [],
    path: '/wd/hub',
    services: [ 'static-server', [Array], [Array] ],
    staticServerFolders: [ [Object], [Object] ],
    staticServerPort: 3000,
    staticServerLog: '/tmp/staticServerLogs',
    _: [ 'desktop.conf.js' ],
    '$0': '..\\node_modules\\@wdio\\cli\\bin\\wdio.js',
    specFileRetryAttempts: 0,
    capabilities: { browserName: 'chrome', 'goog:chromeOptions': {} }
  }
}

**Comment by erwinheitzman** [comment]
`chromedriverVersion: '2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a)',` this version is your problem. Update your chromedriver, this is not an issue.

**Comment by ivanixgames** [comment]
@erwinheitzman   Thanks, Sorry the trouble, yes i just saw a message that selenium couldn't download the webdriver for the version 81.0.  This message only showed up after I upgraded all of webdriverio to 6.x.  I suspect selenium-standalone 6.15.0 was not compatible with webdriverio 5.x
