### ISSUE TITLE
this.skip() is not defined

### ISSUE THREAD

**Issue by flunderpero** [webdriverio/webdriverio#5407]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 6.1.3]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [12]

**Describe the bug**
Reading through the documentation and issues here, the following should work:
```
it("might skip", () => {
   if (!browser.execute(() => navigator.serviceWorker))) {
    this.skip()  // throws error!
  }
}
```
Basically we want to skip some tests based on the *actual* browser environment. We
do not want to simply return, but mark the tests as skipped so we are aware of whether a specific browser supports  a feature or not.

**Comment by BorisOsipov** [comment]
@flunderpero Arrow functions does not have a this of their own.

```
it("might skip", *function* (){
	....
	this.skip(
	...
```

**Comment by flunderpero** [comment]
Of course! Thank you!

This project really rocks.
