### ISSUE TITLE
Upgrade to `webdriverio@6` `getValue` now returns a string array instead of a pure string

### ISSUE THREAD

**Issue by ywangii** [webdriverio/webdriverio#5408]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.1.4
 - **Mode:** Both
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.16.0
 - **NPM version:** 6.13.1
 - **Browser name and version:** Chrome 81
 - **Platform name and version:** macOS

**Config of WebdriverIO**
```
{
  specs: [
    path.join(process.cwd(), 'test/ui/*.js'),
    path.join(process.cwd(), 'test/ui/**/*.js')
  ],
  maxInstancesPerCapability: 5,
  maxInstances: 10,
  capabilities: {
    chrome: {
      capabilities: {
        browserName: 'chrome'
      }
    },
    firefox: {
      capabilities: {
        browserName: 'firefox'
      }
    }
  },
  coloredLogs: true,
  bail: 0,
  waitforTimeout: 10000
  connectionRetryCount: 3,
  framework: 'mocha',
  mochaOpts: {
    ui: 'bdd',
    timeout: 400000
  }
}
```

**Describe the bug**
We are bumping wdio@4 to wdio@6 in our UI automation and `getValue()` API now returns a string array instead of a string now (with targeting #id which should be unique according to the doc here - https://webdriver.io/docs/api/element/getValue.html) which fails all of our related tests.

**To Reproduce**

This is how the failure looks like when calling the `getValue` API.

e.g. `$('#some_id').getValue()` for an <input type='tel'> it errors out something like:

```
assertation failure occured, assumed `[ '10' ]` to equal (===) `'10'`
```

**Expected behavior**

Expect the API returns a string `'10'` instead of `['10']`

Thanks for anyone that could help this out! 🙏

**Comment by christian-bromann** [comment]
You are using multiremote which returns the result of all commands as a string. If you set your capabilities to:

```js
  capabilities: [{
    chrome: {
      capabilities: {
        browserName: 'chrome'
      }
    },
    firefox: {
      capabilities: {
        browserName: 'firefox'
      }
    }
  }]
```

results are as expected.

**Comment by ywangii** [comment]
@christian-bromann Thanks this resolved my issue! Appreciate it!

```
  capabilities: [
      {
        browserName: 'chrome'
      },
      {
        browserName: 'firefox'
      }
   ]
```

Also would be awesome to have this doc - https://webdriver.io/docs/options.html#capabilities to be more specific since for each single capability (not multiremote) per browser it's object but the whole `capabilities` config is an array. The config actually can be either object array or object of objects (multiremote).

**Comment by christian-bromann** [comment]
Cheers! I will see how we can be more descriptive. Appreciate the feedback!
