### ISSUE TITLE
How to wait for an async function to return

### ISSUE THREAD

**Issue by sean-hill** [webdriverio/webdriverio#541]
Hey there,

I'd love to be able to do something like this

	client
		.init()
		.url('https://www.google.com')
		.waitAsync(function(waited){

			// Do some outside async function (like a DB call)
			perhapsADBCall(function(){
				waited()
			})

		})
		...
		.end()

So `end()` isn`t called until the `waited` function is returned. Is this possible already?

**Comment by sean-hill** [comment]
I think I can accomplish this with custom commands. Thanks!

**Comment by christian-bromann** [comment]
Currently you don't need that. Just execute commands and WebdriverIO automatically queues them up, for example:

```js
client
    .init()
    .url('https://www.google.com')
    .waitAsync(function(waited){

        client.getTitle(function() {
             console.log('A');
             
             client.getText('#element', function() {
                  console.log('B');
             });
        });

        client.getValue('#element', function() {
              console.log('D');
        });
    })
    .getTitle(function() {
         console.log('E');
     });
    ...
    .end()
```
outputs:
```
A
B
C
D
E
```

Of course if you do other async stuff like reading files, addCommand can help you out
