### ISSUE TITLE
Unable to change host or port name by passing in seleniumArgs

### ISSUE THREAD

**Issue by abdul-farhat** [webdriverio/webdriverio#5410]
- **WebdriverIO version:** 6.1.12
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v12.16.3
 - **NPM version:** 6.14.4
 - **Browser name and version:** Chrome 81
 - **Platform name and version:** Tested on Windows 10 and Debian based distros
 - **Additional wdio packages used (if applicable):** [@wdio/selenium-standalone service]

**Config of WebdriverIO**
```
export.config = {
    ...
    runner: 'local',
    hostname: '127.0.0.1',
    port: 5555,
    path: '/wd/hub',
   ...
    services: [
        ['selenium-standalone', {
            logPath: './temp',
            args: {
                version: "3.141.59",
                seleniumArgs: ['-host', '127.0.0.1','-port', '5555'],
                drivers: {
                    chrome: { version: "81.0.4044.138" },
                    firefox: { version: "0.26.0" }
                }
            },
        }]
    ]
   ...
}
```

**Describe the bug**
When passing in 'seleniumArgs' into 'args' the host address and port number is not changed for selenium-standalone. Always defaults to localhost:4444 regardless of host or port passed in.

Manually starting selenium-standalone as such:

```
npx selenium-standalone start --config=./selenium-webdriver-versions.json
```

works fine.

Where the selenium-webdriver-versions.json's content is to the likes of:

```
{
  "baseURL": "https://selenium-release.storage.googleapis.com",
  "version": "3.141.59",
  "seleniumArgs": ["-host","127.0.0.1","-port","5555"],
  "drivers": {
    "chrome": {
      "version": "81.0.4044.138",
      "arch": "x64",
      "baseURL": "https://chromedriver.storage.googleapis.com"
    },
    "firefox": {
      "version": "0.26.0"
    }
  }
```

**To Reproduce**
Pass in 'seleniumArgs' as shown above in the wdio config.

**Expected behavior**
When passing in 'seleniumArgs' into 'args' the selenium-standalone service should change accordingly.

**Log**
[https://gist.github.com/abdul-farhat/c593dc0fe7de2fec3252c8b613ea1d98](url)

**Comment by christian-bromann** [comment]
If you are using a custom port for the service (default is `4444`) you have to make sure to also define this in your capabilities:

```js
// wdio.conf.js
exports.config = {
  // ...
  capabilities: [{
    browserName: 'chrome',
    port: 5555
  }]
  // ...
```

I recommend to use the default port if possible so you wouldn't need to configure anything.
