### ISSUE TITLE
es6-promise Promises cause "TypeError: undefined is not a function"

### ISSUE THREAD

**Issue by AndreTheHunter** [webdriverio/webdriverio#542]
[ES6 promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) do not have a finally method. This causes a "TypeError: undefined is not a function" to be thrown at [PromiseHandler:102](https://github.com/webdriverio/webdriverio/blob/master/lib/utils/PromiseHandler.js#L102)

I created a test case in my branch and tested using [es6-promise](https://github.com/jakearchibald/es6-promise) and confirmed the error by running ```_SPEC=test/spec/functional/promises.js & npm run test-desktop```

[Have look at the test case on my fork](https://github.com/webdriverio/webdriverio/compare/master...AndreTheHunter:develop)

If I have time I'll try to fix it and create a pull request

**Comment by tnguyen14** [comment]
I ran into this recently as well.

**Comment by AndreTheHunter** [comment]
I'm happy to contribute to this. Shall I fork from master or just help v3?

**Comment by christian-bromann** [comment]
Awesome. Please contribute to the `v3` branch. Looking forward to your contribution!

**Comment by christian-bromann** [comment]
@AndreTheHunter apparently the `v3` version works with ES6 promises. Everything in `v2.x` are just "emulated" promises. `v3` will be out soon, in the mean time please use good old callbacks :wink: sorry that I have no immediate solution for you

**Comment by tnguyen14** [comment]
I think this issue should not be closed until `v3` is released. There's no easy way for me to test this until that is published.

**Comment by christian-bromann** [comment]
I won't release anything before `v3` as I don't want to spend time in something that is not really stable to get released. Sorry about that. Feel free to checkout the `v3` branch version. It is tested and stable (besides the wdio runner which is the only thing I am currently work before release).
