### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by wswebcreation** [webdriverio/webdriverio#5423]
**Environment (please complete the following information):**
 - **WebdriverIO version:** V6
 - **Mode:** Testtunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12
 - **NPM version:** 6
 - **Browser name and version:** -
 - **Platform name and version:** OSX
 - **Additional wdio packages used (if applicable):** see boilerplate

**Config of WebdriverIO**
See https://github.com/webdriverio/jasmine-boilerplate

**Describe the bug**
Lately I've seen a lot of issues with my local projects that when I install the dependencies and want to run my tests that I get this error

```log
➜  jasmine-boilerplate git:(master) ✗ npm test
> jasmine-boilerplate@1.0.0 test /Users/wimselles/Git/jasmine-boilerplate
> wdio wdio.sauce.conf.js

(node:33742) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at Object.<anonymous> (/Users/wimselles/Git/jasmine-boilerplate/node_modules/devtools/build/launcher.js:31:29)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/wimselles/Git/jasmine-boilerplate/node_modules/devtools/build/index.js:28:40)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
(node:33742) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:33742) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It doesn't matter which script I run, even when you do `npx wdio config` (for triggering a new config) results in this error

**To Reproduce**
- Clone the [jasmine-boilerplate](https://github.com/webdriverio/jasmine-boilerplate)
- do `npm install`
- do `npm t` or `npm run test:local`, both result in the same error

**Expected behavior**
Test will run

**Additional context**
It looks like something is wrong in the `package-lock.json` of for example the `jasmine-boilerplate`. If I remove that it and do the install it works, so that might be the workaround, but it is annoying. I don't know if more people have seen this

**Comment by christian-bromann** [comment]
The error was related to #5369 which can only be fixed by updating the dependencies. I believe the error was introduced by a breaking change in Puppeteer that was released as a patch.

**Comment by wswebcreation** [comment]
Thanks, then it's clear for me now 😉
