### ISSUE TITLE
@wdio/cucumber-framework doesn't report variables in dataTables from Scenarios Outline Examples

### ISSUE THREAD

**Issue by JuanRodriguezAbarca** [webdriverio/webdriverio#5434]
There is an issue which persists along wdio versions which is parsing variable values from Examples in Scenario Outline to the Json Reporter in data tables
 See the report:
![image](https://user-images.githubusercontent.com/11064158/82906134-15887880-9f65-11ea-8dd5-7dd2684e9128.png)
And the feature:
![image](https://user-images.githubusercontent.com/11064158/82905664-6f3c7300-9f64-11ea-9a23-3e36736ceb41.png)
![image](https://user-images.githubusercontent.com/11064158/82906451-90519380-9f65-11ea-8c4b-0dd233cd2a0b.png)

The execution is ok, the problem happens when parsing the variable. See the json report block:
```
"cells": [
                                            "<name>",
                                            "<description>",
                                            "<accountPlan>",
                                            "<API>",
                                            "<environment>",
                                            ""
                                        ],

```
Which is taken in the html as html nodes because the '<>; symbols

My npm dependencies:
"devDependencies": {
    "@babel/cli": "7.8.4",
    "@babel/core": "7.9.0",
    "@babel/preset-env": "^7.9.6",
    "@babel/register": "^7.7.0",
    "@wdio/cucumber-framework": "6.1.13",
    "@wdio/local-runner": "5.23.0",
    "@wdio/spec-reporter": "5.23.0",
    "@wdio/sync": "5.23.0",
    "chromedriver": "^83.0.0",
    "expect": "24.3.0",
    "expect-webdriverio": "0.2.0",
    "fs-extra": "^9.0.0",
    "geckodriver": "^1.19.1",
    "multiple-cucumber-html-reporter": "^1.16.2",
    "wdio-chromedriver-service": "5.0.2",
    "wdio-cucumberjs-json-reporter": "^2.0.0",
    "wdio-geckodriver-service": "^1.0.3",
    "winston": "^3.2.1",
    "yargs": "^15.3.1"

**Comment by christian-bromann** [comment]
Please report this issue in the [multiple-cucumber-html-reporter](https://github.com/wswebcreation/multiple-cucumber-html-reporter#readme) project, thanks!

**Comment by wswebcreation** [comment]
@JuanRodriguezAbarca , please report it here https://github.com/wswebcreation/wdio-cucumberjs-json-reporter and provide your JSON file in that ticket

**Comment by JuanRodriguezAbarca** [comment]
Thanks

**Comment by JuanRodriguezAbarca** [comment]
Hi, now I'm doubting where the error comes from as I was sent here back... 
The JSON fragment corresponding with this step is the following:
`{
	"arguments": [
		{
			"rows": [
				{
					"cells": [
						"name",
						"description",
						"accountPlan",
						"API",
						"environment",
						"apps"
					],
					"locations": [
						{
							"line": 13,
							"column": 21
						},
						{
							"line": 13,
							"column": 30
						},
						{
							"line": 13,
							"column": 46
						},
						{
							"line": 13,
							"column": 62
						},
						{
							"line": 13,
							"column": 70
						},
						{
							"line": 13,
							"column": 86
						}
					]
				},
				{
					"cells": [
						"<name>",
						"<description>",
						"<accountPlan>",
						"<API>",
						"<environment>",
						""
					],
					"locations": [
						{
							"line": 14,
							"column": 21
						},
						{
							"line": 14,
							"column": 30
						},
						{
							"line": 14,
							"column": 46
						},
						{
							"line": 14,
							"column": 62
						},
						{
							"line": 14,
							"column": 70
						},
						{
							"line": 14,
							"column": 91
						}
					]
				}
			]
		}
	],
	"keyword": "Given",
	"name": "existing organization with following data",
	"result": {
		"status": "passed",
		"duration": 7000000
	},
	"line": 12,
	"match": {
		"location": "can not be determined with webdriver.io"
	}
}`

**Comment by wswebcreation** [comment]
@JuanRodriguezAbarca 

Sorry for not being clear about it. I'm the maintainer of both reporting modules. Please file a ticket here https://github.com/wswebcreation/wdio-cucumberjs-json-reporter because that module is used to create the JSON-file. also please add the complete JSON file that doesn't show the data

Reason for asking is that I've ran some test with the module and this feature file

```
Feature: Google

  Background: When I do nothing
    Given This is doing nothing because it's a background

  Scenario: Google open
    Given I open Google
    When I attach data
    Then I can take a screenshot

  Scenario Outline: Google outline <time>
    Given I open Google for the <time> time

    Examples:
      | time   |
      | first  |
      | second |

  Scenario: A pending step
    Given I am a pending step

  Scenario: A failed step
    Given I am a failed step

  Scenario: inline table example
    Given I am a inline table step
      | name | last |
      | John | Doe  |
```

Results in this report

![image](https://user-images.githubusercontent.com/11979740/82922679-34453a00-9f7a-11ea-97ee-de1f86ecdf41.png)
![image](https://user-images.githubusercontent.com/11979740/82922718-40c99280-9f7a-11ea-8acb-0ff43e962e9b.png)
![image](https://user-images.githubusercontent.com/11979740/82922748-4921cd80-9f7a-11ea-9ba8-e351a3b78a00.png)

**Comment by JuanRodriguezAbarca** [comment]
> @JuanRodriguezAbarca
> 
> Sorry for not being clear about it. I'm the maintainer of both reporting modules. Please file a ticket here https://github.com/wswebcreation/wdio-cucumberjs-json-reporter because that module is used to create the JSON-file. also please add the complete JSON file that doesn't show the data
> 
> Reason for asking is that I've ran some test with the module and this feature file
> 
> ```
> Feature: Google
> 
>   Background: When I do nothing
>     Given This is doing nothing because it's a background
> 
>   Scenario: Google open
>     Given I open Google
>     When I attach data
>     Then I can take a screenshot
> 
>   Scenario Outline: Google outline <time>
>     Given I open Google for the <time> time
> 
>     Examples:
>       | time   |
>       | first  |
>       | second |
> 
>   Scenario: A pending step
>     Given I am a pending step
> 
>   Scenario: A failed step
>     Given I am a failed step
> 
>   Scenario: inline table example
>     Given I am a inline table step
>       | name | last |
>       | John | Doe  |
> ```
> 
> Results in this report
> 
> ![image](https://user-images.githubusercontent.com/11979740/82922679-34453a00-9f7a-11ea-97ee-de1f86ecdf41.png)
> ![image](https://user-images.githubusercontent.com/11979740/82922718-40c99280-9f7a-11ea-8acb-0ff43e962e9b.png)
> ![image](https://user-images.githubusercontent.com/11979740/82922748-4921cd80-9f7a-11ea-9ba8-e351a3b78a00.png)

I will open in the correct project, thanks for the info and sorry for the missunderstanding. By the way, there is one kind of scenario which was not taken in care in this list:
This scenario is a combination of a data table in a step and an scenario outline

  Scenario Outline: Google outline <time>
    Given I open Google for the time
        |time|weather|
        |<time>|<wheather>|

    Examples:
      | time      |wheather|
      | first       |  cold      |
      | second |  warm     |

**Comment by JuanRodriguezAbarca** [comment]
Here is the link to the ticket in the correct project
https://github.com/wswebcreation/wdio-cucumberjs-json-reporter/issues/36

**Comment by wswebcreation** [comment]
@christian-bromann 

Reopening this issue because this is an issue in `@wdio/cucumber-framework` or even Cucumber. The data that is being passed to the reporter, when a step succeeds, is this

```json
   {
        "type": "test",
        "start": "2020-05-27T06:52:00.562Z",
        "_duration": 2,
        "uid": "I am a inline table step with examples for the first time31",
        "cid": "0-0",
        "title": "Given I am a inline table step with examples for the first time",
        "fullTitle": "Google: Google outline inline table <time>: Given I am a inline table step with examples for the first time",
        "output": [],
        "argument": {
            "rows": [{
                "cells": ["time", "weather"],
                "locations": [{"line": 32, "column": 9}, {"line": 32, "column": 18}]
            }, {
                "cells": ["<time>", "<wheather>"],
                "locations": [{"line": 33, "column": 9}, {"line": 33, "column": 18}]
            }]
        },
        "state": "passed",
        "end": "2020-05-27T06:52:00.564Z"
    }
```

Here you will see that the inline table data (` "cells": ["<time>", "<wheather>"],`) is not being processed to the logs by or cucumber or the `@wdio/cucumber-framework`.

I'll try to debug it more when I have time.

@JuanRodriguezAbarca 

Sorry for ping ponging you from project to project

**Comment by wswebcreation** [comment]
@christian-bromann 

I've did some digging, and it looks like this is a third party issue, meaning something in Cucumber itself. The data that is being passed to the `handleAfterStep` in the `@wdio/cucumber-framework/lib/reporter.js` is also containing the incorrect data, see below

```json
    {
        "type": "Step",
        "location": {"line": 31, "column": 5},
        "keyword": "Given ",
        "text": "I am a inline table step with examples for the second time",
        "argument": {
            "type": "DataTable",
            "location": {"line": 32, "column": 7},
            "rows": [{
                "type": "TableRow",
                "location": {"line": 32, "column": 7},
                "cells": [{
                    "type": "TableCell",
                    "location": {"line": 32, "column": 9},
                    "value": "time"
                }, {"type": "TableCell", "location": {"line": 32, "column": 18}, "value": "weather"}]
            }, {
                "type": "TableRow",
                "location": {"line": 33, "column": 7},
                "cells": [{
                    "type": "TableCell",
                    "location": {"line": 33, "column": 9},
                    "value": "<time>"
                }, {"type": "TableCell", "location": {"line": 33, "column": 18}, "value": "<wheather>"}]
            }]
        }
    }
```

Not sure how to debug this more

**Comment by JuanRodriguezAbarca** [comment]
Thank you for taking this in consideration.
What would be the next steps?

**Comment by christian-bromann** [comment]
> What would be the next steps?

Feel free to help us investigate.

**Comment by Ravikishore543** [comment]
`After` hook in cucumber is returning the parsed inline table data for every step

Feature:
```
Feature: Sample test

    Scenario Outline:  Opening for the <time> time
    Given I open the url "<time>"
      |time|weather|
      |<time>|<weather>|

  Examples:
    | time      |weather|
    | first       |  cold      |
    | second       |  warm      |
```

Cucumber After Hook:
`Cucumber.After (scenario => console.log(JSON.stringify (scenario,null, 2)));`

Output:
```
"sourceLocation": {
    "uri": "src/features/sampleTest.feature",
    "line": 10
  },
  "pickle": {
    "name": "Opening for the first time",
    "language": "en",
    "steps": [
      {
        "text": "I open the url \"first\"",
        "arguments": [
          {
            "rows": [
              {
                "cells": [
                  {
                    "location": {
                      "line": 5,
                      "column": 8
                    },
                    "value": "time"
                  },
                  {
                    "location": {
                      "line": 5,
                      "column": 13
                    },
                    "value": "weather"
                  }
                ]
              },
              {
                "cells": [
                  {
                    "location": {
                      "line": 6,
                      "column": 8
                    },
                    "value": "first"
                  },
                  {
                    "location": {
                      "line": 6,
                      "column": 15
                    },
                    "value": "cold"
                  }
                ]
              }
            ]
          }
        ],
        "locations": [
          {
            "line": 10,
            "column": 5
          },
          {
            "line": 4,
            "column": 11
          }
        ]
      }
    ],
    "tags": [],
    "locations": [
      {
        "line": 10,
        "column": 5
      },
      {
        "line": 3,
        "column": 5
      }
    ]
  },
  "result": {
    "duration": 477000000,
    "status": "passed"
  }
}
```

```
"sourceLocation": {
    "uri": "src/features/sampleTest.feature",
    "line": 11
  },
  "pickle": {
    "name": "Opening for the second time",
    "language": "en",
    "steps": [
      {
        "text": "I open the url \"second\"",
        "arguments": [
          {
            "rows": [
              {
                "cells": [
                  {
                    "location": {
                      "line": 5,
                      "column": 8
                    },
                    "value": "time"
                  },
                  {
                    "location": {
                      "line": 5,
                      "column": 13
                    },
                    "value": "weather"
                  }
                ]
              },
              {
                "cells": [
                  {
                    "location": {
                      "line": 6,
                      "column": 8
                    },
                    "value": "second"
                  },
                  {
                    "location": {
                      "line": 6,
                      "column": 15
                    },
                    "value": "warm"
                  }
                ]
              }
            ]
          }
        ],
        "locations": [
          {
            "line": 11,
            "column": 5
          },
          {
            "line": 4,
            "column": 11
          }
        ]
      }
    ],
    "tags": [],
    "locations": [
      {
        "line": 11,
        "column": 5
      },
      {
        "line": 3,
        "column": 5
      }
    ]
  },
  "result": {
    "duration": 40000000,
    "status": "passed"
  }
}
```

Cucumber.js hook is returning the parsed values in `pickle` attribute, it might be an issue with `@wdio/cucumber-framework`
>

**Comment by christian-bromann** [comment]
Could be maybe somewhere [here](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-cucumber-framework/src/cucumberEventListener.js#L70-L102).

**Comment by wswebcreation** [comment]
@christian-bromann 

I think I found the problem, but don't know how to solve it right away. I think the problem is in here https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-cucumber-framework/src/utils.js#L230

This is where the step text is determined, this is the step data

```json
` {
        "type": "Step",
        "location": {"line": 31, "column": 5},
        "keyword": "Given ",
        "text": "I am a inline table step with examples for the <time> time",
        "argument": {
            "type": "DataTable",
            "location": {"line": 32, "column": 7},
            "rows": [{
                "type": "TableRow",
                "location": {"line": 32, "column": 7},
                "cells": [{
                    "type": "TableCell",
                    "location": {"line": 32, "column": 9},
                    "value": "time"
                }, {"type": "TableCell", "location": {"line": 32, "column": 18}, "value": "weather"}]
            }, {
                "type": "TableRow",
                "location": {"line": 33, "column": 7},
                "cells": [{
                    "type": "TableCell",
                    "location": {"line": 33, "column": 9},
                    "value": "<time>"
                }, {"type": "TableCell", "location": {"line": 33, "column": 18}, "value": "<wheather>"}]
            }]
        }
    }
```

and this is the pickle data

```json
{
        "name": "Google outline inline table first",
        "language": "en",
        "steps": [{
            "text": "I am a inline table step with examples for the first time",
            "arguments": [{
                "rows": [{
                    "cells": [{
                        "location": {"line": 32, "column": 9},
                        "value": "time"
                    }, {"location": {"line": 32, "column": 18}, "value": "weather"}]
                }, {
                    "cells": [{"location": {"line": 33, "column": 9}, "value": "first"}, {
                        "location": {
                            "line": 33,
                            "column": 18
                        }, "value": "cold"
                    }]
                }]
            }],
            "locations": [{"line": 37, "column": 7}, {"line": 31, "column": 11}]
        }],
        "tags": [],
        "locations": [{"line": 37, "column": 7}, {"line": 30, "column": 3}]
    }
```

The pickle holds the correct data here, because it has the processed data from CucumberJS, but I don't know why the data needs to pick the stepdata here

**Comment by mgrybyk** [comment]
@wswebcreation might be. I think we get text data somewhere before, when parsing data table.
Are you going to fix this one @wswebcreation ?

**Comment by wswebcreation** [comment]
@mgrybyk 

You mention _maybe_ here, what do you mean with that?

**Comment by mgrybyk** [comment]
Nothing specific, I just haven't tried to debug the issue myself

**Comment by wswebcreation** [comment]
I've debugged it from the event listeners to this specific utility and 100% sure that this is the problem. Challenge now is that I'm not sure why this solution has been choosen, I can just fix it by returning the pickle step, because that should (always) hold the processed data, but I'm a little but scared what might brake otherwise
I also don't understand why the report hook is getting the wrong stepdata but the afterhook is getting the correct stepdata, do you have an idea?

**Comment by mgrybyk** [comment]
Might be that we send wrong data in the report hook. Don't have any clues at this point, the best way to understand what is going on is to debug :)

**Comment by Ravikishore543** [comment]
@wswebcreation  [getStepText](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-cucumber-framework/src/utils.js#L230) method will only parse the data present in the step text (ex. Then User `<userId>` with `<password>` is logged in), as you can see in the method it'll return only `step.text/pickle.text`, our issue is with parsing the data in data tables.

**Comment by wswebcreation** [comment]
ahh, shit, it's almost weekend... 🤦

**Comment by christian-bromann** [comment]
> but I'm a little but scared what might brake otherwise

What is broken already can not be breaking again 😉 ... this is why we have the smoke test framework - we can write a custom reporter that just logs things it receives and we can snapshot this to ensure before and after changes make sense.

**Comment by mgrybyk** [comment]
I know what is the root cause of the issue.
It is `getTestCaseSteps` function that ignores pickle data (at least for arguments).

**Comment by mgrybyk** [comment]
I've raised the PR that should give an idea on how to to fix the issue.

Even though "it works" the code doesn't look well and can be optimized :)

Here is the test data I used:

Feature file
```
Feature: Scenarios Outline Variables

    Scenario Outline: whatever
    Given Time <time> and Weather <weather> are passed
        | time      | weather   |
        | <time>    | <weather> |

    Examples:
        | time      | weather   |
        | first1    | cold1     |
        | second1   | warm1     |

    Examples:
        | time      | weather   |
        | first22   | cold22    |
        | second22  | warm22    |
```

step definition
```
Given(/^Time (.*) and Weather (.*) are passed$/, function (t, w, table) {
    console.log(t, w);
});
```

how it looks now
![image](https://user-images.githubusercontent.com/25589559/83310105-438ee680-a20b-11ea-8ef6-33eef1fa621f.png)


I'll try to complete it on Sunday, otherwise feel free to pick it up because I don't have free time next week :(

**Comment by wswebcreation** [comment]
@mgrybyk 

Already tested it with my report and it works 🎉

**Comment by christian-bromann** [comment]
Let's continue convo in #5448
