### ISSUE TITLE
Allow multiple instances per browser

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#544]
Ultimately users should be able to run each spec with a different instance to speed up test execution.

**Comment by christian-bromann** [comment]
moving this to 3.1 release as it nothing that would block releasing v3.0

**Comment by alexpts** [comment]
+1

**Comment by antipodeman** [comment]
+1

**Comment by rskvazh** [comment]
+1

**Comment by mike-suggitt** [comment]
@christian-bromann Would you be able to clarify the relationship between capabilities, multiremote and parallel execution? Reading the usecase behind multieremote i'd be a bit worried about having so much shared logic in every class e.g.

```javascript
if (!isMultiremote && !runSpecs()) {
            return
        }
```
Given that this is, arguably, a minority usecase wouldn't it be better to abstract it out into more of a 'runningMode' type abstraction? I may have misunderstood some things here thought. I'd welcome your thoughts.

**Comment by christian-bromann** [comment]
We have improved the way how we handle multiple session in the wdio testrunner so that we maxed out the capabilities in running tests concurrently. For example: if you have 3 capabilities defined and 5 different spec files and you haven't limited the number of instances (using the `maxInstances` property), the wdio test runner will spawn 15 selenium sessions at the same time. `maxInstances` allows you to limit the concurrency globally or per capability.

The multiremote feature is not meant for parallelization. It helps you to build complex tests where more than one browser are required (e.g. if you are testing a chat or webrtc app or any other communication app). Instead of one browser you can control multiple browser and execute different actions with them. If you guys still have question, find me in the Gitter chat room.
