### ISSUE TITLE
Firefox-profile service Browserstack

### ISSUE THREAD

**Issue by javiergarciacotado** [webdriverio/webdriverio#5441]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [6.1.12]
 - **Mode:** [testrunner]
 - **If WDIO Testrunner, running sync/async:** [async]
 - **Node.js version:** [v12.16.2]
 - **NPM version:** [6.14.4]
 - **Browser name and version:** [Firefox 68]
 - **Platform name and version:** [Browserstack, Windows10]
 - **Additional wdio packages used (if applicable):** [@wdio/firefox-profile-service]

**Config of WebdriverIO**

const browserstack = require('browserstack-local');
const merge = require('deepmerge');
const fs = require('fs');
const path = require('path');
const wdioConf = require('../wdio.conf.js');

exports.config = merge(
  wdioConf.config,
  {
    host: 'hub.browserstack.com',

    user: process.env.BROWSERSTACK_USERNAME || 'BROWSERSTACK_USERNAME',
    key: process.env.BROWSERSTACK_ACCESS_KEY || 'BROWSERSTACK_ACC_KEY',

    capabilities: [
      {
        os: 'Windows',
        os_version: '10',
        browserName: 'Firefox',
        browser_version: '68.0',
        resolution: '1920x1080',
        project: 'Infinity',
        build: `UI-${require('uuid').v1()}`, //to identify build @browserstack
        'browserstack.local': 'true',
        'browserstack.debug': 'true',
        'browserstack.networkLogs': 'true',
        'browserstack.timezone': 'Madrid',
      },
    ],

    services: [
      [
        'firefox-profile',
        {
          extensions: ['./config/browsers/plugin/firefox/'],
          'xpinstall.signatures.required': false,
        },
      ],
    ],

    // Code to start browserstack local before start of test
    onPrepare: function (config, capabilities) {
      require('dotenv').config();
      const outputDir = path.join(__dirname, '../../..', 'dist/browserstack');
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir);
      }
      console.log('Connecting local');
      return new Promise(function (resolve, reject) {
        exports.bs_local = new browserstack.Local();
        exports.bs_local.start(
          {
            key: process.env.BROWSERSTACK_ACCESS_KEY,
            logFile: outputDir + '/output.log',
          },
          function (error) {
            if (error) return reject(error);
            console.log('Connected. Now testing...');
            resolve();
          },
        );
      });
    },
    afterTest: function (test, context, { error, result, duration, passed, retries }) {
      require('axios')
        .put(
          `https://api.browserstack.com/automate/sessions/${browser.sessionId}.json`,
          { name: `${test.title}-${browser.capabilities.browserName}-test` },
          {
            auth: {
              username: process.env.BROWSERSTACK_USERNAME,
              password: process.env.BROWSERSTACK_ACCESS_KEY,
            },
          },
        )
        .then((browserstackResponse) => console.log(browserstackResponse.status))
        .catch((error) => console.error(error));
    },
    onComplete: function (exitCode, config, capabilities, results) {
      exports.bs_local.stop();
    },
  },
  { clone: false },
);

**Describe the bug**
It does not inject the 'moz:firefoxOptions': { profile: '...' } as happens locally (agains Selenoid). Thus, Browserstack service does not enable Firefox browser with the addon I'm interested in.

**To Reproduce**

1. Create a Browserstack free account
2. Create a sample project based on Mocha.
3. Copy above wdio config and name it i.e: wdio.conf.firefox.js
    3.1. Provide env variables BROWSERSTACK_USERNAME and BROWSERSTACK_ACCESS_KEY
3. Add in your package.json ie:
    "test:firefox:browserstack": "npx wdio run config/webdriverio/browserstack/wdio.conf.firefox.js"
    
**Expected behavior**
Load Firefox remotely (I mean, through cloud provider) with extension enabled.

**Comment by erwinheitzman** [comment]
For browserstack you'll need to provide the extention in base64 format.

Reference: https://www.browserstack.com/automate/add-plugins-extensions-remote-browsers

**Comment by javiergarciacotado** [comment]
Hi @erwinheitzman,

Indeed, I have no problem with the Chrome's extension in Browserstack...
The issue is with firefox-profile which works smoothly against Selenoid but it doesn't inject the 'moz:firefoxOptions' when I'm trying to run with in Browserstack.

**Comment by javiergarciacotado** [comment]
Hello,

I have solved current issue accessing directly to firefox-profile (not through wdio-firefox-profile):

onPrepare: function (config, capabilities) {
      require('dotenv').config();
      const outputDir = path.join(__dirname, 'dist/browserstack');
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir);
      }
      console.log('Connecting local');
      return new Promise((resolve, reject) => {
        exports.browserstack = new browserstack.Local();
        exports.browserstack.start(
          {
            key: process.env.BROWSERSTACK_ACCESS_KEY,
            logFile: outputDir + '/output.log',
          },
          (error) => {
            if (error) return reject(error);
            console.log('Connected. Now testing...');
            resolve();
          },
        );
      }).then(() => {
        const firefoxProfile = new FirefoxProfile({
          destinationDirectory: './config/browsers/firefox',
          'xpinstall.signatures.required': false,
        });

        const encodedProfile = require('util')
          .promisify(firefoxProfile.encoded)
          .bind(firefoxProfile)();

        return encodedProfile.then((profile) => {
          capabilities[0]['moz:firefoxOptions'] = {
            profile: profile,
          };
        });
      });
    }

I don't know if you prefer to close it or leave it open as wdio-firefox-profile does not work as expected.

**Comment by christian-bromann** [comment]
I am not sure how your code is different from what the service is doing. I checked manually and settings are applied correctly. Therefor closing this issue. Happy to reopen if someone can provide a reproducible example.
