### ISSUE TITLE
Test is skipped when including break command

### ISSUE THREAD

**Issue by LucianStoicescu** [webdriverio/webdriverio#5453]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 6.1.11]
 - **Mode:** [Standalone]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [12.13.1]
 - **NPM version:** [6.14.5]
 - **Browser name and version:** [Chrome 81]
 - **Platform name and version:** [OS X Catalina 10.15.5]
 - **Additional wdio packages used (if applicable):** [@wdio/spec reporter, @wdio/dot reporter, @jasmine framework ]

**Config of WebdriverIO**
const defaultTimeoutInterval = 60000;
const debug = process.env.DEBUG;
exports.config = {
  port: 9515,
...
specs: ["./tests/browser/**/checkout_paypal_nightly.js"],
  // Patterns to exclude.
  exclude: [
    // 'path/to/excluded/files'
    "./tests/browser/helper/*",
    "./tests/browser/login/login.js",
    "./tests/browser/myaccount/reviews.js"
  ]
...
capabilities: [
    {
      // maxInstances can get overwritten per capability. So if you have an in-house Selenium
      // grid with only 5 firefox instances available you can make sure that not more than
      // 5 instances get started at a time.
      maxInstances: 4,
      //
      browserName: "chrome",
      "goog:chromeOptions": {
        args:
          process.env.CI == "true"
            ? ["--headless", "--disable-gpu", "--window-size=1920,1080"]
            : []
      }
    }
  ]
...
**Describe the bug**
Tried to add a break to a for loop and got the whole test skipped - I triple-checked, it's just the break; that causes this behavior. I've set the logging to trace but it's just start -> stop and nothing to indicate the reason for the skip
**To Reproduce**
Steps to reproduce the behavior (note that the position of the break is irrelevant):

 const iFrames = browser.$$("//iframe");
    iFrames.forEach(element => {
      try {
        browser.switchToFrame(element);
        const pal = $("//*[contains(@class,'paypal-button-container')]");
        pal.waitForClickable();
        pal.click();
        break;
      } catch (error) {}
      
    });

**Expected behavior**
Being able to use break in a test

**Log**
Execution of 1 spec files started at 2020-06-01T22:41:41.384Z

2020-06-01T22:41:41.386Z DEBUG @wdio/utils:initialiseServices: initialise service "chromedriver" as NPM package
2020-06-01T22:41:41.395Z INFO @wdio/cli:launcher: Run onPrepare hook
Starting ChromeDriver 80.0.3987.16 (320f6526c1632ad4f205ebce69b99a062ed78647-refs/branch-heads/3987@{#185}) on port 9515
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
2020-06-01T22:41:41.515Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2020-06-01T22:41:41.518Z INFO @wdio/local-runner: Start worker 0-0 with arg: wdio.conf_n.js
[0-0] 2020-06-01T22:41:41.767Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2020-06-01T22:41:41.771Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2020-06-01T22:41:41.772Z INFO webdriverio: Initiate new session using the ./protocol-stub protocol
2020-06-01T22:41:41.928Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 0
2020-06-01T22:41:41.929Z INFO @wdio/cli: [0-0] SKIPPED in chrome - /tests/browser/checkout/checkout_paypal_nightly.js
2020-06-01T22:41:41.930Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 skipped, 1 total (100% completed) in 00:00:00 

2020-06-01T22:41:41.930Z INFO @wdio/local-runner: Shutting down spawned worker
2020-06-01T22:41:42.182Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2020-06-01T22:41:42.183Z INFO @wdio/local-runner: shutting down

**Comment by mgrybyk** [comment]
There is no builtin `break` in forEach in JavaScript.

What are you trying to achieve @LucianStoicescu ?

**Comment by LucianStoicescu** [comment]
Aw man, I expected it to be something silly like that. I was just trying to stop the for after it found the appropriate iFrame - which I did with a trigger variable eventually.
So, why does this cause the test to be skipped? I would've expected an error or something

**Comment by christian-bromann** [comment]
Not sure but this fails for me with `Illegal break statement`.
