### ISSUE TITLE
Getting undefined / Null error from Vanilla update 

### ISSUE THREAD

**Issue by lieutenantken** [webdriverio/webdriverio#5457]
### **//SOLUTION!!!!** 
**// UPDATE Dependency to 3.3.0 as seen below** 
**//FILE:: node_modules/devtools/package.json**
"dependencies": {
    "@wdio/config": "6.1.14",
    "@wdio/logger": "6.0.16",
    "@wdio/protocols": "6.1.14",
    "@wdio/utils": "6.1.8",
    "chrome-launcher": "^0.13.1",
    "puppeteer-core": "^3.3.0",
    "ua-parser-js": "^0.7.21",
    "uuid": "^8.0.0"
  },
  "devDependencies": {
    "@types/puppeteer": "^3.3.0"

**//WHY::**
https://diff.intrinsic.com/puppeteer/1.12.2/1.15.0  
https://github.com/puppeteer/puppeteer/pull/5603/files

**//FROM::**
node_modules/devtools/build/launcher.json
const log = (0, _logger.default)('devtools');
const DEVICE_NAMES = Object.values(_DeviceDescriptors.devicesMap).map(device => device.name);

**### //MESSAGE:: ERROR::** 
(node:23605) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
(node:23605) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at Object.<anonymous> (/Users/Projects/Company/node_modules/devtools/build/launcher.js:31:29)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/Projects/Company/node_modules/devtools/build/index.js:28:40)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
(node:23605) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23605) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**// IGNORE PREFILL TEXT** 
//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2]
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:** [e.g. 8.11.2]
 - **NPM version:** [e.g. 5.8.0]
 - **Browser name and version:** [e.g. Chrome 68]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Comment by christian-bromann** [comment]
This has been fixed by #5369. Please update all your dependencies. Cheers!

**Comment by lieutenantken** [comment]
The bug was written against 6.1.16 ! Im surprised you do not have more reports. The code changes in #5369 do not address the possibility of a null or undefined {devicemap}. Besides the update provided. This page referred to requires a try/catch as it appears puppeteer propensity to removing/moving & emptying this seemingly critical yet somewhat meaningless file.  
   The bigger question : Can we inject these dependencies on a more optional basis and decouple the severity of cascading failures and stale nested libraries !

**Comment by christian-bromann** [comment]
> The bug was written against 6.1.16 !

Oh, ok - because you mentioned in your issue to have `WebdriverIO version: [e.g. 4.13.2]`

> do not address the possibility of a null or undefined {devicemap}

This object will always be exposed by Puppeteer. Removing it would be need to go along with a major version bump. I assume this was not caught by the Puppeteer team during their rewrite to TypeScript. I am not concerned that this can happen again.
