### ISSUE TITLE
dragAndDrop doesn't work for DragAndDropCoordinate.x = 0 or DragAndDropCoordinate.y=0

### ISSUE THREAD

**Issue by slavamarkovski** [webdriverio/webdriverio#5459]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [6.1.8]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [e.g. 12.16.1]
 - **NPM version:** [e.g. 6.13.4]
 - **Browser name and version:** [e.g. Chrome 83]
 - **Platform name and version:** [e.g. Windows 10]

**Config of WebdriverIO**

**Describe the bug**
el.dragAndDrop({x: 100, y: 0}), el.dragAndDrop({x: 0, y: 100}) doesn't work.
Error "command dragAndDrop requires an WebdriverIO Element or and object with "x" and "y" variables as first parameter" is thrown

**To Reproduce**
el.dragAndDrop({x: 100, y: 0})
el.dragAndDrop({x: 0, y: 100}) 

[Include code or an example repository that can easily be set up]

**Expected behavior**
Source control should be dragged and dropped vertically / horizontally

**Log**

**Additional context**
Seems issue in this line of code - https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/commands/element/dragAndDrop.js#L28 >> (!target.x || !target.y)

> Please use the correct markdown

**Comment by christian-bromann** [comment]
fixed in #5462

**Comment by tehhowch** [comment]
Also affects v5

**Comment by VladislavDarhel** [comment]
Still reproduced
