### ISSUE TITLE
.then spreads my array.

### ISSUE THREAD

**Issue by Freyert** [webdriverio/webdriverio#546]
```html
<input name='George'></input>
<input name='Nancy'></input>
<input name='Steve'></input>
<input name='and the rest of the party'></input>
```
```javascript
driver.getAttributes('input', 'name')
.then(function(names) {
  return names;
})
.then(function(names) { console.log(names); });

//returns 'George'
//should be ['George', 'Nancy', 'Steve', 'and the rest of the party']
// console.log(arguments) instead of names and you see they're being spread.
```

How do I pass on an array of values? This isn't how `then` is supposed to operate.

**Comment by christian-bromann** [comment]
@Freyert thanks for reporting. This is fixed with `v3`. Sorry for not having an immediate solution for you. You could use callbacks in the meantime:

```js
driver.getAttributes('input', 'name', function(err, names) {
    console.log(names); // returns ['George', 'Nancy', 'Steve', 'and the rest of the party']
})

**Comment by Freyert** [comment]
Not a worry! Thanks @christian-bromann for the response. Love the project, I'd love to get more involved as well.

**Comment by christian-bromann** [comment]
Awesome .. looking forward

**Comment by Freyert** [comment]
Also, as a workaround I would caution anyone using the 2.0 library *NOT* to trust the promise interface. Instead, and I hope you don't mind me plugging, use petkaantonov/bluebird to Promisify the callback functions manually.

```javascript
var addValue = Promise.promisify(driver.addValue, driver)

addValue('input', 'cats');
```
Bluebird is a fantastic Promise library if you haven't tried it out already. I'm sure you can do the same with Q.

**Comment by christian-bromann** [comment]
The promise handler in WebdriverIO `v2.x` just emulates promise behaviour and was apparently never able to fulfil the whole promise A+ spec. Although it is perfect to make tests like this:

```js
browser
     .getTitle().should.eventually.be('My title')
     .getValue('#myInput').should.eventually.be('some value');
```

`v3` uses the Q library. There is also a discussion of switching to native promise.

**Comment by Freyert** [comment]
Good info, thanks!
