### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "'wait' action should be preceded by an item with absolute positioning" UserInfo={NSLocalizedDescription='wait' action should be preceded by an item with absolute positioning}

### ISSUE THREAD

**Issue by baligit** [webdriverio/webdriverio#5460]
## 💬 Questions and Help
Hello all, 
I am trying to execute tap action on iOS driver, but the following error is occurred: 
An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "'wait' action should be preceded by an item with absolute positioning" UserInfo={NSLocalizedDescription='wait' action should be preceded by an item with absolute positioning} 

This is my code: 
   ` TouchAction<IOSTouchAction> touchActionChosePhoto = new IOSTouchAction(getIOSDriver());
                touchActionChosePhoto.waitAction(WaitOptions.waitOptions(Duration.ofMillis(5000))).tap(PointOption.point(53, 164)).release().perform();`

Any help to fix it. 

For questions or help please see:

- [WebdriverIO Gitter Support Channel](https://gitter.im/webdriverio/webdriverio)
- [#webdriverio channel om SeleniumHQ Slack](https://seleniumhq.slack.com/join/shared_invite/enQtODAwOTUzOTM5OTEwLTZjZjgzN2ExOTBmZGE0NjkwYzA2Nzc0MjczMGYwYjdiNGQ5YjI0ZjdjYjFhMjVlMjFkZWJmNDYyMmU1OTYyM2Y)

**Comment by christian-bromann** [comment]
It does not look like you are using WebdriverIO. If you use Selenium or a different framework please use their support channels, thanks!
