### ISSUE TITLE
In Linux can I run multiple/parallel real chrome browser in different X (Xvfb) environment?

### ISSUE THREAD

**Issue by xywang68** [webdriverio/webdriverio#5465]
My goal is to utilize the wdio runner to run test with real chrome browsers in parallel.
I am able to spin up any X environment and run test with one real chrome browser from beginning to end by setting process.env.DISPLAY to any target X environment.
I wonder if wdio can help me to run these in parallel using different X environments concurrently? Any suggestion?
Thank you.

**Comment by christian-bromann** [comment]
> I wonder if wdio can help me to run these in parallel using different X environments concurrently?

not sure what you mean by X environment by you can use a selenium grid to be able to run multiple tests in parallel. There are a lot of documentations on the internet around that. You can also use a cloud provider like Sauce Labs.

Closing as this is not really an issue. If you have further question please reach out in the [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
