### ISSUE TITLE
Documentation gives instructions for using mocha chai expect library when it's not supported

### ISSUE THREAD

**Issue by paulcdejean** [webdriverio/webdriverio#5478]
On this page: http://v4.webdriver.io/guide/testrunner/frameworks.html

It gives instructions for setting up chai as the expect library:

```
before: function() {
    var chai = require('chai');
    global.expect = chai.expect;
    chai.Should();
}
```

However when you put in that exact code you get this warning:

```
[0-0] Warning! Unsupported expect lib is used.
Only Jasmine >= 3.3.0 and Jest's expect are supported.
```

And things don't work properly.

The documentation shouldn't suggest setting up mocha chai as your expect library when it's not supported by wdio at this time...

Here's the version of stuff in my package.json:

```
  "dependencies": {
    "@wdio/local-runner": "^6.1.17",
    "@wdio/mocha-framework": "^6.1.17",
    "@wdio/spec-reporter": "^6.1.14",
    "@wdio/sync": "^6.1.14",
    "chai": "^4.2.0",
    "cross-env": "^7.0.2"
  },
```

**Comment by christian-bromann** [comment]
You are using v6 of WebdriverIO and referencing the v4 docs. Please use the lates docs: https://webdriver.io/docs/frameworks.html

**Comment by paulcdejean** [comment]
I was mixed up because on that page when I selected API version->latest at the top, it did not in fact direct me to the latest version, but still a version 4 :(

**Comment by christian-bromann** [comment]
> when I selected API version->latest at the top

This version picker only exists on the v4 docs and therefor directs you to v4 again.

**Comment by paulcdejean** [comment]
Maybe add some warning for old docs, similar to https://github.com/laravel/framework/issues/32484
