### ISSUE TITLE
Bug in watch mode re-run if path not set in options TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by dzsodzso63** [webdriverio/webdriverio#5481]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.1.17
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v10.21.0
 - **NPM version:** 6.14.4
 - **Browser name and version:** Chrome 81
 - **Platform name and version:** OSX 10.15.3 
 - **Additional wdio packages used (if applicable):** @wdio/cli, @wdio/dot-reporter, @wdio/jasmine-framework, @wdio/local-runner, @wdio/spec-reporter, @wdio/sync

**Config of WebdriverIO**
```
exports.config = {
  runner: 'local',
  specs: [
    './test/**/*.test.js'
  ],
  // path: '/',
...
```
**Describe the bug**
When I try to run wdio locally in `--watch` mode, after the first run all additional run throw this error:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
      at validateString (internal/validators.js:125:11)
      at Object.join (path.js:1147:7)
      at WebDriverRequest._createOptions (/Users/dzso/Formlabs/guillotine/static/formlabs-web-frontend/node_modules/webdriver/build/request.js:96:152)
      at WebDriverRequest.makeRequest (/Users/dzso/Formlabs/guillotine/static/formlabs-web-frontend/node_modules/webdriver/build/request.js:67:74)
      at Browser.protocolCommand (/Users/dzso/Formlabs/guillotine/static/formlabs-web-frontend/node_modules/webdriver/build/command.js:70:20)
```
Looks like the source is this line: https://github.com/webdriverio/webdriverio/blob/master/packages/webdriver/src/request.js#L87

**To Reproduce**

- Remove `hostname`, `port`, `path` config entries
- Run wdio in `--watch` mode
- After the first run, modify a test file, wait for re-run
- any methon on the global `browser` object (e.g. `browser.$()`) will throw the error

**Expected behavior**
There shluldn't be this error thrown

**Additional context**
It looks like that in the first run it does not go to that specific line in `request.js`, but other further runs wrapped to `protocolCommand` by `@wdio/sync`

**Comment by christian-bromann** [comment]
Any help on this would be highly appreciated.

**Comment by abecks** [comment]
This was happening to me in Standalone mode. I noticed ChromeDriver is starting on port 9515:

`Starting ChromeDriver 84.0.4147.30 (48b3e868b4cc0aa7e8149519690b6f6949e110a8-refs/branch-heads/4147@{#310}) on port 9515`

So I added `port: 9515` and `path: /` to `wdio.config.js` and it is now working.

**Comment by Yanela-ipsy** [comment]
Hi **abecks** can you paste here the full call please?

**Comment by christian-bromann** [comment]
This bug can't happen anymore as we are now doing this `path.join(options.path || '', endpoint)`
