### ISSUE TITLE
Possibly incorrect browser.waitUntil example?

### ISSUE THREAD

**Issue by ylilarry** [webdriverio/webdriverio#5482]
**Pre-check**
- [X] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [X] Unclear documentation
- [ ] A typo
- [ ] Missing documentation
- [ ] Other

**Description of the improvement / report**
Is this example wrong? https://webdriver.io/docs/api/browser/waitUntil.html

I’ve tested, specifying timeout this does not work:
```
        browser.waitUntil(
            () => browser.getUrl().includes('/orders/1'),
            {
                timeout: 20000,
            }
        )
```
However, this work
```
        browser.waitUntil(
            () => browser.getUrl().includes('/orders/1'), 20000,
        )
```

I’m not sure if this is a bug or a documentation issue

I’m using ^5.18.0

**Comment by christian-bromann** [comment]
> I’m using ^5.18.0

v5 docs are here: https://v5.webdriver.io/docs/api/element/waitUntil.html
