### ISSUE TITLE
[@wdio/allure-reporter] On V6, for android tests, incorrect deviceName is displayed in allure reports

### ISSUE THREAD

**Issue by sam-viz** [webdriverio/webdriverio#5489]
Hello,

First of all, thanks for making such an awesome tool !
I just noticed that migrating from V5 to V6, allure reporter is not displaying the correct device name on android tests anymore.

**Environment (please complete the following information):**
    "@wdio/allure-reporter": "^6.1.14",
    "@wdio/cli": "^6.1.16",
    "@wdio/config": "^6.1.14",
    "@wdio/cucumber-framework": "^6.1.14",
    "@wdio/local-runner": "^6.1.16",
    "@wdio/logger": "^6.0.16",
    "@wdio/sauce-service": "^6.1.16",
    "@wdio/spec-reporter": "^6.1.14",
    "@wdio/sync": "^6.1.14",

**Describe the bug**

We're using wdio as our mobile automation framework, and in our CI, we like to specify a device name for each device, that we can retrieve on allure report later on.

Since V6, for android only, no matter which deviceName i put on the configuration, only emulator-5554 is displayed on allure report.

**To Reproduce**
 - Using wdio and wdio allure reporter, start android appium tests.
Example of a subset of capabilities:
`capabilities: [
		{
			maxInstances: 1,
			deviceName: 'Android GoogleAPI Emulator',
			platformVersion: '6.0',
			newCommandTimeout: 8 * 60 * 60, // in seconds => 8h
			noReset: true,
		}`
 - Check the generated allure reports

Expected behaviour:
 - Each test have the device name specified in capabilities config
Example (got the screenshot using V5 version)

<img width="609" alt="Screenshot 2020-06-14 at 19 09 26" src="https://user-images.githubusercontent.com/6889963/84599541-0d8c6c00-ae73-11ea-8a23-0435bb6b7867.png">

Actual behaviour:
 - A device name is displayed on test, but it is always emulator-5554
<img width="560" alt="Screenshot 2020-06-14 at 19 08 41" src="https://user-images.githubusercontent.com/6889963/84599543-0feec600-ae73-11ea-887b-38afb1c0d2ad.png">

**Context**
I did some basic debugging but the capabilities object injected to allure reporter is not the same from V5 to V6.

In webdriverio/packages/wdio-allure-reporter/src/index.js line 113. We get the browser name and device name from capabilities object.

In V5, here is what this object would look like (some fields were omitted):
`{
  platformName: 'Android',
  automationName: 'UiAutomator2',
  deviceName: 'Android GoogleAPI Emulator',
  platformVersion: '6.0',
  newCommandTimeout: 28800,
  noReset: true
}`

In V6, here what this object would look like (some fields were omitted):
```
{
  platform: 'LINUX',
  webStorageEnabled: false,
  takesScreenshot: true,
  javascriptEnabled: true,
  databaseEnabled: false,
  networkConnectionEnabled: true,
  locationContextEnabled: false,
  warnings: {},
  desired: {
    platformName: 'Android',
    automationName: 'UiAutomator2',
    deviceName: 'Android GoogleAPI Emulator',
    platformVersion: '6.0',
    noReset: true,
  },
  platformName: 'Android',
  automationName: 'UiAutomator2',
  disableAndroidWatchers: true,
  disableWindowAnimation: true,
  deviceName: 'emulator-5554',
  noReset: true,
  deviceUDID: 'emulator-5554',
  deviceApiLevel: 28,
  platformVersion: '9',
  deviceScreenSize: '1440x2560',
  deviceScreenDensity: 560,
  deviceModel: 'AOSP on IA Emulator',
  deviceManufacturer: 'Google',
  pixelRatio: 3.5,
  statBarHeight: 84,
  viewportRect: { left: 0, top: 84, width: 1440, height: 2308 },
}
```

So, i think the capabilities object that is injected the allure reporter contains the value returned from appium server when requesting capabilities, and requested caps were moved to desired object. 
Is there a reason to why was it done this way ? 

Do you think i can create a PR to make allure reporter take device name/ browser name from the desired object ?

Thank you
Regards.

**Comment by christian-bromann** [comment]
> Is there a reason to why was it done this way ?

No.

> Do you think i can create a PR to make allure reporter take device name/ browser name from the desired object ?

Yes please! Let us know if we can help you contributing this PR.

**Comment by christian-bromann** [comment]
For anyone who wants to look into this. The change would need to happen here: https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-allure-reporter/src/index.js#L113-L119 - the `this.capabilities` object surely provides some more in depth data about the device that we could use. It would be great to add a unit test for the `setCaseParameters` method to ensure we have good coverage.

Feel free to book a 1:1 [pairing session](https://webdriver.io/blog/2020/07/01/office-hours.html) if you feel like up for this. Any contributions are welcome 😊

**Comment by jags14385** [comment]
I would like to pick up the issue. I have booked a 1:1 pairing session . Do you want me to do a initial setup ?

**Comment by christian-bromann** [comment]
> I would like to pick up the issue.

Awesome!

> Do you want me to do a initial setup ?

Yes. Please have a look at the [contribution guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and try to get familiar with the code base (e.g. running tests, making changes etc.).

**Comment by jags14385** [comment]
PR is ready for review

**Comment by christian-bromann** [comment]
Thanks @jags14385 , let's continue the conversation in the PR
