### ISSUE TITLE
DevTools service should accept caps: browserName: "chromium"

### ISSUE THREAD

**Issue by mvgiacomello** [webdriverio/webdriverio#5493]
*Environment:*

- WebdriverIO version: 6.1.8
- Mode: WDIO Testrunner
- If WDIO Testrunner, running sync/async: sync
- Node.js version: v12 lts
- NPM version: 6.14.4
- YARN version: 1.12.4
- Browser name and version: Chromium 83.0.4103.0
- Platform name and version: ubuntu 20.04 lts / docker-node-lts
- Additional wdio packages used (if applicable): @wdio/devtools-service:@6.1.14

*Describe the bug:*

Based on this line of code, I shouldn't be able to use devtools with chromium when my capabilities are `browserName: "chromium"`: https://github.com/webdriverio/webdriverio/blob/79291913e844d8221f6f095680d6a5f565b3c1f0/packages/wdio-devtools-service/src/index.js#L23

**Comment by christian-bromann** [comment]
@mvgiacomello this request makes sense to me. Would you mind proposing a PR?

**Comment by mvgiacomello** [comment]
@christian-bromann sure thing, let me just get some things out of the way and I'll raise a PR for this. Cheers.

**Comment by pjcalvo** [comment]
@mvgiacomello I will be happy to get this one closed if you haven't started!

**Comment by mvgiacomello** [comment]
@pjcalvo Haven't started, feel free to pick this one up.

**Comment by pjcalvo** [comment]
@christian-bromann do you have the updated list of chromium based browsers? Also Is there a way to identify if a browser is chromium and avoid hardcoding a list?

**Comment by christian-bromann** [comment]
> do you have the updated list of chromium based browsers?

No but something like:
- chrome
- chromium
- googlechrome
- google chrome

**Comment by pjcalvo** [comment]
@christian-bromann I thought about adding support for MicrosoftEdge and Opera as well, but all the findCDPInterface is coded for chrome and so it will require a major effort.

https://github.com/webdriverio/webdriverio/blob/2038cd0053fa5d3f125e9ca31176b7212e65c747/packages/wdio-devtools-service/src/utils.js#L23

I will just add chromium for now.

**Comment by christian-bromann** [comment]
We will revisit this with the [Network Primitives](https://github.com/webdriverio/webdriverio/issues/5336) project where we will fully integrate Puppeteer into WebdriverIO. The DevTools service then will use the Puppeteer instance created by WebdriverIO.

**Comment by christian-bromann** [comment]
This bug has been fixed. Thanks @pjcalvo for taking this on.
