### ISSUE TITLE
Local custom services are null on the browser object

### ISSUE THREAD

**Issue by StephenEsser** [webdriverio/webdriverio#5499]
**Environment:**
 - **WebdriverIO version:** [6.1.11]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [v10.20.0]
 - **NPM version:** [6.14.4]
 - **Browser name and version:** [Chrome 83]
 - **Platform name and version:** [Mac OS Catalina]
 - **Additional wdio packages used (if applicable):** [Setup was done 1-1 using the [Getting Started Page](https://webdriver.io/docs/gettingstarted.html).]

**Config of WebdriverIO**

This project was generated using the steps on the [Getting Started Page](https://webdriver.io/docs/gettingstarted.html) and then adding an example custom service.

https://github.com/StephenEsser/wdio-custom-service/blob/master/wdio.conf.js

**Describe the bug**

Custom services are added onto the global browser object with null as a name. This makes the service unidentifiable when reading from the global configuration options to analyze the service options.

**To Reproduce**

1. Add a custom local service to the `wdio.conf.js`
2. In the `before` hook of the service print out the global browser object
3. Observe the custom services are unresolvable. Their name shows as null.

```json
 // ...
  "reporters": [
    "spec"
  ],
  "services": [
    "chromedriver",
    [
      null
    ],
    [
      null
    ]
  ],
  "execArgv": [],
  "maxInstances": 5,
  "maxInstancesPerCapability": 100,
  // ...
```

Providing an example project for step by step reproduction.

1. git clone https://github.com/StephenEsser/wdio-custom-service
2. cd wdio-custom-service
3. npx wdio wdio.conf.js

Observe the services array in the console shows null instead of the name of the service.

https://github.com/StephenEsser/wdio-custom-service

**Expected behavior**

Custom services should be named in the global services array.

**Log**

https://gist.github.com/StephenEsser/eabfe7b588bcefdc7320b12c2af92821

**Additional context**

Logging the browser options output here:

https://github.com/StephenEsser/wdio-custom-service/blob/master/lib/wdio-example-service2.js#L10

**Comment by christian-bromann** [comment]
Hey,
thanks for filing the issue. This seems indeed like bug. We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by StephenEsser** [comment]
Closing this issue.

Upon further investigation the service is available in the browser object services array. JSON.stringify does not appropriately print nested class objects. It prints as null even though the Object is present.
