### ISSUE TITLE
Allure-reporter doesnt produce xml for failed in before spec

### ISSUE THREAD

**Issue by dimkin-eu** [webdriverio/webdriverio#5500]
**Describe the bug**
Test failing before `beforeEach` will not be shown in Allure report ( even xmls arent produced)

**Expected behavior**
3 (all started) suites are shown in the report

**Actual behavior**
1 suite is shown in the report

**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.1
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [12.16.1]
 - **NPM version:** [6.14.5]
 - **Browser name and version:** [Chrome 83]
 - **Platform name and version:** [macOS Catalina]
 - **Additional wdio packages used (if applicable):** 
```
  "devDependencies": {
    "@wdio/cli": "6.1.17",
    "@wdio/local-runner": "6.1.17",
    "@wdio/mocha-framework": "6.1.17",
    "@wdio/spec-reporter": "6.1.14",
    "@wdio/sync": "6.1.14",
    "chromedriver": "83.0.0",
    "wdio-chromedriver-service": "6.0.3",
    "@wdio/allure-reporter": "6.1.14"
  }
```

**Config of WebdriverIO**
same as default, except
```
    reporters: [['allure', {outputDir: 'allure-results'}]],
```
**package.json**

```
  "scripts": {
    "test": "npx wdio wdio.conf.js",
    "report": "allure generate --clean allure-results && allure open"
  },
```

**To Reproduce**
run `npm test` and then `npm report`

note 
- spec1.js will fail in `before` with `expect(received).toBeTruthy() Received: false` and **NOT** reported
- spec2.js will fail in `beforeAll` with `[0-1]  Error:  beforeAll is not defined` and **NOT** reported
- spec3.js will fail in `beforeEach` with `expect(received).toBeTruthy() Received: false` and is reported
<img width="1050" alt="Screenshot 2020-06-16 at 08 52 29" src="https://user-images.githubusercontent.com/7899764/84736696-1d10cf80-afaf-11ea-871a-c93d43a81b40.png">

If spec3.js will pass, then the whole allure report **will be shown as passed**, even 2 rest specs failed
<img width="1043" alt="Screenshot 2020-06-16 at 08 53 14" src="https://user-images.githubusercontent.com/7899764/84736739-3154cc80-afaf-11ea-9296-22501547a6bd.png">

spec1.js
```
before(() => {expect(false).toBeTruthy();})

describe('before spec - webdriver.io page', () => {
    it('should have the right title', () => {
        browser.url('https://webdriver.io')
        expect(browser).toHaveTitle('WebdriverIO · Next-gen browser and mobile automation test framework for Node.js');
    })
})
```
spec2.js
```
beforeAll(() => {expect(false).toBeTruthy();})

describe('beforeAll spec - webdriver.io page', () => {
    it('should have the right title', () => {
        browser.url('https://webdriver.io')
        expect(browser).toHaveTitle('WebdriverIO · Next-gen browser and mobile automation test framework for Node.js');
    })
})
```
spec3.js
```
beforeEach(() => {expect(false).toBeTruthy();})

describe('beforeEach Spec - webdriver.io page', () => {
    it('should have the right title', () => {
        browser.url('https://webdriver.io')
        expect(browser).toHaveTitle('WebdriverIO · Next-gen browser and mobile automation test framework for Node.js');
    })
})
```

**Comment by christian-bromann** [comment]
Hey,
thanks for filing the issue. This seems indeed like bug. We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by joshskumar** [comment]
I think the exception  is coming from mocha @dimkin-eu can you check if other reporters have the same issue and also can you lease paste the logs in your console

**Comment by BorisOsipov** [comment]
Hi! We have rewritten the reporter to the new allure-js version. Please try version 8.5.0 of wdio-allure-reporter and provide more details if the issue still persists. Feel free to create a new issue with actual details if it reproduces.
