### ISSUE TITLE
UnhandledPromiseRejectionWarning error when executing wdio config with node 13.0.1

### ISSUE THREAD

**Issue by spattisson** [webdriverio/webdriverio#5503]
**Environment:**
 - **WebdriverIO version:** @wdio/cli (v6.1.17)
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 13.0.1
 - **NPM version:** 6.14.3
 - **Browser name and version:** n/a
 - **Platform name and version:** mac OSX 10.15.5 (19F96)
 - **Additional wdio packages used (if applicable):** n/a

**Config of WebdriverIO**
I was attempting to set up WebdriverIO config using the configuration utility.

**Describe the bug**
I’m trying to get WebdriverIO CLI configured following this guide
https://webdriver.io/docs/gettingstarted.html

I’m getting the below error when executing `npx wdio config -y` when trying to run the configuration utility:
```[~/webdriverio-test]: 
└─> npx wdio config -y
(node:36054) UnhandledPromiseRejectionWarning: Error: Package exports for '/Users/seymourpattisson/webdriverio-test/node_modules/uuid' do not define a valid '.' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:460:13)
    at resolveExports (internal/modules/cjs/loader.js:393:16)
    at Function.Module._findPath (internal/modules/cjs/loader.js:492:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:787:27)
    at Function.Module._load (internal/modules/cjs/loader.js:693:27)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/seymourpattisson/webdriverio-test/node_modules/devtools/build/index.js:18:13)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
(node:36054) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:36054) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**
Steps to reproduce the behaviour:
$ mkdir webdriverio-test && cd webdriverio-test
$ npm init -y
$ npm i --save-dev @wdio/cli
$ npx wdio config -y

exactly as per https://webdriver.io/docs/gettingstarted.html

**Expected behaviour**
The CLI for the configuration was expected to run, allowing me to answer the questions starting with "Where do you want to execute your tests?" etc.

**Comment by christian-bromann** [comment]
Hey,
thanks for filing the issue. This seems indeed like bug. We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by pjcalvo** [comment]
This is an issue thrown by UUID, which does not support NodeJs Version 13.5.x.

If you upgrade to Node 14.x.x it will work just fine. 

cc @christian-bromann @spattisson 

[https://github.com/uuidjs/uuid/issues/440](https://github.com/uuidjs/uuid/issues/440)

**Comment by christian-bromann** [comment]
This issue is fixed using Node.js v13.12 or higher. Closing.
