### ISSUE TITLE
beforeHook/afterHook not executed in cucumber

### ISSUE THREAD

**Issue by osmolyar** [webdriverio/webdriverio#5504]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.1.11]
 - **Mode:** Standalone
 - **If WDIO Testrunner, running sync/async:**sync
 - **Node.js version:** 12.9.0
 - **NPM version:**6/14/4
 - **Browser name and version:**Chrome 83
 - **Platform name and version:**  Windows 10
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/cucumber-framework

**Config of WebdriverIO**
An example of how you configured WebdriverIO config
` 
 beforeStep: function (stepData, context) {
        console.log("In beforeStep");
        console.log("****context is "+ JSON.stringify(context));
    },
    afterStep: function (stepData,context,result) {
        console.log("In afterStep");
        console.log("****context is "+ JSON.stringify(context));
        }
    },
    beforeHook: function (test, context, stepData, world) {
        console.log("In beforeHook, world is "+ JSON.stringify(world));
    },
    afterHook: function (test, context, { error, result, duration, passed, retries }, stepData, world) {
        console.log("In afterHook, world is "+ JSON.stringify(world));
    },
    beforeScenario: function (uri, feature, scenario, sourceLocation) {
        console.log("In beforeScenario");
        global.context.stackP=[];
    },
    afterScenario: function (uri, feature, pickle,result, sourceLocation) {
        console.log("In afterScenario");
        SessionUtilities.logOutOrReload();
`
**Describe the bug**
The console.logs in beforeHook and afterHook never get logged despite several other hooks running.

**To Reproduce**
Run cucumber feature file with above hook configuration.

**Expected behavior**
Per the documentation, these hooks should run before/after each other hook within the suite.

**Comment by christian-bromann** [comment]
Hey,
thanks for filing the issue. This seems like an enhancement as we never supported Cucumber hooks before. We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by osmolyar** [comment]
These are actually documented as being not only for cucumber, specifically with Mocha examples, 
>  /**
     * This hook gets executed _before_ every hook within the suite starts.
     * (For example, this runs before calling `before`, `beforeEach`, `after`, `afterEach` in Mocha.)
     *
     * (`stepData` and `world` are Cucumber-specific.)
     *
     */
    beforeHook: function (test, context/*, stepData, world*/) {
    },
    /**
     * Hook that gets executed _after_ every hook within the suite ends.
     * (For example, this runs after calling `before`, `beforeEach`, `after`, `afterEach` in Mocha.)
     *
     * (`stepData` and `world` are Cucumber-specific.)
     */
    afterHook: function (test, context, { error, result, duration, passed, retries }/*, stepData, world*/) {
    },

and were enhanced in  https://github.com/webdriverio/webdriverio/pull/4545/files to add stepData and context parameters for cucumber.  According to the above they should be running before/after every hook, not just cucumber ones.  Actually not exactly sure what they'd be used for but wanted to try them out to see if they actually log out context.

**Comment by christian-bromann** [comment]
@osmolyar I believe this is now possible with the latest WebdriverIO version and our Cucumber update we did in v7. Closing.
