### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by soumyaevan** [webdriverio/webdriverio#5507]
**Pre-check**
- [ 1] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [1 ] Unclear documentation
- [ ] A typo
- [ ] Missing documentation
- [ ] Other

**Description of the improvement / report**
A clear and concise description.

No documentation us available for firefox capability

**Comment by christian-bromann** [comment]
WebdriverIO supports all browsers and mobile devices. If you follow the getting started guide and use the [selenium standalone service](https://webdriver.io/docs/selenium-standalone-service.html) Firefox should also work out of the box there. The framework doesn't dictate how your drivers are setup.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have further questions. Cheers!
