### ISSUE TITLE
getLogs/getLogTypes doesn't work for Edge Chromium

### ISSUE THREAD

**Issue by lind-eduard** [webdriverio/webdriverio#5509]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.1.14
 - **Mode:** Standalone mode
 - **If WDIO Testrunner, running sync/async:** no idea how to check
 - **Node.js version:** 12.16.3
 - **NPM version:** 6.14.4
 - **Browser name and version:** Edge Chromium 83
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):**  @wdio/selenium-standalone service 6.1.14

**Config of WebdriverIO**
        browser: 'MicrosoftEdge',
        desiredCapabilities: {
        acceptInsecureCerts: true,
        'ms:edgeOptions': {
           args: [ "--headless"]
        },

**Describe the bug**
When I'm trying to execute getLogs/getLogTypes functions on Chromium Edge, I get an error TypeError: browser.getLogTypes is not a function. On Chrome the same code works perfectly

**To Reproduce**
Just try to grab logs in Chromium Edge

**Expected behavior**
Logs are grabbed, same as it work for Chrome browser

**Log**
https://gist.github.com/lind-eduard/e05dfbacb49f22b9e6feb510ca79109c

**Comment by christian-bromann** [comment]
> On Chrome the same code works perfectly

This is because Chrome still has this old JSONWire Protocol command implemented. The command is not supported for many browsers as the WebDriver protocol doesn't have such a command. There is unfortunately nothing WebdriverIO can do about this.
