### ISSUE TITLE
Local testing automation on Browserstack

### ISSUE THREAD

**Issue by mohdasif2294** [webdriverio/webdriverio#551]
Hi, 

I am having trouble with the automated local testing on browserstack .
How do I toggle :-
1. <b>browserstack.local</b> to <i>True</i> 
2. <b>browserstack.debug</b> to <i>True</i>

I am using mocha and webdriver.io .

My test.js is somewhat like this : -
```js
var assert = require('assert');
var webdriverio = require('webdriverio');

var options = {
    desiredCapabilities: {
        browserName: 'firefox',
    },
    host: 'hub.browserstack.com',
    port: 80,
    user: USERNAME,
    key: KEY,
    loglevel: 'silent',
};

var site = "http://local.mynet.com:5000/";


var client = webdriverio
    .remote(options).init();

require('webdrivercss').init(client, {
    screenshotRoot: 'my-shots',
    failedComparisonsRoot: 'diffs',
    misMatchTolerance: 0.05,
    screenWidth: [1024]
});

describe('Login Testing', function() {

    it('Open site and take snapshot', function(done) {
        client.url(site)
            .getTitle(function(err, title) {
                assert.equal(title, 'MY SITE');
            })
            /*.webdrivercss('homepage', {
                name: 'home',
            })*/
            .call(done);
    });

    after('closing client session', function(done) {
        client.end(done);
    });

});
```

PS: I am running Browserstack Local with my access key along with selenium-standalone server .

**Comment by christian-bromann** [comment]
@mohdasif2294 why did you close the issue? Have you solved the problem? How?

**Comment by mohdasif2294** [comment]
I solved this issue :+1:  using standard config of selenium web driver.

Just need to add <pre>'browserstack.local' : 'true',
'browserstack.debug': 'true',</pre>
in desiredCapabilities .

Thanks for the lovely and easy wrapper of selenium 2.0  :)

**Comment by christian-bromann** [comment]
Awesome, thanks for sharing :+1:

**Comment by mohdasif2294** [comment]
@christian-bromann  Thank you for the wrapper Js !!
