### ISSUE TITLE
move target out of bounds: Blocked a frame with origin from accessing a cross-origin frame

### ISSUE THREAD

**Issue by Ed-Ed** [webdriverio/webdriverio#5511]
- WebdriverIO version: 6.1.17
- Node.js version: 14.3.0
- NPM version: 6.14.5
- Browser name and version: Chrome 83.0.4103.106
- Platform name and version: Mac 10.15.3

I'm trying to get the window object like so:

```
browser.url('/');
const window = browser.execute(() => window);
```

This throws the following error:

`Request failed with status 200 due to Error: move target out of bounds: Blocked a frame with origin "http://localhost:8080" from accessing a cross-origin frame.`

Am I getting the window object correctly? Any ideas as to what is causing that issue?

**Comment by christian-bromann** [comment]
> Am I getting the window object correctly?

You can return the window object like that. It can't be serialized. You can only return specific properties from it.

Closing as I don't think this is an issue in WebdriverIO and more a limitation how WebDriver works. I recommend to either call functions on the window object via execute or return the values you are interested in. If you have further questions feel free to reach out in our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
