### ISSUE TITLE
WebdriverIO6 unable to execute any scripts on Chromium Edge 83

### ISSUE THREAD

**Issue by snehalkulkarni20** [webdriverio/webdriverio#5513]
**Environment (please complete the following information):**
 - **WebdriverIO version: 6
 - **Mode: selenium-standalone
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v12.16.2
 - **NPM version:** 6.14.4]
 - **Browser name and version:** Chromium Edge 83
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):**@wdio/selenium-standalone service

**Config of WebdriverIO**
An example of how you configured WebdriverIO config
```
const defaultTimeoutInterval = process.env.DEBUG ? 60 * 60 * 500 : 1200000;
const { removeSync } = require("fs-extra");
const { join } = require("path");
const cucumberJson = require("wdio-cucumberjs-json-reporter").default;

exports.config = {
  // WebdriverIO allows it to run your tests in arbitrary locations (e.g. locally or
  // on a remote machine).
  runner: "local",
  // Define which test specs should run.
  // specs: [
  //     './test/specs/**/*.feature'
  // ],
  // Patterns to exclude.
  exclude: [
    // 'path/to/excluded/files'
  ],

  // Define your capabilities here.
  maxInstances: 8,
  capabilities: [
    {
      maxInstances: 7,
      browserName: "MicrosoftEdge",
      "cjson:metadata": {
        device: "Windows Desktop",
        platform: {
          name: "Windows",
          version: "10",
        },
      },
      specs: [
        "./test/specs/chrome_features/**/*.feature",
        "./test/specs/common_features/**/*.feature",
      ],
    },
  ],

  // Level of logging verbosity: trace | debug | info | warn | error | silent
  sync: true,
  // debug: true,
  // execArgv: ["--inspect-brk=127.0.0.1:5859"],
  logLevel: "error",
  coloredLogs: true, // Enables colors for log output.
  screenshotPath: "./test/reports/errorShots/", // Saves a screenshot to a given path if a command fails.

  // If you only want to run your tests until a specific amount of tests have failed use
  // bail (default is 0 - don't bail, run all tests).
  bail: 0,

  // Set a base URL
  baseUrl: "<url>",

  // Default timeout for all waitFor* commands.
  waitforTimeout: 150000,
  connectionRetryTimeout: 150000,
  connectionRetryCount: 3,

  reporters: [
    "spec",
    [
      "junit",
      {
        outputDir: "./test/reports/junit-results/",
        outputFileFormat: function (opts) {
          return `results-${opts.cid}.${opts.capabilities}.xml`;
        },
      },
    ],
    [
      "allure",
      {
        outputDir: "./test/reports/allure-results/",
        disableWebdriverStepsReporting: true,
        disableWebdriverScreenshotsReporting: false,
      },
    ],
    [
      "cucumberjs-json",
      {
        jsonFolder: "./test/reports/cucumber-results/",
      },
    ],
  ],

  // Test runner services
  services: [
    "selenium-standalone",
    [
      "image-comparison",
      {
        baselineFolder: join(process.cwd(), "./screenshots/baselines/"),
        formatImageName: "{tag}",
        screenshotPath: join(process.cwd(), "screenshots/"),
        savePerInstance: true,
        autoSaveBaseline: true,
        blockOutStatusBar: true,
        blockOutToolBar: true,
        //debug: false,
        disableCSSAnimation: false,
        fullPageScrollTimeout: 2000,
        hideScrollBars: true,
        clearRuntimeFolder: false,
        returnAllCompareData: true,
        ignoreAntialiasing: true,
        //scaleImagesToSameSize:true,
        //rawMisMatchPercentage:true,
        //saveAboveTolerance: 10,
        //misMatchPercentage: 0.50
      },
    ],
  ],

  // Framework you want to run your specs with.
  framework: "cucumber",

  cucumberOpts: {
    requireModule: ["@babel/register"],
    require: ["./test/steps/*.steps.js"],
    backtrace: true,
    compiler: [],
    dryRun: false,
    failFast: false,
    format: ["pretty"],
    colors: true,
    snippets: true,
    source: true,
    profile: [],
    strict: false,
    tagsInTitle: false,
    tagExpression: "not @Pending",
    timeout: defaultTimeoutInterval,
    ignoreUndefinedDefinitions: true,
    failAmbiguousDefinitions: true,
  },

  // Hooks
  onPrepare: function (config, capabilities) {
    removeSync("./test/reports/cucumber-results");
    removeSync("./test/reports/allure-results");
    removeSync("./test/reports/junit-results");
    removeSync("./screenshots");
  },

  beforeSession: function (config, capabilities, specs) {
    require("@babel/register");
  },

  before: function (capabilities, specs) {
    const chai = require("chai");

    global.expect = chai.expect;
    global.assert = chai.assert;
    global.should = chai.should();

    global.reporter = require("wdio-cucumberjs-json-reporter").cucumberJson;
  },

  afterStep(uri, feature, result) {
    if (!result.passed)
      cucumberJson.attach(browser.takeScreenshot(), "image/png");
  },

  onComplete(exitCode, config, capabilities, results) {
    const report = require("multiple-cucumber-html-reporter");
    report.generate({
      jsonDir: "./test/reports/cucumber-results/",
      reportPath: "./cucumber-report/",
      openReportInBrowser: false,
      pageTitle: "Visual & Functional Tests",
      pageFooter:
        "<div><p> &nbsp &nbsp &nbsp A report for visual & functional tests</p></div>",
      displayDuration: true,
      //durationInMS: true,
      reportName: "Visual & Functional Test",
    });
  },
};
```
**Describe the bug**
When i use Edge in the capabilities, and execute the scripts the browser instance gets launched but no actions happen after that. Even the application url is not opened.
I am using WDIO6 and Chromium Edge 83

**To Reproduce**
When i use Edge in the capabilities, and execute the scripts the browser instance gets launched but no actions happen after that. Even the application url is not opened.
I am using WDIO6 and Chromium Edge 83
I execute the npm script "npm run test"

**Expected behavior**
The browser should open the application url and execute the scripts.

**Comment by pjcalvo** [comment]
Can you share the logs that you are getting? This has happened to me when the MicrosoftEdge driver and the browser are on a different version.

Make sure you are using the right chromedriver. You can download it from here and run it manually to try.

https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/

**Comment by snehalkulkarni20** [comment]
There are no logs as there is no error. It launches the browser instances and leaves it there. WDIO commands dont get executed at all.
I am using wdio6 and edge version is 83. Not sure which version of the edge driver gets automatically installed by wdio6.

**Comment by christian-bromann** [comment]
@snackycracky you should at least get some logs from WebdriverIO from the stdout.

**Comment by snehalkulkarni20** [comment]
Below is the log info I could get. The edge browser opens but nothing happens and the test script exits. The browser sessions don't close as well.
One more thing I observed WDIO seems to automatically install this version of edge driver, this is in the npm modules - selenium - driver folder. `17134-MicrosoftEdgeDriver.exe`

console logs:

`[0-3] 2020-06-22T04:08:32.443Z INFO webdriverio: Initiate new session using the webdriver protocol
[0-3] 2020-06-22T04:08:32.445Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
[0-3] 2020-06-22T04:08:32.445Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'MicrosoftEdge', 'cjson:metadata': [Object] },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    browserName: 'MicrosoftEdge',
    'cjson:metadata': { device: 'Windows Desktop', platform: [Object] }
  }
}
[0-3] (node:19224) DeprecationWarning: Got: "options.rejectUnauthorized" is now deprecated, please use "options.https.rejectUnauthorized"
[0-12] 2020-06-22T04:08:32.660Z INFO @wdio/local-runner: Run worker command: run
[0-12] 2020-06-22T04:08:32.832Z INFO webdriverio: Initiate new session using the ./protocol-stub protocol
[0-12] 2020-06-22T04:08:33.097Z INFO wdio-multiple-cucumber-html-reporter: The 'language' was not set, it has been set to the default 'en'
2020-06-22T04:08:33.759Z INFO @wdio/cli: [0-12] SKIPPED in MicrosoftEdge - C:\Users\m1011032\Documents\Sites\acquia\aamc\tests\wdio-automation\test\specs\034-contact-us-form.feature
[0-3] 2020-06-22T04:08:35.985Z WARN webdriver: Request failed with status 500 due to Unable to parse remote response: Unknown error
[0-3] 2020-06-22T04:08:35.986Z INFO webdriver: Retrying 1/3
[0-3] 2020-06-22T04:08:35.986Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
[0-3] 2020-06-22T04:08:35.986Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'MicrosoftEdge', 'cjson:metadata': [Object] },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    browserName: 'MicrosoftEdge',
    'cjson:metadata': { device: 'Windows Desktop', platform: [Object] }
  }
}
[0-3] 2020-06-22T04:08:37.351Z WARN webdriver: Request failed with status 500 due to Unable to parse remote response: Unknown error
[0-3] 2020-06-22T04:08:37.352Z INFO webdriver: Retrying 2/3
[0-3] 2020-06-22T04:08:37.352Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
[0-3] 2020-06-22T04:08:37.352Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'MicrosoftEdge', 'cjson:metadata': [Object] },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    browserName: 'MicrosoftEdge',
    'cjson:metadata': { device: 'Windows Desktop', platform: [Object] }
  }
}
[0-3] 2020-06-22T04:08:39.164Z WARN webdriver: Request failed with status 500 due to Unable to parse remote response: Unknown error
[0-3] 2020-06-22T04:08:39.164Z INFO webdriver: Retrying 3/3
[0-3] 2020-06-22T04:08:39.164Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
[0-3] 2020-06-22T04:08:39.164Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'MicrosoftEdge', 'cjson:metadata': [Object] },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    browserName: 'MicrosoftEdge',
    'cjson:metadata': { device: 'Windows Desktop', platform: [Object] }
  }
}
[0-3] 2020-06-22T04:08:40.752Z ERROR webdriver: Request failed with status 500 due to unknown error: Unable to parse remote response: Unknown error
[0-3] 2020-06-22T04:08:40.752Z ERROR webdriver: unknown error: Unable to parse remote response: Unknown error
    at getErrorFromResponseBody (C:\Users\m1011032\Documents\Sites\acquia\aamc\tests\wdio-automation\node_modules\webdriver\build\utils.js:121:10)
    at WebDriverRequest._request (C:\Users\m1011032\Documents\Sites\acquia\aamc\tests\wdio-automation\node_modules\webdriver\build\request.js:148:56)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async startWebDriverSession (C:\Users\m1011032\Documents\Sites\acquia\aamc\tests\wdio-automation\node_modules\webdriver\build\utils.js:41:16)
    at async Function.newSession (C:\Users\m1011032\Documents\Sites\acquia\aamc\tests\wdio-automation\node_modules\webdriver\build\index.js:44:23)
    at async remote (C:\Users\m1011032\Documents\Sites\acquia\aamc\tests\wdio-automation\node_modules\webdriverio\build\index.js:66:20)
    at async Runner._startSession (C:\Users\m1011032\Documents\Sites\acquia\aamc\tests\wdio-automation\node_modules\@wdio\runner\build\index.js:206:50)
    at async Runner._initSession (C:\Users\m1011032\Documents\Sites\acquia\aamc\tests\wdio-automation\node_modules\@wdio\runner\build\index.js:175:21)
    at async Runner.run (C:\Users\m1011032\Documents\Sites\acquia\aamc\tests\wdio-automation\node_modules\@wdio\runner\build\index.js:93:15)
[0-3] 2020-06-22T04:08:40.753Z ERROR @wdio/runner: Error: Failed to create session.
Unable to parse remote response: Unknown error
    at startWebDriverSession (C:\Users\m1011032\Documents\Sites\acquia\aamc\tests\wdio-automation\node_modules\webdriver\build\utils.js:45:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0-3]  Error:  Failed to create session.
Unable to parse remote response: Unknown error
[0-3] FAILED in MicrosoftEdge - C:\Users\m1011032\Documents\Sites\acquia\aamc\tests\wdio-automation\test\specs\004-year-in-school.feature
2020-06-22T04:08:40.899Z INFO @wdio/cli:launcher: Run onComplete hook
2020-06-22T04:08:40.900Z INFO @wdio/selenium-standalone-service: shutting down all browsers
2020-06-22T04:08:41.331Z ERROR @wdio/cli:utils: Error in onCompleteHook: Error: There were issues reading JSON-files from './test/reports/cucumber-results/'.
    at collectJSONS (C:\Users\m1011032\Documents\Sites\acquia\aamc\tests\wdio-automation\node_modules\multiple-cucumber-html-reporter\lib\collect-jsons.js:16:15)
    at Object.generateReport [as generate] (C:\Users\m1011032\Documents\Sites\acquia\aamc\tests\wdio-automation\node_modules\multiple-cucumber-html-reporter\lib\generate-report.js:69:22)
    at Object.onComplete (C:\Users\m1011032\Documents\Sites\acquia\aamc\tests\wdio-automation\wdio.conf.js:195:12)
    at C:\Users\m1011032\Documents\Sites\acquia\aamc\tests\wdio-automation\node_modules\@wdio\cli\build\utils.js:83:13
    at Array.map (<anonymous>)
    at runOnCompleteHook (C:\Users\m1011032\Documents\Sites\acquia\aamc\tests\wdio-automation\node_modules\@wdio\cli\build\utils.js:81:37)
    at Launcher.run (C:\Users\m1011032\Documents\Sites\acquia\aamc\tests\wdio-automation\node_modules\@wdio\cli\build\launcher.js:83:69)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Spec Files:      0 passed, 1 failed, 12 skipped, 13 total (100% completed) in 00:00:20

2020-06-22T04:08:41.335Z INFO @wdio/local-runner: Shutting down spawned worker
2020-06-22T04:08:41.587Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2020-06-22T04:08:41.588Z INFO @wdio/local-runner: shutting down
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wdio-automation@1.0.0 qa-tests: `wdio wdio.conf.js  --service=selenium-standalone --baseUrl='https://www.qa.cms.aamc.org/' --cucumberOpts.tagExpression='@regression1'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wdio-automation@1.0.0 qa-tests script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\m1011032\AppData\Roaming\npm-cache\_logs\2020-06-22T04_08_41_641Z-debug.log`

**Comment by christian-bromann** [comment]
> [0-3] 2020-06-22T04:08:35.985Z WARN webdriver: Request failed with status 500 due to Unable to parse remote response: Unknown error

Seems like something invalid is returned by the edgedriver. @snehalkulkarni20 can you check what the response was from that driver?

**Comment by snehalkulkarni20** [comment]
hi @christian-bromann how can i check that ?

**Comment by christian-bromann** [comment]
@snehalkulkarni20 can you add some `console.log` in `/node_modules/webdriver/build/request.js` on line 136 something like `console.log(response.body)`

**Comment by snehalkulkarni20** [comment]
Ok.. got this on console for `response.body`

`[0-12] {
  value: {
    stacktrace: 'org.openqa.selenium.WebDriverException: Unable to parse remote response: Unknown error\r\n' +
      '\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:112)\r\n' +
      '\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)\r\n' +
      '\tat org.openqa.selenium.grid.session.remote.RemoteSession$Factory.performHandshake(RemoteSession.java:147)\r\n' +
      '\tat org.openqa.selenium.grid.session.remote.ServicedSession$Factory.apply(ServicedSession.java:161)\r\n' +
      '\tat org.openqa.selenium.remote.server.ActiveSessionFactory.lambda$apply$12(ActiveSessionFactory.java:180)\r\n' +
      '\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\r\n' +
      '\tat java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)\r\n' +
      '\tat java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)\r\n' +
      '\tat java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)\r\n' +
      '\tat java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)\r\n' +
      '\tat java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)\r\n' +
      '\tat java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)\r\n' +
      '\tat java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)\r\n' +
      '\tat java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)\r\n' +
      '\tat java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\r\n' +
      '\tat java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)\r\n' +
      '\tat org.openqa.selenium.remote.server.ActiveSessionFactory.apply(ActiveSessionFactory.java:183)\r\n' +
      '\tat org.openqa.selenium.remote.server.NewSessionPipeline.lambda$null$2(NewSessionPipeline.java:66)\r\n' +
      '\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\r\n' +
      '\tat java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)\r\n' +
      '\tat java.util.Collections$2.tryAdvance(Collections.java:4717)\r\n' +
      '\tat java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)\r\n' +
      '\tat java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)\r\n' +
      '\tat java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)\r\n' +
      '\tat java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)\r\n' +
      '\tat java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)\r\n' +
      '\tat java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\r\n' +
      '\tat java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)\r\n' +
      '\tat org.openqa.selenium.remote.server.NewSessionPipeline.lambda$createNewSession$3(NewSessionPipeline.java:69)\r\n' +
      '\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\r\n' +
      '\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\r\n' +
      '\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\r\n' +
      '\tat java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)\r\n' +
      '\tat java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)\r\n' +
      '\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\r\n' +
      '\tat java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)\r\n' +
      '\tat java.util.stream.Streams$StreamBuilderImpl.tryAdvance(Streams.java:405)\r\n' +
      '\tat java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:728)\r\n' +
      '\tat java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)\r\n' +
      '\tat java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)\r\n' +
      '\tat java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)\r\n' +
      '\tat java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)\r\n' +
      '\tat java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)\r\n' +
      '\tat java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\r\n' +
      '\tat java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)\r\n' +
      '\tat org.openqa.selenium.remote.server.NewSessionPipeline.createNewSession(NewSessionPipeline.java:72)\r\n' +
      '\tat org.openqa.selenium.remote.server.commandhandler.BeginSession.execute(BeginSession.java:65)\r\n' +
      '\tat org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0(WebDriverServlet.java:235)\r\n' +
      '\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\r\n' +
      '\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\r\n' +
      '\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\r\n' +
      '\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\r\n' +
      '\tat java.lang.Thread.run(Thread.java:748)\r\n' +
      'Caused by: org.openqa.selenium.json.JsonException: Unable to determine type from: U. Last 1 characters read: U\n' +
      "Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'\n" +
      "System info: host: 'D1ML31429', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_151'\n" +
      'Driver info: driver.version: unknown\r\n' +
      '\tat org.openqa.selenium.json.JsonInput.peek(JsonInput.java:122)\r\n' +
      '\tat org.openqa.selenium.json.JsonTypeCoercer.lambda$null$6(JsonTypeCoercer.java:140)\r\n' +
      '\tat org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:126)\r\n' +
      '\tat org.openqa.selenium.json.Json.toType(Json.java:69)\r\n' +
      '\tat org.openqa.selenium.json.Json.toType(Json.java:55)\r\n' +
      '\tat org.openqa.selenium.json.Json.toType(Json.java:50)\r\n' +
      '\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:109)\r\n' +
      '\t... 52 more\r\n',
    stackTrace: [
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object]
    ],
    message: 'Unable to parse remote response: Unknown error',
    error: 'unknown error'
  },
  status: 13
}
`

**Comment by christian-bromann** [comment]
> Unable to determine type from: U. Last 1 characters read: U

Seems like the capabilities are invalid formatted. Can you investigate why?

**Comment by snehalkulkarni20** [comment]
This is my capabilities
`    {
      maxInstances: 1,
      browserName: "MicrosoftEdge",
      "cjson:metadata": {
        device: "Windows Desktop",
        platform: {
          name: "Windows",
          version: "10",
        },
      },
    }`

**Comment by christian-bromann** [comment]
> This is my capabilities

@snehalkulkarni20 sorry but there is no way for me to reproduce this as I don't have a Windows machine. Can you please try variations of capabilities to see where the problem occurs?

**Comment by snehalkulkarni20** [comment]
@christian-bromann the similar capability format for other browsers Chrome and Firefox works
Not sure why its a problem for Edge
`    {
      maxInstances: 2,
      browserName: "firefox",
      "cjson:metadata": {
        device: "Windows Desktop",
        platform: {
          name: "Windows",
          version: "10",
        },
      },
    }`

**Comment by snehalkulkarni20** [comment]
Also, looks like WDIO6 is always by default installing the 17134-MicrosoftEdgeDriver.exe
Whereas we need the driver for edge version 83

**Comment by christian-bromann** [comment]
@snehalkulkarni20 would you mind creating an issue here: https://github.com/vvo/selenium-standalone ?

**Comment by snehalkulkarni20** [comment]
Is it not a WDIO issue ?

**Comment by christian-bromann** [comment]
> Is it not a WDIO issue ?

Unlikely. WebdriverIO relies on vvo/selenium-standalone to download and start the right driver.

**Comment by pjcalvo** [comment]
This is also happening on MacOs when executed using selenium-standalone. There are multiple issues opened for this on selenium-standalone! 

I think this can be closed as it is not an wdio issue @christian-bromann

**Comment by christian-bromann** [comment]
@pjcalvo can you link some of the issue here for visibility?

**Comment by pjcalvo** [comment]
@christian-bromann Yes I am sorry I meant to do that.

https://github.com/vvo/selenium-standalone/issues/458 and https://github.com/vvo/selenium-standalone/issues/459 opened by @snehalkulkarni20

**Comment by christian-bromann** [comment]
Closing then, thanks @pjcalvo
