### ISSUE TITLE
Unable to run tests on Firefox

### ISSUE THREAD

**Issue by djohal** [webdriverio/webdriverio#5519]
**Environment:**
 - **WebdriverIO version:** ["@wdio/cli": "^6.1.19 ]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [14.4.0]
 - **NPM version:** [6.14.5]
 - **Browser name and version:** [Chrome 83, Firefox 77]
 - **Platform name and version:** [Windows 10]
 - **Additional wdio packages used (if applicable):** ["@wdio/selenium-standalone-service": "^6.1.14]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

 ```
 capabilities: [
    {
      browserName: 'chrome',
    },
    {
      browserName: 'firefox',
    },
  ],
  services: [
    [
      'selenium-standalone',
      {
        logPath: 'logs',
        installArgs: {
          drivers: {
            chrome: { version: '79.0.3945.88' },
            firefox: { version: '0.26.0' },
          },
        },
        args: {
          drivers: {
            chrome: { version: '79.0.3945.88' },
            firefox: { version: '0.26.0' },
          },
        },
      },
    ],
  ],
```

**Describe the bug**
Using Selenium Standalone server, I'm unable to run tests in firefox when running tests on both Chrome and Firefox in parallel. 
Note: It works fine if I'm running tests just on firefox only i.e remove chrome driver and capability.

**To Reproduce**
- Clone the repo - https://github.com/djohal/webdriverio-test
- git checkout bug
- npm i 
- npm test

**Actual**
Chrome tests run fine. 
Firefox throws an error - `Error:  Couldn't find executable for browser`

Error Gist - https://gist.github.com/djohal/bcfb5bf8e2ff645594e1739e1751b03e

**Expected behavior**
Should be able to run tests on both chrome and firefox in parallel.

**Comment by christian-bromann** [comment]
> Firefox throws an error - `Error: Couldn't find executable for browser`

Do you have Firefox installed on your machine? If Firefox is not installed on the standard app path on your machine you need to specify the browser path in your capabilities:

```js
capabilities: [
   {
     browserName: 'chrome',
   },
   {
     browserName: 'firefox',
     'moz:firefoxOptions': {
         binary: '/path/to/firefox'
     }
   },
 ],
```

Closing this as this is not an issue with WebdriverIO.

**Comment by djohal** [comment]
@christian-bromann It is installed in the standard app path. Like I said firefox tests are working fine with a standalone server if I'm running it JUST on firefox (below settings works fine), however, it fails when running in parallel with Chrome.

```
capabilities: [
   {
     browserName: 'firefox',
    },
 ],

[
      'selenium-standalone',
      {
        logPath: 'logs',
        installArgs: {
          drivers: {
            firefox: { version: '0.26.0' },
          },
        },
        args: {
          drivers: {
            firefox: { version: '0.26.0' },
          },
        },
      },
    ],
```

**Comment by christian-bromann** [comment]
> Like I said firefox tests are working

I don't understand. You initially mentioned:

> Firefox throws an error - `Error: Couldn't find executable for browser`

**Comment by djohal** [comment]
@christian-bromann in the bug description I mentioned - 
Using Selenium Standalone server, I'm unable to run tests in firefox **when running tests on both Chrome and Firefox in parallel**.
Note: It **works fine if I'm running tests just on firefox only** i.e remove chrome driver and capability.

**Comment by christian-bromann** [comment]
I just tried your example and was able to run it by removing the geckodriver version and just setting:

```js
  services: [
    [
      'selenium-standalone',
      {
        logPath: 'logs'
      },
    ],
  ],
```

This will run your test with WebDriver properly. It seems that WebdriverIO is not able to find your Firefox binary on your machine.

**Comment by djohal** [comment]
> ```js
>   services: [
>     [
>       'selenium-standalone',
>       {
>         logPath: 'logs'
>       },
>     ],
>   ],
> ```

Yes, this worked fine. Thank you!

**Comment by jedwards1211** [comment]
I'm not using WDIO or any special version arguments to `selenium-standalone` and it was finding firefox just fine with `webdriverio` v4, but now that I upgrade to v6 it can't find it

**Comment by jpratt2** [comment]
That error can also mean that you need to start .\geckodriver.exe in a terminal
