### ISSUE TITLE
getHTML() return null in the IE7

### ISSUE THREAD

**Issue by arkist** [webdriverio/webdriverio#552]
hi

I don't know why, 
looks like getHTML() doesn't work well in ie7.

here is my sauceLabs testing result:
> scenario: getHTML from searchResult list in google.com

[ie9, win7](https://saucelabs.com/tests/a56d74b71b804c69862cd384c5eca0ac) (o)
[ie7, winXP](https://saucelabs.com/tests/ff83cbf4166949eb8136252d758156af) (x, getHTML() return `null`)

have any idea? thanks!

**Comment by christian-bromann** [comment]
`getHtml` executes a little JavaScript snippet in the browser to get the outer/inner html of an element. Seems that this is not working for IE7:

```
=> JavaScript error 
```

Will look into it. Does is work on other pages then google?

**Comment by arkist** [comment]
@christian-bromann yes i did check that message. 

google is just example. it appear not only google but also any other pages (my interal site) too.

**Comment by christian-bromann** [comment]
All commands using our `selectorExecute(Async)*` were failing as `document.querySelectorAll` is not supported in IE < 9. I added a polyfill. Works now like a charm.

**Comment by arkist** [comment]
good job! ;)
