### ISSUE TITLE
Fix skipped test

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#5521]
We have a [test](https://github.com/webdriverio/webdriverio/blob/master/tests/mocha/test.js#L30-L50) that we had to skip due to an issue in got. This issue has been resolved by now and we should check whether we can re-enable this test or not:

https://github.com/webdriverio/webdriverio/blob/master/tests/mocha/test.js#L30-L50

**Comment by JapneetSingh5** [comment]
I would love to try this one out too :p

**Comment by sethuster** [comment]
https://github.com/webdriverio/webdriverio/pull/5527

**Comment by christian-bromann** [comment]
Closing. Thanks for unskipping @sethuster !
