### ISSUE TITLE
Move docs to Docosaurus v2

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#5522]
The tool for generating the docs (Docosaurus) has publish a [v2](https://v2.docusaurus.io/) of their framework. We should transition over to use the new version.

**Comment by JapneetSingh5** [comment]
Can I help out with this? I have no past experience with docusaurus, but reading the guide for migration I think I can handle this, with some guidance perhaps.

**Comment by christian-bromann** [comment]
> Can I help out with this?

Absolutely. I will assign this to you. Let me know if you have any questions along the way.

**Comment by JapneetSingh5** [comment]
how do I start off? v2 changes the directory structure

**Comment by christian-bromann** [comment]
> how do I start off? v2 changes the directory structure

It would be good if we could keep the `docs` directory and the `website` stuff separated. Feel free to do any necessary changes to transition to v2.

**Comment by christian-bromann** [comment]
@JapneetSingh5 any updates? Is there anything I can do to help?

**Comment by JapneetSingh5** [comment]
Sorry for not updating, I couldn't figure out a way to keep the directory structure the same. How do I start? On a forked repository?

**Comment by christian-bromann** [comment]
> How do I start? On a forked repository?

Yes. You fork this repository and eventually make a pull request to this one. Please have a read to out [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md). If it is not possible to keep the folder structure than feel free to change it.

**Comment by JapneetSingh5** [comment]
Alright, thanks a lot. I will start working on the migration right away.

**Comment by JapneetSingh5** [comment]
Hi, I was working on the migration and found this thread on Github.

https://github.com/facebook/docusaurus/issues/3035

**Comment by JapneetSingh5** [comment]
Should I try out the CLI?

**Comment by christian-bromann** [comment]
> Should I try out the CLI?

yeah, why not?

**Comment by slorber** [comment]
hi,

https://github.com/facebook/docusaurus/pull/3015

the cli is not released yet, but maybe you can get in touch with @anshulrgoyal to see if automated migration works fine on this site

**Comment by anshulrgoyal** [comment]
Hi,
we are currently working on migration cli. I can help u, just tell us how your site is built.

**Comment by anshulrgoyal** [comment]
> Sorry for not updating, I couldn't figure out a way to keep the directory structure the same. How do I start? On a forked repository?

I can help with that. You can change default path of docs and blogs in the new version. 

```
presets: [
    [
      '@docusaurus/preset-classic',
      {
        docs: {
          homePageId: 'introduction',
          path: '../docs', // this should work
          sidebarPath: require.resolve('./sidebars.js'),
          editUrl:
            'https://github.com/facebook/docusaurus/edit/master/website/',
          showLastUpdateAuthor: true,
          showLastUpdateTime: true,
          remarkPlugins: [require('./src/plugins/remark-npm2yarn')],
        },
        blog: {
          path: '../website-1.x/blog',
          editUrl:
            'https://github.com/facebook/docusaurus/edit/master/website-1.x/',
          postsPerPage: 3,
          feedOptions: {
            type: 'all',
            copyright: `Copyright © ${new Date().getFullYear()} Facebook, Inc.`,
          },
        },
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      },
    ],
  ],

```

**Comment by JapneetSingh5** [comment]
Hi, sorry for the repeated delays. 
I have been working on this for some time now, took me quite a while to understand the process.
On starting the server using star:docusaurus, the updated site flashes for a second and I get this error after that.
<img width="1097" alt="Screen Shot 2020-07-15 at 12 30 56 AM" src="https://user-images.githubusercontent.com/54809290/87466089-503c9200-c633-11ea-9f53-008cda25e0ab.png">
I have added markdown linter config files to turn off the linting, the errors stop showing in the IDE on doing that but not when I start the server.
Also, I had to disable husky to make this PR. Sorry for that too 😕

**Comment by anshulrgoyal** [comment]
@JapneetSingh5 Docusaurus uses MDX  so u need to convert it MDX from MD. Like `<img>` is not valid u need to have JSX so convert it to `<img />`. Migration CLI has a convertor for MD to MDX :).

**Comment by JapneetSingh5** [comment]
@anshulrgoyal but the migration CLI isn't available right? Is there a bypass?

**Comment by anshulrgoyal** [comment]
I am afraid no

**Comment by anshulrgoyal** [comment]
@JapneetSingh5  I ran our migration cli on webdriverio and got this:-
https://unruffled-lumiere-b4796a.netlify.app/

Migration CLi doesn't support pages yet but we are working on it. :)

**Comment by JapneetSingh5** [comment]
> @JapneetSingh5 I ran our migration cli on webdriverio and got this:-
> https://unruffled-lumiere-b4796a.netlify.app/
> 
> Migration CLi doesn't support pages yet but we are working on it. :)

Hi @anshulrgoyal , Docusaurus released a new alpha version recently with the CLI, does it automate MD -> MDX conversion too?

**Comment by anshulrgoyal** [comment]
yeah but it is still in alpha

**Comment by hieuxlu** [comment]
I would like to give it a try. Just need to confirm a few points:
- I assume this is only for v7 docs. v6 and ealier will be moved to a separate subdomains
- From what I read, moving to docosaurus v2 will be a bigger effort than v1 because of MDX, and the CLI is not that great. So that would be the major part of this migration https://v2.docusaurus.io/docs/migration
- v2 is still alpha, and IMHO, is better suited to React projects. Do you think we should take it step by step, moving to Docusaurus v1 first, and v2 later (as Facebook might improve the migration CLI by then)?

**Comment by hieuxlu** [comment]
A sample migration PR to show what's the difference between Docusaurus v2 and v1
https://github.com/facebook/create-react-app/pull/7785/files

IMHO, for our webdirverio docs, v2 provides no real value at all. I would really recommend keeping with v1 first, and migrate to v2 when it's mature.

**Comment by christian-bromann** [comment]
> * I assume this is only for v7 docs. v6 and earlier will be moved to a separate subdomain

Yes. At some point we will create a v6 branch and continue to develop/release v6 from there while working on v7 in master.

> * From what I read, moving to docosaurus v2 will be a bigger effort than v1 because of MDX, and the CLI is not that great.

Haven't looked into MDX too deeply but don't see any major blockers yet.

Please also see the discussion in #6212. Let's identify the work items first and create issues out of these.

**Comment by christian-bromann** [comment]
Closing in favor of #6239
