### ISSUE TITLE
Fail gracefully if devtools protocol is used with Firefox stable

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#5523]
Currently it is only possible to automate Firefox using the devtools protocol in the Nightly edition. Until that interface agent is [accessible in all release channels](https://bugzilla.mozilla.org/show_bug.cgi?id=1606604) we need to ensure that we gracefully fail if Firefox Nightly is not installed.

I would propose to modify the [launch process](https://github.com/webdriverio/webdriverio/blob/master/packages/devtools/src/launcher.js) for Firefox to check the channel and throw if Firefox stable is used.

refs #5519

**Comment by sethuster** [comment]
Good afternoon, would you be able to clarify what you mean by channel?

**Comment by christian-bromann** [comment]
> would you be able to clarify what you mean by channel?

Sure thing, Firefox has [4 different release channels](https://www.mozilla.org/en-US/firefox/channel/desktop) for testing purposes. Currently only Firefox Nightly supports automating the browser with Puppeteer. However they [plan to release] this to all other release channels. Until then we need to ensure to throw an error if someone uses the `devtools` package if Firefox other than Firefox Nightly.

**Comment by mathew-jithin** [comment]
@christian-bromann Added a basic handling for this here. Some doubts:

https://github.com/webdriverio/webdriverio/pull/5528

- Do we need to handle binary name changes (Asking this as need to add specific handling in this case)? As this is a quick fix for a feature that will be fixed in near future, do we need to add this?

**Comment by mathew-jithin** [comment]
@christian-bromann Please have a check on https://github.com/webdriverio/webdriverio/pull/5528 Need a quick review before I fix up the failing tests.

**Comment by sethuster** [comment]
That makes sense.

**Comment by christian-bromann** [comment]
I think this can be closed now. The devtools package now finds Firefox Nightly on all systems and this error shouldn't happen anymore.
