### ISSUE TITLE
Re-attach Puppeteer in devtools service if `reloadSession` was called

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#5524]
This issue is related to #5518

If a user uses the devtools service to run the `cdp` command it will start failing once `reloadSession` was called, e.g.

```js
describe('simple test', () => {
  it(`Simple test verification`, () => {
    browser.reloadSession();

    // @ts-ignore: browser.config does not have the property in types
    browser.cdp('Runtime', 'enable');
  });
});
```

The reason is that reload session closes and reopens the browser so that Puppeteer looses its socket connection to it. The service should use the hook called `onReloadSession` to re-initiate the connection to the devtools protocol.

**Comment by HananArgov** [comment]
from looking at the code, I think i've managed to find out what happens.
there's are differences in `node_modules/webdriver/build/index.js` between `newSession` and `reloadSession`. the main difference, at least in chrome, from what i'm seeing... haven't checked other browsers, is that the capabilities aren't being refreshed, thus the old debug address port stays the same.

for `newSession` we can see that this happens in lines 40-52, while in `reloadSession` there's only `_objectSpread` for the params in lines 76-78

@christian-bromann what do you think?

**Comment by christian-bromann** [comment]
> what do you think?

Seems reasonable to me. Can we update the port?

**Comment by HananArgov** [comment]
it may require a change in webdriver itself, and i'm not sure what's the procedure on that. or I can create a workaround in wdio to handle these cases

**Comment by christian-bromann** [comment]
@HananArgov I wonder if we can tweak the `devtools` package because reloading the session works great using the WebDriver protocol.

**Comment by HananArgov** [comment]
i believe we can, and i'll do it through there then, but I think this will cover other issues. not sure which issues, so we better keep an eye on this

**Comment by christian-bromann** [comment]
> one thing I can say for sure - `global.browser.capabilities` remains the same one as the previous session (even the sessionId doesn't change. it only changes in `global.browser.sessionId`)

Maybe that is an issue that can be fixed in a different PR. Theoretically you should get the same capabilities if you request a session with the same capabilities but that is not always possible. Therefor `global.browser.capabilities` should be either updated or an error should be thrown if not the same capabilities were provided.

**Comment by HananArgov** [comment]
it's not the provided capabilities that is the issue. it's the default capabilities, that's coming from the browser itself.
from what i'm seeing I can bypass this by going to `chrome://version` but this (sadly) works only when not using headless mode. I need to find a way to refresh the browser capabilities, and it seems this needs to be addressed in webdriver itself (as mentioned, new sessions and reloaded session aren't updating the capabilities correctly).

**Comment by HananArgov** [comment]
i've requested an online meeting with you if it's ok, so I could show you the details

**Comment by christian-bromann** [comment]
Let's continue our conversation in the PR #5651
