### ISSUE TITLE
Add docs how to transition from Chai to expect-webdriverio

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#5537]
Currently it is impossible to use Chai and expect-webdriverio at the same time. Scripts like:

```js
const expect = require('chai').expect;

describe('Homepage', function () {
    it('should assert', function () {
        browser.url('./');

        expect(browser).toHaveUrl('/login');
        expect(browser.getUrl()).to.include('/login')
    });
});
```

will fail because expect will be overwritten by one or the other assertion library. Let's add some docs how to transition between both or how to run both libraries by importing chai using a special variable like:

```js
const expectChai = require('chai').expect;

describe('Homepage', function () {
    it('should assert', function () {
        browser.url('./');

        expect(browser).toHaveUrl('/login');
        expectChai(browser.getUrl()).to.include('/login')
    });
});
```

**Comment by caweidmann** [comment]
It might be easier to migrate the other way round, e.g. have `expectWdio` set and then keep the `expect` for Chai. It would then require one global find and replace at the end to move off Chai.

E.g. here's what we did:

```
// wdio.conf.js
before: function before() {
  require('expect-webdriverio');
  global.wdioExpect = global.expect;
  const chai = require('chai');
  global.expect = chai.expect;
}
```
That way everything keeps working without having to change any files. Slowly we can go through each file and replace expectations with the `wdioExpect`. Once all expects have been replaced in this way a global find and replace all `wdioExpect => expect` will do the trick and the before hook can be deleted.

**Comment by christian-bromann** [comment]
@caweidmann makes sense to me. Mind adding a section to https://webdriver.io/docs/assertion.html with some documentation on how to transition from Chai to expect-webdriverio?

**Comment by caweidmann** [comment]
Yeah can do. Will try and find some time this week.

**Comment by christian-bromann** [comment]
This has been added thanks to @caweidmann and #5549
