### ISSUE TITLE
Jasmine missing grep and invertGrep from typescript types definition

### ISSUE THREAD

**Issue by mvgiacomello** [webdriverio/webdriverio#5538]
*Environment:*

- WebdriverIO version: 6.1.20
- Mode: WDIO Testrunner
- If WDIO Testrunner, running sync/async: sync
- Node.js version: v12 lts
- NPM version: 6.14.4
- YARN version: 1.12.4
- Browser name and version: Chromium 83.0.4103.0
- Platform name and version: ubuntu 20.04 lts / docker-node-lts
- Additional wdio packages used (if applicable): @wdio/jasmine-framework@6.1.17

*Describe the bug:*

Based on this file and the following documentation, I should be able to use `grep` and `invertGrep` when using the Jasmine framework.

https://github.com/webdriverio/webdriverio/blob/b13e859609f6bcab8654d1ebea14b45ec1ae6265/packages/wdio-jasmine-framework/jasmine-framework.d.ts#L79

Docs:
- Grep: https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-jasmine-framework/README.md#L58

- Inverted Grep: https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-jasmine-framework/README.md#L64

**Comment by sethuster** [comment]
I'll give this a go
