### ISSUE TITLE
dragAndDrop is not using the duration argument when using the JSON Wire protocol

### ISSUE THREAD

**Issue by erwinheitzman** [webdriverio/webdriverio#5541]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5 and 6

Since this issue is in both versions, I would like to cherrypick this to the LTS release as well.

**Describe the bug**
The dragAndDrop command accepts a `duration` argument.
When using the webdriver protocol is uses the duration as expected.
When using the json wire protocol the duration is not used.

**Expected behavior**
Use the duration for either protocol

**Comment by christian-bromann** [comment]
@erwinheitzman I don't think it is technically possible to add a duration for the JSON Wire protocol version of `dragAndDrop`. It uses the protocol methods `moveTo` or `moveToElement` which don't accept any duration parameters.

**Comment by erwinheitzman** [comment]
@christian-bromann no but we can add a pause before executing the buttonUp command :)

**Comment by christian-bromann** [comment]
> no but we can add a pause before executing the buttonUp command :)

Good idea! This is a great first issue. If someone wants to pick this up we are happy to help you!

**Comment by mathew-jithin** [comment]
@christian-bromann @erwinheitzman Would like to pick this up. Can you please help me with a small detail on the same as mentioned?

**Comment by christian-bromann** [comment]
> Can you please help me with a small detail on the same as mentioned?

What detail?

**Comment by mathew-jithin** [comment]
> @christian-bromann no but we can add a pause before executing the buttonUp command :)

@christian-bromann As like, what is expected here?

**Comment by christian-bromann** [comment]
I believe what @erwinheitzman was saying is that we can add a "pause" with the duration of the duration parameter before the [buttonUp command is called](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/commands/element/dragAndDrop.js#L68). Is that right?

**Comment by mathew-jithin** [comment]
Working on this. Never got time to check after I last commented. Will try to give a pull by friday.

**Comment by christian-bromann** [comment]
Any updates @mathew-jithin ?

**Comment by mathew-jithin** [comment]
@christian-bromann Sorry, was equipped with some work in office these days. Forgot to check on this.

I will try to give a pull by Wednesday. Will surely check it out today :-)

**Comment by erwinheitzman** [comment]
@mathew-jithin awesome, if you need any help you can reach out to me on Gitter

**Comment by mathew-jithin** [comment]
Thanks a lot @erwinheitzman Actually, is there any possibility that you have a sample code which was written to test the existing functionality?

**Comment by christian-bromann** [comment]
@mathew-jithin please check out the unit tests for this command: https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/tests/commands/element/dragAndDrop.test.js

**Comment by mathew-jithin** [comment]
Thanks @christian-bromann

**Comment by mathew-jithin** [comment]
https://github.com/webdriverio/webdriverio/pull/5783

**Comment by christian-bromann** [comment]
Let's continue convo in #5783
