### ISSUE TITLE
Timeframe for v3 ?

### ISSUE THREAD

**Issue by rasmusbergpalm** [webdriverio/webdriverio#555]
Hey. Thanks for the great library.
Any idea when we can expect the v3 to be released? I'm anxious to get my hands on the `waitUntil`

**Comment by christian-bromann** [comment]
Thanks so much @rasmusbergpalm,
you can get an idea about when it's going to be released on the [v3 milestone page](https://github.com/webdriverio/webdriverio/milestones/v3). I stopped making predictions about release dates. All I can say is that all big puzzle pieces are in place (promise support, wdio runner, multibrowser, reporters, generator support). There are only some minor features missing + testing + documentation. So stay tuned. Feel free to checkout the `v3` branch to play around with it and let me know if you find any bugs. Cheers :wink:

**Comment by rasmusbergpalm** [comment]
Thanks!
