### ISSUE TITLE
Add Autocompletion for Custom Commands for IDEA IntelliJ, WebStorm, and VSCode

### ISSUE THREAD

**Issue by caoxu2000** [webdriverio/webdriverio#5550]
This is an enhancement request on top of our existing autocompletion feature for a few major IDEs: [autocompletion](https://webdriver.io/docs/autocompletion.html)

I would like an IDE plugin/extension similar to Cypress Helper VSCode extension: [Cypress Helper](https://marketplace.visualstudio.com/items?itemName=Shelex.vscode-cy-helper) so that when I right click in the IDE it brings up context menu with option of 'Go to Custom Command Definition' such as screenshot below:
<img width="434" alt="Screen Shot 2020-06-26 at 8 09 15 AM" src="https://user-images.githubusercontent.com/3377303/85873246-b1d0b580-b785-11ea-85c7-5e5a6d01ab99.png">

**Comment by christian-bromann** [comment]
@caoxu2000 I think it makes sense to have such a plugin for VSCode that allows to jump into the definition of a custom command. A bunch of functionality from the Cypress plugin however seems to be pretty Cucumber related and should work with a respective Cucumber plugin as well.

@caoxu2000 you want to take a stab at this?

**Comment by christian-bromann** [comment]
Moving into a GitHub discussion: #6277
