### ISSUE TITLE
Memory leak when using screenshot function and deleting session

### ISSUE THREAD

**Issue by websaid** [webdriverio/webdriverio#5551]
**Environment (please complete the following information):**
 - **WebdriverIO version:6.0.12** 
 - **Mode:Standalone**
 - **Node.js version:13.10.1**
 - **NPM version:6.14.5**
 - **Browser name and version:Chrome 83**
 - **Platform name and version:Windows 10**
 - **Additional wdio packages used (if applicable):wdio-image-comparison-service**

**Config of WebdriverIO**
`{
        "runner": "local",
        "logLevel": "trace",
        "waitforTimeout": 10000,
        "connectionRetryTimeout": 90000,
        "connectionRetryCount": 3
    }`

**Describe the bug**
Using the screenshot function and deleting the browser with browser.deleteSession() will leave data behind. When run in standalone mode where you initialize multiple browsers in a sort of custom test runner, this memory leak will suddenly lead to a crash.

**To Reproduce**
Check the issue I posted on wdio-image-comparison github: [https://github.com/wswebcreation/webdriver-image-comparison/issues/72](https://github.com/wswebcreation/webdriver-image-comparison/issues/72)

**Expected behavior**
The chunk of data gets cleared with the use of browser.deleteSession()

> Please use the correct markdown

**Comment by christian-bromann** [comment]
You have posted only some screenshots. What I am asking for is to post the actual heapdump and a reproducible example in this thread for visibility.

**Comment by Westsaid** [comment]
**Reproducible example**
`const { remote } = require("webdriverio");
let browsers = []
const heap = require("heapdump")

callTests(new Array(10)).then(erg => {
  console.log("Done")
})
async function main(nsc, i) {
    //console.log(`Started test: ${testcase}@${nsc} (${i+1}/${allNSC.length})`)
    const browser = await remote({
        capabilities : {
            browserName: "chrome",
        },
        logLevel: "error",
        outputDir: __dirname + "../../../logs/"
    }).catch(err => console.log(err));
    browsers[i] = browser


    global.browser = browser;
    let url = "https://www.nytimes.com/"
    await browser.url(url)
    await heap.writeSnapshot(__dirname + "/"+i+"before.heapsnapshot")
    await browser.takeScreenshot()
    await heap.writeSnapshot(__dirname + "/"+i+"after.heapsnapshot")

    await browser.deleteSession()
    await delete browser
    await delete browsers[i]
}

function callTests(arr, i) {
    return new Promise(res => {
        if (i == undefined) i = 0
        let error = false
        main(arr[i], i).catch(async e => {
            console.error(e, arr[i])
            error = e
            await browsers[i].deleteSession();
            await delete browsers[i]
        }).then(async erg => {
            if (i < arr.length - 1) return res(callTests(arr, ++i))
            else res()
        });
    })
}`

Here are the important heapdumps created by this script: 
[9before.zip](https://github.com/webdriverio/webdriverio/files/4845142/9before.zip)
 Thank you!

**Comment by christian-bromann** [comment]
@Westsaid we always appreciate help on such issues as the maintainers have their own priorities and contributions to make. Any help on this is greatly appreciated!

**Comment by erwinheitzman** [comment]
Spawning the instance, going to a url and then killing the browser while running a script to log the memory of the Node process (process.memoryUsage():
```
❯ node ./test.js
❯ node ./test.js
The script uses approximately 33.54 MB
The script uses approximately 35.85 MB
The script uses approximately 27.11 MB
The script uses approximately 27.39 MB
The script uses approximately 27.39 MB
The script uses approximately 27.39 MB
The script uses approximately 27.4 MB
The script uses approximately 27.4 MB
The script uses approximately 22.87 MB
The script uses approximately 23.13 MB
The script uses approximately 23.14 MB
The script uses approximately 23.33 MB
The script uses approximately 23.33 MB
The script uses approximately 23.34 MB
The script uses approximately 23.34 MB
The script uses approximately 23.34 MB
The script uses approximately 23.34 MB
The script uses approximately 23.35 MB
The script uses approximately 23.35 MB
```

Doing the same but also creating 80 screenshots of the web page:
```
The script uses approximately 33.08 MB
The script uses approximately 35.41 MB
The script uses approximately 36.36 MB
The script uses approximately 23.95 MB
The script uses approximately 27.79 MB
The script uses approximately 23.72 MB
The script uses approximately 27.1 MB
The script uses approximately 30.15 MB
The script uses approximately 26.01 MB
The script uses approximately 29.2 MB
The script uses approximately 32.61 MB
The script uses approximately 35.54 MB
The script uses approximately 38.45 MB
The script uses approximately 41.86 MB
The script uses approximately 44.79 MB
The script uses approximately 24.29 MB
The script uses approximately 24.3 MB
The script uses approximately 24.3 MB
The script uses approximately 24.3 MB
```

I don't think there's anything to gain here.

**Comment by erwinheitzman** [comment]
The script used:
```js
const { remote } = require("webdriverio");

async function main() {
  const browser = await remote({
    capabilities: {
      browserName: "chrome",
    },
    logLevel: "error",
  });
  await browser.url("https://duckduckgo.com");
    for (let i = 0; i < 80; i++) {
      await browser.takeScreenshot();
    }
  await browser.deleteSession();
}

main();
let interval = setInterval(() => {
  const used = process.memoryUsage().heapUsed / 1024 / 1024;
  console.log(
    `The script uses approximately ${Math.round(used * 100) / 100} MB`
  );
}, 1000);
setTimeout(() => {
  clearInterval(interval);
}, 20000);

```

**Comment by erwinheitzman** [comment]
I have also created some memory dumps and do not see those strings (screenshots) in memory.
