### ISSUE TITLE
Any way to take screenshot on all jasmine expect() failures?

### ISSUE THREAD

**Issue by rasmusbergpalm** [webdriverio/webdriverio#556]
It's a fairly long shot, but maybe you have an idea.
I'm using jasmine together with webdriverio and I wish to capture screenshots whenever there is an expectation failure for debugging purposes. Any good ideas?

**Comment by christian-bromann** [comment]
I've seen people using the error event to capture screenshots:
```js
browser.on('error', function() {
    browser.saveScreenshort('error.png');
});
```

**Comment by rasmusbergpalm** [comment]
Yea I'm doing that but it's not capturing the jasmine failed expects, since
they're not errors

**Comment by rasmusbergpalm** [comment]
EUREKA!
This is to the next unlucky soul desperately googling for this like I did for a couple of hours.
Here's what you can do
```
var old = jasmine.Spec.prototype.addExpectationResult;
		jasmine.Spec.prototype.addExpectationResult = function(passed, data) {
			if (!passed) {
				errorFunc('I was called ma!');
			}
			return old.call(this, passed, data);
		};
```

**Comment by christian-bromann** [comment]
Awesome @rasmusbergpalm 
I will thing about embedding it into the wdio runner as it might be a common use case.

**Comment by SchwaFa** [comment]
@christian-bromann 
That would be definitely very helpful!!

**Comment by christian-bromann** [comment]
@rasmusbergpalm thanks for sharing this. Indeed this would be helpful. Though it is a bit problematic as we can't execute async functions in there. So if you want to save a screenshot it might happen that the state of the site has already changed. I will see if we can tweak this so it works with promises.

**Comment by christian-bromann** [comment]
@rasmusbergpalm have you been able to take a screenshot?

**Comment by rasmusbergpalm** [comment]
Yea works great. Although we can't really wait for the screenshot to finish, so there might be some race conditions, but we havn't seen them yet.

**Comment by rasmusbergpalm** [comment]
Here's what we include in each test to wire it all together
```java
var WebdriverIO = require('webdriverio');

var driver;
var getRandomId = function () {
	return Math.random().toString(36).substring(11);
};

var recordError = function (errorId) {
	driver.log('browser', function (err, log) {
		console.error("browser logs:", log.value);
	});
	driver.saveScreenshot('./build/junit-jasmine-integration/' + errorId + '-error.png');
};

var old = jasmine.Spec.prototype.addExpectationResult;
jasmine.Spec.prototype.addExpectationResult = function (passed, data) {
	if (!passed) {
		var errorId = getRandomId();
		data.message = 'Id: >>>' + errorId + '<<< ' + data.message;
		recordError(errorId);
	}
	return old.call(this, passed, data);
};

module.exports = {
	
	create: function () {
		driver = WebdriverIO.remote({
			desiredCapabilities: {
				browserName: 'chrome',
				loggingPrefs: {'browser': 'ALL'}
			}
		});
		driver.init();
		driver.setViewportSize({
			width: 1024,
			height: 768
		});

		driver.on('error', function (e) {
			expect(e.body.value.class + ': ' + e.body.value.message).toBeNull();
		});
		
	}
};
```

**Comment by christian-bromann** [comment]
that's what I thought. Taking a screenshot takes usually one to couple of seconds. If you open a new page right after you could be screwed. I will do some experimentations but there is apparently no way to defer the execution in jasmine

**Comment by christian-bromann** [comment]
@rasmusbergpalm @SchwaFa implemented that. Gonna publish it tomorrow

**Comment by SchwaFa** [comment]
Awesome! 
Thanks a lot! :)

**Comment by SchwaFa** [comment]
But unfortunately, it seems that it doesn't work. The expectationResultHandler never gets called.

**Comment by christian-bromann** [comment]
mhm did you update to `v3.1.0`?

**Comment by SchwaFa** [comment]
Yes, I did. ;)

**Comment by christian-bromann** [comment]
mhm .. I just installed the current npm version and tried it and it worked. And you are __not__ using an assertion library like chai because this only works if you use jasmine assertions like `expect(a).toBe(b);`

**Comment by SchwaFa** [comment]
Oh, my mistake. I used the globally installed webdriverio package, which was the old version. ;) Sorry!
Everything works fine now. ;)
