### ISSUE TITLE
wdio-allure-reporter history should be configurable & not limited to 5 items

### ISSUE THREAD

**Issue by ania-s** [webdriverio/webdriverio#5561]
**Is your feature request related to a problem? Please describe.**
The history of a test is limited to 5 items only hence with many test executions per day it's hard to check how the trend looks like.

**Describe the solution you'd like**
The number of history items should be configurable and in case it exceeds the actual number of available history test executions it should take the available ones.

**Comment by BorisOsipov** [comment]
It is not related to wdio reporter. See https://github.com/allure-framework/allure2/issues/347

**Comment by ania-s** [comment]
@BorisOsipov any clue why with the latest wdio-allure-reporter package my history is still limited to 5 and not 20? Is there sth I have to do?

**Comment by BorisOsipov** [comment]
Sorry, I don't know :(

**Comment by BorisOsipov** [comment]
@ania-s check that you have latests allure-commadline https://docs.qameta.io/allure/#_installing_a_commandline

**Comment by ania-s** [comment]
Yes I have the latest allure-commadline as well :/
