### ISSUE TITLE
Opera And Chromium Edge are not working

### ISSUE THREAD

**Issue by soumyaevan** [webdriverio/webdriverio#5567]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** Latest
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 8.12.0
 - **NPM version:** 6.14.0
 - **Browser name and version:** opera 69.0.3686.49, Edge  83.0.478.58
 - **Platform name and version:** OS X 10.15.5
 - **Additional wdio packages used (if applicable):**  @wdio/selenium-standalone service

**Config of WebdriverIO**
An example of how you configured WebdriverIO config
capabilities: [{
    
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        maxInstances: 5,
        //
        browserName: 'opera',
        // If outputDir is provided WebdriverIO can capture driver session logs
        // it is possible to configure which logTypes to include/exclude.
        // excludeDriverLogs: ['*'], // pass '*' to exclude all driver session logs
        // excludeDriverLogs: ['bugreport', 'server'],
        
        "goog:chromeOptions": {
            "binary": "/Applications/Opera.app"
          }
    }],
services: ['selenium-standalone'],
    seleniumArgs: {
        javaArgs: [
          '-Dwebdriver.opera.driver=/Users/soumyasen/Downloads/operadriver_mac64/operadriver'
        ]
      },
**Describe the bug**
Opera nd Edge browser are not openning. Getting error stating "Unable to create new service"
**To Reproduce**

try to launch edge and opeara latest version in wdio

**Expected behavior**
Edge and opera browser should be launched

**Log**
https://gist.github.com/soumyaevan/1f2e06bd4d74c848515fd188387ead07

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
The session requests fails due to:

> Request failed with status 500 due to session not created: Unable to create new service: OperaDriverService

Seems that the driver can't start the browser. This is usually not a problem within WebdriverIO. Please look into the driver logs as they may give indication of why the session can't be started.
