### ISSUE TITLE
moveTo() throws exception due to floating value of newXOffset or newYOffset variables

### ISSUE THREAD

**Issue by monil20** [webdriverio/webdriverio#5568]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.1.16
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.16.3
 - **NPM version:** 6.14.4
 - **Browser name and version:** Chrome 83.0.4103.116
 - **Platform name and version:** Windows 10

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
When passing the float value for `options.xOffset` and/or `options.yOffset`, the function throws exception

**Reason**
While calculating `newXOffset` or `newYOffset`, the `parseInt()` has been applied before subtracting the `scrollX` or `scrollY` respectively which might again result in float if the value of `scrollX` or `scrollY` is float.
[Problem at L28 in moveTo.js](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/commands/element/moveTo.js#L28)

**To Reproduce**
Provide `options.xOffset` and/or `options.yOffset` in `moveTo()` such that the `const scrollX` and/or `const scrollY` variables in `moveTo()` are of type float

**Expected behavior**
`options.x` and/or `options.y` must allow float without error as the expected type is `Number` as per the [official documentation](https://webdriver.io/docs/api/element/moveTo.html)

**Comment by christian-bromann** [comment]
Hey,
thanks for filing the issue. This seems indeed like bug. We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by christian-bromann** [comment]
Will close this issue as an PR is already provided in #5572.

**Comment by monil20** [comment]
Hey,
Thanks for resolving it this soon. Really appreciate the help and activeness of this community. 🍻 I had been stuck because of this issue and was thinking of a way out.

Also, could you let me know the version in which this change would roll out?

**Comment by christian-bromann** [comment]
@monil20 it has not been fixed yet. I closed the issue because we have a PR for it. Please follow #5572 for updates.

**Comment by tehhowch** [comment]
@christian-bromann I think this bug also affects v5, at least for the `Element#dragAndDrop` method when using relative XY offset. I have not tested explicit `moveTo` with floating-point arguments, but did encounter issues with fractional XY offsets in dragAndDrop.
