### ISSUE TITLE
improve Sauce Labs integration

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#557]
Includes:
- change job status automatically
- ~~dump assets into directory~~
- output sauce link in stdout

**Comment by christian-bromann** [comment]
Done. I scratched the asset thing to move forward. That should be a different topic for a different milestone.

Closing as this is done.

**Comment by saulshanabrook** [comment]
@christian-bromann Should I open a new issue for implementing "change job status automatically" ?

**Comment by christian-bromann** [comment]
That should work see https://github.com/webdriverio/webdriverio/blob/master/lib/runner.js#L137
