### ISSUE TITLE
element.MoveTo() without configured parameters is not working on V6

### ISSUE THREAD

**Issue by LMFDias** [webdriverio/webdriverio#5571]
**Environment (please complete the following information):**

**WebdriverIO version:** V6
**Mode:** standalone
**If WDIO Testrunner, running sync/async:** sync
**Node.js version:** v10.17.0
**NPM version:** v6.11.3
**Browser name and version:** chrome,
**Chrome Version:** 83.0.4103.116

**Config of WebdriverIO :**
    "@wdio/cli": "^6.1.24",
    "@wdio/jasmine-framework": "^6.1.23",
    "@wdio/local-runner": "^6.1.20",
    "@wdio/selenium-standalone-service": "^6.1.14",
    "@wdio/spec-reporter": "^6.1.14",
    "@wdio/sync": "^6.1.14",

**Describe the bug**
On V6, $myElement.moveTo() (without configured Parameters) is not working. The mouse does not move . If I do $myElement.click(), using the same element, it's working.  

**To Reproduce**
$myElement.moveTo() 

**Expected behavior**
If $myElement.click() works, it is an indicator that the element is being found. So $myElement.moveTo() should works too.

**Log**
Is not logging any errors despite test failing, and that is because the mouse does not move

**Comment by christian-bromann** [comment]
> On V6, $myElement.moveTo() (without configured Parameters) is not working.

Can you please elaborate what you think is not working? Are you expecting some sort of hove pop up? A reproducible example would be helpful.

> Is not logging any errors despite test failing, and that is because the mouse does not move

Logs would be still helpful to get an idea what is going on. Please provide them.

**Comment by LMFDias** [comment]
I will close the issue, 
I had misconfigured the resolution.
Thank you
