### ISSUE TITLE
Unable to access mochaOpts in wdio config file after upgrading the webdriverio version to 6

### ISSUE THREAD

**Issue by UrvashiSri** [webdriverio/webdriverio#5575]
This bug started after upgrading from webdriver IO 5 to webdriver IO 6.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.1.22
 - **Mode:** Standalone mode 
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 12.16.2
 - **NPM version:** 6.14.4
 - **Browser name and version:**  Chrome 83
 - **Platform name and version:** OS X(Catalina)
 - **Additional wdio packages used (if applicable):**   
     "@wdio/cli": "^6.1.22",
    "@wdio/local-runner": "^6.1.22",
    "@wdio/mocha-framework": "^6.1.19",
    "@wdio/selenium-standalone-service": "^6.1.14",
    "@wdio/spec-reporter": "^6.1.14",
     "webdriver": "^6.1.17"

**Config of WebdriverIO**
```
import {
  getConfigurationOptions
} from '../setup/browser';

const config: WebdriverIO.Config = {
    mochaOpts: {
    ui: 'bdd',
    timeout: 60000
  },
};
export { config };

```
Something similar to this -> https://github.com/pako88/wdio-mocha-typescript/blob/master/config/base.conf.ts

**Describe the bug**
I am getting error for mocha opts 
mochaOpts: {
    ui: 'bdd',
    timeout: 60000
  },

in config file. 
Error is: 
<img width="613" alt="image" src="https://user-images.githubusercontent.com/38689585/86597603-de5dac00-bf93-11ea-80ee-358c95c06bdf.png">

It was working fine with v5. 

**To Reproduce**
I have upgraded the webdriverIO version from 5 to 6. 

**Expected behavior**
mochaOpts should work.

**Additional context**
I have tried to find the cause for this. I get to know that mochaOpts are not present in Options interface.
I have looked into webdriver repo. I could not find mocha opts in Interface Options. https://github.com/webdriverio/webdriverio/blob/master/scripts/templates/webdriverio.tpl.d.ts

I checked for same file in WebdriverIO 5. MochaOpts were present in Interface Options . https://github.com/webdriverio/webdriverio/blob/v5.22.5/scripts/templates/webdriverio.tpl.d.ts

> Please use the correct markdown

**Comment by christian-bromann** [comment]
Hey,
thanks for filing the issue. This seems indeed like bug. We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!
