### ISSUE TITLE
Report creates empty file when mocha framework skips test(s)

### ISSUE THREAD

**Issue by sknight80** [webdriverio/webdriverio#5577]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [6.1.24]
 - **Mode:** [Standalone mode]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [14.5.0]
 - **NPM version:** [6.14.5]
 - **Browser name and version:** [ChromeDriver 83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416})]
 - **Platform name and version:** [MacOS Catalina: 10.15.5 (19F101)]
 - **Additional wdio packages used (if applicable):** [@wdio/cli@6.1.22, @wdio/local-runner@6.1.22, @wdio/mocha-framewor@6.1.19, @wdio/spec-reporter@6.1.14, @wdio/sync@6.1.14, ]

**Config of WebdriverIO**
```
exports.config = {
    runner: 'local',
    specs: [
        './test/specs/**/*.js'
    ],
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    maxInstances: 10,
    capabilities: [{
        maxInstances: 5,
        browserName: 'chrome',
    }],
    logLevel: 'info',
    bail: 0,
    baseUrl: 'http://localhost',
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    services: ['chromedriver'],
    framework: 'mocha',
    reporters : ['spec',
    ['allure', {
      outputDir                            : 'allureReports',
      disableWebdriverStepsReporting       : true,
      disableWebdriverScreenshotsReporting : false,
      stdout                               : true
    }],
    ['junit',
      {
        outputDir : './test_output'
        // outputFileFormat(opts) { // optional
        //   return `results-${opts.cid}.${opts.capabilities}.xml`;
        // }
      }]
  ],
   mochaOpts: {
        ui: 'bdd',
        timeout: 60000,
    retries   : false,
    trace     : true,
    fullTrace : true,
    grep      : '@flaky',
    reporter  : 'spec',
    invert    : true
    }
}
```

**Describe the bug**
At least one bug here which is in `junit-reporter`:  When mocha filter out the test that we don't need to run (tag filter), the reporter generates an empty file (`wdio-0-1-junit-reporter.log`) that cause a problem in Jenkins later.

**To Reproduce**

cat test/specs/basic.js:
```
describe('webdriver.io page', () => {
    it('should have the right title', () => {
        browser.url('https://webdriver.io')
        expect(browser).toHaveTitle('WebdriverIO · Next-gen browser and mobile automation test framework for Node.js');
    })
})

describe.skip('skip test', () => {
  it('should skip', () => {
    browser.url('https://google.com')
  });
});
```
cat test/specs/skip.js 
```
describe('skip test', () => {
  it('should skip @flaky', () => {
    browser.url('https://google.com')
  });
});
```

Run the following command:
```
npx wdio wdio.conf.js
```

**Expected behavior**
The reporter should generate a valid empty XML file as it does in V5.

**Log**
If applicable, add logs to help explain your problem.
[Console log](https://gist.github.com/sknight80/377ffdc82f90a5233c0ef101a8b0a3e6)

**Additional context**
In V5, the reporting workflow worked fine in this case; however, I wasn't able to track down the problem besides this small test project.

**Comment by christian-bromann** [comment]
Hey,
thanks for filing the issue. This seems indeed like bug. We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by sushantsoni5392** [comment]
Hey
This is still an issue, an empty xml file is generated by the junit reporter when jasmine specFilter is used to filter out the specs.
This happens when the initial number of workers started by wdio is more than the actual number of specs to be run. This could happen because some of the specs may get filtered out and may need not be run.

**Comment by christian-bromann** [comment]
@sushantsoni5392 mind raising a PR with a fix?

**Comment by sushantsoni5392** [comment]
@christian-bromann Would love to contribute, never done that. Is this well suited for a beginner?
