### ISSUE TITLE
Using the sauce service with sauceConnect enabled forces a W3C session

### ISSUE THREAD

**Issue by 36degrees** [webdriverio/webdriverio#5585]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.1.19
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.15.0
 - **NPM version:** 6.13.4
 - **Browser name and version:** N/A
 - **Platform name and version:** N/A
 - **Additional wdio packages used (if applicable):** @wdio/cli@6.1.19, @wdio/local-runner@6.1.19, @wdio/mocha-framework@6.1.19, @wdio/sauce-service@6.1.16, @wdio/selenium-standalone-service@6.1.14, @wdio/spec-reporter@6.1.14, @wdio/static-server-service@6.1.14

**Config of WebdriverIO**
```
exports.config = {
  outputDir: './logs/',
  specs: ['./test/integration/**/*.js'],
  baseUrl: 'http://localhost:4567',
  screenshotPath: './screenshots/',
  user: process.env.SAUCE_USERNAME,
  key: process.env.SAUCE_ACCESS_KEY,
  capabilities: [
    {
      browserName: 'internet explorer',
      version: '9.0',
      platform: 'Windows 7'
    }
  ],
  services: [
    ['static-server', {
      folders: [
        { mount: '/', path: './examples' },
        { mount: '/dist/', path: './dist' }
      ],
      port: 4567
    }],
    ['sauce', {
      sauceConnect: true
    }]
  ],
  reporters: ['spec'],
  framework: 'mocha',
  mochaOpts: { timeout: 30 * 1000 }
}
 ```

**Describe the bug**

Using the sauce service with `sauceConnect: true` forces a W3C session as the `tunnelIdentifier` is passed inside the `sauce:options` object:

https://github.com/webdriverio/webdriverio/blob/059db83e98ceda09dec7971b6d79baebee31185d/packages/wdio-sauce-service/src/launcher.js#L61-L65

This means that it is not possible to use the `sauceConnect` option with a browser that does not support W3C.

**To Reproduce**

Run tests using Webdriver with the config above (equivalent to the config used in https://github.com/alphagov/accessible-autocomplete/tree/dad123358a0b9feae7b40ebd1950355a34d77277)

**Expected behavior**

The tests should run under the JSON wire protocol, as `sauce:options` is not present in the defined config.

**Actual behaviour**

The tests run under the W3C protocol, resulting in:

> "Illegal key values seen in w3c capabilities: `[platform, version]`"

(https://app.saucelabs.com/tests/d4ddc769c276436dad278f0d472d2dfa#0)

**Log**

```
> cross-env NODE_ENV=test wdio test/wdio.config.js --logLevel trace

Execution of 1 spec files started at 2020-07-01T08:07:13.723Z

(node:93731) ExperimentalWarning: The dns.promises API is experimental
(node:93731) ExperimentalWarning: The fs.promises API is experimental
[0-0] (node:93744) ExperimentalWarning: The dns.promises API is experimental
[0-0] (node:93744) ExperimentalWarning: The fs.promises API is experimental
[0-0] { outputDir: './logs/',
  specs: [ './test/integration/**/*.js' ],
  capabilities:
   [ { browserName: 'internet explorer',
       build: undefined,
       version: '9.0',
       platform: 'Windows 7' } ],
  baseUrl: 'http://localhost:4567',
  screenshotPath: './screenshots/',
  services: [ [ 'static-server', [Object] ], [ 'sauce', [Object] ] ],
  reporters: [ 'spec' ],
  framework: 'mocha',
  mochaOpts: { timeout: 30000 },
  user: 'tvararu-alphagov',
  key: '[REDACTED]' }
[0-0] RUNNING in internet explorer - /test/integration/index.js
[0-0]  Error:  Failed to create session.
Infrastructure Error -- The Sauce VMs failed to start the browser or device.
For more info, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages
[0-0] FAILED in internet explorer - /test/integration/index.js

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:02:29
```

**Additional context**

Full context can be found in this [pull request to update our project to use WebdriverIO v6](https://github.com/alphagov/accessible-autocomplete/pull/450).

We cannot use the W3C protocol to test with IE9 because we get the error:

> No matching capability sets found. Unable to match capability set `0: selenium:webdriver.remote.quietExceptions` is an unknown extension capability for IE

We think this is caused by https://github.com/SeleniumHQ/selenium/issues/7479.

**Comment by christian-bromann** [comment]
@36degrees thanks for filing the issue? Why would you want to not use the WebDriver protocol? Are you required to test on old browsers?

**Comment by 36degrees** [comment]
> Why would you want to not use the WebDriver protocol? Are you required to test on old browsers?

At the minute, we aim to support IE9+.

We don't seem to be able to use the W3C protocol to test with IE9 because we get the error:

```
No matching capability sets found. Unable to match capability set 0: selenium:webdriver.remote.quietExceptions is an unknown extension capability for IE
```

We think this is caused by SeleniumHQ/selenium#7479. We were not seeing this issue when using an older version of Webdriver, because it was using JSONWP.

At the minute, our options seem to be:

- Try and fix Webdriver so that we can continue to use the JSON wire protocol when testing with IE9 (this PR)
- Hold off on updating Webdriver until we can drop IE9 support
- Start the Sauce Connect client outside of wdio, and pass the tunnel identifier in manually 

I appreciate that JSONWP support does not seem to be mentioned anywhere in the documentation, and so this may not be something you choose to fix, in which case we'll look at the other 2 options. However, we thought it was worth raising as the behaviour is 'surprising'  – in that it's unexpected that using `sauceConnect: true` would change the protocol being used (and it's really hard to debug!)

At the minute it seems like it's _sort of_ possible to use JSONWP with Webdriver, except for these edge cases where things break unexpectedly. I wonder therefore if you do choose not to fix this whether anything could be done to make the behaviour more predictable or explicit?

(Apologies if I've missed something here – I wasn't involved with the original implementation, and a lot of the investigative work has been done by a colleague, so I am learning a lot about how this works as I go!)

**Comment by christian-bromann** [comment]
@36degrees thanks for providing more context. I think this can be fixed. Instead of just setting `sauce:options` in the capabilities we could add some logic that would check for JSONWireProtocol specific capabilities, e.g. `platform` or `version` and if found just directly sets the custom sauce capabilities to it. Would you be up for helping us on this one? I happy to provide any supported needed.

**Comment by lfalkner** [comment]
This is helpful for us too; we had some issues with saucelabs and w3c with appium, and we're seeing issues connecting after upgrading to wdio v6

**Comment by christian-bromann** [comment]
Let's continue the conversation in #5610
