### ISSUE TITLE
browser.getLogTypes() giving error in chrome browser

### ISSUE THREAD

**Issue by soumya-contentsquare** [webdriverio/webdriverio#5587]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** latest
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:**  sync
 - **Node.js version:** 12.18.2
 - **NPM version:** 6.14.5
 - **Browser name and version:** 83.0
 - **Platform name and version:** Mac Catlina
 - **Additional wdio packages used (if applicable):**@wdio/selenium-standalone service

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
I am trying to capture the browser logs inside network tab

**To Reproduce**
const logTypes = browser.getLogTypes() // ['browser', 'driver']
        logTypes.forEach(logType => {
        console.log(browser.getLogs(logType))
})

[Include code or an example repository that can easily be set up]

**Expected behavior**
it should show the logs

**Log**
ERROR webdriver: Request failed due to Error: unknown command: session/f4c40ae3e3584eca0063dc438652673c/se/log/types

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
@soumya-contentsquare unfortunately the `getLogs` command is not supported anymore. If you want to get network logs in Chrome I recommend to use the [DevTools service](https://webdriver.io/docs/devtools-service.html).
