### ISSUE TITLE
@wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by Alona-T** [webdriverio/webdriverio#5589]
## **Describe the bug**
We have our WebdriverIO(Mocha) project integrated with Azure Devops pipeline and also Browserstack as a cloud. When i run it locally with browserstack - everything works well, however when i run on Azure - for some reason i get this error
```
@wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'toLowerCase' of undefined
```

Tests are still passing but for some reason it is failing pipeline due to this error. Also i do not even see any 'toLowerCase' in my code as well as node-modules to even debug it or figure out why it is happening.

## **Environment:**
 - **WebdriverIO version:** 6.1.25
 - **Node.js version:** 13.10.1
 - **NPM version:** 6.14.5
 - **Platform name and version:** iOS cloud latest (browserstack)
 - **Additional wdio packages used (if applicable):** 
```
    "@wdio/appium-service": "^6.1.16",
    "@wdio/cli": "^6.1.25",
    "@wdio/junit-reporter": "^6.1.25",
    "@wdio/local-runner": "^6.1.25",
    "@wdio/mocha-framework": "^6.1.19",
    "@wdio/selenium-standalone-service": "^6.1.14",
    "@wdio/sync": "^6.1.14",
    "webdriverio": "^6.1.25",
    "@wdio/spec-reporter": "^6.1.23",
    "appium": "^1.17.1",
    "browserstack-local": "^1.4.5",
    "chai": "^4.2.0"
```
## **Config of WebdriverIO**
```
process.env.PLATFORM = "IOS"

exports.config = {
    runner: 'local',
    user: process.env.BROWSERSTACK_USERNAME || '*****',
    key: process.env.BROWSERSTACK_ACCESS_KEY || '**********',

    updateJob: false,
    specs: [
      './spec/tests/*_spec.js'
    ],
    exclude: [],

    framework: 'mocha',
      mochaOpts: {
        timeout: 99999999
    },

    logLevel: 'trace',

    reporters: [
        'spec',
        ['junit', {
            outputDir: './reportsIOS/',
            outputFileFormat: function(options) { // optional
                return 'test-ios.xml'
            }
        }]
    ],

    capabilities: [{
      'name': 'My company',
      'build': 'IOS',
      'project': 'UI tests',
      'device': 'iPhone 11 Pro',
      'app': "my_app_custom_id",
      'os_version': '13',
      'browserstack.debug': true,
      "browserstack.appium_version" : "1.17.0",
        }],
      }
```

```
[0-0] 2020-07-08T13:33:42.073Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'toLowerCase' of undefined
    at JunitReporter.buildJunitXml (/home/vsts/work/1/s/node_modules/@wdio/junit-reporter/build/index.js:152:122)
    at JunitReporter.onRunnerEnd (/home/vsts/work/1/s/node_modules/@wdio/junit-reporter/build/index.js:23:22)
    at JunitReporter.WDIOReporter.on.runner (/home/vsts/work/1/s/node_modules/@wdio/reporter/build/index.js:145:12)
    at JunitReporter.emit (events.js:198:13)
    at JunitReporter.EventEmitter.emit (domain.js:448:20)
    at reporters.forEach.reporter (/home/vsts/work/1/s/node_modules/@wdio/runner/build/reporter.js:38:49)
    at Array.forEach (<anonymous>)
    at BaseReporter.emit (/home/vsts/work/1/s/node_modules/@wdio/runner/build/reporter.js:38:20)
    at Runner.run (/home/vsts/work/1/s/node_modules/@wdio/runner/build/index.js:166:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-07-08T13:33:42.078Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in mycustomid - /spec/tests/login_spec.js
2020-07-08T13:33:42.079Z INFO @wdio/cli:launcher: Run onComplete hook
```

## **Expected behavior**
I expect it to generate the report the same way as it does on local and do not fail pipeline

## **Log**
Azure pipeline logs: 
[logs.txt](https://github.com/webdriverio/webdriverio/files/4891009/logs.txt)

**Comment by christian-bromann** [comment]
Hey,
thanks for filing the issue.

@mikesalvia I think you have been working on this part recently. Mind taking a look?

This seems indeed like bug. We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by christian-bromann** [comment]
@Alona-T I believe if you set `os` in your capabilities it should fix the issue in the meantime.

**Comment by Alona-T** [comment]
@christian-bromann thank you for the feedback, however i run it for native mobile apps, do we still need os in this case?

**Comment by christian-bromann** [comment]
I don't know. The fix for this bug is fairly trivial and just requires to check of `runner.capabilities.os` here: https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-junit-reporter/src/index.js#L163. Would you like to take a stab at it to fix it?

**Comment by jonesh66** [comment]
I'm picking this task up.

**Comment by Alona-T** [comment]
Thank you @christian-bromann for the workaround with 'os' capability
I have added it to my ios and android config as 
```
"os": "IOS"
```
and it worked well now - report is generating and tests are passing
Will wait for the fix from jonesh66

**Comment by hieuxlu** [comment]
Setting os in capabilities will result in this error
```
[0-1] 2020-07-15T03:48:53.308Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { os: '5.4.0-40-generic', browserName: 'chrome' },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { os: '5.4.0-40-generic', browserName: 'chrome' }
}
[0-1] 2020-07-15T03:48:53.315Z ERROR webdriver: Request failed with status 500 due to unknown error: Illegal key values seen in w3c capabilities: [os]
[0-1] 2020-07-15T03:48:53.315Z ERROR webdriver: unknown error: Illegal key values seen in w3c capabilities: [os]
```

**Comment by christian-bromann** [comment]
@jonesh66 any updates on this?

**Comment by christian-bromann** [comment]
This has been fixed by #5589

**Comment by Antimatterr** [comment]
I got this error again

**Comment by christian-bromann** [comment]
@Antimatterr this is a very old issue, I recommend updating your WebdriverIO dependencies.

**Comment by Antimatterr** [comment]
> @Antimatterr this is a very old issue, I recommend updating your WebdriverIO dependencies.

I have just done the setup with 

`npm init wdio` using wdio cli

and after running the example test case of wdio `npm run wdio`

I get this error

![image](https://user-images.githubusercontent.com/56473894/206922413-b1b8572d-273c-47c7-8b14-ebf79cd24609.png)

**Comment by christian-bromann** [comment]
This is a known issue #9288
