### ISSUE TITLE
Webdriver 6 + mocha + typescript - moving browser.addCommand()

### ISSUE THREAD

**Issue by dombialcz** [webdriverio/webdriverio#5591]
Hi i moved to Webdriverio 6 from the previous version and I run into a bunch of problems, after finding this pull request https://github.com/webdriverio/webdriverio/pull/4531 I got most of them resolved, but... I am getting a

` error TS2339: Property 'getNumber' does not exist on type 'Element'.`

This is a function I've added in the beforeSuite hook 

```

     */
    beforeSuite: function (suite) {
        browser.addCommand(
            'getNumber',
            function () {
                let cashValue = this.getText().toLowerCase().trim();

                if (isNaN(parseFloat(cashValue.charAt(0)))) {
                    return parseFloat(cashValue.slice(1).replace(',', ''));
                }
                return parseFloat(cashValue.replace(',', ''));
            },
            true,
        );
},
```

And I have the type definition in a separate file

```
declare module WebdriverIO {
    interface Element {
        getNumber: () => number;
    }
}
```

This does not work now, I assume this is because browser is not initialized in the beforeSuite. I have tried moving the functions to before hook and to a separate file, I have tried requiring them in mochaOpts, but it all produces the same error. So I think I don't understand where should I put the browser.addCommand functions. 

I have read https://webdriver.io/docs/typescript.html and https://webdriver.io/blog/2019/11/01/spec-filtering.html. but I couldn't figure out what the solution was (or the solution doesn't work :D )

Any help on this greatly appreciated.

**Comment by pjcalvo** [comment]
@dombialcz I add the addCommands on the before hook on the wdio.conf.js file.

![image](https://user-images.githubusercontent.com/7219896/86960569-f3197b80-c11c-11ea-9e50-b80bec456a1c.png)

Did you add the type definition to the tsconfig file?

![image](https://user-images.githubusercontent.com/7219896/86960636-0e848680-c11d-11ea-9c67-a887d0458d70.png)

**Comment by dombialcz** [comment]
> @dombialcz I add the addCommands on the before hook on the wdio.conf.js file.
> 
> Did you add the type definition to the tsconfig file?
> 

That actually helped, it's strange that the type definitions worked without being explicitly added to `tsconfig.json' before....  And somehow adding the whole directory to typeRoots ` "typeRoots":  ["./types"], ` didn't help at all... 

Anyway this helped, thank you @pjcalvo !

**Comment by pjcalvo** [comment]
Closing this. and it was not an actual code issue. 

@dombialcz good luck. I think you can also reach the chat https://gitter.im/webdriverio/webdriverio for similar question.s
