### ISSUE TITLE
isExisting returns true but execute script fails with non existing element

### ISSUE THREAD

**Issue by Gordiievskyi** [webdriverio/webdriverio#5594]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). 

**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.1.17
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:**async
 - **Node.js version:** v12.16.1
 - **NPM version:** 6.13.4
 - **Browser name and version:** chrome=83.0.4103.116
 - **Platform name and version:** OSX 10.14.6
 - **Additional wdio packages used (if applicable):** [
"@wdio/appium-service": "^6.1.16",
    "@wdio/browserstack-service": "^6.1.15",
    "@wdio/cli": "^6.1.17",
    "@wdio/local-runner": "^6.1.17",
    "@wdio/logger": "^6.0.16",
    "@wdio/mocha-framework": "^6.1.17",
    "@wdio/selenium-standalone-service": "^6.1.14",
    "@wdio/spec-reporter": "^6.1.14",
]

**Config of WebdriverIO**
#wd-bug-conf.js
```
exports.config = {
  specs: [
    './src/tests/**/*.js',
  ],
  logLevel: 'info',
  bail: 0,
  baseUrl: '0.0.0.0',
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  seleniumLogs: 'logs',
  framework: 'mocha',
  reporters: ['spec'],
  maxInstances: 1,
  path: '/wd/hub',
  port: 4444,
  capabilities: [
    {
      browserName: 'chrome',
    }
  ],
  mochaOpts: {
    ui: 'bdd',
    timeout: 3600000
  },
};
```
**Describe the bug**
Execute spec below and you will reproduce it. isExisting says element exists but when execute script it says The element with selector "#search_button_homepage" you trying to pass into the execute method wasn't found

**To Reproduce**
```
describe('DuckDuckGo search', () => {
  it('searches for WebdriverIO', async () => {
    await browser.url('https://duckduckgo.com/');
    await (await $('#search_form_input_homepage')).setValue('WebdriverIO');
    let element_to_delete = await $('#search_button_homepage');
    await browser.execute((element) => { element.remove(); }, element_to_delete);
    element_to_delete = await $('#search_button_homepage');
    await browser.execute(() => {
      const child_el = document.createElement('input');
      child_el.setAttribute('id', 'search_button_homepage');
      const parent_el = document.getElementById('search_form_homepage');
      parent_el.appendChild(child_el) ;
    });
    console.log(JSON.stringify(element_to_delete));
    const EXIST = await element_to_delete.isExisting();
    if (EXIST) {
      await browser.execute((element) => {
        element.setAttribute('style', 'border: 2px solid red;');
      }, element_to_delete);
    }
  });
});
```
[Include code or an example repository that can easily be set up]

**Expected behavior**
isExisting() should return false, honestly I would prefer $() - to return wrapper that has no result aka lazy loading if not then isExisting() should return in this case false

**Log**
https://gist.github.com/Gordiievskyi/c118b8e04bb84f09408e98f94dfb8513
https://gist.github.com/Gordiievskyi/069db22351beff6a4bcf89458cf5ce59

**Additional context**

> Please use the correct markdown

**Comment by pjcalvo** [comment]
If you are not explicitly using the async mode then the async await is not necessary..

**Comment by pjcalvo** [comment]
@Gordiievskyi I went through your code and there might be a different issue than described. `.IsExisting` is finding the element, but `element_to_be_located` still has a reference for the element that you deleted in the first `execute`.

The `isExisting()` works fine, because you are logging the element information just fine. If you move this line `element_to_delete = $('#search_button_homepage');` just before `console.log(JSON.stringify(element_to_delete));` then the element is located again and passed properly to the function. So all worked fine.

![image](https://user-images.githubusercontent.com/7219896/86992254-4fe95600-c15e-11ea-8882-9d0cf01e3a48.png)

**Comment by christian-bromann** [comment]
@Gordiievskyi once you remove the element you've lost the binding between element object and DOM element. Even if you add a DOM element with the same properties it is still not the same element and WebdriverIO can't just pick the new element. Please follow @pjcalvo advice and refetch the element once before you want to interact with it.

**Comment by Gordiievskyi** [comment]
Guys I am in USA, my work day just started.

will answer on your statements one by one:

@pjcalvo  
```
If you are not explicitly using the async mode then the async await is not necessary..
```
I do use async mode, and that is just a code snippet for you to easely get same error, thats not my real test and framework I use.

```
.IsExisting is finding the element, but element_to_be_located still has a reference for the element that you deleted in the first execute
```
That's what I call stale element reference, yes

```
The isExisting() works fine, because you are logging the element information just fine.
```
I would agree if the other methods of wdio also find it but my code shows it's not.  I think here 'stale element reference exception` is a best match

```
If you move this line element_to_delete = $('#search_button_homepage'); just before console.log(JSON.stringify(element_to_delete)); then the element is located again and passed properly to the function. So all worked fine.
```

yes cuase it will execute find again, and store new value. In our gitter chat I got you a point that isExisting take most resent value of element state and execute - not. Thats the problem. This code is to show you how it might hapens. 

@christian-bromann 
```
once you remove the element you've lost the binding between element object and DOM element
```
Yes, like ajax do, and then selenium client in most cases throw stale error. And here - not. Thats my point. I am ok if tool take revalidation responsibility for me like with isExisting, but them I assume it do same way with the rest. Now consider this use case that's more close to mine. 
This time I won't delete enything, I just look through page elements and save reference to non existing one, for a later use but I can't check if I can safaly use it cause check methods do not use it but locator. 

```
describe('DuckDuckGo search', () => {
  it('searches for WebdriverIO', async () => {
    await browser.url('https://duckduckgo.com/');
    let not_existing_element = await $('#search_button_homepage1');

    await browser.execute(() => {
      const child_el = document.createElement('input');
      child_el.setAttribute('id', 'search_button_homepage1');
      const parent_el = document.getElementById('search_form_homepage');
      parent_el.appendChild(child_el) ;
    });
    console.log(JSON.stringify(not_existing_element));
    const EXIST = await not_existing_element.isExisting();//element exists on the page but variable holds state of exception withouf ID that execute checks. isExists care only about locator and locator return new state of Element
    console.log(EXIST); //return true as explained above and so code in IF block executes
    if (EXIST) {
      await browser.execute((element) => { // execute will check if element_to_delete has elementId, but it doesn't, cause at the time of $method invocation element not exists
        element.setAttribute('style', 'border: 2px solid red;');
      }, not_existing_element);
    }
  });
});
```

**Comment by pjcalvo** [comment]
@Gordiievskyi Hey good morning for you sir. Sorry that I pointed out that you didn't need the async await. I understand that it has no relation with the issue.

So `isExisting()` method uses the locator of the Element to locate it again on the page but does not re-assign it. It just validates that there is at least one element with that locator and return either true or false. I think your code can easily be worked around to avoid this conflict.

**Comment by christian-bromann** [comment]
The reason why `isExisting` works even though the element was not found in the first place is because it takes the selector property of the element object and fetches an element with that selector. In your example it works because there is a different element matching with the same selector. This behavior seems unexpected but it is all we can do when having to manage element references across the wire.

How do you expect WebdriverIO to behave here?

**Comment by Gordiievskyi** [comment]
@christian-bromann 

I found even better example of what I mean:

```
describe('DuckDuckGo search', () => {
  it('searches for WebdriverIO', async () => {
    await browser.url('https://duckduckgo.com/');

    await (await $('#search_form_input_homepage')).setValue('WebdriverIO');
    let element_to_delete = await $('#search_button_homepage');
    await browser.execute((element) => { element.remove(); }, element_to_delete);
    // element_to_delete = await $('#search_button_homepage');

    await browser.execute(() => {
      const child_el = document.createElement('input');
      child_el.setAttribute('id', 'search_button_homepage');
      const parent_el = document.getElementById('search_form_homepage');
      parent_el.appendChild(child_el) ;
    });
    console.log(JSON.stringify(element_to_delete));
    const EXIST = await element_to_delete.isExisting();//element exists on the page but variable holds state of exception withouf ID that execute checks. isExists care only about locator and locator return new state of Element
    console.log(EXIST); //return true as explained above and so code in IF block executes
    if (EXIST) {
      await browser.execute((element) => { // execute will check if element_to_delete has elementId, but it doesn't, cause at the time of $method invocation element not exists
        element.setAttribute('style', 'border: 2px solid red;');
      }, element_to_delete);
    }
  });
});
```

Here if one execute the code - you get a `stale element reference: element is not attached to the page document`

But you get it in `execute` method and not in isExisitng(). So I expect that every method should throw it, but isExisting is nothing more then findElements and so always get newest state of element, when the rest methods use id it returns . As I said from my point of view its a bug. Please let me know your thoughts.

**Comment by christian-bromann** [comment]
> As I said from my point of view its a bug. Please let me know your thoughts.

So if I understand you correctly you are saying that `isExisting` should not check anything but return whether or not the element reference was detected in the first place?

**Comment by Gordiievskyi** [comment]
In my opinion - yes. wdio has api to detect when element appears, `waitForExist`. What is use case for `isExisting`, check if previously found element exists(from my point of view). So if one want to check that before acting he want be sure that exists element he gave to that method and not new one. Then if it return false I can decide what to do - wait for it became present - `waitForExist`, re-validate the reference - $('some_locator') or whatever one decide. 

Current behavior make it redundant from my point of view - because behavior is unpredictable, it may return true but click or execute or setValue will either throw `no such element` or `stale element reference`. Both errors are ok if I didn't made validation with isExisting before, `stale` might happen even if I did the validation( in case element refreshed just after isExisting and before action)

**Comment by pjcalvo** [comment]
@Gordiievskyi  I think there is a limitation protocol wise. Webdriver only allows webdriverIO to fetch elements using the supported selectors, css, xpath, etc. So the best webdriverIO can do is to try to find the element again and see if you can locate it. 

You use case is quite specific, and I think it would be easier for you to find a work around. Maybe comparing both elements or properly use the isExisting before and after element has been deleted!  Knowing this limitation I think you can just fetch the element again and avoid conflicts.

**Comment by Gordiievskyi** [comment]
I don't delete element in my test, the second use case when I save reference to non existing element is my case. I made a wrapper on top of wdio methods( I think most of automation do).That saves the wdio element and use inside wrapped methods. So basically what you suggest is to do verification on my side, and I imply that it would be better to do it on wdio side, cause otherwise isExisting is redundant. I will disagree that my use case is rare, its common for those who work with ajax. Yes, unfortunately, wd protocol doesn't have such method at all, and it seams right, because its not server side task, but client. If that is your final decision I am ok, but want to ask to add more description on isExisting in documentation, like with `Custom Services` `SevereServiceError` was added. When I asked about it 2 month ago none respond me on how to achieve it. Now its in the docs and its cool. I am not sure if other selenium clients like protractor or even other language binding like serenity do that check.  At least let people know of its behavior is what shell be done.
If you need me I can create a documentation ticket.

**Comment by pjcalvo** [comment]
Hey. I am sorry man. I am not sure what else we can do here.

**Comment by Gordiievskyi** [comment]
@pjcalvo As I mentioned in my last two sentences If you want me I can create a ticket to make documentation update, so it will be clear for others what the method do

**Comment by pjcalvo** [comment]
@Gordiievskyi awesome. Please create a Pull Request and include the docs changes.
