### ISSUE TITLE
Allure report shows report generated where test run took 6 days

### ISSUE THREAD

**Issue by Madhu-1234** [webdriverio/webdriverio#5595]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [WebdriverIO Gitter Support Channel](https://gitter.im/webdriverio/webdriverio)
- [#webdriverio channel om SeleniumHQ Slack](https://seleniumhq.slack.com/join/shared_invite/enQtODAwOTUzOTM5OTEwLTZjZjgzN2ExOTBmZGE0NjkwYzA2Nzc0MjczMGYwYjdiNGQ5YjI0ZjdjYjFhMjVlMjFkZWJmNDYyMmU1OTYyM2Y)

**Comment by Madhu-1234** [comment]
![image](https://user-images.githubusercontent.com/36332967/87032477-503b2d00-c202-11ea-90c1-d0fcc40189a7.png)

**Comment by christian-bromann** [comment]
Join our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue in WebdriverIO.
