### ISSUE TITLE
Internet Explorer "Missing parameter: url"

### ISSUE THREAD

**Issue by Westsaid** [webdriverio/webdriverio#5596]
## 💬 Questions and Help

Hello guys, im trying to get my tests to the IE and I stumbled upon an error. I'm getting a session created but when trying to use the "browser.url(...)" function, I receive the error " WARN webdriver: Request failed due to Missing parameter: url"

Does somebody has a clue on how to fix this?

I'm running the tests in a standalone testrunner, I am using the IEDriver Version 3.4.
WDIO Log:  [wdio.log](https://github.com/webdriverio/webdriverio/files/4896842/wdio.3.log)
IE Log: [ie.log](https://github.com/webdriverio/webdriverio/files/4896837/ie.log)

### Reproducible example:
`const { remote } = require("webdriverio");
let browsers = []

callTests(new Array(1)).then(erg => {
  console.log("Done")
})
async function main(nsc, i) {
    //console.log(`Started test: ${testcase}@${nsc} (${i+1}/${allNSC.length})`)
    const browser = await remote({
        capabilities : {
            browserName: "internet explorer"
        },
        services:["iedriver"],
        port:4448,
        logLevel: "debug",
        outputDir: __dirname + "/"
    })
    browsers[i] = browser

    global.browser = browser;
    await browser.url("https://www.nytimes.com")

    await browser.deleteSession()
    await delete browser
    await delete browsers[i]
}

function callTests(arr, i) {
    return new Promise(res => {
        if (i == undefined) i = 0
        let error = false
        main(arr[i], i).catch(async e => {
            console.error(e, arr[i])
            error = e
            await browsers[i].deleteSession();
            await delete browsers[i]
        }).then(async erg => {
            if (i < arr.length - 1) return res(callTests(arr, ++i))
            else res()
        });
    })
}`

**Comment by pjcalvo** [comment]
Hi @Westsaid , 

I am not 100% sure, but based on the logs it seems like internet explorer driver 3.4 is not w3c compliant, and so you would need to either downgrade webdriverio (not recommended). Or try a different service.

Can u try using https://webdriver.io/docs/selenium-standalone-service.html instead of `services:["iedriver"],`.

Please let me kno

**Comment by christian-bromann** [comment]
@pjcalvo is right, you are using an outdated IEDriver. Please update the driver by downloading it from the Selenium [project page](https://www.selenium.dev/downloads/).
