### ISSUE TITLE
List of Available CSS Selectors

### ISSUE THREAD

**Issue by Freyert** [webdriverio/webdriverio#560]
I'd like to try and compile a list of available CSS selectors as well as the extras like `:contains` for the docs. Where might I get started with this?

**Comment by christian-bromann** [comment]
checkout [find-element-strategy.js](https://github.com/webdriverio/webdriverio/blob/v3/lib/helpers/find-element-strategy.js) for more information about how WebdriverIO chooses the selector strategy. Note that with `v3` you can chain selectors so some of them will get obsolete, e.g.

```js
client.click('form button=Submit')
```
can get replaced by
```js
client.element('form button').click('=Submit')
```

I am not sure whether or not I should remove those obsolete once. It probably doesn't hurt to keep them.
