### ISSUE TITLE
isDisplayed() is not a function, using with Appium

### ISSUE THREAD

**Issue by GeorgeXCV** [webdriverio/webdriverio#5600]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.23.0
 - **Mode:** Testrunner?
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** v12.16.1
 - **NPM version:** 6.13.4
 - **Platform name and version:** iOS 13.3

**Config of WebdriverIO**
Node.js / Appium / WebdriverIO / BrowserStack

**Describe the bug**
I get "isDisplayed()" is not a function when trying to use it. Following webdriver.io example for JavaScript here - http://appium.io/docs/en/commands/element/attributes/displayed/

**To Reproduce**
Follow webdriverio example from here http://appium.io/docs/en/commands/element/attributes/displayed/

```
 async isE2eElementIdFound(idType, value, timeout = this.shortWait) {
        await this.driver.setImplicitTimeout(timeout);
        const element = await this.driver.findElement(idType, value);
        await this.driver.setImplicitTimeout(this.tenSecondsWait); // Set timeout back to default after search
        const isDisplayed = await (element).isDisplayed();
        if (!isDisplayed) {
            return false;
        }
```

**Expected behavior**
Returns true/false based on element being visible.

**Log**
Appium:
```
2020-07-10T10:06:23.685Z INFO webdriver: COMMAND touchPerform(<object>)
2020-07-10T10:06:23.685Z INFO webdriver: [POST] http://localhost:4723/wd/hub/session/edff324b-46f2-4aac-be55-d83461fc9614/touch/perform
2020-07-10T10:06:23.685Z INFO webdriver: DATA { actions: [ { action: 'tap', options: [Object] } ] }
2020-07-10T10:06:23.976Z INFO webdriver: COMMAND setImplicitTimeout(10000)
2020-07-10T10:06:23.976Z INFO webdriver: [POST] http://localhost:4723/wd/hub/session/edff324b-46f2-4aac-be55-d83461fc9614/timeouts/implicit_wait
2020-07-10T10:06:23.976Z INFO webdriver: DATA { ms: 10000 }
2020-07-10T10:06:23.979Z INFO webdriver: COMMAND findElement("accessibility id", "DigitPad.backspaceButton")
2020-07-10T10:06:23.979Z INFO webdriver: [POST] http://localhost:4723/wd/hub/session/edff324b-46f2-4aac-be55-d83461fc9614/element
2020-07-10T10:06:23.979Z INFO webdriver: DATA { using: 'accessibility id', value: 'DigitPad.backspaceButton' }
2020-07-10T10:06:27.785Z INFO webdriver: RESULT {
  'element-6066-11e4-a52e-4f735466cecf': 'DE000000-0000-0000-1E3F-000000000000',
  ELEMENT: 'DE000000-0000-0000-1E3F-000000000000'
}
2020-07-10T10:06:27.785Z INFO webdriver: COMMAND setImplicitTimeout(10000)
2020-07-10T10:06:27.785Z INFO webdriver: [POST] http://localhost:4723/wd/hub/session/edff324b-46f2-4aac-be55-d83461fc9614/timeouts/implicit_wait
2020-07-10T10:06:27.785Z INFO webdriver: DATA { ms: 10000 }
2020-07-10T10:06:27.789Z INFO webdriver: COMMAND takeScreenshot()
2020-07-10T10:06:27.789Z INFO webdriver: [GET] http://localhost:4723/wd/hub/session/edff324b-46f2-4aac-be55-d83461fc9614/screenshot
2020-07-10T10:06:27.914Z INFO webdriver: RESULT iVBORw0KGgoAAAANSUhEUgAABGUAAAmECAIAAAAjR0TuAAAAAXNSR0IArs4c6...
```

Error:
` Error: TypeError: element.isDisplayed is not a function`

**Comment by christian-bromann** [comment]
The Appium example is correct and shows that you need to use the `$` command as follows:

```js
        await this.driver.setImplicitTimeout(timeout);
        const element = await this.driver.$(selector);
        await this.driver.setImplicitTimeout(this.tenSecondsWait); // Set timeout back to default after search
        const isDisplayed = await element.isDisplayed();
        if (!isDisplayed) {
            return false;
        }
```

**Comment by GeorgeXCV** [comment]
> The Appium example is correct and shows that you need to use the `$` command as follows:
> 
> ```js
>         await this.driver.setImplicitTimeout(timeout);
>         const element = await this.driver.$(selector);
>         await this.driver.setImplicitTimeout(this.tenSecondsWait); // Set timeout back to default after search
>         const isDisplayed = await element.isDisplayed();
>         if (!isDisplayed) {
>             return false;
>         }
> ```

`Error: invalid selector: Locator Strategy 'css selector' is not supported for this session`

And if you follow the Appium example exactly you get a different error:
`const isDisplayed = await $(element).isDisplayed();`

`Error: ReferenceError: $ is not defined`

**Comment by christian-bromann** [comment]
> Error: invalid selector: Locator Strategy 'css selector' is not supported for this session

Please [see the docs](https://webdriver.io/docs/api/browser/$.html) how to use the command and don't just copy my example 😉 

> Error: ReferenceError: $ is not defined

This depends on your setup, if you use the wdio testrunner which the Appium docs assume here you won't see the error.

**Comment by GeorgeXCV** [comment]
```
async isElementDisplayed(elementID) {
        let isDisplayed = await $(elementID).isDisplayed();
        if (!isDisplayed) {
            return false;
        } else {
            return true;
        }
    }
```

Still get reference error. I don't think it is testrunner because package.json shows `webdriverio,` not `wdio`. Whats the difference? Do I have to change library just to use this function? I do get a tooltip explaining what the function does when I type it out so odd it isn't recongised when run.

**Comment by christian-bromann** [comment]
> Whats the difference?

Please see [the docs](https://webdriver.io/docs/setuptypes.html). There is also a lot of video tutorials to get you started.

> let isDisplayed = await $(elementID).isDisplayed();

The correct syntax would be `await (await $(elementID)).isDisplayed()`. I recommend to use the wdio testrunner as it allows to write commands synchronous which allows to write this without `async/await`

**Comment by GeorgeXCV** [comment]
Thanks, moving to wdio testrunner wouldn't make sense because whole project already uses `async/await` with Selenium and MochaJS. 

That syntax doesn't work either. Still complains about the `$`. Is it not possible to use isDisplayed() in standalone mode?

**Comment by christian-bromann** [comment]
> Thanks, moving to wdio testrunner wouldn't make sense because whole project already uses `async/await` with Selenium and MochaJS.

If you move from Selenium to WebdriverIO I would say it makes sense to update the tests to sync at the same time. Running tests synchronous makes tests a lot simpler, e.g.

```js
// async execution
const isDisplayed = await (await $(elementID)).isDisplayed();
```

vs

```js
// sync execution
const isDisplayed = $(elementID).isDisplayed();
```

**Comment by GeorgeXCV** [comment]
> > Thanks, moving to wdio testrunner wouldn't make sense because whole project already uses `async/await` with Selenium and MochaJS.
> 
> If you move from Selenium to WebdriverIO I would say it makes sense to update the tests to sync at the same time. Running tests synchronous makes tests a lot simpler, e.g.
> 
> ```js
> // async execution
> const isDisplayed = await (await $(elementID)).isDisplayed();
> ```
> 
> vs
> 
> ```js
> // sync execution
> const isDisplayed = $(elementID).isDisplayed();
> ```
> 
> Also the WDIO testrunner provides a lot of advantages with its reporters and services.

Only use Selenium for web clients. For mobile its Appium and WebDriverIO. Haven't really had any problems, all our findElement functions etc. use one instance of await. Also never had to use $ selector.

So isDisplayed() is not possible to use outside of testrunner? Reason I need it is because iOS always return element result if out of view (need to scroll), this is expected behaviour for iOS from what I have read, so need something like isDisplayed().

**Comment by christian-bromann** [comment]
> So isDisplayed() is not possible to use outside of testrunner?

No, you can use the same interface with or without testrunner. Just make sure you handle command promises correctly if you decide not to use the testrunner in sync mode.

**Comment by GeorgeXCV** [comment]
> > So isDisplayed() is not possible to use outside of testrunner?
> 
> No, you can use the same interface with or without testrunner. Just make sure you handle command promises correctly if you decide not to use the testrunner in sync mode.

Ok, well no issues with with promises because async/await is used all over the project. As mentioned previously, issue is:
`Error: ReferenceError: $ is not defined`

**Comment by christian-bromann** [comment]
> Error: ReferenceError: $ is not defined

If you don't use the testrunner you need to fetch elements via `browser.$`

**Comment by GeorgeXCV** [comment]
> > Error: ReferenceError: $ is not defined
> 
> If you don't use the testrunner you need to fetch elements via `browser.$`

This is supported for mobile? I get:` Error: invalid selector: Locator Strategy 'css selector' is not supported for this session`

```
const inputElement = await this.driver.$("TextFieldView.description");
await inputElement.clearValue();
```
