### ISSUE TITLE
Does webdriverio use selenium under the hood?

### ISSUE THREAD

**Issue by t0lkman** [webdriverio/webdriverio#5601]
Does webdriverio use selenium under the hood?
I see some old articles stating webdriverio is a js wrapper for selenium.
But I the source code at first glance I don't see any selenium references...

**Comment by pjcalvo** [comment]
WebdriverIO is a custom binding implementation for the that implements the W3C WebDriver protocol, as well as others. 

Could you please use the gitter chat for further details. https://gitter.im/webdriverio/webdriverio

**Comment by christian-bromann** [comment]
> Does webdriverio use selenium under the hood?

Nope. WebdriverIO was pushed to NPM before Selenium had a JS binding.
