### ISSUE TITLE
Appium : findElementByImage selector is currently unavailable in webdriverio

### ISSUE THREAD

**Issue by jayandran-Sampath** [webdriverio/webdriverio#5602]
**Is your feature request related to a problem? Please describe.**
Hi Im trying to use appium feature of finding element by image

http://appium.io/docs/en/advanced-concepts/image-elements/#:~:text=Using%20the%20experimental%20%2Dimage%20locator,back%20to%20your%20Appium%20client.

but cannot find this feature in webdriverio

**Describe the solution you'd like**
Either we can create new selector in appium protocols like image else we can create specific browser methods like

browser.findElementByImage

**Comment by jayandran-Sampath** [comment]
If we can confirm on the approach either new selector or browser specific method.. I can create a PR for this

**Comment by christian-bromann** [comment]
@jayandran-Sampath it seems like adding a new selector strategy sounds most reasonable to me. Looking at the [docs](https://webdriver.io/docs/selectors.html) page what would you suggest this could look like?

**Comment by jayandran-Sampath** [comment]
im also favour of adding new selector. will try to create one PR

**Comment by christian-bromann** [comment]
Addressed in #5626
