### ISSUE TITLE
Fix `getHTML` docs

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#5603]
On the [`getHTML`](https://webdriver.io/docs/api/element/getHTML.html) we document to use the command as follows:

> $(selector).getHTML({  })

where in reality it should say something like this

> $(selector).getHTML(includeSelectorTag)

**Comment by morrme** [comment]
It looks like this is due to the param being marked as optional.
May I submit a suggested change?

**Comment by christian-bromann** [comment]
This has been fixed with [`96e1daa` (#5477)](https://github.com/webdriverio/webdriverio/pull/5477/commits/96e1daaf9de0675a389e6e921c5f98ea0c610311)
