### ISSUE TITLE
Way to implement resetApp for React Native in wdio-cli/?

### ISSUE THREAD

**Issue by robto09** [webdriverio/webdriverio#5605]
Hellow there! I am using the wdio/cli so I created the wdio.conf.js with this command, then I start doing the test. But the issues is when have more than one test in a single or multiple test files. 

In the test file I have something like this: 
```
 beforeEach(async function() {
    $('~home').waitForDisplayed(81000, false);
  });
```

Where home tag is a tag in the first view when the app runs in first screen. And appear this error: 

```
 element ("~home") still not displayed after 10000ms
```

So need to do kind of driver.resetApp()/ But dont know how to do it, what import do I need to do etc.

**Comment by christian-bromann** [comment]
You might want to try the [`reset`](https://webdriver.io/docs/api/appium.html#reset) command. For further question please join our support chat [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). Thanks!

**Comment by robto09** [comment]
I know that but from where I import the driver?

**Comment by robto09** [comment]
> You might want to try the [`reset`](https://webdriver.io/docs/api/appium.html#reset) command. For further question please join our support chat [![Gitter](https://camo.githubusercontent.com/f99733b13256cf0443f9186ebee1a11fae2bbd9a/68747470733a2f2f6261646765732e6769747465722e696d2f776562647269766572696f2f776562647269766572696f2e737667)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). Thanks!

I know that but from where I import the driver?
