### ISSUE TITLE
Internet Explorer: "Unable to get current browser"

### ISSUE THREAD

**Issue by Westsaid** [webdriverio/webdriverio#5607]
## 💬 Questions and Help

Hello everybody,

Im trying to get my standalone WDIO application to work with the IE, but somehow it can't connect to the IEDriver. The driver gives me error "Unable to get current browser".

I'm running WDIO in standalone! I use the latest IEDriver (3.9), I receive this error with every version of the IEDriver between 3.5 - 3.9. When I use 3.4 I get an error I reported at this issue: https://github.com/webdriverio/webdriverio/issues/5596

Thanks for your help in advance!

### Logs
[wdio.log](https://github.com/webdriverio/webdriverio/files/4911516/wdio.log)
[ie.log](https://github.com/webdriverio/webdriverio/files/4911517/ie.log)

### Reproducible Example:  
First start the IEDriver like this: `.\IEDriverServer3.9.exe --port=4448 --log-level=debug`

`const { remote } = require("webdriverio");
let browsers = []

callTests(new Array(1)).then(erg => {
  console.log("Done")
})
async function main(nsc, i) {
    const browser = await remote({
        capabilities : {
            browserName: "internet explorer"
        },
        //services:["selenium-standalone"],
        port:4448,
        logLevel: "debug",
        outputDir: __dirname + "/"
    })
    browsers[i] = browser

    global.browser = browser;
    await browser.url("https://www.nytimes.com")

    await browser.deleteSession()
    await delete browser
    await delete browsers[i]
}

function callTests(arr, i) {
    return new Promise(res => {
        if (i == undefined) i = 0
        let error = false
        main(arr[i], i).catch(async e => {
            console.error(e, arr[i])
            error = e
            await browsers[i].deleteSession();
            await delete browsers[i]
        }).then(async erg => {
            if (i < arr.length - 1) return res(callTests(arr, ++i))
            else res()
        });
    })
}`

**Comment by christian-bromann** [comment]
If you use WebdriverIO in [standalone mode](https://webdriver.io/docs/setuptypes.html#standalone-mode) you need to make sure to have the IEDriver started and your connection options pointed to that driver.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
