### ISSUE TITLE
addValue error handling

### ISSUE THREAD

**Issue by sweinertjr** [webdriverio/webdriverio#562]
Hi-

When I do:
`client.addValue('#someInvalidSelector', value)`, it does not seem to execute my `client.on('error', function(e) {` error handler. It works fine if I try to use `.click` on an invalid selector, but not for `addValue`.

I dug into the `addValue.js` and `return callback(new ErrorHandler(7));` IS firing, it just never makes it to the error handler. Ideas?

**Comment by christian-bromann** [comment]
Not really, I will check it out on `v3` though and see if it works there. Thanks for reporting this!

**Comment by christian-bromann** [comment]
I improved the whole error handling in `v3`. It captures the stack-trace every time you execute a command. This way allows me to generate stack-traces that only relate to your test and WebdriverIO (no bullshit mocha or jasmine traces). Here is an example:

__test.js__
```js
var client = require('./').remote({
  desiredCapabilities: {
    browserName: 'phantomjs',
  }
});

client
    .init()
    .url('http://localhost:8080')
    .getTitle(function() {
        return client.url().then(function() {
            return client.getHTML('#notFound', false);
        });
    })
    .end();
```
produces the following stack-trace:

```txt
NoSuchElement: An element could not be located on the page using the given search parameters.
    at execute(<Function>) at /Users/christianbromann/Sites/Webprojekte/webdriverjs/DEV/lib/commands/selectorExecute.js:62:37
    at execute("return !!document.evaluate;") at /Users/christianbromann/Sites/Webprojekte/webdriverjs/DEV/lib/helpers/ensureClientSideSelectorSupport.js:10:17
    at selectorExecute("#notFound", <Function>, false) at /Users/christianbromann/Sites/Webprojekte/webdriverjs/DEV/lib/commands/getHTML.js:50:17
    at getHTML("#notFound", false) at /Users/christianbromann/Sites/Webprojekte/webdriverjs/DEV/test.js:12:27
```

**Comment by sweinertjr** [comment]
Awesome! Can't wait to check this out. Any estimate as to when v3 will be ready for production?

**Comment by christian-bromann** [comment]
@sweinertjr by the end of this week or beginning next week
