### ISSUE TITLE
(browser).toHaveUrl is failing

### ISSUE THREAD

**Issue by kthulsidoss** [webdriverio/webdriverio#5621]
**WebdriverIO version**: 6.2.0
**Mode:WDIO Testrunner** sync 
**Node.js** version :12.18.2
**NPM** :6.14.6
**Browser Name**:chrome 83.04
**platform** :windows 10 enterprise
**config of webdriver.io** : using the steps outlined in doc
**describe the bug :**
the simple test is failing 
describe('webdriver.io page', () => {
    it('should have the right url', () => {
        browser.url('https://webdriver.io')
        expect(browser).toHaveUrl('https://webdriver.io')
    })
})
**expected behavior** : it is expected to pass

**Comment by christian-bromann** [comment]
> expect(browser).toHaveUrl('webdriver.io')

You are missing the protocol: `expect(browser).toHaveUrl('https://webdriver.io')`

**Comment by kthulsidoss** [comment]
hi sorry that did not work ,here is the error
chrome 83.0.4103.116 windows #0-0] Error: Expect window to have url
[chrome 83.0.4103.116 windows #0-0]
[chrome 83.0.4103.116 windows #0-0] Expected: "webdriver.io"
[chrome 83.0.4103.116 windows #0-0] Received: "https://webdriver.io/"
[chrome 83.0.4103.116 windows #0-0]     at Context.<anonymous> (C:\Users\THULSIKRISHNAN\webdriverio-test\test\specs\basic.js:4:25)
[chrome 83.0.4103.116 windows #0-0]     at Context.executeSync (C:\Users\THULSIKRISHNAN\webdriverio-test\node_modules\@wdio\sync\build\index.js:56:18)
[chrome 83.0.4103.116 windows #0-0]     at C:\Users\THULSIKRISHNAN\webdriverio-test\node_modules\@wdio\sync\build\index.js:82:70

**Comment by kthulsidoss** [comment]
so when i run with this test
describe('webdriver.io page', () => {
    it('should have the right url', () => {
        browser.url('https://webdriver.io')
        expect(browser).toHaveUrl('webdriver.io')
    })
})
it is still throwing error
