### ISSUE TITLE
(browser).toHaveUrl is failing

### ISSUE THREAD

**Issue by kthulsidoss** [webdriverio/webdriverio#5622]
#5621 is the original issue
------------------------------------------
this basic test is also failing

describe('webdriver.io page', () => {
    it('should have the right url', () => {
        browser.url('https://webdriver.io')
        expect(browser).toHaveUrl('webdriver.io')
    })
})
-------------------------------------------

chrome 83.0.4103.116 windows #0-0] Error: Expect window to have url
[chrome 83.0.4103.116 windows #0-0]
[chrome 83.0.4103.116 windows #0-0] **Expected: "webdriver.io"**
[chrome 83.0.4103.116 windows #0-0] **Received: "**https://webdriver.io/**"**
[chrome 83.0.4103.116 windows #0-0] at Context. (C:\Users\THULSIKRISHNAN\webdriverio-test\test\specs\basic.js:4:25)
[chrome 83.0.4103.116 windows #0-0] at Context.executeSync (C:\Users\THULSIKRISHNAN\webdriverio-test\node_modules@wdio\sync\build\index.js:56:18)
[chrome 83.0.4103.116 windows #0-0] at C:\Users\THULSIKRISHNAN\webdriverio-test\node_modules@wdio\sync\build\index.js:82:70

**Comment by kthulsidoss** [comment]
[chrome 83.0.4103.116 windows #0-0] 1) webdriver.io page should have the right url
[chrome 83.0.4103.116 windows #0-0] Expect window to have url

Expected: "https://webdriver.io"
Received: "https://webdriver.io/"

**Comment by christian-bromann** [comment]
@kthulsidoss please don't just open new issues when someone provided a solution. It also clearly shows why the assertion is failing:

```
[chrome 83.0.4103.116 windows #0-0] **Expected: "webdriver.io"**
[chrome 83.0.4103.116 windows #0-0] **Received: "**https://webdriver.io/**"**
```

This will pass:

```js
    describe('webdriver.io page', () => {
        it('should have the right url', () => {
            browser.url('https://webdriver.io')
            expect(browser).toHaveUrl('https://webdriver.io/')
        })
    })
```

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by kthulsidoss** [comment]
@christian-bromann  ah there is a small gotcha of trailing slash !!! thanks anyway
