### ISSUE TITLE
How to capture JS errors globally?

### ISSUE THREAD

**Issue by rasmusbergpalm** [webdriverio/webdriverio#563]
I wish to trigger a jasmine error and capture a screenshot on any JS errors.
Is there any way to instruct webdriverio to capture all JS errors?

**Comment by christian-bromann** [comment]
@rasmusbergpalm do you mean the log buffer in the browser (basically that what you see when you open the devtools in the console tab)?

**Comment by rasmusbergpalm** [comment]
Idealy it'd be some kind of

client.onJsError(function(err));

interface, and the callback would be called as soon as any JS error
happened on the page.

**Comment by christian-bromann** [comment]
That is hard to implement as it requires some kind of socket connection to the browser. Selenium provides a `log` interface where you can grab all kinds of different log types (e.g. error logs). But you need an extra request to get them. In a nutshell: the node client doesn't get any notification that a js error happened on the page but it can ask. Does that make sense?

I thought about executing an async script on the browser once someone called an url. It would listen to a js error and would return if this error happened while in the meantime you click around an do other stuff. This gets problematic as you click on a link that opens a new page. In this case that listener isn't available anymore and the client script doesn't know either.

The best way to tackle this is on Selenium level but I assume that even this isn't easy.

**Comment by rasmusbergpalm** [comment]
Yea, it doesn't seem like it's possible, w.o. native webdriver support for it, which likely won't happen.
You *could* read the log on every command, and fail if there were browser log levels above a certain threshold (SEVERE, ERROR, etc.), but that'd incur a lot of traffic on the wire i suppose.
For now I'm content with just outputting all the browser logs on any errors.
Feel free to close this.

**Comment by kisenka** [comment]
Hey guys, I found solution to track AJAX errors - https://franciskim.co/2016/06/08/webdriverio-injecting-javascript-capture-ajax-errors/
Maybe window.errors can be captured similarly?
