### ISSUE TITLE
Retry flaky tests

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#564]
It would be nice if the wdio runner allows to determine a number of retries for failing tests. This would allow us to ignore flakiness / false positives.

**Comment by rasmusbergpalm** [comment]
Not that it's my business but I'd advice against this.
We've gone down that route and it's not pretty. You're just trading time for stability.
You should eliminate flakyness with great prejudice
http://martinfowler.com/articles/nonDeterminism.html

**Comment by dok** [comment]
I agree with @rasmusbergpalm but I also like to idea of running tests multiple times and grouping up the average. Is it possible to do something like:

Run this test suite ten times
Display which ones passed and which ones failed out of 10 times.

Then it will be easier to determine non-deterministic tests. But maybe this is in the realm of third party testing frameworks and not the webdriver.

**Comment by christian-bromann** [comment]
Thanks for you input @dok @rasmusbergpalm 
it will be an optional thing and will be disabled per default. But I can see a value in this as I personally struggled recently with a problem in my test that I wasn't able to fix unless I would rewrite the whole stack. One of ten tests failed because of a problem in the DB caused by high concurrency.

However this is just a proposal. Gonna wait for more opinions and if people don't want it then this won't get implemented

**Comment by rasmusbergpalm** [comment]
I'm actually in the process of removing this from our own test setup. What I've found is that there are actually tests that *rely* on the re-run. So they setup some things in the first run, and then pass in the second. It's insane. Anyway, I'll stop ranting.

**Comment by christian-bromann** [comment]
NightwatchJS just introduced the possibility of [retrying test cases](https://github.com/nightwatchjs/nightwatch/pull/436) as well (just an observation)

**Comment by christian-bromann** [comment]
Also in protractor is a discussion going on: https://github.com/angular/protractor/issues/1190
I still believe that this is useful.

**Comment by mike-suggitt** [comment]
This would definitely be a nice feature to have as I think there is a distinction between fundamentally broken code and brittle code. Broken code would obviously be things that would never pass (e.g. expect 1 to equal 2)  due to changes in requirements/code. Brittle would be typically race-condition behaviour whereby it maybe sometimes times out. I agree strongly with @rasmusbergpalm that this should in no way excuse brittle code/tests and they still need to be captured and fixed; however the ability to immediately tell if the app is genuinly broken in pretty valuable.

Just my two cents

**Comment by thomaswmanion** [comment]
Since not everyone in the world is using docker containers (or whatever containers), I would agree that having retries helps prevent race conditions on databases that are hit fairly large.

+1

**Comment by christian-bromann** [comment]
Just a heads up for everyone so far. I gonna consider to implement it into the upcoming v4. It will be an option that defaults to 1.

**Comment by wilmoore** [comment]
A little off topic, but since you (@christian-bromann) mentioned it; is there a roadmap that you can point to with what is coming in v4?

Thanks.

**Comment by dok** [comment]
great. thanks @christian-bromann

**Comment by christian-bromann** [comment]
@wilmoore sorry for the late response. I don't really have a roadmap. I try to push out v4.0 as soon as possible and iterate on that. In general you can find future features [here](https://github.com/webdriverio/webdriverio/milestones/Upcoming). What is coming in v.4.0 and what not is unclear as I rather push out soon and skip features for later iterations.

**Comment by gabriel-sagula-hs** [comment]
+1 It is useful.

**Comment by kabirsikand** [comment]
+1 I support this functionality! Currently using http://github.com/TestArmada/magellan for test retries but I'm losing out on wdio functionality :(

**Comment by jeffsheets** [comment]
+1

**Comment by christian-bromann** [comment]
Moving this to upcoming as it might be a required feature for tests with flaky network

**Comment by christian-bromann** [comment]
This got implemented with the recent framework adapter update: http://webdriver.io/guide/testrunner/retry.html

**Comment by christian-bromann** [comment]
@rasmusbergpalm, @dok, @mike-suggitt, @thomaswmanion, @wilmoore, @gabriel-sagula-hs, @kabirsikand @jeffsheets

This is now also available in MochaJS v3 and can be used with the latest released wdio-mocha-framework (`v0.5.0`).

**Comment by avkrash** [comment]
I tried to use MochaJS retries style like 'this.retries()', but only failed steps (it) was re-run. the same situation when I used mochaOpts retries. What could be wrong ?

And what if run retries of test suites in new browser session for clean results ? 

I'm using:
webdriverio@4.4.0
wdio-mocha-framework@0.5.4

**Comment by christian-bromann** [comment]
@avkrash how does your suite look like?

**Comment by avkrash** [comment]
It is simple test suite as I want to be ensure about retries behaviour:

`describe ('test', function () {
    this.retries(4);
    it ('1 step', function () {
        console.log('1');
    });
    it ('2 step', function () {
        console.log('2');
        assert(false);
    });
});`

And in console output I see that only second step retries 5 times. wdio runs in sync mode.

**Comment by christian-bromann** [comment]
This should work with latest wdio-mocha-framework and mocha installed. See https://github.com/webdriverio/webdriverio/blob/57d68f5ed551071f9b77136b49e094710b508ada/docs/guide/testrunner/retry.md#rerun-suites-in-mochajs

**Comment by christian-bromann** [comment]
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have any more questions.
