### ISSUE TITLE
Jasmine tests run twice

### ISSUE THREAD

**Issue by zarko-tg** [webdriverio/webdriverio#5657]
<img width="870" alt="Screenshot 2020-07-24 at 11 16 07" src="https://user-images.githubusercontent.com/6142411/88377285-2c99ea00-cd9f-11ea-9b2a-7be94bb3b5b7.png">

Used the simple recipe from https://webdriver.io/docs/gettingstarted.html
and changed framework to jasmine. Now all tests run twice.

To reproduce:
- Unzip [webdriverio-test.zip](https://github.com/webdriverio/webdriverio/files/4971128/webdriverio-test.zip)
- npm i
- ./node_modules/.bin/wdio wdio.conf.js --spec test/specs/basic.js

**Environment:**
  "devDependencies": {
    "@wdio/cli": "^6.3.4",
    "@wdio/jasmine-framework": "^6.3.0",
    "@wdio/local-runner": "^6.3.4",
    "@wdio/spec-reporter": "^6.3.0",
    "@wdio/sync": "^6.3.3",
    "chromedriver": "^84.0.1",
    "wdio-chromedriver-service": "^6.0.3"
  }

 - **Mode:** WDIO Testrunner, local
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.18.3
 - **NPM version:** 6.14.6
 - **Browser name and version:** Chrome 85
 - **Platform name and version:** MacOS Catalina

**Comment by christian-bromann** [comment]
Seems like related to Jasmine v3.6 release. We will roll back the version.

**Comment by christian-bromann** [comment]
This got fixed and released in v6.3.5
