### ISSUE TITLE
Bug: `filesToWatch` missing from `Config` type

### ISSUE THREAD

**Issue by seanpoulter** [webdriverio/webdriverio#5665]
**Environment (please complete the following information):**
 - **WebdriverIO version:** Latest
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** Both
 - **Node.js version:** 12.x
 - **NPM version:** Latest
 - **Browser name and version:** N/A
 - **Platform name and version:** macOS 10.14.x
 - **Additional wdio packages used (if applicable):** N/A

**Config of WebdriverIO**
Follow [the docs](https://webdriver.io/docs/typescript.html#typed-configuration) to set up a typed configuration file and add `filesToWatch`.

**Describe the bug**
Files to watch is not part of the `Config` type so TypeScript reports it as a problem.

**To Reproduce**
I think we can confirm this one with code inspection. `filesToWatch` is not an optional property on `Config` in either file:

* https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/webdriverio-core.d.ts
* https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-sync/webdriverio-core.d.ts

**Expected behavior**
TypeScript is not grumpy.

**Log**
Hopefully not required

**Additional context**
Hopefully not required

**Comment by christian-bromann** [comment]
The type should be added in the [typescript template](https://github.com/webdriverio/webdriverio/blob/master/scripts/templates/webdriverio.tpl.d.ts#L52-L169) and then generated with `npm run generate:typings`.

**Comment by seanpoulter** [comment]
Cool! I'm happy to open an MR in a day or so.
