### ISSUE TITLE
Webdriver not detecting testID tags when .app is generated in Release mode. 

### ISSUE THREAD

**Issue by robto09** [webdriverio/webdriverio#5670]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2] 6.3.5
 - **Mode:** [Standalone mode or WDIO Testrunner] WDIO Testrunner 
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async] sync
 - **Node.js version:** [e.g. 8.11.2] 14.15.0
 - **NPM version:** [e.g. 5.8.0] 6.14.7
 - **Browser name and version:** [e.g. Chrome 68] ' '
 - **Platform name and version:** [e.g. Windows 10] Mac OS Catalina 10.15.6
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]
```
 "@wdio/cli": "^6.2.0",
"@wdio/jasmine-framework": "^6.3.0",
    "@wdio/local-runner": "^6.3.4",
    "@wdio/sauce-service": "^6.3.2",
    "@wdio/spec-reporter": "^6.3.0",
    "@wdio/sync": "^6.3.3",
    "chromedriver": "^83.0.1",
    "wdio-chromedriver-service": "^6.0.3"
```

**Config of WebdriverIO**
An example of how you configured WebdriverIO config
```
config.capabilities = [
  {
    deviceName: 'iPhone XS Simulator',
    platformName: 'iOS',
    platformVersion: '13.2', 
    orientation: 'PORTRAIT',
    // The path to the app
    app: 'sauce-storage:app-ios-sim.zip',
    // Read the reset strategies very well, they differ per platform, see
    // http://appium.io/docs/en/writing-running-appium/other/reset-strategies/
    noReset: true,
    newCommandTimeout: 240,
    // Always default the language to a language you prefer so you know the app language is always as expected
    language: 'es',
    locale: 'es',
    // Group builds by build name
    build: buildName,
    appiumVersion: '1.17.1',
    browserName: '',
  },
];
```

**Describe the bug**
Hello there! I have an issue in react native that when create an .app in release mode looks like the testID to test iOS are not generated, so when using platforms like SauceLabs or others..  .app its installed in the simulators but test crashes due to timeout because Appium can not detect specific tags in each element(View, inputText, button etc) !! When test in local all works ok in .app debug mode.

**Log**
<img width="1086" alt="Screen Shot 2020-07-23 at 3 42 18 PM" src="https://user-images.githubusercontent.com/28666350/88769365-8bfa5000-d139-11ea-8edf-7c1fb15c3f24.png">

> Please use the correct markdown

**Comment by christian-bromann** [comment]
@robto09 can you make sure you are in native mode? Please use the `switchContext` command for this. If this works locally but not on Sauce it seems to me that it is rather a setup problem with the cloud provider. Therefor I will close this issue. Happy to answer further questions.

**Comment by robto09** [comment]
Thanks for answer. On the other hand, can you kindly clarify what do you mean by native mode and switchContext? Looks not just happens with that platform, also when .app is generated. In local works ok getting the .app in this way: 
```
'Library/Developer/Xcode/DerivedData/myApp-*/Build/Products/Debug-iphonesimulator/myApp.app
```

**Comment by christian-bromann** [comment]
> On the other hand, can you kindly clarify what do you mean by native mode and switchContext?

Please see the Appium docs under [Automating hybrid apps](http://appium.io/docs/en/writing-running-appium/web/hybrid/)

**Comment by robto09** [comment]
I am native mode!. Can you kindly not close the issue so other people can see it?
Thanks

**Comment by christian-bromann** [comment]
> I am native mode!. Can you kindly not close the issue so other people can see it?

People can see the issue whether it is open and closed. I still can't identify a bug in WebdriverIO here. If something works locally but not using a cloud provider that indicates that something with the setup must be wrong. Can you provide Appium logs for running your test locally vs. on the cloud provider?

**Comment by robto09** [comment]
This issue has been solved finally . Thank you very much for your support! For future people having this kind of issue looks like making some configuration in webdriverAgent did the trick. By other hand was hard to figure out that was the problem

**Comment by asifrayn** [comment]
@robto09 can you please share the solution I also cannot access element using ID
