### ISSUE TITLE
Write a test to ensure configuration wizard works from e2e

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#5672]
We promise the user an easy onboarding experience, everything needed to do to run a WebdriverIO e2e test is to:

```sh
$ npm i @wdio/cli
$ npx wdio config --yes
$ npx wdio
```

We should ensure that this works all the time. There have been regressions that were unnoticed (see #5671).

## Proposal

Add a CLI test in `/tests/cli` that:

- runs through the configuration wizard
- "fake installs" packages
- runs the test for all possible variation
    - for Mocha, Jasmine and Cucumber
    - with or without page objects
    - with or without compiler
    - additionally: run simple test with Chromedriver basic setup vs Puppeteer
- checks if they pass

The tricky part about this will be that we need to find a way to automate this without moving away from the original user experience. Here are some suggestions:

- allow to provide default answers via CLI parameters (e.g. `$ npx wdio config --yes --framework jasmine` would use all default values but sets jasmine as framework option)
- overwrite `yarn-install` dependency of `@wdio/cli` package to replace its functionality so that it links the packages rather than installs them from NPM (besides external packages like `wdio-chromedriver-service`)

**Comment by sarathps93** [comment]
Mind if I take this as my first pick?

**Comment by christian-bromann** [comment]
Please do! Let me know via Gitter or in this thread if I can help with anything. Cheers!

**Comment by sarathps93** [comment]
Thanks for letting me work on this @christian-bromann .

Please let me know if the below understanding is correct

We need to allow user to select the type of framework through CLI `$ npx wdio config --yes --framework <framework_name>` which defaults to `mocha` -it will be a new functionality that we are adding as a part of this task.

If the above point needs to be done, then should we avoid asking the question of which framework to install if the user uses the `--framework` option without defaulting all the questions through `--yes` command?

**Comment by christian-bromann** [comment]
We should tweak the configurator to just read parameters and set their values appropriately if the `--yes` flag is set. This is not meant for WebdriverIO users and should purely exist to allow us to run certain configuration scenarios in the WebdriverIO CI/CD pipeline.

**Comment by christian-bromann** [comment]
@sarathps93 any updates? Happy to assist with the task if necessary.

**Comment by sarathps93** [comment]
@christian-bromann Sorry for the delay and please give me time till this weekend. I do have few queries to be clarified, will connect with you on gitter

**Comment by christian-bromann** [comment]
any updates @sarathps93 ? Let me know if I can help with anything.

**Comment by sarathps93** [comment]
@christian-bromann , I was not able to work on this due to some changes in circumstances. Apologies for prolonging it

**Comment by sarathps93** [comment]
I am un-assigning it so that someone else can pick it up.

**Comment by christian-bromann** [comment]
I will go ahead and close this. The config wizard has become quite complex and running tests for all individual scenarios seems not feasible anymore at this point.
