### ISSUE TITLE
Support Selenoid capabilities in type definitions

### ISSUE THREAD

**Issue by rytikovroman1994** [webdriverio/webdriverio#5675]
Environment (please complete the following information):

**WebdriverIO version: 6.3.3
Mode: WDIO Testrunner
If WDIO Testrunner, running sync/async: sync , @wdio/sync
Node.js version: [v14.5.0]
NPM version: [6.14.5]
Browser name and version: [e.g. Chrome 84]
Platform name and version: [MAC OS Catalina 10.15.6]

Config of WebdriverIO
config.ts
"types": ["node", "@wdio/sync", "@wdio/mocha-framework", "@wdio/selenium-standalone-service", "./types/wdio"]

In the 'WebDriver' interface.DesiredCapabilities[]` there is no field for enabling video recording in Selenoid.

This field is missing for normal operation - "solenoid:options"?: { enable: boolean, enable Video: boolean }

**Comment by christian-bromann** [comment]
> This field is missing for normal operation - "solenoid:options"?: { enable: boolean, enable Video: boolean }

Just because there are no type definitions for it, it doesn't mean it doesn't work. Just add them. It would be awesome if you could help us enhance the type definitions to support selenoid capabilities.

**Comment by rytikovroman1994** [comment]
Yes. It works if you add a string -
"solenoid:options"?: { enable: boolean, enable Video: boolean }

The runner doesn't start without it. If the config is written in typescript.

**Comment by christian-bromann** [comment]
> How can i help?

Selenoid capabilities should be added here: https://github.com/webdriverio/webdriverio/blob/master/scripts/templates/webdriver.tpl.d.ts#L316-L346. After the edit run the `npm run generate:typings` script to propagate it to the package definition. Then file a PR. Thanks!

**Comment by suniljaiswal01** [comment]
@christian-bromann  can i work on this issue?

**Comment by christian-bromann** [comment]
@suniljaiswal01 absolutely! Thanks for jumping in 🙏

**Comment by rytikovroman1994** [comment]
I cloned the project. Created its own branch. Wrote the desired option. Committed. I started changes, but my branch is not present when creating a pull request. The name of the branch number of the bug. - 5675

**Comment by rytikovroman1994** [comment]
Oh, I didn't see anyone doing this. But I already did.

**Comment by rytikovroman1994** [comment]
I didn't have time to go on a hike. Please add all the options.

// seleoid specific
        "selenoid:options"?: { 
            enableVNC?: boolean,  
            enableVideo?: boolean, 
            videoName?: string,
            screenResolution?: string,
            videoScreenSize?: string,
            videoFrameRate?: number,
            videoCodec?: string
        },

**Comment by suniljaiswal01** [comment]
@rytikovroman1994  sorry ,did not saw your comment before. If you have already done the changes then you can create a PR, i will close mine

**Comment by rytikovroman1994** [comment]
I have an authorization error. Just add my edits. This will be faster.

**Comment by christian-bromann** [comment]
PR has been merged. Thanks for picking this up @suniljaiswal01
