### ISSUE TITLE
Webdriverio complaints about element visibility on a dropdown box

### ISSUE THREAD

**Issue by chanux** [webdriverio/webdriverio#568]
I'm not exactly sure whether this is a webdriverio bug but I have got the same scenario to work with both java and selenium-webdriver library.

**The issue**
After clicking and revealing a login dropdown box, the `setValue` complains about the input elements not being visible. webdriverjs code for pretty much the same thing works fine. 

**UPDATE:** I tried with click() and keys() function, which does the job pretty close to the way wdjs does and it worked. I think this is a corner case issue in setValue(). addValue() also failed the same way.

```javascript 
var webdriverio = require('webdriverio');
var options = {
    desiredCapabilities: {
        'browserName': 'firefox'
    }
};

webdriverio
    .remote(options)
    .init()
    .url('http://hudlmo.com')
    .click('#click-login')
    .waitForVisible('#sign_in_loginusername', 5000, false, function(err, res){
        console.log("Error: " + err + ", response " + res);
    })
    .isVisible('#sign_in_loginusername', function(err, isVisible){
        console.log("Error: " + err + ", Is visible: " + isVisible);
    })
    .setValue('#sign_in_loginusername', 'testuser')
    .setValue('#sign_in_loginpassword', 'testpass')
    .click('#sign_in_click-signin')
    .waitForVisible('#webinar-tab', 2000)
    .url()
    .then(function(url){
        console.log(url.value);
    })
    .end();
```

Following gist contains the webdriverjs code.

https://gist.github.com/chanux/ac80f7ad9e08b9ae87cc

Oh and thanks for webdriverio and all the hard work. The API pretty sweet.

**Comment by christian-bromann** [comment]
I guess the reason is that visibility checks are pretty strict in `v2.x`. That will change in `v3`. Looking at the code makes me feel that you can just remove

```js
    .waitForVisible('#sign_in_loginusername', 5000, false, function(err, res){
        console.log("Error: " + err + ", response " + res);
    })
    .isVisible('#sign_in_loginusername', function(err, isVisible){
        console.log("Error: " + err + ", Is visible: " + isVisible);
    })
```
as you would get an error message anyway that is like `An element could not be located on the page using the given search parameters.`

**Comment by chanux** [comment]
I actually started without those but when I was in trouble I tried waiting for the element to be visible. When waitForVisible reported true I wanted to double check and added isVisible(). isVisible() reported **true,false**, yeah true and false so I thought there is trouble.

Anyhow without that code this is what I get.

```
RuntimeError: RuntimeError
     (ElementNotVisible:11) An element command could not be completed because the element is not visible on the page.
     Problem: Element is not currently visible and so may not be interacted with
```
(The elements are actually visible on the browser window)

As I mentioned before I got it to work with click() and keys() functions.

Anyhow this weird behavior comes only in my specific case. I tried with deviantart.com which has a similar login and it worked there.

**Comment by christian-bromann** [comment]
@chanux sorry for my absence. I found out that `#sign_in_loginusername` exists twice on the page (even though it is an id). When using a more explicit selector (`#navigation #sign_in_loginusername`) everything works fine:

```js
var webdriverio = require('webdriverio');
var options = {
    logLevel: 'verbose',
    desiredCapabilities: {
        'browserName': 'firefox'
    }
};

webdriverio
    .remote(options)
    .init()
    .url('http://hudlmo.com')
    .click('#click-login')
    .isVisible('#navigation #sign_in_loginusername')
    .setValue('#navigation #sign_in_loginusername', 'testuser')
    .setValue('#navigation #sign_in_loginpassword', 'testpass')
    .click('#sign_in_click-signin')
    .waitForVisible('#webinar-tab', 2000)
    .url().then(function(url){
        console.log(url.value);
    })
    .end();
```

**Comment by chanux** [comment]
@christian-bromann Gah I missed that and I feel dumb :grinning: 

And thank you very much for taking your time for this.
