### ISSUE TITLE
Once the host browser executes test cases, the focus is not moving to guest browser, control remains in the host browser

### ISSUE THREAD

**Issue by DivyaTippa** [webdriverio/webdriverio#5685]
Environment
 - WebdriverIO version: 5.10.9
 - Mode: WDIO Testrunner
 - If WDIO Testrunner, running sync/async: async 
 - Node.js version: v10.16.0
 - NPM version: 6.9.0
 - Browser name and version: Chrome 84.0.4147.105 and Firefox 78.0.2
 - Platform name and version: MacOS Mojave version 10.14.6
 - Additional wdio packages used (if applicable):  @wdio/allure-reporter, @wdio/selenium-standalone service

Config of WebdriverIO: 

 capabilities: {
        Host: {
            capabilities: {
                browserName: 'firefox'
            }
        },
        Guest: {
            capabilities: {
                browserName: 'chrome'
            }
        }
    },

**Describe the bug**

Once the host browser executes test cases, the focus is not moving to guest browser, control remains in the host browser, due to which some of the guest test cases are getting failed  

**To Reproduce**
Will provide that if below information is not sufficient.

Include code or an example repository that can easily be set up

 describe('host test case' , () => {
    it('Seeker Login functionality', () => {

        let host = new login(Host);
        host.browser.url('./');
        host.browser.fullscreenWindow()
        host.userLogin("abc@abc.com", "qwerty");
       
    });
});

describe('Guest test case' , () => {
    it('Provider Login functionality', () => {

        let guest = new login(Guest);
        guest.browser.setWindowSize(1280, 1024)
        guest.browser.url('./');
        guest.userLogin("abc@abc.com", "qwerty");
     
    });
});

**Expected behavior**
once the host test case is executed, the focus/control should automatically switch to guest browser

**Comment by christian-bromann** [comment]
Can you provide a minimal reproducible example?

**Comment by DivyaTippa** [comment]
**Step1:** 
In wdio.config.js file I have set the capabilities as below

capabilities: {
        Host: {
            capabilities: {
                browserName: 'firefox'
            }
        },
        Guest: {
            capabilities: {
                browserName: 'chrome'
            }
        }
    },

_Host browser as Firefox and Guest browser as Chrome_

**Step2:**
Now in one of the .js file i have written test cases for each browser 

           describe('Host test case', () => {
           it('Launching Firefox browser ', () => {
          Host.url('./');
          Host.fullscreenWindow()
          Host.$('//input[@name="email"]').addValue("abc")
           });
         });

         describe('Guest test case', () => {
         it('Launching Chrome browser', () => {
         Guest.url('./');
         Guest.$('//input[@name="email"]').addValue("abc")
           });
        });

i am trying to launch two browsers and execute the test cases one after the other
So when i run this .js file, both browsers get launched
Once the host test cases i.e: Launching URL, fullscreen window and then adding text into text box executed 
the control should move to guest browser automatically(Chrome browser) _**which is expected behaviour**_ 
Issue: but the focus remains in Host browser, control is not moving to guest browser, 
guest browser test cases run in background which leads to failure of some test cases

**Comment by DivyaTippa** [comment]
Hi @christian-bromann 
I have provided reproducible steps, can you please look into it
Thanks

**Comment by christian-bromann** [comment]
Thanks, I can't promise when I have time to look into this. Any suggestions would be appreciated. Cheers!

**Comment by christian-bromann** [comment]
I can't reproduce this anymore with the following script:

```ts
describe('Host test case', () => {
    it('Launching Firefox browser ', async () => {
        const Host = browser.getInstance('Host')
        await Host.url('https://the-internet.herokuapp.com/login');
        await Host.fullscreenWindow()
        await Host.$('#username').addValue("abc")
    })
})

describe('Guest test case', () => {
    it('Launching Chrome browser', async () => {
        const Guest = browser.getInstance('Guest')
        await Guest.url('https://the-internet.herokuapp.com/login');
        await Guest.$('#username').addValue("abc")
        await browser.pause(15000)
    })
})
```

Both browser set the value properly. Happy to re-open if a reproducible example can be provided.
