### ISSUE TITLE
selectorExecute('body', callback) got NosuchElement error

### ISSUE THREAD

**Issue by Naixor** [webdriverio/webdriverio#569]
selectorExecute([], ) -> No Such Element error

**Comment by christian-bromann** [comment]
Ha interesting! Any way to reproduce that?

**Comment by Naixor** [comment]
Only in IE driver can got this error. My hub/node env is win7(64)/win7(64).
```JavaScript
// webdrivercss getPageInfo.js #33
// console.log(element) : body or something else and I m sure it is right
that.instance.selectorExecute(element, function(elem) { ... })
```
And then in webdriverio selectorExecute function I console the selector
```JavaScript
module.exports = function selectorExecute(selector, script) {
    var args = Array.prototype.slice.call(arguments, 2),
        response = {},
        callback = args.pop(),
        self = this;
       console.log(selector)

}
```

**Comment by christian-bromann** [comment]
Ohh yeah I think this is related to #552 and fixed in `v3`. Seems you are using WebdriverCSS. I will roll out the new version to the plugins right after release next week as there are small adaptations necessary. Sorry if I have no immediate fix for that.
