### ISSUE TITLE
Chrome 84: "credentials_enable_service" pref doesn't disable '' Offer to save passwords" option

### ISSUE THREAD

**Issue by iVespid** [webdriverio/webdriverio#5692]
My initial post was on stackoverflow, decided to create an issue here
https://stackoverflow.com/questions/63195981/webdriverio-how-to-disable-save-password-popup-in-chrome-84

This is my first on github, please let me know If I have to provide something additional 

There is 'Save password' pop-up in chrome that I cannot remove even with prefs usage.
Chrome created also has **Offer to save passwords** option enabled even with **"credentials_enable_service": false**
It points me to an idea that prefs might not be passed to chrome or atleast passed partially.

my NPM dependencies:
"@wdio/browserstack-service": "^6.1.15",
"@wdio/cli": "^6.3.4",
"@wdio/cucumber-framework": "^6.3.0",
"@wdio/devtools-service": "^5.13.0",
"@wdio/local-runner": "^6.3.4",
"@wdio/spec-reporter": "^6.3.0",
"@wdio/sync": "^6.3.3",

**Environment (please complete the following information):**
 - **Mode:** [Standalone mode]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** v12.16.1
 - **NPM version:** 6.13.4
 - **Browser name and version:** Chrome 84
 - **Platform name and version:** Windows 10

**Config of WebdriverIO**
`{
  "framework": "cucumber",
  "logLevel": "error",
  "services": [
    "intercept"
  ],
  "reporters": [
    [
      "cucumberjs-json",
      {
        "jsonFolder": "results"
      }
    ]
  ],
  "cucumberOpts": {
    "requireModule": [
      "@babel/register"
    ],
    "require": [
      "./step_definitions/*.js",
      "./support/*.js"
    ],
    "tagExpression": "tags",
    "format": "json:results/results.json",
    "timeout": 60000,
    "failAmbiguousDefinitions": true
  },
  "getPageTimeout": 60000,
  "allScriptsTimeout": 4000000,
  "capabilities": [
    {
      "maxInstances": 15,
      "browserName": "chrome",
      "cjson:metadata": {
        "browser": {
          "name": "chrome",
          "version": "84"
        }
      },
      "goog:chromeOptions": {
        "prefs": {
          "credentials_enable_service": false
        },
        "args": [
          "--disable-infobars",
          "--window-size=420,667",
          "--user-agent='Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X; en-us) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53'"
        ]
      }
    }
  ],
  "sync": true,
  "runner": "local"
}`

**Describe the bug**
Basically I need to disable this popup: https://imgur.com/a/51GZLtY

I've disabled a param in my chrome:

**chrome://settings/passwords** - Offer to save passwords

observed file

**AppData\Local\Google\Chrome\User Data\Default\Preferences**

1 pref were added

**"credentials_enable_service": false**

worth to mention that I've tried other values:

"credentials_enable_service": "false"
"credentials_enable_service": 0
"credentials_enable_service": "0"
"credentials_enable_service": 1
"credentials_enable_service": "1"
"credentials_enable_service": 2
"credentials_enable_service": "2"

in my capabilities I have added the following:

"goog:chromeOptions": {
    "prefs": {
      "credentials_enable_service": false
    },
     "args": [some arguments]
  }

But popup is still present and in a chrome created by WDIO I can see that param

chrome://settings/passwords - Offer to save passwords - is ENABLED

**To Reproduce**
Sign up with password somewhere

**Comment by christian-bromann** [comment]
With a [little googling](https://stackoverflow.com/questions/16301457/webdriver-chrome-browser-avoid-do-you-want-chrome-to-save-your-password-pop-u) I found that this will work:

```js
  "goog:chromeOptions": {
    "prefs": {
      credentials_enable_service: false,
      profile: {
        password_manager_enabled: false
      }
    },
     "args": [some arguments]
  }
```

**Comment by iVespid** [comment]
@christian-bromann also tried this before, doesn't work

**Comment by christian-bromann** [comment]
Not sure then. There is not much WebdriverIO can do here. It sends these configurations straight to Chrome. I would advise to maybe file a Chromium bug report then.

**Comment by mgrybyk** [comment]
@iVespid please add `--enable-automation` to `args`
