### ISSUE TITLE
Unable to run Puppeteer from latest Webdriver.io v6.3.6

### ISSUE THREAD

**Issue by somnanda** [webdriverio/webdriverio#5697]
**Environment:**
 - **WebdriverIO version:** 6.3.6
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** Sync
 - **Node.js version:** 12.16.1
 - **NPM version:** 6.13.4
 - **Browser name and version:** Chrome 84
 - **Platform name and version:** Ubuntu 18.04.1 LTS
 - **Additional wdio packages used (if applicable):** 
        "@wdio/cli": "^6.3.6",
        "webdriverio": "^6.3.6", 
        "@wdio/local-runner": "^6.3.6",
        "@wdio/mocha-framework": "^6.3.6",
        "@wdio/spec-reporter": "^6.3.6",
        "@wdio/sync": "^6.3.6",
        "chromedriver": "^84.0.1",
        "wdio-chromedriver-service": "^6.0.3",
        "@wdio/devtools-service": "^6.3.7"

**Config of WebdriverIO**
   Here's the link to the WDIO config file: https://github.com/somnanda/wdio6/blob/master/wdio.conf.js

   
**Describe the bug**
   Based on the setup in the github repo: https://github.com/somnanda/wdio6 , when I run the tests using command 'npx wdio wdio.conf.js', I get an error with the message:
```
browser.getPuppeteer is not a function
```

Stack below:
  
```
"spec" Reporter:
------------------------------------------------------------------
[chrome 84.0.4147.105 linux #0-1] Spec: /home/ubuntu/dev/wdio6/test/specs/pptr.e2e.js
[chrome 84.0.4147.105 linux #0-1] Running: chrome (v84.0.4147.105) on linux
[chrome 84.0.4147.105 linux #0-1] Session ID: 72e75c0b2b9576a49abc508f92ed17a9
[chrome 84.0.4147.105 linux #0-1]
[chrome 84.0.4147.105 linux #0-1] my e2e tests
[chrome 84.0.4147.105 linux #0-1]    ✖ replaces the WebdriverIO logo with the Puppeteer logo
[chrome 84.0.4147.105 linux #0-1]
[chrome 84.0.4147.105 linux #0-1] 1 failing (2.9s)
[chrome 84.0.4147.105 linux #0-1]
[chrome 84.0.4147.105 linux #0-1] 1) my e2e tests replaces the WebdriverIO logo with the Puppeteer logo
[chrome 84.0.4147.105 linux #0-1] browser.getPuppeteer is not a function
[chrome 84.0.4147.105 linux #0-1] TypeError: browser.getPuppeteer is not a function
[chrome 84.0.4147.105 linux #0-1]     at /home/ubuntu/dev/wdio6/test/specs/pptr.e2e.js:14:46
[chrome 84.0.4147.105 linux #0-1]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[chrome 84.0.4147.105 linux #0-1]     at Context.<anonymous> (/home/ubuntu/dev/wdio6/test/specs/pptr.e2e.js:13:17)
------------------------------------------------------------------
```

**To Reproduce**
  Please clone the repo and run 'npm install' and then 'npx wdio wdio.conf.js' to reproduce. https://github.com/somnanda/wdio6
  I'm also mentioning the steps I followed to create the project below: 
  - Followed the Getting Started page to setup Webdriver.io project for the new version v6.3.6 https://webdriver.io/docs/gettingstarted.html
   - In order to get Puppeteer setup, followed the instructions to get @wdio/devtools-service package in the project. https://webdriver.io/docs/devtools-service.html
   - Setup a test file pptr.e2e.js in the test/specs/ dir which has the following contents:
    
   ```
    describe('my e2e tests', () => {
    it('replaces the WebdriverIO logo with the Puppeteer logo', () => {
        browser.url('https://webdriver.io')

        /**
         * run Puppeteer code with promises to intercept network requests
         * and replace the WebdriverIO logo in the docs with the Puppeteer logo
         */
        const wdioLogo = 'webdriverio.png'
        const pptrLogo = 'https://user-images.githubusercontent.com/10379601/29446482-04f7036a-841f-11e7-9872-91d1fc2ea683.png'
        browser.call(async () => {
            const puppeteerBrowser = browser.getPuppeteer()
            const page = (await puppeteerBrowser.pages())[0]
            await page.setRequestInterception(true)
            page.on('request', (interceptedRequest) => (
                interceptedRequest.url().endsWith(wdioLogo)
                    ? interceptedRequest.continue({ url: pptrLogo })
                    : interceptedRequest.continue()
            ))
        })

        // continue with sync WebdriverIO commands
        browser.refresh()
        browser.pause(2000)
    })
    }) 
```
 

**Expected behavior**
   Puppeteer Tests should pass and the configurations should work as expected.

**Comment by christian-bromann** [comment]
I assume you have this script from https://github.com/webdriverio/webdriverio/blob/master/examples/devtools/intercept.js which is an example that works with the version that is currently on master but not yet released. A release will be done soon.
