### ISSUE TITLE
waitForClickable is not working for Appium Sessions on native apps

### ISSUE THREAD

**Issue by jayandran-Sampath** [webdriverio/webdriverio#5699]
**Is your feature request related to a problem? Please describe.**
WaitForClickable method is not helping while running appium session on native apps

**Describe the solution you'd like**
As per the current implementation in webdriverio, we are calling /execute command with script(Which is having conditions like no overlapping on the position, element within view position etc) since this functionality is not implemented in appium we could not achieve with same set of command. 

my suggestion :  Can we use existing implementation of isDisplayed & isEnabled to validate whether native app element is clickable. we can put condition to identify & execute this command for mobile native apps 

Implementation will be something like this 
 
 wait.until (isElementDisplayed(this.elementId) && isElementEnabled(this.elementId))

if we are good with this approach, i can raise PR for this

**Comment by mgrybyk** [comment]
You can overwrite the command in your project and use the approach you've mentioned in native context otherwise use original command.

I'd look for some other solution to guarantee the element is clickable in native context as far as visibility (that not always works) doesn't mean the element is visible, same with ”enabled”.

**Comment by jayandran-Sampath** [comment]
we are already using the same approach in our project and it works.

Agreeing with your point on native context.

**Comment by christian-bromann** [comment]
We could check if the session is a mobile session and only then fetch the context beforehand and ensure the last `execute` command is called only if the user is in the web context. What do you all think?

**Comment by jayandran-Sampath** [comment]
@christian-bromann  @mgrybyk 

As a temporary solution for native context, can we try using condition of appium Clickable attribute == true && isElementDisplayed(this.elementId) until we find proper solution?

**Comment by christian-bromann** [comment]
> can we try using condition of appium Clickable attribute == true

Can you explain what do you mean by that?

> until we find proper solution?

Why is [my proposal](https://github.com/webdriverio/webdriverio/issues/5699#issuecomment-670052830) not a proper solution?

**Comment by jayandran-Sampath** [comment]
@christian-bromann Sorry i dint get your solution properly, what i understood from your comment is we can have a condition to call /execute only in case of web context. Please correct me if i dint get it properly. So i thought its solution avoid to calling /execute method for appium.


As @mgrybyk commented, since we could not confirm whether the native element is clickable only by checking isDisplayed & isEnabled. 

So what im suggesting as alternate is, we could make use of appium Element attribute (i.e : clickable) & put condition of validating whether its true.

Similar to waitForDisplayed implementation, we can have condition for mobile context to check is Element displayed & element Clickable attribute is true.

for Web -> it will be existing implementation of /execute method with scripts

**Comment by christian-bromann** [comment]
> we could make use of appium Element attribute (i.e : clickable)

Do you have reference docs. I am not aware of such an Appium command.

**Comment by jayandran-Sampath** [comment]
@christian-bromann  my bad, Its not appium specific attribute.. this attribute (Clickable) is specific to UIAUTOMATOR and not available in XCUITEST. So we will not be able to use it.

UIAutomator ref : https://developer.android.com/reference/androidx/test/uiautomator/UiSelector#clickable

**Comment by christian-bromann** [comment]
@jayandran-Sampath you can use this feature as part of your selector to query elements that are clickable. There is nothing that can be implemented in WebdriverIO as this is UIAutomator related.

**Comment by ciekawy** [comment]
I think above solution does not work currently:

```
  console.info
    2024-03-22T20:58:32.446Z INFO webdriver: RESULT {
      'element-6066-11e4-a52e-4f735466cecf': '0.42436799002411085-5',
      ELEMENT: '0.42436799002411085-5'
    }

      at ../node_modules/@wdio/logger/build/node.js:102:9

  console.info
    2024-03-22T20:58:32.450Z INFO webdriver: COMMAND isElementDisplayed("0.42436799002411085-5")

      at ../node_modules/@wdio/logger/build/node.js:102:9
```
seems that `isElementDisplayed` gets wrongly parsed elementID (from number which gets formatted in a wrong way)

**Comment by christian-bromann** [comment]
> seems that `isElementDisplayed` gets wrongly parsed elementID

How is it wrongly parsed?
