### ISSUE TITLE
How to find element by text

### ISSUE THREAD

**Issue by tomitrescak** [webdriverio/webdriverio#570]
After page event, I need to find a new element by text. The `=value` selector seems to work only on anchor elements. I cannot find a way of doing this. Would you please help? Thanks. 

Example:
I want to find a div element that contains text "Group"

**Comment by christian-bromann** [comment]
Use the xPath selector:
'//div[contains(., "Group")]'

Just fyi: in v3 this is a bit simpler:
'div*=Group'

You will be also able to chain selectors:
'client.element("div").click("*=Group");'

**Comment by whitetrefoil** [comment]
Just leaving a note in case any newbie who know nothing about XPath like me dropped into the same hole: the `v3` above means "webdriverio v3", not "XPath v3"...

The document can be found at: http://webdriver.io/guide/usage/selectors.html

Just spent a whole day tried to learn XPath and looking for document about that "newly introduced syntax in XPath 3.0"...

**Comment by JasonMFry** [comment]
Just for clarity's sake, and because this is currently the 3rd google result for this, here's another example. If you're looking for a button whose text is `0`:

`browser.element('button*=0');`

To generalize, it's `browser.element('<element>*=<text>');`

**Comment by jcollum-autodesk** [comment]
`browser.element is not a function` in wdio 5.11

How do I do this in 5.x?

**Comment by mgrybyk** [comment]
Read docs https://webdriver.io/docs/selectors.html

**Comment by jcollum-autodesk** [comment]
`browser.element` does not appear on that page so I don't get how it is supposed to help

**Comment by mgrybyk** [comment]
Correct, don't use browser.element

**Comment by IgorSasovets** [comment]
Hi, team! Are there any ways to dynamically inject element text to the selector? Like below:
```
const text = 'Element text';
$(`button*=${text}`).click()
```

**Comment by christian-bromann** [comment]
@IgorSasovets yes, the example you provided should work.

**Comment by IgorSasovets** [comment]
@christian-bromann , thanks
