### ISSUE TITLE
Unable to pass SauceConnect version via WebDriver SauceService

### ISSUE THREAD

**Issue by apederson21** [webdriverio/webdriverio#5700]
Per a recent SauceLabs [announcement](https://wiki.saucelabs.com/display/DOCS/2020/08/04/Action+Required%3A+Sauce+Connect+Proxy+and+TLS+Deprecation+Notice%2C+October+5%2C+2020), "all versions of Sauce Connect Proxy prior to 4.6.x" are being deprecated.

The [SauceLabs package](https://github.com/saucelabs/node-saucelabs/blob/master/src/index.js#L213) allows you to specify a sauce connect version, but this appears to not be capable via WebDriver IO.

**Comment by christian-bromann** [comment]
Have you tried setting `scVersion` in your wdio.config.js?

**Comment by christian-bromann** [comment]
Actually I am wrong, you can define this property setting `sauceConnectOpts`:

```js
services: [['sauce', {
    sauceConnectOpts: {
        scVersion: '4.6.2'
    }
}]]
```

**Comment by apederson21** [comment]
Wasn't aware of that, thank you @christian-bromann
