### ISSUE TITLE
async onRunnerEnd on a custom reporter does not work

### ISSUE THREAD

**Issue by satyasreem** [webdriverio/webdriverio#5701]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:5.23.0** 
 - **Mode:** [ WDIO Testrunner]
 - **If WDIO Testrunner, running sync:**
 - **Node.js version:13.2.0** 
 - **NPM version: 6.3.1** 
 - **Browser name and version:Chrome**
 - **Platform name and version:** 
 - **Additional wdio packages used (if applicable):**
@wdio/spec-reporter

**Describe the bug**
Am creating a custom reporter that is an extension of the WDIO spec reporter.
I am wanting to do an async operation onRunnerEnd

```
 async onRunnerEnd(runner) {
       this.isSynchronising =true;

       //Do the async job
       await myAsyncJob();
       this.isSynchronising = false;
    }
```

But the onRunnerEnd never waits for this operation to complete. How do I get around this issue? I dont want to override the onSuiteEnd(). I really need the async job to be at the end of the runner.

**Comment by christian-bromann** [comment]
Please check the [docs](https://webdriver.io/docs/customreporter.html#wait-until-issynchronised).

**Comment by satyasreem** [comment]
Yes I saw that example and I am following that using the `get isSynchronised () {
        return this.unsynced.length === 0
    }
`  method.

onRunnerEnd still does not execute the async operation

**Comment by satyasreem** [comment]
I only want to execute that async operation inside onRunnerEnd - basically at the end of all tests.
Even with the sample example, this async operation is not executing.

**Comment by satyasreem** [comment]
Here is the full code.
```
const SpecReporter = require('@wdio/spec-reporter').default;
const webhookUrl = process.env.SLACK_WEBHOOK_URL || 'myURl';
const { IncomingWebhook } = require('@slack/webhook');
const webhook = new IncomingWebhook(webhookUrl, {
    icon_emoji: ":bowtie:",
});


class MyCustomReporter extends SpecReporter {

    constructor(options) {
        super(options);
        if (options.showFailedTestCases == undefined) {
            options.showFailedTestCases = false;
        }
        //This is WDIO way of making a sync call in its runner. Read : https://webdriver.io/docs/customreporter.html#wait-until-issynchronised
        this.isSynchronising = false;
    }

    get isSynchronised () {
        return this.isSynchronising;
    }

  
    async onRunnerEnd(runner) {
        this.isSynchronising = true;
        await this.asyncMethod();
        this.isSynchronised = false;
    }

    async asyncMethod() {
        await <Do something>;
    }
}
module.exports = MyCustomReporter;

```

I am not setting the interval as this is not required to run often. This is expected to run once at the end ,, like to send a summary of test results. 
Any tips is appreciated?

**Comment by BorisOsipov** [comment]
@satyasreem 
```
    async onRunnerEnd(runner) {
        await this.asyncMethod();
        this.isSynchronising = true;
    }
```

**Comment by satyasreem** [comment]
@BorisOsipov - That fixed it. Thanks a lot!
