### ISSUE TITLE
Only the first item from $$ array is an Element instance.

### ISSUE THREAD

**Issue by L0tso** [webdriverio/webdriverio#5703]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.4.0
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]

**Describe the bug**
```
 browser.url("https://webdriver.io")
 $$('div').forEach(element => {
    console.log(element.constructor.name)
 })
```
**Actual result**
```
Element
Browser
Browser
...
```

**Expected behavior**
```
Element
Element
...
```

**Additional context**
It happens because [webdriverMonad](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-utils/src/monad.js#L18) removes `scope` property from [propertiesObject](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/utils/getElementObject.js#L70). It can be fixed by resetting `scope` after each [map](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/utils/getElementObject.js#L76) iteration but I'm not sure, that it is the best way to solve it.

**Comment by christian-bromann** [comment]
@L0tso would you be open to take a stab at this?

**Comment by L0tso** [comment]
@christian-bromann [Done](https://github.com/webdriverio/webdriverio/pull/5705)
