### ISSUE TITLE
--cucumberOpts.name running all specs

### ISSUE THREAD

**Issue by abhinaba-ghosh** [webdriverio/webdriverio#5706]
Package.json

```
"devDependencies": {
    "@babel/cli": "^7.5.0",
    "@babel/core": "^7.5.0",
    "@babel/polyfill": "^7.4.4",
    "@babel/preset-env": "^7.5.0",
    "@babel/register": "^7.4.4",
    "@wdio/cucumber-framework": "^5.11.12",
    "@wdio/local-runner": "^5.11.12",
    "@wdio/selenium-standalone-service": "^5.11.2",
    "@wdio/spec-reporter": "^5.11.7",
    "@wdio/sync": "^5.11.11"
  },
  "dependencies": {
    "@wdio/cli": "^5.11.12",
    "dotenv": "^8.0.0",
    "webdriver": "^5.11.12"
  }
```

I am using ```--cucumberOpts.name``` command, but it is actually running all the specs. 

```
$ npx wdio --cucumberOpts.name="Search for a type that does not exist"

Execution of 3 spec files started at 2020-08-09T14:47:31.410Z

[0-2] RUNNING in chrome - /features/Search/DressSearch.feature
[0-1] RUNNING in chrome - /features/Navigation/MenuNavigation.feature
[0-0] RUNNING in chrome - /features/Authentication/Login.feature
```

Example repository: https://github.com/gavin771/tau_cucumber/tree/chapter_5_3

Is there any configuration changes needs to done?

**Comment by Sand5** [comment]
Hello there are no extra configs based on your command only one scenario should run in the file but on your screenshot all three scenarios run we should have the ability to run just one scenario in a particular file.

**Comment by mgrybyk** [comment]
Hello,

Please update to v6 which is highly recommended! Alternatively you can upgrade to the latest v5 version and follow https://webdriver.io/blog/2019/11/01/spec-filtering.html

Feel free to ask questions in the gitter channel

Cheers
