### ISSUE TITLE
Does webdriverio store the "last element"?

### ISSUE THREAD

**Issue by mike-suggitt** [webdriverio/webdriverio#571]
I'm attempting to implement a custom command that will allow me to do something like
```
client.element('.foo').getParent().then(....
```
From what I can tell so far the only state websdriverio has is the selenium session info?

**Comment by mike-suggitt** [comment]
I'm now looking at using ```elementIdElement``` but it looks like  ```..``` isn't recognised as xpath

**Comment by mike-suggitt** [comment]
Scratch that I looked at hte code and found I could fool it by using ```./..```.

This isn't an issue btw, more just musings about trying to do stuff :)

**Comment by christian-bromann** [comment]
@mike-suggitt what do you think, would it make sense to add a command like `getParent()`? What is your use case here?

**Comment by mike-suggitt** [comment]
@christian-bromann My use case is thus:

Given I have the following snippet from bootstrap
```
<div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email" data-selector="inputbox">
  </div>
```
And on validation errors another element gets appended to the .form-group element

Our cucumber tests use attribute handles in order to drill to particular areas of the app so for example it might be:
```
Given I set value of "inputbox" to "bob"
And I lose focus
Then I should see a validation message for "inputbox"
```
What would be nice is if we could have a step that was able to go up the DOM to the parent of "inputbox" then search for a known selector (e.g. '.validation-message')

Coming to your first question, no, it probably wouldn't. This is because even if you got the parent of an element you still can't do anything with it (until your chaining in v3). In this instance what I would probably do is for those few tests that "might" need the capability, just use ```elementIdElement('.something', './..', function() {....```

**Comment by christian-bromann** [comment]
Thanks for your input! I get your point here and it seems that you have the perfect solution for now. I will keep this issue in mind and if something similar like this pops up again I will going to find an easier solution for that. Thanks!
