### ISSUE TITLE
File Download using Headless Chrome/Chromium with WebdriverIO Devtools Protocol

### ISSUE THREAD

**Issue by vipulgupta2048** [webdriverio/webdriverio#5727]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Description of the improvement / report**
There is no clear documented way of how to download files with WebdriverIOv6 using Devtools protocol + headless browser. It has been quite a few stressful days trying to make a solution work, I would like to document it if you folks think it could be a worthy page of information. If not, I have already written a [blog](https://mixstersite.wordpress.com/2020/08/13/file-download-headless-chrome-chromium-webdriverio-devtools-chromedriver/) and made a [boilerplate project](https://github.com/vipulgupta2048/file-downloads-webdriverio-demo) to make it work and help other folks searching the internet for some answers. Happy to help! Thanks!

**Comment by christian-bromann** [comment]
@vipulgupta2048 I think it makes sense to add such an example to the [devtools service docs](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-devtools-service/README.md) which automatically generates the docs on the project homepage. You want to take a stab at it?

**Comment by vipulgupta2048** [comment]
@christian-bromann Roger that. Will open a PR.

**Comment by christian-bromann** [comment]
Let's continue conversations in the PR.
