### ISSUE TITLE
@wdio/sauce-service Job Names are not sliced when using Jasmine

### ISSUE THREAD

**Issue by GibbsB** [webdriverio/webdriverio#5728]
**Environment:**
 - **WebdriverIO version:** 6.0.1
 - **Mode:** WDIO TestRunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 11.3.0
 - **NPM version:** 6.14.5
 - **Browser name and version:** Chrome 84
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/sauce-service 6.1.16, @wdio/jasmine-framework 6.2.0

**Config of WebdriverIO**
```
services: [sauce],
framework: jasmine
```

**Describe the bug**
During the service.beforeTest(test) function, the suite title is updated from Jasmine__TopLevel__Suite to the real suite name using this slice:
```
if (this.suiteTitle === 'Jasmine__TopLevel__Suite') {
      this.suiteTitle = test.fullName.slice(0, test.fullName.indexOf(test.title) - 1);
} 
```
test.title is not defined for jasmine specResult objects. It should be test.description. https://jasmine.github.io/api/3.6/global.html#SpecResult

**To Reproduce**
```
describe('Description of Feature', () => {
  it('should not include this in the job name', () => {
    expect(true).toBe(true);
  });
});
```

The job name for this feature will be "Description of Feature should not include this in the job na". The final two characters are cut off due to the slice.

Adding log commands to beforeTest shows:
```
      console.log('FULLNAME: ' + test.fullName + ' TITLE: ' + test.title); /// FULLNAME: Description of Feature should not include this in the job name TITLE: undefined
      console.log('OUTPUT OF INDEXOF: ' + test.fullName.indexOf(test.title) - 1); /// OUTPUT OF INDEXOF: NaN
```

**Expected behavior**
Based on the description above, the title should be 'Description of Feature'
beforeTest(test) should use test.description, not test.title.

**Comment by christian-bromann** [comment]
Hey,
thanks for filing the issue. This seems indeed like bug. We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by christian-bromann** [comment]
PR was merged.
