### ISSUE TITLE
How to resume promise chain?

### ISSUE THREAD

**Issue by georgecrawford** [webdriverio/webdriverio#573]
Hi,

Thanks for this fantastic library. I'm trying to wrap my head around the Promise support in v3. I've looked through the examples and tests, but still can't answer this question.

I want, if possible, to do something like this:
```js
		var client = wdio.remote(config)
		.init()
		.url('http://test.com')
		.then(function() {
			console.log('URL loaded');
		});

// and in a separate statement:
		client
		.then(function() {
			console.log('next in queue');
		})
		.saveScreenshot(file)
		.end();
```
This doesn't work, which I understand as `client` is a fulfilled Promise from the start and `'next in queue` is printed immediately. But is there a way to break out of and re-enter the chain like this? My reasoning is that I'd like to pass `client` around between methods, in order to separate out reusable test steps and page setup. If this is the wrong approach, do you have any examples of a test run being configured by multiple reusable step or Page Object methods?

Many thanks for any advice!

**Comment by MaDetho** [comment]
+1

**Comment by christian-bromann** [comment]
Thanks for raising the question. I will write up a small documentation around it.

If you want to have reusable test steps I would recommend to use the `addCommand` functionality. It allows you to run reusable steps as a command within the chain. This way you also won't need to pass the client instance from one function to the other :wink: 

I was recently playing around with some Page Object approaches but I am still not sure which is the way to go. It will be part of the docs overhaul.

@georgecrawford does this work for you?

@MaDetho it seems that you've forgotten to initiate the client instance:
```js
// 1. initialise client instance
var client = require('webdriverio').remote({
    desiredCapabilities: {
         browser: 'chrome'
    }
});

// 2. run stuff
client.init().url(....)...
```

**Comment by georgecrawford** [comment]
Hi,

Yeah, that works fine. It was just counter-intuitive, so it'd be good to document the fact that this is the recommended (only?) way of constructing a complex chain which is configured across multiple files.

Incidentally, using this model, I'll need to call `addCommand` many times. It'd be good if it could throw an `Error` if a command is already defined with that name, so as to avoid unintentionally overwriting existing methods (perhaps with a second parameter to force the overwrite?).

**Comment by christian-bromann** [comment]
That's a good idea!

**Comment by georgecrawford** [comment]
@christian-bromann 

I've been playing around with this a bit more, and experimenting with some Page Object ideas. I quite like this simple pattern:

```js
	client.pages = {
		home: {
			client: client,
			url: 'http://test.com',
			load: function() {
				return this.client
				.url(this.url)
				.then(function() {
					console.log('URL loaded');
				});
			}
		}
	};
```

A page is then loaded like this:
```js
	client.addCommand('loadPage', function(page) {
		return client.pages[page].load();
	});

	client
	.init()
	.loadPage('home')
	.saveScreenshot();
```

I wonder if the `pages` object and the `loadPage` method, or similar, could be part of the webdriverio API?

**Comment by christian-bromann** [comment]
@georgecrawford I feel like that mixing the Page Object with the client instance is a bad idea. A Page Object should be something you create with `new ...` and should be able to inherit from another Page Object.

**Comment by christian-bromann** [comment]
But there is no right or wrong here. If you feel comfortable with your way of creating Page Objects, go ahead, maybe write a blog post about it when you have all pieces figured out

**Comment by georgecrawford** [comment]
Yep, good point. I'm looking forward to your proposals in the docs overhaul.
