### ISSUE TITLE
Wait by default

### ISSUE THREAD

**Issue by marklagendijk** [webdriverio/webdriverio#5732]
**Is your feature request related to a problem? Please describe.**
In the [release notes of version 6](https://webdriver.io/blog/2020/03/26/webdriverio-v6-released.html#devtools-automation-protocol-is-now-default) it says:

> Because of the great success of automation tools like Puppeteer and Cypress.io it became obvious that the WebDriver protocol in its current shape and form doesn't meet the requirements of todays developer and automation engineers.

This triggered me, because for me the main selling point of Cypress has always been that it _waits by default_. I would say that one of the major problems with webtests is flakiness. Very often tests will run fine locally, but then fail when run as part of your CI/CD pipeline.

I would summarize the problem as follows:
* The main problem with webtests is flakiness
* This problem can be solved by waiting for things (url to be something, elements to be clickable etc).
* Any modern webtesting framework should do this by default.

Now [expect-webdriverio](https://www.npmjs.com/package/expect-webdriverio) is a good step towards this direction, because it allows to wait for urls. What I don't understand is why this is made as a separate module, in my opinion it should be part of the core.

**Describe the solution you'd like**

** Solution 1 - waiting by default**
In webdriverio 7 waiting would automatically happens, similar to what Cypress does:
- https://docs.cypress.io/guides/core-concepts/interacting-with-elements.html#Actionability
- https://docs.cypress.io/guides/core-concepts/retry-ability.html#Commands-vs-assertions

**Solution 2 - non-verbose waiting code**
Currently 3 lines of code are needed to safely click an element:
```js
const element = $('.element');
element.waitForClickable();
element.click();
```
There are several ways to solve this:
1. Make `.click()` do a `waitForClickable()` by default, and allow to override.
2. Create separate commands that include the wait, e.g. `waitAndClick()`
3. At the very least, make all `waitFor` methods chainable. Now they will throw an error when the timeout is reached, and otherwise return a boolean. This is of course ridiculous, because the boolean will always be `true`. Returning the element itself would allow for chaining: `$('.element').waitForClickable().click()`

**Comment by marklagendijk** [comment]
Note: as a temporary workaround I created [webdriver-wait-and](https://www.npmjs.com/package/webdriverio-wait-and):
```js
$(".my-element").waitAnd().click();
$(".my-element").waitAndClick();
$(".my-element").waitAndSetValue("some value");
```
I will be very happy when this module will no longer be needed.

**Comment by klamping** [comment]
Since WebdriverIO v5, commands like `click` do wait by default. If the element doesn't exist when you run the command, it will automatically retry until the element exists, or the timeout is reached.

You should be able to just do `$(".my-element").click();` and it will automatically wait.

**Comment by marklagendijk** [comment]
This is not mentioned [in the documentation](https://webdriver.io/docs/api/element/click.html). Also there are no options with regards to waiting that you can pass into the method (similar to the wait methods).

**Comment by christian-bromann** [comment]
Non-deterministic tests are definitely one of the big frustration points for e2e test frameworks. As @klamping has pointed out WebdriverIO automatically waits for element to exist before running a command on it. This could be definitely be better visible in the documentation and if you have an idea where, please raise a PR.

Currently we only check if an element exist to run an action on it (e.g. click). There is [an issue](https://github.com/webdriverio/webdriverio/issues/2866) logged that asks to implement an element is not clickable auto-fix. I am not a big fan of running a bunch of checks prior an action as it would slow down tests tremendously and rather add the middleware that would run specific automation commands if a certain error pops up, e.g. element is not clickable.

Given that we already have `waitForExist` and `waitForDisplayed` I wouldn't necessarily mind to add a `waitForClickable` but it would be better if that happens automatically as you already have pointed out.

I would say working on #2866 would be a good next step. Are you interested to help us getting this landed? I am happy to support you on the way!

**Comment by mgrybyk** [comment]
Can we suggest [overwriting](https://webdriver.io/docs/customcommands.html#overwriting-native-commands) the [click](https://webdriver.io/docs/api/element/click.html) command?
```
browser.overwriteCommand('click', async function(clickFn, opts = {}) {
    if (opts.wait) { await this.waitForClickable() }
    await clickFn(opts)
})
// usage
await elem.click()
// do not wait
await elem.click({ wait: false })
```

I don't mind waiting by default however would insist to make the feature optional or/and at least the timeout configurable.

**Comment by christian-bromann** [comment]
> I don't mind waiting by default however would insist to make the feature optional or/and at least the timeout configurable.

As I mentioned above, I prefer to retry and wait for clickable if an click doesn't work right away. Always calling waitForClickable seems unnecessary to me and only slows down tests.

@marklagendijk I would say working on #2866 would be a good next step. Are you interested to help us getting this landed? I am happy to support you on the way!

**Comment by christian-bromann** [comment]
Closing as I think we are on the same side that #2866 is the right next step.

**Comment by marklagendijk** [comment]
> This could be definitely be better visible in the documentation and if you have an idea where, please raise a PR.

I would suggest adding a page `Deterministic tests` with a section explaining what WebdriverIO already does to make tests deterministic. Apart from that the page could contain some tips (such as using [Chrome's NetworkConditions](https://webdriver.io/docs/api/chromium.html#setnetworkconditions) to make failures deterministic) and examples (such as using expect to check the browser url).

We could then refer to this section in the documentation of all methods which it applies to (such as `click()`).

> I would say working on #2866 would be a good next step. Are you interested to help us getting this landed?

I am definitely interested. Can you give me some pointers on where in the code this should be implemented? (I didn't dive into the WebdriverIO code, yet). Note: I do have experience in contributing pull requests. For reference see [some of my contributions to k6](https://github.com/loadimpact/k6/releases/tag/v0.19.0). 

So I would love to contribute this. My only concern is that I can't be 100% sure I will find the time to do it.

**Comment by christian-bromann** [comment]
> I would suggest adding a page `Deterministic tests`

Sounds good to me

> Can you give me some pointers on where in the code this should be implemented?

We already have a [middle layer system](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/middlewares.js#L5-L44) in the `webdriverio` package that allows to retry commands in certain conditions (e.g. stale element exception). I think that would be were you would need to start looking into.

> So I would love to contribute this.

Awesome.
