### ISSUE TITLE
Error in "AfterTest Hook"  Error: IllegalState: Eyes not open, while using applitool services.

### ISSUE THREAD

**Issue by diptilenka** [webdriverio/webdriverio#5744]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2] 6.3.5
 - **Mode:** [Standalone mode or WDIO Testrunner] WDIO
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async] Sync
 - **Node.js version:** [e.g. 8.11.2] 12.18.0
 - **NPM version:** [e.g. 5.8.0]
 - **Browser name and version:** [e.g. Chrome 68]
 - **Platform name and version:** [e.g. Windows 10] Android
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]
"@wdio/allure-reporter": "^6.3.0",
    "@wdio/applitools-service": "6.3.0",
    "@wdio/appium-service": "^6.1.16",
    "@wdio/browserstack-service": "^6.1.15",
    "@wdio/cli": "^6.3.5",
    "@wdio/jasmine-framework": "^6.3.5",
    "@wdio/local-runner": "^6.3.5",
    "@wdio/spec-reporter": "^6.3.0",
    "@wdio/sync": "^6.3.3",
    "allure-commandline": "^2.13.0",
    "jasmine": "^3.6.1",
    "ts-node": "^8.10.1",
    "tsconfig-paths": "^3.9.0",
    "tslint": "^6.1.2",
    "typescript": "^3.8.3",
    "wdio-chromedriver-service": "^6.0.3",
    "webdriverio": "^6.3.5"
**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
I added browser.takeSnapshot('')
each time 
i.e (HomePage.hamburgerMenu as any).waitAndClick();
    (HomePage.hamburgerDocumentUpload as any).waitAndClick();
    expect(DocumentUploadPage.documentUploadHeaderText).toEqual('Upload')
    browser.takeSnapshot('workflow');
**To Reproduce**
Follow the document s like https://webdriver.io/docs/applitools-service.html
And also mentioned below lines in tsconfig.json
 "types": [
      "node",
      "@wdio/sync",
      "@wdio/jasmine-framework", "@wdio/applitools-service"

and in test 
it("should navigate from Home Screen to Document Upload Page.", () => {
    LoginHandler.switchBackAfterLoginContext();
     ContextHandler.waitForDocumentFullyLoaded();
    (HomePage.hamburgerMenu as any).waitAndClick();
    (HomePage.hamburgerDocumentUpload as any).waitAndClick();
    expect(DocumentUploadPage.documentUploadHeaderText).toEqual('Upload');
    browser.takeSnapshot('test');
  });

The above test passed if browser.takeSnapshot() was not added  and if added the eyes not open error.
[Include code or an example repository that can easily be set up]

**Expected behavior**
The test cases failed and shows 
Error: IllegalState: Eyes not open,
**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

i am using a mobile appp to automate, so its not a browser but a hybrid app.

> Please use the correct markdown

**Comment by dipti-code** [comment]
Attached the appium log 
arguments)","args":[]}[39m
[debug] [35m[W3C (4ac31947)][39m Calling AppiumDriver.execute() with args: ["return (() => document.readyState).apply(null, arguments)",[],"4ac31947-077d-401f-a809-f683722dcfb1"]
[debug] [35m[XCUITest][39m Executing command 'execute'
[debug] [35m[RemoteDebugger][39m Executing atom 'execute_script'
[debug] [35m[RemoteDebugger][39m Executing 'execute_script' atom in default context
[debug] [35m[RemoteDebugger][39m Sending javascript command: '(function(){return function(){var f=this;
[debug] [35m[RemoteDebugger][39m funct...'
[debug] [35m[RemoteDebugger][39m Sending '_rpc_forwardSocketData:' message to app 'PID:86751', page '1', target 'page-7' (id: 519): 'Runtime.evaluate'
[debug] [35m[RemoteDebugger][39m Received data response from send (id: 519): '{"status":0,"value":"complete"}'
[debug] [35m[RemoteDebugger][39m Sending to Web Inspector took 3ms
[debug] [35m[RemoteDebugger][39m Received result for atom 'execute_script' execution: "complete"
[debug] [35m[W3C (4ac31947)][39m Responding to client with driver.execute() result: "complete"
[35m[HTTP][39m [37m<-- POST /session/4ac31947-077d-401f-a809-f683722dcfb1/execute/sync [39m[32m200[39m [90m6 ms - 20[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/session/4ac31947-077d-401f-a809-f683722dcfb1/element[39m
[35m[HTTP][39m [90m{"using":"css selector","value":"button.mat-icon-button mat-icon.hyland-icons"}[39m
[debug] [35m[W3C (4ac31947)][39m Calling AppiumDriver.findElement() with args: ["css selector","button.mat-icon-button mat-icon.hyland-icons","4ac31947-077d-401f-a809-f683722dcfb1"]
[debug] [35m[XCUITest][39m Executing command 'findElement'
[debug] [35m[BaseDriver][39m Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [35m[BaseDriver][39m Waiting up to 0 ms for condition
[debug] [35m[RemoteDebugger][39m Executing atom 'find_element'
[debug] [35m[RemoteDebugger][39m Executing 'find_element' atom in default context
[debug] [35m[RemoteDebugger][39m Sending javascript command: '(function(){return function(){var k=this;functi...'
[debug] [35m[RemoteDebugger][39m Sending '_rpc_forwardSocketData:' message to app 'PID:86751', page '1', target 'page-7' (id: 521): 'Runtime.evaluate'
[debug] [35m[RemoteDebugger][39m Received data response from send (id: 521): '"{\"status\":0,\"value\":{\"ELEMENT\":\":wdc:1598293692365\"}}"'
[debug] [35m[RemoteDebugger][39m Sending to Web Inspector took 36ms
[debug] [35m[RemoteDebugger][39m Received result for atom 'find_element' execution: {"ELEMENT":":wdc:1598293692365"}
[debug] [35m[W3C (4ac31947)][39m Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"5029","ELEMENT":"5029"}
[35m[HTTP][39m [37m<-- POST /session/4ac31947-077d-401f-a809-f683722dcfb1/element [39m[32m200[39m [90m39 ms - 73[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/session/4ac31947-077d-401f-a809-f683722dcfb1/element/5029/displayed[39m
[35m[HTTP][39m [90m{}[39m
[debug] [35m[W3C (4ac31947)][39m Calling AppiumDriver.elementDisplayed() with args: ["5029","4ac31947-077d-401f-a809-f683722dcfb1"]
[debug] [35m[XCUITest][39m Executing command 'elementDisplayed'
[debug] [35m[RemoteDebugger][39m Executing atom 'is_displayed'
[debug] [35m[RemoteDebugger][39m Executing 'is_displayed' atom in default context
[debug] [35m[RemoteDebugger][39m Sending javascript command: '(function(){return function(){var h,l=this;func...'
[debug] [35m[RemoteDebugger][39m Sending '_rpc_forwardSocketData:' message to app 'PID:86751', page '1', target 'page-7' (id: 523): 'Runtime.evaluate'
[debug] [35m[RemoteDebugger][39m Received data response from send (id: 523): '"{\"status\":0,\"value\":true}"'
[debug] [35m[RemoteDebugger][39m Sending to Web Inspector took 43ms
[debug] [35m[RemoteDebugger][39m Received result for atom 'is_displayed' execution: true
[debug] [35m[W3C (4ac31947)][39m Responding to client with driver.elementDisplayed() result: true
[35m[HTTP][39m [37m<-- GET /session/4ac31947-077d-401f-a809-f683722dcfb1/element/5029/displayed [39m[32m200[39m [90m45 ms - 14[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/session/4ac31947-077d-401f-a809-f683722dcfb1/element/5029/click[39m
[35m[HTTP][39m [90m{}[39m
[debug] [35m[W3C (4ac31947)][39m Calling AppiumDriver.click() with args: ["5029","4ac31947-077d-401f-a809-f683722dcfb1"]
[debug] [35m[XCUITest][39m Executing command 'click'
[debug] [35m[RemoteDebugger][39m Executing atom 'click'
[debug] [35m[RemoteDebugger][39m Executing 'click' atom in default context
[debug] [35m[RemoteDebugger][39m Sending javascript command: '(function(){return function(){var h,aa=this;fun...'
[debug] [35m[RemoteDebugger][39m Sending '_rpc_forwardSocketData:' message to app 'PID:86751', page '1', target 'page-7' (id: 525): 'Runtime.evaluate'
[debug] [35m[RemoteDebugger][39m Received data response from send (id: 525): '"{\"status\":0,\"value\":null}"'
[debug] [35m[RemoteDebugger][39m Sending to Web Inspector took 14ms
[debug] [35m[RemoteDebugger][39m Received result for atom 'click' execution: null
[debug] [35m[W3C (4ac31947)][39m Responding to client with driver.click() result: null
[35m[HTTP][39m [37m<-- POST /session/4ac31947-077d-401f-a809-f683722dcfb1/element/5029/click [39m[32m200[39m [90m19 ms - 14[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/session/4ac31947-077d-401f-a809-f683722dcfb1/element[39m
[35m[HTTP][39m [90m{"using":"xpath","value":"(//span[@class='mat-line'])[4]"}[39m
[debug] [35m[W3C (4ac31947)][39m Calling AppiumDriver.findElement() with args: ["xpath","(//span[@class='mat-line'])[4]","4ac31947-077d-401f-a809-f683722dcfb1"]
[debug] [35m[XCUITest][39m Executing command 'findElement'
[debug] [35m[BaseDriver][39m Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [35m[BaseDriver][39m Waiting up to 0 ms for condition
[debug] [35m[RemoteDebugger][39m Executing atom 'find_element'
[debug] [35m[RemoteDebugger][39m Executing 'find_element' atom in default context
[debug] [35m[RemoteDebugger][39m Sending javascript command: '(function(){return function(){var k=this;functi...'
[debug] [35m[RemoteDebugger][39m Sending '_rpc_forwardSocketData:' message to app 'PID:86751', page '1', target 'page-7' (id: 527): 'Runtime.evaluate'
[debug] [35m[RemoteDebugger][39m Received data response from send (id: 527): '"{\"status\":0,\"value\":{\"ELEMENT\":\":wdc:1598293692370\"}}"'
[debug] [35m[RemoteDebugger][39m Sending to Web Inspector took 33ms
[debug] [35m[RemoteDebugger][39m Received result for atom 'find_element' execution: {"ELEMENT":":wdc:1598293692370"}
[debug] [35m[W3C (4ac31947)][39m Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"5030","ELEMENT":"5030"}
[35m[HTTP][39m [37m<-- POST /session/4ac31947-077d-401f-a809-f683722dcfb1/element [39m[32m200[39m [90m37 ms - 73[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/session/4ac31947-077d-401f-a809-f683722dcfb1/element/5030/displayed[39m
[35m[HTTP][39m [90m{}[39m
[debug] [35m[W3C (4ac31947)][39m Calling AppiumDriver.elementDisplayed() with args: ["5030","4ac31947-077d-401f-a809-f683722dcfb1"]
[debug] [35m[XCUITest][39m Executing command 'elementDisplayed'
[debug] [35m[RemoteDebugger][39m Executing atom 'is_displayed'
[debug] [35m[RemoteDebugger][39m Executing 'is_displayed' atom in default context
[debug] [35m[RemoteDebugger][39m Sending javascript command: '(function(){return function(){var h,l=this;func...'
[debug] [35m[RemoteDebugger][39m Sending '_rpc_forwardSocketData:' message to app 'PID:86751', page '1', target 'page-7' (id: 529): 'Runtime.evaluate'
[debug] [35m[RemoteDebugger][39m Received data response from send (id: 529): '"{\"status\":0,\"value\":true}"'
[debug] [35m[RemoteDebugger][39m Sending to Web Inspector took 44ms
[debug] [35m[RemoteDebugger][39m Received result for atom 'is_displayed' execution: true
[debug] [35m[W3C (4ac31947)][39m Responding to client with driver.elementDisplayed() result: true
[35m[HTTP][39m [37m<-- GET /session/4ac31947-077d-401f-a809-f683722dcfb1/element/5030/displayed [39m[32m200[39m [90m48 ms - 14[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/session/4ac31947-077d-401f-a809-f683722dcfb1/element/5030/click[39m
[35m[HTTP][39m [90m{}[39m
[debug] [35m[W3C (4ac31947)][39m Calling AppiumDriver.click() with args: ["5030","4ac31947-077d-401f-a809-f683722dcfb1"]
[debug] [35m[XCUITest][39m Executing command 'click'
[debug] [35m[RemoteDebugger][39m Executing atom 'click'
[debug] [35m[RemoteDebugger][39m Executing 'click' atom in default context
[debug] [35m[RemoteDebugger][39m Sending javascript command: '(function(){return function(){var h,aa=this;fun...'
[debug] [35m[RemoteDebugger][39m Sending '_rpc_forwardSocketData:' message to app 'PID:86751', page '1', target 'page-7' (id: 531): 'Runtime.evaluate'
[debug] [35m[RemoteDebugger][39m Received data response from send (id: 531): '"{\"status\":0,\"value\":null}"'
[debug] [35m[RemoteDebugger][39m Sending to Web Inspector took 95ms
[debug] [35m[RemoteDebugger][39m Received result for atom 'click' execution: null
[debug] [35m[W3C (4ac31947)][39m Responding to client with driver.click() result: null
[35m[HTTP][39m [37m<-- POST /session/4ac31947-077d-401f-a809-f683722dcfb1/element/5030/click [39m[32m200[39m [90m98 ms - 14[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/session/4ac31947-077d-401f-a809-f683722dcfb1/element[39m
[35m[HTTP][39m [90m{"using":"css selector","value":"h1.mat-toolbar__title"}[39m
[debug] [35m[W3C (4ac31947)][39m Calling AppiumDriver.findElement() with args: ["css selector","h1.mat-toolbar__title","4ac31947-077d-401f-a809-f683722dcfb1"]
[debug] [35m[XCUITest][39m Executing command 'findElement'
[debug] [35m[BaseDriver][39m Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [35m[BaseDriver][39m Waiting up to 0 ms for condition
[debug] [35m[RemoteDebugger][39m Executing atom 'find_element'
[debug] [35m[RemoteDebugger][39m Executing 'find_element' atom in default context
[debug] [35m[RemoteDebugger][39m Sending javascript command: '(function(){return function(){var k=this;functi...'
[debug] [35m[RemoteDebugger][39m Sending '_rpc_forwardSocketData:' message to app 'PID:86751', page '1', target 'page-7' (id: 533): 'Runtime.evaluate'
[debug] [35m[RemoteDebugger][39m Received data response from send (id: 533): '"{\"status\":0,\"value\":{\"ELEMENT\":\":wdc:1598293692371\"}}"'
[debug] [35m[RemoteDebugger][39m Sending to Web Inspector took 37ms
[debug] [35m[RemoteDebugger][39m Received result for atom 'find_element' execution: {"ELEMENT":":wdc:1598293692371"}
[debug] [35m[W3C (4ac31947)][39m Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"5031","ELEMENT":"5031"}
[35m[HTTP][39m [37m<-- POST /session/4ac31947-077d-401f-a809-f683722dcfb1/element [39m[32m200[39m [90m40 ms - 73[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/session/4ac31947-077d-401f-a809-f683722dcfb1/element/5031/text[39m
[35m[HTTP][39m [90m{}[39m
[debug] [35m[W3C (4ac31947)][39m Calling AppiumDriver.getText() with args: ["5031","4ac31947-077d-401f-a809-f683722dcfb1"]
[debug] [35m[XCUITest][39m Executing command 'getText'
[debug] [35m[RemoteDebugger][39m Executing atom 'get_text'
[debug] [35m[RemoteDebugger][39m Executing 'get_text' atom in default context
[debug] [35m[RemoteDebugger][39m Sending javascript command: '(function(){return function(){var h,l=this;func...'
[debug] [35m[RemoteDebugger][39m Sending '_rpc_forwardSocketData:' message to app 'PID:86751', page '1', target 'page-7' (id: 535): 'Runtime.evaluate'
[debug] [35m[RemoteDebugger][39m Received data response from send (id: 535): '"{\"status\":0,\"value\":\"Upload\"}"'
[debug] [35m[RemoteDebugger][39m Sending to Web Inspector took 40ms
[debug] [35m[RemoteDebugger][39m Received result for atom 'get_text' execution: "Upload"
[debug] [35m[W3C (4ac31947)][39m Responding to client with driver.getText() result: "Upload"
[35m[HTTP][39m [37m<-- GET /session/4ac31947-077d-401f-a809-f683722dcfb1/element/5031/text [39m[32m200[39m [90m43 ms - 18[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mDELETE[39m [37m/session/4ac31947-077d-401f-a809-f683722dcfb1[39m
[35m[HTTP][39m [90m{}[39m
[debug] [35m[W3C (4ac31947)][39m Calling AppiumDriver.deleteSession() with args: ["4ac31947-077d-401f-a809-f683722dcfb1"]
[debug] [35m[BaseDriver][39m Event 'quitSessionRequested' logged at 1598293701863 (23:58:21 GMT+0530 (India Standard Time))
[35m[Appium][39m Removing session 4ac31947-077d-401f-a809-f683722dcfb1 from our master session list
[debug] [35m[WD Proxy][39m Matched '/session/4ac31947-077d-401f-a809-f683722dcfb1' to command name 'deleteSession'
[debug] [35m[WD Proxy][39m Proxying [DELETE /session/4ac31947-077d-401f-a809-f683722dcfb1] to [DELETE http://127.0.0.1:8100/session/6CFE7660-2B19-4043-BF0E-5DE42A9E4D89] with no body
[debug] [35m[RemoteDebugger][39m Application 'PID:86751' disconnected. Removing from app dictionary.
[debug] [35m[RemoteDebugger][39m Current app is 'PID:86751'
[debug] [35m[RemoteDebugger][39m No longer have app id. Attempting to find new one.
[debug] [35m[RemoteDebugger][39m Application 'PID:86752' disconnected. Removing from app dictionary.
[debug] [35m[RemoteDebugger][39m Current app is 'undefined'
[debug] [35m[RemoteDebugger][39m Application 'PID:86754' disconnected. Removing from app dictionary.
[debug] [35m[RemoteDebugger][39m Current app is 'undefined'
[debug] [35m[WD Proxy][39m Got response with status 200: {
[debug] [35m[WD Proxy][39m   "value" : null,
[debug] [35m[WD Proxy][39m   "sessionId" : "2445A739-68B9-4820-9863-4E7480228820"
[debug] [35m[WD Proxy][39m }
[35m[DevCon Factory][39m Releasing connections for C8C99A9C-F800-498C-8C54-10F0BF825DC6 device on any port number
[35m[DevCon Factory][39m Found cached connections to release: ["C8C99A9C-F800-498C-8C54-10F0BF825DC6:8100"]
[debug] [35m[DevCon Factory][39m Cached connections count: 0
[debug] [35m[XCUITest][39m Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [35m[XCUITest][39m Found a remote debugger session. Removing...
[debug] [35m[RemoteDebugger][39m Disconnecting from remote debugger
[debug] [35m[RemoteDebugger][39m Cleaning up listeners
[debug] [35m[IOSSimulatorLog][39m Stopping iOS log capture
[debug] [35m[BaseDriver][39m Event 'quitSessionFinished' logged at 1598293702885 (23:58:22 GMT+0530 (India Standard Time))
[debug] [35m[W3C (4ac31947)][39m Received response: null
[debug] [35m[W3C (4ac31947)][39m But deleting session, so not returning
[debug] [35m[W3C (4ac31947)][39m Responding to client with driver.deleteSession() result: null
[debug] [35m[W3C (4ac31947)][39m Destroying socket connection
[35m[HTTP][39m [37m<-- DELETE /session/4ac31947-077d-401f-a809-f683722dcfb1 [39m[32m200[39m [90m1023 ms - 14[39m
[35m[HTTP][39m [90m[39m
[35m[Appium][39m Received SIGTERM - shutting down
[debug] [35m[Appium][39m There are no active sessions for cleanup
@christian-bromann

**Comment by dipti-code** [comment]
ERROR @wdio/sync: Error: IllegalState: Eyes not open
    at Object.isValidState (/Users/xxx/Documents/xxx/xxx/node_modules/@applitools/eyes-sdk-core/lib/utils/ArgumentGuard.js:226:11)
    at Object.close (/Users/xxx/Documents/xxx/xxx//node_modules/@applitools/eyes-sdk-core/lib/sdk/EyesBase.js:1140:21)
    at Object.close (/Users/xxx/Documents/xxx/xxx//node_modules/@applitools/eyes-sdk-core/lib/sdk/EyesClassic.js:678:8)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at ApplitoolsService.afterTest (//Users/xxx/Documents/xxx/xxx/node_modules/@wdio/applitools-service/build/index.js:99:20)
[0-0] Error in "AfterTest Hook"
IllegalState: Eyes not open




@christian-bromann

**Comment by christian-bromann** [comment]
@dipti-code can you provide a reproducible example?

**Comment by dipti-code** [comment]
To Reproduce
Steps to reproduce the behavior:
Follow the document s like https://webdriver.io/docs/applitools-service.html
And also mentioned below lines in tsconfig.json
"types": [
"node",
"@wdio/sync",
"@wdio/jasmine-framework", "@wdio/applitools-service"

and in test
it("should navigate from Home Screen to Document Upload Page.", () => {
LoginHandler.switchBackAfterLoginContext();
ContextHandler.waitForDocumentFullyLoaded();
(HomePage.hamburgerMenu as any).waitAndClick();
(HomePage.hamburgerDocumentUpload as any).waitAndClick();
expect(DocumentUploadPage.documentUploadHeaderText).toEqual('Upload');
browser.takeSnapshot('test');
});

@christian-bromann

**Comment by christian-bromann** [comment]
@dipti-code this isn't reproducible .. can you create an example repository that someone can clone and reproduce the error. No one knows what kind of setup you have and the devil can be in the detail.

**Comment by dipti-code** [comment]
@christian-bromann  Sorry , unable to share the huge code as per the company policy, if any other means like zoom call i can share with you.

**Comment by christian-bromann** [comment]
> unable to share the huge code as per the company policy

I am not asking for your project code, I am asking for a minimal example project that reproduces the problem. If this is a problem within WebdriverIO it should be reproducible in a new fresh simplified project.

**Comment by dipti-code** [comment]
@christian-bromann  you can download the git repo and run the iOS config.
https://github.com/dipti-code/applitool_webdriverio.git

**Comment by christian-bromann** [comment]
This is the Appium boilerplate project, it has no integration with Applitools.

**Comment by dipti-code** [comment]
I have integrated.Applitool for you. The error is same what am getting for my project also. @christian-bromann

**Comment by christian-bromann** [comment]
I don't see any Applitools in there, probably not pushed the latest code?

**Comment by dipti-code** [comment]
@christian-bromann check now. Pull the latest now.

**Comment by dipti-code** [comment]
@christian-bromann  Please help in this regards.

**Comment by christian-bromann** [comment]
@dipti-code sorry but there are a lot of other items on my plate that need attention. I am not sure if I am the right person to investigate this. Any contributions from outside would be helpful, thanks!

**Comment by christian-bromann** [comment]
As we have deprecated our Applitools integration this issue is not relevant anymore. We recommend to use [@applitools/eyes-webdriverio](https://www.npmjs.com/package/@applitools/eyes-webdriverio) from now on. Thanks!
