### ISSUE TITLE
Getting Syntax Error on prepare to run tests on saucelabs in docker container

### ISSUE THREAD

**Issue by maleeazeem** [webdriverio/webdriverio#5748]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** ^6.4.0
 - **Mode:** Jasmine
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]async
 - **Node.js version:** [e.g. 8.11.2] node 10 and node 12
 - **NPM version:** [e.g. 5.8.0] 6.14.7
 - **Browser name and version:** [e.g. Chrome 68] on saucelabs for internet explorer browser
 - **Platform name and version:** [e.g. Windows 10]Windows 10
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
services: [getConnectService()]

function getConnectService() {
    //const sauceTunnelName = 'wdio-tunnel-' + Math.random();
    try {
      return params.isSauce() ? ['sauce', {
        sauceConnect: true
      }] : 'selenium-standalone';
    } catch (err) {
        console.log("Error:" + err);
    }
}

**Describe the bug**
I upgraded wdio version to 6 in package.json file. There is no issue if I run my tests connecting saucelabs through my computer terminal. But If I create. docker image of it and run the container then I get an error "ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook". If I go back to wdio version 5 and rebuild my image then tests run perfectly fine. 

wdio version causing issue
    "@wdio/allure-reporter": "^6.3.6",
    "@wdio/cli": "^6.4.0",
    "@wdio/dot-reporter": "^6.4.0",
    "@wdio/jasmine-framework": "^6.4.0",
    "@wdio/local-runner": "^6.4.0",
    "@wdio/sauce-service": "^6.4.0",
    "@wdio/selenium-standalone-service": "^6.4.0",
    "@wdio/spec-reporter": "^6.4.0",
    "@wdio/sync": "^6.4.0",
    "fibers": "^5.0.0",
**NOTE** There is no issue if I run tests without building an image. Problem happens when I run tests on saucelabs in docker container

wdio version which works fine in docker container
    "@wdio/allure-reporter": "^5.13.2",
    "@wdio/cli": "^5.13.2",
    "@wdio/dot-reporter": "^5.13.2",
    "@wdio/jasmine-framework": "^5.13.2",
    "@wdio/local-runner": "^5.13.2",
    "@wdio/sauce-service": "^5.13.2",
    "@wdio/selenium-standalone-service": "^5.13.2",
    "@wdio/spec-reporter": "^5.13.2",
    "@wdio/sync": "^5.13.2",
    "wdio-json-reporter": "^1.3.1",

**To Reproduce**

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Log**
      2020-08-24T03:08:40.243Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
      Error: Command failed: /usr/webdriverio-cookbook/node_modules/saucelabs/build/.sc-v4.6.2/bin/sc --version
      /usr/webdriverio-cookbook/node_modules/saucelabs/build/.sc-v4.6.2/bin/sc: 1: /usr/webdriverio- 
    cookbook/node_modules/saucelabs/build/.sc-v4.6.2/bin/sc: Syntax error: "(" unexpected

    at Promise.all.then.arr (/usr/webdriverio-cookbook/node_modules/bin-check/node_modules/execa/index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)

    Continue...
    Deleted output files and folders from ./testingResultsJsonReporter/
    [0-1] RUNNING in internet explorer - /cookbook/test/specs/basic_sync.ui.js
   [0-0] RUNNING in internet explorer - /cookbook/test/specs/basic_async.ui.js
   [0-2] RUNNING in internet explorer - /cookbook/test/specs/googlesample.ui.js
   [0-1] 2020-08-24T03:09:05.876Z ERROR webdriver: Request failed with status 500 due to Error: Sauce could not start 
   your job. For more information on what happened, please visit 
   https://app.saucelabs.com/tests/355660dfdadf428d83fdxxxxxxxxxxxxxx
   [0-1] 2020-08-24T03:09:05.880Z ERROR webdriver: Error: Sauce could not start your job. For more information on what 
    happened, please visit https://app.saucelabs.com/tests/355660dfdxxxxxxxxxxxxxx
    at getErrorFromResponseBody (/usr/webdriverio-cookbook/node_modules/webdriver/build/utils.js:121:10)
    at WebDriverRequest._request (/usr/webdriverio-cookbook/node_modules/webdriver/build/request.js:149:56)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    [0-1] 2020-08-24T03:09:05.881Z ERROR @wdio/runner: Error: Failed to create session.
    Sauce could not start your job. For more information on what happened, please visit 
    https://app.saucelabs.com/tests/355660dfdadf428d83xxxxxxxxxxxxxx

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
@maleeazeem honestly I don't think this is a problem somewhere in WebdriverIO and rather in the [`saucelabs`](https://www.npmjs.com/package/saucelabs) NPM package. Would you mind creating an issue there?
