### ISSUE TITLE
When tests are excluded in the config file, there should be a message indicating the exclusion when trying to run excluded tests

### ISSUE THREAD

**Issue by cpeck-bi** [webdriverio/webdriverio#5762]
**Is your feature request related to a problem? Please describe.**
When attempting to run a test that is excluded in the wdio config, the message in the console simply says `@wdio/cli:launcher: No specs found to run, exiting with failure`

**Describe the solution you'd like**
The error message should read `"test file name" is excluded in the configuration file`

**Comment by christian-bromann** [comment]
> @wdio/cli:launcher: No specs found to run, exiting with failure

It says that if no specs are set up to run, e.g. when you exclude the same files that you have set as specs. I think this makes sense for me. Maybe I don't understand you, can you elaborate?

**Comment by cpeck-bi** [comment]
I understand that "No specs found" is technically correct, but the reason for this request is to make it clear _why_ no specs are found. I was looking at a new codebase, trying to run a spec file but getting the "No specs found" error; it took me some time to figure out that it was specifically excluded in the config file, and it would have been helpful if the error message itself told me this.

**Comment by christian-bromann** [comment]
I think we could enhance this message to include the spec and exclude globs similar to how Jest shows this:
```
No tests found
In /Users/stuart/git/api-server/jest/projects
  1 file checked.
  testMatch: /Users/stuart/git/api-server/__tests__/**/*.js - 0 matches
  testPathIgnorePatterns: /node_modules/ - 1 match
Pattern:  - 0 matches
```

**Comment by cpeck-bi** [comment]
Christian--can you guide me to where the error message is being created? This is my first time looking at WDIO repo but I'd like to try and make a PR to address this

**Comment by christian-bromann** [comment]
Sure, I usually never remember the position where something is in the code but for that we have a search and it showed me that you can find this part here: https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-cli/src/launcher.js#L176-L177

**Comment by christian-bromann** [comment]
Let's continue convo in #5763
