### ISSUE TITLE
Document how to extend type definition when having custom commands

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#5766]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Description of the improvement / report**

When someone uses WebdriverIO with TypeScript and adds a custom command, TypeScript won't automatically know about the existence of that command. The user needs to add a custom type definition like this:

```ts
declare namespace WebdriverIO {
    // adding command to `browser`
    export interface Browser {
        multiClick(selector: string, all?: boolean, optional?: boolean): boolean;
    }

    // adding command to `element`
    export interface Element {
        waitAndClick(): boolean;
    }
}
```

and reference that file in the `tsconfig.json`, e.g.:

```diff
-      "types": ["node", "@wdio/sync", "@wdio/mocha-framework"]
+      "types": ["node", "@wdio/sync", "@wdio/mocha-framework", "./wdio"]
```

Let's document this on our TypeScript docs page.

**Comment by hieuxlu** [comment]
Ok please assign me this one. Thanks.

**Comment by mgrybyk** [comment]
I'd use 
```
"typeRoots": [
      "./wdio"
    ]
```
instead of `"types"`.

**Comment by mgrybyk** [comment]
let's say I have a structure like this
![image](https://user-images.githubusercontent.com/25589559/91430528-5000fa80-e85f-11ea-95f3-3bc655550620.png)

I guess it's better to keep package types and custom types separately
```
  "types": [
    "node",
    "@wdio/mocha-framework",
    "@wdio/sync"
  ],
  "typeRoots": [
    "./src/types"
  ]
```

**Comment by hieuxlu** [comment]
@mgrybyk The problem with `typeRoots` is that it does not work well with `ts-node`. `ts-node` dictates typeRoots folder to be structured as below, and even after that, lots of people still have problem with it (https://github.com/TypeStrong/ts-node/issues/782), so I propose updating the docs to remove any use of `typeRoots`. 
```
<project_root>/
-- tsconfig.json
-- typings/
  -- <module_name>/
    -- index.d.ts
```
That's why the very good Typescript boilerlate here uses `types` instead of `typeRoots`. I myself can not make `ts-node` to work with `typeRoots` in this boilerplate either, even though VSCode Intellisense recognizes the typings.
https://github.com/pako88/wdio-mocha-typescript

If you agree, I will make the necessary change to update the wdio docs to use `types` instead of `typeRoots` and maybe point the working boilerplate above.

**Comment by mgrybyk** [comment]
@hieuxlu got it. Actually I'm not using `typeRoots` at all in my projects.
Here is `tsconfig.json`
```
{
  "compilerOptions": {
    "outDir": "./.tsbuild/",
    "sourceMap": false,
    "target": "es2019",
    "module": "commonjs",
    "removeComments": true,
    "noImplicitAny": true,
    "strictPropertyInitialization": true,
    "strictNullChecks": true,
    "types": [
      "node",
      "@wdio/mocha-framework",
      "@wdio/sync"
    ],
  },
  "include": [
    "./test/**/*.ts",
    "./src/**/*.ts",
    "./config/*.ts"
  ]
}
```
I have 
`src/wdio/commands.ts`
```
browser.addCommand("getLink", function () {
    const el: WebdriverIO.Element = this

    return el.optAttribute("href")
}, true)
```
and types in `src/types/wdio.d.ts`
```
declare namespace WebdriverIO {
    interface Element {
        getLink (): string
    }
}
```

That's it. I can now use `$('a.page').getLink()`

No need to add `src/types/wdio.d.ts` explicitly to types!

**Comment by mgrybyk** [comment]
There is a guide on how to add custom command https://webdriver.io/docs/typescript.html#adding-custom-commands

**Comment by mgrybyk** [comment]
@hieuxlu please also see what does `ts-node` guys suggest [Help! My Types Are Missing](https://github.com/TypeStrong/ts-node#help-my-types-are-missing)

**Comment by hieuxlu** [comment]
> @hieuxlu please also see what does `ts-node` guys suggest [Help! My Types Are Missing](https://github.com/TypeStrong/ts-node#help-my-types-are-missing)

Yes, either using `include` or `types` but not `typeRoots`. You link is what I said above, following a module structure for `typeRoots`, which does not work for me. 

So I will update the guidelines to use either `types` or `includes`.

**Comment by mgrybyk** [comment]
@hieuxlu I'm not sure it worst using typeRoots and adding types for custom type definitions at all. Please see https://github.com/webdriverio/webdriverio/issues/5766#issuecomment-683264193

**Comment by mgrybyk** [comment]
@hieuxlu please see updated TypeScript setup doc https://webdriver.io/docs/typescript.html#framework-setup
