### ISSUE TITLE
Not able to capture performance data using webdriverio

### ISSUE THREAD

**Issue by akhilsingla123** [webdriverio/webdriverio#5776]
Trying to capture performance data using webdriverio but getting error:

**browser.enablePerformanceAudits is not a function**

Note : Not using wdio to run code, need to run it as standalone code.

       const { remote } = require('webdriverio')

      let browser;

     (async () => {
     browser = await remote({
     automationProtocol: 'devtools',
     capabilities: {
        browserName: 'chrome'
     }
     })

     browser.enablePerformanceAudits();
     await browser.url('https://webdriver.io');
     let metrics = browser.getMetrics()

     console.log(metrics);

     await browser.call(async () => {
    const puppeteerBrowser = browser.getPuppeteer()
    //puppeteerBrowser.enablePerformanceAudits();
    const page = (await puppeteerBrowser.pages())[0]
    await page.setRequestInterception(true)
    page.on('request', interceptedRequest => {
        if (interceptedRequest.url().endsWith('webdriverio.png')) {
            return interceptedRequest.continue({
                url: 'https://user-images.githubusercontent.com/10379601/29446482-04f7036a-841f-11e7-9872-91d1fc2ea683.png'
            })
        }

        interceptedRequest.continue()
       })
       })

      // continue with WebDriver commands
      await browser.refresh()
      await browser.pause(2000)

      await browser.deleteSession()
      })().catch(async (e) => {
     console.error(e)
     await browser.deleteSession()
     })

**Comment by christian-bromann** [comment]
> Note : Not using wdio to run code, need to run it as standalone code.

The devtools service only works if you run WebdriverIO with the test runner. Please see [this example repo](https://github.com/christian-bromann/webdriverio-performance-testing).
