### ISSUE TITLE
@wdio/selenium-standalone-service is a using a couple version out of date selenium-standalone

### ISSUE THREAD

**Issue by Matt-Varney** [webdriverio/webdriverio#5791]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.4.5
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 12.18.3
 - **NPM version:** 6.14.6
 - **Browser name and version:** chrome v85
 - **Platform name and version:** windows 10
 - **Additional wdio packages used (if applicable):** @wdio/selenium-standalone service

**Config of WebdriverIO**

**Describe the bug**
The @wdio/selenium-standalone-service is using version 6.15.1 of selenium-standalone, this defaults the browser driver version downloaded and used to v83, however v85 is now the latest chrome version and so this should be installed by default, this can be achieved by updating wdio/selenium-standalone-service dependancies to use selenium-standalone 6.19.0

**To Reproduce**
Use selenium standalone service in your project

**Expected behavior**
latest version of chromedriver downloaded and used to run tests

**Comment by mgrybyk** [comment]
Hello,

There is no need to update `selenium-standalone` version explicitly.
Installing `@wdio/selenium-standalone-service` adds `selenium-standalone` of the latest version.

You can always specify browser driver versions you'd like to use, see https://webdriver.io/docs/selenium-standalone-service.html#configuration

**Comment by Matt-Varney** [comment]
@mgrybyk I can see selenium-standalones latest version is 6.19.0 and downloads chromedriver version 85.x.x in the default config. However the latest version of @wdio/selenium-standalone-service (v6.4.0) downloads selenium-standalone 6.15.1 as a dependency.

**Comment by mgrybyk** [comment]
Don't worry about that, the latest version of selenium standalone is installed along with the service.
You can try it yourself. Create a new project, install the service, see the version of selenium standalone.

**Comment by Matt-Varney** [comment]
@mgrybyk You're right, strange whenever I installed @wdio/selenium-standalone-service it was always installed selenium-standalone version 6.15.1 with it even when I deleted and allowed my package-lock.json to be regenerated, however after uninstalling it, deleting my package lock and doing an npm cache clean -f, it is now installing version 6.19.0 as you said. Thanks for the help.
