### ISSUE TITLE
Remove Babel from the project

### ISSUE THREAD

**Issue by erwinheitzman** [webdriverio/webdriverio#5795]
**Is your feature request related to a problem? Please describe.**
In #5446 (part of #5424) Babel was replaced with TypeScript. However, Babel was not yet removed which still needs to be done.

**Describe the solution you'd like**
Remove Babel from the project.

**Additional context**
If Babel is still used somewhere, please share your findings here so that we can discuss the solutions.

**Comment by christian-bromann** [comment]
See my draft PR.
