### ISSUE TITLE
browser.uploadFile file command throws Java heap space for a large file to upload

### ISSUE THREAD

**Issue by AutomationGuru** [webdriverio/webdriverio#5798]
**Environment (please complete the following information):**
 - **WebdriverIO version:** latest - 6.4.6 (can reproduce it on 6.1 hence also used the latest)
 - **Mode:** wdio runner
 - **If WDIO Testrunner, running sync/async:** Sync
 - **Node.js version:** v14.4.0
 - **NPM version:** 6.14.5
 - **Browser name and version:** Chrome 83
 - **Platform name and version:** mac
 - **Additional wdio packages used (if applicable):** [ 
"@wdio/browserstack-service": "^6.4.6",
    "@wdio/cli": "^6.4.6",
    "@wdio/devtools-service": "^6.4.6",
    "@wdio/junit-reporter": "^6.4.0",
    "@wdio/local-runner": "^6.4.6",
    "@wdio/mocha-framework": "^6.4.0",
    "@wdio/spec-reporter": "^6.4.0",
    "@wdio/sync": "^6.4.6",
]

**Config of WebdriverIO**
wdio config file to run the specs

**Describe the bug**
Given i have to upload a media file to a remote running instance then i see that using browser.uploadFile(file path) 
i see that it fails to upload the file to the remote test running on browser stack 

**To Reproduce**
Use a media file of size 25mb or greater and when i upload the file to a remote running browser i see the failure (note works fine locally when i use the path)
html>
<head>
<title>Error 500 Java heap space</title>
</head>
<body>
<h2>HTTP ERROR: 500</h2><pre>Java heap space</pre>
<p>RequestURI=/wd/hub/session/17e547b01a7f1fd4af3a417d343abe81bcbd911c/file</p>
<p><i><small><a href="http://jetty.mortbay.org">Powered by Jetty://</a></small></i></p>
</body>
</html>

[Include code or an example repository that can easily be set up]

**Expected behavior**
Should allow user to upload the video/image file or provide a valid error or limit of the file size i can use 

**Log**
**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
I think this is a limitation to the selenium standalone server. I doubt this can be fixed in WebdriverIO. Therefor I am closing this issue. Happy to assist with further questions. Thanks!

**Comment by AutomationGuru** [comment]
But this is remote selenium hub on browserstack !![bitmoji](https://sdk.bitmoji.com/render/panel/7e3bc453-64fb-4a34-bcaa-481724e5d3d9-0d4341bc-bdf2-4195-94d5-6d787e8fb174-v1.png?transparent=1&palette=1&width=246)
