### ISSUE TITLE
"browser is undefinded" when to run wdio cli with config "mochaOpts: { parallel: true }"

### ISSUE THREAD

**Issue by VicGrygorchyk** [webdriverio/webdriverio#5802]
**Environment:**
 - ** "@wdio/cli": "^6.4.5",
    "@wdio/local-runner": "^6.4.5",
    "@wdio/mocha-framework": "^6.4.0",
    "@wdio/spec-reporter": "^6.4.0",
    "@wdio/sync": "^6.4.5",
    "webdriverio": "^6.4.2",:**
 - ** WDIO Testrunner]:**
 - **sync test runner:**
 - **Node.js ver 12.18.3:** 
 - **NPM ver 6.14.6:** [e.g. 5.8.0]
 - **Chrome 85.0.4183.83, chromedriver 85.0.4183.87, Firefox 80.0.1, geckodriver 0.27.0**
 - **Windows 10 64bit:**

**Config of WebdriverIO**
```
exports.config = {
    runner: 'local',
    protocol: 'http',
    port: 4444,
    host: 'localhost',
    path: '/wd/hub',
    automationProtocol: 'webdriver',
    specs: [
        './e2e_tests/*',
        './e2e_tests/*/*'
    ],
    maxInstances: 10,
    capabilities: [
        {
            browserName: 'chrome',
            acceptInsecureCerts: true
        },
        {
            browserName: 'firefox',
        },
    ],
    logLevel: 'error',
    bail: 0,
    waitforTimeout: 20000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 1,
    specFileRetries: 1,
    specFileRetriesDeferred: true,
    reporters: ['spec'],

    framework: 'mocha',
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    }
};

```

**Describe the bug**
wdio cli crashes on the test run with the exception `ReferenceError: browser is not defined` when to pass a param `parallel` to the `mochaOpt` configs.
1) Add `mochaOpts: { parallel: true }` into `wdio.config.js`
2) Create at least 2 separate spec files with any tests inside.
3) Run your tests with the command `npx wdio path/to/wdio.config.js --specs path/to/tests_specs`

Result: 'browser is undefinded` error occurs when the browser starts.

**Expected behavior**
wdio cli should pass `parallel` param to mocha test-runner, what should handle parallel execution of the spec files.

Error:
```
------------------------------------------------------------------
[firefox 80.0.1 windows #1-1] Spec: C:\Projects\Autotests\e2e_tests\smoke2.spec..js
[firefox 80.0.1 windows #1-1] Running: firefox (v80.0.1) on windows
[firefox 80.0.1 windows #1-1] Session ID: cc674f86-8599-48d8-8fd7-836fddc79eb1
[firefox 80.0.1 windows #1-1]
[firefox 80.0.1 windows #1-1] Just a test suite
[firefox 80.0.1 windows #1-1]    ✖ should run this test
[firefox 80.0.1 windows #1-1]
[firefox 80.0.1 windows #1-1] 1 failing (4.8s)
[firefox 80.0.1 windows #1-1]
[firefox 80.0.1 windows #1-1] browser is not defined
[firefox 80.0.1 windows #1-1] ReferenceError: browser is not defined
[firefox 80.0.1 windows #1-1]     at Context.<anonymous> (C:\Projects\Autotests\e2e_tests\smoke2.spec..js:4:9)
[firefox 80.0.1 windows #1-1]     at callFn (C:\Projects\Autotests\node_modules\mocha\lib\runnable.js:358:21)
[firefox 80.0.1 windows #1-1]     at Test.Runnable.run (C:\Projects\Autotests\node_modules\mocha\lib\runnable.js:346:5)
[firefox 80.0.1 windows #1-1]     at Runner.runTest (C:\Projects\Autotests\node_modules\mocha\lib\runner.js:621:10)
[firefox 80.0.1 windows #1-1]     at C:\Projects\Autotests\node_modules\mocha\lib\runner.js:745:12
[firefox 80.0.1 windows #1-1]     at next (C:\Projects\Autotests\node_modules\mocha\lib\runner.js:538:14)
[firefox 80.0.1 windows #1-1]     at C:\Projects\Autotests\node_modules\mocha\lib\runner.js:548:7
[firefox 80.0.1 windows #1-1]     at next (C:\Projects\Autotests\node_modules\mocha\lib\runner.js:430:14)
[firefox 80.0.1 windows #1-1]     at Immediate.<anonymous> (C:\Projects\Autotests\node_modules\mocha\lib\runner.js:516:5)
[firefox 80.0.1 windows #1-1]     at processImmediate (internal/timers.js:456:21)
```

**Comment by christian-bromann** [comment]
> 1. Add `mochaOpts: { parallel: true }` into `wdio.config.js`

This is not supported in WebdriverIO. The WDIO testrunner has its own way to run tests in parallel. There is no need to use the Mocha feature.

**Comment by VicGrygorchyk** [comment]
Shall we mention it anywhere in documentation. please, or it's already there?

**Comment by christian-bromann** [comment]
See [my commit](https://github.com/webdriverio/webdriverio/commit/a0c5bd08044a76b6341bf58655a068afaaad45bc) 😉  it will be published with the next release.
