### ISSUE TITLE
retry when test fail to start

### ISSUE THREAD

**Issue by fege** [webdriverio/webdriverio#5807]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.1.17
 - **Mode:**  WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version: v12.16.1
 - **NPM version:** [e.g. 5.8.0]
 - **Browser name and version:** [e.g. Chrome 68]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
retry: 1,
retryTagFilter: '@retry'
scenarioLevelReporter: true

**Describe the bug**
Scenario is marked with @retry and fails in the preparation (create session), like 

```
740[0-1]  Error:  Failed to create session.
741socket hang up
```

the Scenario is not been retried 

**To Reproduce**

[Include code or an example repository that can easily be set up]

**Expected behavior**
Retry the failed scenario

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
Can you provide a minimal reproducible example?

**Comment by fege** [comment]
the socket problem is coming from appium or better Gradle https://github.com/gradle/gradle/issues/9813 but due to this the session is not started and the @retry does not come in action, while with proper test failure the @retry works fine

**Comment by christian-bromann** [comment]
@fege thanks for the input. Would you mind taking a look into the WebdriverIO codebase to see why this failure is not properly propagated? It is impossible for someone without a reproducible example to find out what issue you are facing.

**Comment by fege** [comment]
I could try,  @christian-bromann can you point me in which part of the codebase look?

**Comment by christian-bromann** [comment]
Please check the `wdio-runner` package as it is responsible for executing the worker.

**Comment by christian-bromann** [comment]
Any updates @fege ?

**Comment by fege** [comment]
no sorry @christian-bromann , not so much time to investigate

**Comment by christian-bromann** [comment]
Closing. Without reproducible example it will be impossible to continue any investigations.
