### ISSUE TITLE
not possible to modify specFileRetries in beforeSession to retry on a specific spec 

### ISSUE THREAD

**Issue by fege** [webdriverio/webdriverio#5810]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.1.17
 - **Mode:**  WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version: v12.16.1
 - **NPM version:** [e.g. 5.8.0]
 - **Browser name and version:** [e.g. Chrome 68]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
```
 specFileRetries: 0,
 beforeSession: function (config, capabilities, specs) {
     const string_specs = specs.toString()
     if (string_specs.includes("coffee_upload"))
        config.specFileRetries = 1
  }

```
**Describe the bug**
specFileRetries change on beforeSession hook it is not applied.
this is needed because I would like to retry only 1 spec in case of error not all the specs were there could be an error 

**To Reproduce**

[Include code or an example repository that can easily be set up]

**Expected behavior**
Override `specFileRetries` or having the possibility to indicate which spec should be retried in case of error

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
Hey,
thanks for filing the issue. This seems indeed like a good enhancement. We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by erwinheitzman** [comment]
Tested and this works with the current version
