### ISSUE TITLE
Add option parameter to `url` command to inject a script before opening the page

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#5813]
**Is your feature request related to a problem? Please describe.**
A lot of times people are interested in setting up the web environment in a certain way to listen to certain events or or modify some of the JS APIs so they can get information out of it. Injecting JS is possible via WebDriver but only after the page load has happened. The problem we want to solve is to allow this before the page load starts.

**Describe the solution you'd like**
As we are integrating more tightly with DevTools and Puppeteer we could enhance the url command to take a script (either a JS function or a script as a string) as second option parameter and use Puppeteer to inject this into the page, e.g.

```js
browser.url('https://webdriver.io', {
  inject: () => {
    const origFetch = window.fetch
    window.fetch = () => { ... }
  }
})
```

This of course would only work for local testing but something well in the scope of the new WebDriver-Bidi protocol to have cross browser support soon.

**Describe alternatives you've considered**
There are none.

**Additional context**
n/a

**Comment by emilyrohrbough** [comment]
There would be value in after the page is loaded is well. For example, we have a custom afterCommand in our test setup for disable/remove the cursor styles because we often had mismatched screenshots due to the cursor blinking.

**Comment by christian-bromann** [comment]
> There would be value in after the page is loaded is well.

Couldn't you just do:

```js
browser.url("...")
browser.execute(() => // disable cursor style)
```
?

**Comment by emilyrohrbough** [comment]
Yeah that is true. NVM.

**Comment by AutomationReddy** [comment]
@christian-bromann I am always receiving this when running `npm run test:mocha`

I tried many ways but no luck. Windows issue

```
$ npm run test:mocha

> @ test:mocha C:\Users\VinodReddy\Desktop\webdriverio\examples\wdio
> ../../packages/wdio-cli/bin/wdio.js ./mocha/wdio.conf.js

'..' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ test:mocha: `../../packages/wdio-cli/bin/wdio.js ./mocha/wdio.conf.js`
npm ERR! Exit status 1
```

**Comment by AutomationReddy** [comment]
NVM. I will switch to Mac.

**Comment by christian-bromann** [comment]
To have this work in Windows you need to prefix the commands in the [package.json](https://github.com/webdriverio/webdriverio/blob/master/examples/wdio/package.json) with `node`:

```diff
{
  "scripts": {
-    "test:mocha": "../../packages/wdio-cli/bin/wdio.js ./mocha/wdio.conf.js",
+    "test:mocha": "node ../../packages/wdio-cli/bin/wdio.js ./mocha/wdio.conf.js",
-    "test:jasmine": "../../packages/wdio-cli/bin/wdio.js ./jasmine/wdio.conf.js",
+    "test:jasmine": "node ../../packages/wdio-cli/bin/wdio.js ./jasmine/wdio.conf.js",
-    "test:cucumber": "../../packages/wdio-cli/bin/wdio.js ./cucumber/wdio.conf.js",
+    "test:cucumber": "node ../../packages/wdio-cli/bin/wdio.js ./cucumber/wdio.conf.js",
-    "test:multiremote": "../../packages/wdio-cli/bin/wdio.js ./multiremote/wdio.conf.js",
+    "test:multiremote": "node ../../packages/wdio-cli/bin/wdio.js ./multiremote/wdio.conf.js",
-    "test:customReporter": "../../packages/wdio-cli/bin/wdio.js ./custom-reporter/wdio.conf.js",
+    "test:customReporter": "node ../../packages/wdio-cli/bin/wdio.js ./custom-reporter/wdio.conf.js",
-    "test:customService": "../../packages/wdio-cli/bin/wdio.js ./custom-service/wdio.conf.js"
+    "test:customService": "node ../../packages/wdio-cli/bin/wdio.js ./custom-service/wdio.conf.js"
  }
}
```

**Comment by christian-bromann** [comment]
A PR for this has been proposed in #5929. Let's continue convo there.
