### ISSUE TITLE
Property 'sharedStore' does not exist on type 'BrowserObject'.ts

### ISSUE THREAD

**Issue by kamalgirdher-rally** [webdriverio/webdriverio#5815]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** wdio/cli : ^6.1.24
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:**  11.3.0
 - **NPM version:** 6.4.1
 - **Browser name and version:** chorme 85.0.4183.83 
 - **Platform name and version:** MacOS Catalina 10.15.4 
 - **Additional wdio packages used (if applicable):**  @wdio/allure-reporter(6.1.23), @wdio/cli(6.1.24), @wdio/dot-reporter(6.1.23), @wdio/jasmine-framework(6.1.23), @wdio/local-runner(6.1.24), @wdio/sauce-service(6.1.16), @wdio/selenium-standalone-service(6.1.14), @wdio/shared-store-service(6.4.7), @wdio/spec-reporter(6.1.23), @wdio/sync(6.1.14)

**Config of WebdriverIO**
services: [
            ['selenium-standalone'],
            'intercept',
            ['shared-store']
        ],

**Describe the bug**
Getting compile time error on sharedStore object saying "Property 'sharedStore' does not exist on type 'BrowserObject'.ts"

**To Reproduce**
With above configuration, trying to access sharedStore object and it is giving compile time error. I have checked in node-modules/@wdio/shared-store-service/shared-store-service.d.ts and it is showing error at step 
`type jsonArray = Array<jsonPrimitive | jsonObject | jsonArray>;`

Error says: Type alias 'jsonArray' circularly references itself.

Code Snippet:
```
describe('This is my test', () => {
  it('should land on home page', () => {
    browser.sharedStore.set('usr','KAMAL');
    console.log(browser.sharedStore.get('usr'));
  });
```

**Expected behavior**
Should be able to access sharedStore object.

**Log**
No logs. Compile time error.

**Additional context**

> Please use the correct markdown

**Comment by mgrybyk** [comment]
@kamalgirdher-rally please make sure to use the latest version of TypeScript and add `"@wdio/shared-store-service"` to `types` in tsconfig.json
It's not reproducible for me locally with TypeScript version 3.9.7

**Comment by mgrybyk** [comment]
Please see https://github.com/microsoft/TypeScript/pull/33050

Let me know if you have any further questions
