### ISSUE TITLE
browser.mock doesn't work in Browserstack

### ISSUE THREAD

**Issue by syedasadulhaq** [webdriverio/webdriverio#5816]
I'm using the wdio6 mock function. It works fine locally & CI. But it is not working in Browserstack. I have tried in chrome & edge browser. 

It throws the following error: 
Failed to fetch browser webSocket url from http://localhost:54908/json/version: connect ECONNREFUSED 127.0.0.1:54908

**Comment by christian-bromann** [comment]
@syedasadulhaq please see the note at the top of this page: https://webdriver.io/docs/mocksandspies.html

**Comment by Samic8** [comment]
Hi. Are there issues that I could follow to get updated when this is available?
