### ISSUE TITLE
'Cannot read property 'waitForExist' of undefined' error is displayed in console when i use waitForExist method on mobile native iOS app with Appium

### ISSUE THREAD

**Issue by Alona-T** [webdriverio/webdriverio#5817]
**Environment (please complete the following information):**
 - **WebdriverIO version:** ^6.1.25
 - **Node.js version:** v13.10.1
 - **NPM version:** 6.14.5
 - **Platform name and version:** iOS native app

**Describe the bug**
In my native app there are elements that are displayed slightly later (2-3 sec). Instead of using pause i tried to use waitForExist as follows:
```
leftSideBar.appName[1].waitForExist({ timeout: 5000 })
```
However when i run a test i expect it to wait for appName[1] to exist and then proceed. It is not waiting even 1 second and failing with error 
```
Cannot read property 'waitForExist' of undefined
```
For some reason it just does not wait

Console logs:
[webdriver_logs.txt](https://github.com/webdriverio/webdriverio/files/5201290/webdriver_logs.txt)

**Comment by mgrybyk** [comment]
The error is pretty straightforward, leftSideBar.appName[1] is undefined, you have to fix it in your project.
Please use gitter for this kind of question

**Comment by mgrybyk** [comment]
Closing for now, happy to answer further questions, cheers!

**Comment by Alona-T** [comment]
it is undefined because it is not yet present
i expected the method to wait for it to exist first and then proceed

**Comment by Alona-T** [comment]
@mgrybyk  or is there any other method that serves this purpose?

**Comment by christian-bromann** [comment]
@Alona-T if `leftSideBar.appName` is defined via `$$('someselector')` then of course it returns and empty string resulting in the error above. I recommend to add an additional check so that if the array is empty, run `$('someselector').waitForExist()`

**Comment by mgrybyk** [comment]
The method waits for element to exist, it can't do anything with undefined variable in your project.
$('not exist').waitForExist() works, while undefined.waitForExist() won't work.

You have to make sure leftSideBar.appName[1] is defined before calling anything on it.

**Comment by mgrybyk** [comment]
If you have upgrade to v6 Id suggest using the embedded assertion library https://github.com/webdriverio/expect-webdriverio#tobeelementsarrayofsize

expext(leftSideBar.appName).toBeElementArrayOfSize({ gte: 1})

**Comment by Alona-T** [comment]
Thank you @mgrybyk and @christian-bromann 
I will try your suggestions
