### ISSUE TITLE
Tracking doc: rewrite `@wdio/allure-reporter` package into TypeScript

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#5825]
This is a tracking issue for organising the effort of re-writing the code base from vanilla JS into TypeScript. If you are reading this and are interested getting involved, this is a great chance to do so. Here are the rules:

- if you are interested converting source files from `/packages/wdio-allure-reporter` into TypeScript please comment on this thread and mention the files you want to convert to avoid duplicate work
- there is no reason to convert the whole package at once - smaller PRs make it easier to review the code
- if you make a PR, reference this issue so we can keep track of the progress
- if you make a PR, label it with `TypeScript` and the package name `wdio-allure-reporter` so we can easier find all PRs
- if you make a PR, assign it to the `TypeScript Rewrite` project

Happy rewriting 😅

**Comment by jags14385** [comment]
I would like to pick this up , once I complete the  #5668 . I understand if , this gets assigned to someone else , by then. Just expressing my interest.

**Comment by christian-bromann** [comment]
Closing in favor of #6085
