### ISSUE TITLE
Tracking doc: rewrite `@wdio/appium-service` package into TypeScript

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#5826]
This is a tracking issue for organising the effort of re-writing the code base from vanilla JS into TypeScript. If you are reading this and are interested getting involved, this is a great chance to do so. Here are the rules:

- if you are interested converting source files from `/packages/wdio-appium-service` into TypeScript please comment on this thread and mention the files you want to convert to avoid duplicate work
- there is no reason to convert the whole package at once - smaller PRs make it easier to review the code
- if you make a PR, reference this issue so we can keep track of the progress
- if you make a PR, label it with `TypeScript` and the package name `wdio-appium-service` so we can easier find all PRs
- if you make a PR, assign it to the `TypeScript Rewrite` project

Happy rewriting 😅

**Comment by ch-t** [comment]
@christian-bromann  I'd like to take it. Should I just assign myself in Project tracker?

**Comment by christian-bromann** [comment]
@ch-t awesome, go for it!

**Comment by christian-bromann** [comment]
@ch-t how are things going. Do you need any help?

**Comment by ch-t** [comment]
thanks for reminding @christian-bromann ! 
I have done all the changes, but got distracted halfway through. Need to accomplish unit tests and create a PR.

**Comment by christian-bromann** [comment]
@ch-t how are things going? Any updates?

**Comment by ch-t** [comment]
@christian-bromann sorry, I was not able finish tests. I have created PR which rewrites package though https://github.com/webdriverio/webdriverio/pull/6149. There are some questions I'd kindly like to have addressed.  

I have got some time now so I can proceed with tests.

**Comment by christian-bromann** [comment]
Awesome! I will close this one so let's continue convo in #6149
