### ISSUE TITLE
Tracking doc: rewrite `@wdio/applitools-service` package into TypeScript

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#5827]
This is a tracking issue for organising the effort of re-writing the code base from vanilla JS into TypeScript. If you are reading this and are interested getting involved, this is a great chance to do so. Here are the rules:

- if you are interested converting source files from `/packages/wdio-applitools-service` into TypeScript please comment on this thread and mention the files you want to convert to avoid duplicate work
- there is no reason to convert the whole package at once - smaller PRs make it easier to review the code
- if you make a PR, reference this issue so we can keep track of the progress
- if you make a PR, label it with `TypeScript` and the package name `wdio-applitools-service` so we can easier find all PRs
- if you make a PR, assign it to the `TypeScript Rewrite` project

Happy rewriting 😅

**Comment by mciastek** [comment]
@christian-bromann I'm going to pick this one. Package is pretty small, so I think I can rewrite as a whole.

**Comment by christian-bromann** [comment]
@mciastek awesome! Yeah the majority of reporters and services have a decent size and can be transformed in one go. Thanks!
