### ISSUE TITLE
Tracking doc: rewrite `@wdio/browserstack-service` package into TypeScript

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#5828]
This is a tracking issue for organising the effort of re-writing the code base from vanilla JS into TypeScript. If you are reading this and are interested getting involved, this is a great chance to do so. Here are the rules:

- if you are interested converting source files from `/packages/wdio-browserstack-service` into TypeScript please comment on this thread and mention the files you want to convert to avoid duplicate work
- there is no reason to convert the whole package at once - smaller PRs make it easier to review the code
- if you make a PR, reference this issue so we can keep track of the progress
- if you make a PR, label it with `TypeScript` and the package name `wdio-browserstack-service` so we can easier find all PRs
- if you make a PR, assign it to the `TypeScript Rewrite` project

Happy rewriting 😅

**Comment by goveanick** [comment]
@christian-bromann I'll like to give this one a try.

**Comment by christian-bromann** [comment]
@goveanick how are things going? Is there anything we can help with?

**Comment by christian-bromann** [comment]
@goveanick given I haven't heard back I will un-assign you and open it up for others.

**Comment by smarigowda** [comment]
I am interested in contributing, can I get help on how do I get started ?

**Comment by christian-bromann** [comment]
@smarigowda I have assigned the ticket already to @Fabianopb (maybe there is a way to collaboratively work together on this). If you haven't done any work on the project I recommend to look into our [contribution docs](https://webdriver.io/docs/contribute.html). Please let me know if they are unclear.

**Comment by Fabianopb** [comment]
@christian-bromann as a Member should I be able to push branches directly to this repo or should I continue with a fork? I have some initial work for this one already, from where @smarigowda can probably continue.

**Comment by christian-bromann** [comment]
> or should I continue with a fork?

Please continue with your fork. Once you reached 10 qualifying PRs and become a project committer you can work on branches.

**Comment by christian-bromann** [comment]
Closing in favor of #6172
