### ISSUE TITLE
Make page objects better work in WebdriverIO

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#583]

**Comment by Sanjo** [comment]
@DominikGuzei has written https://github.com/xolvio/chimp-widgets that gives you page objects for Webdriver.io. So maybe we can merge this work into webdriverio in some form.

**Comment by christian-bromann** [comment]
hey @Sanjo , thanks for pointing out that project. I will check it out

**Comment by georgecrawford** [comment]
I'm so keen to find a good pattern for this. I can't work out how to do it without thousands of `client.addCommand` calls.

**Comment by christian-bromann** [comment]
WebdriverIO v4 now perfectly supports page objects. Check out [the docs](https://github.com/webdriverio/webdriverio/blob/master/docs/guide/testrunner/pageobjects.md) and our [example suite](https://github.com/webdriverio/webdriverio/tree/master/examples/pageobject) for more information.
