### ISSUE TITLE
Tracking doc: rewrite `@wdio/crossbrowsertesting-service` package into TypeScript

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#5832]
This is a tracking issue for organising the effort of re-writing the code base from vanilla JS into TypeScript. If you are reading this and are interested getting involved, this is a great chance to do so. Here are the rules:

- if you are interested converting source files from `/packages/wdio-crossbrowsertesting-service` into TypeScript please comment on this thread and mention the files you want to convert to avoid duplicate work
- there is no reason to convert the whole package at once - smaller PRs make it easier to review the code
- if you make a PR, reference this issue so we can keep track of the progress
- if you make a PR, label it with `TypeScript` and the package name `wdio-crossbrowsertesting-service` so we can easier find all PRs
- if you make a PR, assign it to the `TypeScript Rewrite` project

Happy rewriting 😅

**Comment by sarathps93** [comment]
Hi @christian-bromann I could see that this one is still `to-do` in the project board, I would like to contribute on this and since `@wdio/crossbrowsertesting-service` is a small package, I can raise a PR for all the files together. Is it fine?

**Comment by christian-bromann** [comment]
Awesome 👏 , go for it @sarathps93

**Comment by christian-bromann** [comment]
Any updates @sarathps93?

**Comment by sarathps93** [comment]
Sorry for the delay @christian-bromann . I have raised a pull request for the same

**Comment by christian-bromann** [comment]
Closing in favor of #6195
