### ISSUE TITLE
Tracking doc: rewrite `@wdio/junit-reporter` package into TypeScript

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#5838]
This is a tracking issue for organising the effort of re-writing the code base from vanilla JS into TypeScript. If you are reading this and are interested getting involved, this is a great chance to do so. Here are the rules:

- if you are interested converting source files from `/packages/wdio-junit-reporter` into TypeScript please comment on this thread and mention the files you want to convert to avoid duplicate work
- there is no reason to convert the whole package at once - smaller PRs make it easier to review the code
- if you make a PR, reference this issue so we can keep track of the progress
- if you make a PR, label it with `TypeScript` and the package name `wdio-junit-reporter` so we can easier find all PRs
- if you make a PR, assign it to the `TypeScript Rewrite` project

Happy rewriting 😅

**Comment by MichelAmin47** [comment]
Will pick this on up first, could you please assign me @christian-bromann

**Comment by woutdejong1986** [comment]
@christian-bromann As I will collaborate with @MichelAmin47, can you assign me too? Thanks!

**Comment by christian-bromann** [comment]
@MichelAmin47 @woutdejong1986 any updates?

**Comment by MichelAmin47** [comment]
@christian-bromann we're aiming for a draft PR next week.

**Comment by christian-bromann** [comment]
@MichelAmin47 @woutdejong1986 any updates?

**Comment by MichelAmin47** [comment]
@christian-bromann we rewrote the src files to TypeScript and the current tests passed. Currently we are rewriting the tests.

**Comment by christian-bromann** [comment]
@MichelAmin47 can you create a draft PR? Would love to provide some early feedback 😉

**Comment by MichelAmin47** [comment]
@christian-bromann of course no problem, will prep one tomorrow.

**Comment by MichelAmin47** [comment]
@christian-bromann After the rebase of the masterfork we encountered an "issue" due to code changes in the master fork (hence the PR delay):
report.d.ts in the wdio-reporter packages has been removed. We extend the Report class from the deleted file in the JunitReporter class.

I had a look at the current code base and saw the newly rewritten Allure reporter uses an  `AllureReporterOptions extends WDIOReporterBaseOptions` interface. Is this the same route we should take for the Junit reporter?

Do you still want to see our current code or should we refactor first so no deleted classes are called?

**Comment by christian-bromann** [comment]
> Is this the same route we should take for the Junit reporter?

The reporter should have a similar set up as other reporter, e.g. [`@wdio/concise-reporter`](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-concise-reporter/src/index.ts).

> Do you still want to see our current code or should we refactor first so no deleted classes are called?

Feel free to create a draft PR as soon as possible. I can wait to provide feedback until you say it is good for review.

**Comment by MichelAmin47** [comment]
@christian-bromann @woutdejong1986 We are making progress but ran into a few issues. Really want to finish this up ASAP so I booked an open office hour spot to discuss. Hoping you can give some insight on the overall code.

**Comment by christian-bromann** [comment]
@MichelAmin47 any updates? Would you mind to create a PR with the state you have? I would manually port things over as we have started to merge all v7 changes into the main branch.

**Comment by christian-bromann** [comment]
@MichelAmin47 can you please push what you have? I need to get this merged so we can make the v7 release happen.

**Comment by MichelLalmohamed** [comment]
@christian-bromann Yes, I'll create a PR. Is tomorrow midday ok?

**Comment by MichelAmin47** [comment]
@christian-bromann @woutdejong1986 opened an interim PR with our current state (cleaned up a bit). We were not able to fully integrate your feedback yet from our cal 2 weeks ago. Wout and myself would still like to finish this and rewrite the tests if you are ago with this. Hope to increase the velocity a bit with our schedules clearing up(less hectic client work) a bit in february

**Comment by MichelAmin47** [comment]
@christian-bromann build failed, will fix

**Comment by MichelAmin47** [comment]
👆 @christian-bromann @woutdejong1986 fixed, sorry about that 🙄

**Comment by christian-bromann** [comment]
Let's continue convo there.
