### ISSUE TITLE
How to test File Uploading

### ISSUE THREAD

**Issue by achandra31** [webdriverio/webdriverio#584]
Hi,
Currently, I'm creating an automation using WebDriverIO to test a file upload.
I found a hindrance when I want to type the file path and name.
I noticed that JS can't setValue on input type = "file" for security reason.
Do you know how to do that with WebDriverIO and nodeJS?
In Java, we were using autoIT to type them in the Windows Dialog box.
How can we do that in here?

Thanks,
Agus W.

**Comment by christian-bromann** [comment]
Hi Agus,

there is a command for uploading files, check out [uploadFile](http://webdriver.io/api/utility/uploadFile.html). It takes the pfad of the file you want to upload, that's it.

Let me know if that works for you.
Cheers

**Comment by achandra31** [comment]
Hi Chris,
How to upload through a button like in the attachment?
![upload file](https://cloud.githubusercontent.com/assets/12491390/8346162/d1ecca5c-1b22-11e5-88fb-7053e0b4351d.PNG)

Because I saw that the http://webdriver.io/api/utility/uploadFile.html example it didn't pass any selector.
Do you an example for this?

Thanks,
Agus W.

**Comment by achandra31** [comment]
It works for me now.

Thanks Chris.
