### ISSUE TITLE
Tracking doc: rewrite `@wdio/sauce-service` package into TypeScript

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#5843]
This is a tracking issue for organising the effort of re-writing the code base from vanilla JS into TypeScript. If you are reading this and are interested getting involved, this is a great chance to do so. Here are the rules:

- if you are interested converting source files from `/packages/wdio-sauce-service` into TypeScript please comment on this thread and mention the files you want to convert to avoid duplicate work
- there is no reason to convert the whole package at once - smaller PRs make it easier to review the code
- if you make a PR, reference this issue so we can keep track of the progress
- if you make a PR, label it with `TypeScript` and the package name `wdio-sauce-service` so we can easier find all PRs
- if you make a PR, assign it to the `TypeScript Rewrite` project

Happy rewriting 😅

**Comment by martinfrancois** [comment]
Hey @christian-bromann mind if I start working on this one?

**Comment by christian-bromann** [comment]
Assigned you already to `@wdio/sync` 😉

**Comment by martinfrancois** [comment]
@christian-bromann I just noticed that in the `README` for the sauce service, it mentions an option `noAutoconnect` for the  `sauceConnectOpts` and even though `noAutoconnect` is not in the types file or on https://github.com/bermi/sauce-connect-launcher, it is set inside `onPrepare` in `launcher.js`.

Can you please check whether `noAutoconnect` was removed (and thus should also be removed from `onPrepare` and the `README`) or if it was forgotten to be added to the types and to https://github.com/bermi/sauce-connect-launcher ?

Thanks!

**Comment by martinfrancois** [comment]
I also just noticed that `sePort` is used in `launcher.js` on `sauceConnectOpts`, but I couldn't find it either in the `README` or on the linked github repo in the comment above, can you please also check if that one still exists?

**Comment by martinfrancois** [comment]
Actually nevermind - I just found the `saucelabs` dependency already provides `SauceConnectOptions`, I'm removing the types from the package and replace them with the ones from the dependency, since they seem to be more up to date and I also don't think it makes sense to duplicate them.

**Comment by martinfrancois** [comment]
@christian-bromann in the `node-saucelabs` dependency (xxx)  `noAutodetect` in the interface `SauceConnectOptions` is defined as a `string`:
```
  /**
   * Disable the autodetection of proxy settings.
   */
  noAutodetect?: string;
```
Is this a mistake there? Since here in `launcher.js` we assign `true` (implying it's a boolean, not a string). If it is indeed a string, what should it include? Just "true" and "false"?

**Comment by christian-bromann** [comment]
Good catch, this would need to be fixed here: https://github.com/saucelabs/node-saucelabs/blob/48c9c68d2aed2530e7f3b93992beb46329e5c563/src/constants.js#L191-L192 by adding `type: 'boolean',`

**Comment by martinfrancois** [comment]
@christian-bromann thanks! I'll submit a PR.

**Comment by martinfrancois** [comment]
Done @christian-bromann : https://github.com/saucelabs/node-saucelabs/pull/97
