### ISSUE TITLE
Double-clicking doesn't work on delayed elements

### ISSUE THREAD

**Issue by koggdal** [webdriverio/webdriverio#5865]
**Environment:**
 - **WebdriverIO version:** 6.5.0
 - **Mode:** Both standalone and wdio test runner.
 - **If WDIO Testrunner, running sync/async:** I have only tried this in async mode.
 - **Node.js version:** 12.18.3
 - **NPM version:** 6.14.6
 - **Browser name and version:** Chrome 85
 - **Platform name and version:** macOS 10.15.6

**Config of WebdriverIO**
See steps to reproduce further down.

**Describe the bug**
If I get an element reference to an element that doesn't exist yet, then do `await element.waitForExist()`, and then `await element.doubleClick()`, the test fails with an error like this:

```
invalid argument
from invalid argument: 'element' is missing
  (Session info: chrome=85.0.4183.102)
```

**To Reproduce**
A reproducible test case can be found here: https://codesandbox.io/s/wdio-double-click-issue-qm3sg?file=/test/specs/delayed-elements.js

I couldn't figure out a way to have it run in there, but you can go File -> Export to ZIP and then:
1. Unzip the file somewhere
2. Navigate to the folder
3. `npm install`
4. `npm test`

And you will see one test passing (click) and one test failing (double click).

Copy of the test code to make it clearer right here:

```js
await browser.url("http://the-internet.herokuapp.com/dynamic_loading/2");
const startButton = await browser.$("#start button");
const finishTitle = await browser.$("#finish h4");
await startButton.click();
await finishTitle.waitForExist();
expect(await finishTitle.getText()).toBe("Hello World!");
await finishTitle.doubleClick(); // This causes the error
```

**Expected behavior**
Since both `await element.click()` and `await element.getText()` work, I would expect `await element.doubleClick()` to work just fine too.

**Additional context**
It seems like the element object still has an error object attached to it, even after the element starts existing (after running `await element.waitForExist()`). I wonder if this error state needs to be reset once the element becomes available?

Thanks! 🙏

**Comment by L0tso** [comment]
It happens because double click try to perform [the action](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/commands/element/doubleClick.js#L42) 
```js
{ type: 'pointerMove',  origin: this,  x: 0, y: 0 }
```  
but ```this``` doesn't contain `element-6066-11e4-a52e-4f735466cecf` property for w3c.

P.S. Same bug will be with
```js 
await finishTitle.click({})
```

**Comment by christian-bromann** [comment]
I suggest to check in the command if `this` has an `element` property and if not call `waitForExist` on it. The implementation should happen [here](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/commands/element/doubleClick.js#L24-L52) and should be accompanied by a unit test. I think this is a great little enhancement for someone who likes to contribute.

**Comment by L0tso** [comment]
I'm not sure that `waitForExist` will help in this case. `this` even after `waitForExist` won't contain the required property. Or I don't get the point.
I suggest the `element-6066-11e4-a52e-4f735466cecf` property should be setted [here](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/middlewares.js#L16).

**Comment by christian-bromann** [comment]
> I'm not sure that `waitForExist` will help in this case. `this` even after `waitForExist` won't contain the required property. Or I don't get the point.

I see what you mean. The expected behavior here should be that the middleware should help fetch the element if it doesn't exist and populate the element ids and correct properties to it so that it can continue the task of the command.

@L0tso your suggestion makes a lot of sense. Would you mind taking a stab at it?

**Comment by L0tso** [comment]
@christian-bromann https://github.com/webdriverio/webdriverio/pull/5872

**Comment by christian-bromann** [comment]
Thanks for the contribution!

**Comment by koggdal** [comment]
Thanks for the swift response and fix! 🙏 🙇
