### ISSUE TITLE
Add documentation on integrating to Bamboo

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#5866]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

We already have a page on integrating with [Jenkins](https://webdriver.io/docs/jenkins.html) and it would be amazing if we could continue this effort with other CI systems. Through a Gitter conversation I connected with @AutomationReddy who was interested writing this up.

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Description of the improvement / report**

I would suggest the following:

- add a page to our docs similar to our [Jenkins docs](https://github.com/webdriverio/webdriverio/blob/master/docs/JenkinsIntegration.md) documenting how you use Bamboo with WebdriverIO (maybe include Allure or JUnit reports)
- add the page to the [sidebar](https://github.com/webdriverio/webdriverio/blob/master/website/_sidebars.json#L41)
- images should be located [here](https://github.com/webdriverio/webdriverio/tree/master/website/static/img) and the path should be an absolute path based from our domain, e.g. `https://webdriver.io/img/jenkins/jobname.png`

@AutomationReddy thanks so much for contributing these docs, if I can help with something, please let me know. You can test the website by:

```sh
# clone repo
git clone git@github.com:webdriverio/webdriverio.git
# install dependencies
npm install
# going into the website dir
cd ./webdriverio/website
# start server
npm start
```

**Comment by AutomationReddy** [comment]
Thanks @christian-bromann for the clear cut details. I will start working on this.

**Comment by AutomationReddy** [comment]
When I do `npm start` it is throwing below error:

```
C:\Users\VinodReddy\Desktop\webdriverio\website>npm start

> @ start C:\Users\VinodReddy\Desktop\webdriverio\website
> cd .. && npm run docs:generate && cd ./website && npx run-p start:*
> webdriverio-monorepo@ docs:generate C:\Users\VinodReddy\Desktop\webdriverio
> npm run clean:website && ./scripts/docs-generation/generateDocs.js

> webdriverio-monorepo@ clean:website C:\Users\VinodReddy\Desktop\webdriverio
> rimraf docs/_*.md docs/api/_*.md docs/api/**/_*.md website/sidebars.json

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webdriverio-monorepo@ docs:generate: `npm run clean:website && ./scripts/docs-generation/generateDocs.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webdriverio-monorepo@ docs:generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\VinodReddy\AppData\Roaming\npm-cache\_logs\2020-09-15T16_41_33_836Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `cd .. && npm run docs:generate && cd ./website && npx run-p start:*`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Steps:
- Forked
- Cloned
- cd ./webdriverio
- npm i
- cd ./website
- npm i
- npm start

**Comment by christian-bromann** [comment]
@AutomationReddy I ran the exact steps that you have listed and it works on my mac machine. I just pushed a small tweak to the `package.json` which should fix this problem. Please pull the latest code and retry. Cheers!

**Comment by AutomationReddy** [comment]
I have completed the documentation. However, when I am trying to push the changes to fork, I am seeing the below error:

![image](https://user-images.githubusercontent.com/42345623/93427522-93d5a580-f8db-11ea-91a6-4dddb799599d.png)

**Comment by christian-bromann** [comment]
@AutomationReddy this is because you didn't compiled the project (which is not needed when working on the docs). So if you run:

```sh
$ npm run setup-full
```

these errors will go away. You can also just skip this check by calling:

```sh
$ git push origin bamboo_docs --no-verify
```

**Comment by AutomationReddy** [comment]
Thanks @christian-bromann. Here you go: https://github.com/webdriverio/webdriverio/pull/5871

**Comment by christian-bromann** [comment]
Thanks!
