### ISSUE TITLE
clearValue doesn't work on Chrome 85.0.1 driver 

### ISSUE THREAD

**Issue by branhuac** [webdriverio/webdriverio#5869]
**Environment (please complete the following information):**
 - **WebdriverIO version:6.5.0"** 
 - **Mode: WDIO Testrunner** 
 - **If WDIO Testrunner, running sync/async:sync** 
 - **Node.js version:12.18.3** 
 - **NPM version:6.14.7**
 - **Browser name and version:Chrome 85.0.4183.102**
 - **Platform name and version:MacOS 10.15.6**
 - **Additional wdio packages used (if applicable):@wdio/cucumber-framework, @wdio/selenium-standalone-service** 

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
clearValue function doesn't work

**To Reproduce**
Run clearValue on Chrome

**Expected behavior**
To clear the input field

> Please use the correct markdown

**Comment by christian-bromann** [comment]
> clearValue function doesn't work

@branhuac can you proof this? There are a lot of people using the command daily and don't experience this. Please provide a reproducible example.

**Comment by Achder** [comment]
There are multiple tickets concerning exactly this topic.

https://github.com/webdriverio/webdriverio/issues/5745
https://github.com/webdriverio/webdriverio/issues/5343
https://github.com/webdriverio/webdriverio/issues/5141
https://github.com/webdriverio/webdriverio/issues/4482
https://github.com/webdriverio/webdriverio/issues/4155
https://github.com/webdriverio/webdriverio/issues/1886
https://github.com/webdriverio/webdriverio/issues/1140

@christian-bromann I think you responded to all of these messages. It makes me wonder why you are asking for a proof. 
This isn't even working in something like squish IDE, which is also using webdriver/chromedriver. I have a feeling this is one of the best known flaws. There is a common workaround for this problem which is probably why it's somehow accepted (typescript version below):

```
// Helper function.
const clearAndType = async (element: WebdriverIO.Element, newValue: string) => {
  const value = await element.getValue()
  const length = value.length
  const backSpaces = new Array(length).fill('Backspace')
  await element.setValue(backSpaces)
  await element.setValue(newValue)
}
```

**Comment by christian-bromann** [comment]
@Achder I've never experienced this issue and always asked for a reproducible example that couldn't be provided. I acknowledge that this is likely a bug in Chromedriver and ideally should be addressed there. A reproducible example could help in this effort.

**Comment by Achder** [comment]
Is there an empty example project I can use for this?

**Comment by christian-bromann** [comment]
just start with a boilerplate WDIO project:
```sh
$ npm i @wdio/cli
$ npx wdio config --yes
```

**Comment by christian-bromann** [comment]
I will close this given that no reproducible example was provided. I recognise that there is a pattern for those kind of issues but as mentioned above, this is a problem in Chromedriver. If someone can suggest an alternative implementation that doesn't require to execute commands in case Chromedriver is able to do its action successfully, I am all for it.

**Comment by jedwards1211** [comment]
@christian-bromann I'm pretty sure this is in the case of React controlled inputs and `clearValue` is failing to trigger the correct change event, hence React restores the value on the input.  (I was just running some tests and saw an input flicker blank for a split second)

**Comment by christian-bromann** [comment]
A reproducible example would be helpful here. There are many things we can do on the project side to fix these React related issues but without such an example it is difficult to implement them.

**Comment by minhe86** [comment]
@christian-bromann Here is my example - here clearValue() didn't work which is text <input> element’s value.

After clearValue(), the value "Allure" is still there.
<div class="field-column col-xs-6"><input class="form-control" type="text" data-test-selector="site-details-name" value="Allure"></div>

**Comment by Tzng** [comment]
I had the same problem。

Here's my example

https://github.com/Tzng/webdriver-test

**Comment by mankeheaven** [comment]
why close this?

**Comment by CreeTar** [comment]
still an issue...

**Comment by christian-bromann** [comment]
@mankeheaven @CreeTar as mentioned above a reproducible example would be helpful.

**Comment by BorisOsipov** [comment]
@christian-bromann just react sample app from github search

```
describe('react', () => {
    it('clear value fails for react app', async () => {
        await browser.url("https://demo.rmuif.com/");
        await browser.$("span=Sign up").click();
        const input = "[type=email]";
        await browser.$(input).setValue("foobar@gmail.com")
        await browser.$(input).clearValue();
        await browser.pause(1000);
        assert.strictEqual(await browser.$(input).getValue(), "");
    });

    it('clear value works for google', async () => {
        await browser.url("https://www.google.com/");
        const input = "[name=q]";
        await browser.$(input).setValue("foobar@gmail.com")
        await browser.$(input).clearValue();
        await browser.pause(1000);
        assert.strictEqual(await browser.$(input).getValue(), "");
    });
});
```

deps
```
    "@wdio/local-runner": "^7.12.3",
    "@wdio/mocha-framework": "^7.12.3",
    "@wdio/spec-reporter": "^7.10.1",
    "chromedriver": "^92.0.2",
    "wdio-chromedriver-service": "^7.2.0"
```

Chrome Version 92.0.4515.159

**Comment by vlad-kryvokoniev** [comment]
it is still an issue... it's annoying

Have an example:

I ran a repl in Chrome 95.0.4638.69
Node v14.18.0

https://user-images.githubusercontent.com/90450449/140309335-22ff1843-4566-4920-99ed-985e5945db32.mov

**Comment by christian-bromann** [comment]
There are some parallel discussions happening, I am gonna try to consolidate them:

**Comment by christian-bromann** [comment]
The above example:

```
import assert from 'node:assert'
describe('webdriver.io page', () => {
    it('clear value fails for react app', async () => {
        await browser.url("https://demo.rmuif.com/");
        await browser.$("span=Sign up").click();
        const input = "[type=email]";
        await browser.$(input).setValue("foobar@gmail.com")
        await browser.$(input).clearValue();
        await browser.pause(1000);
        assert.strictEqual(await browser.$(input).getValue(), "");
    });

    it('clear value works for google', async () => {
        await browser.url("https://www.google.com/");
        const input = "[name=q]";
        await browser.$(input).setValue("foobar@gmail.com")
        await browser.$(input).clearValue();
        await browser.pause(1000);
        assert.strictEqual(await browser.$(input).getValue(), "");
    });
})
```
is passing for me. I am gonna close this, happy to re-open if a reproducible example can be provided.
