### ISSUE TITLE
Can webdriver.io clean itself when exceptions are thrown?

### ISSUE THREAD

**Issue by justinhelmer** [webdriverio/webdriverio#587]
I have a custom node module that spawns a webserver, spawns a selenium server, then uses mocha to run an e2e suite using your wonderful webdriver.io WebDriverJS wrapper. I'm trying to properly clean up all child processes on an error. I am able to successfully kill the webserver and selenium server, but I can see that sometimes, one or more webdriver processes are still running.

For assertions that always resolve, like `getTitle()`, the suite finishes running, and whether pass or fail, the script finishes executing and webdriver.io kills the child webdriver processes. However, for exceptions, i.e. `waitForExist()`, a `NoSuchElementError` gets thrown, and the webdriver process(es) continues to run in the background.

QUESTION 1: any chance webdriver.io can catch its own exceptions, and clean itself up? i.e.

```javascript
// kill all running webdriver processes, i.e.
// /usr/local/Cellar/phantomjs/2.0.0/bin/phantomjs --webdriver=22650 --webdriver-logfile=/....
process.on('uncaughtException', cleanup); 
```

QUESTION 2: if not, what would you recommend for an approach to cleaning up the phantom process(es)?

Any help would be greatly appreciated. I'm using 2.4.5.

**Comment by justinhelmer** [comment]
Here's an example suite for your reference:

```javascript
// @file client.js
(function () {
  'use strict';

  var _ = require('lodash');
  var webdriverio = require('webdriverio');
  var config = require('../config');

  module.exports = _.memoize(function (options) {
    options = _.defaults(options || {}, config.selenium.desiredCapabilities);

    return webdriverio.remote({
      desiredCapabilities: _.defaults(options, {
        browserName: 'phantomjs'
      })
    });
  });
})();

```

```javascript
// @file homePageSpec.js
(function () {
  'use strict';

  var client = require('../lib/client')(),
    expect = require('chai').expect,
    config = require('../config'),
    _ = require('lodash');

  describe('navigating to the home page', function () {
    this.timeout(config.mocha.timeout.suite);

    describe('for authenticated users', function () {
      before(function () {
        return client
          .init()
          .url(config.webserver.url + '/')
          .setCookie({ name: 'status', value: '%22authenticated%22' })
          .url(config.webserver.url + path);
      });

      after(function () {
        return client.end();
      });

      it('should show a logo', function () {
        return expect(client.isVisible('img[src="/images/logo.png"][alt="Logo Alt Text"]').to.eventually.be.true;
      });
    });
  });
});
})();
```

**Comment by christian-bromann** [comment]
> your wonderful webdriver.io
Thanks!

> webdriver.io WebDriverJS wrapper
1. That's not quite right. WebdriverIO is an own library that has all commands implemented and doesn't depend on selenium-webdriver
2. WebdriverIO used to be WebdriverJS (<v2) ([checkout npm](https://www.npmjs.com/package/webdriverjs)). We had to rename the library as the Selenium guys started to call their selenium-webdriver project WebdriverJS

Just wanna point that out :wink: 

> QUESTION 1: any chance webdriver.io can catch its own exceptions, and clean itself up?
No really. Afaik you can't defer the shutdown process. You have to handle that using the test framework.

> QUESTION 2: if not, what would you recommend for an approach to cleaning up the phantom process(es)?
I would recommend to have a cleanup suite at the end. You can do using the mocha.opts config:

```
test/setup.js test/spec/*.js test/teardown.js
--timeout 100000
--reporter spec
```

The setup.js is basically the same you have in client.js but wrapped in a describe/it block. The teardown.js file could look like this:

```js
describe('teardown', function() {
  it('stops the client', function(done) {
    this.client.end(done);
  })
})
```

Good news: tomorrow (Monday) `v3` will get released and it will have an own test runner so you don't need to setup all that. You just define a config file that points to your test. The testrunner will take care on creating and shutting down the instance for you.

**Comment by justinhelmer** [comment]
Thanks for the info and for the quick reply.

I'll wait to see what the runner brings in `v3`.

And say "hi" to @ChrisWren for me ;-)
