### ISSUE TITLE
Not able to run test cases on Safari , as it doesnot allow auth-pop up to pass-by. 

### ISSUE THREAD

**Issue by khyati2010** [webdriverio/webdriverio#5875]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [6.4.7]
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [v12.18.2]
 - **NPM version:** [6.14.5]
 - **Browser name and version:** [Safari]
 - **Platform name and version:** [ios]
 - **Additional wdio packages used :** [@wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
services: [
        'selenium-standalone'
    ],
    framework: 'mocha',
    baseUrl: 'https://username:password@local.test.com',

**Describe the bug**
Not able to run test cases on Safari, as it does not allow auth-pop up to pass-by. 

**To Reproduce**
For all the applications which has the auth pop up , which comes over & above the screen of the browser.
Now the browsers are removing the support for this. So while running my test cases on webdriver io I am not able to run test cases either on local not on Cross-browser supporting tools like BrowserStack.

In Safari I have made the required configurations like this

**Expected behavior**
By passing URL like this:- https://username:password@local.test.com
test cases should run

**Log**

<img width="774" alt="safari" src="https://user-images.githubusercontent.com/6421649/93568496-e7182880-f9ad-11ea-8f1e-f2c1ec39efeb.png">

**Additional context**
I checked and it seems that this way of passing username: password is deprecated and eventually safari is the first to implement this  in future chrome and firefox will phase out it too 
please refer https://tools.ietf.org/html/rfc3986

> Please use the correct markdown

**Comment by christian-bromann** [comment]
@khyati2010 thanks for filing this issue. This is unfortunately a problem with the WebDriver protocol not allowing to pass an auth prompt. Please see: https://github.com/w3c/webdriver/issues/385. It is considered to land in the next generation of this protocol.
