### ISSUE TITLE
unable to set globals in onPrepare() in wdio.conf

### ISSUE THREAD

**Issue by spatchamatla** [webdriverio/webdriverio#5884]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.5.0
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** yes
 - **Node.js version:** v12.12.0
 - **NPM version:** v6.11.3
 - **Browser name and version:** Chrome 85.0.4183.83
 - **Platform name and version:** macOS v10.15.6
 - **Additional wdio packages used (if applicable):**
```
    "@wdio/allure-reporter": "^6.4.7",
    "@wdio/cli": "^6.5.0",
    "@wdio/jasmine-framework": "^6.5.0",
    "@wdio/local-runner": "^6.5.0",
    "@wdio/selenium-standalone-service": "^6.4.7",
    "@wdio/spec-reporter": "^6.4.7",
    "@wdio/sync": "^6.5.0"
```

**Describe the bug**
unable to set globals in onPrepare() in wdio.conf. But works fine if we try to access or set globals in before().

**To Reproduce**
In wdio.conf, onPrepare(),
```
 global['testSpec1'] = 'Hi There';
```
 and in test
```
console.log(`global["testSpec1"]:\n${global["testSpec1"]}`);
```

**Expected behavior**
able to set globals in onPrepare()

**Log**
[0-0] global["testSpec1"]:
undefined

**Comment by christian-bromann** [comment]
This is impossible given that the onPrepare hook is run outside the worker thread. You can either store data in a temporary file or assign it as extra capabilities and read it via `browser.requestedCapabilities`.
