### ISSUE TITLE
option to append to wdio logs

### ISSUE THREAD

**Issue by aluo-lmi** [webdriverio/webdriverio#5885]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to append to the wdio log files instead of overwrite them.

**Describe the solution you'd like**
An option alongside `outputDir` and and `logLevel` that will cause the logs to be appended to the `wdio.log` file instead of overwriting.

**Describe alternatives you've considered**
On my side, I can create a new log file for every new webdriverio BrowserObject or create only one webdriverio BrowserObject for all tests

**Additional context**

**Comment by christian-bromann** [comment]
@aluo-lmi why can't you just store the logs in a different folder? I am not sure if it makes sense to add this special use case as a core functionality. Maybe I don't fully understand. Would you mind to provide more details?

**Comment by aluo-lmi** [comment]
Hi, yes you are right different log folders works for the general use case. Thinking again I agree this is somewhat of a special case, and maybe we can close this. I have decided to work around it in my project for now by appending the contents of the `wdio.log` file in my `outputDir` to a combined log file in the `outputDir` myself to achieve the same effect

**Comment by christian-bromann** [comment]
Sounds like a good solution. Will close this then. Thanks for bringing up the idea anyway!
