### ISSUE TITLE
Better document error handling in hooks

### ISSUE THREAD

**Issue by Achder** [webdriverio/webdriverio#5889]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2]
 - **Mode:** testrunner
 - **If WDIO Testrunner, running sync/async:** sync & async
 - **Node.js version:** 12
 - **Browser name and version:** Chrome 85
 - **Platform name and version:** Windows 10

**Describe the bug**
I was having trouble with some tests when I realized, that my onPrepare hook was throwing an error. 
The test still ran as usual but since my backend wasn't running, I was getting misleading errors.

**To Reproduce**
Add this hook to your config.

```
onPrepare: async function (config, capabilities) {
      throw new Error("error")
}

// or 

onPrepare: function (config, capabilities) {
      throw new Error("error")
}
```

**Log**

```
...
2020-09-25T10:57:13.724Z ERROR @wdio/cli:utils: Error in hook: Error: error
    at Object.onPrepare (C:\Development\anvajo datalab\test\config\wdio.conf.ts:251:13)
    at C:\Development\anvajo datalab\node_modules\@wdio\cli\build\utils.js:95:14
    at Array.map (<anonymous>)
    at runLauncherHook (C:\Development\anvajo datalab\node_modules\@wdio\cli\build\utils.js:93:27)
    at Launcher.run (C:\Development\anvajo datalab\node_modules\@wdio\cli\build\launcher.js:78:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Starting ChromeDriver 85.0.4183.87 (cd6713ebf92fa1cacc0f1a598df280093af0c5d7-refs/branch-heads/4183@{#1689}) on port 9515
...
```

**Expected behavior**
An error in onPrepare hook should abort the test.

**Comment by christian-bromann** [comment]
Please see: https://webdriver.io/docs/customservices.html

> An Error thrown during a service hook will be logged while the runner continues. If a hook in your service is critical to the setup or teardown of the test runner, the SevereServiceError exposed from the webdriverio package can be used to stop the runner.

```js
import { SevereServiceError } from 'webdriverio'

export default class CustomService { 
    async onPrepare(config, capabilities) {
        // TODO: something critical for setup before all workers launch

        throw new SevereServiceError('Something went wrong.')
    }
    
    // custom service methods ...
}
```

I think this should be better documented.

**Comment by christian-bromann** [comment]
It would be nice if we could extend the docs with an additional page `Hooks` and document all available WDIO hooks and their behavior that they don't break the test lifecycle (except when using the `SevereServiceError`).

Any help on this would be appreciated.

**Comment by Achder** [comment]
Importing SevereServiceError from webdriverio seems to interfere with sync mode.
When including from webdriverio my selectors return promises.

**Comment by christian-bromann** [comment]
it shouldn't if you explicitly set `@wdio/sync` types:
```json
    "types": [
      "node",
      "@wdio/mocha-framework",
      "@wdio/sync"
    ],
```

**Comment by Achder** [comment]
My tsconfig.json looks like this:

```
{
  "compilerOptions": {
    "target": "ES2017",
    "module": "CommonJS",
    "moduleResolution": "node",
    "noUnusedLocals": true,
    "noImplicitReturns": true,
    "inlineSources": true,
    "inlineSourceMap": true,
    "experimentalDecorators": true,
    "newLine": "lf",
    "jsx": "react",
    "esModuleInterop": true,
    "baseUrl": ".",
    "paths": {
      "@src/*": ["src/*"],
      "@main/*": ["src/main/*"],
      "@render/*": ["src/renderer/*"],
      "@reducer/*": ["src/renderer/reducer/*"],
      "@components/*": ["src/renderer/components/*"],
      "@logic/*": ["src/renderer/logic/*"],
      "@utility/*": ["src/renderer/utility/*"],
      "@lang/*": ["lang/*"]
    },
    "allowSyntheticDefaultImports": true,
    "resolveJsonModule": true,
    "types": [
      "@wdio/sync", 
      "@wdio/cucumber-framework",
      "expect-webdriverio",
      "node", 
      "wdio-image-comparison-service",
      "webpack-env"
    ],
  }
}
```

I've had this problem before with Config interface. There I could solve the issue by using WebdriverIO.Config instead of importing. But this isn't working with SevereServiceError.

**Comment by VladislavKostyukevich** [comment]
I'm also interested in this feature, any idea?

**Comment by christian-bromann** [comment]
Created a PR for this. Closing.

**Comment by christian-bromann** [comment]
FYI: the solution to use `SevereServiceError` in TypeScript and WebdriverIO sync mode is by using require to avoid type clashings.

```js
const { SevereServiceError } = require('webdriverio')
```
