### ISSUE TITLE
Xpath

### ISSUE THREAD

**Issue by Shirish2015** [webdriverio/webdriverio#589]
Hi , I am trying to use xpath to click on a particular checkbox ...its giving me an invalid selector / element not found error message ...but able to use the same path to click  using selenium web driver, java ...need help on this

**Comment by christian-bromann** [comment]
Could you send that code snippet where you use xPath?

**Comment by Shirish2015** [comment]
So i'm using the  Xpath and initializing to some variable as below.but it is not working.

var selectAll = [@id="rpt-root"]/DIV/DIV[3]/DIV[2]/DIV/DIV[4]/DIV/DIV[4]/UL/LI[1]/DIV/SVG[1]

**Comment by Shirish2015** [comment]
And also I 'm facing this issue too can you explain me this issue specifically. Thank You.

Delete Suite - 5982 ms
selects one entry delete entry - 5982 ms

Failures:

1) Delete Suite selects one entry delete entry
Message:
timeout: timed out after 5000 msec waiting for spec to complete
Stacktrace:
undefined

Finished in 5.986 seconds
1 test, 1 assertion, 1 failure, 0 skipped

-------END TEST RESULTS-------

Spec.js is

var Util = require('../../../node_modules/func-kit/test_lib/Util.js'),
   ct   = require('../../../node_modules/func-kit/test_lib/constants.js'),
   _    = require('../../../node_modules/lodash');

describe("Delete Suite", function(){

var testUrls = {
       tp: ''
     },
     getUrl = Util.pageGetter(ct.PROTOCOL, ct.HOST, 4444),  // But there are some specific tasks that these modules take care of.
     cx     = Util.setUp(process, getUrl(testUrls.tp));    

it("selects one entry delete entry", function(done){

  setTimeout(function(){
  

var selectEntry = '.rpt-edition-list-wrapper .rv-selectable-list .rpt-edition .rpt-item-indicator.rpt-item-unchecked'; // //*[@id="rpt-root"]/div/div[3]/div[2]/div/div[4]/div/div[4]/ul/li[1]/div/svg[1]
 var delete1  = '.rpt-delete';


   cx.client.waitForExist(selectEntry, ct.SELECTOR_TIMEOUT, false, function(done){
    cx.client
    .click(selectEntry)
  .click(delete1)
    client.pause(1000);

    }) 
.call(done);
},4000);

});

**Comment by christian-bromann** [comment]
> timeout: timed out after 5000 msec waiting for spec to complete

@Shirish2015 this sounds like you need to increase the default timeout. Are you using the wdio test runner or do you have your own setup?

**Comment by christian-bromann** [comment]
I guess this is fixed. Feel free to reopen if not.

**Comment by Shirish2015** [comment]
No, not yet even though i have increased the timeout also it is throwing
the same error?

On Wed, Jul 15, 2015 at 11:31 AM, Christian Bromann <
notifications@github.com> wrote:

> Closed #589 <https://github.com/webdriverio/webdriverio/issues/589>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webdriverio/webdriverio/issues/589#event-356766947>.
>



-- 
Regards,
Shirish Kumar

**Comment by christian-bromann** [comment]
The jasmine timeout need to be higher then `ct.SELECTOR_TIMEOUT`

**Comment by Shirish2015** [comment]
I will try with your suggestions  and I'm really appreciate for your
help.Thank You.

On Wed, Jul 15, 2015 at 1:21 PM, Christian Bromann <notifications@github.com
> wrote:

> The jasmine timeout need to be higher then ct.SELECTOR_TIMEOUT
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webdriverio/webdriverio/issues/589#issuecomment-121734978>
> .
>



-- 
Regards,
Shirish Kumar
