### ISSUE TITLE
Property 'cdp' does not exist on type 'BrowserObject'

### ISSUE THREAD

**Issue by rangavenu** [webdriverio/webdriverio#5890]
## 💬 Questions and Help
Hi, I'm trying to verify DOM using print emulation and I looked into using @wdio/devtools-service to set CSS media type to Print. 

Followed the instructions from 
https://www.npmjs.com/package/@wdio/devtools-service/v/5.16.16

WebdriverIO version: **5.18.7**
 running sync/async: **sync**
Node.js version: **12.18.3**
NPM version: **6.14.6**
Browser name and version: Chrome 85.0.4183.102
Platform name and version: Windows 10
Additional wdio packages used (if applicable):
**@wdio/selenium-standalone service**
**@wdio/cucumber-framework": "^5.18.6"**

We are on webdriverio 5 and are using typescript.  As mentioned above, we use cucumber and one of our step will typically set it to Emulate CSS media Type to 'Print' like

browser.cdp('Emulation', 'setEmulatedMedia', {
      media: 'print',
    });

When the browser is launched and before starting tests, I get the below error
Property 'cdp' does not exist on type 'BrowserObject' when running tests.

Any advice on this is appreciated.

Our config file looks like below.
{
  services: [ 'selenium-standalone', 'devtools' ],
  exclude: [],
  sync: true,
  maxInstances: 2,
  logLevel: 'error',
  bail: 0,
  waitforTimeout: 10000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  capabilities: [ { maxInstances: 2, browserName: 'chrome' } ],
  before: [Function: before],
  afterSession: [Function: afterSession],
  beforeFeature: [Function: beforeFeature],
  beforeScenario: [Function: beforeScenario],
  afterStep: [Function: afterStep],
  afterScenario: [Function: afterScenario],
  afterFeature: [Function: afterFeature],
  batchName: '',
  specs: [ './features/functional/**/Print View.feature' ],
  framework: 'cucumber',
  cucumberOpts: {
    backtrace: true,
    requireModule: [ 'tsconfig-paths/register', [Function] ],
    failAmbiguousDefinitions: true,
    failFast: false,
    format: [ 'pretty' ],
    colors: true,
    ignoreUndefinedDefinitions: false,
    source: true,
    profile: [],
    require: [ './stepDefinitions/**/*.ts', './helpers/**/*.ts' ],
    snippets: undefined,
    strict: true,
    tagExpression: 'not @weekly and not @iffy and (not @exclude-chrome and (not @ignore))',
    tagsInTitle: false,
    timeout: 30000,
    dryRun: false
  },
  reporters: [ [ 'allure', [Object] ], [ 'junit', [Object] ] ],
  addTagExpression: [Function: addTagExpression],
  browserName: 'chrome',
  deprecationWarnings: false,
  planLogoUrl: 'eb2uiMock/images/aries.png',
  screenshotPath: './allure-results/',
  setReportOutputDir: [Function: setReportOutputDir],
  suites: {
    visual: [ './features/visual/**/*.feature' ],
    singleThread: [ './features/functional/Search Page/Loading Panel.feature' ]
  },
  wiremock: { <url> },
  onPrepare: [AsyncFunction: onPrepare],
  onComplete: [AsyncFunction: onComplete],
  resetMock: [AsyncFunction: resetMock],
  log: [Function: log],
  isRunCrossBrowser: false,
  baseUrl: '<url>',
  ebSearchUrl: '{user}/{plan}',
  ebSearchForbiddenUrl: '<url>',
  ebSearchTimeoutUrl: '<url>',
  ebPortalTriggerUrl: '<url>',
  errorUrl: '<url>',
  planManagementServiceUrl: '<url>',
  signInUrl: '<url>',
  rootUrl: '<url>'
}

**Comment by christian-bromann** [comment]
You need to add `@wdio/devtools-service` to your tsconfig. Please see the [typescript docs](https://webdriver.io/docs/typescript.html).

**Comment by rangavenu** [comment]
Sorry missed out on mentioning. I did try adding it to my tsconfig and still face the same issue. Below are the contents of my tsconfig

{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "allowJs": true,
    "module": "commonjs",
    "types": [
      "@wdio/sync",
      "chai",
      "mocha",
      "@wdio/devtools-service",
    ]
  },
  "include": [
    "tests/**/*.ts"
  ]
}

**Comment by christian-bromann** [comment]
> WebdriverIO version: **5.18.7**

You are using an outdated version. I recommend to update.

**Comment by baishalighosh** [comment]
> You need to add `@wdio/devtools-service` to your tsconfig. Please see the [typescript docs](https://webdriver.io/docs/typescript.html).

This worked for me too. Thanks
