### ISSUE TITLE
Documentation for Webdriverio to run different browsers(Opera, Microsoft Edge etc)

### ISSUE THREAD

**Issue by faizaaslam1** [webdriverio/webdriverio#5898]
**Pre-check**
- [ ] I'm aware that I can edit the docs and submit a pull request

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

A clear and concise description.
there should also be a documentation on how to run different browsers(Opera, Microsoft Edge, Safari) in webdriverio as it gets very confusing for the freshers who are trying to learn and work with webdriverio.
i have set capabilities for microsoft edge
 { 
browserName: 'MicrosoftEdge'
}
`services: [
        ['selenium-standalone', {
            logPath: 'logs',
            installArgs: {
                drivers: {
                  //  chrome: { version: '85.0.4183.83' },
                     edge: { version: '80.0.600.0' }
                }
            },
            args: {
                drivers: {
                   // chrome: { version: '85.0.4183.83' },
                    edge: { version: '80.0.600.0' }
                }
            },
        }]
    ],
`
but its not working.
I keep on receiving error:
Failed to create session. 
Unable to connect to local http://127.0.0.1:4444/wd/hub make sure browser driver is running on that address.

**Comment by christian-bromann** [comment]
Yeah I think it doesn't hurt to have more detailed documentation on each of them. Any support on this would be highly appreciated, thanks!

**Comment by AutomationReddy** [comment]
@christian-bromann I will take this up. Will discuss more on the Office hours on this as well.

**Comment by AutomationReddy** [comment]
@faizaaslam1 Please try as below

Install 2 packages `wdio-edgedriver-service (for legacy edge)`
`npm i -D msedgedriver --edgechromiumdriver_version=<VERSION> for edge chromium`

Add `edgedriver `in services and `browserName `as `MicrosoftEdge`

I haven't tried with selenium-standalone. But the above worked for me. I am using Edge Chromium V85.X

**Comment by mgrybyk** [comment]
Let's document how to use all them with selenium-standalone as well.
It should be really easy for IE11, firefox, safari and chromium based drivers (chrome, edge, etc).

One guy I'd omit as a hell is legacy edge. It's extremely problematic, delends on windows version, there is no fully working version. And it's deprecated.

**Comment by mgrybyk** [comment]
@AutomationReddy @faizaaslam1 Edge should work with selenium-standalone once https://github.com/webdriverio/webdriverio/pull/5956 is merged

**Comment by christian-bromann** [comment]
@AutomationReddy any updates? Happy to support in any way if needed.

**Comment by christian-bromann** [comment]
Seems that #5956 is merged. I will close. Happy to re-open if this still seem to be an issue.
