### ISSUE TITLE
ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'testRailsOptions' of undefined

### ISSUE THREAD

**Issue by payalsood** [webdriverio/webdriverio#5899]
I am getting ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'testRailsOptions' of undefined.

 I used wdio test-rail reporter. Can this be resolved please? Is this a bug?

**Comment by christian-bromann** [comment]
> I used wdio test-rail reporter.

Please file a bug in the test-rail reporter project, thanks!

**Comment by QA-Fusemachines** [comment]
Is this issue resolved

**Comment by leoshane13** [comment]
May I know where can I find test-rail reporter project, I met the same issue, thanks

**Comment by christian-bromann** [comment]
> May I know where can I find test-rail reporter project?I met the same issue, thanks

https://github.com/oxynade/wdio-testrail-reporter
