### ISSUE TITLE
set default loggingPrefs for chrome

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#590]
Getting the log buffer in chrome is only possible if you set the right capabilities:

```js
capabilities.loggingPrefs = { "driver": "INFO", "browser": "INFO" }
```

It is useful to set this as default value if browserName is Chrome.
(see also #491)

**Comment by spatchamatla** [comment]
can we also get the browser debug logs as well with the above, when we set **"browser": "DEBUG"?**

**Comment by christian-bromann** [comment]
You mean everything that gets printed via `console.debug`?

**Comment by spatchamatla** [comment]
yes

**Comment by christian-bromann** [comment]
not sure, try it out :wink:

**Comment by spatchamatla** [comment]
got it, i thought, if we can allow which type of logs can be captured using capabilities.loggingPrefs, will be a great addition.

**Comment by christian-bromann** [comment]
well you can enable it in your capabilities already now:

```js
var webdriverio = require('webdriverio');
var client = webdriverio.remote({
    desiredCapabilities: {
        browserName: 'chrome',
        loggingPrefs: { "driver": "INFO", "browser": "INFO" }
    }
});
```
This issue is more about setting those loggingPrefs as default value to make the log command work in chrome.

**Comment by spatchamatla** [comment]
Got it

**Comment by toddhgardner** [comment]
The Selendroid driver that Saucelabs is currently using doesn't appear to support any loggingPrefs being passed. Even with an empty object, it generates this error:

```
io.selendroid.server.model.SelendroidStandaloneDriver createNewTestSession
SEVERE: Error occurred while starting Selendroid session
java.lang.ClassCastException: org.json.JSONObject cannot be cast to org.openqa.selenium.logging.LoggingPreferences
```

Unfortunately, with this change there is no way (AFAIK) to exclude loggingPrefs from being sent, since the deepMerge is smashing the object back onto capabilities. I need a way to exclude it intentionally. Suggestions?

**Comment by christian-bromann** [comment]
@toddhgardner have you tried to pass an empty string or a boolean?

**Comment by toddhgardner** [comment]
@christian-bromann yes, and webdriver.io indeed passes emptystring or false through, neither of which can be case to the LoggingPreferences object. It appears I need a way to intentionally pass nothing.

**Comment by christian-bromann** [comment]
ok, I created an issue (#684) and gonna fix that :wink:

**Comment by toddhgardner** [comment]
Thanks @christian-bromann, if you have an idea for how you would like this done, I would be happy to submit the PR myself. Can this be as simple as checking for `false` in loggingPrefs and excluding it from the deepMerge?

**Comment by christian-bromann** [comment]
> Can this be as simple as checking for false in loggingPrefs and excluding it from the deepMerge?

yeah, just ignore deepmerge for the `loggingPrefs` property and add a little command why that. Thanks!
