### ISSUE TITLE
high severity vulnerability in @wdio/devtools-service package

### ISSUE THREAD

**Issue by FelixZilber** [webdriverio/webdriverio#5907]
@wdio/devtools-service version 6.5.2 has high severity vulnerability

path of package with vulnerability: 
@wdio/devtools-service > lighthouse > jsonld > rdf-canonize  > node-forge
the patch in node-forge version >= 0.10.0

**Comment by christian-bromann** [comment]
@FelixZilber thanks for reporting the issue. Do you know if this has been fixed in one of the upstream dependencies?

**Comment by FelixZilber** [comment]
@christian-bromann I found next dependency tree:
 wdio/devtools-service
    =>   "lighthouse": "^6.3.0",
        =>"jsonld": "^1.5.0",
            =>"rdf-canonize": "^1.0.2",
                => "node-forge": "^0.9.1"
looks like upsteam dependencies don't include a fix(unless I missed something)

**Comment by christian-bromann** [comment]
Seems that the vulnerability fix is in node-forge version >= 0.10.0. Given that the dependency tree uses `^` for all the dependencies this should be resolved. Users just need to reinstall their dependencies to get the security fix. Closing unless I am overseeing something.

**Comment by FelixZilber** [comment]
deleting package-lock.json and reinstall solved the issue for me
