### ISSUE TITLE
How does execute works.

### ISSUE THREAD

**Issue by Naixor** [webdriverio/webdriverio#591]
I want to rewrite the method selectorExecute to make it support RegExp. But I don't know how does execute works. 
```JavaScript
this.requestHandler.create(
        '/session/:sessionId/execute',
        {script: script, args: args},
        callback
    );
```
What happened in browsers?

**Comment by christian-bromann** [comment]
You want to enable selector with regexp? How should that work?

**Comment by Naixor** [comment]
Just like this: `//div[id=wrapper]/div[nth-child=-1,class=div]/div[id=head_wrapper]/p/img[src=/[\s\S]+/g]`.
A grammar close to Xpath. 
`//` === `/body`.
`nth-child` is supported too.
I am working for this now.

**Comment by christian-bromann** [comment]
Cool, feel free to do a PR. I guess we can close that then.
