### ISSUE TITLE
Unable to run Puppeteer from latest Webdriver.io v6.5.2

### ISSUE THREAD

**Issue by jamieni** [webdriverio/webdriverio#5915]
Reopening issue #5697 on Webdriver.io v6.5.2

I used the same example here: https://github.com/webdriverio/webdriverio/blob/master/examples/devtools/intercept.js
and received this error: `puppeteerBrowser.pages() is not a function`

**Comment by pmerwin** [comment]
I am getting this with the latest:

2020-10-03T19:31:53.810Z ERROR @wdio/utils:initialiseServices: Error: Couldn't initialise "@wdio/devtools-service".
TypeError: Cannot read property 'requestLatencyMs' of undefined

**Comment by mgrybyk** [comment]
@jamieni please change https://github.com/webdriverio/webdriverio/blob/3867103c9c5af0c83ee933b0c75ae8d9af0c73e4/examples/devtools/intercept.js#L8 to `const { remote } = require('webdriverio');`

I'll update the example
