### ISSUE TITLE
Starting firefox on MacOS takes much time in binary is not specified

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#5916]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.5.0
 - **Platform name and version:** MacOS
 - **Additional wdio packages used (if applicable):** devtools

**Config of WebdriverIO**
```js
automationProtocol: 'devtools',
    capabilities: [
        {
            browserName: 'firefox',
        },
    ],
```

**Describe the bug**
it takes more than 5 seconds for finder to find Firefox binary every time 

**To Reproduce**
1. run tests in firefox
2. wait for tests to start

**Expected behavior**
less than a second for sure, ideally less than 100 ms

**Comment by christian-bromann** [comment]
The optimisation should happen in the [firefox finder](https://github.com/webdriverio/webdriverio/blob/master/packages/devtools/src/finder/firefox.js) in the devtools package. It seems that the command for checking the app register takes a long time. In fact I optimized this for Chrome in the [chrome-launcher](https://github.com/GoogleChrome/chrome-launcher/pull/209) package. A similar change needs to happen in the finder as well.

**Comment by joventuraz** [comment]
Coincidentally, I've been trying to run e2e tests and have had problems locating the firefox binary, looks like we are looking specifically for a nightly install? Anyways, during my debugging I found this command to take a while: https://github.com/webdriverio/webdriverio/blob/master/packages/devtools/src/finder/firefox.js#L27-L31 I think this might be related to the issue.

**Comment by mgrybyk** [comment]
@joventuraz  correct for devtools protocol
