### ISSUE TITLE
Running with PhantomJS Ghostdriver directly no longer works in 3.0.0

### ISSUE THREAD

**Issue by Sanjo** [webdriverio/webdriverio#594]
Reproduce: https://github.com/Sanjo/phantomjs-webdriver-v3-issue

This works with 2.4.5. If you start the Selenium server additionally, it works. Is this something that you can fix?

**Comment by christian-bromann** [comment]
@Sanjo not reproducible with phantomjs `v2`. Seems to be related to ariya/phantomjs#11421. I don't think it is an error in WebdriverIO since it got introduced due to an update of the request module.

**Comment by Sanjo** [comment]
I've created a pull-request to fix this issue with PhantomJS 1.9. For chimp and meteor-cucumber we cannot yet upgrade to PhantomJS 2 because it seems that there is still no cross-platform build available.
