### ISSUE TITLE
Enable a mechanism for manually failing the test run (via service/reporter/config hooks)

### ISSUE THREAD

**Issue by StephenEsser** [webdriverio/webdriverio#5942]
# Description

Provide a mechanism to manually fail the test run.

We're developing a service/reporter concept that collects data during the test run and evaluates it after testing has completed. Following the evaluation of the data collection we're looking for a mechanism for pass/failing the test run.

## Potential Solutions:

1. Enable the hooks (or a new hook) to return an exit code.
2. Allow and honor assertions in the after/tear down hooks.
3. Fail the test run if an error is thrown from within the after/tear down hooks.

## Additional Details

The solution provided [here](https://github.com/webdriverio/webdriverio/issues/2843) does not appear to work as intended. It does fail the test run, but as a result of an error that the solution appears to result in. A concrete/supported mechanism to pass/fail the test run is desirable.

https://github.com/webdriverio/webdriverio/issues/2843

```
------------------------------------------------------------------
[chrome 83.0.4103.61 linux #0-0] Spec: /Users/user-name/Github/terra/terra-toolkit/packages/terra-functional-testing/tests/wdio/temp-spec.js
[chrome 83.0.4103.61 linux #0-0] Running: chrome (v83.0.4103.61) on linux
[chrome 83.0.4103.61 linux #0-0] Session ID: 7781e9cb66bce22d9761e72ca2816fb4
[chrome 83.0.4103.61 linux #0-0]
[chrome 83.0.4103.61 linux #0-0] Axe
[chrome 83.0.4103.61 linux #0-0]    ✖ should report a color contrast violation
[chrome 83.0.4103.61 linux #0-0]
[chrome 83.0.4103.61 linux #0-0] 2 failing (916ms)
[chrome 83.0.4103.61 linux #0-0]
[chrome 83.0.4103.61 linux #0-0] 1) Axe should report a color contrast violation
[chrome 83.0.4103.61 linux #0-0] done() called multiple times in test <Axe should report a color contrast violation> of file /Users/user-name/Github/terra/terra-toolkit/packages/terra-functional-testing/tests/wdio/temp-spec.js
[chrome 83.0.4103.61 linux #0-0] Error: done() called multiple times in test <Axe should report a color contrast violation> of file /Users/user-name/Github/terra/terra-toolkit/packages/terra-functional-testing/tests/wdio/temp-spec.js
[chrome 83.0.4103.61 linux #0-0]     at createMultipleDoneError (/Users/user-name/Github/terra/terra-toolkit/node_modules/mocha/lib/errors.js:294:13)
[chrome 83.0.4103.61 linux #0-0]     at multiple (/Users/user-name/Github/terra/terra-toolkit/node_modules/mocha/lib/runnable.js:282:24)
[chrome 83.0.4103.61 linux #0-0]     at done (/Users/user-name/Github/terra/terra-toolkit/node_modules/mocha/lib/runnable.js:293:14)
[chrome 83.0.4103.61 linux #0-0]     at /Users/user-name/Github/terra/terra-toolkit/node_modules/mocha/lib/runnable.js:363:11
[chrome 83.0.4103.61 linux #0-0]     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by christian-bromann** [comment]
> We're developing a service/reporter concept that collects data during the test run and evaluates it after testing has completed.

Can you describe this a bit more. Hooks have been designed to not interfere with the test process. Our current recommended way is to have a test at the end of all that allows to make an assertion.

**Comment by StephenEsser** [comment]
We're developing global utility functions that capture information as the test runs. (Accessibility checking and screenshots)

An example:

```js
  it('should walk through an example test', () => {
    browser.url('/example-url.html');

    // Test steps
    // .
    // .
    // .

    Terra.report.accessibility(); // Analyze the current webpage using axe-core and store that information.
    Terra.report.screenshot() // Take a screenshot and store that information.

    // Additional test steps/assertions
    // .
    // .
    // .
  });
```

We don't want these utility functions to run assertions inline because once an assertion fails it will bail out and skip any test steps/assertions that happen after. We want to capture this information without interfering with other test steps/assertions. After the test run completes we want to analyze this information and pass/fail the build based on certain criteria. 

>  Our current recommended way is to have a test at the end of all that allows to make an assertion.

Do you have an example of setting up a test that is guaranteed to run after all other tests, files, and suites have completed?

**Comment by christian-bromann** [comment]
@StephenEsser we currently allow service to fail in `onPrepare` and `onComplete` using the `SevereServiceError` that was implemented in #5565. You can collect errors in a log file or wherever and use the onComplete hook in your service to check for these errors. If there are any you can make the process fail by throwing a `SevereServiceError` in that hook function.

I think this is essentially what you are describing. What is not possible is to have the test stop / bail early (the work around would be to have an assertion).

Please let me know if this would work for you. Happy to discuss opportunity to better integrate your tool with WebdriverIO. Will close this as it seems that the framework can provide the functionality you are asking for.

**Comment by rafz12** [comment]
@christian-bromann The work around to have an assertion does not work; when someone intends to use assertion almost everywhere in test; the fact is a simple page transitions failure should exit out the whole describe block or move on to next set of tests. I shouldn't have to end the whole test just because of negative expect validation.

**Comment by rafz12** [comment]
What is the solution for: when a single IT block fails or a method inside IT block fails how do I force fail all the remaining IT blocks inside the describe block and move to next test? (for webdriverIO+jasmine) 
Bail options didn't work
failI() call back did not work
done() call also did not work.

**Comment by christian-bromann** [comment]
Please check the [Jasmine docs](https://jasmine.github.io/api/edge/Configuration), particularly `stopOnSpecFailure`
