### ISSUE TITLE
wdio cli install report/service - typed configuration support

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#5944]
**Is your feature request related to a problem? Please describe.**
As a TypeScript user, I want to use `npx wdio install ...` to add reporter/service to my wdio.conf.ts

**Describe the solution you'd like**
`npx wdio config/wdio.conf.ts install reporter allure`

**Describe alternatives you've considered**
Ideally, I'd like `npx wdio` to find my `wdio.conf.ts` somehow but I don't have a solution for that.

**Additional context**
Assuming that we are switching to TypeScript more and more we should focus on improving its support in cli module as well.

**Comment by mgrybyk** [comment]
I believe this one should be implemented once https://github.com/webdriverio/webdriverio/issues/5945 is done

**Comment by christian-bromann** [comment]
Let's continue convo in #6699
