### ISSUE TITLE
wdio cli - Typed Config support

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#5945]
**Is your feature request related to a problem? Please describe.**
As a TypeScript user, I want wdio cli to:
- create a typed config for me
- add typescript to dev dependencies if it's not there
- create tsconfig file, if it's missing
- ask me to set up eslint

**Describe the solution you'd like**
any solution to achieve the request

**Comment by christian-bromann** [comment]
Please also see #5959 what needs to be supported.

**Comment by christian-bromann** [comment]
Implemented in #6275
