### ISSUE TITLE
Fix unit tests in Windows

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#5950]
Currently our unit tests are broken in Windows. It would be great if someone with a Windows machine could take a look at them. The list of errors can be found here:

https://github.com/webdriverio/webdriverio/pull/5947/checks?check_run_id=1220246069

Also in case #5947 got merged until then I would be great if the unit tests could be enabled again in `.github/workflows/test.yml`

**Comment by logesr** [comment]
I can take it up!

**Comment by mgrybyk** [comment]
@logesr on it as well, have you started?

**Comment by mgrybyk** [comment]
@logesr feel free to pick up my branch and proceed https://github.com/webdriverio/webdriverio/compare/fix-unit-tests-win

Cheers!

**Comment by logesr** [comment]
Thanks @mgrybyk

**Comment by logesr** [comment]
@christian-bromann @mgrybyk  I am facing an issue while setting up my windows machine. The below error is thrown at times resulting in failure of builds.

──────────────────────────────────────────────┐
│                     npm update check failed                     │
│               Try running with sudo or get access               │
│              to the local update config store via               │
│ sudo chown -R $USER:$(id -gn $USER) C:\Users\Logeswaran\.config


I have tried reinstalling the node & npm. No luck. Any thoughts on this?

**Comment by mgrybyk** [comment]
Nope, it works for me out out the box.
I just installed npm on my Windows machine and that's it
