### ISSUE TITLE
updated port in wdio config is not being set in wdio runner in latest v6.*.*

### ISSUE THREAD

**Issue by spatchamatla** [webdriverio/webdriverio#5952]
WebdriverIO version: 6.6.0
Mode: WDIO Testrunner
If WDIO Testrunner, running sync/async: async
Node.js version: v12.12.0
NPM version: v6.11.3
Browser name and version: Chrome 85.0.4183.83
Platform name and version: macOS v10.15.6

**Config of WebdriverIO**
```
exports.config = {
  runner: 'local',
  path: '/wd/hub',
  baseUrl: 'http://localhost',
  services: ['selenium-standalone'],
  port: 7777,
  seleniumArgs: {
    seleniumArgs: ["-port", "7777"],
  },
}

```

**Describe the bug**
port set in wdio config is not being set for WebdriverIO session.

Note: This is working in 
```
 "@wdio/allure-reporter": "^5.22.4",
  "@wdio/cli": "^5.23.0",
```

**To Reproduce**
with above config, run wdio and you see in ```wdio-0-0.log```
```
2020-10-07T22:18:02.545Z INFO @wdio/local-runner: Run worker command: run
2020-10-07T22:18:02.551Z INFO webdriverio: Initiate new session using the ./protocol-stub protocol
2020-10-07T22:18:03.248Z INFO webdriverio: Initiate new session using the webdriver protocol
2020-10-07T22:18:03.250Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
```

it defaults to port ```4444```

**Expected behavior**
WebdriverIO session to be initiated on ```http://localhost:7777/wd/hub/session```

**Comment by christian-bromann** [comment]
Couple of things:

1. You are using the selenium standalone server which overwrites the `port` option as it should
2. you misconfigured `seleniumArgs`, please see a working example in the [service docs](https://webdriver.io/docs/selenium-standalone-service.html#custom-configurations)
