### ISSUE TITLE
Clean up TypeScript set up

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#5955]
Since https://github.com/webdriverio/webdriverio/pull/5853 `webdriver.d.ts` is no longer generated automatically.

Let's have `webdriver.d.ts` types autogenerated

**Comment by christian-bromann** [comment]
I will broaden this scope as we have rewritten all packages we can take a re-stab at how our typings are implemented. This is a work in progress PR.

**Comment by christian-bromann** [comment]
Tackled in #6302
