### ISSUE TITLE
Add the ability to customize the name of the before hook that shows up in the allure report because it takes the name of the first test by default

### ISSUE THREAD

**Issue by jamesmortensen** [webdriverio/webdriverio#5973]
**Is your feature request related to a problem? Please describe.**
We use before hooks to setup all of our tests and make sure we're on the right page before we start executing a series of negative test cases, but in the report, the before hook takes on the name of the first test when instead we feel it should take on the name of the entire suite.

<img width="679" alt="Screen Shot 2020-10-12 at 2 23 54 PM" src="https://user-images.githubusercontent.com/1315816/95727218-84a60580-0c97-11eb-8dc0-057cf41daf11.png">

As you can see, the before test has the same name, in quotes, as the first actual test in the sequence (test number 2) even though the "before" is for all tests in the suite.

Mocha has the ability to pass a title to before hooks, but wdio/allure-reporter seems to ignore them.

**Describe the solution you'd like**
I can't imagine that this is the behavior most people would want, but since I'm not in their shoes, we have to assume changing the default behavior could break stuff.  It would be great to be able to pass in a custom title to before and then have that appear in the report instead.

```
before('before hook with custom title, () => {
    // do the before stuff here
);

it('should ...', () => {
   // test 1
});

it('should ...', () => {
   //test 2 and so forth
....
```

**Describe alternatives you've considered**

I have tried hacking the test titles via the currentTest and this.test JavaScript objects, which are accessible in the before block, however, changing the values doesn't seem to affect the report.

Another alternative is to disable the before and after hook reporting, but that won't help us if there is a problem in the before/after hooks.

**Comment by christian-bromann** [comment]
Hey,
thanks for filing the issue. This seems indeed like something we should improve. The `beforeAll` hook should contain the suite title rather than the title of the first test. We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by sarathps93** [comment]
@christian-bromann Is it ok I work on this?

**Comment by christian-bromann** [comment]
@sarathps93 that would be awesome!

**Comment by sarathps93** [comment]
Thanks @christian-bromann . Just for a head start, do you think the fix would be somewhere in the `wdio-allure-reporter` package and could it be somewhere at the framework level such as in `wdio-mocha-framework` or `wdio-jasmie-framework`?

**Comment by christian-bromann** [comment]
I haven't looked into this issue, so can't really tell.

**Comment by sarathps93** [comment]
@christian-bromann @jamesmortensen I have raised a PR with a fix. Now the mocha before all & after all hooks will take the name of the suite instead of the first test

**Comment by christian-bromann** [comment]
Let's continue convo in #6108
