### ISSUE TITLE
Steps are being displayed as tests

### ISSUE THREAD

**Issue by mareru** [webdriverio/webdriverio#5983]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.5.2
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v12.18.3
 - **NPM version:** 6.14.8
 - **Browser name and version:** Chrome 86
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/spec-reporter, @wdio/selenium-standalone service, @wdio/cucumber-framework, @wdio/cli, @wdio/local-runner, @wdio/sync

**Describe the bug**
The report is displaying every step as a "test", this creates confusion as there can be displayed 40 tests, when there are actually only 9 cucumber Scenarios.

**Expected behavior**
I would expect that the report displays on the graphs the cucumber "Scenarios" that failed/passed/broken instead of each separate step definition.

**Additional context**
I have found similar issue but for cucumberjvm which got resolved there [allure-cucumberjvm](https://github.com/allure-framework/allure-cucumberjvm/issues/21). Maybe it could serve as an inspiration to do the same here.

**Comment by christian-bromann** [comment]
@mareru for better understanding would you mind sharing a Allure report displaying the current state and one with the state you are looking for?

**Comment by mareru** [comment]
Here is a screenshot with my comments of the [report dashboard](https://monosnap.com/file/o9pL98Ed9tIFyTUFzjBOuCnARBiByq).
Here is a screenshot with my comments of the [graphs](https://monosnap.com/file/jrnucdNpQBXxn5odR76dIiy8TvcsES).
I hope this makes it clearer. Let me know if you have any questions. 
Thanks!

**Comment by BorisOsipov** [comment]
@mareru have you tried `useCucumberStepReporter` wdio-allure-reporter option?
see https://webdriver.io/docs/allure-reporter.html for details.

**Comment by mareru** [comment]
@BorisOsipov 
Thank you so much. That worked just the way I expected. 
I had it before but because of some other try and errors session I turned it off.
Sorry for the inconvenience, I'll close it.
