### ISSUE TITLE
Shared-store not working when running tests on sauce labs

### ISSUE THREAD

**Issue by kamalgirdher-rally** [webdriverio/webdriverio#5986]
**Environment :**
  WebdriverIO version: wdio/cli : ^6.1.24
  Mode: WDIO Testrunner
  If WDIO Testrunner, running sync/async: sync
  Node.js version: 11.3.0
  NPM version: 6.4.1
  Browser name and version: chorme 85.0.4183.83
  Platform name and version: MacOS Catalina 10.15.4
  Additional wdio packages used (if applicable): @wdio/allure-reporter(6.1.23), @wdio/cli(6.1.24), @wdio/dot-reporter(6.1.23), @wdio/jasmine-framework(6.1.23), @wdio/local-runner(6.1.24), @wdio/sauce-service(6.1.16), @wdio/selenium-standalone-service(6.1.14), @wdio/shared-store-service(6.4.7), @wdio/spec-reporter(6.1.23), @wdio/sync(6.1.14), sauce-connect-launcher(^1.3.2)

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
While setting up my tests to run on sauce-labs, I found that it gives error while setting and getting variables in shared-store.

**To Reproduce**
Run the test on sauce labs and try to set or get a variable in/from shared-store.

```
  describe('test', () => {
    it('test', () => {
      browser.sharedStore.set('name','kamal')
     });
  });
```

**Expected behaviour**
Test should run fine and set name in shared store.

**Log**
`TypeError: Cannot read property 'set' of undefined`

**Additional context**
All my tests work absolutely fine locally and on docker containers. Also, all the tests which do not use shared-store are working fine on sauce labs.

**Comment by christian-bromann** [comment]
@kamalgirdher-rally the shared store service doesn't care whether it is run locally or on a vendor platform. Please check if you have installed all dependencies properly. Look into the logs to see if the service might not be installed correctly.

Closing as this seems to be a user error. Happy to assist with further questions.

**Comment by kamalgirdher-rally** [comment]
yes. you're right. This was issue at my end only. Got it working now. Thanks!
