### ISSUE TITLE
SauceLabs dashboard displays test as failed when it has passed on retry

### ISSUE THREAD

**Issue by jiyoon-sb** [webdriverio/webdriverio#5989]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.6.2
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.13.0
 - **NPM version:** 6.12.0
 - **Browser name and version:** N/A
 - **Platform name and version:** N/A
 - **Additional wdio packages used (if applicable):** @wdio/cli, @wdio/dot-reporter, @wdio/junit-reporter, @wdio/local-runner, @wdio/mocha-framework, @wdio/reporter, @wdio/sauce-service, @wdio/selenium-standalone-service, @wdio/spec-reporter, @wdio/sync

**Config of WebdriverIO**
```
'use strict';
 
const chai = require('chai');
 
global.assert = chai.assert;
global.chai = chai;
chai.Should();
 
exports.config = {
  user: process.env.SAUCE_USERNAME,
  key: process.env.SAUCE_ACCESS_KEY,
  region: 'us-west-1',
 
  maxInstances: 1,
  capabilities: [
      {
        browserName: 'chrome',
        platformName: 'Windows 10',
        browserVersion: '83.0',
        'sauce:options': {
          parentTunnel: '<insert tunnel name>',
          public: 'team',
          screenResolution: '1280x960',
          tunnelIdentifier: 'Primary',
          extendedDebugging: true,
        }
      }
  ],
  execArgv: [],
  sync: true,
  logLevel: 'trace',
  coloredLogs: true,
  deprecationWarnings: true,
  bail: 0,
  screenshotPath: 'screenshots',
  baseUrl: '',
  outputDir: './wdio-log',
  waitforTimeout: 60000,
  connectionRetryTimeout: 120000,
  connectionRetryCount: 3,
  services: [
    [
      'sauce',
      {
        sauceConnect: true,
        sauceConnectOpts: {
          parentTunnel: '<insert tunnel name here>',
          tunnelIdentifier: 'Primary',
        },
      },
    ],
  ],
  framework: 'mocha',
  reporters: [
    [
      'junit',
      {
        outputDir: './reports/',
        outputFileFormat: function (opts) {
          return `results-${opts.cid}.${opts.capabilities.browserName}-v${opts.capabilities.browserVersion}.xml`;
        },
      },
    ],
  ],
 
  mochaOpts: {
    retries: 2,
    timeout: 0,
   ui: 'bdd',
  }
};
```

**Describe the bug**
wdio config has been set so that a test will retry upon a failure.  When a test passes on a retry, SauceLabs dashboard still indicates the test as failed even though it has passed.

**To Reproduce**
1. Set up wdio configuration to allow for retries.
2. Set up a test to fail and then pass on a retry.
3. Login to SauceLabs and observe the test status.

```
'use strict';
 
describe(`custom-test`, function () {
  let tries = 0;

  it(`passes`, function () {
    console.log('Starting test.');
 
    if (tries < 1) {
      ++tries;
      console.log('Failing intentionally.');
      chai.expect(true).to.be.false;
    }
 
    console.log('Passing.');
    chai.expect(true).to.be.true;
  });
});
```

**Expected behavior**
SauceLabs dashboard to correctly display test status for tests that pass on retry.

**Log**
1. [console.log](https://gist.github.com/jiyoon-sb/e82450937a346ab6abc93eb5fd8f8452#file-console-log)
2. [wdio-0-0.log](https://gist.github.com/jiyoon-sb/b9623b683c2ce3c2fe7f425ceed1f134#file-wdio-0-0-log)
3. [wdio.log](https://gist.github.com/jiyoon-sb/e54ed0195cd8079adb9fa697dd2118c4#file-wdio-log)

**Additional context**
A SauceLabs support ticket was created and they have responded indicating they have spoke with the main contributor for the WDIO project and confirms they think it is a WDIO issue.

**Comment by christian-bromann** [comment]
fixed by #5997
