### ISSUE TITLE
Unable to take screenshot with allure when using multiremote feature 

### ISSUE THREAD

**Issue by Amrkamel1** [webdriverio/webdriverio#5991]
Unable to have screenshot from the failed test when using combination of browserstack/appium and selenium stand alone services

**Environment (please complete the following information):**
 - **WebdriverIO version:**  6.6.4
 - **Mode:** multiremote feature
 - **If WDIO Testrunner, running sync/async:**  sync
 - **Node.js version:** 12.18.0
 - **NPM version:** 6.14.4
 - **Browser name and version:** chrome 
 - **Platform name and version:** win10 + BS
 - **Additional wdio packages used (if applicable):** 

  ```
"dependencies": {
    "@wdio/browserstack-service": "^6.6.3",
    "@wdio/cli": "^6.6.4",
    "eslint": "^7.11.0",
    "frisby": "^2.1.3",
    "wdio-chromedriver-service": "^6.0.4",
    "webdriverio": "^6.6.4"
  },
  "devDependencies": {
    "@wdio/allure-reporter": "^6.6.3",
    "@wdio/appium-service": "^6.6.3",
    "@wdio/dot-reporter": "^6.6.0",
    "@wdio/local-runner": "^6.6.4",
    "@wdio/mocha-framework": "^6.6.3",
    "@wdio/selenium-standalone-service": "^6.6.5",
    "@wdio/spec-reporter": "^6.6.3",
    "@wdio/sync": "^6.6.4",
    "@wdio/concise-reporter": "^6.6.0",
    "chai": "^4.2.0",
    "mocha": "^8.1.3"
  }

```
**Config of WebdriverIO**

```

services: [
  ['selenium-standalone', {
      args: {
        seleniumArgs: ['-port', '4444']
      },
  }],  
  ['browserstack'],
  // ['appium',{
  //   command : 'appium',
  //   args: {
  //       debugLogSpacing: true,
  //       sessionOverride: true,
  //       port: 4728,
  //       allowInsecure:'chromedriver_autodownload'
  //   },
  // }]
],
 afterTest: function(test, context, { error, result, duration, passed, retries }) {
        if (error !== undefined) {
            browser.takeScreenshot();
          }
    },

    reporters: ['dot','spec',['allure', {
        outputDir: 'allure-results',
        disableWebdriverStepsReporting: true,
        disableWebdriverScreenshotsReporting: false,
        disableMochaHooks: true
    }]],
```

**Describe the bug**
Unable to take screenshot for failed test when using multiremote feature

**To Reproduce**
use multi-remote feature with broswerstack/appium and selenium 

**Expected behavior**
Screenshot should be taken either from Browser or mobile app once test is failing

**Comment by christian-bromann** [comment]
Hey,
thanks for filing the issue. This seems indeed like bug. We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by MalshaRajapaksha** [comment]
The script fails with this error. Error: element (".WONDERESC") still not displayed after 30000ms

Tried different combinations for XPath, (relative, fixed, text()} and CSS selectors, but the button not clicked. The sign-in button div in the code block:
<div>
    <div class="WONDERBSC" role="form">
        <div>
            <div class="WONDERJ1B" data-automation-id="username">
                <div class="TOM-Label WONDERP1B"
                    title="Username">Username</div>
                <input type="text"
                        class="TOM-Textbox WONDERM1B" aria-label="Username">
                    <button type="button" class="TOM-Button WONDERN1B"/>
            </div>
        </div>
            <div>
                <div class="WONDERJ1B"
                    data-automation-id="password">
                    <div class="TOM-Label WONDERP1B" title="Password">Password</div>
                    <input type="password" class="TOM-Password Textbox WONDERM1B" aria-label="Password">
                        <button type="button" class="TOM-Button WONDERN1B"/>
                </div>
            </div>
                <button type="button"
                        class="WONDERESC"
                        data-automation-id="go Button">Sign In</button>
    </div>      
</div>

**Comment by mgrybyk** [comment]
@MalshaRajapaksha I believe the comment was deleted by accident, can you please re send it? Thanks

**Comment by hieuxlu** [comment]
@christian-bromann I would like to investigate this, as I worked on multiremote in the past few days. 

@Amrkamel1 IIRC, the API is `browser.saveScreenshot(filePath)`, not `browser.takeScreenshot()`, or what am I missing?

**Comment by christian-bromann** [comment]
Thank you @hieuxlu .. love all these great fixes on the multiremote side 👏

**Comment by Amrkamel1** [comment]
> @christian-bromann I would like to investigate this, as I worked on multiremote in the past few days.
> 
> @Amrkamel1 IIRC, the API is `browser.saveScreenshot(filePath)`, not `browser.takeScreenshot()`, or what am I missing?

interesting im using it without path in regular mode with no problem.
or it could mean that this part is already not used at all  

    reporters: ['dot','spec',['allure', {
        outputDir: 'allure-results',
        disableWebdriverStepsReporting: true,
        **disableWebdriverScreenshotsReporting: false,**
        disableMochaHooks: true
    }]],

**Comment by hieuxlu** [comment]
`wdio-allure-reporter` by design does not exclude support for multiremote. 
https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-allure-reporter/src/index.js#L212

There's a related PR, where we enabled something that was previously disabled in allure-reporter. I think we can do the same here: https://github.com/webdriverio/webdriverio/pull/6020 

@christian-bromann @mgrybyk Can you guys think of what could go wrong when enabling multiremote screenshots in for wdio allure reporter? I've experimented with it, and the only issue I found is that we can't distinguish which screenshot belongs to which browser in case of multiremote. Enabling screenshot attachment is quick, but to properly detect browser session in `onBeforeCommand` and `onAfterCommand`, we need to fix another issue: sessionId is undefined in case of multiremote when passed to `onBeforeCommand` & `onAfterCommand`. I prefer logging another issue to fix undefined sessionId, while enable screenshot capturing first. What do you think?

![image](https://user-images.githubusercontent.com/11418231/97099419-4a872b80-16bb-11eb-8c7b-65d70ad9233a.png)
