### ISSUE TITLE
es6 modules support

### ISSUE THREAD

**Issue by mohdasif2294** [webdriverio/webdriverio#600]
Hey!

I wanted to know how to run js scripts having es6 modules in wdio test runner . 
Usually for the unsupported environment . I use <b>--compilers js:babel/register</b> as argument to tests.

Where in wdio.config.js  can I specify this argument ?

This is the screenshot of errors which I get while running the tests .
![wdio_error](https://cloud.githubusercontent.com/assets/5481219/8497605/32c98566-219c-11e5-9557-4f8047653424.png)

**Comment by christian-bromann** [comment]
@mohdasif2294 instead of adding a parameter could you try to add `require('babel/register');` into your config file?

**Comment by mohdasif2294** [comment]
Thanks ! 
This Worked!!  :+1:

**Comment by BradNeuberg** [comment]
I've tried adding require('babel/register'); to the top of my wdio.conf.js to get babel to transpile my source files before wdio tries to run them, but it does not work; I only get a blank browser that pops up. Is there something else that others did for this bug fix for this to work?

**Comment by christian-bromann** [comment]
@BradNeuberg you can also try to put it into your before hook

**Comment by BradNeuberg** [comment]
I figured out the answer: you have to add this in wdio.config.js _after_ the configuration JSON at the top of the file.

**Comment by BradNeuberg** [comment]
A note for others that want to use Babel with Webdriver.io: make sure to turn off Babel's regenerator transformer so that generators are passed through to Webdriver.io/Node.js Harmony. Add this after your wdio.config.js JSON block:

    // Cause all of our Selenium scripts to get transpiled by Babel in real-time into full ES6,
    // running on Node.js. Allow generator calls to directly go through, since Node.js has efficient
    // support for those.
    require('babel/register')({
      blacklist: [
        'regenerator'
      ]
    });

**Comment by ghengeveld** [comment]
Thanks @BradNeuberg, that works. The docs should say something about this.

**Comment by stsvilik** [comment]
Maybe due to Babel updates a step suggested by @BradNeuberg didn't work for me. I managed to make it work though with the following code:
```js
require("babel-core/register")({
    presets: ['es2015']
});
```

As mentioned above, this snippet of code goes AFTER export.config. With this you could write your tests in ES6.

**Comment by ghengeveld** [comment]
With Babel 6 it should be `babel-register` (it's a separate npm package), and you can put the configuration in a `.babelrc` file.

**Comment by stsvilik** [comment]
@ghengeveld got it thanx. Looks like register is bundled with various npm packages:

- babel-core
- babel-register

**Comment by shridharkalagi** [comment]
Is there a way to write the config files in ES6? I need this as I'm merging few config files and also in the hooks I'm using other functions from other files. Can someone help?

**Comment by stsvilik** [comment]
@shridharkalagi Node 8+ would support ES6 syntax natively (sans import/export). Still not sure how ES6 would solve a problem for you that ES5 wouldn't.

**Comment by shridharkalagi** [comment]
Hey @stsvilik ES6 syntax in config files was not working for me. However, I got it working. Reference [here](https://github.com/christian-bromann/saucecon-talk-2018-livecoding/blob/master/wdio.local.conf.js)
