### ISSUE TITLE
Add browser.mock clearAll and restoreAll commands

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#6003]
**Is your feature request related to a problem? Please describe.**
I want to be able to clear/restore all mocks with one command

**Describe the solution you'd like**
implement `browser.mock.clearAll` and `browser.mock.restoreAll` commands

**Comment by mgrybyk** [comment]
This ones applied to all the user defined mocks.
Kind of jest.clearAllMocks()

**Comment by christian-bromann** [comment]
Implemented in #6930
