### ISSUE TITLE
Better deal with strings in `switchWindow`

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#6012]
**Is your feature request related to a problem? Please describe.**
Currently the [`switchWindow`](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/commands/browser/switchWindow.js) command iterates over all window handles and calls matches on url and title to see if the input matches it. This can be problematic if users use strings that contain a regexp character:

```js
// works perfectly if you match like this
browser.switchWindow('google.com')

// doesn't work if you have a `?` character
browser.switchWindow('google.com?foobar=barfoo') // does not match the url e.g. https://google.com?foobar=barfoo
```

**Describe the solution you'd like**
Let's check if the command input is a string and use [`includes`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes) if so otherwise use [`match`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match) if it is a RegExp.

**Describe alternatives you've considered**
n/a

**Additional context**
This comes from a conversation I had with someone in Gitter stumbling over this.

**Comment by kacperturon** [comment]
can I get assigned to it?

**Comment by christian-bromann** [comment]
@kacperturon sure thing!

**Comment by christian-bromann** [comment]
@kacperturon any updates?

**Comment by christon88** [comment]
@christian-bromann since this has not been updated for a while, do you mind if i take a shot at it?

**Comment by christian-bromann** [comment]
sure thing, go for it!
