### ISSUE TITLE
If statement while using WDIO test runner

### ISSUE THREAD

**Issue by razielron** [webdriverio/webdriverio#6017]
Hey, so my team is working to change the entire site framework (Angular -> vue.js).
This is a long process and they do it in parts.
This means we can have 2 components that look the same but the elements are different.
I want to build a wrapper function that checks element's existence and navigate to a function that uses the relevant elements (that does clicks, sendkeys etc.).
So I tried adding an 'if' statement but obviously this is a promise, so I tried adding 'async/await' but that breaks the WDIO test runner or so I read it.
I don't want to use .then() cause this looks very bad and unreadable.
Can someone help me with an example on how to use an 'if' statement while keeping WDIO test runner (without .then() function)?

**Comment by christian-bromann** [comment]
> so I tried adding 'async/await' but that breaks the WDIO test runner or so I read it.

Why would async/await break the runner? If statements work well in WebdriverIO tests.

I recommend to have a look into the docs, particularly these resources:

- https://webdriver.io/docs/sync-vs-async.html
- https://webdriver.io/docs/pageobjects.html

If you have more questions don't hesitate to join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).

I will close this as it doesn't seem to be an issue.
