### ISSUE TITLE
AWS DeviceFarm Desktop Browser testing support

### ISSUE THREAD

**Issue by workeitel** [webdriverio/webdriverio#6018]
**Is your feature request related to a problem? Please describe.**
I would like to contribute AWS DeviceFarm support to easily connect to DeviceFarm webdriver endpoint.

**Describe the solution you'd like**

The Auth model for AWS DeviceFarm is slightly different. There is no fixed webdriver endpoint but instead the DeviceFarm endpoint needs to be called using the [aws-sdk](https://github.com/aws/aws-sdk-js/). The API call returns the webdriver endpoint. Here is a example in the official DeviceFarm docs: https://docs.aws.amazon.com/devicefarm/latest/testgrid/testing-frameworks-nodejs.html#w10aac11c13c13

Other services are detected based on the provided credentials: https://github.com/webdriverio/webdriverio/blob/db67ff5513d022ec9a4a8033b65e1584e5e4013a/packages/wdio-config/src/utils.js#L57 so I thought DeviceFarm could be used the same but that has two problems:

1) Heavy dependency of aws-sdk package in the wdio-config package to call DeviceFarm for the endpoint
2) The credentials can be either permanent (like username/password) or temporary credentials which contains a third component and max valid for 12h. The aws-sdk has already multiple mechanisms to find credentials (environment variables, config file, ...): https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-credentials-node.html - Hard-coding temporary in the wdio config would be strange. It might be compromise for permanent credentials but we should support temporary for sure as well since it's the recommendation by AWS.

My suggestion would be to add a new `devicefarm` service which calls DeviceFarm in `onPrepare`. That solves the mentioned problems but has the downside that: 1) user/key is ignored for `devicefarm` and 2) `devicefarm` must be in the enabled services.

My questions:

1) Is such a contribution welcome?
2) Is the proposed approach a good idea? Any other suggestions?
3) Except unit testing which other testing should be included to verify the new package?

(disclaimer: I'm with AWS but I'm not in the AWS DeviceFarm team)

**Comment by christian-bromann** [comment]
Hey @workeitel 👋 

Such a contribution is of course welcome!

if the `aws-sdk` wouldn't be so huge I would not have a problem adding it as dependency. It would be great if the experience could be as seamless as possible, without having an extra service. Services like other WebdriverIO plugins only work in conjunction with running the wdio testrunner.

Is it feasible to extract this one request into a little helper method and integrate it directly into the [`webdriverio`](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/index.js#L45-L47) package?

If we can't and have to use the SDK I would suggest to create a service that does the job you described above.

For this change unit testing should be sufficient enough.

**Comment by workeitel** [comment]
Extracting only this one API call is difficult for two reasons:

1) Credential detection is needed for temporary credentials. It would be a lot of effort to re-implement that part to be consistent with the aws-sdk. It's required for temporary credentials because the creds are only valid for a limited amount of time and can come from many different sources.
2) The API call itself needs to be signed using the AWS Signature v4 which is not trivial to implement. There is one [community owned package](https://www.npmjs.com/package/aws4) which only includes the signature so that could work.

Another option would be to use the new aws-sdk V3 which is currently in release candidate state. It's more lightweight but still has some dependencies: https://github.com/aws/aws-sdk-js-v3/tree/master/clients/client-device-farm

What do you think? Too big or worth a try?

---

Another idea is to still require the `devicefarm` service but automatically load it if possible:

For permanent credentials using wdio's user/key is fine. We would map the AWS access key ID (always 20 chars and starts with a defined prefix: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html#identifiers-unique-ids ) to `user` and the AWS secret access key (always 40 chars https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html#access-keys-and-secret-access-keys ) to `password`.

Would it be possible to instead of triggering the `devicefarm` call in `detectBackend` to load the `devicefarm` service instead? That way, if a user has permanent credentials it can be configured only with `user` and `password`, the `devicefarm` service gets automatically loaded and no other configuration is needed. The `devicefarm` service is then triggering the API call and updating the capabilities.

For temporary credentials I don't see how we can make the auto detection work since in addition to the AWS secret access key and AWS secret access key a third key called AWS session token is required. In addition it can change often so updating the config file every time is cumbersome. For that case I would propose to require manually putting the `devicefarm` config into the `services` and not use the service auto-detection. It's a bit uncommon from what I see in other wdio cloud services but I think a good compromise. Then we can use the aws-sdk to discover credentials and trigger the call.

**Comment by christian-bromann** [comment]
> What do you think? Too big or worth a try?

Adding a 415kb (minified) dependency to a package that has 1MB (minified) total payload seems a bit too much. Currently it seems that having a dedicated `devicefarm` service seems like the best approach until we can maybe strip out the auth part from the S3 package to make it more lightweight. The service could be build in a way that it also supports users using WebdriverIO in standalone mode.

WDYT?

**Comment by workeitel** [comment]
I created a initial version as a separate service. It's just a draft and missing the README.md and some tests (builds fail because of low test coverage) but would be great to get some feedback if it goes in the right direction.

**Comment by christian-bromann** [comment]
@workeitel did you publish the service somewhere? Would love to take a look.

**Comment by christian-bromann** [comment]
I am closing this up. I think we have an agreement that adding an AWS DeviceFarm service to the core project (this repo) is not desired due to the large dependency `aws-sdk-js-v3` brings. Such a service can very well life in a different repository without any negative effect on the user experience. This discussion has shown that we should have a better definition of what is suppose to be added to core vs. go as community plugin. Thanks for the contributions @workeitel. I still very much looking forward to have an AWS service for WebdriverIO. I am happy to assist reviewing code and adding it to the `@wdio/cli` package and our docs. Cheers!

**Comment by JavierLuna** [comment]
Hi @christian-bromann!

We've just published [wdio-aws-device-farm-service](https://github.com/awslabs/wdio-aws-device-farm-service) and is available in [npmjs](https://www.npmjs.com/package/wdio-aws-device-farm-service). Feel free to drop by and comment on it, your feedback would be greatly appreciated.

We will work towards adding it to the @wdio/cli and the docs. Expect a PR soon 😄.

Thank you for the response and advise.

**Comment by christian-bromann** [comment]
> We will work towards adding it to the @wdio/cli and the docs. Expect a PR soon 😄.

Awesome, looking forward! Thanks for all your work 🙏
