### ISSUE TITLE
RuntimeError: Couldn't connect to selenium server

### ISSUE THREAD

**Issue by gaboom** [webdriverio/webdriverio#602]
Following the default example http://webdriver.io/guide.html or http://webdriver.io/ on a windows 8 machine, it never worked:

```
RuntimeError: Couldn't connect to selenium server
    at end() at c:\src\webdsl\index.js:16:6
```

The selenium server was up and running:
```
$ java -jar selenium-server-standalone-2.45.0.jar
18:42:28.635 INFO - Launching a standalone server
18:42:28.760 INFO - Java: Oracle Corporation 25.45-b02
18:42:28.760 INFO - OS: Windows 8.1 6.3 amd64
18:42:28.775 INFO - v2.45.0, with Core v2.45.0. Built from revision 5017cb8
18:42:28.900 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
18:42:28.900 INFO - Version Jetty/5.1.x
18:42:28.900 INFO - Started HttpContext[/selenium-server,/selenium-server]
18:42:28.978 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@11531931
18:42:28.994 INFO - Started HttpContext[/wd,/wd]
18:42:28.994 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
18:42:28.994 INFO - Started HttpContext[/,/]
18:42:28.994 INFO - Started SocketListener on 0.0.0.0:4444
18:42:28.994 INFO - Started org.openqa.jetty.jetty.Server@cc34f4d
```

Only after adding explicit
```
    host: 'localhost',
    port: 4444
```
it started working!  

```javascript
var webdriverio = require('webdriverio');
var options = {
    desiredCapabilities: {
        browserName: 'chrome'
    },
    host: 'localhost',
    port: 4444
};

webdriverio
    .remote(options)
    .init()
    .url('http://www.google.com')
    .title(function(err, res) {
        console.log('Title was: ' + res.value);
    })
    .end();
```

**Comment by christian-bromann** [comment]
That is weird. Which version are you using? Per default it's falls back to localhost:4444 so there is absolute no need to add host and port (even on Windows).

**Comment by christian-bromann** [comment]
This got fixed by #627 and published with `v3.1.0`

**Comment by santospro** [comment]
Hi christian, how can I download the v3.1.0 ??

**Comment by n06rin** [comment]
@christian-bromann I making first steps with webdriver.io and stucked with that problem too.

I have a 4.8.0 webdriverio version.

I'm try to use wdio-selenium-standalone-service, and only when I set

    host: 'localhost',
    port: 4444

at wdio.test.conf it start working as expected.

**Comment by christian-bromann** [comment]
@n06rin please make sure you have a selenium standalone server running and Chromedriver or Geckodriver setup. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions.

**Comment by juliancoleman** [comment]
[Gitter](https://gitter.im/webdriverio/webdriverio) is pretty quiet. I'm currently experiencing this issue with `webdriverio@^4.12.0` and `chromedriver@^2.38.3`. Do I _really_ need to use `selenium-standalone`? According to [this doc](https://developers.google.com/web/updates/2017/04/headless-chrome#using_webdriverio) and [WebDriverIO's own docs](http://webdriver.io/guide/services/chromedriver.html), I shouldn't, unless there's some extra config that's missing from the documentation. In that case, please supply some additional documentation for setup.
