### ISSUE TITLE
do not rely on global browser instance

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#6025]
**Is your feature request related to a problem? Please describe.**
Some packages like spectron run webdriverio programmatically and suppose that a browser instance created in a programmatic way is the only entry point (which I believe is correct)

**Describe the solution you'd like**
I'd like to remove all the occurrences of `global.browser` from the project

**Comment by Hayk-S** [comment]
`import { Application } from 'spectron';
/**
 * Future instance of the Electron Application
 */
let app = null;
export const launchApp = async () => {
  app = new Application({
    path: appPath
  });
  await app.start();
  return app;
};` 

And after in beforeAll hook I call it as `global.app = await launchApp();`

**Comment by mgrybyk** [comment]
@Hayk-S can you try the following as a workaround:
```
await app.start();
global.browser = app; // add this one
return app;
```

**Comment by christian-bromann** [comment]
> I'd like to remove all the occurrences of `browser.global` from the project

I only see usage in the services.

Is the background idea here to allow Spectron user to use services?

**Comment by mgrybyk** [comment]
Yes

**Comment by christian-bromann** [comment]
Let's continue convo in #6143
