### ISSUE TITLE
Include coverage result from .ts files

### ISSUE THREAD

**Issue by hieuxlu** [webdriverio/webdriverio#6033]
We're skipping test coverage for *.ts files while migrating to Typescript. I propose to maintain coverage and migrate at the same time, or at least tracking this issue somewhere so we won't have to rush to update coverage of hundreds of files after TS migration.

https://github.com/webdriverio/webdriverio/blob/73878e15ac588d65d0dd6b6bf505f530f15aa8c2/jest.config.js#L26-L29

**Comment by hieuxlu** [comment]
Another issue with Typescript migration: symlink commited to GIT is not understood by Windows. I don't know why it still passes CI checks.
```
// packages\wdio-applitools-service\src\@types\applitools-service.d.ts
../../applitools-service.d.ts
```

![image](https://user-images.githubusercontent.com/11418231/97191120-228dea00-17d9-11eb-8e07-7815ebd26fe8.png)

**Comment by christian-bromann** [comment]
@hieuxlu I've seen CI runs particular failing on Windows with a bunch of TS erros. This could be the reason for this.

**Comment by hieuxlu** [comment]
> @hieuxlu I've seen CI runs particular failing on Windows with a bunch of TS erros. This could be the reason for this.

Ah wrong alert, Windows developers will need to set git's `core.symlinks` to true, either globall with `git config --global --add core.symlinks true` or locally when cloning `git clone -c core.symlinks=true <URL>`

I think we might need to update this in CONTRIBUTE.md docs
https://github.com/git-for-windows/git/wiki/Symbolic-Links
