### ISSUE TITLE
How to replace waitFor in v3?

### ISSUE THREAD

**Issue by binarykitchen** [webdriverio/webdriverio#604]
Changelog says that the `waitFor` command has been removed. But doesn't say much how to fix code. How can I migrate my code from v2 to v3 that has plenty of `waitFor` in it?

**Comment by binarykitchen** [comment]
And you say, waitForExist has also been removed but it's still documented in http://webdriver.io/api/utility/waitForExist.html

**Comment by christian-bromann** [comment]
> And you say, waitForExist has also been removed

Where does it say that?


> How can I migrate my code from v2 to v3 that has plenty of waitFor in it?

Just replace it with `waitForExist`

**Comment by binarykitchen** [comment]
Here it says:
https://github.com/webdriverio/webdriverio/blob/master/CHANGELOG.md#v300-2015-06-29

"removed waitFor command (same as waitForExist)"

That sentence can be easily misunderstood. I interpreted it that the same applies for waitForExist. But you probably meant to replace all occurrences of `waitFor` with `waitForExist`? Language you know ;)

**Comment by christian-bromann** [comment]
I see, ya you are totally right. Language is a tricky piece of cake. Let me fix that.
Cheers
