### ISSUE TITLE
browser.elementSubmit not supported

### ISSUE THREAD

**Issue by nolanlawson** [webdriverio/webdriverio#6044]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.7.0
 - **Mode:** WDIO
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.19.0
 - **NPM version:** 6.14.8
 - **Browser name and version:** 86
 - **Platform name and version:** MacOS Catalina
 - **Additional wdio packages used (if applicable):** N/A

**Config of WebdriverIO**

I followed the [Getting started](https://webdriver.io/docs/gettingstarted.html) guide. No other modifications.

**Describe the bug**

[`browser.elementSubmit`](https://webdriver.io/docs/api/jsonwp.html#elementsubmit) is documented on the website, but as far as I can tell, it's not actually exposed on the `browser` object. You can test like so:

```js
describe('webdriver.io page', () => {
    it('has browser.elementSubmit', () => {
        browser.url('https://webdriver.io');
        console.log('browser.elementSubmit', browser.elementSubmit); // <- undefined
    })
})
```

There is also no equivalent API, e.g. `browser.$('form').submit()`. It seems the only way to submit a form is via JavaScript or clicking the `submit` button.

[Searching the codebase](https://github.com/webdriverio/webdriverio/blob/464d95a6d51183a9cf95ddf9417ddbf76058a104/packages/webdriver/webdriver.d.ts) seems to indicate that it's documented, but not implemented.

**To Reproduce**

See above. Following the "getting started" guide and using that test in `test/spec/basic.js` is sufficient to repro.

**Expected behavior**

Since the API is documented, I would expect it to exist.

**Comment by christian-bromann** [comment]
> is documented on the website, but as far as I can tell, it's not actually exposed on the `browser` object

Correct because it is a command that was supported in the old JSONWireProtocol and doesn't not work in latest browsers anymore.

> It seems the only way to submit a form is via JavaScript or clicking the `submit` button.

That is correct and the recommended way to go forward.

> Since the API is documented, I would expect it to exist.

If you run a test in an old browser this command would still exist. WebdriverIO knows which protocol is being used and assigns the commands based on that.

Let me know if you have any further questions.

**Comment by nolanlawson** [comment]
Awesome, thanks for the explanation! I was not aware of this.
