### ISSUE TITLE
How to make wdio customCommands work with typescript

### ISSUE THREAD

**Issue by poc7667** [webdriverio/webdriverio#6046]
Newbie to wdio.
But wonder why it's not easily getting along with typescript.
```
Error: TSError: ⨯ Unable to compile TypeScript:
tests/specs/basic/01_new_apartments.spec.ts(20,17): error TS2339: Property 'lala' does not exist on type 'BrowserObject'.
```

```
import { BASE_URL } from "../../constants";
import Index from "../../pageobjects/index.page";


describe('Export apartments', () => {
    let index : Index

    before( () => {
        index = new Index();
        browser.addCommand('lala', ()=>{
            console.log(123);
        })
    });

    it('should take screenshot', () => {

        browser.url(BASE_URL)
        browser.pause(3000);
        browser.lala();
    });

});

```

**Comment by hieuxlu** [comment]
The most common issue is you forgot to add reference to type definition file in `tsconfig.json`
See docs on webdriverio, section "Adding custom commands": https://webdriver.io/docs/typescript.html#adding-custom-commands
Boilerplate wdio Typescript project: https://webdriver.io/docs/boilerplate.html#pako88wdio-mocha-typescripthttpsgithubcompako88wdio-mocha-typescript
