### ISSUE TITLE
Option to disable implicit wait

### ISSUE THREAD

**Issue by hico-bst** [webdriverio/webdriverio#6047]
**Is your feature request related to a problem? Please describe.**
I'm migrating from v4 to v6 and noticed that actions like `click` do implicitly wait for the element to exist if it doesn't already.
This implicit wait is not controlled by `browser.setTimeout({implicit: 1})`, as it just calls `currentElement.waitForExist()` which uses `waitforTimeout` from the config.

**Describe the solution you'd like**
- An option in wdio.conf.js. E.g. `enableImplicitWait: true`. I could then set it to `false`.
- Use the implicit timeout in the `implicitWait` function. I could then set it to `1`.
`currentElement.waitForExist({timeout: browser.getTimeouts().implicit || undefined})`
https://github.com/webdriverio/webdriverio/blob/6d41918/packages/webdriverio/src/utils/implicitWait.ts

Though the latter would print a timeout error which is not exactly my desired error message.
- Without implicit timeout: `Can't call click on element with selector "aa" because element wasn't found`
- With: ``waiting for selector `aa` failed: timeout 1ms exceeded``

**Additional context**
This mainly affects my unit tests in which I check for various error messages. Previously, they ran near instantly aside from the ones that do `waitFor` something.
Now, pretty much all tests that I expect to throw an error take 2s to complete. (My `waitforTimeout` value) The execution duration for my webdriver spec increased threefold from 20 seconds to 60 seconds.

**Comment by christian-bromann** [comment]
This seems pretty specific to your setup. I don't understand why you would run unit tests alongside e2e tests and how explicitly waiting on the element is causing an issue here. Just set `waitforTimeout` to 0 and you should have the same effect.

Happy to answer any further questions.

**Comment by hico-bst** [comment]
I wrote unit tests for the dependencies I use for the e2e setup. This way I can quickly check if an update breaks the API/wrappers I created.
Setting `waitforTimeout: 0` forces me to explicitly pass the timeout parameter in each `waitFor*` call. I will give it a shot though, it should not be too much hassle in my setup.

In any case, I do find it confusing that this implicit wait is not affected by setting `browser.setTimeout({implicit: 1})`. I had to check the source code to find out why that is.

**Comment by christian-bromann** [comment]
WebdriverIO is not implicitly waiting on elements. If an element is not found, WebdriverIO waits until it exists - this explicit waiting and is different from WebDrivers implicit waiting (which you should not use).

**Comment by hico-bst** [comment]
This might technically be true, but as a user of the WebdriverIO API I have little control over this particular wait without affecting all others. I did not explicitly tell it to wait, and the method even is called `implicitWait`.

Anyway, your suggestion to set `waitforTimeout: 0` did work for me, so there are ways to get around it. Thank you!
