### ISSUE TITLE
Allow webdriver steps reporting in allure when using cucumber step reporting.

### ISSUE THREAD

**Issue by gambrose** [webdriverio/webdriverio#6048]
**Is your feature request related to a problem? Please describe.**
When using the allure with cucumber. When I set `useCucumberStepReporter` I lose the nice webdriver steps reporting.

**Describe the solution you'd like**
I would like the cucumber step reporting to be controlled only by the existing option `disableWebdriverStepsReporting`.

**Describe alternatives you've considered**
Not use `useCucumberStepReporter` and live with each scenario step being a test.

**Comment by christian-bromann** [comment]
Any kind of enhancements to the Allure reporter is welcome. Please feel free to provide a pull request, thanks!

**Comment by christian-bromann** [comment]
Let's continue convo in #6049
