### ISSUE TITLE
test suite ends due to command error

### ISSUE THREAD

**Issue by Skadi2k3** [webdriverio/webdriverio#605]
This relates to the following code example: https://github.com/webdriverio/webdriverio/blob/master/examples/webdriverio.with.mocha.and.chai.js

If you change the browser to, e.g. firefox, or the expected value, e.g. from 26 to 27, it will exit the whole testing suite without even calling the after function.

It ends with:
undefined: expected 26 to equal 27 
at elementIdSize("0") at     at /<path>/webdriverio/lib/commands/getElementSize.js:43:4

**Comment by christian-bromann** [comment]
`getElementSize` should not throw an error actually. But indeed if a command fails the test suite doesn't end by calling the after hook function. I tried to just throw an error and it worked properly.

**Comment by Skadi2k3** [comment]
Using only one get<x> call per it statement makes the test run till the end, so it seems the chaining doesn't work anymore, when an assert fails.

**Comment by christian-bromann** [comment]
fixed with 85f6a86...4310728
