### ISSUE TITLE
specFileRetriesDeferred is missing from Typescript config definitions

### ISSUE THREAD

**Issue by LouisStAmour** [webdriverio/webdriverio#6051]
**Environment (please complete the following information):**
 - **WebdriverIO version: 6.7.0**

**Config of WebdriverIO**
I copied in the default config from the examples folder, and modified it to use the TypeScript config object as shown in the TypeScript setup documentation.

**Describe the bug**
TypeScript error: 

> Object literal may only specify known properties, and 'specFileRetriesDeferred' does not exist in type 'Config'

**To Reproduce**

Copy https://github.com/webdriverio/webdriverio/blob/master/examples/wdio.conf.js to wdio.conf.ts and then modify it as instructed at Typed Configuration: https://webdriver.io/docs/typescript.html#typed-configuration

**Expected behavior**
The example config file with all the options should be valid TypeScript :)

**Additional context**
Running Yarn v2 PnP which is why I didn't generate my config, I hit bug #5228 so I copied and pasted my config instead.

**Comment by christian-bromann** [comment]
Hey,
thanks for filing the issue. This seems indeed like bug. We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!
