### ISSUE TITLE
[wdio-allure-reporter] Unable to attach buffer content type as a 'image/png'  to allure report 

### ISSUE THREAD

**Issue by jaworsmi** [webdriverio/webdriverio#6053]
https://github.com/webdriverio/webdriverio/blob/63519058a7fab1bdc424fc95c14f97207d496627/packages/wdio-allure-reporter/src/index.js#L538-L540

All kind of buffer content types (like screenshots created in wdio) are handed as a  'text/plain'  due to changes made in #6022

**Comment by mgrybyk** [comment]
Fixing it
