### ISSUE TITLE
Reporter outputs everything to the terminal

### ISSUE THREAD

**Issue by erwinheitzman** [webdriverio/webdriverio#6055]
A user complained that after upgrading to version 6.7.0, their terminal was flooded with log messages.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.7.0

**Describe the bug**
Terminal is flooded with logging

**To Reproduce**
After pulling the latest version and running the following, I managed to reproduce this very easily:

```js
mkdir wdio-temp
cd wdio-temp
npm init -y
npm i @wdio/cli
npx wdio config -y
npx wdio
```

You'll see all the webdriver request messages which weren't shown in previous versions.

**Expected behavior**
Same logging as in previous versions

**Comment by christian-bromann** [comment]
> You'll see all the webdriver request messages which weren't shown in previous versions.

I just ran the script and see the same logs that were shown before too. The default behavior was always that WebDriver request data was shown. Please describe what you were expecting.

Otherwise I would close this.

**Comment by aditya-3008** [comment]
Hi, 
If you will try interacting with browser.react$('Component) , you will find the execute/sync function getting called multiple times and flooded with logs. 
You can try with the code:
describe('Noise in logs execute/sync is getting called multiple times', () => {
it('Demos Creative react app', async function () {
await browser.url('https://demos.creative-tim.com/nextjs-material-kit-pro/presentation')
await browser.maximizeWindow();
const prop = browser.react$('f', { props: { className: 'jss892' } });
console.log(prop);
await browser.takeScreenshot();
await browser.saveScreenshot("C:\Users\demoReact.png");
})
})

**Comment by christian-bromann** [comment]
This is not new behavior, I tested with `v6.4.0` and see the same

**Comment by christian-bromann** [comment]
You can set [`logLevel`](https://webdriver.io/docs/options.html#loglevel) to `warn` to suppress these messages. I checked and it was the same behavior in v6.1.x. Therefor I will close the issue.

**Comment by aditya-3008** [comment]
So it means, whenever we will call the browser.react$(), it will return with execute/sync function with all the details inside it in the logs.
Below screenshot: 
![image](https://user-images.githubusercontent.com/69587843/97713454-2911af80-1ac0-11eb-9c23-a3b54df8a280.png)

**Comment by christian-bromann** [comment]
This is correct. Again, you can suppress these logs if you don't want them in your terminal. Some people might be interested in these. If you have an idea how to improve please let us know.

**Comment by aditya-3008** [comment]
Thank you so much for the information, can you please let me know if we can disable these execute/sync logs. I want other logs like assertions and results but I don't want to see execute/sync which is getting called after browser.react$()

**Comment by erwinheitzman** [comment]
@aditya-3008 https://webdriver.io/docs/options.html#loglevel
