### ISSUE TITLE
browser.mock in a new window not working

### ISSUE THREAD

**Issue by vmelikyan** [webdriverio/webdriverio#6057]
**Environment:**
 - **WebdriverIO version:** 6.7.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.23.0
 - **NPM version:** 6.14.8
 - **Browser name and version:** Chrome 86.0.4240.111
 - **Platform name and version:** Mac OS Catalina 10.15.7 (19H2)
 - **Additional wdio packages used (if applicable):** @wdio/spec reporter, @wdio/selenium-standalone service

**Config of WebdriverIO**
```javascript
exports.config = 
{
  runner: 'local',
  specs: [ './specs/**test.js' ],
  exclude: [],
  maxInstances: 5,
  capabilities: [ { maxInstances: 5, browserName: 'chrome' } ],
  logLevel: 'warn',
  bail: 180000,
  baseUrl: '',
  waitforTimeout: 25000,
  connectionRetryTimeout: 90000,
  specFileRetries: 0,
  connectionRetryCount: 2,
  // automationProtocol: 'devtools',
  services: [ 'selenium-standalone' ],
  framework: 'mocha',
  specFileRetries: 0,
  reporters: ['spec'],
  mochaOpts: { ui: 'bdd', timeout: 60000 }
}
```

**Describe the bug**
Mocking seems to not work when opening a new tab in the test flow.

**To Reproduce**

```javascript
describe("Mocking", () => {
  it('Should be able to mock in a new tab', () => {
    const mock1 = browser.mock('https://www.rapidtables.com/web/html/**')
    browser.url('https://www.rapidtables.com/web/html/link/html-link-new-window.html')
    browser.$('//a[contains(text(),"Open page in new window")]').click()
    browser.waitUntil(() => (browser.getWindowHandles()).length > 1);
    browser.switchToWindow(browser.getWindowHandles()[1]);
    const mock2 = browser.mock('https://www.rapidtables.com/web/html/**')
    browser.pause(2000)
    browser.refresh()
    browser.pause(2000)
    console.warn(mock1.calls.length);
    console.warn(mock2.calls.length);
  });
});
```

```
Execution of 1 spec files started at 2020-10-30T20:58:20.692Z

[0-0] RUNNING in chrome - /specs/mock_test.js
[0-0] 1
[0-0] 0
[0-0] PASSED in chrome - /specs/mock_test.js
```

**Expected behavior**
Should be able to mock in the new tab after the page is refreshed.

**Additional context**
It seems like we are always getting the first page [here](https://github.com/webdriverio/webdriverio/blob/d064e3175a915fdc74507cbfaf561c67602c5a0d/packages/webdriverio/src/commands/browser/mock.ts#L116)

**Comment by christian-bromann** [comment]
Hey,
thanks for filing the issue. This seems indeed like bug. We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by mgrybyk** [comment]
It's only tests left to do https://github.com/webdriverio/webdriverio/compare/mock-multi-window

Sorry to say I don't have time to work on it right now, please feel free to pick up.

P.S.
tested locally, works fine

**Comment by leviv-kr** [comment]
Hey all!
Is this still an issue? I keep getting this error using v7.16.14

Thanks in advance
