### ISSUE TITLE
Pending tests

### ISSUE THREAD

**Issue by dhoulker** [webdriverio/webdriverio#606]
Hi,

We used to use 

it('should be a test that we write later');

To allow us to have pending tests that need to be written later.

http://mochajs.org/#pending-tests

When we try this now the test fails with 'undefined is not a function'

Is it still possible to have pending tests, and if so what should the format of them be?

Thanks,

Dave

**Comment by christian-bromann** [comment]
Hi Dave,

I wasn't aware of this functionality in Mocha when I was implementing the support for generators. I will fix that.

**Comment by christian-bromann** [comment]
fixed and publish `v3.0.2`

**Comment by dhoulker** [comment]
Wow - that was quick, many thanks!

I really don't want to ask for more after you fixed it so quickly - but whilst the test does not fail it reports as -undefined, where it used to show the test name in the reporter.

![image](https://cloud.githubusercontent.com/assets/5832261/8519523/28f1e3f4-23cb-11e5-8579-c3c66e9c5b6a.png)

Would it be possible to update that?

Many thanks

Dave

**Comment by christian-bromann** [comment]
Dang I tested it with the dot reporter. Fixed with `v3.0.3`

**Comment by dhoulker** [comment]
That works :) You don't mess around!

Thanks Christian.
