### ISSUE TITLE
Cannot change outputDir for a new Appium session while testing

### ISSUE THREAD

**Issue by RedMickey** [webdriverio/webdriverio#6068]
Hello,
I am a maintainer of [React Native Tools](https://github.com/microsoft/vscode-react-native) VS Code extension, which is used for debugging React Native applications in VS Code. We use WebdriverIO package for testing of the extension.

**Environment:**
 - **WebdriverIO version:** 6.6.7
 - **Mode:** Standalone mode
 - **Node.js version:** 10.19.0
 - **NPM version:** 6.13.4
 - **Platform names and versions:** Windows 10, macOS 10.15.7, Linux Ubuntu 18.04
 - **Appium**: 1.18.2

**Describe the bug**
We use `Appium` as a server. In our tests we create a WebdriverIO session per each test. We'd like to have logs from each session in separate `wdio.log` files. We specify `outputDir` parameter for each session, but the only first configuration is taken into account. So logs from the second session are written in the `.log` file of the first session and so on.

**To Reproduce**
Try to create 2 WebdriverIO sessions sequentially with different `outputDir` parameters.

1. Start Appium using the command `appium` in the terminal
2. Add capabilities to the configurations below and run the script

```js
const wdio = require("webdriverio");

const opts1 = {
    path: '/wd/hub',
    port: 4723,
    capabilities: { /*any capabilities*/ },
    logLevel: "trace",
    outputDir: `${__dirname}/1`
};

const opts2 = {
  path: '/wd/hub',
  port: 4723,
  capabilities: { /*any capabilities*/ },
  logLevel: "trace",
  outputDir: `${__dirname}/2`
};
  
  async function main () {
    let client = await wdio.remote(opts1);

    console.log("ses1-sleep");
    await sleep(4000);

    await client.deleteSession();

    console.log("ses1 - end");
    await sleep(15000);

    console.log("ses2");
    client = await wdio.remote(opts2);
  
    console.log("ses2-sleep");
    await sleep(6000);

    console.log("ses2 - pre end");
    await client.deleteSession();
  }
  
  main();

async function sleep(time) {
  await new Promise(resolve => {
      const timer = setTimeout(() => {
          clearTimeout(timer);
          resolve();
      }, time);
  });
}
```

After that logs from the both sessions were written to the log file for the first session
![image](https://user-images.githubusercontent.com/33267199/98209318-c6049a80-1f4f-11eb-96a3-5e66b0668a13.png)

**Expected behavior**
`wdio.log` logs for each session are written in different files (in the folders `1` and `2`).

**Additional context**
We investigated this issue and found out that [`process.env.WDIO_LOG_PATH`](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/index.js#L50) is responsible for logging directory. While debugging we found out this variable is changed on each session creation. We also found that a log file is created [here](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-logger/src/node.ts#L63-L65). We revealed such behavior that according to the current condition if the `process.env.WDIO_LOG_PATH` is changed and the 'logFile' exists, a new file won't be created. So WebdriverIO continues to write logs to the first created file.
![Screen Shot 2020-11-05 at 10 36 21](https://user-images.githubusercontent.com/33267199/98211597-52fd2300-1f53-11eb-8afb-bad27bb804b6.png)

**Comment by christian-bromann** [comment]
@RedMickey thanks for filing this issue. This definitely seems like an undesired behavior which should be easy to fix. I would suggest to add function to the logging interface (`@wdio/logger`) that cleans up log file, e.g.:

```js
loggers[name].clearLogger = () => {
    delete logFile
}
```

and then, call this method when `deleteSession` is called, e.g. in `packages/webdriver/src/command.ts` after the request was made.

Would you mind to take a stab at this and help us out? Please have a look into our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and if there are any questions I am happy to help out!

**Comment by RedMickey** [comment]
@christian-bromann, I started to fix this issue and found out that loggers use an interface from the external [`loglevel` ](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-logger/src/node.ts#L2)package. Could you please tell me which option is better?
- I can create an interface extending interfaces from the `loglevel` package and add there the `clearLogger` method (this could require some additional changes in the existing code)
```
loggers[name].clearLogger = () => {
    if (logFile) {
        logFile.end()
    }
    logFile = null
}
```

- Or I can add the `clearLogger` method the following way:
```
getLogger.clearLogger = () => {
    if (logFile) {
        logFile.end()
    }
    logFile = null
}
```

**Comment by christian-bromann** [comment]
@RedMickey I suggest the second approach.

**Comment by christian-bromann** [comment]
Let's continue convo in #6073
