### ISSUE TITLE
Issue with find-elements

### ISSUE THREAD

**Issue by suryap666** [webdriverio/webdriverio#6069]
I am trying to find elements in a generic method. I am chaining my XPath in various methods to form my elements like shown below.

![image](https://user-images.githubusercontent.com/36958912/98233775-9c7d5a80-1fb3-11eb-9e20-17ce441bf3a1.png)

command 1: $(`//div[@id='portfolio-list-app']`).$(`//table`).$(`//tbody`).$(`//tr[1] //td`)
command 2: $(`//div[@id='portfolio-list-app']`).$(`//table`).$(`//tbody`).$$(`//tr`)[0].$$(`//td`)

I am expecting these two commands to do the same things.

![image](https://user-images.githubusercontent.com/36958912/98233975-de0e0580-1fb3-11eb-8500-91f0f59e14d6.png)

Bug:
The second command gives 308 elements, but the first one gives around 14.
The second command should work exactly like the first one, that is the result for the second command should also be 14. Please correct me if I am wrong.

My version details

"devDependencies": {
    "@types/mocha": "^8.0.3",
    "@wdio/allure-reporter": "^6.7.2",
    "@wdio/cli": "^6.7.2",
    "@wdio/local-runner": "^6.7.2",
    "@wdio/mocha-framework": "^6.7.0",
    "@wdio/selenium-standalone-service": "^6.6.5",
    "@wdio/spec-reporter": "^6.7.0",
    "@wdio/sync": "^6.7.2",
    "chromedriver": "^86.0.0",
    "del-cli": "^3.0.1",
    "ts-node": "^9.0.0",
    "typescript": "^4.0.5",
    "wdio-chromedriver-service": "^6.0.4",
    "wdio-mochawesome-reporter": "^4.0.0",
    "wdio-video-reporter": "^3.1.1"
  },
  "dependencies": {
    "@types/chai": "^4.2.14",
    "@types/webdriverio": "^5.0.0",
    "allure-commandline": "^2.13.0",
    "chai": "^4.2.0"
  }

**Comment by BorisOsipov** [comment]
@suryap666 your chaining is incorrect. From docs `

// | Selects nodes in the document from the current node that match the selection no matter where they are
-- | --
`
If you don't set `current node` it will be whole document. Use dot `.` to set current node.

`$(//div[@id='portfolio-list-app']).$(.//table).$(.//tbody)` and so one
