### ISSUE TITLE
scrollIntoView not working as expected

### ISSUE THREAD

**Issue by mw29535** [webdriverio/webdriverio#6072]
Hello, 
I am testing in a QA environment, and I'm trying to have wdio scroll to an element by using scrollIntoView(). However, scrollIntoView doesn't work unless it is used twice.

Environment:
 - Mode: WDIO Testrunner
 - WDIO Testrunner - running sync v6.5.2
 - Node.js version: 10.16.3
 - NPM version:  6.9.0
 - Browser name and version:  Chrome 86
 - Platform name and version: Windows 10

**Describe the bug**
WebdriverIO does not execute the scrollIntoView function. It needs to be called twice to work

**Expected behavior**
The browser should scroll down without needing to call scrollintoview twice.

![image](https://user-images.githubusercontent.com/69998734/98298353-7b991300-1f7b-11eb-8ef8-98533bacb990.png)

**Comment by christian-bromann** [comment]
@mw29535 can you provide a reproducible example?

**Comment by mw29535** [comment]
it's in my company's QA environment

**Comment by christian-bromann** [comment]
I understand. To investigate this issue it is however necessary to provide such an example otherwise there is no chance for a fix unless you would like to help us out with one.

**Comment by mw29535** [comment]
not feasible at all, I'm sorry.

**Comment by christian-bromann** [comment]
Closing then. Please understand that we need to have a reproducible example to examine the issue.

**Comment by christian-bromann** [comment]
@mw29535 please note that I am not asking for your application that you are testing. I am asking for any arbitrary web app (maybe even self constructed) that reproduces the effect of `scrollIntoView` not working. It's like going to a mechanic and say "My car doesn't drive" and don't allow the mechanic to look into the car 😉

**Comment by zaper4life** [comment]
I voulunteer
