### ISSUE TITLE
Login to box.com not working on safari-webdriverio. "ERROR webdriver: Request failed with status 500 due to unknown error: unknown error"

### ISSUE THREAD

**Issue by suchitrak** [webdriverio/webdriverio#6077]
Steps to reproduce:

Clone the repo 
1. https://github.com/suchitrak/webdriverio
2. Execute npm run test

ERROR webdriver: Request failed with status 500 due to unknown error: unknown error

Environment:
MAC OS Catalina - 10.15.7
Safari 14

Steps to enable Safari:
https://developer.apple.com/documentation/webkit/testing_with_webdriver_in_safari
Follow the steps in above link 
1. safaridriver --enable
2. /usr/bin/safaridriver --port 4444

What is working:
1. The same above script works fine on chrome 
2. the other example scripts in the repo works fine on Safari 14 too.

ONLY the Login to Box.com is not working on Safari 14.  But Login to Box.com works fine when executed on browserstack that has Safari 13.

**Comment by christian-bromann** [comment]
@suchitrak does this work locally but not on BrowserStack?

**Comment by christian-bromann** [comment]
I don't think there is anything WebdriverIO can do if this use case stopped working in Safari v14. I recommend to file a bug in the Safaridriver project and let the devs know that the command is behaving differently. I don't think there is much we can do on the WebdriverIO side. Let me know if you have more questions.
