### ISSUE TITLE
Specification of Hub and port for remote running of test cases. [Test Runner]

### ISSUE THREAD

**Issue by mohdasif2294** [webdriverio/webdriverio#608]
How to specify the hub and port for running tests on browserstack and saucelabs ? And providing other configuration for the same. like local /remote host  and debug level .

**Comment by christian-bromann** [comment]
> How to specify the hub and port for running tests on browserstack and saucelabs ?

If you are using Sauce Labs, Browserstack or Testingbot you don't need to specify that, WebdriverIO figures that out according to your access key. See [here](https://github.com/webdriverio/webdriverio/blob/master/examples/wdio.conf.js#L3-L14)
