### ISSUE TITLE
Why Browser capabilities is mandatory to mention in config file for executing any case in webdriverIO v6?

### ISSUE THREAD

**Issue by nam81285** [webdriverio/webdriverio#6086]
Hi. I want to upgrade my wdio v from 4.8.0 to latest v6 andI have done all the changes and able to upgrade also. But my framework is an API test framework and I dnt need to invoke browser to run my script in wdio v 4. But in v6 its sayjng 0 specs wxecuted if I dnt add the browser capabilities to the config file. Why Browser capabilities is mandatory to mention in config file for executing any case in webdriverIO v6? I don't want to invoke or start a browser session. Please help me.

**Comment by christian-bromann** [comment]
> Why Browser capabilities is mandatory to mention in config file for executing any case in webdriverIO v6?

You should not use WebdriverIO if you do API testing and don't need a browser. Just use a normal test framework like Mocha or Jasmine directly.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by nam81285** [comment]
I understand but is there any option to switchoff the capabilities and do it for time being.

**Comment by christian-bromann** [comment]
> I understand but is there any option to switchoff the capabilities and do it for time being.

No. The WebdriverIO testrunner is not designed to test without a browser.
