### ISSUE TITLE
FirefoxOptions type definition requires debuggerAddress which produces org.openqa.selenium.InvalidArgumentException when set

### ISSUE THREAD

**Issue by nikita-pankratov** [webdriverio/webdriverio#6087]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 6.7.3]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [12.13.0]
 - **NPM version:** [6.12.0]
 - **Browser name and version:** [e.g. Chrome 68]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [@wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
within webdriver package, within the type definition file, "moz:firefoxOptions" now has the `debuggerAddress` field and its mandatory (look at code below). When set you receive the error shown below from in selenium-standalone service log.
```
export interface FirefoxOptions {
    debuggerAddress: string
    binary?: string
    args?: string[]
    profile?: string
    log?: FirefoxLogObject
    prefs?: {
        [name: string]: string | number | boolean
    }
}
```

```
17:56:29.508 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "acceptInsecureCerts": true,
  "browserName": "firefox",
  "moz:firefoxOptions": {
    "debuggerAddress": "localhost:65010",
    "args": [
      "-remote-debugging-port",
      "65010"
    ]
  }
}
17:56:29.510 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
17:56:29.713 INFO [ServicedSession$Factory.apply] - Invalid moz:firefoxOptions field debuggerAddress
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'SJCMAC1YZMD6R', ip: '2600:8801:c503:6200:9087:50cb:ef75:de6f%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '13.0.1'
Driver info: driver.version: unknown
remote stacktrace: 
org.openqa.selenium.InvalidArgumentException: Invalid moz:firefoxOptions field debuggerAddress
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'SJCMAC1YZMD6R', ip: '2600:8801:c503:6200:9087:50cb:ef75:de6f%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '13.0.1'
Driver info: driver.version: unknown
```

**To Reproduce**
all you need is to have a typed wdio.conf.ts and firefox capabilities which look something like this 
```
browserOptions = {
      "browserName": "firefox",
      "acceptInsecureCerts": true,
      "moz:firefoxOptions": {
        // debuggerAddress: "127.0.0.1:65010",
        args: determineBrowserSetupArgs(browserName),
      },
    }
```

**Expected behavior**
Not sure what is supposed to happen here. Initially I thought that debuggerAddress should not be mandatory for FirefoxOptions but after the selenium-standalone error I think it needs to be removed completely.

**Comment by christian-bromann** [comment]
@nikita-pankratov this property is definitely not required, feel free to raise a PR to make it optional. Cheers!
