### ISSUE TITLE
Unknown capability encountered: 'safariOptions' = '{     automaticInspection = 1; }'

### ISSUE THREAD

**Issue by suchitrak** [webdriverio/webdriverio#6088]
Steps to reproduce:

1. Clone the repo. -- `https://github.com/suchitrak/webdriverio`
2. On terminal run the following command `/usr/bin/safaridriver --port 4444`
3. Execute npm run test

Following error is displayed
ERROR @wdio/runner: Error: Failed to create session.
Unknown capability encountered: 'safariOptions' = '{
    automaticInspection = 1;
}'

Environment:
MAC OS Catalina - 10.15.7
Safari 14

Steps to enable Safari:
https://developer.apple.com/documentation/webkit/testing_with_webdriver_in_safari
Follow the steps in above link

Documentation on the safarioption ``automaticinspection` https://www.selenium.dev/selenium/docs/api/rb/Selenium/WebDriver/Safari/Options.html
https://developer.apple.com/documentation/webkit/about_webdriver_for_safari

safaridriver --enable
/usr/bin/safaridriver --port 4444
What is working:

The same above script works fine if ```
'safariOptions' = '{
    automaticInspection = 1;
}'
``` is removed

**Comment by christian-bromann** [comment]
@suchitrak feel free to add these types to the interfaces:

- https://github.com/webdriverio/webdriverio/blob/master/packages/webdriver/webdriver.d.ts#L322-L340
- https://github.com/webdriverio/webdriverio/blob/master/packages/webdriver/src/types.ts#L303-L326

**Comment by christian-bromann** [comment]
@suchitrak after taking a second look it seems that you've provided the wrong capabilities:

```js
'safariOptions' = {
    automaticInspection = 1;
}
```

According to the [Safaridriver](developer.apple.com/documentation/webkit/about_webdriver_for_safari) docs you need to set the caps as following:

```js
{
    browserName: 'safari'
    'safari:automaticInspection': ...
    'safari:automaticProfiling': ...
}
```

Let me know if you have any further questions.
