### ISSUE TITLE
Wdio Testrunner and browserstack

### ISSUE THREAD

**Issue by dhoulker** [webdriverio/webdriverio#609]
Hi,

I'm using the new wdio testrunner, and its great to be able to add multiple capabilities for the tests, but because they all run in parallel my browser stack license doesn't let me run the tests.

Is there anyway to be able to run them in series?

Thanks,

Dave

**Comment by christian-bromann** [comment]
Hi @dhoulker 
unfortunately not. You could make a config file for each capability (maybe have a main config file and inherit form that) and run your test command like:

```sh
$ wdio conf1.js && wdio conf2.js && wdio conf3.js ...
```

We will improve the way how to deal with capabilities with the next major release.

**Comment by dhoulker** [comment]
Cool, i'll try that thanks Christian

**Comment by gerbil** [comment]
Any updates for 'the way how to deal with capabilities with the next major release' ?

**Comment by christian-bromann** [comment]
@gerbil you can limit that using [`maxInstances`](https://github.com/webdriverio/webdriverio/blob/master/examples/wdio.conf.js#L52-L60) property in your wdio.conf.js

**Comment by gerbil** [comment]
it's not working properly. I'm using grunt-webdriver (using webdriverio by default as local module), in my conf.js maxInstances is just ignored!
