### ISSUE TITLE
Globals on wdio.conf no longer recognized after jasmine upgrade

### ISSUE THREAD

**Issue by luiscspinho** [webdriverio/webdriverio#6091]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [6.7.3]
 - **Mode:** [Standalone mode]
 - **Node.js version:** [12.8.0]
 - **NPM version:** [6.10.2]
 - **Browser name and version:** [Chrome 86]
 - **Additional wdio packages used (if applicable):** [@wdio/jasmine-framework]

**Describe the bug**
After the @wdio/jasmine-framework upgrade from 6.7.0 to 6.7.1, all the global variables present on the wdio.conf (`before` hook, for example) are no longer reachable. Not sure, but might be related to https://github.com/jasmine/jasmine-npm/blob/main/release_notes/3.6.1.md ?

**To Reproduce**
For example, override the `global.$` for something, and then access `$` on a different file (a page object, for example)

**Expected behavior**
I would expect that my variable is still  accessible.

**Comment by christian-bromann** [comment]
> Not sure, but might be related to [https://github.com/jasmine/jasmine-npm/blob/main/release_notes/3.6.1.md](https://github.com/jasmine/jasmine-npm/blob/main/release_notes/3.6.1.md?rgh-link-date=2020-11-11T14%3A45%3A38Z) ?

Probably not. I just ran a boilerplate project:

```sh
mkdir test
cd test
npm i @wdio/cli
npx wdio config
# select jasmine
npx wdio
```

passes correctly. This seems to be an issue with your setup. Happy to re-open if you can provide a reproducible example that shows it is indeed an issue in WebdriverIO.
