### ISSUE TITLE
browser.deleteCookies() does not appear to be working in Safari

### ISSUE THREAD

**Issue by Emmet-McGuire** [webdriverio/webdriverio#6095]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.7.2
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.18.1
 - **NPM version:** 6.14.5
 - **Browser name and version:** Safari 13
 - **Platform name and version:** Mac OS 10.15
 - **Additional wdio packages used (if applicable):** 
    "@wdio/cli": "^6.7.2",
    "@wdio/cucumber-framework": "^6.7.0",
    "@wdio/local-runner": "^6.7.2",
    "@wdio/mocha-framework": "^6.7.0",
    "@wdio/sauce-service": "^6.7.2",
    "@wdio/spec-reporter": "^6.7.0",
    "@wdio/sync": "^6.7.2"

**Config of WebdriverIO**

- Basic configuration file using Cucumber

- Uses Saucelabs for running tests (`services: ['sauce']`)

- The following hook:

```
afterScenario: function (uri, feature, scenario, result, sourceLocation) {

        const beforeCookies = browser.getCookies();
        console.log("Cookies BEFORE delete: " + beforeCookies);

        browser.deleteCookies();

        const afterCookies = browser.getCookies();
        console.log("Cookies AFTER delete: " + afterCookies);
}
```

**Describe the bug**
When using `browser.deleteCookies();` for multiple browsers (running in Saucelabs), it correctly deletes the cookies in Chrome, Firefox and Edge, but not in Safari.  In Safari, it doesn't appear to delete any cookies.

When the following afterScenario hook is executed, see the results in Chrome and Safari:

```
afterScenario: function (uri, feature, scenario, result, sourceLocation) {

        const beforeCookies = browser.getCookies();
        console.log("Cookies BEFORE delete: " + beforeCookies);

        browser.deleteCookies();

        const afterCookies = browser.getCookies();
        console.log("Cookies AFTER delete: " + afterCookies);
}
```

```
// Chrome Result
[1-1] Cookies BEFORE delete: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
[1-1] Cookies AFTER delete: 

// Safari Result
[0-1] Cookies BEFORE delete: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
[0-1] Cookies AFTER delete: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
```

**To Reproduce**

* In a Test (or a hook before/after a test), run the following:

```
browser.url('https://www.google.com/');

const beforeCookies = browser.getCookies();
console.log("Cookies BEFORE delete: " + beforeCookies);

browser.deleteCookies();

const afterCookies = browser.getCookies();
console.log("Cookies AFTER delete: " + afterCookies);
```
* Execute in Safari & Chrome and you will see the resulting logging from after the delete will be different

**Expected behavior**
What *should* happen is that the cookies are deleted, and the second console.log doesn't list any cookies (as defined in https://webdriver.io/docs/api/browser/deleteCookies.html )

**Log**

**Additional context**

**Comment by christian-bromann** [comment]
@Emmet-McGuire thanks for filing the issue. Unfortunately this is a Safari limitation as it stores cookie on OS level rather than within a specific browser session. There is nothing WebdriverIO can do about this. Closing.
