### ISSUE TITLE
Add print protocol command

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#6096]
There has been a new command for printing websites through PDF added to the spec which we should add to our [protocol bindings](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-protocols/protocols/webdriver.json). The command should be added there. You can find more information on typings in this [Selenium PR](https://github.com/SeleniumHQ/selenium/pull/8597/files).

**Comment by zachlysobey** [comment]
I'd consider taking a stab at this one. I'll do a little exploration later this evening and check back with any questions.
But also, if someone else is eager to pick this up, feel free. I can take a back seat and lend some 👀 to any PRs, etc..

**Comment by christian-bromann** [comment]
Thank you @zachlysobey , I assigned it to you but happy to re-assign if someone else feels more eager. Let me know if you have any questions, should be just a simple change in the json file.

Ah I forgot, if you don't mind we should also add the protocol in the `devtools` package, implemented with Puppeteer. If you haven't worked with Puppeteer yet we can also make this a second issue.

**Comment by zachlysobey** [comment]
@christian-bromann I took a stab at it. I'm sure it needs some work.

**Comment by christian-bromann** [comment]
Thank you @zachlysobey , I approved the PR. There are two tasks left with this one:

- add a Puppeteer implementation by adding a `printPage.js` to [this directory](https://github.com/webdriverio/webdriverio/tree/master/packages/devtools/src/commands) implementing the protocol command with Puppeteer using the [`Page.pdf()`](https://pptr.dev/#?product=Puppeteer&version=v5.4.1&show=api-pagepdfoptions) interface. The options are identical to the protocol command so you just need to pass them along. This one requires a little e2e test which we have located [here](https://github.com/webdriverio/webdriverio/blob/master/e2e/protocol.test.js). That test only needs to call the command and check of the response is a string (asserting the PDF seems a bit overkill).
- I suggest to also add a helper method to the WebdriverIO interface to easier use this protocol command. Similar to the [`saveScreenshot`](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/commands/browser/saveScreenshot.ts) command we should add a `savePDF` command that allows to store the PDF directly as a file.

Would you be up to tackle the last two tasks as well? Happy to assist!

**Comment by Maxgit3** [comment]
do you need any help with this task?

**Comment by christian-bromann** [comment]
@Maxgit3 absolutely, I created #6120 and #6121. Feel free to claim one issue for you. Will close this ticket.

**Comment by Maxgit3** [comment]
> @Maxgit3 absolutely, I created #6120 and #6121. Feel free to claim one issue for you. Will close this ticket.

Thank you.  I can look into #6120
