### ISSUE TITLE
Delete and search file in folder with WebdriverIO

### ISSUE THREAD

**Issue by achandra31** [webdriverio/webdriverio#610]
Hi Chris,
Do you have an example to search and delete a file in the folder using WebDriverIO?
I need to search a file that contains "import00-" name and delete it.

Thanks,
Agus Wicaksana

**Comment by christian-bromann** [comment]
Hi @achandra31,

you mean search a file on your system (using node) and delete it? I don't see how that relates to WebdriverIO

**Comment by achandra31** [comment]
Hi Chris,
Sorry, I'm still new with webdriverIO and nodeJS thing...
In my previous thread, I saw the uploading file using WebDriverIO, that's why I thought the search and delete is still related with it.

Thanks for your quick response.

**Comment by christian-bromann** [comment]
I would recommend to use the glob npm package for searching files on your system. For deleting them you can just use the fs module.

**Comment by achandra31** [comment]
Thanks
