### ISSUE TITLE
Broken `View Source` & `Improve this doc` links in doc pages

### ISSUE THREAD

**Issue by zachlysobey** [webdriverio/webdriverio#6101]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [ ] Missing documentation
- [x] Other

**Description of the improvement / report**

The wdio doc pages `View Source` & `Improve this doc` buttons seem to be broken across the board.
Looks like they point to some *pre-monorepo* code?

For example

> http://v4.webdriver.io/api/action/click.html

points at:

> https://github.com/webdriverio/webdriverio/blob/master/lib/commands/click.js

Where it probably *should* instead be:

> https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/commands/element/click.js

NOTE: *I may take a stab at tracking down and resolving this issue myself. But I wanted to report it before I forgot*

**Comment by zachlysobey** [comment]
on second glance, it seems where I'm getting tripped up is that I'm selecting "latest" from the API, but its actually *not* giving me the docs for the latest (6.x). It's giving docs for 4.x.

I'm going to leave this up for now to remind myself to follow up; but feel free to close.

**Comment by christian-bromann** [comment]
@zachlysobey thanks for creating the issue. As we have deprecated v4 we don't really maintain the docs anymore either. It is just there for people who still use it but we don't think it is valuable to improve these docs. Therefor I am gonna close this. Let me know if you have any more questions.
