### ISSUE TITLE
Skip a test 

### ISSUE THREAD

**Issue by dhoulker** [webdriverio/webdriverio#611]
Hi,

It used to be possible to skip a misbeahaving test with the following code

it.skip('Should be a test i want to skip')

http://mochajs.org/#inclusive-tests

This now returns ERROR: Undefined is not a function.

Not an urgent one, but it was a much cleaner method than simply commenting tests out.

Thanks,

Dave

**Comment by christian-bromann** [comment]
fixed and published with `v3.0.5`
Thanks for reporting

**Comment by dhoulker** [comment]
:) Thank you!
