### ISSUE TITLE
SauceLabs protocol not working

### ISSUE THREAD

**Issue by ergbouncex** [webdriverio/webdriverio#6110]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.7.3
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v14.15.0
 - **NPM version:** 6.14.8
 - **Browser name and version:** Chrome Latest
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** n/a

**Config of WebdriverIO**
Default config from the cli wit the addition of:
```
    user: xxx,
    key: xxx,
    region: 'us',
    services: [
        ['sauce', {
            setJobNameInBeforeSuite: true
        }],
    ],
```

**Describe the bug**
None of the SauceLabs protocol commands are working while running in SauceLabs. When I tried the commands directly with browser.execute, as in the saucelab docs, it works fine. An example error is:
```
[0-0] TypeError in "webdriver.io page should have browser.getLogs"
TypeError: browser.getPageLogs is not a function
```

**To Reproduce**
Run a simple test in SauceLabs and try any of the SauceLabs protocol commands. For example. 

```
describe('webdriver.io page', () => {
   it('should have browser.getLogs', () => {
        browser.url('https://www.selenium.dev')
        const network = browser.getPageLogs('sauce:network')
        console.log(network);
    })
})
```

**Expected behavior**
I expect to see an object with all of the network calls. However, I only get an error: 
```
[0-0] TypeError in "webdriver.io page should have browser.getLogs"
TypeError: browser.getPageLogs is not a function
```

**Log**
If applicable, add logs to help explain your problem.
Here are the logs: [gist](https://gist.github.com/ergbouncex/435592240031e96cafa4cae97e54d936)

**Additional context**
This worked in older versions of wdio.

**Comment by christian-bromann** [comment]
@ergbouncex thanks for filing the issue and sorry for this regression. I have fixed it in #6111 and will do a release with that fix as soon as I get a review.
