### ISSUE TITLE
@wdio/sync not compatible with the latest node version(14.15.0)

### ISSUE THREAD

**Issue by alivelumula** [webdriverio/webdriverio#6113]
Hi Colleagues,

I am currently on WDIO V6.
@wdio/sync dependency is not compatible with the latest node version(14.15.0)
`“@wdio/sync”: "^6.7.3"`

For this ,we need to maintain node version to 12.19.0 currently which is the stable version.

Error while : npm i @wdio/sync on node version 14.15.0
```
gyp ERR! cwd C:\Users\......\Desktop\Learning\LatestPull_16thJuly\webdriver-io-e2e-tests\node_modules\fibers
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version
```

Need support here for the dependency update on latest node version.
Thank You in advance.

**Comment by christian-bromann** [comment]
I was running the project pipeline on Windows using Node v14.5 and [it passed](https://github.com/webdriverio/webdriverio/runs/1405841555) which proves to me that fibers works fine on Windows. Given your information I can't see any differences in both environments. Can you provide more information that can show that Fibers in indeed to supported for Windows on Node 14.5? From all sources I have it seems to work just fine.

**Comment by alivelumula** [comment]
Hello Christian,
Thank you for the quick reply.
Here is the log .Hope this helps

C:\Users\....\Desktop\Learning\LatestPull_16thJuly\webdriver-io-e2e-tests\node_modules\fibers>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --release ) 
gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:327:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:465:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\....\Desktop\Learning\LatestPull_16thJuly\webdriver-io-e2e-tests\node_modules\fibers
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'`
Alpine users please run: `sudo apk add python make g++`
'nodejs' is not recognized as an internal or external command,
operable program or batch file.
npm WARN webdriver-io-e2e-tests@0.0.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fibers@4.0.3 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@4.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\.....\AppData\Roaming\npm-cache\_logs\2020-11-10T04_45_02_465Z-debug.log

**Comment by christian-bromann** [comment]
> gyp ERR! find Python Python is not set from command line or npm configuration
> gyp ERR! find Python Python is not set from environment variable PYTHON

WebdriverIO requires to have Python installed on your system.

**Comment by amuttsch** [comment]
@christian-bromann  I have the same issue on Linux building fibers. I'm using node 14.15.1 on Arch Linux. I have `python` and the build tools installed. Am I missing sth. that needs to be installed? Thanks!

```
$ yarn             
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.0.7: The platform "linux" is incompatible with this module.
info "fsevents@2.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @wdio/mocha-framework@6.11.0" has unmet peer dependency "webdriverio@^6.0.1".
[4/4] Building fresh packages...
[1/2] ⢀ fibers
error /build/node_modules/fibers: Command failed.
Exit code: 127
Command: node build.js || nodejs build.js
Arguments: 
Directory: /build/node_modules/fibers
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.15.1 | linux | x64
gyp info find Python using Python version 3.9.1 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/home/user/.fnm/node-versions/v14.15.1/installation/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/build/node_modules/fibers/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/.fnm/node-versions/v14.15.1/installation/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/.cache/node-gyp/14.15.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/user/.cache/node-gyp/14.15.1',
gyp info spawn args   '-Dnode_gyp_dir=/home/user/.fnm/node-versions/v14.15.1/installation/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/user/.cache/node-gyp/14.15.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/build/node_modules/fibers',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/build/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc: In function 'void uni::SetAccessor(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, uni::FunctionType (*)(v8::Local<v8::String>, const GetterCallbackInfo&), void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const SetterCallbackInfo&))':
../src/fibers.cc:362:59: warning: cast between incompatible function types from 'uni::FunctionType (*)(v8::Local<v8::String>, const GetterCallbackInfo&)' {aka 'void (*)(v8::Local<v8::String>, const v8::PropertyCallbackInfo<v8::Value>&)'} to 'v8::AccessorNameGetterCallback' {aka 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)'} [-Wcast-function-type]
  362 |   object->SetAccessor(isolate->GetCurrentContext(), name, (AccessorNameGetterCallback)getter, (AccessorNameSetterCallback)setter).ToChecked();
      |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/fibers.cc:362:95: warning: cast between incompatible function types from 'void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const SetterCallbackInfo&)' {aka 'void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)'} to 'v8::AccessorNameSetterCallback' {aka 'void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)'} [-Wcast-function-type]
  362 |   object->SetAccessor(isolate->GetCurrentContext(), name, (AccessorNameGetterCallback)getter, (AccessorNameSetterCallback)setter).ToChecked();
      |                                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/fibers.cc: In static member function 'static void Fiber::Init(v8::Local<v8::Object>)':
../src/fibers.cc:899:32: error: no matching function for call to 'v8::Object::Set(v8::Local<v8::String>&, v8::Local<v8::Function>&)'
  899 |    target->Set(sym_yield, yield);
      |                                ^
In file included from /home/user/.cache/node-gyp/14.15.1/include/node/node.h:67,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:3670:37: note: candidate: 'v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)'
 3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:3673:37: note: candidate: 'v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)'
 3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
../src/fibers.cc:903:28: error: no matching function for call to 'v8::Function::Set(v8::Local<v8::String>&, v8::Local<v8::Function>&)'
  903 |    fn->Set(sym_yield, yield);
      |                            ^
In file included from /home/user/.cache/node-gyp/14.15.1/include/node/node.h:67,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:3670:37: note: candidate: 'v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)'
 3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:3673:37: note: candidate: 'v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)'
 3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
../src/fibers.cc:909:58: error: no matching function for call to 'v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::Function>&)'
  909 |    target->Set(uni::NewLatin1Symbol(isolate, "Fiber"), fn);
      |                                                          ^
In file included from /home/user/.cache/node-gyp/14.15.1/include/node/node.h:67,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:3670:37: note: candidate: 'v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)'
 3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:3673:37: note: candidate: 'v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)'
 3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
../src/fibers.cc: In function 'void init(v8::Local<v8::Object>)':
../src/fibers.cc:927:69: error: no matching function for call to 'v8::Object::Get(v8::Local<v8::String>)'
  927 |  if (did_init || !target->Get(uni::NewLatin1Symbol(isolate, "Fiber"))->IsUndefined()) {
      |                                                                     ^
In file included from /home/user/.cache/node-gyp/14.15.1/include/node/node.h:67,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:3717:43: note: candidate: 'v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)'
 3717 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
      |                                           ^~~
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:3717:43: note:   candidate expects 2 arguments, 1 provided
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:3720:43: note: candidate: 'v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)'
 3720 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
      |                                           ^~~
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:3720:43: note:   candidate expects 2 arguments, 1 provided
In file included from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
../src/fibers.cc: At global scope:
/home/user/.cache/node-gyp/14.15.1/include/node/node.h:758:7: warning: cast between incompatible function types from 'void (*)(v8::Local<v8::Object>)' to 'node::addon_register_func' {aka 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)'} [-Wcast-function-type]
  758 |       (node::addon_register_func) (regfunc),                          \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user/.cache/node-gyp/14.15.1/include/node/node.h:792:3: note: in expansion of macro 'NODE_MODULE_X'
  792 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/fibers.cc:940:1: note: in expansion of macro 'NODE_MODULE'
  940 | NODE_MODULE(fibers, init)
      | ^~~~~~~~~~~
../src/fibers.cc: In instantiation of 'void uni::Return(v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, uni::GetterCallbackInfo) [with T = v8::Object; uni::GetterCallbackInfo = v8::PropertyCallbackInfo<v8::Value>]':
../src/fibers.cc:838:45:   required from here
../src/fibers.cc:206:28: error: no matching function for call to 'v8::ReturnValue<v8::Value>::Set(v8::Persistent<v8::Object>&)'
  206 |   info.GetReturnValue().Set(handle);
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
In file included from /home/user/.cache/node-gyp/14.15.1/include/node/node.h:67,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:4220:18: note: candidate: 'template<class S> void v8::ReturnValue<T>::Set(const v8::Global<S>&) [with S = S; T = v8::Value]'
 4220 |   V8_INLINE void Set(const Global<S>& handle);
      |                  ^~~
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:4220:18: note:   template argument deduction/substitution failed:
../src/fibers.cc:206:28: note:   'v8::Persistent<v8::Object>' is not derived from 'const v8::Global<T>'
  206 |   info.GetReturnValue().Set(handle);
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
In file included from /home/user/.cache/node-gyp/14.15.1/include/node/node.h:67,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:4222:18: note: candidate: 'template<class S> void v8::ReturnValue<T>::Set(const v8::TracedReferenceBase<S>&) [with S = S; T = v8::Value]'
 4222 |   V8_INLINE void Set(const TracedReferenceBase<S>& handle);
      |                  ^~~
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:4222:18: note:   template argument deduction/substitution failed:
../src/fibers.cc:206:28: note:   'v8::Persistent<v8::Object>' is not derived from 'const v8::TracedReferenceBase<T>'
  206 |   info.GetReturnValue().Set(handle);
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
In file included from /home/user/.cache/node-gyp/14.15.1/include/node/node.h:67,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:4224:18: note: candidate: 'template<class S> void v8::ReturnValue<T>::Set(v8::Local<S>) [with S = S; T = v8::Value]'
 4224 |   V8_INLINE void Set(const Local<S> handle);
      |                  ^~~
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:4224:18: note:   template argument deduction/substitution failed:
../src/fibers.cc:206:28: note:   'v8::Persistent<v8::Object>' is not derived from 'v8::Local<T>'
  206 |   info.GetReturnValue().Set(handle);
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
In file included from /home/user/.cache/node-gyp/14.15.1/include/node/node.h:67,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:11142:6: note: candidate: 'void v8::ReturnValue<T>::Set(bool) [with T = v8::Value]'
11142 | void ReturnValue<T>::Set(bool value) {
      |      ^~~~~~~~~~~~~~
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:11142:31: note:   no known conversion for argument 1 from 'v8::Persistent<v8::Object>' to 'bool'
11142 | void ReturnValue<T>::Set(bool value) {
      |                          ~~~~~^~~~~
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:11113:6: note: candidate: 'void v8::ReturnValue<T>::Set(double) [with T = v8::Value]'
11113 | void ReturnValue<T>::Set(double i) {
      |      ^~~~~~~~~~~~~~
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:11113:33: note:   no known conversion for argument 1 from 'v8::Persistent<v8::Object>' to 'double'
11113 | void ReturnValue<T>::Set(double i) {
      |                          ~~~~~~~^
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:11119:6: note: candidate: 'void v8::ReturnValue<T>::Set(int32_t) [with T = v8::Value; int32_t = int]'
11119 | void ReturnValue<T>::Set(int32_t i) {
      |      ^~~~~~~~~~~~~~
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:11119:34: note:   no known conversion for argument 1 from 'v8::Persistent<v8::Object>' to 'int32_t' {aka 'int'}
11119 | void ReturnValue<T>::Set(int32_t i) {
      |                          ~~~~~~~~^
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:11130:6: note: candidate: 'void v8::ReturnValue<T>::Set(uint32_t) [with T = v8::Value; uint32_t = unsigned int]'
11130 | void ReturnValue<T>::Set(uint32_t i) {
      |      ^~~~~~~~~~~~~~
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:11130:35: note:   no known conversion for argument 1 from 'v8::Persistent<v8::Object>' to 'uint32_t' {aka 'unsigned int'}
11130 | void ReturnValue<T>::Set(uint32_t i) {
      |                          ~~~~~~~~~^
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:4239:18: note: candidate: 'template<class S> void v8::ReturnValue<T>::Set(S*) [with S = S; T = v8::Value]'
 4239 |   V8_INLINE void Set(S* whatever);
      |                  ^~~
/home/user/.cache/node-gyp/14.15.1/include/node/v8.h:4239:18: note:   template argument deduction/substitution failed:
../src/fibers.cc:206:28: note:   mismatched types 'S*' and 'v8::Persistent<v8::Object>'
  206 |   info.GetReturnValue().Set(handle);
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
make: *** [fibers.target.mk:123: Release/obj.target/fibers/src/fibers.o] Error 1
make: Leaving directory '/build/node_modules/fibers/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/.fnm/node-versions/v14.15.1/installation/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.10.6-arch1-1
gyp ERR! command "/home/user/.fnm/node-versions/v14.15.1/installation/bin/node" "/home/user/.fnm/node-versions/v14.15.1/installation/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /build/node_modules/fibers
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
Alpine users please run: `sudo apk add python make g++```

**Comment by JopPobs11** [comment]
Hi cristian, i found same error but it my case there is message to set visual studio to new updates. But i already update my visual studio and still get error when install @wdio/sync

This is the error : 
PS C:\JoData\1_Project\Project_BDD\mobile-automation-appium> npm i @wdio/sync
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@wdio/sync@7.27.0',
npm WARN EBADENGINE   required: { node: '>=12.0.0 <16' },
npm WARN EBADENGINE   current: { node: 'v18.16.0', npm: '9.6.7' }
npm WARN EBADENGINE }
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\JoData\\1_Project\\Project_BDD\\mobile-automation-appium\\node_modules\\@wdio\\sync',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\JoData\1_Project\Project_BDD\mobile-automation-appium\node_modules\@wdio\sync\node_modules\webdriverio'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\JoData\\1_Project\\Project_BDD\\mobile-automation-appium\\node_modules\\@wdio\\sync\\node_modules\\webdriverio'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\JoData\\1_Project\\Project_BDD\\mobile-automation-appium\\node_modules\\@wdio\\sync\\node_modules',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\JoData\1_Project\Project_BDD\mobile-automation-appium\node_modules\@wdio\sync\node_modules\puppeteer-core\lib\cjs\puppeteer'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\JoData\\1_Project\\Project_BDD\\mobile-automation-appium\\node_modules\\@wdio\\sync\\node_modules\\puppeteer-core\\lib\\cjs\\puppeteer'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\JoData\1_Project\Project_BDD\mobile-automation-appium\node_modules\fibers
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node build.js || nodejs build.js
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@18.16.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.11 found at "C:\Users\Jonatan_118465\AppData\Local\Programs\Python\Python310\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\Jonatan_118465\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at C:\Users\Jonatan_118465\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\Jonatan_118465\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:369:14)
npm ERR! gyp ERR! stack     at C:\Users\Jonatan_118465\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at C:\Users\Jonatan_118465\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:390:16
npm ERR! gyp ERR! stack     at C:\Users\Jonatan_118465\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Users\Jonatan_118465\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16        
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:427:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Jonatan_118465\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
npm ERR! gyp ERR! cwd C:\JoData\1_Project\Project_BDD\mobile-automation-appium\node_modules\fibers
npm ERR! gyp ERR! node -v v18.16.0
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok
npm ERR! node-gyp exited with code: 1
npm ERR! Please make sure you are using a supported platform and node version. If you
npm ERR! would like to compile fibers on this machine please make sure you have setup your
npm ERR! build environment--
npm ERR! Windows + OS X instructions here: https://github.com/nodejs/node-gyp
npm ERR! Ubuntu users please run: `sudo apt-get install g++ build-essential`
npm ERR! RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'`
npm ERR! Alpine users please run: `sudo apk add python make g++`
npm ERR! 'nodejs' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

npm ERR! A complete log of this run can be found in: C:\Users\Jonatan_118465\AppData\Local\npm-cache\_logs\2023-07-25T06_12_41_387Z-debug-0.log
