### ISSUE TITLE
Globals not getting set in Before Hook

### ISSUE THREAD

**Issue by ergbouncex** [webdriverio/webdriverio#6118]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.8.0
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v14.15.0
 - **NPM version:** 6.14.8
 - **Browser name and version:** Chrome Latest
 - **Platform name and version:** Windows 10

**Config of WebdriverIO**
```
	before(capabilities, specs) {
            global.SERVICE_ACCOUNT = process.env.SERVICE_ACCOUNT;
        }
```

**Describe the bug**
In prior versions I would set global vars (constants) in the before hook so in my tests I can reference them in `describe` blocks like,
```
describe('Some Test Here', function () {
    const db = setUp(SERVICE_ACCOUNT);

   it('tests something here, function() {
       const results = db.query('select stuff');
       ...
   });
});
```

However, I noticed that these globals are now undefined unless I reference them from within an `it` or set them in a `before` function within the test itself. 

**To Reproduce**

**Expected behavior**
I expect that globals set within a `before` hook in the main config will be accessible from within a `describe` block while using the mocha framework.

**Log**
```
[0-0]  Error:  Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
`browser` object has only `capabilities` and some flags like `isMobile`.
Helper files that use other `browser` commands have to be moved to `before` hook.
Spec file(s): /test/spec/sample.spec.js
Error: ReferenceError: SERVICE_ACCOUNT is not defined
```

**Additional context**
I would like to make sure this is not a regression since this used to work.

**Comment by christian-bromann** [comment]
@ergbouncex thanks for filing the issue. This has changed with v6. We now load files a bit earlier to check whether the framework is suppose to run this file or not. I don't think this needs to be a show stopper for you as you can just do:

```js
describe('Some Test Here', function () {
   let db = null

   beforeAll(() => {
       db = setUp(SERVICE_ACCOUNT);
   })

   it('tests something here, function() {
       const results = db.query('select stuff');
       ...
   });
});
```

I don't see a scenario where someone would need to run async code before the test file is being loaded. If you see a need for this please elaborate. Otherwise I will close this issue. Happy to assist for any more questions. Cheers!
