### ISSUE TITLE
`before` hook executed after `describe` block in test

### ISSUE THREAD

**Issue by benbcai** [webdriverio/webdriverio#6119]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.8.0
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.16.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Chrome 86.0.4240.198
 - **Platform name and version:** MacOS Catalina (10.15.4)
 - **Additional wdio packages used (if applicable):** @wdio/local-runner, @wdio/mocha-framework, @wdio/sync, @wdio/spec-reporter

**Config of WebdriverIO**
https://github.com/benbcai/sample-component-js/blob/master/wdio.conf.js

**Describe the bug**
According to this `before` hook [documentation](https://webdriver.io/docs/configurationfile.html) it is expected to be executed before test execution begins. However, it appears that the `describe` block in a webdriverio test is executed before the `before` hook`.

This can be demonstrated using this [example repository](https://github.com/benbcai/sample-component-js). Logging messages are added inside the `before` hook and throughout the test. Notice that the message inside the `before` hook is logged after the `describe` block.

There are some configurations I need to setup using the browser object before tests begin. Since the `before` hook is executed after the test begins, I'm unable to complete the configurations and setup custom commands.

WebdriverIO version 4 executes the `before` hook before the test begins. It appears this execution order has changed either in v5 or v6.

**To Reproduce**
1) Clone the [example repository](https://github.com/benbcai/sample-component-js).
2) Run `npm install`
3) Run `npm run test`
4) Examine the logged messages prefixed with `*********` that the `before` hook is executed after the test begins (after the `describe` block but before the `it` block).

**Expected behavior**
The `before` hook should be executed before test execution begins so that custom commands and configurations can be setup.

**Log**

```
//example-service.js
class ExampleService {
  before() {
    console.log('********* Executing "before" hook in Example Service *********');
  }
}
```

```
//example-spec.js
console.log('********* Outside "describe" block in test *********');
describe('describe block', () => {
  console.log('********* Inside "describe" block in test *********');
  it('should log message', () => {
    console.log('********* Inside "it" block in test *********');
  })
})
```

> ********* Outside "describe" block in test *********
> ********* Inside "describe" block in test *********
> ********* Executing "before" hook in Example Service *********
> ********* Inside "it" block in test *********

**Comment by christian-bromann** [comment]
> WebdriverIO version 4 executes the `before` hook before the test begins. It appears this execution order has changed either in v5 or v6.

This has indeed changed with v6. I added a PR to bring this functionality back (as part of the `beforeSession` hook), see #6122.

**Comment by benbcai** [comment]
@christian-bromann Thanks for getting the change made so quickly!

**Comment by benbcai** [comment]
@christian-bromann I pulled down the latest version and verified that it has the change you made but I'm still seeing the `before` hook being executed after the `describe` block. I noticed that your change moved up the `beforeSession` hook. Does that also move up the execution of the `before` hook?

**Comment by christian-bromann** [comment]
> Does that also move up the execution of the `before` hook?

No. You have to move your code into the `beforeSession` hook. Given that we want to validate whether to run the test file or not before we start the session we have to read the file, which means running describe blocks without executing hooks or tests.

**Comment by benbcai** [comment]
@christian-bromann We currently configure our custom commands in the `before` hook because this hook is where we have access the `browser` object. The `browser` object is undefined in the `beforeSession` hook so we're unable to move our custom command implementations from `before` to `beforeSession` .

One of our custom commands is to encapsulate the `describe` block by running the entire block against different form factors. This is the reason why we needed the `before` hook to be executed before running the `describe` blocks.

For webdriverio to validate whether or not to run the test file before starting the session, is it possible to just check for the _existence_ of the `describe` block as oppose to _executing_ it like what it currently does in v6?

**Comment by christian-bromann** [comment]
@benbcai you can still register your custom commands in the `before` hook. That hasn't changed. I just tried it and it works without problems.

**Comment by benbcai** [comment]
@christian-bromann I updated my [example project](https://github.com/benbcai/sample-component-js) to demonstrate my use case.

In the `before` hook I added the [describeWithFormFactors](https://github.com/benbcai/sample-component-js/blob/master/lib/example-service.js#L11-L23) custom command where there is a need to access the browser object. What this custom command does is that it iterates the `describe` block in the test for each given form factor provided. [This test](https://github.com/benbcai/sample-component-js/blob/master/test/wdio/example-spec.js#L2) illustrates how this custom command is used in place of `describe`.

It is true that custom commands can still be registered in the `before` hook. However, any such custom command can no longer be executed before or immediately after the describe block because at this point the custom commands have not yet been initialised in the before hook. Custom commands created in the `before` hook can only be used inside the `it` block where they are initialised at that point and this introduces limitations for using these custom commands.

If you run the example project, you will see an error indicating the `describeWithFormFactors` command is undefined. V4 provided the flexibility for my use case. However, I can no longer do the same when using V6.

**Comment by christian-bromann** [comment]
You can still have in your tests. Just read `formFactors` from a JSON file as synchronous operation, e.g.:

```js
const formFactors = require('./formFactor.json')

formFactors.forEach(formFactor => describe(`[${formFactor}]`, () => {
    before(() => {
        // Call global.browser.setWindowSize to set the form factor height and width.
    });

    describe(title, fn);

    after(() => {
        // Call global.browser.setWindowSize to restore to the original window size.
    });
}));
```

**Comment by benbcai** [comment]
@christian-bromann In production the `describeWithFormFactors` custom command allows our consumers to specify any form factor of their choice and can vary in each test. Besides, this custom command is just one of many custom commands we have.

**Comment by StephenEsser** [comment]
The describes within the spec file being executed/evaluated prior to the services/configuration `before` hook feels counter intuitive/out of sync for the testing lifecycle.

There doesn't appear to be a way to setup a global configuration that uses browser commands within the scope of an early executing describe. 

> No. You have to move your code into the beforeSession hook. Given that we want to validate whether to run the test file or not before we start the session we have to read the file, which means running describe blocks without executing hooks or tests.

Can you explain this process a little more to help us understand the intended nature of executing the describe blocks prior to setting up the service and running the tests?

**Comment by benbcai** [comment]
@christian-bromann Wanted to check if you have any more thoughts on this.
