### ISSUE TITLE
Add a `printPage` implementation for the `devtools` protocol

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#6120]
In #6102 we added a new WebDriver protocol command that allows to print pages via PDF. This should now be implemented in the `devtools` package to stay feature conform.

Add a Puppeteer implementation by adding a `printPage.js` to [this directory](https://github.com/webdriverio/webdriverio/tree/master/packages/devtools/src/commands) implementing the protocol command with Puppeteer using the [`Page.pdf()`](https://pptr.dev/#?product=Puppeteer&version=v5.4.1&show=api-pagepdfoptions) interface. The options are identical to the protocol command so you just need to pass them along. This one requires a little e2e test which we have located [here](https://github.com/webdriverio/webdriverio/blob/master/e2e/protocol.test.js). That test only needs to call the command and check of the response is a string (asserting the PDF seems a bit overkill).

**Comment by Maxgit3** [comment]
> @Maxgit3 absolutely, I created #6120 and #6121. Feel free to claim one issue for you. Will close this ticket.

Thank you.  I can look into #6120

**Comment by Maxgit3** [comment]
I am running into an issue running the "setup-full" script in the package json file.  

> packages/wdio-logger/src/node.ts(142,13): error TS2794: Expected 1 arguments, but got 0. Did you forget to include 'void' in your type argument to 'Promise'?
error TS2688: Cannot find type definition file for '@wdio/cucumber-framework'.
error TS2688: Cannot find type definition file for 'webdriver'.
error TS2688: Cannot find type definition file for 'webdriverio'.
error TS2688: Cannot find type definition file for '@wdio/logger'.
error TS2688: Cannot find type definition file for 'webdriverio'.
error TS2318: Cannot find global type 'Array'.
error TS2318: Cannot find global type 'Boolean'.
error TS2318: Cannot find global type 'CallableFunction'.
error TS2318: Cannot find global type 'Function'.
error TS2318: Cannot find global type 'IArguments'.
error TS2318: Cannot find global type 'NewableFunction'.
error TS2318: Cannot find global type 'Number'.
error TS2318: Cannot find global type 'Object'.
error TS2318: Cannot find global type 'RegExp'.
error TS2318: Cannot find global type 'String'.
packages/wdio-repl/src/index.ts(36,57): error TS2307: Cannot find module '@wdio/utils' or its corresponding type declarations.
packages/webdriver/src/utils.ts(2,20): error TS2307: Cannot find module '@wdio/logger' or its corresponding type declarations.
packages/webdriver/src/request.ts(7,20): error TS2307: Cannot find module '@wdio/logger' or its corresponding type declarations.
packages/webdriver/src/request.ts(8,43): error TS2307: Cannot find module '@wdio/utils' or its corresponding type declarations.      
packages/webdriver/src/command.ts(1,20): error TS2307: Cannot find module '@wdio/logger' or its corresponding type declarations.     
packages/webdriver/src/command.ts(2,73): error TS2307: Cannot find module '@wdio/utils' or its corresponding type declarations.      
packages/webdriver/src/constants.ts(1,37): error TS2307: Cannot find module '@wdio/config' or its corresponding type declarations.   
packages/webdriver/src/constants.ts(111,19): error TS7006: Parameter 'requestOptions' implicitly has an 'any' type.
packages/webdriver/src/constants.ts(118,19): error TS7006: Parameter 'response' implicitly has an 'any' type.
packages/webdriver/src/index.ts(1,20): error TS2307: Cannot find module '@wdio/logger' or its corresponding type declarations.       
packages/webdriver/src/index.ts(3,60): error TS2307: Cannot find module '@wdio/utils' or its corresponding type declarations.        
packages/webdriver/src/index.ts(4,32): error TS2307: Cannot find module '@wdio/config' or its corresponding type declarations.

**Comment by christian-bromann** [comment]
@Maxgit3 I have no issues cloning the repository and setting things up: https://gist.github.com/christian-bromann/6b316bcd318e87480e77730dae1e0619

**Comment by Maxgit3** [comment]
Thanks got it working

**Comment by christian-bromann** [comment]
Let's continue convo in #6162
