### ISSUE TITLE
Add `savePDF` command to WebdriverIO package

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#6121]
In #6102 we added a new WebDriver protocol command that allows to print pages via PDF. This should now be implemented in `webdriverio` similar to `saveScreenshot to allow to directly store the pdf as file on the file system. Similar to the [`saveScreenshot`](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/commands/browser/saveScreenshot.ts) command we should add a `savePDF` command that allows to store the PDF directly as a file.

**Comment by NickR23** [comment]
Hello!
I'm having trouble with getting a base64 encoded string from the printPage protocol, I am getting back an object. 

```
    TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of ObjectTypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object

      34 | 
      35 |     const pdf = await this.printPage()
    > 36 |     const screenshot = Buffer.from(pdf, 'base64')
         |                               ^
      37 |     fs.writeFileSync(absoluteFilepath, screenshot)
      38 | 
      39 |     return screenshot

      at Browser.savePDF (packages/webdriverio/src/commands/browser/savePDF.ts:36:31)
      at Object.<anonymous> (packages/webdriverio/tests/commands/browser/savePDF.test.js:30:28)
```
The code snippet above is from my [savePDF.ts](https://github.com/NickR23/webdriverio/blob/savePDF/packages/webdriverio/src/commands/browser/savePDF.ts)
The printPage protocol says that it returns a base64 encoded string [here](https://github.com/NickR23/webdriverio/blob/338a600572519749717358b06ead89c0d5773ef7/packages/wdio-protocols/protocols/webdriver.json#L204)
I apologize if there is an obvious fix. This is my first open source contribution and I'm a bit overwhelmed!

Thank you!

**Comment by christian-bromann** [comment]
@NickR23 first off, thank you for looking into it, I will assign this ticket to you!

Can you check what the value `pdf` is? It doesn't seem to be a string as expected.

**Comment by NickR23** [comment]
![pdfObject](https://user-images.githubusercontent.com/29212540/99465174-c9acff80-2907-11eb-904e-1e96a197aa5a.png)
The object actually seems to be empty.

**Comment by christian-bromann** [comment]
@NickR23 Ah, I assume you are running Jest tests to validate the behavior. In this case you need to update the [got mock](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/tests/__mocks__/got.js) to return proper data.
