### ISSUE TITLE
browser.setTimeout() does not work on iOS simulators in SauceLabs

### ISSUE THREAD

**Issue by vijkris99** [webdriverio/webdriverio#6128]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment:**
 - **WebdriverIO version:** 6.7.0
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.14.1
 - **NPM version:** 6.13.4
 - **Browser name and version:** Safari (latest)
 - **Platform name and version:** iOS 13.4
 - **Additional wdio packages used (if applicable):** 
    "@wdio/cli": "^6.7.0",
    "@wdio/junit-reporter": "^6.7.0",
    "@wdio/local-runner": "^6.7.2",
    "@wdio/mocha-framework": "^6.7.0",
    "@wdio/sauce-service": "^6.7.2",
    "@wdio/spec-reporter": "^6.7.0",
    "@wdio/sync": "^6.7.2",

**Config of WebdriverIO**
```
const sauceOptions = {
  build: process.env.SAUCE_BUILD_NAME,
  "custom-data": {
    spa_name: "my-spa",
    spa_version: "1.0.3",
    commit: "0k392a9dkjr",
  },
};

exports.config = {
  runner: "local",
  outputDir: "./test-results",

  specs: ["./test/specs/**/mytest.js"],
  exclude: [
    // 'path/to/excluded/files'
  ],
  
  maxInstances: 1,
  capabilities: [
    {
      ...sauceOptions,
      maxInstances: 1,
      appiumVersion: "1.17.1",
      browserName: "Safari",
      platformName: "iOS",
      platformVersion: "13.4",
      deviceName: "iPhone Simulator",
      deviceOrientation: "portrait",
      acceptInsecureCerts: true,
    },
  ],

  logLevel: "info",
  bail: 0,
  baseUrl: "http://localhost:3000",

  waitforTimeout: 10000,
  connectionRetryTimeout: 120000,
  connectionRetryCount: 1,

  services: [
    [
      "sauce",
      {
        sauceConnect: true,
        sauceConnectOpts: {
          logfile: "./test-results/sauce-connect.log",
          verbose: 0, // Set 1 to enable for troubleshooting
        },
      },
    ],
  ],

  // SauceLabs credentials
  user: process.env.SAUCE_USERNAME,
  key: process.env.SAUCE_ACCESS_KEY,
  region: "us",

  framework: "mocha",
  mochaOpts: {
    ui: "bdd",
    timeout: 180000,
  },

  reporters: [
    "spec",
    [
      "junit",
      {
        outputDir: "./test-results/junit",
        outputFileFormat: function (options) {
          return `results-${options.cid}.${options.capabilities.browserName}.xml`;
        },
      },
    ],
  ],

  before: function (capabilities, specs) {
    browser.setTimeout({ pageLoad: 10000 }); // Fail if a page does not load within this time (ms)
    browser.setTimeout({ implicit: 5000 }); // Fail if an element is not found within this time (ms)
    require("expect-webdriverio").setOptions({ wait: 5000 }); // Wait until specified timeout for all assertions (ms)
  },
};
```

**Describe the bug**
`browser.setTimeout({ pageLoad: 10000 })` does not work when running tests against an iOS simulator on SauceLabs

**To Reproduce**
I set the timeout using a hook within `wdio.conf.js`, so the test code itself is immaterial. In any case, here is a simple example that I tried:
```
it("should have correct title", () => {
    browser.url("/");
    expect(browser).toHaveTitle("React App");
  });
```

**Expected behavior**
The browser timeouts are configured correctly

**Log**
Here is the error I see on SauceLabs:
```
HTTP Status: 400
1 "Parameters were incorrect. We wanted \"MJSONWP protocol requires type and ms\" and you sent {\"pageLoad\":10000}"
```
Note that this step does not actually fail the test, and there is no indication that there was an issue. I just happened to notice this by chance when I expanded the results of this step in SauceLabs. I was then able to reproduce this consistently. Also note that this works fine when running against desktop browsers on SauceLabs.

**Additional context**
None

**Comment by christian-bromann** [comment]
Thanks for filing the issue. This is an issue with Sauce Labs. I recommend to file a support ticket. There is nothing we can do in WebdriverIO to fix this.

**Comment by vijkris99** [comment]
Thanks for responding @christian-bromann! I already filed a support case and SauceLabs responded that it is probably a wdio issue and nothing at their end. I am going to check with them again and reference this ticket.
