### ISSUE TITLE
Unexpected logging error on iOS simulators in SauceLabs

### ISSUE THREAD

**Issue by vijkris99** [webdriverio/webdriverio#6130]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment:**
 - **WebdriverIO version:** 6.7.0
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.14.1
 - **NPM version:** 6.13.4
 - **Browser name and version:** Safari (latest)
 - **Platform name and version:** iOS 13.4
 - **Additional wdio packages used (if applicable):** 
    "@wdio/cli": "^6.7.0",
    "@wdio/junit-reporter": "^6.7.0",
    "@wdio/local-runner": "^6.7.2",
    "@wdio/mocha-framework": "^6.7.0",
    "@wdio/sauce-service": "^6.7.2",
    "@wdio/spec-reporter": "^6.7.0",
    "@wdio/sync": "^6.7.2",

**Config of WebdriverIO**
```
const sauceOptions = {
  build: process.env.SAUCE_BUILD_NAME,
  "custom-data": {
    spa_name: "my-spa",
    spa_version: "1.0.3",
    commit: "0k392a9dkjr",
  },
};

exports.config = {
  runner: "local",
  outputDir: "./test-results",

  specs: ["./test/specs/**/mytest.js"],
  exclude: [
    // 'path/to/excluded/files'
  ],
  
  maxInstances: 1,
  capabilities: [
    {
      ...sauceOptions,
      maxInstances: 1,
      appiumVersion: "1.17.1",
      browserName: "Safari",
      platformName: "iOS",
      platformVersion: "13.4",
      deviceName: "iPhone Simulator",
      deviceOrientation: "portrait",
      acceptInsecureCerts: true,
    },
  ],

  logLevel: "info",
  bail: 0,
  baseUrl: "http://localhost:3000",

  waitforTimeout: 10000,
  connectionRetryTimeout: 120000,
  connectionRetryCount: 1,

  services: [
    [
      "sauce",
      {
        sauceConnect: true,
        sauceConnectOpts: {
          logfile: "./test-results/sauce-connect.log",
          verbose: 0, // Set 1 to enable for troubleshooting
        },
      },
    ],
  ],

  // SauceLabs credentials
  user: process.env.SAUCE_USERNAME,
  key: process.env.SAUCE_ACCESS_KEY,
  region: "us",

  framework: "mocha",
  mochaOpts: {
    ui: "bdd",
    timeout: 180000,
  },

  reporters: [
    "spec",
    [
      "junit",
      {
        outputDir: "./test-results/junit",
        outputFileFormat: function (options) {
          return `results-${options.cid}.${options.capabilities.browserName}.xml`;
        },
      },
    ],
  ],

  before: function (capabilities, specs) {
    browser.setTimeout({ pageLoad: 10000 }); // Fail if a page does not load within this time (ms)
    browser.setTimeout({ implicit: 5000 }); // Fail if an element is not found within this time (ms)
    require("expect-webdriverio").setOptions({ wait: 5000 }); // Wait until specified timeout for all assertions (ms)
  },
};
```

**Describe the bug**
At the very end of each test, wdio seems to execute a `POST log` command with a payload of `{ "type": "performance" }` while running against an iOS simulator on SauceLabs. This leads to an error on the test logs, although the test itself seems to pass overall.
Note that the test script itself does not contain this logging statement - it seems to be automatically executed by wdio. Also note that this error does not occur while running the same test against a desktop browser on SauceLabs.

**To Reproduce**
The log statement seems to be internal to wdio, so the test code itself is immaterial. In any case, here is a simple example that I tried:
```
it("should have correct title", () => {
    browser.url("/");
    expect(browser).toHaveTitle("React App");
  });
```

**Expected behavior**
The test runs fine without any errors

**Log**
Here is the error I see on SauceLabs:
```
HTTP Status: 500
1 {
2	"message": "An unknown server-side error occurred while processing the command. Original error: No logs of type 'performance' found."
3 }
```
As mentioned earlier, this error does not fail the test itself. It also does not happen while running against desktop browsers on SauceLabs.

**Additional context**
I noticed a `GET log/types` command getting fired just before the step that causes this error. This also seems to be internal to wdio, and resulted in the following response on SauceLabs:
```
HTTP Status: 200
1 [
2	"syslog",
3	"crashlog",
4	"performance",
5	"server",
6	"safariConsole",
7	"safariNetwork"
8 ]
```
This was followed by 6 POST log commands, with all of them passing except for the one with "performance" in the payload. SauceLabs does not support performance testing on iOS, which is the probable cause of this error.

**Comment by christian-bromann** [comment]
> No logs of type 'performance' found.

These types of logs are only available if you run `extendedDebugging` with `performanceEnabled`. Also it is only supported on Chrome.

**Comment by vijkris99** [comment]
Thanks for responding @christian-bromann! I already filed a support case and SauceLabs responded that it is probably a wdio issue and nothing at their end. I am going to check with them again and reference this ticket.

**Comment by TheTeejers** [comment]
@christian-bromann This is an error that can be reproduced locally. Enrique was able to reproduce this outside of Sauce Labs.
