### ISSUE TITLE
getting typescript error when creating a test

### ISSUE THREAD

**Issue by ravi005e** [webdriverio/webdriverio#6137]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [6.9.0]
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [12.18.4]
 - **NPM version:** [6.14.6]
 - **Browser name and version:** [Chrome 70]
 - **Platform name and version:** [Windows 10]
 - **Additional wdio packages used (if applicable):** [typescript]

vscode shows error, see attached video

**Expected behavior**
there should be a way to access the browser instance

[2020-11-19_20-28-57.zip](https://github.com/webdriverio/webdriverio/files/5571259/2020-11-19_20-28-57.zip)

**Comment by christian-bromann** [comment]
@ravi005e the browser object is not passed in as argument in the describe callback. I recommend to have a look into [the docs](https://webdriver.io/docs/gettingstarted.html) and check out our [TypeScript boilerplates](https://webdriver.io/docs/boilerplate.html).

**Comment by ravi005e** [comment]
I disagree with your decision, all the examples I have seen none use coding rules as restricted as I do

**Comment by christian-bromann** [comment]
@ravi005e if you could describe your typescript issue a bit more detailed I could maybe give a better answer to what is happening but you provided almost no details which makes it hard to make any assumptions.

**Comment by ravi005e** [comment]
Please d/l attached zip file, unzip cd to unzipped folder
at terminal type> npm install
open in vscode with eslinter plugin
see specs folder, and mouse over as shown in the video, this will recreate the situation as I'm experiencing
[wdio_framework-jasmine.zip](https://github.com/webdriverio/webdriverio/files/5578323/wdio_framework-jasmine.zip)
