### ISSUE TITLE
wdio failing to use specified version

### ISSUE THREAD

**Issue by mw29535** [webdriverio/webdriverio#6142]
**Environment (please complete the following information):**
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.16.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Chrome 85.0.4183.87
 - **Platform name and version:** MacOS Big SUR
 - **Additional wdio packages used (if applicable):** @wdio/selenium-standalone service 6.9.0

['selenium-standalone',{ 
            logPath: "logs",
            installArgs: {
                version : "3.141.59",
                baseURL : "https://selenium-release.storage.googleapis.com",
                drivers : {
                    chrome : {
                        version : "85.0.4183.87",
                        arch    : process.arch,
                        baseURL : "https://chromedriver.storage.googleapis.com",
                    }
                }
            },
            args: {
                drivers: {
                    chrome: {
                        version: "85.0.4183.87",
                        arch: process.arch,
                    },
                }
            },
    }]],

**Describe the bug**
As listed above, those are the settings I am using for services. I expect that wdio will use chrome version 85.0.4183.87, however, it is failing to start spec files

**Log**
14:53:58.178 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "acceptInsecureCerts": true,
  "browserName": "chrome"
}
14:53:58.179 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 85.0.4183.87 (cd6713ebf92fa1cacc0f1a598df280093af0c5d7-refs/branch-heads/4183@{#1689}) on port 21979
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
14:53:59.790 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "acceptInsecureCerts": true,
  "browserName": "chrome"
}
14:53:59.791 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 85.0.4183.87 (cd6713ebf92fa1cacc0f1a598df280093af0c5d7-refs/branch-heads/4183@{#1689}) on port 47614
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
14:54:01.175 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "acceptInsecureCerts": true,
  "browserName": "chrome"
}
14:54:01.175 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 85.0.4183.87 (cd6713ebf92fa1cacc0f1a598df280093af0c5d7-refs/branch-heads/4183@{#1689}) on port 39478
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
14:54:02.303 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "acceptInsecureCerts": true,
  "browserName": "chrome"
}
14:54:02.303 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 85.0.4183.87 (cd6713ebf92fa1cacc0f1a598df280093af0c5d7-refs/branch-heads/4183@{#1689}) on port 22668
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.

2020-11-22T19:53:55.678Z DEBUG @wdio/utils:initialiseServices: initialise service "selenium-standalone" as NPM package
(node:3181) ExperimentalWarning: The dns.promises API is experimental
(node:3181) ExperimentalWarning: The fs.promises API is experimental
2020-11-22T19:53:55.828Z INFO @wdio/cli:launcher: Run onPrepare hook
2020-11-22T19:53:57.113Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2020-11-22T19:53:57.115Z INFO @wdio/local-runner: Start worker 0-0 with arg: wdio.conf.js
[0-0] (node:3183) ExperimentalWarning: The dns.promises API is experimental
[0-0] (node:3183) ExperimentalWarning: The fs.promises API is experimental
[0-0] 2020-11-22T19:53:57.467Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2020-11-22T19:53:57.471Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2020-11-22T19:53:57.474Z INFO webdriverio: Initiate new session using the ./protocol-stub protocol
[0-0] RUNNING in chrome - /test/specs/example.e2e.js
[0-0] 2020-11-22T19:53:57.956Z DEBUG @wdio/utils:initialiseServices: initialise service "selenium-standalone" as NPM package
[0-0] 2020-11-22T19:53:58.101Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2020-11-22T19:53:58.102Z INFO webdriverio: Initiate new session using the webdriver protocol
[0-0] 2020-11-22T19:53:58.104Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
[0-0] 2020-11-22T19:53:58.104Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
     firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true } }
[0-0] (node:3183) ExperimentalWarning: Readable[Symbol.asyncIterator] is an experimental feature. This feature could change at any time
[0-0] 2020-11-22T19:53:59.777Z DEBUG webdriver: request failed due to status 33
[0-0] 2020-11-22T19:53:59.777Z WARN webdriver: Request failed with status 500 due to session not created: This version of ChromeDriver only supports Chrome version 85
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'Michaels-MBP', ip: '192.168.1.67', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_242'
Driver info: driver.version: unknown
remote stacktrace: 0   85.0.4183.87-x64-chromedriver       0x000000010e4731b9 85.0.4183.87-x64-chromedriver + 4911545
1   85.0.4183.87-x64-chromedriver       0x000000010e412e03 85.0.4183.87-x64-chromedriver + 4517379
2   85.0.4183.87-x64-chromedriver       0x000000010e080dc6 85.0.4183.87-x64-chromedriver + 773574
3   85.0.4183.87-x64-chromedriver       0x000000010dfdc452 85.0.4183.87-x64-chromedriver + 99410
4   85.0.4183.87-x64-chromedriver       0x000000010dfd8d6f 85.0.4183.87-x64-chromedriver + 85359
5   85.0.4183.87-x64-chromedriver       0x000000010e007716 85.0.4183.87-x64-chromedriver + 276246
6   85.0.4183.87-x64-chromedriver       0x000000010e004723 85.0.4183.87-x64-chromedriver + 263971
7   85.0.4183.87-x64-chromedriver       0x000000010dfde720 85.0.4183.87-x64-chromedriver + 108320
8   85.0.4183.87-x64-chromedriver       0x000000010dfdf693 85.0.4183.87-x64-chromedriver + 112275
9   85.0.4183.87-x64-chromedriver       0x000000010e43bf72 85.0.4183.87-x64-chromedriver + 4685682
10  85.0.4183.87-x64-chromedriver       0x000000010e449b3a 85.0.4183.87-x64-chromedriver + 4741946
11  85.0.4183.87-x64-chromedriver       0x000000010e449801 85.0.4183.87-x64-chromedriver + 4741121
12  85.0.4183.87-x64-chromedriver       0x000000010e41f25e 85.0.4183.87-x64-chromedriver + 4567646
13  85.0.4183.87-x64-chromedriver       0x000000010e44a061 85.0.4183.87-x64-chromedriver + 4743265
14  85.0.4183.87-x64-chromedriver       0x000000010e430d0a 85.0.4183.87-x64-chromedriver + 4640010
15  85.0.4183.87-x64-chromedriver       0x000000010e4630ba 85.0.4183.87-x64-chromedriver + 4845754
16  85.0.4183.87-x64-chromedriver       0x000000010e479387 85.0.4183.87-x64-chromedriver + 4936583
17  libsystem_pthread.dylib             0x00007fff20324950 _pthread_start + 224
18  libsystem_pthread.dylib             0x00007fff2032047b thread_start + 15

**Comment by christian-bromann** [comment]
Please see error message:

> Request failed with status 500 due to session not created: This version of ChromeDriver only supports Chrome version 85

You have to update your chromedriver version to make this work.

**Comment by christian-bromann** [comment]
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
