### ISSUE TITLE
How to identify and switch to the frame

### ISSUE THREAD

**Issue by amiya-pattnaik** [webdriverio/webdriverio#615]
our  application is embedded inside an iframe i.e the application window (all the page elements) are inside the iframe.  Safari as the only supported browser and we are using webdriverIO as the standard tool. We are not able to switch to the iframe, and not able to click or able to do any action on the page. We have tried below code in our script but not able to proceed. 

client.frame('ifrm');

please advise us. we appreciate your help.
Thanks,
Amiya

**Comment by christian-bromann** [comment]
There are three options you can take to switch to a frame:

via interger query: if you only have one iframe on the page you can switch calling client.frame(0) (though not sure if 0 is the current frame, if so use 1)
via name attribute: give that iframe a name like name="myIframe" then you can switch calling client.frame("myIframe")
via WebElement: query the iframe using the element method and then pass the result to the frame command

**Comment by amiya-pattnaik** [comment]
Hi Chris,
I am extremely sorry for late replay. I was on a vacation hence bit late.
We have below iframe code. We tried all option you have suggested, still not working on Safari. Could you please help us? 

<iframe src="" id="ifrm" name="ifrm"></iframe>
	#document
	<html>
	<head><link rel="stylesheet" href=“/appURL" type="text/css"> </head>
	<body>…</body>
	</html>
<iframe



Thanks.
Amiya

**Comment by amiya-pattnaik** [comment]
<iframe src="" id="ifrm" name="ifrm"></iframe>
	#document
	<html>
	<head><link rel="stylesheet" href=“/appURL" type="text/css"> </head>
	<body>…</body>
	</html>
<iframe

**Comment by amiya-pattnaik** [comment]
<iframe src = "" id = "ifrm" name = "ifrm"> <iframe>

**Comment by amiya-pattnaik** [comment]
i dont know what is happening here. After typing iframe html code, it is getting truncated

**Comment by christian-bromann** [comment]
Is it only not working with safari?

**Comment by amiya-pattnaik** [comment]
Yes Chris, It is not working for Safari browser. to test it we tied with Firefox, with the same code switching to iframe is happening properly for Firefox and Chrome, but not on Safari. 

Please suggest us. for our application Safari is the only official supported browser. Your help is much needed. I appreciate your help and support.

Thanks,
Amiya

**Comment by amiya-pattnaik** [comment]
Hi Chris,
Could you please help on this iframe safari issue? We just took the latest selenium webdriverjs and checked with  the raw selenium code, it is perfectly switching in iframe with Safari browser. 

Please help us ...we appreciate your help

**Comment by christian-bromann** [comment]
@amiya-pattnaik could you send me that code as a gist?

**Comment by amiya-pattnaik** [comment]
Hi Chris, 

Here is the below raw selenium code which is working fine for safari on iframe. Could you please help us on how we can do it for webdriverIO. thanks Amiya

switchTo: (function() {
		var parent = null;
		var frameByName = function(name) {
			driver.switchTo().defaultContent();
			this.parent.waitForElement("//iframe[@name='" + name + "']");
			driver.switchTo().frame(name);
		};
		var frameById = function(id) {
			driver.switchTo().defaultContent();
			this.parent.waitForElement("//iframe[@id='" + id + "']");
			driver.switchTo().frame(id);
		};
		return {
			frameByName: frameByName,
			frameById: frameById
		};
	})(),

	switchParent: function(){
		driver.switchTo().defaultContent();
	},

**Comment by christian-bromann** [comment]
@amiya-pattnaik I looked into the safaridriver issue list and this seems to be a valid issue: https://code.google.com/p/selenium/issues/detail?id=8413&can=1&q=browser%3DSafari%20component%3DWebDriver%20status%3ANew%2CAccepted%2CWorkingAsIntended%2CWontFix%2CNotFeasible&colspec=ID%20Stars%20Type%20Status%20Priority%20Owner%20Summary%20Browser%20Component

So there is nothing I can do about that. I am not even able to open a website that contains an iframe using safaridriver.

**Comment by christian-bromann** [comment]
hah .. got it working using Sauce Labs:

```js
var client = require('webdriverio').remote({
    user: process.env.SAUCE_USERNAME,
    key: process.env.SAUCE_ACCESS_KEY,
    desiredCapabilities: {
        browserName: 'safari'
    }
});

client
    .init()
    .url('http://webdriverjs.christian-bromann.com/two.html')
    .element('iframe').then(function(res) {
      return client.frame(res.value);
    })
    .getHTML('head title', false).then(console.log)
    .end();
```

Apparently switching to an iframe using the name isn't working.

**Comment by christian-bromann** [comment]
Oh and btw: I've used getHTML to get the title because `getTitle` would still return the title of the parent frame

**Comment by amiya-pattnaik** [comment]
Thanks a lot  Chris for your time and support.
In our automation script we are using only wendriverIO and we are not using any Sauce Labs code. below is code. 
client = webdriverio.remote({desiredCapabilities: {browserName: 'safari'} }); 

if we use the the above Sauce Labs code which you have mentioned, should we require to import any any Sauce Labs modules /packages through 'require' statement or webdriverIO has inbuld Sauce Labs code support? please advise.

Thanks,
Amiya

**Comment by christian-bromann** [comment]
@amiya-pattnaik no, just register yourself (e.g. [here](https://saucelabs.com/signup/trial)) and you will get an access key which you pass in in the above code. Of course there are more cloud provide like Sauce Labs. There more famous ones are [Browserstack](https://www.browserstack.com/) and [TestingBot](https://testingbot.com/)

**Comment by amiya-pattnaik** [comment]
Hi Chris,
I have registered it. few queries, it would be great if you could help us

1. is this access key valid for life time ? or it will be expired after a trail period?
2. if I use this access code in our code, in which environment it will run? will it point to Sauce Labs browser / env ?? (hope it will not)

**Comment by christian-bromann** [comment]
> is this access key valid for life time ? or it will be expired after a trail period?

The access key is coupled to your username. So if you don't generate a new access key (because you might thing that someone has stolen it) it will remain forever.

> if I use this access code in our code, in which environment it will run?

If you use Sauce Labs the browser will run in one of the VMs in Sauce Labs own datacenters. If you have sensible information on your page then you can use [Sauce Connect](https://docs.saucelabs.com/reference/sauce-connect/) which establishes a secure tunnel between your computer and the VM.

**Comment by amiya-pattnaik** [comment]
thanks a lot Chris for the clarification. Unfortunately we don,t have permission to run our script other than our own environment. Any other idea where we can solve this iframe issue in Safari browser with simple webdriverIO module??

**Comment by christian-bromann** [comment]
Just be clear: what is your definition of environment? If you use Sauce Labs only the browser will be in the cloud .. test still running on your machine (in your environment)

> Any other idea where we can solve this iframe issue in Safari browser with simple webdriverIO module??

You could try to down-/upgrade the safaridriver version.

**Comment by amiya-pattnaik** [comment]
Thanks Chris, we appreciate your valuable suggestion. We will try and will get back to you.

**Comment by lamanhhien** [comment]
@christian-bromann  i want get dom of  iframe but it into the other iframe . How to get  dom of iframe has id= "small"
<iframe id="big">
    <html>
    <body>
    <div class="menu"></div>
    <iframe id="small">
        <html>
        <body>
        <div id="replay" style="display:none"></div>
        </body>
        </html>
    </iframe>
    </body>
    </html>
</iframe>

**Comment by Pascal-nonprofit8** [comment]
> [@amiya-pattnaik](https://github.com/amiya-pattnaik) could you send me that code as a gist?





https://fractured809.github.io/test-suite/
