### ISSUE TITLE
@wdio/testingbot-service doesn't configure the hostname/protocoll/port for tbTunnel option

### ISSUE THREAD

**Issue by karfau** [webdriverio/webdriverio#6151]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.9.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 10
 - **NPM version:** 6.14.8
 - **Browser name and version:** not relevant
 - **Platform name and version:** not relevant
 - **Additional wdio packages used (if applicable):** @wdio/testingbot-service (v6.8.2)

**Config of WebdriverIO**
https://gist.github.com/karfau/fbb7b5f2202c80c5c5fa61dab6f2f39d

**Describe the bug**
According to the documentation the only thing needed to run through the testinbot tunnel is to set tbTunnel option to `true`. But to actually make it work you also need to set the fields `hostname`, `protocol` and `port` correctly to actually make it work (see https://gist.github.com/karfau/fbb7b5f2202c80c5c5fa61dab6f2f39d#file-wdio-conf-js-L66-L68 in the provided config)

**To Reproduce**

```typescript
describe("browser support", () => {
  it("home page should show clickable button", async () => {
    await browser.url(`/`);
    const button = await $("button");
    expect(await button.waitForClickable({ timeout: 2000 })).toEqual(true);
  });
});
```

**Expected behavior**
The service already set's the three parameters (and `path`) to the correct values when `tbTunnel` option is not set or false. It should also set them correctly when it's set to true.

(Or) The (testingbot?) documentation could/should be more clear about HTTP vs HTTPS and the related ports (which combinations work) and when to use what.

**Comment by christian-bromann** [comment]
@testingbot can you take a look. I remember we changed this part recently.
