### ISSUE TITLE
Not able to Launch browser with wdio@sync : 6.9.1 : Giving Error when browser.waituntill and WaitUntilOptions are being used 

### ISSUE THREAD

**Issue by Bhargav704** [webdriverio/webdriverio#6153]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** ["webdriver": "^6.9.1",]
 - **Mode:** [ "selenium-standalone": "^6.20.1"]
 - **If WDIO Testrunner, running sync/async:** [@wdio/sync": "^6.9.1]
 - **Node.js version:** [14.14.9]
 - **NPM version:** [6.14.9]
 - **Browser name and version:** ["chromedriver": "^87.0.0"]
 - **Platform name and version:** [Windows 10]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Dependencies**
devDependencies": {
    "@babel/cli": "^7.12.8",
    "@babel/core": "^7.12.8",
    "@babel/node": "^7.12.6",
    "@babel/preset-env": "^7.12.7",
    "@babel/register": "^7.12.1",
    "@types/chai": "^4.2.14",
    "@types/mocha": "^8.0.4",
    "@types/node": "^14.14.9",
    "@typescript-eslint/eslint-plugin": "^4.8.2",
    "@typescript-eslint/parser": "^4.8.2",
    "@wdio/allure-reporter": "^6.8.1",
    "@wdio/browserstack-service": "^6.8.0",
    "@wdio/junit-reporter": "^6.8.1",
    "@wdio/local-runner": "^6.9.1",
    "@wdio/mocha-framework": "^6.8.0",
    "@wdio/selenium-standalone-service": "^6.9.0",
    "@wdio/spec-reporter": "^6.8.1",
    "@wdio/sync": "^6.9.1",
    "allure-commandline": "^2.13.0",
    "chai-webdriverio": "^1.0.0",
    "chromedriver": "^87.0.0",
    "eslint": "^7.14.0",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-config-prettier": "^6.15.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-webdriverio": "^1.0.1",
    "faker": "^5.1.0",
    "husky": "^4.3.0",
    "lint-staged": "^10.5.1",
    "local-runner": "^0.1.1-alpha",
    "prettier": "^2.2.0",
    "ts-node": "^9.0.0",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^4.1.2",
    "wdio-chromedriver-service": "^6.0.4",
    "wdio-video-reporter": "^3.1.1",
    "webdriverio": "^6.9.1"
  },
  "dependencies": {
    "@wdio/cli": "^6.9.1",
    "axios": "^0.21.0",
    "chai": "^4.2.0",
    "config": "^3.3.2",
    "dotenv": "^8.2.0",
    "fibers": "^5.0.0",
    "jslint": "^0.12.1",
    "mocha": "^8.2.1",
    "selenium-standalone": "^6.20.1",
    "webdriver": "^6.9.1",
    "winston": "^3.3.3"
  }

**Log**

Execution of 1 spec files started at 2020-11-24T06:15:02.840Z
Starting ChromeDriver 87.0.4280.20 (c99e81631faa0b2a448e658c0dbd8311fb04ddbd-refs/branch-heads/4280@{#355}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.     
ChromeDriver was started successfully.
[0-0] 2020-11-24T06:15:09.174Z WARN @wdio/mocha-framework: Unable to load spec files quite likely because they rely on 
`browser` object that is not fully initialised.
`browser` object has only `capabilities` and some flags like `isMobile`.
Helper files that use other `browser` commands have to be moved to `before` hook
**Error: TSError: ⨯ Unable to compile TypeScript:
error TS2554: Expected 1-2 arguments, but got 3.
error TS2559: Type '25000' has no properties in common with type 'WaitUntilOptions'**

    at createTSError ( ts-node\src\index.ts:500:12)
    at reportTSError ( ts-node\src\index.ts:504:19)
    at getOutput ( ts-node\src\index.ts:739:36)
    at Object.compile ( ts-node\src\index.ts:955:32)
    at Module.m._compile ( ts-node\src\index.ts:1043:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.require.extensions.<computed> [as .ts] ( ts-node\src\index.ts:1046:12)  
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)

**Comment by christian-bromann** [comment]
Please see error message:

> Unable to load spec files quite likely because they rely on
> `browser` object that is not fully initialised.

You are using the `browser` object outside of an it block or hook which is not allowed. Given there is no reproducible example this is the only assumption I can make. Closing as it is not a WebdriverIO issue.
