### ISSUE TITLE
Server doesn't start

### ISSUE THREAD

**Issue by Gennadiii** [webdriverio/webdriverio#6154]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2]
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:** [e.g. 8.11.2]
 - **NPM version:** [e.g. 5.8.0]
 - **Browser name and version:** [e.g. Chrome 68]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**

**To Reproduce**

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
Closing as no description was provided.

**Comment by Gennadiii** [comment]
@christian-bromann my bad, I added description but it got discarded somehow. Added it now. Could you please take a look and maybe I could add some more info that you might need?

**Comment by christian-bromann** [comment]
> I could add some more info that you might need?

some wdio logs would be great!

**Comment by Gennadiii** [comment]
@christian-bromann 
2020-11-24T12:32:34.620Z DEBUG @wdio/utils:initialiseServices: initialise service "selenium-s
tandalone" as NPM package
2020-11-24T12:32:34.660Z INFO @wdio/cli:launcher: Run onPrepare hook
2020-11-24T12:32:36.169Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2020-11-24T12:32:36.174Z INFO @wdio/local-runner: Start worker 0-0 with arg: dist/config/wdio
/local.conf.js
[0-0] 2020-11-24T12:32:36.566Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2020-11-24T12:32:37.329Z DEBUG @wdio/utils:initialiseServices: initialise service "sele
nium-standalone" as NPM package
[0-0] 2020-11-24T12:32:37.377Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2020-11-24T12:32:37.379Z INFO webdriverio: Initiate new session using the ./protocol-st
ub protocol
[0-0] RUNNING in chrome - C:\Users\LEGION\repos\current\corva-web-tests\dist\specs\main\notif
ications\likePost.notificationSpec.js
[0-0] 2020-11-24T12:32:38.004Z DEBUG @wdio/local-runner:utils: init remote session
2020-11-24T12:32:38.004Z INFO webdriverio: Initiate new session using the webdriver protocol
[0-0] 2020-11-24T12:32:38.006Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
[0-0] 2020-11-24T12:32:38.006Z INFO webdriver: DATA {
  capabilities: { alwaysMatch: { browserName: 'chrome' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'chrome' }
}
[0-0] 2020-11-24T12:32:39.650Z DEBUG webdriver: request failed due to status 33
[0-0] 2020-11-24T12:32:39.650Z WARN webdriver: Request failed with status 500 due to session
not created: This version of ChromeDriver only supports Chrome version 85
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'DESKTOP-KKDVH01', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'x86',
 os.version: '10.0', java.version: '1.8.0_271'
Driver info: driver.version: unknown
remote stacktrace: Backtrace:
        Ordinal0 [0x00F6D383+3134339]
        Ordinal0 [0x00E5A171+2007409]
        Ordinal0 [0x00CFAEE8+569064]
        Ordinal0 [0x00C8139F+70559]
        Ordinal0 [0x00C7CC63+52323]
        Ordinal0 [0x00CA0DFC+200188]
        Ordinal0 [0x00CA0C1D+199709]
        Ordinal0 [0x00C9EB0B+191243]
        Ordinal0 [0x00C82E77+77431]
        Ordinal0 [0x00C83E3E+81470]
        Ordinal0 [0x00C83DC9+81353]
        Ordinal0 [0x00E70CD9+2100441]
        GetHandleVerifier [0x010DB75A+1396954]
        GetHandleVerifier [0x010DB3D9+1396057]
        GetHandleVerifier [0x010E7126+1444518]
        GetHandleVerifier [0x010DBCE8+1398376]
        Ordinal0 [0x00E67F51+2064209]
        Ordinal0 [0x00E722EB+2106091]
        Ordinal0 [0x00E72411+2106385]
        Ordinal0 [0x00E849C4+2181572]
        BaseThreadInitThunk [0x76CA6359+25]
        RtlGetAppContainerNamedObjectPath [0x77088944+228]
        RtlGetAppContainerNamedObjectPath [0x77088914+180]

[0-0] 2020-11-24T12:32:39.651Z INFO webdriver: Retrying 1/3
2020-11-24T12:32:39.651Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
2020-11-24T12:32:39.651Z INFO webdriver: DATA {
  capabilities: { alwaysMatch: { browserName: 'chrome' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'chrome' }
}
[0-0] 2020-11-24T12:32:40.691Z DEBUG webdriver: request failed due to status 33
[0-0] 2020-11-24T12:32:40.691Z WARN webdriver: Request failed with status 500 due to session
not created: This version of ChromeDriver only supports Chrome version 85
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'DESKTOP-KKDVH01', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'x86',
 os.version: '10.0', java.version: '1.8.0_271'
Driver info: driver.version: unknown
remote stacktrace: Backtrace:
        Ordinal0 [0x00F6D383+3134339]
        Ordinal0 [0x00E5A171+2007409]
        Ordinal0 [0x00CFAEE8+569064]
        Ordinal0 [0x00C8139F+70559]
        Ordinal0 [0x00C7CC63+52323]
        Ordinal0 [0x00CA0DFC+200188]
        Ordinal0 [0x00CA0C1D+199709]
        Ordinal0 [0x00C9EB0B+191243]
        Ordinal0 [0x00C82E77+77431]
        Ordinal0 [0x00C83E3E+81470]
        Ordinal0 [0x00C83DC9+81353]
        Ordinal0 [0x00E70CD9+2100441]
        GetHandleVerifier [0x010DB75A+1396954]
        GetHandleVerifier [0x010DB3D9+1396057]
        GetHandleVerifier [0x010E7126+1444518]
        GetHandleVerifier [0x010DBCE8+1398376]
        Ordinal0 [0x00E67F51+2064209]
        Ordinal0 [0x00E722EB+2106091]
        Ordinal0 [0x00E72411+2106385]
        Ordinal0 [0x00E849C4+2181572]
        BaseThreadInitThunk [0x76CA6359+25]
        RtlGetAppContainerNamedObjectPath [0x77088944+228]
        RtlGetAppContainerNamedObjectPath [0x77088914+180]

[0-0] 2020-11-24T12:32:40.691Z INFO webdriver: Retrying 2/3
2020-11-24T12:32:40.691Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
2020-11-24T12:32:40.691Z INFO webdriver: DATA {
  capabilities: { alwaysMatch: { browserName: 'chrome' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'chrome' }
}
[0-0] 2020-11-24T12:32:41.766Z DEBUG webdriver: request failed due to status 33
[0-0] 2020-11-24T12:32:41.767Z WARN webdriver: Request failed with status 500 due to session
not created: This version of ChromeDriver only supports Chrome version 85
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'DESKTOP-KKDVH01', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'x86',
 os.version: '10.0', java.version: '1.8.0_271'
Driver info: driver.version: unknown
remote stacktrace: Backtrace:
        Ordinal0 [0x00F6D383+3134339]
        Ordinal0 [0x00E5A171+2007409]
        Ordinal0 [0x00CFAEE8+569064]
        Ordinal0 [0x00C8139F+70559]
        Ordinal0 [0x00C7CC63+52323]
        Ordinal0 [0x00CA0DFC+200188]
        Ordinal0 [0x00CA0C1D+199709]
        Ordinal0 [0x00C9EB0B+191243]
        Ordinal0 [0x00C82E77+77431]
        Ordinal0 [0x00C83E3E+81470]
        Ordinal0 [0x00C83DC9+81353]
        Ordinal0 [0x00E70CD9+2100441]
        GetHandleVerifier [0x010DB75A+1396954]
        GetHandleVerifier [0x010DB3D9+1396057]
        GetHandleVerifier [0x010E7126+1444518]
        GetHandleVerifier [0x010DBCE8+1398376]
        Ordinal0 [0x00E67F51+2064209]
        Ordinal0 [0x00E722EB+2106091]
        Ordinal0 [0x00E72411+2106385]
        Ordinal0 [0x00E849C4+2181572]
        BaseThreadInitThunk [0x76CA6359+25]
        RtlGetAppContainerNamedObjectPath [0x77088944+228]
        RtlGetAppContainerNamedObjectPath [0x77088914+180]

[0-0] 2020-11-24T12:32:41.767Z INFO webdriver: Retrying 3/3
2020-11-24T12:32:41.767Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
2020-11-24T12:32:41.767Z INFO webdriver: DATA {
  capabilities: { alwaysMatch: { browserName: 'chrome' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'chrome' }
}
[0-0] 2020-11-24T12:32:42.801Z DEBUG webdriver: request failed due to status 33
[0-0] 2020-11-24T12:32:42.801Z ERROR webdriver: Request failed with status 500 due to session
 not created: session not created: This version of ChromeDriver only supports Chrome version
85
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'DESKTOP-KKDVH01', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'x86',
 os.version: '10.0', java.version: '1.8.0_271'
Driver info: driver.version: unknown
remote stacktrace: Backtrace:
        Ordinal0 [0x00F6D383+3134339]
        Ordinal0 [0x00E5A171+2007409]
        Ordinal0 [0x00CFAEE8+569064]
        Ordinal0 [0x00C8139F+70559]
        Ordinal0 [0x00C7CC63+52323]
        Ordinal0 [0x00CA0DFC+200188]
        Ordinal0 [0x00CA0C1D+199709]
        Ordinal0 [0x00C9EB0B+191243]
        Ordinal0 [0x00C82E77+77431]
        Ordinal0 [0x00C83E3E+81470]
        Ordinal0 [0x00C83DC9+81353]
        Ordinal0 [0x00E70CD9+2100441]
        GetHandleVerifier [0x010DB75A+1396954]
        GetHandleVerifier [0x010DB3D9+1396057]
        GetHandleVerifier [0x010E7126+1444518]
        GetHandleVerifier [0x010DBCE8+1398376]
        Ordinal0 [0x00E67F51+2064209]
        Ordinal0 [0x00E722EB+2106091]
        Ordinal0 [0x00E72411+2106385]
        Ordinal0 [0x00E849C4+2181572]
        BaseThreadInitThunk [0x76CA6359+25]
        RtlGetAppContainerNamedObjectPath [0x77088944+228]
        RtlGetAppContainerNamedObjectPath [0x77088914+180]

2020-11-24T12:32:42.801Z ERROR webdriver: session not created: session not created: This vers
ion of ChromeDriver only supports Chrome version 85
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'DESKTOP-KKDVH01', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'x86',
 os.version: '10.0', java.version: '1.8.0_271'
Driver info: driver.version: unknown
remote stacktrace: Backtrace:
        Ordinal0 [0x00F6D383+3134339]
        Ordinal0 [0x00E5A171+2007409]
        Ordinal0 [0x00CFAEE8+569064]
        Ordinal0 [0x00C8139F+70559]
        Ordinal0 [0x00C7CC63+52323]
        Ordinal0 [0x00CA0DFC+200188]
        Ordinal0 [0x00CA0C1D+199709]
        Ordinal0 [0x00C9EB0B+191243]
        Ordinal0 [0x00C82E77+77431]
        Ordinal0 [0x00C83E3E+81470]
        Ordinal0 [0x00C83DC9+81353]
        Ordinal0 [0x00E70CD9+2100441]
        GetHandleVerifier [0x010DB75A+1396954]
        GetHandleVerifier [0x010DB3D9+1396057]
        GetHandleVerifier [0x010E7126+1444518]
        GetHandleVerifier [0x010DBCE8+1398376]
        Ordinal0 [0x00E67F51+2064209]
        Ordinal0 [0x00E722EB+2106091]
        Ordinal0 [0x00E72411+2106385]
        Ordinal0 [0x00E849C4+2181572]
        BaseThreadInitThunk [0x76CA6359+25]
        RtlGetAppContainerNamedObjectPath [0x77088944+228]
        RtlGetAppContainerNamedObjectPath [0x77088914+180]

    at Object.getErrorFromResponseBody (C:\Users\LEGION\repos\current\corva-web-tests\node_mo
dules\webdriver\build\utils.js:94:12)
    at WebDriverRequest._request (C:\Users\LEGION\repos\current\corva-web-tests\node_modules\
webdriver\build\request.js:134:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.startWebDriverSession (C:\Users\LEGION\repos\current\corva-web-tests\node
_modules\webdriver\build\utils.js:29:20)
    at async Function.newSession (C:\Users\LEGION\repos\current\corva-web-tests\node_modules\
webdriver\build\index.js:30:45)
    at async Object.exports.remote (C:\Users\LEGION\repos\current\corva-web-tests\node_module
s\webdriverio\build\index.js:60:22)
    at async Runner._startSession (C:\Users\LEGION\repos\current\corva-web-tests\node_modules
\@wdio\runner\build\index.js:128:56)
    at async Runner._initSession (C:\Users\LEGION\repos\current\corva-web-tests\node_modules\
@wdio\runner\build\index.js:108:25)
    at async Runner.run (C:\Users\LEGION\repos\current\corva-web-tests\node_modules\@wdio\run
ner\build\index.js:52:19)
[0-0]  Error:  Failed to create session.
session not created: This version of ChromeDriver only supports Chrome version 85
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'DESKTOP-KKDVH01', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'x86',
 os.version: '10.0', java.version: '1.8.0_271'
Driver info: driver.version: unknown
remote stacktrace: Backtrace:
        Ordinal0 [0x00F6D383+3134339]
        Ordinal0 [0x00E5A171+2007409]
        Ordinal0 [0x00CFAEE8+569064]
        Ordinal0 [0x00C8139F+70559]
        Ordinal0 [0x00C7CC63+52323]
        Ordinal0 [0x00CA0DFC+200188]
        Ordinal0 [0x00CA0C1D+199709]
        Ordinal0 [0x00C9EB0B+191243]
        Ordinal0 [0x00C82E77+77431]
        Ordinal0 [0x00C83E3E+81470]
        Ordinal0 [0x00C83DC9+81353]
        Ordinal0 [0x00E70CD9+2100441]
        GetHandleVerifier [0x010DB75A+1396954]
        GetHandleVerifier [0x010DB3D9+1396057]
        GetHandleVerifier [0x010E7126+1444518]
        GetHandleVerifier [0x010DBCE8+1398376]
        Ordinal0 [0x00E67F51+2064209]
        Ordinal0 [0x00E722EB+2106091]
        Ordinal0 [0x00E72411+2106385]
        Ordinal0 [0x00E849C4+2181572]
        BaseThreadInitThunk [0x76CA6359+25]
        RtlGetAppContainerNamedObjectPath [0x77088944+228]
        RtlGetAppContainerNamedObjectPath [0x77088914+180]

[0-0] 2020-11-24T12:32:42.801Z ERROR @wdio/runner: Error: Failed to create session.
session not created: This version of ChromeDriver only supports Chrome version 85
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'DESKTOP-KKDVH01', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'x86',
 os.version: '10.0', java.version: '1.8.0_271'
Driver info: driver.version: unknown
remote stacktrace: Backtrace:
        Ordinal0 [0x00F6D383+3134339]
        Ordinal0 [0x00E5A171+2007409]
        Ordinal0 [0x00CFAEE8+569064]
        Ordinal0 [0x00C8139F+70559]
        Ordinal0 [0x00C7CC63+52323]
        Ordinal0 [0x00CA0DFC+200188]
        Ordinal0 [0x00CA0C1D+199709]
        Ordinal0 [0x00C9EB0B+191243]
        Ordinal0 [0x00C82E77+77431]
        Ordinal0 [0x00C83E3E+81470]
        Ordinal0 [0x00C83DC9+81353]
        Ordinal0 [0x00E70CD9+2100441]
        GetHandleVerifier [0x010DB75A+1396954]
        GetHandleVerifier [0x010DB3D9+1396057]
        GetHandleVerifier [0x010E7126+1444518]
        GetHandleVerifier [0x010DBCE8+1398376]
        Ordinal0 [0x00E67F51+2064209]
        Ordinal0 [0x00E722EB+2106091]
        Ordinal0 [0x00E72411+2106385]
        Ordinal0 [0x00E849C4+2181572]
        BaseThreadInitThunk [0x76CA6359+25]
        RtlGetAppContainerNamedObjectPath [0x77088944+228]
        RtlGetAppContainerNamedObjectPath [0x77088914+180]

    at Object.startWebDriverSession (C:\Users\LEGION\repos\current\corva-web-tests\node_modul
es\webdriver\build\utils.js:34:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-11-24T12:32:42.910Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in chrome - C:\Users\LEGION\repos\current\corva-web-tests\dist\specs\main\notifi
cations\likePost.notificationSpec.js
2020-11-24T12:32:42.911Z INFO @wdio/cli:launcher: Run onComplete hook
2020-11-24T12:32:42.912Z INFO @wdio/selenium-standalone-service: shutting down all browsers

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:08

2020-11-24T12:32:42.913Z INFO @wdio/local-runner: Shutting down spawned worker
2020-11-24T12:32:43.164Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2020-11-24T12:32:43.166Z INFO @wdio/local-runner: shutting down

**Comment by christian-bromann** [comment]
Please see error message:

> Request failed with status 500 due to session
> not created: This version of ChromeDriver only supports Chrome version 85

this is related to https://github.com/vvo/selenium-standalone/pull/486

**Comment by Gennadiii** [comment]
@christian-bromann yeah I saw that. I just don't get why I get old driver when I have latest package installed. Thanks for your time, appreciate it. I'll address my question by that link.
