### ISSUE TITLE
An unknown server-side error when using chrome

### ISSUE THREAD

**Issue by kol1** [webdriverio/webdriverio#617]
Every time I'm using chrome with webdriverio I get this error:

    RuntimeError: An unknown server-side error occurred while processing the command. (UnknownError:13)

For example when I run this code:

    webdriverio = require('webdriverio');
    webdriverio.remote({
        desiredCapabilities: {
            browserName: 'chrome',
        }
    }).init().url('http://google.com').getTitle(function(title){
        console.log(title);
    });

I've tried the same code with firefox and phantomjs and had no problems.

**Comment by christian-bromann** [comment]
Do you have the chromedriver installed on your system?

**Comment by kol1** [comment]
No, I didn't. My bad, you can delete this issue.

**Comment by christian-bromann** [comment]
Alright then
