### ISSUE TITLE
isFocused stopped working on 6.10

### ISSUE THREAD

**Issue by unickq** [webdriverio/webdriverio#6179]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.10
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12
 - **NPM version:** 6
 - **Browser name and version:** any
 - **Platform name and version:** any

**Describe the bug**
isFocused() seems no to work after update to 6.10. Maybe TS changes https://github.com/webdriverio/webdriverio/pull/6139 missed it :)

```js
describe("A", () => {
  it("A", () => {
    browser.navigateTo("https://the-internet.herokuapp.com/login");
    console.log($("#username").isFocused());
    console.log($("#password").isFocused());
    $("#username").click();
    console.log($("#username").isFocused());
    console.log($("#password").isFocused());
  });
});
```
**6.9.1:**

[0-0] false
[0-0] false
[0-0] true
[0-0] false

**6.10.4**

[0-0] true
[0-0] true
[0-0] true
[0-0] true

**Comment by mgrybyk** [comment]
I guess we missed await https://github.com/webdriverio/webdriverio/blob/788019e77c3fa2376811ceca5ba3d1511ecba525/packages/webdriverio/src/commands/element/isFocused.ts#L34
