### ISSUE TITLE
Cucumber reporter

### ISSUE THREAD

**Issue by Lewiscowles1986** [webdriverio/webdriverio#6186]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [x] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

(I am unsure if it is missing or unclear, but I've not been able to find, google or github search it)

**Description of the improvement / report**

Using the cucumber framework for wdio via nodeJs, I get the following output

```
--------
TIMELINE REPORTER: Created C:\Users\lewis\projects\gutenberg-shortcode-preview-block\test-reports/timeline-report.html
--------

Spec Files:      1 passed, 1 total (100% completed) in 00:00:16 
```

I would like something more akin to a per-scenario report

```
PASS  e2e/features/login.feature (25.59 s)
  As a user, I recieve an error message when using invalid credentials to log into the application
    √ Missing Username
    √ Missing Password
  As a user, I can login
    √ as an admin (28 ms)
```

Others have suggested 

> have you looked at cucumber --format ?

I have no idea what that advice entails, it seems to be about abandoning this integration.

**Comment by christian-bromann** [comment]
Hey @Lewiscowles1986, thanks for filing the issue. Please take a look into our docs. WebdriverIO provides a variety of reporting plugins. We also have some documentation how to [build a reporter](https://webdriver.io/docs/customreporter.html) yourself if the ones provided don't fit your requirements. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have questions to the usage of specific reporters.

I will close this issue as it isn't necessarily an issue in WebdriverIO.

**Comment by Lewiscowles1986** [comment]
It's a core package, but I think the issue was actually just a confusingly named file.

The answer is the following

`npm install @wdio/dot-reporter --save-dev` then add  'spec' to reporters

It produces something close to what I wanted and needed... 🙄 

```
 "spec" Reporter:
------------------------------------------------------------------
[chrome 87.0.4280.66 windows #0-0] Spec: C:\Users\lewis\projects\############\e2e\features\login.feature
[chrome 87.0.4280.66 windows #0-0] Running: chrome (v87.0.4280.66) on windows
[chrome 87.0.4280.66 windows #0-0] Session ID: 0fa689bb8b4fb47b83f8e343983d1059
[chrome 87.0.4280.66 windows #0-0]
[chrome 87.0.4280.66 windows #0-0] Login
[chrome 87.0.4280.66 windows #0-0]     As a user, I recieve an error message when using invalid credentials to log into the application
[chrome 87.0.4280.66 windows #0-0]        ✓ Given I am on the login page
[chrome 87.0.4280.66 windows #0-0]        ✓ When I login with ############ and empty_string
[chrome 87.0.4280.66 windows #0-0]        ✓ Then I should see an error message saying The password field is empty.
[chrome 87.0.4280.66 windows #0-0]
[chrome 87.0.4280.66 windows #0-0]     As a user, I recieve an error message when using invalid credentials to log into the application
[chrome 87.0.4280.66 windows #0-0]        ✓ Given I am on the login page
[chrome 87.0.4280.66 windows #0-0]        ✓ When I login with empty_string and ############
[chrome 87.0.4280.66 windows #0-0]        ✓ Then I should see an error message saying The username field is empty.
[chrome 87.0.4280.66 windows #0-0]
[chrome 87.0.4280.66 windows #0-0]     As a user, I can login
[chrome 87.0.4280.66 windows #0-0]        ✓ Given I am on the login page
[chrome 87.0.4280.66 windows #0-0]        ✓ When I login as an admin
[chrome 87.0.4280.66 windows #0-0]        ✓ Then I should be on the admin dashboard page
[chrome 87.0.4280.66 windows #0-0]
[chrome 87.0.4280.66 windows #0-0] 9 passing (9.6s)


Spec Files:      1 passed, 1 total (100% completed) in 00:00:14
```
