### ISSUE TITLE
Chaining issue after upgrading from 2.4.5 to 3.0.0

### ISSUE THREAD

**Issue by sean-hill** [webdriverio/webdriverio#619]
Hey I used to have this custom login command like so:	

	client.addCommand('login', function (url, usernameSelector, usernameValue, passwordSelector, passwordValue, submitSelector, callback) {

		this
			.url(url)
			.addValue(usernameSelector, usernameValue)

		if (passwordSelector && passwordValue) {
			this.addValue(passwordSelector, passwordValue)
		}

		this.click(submitSelector, callback)

	});

Which would be called like this:

	client
		.init()
		.login('http://www.google.com', '#username', 'sean', '#password', 'password', '#submit')
		.end()

Which should would be equivalent (I think) as this:

	client
		.init()
		.url('http://www.google.com')
		.addValue('#username', 'sean')
		.addValue('#password', 'password')
		.click('#submit')
		.end()

However, after upgrading to 3.0.0, it now skips over typing in the `usernameValue` when using my custom `login` command. Thoughts?

**Comment by christian-bromann** [comment]
Yeah. In `v3` every command is a promise. So instead of having the callback as last command you need to return a promise. As soon as this promise resolves the custom command finishes. So you should change your login method like this:

```js
client.addCommand('login', function (url, usernameSelector, usernameValue, passwordSelector, passwordValue, submitSelector) {

    return this
        .url(url)
        .addValue(usernameSelector, usernameValue).then(function() {
            if (passwordSelector && passwordValue) {
                return this.addValue(passwordSelector, passwordValue);
            }
        }).then(function() {
            return this.click(submitSelector);
        });

});
```

**Comment by sean-hill** [comment]
You're the best :+1:
