### ISSUE TITLE
Wdio for VSCode. 

### ISSUE THREAD

**Issue by QAtester111** [webdriverio/webdriverio#6196]
I am a beginner and trying to run a project on Vscode. the project was working fine on webstorm. 

Wdio command not recognized on VS code , whereas working fine on webstorm.  When I give path like ./node_modules/.bin/wdio wdio.conf.js Then it works fine in vscode. 
I have searched alot but couldn't find anything on that, please help before closing the issue. 
here is the terminal:

```
PS E:\Project> **wdio wdio.conf.js**
wdio : The term 'wdio' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of 
the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ wdio wdio.conf.js
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (wdio:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


Suggestion [3,General]: The command wdio was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\wdio". See "get-help about_Command_Precedence" for more details.
```

**Comment by christian-bromann** [comment]
@QAtester111 thanks for filing the issue. Please have a look into the [getting started guide](https://webdriver.io/docs/gettingstarted.html) on how to you get up and running with WebdriverIO. It should work independent from which IDE you are using.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
