### ISSUE TITLE
(Mocks and Spies) browser.mock stub leaks from preceding scenarios

### ISSUE THREAD

**Issue by ManjunathDamo** [webdriverio/webdriverio#6197]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [ 6.10.5]
 - **Mode:** [Standalone mode ]
 - **WDIO Testrunner, running sync**
 - **Node.js version:** [ 12+]
 - **NPM version:** [6+]
 - **Browser name and version:** [Chrome 85+]
 - **Additional wdio packages used (if applicable):** "@wdio/cucumber-framework": "^6.10.4", "wdio-chromedriver-service": "^6.0.4",
- **Config of WebdriverIO** - basic config generated for Cucumber wdio framework

**Describe the bug**
browser.mock().respond Always Return first Stub even when Mocking same service with different stub 

**To Reproduce**
**Feature File:** 
```
Feature: Use WDIO browser mock

    Scenario: Mock Google to WDIO
        Given I mock the requested URL to WDIO
        When I navigate to Google
        Then I Print Page name

    Scenario: Mock Google to WDIO
        Given I mock the requested URL to GITHUB
        When I navigate to Google
        Then I Print Page name
```
**Step Definition File:**

```
import { Given, Then, When } from 'cucumber';

When(/^I mock the requested URL to WDIO$/,() => {
    const pageMock = browser.mock('https://google.com/');
    pageMock.respond('https://webdriver.io');
});

When(/^I mock the requested URL to GITHUB$/,() => {
    const pageMock = browser.mock('https://google.com/');
    pageMock.respond('https://github.com/');
});

Given(/^I navigate to Google$/, () => {
    browser.url('https://google.com');
});

Then(/^I Print Page name$/, () => {
    browser.url('https://google.com');
    console.log('Current Url',browser.getTitle());
});

```

**Expected Behaviour**
Should Print :
 Current Url  WebdriverIO · Next-gen browser and mobile automation test framework for Node.js
 Current Url GitHub: Where the world builds software · GitHub

**Actual Behaviour**
Prints :
Current Url  WebdriverIO · Next-gen browser and mobile automation test framework for Node.js
Current Url  WebdriverIO · Next-gen browser and mobile automation test framework for Node.js

Apologies if any format mismatch. Thanks in advance.

**Comment by mgrybyk** [comment]
You should restore mock before using respond command again

**Comment by ManjunathDamo** [comment]
Thanks, it Works. But is there a way to restore all mocks together with single command ? In case we mock multiple service ?

**Comment by mgrybyk** [comment]
No, see https://github.com/webdriverio/webdriverio/issues/6003

**Comment by mgrybyk** [comment]
Should I close this one in such case?

**Comment by ManjunathDamo** [comment]
Yes we can close this ., I will follow up [#6003](https://github.com/webdriverio/webdriverio/issues/6003). Thanks
