### ISSUE TITLE
Upload file function doesn't work for Safari

### ISSUE THREAD

**Issue by Ridhib** [webdriverio/webdriverio#6200]
I am trying to use the upload file function, it works fine in Chrome but doesn't work in Safari. 
 upload(selector, filePath) {
    browser.execute(
      // assign style to elem in the browser
      el => (el.style.display = 'block'),
      // pass in element so we don't need to query it again in the browser
      selector,
    );
    const remotepath = browser.uploadFile(path.join(__dirname, '..', filePath));
    selector.addValue(remotepath);
    return this;
  }

**Comment by christian-bromann** [comment]
@Ridhib thanks for filing the issue. Uploading a file is indeed not supported in Safari. There is nothing WebdriverIO can do about this. We will add a note to the docs pointing this out better. We recommend to use the `@wdio/selenium-standalone-service` to make it work there.
