### ISSUE TITLE
addCommand with async package

### ISSUE THREAD

**Issue by sean-hill** [webdriverio/webdriverio#621]
Hey there, I was curious how I could create a custom command while utilizing the `async` npm package. Below is an example of what I'd like to do, but I'm no sure how to return the results.

	// Custom Command

	var async = require('async');

	client.addCommand('asyncExample', function(){

		var self = this;

		self.elements('#example', function(err, elements){

			async.parallel({

				first: function(done) {

					self.elementIdText(elements.value[0].ELEMENT, function(err, text) {
						return done(null, text.value);
					});

				},
				second: function(done) {

					self.elementIdText(elements.value[1].ELEMENT, function(err, text) {
						return done(null, text.value);
					});

				}

			}, function(err, results){

				// results: {
				//		first: 'text', second: 'text'
				// }

				// How do I end the custom command and send back "results"?
				
			});

		});

	});

	// Implementation

	client
		.init()
		.url('http://www.example.com')
		.asyncExample(function(err, results){
			console.log(results);
		})
		.end()

I also feel like I lost a lot of functionality now that I can't hand a callback that I can call to finish my custom command. For instance, with v2 I could have just have returned:

    return callback(null, results);

And wa la, it would have worked, but now with promises I don't know what to do.

**Comment by sean-hill** [comment]
Got it. Like @christian-bromann said... :smile: ... every command needs to return a promise. So I had to `npm install q`, and then used the following code:

    client.addCommand('asyncExample', function(){

        var Q = require('q');
        var self = this;
        var defer = Q.defer();

        self.elements('#example', function(err, elements){

            async.parallel({

                // Same as above...

            }, function(err, results){

                defer.resolve(results);

            });

            return defer.promise;

        });

    });

Just to verify with @christian-bromann is this the correct way to implement it?

**Comment by christian-bromann** [comment]
Well, I don't think you need async AND q to handle that, just chain your promises with then or if you want to run stuff in parallel use Q.all. Here would be my version of your custom command from above:

```js
client.addCommand('asyncExample', function(){

    var self = this;

    return self.elements('#example').then(function(elements) {
        var result = {};

        return self.elementIdText(elements.value[0].ELEMENT, function(err, text) {
            result.first = text.value;
        }).then(function(first) {
            return self.elementIdText(elements.value[1].ELEMENT);
        }).then(function(text) {
            result.second = text.value;
        }).then(function() {
            return result;
        });

    });

});
```

Sure if you feel more comfortable with using async and Q, do that! Both ways are ok.

**Comment by sean-hill** [comment]
Dude, you're genius, I'm glad I asked, thanks!

**Comment by christian-bromann** [comment]
just updated the example
