### ISSUE TITLE
how to check latest webdriver version and update 

### ISSUE THREAD

**Issue by IdeasRahulVerma** [webdriverio/webdriverio#6210]
Can't connect to WebDriver.
Error: Failed to create session.
session not created: This version of ChromeDriver only supports Chrome version 85
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'DLLE-PC', ip: '192.168.43.220', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_231'
Driver info: driver.version: unknown
remote stacktrace: Backtrace:
        Ordinal0 [0x006ED383+3134339]
        Ordinal0 [0x005DA171+2007409]
        Ordinal0 [0x0047AEE8+569064]
        Ordinal0 [0x0040139F+70559]
        Ordinal0 [0x003FCC63+52323]
        Ordinal0 [0x00420DFC+200188]
        Ordinal0 [0x00420C1D+199709]
        Ordinal0 [0x0041EB0B+191243]
        Ordinal0 [0x00402E77+77431]
        Ordinal0 [0x00403E3E+81470]
        Ordinal0 [0x00403DC9+81353]
        Ordinal0 [0x005F0CD9+2100441]
        GetHandleVerifier [0x0085B75A+1396954]
        GetHandleVerifier [0x0085B3D9+1396057]
        GetHandleVerifier [0x00867126+1444518]
        GetHandleVerifier [0x0085BCE8+1398376]
        Ordinal0 [0x005E7F51+2064209]
        Ordinal0 [0x005F22EB+2106091]
        Ordinal0 [0x005F2411+2106385]
        Ordinal0 [0x006049C4+2181572]
        BaseThreadInitThunk [0x759033AA+18]
        RtlInitializeExceptionChain [0x77E69F72+99]
        RtlInitializeExceptionChain [0x77E69F45+54]

Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible

###How to update chromedriver ?

**Comment by mgrybyk** [comment]
Please see https://webdriver.io/docs/selenium-standalone-service.html

You can specify which chromedriver version to use.
Make sure to update all the packages to latest versions.

Use gitter for this kind of questions.
Thanks
