### ISSUE TITLE
touchAction can not run when WinAppDriver ran without appium

### ISSUE THREAD

**Issue by serhatbolsu** [webdriverio/webdriverio#6211]
**Environment (please complete the following information):**
 - **WebdriverIO version: 6.8.1
 - **@wdio/appium-service**  : 6.8.0

**Describe the bug**
I am testing Windows Application using WinAppDriver. Running the driver is possible without lunching through Appium. 
If I run without appium, `touchAction` is not forwarded to driver. Although driver is capable of handling the `touchAction`

**To Reproduce**
Any touch action command

**Expected behavior**
Touchaction shall be used with WinAppDriver.

**Log**
[undefined windows #0-0] touchAction can be used with Appium only.
[undefined windows #0-0] Error: touchAction can be used with Appium only.
[undefined windows #0-0]     at Browser.exports.touchAction (C:\repos\thick-client-test-framework\node_modules\webdriverio\build\commands\constant.js:58:15)
[undefined windows #0-0]     at Browser.touchAction (C:\repos\thick-client-test-framework\node_modules\webdriverio\build\commands\browser\touchAction.js:5:35)
[undefined windows #0-0]     at Browser.runCommandWithHooks (C:\repos\thick-client-test-framework\node_modules\@wdio\sync\build\wrapCommand.js:70:34)
[undefined windows #0-0]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[undefined windows #0-0]     at Browser.runCommandWithHooks (C:\repos\thick-client-test-framework\node_modules\@wdio\sync\build\wrapCommand.js:65:24)
[undefined windows #0-0]     at Browser.touchAction (C:\repos\thick-client-test-framework\node_modules\@wdio\sync\build\wrapCommand.js:44:44)
[undefined windows #0-0]     at AlarmPage.deleteAlarm (C:\repos\thick-client-test-framework\pages\/Alarm.js:51:13)
[undefined windows #0-0]     at Context.<anonymous> (C:\repos\thick-client-test-framework\tests\/alarm.spec.js:28:15)
[undefined windows #0-0]     at Context.executeSync (C:\repos\thick-client-test-framework\node_modules\@wdio\sync\build\index.js:25:22)!

**Comment by christian-bromann** [comment]
> Although driver is capable of handling the `touchAction`

The error in the logs (`touchAction can be used with Appium only.`) is actually coming from WinAppDriver. WebdriverIO doesn't throw this.

Closing as it is a limitation of the driver and not WebdriverIO.

**Comment by serhatbolsu** [comment]
@christian-bromann  actually , i think its here->
https://github.com/webdriverio/webdriverio/blob/e78ecef891b2de4a2f7c198117d35db8debf1c68/packages/webdriverio/src/commands/constant.ts

**Comment by christian-bromann** [comment]
@serhatbolsu does WinAppDriver has documentation about what it supports? WebdriverIO assigns protocol commands based on the assumption which driver is being used. All [Appium protocol commands](https://webdriver.io/docs/api/appium.html) are currently only assigned if the capabilities indicate an Appium session. If WinAppDriver also supports a subset of these commands we need to change that logic.

**Comment by serhatbolsu** [comment]
Yes WinAppDriver supports touchActions, even when I open appium (winappdriver can run by itself, or through appium) they are correctly propagated to win app driver. 
Here is a full list, they claim to support -> [supported api list](https://github.com/microsoft/WinAppDriver/blob/master/Docs/SupportedAPIs.md)

**Comment by christian-bromann** [comment]
> Yes WinAppDriver supports touchActions

Apparently not, there is no endpoint that defines `/session/:sessionId/touch/perform` which is required to use `touchActions`. You can however use the `touchPerform` command.

**Comment by serhatbolsu** [comment]
I have not seen it working yet, however there are examples in their Regression suite
https://github.com/microsoft/WinAppDriver/blob/master/Tests/Input/TouchScenarios.cs

Do you mean, they only support single touch functions but not as action and combination of actions?

**Comment by christian-bromann** [comment]
> Do you mean, they only support single touch functions but not as action and combination of actions?

Correct.

**Comment by christian-bromann** [comment]
I am going ahead and close this as it isn't something we can fix in WebdriverIO. I recommend to raise an issue in the WinAppDriver project. Thanks!

**Comment by serhatbolsu** [comment]
thank you
