### ISSUE TITLE
Unable to simulate Select+All only under OS X

### ISSUE THREAD

**Issue by astoilkov** [webdriverio/webdriverio#622]
I have tried to simulate `Select+All` under OS X but without success. Everything works fine under Windows.

The code below works under Windows but not under Mac. The text never gets selected.

```
var CTRL_CMD = process.platform == 'darwin' ? 'Command' : 'Control';

it('test', function () {
  client.keys('some text');
  client.keys(CTRL_CMD); // the value here is correct
  client.keys('a'); // also tried with uppercase A
  client.keys(CTRL_CMD);
});
```

Update: I also tried using `Meta` and `\uE03D`

**Comment by christian-bromann** [comment]
You need to pass an array to the keys command instead of calling it multiple times:

```js
var webdriverio = require('webdriverio');
var client = webdriverio.remote({
    desiredCapabilities: {
        browserName: 'firefox'
    }
});
var CTRL_CMD = process.platform == 'darwin' ? 'Command' : 'Control';

client
    .init()
    .url('http://webdriverjs.christian-bromann.com/')
    .setValue('.searchinput', 'test')
    .keys([CTRL_CMD, 'a', 'c'])
    .pause(5000)
    .end();
```

**Comment by christian-bromann** [comment]
Seems to not work with Chrome though. An chromedriver [issue](https://code.google.com/p/selenium/issues/detail?id=5358&noredir=1) is already created

**Comment by astoilkov** [comment]
Thanks.

**Comment by astoilkov** [comment]
The issue was created in 2013 and is now closed. Do you think I should create a new one?

**Comment by christian-bromann** [comment]
This might be related to https://code.google.com/p/chromedriver/issues/detail?id=581&colspec=ID%20Status%20Pri%20Owner%20Summary .. but yes probably makes sense to check for similar issues first and then file an issue here: https://code.google.com/p/chromedriver/issues/list

**Comment by michahell** [comment]
Again experiencing the same problem.
I have tried the following, and nothing works, unfortunately on Mac OSX on chrome.

```javascript
.keys(['U+E03D', 'a', 'U+E000']).pause(2500)
.keys(['U+E03D', 'a', 'U+E03D']).pause(2500)
.keys(['Command', 'a', 'Command']).pause(2500)
.keys(['Command', 'a', 'Null']).pause(2500)
```

Within starting to use webdriver.io, running into 3 unresolved (or hard to resolve) issues within 2 days :( I cannot help but wonder if [this is used for automated testing](https://github.com/auchenberg/volkswagen) @ webdriverio. (hint: thats a joke, of course)

**Comment by michahell** [comment]
Actually, passing ANY unicode character to chrome does not work. I've just tried the backspace character like so:

```javascript
.keys(['U+E003']).pause(1500) // backspace unicode
.keys(['U+0008']).pause(1500) // backspace ASCII
```
...which also does not work :/
Do people actually test more then clicking a few buttons here and there ? :/

**Comment by christian-bromann** [comment]
@michahell I am sorry that you had a bad experience. But please be aware of the fact that WebdriverIO is not responsible for problems related to the Selenium framework. In general I think that copy&paste should not be part of your e2e test since it's not a functionality of your app but rather one of your browser.

Also nice joke but note that this is an open source project and we do this for free and in our free time. So if you find a bug, feel free to fix it and open a PR instead of blaming the contributor!

**Comment by michahell** [comment]
I'm sorry about the joke, I understand this is the case for open source projects.
I meant that sending non text keyboard input (control / command / backspace) seems like a big feature that people would use, which is apparently not the case, otherwise this would have been detected earlier.

The original bug title is: "Unable to simulate Select+All only under OS X" which is not related to copy & paste at all, neither is the (bigger) bug that sending *any* Unicode character does not seem to work on OSX (I am not trying to copy + paste, I'm trying to simulate user input into a textfield.) 

Do you want me to open a separate issue for this?

**Comment by christian-bromann** [comment]
I tried the following with Firefox:

```js
var webdriverio = require('webdriverio');
var client = webdriverio.remote({
    desiredCapabilities: {
        browserName: 'firefox'
    }
});

client
    .init()
    .url('http://webdriverjs.christian-bromann.com/')
    .setValue('.searchinput', 'test')
    .keys(['Command','a', 'c', 'v', 'v'])
    .pause(5000)
    .end();
```

And it works. So it is apparently a bug in Chromedriver as I mentioned above. Feel free to open an issue there.

**Comment by michahell** [comment]
I see, thank you. I missed the original chromeDriver issue link. Apparently that issue is still unresolved and this is indeed not a webdriverIO issue, I did not notice.

**Comment by astoilkov** [comment]
Hi,

Just to add a little information to help with the case. I have been struggling with this issue for some time. There have been a opened bug related with that but after being resolve the issue still persisted. I have opened issue myself but waiting to get resolved. I also can't understand how it is possible such an issue not getting resolved for so much time.

You can take a look at this: https://code.google.com/p/chromium/issues/detail?id=518178&can=8&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified

Hope this helps.

**Comment by zackster** [comment]
Has anyone got this working recently?

I've tried ["Meta', 'A', 'NULL'] . and ['Meta', 'A', null].  Neither work.
I have resorted to the fact that:

- I'm going to have to use this pattern for select all: 

`
let keySequence = ['Shift'];
    for(let i = tetLength; i > 0; i--) {
        keySequence.push(["ArrowLeft"])        
    }
browser.keys(keySequence);
`

- For our Electron app, we're going to have to use CONTROL for our keyboard shortcuts if node.env === 'test'

**Comment by chandanrayarm** [comment]
Hi there I'm trying to work Option+Command+W key to work but its not working can someone help me here as client.keys(['Option, 'Command', 'W']);

**Comment by chandanrayarm** [comment]
Hi @christian-bromann do you have any idea that chrome can handle multiple keys like -  keys(['Option, 'Command', 'W']) ?

**Comment by rashedul-haque-ideascale** [comment]
Ahh 5 years later I am trying to simulate Command + A on Mac and it works fine when I run my test on the browser, but when I try to run the same code in a headless browser mode, it does not work! I have been struggling for a few days but still no luck finding any solution to this!
