### ISSUE TITLE
@wdio/selenium-standalone-service - TypeError: require(...) is not a function

### ISSUE THREAD

**Issue by ArminazK** [webdriverio/webdriverio#6235]
- **WebdriverIO version:** 6.10.10
 - **Mode:** wdio
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.20.0
 - **NPM version:** 6.14.8
 - **Browser name and version:** Chrome 87.0.4280.88
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/selenium-standalone service

**Config of WebdriverIO**
According to example

**Describe the bug**
Error on starting test:
`Error: Couldn't initialise "@wdio/selenium-standalone-service".
TypeError: require(...) is not a function
    at Object.<anonymous> (...\node_modules\selenium-standalone\lib\install.js:12:50)`

**To Reproduce**
Run any simple test

**Expected behavior**
Test to be executed.

**Workaround**
Remove tailing parentheses here selenium-standalone\lib\install.js:12: const defaultConfig = require('./default-config')();
Remove tailing parentheses here selenium-standalone\lib\start.js:12: const defaultConfig = require('./default-config')();

Any fix or explanation?

Thanks a lot!

**Comment by mgrybyk** [comment]
Please update @wdio packages to the latest versions, try deleting node_modules folder, package-lock.json, and installing packages again.

**Comment by ArminazK** [comment]
I do have latest @wdio versions.
Deleted node_modules, package.lock file and reinstalled again.
The same issue appears on new fresh PC as well.

**Comment by christian-bromann** [comment]
Just checked and had no issues.

**Comment by ArminazK** [comment]
Thank you Christian for forcing me to check more. My bad. My corporate artifactory was messing with packages :(
Everything works fine now. 👍
