### ISSUE TITLE
devtools past 6.6.4 breaks AWS lambda-chromium

### ISSUE THREAD

**Issue by pmerwin** [webdriverio/webdriverio#6238]
It looks like after 6.6.4 of the devtools service, our lambda-chromium build is failing to connect using devtools back end:

ERROR @wdio/runner: Error: connect ECONNREFUSED 127.0.0.1:34285

Builds that succeed are using hostname:localhost and connect just fine, but if we move past 6.6.4 it breaks. I saw there is a new config object that can be passed into devtools service:

 // this['wdio:devtoolsOptions'] = {
        //     // debuggerAddress: 'localhost',
        //     headless: true,
        //     incognito: true,
        //     ignoreDefaultArgs: false
        // };
I am trying that and still getting a connection refused error. Any suggestions and what we need to do to make it work past 6.6.4?

Are there any docs that I am missing that explain any changes that would cause this?

**Comment by christian-bromann** [comment]
Logs would be helpful. I am not aware of any breaking changes that could cause this.

**Comment by pmerwin** [comment]
failing test log: https://gist.github.com/pmerwin/a22b397b684c281175ccf6cb9332cc50
passign test log:  https://gist.github.com/pmerwin/1be14e8a481030adbad131a5ca06459c

I wish I could provide more / better logs but this is all I get ^

**Comment by christian-bromann** [comment]
Please update your WebdriverIO version and try again. The issue should be fixed now.
