### ISSUE TITLE
Unable to Click on Button in Safari

### ISSUE THREAD

**Issue by Askarov5** [webdriverio/webdriverio#6241]
Testing angular 1 web application. Completed an automation project for angular 2 app and everything worked fine. Started another project for the company's main web application which was built on angular 1 JS. Automated Login Page and run the tests on chrome, everything works fine. But the same code could not click on a button(Sign in) and failed on safari. (Could not click all buttons - By passed login form by using browser.keys('\uE007'); and tried to continue, still failed)

**Environment (please complete the following information):**
 - **WebdriverIO version:** 
 - @wdio/cli@6.10.5
     │── webdriverio@6.10.5 
  └─┬ @wdio/local-runner@6.10.5
         └─┬ @wdio/runner@6.10.5
                └── webdriverio@6.10.5 
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 14.15.1
 - **NPM version:**  6.14.8
 - **Browser name and version:** Safari 14.0.2.
 - **Platform name and version:** macOS Big Sur v11.1
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
capabilities: [{
            maxInstances: 1,
            browserName: 'safari',
            port: 4445
         }]

**Describe the bug**
Unable to click on a button in Angular 1 application in Safari(not sure if its angular version but everything works fine in Angular 2). isClickable() returns true. The same code works in chrome fine.

**To Reproduce**
Steps to reproduce the behavior: our application is behind the firewall, you can try with any other angular 1 applications.

[Include code or an example repository that can easily be set up]

**Expected behavior**
Click on a button

**Log** (Login page: {fill user cred.} click on a button and wait for the Header of home page)
[0-0] 2020-12-16T19:56:01.803Z INFO webdriver: RESULT true
Clickable true
2020-12-16T19:56:01.804Z INFO webdriver: COMMAND findElement("xpath", ".//button[normalize-space() = "SIGN IN"]")
2020-12-16T19:56:01.804Z INFO webdriver: [POST] http://localhost:4445/session/B951A935-A8E4-44C4-ABA8-F7FA6C278BE8/element
2020-12-16T19:56:01.804Z INFO webdriver: DATA { using: 'xpath', value: './/button[normalize-space() = "SIGN IN"]' }
[0-0] 2020-12-16T19:56:01.809Z INFO webdriver: RESULT {
  'element-6066-11e4-a52e-4f735466cecf': 'node-4DCFDC10-2500-48E9-86AC-7D114264EADE'
}
[0-0] 2020-12-16T19:56:01.810Z INFO webdriver: COMMAND elementClick("node-4DCFDC10-2500-48E9-86AC-7D114264EADE")
2020-12-16T19:56:01.810Z INFO webdriver: [POST] http://localhost:4445/session/B951A935-A8E4-44C4-ABA8-F7FA6C278BE8/element/node-4DCFDC10-2500-48E9-86AC-7D114264EADE/click.     >>>Inside of the link:{"value":{"error":"unknown method","message":"","stacktrace":""}} <<<<
[0-0] 2020-12-16T19:56:01.829Z INFO webdriver: COMMAND findElement("xpath", ".//h1[normalize-space() = "BACP Queue"]")
2020-12-16T19:56:01.830Z INFO webdriver: [POST] http://localhost:4445/session/B951A935-A8E4-44C4-ABA8-F7FA6C278BE8/element

**Additional context**
devDependencies": {
    "@wdio/allure-reporter": "^6.8.1",
    "@wdio/cli": "^6.10.5",
    "@wdio/local-runner": "^6.10.5",
    "@wdio/mocha-framework": "^6.10.4",
    "@wdio/spec-reporter": "^6.8.1",
    "@wdio/sync": "^6.10.4",
    "allure-commandline": "^2.13.0",
    "chromedriver": "^87.0.2",
    "wdio-chromedriver-service": "^6.0.4"
  }

> Please use the correct markdown

**Comment by christian-bromann** [comment]
> on chrome, everything works fine. But the same code could not click on a button(Sign in) and failed on safari.

I am sorry to say that unfortunately there is nothing WebdriverIO can do here. There are numerous issues [reported](https://developer.apple.com/forums/thread/98188) on that. I recommend to report this at feedbackassistant.apple.com. Thanks!

**Comment by Askarov5** [comment]
Using Safari Technology Preview solved this issue for me. Configurations:
capabilities: [
        {
            maxInstances: 1,
            browserName: 'safari technology preview',
            //>Run In terminal to run safari preview driver: /Applications/Safari\ Technology\ Preview.app/Contents/MacOS/safaridriver --port 4444
            port: 4444
        }
    ]

**Comment by ryan-cubic** [comment]
this issue is gone when the app under test upgraded to angular v16 and using safari v17.4.1
