### ISSUE TITLE
@wdio/devtools-service currently only supports Chrome version 63 and up error

### ISSUE THREAD

**Issue by FelixZilber** [webdriverio/webdriverio#6243]
I'm getting the next error "@wdio/devtools-service currently only supports Chrome version 63 and up..." while using the latest devtools 6.10.11. All other packages up to date as well.

Looks like the problem in wdio-devtools-service/src/index.ts:

` beforeSession (_: WebdriverIO.Config, caps: WebDriver.DesiredCapabilities) {
        if (!isBrowserSupported(caps)) {
            return log.error(UNSUPPORTED_ERROR_MESSAGE)
        }
        this._isSupported = true
    }`

here instead of capabilities, it gets a list of specs to run,
 which cause `!isBrowserSupported(caps)` to return false

**Comment by christian-bromann** [comment]
This has been fixed with the latest release. Thanks for reporting.
