### ISSUE TITLE
v3 client error handling

### ISSUE THREAD

**Issue by sean-hill** [webdriverio/webdriverio#625]
Hey I used to have this:

    client.on('error', function(e) {
        console.log(e.body.value.class);
        console.log(e.body.value.message);
    });

But after upgrading to v3 my `e` object looks like this:

	{ 
		message: 'An element could not be located on the page using the given search parameters.',
	  	type: 'NoSuchElement',
	  	stack: undefined 
	}

Are the docs just outdated, or is something wrong?

**Comment by christian-bromann** [comment]
this got already fixed here: https://github.com/webdriverio/webdriverio/commit/431072883d0f4585eba981bcdfa78244eee11dfa#diff-3b660a335cd0d5e1c680f02c2a2a8c70R89
and will be published tomorrow :wink:

**Comment by sean-hill** [comment]
Great! So what will the error look like? How it used to be or how it is now?

**Comment by christian-bromann** [comment]
How it is now: error message, type and stack trace. Do you think any other information could be useful?

**Comment by christian-bromann** [comment]
fix released with `v3.1.0`

**Comment by sean-hill** [comment]
Um, can't think of anything right now :smile: Thanks @christian-bromann!

**Comment by sean-hill** [comment]
Hey @christian-bromann,

Just upgraded to `3.1.0`. I'm just doing a simple `addValue('#something')`, where `#something` doesn't exist on the page. So my `client.on('error')` picks it up fine, but is fired like 5 times in a row for the same error. I think this is a problem.

**Comment by christian-bromann** [comment]
dang .. yeah the error basically triggers up the promise chain. Could you create an new issue for this? Thanks!
