### ISSUE TITLE
webdriverio: setValue fails for edge(87) on browserstack

### ISSUE THREAD

**Issue by Michel73** [webdriverio/webdriverio#6257]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.10.11
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync 
 - **Node.js version:** v12.13.1
 - **NPM version:** 6.12.1
 - **Browser name and version:** Edge 87
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** 
  "@wdio/browserstack-service": "6.10.10",
    "@wdio/cli": "6.10.11",
    "@wdio/sync": "6.10.11",
    "webdriverio": "6.10.11",
    "@wdio/jasmine-framework": "6.10.11",
    "@wdio/local-runner": "6.10.13",
    "@wdio/spec-reporter": "6.10.6",
    "wdio-chromedriver-service": "6.0.4",

**Config of WebdriverIO**
Capabilities for edge:
```js
{
      'browserstack.local': true,
      'browserstack.console': 'verbose',
      'browserstack.debug': 'true',
      browserName: 'edge',
      browserVersion: 'latest',
      os: 'windows',
      os_version: '10'
}
...
```
before hook:
```js
before: async function(capabilities, specs) {
  try {

    await new Promise(async (resolve) => {
      let loginSuccessful = false;
      const maxTrials = 3;
      let i = 0;
      while (!loginSuccessful && i < maxTrials) {
        try {
          const login = await $('#kc-form');
          const userName = await login.$('#username');
          await userName.setValue('test');
          const password = await login.$('#password');
          await password.setValue('test');
          const submitBtn = await login.$('#kc-login');
          await submitBtn.click();
          loginSuccessful = true;
        } catch (e) {
          await browser.pause(1000);
          i++;
        }
      }
      if (loginSuccessful) {
        resolve();
      }
    });
  } catch (error) {
    throw new Error('Login failed after some retries');
  }

},
```

**Describe the bug**
I'm testing my application via `browserstack-service` for the browsers `firefox`, `chrome` and `edge`.
To enter my application I have to login first via identity-provider `keycloak` in the before-hook of `wdio.conf.js`. This works fine for `chrome`, `firefox`and even `edge v18.0`, but not for the latest `edge v80 - edge v87`.
I get an error `ERROR webdriver: Request failed with status 500 due to unknown error: unknown error` if I try to call `setValue` on an input-field - `userName.setValue('test')`.

**To Reproduce**

[Include code or an example repository that can easily be set up]

**Expected behavior**
The call of `setValue` should work as it does in `chrome` or `firefox`.

**Log**
https://gist.github.com/Michel73/1993d48f637eea6434bac3941c6e3665

**Additional context**

> Please use the correct markdown

**Comment by erwinheitzman** [comment]
What's the behavior of the code?

Also, the error is missing from the log that you provided.

**Comment by christian-bromann** [comment]
I recommend to reach out to the BS support team. WebdriverIO acts according to the WebDriver specification and doesn't do anything specific for Edge. This looks like a configuration issue on BS side.
