### ISSUE TITLE
Type 'BrowserObject' has no call signatures

### ISSUE THREAD

**Issue by qvalero** [webdriverio/webdriverio#6259]
Hello,

Since last update of webdriver io dependencies, which includes more and more typecript support, I have a new issue appearing.
I have created custom command, following https://webdriver.io/docs/typescript.html#adding-custom-commands

It concerns a swipe function with following declaration:
`export function swipe(this: WebdriverIO.BrowserObject, args: ISwipeArgs = {}): void {...}`

I have added the declaration in: ./types/index.d.ts file:

`    export interface BrowserObject {
        swipe: typeof import('../src/customCommands/swipe').swipe;
        cucumberWorld?: import('../src/step-definitions/world').JTWorld;
}`

On following command line: `driver.swipe({ direction: 'down' });` I have now the error: 
`error TS2349: This expression is not callable.
[build       ]   Not all constituents of type 'BrowserObject | ((this: BrowserObject, args?: ISwipeArgs) => void)' are callable.
[build       ]     Type 'BrowserObject' has no call signatures.`

What am I missing ? 
In tsconfig.json I have:
`   "types": [   
      "node",
      "@wdio/cucumber-framework",
      "@wdio/sync",
      "webdriver",
      "./types/"
    ],`

**Comment by erwinheitzman** [comment]
I'm missing the part where you declare the WebdriverIO scope in your type declaration file, do you have this namespace declared?

**Comment by qvalero** [comment]
Is it what you need?
`  "include": [
    "./src/**/*.ts"
  ]`
  
  My custom command is in ./src folder, and my type declaration file is on ./types folder

**Comment by erwinheitzman** [comment]
No I meant the part where you declare the WebdriverIO namespace in the `types/index.d.ts` file. Just like shown in the documentation

**Comment by qvalero** [comment]
Ah yes this is it:

`
declare namespace WebdriverIO {

    interface Config {
        automationProtocol: 'devtools' | 'webdriver';
        screenshotPath: string;
        logsSplitter?: import('../src/utils/logsSplitter').ClientLogsSplitter;
    }

    export interface ILogger {
        trace: (log: string) => void;
        debug: (log: string) => void;
        log: (log: string) => void;
        info: (log: string) => void;
        warn: (log: string) => void;
        error: (log: string) => void;
    }

    // override type definitions for $ and $$
    export interface Element {
        $(selector: import('../src/views/selector').IWdioSelector): Element;
        $$(selector: import('../src/views/selector').IWdioSelector): ElementArray;
    }

    export interface BrowserObject {
        swipe: typeof import('../src/customCommands/swipe').swipe;
        compareScreen(tag: string, options?: object): typeof import('wdio-native-app-compare-service');
        compareElement(element: object, tag: string, options?: object): typeof import('wdio-native-app-compare-service');
        saveScreen(tag: string): typeof import('wdio-native-app-compare-service');
        saveElement(element: object, tag: string, options?: object): typeof import('wdio-native-app-compare-service');
        cucumberWorld?: import('../src/step-definitions/world').JTWorld;
    }
}`

**Comment by christian-bromann** [comment]
@qvalero I recommend to update your WebdriverIO version to v7. We have overhauled the TypeScript setup and documented how you can enhance the browser object here: https://webdriver.io/docs/typescript#adding-custom-commands. If you like to help us investigate and fix the issue in v6 that would be awesome.
