### ISSUE TITLE
Docker process is hanging after execution of tests

### ISSUE THREAD

**Issue by AlexeyCL** [webdriverio/webdriverio#6261]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6
 - **Mode:** Docker/ wdio
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12
 - **NPM version:** 6.14
 - **Browser name and version:** Chrome 87
 - **Platform name and version:** Linux, Mac
 - **Additional wdio packages used (if applicable):** wdio-docker-service

**Config of WebdriverIO**
```
exports.config = {

    runner: 'local',

    specs: [
        './test/specs/**/*.js'
    ],
    exclude: [
    ],
    
    maxInstances: 10,
   
    capabilities: [
        {
            browserName: 'chrome',
            acceptInsecureCerts: true,
            'goog:chromeOptions': {
                args: ['--window-size=1920,1080', '--incognito', '-–ignore-certificate-errors', '--headless'],
            },
        },
    ],
    logLevel: 'info',
    bail: 0,
    baseUrl: 'http://localhost',
    
    waitforTimeout: 10000,

    connectionRetryTimeout: 120000,

    connectionRetryCount: 3,
    dockerOptions: {
        image: 'selenium/standalone-chrome',
        healthCheck: 'http://localhost:4444',
        options: {
            p: ['4444:4444'],
            shmSize: '2g'
        }
    },
    services: ['docker'],
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },
}
```

**Describe the bug**
For test execution, I'm using lerna, which executes tests with a docker. After the test execution, the docker process is stuck.
```
webdriverio-test: Spec Files:    2 passed, 2 total (100% completed) in 00:00:10 
webdriverio-test: 2020-12-24T11:00:43.516Z INFO @wdio/local-runner: Shutting down spawned worker
webdriverio-test: 2020-12-24T11:00:43.766Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
webdriverio-test: 2020-12-24T11:00:43.766Z INFO @wdio/local-runner: shutting dow
```

Important to notice, that without Lerna or another executor all works

**To Reproduce**
https://github.com/AlexeyCL/wdio-docker-lerna you can find a simple example

**Comment by mgrybyk** [comment]
I guess it's an issue of docker service, please raise an issue there https://github.com/stsvilik/wdio-docker-service

Let us know if you have any further questions.

**Comment by AlexeyCL** [comment]
@mgrybyk I think I found the issue, I'm waiting for PR review:https://github.com/stsvilik/wdio-docker-service/pull/93

**Comment by AlexeyCL** [comment]
@christian-bromann I think, you can delete the labels. I'm waiting for PR review https://github.com/stsvilik/wdio-docker-service/pull/93
