### ISSUE TITLE
webdriverio package has non-dev dependencies on @types

### ISSUE THREAD

**Issue by starpit** [webdriverio/webdriverio#6278]
**Is your feature request related to a problem? Please describe.**

The webdriverio npm has non-dev dependencies on a variety of `@types/...` packages. In particular, I would like to call out the lodash types. Thus, even if my project does not itself depend on lodash, my typescript build times are slowed down (pretty excessively; by about 40%) by having the lodash types installed. The 40% number comes from comparing `tsc` times, in my project, before and after manually rm -rf'ing `node_modules/@types/lodash*`

It is worth noting that Typescript gives me no straightforward way to "line item veto" a subset of typings. https://github.com/microsoft/TypeScript/issues/17042. Instead, it seems to blindly load in all of the typings for every compilation unit, whether or not they are used.

**Describe the solution you'd like**
Could you modify the `@types` to be devDeps?

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by christian-bromann** [comment]
There are some typings the WebdriverIO types rely on which need to remain production dependencies. But you are totally right that some types like the one from lodash should can be moved into the dev dependency section. Any contributions are highly appreciated.
