### ISSUE TITLE
wdio runner sometimes doesn't realize that a test has completed when running through gridlastic and report portal configured

### ISSUE THREAD

**Issue by chan-ai** [webdriverio/webdriverio#6290]
**Environment (please complete the following information):**
 - **WebdriverIO version:** ^5.18.7
 - **Mode:** [Testrunner mode]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [~8.9.4]
 - **NPM version:** [6.14.5]
 - **Browser name and version:** [Chrome ^87.0.2]
 - **Platform name and version:** [Windows 10]
 - **Additional wdio packages used (if applicable):**
 -  ["wdio-chromedriver-service": "^5.0.2",
    "wdio-reportportal-reporter": "^6.1.0",
    "wdio-reportportal-service": "^6.1.0",
    "@wdio/cli": "^5.18.7",
    "@wdio/dot-reporter": "^6.7.0",
    "@wdio/junit-reporter": "^6.4.0",
    "@wdio/local-runner": "^5.18.7",
    "@wdio/mocha-framework": "^5.18.7",
    "@wdio/spec-reporter": "^5.18.7",
    "@wdio/sync": "^5.18.7"]

**Config of WebdriverIO**
under package.json scripts section configure `"e2etest": "npx wdio run ./e2e/wdio.grid.conf.js",`

**Describe the bug**
wdio runner sometimes doesn't realize that a test has completed when running through gridlastic

**To Reproduce**
Configure report portal to display the report.
`const reportportal = require('wdio-reportportal-reporter');
  const RpService = require('wdio-reportportal-service');
define the conf;
reporters: [
    ['junit', {
      outputDir: './',
      outputFileFormat: function(options) { // optional
        return `results-${options.cid}.xml`
      }
    }],
    [reportportal, conf]
  ],`

Try to run a project which has couple of failures along with success. In my case my project has 200 tests with 40 failures.

**Expected behavior**
Once all the tests are completed execution, the jenkins job should finish with build status.

**Log**
Some logs.
[gist](https://gist.github.com/chan-ai/0ab19304a20c599bb277a73a516b6b4a) 

**Additional context**
If I disable the report portal plugin in the webdriver config, jenkins job doesn't halt. The job will finish with pass and failure status like below
`[0-73] 2021-01-05T18:19:40.933Z INFO webdriver: COMMAND closeWindow()
[0-73] 2021-01-05T18:19:40.934Z INFO webdriver: [DELETE] http://xyz.gridlastic.com:80/wd/hub/session/b17e271d142e86896f5e41ebec47fd24/window
[0-73] 2021-01-05T18:19:40.998Z INFO webdriver: RESULT []
[0-73] 2021-01-05T18:19:41.000Z INFO webdriver: COMMAND deleteSession()
[0-73] 2021-01-05T18:19:41.000Z INFO webdriver: [DELETE] http://xyz.gridlastic.com:80/wd/hub/session/b17e271d142e86896f5e41ebec47fd24
2021-01-05T18:19:41.301Z DEBUG @wdio/local-runner: Runner 0-73 finished with exit code 0
[0-73] PASSED in chrome - /e2e/specs/home/upcoming-tasks/engage-home-add-tasks.spec.js
2021-01-05T18:19:41.302Z INFO @wdio/cli:launcher: Run onComplete hook
************* reached on complete *************
********** results finished -77
********** results passed -57
********** results failed -20

Spec Files:	 57 passed, 20 failed, 77 total (100% completed) in 00:18:41 

2021-01-05T18:19:41.303Z INFO @wdio/local-runner: Shutting down spawned worker
2021-01-05T18:19:41.554Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2021-01-05T18:19:41.555Z INFO @wdio/local-runner: shutting down
[Pipeline] }`

Any help is appreciated. 
More logs [gist](https://gist.github.com/chan-ai/6a971fa7a96a6717d99415b616b25383.js)

**Comment by chan-ai** [comment]
@christian-bromann adding more logs.

**Comment by christian-bromann** [comment]
@chan-ai as I mentioned in the Gitter chat this issue is impossible for us to get you any support. The logs you provided aren't the one I requested and don't really show any clue of bug on WebdriverIO side. Please investigate first whether this is actually an issue in WebdriverIO or not a setup problem in your CI/CD system.
