### ISSUE TITLE
Inconsistent behavior using chrome args in DevTools

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#6294]
With the WebDriver protocol Chrome flags don't need to be prefixed with `--`. With DevTools this won't work and will result in Chrome opening a tab for every flag used, e.g.

![image](https://user-images.githubusercontent.com/731337/103897996-93645300-50f4-11eb-9c6a-deef70a696b5.png)

Let's make this consistent and ensure that in DevTools all args are prefixed with `--` [when launching the browser](https://github.com/webdriverio/webdriverio/blob/master/packages/devtools/src/launcher.ts#L92).

**Comment by devbret** [comment]
Hello, I am new to working on Open Source projects and I'd like to begin here. If this issue is still available, may I work on it? And if so, where is a good place to begin? Thank you for your help and time.

**Comment by christian-bromann** [comment]
Hi @devbret , unfortunately this bug has been already addressed by @rkeshwani in their PR #6294. Please have a look at the other `good first pick` issues. I am happy to help find something.
