### ISSUE TITLE
Returning Error object from execute

### ISSUE THREAD

**Issue by dangmai** [webdriverio/webdriverio#630]
Hi, first of all thank you for this great project - I find the API refreshingly clear and the monadic addition in v3 super cool. There's only one snag that I'm running into - for some reason whenever I try to return an Error object from browser context (from `execute` or `selectorExecute` for example), the result is blank. The following code demonstrates that:

```
var webdriverio = require("webdriverio");
var options = {
    host: "127.0.0.1",
    desiredCapabilities: {
        browserName: "chrome"
    }
};

var client = webdriverio.remote(options);
client
  .init()
  .url("https://news.ycombinator.com/")
  .execute(function () {
    return new Error("test error");
  })
  .then(function (result) {
    console.log(result);
  })
  .end();
```

The log would look something like this:
```
{ sessionId: 'dba9bb07-c725-4d2b-913d-182a883a03f9',
  status: 0,
  state: 'success',
  value: {},
  class: 'org.openqa.selenium.remote.Response',
  hCode: 1290608126 }
```

I can change the result type to other types of objects and they seem to work fine (e.g. `return { type: error, message: 'test error' };`), it's just the Error object that seems to be blanked out.

**Comment by christian-bromann** [comment]
> I find the API refreshingly clear and the monadic addition in v3 super cool

Glad you like WebdriverIO :+1: 

This is a chromedriver related issue. I tested it with PhantomJS and Firefox. Both return the error message and Firefox even returns a stack trace. Feel free to open an issue in the [chromedriver project](https://code.google.com/p/chromedriver/issues/list).

Why do you want to return an error object? If you would throw it you would get all information about the error.

**Comment by dangmai** [comment]
Thanks for answering @christian-bromann You are right, throwing the error makes a lot more sense. I believe I tried doing that a few days ago and the error handler didn't catch it, but you pushed some commits for v3.1 that fixed that issue so now the error's caught correctly.

Thanks again!
