### ISSUE TITLE
Test run successfully individually but failed for the whole test [WDIO]

### ISSUE THREAD

**Issue by dnomsed31** [webdriverio/webdriverio#6300]
Hi everyone, I'm new to webdriverio & I need some help here.

Whenever I run my test individually on VS Code Terminal, is working fine. Example: `npm run --suite netsalespage`

### _**wdio.conf.js**_

`specs: [
      './test/**/*.js'
  ],

suites: {
      loginpage: ["./test/loginPage.js"],
      signuppage: ["./test/signUpPage.js"],
      netsalespage: ["./test/netSalesPage.js"],
      salesorderpage: ["./test/salesOrderPage.js"]
},`
    
But the test will have some errors when I run as a whole `npm test`

It would prompt errors such as "Can't call selector" "Can't call element". I have already extended the timeout but it doesn't work, can anyone kindly advise?

**Comment by christian-bromann** [comment]
@dnomsed31 please provide some logs and a reproducible example if possible. It is really hard to understand what is going on.

**Comment by dnomsed31** [comment]
Hi @christian-bromann , thank you for replying, I managed to solve it by amending the maxinstances & extending the timeout in wdio.conf.js. 

However, I have another enquiry, I'm trying to check if the web application send the API request with the correct parameter. You can check the API call through the chrome inspect and see the network request by using wdio-intercept service. But I have no idea how I should begin with, any kind advise or any projects I can refer for understanding? 

Thank you for your time :)

**Comment by christian-bromann** [comment]
@dnomsed31 you can use WebdriverIOs [mocking capabilities](https://webdriver.io/docs/mocksandspies.html) for this. Join our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if your have further questions. Cheers!
