### ISSUE TITLE
Unable to provide custom sauce-job-name in after hook

### ISSUE THREAD

**Issue by AutomationReddy** [webdriverio/webdriverio#6301]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [6.5]
 - **Mode:** [WDIO Testrunner]
 - **Node.js version:** [>12]
 - **NPM version:** [>6]
 - **Browser name and version:** [Chrome]
 - **Platform name and version:** [Windows 10]
 - **Additional wdio packages used (if applicable):** [@wdio/sauce-service]

**Describe the bug**
Sauce service provides option to update the job name using `sauceOptions: setJobNameInBeforeSuite(boolean)`. However, my requirement is to update job name with a custom name and I am doing it in the after hook: `browser.execute('sauce:job-name=' + customName)`. But when I see the sauce labs results board, the job name is overriding with test suite title

**To Reproduce**
- Open a test in sauce labs
- Update the job name in afterhook or anywhere in before and after using `browser.execute('sauce:job-name=' + customName)`

**Sometimes, it updates the job name if there are any failures/no failures in the test** (Updates the custom name in 1/100th execution)
**Expected behavior**
Job name in SauceLabs should be customName and not the suite title

**Additional context**
After checking the sauce-service library, I am assuming, ```await this._api.updateJob(this._config.user as string, sessionId, body as Job)``` in `this.updateJob()` is updating the jobname back to the test suite name which is calling in after hook of sauce service.

in getBody method --> `body.name = this._suiteTitle`

```
 if (!this._browser.isMultiremote) {
            log.info(`Update job with sessionId ${this._browser.sessionId}, ${status}`)
            return this._isUP ? this.updateUP(failures) : this.updateJob(this._browser.sessionId, failures)
        }
```

**Comment by christian-bromann** [comment]
Any suggestions how this could be handled?

**Comment by wswebcreation** [comment]
@AutomationReddy 

Can you also explain when you see this behaviour? Is this with Sauce Desktop VMs or with Sauce Labs real devices?

**Comment by AutomationReddy** [comment]
@christian-bromann How about accepting one more option like customName(`job_name`) in sauceOptions. Wherever we are updating the jobname in sauce service library, we fist check customName(``) is not null and not empty, then update with custom name else keep the suiteTitle.

@wswebcreation It's happening with VMs and sim/emu. You can execute a test using sauce service and update sauce job-name using JS executer anywhere in before or after hooks. It is not updating with the name that we provide and overriding with the suite title.

**Comment by christian-bromann** [comment]
@AutomationReddy I suggest to have an additional sauce service options like `autoJobName` which is default `true` but can be set to `false` in which the service will not set the job name. What do you think @wswebcreation?

**Comment by wswebcreation** [comment]
@christian-bromann 

It's kinda strange that you can't update is in an after hook because the jobname is set in the before hook of the service. Should we just figure out why it isn't updating it before we introduce a new cap?

I can take a look at it today or tomorrow

**Comment by christian-bromann** [comment]
> I can take a look at it today or tomorrow

Sounds good. The job name is in fact set in the after hook as well.

**Comment by christian-bromann** [comment]
@wswebcreation thanks for creating a fix. @AutomationReddy I will release this in a second, please give it a try. Happy to re-open if issue still persist then.
