### ISSUE TITLE
Update Allure to v2

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#6313]
The `allure-js-commons` has been updated to v2 with TypeScript support. We should update our `@wdio/allure-reporter` to that version and improve our type definitions around it.

**Comment by alexmi256** [comment]
This would be really nice to have, I took a look at 
- https://github.com/allure-framework/allure-js/tree/master/packages/allure-js-commons
- https://github.com/allure-framework/allure-js-commons
And unfortunately this is definitely beyond me. 
The code almost looks like a rewrite and I saw nothing similar to an upgrade path being mentioned.

**Comment by lararojasmr** [comment]
I'm working on this. Let me try. I need this :)

**Comment by vovsemenv** [comment]
Hello from allure team 🚀. 
Is someone actively working on this? We getting issues like this in allure repo and i guess it's better to update allure-commons version to v2.

I can make PR if its fine

**Comment by christian-bromann** [comment]
@vovsemenv I don't think anyone is working on it currently. Any contributions are appreciated!

**Comment by BorisOsipov** [comment]
resolved in https://github.com/webdriverio/webdriverio/pull/9704
