### ISSUE TITLE
some callbacks no longer supported

### ISSUE THREAD

**Issue by Deothrin** [webdriverio/webdriverio#632]
The whats new page for version 3 states that you can continue to use callbacks but this does not seem to be the case. In particular, calling executeAsync like this:

`client.executeAsync(
  function (cb) { // do something on client },
  function (result) { // handle result }
)`

ends up attempting to pass the callback as the first parameter to the remote function. If this is not a bug would you mind making it clear in the docs that it is likely that using callbacks will break your code. I've also run into similar problems with custom commands no longer working in the switch to 3.

Matt

**Comment by christian-bromann** [comment]
@Deothrin you are right. These are breaking changes and not mentioned in our docs. Fixed that. All execute commands don't support callbacks anymore. Please receive your result like this:

```js
client.executeAsync( function (cb) { // do something on client }).then(function(res) { ... })
```

> I've also run into similar problems with custom commands

In `v2.x` the function parameter used to had a callback that should get called once you are done with
your steps. Here is an example:

```js
client.addCommand("getUrlAndTitle", function(customVar, cb) {
    this.url(function(err,urlResult) {
        this.getTitle(function(err,titleResult) {
            var specialResult = {url: urlResult.value, title: titleResult};
            cb(err,specialResult);
            console.log(customVar); // "a custom variable"
        })
    });
});
```

With `v3` we switched over to an promised based execution flow. Therefor the callback parameter is gone
and gets replaced by a promise you need to return in tha function. Once that promise is resolved the
command queue continues. The example above looks in `v3` like this:

```js
client.addCommand("getUrlAndTitle", function(customVar) {
    return this.url().then(function(urlResult) {
        return this.getTitle().then(function(titleResult) {
            console.log(customVar); // "a custom variable"
            return { url: urlResult.value, title: titleResult };
        });
    });
});
```

**Comment by Deothrin** [comment]
Thanks for the clarification, looks like it is time for me to fully embrace promises.

**Comment by astoilkov** [comment]
I have a question. Why you don't allow functions to be passed? Take a look at this scenario which I want to provide a callback as a parameter. 

```
client.addCommand('getSpellcheckRanges', function (callback) {
  return this.execute(function () {
    return window.editor.highlight.ranges.spellcheck;
  }).then(function (result) {
    // callback here is undefined
    callback(result.value);
  });
});
```

```
.getSpellcheckRanges(function (ranges) {
  expect(ranges).toBeFalsy();
})
```

I agree with the idea of promises. It's brilliant. However, in this scenario I think that my approach is more clear. Is there any problem for this to work as written above.

**Comment by christian-bromann** [comment]
How is your approach more clear when you can do that:

```js
client.addCommand('getSpellcheckRanges', function () {
  return this.execute(function () {
    return window.editor.highlight.ranges.spellcheck;
  }).then(function (result) {
    return result.value;
  });
});
```
```js
.getSpellcheckRanges().to.eventually.become(false)
```

**Comment by astoilkov** [comment]
Actually, I never though of that solution. This works great for me. Thanks.
