### ISSUE TITLE
beforeTest/afterTest hook -> together with beforeEach/afterEach doesn't work correctly.

### ISSUE THREAD

**Issue by paul-gladoon** [webdriverio/webdriverio#6325]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.11.3
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** v14.15.1
 - **Additional wdio packages used (if applicable):** "@wdio/mocha-framework": "6.4.7"

**Config of WebdriverIO**

```
const config = {
  ...wdioBuildConfig(),
  logLevel: 'silent',
  bail: 0,
  specs: ['./specs/**/*.ts'],
  waitforTimeout: 10000,
  connectionRetryTimeout: 120000,
  connectionRetryCount: 3,
  services: ['chromedriver'],
  framework: 'mocha',
  reporters: [['allure', {
      outputDir: 'allure-results',
      disableWebdriverStepsReporting: true,
      disableWebdriverScreenshotsReporting: false,
      disableMochaHooks: true
    }
  ]],
  beforeTest: async () => {
    console.log('BEFORE TEST')
  },
  afterTest: async () => {
    console.log('AFTER TEST')
  }
}
```

**Describe the bug**
beforeTest/afterTest hook -> together with beforeEach/afterEach doesn't work correctly.

**To Reproduce**
add to config:

```
beforeTest: async () => {
    console.log('BEFORE TEST')
  },
  afterTest: async () => {
    console.log('AFTER TEST')
  }
```

create a spec:

```
describe('SUITE 1', function() {
  beforeEach(async () => console.log('BEFORE EACH'))
  afterEach(async() => console.log('AFTER EACH'))

  it('IT 1', async function() {
    console.log('IT HERE')
  })
})
```

**Actual behavior**
OUTPUT:
[0-0] BEFORE EACH
[0-0] BEFORE TEST
[0-0] IT HERE
[0-0] AFTER TEST
[0-0] AFTER EACH

[Include code or an example repository that can easily be set up]

**Expected behavior**
EXPECTED OUTPUT:
[0-0] BEFORE TEST
[0-0] BEFORE EACH
[0-0] IT HERE
[0-0] AFTER EACH
[0-0] AFTER TEST

beforeTest -> must include beforeEach, also afterTest -> must include afterEach

**Comment by mgrybyk** [comment]
It works as designed.
If you want to run something before/after mocha beforeEach hook use webdriverio beforeHook and afterHook

**Comment by christian-bromann** [comment]
@paul-gladoon thanks for filing the issue. Unfortunately there are some limitation WebdriverIO has when registering such hooks in Mocha. They can't include the hooks registered for a `describe` block. Therefor the wdio hooks are only run before every `it` or `test` block. We recommend to register hooks that respect Mocha hooks in the test suite.

**Comment by Xotabu4** [comment]
If someone will find this issue: here is my workaround to make preconditions work in predicable order:

```javascript
before: function (capabilities, specs) {
        beforeEach(function () {
            console.log('Global Before test called')
            browser.url('/')
        }) 
},
```
