### ISSUE TITLE
Appium client failing to find element on  Android Chrome browser

### ISSUE THREAD

**Issue by only4arunkumar** [webdriverio/webdriverio#6332]
**Environment (please complete the following information):**
 - **WebdriverIO version:**6.12.0**
 
 - **Node.js version:** 14.15.4
 - **NPM version:** 6.14.10
 - **Browser name and version:** Chrome
 - **Platform name and version:** Android 11
 - **Additional wdio packages used (if applicable):** 
 - @wdio/appium-service": "^6.11.0",
    "@wdio/cli": "^6.12.0",
    "@wdio/local-runner": "^6.12.0",
    "@wdio/mocha-framework": "^6.11.0",
    "@wdio/spec-reporter": "^6.11.0",
    "@wdio/sync": "^6.11.0",
    "chromedriver": "^87.0.5",
    "wdio-chromedriver-service": "^6.0.4"

**.    **Config of WebdriverIO  mobile Browser Automation**.  **

const { config } = require('./wdio.shared.conf');

// ============
// Specs
// ============
config.specs = [
    './tests/specs/**/browser*.spec.js',
];

// ============
// Capabilities
// ============
// For all capabilities please check
// http://appium.io/docs/en/writing-running-appium/caps/#general-capabilities
config.capabilities = [
    {
        // The defaults you need to have in your config
        platformName: 'Android',
        browserName: 'chrome',
        maxInstances: 1,
        // For W3C the appium capabilities need to have an extension prefix
        // http://appium.io/docs/en/writing-running-appium/caps/
        // This is `appium:` for all Appium Capabilities which can be found here
        'appium:deviceName': 'Pixel_Defualt',
        'appium:platformVersion': '11',
        'appium:orientation': 'PORTRAIT',
        // `automationName` will be mandatory, see
        // https://github.com/appium/appium/releases/tag/v1.13.0
        'appium:automationName': 'UiAutomator2',
        'appium:newCommandTimeout': 240,
        'goog:chromeOptions': {
            w3c: true,
            // Add this option to prevent the annoying "Welcome"-message
            args: ['--no-first-run'],
        },
    },
];

exports.config = config;

**.     Shared config              **
exports.config = {
    // ====================
    // Runner and framework
    // Configuration
    // ====================
    runner: 'local',
    framework: 'jasmine',
    jasmineNodeOpts: {
        // Updated the timeout to 30 seconds due to possible longer appium calls
        // When using XPATH
        defaultTimeoutInterval: 90000,
        helpers: [require.resolve('@babel/register')],
    },
    sync: true,
    logLevel: 'debug',
    deprecationWarnings: true,
    bail: 0,
    baseUrl: 'http://the-internet.herokuapp.com',
    //baseUrl: 'https://motivation.vudoo.io/watch/12373082862',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    reporters: ['spec'],

    // ====================
    // Appium Configuration
    // ====================
    services: [
        [
            'appium',
            {
            // For options see
            // https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-appium-service
                args: {
                    // Auto download ChromeDriver
                    relaxedSecurity: true,
                    // chromedriverAutodownload: true,
                    // For more arguments see
                    // https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-appium-service
                },
                command: 'appium',
            },
        ],
    ],
    port: 4723,
};

------------**Describe the bug** -------------------
**To Reproduce**

Attempt to click on a button on Video Js player (nested in div) from android chrome browser was failing when using appium javascript client through webdriverio.

User was able to interact with the button on desktop chrome browser, but it failed on android chrome emulators 
checks for visibility and clickable were able to find the element but invoking click on the same element was failing with no such element error.

Later C# appium client was used to perform the same action successfully

Video player : https://motivation.vudoo.io/embed/12373082862 

[Include code or an example repository that can easily be set up]
https://github.com/only4arunkumar/Video-JS-Appium/tree/main/javascript-webdriverio
https://github.com/only4arunkumar/Video-JS-Appium/blob/main/javascript-webdriverio/test/basic/android-create-web-session.test.js

**Expected behavior**
The elementClick call should ideally work fine 

**Log**
https://github.com/only4arunkumar/Video-JS-Appium/blob/main/javascript-webdriverio/Appium_logs

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
Looking at the error log:

```
[info] [35m[W3C (196f065b)][39m Driver proxy active, passing request on via HTTP proxy
[debug] [35m[WD Proxy][39m Matched '/wd/hub/session/196f065b-3e11-49b0-a0c8-e8eb4f7cda8b/element/button.vjs-big-play-button/click' to command name 'click'
[debug] [35m[WD Proxy][39m Proxying [POST /wd/hub/session/196f065b-3e11-49b0-a0c8-e8eb4f7cda8b/element/button.vjs-big-play-button/click] to [POST http://127.0.0.1:8017/wd/hub/session/9ccd19a813efe8c2c11d14cde6fd3b0c/element/button.vjs-big-play-button/click] with body: {}
[info] [35m[WD Proxy][39m Got response with status 404: {"value":{"error":"no such element","message":"no such element: Element_id length is invalid\n  (Session info: chrome=83.0.4103.106)","stacktrace":"0   chromedriver_mac64_v83.0.4103.39    0x000000010c0cee99 chromedriver_mac64_v83.0.4103.39 + 4808345\n1   chromedriver_mac64_v83.0.4103.39    0x000000010c0695f3 chromedriver_mac64_v83.0.4103.39 + 4392435\n2   chromedriver_mac64_v83.0.4103.39    0x000000010bcf529d chromedriver_mac64_v83.0.4103.39 + 770717\n3   chromedriver_mac64_v83.0.4103.39    0x000000010bc5e1c5 chromedriver_mac64_v83.0.4103.39 + 152005\n4   chromedriver_mac64_v83.0.4103.39    0x000000010bc5fdd6 chromedriver_mac64_v83.0.4103.39 + 159190\n5   chromedriver_mac64_v83.0.4103.39    0x000000010bc56dab chromedriver_mac64_v83.0.4103.39 + 122283\n6   chromedriver_mac64_v83.0.4103.39    0x000000010bc7b082 chromedriver_mac64_v83.0.4103.39 + 270466\n7   chromedriver_mac64_v83.0.4103.39    0x000000010bc56c36 chromedriver_mac64_v83.0.4103.39 + 121910\n8   chromedriver_mac64_v83.0.4103.39    0x000000010bc7b...
[debug] [35m[W3C][39m Matched W3C error code 'no such element' to NoSuchElementError
```

It seems that this issue is connected to Appium given that an element was successfully queried but interacting with it then failed. I recommend raise an issue in the Appium project.

**Comment by christian-bromann** [comment]
Actually no, it seems that the element id was applied incorrectly. Appium fetched the element correctly via:

```
[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/196f065b-3e11-49b0-a0c8-e8eb4f7cda8b/element[39m
[info] [35m[HTTP][39m [90m{"using":"css selector","value":"button.vjs-big-play-button"}[39m
[info] [35m[W3C (196f065b)][39m Driver proxy active, passing request on via HTTP proxy
[debug] [35m[WD Proxy][39m Matched '/wd/hub/session/196f065b-3e11-49b0-a0c8-e8eb4f7cda8b/element' to command name 'findElement'
[debug] [35m[WD Proxy][39m Proxying [POST /wd/hub/session/196f065b-3e11-49b0-a0c8-e8eb4f7cda8b/element] to [POST http://127.0.0.1:8017/wd/hub/session/9ccd19a813efe8c2c11d14cde6fd3b0c/element] with body: {"using":"css selector","value":"button.vjs-big-play-button"}
[debug] [35m[WD Proxy][39m Got response with status 200: {"value":{"element-6066-11e4-a52e-4f735466cecf":"ae9c6bc0-4609-4bc9-ad44-abb7e88c6808"}}
```

The element id was `ae9c6bc0-4609-4bc9-ad44-abb7e88c6808` but when clicking on the element the css selector was used instead: `POST /wd/hub/session/196f065b-3e11-49b0-a0c8-e8eb4f7cda8b/element/button.vjs-big-play-button/click`. Now looking at the code I see:

```js
 (await client.elementClick("button.vjs-big-play-button"));
```

which is incorrect. It should be:

```js
 await (await client.$("button.vjs-big-play-button")).click();
```

instead
