### ISSUE TITLE
afterSession hook is clearing debug log

### ISSUE THREAD

**Issue by RafalSkorka** [webdriverio/webdriverio#6346]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.12.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.16.1
 - **NPM version:** 6.14.11
 - **Browser name and version:** Chrome 88
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** none

**Config of WebdriverIO**
Generated with `npx wdio config -y ` with these changes:
```
    outputDir: 'reports',
    logLevel: 'debug',
    afterSession: function (config, capabilities, specs) {
        console.log(`afterSession hook!`);
    },
```
**Describe the bug**
When `outputDir` and `afterSessions` are defined, setting logLevel to values 'debug' or 'trace' makes the `wdio-0-0.log` almost empty.
It is because this log is cleared after `deleteSession` command is executed, but `executeHooksWithArgs` function logs a message there afterwards clearing its previous contents. 

**To Reproduce**
* Run the `Getting Started` steps.
* Modify the config as above.

**Expected behavior**
The `wdio-0-0.log` is not cleared in the `afterSession` hook.

**Log**
Here is the only entry after running such project:
```
2021-01-25T22:00:24.094Z DEBUG @wdio/sync: Finished to run "afterSession" hook in 0ms
```

**Additional context**
This was introduced with https://github.com/webdriverio/webdriverio/issues/6068

**Comment by christian-bromann** [comment]
I have experienced this too and was wondering how I reproduced it. Thanks for taking the initial research, you want to take a stab at it?

**Comment by RafalSkorka** [comment]
I am sorry, I will not be able to tackle this soon :(

**Comment by wyhmichael** [comment]
I am experiencing exactly the same with the same setup 

```
WebdriverIO version: 6.12.1
Mode: WDIO Testrunner
If WDIO Testrunner, running sync/async: sync
Node.js version: 12.16.1
NPM version: 6.14.11
Browser name and version: Chrome 88
Platform name and version: Windows 10
Additional wdio packages used (if applicable): none
```

**Comment by christian-bromann** [comment]
This will be fixed as part of #6577

**Comment by RafalSkorka** [comment]
@christian-bromann I am still experiencing this issue after updating to 7.2.0 :(

**Comment by wyhmichael** [comment]
Yep, @christian-bromann still experiencing this with latest WDIO and async mode, like @RafalSkorka mentioned this is related to `deleteSession` and `executeHooksWithArgs`

Introduced by https://github.com/webdriverio/webdriverio/issues/6068, the log would be cleared when command === 'deleteSessioin' - https://github.com/webdriverio/webdriverio/pull/6073/files#diff-b08c37e616f7015c3c66a75fde5d6a5f9e58955dcc8be341320d65536e492037R103-R105, and `executeHooksWithArgs` runs `endSession` first and then `afterSession`, anything happens in `afterSession` would be logged into a new log file

**Comment by wyhmichael** [comment]
hi @christian-bromann I put up a PR with a workaround about this issue, please let me know how you think about it - https://github.com/webdriverio/webdriverio/pull/8506, thanks~

cc @RafalSkorka
