### ISSUE TITLE
[IEDriver] Requests from different service hooks, with same criteria, timeout

### ISSUE THREAD

**Issue by yuderekyu** [webdriverio/webdriverio#6354]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [6.12.1]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [e.g. 12.20.1]
 - **NPM version:** [e.g. 6.14.10]
 - **Browser name and version:** [e.g. IEDriverServer version 3.11.0]
  - **Platform name and version:** [e.g. MacOS Catalina 10.15.7]
 - **Additional wdio packages used (if applicable):** [Custom Services]

**Config of WebdriverIO**
https://github.com/cerner/terra-toolkit/blob/wdio-issue-reduced-test-case/packages/terra-functional-testing/src/config/wdio.conf.js

**Describe the bug**
Define two services that trigger a `browser.execute` based on the same criteria (in this case, a `refresh` or `url` call), within their afterCommand hooks. When the test runs against the IEDriver, the requests seem to hang indefinitely. It seems like Firefox and Chrome are fine.

My sample test executes a url, refresh, then takes a screenshot for debugging purposes. https://github.com/cerner/terra-toolkit/blob/wdio-issue-reduced-test-case/packages/terra-functional-testing/tests/wdio/test-spec.js

Service 1: https://github.com/cerner/terra-toolkit/blob/wdio-issue-reduced-test-case/packages/terra-functional-testing/src/services/wdio-terra-service.js#L102-L114

Service 2: https://github.com/cerner/terra-toolkit/blob/wdio-issue-reduced-test-case/packages/terra-functional-testing/src/services/wdio-test-service.js#L6-L13

### branch
https://github.com/cerner/terra-toolkit/tree/wdio-issue-reduced-test-case

### steps to reproduce
+ switch to node 12
+ execute  `npm install`
+ launch a local selenium hub. i've tested with the latest version, 3.141.59, and 3.14.0. logs are from 3.14.0. 
+ register an ie node to the hub via vm, using the IEDriverServer from Selenium. i've tested with IEDriverServer 3.150.1 and 3.11.0. logs are from 3.11.0
+ update the `wdio-ie-local-hub` script to your own ip address and ports. https://github.com/cerner/terra-toolkit/blob/wdio-issue-reduced-test-case/package.json#L82
+ execute `npm run wdio-ie-local-hub`

**Expected behavior**
Tests to execute without timing out.

**Log**
+ ie driver log: https://gist.github.com/yuderekyu/e66b347e588d6b3b781d7a122e2d6e1c
+ wdio log: https://gist.github.com/yuderekyu/ae55b552ba2651e53446e78d9fdf4e10
+ hub log: https://gist.github.com/yuderekyu/434454f75fb107f91febe9eecc6907be

**Additional context**
This very well could be an iedriver issue, but I'd love to get some input from you all. It seems like the wdio requests are being sent just fine, but the driver freezes. I've tried to create a vanilla selenium test case [[here],](https://github.com/cerner/terra-toolkit/blob/wdio-issue-reduced-test-case/packages/terra-functional-testing/tests/wdio/vanilla-selenium-spec.js) but I'm not sure if my implementation is 1-1 translation with how wdio implements its requests.

**Comment by christian-bromann** [comment]
> This very well could be an iedriver issue, but I'd love to get some input from you all. It seems like the wdio requests are being sent just fine, but the driver freezes.

I am afraid this is indeed an issue with IEDriver. Happy to add things to WebdriverIO that can help the IEDriver to be more stable. 

I also see this error in your wdio logs:
> Request failed with status 404 due to Error 404: Not Found

Maybe it has to do with that IEDriver is not able to run the execute command on a 404 page.
