### ISSUE TITLE
Visual Regression testing > Compare specific area of the page

### ISSUE THREAD

**Issue by nida-trayio** [webdriverio/webdriverio#6367]
**Is your feature request related to a problem? Please describe.**
My use case to compare 2 pages but not to compare the footer

**Describe the solution you'd like**
Take the screenshots that doesn't include footer and then compare
Or take the screenshots of full-page but while doing comparison ignore the footer

**Comment by wswebcreation** [comment]
Hi @nida-trayio 

WebdriverIO is not maintaining the Visual  Regression services. Can you please submit your feature request on the appropriate repo?

Tnx
