### ISSUE TITLE
navigation issue

### ISSUE THREAD

**Issue by kerjukha** [webdriverio/webdriverio#6369]
can't get to the current version of website after version change

**Comment by christian-bromann** [comment]
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
