### ISSUE TITLE
Error while doing npx wdio config -y

### ISSUE THREAD

**Issue by kartikb88** [webdriverio/webdriverio#6378]
npx wdio config -y

=========================
WDIO Configuration Helper
=========================

Installing wdio packages:
- @wdio/local-runner
- @wdio/mocha-framework
- @wdio/spec-reporter
- wdio-chromedriver-service
- @wdio/sync
- chromedriver
npm WARN deprecated debug@4.2.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"

> chromedriver@88.0.0 install C:\Users\kbharga\Desktop\TATAAIG-PROJECT-DATA\Webdriverio-Test\node_modules\chromedriver
> node install.js

ChromeDriver binary exists. Validating...
ChromeDriver is already available at 'C:\Users\kbharga\AppData\Local\Temp\88.0.4324.96\chromedriver\chromedriver.exe'.
Copying to target path C:\Users\kbharga\Desktop\TATAAIG-PROJECT-DATA\Webdriverio-Test\node_modules\chromedriver\lib\chromedriver
Done. ChromeDriver binary available at C:\Users\kbharga\Desktop\TATAAIG-PROJECT-DATA\Webdriverio-Test\node_modules\chromedriver\lib\chromedriver\chromedriver.exe

> fibers@4.0.3 install C:\Users\kbharga\Desktop\TATAAIG-PROJECT-DATA\Webdriverio-Test\node_modules\fibers
> node build.js || nodejs build.js

C:\Users\kbharga\Desktop\TATAAIG-PROJECT-DATA\Webdriverio-Test\node_modules\fibers>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )
gyp ERR! find VS 
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS 
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\kbharga\Desktop\TATAAIG-PROJECT-DATA\Webdriverio-Test\node_modules\fibers
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'`
Alpine users please run: `sudo apk add python make g++`
'nodejs' is not recognized as an internal or external command,
operable program or batch file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\mocha\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN Webdriverio-Test@1.0.0 No description
npm WARN Webdriverio-Test@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.1 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fibers@4.0.3 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@4.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kbharga\AppData\Roaming\npm-cache\_logs\2021-02-02T04_32_59_830Z-debug.log
wdio.js config

Initialize WebdriverIO and setup configuration in your current project.

Options:
      --version          Show version number                           [boolean]
      --watch            Run WebdriverIO in watch mode                 [boolean]
  -h, --hostname         automation driver host address                 [string]
  -p, --port             automation driver port                         [number]
      --path             path to WebDriver endpoints (default "/")      [string]
  -u, --user             username if using a cloud service as automation backend
                                                                        [string]
  -k, --key              corresponding access key to the user           [string]
  -l, --logLevel         level of logging verbosity
                  [choices: "trace", "debug", "info", "warn", "error", "silent"]
      --bail             stop test runner after specific amount of tests have
                         failed                                         [number]
      --baseUrl          shorten url command calls by setting a base url[string]
  -w, --waitforTimeout   timeout for all waitForXXX commands            [number]
  -f, --framework        defines the framework (Mocha, Jasmine or Cucumber) to
                         run the specs                                  [string]
  -r, --reporters        reporters to print out the results on stdout    [array]
      --suite            overwrites the specs attribute and runs the defined
                         suite                                           [array]
      --spec             run only a certain spec file - overrides specs piped
                         from stdin                                      [array]
      --exclude          exclude certain spec file from the test run - overrides
                         exclude piped from stdin                        [array]
      --mochaOpts        Mocha options
      --jasmineNodeOpts  Jasmine options
      --cucumberOpts     Cucumber options
      --yarn             Install packages via yarn package manager.
                                                      [boolean] [default: false]
  -y, --yes              will fill in all config defaults without prompting
                                                      [boolean] [default: false]
      --help             Show help                                     [boolean]

Documentation: https://webdriver.io
@wdio/cli (v6.12.1)

Error: something went wrong during setup: null
    at runConfig (C:\Users\kbharga\Desktop\TATAAIG-PROJECT-DATA\Webdriverio-Test\node_modules\@wdio\cli\build\commands\config.js:65:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.handler (C:\Users\kbharga\Desktop\TATAAIG-PROJECT-DATA\Webdriverio-Test\node_modules\@wdio\cli\build\commands\config.js:114:9)
    at Object.handler (C:\Users\kbharga\Desktop\TATAAIG-PROJECT-DATA\Webdriverio-Test\node_modules\@wdio\cli\build\commands\config.js:117:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by christian-bromann** [comment]
It seems that Fibers failed to install. You might use a deprecated Node.js version. Can you try with Node.js version 12?

**Comment by AutomationReddy** [comment]
@christian-bromann Even I got this error today. We are moving to a different version (RHEL 7/ubi) of docker images with red hat open-shift platform. 

My node version is 12.19.1

Any suggestions?

![image](https://user-images.githubusercontent.com/42345623/106581900-6414fa80-6569-11eb-9deb-4064ec6dd736.png)

**Comment by christian-bromann** [comment]
It seems that Node.js has not sufficient permission to install fibers.

**Comment by AutomationReddy** [comment]
My Bad. I didn't notice that. Permission issue cleared and it's now working for me. Thanks

**Comment by kartikb88** [comment]
> It seems that Node.js has not sufficient permission to install fibers.

I will try this solution as well. Can you please guide me how i can give full permission to node js?

**Comment by kartikb88** [comment]
> It seems that Fibers failed to install. You might use a deprecated Node.js version. Can you try with Node.js version 12?

Wdio with node 12, Issue resolved. But you guys have to keep updated because the webdriverIo is not supporting node >14

**Comment by christian-bromann** [comment]
@kartikb88 we will have a new major release next week.

**Comment by Xotabu4** [comment]
Getting error with wdio 7 and node 15.8

```
➜  10-js-ui-wdio-Xotabu4 git:(draft/1) ✗ npx wdio config

=========================
WDIO Configuration Helper
=========================

? Where is your automation backend located? On my local machine
? Which framework do you want to use? mocha
? Do you want to run WebdriverIO commands synchronous or asynchronous? sync
? Are you using a compiler? TypeScript (https://www.typescriptlang.org/)
? Where are your test specs located? ./test/specs/**/*.ts
? Do you want WebdriverIO to autogenerate some test files? Yes
? Do you want to use page objects (https://martinfowler.com/bliki/PageObject.html)? Yes
? Where are your page objects located? ./test/pageobjects/**/*.ts
? Which reporter do you want to use? spec
? Do you want to add a service to your test setup? chromedriver
? What is the base url? http://localhost

Installing wdio packages:
- @wdio/local-runner
- @wdio/mocha-framework
- @wdio/spec-reporter
- wdio-chromedriver-service
- @wdio/sync
- ts-node
- typescript
- chromedriver
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: @wdio/cli@7.0.4
npm ERR! node_modules/@wdio/cli
npm ERR!   @wdio/cli@"^7.0.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @wdio/cli@"^6.0.0" from wdio-chromedriver-service@6.0.4
npm ERR! node_modules/wdio-chromedriver-service
npm ERR!   dev wdio-chromedriver-service@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-16T19_35_25_274Z-debug.log
wdio config

Initialize WebdriverIO and setup configuration in your current project.

Options:
      --version          Show version number                           [boolean]
      --watch            Run WebdriverIO in watch mode                 [boolean]
  -h, --hostname         automation driver host address                 [string]
  -p, --port             automation driver port                         [number]
      --path             path to WebDriver endpoints (default "/")      [string]
  -u, --user             username if using a cloud service as automation backend
                                                                        [string]
  -k, --key              corresponding access key to the user           [string]
  -l, --logLevel         level of logging verbosity
                  [choices: "trace", "debug", "info", "warn", "error", "silent"]
      --bail             stop test runner after specific amount of tests have
                         failed                                         [number]
      --baseUrl          shorten url command calls by setting a base url[string]
  -w, --waitforTimeout   timeout for all waitForXXX commands            [number]
  -f, --framework        defines the framework (Mocha, Jasmine or Cucumber) to
                         run the specs                                  [string]
  -r, --reporters        reporters to print out the results on stdout    [array]
      --suite            overwrites the specs attribute and runs the defined
                         suite                                           [array]
      --spec             run only a certain spec file - overrides specs piped
                         from stdin                                      [array]
      --exclude          exclude certain spec file from the test run - overrides
                         exclude piped from stdin                        [array]
      --mochaOpts        Mocha options
      --jasmineNodeOpts  Jasmine options
      --cucumberOpts     Cucumber options
      --autoCompileOpts  Auto compilation options
      --yarn             Install packages via yarn package manager.
                                                      [boolean] [default: false]
  -y, --yes              will fill in all config defaults without prompting
                                                      [boolean] [default: false]
      --help             Show help                                     [boolean]

Documentation: https://webdriver.io
@wdio/cli (v7.0.4)

Error: something went wrong during setup: null
    at runConfig (/mnt/c/GitHub/Startit/10-js-ui-wdio-Xotabu4/node_modules/@wdio/cli/build/commands/config.js:102:15)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Object.handler (/mnt/c/GitHub/Startit/10-js-ui-wdio-Xotabu4/node_modules/@wdio/cli/build/commands/config.js:166:9)
    at Object.handler (/mnt/c/GitHub/Startit/10-js-ui-wdio-Xotabu4/node_modules/@wdio/cli/build/commands/config.js:169:15)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
npm ERR! code 1
npm ERR! path /mnt/c/GitHub/Startit/10-js-ui-wdio-Xotabu4
npm ERR! command failed
npm ERR! command sh -c wdio "config"

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-16T19_35_25_314Z-debug.log
```

**Comment by Xotabu4** [comment]
Figured out if no additional services is not selected (i disabled preselected chromedriver) - installation passes:
```
=========================
WDIO Configuration Helper
=========================

? Where is your automation backend located? On my local machine
? Which framework do you want to use? mocha
? Do you want to run WebdriverIO commands synchronous or asynchronous? sync
? Are you using a compiler? TypeScript (https://www.typescriptlang.org/)
? Where are your test specs located? ./test/specs/**/*.ts
? Do you want WebdriverIO to autogenerate some test files? Yes
? Do you want to use page objects (https://martinfowler.com/bliki/PageObject.html)? Yes
? Where are your page objects located? ./test/pageobjects/**/*.ts
? Which reporter do you want to use? spec
? Do you want to add a service to your test setup? 
? What is the base url? http://localhost
```
Works

**Comment by christian-bromann** [comment]
@Xotabu4 can you check if one of the following packages fails to install?

```
- @wdio/local-runner
- @wdio/mocha-framework
- @wdio/spec-reporter
- wdio-chromedriver-service
- @wdio/sync
- ts-node
- typescript
- chromedriver
```

**Comment by Xotabu4** [comment]
> @Xotabu4 can you check if one of the following packages fails to install?
> 
> ```
> - @wdio/local-runner
> - @wdio/mocha-framework
> - @wdio/spec-reporter
> - wdio-chromedriver-service
> - @wdio/sync
> - ts-node
> - typescript
> - chromedriver
> ```

chromedriver fails:


npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: @wdio/cli@7.0.5
npm ERR! node_modules/@wdio/cli
npm ERR!   @wdio/cli@"^7.0.5" from the root project
npm ERR! 
**npm ERR! Could not resolve dependency:
npm ERR! peer @wdio/cli@"^6.0.0" from wdio-chromedriver-service@6.0.4**
npm ERR! node_modules/wdio-chromedriver-service
npm ERR!   dev wdio-chromedriver-service@"*" from the root project


it seems like it still have wdio/cli 6.0.0 in his package.json

**Comment by christian-bromann** [comment]
That should be updated then

**Comment by dhapolapankaj** [comment]
running below command resolved this issue

`npm config set strict-ssl false`

**Comment by amodmahajan2016** [comment]
Facing same issue with @wdio/cli (v7.5.1) and node version as v14.16.1. I tried setting up strict SSL false but did not work.

**Comment by sheekha-singh** [comment]
I am in the same boat. Using v12.22.12 (npm v6.14.16) , wdio - @wdio/cli@7.19.5 and Appium version - 1.16.0 - all on device farm and I get the exact same errors. Tried everything but nothing works
