### ISSUE TITLE
TypeError when using xunit reporter

### ISSUE THREAD

**Issue by SchwaFa** [webdriverio/webdriverio#638]
Using the latest version 3.1.0 of webdriverio, if I use the xunit reporter I get the following error at the end of all tests:

```
node_modules/webdriverio/lib/reporter/xunit.js:314
            return (data.requestOptions.method || 'get').toUpperCase() + ' ' +
                                       ^
TypeError: Cannot read property 'method' of undefined
    at [...]/node_modules/webdriverio/lib/reporter/xunit.js:314:40
    at XUnit.printLogTags ([...]/node_modules/webdriverio/lib/reporter/xunit.js:217:20)
    at [...]/node_modules/webdriverio/lib/reporter/xunit.js:313:14
    at Array.forEach (native)
    at XUnit.genTestsuite ([...]/node_modules/webdriverio/lib/reporter/xunit.js:237:11)
    at [...]/node_modules/webdriverio/lib/reporter/xunit.js:257:18
    at Array.forEach (native)
    at XUnit.genTestsuite ([...]/node_modules/webdriverio/lib/reporter/xunit.js:237:11)
    at [...]/node_modules/webdriverio/lib/reporter/xunit.js:257:18
    at Array.forEach (native)
```

It worked with an older version of webdriverio. Any ideas?

**Comment by christian-bromann** [comment]
fixed with #631 I haven't published it yet but will later today

**Comment by SchwaFa** [comment]
Awesome! Looking forward to the release. :)
Thanks a lot for the fast replies!

**Comment by SchwaFa** [comment]
I'm still waiting for the release... ;)

**Comment by christian-bromann** [comment]
Dang, sorry! This is why I should stop making promises on releases. I want to get #629 fixed before I release the next version. I will keep you posted in this thread.

**Comment by SchwaFa** [comment]
Still no news? We can't use it with CI (Jenkins) at the moment because of the bug. :(

**Comment by christian-bromann** [comment]
Sorry, not that much time for me atm but this will change soon :wink: 
If you want to already use this just change the WebdriverIO version to current master

**Comment by dhoulker** [comment]
I've been waiting for this as well, so that'd be really useful - how do we install the current master version?

**Comment by christian-bromann** [comment]
in you package json define webdriverio as follows:

```js
...
"webdriverio": "webdriverio/webdriverio",
...
```

**Comment by christian-bromann** [comment]
or `npm install --save webdriverio/webdriverio`

**Comment by dhoulker** [comment]
Great - I didn't know you could do that!

Thanks,

Dave
