### ISSUE TITLE
Detecting the backend is happening without reading the Cli arguments

### ISSUE THREAD

**Issue by wswebcreation** [webdriverio/webdriverio#6384]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6
 - **Mode:** Testrunner
 - **If WDIO Testrunner, running sync/async:** both
 - **Node.js version:** all
 - **NPM version:** all
 - **Browser name and version:** all
 - **Platform name and version:** all
 - **Additional wdio packages used (if applicable):** 

**Config of WebdriverIO**
```js
exports.config = {
  // ====================
  // Runner Configuration
  // ====================
  runner: 'local',
  // ==================
  // Specify Test Files
  // ==================
  specs: [
    './test/e2e/specs/**/*.js'
  ],
  // ============
  // Capabilities
  // ============
  maxInstances: 20,
  capabilities: [
    {
        browserName: 'chrome',
        platformName: 'Windows 10',
        browserVersion: 'latest',
        'sauce:options': {
        },
    },
  ],
  // ===================
  // Test Configurations
  // ===================
  logLevel: 'silent',
  bail: 0,
  baseUrl: 'http://localhost:3000',
  waitforTimeout: 10000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  framework: 'jasmine',
  reporters: ['spec'],
  jasmineNodeOpts: {
    defaultTimeoutInterval: 60000,
    helpers: [require.resolve('@babel/register')],
  },
  services: ['sauce'],
};
```

**Describe the bug**
When you want to provide your `user` and `key` through the command line WDIO now defaults back to the default backend which is `http://localhost:4444/`. It looks like the order of reading the CLI args and detecting the backend is not the correct one

**To Reproduce**
Use the above config and this command 

`yarn test.e2e.sauce.eu --spec=./test/e2e/specs/checkout.complete.spec.js --user=username --key###`

**Expected behavior**
The `detectBackend` method will be used with the CLI args and will start a session in Sauce Labs

**Comment by christian-bromann** [comment]
Let's continue convo in #6408
