### ISSUE TITLE
Add ability to use mock on remote browser

### ISSUE THREAD

**Issue by apanashchenko** [webdriverio/webdriverio#6387]
**Is your feature request related to a problem? Please describe.**
Hi guys,
I want use wdio feature [Mocks and Spies](https://webdriver.io/docs/mocksandspies.html). As for me it's very useful and can help a lot of developers, but it's available only for local browser run. Some time need mock some third party and run test in some remote clusters. I don't want mock backend or use some mock servers, to many movements =) 

**Describe the solution you'd like**
Some tool like [selenoid](https://aerokube.com/selenoid/latest/#_accessing_browser_developer_tools) can provide access to devtool session. I looked at the code, wdio use just default CDP port and create this `ws` session by itself. I think need add possibility put `ws` session to wdio config.

**Describe alternatives you've considered**

**Additional context**

I want see code like this:
```typescript
describe('Card transactions tests', () => {
    beforeEach('setup data', async function () {
        this.transactions = [
            {
                id: 1,
                currency: 'USD',
                amount: '100.00',
                date: '2020-11-01T13:29:31.000Z',
                merchantName: 'Test MOCK',
                status: 'APPROVED',
            },
        ];
        await browser.devtool({browserWSEndpoint: `ws://${host}:4444/devtools/${browser.sessionId}`});
        const mock = await browser.mock('**/cards/*/transactions', {method: 'get'});
        await mock.respond(this.transactions);
    });

    it('should see transactions by card', async function () {
        await loginAsUser(this.user);
        await transactions.open();
        await transactions.selectCard('USD Card');
        await transactions.transactionsShouldBePresent(this.transactions);
    });
});
```
Maybe  `await browser.devtool(opt)` not the best solution, but it can be discussed by You =)

Best regards and peace!

**Comment by SergeyPirogov** [comment]
Super awesome feature

**Comment by christian-bromann** [comment]
> Some time need mock some third party and run test in some remote clusters. I don't want mock backend or use some mock servers, to many movements =)

Can you explain this? WebdriverIO currently can only mock the network of a browser it is also automating. With `browser.devtool` it seems you also want to mock a browser that has nothing to do with your automated session. Using these mocking capabilities in remote browser will be possible with Selenium 4 grid where the websocket connection is being forwarded from the local machine to the remote machine. There shouldn't be anything needed to make it work in WebdriverIO. But maybe I don't understand something here. Please elaborate.

**Comment by BorisOsipov** [comment]
>Using these mocking capabilities in remote browser will be possible with Selenium 4 grid where the websocket connection is being forwarded from the local machine to the remote machine.

Selenoid does smth similar. It provides per-selenium session url with corresponding proxied cdp websocket. See example how you can use remote cdp session along with wdio selenium session here https://github.com/aerokube/browsers-puppeteer-example/blob/master/index.js

@apanashchenko wants an ability to use `wss://${host}:4444/devtools/${browser.sessionId}/` as endpoint for wdio devtools rather then "hardcoded" local port in wdio runner mode.

**Comment by apanashchenko** [comment]
@BorisOsipov you are completely right!

**Comment by christian-bromann** [comment]
So essentially attach to an existing browser session through Chrome DevTools?

**Comment by apanashchenko** [comment]
Looks like yes.

**Comment by christian-bromann** [comment]
In that case I suggest to enhance the `attach` method exported by `webdriverio` to have like a `wsUrl` and in that case return a DevTools instance that attaches to this url. This has not been [implemented yet](https://github.com/webdriverio/webdriverio/blob/main/packages/devtools/src/index.ts#L125-L131). So the could would look like this:

```js
import { attach } from 'webdriverio'

describe('Card transactions tests', () => {
    beforeEach('setup data', async function () {
        this.transactions = [
            {
                id: 1,
                currency: 'USD',
                amount: '100.00',
                date: '2020-11-01T13:29:31.000Z',
                merchantName: 'Test MOCK',
                status: 'APPROVED',
            },
        ];
        const browser = await attach({wsUrl: `ws://${host}:4444/devtools/${browser.sessionId}`});
        const mock = await browser.mock('**/cards/*/transactions', {method: 'get'});
        await mock.respond(this.transactions);
    });

    it('should see transactions by card', async function () {
        await loginAsUser(this.user);
        await transactions.open();
        await transactions.selectCard('USD Card');
        await transactions.transactionsShouldBePresent(this.transactions);
    });
});
```

Any contributions are welcome! Happy to help with this.

**Comment by christian-bromann** [comment]
This is currently being worked on in #6459. If anyone can pick up the PR to bring it over the finish line that would be amazing!
