### ISSUE TITLE
Programmatically execute commands

### ISSUE THREAD

**Issue by Deothrin** [webdriverio/webdriverio#639]
In version 2 I could do this and it would work
```
commands = [
 {action: 'click', selector: '#id1' }
 {action: 'click', selector: '#id2' }
]

commands.forEach(function (cmd) {
  client[cmd.action](cmd.selector)
})
```

In version 3 commands must be chained

`client.click().click()`

or you'll run into timing issues because the commands appear to be executed immediately if not chained.

How do I get this to work using version 3?

**Comment by christian-bromann** [comment]
As we support promises and have a promised based chaining we can't support this anymore. I would recommend to use the wdio runner and do:

```js
commands = [
 {action: 'click', selector: '#id1' }
 {action: 'click', selector: '#id2' }
]

commands.forEach(function (cmd) {
   yield client[cmd.action](cmd.selector)
})
```

**Comment by Deothrin** [comment]
Thanks, I'll check it out. In the meantime I realised I could do it this way:
```
(function next () {
   cmd = commands.shift()
   if (cmd) {
       client[cmd.action](cmd.selector).then(next)
})()
```
