### ISSUE TITLE
webdriverIO backward compatibility for older version

### ISSUE THREAD

**Issue by amiya-pattnaik** [webdriverio/webdriverio#640]
Hi Chris,

We automation project developed in the older version of webdriverIO wher the syntax is different compare to the new version of webdriverIO. for example 

In old version
--------------------
client.getText('#elem', function (err, actual){
//console.log();
} );

In new version
---------------------
client.getText('#elem').then(function(text) {
    //console.log(text);
});

1. If I install the latest version of sebdrioverIO, Will the older syntax / code will work on the new version?
2. few APIs / methods which was in older version are not available in the newer one, for example client.waitFor() in now not available in the new API list. will it works or we have to modify the script accordingly?

Please suggest us. We highly appreciate your help.

Thanks,
Amiya

**Comment by christian-bromann** [comment]
> If I install the latest version of sebdrioverIO, Will the older syntax / code will work on the new version?

Callbacks are still supported in the new version (except for `execute`, `executeAsync`, `selectorExecute` and `selectorExecuteAsync`)

> few APIs / methods which was in older version are not available in the newer one, for example client.waitFor() in now not available in the new API list. will it works or we have to modify the script accordingly?

Please replace all `waitFor` commands with `waitForExist`

**Comment by amiya-pattnaik** [comment]
thanks a lot for your support and guidance
