### ISSUE TITLE
not able to calculate CLS (Cumulative Layout Shift) using browser.getMetrrics(). its printing 0

### ISSUE THREAD

**Issue by pratimghosh76** [webdriverio/webdriverio#6406]
below is my package.json

"dependencies": {
    "@babel/cli": "^7.8.4",
    "@babel/core": "^7.9.6",
    "@babel/preset-env": "^7.9.6",
    "@babel/register": "^7.9.0",
    "@slack/client": "^5.0.2",
    "@wdio/cli": "6.1.12",
    "@wdio/devtools-service": "^7.0.0",
    "@wdio/local-runner": "^6.1.12",
    "@wdio/mocha-framework": "^6.1.8",
    "@wdio/sauce-service": "^6.5.0",
    "@wdio/selenium-standalone-service": "^6.4.7",
    "@wdio/spec-reporter": "^6.4.7",
    "@wdio/sync": "^6.1.8",
    "chai": "^4.2.0",
    "chakram": "^1.5.0",
    "chromedriver": "^88.0.0",
    "chromium": "^3.0.2",
    "csv-write-stream": "^2.0.0",
    "devtools": "^7.0.0",
    "fs": "0.0.1-security",
    "https": "^1.0.0",
    "install": "^0.13.0",
    "lighthouse": "^7.0.1",
    "node-localstorage": "^2.1.6",
    "node-slack": "0.0.7",
    "npm": "^7.5.3",
    "puppeteer": "3.0.1",
    "puppeteer-core": "2.0.0",
    "slack": "^11.0.2",
    "tcp-port-used": "^1.0.1",
    "url": "^0.11.0",
    "wdio-chromedriver-service": "^6.0.4",
    "wdio-docker-service": "^3.0.0",
    "wdio-json-reporter": "^2.0.0",
    "wdio-slack-service": "^2.0.8",
    "webdriverio": "^7.0.1"
  },

[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2]
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:** [e.g. 8.11.2]
 - **NPM version:** [e.g. 5.8.0]
 - **Browser name and version:** [e.g. Chrome 68]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**

**To Reproduce**

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
It seems you haven't updated all WDIO packages properly. It is important that all packages are updated to latest. Please do that and give it another shot. Let me know if you have any further questions.
