### ISSUE TITLE
Sauce service updates the test status in Sauce dashboard as passed if failed in before each method

### ISSUE THREAD

**Issue by AutomationReddy** [webdriverio/webdriverio#6409]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [6.5]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [>12]
 - **NPM version:** [>6]
 - **Browser name and version:** [e.g. Chrome 68]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [@wdio/sauce-service]

**Describe the bug**
I have 11 tests with before each. 10 got passed and11th test case failed in beforeEach() which shows the results as expected in terminal but sauce labs dashboard shows as passed.

**To Reproduce**
Fail the test in before each hook

**Expected behavior**
When a test failed irrespective of hooks, saucelabs dashboard should reflect the same.

Additional Context:

`this._failures` count in service.ts is initialised for a test failure in afterEach() hook which will not be executed if a test fails in beforeEach().

**Comment by christian-bromann** [comment]
Can you provide a reproducible example?

**Comment by AutomationReddy** [comment]
@christian-bromann Write any test but fail it in beforeEach()

**Comment by AutomationReddy** [comment]
@christian-bromann Just checking the status on this. This is actually giving us many false results.

**Comment by christian-bromann** [comment]
@AutomationReddy still don't see a minimal reproducible example, it makes it easier to work on this issue.

**Comment by AutomationReddy** [comment]
@christian-bromann 

From the autogenerated project (mocha and pageObject), when you navigate to the page and before tests get started, add
`beforeEach()` and wait for any element on the page which doesn't exist. Your test will be failed now in before each itself. And see sauce labs status will be marked as passed but your test is failed. This need to be ran in Sauce.

Let me know if you need any info.

**Comment by christian-bromann** [comment]
fixed in #6912
