### ISSUE TITLE
Uncaught exceptions don't seem to be caught when triggered inside a callback

### ISSUE THREAD

**Issue by RobertWHurst** [webdriverio/webdriverio#641]
When using the framework I noticed that if I threw an exception from within a callback from methods such as getTitle, the exception is not caught by mocha. Instead it just times out.

![screen shot 2015-07-17 at 5 38 42 pm](https://cloud.githubusercontent.com/assets/178857/8759541/01e57c2e-2cab-11e5-9b66-833e4eb9ce58.png)
<img width="851" alt="screen shot 2015-07-17 at 5 38 52 pm" src="https://cloud.githubusercontent.com/assets/178857/8759542/06205dd6-2cab-11e5-9b78-3ad2af7b967e.png">

**Comment by christian-bromann** [comment]
@RobertWHurst there is no way Mocha could catch that error. Here is a different example:

```js
it('should rest', function(done) {
    var defer = q.defer();
    defer.promise.then(function() {
        throw new Error("HAHA");
        done();
    });
    setTimeout(defer.resolve, 3000);
});
```

This will also timeout instead of throwing that error immediately. I would not recommend to end a test using that callback function when working with promises. Just return your command chain and if one command fails or an assertion fails this promise will get rejected. Here is an example:

```js
it('should have the right title - the promise way', function() {
    return browser
        .url('/')
        .getTitle().then(function(title) {
            throw new Error('BOOOM');
            assert.equal(title, 'WebdriverIO - Selenium 2.0 javascript bindings for nodejs');
        });
});
```

**Comment by RobertWHurst** [comment]
Sorry, I uploaded the incorrect example. I mean't to file this in reference to using a callback, without a promise.

**Comment by christian-bromann** [comment]
> I mean't to file this in reference to using a callback, without a promise.

Sorry. I don't quite understand what you mean by that.

**Comment by RobertWHurst** [comment]
I updated the comment, sorry for the confusion.

**Comment by b1alpha** [comment]
browser.url('foobar.com').getTitle(function(err, title) {
    throw new Error('never shows up');
});

**Comment by b1alpha** [comment]
describe('assert callback error should be caught', function() {
    it('search for errors', function() {
    return browser
        .url('/').getTitle(function(err, title) {
            throw new Error('never shows up');
        });
  
    });
});


This does throw an error;

0 passing (3.90s)
1 failing

1) search for errors:
never shows up
running chrome (vdev) on OS X 10.10
Error: never shows up
    at Object.<anonymous> (test/test.spec.js:43:19)

**Comment by christian-bromann** [comment]
Yeah like I mentioned .. Mocha can't catch that error until you return the promise.

**Comment by bonjonbovi87** [comment]
Bumping an old thread .. but I stumbled here after bashing my head for the last hour as I was having the same problem.  

The solution is simple - remove the keyword **done** from your **it** declaration.

**Incorrect:**
```javascript
it('my test', function(done){
    return browser.getTitle().then(function(){
       throw new Error("This will never be shown");
    });
});
```

**Correct:**
```javascript
it('my test', function(){
    return browser.getTitle().then(function(){
       throw new Error("This will shown");
    });
});
```

**Comment by christian-bromann** [comment]
@bonjonbovi87 just never use done 😉

**Comment by lrn2prgrm** [comment]
setTimeout(throw new Error(''))
