### ISSUE TITLE
scrollIntoView's argument of type '{ block: string; }' is not assignable to parameter of type 'boolean'.

### ISSUE THREAD

**Issue by DenysBarkan** [webdriverio/webdriverio#6414]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.0.2
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 14.15.5
 - **NPM version:** 6.14.11
 - **TypeScript version:** 4.1.5
 - **Browser name and version:** Chrome 88
 - **Platform name and version:** MacOS 10.15.7
 - **Additional wdio packages used (if applicable):** "@wdio/allure-reporter", "@wdio/devtools-service", "@wdio/local-runner", "@wdio/mocha-framework", "@wdio/spec-reporter", "@wdio/sync", "@wdio/types"

**tsconfig.json**
```
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "*": [ "./*" ],
            "src/*": ["./src/*"]
        },
        "outDir": "./build",
        "allowJs": true,
        "types": [
            "node", 
            "webdriverio/sync", 
            "@wdio/mocha-framework",
            "@wdio/devtools-service"
        ],
        "inlineSourceMap": true,
        "target" : "es2019"
    }
}
```

**Describe the bug**
After update the WDIO to v7 and ts to v4 the scrollIntoView was broke through the all project. 
The scrollIntoView doesn't get the options according to MDN references in easy elements. 

**To Reproduce**

```
  get element1() { return $(`.jkor`) }
    get element2() { return this.element1.$(`.oehp`) }

    scrollToElements(){
    this.element1.scrollIntoView({block:'center'})   //Error:  Argument of type '{ block: string; }' is not assignable to parameter of type 'boolean'.
    $(`.jkor`).scrollIntoView({block:'center'})      //Error:  Argument of type '{ block: string; }' is not assignable to parameter of type 'boolean'.
    this.element2.scrollIntoView({block:'center'})   // 
    }

```

**Expected behavior**
The scrollIntoView get the options according to MDN references

**Additional context**
![Screen Shot 2021-02-12 at 9 59 24 AM](https://user-images.githubusercontent.com/45456152/107743216-278b9080-6d19-11eb-99f8-8bd39a499b3e.png)
![Screen Shot 2021-02-12 at 9 59 33 AM](https://user-images.githubusercontent.com/45456152/107743217-28bcbd80-6d19-11eb-9f1f-e41c33ff1a23.png)
![Screen Shot 2021-02-12 at 9 59 41 AM](https://user-images.githubusercontent.com/45456152/107743219-29edea80-6d19-11eb-8e42-3481df7d62b9.png)
![Screen Shot 2021-02-12 at 9 59 48 AM](https://user-images.githubusercontent.com/45456152/107743221-2a868100-6d19-11eb-9abd-e8a75b4393d4.png)

**Comment by christian-bromann** [comment]
@BorisOsipov @DenysBarkan could you review #6415?
