### ISSUE TITLE
isDisplayed support for Microsoft Edge

### ISSUE THREAD

**Issue by savkaoleg** [webdriverio/webdriverio#6417]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.10.11
 - **Mode:** WDIO Testrunner
 - **running sync/async:** async
 - **Node.js version:** 12.17.0
 - **NPM version:** 6.14.9
 - **Browser name and version:** 88.0.705.63
 - **Platform name and version:** Windows 10

**Config of WebdriverIO**
Run with browserName = msedge:
{
    runner: 'local',
    specs: [
        './test/specs/**/*.js'
    ],
    maxInstances: 10,
    capabilities: [{    
        maxInstances: 5,
        browserName: 'msedge',
        acceptInsecureCerts: true
    }],
    logLevel: 'trace',
    bail: 0,
    baseUrl: 'http://localhost',
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 600000
    }
}

Run with browserName = MicrosoftEdge:
{
    runner: 'local',
    specs: [
        './test/specs/**/*.js'
    ],
    maxInstances: 10,
    port: 4444,
    path: '/wd/hub',
    capabilities: [{    
        maxInstances: 5,
        browserName: 'MicrosoftEdge',
        acceptInsecureCerts: true
    }],
    logLevel: 'trace',
    bail: 0,
    baseUrl: 'http://localhost',
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 600000
    }
}
**Describe the bug**
If I run test without setting selenium port and path, I must set browserName: 'msedge' and in isDisplayed command i have browser.isDevTools = true and browser.capabilities.browserName = 'Edge'.
If i run test with setting selenium port and path, I must set browserName: 'MicrosoftEdge' and in isDisplayed command i have browser.isDevTools = undefined and browser.capabilities.browserName = 'msedge'.

And in result in first variant I have error in el.waitForDisplayed and in second variant I don't have any errrors/

**To Reproduce**
```
        await browser.url("https://www.wikipedia.org/");
        const el = await browser.$("#searchLanguage > option:nth-child(24)");
        const result = await el.waitForDisplayed({ timeout: 60000 });
        expect(result).toBeExisting();
```
**Expected behavior**
Looks like some naming bug with Edge

**Comment by christian-bromann** [comment]
> And in result in first variant I have error

It would be helpful if you can share that error.

**Comment by savkaoleg** [comment]
```
Error: element ("#searchLanguage > option:nth-child(24)") still not displayed after 60000ms
    at C:\projects\webdriverio-test\node_modules\webdriverio\build\commands\browser\waitUntil.js:22:23
    at async Element.elementErrorHandlerCallbackFn (C:\projects\webdriverio-test\node_modules\webdriverio\build\middlewares.js:17:32)
    at async Element.runCommandWithHooks (C:\projects\webdriverio-test\node_modules\@wdio\sync\build\wrapCommand.js:70:25)
    at Element.runCommandWithHooks (C:\projects\webdriverio-test\node_modules\@wdio\sync\build\wrapCommand.js:65:24)
    at Element.wrapCommandFn (C:\projects\webdriverio-test\node_modules\@wdio\sync\build\wrapCommand.js:44:44)
    at Element.elementErrorHandlerCallback (C:\projects\webdriverio-test\node_modules\webdriverio\build\middlewares.js:34:12)
    at Context.<anonymous> (C:\projects\webdriverio-test\test\specs\example.e2e.js:8:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Context.executeAsync (C:\projects\webdriverio-test\node_modules\@wdio\utils\build\shim.js:101:16)
    at async Context.exports.testFrameworkFnWrapper (C:\projects\webdriverio-test\node_modules\@wdio\utils\build\test-framework\testFnWrapper.js:25:18)
```

**Comment by christian-bromann** [comment]
This error means that the element didn't show up. The command is very well supported in both WebDriver and DevTools automation. Please verify that you have selected the correct element.

Closing as this appears not to be an issue. Feel free to join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have further questions.

**Comment by savkaoleg** [comment]
> This error means that the element didn't show up. The command is very well supported in both WebDriver and DevTools automation. Please verify that you have selected the correct element.
> 
> Closing as this appears not to be an issue. Feel free to join our [![Gitter](https://camo.githubusercontent.com/8b6f368b7e24e49e393505358ce5270198b5d1a15b0155b3bfd90f414ae21861/68747470733a2f2f6261646765732e6769747465722e696d2f776562647269766572696f2f776562647269766572696f2e737667)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have further questions.

But in second variant I don't have any errors

**Comment by christian-bromann** [comment]
For me the example works neither in Chrome nor in MSEdge no matter which protocol.
