### ISSUE TITLE
Several Cucumber hooks returning undefined in 7.0.x 

### ISSUE THREAD

**Issue by esaari** [webdriverio/webdriverio#6418]
**Environment (please complete the following information):**
 - **WebdriverIO version:**  7.0.3
 - **Mode:** testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:**  12.18.4
 - **NPM version:** 6.x
 - **Browser name and version:**  Chrome 88
 - **Platform name and version:**  MacOS Big Sur 11.2
 - **Additional wdio packages used (if applicable):** see `package.json` in example

**Config of WebdriverIO**
This is the same config as the one from the cucumber boilerplate: https://github.com/webdriverio/cucumber-boilerplate/blob/master/package.json, except the packages have all been updated to 7.0.x where available and several files were updated to work with cucumber v7. 

**Describe the bug**
Cucumber hooks may be broken. When you console.log the individual params in the `afterScenario` hook in v6, you get output for each output as seen in the wdiov6Output.rtf file below. In wdiov7Output.rtf, except for the `uri` param, they all returned undefined and they are accurate per the latest version of the docs: https://webdriver.io/docs/options#afterscenario
**To Reproduce**
1. Unzip the repo below
2. `cd` to project root and `yarn install`
2. In terminal, run `yarn run test:features` from project root. 
3. See output. 

The only thing that was done here was uncommenting a few of the Cucumber hooks in `hooks.js` and comparing their output in v7 to v6. 

**Expected behavior**
All Cucumber hook functions should return objects per the current documentation and should be functionally no different than wdio v6.

**Log**
See `wdioV6Output` and `wdioV7Output`.

**Additional context**

[wdiov7Output.txt](https://github.com/webdriverio/webdriverio/files/5973958/wdiov7Output.txt)
[wdioV6Output.txt](https://github.com/webdriverio/webdriverio/files/5973967/wdioV6Output.txt)
[cucumber-boilerplate.zip](https://github.com/webdriverio/webdriverio/files/5973973/cucumber-boilerplate.zip)

> Please use the correct markdown

**Comment by esaari** [comment]
Not sure if this is possibly related but it looks like the `package.json` for the `wdio-cucumber-framework` has a conflicting dependency: https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-cucumber-framework/package.json#L33
Also `@types/cucumber` v7 is available: https://github.com/webdriverio/webdriverio/blob/f66a2adbbde005f1850c7683723471c0813530c0/packages/wdio-cucumber-framework/package.json#L41

**Comment by esaari** [comment]
> Not sure if this is possibly related but it looks like the `package.json` for the `wdio-cucumber-framework` has a conflicting dependency: https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-cucumber-framework/package.json#L33
> Also `@types/cucumber` v7 is available:
> 
> https://github.com/webdriverio/webdriverio/blob/f66a2adbbde005f1850c7683723471c0813530c0/packages/wdio-cucumber-framework/package.json#L41

**Comment by christian-bromann** [comment]
The hooks aren't broken, just some parts of the documentation hasn't been correctly updated. With the upgrade to v7 of Cucumber we had to tweak some of the hooks.

**Comment by christian-bromann** [comment]
Fixed in #6431
