### ISSUE TITLE
Use descriptive names for generics instead of single letters.

### ISSUE THREAD

**Issue by dylang** [webdriverio/webdriverio#6426]
**Is your feature request related to a problem? Please describe.**

Single-letter generics in WebdriverIO are difficult to know what the expected value is when using the public api.

Example:

I want to provide a type for `execute`'s return value... Hmm, what are `T` and `U`?

```ts
export default function execute<T, U extends any[]> (
    this: WebdriverIO.Browser | WebdriverIO.Element,
    script: string | ((...innerArgs: U) => T),
    ...args: U
): Promise<T> {
```

**Describe the solution you'd like**

Generics don't need to be single capital letters in TypeScript.

```ts
export default function execute<ExecuteOutput, ExecuteArguments extends any[]> (
    this: WebdriverIO.Browser | WebdriverIO.Element,
    script: string | ((...innerArgs: ExecuteArguments) => WebdriverIO),
    ...args: ExecuteArguments
): Promise<T> {
```

**Describe alternatives you've considered**

Opening the source every time I'm trying to figure out what's expected.

**Additional context**
I don't know if this is necessary, there are times when a single letter is fine, like type helpers: https://github.com/bradzacher/eslint-plugin-typescript/blob/master/docs/rules/generic-type-naming.md

**Comment by christian-bromann** [comment]
fixed in #6429
