### ISSUE TITLE
Problem pausing webdriver after each action

### ISSUE THREAD

**Issue by vladei** [webdriverio/webdriverio#643]
Hi there. I'm writing some tests for my app and I have the following problem. I have a list of users and next to them I have a button that when it's clicked it books the specific user. I want to test a case where all the users are booked. I do the following with this code.

```
function bookSession() {
  client
    .url('localhost:9000/psychologists')
    .waitForVisible('.user-item')
    .pause(1000)
    .elements('.user-item').then(function(elements) {
      var promises = [];
      var self = this;
      _.forEach(elements.value, function(element) {
        promises.push(
          self.elementIdElement(element.ELEMENT, '.book-button')
          .then(function(button) {
            return self.elementIdClick(button.value.ELEMENT);
          })
          );
      });
      return Q.all(promises);
    });
}

```

It works well but I want between the different bookings to pause the client for a specific amount of time.I tried the following two options to see if they will work

```
promises.push(
          self.elementIdElement(element.ELEMENT, '.book-button')
          .pause(3000)
          .then(function(button) {
            return self.elementIdClick(button.value.ELEMENT);
          })
          );
```

AND

```

_.forEach(elements.value, function(element) {
        promise.push(self.pause(3000));
        promises.push(
          self.elementIdElement(element.ELEMENT, '.book-button')
          .then(function(button) {
            return self.elementIdClick(button.value.ELEMENT);
          })
          );
      });
```

but neither of them seems to pause the client. Can anybody help me with this?

Thanx

**Comment by christian-bromann** [comment]
Try this:

```js
function bookSession() {
  client
    .url('localhost:9000/psychologists')
    .waitForVisible('.user-item')
    .pause(1000)
    .elements('.user-item').then(function(elements) {
      var promises = [];
      var self = this;
      _.forEach(elements.value, function(element) {
        self = self.pause(3000).elementIdElement(element.ELEMENT, '.book-button').then(function(button) {
          return self.elementIdClick(button.value.ELEMENT);
        });
        promises.push(self);
      });
      return Q.all(promises);
    });
}
```
I know it looks a bit stupid but this is how promise chaining works with WebdriverIO. In the elements fullfill function `this` is a fulfilled promise and all commands you call on `this` would get executed immediately (which is desired for the first user-item button). But then we want to execute click after click. Therefor we need to save the last click promise in order to execute the next click after that. Does that make sense? :laughing:
