### ISSUE TITLE
window not defined

### ISSUE THREAD

**Issue by ipao9** [webdriverio/webdriverio#644]
I'm running an external script with a basic configuration to spin up firefox, and the global window object is not defined. Any ideas?

**Comment by christian-bromann** [comment]
Could you share some code?

**Comment by ipao9** [comment]
Please see below (error: window not defined):

var webdriverio = require('webdriverio');
var client = webdriverio.remote(options);
var options = {
  desiredCapabilities: {
      browserName: 'chrome'
  },
};
 
client
  .init()
  .url('http://xxxxxx.com')
  .setValue('#email', 'hello')
  .setValue('#password', 'world')
  .click('#signin')
  .waitUntil(function() {
    return Date.now() - window.performance.timing.loadEventEnd > 20000;
  })
  .title(function(err, res) {
      console.log('Title was: ' + res.value);
  })
  .end();

**Comment by christian-bromann** [comment]
`waitUntil` doesn't execute code in the browser. But changing this is simple:

```js
var webdriverio = require('webdriverio');
var client = webdriverio.remote(options);
var options = {
  desiredCapabilities: {
      browserName: 'chrome'
  },
};

client
  .init()
  .url('http://xxxxxx.com')
  .setValue('#email', 'hello')
  .setValue('#password', 'world')
  .click('#signin')
  .waitUntil(function() {
    return client.execute(function() {
      return Date.now() - window.performance.timing.loadEventEnd > 20000;
    }).then(function(result) {
      return result.value;
    });
  })
  .title(function(err, res) {
      console.log('Title was: ' + res.value);
  })
  .end();
```
