### ISSUE TITLE
Allow timeoutMsg in browser.waitUntil WaitUntilOptions to take a function

### ISSUE THREAD

**Issue by robd** [webdriverio/webdriverio#6440]
**Is your feature request related to a problem? Please describe.**
I'm trying to improve the error message I see when `waitUntil` times out based on the latest state of the page. 

For example, if I'm waiting for a list of 10 elements to appear, and only 6 have appeared so far, I'd like to show the actual elements in the timeout message.

**Describe the solution you'd like**
I'd like `timeoutMsg` to take a function so I could do something like the following:

```typescript
let elements: any[] = [];
browser.waitUntil(
  () => {
    elements = $$(".someElement");
    return elements.length == 10;
  },
  {
    timeoutMsg: () => `Timed out when waiting for 10 elements to appear, latest elements were ${elements.join(
      ","
    )}`,
  }
);
```

**Describe alternatives you've considered**
I tried creating a subclass of `String` which could be updated dynamically, but don't think this is possible due to the [strict type checking for strings](https://github.com/webdriverio/webdriverio/blob/2f27b1800de30941fc91c0538b54332ccf2338f4/packages/webdriverio/src/commands/browser/waitUntil.ts#L73).

**Additional context**
I have seen the ability to generate failure messages dynamically in other test frameworks and can help a lot with speed of identification of failures. I'm happy to work on a patch if this would be accepted.

**Comment by christian-bromann** [comment]
Have you tried:

```ts
browser.waitUntil(
  () => {
    elements = $$(".someElement");
    if (elements.length !== 10) {
      throw new Error(`Waiting on 10 elements, received ${elements.length} so far`)
    }
  }
)
```

?

**Comment by robd** [comment]
Ah no - I hadn't tried this and and the below seemed to work - thanks! 

```typescript
let count = 0;
let elements: any[] = [];
browser.waitUntil(() => {
  elements = $$(".someElement");
  if (elements.length !== 10) {
    throw `Waiting on 10 elements, received ${
      elements.length
    } so far (${count++} exceptions thrown)`;
  }
  return true;
});
```
Gives this error: `waitUntil condition failed with the following reason: Waiting on 10 elements, received 0 so far (19 exceptions thrown)
`

I'm interested in how this works - I guess all exceptions raised up until the final one before the timeout expires are ignored silently and then it just shows the final one before the timeout happened?  If this is the case, wondering if this is desirable because it could hide intermediary exceptions? (Perhaps not a problem in practice.)

My personal preference would be to have the first exception immediately crash out of the loop and have the API specify that the user needs to return false form the function in the case that the loop should try again. Another approach could be to report all non unique exception messages at the end. 

Happy to do a PR for something here if this is of interest.

**Comment by christian-bromann** [comment]
> I'm interested in how this works - I guess all exceptions raised up until the final one before the timeout expires are ignored silently and then it just shows the final one before the timeout happened?

Correct!

> If this is the case, wondering if this is desirable because it could hide intermediary exceptions? (Perhaps not a problem in practice.)

Also correct that it is not a problem in practice. You can certainly build your custom wait until method using the call command or your own custom command working with `try/catch`.

Your suggestions make sense and a desirable behavior for some people. It would however would be a breaking change which I am not keen to introduce after the recent major release, not knowing how many other users would like to adjust the behavior. I suggest to create a discussions thread where we can weigh pros/cons of discussed approaches.

Closing as I think this has been resolved. Happy to answer further questions 😉

**Comment by robd** [comment]
Yes this makes sense - thanks for your help. Hopefully this conversation will act as a solution for those that need it. 

Realise now, another feature of the current behaviour is that you can use assertions in wait conditions and things "just work":

```typescript
browser.waitUntil(() => {
  expect($$(".someElement")).toBeElementsArrayOfSize(10);
  return true;
});
```

**Comment by martindzejky** [comment]
Hi! I just found this issue and I have to say, this is not at all the behaviour I expected. _Can you please add it to the docs for `waitUntil` please?_ It would have saved me some time.

From the currect version of the docs, I assumed that returning `false` from the condition function triggers the retry, but throwing an error immediately stops and fails the test with the error.

It would be super helpful, if you added these to the docs:
* `condition` is a function which takes no arguments and returns either a boolean or a promise resolving to a boolean
* returning a rejected promise or throwing an error still triggers the retry
* you can safely use `expect` inside of `waitUntil`

**Comment by christian-bromann** [comment]
@martindzejky thanks for the feedback! Would you be open to give us a hand?

**Comment by martindzejky** [comment]
> Yes this makes sense - thanks for your help. Hopefully this conversation will act as a solution for those that need it.
> 
> Realise now, another feature of the current behaviour is that you can use assertions in wait conditions and things "just work":

Actually, I've been playing around with this, and `expect` does not work inside of the `waitUntil` for me. I'm using Jasmine together with Webdriver, maybe that's why. 🤷 So I still have to throw an error manually.

**Comment by christian-bromann** [comment]
> maybe that's why. 🤷

Yeah, Jasmine assertion lib doesn't throw errors, as it allows multiple errors per test.

**Comment by martindzejky** [comment]
Okay, after a lot of testing, here's what I found out (for future reference):

Enabling `oneFailurePerSpec` in the jasmine config causes failed expectations to throw errors, which makes `browser.waitUntil` behave like expected. However, the first failed `expect` not only throws an error, but also marks the spec as failed. So even if the `browser.waitUntil` eventually passes after a few tries, the spec still fails with the first failed expectation. 😢 

So, all in all, when using the Jasmine framework, it does not make sense to call `expect` inside of `waitUntil`. 🏁

**Comment by christian-bromann** [comment]
@martindzejky honestly I think you don't need to. If your condition within `waitUntil` fails after timeout,`waitUntil` throws an error and makes your test fail. I would just put the expect below.

**Comment by martindzejky** [comment]
@christian-bromann that's right. But I wanted to write a nice piece of code like this:

```
await browser.waitUntil(async () => {
  const customer = await getCustomer()

  expect(customer).toEqual(jasmine.objectContaining({ name: 'hello world' }))
}, {
  timeout: 10000
})
```

But that does not work with Jasmine because the spec is always marked as failed, even if the `waitUntil` eventually passes.

**Comment by christian-bromann** [comment]
@martindzejky have you tried switching to Mocha? Or is there anything within Jasmine that you need for you specs? Note that WebdriverIO ships its own `expect` assertion lib so the transition should be easy.

> because the spec is always marked as failed, even if the `waitUntil` eventually passes.

I am not sure why this happens. The command only fails if the timeout is reached. Can you provide more details, e.g. the error message?

**Comment by martindzejky** [comment]
@christian-bromann I expect that Jasmine's `expect` somehow marks the spec as failed, there's no additional error message apart from the failed assertion. Mocha probably does not have this feature but I have not considered switching yet.
