### ISSUE TITLE
browser.url(url) not working remotely (browserstack)

### ISSUE THREAD

**Issue by larryg01** [webdriverio/webdriverio#6460]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.0.5
 - **Mode:** Standalone mode
 - **Node.js version:** 12.18.4
 - **Yarn version:** 1.22.10
 - **Browser name and version:** Chrome 88
 - **Platform name and version:** Mac 10.15.7 (Catalina)

**Describe the bug**
When using browser.url(url); 
I am getting this error message when running remotely via **Browserstack**
```js
   "TypeError [ERR_INVALID_URL]: Invalid URL:
     at onParseError (internal/url.js:256:9)
     at new URL (internal/url.js:332:5)
     at new URL (internal/url.js:329:22)
    at Browser.url (/xxxxx/node_modules/webdriverio/build/commands/browser/url.js:43:17)"
```

locally its working as expected.

**To Reproduce**
```js
// navigate to a new URL (local and browserstack)
browser.url('https://webdriver.io');
// receive url
console.log(browser.getUrl()); // outputs: "https://webdriver.io"
```

**Expected behavior**
The given url should be received both locally and remotely.

**Comment by christian-bromann** [comment]
@larryg01 would you like to take a stab at this?

**Comment by larryg01** [comment]
@christian-bromann I would like to have a chat about this issue..
With the change that works, its not passing the 'relative url' as its not passing the baseUrl so in the end all you get is the /foobar and not http://foobar.com/foobar
so locally it will work fine but via crossbrowser services its failing with the error (as above).
So what i am struggling with is having it working both in the branch and the real world (if that makes sense)

**Comment by christian-bromann** [comment]
Can you provide the wdio logs? I would be interested in the WebDriver calls.

**Comment by larryg01** [comment]
I deleted my fork and started from scratch 
I created a branch for the fix
I realise that the url file is now called url.js and NOT url.ts as was the previous case
so at some point that file was changed from .ts to .js (can you shed some light on that please)

**Comment by christian-bromann** [comment]
> so at some point that file was changed from .ts to .js (can you shed some light on that please)

The file still ends with `.ts`: https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/browser/url.ts

**Comment by larryg01** [comment]
OK, I need to make the change to '/build/commands/browser/url.js'  and NOT  '/src/commands/browser/url.ts'  but the .js file is an ignored file am i allowed to make changes to it ? 
also If i am allowed to do it, where would i need to place the test file for it?

**Comment by larryg01** [comment]
@christian-bromann I have made the changes and commit the files, Will do a PR and submit, hopefully this is done the correct way now

**Comment by erwinheitzman** [comment]
no .js files need to be changed, the .js files you see is the output of the .ts files

**Comment by larryg01** [comment]
thats what i figured, so the change needs to be the .ts file because as you can see its not working in the state it is at the moment so none of my remote tests will work once upgraded to v7. So my question is what changed from v6 to make that stop working.
Since I am using it in standalone mode and with JS and not TS not sure what changed so dramatically for it to stop working.

**Comment by christian-bromann** [comment]
@larryg01 I looked into the issue again and the implementation seems fine to me. I have no idea why it is working locally but failing on BS. The WebDriver commands send to the driver are the same. I am happy to re-open the issue if you can provide a minimal reproducible example. Thanks for your effort looking into this.

**Comment by larryg01** [comment]
@christian-bromann you can checkout my framework https://github.com/larryg01/klassi-demo-js then run
 'yarn bslocal chrome'  then upgrade webdriverio to latest version and then run the command again, youw ill see it working on v6.12.1 and failing on v7

**Comment by christian-bromann** [comment]
> you can checkout my framework [larryg01/klassi-demo-js](https://github.com/larryg01/klassi-demo-js) then run

Can you give me access to this repo?

**Comment by larryg01** [comment]
Invitation sent

**Comment by christian-bromann** [comment]
@larryg01 the problem was that the base url was an empty string. I created a PR with a fix that ensures that empty strings are ignored.

**Comment by larryg01** [comment]
@christian-bromann thats awesome so this will be merged at some point today so that i can get my upgrade completed. Thank you
