### ISSUE TITLE
Unexpected code lines is linked from the terminal after ts compiler (looks like sourcemap counts incorrect)

### ISSUE THREAD

**Issue by DenysBarkan** [webdriverio/webdriverio#6466]
**Environment:**
 - **WebdriverIO version:** 7.0.5
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v14.15.4
 - **NPM version:** 6.14.10
 - **TypeScrip version:** 4.1.5
- **Additional wdio packages used (if applicable):** [@wdio/allure-reporter, @wdio/devtools-service, @wdio/local-runner, @wdio/mocha-framework, @wdio/spec-reporter, @wdio/sync, @wdio/types]

**tsconfig.json**
```
{
    "compilerOptions": {
        "paths": {
            "*": [
                "./*"
            ],
            "src/*": [
                "./src/*"
            ]
        },
        "outDir": "./build",
        "allowJs": true,
        "types": [
            "node",
            "webdriverio/sync",
            "@wdio/mocha-framework",
            "@wdio/devtools-service",
            "chai",
            "chromedriver"
        ],
        // "sourceMap": true,
        "inlineSourceMap": true,
        "target": "es2019",
    },
}
```
**Describe the bug**
The code lines in the source code and in the code after the ts compilation are not equal. 

**To Reproduce**
1. develop some ts code lines with issues. 
2. run the file
3. call the line with issue from the reporter in terminal
4. pay attention to the code line

```
    /**
     * some
     * mor
     * code
     * lines
     * to
     * check
     * the
     * compiler
     * of
     * the 
     * ts
     * and
     * the
     * source
     * map
     * work
     * 
     */
    it('test ts', function(){
        const f = 1
        let s = f+1
        console.log("num1 : ", f, 'num2 : ', s)
        // the line with the issue
        f.should.be.equal(s, 'the number are not equal')
    })
```

**Expected behavior**
The line of code is linked from the reporter (terminal) are equal to the line with the issue in the code.

**Log**
```
[chrome 88.0.4324.150 windows #0-0] the number are not equal: expected 1 to equal 2
[chrome 88.0.4324.150 windows #0-0] AssertionError: the number are not equal: expected 1 to equal 2
[chrome 88.0.4324.150 windows #0-0]     at Context.<anonymous> (/Users/dv/SDET/a.com/test/flows/s.test.ts:158:21)
```

https://user-images.githubusercontent.com/45456152/108238932-1516ba00-7152-11eb-8dd4-e6577fed57a0.mov

**Comment by christian-bromann** [comment]
@DenysBarkan thanks for reporting this issue. Seems very weird to me. Any idea where this can be a bug within the WebdriverIO code base?

**Comment by Alximicus** [comment]
Are there any updates? I still have the same issue in 7.6.0 version
