### ISSUE TITLE
Not all methods are shown on the autocomplete list 

### ISSUE THREAD

**Issue by DenysBarkan** [webdriverio/webdriverio#6467]
**Environment:**
 - **WebdriverIO version:** 7.0.5
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v14.15.4
 - **NPM version:** 6.14.10
 - **TypeScript version:** 4.1.5

**Describe the bug**
Some of the methods are missed from the autocomplete list

**To Reproduce**
for example the 
```
browser.getUrl()
```
is not shown on the autocomplete list.
Instead the all these methods were shown on the autocomplete list in wdio6.

In addition, the methods are shown in wdio6 as the methods now are shown in wdio7 as property

**Expected behavior**
all wdio7 methods are ready for autocomplete and are shown on the autocomplete list

compare the lists of the wdio6 and wdio7:
<img width="585" alt="Screen Shot 2021-02-17 at 10 18 17 AM" src="https://user-images.githubusercontent.com/45456152/108241480-8e171100-7154-11eb-82a8-1637568135b9.png">
![Screen Shot 2021-02-17 at 10 18 07 AM](https://user-images.githubusercontent.com/45456152/108241512-9707e280-7154-11eb-89af-c50aaa4b64e2.png)
<img width="610" alt="Screen Shot 2021-02-17 at 10 21 16 AM" src="https://user-images.githubusercontent.com/45456152/108241627-b6067480-7154-11eb-9afb-0c416b00751c.png">
![Screen Shot 2021-02-17 at 10 21 33 AM](https://user-images.githubusercontent.com/45456152/108241654-bbfc5580-7154-11eb-8a52-91d32d033457.png)
<img width="577" alt="Screen Shot 2021-02-17 at 10 22 37 AM" src="https://user-images.githubusercontent.com/45456152/108241685-c3bbfa00-7154-11eb-8f52-8373e7702bbc.png">
![Screen Shot 2021-02-17 at 10 22 26 AM](https://user-images.githubusercontent.com/45456152/108241697-c880ae00-7154-11eb-84f3-3a44a86d41d0.png)

**Comment by christian-bromann** [comment]
Are you using TypeScript or not? With TypeScript I get all suggestions just fine:

![Screenshot 2021-02-18 at 13 31 22](https://user-images.githubusercontent.com/731337/108357441-b99a0a00-71ed-11eb-81b7-b788c5746db8.png)
![Screenshot 2021-02-18 at 13 30 54](https://user-images.githubusercontent.com/731337/108357445-bb63cd80-71ed-11eb-8de5-a4b278866f79.png)

**Comment by DenysBarkan** [comment]
I'm using TypeScript. But get a totally different result. Could it be the issue in the preferences or in the version of the TS or so?

**Comment by christian-bromann** [comment]
Just make sure that you are using TS v4 or higher and applied the WebdriverIO types according to [the docs](https://webdriver.io/docs/typescript). Can you verify you did this?

**Comment by DenysBarkan** [comment]
dependencies i use:
```
  "devDependencies": {
    "@types/chai": "^4.2.13",
    "@types/jquery": "^3.5.5",
    "@types/mocha": "^8.2.1",
    "@types/node": "^14.11.8",
    "@wdio/allure-reporter": "^7.0.4",
    "@wdio/cli": "^7.0.5",
    "@wdio/devtools-service": "^7.0.5",
    "@wdio/local-runner": "^7.0.5",
    "@wdio/mocha-framework": "^7.0.4",
    "@wdio/spec-reporter": "^7.0.4",
    "@wdio/sync": "^7.0.5",
    "@wdio/types": "^7.0.4",
    "allure-commandline": "^2.13.0",
    "aws-sdk": "^2.846.0",
    "browserstack-local": "^1.4.5",
    "chai": "^4.2.0",
    "chromedriver": "^88.0.0",
    "ts-node": "^9.0.0",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^4.1.5",
    "wdio-chromedriver-service": "^6.0.3",
    "wdio-json-reporter": "^2.0.0"
  },
  ```
  
and the TypeScript config:
```
{
    "compilerOptions": {
        "paths": {
            "*": [
                "./*"
            ],
            "src/*": [
                "./src/*"
            ]
        },
        "outDir": "./build",
        "allowJs": true,
        "types": [
            "node",
            "webdriverio/sync",
            "@wdio/mocha-framework",
            "@wdio/devtools-service",
            "chai",
            "chromedriver"
        ],
        "inlineSourceMap": true,
        "target": "es2019",
    },
}
```

**Comment by christian-bromann** [comment]
Any chance you can provide a minimal reproducible example?

**Comment by DenysBarkan** [comment]
do you want me to do a screencast? or something like this?

https://user-images.githubusercontent.com/45456152/108366406-00ddc600-7201-11eb-9f94-a6961cbcd482.mov

**Comment by christian-bromann** [comment]
Nope, I need a reproducible example that I can check out myself and see why the setup is incorrect.

**Comment by DenysBarkan** [comment]
https://github.com/DenysBarkan/wdio7_testing.git

in './test/specs/example.e2e.ts' in 18 line the new it

**Comment by christian-bromann** [comment]
Looking into the dependencies it seems that there are issues resolving some sub packages:

> Cannot find module '@wdio/protocols'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?ts(2792)

**Comment by DenysBarkan** [comment]
do you have any progress with this case?

**Comment by christian-bromann** [comment]
Same here, as we are moving away from `sync` execution, this issue is not very relevant anymore.
