### ISSUE TITLE
The method's descriptions are not shown 

### ISSUE THREAD

**Issue by DenysBarkan** [webdriverio/webdriverio#6468]
**Environment:**
 - **WebdriverIO version:** 7.0.5
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v14.15.4
 - **NPM version:** 6.14.10

**Describe the bug**
The method's descriptions are not shown in the VScode. 
the methods are named as properties in the description field

**To Reproduce**
Move the mouse pointer over the methods in the code line.
pay attention to the description of the methods.

compare wdio6 and wdio7:
<img width="838" alt="Screen Shot 2021-02-17 at 10 38 10 AM" src="https://user-images.githubusercontent.com/45456152/108242595-c3702e80-7155-11eb-8c1c-29bf6a218cbb.png">
![Screen Shot 2021-02-17 at 10 38 19 AM](https://user-images.githubusercontent.com/45456152/108242621-c834e280-7155-11eb-846e-f20eb6b3ac3f.png)
<img width="794" alt="Screen Shot 2021-02-17 at 10 33 56 AM" src="https://user-images.githubusercontent.com/45456152/108242727-eb5f9200-7155-11eb-81ea-af2661db3e0e.png">
![Screen Shot 2021-02-17 at 10 34 12 AM](https://user-images.githubusercontent.com/45456152/108242742-ef8baf80-7155-11eb-95b9-45aaa69cd796.png)

**Comment by christian-bromann** [comment]
This is a TypeScript limitation. WebdriverIO has every command implemented in a separate file. All these are then gathered in a single [export file](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/browser.ts). With WebdriverIO providing type definitions for sync and async command handling we need to [transform](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/types.ts#L12-L64) the type definitions to work in a synchronous manner. Unfortunately with this transformation we loose all type descriptions. I don't know if there is a way to workaround this. Any suggestions are welcome.

**Comment by DenysBarkan** [comment]
But at the same time, it works perfectly in WDIO6 with typescript. 
See the additional pic the name of the function is the version of wdio.

**Comment by christian-bromann** [comment]
> But at the same time, it works perfectly in WDIO6 with typescript.

I know, in v6 we have [autogenerated](https://github.com/webdriverio/webdriverio/blob/v6/packages/wdio-sync/webdriverio-core.d.ts#L1117-L1395) these type definitions. This wasn't very scaleable so we moved away from it. Maybe something we can report in the TS project!?

**Comment by christian-bromann** [comment]
As we are moving away from `sync` execution, this issue is not really relevant anymore.
