### ISSUE TITLE
log('browser') not showing the newest browser log 

### ISSUE THREAD

**Issue by mirokuxy** [webdriverio/webdriverio#647]
log('browser') is not getting the newest browser log. whenever I use .log('browser'), it's always returning the logs of the previous website.

say I'm running this code:
```
client.init()
.url('https://google.com')
.log('browser').then(function(logs){ /* do nothing or do whatever*/ })
.url('https://github.com')
.log('browser').then(function(logs){ console.log(logs); })  // it's returning logs from google.com
```

So right now I can never get the current / newest logs. If I want to get logs of `url 1`, I've got to `go to url 1`, then `go to url 2` and then I can get logs of `url 1`. This is just so annoying.

Is it a bug or it is supposed to have such behaviour?
Any other way I can get the most recent logs?

I'm using selenium-standalone with chromeDriver.

**Comment by christian-bromann** [comment]
Interesting. I am not sure if this is actual a bug in WebdriverIO or more something weird going on in Selenium? Do you see the same behaviour across different browser?

**Comment by mirokuxy** [comment]
haven't tried yet. currently only tried on chromeDriver.

**Comment by christian-bromann** [comment]
Would you try other browser as well?

**Comment by mirokuxy** [comment]
I may try on phantom. but not others.

**Comment by christian-bromann** [comment]
yeah that might already help to know if the same problem occurs there too

**Comment by christian-bromann** [comment]
Wasn't able to reproduce this. google.com doesn't print any logs no matter how often you visit the page. I tested a different scenario where I `console.log` something right at the beginning of the page. I was able to get that log right after calling the url command
