### ISSUE TITLE
[wdio-devtools-service] Support CDP on Selenium 4 Grid

### ISSUE THREAD

**Issue by dylanlive** [webdriverio/webdriverio#6470]
**Is your feature request related to a problem? Please describe.**
Selenium 4.0 (now in Beta) [supports proxying CDP Requests across Grid](https://www.selenium.dev/blog/2020/selenium-4-alpha-6-is-out/).

It would be nice if we could use the WebdriverIO Devtools Service to run those commands against a Selenium 4.0 Grid.

**Describe the solution you'd like**
When providing a remote machine in the config, such as:
```
    runner: 'local',
    hostname: 'my.grid.ip',
    port: 4444,
```

And providing the devtools service
```
services: ['devtools'],
```

I should be able to call commands in my test like:
```
browser.cdp('Browser', 'getVersion')
```

**Describe alternatives you've considered**
n/a

**Additional context**
I'm happy to take a shot at this PR if you'd accept it. I believe the change will occur in here:
https://github.com/webdriverio/webdriverio/blob/26772cdb71d211c0f63fc5b6247fe41c5f83ba76/packages/webdriverio/src/commands/browser/getPuppeteer.ts#L58
```
         this.puppeteer = await puppeteer.connect({
-            browserURL: `http://${chromiumOptions.debuggerAddress}`,
+            browserWSEndpoint: `ws://${this.config.hostname}:${this.config.port}/session/${this.sessionId}/se/cdp`,
         })
```

Of course with some conditionals added depending on if

1. User provided a custom debuggerAddress
2. Whether a local run or a remote host/port is being used
3. If it's Remote, check if it's a Selenium 4.0 Grid that accepts those commands (can probably look at returned capabilities, which exposes this endpoint)

**Comment by dylanlive** [comment]
Please let me know if you'd accept a PR with the above approach, and I'll take a shot at it.

**Comment by christian-bromann** [comment]
That sounds like a good idea! Please go ahead and let me know if you have any questions, thanks!

**Comment by L0tso** [comment]
Hello, I have got some thoughts about this feature request
Maybe, it will be better to add an ability to connect via ws for devtools-service in general, not only for Selenium 4 Grid.
For example, Selenoid and Moon also have CDP proxy but use different ws endpoints: [1](https://aerokube.com/selenoid/latest/#_accessing_browser_developer_tools) [2](https://aerokube.com/moon/latest/#_accessing_chrome_developer_tools)
@dylanlive @christian-bromann what do you think about it?

**Comment by christian-bromann** [comment]
@L0tso could call, it would be great if all could be supported by default without custom configurations. Do you know if these providers provide any information about their CDP interface in the session response?

**Comment by BorisOsipov** [comment]
Agree with @christian-bromann. It will be better if Aerokube team behave like Selenium 4 grid. @L0tso could you create issue for it in selenoid repo?

**Comment by L0tso** [comment]
@christian-bromann @BorisOsipov Good point! I agree, it will be better to use default Selenium-like ws endpoints. I will create issues for the Selenoid team.

**Comment by dylanlive** [comment]
In Selenium 4, after a session is created the hub returns the endpoint like this:

```
{
    "status": 0,
    "sessionId": "c8adfc6384648299d726d9c63d4e7a15",
    "value": {
        "se:options": {
            "cdp": "http://localhost:5555/session/c8adfc6384648299d726d9c63d4e7a15/se/cdp"
         },
    }
}
```
(condensed)

I was thinking of just grabbing the endpoint directly from the response (instead of hardcoding assumptions) especially since other tools like Selenoid, etc. might want to also utilize this to discover the endpoint.

Thoughts on that side? Maybe I could just take the step for Selenium now, and then we can revisit once https://github.com/aerokube/selenoid/issues/1063 is implemented?

Side note: Selenium 4 returns the Node (port 5555) in the endpoint instead of the Hub. Selenium Hub does proxy the cdp requests to the node. So I'm checking with the contributors of Selenium via Slack to see if that can be changed to the hub's ip/port

**Comment by christian-bromann** [comment]
> Thoughts on that side? Maybe I could just take the step for Selenium now, and then we can revisit once [aerokube/selenoid#1063](https://github.com/aerokube/selenoid/issues/1063) is implemented?

Sounds good to me!

**Comment by jamesmortensen** [comment]
Quick question, does this also address connecting to a selenium/standalone-chrome Docker container, one that is _not_ using Selenium Grid?  We have a small CI/CD job that just runs our tests on a single container using the wdio-docker-service.

**Comment by dylanlive** [comment]
@jamesmortensen Great question. I used `selenium/standalone-chrome:4.0.0-beta-1-20210215` for testing. The selenium standalone does expose the cdp endpoint within capabilities. However, the endpoint they're exposing is the internal docker IP, which can't be reached.

So my PR will unfortunately hang in the case you're using Devtools Service AND the Docker Images until Selenium exposes the Hub/Router's IP/Port. They have acknowledged this as a problem in Slack, and I believe https://github.com/SeleniumHQ/selenium/issues/9202 will be the fix.

**Comment by christian-bromann** [comment]
Let's continue conversations in [respective PR](https://github.com/webdriverio/webdriverio/pull/6508).

**Comment by AlexGrs** [comment]
Hello @dylanlive 

In one of your previous message, you talked about "grabbing the endpoint directly from the response" especially for Selenoid for instance which expose an address like `<ws or http>://selenoid.example.com:4444/devtools/<session-id>/<method>`

In your PR, I can see a user can add in capabilities an address to contact the remote cdp endpoint. 

The issue with this approach is that for tools like Selenoid, the address contains the `sessionId` which is dynamic for each tests run. 

Did you try your PR with a Selenoid setup and make it work ? As of now, reading the code of the PR and the way tools like Selenoid work, I don't see how it could work except by harcoding the sessionId in the URL which we can't do.

**Comment by dylanlive** [comment]
Hey @AlexGrs,

The cdp endpoint is not a capability provided by the user. It's a capability returned by Selenium. The CDP Endpoint returned by selenium also returns a session id in this format: `http://<grid_ip>/session/<session_id>/se/cdp`

I'm on a new laptop without my examples, but it roughly works like this:
If I POST http://<grid_ip>/wd/hub/session
With the body content:
```
"desiredCapabilities": {
  "browserName": "chrome"
}
```

I will get back:
```
{
    "status": 0,
    "sessionId": "c8adfc6384648299d726d9c63d4e7a15",
    "value": {
        "se:options": {
            "cdp": "http://localhost:5555/session/c8adfc6384648299d726d9c63d4e7a15/se/cdp"
         },
    }
}
```
(plus a lot more, but this is condensed)

I have not tested selenoid, but I'd imagine if it doesn't have the key `"se:options"` in the response, it won't work. This key name is also likely to change in selenium beta 2.
