### ISSUE TITLE
[Chrome] moveTo() not working inside iframes

### ISSUE THREAD

**Issue by javierfigueroacl** [webdriverio/webdriverio#6478]
**Environment (please complete the following information):**

**WebdriverIO version:** 6.10.5
**Mode:** [WDIO Testrunner]
**If WDIO Testrunner, running sync/async:** sync
**Node.js version:** 12.4.0
**NPM version:** 6.9.0
**Platform name and version:** Ubuntu 18.04.5 LTS
**Additional wdio packages used (if applicable):** @wdio/selenium-standalone service (6.23.0)
**Describe the bug**
After upgrading to v6 of WDIO, the moveTo method stopped to work for elements inside iframes. No error is displayed, this occurs even after using switchToFrame() to access the frame that contains the element.

**Dependencies installed:**

    "selenium-standalone": "~6.23.0",
    "webdriverio": "~6.10.5",
    "@wdio/allure-reporter": "~6.8.1",
    "@wdio/cli": "~6.10.5",
    "@wdio/devtools-service": "~6.10.5",
    "@wdio/dot-reporter": "~6.8.1",
    "@wdio/junit-reporter": "~6.8.1",
    "@wdio/local-runner": "~6.10.5",
    "@wdio/mocha-framework": "~6.10.4",
    "@wdio/selenium-standalone-service": "~6.10.4",
    "@wdio/spec-reporter": "~6.8.1",
    "@wdio/sync": "~6.10.4",
    "chai": "~4.2.0",
    "chai-as-promised": "~7.1.1",
    "chai-roughly": "~1.0.0",
    "mocha": "~8.2.1",
    "mocha-logger": "~1.0.7",
    "wdio-intercept-service": "~4.1.2"

**WDIO config**

config = {
maxInstances: 10,
capabilities: [{
        maxInstances: 5,
        browserName: process.env.BROWSER || 'chrome',
        'goog:chromeOptions': {
            prefs: {
                'profile.managed_default_content_settings.popups': 1,
                'profile.managed_default_content_settings.notifications': 1
            }
        }
    }],
services: ['selenium-standalone', 'devtools', 'intercept'],
framework: 'mocha',
}

**Expected behavior**
moveTo should move the cursor to the desired point

**Comment by christian-bromann** [comment]
Can you provide a reproducible example? Also please try with the latest version (v7) if this error still occurs.

**Comment by javierfigueroacl** [comment]
I have attached a reproducible example:
[wdio-sandbox.zip](https://github.com/webdriverio/webdriverio/files/6038294/wdio-sandbox.zip)

I found out that this is happening with wdio 7 as well, so I have updated the issue title.

**Readme:**

To reproduce run:
----------------------------------------------

```
npm install

npm start

npx wdio run ./wdio.conf.js --spec example.e2e.js
```

Description:
----------------------------------------------

There are 2 buttons that change text on mouse over.
First button changes the text and pass the expect, however second button does not change the text and does not pass the expect.

Expect error displayed on console:

[chrome 88.0.4324.182 linux #0-0] Expected: "Mouse over button 2"
[chrome 88.0.4324.182 linux #0-0] Received: "Not mouse over"
[wdio-sandbox.zip](https://github.com/webdriverio/webdriverio/files/6038310/wdio-sandbox.zip)

**Comment by christian-bromann** [comment]
@javierfigueroacl thanks, this helps a lot. It seems like an issue within the WebDriver spec. IMO it should execute the action relative from the iframe. If I tweak the moveTo command implementation as follows:

```suggestion:
-                 x: newXOffset,
+                 x: newXOffset + 97,
-                 y: newYOffset
+                 y: newYOffset + 67
```

where 97px is the top distance to the root document and 67px the left distance it hits the bottom as expected. It seems this issue was brought up in the spec already in w3c/webdriver#1256. I will re-trigger that conversation to see if we can get a fix there.

**Comment by christian-bromann** [comment]
I reported the issue to the Chromedriver team which will fixes it. There is nothing in WebdriverIO we can do about this.

**Comment by MrBIN89** [comment]
@christian-bromann could you share a link to relevant chromedriver bug to follow

**Comment by kartikperumal** [comment]
Hi @christian-bromann Sorry, I understand this issue almost two years old but I am trying to find the bug to track in Chromium bug search page and can't seem to find any relevant ones. 
Could you please also mention what the workaround would be? Would it be scrolling the element into the iframe into view before trying to moveTo() it? Thanks!

**Comment by christian-bromann** [comment]
You can track the progress in the spec issues: https://github.com/w3c/webdriver/issues/1256

> Could you please also mention what the workaround would be?

I don't know a workaround around this. I also haven't done much investigation recently so if you have a clue what is going on, please let us know here.
