### ISSUE TITLE
Typings for `wdio:devtoolsOptions` in 6473 aren't working for me

### ISSUE THREAD

**Issue by dylang** [webdriverio/webdriverio#6479]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.0.7
 - **Mode:** Standlone, async
 - **Node.js version:** 14
 - **NPM version:** yarn 1
 - **Browser name and version:** n/a
 - **Platform name and version:** TypeScript 4.1.5
 - **Additional wdio packages used (if applicable):** DevTools 7.0.7

**Config of WebdriverIO**

```json5
// tsconfig.json
"types": [
  "node",
  "webdriverio/async"
],
```

```
automationProtocol: 'devtools'
browser: 'chrome',
```

**Describe the bug**

Hi, thanks for making the changes in #6473!

I'm having trouble making them work:

**To Reproduce**

From the README

```ts
    browser = await remote({
        automationProtocol: 'devtools',
        capabilities: {
            browserName: 'chrome',
            'wdio:devtoolsOptions': {
                headless: true
            }
        }
    })
```

<img width="605" alt="Screen Shot 2021-02-18 at 7 29 16 PM" src="https://user-images.githubusercontent.com/51505/108439678-bfa8de80-721f-11eb-872f-06719fabe554.png">

From `tests/typings/webdriverio/config.ts`:

```ts
import { remote } from 'webdriverio';

const getBrowser = async () => {
    const browser = await remote({
        capabilities: {
            'wdio:devtoolsOptions': {
                ignoreDefaultArgs: false
            }
        }
    });
	return browser;
};
```

<img width="807" alt="Screen Shot 2021-02-18 at 7 27 58 PM" src="https://user-images.githubusercontent.com/51505/108439671-bc155780-721f-11eb-81bf-1c11f44525a3.png">

**Expected behavior**

No error

**Comment by christian-bromann** [comment]
Can you try with `tsconfig.json` being configured as such:

```js
// tsconfig.json
"types": [
  "node",
  "devtools",
  "webdriverio/async"
],
```

**Comment by dylang** [comment]
Yes, thank you @christian-bromann, that works. 

What do you think of this alternative solution:


```ts
import 'devtools';
```

or, to avoid any potential side effects from importing devtools:

```ts
import type {} from 'devtools';
```

As you may have figured out, my team and I are not a fan of globals.

**Comment by christian-bromann** [comment]
> What do you think of this alternative solution:

This would be a major change and could break a lot of peoples test.

> As you may have figured out, my team and I are not a fan of globals.

I understand, though I think many people would not like to add these imports all the time. I am not sure what your team is concerned about having a WebdriverIO namespace defined as global. Can you elaborate?

Closing as this seems to be resolved.
