### ISSUE TITLE
Reversal of waitForExist() broken when it comes with timeout

### ISSUE THREAD

**Issue by binarykitchen** [webdriverio/webdriverio#649]
To me, it looks like that when waiting for the selector to not match any elements with the reversal option of `waitForExist()` and having a timeout specified, it's behaving weird: it doesn't wait until the selector disappeared, it waits until the timeout has expired and then fires the callback. Not earlier

```
client.waitForExist(selector, 10000, true, cb)
```

Actual: always waits 10 seconds
Expected: fires callback earlier when selector has disappeared unless there is an error

**Comment by binarykitchen** [comment]
Also, it should fire the callback asap when the selector doesn't exist at all. Right away a check at the beginning is missing.

**Comment by christian-bromann** [comment]
which version are you using? The current version does all the things:

```js
var webdriverio = require('./');
var client = webdriverio.remote({
    desiredCapabilities: {
        browserName: 'phantomjs'
    }
});

var start;

client
    .init()
    .url('http://webdriverjs.christian-bromann.com')
    .call(function() {
        start = new Date().getTime();
    })
    .waitForExist('.goAway', 10000, true)
    .call(function() {
        console.log('finished after', (new Date().getTime()) - start, 'ms');
    })
    .end();
```

**Comment by binarykitchen** [comment]
weird. i am really using the latest version. i guess it must be something else, a problem within our html or css code ...

**Comment by binarykitchen** [comment]
does the same work for you when using `waitForVisible()` instead??

my problem is that i do not know whether to use `waitForVisible()` or `waitForRemoval()` here. this because i am dealing with a very old, unstable JS framework which does hide the element first and removes it a bit later from DOM when unused.

so need something that covers both.

**Comment by christian-bromann** [comment]
ok, then use the swiss knife of waitFor commands: waitUntil:

```js
client.waitUntil(function() {
    return this.isExisting(selector).then(function(isExisting) {
        return this.isVisible(selector).then(function(isVisible) {
            return isExisting && isVisible;
        });
    });
});
```

**Comment by binarykitchen** [comment]
thanks heaps
