### ISSUE TITLE
afterScenario cucumber hook is not capturing the scenario Pass/fail status through world object

### ISSUE THREAD

**Issue by vdrulerz** [webdriverio/webdriverio#6494]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [7.0.7]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [webdriverio/sync]
 - **Node.js version:** [12.13.0]
 - **NPM version:** [e.g. 6.12.0]
 - **Browser name and version:** [openfin]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [@wdio/cucumber-framework]

**Config of WebdriverIO**

![image](https://user-images.githubusercontent.com/6131428/108748545-b774da00-7564-11eb-9e2c-209f4f988be6.png)

**Describe the bug**
world.result.status is not giving the correct pass/fail status of the scenario

**To Reproduce**
Use afterScenario hook in the wdio config file and try to log world.result.status...it won't print the exact pass/fail status as described in the screenshot. It used to be working fine with V6 as result.status

**Expected behavior**
It should print PASSED or FAILED after logging world.result.status

> Please use the correct markdown

**Comment by esaari** [comment]
@vdrulerz I just went through this same issue myself - they are being emitted, just the status codes changed (`1` is passing). You can see an example of how this is handled here: https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-browserstack-service/src/service.ts#L122

**Comment by christian-bromann** [comment]
@vdrulerz this has changed with the update to Cucumber v7. @esaari has pointed out correctly that you can find out the meaning by mapping the number to the status. This is something we could also propagate to the user given that WebdriverIO has such a map internally.

@esaari @vdrulerz would anyone be interested to take a stab at it?

**Comment by christian-bromann** [comment]
fixed in  #6941
