### ISSUE TITLE
Switching windows by number instead of url or title

### ISSUE THREAD

**Issue by stefankruijt** [webdriverio/webdriverio#6495]
I'm working on tests that need to verify that our application syncs user data between two tabs.
These 2 tabs will have the same URL and name. So I'm not sure if  https://webdriver.io/docs/api/browser/switchWindow/ can be used in this case? (urlOrTitleToMatch will be the same for both browser tabs)

An example:
1. Open myapplication.com/#/somepage in first browser tab
2. Open myapplication.com/#/somepage in 2nd browser tab
3. Do some actions in the 2nd browser tab
4. Switch back to first browser tab
5. Verify that elements have changed to expected values

**Describe the solution you'd like**
It would be nice if it's possible to open browser tabs by number. Like for instance `browser.switchWindow(0)` and `browser.switchWindow(1)`

**Describe alternatives you've considered**
I don't see this feature in the API docs at https://webdriver.io/docs/api/browser/switchWindow/. Maybe there is something I missed?

**Additional context**

**Comment by stefankruijt** [comment]
I realized that `browser.newWindow` returns the windowId. However when I open multiple windows with the same url they all got the same windowId.

Not sure if this behavior in webdriverIo is expected or a bug? It would make sense to me if you could open the same URL multiple times in different tabs.

Eventually got my test working by using Puppeteer as a workaround:
```
const page = await puppeteerBrowser.newPage();
await page.goto(baseUrl);

const pageList = await puppeteerBrowser.pages();
await pageList[window].bringToFront()
```

**Comment by christian-bromann** [comment]
@stefankruijt thanks for filing the issue. You can switch to a tab via its index using protocol commands, e.g.:

```js
const tabs = await browser.getWindowHandles()
await browser.switchToWindow(0)
```

I am not sure if it makes sense to enhance the `switchWindow` helper given that it literally would call exactly that. Happy to discuss further.

**Comment by stefankruijt** [comment]
Thanks that works! I wasn't aware `browser.getWindowHandles()` exists. Would it make sense to add this to the docs at https://webdriver.io/docs/api/?

**Comment by christian-bromann** [comment]
It is part of the API docs but in the protocol section: https://webdriver.io/docs/api/webdriver
