### ISSUE TITLE
[wdio-junit-reporter] optional "system-out" by setting configuration, make reporter more clear and simple

### ISSUE THREAD

**Issue by Himoriarty** [webdriverio/webdriverio#6499]
when i get a junit-reporter, it containes many `system-out` information, that make me difficult to read the reporter.   

What I want to:
the xml  file of the reporter just outputs like the example of webdriverio's document without `system-out` label by setting configuration.

**Comment by christian-bromann** [comment]
I am not much familiar how this will effect the junit reports rendered e.g. in Jenkins. Can you provide some screenshots for that? It doesn't need to be Jenkins, just any other platform that uses these reports to generate output.

> like the example of webdriverio's document

Which document are you referring to?

**Comment by Himoriarty** [comment]
> I am not much familiar how this will effect the junit reports rendered e.g. in Jenkins. Can you provide some screenshots for that? It doesn't need to be Jenkins, just any other platform that uses these reports to generate output.
> 
> > like the example of webdriverio's document
> 
> Which document are you referring to?

example of webdriverio：
![image](https://user-images.githubusercontent.com/28705788/109934893-f4c92c80-7d07-11eb-8c25-967ff249ad96.png)
 
my result:
![image](https://user-images.githubusercontent.com/28705788/109935041-204c1700-7d08-11eb-8688-6c0e123808bc.png)

**Comment by christian-bromann** [comment]
And what is the desired state here?

**Comment by Himoriarty** [comment]
> And what is the desired state here?

I desired that I can choose whether to print <system-out> information in the report or not.

**Comment by christian-bromann** [comment]
> I desired that I can choose whether to print information in the report or not.

So you don't want to have the WebDriver commands in your JUnit report? Where do you use the report that these information are undesired?

**Comment by Himoriarty** [comment]
after my test case is executed, WebDriverIO will generate the junit-report, it contains many lines of system-out. if my mates execute the same test case at the same time, there is a high probability of conflict when submitting git, because the system-out information in junit-report usually is different at every turn.

**Comment by christian-bromann** [comment]
@Himoriarty oh so you are committing these log files into your repository? May I suggest to write a custom reporter that only stores the information which might be conflict free and save to commit into a repository? Because all junit reports have time stamps that will always conflict with other reports.

**Comment by Himoriarty** [comment]
> @Himoriarty oh so you are committing these log files into your repository? May I suggest to write a custom reporter that only stores the information which might be conflict free and save to commit into a repository? Because all junit reports have time stamps that will always conflict with other reports.

get it! i really appreciate your patience, thank you for your advice.

**Comment by Primajin** [comment]
I am also running into this issue and wonder if there is a way to either remove this or fix the reporter starting to choke after many lines.

I set all logging to `silent` and tried to tweak `errorOptions` but it still puts this verbose logs in there.

Thus working fine for around 1500 lines, it starts to choke at some point leaving the XML file unparseable:

![Screenshot 2022-09-30 at 14 36 50](https://user-images.githubusercontent.com/1742115/193271133-b4ab6fc0-ba77-4667-ad15-c99260bfc59a.png)


While having less lines seem to work:
![Screenshot 2022-09-30 at 14 37 49](https://user-images.githubusercontent.com/1742115/193271330-b39d9f5d-0182-4e4a-ae1d-ede3a09ae521.png)

**Comment by christian-bromann** [comment]
@Primajin mind raising a new issue for this as I guess this is different from what the original poster had in mind. Bascially you are saying the reporter is unable to store large amount of data in the file, right?

**Comment by Primajin** [comment]
Correct, OK will do so 👌🏻
