### ISSUE TITLE
Question: waitFor.. methods only work with CSS selectors, or with Xpath also?

### ISSUE THREAD

**Issue by cristian-smocot** [webdriverio/webdriverio#651]
Like the title says, my question (not necessarily an issue) is if __waitFor..__ methods only work with CSS selectors, or XPath selectors are also usable in waitFor.. logic?

**Comment by christian-bromann** [comment]
@cristian-smocot you can use any [selector strategy](http://webdriver.io/guide/usage/selectors.html) here :wink:
