### ISSUE TITLE
[wdio.conf Hooks] afterStep runs after Cucumber step has an undefined 'uri' - AfterScenario is fine

### ISSUE THREAD

**Issue by Joostverrijk** [webdriverio/webdriverio#6510]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [7.0.7]
 - **Mode:** [Standalone]
 - **If WDIO Testrunner, running sync
 - **Node.js version:** [e.g. 14.15.5]
 - **NPM version:** [e.g. 6.14.11]
 - **Browser name and version:** [e.g. Chrome  88.0.4324.182 (Official Build) (x86_64)]
 - **Platform name and version:** [OSX]
 - **Additional wdio packages used:
    "@wdio/cucumber-framework": "^7.0.7",
    "@wdio/junit-reporter": "^7.0.7",
    "@wdio/local-runner": "^7.0.7",
    "@wdio/selenium-standalone-service": "^7.0.7",
    "@wdio/spec-reporter": "^7.0.7",
    "@wdio/sync": "^7.0.7",

**Config of WebdriverIO**
An example of how you configured WebdriverIO config
With cucumber

**Describe the bug**
I want to use information that is within the uri variable in the AfterStep inside the wdio.conf file. But it's always undefined. 
console.log(JSON.stringify(uri)); ==> result undefined

When doing the same with the afterScenario Hook, the result is an object with all the info necessary.

**To Reproduce**
This is my line added to wdio.conf:
afterStep: function afterStep({ uri, feature, step }, context, { error, result, duration, passed, retries }) {
        if ({passed}.passed === false ) {
            console.log(JSON.stringify(uri));
        }
    },

[Include code or an example repository that can easily be set up]

**Expected behavior**
I want the contents of uri

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Comment by esaari** [comment]
@Joostverrijk The `afterStep` hook has changed for v7: https://webdriver.io/docs/options#afterstep

**Comment by Joostverrijk** [comment]
So the conf.js comments are invalid?

`{ uri, feature, step }, context, { error, result, duration, passed, retries }) {`

**Comment by christian-bromann** [comment]
@Joostverrijk yes, see the [updated wdio.conf.js](https://github.com/webdriverio/webdriverio/blob/main/examples/wdio.conf.js#L361) version.

**Comment by lacell75** [comment]
So, how to get feature or scenerio information in afterStep function with V7? It doesn't work in my case.

**Comment by christian-bromann** [comment]
> So, how to get feature or scenario information in afterStep function with V7?

feature information can be received in `before/afterFeature` and scenario information in `before/afterScenario`

**Comment by lacell75** [comment]
In my case, I need to retreive these information in AfterStep, This is no longer possible?
my code in v6 
`afterStep: ({ step }, context, {
    passed,
  }) => {
    if (passed
      && failureObject === null
      && !step.scenario.tags.map((tag) => tag.name).includes('@DieManufacturing')
      && !step.step.keyword.includes('Given')
      && !step.step.text.includes('I am logged on ')
      && !step.step.text.includes('I switch to ')
      && !step.step.text.includes('I expect a new tab has been opened')
      && browser.getUrl().includes(targetedEnv)) {
      const NoErrorToast = browser.execute(toastInterceptor.expectToast);
      if (NoErrorToast !== true && NoErrorToast !== null && NoErrorToast !== 'null') {
        failureObject = {};
        failureObject.type = 'afterStepError';
        failureObject.stepTitle = `${step.step.keyword}${step.step.text}`;
        failureObject.error = `An error message is displayed during test: "${NoErrorToast}"`;
        // console.log('error detected');
        browser.takeScreenshot();
      }
    }
  },`

**Comment by christian-bromann** [comment]
@lacell75 you can store the step information in memory and use them in your afterStep hook.

**Comment by lacell75** [comment]
Thanks , that works
