### ISSUE TITLE
TypeError when passing a third arg into a mocha test

### ISSUE THREAD

**Issue by patkunicki** [webdriverio/webdriverio#6511]
**Environment:**
 - **WebdriverIO version:** ^6.11.0
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v12.18.3
 - **NPM version:** 6.14.6
 - **Browser name and version:** Chrome 68
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used:** @wdio/mocha-framwork

**Describe the bug**
When a third param is passed into a mocha `it` the test fails before the test code is run. The error thats thrown:
`TypeError: fn.apply is not a function`

**To Reproduce**
Run the following test with the mocha-framework, content of the test doesnt matter.

`describe('describe', () => {
    it('it', () => {
        // some code
    }, {
        options: {}
    })
})`

**Expected behavior**
I would expect that wdio would ignore the third arg and just use the title and function. I've tested this using vanilla mocha, there isnt a type check error when options are passed in, and the test runs correctly.

**Additional context**
The reason for the third arg is that we have a custom mocha integration that requires some params to be passed in in certain cases.

**Comment by christian-bromann** [comment]
Let's continue convo in respective PR.
