### ISSUE TITLE
[corner case] exception when calling `click` if the window is closed after the click

### ISSUE THREAD

**Issue by link89** [webdriverio/webdriverio#6515]
One of our products has a detached window that can be put back by clicking an `attach back` button. By doing this the window will be closed. We found that the following error will be thown.

`ERROR webdriver: Request failed with status 404 due to no such window: no such window: window was already closed
  (Session info: chrome=88.0.4324.192)`

After some investigation, I found that `webdirver.io` implements the` click` method by `ActionChain`. And it will call `Release Actions` after `Perform Actions` is executed. And since the window is no longer exists after calling the `Perform Action`, the `Release Actions` will always fail.  We can't even try-catch this exception because it is an async call.

We are now working around this problem by simulating the click action via `execute script`. But I hope the bug could be fixed in `webdriver.io`.

Webdriver.io version: 6.6.6

**Comment by christian-bromann** [comment]
@link89 thanks for filing an issue. This is indeed an interesting corner case. I suggest to wrap the `releaseAction` command in our [click implementation](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/element/click.ts#L133) within a try/catch and only re-throw the error if it doesn't contain `no such window`. I think this is a nice first ticket to work on, you want to take a stab at it?

**Comment by christian-bromann** [comment]
Let's continue conversation in #6535
