### ISSUE TITLE
WDIO v.7 with async mode and TypeScript incorrectly returns types

### ISSUE THREAD

**Issue by xmtigra** [webdriverio/webdriverio#6518]
**Environment:**
 - **WebdriverIO version:** [e.g. 7.0.8]
 - **Mode:** [Standalone mode]
 - **Node.js version:** [e.g. 15.7.0]
 - **NPM version:** [e.g. 7.4.3]
 - **Browser name and version:** [e.g. Chrome 88]
 - **Platform name and version:** [e.g. MacOS Catalina 10.15.7]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**tsconfig.json** 
`"compilerOptions": {
...
"types": [
"webdriverio/async",
"node"
]
...
}`

**Describe the bug**
WDIO v.7 with async mode and TypeScript incorrectly returns types

```
get paragraph() {       // return wrong type WebdriverIO.Element
   return $("p");
}
```

```
get paragraphs() {       // return corrent type Promice<ElementArray>
   return $$("p");
}
```

https://ibb.co/wJhVwFF
https://ibb.co/hCS6Hcb

**Comment by christian-bromann** [comment]
@xmtigra thanks for raising an issue, a fix was proposed in #6520
