### ISSUE TITLE
v7.0 does not save executed commands (works in v4)

### ISSUE THREAD

**Issue by DudaGod** [webdriverio/webdriverio#6519]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.0.0
 - **Mode:** standalone
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 12.18.1
 - **NPM version:** 6.14.5
 - **Browser name and version:** chrome@85
 - **Platform name and version:** Linux

**Config of WebdriverIO**
Example of test:
```
const {remote} = require('webdriverio');
let client;

(async function () {
    client = await remote({
        automationProtocol: 'devtools',

        capabilities: {
            browserName: 'chrome',
            browserVersion: '85.0',
        }
    });

    await client.url('https://yandex.ru')

    console.log('client.commandList:', client.commandList);

    await client.deleteSession();
})()
    .catch(async (e) => {
        console.error(e.stack)
        await client.deleteSession()
    })

```

**Describe the bug**
In wdio@4 in `client.commandList` was the list of executed commands, but now it consists all available browser commands. This feature was added here - https://github.com/webdriverio/webdriverio/commit/43efd4a8463419cfe5c347268544b19e62394931.

My questions:
- is there any workaround to get executed commands?
- why it was removed?
- can I implement this feature in current version?

**Comment by christian-bromann** [comment]
> * is there any workaround to get executed commands?

You can use listeners to store data about executed commands and results, e.g.
```js
browser.on('command', (command) => console.log(command))
browser.on('command', (result) => console.log(result))
```

> * why it was removed?

I am not entirely sure but I assume for performance reasons. Storing command and result data for long tests can have tremendous impact on memory (e.g. when screenshots are stored)

> * can I implement this feature in current version?

For above reasons I don't think this feature would justify its value, particularly as it can be implemented using listeners.

I hope this answers your questions. Happy to address further ones.

**Comment by DudaGod** [comment]
> You can use listeners to store data about executed commands and results, e.g.

I tried to use them and they do not cover all features from v4: 
- ability to save all called command names
- arguments with which the command was called

Example of test:
```
const wdio = require('webdriverio');
const Promise = require('bluebird');

let client;

(async function () {
    client = await wdio.remote({
        protocol: 'http',
        hostname: 'some-host,
        port: 4444,
        path: '/wd/hub',
        capabilities: {
            browserName: 'chrome',
            browserVersion: '85.0',
        }
    });

    client.addCommand('foo', async (args) => {
        await Promise.delay(1000);
    });

    client.on('command', (command) => {
        console.log('===> RUN COMMAND:', command);
    });

    client.on('result', (result) => {
        console.log('<=== COMMAND RESULT:', result);
    });

    await client.url('https://yandex.ru');
    const body = await client.$('body');
    await body.click();
    await client.foo('arg1', 'arg2');
    await client.pause(3000);

    await client.deleteSession();
})()
    .catch(async (e) => {
        console.error(e.stack)
        await client.deleteSession()
    })
```

When run it with `automationProtocal=webdriver` I see:
```
===> RUN COMMAND: {
  method: 'POST',
  endpoint: '/session/:sessionId/url',
  body: { url: 'https://yandex.ru/' }
}
<=== COMMAND RESULT: {
  method: 'POST',
  endpoint: '/session/:sessionId/url',
  body: { url: 'https://yandex.ru/' },
  result: { value: null }
}
===> RUN COMMAND: {
  method: 'POST',
  endpoint: '/session/:sessionId/element',
  body: { using: 'css selector', value: 'body' }
}
<=== COMMAND RESULT: {
  method: 'POST',
  endpoint: '/session/:sessionId/element',
  body: { using: 'css selector', value: 'body' },
  result: {
    value: {
      'element-6066-11e4-a52e-4f735466cecf': '17431f19-05e1-4096-929b-241ff1210f72'
    }
  }
}
===> RUN COMMAND: {
  method: 'POST',
  endpoint: '/session/:sessionId/element/17431f19-05e1-4096-929b-241ff1210f72/click',
  body: {}
}
<=== COMMAND RESULT: {
  method: 'POST',
  endpoint: '/session/:sessionId/element/17431f19-05e1-4096-929b-241ff1210f72/click',
  body: {},
  result: { value: null }
}
<=== COMMAND RESULT: { name: 'foo', result: undefined }
===> RUN COMMAND: { method: 'DELETE', endpoint: '/session/:sessionId', body: {} }
<=== COMMAND RESULT: {
  method: 'DELETE',
  endpoint: '/session/:sessionId',
  body: {},
  result: { value: null }
}
```

In that log I don't see command names that I run (`url`, `$`, `click`, `pause`, `deleteSession`). Url from endpoint does not match one by one to command name. Moreover I can't get params of called methods.

So it looks like, that it does cover my needs (line in v4).

> I am not entirely sure but I assume for performance reasons. Storing command and result data for long tests can have tremendous impact on memory (e.g. when screenshots are stored)

But we can add some option to enable this feature so if user want to save commands he will do it on purpose.

> For above reasons I don't think this feature would justify its value, particularly as it can be implemented using listeners.

Currently I can't implement the same feature using only listeners, because they don't have all info that I need.

> I hope this answers your questions. Happy to address further ones.

New question:
- can we add listeners that will inform about called commands with their params or implement feature from v4 with using flag to enable it?

**Comment by christian-bromann** [comment]
> In that log I don't see command names

I see no problem adding that information to the [event trigger](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriver/src/command.ts#L91).

> Moreover I can't get params of called methods.

They are as part of the `body` property, no?

> * can we add listeners that will inform about called commands with their params or implement feature from v4 with using flag to enable it?

I would propose to enhance the event payload rather than implementing this feature behind a flag.
