### ISSUE TITLE
Access the wdio.conf from the the global scope

### ISSUE THREAD

**Issue by guillegette** [webdriverio/webdriverio#652]
Hi there,

What do you guys think having a method in the browser object to get the configuration that was used to initiate WebdriverIO in the test runner ? That way I would be able to get the full path url and potentially other settings :)

Cheers,
G.

**Comment by christian-bromann** [comment]
Honestly I don't want to pollute the browser namespace any more. You can access your settings with:

```js
console.log(browser.options);
// or
console.log(browser.desiredCapabilities);
```

If you want to access your config file just assign your desired properties in the before hook:

```js
/**
 * config file
 */
var specs = ['...'];

exports.config = {
    // ...
    before: function() {
        browser.specs = specs
    }
};
```

Cheers

**Comment by YuxuanLin** [comment]
Suggest put this in doc please. A really often usage.

**Comment by christian-bromann** [comment]
@YuxuanLin we have [this documentation page](http://webdriver.io/guide/testrunner/browserobject.html), would you mind proposing a PR to add things that are missing?

**Comment by YuxuanLin** [comment]
Of course. I will do this when I am free
