### ISSUE TITLE
element.$ retrieves the wrong element on page containing nested tables.

### ISSUE THREAD

**Issue by kurtsmurf** [webdriverio/webdriverio#6524]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.0.8
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v14.15.4
 - **NPM version:** 6.14.10
 - **Browser name and version:** Chrome 88.0.4324.190
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** n/a

**Config of WebdriverIO**
See [wdio.conf.js](https://github.com/kurtsmurf/repro-wdio-bug/blob/master/wdio.conf.js) in minimum reproducible example.

**Describe the bug**
When dealing with a page containing nested tables, `$('inner-table-selector').$('tbody tr')` returns the incorrect element. Instead of first row of inner table body, the above returns first row of inner table head.

See minimum reproducible example [here](https://github.com/kurtsmurf/repro-wdio-bug).

**To Reproduce**
Clone [minimum reproducible example repository](https://github.com/kurtsmurf/repro-wdio-bug).

Run `npm run serve` to serve example website-under-test.

Run 'npm t' to reproduce.

**Expected behavior**
Given markup like this (containing nested tables):
```
table#outer-table
    thead
        tr
        ...
    tbody
        tr
            td
                table#inner-table
                    thead
                        tr
                            th
                    tbody
                        tr
                            td
```
`$('#inner-table').$('tbody tr')` returns the first row of the inner table's body.

**Log**
https://github.com/kurtsmurf/repro-wdio-bug/blob/master/spec.log

**Additional context**
`$('#inner-table tbody tr')` works as expected

**Comment by christian-bromann** [comment]
@kurtsmurf thanks for filing the issue. This is indeed a funky behavior and I [reported it](https://github.com/whatwg/html/issues/6435) in the HTML spec. There is nothing WebdriverIO can do at this point to fix the issue as the problem rooted within HTML.

**Comment by christian-bromann** [comment]
Please see the following explanation to this: https://github.com/whatwg/dom/issues/956#issuecomment-790690973

**Comment by kurtsmurf** [comment]
Yup - saw it. Many thanks for your help @christian-bromann! Love when I can get a solution _and_ learn something new about the web platform!
