### ISSUE TITLE
Ability to create wdio instance without run new browser session

### ISSUE THREAD

**Issue by DudaGod** [webdriverio/webdriverio#6525]
**Is your feature request related to a problem? Please describe.**

In v4 method [`remote`](https://github.com/webdriverio/webdriverio/blob/v4.14.1/index.js#L28-L43) creates new wdio instance without init new session. There was command [`init`](https://github.com/webdriverio/webdriverio/blob/v4.14.1/lib/protocol/init.js) for this purpose.

We used this opportunity in next way:
- in [our tool](https://github.com/gemini-testing/hermione) wdio instance created in master process and then init new browser session;
- master process run tests in workers and pass them `sessionId` which should be used in new wdio instance. It means that each worker create new wdio instance (because we can't pass instance between ipc) and overrides `sessionId` from master. And run tests after that. So we can run test in the same browser session from different workers, but wdio instance in each worker is different.

In v7 method [`remote`](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/index.ts#L31) and [init new browser session by default inside](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/index.ts#L57). 

**Describe the solution you'd like**
I want to implement ability to create wdio instance without create new browser session it it like it was in wdio@4.
It can looks like:
```
const browser = await wdio.remote(options, () => {}, {createNewSession: false});
const session = await browser.newSession(...);
```

What do you think?

**Comment by christian-bromann** [comment]
@DudaGod isn't this what the `attach` method would do? I think this isn't very well documented but you can do things like:

```js
import { attach } from 'webriverio'

const browser = attach({
  sessionId: 'xxx'
})

await browser.url('...')
```

**Comment by DudaGod** [comment]
@christian-bromann you are right, it works when I using `automationProtocol=webdriver`.
Example of master process:
```
const cp = require("child_process");
const path = require('path');
const wdio = require('webdriverio');

const worker = cp.fork(path.join(process.cwd(), './worker'));

let client;

(async function () {
    client = await wdio.remote({
        protocol: 'http',
        hostname: 'localhost',
        port: 4444,
        path: '/wd/hub',
        automationProtocol: 'webdriver',

        capabilities: {
            browserName: 'chrome',
            browserVersion: '85.0',
        }
    });

    worker.send({sessionId: client.sessionId});

    worker.on('message', async () => {
        await client.deleteSession();
        process.exit(0);
    });
})()
    .catch(async (e) => {
        console.error(e.stack);
        await client.deleteSession();
    });
```

Example of worker process:
```
const wdio = require('webdriverio');

process.on('message', async ({sessionId}) => {
    const client = await wdio.attach({
        sessionId,
        protocol: 'http',
        hostname: 'localhost',
        port: 4444,
        path: '/wd/hub',
        automationProtocol: 'webdriver',
    });

    await client.url('https://github.com');

    process.send(`worker.${sessionId}.freeBrowser`);
});
```

But it doesn't work when I try to use `automationProtocol=devtools`.
Code of worker when I want that wdio use default options and explicitly set `automationProtocol`:
```
const wdio = require('webdriverio');

process.on('message', async ({sessionId}) => {
    const client = await wdio.attach({
        sessionId,
        automationProtocol: 'devtools',
    });

    await client.url('https://github.com');

    process.send(`worker.${sessionId}.freeBrowser`);
});
```

In that case I get error:
```
2021-03-01T19:07:34.355Z INFO webdriver: COMMAND navigateTo("https://github.com/")
(node:40939) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: undefined://undefined:undefined/session/2a61755d-6971-46f1-83f8-ded9bd8381cb/url
```

It looks like that inside attach `devtools` is not supported because it call method `attachToSession` from package `webdriver` and not from package `devtools`.
In `devtools` packages I see that `attachToSession` method is not implemented yet - https://github.com/webdriverio/webdriverio/blob/main/packages/devtools/src/index.ts#L129-L131.

It's hard to implement this feature or no one has needed such an opportunity yet? Can I do it?

**Comment by christian-bromann** [comment]
It is already in progress at #6459

**Comment by DudaGod** [comment]
> It is already in progress at #6459

🔥  Thank you.
