### ISSUE TITLE
Firefox-Profile in WebDriverIO

### ISSUE THREAD

**Issue by achandra31** [webdriverio/webdriverio#653]
Hi Chris,
I need to set my Firefox profile in WebdriverIO similar to the example in this issue: https://github.com/webdriverio/webdriverio/issues/240
I notice that the one mentioned in that issue was for webdriverjs.

Please let me know if there are any modules or embedded module in webdriverio similar to those.

Thanks,
Agus Wicaksana

**Comment by christian-bromann** [comment]
Hi Agus,
webdriverjs is the old project name of WebdriverIO. You can apply the firefox profile exactly the same way it is described there.

Cheers
