### ISSUE TITLE
Webdriver capabilites error

### ISSUE THREAD

**Issue by halukbaysal** [webdriverio/webdriverio#6539]
Environment:

WebdriverIO version: [7.0.7]
Mode: [WDIO Runner]
If WDIO Testrunner, running sync/async: [async]
Node.js version: [v12.18.3]
NPM version: [6.14.6]
Browser name and version: [Chrome 88.0.4324.192]
Platform name and version: [MacOS Catalina]
Additional wdio packages used (if applicable): [@wdio/allure-reporter, @wdio/spec reporter, @wdio/selenium-standalone service, @wdio/browserstack-service, @wdio/cucumber-framework, @wdio/devtools-service, @wdio/spec-reporter, @wdio/local-runner]

**Config of WebdriverIO**
example project: https://github.com/halukbaysal/wdio_v7

**Describe the bug**
ERROR @wdio/runner: Error: Invalid or unsupported WebDriver capabilities found ("os", "os_version", "browser_version", "resolution", "project", "build", "name", "browserstack.debug", "browserstack.selenium_version", "browserstack.use_w3c", "browserstack.networkLogs", "browserstack.console", "browserstack.idleTimeout"). Ensure to only use valid W3C WebDriver capabilities (see https://w3c.github.io/webdriver/#capabilities).

**To Reproduce**
Update the user and key for BrowserStack in wdio.conf.js file and execute the test

**Comment by christian-bromann** [comment]
@halukbaysal as the error message states you are using invalid capabilities, please ensure that your capabilities are conform with the W3C protocol, e.g.:

```js
var capabilities = {
	'bstack:options' : {
		"os" : "Windows",
		"osVersion" : "10",
		"projectName" : "some project",
		"buildName" : "some build",
		"sessionName" : "some name",
		"local" : "true",
		"seleniumVersion" : "3.14.0",
		"userName" : "christianbromann1",
		"accessKey" : "9U4FPti5ctHDgFc5j7eM",
	},
	"browserName" : "Chrome",
	"browserVersion" : "latest",
}
```

see also https://www.browserstack.com/automate/capabilities?tag=selenium-4
