### ISSUE TITLE
Not able to see flow chart for test execution

### ISSUE THREAD

**Issue by KundanGaikwad** [webdriverio/webdriverio#6540]
I'd like to report
- [Flow chart for the test execution ] Missing documentation

Please add more details to the test execution flow chart. because the flow chart is not there. 

Evidence:-
![image](https://user-images.githubusercontent.com/65899596/109849608-92285000-7c77-11eb-88a9-4f7e050cf9db.png)
https://webdriver.io/docs/flowcharts/testexecution/

**Comment by klamping** [comment]
Seems the `script` tags were stripped from the flowchart markdown files. I believe these are the most recent versions:
https://github.com/jdavis61/webdriverio/tree/master/docs/flowcharts

@christian-bromann Was there a reason why these tags were removed, or was it just incidental to the docasaurus upgrade and they can be added back in?

**Comment by christian-bromann** [comment]
> or was it just incidental to the Docusaurus upgrade and they can be added back in?

Yes exactly that.

**Comment by klamping** [comment]
FYI, trying to get these scripts added back in.

**Comment by klamping** [comment]
Just an update. I'm having some compilation errors with adding the scripts back in. Not sure what's going on, so stuck trying to figure that out.

**Comment by naddison** [comment]
Looking for these as well!

**Comment by christian-bromann** [comment]
@klamping any updates? Happy to help with the compilation errors.

**Comment by christian-bromann** [comment]
Thanks @tamil777selvan for bringing back these flow charts!
