### ISSUE TITLE
@wdio/devtools-service. An incorrect parameter is passed in the beforeSession hook

### ISSUE THREAD

**Issue by fedoseevGIT** [webdriverio/webdriverio#6545]
**Environment (please complete the following information):**
 - **Additional wdio packages used (if applicable):** [@wdio/devtools-service 7.0.9]

**Describe the bug**
I'm getting the next error "@wdio/devtools-service: The @wdio/devtools-service currently only supports Chrome version 63 and up, and Chromium as the browserName!" while using the latest devtools 7.0.9. All other packages up to date as well.

Problem in [beforeSession hook](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-devtools-service/src/index.ts#L46):

```
beforeSession (_: unknown, caps: Capabilities.Capabilities) {
        if (!isBrowserSupported(caps)) {
            return log.error(UNSUPPORTED_ERROR_MESSAGE)
        }
        this._isSupported = true
    }
```

Capabilities are passed by the first parameter, not the second.

**Expected behavior**
The service will start successfully.

```
beforeSession (caps: Capabilities.Capabilities) {
        if (!isBrowserSupported(caps)) {
            return log.error(UNSUPPORTED_ERROR_MESSAGE)
        }
        this._isSupported = true
    }
```

**Comment by christian-bromann** [comment]
@fedoseevGIT not sure what to say other than: your environment is not supported. Note it only works with Chrome v63 and up.

**Comment by fedoseevGIT** [comment]
@christian-bromann, Yes, thank you, I understood the problem: in the project we use @wdio6, where in the beforeSession hook, the first parameter is passed capabilities, and the second is the path to the executable test.

Issue can be closed :)
