### ISSUE TITLE
wdio-devtools, First Input Delay metric is missing

### ISSUE THREAD

**Issue by Vojow** [webdriverio/webdriverio#6546]
**Environment (please complete the following information):**
 - **WebdriverIO version: 7.0.9

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
The first input delay, which was mentioned in release notes: [https://webdriver.io/blog/2021/02/09/webdriverio-v7-released/](url), is missing in all related areas 
![image](https://user-images.githubusercontent.com/35311417/109947024-2b3b8300-7cd9-11eb-8aaa-effec9e30358.png)
![image](https://user-images.githubusercontent.com/35311417/109947066-342c5480-7cd9-11eb-8d5f-fbda3f245ce6.png)

**Expected behavior**
Possibility to access FID from Lighthouse 7+.

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
`firstInputDelay` got deprecated and was replaced by `maxPotentialFID`. Please updated to `v7.14.0` to use this metric. Thanks!
