### ISSUE TITLE
Improve typings by using function overloads

### ISSUE THREAD

**Issue by flunderpero** [webdriverio/webdriverio#6549]
The Typescript signatures are sometimes too loose and unnecessarily hard to use. Take `getLocation` as an example:
```
export default function getLocation(this: WebdriverIO.Element, prop?: 'x' | 'y'): Promise<number | {
    x: number;
    y: number;
}>;
```
This is hard to use because the return type is not bound to the input type. I have to do a type cast which should not be needed.

**Describe the solution you'd like**
This could be easily solved by using overload signatures like this:

```
export function getLocation(this: WebdriverIO.Element): Promise<{
    x: number;
    y: number;
}>
export function getLocation(this: WebdriverIO.Element, prop: 'x' | 'y'): Promise<number>
function getLocation(this: WebdriverIO.Element, prop?: 'x' | 'y'): Promise<number | {
    x: number;
    y: number;
}> {
   // Implementation does not need to change ...
}
```

**Additional context**

This is just an example that - together with `getSize` - jumped me right in the face while updating our codebase to WebdriverIO 7.

**Comment by christian-bromann** [comment]
Ah perfect, good idea @flunderpero! Would you like to take a stab at it?

**Comment by iamkenos** [comment]
hi there, i tried to give this a go as i also noticed this problem whilst migrating to v7:
https://github.com/webdriverio/webdriverio/compare/main...iamkenos:feat/6549-improve-typings-using-overloads

just that even after doing so, the return type still isnt bound to the input type:
![image](https://user-images.githubusercontent.com/21245218/110075942-a165e580-7dbe-11eb-84d4-5c42cd7ad300.png)

that or i'm missing something.

i'm also thinking whether something like [this](https://stackoverflow.com/a/54166010/2285470) is alright but i'm not sure if it's doable or whether it will overcomplicate things if it is.

thoughts?

**Comment by christian-bromann** [comment]
@iamakulov for synchronous commands we need to transform them from having promise return value to normal return values. This happens [here](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/types.ts#L12-L28). It might be that this isn't picked up which makes sense to me but I have really no clue how this can be done in TS.

**Comment by iamakulov** [comment]
> @iamakulov for synchronous commands we need to transform them from having promise return value to normal return values. This happens [here](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/types.ts#L12-L28). It might be that this isn't picked up which makes sense to me but I have really no clue how this can be done in TS.

I’m guessing that was for @iamkenos :) (No worries! GitHub’s username autosuggestion is tricky.)

**Comment by christian-bromann** [comment]
Uups, sorry @iamakulov - cool name though 😉

**Comment by iamkenos** [comment]
> @iamakulov for synchronous commands we need to transform them from having promise return value to normal return values. This happens [here](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/types.ts#L12-L28). It might be that this isn't picked up which makes sense to me but I have really no clue how this can be done in TS.

@christian-bromann @flunderpero i think i got something. it's not as straightforward as i wanted it to be but i think it works and fixes the issue.

diff in [here](https://github.com/webdriverio/webdriverio/compare/main...iamkenos:feat/6549-improve-typings-using-overloads)

async:
<img width="692" alt="Screenshot 2021-03-06 at 5 20 17 PM" src="https://user-images.githubusercontent.com/21245218/110203055-ed8c5500-7ea6-11eb-9256-f5c5b82df5c6.png">
<img width="692" alt="Screenshot 2021-03-06 at 5 20 56 PM" src="https://user-images.githubusercontent.com/21245218/110203064-f1b87280-7ea6-11eb-9b9b-99d442bee0c2.png">

sync:
<img width="692" alt="Screenshot 2021-03-06 at 6 03 54 PM" src="https://user-images.githubusercontent.com/21245218/110203069-f715bd00-7ea6-11eb-8934-c0d1de0349fe.png">
<img width="692" alt="Screenshot 2021-03-06 at 6 04 05 PM" src="https://user-images.githubusercontent.com/21245218/110203075-fbda7100-7ea6-11eb-9045-bc66629155d5.png">

i'd like to know your thoughts before i check other commands and proceed with a pr.

ps - that's gonna be my first time contributing so i dont really know how it goes 😬

**Comment by christian-bromann** [comment]
Looks good, feel free to open a PR. Too bad this can't be referred automatically from the file and a redeclaration is necessary but I guess we have a very special case offering an API in async and sync mode.

**Comment by azygis** [comment]
Apparently I am also working on the same issue that @iamkenos works on and created a draft-ish PR #6555. I don't really see the problem that you have - there is no need to "redeclare" the functions other than having the overloads themselves.

I will drop my pull request later, but you can take a look at the code there I suppose, it does imply the correct return type based on argument type.

**Comment by christian-bromann** [comment]
Fixed by https://github.com/webdriverio/webdriverio/pull/6558
