### ISSUE TITLE
Firefox-Profile error during run

### ISSUE THREAD

**Issue by achandra31** [webdriverio/webdriverio#655]
Hi Chris,
I've install the npm install firefox-profile and has this line of code:
 var FirefoxProfile = require('./node_modules/firefox-profile')

    var fp = new FirefoxProfile();
    fp.setPreference("browser.download.folderList",2);
    fp.setPreference("browser.download.manager.showWhenStarting",false);
    fp.setPreference("browser.download.dir", process.env.KE_HOME);
    fp.setPreference("browser.helperApps.neverAsk.saveToDisk","application/octet-stream");

    before(function(done){
        
            global.client = {};
            client = webdriverio.remote({ desiredCapabilities: {browserName: 'firefox', firefox_profile: this.fp} });
            client.init(done);
                
        });

        after(function(done) {
            client.end(done);
        });

But when I tried to run it, it returned this error:
![firefox-profile error](https://cloud.githubusercontent.com/assets/12491390/8822067/dd3551ac-308c-11e5-936b-d5435bb2c8f6.PNG)

Thanks.

**Comment by christian-bromann** [comment]
WebdriverIO doesn't use `concat-map`. Seems to be a missing dependency in one of your dependencies. Did you tried to install it `npm install concat-map` ?

Closing as it is not a WebdriverIO issue but feel free to ask more questions in this thread.

**Comment by achandra31** [comment]
Thanks Chris.
I want the Firefox to download automatically to desired folder as set in the profile above.
But, when I ran the code and click on the link button, it still showing up the dialog box:
![click link button](https://cloud.githubusercontent.com/assets/12491390/8822670/54bf9ce2-3091-11e5-9c49-5fbcd3be4603.PNG)

**Comment by christian-bromann** [comment]
I don't know about this migration jar. The problem in your script is that a NPM module is missing. You need to find out which dependency is using it.

**Comment by achandra31** [comment]
Sorry, I didn't mention.
I have resolved the dependencies issue.
Now, when I try to run my code, I want that when the automation clicked on the "Click to download migration JAR" button, it will automatically downloaded the .jar file to the desired folder as set in the profile: 
fp.setPreference("browser.download.dir", process.env.KE_HOME);

On the contrary, it still displaying that dialog box Save File.
Do you have any example setting a Firefox profile in webdriverio?

**Comment by christian-bromann** [comment]
ahh I see, I would check out the firefox-profile docs for that. There has to be an option that downloads file automatically. 

> Do you have any example setting a Firefox profile in webdriverio?

WebdriverIO doesn't work different here. If you see an example using a different library it should also work in WebdriverIO.

**Comment by achandra31** [comment]
Thanks Chris.
