### ISSUE TITLE
Use a remote Chrome browser with DevTools Protocol

### ISSUE THREAD

**Issue by nicolasbouffard** [webdriverio/webdriverio#6550]
**Environment :**
 - **WebdriverIO version:** 7.0.9
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 15.11.0
 - **NPM version:** 7.6.0
 - **Browser name and version:** Chrome 89.0
 - **Platform name and version:** Alpine 3.13
 - **Additional wdio packages used (if applicable):**
   - @wdio/cli
   - @wdio/devtools-service
   - @wdio/local-runner
   - @wdio/mocha-framework
   - @wdio/sync

**Config of WebdriverIO**
```js
exports.config = {
  runner: "local",
  path: "/wd/hub",
  maxInstances: 10,
  maxInstancesPerCapability: 10,
  logLevel: "info",
  logLevels: {
    webdriver: "info",
    "@wdio/applitools-service": "info",
  },
  bail: 1,
  baseUrl: "http://localhost",
  waitforTimeout: 20000,
  filesToWatch: [],
  connectionRetryTimeout: 15000,
  connectionRetryCount: 0,
  framework: "mocha",
  reporters: ["spec"],
  services: [
    "devtools",
  ],
  mochaOpts: {
    ui: "bdd",
    timeout: 60000,
    bail: true,
  },
};
```

**Describe the bug**
I cannot make WebdriverIO communicate effectively with a remote Chrome DevTools instance, despite configuring all the settings and services required (to my knowledge).

**To Reproduce**
I have prepared a repository that demonstrates the issue as precisely as possible :
https://github.com/nicolasbouffard/wdio-selenoid-devtools

**Expected behavior**
I expect to be able to run a remote Chrome browser and have a local WebdriverIO instance communicate with it.

**Log**
[WebdriverIO logs](https://gist.github.com/nicolasbouffard/7069f7ad995b0f43a2af68202085b509)

**Comment by christian-bromann** [comment]
I believe this is related to the work happening in #6508 which will be merged soon. Thanks for raising the issue.

**Comment by AlexGrs** [comment]
Hi @christian-bromann !

I was wondering if the cdp endpoint in this MR could bdecaled with "dynamic" infos like the current id ie something like:

```
            capabilities: {
                'se:options': {
                    'cdp': 'http://my.grid:1234/session/{SESSION_ID}/se/cdp'
                }
            }
```

and SESSION_IP is automatically set by WDIO when running the test?
