### ISSUE TITLE
Unable to add type declarations for custom configuration properties in a typescript implementation

### ISSUE THREAD

**Issue by laraleedev** [webdriverio/webdriverio#6551]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.0.9
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 14.15.5
 - **NPM version:** 6.14.11
 - **Browser name and version:** Chrome 89.0.4389.72
 - **Platform name and version:** macOS Catalina 10.15.7

**Config of WebdriverIO**
wdio.conf.js
```
const drivers = {
    chrome: { version: "89.0.4389.23" }, // https://chromedriver.chromium.org/
    firefox: { version: "0.29.0" }, // https://github.com/mozilla/geckodriver/releases
    chromiumedge: { version: "90.0.814.0" } // https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/
  };

exports.config = {
    runner: "local",
    specs: ["./src/test/specs/**/*.ts"],
    suites: {
      chkSmoke: [
        "./src/test/specs/checkout/smoke_nonprod.spec.ts",
        "./src/test/specs/checkout/smoke_prod.spec.ts"
      ]
    },
    exclude: [],
    capabilities: [
        {
          browserName: "chrome",
          maxInstances: 3,
          "goog:chromeOptions": {
            args: ["--user-agent=CompanyNameTestAutomation"]
          }
        }
      ]
    logLevel: "debug", // Level of logging verbosity: trace | debug | info | warn | error
    outputDir: "./logs",
    netlifyAuthToken: process.env.NETLIFY_AUTH_TOKEN
      ? process.env.NETLIFY_AUTH_TOKEN
      : "",
    deprecationWarnings: true,
    bail: 0,
    specFileRetries: process.env.specFileRetries || 0,
    baseUrl: process.env.BASEURL
      ? process.env.BASEURL
      : "https://stage.companyName.com",
    waitforTimeout: 30000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 6,
    services: [
      [
        "selenium-standalone",
        {
          installArgs: { drivers },
          args: { drivers }
        }
      ]
    ],
    framework: "jasmine",
    reporters: [
      "spec",
      ["allure", { outputDir: "logs/allure" }],
      ["junit", { outputDir: "logs/junit" }]
    ],
    jasmineOpts: {
      defaultTimeoutInterval: 10000,
      expectationResultHandler() {}
    },
    foobar: {
        loginName: process.env.LOGINNAME,
        skuNumbers: process.env.SKUNUMBERS,
        skuQuantities: process.env.SKUQUANTITIES
    }
    afterTest(test, context, result) {
      if (!result.passed) {
        browser.takeScreenshot();
      }
    }
  };
```

tsconfig.json (7.0.9)
```
{
    "compilerOptions": {
        "target": "ES2020",
        "module": "commonjs",
        "moduleResolution": "node",
        "esModuleInterop": true,
        "baseUrl": "./",
        "paths": {
            "*": [ "./*" ]
        },
        "types": ["node", "webdriverio/sync", "@wdio/jasmine-framework", "@wdio/types", "./types/wdio"]
    },
    "include": [
        "src/**/*.ts"
    ],
    "exclude": []
  }

```

wdio.d.ts (6.10.5)
```
declare namespace WebdriverIO {
  interface Foobar {
    loginName?: string;
    skuNumbers?: string;
    skuQuantities?: string;
    // etc
  }

  interface Config {
    foobar?: Foobar;
  }
}
```

wdio.d.ts (7.0.9)
```
declare global {
  namespace WebdriverIO {
    interface Foobar {
      loginName?: string;
      skuNumbers?: string;
      skuQuantities?: string;
      // etc
    }

    interface Config {
      foobar?: Foobar;
    }
  }
}

export {};
```

**Describe the bug**
https://webdriver.io/docs/browserobject/#custom-configurations
Custom configurations were accessible from our spec files in our previous v6.10.5 implementation:

foobar.spec.ts (6.10.5)
```
const { loginName } = browser.config.foobar; // No error
```

On upgrading to version 7.0.9, there doesn't seem to be a way to utilize the documented custom configurations in typescript. References to this functionality is still present in documentation, such as webdriverio/build/types.d.ts:102 
```
    /**
     * Given WebdriverIO options (including custom configurations)
     */
    config: Options.WebdriverIO | Options.Testrunner;
```

And Config is still an interface we can extend within global.webdriverio namespace as per @wdio/types/build/index.d.ts:35

However on adding our custom configuration prop as above, it still errors when trying to access it from a spec:

foobar.spec.ts (7.0.9)
```
const { loginName } = browser.config.foobar; // Property 'foobar' does not exist on type 'WebdriverIO | Testrunner'.  Property 'foobar' does not exist on type 'WebdriverIO'.ts(2339)
```

We also described the problem in the wdio gitter and got confirmation that there doesn't seem to be a way to add types for custom configurations atm:
https://gitter.im/webdriverio/webdriverio?at=6040aa0dd1aee44e2dc2e5a9

Unfortunately I don't have a solution for this myself given my current typescript ability. Several attempts at extending Options.WebdriverIO/Options.Testrunner were fruitless. 

**To Reproduce**
1) Setup a default wdio repository
2) Add any custom property to wdio.conf.js
3) Add a custom definitions file that adds your custom props to within the global.WebdriverIO namespace to the Config interface, as shown above
4) Add the custom definitions file to `types` within tsconfig.json
5) Try to access your custom configuration property from any spec file

**Expected behavior**
There should be a valid way to extend wdio type definitions and allow custom configuration properties to be access without error in a project using wdio and typescript.

**Comment by RafalSkorka** [comment]
I also had this problem and was able to fix it with this in wdio.d.ts

```
declare global {
    namespace WebdriverIO {
        interface Browser {
            config: WebdriverIO.Config
        }
    }
}
```

**Comment by christian-bromann** [comment]
@laraleedev can you try @RafalSkorka solution?

**Comment by laraleedev** [comment]
This works! Thank you for the solution @RafalSkorka
