### ISSUE TITLE
Unable to use `networkConnectionEnabled: true` in WDIO 7

### ISSUE THREAD

**Issue by flunderpero** [webdriverio/webdriverio#6556]
I guess the checking for W3C compatible capabilities is too strict or custom capabilities have to be configured in another way, but the docs don't mention that.

I faced a similar problem with the browserstack-service (but I did not track it down, it might be a different problem. I just reverted the service to 6.x.x which works).

**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.1.0
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]

**Config of WebdriverIO**
This happens with "chromedriver" services as well as with the standard service.

```
export const config: WebdriverIO.Config = {
    runner: "local",
    specs: ["__specs__/*.spec.js"],
    specFileRetries: 0,
    capabilities: [
        {
            browserName: "chrome",
            "goog:chromeOptions": {
                args: chrome_args,
                mobileEmulation: {deviceName: "Pixel 2 XL"},
            },
            networkConnectionEnabled: true,
        } as Capabilities,
    ],
    port: 9515,
    path: "/",
    services: [
        [
            "chromedriver",
            {
                logFileName: "/tmp/chromedriver.log",
                port: 9515,
            },
        ],
    ],
}
```

**Describe the bug**
I get the following error:
```
Error: Invalid or unsupported WebDriver capabilities found ("networkConnectionEnabled"). Ensure to only use valid W3C WebDriver capabilities (see https://w3c.github.io/webdriver/#capabilities).
    at Object.startWebDriverSession (/Users/pero/src/pero/cling-main/node_modules/webdriver/build/utils.js:38:19)
    at Function.newSession (/Users/pero/src/pero/cling-main/node_modules/webdriver/build/index.js:56:59)
    at Object.exports.remote (/Users/pero/src/pero/cling-main/node_modules/webdriverio/build/index.js:56:43)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Runner._startSession (/Users/pero/src/pero/cling-main/node_modules/@wdio/runner/build/index.js:202:56)
    at Runner._initSession (/Users/pero/src/pero/cling-main/node_modules/@wdio/runner/build/index.js:164:25)
    at Runner.run (/Users/pero/src/pero/cling-main/node_modules/@wdio/runner/build/index.js:87:19)
```

**Comment by christian-bromann** [comment]
As `networkConnectionEnabled` is not a valid W3C WebDriver capability your session request fails. You can set custom capabilities by using vendor keys, e.g.:

```js
    capabilities: [
        {
            browserName: "chrome",
            "goog:chromeOptions": {
                args: chrome_args,
                mobileEmulation: {deviceName: "Pixel 2 XL"},
            },
            "custom:networkConnectionEnabled": true,
        } as Capabilities,
    ],
```

**Comment by flunderpero** [comment]
I would have guessed something like this. I think the docs need some updates, see https://webdriver.io/docs/api/chromium/#setnetworkconnection

**Comment by flunderpero** [comment]
@christian-bromann Are you sure that this actually works? Which vendor prefix would I have to use for "networkConnectionEnabled"? BTW: If I comment out the check in utils.ts, it works fine as is, i.e. "networkConnectionEnabled" is used by the service "chromedriver" and I can call `browser.setNetworkConnection()`.

**Comment by christian-bromann** [comment]
@flunderpero thanks for pointing this out. It doesn't seem that `networkConnectionEnabled` is a capability that a user can set for the remote session. It is returned however for sessions where this command is available (e.g. Chrome based sessions). Updated the docs.

**Comment by flunderpero** [comment]
@christian-bromann You *need* to set this capability or otherwise `browser.setNetworkConnection()` won't work but throw an error.

**Comment by christian-bromann** [comment]
Ah, really? I was looking for `networkConnectionEnabled` in the Chromedriver docs but couldn't find it anywhere. Do you have a link to any kind of documentation around it?

**Comment by flunderpero** [comment]
I looked at the [source-code](https://chromium.googlesource.com/chromium/src/+/master/chrome/test/chromedriver/capabilities.cc) and you are right: The capability `networkConnectionEnabled` is set/returned by the ChromeDriver. But when I run my tests with mobile emulation (which is required for manipulating the network) I get this error:
```
unknown error: network connection must be enabled
  (Session info: chrome=89.0.4389.82)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

If I explicitly set `networkConnectionEnabled` on the capabilities the test runs fine (if I comment out the check in `webdriver/utils.ts`). These are the capabilities:
```
    capabilities: [
        {
            browserName: "chrome",
            "goog:chromeOptions": {
                args: chrome_args,
                mobileEmulation: {deviceName: "Pixel 2 XL"},
            },
            networkConnectionEnabled: true
        } as Capabilities,
    ]
```

I don't know whether this is a bug in ChromeDriver but I have to set "networkConnectionEnabled" in order for test manipulating the network to work.

**Comment by christian-bromann** [comment]
What happens if you move it into chrome options, e.g.:
```
    capabilities: [
        {
            browserName: "chrome",
            "goog:chromeOptions": {
                args: chrome_args,
                mobileEmulation: {deviceName: "Pixel 2 XL"},
            }
        } as Capabilities,
    ]
```

**Comment by flunderpero** [comment]
I already tried that at the very start. It fails with this error:
```
[0-0] 2021-03-07T23:53:28.587Z ERROR webdriver: invalid argument: invalid argument: cannot parse capability: goog:chromeOptions
from invalid argument: unrecognized chrome option: networkConnectionEnabled
    at Object.getErrorFromResponseBody (/Users/pero/src/pero/cling-main/node_modules/webdriver/build/utils.js:189:12)
    at WebDriverRequest._request (/Users/pero/src/pero/cling-main/node_modules/webdriver/build/request.js:168:31)
```

**Comment by christian-bromann** [comment]
My suggestion here is to bring this up in the Chromedriver project. It doesn't seem to be an official support capability but still it has some functionality. In the meantime you should be able to use [the `throttle`](https://webdriver.io/docs/api/browser/throttle/) command to achieve the same.
