### ISSUE TITLE
Link to boilerplates in WebdriverIO Examples document redirects to a 404 page

### ISSUE THREAD

**Issue by raditotev** [webdriverio/webdriverio#6571]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [x] A typo
- [ ] Missing documentation
- [ ] Other

**Description of the improvement / report**
In [WebdriverIO Examples document](https://github.com/webdriverio/webdriverio/tree/main/examples#webdriverio-examples) a  typo in the link to WDIO boilerplates redirects users to a 404 page:
```
404 Not Found
Code: NoSuchKey
Message: The specified key does not exist.
Key: docs/boilerplate.html
RequestId: ****
HostId: *****
```
Updating the link will redirect users to the correct page:
```diff
- [boilerplates](http://www.webdriver.io/docs/boilerplate.html)
+ [boilerplates](http://www.webdriver.io/docs/boilerplates.html)
```

**Comment by christian-bromann** [comment]
Thanks for letting us know!
