### ISSUE TITLE
Detect session env works incorrectly on call remote method

### ISSUE THREAD

**Issue by DudaGod** [webdriverio/webdriverio#6575]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.1.0
 - **Mode:** Standalone mode
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 12.18.1
 - **NPM version:** 6.14.5

**Describe the bug**
When calling `remote` method with capabilities for chrome emulator [wdio determines](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-utils/src/envDetector.ts#L175) that it supports w3c protocol, but it doesn't and I can't control this behaviour.

Example:
```
const {remote} = require('webdriverio')

let client;

const opts = {
    protocol: 'http',
    hostname: 'localhost',
    port: 4444,
    path: '/wd/hub',
    automationProtocol: 'webdriver',

    capabilities: {
        platformName: 'Android',
        deviceName: 'android',
        version: '67.0',
        browserName: 'chrome'
    }
};

(async function () {
    client = await remote(opts);

    await client.url('https://github.com');
    await client.setTimeout({pageLoad: 5000}); // throw error - `unknown error: 'ms' must be a double`

    await client.deleteSession();
})()
    .catch(async (e) => {
        console.error(e.stack)
        await client.deleteSession()
    });
```

After run it I get an error:
```
2021-03-10T07:30:00.322Z ERROR webdriver: Request failed with status 200 due to Error: unknown error: 'ms' must be a double
  (Session info: chrome=67.0.3396.81)
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.9.151-35 x86_64)
Error: unknown error: 'ms' must be a double
  (Session info: chrome=67.0.3396.81)
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.9.151-35 x86_64)
    at Object.getErrorFromResponseBody (/Users/dudkevich/job/projects/dudkevich-scripts/FEI-20461.wdio_6/node_modules/webdriver/build/utils.js:189:12)
    at WebDriverRequest._request (/Users/dudkevich/job/projects/dudkevich-scripts/FEI-20461.wdio_6/node_modules/webdriver/build/request.js:168:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Browser.wrapCommandFn (/Users/dudkevich/job/projects/dudkevich-scripts/FEI-20461.wdio_6/node_modules/@wdio/utils/build/shim.js:79:29)
    at async Browser.wrapCommandFn (/Users/dudkevich/job/projects/dudkevich-scripts/FEI-20461.wdio_6/node_modules/@wdio/utils/build/shim.js:79:29)
    at async /Users/dudkevich/job/projects/dudkevich-scripts/FEI-20461.wdio_6/setTimeout.js:54:5
```

I can fix it with `attach` and explicitly specify then `isW3C` needs to be disabled:
```
const {remote, attach} = require('webdriverio')

let client, client2;

const opts = {
    protocol: 'http',
    hostname: 'localhost',
    port: 4444,
    path: '/wd/hub',
    automationProtocol: 'webdriver',

    capabilities: {
        platformName: 'Android',
        deviceName: 'android',
        version: 'phone-67.0',
        browserName: 'chrome'
    }
};

(async function () {
    client = await remote(opts);
    client2 = attach({sessionId: client.sessionId, ...opts, isW3C: false});

    await client2.url('https://github.com');
    await client2.setTimeout({pageLoad: 5000});

    await client.deleteSession();
})()
    .catch(async (e) => {
        console.error(e.stack)
        await client.deleteSession()
    });
```

To my mind in method `remote` should be ability to pass session environments flags to overwrite flags that detected flags by capabilities.

**Comment by christian-bromann** [comment]
Can you share what your WebDriver endpoint returns when requesting the session? WebdriverIO looks into there [to determine](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-utils/src/envDetector.ts#L9-L44) whether it is a W3C session or JSONWP one. If your WebDriver endpoint mixes both of them, then errors like these happen.

**Comment by DudaGod** [comment]
When requesting session I get these capabilities:
```
capabilities: {
  androidNaturalOrientation: true,
  browserName: 'chrome',
  databaseEnabled: false,
  desired: {
    androidNaturalOrientation: true,
    browserName: 'chrome',
    deviceName: 'android',
    noReset: true,
    platformName: 'Android',
    udid: 'emulator-5554',
    version: 'phone-67.0'
  },
  deviceManufacturer: 'unknown',
  deviceModel: 'Android SDK built for x86',
  deviceName: 'emulator-5554',
  deviceScreenSize: '720x1280',
  deviceUDID: 'emulator-5554',
  javascriptEnabled: true,
  locationContextEnabled: false,
  networkConnectionEnabled: true,
  noReset: true,
  platform: 'LINUX',
  platformName: 'Android',
  platformVersion: '6.0',
  takesScreenshot: true,
  udid: 'emulator-5554',
  version: 'phone-67.0',
  warnings: {},
  webStorageEnabled: false
}
```

> If your WebDriver endpoint mixes both of them, then errors like these happen.

How can I figure it out? In chrome emulator I use appium@1.8.1.

I reproduce the problem with `isMobile: true` session flag. The problem is here - https://github.com/webdriverio/webdriverio/blob/main/packages/webdriver/src/utils.ts#L173. Command `setTimeouts` present in w3c protocol - https://webdriver.io/docs/api/webdriver#settimeouts and in jsonwire protocol - https://webdriver.io/docs/api/jsonwp#settimeouts. 

And when I call `setTimeout({pageLoad: 5000})` with `isW3C: false` then it try call jsonwire protocol under the hood - https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/browser/setTimeout.ts#L61, but it calls method from w3c protocol - https://github.com/webdriverio/webdriverio/blob/main/packages/devtools/src/commands/setTimeouts.ts#L13. And I get error like this:
```
Error: Malformed type for "implicit" parameter of command setTimeouts
Expected: number
Actual: string

For more info see https://w3c.github.io/webdriver/#dfn-set-timeouts

    at Browser.protocolCommand (/Users/dudkevich/job/projects/dudkevich-scripts/FEI-20461.wdio_6/node_modules/webdriver/build/command.js:54:23)
    at Browser.setTimeout (/Users/dudkevich/job/projects/dudkevich-scripts/FEI-20461.wdio_6/node_modules/webdriverio/build/commands/browser/setTimeout.js:61:35)
    at /Users/dudkevich/job/projects/dudkevich-scripts/FEI-20461.wdio_6/setTimeout.js:113:19
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

If I change order of apply protocols here - https://github.com/webdriverio/webdriverio/blob/main/packages/webdriver/src/utils.ts#L173 to `JsonWProtocol, WebDriverProtocol` then everything works correct.

**Comment by DudaGod** [comment]
cc @christian-bromann can you look at this problem, please?

**Comment by christian-bromann** [comment]
This is rather an issue in Appium as it should understand the W3C flavor for that command. Can you try with the latest Appium version? Again JSONWireProtocol is deprecated and Appium has updated their commands to support W3C.

**Comment by DudaGod** [comment]
> This is rather an issue in Appium as it should understand the W3C flavor for that command. Can you try with the latest Appium version? Again JSONWireProtocol is deprecated and Appium has updated their commands to support W3C.

You was right. With appium@1.9.0 this problem is not reproduced anymore.
Thank you.
