### ISSUE TITLE
isClickable not usable to validate scroll position - add an option to prevent it from scrolling or a new function

### ISSUE THREAD

**Issue by constantine-photoshelter** [webdriverio/webdriverio#6579]
Summary: I am writing a test that adds an element to a scrollable list and validates that the addition does not change which elements are displayed in the list. isClickable is not suitable since it will scroll to an element if not visible. isDisplayedInViewport is not suitable because it can return true for elements not visible on the page.

**Is your feature request related to a problem? Please describe.**
I was working on writing automation scrolled to the middle of a scrollable list and adds an element either above or below the current view. The goal of the test was to validate that all elements visible before adding an element were also visible after adding an element. Because the size of the scrolable list is smaller than the window, [isDisplayedInViewport was returning True for some elements not displayed](https://github.com/webdriverio/webdriverio/issues/4646). isClickable was not a suitable alternative because [it will scroll to the element if possible](https://github.com/webdriverio/webdriverio/pull/4656).

**Describe the solution you'd like**
I would like a way to call isClickable() or a new function that will tell me if an element is clickable without attempting to scroll to that element.

**Describe alternatives you've considered**
The only alternative I can think of is to to use getLocation() to create an array with the relative height of all elements on the page and validate that values before match values after, but this is error prone. The way the list is stored, all elements shown on the page are shown and only a few elements above or below the displayed elements are loaded. Creating a new element may result in removing a non-visible element and replacing it with the newly created element but not change the scroll position. If I allow for elements to be removed from the list while performing a validation, it becomes far more difficult to validate that all visible elements before adding to the list are still displayed.

**Comment by christian-bromann** [comment]
> I would like a way to call isClickable() or a new function that will tell me if an element is clickable without attempting to scroll to that element.

This all seems like a pretty custom scenario. I am not sure what a scrollable list is based on your description, it can be many things. It seems it makes most sense for you to work with the `execute` command and determine the visibility of list elements via JavaScript.

I am sorry but I neither see a bug in your report nor a feature request that makes sense to add given the very custom scenario. Happy to continue the conversation and support.

**Comment by constantine-photoshelter** [comment]
@christian-bromann By scrollable list, I mean any section within a window that can scroll. For example: In the center pane in gmail, when checking email. If I scroll a little, the element for the top email is still considered true for isDisplayedInViewport() and isClickable() will scroll to the element making it difficult to validate that the same or different emails are shown in the scroll position after an email comes in. A little different, but something similar can be created on [this page](https://github.com/webdriverio/webdriverio/issues/6579). If I scroll down, a header pops up that covers the top portion of the screen `.js-sticky`. If I scroll down such that `.js-sticky` covers `form[aria-label=“Select assignees”]` (the right pane element that shows the individual assigned to the ticket) while it is still within the viewport and I want to verify if `form[aria-label=“Select assignees”]` is no longer visible on the page, I cannot, because isDisplayedInViewport() will return true, since the element is displayed and exists within the viewport and isClickable() will scroll it and return true as well. In this scenario, lets say I wanted to validate that `.js-sticky` is visible and that after scrolling to a specific position on the page, `form[aria-label=“Select assignees”]` isDisplayedInViewport() but is not visible as a way to verify that `.js-sticky` is covering it. Is there another way that you would suggest  might be usable in that scenario were I want to be able to confirm that an element that can be scrolled to and does exist within the page is covered by another element?

**Comment by constantine-photoshelter** [comment]
Also, for reference, the list I was referring to my my initial post was the polymer component [iron-list ](https://www.webcomponents.org/element/@polymer/iron-list) As you scroll down, it reuses the list elements and changes the order as you scroll. So, for example, you may have 15 elements on the list with 5 displayed; as you scroll, elements out of view are reassigned to other elements in the direction you are scrolling and moved to a different position in the list.
