### ISSUE TITLE
Can not be integrated with a type-script project. browser.cdp is not a function    

### ISSUE THREAD

**Issue by poc7667** [webdriverio/webdriverio#6592]
**Pre-check**
- [x ] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [x ] Unclear documentation

**Description of the improvement / report**
A clear and concise description.
```
{
  ...
  "devDependencies": {
    ...
    "chromedriver": "89.0.0",
    "node-fetch": "^2.6.1",
    "ts-node": "^9.0.0",
    "tsconfig-paths": "3.9.0",
    "typescript": "^3.8.3",
    "wdio-chromedriver-service": "6.0.4"
  },
  "dependencies": {
    "@wdio/devtools-service": "^6.3.7",
    "@wdio/types": "^7.1.1",
    "wdio-intercept-service": "^4.1.3"
  }
}
```
# Sample.ts

    it('Capturing network logs', () => {

        /**
         * enable necessary domains
         */
        // @ts-ignore
        browser.cdp('Profiler', 'enable')
        // @ts-ignore
        browser.cdp('Debugger', 'enable')
    });

# results

browser.cdp is not a function

**Comment by jamesmortensen** [comment]
Do you have devtools listed in your wdio.conf.js services array?

**Comment by christian-bromann** [comment]
Please add `@wdio/devtools-service` to your types list as mentioned here: https://webdriver.io/docs/typescript#services. Please let us know if there are more questions.
