### ISSUE TITLE
Feedback from first time contributor to WebdriverIO

### ISSUE THREAD

**Issue by RossVertizan** [webdriverio/webdriverio#6595]
**Pre-check**
- [X] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) and submit a pull request

Please don't take any of this as criticism, clearly there is a lot of hard work and effort in webdriverio and I contribute these comments with the hope of improving the tool.

**Describe the improvement**
In #6548 I was asked if there was anything missing from [https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md ](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md ) and I was asked to file my response as a separate issue.  This is that response.

First, I understand that contributors need to read the CONTRIBUTING document, and I thought I had, but it is only in writing this that I realise that what I read was [https://webdriver.io/docs/contribute/](https://webdriver.io/docs/contribute/), which is different to the one I should have read.  However, I quickly followed the link to [Set Up Project](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#set-up-project) and followed from there.  Does there need to be a contribute page and a contributing page?

Setting up the project went fine until it came to running the tests and the tests failed, even as a write this ```npm run test``` fails on an up-to-date version of the main webdriverio repo ( I get ```Depcheck failed: undefined```).  So what should I do in that case?  I spent a long time trying to figure out what I had done wrong and trying to dig into the problem.

Working on the code was fine, I used the ```npm link``` feature to link in the wdio-config package and everything worked well and I was able to proceed easily working in an environment I was familiar with.  I used the ```npm run watch``` command and that also worked well and has for everything that I have done.  I then moved over to work on the wdio-cli package and when I tried to link that I got an error:
```
Error: Couldn't initialise "@wdio/local-runner".
Error: Cannot find module 'loglevel'
Require stack:
- H:\git\webdriverio_6469\packages\wdio-logger\build\node.js
- H:\git\webdriverio_6469\packages\wdio-local-runner\build\index.js
- H:\git\webdriverio_6469\packages\wdio-cli\node_modules\@wdio\utils\build\utils.js
- H:\git\webdriverio_6469\packages\wdio-cli\node_modules\@wdio\utils\build\initialisePlugin.js
- H:\git\webdriverio_6469\packages\wdio-cli\node_modules\@wdio\utils\build\index.js
- H:\git\webdriverio_6469\packages\wdio-cli\build\launcher.js
- H:\git\webdriverio_6469\packages\wdio-cli\build\index.js
- H:\git\webdriverio_6469\packages\wdio-cli\bin\wdio.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (H:\git\webdriverio_6469\packages\wdio-logger\src\node.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at Object.safeRequire (H:\git\webdriverio_6469\packages\wdio-cli\node_modules\@wdio\utils\build\utils.js:183:15)
    at Object.initialisePlugin (H:\git\webdriverio_6469\packages\wdio-cli\node_modules\@wdio\utils\build\initialisePlugin.js:30:34)
    at new Launcher (H:\git\webdriverio_6469\packages\wdio-cli\src\launcher.ts:102:25)
    at launch (H:\git\webdriverio_6469\packages\wdio-cli\src\commands\run.ts:128:22)
    at Object.handler (H:\git\webdriverio_6469\packages\wdio-cli\src\commands\run.ts:171:16)
    at Object.exports.run (H:\git\webdriverio_6469\packages\wdio-cli\src\index.ts:65:16)
    at Object.<anonymous> (H:\git\webdriverio_6469\packages\wdio-cli\bin\wdio.js:11:21)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
```
when I then did an ```npm unlink```, it didn't go back to the pre-linking state and I was unable to fix the environment I was working in.  Eventually, I filed on Gitter and @christian-bromann suggested that I used the examples.  It wasn't clear to me how I should run the examples, so I used the command:
```node ..\..\..\packages\wdio-cli\bin\wdio.js```
in the examples/wdio/mocha directory.  That ran and I was able to proceed.  When I came to the examples in the jasmine, cucumber and multiremote directories these did not run and the problem was a timeout waiting to connect to the server.  I did an npm install of chromedriver and wdio-chromedriver-service and added chromedriver as a service.  I see back on the [contribute page](https://webdriver.io/docs/contribute/), under "Work With The Code", that it mentions that the contributor needs to take care of running up a server and also mentions the WebDriver Mock Service, but there is no further information about how one would use that service.

As a first time working in a TypeScript environment I struggled with how to define the typing and the syntax that is introduced.  A link to some good tutorials or resources would be helpful.

Finally, I got to a point where I could go no further and submitted my pull request and swiftly got comments from @erwinheitzman, which I implemented.  I still had some coding issues and many thanks to @christian-bromann for taking a one on one meeting to help me through those issues.

I have now updated the documentation, I only needed to add a paragraph, but that needed to be inserted in multiple places.  It would be useful to note things like that in the contributing guide.

So, finally, I got to the testing and I am baffled by the structure.  There are a number of problems with the testing:

1. Looking at the structure of the smoke tests, I don't really understand how they worked.  It would be good to have a few words of explanation.  I managed to create some smoke tests by modifying an existing test for my purposes.
2. For the wdio-cli tests I have filed a separate issue #6593.

**Description of the improvement / report**
So, to try and summarise this ramble, I would suggest the following specific changes:

1. Combine the contribute page and the contributing page to have one location
2. Provide some details on what to do if the tests ```npm run test``` do not pass after a clean install and setup
3. Emphasise using the examples over ```npm link``` and provide instructions for how the examples should be run, especially for the setup of a browser driver and/or some instructions on how to use the WebDriver Mock Service.
4. (Maybe) Checkout why the ```npm link``` does not appear to work for the wdio-cli package.  Note that the ```npm unlink``` might give undesirable results and warn users about this or provide notes on how to avoid this issue.
5. Links to some decent Typescript resources
5. For the documentation, are there any writing style guides? Note that in some cases the same data may be in multiple places e.g. in examples files.
6. A primer on the structure of the smoke tests
7. A primer on the mocking used in the Jest tests and general structure, subject to the outcome of #6593
8. A walk through of the pull request process.  Do I resolve conversations when the issue has been fixed or does the reviewer?

I hope this helps, and as I say, please don't take this as criticism, I just want to make it even better.

**Comment by christian-bromann** [comment]
Address comments in #6598
