### ISSUE TITLE
'before all hook' failure

### ISSUE THREAD

**Issue by RCrawford2057** [webdriverio/webdriverio#66]
After upgrading from 0.6.9 to 0.7.8 I have started getting this error when running previously passing tests :

  Test Examples
    1) "before all" hook

  ✖ 1 of 9 tests failed:

  1) Test Examples "before all" hook:
     Error: timeout of 2000ms exceeded
      at Object.<anonymous> (/Users/ryan.crawford/Documents/Test Prototype 3/node-selenium-phantomjs-example/node_modules/mocha/lib/runnable.js:167:14)
      at Timer.list.ontimeout (timers.js:101:19)

This is the test I was trying to run:

<code>
describe('Test Examples', function(){
    before(function(done) {
        client.init().url('http://localhost:3000/', done);
    });

```
describe('Check the homepage', function(){

    it('should see correct title', function(done) {
        client.getTitle(function(title){
            expect(title).to.have.string('Test');
            done();
        });
    });
```

<code>

**Comment by ankurkaushal** [comment]
I just stumbled upon while I was having the same error, the trick is to set timeout to 0. That way mocha disables the timeout.

Ref: https://github.com/mochajs/mocha/commit/35da58bdd551ec0a0cdb3eacb884a83d141aca63
