### ISSUE TITLE
Error in "node_modules/webdriverio/build/commands/browser/executeAsync.d.ts:44:171"  while building  -> "error TS1005: ',' expected"

### ISSUE THREAD

**Issue by sehgasau** [webdriverio/webdriverio#6603]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.2.1
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 12.18.1
 - **NPM version:** 6.14.5
 - **Browser name and version:** Chrome 86
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
generic config in typescript 

**Describe the bug**
When compiling the typescript file, i get this error: "node_modules/webdriverio/build/commands/browser/executeAsync.d.ts:44:171 error TS1005: ',' expected"

**To Reproduce**

**Expected behavior**
Compile the typescript file successfully 

**Log**

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
Which TypeScript version are you using? Note that WebdriverIO v7 requires TypeScript v4.1

**Comment by sehgasau** [comment]
Oh i see, yeah ts version on my machine is 3.8. Thanks for the info, will update and try again

**Comment by christian-bromann** [comment]
Any updates?

**Comment by sehgasau** [comment]
Sorry, I literally forgot to reply to this issue, so I downgraded my wdio version to < v7 stable release and it worked after that. Thank you for the support :)
