### ISSUE TITLE
Stale element reference Error

### ISSUE THREAD

**Issue by tnguyen14** [webdriverio/webdriverio#662]
A suite of UI tests were running fine and passing for us, until a couple days ago when it started to fail with the following error:

` Error: stale element reference: element is not attached to the page document
      at endReadableNT (_stream_readable.js:891:12)`

I am at a loss as to how to debug this. Sometimes even just putting a random pause of 2-3s might make it work.

Another sort of failures that are appearing is when clicking a button or link that links to another page (like submitting a form). The action that happens after the `click` action often fails because the new page context has not been set up yet. And that seems to be related/similar to the issue above.

**Comment by christian-bromann** [comment]
> Error: stale element reference: element is not attached to the page document

The reason for that is that an element you queried before was removed from the DOM. I can't really tell where the problem is without having a reproducible example.

**Comment by tnguyen14** [comment]
I have narrowed down the test case where clicking on a link to get a page refresh to the following gist 
https://gist.github.com/tnguyen14/c1bb49f162fda54f790d

When I run the test `mocha carousel.js --timeout 10000`, I inconsistently get about 2 different failures every time. 

I think this is similar to how the `stale element reference` error occurs as well.

**Comment by christian-bromann** [comment]
ref #748

**Comment by christian-bromann** [comment]
Closed due
