### ISSUE TITLE
ERROR @wdio/runner: Error: Cannot find module 'cypress/types/bluebird'

### ISSUE THREAD

**Issue by thuquynhpham** [webdriverio/webdriverio#6620]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** "@wdio/cli": "^5.16.10"
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:**  v14.16.0
 - **NPM version:** 6.14.11
 - **Browser name and version:**  Appium 1.20.2
 - **Platform name and version:** [e.g. Windows 10] Android  version 10
 - **Additional wdio packages used (if applicable):**"@wdio/local-runner": "^5.16.10", "@wdio/mocha-framework": "^5.16.10", "@wdio/selenium-standalone-service": "^5.16.10", "@wdio/spec-reporter": "^5.16.5", "@wdio/sync": "^5.16.10", "chai": "^4.2.0", "@wdio/cli": "^5.16.10"

**Config of WebdriverIO**
wdio.android.conf.js

let { join } = require('path');
exports.config = {
    runner: 'local',
    port: 4723,
    specs: [
        './test/specs/**/*.js'
    ],
    exclude: [
    ],
    maxInstances: 10,
    capabilities: [{
        platformName: 'Android',
        'appium:deviceName': 'Pixel 2',
        'appium:app': join(process.cwd(), './app-stage-debug.apk')
    }],
    logLevel: 'info',
    bail: 0,
    baseUrl: 'http://localhost',
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    services: ['chromedriver'],
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },
}

**Describe the bug**
the test run normally, then it suddenly throw ERROR @wdio/runner: Error: Cannot find module 'cypress/types/bluebird'

**To Reproduce**
By running  `./node_modules/.bin/wdio wdio.android.conf.js`

sample.test.js
`describe('Sample', ()=>{
    beforeEach(() => {
    });

    it('Test', ()=>{
        
    })
})`

**Expected behavior**

**Log**
/Users/thuquynhpham/Documents/planday-test-automation-nightwatch/node_modules/@wdio/local-runner/build/run.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/thuquynhpham/Documents/planday-test-automation-nightwatch/mobile/pageObjects/Login.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
[0-0]  Error:  Cannot find module 'cypress/types/bluebird'

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
Sorry but WebdriverIO doesn't use Cypress in any shape of form. You might import something that doesn't belong to the framework, e.g.: /Users/thuquynhpham/Documents/planday-test-automation-nightwatch/mobile/pageObjects/Login.js:1:16
