### ISSUE TITLE
Replace `markdox` with `jsdoc-to-markdown`

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#6640]
Markdox now introduces 4 severe bugs to the code base. They shouldn't impact the user given we generate our docs in CI but it is still something we should clean up. I suggest to switch to [jsdoc-to-markdown](https://www.npmjs.com/package/jsdoc-to-markdown).

**Comment by mathew-jithin** [comment]
@christian-bromann Shall I pick it up?

Also, anything specific I need to keep in mind?

**Comment by christian-bromann** [comment]
@mathew-jithin feel free to pick it up. The file to look into is here: https://github.com/webdriverio/webdriverio/blob/main/scripts/docs-generation/wdioDocs.js. The goal is to parse all `.ts` files within the command dir and generate markdown files which later will be parsed by Docusarus. Let me know if you have any questions.

**Comment by christian-bromann** [comment]
@mathew-jithin any updates? I will un-assign you, feel free to re-assign when you still want to tackle this. Cheers!

**Comment by abhishek-bodapati** [comment]
Hi, can I work on this?

**Comment by christian-bromann** [comment]
@abhishek-bodapati yes, absolutely!

**Comment by optimm** [comment]
hey @christian-bromann  if this issue is not yet solved can i take it , also a little guidance over this would be great, Thank you

**Comment by christian-bromann** [comment]
Thanks for taking a stab at this!

> also a little guidance over this would be great

Please have a look into our [contributing guidelines](https://webdriver.io/docs/contribute) and particular the part that goes into generating the how we generate the [documentation](https://webdriver.io/docs/contribute#documentation). Please let us know if you have any questions.

**Comment by boneskull** [comment]
Upon `npm install` in a working copy, I'm seeing:

```

The WebdriverIO team is aware of the following reported vulnerabilities.
These do not impact packages used by users.
Please help us to resolve the issue, see https://github.com/webdriverio/webdriverio/issues/6640
added 318 packages from 99 contributors, removed 480 packages, updated 318 packages and audited 1305 packages in 39.398s

112 packages are looking for funding
  run `npm fund` for details

found 9 vulnerabilities (1 low, 2 moderate, 4 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

No specific vulns are displayed. Using node@14 and npm@6 as per the `.nvmrc`.

**Comment by boneskull** [comment]
(though, if I had a suggestion: call out the _specific_ ignorable vulns in the message)

**Comment by christian-bromann** [comment]
> call out the _specific_ ignorable vulns in the message

done: https://github.com/webdriverio/webdriverio/commit/ffe6c48ee3ac36244113cf1ddbca6dc42b94a1c5

**Comment by christian-bromann** [comment]
Resolved by @tamil777selvan
