### ISSUE TITLE
Suite definition that supports the new syntax to group specs files

### ISSUE THREAD

**Issue by lacell75** [webdriverio/webdriverio#6642]
I would be very interested if the new feature (gouping specs for execution in a single instance) would be supported on Suite definition like : 
```
"suites": 
{
               setup:[
                  [
                      "./test/specs/setup/test_login.js",
                      "./test/specs/setup/test_product_order.js",
                      "./test/specs/setup/test_checkout.js"
                  ],
                  "./test/specs/setup/test_b*.js",
              ],
             login:[
                  [
                      "./test/specs/login/test_login.js",
                      "./test/specs/login/test_product_order.js",
                      "./test/specs/login/test_checkout.js"
                  ],
                  "./test/specs/login/test_b*.js",
              ],
}
```

**Comment by RossVertizan** [comment]
@christian-bromann: Yes, both of those statements are correct.  I explicitly excluded support for suites and no it shouldn't be a problem to implement.
Would this cause problems for the reporters?  I think it will be OK because my feeling is that the reporters are downstream of the "spec resolution".

**Comment by christian-bromann** [comment]
Yeah, I agree, it shouldn't be a big issue for reporters.

**Comment by RossVertizan** [comment]
I'm happy to take a look at this if you'd like

**Comment by christian-bromann** [comment]
Go for it!

**Comment by christian-bromann** [comment]
PR got merged and released, thanks @RossVertizan

**Comment by lacell75** [comment]
Thanks a lot!!
