### ISSUE TITLE
GitHub logo link is missing on the teams page

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#6644]
On the [Team](https://webdriver.io/community/team) page in our docs, every member is suppose to have a link to their GitHub and Twitter profile. For some reasons the GitHub logo link is missing:

![Screenshot 2021-03-31 at 19 45 03](https://user-images.githubusercontent.com/731337/113188135-f54ad980-9259-11eb-932c-ae483a4a4608.png)

The code for this React component can be found here: https://github.com/webdriverio/webdriverio/blob/main/website/src/theme/card.jsx. I believe it is just a CSS issue.

**Comment by arsen1c** [comment]
Hey, I went through the code an noticed there was no github icon svg in https://github.com/webdriverio/webdriverio/blob/main/website/src/theme/card.jsx file. So I went ahead and added a github svg in the `GithubLink` component and made small changes in the css file as well. This has fixed the issue. Now, can you please guide me further on which branch of my fork should I push the changes?

**Comment by arsen1c** [comment]
Here's how the Team page looks like after the fix:

![image](https://user-images.githubusercontent.com/46086050/113260893-6d61df80-92ec-11eb-84cb-e100cd85da9a.png)

**Comment by christian-bromann** [comment]
Thanks for tackling this! Let's continue convo in #6646
