### ISSUE TITLE
Can not mock error response with 422, 0 

### ISSUE THREAD

**Issue by poc7667** [webdriverio/webdriverio#6648]
The mock request just hangs forever if I tried to mock a failed response.
If mock doesn't provide a way to mimic error response. Any alternative?

```
            sampleMock = browser.mock('**/create',{
                method: 'post'
            })
            sampleMock.respond(null, {
                // 0, 422 will cause request hanging. 404 works. So odd~
                statusCode: 422
            });

```

**Environment (please complete the following information):**
   - wdio 6
  - chrome 86

**Comment by christian-bromann** [comment]
I believe this is the nature of a 422 response:

> The HyperText Transfer Protocol (HTTP) 422 Unprocessable Entity response status code indicates that the server understands the content type of the request entity, and the syntax of the request entity is correct, but it was unable to process the contained instructions.

I don't think this underlies any issue with WebdriverIO and is rather a result of how Chrome treats such requests. I advise to raise an issue in the Protractor project.
