### ISSUE TITLE
Documented customWorkerService constructor signature does not appear to match implementation

### ISSUE THREAD

**Issue by RossVertizan** [webdriverio/webdriverio#6651]
**Pre-check**
- [X] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [ ] Missing documentation
- [X] Other

In the documentation describing [custom services](https://github.com/webdriverio/webdriverio/blob/9d2220e89144b0ca69232737957ad5fc32ca1300/website/docs/CustomServices.md) the signature of the constructor is given as:
```javascript
constructor (serviceOptions, capabilities, config, browser) {
        this.browser = browser
    }
```
however, in trying to use this, I find that serviceOptions, capabilities, and config are indeed passed and are as expected.  However, "browser" is not passed and is "undefined", which is odd as specific mention is made to store an instance of the browser on the service.

Closer inspection of the code shows that in the file packages/wdio-utils/src/initialiseServices.ts  the new service is only created with the first three [options](https://github.com/webdriverio/webdriverio/blob/9d2220e89144b0ca69232737957ad5fc32ca1300/packages/wdio-utils/src/initialiseServices.ts#L172-L175)

```typescript
            const Service = (service as Services.ServicePlugin).default || service as Services.ServiceClass
            if (typeof Service === 'function') {
                return new Service(serviceConfig, caps, config)
            }
```
So, it would seem that there is a mismatch between the documentation and the implementation.

I have tried passing the browser object that is available as a fourth argument, but it does not help me achieve what I want to do, and that may be why it is not being passed.  It has no browser.call function for me to wrap async functions inside the service (or maybe more accurately plugin).  So I am unclear if the implementation is correct and documentation out of date or vice-versa, or maybe there is a third explanation?

**Description of the improvement/report**
This anomaly should be resolved either way.  Is there a value in having the browser passed to the service constructor?  Other services appear to get a browser passed in the "before" method and it also seems possible to take the browser off the global object, maybe a discussion of these different approaches would be useful.

I don't really want to wrap this in with this issue, but I'm not sure it warrants an issue of its own.  A few words about how to make async methods defined in services/plugins (difference?) run synchronously (in the fiber context ?) would maybe help as well.

I'm happy to do the leg work on this, I just need some guidance on the thinking.

**Comment by christian-bromann** [comment]
@RossVertizan thanks for pointing this out, this was indeed an error within the docs.
