### ISSUE TITLE
Implement codemod for transitioning Protractor tests into WebdriverIO

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#6659]
The Protractor project will soon be deprecated and a lot of users need to transition to a new framework. We want to help with this transition by providing a codemod that can transform their code into WebdriverIO code.

I started to work on a codemod using [jscodeshift](https://www.npmjs.com/package/jscodeshift): https://github.com/webdriverio/protractor-codemod

Here at Sauce Labs we have a lot of customers using Protractor so we connected to a couple to help them transitioning battle-testing the solutions we evaluate with this codemod or Craigs solution (see below).

**Comment by cnishina** [comment]
I have some ideas about this. We should talk about it.

**Comment by christian-bromann** [comment]
@cnishina I am currently working with jscodeshift to build a transformer that does something like:

```js
    /**
     * transform:
     * element(by.id('gobutton')).click();
     * $('#gobutton').click()
     */
    root.find(j.CallExpression)
      .filter((path) => (
          path.value.callee &&
          path.value.callee.type === 'Identifier' &&
          path.value.callee.name === 'element' &&
          path.value.arguments.length === 1 &&
          path.value.arguments[0].callee.type === 'MemberExpression' &&
          path.value.arguments[0].callee.object.name === 'by' &&
          path.value.arguments[0].callee.property.name === 'id'
      ))
      .replaceWith((path) => j.callExpression(
        j.identifier('$'),
        [j.literal(`#${path.value.arguments[0].arguments[0].value}`)]
      ))
```

Would love to hear your ideas on it. Will reach out via email.

**Comment by cnishina** [comment]
That's one way to do it. I have something different in mind.

**Comment by jan-molak** [comment]
Maybe we could mob on this?

**Comment by christian-bromann** [comment]
@jan-molak sure thing, I created https://github.com/webdriverio/protractor-codemod as a starting point. Happy to go in any direction with this.

**Comment by christian-bromann** [comment]
The codemod is in a pretty good shape now and we exploring issues as we support organizations to migrate to WebdriverIO. Please follow updates on the codemod in its repository.
