### ISSUE TITLE
Option to run selenium-standalone

### ISSUE THREAD

**Issue by silvenon** [webdriverio/webdriverio#666]
I'm not sure if this has any drawbacks, but it would be cool to make `wdio` optionally run the Selenium server, since we're always going to do that anyway. Then the configuration would go in `wdio.conf.js`.

**Comment by silvenon** [comment]
Or maybe since we're going to be running a local server, it's best to run selenium then as well…

**Comment by christian-bromann** [comment]
Adding this would be a huge pain in the a** to maintain since you have to make sure that it runs on all OS with all browser. Currently it is easier: if something doesn't work you can blame it on Selenium :wink: However there are good tools out there for example [selenium-standalone](https://github.com/vvo/selenium-standalone). What we could do is to improve the support for that project. Any suggestions how?

**Comment by silvenon** [comment]
I think adding a few recipes in the docs will be enough. I'll submit a PR when I find time :wink:

**Comment by christian-bromann** [comment]
Awesome, looking forward to that! Thanks

**Comment by monolithed** [comment]
@christian-bromann, 

> If the server is on the same machine where Nightwatch is running, it can be started/stopped directly by the Nightwatch Test Runner.
```js
  "selenium" : {
    "start_process" : false,
    "server_path" : "",
    "log_path" : "",
    "host" : "127.0.0.1",
    "port" : 4444,
    "cli_args" : {
      "webdriver.chrome.driver" : "",
      "webdriver.ie.driver" : ""
    }
  }
```

PS: [Nightwatch](http://nightwatchjs.org/guide) and [Testium](https://github.com/groupon/testium)

it's a real pain to run the selenium server manually...

**Comment by christian-bromann** [comment]
@monolithed true! In v4 we are introducing services that will take care of that. I already created a repository to run selenium standalone automatically. The only thing the user has to do is to download and add the service into his wdio.conf.js like

```js
// ...
services: ['selenium-standalone'],
// ...
```

I already created a similar service for a better sauce labs integrations that updates the job automatically and runs sauce connect if desired. Check out https://github.com/webdriverio/wdio-sauce-service

**Comment by monolithed** [comment]
@christian-bromann, :+1: 

> The only thing the user has to do is to download
It's ok,  I already have `selenium-standalone` as `npm` as `npm` dependency.

What about `stop` command?
Is there any way to kill the child process (`selenium.start([opts,] cb(error, child))`) like?

```js
onComplete (server) {
    server.kill();
}

**Comment by christian-bromann** [comment]
it should get killed automatically once the main process dies. If not just store the child process in a variable and kill the server in the `onComplete` command

**Comment by monolithed** [comment]
@christian-bromann, that's cool. 
So, the most important question, when? :dancers:

**Comment by christian-bromann** [comment]
Well you already can start selenium-standalone as an npm package in your `inPrepare` and shut it down in your `onComplete` hook.
However in v4 you only need to add the service and it takes care of that. Regarding release date:  I need to tie some loose ends and still have to port everything that was merged into master since I started working on v4 + some major changes with the website. I stopped giving any ETAs .. it's definitely soon!

**Comment by jardakotesovec** [comment]
@christian-bromann just found this thread and tried wdio-selenium-standalone-service but index.js in this package: 
```
/**
 * no service required
 */
module.exports = {}
```
suggests that its not ready yet, right? :-)
Thanks.

**Comment by christian-bromann** [comment]
it's ready but it seems that there are problems starting the server. The standalone service only uses the launcher.js file.

**Comment by mo** [comment]
@christian-bromann was this work finished or not? I'm using selenium standalone service and it works well when I run my test normally, but the REPL doesn't seem to pick up the config from wdio.conf.js or something?

"./node_modules/.bin/wdio wdio.conf.js" works
"./node_modules/.bin/wdio repl chrome" doesn't work

**Comment by christian-bromann** [comment]
> "./node_modules/.bin/wdio repl chrome" doesn't work

This should work with latest WebdriverIO version.

**Comment by christian-bromann** [comment]
> [21:54:59] ERROR	Error: connect ECONNREFUSED 127.0.0.1:4444

This clearly says that it can't connect to a selenium server so you need to start one first

**Comment by christian-bromann** [comment]
Please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have more questions. Thanks!
