### ISSUE TITLE
websocket connect in AttachToSession don't work for selenoid

### ISSUE THREAD

**Issue by fedoseevGIT** [webdriverio/webdriverio#6665]
**Environment (please complete the following information):**
 - **WebdriverIO and other packages version:** 7.3
 - **Mode:** WDIO Testrunner sync
 - **Node.js version:** 14.15.4
 - **Browser name and version:** Chrome latests
 - **Platform name and version:** Selenoid

**Describe the bug**
Recently released wdio 7.3, which included PR https://github.com/webdriverio/webdriverio/pull/6637

It was supposed to solve the problem of connecting to a websocket on remote browsers in selenoid https://github.com/webdriverio/webdriverio/issues/6387

However, this still doesn't work when using the following code:

```
const client = await attach({
                sessionId: browser.sessionId,
                capabilities: {
                    ...Object.assign(browser.capabilities, {
                        'goog:chromeOptions': {debuggerAddress: `${host}:${port}`},
                    }),
                },
                options: {
                    automationProtocol: 'devtools',
                },
            });
```

We still won't be able to connect to websocket, because in https://github.com/webdriverio/webdriverio/blob/main/packages/devtools/src/launcher.ts#L193 the browserURL (debuggerAddress) is passed, and for selenoid, the browserWSEndpoint must be passed immediately using the template `wss://${host}:4444/devtools/${browser.SessionID}`

**Expected behavior**
Successful connection to the websocket when using the code specified above

**Comment by christian-bromann** [comment]
The `attach` method currently allows to connect to a CDP session and it works for Chrome sessions but given that Selenoid has a custom CDP endpoint it requires some custom implementation. I suggest to modify the [`launch`](https://github.com/webdriverio/webdriverio/blob/main/packages/devtools/src/launcher.ts#L196-L222) method to create a Selenoid CDP WS endpoint. The question is how to determine whether we are dealing with a Selenoid session or not. Maybe we can detect a Seleniod flag in the capabilities?

Any contributions are appreciated.

**Comment by fedoseevGIT** [comment]
It seems to be ideal to define this at the wdio.config.js level, so that inside the test you do not have to use an attachment, but initially connect to the desired WSEndpoint.

Can you please tell me where is the entry point to the lounch method when starting wdio? At this point, do we already have a sessionID?

**Comment by christian-bromann** [comment]
> It seems to be ideal to define this at the wdio.config.js level, so that inside the test you do not have to use an attachment, but initially connect to the desired WSEndpoint.

I am not sure if I understand this correctly. Are you suggesting to allow attaching to sessions when using the WDIO testrunner? What is your usecase here? Someone needs to create a session at some point.

> Can you please tell me where is the entry point to the lounch method when starting wdio? At this point, do we already have a sessionID?

The attach method assumes you have a session id. Ideally you should be able to do just this:

```js
const browserA = await remote({ ... })
const browserB = await attach(browserA)
```

The `launch` method is used here: https://github.com/webdriverio/webdriverio/blob/8d49d8a657145b0d494ad7148c7d8d0d4c17a7c0/packages/devtools/src/index.ts

**Comment by BorisOsipov** [comment]
>The question is how to determine whether we are dealing with a Selenoid session or not. Maybe we can detect a Seleniod flag in the capabilities?

Capabilities from Selenoid are indistinguishable from capabilities returned by chromedriver\geckodriver\etc create session response.

**Comment by fedoseevGIT** [comment]
Me managed to solve the problem a little differently. In fact, this is very important for my project, so I would be very grateful if you take a look at this [pull request](https://github.com/webdriverio/webdriverio/pull/6669).

**Comment by christian-bromann** [comment]
> Capabilities from Selenoid are indistinguishable from capabilities returned by chromedriver\geckodriver\etc create session response.

Is it something we can request Selenoid to do? The Selenium server does this too as does Chromedriver.

**Comment by christian-bromann** [comment]
With https://github.com/webdriverio/webdriverio/pull/6684 you can connect to any arbitrary DevTools endpoints, e.g.

```js
            const client = await attach({
                sessionId: browser.sessionId,
                capabilities: {
                    'wdio:devtoolsOptions': {
                        browserWSEndpoint: format(
                            wss://%s:4444/devtools/%s,
                            browser.options.hostname,
                            browser.sessionId
                        )
                    }
                }
            });
```

Please let me know if this doesn't work for you. Cheers!
