### ISSUE TITLE
Exceptions in then do not reject promise (promise is never resolved nor rejected)

### ISSUE THREAD

**Issue by stefanmayer13** [webdriverio/webdriverio#667]
I'm using mocha as testrunner and return the webdriverio promises in my test cases. If one of my custom code called in a `then` function fails (throws an exception), the `then` added by mocha is not called (it registers a resolve and a rejection handler). I already tried to find the bug in the source code of webdriverio, but I could not find it. It seems that the code in `webdriverio.js`on line 195 is not working correctly.
```
if(self.promise.isRejected() && self.lastPromise.isRejected()) {
    return resolve.call(client, e, true, !onRejected);
}
return resolve.call(client, safeExecute(onRejected, arguments).bind(self));
```
The `then` of mocha is skipped here. This causes the test to timeout. As GUI-Tests take some time to run, the timeout of mocha is quite high. Therefore, you need to wait till the timeout or kill the test, which leaks an open session to the browser.

Here is some example code to test the behavior:

Resolves correctly
```
return client.url('/').then(() => {
    throw new Error('Exception');
});
```

Never resolves nor rejects
```
return client.url('/').then(() => {
    throw new Error('Exception');
}).pause(100);
```

This skips the first registered rejection handler, but will call the rejection handler registered afterwards:
```
return client.url('/').then(() => {
    throw new Error('Exception');
}).pause(100).then(() => {
    console.log('not called');
}, () => {
    console.log('not called either');
}).then(() => {
    console.log('not called as expected');
}, () => {
    console.log('called?!');
});
```

Regards,
Stefan

**Comment by jaroslav-kubicek** [comment]
I have very similar problem. When exception is thrown in callback, `done` function is never called:

```
it('check elements', function(done) {
  client.elements('h2', function(err, response) {
    if (err) {
      return done(err);
    }
    expect(response.value).to.be.an('array').that.have.length(10);
    done(); // not called when expect fails
  });
});
```

**Comment by christian-bromann** [comment]
@stefanmayer13 I improved the error handling in `v3.2.0`, when executing:

```js
client
    .init()
    .url('http://localhost:8080').then(function() {
        throw new Error('Exception');
    })
    .pause(100).then(function() {
        console.log('not called');
    }, function() {
        console.log('not called either');
    }).then(function() {
        console.log('not called as expected');
    }, function() {
        console.log('called?!');
    }).end();
```

I get

```
not called either
not called as expected
```

which makes totally sense, right? Will close the issue.

@jaroslav-kubicek this is a different issue, if an assertion fails it throws an assertion exception. Therefor the code stops at this point. You can handle it in two different ways:

using callbacks:
```js
it('check elements', function(done) {
  client.elements('h2', function(err, response) {
    if (err) {
      return done(err);
    }
    expect(response.value).to.be.an('array').that.have.length(10);
  }).catch(done).call(done);
});
```
or with promises:
```js
it('check elements', function() {
  return client.elements('h2').then(function(response) {
    expect(response.value).to.be.an('array').that.have.length(10);
  });
});
```

**Comment by stefanmayer13** [comment]
@christian-bromann Yes, thats the expected output! Thanks! :)
