### ISSUE TITLE
@wdio/junit-reporter: testcase names have a different naming format than the one specified in the docs

### ISSUE THREAD

**Issue by sandupetrasco** [webdriverio/webdriverio#6671]
I'd like to report
- [X] Unclear documentation
- [ ] A typo
- [ ] Missing documentation
- [X] Other

**Description of the report**
affected package: `@wdio/junit-reporter`

_One specific example is the following one:_
**[The docs:](https://www.npmjs.com/package/@wdio/junit-reporter/v/7.3.0)**
![image](https://user-images.githubusercontent.com/52775984/113890312-b6be9d00-97cc-11eb-9990-0df68124ea5a.png)

**The use-case:**
![image](https://user-images.githubusercontent.com/52775984/113890885-3d737a00-97cd-11eb-9611-6ffaa7131984.png)
![image](https://user-images.githubusercontent.com/52775984/113890651-069d6400-97cd-11eb-8bca-05417cb83c6c.png)

It can be seen that the naming format from the docs does not correspond with the one that is used in > 6.* versions (it is the same in older < 5.* versions of @wdio/junit-reporter).

Another issue related to naming format:
Test:
![image](https://user-images.githubusercontent.com/52775984/113891770-10739700-97ce-11eb-9a1b-05503649975f.png)
Current output in the reporter:
![image](https://user-images.githubusercontent.com/52775984/113891877-284b1b00-97ce-11eb-9dc3-dc0f9b8dc1d5.png)
Conclusion: All the symbols or none should be allowed in the tests names.

These issues come as a problem for our solutions and we would appreciate it if you fix them ASAP.
Thanks!

**Comment by AutomationReddy** [comment]
@sandupetrasco I will provide a PR soon to update the doc and `_` will be removed from test names. Can you also please let us know what is the issue that you are facing with special chars. The reason for allowing `@` is; few reporters take tags from test case names which starts with `@` symbol like `@foo` `@bar`.

**Comment by sandupetrasco** [comment]
@AutomationReddy The older versions of @wdio/junit-reporter (e.g. 5.18.*) were removing all the special chars from the test names. We were using some string matches after formatting the test name in junit format, and a specific edge-case with the `@` symbol is kinda' extra :).
However, is there a specific reason you do not allow special chars (those on the keyboard) and remove (some of) them from the test names?

**Comment by christian-bromann** [comment]
> These issues come as a problem for our solutions and we would appreciate it if you fix them ASAP.

@sandupetrasco if this is a problem for you please consider contributing to the project to get it resolved, thanks!

**Comment by christian-bromann** [comment]
@lthurr did your fix recently also fixed this?

**Comment by lthurr** [comment]
@christian-bromann Nope! My fix was about appending all the parent suite names to `classname`

Regarding this issue:
The documentation says you'll get

```
... name="a_nested_test_suite_a_test_case" ...
```

And you actually get
```
... name="a nested test suite a test case" ...
```

I think documentation could be updated.

**Comment by christian-bromann** [comment]
@lthurr yes thanks for clarifying. Updated docs.
