### ISSUE TITLE
spec-reporter saucelabs link doesn't reflect 'eu' region

### ISSUE THREAD

**Issue by michalboo** [webdriverio/webdriverio#6680]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.3.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.22.1
 - **NPM version:** 6.14.12
 - **Additional wdio packages used (if applicable):** 
 ```
    "@wdio/cucumber-framework": "^7.3.1",
    "@wdio/local-runner": "^7.3.1",
    "@wdio/sauce-service": "^7.3.1",
    "@wdio/spec-reporter": "^7.3.1",
    "@wdio/sync": "^7.3.1"
 ```

**Config of WebdriverIO**
https://github.com/michalboo/wdio-eu-link/blob/eu-reporter-link-issue/wdio.conf.js

**Describe the bug**
Running tests in Saucelabs with the eu region works as expected, but the 'Check out job at …' links posted in stdout by the reported point to the https://app.saucelabs.com domain (instead of the expected https://app.eu-central-1.saucelabs.com/tests/…). This causes problems (a 404 in saucelabs), especially for newcomers trying to debug failures.

Going from:
<img width="1130" alt="Screenshot 2021-04-08 at 23 16 14" src="https://user-images.githubusercontent.com/2195501/114105243-59a61280-98c4-11eb-9bd3-615aff59b7ad.png">
To:
<img width="740" alt="Screenshot 2021-04-08 at 23 45 09" src="https://user-images.githubusercontent.com/2195501/114105342-7b9f9500-98c4-11eb-85d2-13b909eea976.png">

Looking into the code, it appears that the `region` config field "gets lost" before reaching what seems to be [the relevant spec-reporter code](https://github.com/webdriverio/webdriverio/blob/f33b4f8671a9dd0569c91a39556565f607dd26fa/packages/wdio-spec-reporter/src/index.ts#L146)

The `region` appears to get dropped at the point of starting the remote session. The `validateConfig` function is invoked with a `keysToKeep` argument, containing the keys of the the webdriver config `DEFAULTS` onject: https://github.com/webdriverio/webdriverio/blob/dc7413a095ad13cfb6c49a8937696aa394ccb2cc/packages/webdriverio/src/index.ts#L33
This is defined in: https://github.com/webdriverio/webdriverio/blob/dc7413a095ad13cfb6c49a8937696aa394ccb2cc/packages/webdriver/src/constants.ts#L6, and does not include `region`.

**To Reproduce**
Steps to reproduce the behaviour:
1. run tests on saucelabs with region 'eu'
2. Check out the "Check out job at …" link in the stdout report
 
(cloning https://github.com/michalboo/wdio-eu-link/blob/eu-reporter-link-issue/ and running:
 ```
 npm i
 SAUCE_USERNAME=<YER_USERNAME> SAUCE_ACCESS_KEY=<YER_ACCESS_KEY> npx wdio run wdio.conf.js
```
should also do it.

**Expected behavior**
The "Check out job at …" link points at the correct (eu) saucelabs domain.

**Log**
https://gist.github.com/michalboo/212fbdaf468da66c06da65a1c0785e57

**Additional context**
This appears to work as expected in wdio 6 (checked 6.6.3)
I'd appreciate some thoughts on what the best way of fixing this could be. I imagine it would be relatively simple to (re)add `region` to the webdrivier DEFAULTS constant, similar to the fix in https://github.com/webdriverio/webdriverio/pull/6416, but I don't know a great deal about the overall picture (so I could be missing something simple/obvious/beautiful).

**Comment by christian-bromann** [comment]
We generate the link [within the spec reporter](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-spec-reporter/src/index.ts#L143-L152) and something seems to have changed that it can't detect the proper region anymore. This is a good first issue to start working/contributing to WebdriverIO. Any contributions would be appreciated!

**Comment by christian-bromann** [comment]
A PR with a fix was proposed and released with the next version. Thanks for filing the issue!
