### ISSUE TITLE
Capture cursor in `saveScreenshot`

### ISSUE THREAD

**Issue by Joozty** [webdriverio/webdriverio#6697]
It would be nice if `saveScreenshot` could also capture the cursor position. Not sure how hard it is. I guess it's doable by remembering the last position of cursor and when a page is about to be screenshotted  you would render an image instead on that position?🤔 

I can imagine to have optional param `saveScreenshot(captureCursor: boolean | string)` 
  - boolean - render default cursor image
  - string - render image from path

**Comment by christian-bromann** [comment]
@Joozty this is not gonna be easy. The best approach IMO is to inject a script using DevTools for every page load that tracks the cursor position (even though given everything is automated there won't be much cursor activity) and allows you to read it from the page global scope and then attach a give to a screenshot made.

I believe this is an excellent feature for a community service but I doubt anyone from the core team would pick this up. Therefor I am closing this. Thanks for filing the issue.
