### ISSUE TITLE
Add content to xUnit reporter

### ISSUE THREAD

**Issue by SchwaFa** [webdriverio/webdriverio#670]
Is it somehow possible to add something to the xUnit report?

I'm trying to link the screenshots (which I take in the expectationResultHandler of Jasmine) in the test report in Jenkins. 
Therefore, I found this nice little Jenkins Plugin: 
https://wiki.jenkins-ci.org/display/JENKINS/JUnit+Attachments+Plugin

It reads specific lines in the system-out section of the XML report to identify and add files to the Jenkins test result page.
But unfortunately, I can't just add such a line ("[[ATTACHMENT|/path/to/file]]") to the XML report and console.log ist not enough.

Where do the lines in the \<system-out...\> element come from? There are only webdriver logs in there. It would be nice to have the possibility to add everything that is printed using console.log().

The plain Jenkins JUnit test report is not that helpful without screenshots. 

(Maybe a nice HTML reporter would also solve this ;) ).

**Comment by christian-bromann** [comment]
Sounds interesting. Something like this should be possible.
We already have a ticket for a nice html reporter (see #532) and would like to prioritise that one before tackling this.

**Comment by SchwaFa** [comment]
Thanks for the fast reply. :+1: 
I already saw the ticket for the HTML reporter, which was the reason for my last sentence. But don't forget to always keep the CI integration (Jenkins) in mind. ;)

I'm really looking forward to this great feature!

**Comment by christian-bromann** [comment]
> But don't forget to always keep the CI integration (Jenkins) in mind. ;)

Sure :wink: I am totally excited to get the html reporter shipped. There are so much unused possibilities in the current eco system. I will keep you posted.

**Comment by christian-bromann** [comment]
Moved to the wdio-junit-reporter project
