### ISSUE TITLE
Remove `fibers` from WebdriverIO

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#6703]
In https://github.com/webdriverio/webdriverio/discussions/6702 we started an RFC to find the next step for supporting WebdriverIO in Node.js v16. As mentioned in the discussion node-fibers won't be supported anymore. Based on the decision found in the RFC we should implement a solution that allows us to move forward with Node.js v16.

**Comment by binarykitchen** [comment]
Aye. Unable to use webdriverio on latest node v16:

```
Assertion failed: (thread_id_key != 0x7777), function find_thread_id_key, file ../src/coroutine.cc, line 134.
```

Comes from the fibres package ...

**Comment by christian-bromann** [comment]
> Aye. Unable to use webdriverio on latest node v16:

This is the reason for this issue.

**Comment by ASOS-DaliaBanerjee** [comment]
Any update on this issue?

**Comment by christian-bromann** [comment]
@ASOS-DaliaBanerjee we just deprecated the sync API: https://webdriver.io/blog/2021/07/28/sync-api-deprecation. Fibers support will be available until we drop support for Node.js v14 which will be in April 2023. I will close this issue as this doesn't need to stay around so long.
