### ISSUE TITLE
Timeout option passed to waitForDisplayed function is ignored when searching for not existing element from element 

### ISSUE THREAD

**Issue by Anastasiia-Levina** [webdriverio/webdriverio#6704]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [7.3.1]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [v14.16.0]
 - **NPM version:** [6.14.11]
 - **Browser name and version:** [Chrome 89]
 - **Platform name and version:** [macOS 11.2.3 (20D91)]
 - **Additional wdio packages used (if applicable):** [
    "@wdio/cli": "^7.3.1",
    "@wdio/local-runner": "^7.3.1",
    "@wdio/mocha-framework": "^7.3.1",
    "@wdio/spec-reporter": "^7.3.1",
    "@wdio/sync": "^7.3.1",
    "webdriverio": "^7.3.1",
    "chromedriver": "^89.0.0",
    "wdio-chromedriver-service": "^7.0.0"
]

**Config of WebdriverIO**
exports.config = {
  specs: ['test.js'],
  logLevel: 'info',
    path: '/',
    capabilities: [{
        browserName: 'chrome',
    }],
    waitforTimeout: 1000,
    services: [
        [ 'chromedriver', {
            outputDir: './'
        }]
    ],
    framework: 'mocha',
    mochaOpts: {
        timeout: 30000
    },
}

**Describe the bug**
I have repeatable elements on the page. I need to check that each of this repeatable elements doesn't have another element under it. I use waitForDisplayed function for this task, and pass timeout option to it. This timeout option is ignored.

**To Reproduce**
1. Open google search
2. Get all elements with class .g
3. Use waitForDisplayed function with timeout 0.5 sec to check if $('.imnotexist') element is displayed under $$('.g')[9] element

describe('Element lookup test', () => {
    it('should wait 0.5 seconds for the element to appear', () => {
        browser.url('https://www.google.com/search?q=ololo');
        const parentElements = $$('.g');
        const element = parentElements[9].$('#idontexist');
        element.waitForDisplayed({ timeout: 500, timeoutMsg: "I timed out!" });
        browser.deleteSession();
    })
})

**Expected behavior**
waitForDisplayed should throw timeout exception after 0.5 sec

[wdio7.zip](https://github.com/webdriverio/webdriverio/files/6305703/wdio7.zip)

**Comment by christian-bromann** [comment]
This error can already be reproduced by running:

```js
        browser.url('https://www.google.com/search?q=ololo')
        const parentElements = $$('.g')
        const element = parentElements[9].$('#idontexist')
        console.log(element)
```

The problem lies somewhere in the [`refetchElement`](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/utils/refetchElement.ts) logic which is triggered if catching an element fails. Any help on this would be appreciated.

**Comment by christian-bromann** [comment]
After revisiting this issue it turns out that everything is working as expected, the following example reproduces this:

```js
const { remote } = require('webdriverio')

let browser

;(async function () {
    browser = await remote({
        logLevel: 'error',
        capabilities: {
            browserName: 'chrome',
        }
    })
    await browser.url('https://www.google.com/search?q=ololo')
    const parentElements = await browser.$$('.g')
    const element = await parentElements[9].$('#idontexist')
    await element.waitForDisplayed({ timeout: 500, timeoutMsg: 'I timed out!' })

    throw new Error('I should never be reached!')
})().catch(async (e) => {
    console.error('Test run failed:', e.message)
    await browser.deleteSession()
})
```

Outputs: `Test run failed: I timed out!`
