### ISSUE TITLE
elementIDElement is not working

### ISSUE THREAD

**Issue by thejananda** [webdriverio/webdriverio#671]
```js
.elements('//div[@class="normal" and @eventproxy="isc_alu_nms_SAMLoginForm_0"]/div/div',function(err,res) {
		var self = this;
		for(var x=0;x<res.value.length;x++){
       	 console.log("ttttt");
       	 console.log(res.value[x].ELEMENT);
        	self.elementIdElement(res.value[x].ELEMENT,'//div').then(function(txt){
          	                                                                       client.elementIdAttribute(txt.value.ELEMENT,"id").then(function(res){
          	                                                                    	   console.log("attributes :",res);
          	                                                                    	console.log("attributes :",res.value);
          	                                                                       });
									
											                });

```
i here i am getting the elements 
under the elemnts there are 4 div's
under each div i am trying take id attribute value 

but it is fetching the id attribute value of first div in page and printing four times..

**Comment by christian-bromann** [comment]
Hi @thejananda 

first of all: it makes my life easier if your code example is formatted so I can understand easier what's going on.

regarding your issue: each command is async, you need to make sure that it gets executed at the right time, try:

```js
return client.elements('//div[@class="normal" and @eventproxy="isc_alu_nms_SAMLoginForm_0"]/div/div').then(function(res) {
    var self = this,
        commands = [],
        q = require('q');

    for (var x = 0; x < res.value.length; x++) {
        console.log("ttttt");
        console.log(res.value[x].ELEMENT);
        commands.push(self.elementIdElement(res.value[x].ELEMENT, '//div').then(function(txt) {
            return client.elementIdAttribute(txt.value.ELEMENT, "id").then(function(res) {
                console.log("attributes :", res);
                console.log("attributes :", res.value);
            });
        }));
    }

    return q.all(promises);
});
```

**Comment by thejananda** [comment]
var webdriverio = require('webdriverio');
var options = {
	    desiredCapabilities: {
	        browserName:'firefox'
	    },
	    host : '135.250.24.78',
	    port : '5555',
	};


var client=webdriverio.remote(options);
client
	.init()
	.url('http://135.250.194.235/')
	.pause(2500) ;

return client.elements('//div[@class="normal" and @eventproxy="isc_alu_nms_SAMLoginForm_0"]/div/div').then(function(res) {
    var self = this,
        commands = [],
        q = require('q');

    for (var x = 0; x < res.value.length; x++) {
        console.log("ttttt");
        console.log(res.value[x].ELEMENT);
        commands.push(self.elementIdElement(res.value[x].ELEMENT, '//div').then(function(txt) {
            return client.elementIdAttribute(txt.value.ELEMENT, "id").then(function(res) {
                console.log("attributes :", res);
                console.log("attributes :", res.value);
            });
        }));
    }

    return q.all(promises);
});


here is my full code

**Comment by thejananda** [comment]
even now its printing same...
