### ISSUE TITLE
Remove scripts from log payload

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#6714]
If someone executes a script, the payload of that execute command is stored in the logs which can be very noisy when passing in large scripts, e.g. when using `isDisplayed`:

```log
[0-0] 2021-04-14T10:53:53.105Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
[0-0] 2021-04-14T10:53:53.106Z INFO webdriver: [POST] http://localhost:9515/session/cbfaae75ee94c6e8390b41022122e082/execute/sync
[0-0] 2021-04-14T10:53:53.106Z INFO webdriver: DATA {
  script: 'return (function isElementDisplayed(element) {\n' +
    '    function nodeIsElement(node) {\n' +
    '        if (!node) {\n' +
    '            return false;\n' +
    '        }\n' +
    '        switch (node.nodeType) {\n' +
    '            case Node.ELEMENT_NODE:\n' +
    '            case Node.DOCUMENT_NODE:\n' +
    '            case Node.DOCUMENT_FRAGMENT_NODE:\n' +
    '                return true;\n' +
    '            default:\n' +
    '                return false;\n' +
    '        }\n' +
    '    }\n' +
    '    function parentElementForElement(element) {\n' +
    '        if (!element) {\n' +
    '            return null;\n' +
    '        }\n' +
    '        return enclosingNodeOrSelfMatchingPredicate(element.parentNode, nodeIsElement);\n' +
    '    }\n' +
    '    function enclosingNodeOrSelfMatchingPredicate(targetNode, predicate) {\n' +
    '        for (let node = targetNode; node && node !== targetNode.ownerDocument; node = node.parentNode)\n' +
    '            if (predicate(node)) {\n' +
    '                return node;\n' +
    '            }\n' +
    '        return null;\n' +
```

I suggest to check if we have a `script` property in the payload and just put in a placeholder.

**Comment by OlaoluwaM** [comment]
Hey @christian-bromann , can I try my hand at this?

**Comment by christian-bromann** [comment]
Sure thing!

**Comment by OlaoluwaM** [comment]
Could you perhaps point me to where I can start looking?

**Comment by christian-bromann** [comment]
I would take a look here: https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-utils/src/utils.ts#L89-L100

**Comment by OlaoluwaM** [comment]
I think I know what to do here.

Correct me if I am wrong but we will check the ``result`` argument for a script property, if one exists we return a placeholder right?

If so, where should I get the placeholder from and what kind of check should I perform to confirm the existence of the ``script`` property on the ``result`` object? Would it be the same checks as for the ``file`` property?

**Comment by OlaoluwaM** [comment]
@christian-bromann ?

**Comment by christian-bromann** [comment]
> if one exists we return a placeholder right?

That seems like a good solution to me.

> where should I get the placeholder from

Just define one

> what kind of check should I perform to confirm the existence of the `script` property on the `result` object?

Yes.

Would it be the same checks as for the `file` property?

Yes.

**Comment by christian-bromann** [comment]
@OlaoluwaM any progress on this?

**Comment by OlaoluwaM** [comment]
So sorry for the delay, will get in it today, just gotta open the PR

**Comment by OlaoluwaM** [comment]
Done! So sorry for the delay, please take a look when you can and any feedback is much appreciated

**Comment by christian-bromann** [comment]
Let's continue conversation in #6921
