### ISSUE TITLE
Error with getting started

### ISSUE THREAD

**Issue by fcarrasco92** [webdriverio/webdriverio#6715]
I did the first installation from getting started with this configuration.
![image](https://user-images.githubusercontent.com/5995491/114726125-135d1300-9d0b-11eb-920b-dd84bdc301f6.png)

when run the script `npx wdio run ./wdio.conf.js`

launch error. 
![image](https://user-images.githubusercontent.com/5995491/114726295-41daee00-9d0b-11eb-808c-399192de88fc.png)
![image](https://user-images.githubusercontent.com/5995491/114726323-499a9280-9d0b-11eb-8151-d67b8147a85d.png)
![image](https://user-images.githubusercontent.com/5995491/114726359-53bc9100-9d0b-11eb-91ca-9659ed12fc63.png)

I add the dependencies

`
"dependencies": {
    "@wdio/cli": "^7.4.2"
  },
  "devDependencies": {
    "@wdio/allure-reporter": "^7.4.2",
    "@wdio/local-runner": "^7.4.2",
    "@wdio/mocha-framework": "^7.4.2",
    "@wdio/spec-reporter": "^7.4.3",
    "@wdio/sync": "^7.4.2",
    "chromedriver": "^89.0.0",
    "wdio-chromedriver-service": "^7.0.0"
  }
`

please help with this.

thanks

**Comment by christian-bromann** [comment]
Thanks for reporting, this is indeed a regression.

**Comment by christian-bromann** [comment]
Running a release with a fix for this. Once done, please re-install the `@wdio/cli` package. The fixed version should be `v7.4.3`.

**Comment by fcarrasco92** [comment]
@christian-bromann  thanks so much, a pleasure to help
