### ISSUE TITLE
Regression of https://github.com/webdriverio/webdriverio/pull/6487

### ISSUE THREAD

**Issue by pmerwin** [webdriverio/webdriverio#6716]
Seeing this issue again with vs 7.4, devtools backend shrinks viewsport, chrome-driver works.  Using latest chrome : Version 89.0.4389.128 (Official Build) (x86_64)

https://github.com/webdriverio/webdriverio/pull/6487

**Comment by L0tso** [comment]
@christian-bromann Fix was removed [here](https://github.com/webdriverio/webdriverio/pull/6684/files#diff-8f671d792ef73a8deffe369fbd833f6338a1bbea44d8fb4849635545797f6e4eL117). Was it necessary?

**Comment by christian-bromann** [comment]
I removed it because of this comment:

> // @ts-ignore ToDo(@L0tso): remove once https://github.com/puppeteer/puppeteer/pull/6942 is merged

but now I realise that the comment was about remove the comment not the viewport property.

**Comment by christian-bromann** [comment]
Fixed and released with `v7.4.5`
