### ISSUE TITLE
Why wdio pass "desiredCapabilities" with "capabilities" to /session? [w3c]

### ISSUE THREAD

**Issue by DudaGod** [webdriverio/webdriverio#6721]
Hello.

According to w3c specification - https://w3c.github.io/webdriver/#processing-capabilities field `desiredCapabilities` should not be transmitted. But I see that it is passed:
```
2021-04-16T13:53:33.609Z INFO webdriver: Initiate new session using the WebDriver protocol
2021-04-16T13:53:33.616Z INFO webdriver: [POST] http://MY_GRID_URL/wd/hub/session
2021-04-16T13:53:33.616Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'chrome', browserVersion: '85.0' },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'chrome', browserVersion: '85.0' }
}
```

Moreover `desiredCapabilities` from jsonwp - https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#status knows nothing about `browserVersion`.

It looks like that problem is here:
https://github.com/webdriverio/webdriverio/blob/9d2220e89144b0ca69232737957ad5fc32ca1300/packages/webdriver/src/utils.ts#L56-L73.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.1.0
 - **Mode:** Standalone mode
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 12.18.1
 - **NPM version:** 6.14.5

**To Reproduce**

Test example:
```
const wdio = require('webdriverio');
let client;

(async function () {
    client = await wdio.remote({
        protocol: 'http',
        hostname: 'MY_GRID_URL,
        port: 4444,
        path: '/wd/hub',

        automationProtocol: 'webdriver',
        logLevel: 'trace',

        capabilities: {
            browserName: 'chrome',
            browserVersion: '85.0',
        }
    });

    console.log('client:', client);

    await client.deleteSession();
})()
    .catch(async (e) => {
        console.error(e.stack)
        await client.deleteSession()
    })
```

**Expected behavior**

I expected that wdio pass only `capabilities` to `/session` like it is described in w3c protocol.

**Comment by christian-bromann** [comment]
This is done intentionally to ensure that tests can be run on deprecated JSONWP as well as WebDriver endpoints. I believe it is a good idea to keep it around for a little while until everyone has moved on from JSONWP. Are you running into any issues having `desiredCapabilities` transmitted in the session request? Usually endpoints that speak WebDriver will just ignore it. Afaik there is no paragraph in the spec saying it is not allowed to send additional data over the wire.

**Comment by DudaGod** [comment]
> Are you running into any issues having desiredCapabilities transmitted in the session request?

Yes we have a problem in one piece of code, but it looks like we just need to fix it (increase priority for `capabilities`).

Thank you. I close it.
