### ISSUE TITLE
"java.net.ConnectException: Connection refused: connect" after upgrade to webdriverIO v7

### ISSUE THREAD

**Issue by mareru** [webdriverio/webdriverio#6728]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.4.5
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.18.3
 - **NPM version:** 6.14.8 (yarn: 1.22.5)
 - **Browser name and version:** 90.0.4430.72
 - **Platform name and version:**  Windows 10
 - **Additional wdio packages used (if applicable):**
 This is my `package.json` dependencies: 

```
  "dependencies": {
    "@babel/cli": "^7.13.14",
    "@babel/plugin-proposal-export-default-from": "^7.12.13",
    "@babel/preset-env": "^7.13.15",
    "@babel/register": "^7.13.14",
    "@types/cucumber": "^7.0.0",
    "@wdio/cli": "^7.4.5",
    "@wdio/config": "^7.4.2",
    "@wdio/cucumber-framework": "^7.4.2",
    "@wdio/local-runner": "^7.4.5",
    "@wdio/selenium-standalone-service": "^7.4.2",
    "@wdio/spec-reporter": "^7.4.3",
    "@wdio/sync": "^7.4.5",
    "chai": "^4.3.4",
    "eslint-plugin-wdio": "^7.4.2",
    "file-system": "^2.2.2",
    "mjpeg-consumer": "^2.0.0",
    "node-fetch": "^2.6.1",
    "webdriverio": "^7.4.5",
    "yarn": "^1.22.10"
  },
  "devDependencies": {
    "@babel/core": "^7.13.15",
    "@cucumber/cucumber": "^7.1.0",
    "@wdio/allure-reporter": "^7.4.2",
    "@wdio/browserstack-service": "^7.4.5",
    "@wdio/junit-reporter": "^7.4.2",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.23.0",
    "eslint-plugin-import": "^2.22.1",
    "forever": "^3.0.4",
    "jest": "^26.6.3",
    "npm-run-all": "^4.1.5"
  }
```

**Config of WebdriverIO**
This is my `wdio.conf.js`:

```
const path = require('path');
const commands = require('./src/commands/commands');

exports.config = {

    specs: [
        './src/features/**/*.feature',
    ],

    suites: {
        warmUp: [
            './src/features/warmUp.feature',
        ],
        features: [
            './src/features/accountSummary.feature',
            './src/features/cart.feature',
            './src/features/categoryNavigation.feature',
            './src/features/checkout.feature',
            './src/features/forgotPassword.feature',
            './src/features/loggedOutNavigation.feature',
            './src/features/login.feature',
            './src/features/orderHistory.feature',
            './src/features/orderTemplate.feature',
            './src/features/outofstock.feature',
            './src/features/productDetail.feature',
            './src/features/promotions.feature',
            './src/features/register.feature',
            './src/features/search.feature',
            './src/features/checkoutMobile.feature',
        ],
    },
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    
    maxInstances: 1,
   
    capabilities: [{
        maxInstances: 1,
        browserName: 'chrome',
    },
    {
        maxInstances: 1,
        browserName: 'firefox',
        acceptInsecureCerts : true,
    },
    ],

    sync: true,
    logLevel: 'debug',
    coloredLogs: true,
    screenshotPath: './error-shots',
    baseUrl: 'https://myapp.com/',
    waitforTimeout: 20000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    services: ['selenium-standalone'],
    outputDir: path.join(__dirname, 'logs'),
    framework:
        'cucumber',
    reporters:
        [
            'spec',
            'allure',
            ['junit', {
                outputDir: './junit-results',
                outputFileFormat: function(options) { // optional
                    return `results-${options.cid}.${options.capabilities.browserName}.xml`
                },
            }],
        ],
    cucumberOpts:
        {
            // <boolean> show full backtrace for errors
            backtrace: false,
            // <string[]> module used for processing required features
            requireModule:
                ['@babel/register'],
            // <boolean< Treat ambiguous definitions as errors
            failAmbiguousDefinitions:
                true,
            // <boolean> invoke formatters without executing steps
            // dryRun: false,
            // <boolean> abort the run on first failure
            failFast:
                false,
            // <boolean> Enable this config to treat undefined definitions as
            // warnings
            ignoreUndefinedDefinitions:
                false,
            // <string[]> ("extension:module") require files with the given
            // EXTENSION after requiring MODULE (repeatable)
            name:
                [],
            // <boolean> hide step definition snippets for pending steps
            snippets:
                true,
            // <boolean> hide source uris
            source:
                true,
            // <string[]> (name) specify the profile to use
            profile:
                [],
            // <string[]> (file/dir) require files before executing features
            require:
                [
                    './src/step_definitions/*.js',
                    './src/step_definitions/mobile/*.js',
                    // Or search a (sub)folder for JS files with a wildcard
                    // works since version 1.1 of the wdio-cucumber-framework
                    //'./src/**/*.js',
                ],
            // <string> specify a custom snippet syntax
            snippetSyntax:
            undefined,
            // <boolean> fail if there are any undefined or pending steps
            strict:
                true,
            // <string> (expression) only execute the features or scenarios with
            // tags matching the expression, see
            // https://docs.cucumber.io/tag-expressions/
            tagExpression:
                'not @Ignore',
            // <boolean> add cucumber tags to feature or scenario name
            tagsInTitle:
                false,
            // <number> timeout for step definitions
            timeout: 60000,
        },
    before: function before() {
        const chai = require('chai');

        global.expect = chai.expect();
        global.should = chai.should();

        //setup test data
        global.testdata = require('./testData');
        global.loc = require('./localisation');

        browser.maximizeWindow();

        Object.keys(commands).forEach(key => {
            browser.addCommand(key, commands[key]);
        });
    }
    ,
}
;
```
This is my `wdio.chrome.headless.conf.js`: 

```
const path = require('path');
const wdioConfig = require('../../../wdio.conf.js');


const chromeDriverVersion = process.env.CHROME_DRIVER_VERSION;

wdioConfig.config.capabilities = [{
    maxInstances: 1,
    browserName: 'chrome',
    'goog:chromeOptions': {
        // to run chrome headless the following flags are required
        // (see https://developers.google.com/web/updates/2017/04/headless-chrome)
        args: ['--headless', '--disable-gpu', '--no-sandbox', '--window-size=1920,1080'],
    },
    acceptInsecureCerts : true,
}];


const seleniumConfig = {
    drivers: { chrome: { version:  chromeDriverVersion} },
};

wdioConfig.config.services = [
    [
        'selenium-standalone',
        {
            logPath: path.join(__dirname, "../../../selenium-server-logs"),
            args: seleniumConfig,
            installArgs: seleniumConfig,
        },
    ],
];

exports.config = wdioConfig.config;
```

**Describe the bug**
When I run my test suite with  
 `yarn run wdio src/resources/config/wdio.chrome.headless.conf.js --suite warmUp --suite features`,   
then randomly my tests fail with the error `java.net.ConnectException: Connection refused: connect`. I cannot say it happens to a particular test, but it happens all the time to some tests (not always the same tests - it may happen that in one run a test passed and in the second run it failed with this error).  

**To Reproduce**
It happens randomly to my test suite but happens every time I run the tests (regardless headless or headful mode)

**Expected behavior**
I would expect not to have this connection issue

**Log**
In the logs I have the error:  
```
2021-04-19T18:15:39.282Z INFO webdriver: COMMAND elementClear("1bc3c9b6-58b8-4653-99fc-e69b21aa186e")
2021-04-19T18:15:39.282Z INFO webdriver: "INFO webdriver: [POST] http://localhost:4444/wd/hub/session/3168eac22ed891f60e0a3e180b05ccf5/element/1bc3c9b6-58b8-4653-99fc-e69b21aa186e/clear
2021-04-19T18:15:41.446Z DEBUG webdriver: request failed due to status 13
2021-04-19T18:15:41.446Z WARN webdriver: Request failed with status 500 due to java.net.ConnectException: Connection refused: connect
```
This is in my console:  
```
unknown error: java.net.ConnectException: Connection refused: connect
    at Object.getErrorFromResponseBody (C:\my-project\node_modules\webdriver\build\utils.js:189:12)
    at WebDriverRequest._request (C:\my-project\node_modules\webdriver\build\request.js:168:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Browser.runCommandWithHooks (C:\my-project\node_modules\@wdio\sync\build\wrapCommand.js:105:25)
    at Browser.runCommandWithHooks (C:\my-project\node_modules\@wdio\sync\build\wrapCommand.js:100:24)
    at Browser.url (C:\my-project\node_modules\@wdio\sync\build\wrapCommand.js:67:44)
    at LoginPage.openPage (C:\my-project\src\pages\/loginPage.js:47:29)
    at World.<anonymous> (C:\my-project\src\step_definitions\/navigation_steps.js:22:15)
    at World.executeSync (C:\my-project\node_modules\@wdio\sync\build\index.js:38:22)
    at World.executeSync (C:\my-project\node_modules\@wdio\sync\build\index.js:52:38)
    at C:\my-project\node_modules\@wdio\sync\build\index.js:69:68
```

**Additional context**
This started to happen once I upgraded to webdriverIO v7.  
It seams to me like selenium session is not created sometimes, but I don't know how to fix it or what is exactly causing this issue.

**Comment by christian-bromann** [comment]
Hey @mareru , thanks for filling an issue in the WebdriverIO project.

This seems to be a tough one. While my initial gut feeling says this issue is infrastructure related and not in WebdriverIO, your comment on "it starts to happen after WebdriverIO" makes me think. Some questions:

- From which version did you upgrade from?
- What WebDriver backend are you running your tests against? 
- How many tests do you run in parallel?
- Where do you run these tests (own CI or somewhere else)?

It will probably impossible to provide a reproducible example for this one. A solution could be to implement retries for such failing requests. Could you also do some research on your site whether there are chances that your connection gets lost somewhere?

**Comment by mareru** [comment]
Hello @christian-bromann , thanks for the reply.  

- From which version did you upgrade from? 
I upgraded from version 5 to version 7.   
Although I have to say that at first (when I wanted to upgrade to version 6) I only upgraded webdriverio dependency in `package.json` which I learned later on that is not the proper way to upgrade (I also needed to upgrade other webdriverio packages).  
My `package.json` file prior to upgrade to version 7 looked like this (and it didn't break with this error):  
```
 "dependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/plugin-proposal-export-default-from": "^7.5.2",
    "@babel/preset-env": "^7.4.2",
    "@babel/register": "^7.4.0",
    "@types/cucumber": "^4.0.5",
    "@wdio/cli": "^5.13.2",
    "@wdio/config": "^5.13.2",
    "@wdio/cucumber-framework": "^5.13.2",
    "@wdio/local-runner": "^5.13.2",
    "@wdio/selenium-standalone-service": "^5.13.2",
    "@wdio/spec-reporter": "^5.13.2",
    "@wdio/sync": "^5.13.2",
    "chai": "^4.1.2",
    "cucumber": "^4.2.1",
    "eslint-plugin-wdio": "^5.7.8",
    "file-system": "^2.2.2",
    "mjpeg-consumer": "^2.0.0",
    "node-fetch": "^2.6.0",
    "webdriverio": "^6.10.5",
    "yarn": "^1.17.3"
  },
  "devDependencies": {
    "@babel/core": "^7.4.0",
    "@wdio/allure-reporter": "^5.13.2",
    "@wdio/browserstack-service": "^5.0.0",
    "@wdio/junit-reporter": "^5.18.6",
    "babel-eslint": "^10.0.3",
    "babel-jest": "^24.8.0",
    "eslint": "^6.0.0",
    "eslint-plugin-import": "^2.18.0",
    "forever": "^0.15.3",
    "jest": "^24.8.0",
    "npm-run-all": "^4.1.5"
  }
```
- What WebDriver backend are you running your tests against?  
I am not quite sure what do you mean by this. I use Chrome driver version `90.0.4430.24` but I am guessing it is not what you meant by WebDriver backend. Can you please clarify it a bit?
- How many tests do you run in parallel?  
I don't run in parallel. They are all run sequentially, one after another.
- Where do you run these tests (own CI or somewhere else)?
Usually they are run on CI (Azure pipeline) - that is where version 5 is currently running without this error.  
But this error I get while running it locally on my machine - Windows 10.   
I wanted to upgrade to the latest webdriverIO version, but I can't get my suite to run successfully on my local machine so that is why I haven't pushed my changes yet in order to run in CI.   
But I could try it out in CI and see if it happens there as well - if that would matter. What do you think?

**Comment by christian-bromann** [comment]
> * Can you please clarify it a bit?

What I mean by that is where do the WebdriverIO request go to? A local driver like chromedriver or do you have a custom Selenium Grid or use a cloud service like Sauce Labs?

> * But this error I get while running it locally on my machine - Windows 10.

Interesting, can you try to create a minimal example then? Or would that be too difficult given that this error happens randomly?

> * But I could try it out in CI and see if it happens there as well - if that would matter. What do you think?

Yes, let's try that.

**Comment by mareru** [comment]
> What I mean by that is where do the WebdriverIO request go to? A local driver like chromedriver or do you have a custom Selenium Grid or use a cloud service like Sauce Labs?
It is a local driver like Chrome Driver that I mentioned before. (same on CI as well as on my local machine)

> Interesting, can you try to create a minimal example then? Or would that be too difficult given that this error happens randomly?
I can try to do that tomorrow - maybe copy all of my set up and provide some example tests towards public site.  
It would be also good exercise to see if I can reproduce it.

> Yes, let's try that.
Ok, I will be able also to do that tomorrow.

**Comment by mareru** [comment]
Hello @christian-bromann,
These are my updates:  

- I pulled the version I have in CI (with webdriverIO 5) to my local machine and the thing is I got the same error for one of the scenarios. That being said I believe it is not related to the wdio upgrade after all
- on my CI in Azure this error with the old code base is not happening for some reason
- I am trying to run the code with the upgrade to version 7 on the CI, but currently there are some issues with the node version we have there. It needs to be updated due to an error (`error @wdio/cli@7.4.5: The engine "node" is incompatible with this module. Expected version ">=12.0.0". Got "10.23.3`) 
- I tried to provide minimal example. I basically downloaded as zip file my whole code base and: 
  -left all the configuration I had after upgrading to version 7
  -removed all the code related to testing my app 
  -added some test scenarios for testing the `https://the-internet.herokuapp.com/` and for this examples I was not able to reproduce the error :(   

I have to see what will happen in CI yet, but I am guessing it will not happen there. That's just my lucky guess :)   
Do you have any idea why would this happen to me locally? I didn't experience it in the past as far as I can remember.  
Could it be related to my poor internet connection? (I am working from home so things are not ideal)  
I really don't know what could possibly cause this.   
Any advice would be helpful :)

**Comment by mareru** [comment]
This is what I get when I try to open that POST request from the logs while my execution is still ongoing:   
```
{
  "value": {
    "stacktrace": "java.lang.RuntimeException: java.net.ConnectException: Connection refused: connect\r\n\tat org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0(WebDriverServlet.java:240)\r\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)\r\n\tat java.util.concurrent.FutureTask.run(Unknown Source)\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\r\n\tat java.lang.Thread.run(Unknown Source)\r\nCaused by: java.net.ConnectException: Connection refused: connect\r\n\tat java.net.DualStackPlainSocketImpl.connect0(Native Method)\r\n\tat java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)\r\n\tat java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)\r\n\tat java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)\r\n\tat java.net.AbstractPlainSocketImpl.connect(Unknown Source)\r\n\tat java.net.PlainSocketImpl.connect(Unknown Source)\r\n\tat java.net.SocksSocketImpl.connect(Unknown Source)\r\n\tat java.net.Socket.connect(Unknown Source)\r\n\tat java.net.Socket.connect(Unknown Source)\r\n\tat sun.net.NetworkClient.doConnect(Unknown Source)\r\n\tat sun.net.www.http.HttpClient.openServer(Unknown Source)\r\n\tat sun.net.www.http.HttpClient.openServer(Unknown Source)\r\n\tat sun.net.www.http.HttpClient.\u003cinit>(Unknown Source)\r\n\tat sun.net.www.http.HttpClient.New(Unknown Source)\r\n\tat sun.net.www.http.HttpClient.New(Unknown Source)\r\n\tat sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)\r\n\tat sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)\r\n\tat sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)\r\n\tat sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)\r\n\tat sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)\r\n\tat sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)\r\n\tat java.net.HttpURLConnection.getResponseCode(Unknown Source)\r\n\tat org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:111)\r\n\tat org.openqa.selenium.grid.session.remote.Passthrough.handle(Passthrough.java:35)\r\n\tat org.openqa.selenium.grid.session.remote.RemoteSession.execute(RemoteSession.java:129)\r\n\tat org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0(WebDriverServlet.java:235)\r\n\t... 5 more\r\n",
    "stackTrace": [
      {
        "fileName": "WebDriverServlet.java",
        "methodName": "lambda$handle$0",
        "className": "org.openqa.selenium.remote.server.WebDriverServlet",
        "lineNumber": 240
      },
      {
        "fileName": null,
        "methodName": "call",
        "className": "java.util.concurrent.Executors$RunnableAdapter",
        "lineNumber": -1
      },
      {
        "fileName": null,
        "methodName": "run",
        "className": "java.util.concurrent.FutureTask",
        "lineNumber": -1
      },
      {
        "fileName": null,
        "methodName": "runWorker",
        "className": "java.util.concurrent.ThreadPoolExecutor",
        "lineNumber": -1
      },
      {
        "fileName": null,
        "methodName": "run",
        "className": "java.util.concurrent.ThreadPoolExecutor$Worker",
        "lineNumber": -1
      },
      {
        "fileName": null,
        "methodName": "run",
        "className": "java.lang.Thread",
        "lineNumber": -1
      }
    ],
    "message": "java.net.ConnectException: Connection refused: connect",
    "error": "unknown error"
  },
  "status": 13
}
```  
Does this give any more clues to you?

**Comment by erwinheitzman** [comment]
Could you perhaps set the `outputDir` and set your `logLevel` to `trace` and share the full logs when running this specific scenario (use a gist link)?

Of course you can filter sensitive data if there is any in the logs.

**Comment by mareru** [comment]
@erwinheitzman thanks for reaching out.  

Here are my logs [gist](https://gist.github.com/mareru/f5d2facbce9fa4bcc0a65b6bd6e7b91c) 

I have to mention that I tried to run the tests once in my office (I was able to go there finally) and I didn't get that error.  
Also I went home and switched to my WiFi connection and didn't get that error (there were some other errors involved but that's a different story :) )  

When I use my 4G Modem stick for the internet connection, then I get this error.  

Could be that it is related to my internet connection? o_O  
If so what is the reason of this happening, it is so weird.

**Comment by christian-bromann** [comment]
So it seems to be a network related issue. No matter what, WebdriverIO should at least retry this like normal WebDriver errors.

**Comment by christian-bromann** [comment]
Added a PR with a fix. Let's continue convo there: #6756

**Comment by NIBOSAP** [comment]
Hi @christian-bromann,

I have the same issue as @mareru.
After investigation, I noticed that the error I get is slightly than the one you handled in your PR, so in my case the retry is not called.

Here is the error I get: 
```
java.net.ConnectException: Connection refused (Connection refused)
```
Would it be possible to also handle this case? 

Thanks a lot.
