### ISSUE TITLE
Add browser["browserName"] documentation to Multiremote documentation

### ISSUE THREAD

**Issue by evilC** [webdriverio/webdriverio#6754]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [x] Unclear documentation
- [ ] A typo
- [ ] Missing documentation
- [ ] Other

**Description of the improvement / report**
I am using Multiremote with a config such as
```
    capabilities: {
        browserA: {
            capabilities: {
                browserName: 'chrome'
            }
        },
        browserB: {
            capabilities: {
                browserName: 'chrome'
            }
        }
    }
```
I am also use cucumer-framework, so I am not using code such as
```
    const browser = await multiremote({
        browserA: {
            capabilities: {
                browserName: 'chrome'
            }
        },
        browserA: {
            capabilities: {
                browserName: 'chrome'
            }
        }
    })
```
to new up the browser object.
As such, I wanted some way to be able to access the `browserA` and `browserB` objects, eg from a step definition such as
`Given Agent 'A' does something`  
And obviously I did not want to have to do something like 
` eval ("browser" + "A").$('#someSelector').click()`  
Because `eval()` is a nasty dangerous hack.  
So I feel that it would be worthwhile pointing out in the multiremote page [here](https://webdriver.io/docs/multiremote/) that you can actually access these browser objects via strings by doing `browser["browser" + "A"].$('#someSelector').click()` - it took me a while to figure this out.

**Comment by christian-bromann** [comment]
@evilC would you like to take a stab at it and propose a change to the docs?

**Comment by evilC** [comment]
Well I am kind of new to wdio, so was unsure as to where to put it.
Would this be solely applicable to the "Using WDIO Testrunner" section, or would it be of use also in standalone mode?

**Comment by christian-bromann** [comment]
@evilC this would be also the case for standalone mode

**Comment by evilC** [comment]
Done
https://github.com/webdriverio/webdriverio/pull/6755

**Comment by evilC** [comment]
Oh, and a quick question if I may - is there a simple way to get a list of browser instances?
I currently parse the `wdio.conf.js` file like so, but it feels a bit hacky  

given
```js
  capabilities: {
    browserA: {
      capabilities: {
        browserName: "chrome",
        "goog:chromeOptions": {
          args: ["use-fake-ui-for-media-stream"],
        },
      },
    },
    browserB: {
      capabilities: {
        browserName: "chrome",
        "goog:chromeOptions": {
          args: ["use-fake-ui-for-media-stream"],
        },
      },
    },
  },
```

```js
https://github.com/webdriverio/webdriverio/pull/6755

// ...

      this.browsers = {};
      let caps = config.config.capabilities;
      for (const [key, value] of Object.entries(caps)) {
        let browserId = key.match(/browser(.)/)[1];
        this.browsers[browserId] = browser[key];
      }
```

Thus giving me an object with two keys: `A` which points to `browserA` and `B` which points to `browserB`  
ie is there a better way of obtaining the strings `browserA` and `browserB` ?

**Comment by christian-bromann** [comment]
@evilC yes, try `browser.instances`

**Comment by christian-bromann** [comment]
I incorporated this information into your PR. If you sign the CLA we can go ahead and merge it. Thanks a lot!

**Comment by evilC** [comment]
D'oh, I swear I had looked for that, obviously not. Is this maybe worth adding to the documentation too?

**Comment by christian-bromann** [comment]
> Is this maybe worth adding to the documentation too?

As I mentioned in my previous comment I did in your PR 😉
