### ISSUE TITLE
wdio.conf.js is not created by command npx wdio config

### ISSUE THREAD

**Issue by amodmahajan2016** [webdriverio/webdriverio#6757]
Node version - 

C:\Users\aadit>node -v
v14.16.1

Npm version-
C:\Users\aadit>npm -v
6.14.12

### Steps to reproduce
1. npm install --save-dev @wdio/cli
2. npx wdio config
=========================
WDIO Configuration Helper
=========================

? Where is your automation backend located? On my local machine
? Which framework do you want to use? mocha
? Are you using a compiler? No!
? Where are your test specs located? ./test/specs/**/*.js
? Do you want WebdriverIO to autogenerate some test files? Yes
? Do you want to use page objects (https://martinfowler.com/bliki/PageObject.html)? Yes
? Where are your page objects located? ./test/pageobjects/**/*.js
? Which reporter do you want to use? spec
? Do you want to add a service to your test setup? chromedriver
? What is the base url? http://localhost

Error - Error: null
    at runConfig (C:\AmodMahajan\WdioLearning\node_modules\@wdio\cli\build\commands\config.js:101:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

### Package.json
`{
  "name": "wdio-testing",
  "version": "1.0.0",
  "description": "Learn WebDriverIO",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "Automation",
    "WebDriverIO"
  ],
  "author": "Amod",
  "license": "ISC",
  "devDependencies": {
    "@wdio/cli": "^7.5.1",
    "@wdio/local-runner": "^7.5.1",
    "@wdio/mocha-framework": "^7.4.6",
    "@wdio/spec-reporter": "^7.4.3",
    "chromedriver": "^90.0.0",
    "wdio-chromedriver-service": "^7.0.0"
  }
}
`

### Complete Log

PS C:\AmodMahajan\WdioLearning> npx wdio config
'"C:\Users\aadit\Downloads\ansi160\x64\ansicon"' is not recognized as an internal or external command,
operable program or batch file.
'"C:\Users\aadit\Downloads\ansi160\x64\ansicon"' is not recognized as an internal or external command,
operable program or batch file.

=========================
WDIO Configuration Helper
=========================

? Where is your automation backend located? On my local machine
? Which framework do you want to use? mocha
? Are you using a compiler? No!
? Where are your test specs located? ./test/specs/**/*.js
? Do you want WebdriverIO to autogenerate some test files? Yes
? Do you want to use page objects (https://martinfowler.com/bliki/PageObject.html)? Yes
? Where are your page objects located? ./test/pageobjects/**/*.js
? Which reporter do you want to use? spec
? Do you want to add a service to your test setup? chromedriver
? What is the base url? http://localhost

Installing wdio packages:
- @wdio/local-runner
- @wdio/mocha-framework
- @wdio/spec-reporter
- wdio-chromedriver-service
- chromedriver
'"C:\Users\aadit\Downloads\ansi160\x64\ansicon"' is not recognized as an internal or external command,
operable program or batch file.
'"C:\Users\aadit\Downloads\ansi160\x64\ansicon"' is not recognized as an internal or external command,
operable program or batch file.

> chromedriver@90.0.0 install C:\AmodMahajan\WdioLearning\node_modules\chromedriver
> node install.js

ChromeDriver binary exists. Validating...
ChromeDriver is already available at 'C:\Users\aadit\AppData\Local\Temp\90.0.4430.24\chromedriver\chromedriver.exe'.
Copying to target path C:\AmodMahajan\WdioLearning\node_modules\chromedriver\lib\chromedriver
Done. ChromeDriver binary available at C:\AmodMahajan\WdioLearning\node_modules\chromedriver\lib\chromedriver\chromedriver.exe
npm WARN wdio-testing@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ wdio-chromedriver-service@7.0.0
+ chromedriver@90.0.0
+ @wdio/spec-reporter@7.4.3
+ @wdio/local-runner@7.5.1
+ @wdio/mocha-framework@7.4.6
updated 5 packages and audited 412 packages in 17.52s

30 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

wdio.js config

Initialize WebdriverIO and setup configuration in your current project.

Options:
      --version          Show version number                           [boolean]
      --watch            Run WebdriverIO in watch mode                 [boolean]
  -h, --hostname         automation driver host address                 [string]
  -p, --port             automation driver port                         [number]
      --path             path to WebDriver endpoints (default "/")      [string]
  -u, --user             username if using a cloud service as automation backend
                                                                        [string]
  -k, --key              corresponding access key to the user           [string]
  -l, --logLevel         level of logging verbosity
                  [choices: "trace", "debug", "info", "warn", "error", "silent"]
      --bail             stop test runner after specific amount of tests have
                         failed                                         [number]
      --baseUrl          shorten url command calls by setting a base url[string]
  -w, --waitforTimeout   timeout for all waitForXXX commands            [number]
  -f, --framework        defines the framework (Mocha, Jasmine or Cucumber) to
                         run the specs                                  [string]
  -r, --reporters        reporters to print out the results on stdout    [array]
      --suite            overwrites the specs attribute and runs the defined
                         suite                                           [array]
      --spec             run only a certain spec file - overrides specs piped
                         from stdin                                      [array]
      --exclude          exclude certain spec file from the test run - overrides
                         exclude piped from stdin                        [array]
      --mochaOpts        Mocha options
      --jasmineOpts      Jasmine options
      --cucumberOpts     Cucumber options
      --autoCompileOpts  Auto compilation options
      --yarn             Install packages via yarn package manager.
                                                      [boolean] [default: false]
  -y, --yes              will fill in all config defaults without prompting
                                                      [boolean] [default: false]
      --help             Show help                                     [boolean]

Documentation: https://webdriver.io
@wdio/cli (v7.5.1)

Error: null
    at runConfig (C:\AmodMahajan\WdioLearning\node_modules\@wdio\cli\build\commands\config.js:101:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by christian-bromann** [comment]
Thanks for filing the issue.

It seems that installing dependencies has failed for unknown reasons. I've addressed the bad error message in #6758. Please retry installing the dependencies. If it fails again please check the stdout/stderr for errors.

**Comment by amodmahajan2016** [comment]
@christian-bromann Yeah I can see error messages and tried installing those dependencies manually. I assume once all dependencies are in place then conf file should have created which is not happening. I feel the setup and installation of a tool should not be difficult this much.

**Comment by christian-bromann** [comment]
> I feel the setup and installation of a tool should not be difficult this much.

It usually isn't .. if you can tell me more about the error that you are seeing when installing dependencies manually because without this error everything would have gone just fine.

**Comment by amodmahajan2016** [comment]
### When I run below command-
C:\AmodMahajan\WdioLearning> npx wdio config
=========================
WDIO Configuration Helper
=========================

? Where is your automation backend located? On my local machine
? Which framework do you want to use? mocha    
? Are you using a compiler? No!
? Where are your test specs located? ./test/specs/**/*.js        
? Do you want WebdriverIO to autogenerate some test files? Yes
? Do you want to use page objects (https://martinfowler.com/bliki/PageObject.html)? Yes
? Where are your page objects located? ./test/pageobjects/**/*.js
? Which reporter do you want to use? spec
? Do you want to add a service to your test setup? chromedriver
? What is the base url? http://localhost

Installing wdio packages:
- @wdio/local-runner@latest
- @wdio/mocha-framework@latest
- @wdio/spec-reporter@latest
- wdio-chromedriver-service
- chromedriver
'"C:\Users\aadit\Downloads\ansi160\x64\ansicon"' is not recognized as an internal or external command,
operable program or batch file.
'"C:\Users\aadit\Downloads\ansi160\x64\ansicon"' is not recognized as an internal or external command,
operable program or batch file.

> chromedriver@90.0.0 install C:\AmodMahajan\WdioLearning\node_modules\chromedriver
> node install.js

ChromeDriver binary exists. Validating...
ChromeDriver is already available at 'C:\Users\aadit\AppData\Local\Temp\90.0.4430.24\chromedriver\chromedriver.exe'.
Copying to target path C:\AmodMahajan\WdioLearning\node_modules\chromedriver\lib\chromedriver
Done. ChromeDriver binary available at C:\AmodMahajan\WdioLearning\node_modules\chromedriver\lib\chromedriver\chromedriver.exe
npm WARN wdio-testing@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @wdio/spec-reporter@7.5.2
+ chromedriver@90.0.0
+ @wdio/local-runner@7.5.2
+ wdio-chromedriver-service@7.0.0
+ @wdio/mocha-framework@7.5.2
updated 7 packages and audited 438 packages in 24.467s

30 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

wdio.js config

Initialize WebdriverIO and setup configuration in your current project.

Options:
      --version          Show version number                           [boolean]
      --watch            Run WebdriverIO in watch mode                 [boolean]
  -h, --hostname         automation driver host address                 [string]
  -p, --port             automation driver port                         [number]
      --path             path to WebDriver endpoints (default "/")      [string]
  -u, --user             username if using a cloud service as automation backend
                                                                        [string]
  -k, --key              corresponding access key to the user           [string]
  -l, --logLevel         level of logging verbosity
                  [choices: "trace", "debug", "info", "warn", "error", "silent"]
      --bail             stop test runner after specific amount of tests have
                         failed                                         [number]
      --baseUrl          shorten url command calls by setting a base url[string]
  -w, --waitforTimeout   timeout for all waitForXXX commands            [number]
  -f, --framework        defines the framework (Mocha, Jasmine or Cucumber) to
                         run the specs                                  [string]
  -r, --reporters        reporters to print out the results on stdout    [array]
      --suite            overwrites the specs attribute and runs the defined
                         suite                                           [array]
      --spec             run only a certain spec file - overrides specs piped
                         from stdin                                      [array]
      --exclude          exclude certain spec file from the test run - overrides
                         exclude piped from stdin                        [array]
      --mochaOpts        Mocha options
      --jasmineOpts      Jasmine options
      --cucumberOpts     Cucumber options
      --autoCompileOpts  Auto compilation options
      --yarn             Install packages via yarn package manager.
                                                      [boolean] [default: false]
  -y, --yes              will fill in all config defaults without prompting
                                                      [boolean] [default: false]
      --help             Show help                                     [boolean]

Documentation: https://webdriver.io
@wdio/cli (v7.5.2)

Error: An unknown error happened! Please retry installing dependencies via "npm i --save-dev @wdio/local-runner@latest @wdio/mocha-framework@latest @wdio/spec-reporter@latest wdio-chromedriver-service chromedriver"
    at runConfig (C:\AmodMahajan\WdioLearning\node_modules\@wdio\cli\build\commands\config.js:104:15)

After this, I explicitly download the required dependencies and run the same command "npx wdio config" but get the same error. How can I create now wdio.conf.js file now?

**Comment by christian-bromann** [comment]
Do you see any errors when installing the deps manually?

**Comment by amodmahajan2016** [comment]
No. they are installed properly.
