### ISSUE TITLE
Legacy syntax with function(err, data) apparently cloning references instead of keeping original objects from function closures

### ISSUE THREAD

**Issue by marco-faustinelli** [webdriverio/webdriverio#676]
I'm encountering a very strange error while trying to use the legacy syntax with callback arg rather than promise.then. Steps are:
1) the callback contains in its closure a reference to an external object
2) the callback modifies the object during its run
3) **the external object should be modified, but actually it's not**

The simplest working example of the mechanism I want to use is this (just run it in a console):

    var obj = {};
    function modifier(ref) { return function(key,value) { ref[key] = value } };
    modifier(obj)('chiave',123123);

    obj → { chiave: 123123 } // obj is mutated

In the case that I am documenting here, mutation is NOT happening and the original obj remains empty.

Going back to webdriverio, the call I want to execute is

    elements(selector, function(err, data) { .. .. .. .. })

I prepare the callback through a two-step valorisation. The complete code is:

    function statefulLogFun(state) {
      return function(extractor, fieldName) {
        return function(err, data) { // this will be the callback
          var value;
          if (!err) {
            value = extractor(data);
            state[fieldName] = value;
          }
          _timestampedLog(true, 
            err ? 'ERROR: state[\'' + fieldName + '\'] not set!' : 'this.state = ' + JSON2.stringify(state));
        }
      }
    }

The first layer is valorised inside the beforeEach method (I am using Mocha):

    this.state = {}; // 'this' is the test itself
    helper.statefulLog = helper.statefulLogFun(this.state); // statefulLog(extractor, fieldName)

The second layer is valorised inside the test:

    client
      .elements('#listAdUnit tbody tr', helper.statefulLog(function(data){return data.value.length;}, 'adUnitsNumber'))

After this step I expect that 

    this.state = { adUnitsNumber: <value from elements>}

During the run of the test I am logging everything and I can see that:
1) the callback receives an empty object
2) the callback adds the couple key-value correctly (see call to JSON2.stringify)
3) the original this.state remains empty

What is happening here? Thank you for your attention.

**Comment by christian-bromann** [comment]
@marco-faustinelli ugh this is pretty complex and I am not sure if I fully understand what you are trying to do here and if this is an problem with WebdriverIO. One mistake I often made when changing objects in the callback is that I missed that everything is running asynchronous. So make sure `this.state` is called when the command is done.

**Comment by marco-faustinelli** [comment]
Hello Christian,

I have a pretty solid experience with mutating JS objects in asynch situations. The key of my reasoning is in what I call "two-step valorisation". Have you tried to run in console the first simple example I am providing? 

That simple example is mapped exactly into the complex real case. I reckon that viewing the console run of the simple should allow you to "see" the problem I am experiencing with `client.elements`: the callback closes on `this.state` and I __know__ that the callback is run in the course of the `client.elements` invocation (I suppose it runs __after__ the command is done, but I haven't checked the source code ;-). NB: `helper` is merely a namespace. 

But it looks like the callback is operating on a clone of `this.state`, not on the real thing.

Christian, I understand this is a nasty case and it may cost you more time than the average request. That's why am asking you how can I assist. Possibly I should delve into the source code, but I must admit that the new monadic version is kinda hostile to my comprehension :-(

Questions are:

* Does the problem lie in the fact that I try to stick to the older syntax and not use `.then()`?

* Is it possible that the code that maintains the backward compatibility of the old syntax is handling parameters differently than the promise-based code?

I am really puzzled because to me closures are sacred things that JS to my knowledge has always handled correctly, but this is a major problem for me.

Please try at least to run the simple example. Today I will have a look at how to prepare a testcase to submit.

Thank you very much for your attention.

**Comment by marco-faustinelli** [comment]
OK, eventually I got to the end of all this and it's not webdriverio. Thank you for your attention.
