### ISSUE TITLE
Ability to extend page load timeouts for performance testing

### ISSUE THREAD

**Issue by constantine-photoshelter** [webdriverio/webdriverio#6763]
**Is your feature request related to a problem? Please describe.**
We are running performance testing that looks something like this:
browser.enablePerformanceAudits();
loginPage.open(); // this function opens a login page using browser.url();
loginPage.login();// this function enters credentials, presses logging, and validates that the page redirected as expected
libraryPage.open(path);//This opens a page using browser.url();
browser.getMetrics(); is then called.

The libraryPage that we open after loggin in typically takes between 10-20 seconds to load under normal circumstances. With the throttling from performance testing using default values, that load time is over a minute and we get an error that reads: Couldn't capture performance due to: Page with url "<page_URL>" failed to load
waitforTimeout and connectionRetryTimeout are both set to 90000, so the test breaking at about 60,000ms is unexpected.

**Describe the solution you'd like**
A way to set the timeout for a page load when using performance testing.

**Describe alternatives you've considered**
We've tried extending every other possible timeout we could look into and have been unable to get the performance metrics consistently. It is very rare for the page to load within the allotted time.

**Comment by christian-bromann** [comment]
> waitforTimeout and connectionRetryTimeout are both set to 90000, so the test breaking at about 60,000ms is unexpected.

There are many types of timeouts in WebdriverIO. You can read more about it in [the docs](https://webdriver.io/docs/timeouts/). The timeout that you see breaking your tests are framework specific timeouts.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by constantine-photoshelter** [comment]
Sorry to have posted in the wrong place. I assumed incorrectly that I had experimented with all available timeouts. Thank you for your helps.
