### ISSUE TITLE
issue when set cookie in Chrome version 90.0.4430.24

### ISSUE THREAD

**Issue by fcarrasco92** [webdriverio/webdriverio#6766]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.16.15
 - **Mode:** Standalone mode
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.x
 - **NPM version:** 6.14.8
 - **Browser name and version:**  90.0.4430.24
 - **Platform name and version:** macOS Catalina version 10.15.7 
 - **Additional wdio packages used (if applicable):** "@wdio/allure-reporter": "^5.16.11",
        "@wdio/appium-service": "^5.16.11",
        "@wdio/cli": "^5.16.15",
        "@wdio/devtools-service": "^5.16.10",
        "@wdio/jasmine-framework": "^5.16.15",
        "@wdio/local-runner": "^5.16.15",
        "@wdio/selenium-standalone-service": "^5.16.10",
        "@wdio/spec-reporter": "^5.16.11",
        "@wdio/sync": "^5.16.15",

**Config of WebdriverIO**
Initial setup

**Describe the bug**
When run the execution there is a problem how to set cookie

**To Reproduce**
open browser 
set cookie
show the following error: webdriver: Request failed due to invalid cookie domain: invalid cookie domain: Cookie 'domain' mismatch
![image](https://user-images.githubusercontent.com/5995491/116292178-67341700-a763-11eb-8c21-808e4e2dd579.png)

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Log**
capabilities: {
    alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'chrome', 'goog:chromeOptions': { args: [Array] } }
}
[0-0] DEPRECATION: An asynchronous before/it/after function took a done callback but also returned a promise. This is not supported and will stop working in the future. Either remove the done callback (recommended) or change the function to not return a promise.
[0-0] 2021-04-27T18:04:12.010Z INFO webdriver: COMMAND navigateTo("https://uat.sodimac.cl/sodimac-cl/search?Ntt=toallas")
[0-0] 2021-04-27T18:04:12.010Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session/6afa557e6e67379771199e2dbc1a08ea/url
[0-0] 2021-04-27T18:04:12.011Z INFO webdriver: DATA { url: 'https://uat.sodimac.cl/sodimac-cl/search?Ntt=toallas' }
[0-0] 2021-04-27T18:04:13.483Z INFO webdriver: COMMAND addCookie(<object>)
[0-0] 2021-04-27T18:04:13.483Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session/6afa557e6e67379771199e2dbc1a08ea/cookie

0-0] 2021-04-27T18:04:13.492Z DEBUG webdriver: request failed due to response error: invalid cookie domain
[0-0] 2021-04-27T18:04:13.493Z WARN webdriver: Request failed due to invalid cookie domain: Cookie 'domain' mismatch
  (Session info: headless chrome=90.0.4430.85)
[0-0] 2021-04-27T18:04:13.500Z DEBUG webdriver: request failed due to response error: invalid cookie domain
[0-0] 2021-04-27T18:04:13.500Z INFO webdriver: Retrying 2/3
**Additional context**
![image](https://user-images.githubusercontent.com/5995491/116292458-b9753800-a763-11eb-954f-9c125299204d.png)

**Comment by jayrepo** [comment]
Check release note of chromedriver v90: https://chromedriver.storage.googleapis.com/90.0.4430.24/notes.txt. You are not able to set cookie for a different domain starting from v90.

**Comment by christian-bromann** [comment]
Thanks @jayrepo for this information. Didn't know this either.

**Comment by fcarrasco92** [comment]
Hi @jayrepo 

I don't understand the problem, because this configuration for the cookie.

cookie: {
    name: 'CF_Authorization',
    value: 'eyJhbGciOiJSUzI1NiIsImtpZCI6ImUxMjI1MWRmODQ5MjM1NDRjY2IwNGNkZGJjMWMzMGM3ODRlOGY4NWI4NWI0NGM2N2NhZWQ5ODFjNTVjOTZkNmUifQ.eyJhdWQiOlsiZjRiNjYzZTNlYjU2ODJjM2E1YjY1MzBiZjg3ZGY4Y2I4OGU0ODYwZDhhMGY4NGI3YTFmN2U3M2NkZmY1Y2NkNiJdLCJlbWFpbCI6ImV4dF9sZmNhcnJhc2NvZ0BGYWxhYmVsbGEuY2wiLCJleHAiOjE2MTk2MjI4ODIsImlhdCI6MTYxOTUzNjQ4MiwibmJmIjoxNjE5NTM2NDgyLCJpc3MiOiJodHRwczovL2ZiLmNsb3VkZmxhcmVhY2Nlc3MuY29tIiwidHlwZSI6ImFwcCIsImlkZW50aXR5X25vbmNlIjoiTzhHcTVSVjVMbHd0UFhZeSIsInN1YiI6Ijk5NDA1Mjk5LWY3MDgtNGQ3OC1hMGU5LTk3MmZlZjI2YWI1OSIsImNvdW50cnkiOiJDTCJ9.XjWgRNVu7knJnCiaEiJHBl3--dzTLzUARt_uoGF1sQwPyjAXtv1z_bKAs58iLrl0bcN35MoD0z_-4JUbpI9deHyidEvDAdKjULyk9Sa6d3Cyi0mKhAlnmkc1rsqNi3E35Ddyx30O18lfEmoMGyNst_oZEAhQKtdZ1WlaezmKHyV0ZiFRfMalD3nBcU5TAisGM2g70lxlxCiMoNejXWBTGnrT_dxtR_PPn0A4YaWfJyedkr3SfmJIlH4sX2CHjY0TAgNis-swYqPE20rfvTWoyZntVFGGjzUPabi3sAr84tEAqJLWjVRXXWDF0x2MZjC1G3DKnlG2fcMHRTY-ieZCtA',
    domain: 'uat.sodimac.cl'
  }
}

and this is the URL: 'https://uat.sodimac.cl/sodimac-cl/search?Ntt=toallas'
[0-0] 2021-04-28T13:08:16.626Z INFO webdriver: DATA { url: 'https://uat.sodimac.cl/sodimac-cl/search?Ntt=toallas' }


can you give more details or help me?

thanks

**Comment by jayrepo** [comment]
When you open the url, you are redirected to sso page `fb.cloudflareaccess.com`, while you are at this page, you are not able to set cookie for `uat.sodimac.cl` as the domain is different.

And please remove your jwt token, it exposes some sensitive information.
