### ISSUE TITLE
`$$` command doesn't return elements in document order 

### ISSUE THREAD

**Issue by uno-dos** [webdriverio/webdriverio#6779]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.5.3
 - **Mode:** Standalone mode 
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 14.16.1
 - **NPM version:** 7.9.0
 - **Browser name and version:** Chrome 74.0.3729.6
 - **Platform name and version:** macOS 10.15.7
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
`$$` Command doesn't return elements in document order when using CSS selector.

**To Reproduce**
Have a sample DOM which looks like this:
```
...
<div test-id='xyz-1a'>
<div test-id='xyz-1b'>
<div test-id='xyz-1c'>
<div test-id='xyz-2d'>
...
```
Then run the following command:
`$$("[test-id*='xyz-']");` 

Result: `$$` command returns elements in random order.

**Expected behavior**
`$$` command should return elements in document order.

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
> `$$` command should return elements in document order.

Why? Where is this defined? WebdriverIO returns what it receives from Protractor or the WebDriver protocol depending what you run. If you desire to select elements by their alphabetical order of that attribute you can do things like `$$("[test-id*='xyz-']").sort((e) => e.getAttribute("test-id"))`.

I am gonna close this as again, WebdriverIO just forwards what it gets from the automation protocol underneath. I understand though that it seems odd these elements are not in their alphabetical order based on the selector.
