### ISSUE TITLE
"Error [ERR_STREAM_WRITE_AFTER_END]: write after end" after 7.5.3 upgrade

### ISSUE THREAD

**Issue by jweingarten** [webdriverio/webdriverio#6787]
Since we picked up 7.5.3 our parallel running Chrome/Saucelabs tests are failing randomly with `Error [ERR_STREAM_WRITE_AFTER_END]: write after end`
I know you want reproducible steps, but its extremely difficult to find them as the tests run in parallel. 
I moved our pipeline back to use 7.5.2 and everything is fine again. 

Failing package setup:
```
 00:00:43 + wdio-mochawesome-reporter@4.0.0
00:00:43 + wdio-chromedriver-service@7.0.0
00:00:43 + @wdio/mocha-framework@7.5.3
00:00:43 + chromedriver@90.0.0
00:00:43 + wdio-json-reporter@2.0.0
00:00:43 + @wdio/sauce-service@7.5.3
00:00:43 + @wdio/spec-reporter@7.5.3
00:00:43 + @wdio/cli@7.5.3
00:00:43 + @wdio/sync@7.5.3
00:00:43 + @wdio/dot-reporter@7.5.3
00:00:43 + @wdio/local-runner@7.5.3
00:00:43 + @wdio/junit-reporter@7.5.3 
```

Working package setup:
```
 00:00:40 + wdio-chromedriver-service@7.0.0
00:00:40 + chromedriver@90.0.0
00:00:40 + wdio-mochawesome-reporter@4.0.0
00:00:40 + wdio-json-reporter@2.0.0
00:00:40 + @wdio/spec-reporter@7.5.2
00:00:40 + @wdio/sauce-service@7.5.2
00:00:40 + @wdio/cli@7.5.2
00:00:40 + @wdio/sync@7.5.2
00:00:40 + @wdio/local-runner@7.5.2
00:00:40 + @wdio/mocha-framework@7.5.2
00:00:40 + @wdio/junit-reporter@7.5.2
00:00:40 + @wdio/dot-reporter@7.5.2 
```

i will work on trying to narrow it down.

**Comment by christian-bromann** [comment]
@jan-molak maybe related to your changes?

**Comment by jan-molak** [comment]
@jweingarten would you be able to keep the package versions as they were in your working setup and update just the local runner to 7.5.3 so we could try to narrow it down?

**Comment by jweingarten** [comment]
So only update `@wdio/local-runner` ? I can try that. Yes.

**Comment by jweingarten** [comment]
``` 00:00:39 + wdio-chromedriver-service@7.0.0
00:00:39 + wdio-mochawesome-reporter@4.0.0
00:00:39 + @wdio/mocha-framework@7.5.2
00:00:39 + @wdio/dot-reporter@7.5.2
00:00:39 + wdio-json-reporter@2.0.0
00:00:39 + @wdio/spec-reporter@7.5.2
00:00:39 + chromedriver@90.0.0
00:00:39 + @wdio/sauce-service@7.5.2
00:00:39 + @wdio/junit-reporter@7.5.2
00:00:39 + @wdio/cli@7.5.2
00:00:39 + @wdio/local-runner@7.5.3
00:00:39 + @wdio/sync@7.5.2 
```
It fails with this setup. Not every time, but it does. 
My reporters in the config are set to `reporters: ['spec', 'json'],`. When it fails the `wdio-x-x-json-reporter.log` is empty and the `wdio-x-x.log` seems fine. 
The `wdio.log` also seems fine.

**Comment by jan-molak** [comment]
Thanks, I just managed to reproduce it locally too. Let me have a look.

**Comment by jweingarten** [comment]
Just FYI, when I see the failure my tests actually did not have any failures. Glad you found a way to reproduce it.
