### ISSUE TITLE
Error [ERR_REQUIRE_ESM] upgrading from v6 to v7 

### ISSUE THREAD

**Issue by dadamschi** [webdriverio/webdriverio#6789]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7 (from v6)
 - **Mode:** TestRunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** v16.0.0
 - **NPM version:** 7.10.0
 - **Browser name and version:** Chrome 89
 - **Platform name and version:** MacOS
 - **Additional wdio packages used (if applicable):**    
  "@wdio/cli": "7",
    "@wdio/codemod": "^0.8.11",
    "@wdio/cucumber-framework": "7",
    "@wdio/sync": "7",
    "@wdio/allure-reporter": "^6.4.5",
    "@wdio/junit-reporter": "^6.4.0",
    "@wdio/local-runner": "7",
    "@wdio/mocha-framework": "^6.4.0",
    "@wdio/sauce-service": "^6.4.5",
    "@wdio/selenium-standalone-service": "^6.4.0",
    "wdio-chromedriver-service": "7",
    "wdio-json-reporter": "^2.0.0",
    "@wdio/allure-reporter": "^6.4.5",
    "@wdio/junit-reporter": "^6.4.0",
    "@wdio/local-runner": "7",
    "@wdio/mocha-framework": "^6.4.0",
    "@wdio/sauce-service": "^6.4.5",
    "@wdio/selenium-standalone-service": "^6.4.0",
    "@wdio/spec-reporter": "7"

**Config of WebdriverIO**
I am using the default config and using an environment override (e.g. wdio.staging.config.js)

**Describe the bug**
I am getting a number of JS error (I think) when upgrading from v6 to v7. Upgrading my version of Node was required as I was at v12.13 which wasn't supported by v7.

**To Reproduce**
* I am using a boilerplate project (https://webdriver.io/docs/boilerplates/#serhatbolsuwebdriverio-mocha-uiautomation-boiler) 
* I followed the upgrade steps in https://webdriver.io/docs/v7-migration/
* added `"type": "module"` to package.json
* added 
```
"scripts": {
    "test": "wdio wdio.staging.conf.js"
}
``` 
in package.json
* when trying to run my tests (`yarn test`) I get the following error(s):
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/dadams/work/experimental/webdriverio-framework/wdio.staging.conf.js
require() of ES modules is not supported.
require() of /Users/dadams/work/experimental/webdriverio-framework/wdio.staging.conf.js from /Users/dadams/work/experimental/webdriverio-framework/node_modules/@wdio/config/build/lib/FileSystemPathService.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename wdio.staging.conf.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/dadams/work/experimental/webdriverio-framework/package.json.

    at new NodeError (node:internal/errors:363:5)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1125:13)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at FileSystemPathService.loadFile (/Users/dadams/work/experimental/webdriverio-framework/node_modules/@wdio/config/build/lib/FileSystemPathService.js:22:16)
    at ConfigParser.addConfigFile (/Users/dadams/work/experimental/webdriverio-framework/node_modules/@wdio/config/build/lib/ConfigParser.js:40:46)
    at new Launcher (/Users/dadams/work/experimental/webdriverio-framework/node_modules/@wdio/cli/build/launcher.js:42:27)
    at launch (/Users/dadams/work/experimental/webdriverio-framework/node_modules/@wdio/cli/build/commands/run.js:125:22)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**
I am able to upgrade and then run tests

**Additional context**
I did upgrade Node to v16 which may have something to do with these issues. I did try the "instead" steps individually and those were not working for me.

**Comment by christian-bromann** [comment]
WebdriverIO is not yet compatible as ESM module. We have a project for this created in [#17](https://github.com/webdriverio/webdriverio/projects/17). Any contributions to make this possible would be very appreicated.

**Comment by christian-bromann** [comment]
@dadamschi please follow #6812 for updates on ESM support. Unfortunately we are currently blocked as our stack uses Jest which is not yet fully ESM compatible the way we need it to be.
