### ISSUE TITLE
Example in newWindow documentation doesn't work

### ISSUE THREAD

**Issue by Joozty** [webdriverio/webdriverio#6797]
**Pre-check**
- [ x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [ x] Unclear documentation
- [ ] A typo
- [ ] Missing documentation
- [ ] Other

**Description of the improvement / report**
A clear and concise description.

Example provided on [newWindow doc page](https://webdriver.io/docs/api/browser/newWindow/) doesn't work. When I run it it closes all the windows. I had to use [this code instead](https://github.com/webdriverio/webdriverio/issues/3270#issuecomment-451999597). So I guess it's just a mistake or am I doing something wrong?

**Comment by erwinheitzman** [comment]
You linked to the `newWindow` command. When reading your description I think you meant to reference to closeWindow, can you share if this is the case and if so, please update the issue?

**Comment by Joozty** [comment]
The link is correct. Example present there contains closeWindow command which is problematic and should be updated to something like this:


```js
	it('should open a new tab', () => {
		browser.url('https://google.com')
		console.log(browser.getTitle()) // outputs: "Google"

		browser.newWindow('https://webdriver.io', {
			windowName: 'WebdriverIO window',
			// windowFeature: 'width=420,height=230,resizable,scrollbars=yes,status=1',
		})
		console.log(browser.getTitle()) // outputs: "WebdriverIO · Next-gen browser and mobile automation test framework for Node.js"

		const handles = browser.getWindowHandles()
		if (handles.length > 1) {
			browser.switchToWindow(handles[1])
			browser.closeWindow()
			browser.switchToWindow(handles[0])
		}
		console.log(browser.getTitle()) // outputs: "Google"
	})
 ```

**Comment by christian-bromann** [comment]
@Joozty would you mind raising a PR and updating the example?
