### ISSUE TITLE
error on Protocol of selectorExecuteAsync or executeAsync

### ISSUE THREAD

**Issue by idoaizenshtein** [webdriverio/webdriverio#683]
Hello,

I use webdriver.io and try to incorporate reading ajax after the page is ready ...
I try to use the Protocol of selectorExecuteAsync or executeAsync but whenever I get the following error:
"webdriverInstance.eventHandler.removeEventListener = removeEventListener (t
                                                        ^
TypeError: Can not set property 'removeEventListener' of undefined"

The code examples are in your documentation:
I also try the code snippet example 3 returned to this page:
http://selenium.googlecode.com/git-history/facb1dcca95e8050ab349e5b288ed95377962d37/docs/api/javascript/class_webdriver_WebDriver.html

And you get the same mistake I made before.
```js
  driver.executeAsyncScript (function () {
    var callback = arguments [arguments.length - 1];
    var xhr = new XMLHttpRequest ();
    xhr.open ("GET", "/resource/data.json", true);
    xhr.onreadystatechange = function () {
      if (xhr.readyState == 4) {
        callback (xhr.resposneText);
      }
    }
    xhr.send ('');
  }). then (function (str) {
    console.log (JSON.parse (str) ['food']);
  });
```
I try the code as it is in the following example:
http://webdriver.io/api/protocol/executeAsync.html

```js
client
     .timeoutsAsyncScript (5000)
     .executeAsync (function (a, b, c, d, done) {
         setTimeout (function () {
             done (a + b + c + d);
         }, 3000);
     }, 1, 2, 3, 4) .then (function (ret) {
         console.log (ret.value); // Outputs: 10
     });
```
I use a Mac, and ChromeDriver.

**Comment by christian-bromann** [comment]
@idoaizenshtein according to your problem description it seems that you are using selenium-webdriver and not WebdriverIO. This library doesn't have a command called executeAsyncScript

**Comment by idoaizenshtein** [comment]
No ... as I wrote I tried the selenium and the WebdriverIO as I wrote in the second example ...
And both of them are not working ...

**Comment by idoaizenshtein** [comment]
No ... as I wrote I tried the selenium and the WebdriverIO as I wrote in the second example ...
And both of them are not working ...


Ido Aizenshtein
Web & App Developer

Cell: 972-52-3991133
Office: 972-3-5610382
Fax: 972-3-6844889
Mail: ido@bizibox.biz
Adress: Yehuda and Noah Moses St 13, Tel Aviv
Zipcode: 6744252 
Company: Ifact Ltd
Website: www.bizibox.biz

**Comment by christian-bromann** [comment]
@idoaizenshtein can you provide a gist that reproduces the error?

**Comment by idoaizenshtein** [comment]
RuntimeError: POST /session//timeouts/async_script
Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
System info: host: 'h-MacBook-Pro-sl-ido.local', ip: '10.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_51'
Driver info: driver.version: unknown 
    at executeAsync(<Function>, 1, 2, 3, 4) at /Users/idoaizenshtein/webdriverio-test/test.js:29:3 

The error comes after the following function:
client
	.timeoutsAsyncScript (5000)
	.executeAsync (function (done) {
	var xhr = new XMLHttpRequest ();
	xhr.open ("GET", "http://www.w3schools.com/website/customers_mysql.php", true);
	xhr.onreadystatechange = function () {
		if (xhr.readyState == 4) {
			done(xhr.resposneText);
		}
	}
	xhr.send('');
}).then (function (ret) {
	console.log (ret); // Outputs: 10
});
