### ISSUE TITLE
Getting an error when running "npx wdio config" command

### ISSUE THREAD

**Issue by guruprasadsr2805** [webdriverio/webdriverio#6834]
**Environment (please complete the following information):**
 - **WebdriverIO version: 7.5.6
 - **Mode: WDIO Testrunner
 - **If WDIO Testrunner, running sync/async: sync/async
 - **Node.js version: 15.6.0
 - **NPM version: 7.11.2

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
I created a new project with "npm init -y" and installed wdio cli with "npm install --save-dev @wdio/cli". When I tried to create config using the "npx wdio config" command, I am getting an error.

![image](https://user-images.githubusercontent.com/54303816/117288623-51bc9c80-ae89-11eb-9ce1-990d3fb474f6.png)

**Comment by christian-bromann** [comment]
This is fixed in #6833
