### ISSUE TITLE
Mobile Device "setValue()" - unknown error: 'value' must be a list

### ISSUE THREAD

**Issue by fabianschmider** [webdriverio/webdriverio#6847]
Webdriver IO is using Saucelabs to run the tests.
Actually I run a mobile device for my test:
{
        base: 'SauceLabs',
        browserName: 'chrome',
        appiumVersion: '1.9.1',
        deviceName: 'Samsung Galaxy S9 WQHD GoogleAPI Emulator',
        deviceOrientation: 'portrait',
        version: '9.0',
        platform: 'Android'
}

If I want to set a text with "element.setValue("abc");"
then the error comes up:
Error: An unknown server-side error occurred while processing the command. Original error: unknown error: 'value' must be a list

I tried this already (set text in a list) - but I get the same error:
https://github.com/appium/appium/issues/12059

I found some issues regarding this error - but not sure how to solve this.

https://github.com/webdriverio/webdriverio/pull/3428
https://github.com/webdriverio/webdriverio/pull/3347

Have anyone solved this issue already?
Thanks for your answers!

**Comment by christian-bromann** [comment]
@fabianschmider which Appium version are you using and what is the Chromedriver version? Can you provide some logs as well?

**Comment by fabianschmider** [comment]
Hi @christian-bromann,
AppiumVersion: **1.9.1**
Chrome: with Saucelabs: **browserName: 'chrome'** (I think this should be the latest version)
Logs: [logs.txt](https://github.com/webdriverio/webdriverio/files/6491439/logs.txt)

**Comment by wswebcreation** [comment]
@Fabianopb 

Please try to use a newer version of Appium. 1.9.1 does not support Android 9.
You can for example use 1.20.1. Can you verify if it works after changing to a newer version?

**Comment by fabianschmider** [comment]
Hi @wswebcreation ,
yes - with a higher version of appium all works fine.
Thank you very much!!

Fabian Schmider
