### ISSUE TITLE
spec reporter - flag to print only failed tests in summary

### ISSUE THREAD

**Issue by unickq** [webdriverio/webdriverio#6849]
**Is your feature request related to a problem? Please describe.**
I think sometimes it might be useful to see only failed specs output in summary

**Describe the solution you'd like**
A flag in the config.
```
      "spec",
      {
        symbols: { passed: "[+]", skipped: "[/]", failed: "[-]" },
        onlyFailed true,
      },
```

**Comment by christian-bromann** [comment]
Seams like a reasonable request, would you like to take a stab at it?

**Comment by unickq** [comment]
Yep, done in https://github.com/webdriverio/webdriverio/pull/6852

**Comment by christian-bromann** [comment]
Let's continue convo in #6852
