### ISSUE TITLE
Comparison with Intern / Leadfoot

### ISSUE THREAD

**Issue by dandv** [webdriverio/webdriverio#685]
I was curious, how does WebdriverIO compare with Intern? From what I've learned so far,

* WebdriverIO is just a Webdriver client for Node.JS and lets you use test runners like Jasmine, Cucumber or Mocha, while Intern implements their own test runner with chai-as-promised assertions, and tests written in other frameworks [have to be converted](https://theintern.github.io/intern/#custom-interfaces)
* Intern implements their own Webdriver client called [Leadfoot](https://theintern.github.io/leadfoot/), which claims to be the most comprehensively tested Webdriver client, and to normalize the bugs that Webdriver servers have:

    > Leadfoot is also the only WebDriver client library that includes an exhaustive unit test suite that verifies that results are consistently returned from all remote drivers. Through this test suite we have discovered and reported over 15 defects to upstream WebDriver server implementers.

* WebdriverIO has a simpler syntax [than Leadfoot's Command object](https://theintern.github.io/intern/#writing-functional-test)

How accurate is this? I'm very new to both projects.

There's also a [related StackOverflow question](http://stackoverflow.com/questions/28742069/leadfoot-vs-webdriver-io-javascript-client-library-for-selenium-webdriver-api).

**Comment by christian-bromann** [comment]
Haven't used Leadfoot, here is what I am thinking:

> while Intern implements their own test runner

WebdriverIO has its own test runner too, called `wdio`

> normalize the bugs that Webdriver servers have

This sounds promising but it is just a phrase. You will have to deal with weird Selenium behaviour like in other libraries too. There are couple of things you can workaround but WebdriverIO as well as other frameworks do that too they just don't advertise with it that much. Each vendor driver has its bugs and it is impossible to have a workaround for all those. Most importantly, all these workarounds are implemented in a way that they [inject javascript](team management info directive) to simulate the Selenium command which does _not_ work on mobile :wink: 

> WebdriverIO has a simpler syntax than Leadfoot's Command object

I guess this depends on the developer. (I would agree though :wink:)

**Comment by dandv** [comment]
> WebdriverIO has its own test runner too, called wdio

Correct. I meant WebdriverIO doesn't have its own test framework or assertion library - is that accurate?

**Comment by christian-bromann** [comment]
> doesn't have its own test framework

Right. WebdriverIO relies on approved and active developed test frameworks like Mocha, Jasmine and Cucumber

> or assertion library

Also right. WebdriverIO should be as framework agnostic as possible

**Comment by christian-bromann** [comment]
Closing. I guess most helpful would be a blog post we could reference to. Unfortunately as a maintainer of WebdriverIO I can't write such a blog post. But I will keep my eyes open for stuff like this.

**Comment by dandv** [comment]
I wrote a blog post, and one of the sections may be interesting:

[Node.JS WebDriver client libraries compared](http://wiki.dandascalescu.com/howtos/Comparison_of_Node_js_Selenium_Webdriver_client_libraries#WebdriverIO)

**Comment by jchristi** [comment]
Updated link: [Node.JS WebDriver client libraries compared](http://wiki.dandascalescu.com/howtos/from_zero_to_automated_web_app_testing_best_practices#Node.JS_WebDriver_client_libraries_compared)
