### ISSUE TITLE
Make Cucumber before/after step hooks trigger before/after wdio hooks

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#6859]
Please see #6838 

Currently if you have an `beforeStep` or `afterStep` hook defined in Cucumber it would trigger the `beforeStep`/`afterStep` WebdriverIO hooks where in reality it should trigger `beforeHook`/`afterHook`.

As this is a breaking change let's plan a fix for v8.

**Comment by jonn-set** [comment]
Thanks for this, @christian-bromann. 

Can we have this fixed in v7 please? Otherwise we will have to skip v7 completely and wait for v8, we need scenario tag details in `afterStep` which you were exposing in v6 through `step.scenario`  but was removed in v7, the only way is to get details is from `AfterStep` of cucumber but as soon as we introduce it we see this issue.

**Comment by christian-bromann** [comment]
> Can we have this fixed in v7 please?

Mhm .. this is a breaking change, however probably not many people would be impacted. Do you want to take a stab at this?

**Comment by jonn-set** [comment]
I can have a look but where do I start? `wdio-cucumber-framework`?

**Comment by christian-bromann** [comment]
Yes in particular [cucumberEventListener.ts](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-cucumber-framework/src/cucumberEventListener.ts) and [reporter.ts](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-cucumber-framework/src/reporter.ts)

**Comment by jonn-set** [comment]
Well I was wondering if I can add `scenario` object back into step passed to `afterStep` & `beforeStep`, that will solve my problem TBH. 

I will add it as a function to utils, can call it something like `buildStepDetails` and call it below in `index.js`, will also change the definition in `types.ts`, this way I can get scenario details including tags and someone who's more skilled can fix this issue :)

P.S. _I am not a TS developer._

I will open another feature request and create a PR if you are happy with it. You happy for me go ahead with it? 

**From**:
`index.js`
```typescript 
wrapStep(
    code: Function,
    isStep: boolean,
    config: Options.Testrunner,
    cid: string,
    options: StepDefinitionOptions,
    getHookParams: Function
) {
    return function (this: Cucumber.World, ...args: any[]) {
        const hookParams = getHookParams()
        const retryTest = isStep && isFinite(options.retry) ? options.retry : 0
        /**
         * wrap user step/hook with wdio before/after hooks
         */
        const beforeFn = isStep ? config.beforeStep : config.beforeHook
        const afterFn = isStep ? config.afterStep : config.afterHook
        return testFnWrapper.call(this,
            isStep ? 'Step' : 'Hook',
            { specFn: code, specFnArgs: args },
            { beforeFn: beforeFn as Function[], beforeFnArgs: (context) => [hookParams?.step, context] },
            { afterFn: afterFn as Function[], afterFnArgs: (context) => [hookParams?.step, context] },
            cid,
            retryTest)
    }
}
```

**To**
```typescript
wrapStep(
    code: Function,
    isStep: boolean,
    config: Options.Testrunner,
    cid: string,
    options: StepDefinitionOptions,
    getHookParams: Function
) {
    return function (this: Cucumber.World, ...args: any[]) {
        const hookParams = getHookParams()
        const retryTest = isStep && isFinite(options.retry) ? options.retry : 0
        /**
         * wrap user step/hook with wdio before/after hooks
         */
        const beforeFn = isStep ? config.beforeStep : config.beforeHook
        const afterFn = isStep ? config.afterStep : config.afterHook
        return testFnWrapper.call(this,
            isStep ? 'Step' : 'Hook',
            { specFn: code, specFnArgs: args },
            {
                beforeFn: beforeFn as Function[], beforeFnArgs: (context) => [hookParams ? {
                    'step': hookParams.step,
                    'scenario':
                        {
                            'name': hookParams.scenario.name,
                            'tags': hookParams.scenario.tags,
                            'astNodeIds': hookParams.scenario.astNodeIds
                        }
                } : undefined, context]
            },
            {
                afterFn: afterFn as Function[], afterFnArgs: (context) => [hookParams ? {
                    'step': hookParams.step,
                    'scenario':
                        {
                            'name': hookParams.scenario.name,
                            'tags': hookParams.scenario.tags,
                            'astNodeIds': hookParams.scenario.astNodeIds
                        }
                } : undefined, context]
            },
            cid,
            retryTest)
    }
}
```

**Comment by jonn-set** [comment]
@christian-bromann I think I managed to find a fix for the issue and changes needed is to `index.ts` mainly.

Adding this to `addWdioHooks` function in `index.ts` fixes the execution sequence, I am attaching `passed` object to end of `afterStep` so that we know the test has passed.

```typescript
        Cucumber.BeforeStep(async function wdioHookBeforeStep() {
            const params = eventListener?.getHookParams()
            await executeHooksWithArgs(
                'beforeStep',
                config.beforeStep,
                [params?.uri, params?.feature, params?.scenario, params?.step]
            )
        })
        Cucumber.AfterStep(async function wdioHookAfterStep(world: ITestCaseHookParameter) {
            const params = eventListener?.getHookParams()
            await executeHooksWithArgs(
                'afterStep',
                config.afterStep,
                [params?.uri, params?.feature, params?.scenario, params?.step, { 'passed': world.result?.status === Cucumber.Status.PASSED }]
            )
        })
```

The `wrapStep` function was changing the `beforeStep` & `afterStep` into `beforeHook`/`afterHook` hence were getting execute around the Cucumber `BeforeStep`/`AfterStep`. I had to make some changes to it to make sure `beforeStep`/`afterStep` are ignored.

Please find the changes to `wrapStep` below:
![image](https://user-images.githubusercontent.com/10925588/118405327-580ffd00-b66f-11eb-8cfc-a5440aeb90cb.png)

TBH, I don't fully understand the purpose of the above function hence have kept the changes to a minimum but have changed the name of the function to `wrapHook` as I feel it no longer deals with steps, if that's not the case let me please.

Before I go ahead an make changes to anything else and add tests, can you confirm the purpose of `wrapSteps`, I dont fully understand what a `userHook` is.

Thanks.

**Comment by jonn-set** [comment]
@christian-bromann can you review the changes, I have also tested it by linking the package to my local project.

Below is the order in which it runs:
![image](https://user-images.githubusercontent.com/10925588/118568006-c687b480-b76e-11eb-8360-e9c52c989080.png)

**Comment by sadabnepal** [comment]
@jonn-set I am also facing issue due to 'result' object missing in aferStep argument.  Are you implementing change as mentioned in [afterStep Documentation](https://webdriver.io/docs/options/#afterstep)

**Comment by jonn-set** [comment]
> @jonn-set I am also facing issue due to 'result' object missing in aferStep argument. Are you implementing change as mentioned in [afterStep Documentation](https://webdriver.io/docs/options/#afterstep)

I am changing the 2nd param to be scenario details and 3rd one to be result which is this object, `{passed, error, duration}`, its missing retries as I could not figure out how to get this out.
