### ISSUE TITLE
chromedriver and setValue(), skipping characters

### ISSUE THREAD

**Issue by JohanTh** [webdriverio/webdriverio#686]
Using `setValue()` to fill in input fields when having chrome set does not always fill in the entire values provided. Some characters are often skipped when using chromedriver and a solution that was suggested by another user in the gitter chat was to implement a pause between each character.

This is an example of a step definition that will fail to print all characters:

``` javascript
this.When(/^I fill in the name$/, function (callback) {
      return this.client
        .setValue("#name", "Test 123")
        .getValue("#name")
        .then(function (value) {
          assert(value === "Test 123"); // true
        });
    });
```

 This step often gives one of the following results:

> Tet 123
> Test123

**Comment by davidhouweling** [comment]
Any update on this?

**Comment by davidhouweling** [comment]
I've come up with a bit of a novel solution... browser of course being the client.

``` js
function sendInput(selector, inputString, keyIndex = 0) {
  return browser
    .keys(inputString.substr(keyIndex, 1))
    .waitUntil(() =>
      browser
        .getValue(selector)
        .then(value => value === inputString.substr(0, keyIndex + 1))
    )
    .then(() => {
      if (keyIndex < inputString.length) {
        return sendInput(selector, inputString, keyIndex + 1);
      }
      return browser.keys('Enter');
    });
}
```

**Comment by christian-bromann** [comment]
This is an old thread and I realized that WebdriverIO is not responsible for this problem. It sends the key values according to the protocol. If chromedriver skips characters it should be fixed by chromedriver.

**Comment by DaveWelling** [comment]
I was hitting this problem because the React rendering cycle wasn't fast enough.  I would just get the first character.
Keys (as in the example workaround) doesn't seem to be supported anymore by webdriver.  So here was my solution:
`function sendInput(selector, inputString, keyIndex = 0) {
    browser.addValue(selector, inputString.substr(keyIndex, 1));
    browser.waitUntil(() => {
        let value = browser.getValue(selector);
        return value === inputString.substr(0, keyIndex + 1);
    });
    if (keyIndex < inputString.length) {
        return sendInput(selector, inputString, keyIndex + 1);
    }
}`
Maybe this will help somebody who finds this while experiencing the same problem.
