### ISSUE TITLE
Unable to switch to WebView Contexts

### ISSUE THREAD

**Issue by guneetgarg** [webdriverio/webdriverio#6861]
Trying to Automate android app and we are switching from native to webview but **getContexts** is showing only one view

>    "@wdio/browserstack-service": "^7.5.7",
    "@wdio/cli": "^7.5.7",
    "@wdio/local-runner": "^7.5.7",
    "@wdio/mocha-framework": "^7.5.3",
    "@wdio/spec-reporter": "^7.5.7",
    "@wdio/sync": "^7.5.7",

![image](https://user-images.githubusercontent.com/3676026/118357477-05174680-b598-11eb-9b66-def69bb56bab.png)
![image](https://user-images.githubusercontent.com/3676026/118357520-355ee500-b598-11eb-9435-c1110d97405a.png)

**Comment by wswebcreation** [comment]
This is not Appium nor WebdriverIO related but in 99.99% of the case that the Android app is not a debug app.
Please contact your developers and let them show this https://developer.chrome.com/docs/devtools/remote-debugging/webviews/

**Comment by guneetgarg** [comment]
App is in debug mode and we tried same code on 2 different environment

working - java - selenium

> [POST http://127.0.0.1:8201/wd/hub/session/5d817ee5-7f91-4dfa-817e-d679e57ac234/element] with body: {"strategy":"xpath","selector":"//*[@text='Continue']","context":"","multiple":false}

not working - nodejs - webdriverio

> [POST http://127.0.0.1:8201/wd/hub/session/e22e2bc3-87f3-4f6f-881f-f661269251fb/element] with body: {"strategy":"xpath","selector":"//*[@text='Continue']","context":"","multiple":false}
