### ISSUE TITLE
waitForExist is not a function

### ISSUE THREAD

**Issue by sqagithub** [webdriverio/webdriverio#6863]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 devDependencies": {
    "@babel/cli": "^7.13.16",
    "@babel/core": "^7.14.2",
    "@babel/preset-env": "^7.14.2",
    "@babel/register": "^7.13.16",
    "@wdio/cli": "^7.5.7",
    "@wdio/local-runner": "^7.5.7",
    "@wdio/mocha-framework": "^7.5.3",
    "@wdio/spec-reporter": "^7.5.7",
    "chromedriver": "^90.0.0",
    "prettier": "^2.3.0",
    "wdio-chromedriver-service": "^7.0.0"
  },
**babel.config.js:**
module.exports = {
	presets: [
		[
			'@babel/preset-env',
			{
				targets: {
					node: 14,
				},
			},
		],
	],
}

**Config of WebdriverIO**
runner: local

**Describe the bug**
[chrome 90.0.4430.212 windows #0-0] Running: chrome (v90.0.4430.212) on windows
[chrome 90.0.4430.212 windows #0-0] Session ID: 1df20c661ac7fc822a7ae8b9a05a271b
[chrome 90.0.4430.212 windows #0-0]
[chrome 90.0.4430.212 windows #0-0] » \test\features\actions.js
[chrome 90.0.4430.212 windows #0-0] Browser actions
[chrome 90.0.4430.212 windows #0-0]    ✖ test input field
[chrome 90.0.4430.212 windows #0-0]    ✖ click populate
[chrome 90.0.4430.212 windows #0-0]
[chrome 90.0.4430.212 windows #0-0] 2 failing (396ms)
[chrome 90.0.4430.212 windows #0-0]
[chrome 90.0.4430.212 windows #0-0] 1) Browser actions test input field
[chrome 90.0.4430.212 windows #0-0] nameinput.waitForExist is not a function
[chrome 90.0.4430.212 windows #0-0] TypeError: nameinput.waitForExist is not a function
[chrome 90.0.4430.212 windows #0-0]     at Context.<anonymous> (C:\Users\Home\Documents\automation\wdioautomation\test\features\/actions.js:7:13)
[chrome 90.0.4430.212 windows #0-0]     at Context.executeAsync (C:\Users\Home\Documents\automation\wdioautomation\node_modules\@wdio\utils\build\shim.js:136:25)
[chrome 90.0.4430.212 windows #0-0]     at Context.testFrameworkFnWrapper (C:\Users\Home\Documents\automation\wdioautomation\node_modules\@wdio\utils\build\test-framework\testFnWrapper.js:45:32)
[chrome 90.0.4430.212 windows #0-0]
[chrome 90.0.4430.212 windows #0-0] 2) Browser actions click populate
[chrome 90.0.4430.212 windows #0-0] btnPopulate.waitForExist is not a function
[chrome 90.0.4430.212 windows #0-0] TypeError: btnPopulate.waitForExist is not a function
[chrome 90.0.4430.212 windows #0-0]     at Context.<anonymous> (C:\Users\Home\Documents\automation\wdioautomation\test\features\/actions.js:14:15)
[chrome 90.0.4430.212 windows #0-0]     at Context.executeAsync (C:\Users\Home\Documents\automation\wdioautomation\node_modules\@wdio\utils\build\shim.js:136:25)
[chrome 90.0.4430.212 windows #0-0]     at Context.testFrameworkFnWrapper (C:\Users\Home\Documents\automation\wdioautomation\node_modules\@wdio\utils\build\test-framework\testFnWrapper.js:45:32)

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:03

2021-05-15T18:00:44.295Z INFO @wdio/local-runner: Shutting down spawned worker
2021-05-15T18:00:44.559Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2021-05-15T18:00:44.560Z INFO @wdio/local-runner: shutting down
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wdioautomation@1.0.0 test: `wdio wdio.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wdioautomation@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Home\AppData\Roaming\npm-cache\_logs\2021-05-15T18_00_44_597Z-debug.log

**To Reproduce**

describe('Browser actions', () => {
	it('test input field', () => {
		browser.url('https://devexpress.github.io/testcafe/example/')
		const nameinput = $('#developer-name')
		nameinput.waitForExist()
		nameinput.setValue('Michael')
		browser.pause(3000)
		nameinput.clearValue()
	})
	it('click populate', () => {
		const btnPopulate = $('#populate')
		btnPopulate.waitForExist()
		btnPopulate.click()
	})
})

**Expected behavior**
Functions not working in my setup with function parenthesis. For example:  nameinput.waitForExist() does not work but nameinput.waitForExist does not throw any errors

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by AutomationReddy** [comment]
@sqagithub This is sync issue. Please surround your tests with async and await like below and it should work: (You can also install @wdio/sync package and it will be taken care including asynchronous but not recommended; see [here](https://webdriver.io/docs/sync-vs-async))

```js
describe('Browser actions', () => {
    it('test input field', async () => {
    browser.url('https://devexpress.github.io/testcafe/example/')
    const nameinput = await $('#developer-name')
    nameinput.waitForExist()
    nameinput.setValue('Michael')
    browser.pause(3000)
    nameinput.clearValue()
    })
    it('click populate', async () => {
    const btnPopulate = await $('#populate')
    btnPopulate.waitForExist()
    btnPopulate.click()
    })
    })
```

**Comment by christian-bromann** [comment]
Thanks for responding @AutomationReddy
