### ISSUE TITLE
wdio/sync does not work with Node 16

### ISSUE THREAD

**Issue by nilskasseckert** [webdriverio/webdriverio#6865]
**Describe the bug**
With node 16 fibers does not work anymore as you can see [here.](https://stackoverflow.com/questions/67330252/thread-id-key-0x7777-function-find-thread-id-key-file-src-coroutine-cc/67383621#67383621) But wdio/sync uses fibers. Therefore it does not work anymore. Switching to Node 15 is only a short term solution, as Fibers will stop working for all releases >= Node 16.

**To Reproduce**
Install node 16 and try to use wdio/sync

**Expected behavior**
wdio/sync is working with node 16.

What can I do?

Regardsm.
Nils

**Comment by BorisOsipov** [comment]
@nilskasseckert see https://github.com/webdriverio/webdriverio/discussions/6702
