### ISSUE TITLE
Passing arguments in execute

### ISSUE THREAD

**Issue by Demango** [webdriverio/webdriverio#687]
I'm getting some very strange exceptions being thrown by executing JS
execution:
``` javascript
Executing: [execute script: return (function (selector) {
    jQuery(selector+':visible').first().click();
    return 'done';
}).apply(null, arguments);, [.task-info]])
```
source:
``` javascript
this.click = function(selector, cb) {
    client
    .execute(function(selector) {
        jQuery(selector+':visible').first().click();
        return 'done';
    }, selector)
    .then(function() {
        cb()
    }, function(err) {
        // handles error
    });
}
``` 

Throws 
``` java
WARN - Exception thrown
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number"
```

(full stack trace: http://pastebin.com/GF5rUC5h)

This always occurs on certain classes being passed, never at random, the classes that throw the exception are as follows:
>a[href="#tab-comments"]
.task-info

Initially my thinking was that it was caused by the attribute selector on the first class, but clearly I was proven wrong after a little while, here are also some classes that always wok:
>a.project-details
a[href="#tab-jobs"]
.job-info

There is always exactly one of those elements selected by the href attributes and always many (and all visible) of the others.
I am utterly dumbfounded at this, and am, once again, at a complete impasse on this issue, if needed I can provide more information about the setup of my test page.

**Comment by christian-bromann** [comment]
This seems to be a weird Selenium issue. My suggestion here would be to find a different way to click on that visible element (maybe using xpath).

**Comment by Demango** [comment]
Noted.
