### ISSUE TITLE
Exclude files from code coverage

### ISSUE THREAD

**Issue by swendlandt** [webdriverio/webdriverio#6877]
**Is your feature request related to a problem? Please describe.**
If I take code coverage as described in https://webdriver.io/docs/devtools-service/#capture-code-coverage the devtools-service tries to intercept and transform all loaded js files, including third-party libraries. This is extremely unperformant if you load big third-party libraries. Also in most cases I am not interested in the coverage of the third-party libraries, just my own code.

**Describe the solution you'd like**
The `coverageReporter` objects should have two additional properties `include` and `exclude` where you can define file patterns to include respectively exclude from coverage.

**Comment by christian-bromann** [comment]
Thanks for filing the issue, contributions on this are much appreciated.

**Comment by kailin0512** [comment]
Hey @christian-bromann, I would like to try to contribute to this problem, 

From my understanding, I should add 'include' and 'exclude' type definition here
https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-devtools-service/src/types.ts#L10-L29

and make some logic change here to skip/include the file pattern here
https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-devtools-service/src/gatherer/coverage.ts#L25
But I am not sure where to add skip/include logic in devtools, do you have some suggestions or related recommend materials for me to look at?

**Comment by christian-bromann** [comment]
Let's continue conversations in #6920
