### ISSUE TITLE
@wdio/mocha-framework - randomize spec execution order

### ISSUE THREAD

**Issue by unickq** [webdriverio/webdriverio#6879]
**Is your feature request related to a problem? Please describe.**
Is that possible to implement randomizing option for mocha? Or it's not an option because of the original **mocha** plugin?

Found out that **jasmine** has it, so raising this question

**Comment by christian-bromann** [comment]
@unickq this would need to be implemented in Mocha, see also mochajs/mocha#902. I recommend to get involved in the project and contribute to it.
