### ISSUE TITLE
.execute() before document ready

### ISSUE THREAD

**Issue by sean-hill** [webdriverio/webdriverio#688]
Hey there,

I'd like to execute some JavaScript before my pages `$(document).ready` fires, however right now, it fires after the `$(document).ready`. Is this possible or am I out of luck?

**Comment by christian-bromann** [comment]
I don't think you can solve that with Selenium. Maybe you can inject a script if it is within your test environment. Or you could install a browser extension for this but that will hard to do for each browser.
