### ISSUE TITLE
Add an onComplete hook in @wdio/reporter so reporters know when all the tests are completed.

### ISSUE THREAD

**Issue by jamesmortensen** [webdriverio/webdriverio#6880]
**Is your feature request related to a problem? Please describe.**

While looking through and attempting to build custom reporters, I've observed there is no onComplete hook that runs in the reporter at the very end of the entire test run. A hook at the end would allow us to do something like generating a report or uploading a report to a remote server, for example.  

I see ReportPortal and Delta Reporter both require a reporter and a service be configured independently, and allure reporter doesn't have a service but does require extra steps to either generate a report via a CLI or by using the onComplete hook in the configuration file.  

Would it simplify report configuration if the @wdio/reporter had an onComplete hook which the reporters could use?  Does something like this already exist?  What would one need to do to add this?  Thank you.

**Describe the solution you'd like**

I picture WDIOReporter having an onComplete hook so report configuration could be kept out of services and in reporters.

**Describe alternatives you've considered**

There is no way that I can see for reporters to know when the last test has executed.  I considered reading the spec file list from the config file in every onRunnerEnd hook, storing the names of the ones that ran, and then assuming we're at the end when I've collected all of them, but that seems rather fragile considering the multiple ways wdio can be started.

For now, I'll do what allure-reporter does and perform some final step in the onComplete hook, perhaps as a service.  I've also wondered if I could programmatically modify the services list from the reporter to avoid the extra manual configuration there, but given how the configuration cannot be modified once it starts due to separation of contexts, I doubt that would work.

Hope this explanation helps.  Please let me know if I can clarify.

**Comment by christian-bromann** [comment]
> Would it simplify report configuration if the @wdio/reporter had an onComplete hook which the reporters could use? Does something like this already exist? What would one need to do to add this? Thank you.

With v5 we moved all reporter into the worker instance for performance reasons. Reporters generally should not run any async code as they essentially only listen on events and log them somewhere somehow. This is why some reporters with extra functionality come with services. While it is an overhead in terms of setup it is currently how the plugins are designed. There was already a discussion on this to make reporters like services, I couldn't find it anymore. IMHO the task of managing what happens with logs should not be part of a reporter but more of a general service that focuses on that.

I am happy to start an official discussion on finding a better architecture for this.

**Comment by jamesmortensen** [comment]
Here is the use case:   We want to report the sum of all passing, failing, skipped, ignored tests, and the total duration, to a Google Sheet.  Since we aren't needing to print anything to the terminal or stdout, would it be better to just build the entire thing as a service instead of as a reporter?

As a service, we have access to the result of all of the tests in the after hooks, and we have access to the onComplete hook as well.  I was thinking it would be called wdio-google-sheet-service or wdio-google-sheet-reporter-service.  Is there any downside to this type of setup?

**Comment by christian-bromann** [comment]
No, I think this sounds find.

**Comment by christian-bromann** [comment]
With the current way WebdriverIO works there is no chance to make an async operation if the testrunner completes. IMO reporters should not be able to do anything async. Therefor the current recommendation is to provide a service that uses. the `onComplete` hook. While I agree that this design is not idea for this use case, I haven't found a better solution for this yet that doesn't require to rewrite all reporters in the ecosystem to work.

I will close the issue as there is not really a path forward. I will observe if same topic comes up in the future or if folks propose a better solution to this.

Thanks for reporting the issue.

**Comment by jamesmortensen** [comment]
Thanks for clarifying.  Will go the service/reporter route.

**Comment by em** [comment]
Why even have separate integrations? Just make a single plugin API with all the hooks and let them all by async. The weird mashup of different types of integrations with some missing features is very confusing and buggy.

**Comment by christian-bromann** [comment]
> Just make a new universal plugins interface and consider everything else supported as legacy integrations with some adapter layer.

Feel free to raise an issue with a concrete proposal and we can talk about it. I am open to changes given we have seen more of these cases popping up. That said, we want to be careful which interfaces we open up and start to maintain as it is additional work and we also want to ensure users don't get confused about these integrations.
