### ISSUE TITLE
Eager / early page load automation not available for devtools

### ISSUE THREAD

**Issue by kingIZZZY** [webdriverio/webdriverio#6882]
When automating using `automationProtocol: 'devtools'` eg. on Chrome
How to run automations very early at earliest possible point during page load?

With WebDriver for example there is a capability [`'pageLoadStrategy'`](https://w3c.github.io/webdriver/#dfn-table-of-page-load-strategies) which can be set to `'eager'` or even `'none'`

This capability does not seem to be implemented for WebdriverIO+devtools. Rather it seems like automations only begin operating after full complete page load is finished.

For many use cases automation is needed much earlier, such as immediately upon initial page parse, document begin, document end, before loading secondary resources etc.

**Comment by christian-bromann** [comment]
What needs to be done here is to have the `devtools` package acknowledge the capability and make sure Puppeteer behaves the way the capability is set when it transitions through pages.

**Comment by kingIZZZY** [comment]
Was trying to dig into puppeteer & Dev Tools Protocol to figure out how is `pageLoadStrategy` implemented so as to try to figure out how can the effect (or similar) be achieved from WebdriverIO

Some random findings so far:

- [page_load_strategy.cc](https://source.chromium.org/chromium/chromium/src/+/master:chrome/test/chromedriver/chrome/page_load_strategy.cc;l=14)
- [Selenium WebDriver Browser.cpp:555](https://github.com/SeleniumHQ/selenium/blob/64447d4b03f6986337d1ca8d8b6476653570bcc1/cpp/iedriver/Browser.cpp#L555)

I'll post anything else I might find

**Comment by christian-bromann** [comment]
I think a fix should be applied to [this code area](https://github.com/webdriverio/webdriverio/blob/main/packages/devtools/src/devtoolsdriver.ts#L236) where we wait for the document to be ready.

**Comment by kingIZZZY** [comment]
OK yes I can see how we could probably edit some code there to handle `'interactive'` readyState and such

but a few questions:

1. is `pageLoadStrategy` capability even the right way to go here? It would seem that `pageLoadStrategy` is a WebDriver specific concept. Devtools doesn't have such a concept apparently. Or perhaps is this something WebdriverIO would aim to "standardize" across automation protocols? Will this be a `wdio:devtoolsOptions` property?
2. Is [that code area](https://github.com/webdriverio/webdriverio/blob/main/packages/devtools/src/devtoolsdriver.ts#L236) you referenced the right place/way how to implement earliest point of page load lifecycle (akin to page load strategy `none`) ? From the ChromeDriver source it looks like pageLoadStrategy `none` returns in a [non-blocking](https://source.chromium.org/chromium/chromium/src/+/master:chrome/test/chromedriver/chrome/page_load_strategy.cc;l=24) kind of way, without sending JS executions to the browser to test for document ready state client-side, as the referenced code is doing. How could such an effect be achieved in WebdriverIO, to know when the document has indeed begun loading (and at that - at its earliest point possible) but not waiting for any completion of loading or interactivity or readiness at all?
3. If WebdriverIO devtools uses Puppeteer under the hood, should this be done via puppeteer events? such as 
    - [page.on('domcontentloaded')](https://pptr.dev/#?product=Puppeteer&show=api-event-domcontentloaded) Emitted when the JavaScript DOMContentLoaded event is dispatched.
    - [page.on('framenavigated')](https://pptr.dev/#?product=Puppeteer&show=api-event-framenavigated) ? Emitted when a frame is navigated to a new URL.
    - [page.on('load')](https://pptr.dev/#?product=Puppeteer&show=api-event-load) Emitted when the JavaScript load event is dispatched.
    - Other?
4. Or similarly/alternatively should early page load work via hooking into the underlying [CDP _within_ puppeteer](https://pptr.dev/#?product=Puppeteer&show=api-class-cdpsession) that is [_within_ WebdriverIO](https://webdriver.io/docs/api/browser/getPuppeteer/) ?
    - [Page.domContentEventFired](https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-domContentEventFired)
    - [Page.frameNavigated](https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-frameNavigated) Fired once navigation of the frame has completed. Frame is now associated with the new loader.
    - [Page.lifecycleEvent](https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-lifecycleEvent) Fired for top level page lifecycle events such as navigation, load, paint, etc.
    - [Page.loadEventFired](https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-loadEventFired)
    - [Network.loadingFinished](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-loadingFinished) Fired when HTTP request has finished loading.
    - Other?

**Comment by kingIZZZY** [comment]
While waiting for comment on above questions - just 1 or 2 more random possibly useful references:

- [puppeteer src/common/Page.ts:554](https://github.com/puppeteer/puppeteer/blob/523aa0aafa9b2bf2c14e0ba416e4100f73bafa0a/src/common/Page.ts#L554) and [557](https://github.com/puppeteer/puppeteer/blob/523aa0aafa9b2bf2c14e0ba416e4100f73bafa0a/src/common/Page.ts#L557) Puppeteer using CDP events `Page.domContentEventFired` and `Page.loadEventFired` for its own Page object events
- [Page Load Strategy in chrome driver](https://stackoverflow.com/a/55304096)

**Comment by christian-bromann** [comment]
> 1. is `pageLoadStrategy` capability even the right way to go here? It would seem that `pageLoadStrategy` is a WebDriver specific concept. Devtools doesn't have such a concept apparently. Or perhaps is this something WebdriverIO would aim to "standardize" across automation protocols? Will this be a `wdio:devtoolsOptions` property?

The goal of the devtools package is to provide the same API we have in WebDriver for the DevTools protocol to allow users to pick one over the other. In some situations it is a burden to download and setup a driver properly, so by just using the devtools package you can automate browser without any setup. Therefor it would be good if we could mimic the capabilities in WebDriver as good as possible. However if there are options that make sense to provide on top that what we use the `wdio:devtoolsOptions` caps for.

> 2\. Is [that code area](https://github.com/webdriverio/webdriverio/blob/main/packages/devtools/src/devtoolsdriver.ts#L236) you referenced the right place/way how to implement earliest point of page load lifecycle (akin to page load strategy `none`) ? From the ChromeDriver source it looks like pageLoadStrategy `none` returns in a [non-blocking](https://source.chromium.org/chromium/chromium/src/+/master:chrome/test/chromedriver/chrome/page_load_strategy.cc;l=24) kind of way, without sending JS executions to the browser to test for document ready state client-side, as the referenced code is doing. How could such an effect be achieved in WebdriverIO, to know when the document has indeed begun loading (and at that - at its earliest point possible) but not waiting for any completion of loading or interactivity or readiness at all?

I believe Puppeteer and Chrome DevTools expose events that can exactly tell us when a page load starts. I am not sure if it is necessary to implement navigation tracking the same way Chromedriver did (I certainly don't mind extra complexity here 😉 ) therefor I suggest that if the navigation strategy is `none` we just don't wait at all, if it is eager we wait until the page starts loading and if it is normal we keep the current behavior.

> 3\. If WebdriverIO devtools uses Puppeteer under the hood, should this be done via puppeteer events?

Yes!

> 4\. Or similarly/alternatively should early page load work via hooking into the underlying [CDP _within_ puppeteer](https://pptr.dev/#?product=Puppeteer&show=api-class-cdpsession) that is [_within_ WebdriverIO](https://webdriver.io/docs/api/browser/getPuppeteer/) ?

Using as most of the Protractor interfaces will prevent things from breaking. So I would vote for using Protractor events as much as possible.

**Comment by kingIZZZY** [comment]
👍 excellent thanks for all the input

> I suggest that if the navigation strategy is `none` we just don't wait at all, if it is eager we wait until the page starts loading and if it is normal we keep the current behavior.

I wonder if that differs from WebDriver 🤔 come to think of it I'm not sure... I was under the impression that all of these 3 navigation options always imply waiting at least until the navigation action has started, whatever that means; the browser has started navigating, or the browser has successfully requested the page, or the browser is starting to get first byte response, or maybe even the beginning of the main HTML, 🤷‍♂️ not sure. But definitely not immediate synchronous continuation of running code before even receiving acknowledgement that the browser is navigating.. or at least so I was convinced. So `none` would've meant don't wait _any_ longer as soon as navigation is successful at all - immediately return and continue running automation code. `eager` would mean wait until page is `interactive` before loading other resources (DOMContentLoaded sort of thing) and `normal` would be page ready / complete / loaded sort of thing.

But maybe you're right and `none` means continue running code even tho page may not have even started navigating yet 🤔 would you know about this with certainty?

**Comment by kingIZZZY** [comment]
I find this notion of a very early/earliest possible point in time during page load exists for example in chrome extensions, the concept of accessing the page and performing actions (indeed after navigation occurs, but otherwise most earliest point during page load) even before the HTML has been fully loaded, before page is `interactive` even, and maybe even before that 😲 here are some sources:

- [Chrome Extensions docs `run_time`](https://developer.chrome.com/docs/extensions/mv3/content_scripts/#run_time)
- [stackoverflow "Chrome extension: Inject JS before page load"](https://stackoverflow.com/a/19192010)
- [stackoverflow "Chrome extension set to `run_at` `document_start`..."](https://stackoverflow.com/a/28188390)
- [Tampermonkey docs @run-at](https://www.tampermonkey.net/documentation.php?version=4.12&ext=dhdg&updated=true&old=4.11&intr=true&show=dhdg#_run_at) `document-start` "The script will be injected as fast as possible."

Wondering whether that was the idea of pageLoadStrategy `none`, i.e. earliest possible point when the page can be messed with at all even before fully parse/loaded, way before DOMContentLoaded / readyState `intreractive`

**Comment by kingIZZZY** [comment]
> events that can exactly tell us when a page load starts

If you could point these out to me that would be great

> Using as most of the Protractor interfaces will prevent things from breaking. So I would vote for using Protractor events as much as possible.

Sorry I guess I'm not familiar with Protractor, is it still part of the codebase? Is [this area of code](https://github.com/webdriverio/webdriverio/blob/main/packages/devtools/src/devtoolsdriver.ts#L236) using protractor interfaces? I can't find Protractor required or used much of anywhere in the code, only [mentioned](https://github.com/webdriverio/webdriverio/search?q=protractor) in some docs & changelogs apparently?

**Comment by christian-bromann** [comment]
> If you could point these out to me that would be great

For `eager` I would use the `page.on('framenavigated')` event handler and for `normal`, maybe `page.on('load')`.

> Sorry I guess I'm not familiar with Protractor, is it still part of the codebase?

Yes, it is part of the `devtools` package code base. At the beginning of the `checkPendingNavigations` function you see that the current page handle is assigned to `page` which you can use. With that you have access to the [`Page`](https://pptr.dev/#?product=Puppeteer&version=v9.1.1&show=api-class-page) object.

**Comment by kingIZZZY** [comment]
How do I access capabilities property `pageLoadStrategy` from within that `checkPendingNavigations()` method? I tried debugging through it examining all available objects but couldn't find caps

**Comment by christian-bromann** [comment]
You will have to pass these capabilities in when the [class in created](https://github.com/webdriverio/webdriverio/blob/main/packages/devtools/src/index.ts#L52).

**Comment by kingIZZZY** [comment]
I apologize in advance - I have almost no clue what it is that I was thinking that I _think_ that I'm trying to do here... 😆🤦‍♂️
See this [pathetic first attempt commit diff `c1f8f91a`](https://github.com/kingIZZZY/webdriverio/commit/c1f8f91ae59eb99d283992be0b7c902e3f07aa7f)

I have so many questions...

- Does it even work / make any sense? To set the promise resolve function outside of the Promise, and trying to make the page events handlers call the promise's resolve()?...
- What if the `framenavigated` / `load` events are missed or fired already earlier
- Do we need a reasonable timeout to expire the promise in case it gets stuck for too long waiting for the events
- Do we need to track state when events may have happened on the same Page but differing cycles of a _previous_ page navigation vs _current_ / _subsequent_ page navigation...
- Am I even anywhere remotely on the right track.. have I managed to break all of webdriverIO's coding conventions/styles and completely ignored TypeScript and overall horribleness... Is it even... I don't even... 🤦‍♂️

**Comment by christian-bromann** [comment]
> * Does it even work / make any sense? To set the promise resolve function outside of the Promise, and trying to make the page events handlers call the promise's resolve()?...

mhm .. maybe you can just have two flags for eager and normal pageload and in `checkPendingNavigations` do something like this:
```js
await new Promise<void>((resolve, reject) => {
    setTimeout(() => reject(new Error('pageload timeout'), 30000)
    const checkInterval = setInterval(() => {
        if (pageloadStrategy === 'eager' && this.frameNavigated || this.pageLoaded) {
            clearTimeout(checkInterval)
            resolve()
        }
    }, 100)
})
```

> * What if the `framenavigated` / `load` events are missed or fired already earlier

Well usually this should not happen. This is why I suggest to work with flags here because if we miss the events, these flags will be set to `true` and no waiting is required. We should only wait if the page actually loads.

> * Do we need a reasonable timeout to expire the promise in case it gets stuck for too long waiting for the events

We should allow users to define a timeout for page loads, e.g. see above 30s.

> * Do we need to track state when events may have happened on the same Page but differing cycles of a _previous_ page navigation vs _current_ / _subsequent_ page navigation...

Not sure if I understand. We should only focus on the page that currently has the focus (see `getPageHandle`).

> * Am I even anywhere remotely on the right track..

Sure you are 😄  new codebases can look intimidating but once you spend some time on it you feel much more comfortable. You can ignore all coding convention until you get the main functionality working, this is what I usually do too.

**Comment by christian-bromann** [comment]
> How to know when to do that?

By listening on the `page.on('framedetached')` event. Puppeteer allows to track exactly which pages are open and which ones close.

**Comment by kingIZZZY** [comment]
Then how about `Runtime.executionContextCreated` instead of that whole try/catch block with `...evaluate('1')`?
[puppeteer/src/common/FrameManager.ts:353](https://github.com/puppeteer/puppeteer/blob/943477cc1eb4b129870142873b3554737d5ef252/src/common/FrameManager.ts#L353)

Worth contributing another Page emit event there to the puppeteer project?...

**Comment by kingIZZZY** [comment]
In fact - [this puppeteer test](https://github.com/puppeteer/puppeteer/blob/main/test/evaluation.spec.ts#L143) seems to prove that once `framenavigated` event hits, execution context is definitely working & usable. So we can eliminate this whole check?

**Comment by kingIZZZY** [comment]
Attempt # 000001 https://github.com/webdriverio/webdriverio/commit/bc5fdfc1aa8c28d12b0c8fe8d8e3503c3a22ca50

**Comment by kingIZZZY** [comment]
Finally figured out how to build and debug local changes.

Problems:

> By listening on the `page.on('framedetached')` event.

- Unfortunately this `framedetached` event seems to fire off at other times, other than "at the end of a page lifecycle" when it's time to clean up all the loading state flags from previous/current loaded document. So the question returns: When is the right time upon what page event should we clear the page loading flags? Perhaps a different option from the ones listed [above 👆](https://github.com/webdriverio/webdriverio/issues/6882#issuecomment-844349082)?

- Is there a better way than `checkPendingNavigation()` ?

Why do we even [`checkPendingNavigation()`](https://github.com/webdriverio/webdriverio/blob/a840d46fb34ec4876c426b0f421327d48227f0c0/packages/devtools/src/devtoolsdriver.ts#L194) ? Here's the commit https://github.com/webdriverio/webdriverio/commit/2db6a8d3d97f42b7b553954f318b7a0fcedc369d, bug https://github.com/webdriverio/webdriverio/issues/4443, and PR https://github.com/webdriverio/webdriverio/pull/4459 which has some important discussion including some debug results from the flow of operations and even direct mention of eager pageLoadStrategy https://github.com/webdriverio/webdriverio/pull/4459#issuecomment-529157827.

Waiting for page execution context seems like waiting too long (ex. this [bestbuy product](https://www.bestbuy.com/site/razer-blade-15-base-15-6-gaming-laptop-intel-core-i7-16gb-memory-nvidia-geforce-gtx-1660-ti-256gb-ssd-black/6437974.p?skuId=6437974) page) it almost seems like only upon full page loaded complete does this [await-for-execution-context](https://github.com/webdriverio/webdriverio/blob/main/packages/devtools/src/devtoolsdriver.ts#L230) finally return 🤔

Why are we using `await page.mainFrame().executionContext()` to ensure page navigation safety? Is it even a good indicator? The above PR comments seem to show executions happening (!) way before executionContext is officially created. Maybe waiting on this is not the right thing to wait on? Maybe we go straight to [evaluate()ing "1"](https://github.com/webdriverio/webdriverio/blob/v7.6.1/packages/devtools/src/devtoolsdriver.ts#L231) instead of waiting for execution context?

Could we instead rely on other lifecycle/navigation/runtime events from the frame or page as our "check navigation" logic?

**Comment by christian-bromann** [comment]
> Finally figured out how to build and debug local changes.

Have you been struggling with specific issues? Anything we could improve in the [contribution guidelines](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md)?

> * Unfortunately this `framedetached` event seems to fire off at other times

The event should send the frame id and we can just check whether we were running on that frame id and only reset if it is the one we were.

> * Is there a better way than `checkPendingNavigation()` ?

I am not sure what you mean by that.

> Why do we even [`checkPendingNavigation()`](https://github.com/webdriverio/webdriverio/blob/a840d46fb34ec4876c426b0f421327d48227f0c0/packages/devtools/src/devtoolsdriver.ts#L194) ?

The goal is to wait for the page to be ready when an url is called otherwise people will run into race conditions. Additionally we try to mimic the WebDriver protocol as close as possible and waiting for the page to load is what happens in Webdriver.

> Why are we using `await page.mainFrame().executionContext()` to ensure page navigation safety? Is it even a good indicator?

Afaik Puppeteer ensures that an execution context exists before allowing to interact with it. It seem to work so far, sure there are better options.

> Could we instead rely on other lifecycle/navigation/runtime events from the frame or page as our "check navigation" logic?

Suggestions are welcome.

**Comment by christian-bromann** [comment]
I will go ahead and close this issue. Moving on we will not endorse using WebdriverIO with `automationProtocol: 'devtools'`. Folks should use Puppeteer directly when interacting with CDP. Maintaining a WebDriver like version via CDP is not maintainable and there is no advantage to that.
