### ISSUE TITLE
Electron app as binary issue

### ISSUE THREAD

**Issue by wdioAutomationUser** [webdriverio/webdriverio#6883]
Hi i am getting ERROR webdriver: Request failed with status 500 due to session not created: session not created
[0-0] from no such window: window was already closed
[0-0] (Session info: chrome=80.0.3987.134)
[0-0] 2021-05-19T16:37:06.994Z ERROR webdriver: session not created: session not created
the window gets opened it is binary electron app but then gets closed and above error is displayed
kindly help me on this
I am using the below dependencies 
"@wdio/allure-reporter": "^7.5.7",
"@wdio/local-runner": "^7.5.7",
"@wdio/mocha-framework": "^7.5.3",
"@wdio/sync": "^7.5.7",
"chai": "^4.3.4",
"devtools": "^7.5.7",
"electron": "^8.0.3",
"webdriverio": "^7.5.7",
"@wdio/cli": "^7.3.1",
"chromedriver": "^80.0.2",
"html-dnd": "^1.2.1",
"wdio-chromedriver-service": "^7.1.0"

**Comment by christian-bromann** [comment]
Please see the [ElectronJS docs](https://www.electronjs.org/docs/tutorial/using-selenium-and-webdriver#setting-up-with-webdriverio) on how to setup WebdriverIO and Electron. Does this not work for you?

**Comment by wdioAutomationUser** [comment]
The problem was with configuration in wdio.conf file, after making changes with host and port, the issue is resolved, thanks. We have a common code base that should work for both web and electron app, that's where I was facing the difficulty to get the script running for both apps.

**Comment by jehon** [comment]
@wdioAutomationUser : could you post your wdio.conf.js file? Having a problem where this could help me...
