### ISSUE TITLE
Unexpected behavior when chaining element selections

### ISSUE THREAD

**Issue by leabaertschi** [webdriverio/webdriverio#6885]
**Environment (please complete the following information):**
using https://github.com/webdriverio/cucumber-boilerplate

**Config of WebdriverIO**
using https://github.com/webdriverio/cucumber-boilerplate

**Describe the bug**
We use `waitUntil` to retry some tests in case the website is not yet in the expected state when a test scenario starts. Inside this `waitUntil` when chaining element selections (`$('parentElement').$('childElement')`) and the parent element does not exist, instead of failing and re-executing the `waitUntil` loop, I see several retries to select the parent element in the logs.

All the code for the retry logic and example step and feature can be found here: https://github.com/leabaertschi/cucumber-boilerplate/tree/retry-logic.

**To Reproduce**

Clone https://github.com/leabaertschi/cucumber-boilerplate, check out branch `retry-logic` and run the `bug.feature`.

**Expected behavior**
I would expect the chained selection to fail on the first try if the parent element does not exist and throw an error so that the `try-catch` inside the `waitUntil` can catch the error and return false to retry execution.

**Comment by christian-bromann** [comment]
Thanks for the thorough issues description, I assume this bug somewhere lies in our [retry logic](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/middlewares.ts#L35). Any contribution are appreciated.

**Comment by christian-bromann** [comment]
@leabaertschi unfortunately your provided example doesn't help to reproduce the issue as it uses an unknown website. Can you amend the example to use a public website?

**Comment by leabaertschi** [comment]
@christian-bromann I'm really confused now, I was able to run those tests locally with the demo app static site that is included in the project. According to the readme of the cucumber-boilerplate project `yarn test` should start a local webserver with this test website, but I can't get it to work anymore now. Since this seems to be your project, maybe you can give me a hint?

**Comment by christian-bromann** [comment]
Hey Lea,

sorry for not getting back to you for so long. I didn't quite look carefully enough into the issue. Sorry about that! I believe there is a conceptional problem here. When you run:

```js
$(retry > 5 ? parentSelector : `${parentSelector}foo`).$(childSelector)
```

WebdriverIO runs its own retry logic to find `${parentSelector}foo` which already takes up all the time for running the step. So your retry mechanism doesn't even kick in. If you change your step to this:

```ts
Given(
    /^there is an element "([^"]*)" inside an element "([^"]*)"$/,
    (childSelector: string, parentSelector: string) => {
        let retry = 0;
        refreshSafe(() => {
            retry += 1;
            const parentElement = $(retry > 5 ? parentSelector : `${parentSelector}foo`);
            expect(parentElement.isDisplayed()).toBeTruthy();
            parentElement.$(childSelector);
        });
    }
);
```

Keep in mind that WebdriverIO already retries elements if they don't exist.

I hope this helps, let me know if I can further help!
