### ISSUE TITLE
 Impossible to pass function as parameter to custom command

### ISSUE THREAD

**Issue by pazone** [webdriverio/webdriverio#689]
I'm trying to create custom command which receives the function as parameter. And it does not work due to backward compatibility [here](https://github.com/webdriverio/webdriverio/blob/43efd4a8463419cfe5c347268544b19e62394931/lib/webdriverio.js#L349). Parameter is being dropped. Is this backwards compatibility so necessary? Now i'm forced to do like this:
```
client.myNewCommand(myFuction, anyNonFunctionArg)
```

**Comment by christian-bromann** [comment]
> Is this backwards compatibility so necessary?

I think yes, many people are still using the old callback functionality as they are not familiar with promises. But I will drop that in one of the next versions. So far there is no other way than this workaround.
