### ISSUE TITLE
Missing TS types for webdriverIO commands?

### ISSUE THREAD

**Issue by ArminazK** [webdriverio/webdriverio#6892]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.6.0
 - **Mode:** WDIO Testrunner (typescript)
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** v14.16.1
 - **NPM version:** 6.14.12
 - **Browser name and version:** Chrome 90, Firefox 88
 - **Platform name and version:** MacOS BigSur 11.3
 - **Additional wdio packages used (if applicable):** @wdio/spec reporter, @wdio/selenium-standalone service

**Config of WebdriverIO**
[config](https://github.com/ArminazK/wdio7_multiremote/blob/main/wdio.conf.ts)

**Describe the bug**
Missing TS types for webdriverio commands?

**To Reproduce**
Here is an example: [repo](https://github.com/ArminazK/wdio7_multiremote)
I am implementing custom browser for multiremotebrowser support of PO pattern.
**Expected behavior**
I assume that some webdriverio commands are missing/or have wrong Types
e.g.:
browser - $/$$ should be of type: `WebdriverIO.Browser | WebdriverIO.Element | WebdriverIO.MultiRemoteBrowser`
element - getText() should be of type: `WebdriverIO.Element | WebdriverIOAsync.Element`

Adding those types solves TS compiler issues in my example repo e.g.
`await this.browser.$('#username')` does not need 'ts-ignore' once I add these Types in node_modules
compiler message: `'type 'Browser | MultiRemoteBrowser' is not assignable to method's 'this' of type 'Browser | Element'.'`

**Additional context**
I could use type `any` in my [driverFactory](https://github.com/ArminazK/wdio7_multiremote/blob/main/test/util/driverFactory.ts) for `browser()`, but then I loose intellisense....

Thanks for your time!

**Comment by christian-bromann** [comment]
Hey @ArminazK , thanks for filling the issue.

I recommend to work with generics here, e.g.:

```ts
import BrowserObject = WebdriverIO.Browser;
import MultiRemoteBrowserObject = WebdriverIO.MultiRemoteBrowser;

export class DriverFactory<T = BrowserObject> {
    private readonly _browser: T;

    constructor(browser: T) {
        this._browser = browser;
    }

    get browser(): T {
        return this._browser;
    }
}
```

Command results for multiremote are different than for normal browser sessions therefor you can't just define the browser as `WebdriverIO.Browser | WebdriverIO.Element | WebdriverIO.MultiRemoteBrowser`.
