### ISSUE TITLE
Using -cucumberOpts.tagExpression='@smoke' spawns sessions for ignored scenarios

### ISSUE THREAD

**Issue by nealio42** [webdriverio/webdriverio#6894]
WDIO version 7.6.0

example use case

feature1.feature has 20 scenarios, 1 is tagged @smoke
feature2.feature has 5 scenarios, 1 is tagged @smoke

running with --cucumberOpts.tagExpression='@smoke' should create 2 sessions. Instead, it creates 25 sessions. Looking at the wdio logs, 23 of these sessions cause the command to fail with exit code 1.

**Comment by christian-bromann** [comment]
Can you provide a minimal reproducible example? Normally every feature file spawns a worker process and with that a single session.

**Comment by nealio42** [comment]
Closing, need example but do not have the time. Sorry for wasting your time. It is probably my misunderstanding of the worker process and sessions.
