### ISSUE TITLE
Ability to expose all existing commands

### ISSUE THREAD

**Issue by unlok** [webdriverio/webdriverio#6898]
**Is your feature request related to a problem? Please describe.**
I want to wrap all existing commands via `overwriteCommand()` method for `browser` and `element`.

**Describe the solution you'd like**
Now I can do this:
```js
const browserCommandNames = Object.keys(require('webdriverio/build/commands/browser'));
const elementCommandNames = Object.keys(require('webdriverio/build/commands/element'));
```
But this solution is fragile and it is internal stuff. Can you expose public API for this purpose?

**Comment by christian-bromann** [comment]
> I want to wrap all existing commands via `overwriteCommand()` method for `browser` and `element`.

Mind explaining what your use case is here? Just curious.

> Can you expose public API for this purpose?

Yes, there is a `commandList` property you can use. I added some docs around it.

**Comment by unlok** [comment]
> Mind explaining what your use case is here? Just curious.

I want to add some code before and after each command execution. Like a timer or some log. I have to do it only for public API, but `commandList` contains a lot of another commands. This list is not what we are talking about. Also how can I get `commandList` of an element before I run test and get some element instance?
Precise lists are located there:
https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/browser.ts
https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/element.ts

```
"newSession"
"deleteSession"
"status"
"getTimeouts"
"setTimeouts"
"getUrl"
"navigateTo"
"back"
"forward"
"refresh"
"getTitle"
"getWindowHandle"
"closeWindow"
"switchToWindow"
"createWindow"
"getWindowHandles"
"printPage"
"switchToFrame"
"switchToParentFrame"
"getWindowRect"
"setWindowRect"
"maximizeWindow"
"minimizeWindow"
"fullscreenWindow"
"findElement"
"findElements"
"findElementFromElement"
"findElementsFromElement"
"getActiveElement"
"isElementSelected"
"isElementDisplayed"
"getElementAttribute"
"getElementProperty"
"getElementCSSValue"
"getElementText"
"getElementTagName"
"getElementRect"
"isElementEnabled"
"elementClick"
"elementClear"
"elementSendKeys"
"getElementValue"
"getPageSource"
"executeScript"
"executeAsyncScript"
"getAllCookies"
"addCookie"
"deleteAllCookies"
"getNamedCookie"
"deleteCookie"
"performActions"
"releaseActions"
"dismissAlert"
"acceptAlert"
"getAlertText"
"sendAlertText"
"takeScreenshot"
"takeElementScreenshot"
"getElementComputedRole"
"getElementComputedLabel"
"setPermissions"
"generateTestReport"
"createMockSensor"
"getMockSensor"
"updateMockSensor"
"deleteMockSensor"
"setTimeZone"
"addVirtualAuthenticator"
"removeVirtualAuthenticator"
"addCredential"
"getCredentials"
"removeAllCredentials"
"removeCredential"
"setUserVerified"
"isAlertOpen"
"isAutoReporting"
"setAutoReporting"
"isLoading"
"takeHeapSnapshot"
"getNetworkConnection"
"setNetworkConnection"
"getNetworkConditions"
"setNetworkConditions"
"deleteNetworkConditions"
"sendCommand"
"sendCommandAndGetResult"
"file"
"launchChromeApp"
"elementHover"
"touchPinch"
"freeze"
"resume"
"shutdown"
"getLogTypes"
"getLogs"
"isW3C"
"isMobile"
"isIOS"
"isAndroid"
"isChrome"
"isSauce"
"isSeleniumStandalone"
"puppeteer"
"_NOT_FIBER"
"$$"
"$"
"call"
"custom$$"
"custom$"
"debug"
"deleteCookies"
"execute"
"executeAsync"
"getCookies"
"getPuppeteer"
"getWindowSize"
"keys"
"mock"
"newWindow"
"pause"
"react$$"
"react$"
"reloadSession"
"savePDF"
"saveRecordingScreen"
"saveScreenshot"
"setCookies"
"setTimeout"
"setWindowSize"
"switchWindow"
"throttle"
"touchAction"
"uploadFile"
"url"
"waitUntil"
"strategies"
```

**Comment by christian-bromann** [comment]
> Like a timer or some log.

Why don't you use the `beforeCommand` and `afterCommand` hook for this?

**Comment by unlok** [comment]
> > Like a timer or some log.
> 
> Why don't you use the `beforeCommand` and `afterCommand` hook for this?

Looks like it is what I need 👍 I'll try this approach, thanks!

**Comment by unlok** [comment]
@christian-bromann, what I do wrong?
```js
const wdio = require('./packages/webdriverio')

let client

(async function () {
    client = await wdio.remote({
        protocol: 'http',
        hostname: '...',
        port: 4444,
        path: '/wd/hub',
        capabilities: {
            browserName: 'chrome',
            browserVersion: '85.0',
        },
        beforeCommand: [(args) => {
            console.log('BEFORE', args)
        }],
    })

    await client.url('https://yandex.ru')
    const body = await client.$('body')
    await body.click()
    await client.pause(3000)

    await client.deleteSession()
})()
    .catch(async (e) => {
        console.error(e.stack)
        await client.deleteSession()
    })
```

And got error:
```
TypeError: Cannot convert undefined or null to object
    at execHook (.../webdriverio/packages/wdio-sync/build/executeHooksWithArgs.js:35:27)
```
Code at this line `delete global.browser._NOT_FIBER;`

Log of `global`:
```
Object [global] {
  global: [Circular],
  clearInterval: [Function: clearInterval],
  clearTimeout: [Function: clearTimeout],
  setInterval: [Function: setInterval],
  setTimeout: [Function: setTimeout] {
    [Symbol(nodejs.util.promisify.custom)]: [Function]
  },
  queueMicrotask: [Function: queueMicrotask],
  clearImmediate: [Function: clearImmediate],
  setImmediate: [Function: setImmediate] {
    [Symbol(nodejs.util.promisify.custom)]: [Function]
  },
  _HAS_FIBER_CONTEXT: false
}
```

There is no `browser` property.

**Comment by christian-bromann** [comment]
Please see https://webdriver.io/docs/setuptypes. Hooks like `beforeCommand` only work with the wdio testrunner.

**Comment by unlok** [comment]
@christian-bromann, unfortunately hooks are not working properly.
```
...
BEFORE executeScript
AFTER executeScript
AFTER execute
BEFORE performActions
BEFORE performActions
BEFORE performActions
AFTER performActions
AFTER performActions
AFTER performActions
BEFORE releaseActions
BEFORE releaseActions
BEFORE releaseActions
AFTER releaseActions
AFTER releaseActions
AFTER releaseActions
AFTER moveTo
AFTER moveTo
BEFORE url
BEFORE extendOptions
AFTER extendOptions
AFTER url
BEFORE extendOptions
AFTER extendOptions
AFTER executeScript <- there was not BEFORE hook for this command.
...
```
The same thing with `navigateTo`, `deleteSession` commands.

**Comment by christian-bromann** [comment]
> unfortunately hooks are not working properly

They do work properly, just maybe not the way you expect. WebdriverIO commands can be nested, so this is absolutely normal:

```
BEFORE execute
BEFORE executeScript
AFTER executeScript
AFTER execute
```

Here the `execute` command is run first and triggers `executeScript`.

You will have to provide a concrete example when you believe there is something not working. This log doesn't really help understand the issue.

**Comment by unlok** [comment]
@christian-bromann, you are right. I could not reproduce this case with wdio runner. But in my case I do not have runner and have to use wdio directly via `wdio.remote()`. So looks like my first question is actual, I mean - API to getting public commands list for browser and element.

**Comment by christian-bromann** [comment]
I believe the standalone interface only gives you the `commandList` which you can use to then overwrite certain or all commands.
