### ISSUE TITLE
Not able to use expect in jasmine framework

### ISSUE THREAD

**Issue by praveendvd** [webdriverio/webdriverio#6906]
**Environment (please complete the following information):**
 - **WebdriverIO version:**  7.6.0
 -  - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [async]
 - **Node.js version:**  v16
 - **NPM version:**  6.14.10
 - **Browser name and version:**  chrome 90.0.4430.212
 - **Platform name and version:** [ Windows 10]
 - **Additional wdio packages used (if applicable):**     "@wdio/jasmine-framework": "^7.6.0",
                                                                                        "@wdio/local-runner": "^7.6.0",
                                                                                        "@wdio/spec-reporter": "^7.6.0",
                                                                                        "chromedriver": "^90.0.1",
                                                                                        "wdio-chromedriver-service": "^7.1.0"

**Describe the bug**
  await expect(SecurePage.flashAlert).toBeExisting();  throws Expected [object Promise] to be existing.

**To Reproduce**

[temp_2.zip](https://github.com/webdriverio/webdriverio/files/6535504/temp_2.zip)

Just run this project which was made from auto generate feature in wdio

**Expected behavior**

Test should pass

**Log**

```
Error: Expected [object Promise] to be existing.
[chrome 90.0.4430.212 windows #0-0]     at <Jasmine>
[chrome 90.0.4430.212 windows #0-0]     at <Jasmine>
[chrome 90.0.4430.212 windows #0-0]     at UserContext.<anonymous> (C:\Users\temp_2\test\specs\example.e2e.js:9:45)
[chrome 90.0.4430.212 windows #0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by christian-bromann** [comment]
In Jasmine you have to use [async matchers](https://jasmine.github.io/api/3.7/async-matchers). See also #6855.

```js
await expectAsync(SecurePage.flashAlert).toBeExisting();
```
