### ISSUE TITLE
 'element not interactable'  and  ' element wasn't found '

### ISSUE THREAD

**Issue by bx2651** [webdriverio/webdriverio#6907]
I want to do something after the page loads, such as click a button or input some text, sometimes it works but sometimes it prompts me 'element not interactable' or ' element wasn't found '. How can I avoid it?

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.5.0]
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:14.16.1 [e.g. 8.11.2]
 - **NPM version:** [e.g. 5.8.0]
 - **Browser name and version: chrome=90.0.4430.212 [e.g. Chrome 68]
 - **Platform name and version:MAC OS [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
  specs: [
    path.join(__dirname, '/tests/e2e/**/*.spec.ts'),
    path.join(__dirname, '/tests/e2e/**/*.spec.js'),
  ],
  exclude: [
    // 'test/spec/multibrowser/**',
    // 'test/spec/mobile/**'
  ],
  logLevel: 'trace',
  outputDir: path.join(__dirname, 'tests/e2e/logs'),
  bail: 0,
  waitforTimeout: 1000,
  framework: 'mocha',
  specFileRetries: 0,
  specFileRetriesDeferred: false,
  reporters: ['spec'],
  mochaOpts: {
    ui: 'bdd',
    timeout: 6000000,
    require: 'ts-node/register',
  },

**Describe the bug**
I want to do something after the page loads, such as click a button or input some text, sometimes it works but sometimes it prompts me 'element not interactable' or ' element wasn't found '.

**To Reproduce**
1.  browser.url(path)
2. register() {
    this.getEmail();
    this.email.addValue(config.email);
    this.password.addValue(config.password);
    this.inviteCode.addValue(config.inviteCode);
    this.next.click();
  }
3. click button or input some text and then it will prompts me 'element not interactable' or ' element wasn't found '.

**Expected behavior**

**Log**
element not interactable
(Session info: chrome=90.0.4430.212)
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at Object.exports.registerUser (/Users/mac/Documents/工作/master-web/tests/e2e/utils/account.js:18:33)
at Context. (/Users/mac/Documents/工作/master-web/tests/e2e/specs/team.spec.js:240:20)

Error: Can't call click on element with selector "button=开始使用" because element wasn't found
at Context. (/Users/mac/Documents/工作/master-web/tests/e2e/specs/account.spec.js:67:35)

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
If an element is not interact-able you can't interact with it. Make sure the element is loaded and it is interactable, via:
```js
browser.waitUntil(() => {
    const elem = $('selector')
    try {
        elem.click()
        return true
    } catch () {
        return false
    }
})
```
