### ISSUE TITLE
allure line shown in section of code under https://webdriver.io/docs/allure-reporter/#autogenerate-report cannot directly accessed be 

### ISSUE THREAD

**Issue by starbuck251** [webdriverio/webdriverio#6913]
**Describe the improvement**
Having installed the allure commandline, then
When trying to copy in the Code block under https://webdriver.io/docs/allure-reporter/#autogenerate-report into onComplete()
On the 2nd line of code, the allure command is showing TS2304: Cannot find name 'allure'.
` const generation = allure(['generate', 'allure-results', '--clean'])`

I can see not see a way to access 'allure' in this example therefore it does not run.

I'd like to report
- [X ] Unclear documentation

**Description of the improvement / report**
If someone can improve the documentation to be a pick up and go bit of code or explain what else might need to be imported for it to work.

**Comment by christian-bromann** [comment]
Hey @starbuck251 , thanks for filling the issue.

The doc was a bit unclear due to a missing import. I added a commit to better demonstrate it. Docs will be updated in a minute or two. Let me know if you have further questions.

**Comment by starbuck251** [comment]
Hi @christian-bromann thanks for clarifying, that has helped, it looks like it runs now - just spotted up one more thing although it doesn't seem to stop it working

the line `resolve();`
is showing
`TS2794: Expected 1 arguments, but got 0. Did you forget to include 'void' in your type argument to 'Promise'`?

thanks again

**Comment by christian-bromann** [comment]
The example isn't using TypeScript. You will need to adjust it by the following:

```ts
return new Promise<void>((resolve, reject) => {
```

**Comment by rsvenkata** [comment]
const generation = allure(['generate', 'allure-results', '--clean'])

How can I pass another parameter to above 'generation' method? I wanted to place the allure-report into a specific folder.

Eg: 
const generation = allure(['generate', 'allure-results', 'Reports/allure-report', '--clean'])

But it does not work.
