### ISSUE TITLE
waitForText and other expects fail in async mode

### ISSUE THREAD

**Issue by mlynch** [webdriverio/webdriverio#6918]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.6.1
 - **Mode:** `npx wdio run`
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 14.15.0
 - **NPM version:** 7.5.6
 - **Browser name and version:** Chrome 91.0.4472.77 (Official Build) (x86_64)
 - **Platform name and version:** macOS 11.2.3
 - **Additional wdio packages used (if applicable):** `@wdio/jasmine-framework`, `@wdio/local-runner`, `@wdio/spec-reporter`

**Config of WebdriverIO**

(default one generated with `npx wdio config`, without comments below):

```
exports.config = {
    runner: 'local',
    specs: [
        './test/specs/**/*.js'
    ],
    exclude: [
        // 'path/to/excluded/files'
    ],
    maxInstances: 10,
    capabilities: [{
        maxInstances: 5,
        browserName: 'chrome',
        acceptInsecureCerts: true
    }],
    logLevel: 'info',
    bail: 0,
    baseUrl: 'http://localhost:8080',
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    services: ['chromedriver'],
    framework: 'jasmine',
    reporters: ['spec'],
    jasmineOpts: {
        defaultTimeoutInterval: 60000,
        expectationResultHandler: function(passed, assertion) {
            // do something
        }
    }
}
```

**Describe the bug**

In async mode, tests using expects like `waitForText` fail, but work fine in sync mode. 

**To Reproduce**

https://github.com/mlynch/webdriverio-async-issue

**Expected behavior**

Text should pass in async mode and find element's correct text, as in sync mode

**Log**

https://gist.github.com/mlynch/55ca0642791d9e83d0b5f873390c09d7

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
Unfortunately Jasmines matcher have a different name when running in async mode as others. See also https://jasmine.github.io/api/3.7/async-matchers. We already started working on this in #6855. I recommend to switch to Mocha as it comes with better retry mechanisms anyway. Please let me know if you have further questions.

**Comment by mlynch** [comment]
Worked great, thanks
