### ISSUE TITLE
Run specific suite or spec using wdio test runner - Not working

### ISSUE THREAD

**Issue by Yanela-ipsy** [webdriverio/webdriverio#6919]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.12.1
 - **Mode:** WDIO Testrunner
 - **running sync** 
 - **Node.js version:** 12.21.0
 - **NPM version:** 6.14.11
 - **Browser name and version:**  Chrome 90
 - **Platform name and version:** Mac OS Catalina - version 10.15.7

**Config of WebdriverIO**
I have a "config" folder with this files: 

![image](https://user-images.githubusercontent.com/68640177/119693424-a4eb9480-be22-11eb-9abf-3bceeaf91165.png)

E.g "local.conf.js":

```
const baseConfig = require('./wdio.conf').config;

const localConfig = Object.assign(baseConfig, {
  // local capabilities
  capabilities: [
    {
      maxInstances: 5,
      browserName: 'chrome',
      acceptInsecureCerts: true,
      'goog:chromeOptions': {
        args: ['--disable-web-security', '--ignore-certificate-errors'],
      },
    },
  ],
});

exports.config = localConfig;
```

**Describe the bug**
1. I'm creating a script to run suites using test runner
2. Here is my file called "runTests.js"

```
const Launcher = require('@wdio/cli').default;

const runTest = () => {
 
  const wdio = new Launcher('./config/local.conf.js');
  wdio.run({ spec: 'MySpecFile.spec.js' }).then(
    (code) => {
      process.exit(code);
    },
    (error) => {
      console.error('Launcher failed to start the test', error.stacktrace);
      process.exit(1);
    },
  );
};

module.exports = runTest();
 ```
3. I created this script on package.json:  
 "run-test":"node ./scripts/runTests.js"

**To Reproduce**
When I execute "**npm run run-test**"  the runner start to run all specs files instead the specific one called "MySpecFile.spec.js"

**Expected behavior**
I'm expected that only "MySpecFile.spec.js" runs. 
I the future I hope to change  spec: 'MySpecFile.spec.js' with suite: 'MySuite' in order to run specific suites.

**Comment by christian-bromann** [comment]
@Yanela-ipsy I believe I was not quite correct with my suggestion. I looked into it and updated [the docs](https://webdriver.io/docs/setuptypes#package-api-2). The arguments to overwrite the config are suppose to go into the `Launcher` constructor, e.g.:
```js
const wdio = new Launcher(
    '/path/to/my/wdio.conf.js',
    { spec: '/path/to/a/single/spec.e2e.js' }
)

wdio.run().then((exitCode) => {
    process.exit(exitCode)
}, (error) => {
    console.error('Launcher failed to start the test', error.stacktrace)
    process.exit(1)
})
```

**Comment by Yanela-ipsy** [comment]
Hi @christian-bromann many thanks!! 
to run specific suite we can use the same logic right?
const wdio = new Launcher(
    '/path/to/my/wdio.conf.js',
    { suite: 'suiteName' }
)

**Comment by christian-bromann** [comment]
Correct!
