### ISSUE TITLE
Is it possible to launch multiple tests via selenium grid and Appium?

### ISSUE THREAD

**Issue by robertfausk** [webdriverio/webdriverio#693]
I want to have an inside running test system where I can run tests in parallel on desktop and mobile web browser.

My current architecture is as follows:
I have a selenium grid connected with multiple Appium server.
I'm using wdio.conf.js which connects to the selenium hub.

When I'm starting a test on one android device it's working fine but when I'm starting a test on more than one android device in parallel it says:
```
ERROR: A new session could not be created. (Original error: Requested a new session but one was in progress)
```

I wonder what I'm doing wrong. Any help would be appreciated:) I can also provide my config files and any further information.

**Comment by christian-bromann** [comment]
@robertfausk so for getting back to you now. Did you get your setup working in the meantime?
It should be possible as far as I know but not 100% sure. Could be that you can only spawn on emulator in your system. Or maybe this is an Appium config.

**Comment by christian-bromann** [comment]
Closed due to inactivity
