### ISSUE TITLE
Error accessing .this in a custom command function

### ISSUE THREAD

**Issue by jontxo** [webdriverio/webdriverio#6936]
**Environment
 - **WebdriverIO version:7.6.1
 - **Mode:WDIO Testrunner sync
 - **Node.js version:4.17.0
 - **NPM version:6.14.13
 - **Browser name and version:Chrome 91
 - **Platform name and version:Archlinux
 - **Additional wdio packages used (if applicable):@wdio/local-runner, @wdio/cli, @wdio/config, @wdio/cucumber-framework, @wdio/dot-reporter,@wdio/mocha-framework, @wdio/protocols, @wdio/selenium-standalone-service, @wdio/spec-reporter, @wdio/sync, @wdio/types

**Describe the bug**
In my project the implementation of the custom commands is defined in the class CustomCommands. In the functions that implement the method, for example: 

    browser.addCommand( 'waitForClickable', function ( ms = 5 ): boolean {

      return this.waitForDisplayed( { timeout: <number>ms } );
      // Return browser.waitForDisplayed(this.element().selector,ms) && browser.waitForEnabled(this.element().selector,ms);
    }, true );

The following error appears in the lines with the this: 'this' implicitly has type 'any' because it does not have a type annotation.ts(2683)

**To Reproduce**
Compile this project: https://github.com/yon-cuadrado-projects/webdriverio-cucumber-typescript

**Expected behavior**
The project compiles correctly.

**Comment by christian-bromann** [comment]
```ts

**Comment by christian-bromann** [comment]
According to the [Typescript documentation](https://www.typescriptlang.org/docs/handbook/functions.html#this-parameters):

> you can provide an explicit this parameter. this parameters are fake parameters that come first in the parameter list of a function

```ts
browser.addCommand( 'waitForClickable', function (this: WebdriverIO.Browser, ms = 5 ): boolean {

  return this.waitForDisplayed( { timeout: <number>ms } );
  // Return browser.waitForDisplayed(this.element().selector,ms) && browser.waitForEnabled(this.element().selector,ms);
}, true );
```
