### ISSUE TITLE
custom tsconfig seems to be ignored

### ISSUE THREAD

**Issue by Joozty** [webdriverio/webdriverio#6939]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.6.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 16.0.0
 - **NPM version:** 7.10.0
 - **Browser name and version:** Chrome 90
 - **Platform name and version:** MacOS 11.4
 - **Additional wdio packages used (if applicable):** Additional packages can. be found in [package.json](https://github.com/Joozty/wdio-ts/blob/main/test/package.json)

**Config of WebdriverIO**
I followed [TS tutorial](https://webdriver.io/docs/typescript/) on your page.

**Describe the bug**
I created a repository to demonstrate the bug. Basically, I use mono repository structure which contains two packages - `test` and `core` (`@test/core`). Both packages use Typescript. 

 [`@test/core` package](https://github.com/Joozty/wdio-ts/blob/main/core/package.json#L2) is imported in tests. Additionally to that I use two tsconfig files ([`tsconfig.json`](https://github.com/Joozty/wdio-ts/blob/main/test/tsconfig.json) and [`tsconfig-prod.json`](https://github.com/Joozty/wdio-ts/blob/main/test/tsconfig-prod.json)). The reason behind it is that `tsconfig.json` is used only by my IDE so I can correctly navigate to [`core/src` folder](https://github.com/Joozty/wdio-ts/blob/main/test/tsconfig.json#L5)  when I click on import link (custom path is defined).  `tsconfig-prod.json` doesn't use custom path so `@test/core` is resolved correctly to `test/dist/index.js`.

In the config file I explicitly defined that wdio should use [tsconfig-prod file](https://github.com/Joozty/wdio-ts/blob/main/test/wdio.conf.ts#L8) however when I run the test it fails and says that [`require.resolve("@test/core")` points to `<absolute_path>/core/src/index.ts`](https://github.com/Joozty/wdio-ts/blob/main/test/src/specs/example.e2e.ts#L5) which is wrong since it should point to `<absolute_path>/core/dist/index.js`

To me it seems that typescript loads still tsconfig.json event different project is defined in `wdio.conf.ts`

**To Reproduce**
Just clone the repository and install the packages and then run test command

https://github.com/Joozty/wdio-ts

**Expected behavior**
Test should pass without any error.

**Comment by christian-bromann** [comment]
Hey @Joozty thanks for filling the issue. I checked the repo and `ts-node` register is called with the properties you've provided in your wdio.conf.js. I honestly don't know really if this is a misconfiguration with TS or something else.

**Comment by Joozty** [comment]
@christian-bromann Thanks for looking into it. 🙂 

I doubt it's a misconfiguration of TS. I use this approach in different projects that uses webpack, plain tsc or even ts-node and it works just fine. 🤷

**Comment by Assone** [comment]
me too

**Comment by christian-bromann** [comment]
@Joozty any updates on this?

**Comment by Joozty** [comment]
not really it's still an issue and don't know how to solve it. 😞

**Comment by kopax-polyconseil** [comment]
> not really it's still an issue and don't know how to solve it. disappointed

If it helps you : https://github.com/webdriverio/webdriverio/issues/9151#issuecomment-1305990270

**Comment by christian-bromann** [comment]
This bug is now fixed with latest v8
