### ISSUE TITLE
expect failed with Expected: "displayed"     Received: "not displayed"

### ISSUE THREAD

**Issue by sqagithub** [webdriverio/webdriverio#6959]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [^7.5.7]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [async]
 - **Node.js version:** [v14.17.0]
 - **NPM version:** [6.14.13]
 - **Browser name and version:** [e.g. Chrome 91]
 - **Platform name and version:** [e.g. Windows 10]
"devDependencies": {
    "@babel/cli": "^7.13.16",
    "@babel/core": "^7.14.2",
    "@babel/preset-env": "^7.14.2",
    "@babel/register": "^7.13.16",
    "@wdio/allure-reporter": "^7.7.0",
    "@wdio/cli": "^7.5.7",
    "@wdio/local-runner": "^7.5.7",
    "@wdio/mocha-framework": "^7.5.3",
    "@wdio/spec-reporter": "^7.5.7",
    "chromedriver": "^90.0.0",
    "prettier": "2.3.0",
    "wdio-chromedriver-service": "^7.0.0"

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
expect failing on toBeDisplayed in async 

**To Reproduce**

bingo.js
class bingoPage {

get customersTab() {
		return $(
			'//span[@class="button-text" and text()="Customers xxx"]//parent::button'
		)
	}
	
	}
	
	

default.js
	
	it('Step 3: Validate xxxxxx', async () => {
		await commonPage.drawer()
	
		**await expect(bingoPage.customersTab).toBeDisplayed()**
	})
	
	
	
	ERROR MESSAGE:
	
	Expect $('//span[@class="button-text" and text()="Customers xxx"]//parent::button')to be displayed
    Expected: "displayed"
    Received: "not displayed"

**Expected behavior**

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by sqagithub** [comment]
sample.js
const samplePage = require("../pageobjects/sample.page")



/*
Created By:   
Workflow:     
Description:  This test creates a sample test
*/

describe('Scenario: Login into website', async () => {
	it('Step 1: Launch website', async () => {
		await browser.url('https://devexpress.github.io/testcafe/example/')
		await browser.pause(6000)
        await samplePage.validatePage()
		
	
	})
})

sample.page.js
class samplePage {
	get cafeText() {
		return $(
			'//p[text()="This webpage is used as a sample in TestCafe tutorials."]'
		)
	}

	get yourname() {
		return $('//input[@id="developer-name"]')
	}

	get populateBtn() {
		return $('//input[@type="button" and @id="populate"]')
	}

	get textLabel() {
		$('//label[@for="remote-testing"]')
	}

	get resetDialog() {
		$()
	}

	async validatePage() {
		await (await this.cafeText).isDisplayed()
		await (await this.yourname).addValue('Michael')
		await (await this.populateBtn).waitForExist()
		await browser.pause(6000)
		await expect(this.populateBtn).toBeDisplayed() // button works
		await expect(this.textLabel).toBeDisplayed() // this does not work
	}
}

module.exports = new samplePage()


Error Message:
0-0] Error in "Scenario: Login into website Step 1: Launch website"
Error: Expect  to be displayed

Expected: "displayed"
Received: "not displayed"
    at samplePage.validatePage (C:\dev\automation-ui\wdioautomation\test\pageobjects\/sample.page.js:30:32)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Context.<anonymous> (C:\dev\automation-ui\wdioautomation\test\features\/sample.js:15:9)
    at Context.executeAsync (C:\dev\automation-ui\wdioautomation\node_modules\@wdio\utils\build\shim.js:136:16)
    at Context.testFrameworkFnWrapper (C:\dev\automation-ui\wdioautomation\node_modules\@wdio\utils\build\test-framework\testFnWrapper.js:52:18)
[0-0] 2021-06-02T14:45:58.735Z INFO webdriver: COMMAND deleteSession()
[0-0] 2021-06-02T14:45:58.735Z INFO webdriver: [DELETE] http://localhost:9515/session/bf49bb8150de2a11008e3e94cbdf3977
[0-0] FAILED in chrome - C:\dev\automation-ui\wdioautomation\test\features\sample.js

**Comment by mgrybyk** [comment]
Is this.textLabel actually visible?
Can you log it's visibility state in console?

Expect library relies on isDisplayed method of webdriverio. If it returns false there is nothing we can do. In such case you have to adjust your selector to check visibility of one of its parents instead.

**Comment by sqagithub** [comment]
I am closing this ticket. This may be iframe issue.
