### ISSUE TITLE
element as first class citizen

### ISSUE THREAD

**Issue by lutzj82** [webdriverio/webdriverio#696]
I'd like to see the element become more of a first class citizen.  What I mean by this, is that instead of:

driver.setValue('#someinputEl', 'value');

I'd like to more of the following:

driver.element('#someinputEl').setValue('value');

It actually works for any command that takes a single argument (selector), such as getText or getValue
I just think it reads easier, and allows me to create functions representing each element.

Thanks

**Comment by christian-bromann** [comment]
@lutzj82 this is almost the case. Thinks like

```html
<div class="row">
  <div class="entry">
    <label>Product A</label>
    <button>Add to cart</button>
    <button>More Information</button>
  </div>
  <div class="entry">
    <label>Product B</label>
    <button>Add to cart</button>
    <button>More Information</button>
  </div>
  <div class="entry">
    <label>Product C</label>
    <button>Add to cart</button>
    <button>More Information</button>
  </div>
</div>
````
```js
var row = yield client.element('.row .entry:nth-Child(1)');
yield row.click('button*=Add');
```
already work. I guess it should be possible to avoid the element argument if your last command call was the element command. It is just kinda hard to explain that to users like, you can do
```js
client.click('#myelement');
```
but
```js
var myelement = client.element('#myelement');
myelement.click();
```

**Comment by lutzj82** [comment]
I get it...I guess since there was support for element chaining, it seems like a logical extension.  I agree that I don't want it to be confusing though.

**Comment by christian-bromann** [comment]
Moving into icebox. I get your point here but I don't 100% agree with you. One of the characteristics of E2E tests are that they get executed from the viewpoint of the user. Therefor:

__The User__ -> _clicks_ -> on `elementA`

which is exactly the reason why we have designed the API how it is:

__`browser.`__ _`click`_ `('#elementA')`

However your argument makes sense when receiving attributes from certain elements (e.g. `getCSSProperty`, `getLocation` or `isVisible`). This could confuse other people though :smile: .. I will leave it as it is for now and keep it open so other people can comment on this.

**Comment by christian-bromann** [comment]
WebdriverIO (v4) now internally remembers the last result of a command. If you chain an element command with an action command it finds the element from the previous command and uses the result to execute the action. With that you can remove the selector (first parameter) and the command looks as simple as:

```js
var elem = browser.element('#username');
elem.setValue('Max Mustermann');
```

which is basically the same thing as:

```js
browser.element('#username').setValue('Max Mustermann');
```

or

```js
browser.setValue('#username', 'Max Mustermann');
```
