### ISSUE TITLE
Detect headless mode

### ISSUE THREAD

**Issue by Joozty** [webdriverio/webdriverio#6972]
**Is your feature request related to a problem? Please describe.**
Not sure if this is technically doable (probably not) but I will ask anyway.  Would it be possible to expose flags that the browser is run with? 

I have some tests that cannot be run in headless mode and I would like to detect whether the browser is run in headless or not headless mode something like `driver.isHeadless` || `browser.isHeadless`

I know there are some [techniques to detect headless mode](https://stackoverflow.com/questions/44397492/detect-chrome-running-in-headless-mode-from-javascript) which could be used as an alternative however, I have also some tests that need to have disabled websecurity (`--disable-web-security`) and that's harder to detect I guess.

**Comment by christian-bromann** [comment]
@Joozty thanks for filing the issue.

I believe what you can try to do is open the `chrome://version` page to find out which flags are set in the beginning of the session. Would that solve your issue?

**Comment by BorisOsipov** [comment]
@Joozty you can access current session capabilities by `console.log(browser.requestedCapabilities)` and check are there headless option or not for current browser.

**Comment by Joozty** [comment]
Thanks, guys. `browser.requestedCapabilities` was the thing I was looking for. 


For future readers I solved my problem with this code (using mocha and chrome):


```ts
type ChromeFlags = '--headless' | '--no-sandbox' // there is more flags...

const disableInHeadlessMode = (name: string, callback: () => Promise<void>) => {
	it(name, async function () {
		const browserCapabilities = browser.requestedCapabilities as {
			'goog:chromeOptions'?: { args: ChromeFlags[] }
		}
		const chromeOptions = browserCapabilities['goog:chromeOptions']
		if (chromeOptions?.args?.includes('--headless')) this.skip()
		else await callback()
	})
}

describe('test', () => {
	disableInHeadlessMode('1', async () => {
		expect(1).toBe(1)
	})
})
```


btw. it would be nice if [`requestedCapabilities`](https://github.com/webdriverio/webdriverio/blob/9d2220e89144b0ca69232737957ad5fc32ca1300/packages/webdriver/src/types.ts#L28) exposed also `goog:ChromeOptions`. As you can see in my example I had to assert custom type to it so I could use it correctly.

**Comment by christian-bromann** [comment]
> As you can see in my example I had to assert custom type to it so I could use it correctly.

Unfortunately `requestedCapabilities` can defined in multiple ways, e.g.:

```js
// jwp way
{
     browserName: 'chrome'
}
// webdriver way
{
     alwaysMatch: { browserName: 'chrome' }
}
// multiremote way
'chromeBrowser': { capabilities: { browserName: 'chrome' } }
```

Therefor I recommend to do:

```ts
import { Capabilities } from '@wdio/types'
const browserCapabilities = browser.requestedCapabilities as Capabilities.DesiredCapabilities
```
