### ISSUE TITLE
newWindow called twice opens only one window

### ISSUE THREAD

**Issue by Joozty** [webdriverio/webdriverio#6973]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.6.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 16.0.0
 - **NPM version:** 7.10.0
 - **Browser name and version:** chrome 91
 - **Platform name and version:** MacOS 11.3
 - **Additional wdio packages used (if applicable):**  none

**Config of WebdriverIO**
An example of how you configured WebdriverIO config
Just the default config nothing specific there

**Describe the bug**
When I call `newWindow` command twice it opens newWindow and the second call just opens the page in the current window

**To Reproduce**

```js
describe('newWindow', () => {
	it(`open two windows`, async () => {
		await browser.newWindow('https://yahoo.com')
		await browser.newWindow('https://google.com') // yahoo.com window gets overridden by google.com
		await browser.debug()
	})
})

```

**Comment by christian-bromann** [comment]
As the docs mention this command is a proxy for `window.open` which exactly behaves this way. It would only open in a new tab if you don't call this command out of a window that was opened with `window.open`. If you want to create a new window/tab every time you need to use [`browser.createWindow`](https://webdriver.io/docs/api/webdriver#createwindow).

**Comment by Joozty** [comment]
I tested your theory and even if I call `window.open()` in a window that was previously opened via `window.open` it opens a new tab just fine. 

I also don't see any mention about it in the [official documentation](https://developer.mozilla.org/en-US/docs/Web/API/Window/open) 🤔

**Comment by christian-bromann** [comment]
Well given that `newWindow` does exactly that, why is it not working then?

> it opens a new tab just fine.

Just tried again and can confirm, not sure why it was not working when I tried last time. Any help on this would be appreciated. Thanks!

**Comment by praveendvd** [comment]
```


describe('My Login application', () => {
  it('should login with valid credentials', async () => {
    //await b.url("https://www.google.com")
    await browser.newWindow('https://webdriver.io', {
      windowName: 'WebdriverIO window'
    })
    await browser.debug()

    await browser.newWindow('https://www.google.com', {
      windowName: 'Google window',
    }) // yahoo.com window gets overridden by google.com
    await browser.debug()

  });


});



```

@Joozty 
you have to give windowname which unique else it will take the previous one

**Comment by Joozty** [comment]
Thanks @praveendvd you are right.  This solves the problem. It would be nice to have it in documentation I guess.



There is also a problem with `closeWindow` method. When I try to close window as a user I would expect to get context back to previous window but that doesn't work and I need to explicitly change the context like this:


```
		await browser.newWindow('https://yahoo.com', {windowName: 'window1'})
		await browser.newWindow('https://google.com', {windowName: 'widnow2'}) 
		const handles = await browser.getWindowHandles()
		await browser.switchToWindow(handles[0])
                // Do something on the yahoo page
```

**Comment by Joozty** [comment]
Thanks @praveendvd you are right.  This solves the problem. It would be nice to have it in documentation I guess.



There is also a problem with `closeWindow` method. When I try to close window as a user I would expect to get context back to previous window but that doesn't work and I need to explicitly change the context like this:


```
		await browser.newWindow('https://yahoo.com', {windowName: 'window1'})
		await browser.newWindow('https://google.com', {windowName: 'widnow2'}) 
		const handles = await browser.getWindowHandles()
		await browser.switchToWindow(handles[0])
                // Do something on the yahoo page
```

**Comment by praveendvd** [comment]
> Thanks @praveendvd you are right.  This solves the problem. It would be nice to have it in documentation I guess.
> 
> 
> 
> There is also a problem with `closeWindow` method. When I try to close window as a user I would expect to get context back to previous window but that doesn't work and I need to explicitly change the context like this:
> 
> 
> ```js
>      await browser.newWindow('https://yahoo.com', {windowName: 'window1'}) 
>      await browser.newWindow('https://google.com', {windowName: 'widnow2'}) 
>      const handles = await browser.getWindowHandles()
>      await browser.switchToWindow(handles[0])
>      // Do something on the yahoo page
> ```

You can create a Pull request with document changes if you could ,or else I can do it let me know

**Comment by Joozty** [comment]
@praveendvd sorry for late reply. Feel free to do it. 🙂

**Comment by christian-bromann** [comment]
> There is also a problem with `closeWindow` method. When I try to close window as a user I would expect to get context back to previous window but that doesn't work and I need to explicitly change the context like this:

Since `closeWindow`is a protocol command it only does closing the window. We could consider adding a WDIO command that is a bit more smart about it. However, making a change within the docs mentioning the handle change would be also a good first step.

**Comment by christian-bromann** [comment]
@Joozty or @praveendvd anyone up to the task? Happy to help!

**Comment by praveendvd** [comment]
> @Joozty or @praveendvd anyone up to the task? Happy to help!

So this should be just documentation update if I am not wrong ? I could take it up

**Comment by praveendvd** [comment]
@christian-bromann  what is the actual use of windowName , we can't use it to switchWindow function also . Is there any other place we are using it ? . It would make sense to make switchWindow accept windowName else remove that altogether from newWindow

**Comment by christian-bromann** [comment]
> It would make sense to make switchWindow accept windowName else remove that altogether from newWindow

I think that could be a useful feature.

Another option is to attach a random number to the window name to ensure it opens in a new tab.

**Comment by christian-bromann** [comment]
Let's continue conversation in #7224
