### ISSUE TITLE
browser.reset ➞ browser.resetApp

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#6977]
Convention seems to be that Appium commands have their name mapped 1:1 to webdriverIO commands.
This isn't the case for `resetApp` which is `reset`.
Let's be conventional but try to keep backwards compatibility.

✅ closeApp ➞ browser.closeApp
✅ launchApp ➞ browser.launchApp
❌ resetApp ➞ browser.reset

**Comment by christian-bromann** [comment]
@nextlevelbeard sounds reasonable to me, mind taking a stab at it? I suggest to keep `reset` and throw a deprecation warning. Once we make the next major release we can clean it up.

**Comment by christian-bromann** [comment]
Thanks @srikanthgurram for tackling this 👍
