### ISSUE TITLE
WDIO Configuration Helper run test command for typescript is not correct

### ISSUE THREAD

**Issue by sadabnepal** [webdriverio/webdriverio#6978]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Description of the improvement / report**
WDIO Configuration Helper suggest `npx wdio wdio.conf.js` command to run test but when we select compiler as typescript `wdio.conf.ts` file is being generated and hence command should suggest `npx wdio wdio.conf.ts`

**Comment by praveendvd** [comment]
it depends on what compiler you use  and also you don't have  to specify the config file . You can run it as npx wdio

**Comment by christian-bromann** [comment]
@sadabnepal you want to take a stab at this? You can find the log message [here](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-cli/src/commands/config.ts#L196). I suggest to use `util.format` and pass in the actual file name with the correct suffix.

**Comment by christian-bromann** [comment]
Fixed in #6979
