### ISSUE TITLE
Ensure `keys` use a mobile equivalent when run in native context

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#6981]
Currently if someone runs `browser.keys("foobar")` in a native context Appium throws an error given that `performActions` commands aren't supported in native context.

I suggest:
- check if `isMobile` flag is enabled
- if so read the context
- if context is not web use JWP keys command or something equivalent to that

**Comment by stormtroopa** [comment]
Key-input is absolutely essential for our tests. We definitely need this to be fixed. Without key-input, testing our applications on all targets on saucelabs will stay a dream.
Can you tell if and when this problem can be solved?

**Comment by christian-bromann** [comment]
@stormtroopa you can always use the Appium protocol commands to do key input, there is no need to wait for this enhancement to land. This just simplifies the usage. Please get involved and help the community implement this.

**Comment by christian-bromann** [comment]
Not sure if it is a good idea to rely on deprecated protocols. I reached out to the Appium team to ask for advice on what is the best approach for key events in native contexts.

**Comment by christian-bromann** [comment]
Apparently `performActions` is supported for native contexts too, see https://appiumpro.com/editions/46-sending-arbitrary-keystrokes-with-the-actions-api. Closing. Please let me know if anyone experiences issues and say which platform.
