### ISSUE TITLE
Calling `browser.mock` in a docker container fails with `ECONNREFUSED`

### ISSUE THREAD

**Issue by johnson-tyl** [webdriverio/webdriverio#6997]
If you run a test that needs `browser.mock` inside docker container, it fails on node-fetch ClientRequest with `ECONNREFUSED` error.

**Exception**:
```javascript
FetchError: Failed to fetch browser webSocket URL from http://localhost:39857/json/version: request to http://localhost:39857/json/version failed, reason: connect ECONNREFUSED 127.0.0.1:39857
    at ClientRequest.<anonymous> (C:\Users\user\workspace\node.js\tyl-e2e-reviews\node_modules\node-fetch\lib\index.js:1461:11)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at Browser.runCommandWithHooks (C:\Users\user\workspace\node.js\tyl-e2e-reviews\node_modules\@wdio\sync\build\wrapCommand.js:100:24)
    at Browser.wrapCommandFn (C:\Users\user\workspace\node.js\tyl-e2e-reviews\node_modules\@wdio\sync\build\wrapCommand.js:67:44)
    at LoginPage.setPassword (C:\Users\user\workspace\node.js\tyl-e2e-reviews\tests\pages\app\application\login.page.js:36:29)
```

**NOTE**: The port seen above is not same every time, so cant expose it either.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.6.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** [e.g. 8.11.2] v12.18.3
 - **NPM version:** [e.g. 5.8.0] v6.14.11
 - **Browser name and version:** Chrome 91
 - **Platform name and version:** Docker - [image: standalone-chrome-debug]( https://hub.docker.com/r/selenium/standalone-chrome-debug)
 - **Additional wdio packages used (if applicable):** wdio-docker-service

**Config of WebdriverIO**
```javascript
exports.config = {
    runner: 'local',
    hostname: 'localhost',
    path: '/wd/hub',
    outputDir: './logs',

    capabilities: [
	{
		"maxInstances": 5,
		"browserName": "chrome",
		"goog:chromeOptions": {
			"args": [
				"--start-maximized"
			],
			"prefs": {
				"credentials_enable_service": false,
				"profile": {
					"password_manager_enabled": false
				}
			}
		}
	}],
	services:
        [
            [wdioScreenshot],
            'shared-store',
            'docker'
        ],
    dockerOptions: {
        image: 'selenium/standalone-chrome-debug',
        healthCheck: {
            url: 'http://localhost:4444',
            maxRetries: 3,
            inspectInterval: 1000,
            startDelay: 2000
        },
        options: {
            p: ['4444:4444', '5900:5900'],
            shmSize: '2g'
        }
    },
    dockerLogs: 'logs',
}
```

**Describe the bug**
I am running my existing local tests inside the docker container using the `wdio-docker-service` and the tests that were running successfully locally dont run inside the container, where it encounters the `browser.mock()` call, its throwing the error mentioned above.

**To Reproduce**

1. Setup a project with latest WebdriverIO and `wdio-docker-service`
2. Write a test that uses `browser.mock()`
3. Setup the tests to run inside the container using the instructions from [here](https://github.com/stsvilik/wdio-docker-service/wiki/Selenium-Docker:-Viewing-tests-as-they-run) 
4. Run the tests

**Expected behavior**
The test should pass when running inside the container.

**Log**
Nothing in logs, see the exception above.

**Comment by christian-bromann** [comment]
> ```js
> request to http://localhost:39857/json/version failed, reason: connect ECONNREFUSED 127.0.0.1:39857
> ```

Your Docker setup needs to expose `39857` to allow connecting with the DevTools service. I recommend to create an issue in the [Docker service](https://github.com/stsvilik/wdio-docker-service). This can't be fixed within WebdriverIO.

**Comment by johnson-tyl** [comment]
@christian-bromann this port is random, I did mention that in my original bug report, is it possible to keep it fixed in WDIO as its created by Devtools

![image](https://user-images.githubusercontent.com/63800148/121370063-50710a80-c934-11eb-802f-0a3cecd9ebe6.png)

**Comment by christian-bromann** [comment]
> is it possible to keep it fixed in WDIO as its created by Devtools

It is not given you use Docker as WebDriver backend. And if the Docker service doesn't allow a way to create that connection there is nothing WebdriverIO can do.

**Comment by johnson-tyl** [comment]
The problem is not WebdriverIO but Devtools or Docker service but I am also wondering if its trying to connect to something on the host machine, this call should be exclusively local to the container and not trying to access anything outside of it. I have logged an issue with docker service as well, https://github.com/stsvilik/wdio-docker-service/issues/104, there's already a similar one open there, https://github.com/stsvilik/wdio-docker-service/issues/78

**Comment by christian-bromann** [comment]
Correct, these are the same issues. Thanks for raising the issue there.
