### ISSUE TITLE
Improve setViewportSize logic

### ISSUE THREAD

**Issue by amitaibu** [webdriverio/webdriverio#700]
Better handle window size, as now we loop for 5 times and hope for the best :)

Continuing [this](https://github.com/webdriverio/webdrivercss/issues/102) issue here.

**Comment by amitaibu** [comment]
We are currently iterating multiple times, trying to reach the size we want. It seems the width is set on the first time, but height isn't (and it may not be set properly). Here's a printout of the process. Note the height isn't set "correctly" in the end (but the question is why do we care about the height)

```
not yet....
{ sessionId: '25610f0d8525c9bf614c2e7853e790de',
  status: 0,
  value: { screenHeight: 635, screenWidth: 960 } }
not yet....
{ sessionId: '25610f0d8525c9bf614c2e7853e790de',
  status: 0,
  value: { screenHeight: 635, screenWidth: 960 } }
not yet....
{ sessionId: '25610f0d8525c9bf614c2e7853e790de',
  status: 0,
  value: { screenHeight: 635, screenWidth: 960 } }
not yet....
{ sessionId: '25610f0d8525c9bf614c2e7853e790de',
  status: 0,
  value: { screenHeight: 635, screenWidth: 960 } }
****************
Result:
{ screenHeight: 635, screenWidth: 960 }
Size:
{ width: 960, height: 707 }
****************
```

How about changing [this](https://github.com/webdriverio/webdriverio/blob/master/lib/commands/setViewportSize.js#L83-L84) part to care only about the width?

```js
if (retryNo < MAX_TRIES && res.value.screenWidth !== size.width) {
```

**Comment by christian-bromann** [comment]
Let's continue the discussion in #701
