### ISSUE TITLE
Include console messages in spec report

### ISSUE THREAD

**Issue by db798** [webdriverio/webdriverio#7001]
**Is your feature request related to a problem? Please describe.**

In the current implementation of the spec reporter, console logs are written to the console at runtime while the the spec output is written on test completion. This makes debugging failures difficult as you can't quickly associated logs with specs.

In the example below I need to do some looking to be able to associate the logs with appropriate spec.
```
12:12:57  [0-0] RUNNING in MultiRemote - myFeature.feature
...My message from console.log....    
... logging an entity name...
... logging an entity GUID...
12:14:15  [0-0] PASSED in MultiRemote - myFeature.feature

12:14:27  [0-1] RUNNING in MultiRemote - myFeature2.feature
... more console.log messages are printed...
... logging another entity name...
... logging another entity GUID...
12:15:08  [0-1] PASSED in MultiRemote - myFeature2.feature

12:15:12   "spec" Reporter:
12:15:12  ------------------------------------------------------------------
12:15:12  [MultiremoteBrowser #0-0] Running: MultiremoteBrowser on chrome, chrome
12:15:12  [MultiremoteBrowser #0-0]
12:15:12  [MultiremoteBrowser #0-0] » /myFeature.feature
12:15:12  [MultiremoteBrowser #0-0] Test 1
12:15:12  [MultiremoteBrowser #0-0] Scenario 1
12:15:12  [MultiremoteBrowser #0-0]    ✓ Step 1
12:15:12  [MultiremoteBrowser #0-0]    ✓ Step 2
......
12:15:12  [MultiremoteBrowser #0-0] 2 passing (59.7s)
12:15:12  ------------------------------------------------------------------
12:15:12  [MultiremoteBrowser #0-1] Running: MultiremoteBrowser on chrome, chrome
12:15:12  [MultiremoteBrowser #0-1]
12:15:12  [MultiremoteBrowser #0-1] » /myFeature2.feature
12:15:12  [MultiremoteBrowser #0-1] Test 2
12:15:12  [MultiremoteBrowser #0-1] Scenario 2
12:15:12  [MultiremoteBrowser #0-1]    ✓ Step 1
12:15:12  [MultiremoteBrowser #0-1]    ✓ Step 2
....
12:15:12  [MultiremoteBrowser #0-1] 2 passing (31.4s)
```

**Describe the solution you'd like**
Ideally the console messages would be logged as part of the spec report on test completion, like below.

```
12:15:12   "spec" Reporter:
12:15:12  ------------------------------------------------------------------
12:15:12  [MultiremoteBrowser #0-0] Running: MultiremoteBrowser on chrome, chrome
12:15:12  [MultiremoteBrowser #0-0]
12:15:12  [MultiremoteBrowser #0-0] » /myFeature.feature
12:15:12  [MultiremoteBrowser #0-0] Test 1
12:15:12  [MultiremoteBrowser #0-0] Scenario 1
12:15:12  [MultiremoteBrowser #0-0]    ✓ Step 1
12:15:12  [MultiremoteBrowser #0-0]    My message from console.log
12:15:12  [MultiremoteBrowser #0-0]    ✓ Step 2
```

**Describe alternatives you've considered**

**Additional context**

We are looking to move from Protractor and the proposed solution is how it works there, e.g. below is a modified sample protractor output.

```
11:49:43  [firefox #11] Feature: My Feature Name
11:49:43  [firefox #11] 
11:49:43  [firefox #11]   Scenario: 1
11:49:43  [firefox #11]     Step 1
11:49:43  [firefox #11]     Step 2
11:49:43  [firefox #11] 
11:49:43  [firefox #11]   Scenario: 2
11:49:43  [firefox #11]     Step 3
11:49:43  [firefox #11] 10:49:26.445Z  INFO Visiting url: <my-url>
11:49:43  [firefox #11] 10:49:29.619Z  INFO cookie value 1: 3a4319e0-99a7-4239-9ef7-6a2a14500526
11:49:43  [firefox #11] 10:49:29.619Z  INFO cookie value 2: 0f3e8e7f-013b-410f-8d59-5d9d6d4ed837
11:49:43  [firefox #11]     Step 4
11:49:43  [firefox #11]     Step 5
11:49:43  [firefox #11] 
11:49:43  [firefox #11] 2 scenarios (2 passed)
11:49:43  [firefox #11] 5 steps (5 passed)
11:49:43  [firefox #11] 2m00.848s
```

**Comment by christian-bromann** [comment]
I suggest to create a reporter option that allows to embed console.log lines within the report and then implement as suggested above.

Any contributions to this are appreciated.

**Comment by praveendvd** [comment]
> I suggest to create a reporter option that allows to embed console.log lines within the report and then implement as suggested above.
> 
> Any contributions to this are appreciated.

@christian-bromann 

Hi i have added this to allure-report using 👍 

        const originalStdoutWrite = process.stdout.write.bind(process.stdout);

        process.stdout.write = (chunk, encoding, callback) => {
            if (typeof chunk === 'string') {
                output += chunk;
            }

            return originalStdoutWrite(chunk, encoding, callback);
        };
        
        
  
![image](https://user-images.githubusercontent.com/45095911/123992979-f8be4000-d9c3-11eb-9a62-492419b7aa00.png)


is it a good approach should i do this for spec and create a pull request ?

**Comment by praveendvd** [comment]
@christian-bromann 

![image](https://user-images.githubusercontent.com/45095911/124020540-4d70b380-d9e2-11eb-9b7a-b0e67013f50a.png)

**Comment by christian-bromann** [comment]
@praveendvd that looks awesome, can you raise a PR for it?

**Comment by praveendvd** [comment]
Will do that thanks @christian-bromann

**Comment by christian-bromann** [comment]
PR raised and merged, thanks @praveendvd
