### ISSUE TITLE
Get rid of `browser.config` and only use `browser.options` everywhere

### ISSUE THREAD

**Issue by NIBOSAP** [webdriverio/webdriverio#7005]
**Environment :**
 - **WebdriverIO version:** tested 7.3.0 and 7.7.3
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** Node 12
 - **NPM version:** 6.14.5

**Config of WebdriverIO**

A simple config file with: 

```
region: 'eu',
```

**Describe the bug**

The config given to the reporter doesn't contain "region". As, for what I understand, region is not in the constants [here](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/constants.ts#L31)

**To Reproduce**

Run a test with spec as reporter and breakpoint in the getTestLink() [here](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-spec-reporter/src/index.ts#L142)

**Expected behavior**

We have a reporter and we wanted to select the datacenter by using the config.region. As you tried [here](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-spec-reporter/src/index.ts#L163). 

Not sure that you want to get the region. So, It was just to know if you want to fix this or change the way to retrieve the datacenter. If it's the first option, we will have nothing to do on our side :).

Sorry if I missed something, i'm not an expert of webdriverio.

**Comment by christian-bromann** [comment]
I can't reproduce this. These were the steps I was running:

```sh
$ npm i @wdio/cli
$ npx wdio config
# pick, run on Sauce, region eu and disable chromedriver service
$ npx wdio
```

This created the following report:

```
 "spec" Reporter:
------------------------------------------------------------------
[chrome 91.0.4472.77 Windows #0-0] Running: chrome (v91.0.4472.77) on Windows
[chrome 91.0.4472.77 Windows #0-0] Session ID: 87dc017f2ac6488d8ef4b2bf8dc62bce
[chrome 91.0.4472.77 Windows #0-0]
[chrome 91.0.4472.77 Windows #0-0] » /test/specs/example.e2e.js
[chrome 91.0.4472.77 Windows #0-0] My Login application
[chrome 91.0.4472.77 Windows #0-0]    ✓ should login with valid credentials
[chrome 91.0.4472.77 Windows #0-0]
[chrome 91.0.4472.77 Windows #0-0] 1 passing (8.5s)
[chrome 91.0.4472.77 Windows #0-0]
[chrome 91.0.4472.77 Windows #0-0] Check out job at https://app.eu-central-1.saucelabs.com/tests/87dc017f2ac6488d8ef4b2bf8dc62bce?auth=12409632f782a44ebb3396c9ed4153b4
```

**Comment by NIBOSAP** [comment]
In fact, there is no errors. I was just pointing the fact that the ```config.region``` variable is undefined every time [here](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-spec-reporter/src/index.ts#L163):
```
const isEUCentral = ['eu', 'eu-central-1'].includes(config?.region || '') || (config.hostname?.includes('eu-central'))
```
Because when you give the config to a reporter, you are validating it with the validateConfig() method and some constants: [here](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/index.ts#L33).
And the "region" property (or key) is not in the constants to keep (or the keysToKeep [here](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-config/src/utils.ts#L44)), so the validateConfig drop it. 
And so, the config given to the reporter doesn't contain the property region.

### Reproduction Example

To reproduce it, you could do:
```
git clone https://github.com/serhatbolsu/webdriverio-mocha-uiautomation-boiler.git
npm i
```
Put a breakpoint at the line 48 of the node_modules/webdriver/build/index.js file. 
run the ```wdio.saucelabs.conf.js```

You will able to see that the ```params``` variable contains the "region" property. and if you step to the line 49, and check the ```config``` variable, you will see that the ```config``` variable doesn't contain the "region" property.

So, in all reporters, we don't have the ```config.region``` variable

**Comment by christian-bromann** [comment]
It seems that `browser.config` and `browser.options` are diverging. There is no reason to have both so I propose to to get rid of `browser.config`. We should make sure that custom configurations are propagated into `browser.options` and clean up [this part](https://github.com/webdriverio/webdriverio/blob/main/website/docs/BrowserObject.md#configurations-versus-options) of the docs. Any help on this is appreciated.
