### ISSUE TITLE
No specs found to run, exiting with failure in V7

### ISSUE THREAD

**Issue by TuHuynhVan** [webdriverio/webdriverio#7006]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.7.3
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:**  sync
 - **Node.js version:** 12.18.2
 - **NPM version:** [e.g. 5.8.0]
 - **Browser name and version:** appium 1.18.1

**Describe the bug**

**To Reproduce**
`npm run test-config.js`

https://github.com/madhukarapai/Mobile-Automation-WebdriverIO

**NOTE**
* If I downgrade webdriverio version to below, it worked.

```
"dependencies": {
    "@wdio/cli": "^6.4.6",
    "@wdio/local-runner": "^6.4.6",
    "@wdio/mocha-framework": "^6.4.0",
    "@wdio/sync": "^6.4.6",
    "webdriverio": "^6.4.6"
  },
  "devDependencies": {
    "@babel/cli": "^7.11.6",
    "@babel/core": "^7.11.6",
    "@babel/preset-env": "^7.11.5",
    "@babel/register": "^7.11.5",
    "@wdio/allure-reporter": "^6.8.1",
    "chai": "^4.2.0"
  }
```

**Comment by TuHuynhVan** [comment]
I found out the root cause. When we have an invalid config properties(in the example repo, we had typo for capabilities), even we have specs we will face that error, still a bug.

**Comment by christian-bromann** [comment]
@TuHuynhVan this is the expected behavior. We want to prevent that tests just pass in the case of a misconfiguration when actually no test are running.

**Comment by EINBOX** [comment]
@TuHuynhVan can you elaborate what is wrong in config? are you talking about capabilities? 
seems me too facing same issues, through config file I could able to run till launching browser on app but later my spec is not at all running..its just idle without moving to next next after the hook'before'

**Comment by almedin96** [comment]
I'm having issue after cloning your project, can you explain me where is the problem? 
![err](https://user-images.githubusercontent.com/76960581/156948193-a3183ed9-aca6-4199-8ba7-cbfcabc21c6d.PNG)

**Comment by satisk889** [comment]
copy the path and put it in spec .

 specs: [
        '/Users/rambo/Desktop/Boiler/trial1/tests/specs/login.spec.ts'
        // ToDo: define location for spec files here
    ],
