### ISSUE TITLE
Invalid or unsupported WebDriver capabilities found ("app", "appArguments") with WinAPPDriver

### ISSUE THREAD

**Issue by lacell75** [webdriverio/webdriverio#7007]
**Environment (please complete the following information):**
 - **WebdriverIO version:** latest
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 14.16.0
 - **NPM version:** 6.4.11
 - **Additional wdio packages used (if applicable):** services: ['winappdriver'],

**Config of WebdriverIO**

```
require('ts-node').register({ transpileOnly: true });

exports.config = {
    runner: "local",

    specs: ["./test/specs/*.ts"],
  
    maxInstances: 1,
  
    port: 4723,
    capabilities: [
      {
        app: "Microsoft.WindowsAlarms_8wekyb3d8bbwe!App",
        appArguments: '-noCloseConfirmationPopUp',
        "ms:experimental-webdriver": true,
        browserName: "",
      },
    ],
    logLevel: "trace",
    services: ["winappdriver"],
    framework: "jasmine",
    outputDir: ".\\reports",
    reporters: ["dot", ["junit", { outputDir: ".\\reports" }]],
  
    before() {
      //implicit wait for 5 seconds
      browser.setTimeout({ implicit: 5000 });
    },
  
    jasmineNodeOpts: {
      defaultTimeoutInterval: 30000,
      expectationResultHandler: function (passed, assertion) {
        /**
         * only take screenshot if assertion failed
         */
        if (passed) {
          return;
        }
  
        browser.getPageSource();
        browser.saveScreenshot(
          `.\\reports\\assertionError_${assertion.error.message}.png`
        );
      },
    }
}
```

**Describe the bug**
Unable to launch a test with WebDriverIO V7 on a windows application , please see this error : ` Error: Invalid or unsupported WebDriver capabilities found ("app", "appArguments"). Ensure to only use valid W3C WebDriver capabilities (see https://w3c.github.io/webdriver/#capabilities).`

**To Reproduce**

- Install this project and update WebdriverIO : https://github.com/licanhua/wdio-winappdriver-example
- npm run test

**Expected behavior**
The `app` and `appArguments`  capabilities should be accepted by webdriverIO

**Comment by christian-bromann** [comment]
> The `app` and `appArguments` capabilities should be accepted by webdriverIO

I disagree. These are invalid WebDriver capabilities. It seems that WinAppDriver is still lacking in supporting the protocol. See also microsoft/WinAppDriver#988

**Comment by lacell75** [comment]
@licanhua  Do you have a workaround to work with latest version of webdriverIO because WinAppDriver is not supported W3C protocol?

**Comment by christian-bromann** [comment]
@lacell75 one option would be to use WebdriverIO v6

**Comment by lacell75** [comment]
Yes but I'm currently using the v7 for the web app( and I need this version
for shadow support) and I will have to launch the tests with  multi remote
function (web app + Windows app) to test a WPF app

**Comment by licanhua** [comment]
It's best to fix it on Webdriverio side. `app` is a must have field to compatible with [appium](https://appium.io/docs/en/about-appium/getting-started/?lang=en) for native apps on Windows/Android/iOS.
Some native customers with appium may not be able to upgrade from v6 to v7 if webdriverio can't provide `app`.

I would suggest you add things like 'webdriverio:app": "Microsoft.WindowsAlarms_8wekyb3d8bbwe!App", then webdriver remove the webdriverio prefix and send the message out with `app`.
In this way, webdriverio supports any not `w3c` capabilities like  { webdriverio:appArguments: '...' } for v6 customers.

Another workaround is to let winappdriver to support things like: "ms:app": "..." to meet `W3C WebDriver capabilities`, but it will only fix problem on Windows, you still hit issue on iOS and Android.

@DHowett and @kat-y. FYI

**Comment by christian-bromann** [comment]
> `app` is a must have field to compatible with [appium](https://appium.io/docs/en/about-appium/getting-started/?lang=en) for native apps on Windows/Android/iOS.

I agree but Appium provides a valid W3C capability for this which is `appium:app`.

> I would suggest you add things like 'webdriverio:app": "Microsoft.WindowsAlarms_8wekyb3d8bbwe!App", then webdriver remove the webdriverio prefix and send the message out with `app`.

We have done this capability check intentionally because we can't guarantee that non WebDriver compatible driver can be supported at this point.

> Another workaround is to let winappdriver to support things like: "ms:app": "..." to meet `W3C WebDriver capabilities`, but it will only fix problem on Windows, you still hit issue on iOS and Android.

Again, Appium supports W3C WebDriver fully. If the underlying driver (e.g. WinAppDriver) doesn't it needs to be fixed there.

**Comment by licanhua** [comment]
@lacell75 Likely you have to add appium to your dependency or wait for WinAppDriver to fix the issue
