### ISSUE TITLE
Commands to remove in v8

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#7018]
The following commands should be removed in v8:

-`reset` (#7002)

**Comment by erwinheitzman** [comment]
Maybe also remove the browser.config in V8 as we now have browser.options?

**Comment by christian-bromann** [comment]
see #7005 😉

**Comment by erwinheitzman** [comment]
Yeah I had read it and that's why I mentioned it here so that it might be part of v8 instead of having a separate issue for it 😄 

I don't mind removing it before that but since this is here for a reason I thought this might be nice to include ;)
