### ISSUE TITLE
[wdio-devtools-service] Support Firefox Remote Protocol / CDP

### ISSUE THREAD

**Issue by dylanlive** [webdriverio/webdriverio#7023]
**I'm happy to put in a PR if you'd approve it. Need to do some testing on Firefox Local.**
----------------

**Is your feature request related to a problem? Please describe.**
When using the `devtools` service and setting Firefox as your browser, it returns an error that it's not supported. However, since Firefox 86, it has shipped a Remote Agent ([source](https://firefox-source-docs.mozilla.org/remote/Usage.html)) which works with a subset of CDP Commands.

**Describe the solution you'd like**
Allow calling `browser.cdp` commands when the browser is Firefox.

**Describe alternatives you've considered**
n/a

**Additional context**
I was able to get this working with Firefox and Selenium Grid 4 by using `patch-package` to do the following:
- Add firefox here: https://github.com/webdriverio/webdriverio/blob/509c16fdb986852fe4ba27d3159ef8b9838777c2/packages/wdio-devtools-service/src/utils.ts#L8
- Remove the `Console` domain, as it was throwing an error with Firefox: https://github.com/webdriverio/webdriverio/blob/509c16fdb986852fe4ba27d3159ef8b9838777c2/packages/wdio-devtools-service/src/index.ts#L248
```
ERROR @wdio/sync: Error: Protocol error (Console.enable): Console.enable RemoteAgentError@chrome://remote/content/cdp/Error.jsm:29:5
[0-0] UnknownMethodError@chrome://remote/content/cdp/Error.jsm:112:7
```

I then ran a test that called `browser.cdp("Runtime", "enable")` and was able to receive console logs and exception events.

Note: In capabilities, you also need to pass `"moz:debuggerAddress": true,`

**Comment by christian-bromann** [comment]
Hey @dylanlive,

thanks for reaching out. Your suggestions sound totally reasonable.

> * Add firefox here:

I know the Firefox team is working on adopting parts of CDP within the browser but afaik this has still not landed in the stable release channel yet and only available with the DeveloperEdition. We should add firefox to this list to be ready when this will be released in stable

> * Remove the `Console` domain, as it was throwing an error with Firefox:

Given that the `Console` domain is deprecated we can remove it from the list.

Let me know if you need any help making said changes. Happy to support.

**Comment by dylanlive** [comment]
@christian-bromann Thanks! Especially for the tip on the `Console` domain - I wasn't sure if removing that entirely would be bad (was considering adding a conditional).

>but afaik this has still not landed in the stable release channel yet

I tested with Firefox 88 on Stable - it worked. I think [this doc](https://firefox-source-docs.mozilla.org/remote/Usage.html) implies it has been in stable since v86.

**Comment by dylanlive** [comment]
Closed by https://github.com/webdriverio/webdriverio/pull/7027

Thanks!
