### ISSUE TITLE
Set Attribute

### ISSUE THREAD

**Issue by AltasHuseyin** [webdriverio/webdriverio#7030]
Hi, I remember I was able to use below code for setting/changing attribute in browser with Selenium/Java. I could not find anyways for WebdriverIO, TypeScript/JavaScript... Could you help me please?

WebDriver driver; // Assigned elsewhere
JavascriptExecutor js = (JavascriptExecutor) driver;
js.executeScript("document.getElementById('//id of element').setAttribute('attr', '10')");

**Comment by bereg2k** [comment]
@AltasHuseyin it's possible using `browser.execute()` method. 

```typescript
await browser.url("https://duckduckgo.com/");
const searchInput = await $("[name='q']");

// with 'external' arguments
await browser.execute("arguments[0].setAttribute('placeholder', 'Your search query goes here');", searchInput);
expect(searchInput).toHaveAttribute("placeholder", "Your search query goes here");

// no arguments
await browser.execute("document.getElementById('search_form_input_homepage').setAttribute('placeholder', 'Different placeholder');")
expect(searchInput).toHaveAttribute("placeholder", "Different placeholder");
```

**Comment by christian-bromann** [comment]
Great answer @bereg2k

**Comment by christian-bromann** [comment]
one way would also be:
```js
await browser.execute((elem) => elem.setAttribute('placeholder', 'Your search query goes here'), searchInput);
```

**Comment by AltasHuseyin** [comment]
I have implemented successfully. Thank you.
