### ISSUE TITLE
how to use browser.cdp function in standalone mode?

### ISSUE THREAD

**Issue by trizau** [webdriverio/webdriverio#7033]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [ ] Missing documentation
- [x] Other

**Description of the improvement / report**
A clear and concise description.

```javascript
const {remote} = require("webdriverio")
const browser = await remote({
    services: ['devtools'],
    capabilities: {
        browserName: 'chrome',
    }
});

console.log(browser.cdp); // is undefined
await browser.deleteSession();
```

**Comment by christian-bromann** [comment]
Use the [`getPuppeteer`](https://webdriver.io/docs/api/browser/getPuppeteer) method to access Puppeteer in standalone.
