### ISSUE TITLE
Set cucumberOpts through command line arguments

### ISSUE THREAD

**Issue by guillegette** [webdriverio/webdriverio#704]
Hi there,

Loving your work on this library. Would you consider the option to overwrite some of the cucumberOpts by command line arguments? In particular the -tags one. I really like the wdio test runner but sometimes I would like to execute certain tests filter by tags.

Im happy to create a PR for this change but want to see if you guys have an opinion about this.

Cheers!

**Comment by christian-bromann** [comment]
Thanks for your proposal! :+1: 
Implemented it and will get published with the next release

**Comment by guillegette** [comment]
Love your work!

**Comment by christian-bromann** [comment]
Fixed and published with `v3.2.0`
