### ISSUE TITLE
duplicate steps with the undefined status when generating a report @wdio/allure-reporter /// дублирование шагов со статусом undefined при генерации отчета @wdio/allure-reporter

### ISSUE THREAD

**Issue by platon023** [webdriverio/webdriverio#7042]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.7.4
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v14.17.1
 - **NPM version:** v6.14.13
 - **Browser name and version:** Chrome 91
 - **Platform name and version:** Linux
 - **Additional wdio packages used:** @wdio/cucumber-framework, @wdio/spec-reporter, @wdio/allure-reporter

Parameters - wdio.conf.js 
```
framework: 'cucumber',
    reporters: ['spec', ['allure', {outputDir: 'allure-results'}]],
    // If you are using Cucumber you need to specify the location of your step definitions.
    cucumberOpts: {
        // <string[]> (file/dir) require files before executing features
        require: ['./steps/defenitions/actions.js'],
        // <boolean> show full backtrace for errors
        backtrace: false,
        // <string[]> ("extension:module") require files with the given EXTENSION after requiring MODULE (repeatable)
        requireModule: [],
        // <boolean> invoke formatters without executing steps
        dryRun: false,
        // <boolean> abort the run on first failure
        failFast: false,
        // <string[]> (type[:path]) specify the output format, optionally supply PATH to redirect formatter output (repeatable)
        format: ['pretty'],
        // <boolean> hide step definition snippets for pending steps
        snippets: true,
        // <boolean> hide source uris
        source: true,
        // <string[]> (name) specify the profile to use
        profile: [],
        // <boolean> fail if there are any undefined or pending steps
        strict: false,
        // <string> (expression) only execute the features or scenarios with tags matching the expression
        tagExpression: '',
        // <number> timeout for step definitions
        timeout: 60000,
        // <boolean> Enable this config to treat undefined definitions as warnings.
        ignoreUndefinedDefinitions: false
    },
```

File Content ~./steps/defenitions/actions.js
```
const { Given, When, Then } = require('@cucumber/cucumber');
const load = require('eaist-ui-testing');
const escapeString = load('support/util/escapeString');
const login = load('controllers/actions/login/standard');
const button = load('controllers/actions/click/button');

Given(/^Log in to the system$/, login);

When(/^Click on (?:button|link)(?: "((?:\\\"|[^"])*)")?(.*)$/,
    (name, root) => button({
        name: escapeString(render(name)),
        root: parse(root)
    }));
```

After running the test, xml is generated with duplicates of the steps after broken, https://pastebin.com/J9x733kq == created xml file

**Comment by christian-bromann** [comment]
@platon023 can you please provide an english translation? Not many contributor of WebdriverIO speak Russian.

**Comment by BorisOsipov** [comment]
Culprit is https://github.com/webdriverio/webdriverio/pull/6453

For `onTestSkip` reporter event cucumber adapter pruduces title without `Given\When\Then`keyword
and allure relies on test title here https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-allure-reporter/src/index.ts#L222

**Comment by BorisOsipov** [comment]
This patch fixes the issue, maybe it will be usefull for someone how will pick up the issue. 
```
Index: packages/wdio-cucumber-framework/src/utils.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/packages/wdio-cucumber-framework/src/utils.ts b/packages/wdio-cucumber-framework/src/utils.ts
--- a/packages/wdio-cucumber-framework/src/utils.ts	(revision 304f9e4d7ead190b32b7ea88d2f923d89439b2c5)
+++ b/packages/wdio-cucumber-framework/src/utils.ts	(revision 71feb165e739988d5943826b7bf05ed7c7b3ae8b)
@@ -109,7 +109,7 @@
         file?: string
     }
 ) {
-    return {
+    return Object.assign(params, {
         uid: step.id,
         // @ts-ignore
         title: getTestStepTitle(step.keyword, step.text, params.type),
@@ -118,9 +118,8 @@
         file: uri,
         tags: scenario.tags,
         featureName: feature.name,
-        scenarioName: scenario.name,
-        ...params
-    }
+        scenarioName: scenario.name }
+    )
 }
 
 /**
```

**Comment by christian-bromann** [comment]
@platon023 would you like to pick this up and provide a PR?

**Comment by praveendvd** [comment]
> **Environment (please complete the following information):**
>  - **WebdriverIO version:** 7.7.4
>  - **Mode:** WDIO Testrunner
>  - **If WDIO Testrunner, running sync/async:** sync
>  - **Node.js version:** v14.17.1
>  - **NPM version:** v6.14.13
>  - **Browser name and version:** Chrome 91
>  - **Platform name and version:** Linux
>  - **Additional wdio packages used:** @wdio/cucumber-framework, @wdio/spec-reporter, @wdio/allure-reporter
> 
> 
> Parameters - wdio.conf.js 
> ```
> framework: 'cucumber',
>     reporters: ['spec', ['allure', {outputDir: 'allure-results'}]],
>     // If you are using Cucumber you need to specify the location of your step definitions.
>     cucumberOpts: {
>         // <string[]> (file/dir) require files before executing features
>         require: ['./steps/defenitions/actions.js'],
>         // <boolean> show full backtrace for errors
>         backtrace: false,
>         // <string[]> ("extension:module") require files with the given EXTENSION after requiring MODULE (repeatable)
>         requireModule: [],
>         // <boolean> invoke formatters without executing steps
>         dryRun: false,
>         // <boolean> abort the run on first failure
>         failFast: false,
>         // <string[]> (type[:path]) specify the output format, optionally supply PATH to redirect formatter output (repeatable)
>         format: ['pretty'],
>         // <boolean> hide step definition snippets for pending steps
>         snippets: true,
>         // <boolean> hide source uris
>         source: true,
>         // <string[]> (name) specify the profile to use
>         profile: [],
>         // <boolean> fail if there are any undefined or pending steps
>         strict: false,
>         // <string> (expression) only execute the features or scenarios with tags matching the expression
>         tagExpression: '',
>         // <number> timeout for step definitions
>         timeout: 60000,
>         // <boolean> Enable this config to treat undefined definitions as warnings.
>         ignoreUndefinedDefinitions: false
>     },
> ```
> 
> 
> File Content ~./steps/defenitions/actions.js
> ```
> const { Given, When, Then } = require('@cucumber/cucumber');
> const load = require('eaist-ui-testing');
> const escapeString = load('support/util/escapeString');
> const login = load('controllers/actions/login/standard');
> const button = load('controllers/actions/click/button');
> 
> Given(/^Log in to the system$/, login);
> 
> When(/^Click on (?:button|link)(?: "((?:\\\"|[^"])*)")?(.*)$/,
>     (name, root) => button({
>         name: escapeString(render(name)),
>         root: parse(root)
>     }));
> ```
> 
> After running the test, xml is generated with duplicates of the steps after broken, https://pastebin.com/J9x733kq == created xml file
> 

Did you try adding the option 

useCucumberStepReporter: true ?

**Comment by platon023** [comment]
> > **Environment (please complete the following information):**
> > 
> > * **WebdriverIO version:** 7.7.4
> > * **Mode:** WDIO Testrunner
> > * **If WDIO Testrunner, running sync/async:** sync
> > * **Node.js version:** v14.17.1
> > * **NPM version:** v6.14.13
> > * **Browser name and version:** Chrome 91
> > * **Platform name and version:** Linux
> > * **Additional wdio packages used:** @wdio/cucumber-framework, @wdio/spec-reporter, @wdio/allure-reporter
> > 
> > Parameters - wdio.conf.js
> > ```
> > framework: 'cucumber',
> >     reporters: ['spec', ['allure', {outputDir: 'allure-results'}]],
> >     // If you are using Cucumber you need to specify the location of your step definitions.
> >     cucumberOpts: {
> >         // <string[]> (file/dir) require files before executing features
> >         require: ['./steps/defenitions/actions.js'],
> >         // <boolean> show full backtrace for errors
> >         backtrace: false,
> >         // <string[]> ("extension:module") require files with the given EXTENSION after requiring MODULE (repeatable)
> >         requireModule: [],
> >         // <boolean> invoke formatters without executing steps
> >         dryRun: false,
> >         // <boolean> abort the run on first failure
> >         failFast: false,
> >         // <string[]> (type[:path]) specify the output format, optionally supply PATH to redirect formatter output (repeatable)
> >         format: ['pretty'],
> >         // <boolean> hide step definition snippets for pending steps
> >         snippets: true,
> >         // <boolean> hide source uris
> >         source: true,
> >         // <string[]> (name) specify the profile to use
> >         profile: [],
> >         // <boolean> fail if there are any undefined or pending steps
> >         strict: false,
> >         // <string> (expression) only execute the features or scenarios with tags matching the expression
> >         tagExpression: '',
> >         // <number> timeout for step definitions
> >         timeout: 60000,
> >         // <boolean> Enable this config to treat undefined definitions as warnings.
> >         ignoreUndefinedDefinitions: false
> >     },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File Content ~./steps/defenitions/actions.js
> > ```
> > const { Given, When, Then } = require('@cucumber/cucumber');
> > const load = require('eaist-ui-testing');
> > const escapeString = load('support/util/escapeString');
> > const login = load('controllers/actions/login/standard');
> > const button = load('controllers/actions/click/button');
> > 
> > Given(/^Log in to the system$/, login);
> > 
> > When(/^Click on (?:button|link)(?: "((?:\\\"|[^"])*)")?(.*)$/,
> >     (name, root) => button({
> >         name: escapeString(render(name)),
> >         root: parse(root)
> >     }));
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After running the test, xml is generated with duplicates of the steps after broken, https://pastebin.com/J9x733kq == created xml file
> 
> Did you try adding the option
> 
> useCucumberStepReporter: true ?

Thanks. Yes, I tried this option, but the view of the report display does not meet the customer's requirements, the view with the useCucumberStepReporter: false option takes priority.

**Comment by christian-bromann** [comment]
@praveendvd @platon023 would it help to make a patch suggested by @BorisOsipov ?

**Comment by praveendvd** [comment]
@christian-bromann  sure Chris I can have a look this week if it's good with @platon023  

@platon023 feel free to contribute with a patch else I could take a look :)

**Comment by platon023** [comment]
@praveendvd I would be happy to help but I'm not strong in the project's back code

**Comment by staizen-alexm** [comment]
hey folks, decided to pick this one up.

raised #7209 for review.

@platon023 side note - not sure if there's a specific reason you're not using it but the `useCucumberStepReporter` helps when using allure reporter with cucumber.

e.g. 
```js
  // wdio.conf.js
  reporters: [
    ["allure", { outputDir: "allure-results", useCucumberStepReporter: true }],
  ],
```

**Comment by christian-bromann** [comment]
Thanks @staizen-alexm , let's continue discussion in #7209
