### ISSUE TITLE
OnSuiteEnd Hook fires for every spec file in suite

### ISSUE THREAD

**Issue by joewdriver** [webdriverio/webdriverio#7044]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version: 6.4.5
 - **Mode:**  WDIO Testrunner
 - **If WDIO Testrunner: running sync
 - **Node.js version:** 14.9
 - **NPM version:** 6.14
 - **Browser name and version:** chrome 90
 - **Platform name and version:** mac catalina

**Config of WebdriverIO**
```reporters: [TRReporter,'spec'],

    suites: {
        auto: [
            './src/test/ui/foo/specs/*.ts',
        ],
        otherFeature: [
            // ...
        ]
    },
 

**Describe the bug**
I have implemented a custom reporter.  The OnSuiteEnd hook I have inherited from the WDIOReporter is firing at the end of every spec file, instead of at the end of every suite defined in the config

**To Reproduce**
define multiple spec files in a suite, implement a custom reporter with a hook that logs something in the onSuiteEnd, run the suite using the --suite xyz argument.

**Expected behavior**
this hook should run exactly one at the end of the suite

**Additional context**
Data stored in the reporter class also appears to be flushed between spec files.

**Comment by christian-bromann** [comment]
@joewdriver reporters only life within the lifecycle of a test suite (spec file). There are some discussions around this in #3780. Let's continue there. Closing as this is not a defect.
