### ISSUE TITLE
Cannot Get waitUntil isDisplayed to Work

### ISSUE THREAD

**Issue by awhisler** [webdriverio/webdriverio#7046]
**Environment:**
 - **WebdriverIO version:** 7.7.3
 - **Mode:** mocha
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 16.2.0
 - **NPM version:** 7.13.0
 - **Browser name and version:** Chrome 91
 - **Platform name and version:** MacOS
 - **Additional wdio packages used (if applicable):** "@wdio/cli": "^7.7.3", "@wdio/local-runner": "^7.7.3", "@wdio/mocha-framework": "^7.7.3", "@wdio/spec-reporter": "^7.7.3", "wdio-chromedriver-service": "^7.1.0"

I have a function that basically is supposed to wait until a selector is present (identifying that the rows are populated) and then count the rows

```
async getCaseList() {
        let caseList;
        browser.waitUntil(async () => 
            (await $$('.list-content-area .row span'))[0].isDisplayed(), 8000)
        caseList = await browser.findElements('css selector', '.list-content-area .row');
        return caseList.length
    }

```

I have tried multiple variations of the code above and everything returns 0 unless I put a `pause` in there before the `findElements`. Please help!

**Comment by christian-bromann** [comment]
You need to use `await` for the `waitUntil` command as well:

```js
    async getCaseList() {
        let caseList;
        await browser.waitUntil(async () => 
            (await $$('.list-content-area .row span'))[0].isDisplayed(), 8000)
        caseList = await browser.$('.list-content-area .row');
        return caseList.length
    }
```
