### ISSUE TITLE
Not able to use waituntil method  and cant click on the elements in ASYNC mode 

### ISSUE THREAD

**Issue by samplehub** [webdriverio/webdriverio#7048]
**Environment **
 - **WebdriverIO version:** [e.g. ^7.7.3]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [async]
 - **Node.js version:** [v14.17.0]
 - **NPM version:** [7.15.0]
 - **Browser name and version:** [e.g. Chrome 91]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [ "@wdio/allure-reporter": "7.7.3",
    "@wdio/cucumber-framework": "^7.7.3", @wdio/selenium-standalone service]

**Config of WebdriverIO**
Project is WDIO + Cucumber + Typescript + Async mode

**Describe the bug**
I am not able to get the array of multiple elements and do any clicks or any functions after that 

This is also related to https://github.com/webdriverio/webdriverio/issues/7046

Also checked these docs https://webdriver.io/docs/api/browser/waitUntil/
https://webdriver.io/docs/autowait

**To Reproduce**
```
async addABestSeller() : Promise<void>
{
  await browser.url("https://www.amazon.co.uk/best-sellers-books-Amazon/zgbs/books/ref=zg_bs_nav_0"); 
  await (await browser.$('#a-autoid-0')).click(); 
  await browser.waitUntil(async () =>   
   (await $$('a-section a-spacing-small')).length > 1, {timeout:8000})
  
   const bookList = await browser.$$('a-section a-spacing-small');
   console.log(bookList.length);
    await bookList[0].click();
}

```

**Expected behavior**
The above code is to navigate to Amazon Best sellers books site . 
https://www.amazon.co.uk/best-sellers-books-Amazon/zgbs/books/ref=zg_bs_nav_0
Get all the books in an array (Expected Length should be 50) 
![image](https://user-images.githubusercontent.com/18566869/123095254-c93c9000-d425-11eb-8540-e4c0c8c21ac5.png)

click on first element or any 
add to basket after that . 

**Log**
Ran into multiple issues . Couldnt get it to working. 
Error: waitUntil condition timed out after 8000ms

**Comment by samplehub** [comment]
@christian-bromann  , Please help me with the above issue. Thanks in advance.

**Comment by christian-bromann** [comment]
@samplehub your selectors where incorrect

```patch
- a-section a-spacing-small
+ .a-section.a-spacing-small
```

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
