### ISSUE TITLE
Property 'on' does not exist on type 'BrowserObject'

### ISSUE THREAD

**Issue by alexStrusberg** [webdriverio/webdriverio#7049]
Hello,

I am trying to work with the chrome dev tools protocol e.g. 

           browser.cdp('Network', 'enable');
            browser.on('Network.responseReceived', async (params) => {
                if (params.response.url.includes("accounts.register")) {
                    const res = await browser.cdp('Network','getResponseBody', {
                        requestId: params.requestId
                    });
                    console.log(`Loaded ${params.response.url}`);
                    console.log(`${JSON.parse(res.body).callId}`);
                }
            });

Yet I am getting this compilation error: error 

error TS2339: Property 'on' does not exist on type 'BrowserObject'
at createTSError (C:\dev\sdk\e2e\node_modules\ts-node\src\index.ts:500:12)
    at reportTSError (C:\dev\sdk\e2e\node_modules\ts-node\src\index.ts:504:19)
    at getOutput (C:\dev\sdk\e2e\node_modules\ts-node\src\index.ts:739:36)
    at Object.compile (C:\dev\sdk\e2e\node_modules\ts-node\src\index.ts:955:32)
    at Module.m._compile (C:\dev\sdk\e2e\node_modules\ts-node\src\index.ts:1043:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (C:\dev\sdk\e2e\node_modules\ts-node\src\index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)

I have the following tsconfig file 

{
  "compilerOptions": {
      "target": "ES2018",
      "baseUrl": ".",
      "paths": {
          "*": [ "./*" ]
      },
    "types": ["node",
      "@wdio/sync",
      "@wdio/mocha-framework",
      "@wdio/devtools-service",
      "./types/wdio"
    ]
  },
  "include": [
      "./.eslintrc.js",
      "./src/**/*.ts",
      "./config/**/*.ts",
      "./test/**/*.ts"
  ],
  "exclude": [
    "./node_modules"
  ]
}

And this package.json 

{
  "name": "wdio-mocha-typescript",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "npx wdio config/chromedriver.conf.js",
    "test:devtools": "npx wdio config/devtools.conf.js",
    "test:sauce": "npx wdio config/sauce.conf.js",
    "eslint": "npx eslint ."
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/pako88/wdio-mocha-typescript.git"
  },
  "keywords": [],
  "author": "Pascal Koenig",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/pako88/wdio-mocha-typescript/issues"
  },
  "homepage": "https://github.com/pako88/wdio-mocha-typescript#readme",
  "devDependencies": {
    "@types/mocha": "^8.0.3",
    "@types/node": "^14.14.6",
    "@typescript-eslint/eslint-plugin": "^4.6.1",
    "@typescript-eslint/parser": "^4.6.1",
    "@wdio/cli": "^6.7.2",
    "@wdio/devtools-service": "^6.6.6",
    "@wdio/local-runner": "^6.7.2",
    "@wdio/mocha-framework": "^6.7.0",
    "@wdio/sauce-service": "^6.7.2",
    "@wdio/spec-reporter": "^6.7.0",
    "@wdio/sync": "^6.7.2",
    "chromedriver": "^90.0.0",
    "eslint": "^7.13.0",
    "express": "^4.17.1",
    "sync-request": "^6.1.0",
    "html-dnd": "^1.2.1",
    "ts-node": "^9.0.0",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^4.0.5",
    "wdio-chromedriver-service": "^6.0.4",
    "get-random-values": "^1.2.2"
  }
}

What could be the issue?
Please please advise :-)

Thank you
Alex S

**Comment by christian-bromann** [comment]
Thank you for filing the issue. We recommend to upgrade to v7 where we improved TypeScript support and this error doesn't appear. We also accept PRs for [v6](https://github.com/webdriverio/webdriverio/tree/v6).
