### ISSUE TITLE
Webdriver fails in IE9 on quirksmode (old doctype) pages; its own JavaScript errors

### ISSUE THREAD

**Issue by stuartlangridge** [webdriverio/webdriverio#705]
Instructions to replicate:
1. Start Selenium
2. Use webdriver to load a page with a legacy doctype (e.g., `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">`) in Internet Explorer 9 (because IE9 will load that page in quirks mode, and various "newer" ES5 JS features such as `Array.forEach` do not exist)
3. See an error

Code of the used HTML page (http://www.brothercake.com/Ref/ie9-legacy.html):

    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
    <html>
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title></title>
    <script>
    </script>
    </head>
    <body>
    <p>
    <script>
    if(document.documentElement.firstElementChild) {
        document.write("Supports DOM3 (Edge Mode)");
    } else {
        document.write("No DOM3 (Legacy Mode)");
    }
    </script>
    </p>
    </body>
    </html>

The error is as follows. Note that I'm using BrowserStack here to test IE9, but this is not a browserstack problem; it exhibits when doing local testing in IE9 too. You will see that I don't _do_ anything with the page; I just open it, wait for body, and get the failure.

    node -e "var webdriverio=require('webdriverio');webdriverio.remote({desiredCapabilities:{browserName:'internet explorer',version:9},host:'hub.browserstack.com',port:80,user:'BROWSERSTACKUSER',key:'BROWSERSTACKKEY'}).init().url('http://www.brothercake.com/Ref/ie9-legacy.html').waitForVisible('body').end();"

    .../node_modules/webdriverio/lib/utils/PromiseHandler.js:154
                throw error;
                      ^
    RuntimeError: RuntimeError
     (UnknownError:13) An unknown server-side error occurred while processing the command.
     Problem: JavaScript error in async script. (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 24 milliseconds
    Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
    System info: host: '185-44-130-106', ip: '185.44.130.106', os.name: 'windows', os.arch: 'x86', os.version: '6.0', java.version: '1.8.0_51'
    Driver info: org.openqa.selenium.ie.InternetExplorerDriver
    Capabilities [{browserAttachTimeout=0, enablePersistentHover=true, ie.forceCreateProcessApi=false, ie.usePerProcessProxy=false, ignoreZoomSetting=false, handlesAlerts=true, version=9, platform=WINDOWS, nativeEvents=true, ie.ensureCleanSession=true, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:10477/, takesScreenshot=true, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=dismiss}]
    Session ID: 10c99b0b-3767-4238-9e11-f5b8a0d672b0

     Callstack:
     -> executeAsync("return (function (fn, sArr, args) {  var cb = arguments[arguments.length - 1],  i = 0, sArgs = [],  use, value, xp, cs, tn,  res, j, arg;  while ((use = sArr[i++]) && (value = sArr[i++])) {  arg = [];  xp = cs = tn = [Function];  switch (use) {  case \"partial link text\": xp = '//a[contains(text(),\"'+value+'\")]'; break;  case \"link text\": xp = '//a[text()=\"'+value+'\"]'; break;  case \"xpath\": xp = value; break;  case \"id\": cs = '[id=\"'+value+'\"]'; break;  case \"name\": cs = '[name=\"'+value+'\"]'; break;  case \"tag name\": tn = value; break;  case \"css selector\": cs = value; break;  default: throw new Error(\"Could not evaluate selector: Invalid strategy \" + use);  }   if (xp) {  res = document.evaluate(xp, document, null, 0, null);  while (value = res.iterateNext()) {  arg.push(value);  }  } else if (tn || cs) {  res = tn ? document.getElementsByTagName(tn) : document.querySelectorAll(cs);  j = 0;  while (value = res[j++]) {  arg.push(value);  }  }  sArgs.push(arg);  }   var parameter = args && sArgs.concat(args) || sArgs;  if(parameter.length === 0 || (parameter.length === 1 && parameter[0].length === 0)) {  if(typeof cb === 'function') {  return cb('NoSuchElement') && new Error('NoSuchElement');  }  return new Error('NoSuchElement');  }   parameter.push(arguments[arguments.length - 1]);   return fn.apply(window, parameter);\n})(function (elements, reverse) {  var cb = arguments[arguments.length - 1],  db = document.body,  dde = document.documentElement;   var interval = setInterval(function() {   for (var i = 0; i < elements.length; ++i) {  var elem = elements[i],  conditionFulfilled = reverse ? false : true;   while (elem.parentNode && elem.parentNode.getBoundingClientRect) {   var condition = false,  elemDimension = elem.getBoundingClientRect(),  elemComputedStyle = window.getComputedStyle(elem),  documentDimension = {  width: Math.max(db.scrollTop || 0, dde.scrollTop || 0, db.offsetwidth || 0, dde.offsetWidth || 0, db.clientWidth || 0, dde.clientWidth || 0),  height: Math.max(db.scrollheight || 0, dde.scrollHeight || 0, db.offsetHeight || 0, dde.offsetHeight || 0, db.clientHeight || 0, dde.clientHeight || 0)  };   if ((!reverse &&  elemComputedStyle.display !== 'none' &&  elemComputedStyle.visibility === 'visible' &&  parseFloat(elemComputedStyle.opacity, 10) > 0 &&  elemDimension.bottom >= 0 &&  elemDimension.top <= documentDimension.height &&  elemDimension.right >= 0 &&  elemDimension.left <= documentDimension.width) ||   (reverse &&  (elemComputedStyle.display === 'none' ||  elemComputedStyle.visibility === 'hidden' ||  parseFloat(elemComputedStyle.opacity, 10) === 0 ||  elemDimension.bottom < 0 ||  elemDimension.top > documentDimension.height ||  elemDimension.right < 0 ||  elemDimension.left > documentDimension.width))) {   condition = true;   }   if(reverse) {  /**   * if reverse is true (waitForInvisible) the condition is fulfilled   * when at least one element is hidden   */  conditionFulfilled = conditionFulfilled || condition;  } else {  /**   * if reverse is false (waitForVisible (default)) the condition is fulfilled   * when each element is visible   */  conditionFulfilled = conditionFulfilled && condition;  }  elem = elem.parentNode;   }   if(conditionFulfilled) {  window.clearInterval(interval);  return cb(true);  }   }   }, 100);\n},[\"css selector\",\"body\"],[false], arguments[arguments.length - 1]);")
     -> selectorExecuteAsync("body",[Function],false)
     -> waitForVisible("body")

**Comment by christian-bromann** [comment]
It seems that the way we used to do this is waitForVisible command throws an exception in old IE version. We have fixed that with v3.0.0. I recommend to either update to the current WebdriverIO version or use `waitFor("body")`
