### ISSUE TITLE
browser.react$ can not find memoized component

### ISSUE THREAD

**Issue by simoesrf** [webdriverio/webdriverio#7077]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.7.4
 - **Mode:** Standalone mode
 - **If WDIO Testrunner, running sync/async:** sync/async
 - **Node.js version:** 14.16.1
 - **NPM version:** 7.11.2
 - **Browser name and version:** Chrome 91
 - **Platform name and version:** Mac OS
 - **Additional wdio packages used (if applicable):** n/a

**Config of WebdriverIO**
Default configurations

**Describe the bug**
When I try to select a component memorized by the `React.memo` with `displayName` defined, the `browser.react$` or `browser.react$$` returns element not found or empty.

**To Reproduce**
Trying to target a component memorized.

**Code example**
_React app sample_
```TSX
const Title: React.FC = ({ children }) => <p>{children}</p>;

const TitleWrapper: React.FC = React.memo(() => <Title>Amazing <code>Title</code>.</Title>);
TitleWrapper.displayName = 'TitleWrapper';

const App: React.FC = () => <header><TitleWrapper /></header>
```
_Test sample_
```TS
describe("Test", () => {
  it("should work identify the text", async () => {
    await browser.url('http://localhost:3000/');
    const title = await browser.react$('TitleWrapper');

    await expect(await title.getText()).toBe("Amazing Title.");
  });
});
```

**Expected behavior**
It should identify the component by its `displayName`.

**Notes**
I don't know if I missed some documentation related to what I'm reporting or already existing open issues reporting this.

To make this work, is to define the `displayName` before memo:
```TSX
const TitleWrapper: React.FC = () => <Title>Amazing <code>Title</code>.</Title>;
TitleWrapper.displayName = 'TitleWrapper';
const MemoTitleWrapper = React.memo(TitleWrapper);

const App: React.FC = () => <header><MemoTitleWrapper /></header>
```

**Comment by simoesrf** [comment]
It seems that the `resq` guys release a new version that can help out with this issue: https://github.com/baruchvlz/resq/pull/79

**Comment by christian-bromann** [comment]
@simoesrf if you clear your package-lock you should receive that fix. Can you verify if this is still an issue?

**Comment by simoesrf** [comment]
Fixed, thank you!
