### ISSUE TITLE
Performance DevTools too slow

### ISSUE THREAD

**Issue by oscarm081297** [webdriverio/webdriverio#7083]
Hi folks!
I'm trying to get some performance metrics using webdriverIO and I am launching a simple test script, It's working  but.... is taking almost a minute using 3 commands, that IMO is taking too much time!

![Screen Shot 2021-06-30 at 13 35 58](https://user-images.githubusercontent.com/50888671/124021098-6197bf00-d9a8-11eb-88f7-31e99b6b805c.png)

Also, I'm working with the latest versions 7...

  "devDependencies": {
    "@wdio/allure-reporter": "^7.7.3",
    "@wdio/cli": "^7.7.4",
    "@wdio/devtools-service": "^7.7.4",
    "@wdio/local-runner": "^7.7.4",
    "@wdio/mocha-framework": "^7.7.4",
    "@wdio/spec-reporter": "^7.7.3",
    "chromedriver": "^91.0.1",
    "wdio-chromedriver-service": "^7.1.1"
  }

Does anyone have faced same issue ?

**Comment by christian-bromann** [comment]
I am sure we can improve the performance here a bit. Lighthouse now provides their own utility methods for url navigation etc. We might be able to copy from there to increase the speed and stay compliant with the report creation mechanism. Any contributions are welcome.

**Comment by christian-bromann** [comment]
Please try with the latest version of WebdriverIO as we have shipped several improvements. That said, checking the performance of a page always will take longer than a normal page load due to many reasons. I will close this issue. Happy to reopen if concrete issues can be laid out.
