### ISSUE TITLE
CSS selector misinterpreted as file extension by browser.$()

### ISSUE THREAD

**Issue by SeanHayes** [webdriverio/webdriverio#7087]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.7.4
 - **Mode:** Standalone
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 15
 - **Browser name and version:** Chrome
 - **Platform name and version:** Linux

**Config of WebdriverIO**
N/A
**Describe the bug**

**To Reproduce**
Trying to use `$('.Gif')` to select an element such as `<div class="Gif">...</div>` results in:
`ENOENT: no such file or directory, open '.Gif'`

The cause is the selector matches `IMAGEPATH_MOBILE_SELECTORS_ENDSWITH` in `utils/findStrategy.ts`, and webdriverio tries to open a file instead of querying the DOM.

**Expected behavior**
Query the element instead of trying to open a file.

**Comment by christian-bromann** [comment]
Contributions are appreciated.
