### ISSUE TITLE
driver is incredibly slow

### ISSUE THREAD

**Issue by AndrewRayCode** [webdriverio/webdriverio#71]
When I switched from this driver to `selenium-webdriver`, my entire test suite went from 30-40 minutes to run to 7 minutes to run. I have noticed this library will randomly hang between commands for long periods of time.

The official `selenium-webdriver` library also threw a lot of errors that were not noticed by webdriverjs. I think this library is eating a lot of errors that it should be throwing :(

**Comment by ngokevin** [comment]
I also have this issue where WebdriverIO is slow. Gonna try to use the selenium lib, but just chiming in.

I am using Webdriver remote with SauceLabs, and doing ```waitFor```s. When looking at the SauceLabs screencast, the page is fully loaded, but the ```waitFor``` hangs doing nothing for 3 minutes even though the elements are there.

**Comment by christian-bromann** [comment]
You don't need to use waitFor after opening an url. Selenium waits automatically until page is fully loaded. I haven't experienced a general slow experience at all using WebdriverIO.

**Comment by ngokevin** [comment]
It became perceivably faster once I called ```.screenshot()``` at the end? Maybe it was waiting for another command. My Sauce Labs tests went from 3min to 40sec about.

**Comment by christian-bromann** [comment]
mhm interesting ... do you have an example script that can reproduce that?

**Comment by ngokevin** [comment]
Sorry for the slow response. I compared two webdriver clients where one ends with a ```.waitForExist``` and one ends with a ```.waitForExist + .screenshot```. SauceLabs didn't consider ```.waitForExist``` a command and was waiting 90 seconds for more. Though I think that is expected so it's not actually an issue.
