### ISSUE TITLE
Retried test marked as failed in the test report

### ISSUE THREAD

**Issue by alminv** [webdriverio/webdriverio#7104]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.7.1
 - **Node.js version:** 15.6.0
 - **NPM version:** 7.4.0
 - **Browser name and version:** Chrome 91
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/spec-reporter 7.7.0

**Config of WebdriverIO**
N/A

**Describe the bug**
When test is retried if in the first run test fails and then passes in the next run, first test run is marked as failed (compared to skipped with WebdriverIO 6.x.x). As a consequence in the XML report there are failed tests so Azure DevOps will fail the test task if failTaskOnFailedTests is set to true.

**To Reproduce**
Use spec-reporter, this is what we have in the config file:
`reporters: [
    "spec",
    [
      "junit",
      {
        outputDir: "./test/results",
        outputFileFormat: function (options) {
               return 'test-result-${xxxx.cid}.xml';
        },
      },
    ],
  ]`

We use Mocha 8.4.0 so we set this.retries(1) in the describe block. 
Run a single test and make it fail first time and pass the second time. Open test results XML file, first test is marked as failed, second one as passed.

**Expected behavior**
First test is marked as skipped (like in WebdriverIO 6.x.x.)

**Log**
Test results XML file content:
`<testsuites>
  <testsuite name="Smoke tests" timestamp="2021-07-05T14:22:46" time="18.064" tests="2" failures="1" errors="1" skipped="0">
    <properties>
      <property name="specId" value="0"/>
      <property name="suiteName" value="Smoke tests"/>
      <property name="capabilities" value="chrome.91_0_4472_124.windows"/>
      <property name="file" value=".tests\smoke\smoketest.spec.js"/>
    </properties>
    <testcase classname="chrome.91_0_4472_124.windows.Smoke tests" name="should test something" time="10.198">
      <failure/>
      <error message="[2mexpect([22m[31mreceived[39m[2m).[22mtoBeGreaterThan[2m([22m[32mexpected[39m[2m)[22m&#xA;&#xA;Expected: > [32m0[39m&#xA;Received:   [31m0[39m"/>
      <system-out>xxxx</system-out>
      <system-err>xxxxx</system-err>
    </testcase>
    <testcase classname="chrome.91_0_4472_124.windows.Smoke tests" name="should test something" time="7.863">
      <system-out>xxxx</system-out>
    </testcase>
  </testsuite>
</testsuites>`

**Additional context**
We use Azure DevOps for CI/CD and since WebdriverIO update from 6.5.2 to 7.7.1 our builds are failing if any test is retried.

**Comment by christian-bromann** [comment]
I believe this is a bug in the `@wdio/junit-reporter`. Any contributions are appreciated.

**Comment by lthurr** [comment]
Hey, @christian-bromann 
I'm interested on doing my first contribution here, 

I could see `wdio-reporter` mark the test as failed when [**test:retry** is triggered](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-reporter/src/index.ts#L134) and therefore  `wdio-junit-reporter` sees it as as a failed test case.

so far, I see two options to fix this:
- on `wdio-reporter`, mark the test as **skipped** when test:retry is triggered 
- on `wdio-junit-reporter`, do the same

let me know your feedback and I can open the PR

**Comment by christian-bromann** [comment]
@lthurr thanks for taking a stab at it 🙏 

> so far, I see two options to fix this:

Ideally it would be great to have all reporters behave the same. I believe the spec reporter and maybe some others already handle this. Can you verify?

If other reporter do the same already and essentially do what you suggested (mark test as skipped when `test:retry` is triggered), we can just move all that code in the main `wdio-reporter`. If not, we can also just fix it directly in `wdio-junit-reporter`.

**Comment by christian-bromann** [comment]
Let's continue convo in #7157

**Comment by smtripathi99** [comment]
It seems it is again not working ?

"@axe-core/webdriverio": "4.8.1",
    "@babel/cli": "^7.19.3",
    "@babel/core": "^7.19.3",
    "@cucumber/cucumber": "^10.8.0",
    "@wdio/cli": "^8.40.2",
    "@wdio/cucumber-framework": "^8.21.0",
     "@wdio/spec-reporter": "^8.21.0",
    "axe-html-reporter": "^2.2.3",
    "wdio-cucumberjs-json-reporter": "^4.4.3",
