### ISSUE TITLE
@wdio/sauce-service TypeScript error for region configuration option

### ISSUE THREAD

**Issue by vitalyiegorov** [webdriverio/webdriverio#7106]
Original type:
```
import type { SauceLabsOptions } from 'saucelabs';
region?:
    | "us"
    | "eu"
    | "apac"
    | "us-west-1"
    | "us-east-1"
    | "eu-central-1"
    | "apac-southeast-1"
    | "staging";
```

differs from the `@wdio/type/Options.d.ts`:
```export declare type SauceRegions = 'us' | 'eu' | 'apac' | 'us-west-1' | 'us-east-1' | 'eu-central-1' | 'apac-southeast-1';```

Option `staging` is missing,

Maybe we could  use original type for this:

```
import type { SauceLabsOptions } from 'saucelabs';

export interface WebdriverIO extends Omit<WebDriver, 'capabilities'> {
...
    /**
     * If running on Sauce Labs, you can choose to run tests between different datacenters:
     * US or EU. To change your region to EU, add region: 'eu' to your config.
     */
    region?: SauceLabsOptions;
...
}
``` 

**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.7.4

**Comment by christian-bromann** [comment]
> Maybe we could use original type for this:

This would mean we need to add the `saucelabs` package as dependency which would be not ideal for folks not using Sauce Labs.

I will add the missing string to the type.
