### ISSUE TITLE
Webdriver methods returns element reference and not webdriverio elements

### ISSUE THREAD

**Issue by praveendvd** [webdriverio/webdriverio#7112]
**Environment (please complete the following information):**
 - **WebdriverIO version:**  ^7.7.4"
 - **Mode:** [Standalone mode or WDIO Testrunner] : Test runner
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async] : Async
 - **Node.js version:** [e.g. 8.11.2] : 16.3.0
 - **NPM version:** [e.g. 5.8.0] : 6.14.10
 - **Browser name and version:** [e.g. Chrome 68] : 91
 - **Platform name and version:** [e.g. Windows 10] : win10
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]:

```
 "dependencies": {
    "allure-commandline": "^2.13.8",
    "appium": "^1.21.0",
    "protractor-beautiful-reporter": "^1.3.6",
    "webdriverio": "^7.7.4"
  },
  "devDependencies": {
    "@wdio/allure-reporter": "^7.7.3",
    "@wdio/appium-service": "^7.7.3",
    "@wdio/cli": "^7.7.4",
    "@wdio/dot-reporter": "^7.7.3",
    "@wdio/jasmine-framework": "^7.7.3",
    "@wdio/junit-reporter": "^7.7.3",
    "@wdio/local-runner": "^7.7.4",
    "@wdio/mocha-framework": "^7.7.4",
    "@wdio/spec-reporter": "^7.7.3",
    "chromedriver": "^91.0.1",
    "eslint": "^7.30.0",
    "wdio-chromedriver-service": "^7.1.1",
    "wdio-mochawesome-reporter": "^4.0.0",
    "wdio-video-reporter": "^3.1.2"
  },

```

**Describe the bug**

All direct webdriver.js methods like findELement, getActiveElement etc returns element reference than webdriverio.element

**To Reproduce**

```

describe('My Login application', () => {
    it('should login with v1alid credentials', async () => {
        await browser.url('https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file')
        await browser.maximizeWindow()
        file = await browser.findElement("xpath",'//*[contains(text(),"This produces a similar-looking output to the previous example:")]')
        await file.scrollIntoView()
        frame = await $('#frame_Limiting_accepted_file_types')
        await browser.switchToFrame(frame)
         let a = await browser.getActiveElement()
         
         
    });
});

```
This code returns a string for the identifier file instead of actual element object

**Expected behavior**

it should return element object instead of string or document a way to get actual element from the element reference

**Comment by praveendvd** [comment]
Actual:

```

    findElement(using: string, value: string): ElementReference;
    /**
```

Expected:

```
findElement(using: string, value: string):  Promise<WebdriverIO.Element>;
```

**Comment by BorisOsipov** [comment]
Hi @praveendvd 

>All direct webdriver.js methods like findELement, getActiveElement 

yes it is as designed and as described in protocol docs
![image](https://user-images.githubusercontent.com/6514276/125034260-1319ad00-e099-11eb-90cf-22bde3ba9ce4.png)

>or document a way to get actual element from the element reference

You can find docs here https://webdriver.io/docs/api/element/$
>You can also pass in an object as selector where the object contains a property element-6066-11e4-a52e-4f735466cecf with the value of a reference to an element. The command will then transform the reference to an extended WebdriverIO element.

And example:

```
        await browser.url('https://google.com');
        const activeElement = await browser.getActiveElement()
        await (await $(activeElement)).getAttribute("class")
```

**Comment by praveendvd** [comment]
i think it needs to be documenteed in the findELement session too i guess, i create a pull request

**Comment by BorisOsipov** [comment]
@praveendvd I am not sure that is a right place. It is protocol commands docs and `$()` is wdio specific stuff.

**Comment by praveendvd** [comment]
> @praveendvd I am not sure that is a right place. It is protocol commands docs and `$()` is wdio specific stuff.

but what that protocol command returns is not usable unless we use it with $() , its not obvious from the current documentation but you are right too.

**Comment by praveendvd** [comment]
````
Returns: <object> element: A JSON representation of an element object 

<div class="admonition admonition-info alert alert--info"><div class="admonition-heading"><h5><span class="admonition-icon"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="16" viewBox="0 0 14 16"><path fill-rule="evenodd" d="M7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 0 1 1.3 8c0-3.14 2.56-5.7 5.7-5.7zM7 1C3.14 1 0 4.14 0 8s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm1 3H6v5h2V4zm0 6H6v2h2v-2z"></path></svg></span>info</h5></div><div class="admonition-content"><p>For more information on how to retrieve wdio Element from the return webdriver element reference, check out<a href="/docs/$">$</a> guide.</p></div></div>

````

**Comment by praveendvd** [comment]
add an info panel ?

**Comment by praveendvd** [comment]
@BorisOsipov 

![image](https://user-images.githubusercontent.com/45095911/125037646-515c9f80-e08c-11eb-8f7f-c4998d7b923e.png)

**Comment by BorisOsipov** [comment]
@praveendvd

Maybe :)

1) You have to add this text to ALL such commands for each protocol.
2) Also it is not static pages - docs are generated from protocol json representation [by scripts](https://github.com/webdriverio/webdriverio/blob/main/scripts/docs-generation/protocolDocs.js).

So I would recommend to create separate issue about this docs and recieve agreement from other mainteiners to change it - just to save you time if it will be rejected.

**Comment by praveendvd** [comment]
perfect i will raise a separate issue then and see what others think , because its really unclear from the documentation . I will raise the bug and will try to do patch also so that i will learn something new even if its rejected :D @BorisOsipov  Thank you for all the help

**Comment by BorisOsipov** [comment]
@praveendvd if you want smth challenging you can pick up https://github.com/webdriverio/webdriverio/discussions/6256
:D

**Comment by praveendvd** [comment]
> @praveendvd if you want smth challenging you can pick up #6256
> :D

may be i will stick with documentation :laughing: or else i will bug you more with review questions
