### ISSUE TITLE
Ending promise chain early

### ISSUE THREAD

**Issue by sean-hill** [webdriverio/webdriverio#712]
Hey there, is it possible to do something like this?

	client
		.url('http://url.com')
		.click('#something')
		.url()
		.then(function(url){

			if (url === 'http://some-other-url.com') {
				this.end()
			}

		})
		.click('#other')
		.end()
		
In other words, end the chain earlier depending on a condition. With the code above I get an error saying `org.openqa.selenium.remote.SessionNotFoundException: Session ID is null. Using WebDriver after calling quit()?`

Thanks!

**Comment by sean-hill** [comment]
I found a solution, not sure if it's accurate, but I can do this.

	if (url === 'http://some-other-url.com') {
	    return this
	    	.end()
	    	.then(function(){
		    	throw new Error('Stop the chain');
		    })
	}

**Comment by christian-bromann** [comment]
I am not sure if this issue requires any action as it can be handled by structuring the code. If you call end you need to make sure that no commands get executed anymore, your example could also be written like

```js
client
    .url('http://url.com')
    .click('#something')
    .url()
    .then(function(url){
        if (url !== 'http://some-other-url.com') {
            return this.click('#other');
        }
    })
    .end()
```

`end` should always be the last command.
