### ISSUE TITLE
Configurable retry count for retrying of single tests 

### ISSUE THREAD

**Issue by timzatko** [webdriverio/webdriverio#7125]
**Is your feature request related to a problem? Please describe.**
The [documentation](https://webdriver.io/docs/retry#rerun-single-tests-in-jasmine-or-mocha) describes how a single test can be retried. It can be set by setting the third/second parameter of it/beforeEach. However, it is not possible to set a default value for that and we would like to avoid setting it manually everywhere. 
Using `specFileRetries` is not an acceptable solution for us, since it retries the whole spec file and tests that previously passed.

**Describe the solution you'd like**
Allow setting an option (for example `testRetryCount`) from `jasmineNodeOpts` which would set the default value for retryCount (third parameter) in `it`.
I believe it could be done the same way as other suit functions such us _beforeAll_ are overridden - [link](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-jasmine-framework/src/index.ts#L168).

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by christian-bromann** [comment]
@timzatko Jasmine really doesn't provide great ways to retry tests. Mocha is much advanced and provides options such as [`retries`](https://webdriver.io/docs/frameworks#retries) that really only retry a specific test including the hook. If we would implement such option on WebdriverIO level, we would need to make it compliant to other frameworks as well. Is there anything that makes you want to keep using Jasmine? An easier solution might be just to switch to Mocha.

**Comment by timzatko** [comment]
Hi!

> If we would implement such option on WebdriverIO level, we would need to make it compliant to other frameworks as well. 

Mocha already has an option for that (see the [docs](https://webdriver.io/docs/retry/#rerun-suites-in-mocha)).

> Using Mocha you can also set a retry count for all specs using **mochaOpts.retries** in your wdio.conf.js.

Is it possible to do the same for _jasmine_? For example, by allowing **jasmineOpts.retries** in wdio.conf.js

> Is there anything that makes you want to keep using Jasmine? An easier solution might be just to switch to Mocha.

I don't know, the project is quite mature, we would need to research that.

**Comment by christian-bromann** [comment]
> Is it possible to do the same for _jasmine_? For example, by allowing **jasmineOpts.retries** in wdio.conf.js

No, Jasmine has no such feature which is why I recommend to switch to Mocha.

Note that WebdriverIO only retries specific `it` blocks and not their corresponding hooks. So the retry mechanism might not even work for you if you use and work with hooks. I am honestly a bit unsure if we want to extend WebdriverIO's retry mechanism functionality because of mentioned limitation. An [older discussion](https://github.com/jasmine/jasmine/issues/960) in the Jasmine project shows that there might be interest to add this to Jasmine.

**Comment by timzatko** [comment]
@christian-bromann Thanks, we will have to consider our options here and try switching to Mocha.
