### ISSUE TITLE
How to set multiple cookies

### ISSUE THREAD

**Issue by sean-hill** [webdriverio/webdriverio#713]
Suppose I have an array:

	var cookies = [
		{ name: 'one', value: 'test '}
		{ name: 'two', value: 'test '}
		{ name: 'three', value: 'test '}
		{ name: 'four', value: 'test '}
	];

What is the best way to set all these cookies with a loop? With v2 I could have done:

	client.addCommand('customSetCookies', function(callback){
		for(var i = 0; i < cookies.length; i++) {
			client.setCookie(cookies[i]);
		}
		return callback();
	});

	client
		.init()
		.url('http://www.google.com')
		.customSetCookies()
		.end()

However in v3, how do I accomplish this with the promise chain correctly. Thanks!

**Comment by sean-hill** [comment]
I came up with a solution. Just verifying this is an appropriate way to handle it.

	client.addCommand('loadCookies', function(cookies){
		
		var self = this;

		return cookies.reduce(function (promiseChain, currentCookie) {
			return self.setCookie(currentCookie)
		}, cookies[0]);

	});

	client
	    .init()
	    .loadCookies(cookies)
	    .url('http://www.google.com')
	    .end()

The `reduce` function combines all the promises into one long chain.

**Comment by christian-bromann** [comment]
@sean-hill yeah, you need to iterate through your object. Your example looks good!
