### ISSUE TITLE
Amend JUnit reporter for better test cases grouping

### ISSUE THREAD

**Issue by sgkiokas** [webdriverio/webdriverio#7132]
**Describe the solution you'd like**
While using the CalliopePro tool to upload out JUnit reports in order to take advantage of the `smart` and `merge_containers` [features](https://docs.calliope.pro/supported-formats/junit-xml/#defaults), I've noticed that this is not possible due to the way the `classname` is constructed in JUnit since it's not taking into consideration the nested `testsuite` name. 

For example, the output of JUnit is:

```
  <testsuite name="Home_Page_Main_Find_Out_More" timestamp="2021-07-12T16:46:26" time="126.141" tests="0" failures="0" errors="0" skipped="0"/>
  <testsuite name="MBIL_4957_MBIL_4961_Click_on_Find_Out_More_and_navigate_to_a_new_page" timestamp="2021-07-12T16:46:26" time="72.052" tests="3" failures="0" errors="0" skipped="0">
    <testcase classname="emulator-5554.android.9.tnl_apk.MBIL_4957_MBIL_4961_Click_on_Find_Out_More_and_navigate_to_a_new_page" name="should_acknowledge_the_on_boarding_message_displayed" time="15.249"/>
    <testcase classname="emulator-5554.android.9.tnl_apk.MBIL_4957_MBIL_4961_Click_on_Find_Out_More_and_navigate_to_a_new_page" name="should_display_an_Alert_message_with_Find_Out_More_Button" time="0.21"/>
    <testcase classname="emulator-5554.android.9.tnl_apk.MBIL_4957_MBIL_4961_Click_on_Find_Out_More_and_navigate_to_a_new_page" name="should_click_on_Find_Out_More_Button_and_validate_the_navigation" time="0.084"/>
  </testsuite>
```

In order to achieve the grouping and remove any duplicates should have been:

```
  <testsuite name="Home_Page_Main_Find_Out_More" timestamp="2021-07-12T16:46:26" time="126.141" tests="0" failures="0" errors="0" skipped="0"/>
  <testsuite name="MBIL_4957_MBIL_4961_Click_on_Find_Out_More_and_navigate_to_a_new_page" timestamp="2021-07-12T16:46:26" time="72.052" tests="3" failures="0" errors="0" skipped="0">
    <testcase classname="emulator-5554.android.9.tnl_apk.Home_Page.Main.Find_Out_More.MBIL_4957_MBIL_4961_Click_on_Find_Out_More_and_navigate_to_a_new_page" name="should_acknowledge_the_on_boarding_message_displayed" time="15.249"/>
    <testcase classname="emulator-5554.android.9.tnl_apk.Home_Page.Main.Find_Out_More.MBIL_4957_MBIL_4961_Click_on_Find_Out_More_and_navigate_to_a_new_page" name="should_display_an_Alert_message_with_Find_Out_More_Button" time="0.21"/>
    <testcase classname="emulator-5554.android.9.tnl_apk.Home_Page.Main.Find_Out_More.MBIL_4957_MBIL_4961_Click_on_Find_Out_More_and_navigate_to_a_new_page" name="should_click_on_Find_Out_More_Button_and_validate_the_navigation" time="0.084"/>
  </testsuite>
```

**Describe alternatives you've considered**
I was thinking of 2 main alternatives:

(a) Create a custom reporter that will act as a wrapper to the Jasmine JUnitXmlReporter which actually creates exactly the above by default.
(b) Create a post-processing script modifying the XML with the correct `classname` value.

**Comment by christian-bromann** [comment]
I believe this suggestion of amending the class name to consider nested testsuites makes sense, any contributions are appreciated.

**Comment by sgkiokas** [comment]
@christian-bromann is there any documentation on how to test my changes locally prior to raising a PR? Thanks in advance!

**Comment by lthurr** [comment]
We have available `suite.fullTitle` to use [here](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-junit-reporter/src/index.ts#L173) 

But it will produce something like:
```
<testcase classname="browser.Suite Inner suite test 1" name="test 1" time="..."/>
```
instead of
```
<testcase classname="browser.Suite.Inner_suite.test_1" name="test 1" time="..."/>
```

Is that okay?

**Comment by sgkiokas** [comment]
Hi @lthurr. I have based the above proposal to some manual amendment of the produced XML file in which the dots replacing the spaces where mandatory in order to achieve the grouping I mentioned. I can give it a go and let you know though.

**Comment by sjieg** [comment]
Hey @lthurr, on behalf of the Calliope Pro team, your work on this is much appreciated!

**Comment by sgkiokas** [comment]
We thank you as well on behalf of Camelot Lottery Solutions :)
