### ISSUE TITLE
Retry (whole) scenario on failure for handling flaky tests (Re-opened)

### ISSUE THREAD

**Issue by abhidp** [webdriverio/webdriverio#7137]
**Describe the bug**
Reopening the issue: https://github.com/webdriverio/webdriverio/issues/4628
Cannot retry complete `describe()` as per the docs: https://webdriver.io/docs/retry/

The above bug was closed with a resolution:- describe blocks can be retried using `this.retries(2)` inside a describe block. 

But according to the comment of one of Mocha's member, mocha does NOT support this at all: https://github.com/mochajs/mocha/issues/4094#issuecomment-557201979

Please clarify what is the right way to run complete `describe` upon failure.

**Comment by christian-bromann** [comment]
> Please clarify what is the right way to run complete `describe` upon failure.

Please use [retry on a spec file basis for this|(https://webdriver.io/docs/retry/#add-retries-on-a-per-specfile-basis).
