### ISSUE TITLE
The parameter --user-data-dir does not take effect

### ISSUE THREAD

**Issue by trizau** [webdriverio/webdriverio#7144]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.7.6
 - **Mode:** Standalone mode
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version: v15.14.0
 - **NPM version: 7.19.1
 - **Browser name and version: chrome 91
 - **Platform name and version: windows10 
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
```javascript
import {remote} from "webdriverio"
const browser = await remote({
    logLevel: "silent",
    capabilities: {
        browserName: 'chrome',
        "goog:chromeOptions": {
            args: [
                '--user-data-dir=' + path.join(__dirname, '/myBrowser'),
            ],
        },
        "wdio:devtoolsOptions": {
            ignoreDefaultArgs: ['--enable-automation'],
        }
    }
});
```

**Describe the bug**
```'--user-data-dir=' + path.join(__dirname, '/myBrowser'),``` Is invalid here

**To Reproduce**
Every time,  
But this is normal in mac

**Expected behavior**
The browser user's directory is under this directory I defined

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

I found a temporary solution:  
Insert at line **68** of file **/node_modules/devtools/build/launcher.js** : ```userDataDir: false```

**Comment by christian-bromann** [comment]
The dashes should be omitted, e.g.:
```js
import {remote} from "webdriverio"
const browser = await remote({
    logLevel: "silent",
    capabilities: {
        browserName: 'chrome',
        "goog:chromeOptions": {
            args: [
                'user-data-dir=' + path.join(__dirname, '/myBrowser'),
            ],
        },
        "wdio:devtoolsOptions": {
            ignoreDefaultArgs: ['--enable-automation'],
        }
    }
});
```

**Comment by trizau** [comment]
> The dashes should be omitted, e.g.:
> 
> ```js
> import {remote} from "webdriverio"
> const browser = await remote({
>     logLevel: "silent",
>     capabilities: {
>         browserName: 'chrome',
>         "goog:chromeOptions": {
>             args: [
>                 'user-data-dir=' + path.join(__dirname, '/myBrowser'),
>             ],
>         },
>         "wdio:devtoolsOptions": {
>             ignoreDefaultArgs: ['--enable-automation'],
>         }
>     }
> });
> ```

It didn't work for me, in the **chrome://version** page I see 
```
Google Chrome	91.0.4472.124 (Official Build) (64-bit) (cohort: Stable)
Revision	7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS	Windows Server OS Version 1809 (Build 17763.1518)
JavaScript	V8 9.1.269.36
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
Command Line	"C:\Program Files\Google\Chrome\Application\chrome.exe" --remote-debugging-port=49791 --user-data-dir="C:\Users\ADMINI~1\AppData\Local\Temp\2\lighthouse.61501964" --disable-popup-blocking --disable-extensions --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-first-run --no-default-browser-check --disable-hang-monitor --disable-prompt-on-repost --disable-client-side-phishing-detection --password-store=basic --use-mock-keychain --disable-component-extensions-with-background-pages --disable-breakpad --disable-dev-shm-usage --disable-ipc-flooding-protection --disable-renderer-backgrounding --force-fieldtrials=*BackgroundTracing/default/ --enable-features=NetworkService,NetworkServiceInProcess --disable-features=site-per-process,TranslateUI,BlinkGenPropertyTrees --window-position=0,0 --window-size=1200,900 --flag-switches-begin --flag-switches-end "user-data-dir=C:\Users\Administrator\Desktop\mark3\MyBrowser" about:blank
Executable Path	C:\Program Files\Google\Chrome\Application\chrome.exe
Profile Path	C:\Users\ADMINI~1\AppData\Local\Temp\2\lighthouse.61501964\Default

```

The parameter **--user-data-dir** is repeatedly defined by **/node_modules/chrome-launcher/dist/chrome-launcher.js**, according to line 80 of this file
```javascript
if (typeof this.opts.userDataDir ==='boolean') {
     if (!this.opts.userDataDir) {
         this.useDefaultProfile = true;
         this.userDataDir = undefined;
     }
     else {
         throw new utils_1.InvalidUserDataDirectoryError();
     }
}
else {
     this.useDefaultProfile = false;
     this.userDataDir = this.opts.userDataDir;
}
```
And line 103
```javascript
if (!this.useDefaultProfile) {
     // Place Chrome profile in a custom location we'll rm -rf later
     // If in WSL, we need to use the Windows format
     flags.push(`--user-data-dir=${isWsl? utils_1.toWinDirFormat(this.userDataDir): this.userDataDir}`);
}
```
I have to pass in the **userDataDir** parameter for **/node_modules/devtools/build/launcher.js:65**
(The definition will be repeated on the mac, but this is fine on the mac)

**Comment by christian-bromann** [comment]
Are you running it via Chromedriver or through Puppeteer?

**Comment by trizau** [comment]
> Are you running it via Chromedriver or through Puppeteer?

This is the code used to start the browser
```javascript
import {remote} from "webdriverio"
const browser = await remote({
    logLevel: "silent",
    capabilities: {
        browserName: 'chrome',
        "goog:chromeOptions": {
            args: [
                'user-data-dir=' + path.join(__dirname, '/myBrowser'),
            ],
        },
        "wdio:devtoolsOptions": {
            ignoreDefaultArgs: ['--enable-automation'],
        }
    }
});
```

**Comment by christian-bromann** [comment]
Created a new issue, see above.
