### ISSUE TITLE
Apparent AMP element can't be fetched and throws stale element

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#7147]
The following script:

```js
describe("amp validation", () => {
    it("amp valtation testing", () => {
        browser.url("https://validator.ampproject.org/")
        browser.maximizeWindow()
        $("#input").setValue("https://google.co.in")
    })
})
```

Always fails because fetching `#input` always results in `stale element error` even with retries. I might be related to AMP.

**Comment by praveendvd** [comment]
> The following script:
> 
> ```js
> describe("amp validation", () => {
>     it("amp valtation testing", () => {
>         browser.url("https://validator.ampproject.org/")
>         browser.maximizeWindow()
>         $("#input").setValue("https://google.co.in")
>     })
> })
> ```
> 
> Always fails because fetching `#input` always results in `stale element error` even with retries. I might be related to AMP.

![image](https://user-images.githubusercontent.com/45095911/126046487-8b60fa2c-bead-4d5d-a424-91e09daaabae.png)

yes chromedriver is not able to find even the html element , it looks like website issue but would be great to know why

**Comment by praveendvd** [comment]
@christian-bromann  
![image](https://user-images.githubusercontent.com/45095911/126047048-bdfa70ad-d118-4d01-9194-d2930e22b92c.png)

works well with xpath !

**Comment by christian-bromann** [comment]
Very weird, it seems to only happen to that specific page. Other AMP pages are fine.

**Comment by praveendvd** [comment]
> Very weird, it seems to only happen to that specific page. Other AMP pages are fine. Using the `devtools` protocol, it can not even find any element. So I assume it is definitely AMP related but not sure why this page is special.

i tried disabling webdriver , enable automation , setting useragent etc but no use the website still behaves the same .  But its really interesting why css fails and xpath works

**Comment by christian-bromann** [comment]
Let's close this as it doesn't seem people are facing this issue or are concerned.
