### ISSUE TITLE
Access Global Variable

### ISSUE THREAD

**Issue by saulshanabrook** [webdriverio/webdriverio#715]
Is it possible to access global variables from client? For example, if the client sets `window.config` to something, is it possible to retrieve that value?

**Comment by christian-bromann** [comment]
yeah, just inject a snippet and return your desired value, e.g.

```js
client.execute(function() {
    return window.config;
}).then(function(config) {
    console.log(config.property);
});
```

**Comment by saulshanabrook** [comment]
@christian-bromann Thank you!

**Comment by saulshanabrook** [comment]
I think actually it would be `console.log(config.value.property)`.

`config` looks like:

```
{ state: 'success',
  sessionId: '2ca2bd7c-ead3-49cf-8b8a-77fb7f27885d',
  hCode: 339999902,
  value: {},
  class: 'org.openqa.selenium.remote.Response',
  status: 0 }
```
