### ISSUE TITLE
allure-reporter output with nested describes is wrong

### ISSUE THREAD

**Issue by ccwilkins** [webdriverio/webdriverio#7168]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.2.3
 - **Mode:** Standalone mode
 - **Node.js version:** 12.21.0
 - **NPM version:** 6.14.11
 - **Browser name and version:** Chrome 91.0.4472.164
 - **Platform name and version:** Mac OS Catalina
 -  @wdio/allure-reporter: 7.7.7
 - @wdio/mocha-framework: 7.2.1
 - mocha: 8.3.2
 - chai: 4.2.0

**Config of WebdriverIO**
```
exports.config = buildDefaultConfig({
    maxInstances: 1,
    specs: ["./wdio/tests/**/*.spec.ts?(x)"],
    services: ['devtools'],
    framework: "mocha",
    waitforTimeout: 10000,
    mochaOpts: {
      ui: "bdd",
      timeout: 300000,
      require: ["tsconfig-paths/register"]
    },
    onComplete: function() {
      const generation = allure(['generate', 'allure-results', '--clean'])
      return new Promise((resolve, reject) => {
          const generationTimeout = setTimeout(
              () => reject(new Error('Could not generate Allure report')),
              30000)
  
          generation.on('exit', function(exitCode) {
              clearTimeout(generationTimeout)
  
              if (exitCode !== 0) {
                  return reject(new Error('Could not generate Allure report'))
              }
  
              resolve()
          })
      })
    },
    reporters: [
      "spec",
      ['allure', {
        disableWebdriverStepsReporting: false,
        disableWebdriverScreenshotsReporting: true,
        disableMochaHooks: true
      }]
  ],
    nyc: {
      reporters: ["html", "text"]
    },
    pluginInfo: {
      ...local && { overrideUrl: process.env.OVERRIDE_URL || localOverride },
      pluginPath: "/some-path/"
    },
    ...overwriteLifecycle
  });
```

**Describe the bug**
When the allure report is generated for a spec file (single suite) that has nested describes. Each nested describe becomes its own suite. This results in the actually allure report that doesn't have all the test cases under the appropriate suite (per spec file).

**To Reproduce**

Setup a mocha WDIO test with nested describe blocks and run with allure reports.

**Expected behavior**
Expect the allure report to be under a single suite for all the describes/its.

**Additional context**
Trying to generate allure reports. My specs use nested describe blocks. When I introduced the allure reporter what is generated is wrong. Each nested describe becomes its own suite which is wrong.

**Comment by BorisOsipov** [comment]
Hi @ccwilkins 

It is not a bug. Reporter was initially designed to split nested steps. It made reporter implementation simpler.
I am not sure our old allure-commons supports nested suites as well.

Any contributions are welcome.

**Comment by ccwilkins** [comment]
Seems odd that nested steps would be split. Especially given the nature of how tests can be written with mocha and jasmine. The hierarchy tells the story being told in the test (suite). By splitting it up that fundamentally breaks down and also makes it very convoluted to review the test results.

**Comment by BorisOsipov** [comment]
And when I say it is trade off - this solution was implemented 5+ years ago and maybe now it is good time to review this decision and change it. Any contributions are welcome.

**Comment by BorisOsipov** [comment]
Hi! We have rewritten the reporter to the new allure-js version. Please try version 8.5.0 of wdio-allure-reporter and provide more details if the issue still persists. Feel free to create a new issue with actual details if it reproduces.

**Comment by OneDaveTaylor** [comment]
@BorisOsipov @epszaw I am not seeing nested describe blocks being contained in the parent suite in the latest version.  In the example, I was hoping to see 2 suites with all tests/describes nested inside.  Is that feasible?

`"@wdio/allure-reporter": "8.10.6",`
```
describe('Parent describe block 1', () => {
    it('test inside parent describe', async () => {
        await expect(1).toBe(1);
    })
    describe('nested describe 1', () => {
        it('test inside nested describe 1', async () => {
        await expect(1).toBe(1);
        })
    })
    describe('nested describe 2', () => {
        it('test inside nested describe 2', async () => {
            await expect(1).toBe(1);
        })
    })
})
  
describe('Parent describe block 2', () => {
    describe('nested describe 1', () => {
        it('test inside nested describe 1', async () => {
        await expect(1).toBe(1);
        })
    })
    describe('nested describe 2', () => {
        it('test inside nested describe 2', async () => {
            await expect(1).toBe(1);
        })
    })
})
```

![Screen Shot 2023-06-02 at 3 44 01 PM](https://github.com/webdriverio/webdriverio/assets/38532482/781febae-d26c-406e-a3b7-4dd824a68256)

**Comment by BorisOsipov** [comment]
@OneDaveTaylor Please feel free to file a new issue with these details to track future improvements. We don't consider any issues with old allure-js as point to improvement.

**Comment by VitaliMorgun** [comment]
Is the issue described @OneDaveTaylor was taken into account? I'm experiencing the same nesting issue with @wdio/allure-reporter: "9.2.14"

**Comment by christian-bromann** [comment]
@VitaliMorgun as you can see in the previous response, please feel free to raise a new issue with details.
