### ISSUE TITLE
Connect to an existing chromedriver instance

### ISSUE THREAD

**Issue by Deothrin** [webdriverio/webdriverio#717]
using selenium-webdriver you can do this

run a chromedriver:

`chromedriver --port=9515`

connect:

```
var driver = new webdriver.Builder()
   .withCapabilities(webdriver.Capabilities.chrome())
   .usingServer('http://localhost:9515')  // <- this
   .build();
```

is there an equivalent for webdriverio?

**Comment by christian-bromann** [comment]
@Deothrin WebdriverIO doesn't start a server for you yet. I would recommend to start it using [selenium-standalone](https://github.com/vvo/selenium-standalone). The project allows you to set the port as well.

**Comment by cg-tester** [comment]
@andreasmarkussen 
where should I run command   chromedriver --port=9515 and wdio repl  --path=/ --host=127.0.0.1 --port=9515 ?
please help me
