### ISSUE TITLE
Saucelabs status reporting not working

### ISSUE THREAD

**Issue by saulshanabrook** [webdriverio/webdriverio#718]
OK I [see that there is support to send the status of the job to Saucelabs](https://github.com/webdriverio/webdriverio/blob/2ee280aa8391a6f5930ae3c31f1be07ee456a37c/test/runner.js#L74-L91), but it isn't working for me.

This might be because I am running multiple browsers at once.

* [Travis CI Job](https://travis-ci.org/lucibus/lucibus/jobs/76036510)
* [One of the Sauce Labs jobs (showing it doesn't have a status)](https://saucelabs.com/tests/ce62aac8ac094e5fa0435a138bd52b60)
* [All the Sauce Labs jobs](https://saucelabs.com/u/sshanabrook)
* [`wdio.conf.js`](https://github.com/lucibus/lucibus/blob/1d2a3ec75b1f223a588bb98e9adc3e4b6f3c1019/caido/wdio.conf.js)

**Comment by saulshanabrook** [comment]
Should sauce connect be started in travis or will webdriverio start it automatically? I [see that there is support for starting it in webdriverio](https://github.com/webdriverio/webdriverio/blob/2ee280aa8391a6f5930ae3c31f1be07ee456a37c/test/runner.js#L44-L48), but I have been [starting sauce connect with travis](http://docs.travis-ci.com/user/sauce-connect/#Setting-up-Sauce-Connect) and that has been working. However, I thought that maybe if i had webdriverio start sauce connect somehow, then that would also get it to report the job status

**Comment by christian-bromann** [comment]
You need to start sauce connect via Travis. The link refers to the test runner that runs test on webdriverio. As you can see I start sauce connect by myself too. Integrating sauce connect into webdriverio would exceed the scope of the project. There are a lot of libraries though that help you to run sauce connect.

**Comment by saulshanabrook** [comment]
What is [this code](https://github.com/webdriverio/webdriverio/blob/2ee280aa8391a6f5930ae3c31f1be07ee456a37c/test/runner.js#L44-L48) for then?

Anyway, this is a side issue, I am currently starting sauce connect through travis.

**Comment by christian-bromann** [comment]
@saulshanabrook it is my current approach to use sauce connect when testing webdriverio (so basically only for dev purposes)

**Comment by saulshanabrook** [comment]
Hm, so does that mean that I should [add some custom code](https://github.com/webdriverio/webdriverio/issues/374#issuecomment-66311612) for sauce labs status reporting and this isn't a feature in webdriverio core?

**Comment by christian-bromann** [comment]
no, the wdio test runner should update the job, I haven't checked that issue so far. Just sayin' that Sauce Connect isn't and won't be part of WebdriverIO (maybe as a plugin but not part of the core project)

**Comment by saulshanabrook** [comment]
OK makes sense.

**Comment by christian-bromann** [comment]
@saulshanabrook do you still have a problem with this? I just tested it and all my sauce labs properties like test name or build number get propagated to sauce as well as job status.

**Comment by silvenon** [comment]
It works for me as well, the jobs are updated as expected. To tell Travis to start Sauce Connect all you need to do is add this to `.travis.yml`:

```yml
addons:
  sauce_connect:
    username: "Your Sauce Labs username"
    access_key: "Your Sauce Labs access key"
```

Read [these instructions](http://docs.travis-ci.com/user/sauce-connect/) for more info.

**Comment by saulshanabrook** [comment]
OK ill close this, and reopen if I double check it and get errors. Thanks!
