### ISSUE TITLE
Order of beforeEach() and before() block execution seems unexpected in nested describe 

### ISSUE THREAD

**Issue by YashMonetate** [webdriverio/webdriverio#7182]
Environment:
 - **WebdriverIO version:** 5.8.3
 - **Mode: WDIO Testrunner
 - **WDIO Testrunner, running in sync
 - **Node.js version:** 12.22.3
 - **NPM version:** 6.14.13
 - **Browser name and version:** Chrome 92
 - **Platform name and version:** Windows 10

**Describe the bug**
If there is nested describe block as in top level describe we have beforeEach() and in nested level describe we have before(), then it executes before() first then beforeEach() later. That seems reverse as expected

**To Reproduce**
Please use this code to reproduce. How i run the file is **yarn browser-test filename**

```
describe("top level", () => {
    beforeEach(() => {
        console.log("This is top level before each block. Should be executed first");
    });

    describe("First level nested describe", () => {
        before(() => {
            console.log("This is first level before block. Should be executed later");
        });

        it("This is sample test", () => {

        });
    });
});
```

**Expected behavior**
Expected output:
This is top level before each block. Should be executed first
This is first level before block. Should be executed later

Actual Output:
This is first level before block. Should be executed later
This is top level before each block. Should be executed first

> Please use the correct markdown

**Comment by christian-bromann** [comment]
Hey @YashMonetate 👋  thanks for raising the issue. Unfortunately WebdriverIO doesn't control the order of the execution here. It is part of the test framework, e.g. Mocha or Jasmine. Please raise this issue there, they might be able to provide more details. Thanks!
