### ISSUE TITLE
Add Rest API / API testing ability to WebdriverIO

### ISSUE THREAD

**Issue by praveendvd** [webdriverio/webdriverio#7186]
**Is your feature request related to a problem? Please describe.**

It would be great if we can integrate API testing into our WebdriverIO platform, but we could do this also by not reinventing the wheel as there are already opensource tools like chakram which looks to be promising : 

 http://dareid.github.io/chakram/jsdoc/index.html
http://dareid.github.io/chakram/

**Describe the solution you'd like**

Allow user to create browser object as chakram or any other tool object and see how we can integrate request and response data into the exciting reporting framework

**Describe alternatives you've considered**

Create a headless chrome driver capability and run chakram in the test framework like mocha, jasmine etc

**Comment by BorisOsipov** [comment]
>It would be great if we can integrate API testing into our WebdriverIO platform

I dont think so. There are enough libs\tools for API testing.

> tools like chakram which looks to be promising

It is abandoned project based on fully deprecated request http client lib.

**Comment by praveendvd** [comment]
@BorisOsipov  True but having to switch between tools for different test levels can be avoided, now we can use webdriverIO for web, electron, mobile, WPF and adding API to the list sounds interesting.

**Comment by christian-bromann** [comment]
The advantage I see of adding API testing capabilities would be the ability to leverage the WebdriverIO ecosystem, its reporters and services. As @praveendvd mentioned the notion of being able to use one tool for multiple types of testing can be appealing. We see it in other frameworks, e.g. [TheIntern](https://theintern.io/), that combine e2e with unit testing capabilities.

Something I believe we should answer is:
- what are current popular API testing tools
- where could WebdriverIO provide an advantage compared to the existing tools
- how should this look like (e.g. if you omit capabilities, you automatically run API tests, or do we have an `$ wdio run e2e wdio.conf.js` vs. `$ wdio run api wdio.conf.js`?

I can imagine some other opportunities here we can leverage API response data to build mock server for e2e tests.
