### ISSUE TITLE
Getting 'No specs found to run, exiting with failure' even though theres is specs mentioned in config file

### ISSUE THREAD

**Issue by Vijaygc112** [webdriverio/webdriverio#7188]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - WebdriverIO version: 7.8.0
 - Mode: WDIO Testrunner [sync]
 - Node.js version: 14.17.3
 - NPM version: 7.19.1

An example of how you configured WebdriverIO config
exports.config = {
    runner: 'local',
    port: 4723,
    host: 'localhost',
    path: '/wd/hub',
    loglevel: 'info',
    framework: 'mocha',
    mochaOpts:{
        ui: 'bdd',
        require:['@babel/register'],
        timeout: 600000
    },
    maxInstances: 1,
    sync: true, 
    specs:[
        './test/spec/playwithmocha.js'
    ]

}

I am getting 'No specs found to run, exiting with failure' error even though I am just trying to try the framework out for a Hello World program

https://github.com/Vijaygc112/WebdriverIO-Appium

I should be able to run mocha tests

**Comment by BorisOsipov** [comment]
@Vijaygc112 you must set capabilities in config. See https://webdriver.io/docs/options/#capabilities

**Comment by Vijaygc112** [comment]
Yes it started working after I added capabilities. Thank you.
