### ISSUE TITLE
Can not figure out how to work with opera driver

### ISSUE THREAD

**Issue by rain1017** [webdriverio/webdriverio#719]
I have installed operadriver in the PATH,  but it can't be loaded with selenium.jar, so simply set desiredCapabilities.browserName does not work
```
17:21:50.437 INFO - Driver class not found: com.opera.core.systems.OperaDriver
17:21:50.438 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered

The best matching driver provider org.openqa.selenium.safari.SafariDriver can't create a new driver instance for Capabilities [{loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@f5f80d4, platform=ANY, javascriptEnabled=true, handlesAlerts=true, browserName=opera, requestOrigins={name=webdriverio, url=http://webdriver.io, version=3.1.0}, rotatable=true, locationContextEnabled=true, version=}]
```

According to [this](https://github.com/operasoftware/operachromiumdriver/blob/master/docs/desktop.md),
we have to use the RemoteWebDriver,  the following python script worked
```python
import time
from selenium import webdriver
from selenium.webdriver.chrome import service
webdriver_service = service.Service('./operadriver')
webdriver_service.start()
driver = webdriver.Remote(webdriver_service.service_url, webdriver.DesiredCapabilities.OPERA)
```
However, I can't find any equivalent in webdriver.io.

**Comment by christian-bromann** [comment]
How are your capabilities look like?

**Comment by rain1017** [comment]
```js   
desiredCapabilities: {
    browserName: 'opera'
}
```

**Comment by christian-bromann** [comment]
I wasn't able to get opera running using the standalone server. If I set `browserName: "opera"` the server always starts chrome. However I [downloaded](https://github.com/operasoftware/operachromiumdriver/releases) the operadriver and put the binary somewhere where it was available (`/usr/bin`) on my system (mac). Then I started the driver

```sh
$ operadriver --port=4444 --verbose
```

Like other drivers the path to API is not `/wd/hub` so you need to set the path to `/`. The script I was running looked like:

```js
var client = require('webdriverio').remote({
    path: '/',
    desiredCapabilities: {
        browserName: 'opera'
    }
})

client
    .init()
    .url('http://opera.com')
    .end();
```

The ability to change the path got introduced by #690 and is not yet released. I am working on that to get a new release out as soon as possible
