### ISSUE TITLE
Allow a simple project using the `wdio` package

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#7195]
Let's make the on boarding to WebdriverIO even more simpler by allowing to run a simple command:

```sh
$ npx wdio /path/to/project
```

This should:

- create the directory if not already existing
- install `@wdio/cli`
- run `$ npx wdio config`

We should make sure that a global installed `wdio` package doesn't interfere with a local installed `@wdio/cli` that has a `wdio` binary. I would like to also see an update to our main page showing how quickly you can run a simple test.

**Comment by erwinheitzman** [comment]
I think we can already close this can't we? 😃

**Comment by christian-bromann** [comment]
For reference: https://github.com/webdriverio/wdio
