### ISSUE TITLE
iOS simulators on Sauce are not working with same setup as Android emulators

### ISSUE THREAD

**Issue by juanalblue** [webdriverio/webdriverio#7199]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.9.0
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async]
 - **Node.js version:** 12.13.0
 - **NPM version:** 6.12.0
 - **Browser name and version:** Safari
 - **Platform name and version:** iOS 14.3
 - **Additional wdio packages used (if applicable):**

**Config of WebdriverIO**
services: [
    [
      'sauce',
      {
        sauceConnect: true,
        sauceConnectOpts: { tunnelIdentifier: '1988009-10' }
      }
    ]
  ],
.
.
.
 capabilities: [
  {
    "browserName": "Safari",
    "platformName": "iOS",
    "build": "OneID UIv4 | LOCAL | iPhone 11 Pro Max Simulator | 14.3 | iOS | DTCI-ALL-REGFIELDS.WEB | US | en-US | Pipeline#1988009 portrait",
    "automationName": "XCUITest",
    "deviceName": "iPhone 11 Pro Max Simulator",
    "enablePerformanceLogging": true,
    "idleTimeout": 60000,
    "newCommandTimeout": 60000,
    "deviceOrientation": "PORTRAIT",
    "platformVersion": "14.3"
  }
],
.
.
.

**Describe the bug**
The same configuration except what must be changed (see bellow) results in working Android devices but the iOS devices return the following error and log: 
ERROR webdriver: MaxRedirectsError: Redirected 10 times. Aborting.
[0-3]     at Request._onResponseBase (/app/node_modules/got/dist/source/core/index.js:853:35)
[0-3]     at Request._onResponse (/app/node_modules/got/dist/source/core/index.js:934:24)
[0-3]     at ClientRequest.<anonymous> (/app/node_modules/got/dist/source/core/index.js:948:23)
[0-3]     at Object.onceWrapper (events.js:300:26)
[0-3]     at ClientRequest.emit (events.js:215:7)
[0-3]     at ClientRequest.EventEmitter.emit (domain.js:476:20)
[0-3]     at ClientRequest.origin.emit (/app/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
[0-3]     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
[0-3]     at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
[0-3]     at TLSSocket.socketOnData (_http_client.js:456:22)
[0-3] [pid 144] 2021-07-28T21:51:17.782Z ERROR @wdio/runner: Error: Failed to create session.
[0-3] Redirected 10 times. Aborting.
[0-3]     at Object.startWebDriverSession (/app/node_modules/webdriver/build/utils.js:68:15)
[0-3]     at processTicksAndRejections (internal/process/task_queues.js:93:5)

This looks similar to me as this issue from last year, but it was fixed in v6 and we are to v7.9 now.
https://github.com/webdriverio/webdriverio/issues/5262

Settings for the working Android device
services: [
    [
      'sauce',
      {
        sauceConnect: true,
        sauceConnectOpts: { tunnelIdentifier: '1988009-9' }
      }
    ]
  ],
.
.
.
capabilities:[
  {
    "browserName": "Chrome",
    "platformName": "Android",
    "build": "OneID UIv4 | LOCAL | Samsung Galaxy Tab A 10 GoogleAPI Emulator | 8.0 | Android | DTCI-ALL-REGFIELDS.WEB | US | en-US | Pipeline#1988009 portrait",
    "automationName": "UiAutomator2",
    "deviceName": "Samsung Galaxy Tab A 10 GoogleAPI Emulator",
    "enablePerformanceLogging": true,
    "idleTimeout": 60000,
    "newCommandTimeout": 60000,
    "deviceOrientation": "PORTRAIT",
    "platformVersion": "8.0"
  }
]

**To Reproduce**
Run any tests with the two sets of capabilities above (the use of tunnelIdentifier does not seem to change anything but using sauceConnect is needed for our tests to run) and the android one will work and the iOS one will fail after 10 redirections.

**Expected behavior**
iOS device tests should run just as Android device tests.

**Log**
The snips above are about all the logs I have.

**Additional context**
I tried to do a version of this using the appium:capability format for the appium specific configs but it also fails with "@wdio/runner: Error: Invalid or unsupported WebDriver capabilities found ("tunnelIdentifier")." even when I do not use tunnelIdentifier.  I may file a separate bug on that soon.

> Please use the correct markdown

**Comment by christian-bromann** [comment]
@juanalblue thanks for reporting the issue. It seems there is an issue starting these virtual devices. I was able to [reproduce this](https://app.saucelabs.com/tests/be0d6d12a9f64e60a71e02b8fd9428b2). I connected to the appropriate team and they started to investigate.

**Comment by christian-bromann** [comment]
The problem was identified and logged in the [appropriate repository](https://github.com/appium/appium-remote-debugger/issues/251). As workaround I suggest to remove the `enablePerformanceLogging` capability for iOS until this is fixed. Please follow this issue for updates. I will close this issue as there is nothing that can be done in WebdriverIO.

**Comment by asanders-tester** [comment]
I'm having this same issue with iOS on AWS Device Farm, except I'm not using `enablePerformanceLogging` in my capabilities at all. I added it in and set the value to false, but I'm getting the same error. I've tried changing the `connectionRetryTimeout` to as high as 500000, but it's still the same error. Here's the log from AWS:

[DEVICEFARM] Setting up your device. This usually takes 2-3 minutes.
[DEVICEFARM] ########### Start executing testspec ###########
 
 
[DEVICEFARM] ########### Entering phase install ###########
 
[DeviceFarm] export APPIUM_VERSION=1.19.0
[DeviceFarm] avm $APPIUM_VERSION
  [36m    exists[0m : [90m1.19.0[0m
[DeviceFarm] ln -s /usr/local/avm/versions/$APPIUM_VERSION/node_modules/.bin/appium  /usr/local/avm/versions/$APPIUM_VERSION/node_modules/appium/bin/appium.js
ln: /usr/local/avm/versions/1.19.0/node_modules/appium/bin/appium.js: File exists
[DeviceFarm] if [ $(echo $APPIUM_VERSION | cut -d "." -f2) -ge 19 ]; then
  DEVICEFARM_DEVICE_UDID_FOR_APPIUM=$(echo $DEVICEFARM_DEVICE_UDID | tr -d "-");
  DEVICEFARM_WDA_DERIVED_DATA_PATH=$DEVICEFARM_WDA_DERIVED_DATA_PATH_V6;
elif [ $(echo $APPIUM_VERSION | cut -d "." -f2) -ge 18 ]; then
  DEVICEFARM_DEVICE_UDID_FOR_APPIUM=$(echo $DEVICEFARM_DEVICE_UDID | tr -d "-");
  DEVICEFARM_WDA_DERIVED_DATA_PATH=$DEVICEFARM_WDA_DERIVED_DATA_PATH_V5;
elif [ $(echo $APPIUM_VERSION | cut -d "." -f2) -ge 17 ]; then
  DEVICEFARM_DEVICE_UDID_FOR_APPIUM=$(echo $DEVICEFARM_DEVICE_UDID | tr -d "-");
  DEVICEFARM_WDA_DERIVED_DATA_PATH=$DEVICEFARM_WDA_DERIVED_DATA_PATH_V4;
elif [ $(echo $APPIUM_VERSION | cut -d "." -f2) -ge 16 ]; then
  DEVICEFARM_DEVICE_UDID_FOR_APPIUM=$(echo $DEVICEFARM_DEVICE_UDID | tr -d "-");
  DEVICEFARM_WDA_DERIVED_DATA_PATH=$DEVICEFARM_WDA_DERIVED_DATA_PATH_V3;
elif [ $(echo $APPIUM_VERSION | cut -d "." -f2) -ge 15 ]; then
  DEVICEFARM_DEVICE_UDID_FOR_APPIUM=$(echo $DEVICEFARM_DEVICE_UDID | tr -d "-");
  DEVICEFARM_WDA_DERIVED_DATA_PATH=$DEVICEFARM_WDA_DERIVED_DATA_PATH_V2;
else
  DEVICEFARM_DEVICE_UDID_FOR_APPIUM=$DEVICEFARM_DEVICE_UDID;
  DEVICEFARM_WDA_DERIVED_DATA_PATH=$DEVICEFARM_WDA_DERIVED_DATA_PATH_V1;
fi
[DeviceFarm] nvm install 15.5.1
Downloading and installing node v15.5.1...
Downloading https://nodejs.org/dist/v15.5.1/node-v15.5.1-darwin-x64.tar.xz...
#=#=#                                                                         
##O#- #                                                                       

##                                                                         3.3%
####                                                                       6.1%
#####                                                                      7.7%
######                                                                     9.4%
########                                                                  12.0%
##########                                                                14.3%
###########                                                               16.1%
############                                                              17.6%
##############                                                            19.7%
################                                                          22.8%
#################                                                         24.8%
###################                                                       27.3%
#######################                                                   32.7%
############################                                              39.0%
###############################                                           44.4%
######################################                                    53.2%
##########################################                                58.9%
##########################################                                59.5%
###############################################                           65.3%
##################################################                        70.8%
#######################################################                   77.3%
##############################################################            86.7%
##################################################################        92.5%
#####################################################################     96.1%
######################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
npm notice 
npm notice New minor version of npm available! 7.3.0 -> 7.20.6
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.20.6>
npm notice Run `npm install -g npm@7.20.6` to update!
npm notice 
Now using node v15.5.1 (npm v7.3.0)
[DeviceFarm] echo "Navigate to test package directory"
Navigate to test package directory
[DeviceFarm] cd $DEVICEFARM_TEST_PACKAGE_PATH
[DeviceFarm] npm install *.tgz

added 1 package, and audited 892 packages in 5m

77 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
 
[DEVICEFARM] ########### Entering phase pre_test ###########
 
[DeviceFarm] echo "Start appium server"
Start appium server
[DeviceFarm] appium --log-timestamp --address 127.0.0.1 --default-capabilities "{\"usePrebuiltWDA\": true, \"derivedDataPath\":\"$DEVICEFARM_WDA_DERIVED_DATA_PATH\", \"deviceName\": \"$DEVICEFARM_DEVICE_NAME\", \"platformName\":\"$DEVICEFARM_DEVICE_PLATFORM_NAME\", \"app\":\"$DEVICEFARM_APP_PATH\", \"automationName\":\"XCUITest\", \"udid\":\"$DEVICEFARM_DEVICE_UDID_FOR_APPIUM\", \"platformVersion\":\"$DEVICEFARM_DEVICE_OS_VERSION\"}" >> $DEVICEFARM_LOG_DIR/appiumlog.txt 2>&1 &
[DeviceFarm] start_appium_timeout=0; while [ true ]; do
    if [ $start_appium_timeout -gt 60 ];
    then
        echo "appium server never started in 60 seconds. Exiting";
        exit 1;
    fi;
    grep -i "Appium REST http interface listener started on 127.0.0.1:4723" $DEVICEFARM_LOG_DIR/appiumlog.txt >> /dev/null 2>&1;
    if [ $? -eq 0 ];
    then
        echo "Appium REST http interface listener started on 127.0.0.1:4723";
        break;
    else
        echo "Waiting for appium server to start. Sleeping for 1 second";
        sleep 1;
        start_appium_timeout=$((start_appium_timeout+1));
    fi;
done;
Waiting for appium server to start. Sleeping for 1 second
Waiting for appium server to start. Sleeping for 1 second
Waiting for appium server to start. Sleeping for 1 second
Waiting for appium server to start. Sleeping for 1 second
Waiting for appium server to start. Sleeping for 1 second
Appium REST http interface listener started on 127.0.0.1:4723
 
[DEVICEFARM] ########### Entering phase test ###########
 
[DeviceFarm] echo "Navigate to test code directory"
Navigate to test code directory
[DeviceFarm] cd $DEVICEFARM_TEST_PACKAGE_PATH/node_modules/test-runner*
[DeviceFarm] echo "Start Appium Node test"
Start Appium Node test
[DeviceFarm] cp -R mobile/tests ../../tests
[DeviceFarm] npx jest cancelApprovedApplication.test.js --config mobile/jest.mobile_aws.config.js
  console.log
    testLog:Test environment: stage, OS: ios

      at testLog (node_modules/test-runner/mobile/utils/globals.js:730:13)

  console.log
    ┌───────────┬─────────┐
    │  (index)  │ Values  │
    ├───────────┼─────────┤
    │ targetEnv │ 'stage' │
    │ startEnv  │ 'stage' │
    │  sameEnv  │  true   │
    └───────────┴─────────┘

      at activateSwitchEnv (node_modules/test-runner/mobile/utils/globals.js:596:13)

  console.info
    2021-08-16T01:15:37.803Z INFO webdriver: Initiate new session using the WebDriver protocol

      at apply (node_modules/test-runner/node_modules/@wdio/logger/build/node.js:76:9)

  console.info
    2021-08-16T01:15:37.839Z INFO webdriver: [POST] http://localhost:4723/wd/hub/session

      at apply (node_modules/test-runner/node_modules/@wdio/logger/build/node.js:76:9)

  console.info
    2021-08-16T01:15:37.849Z INFO webdriver: DATA {
      capabilities: {
        alwaysMatch: {
          platformName: 'ios',
          enablePerformanceLogging: false,
          newCommandTimeout: 1200,
          noReset: false
        },
        firstMatch: [ {} ]
      },
      desiredCapabilities: {
        platformName: 'ios',
        enablePerformanceLogging: false,
        newCommandTimeout: 1200,
        noReset: false
      }
    }

      at apply (node_modules/test-runner/node_modules/@wdio/logger/build/node.js:76:9)

  console.warn
    2021-08-16T01:17:38.030Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.

      at apply (node_modules/test-runner/node_modules/@wdio/logger/build/node.js:76:9)
      at Logger.warn (node_modules/test-runner/node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
      at retry (node_modules/test-runner/node_modules/webdriver/build/request.js:121:17)
      at WebDriverRequest._request (node_modules/test-runner/node_modules/webdriver/build/request.js:127:24)
      at Object.startWebDriverSession (node_modules/test-runner/node_modules/webdriver/build/utils.js:29:20)
      at Function.newSession (node_modules/test-runner/node_modules/webdriver/build/index.js:35:45)

  console.info
    2021-08-16T01:17:38.042Z INFO webdriver: Retrying 1/3

      at apply (node_modules/test-runner/node_modules/@wdio/logger/build/node.js:76:9)
