### ISSUE TITLE
Placing data in clipboard in order to paste

### ISSUE THREAD

**Issue by astoilkov** [webdriverio/webdriverio#720]
Hi,

I am trying to do a paste in a `<textarea>` element. The problem is that I can't perform select, cut and then paste (as described [here](https://github.com/webdriverio/webdriverio/issues/290)). I should have a direct way for pasting without all other commands. I need this because I have a state before I perform a paste which I can't disregard. Let me give you an example:

 1. I write `function (|)`
 2. Select some text `fun|ction (|)` (now `ction (` is selected)

Now I need to do a paste. However, if I start writing the desired content to paste I will lose my selection and don't know how to retrieve it after. I was thinking I can create a separate `<textarea>` and write there and cutting and placing the data in the clipboard but again I can't retrieve the selection in the previous `<textarea>` element.

Any suggestions on how to achieve what I want is greatly appreciated.

**Comment by christian-bromann** [comment]
> Now I need to do a paste.

do that with `setValue(element, ["Control","v"])`

> I will lose my selection and don't know how to retrieve it after

Isn't this the usual case if you paste something?

I am not sure if I have quite understand what the exact problem is, could you explain it in more detail please? Thanks!

**Comment by astoilkov** [comment]
I will try in less detail to get confusion out of the way. I want to paste a custom string. The clipboard can for example "clipboard text". However, I want to paste "custom word".

**Comment by christian-bromann** [comment]
Can you set the value of an random input element to `custom word` then copy that text and paste it into the textarea?

**Comment by astoilkov** [comment]
And now we get back to the problem that I described in my first post. If you focus random input element and copy from there I can't retrieve the selection in the input I was before going to the random one.

**Comment by christian-bromann** [comment]
You could copy the text first and then select the text in the textarea, could you?

**Comment by astoilkov** [comment]
No. I can't. There will be multiple paste commands with different text I want to paste when writing. This will solve the problem for the first paste.

I am testing a custom Editor that is built on top of `<textarea>` element that supports autocompletion and in order to test it I need complex sequences of text writing, cut, copy, paste, selection with Shift key, and keyboard shortcuts. 

This is why I need a paste that will paste anything I tell it without hackery like selecting another input and copying from there. I imagined it will be possible to put something in the clipboard.

**Comment by christian-bromann** [comment]
No there is no Selenium command to put stuff into the clipboard. However you can try to that by injecting javascript using execute.

**Comment by astoilkov** [comment]
Thanks a lot. Actually, you got me thinking and I found a solution. I used node.js to copy content to the clipboard.
```
var escape = require('shell-escape');
require('child_process').execSync('printf ' + escape([text]) + ' | pbcopy');
```

**Comment by ponmudivn** [comment]
node-copy-paste module can be used to copy data to clipboard.

https://github.com/xavi-/node-copy-paste

**Comment by xcao-riffyn** [comment]
@ponmudivn copy-paste works like a charm!  Unbelievable!  The code is super simple
