### ISSUE TITLE
Do not swallow unknown errors

### ISSUE THREAD

**Issue by avalkowsky** [webdriverio/webdriverio#7200]
**Environment (please complete the following information):**
 - **WebdriverIO version: 5.23.0** 
 - **Mode:  WDIO Testrunner ** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync:** [e.g. sync/async]
 - **Node.js version: 12.15.0** [e.g. 8.11.2]
 - **NPM version: 6.13.14** [e.g. 5.8.0]
 - **Browser name and version: - **
 - **Platform name and version: -**
 - **Additional wdio packages used (if applicable):** 

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**

We are running tests that are executed by a custom webdriver server following the RFC spec of webdriver.
When an error is returned by the AWS infrastructure before going to the server, all we see in logs is 'Unknown Error' while a simple JSON.stringify on the body will result in revealing the actual error like: '{"message":"Unauthorized"}'.

**To Reproduce**
Return an error that does not comply with the utils/getErrorFromResponseBody

**Expected behavior**
The error is logged so that the user can investigate it:
'unknown error: {"message":"Unauthorized"}'

**Possible solution**
Parse unknown errors:
```
function getErrorFromResponseBody(body) {
  if (!body) {
    return new Error('Response has empty body');
  }

  if (typeof body === 'string' && body.length) {
    return new Error(body);
  }

  if (typeof body !== 'object' || !body.value && !body.error) {
    let unknownBody;
    try {
      unknownBody = ': ' + JSON.stringify(body);
    } catch(e) {
      unknownBody = ' - stringify error while reading(' + body + '):' + e;
    }

    return new Error('unknown error' + unknownBody);
  }
```

I could even do a pull request but honestly don't know where to put in code as I manipulated the already build files in node_modules/webdriver/dist to investigate it.
Cheers!

**Comment by erwinheitzman** [comment]
Could you test this with v6 or higher as we currently only support v6 and v7?

**Comment by praveendvd** [comment]
> Could you test this with v6 or higher as we currently only support v6 and v7?

for wdio 7 also it does the same thing, like if element is not found it won't throw error unless we do some actions on it 

```
example
it("test pass",()=>{

await $("wrong")

})


it("test fail",()=>{

await (await $("wrong")).getText()

})
```

**Comment by erwinheitzman** [comment]
@praveendvd that's logical because the first example doesn't don't do anything and has nothing to do with the issue mentioned above.

**Comment by praveendvd** [comment]
> @praveendvd that's logical because the first example doesn't don't do anything and has nothing to do with the issue mentioned above.
> 
> EDIT: the main reason I ask to test this in v6/v7 is that we no longer maintain v5 as is has become deprecated (it's years old by now).

Yes so was mentioning that  the unknown error might throw error if the user try to do something on it

**Comment by christian-bromann** [comment]
Added PR with a fix: https://github.com/webdriverio/webdriverio/pull/7206
