### ISSUE TITLE
Selenium Standalone Service doesn't work with given browser version in linux or docker container

### ISSUE THREAD

**Issue by maleeazeem** [webdriverio/webdriverio#7203]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** ^6
 - **Mode:** "@wdio/selenium-standalone-service": "^6.6.5"
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12
 - **NPM version:** 6.14.12
 - **Browser name and version:** Microsoft-Edge 93.0.961.2 dev
 - **Platform name and version:** Linux / docker
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
```js
const customSeleniumStandAlone = [['selenium-standalone', {
    logPath: 'logs',
    installArgs: {
        version: '3.141.59',
        baseURL: 'https://selenium-release.storage.googleapis.com',
        drivers: {
            chromiumedge: {
                // version: '91.0.864.70' // version to run in mac os
                version: '93.0.961.2'     // version to run in docker container
            }
        },
        chrome : {
            version : '92.0.4515.107',
            arch    : process.arch
        },
        firefox: {
            version: '0.29.1'
        }
    }
}]];

_Capabilities_

export function getCapabilities() {
    const capabilities = {
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 3 instances get started at a time.
        // maxInstances:
        acceptInsecureCerts: true,
        browserName: params.getBrowserName()
    };
    if (params.getBrowserName() === 'microsoftedge' || params.getBrowserName() === 'MicrosoftEdge') {
        capabilities['browserName'] = 'MicrosoftEdge';
        capabilities['ms:edgeOptions'] = {
            args: [
                '--disable-dev-shm-usage',
                '--headless', // Run headless in CI, no one is looking anyway
                '--no-sandbox', // Sice the container is itself a sandbox, unsandbox to avoid permission issues
                '--disable-gpu', // Temporary requirement to deal with known bugs
                '--window-size=1680,1050'
            ]
        };
    }
    if (params.getBrowserName() === 'firefox') {
        capabilities['moz:firefoxOptions'] = {
            args: [
                '--headless', // Run headless in CI, no one is looking anyway
                '--window-size=1680,1050'
            ]
        };
    }
    if (params.getBrowserName() === 'chrome' && (params.isDocker() === true || params.isHeadless())) {
        capabilities['goog:chromeOptions'] = {
            args: [
                '--disable-dev-shm-usage',
                '--no-sandbox', // Sice the container is itself a sandbox, unsandbox to avoid permission issues
                '--headless', // Run headless in CI, no one is looking anyway
                '--disable-gpu', // Temporary requirement to deal with known bugs
                '--window-size=1680,1050'
            ]
        };
    }
    if (params.isSauce() || params.getBrowserName() === 'internet explorer' ||
        params.getBrowserName() === 'ie' || params.getBrowserName() === 'safari') {
        return getCapabilitiesForSauceLabs(params.getBrowserName(), params.getPlatform(),
            params.getBrowserVersion());
    }
    return capabilities;
}
```

**Describe the bug**
      **Test run in macOS with Edge Browser**
With Above configs when I run the tests from my mac terminal tests run successfully and after giving a command 
"ls node_modules/selenium-standalone/.selenium/"  I can see chromiumedgedriver folder with expected edge driver in it.

<img width="1324" alt="Screen Shot 2021-07-29 at 9 49 42 AM" src="https://user-images.githubusercontent.com/50889269/127532633-b7a78955-209c-4ef7-8dcf-abc4e764353c.png">
<img width="1073" alt="Screen Shot 2021-07-29 at 9 27 03 AM" src="https://user-images.githubusercontent.com/50889269/127532713-a9080b15-aa28-4e5e-a223-5bcfab859197.png">

      **Test run in docker with Edge Browser**
I have created docker images which has Microsoft Edge 93.0.961.2 dev installed. When I try to run in docker container with the selenium-standalone configs as I mentioned above I get an error of "ERROR webdriver: RequestError: connect ECONNREFUSED 127.0.0.1:4444". In docker container when I give a command below after running the tests with edge
"ls node_modules/selenium-standalone/.selenium/" it shows only one folder of "selenium-server" 

<img width="1073" alt="Screen Shot 2021-07-29 at 9 27 03 AM" src="https://user-images.githubusercontent.com/50889269/127532790-29602cf6-af15-4349-a469-b3e8d97b5243.png">

**To Reproduce**
Create a docker image of Edge Browser 
     FROM ubuntu:latest
ENV LC_ALL=C
ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN=true
ENV PATH "$PATH:/opt/microsoft/msedge-dev"

RUN groupadd --gid 1000 node \
  && useradd --uid 1000 --gid node --shell /bin/bash --create-home node

RUN apt-get -qqy update
RUN apt-get -qqy install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common
RUN curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
RUN echo "deb http://archive.ubuntu.com/ubuntu xenial main universe\n" > /etc/apt/sources.list \
  && echo "deb http://archive.ubuntu.com/ubuntu xenial-updates main universe\n" >> /etc/apt/sources.list \
  && echo "deb http://security.ubuntu.com/ubuntu xenial-security main universe\n" >> /etc/apt/sources.list
RUN apt-get -qqy update

RUN curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
RUN sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/ \
    && sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list' \
    && sudo rm microsoft.gpg

RUN curl -sL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash -
RUN apt-get -qqy --force-yes --no-install-recommends install \
  git \
  nodejs \
  firefox \
  microsoft-edge-dev \
  google-chrome-stable \
  openjdk-8-jre-headless \
  x11vnc \
  xvfb

RUN firefox --version
RUN google-chrome --version
RUN node --version
RUN npm --version

After creation of image, use the same image to run tests with above configs in wdio.conf.js file

[Include code or an example repository that can easily be set up]

**Expected behavior**
Folder of chromiumedgebrowser(drivers in it) should be created under node_modules/selenium-standalone/.selenium/ in docker

**Log**
[0-5] 2021-07-29T16:22:15.851Z ERROR @wdio/runner: Error: Failed to create session.
Unable to connect to "http://localhost:4444/wd/hub", make sure browser driver is running on that address.
If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.
    at Object.startWebDriverSession (/usr/webdriverio-test/node_modules/webdriver/build/utils.js:34:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0-5] FAILED in MicrosoftEdge - /cookbookJsFiles/src/test/specs/rallyhealth_po.ui.js
[0-6] [INFO][2021-07-29T16:22:18.406 src/helpers/wdioConfHelper.ts:214:14] Start reading file of axe.min.js
[0-6] RUNNING in MicrosoftEdge - /cookbookJsFiles/src/test/specs/sharedStoreTest.ui.js
[0-6] 2021-07-29T16:22:19.909Z ERROR webdriver: RequestError: connect ECONNREFUSED 127.0.0.1:4444
    at ClientRequest.<anonymous> (/usr/webdriverio-test/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:326:22)
    at ClientRequest.EventEmitter.emit (domain.js:483:12)
    at ClientRequest.origin.emit (/usr/webdriverio-test/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at Socket.socketErrorListener (_http_client.js:427:9)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
[0-6] 2021-07-29T16:22:19.913Z ERROR @wdio/runner: Error: Failed to create session.
Unable to connect to "http://localhost:4444/wd/hub", make sure browser driver is running on that address.
If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.
    at Object.startWebDriverSession (/usr/webdriverio-test/node_modules/webdriver/build/utils.js:34:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0-6] FAILED in MicrosoftEdge - /cookbookJsFiles/src/test/specs/sharedStoreTest.ui.js

**Comment by christian-bromann** [comment]
Can you provide any WebdriverIO logs showing what the Selenium Standalone server is doing? It seems it didn't register on port `4444` which can have many reasons.

**Comment by erwinheitzman** [comment]
I believe from old discussions this is usually a permission problem where it fails to download the driver or downloads it but fails to set the correct permissions. Might be useful to check that but like Christian said, we can only make assumptions without logs :)

**Comment by maleeazeem** [comment]
Here is a screen shot of more logs inside the docker. 
![Screen Shot 2021-08-02 at 1 43 56 PM](https://user-images.githubusercontent.com/50889269/127921495-fb7d0f17-e648-4f7b-a13d-f562b39fd9e2.png)

I am also getting an error of in the beginning of the test. I am using Edge not chrome.
_Error: Missing /usr/webdriverio-test/node_modules/selenium-standalone/.selenium/chromedriver/latest-x64-chromedriver
    at /usr/webdriverio-test/node_modules/selenium-standalone/lib/check-paths-existence.js:16:29
    at suppressedCallback (fs.js:215:5)
    at FSReqCallback.oncomplete (fs.js:156:23)_

**Comment by erwinheitzman** [comment]
It states port 4444 is already in use

**Comment by christian-bromann** [comment]
Yes, this seems like a configuration issue. I recommend have a look at one of the [boilerplate projects](https://github.com/17thSep/WebdriverIO_Master/tree/master/TypeScript/Docker) that uses Docker.

**Comment by maleeazeem** [comment]
It states 4444 in used. How can I resolve the issue. Do I need to change port in selenium-standalone options? Boilerplate doesn't work for me, the reason is I am creating my own browser image and using it.
