### ISSUE TITLE
How to use with Electron?

### ISSUE THREAD

**Issue by LeMoussel** [webdriverio/webdriverio#721]
For testing with web driver, I use [Electron](https://github.com/atom/electron) with WebDriverJS ([JavaScript Selenium driver](http://seleniumhq.github.io/selenium/docs/api/javascript/)). It as an example.

```javascript
var webdriver = require('selenium-webdriver');
var driver = new webdriver.Builder()
  // The "9515" is the port opened by chrome driver.
  .usingServer('http://localhost:9515')
  .withCapabilities({chromeOptions: {
    // Here is the path to your Electron binary.
    binary: 'C:/Path-to-Your-App/Electronbinary/electron-v0.30.4-win32-ia32/electron.exe'}})
   .setProxy(proxy.pac('http://proxy.mysite.fr/proxy.pac'))
  .forBrowser('electron')
  .build();
driver.get('http://www.google.com');
```
Is it possible tu `webdriverio` with Electron? How? Did you have example?

With our [basic configuration](http://webdriver.io/guide/getstarted/configuration.html) documentation, I do this 
```javascript
var webdriverio = require('webdriverio');
var options = {
    desiredCapabilities: {
            browserName: 'chrome' 
            chromeOptions: {binary: 'C:/Path-to-Your-App/Electronbinary/electron-v0.30.4-win32-ia32/electron.exe'},
            Proxy: {proxyType: pac, proxyAutoconfigUrl: 'http://proxy.mysite.fr/proxy.pac' }
        }
};
var driver = webdriverio.remote(options);
driver.url('http://www.google.com');
```
Is it exact?
I don't find how to set the parameter server to 'http://localhost:9515'

**Comment by christian-bromann** [comment]
using server means where your selenium server is running. WebdriverIO uses host (defaults to localhost) and port (defaults to 4444) property here.

This should work for you:
```js
var webdriverio = require('webdriverio');
var options = {
    port: 9515,
    desiredCapabilities: {
            browserName: 'chrome' 
            chromeOptions: {binary: 'C:/Path-to-Your-App/Electronbinary/electron-v0.30.4-win32-ia32/electron.exe'},
            Proxy: {proxyType: pac, proxyAutoconfigUrl: 'http://proxy.mysite.fr/proxy.pac' }
        }
};
var driver = webdriverio.remote(options);
driver.url('http://www.google.com');
```

Glad to see you switching to WebdriverIO! Let me know if there are any other problems

**Comment by LeMoussel** [comment]
I use ChromeDriver server (V 2.15),

![2015-08-20_19-20-24](https://cloud.githubusercontent.com/assets/1816573/9390289/91090c56-4770-11e5-8f01-ae19af2fa4d4.png)

with this code
```javascript
var webdriverio = require('webdriverio');
var options = {
    port: 9515,
    desiredCapabilities: {
            browserName: 'chrome',
            chromeOptions: {binary: 'C:/Users/lemoussel/OneDrive/Electron/Drivium_io/electron-v0.30.4-win32-ia32/electron.exe'},
        }
};

webdriverio
    .remote(options)
    .init()
    .url('http://www.google.com')
    .title(function(err, res) {
        console.log('Title was: ' + res.value);
    })
    .end();
```
I have got this error

> [424:0820/191702:INFO:CONSOLE(0)]  [31mRuntimeError: Couldn't connect to selenium server [0m
> [424:0820/191702:INFO:CONSOLE(0)]  [1;30m    at end() at C:\Users\lemoussel\OneDrive\Electron\Drivium_io\main.js:25:6 [0m
[424:0820/191702:INFO:CONSOLE(0)]  [31mRuntimeError: Couldn't connect to selenium server [0m
[424:0820/191702:INFO:CONSOLE(0)]  [1;30m    at end() at C:\Users\lemoussel\OneDrive\Electron\Drivium_io\main.js:25:6 [0m
[424:0820/191702:INFO:CONSOLE(0)]  [31mRuntimeError: Couldn't connect to selenium server [0m
[424:0820/191702:INFO:CONSOLE(0)]  [1;30m    at end() at C:\Users\lemoussel\OneDrive\Electron\Drivium_io\main.js:25:6 [0m

**Comment by LeMoussel** [comment]
I found why with from [issue #113](https://github.com/webdriverio/webdriverio/issues/113#issuecomment-29896726) :+1: 

So on my Win 7, in chromedriver directory, I run ChromeDriver like this 
`chromedriver --url-base=/wd/hub --port=9515`

and I run the node process that connects to chromedriver, like this:
```javascript
var webdriverio = require('webdriverio');
var options = {
    host: "localhost",
    port: 9515,
    desiredCapabilities: {
            browserName: 'chrome',
            chromeOptions: {binary: 'C:/Users/lemoussel/OneDrive/Electron/Drivium_io/electron-v0.30.4-win32-ia32/electron.exe'},
        }
};

webdriverio
    .remote(options)
    .init()
    .url('http://www.google.com')
    .title(function(err, res) {
        console.log('Title was: ' + res.value);
    })
    .end();
```
 Just works as expected.. So Gooood :)

**Comment by christian-bromann** [comment]
@LeMoussel glad that it is working now .. whooop whooop

**Comment by LeMoussel** [comment]
Updated documentation on [Setting up Electron with WebdriverIO](https://github.com/atom/electron/blob/master/docs/tutorial/using-selenium-and-webdriver.md)

**Comment by christian-bromann** [comment]
Awesome thanks! :+1:

**Comment by bushev** [comment]
Guys, what a way to bind webdriverio to my Electron application, not to the Google page?

**Comment by mduqueoviedo** [comment]
@bushev I was looking at the same than you, and only found it after a lot of digging:

```
import electron from 'electron';
const driver = new webdriver.Builder()
// The "9515" is the port opened by chrome driver.
  .usingServer('http://localhost:9515')
  .withCapabilities({
    chromeOptions: {
      binary: electron,
      args: [`app=${path.join(__dirname, '../..')}`] // This path is the one you define in your start script
    }
  })
  .forBrowser('electron')
  .build();
```

**Comment by christian-bromann** [comment]
@mduqueoviedo what you use is selenium-webdriver not WebdriverIO

**Comment by mduqueoviedo** [comment]
My bad, you are right. In any case I think the `args` part can be set up very similarly for both systems.

**Comment by alehander92** [comment]
thank you @mduqueoviedo : this was almost working for me, but for me `goog:chromeOptions` worked with `webdriver` from `npm i webdriver`, not `chromeOptions`
