### ISSUE TITLE
await doesn't work in async cucumber step

### ISSUE THREAD

**Issue by lacell75** [webdriverio/webdriverio#7210]
[*Environment (please complete the following information):**
 - **WebdriverIO version:** 7.9.0
 - **Mode:** WDIO
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 14.16
 - **NPM version:** 6.14.11
 - **Browser name and version:** Any
 - **Platform name and version:**  Windows 10
 - **Additional wdio packages used (if applicable):** "@wdio/cli": "^7.9.0",
    "@wdio/cucumber-framework": "^7.9.0",
    "@wdio/dot-reporter": "^7.9.0",
    "@wdio/local-runner": "^7.9.0",
    "@wdio/mocha-framework": "^7.9.0",
    "@wdio/spec-reporter": "^7.9.0",
    "@wdio/sync": "^7.9.0",
    "@wdio/allure-reporter": "^7.9.0",
     "expect": "^27.0.6",
    "expect-webdriverio": "^3.1.0",

**Describe the bug**
After upgrade to  7.9.0` (was working in `7.8.0`), Await doesn't work in async step definition from cucumber

**To Reproduce**
Sample feature file:

```
Feature: Execute test with an async step

  Scenario: async step
    Given test async function

```
code snippet:
```

import { Given } from '@cucumber/cucumber';

Given('test async function', async () => {
  const start = Date.now();
  await browser.pause(15000);
  const end = Date.now() - start;
  console.log(`Nb of miliseconds: ${end}`);
});


```

**Expected behavior**
A pause of 15s should be done

**wdio.config file:**
```
specs: ['features/*.feature'],
  framework: 'cucumber',
  cucumberOpts: {
    backtrace: true,
    requireModule: [],
    require: [
      'src/support/*',
      'src/step_definitions/*'
    ],
    dryRun: false,
    failFast: false,
    format: ['pretty'],
    colors: true,
    snippets: true,
    source: true,
    profile: [],
    strict: true,
    tagExpression: ''
    timeout: 30000,
    ignoreUndefinedDefinitions: true
  },
```

**Log**
1 ms is displayed instead of 15000
```
[0-0] >>> [0-0] Nb of milliseconds: 1

```

**Comment by lacell75** [comment]
Bug reproduced in sync and async mode

**Comment by erwinheitzman** [comment]
Just tried to reproduce it with the latest version and works just fine: `[0-0] Nb of miliseconds: 15006`.

Please provide a reproducible example.

**Comment by lacell75** [comment]
Very strange. Did you try to reproduce it in sync mode?


Le ven. 30 juil. 2021 à 18:31, Erwin Heitzman ***@***.***> a
écrit :

**Comment by christian-bromann** [comment]
@lacell75 I also can't reproduce it. Make sure you have `@wdio/sync` installed. Even better would be to switch to async all completely as we have deprecated sync mode. Will close, happy to re-open if a reproducible example can be provided.
