### ISSUE TITLE
Unexpected alert open not catched.

### ISSUE THREAD

**Issue by sean-hill** [webdriverio/webdriverio#722]
Hey there, I'm having a bug where the `client.on('error')` isn't catching this following bug (it's when an unexpected alert box is opened):

	15:43:15.900 WARN - Exception thrown
	org.openqa.selenium.UnhandledAlertException: unexpected alert open
	  (Session info: chrome=41.0.2272.118)
	  (Driver info: chromedriver=2.15.322448 (52179c1b310fec1797c81ea9a20326839860b7d3),platform=Linux 3.13.0-36-generic x86_64) (WARNING: The server did not provide any stacktrace information)
	Command duration or timeout: 3 milliseconds: null
	Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
	System info: host: 'N/A', ip: 'N/A', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-36-generic', java.version: '1.7.0_75'
	Session ID: 93d5f43b3195d438411c0fdc46fa5788
	Driver info: org.openqa.selenium.chrome.ChromeDriver
	Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.84w3Hu}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=41.0.2272.118, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
		at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
		at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:162)
		at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
		at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:622)
		at org.openqa.selenium.remote.RemoteWebDriver.getCurrentUrl(RemoteWebDriver.java:319)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:606)
		at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:101)
		at com.sun.proxy.$Proxy1.getCurrentUrl(Unknown Source)
		at org.openqa.selenium.support.events.EventFiringWebDriver.getCurrentUrl(EventFiringWebDriver.java:164)
		at org.openqa.selenium.remote.server.handler.GetCurrentUrl.call(GetCurrentUrl.java:30)
		at org.openqa.selenium.remote.server.handler.GetCurrentUrl.call(GetCurrentUrl.java:1)
		at java.util.concurrent.FutureTask.run(FutureTask.java:262)
		at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
		at java.lang.Thread.run(Thread.java:745)

	15:43:15.906 WARN - Exception: unexpected alert open
	  (Session info: chrome=41.0.2272.118)
	  (Driver info: chromedriver=2.15.322448 (52179c1b310fec1797c81ea9a20326839860b7d3),platform=Linux 3.13.0-36-generic x86_64) (WARNING: The server did not provide any stacktrace information)
	Command duration or timeout: 3 milliseconds: null
	Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
	System info: host: 'N/A', ip: 'N/A', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-36-generic', java.version: '1.7.0_75'
	Session ID: 93d5f43b3195d438411c0fdc46fa5788
	Driver info: org.openqa.selenium.chrome.ChromeDriver
	Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.84w3Hu}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=41.0.2272.118, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]

	non_object_property_load: Cannot read property 'value' of undefined

	    at screenshot() at /var/www/unbill-integrations/source/node_modules/webdriverio/lib/commands/saveScreenshot.js:30:17
	    at end() at /var/www/unbill-integrations/source/util/biller-auth/biller-scraper.js:75:7

	non_object_property_load: Cannot read property 'value' of undefined

	    at screenshot() at /var/www/unbill-integrations/source/node_modules/webdriverio/lib/commands/saveScreenshot.js:30:17
	    at end() at /var/www/unbill-integrations/source/util/biller-auth/biller-scraper.js:75:7

When this happens, Selenium just stays open and the browser never closes. Just thought I'd report it :)

**Comment by christian-bromann** [comment]
This happens when you try to interact with an element if an alert box is open. Not sure why it doesn't get caught by some command.

**Comment by sean-hill** [comment]
Yeah that makes sense. I'd love for it to be caught though by the `client.on('error')` event, or else my tests just get locked up and don't continue. Thanks!

**Comment by christian-bromann** [comment]
if an unexpected alert pops up it usually is a good indicator that something went wrong with your app :wink:

**Comment by sean-hill** [comment]
:shipit:

**Comment by sweinertjr** [comment]
+1 I’m trying to test a login process. It show an alert if the credentials were invalid, but doesn't show one if the credentials were valid. How can I accept an alert conditionally or check for an alert that may not exist without things blowing up on me?

**Comment by christian-bromann** [comment]
@sweinertjr in this case I would always check for an alert but handle the exception if login fails

```js
browser.alertText().then(function(res ) {
    // throw exception if login was intended to pass
}, function() {
    // throw exception if login was intended to fail
})
```

**Comment by christian-bromann** [comment]
I believe that if an alert pops up that was not expected, your integration test should fail. However right now WebdriverIO provides no handy methods to deal with alert or confirm boxes. This will get tackled in #780 . We should continue the conversation about this topic there. Closing.

**Comment by CTaylor1118** [comment]
@christian-bromann This should be reopened. This exception is still a problem and it looks like #780 did not address this issue.

**Comment by christian-bromann** [comment]
@CTaylor1118 you can always run into this error if you don't handle alerts gracefully. WebdriverIO can not handle unexpected alert pop ups. I you get an unexpected alert your test should fail. Please update to the latest version of WebdriverIO.

**Comment by wcb7007** [comment]
@christian-bromann  So basically you are saying that there is no such thing as an unexpected alert box - is this because you are supposed to know how the screen reacts to all actions that Webdriver performs on it? Even just an alert that may popup somewhere at a random time to click "OK"?  So, the code should be written in a manner that anywhere a alert can be triggered, it should be handled.  That seems to be a very large task, but there is no other way to check, correct?

**Comment by christian-bromann** [comment]
> So, the code should be written in a manner that anywhere a alert can be triggered, it should be handled.

Yes

> That seems to be a very large task

Why? If an alert pops up that is not expected something is wrong and a valid decision to let the test fail. 

> but there is no other way to check, correct?

You can check for an alert after each command but that doesn't seem to be a good solution. So no!

**Comment by monolithed** [comment]
@wcb7007, Here is a possible solution for your problem:

**commands.js**

```js
browser.addCommand('ignoreModalWindows', () => {
    this.execute(function () {
        window.alert = window.confirm = window.prompt = window.onbeforeunload = null;
    });
})l
```

**page.js**

```js
export default  class Page {
  static open (options) {
       for (let [name, value] of Object.entries(options)) {
           if (value) {
              browser[option]();
           }
       }
  }
};
```

**login.js**

```js
import Page from '../pages';

export default class Login extends Page {};
```

**test.js**

```js
import Login from '../pages/login';

it('Test', () => {
     Login.open({ ignoreModalWindows: true });
});
```

**Comment by CTaylor1118** [comment]
Could functionality like the staleElementError handler be added for these unexpected alert errors and allow the user to specify how it is handled if it is encounters (accept, dismiss, confirm)

**Comment by bhabanipattanayak** [comment]
You can ass this if you want to do some action for all the alerts
DesiredCapabilities browser = DesiredCapabilities.firefox(); 
browser.setCapability(CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR, UnexpectedAlertBehaviour.IGNORE);
You can use UnexpectedAlertBehaviour.ACCEPT or UnexpectedAlertBehaviour.DISMISS
Same can be done for other drivers.

**Comment by briandipalma** [comment]
@bhabanipattanayak Is that WebdriverIO or Webdriver Java?
