### ISSUE TITLE
[HELP]DevTools causes page load failure without logging a reason. 

### ISSUE THREAD

**Issue by maleeazeem** [webdriverio/webdriverio#7238]
I am facing an issue while running devtools service to capture performance metrics. After navigating couple of pages when I reach third UI page I get an error of 
**_"Error: Couldn't capture performance due to: Page with url "https://.............com/questions" failed to load"_**
When I dug into the issue I found that in _node_modules/@wdio/devtools-service/build/index.js_ at line number 54 I am getting an error as shown in below image.
<img width="984" alt="Screen Shot 2021-08-08 at 11 07 53 PM" src="https://user-images.githubusercontent.com/50889269/128669810-a5b843d8-b841-4dd8-8fca-2f31a061ec3c.png">

Error message object at line 54 is coming from  _node_modules/@wdio/devtools-service/build/gatherer/trace.js_ file at line 70 as shown in picture below
<img width="907" alt="Screen Shot 2021-08-08 at 11 30 32 PM" src="https://user-images.githubusercontent.com/50889269/128669835-42ab3570-8545-4f6e-bdfe-2264fdc6008a.png">

msgObj Object returns  json as :
_{"frame":{"id":"D268428A05C087D1AA95C00A90B0310B","loaderId":"066363C593D40CC80D6BD26CCBB54FE7","url":"https://survey........./question","domainAndRegistry":"rally-dev.com","securityOrigin":"https://survey.decent-stub.rally-dev.com","mimeType":"text/html","adFrameType":"none","secureContextType":"Secure","crossOriginIsolatedContextType":"NotIsolated","gatedAPIFeatures":[]},"type":"Navigation"}_

With all above information I could not be able to figure it out why I am getting page load error. 
 
In order to get metrics If i comment it out below code in node_modules/@wdio/devtools-service/build/index.js then I can able to retrieve metrics. 
this.traceGatherer.once('tracingError', (err) => {
            const auditor = new auditor_1.default();
            auditor.updateCommands(global.browser, () => {
                throw new Error(`Couldn't capture performance due to: ${err.message}`);
            });
        });

**Is it possible** 
- instead of throwing error, just log an error message and proceed it with test. or
- just ignore the frame load issue and log a warning message or
- log main reason of page loading. 
 
My whole work is stopped at this point. Pleas help me out with this problem. lighthouse on chrome browser returns performance results then why devtools doesn't returns results whether or not page loaded completely or not. 

I am also adding pictures of that specific UI page which is causing a problem but I don't think that cause a problem. 
The page shows some pending call in network
<img width="1680" alt="Screen Shot 2021-08-09 at 12 00 43 AM" src="https://user-images.githubusercontent.com/50889269/128670035-f00c000d-7892-43fc-89ac-5ec852f30c00.png">

<img width="1680" alt="Screen Shot 2021-08-08 at 10 26 18 PM" src="https://user-images.githubusercontent.com/50889269/128668823-0f697177-871a-44a4-9f1d-9065999a5e0c.png">

package.json
    "@wdio/cli": "^6.6.7",
    "@wdio/devtools-service": "6.6.6",
    "@wdio/dot-reporter": "^6.6.6",
    "@wdio/jasmine-framework": "^6.6.6",
    "@wdio/local-runner": "^6.6.7",
    "@wdio/sauce-service": "^6.6.7",
    "@wdio/selenium-standalone-service": "6.6.5",
    "@wdio/shared-store-service": "^6.6.7",
    "@wdio/spec-reporter": "^6.6.8",
    "@wdio/static-server-service": "^6.3.6",

Test
            const runMetrics = (() => {
        browser.pause(2000);
        logger().info(browser.getTitle());
        const metrics = browser.getMetrics();
        logger().info(`Metrics: ${JSON.stringify(metrics)}`);
    });

    it('devtools', () => {
        browser.enablePerformanceAudits();
        browser.url(loginPageUrl);
        runMetrics();

        RallyLoginPage.loginToRallyEngine(username, password);
        runMetrics();

        browser.url('https://................../question');           // at this page I get a page load error
        runMetrics();

        browser.disablePerformanceAudits();
    });

**Comment by christian-bromann** [comment]
This is very much related to issue other issues we have seen and trying to fix as part of #7019.

**Comment by christian-bromann** [comment]
PR got merged and released. Closing.
