### ISSUE TITLE
Capabilities weird behavior with `OnWorkerStart`

### ISSUE THREAD

**Issue by Nouxx** [webdriverio/webdriverio#7249]
**Environment (please complete the following information):**
 - **WebdriverIO version:** "^7.3.0"
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync: "^7.0.8"
 - **Node.js version:** node:14.16-alpine3.10 (Docker)
 - **NPM version:** according to node version
 - **Additional wdio packages used (if applicable):** none

**Config of WebdriverIO**
my full [wdio.conf.js](https://gist.github.com/Nouxx/c4d564e4e627ccf4d6d10fc310b494d3)

**Describe the bug**
I'm trying to edit worker capabilities using the `onWorkerStart` hook (see actual implementation above), in this example, I'm adding 3 capabilities.
```js
    onWorkerStart: function (cid, caps, specs, args, execArgv) {
        var index = devices.findIndex(device => device.available == true)
        const device = devices[index]
        console.log(`device ${device.udid} used by worker ${cid}`)
        caps['appium:udid'] = device.udid
        caps['appium:systemPort'] = device.systemPort
        caps['appium:platformVersion'] = device.platformVersion
        console.log(caps)
        devices[index].available = false
    },
```
I'm launching 2 workers (`maxInstances` is set to `2`) and each worker should have different 3 capabilites (udid, systemPort...)
The onWorkerStart log output are correct (for worker [0-0] and [0-1]), but when requesting the Appium server, the same capabilities are sent.

Full log below

**To Reproduce**

**Expected behavior**
The caps to be overwritten by the one defined in the OnWorkerStart hook, and not the latest one 

**Log**
https://gist.github.com/Nouxx/43f5cb92a3928ba22cb389828a90c13b

**Additional context**
N/A

**Comment by christian-bromann** [comment]
> I'm trying to edit worker capabilities using the `onWorkerStart` hook

We recommend to make these amendments in `beforeSession`. Capabilities within the `onWorkerStart` can't be modified. Let me know if this works for you. Happy to re-open if not.
