### ISSUE TITLE
Wrong touchAction typescript return type

### ISSUE THREAD

**Issue by vitalyiegorov** [webdriverio/webdriverio#7250]
**Environment:**
 - **WebdriverIO version:** 7.9.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 16.1.0
 - **NPM version:** 7.11.2

**Describe the bug**
Typescript return type of element and browser `touchAction` should return `Promise<void>` instead of `void`

https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/element/touchAction.ts
https://github.com/webdriverio/webdriverio/blob/v7.9.1/packages/webdriverio/src/commands/browser/touchAction.ts

**To Reproduce**
Install `webdriverio` and try to call `await browser.touchAction(...)`

**Expected behavior**
No TS error

**Comment by christian-bromann** [comment]
Make sure you set `webdriverio/sync` in your `tsconfig.json`:

```json
{
    "compilerOptions": {
        "types": ["node", "webdriverio/sync"]
    }
}
```

Read more about this on the [docs](https://webdriver.io/docs/typescript#framework-setup).
