### ISSUE TITLE
High Thread Usage, consume a large amount of resource during test execution when running in parallel

### ISSUE THREAD

**Issue by wbigno** [webdriverio/webdriverio#7251]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.4
 - **Mode:**  WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** aysnc
 - **Node.js version:** 12.18.0
 - **NPM version:**6.14.4 - **Browser name and version:** Chrome Latest
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):**  @wdio/spec reporter, allure, junit, sauce, image comparision

**Config of WebdriverIO**
```js
const defaultWindowsBrowserSauceOptions = {
  build: `WebdriverIO-V6 build-${new Date().getTime()}`,
  screenResolution: '2560x1600',
  seleniumVersion: '3.141.59',
};

const defaultMacBrowserSauceOptions = {
  build: `WebdriverIO-V6 build-${new Date().getTime()}`,
  screenResolution: '2360x1770',
  seleniumVersion: '3.141.59',
};
const chromeOptions = {
  'goog:chromeOptions': {
    'w3c': true,
    prefs: {
      'download.default_directory': "C:\\Users\\Administrator\\Downloads", 
      'download.prompt_for_download': false,
      'safebrowsing.enabled': true
    }
  },
};


// Max time for single test case execution
let timeout = process.env.DEBUG ? 99999999 : 500000;
let elementTimeout = 10000;


// override the wdio with sauce conf
const sauceConfig = Object.assign(baseConfig, {

  protocol: 'http',
  user: sauce.user,
  key: sauce.key,
  logLevel: 'trace',
  maxInstances: 20,
  region: 'us',
  //
  // Test runner services
  // Services take over a specific job you don't want to take care of. They enhance
  // your test setup with almost no effort. Unlike plugins, they don't add new
  // commands. Instead, they hook themselves up into the test process.
  services: [
    ['sauce', {
      sauceConnect: false,
      sauceConnectOpts: {
      },
      setJobNameInBeforeSuite: true,
    }],
    ['image-comparison', {
      baselineFolder: join(process.cwd(), 'visual-regression/'),
      formatImageName: process.env.DOMAIN + '--{browserName}--{browserVersion}-{tag}',
      screenshotPath: join(process.cwd(), '.tmp/'),
      misMatchTolerance: 0.02,
      savePerInstance: true,
      autoSaveBaseline: true,
      blockOutStatusBar: true,
      blockOutToolBar: true,
    }],
  ],
  // If you have trouble getting all important capabilities together, check out the
  // Sauce Labs platform configurator - a great tool to configure your capabilities:
  // https://docs.saucelabs.com/reference/platforms-configurator
  //
  capabilities: [
    // maxInstances can get overwritten per capability. So if you have an in-house Selenium
    // grid with only 5 firefox instances available you can make sure that not more than
    // 5 instances get started at a time.
    { 'maxInstances': 20, 'browserName': 'googlechrome', 'platformName': 'Windows 10', 'browserVersion': 'latest',
      'sauce:options': {
        ...defaultWindowsBrowserSauceOptions,
      },
      ...chromeOptions,
    },
    // { 'maxInstances': 40, 'browserName': 'googlechrome', 'platformName': 'Windows 10', 'browserVersion': 'latest-1',
    //   'sauce:options': {
    //     ...defaultWindowsBrowserSauceOptions,
    //   },
    //   ...chromeOptions,
    // },
    // { 'maxInstances': 20, 'browserName': 'chrome', 'platformName': 'macOS 10.15', 'browserVersion': 'latest',
    //   'sauce:options': {
    //     ...defaultMacBrowserSauceOptions,
    //   },
    // },
    // { 'maxInstances': 20, 'browserName': 'chrome', 'platformName': 'macOS 10.15', 'browserVersion': 'latest-1',
    //   'sauce:options': {
    //     ...defaultMacBrowserSauceOptions,
    //   },
    // },
  ],

  // afterHook: function (test, context, { error, result, duration, passed, retries }) {
  // },
  /**
  * Function to be executed after a test (in Mocha/Jasmine).
  */
  afterTest:
  function(test, context, { error, result, duration, passed, retries }) {
    if (error !== undefined) {
      try {
        utilities.takeScreenshot(process.env.DOMAIN +'--'+ browser.capabilities.browserName +'--'+ test.title, true);
      } catch {
        console.log('>> Capture Screenshot Failed!');
      }
    }
  },
  function() {
    driver.executeScript('sauce:job-result=' + (this.currentTest.state));
    driver.quit();
  },
});

exports.config = sauceConfig;
```
**Describe the bug**
We have our maxINsatnce set to 20, but when out test suite contains 300+ spec files, we see 300+ threads consumed during the test. We would expect that once a test is executed that thread would be released. What we are seeing though is the opposite that the test runner is opening a new thread for every test which in the case of 300+ spec files consumes a massive amount of resources.

**To Reproduce**
Execute a test suite on Sauce labs or other service, with Max Instances set to 20, and with 100+ spec files in the suite. You will see the log output shows that the number of threads in use is not limited to the 20 maxInstance, but rather the number of spec files.

[Include code or an example repository that can easily be set up]

**Expected behavior**
Would expect the thread count to mirror the maxInstance

**Log**
example, over 293 threads used up on this test run with just over 300 spec files in this suite
```
[0-265] PASSED in googlechrome - /test/specs/nylim/component/test/top-sectors-etf-functional.spec.js
[0-287] FAILED in googlechrome - /test/specs/nylim/component/test/infographic-image-dynamic-media.spec.js
[0-267] PASSED in googlechrome - /test/specs/nylim/component/test/top-sectors-mf-functional.spec.js
[0-286] AssertionError in "Image Dynamic Media Large should be the correct size Large for Med viewport"
expected { width: 961, height: 278 } to deeply equal { width: 960, height: 278 }
[0-286] FAILED in googlechrome - /test/specs/nylim/component/test/image-dynamic-media.spec.js
[0-293] AssertionError in "TimeLine, Dynamic Media Extra Small Narrow TimeLine Dynamic Media Large should be the correct size Large for Med viewport"
expected { width: 961, height: 278 } to deeply equal { width: 960, height: 278 }
[0-293] FAILED in googlechrome - /test/specs/nylim/component/test/time-line-dynamic-media.spec.js
[0-246] PASSED in googlechrome - /test/specs/nylim/component/test/statistics-mf-left-table-funds-data-functional.spec.js
[0-245] PASSED in googlechrome - /test/specs/nylim/component/test/statistics-mf-left-table-benchmark-data-functional.spec.js
```
**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
> example, over 293 threads used up on this test run with just over 300 spec files in this suite

The worker id number continue to increase even though older worker shut down. Just because you see the log line being prefixed with `[0-293]` it doesn't mean there 293 workers active. I just tested it and everything works as expected.

**Comment by wbigno** [comment]
Christian

I’m being informed by my server team that when our run is happening the resources container to grow and the last half of the run they are seeing 100% of all resources consumed so on their end this seems to not be the case and the threads seem to be holding some resources open. 

Can you help explain that?

Thanks.

**Comment by wbigno** [comment]
Christian, Also there are 334 spec files in this suite, so why only 293 workers? shouldn't we see a 1 to 1 relationship based on your comment?

**Comment by christian-bromann** [comment]
> Can you help explain that?

I can't as I am not sure what your setup is. What I know is that when I setup a WebdriverIO test suite with one capability and 10 spec files and I have `maxInstances` set to `5` I only have 5 parallel sessions running. I am not sure which resources could stay around.

> shouldn't we see a 1 to 1 relationship based on your comment?

Depends 😉  there might be spec files that are being skipped and therefor don't count in there.

**Comment by wbigno** [comment]
Thanks for the quick response. 

So your test only looked to confirm that the number of browsers open match the maxInstance, and there was no measurement of the resources on the system being consumed? I would also agree I don’t see any issues with the number of browsers opening. 

The issues I am seeing is with large test suites, the amount of resources exponential increase as the execution runs. I think your small sample would not be able to validate anything except that the browsers did not exceed the config setting. But this does not translate into system resources. 

I am seeing a much larger issue here that I feel should warrant some more review before just closing out this ticket as if there is a memory/resource issues with your wdio test runner where large test runs continue to consume more and more resources this becomes a very real issues on an enterprise level for many of us. 

Thanks for your consideration in expanding your review more into this issues.

**Comment by BorisOsipov** [comment]
>The issues I am seeing is with large test suites, the amount of resources exponential increase as the execution runs.

1) Will be nice to see grafana dashboard screens how it looks like from test execution start to finish time. I mean charts with cpu\mem consumption.
2) Can you investigate what processes are culprits in resource consuptions? Especially at the end of "exponential increase"

**Comment by christian-bromann** [comment]
> I am seeing a much larger issue here that I feel should warrant some more review before just closing out this ticket as if there is a memory/resource issues with your wdio test runner where large test runs continue to consume more and more resources this becomes a very real issues on an enterprise level for many of us.

I totally agree with you that running a lot of tests in parallel definitely takes a hit on CPU/memory of your machine. Every worker loads a Node.js environment and loads tons of objects into memory. We are always interesting improving the performance of our testrunner but it requires having some concrete approaches and suggestions to it. This ticket currently only states that running a lot of tests in parallel consumes a lot of CPU/memory which is no news to us. As long as no concrete culprit is identify I see no value keeping the ticket around unless you want to help us investigate the issue.

**Comment by wbigno** [comment]
Boris

Sorry for the delay, the server team was able to provide these details, but they do not have access to grafana on the server. 


Row
fullcmd
command
login
nproc
totcpu
pctcpu
rss
1
<Multi>
<Multi>
cy_JENKINS
13
1.12
0.47
1649220
2
/prod/sys/ws/node-v10.16.3-linux-x64/bin/node /prod/sys/ws/workspace/Martech/A
node
cy_JENKINS
1
19.44
8.13
677488
3
/prod/sys/ws/node-v10.16.3-linux-x64/bin/node /prod/sys/ws/workspace/Martech/A
node
cy_JENKINS
1
14.09
5.89
672712
4
/prod/sys/ws/node-v10.16.3-linux-x64/bin/node /prod/sys/ws/workspace/Martech/A
node
cy_JENKINS
1
21.04
8.8
668684
5
/prod/sys/ws/node-v10.16.3-linux-x64/bin/node /prod/sys/ws/workspace/Martech/A
node
cy_JENKINS
1
10.55
4.41
660772
6
/prod/sys/ws/node-v10.16.3-linux-x64/bin/node /prod/sys/ws/workspace/Martech/A
node
cy_JENKINS
1
9.59
4.01
651696
7
/prod/sys/ws/node-v10.16.3-linux-x64/bin/node /prod/sys/ws/workspace/Martech/A
node
cy_JENKINS
1
14.58
6.1
489944
8
<Multi>
<Multi>
root
278
1.24
0.52
362004
9
/prod/sys/ws/node-v10.16.3-linux-x64/bin/node /prod/sys/ws/workspace/Martech/A
node
cy_JENKINS
1
1.5
0.63
183280
10
/prod/sys/ws/node-v10.16.3-linux-x64/bin/node /prod/sys/ws/workspace/Martech/A
node
cy_JENKINS
1
2.49
1.04
183200
11
/prod/sys/ws/node-v10.16.3-linux-x64/bin/node /prod/sys/ws/workspace/Martech/A
node
cy_JENKINS
1
2.51
1.05
183092
12
/prod/sys/ws/node-v10.16.3-linux-x64/bin/node /prod/sys/ws/workspace/Martech/A
node
cy_JENKINS
1
1.8
0.75
182844
13
/prod/sys/ws/node-v10.16.3-linux-x64/bin/node /prod/sys/ws/workspace/Martech/A
node
cy_JENKINS
1
1.59
0.67
175432
14
/prod/sys/ws/node-v10.16.3-linux-x64/bin/node /prod/sys/ws/workspace/Martech/A
node
cy_JENKINS
1
1.91
0.8
172516
15
/prod/sys/ws/node-v10.16.3-linux-x64/bin/node /prod/sys/ws/workspace/Martech/A
node
cy_JENKINS
1
1.84
0.77
167604
16
/prod/sys/ws/node-v10.16.3-linux-x64/bin/node /prod/sys/ws/workspace/Martech/A
node
cy_JENKINS
1
2.41
1.01
164280
17
/prod/sys/ws/node-v10.16.3-linux-x64/bin/node /prod/sys/ws/workspace/Martech/A
node
cy_JENKINS
1
1.79
0.75
148492
18
/prod/sys/ws/node-v10.16.3-linux-x64/bin/node /prod/sys/ws/workspace/Martech/A
node
cy_JENKINS
1
1.32
0.55
141276
19
/prod/sys/ws/node-v10.16.3-linux-x64/bin/node /prod/sys/ws/workspace/Martech/A
node
cy_JENKINS
1
0.85
0.36
141024
20
/prod/sys/ws/node-v10.16.3-linux-x64/bin/node /prod/sys/ws/workspace/Martech/A
node
cy_JENKINS
1
1.74
0.73
140924
21
/prod/sys/ws/node-v10.16.3-linux-x64/bin/node /prod/sys/ws/workspace/Martech/A
node
cy_JENKINS
1
0.6
0.25
140524
22
/prod/sys/ws/node-v10.16.3-linux-x64/bin/node /prod/sys/ws/workspace/Martech/A
node
cy_JENKINS
1
0.95
0.4
139852
23
/prod/sys/ws/node-v10.16.3-linux-x64/bin/node /prod/sys/ws/workspace/Martech/A
node
cy_JENKINS
1
0.65
0.27
139644
24
/prod/sys/ws/node-v10.16.3-linux-x64/bin/node /prod/sys/ws/workspace/Martech/A
node
cy_JENKINS
1
0.95
0.4
138260
25
/prod/sys/ws/node-v10.16.3-linux-x64/bin/node /prod/sys/ws/workspace/Martech/A
node
cy_JENKINS
1
0.55
0.23
136968
26
/prod/sys/ws/node-v10.16.3-linux-x64/bin/node /prod/sys/ws/workspace/Martech/A
node
cy_JENKINS
1
0.92
0.38
133960
27
/prod/sys/ws/node-v10.16.3-linux-x64/bin/node /prod/sys/ws/workspace/Martech/A
node
cy_JENKINS
1
1.76
0.74
133192
28
/prod/sys/ws/node-v10.16.3-linux-x64/bin/node /prod/sys/ws/workspace/Martech/A
node
cy_JENKINS
1
0.68
0.28
131208
29
/prod/sys/ws/node-v10.16.3-linux-x64/bin/node /prod/sys/ws/workspace/Martech/A
node
cy_JENKINS
1
1.14
0.48
128364
30
<Multi>
<Multi>
tq
10
0.05
0.02
21048
31
<Multi>
<Multi>
postfix
2
0
0
4868
32
<Multi>
<Multi>
esmbpm
2
0.01
0
4676
33
/usr/lib/polkit-1/polkitd --no-debug
polkitd
polkitd
1
0
0
1312
34
/usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --system
dbus-daemon
dbus
1
0
0
1188
35
/usr/sbin/ntpd -u ntp:ntp -u ntp:ntp
ntpd
ntp
1
0
0
816
36
/sbin/rpcbind -w
rpcbind
rpc
1
0
0
408
37
<Other>
<Other>
<N/A>
1
34.3
14.35
<N/A>
 
These are the resources running when we see the spike occurring. 

Thanks
Will

**Comment by BorisOsipov** [comment]
@wbigno it is absolutly unreadable a bunch of text. Please pay attention what do you send - email <-> github integration is not ideal sometimes.

If I formated this output it doesn't look like resource overload:
![image](https://user-images.githubusercontent.com/6514276/129360424-2808f6e9-d4ce-4809-806d-90d16fafc108.png)

`pctcpu` seems is "the average cpu used by the process since its startup" and it is low for all node processes.
