### ISSUE TITLE
WDIO click() command doesn't resolve and test execution hangs upon click on a web element.

### ISSUE THREAD

**Issue by Hayk-S** [webdriverio/webdriverio#7259]
- **WebdriverIO version:** [7.7.5]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [async]
 - **Node.js version:** [14.16.0]
 - **NPM version:** [7.12.1]
 - **Browser name and version:** [Chrome 92]
 - **Platform name and version:** [macOS Big Sur 11.4]
 - **Additional wdio packages used (if applicable):** [@wdio/spec reporter, @wdio/shared-store-service, @wdio/devtools-service, @wdio/mocha-framework]

**Describe the bug**

`click()` command is not resolving which causes the test execution to hang and the browser hangs on an infinite loading state. 

**To Reproduce**
1. Navigate to `https://www.postman.com/product/api-client/`
2. Open `Product` dropdown from page Header
3. Select option e.g. (API Platform)
4. Check that test successfully executes and finishes

**Expected behavior**
After performing `click` on the target dropdown option the page should load and test execution should be finished.

**Additional context**
The issue may be related to `devtools` service.

**Comment by christian-bromann** [comment]
@Hayk-S can you provide a reproducible example?

**Comment by Hayk-S** [comment]
@christian-bromann I have described the steps in the description. Apart from that nothing is needed to reproduce the issue no prior steps or additional setup is needed.

**Comment by BorisOsipov** [comment]
@Hayk-S it will be easier to reproduce if you provide **code** that reproduces the issue rather than just steps.

**Comment by christian-bromann** [comment]
+1 on what @BorisOsipov says, there is no guarantee that we will automate your step description the same way you have it.

**Comment by Hayk-S** [comment]
Ok here is the reproducible example

https://github.com/Hayk-S/WDIO-reproducible-example

Run the test by `npx wdio run ./wdio.conf.js --spec example.e2e.js`

Note that as soon as I remove the `devtools` from services in `wdio.config.js` it works.

**Comment by BorisOsipov** [comment]
@Hayk-S thank you for the reproducible example.

Now it is clear what is happened.

It is not wdio issue.
After click the page isnt loaded completely due some requests to "http://nr-data.net/*" urls that never completes. Seems it is "https://www.postman.com" site issue.

you can apply workaround like:   
```
        await browser.setTimeout({ 'pageLoad': 10000 })
        await browser.url(`https://www.postman.com/home`)
```

It fixes the issue for me.
