### ISSUE TITLE
getText() is returning nothing but getHTML() shows the text is present

### ISSUE THREAD

**Issue by philipobrien** [webdriverio/webdriverio#726]
I'm using Meteor and Cucumber and I'm testing the presence of this link

```html
<li><a href="/prediction" class="test">Prediction</a></li>
```

my step definition is

```js
this.client.
                waitForExist('.navbar-fixed').
                waitForExist('a.test').
                getText('a.test').should.become("Prediction").and.notify(callback);
```

which returns the following error

```console
AssertionError: expected '' to deeply equal 'Prediction'
```

but when I change the step definition to this

```js
this.client.
                waitForExist('.navbar-fixed').
                waitForExist('a.test').
                getHTML('a.test').should.become("Prediction").and.notify(callback);
```

I can see that the text is definitely present

```console
AssertionError: expected '<a href="/prediction" class="test">Prediction</a>' to deeply equal 'Prediction'
```

**Comment by christian-bromann** [comment]
ha, that's weird. Do you have an reproducible example (html file + webdriverio script)? Also could you provide Selenium and WebdriverIO logs? Are there more elements with the class test on that page (probably not)?

**Comment by philipobrien** [comment]
I just renamed the class to be sure there was no clashes but it didn't help. Meteor doesn't seem to be providing any logs other than the Cucumber log which doesn't contain anything useful other than the `AssertionError` above.

**Comment by christian-bromann** [comment]
Could you try to do a `pause(5000)` to be sure that is not some race condition?

**Comment by philipobrien** [comment]
Like this

```js
waitForExist('.navbar-fixed').
                waitForExist('a.test').
                pause(5000).
                getText('a.test').should.become("Prediction").and.notify(callback);
```

This didn't fix it

**Comment by christian-bromann** [comment]
Interesting. I've seen that problem in some other issue too and I am wondering why Selenium is acting weird here. In order to move forward use this for your assertion:

```js
this.client.
                waitForExist('.navbar-fixed').
                waitForExist('a.test').
                getHTML('a.test', false).should.become("Prediction").and.notify(callback);
```

It requires some investigation to solve this. I queued it up.

**Comment by philipobrien** [comment]
That works for me :thumbsup:

**Comment by drets** [comment]
Tried to reproduce the issue and everything went smoothly.
@philipobrien, could you provide a dump of the html file where the issue was spotted (as asked in https://github.com/webdriverio/webdriverio/issues/726#issuecomment-133047060)?

**Comment by cobbdb** [comment]
getText() is bugging out for me too:
 . console out: http://dpaste.com/1J66EK2
 . webdriver script: http://dpaste.com/00EM64N
 . html in page: http://dpaste.com/3NNANWD

I have queried with jquery and the value is definitely there, but getText() returns empty. I have updated tests to use getHTML() as a workaround which has solved the problem of failed tests.

Just to be super clear - I'm saying that everything else left the same, getText() returns empty, but getHTML() returns the correct value.

Side note, just started rolling over some of our ui tests to wdio and loving it so far!

**Comment by drets** [comment]
The element is **not** visible that's why `getText` returns empty string:
* [Selenium FAQ](https://code.google.com/p/selenium/wiki/FrequentlyAskedQuestions#Q:_Why_is_it_not_possible_to_interact_with_hidden_elements?)
* [WebDriver spec](http://www.w3.org/TR/webdriver/#interactable)

**Comment by christian-bromann** [comment]
@drets thanks, double checked that and it is true. I added a note to the getText docs to make people aware of that.
