### ISSUE TITLE
wdio/log has truncated statements and is out of time order

### ISSUE THREAD

**Issue by beeman88** [webdriverio/webdriverio#7260]
Hi:

Using these version of wdio

 "@wdio/allure-reporter": "^6.11.0",
 "@wdio/cli": "^6.12.1",
 "@wdio/jasmine-framework": "^6.11.0",
 "@wdio/local-runner": "^6.12.1",
 "@wdio/logger": "^6.10.10",
 "@wdio/sauce-service": "^6.12.1",
 "@wdio/selenium-standalone-service": "^6.12.1",
 "@wdio/spec-reporter": "^6.11.0",
 "@wdio/sync": "^6.11.0",
 "jasmine-expect": "3.8.4",
 "webdriverio": "^6.12.1"
        
 The wdio.log is
      
2021-08-10T16:26:21.088Z INFO @wdio/local-runner: Start worker 0-0 wi2021-08-10T16:26:21.075Z INFO @wdio/cli:launcher: Run onWorkerSt2021-08-12021-08-10T16:26:26.941Z INFO @wdio/cli:launcher: Run onComplete hook
t code 1
2021-08-10T16:26:31.108Z INFO @wdio/local-runner: Shutting down spawned worker
2021-08-10T16:26:31.364Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully

We parse the log for Exit Code 1 to find failing tests but the log statements are truncated and out of order.  
Any advice or help?
Thanks
Bryan

**Comment by christian-bromann** [comment]
> We parse the log for Exit Code 1 to find failing tests

Why don't you use the `after` hook to check if a worker is passing or failing?

> but the log statements are truncated and out of order.

Not sure what is truncated in the example above, also there is no guarantee that log messages are in any particular order.

I will close this issue as I think there are workarounds to and this doesn't display like an actual bug. Happy to continue to help with your configuration though.
