### ISSUE TITLE
Run specs on existing browser instance

### ISSUE THREAD

**Issue by Ramanth** [webdriverio/webdriverio#7269]
**Is your feature request related to a problem? Please describe.**
I need the browser instance not to be closed and i can trigger next spec execution on the same instance and this capability will help me automate pieces of my workflows and decide to execute them in an order dynamically.

**Describe the solution you'd like**
Suggestion : have option to launch a browser and have a session associated with it and may be we can have configuration options, such that we can input the session-id and it runs the spec on the existing browser with that session-id

**Describe alternatives you've considered**
selenium webdriver has a similar concept where we can launch a chromedriver on a port and give the capabilities to connect to it. Not sure if we have similar in webdriverio

**Additional context**
This will make it more flexible in terms of automating smaller modules and executing them as desired flow

**Comment by christian-bromann** [comment]
@Ramanth can you elaborate on this? How is the user suppose to decide which spec to run next?

**Comment by christian-bromann** [comment]
Closing due inactivity.
