### ISSUE TITLE
setInput("Backspace") no longer functioning

### ISSUE THREAD

**Issue by pieceOpiland** [webdriverio/webdriverio#7271]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.9.1
 - **Mode:** Standalone mode 
 - **Node.js version:** v12.18.3
 - **NPM version:** 7.8.0
 - **Browser name and version:** Chrome 92.0.4515.131
 - **Platform name and version:** MacOS 11.5.2

**Config of WebdriverIO**
It's standalone, so I don't believe this is needed?

**Describe the bug**
When trying to run `setInput("Backspace")` on an element, WebdriverIO logs: `Unknown key: "Back space"`

**To Reproduce**
I've created a [script in this gist](https://gist.github.com/pieceOpiland/17433e79a0416fd8d947ded3c765393a) to replicate it. Install webdriverio along side it and run the script.

**Expected behavior**
I expect the "erroneous" 'a' character to be deleted from the selected input.

**Log**
The full log can be found at [this gist](https://gist.github.com/pieceOpiland/e3d24ab27faa4587894c3ef0dcb92107).

**Additional context**
I presume it may be related to these changes: https://github.com/webdriverio/webdriverio/pull/6661? I went up the call stack in the error, and it seems like the unicode backspace character is being translated to "Back space" in the changes in `elementSendKeys.ts`

**Comment by christian-bromann** [comment]
PR with a patch was merged, a release with the fix will be prepared.
