### ISSUE TITLE
Error time out exceeds

### ISSUE THREAD

**Issue by RollerIn** [webdriverio/webdriverio#7275]
Error: Timeout of 10000ms exceeded. The execution in the test "My Login application "before each" hook for "Moving pages"" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). 

here am automation mobile browser  on android using mocha and WebdriverIO, after launching the application ,before loading application completely ….its closing with the above error.

can you suggest me to fix this issue?

**Comment by christian-bromann** [comment]
> can you suggest me to fix this issue?

The error message already provides a solution: increase the timeout for the test specs.
