### ISSUE TITLE
how to execute webdriverIO scripts on phantomjs

### ISSUE THREAD

**Issue by amiya-pattnaik** [webdriverio/webdriverio#728]
Hi,
In our project we are using Jasmine-Node and webdriver IO. We want to run our script in headless mode using phantomjs. How we can execute our existing webdriver script on phantomjs using jasmine-node.
Please help us..

currently to execute our script we are using below command

jasmine-node sampleFile.spec

Thanks,
Amiya

**Comment by christian-bromann** [comment]
Set `phantomjs` as browser name like in https://github.com/webdriverio/webdriverio/blob/master/examples/webdriverio.with.jasmine.spec.js

**Comment by amiya-pattnaik** [comment]
Thanks Chris for your quick reply.
One more question. Should we require to install phantomjs globally through NPM? or it will take automatically like Safari, FireFox/chrome?

**Comment by christian-bromann** [comment]
I would install it globally

**Comment by amiya-pattnaik** [comment]
Thanks a lot for your input. We will try and will update you accordingly.
