### ISSUE TITLE
Configuration typings incorrect for capabilities "goog:chromeOptions"

### ISSUE THREAD

**Issue by waynevanson** [webdriverio/webdriverio#7284]
**Environment (please complete the following information):**
 - **WebdriverIO version:**  "^7.9.1"
 - **Mode:** Standalone 
 - **If WDIO Testrunner, running sync/async:** N/A
 - **Node.js version:** 14.7.3
 - **NPM version:** 6.14.14
 - **Browser name and version:** N/A
 - **Platform name and version:** MacOS and not sure (new laptop)
 - **Additional wdio packages used (if applicable):**N/A

**Config of WebdriverIO**

```ts
import { RemoteOptions, remote } from "webdriverio";

const configuration: RemoteOptions = {
  capabilities: {
    
    // Type 'string' is not assignable to type 'WebdriverIO'.ts(2322)
    // (property) Capabilities.browserName?: string | undefined
    browserName: "chrome",
    
    // Property 'capabilities' is missing in type '{ headless: true; }' but required in type 'WebdriverIO'.ts(2741)
    // Options.d.ts(251, 5): 'capabilities' is declared here.
    // (property) VendorExtensions['goog:chromeOptions']?: ChromeOptions | undefined
    "goog:chromeOptions": {
        headless: true,
    }
  }
}

const browser = remote(configuration) 
```

**Describe the bug**
In Capabilities, it runs the following correctly but incorrectly throws and error during the type checking phase (typescript)

The above configuration is valid.

**To Reproduce**

type config into an IDE with TS support

**Expected behavior**
No compile time errors in this case.

**Log**
Mentioned in config

**Comment by christian-bromann** [comment]
Thanks for reporting the issue. Your typings are correct however, `capabilities` are not specified in your example. It accepts a raw W3C object as well as normal caps and multiremote caps. For your example the following example would work:

```ts
import { RemoteOptions, remote } from "webdriverio";
import type { Capabilities } from '@wdio/types'

const configuration: RemoteOptions = {
  hostname: 'foo',
  capabilities: {
    // Type 'string' is not assignable to type 'WebdriverIO'.ts(2322)
    // (property) Capabilities.browserName?: string | undefined
    browserName: 'chrome',
    
    // Property 'capabilities' is missing in type '{ headless: true; }' but required in type 'WebdriverIO'.ts(2741)
    // Options.d.ts(251, 5): 'capabilities' is declared here.
    // (property) VendorExtensions['goog:chromeOptions']?: ChromeOptions | undefined
    "goog:chromeOptions": {
        headless: true,
    }
  } as Capabilities.Capabilities
}

const browser = remote(configuration) 
```

I will create a ticket to better document these types within the docs.

**Comment by christian-bromann** [comment]
@waynevanson mind taking a look at the PR? Would you see other places where types could be a bit better explained?

**Comment by waynevanson** [comment]
So adding host name makes it valid? I'll look at it right now.

**Comment by waynevanson** [comment]
It seems okay @christian-bromann, I have nothing to add for the time being.
