### ISSUE TITLE
Unable to create new session with FF/Chrome/Appium: Request failed with status 200 due to Response has empty body

### ISSUE THREAD

**Issue by maidendth** [webdriverio/webdriverio#7285]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.9.1
 - **Mode:** Standalone mode
 - **If WDIO Testrunner, running sync/async:** N/A
 - **Node.js version:** 14.1.0
 - **NPM version:** 7.20.6
 - **Browser name and version:** chrome: 92.0.4515.131, chromedriver 92.0.4515.107, FF 91.0, geckodriver: 0.26.0
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** N/A

**Config of WebdriverIO**
```
;(async () => {
    const browser = await remote({
        port: 4444,
        capabilities: {
            browserName: 'chrome'
        }
    })

```

**Describe the bug**
A simple test to open either a Chrome or Firefox browser on my local PC using the browser drivers (chromedriver/geckodriver) fails with a response has empty body error message (note: did not include the 3 retries output, exactly the same as the first failure):
D:\myprj>node test.js
2021-08-17T02:37:58.303Z INFO webdriver: Initiate new session using the WebDriver protocol
2021-08-17T02:37:58.526Z INFO webdriver: [POST] http://127.0.0.1:4444/session
2021-08-17T02:37:58.528Z INFO webdriver: DATA {
  capabilities: { alwaysMatch: { browserName: 'chrome' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'chrome' }
}
2021-08-17T02:37:59.854Z WARN webdriver: Request failed with status 200 due to Response has empty body
2021-08-17T02:38:03.504Z ERROR webdriver: Error: Response has empty body
    at Object.getErrorFromResponseBody (D:\myprj\node_modules\webdriver\build\utils.js:181:16)
    at NodeJSRequest._request (D:\myprj\node_modules\webdriver\build\request\index.js:157:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.startWebDriverSession (D:\myprj\node_modules\webdriver\build\utils.js:63:20)
    at async Function.newSession (D:\myprj\node_modules\webdriver\build\index.js:58:45)
    at async remote (D:\myprj\node_modules\webdriverio\build\index.js:67:22)
    at async D:\myprj\test.js:19:21
(node:22772) UnhandledPromiseRejectionWarning: Error: Failed to create session.
Make sure to connect to valid hostname:port or the port is not in use.
If you use a grid server
Make sure to add vendor prefix like "goog:", "appium:", "moz:", etc to non W3C capabilities.
See more https://www.w3.org/TR/webdriver/#capabilities
    at Object.startWebDriverSession (D:\myprj\node_modules\webdriver\build\utils.js:68:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Function.newSession (D:\myprj\node_modules\webdriver\build\index.js:58:45)
    at async remote (D:\myprj\node_modules\webdriverio\build\index.js:67:22)
    at async D:\myprj\test.js:19:21
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22772) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22772) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

*A few important notes*
1. My test works perfectly fine when webdriverio uses Puppeteer (when not using the browser drivers).
2. This failure also occurs with Appium.
3. Using a network packet sniffer, I have verified that chromedriver, geckodriver and Appium all send back the proper session response with the proper data in the response -- the response body is not empty as the webdriverio error message indicates. This leads me to believe there is an issue with the latest webdriverio version (if it is a configuration issue on my end I cannot possibly see what that could be).
4. From the browser drivers point of view, the new session request completes with success and it opens the browser as expected.
5. I did a quick test and used Selenium with Appuim with an android phone connected via usb and it works fine.

**To Reproduce**
Here is the full source code I used, copied from the webdriverio website getting starting example with some minor changes. Just run this javascript with the software versions mentioned above (the browser drivers are on port 4444).

```
const { remote } = require('webdriverio');

;(async () => {
   const browser = await remote({
        port: 4444,
        capabilities: {
            browserName: 'chrome'
        }
    })

    await browser.url('https://webdriver.io')

    await browser.pause(5000);

    await browser.deleteSession()
})()


```
**Expected behavior**
Webdriverio should complete the new session request with success, load the specified web page, pause and then delete the session.

**Log**
The main webdriverio log output is above. 

If needed, here is the chromedriver and geckodriver log output showing they completed the new session request with success:

Chromedriver:
[1629167883.497][INFO]: [7a61513da5778801e7041db7adba3f0c] RESPONSE InitSession {
   "capabilities": {
      "acceptInsecureCerts": false,
      "browserName": "chrome",
      "browserVersion": "92.0.4515.131",
      "chrome": {
         "chromedriverVersion": "92.0.4515.107 (87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634})",
         "userDataDir": "C:\\Users\\xxxx\\AppData\\Local\\Temp\\scoped_dir24320_2122438286"
      },
      "goog:chromeOptions": {
         "debuggerAddress": "localhost:52957"
      },
      "networkConnectionEnabled": false,
      "pageLoadStrategy": "normal",
      "platformName": "windows",
      "proxy": {

      },
      "setWindowRect": true,
      "strictFileInteractability": false,
      "timeouts": {
         "implicit": 0,
         "pageLoad": 300000,
         "script": 30000
      },
      "unhandledPromptBehavior": "dismiss and notify",
      "webauthn:extension:credBlob": true,
      "webauthn:extension:largeBlob": true,
      "webauthn:virtualAuthenticators": true
   },
   "sessionId": "7a61513da5778801e7041db7adba3f0c"
}

Geckodriver:
1629166960622   webdriver::server       DEBUG   -> POST /session {"capabilities":{"alwaysMatch":{"browserName":"firefox","moz:firefoxOptions":{"args":["-remote-debugging-port","50240"]}},"firstMatch":[{}]},"desiredCapabilities":{"browserName":"firefox","moz:firefoxOptions":{"args":["-remote-debugging-port","50240"]}}}
1629166960634   mozrunner::runner       INFO    Running command: "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe" "-marionette" "-remote-debugging-port" "50240" "-foreground" "-no-remote" "-profile" "C:\\Users\\xxxx\\AppData\\Local\\Temp\\rust_mozprofileKexNKd"
1629166960640   geckodriver::marionette DEBUG   Waiting 60s to connect to browser on 127.0.0.1:50242
1629166966996   geckodriver::marionette DEBUG   Connection to Marionette established on 127.0.0.1:50242.
1629166967038   webdriver::server       DEBUG   <- 200 OK {"value":{"sessionId":"ba642f5a-bcf7-47f4-bda3-0b8f31086ca3","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"91.0","moz:accessibilityChecks":false,"moz:buildID":"20210804193234","moz:debuggerAddress":"localhost:50240","moz:geckodriverVersion":"0.26.0","moz:headless":false,"moz:processID":10884,"moz:profile":"C:\\Users\\xxxx\\AppData\\Local\\Temp\\rust_mozprofileKexNKd","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"windows","platformVersion":"10.0","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"}}}

> Please use the correct markdown

**Comment by christian-bromann** [comment]
If I start a fresh project using `npx wdio ./test` I can't reproduce this. Make sure you don't have anything else running on the same port. Also, can you try to log the response object in `./node_modules/webdriver/build/request/index.js` to see what you actually get back?

**Comment by maidendth** [comment]
I checked the port and it is not in use, the only thing running on this port is the browser drivers (when I unload the browser driver the port is available). 

I enabled the debug logging level (should of done this before) and I get this error message from `./node_modules/webdriver/build/utils.js::isSuccessfulResponse`:  `DEBUG webdriver: request failed due to missing body`

I also added some code in `./node_modules/webdriver/build/request/index.js` right after the session request is sent and the response is received. The response object has a status code of 200 and an empty response body (the response body is null). I attempted to look further into the code to try and figure out where the empty response body is coming from, but I get lost since I don't understand the structure of the code (i.e., where `this._libRequest` ends up going).

**Comment by christian-bromann** [comment]
Can you inspect the response object here: https://github.com/webdriverio/webdriverio/blob/main/packages/webdriver/src/request/index.ts#L169 and past the output here? If this object has `body: null` then the browser driver returns that value. A reproducible example within a repo would be nice.

**Comment by maidendth** [comment]
After trying a bunch of different stuff and having no luck, I decided to upgrade node from version 14.1.0 to 16.7.0 and all of a sudden everything start working. I can now run webdriverio with both Chrome and Firefox. Maybe there is some obscure bug in something that is used in node 14.1.0 by webdriverio.

**Comment by christian-bromann** [comment]
I am not sure how this is related to a specific Node.js version but it might. Glad it is working now.

**Comment by neuged** [comment]
I had the same issue, was also on node 14.1.0 . Upgrading node to 16.7.0 fixed it. Thanks for the tip!
