### ISSUE TITLE
Cucumber step-definitions location is ignored

### ISSUE THREAD

**Issue by nareshbhatia** [webdriverio/webdriverio#729]
- `wdio config` asks for the location of step-definition files, but ignores it completely. In other words, the location is not specified in the generated config file (using `cucumberOpts`).
- Even after specifying the step-definition location as follows, wdio ignores that location at runtime. It assumes that the step definitions are located under the features folder.

```
    cucumberOpts: {
        require: ['./test/step-definitions/**/*.js']
    },
```

**Comment by christian-bromann** [comment]
@nareshbhatia I can't really reproduce this. If you check out the [example wdio.conf](https://github.com/webdriverio/webdriverio/blob/master/examples/wdio.cucumber.conf.js) for cucumber it also specifies the step definition in a random folder and it works. Are you sure the path to your file is right?

**Comment by nareshbhatia** [comment]
@christian-bromann sorry for the confusion. I checked again and only bullet 1 is an issue, bullet 2 is NOT an issue.

Here's my run of the wdio config:
    
    $ wdio config

    =========================
    WDIO Configuration Helper
    =========================

    ? Where do you want to execute your tests? On my local machine
    ? Which framework do you want to use? cucumber
    ? Where are your feature files located? ./features/**/*.feature
    ? Where are your step definitions located? ./step_definitions/**/*.js
    ? Which reporter do you want to use? dot
    ? Level of logging verbosity: silent
    ? In which directory should screenshots gets saved if a command fails? ./errorShots/
    ? What is the base url? http://google.com

    Configuration file was created successfully!
    To run your tests, execute:

        $ wdio wdio.conf.js

This does not produce the following lines in wdio.conf.js:

    cucumberOpts: {
        require: ['./step_definitions/**/*.js']
    },

P.S. When I had originally inserted the above lines in wdio.conf.js manually, I had accidentally misspelled `step_definitions`, hence it was not finding the step definitions. After correcting this, everything worked fine. So bullet 2 is not an issue.

**Comment by christian-bromann** [comment]
Issue 1 got already fixed but is not released yet. I am trying to get a release out as soon as possible
