### ISSUE TITLE
How to make in a synchronous way with yield?

### ISSUE THREAD

**Issue by LeMoussel** [webdriverio/webdriverio#730]
```javascript
webdriverio
    .remote(options)
    .init()
    .url('http://www.google.com')
    .title(function(err, res) {
        console.log('Title was: ' + res.value);
    })
    .end();
```
How can I make this in synchronous way?
I do this 
```javascript
var driver = webdriverio.remote(options)
yield driver.init().url('http://www.google.com')
var title = yield driver.getTitle()
console.log('Title was: ' + res.value)
yield driver.end()
```
But Igot this error 

![2015-08-21_07-54-00](https://cloud.githubusercontent.com/assets/1816573/9402164/f1279800-47d9-11e5-8984-e8edb611c938.png)

**Comment by christian-bromann** [comment]
@LeMoussel you need to use the wdio testrunner together with Mocha or Jasmine. Once you run your specs with wdio and use node >0.11 yield will be supported
