### ISSUE TITLE
Allow Cucumber adapter to publish reports to reports.cucumber.io

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#7300]
Allow Cucumber adapter to publish reports to https://reports.cucumber.io/.
According to the documentation it's a matter of passing a simple `publish` flag to the the `cucumber-js` binary.
And yet currently, passing `publish` as `true` in webdriverIO's config ( `cucumberOpts` ) does not seem to work.

**Comment by christian-bromann** [comment]
Sounds like a neat idea. Any contributions are appreciated.

**Comment by praveendvd** [comment]
> Sounds like a neat idea. Any contributions are appreciated.

Cucumber.js from version 7.3.0.

https://reports.cucumber.io/

But we are using v7.0.0 

@christian-bromann  so should we wait till the cucumber version is updated ?

**Comment by christian-bromann** [comment]
> so should we wait till the cucumber version is updated ?

This can be already done in a separate effort.

**Comment by nextlevelbeard** [comment]
@christian-bromann Correct me if I'm wrong but I suspect that the upgrade to the Cucumber packages is not enough.

Seems like webdriverIO is using the [CucumberRuntime](https://github.com/cucumber/cucumber-js/blob/main/src/runtime/index.ts) instead of directly invoking the CLI.

This way we can only run CucumberJS with the [runtime options](https://github.com/cucumber/cucumber-js/blob/06be59ae3407b5f38bb063b1dd30dea72f110b5c/src/runtime/index.ts#L29) and not the [CLI options](https://github.com/cucumber/cucumber-js/blob/06be59ae3407b5f38bb063b1dd30dea72f110b5c/src/cli/configuration_builder.ts#L19).
This means users can't specify a lot of options including `publish`.

Users are unable to specify formatters like JSON and have to rely on other packages like [wdio-cucumberjs-json-reporter](https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter).

CucumberJS can also respond to environment variables, like the publishing case [here](https://github.com/cucumber/cucumber-js/blob/06be59ae3407b5f38bb063b1dd30dea72f110b5c/src/cli/configuration_builder.ts#L168) but again, only available on the CLI.

They are working on a [programmatic API](https://github.com/cucumber/cucumber-js/issues/1711) but that seems far away.
We should probably consider changing the way we make the call.

[Here's how Serenity does it](https://github.com/serenity-js/serenity-js/blob/11ea0dff0656ef4c7556f0af275810d39c5f6a93/packages/cucumber/src/cli/CucumberCLIAdapter.ts#L119)

**Comment by christian-bromann** [comment]
@nextlevelbeard I think it it something like a rest url where you can push your report to. It is just a matter of looking into the Cucumber.js code and figure that out.

**Comment by praveendvd** [comment]
https://github.com/cucumber/common/blob/main/scripts/publish-cucumber-report

@christian-bromann  this is the bat file that can be used to publish the message , (got by contacting cucumber team ) . It seems we need to pass message.ndjson file .

I am not sure do we generate as part of cucumber framework .  Could you guide me here .

**Comment by christian-bromann** [comment]
We could introduce a cucumberOpts options: `cucumberPublishUrl` and `cucumberPublishToken` and have this as part of the cucumber framework (after the `after` hook is called, so people could amend the report if need be).

**Comment by praveendvd** [comment]
> We could introduce a cucumberOpts options: `cucumberPublishUrl` and `cucumberPublishToken` and have this as part of the cucumber framework (after the `after` hook is called, so people could amend the report if need be).

They are just doing a put to publish url , but I am not sure how to create the message.ndjson report out  . If the final message.ndjson file is there then we can directly upload using rest calls instead of using batch file . Or can use the bat directly .

**Comment by christian-bromann** [comment]
> but I am not sure how to create the message.ndjson report out

Check out one of the links @nextlevelbeard has shared. Once created we can just upload it via Node.js.

**Comment by praveendvd** [comment]
@christian-bromann

**Comment by praveendvd** [comment]
[sampleProject.zip](https://github.com/webdriverio/webdriverio/files/7266982/sampleProject.zip)


Created a sample , project current challenges is cucumber json report creates different json reports for each feature so i am not sure how to consolidate it 

Also cucumber json report hasa dependency if webdriverio CLI which is not updated with the releases of wdio , 

any one who want to  pick this up can refer the sample project , it includes readme on what it does

**Comment by christian-bromann** [comment]
> 1. cucumber json report

Are you referring to https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter ?

> 2\. Cucumber json report has a webdriverio CLI dependecy thats different from the lastest wdio version.

Another option is to make this a reporter feature.

**Comment by christian-bromann** [comment]
@praveendvd do you want to pick this up next?

**Comment by praveendvd** [comment]
> @praveendvd do you want to pick this up next?

I tried and I am not able move forward from what I have suggested . I am not sure depending again on third party library to convert json to cucumber message is a good approach . We should be able to generate cucumber message directly

**Comment by aslakhellesoy** [comment]
> Publish feature seems to be supported only from Cucumber.js from version 7.3.0.

While https://reports.cucumber.io says you need `>= 7.3.0` it's actually been supported since [7.0.0-rc.0](https://github.com/cucumber/cucumber-js/blob/main/CHANGELOG.md#700-rc0---2020-09-14)

> I am not sure how to create the message.ndjson report out

This is done with Cucumber.js' built-in `message` formatter.

**Comment by christian-bromann** [comment]
Thanks @aslakhellesoy for replying. The remaining question is:

> How do we integrate this?

There are various options:

1) create a new reporter or enhance the `wdio-cucumberjs-json-reporter` and upload a report for every worker or
2) create a service that uses `onComplete` to merge all reports into one

I tend to the first option, what do you all think?

**Comment by praveendvd** [comment]
> > Publish feature seems to be supported only from Cucumber.js from version 7.3.0.
> 
> While https://reports.cucumber.io says you need `>= 7.3.0` it's actually been supported since [7.0.0-rc.0](https://github.com/cucumber/cucumber-js/blob/main/CHANGELOG.md#700-rc0---2020-09-14)
> 
> > I am not sure how to create the message.ndjson report out
> 
> This is done with Cucumber.js' built-in `message` formatter.

@aslakhellesoy  Thanks for reply , we are not using cucuberjs cli could we still geenrate the message md

@christian-bromann  , currently the only requirement is for cucumber reporter but in future if other reporters comes up that can use cucumber message directly then we have to twitch the code again. SO having a separate reporter to generate ndjson would be more apt , a future proof approach

**Comment by tamil777selvan** [comment]
Hi, Now that we've switched to use the Cucumber API for running tests, this feature should be working once we update the Cucumber dependency to version 9.5.0. This update is essential to address the issue mentioned [here](https://github.com/cucumber/cucumber-js/issues/2321).

**Comment by nextlevelbeard** [comment]
@tamil777selvan Can confirm this is now working after your work for use of the Cucumber programmatic API.
But not sure we should close this fully due to the fact that currently WDIO publishes a reporter for each worker run.
Which is not ideal.

**Comment by tamil777selvan** [comment]
I agree, @nextlevelbeard. I was experimenting with this to find a workaround, and I managed to succeed by leveraging the capabilities of both the `cucumberMessageReporter` and the `onComplete` hook. Currently, I'm in the process of developing a solution that will expose this functionality as a new function, possibly named `publishReport`, within the framework adapter. This function can then be called within `onComplete` hooks to utilize the solution. If you have any other ideas or thoughts, please feel free to share them.
