### ISSUE TITLE
Appium protocol not detected adequately

### ISSUE THREAD

**Issue by jlipps** [webdriverio/webdriverio#7301]
For example, this set of capabilities:

```
2021-08-18T21:56:24.696Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      'appium:rokuHost': 'localhost',
      'appium:rokuEcpPort': 8060,
      'appium:rokuWebPort': 80,
      'appium:rokuUser': 'rokudev',
      'appium:rokuHeaderHost': '192.168.101.39',
      'appium:keyCooldown': 2000,
      'appium:automationName': 'Roku',
      'appium:platformName': 'Roku'
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    'appium:rokuHost': 'localhost',
    'appium:rokuEcpPort': 8060,
    'appium:rokuWebPort': 80,
    'appium:rokuUser': 'rokudev',
    'appium:rokuHeaderHost': '192.168.101.39',
    'appium:keyCooldown': 2000,
    'appium:automationName': 'Roku',
    'appium:platformName': 'Roku'
  }
}
```

These capabilities should trigger the environment detector to include the Appium protocol, but they don't. Potentially to do with the fact that W3C vendor prefixes are now on the capabilities?

**Comment by christian-bromann** [comment]
@jlipps created a PR to address the issue. However can you provide the session response of the Roku driver. I would prefer to detect the environment based on the session response rather than the requested capabilities.

**Comment by jlipps** [comment]
the roku driver responds with a lot of specific capabilities that I don't think WDIO should know about unless it wants to implement roku specific client side support. rather if we want to look at returned capabilities, i say we should just check for the presence of `automationName` (or `appium:automationName`, but currently appium strips all prefixes internally before responding with caps).
