### ISSUE TITLE
iOS Device on AWS Webdriver Session Timeout

### ISSUE THREAD

**Issue by asanders-tester** [webdriverio/webdriverio#7302]
**Environment (please complete the following information):**
 - **WebdriverIO version:** ^6.10.11
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:**async
 - **Node.js version:** 15.5.1
 - **NPM version:** 7.3.0
 - **Browser name and version:** native app, no browser
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** none
**Config of WebdriverIO**
Not using a wdio config file, session is created inside project globals.js:
`client = await wdio.remote(inputs.device);`
device config:
```
"AWSiOS": {
        "path": "/wd/hub",
        "port": 4723,
        "capabilities": {
            "platformName": "ios"
        }
    }

```
AWS config:
```
module.exports = {
    rootDir: '../../../',
    roots: [
        '<rootDir>/node_modules/test-runner/mobile',
        '<rootDir>/tests'
    ],
    setupFiles: [
        '<rootDir>/node_modules/test-runner/mobile/utils/globals.js',
        '<rootDir>/node_modules/test-runner/api/jest/setup/globals.js'
    ],
    setupFilesAfterEnv: [
        '<rootDir>/node_modules/test-runner/node_modules/jest-extended',
        '<rootDir>node_modules/test-runner/api/jest/setup/init.js'
    ],
    transformIgnorePatterns: [
        '<rootDir>/node_modules/@babel',
        '<rootDir>/node_modules/@jest'
    ],
    clearMocks: true,
    testEnvironment: 'node',
    slowTestThreshold: 200000,
    testTimeout: 300000
};

```
**Describe the bug**
When running a test on an iOS device through AWS Device Farm, the following error occurs:
`2021-08-16T01:17:38.030Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.`
There aren't any issues when running tests on an Android device using the same code (only some minor environment settings).

**To Reproduce**
Run a test on an iOS device through AWS Device Farm using the same wdio settings. I don't have relevant code to provide because I would have to add the entire zipped project which is not allowed by the company I work for.

**Expected behavior**
I expected the session to connect and the test to begin running.

**Log**
If applicable, add logs to help explain your problem.
Device Farm log:
https://gist.github.com/asanders-tester/c020df0caf2e38c93c36a9ea432bdb91
Appium log:
https://gist.github.com/asanders-tester/2df279e09bdf36f4147b1ccb691050b3

**Additional context**
I very well may just have an error, but I've tried everything I can find online to fix this problem. I've increased the `connectionRetryTimeout` to as high as 500000, downgraded to wdio v5, and added the `enablePerformanceLogging = false` because of an open [bug](https://github.com/appium/appium/issues/15685). 
I made a comment on another [ticket](https://github.com/webdriverio/webdriverio/issues/7199) that sounded similar to my issue.

> Please use the correct markdown

**Comment by christian-bromann** [comment]
Thanks for filing the ticket. It seems that your capabilities are not well defined enough for AWS to find the right device. Just providing `"platformName": "ios"` doesn't tell which device you actually want. This might work for Android for random reason but not for iOS. I recommend to look into the AWS docs to see which capabilities are required to request a certain device. In the Appium logs:

```
2021-08-16 01:17:50:324 - [debug] [35m[WD Proxy][39m Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.loanpal.loanpalPros","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
2021-08-16 01:18:50:332 - [35m[WD Proxy][39m Error: timeout of 240000ms exceeded
```

You see that it times out on the AWS side too. 

Closing as this is more a configuration issue rather than a bug in WebdriverIO.

**Comment by asanders-tester** [comment]
> Thanks for filing the ticket. It seems that your capabilities are not well defined enough for AWS to find the right device. Just providing `"platformName": "ios"` doesn't tell which device you actually want. This might work for Android for random reason but not for iOS. I recommend to look into the AWS docs to see which capabilities are required to request a certain device. In the Appium logs:
> 
> ```
> 2021-08-16 01:17:50:324 - [debug] �[35m[WD Proxy]�[39m Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.loanpal.loanpalPros","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
> 2021-08-16 01:18:50:332 - �[35m[WD Proxy]�[39m Error: timeout of 240000ms exceeded
> ```
> 
> You see that it times out on the AWS side too.
> 
> Closing as this is more a configuration issue rather than a bug in WebdriverIO.

You aren't meant to add much into the capabilities because most of it is defaulted, and it'll actually cause a failure if you override them. The device pool set up has the devices and the lines here get the UDID for the device and manipulates it because appium doesn't accept a '-' in the UDID.
```
[DeviceFarm] if [ $(echo $APPIUM_VERSION | cut -d "." -f2) -ge 19 ]; then
  DEVICEFARM_DEVICE_UDID_FOR_APPIUM=$(echo $DEVICEFARM_DEVICE_UDID | tr -d "-");
  DEVICEFARM_WDA_DERIVED_DATA_PATH=$DEVICEFARM_WDA_DERIVED_DATA_PATH_V6;
elif [ $(echo $APPIUM_VERSION | cut -d "." -f2) -ge 18 ]; then
  DEVICEFARM_DEVICE_UDID_FOR_APPIUM=$(echo $DEVICEFARM_DEVICE_UDID | tr -d "-");
  DEVICEFARM_WDA_DERIVED_DATA_PATH=$DEVICEFARM_WDA_DERIVED_DATA_PATH_V5;
elif [ $(echo $APPIUM_VERSION | cut -d "." -f2) -ge 17 ]; then
  DEVICEFARM_DEVICE_UDID_FOR_APPIUM=$(echo $DEVICEFARM_DEVICE_UDID | tr -d "-");
  DEVICEFARM_WDA_DERIVED_DATA_PATH=$DEVICEFARM_WDA_DERIVED_DATA_PATH_V4;
elif [ $(echo $APPIUM_VERSION | cut -d "." -f2) -ge 16 ]; then
  DEVICEFARM_DEVICE_UDID_FOR_APPIUM=$(echo $DEVICEFARM_DEVICE_UDID | tr -d "-");
  DEVICEFARM_WDA_DERIVED_DATA_PATH=$DEVICEFARM_WDA_DERIVED_DATA_PATH_V3;
elif [ $(echo $APPIUM_VERSION | cut -d "." -f2) -ge 15 ]; then
  DEVICEFARM_DEVICE_UDID_FOR_APPIUM=$(echo $DEVICEFARM_DEVICE_UDID | tr -d "-");
  DEVICEFARM_WDA_DERIVED_DATA_PATH=$DEVICEFARM_WDA_DERIVED_DATA_PATH_V2;
else
  DEVICEFARM_DEVICE_UDID_FOR_APPIUM=$DEVICEFARM_DEVICE_UDID;
  DEVICEFARM_WDA_DERIVED_DATA_PATH=$DEVICEFARM_WDA_DERIVED_DATA_PATH_V1;
fi
```

**Comment by christian-bromann** [comment]
@asanders-tester understand. Well all I can say here is that WebdriverIO doesn't receive a response. If my assumption that capabilities were configured are wrong, then it needs to be a problem on AWS end.
