### ISSUE TITLE
WDIO returns an object even if element cannot be found

### ISSUE THREAD

**Issue by jlipps** [webdriverio/webdriverio#7307]
In the case a call to `driver.findElement` results in a server-side 404/NoSuchElement, I would expect a client side error to be thrown, not an error object to be returned. But consider this example:

```js
const wdio = require('webdriverio');

async function main () {
  const driver = await wdio.remote({
    connectionRetryCount: 0,
    hostname: 'localhost',
    port: 9515,
    path: '/',
    capabilities: {
      browserName: 'chrome'
    }
  });
  try {
    await driver.navigateTo('https://google.com');
    await driver.findElement('xpath', '//badelement');
    console.log(1);
  } finally {
    await driver.deleteSession();
  }
}

main().catch(console.error);
```

When run, it prints out `1`, and the value of findElement is:

```
{
  error: 'no such element',
  message: 'no such element: Unable to locate element: {"method":"xpath","selector":"//badelement"}\n' +
    '  (Session info: chrome=92.0.4515.159)',
  stacktrace: '0   chromedriver                        0x0000000109627829 chromedriver + 2730025\n' +
    '1   chromedriver                        0x0000000109ce4f43 chromedriver + 9797443\n' +
    '2   chromedriver                        0x00000001093b9958 chromedriver + 182616\n' +
    '3   chromedriver                        0x00000001093edd7b chromedriver + 396667\n' +
    '4   chromedriver                        0x000000010941f6a4 chromedriver + 599716\n' +
    '5   chromedriver                        0x000000010940aecd chromedriver + 515789\n' +
    '6   chromedriver                        0x000000010941d464 chromedriver + 590948\n' +
    '7   chromedriver                        0x000000010940b193 chromedriver + 516499\n' +
    '8   chromedriver                        0x00000001093e18be chromedriver + 346302\n' +
    '9   chromedriver                        0x00000001093e2b25 chromedriver + 351013\n' +
    '10  chromedriver                        0x00000001095eef8f chromedriver + 2498447\n' +
    '11  chromedriver                        0x0000000109601a61 chromedriver + 2574945\n' +
    '12  chromedriver                        0x00000001095d476b chromedriver + 2389867\n' +
    '13  chromedriver                        0x0000000109602eda chromedriver + 2580186\n' +
    '14  chromedriver                        0x00000001095e4ffc chromedriver + 2457596\n' +
    '15  chromedriver                        0x000000010961c148 chromedriver + 2683208\n' +
    '16  chromedriver                        0x000000010961c2d1 chromedriver + 2683601\n' +
    '17  chromedriver                        0x000000010962c848 chromedriver + 2750536\n' +
    '18  libsystem_pthread.dylib             0x00007fff6f61e109 _pthread_start + 148\n' +
    '19  libsystem_pthread.dylib             0x00007fff6f619b8b thread_start + 15\n'
}
```

Is the user meant to inspect every object that comes back from `findElement` to determine if it is an element or if it's an error?

**Comment by praveendvd** [comment]
@jlipps  findELement is w3c command used to retrieve the response 

use  wdio selectors instead

But the selector also doesn#t throw an error unless you try to do an action on the object like 

```
const elem = await $("//badlocator")
await elem.click()
```

@christian-bromann 

https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/browser/%24.ts

should we add a throw error if the element res has an error in it for $.ts ?

```
export default async function $ (
    this: WebdriverIO.Browser | WebdriverIO.Element,
    selector: Selector
) {
    /**
     * convert protocol result into WebdriverIO element
     * e.g. when element was fetched with `getActiveElement`
     */
    if (typeof selector === 'object' && typeof selector[ELEMENT_KEY] === 'string') {
        return getElement.call(this, undefined, selector)
    }

    const res = await findElement.call(this, selector)
    if ( res.hasOwnProperty('error') ) throw new Error(JSON.stringify(res,null,2))
    return getElement.call(this, selector as string, res)
}
```

**Comment by jlipps** [comment]
OK thanks for the reply. My experience of working with every other webdriver client across many other languages is that they do the equivalent of throwing an exception when an element cannot be found (and a single element is requested). So I was surprised by wdio's behavior here.

**Comment by jlipps** [comment]
More generally, I would expect that any command which results in a non-200 response from the webdriver server would result in an error/rejection on the client side.

**Comment by jlipps** [comment]
But good to know I should always use `driver.$` instead of `driver.findElement`. I assumed they were the same thing.

**Comment by christian-bromann** [comment]
> should we add a throw error if the element res has an error in it for $.ts ?

No, WebdriverIOs selector methods have lazy loading capabilities. So there should be no issues if an element is not found. Once you call an action on it WebdriverIO will then try to find it and throws and error if it can't

> I would expect that any command which results in a non-200 response from the webdriver server would result in an error/rejection on the client side.

Using raw W3C commands documented in https://webdriver.io/docs/api/webdriver will just return the server response. The `webdriver` package is meant to be used to interact with the protocol. The behavior logic should be implemented in whatever package consumes it, e.g. `webdriverio`. I believe other commands will throw an error if the response is a non 200 however element queries are special in the sense that if an element wasn't found and 404 is returned it doesn't necessarily mean something went wrong, it just indicates that the element wasn't found. In some cases this is what you would expect, e.g. wait until an element disappears. This is why for `findElement` a commands alike the behavior is different.

As @praveendvd correctly points out, to query elements, always use webdriverio commands like `$` or `$$` .

**Comment by jlipps** [comment]
@christian-bromann is there some kind of no-op function I can run on the element then to determine whether it exists? When writing tests I sometimes want to simply check for the existence of an element

**Comment by praveendvd** [comment]
> @christian-bromann is there some kind of no-op function I can run on the element then to determine whether it exists? When writing tests I sometimes want to simply check for the existence of an element

https://webdriver.io/docs/api/element/isExisting/#usage

Use is existing

**Comment by jlipps** [comment]
ah ok, this is boolean, correct? so ultimately no matter what I need to make a helper function that finds the element, and then conditionally throws if isExisting returns false.

**Comment by praveendvd** [comment]
> ah ok, this is boolean, correct? so ultimately no matter what I need to make a helper function that finds the element, and then conditionally throws if isExisting returns false.

A test becomes test when you assert something , so do an assertion that element exist if that's what you want , if it's just part of a sequence of step , then the next step like element.click will fail , so depends on the context in which you are using it

**Comment by jlipps** [comment]
Yeah, my use case is a bit abnormal in that I'm using wdio to test a server implementation of the protocol, not to test an app itself per se.
