### ISSUE TITLE
API documentation is based on callbacks and makes it difficult to write promises-based code

### ISSUE THREAD

**Issue by nareshbhatia** [webdriverio/webdriverio#732]
For example, the documentation for the [init()](http://webdriver.io/api/protocol/init.html) function specifies the callback argument as follows:

> callback function that contains command results and gets called when the command finishes

Two issues with this:
1. It is unclear what exactly is "command results".
2. It is difficult to write correct promises-based code based on this description.

For example, I was trying to convert the callback based example in the [developer guide](http://webdriver.io/guide.html) and got completely confused. This is what I have currently:

    var webdriverio = require('webdriverio');
    var options = {
        desiredCapabilities: {
            browserName: 'chrome'
        }
    };

    var client = null;

    webdriverio.remote(options).init()
        .then(function(result) {
            client = result;
            return client.url('http://www.google.com');
        })
        .then(function() {
            return client.title();
        })
        .then(function(title) {
            console.log('Title was: ' + title);
            return client.end();
        });

Here are some of the questions I have:

- `webdriver.remote()` is not documented. Is this function synchronous or asynchronous? What does it return?
- I am assuming that `init()` returns a promise which `onFulfilled` provides an initialized instance of webdriveio. I am calling it `client`. Is this assumption correct?
- What value is returned when `url()` is fulfilled?
- As it stands right now, the code is bringing up a browser and then hangs. What is the correct way to write this code using promises?

Granted that writing documentation for promises-based code is difficult (see [this long discussion](https://github.com/jsdoc3/jsdoc/issues/509)). However, something like this from that thread can be adopted:

    /**
     * A promise for the user's favorite color.
     *
     * @promise FavoriteColorPromise
     * @fulfill {string} The user's favorite color.
     * @reject {TypeError} The user's favorite color is an invalid type.
     * @reject {MissingColorError} The user has not specified a favorite color.
     */

    /**
     * Retrieve the user's favorite color.
     *
     * @returns {FavoriteColorPromise} A promise for the user's favorite color.
     */
    User.prototype.getFavoriteColor = function() {
        // ...
    };

At a minimum, if you could provide a promises-based version of the simple example above, that would be of tremendous help.

**Comment by christian-bromann** [comment]
> webdriver.remote() is not documented. Is this function synchronous or asynchronous? What does it return?

Yes it is a synchronous function that creates your webdriver instance. After you have that you need to call `init` to initialise the Selenium session. That command  and all following are asynchronous.

> I am assuming that init() returns a promise which onFulfilled provides an initialized instance of webdriveio. I am calling it client. Is this assumption correct?

`init` creates a selenium session and returns a json with all properties of that session (like is js enabled and other stuff, usually not that important)

> What value is returned when url() is fulfilled?

It returns the usual selenium command response with a status code (should be 0 which means that the command was executed successfully) and some other information which are usually not that important for your test

> As it stands right now, the code is bringing up a browser and then hangs. What is the correct way to write this code using promises?

Sure! Note that all commands responses from the selenium server. They can be used for assertions.

```js
var client = webdriverio.remote(options);

client
    .init()
    .url('http://www.google.com')
    .getTitle().then(function(title) {
        console.log('Title was: ' + title);
    })
    .end();
```

I will try to improve the docs in a way that these kinds of confusion won't come up again. Thanks for your input!

**Comment by bobtuna** [comment]
Can you explain me how .remote() method is working and what is he doing?
**What does it return?** Is it promise or something else? 
What is wdio()?
I am seeing that .remote() work as promise, when I am trying to execute `console.log(webdriverio.remote())`.
