### ISSUE TITLE
Link in the Intercept Service does not work

### ISSUE THREAD

**Issue by timestampx** [webdriverio/webdriverio#7324]
Incorrect link in description [usage-with-webdriver-standalone](https://webdriver.io/docs/wdio-intercept-service/#usage-with-webdriver-standalone) 
![Screenshot_10](https://user-images.githubusercontent.com/5372340/130484475-dfc1cc5d-9e05-4145-ab60-d4a0c559d22d.png)

**Comment by christian-bromann** [comment]
Created issue in correct repository: webdriverio-community/wdio-intercept-service#146
