### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by brightsider** [webdriverio/webdriverio#7333]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.10.1
 - **Mode:** WDIO Cli
 - **Node.js version:** 14.17.5
 - **NPM version:** 6.14.14
 - **Browser name and version:** 92
 - **Platform name and version:** macOS 11.5.2

**Config of WebdriverIO**
WDIO Configuration Helper

? Where is your automation backend located? On my local machine
? Which framework do you want to use? cucumber
? Do you want to use a compiler? Babel (https://babeljs.io/)
? Where are your feature files located? ./features/**/*.feature
? Where are your step definitions located? ./features/step-definitions/steps.js
? Do you want WebdriverIO to autogenerate some test files? Yes
? Do you want to use page objects (https://martinfowler.com/bliki/PageObject.htm
l)? Yes
? Where are your page objects located? ./features/pageobjects/**/*.js
? Which reporter do you want to use? spec
? Do you want to add a service to your test setup? chromedriver
? What is the base url? http://localhost

**Describe the bug**
Cannot use import statement outside a module

**To Reproduce**
npx wdio config

**Expected behavior**
Expected run without error.

**Comment by christian-bromann** [comment]
Unfortunately Cucumber with the current version depends on `@cucumber/create-meta` which has `ts-node` in its dependencies. This got fixed with the latest version of that package will is also part of the latest Cucumber version. We are working. in #7309 to update it which will resolve this issue.
