### ISSUE TITLE
Make setValue work just like selectByValue for <select> tags

### ISSUE THREAD

**Issue by dandv** [webdriverio/webdriverio#734]
If one is agnostic to the input type, `.setValue([name="howMany"], '4')`  is just as semantic as `.selectByValue([name="howMany"], '4')`, and you have one less command to learn . Yet the former will generate this error:

> RuntimeError: invalid element state: Element must be user-editable in order to clear it.

Would it be possible to make setValue work on `<select>` tags as well?

**Comment by christian-bromann** [comment]
`setValue` clears the input element before it sets the value. select elements can't get cleared (see error above). To make this happen, we would have to skip the clear step but unfortunately I can't predict if the selector is an select element or not.
