### ISSUE TITLE
WebdriverIO.Element.waitUntil executes WDIO commands in async mode despite sync mode test context

### ISSUE THREAD

**Issue by tehhowch** [webdriverio/webdriverio#7340]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.10.1 (commit SHA edb4fcb6264dde85713339bcd03a2ca8eca81643)
 - **Mode:**  WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 14.17.3
 - **NPM version:** 6.14.13
 - **Browser name and version:** Chrome 92
 - **Platform name and version:** macOS 11
 - **Additional wdio packages used (if applicable):** (reproducible with `webdriverio/examples/wdio` test script)

**Config of WebdriverIO**
```bash
cd examples/wdio
npm run test:mocha
```

**Describe the bug**
When using sync mode, WDIO commands inside of a `.waitUntil` command executed on a `WebdriverIO.Element` will be async, rather than sync. If using `browser.waitUntil`, the WDIO commands are correctly sync.

**To Reproduce**

Update `examples/wdio/mocha/mocha-test` to include
1. chai.assert (or replace the asserts with w/e else
```js
describe('waitUntil', function () {
    it('should work in sync mode when called from WebdriverIO.Element', function () {
        browser.url('https://webdriver.io');
        const contentHome = browser.$('.main-wrapper');
        try {
            contentHome.waitUntil(() => contentHome.getText() instanceof Promise, { timeout: 1000 });
            assert.fail('should be text!');
        } catch (err) {
            assert.strictEqual(err.message, 'waitUntil condition timed out after 1000ms'); // fails
        }
    });
    it('should work in sync mode when called from browser', function () {
        browser.url('https://webdriver.io');
        const contentHome = browser.$('.main-wrapper');
        try {
            browser.waitUntil(() => contentHome.getText() instanceof Promise, { timeout: 1000 });
            assert.fail('should be text!');
        } catch (err) {
            assert.strictEqual(err.message, 'waitUntil condition timed out after 1000ms'); // passes
        }
    });
});
```

**Expected behavior**
Both tests should pass.

**Comment by christian-bromann** [comment]
I will go ahead and close this issue given that we have deprecated sync usage and will remove it with `v8` of WebdriverIO. If someone is interested fixing this please raise a PR to the `v7` branch. I would be happy to merge and release it.
