### ISSUE TITLE
Failure to find element from WebdriverIO.Element.$ results in reference element changing

### ISSUE THREAD

**Issue by tehhowch** [webdriverio/webdriverio#7344]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.10.1
 - **Mode:** WDIO testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v14.17.3
 - **NPM version:** 6.14.13
 - **Browser name and version:** Chrome 92
 - **Platform name and version:** macOS 11
 - **Additional wdio packages used (if applicable):** 
    "@wdio/cli": "^7.10.1",
    "@wdio/junit-reporter": "^7.10.1",
    "@wdio/local-runner": "^7.10.1",
    "@wdio/mocha-framework": "^7.10.1",
    "@wdio/sauce-service": "^7.10.1", // installed, but executing locally when issue occurred
    "@wdio/selenium-standalone-service": "^7.10.1",
    "@wdio/spec-reporter": "^7.10.1",
    "@wdio/sync": "^7.10.1",

**Config of WebdriverIO**
wdio.conf.js
```js
{
  runner: 'local',
  framework: 'mocha',
  mochaOpts: { ui: 'bdd', timeout: 150000 },
  path: '/wd/hub',
  services: [['selenium-standalone', {
    logPath: 'logs',
    installArgs: { drivers: { chrome: {
      version: '92.0.4515.107',
      baseURL: 'https://chromedriver.storage.googleapis.com',
    } } },
    args: { drivers: { chrome: {
      version: '92.0.4515.107',
      baseURL: 'https://chromedriver.storage.googleapis.com',
    } } },
  }]],
  capabilities: [{
    browserName: 'chrome', browserVersion: '86', 'goog:chromeOptions': {
      args: [
        '--disable-extensions',
        '--no-sandbox',
        '--window-size=1920,1080',
        '--headless',
        '--disable-gpu',
      ],
    },
    specs: ['/path/to/test.spec.js'],
  }],
}
```

**Describe the bug**
When parsing a table cell (*parent*) that contains multiple of the same element selector (*accordions*) and differentiating items inside (*content*), we determine how to parse the content by querying inside the accordion using a unique CSS selector like `[data-qa-attribute="some value"]`. In 7.7.4, this worked fine. However in 7.10.1, searching for the 2nd possible unique selector fails, because the accordion element reference was reset to a different accordion element reference when searching for the first possible unique selector failed.

**To Reproduce**
Still working on a repo. The gist is:
1. get element reference to a container with multiple items
2. loop over `element.$$(content)` as `subelement`
3.  try to find a specific selector inside the subelement, multiple times, on the second or later subelement
4. notice that the search for the specific selector searches inside the _first_ subelement, rather than the one you used when the first specific selector failed.

e.g.
```js
const rows = browser.$$('tr');
rows.forEach((rowEl) => {
  const cell = rowEl.$('[data-selector="value"]');
  const containers = cell.$$('[data-selector="container"]');
  containers.forEach((containerEl) => { // at least 2
    const name = containerEl.$('.name').getText();
    const content = containerEl.$('.content');
    if (name === 'a') processA(content); // first containerEl enters here
    else if (name === 'b') {             // second containerEl enters this block
      if (content.$('[data-selector="no match"]').isExisting()) { /* do something */ } // when this misses
      else if (content.$('[data-selector="has match"]').isExisting()) {                // this one misses too, but shouldn't
        // do something else
      }
    }
  });
});
```

**Expected behavior**
I should be able to repeatedly query inside a specific, non-first element when using a variable bound to that specific WebDriverIO.Element after having located that element with `$$`.

**Logs**
[gist for 7.10.1, with some code too](https://gist.github.com/tehhowch/cca1d73c3bd2ff4ab7ba3f87a9710069)
[gist for 7.7.4, wdio logs only](https://gist.github.com/tehhowch/35139ce58d6b36bedb3d33972fc7e52b)

**Additional context**
The test works correctly in sync mode with WebdriverIO v7.7.4

**Comment by tehhowch** [comment]
@christian-bromann is the above reproduction satisfactory?

**Comment by christian-bromann** [comment]
I haven't look into it. Any help or contributions are appreciated.

**Comment by christian-bromann** [comment]
@tehhowch have you tried run this code with `async/await`?

**Comment by tehhowch** [comment]
> @tehhowch have you tried run this code with `async/await`?

No, I have not. It seems to be an algorithm error so I doubt there would be a difference.

**Comment by christian-bromann** [comment]
> It seems to be an algorithm error so I doubt there would be a difference.

That is incorrect. There is a lot of magic going on if you run these commands in a synchronous fashion. It is likely that an error is located there. I would be great if you can double check. Note that we have depcrecated sync execution and ask everyone to switch to async anyway. Therefor I was hoping that you would be able to transform the test into an async test and we can close this issue.

**Comment by tehhowch** [comment]
Switching all of our page object and test code to async at once is not a reasonable workaround to a bug introduced by a refactoring in a minor version. Furthermore, a deprecated functionality is one that is still expected to work correctly in all application versions in which it is found.

Note that the test passes--in sync mode--when not using wdio's selenium-standalone package, and then fails when using it. This is why I feel the issue is algorithmic.
