### ISSUE TITLE
Add better documentation for multiremote with saucelabs

### ISSUE THREAD

**Issue by saulshanabrook** [webdriverio/webdriverio#735]
OK so I got [multiremote](http://webdriver.io/guide/usage/multiremote.html) working with saucelabs.

I will list the key attributes of my setup bellow. You only want the following things applied when on travis, so just check the environment for the `CI` variable, and only set these configuration options if so.

## `wdio.conf.js`

Include:

```javascript
user: process.env.SAUCE_USERNAME,
key: process.env.SAUCE_ACCESS_KEY
```

Also if you are using Moch and see errors like 1000ms exceeded. Ensure the done() callback is being called in this test`, then increase the timeout here:

```javascript
mochaOpts: {
    timeout: 50000
}
```

The `capabilities` should include some browser, or else it won't launch the tests, but it doesn't matter which browser, because this won't actually be used. A side effect is that it will launch an extra browser and not run any tests on it. I have mine like this:

```
  capabilities: [{
    browserName: 'chrome'
  }
```

## Testing file

Now you wanna define some more options on each browser. Mine look like this:

```javascript
    waitforTimeout: 10000,
    user: process.env.SAUCE_USERNAME,
    key: process.env.SAUCE_ACCESS_KEY,
    host: 'ondemand.saucelabs.com',
    port: 80,
    desiredCapabilities: {
      browserName: 'chrome',
      'tunnel-identifier': process.env.TRAVIS_JOB_NUMBER,
      'idle-timeout': 30000,
      name: 'lucibus',
      version: 'dev',
      platform: 'Mac 10.10',
      build: process.env.TRAVIS_BUILD_NUMBER,
      captureHtml: true
    }
```

If you call the variable returned by `multiremote(..)` browser, call `browser.init()` and begin your tests.

My test file with Mocha, ES6, and `must-js` starts off like this:

```
import 'must'
import webdriverio from 'webdriverio'
import booleanFromEnv from '../caido/config/booleanFromEnv'

var config

if (booleanFromEnv('CI', false)) {
  config = {
    waitforTimeout: 10000,
    user: process.env.SAUCE_USERNAME,
    key: process.env.SAUCE_ACCESS_KEY,
    host: 'ondemand.saucelabs.com',
    port: 80,
    desiredCapabilities: {
      browserName: 'chrome',
      'tunnel-identifier': process.env.TRAVIS_JOB_NUMBER,
      'idle-timeout': 30000,
      name: 'lucibus',
      version: 'dev',
      platform: 'Mac 10.10',
      build: process.env.TRAVIS_BUILD_NUMBER,
      captureHtml: true
    }
  }
} else {
  config = {
    desiredCapabilities: {
      browserName: 'chrome'
    }
  }
}

var browsers = webdriverio.multiremote({
  first: config,
  second: config
})

var firstBrowser = browsers.select('first')
var secondBrowser = browsers.select('second')

describe('App', function () {
  before('init', function *() {
    yield browsers.init()
  })
  after('end', function *() {
    yield browsers.end()
  })
  before('go to URL', function *() {
    yield browsers.url('http://localhost:8081/')
  })

  describe('Grandmaster level', function () {
    function * mustEqual (b, value) {
      yield b.getValue('#grandmaster .level input').must.eventually.equal(value.toString())
    }
    it('must start at 100', function *() {
      yield* mustEqual(firstBrowser, 100)
      yield* mustEqual(secondBrowser, 100)
      yield browsers.sync()
    })
```

## `.travis.yml`

Then just make sure to enable sauce connect in your `.travis.yml`:

```
addons:
  sauce_connect: true
```

**Comment by saulshanabrook** [comment]
I bet if I didn't used the `wdio.conf.js` file and just used mocha to start the tests, that extra machine wouldn't be provisioned. However I am using a bunch of yield statements in my mocha tests that don't seem to work when run directly by mocha, so requires using the `wdio` CLI tool.

**Comment by christian-bromann** [comment]
@saulshanabrook so what exactly is missing in our [current documenation](http://webdriver.io/guide/usage/multiremote.html)? Only the sauce part?

**Comment by saulshanabrook** [comment]
If I created a PR with a section in that documentation page for using with a `wdio.conf.js` file would that be helpful? I would just mention that you need to specify that both that config and the config passed to multiremote need the `user` and `key` values.

Also, It might be helpful to have a saucelabs section, to show an example of passing in things like the tunnel identifier and also increasing timeouts. I could make a PR for that as well, if you think it would be helpful.

**Comment by christian-bromann** [comment]
Yeah, if you could open a PR that would be awesome

**Comment by christian-bromann** [comment]
I guess we can close this now. Thanks for your doc PR. Applying this for multiremote should be obvious.
