### ISSUE TITLE
Allow to set Chrome preferences when running tests with Puppeteer

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#7351]
**Is your feature request related to a problem? Please describe.**
With the following test you are able to specify preferences, e.g. default download directory, in Chrome using WebDriver:

```js
const { remote } = require('./packages/webdriverio')

let browser

const opts = {
    // automationProtocol: 'devtools',
    capabilities: {
        browserName: 'chrome',
        'goog:chromeOptions': {
            prefs: {
                'download.default_directory': __dirname
            }
        }
    }
}

;(async function () {
    browser = await remote(opts)
    await browser.url('https://the-internet.herokuapp.com/download')
    await browser.$("a[href*='some-file.txt']").click()
    await browser.deleteSession()
})().catch(async (e) => {
    console.error(e.stack)
    await browser.deleteSession()
})
```

The `prefs` property is not respected when starting sessions using Puppeteer.

**Describe the solution you'd like**
I would suggest to create a temporary directory with a preference file that contains these preferences. Then pass this directory as `customDataDir` to the launch method, like in [this exampe](https://stackoverflow.com/a/65113325/765174). This should only happen if someone defines these prefs.

**Describe alternatives you've considered**
In WebDriver this obviously works already.

**Additional context**

**Comment by christian-bromann** [comment]
> Is that possible to be added to WDIO?

What do you mean?

> as we don't have direct access to a puppeteer

You do have access to the Puppeteer instance with [`getPuppeteer`](https://webdriver.io/docs/api/browser/getPuppeteer).

**Comment by yzvezdin** [comment]
Cool, will try. Thank you.

**Comment by christian-bromann** [comment]
This feature got implemented in `chrome-launcher` (GoogleChrome/chrome-launcher#247) and will be available once merged and released.
