### ISSUE TITLE
Import globals instead of relying on globals

### ISSUE THREAD

**Issue by fregante** [webdriverio/webdriverio#7354]
**Is your feature request related to a problem? Please describe.**

Globals bring a variety of issues that need to be addressed separately and could be avoided by just not using globals now that we have CJS and ESM.

Namely this is ESLint and TypeScript issues (I'm not looking for a solution to each)

**Describe the solution you'd like**

Like Jest, offer a [`injectGlobals: false` option](https://jestjs.io/docs/configuration#injectglobals-boolean) and document a file to import:
```js
import {expect, jest, test} from '@jest/globals';
```

I tried using `const {default: browser} = require("webdriverio/build/commands/browser")` but the functions refer to `this` so there must be something that I'm missing.

**Additional context**

No setup, type work out of the box thanks to my `require` (if only my import was right)

<img width="703" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/131212360-d52be330-b0fe-4a0e-a048-d2cc58bebe82.png">

**Comment by christian-bromann** [comment]
> Globals bring a variety of issues

Can you elaborate what kind of issues you are referring to?

I definitely believe moving away from globals is a cleaner way of handling the browser variable. It would require some refactoring across the project to get this working though. So far I haven't had anyone with severe issues using the global variable.

**Comment by fregante** [comment]
> > Globals bring a variety of issues
> 
> Can you elaborate what kind of issues you are referring to?

ESLint `no-undef` reports, I don’t even lack of completions, TypeScripts compile errors. Each of these issues have its own solution/config, but an `import` would work out of the box

**Comment by christian-bromann** [comment]
> ESLint `no-undef` reports, I don’t even lack of completions

For that we offer an [Eslint plugin](https://www.npmjs.com/package/eslint-plugin-wdio).

I guess we can optionally offer to import these. Any other opinions?

**Comment by erwinheitzman** [comment]
eslint allows you to define globals for this very reason, add `browser` as a global and you're ready to go

**Comment by fregante** [comment]
I think you have not read my post.

1. I'm not looking for a solution, I know _more configuration_ fixes each of the 3 issues
2. I don't think it's reasonable for a project to require additional configuration just to get the basics working
3. `no-undef` only fixes one of the 3 issues

**Comment by erwinheitzman** [comment]
I read it but a bit too quick as I am doing this during my coffee break ^^;

I think it's nice to offer the option but to say it's unreasonable I think is a bit of a stretch. I say this because if there's compilation / build errors then we should resolve those and the same goes for unrecognized autocompletions as this would be more of a workaround then a fix for the actual issues it seems.

Do you agree with this @fregante or am I making too many assumptions here?

**Comment by christian-bromann** [comment]
> fixes each of the 3 issues

@fregante can you clarify the issues you are mentioning? So far I only see no-undef when not having browser (or $ or $$) defined as globals.

**Comment by fregante** [comment]
> ESLint `no-undef` reports, IDE lack of completions, TypeScripts compile errors.

**Comment by christian-bromann** [comment]
We will put this into the v8 release.

**Comment by erwinheitzman** [comment]
> We will put this into the v8 release. We should then deprecate the usage of globals and remove them completely in v9.

How do you feel about making the use of globals optional?

**Comment by christian-bromann** [comment]
> How do you feel about making the use of globals optional?

I don't have a strong opinion for or against it. What would be the advantages of doing that?

**Comment by erwinheitzman** [comment]
> We will put this into the v8 release. We should then deprecate the usage of globals and remove them completely in v9.

How do you feel about making the use of globals optional instead?

**Comment by erwinheitzman** [comment]
@christian-bromann after having thought about it some more we could actually explain that the user can create their own globals in one of the hooks like so:
```js
import { browser } from 'webdriverio';

export const config = {
  before: () => {
    global.browser = browser
  }
}
```
If this would work then I feel that we could indeed remove the use of globals 👍

**Comment by christian-bromann** [comment]
@erwinheitzman totally, we could even create a service that would attach everything to the global scope.

**Comment by christian-bromann** [comment]
I looked into other projects and aside from `vitest` many offer to import globals directly but basically still adding them to the global scope anyway. Given we never had any issues with users complaining about WebdriverIO adding `browser` to the global scope I'ld suggest to keep the current behavior but provide ways to also import them explicitly like e.g. Jest. Adding a configuration to avoid injecting into the global scope, like Jest, can be also implemented.

**Comment by christian-bromann** [comment]
An implementation is done in #8631, feedback would be much appreciated.

**Comment by erwinheitzman** [comment]
I just found out that Jest uses the globals but you can overwrite them with the imports, maybe we can apply the same idea (keep the globals and allow them to be overwritten)?

**Comment by christian-bromann** [comment]
@erwinheitzman that is what the PR implements. The behavior stays the same as in `v7` with the difference that if you like you can import implicitly and even disable the injection of globals.
