### ISSUE TITLE
Add ability to load addons / extensions / webextensions in Firefox

### ISSUE THREAD

**Issue by fregante** [webdriverio/webdriverio#7355]
**Is your feature request related to a problem? Please describe.**

Firefox requires addons to be signed unless they're installed "temporarily". This means that the regular way of loading extensions via `firefox-profile` does not work anymore:

- https://github.com/saadtazi/firefox-profile-js/issues/125

_Side note: It can work if you use Firefox Developer Edition but that’s not available on BrowserStack_

**Describe the solution you'd like**

`selenium-webdriver` exposes an API that lets you install addons _after_ the browser has launched, which allows installing addons _temporarily_: https://github.com/SeleniumHQ/selenium/blob/586affe0cf675b1d5c8abc756defa4a46d95391b/javascript/node/selenium-webdriver/firefox.js#L666

**Describe alternatives you've considered**

This doesn't appear to be possible with WDIO, except may by sending raw WebDriver commands but this method is nowhere to be found.

**Additional context**

- https://webdriver.io/docs/api/webdriver - no API to send arbitrary command
- https://webdriver.io/docs/firefox-profile-service#configuration - the suggested way does not work in regular Firefox
- https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/firefox.html - `selenium-webdriver/firefox` docs 
- https://github.com/mozilla/webextension-polyfill/blob/ea82fbf55684193c10e81545378a7656a0871840/test/integration/setup.js#L53-L73 - how Mozilla calls said API, at a lower level

**Comment by christian-bromann** [comment]
I suggest to create a protocol file similar we have for Chrome in [`@wdio/protocols`](https://github.com/webdriverio/webdriverio/tree/main/packages/wdio-protocols/protocols) and [apply this protocol](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriver/src/utils.ts#L165-L205) when Firefox is used. Any contributions are welcome!

**Comment by christian-bromann** [comment]
Implemented in #7384
