### ISSUE TITLE
Duplicate reporter document entry for Intercept service

### ISSUE THREAD

**Issue by babusekaran** [webdriverio/webdriverio#7369]
**Pre-check**
- [X] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [ ] Missing documentation
- [X] Other

![wdio-doc-issue](https://user-images.githubusercontent.com/26348282/131383441-199d4cb5-c268-4358-aa52-7c882e9d7a09.png)

**Comment by christian-bromann** [comment]
Good catch, let's continue convo in #7370
