### ISSUE TITLE
Add support for multiremote with just `wdio.conf.js`

### ISSUE THREAD

**Issue by saulshanabrook** [webdriverio/webdriverio#737]
What do you think about adding the ability to use multiremote while still just using a `wdio.conf.js` file and the `wdio` command line tool, instead of importing `webdriverio` and then calling `webdriverio.multiremote(...)`.

I ask because if you don't use the `wdio` command line tool then you lose the generator support added for Mocha (I could be totally wrong about this, but this is my hypothesis so far. Lemme know if this is false).

I have gotten multiremote to work with the `wdio` CLI tool, but it is suboptimal, because you have to define the `capabilities` in the `wdio.conf.js` file in order to get it to run the test file, which calls `multiremote`. This means it sets up an extra browser testing instance that is not used by multiremote but is still provisioned and wasted. If this doesn't make sense, I can elaborate further. This approach is documented in #735.

Instead I am hoping we could some sort of option in the configuration to enable multiremote there. If this was added and documented, it would close #735. I would be happy to work on it and create a PR for it, if we agreed on the API first.

**Comment by christian-bromann** [comment]
I don't think it makes sense to mix single browser tests with multiremote tests. You should have two different wdio configs, one for usual e2e tests with different browser and the other one only for multiremote tests. I will create a ticket to add support for multiremote in the wdio test runner.

**Comment by christian-bromann** [comment]
just recognised that I marked the issue as "discussion" and closed it immediately after responding to it. Sorry! If you feel like it make sense I can reopen it again. But just the fact that multiremote commands return two results makes it impossible to have the same tests for remote and multiremote tests.

**Comment by saulshanabrook** [comment]
I agree with you, it should be a different wdio config and completely different tests.

I am just wondering if it is possible to use the `wdio` command line tool, with a `wdio.conf.js` file to support creating a multiremote, without having to import `webdriverio` and call `multiremote()`
