### ISSUE TITLE
[Config] Incorrect config generation when picking allure leads to error thrown on wdio runs

### ISSUE THREAD

**Issue by bartekkustra** [webdriverio/webdriverio#7375]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.11.1 (but happened in 7.10.0 as well)
 - **Mode:** standalone/local
 - **If WDIO Testrunner, running sync/async:** async
 - **Platform name and version:** macOS

**Config of WebdriverIO**
Standard `wdio config` result:
![image](https://user-images.githubusercontent.com/13950466/131700576-f314cefa-67d3-48bb-bf85-7b2eda012be8.png)

This only happens when picking `allure` as a reporter

**Describe the bug**
When picking the allure reporter the `wdio.conf.js` file has additional `afterTest` function which is incorrectly created with `async` at the beginning of the line instead.

```diff
- async afterTest: function(test, context, { error, result, duration, passed, retries }) {
+ afterTest: async function(test, context, { error, result, duration, passed, retries }) {
```

**To Reproduce**
- `npx wdio config`
- Pick `allure` as a reporter (one of many or only, doesn't matter)
- generate config
- check line `:223` for `afterTest` function and note the issue

**Expected behavior**
It should correctly write the line:
```
afterTest: async function(test, context, { error, result, duration, passed, retries }) {
```

**Comment by christian-bromann** [comment]
This got fixed thanks to @gpt14
