### ISSUE TITLE
Attachment (Screenshot) is one Step to late of Allure Reporter with WebdriverIO

### ISSUE THREAD

**Issue by CompGeist** [webdriverio/webdriverio#7376]
The screenshots that will be attachments in the report are visible one step to late. (see picture)

**Expected behavior**
- report show screenshots for failing steps only
- screenshot (attachment) is visible at failing step

**Context:**
 - The report creates screenshots for failing steps only
 - this behavior is chains with usage of multiple steps with one screenshot each (was visible for screenshot on every step too; see picture)
 - my guess: wrong index usage

**Environment:**
 - **WebdriverIO version ("@wdio/cli"):** "^7.11.1"
 - **Allure reporter version ("@wdio/allure-reporter"):**  "^7.10.1"
 - execution date (dd.mm.jjjj): 02.09.2021
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Browser name and version:** Chrome v92.0.4515.159 (64-Bit)
 - **Platform name and version:** Windows 10

**relevant code of wdio.conf.ts**
`const {execSync} = require('child_process');`
`const resultDirectory: string = '.\\testresults\\allureReport'; // fixed directory`
`export const config: WebdriverIO.Config = {`
`...`
`reporters: [['allure', {`
`outputDir: resultDirectory,`
`disableWebdriverStepsReporting: true,`
`disableWebdriverScreenshotsReporting: false, // to allow screenshots`
`}]],`
`...`
`onPrepare: async function (config, capabilities) {`
    `    const npmCommandClearAllure: string = 'npm run clearAllureDirectory --allureDir=' + resultDirectory;`
  `      execSync(npmCommandClearAllure)`
`    },`
`...`
    `afterTest: function(test, context, { error, result, duration, passed, retries }) {`
`        if (error) {`
     `       browser.takeScreenshot();`
`        }`
`    },`
`...`
   `onComplete: function(exitCode, config, capabilities, results) {`
        `const npmCommandConvertAllure: string = 'npm run convertAllure --xmlSrcDir=' + resultDirectory + ' --targetDir='+ resultDirectory + '\\00Clean';`
       ` execSync(npmCommandConvertAllure);`
  `  },`
`}`
**relevant code of package.json**
`...`
`"devDependencies": {`
`...`
`"@wdio/allure-reporter": "^7.10.1",`
`...`
`},`
`"scripts": {`
`...`
`"clearAllureDirectory": "rimraf %npm_config_allureDir%",`
`"convertAllure": "allure generate %npm_config_xmlSrcDir% -o %npm_config_targetDir% --clean && rimraf %npm_config_xmlSrcDir%\\*.* && xcopy /s %npm_config_targetDir%\\* %npm_config_xmlSrcDir% && rimraf %npm_config_targetDir%",`
`...`
`},`
`"dependencies": {`
`...`
`"@wdio/cli": "^7.11.1",`
`"rimraf": "^2.6.2",`
`...`
`}`

**Bug (screenshot only on error):**
![screenshotWrongPosition](https://user-images.githubusercontent.com/89922249/131840025-3c45ad20-88d0-42ce-a8f8-8a3ca33e043e.jpg)
**Bug (screenshot on every step):**
![screenshotWrongPositions](https://user-images.githubusercontent.com/89922249/131841849-d28bfb42-b6ad-4637-b559-80663e59ed81.jpg)

**Comment by christian-bromann** [comment]
@CompGeist thanks for reporting. Please consider to contribute to the project. The maintainer team is happy to help.

**Comment by praveendvd** [comment]
@christian-bromann  @CompGeist  

it seems like you are using async , for async everythign is promise even after test. 

so you should handle it properly as :
```
afterTest: async function(test, context, { error, result, duration, passed, retries }) {
if (error) {
await browser.takeScreenshot();
}
```

**Comment by christian-bromann** [comment]
@CompGeist can you verify whether or not you are using sync or async? If so can you provide a reproducible example?

**Comment by CompGeist** [comment]
> @CompGeist can you verify whether or not you are using sync or async? If so can you provide a reproducible example?
This was the solution!

@christian-bromann yes we use async code in our tests. I can't provide a full reproducible example (company regulation and i don't have time to create a new free one), but i can show the changes i did.

This change in the "wdio.conf.js" did the trick:
```
afterTest: async function(test, context, { error, result, duration, passed, retries }) {  
        if (error) {
            await browser.takeScreenshot();
        }
},
```
Compared to bevore (which created the explained error):
```
afterTest: function(test, context, { error, result, duration, passed, retries }) {  
        if (error) {
            browser.takeScreenshot();
        }
},
```

Conclusion: It wasn't a bug, it was a layer 7 problem.
