### ISSUE TITLE
Accept Insecure Certs Safari - not work

### ISSUE THREAD

**Issue by opensourcesensor** [webdriverio/webdriverio#7380]
- WebdriverIO version: latest
 - Mode: WDIO Testrunner, async:
 - Node.js version: 16.8.2
 - NPM version: 7.21.0
 - Browser name and version: Safari, latest
 - Platform name and version: macOS 11

For this issue, I use these 2 capabilities:
strictSSL: true,
acceptInsecureCerts: true,

On the website I run the tests, there are insecure SSL certs, that have to be accepted manually.
For this I take the capability: 
acceptInsecureCerts: true,
--> It works in Chrome and Firefox, but not on safari.

**To Reproduce**
Open a website with insecure SSL certs with safari browser.

**Expected behavior**
Than there should be the message that you have to accept the SSL certificates manually,
to enter the website.

**Log**
There is no log, this failure you only see in the desktop.
--> The error is, that he cant click an element, because the web page can not load.

**Comment by christian-bromann** [comment]
Thanks for reporting the issue.

> acceptInsecureCerts: true,
> --> It works in Chrome and Firefox, but not on safari.

Please report this bug in the WebKit project. It can't be fixed within WebdriverIO.

**Comment by christian-bromann** [comment]
Just found [this article](https://www.toolsqa.com/selenium-webdriver/ssl-certificate-in-selenium/) saying:

> For Safari, the untrusted certificates handling is a bit different. We need to execute a JavaScript piece that will allow the browser to pass through the certificate and navigate to the intended page.

To ignore insecure certs, just run:
```js
await browser.execute('CertificateWarningController.visitInsecureWebsiteWithTemporaryBypass()')
```

**Comment by opensourcesensor** [comment]
Hi @christian-bromann ,
thank you!
This is working and really helpful for me!

Maybe we can add this to the WDIO documentation at some time?

All the best,
Fabian Schmider

**Comment by christian-bromann** [comment]
> Maybe we can add this to the WDIO documentation at some time?

Yeah, we should have a FAQ section with a page on insecure certs. You want to help us take a stab at it?

**Comment by opensourcesensor** [comment]
@christian-bromann, that sounds interesting, but my knowledge of certificates is not very deep. - feel free to send an email with your expectations, then we'll see if I can help! fabian.schmider@gmx.de

**Comment by christian-bromann** [comment]
I would suggest to create a new `FAQ` section and start with a page called `Accept Insecure Certs`. Then in that page summarise what the blog article says. What do you think?

**Comment by opensourcesensor** [comment]
@christian-bromann , ah yes that sounds good, there I can help!

**Comment by christian-bromann** [comment]
@opensourcesensor awesome, let me know if you need any help dealing with our docs system. It is a typical Docusarus v2 setup, you can find more information here: https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#documentation

**Comment by opensourcesensor** [comment]
Hi @christian-bromann ,
the documentation is not working for me.
I think you could add the link of this report in the https://webdriver.io/docs/configurationfile/.

Thank you!
BR
Fabian Schmider

**Comment by christian-bromann** [comment]
> the documentation is not working for me.

Can you elaborate what is not working?

**Comment by hariharanbrowserstack** [comment]
@christian-bromann , could see this workaround of executing `CertificateWarningController.visitInsecureWebsiteWithTemporaryBypass()` is not working from safari 15.6 . Do you see the same ? Did we find any alternative for the same ?

**Comment by christian-bromann** [comment]
I am not familiar with this, also never used it. If you find how this works it would be great if we could document it.

**Comment by kumarsourav12** [comment]
so, whats up with this issue now? did we find any solution? newer safari versions are not supporting visitInsecureWebsiteWithTemporaryBypass
