### ISSUE TITLE
Namespace 'global.WebdriverIO' has no exported member 'Browser'

### ISSUE THREAD

**Issue by SNDST00M** [webdriverio/webdriverio#7383]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.1.1
 - **Mode:** Standalone
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 16.4.2 (TS version 4.3.5)
 - **NPM version:** 7.20.3
 - **Browser name and version:** Chrome 92
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** `@types/webdriverio`, `@wdio/cli`

**Config of WebdriverIO**
An example of how you configured WebdriverIO config: N/A

**Describe the bug**
The global namespace `WebdriverIO` is consistently empty. Breaking these references:
- `WebdriverIO.Browser`
- `WebdriverIO.MultiRemoteBrowser`
- `WebdriverIO.Element`

**To Reproduce**

```javascript
import { remote } from "webdriverio";
const browser = await remote({
	capabilities: {
		browserName: "chrome",
		pageloadStrategy: this.loadStrategy
	}
});
await browser.url(process.env.CI_ADDRESS);
```

VSC reports all types as `any` because the type references can't be validated.

**Expected behavior**
VSC reports the type of each function return on hover.

**Additional context**
N/A

**Comment by christian-bromann** [comment]
Please set:
```json
"types": ["webdriverio/async"],
```
in your tsconfig.json. See also https://webdriver.io/docs/typescript#framework-setup

**Comment by SNDST00M** [comment]
Thanks!

**Comment by SNDST00M** [comment]
Does it work with pure JavaScript?

**Comment by SNDST00M** [comment]
And do I need to install anything in `package.json`? I have `webdriver` `@types/webdriverio` & `@wdio/cli` installed

**Comment by christian-bromann** [comment]
> Does it work with pure JavaScript?

Yes!

> And do I need to install anything in `package.json`? I have `webdriver` `@types/webdriverio` & `@wdio/cli` installed

Please follow the [Getting Started](https://webdriver.io/docs/gettingstarted) guide in our docs.
