### ISSUE TITLE
Webdriverio inheritance approach

### ISSUE THREAD

**Issue by thangavignesh** [webdriverio/webdriverio#739]
I am trying to inherit webdriverio api function's in my project module. But, it's behaving bit different than normal module. could your please let me know, how to derive the webdriverio root module?

##./lib/apm.js:

```javascript
var webdriverio = require('../node_modules/webdriverio/lib/webdriverio'), // I know using dangerously.
    utils = require('util');

function apm() {
    this.super_.apply(this);
    this.version = '0.0.1' //tmp: later from package.json
};

utils.inherits(apm, webdriverio);

apm.prototype.setVersion = function(version){
    this.version = version;
};

apm.prototype.getVersion = function() {
    return this.version;
}

module.exports = apm;

```
##index.js

```javascript
var apm= require('./lib/apm');
console.log(apm.remote().url())
```

###Error: 
```text
console.log(apm.remote().url());
                ^

has no method 'remote'
```

**Comment by christian-bromann** [comment]
@thangavignesh the WebdriverIO client instance is a Monad and can't be used as inheritance. I would recommend to use the addCommand utility to enhance your webdriver instance with additional methods.
