### ISSUE TITLE
Cannot get Electron's BrowserWindow URL after URL navigate

### ISSUE THREAD

**Issue by lseongjoo** [webdriverio/webdriverio#740]
Using WebdriverIO for testing an Electron app.

I can get the current url of an Electron app's BrowserWindow with client.url() like with any other browser. Though you cannot navigate to a URL using it since Electron uses BrowserWindow.loadUrl() to do that.

```javascript
# get current URL
var webdriverio = require('webdriverio');
# set Electron option
var options = {
    host: "localhost",
    port: 9515,
    desiredCapabilities:{
      browserName: 'chrome',
      chromeOptions: {
        binary: 'Electron.app/Contents/MacOS/Electron'
      }
    }
  };

var client = webdriverio.remote(options);
client.init();

client.url(function(err, res){
    console.log(res.value);
});
```
But the problem is that if Electron client navigates to a remote URL (like https://github.com/) using BrowserWindow.loadUrl() internally due to some event (like button click), then the Webdriver client does not proceed to next chained action.

```javascript
client
  .click('#some_btn_to_load_remote_url')
  .url(function(err, res){
      # Problem! Cannot reach here.
  })
```

The Electron client uses ipc.send() to handle event and the event handler is as below.

```javascript

ipc.on('loadUrl', function(event, url){
    mainWindow.loadUrl(url);
});
```

I didn't send back ipc reply since the caller window would not get the reply anyway.

**Comment by christian-bromann** [comment]
mhm..haven't tried to use WebdriverIO with Electron yet. There are people who got that running though, see #721 

@LeMoussel any idea?

**Comment by lseongjoo** [comment]
Oh, it is running alright. I am using it for testing and everything works. But just got stuck with getting URL when above scenario.



2015. 8. 27. 오후 5:42 Christian Bromann <notifications@github.com> 작성:

**Comment by christian-bromann** [comment]
@lseongjoo so what do you think how we should fix this issue?

**Comment by lseongjoo** [comment]
Thank you @christian-bromann for following up this issue. 

I think, figuring out when and how WebdriverIO client as Electron loses "grip" on client's url would be the first thing. I set up a simple test to single out the problem. 

```javascript

client
  .url(function(err, res){
    // this works
    var path = url.parse(res.value).pathname;
    console.log(path);
  })
  .click("#btn_navigate_to_diff_url")
  .url(function(err, res){
     // problem! cannot reach here
      var path = url.parse(res.value).pathname;
      console.log(path);
  })
```

I suspected first that it was due to schema change. But when the above sequence is performed within the same schema, say file://  since Electron is native app, the problem persists. It cannot reach the second url fetching part. Thus, it seems unlikely that it is schema change problem.

I looked into webdriverio/url.js (http://git.io/vG8DD), and suspect that requestHandler.create() is failing with Electron when URL is changed. Since getting URL before URL change performs as expected, I don't think Electron is fundamentally different when setting URL.

**Comment by christian-bromann** [comment]
Can you paste in some Selenium logs?

**Comment by lseongjoo** [comment]
Can you please point a ref how I can produce the logs?

**Comment by christian-bromann** [comment]
Sure, how do you run your Selenium server?

**Comment by lseongjoo** [comment]
```
chromedriver --url-base=/wd/hub --port=9515
```

**Comment by christian-bromann** [comment]
cool, just start chromedriver this way:

```js
chromedriver --url-base=/wd/hub --port=9515 --log-path=chromedriver.log
```

run the test and attach the log file to this thread

**Comment by lseongjoo** [comment]
I have produced log and pasted seemingly relevant parts as below. The log shows that first COMMAND GetUrl produces RESPONSE GetUrl. But The second COMMAND GetUrl does not receive RESPONSE until timeout.

```
[2.146][INFO]: Launching chrome: ../codebasic_client/dist/CodeBasic-darwin-x64/CodeBasic.app/Contents/MacOS/Electron --disable-background-networking --disable-client-side-phishing-detection --disable-component-update --disable-default-apps --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-web-resources --enable-logging --ignore-certificate-errors --load-extension=/var/folders/zx/sy2_rths0_vbqd4smg627p400000gn/T/.org.chromium.Chromium.OtDEyS/internal --log-level=0 --metrics-recording-only --no-first-run --password-store=basic --remote-debugging-port=12550 --safebrowsing-disable-auto-update --safebrowsing-disable-download-protection --test-type=webdriver --use-mock-keychain --user-data-dir=/var/folders/zx/sy2_rths0_vbqd4smg627p400000gn/T/.org.chromium.Chromium.kb871V data:,
[3.672][INFO]: RESPONSE InitSession {
   "acceptSslCerts": true,
   "applicationCacheEnabled": false,
   "browserConnectionEnabled": false,
   "browserName": "chrome",
   "chrome": {
      "userDataDir": "/var/folders/zx/sy2_rths0_vbqd4smg627p400000gn/T/.org.chromium.Chromium.kb871V"
   },
   "cssSelectorsEnabled": true,
   "databaseEnabled": false,
   "handlesAlerts": true,
   "hasTouchScreen": false,
   "javascriptEnabled": true,
   "locationContextEnabled": true,
   "mobileEmulationEnabled": false,
   "nativeEvents": true,
   "platform": "Mac OS X",
   "rotatable": false,
   "takesHeapSnapshot": true,
   "takesScreenshot": true,
   "version": "43.0.2357.65",
   "webStorageEnabled": true
}

...

[3.721][INFO]: COMMAND GetUrl {

}
[3.721][INFO]: Waiting for pending navigations...
[3.924][INFO]: Done waiting for pending navigations
[3.943][INFO]: Waiting for pending navigations...
[3.943][INFO]: Done waiting for pending navigations
[3.943][INFO]: RESPONSE GetUrl "file:///Users/seongjoo/Documents/development/codebasic/codebasic_client/dist/CodeBasic-darwin-x64/CodeBasic.app/Contents/Resources/app/views/index.html"

...

[6.387][INFO]: COMMAND ClickElement {
   "id": "0.9885257398709655-3"
}
[6.387][INFO]: Waiting for pending navigations...
[6.387][INFO]: Done waiting for pending navigations
[6.441][INFO]: Waiting for pending navigations...
[6.441][INFO]: Done waiting for pending navigations
[6.441][INFO]: RESPONSE ClickElement
[6.446][INFO]: COMMAND GetUrl {

}
[6.446][INFO]: Waiting for pending navigations...
[6.446][INFO]: Done waiting for pending navigations
```

**Comment by christian-bromann** [comment]
I see, ok I guess there is not much I can do about this as it is clearly a bug in chromedriver. I would recommend to submit [an issue](https://sites.google.com/a/chromium.org/chromedriver/help) so the bug can get fixed.
For your test: you could try to get the url using `window.location`:

```js
client.execute(function() {
    return window.location.href;
}).then(function(url) {
    console.log('URL is', url);
});
```

If this works out for you, just write a custom command that does this and you should be all set.

**Comment by lseongjoo** [comment]
Thank you, Christian. With your help, I can now see that it is chromedriver issue. I will submit this as chromedriver issue. 

The script produces the same result. After URL change, chromedriver does not produce RESPONSE while before URL change it does produce RESPONSE. I think this is in general chromedriver's window.location setting issue.

**Comment by christian-bromann** [comment]
Ok, closing this issue then.

**Comment by lseongjoo** [comment]
I've submitted this issue as [issue 1207](https://goo.gl/N3921G)

**Comment by christian-bromann** [comment]
:+1: thanks!

**Comment by onassar** [comment]
Just stumbling on this now. Is there a safe/expected way of accessing the URL of a remote URL of a `BrowserWindow` instance?
