### ISSUE TITLE
Native Methods doesn't seems to work with html5/Angular apps

### ISSUE THREAD

**Issue by splurgeop** [webdriverio/webdriverio#7402]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [ 7.7.3]
 - **Mode:** [ WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:** [ 14.16.1]
 - **NPM version:** [7.20.5]
 - **Browser name and version:**  chrome 93
 - **Platform name and version:** [Windows 10]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
i have an angular application with html5.
i have noticed  few examples like  the input box has the html like this

`<input _ngcontent-cgc-c281="" type="text" name="baseUrl" formcontrolname="baseUrl" id="baseUrl" class="k-textbox k-widget ng-untouched ng-pristine ng-valid" size="10">`

if you notice that it doesn't have any value attribute associated with it.
Now when i am using  the basic wdio code like 
await $("Xpath Value of the input box").getValue();
i am always getting a blank value.
tried  getproperty('value') as well but the same result.
i have more controls where the value is not explicitly specifed in the DOM and using the getvalue is returning empty string.

**<input _ngcontent-cgc-c281="" type="text" name="baseUrl" formcontrolname="baseUrl" id="baseUrl" class="k-textbox k-widget ng-untouched ng-pristine ng-valid" size="10">**

**To Reproduce**
Naviage to html 5 angular apps
try to get value of text box

[Include code or an example repository that can easily be set up]

**Expected behavior**
the native wdio functions shouldd work

**Log**

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
@splurgeop what Angular version is that and do you have any example in the wild that I can use to test?

**Comment by splurgeop** [comment]
angular version 11.
my application is not acessible outside. but  if i look at the implementatin of getvalue
 https://webdriver.io/docs/api/element/getValue
 the value is a property here.
  whereas in my case it doesnt.
  
  here is another angular app
  https://creadoor.co.uk/search
  which can be tried

**Comment by erwinheitzman** [comment]
Some more context would be helpful, like does it have a value when you manually type something into said element? If not, then this is not an issue with the command (there's no value so it cannot be used) but rather the input element is used in a different way. For example, sometimes the input element is just a placeholder and another element has the actual value (not as I'm attribute but as in string value).

**Comment by splurgeop** [comment]
The "value" attribute is not present irrespective of manual or automation.
if you take a look at the  url 
https://creadoor.co.uk/search

and if you enter something in the search box you wont see the "value" attribute.
I can understand the getValue is for value attribute but is there any way out that we can get the text attribute.
throught js if i get the value  
`browser.execute(argument[0].value, elem)`

this works.
Just wondering if this is something can be added to webdriver to deal with this

**Comment by christian-bromann** [comment]
@splurgeop I have this simple test:
```js
const { remote } = require('webdriverio')

let browser

const opts = {
    capabilities: {
        browserName: 'chrome'
    }
}

;(async function () {
    browser = await remote(opts)
    await browser.url('https://creadoor.co.uk/search')
    await browser.$('#input-58').setValue('foobar')
    console.log(await browser.$('#input-58').getValue())

    await browser.deleteSession()
})().catch(async (e) => {
    console.error(e.stack)
    await browser.deleteSession()
})
```

And it returns successfully the value of the input for both, running with CDP and WebDriver. Can you provide a reproducible example?
