### ISSUE TITLE
defaultViewport is NOT working for Chrome ONLY

### ISSUE THREAD

**Issue by 1MaJKeL1** [webdriverio/webdriverio#7404]
When user has defined protocol as devtool and test are executed on Chrome then setup from defaultViewport is not valid, browser is opened in different resolution.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [7.12.2]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [14.17.2]
 - **NPM version:** [6.14.14]
 - **Browser name and version:** [Chrome 93]
 - **Platform name and version:** [Windows 10]

**Config of WebdriverIO**
`const browserConfig = {
  automationProtocol: 'devtools',
  capabilities: [
    {
      maxInstances: 1,
      browserName: Browser.CHROME,

      'wdio:devtoolsOptions': {
        headless: false,
        defaultViewport: {
            width: 800,
            height: 600,
            deviceScaleFactor: 1,
            isMobile: false
        }
    },

      "goog:chromeOptions": {
        args: ["--start-maximized", "--disable-infobars"],
        //args: ['--start-maximized', '--headless', '--disable-gpu'],
      },
      acceptInsecureCerts: true,
    },
  ],
  services: [
    //["devtool"],
    //["chromedriver"],
  ],
};`

**Describe the bug**

**To Reproduce**
Setup in config automationProtocol: 'devtools',
capabilities browserName: Chrome
define defaultViewport e.g. 
```
      'wdio:devtoolsOptions': {
        headless: false,
        defaultViewport: {
            width: 800,
            height: 600,
            deviceScaleFactor: 1,
            isMobile: false
        }
```
Execute any type of test just open browser and URL to see if viewport is adjusted to defined in config setup

**Result**
DefaultViewport is not applied to Chrome but it work well on Chromium bases EDGE

**Expected behavior**
DefaultViewport for devtool execution is applied to Chrome as well

**Comment by christian-bromann** [comment]
While we pass in the `wdio:devtoolsOptions` object directly into `puppeteer.launch` (see [here](https://github.com/webdriverio/webdriverio/blob/main/packages/devtools/src/launcher.ts#L160-L183)), we use the [`chrome-launcher`](https://www.npmjs.com/package/chrome-launcher) package because it can find the binary for us. Maybe we can use the Puppeteer launcher also for Chrome but we definitely need to make sure that Puppeteer settings are recognised by `chrome-launcher`.

**Comment by christian-bromann** [comment]
Applied a PR with a fix. Let's continue convo there.
