### ISSUE TITLE
To add to documentation the explicit Severity values accepted by Allure API

### ISSUE THREAD

**Issue by saranyaeaswaran** [webdriverio/webdriverio#7406]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Description of the improvement / report**
In section [Supported Allure API](https://webdriver.io/docs/allure-reporter/#supported-allure-api), `addSeverity(value)` has just the description to add the severity level to allure reporter. But this accepts only the values `blocker, critical, normal, minor, trivial` as per documentation from [Allure Runtime API](https://docs.qameta.io/allure/#_runtime_api) > allure.severity(severity). We should probably add these values to webdriverIO documentation to make it more clear to the user that only these values are accepted for the severity level.

I can do this change if this issue gets accepted.
![image](https://user-images.githubusercontent.com/46667193/132932696-c8e6cd4a-fd78-4ce3-be4e-120488935775.png)
![image](https://user-images.githubusercontent.com/46667193/132932740-41019bed-3079-4831-be74-c77bd01b9f97.png)

**Comment by christian-bromann** [comment]
@saranyaeaswaran you want to help us getting this updated? All you need to do is send a PR with changes to [this file](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-allure-reporter/README.md).

**Comment by saranyaeaswaran** [comment]
Yes @christian-bromann I will take up this! Thanks.

**Comment by christian-bromann** [comment]
Let's continue our conversation in #7420
