### ISSUE TITLE
Typescript typing for the world object

### ISSUE THREAD

**Issue by valentindoering** [webdriverio/webdriverio#7424]
Im using WebdriverIO with cucumber. With the setWorldConstructor method its possible to customize the world object, that is accessible within the cucumber step definitions. The function calls `this` to get the world. However the `this` in typescript has an any type. Would it be possible to provide an interface somehow for the world to make the typing cleaner?  At the moment its a little bit cumbersome, Im doing it like that:

```
interface IWorld {
methodOnTheWorld(): void;
}

Given(
  "you open the website",
  async function () {
    (this as IWorld).methodOnTheWorld();
  }
);
```
Thank you for your help.

**Comment by christian-bromann** [comment]
If you import `Given` from the Cucumber package you should have `IWorld` typed for `this` scope, e.g. I checked with the [Cucumber Boilerplate](https://github.com/webdriverio/cucumber-boilerplate) and it is exactly like that:
![Screenshot 2021-09-20 at 11 20 13](https://user-images.githubusercontent.com/731337/133980513-59ccb379-3465-4fdd-b88d-9606c49c0af9.png)

Not sure if something is not properly configured but it should work out of the box. Happy to re-open this if you can provide a reproducible example.

**Comment by dietergeerts** [comment]
@christian-bromann , but how can you add properties to that type though? I'm a bit struggling with it. It may be my TypeScript skills. I know you should be able to declare the same interface and TS should merge them, but I have no luck.
