### ISSUE TITLE
@wdio/sync 7.12.4 contains reference to fibers

### ISSUE THREAD

**Issue by Rashmi-nw** [webdriverio/webdriverio#7426]
Hi, 

**Environment (please complete the following information):**
 - **WebdriverIO version:** [7.12.4]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:** [16.8.0]
 - **NPM version:** [7.21.0]
 - **Browser name and version:** [93.0.4577.63]
 - **Platform name and version:** [Mac]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Describe the bug**
We are trying to update our solution to use Node 16.8.0

As suggested in https://webdriver.io/blog/2021/07/28/sync-api-deprecation/ , I have now upgraded to higher version of webdriver but wdio/sync is still using fibers package. 

**To Reproduce**
Include @wdio/sync@7.12.4 in packages.config
Run `npm ls @types/fibers`

**Expected behavior**
No reference to `fibers` should be found in https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-sync/package.json as it is not maintained

**Log**
node: ../src/coroutine.cc:134: void* find_thread_id_key(void*): Assertion `thread_id_key != 0x7777' failed.
Aborted (core dumped)

**Comment by christian-bromann** [comment]
> We are trying to update our solution to use Node 16.8.0

Please read our blog post on this: https://webdriver.io/blog/2021/07/28/sync-api-deprecation
