### ISSUE TITLE
direct connect behavior not implemented correctly

### ISSUE THREAD

**Issue by jlipps** [webdriverio/webdriverio#7427]
The current directConnect behavior appears to not be implemented correctly. It's defined here: https://github.com/webdriverio/webdriverio/blob/main/packages/webdriver/src/index.ts#L44-L52

It merely looks for directConnect information in the params, but it should be looking in the capability response from the new session request. That's the whole point--for a load balancer to be able to respond with specific direct server connection information in its new session response, so that subsequent requests can be faster. The current implementation is basically just a reimplementation of the hostname and port parameters that can already be passed in.

The test for this feature just tests the current behavior, which I think is incorrect. For an example of a correct implementation, check out [web2driver](https://github.com/projectxyzio/web2driver/blob/master/src/session.js#L34-L63)'s wrapping of webdriver.

(I discovered this issue when I went to remove web2driver's handling of this case because I thought webdriver already handled it).

**Comment by christian-bromann** [comment]
Thanks for reporting @jlipps , if these direct connect parameters are suppose to come from a session response then this is indeed wrong.

**Comment by jlipps** [comment]
Yes, that's the case. Here's a reference article: https://appiumpro.com/editions/86-connecting-directly-to-appium-hosts-in-distributed-environments

**Comment by jlipps** [comment]
The funny thing is I have some kind of memory of maybe implementing this myself for wdio? So maybe it got moved around and accidentally put somewhere else? Or maybe I am misremembering and I did not implement this feature in wdio.
