### ISSUE TITLE
How do i know when page is loaded?

### ISSUE THREAD

**Issue by lonfee88** [webdriverio/webdriverio#743]
Usually， when a button is clicked, the page will be redirected to another url. Rather than pause for a second or two, how do i know when the page is loaded?

**Comment by lonfee88** [comment]
@christian-bromann can you help me ?

**Comment by christian-bromann** [comment]
If you click on a button that opens another page Selenium will wait until the page gets loaded. There is no event that gets triggered. If you are using a framework like Angular or Ember I would recommend to use the waitForExist command in order to make sure that a specific element is available to continue the execution

**Comment by lonfee88** [comment]
Thank you so much

**Comment by testautomationacademy** [comment]
I created this function to handle this:
```    waitForUrlChange(url, waitTime) {
        browser.waitUntil(() =>
            browser.getUrl() === `${url}`,
            {
                timeout: waitTime, timeoutMsg: 'timeout: expected URL to be changed'
            }
        );
    }
```
it works great and waits until url is changed

**Comment by fusion2222** [comment]
In my opinion, all suggested approaches mentioned here are heavily flawed nad non-reliable.

Checking for URL to change or to rely on`waitForExists()` but does not guarantee elements will be initialized by application's javascript and therefore may be not interactable.

Ideal solution would be to wait until all Javascript and CSS is loaded and initialized, then perform any testing.

**Comment by christian-bromann** [comment]
> Ideal solution would be to wait until all Javascript and CSS is loaded and initialized, then perform any testing.

This is exactly what happens in WebDriver, as long as your [page load strategy](https://w3c.github.io/webdriver/#navigation) is set to normal which is the default.
