### ISSUE TITLE
Example from docs broken: this.getText is not a function

### ISSUE THREAD

**Issue by oldmankit** [webdriverio/webdriverio#7434]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.12.6
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 12.18.3
 - **NPM version:** 6.14.6
 - **Browser name and version:** Chrome 93
 - **Platform name and version:** Windows 10

**Config of WebdriverIO**
Followed defaults. Minimal example repository is here: https://github.com/oldmankit/wdio-minimal-example

**Describe the bug**
In the [help docs](https://webdriver.io/docs/api/element/waitUntil) there is the following example:
```
it('should wait until text has changed', async () => {
    const elem = await $('#someText')
    await elem.waitUntil(async () => {
        return (await this.getText()) === 'I am now different'
    }, {
        timeout: 5000,
        timeoutMsg: 'expected text to be different after 5s'
    });
});
```

When I run that I get the following error: `waitUntil condition failed with the following reason: this.getText is not a function`

**To Reproduce**
Clone https://github.com/oldmankit/wdio-minimal-example
npx wdio

**Expected behavior**
I would expect both tests to pass.

**Additional context**
I'm new to webdriver IO so could have misunderstood something fundamental here.

**Comment by christian-bromann** [comment]
Updated the docs, the example should be:
```js
    it('should wait until text has changed', async () => {
        const elem = await $('#someText')
        await elem.waitUntil(async function () {
            return (await this.getText()) === 'I am now different'
        }, {
            timeout: 5000,
            timeoutMsg: 'expected text to be different after 5s'
        });
    });
```

**Comment by oldmankit** [comment]
Thanks so much, @christian-bromann
