### ISSUE TITLE
[Feature][HELP] Parallel ,remote test execution

### ISSUE THREAD

**Issue by EINBOX** [webdriverio/webdriverio#7435]
Hello,
I am not sure this feature is possible or available with WebdriverIO, let me put my requirements here
 1. launch set of test cases on local browsers like chrome ,Mozilla,safari on Mac OS —> cross browser/parallel testing
 2. launch set of test cases on local <chrome,firefox,safari> and on mobile<chrome,firefox,edge> —>prallelly 
 3. launch set of test cases on mobile browsers <chrome,firfox,edge>
 4. launch set of test cases on android and iOS browsers —> parallel
 if yes, can you please share what kind of configuration is required and service type also

one more requirement, if I use allure report ? parallel test execution report will update in allure ? < I know its possible in extentReports>
To update parallel tests results on allure , do I need to handle at program level ? config file?

Thanks In advance

**Comment by christian-bromann** [comment]
Yes all of these requirements are possible with WebdriverIO. Please check our [documentation page](https://webdriver.io/) for more information. If something is missing, please let us know. There are hundred of different ways to setup mobile and desktop test execution. You can use Selenium Grid or a vendor like Sauce Labs. It is a bit out of scope for WebdriverIO to recommend a specific setup. There are plenty information on the internet that can help you here.
