### ISSUE TITLE
[HELP]] SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by EINBOX** [webdriverio/webdriverio#7438]
Please dont say follow the document, I did lot go search on google and in out forum. but nothing is fixed
I have created few page object files and written few methods ,when try to import them into my main file, am getting the above error.

wha to tried: as per google search and other places
1. add type as module in the config.js—did not work
2. add require: ['@babel/register'] in the wdio.shared.config did not work
3. some tother options
I know this is common error when I searched in google 
in my existing node js typescript , I have not encountered this kind of issues but here am getting this
experts please provide some solution to fix this.

**Comment by christian-bromann** [comment]
> 1. add type as module in the config.js—did not work

What is `config.js`? And what "type" did you add?

> 2\. add require: ['@babel/register'] in the wdio.shared.config did not work

With WebdriverIO v7 this is not needed at all.

If you have import statements in your tests and you want to use Babel please follow [our docs](https://webdriver.io/docs/babel).

Sorry there is nothing more I can do. The docs describe how to set this up. You also didn't provide a reproducible example that I can look into. I will close this as this doesn't seem to be an issue in WebdriverIO. For questions like this I also recommend to visit the Gitter support channel.

**Comment by EINBOX** [comment]
I wiil share my sample project

**Comment by wswebcreation** [comment]
@EINBOX 

Can you please first merge all the suggested changes from my PR before you proceed with this?

**Comment by EINBOX** [comment]
due to restrictions, I can't upload/download
I have created with all your suggestions new branch<manually>, please check it here
https://github.com/EINBOX/WDIOTestProject

**Comment by EINBOX** [comment]
Thank you for your support
its resolved after I used this way 
module.exports = new Top();

and const TOP = require('../pageObjects/top.page');
