### ISSUE TITLE
On desktop safari moveTo does not work on second page load in beforeEach block

### ISSUE THREAD

**Issue by Sam55555** [webdriverio/webdriverio#7453]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [7.7.8]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [async]
 - **Node.js version:** [14.15.0]
 - **NPM version:** [6.14.8]
 - **Browser name and version:** [Safari 14]
 - **Platform name and version:** [MacOS]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
On the page we have elements that have a hover effect. Before each _it-block_ with test we reload the page in the _beforEach-block_. By using _browser.url_ in the _beforeEach-block_ and _moveTo_ in the _it-block_ when executing the second _it-block_, _moveTo_ does not trigger a hover event.

**To Reproduce**

MoveToNotWorkingOnSecondLoad.zip
[MoveToNotWorkingOnSecondLoad.zip](https://github.com/webdriverio/webdriverio/files/7202932/MoveToNotWorkingOnSecondLoad.zip)

**Expected behavior**
_moveTo_ triggers the hover effect in each _it-block_ when the page has been reloaded in the _beforeEach-block_.

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
Two questions:

- what is `checkScreen` doing? It is not possible to run the code like this
- why do you overwrite `releaseActions`? Have you tried without overwriting it?

**Comment by Sam55555** [comment]
- checkScreen is a function of https://github.com/wswebcreation/wdio-image-comparison-service, can be replaced by saveScreenshot
- without overriding, the hover effect does not work on Safari, because releaseAction removes the hover effect, ticket added by apple

**Comment by christian-bromann** [comment]
> * ticket added by apple

Can you reference it here.

So if we know that actually this is a problem with Safari, why do we have to have this ticket then? You applied a workaround so it works in Safari but now it doesn't work in other browser. Shall we rather wait for Safari to fix this issue or can you apply your overwrite only if you run Safari tests?

**Comment by Sam55555** [comment]
This is a different problem, currently there is only the problem that there is no hover effect in the second it-block after reloading the page.

**Comment by christian-bromann** [comment]
Please help us investigate in the issue. I can't promise that anyone from the maintainer team can look into this anytime soon.

**Comment by christian-bromann** [comment]
@Sam55555 any updates?

**Comment by Sam55555** [comment]
@christian-bromann currently no updates, we overriding 'moveTo' and 'releaseAction' commands as workaround for safari desktop

**Comment by ArminazK** [comment]
Hello, just wanted to give my 2 cents here.
To make`moveTo` to work in safari, you need:
* overwrite/change `pefromActions` to NOT to `releaseActions` in the end
* this means that cursor remains on the same spot on the second test run, so move the cursor away to some 'inital' spot before each safari hover (e.g. I use selector 'body')
*  sometimes this does not work on minimised browser...

Hope it helps

**Comment by Sam55555** [comment]
> Hello, just wanted to give my 2 cents here. To make`moveTo` to work in safari, you need:
> 
> * overwrite/change `pefromActions` to NOT to `releaseActions` in the end
> * this means that cursor remains on the same spot on the next run (thats why it fails on second run), so move the cursor away to some 'initial' spot before each safari hover (e.g. I use selector 'body')
> * sometimes this does not work on minimised browser...
> 
> Hope this helps

We override `moveto` because of the second fix for Safari caused by scrolled pages, where Safari gives wrong calculations for scrolled pages and `moveto` does not work after scrolling. For hover you can do both: empty `releaseActions` or full `pefromActions` overrides.

**Comment by christian-bromann** [comment]
> * overwrite/change `pefromActions` to NOT to `releaseActions` in the end

The `performActions` command doesn't do a `releaseAction` command, it is up to you to call it or not.

I am not sure at this point what we can do to fix this issue in WebdriverIO. Therefor I am closing this, however if anyone has suggestions to improve the experience I am happy to re-open and discuss.

Thanks for the insights @ArminazK
