### ISSUE TITLE
cucumber js world context is undefined in hooks.ts

### ISSUE THREAD

**Issue by czdaniel** [webdriverio/webdriverio#7454]
# Issue description
cucumber js world context is undefined in hooks.ts

# Steps to reproduce
`beforeHook: function (test, context, stepData, world) {console.log(world)},` in hooks.ts

# Expected behavior
I expect I'd log the world context of my cucumber tests

# Actual behavior
the output is undefined.

# Issue occurred on browser/platform 
selenium, wdio, cucumber framework. Didn't modify anything else about the project.

**Comment by christian-bromann** [comment]
The world variable needs to be added [here](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-cucumber-framework/src/index.ts#L370-L371). Any contribution to this are appreciated.

**Comment by christian-bromann** [comment]
Fixed in #7475
