### ISSUE TITLE
Allure Report Usage ES5 example uses object destructuring format but the code example is not

### ISSUE THREAD

**Issue by saranyaeaswaran** [webdriverio/webdriverio#7459]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [x] A typo
- [ ] Missing documentation
- [ ] Other

**Description of the improvement / report**

Allure Report Usage ES5 example [here](https://webdriver.io/docs/allure-reporter/#usage) uses object destructuring format 
```
const { addFeature } = require('@wdio/allure-reporter').default
```
but the Mocha code example mentioned in the  documentation is specific to ES6 example of Allure API usage. Instead, can we correct the ES5 code example to below?
```
const allureReporter = require('@wdio/allure-reporter').default
```
This might help somebody who's new to JS and WebdriverIO.

**Comment by christian-bromann** [comment]
@saranyaeaswaran thanks for reporting. If this makes the example for clear I am all for it. Mind tackling this as part of #7420 ?

**Comment by saranyaeaswaran** [comment]
Sure, I will push this change as part of #7420.

**Comment by christian-bromann** [comment]
Added a comment in #7420, will close this one.
