### ISSUE TITLE
wdio debug and run mode

### ISSUE THREAD

**Issue by EINBOX** [webdriverio/webdriverio#7460]
I am trying to setup debug mode of wdio run but not at all working 
can some help me to run our test cases using wdio test runner ?
I tried below ways: 
in case of below set up , we need to setup as specs:[
    **"../test/specs/**/*.js"**
],
but for npm run test 
specs:[
    **"./test/specs/**/*.js"**
],
![image](https://user-images.githubusercontent.com/57449767/134329090-6e2d6e5d-7023-440a-bdf8-a2590b408c17.png)

please help me a good config where we can run our test case in debug mode

if I go with above setup which is mentioned in the screenshot, its able to find specs or appium services or selenium services

**Comment by christian-bromann** [comment]
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
