### ISSUE TITLE
Junit Reporter add "time" to testsuites element

### ISSUE THREAD

**Issue by rikbrowning** [webdriverio/webdriverio#7463]
**Is your feature request related to a problem? Please describe.**
On the `testsuites` element there is a time attribute that can be added containing the total time the test suites took to run. I am trying to leverage https://github.com/dorny/test-reporter to have the results display in our CI run but having the missing time attribute is causing it to fail.

**Describe the solution you'd like**
`testsuites` element should have a time attribute

**Comment by christian-bromann** [comment]
@rikbrowning this is currently not available in `junit-report-builder`, can you plead your case in https://github.com/davidparsson/junit-report-builder/issues/8 ? Thanks!

**Comment by christian-bromann** [comment]
I will go ahead and close this one as it seems that there is nothing actionable here. If `davidparsson/junit-report-builder` decides to support this I am fine adding it in WebdriverIO as well but it seems it isn't common for junit reports to have many properties on the `testsuites` level.
