### ISSUE TITLE
Sample Typescript project get generated without tsconfig file

### ISSUE THREAD

**Issue by praveendvd** [webdriverio/webdriverio#7468]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2] :  7.13.1
 - **Mode:** [Standalone mode or WDIO Testrunner] : Test runner
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async] : Async
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service] : @wdio/cli

**Describe the bug**

On creating sample typescri[t project with @wdio/cli , it does not create tsconfig.json file automatically. This results in type error for global objects like browser , $ etc .

**To Reproduce**

  run `npx wdio`
  generate sample jasmine-typescript (or other typescript ) project

**Expected behavior**

basic tsconfig.json file should be created and the project should run without any type error

**Log**

![image](https://user-images.githubusercontent.com/45095911/134598566-eb008ae1-ce93-449c-8b66-99816d175b54.png)

**Required tsconfig**

```
{
    "compilerOptions": {
        "types": ["node", "webdriverio/async","@wdio/jasmine-framework"],
        "target": "ES6"
    }
    
}
```

**Comment by christian-bromann** [comment]
I suggest to check if a `tsconfig.json` is existing and if not create a minimal required one as you suggested there.

**Comment by praveendvd** [comment]
> I suggest to check if a `tsconfig.json` is existing and if not create a minimal required one as you suggested there. The code for this needs to be written [here](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-cli/src/commands/config.ts). If there are any questions, please let me know.

Thank you so much  @christian-bromann  will pick this up , then .

**Comment by christian-bromann** [comment]
Thanks for taking a stab at this. Let's continue conversation in #7471
