### ISSUE TITLE
browser.takeScreenshot() does not take screenshots for Allure reporter 

### ISSUE THREAD

**Issue by atilajanosi** [webdriverio/webdriverio#7469]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [7.13.1]
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [async]
 - **Node.js version:** [16.4.1]
 - **NPM version:** [7.19.1]
 - **Browser name and version:** [safari 14.1.2, chrome 92.0.4515.159]
 - **Platform name and version:** [macOS Big Sur 11.5.2 ]
 - **Additional wdio packages used (if applicable):** ["@wdio/allure-reporter": "^7.13.0"]

**Describe the bug**
When running the test with allure reporter configured(with screenshots) the screenshots(.png images) are not being generated. 
Documentation used: https://www.npmjs.com/package/@wdio/allure-reporter 

**To Reproduce**
Precondition:
In wdio.conf.js set reporter: 
```
reporters: [
        'spec',
        ['allure', {
            outputDir: 'allure-results',
            disableWebdriverStepsReporting: true,
            disableWebdriverScreenshotsReporting: false,
            disableMochaHooks: false
        }],
],
```
and 

```
afterTest: function (test, context, { error, result, duration, passed, retries }) {
        console.log('After test')
        browser.takeScreenshot();
},
```

Steps:
1. create a test that opens the web page
2. observe the results in allure-reports folder

**Expected behavior**
No screenshot is being generated in the allure-reports folder. Screenshots are not being generated. 

**Additional context**
have tried with: 
`browser.saveScreenshot(location)`
and the screenshot for this particular scenario is generated so the code should be ok. 

Adding raw allure-reporter package and setting up everything in _before()_ method creates everything as expected.

**Comment by christian-bromann** [comment]
Thanks for reporting. Any contributions on this would be appreciated. Thanks!

**Comment by praveendvd** [comment]
@christian-bromann  its because of not using awai

```
afterTest: async function (test, context, { error, result, duration, passed, retries }) {
        console.log('After test')
        await browser.takeScreenshot();
},
```

**Comment by praveendvd** [comment]
If this autogenerated then we could fix adding async and await to all hooks in config file .

**Comment by christian-bromann** [comment]
good catch @praveendvd .. we don't have this autogenerated.

@atilajanosi please see solution above.

**Comment by atilajanosi** [comment]
Hi, this solution does not change anything(just tried it once again). I forgot to mention in the issue that i have tried with async.

**Comment by atilajanosi** [comment]
It works, confirmed. Thanks
