### ISSUE TITLE
[HELP] get style of html elment 

### ISSUE THREAD

**Issue by EINBOX** [webdriverio/webdriverio#7473]
I am facing an issue to fetch font size from html elements which resides within iframe 
having couple queries 
1. get active iframe which is in the current page
2. get html elements attributes like style to fetch font size
3.
Source : please refer the attached screen shot
const iFramesCount=iframes.length
            console.log("frame count:"+iFramesCount)
            browser.switchToFrame(iframes[0]) —> thought 1st frame is active frame In the page
            const pageSource=browser.getPageSource();
            console.log("page source:"+pageSource)—> returns as undefined
            const html=await browser.$('html')
            const style=await html
            console.log("html body:"+html2.body) —> returns undefined
            console.log("html body after font increase :"+html2.getAttribute("style")) —> returns undefined 
![image](https://user-images.githubusercontent.com/57449767/134869084-c171f4ff-0ce1-46e1-bbc5-29cf32dfaa22.png)

**Comment by christian-bromann** [comment]
@EINBOX you are now using `await` for all commands. You can get the style of an element using [`getElementCSSValue`](https://webdriver.io/docs/api/webdriver#getelementcssvalue).

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by EINBOX** [comment]
Thank you @christian-bromann
 I will try and let you know
