### ISSUE TITLE
Using failFast jasmine option causes jasmine options issue

### ISSUE THREAD

**Issue by DirkoOdendaal** [webdriverio/webdriverio#7474]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.13.0 - But issue present in earlier options too
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync and async
 - **Node.js version:** 14.17.5
 - **NPM version:** 7.20.6
 - **Browser name and version:**  Chrome 94
 - **Platform name and version:**  Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/spec-reporter, @wdio/local-runner, @wdio/jasmine-framework, @wdio/sauce-service, @wdio/sync

**Config of WebdriverIO**
config = {
    runner: 'local',
    specs: [
        './test/specs/**/*.js'
    ],
    maxInstances: 4,
    logLevel: 'error',
    deprecationWarnings: false,
    bail: 2,
    baseUrl: 'https://www.saucedemo.com/',
    waitforTimeout: 10000,
    specFileRetries: 1,
    connectionRetryCount: 2,
    framework: 'jasmine',
    reporters: ['spec'],
    jasmineOpts: {
        defaultTimeoutInterval: 60000,
        isVerbose: false,
        oneFailurePerSpec: true,
        failFast: true
    },
    services: []
}

**Describe the bug**
When setting failFast to true, you get a error that you can't use failFast and stopOnSpecFailure together, even if you don't set stopOnSpecFailure yourself.

Error: stopOnSpecFailure and failFast are aliases for each other. Don't set failFast if you also set stopOnSpecFailure.

**To Reproduce**
Just set failFast to true in jasmineOpts.
Sample repository to replicate it here: 
https://github.com/DirkoOdendaal/webdriverio-jasmine

**Expected behavior**
Setting failFast in your jasmineOpts should stop execution of the suite after the first spec failure. 

**Log**
https://gist.github.com/DirkoOdendaal/31319bf1b438f09e8eaef273840c0039

> Please use the correct markdown

**Comment by christian-bromann** [comment]
`failFast` is deprecated in Jasmine. I pushed a commit to make this more clear.
