### ISSUE TITLE
WaitForExist

### ISSUE THREAD

**Issue by linn84** [webdriverio/webdriverio#749]
I'm trying to automatically login with two different users in two separate windows. To wait for the windows to load I'm using waitForExist, but this doesn't work.

Below is some of my code:

```js
var browser = webdriverio.multiremote({
    chrome1 : {
        desiredCapabilities : {
	    browserName : 'chrome'
	}
    },
    chrome2 : {
	desiredCapabilities : {
	    browserName : 'chrome'
	}
    }
});

function logIn() {
    chrome1.waitForExist('#btnLogin').then(function() {
        chrome1.setValue('#logUsername', 'a@a.com').setValue('#password', 'a').click('#btnLogin');
});
```

If I add a delay and don't use waitForExist() it works, so the button do really exist when the window is fully loaded.

**Comment by christian-bromann** [comment]
What do you mean with it doesn't work?

**Comment by linn84** [comment]
Is there a way to delete this issue? Last week when I tried waitForExist it didn't wait.. Today when someone in my team had changed the buttonId during the weekend it suddenly works as it's supposed to. =)
