### ISSUE TITLE
Can you tell us how to use WebdriverIO with Chrome (not the Canary)?

### ISSUE THREAD

**Issue by KennethKinLum** [webdriverio/webdriverio#7498]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [x] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Description of the improvement / report**
The section https://webdriver.io/docs/gettingstarted#run-in-a-script
would open up Google Chrome Canary.  Could you tell us and perhaps add in the docs how to not run with Canary but the standard Chrome?

By the way, I just tried: if I first run
```
npm install -g chromedriver
chromedriver --port=4444 --verbose
```
then it'd start Chrome.  But if I don't run it, then it'd start Chrome Canary.  Not sure if it is related to me trying Selenium and installing chromedriver binary earlier.  (on https://chromedriver.chromium.org/ )

P.S. I found that the reason may be, if the `chromedriver` isn't running by the command above, then it may be Puppeteer that is running.  And on https://github.com/puppeteer/puppeteer :

> Puppeteer is a Node library which provides a high-level API to control Chrome or Chromium over the DevTools Protocol. Puppeteer runs headless by default, but can be configured to run full (non-headless) Chrome or Chromium.

But it seems headless doesn't mean Canary -- it means without displaying the browser on the screen?
Maybe you can add a line as to, how do we start Chrome (non Canary) from the interface of WebdriverIO?

**Comment by praveendvd** [comment]
You can start the service using chromedriver service.

**Comment by KennethKinLum** [comment]
> You can start the service using chromedriver service.
> 
> https://webdriver.io/docs/wdio-chromedriver-service/

can you use Puppeteer and be able to use Chrome and not Canary?
I tried 
```js
  const browser = await remote({
    capabilities: {
      browserName: "chrome",
      browserVersion: "94.0",
    },
  });
```
but it doesn't work.

**Comment by praveendvd** [comment]
> > You can start the service using chromedriver service.
> > 
> > https://webdriver.io/docs/wdio-chromedriver-service/
> 
> can you use Puppeteer and be able to use Chrome and not Canary?
> I tried 
> ```js
>   const browser = await remote({
>     capabilities: {
>       browserName: "chrome",
>       browserVersion: "94.0",
>     },
>   });
> ```
> but it doesn't work.
> 
Could you try passing binary argument to show which chrome binary to use , You can pass chrome or chrome canary as you want

**Comment by christian-bromann** [comment]
I added some docs that shed more light in this. If you don't have a browser driver running WebdriverIO falls back using the DevTools protocol and Puppeteer. It seems that Puppeteer launches Canary for some reasons but as @praveendvd pointed out you can set the chrome binary to point to Chrome. I added some docs related to Chrome specific options as well.
