### ISSUE TITLE
Debug nodejs process while test running

### ISSUE THREAD

**Issue by bartq** [webdriverio/webdriverio#750]
I'd like to set a beakpoint in my test and then use my WebStorm IDE powers to live execute code and play around. But it seems that specs files are loaded in a special way therefore debugger API is not notified that breakpointed line in my file was reached. 
Probably I'd like to have my spec files to be loaded by `wdio` script as normal CommonJS modules. Is it possible?

**Comment by christian-bromann** [comment]
@bartq have you tried to use http://webdriver.io/api/utility/debug.html? It is kind of a breakpoint thing. It stops the execution flow and allows you to jump into the browser to use dev tools for analysing elements.

**Comment by bartq** [comment]
I didn't try that :) Will take a look. 
But I'd like to use native WebStorm capabilities like this: http://blog.jetbrains.com/webide/files/2011/11/NodeJSDebugging.png. Looks like it's not possible with webdriverio now.

**Comment by christian-bromann** [comment]
We have already an open issue for [improving nodejs debugging](https://github.com/webdriverio/webdriverio/issues/459) so I will close this one. I've never needed to debug in nodejs for my tests. I guess (correct me if I am wrong) for e2e tests the easiest solution is to use console and check the Selenium logs.

**Comment by christian-bromann** [comment]
Debugging ability just got published with v4.0.9. For info see http://webdriver.io/guide/testrunner/debugging.html.
