### ISSUE TITLE
No docs for browser.deleteSession()

### ISSUE THREAD

**Issue by KennethKinLum** [webdriverio/webdriverio#7502]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [x] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Description of the improvement / report**
I can find https://webdriver.io/docs/api/browser/deleteCookies/
but it seems there is no docs for `deleteSession()` ?
also there is no such call like Selenium as browser.close() or browser.quit() ... Maybe the details can be added to the docs.

**Comment by praveendvd** [comment]
https://webdriver.io/docs/api/webdriver/#deletesession

Hi the driver quit , delete session are not generic browser methods , they are protocol depended . So if the browser instance is a webdriver protocol , these commands will also be available .

**Comment by christian-bromann** [comment]
> also there is no such call like Selenium as browser.close() or browser.quit()

Why should there be such commands. WebdriverIO is an independent implementation of the WebDriver protocol.
