### ISSUE TITLE
Add ability to override classname

### ISSUE THREAD

**Issue by facusantillo** [webdriverio/webdriverio#7521]
jest-junit has the ability to override the classname attribute on the testcase.

This is really useful on cases where the XML is consumed by a service that sanitizes duplicates.

If the classname is exactly the same due to configuration on environments, then we lose some of the reports.

**Comment by christian-bromann** [comment]
@facusantillo thanks for reporting the issue.

Can you explain in more detail how current junit reports in WebdriverIO look like and how you suggest user should be able to overwrite them?

**Comment by facusantillo** [comment]
@christian-bromann 

Current XML tag is created like 

`<testcase classname="DeviceOrBrowser_-_Describe_Name" name="TestOrITfromMochaOrJest" time="76.992">`

Jest junit allows users to override the format on the className using an options parameter.

User should be able to do it by overriding the className with an option parameter as well.

It could be something like:

`// wdio.conf.js
module.exports = {
    // ...
    reporters: [
        'dot',
        ['junit', {
            outputDir: './',
            outputFileFormat: function(options) { // optional
                return `results-${options.cid}.${options.capabilities}.xml`
            },
            classNameTemplate: 'GIVEN TEMPLATE'
        }]
    ],
    // ...
};`

**Comment by christian-bromann** [comment]
> classNameTemplate: 'GIVEN TEMPLATE'

How is this suppose to work? The `className` needs to contain test and device data, it can't just be a string. Maybe I don't fully understand, can you elaborate?

**Comment by facusantillo** [comment]
In Jest reporter you can pass a string that is going to be used as a the className.
Here is an example:

```
reporters: [
        'default',
        [
            'jest-junit',
            {
                suiteName: 'jest tests',
                output: 'junit.xml',
                outputDirectory: './junit',
                classNameTemplate: '{classname} - {title}',
                titleTemplate: '{classname} - {title}',
                ancestorSeparator: ' › ',
                suiteNameTemplate: '{filename}'
            }
        ],
]
```

As I pointed, this is specially useful for parsers and sanitization of duplicates in test suites.

wdio-junit-reporter doesn't have this ability, resulting in some inner login handling how the className is being presented in the XML and causing some errors in tools that we use for parsing the XML into more detailed reports.

**Comment by christian-bromann** [comment]
I understand and agree with these assumptions. Just wanted to get clarity on what you were reporting. I only disagree with the approach:

```js
classNameTemplate: '{classname} - {title}',
```

Doesn't seem right to me because it would be hard to document what "variable" replaces which value. Therefor I suggest to what `outputFileFormat` does and expect a function with certain objects as parameters that will help compile the string.

Any contributions to this would be appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by facusantillo** [comment]
Agree, a function would work better. Thanks for tagging it.
