### ISSUE TITLE
Wdio V7 throws error as soon as you add any services in wdio config file

### ISSUE THREAD

**Issue by skamineni** [webdriverio/webdriverio#7531]
Hi,
  We are trying to upgrade from V6 to V7. We are using V7.14.1 . We are blocked in the upgrade process in our org. Can someone please help.

1. As soon as I add services: []selenium-standalone] gives error as below when running tests:
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/18192016/136603703-179f7a4f-d6cc-4960-b11f-d19b8a29fae3.png">

2. As soon as I remove the services. Tests work fine falling back to puppeteer chrome.
3. Same way , as soon as I ass "sauce" service to run against sauce labs I get same error
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/18192016/136603649-a81b0595-588e-44bf-b1ef-c2cbcbb9872b.png">

**Comment by skamineni** [comment]
This is my wdio config file

<img width="976" alt="image" src="https://user-images.githubusercontent.com/18192016/136718463-9b66b148-d3f3-4a25-b5ae-9b8909083262.png">

We use babel that in in before hook to compile our Dev files which are in babel V6
<img width="1461" alt="image" src="https://user-images.githubusercontent.com/18192016/136718496-de378cb4-0eb0-46df-a06a-dd9c076bf2fd.png">

Then the test is just do **browser.url(any URL is fine)** If I remove services section from wdio config file. Test executes fine.

We will get that error. Please let me know you need anything. I can give saucelabs URL too.

**Comment by skamineni** [comment]
This is my saucelabs config
<img width="995" alt="image" src="https://user-images.githubusercontent.com/18192016/136718622-b7f4e636-2dd7-4a07-8560-beb93e46aa22.png">


Both gives same error

**Comment by christian-bromann** [comment]
Your Babel setup is not correct. There is no need to import it as WebdriverIO does this automatically. See https://webdriver.io/docs/babel for more information.

**Comment by skamineni** [comment]
None of the cross browser like firefox and Safari are working as well. Adding services: [selenium-standalone] is bringing the error back

**Comment by christian-bromann** [comment]
Please see the error message. It seems that you are applying the property `superAdminEmail` to an option that only is allowed to have `http`, `https` or `http2`. Please check your configuration.
