### ISSUE TITLE
Allow real time reporting of reporters using WDIO Testrunner

### ISSUE THREAD

**Issue by kdp88** [webdriverio/webdriverio#7532]
**DD** 
this may be a duplicate(apologies if it is) i  did a search in all issues, found 25 closed issues that may relate to spec reporter in real time but couldnt find much information except for a comment that stated watchmode, i posted in gitter but no response as of yet so i just want to see if someone out there has found something i have yet to find regarding real time output of the spec being ran, I also searched all of gitter for solutions but came up short, i looked through the webdriverio documentation but couldnt find much info about real time reporters

**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when i have to wait until the end of the run to see output

**Describe the solution you'd like**
im coming over from protractor, and theres a npm package for real time reporters, id like to see something similar

**Describe alternatives you've considered**
I have done global searches inside gitter and saw some people put code in the afterStep but from my understanding that is used for cucumber or the framework im not using(which is jasmine). please keep me honest here!

**Comment by praveendvd** [comment]
![test](https://user-images.githubusercontent.com/45095911/138003550-91d70dfc-1fd7-4821-9c7a-66f2395d2c2e.gif)

**Comment by praveendvd** [comment]
> Can you raise a separate PR that shows something useful? Like `emulator-5554`

Sure

**Comment by christian-bromann** [comment]
> Do you think any other fix will be required

No, this looks good to me. Please add a unit test to it so we make sure we don't regress.

**Comment by praveendvd** [comment]
Lets continue discussion at : #7572
