### ISSUE TITLE
WDIO get stuck while switching to a new window in headless mode

### ISSUE THREAD

**Issue by srivishal1** [webdriverio/webdriverio#7545]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 6,7
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:** 14
 - **NPM version:** [e.g. 5.8.0]
 - **Browser name and version:** [e.g. Chrome 93,94]
 - **Platform name and version:**Windows

**Comment by djv1001** [comment]
Dang, I'm currently experiencing this in 7.24.0, in headless chrome. 

Switching to a new window then calling "browser.getUrl()" just hangs. 

Calling "browser.getUrl()" before switching works fine.

**Comment by HauLe17** [comment]
Same issue when switching to new window and getUrl, I think it commom issue.
