### ISSUE TITLE
How to Allow Camera and Mic Access in Chrome browser?

### ISSUE THREAD

**Issue by sureshkrishnannair** [webdriverio/webdriverio#7548]
I have to test an application  where every time when  login, the  alert for allowing Camera and Mic pops up.
This is blocking WebdriverIO to test such applications. 

I wonder if there is a solution that already exists .

Please consider this as a feature if that is not implemented yet ?

![image](https://user-images.githubusercontent.com/35076518/137205045-30e622c6-0690-46d3-b624-015db42f31fb.png)

**Comment by pmerwin** [comment]
Hmm I have an app where I test video conf ... I use these caps:

```
'goog:chromeOptions': {
                        args: [
                            // "--incognito",
                            "--enable-automation",
                            "--disable-popup-blocking",
                            "--disable-notifications",
                            "--disable-extensions",
                            "--browser-test",
                            "--use-fake-ui-for-media-stream",
                            "--use-fake-device-for-media-stream"
                        ],
                        ```
                        
                        I think using these : 
   "--disable-notifications",
                          "--use-fake-ui-for-media-stream",
                            "--use-fake-device-for-media-stream"
                            saves me from seeing that alert you are seeing?
