### ISSUE TITLE
Bring back id selector

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#7550]
### Discussed in https://github.com/webdriverio/webdriverio/discussions/7547

<div type='discussions-op-text'>

<sup>Originally posted by **RyanRedpath** October 13, 2021</sup>
Hi, 

Do WDIO support the mobile selector/locator "resource-id"? Until recently I have been using "accessibility-id" but a recent upgrade on React Native allowed our devs to set resource-id, but it does not appear to work - "InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session"

I noticed there is no mention of resource-id in the link below so wondered was this actually something wdio does not support? Like it does for say  accessibility-id?

https://webdriver.io/docs/selectors/#accessibility-id

http://appium.io/docs/en/commands/element/find-elements/index.html#selector-strategies

Thanks,
Ryan</div>

**Comment by christian-bromann** [comment]
> verified using the android test app from appium

Thanks for verifying. My suggestion was to have a `id` selector like we used to. So rather than writing `$("id=resource-id")` we write `$("#resource-id")`

**Comment by awhisler** [comment]
@christian-bromann I'm a little confused here - so when you add a testID in React Native it assigns it to `resource-id`
![image](https://github.com/webdriverio/webdriverio/assets/2396250/aaa53197-4638-4d31-9285-ad92940daa65)

But I cannot seem to figure out how to call it in WDIO or even additionally how to call it with the same selector for Android and iOS.

I have tried:
```
id=resource-id/PostalCode
#PostalCode
id=PostalCode
```

None of them work for Android, why?

Additionally, I tried adding accessibilityLabel (as you can see for`Postal_Code`) but that comes back as `label` for iOS
![image](https://github.com/webdriverio/webdriverio/assets/2396250/367eb8be-8191-4fc2-8f46-5c377df0b8ba)

**Comment by christian-bromann** [comment]
> None of them work for Android, why?

I really don't know, maybe a good idea to reach out to the Appium project.

**Comment by ChaseRehmV** [comment]
@awhisler @christian-bromann I was running into the same problem with resourceID and Appium/React-Native, but I got things working with the following selector syntax below. I'm using latest Appium 2 and WDIO.

driver.$('android=new UiSelector().resourceId("<myResourceID>")')
