### ISSUE TITLE
Test conditional logic running before "before" hook

### ISSUE THREAD

**Issue by rohantalkad747** [webdriverio/webdriverio#7553]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.14.1
 - **Mode:** WDIO Runner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 14
 - **Browser name and version:** Chrome 91
 - **Platform name and version:** OSX

**Config of WebdriverIO**
I have a before hook that needs to initialize data based on browser params

**Describe the bug**

I have some conditional logic to determine whether certain test suites will run. Basically, it decides whether to use describe or xdescribe (skips tests). This conditional logic checks the browser for some details. 

(browserFeatureEnabled(someFeature) ? describe : xdescribe)("My Test", () => { ...

However, I'm seeing that the checking is done BEFORE the browser is even instantiated (ie prior to the before hook running, but after onPrepare) so the tests are not running at all! I am using the Jasmine test framework. 

**To Reproduce**

1. Create  a before hook, console.log something. 
2. Create a test suite that executes conditionally based on something that happens after before hook.
e.g, (browserFeatureEnabled(someFeature) ? describe : xdescribe)("My Test", () => { ... });
3. You will find that the test conditional logic is executing prior to the before hook. 

**Expected behavior**

Test conditional logic executes after "before" hook.

**Comment by praveendvd** [comment]
Please  add a reproducible example , and the expected result
