### ISSUE TITLE
Unable to donwload latest selenium version 

### ISSUE THREAD

**Issue by amrsa1** [webdriverio/webdriverio#7557]
**Environment (please complete the following information):**
 - **WebdriverIO version:**  7.14.1
 - **Mode:** Standalone
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]async
 - **Node.js version:** 14
 - **NPM version:** 6.14.15
 - **Browser name and version:** 94
 - **Platform name and version:** Linux
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
   
```
           services: [['selenium-standalone',
            { 
                installArgs: {
                    version: '4.0.0',
                    baseURL: 'https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.0.0',
                    drivers: {
                        chrome: {
                            version: drivers.chrome.version,
                            baseURL: 'https://chromedriver.storage.googleapis.com',
                        },
                        firefox: {
                            version: drivers.firefox.version,
                        },
                    }
                },
                args: {
                    seleniumArgs: ['-host', 'localhost', '-port', '4455'],
                    drivers
                },
            }
        ]],
```

**Describe the bug**
Unable to use new GitHub URL for selenium version 4.0.0, as currently, existing method is appending extra parameters to the URL which doesn't exist 

**To Reproduce**
Use the config above

**Expected behavior**
Better handling for the GitHub URL for downloading selenium 4 jar 
`https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.0.0/selenium-server-4.0.0.jar`

**Log**

```
Error in "getDownloadStream". Could not download https://github.com/SeleniumHQ/selenium/releases/download   /selenium-4.0.0/4.0/selenium-server-4.0.0.jar
See more details below:
404 https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.0.0/4.0/selenium-server-4.0.0.jar
```

**Comment by Pandicool** [comment]
@amrsa1 are you able to run the selenium stand alone in different port ?
for me its showing error like.

ERROR @wdio/runner: Error: Failed to create session.
[0-1] Unable to connect to "http://localhost:4444/wd/hub", make sure browser driver is running on that address.
[0-1] If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.


**In my wdio config :** my configuration
services: [
    ['selenium-standalone', {
      args: {
        seleniumArgs: ["--host","localhost","--port", "7777"]
      }
    }]
  ],
  
  CC : @christian-bromann
