### ISSUE TITLE
Custom Reporter

### ISSUE THREAD

**Issue by zdfs** [webdriverio/webdriverio#758]
If I have a custom reporter, how can I get Webdriver.io to recognize it? Is there a way currently to do this?

**Comment by christian-bromann** [comment]
Nope, but this should be easy to add.

**Comment by christian-bromann** [comment]
Fixed and just release with `v3.2.2`

**Comment by christian-bromann** [comment]
I can't update webdriver.io atm due to deploy issues. I hope this will get fixed asap.
