### ISSUE TITLE
[📖 Docs]: Run in a script

### ISSUE THREAD

**Issue by nonopolarity** [webdriverio/webdriverio#7584]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Unclear documentation

### Description of the improvement / report

On this page: https://webdriver.io/docs/gettingstarted#run-in-a-script
Run in a script

It doesn't say how to have `expect` if it is in a script...
I can't find it in other places in the docs.

It seems if we use `npx wdio ./path/to/new/project` to create the project, then we have the `expect` in the file `test/specs/example.e2e.js`  but as a standalone script, we do not.

Can you make a section or a standalone script page that talks more about it?  It seems there is some difference also about `$` vs `browser.$`

For example, Playwright's very example is able to make use of `expect` already:
https://playwright.dev/docs/intro#first-test

so if not there in your first example, can you add a small section talking about using WebdriverIO as a standalone script (and have `expect`?)

P.S. later on, it seems it is `expect` when it is mocha or jasmine, but different when using cucumber.  So perhaps you can give an example of have WebdriverIO and mocha at the same time?  Can we just `yarn add mocha` and start using it?  Does it have the property that it will wait a few seconds before failing the test that some text is not there?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
I think we can close this. There is nothing actionable left here to do.
