### ISSUE TITLE
[📖 Docs]: about mocha, jasmine, cucumber vs jest

### ISSUE THREAD

**Issue by nonopolarity** [webdriverio/webdriverio#7589]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Missing documentation

### Description of the improvement / report

```markdown
when we initialize a WebdriverIO project using `npx wdio` it asked us to choose from one of:

1. mocha
2. jasmine
3. cucumber

can we use "jest" as well?  I did grep in the webdriverio project that there are many `jest.fn()` inside of mocha, jasmine, and cucumber files... so does that mean "jest" is always used, together with mocha, jasmine, or cucumber?  I though jest replaces jasmine or mocha... can the docs specify whether jest is used and how does it relate to mocha / jasmine?
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sidferreira** [comment]
@christian-bromann Sorry for my lack of knowledge in this subject, and maybe I'm missing the point, but, Jest seems to be way more capable in overall, especially if we think about describe.each and test.each. I would love to understand how exactly Jasmine and Jest are different in this case...

**Comment by christian-bromann** [comment]
There are some minor advantages of Jest and most of them can be worked around. Overall I think though that for many use cases, Jasmine does the same job particularly after we introduced `expect-webdriverio`. That said, if someone wants to build a framework adapter for Jest, I am happy to offer support for it.

**Comment by sidferreira** [comment]
@christian-bromann IMHO the starting point for a jest runner is to run 100% of what Jasmine does, in a dropin replacement vibe, and build up out of it. I'll try to spend some time on it... I just would like to know what would be the requirement to have it as a webdriverio package, in order to have more hands maintaining it...

**Comment by christian-bromann** [comment]
If you can add it to this repository without decreasing the test coverage level I am fine to add it to this core repository.

**Comment by sidferreira** [comment]
@christian-bromann fair and square!
