### ISSUE TITLE
Promise chain breaks when error occurs inside promise running multiple commands

### ISSUE THREAD

**Issue by lutzj82** [webdriverio/webdriverio#760]
The following obviously works:

    function test() {
      return driver.click('#elementId').pause(500);
    }

The following does not work:

    function testError() {
      return driver.isExisting('#someElement').then(function(isExisting) {
        if (isExisting) {
          return this.click('#someElement').pause(500);
        }
      }).then(function() {
        //do something else
      });
    }

The click fails because the element is not visible. The error is reported, but execution stops.
If i do the following, then it works:

    function testErrorWorking() {
      return driver.isExisting('#someElement').then(function(isExisting) {
        if (isExisting) {
          return this.click('#someElement');
        }
      }).then(function() {
        return this.pause(500);
      }).then(function() {
        //do something else
      });
    }

I'm not sure if this is expected behavior or not.  I feel like it should work and I shouldn't have to do single commands within a promise.
Thanks!

**Comment by christian-bromann** [comment]
This is expected (promise) behaviour. If click fails the onFulfilledHandler in then won't get executed because the previous promise wasn't fulfilled. It should work if you use `finally` instead.
