### ISSUE TITLE
WaitFor default value not being used by waitForxxx commands

### ISSUE THREAD

**Issue by BenHarrington** [webdriverio/webdriverio#761]
In the wdio.conf.js file from the examples:

// Default timeout for all waitForXXX commands.
    waitforTimeout: 10000,

The logs report 500ms is being used by default rather than this value.

**Comment by christian-bromann** [comment]
@BenHarrington wasn't able to reproduce this. Here is a simple test that proves it: https://gist.github.com/christian-bromann/b3c80bd2290fc5e38781

**Comment by drets** [comment]
not reproducible for me as well

**Comment by christian-bromann** [comment]
Closing this then. Feel free to reopen or reach us on gitter if you need help.
