### ISSUE TITLE
[📖 Docs]: Clarify that `@wdio/devtools-service` commands only work locally

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#7620]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Missing documentation

### Description of the improvement / report

Many people that use the `@wdio/devtools-service` commands are confused why they are seeing things like `browser.cdp is not a function`. Two things we should do:

- make clear that this service only works locally and why
- register these methods and throw a meaningful error message

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dagoud** [comment]
@christian-bromann I would like to start picking up issues and helping with the project - this looks like one I could pick up.

What is involved - would it be a case of adding a description to the top paragraph [here](https://webdriver.io/docs/devtools-service)?

Is it describing that it only works when using the Puppeteer protocol?

**Comment by christian-bromann** [comment]
> would it be a case of adding a description to the top paragraph [here](https://webdriver.io/docs/devtools-service)?

Yes. However more services, e.g. Selenium server v4 and cloud provider like Testingbot now support running CDP in the cloud so saying that this only works locally would not be quite right.

> * register these methods and throw a meaningful error message

I think having this would clear up most of the confusion. Once the service is initialised it should register all custom commands so they not fail with `function not defined`. If a connection to the Chrome DevTools Protocol couldn't be established it would be great if we can properly throw an error message for it.

**Comment by dagoud** [comment]
Ok cool thanks @christian-bromann - I will check out the repo and take a look
