### ISSUE TITLE
[📖 Docs]: Old readme links to `master` branch of this project

### ISSUE THREAD

**Issue by jpalmieri** [webdriverio/webdriverio#7628]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

A typo, Other

### Description of the improvement / report

The [old home](https://github.com/itszero/wdio-browserstack-service) for this project has an incorrect link to this repo: it points to the `master` branch, and this repo's trunk is now `main`. So, when someone finds `itszero/wdio-browserstack-service` via a search and follows it here, they see an [old history](https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-browserstack-service) of the  project (since `master` is months behind `main`).

I am unable to edit the readme for `itszero/wdio-browserstack-service` (since the project is archived), so I'm reaching out here.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
> I am unable to edit the readme for `itszero/wdio-browserstack-service` (since the project is archived), so I'm reaching out here.

I also can't update the old project. What would you suggest?

**Comment by jpalmieri** [comment]
ah, I guess I assumed someone would be able to update the old project.

I guess the other option might be to delete `master`: https://github.blog/changelog/2020-07-17-links-to-deleted-branches-now-redirect-to-the-default-branch/

**Comment by christian-bromann** [comment]
Done, thanks for the tip!
