### ISSUE TITLE
Error Argument of type packages/wdio-cucumber-framework/src/utils.ts

### ISSUE THREAD

**Issue by hanifahatiyabudianto** [webdriverio/webdriverio#7630]
I got an error at utils.ts
Argument of type '(row: TableRow) => { cells: string[]; }' is not assignable to parameter of type '(value: PickleTableRow, index: number, array: readonly PickleTableRow[]) => { cells: string[]; }'.
  Types of parameters 'row' and 'value' are incompatible.
    Type 'PickleTableRow' is missing the following properties from type 'TableRow': location, id
![image](https://user-images.githubusercontent.com/19193414/139808119-427ac5ab-6ccb-4378-9d86-b85f5a674376.png)

and, 
No overload matches this call.
  Overload 1 of 2, '(predicate: (value: string, index: number, array: string[]) => value is string, thisArg?: any): this is string[]', gave the following error.
    Argument of type '(key: keyof Capabilities.Capabilities) => boolean' is not assignable to parameter of type '(value: string, index: number, array: string[]) => value is string'.
      Types of parameters 'key' and 'value' are incompatible.
        Type 'string' is not assignable to type 'keyof Capabilities'.
  Overload 2 of 2, '(predicate: (value: string, index: number, array: string[]) => unknown, thisArg?: any): boolean', gave the following error.
    Argument of type '(key: keyof Capabilities.Capabilities) => boolean' is not assignable to parameter of type '(value: string, index: number, array: string[]) => unknown'.
      Types of parameters 'key' and 'value' are incompatible.
        Type 'string' is not assignable to type 'keyof Capabilities'.

![image](https://user-images.githubusercontent.com/19193414/139808176-d8c4ede0-2e19-4355-9b90-25c8374d1356.png)

**Comment by christian-bromann** [comment]
@hanifahatiyabudianto I can't spot these TypeScript errors, the build is green and these errors would have been caught. Can you explain how this can be reproduced?

**Comment by hanifahatiyabudianto** [comment]
I am using webdriverIO v7 with JavaScript, Node.js v14.17.6, NPM v6.14.15, appium-service: ^7.16.3, cucumber-framework:^7.16.3.
Describe the bug:
I use pageObject:
        `get btnSelesai () { return $('~btnDone') }`
and a method:
```
        async landingDone () {
                      await expect(this.btnSelesai).toBeClickable()
                      await this.btnSelesai.click()
        }
```
and then, in step-definitions:
      `await LandingPage.landingDone()`
When I run, I got this error:
[0-0] setDefinitionFunctionWrapper is deprecated and will be removed in version 8.0.0 of cucumber-js. If this was used to wrap generator functions, please transition to using async / await. If this was used to
wrap step definitions, please use BeforeStep / AfterStep hooks instead. If you had other use cases, please create an issue.
[0-0] 2021-11-01T11:52:32.266Z ERROR webdriver: Request failed with status 405 due to unknown method: Method is not implemented
Error: Expect $(~btnDone) to be clickable
Expected: "clickable"
Received: "not clickable"

Then I npm update the wdio-cucumber-framework package, but wdio-cucumber-framework package still use JavaScript not typescript file.
I migrate wdio from javaScript to typescript but got the same error **setDefinitionFunctionWrapper** , wdio-cucumber-framework package still use JavaScript not typescript file.
So I copy https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-cucumber-framework/src/index.ts#L296-L322 manually to ts file, and got an error at utils.ts.
