### ISSUE TITLE
[🐛 Bug]: Lighthouse throws Error: Protocol JSON API error (list), status: 404

### ISSUE THREAD

**Issue by dragosMC91** [webdriverio/webdriverio#7638]
### WebdriverIO Version

7.14.0

### Node.js Version

12.15.0

### Mode

WDIO Testrunner

### What happened?

I can no longer use devtools after upgrading the wdio version.
This problem started appearing once https://github.com/webdriverio/webdriverio/pull/7019 was merged.

If I try to use devtools features like cdp I get `browser.cdp is not a function`.

Note that I have tried various node version (12.15.0, 12.22.6, 14.17.6), chrome version 93 and 95 and multiple OSs (mac, linux) and its the same.

### How to reproduce the bug.

I have created a small repo with a reproductible example here: https://github.com/dragosMC91/lighthouse-bug

### Steps to reproduce:
```
➜ yarn install
➜ cd someapp/
➜ yarn test:e2e e2e/test/dummy.desktop.test.js
```

The above repo is a stripped down version of a massive monorepo I appologise if it's clunky.

### Relevant log output

```typescript
ERROR @wdio/sync: Error: Protocol JSON API error (list), status: 404
[0-0]     at IncomingMessage.<anonymous> (/Users/dragoscmd/Documents/bug/src/node_modules/@wdio/devtools-service/node_modules/lighthouse/lighthouse-core/gather/connections/cri.js:107:18)
[0-0]     at IncomingMessage.emit (events.js:412:35)
[0-0]     at IncomingMessage.emit (domain.js:470:12)
[0-0]     at endReadableNT (internal/streams/readable.js:1317:12)
[0-0]     at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
The steps to reproduce are invalid, getting `/bin/sh: wdio: command not found`

**Comment by dragosMC91** [comment]
> The steps to reproduce are invalid, getting `/bin/sh: wdio: command not found`

hmm I tried on 2 different mac machines before posting, I will try to find out why you get that error and get back with an update of steps.
What version of node & yarn are you using?

**Comment by christian-bromann** [comment]
> What version of node & yarn are you using?

latest

Note: in https://github.com/dragosMC91/lighthouse-bug/blob/main/someapp/package.json where I am suppose to run `yarn test:e2e e2e/test/dummy.desktop.test.js` no dependencies for wdio are defined.

**Comment by dragosMC91** [comment]
> > What version of node & yarn are you using?
> 
> latest
> 
> Note: in https://github.com/dragosMC91/lighthouse-bug/blob/main/someapp/package.json where I am suppose to run `yarn test:e2e e2e/test/dummy.desktop.test.js` no dependencies for wdio are defined.

`someapp/package.json` has a devDependency on `"somelayer": "^1.0.0"` (https://github.com/dragosMC91/lighthouse-bug/blob/main/somelayer/package.json) which contains all the deps but i'm updating this now

**Comment by dragosMC91** [comment]
@christian-bromann I updated the structure of https://github.com/dragosMC91/lighthouse-bug and also tested it on 2 more laptops and had no problems running the tests :(. I don’t think it's because we're using older version of node/yarn so not sure why you get that error when running

**Comment by dragosMC91** [comment]
> @christian-bromann I updated the structure of https://github.com/dragosMC91/lighthouse-bug and also tested it on 2 more laptops and had no problems running the tests :(. I don’t think it's because we're using older version of node/yarn so not sure why you get that error when running

maybe runing with `npx wdio e2e/wdio.appX.conf.js e2e/test/dummy.desktop.test.js` will work?

**Comment by christian-bromann** [comment]
This bug was fixed and released just a second ago, please update your dependencies. Thanks!
