### ISSUE TITLE
[🐛 Bug]: run is not working when project already has a misconfigured tsconfig.json

### ISSUE THREAD

**Issue by Badisi** [webdriverio/webdriverio#7640]
### WebdriverIO Version

7.16.3

### Node.js Version

14.17.5

### Mode

Standalone Mode

### What happened?

The starter project generated with `@wdio/cli` does not run if a `tsconfig.json` already exists and is not properly configured.

### What is your expected behavior?

Everything should work without any issues after installing WebdriverIO on an existing project.

### How to reproduce the bug.

The original use case was to install `wdio` on an existing `angular` project.

But for the sake of this issue it can be reproduced as follow:

1) Create a folder `test` then go inside

    ```sh
    mkdir test
    cd test
    ```
2) Create a `tsconfig.json` file

    ```json
    {
      "compilerOptions": {
          "module": "es2020"
      }
    }
    ```
3) Install WebdriverIO with `typescript` as a compiler

    ```sh
    npx wdio .
    ```
4) Run the tests

    ```sh
    wdio run wdio.conf.ts
    ```
5) The following error occurs:
    > SyntaxError: Unexpected token 'export'

### Proposal

Actually, the `@wdio/cli` looks for a `tsconfig.json` file in the current directory and ignores it if it founds one or create one otherwise. But to me the problem is that existing typescript projects will always have a `tsconfig.json` file and those should only serve the main project itself. We should not use the same `tsconfig.json` for both the main project and the tests.

I think something like this would be more suitable:
```
project
├── test
│   ├── pageobjects
│   ├── specs
│   └── tsconfig.json
└ tsconfig.json
```

WebdriverIO would always look up for a `tsconfig.json` in the test folder.
This file would be created during each installation (no need to detect it anymore or to configure it manually afterwards).
And this file would always guarantee that everything is properly configured for wdio to work.

### Relevant log output

```typescript
export const config: WebdriverIO.Config = {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
I agree with the suggested solution of always creating a `tsconfig.json` file for WebdriverIO that differs from the application one. Another option would be to ask in the wizard if existing `tsconfig.json` should be used as compiler option. Any contributions are appreciated.

**Comment by praveendvd** [comment]
@christian-bromann  and @Badisi 

if you run the comman


`npm init wdio /path/to/folder`

it will create tsconfig file inside the destination folder , 

as per getting started page , you should be using this

https://webdriver.io/docs/gettingstarted#using-npm

Please let me know if this was what expected

**Comment by christian-bromann** [comment]
@praveendvd the suggestion here is to create a separate `tsconfig.e2e.json` file that is specific to WebdriverIO. Some Angular apps run e.g. with ESM modules only and then it is better to have a separated tsconfig for e2e tests.

**Comment by Badisi** [comment]
@christian-bromann, exactly - but the name of that file should remain `tsconfig.json` because otherwise typing wouldn't work in code editor like Vscode which only recognizes `tsconfig.json` and not `tsconfig.e2e.json`.

To me, the ideal solution should be a solution where wdio is installed "completely" in a dedicated folder.
Where the configurations (wdio, tsconfig), the specs, etc, would be centralized.

```
wdio
 ├── pageobjects
 ├── specs
 ├── wdio.config.ts
 └── tsconfig.json
```

Example : https://github.com/Badisi/wdio-harness
This project is an angular project where `projects/tests` is a folder containing everthing that relates to e2e testing.

----

@praveendvd, the issue is that no matter the `./path/to/folder` that you gave, the `tsconfig.json` file that will be generated will be located in `./`, and ignored if already existing -> resulting in wdio not working.

**Comment by praveendvd** [comment]
@Badisi  

But if I give npm init wdio test then a entire new project with tsconfig will be created in test folder . Could you reverify this is not happening ? And add an example where it's not happening and we could try it out

**Comment by Badisi** [comment]
### Case 1

If `my-test` folder does not exists, `npm init wdio my-test` results in:

![Screen Shot 2021-11-16 at 17 14 03](https://user-images.githubusercontent.com/674862/142022798-346bfd9d-7c20-4634-99b9-1d93814380bb.png)

-> this configuration is fine
-> but to me, `tsconfig.json` and `wdio.conf.ts` should be located in `my-test/test/` otherwise: see case 2

----

### Case 2

If `my-test` folder already exists and contains a `tsconfig.json`, `npm init wdio my-test` results in:

![Screen Shot 2021-11-16 at 17 18 22](https://user-images.githubusercontent.com/674862/142023535-8a0d32c3-81ef-418b-ac5e-ec3888e571d5.png)

-> the `tsconfig.json` is not touched, so running `wdio run` will failed

Project like Angular/React/Whatever, already have a `tsconfig.json` that relates to the project itself and that are not always properly configured for wdio (ie. esm and not cjs).

**Comment by praveendvd** [comment]
@christian-bromann  , currently we treat webdriverio as a full new project and creates the tsconfig.json under the root of the project directory. should we move this under test folder ?

**Comment by christian-bromann** [comment]
> should we move this under test folder ?

I would suggest yes, because there are cases where e.g. Angular users want a different tsconfig for their app than for their tests. In general it makes sense to separate them.

**Comment by praveendvd** [comment]
@christian-bromann  will pick this up then 🥳

**Comment by praveendvd** [comment]
@christian-bromann   ,


if we move tsconfig inside test folder , then we need to create a wdio-entrypoint.js with below content


```
require('ts-node').register(
    {
        transpileOnly: false,
        files: true,
        project: "./test/tsconfig.json"
    }
)
module.exports = require('./wdio.conf')
```

and run test as :


`npx wdio run ./wdio-entrypoint.js --no-autoCompileOpts.autoCompile`


should we create the entry point as part of the demo project ? or just close this bug by mentioning @Badisi  can create a separte tsconfig file inside the test folder with the content 

```
{
    "compilerOptions": {
        "types": [
            "node",
            "webdriverio/async",
            "@wdio/jasmine-framework",
            "expect-webdriverio"
        ],
        "target": "ES5"
    }
}
```


and then use the above mentioned entry point.js and command

**Comment by praveendvd** [comment]
[wdio.conf.zip](https://github.com/webdriverio/webdriverio/files/7557995/wdio.conf.zip)

A demo project for you to use @Badisi 

Related document :

 https://webdriver.io/docs/typescript/#tsconfigjson-example

**Comment by christian-bromann** [comment]
@praveendvd how about this:

if the user picks TypeScript as compiler we could add a question to the [configuration wizard](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-cli/src/constants.ts#L150-L370) asking whether or not they want to re-use their current `tsconfig.json` or create a new one specific for e2e tests (which should be the default option here). If the user picks creating a new tsconfig, we create that file with the content you mentioned above and add [`autoCompileOpts`](https://webdriver.io/docs/typescript#configuration) to the `wdio.conf.ts`.

**Comment by praveendvd** [comment]
@christian-bromann  

Few questions :

1) in case of creating an entire new project if user wants to create a new tsconfig we will check if tsconfig exists, if it doesnt exists we will create the tsconfig file in the route of the project

2) in case of creating project in the existing project directory , if tsconfig exists and usser wants a separate tsconfig then, we will create it under test folder

    in case 2 , if the already existing root tsconfig doesnt have target:es5 or "module":"commonjs" then below error is thrown
    
    
![image](https://user-images.githubusercontent.com/45095911/142386710-2a3ea9a1-4dd3-4895-ab68-3c991a931123.png)

**Comment by Badisi** [comment]
@praveendvd ,

- The `wdio-entrypoint.js` is not even needed as you can make it run like this :
  ```sh
  $ npx wdio run ./wdio.conf.ts --autoCompileOpts.tsNodeOpts.project=./test/tsconfig.json
  ```
  And no need for an `autoCompileOpts` options in the `tsconfig.json` either.

- If you leave the `wdio.conf.ts` outside the `/test` folder or at least do not leave it alongside a proper `tsconfig.json` (with wdio types) then a code editor like Vscode won't be able to find the typing for `config: WebdriverIO.Config`. In my example [wdio-harness](https://github.com/Badisi/wdio-harness/tree/master/projects/tests) I have put everything that's wdio related inside the `tests` folder. I like it that way because everything is bundled and self-sufficient.

@christian-bromann,

Indeed that would be a solution, but all and all I think it would add more complexity.

**Comment by praveendvd** [comment]
@christian-bromann  as mentioned its just one command 

`npx wdio run ./wdio.conf.ts --autoCompileOpts.tsNodeOpts.project=./test/tsconfig.json` or adding autocompile option inside wdio.config file so that you dont have to pass it through command line

but the suggested changes will have entire different project structure for a completly new webdriverIO project and webdriverio project initialized inside the current project . 

I think its better to leave it the way it is and as @Badisi  mentioned user can chose any of the option specified above if they chose to create wdio under the root directory instead of test folder inside the root folder.

**Comment by praveendvd** [comment]
@Badisi  i am not familiar with angular just a quick question , why you want the project structure tobe as mentioned in your comment as case 2

https://github.com/webdriverio/webdriverio/issues/7640#issuecomment-970438905

why is it not possible to create a folder inside my-test say wdioproject or test and initialize the wdio project inside that instead of my-test itself ?

**Comment by christian-bromann** [comment]
> 1. if it doesnt exists we will create the tsconfig file in the route of the project

Why not stay consistent for both scenarios and always have it in `/test/tsconfig.json`? As more as I think about it as more I like the idea of having separate config file for app and testing. What do you think? Happy with both.

> 2\. if tsconfig exists and usser wants a separate tsconfig then, we will create it under test folder

That seems reasonable. Then we also don't need to include the question in the questionaire (you can define whether the question should be asked by using the `when` property, e.g. like [here](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-cli/src/constants.ts#L190).

> `npx wdio run ./wdio.conf.ts --autoCompileOpts.tsNodeOpts.project=./test/tsconfig.json` or adding autocompile option inside wdio.config file so that you dont have to pass it through comm

I prefer adding it in the `wdio.conf.ts`.

**Comment by praveendvd** [comment]
@christian-bromann  for case one there will be type error for config file for a new wdio if tsconfig is inside test folder (like the screenshot i provided) we will be needing two config file in that case . One in test folder and one in root if it doesn't exists ( which is already implemented)

**Comment by christian-bromann** [comment]
> or you want to move wdio.config.ts also inside test folder as @Badisi mentioned ?

🤔  understand, ok then I suggest these two cases:

- tsconfig file exist in root folder -> create wdio.conf.ts and wdio tsconfig.json within `/test`
- tsconfig doesn't exist -> create both in the root folder as it is atm

Would that work?

**Comment by praveendvd** [comment]
@Badisi  Closed with the pull request
