### ISSUE TITLE
[wdio-junit-reporter]: Add ability to use filename as testsuite name attribute

### ISSUE THREAD

**Issue by facusantillo** [webdriverio/webdriverio#7645]
### Is your feature request related to a problem?

jest-junit plugin allows users to use suiteNameTemplate: '{filename}' in junit reporter configuration. This is really useful specially on suites that can't nest more than one test in a describe block due to device specific configurations.

As the result, the testsuite tag looks like:

<testsuite errors="0" failures="3" name="PageLoad.test.ts" skipped="0" tests="8" time="96.331" timestamp="2021-11-01T16:00:07">

### Describe the solution you'd like.

an additional parameter passed through config like suiteNameTemplate to allow users to set the testSuite name attribute as the fileName (same as jest works)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
> an additional parameter passed through config like suiteNameTemplate to allow users to set the testSuite name attribute as the fileName (same as jest works)

Can you describe this a bit more thoroughly, maybe add some code/configuration examples?

**Comment by facusantillo** [comment]
this is  a typical jest configuration file that overrides some of it :

```
reporters: [
        'default',
        [
            'jest-junit',
            {
                suiteName: 'jest tests',
                output: 'junit.xml',
                outputDirectory: './junit',
                classNameTemplate: '{classname} - {title}',
                titleTemplate: '{classname} - {title}',
                ancestorSeparator: ' › ',
                suiteNameTemplate: '{filename}'
            }
        ],
    ],
```

The suiteName uses the filename (eg: LoginTest.spec.ts) and then it's used on the XML as follows:
```
<testsuites errors="0" failures="4" name="jest tests" tests="28" time="211.067">
      <testsuite errors="0" failures="3" name="LoginTest.spec.ts" skipped="0" tests="8" time="96.331" timestamp="2021-11-01T16:00:07"> 
```

This is really useful when you have multiple reporters implemented (like allure) but you need to parse and normalize the junit files for other external services and since the describes are duplicated then results in a sanitization problem merging results that shouldn't be merged.

Here is an example of two XML's generated by the current plugin that would collide:

```
<testsuites time="10.412">
   <testsuite errors="0" failures="0" name="Dashboard layout" skipped="0" tests="1" time="10.412" timestamp="2021-11-03T07:15:53">
      <properties>
         <property name="specId" value="0"/>
         <property name="suiteName" value="Dashboard - layout"/>
         <property name="capabilities" value="9a261ffaz002x6.android.11"/>
         <property name="file" value="./src/tests/native/mm3/Dashboard/dashboard.layout.spec.ts"/>
      </properties>
      <testcase classname="1635948964991.googlepixel4.11_0.Dashboard_-_layout" name="Check dashboard screen layout" time="10.409">
```
```
<testsuites time="12.276">
   <testsuite errors="0" failures="0" name="Dashboard layout" skipped="0" tests="1" time="12.276" timestamp="2021-11-03T07:16:27">
       <properties>
          <property name="specId" value="0"/>
          <property name="suiteName" value="Dashboard - layout"/>
          <property name="capabilities" value="9b081ffaz006hz.android.11"/>
          <property name="file" value="./src/tests/native/mm3/Dashboard/net.promoter.score.spec.ts"/>
       </properties>
       <testcase classname="1635949000680.googlepixel4.11_0.Dashboard_-_layout" name="Check Net Promoter Score is loading" time="12.274">
```

Since the `name` attribute on `testsuite` tag would be repeated the sanitization would occur. This is where using the filename simplifies it. Today we can only set a regex, would be nice to have the ability to set that attribute to use the filename too

**Comment by christian-bromann** [comment]
Thanks for the explanation. I totally agree that users should be able to define suite names more granular. I am open to the idea of templates. I could also see functions that expect a string as return value, similar as to the `outputFileFormat` parameter. What do you think? Would you be open help us implement this?

**Comment by facusantillo** [comment]
sure, never contributed to this project but would love to help you out

**Comment by facusantillo** [comment]
@christian-bromann I have created a PR, not sure if everything is correct (first time contributing) let's continue there!

**Comment by christian-bromann** [comment]
Let's continue convo in #7647
