### ISSUE TITLE
[🐛 Bug]: saved screenshot dimensions (both width and height) are twice the window size

### ISSUE THREAD

**Issue by nmattia** [webdriverio/webdriverio#7649]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.12.1

### Node.js Version

14.18.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: {
      browserName: "chrome",
      "goog:chromeOptions": {
        args: [
          "--headless",
          "--disable-gpu",
        ],
      },
    }
```

### What happened?

When I `setWindowSize(w,h)` and `saveScreenshot()`, the screenshot has dimensions width = `2*w` and height = `2*h`.

### What is your expected behavior?

The screenshot should have the same dimensions as the window.

### How to reproduce the bug.

Note: I can reproduce this on my machine, although it works as expected on another machine.

``` js
await browser.setWindowSize(23,12);
await browser.saveScreenshot("foo.png")
```

``` bash
$ sips -g pixelWidth -g pixelHeight ./foo.png
foo.png
  pixelWidth: 46
  pixelHeight: 24
```

### Relevant log output

```typescript
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by wswebcreation** [comment]
Hi @nmattia 

This is not an issue with WDIO, the fact that the screenshot size is bigger than the screensize has to do with the DPR value.

> DPR or Device Pixel Ratio, also known as CSS pixel ratio, is the number of physical pixels that make up a CSS pixel in one direction of a screen like in the width direction or in the height direction.

This happens on mobile phones / Mac retina screens and so on.

Closing it for now, but it's open for discussion

**Comment by nmattia** [comment]
Ah I see! Thanks!

Indeed, it's a MacBook Pro. Is there any way to read the DPR? Then I could adapt the window dimensions.

Alternatively, is there a way to set the window size in actual pixels as opposed to CSS pixels?

**Comment by wswebcreation** [comment]
Hi @nmattia 


>  Is there any way to read the DPR?

Yes, you can ask the browser with for example [this](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio) command inside of the `execute` method.

```js
await driver.execute('return window.devicePixelRatio;');
```

> Alternatively, is there a way to set the window size in actual pixels as opposed to CSS pixels?

No, there is no other way by default. You might need to use a NPM library that will resize the image when DPR > 1.

Hope this helps
