### ISSUE TITLE
[🐛 Bug]: Cucumber afterScenario hook missing Cucumber's World object

### ISSUE THREAD

**Issue by jvisco** [webdriverio/webdriverio#7651]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.3

### Node.js Version

12.13.1

### Mode

WDIO Testrunner

### What happened?

Cucumber's World object, is not available in the WDIO `afterScenario` hook. This appears to have been fixed in WDIO v6 but not v7.

https://github.com/webdriverio/webdriverio/pull/5483

### What is your expected behavior?

The `afterScenario` to have a `context` param for the Cucumber World object like it does in WDIO v6:
https://github.com/webdriverio/webdriverio/blob/v6.12.1/packages/wdio-cucumber-framework/cucumber-framework.d.ts#L33

```
    /**
     *
     * Runs after a Cucumber Scenario.
     * @param {ITestCaseHookParameter} world  world object containing information on pickle and test step
     * @param {Object}                 result results object containing scenario results
     * @param {boolean}                result.passed   true if scenario has passed
     * @param {string}                 result.error    error stack if scenario failed
     * @param {number}                 result.duration duration of scenario in milliseconds
     * @param {Object}                 context  Cucumber's world object
     */
    afterScenario: async function (world, result, context) {
      console.log('context: ' + context);
    },
```

### How to reproduce the bug.

1. Set up WDIO + Cucumber
2. Execute a Cucumber scenario that stores data in the Cucumber World object
3. Log all the `afterScenario` parameters (world, result, context)

### Relevant log output

```typescript
[0-0] context: undefined
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

It seems that with the last major update of Cucumber we removed the world context as parameter from these hooks. It seems reasonable to me to re-add it to the hooks. The relevant code for that is [here](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-cucumber-framework/src/index.ts#L259-L311). Any contributions are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by jvisco** [comment]
I forked the repo and started to look into fixing the issue. But I was unable to make any progress. I did not see how/where to pass along the Cucumber World object as context in the relevant code. Any assistance/instructions would be greatly appreciated!

**Comment by christian-bromann** [comment]
Thanks for picking this up @jvisco , let's continue convo in #7662
