### ISSUE TITLE
[🐛 Bug]: Intl.NumberFormat not working as expected starting with version 7.14.0 when called in wdio tests

### ISSUE THREAD

**Issue by dragosMC91** [webdriverio/webdriverio#7652]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.14.0

### Node.js Version

12.22.7

### Mode

WDIO Testrunner

### What happened?

I have some tests which validate some formatted numbers with foreign characters (bengali) are displayed correctly on the page. These numbers are formatted with Intl.NumberFormat (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat)

`new Intl.NumberFormat('bn').format(10000)` now returns `10,000` when called within the wdio test

Note that switching back to wdio version `7.13.2` works as expected so this was introduced https://github.com/webdriverio/webdriverio/releases/tag/v7.14.0.

### What is your expected behavior?

`new Intl.NumberFormat('bn').format(10000)` should return `১০,০০০`

### How to reproduce the bug.

1. clone https://github.com/dragosMC91/lighthouse-bug
2. run `yarn install`
3. cd to `someapp`
4. run `npx wdio e2e/wdio.appX.conf.js e2e/test/dummy.desktop.test.js`

**Note** that setting `NODE_ICU_DATA='/path/to/full-icu/'` fixes the problem and Intl.NumberFormat returns the expected value like it did before the update.
I don’t know what the problem is but I wanted to report it in case it affected someone else or if the underlying bug might morph into something else.

### Relevant log output

```typescript
[0-0] RUNNING in chrome - /e2e/test/dummy.desktop.test.js
[0-0] formatted number: 10,000
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
This is because the terminal doesn't support the characters you expect. This is not an issue with WebdriverIO.

**Comment by dragosMC91** [comment]
> This is because the terminal doesn't support the characters you expect. This is not an issue with WebdriverIO.

I'm not sure I follow, why does it work as expected in wdio 7.13.2 if it's a terminal problem but not on 7.14?
