### ISSUE TITLE
[📖 Docs]: Can you add how browser.pause() or toExist() works in v6 and synchronous mode?

### ISSUE THREAD

**Issue by nonopolarity** [webdriverio/webdriverio#7655]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Unclear documentation

### Description of the improvement / report

Is it true that in V5 and V6, when we do `browser.pause(3000)` or `expect(el).toExist()`, it does some kind of "idle loop" to wait?  

Or is it Node having some synchronous capability that will go away in Node 16 or 17?

Can you add some explanation in the docs as to how it works?  (many programmers I know don't know how things work. They just work and go home).

Also, if we rely on Node 14 or 15 having synchronous capability... then isn't it true that in Node 16 or Node 17, we can just do the "idle loop"?  Meaning for `browser.pause(3000)`, we loop until we have waiting for 3 seconds, and for `expect(el).toExist()` we simply loop for at most 10 seconds until it shows up. (although it may not be too efficient that way).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
> Is it true that in V5 and V6, when we do `browser.pause(3000)` or `expect(el).toExist()`, it does some kind of "idle loop" to wait?

`browser.pause(ms)` essentially just runs a `setTimeout` while `expect(el).toExist()` tries to check for element existence multiple times until it times out.

> Or is it Node having some synchronous capability that will go away in Node 16 or 17?

WebdriverIO has been using [fibers](https://www.npmjs.com/package/fibers) which was using some internal V8 interfaces that allowed it to run these commands in a synchronous fashion. These interfaces got removed in an V8 version that is being used starting with Node.js v16.

> Can you add some explanation in the docs as to how it works?

I believe we added some reasonable information in our [blog post](https://webdriver.io/blog/2021/07/28/sync-api-deprecation). As we move away from it I don't see much value having it as part of some official docs.

> Also, if we rely on Node 14 or 15 having synchronous capability... then isn't it true that in Node 16 or Node 17, we can just do the "idle loop"?

While keeping the synchronous mode would have been nice there is technically no way we can achieve it.
