### ISSUE TITLE
[🐛 Bug]: Setup for electron: can not read sessionId

### ISSUE THREAD

**Issue by jehon** [webdriverio/webdriverio#7660]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.4

### Node.js Version

17.0.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
        maxInstances: 1,
        browserName: 'chrome',
        acceptInsecureCerts: true,
        "goog:chromeOptions": { binary: './node_modules/electron/dist/electron', args: ["app=" + __dirname] 
},
```

### What happened?

I try to test an electron application, based on electron documentation, and based on praveendvd/WebdriverIO_electronAppAutomation_boilerplate. Those documentation are not in sync, so I tried my personal mix.

Launching wdio:
- It start in console
- It run beforeSession hook
- It open shortly (< 1s) the electron app (but I can't be sure this is my app, since the window dissapear too quickly)
- It complain in console (see below)
- It bail out (before the "before" hook)
- It run the "onComplete" hook and says that 1 test failed (I only have I test)

Here is the wdio.conf.cjs:

```
{
  "runner": "local",
  "port": 9515,
  "path": "/wd/hub",
  "specs": [
    "tests/app/specs/**/*.*js"
  ],
  "exclude": [],
  "maxInstances": 1,
  "capabilities": [
    {
      "maxInstances": 1,
      "browserName": "chrome",
      "acceptInsecureCerts": true,
      "goog:chromeOptions": {
        "binary": "./node_modules/electron/dist/electron",
        "args": [
          "app=/home/jehon/src/kiosk"
        ]
      }
    }
  ],
  "logLevel": "info",
  "bail": 0,
  "waitforTimeout": 10000,
  "connectionRetryTimeout": 120000,
  "connectionRetryCount": 0,
  "services": [
    [
      "chromedriver",
      {
        "port": 9515,
        "path": "/wd/hub",
        "chromedriverCustomPath": "./node_modules/electron-chromedriver/chromedriver.js"
      }
    ]
  ],
  "framework": "jasmine",
  "reporters": [
    "spec"
  ],
  "jasmineOpts": {
    "defaultTimeoutInterval": 60000
  }
}
```

Here are the relevant package.json dependencies:
```
    "@wdio/cli": "7.16.4",
    "@wdio/jasmine-framework": "7.16.4",
    "@wdio/local-runner": "7.16.4",
    "@wdio/spec-reporter": "7.16.4",
    "wdio-chromedriver-service": "7.2.2"
```

### What is your expected behavior?

I would expect the test to open the electron app and say that the electron app is ok.

I would also expect the documentation to be up-to-date (and I will make the necessarily pull request when this is fixed both at electron and here). 

### How to reproduce the bug.

git clone https://github.com/jehon/kiosk.git
git checkout 2021-11-08-wdio-bug-report
npm install
npm run wdio

(I am running under linux)

Code is also available here: https://github.com/jehon/kiosk/tree/2021-11-08-wdio-bug-report

### Relevant log output

```typescript
[0-0] RUNNING in chrome - /tests/app/specs/example.e2e.cjs
[0-0] 2021-11-08T10:21:43.018Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2021-11-08T10:21:43.043Z INFO webdriver: [POST] http://localhost:9515/wd/hub/session
[0-0] 2021-11-08T10:21:43.043Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       acceptInsecureCerts: true,
[0-0]       'goog:chromeOptions': [Object]
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     acceptInsecureCerts: true,
[0-0]     'goog:chromeOptions': { binary: './node_modules/electron/dist/electron', args: [Array] }
[0-0]   }
[0-0] }
[0-0] 2021-11-08T10:21:48.303Z ERROR @wdio/runner: TypeError: Cannot read properties of null (reading 'sessionId')
[0-0]     at startWebDriverSession (/home/jehon/src/kiosk/node_modules/webdriver/build/utils.js:73:38)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0]     at async Function.newSession (/home/jehon/src/kiosk/node_modules/webdriver/build/index.js:58:45)
[0-0]     at async remote (/home/jehon/src/kiosk/node_modules/webdriverio/build/index.js:67:22)
[0-0]     at async Runner._startSession (/home/jehon/src/kiosk/node_modules/@wdio/runner/build/index.js:223:56)
[0-0]     at async Runner._initSession (/home/jehon/src/kiosk/node_modules/@wdio/runner/build/index.js:176:25)
[0-0]     at async Runner.run (/home/jehon/src/kiosk/node_modules/@wdio/runner/build/index.js:88:19)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by jehon** [comment]
I forgot to mention that my electron app is not "packaged", it is the source folder, as documented in electron testing page (https://www.electronjs.org/docs/latest/tutorial/using-selenium-and-webdriver at the very bottom of the page).

electron version: 
    "electron": "15.3.0"
    "electron-chromedriver": "15.0.0"

**Comment by praveendvd** [comment]
> I forgot to mention that my electron app is not "packaged", it is the source folder, as documented in electron testing page (https://www.electronjs.org/docs/latest/tutorial/using-selenium-and-webdriver at the very bottom of the page).
> 
> electron version: 
>     "electron": "15.3.0"
>     "electron-chromedriver": "15.0.0"
> 

Binary and args means you should be able to start the app as

`electron path-to-app`

**Comment by jehon** [comment]
Thanks for your help! 

The application is not "packaged", and the configuration described in your link is for "packaged" applications... I did test it with the binary = __dirname, and no args, but that no help.

I made the test, with 

```
'goog:chromeOptions': { binary: './node_modules/electron/dist/electron', args: [ "app=." ] }
```
I tried too with ``` `app=${__dirname}` ```, but with no success.

I did put a hook in the launching, and the command launched is
```
./node_modules/electron/dist/electron \
    --allow-pre-commit-input \
    --app=. \
    --disable-background-networking \
    --disable-client-side-phishing-detection \
    --disable-default-apps \
    --disable-hang-monitor \
    --disable-popup-blocking \
    --disable-prompt-on-repost \
    --disable-sync \
    --enable-automation \
    --enable-blink-features=ShadowDOMV0 \
    --enable-logging \
    --ignore-certificate-errors \
    --log-level=0 \
    --no-first-run \
    --no-service-autorun \
    --password-store=basic \
    --remote-debugging-port=0 \
    --test-type=webdriver \
    --use-mock-keychain \
    --user-data-dir=/tmp/.org.chromium.Chromium.ms9aJU \
    data:
```
I tried this command in a console, and I get the same problem. I got some more logs...

```
DevTools listening on ws://127.0.0.1:41559/devtools/browser/a42557f5-4e9c-4736-84a2-0cf153502020
Options:
      --version                      Show version number               [boolean]
  -f, --file                         additionnal file configuration     [string]
      --devMode, ---d, ----dev-mode  activate the dev mode             [boolean]
      --help                         Show help                         [boolean]

Unknown arguments: app, disable-background-networking, disableBackgroundNetworking, disable-client-side-phishing-detection, disableClientSidePhishingDetection, disable-default-apps, disableDefaultApps, disable-hang-monitor, disableHangMonitor, disable-popup-blocking, disablePopupBlocking, disable-prompt-on-repost, disablePromptOnRepost, disable-sync, disableSync, enable-automation, enableAutomation, enable-blink-features, enableBlinkFeatures, enable-logging, enableLogging, ignore-certificate-errors, ignoreCertificateErrors, log-level, logLevel, first-run, firstRun, service-autorun, serviceAutorun, password-store, passwordStore, remote-debugging-port, remoteDebuggingPort, test-type, testType, use-mock-keychain, useMockKeychain, user-data-dir, userDataDir, data:
```

The last line is strange...

**Comment by jehon** [comment]
Ok, I found it out !!!

I use "yargs" in "strict" mode to parse the command line options. This detect all those parameters as unknown, and kill the app.

That is now fixed!

To anybody coming to this thread:

!! Yargs must not be in "strict" mode !!
