### ISSUE TITLE
Error: [webdrivercss("screenshot",[])] <

### ISSUE THREAD

**Issue by worry127722** [webdriverio/webdriverio#768]
var webdriverio = require('webdriverio');
    var client = webdriverio.remote(options);
    require('webdrivercss').init(client,{
        screenshotRoot: xpath + '/' + time
    });
    client
        .init()
        .url(url)
        .setViewportSize({
            width: 1280,
            height: 800
        })
        .webdrivercss('screenshot',[
            {
                name: 'screenshot',
                elem: 'body'
            }
        ], function(err, res) {
            console.log(err);
        })
        .end();

{ [Error: [webdrivercss("screenshot",[])] <= 
 [saveDocumentScreenshot("/workspace/test_webd/tieba.baidu.com/L3AvMzUzMDM5Nzg2OD9fX3FhX3BhZ2VfZGlmZj0x/1441678124472/screenshot.png")] <= 
 Command failed: gm convert: Unable to open file (/workspace/test_webd/node_modules/webdrivercss/lib/../.tmp/0-1.png) [No such file or directory].
] code: 1, signal: null }

the screenshot.png did not be created, why?

**Comment by christian-bromann** [comment]
If you file an issue on Github please be aware of the following things:

1. What version of WebdriveIO and WebdriverCSS are you using. How does your setup and environment look like etc
2. Describe your problem and how you can reproduce it (if possible) as detailed as possible.
3. __Never__ post error messages and just ask _"why?_
4. A nice greeting hasn't hurt anyone!!!

Closing due the missing points above. Feel free to open a new issue with these facts in mind.

Have a good day!
