### ISSUE TITLE
[🐛 Bug]: Console.Logs not attaching to AllureReport on a failed cucumber step

### ISSUE THREAD

**Issue by starbuck251** [webdriverio/webdriverio#7686]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.10

### Node.js Version

12

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
NA
```

### What happened?

When running tests with Cucumber framework, allure reporter and console.logs to be attached, when a step fails the logs are not attached to the allure report

I have chatted with @praveendvd on his PR https://github.com/webdriverio/webdriverio/pull/7134 around this issue
and a fix that was tested by my developer in house was confirmed along with Praveens initial thoughts on the fix. Fix just involves moving a single line to the top of onTestFail which is captured in the conversation on the PR.

### What is your expected behavior?

On fail the logs should be attached to the allure report

### How to reproduce the bug.

When running wdio with allure logs, cucumber framework, and console logs attaching to the allure report, when a step fails, on opening the report, the failed step does not have the logs leading up to failing, all passing steps contain logs.

### Relevant log output

```typescript
NA
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by praveendvd** [comment]
Thank you will push the fix today 🙂

**Comment by praveendvd** [comment]
Fixed as part of https://github.com/webdriverio/webdriverio/pull/7691 , thanks for raising @starbuck251
