### ISSUE TITLE
[🐛 Bug]: Unable to test Iphone - WDIO- Saucelabs

### ISSUE THREAD

**Issue by opensourcesensor** [webdriverio/webdriverio#7690]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
 base: 'SauceLabs',
 browserName: 'Safari',
 appiumVersion: '1.22.0',
 deviceName: 'iPhone X Simulator',
 deviceOrientation: 'portrait',
 platform: 'iOS',
}
```

### What happened?

Since this week the tests are unable to click elements on the Iphone, Safari Browser. 
There is a error:

WebDriver Error: An element command failed because the referenced element is no longer attached to the DOM.

### What is your expected behavior?

The element on Iphone should be clickable.

### How to reproduce the bug.

describe('1_Login_Phone', () => {
    it('1.1/1.2/1.3', async() => {
        await browser.url(`https://www.sick.com/de/de`);
        const cookie =  await $('[class="button blue big right"]');
        await cookie.click();
});
});
-> test.js

Run with a saucelabs capabilities conf file.

### Relevant log output

```typescript
WebDriver Error: An element command failed because the referenced element is no longer attached to the DOM.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
I was able to reproduce this. I recommend to raise an issue in the [Appium](https://github.com/appium/appium) project. WebdriverIO does nothing special here and the same trivial code works on desktop Safari. Given that there is really nothing we can do in WebdriverIO I will close the issue. Happy to re-open if there is anything we can do.
