### ISSUE TITLE
[🐛 Bug]: Couldn't find plugin "wait-for" service

### ISSUE THREAD

**Issue by Badisi** [webdriverio/webdriverio#7700]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.7

### Node.js Version

14.17.5

### Mode

Standalone Mode

### What happened?

Running a new WebdriverIO project where `wait-for` was choosen as a `service` doesn't work.

### What is your expected behavior?

Everything should work without any issues after installing WebdriverIO.

### How to reproduce the bug.

```sh
$ mkdir test
$ cd test
$ npm init wdio . # choose wait-for when asked for desired services
$ npm run wio
```

### Relevant log output

```typescript
> webdriverio-tests@0.1.0 wdio
> wdio run wdio.conf.ts

Execution of 1 workers started at 2021-11-15T13:38:54.392Z

2021-11-15T13:38:54.449Z ERROR @wdio/utils:initialiseServices: Error: Couldn't find plugin "wait-for" service, neither as wdio scoped package "@wdio/wait-for-service" nor as community package "wdio-wait-for-service". Please make sure you have it installed!
    at initialisePlugin (/Users/jpti/Workspace/test/node_modules/@wdio/utils/build/initialisePlugin.js:41:11)
    at initialiseServices (/Users/jpti/Workspace/test/node_modules/@wdio/utils/build/initialiseServices.js:59:56)
    at initialiseLauncherService (/Users/jpti/Workspace/test/node_modules/@wdio/utils/build/initialiseServices.js:86:26)
    at Launcher.run (/Users/jpti/Workspace/test/node_modules/@wdio/cli/build/launcher.js:73:103)
    at launch (/Users/jpti/Workspace/test/node_modules/@wdio/cli/build/commands/run.js:126:21)
    at Object.handler (/Users/jpti/Workspace/test/node_modules/@wdio/cli/build/commands/run.js:164:16)
    at /Users/jpti/Workspace/test/node_modules/yargs/build/index.cjs:1:9052
    at j (/Users/jpti/Workspace/test/node_modules/yargs/build/index.cjs:1:4931)
    at M.applyMiddlewareAndGetResult (/Users/jpti/Workspace/test/node_modules/yargs/build/index.cjs:1:9021)
    at M.runCommand (/Users/jpti/Workspace/test/node_modules/yargs/build/index.cjs:1:7206)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by Badisi** [comment]
I guess that this line [constants.ts#L107](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-cli/src/constants.ts#L107) should be removed or [wdio-wait-for](https://github.com/webdriverio/wdio-wait-for) package should be renamed to `@wdio/wait-for-service` or `wdio-wait-for-service`.

**Comment by christian-bromann** [comment]
@Badisi mind taking a stab at this?

**Comment by Badisi** [comment]
I don't mind but I'm not sure which solution is better.

To me, `wdio-wait-for` is not really a wdio "service", in the sense that it does not provide a class object as explained in the [docs](https://webdriver.io/docs/customservices). I love the idea that a user could simply `npm i` a package, reference it in the `services` of the wdio config and voila! But if we just rename `wdio-wait-for` to let say `@wdio/wait-for-service`, is it really going to work ?

**Comment by christian-bromann** [comment]
`wdio-wait-for` is not a service in that sense. It isn't picked up by the testrunner. It needs to be imported. Maybe we add a new section called `Plugins` where the only choice is "wdio-wait-for"? I am sure people will build other cool things we can add there eventually.

**Comment by Badisi** [comment]
Exactly, it's just something that needs to be "imported".

I'm also working on a package that is more or less the same as `wdio-wait-for` and I was looking, at first, for a way to add it as a "Plugin" when I realized the only thing available was "Services" and "Reporters". So yes `Plugins` would be a good idea!

But I also renamed my local `wdio-wait-for` package to `wdio-wait-for-service` and it seems to work.

So, renaming `wdio-wait-for` seems to be a quick fix, whereas adding a `Plugins` section would be a better fit but would require more effort and time that I don't have unfortunately..

**Comment by christian-bromann** [comment]
> whereas adding a `Plugins` section would be a better fit but would require more effort and time that I don't have unfortunately..

I would prefer this option. We can leave it open as an issue and maybe someone wants to contribute to this.

**Comment by gpt14** [comment]
I can pick this up.

**Comment by christian-bromann** [comment]
@gpt14 cheers! Let me know if you have any questions. Happy to answer.
