### ISSUE TITLE
[💡 Feature]: Allow for a single framework-agnostic manager of test attachments

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#7703]
### Is your feature request related to a problem?

Currenlty Cucumber users can add attachment to the framework with `this.attach` function.
These attachments play nicely with Cucumber oriented third party services but they are not made available to WDIO services and reporters that want to make use of them.

webdriverIO users should have single method of adding and getting attachments for tests within (WDIO and framework-specific) hooks.

### Describe the solution you'd like.

Add a test attachment once.
Have it made available in all community and custom reporters/ services.
Have it available to Cucumber/Mocha/Jasmine frameworks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hammzj** [comment]
I'd actually love to have this implemented as well as it would be an immense help in tracking data throughout a test.

[Cucumber allows attachments](https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/attachments.md) of various file types to any step or hook.

For example they provided an example of adding an attachment to an hook that completes after every scenario test:
```js
var {After} = require('@cucumber/cucumber');

After(function () {
  this.attach('{"name": "some JSON"}', 'application/json');
});
```
Finally, that attachment is linked to the Cucumber's instance of a  [World object for that scenario](https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/world.md). So, we can add attachments to any step that occurred inside of that scenario to use for reporting later on. Similarly, there is [a CucumberJSON reporter available](https://webdriver.io/docs/wdio-cucumberjs-json-reporter) for WebDriverIO but ultimately, it would be much better if this functionality was native to WDIO.


Here's another example of how it would work with steps and an After hook:

** Scenario**
```cucumber

Scenario: The user adds a new To Do item
Given the "staticUser" user logs into the app
And the user is on the "to do list" screen
When the user adds a new note:
"""
This is a test note!
"""
Then the "staticUser" user's most recent note is saved to the dashboard
```

**Step Definitions:**
```js
const {Given, When, Then, After, Status} = require('@cucumber/cucumber');

Given("the {string} user logs into the app", async function (fixture) {
    /*
   Pseudocode to get a defined user named "staticUser".
   The object properties will be {username: 'a-tester@hemail.com', password: 'MyPa$$word!', notes: []}
   */
    const user = getUser(fixture)
    await app.login(user) //pseudocode to login
    this.user = user //here, the Cucumber World has access to that user fixture in other steps.
    
    this.attach(user, 'application/json') //Here, we attach the user fixture we used to log in.
})

Given("the user is on the To Do List screen", async function () {
    this.screen = ToDoListScreen //assume this is an external class with elements and helper functions
})

When(`the user adds a new note:`, async function (docString) {
    const note = await this.screen.addNote(docString); // {text, timeAdded}
    this.user.notes.push(note)

    //In this step, the note will be attached.
    this.attach(note, 'application/json')
})

Then(`the {string} user's most recent note is saved to the dashboard`, async function (user) {
    const newestNote = this.user.notes.reverse(n => n.timeAdded)[0]
    this.screen.validateNoteIsSaved(newestNote)
});

After(async function ({result, pickle}) {
    //If the scenario fails, attach a screenshot to the After hook of that scenario.
    if (result.status === Status.FAILED) {
        const screenshot = await driver.takeScreenshot();
        this.attach(screenshot, 'base64:image/png');
    }
});

function getUser(fixtureName) {
    const users = {
        staticUser: {username: 'a-tester@hemail.com', password: 'MyPa$$word!', notes: []},
        otherUser: {username: 'blahblah@hemail.com', password: 'ABCD1234!', notes: []}
    }
    return users[fixtureName]
}
```

I think all of this is handled by [Cucumber Messages](https://github.com/cucumber/common/tree/main/messages) but it's a new concept to me. I just wanted to add my input as I really really want this too.

**Comment by nextlevelbeard** [comment]
Take a simple case of saving a screenshot on error.

You use the webdriverIO's `saveScreenshot` command.
Now you want this screenshot to be part of your reporting pipeline.

Suppose you are using Cucumber and 3 other services / reporters.
- Cucumber JS JSON reporter
- Allure
- Microsoft Teams
- You have a custom service that also needs to do something with the attachments

You will need, at the moment of taking a screenshot
(which can vary but is usually in WDIO hooks or Cucumber hooks) :

1. Add it to Cucumber framework native attachment in order to work with Cucumber reporters
In a Step or Cucumber hook call `this.attach`, `this` being the `World`

2. Add it to [Allure ](https://webdriver.io/docs/allure-reporter/ ) by Importing and calling `addAttachment` from `@wdio/allure-reporter`.

3. The [Microsoft Teams service](https://webdriver.io/docs/wdio-ms-teams-service/) does not do anything with test attachments currently but we could enhance it to do so.
The problem is: Services need a to have a standardized a way to know which attachments does the current test have.

4. In your custom service, you'll have to hard code a way to get your attachments.
In the moment of taking a screenshot, we save it to the browser scope.
Then in this custom service we built, we retrieve it from the browser scope.

So your code could look something like this:

```js
import cucumberJson from 'wdio-cucumberjs-json-reporter';
import allureReporter from '@wdio/allure-reporter';


After(function (scenario) {
  const passed = scenario.result.status === Status.PASSED;
  if (!passed) {
    const filename = "example";

    try {
      browser.saveScreenshot(filename);

      // Attach screenshot to reporters
      const file = fs.readFileSync(filename);
      if (file) {
            const base64 = Buffer.from(file).toString('base64');
            
            // Add it to cucumberjs-json
            cucumberJson.attach(base64, 'image/png')
            
            // Add it to native Cucumber reporting, this = World
            this.attach(base64, 'image/png') 
            
            // Add it to Allure
            allureReporter.addAttachment('Error screenshot',  base64, 'image/png')
            
            // Save it to browser scope to use in my custom service
            browser.attachments.push({ base64, type: 'image/png' })
            
            // Third party services have no idea which attachments exist
            // Their maintainers cannot enhance them to support it because there is no API
      }
    } catch (err) {
      // Handle it
    }
  }
});
```

When it could just be like this:
```js
After(function (scenario) {
  const passed = scenario.result.status === Status.PASSED;
  if (!passed) {
    const filename = "example";

    try {
      browser.saveScreenshot(filename);
      browser.addAttachment({ 
        name: "Error screenshot",
        type: "image/png",
        fileOrContent: filename
      })
  }
});

```
--- 

This would be a lot simpler if we had a standardization for test attachments.
Something like `browser.addAttachment` and `browser.getAttachments`

`browser.addAttachment` would:
- Automatically add atachments to all used integrations that are possible: 
  - Automatically add the attachment to Allure if registered as a service/reporter
  - Automatically call World.attach if you're using Cucumber
  - Save the attachments in the browser/session scope to be retrieved later by `getAttachments`

`browser.getAttachmens` would:
- Be available in WDIO and Cucumber hooks in order for the services / reporters to do something with them.
Teams service could retrieve and include the attachments in the messages, for example.
A custom service/reporter and official/community services would be able to call it to know which attachments does the test have.

**Comment by christian-bromann** [comment]
> Something like `browser.addAttachment` and `browser.getAttachments`

I am not a big fan of the idea of adding these commands to the `browser` instance given they only use in combination with Allure and Cucumber. Commands already work very differently based on the remote end, increasing the fragmentation on the framework level would just create more confusion. Maybe the Allure reporter could expose a helper method that someone can just import and use?

**Comment by nextlevelbeard** [comment]
> > Something like `browser.addAttachment` and `browser.getAttachments`
> 
> I am not a big fan of the idea of adding these commands to the `browser` instance given they only use in combination with Allure and Cucumber. 

Well that's just a suggestion of an API. it could be exposed as a parameter on service hooks, for example.
The idea is not only to use it with Cucumber and Allure but to be constantly enhanced with every integration that does something with attachments. The user only has to declare an attachment once, no matter what reporters they are using.

> Commands already work very differently based on the remote end, increasing the fragmentation on the framework level would just create more confusion. Maybe the Allure reporter could expose a helper method that someone can just import and use?

It already has one, if you see there on the code.
The problem is exactly that, for every reporter / integration you add to your project, you have to deal with adding the attachments for it. webdriverIO could do it for you. Cucumber and Allure are an example, could be done automatically for Report Portal, Teams, Slack, Sauce when you register them.

**Comment by BorisOsipov** [comment]
Hi! We have rewritten the reporter to the new allure-js version. Please try version 8.5.0 of wdio-allure-reporter and provide more details if the issue still persists. Feel free to create a new issue with actual details if it reproduces.
