### ISSUE TITLE
[🐛 Bug]: @wdio/sync doesn't work with node 16

### ISSUE THREAD

**Issue by slaven3kopic** [webdriverio/webdriverio#7704]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

6.10.11

### Node.js Version

16.13.0

### Mode

Standalone Mode

### What happened?

At the moment `@wdio/sync` doesn't work with node 16.13.0. This version of node is recommended for most of the users.

### How to reproduce the bug.

Install node 16.13.0 and try to use it with `@wdio/sync`

### Relevant log output

```typescript
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@wdio/sync@7.16.8',
npm WARN EBADENGINE   required: { node: '>=12.0.0 <16' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.1.0' }
npm WARN EBADENGINE }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
We don't support `@wdio/sync` for NodeJS v16 and above anymore. Therefor we deprecated our synchronous API. For more information see https://webdriver.io/blog/2021/07/28/sync-api-deprecation.

**Comment by cgungaloo** [comment]
browser.performActions() doesnt seem to work without it anymore, its not recognised as a function

**Comment by christian-bromann** [comment]
@cgungaloo `positionClick` is a JSONWireProtocol command which probably is not supported by the browser anymore that you use for testing. We recommend to use [`performAction`](https://webdriver.io/docs/api/webdriver/#performactions).
