### ISSUE TITLE
[📖 Docs]: Improve resources documentation

### ISSUE THREAD

**Issue by Badisi** [webdriverio/webdriverio#7705]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Unclear documentation

### Description of the improvement / report

While looking for resources (plugins and such):

- I first went to the github page and found this list:  
   https://github.com/webdriverio/webdriverio#package-packages

- Then I went to the website and found this other list (which is not the same):  
   https://webdriver.io/community/resources#plugins 

- I also found this repo which I guess is used to generate the page on the website:
  https://github.com/webdriverio/awesome-webdriverio

- And finally, I found on the doc that if you develop something yourself you should reference it here:
  https://github.com/webdriverio/webdriverio/blob/main/scripts/docs-generation/3rd-party/services.json
  But those are found nowhere..

I don't know how but I'm sure there is something to do here to improve user adoption as it was painfull for me to find all those info.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
> * I first went to the github page and found this list:

This is a list of all packages that are part of this repository.

> * Then I went to the website and found this other list (which is not the same):

This is a general list of 3rd party plugins developed outside of this repository (community packages)

> * I also found this repo which I guess is used to generate the page on the website:

Correct!

> * And finally, I found on the doc that if you develop something yourself you should reference it here:
>   https://github.com/webdriverio/webdriverio/blob/main/scripts/docs-generation/3rd-party/services.json
>   But those are found nowhere..

Yes, this is indeed not well documented. Here is an example commit of someone adding their service/plugin to this list: https://github.com/webdriverio/webdriverio/commit/3cb5937b968dfe93cf78871589019736a6c98d9e.

**Comment by christian-bromann** [comment]
@Badisi thanks for raising this issue. It is very important to be very clear about this to incentivise the community to build more plugins and make the WebdriverIO ecosystem richer. I added a commit to be more clear about this. Please review and let me know what you think. Happy to extend the docs further. Also let me know where else you see a lack of documentation. Thank you for your contributions!

**Comment by Badisi** [comment]
All the 3rd-parties listed in [services.json](https://github.com/webdriverio/webdriverio/blob/main/scripts/docs-generation/3rd-party/services.json) are only visible when using the wdio installer.
Maybe we could also list them in `awesome-webdriverio` ?

That way, people would be aware of that "rich ecosystem" even before starting using wdio.
And it could even make them adopt wdio if they see something that may fit their needs.

**Comment by christian-bromann** [comment]
> Maybe we could also list them in `awesome-webdriverio` ?

Yes, makes sense.

**Comment by Badisi** [comment]
Done in https://github.com/webdriverio/awesome-webdriverio/pull/4.
