### ISSUE TITLE
[💡 Feature]: Allow second parameter to getCSSProperty to target pseudo elements, e.g. '::after'

### ISSUE THREAD

**Issue by nikolajl** [webdriverio/webdriverio#7709]
### Is your feature request related to a problem?

I need to check a css style that is implemented as pseudo element `::after`.

In the browser this is possible using `window.getComputedStyle(element, '::after')`. However, there is not an obvious way to do this in on the Element in WebdriverIO.

Under the hood, `getCSSProperty()` uses getComputedStyle, but only allows 1 parameter. Allowing a second parameter would be an obvious simple solution.

### Describe the solution you'd like.

Add second parameter to `getCSSProperty()`

Example:
```
const contentAfter = await $('#selector').getCSSProperty('content', '::after')
```

Parameter would be added here.
https://github.com/webdriverio/webdriverio/blob/f8584110532a33ad899ff66eefde427d2d0c7481/packages/webdriverio/src/commands/element/getCSSProperty.ts#L73
```
export default async function getCSSProperty (
    this: WebdriverIO.Element,
    cssProperty: string,
    pseudoElement?: string // or '::before' | '::after'
) {
```

and then passed on to this one:
https://github.com/webdriverio/webdriverio/blob/f8584110532a33ad899ff66eefde427d2d0c7481/packages/devtools/src/scripts/getElementCSSValue.ts#L5
```
export default function getElementCSSValue (_: HTMLElement, elem: HTMLElement, propertyName: string, pseudoElement?: string ): string {
    return (window.getComputedStyle(elem, pseudoElement) as any)[propertyName]
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Thanks for proposing the idea @nikolajl! I think the structure you suggest works out, maybe we can be a bit more stricter about the pseudo element strings? So rather than defining it as `string`, we could list `'::after' | '::before' | etc`.

Any contributions that implements this suggestion are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by Andrewnt219** [comment]
Hi @christian-bromann, I want to help with this issue.

**Comment by christian-bromann** [comment]
Awesome, let me know if you have any questions.

**Comment by Andrewnt219** [comment]
@christian-bromann the `geElementCssValue` gets its type from an ignored d.ts file. Even if I change the file, it doesn't affect the type anyway. I tried adding types to both the `getElementCssValue` in packages/devtools/src/commends but that didn't work either. How should I type the third parameter? 

<img width="1023" alt="Screen Shot 2021-11-24 at 10 17 11 PM" src="https://user-images.githubusercontent.com/52666982/143374389-86ffe0d2-c866-41e7-b7e6-8fab00bcb994.png">

<img width="750" alt="Screen Shot 2021-11-24 at 10 23 40 PM" src="https://user-images.githubusercontent.com/52666982/143374333-ca018143-1d30-47ce-948c-327050d1283c.png">
c2.png">

**Comment by christian-bromann** [comment]
> it doesn't affect the type anyway.

You can generate types via `npm run generate:typings`, see also https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#typescript-definitions

**Comment by Andrewnt219** [comment]
Thanks. I misunderstood that the script will change base on TypeScript, but I actually had to go inside the JSON file and update the type.

**Comment by Pawel1894** [comment]
@christian-bromann I guess this can be closed? 😄

**Comment by christian-bromann** [comment]
Yes, thanks @Pawel1894 for working on this 👏
