### ISSUE TITLE
Coffeescript

### ISSUE THREAD

**Issue by Haardt** [webdriverio/webdriverio#771]
Hi,
i can't use my "*.coffee" script tests (with mocha). In the "ConfigParser.js" all files without postfix ".js" are filtered.

    patternFilter = function(path) { path.slice(-3) === '.js' || path.slice(-7) === 'feature'; };

if i add 
    
    path.slice(-7) === '.coffee'

All work fine. Missing some points or is that a bug?

**Comment by christian-bromann** [comment]
nope, this seems serious.

**Comment by christian-bromann** [comment]
Fixed and just release with `v3.2.2`
