### ISSUE TITLE
[🐛 Bug]: mock.respond uses atob which doesn't work correcly for utf8

### ISSUE THREAD

**Issue by Nio-o** [webdriverio/webdriverio#7710]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.8

### Node.js Version

14.17.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
chrome_1920x1080: {
      windowSize: {
        width: 1920,
        height: 1080,
      },
      gridUrl: 'http://localhost:4444/wd/hub',
      baseUrl:  'http://host.docker.internal:3000',
      desiredCapabilities: {
        browserName: 'chrome',
      },
    },
```

### What happened?

I want to use mock.respond to intercept http request, make same modifications on response.body object (e.g. add one new field). Response from backend contains cyrillic or non-ASCII  symbols  (e.g "АБВГ", "Coöperatief") but when I want to modify this response it includes unreadable characters

I found issue https://github.com/webdriverio/webdriverio/pull/6062 with similar problem

Also I research that problem in this part of [code](https://github.dev/webdriverio/webdriverio/blob/f8584110532a33ad899ff66eefde427d2d0c7481/packages/webdriverio/src/utils/interception/devtools.ts#L92) 

### What is your expected behavior?

All string converted correcly

### How to reproduce the bug.

```typescript
const mock = await this.browser.mock('my-endpoint-url', {
  method: 'POST',
})

mock.respond(
  (request) => {
    //   Now you can see wrong body
    // "АБВГ" becomes something unreadable like "²Ð¸Ñ"
    // "Coöperatief" becomes "CoÃ¶peratief"
    console.log(JSON.stringify(request.body))
    // This response return to browser and it prints wrong

    // Works without any issues
    return {
      data: 'АБГВ',
    }
    // But body is corrupted
    return request.body
  },
  {
    statusCode: () => 200,
    headers: () => ({ foo: 'bar' }),
    fetchResponse: true,
  },
)

await browser.url(`/valid-url`)

```

### Relevant log output

```typescript
No logs needed.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

Similar was fixed in https://github.com/webdriverio/webdriverio/pull/6062 (but not all cases)

- [X] I have searched the existing issues

**Comment by Nio-o** [comment]
My solution is just replace atob to Buffer.from, but I'm not sure that is good for you. [Link to file](https://github.dev/webdriverio/webdriverio/blob/f8584110532a33ad899ff66eefde427d2d0c7481/packages/webdriverio/src/utils/interception/devtools.ts#L92)


```typescript
// Old 
request.body = base64Encoded ? atob(body) : body

// New
request.body = base64Encoded ? Buffer.from(body, 'base64').toString('utf8') : body;
```

**Comment by christian-bromann** [comment]
Thanks for reporting @Nio-o , your suggestion seems like a viable solution to me, mind raising a PR?

**Comment by Nio-o** [comment]
@Nio-o I made PR but I don't about your workflow and should it be covered with tests. We can continue discussion in PR
https://github.com/webdriverio/webdriverio/pull/7711

**Comment by christian-bromann** [comment]
Awesome, let's continue convo in #7711
