### ISSUE TITLE
[🐛 Bug]: Enabling Sauce Connect w/ sauce-service with W3C EMUSIM capabilities presents invalid capability error

### ISSUE THREAD

**Issue by abSauce** [webdriverio/webdriverio#7722]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.5.0

### Node.js Version

15.14.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
        browserName: 'safari',
        platformName: 'iOS',
        "appium:platformVersion": '14.3',
        "appium:deviceName": 'iPhone XS Simulator',
        "sauce:options": {
            appiumVersion: '1.20.1',
            build: process.env.BUILD_NAME + build_info,
        }        
    }

or 

{
        browserName: 'Chrome',
        platformName: 'Android',
        "appium:platformVersion": '10.0',
        "apppium:deviceName": 'Android GoogleAPI Emulator',
        "sauce:options": {

            build: process.env.BUILD_NAME + build_info,
        }
    },
```

### What happened?

When attempting to use the provided W3C EMUSIM capabilities (as listed [here](https://saucelabs.com/platform/platform-configurator)) with Sauce Connect started using sauce-service (sauceConnect: true), the client returns this error in the logs.

`ERROR @wdio/runner: Error: Invalid or unsupported WebDriver capabilities found ("tunnelIdentifier"). Ensure to only use valid W3C WebDriver capabilities (see https://w3c.github.io/webdriver/#capabilities).
    at Object.startWebDriverSession (/Users/anthonybrown/Desktop/TrainingTests/mega-test/node_modules/webdriver/build/utils.js:38:19)
    at Function.newSession (/Users/anthonybrown/Desktop/TrainingTests/mega-test/node_modules/webdriver/build/index.js:58:59)
    at Object.remote (/Users/anthonybrown/Desktop/TrainingTests/mega-test/node_modules/webdriverio/build/index.js:67:43)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Runner._startSession (/Users/anthonybrown/Desktop/TrainingTests/mega-test/node_modules/@wdio/runner/build/index.js:216:56)
    at async Runner._initSession (/Users/anthonybrown/Desktop/TrainingTests/mega-test/node_modules/@wdio/runner/build/index.js:172:25)
    at async Runner.run (/Users/anthonybrown/Desktop/TrainingTests/mega-test/node_modules/@wdio/runner/build/index.js:87:19)`

This does not seem to occur with Desktop W3C capabilities however. 

### What is your expected behavior?

It is expected that the test would use the tunnel successfully with the service. However, it seems that that the capability might be placed in the wrong spot. The client seems to fail before you are able to the capabilities are sent to Sauce and do not appear in the logs with logLevel:debug . 

### How to reproduce the bug.

This is specific to using Sauce Connect on Sauce Labs, so will need a test a config pointing to Sauce. Then, you can simply enable Sauce Connect with the snippet below.

```
services: [['sauce', {
        sauceConnect: true,
}]]
```

With the above configured, the above W3C capabilities will encounter the provided tunnelIdentifier error. Also, have seen this with sauce-service version 7.5.0 and 7.14.1. 

Interestingly enough this error does not appear with sauce-service version 6.1.9. 

### Relevant log output

```typescript
Provided above, but happy to provide more information if necessary.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by wswebcreation** [comment]
Closing this one, https://github.com/webdriverio/webdriverio/pull/7726 should fix this

**Comment by wswebcreation** [comment]
Reopening this issue again. The PR that I initially created is not 100% correct. Secondly Sauce will release W3C support on RDC at the beginning of December so we will then also need to have a new fix.
I'll work on figuring out how to solve the Appium part the best way for JWP/W3C sessions for emusim and RDC. 

For now, the best thing to do to make SC work with EMUSIM is to NOT provide the W3C appium caps.
