### ISSUE TITLE
[📖 Docs]: Capabilities defined in CucumberOpts have no effect on the framework and should be removed

### ISSUE THREAD

**Issue by hammzj** [webdriverio/webdriverio#7742]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Unclear documentation

### Description of the improvement / report

I came across this issue in the [old wdio-cucumber-framework](https://github.com/webdriverio-boneyard/wdio-cucumber-framework/issues/6#issuecomment-285871794) from years ago addressing why some of the passed-in `cucumberOpts` are not working. Specifically, I am having problems with the `cucumberOpts.profile` and `cucumberOpts.format`. These should both be removed from the documentation in the [Testrunner Configuration](https://webdriver.io/docs/configurationfile/) as they are misleading. 

For `format`, it is not being used because WebDriverIO prefers the `reporter` capability instead, so only WDIO-specific formatters/reporters _can_ be used, and not formats as defined by [Cucumber](https://github.com/cucumber/cucumber-js/blob/main/docs/formatters.md).

For `profile`, this also has no effect since the `cucumberOpts` are necessarily the same as that option anyway, so it's redundant.

There are probably more options in `cucumberOpts` that are not used, either, but so far I've come across these ones definitely should be removed.

It would be very much preferred if there was a lot more clear documentation on what capability options are actually used by WebDriverIO when specifying a Cucumber framework in the configuration. This would include detecting and removing redundant and unused capabilities. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Let's clean these capabilities up if not needed 👍  We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by praveendvd** [comment]
https://github.com/webdriverio/webdriverio/blob/ba5e0fbbe47348c0ec81c77ea8521f1d34abe3f3/packages/wdio-cucumber-framework/src/types.ts#L92

Could retry be made optional ? the auto generated cucumber project doesnt have this property so we will get type error saying retry is required .

If its about makinng it optional , then we can do it as part of this ticket , else will raise a separate ticket to add this property to auto generate cucumber Opts 


![image](https://user-images.githubusercontent.com/45095911/144723619-ed9cd2ea-31a5-414b-a2d1-28ad818b7307.png)

**Comment by christian-bromann** [comment]
@praveendvd yes, there is no reason why it is mandatory. This is a bug. Do you wanna take a stab at this?

**Comment by praveendvd** [comment]
@christian-bromann sure Christian , but I am not sure about the other flags mentioned in this ticket but will have a look 🎉

**Comment by christian-bromann** [comment]
I believe `format` is mentioned in the docs couple of times but is not used in the TS typings. I suggest to check the source code and remove all occurrences. The same for `profile`. We have an issue logged for it to add support for it #7692. I believe the [type definitions we have](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-cucumber-framework/src/types.ts#L5-L116) are the source of truth and we have to make sure the docs are aligned to that.

**Comment by hammzj** [comment]
@christian-bromann as related to #7692, I don't actually think adding `profiles` in will reduce complexity. I will address my reasonings there.

**Comment by praveendvd** [comment]
> @christian-bromann as related to #7692, I don't actually think adding `profiles` in will reduce complexity. I will address my reasonings there.

@hammzj would you be taking this up ? 🎉

**Comment by praveendvd** [comment]
@hammzj I will take it up 🎉🎉

**Comment by praveendvd** [comment]
Could we continue the discussion in the pull request

**Comment by hammzj** [comment]
Thank you for taking this up @praveendvd!!
