### ISSUE TITLE
[🐛 Bug]: calling acceptAlert on prompt() dismisses the prompt instead of accepting it (devtools)

### ISSUE THREAD

**Issue by jan-molak** [webdriverio/webdriverio#7744]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.9

### Node.js Version

14.18.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    headless: true,
    automationProtocol: 'devtools',

    capabilities: [{

        browserName: 'chrome',
        'goog:chromeOptions': {
            args: [
                '--disable-web-security',
                '--allow-file-access-from-files',
                '--allow-file-access',
                '--disable-infobars',
                '--ignore-certificate-errors',
                '--headless',
                '--disable-gpu',
                '--disable-gpu',
                '--window-size=1024x768',
            ],
        }
    }],
}
```

**IMPORTANT UPDATE** this defect manifests itself when using the `devtools` protocol and a local browser. 
Running the tests I mentioned in this ticket on SauceLabs works fine.

### What happened?

Consider a static HTML page with the following content:

```html
<html lang="en">
<body>
  <button id="trigger" onclick="trigger()">Trigger Alert</button>
  <p id="result"></p>

  <script>
      function trigger() {
          document.getElementById("result").innerHTML = prompt(`Your answer?`, 'default value') || 'dismissed';
      }
  </script>
</body>
</html>
```

When the `#trigger` is clicked, a JavaScript `prompt` with the default value appears:

<img width="452" alt="Screenshot 2021-11-23 at 23 19 33" src="https://user-images.githubusercontent.com/1089173/143144055-11fa52fb-97e5-4946-9a77-7505d1ef80fc.png">

If I interact with such `prompt` manually, I see the following behaviour:
- I click on `OK` => `#result` is set to `default value`
- I click on `Cancel` => `#result` is set to `dismissed`
- I enter `different value` AND click on `OK` => `#result` is set to `default value`

However, when I interact with the above page with a WebdriverIO script and a **local** Chrome browser (via devtools protocol) the behaviour is different.

Calling [`browser.dismissAlert()`](https://webdriver.io/docs/api/webdriver/#acceptalert) dismisses the alert and sets `#result` to `dismissed`, so this part is correct.

However, calling the below WebdriverIO APIs results in an unexpected/incorrect behaviour:
- [`browser.acceptAlert()`](https://webdriver.io/docs/api/webdriver/#acceptalert) => `#result` is set to `dismissed` instead of the `default value`
- [`browser.sendAlertText('different value')`](https://webdriver.io/docs/api/webdriver/#sendalerttext) => `#result` is set to `different value` straight away, without me having to call `browser.acceptAlert` like I would with the JSON Wire protocol (could you confirm if that's intentional?)

Resolving this issue would help to enable better support for WebdriverIO in [Serenity/JS](https://serenity-js.org) - see serenity-js/serenity-js#805

### What is your expected behavior?

I'd expect:
- `browser.acceptAlert()` to confirm the `default value`, so be equivalent to clicking on 'OK' manually
- `browser.sendAlertText()` to be compatible with JSON Wire Protocol so not confirm the alert straight await (although if that's intentional, please let me know)

### How to reproduce the bug.

Start a web server serving the following HTML file I'll be referring to as `prompt.html`:

```html
<html lang="en">
<body>
  <button id="trigger" onclick="trigger()">Trigger Alert</button>
  <p id="result"></p>

  <script>
      function trigger() {
          document.getElementById("result").innerHTML = prompt(`Your answer?`, 'default value') || 'dismissed';
      }
  </script>
</body>
</html>
```

Create the following test:

```typescript
describe('modal dialog', () => {

  it('should accept a prompt with a default value', async () => {
    await browser.navigateTo('http://localhost/prompt.html')
    await $('#trigger').click();
    await browser.acceptAlert();
    expect(await $('#result').getText()).toEqual('default value'); // currently fails since the prompt is dismissed
  });

  it('should (probably?) be compatible with JSON Wire Protocol', async () => {
    await browser.navigateTo('http://localhost/prompt.html')
    await $('#trigger').click();
    await browser.sendAlertText('different value');
    await browser.acceptAlert(); // fails, alert already handled
    expect(await $('#result').getText()).toEqual('different value');
  });
});
```

### Relevant log output

```typescript
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

Mhm 🤔  [`devtools`](https://github.com/webdriverio/webdriverio/blob/main/packages/devtools/src/commands/acceptAlert.ts#L14) actually calls `await this.activeDialog.accept()` which should accept rather than dismissing it. Not sure what is going on here.

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by jan-molak** [comment]
Thanks @christian-bromann, I think I got to the bottom of it.

In [`acceptAlert.ts`](https://github.com/webdriverio/webdriverio/blob/main/packages/devtools/src/commands/acceptAlert.ts#L14) we have:

```typescript
export default async function acceptAlert(this: DevToolsDriver) {
    if (!this.activeDialog) {
        throw new Error('no such alert')
    }

    await this.activeDialog.accept()
    delete this.activeDialog
    return null
}
```
From what I can tell, calling `this.activeDialog.accept()` on `prompt` without specifying the value to be entered gets interpreted by Puppeteer as an intention to dismiss the prompt.


However, Puppeteer [`accept()`](https://github.com/puppeteer/puppeteer/blob/943477cc1eb4b129870142873b3554737d5ef252/src/common/Dialog.ts#L93-L100) has an optional parameter: [`accept(promptText?: string)`](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#dialogacceptprompttext). Puppeteer's `Dialog` also has a handy [`defaultValue()`](https://github.com/puppeteer/puppeteer/blob/943477cc1eb4b129870142873b3554737d5ef252/src/common/Dialog.ts#L83) method which returns either the default value of the prompt, or an [empty string](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#dialogdefaultvalue) if there's no default value or the dialog is not a prompt.

It looks like by changing the `acceptAlert` implementation as follows I get to the desired behaviour:

```typescript
async function acceptAlert() {
    if (!this.activeDialog) {
        throw new Error('no such alert');
    }

    await this.activeDialog.accept(this.activeDialog.defaultValue());
    delete this.activeDialog;
    return null;
}
```
Should I send you a PR with this change?

Regarding the second issue, so separating entering the text from accepting the dialog - it seems to be impossible due to the limitation of the [Puppeteer API](https://github.com/puppeteer/puppeteer/blob/943477cc1eb4b129870142873b3554737d5ef252/src/common/Dialog.ts#L93-L100), so I'll work around this some other way.

**Comment by christian-bromann** [comment]
> Should I send you a PR with this change?

Yes please! Thanks for investigating.

**Comment by jan-molak** [comment]
Done - #7746

**Comment by jan-molak** [comment]
Actually, sorry @christian-bromann, there's one more thing.

In `sendAlertText.ts` we have
```typescript
async function sendAlertText({ text }) {
    if (!this.activeDialog) {
        throw new Error('no such alert');
    }
    await this.activeDialog.accept(text);
    return null;
}
exports.default = sendAlertText;
```
Now, since Puppeteer dismisses the prompt upon calling `activeDialog.accept(text)`, we need to also clear the local state, so:

```typescript
async function sendAlertText({ text }) {
    if (!this.activeDialog) {
        throw new Error('no such alert');
    }
    await this.activeDialog.accept(text);
    delete this.activeDialog;
    return null;
}
exports.default = sendAlertText;
```

I'll send you another PR in a sec

**Comment by jan-molak** [comment]
Done - #7749
