### ISSUE TITLE
[🐛 Bug]: Google throwing captcha in headless mode. Same code works in headful mode

### ISSUE THREAD

**Issue by maaaariana** [webdriverio/webdriverio#7748]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.8

### Node.js Version

14.16.0

### Mode

Standalone Mode

### What happened?

When I am trying to login using google, exact same code works without any problem in headful mode. However if I change the browser to headless (with exact same code), then google throws captcha.

![image (1)](https://user-images.githubusercontent.com/62989745/143240468-2e261151-cdf7-4097-b784-66bafa3d861f.png)

### How to reproduce the bug.

1. Run code in headless mode 
2. Try to login using google in test

The same issue [puppeteer-extra/issues/589](https://github.com/berstend/puppeteer-extra/issues/589)

### Relevant log output

```typescript
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@maaaariana thanks for reporting. Unfortunately this is specific to Chrome and nothing where WebdriverIO can have an impact. I might be wrong, if so I am happy to re-open but I don't think any changes in WebdriverIO could fix this.
