### ISSUE TITLE
[🐛 Bug]: It seems that the `World` class from cucumber isn't exported like all other cucumber exports

### ISSUE THREAD

**Issue by dietergeerts** [webdriverio/webdriverio#7755]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

^7

### Node.js Version

14

### Mode

WDIO Testrunner

### What happened?

I want to set a custom world class, and in the cucumber docs, they state to extend the World class, but that class isn't re-exported like all other cucumber exports (`setWorldConstructor`, `Given`, ....)

I could use that class directly from the `@cucumber/cucumber` package, but I don't know if there would be side-effects, as that's one of the reasons for the re-exports as far as I understand.

### What is your expected behavior?

I can import `World` from `@wdio/cucumber-framework`

### How to reproduce the bug.

```ts
import { setWorldConstructor } from '@wdio/cucumber-framework';

// No `World` class exported to create the custom world class.
```

### Relevant log output

```typescript
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
fixed in #7757
