### ISSUE TITLE
isVisible() returns a Promise that never resolves

### ISSUE THREAD

**Issue by jwalton** [webdriverio/webdriverio#776]
I'm having a problem where I'm calling into webdriverIO, and it appears webdriverIO is never returning.  Looking for advice on how to figure out what's going on here (since I am not a Selenium ninja.)

I'm upgrading a pile of old tests from an ancient version of webdriverJS to webdriverIO.  In our old code, we had defined a `waitForVisible`, which is similar to the webdriverIO version, except it doesn't care if the element is acually on the screen or not.  So I renamed our existing one to `benbriaWaitForVisible()`, and reimplemented it using `waitUntil()`.  Here's the coffee-script code:

```
# This is just like waitForVisible, except it doesn't care if the item is in the viewport or not.
client.addCommand 'benbriaWaitForVisible', (cssSelector, timeInMs, reverse=false) ->
    @waitUntil(
        ->
            @isVisible(cssSelector)
            .then (isVisible) ->
                return if reverse then !isVisible else isVisible
        timeInMs
    )
    .catch (err) ->
        msg = "Selector #{cssSelector} did not become #{if reverse then 'in' else ''}visible after #{timeInMs}ms"
        screenshot(this, msg)
        .then -> throw new Error msg
```

`screenshot()` here is a function that saves a screenshot to /tmp.

So, all is well, and tests are all passing on my macbook, but when I commit this, it fails on our CI server (codeship.) And it always fails in exactly the same place.  The error says it's looking for the selector `#name`, but it didn't show up on the page after a 5 second wait.  In the screenshot, though, I can see #name is right there.

Since this is on codeship, I have limited debugging ability, so I hack up the above to look like:

```
# This is just like waitForVisible, except it doesn't care if the item is in the viewport or not.
client.addCommand 'benbriaWaitForVisible', (cssSelector, timeInMs, reverse=false) ->
    @waitUntil(
        ->
            console.log new Date(), "Looking for #{cssSelector}"
            @isVisible(cssSelector)
            .then (isVisible) ->
                console.log "#{cssSelector} is visible? #{isVisible} #{if reverse then !isVisible else isVisible}"
                return if reverse then !isVisible else isVisible
        timeInMs
    )
    .catch (err) ->
        msg = "Selector #{cssSelector} did not become #{if reverse then 'in' else ''}visible after #{timeInMs}ms"
        screenshot(this, msg)
        .then -> throw new Error msg
```

Note there's now a `console.log()` right before the call into `isVisible()`, and another when `isVisible()` resolves.

And, here's where things get interesting, because on codeship, in all the tests up to this one, everything works as expected, and I get output like:

```
Thu Sep 10 2015 20:29:34 GMT+0000 (UTC) 'Looking for #advanced-account-settings-views'
#advanced-account-settings-views is visible? true true
Thu Sep 10 2015 20:29:35 GMT+0000 (UTC) 'Looking for #advanced-account-settings-views'
#advanced-account-settings-views is visible? true true
```

but when I try to run this test, the output I get is:

```
Thu Sep 10 2015 20:29:38 GMT+0000 (UTC) 'Looking for #name'
Selector #name did not become visible after 5000ms  Screenshot saved at 
	 /tmp/selenium-screenshot-timeout-1441913956324.png
```

You'll notice that the `"#name is visible?"` debug line didn't get printed.  It's like the call to isVisible isn't returning.  So *then* I hacked this up to look like this ugly mess:

```
promiseWithTimeout = (ms, p) ->
    return new Promise (resolve, reject) ->
        done = false
        timer = setTimeout(
            ->
                if !done
                    done = true
                    reject new Error 'Timeout'
            ms
        )
        p.then(
            (result) ->
                if !done
                    done = true
                    clearTimeout timer
                    resolve result
            (err) ->
                if !done
                    done = true
                    clearTimeout timer
                    reject err
        )

# This is just like waitForVisible, except it doesn't care if the item is in the viewport or not.
client.addCommand 'benbriaWaitForVisible', (cssSelector, timeInMs, reverse=false) ->
    @waitUntil(
        ->
            promiseWithTimeout(250, @isVisible(cssSelector))
            .then (isVisible) ->
                return if reverse then !isVisible else isVisible
            .catch (err) ->
                console.log "    Warning: Error while looking for #{cssSelector} - will try again:", err
                return false
        timeInMs
    )
    .catch (err) ->
        msg = "Selector #{cssSelector} did not become #{if reverse then 'in' else ''}visible after #{timeInMs}ms"
        screenshot this, msg
        .then -> throw new Error msg
```

And, sure enough, now this test is passing, although I see two console.logs for this "Timeout" error before it does.

**Comment by christian-bromann** [comment]
Thanks for this amazing issue post. I love if people are as descriptive as possible! :+1: 

I think we are dealing with a racing condition here. At the time were you check for visibility the element seems not to exist on the page. Could you put a `waitForExist` right in front of it?

```coffee
# This is just like waitForVisible, except it doesn't care if the item is in the viewport or not.
client.addCommand 'benbriaWaitForVisible', (cssSelector, timeInMs, reverse=false) ->
    @waitUntil(
        ->
            @waitForExist(cssSelector)
            .isVisible(cssSelector)
            .then (isVisible) ->
                return if reverse then !isVisible else isVisible
        timeInMs
    )
    .catch (err) ->
        msg = "Selector #{cssSelector} did not become #{if reverse then 'in' else ''}visible after #{timeInMs}ms"
        screenshot(this, msg)
        .then -> throw new Error msg
```

If this doesn't work `isVisible` seems to throw an error. Could you log the error message in your catch block?

**Comment by jwalton** [comment]
Oooohhhhh...  It's not waiting 5 seconds at all.  It's throwing an error and I'm catching it and ignoring it.  -_-

So, yeah, problem was:

```
Unexpected modal dialog (text: This page is asking you to confirm that you want to leave - data you have entered may not be saved.): This page is asking you to confirm that you want to leave - data you have entered may not be saved.
```

Thanks for the help, sir.  :)
