### ISSUE TITLE
implement error hook

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#777]
It can sometimes be useful to react on certain errors in order to get an idea about what went wrong. Currently user can register error handlers to do that but the disadvantage of event handler is that they are running independent from the execution flow.

I was running into an use case where my test occasionally failed due to an error in my rest api. The only error message I was able to generate was that submitting the form wasn't successful. I wasn't able to get behind the actual error response to make the error more meaningful.

Therefor it makes sense to implement some kind of error hook that gets executed if an command fails. Thanks to the monadic structure of WebdriverIO this needs to get implemented at a [single point in the code](https://github.com/webdriverio/webdriverio/blob/master/lib/webdriverio.js#L174-L195). Before we actually reject the command promise we execute the hook. This allows us to accept further promises so the user is able to do certain command actions before the error gets thrown.

This would solve my initial issue. Instead of just accepting that the form wasn't submitted successfully I could execute another command that can grab error logs from the console.

Question to answer:
1. Why not just catch a possible error and throw after getting the logs?
2. How should user be able to react only on certain errors?
3. Does this actually make sense :laughing: ?

**Comment by jhoguet** [comment]
if the intent is for an instance of a command, then I must be missing something, why not just handle the rejection. 

If it is a more global handler, like before rejecting commands of type x, do y... I see potential there. 

In our code base we have some hackery trying to basically make it so that on a failed command we can get a console dump, html dump, and screenshot - and it sounds like this might make that easier...

**Comment by christian-bromann** [comment]
> If it is a more global handler, like __before__ rejecting commands of type x, do y... I see potential there.

yeah it's like that..like a before hook for rejected commands

**Comment by georgecrawford** [comment]
Might this also work for the `StaleElementReference` issue described in #748?

**Comment by christian-bromann** [comment]
Implemented in the monad see #969. Let's continue convo there.
