### ISSUE TITLE
[🐛 Bug]: Can't switch windows via devtools

### ISSUE THREAD

**Issue by jan-molak** [webdriverio/webdriverio#7770]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.10

### Node.js Version

16.13.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    headless: true,
    automationProtocol: 'devtools',

    capabilities: [{

        browserName: 'chrome',
        'goog:chromeOptions': {
            args: [
                '--disable-web-security',
                '--allow-file-access-from-files',
                '--allow-file-access',
                '--disable-infobars',
                '--ignore-certificate-errors',
                '--headless',
                '--disable-gpu',
                '--disable-gpu',
                '--window-size=1024x768',
            ],
        }
    }],
};
```

### What happened?

It looks like the fix introduced by @mgrybyk in #4472 is missing from the [current version](https://github.com/webdriverio/webdriverio/blob/v7.16.10/packages/devtools/src/commands/getWindowHandles.ts), which means that `switchWindow` API doesn't work when used with the `devtools` protocol (`browser.getWindowHandles()` returns an array with one entry for the current window, instead of all the handles for all the open windows/tabs)

CC: @christian-bromann @mgrybyk 

### What is your expected behavior?

I'd like to be able to use WebdriverIO to switch to new windows created by a JavaScript interaction.

### How to reproduce the bug.

Navigate to a page that opens a new pop-up window, for example:

```html
<html lang="en">
<head>
    <title>Main page</title>
</head>
<body>
    <h1>Main page</h1>
    <ul>
        <li><a href="javascript:void(0)" onclick="popup()" id="new-popup-link">open new popup</a></li>
    </ul>


    <script>
        function popup() {
            var w = window.open('about:blank', 'new-popup', 'width=512,height=256');
            w.document.write('<h1>New pop-up</h1>');
            w.document.close();
        }
    </script>
</body>
</html>
```

Click on the `$("#new-popup-link")` to open the pop-up and see that `browser.getWindowHandles()` returns an array of 1 window handle instead of 2 window handles.

### Relevant log output

```typescript
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by gauravgandhi1315** [comment]
I have been facing the same issue. Thanks for reporting

**Comment by jan-molak** [comment]
OK, interestingly enough, it looks like the latest version of WebdriverIO _shouldn't_ need patch #4472 because it _should_ solve the problem of keeping track of the open windows via [`targetcreated` and `targetdestroyed` handlers](https://github.com/webdriverio/webdriverio/blob/ba5e0fbbe47348c0ec81c77ea8521f1d34abe3f3/packages/devtools/src/devtoolsdriver.ts#L33-L34).

I'll keep debugging.

**Comment by christian-bromann** [comment]
@jan-molak shall we keep the issue to follow up on this?

**Comment by jan-molak** [comment]
@christian-bromann - sure, although this is more of a feature request than a bug report since WDIO seems to be working correctly as long as I synchronise it on my side.

What I think would be a nice addition is for WDIO to auto-wait when switching windows, in a similar way it auto-waits for an element to be clickable.

**Comment by christian-bromann** [comment]
Agree, mind raising an issue for it?
