### ISSUE TITLE
[💡 Feature]: Support playwright

### ISSUE THREAD

**Issue by DudaGod** [webdriverio/webdriverio#7776]
### Is your feature request related to a problem?

Hello.

Webdriverio already supports the ability to use [puppeteer](https://pptr.dev/) under the hood. But there is another more promising tool - [playwright](https://playwright.dev/) which is rapidly developing. Playwright has similar API with puppeteer and his core feature - ability to run tests in chrome, firefox and safari (using CDP protocol).

What do you think about supporting playwright in wdio?

### Describe the solution you'd like.

I want to be able to use playwright with wdio just like puppeteer is used.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by erwinheitzman** [comment]
There's no difference in how you'd use it as far as I am aware.
Both use the Devtools protocol so I don't think there's a point in implementing this right now but feel free to share why you think this would add value

**Comment by christian-bromann** [comment]
Adding support for PW would enable users to use WebdriverIO APIs, particularly the ones that use CDP functionality, across multiple browser. So there is definitely a value add for having support for it.

That said, it was a lot of work to implement all WebDriver commands with Puppeteer and I am sure we are still not 100% there. So adding PW would be even more work given their API has diverged from the Puppeteer one. In addition to that PW provides its own testrunner so I doubt people would pick a WebdriverIO / PW setup if they can just go with PW straight.

@DudaGod if you are open to implement support for it I recommend have a look into the [`devtools`](https://www.npmjs.com/package/devtools) package and copy/paste the code to use it with Playwright. I doubt though that the WebdriverIO team has the bandwith to add native support for it.

What do you all think?

**Comment by DudaGod** [comment]
> In addition to that PW provides its own testrunner so I doubt people would pick a WebdriverIO / PW setup if they can just go with PW straight.

But if developers need to also test browsers that don't support cdp protocol then they need to have two tools (pw for cdp and something else for w3c/jwp). So in my opinion the wrapper over PW makes sense.

> @DudaGod if you are open to implement support for it I recommend have a look into the devtools package and copy/paste the code to use it with Playwright. I doubt though that the WebdriverIO team has the bandwith to add native support for it.

Yes, I want to try to implement it. I will look at devtools package and in PW source code. Thank you.

**Comment by erwinheitzman** [comment]
@christian-bromann as far as I am aware they use a version of the browsers where they have added support of the CDP on top where needed. Maybe we can utilize Puppeteer when using those versions of the browsers instead? Not sure if that would work though.

**Comment by christian-bromann** [comment]
> I mean you cannot start firefox\webkit session by selenium and use PW features. PW connection to existing browser session supported only for chromium.

That is totally true @BorisOsipov !

> Maybe we can utilize Puppeteer when using those versions of the browsers instead?

Honestly I was never a big fan of their idea of patching browser engines to hack CDP support into browser. If the PW team would have but as much energy into enhancing the WebDriver specification we would have been much better off. That said, I have reserved feelings about adding PW support. The team behind it has been hostile against web standards. If someone is interested putting the work into making this reality I am happy to do the work on the WebdriverIO side to make the integration as seamless as we have with Puppeteer.

Anyhow, this is certainly not something we want to put on our roadmap, therefor I will close the discussion. @DudaGod I am happy to support you with everything needed from the WebdriverIO side.
