### ISSUE TITLE
[🐛 Bug]: cannot read property 'selenoid:options' of undefined - during watch mode

### ISSUE THREAD

**Issue by Badisi** [webdriverio/webdriverio#7780]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

14.17.5

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
    browserName: 'chrome',
    acceptInsecureCerts: true
}
```

### What happened?

Using the `mock` api during `watch` mode will work fine during the first run but will trigger the following error the second time :
```sh
[chrome (unknown) #0-0] Cannot read property 'selenoid:options' of undefined
[chrome (unknown) #0-0] TypeError: Cannot read property 'selenoid:options' of undefined
[chrome (unknown) #0-0]     at Browser.getPuppeteer (/Users/test/app-test/node_modules/webdriverio/build/commands/browser/getPuppeteer.js:71:52)
[chrome (unknown) #0-0]     at Browser.wrapCommandFn (/Users/test/app-test/node_modules/@wdio/utils/build/shim.js:131:38)
[chrome (unknown) #0-0]     at async Browser.mock (/Users/test/app-test/node_modules/webdriverio/build/commands/browser/mock.js:119:9)
[chrome (unknown) #0-0]     at async Browser.wrapCommandFn (/Users/test/app-test/node_modules/@wdio/utils/build/shim.js:131:29)
```

This seems related to https://github.com/webdriverio/webdriverio/issues/7086

### How to reproduce the bug.

Simply use a basic mock example (as from the [doc](https://webdriver.io/docs/api/browser/mock/)):

```ts
it('should modify http responses', async () => {
    const mock = await browser.mock('http://localhost:4200')
    mock.respond('test');
});
```

Then:

1. Start your test in watch mode
```sh
wdio run wdio.config.ts --watch
```
2. Wait for the test to run
```
=> result: passing !
```
3. Save your test file to trigger a new test run
```
=> result: cannot read property 'selenoid:options' of undefined
```

### Relevant log output

```typescript
[chrome (unknown) #0-0] Cannot read property 'selenoid:options' of undefined
[chrome (unknown) #0-0] TypeError: Cannot read property 'selenoid:options' of undefined
[chrome (unknown) #0-0]     at Browser.getPuppeteer (/Users/test/app-test/node_modules/webdriverio/build/commands/browser/getPuppeteer.js:71:52)
[chrome (unknown) #0-0]     at Browser.wrapCommandFn (/Users/test/app-test/node_modules/@wdio/utils/build/shim.js:131:38)
[chrome (unknown) #0-0]     at async Browser.mock (/Users/test/app-test/node_modules/webdriverio/build/commands/browser/mock.js:119:9)
[chrome (unknown) #0-0]     at async Browser.wrapCommandFn (/Users/test/app-test/node_modules/@wdio/utils/build/shim.js:131:29)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

It seems that we don't correctly pass in the arguments when we rerun a session. My first guess is in [`watcher.ts`](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-cli/src/watcher.ts#L167-L168) but not entirely sure.

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by Badisi** [comment]
I think so, because when the method [getPuppeteer.ts#L45](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/browser/getPuppeteer.ts#L45) is called:

#### The first time

Both `capabilities` and `requestedCapabilities` are properly set.

<img width="470" alt="Screen Shot 2021-12-06 at 12 34 06" src="https://user-images.githubusercontent.com/674862/144839869-e7addebd-db7d-4621-92bc-60ea1404b067.png">

#### The second time

Most of the previous info are lost.

<img width="463" alt="Screen Shot 2021-12-06 at 12 35 26" src="https://user-images.githubusercontent.com/674862/144839793-34acfa10-3718-484f-abb5-7c96ce73e6f2.png">

----

I would be glad to help, as always, but unfortunately after further investigation I think it requires more knowledge of the library than I have..

**Comment by ari-meetai** [comment]
Could this be related to [#7086](url) ?

I can still repro this right now with Chrome 100.

**Comment by christian-bromann** [comment]
@ari-meetai any contribution that helps fixing the issue is welcome!

**Comment by Badisi** [comment]
@ari-meetai, yes I think so
(that's what I said in the **What happened?** section)

**Comment by Badisi** [comment]
@ari-meetai, are you still facing this issue ?

Because I don't know what fixed it, but I got it working with the following configuration:
```json
  "@wdio/cli": "^7.19.5",
  "@wdio/jasmine-framework": "^7.19.5",
  "@wdio/local-runner": "^7.19.5",
  "@wdio/spec-reporter": "^7.19.5",
  "chromedriver": "^100.0.0",
```

**Comment by christian-bromann** [comment]
I will close this due to inactivity. We've done various further improvements to the watch mode so if this bug still seems to be valid I am happy to re-open.

**Comment by kenchen-asurion** [comment]
I'm experiencing the same issue when trying to mock API calls in component tests.

```
TypeError: Cannot read properties of undefined (reading 'selenoid:options')
    at Browser.getPuppeteer (http://localhost:52696/node_modules/@wdio/browser-runner/node_modules/webdriverio/build/commands/browser/getPuppeteer.js?v=7bf5bdff:67:52)
    at Browser.wrapCommandFn (http://localhost:52696/node_modules/@wdio/utils/build/shim.js?v=7bf5bdff:88:38)
    at Browser.<anonymous> (http://localhost:52696/node_modules/@wdio/utils/build/shim.js?v=7bf5bdff:240:24)
    at Browser.mock (http://localhost:52696/node_modules/@wdio/browser-runner/node_modules/webdriverio/build/commands/browser/mock.js?v=7bf5bdff:115:20)
    at Browser.wrapCommandFn (http://localhost:52696/node_modules/@wdio/utils/build/shim.js?v=7bf5bdff:88:38)
    at Browser.mock (http://localhost:52696/node_modules/@wdio/utils/build/shim.js?v=7bf5bdff:240:24)
    at Context.<anonymous> (http://localhost:52696/Users/[redacted]:96:45)
```

The line of code that is breaking is when I call `browser.mock`
```
const apiPOSTMock = await browser.mock("**/api", {
  method: "post",
});
```

I tried to set `selenoid:options` in the capabilities object in `wdio.conf.ts`, but that doesn't work
```
capabilities: [
    {
      // capabilities for local browser web tests
      browserName: "chrome", // or "firefox", "microsoftedge", "safari"
      "selenoid:options": {
        enableVNC: true,
        enableVideo: true,
      },
      "moon:options":{}
    },
  ],
```

I've attached my wdio config file and package json below for additional context. Any advice would be appreciated.
[configs.zip](https://github.com/webdriverio/webdriverio/files/13982156/configs.zip)

**Comment by christian-bromann** [comment]
@kenchen-asurion can you raise a new issue titled: "Support `mock` command for browser-runner"? This capability is not yet enabled when running tests within the browser. We definitely want to make this experience seamless now that the command will allow mocking cross browser at some day.

In the meantime I recommend to mock the complete `fetch` command from the global window scope.
