### ISSUE TITLE
[🐛 Bug]: Modified clicks (Control Click, Shift Click) on Chromedriver protocol does not work

### ISSUE THREAD

**Issue by jporley** [webdriverio/webdriverio#7793]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16

### Node.js Version

14.17

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
      browserName: 'chrome',
      'goog:chromeOptions': {
        useAutomationExtension: false,
        args: ['ignore-certificate-errors-spki-list=NpRJBrWcf/vumIMC1YbJGJE3OmN2U8VV8q4YGKkoS7Y='],
        w3c: true
      }
    }
```

### What happened?

We are running webdriverio v7.16 on sync mode.
In order to control+click elements (or any other click modifier like Shift) we need to use browser.performActions, sending the key down signal, then clicking, and then sending the keyup signal.
This **works properly for DevTools** protocol but **not for Chromedriver**. We have tested many solutions and have not gotten it to work with Chromedriver at all. **This used to work for us in version 6**

There is **no logged errors** or things that don't go as expected. The click happens, but it is not modified, for instance Control+Click is just as if you do the Click. Shift + Click will not select text, it will just click.

### What is your expected behavior?

Click be affected by the key that we are holding down. Or at least another way to tap into Control+Click or Shift+Click.

### How to reproduce the bug.

To reproduce:
```
browser.performActions([
      {
        type: 'key',
        id: 'keyboard',
        actions: [{ type: 'keyDown', value: '\uE009' }]
      }
    ]);

// click on an element in UI

browser.performActions([
      {
        type: 'key',
        id: 'keyboard',
        actions: [{ type: 'keyUp', value: '\uE009' }]
      }
    ]);
```

Note:
We have also tested a solution entirely through performActions which doesn't work either, as such:
```
browser.performActions([
      {
        type: 'key',
        id: 'keyboard',
        actions: [{ type: 'keyDown', value }]
      },
      {
        type: 'pointer',
        id: 'pointer1',
        parameters: { pointerType: 'mouse' },
        actions: [
          { type: 'pointerMove', x: targetX, y: targetY },
          { type: 'pointerDown', button: 0 },
          { type: 'pointerUp', button: 0 }
        ]
      },
      {
        type: 'key',
        id: 'keyboard2',
        actions: [{ type: 'keyUp', value }]
      }
    ]);
``` 

### Relevant log output

```typescript
There are no error/warning logs when this happens, the click is just not modified as it should.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
It seems that the browser driver doesn't correct apply the click. I wonder how WebdriverIO can mitigate the issue given that it seems to be to be the fault of Chromedriver. Any suggestions?

**Comment by jporley** [comment]
Quite honestly I'm hoping that someone comes in with some sort of alternative to this, it can't be the case that nobody else is using modified clicks on version 7?

**Comment by christian-bromann** [comment]
@jporley with v8 we know added a better action interface. We also now expose a `Key` object that allows to easier access special characters, e.g.:

```ts
import { Key } from 'webdriverio'

// ...
await browser.action('key)
            .down(Key.Ctrl).down('c')
            .pause(10)
            .up(Key.Ctrl).up('c')
            .perform()
```

This should help making these special interaction possible. Let me know if you still experience any problems with this.

**Comment by burdeasa** [comment]
> I had issues with ctrl+multipleclick
> 
> This worked for me
> 
> ```
>     await browser.performActions([
>         {
>           type: "key",
>           id: "keyboard",
>           actions: [{ type: "keyDown", value: "" }],
>         },
>       ]);
>     await campaignNameColumn.click();
>     await monthColumn.click();
>     await browser.performActions([
>       {
>         type: "key",
>         id: "keyboard",
>         actions: [{ type: "keyUp", value: "" }],
>       },
>     ]);
> ```

It looks like the magic string needed for `value` above is '\uE009' to represent the Ctrl key. I think the corresponding value for Shift is '\uE008'.
