### ISSUE TITLE
add waitForAlert and isAlertPresent commands

### ISSUE THREAD

**Issue by jwalton** [webdriverio/webdriverio#780]
In `alertText()`, there's [this example](http://webdriver.io/api/protocol/alertText.html):

```
// close a dialog box if is opened
client.alertText( function( err, res ) {
    if ( res != null ) {
        this.alertDismiss()
    }
});
```

But, if I actually try this, I get an error: 'Error: No alert is present'

(Although, I'm actually raising this because I have a test that tries to close an alert, and then it tries to do something else, and when this test runs on Codeship, on what I assume are the slowest VMs in the world, that second command fails because the alert is still open.  A `.pause(500)` fixes it, but it would be better if I had some way to wait for the alert to be gone.)

**Comment by christian-bromann** [comment]
This is not a bug in WebdriverIO or in the docs that is how Selenium works :wink: The command fails if you want to interact with an alert if no alert is present. Maybe it is useful to add `isAlertPresent` and `waitForAlert` to better deal with this. What do you think?

**Comment by jwalton** [comment]
That would be handy, for sure.

**Comment by sean-hill** [comment]
Hey, so the biggest problem with this is that in my: 

	client.on('error', function(e) {

	});

The error keeps rotating between `org.openqa.selenium.UnhandledAlertException` and `unexpected alert open` and never stops, therefore it locks up my test servers. My logs just run wild with `Exception: unexpected alert open` and `unexpected alert open`. Is there any way to fix this?

**Comment by sean-hill** [comment]
I guess another question also is what's the best way to close the session if an error is thrown?

	client.on('error', function(e) {
		client.end();
	});	

I've tried this but for instance, if the error is an `unexpected alert open`, `client.on('error')` is fired indefinitely and never stops.

**Comment by christian-bromann** [comment]
We already have a lot of waitForXXX functions and I don't think adding another one makes much sense since it isn't that common. You can write your own custom command if you want to, the operation is simple:

```js
browser.waitUntil(function() {
    return browser.alertText();
}, 10000);
```

**Comment by briandipalma** [comment]
I don't know how to suggest this as an enhancement to the W3 Webdriver authors but `isAlertPresent` would be a great addition. This is to allow better handling of divergent browser behaviours. For example navigating away from our login page in Chrome launches an alert but not in Fx. This is browser behaviour and not our own code. So in our logout code I'm doing this:

```
  logout() {
    browser.url("");

    if (browser.desiredCapabilities.browserName === "firefox") {
      // Fx doesn't launch an alert when navigating away. You can try/catch the
      // `alertAccept` call below but you end up with spurious error screenshots
      // as Fx has no alert to accept. There is no way to test for the presence
      // of an alert.
      return;
    }

    browser.alertAccept();
  }
```

Which is brittle compared to testing if an alert is present or not. Any chance this could be reopened as a feature request so that this state could be queried without creating error screenshots?
