### ISSUE TITLE
[🐛 Bug]: SauceLabsCapabilities type definition missing properties

### ISSUE THREAD

**Issue by AndruC** [webdriverio/webdriverio#7800]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.9.0

### Node.js Version

14.18.1

### Mode

WDIO Testrunner

### What happened?

When writing configurations for a Typescript project, adding eg. the 'cacheId' capability to the sauce:options key will be identified as a Typescript error, even though it is a valid key.

### What is your expected behavior?

The Typescript defintions should match the Sauce-Specific capabilities documented on the [Sauce Labs Test Configuration Options page](https://docs.saucelabs.com/dev/test-configuration-options/).

### How to reproduce the bug.

In a Typescript project, use the following capabilities definitions with a Typescript validator such as the one included in VSCode:

```js
capabilities: [
  {
    platformName: 'Android',
    'appium:deviceName': 'Samsung_Galaxy_S10_real',
    'sauce:options': {
        cacheId: 'kjldkf'
    },
  }
]      
```

### Relevant log output

```typescript
Types of property ''sauce:options'' are incompatible.
  Type '{ cacheId: string; allowTouchIdEnroll: boolean; build: string; }' is not comparable to type 'SauceLabsCapabilities'.
    Object literal may only specify known properties, and 'cacheId' does not exist in type 'SauceLabsCapabilities'. ts(2352)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

@AndruC would you like to add this property to our types [here](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-types/src/Capabilities.ts#L586-L849)?

**Comment by wswebcreation** [comment]
@AndruC 

Keep in the back of your mind that the support for W3C for the Real Device Cloud has been postponed to beginning of 2022, see [this](https://support.saucelabs.com/hc/en-us/articles/4412359870231?utm_source=beamer&utm_medium=sidebar&utm_campaign=Upcoming-W3C-Support-Release-date-extended-for-Appium-Tests-on-Real-Devices&utm_content=ctalink) message due to a breaking changing for customer who are using a mix of JWP and W3C caps. 
Sauce Labs wants to give customer more time to fix this.

**Comment by christian-bromann** [comment]
I went ahead and added them.
