### ISSUE TITLE
[🐛 Bug]: Element nextElement/previousElement/parentElement not chainable

### ISSUE THREAD

**Issue by alexmi256** [webdriverio/webdriverio#7804]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### What happened?

Maybe this is a known limitation/not-yet-implemented but it seems that the `nextElement`, `previousElement`, and `parentElement` Element functions are not chainable.
With example demo genrated test for https://the-internet.herokuapp.com/login: 
- `await $('#login').$('#username').isExisting()` works
- `await $('#username').nextElement().isExisting())` does not and throws `TypeError: $(...).nextElement(...).isExisting is not a function`

### What is your expected behavior?

The `nextElement`, `previousElement`, `parentElement`  functions allow for chaining.

### How to reproduce the bug.

Set up demo test.
Replace code with:
```
        await browser.url(`https://the-internet.herokuapp.com/login`);
        console.log(await $('#login').$('#username').isExisting());
        console.log(await $('#username').nextElement().isExisting());
```

### Relevant log output

```typescript
No relevant output AFAICT
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

I believe this can be fixed by just adding these commands [here](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-utils/src/shim.ts#L70). You want to take a stab at this?

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by alexmi256** [comment]
I'll take a stab at it

**Comment by praveendvd** [comment]
@alexmi256  you just have to update with all the required commands  : 

https://github.com/webdriverio/webdriverio/blob/880509c9573f136c634683fd73a2e0a034843184/packages/wdio-utils/src/shim.ts#L70

**Comment by praveendvd** [comment]
@christian-bromann  and @erwinheitzman 

One quick question , why chaining is restricted the QUERY commands ? cant we just wrap everything with chainable ?
