### ISSUE TITLE
Unclear on the order of browsers given to callbacks while using multiremote.

### ISSUE THREAD

**Issue by ngokevin** [webdriverio/webdriverio#781]
When using multiremote, we do something like...

```js
var multiremote = {
  firefox: // ...
  chrome: // ...
}

client.screenshot().then(function(browserA, browserB) {
// ...
```

How are we supposed to know which order the browsers are passed in the callback of the client promise? Previously, the argument passed to the callback was a single object with browsers as the object key, which made it predictable.

**Comment by christian-bromann** [comment]
If you define the browser like

```js
var multiremote = {
  firefox: // ...
  chrome: // ...
}
```

then the order is exactly like this:
```js
client.screenshot().then(function(firefox, chrome) {
// ...
```

**Comment by ngokevin** [comment]
I see, didn't know that since the concept of maps don't really have guaranteed order when it comes to the order of the keys defined.

Sometimes I would like to be able to refer to the multiremote config of the browser, so this way I have to keep track of the order of my multiremote config in order to reference back to it. 

Anyways, thanks!
