### ISSUE TITLE
[🐛 Bug]: browser.switchToFrame() doesn't work as expected

### ISSUE THREAD

**Issue by unickq** [webdriverio/webdriverio#7820]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.12

### Node.js Version

14.18.2

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
   browserName: "firefox",
   browserName: "chrome"
}
```

### What happened?

browser.switchToFrame() doesn't work.

**Selenium Grid:** 3.141.59, 4.0.0 and 4.1.0
**Browsers:** Chrome 96, Firefox 94

### How to reproduce the bug.

```js
it('Failing example', async () => {
   await browser.url('https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file')
   const frame = await $('#frame_Limiting_accepted_file_types')
   await browser.switchToFrame(frame)
});
```

### Relevant log output

```
Chrome

ERROR webdriver: Request failed with status 400 due to invalid argument: invalid argument: missing 'ELEMENT'
[0-0]   (Session info: chrome=96.0.4664.110)
Uncaught Error: invalid argument: missing 'ELEMENT'
  (Session info: chrome=96.0.4664.110)
```

```
Firefox 

ERROR webdriver: Request failed with status 400 due to invalid argument: data did not match any variant of untagged enum FrameId at line 1 column 9
Uncaught:
Error: data did not match any variant of untagged enum FrameId at line 1 column 9
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by n8sloat** [comment]
@unickq I am seeing this same issue.  What was the resolution?

**Comment by dreuxl** [comment]
same here :(

**Comment by christian-bromann** [comment]
If you encounter an issue that looks like this, please provide a reproducible example!
