### ISSUE TITLE
[🐛 Bug]: Spec status shows passed even if one spec failed 

### ISSUE THREAD

**Issue by praveendvd** [webdriverio/webdriverio#7822]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.12

### Node.js Version

v16.5.0

### Mode

WDIO Testrunner

### What happened?

Final spec result shows passed even if one test inside spec fails for **Jasmine framework**

### What is your expected behavior?

if any test fails, then spec should fail. 

### How to reproduce the bug.

[package.zip](https://github.com/webdriverio/webdriverio/files/7735541/package.zip)

### Relevant log output

![image](https://user-images.githubusercontent.com/45095911/146554003-45dc1db9-444c-479e-98ce-e205b988dcfd.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by praveendvd** [comment]
await expect(SecurePage.flashAlert).not.toBeExisting(); , issue is with only such async expect , for normal expect it works as expected

**Comment by praveendvd** [comment]
@christian-bromann  i will take it up , it seems e.emit is having some exeception thrown

**Comment by praveendvd** [comment]
https://github.com/webdriverio/webdriverio/blob/ff33119250bfe1cd47ef68472b2f5e9058d14c32/packages/wdio-reporter/src/stats/test.ts#L126

THe actual value is a promise not a resolved value ,

**Comment by christian-bromann** [comment]
Thanks for taking this up, let's continue convo in #7823
