### ISSUE TITLE
How to integrate Appium with WebdriverIO

### ISSUE THREAD

**Issue by amiya-pattnaik** [webdriverio/webdriverio#783]
Hi,
We are new to mobile testing. We just downloaded and installed Appium. We ran few of the sample code (Javascript binding) on IOS simulator using Safari and sample app. It is working. We just want to use WebdriverIO code. Need your help on integrating it and sample code. 

Appreciate your help. 

Thanks,
Amiya

**Comment by christian-bromann** [comment]
Hi Amiya,

please checkout [the examples](https://github.com/webdriverio/webdriverio/tree/master/examples/standalone)

Cheers
Christian

**Comment by christian-bromann** [comment]
oh and fyi: feel free to join the gitter chat. You will get your answer much quicker than here.

**Comment by amiya-pattnaik** [comment]
Thanks a lot Chris for you help. We will go through it and will let you know if we are facing any issues. 
I appreciate your help. 
Regards,
Amiya
