### ISSUE TITLE
[🐛 Bug]: no types defined for appium xcui driver capabilities

### ISSUE THREAD

**Issue by amandaflagg** [webdriverio/webdriverio#7843]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

14.16.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: {
        //desktop browser
        chromeBrowser: {
            port: 4444,
            path: '/wd/hub',
            capabilities: {
                browserName: 'chrome',
                'goog:chromeOptions': {
                    args: [
                        '--use-fake-device-for-media-stream',
                        '--use-fake-ui-for-media-stream',
                    ],
                },
            },
        },
        //appium ios app
        iosApp: {
            capabilities: {
                port: 4723,
                platformName: 'iOS',
                automationName: 'XCUITest',
                deviceName: 'iPhone 11',
                orientation: 'PORTRAIT',
                bundleId: 'pro.org.sdk.App',
                updatedWDABundleId: 'io.appium.WebdriverAgentRunner',
                autoAcceptAlerts: true,
                xcodeSigningId: 'iPhone Developer',
                xcodeOrgId: '0000000000',
                udid: '00000000-0000000000000000'
            },
        },
    },
```

### What happened?

The TypeError `Type 'string' is not assignable to type 'WebdriverIO'.ts` is shown when using any the following capabilities as defined by [appium-xcuitest-driver](https://github.com/appium/appium-xcuitest-driver#desired-capabilities):
updatedWDABundleId
xcodeSigningId
xcodeOrgId

### What is your expected behavior?

Are additional Appium iOS types supported, or should they be defined as needed when used in individual projects? I see that all the general iOS Appium types are defined in the [capabilities types file](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-types/src/Capabilities.ts), but none of the additional capabilities are, such as the ones provided by [Appium specifically for XCUITest](https://appium.io/docs/en/writing-running-appium/caps/#ios-only-using-xcuitest).

When using some of the XCUITest Appium capabilities, they throw TypeErrors within my project.

### How to reproduce the bug.

To reproduce the bug, paste the following into a WDIO Typescript project as the conf file: https://gist.github.com/amandaflagg/cd4183d4e5e94537f3949cd3ca3a0f2f

### Relevant log output

```typescript
none applicable
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks @amandaflagg for filing the issue. Seems that @praveendvd has picked it up in #7844 👏  Let's continue convo in the PR.
