### ISSUE TITLE
[🐛 Bug]: Mobile App closes in Android emulator and WDIO script terminates as passed

### ISSUE THREAD

**Issue by Zarmeena** [webdriverio/webdriverio#7845]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7

### Node.js Version

16.13.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
platformName: 'Android',
'appium:deviceName': 'emulator-5554',
'appium:udid': 'emulator-5554',
'appium:automationName': 'UiAutomator2',
'appium:platformVersion': '11',
'appium:orientation': 'PORTRAIT',
'appium:autoGrantPermissions': true,
'appium:newCommandTimeout': 240,
'appium:app': '<path to apk>'
```

### What happened?

App is getting closed initially during the test execution and no elements are identified, Following is the error:

[0-0] 2021-12-23T11:19:05.866Z WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Cannot read properties of null (reading 'jwproxy')

### What is your expected behavior?

App should be launched and elements be clicked to complete the execution without any error

### How to reproduce the bug.

browser.switchContext('NATIVE_APP');
browser.pause(25000);
$(link).waitForDisplayed(15000);
browser.takeScreenshot();
if($(link).isDisplayed())
$(link).click();

### Relevant log output

```typescript
[0-0] 2021-12-23T11:19:05.882Z WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Cannot read properties of null (reading 'jwproxy')
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by praveendvd** [comment]
@Zarmeena  could you try passing "appium:plaform"

**Comment by Zarmeena** [comment]
@praveendvd 'appium:platform' instead of 'platformName'?

**Comment by praveendvd** [comment]
> @praveendvd 'appium:platform' instead of 'platformName'?

Yes, could Yoh try that

**Comment by praveendvd** [comment]
@Zarmeena  Any update on this , where you able to make it work ?

**Comment by Zarmeena** [comment]
App was crashing due to the incompatibility of WebdriverIO sync libraries with NodeJS v16. Script is working fine on downgrading the node version to v14
