### ISSUE TITLE
[🐛 Bug]:  Error:  Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.

### ISSUE THREAD

**Issue by wbigno** [webdriverio/webdriverio#7854]
Just upgraded to v7, here is my package.json
{
  "name": "nyl-aem-automation",
  "version": "1.0.0",
  "description": "NYL.com AEM Automation Framework",
  "main": "./node_modules/.bin/wdio",
  "scripts": {
    "test.local": "npx wdio wdio.conf.js",
    "test.sauce": "wdio run wdio.saucelabs.allbrowsers.conf.js",
    "test.sauce.chrome": "wdio run wdio.saucelabs.chrome.conf.js",
    "test.sauce.firefox": "wdio run wdio.saucelabs.firefox.conf.js",
    "test.sauce.safari": "wdio run wdio.saucelabs.safari.conf.js",
    "test.sauce.edge": "wdio run wdio.saucelabs.edge.conf.js",
    "test.sauce.ie": "wdio run wdio.saucelabs.ie.conf.js",
    "lint": "eslint .",
    "report": "allure generate report/allure-results  && allure open",
    "report.ci": "allure generate report/allure-results --clean -o allure-report && allure open"
  },
  "author": "William Bigno <william.m.bigno.iii@accenture.com>",
  "license": "MIT",
  "dependencies": {},
  "devDependencies": {
    "@babel/cli": "^7.14.5",
    "@babel/core": "^7.11.4",
    "@babel/plugin-proposal-class-properties": "^7.10.4",
    "@babel/preset-env": "^7.11.0",
    "@babel/register": "^7.10.5",
    "@wdio/allure-reporter": "^7.16.11",
    "@wdio/cli": "^7.16.12",
    "@wdio/codemod": "^0.9.1",
    "@wdio/cucumber-framework": "^7.16.12",
    "@wdio/devtools-service": "^7.16.12",
    "@wdio/junit-reporter": "^7.16.12",
    "@wdio/local-runner": "^7.16.12",
    "@wdio/logger": "^7.16.0",
    "@wdio/mocha-framework": "^7.16.11",
    "@wdio/sauce-service": "^7.16.12",
    "@wdio/spec-reporter": "^7.16.11",
    "@wdio/sync": "^7.16.12",
    "allure-commandline": "^2.17.2",
    "axios": "^0.24.0",
    "babel-eslint": "^10.1.0",
    "chai": "^4.2.0",
    "chai-html": "^1.3.0",
    "chai-match-pattern": "^1.2.0",
    "chromedriver": "^96.0.0",
    "eslint": "^6.8.0",
    "eslint-config-google": "^0.14.0",
    "eslint-plugin-babel": "^5.3.1",
    "eslint-plugin-mocha": "^6.3.0",
    "global-agent": "^2.1.12",
    "jscodeshift": "^0.13.0",
    "request": "^2.34",
    "request-promise": "^4.2.6",
    "wdio-allure-reporter": "^0.8.3",
    "wdio-chromedriver-service": "^7.2.2",
    "wdio-image-comparison-service": "3.1.0",
    "webdriverio": "^7.16.12",
    "xml2js": "^0.4.23"
  },
  "babel": {
    "presets": [
      [
        "@babel/preset-env"
      ]
    ],
    "plugins": [
      "@babel/plugin-proposal-class-properties"
    ]
  }
}

I now get this error, here is my console log
Execution of 1 workers started at 2021-12-29T11:03:55.556Z

[0-0]
[0-0]
[0-0]
[0-0] ##############################
[0-0] !!CLEARING!!
[0-0] ##############################
[0-0]
[0-0]
[0-0]
[0-0] RUNNING in chrome - C:\Users\T85KZFL\nyl-aem-automation\NYL.AEM.AUTOMATION\test\specs\nyl\component\test\beta-hero-visual-regression.spec.js
[0-0]  Error:  Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
`browser` object has only `capabilities` and some flags like `isMobile`.
Helper files that use other `browser` commands have to be moved to `before` hook.
Spec file(s): C:\Users\T85KZFL\nyl-aem-automation\NYL.AEM.AUTOMATION\test\specs\nyl\component\test\beta-hero-visual-regression.spec.js
Error: ReferenceError: baseUrl is not defined
    at Object.<anonymous> (C:\Users\T85KZFL\nyl-aem-automation\NYL.AEM.AUTOMATION\test\specs\nyl\component\test\/beta-hero-visual-regression.spec.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Module._compile (C:\Users\T85KZFL\nyl-aem-automation\NYL.AEM.AUTOMATION\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Object.newLoader [as .js] (C:\Users\T85KZFL\nyl-aem-automation\NYL.AEM.AUTOMATION\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.implementationOfRequireOrImportForUnstableEsm [as requireOrImport] (C:\Users\T85KZFL\nyl-aem-automation\NYL.AEM.AUTOMATION\node_modules\mocha\lib\nodejs\esm-utils.js:101:12)
[0-0] FAILED in chrome - C:\Users\T85KZFL\nyl-aem-automation\NYL.AEM.AUTOMATION\test\specs\nyl\component\test\beta-hero-visual-regression.spec.js

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:15

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nyl-aem-automation@1.0.0 test.local: `npx wdio wdio.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nyl-aem-automation@1.0.0 test.local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\T85KZFL\AppData\Roaming\npm-cache\_logs\2021-12-29T11_04_11_855Z-debug.log

Previously everything ran fine.. 

I use a super class for my driver with a constructor like this
/** Class representing a global class to initate the browser. */
export default class Common {
/**
 * Global Common Class to initate all browsers.
 * @constructor
 */
constructor() {
	this.title = 'Common Class';
}
/**
 * Function to open url of a specifc page for testing.
 * @param {string} path - url of page being opened.
 */
open(path) {
	browser.url(path);
}
}

I then call the Page Object class from the spec file like this
import hero from '../../../../component/core-experience/hero/core/hero.component';

    describe('Hero - Billboard Style CSS Valdation SM', function() {
        beforeEach(function() {
            hero.openTestBillboardStyleNyl();
            browser.pause(4000);
        });

        it('should compare current Hero - Billboard Style image with a baseline Compare SM Viewport', function() {
            utilities.changeViewport('SM');
            expects(
                browser.checkElement(hero.heroBGColor,
                    'Hero-SM', {
                    fullPageScrollTimeout: '5000',
                }),
            ).to.be.below(0.1);
        });
    });

My Page Object looks like this
import Common from '../../../../../support/utils/common';
import * as urlNyl from '../../../../../support/resouces/beta-nyl-test-page-urls';

/** Class of Container component*/
class hero extends Common {

openTestBillboardStyleNyl() {
super.open(urlNyl.testPageHero2);
return this;
}

export default new hero();

I maintain one file with all url paths that I import to the page object and then reference them.

This method has worked flawless for the last 2 years. but when I did an upgrade yesterday nothing will run now.

**Comment by christian-bromann** [comment]
Please see your error log:

> Error: ReferenceError: baseUrl is not defined
at Object. (C:\Users\T85KZFL\nyl-aem-automation\NYL.AEM.AUTOMATION\test\specs\nyl\component\test/beta-hero-visual-regression.spec.js:3:1)

This causes an error when initialising the test files.

**Comment by JoaqPareja** [comment]
had the same issue, its really annoying
