### ISSUE TITLE
[💡 Feature]: Make `npm install` step optional in CLI wizarrd

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#7864]
### Is your feature request related to a problem?

If someone wants to add WebdriverIO to an existing project it might not be desirable to immediately run `npm install`.

### Describe the solution you'd like.

I suggest to add a question at the end of the wizard to ask whether or not this command should be run (with default set to "yes").

### Describe alternatives you've considered.

n/a

### Additional context

Just saw this as part of `create-remix` and liked the approach.

Everything related to the implementation of the configuration wizard can be found [here](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-cli/src/commands/config.ts).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gpt14** [comment]
I can pick this up

**Comment by praveendvd** [comment]
@christian-bromann  seems this is merged could we close it ?. @gpt14  awesome work ❣️🎉

**Comment by christian-bromann** [comment]
> seems this is merged could we close it ?

Feel free to close such issues yourself as you have all the rights to do it ;-)

**Comment by praveendvd** [comment]
> > seems this is merged could we close it ?
> 
> Feel free to close such issues yourself as you have all the rights to do it ;-) 

Was just wondering whether u had any pending tasks for this ,
