### ISSUE TITLE
[🐛 Bug]: duration property in the afterSuite hook is undefined

### ISSUE THREAD

**Issue by jamesmortensen** [webdriverio/webdriverio#7873]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.9

### Node.js Version

v14.17.5

### Mode

WDIO Testrunner

### What happened?

We were attempting to get the duration of tests running in a describe suite, but in the afterSuite hook, we are seeing the duration as undefined:

```{
[0-0]   type: 'afterSuite',
[0-0]   title: 'Describe block A',
[0-0]   parent: '',
[0-0]   fullTitle: 'Describe block A',
[0-0]   pending: false,
[0-0]   file: '/Users/james/Dev/test.spec.js',
[0-0]   duration: undefined
[0-0] }
```

Inside wdio.conf.js:
```
afterSuite: function (suite) {
        // this fires when the describe suite is completed and it contains the file that was run.
        console.info(suite);
}
```

### What is your expected behavior?

It looks like someone intended to implement behavior where the duration of an entire suite is tracked and made available in the afterSuite hook.

### How to reproduce the bug.

To reproduce, write a single spec.js test file with a few simple tests, and then add the afterSuite hook and log the "suite" object to see its properties.

### Relevant log output

```typescript
{
[0-0]   type: 'afterSuite',
[0-0]   title: 'Describe block A',
[0-0]   parent: '',
[0-0]   fullTitle: 'Describe block A',
[0-0]   pending: false,
[0-0]   file: '/Users/james/Dev/test.spec.js',
[0-0]   duration: undefined
[0-0] }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@jamesmortensen Thanks for reporting!

The duration should definitely be set no matter if it is `0` or any other minimal duration.

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by praveendvd** [comment]
@christian-bromann  I will take this up 

@jamesmortensen  which framework  are you using , is there a  minimum reproducible example

**Comment by jamesmortensen** [comment]
@praveendvd we use Mocha as the framework.

**Comment by christian-bromann** [comment]
@praveendvd we should be able to compute the duration ourselves. WebdriverIO only runs one suite at a time within a worker process. So `@wdio/reporter` could be enhanced to calculate this duration between `suiteStart` and `suiteEnd`. What do you think?

**Comment by praveendvd** [comment]
@christian-bromann  the aftersuite object is comming from the mocha directly i couldnt find it in reporter . So i made the changes in mocha itself .  

Will continue the discussion in the PR
