### ISSUE TITLE
[🐛 Bug]: Incorrect file line being reported in stack trace error

### ISSUE THREAD

**Issue by klabak** [webdriverio/webdriverio#7874]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.12

### Node.js Version

12.18.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{ browserName: 'chrome' }
```

### What happened?

Hi there,

We recently updated our WDIO framework from version 6 to version 7 and we're seeing incorrect file lines reported in the printed stack trace during a test error. When a test errors out the file name and file line / column is displayed in the stack trace. However, the values for line / column are incorrect and often more than a couple of lines off making debugging issues with tests difficult. Please the reproduction steps below.

### What is your expected behavior?

A consistent stacktrace error file line / column regardless of test execution order / file size. The first image shows proper file location of where the error occurred. The second image is reporting an incorrect value simply by taking out the passing test above it from the spec file.

### How to reproduce the bug.

I used the test example from the WDIO website documentation to illustrate the issue:

stackTraceTest.wdio.js
````
describe('WebdriverIO stack trace test', () => {
  it('should do a correct assertion', () => {
    browser.url('https://webdriver.io');
    expect(browser).toHaveTitle(
      'WebdriverIO · Next-gen browser and mobile automation test framework for Node.js | WebdriverIO'
    );
  });

  it('should do an incorrect assertion', () => {
    browser.url('https://webdriver.io');
    expect(browser).toHaveTitle('The wrong title');
  });
});
````

and my simple config file:
````
exports.config = {
  // ==================================
  // Where should your test be launched
  // ==================================
  runner: 'local',
  // ==================
  // Specify Test Files
  // ==================
  specs: ['./stackTraceTest.wdio.js'],
  // ============
  // Capabilities
  // ============
  maxInstances: 1,
  capabilities: [
    {
      browserName: 'chrome'
    }
  ],
  // ===================
  // Test Configurations
  // ===================
  logLevel: 'error',
  waitforTimeout: 30000,
  framework: 'jasmine',
  jasmineOpts: {
    defaultTimeoutInterval: 1200000
  }
};
````
Executing the above yields the proper result:

![Correct stack trace](https://user-images.githubusercontent.com/18174252/148148271-cf2619b7-1f33-4755-aaa7-0b430cc65805.png)

Now delete the passing test (the first one) and re-run. You'll get an incorrect file line in the stack trace:

![Incorrect stack trace](https://user-images.githubusercontent.com/18174252/148148940-8712ee60-5832-4048-9b33-17e90fa94a7c.png)

I've tested this with both Jasmine and Mocha and two different IDEs (VSCode and IntelliJ). I've tried with both sync and async test formats as well. Any thoughts on this? Thanks!

### Relevant log output

```typescript
Execution of 1 workers started at 2022-01-05T01:59:07.823Z

[0-0] Browserslist: caniuse-lite is outdated. Please run:
[0-0] npx browserslist@latest --update-db
[0-0] 
[0-0] Why you should do it regularly:
[0-0] https://github.com/browserslist/browserslist#browsers-data-updating
[0-0] RUNNING in chrome - /wdio/tests/stackTraceTest.wdio.js
[0-0] Error in "WebdriverIO website test should do an incorrect assertions"
Error: Expect window to have title
Expected: "The wrong title"
Received: "WebdriverIO · Next-gen browser and mobile automation test framework for Node.js | WebdriverIO"
    at <Jasmine>
    at UserContext.<anonymous> (/app/huey/libs/testUtils/wdio/tests/stackTraceTest.wdio.js:6:21)
[0-0] FAILED in chrome - /wdio/tests/stackTraceTest.wdio.js

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:37
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for filing the issue.

I am not sure what could cause this. Maybe a babel or TS transform step in between.

Any hints or investigations in this regards would be appreciated.

**Comment by klabak** [comment]
Hey Christian thanks for the response. Here is our babel config if that helps at all

````
require('babel-polyfill');
require('babel-register')({
  presets: ['env'],
  plugins: ['transform-object-rest-spread', 'transform-class-properties'],
  ignore: [
    /node_modules\/(?!react-intl|intl-messageformat|intl-messageformat-parser).*/
  ]
});
global.window = {};
````

**Comment by klabak** [comment]
Hi Christian,

Funny enough another one of our engineers is working on converting our test library Babel configuration to use only Babel 7 modules. I tried out his branch and the stack trace issue seems to be resolved so it does seem to be a transform issue like you suggested. He had to do the following to get everything to work:

Removed babel.config.js (he couldn't get this to work using that file for some reason) and moved the settings into the WDIO config like this:

````
 autoCompileOpts: {
    babelOpts: {
      presets: [
        [
          '@babel/preset-env',
          {
            targets: {
              node: '12'
            }
          },
          'jest'
        ],
        ['@babel/preset-react']
      ],
      plugins: [],
      ignore: []
    }
  },
````
Here's our package.json Babel modules for reference. He removed all of the Babel version 6 modules:

"dependencies": {
    "@babel/cli": "7.14.5",
    "@babel/core": "7.14.6",
    "@babel/preset-env": "7.14.7",
    "@babel/register": "7.14.5",
    "@babel/runtime": "7.14.5",
}
"devDependencies": {
    "@babel/plugin-transform-runtime": "7.14.5",
    "@babel/preset-react": "7.14.5",
    "babel-eslint": "7.1.1",
    "babel-jest": "22.4.1",
    "babel-loader": "8.2.3"
}
````

So I think we are all set! Thanks for pointing us in the right direction!

**Comment by christian-bromann** [comment]
Awesome, thanks for confirming!
