### ISSUE TITLE
[🐛 Bug]: <project is not run>https://prnt.sc/262k5q1

### ISSUE THREAD

**Issue by RenuThakur** [webdriverio/webdriverio#7875]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### What happened?

We run the project comes this error.
https://prnt.sc/262k5q1
can you help me what is missing here

### What is your expected behavior?

my project is run

### How to reproduce the bug.

run the project

### Relevant log output

```typescript
Run the project
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Closing.

Please properly fill out the issue template and don't share any shady links. Thanks!
