### ISSUE TITLE
[🐛 Bug]: For mocha tests, BrowserStack session name is set as '<the last test title's describe> - <test title>' 

### ISSUE THREAD

**Issue by swatitabib-iplayer** [webdriverio/webdriverio#7876]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.5.7

### Node.js Version

12

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
  os: 'OS X',
  osVersion: 'Catalina',
  browserName: 'Chrome',
  browserVersion: 'latest',
}

Wdio and other packages in use:
@wdio/browserstack-service
@wdio/cli
@wdio/local-runner
@wdio/mocha-framework
@wdio/selenium-standalone-service
@wdio/spec-reporter
webdriverio
selenium-standalone (^6.15)
```

### What happened?

homepage.spec.ts
```
describe('Homepage', () => {
  describe('header', () => {
    it('is rendered', () => {});
  }
  describe('navigation', () => {
    it('is present on the page', () => {});
  }
  describe('footer', () => {
    it('is present on the page', () => {});
  }
})
```
category.spec.ts
```
describe('Category Page', () => {
  describe('header', () => {
    it('is rendered', () => {});
  }
  describe('navigation', () => {
    it('is present on the page', () => {});
  }
  describe('footer', () => {
    it('is present on the page', () => {});
  }
})
```
**Current Behavior:**
With Mocha tests, the session name for the above spec files is same which is "footer - is present on the page".  (last test's parent describe - last test's title) as per https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-browserstack-service/src/service.ts#L95

I have tried to rename the session name using BrowserStack REST API but it is overriding the session name by BrowserStack-service after the hook code.

**Additional Info:**
Fix done for Jasmine tests #6777 
https://github.com/webdriverio/webdriverio/pull/7198 

### What is your expected behavior?

In the above case, the expected session name for homepage.spec.ts should be - `'Homepage'`
and for category.spec.ts, should be - `'Category Page'`. 
Expect the main/global describe title of the spec file as a session name so we can differentiate between different spec files. 

### How to reproduce the bug.

To reproduce the issue, run the mocha tests shown above(nested describe) in BrowserStack and observe the BrowserStack session names.

### Relevant log output

```typescript
The session name for both the spec files is the same - "footer - is present on the page"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> ### WebdriverIO Version
> 7.5.7

Can you update to latest version and see if the error still persists?

**Comment by christian-bromann** [comment]
I assume your 👍  indicates you were able to solve this problem? Closing then.

**Comment by swatitabib-iplayer** [comment]
@christian-bromann today, I checked with latest webdriverIO version and can confirm that the issue is present on latest version of wdio packages. Could you please reopen the issue?

**Comment by christian-bromann** [comment]
Thanks for confirming @swatitabib-iplayer .. any contributions mitigating this problem would be appreciated.

**Comment by bhanuagarwal73** [comment]
Team any resolution on this ??

**Comment by christian-bromann** [comment]
Please check the progress on the PR, thanks!
