### ISSUE TITLE
suggestion for monorepo: run 'lerna link convert'

### ISSUE THREAD

**Issue by boneskull** [webdriverio/webdriverio#7879]
This assumes that a) you use `npm`, and b) you publish with `lerna`.

In [Appium](/appium/appium), we found that running `lerna link convert` (once) simplifies bootstrapping of our monorepo.

What this will do is add a dependency in the root `package.json` _for each package_, and the dependency will be a relative URL beginning with `file:`; e.g., `"foo": "file:packages/foo"`.  It will also replace any non-`file:` dependencies (or dev dependencies) in each package with something similar for interdependencies; e.g., `packages/foo/package.json` may contain a dependency of `"foo": "file:../bar"`.

In practice, this _eliminates the need to run `lerna bootstrap`_ because it eliminates the need for `package/*/package-lock.json`.   The result is a _single_ root `package-lock.json` which describes the dependencies of the monorepo _and all child repos_.  This means, of course, you can ditch the scripts which `rimraf` extraneous lockfiles (since these can give `lerna publish` fits).

Upon `lerna publish`, `lerna` will temporarily switch any relative `file:` deps in `packages/*/package.json` to their actual published (or to-be-published) versions, so these weirdo dependencies don't end up in your tarball.

That's all!

**Comment by christian-bromann** [comment]
Thanks for raising this. I was planning to eventually switch to Yarn workspaces as I feel it allows better dependency management.

**Comment by christian-bromann** [comment]
I will go ahead and close this as I don't think it is relevant anymore with Lerna v7 and their move towards NPM workspaces. Thanks for the tip anyway.
