### ISSUE TITLE
[💡 Feature]: appium-classifier-plugin in webdriverIO

### ISSUE THREAD

**Issue by EINBOX** [webdriverio/webdriverio#7884]
### Is your feature request related to a problem?

Hello,
appium-classifier-plugin is the feature to help identifying elements on mobile and using in selenium .

is there any way to support above plugin with webdriverIO?

### Describe the solution you'd like.

The classical elements selection is so brittle and needed an alternative to that, therefore one can use the work that has been accomplished here already
https://github.com/testdotai/appium-classifier-plugin

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
I think raising an issue in the package (appium-classifier-plugin#64) was the right way to go about this. Given its [requirements](https://github.com/testdotai/appium-classifier-plugin#system-setup) for 3rd party dependencies I don't think it is a good idea to make it a dependency of WebdriverIO. Therefor the best option is that this package allows support for other frameworks like WebdriverIO. You could fork it and build your own version using [custom selectors](https://webdriver.io/docs/selectors/#custom-selector-strategies).
