### ISSUE TITLE
[💡 Feature]: Request browser.mock() method to support running tests on range of browsers with BrowserStack integration

### ISSUE THREAD

**Issue by NikithaShetty777** [webdriverio/webdriverio#7885]
### Is your feature request related to a problem?

https://webdriver.io/docs/mocksandspies/
We have browser.mock() only supported when running local tests on Chrome at the moment.
It would be great if the method was supported across other browsers as well and not just limited to local testing.
Wish to see the mock method work successfully for WDIO integration tests with BrowserStack.

### Describe the solution you'd like.

I want the mock method to work successfully while running the WDIO integration tests with BrowserStack.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Thanks for filing the issue.

I believe BrowserStack sends the websocket connection for a session to the browser in the session response. We can use this one to connect via Puppeteer. This way the command at least would work for BS. Unfortunately the Chrome DevTools protocol is only available in Chrome, therefor support for other browser depends on the development of the WebDriver specificiation.

Any contributions that enable this in BrowserStack as mentioned above would be appreciated.

**Comment by bhanuagarwal73** [comment]
I tried running it with Puppeteer but didn't worked.
@christian-bromann  any working example or something to get over it ?

**Comment by christian-bromann** [comment]
@bhanuagarwal73 how would you think I have a working example given the issue is still open and is looking for contributors?

**Comment by bhanuagarwal73** [comment]
@christian-bromann 
I wrote:

blockNetworkCall: async (requestUrl: string[]): Promise<any> => {
        const wildcardMatch = require('wildcard-match');
        const blockRequest = wildcardMatch([requestUrl], { separator: false });

        const puppeteer = await browser.getPuppeteer();
        const pages = await puppeteer.pages();
        pages[0].setRequestInterception(true);
        pages[0].on('request', (request) => {
            if (blockRequest(request.url())) {
                const u = request.url();
                console.log(`request to ${u.substring(0, 50)}...${u.substring(u.length - 5)} is aborted`);
                request.abort();
                return;
            }
            request.continue();
        })
    }


With this, I am able to block the calls locally but not over browserstack

**Comment by GrandEL01** [comment]
Hey,

In order to use this use this feature with browserstack. WebdriverIO internally uses CDP for this feature. Hence we need to set the capability of seleniumCdp to true and we should have selenium version greater than 4.0.0 this will allow WebdriverIO users to use this feature on BrowserStack as well.


Sample Capabilities would look like following:

{
  ...
  "bstack:options":{
    seleniumCdp:true,
    seleniumVersion:'4.x.x',
    ...
  }
  ...
}

Hope this helps.

**Comment by christian-bromann** [comment]
@GrandEL01 thanks for verifying, I also got it working via these capabilities:

```
import { remote } from './packages/webdriverio/build/index.js'

const browser = await remote({
    user: 'xxx',
    key: 'xxx',
    capabilities: {
        browserName: 'chrome',
        'bstack:options': {
            os: 'Windows',
            osVersion: '11',
            browserVersion: 'latest',
            seleniumCdp: true,
            seleniumVersion: '4.6.0'
        }
    }
})

const mock = await browser.mock('**/*.png', {
    method: 'get'
})
mock.abort('Failed')
await browser.url('https://bild.de/')
console.log(mock.calls)
await browser.deleteSession()
```

**Comment by bhanuagarwal73** [comment]
Hey @christian-bromann  
I am not getting seleniumCdp option at all
![image](https://user-images.githubusercontent.com/38572421/206892575-b83275b4-2419-4ca6-bbad-d44d5b2b093d.png)


Packages:
![image](https://user-images.githubusercontent.com/38572421/206892605-399ec7bb-4096-477c-a4a1-35a1cb3f4cb8.png)

**Comment by christian-bromann** [comment]
@bhanuagarwal73 it is because it isn't defined as type in the BS option but is actually interpreted by their platform. I pushed a fix which will be released in the next version. In the meantime you can ignore the TypeScript error.
