### ISSUE TITLE
I am able to generate report and allure-report folder is available but when using allure open Allure report is not opening

### ISSUE THREAD

**Issue by Jyoti2190-Test** [webdriverio/webdriverio#7908]
### Discussed in https://github.com/webdriverio/webdriverio/discussions/7907

<div type='discussions-op-text'>

<sup>Originally posted by **Jyoti2190-Test** January 12, 2022</sup>
I am able to generate report and allure-report folder is available but when using allure open Allure report is not opening, its showing can't reach the page and also index.html is showing just loading 
<img width="503" alt="image" src="https://user-images.githubusercontent.com/70073904/149063333-b8edebd9-c3bc-4867-974f-ebce8a9c8154.png">
<img width="361" alt="image" src="https://user-images.githubusercontent.com/70073904/149063369-ada05050-3d98-4afe-86b1-a4ce05b6eb84.png">
<img width="361" alt="image" src="https://user-images.githubusercontent.com/70073904/149063472-d2e6dd6d-615e-47f0-8f5c-1457e5d3934e.png">
</div>

**Comment by christian-bromann** [comment]
Please raise this issue in the Allure project. I am not sure how this is connected to WebdriverIO given that the `allure-report` folder exist.
