### ISSUE TITLE
Running specs in parallel

### ISSUE THREAD

**Issue by mike-suggitt** [webdriverio/webdriverio#792]
I've forked the repo to look into how we could achieve parallel execution of specs for webdriverio. For this i'm simply looking to shard the spec files and execute up to a maxInstance count of threads, each running a spec file. I'm then launching multiple browsers for each instance using the launcher component.

I wanted to just open a disucssion on this and get thoughts on how best this can be achieved and the possible implications etc. I'm already looking into things like how to do reporting on parallel execution etc as the current reporters simply console out (but with some constraining business logic).

Anyway, yea.....thoughts?

**Comment by christian-bromann** [comment]
There is already an open discussion/thread about this. Let's continue the conversation there. I already implemented an approach to run parallel tests in [the v4 branch](https://github.com/webdriverio/webdriverio/blob/v4.0/lib/launcher.js#L65-L82). I works pretty good so far. What we definitely could discuss is how the reporter could look like.

**Comment by mike-suggitt** [comment]
Hi @christian-bromann. Thanks for your reply, can you provide a link to this disucssion at all? I took a quick look at the code you provided and have some thoughts/questions.

**Comment by christian-bromann** [comment]
oh sorry it is #544
