### ISSUE TITLE
[📖 Docs]: Limitations for nth selector using TypeScript does not work

### ISSUE THREAD

**Issue by a2f0** [webdriverio/webdriverio#7932]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Unclear documentation

### Description of the improvement / report

It appears that the [documentation for limitations](https://webdriver.io/docs/autowait/#limitation) to select the nth element of an array using `waitUnitl` does not work when using TypeScript, or at least fails TypeScript validation because the `success` case returns an object of type `WebdriverIO.Element`  where waitUntil only accepts a function that returns ` boolean | Promise<boolean>`.  The error with the example verbatim is in the attached screenshot.

![Screen Shot 2022-01-17 at 8 49 56 AM](https://user-images.githubusercontent.com/1569853/149780792-49671b65-43ea-40ef-b7a6-a54904fc0880.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Thanks for reporting!

I believe `waitUntil` returns the truthy value returned by the callback. The typings and docs should reflect that.

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by harsha509** [comment]
HI @christian-bromann ,

Looks like the typing's are fine, as `waitUntil` should return a Boolean value.
```
waitUntil(this: WebdriverIO.Browser | WebdriverIO.Element, condition: () => boolean|Promise< boolean >, { timeout, interval, timeoutMsg }?: Partial<WaitUntilOptions>): Promise<true | void>;
```

Looks like code sample in docs  should be updated , like below
```
    await browser.waitUntil(
      async () => {
        const elems = await $$('div');
        if (elems.length !== 2) {
          return false
        }
        return elems[2].getText() === "Some text"
      }, {
        timeoutMsg: 'Never found enough div elements',
      })
```

Please  suggest, will give the PR for this in docs!

**Comment by christian-bromann** [comment]
@harsha509 thanks for investigating. I think the types might be wrong here. I believe `waitUntil` is implemented so it returns the `truthy` value, e.g.:
```js
const value = await browser.waitUntil(() => 'foobar');
console.log(value); // outputs: "foobar"
```

Can you confirm? If so I suggest to not expect a boolean as return value but a generic.

**Comment by nextlevelbeard** [comment]
@christian-bromann @harsha509 Was any other progress made on this?

**Comment by christian-bromann** [comment]
@nextlevelbeard I don't think so, would you like to pick it up?

**Comment by christian-bromann** [comment]
fixed by https://github.com/webdriverio/webdriverio/pull/9767
