### ISSUE TITLE
Disable init command for wdio instances

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#794]
I often see people using the wdio test runner and have tests like:

```js
var webdriverio = require('webdriverio');
var client = webdriverio.multiremote();

client
    .init()
    // ...
```

We should disable init and end commands for webdriver instances in wdio. When someone is calling that command it should fail with a descriptive error message so the user know that he doesn't need to create a session by himself.

**Comment by Josiah** [comment]
So you don't need to call .init()?

If you do, under what circumstances?

**Comment by christian-bromann** [comment]
@Josiah when you are using the wdio test runner you don't need to call `init` nor `end` because the test runner takes care of that. There are no circumstances where you have to do it.

**Comment by christian-bromann** [comment]
fixed with v4
