### ISSUE TITLE
[🐛 Bug]: Allure report doesn't attach image when the screenshot trigger is in "afterScenario" hooks

### ISSUE THREAD

**Issue by carri747** [webdriverio/webdriverio#7940]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.13

### Node.js Version

15.14.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
        browserName: 'chrome',
        'goog:chromeOptions': {
            args: [
                '--disable-infobars',
                '--no-sandbox',
                '--disable-gpu',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage',
                '--window-size=1920,1080'
            ],
            prefs: {
                ['profile.default_content_setting_values.images']: 2
            }
        }
    }
```

### What happened?

I decide to upgrade WDIO version from 7.5.3 to 7.16.13. I use in wdio.conf.ts this method to take a screenshot 
`afterScenario: async function (world) {
            browser.takeScreenshot();
}`
and works properly with the version 7.5.3 but now with the current version doesn't work. I've a workaround and if create a new hooks "afterStep" and there works properly 

### What is your expected behavior?

Attach the image to report

### How to reproduce the bug.

Run a test with a fail.

### Relevant log output

```typescript
Nothing highlight in the logs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by carri747** [comment]
This is my setup in allure report 
```
reporters: [
        'spec',
        [
            'allure',
            {
                outputDir: './out/allure-result/',
                disableWebdriverStepsReporting: true,
                disableWebdriverScreenshotsReporting: false,
                useCucumberStepReporter: true
            }
        ]
    ],
```

I notice that when I remove the flag "userCucumberStepReport" the image it's attached but with this flag "true" the picture is not attached.

**Comment by praveendvd** [comment]
`afterScenario: async function (world) { await browser.takeScreenshot(); }`

you have to use await as its an async function

**Comment by praveendvd** [comment]
Try adding in afterStep than scenario 

```
afterStep:  async function (test, scenario, { error, duration, passed }) {
  if (error) {
    await browser.takeScreenshot();
  }
}
```

**Comment by carri747** [comment]
With afterStep is working properly.
