### ISSUE TITLE
How to get an exact screenshot of a specific element ?

### ISSUE THREAD

**Issue by CDV13100** [webdriverio/webdriverio#7947]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.11

### Node.js Version

14.17.6

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [
    {
      browserName: 'chrome'
    }
],
```

### What happened?

When we try to take a screenshot of a specific element (and not a full screenshot of the browser), the image is shifted whatever the method used to take the screenshot :

$(selector).saveScreenshot(filename)
browser.takeElementScreenshot(elementId, scroll)

on the left, the selected element, on the right the result of the screenshot
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/98392071/150970018-31b04c78-1c99-401c-9021-3653f89685fa.png)

### What is your expected behavior?

We expect to have a screenshot of the element identified by $(selector)

### How to reproduce the bug.

private googleImg = '//img[@alt="Google"]';

  async google(){
    await browser.url('https://www.google.fr/'); 
    await browser.pause(2000);
    const elem = await $(this.googleImg);
    await elem.saveScreenshot('./google.png');
  }

result :
![google (2)](https://user-images.githubusercontent.com/98392071/150969644-deb1bdfc-e125-49aa-94c7-81bf28e0f169.png)

### Relevant log output

```typescript
The code executes without error. There is nothing relevant in the logs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
There is not much WebdriverIO does wrong here. It calls the correct [WebDriver command](https://www.w3.org/TR/webdriver/#take-element-screenshot), at least I assume given that no logs are provided. Maybe it makes sense to file a Chromedriver bug. Any help investigating this, would be appreciated.

**Comment by praveendvd** [comment]
```
describe('My Login application', () => {
    it('should login with valid credentials', async () => {
        await browser.url('https://www.google.fr/');
        //close the cookies page and maximize the browser
        await browser.pause(5000);
        const elem = await $('img[alt="Google"]');
        await elem.saveScreenshot('./google.png');
    });
});

```

@CDV13100  It works as expected ,

Have a try at following things

1.  ​if you are using asynchronous image try waiting for image size to be stable before taking the screenshot ,
2.  If you are using headless , make sure you test screen size properly 
3. make sure there is no overlapping elements then the overlapping elements screenshot will be taken instead

**Comment by CDV13100** [comment]
Thanks @christian-bromann for your suggestion about a driver issue.
It helps us to identify the problem.

Wdio allows two different automation protocols : devtools/puppeteer and driver.
In our case, we used the devtools/puppeteer, and the element screenshot doesn't work with this protocol.
By using a driver protocol with the chromedriver service, the screenshot of an element is as expected.

However, I wonder why it doesn't work with devtools/puppeteer ?

Thanks @praveendvd  for your answer.

**Comment by christian-bromann** [comment]
> However, I wonder why it doesn't work with devtools/puppeteer ?

Not sure. WebdriverIO uses a built in [Puppeteer method](https://pptr.dev/#?product=Puppeteer&version=v13.0.1&show=api-elementhandlescreenshotoptions) here so I assume there is some issue with clipping on Puppeteer side.

**Comment by anshitbansal21** [comment]
Is this issue happening for `browser.saveElement()` as well? I am unable to find an open issue for that and this one seems to be the same issue where the browser seems to shift before capturing the screenshot 😔
