### ISSUE TITLE
Cucumber framework xunit reporter reports incorrect status

### ISSUE THREAD

**Issue by austek-mdsol** [webdriverio/webdriverio#795]
Webdriverio: 3.1.0
cucumber: 0.5.2

Xunit reports incorrect status for testcase.

Test Suite shows 3 tests and 0 failures
`testsuite name="Able to click on logo and redirect to Project List page" tests="3" failures="0" skipped="0" disabled="0" time="16.11" timestamp="Thu Sep 17 2015 16:26:27 GMT+0100 (BST)" id="2" file="/features/ta/Logo_Redirects_to_Project_List.feature">`

and yet individual test cases shows failed status
`<testcase name="I am logged in" disabled="false" time="13.628" id="3" file="/features/ta/Logo_Redirects_to_Project_List.feature" status="failed" classname="firefox">`

When using spec reporter all the test pass

**Comment by austek-mdsol** [comment]
testcase failed status problem is fixed on v3.2.4. However, 3.2.4 still prints `failure` tags.  Raised PR https://github.com/webdriverio/webdriverio/pull/797 to not print `failure` tag when there are no errors

**Comment by christian-bromann** [comment]
Merged #797

**Comment by christian-bromann** [comment]
Thanks!
