### ISSUE TITLE
[📖 Docs]: Improve documentation around JUnit Reporter suiteNameFormat

### ISSUE THREAD

**Issue by OtherwiseJunk** [webdriverio/webdriverio#7952]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Unclear documentation, Missing documentation

### Description of the improvement / report

I was recently working on configuring the junit test reporter for our test suite, we use `-` characters in our spec titles, and I was trying to get it to not strip them out.

I had provided a config of

      {

        outputDir: './',

        suiteNameFormat: '/[^a-zA-Z0-9@-]+/',

        outputFileFormat: function (options) {

          return `results.Chrome-${options.capabilities.os_version}.xml`;

        }

      }

based on the default regex in the code, but it was still stripping out the characters.

It turned out that making the suiteNameFormat a string instead of just passing it in directly was the cause of the issue:

      {

        outputDir: './',

        suiteNameFormat: /[^a-zA-Z0-9@-]+/,

        outputFileFormat: function (options) {

          return `results.Chrome-${options.capabilities.os_version}.xml`;

        }

      }

I think having just a quick example of this value being configured would be helpful here.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Thanks for raising this issue @OtherwiseJunk!

You want to take a stab at this? You can find the docs for the reporter [here](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-junit-reporter/README.md).

**Comment by OtherwiseJunk** [comment]
Created https://github.com/webdriverio/webdriverio/pull/7957 to resolve this issue.

**Comment by christian-bromann** [comment]
Closing, thanks @OtherwiseJunk for the contribution.
