### ISSUE TITLE
[📖 Docs]: Add documentation on `element`, `browser` and `mock` objects

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#7954]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Missing documentation

### Description of the improvement / report

Based on a tweet by `@davert`: https://twitter.com/davert/status/1487229512173686785

It would be great if the docs could have specific information on the `element`, `browser` and `mock` objects within the API section. Rather then just expanding the object functions it would be better if the object itself would be explained and a permalink would be created so that docs can be shared for that specific object.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by praveendvd** [comment]
@christian-bromann  Hi I can take it up , any hint on where to get started on it .

**Comment by christian-bromann** [comment]
> any hint on where to get started on it .

Please check out the [contributing guidelines](https://webdriver.io/docs/contribute#documentation) for our docs. I think what we need is an index file for the page groups. Docusaurus should have some docs around this. Given that the API is auto generated I suggest to have the custom docs for these pages in `../docs/api/(element|browser|mock).md` and move these pages then into the API folder during page generation.

**Comment by praveendvd** [comment]
> > any hint on where to get started on it .
> 
> Please check out the [contributing guidelines](https://webdriver.io/docs/contribute#documentation) for our docs. I think what we need is an index file for the page groups. Docusaurus should have some docs around this. Given that the API is auto generated I suggest to have the custom docs for these pages in `../docs/api/(element|browser|mock).md` and move these pages then into the API folder during page generation.
> 
> We already have a documentation page on the [`browser`](https://webdriver.io/docs/browserobject) object.

I will have look , I was confused because i was not able to get  common entry point . Each page is generated separately . Some has a sidebar file , some have md file , some doesnt have any reference but the section is created and there is individual md files for the content inside .

**Comment by christian-bromann** [comment]
We have a [scripts folder](https://github.com/webdriverio/webdriverio/tree/main/scripts/docs-generation) that does all that. While it seems overkill it really keeps documenting all these commands bare-able 😉  let me know if you have any suggestions for improvements though.

**Comment by praveendvd** [comment]
@christian-bromann  

![image](https://user-images.githubusercontent.com/45095911/152999868-36b0374a-7ae2-4adb-8c52-068792f4ca3c.png)

I am getting this error on trying to run the document locally

**Comment by christian-bromann** [comment]
@praveendvd seems like something is wrong with the readme provided by this service. I suggest to do the following:

- catch the error and ignore creating docs for the service
- create an issue in the repository and ask to have it fixed

**Comment by Badisi** [comment]
Compiling issue due to [@badisi/wdio-harness](https://github.com/Badisi/wdio-harness) was fixed.

> The `README.md` of the library was actually containing an `<hr>` tag, which is completely standards HTML and was working fine in MARKDOWN, but requires to be `<hr/>` for JSX to compile.

**Comment by christian-bromann** [comment]
Fixed by #8834
