### ISSUE TITLE
Offer API for programmatic use and deprecate gulp-webdriver

### ISSUE THREAD

**Issue by silvenon** [webdriverio/webdriverio#796]
This is just a suggestion. I hope I'm not annoying you with issues :grin:

Some of the reasons are:

* it's essentially just a wrapper for the `wdio` executable, which kinda goes against gulp's [guidelines](https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md)
* with the plugin you can't make the configuration file name default to `wdio.conf.js`
* with the plugin you will always specify just that configuration file, so stream is weird to use for that
* allows us deal with gulp so you don't have to 
* one less module to maintain

The usage could look something like this:

```js
import {wdio} from 'webdriverio';

gulp.task('webdriver', (done) => {
  wdio(done);
});
```

#### `wdio([configFile,] [options,] callback)`

* `configFile` is a path to the configuration file, defaults to `wdio.conf.js`
* `options` override the configuration in `configFile`
* `callback(err)` gets called when tests are finished, with `err` as the error if there is one

This would preserve backwards compatibility, I think.

**Comment by christian-bromann** [comment]
This is possible now. You can require the launcher and call the `run` command. It's a promise that resolves with the exitCode. Here is an example:

```js
    var launcher = require('webdriverio/lib/launcher')
    let launcher = new Launcher(configFile, args)
    launcher.run().then(
        (code) => process.exit(code),
        (e) => process.nextTick(() => {
            throw e
        }))
```
