### ISSUE TITLE
[📖 Docs]: Add more async examples for filter, findIndex, etc

### ISSUE THREAD

**Issue by uno-dos** [webdriverio/webdriverio#7960]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Missing documentation

### Description of the improvement / report

So far there is very little documentation on how to use various functions like `filter()`, `find()`, `findIndex()`, etc in async way. Please add more code snippets/examples on how to use various functions in async way. This will make transition from sync to async easier for many developers.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Thanks for reporting!

More documentation is always good.

Any contributions that resolves the issue are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by irtiza** [comment]
@christian-bromann I am interested in contributing to the project. So decided to look for good first pick labeled issues. 

If I can get more information on these methods, where they are and how to use them, then I can update docs and create PR. 

Let me know your thoughts.

Regards

**Comment by christian-bromann** [comment]
Hey @irtiza 👋 

that's awesome, thanks for your interest.

The commands are currently implemented in our [shim file](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-utils/src/shim.ts#L261-L277) that handles sync and async command handling. This is basically a wrapper around the WebdriverIO command. I suggest the best place to document this behavior is directly within our [`$$` for browser scope](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/browser/$$.ts#L22) / [`$$` for element scope](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/element/$$.ts#L20) command. You can find some docs on how to generate the website locally [here](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#deploying-the-documentation-locally). Let me know if you have any questions, happy to assist.

**Comment by christian-bromann** [comment]
@irtiza any updates, issues or anything I can help with?

**Comment by christian-bromann** [comment]
Fixed by #8834
