### ISSUE TITLE
[🐛 Bug]: trim(), toLowerCase(), etc are not working with getText() in async mode

### ISSUE THREAD

**Issue by uno-dos** [webdriverio/webdriverio#7961]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.6

### Node.js Version

16.13.1

### Mode

Standalone Mode

### What happened?

```
TypeError: elem.getText(...).trim is not a function
```
error shows up for all String methods like `toLowerCase()` for `elem.getText()` in async mode.

### What is your expected behavior?

I would assume that String functions should work out of the box for `getText()` method or at least there would be some docs how to use them in async mode.

### How to reproduce the bug.

Have a sample run with a code that looks like this:

```
async someAsyncSearchFunction (searchTarget) {
  let elem = await $('.foo');
  if (await elem.getText().trim() === searchTarget) {
    ...
  }
}
```

### Relevant log output

```typescript
TypeError: elem.getText(...).trim is not a function
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
You can't chain string prototype methods with element commands, so rather than doing:
```js
await elem.getText().trim()
```
do:
```js
(await elem.getText()).trim()
```
