### ISSUE TITLE
Whenever I set up webdriverio with a typescript compiler I get an error when trying to run the test

### ISSUE THREAD

**Issue by eoin-roll-out** [webdriverio/webdriverio#7963]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.14

### Node.js Version

16.13.2

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [{
        maxInstances: 5,
        browserName: 'chrome',
        acceptInsecureCerts: true
    
    }],
```

### What happened?

I set up webdriverio using `npm init wdio.`
I then attempted to run the example.spec file and this returned the following error:
![Screenshot 2022-02-01 at 20 30 27](https://user-images.githubusercontent.com/60970259/152046159-3447d9d7-85a4-4667-9b05-c2715ef19c69.png)

### What is your expected behavior?

I would expect the test to run. I am testing on a new project and could do with getting this working, a speedy reply will be greatly appreciated.? Error: Could not execute "run" due to missing configuration. Would you like to create one?

### How to reproduce the bug.

Follow the steps I have mentioned above with the same versions

### Relevant log output

```typescript
? Error: Could not execute "run" due to missing configuration. Would you like to create one?
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by eoin-roll-out** [comment]
@christian-bromann Oh so you ran using  'npx wdio run test/wdio.conf.ts' but I just ran 'yarn wdio' as I thought that script was already present in package.json?

`  "scripts": {
        "wdio": "wdio run wdio.conf.js"
    }`

When I run with the npx command you have said it runs okay but how can I do the same with yarn?

**Comment by christian-bromann** [comment]
Actually this was fixed in here and just not yet deployed. I will do this now. Thanks for letting us know.

**Comment by eoin-roll-out** [comment]
Thanks @christian-bromann for the help!
