### ISSUE TITLE
wdio config problem ENOENT: no such file or directory, open 'wdio.capabilities.json'

### ISSUE THREAD

**Issue by paweljagiello** [webdriverio/webdriverio#7972]
I get following error after running my config file : 

> `2022-02-03T14:12:45.921Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: /Users/paweljagiello/Documents/6.0/Ztable.Mobile/test/Mobile/wdio.conf.ts: ENOENT: no such file or directory, open 'wdio.capabilities.json'
> wdio run <configPath>
> 
> Run your WDIO configuration file to initialize your tests. (default)
> 
> Options:
>       --version             Show version number                        [boolean]
>       --watch               Run WebdriverIO in watch mode              [boolean]
>   -h, -h, --hostname        automation driver host address              [string]
>   -p, -p, --port            automation driver port                      [number]
>       --path                path to WebDriver endpoints (default "/")   [string]
>   -u, -u, --user            username if using a cloud service as automation
>                             backend                                     [string]
>   -k, -k, --key             corresponding access key to the user        [string]
>   -l, -l, --logLevel        level of logging verbosity
>          [choices: "trace", "debug", "info", "warn", "error", "silent", "trace",
>                                      "debug", "info", "warn", "error", "silent"]
>       --bail                stop test runner after specific amount of tests have
>                             failed                                      [number]
>       --baseUrl             shorten url command calls by setting a base url
>                                                                         [string]
>   -w, -w, --waitforTimeout  timeout for all waitForXXX commands         [number]
>   -f, -f, --framework       defines the framework (Mocha, Jasmine or Cucumber)
>                             to run the specs                            [string]
>   -r, -r, --reporters       reporters to print out the results on stdout [array]
>       --suite               overwrites the specs attribute and runs the defined
>                             suite                                        [array]
>       --spec                run only a certain spec file - overrides specs piped
>                             from stdin                                   [array]
>       --exclude             exclude certain spec file from the test run -
>                             overrides exclude piped from stdin           [array]
>       --mochaOpts           Mocha options
>       --jasmineOpts         Jasmine options
>       --cucumberOpts        Cucumber options
>       --autoCompileOpts     Auto compilation options
>       --help                Show help                                  [boolean]
> 
> Examples:
>   wdio run wdio.conf.js --suite foobar      Run suite on testsuite "foobar"
>   wdio run wdio.conf.js --spec              Run suite on specific specs
>   ./tests/e2e/a.js --spec ./tests/e2e/b.js
>   wdio run wdio.conf.js                     Run suite with custom Mocha timeout
>   --mochaOpts.timeout 60000
>   wdio run wdio.conf.js                     Disable auto-loading of ts-node or
>   --autoCompileOpts.autoCompile=false       @babel/register
>   wdio run wdio.conf.js                     Run suite with ts-node using custom
>   --autoCompileOpts.tsNodeOpts.project=con  tsconfig.json
>   figs/bdd-tsconfig.json
> 
> Documentation: https://webdriver.io
> @wdio/cli (v7.16.14)
> 
> Error: ENOENT: no such file or directory, open 'wdio.capabilities.json'
>     at Object.openSync (node:fs:585:3)
>     at Object.readFileSync (node:fs:453:35)
>     at Object.<anonymous> (/Users/paweljagiello/Documents/6.0/Ztable.Mobile/test/Mobile/wdio.conf.ts:3:33)
>     at Module._compile (node:internal/modules/cjs/loader:1097:14)
>     at Module.m._compile (/Users/paweljagiello/Documents/6.0/Ztable.Mobile/node_modules/ts-node/src/index.ts:473:23)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
>     at Object.require.extensions.<computed> [as .ts] (/Users/paweljagiello/Documents/6.0/Ztable.Mobile/node_modules/ts-node/src/index.ts:476:12)
>     at Module.load (node:internal/modules/cjs/loader:975:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Module.require (node:internal/modules/cjs/loader:999:19) {
>   errno: -2,
>   syscall: 'open',
>   code: 'ENOENT',
>   path: 'wdio.capabilities.json'
> }`

Here is my capabilities.js

> `const process = require('process');
> const fs = require('fs');
> 
> const devices = [];
> for (let i=2; i < process.argv.length; i++) {
>     devices.push(process.argv[i]);
> }
> 
> const capabilities = [
>     {
>         browserName: '',
>         autoWebview: true,
>         autoWebviewTimeout: 20000,
>         platformName: 'Android',
>         deviceName: 'pixel2xl',
>         app: __dirname + '/platforms/android/app/build/outputs/apk/release/app-release.apk',
>         'app-package': 'se.ztabler.app.ztable',
>         'app-activity': 'MainActivity',
>         autoAcceptAlerts: 'true',
>         autoGrantPermissions: 'true',
>         newCommandTimeout: 300000
>     },
>     {
>         browserName: '',
>         autoWebview: true,
>         autoWebviewTimeout: 20000,
>         app: __dirname + '/platforms/ios/build/emulator/myApp.app',
>         version: '15.0',
>         platform: 'iOS',
>         deviceName: 'iPhone 13',
>         platformName: 'iOS',
>         name: 'Ridely',
>         automationName: 'XCUITest',
>         nativeWebTap: 'true'
>     }
> ];
> 
> const exportedCapabilities = capabilities.filter(c => devices.findIndex(d => d.toLowerCase() === c.deviceName.toLowerCase().trim()) >= 0);
> 
> fs.writeFileSync('wdio.capabilities.json', JSON.stringify(exportedCapabilities));
> 

tsconfig file:
> `{
>   "compileOnSave": false,
>   "compilerOptions": {
>     "baseUrl": "./",
>     "outDir": "./dist/out-tsc",
>     "sourceMap": true,
>     "declaration": false,
>     "inlineSources": true,
>     "sourceRoot": "/",
>     "downlevelIteration": true,
>     "experimentalDecorators": true,
>     "module": "commonjs",
>     "moduleResolution": "node",
>     "importHelpers": true,
>     "target": "es2015",
>     "lib": [
>       "es2018",
>       "dom",
>       "esnext.asynciterable"
>     ],
>     "allowSyntheticDefaultImports": true,
>     "types": [
>       "node",
>       "webdriverio/async",
>       "@wdio/devtools-service",
>       "jasmine"
>     ]
>   },
>   "angularCompilerOptions": {
>     "fullTemplateTypeCheck": true,
>     "strictInjectionParameters": true
>   }
> }
> `
> wdio.conf.ts:
> `import { readFileSync } from 'fs';
> 
> const capabilities = JSON.parse(readFileSync('wdio.capabilities.json', 'utf8'));
> 
> export const config = {
>     runner: 'local',
>     port: 4723,
>     specs: [
>         './test/specs/**/*.ts'
>     ],
>     exclude: [
>         './test/specs/**/skip.ts'
>     ],
>     maxInstances: 1,
>     capabilities,
>     logLevel: 'info',
>     bail: 0,
>     baseUrl: 'http://localhost',
>     waitforTimeout: 10000,
>     connectionRetryTimeout: 120000,
>     connectionRetryCount: 3,
>     services: [['appium',{
>         args: {
>             allowInsecure: 'chromedriver_autodownload'
>         }
>     }]],
>     framework: 'jasmine',
>     reporters: ['spec'],
>     jasmineOpts: {
>         defaultTimeoutInterval: 60000,
>         expectationResultHandler: function(passed, assertion) {
>         }
>     }
> }
> `

**Comment by christian-bromann** [comment]
> ENOENT: no such file or directory, open 'wdio.capabilities.json'

The error is pretty clear here. You seem to import a json file somewhere that doesn't exist.
