### ISSUE TITLE
[🐛 Bug]: UnhandledPromiseRejectionWarning: Error when executing wdio config from Gitlab Pipeline

### ISSUE THREAD

**Issue by louis57** [webdriverio/webdriverio#7973]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.14

### Node.js Version

14.18.3

### Mode

WDIO Testrunner

### What happened?

I created a gitlab pipeline (*.yml) to execute my webdriverIO tests. The script runs through until it gets to the point where it runs WDIO CLI Wizard, then I got the following UnhandledPromise:

```
+ @wdio/cli@7.16.14
...
$ node -v
v14.18.3
$ cd e2e
$ npx wdio run ./wdio.conf.ts
...
Finished installing packages.
Running WDIO CLI Wizard...
=========================
WDIO Configuration Helper
=========================
? Where is your automation backend located? (Use arrow keys)
❯ On my local machine 
  In the cloud using Experitest 
  In the cloud using Sauce Labs 
  In the cloud using Browserstack or Testingbot or LambdaTest or a different ser
vice 
  I have my own Selenium cloud (node:19) UnhandledPromiseRejectionWarning: Error: Error calling: npx wdio config
    at ChildProcess.<anonymous> (/usr/src/app/.npm/_npx/19/lib/node_modules/wdio/build/utils.js:21:31)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### What is your expected behavior?

The CLI for the configuration was expected to run, allowing my test script to be executed on Gitlab Pipeline

### How to reproduce the bug.

Step to reproduce this behavior
1. Create a `.gitlab-ci.yml` file on gitlab
2. In this file, write a script to execute a test job
```
image: //your image if needed

stages:
  - e2e_test

automationtest:
  stage: e2e_test
  script:
    - >
      node -v
    - >
      cd e2e
    - >
      npx wdio run ./wdio.conf.ts
```
3. Submit to your repo on Gitlab and check the pipeline

### Relevant log output

```typescript
Running WDIO CLI Wizard...
=========================
WDIO Configuration Helper
=========================
? Where is your automation backend located? (Use arrow keys)
❯ On my local machine 
  In the cloud using Experitest 
  In the cloud using Sauce Labs 
  In the cloud using Browserstack or Testingbot or LambdaTest or a different ser
vice 
  I have my own Selenium cloud (node:19) UnhandledPromiseRejectionWarning: Error: Error calling: npx wdio config
    at ChildProcess.<anonymous> (/usr/src/app/.npm/_npx/19/lib/node_modules/wdio/build/utils.js:21:31)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Cleaning up file based variables
00:01
Job succeeded
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by louis57** [comment]
@christian-bromann I am also confused why it runs `wdio config`. The file `wdio.conf.ts` does exist in my project/branch, under folder `e2e`, therefore in my script I change directory to `e2e` and then execute the file.

```
script:
    - >
      node -v
    - >
      cd e2e
    - >
      npx wdio run ./wdio.conf.ts
```

I expected it executed the script, but apparently it did not.

**Comment by praveendvd** [comment]
>  `npx wdio run "./wdio.conf.ts"`

Could you give  try of enclosing it with quotes , is your local system is also running linux ?

**Comment by louis57** [comment]
@praveendvd I did try the quotes, still the same error. Yes, my local system is Ubuntu 18.04.6 LTS

**Comment by praveendvd** [comment]
> @praveendvd I did try the quotes, still the same error. Yes, my local system is Ubuntu 18.04.6 LTS

Its really hard to debug it without the environment .  

1. Try doing an ls and see if file is there
2. Make sure you have project checkout step if ls doesnt show the files
3. Make sure you didnt accidently added the file to git ignore Remove the git cache and push every thing and see

**Comment by praveendvd** [comment]
https://webdriver.io/docs/typescript/

make sure tsnode is installed and tsconfig.json is configured correcly and is in current direcly. Else create a separate tsconfig for your project and move it under test folder , and add autocompile option and add path to new tsconfig.json file explicitly

**Comment by louis57** [comment]
The issue was caused because of wrong path in my file `wdio.conf.ts`

Thanks all.
