### ISSUE TITLE
[🐛 Bug]: Can't take a screenshot with Appium (browser.checkElement is not a function)

### ISSUE THREAD

**Issue by Searcher865** [webdriverio/webdriverio#7974]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.14

### Node.js Version

15.0.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [{
        maxInstances: 1,
        platformName: "Android",
        "appium:deviceName": "Pixel 3",
        "appium:platformVersion": "11.0",
        "appium:automationName": "UIAutomator2",
        "appium:browserName": "Chrome",
        "appium:chromedriverExecutable": "C:/WebDriver/bin/chromedriver.exe",
        "appium:appiumVersion": '2.0.0-beta.25',
        "appium:waitforTimeout": '30000',
        "appium:commandTimeout": '30000'
        //             maxInstances: 5,
        
        // acceptInsecureCerts: true
    }]

 services: [
        ['appium'],
        ['chromedriver'],
        ['image-comparison', 
        // The options
        { 
            // Some options, see the docs for more
            baselineFolder: join(process.cwd(), './test/visual test/baseline/'),
            formatImageName: '{tag}-{logName}-{width}x{height}',
            screenshotPath: join(process.cwd(), './test/visual test/chekc/'),
            // savePerInstance: true,
            autoSaveBaseline: true,
            // blockOutStatusBar: true,
            // blockOutToolBar: true,
            isHybridApp:true
            // clearRuntimeFolder: true
            // Without this option, it errors out only when mismatch is above 1.23%(by default)
            // ... more options
        }],
         
    ]
```

### What happened?

1. after launch, Chrome opens on Pixel 3 (Android Studio emulator).
2. URL is being navigated
3. Finds a layout element.
4. await browser.checkElement(await element, 'simple', {}) is called
5. Error appears in console "browser.checkElement is not a function". Playable for any other image comparison or image save function

### What is your expected behavior?

Expected behavior
Test completed successfully. A screenshot of the element is taken and saved.

browser.checkElement is wdio-image-comparison-service version: 3.1.0. This function should compare the appearance of the element with the reference screenshot. If there is no reference image, the auto-detect function automatically saves the reference image. If I run the test in desktop Chrome with Chromdriver, then this function works. If I run the test in Appium then it doesn't work.

### How to reproduce the bug.

git link https://github.com/Searcher865/wdio-with-appium-example-

- Node.js version: 15.0.0
- NPM version: 7.0.2
- Browser name and version: Chrome83
- Platform name and version: Windows 10
- WebdriverIO version: 7.16.14
- wdio-image-comparison-service version: 3.1.0
- Appium 2.0.0-beta.25 ( 1.22.2)
- TS version: 10.4.0

run Android studio 2021
run emulator Pixel 3, andriod 11, Chrome 83
start Android Emulator Pixel 3
npm i
npm test

### Relevant log output

```typescript
I put the logs in the repository link https://github.com/Searcher865/wdio-with-appium-example-/tree/master/logs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Can you provide the WDIO logs?

**Comment by christian-bromann** [comment]
@wswebcreation any reason why the image comparison would not work here?

**Comment by gauravgandhi1315** [comment]
Image comparison is working for me. Logs would definitely help.

**Comment by Searcher865** [comment]
@christian-bromann @gauravgandhi1315 I left a link to the logs in the description. Need others? duplicating

> I put the logs in the repository link https://github.com/Searcher865/wdio-with-appium-example-/tree/master/logs

**Comment by christian-bromann** [comment]
It seems that this is a bug in the [wdio-image-comparison-service](https://github.com/wswebcreation/wdio-image-comparison-service/blob/main/lib/service.js#L30) because the capabilities don't contain `browserName`. So rather than having `'appium:browserName': 'Chrome'` set, just do `'browserName': 'Chrome'`. The `browserName` capability should not be prefixed.

**Comment by Searcher865** [comment]
@christian-bromann thank you
If I use capabilities 'browserName': 'Chrome' my test doesn't work at all. I think when 'browserName': 'Chrome' Appium doesn't start.
If I use 'appium:browserName': 'Chrome' then my test runs on the emulator but doesn't save or compare screenshots with wdio-image-comparison-service and I get an error browser.checkElement is not a function
I put new logs when I used 'browserName': 'Chrome' in git link https://github.com/Searcher865/wdio-with-appium-example-/tree/master/logs%20browserName%20Chrome
Old logs when I used 'appium:browserName': 'Chrome' git link https://github.com/Searcher865/wdio-with-appium-example-/tree/master/logs%20appiumbrowserName%20Chrome%2C

I tried also browserName: 'Chrome', 'browserName': Chrome, browserName: Chrome, 'browserName': 'Chromium', 'browserName': 'Browser ', appium:browserName: 'Chrome', 'appium:browserName': Chrome, appium:browserName: Chrome, 'appium:browserName': 'Chromium', 'appium:browserName': 'Browser ' etc. this does not work

**Comment by wswebcreation** [comment]
Hi @Searcher865 

Sorry for the late response, been pretty busy. But I'e created a PR for your project. The PR contains a few things that you need to be aware of:

- it seems that Android 11 emulators don't have chrome installed anymore (at least not on my machine). The Appium logs told me that it wanted to start chrome, but couldn't find it and thus was complaining about an `appium:app` cap not being provided
- you were using Appium 2.0-beta in your caps, when you just start with Appium I wouldn't recommend to start with the beta, but first get familiar with 1.x. Please check the [appium-boilerplate](https://github.com/webdriverio/appium-boilerplate) for steps on how to install all deps
- as @christian-bromann already mentioned, `browserName` is a valid W3C capability and should NOT be prefixed with `appium:`

I've changed the Android emulator to Android 10 in the PR, please try to get check that PR out and see if you get it running.
