### ISSUE TITLE
[🐛 Bug]:Protocol error (Input.dispatchMouseEvent): Target closed - why does it happens?

### ISSUE THREAD

**Issue by avikha** [webdriverio/webdriverio#7988]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.11.0

### Node.js Version

14.16

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  browserName: 'chromium',
  browserVersion: '92',
  platformName: 'amazon-linux',
  automationProtocol: 'puppeteer'
}
```

### What happened?

We are running `wdio` and headless browser inside aws lambda, with `chrome-aws-lambda` and `puppeteer` protocol. But sometimes we see the following errors - 

```
Error: Protocol error (Input.dispatchMouseEvent): Target closed.
   at /tmp/wdio/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:217:63
   at new Promise (<anonymous>)
   at CDPSession.send (/tmp/wdio/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:216:16)
   at Mouse.move (/tmp/wdio/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Input.js:343:32)
   at Mouse.click (/tmp/wdio/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Input.js:367:24)
   at ElementHandle.click (/tmp/wdio/node_modules/puppeteer-core/lib/cjs/puppeteer/common/JSHandle.js:416:32)
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

This error leads to the `wdio` runner being stuck, and then the lambda runs out of time and crashes.

And we are trying to understand what is it? What does it mean that the `target closed` (we guess it happens when browser shuts down unexpectedly) and why is it get closed out of nowhere? Why the runner is getting stuck and not just failing?

Mostly, we see it after navigation operations, but not only. 

I'd like to have help, and perhaps ideas of how can we work around it? Has anybody else encountered the problem?

Thanks, everyone. 

### How to reproduce the bug.

Hard to reproduce it. 

First of all, you should run the `wdio` project inside the `aws-lambda` using the `chrome-aws-lambda`. After that, you can just write tests with navigations between pages and so on. 

### Relevant log output

```typescript
[0-0] 2022-02-08T2:49:20.4920Z Protocol error(Input.dispatchMouseEvent): Target closed.


Error: Protocol error (Input.dispatchMouseEvent): Target closed.
   at /tmp/wdio/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:217:63
   at new Promise (<anonymous>)
   at CDPSession.send (/tmp/wdio/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:216:16)
   at Mouse.move (/tmp/wdio/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Input.js:343:32)
   at Mouse.click (/tmp/wdio/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Input.js:367:24)
   at ElementHandle.click (/tmp/wdio/node_modules/puppeteer-core/lib/cjs/puppeteer/common/JSHandle.js:416:32)
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> We are running `wdio` and headless browser inside aws lambda, with `chrome-aws-lambda` and `puppeteer` protocol.

Is AWS Lambda supporting running Chrome through Chrome DevTools. I was not aware this is supported yet. Can you confirm?

**Comment by avikha** [comment]
Yes, they are. 

I'm not sure that I have formal documentation to show you. But, from an engineering perspective, it works. 

Today, at Duda, we are running hundreds of tests a day using the `wdio` and the `chrome-aws-lambda` with Puppeteer.

But some of them fail because of the `Target is closed` issue that I've shown above. Not all related to mouse events. It is just annoying. In those cases, the `wdio` script continues to run, the runner continues to run until the lambda times out. 

And we don't are sure why it happens and what can be done. 

Thanks for the response.

**Comment by christian-bromann** [comment]
It is hard to say why this happens, could be related to a race condition or other connectivity issues. I personally won't be able to look into this anytime soon so any help to solve this problem and make the devtools connection a bit more resilient is much appreciated.

Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by christian-bromann** [comment]
I will go ahead and close this issue as I don't see anything actionable here. Without a clear reproducible example it is difficult to work on a fix. Happy to re-open if the problem/bug can be better encapsulated.
