### ISSUE TITLE
How to live test&debug a current browser (hosting by command webdriver-manager start) ?

### ISSUE THREAD

**Issue by machei** [webdriverio/webdriverio#799]
I wanna to debug a own project on mode remotely debugging without using any file script.

I dont know how to connect to selenium or webdriver...

Maybe somebody tells me how to debug remotely? I wanna type something on console like terminal for debugging like favourite tool `Chrome Developer Tools > Console`

**Comment by christian-bromann** [comment]
Sorry but I don't understand the problem? How is your issue related to WebdriverIO?

**Comment by machei** [comment]
I found something from protractor with command --explorerElement, but still doesnt support test framework like that jasmine
example: `expect(element.all('a').count()).toBe(5)`, that expect will be called as undefined.
Any idea for improving quality of work?

**Comment by christian-bromann** [comment]
This is not protractor :wink: 
Please file an issue [here](https://github.com/angular/protractor)
