### ISSUE TITLE
[📖 Docs]: Clarity on Overwriting Native Commands

### ISSUE THREAD

**Issue by betaorbust** [webdriverio/webdriverio#7991]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Unclear documentation

### Description of the improvement / report

Can you clarify the context around the [Overwriting Native Commands](https://webdriver.io/docs/customcommands#overwriting-native-commands) section?
Currently it says:
> It is not recommended to do this, because it may lead to unpredictable behavior of the framework!

A couple questions: 
- Is this unpredictable because you could cause native commands to do things that aren't in the standard docs, or unpredictable because messing with native commands cause unpredictable platform/framework behavior?
- We're currently considering using this to monkey patch some commands to support our corner case platforms/code. Is this functionality expected to continue to be supported, or are there active plans to deprecate `overwriteCommand` in the relatively near future? (Trying to judge how much runway this buys us.)

Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
> * Is this unpredictable because you could cause native commands to do things that aren't in the standard docs, or unpredictable because messing with native commands cause unpredictable platform/framework behavior?

Both. It also might confuse people that aren't aware that these commands got overwritten.

> * We're currently considering using this to monkey patch some commands to support our corner case platforms/code. Is this functionality expected to continue to be supported, or are there active plans to deprecate `overwriteCommand` in the relatively near future? (Trying to judge how much runway this buys us.)

We don't plan to deprecate this.

**Comment by betaorbust** [comment]
Thank you!
