### ISSUE TITLE
[💡 Feature]: Expose CID on hooks like before and after

### ISSUE THREAD

**Issue by x8co** [webdriverio/webdriverio#7992]
### Is your feature request related to a problem?

I need to create a framework where i can assign login credentials from a pool of available credentials and then add it back to the pool once the execution is over as we do not support multi session login 

To do this we need to get CID in before hook so we can do the assignment dynamically. Right now i see absolutely no way to achieve this in wdio

### Describe the solution you'd like.

1. Expose CID in before/beforeSession and afterSuite/afterSession hook

### Describe alternatives you've considered.

Tried to make use of Process ID but as we can get PID of child process only in before hook which is already in parallel threads the child threads cannot effectively communicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
> Tried to make use of Process ID but as we can get PID of child process only in before hook which is already in parallel threads the child threads cannot effectively communicate

I don't understand why is it not possible to assign the login credentials within the `beforeSession` or `before` hook?

**Comment by x8co** [comment]
BTW i did try to use '@wdio/shared-store-service' wherein in the beforeSession i try to update a list of used id's but again this is not useful as they all run in parallel and 2 parallel worker can update the list at same position

**Comment by christian-bromann** [comment]
I think the easier solution would be to expose the CID as environment variable within the worker process. This should be a fairly simple enhancement. Contributions welcome!

**Comment by razan45** [comment]
Added a PR as I had a similar use case.

**Comment by christian-bromann** [comment]
With #8560 you have now access to the cid within the worker via `process.env.WDIO_WORKER_ID`.
