### ISSUE TITLE
[🐛 Bug]: ESM module exports in Puppeteer 13.3.0 break devtools integration (ERR_PACKAGE_PATH_NOT_EXPORTED)

### ISSUE THREAD

**Issue by jan-molak** [webdriverio/webdriverio#7994]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.14

### Node.js Version

16.13.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
headless: true,
    automationProtocol: 'devtools',

    runner: 'local',

    capabilities: [{

        browserName: 'chrome',
        'goog:chromeOptions': {
            args: [
                '--headless',
                '--disable-infobars',
                '--no-sandbox',
                '--disable-gpu',
                '--window-size=1024x768',
            ],
        },
    }],
```

### What happened?

- WebdriverIO defines its [dependency on `puppeteer-core`](https://github.com/webdriverio/webdriverio/blob/aad97d5b6819039d667bdb89a1324fe139dbea6a/packages/devtools/package.json#L34) as a range of `^13.1.3`
- In version 13.3.0, Puppeteer introduced [support for ESM modules](https://github.com/puppeteer/puppeteer/commit/523b487e8802824cecff86d256b4f7dbc4c47c8a#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R7-R10), which seems to be backwards-incompatible
- This means that imports used in the `devtools`, such as [these ones](https://github.com/webdriverio/webdriverio/blob/4c27abfecd64322173c50f6cb38c2c7e41470a2d/packages/devtools/src/commands/performActions.ts#L1-L2) now break with `ERR_PACKAGE_PATH_NOT_EXPORTED` since the files that WebdriverIO expects to be available are no longer exported by `puppeteer-core`
- see puppeteer/puppeteer/issues/7986

```
@serenity-js/webdriverio: [0-8] 2022-02-09T19:46:25.742Z ERROR @wdio/runner: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/cjs/puppeteer/common/USKeyboardLayout' is not defined by "exports" in /home/runner/work/serenity-js/serenity-js/packages/webdriverio/node_modules/webdriverio/node_modules/puppeteer-core/package.json
@serenity-js/webdriverio: [0-8]     at new NodeError (internal/errors.js:322:7)
@serenity-js/webdriverio: [0-8]     at throwExportsNotFound (internal/modules/esm/resolve.js:332:9)
@serenity-js/webdriverio: [0-8]     at packageExportsResolve (internal/modules/esm/resolve.js:565:3)
@serenity-js/webdriverio: [0-8]     at resolveExports (internal/modules/cjs/loader.js:450:36)
@serenity-js/webdriverio: [0-8]     at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
@serenity-js/webdriverio: [0-8]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
@serenity-js/webdriverio: [0-8]     at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/runner/work/serenity-js/serenity-js/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
@serenity-js/webdriverio: [0-8]     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
@serenity-js/webdriverio: [0-8]     at Module.require (internal/modules/cjs/loader.js:974:19)
@serenity-js/webdriverio: [0-8]     at require (internal/modules/cjs/helpers.js:101:18)
```

@christian-bromann?

### What is your expected behavior?

I'd expect WebdriverIO to work with Puppeteer and not throw errors

### How to reproduce the bug.

- Run any test in WebdriverIO using the `devtools` protocol, local Chrome (I'm using v98) and `puppeteer-core` 13.3.0
- see `ERR_PACKAGE_PATH_NOT_EXPORTED`

### Relevant log output

```typescript
See above.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
This problem is caused based on one of the imports you find in [`performActions.ts`](https://github.com/webdriverio/webdriverio/blob/main/packages/devtools/src/commands/performActions.ts#L1). I had to import it this way because there was no other way to do so and of course at some points it would break. The solution to this would be to find a better way to import this file. Maybe they properly export it now.

@jan-molak you want to take a stab at it?

**Comment by jan-molak** [comment]
I might give it a shot tonight ;-)

**Comment by abianche** [comment]
Is there any way to workaround the issue until this gets fixed?
Thanks.

**Comment by jan-molak** [comment]
OK, Puppeteer has reverted the change in `13.3.1` (https://github.com/puppeteer/puppeteer/commit/179ededa1400c35c1f2edc015548e0f2a1bcee14). 
Closing.

**Comment by christian-bromann** [comment]
Awesome!

**Comment by pdrmailbox** [comment]
> Is there any way to workaround the issue until this gets fixed? Thanks.
> 
> EDIT: downgrading wdio deps. obviously worked.

**Workaround**

If you have backup of "node_modules/puppeteer-core" then overwrite it. It worked for us.

Also you may try using previous version of "puppeteer-core" package from https://www.npmjs.com/package/puppeteer-core.
