### ISSUE TITLE
[🐛 Bug]: touchAction('tap') not working on custom TextInput component

### ISSUE THREAD

**Issue by LayMui** [webdriverio/webdriverio#7995]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.14

### Node.js Version

16.13.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
browserName: '',
    platformName: 'iOS',
    maxInstances: 1,
    // For W3C the appium capabilities need to have an extension prefix
    // This is `appium:` for all Appium Capabilities which can be found here
    // http://appium.io/docs/en/writing-running-appium/caps/
    'appium:deviceName': 'iPhone 13',
    'appium:platformVersion': '15.2',
    'appium:orientation': 'PORTRAIT',
    'appium:automationName': 'XCUITest',
    // The path to the app
    'appium:app': join(process.cwd(), './tests/apps/navapp.app'),
    // Read the reset strategies very well, they differ per platform, see
    // http://appium.io/docs/en/writing-running-appium/other/reset-strategies/
    'appium:noReset': false,
    'appium:newCommandTimeout': 240,
```

### What happened?

I have a UI component from design system component called AhuaTextInput
this component is not responding to touchAction('tap')
i have to physically tap on the AhuatextInput for the setValue or addValue to take place

the accessibilityLabel is set for this AhuaTextInput to be 'AhuaTextInput' as verified by the accessibility inspector
it works for the React native text input with accessibilityLabel 'PhoneNumberInput'
but it does not work for the AhuaTextinput 
  instead this line     await $('~AhuaTextInput').setValue(text) , I expect it the enter the text to the AhuaTextInput but the text appear in the PhoneNumberInput

here is the code snippet
```
async enterText(text) {

         await $('~PhoneNumberInput').waitForDisplayed()
         await $('~PhoneNumberInput').touchAction('tap')
         await $('~PhoneNumberInput').addValue(text)

          await $('~AhuaTextInput').waitForDisplayed()
          await $('~AhuaTextInput').touchAction('tap') //Issue with touchAction
          await $('~AhuaTextInput').setValue(text)
````
          
  }

### What is your expected behavior?

expect the text to be entered into the AhuaTextInput component

### How to reproduce the bug.

github repo
https://github.com/LayMui/navapp-with-automation

in xcode (Version 13.2.1 (13C100)

cd ios
open the  navapp.xcworkspace
and build the project to run the metro bundler 
start a simulator iphone 13, iOS 15.2

in another terminal
run 
yarn ios.app

### Relevant log output

```typescript
refer to the Issue.md
https://github.com/LayMui/navapp-with-automation/blob/master/Issue.md
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Hey,
thanks for filing the issue. We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by LayMui** [comment]
this issue is due to testID hardcoded to inputPress on the custom component.
this is resolved
