### ISSUE TITLE
[🐛 Bug]: wdio-reporter stops reporting skipped test step for cucumber since version 7.16.11 of @wdio/cucumber-framework

### ISSUE THREAD

**Issue by wenzhhu** [webdriverio/webdriverio#8007]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.11+

### Node.js Version

14.18.3

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
        browserName: 'chrome'
}
```

### What happened?

Starting from version 7.16.11. WDIO reporters stop reporting skipped test step for cucumber.

### What is your expected behavior?

WDIO reporters should still report skipped test step for cucumber.

### How to reproduce the bug.

https://github.com/wenzhhu/wdio-cucumber-framework-bug-8007

### Relevant log output

```typescript
"spec" Reporter:
------------------------------------------------------------------
[Chrome 98.0.4758.80 darwin #0-0] Running: Chrome (v98.0.4758.80) on darwin
[Chrome 98.0.4758.80 darwin #0-0] Session ID: 2808bbc0-6509-40ae-ad6d-c41ef1e70363
[Chrome 98.0.4758.80 darwin #0-0]
[Chrome 98.0.4758.80 darwin #0-0] » /features/my-feature.feature
[Chrome 98.0.4758.80 darwin #0-0] Example feature
[Chrome 98.0.4758.80 darwin #0-0] As a user of WebdriverIO
[Chrome 98.0.4758.80 darwin #0-0] I should be able to use different commands
[Chrome 98.0.4758.80 darwin #0-0] to get informations about elements on the page
[Chrome 98.0.4758.80 darwin #0-0]
[Chrome 98.0.4758.80 darwin #0-0] Get size of an element
[Chrome 98.0.4758.80 darwin #0-0]    ✓ Given this is passing step
[Chrome 98.0.4758.80 darwin #0-0]    ✖ Then this is failing step
[Chrome 98.0.4758.80 darwin #0-0]    ? Given this is passing step
[Chrome 98.0.4758.80 darwin #0-0]
[Chrome 98.0.4758.80 darwin #0-0] 1 passing (41ms)
[Chrome 98.0.4758.80 darwin #0-0] 1 failing
[Chrome 98.0.4758.80 darwin #0-0]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

This seems like a regression indeed. You want to help us get this fixed?

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by wenzhhu** [comment]
Thanks @christian-bromann,

I'd love to help to contribute. The thing is that the original fix  https://github.com/webdriverio/webdriverio/pull/7777 is a bit unclear to me. I would like to have a thorough understanding of what problem the original fix tried to solve first so that I could provide a proper fix for the bug I reported here.

Given that the regression is a bit serious IMO, I think we better roll back fix https://github.com/webdriverio/webdriverio/pull/7777 in next release if it will be due soon.

I will try to make a re-attempt for the original problem with some extra regression tests then.

Please let me know how you think. Thanks.

**Comment by christian-bromann** [comment]
@wswebcreation can you chime in on this?

**Comment by kaksjonovs** [comment]
Issue still reproducible in `7.19.5`.

**Comment by lacell75** [comment]
I reproduced this issue also since the upgrade wdio to latest version. I will try to fix it today.

**Comment by kaksjonovs** [comment]
@lacell75 Waiting for the review: https://github.com/webdriverio/webdriverio/pull/8262
