### ISSUE TITLE
[🐛 Bug]: appium-service does not start automatically for appium version 2.0.0-beta.25

### ISSUE THREAD

**Issue by Plazzko** [webdriverio/webdriverio#8012]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.14.1

### Node.js Version

14.18.2

### Mode

WDIO Testrunner

### What happened?

Appium-service never gets launched and therefore the tests are never run. 

### What is your expected behavior?

Appium service should start the appium server.

### How to reproduce the bug.

Full instructions can be found here:
1. https://appiumpro.com/editions/122-installing-appium-20-and-the-driver-and-plugins-cli
2. https://appiumpro.com/editions/123-migrating-to-appium-20-part-1-capability-prefixes

Add `@wdio/appium-service` and try to run any test. The server will never launch. 

### Relevant log output

There isn't one, but I can share with you my findings.

I was able to dig through the code and find the issue. It seems that the callback inside of the `startAppium` (AppiumLauncher class) method never gets called. The reason for it is that the code is waiting for the message from appium to be piped to the `stdout` stream, but instead, in the new appium version, the message is piped out to the `stderr` stream.

It seems that the appium library is using `https://github.com/npm/npmlog` which pipes the output to `stderr` by default. I was unable to figure out how the output previously was piped to the `stdout`. That being said if I subscribed to the `stderr` steam and moved the if statement there (from the `stdout` block), it seemed to work normally. However, there is some additional code there and I'm not sure if this is the best thing to do.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> There isn't one, but I can share with you my findings.

Can you set the [`outputDir`](https://webdriver.io/docs/options#outputdir) option and provide the file contents here including the stdout?

**Comment by Plazzko** [comment]
> > There isn't one, but I can share with you my findings.
> 
> Can you set the [`outputDir`](https://webdriver.io/docs/options#outputdir) option and provide the file contents here including the stdout?

Sure. Here is the log (I had to use `ctrl+c` to exit the process):
[wdio.log](https://github.com/webdriverio/webdriverio/files/8062123/wdio.log)

**Comment by AntonKostenko** [comment]
Hey @Plazzko, I was also running into this using appium 2.0. The issues appear to be `arg` related. I was able to work around this issue by removing all `args` from the appium service. 
I believe that all the `--port --address --log-level` args you have are not needed as they are provided/available in other areas of the `wdio.conf.ts` file through `port`, `baseUrl`, `logLevels {'@wdio/appium-service': 'debug'}`. I was also able to get around not needing  relaxed-caps by adding the vendor and wrapping the cape in quotes. `'appium:automationName': 'automationNameValue'`.

**Comment by nextlevelbeard** [comment]
I can consistently replicate the issue when upgrading from Appium beta 19 to beta 20.
Here's a diff of those two versions.
https://github.com/appium/appium/compare/appium%402.0.0-beta.19...appium%402.0.0-beta.20

**Comment by sam-022** [comment]
With latest `2.0.0-beta.27` appium version, I am seeing the following error when spinning up appium-service - 

`An unknown server-side error occurred while processing the command. Original error: Could not find a driver for automationName 'UIAutomator2' and platformName Android'. Have you installed a driver that supports those capabilities? Run 'appium driver list --installed' to see. (Lower-level error: Could not find installed driver to support given caps)`

I already have the driver installed as well - 

```
appium driver list --installed
✔ Listing installed drivers
- uiautomator2@1.75.0 [installed (NPM)]
- xcuitest@3.53.1 [installed (NPM)]
```

Note: this works fine with `2.0.0-beta.19` version.

**Comment by ranam2030** [comment]
With appium 2.0.0-beta.27, when installing some new package I am getting the error called - 
`An unknown server-side error occurred while processing the command. Original error: Could not find a driver for automationName 'UIAutomator2' and platformName Android'. Have you installed a driver that supports those capabilities? Run 'appium driver list --installed' to see. (Lower-level error: Could not find installed driver to support given caps)`

But I already have the driver and it's works fine before installing the new package.

**Comment by Plazzko** [comment]
I'm no longer working on a webdriver project, but the issue seems to be resolved. More info can be found here: https://github.com/appium/appium/issues/16676#issuecomment-1234683455
