### ISSUE TITLE
[🐛 Bug]: Importing WebDriver from a ESM package fails

### ISSUE THREAD

**Issue by serverwentdown** [webdriverio/webdriverio#8017]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.14

### Node.js Version

16.13.1

### Mode

Standalone Mode

### What happened?

Attempts to import WebDriver from an ESModule fails

### index.js
```js
import WebDriver from 'webdriver'
console.debug(WebDriver);
WebDriver.newSession();
```

### package.json
```json
{
  "name": "webdriver-import-fail",
  "type": "module",
  "dependencies": {
    "webdriver": "^7.16.14"
  }
}
```

### Relevant log output

```bash
$ node index.js
{
  getPrototype: [Getter],
  DEFAULTS: [Getter],
  command: [Function: default_1],
  default: [class WebDriver]
}
file:///home/ambrose/Documents/webdriver-import-fail/index.js:3
WebDriver.newSession();
          ^

TypeError: WebDriver.newSession is not a function
    at file:///home/ambrose/Documents/webdriver-import-fail/index.js:3:11
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)      
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
This is a known issue and progress to make WebdriverIO and its sub packages ESM compatible was done in #6812. Unfortunately due to a blocker there wasn't much progress on that.
