### ISSUE TITLE
[🐛 Bug]: `Cannot find name 'browser'.ts(2304)` and `Namespace 'global.WebdriverIO' has no exported member 'Element'.ts(2694)`

### ISSUE THREAD

**Issue by Lucasmiguelmac** [webdriverio/webdriverio#8018]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

v14.15.1

### Mode

WDIO Testrunner

### What happened?

I just created a default project with latest everything choosing TypeScript and Cucumber. Tests pass, but when I go to the pageobjects fijes I get the following errors:
```
Namespace 'global.WebdriverIO' has no exported member 'Element' .ts(2694)
```
```
Cannot find name '$'. Do you need to install type definitions for jQuery? Try `npm i --save-dev @types/jquery`.ts(2581)
```
```
Cannot find name 'browser'.ts(2304)
```

### What is your expected behavior?

This errors should not be popping.

### How to reproduce the bug.

- Create npm project ( `npm init -y` )
- Create wdio project ( `npm init wdio` )
    - Selected typescript and cucumber
- Run automatically generated tests -> pass
- Go to see pageobjects at `features/pageobjects`
- See TS errors raise with `WebdriverIO.Element` and, `browser` and `$` objects:
```
Namespace 'global.WebdriverIO' has no exported member 'Element' .ts(2694)
```
```
Cannot find name '$'. Do you need to install type definitions for jQuery? Try `npm i --save-dev @types/jquery`.ts(2581)
```
```
Cannot find name 'browser'.ts(2304)
```

### Relevant log output

```typescript
Namespace 'global.WebdriverIO' has no exported member 'Element' .ts(2694)
```
```
Cannot find name '$'. Do you need to install type definitions for jQuery? Try `npm i --save-dev @types/jquery`.ts(2581)
```
```
Cannot find name 'browser'.ts(2304)
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> I just created a default project with latest everything choosing TypeScript and Cucumber.

Did you use `npm init wdio`? Can you share your `tsconfig`?

**Comment by Lucasmiguelmac** [comment]
> 

Yes I did. I used `npm init wdio .` to be precise. But it shouldn't change anything.

Here's my `tsconfig.json`:
```json
{
    "compilerOptions": {
        "types": [
            "node",
            "webdriverio/async",
            "@wdio/cucumber-framework",
            "expect-webdriverio"
        ],
        "target": "ES5"
    }
}
```

**Comment by Lucasmiguelmac** [comment]
Already fixed it. Apparently the installer sent my `tsconfig` and my `wdio.conf` as well inside a `/test/` directory. Never happened to me before. Easy fix though.

**Comment by minakshif** [comment]
I am also facing same issue as $ and Browser cant find. plz provide solution

**Comment by bolem3560** [comment]
I am also facing same issue as $ and Browser cant find. plz provide solution

**Comment by Akupsmee** [comment]
> @Lucasmiguelmac How did you fix the issue? I'm also facing issue with $ and browser commands when I tried to run the scripts with type script

I guess you need to cross check your setup. what does your  tsconffig.json file look like?

here is mine : 
`{
    "compilerOptions": {
        "types": [
            "node",
            "webdriverio/async",
            "@wdio/cucumber-framework",
            "expect-webdriverio"
        ],
        "target": "es2019",
        "moduleResolution": "Node"
    }
}`

**Comment by octome22001** [comment]
@minakshif @bolem3560 @Akupsmee you can try moving 2 files "tsconfig" and "wdio.conf" out of the "test" folder to the root project folder. Hope it works for you guys.

**Comment by HaHuynhVN** [comment]
@minakshif @bolem3560 @Akupsmee you can try moving 2 files "tsconfig" and "wdio.conf" out of the "test" folder to the root project folder. Hope it works for you guys.

**Comment by darkartswizard** [comment]
TypeScript install error closed and never fixed?

**Comment by matzetronic** [comment]
same here 😞

**Comment by Dinoraptor101** [comment]
> ```json
>             "webdriverio/async",
> ```

This resolved my problem, they Removed  "webdriverio/async", and replacted it with "@wdio/globals/types"  in WDIO 8 and later.

**Comment by Dinoraptor101** [comment]
> > ```json
> >             "@wdio/globals/types",
> > ```
> 
> This resolved my problem, they Removed "webdriverio/async", and replacted it with "@wdio/globals/types" in WDIO 8 and later.

**Comment by kapparao** [comment]
> ```ts
> Namespace 'global.WebdriverIO' has no exported member 'Element'
> ```

How you resolve this issue. Could you explain please..

**Comment by kapparao** [comment]
> ~same here 😞~ works using Node 16 and the following tsconfig.json setting:
> 
> ```json
> {
>   "compilerOptions": {
>     "types": ["node", "@wdio/globals/types"],
>   }
> }
> ```
> 
> 👍🏻

`{

    "compilerOptions": {
        "moduleResolution": "node",
        "module": "ESNext",
        "types": [          
            "node","chai",
            "@wdio/globals/types",
            "webdriverio/async",
            "expect-webdriverio",
            "@wdio/cucumber-framework"

        ],
        "typeRoots": ["node_modules/@types"],
        "target": "es2022",
        "esModuleInterop": true,
        "resolveJsonModule": true,
    }

}`
Still facing this issue. even, edit as yours..
above is my tsconfig.json.. Is it Correct or need to change anything..

**Comment by reemadaga** [comment]
I am facing the same issue with webdriverIO 7. upgrading from web driverIO 6 to 7. Can someone please share the solution?

**Namespace 'global.WebdriverIO' has no exported member 'Element'.**

Sharing the compiler options in tsconfig:
"typeRoots": ["./node_modules/@types"],
        "types": [
            "node", 
            "webdriverio/async",
            "@wdio/mocha-framework", 
            "wdio-native-app-compare-service",
            "expect-webdriverio",
            "./src/types/global",
        ],

**Comment by christian-bromann** [comment]
@reemadaga I recommend updating to v8 as we don't actively maintain v7 anymore.

**Comment by reemadaga** [comment]
Just curious as to what changed when I moved from sync to async. Thank you in advance

**Comment by christian-bromann** [comment]
> Just curious as to what changed when I moved from sync to async.

Some types have changed since v6 and all commands are now asynchronous.

**Comment by reemadaga** [comment]
@christian-bromann 
I have tried upgrading to v8 and ran into the following issues:
While resolving: @wdio/allure-reporter@7.33.0
npm ERR! Found: @wdio/cli@8.27.1
npm ERR! node_modules/@wdio/cli
npm ERR!   dev @wdio/cli@"^8.27.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @wdio/cli@"^7.0.0" from @wdio/allure-reporter@7.33.0
npm ERR! node_modules/@wdio/allure-reporter
npm ERR!   dev @wdio/allure-reporter@"^7.33.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @wdio/cli@7.34.0
npm ERR! node_modules/@wdio/cli
npm ERR!   peer @wdio/cli@"^7.0.0" from @wdio/allure-reporter@7.33.0
npm ERR!   node_modules/@wdio/allure-reporter
npm ERR!     dev @wdio/allure-reporter@"^7.33.0" from the root project

**Comment by christian-bromann** [comment]
You seem to have a lot of mixed dependencies, I recommend to update all WDIO related packages.

**Comment by reemadaga** [comment]
@christian-bromann how do you recommend I do that? I tried installing the packages individually but that is failing as well.

**Comment by reemadaga** [comment]
@christian-bromann I resolved the issue by using --force to install packages

**Comment by reemadaga** [comment]
024-01-20T00:03:48.764Z ERROR webdriver: Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: Failed to receive any data within the timeout: 5000
[0-0] 2024-01-20T00:03:48.764Z ERROR webdriver: unknown error: An unknown server-side error occurred while processing the command. Original error: Failed to receive any data within the timeout: 5000
[0-0]     at getErrorFromResponseBody (xxx/node_modules/webdriver/build/utils.js:195:12)
[0-0]     at NodeJSRequest._request (xxx/node_modules/webdriver/build/request/index.js:193:23)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async startWebDriverSession (xxx/node_modules/webdriver/build/utils.js:64:20)
[0-0]     at async WebDriver.newSession (xxx/node_modules/webdriver/build/index.js:19:45)
[0-0]     at async remote (xxx/node_modules/webdriverio/build/index.js:45:22)
[0-0]     at async Runner._startSession (xxx/node_modules/@wdio/runner/build/index.js:224:29)
[0-0]     at async Runner._initSession (xxx/node_modules/@wdio/runner/build/index.js:190:25)
[0-0]     at async Runner.run (xxx/node_modules/@wdio/runner/build/index.js:79:19)
[0-0] 2024-01-20T00:03:48.765Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] An unknown server-side error occurred while processing the command. Original error: Failed to receive any data within the timeout: 5000
[0-0]     at startWebDriverSession (xxx/node_modules/webdriver/build/utils.js:69:15)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async WebDriver.newSession (xxx/node_modules/webdriver/build/index.js:19:45)
[0-0]     at async remote (xxx/node_modules/webdriverio/build/index.js:45:22)
[0-0]     at async Runner._startSession (xxx/node_modules/@wdio/runner/build/index.js:224:29)
[0-0]     at async Runner._initSession (xxx/node_modules/@wdio/runner/build/index.js:190:25)
[0-0]     at async Runner.run (xxx/node_modules/@wdio/runner/build/index.js:79:19)

**Comment by prajapatiharshit** [comment]
`{
  "compilerOptions": {
    "outDir": "./dist/wdio",
    "target": "ESNext",
    "module": "CommonJS",
    "removeComments": true,
    "moduleResolution": "Node",
    "esModuleInterop": true,
    "types": ["node", "@wdio/globals/types", "expect-webdriverio", "@wdio/jasmine-framework", "@wdio/devtools-service","axios","jasmine"],
    "resolveJsonModule": true,
    "typeRoots": ["node_modules/@types"],
    "lib": ["es2018", "dom", "dom.iterable"],
    "allowSyntheticDefaultImports": true,
  }`

My `tsconfig.json` file looked like above, I just added "ESNext" in lib and it was resolved.
