### ISSUE TITLE
mocha --compilers option not recognized by wdio runner

### ISSUE THREAD

**Issue by kabirsikand** [webdriverio/webdriverio#802]
```
    framework: 'mocha',

    mochaOpts: {
        ui: 'bdd',
        compilers: {'coffee': 'coffee-script/register'}
    }
```

The `compilers` flag isn't actually set when running mocha via wdio. Test this by running the simple coffeescript test below:

```
describe 'Google Search Test', ->
  it 'goes to google', ->
    browser.url("http://www.google.com")
      .getTitle().should.eventually.eql('Google')
```

The compiled JS (compiled via `coffee -c <file>` on Coffeescript 1.7.1):

```
// Generated by CoffeeScript 1.7.1
(function() {
  describe('Google Search Test', function() {
    return it('goes to google', function() {
      return browser.url("http://www.google.com").getTitle().should.eventually.eql('Google');
    });
  });

}).call(this);
```

**Comment by kabirsikand** [comment]
Looks like I had bad syntax - this isn't a bug, but rather an enhancement now.
It accepts an array with 'x:y' strings
```
    mochaOpts: {
        ui: 'bdd',
        compilers: ['coffee:coffee-script/register']
    },
```

**Comment by kabirsikand** [comment]
I think we might want to add this to the docs^

**Comment by christian-bromann** [comment]
ohh, ok well the examples are using arrays as well http://webdriver.io/guide/getstarted/configuration.html
Feel free to create a PR with a section that describes how to use/compile coffee script.
