### ISSUE TITLE
[🐛 Bug]: DevTools service fails to setup ('browser.cdp is not a function') when loading a URL in the before() hook

### ISSUE THREAD

**Issue by johnBartos** [webdriverio/webdriverio#8021]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### What happened?

The DevTools service's `before` hook is executed before before the `browser.url = awaited'` log is emitted. As a result, the check here https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-devtools-service/src/index.ts#L234 to find the current page fails.

### What is your expected behavior?

The `before` hook is awaited and blocks the `before` hook of the DevTools service, so that I can load the page before the DevTools service tries to set up.

### How to reproduce the bug.

Try this config:
```
{
    services: [['selenium-standalone', { drivers: { firefox: '0.29.1', chrome: '98.0.4758.80' } }], 'devtools'],
    before: async () => {
        console.log('>>> BEFORE');
        await browser.url(browser.options.baseUrl);
        console.log('browser.url = awaited');
    }
}
```
### Relevant log output

```typescript
[0-0] >>> BEFORE
[0-0] >>> DEVTOOLS SERVICE BEFORE
[0-0] >>>> SETUP
[0-0] >>>> SUPPORTED
[0-0] 2022-02-16T19:56:08.674Z DEBUG @wdio/utils:shim: Finished to run "beforeCommand" hook in 1ms
[0-0] 2022-02-16T19:56:08.678Z DEBUG @wdio/utils:shim: Finished to run "beforeCommand" hook in 0ms
[0-0] 2022-02-16T19:56:08.680Z INFO webdriver: COMMAND navigateTo(URL)
[0-0] 2022-02-16T19:56:08.680Z INFO webdriver: [POST] URL
[0-0] 2022-02-16T19:56:08.680Z INFO webdriver: DATA {
[0-0]   url: URL
[0-0] }
[0-0] 2022-02-16T19:56:08.798Z DEBUG @wdio/utils:shim: Finished to run "afterCommand" hook in 0ms
[0-0] >>>> HAS PUPPETEER
[0-0] >>>> HAS TARGET
[0-0] >>>> NO PAGE
[0-0] 2022-02-16T19:56:09.215Z DEBUG @wdio/utils:shim: Finished to run "afterCommand" hook in 0ms
[0-0] 2022-02-16T19:56:09.215Z DEBUG @wdio/utils:shim: Finished to run "afterCommand" hook in 0ms
[0-0] browser.url = awaited


```
The above logs (DEVTOOLS SERVICE, BEFORE, SETUP, SUPPORTED, HAS PUPPETEER, HAS TARGET, NO PAGE) were added to the DevTools _setupHandler() function.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by johnBartos** [comment]
I removed ` || t['_targetInfo'].browserContextId)` from https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-devtools-service/src/index.ts#L228 because I noticed that when the DevTools service failed to setup, the target it grabbed seemed to be the Chrome DevTools target instead of the actual page. Maybe this is the bug?

**Comment by johnBartos** [comment]
https://github.com/webdriverio/webdriverio/pull/6664 comes back from the blame

**Comment by johnBartos** [comment]
Happy to put up a PR, just wondering what a fix would look like. I can think of:

* Reverting #6664
* Preferring `t.type() === 'page'` if it exists

For 2, I was thinking of something like

```
this._target = await Promise.allSettled([
    this._puppeteer.waitForTarget((t) => t.type() === 'page'),
    this._puppeteer.waitForTarget((t) => ['_targetInfo'].browserContextId)
]).then(results => results[0] || results[1]);
```

But it needs work to not wait for 30s if either target never exists.

**Comment by christian-bromann** [comment]
@johnBartos thanks for investigating this. The second option looks good to me. Mind raising a PR?

**Comment by amandaflagg** [comment]
I believe this is blocking me from being able to mock geolocation data using devtools in my tests. @christian-bromann Does this issue just need someone to create a PR with @johnBartos's suggested solution (the 2nd one)?

**Comment by christian-bromann** [comment]
@amandaflagg any contributions that provide a fix for this are appreciated.

**Comment by christian-bromann** [comment]
At this point I recommend to use the [`getPuppeteer`](https://webdriver.io/docs/api/browser/getPuppeteer/) command and access the Puppeteer API directly. With v9 of WebdriverIO we will deprecate the `devtools` package as it is not valuable anymore to maintain this much longer.
