### ISSUE TITLE
[🐛 Bug]: [ts] Property 'options' does not exist on type 'Browser'.

### ISSUE THREAD

**Issue by srpalwaidynamite** [webdriverio/webdriverio#8044]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v7.16.7

### Node.js Version

v12.18.4

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [
    {
      platformName: 'Android',
      maxInstances: 1,
      'appium:deviceName': 'Zebra_TC57_API_30',
      'appium:platformVersion': '11.0',    
      'appium:orientation': 'PORTRAIT',
      'appium:automationName': 'UiAutomator2',
      'appium:app': join(process.cwd(), './e2e/bin/storeinsights.apk'),
      'appium:appWaitActivity': 'host.exp.exponent.MainActivity',
      'appium:fullReset': true,
      'appium:newCommandTimeout': 240,
    }
]
```

### What happened?

I would like to use storeNumber value in the testscripts which is actually defined in wdio.conf.ts file.
![dqTdPVzehBlkTyoVpWNnVzdJ](https://user-images.githubusercontent.com/95707610/155203991-9bff320e-21e5-4197-825c-6d99851bc8ea.png)
 I'm seeing above error "[ts] Property 'options' does not exist on type 'Browser'." when I mouseover on options
and value is not getting entered

### What is your expected behavior?

storeNumber should get entered

### How to reproduce the bug.

Define a variable in wdio.conf.ts

storeNumber:256

and try to use above variable in the test scripts
 browser.options.storeNumber
<img width="725" alt="image" src="https://user-images.githubusercontent.com/95707610/155204305-53156cc0-8383-4e28-bdbe-b45449aa5408.png">
<img width="710" alt="image" src="https://user-images.githubusercontent.com/95707610/155204354-05b18de6-5a67-4969-a950-25545031fc11.png">

### Relevant log output

```typescript
I'm seeing above error "[ts] Property 'options' does not exist on type 'Browser'." when I mouseover on options
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@srpalwaidynamite I can reproduce the issue. I created a sample project via:

```sh
npm create wdio /some/dir
```

and then picked TypeScript as compiler. In the page object as well as within the test the `browser.options` object is given. Can you verify your TypeScript settings and compare it with a new project template?

Closing, but happy to re-open if I missed something.
