### ISSUE TITLE
[🐛 Bug]: Getters outputted in login.page.ts from CLI have TypeScript error

### ISSUE THREAD

**Issue by WillBrock** [webdriverio/webdriverio#8047]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.15

### Node.js Version

16

### Mode

WDIO Testrunner

### What happened?

The change in #7978 is causing the types on getters to throw errors. This is happening on a clean install and typescript project generated from the CLI. When I remove the change from 7978 the error goes away.

I'm not sure what the fix would be but happy to create a PR if there are any suggestions or we revert the previous change.

```javascript
    public get inputUsername(): ChainablePromiseElement<Promise<WebdriverIO.Element>> {
        return $('#username');
    }
```

`Type 'ChainablePromiseElement<Element>' is not assignable to type 'ChainablePromiseElement<Promise<Element>>'`

### How to reproduce the bug.

Create a new typescript project following the [Getting Started Guide](https://webdriver.io/docs/gettingstarted)

Open up the login.page.ts file and you'll see the typescript error on the getters.

``Type 'ChainablePromiseElement<Element>' is not assignable to type 'ChainablePromiseElement<Promise<Element>>'``

### Relevant log output

```typescript
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@WillBrock why do you need to explicity type this getter? TypeScript infers the type from the returned value. There are only some cases in TypeScript where you explicitly need to type the return value. Also according to the error, this should work fine:

```ts
    public get inputUsername(): ChainablePromiseElement<WebdriverIO.Element> {
        return $('#username');
    }
```

**Comment by WillBrock** [comment]
@christian-bromann The login.page.ts file that is generated from the CLI when creating a new project has the getters as `ChainablePromiseElement<Promise<WebdriverIO.Element>>` included in it.

Should I submit a PR to update what is generated to login.page.ts and just remove the types on the getters? This way when someone installs the example project from the CLI they don't get errors.

**Comment by christian-bromann** [comment]
I already pushed [a commit](https://github.com/webdriverio/webdriverio/commit/1355d548ef364318690ef44bbea4c5657ce64680) with a fix for that. I am working on the Windows workflow pipeline. Once that is fixed we can release this patch.
