### ISSUE TITLE
[💡 Feature]: Allow passing more capabilites via REPL

### ISSUE THREAD

**Issue by gaunap** [webdriverio/webdriverio#8048]
### Is your feature request related to a problem?

Appium breaks up every 60s if no new command is send when using repl for iOS:
`wdio repl ios  --path /wd/hub --platformVersion 15.2 --deviceName 'iPhone 13'`

This makes testing very cumbersome.

The newCommandTimeout of the capabilities cannot be overwritten.

### Describe the solution you'd like.

I like to pass more capbilities to Appium. E.g. using this kind of signature: --"appium:newCommandTimeout" 9999999

### Additional context

My setup is MacOS 12.2.1, wdio 7.16.13, Appium-Server-GUI 1.22 and iphone Simulator 13

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Thanks for reporting!

Any contributions that implements this enhancement are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by praveendvd** [comment]
@christian-bromann when i run `wdio repl chrome` it just creates a new wdio project , it doesnt do anything

**Comment by christian-bromann** [comment]
@praveendvd the repl starts for me:

```
❯ mkdir repltest
❯ cd repltest/
❯ npm i @wdio/cli

added 303 packages, and audited 304 packages in 7s

38 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
❯ npx wdio repl chrome
2022-03-23T12:36:45.496Z INFO devtools:puppeteer: Initiate new session using the DevTools protocol
2022-03-23T12:36:45.497Z INFO devtools: Launch Google Chrome with flags: --enable-automation --disable-popup-blocking --disable-extensions --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-first-run --no-default-browser-check --disable-hang-monitor --disable-prompt-on-repost --disable-client-side-phishing-detection --password-store=basic --use-mock-keychain --disable-component-extensions-with-background-pages --disable-breakpad --disable-dev-shm-usage --disable-ipc-flooding-protection --disable-renderer-backgrounding --force-fieldtrials=*BackgroundTracing/default/ --enable-features=NetworkService,NetworkServiceInProcess --disable-features=site-per-process,TranslateUI,BlinkGenPropertyTrees --window-position=0,0 --window-size=1200,900
2022-03-23T12:36:46.713Z INFO devtools: Connect Puppeteer with browser on port 62158

The execution has stopped!
You can now go into the browser or use the command line as REPL
(To exit, press ^C again or type .exit)

›
```

**Comment by praveendvd** [comment]
@christian-bromann  , the documentation was not clear , if i do `npm install -g wdio`  and then run `wdio repl chrome` we see it just setups up wdio project .

**Comment by praveendvd** [comment]
I could pick this up to improve the documentation and try to upgrade repl to be able to take capability from a file instead so that all caps can be passed as such

**Comment by christian-bromann** [comment]
> npm install -g wdio

This is __not__ the wdio cli package. It is a deprecated package.

**Comment by christian-bromann** [comment]
> I could pick this up to improve the documentation and try to upgrade repl to be able to take capability from a file instead so that all caps can be passed as such

I like the idea of passing in a wdio config but then the user has to provide an index which capability should be picked from the config file.

**Comment by praveendvd** [comment]
> > I could pick this up to improve the documentation and try to upgrade repl to be able to take capability from a file instead so that all caps can be passed as such
> 
> I like the idea of passing in a wdio config but then the user has to provide an index which capability should be picked from the config file.

then the user has to provide an index which capability should be picked from the config file.

Could u elaborate on this @christian-bromann  I didn't quiet understand 🙈

Will have a look at it then

**Comment by christian-bromann** [comment]
So in your `wdio.conf.js` you can define either a set of capabilities, e.g.:

```js
exports.config = {
  // ...
  capabilities: [
    { browserName: "chrome" },
    { browserName: "firefox" },
    { browserName: "safari" }
  ]
  // ...
```
or multiremote capabilities, e.g.:

```js
exports.config = {
  // ...
  capabilities: {
    browserA: { browserName: "chrome" },
    browserB: { browserName: "firefox" },
    browserC: { browserName: "safari" }
  }
  // ...
```

When someone runs a repl, e.g. `wdio repl --config ./wdio.conf.js` I suggest to have the user define a capability either as index (see first example) or as browser name (if second example, e.g.:
```sh
wdio repl --config ./wdio.conf.js --capability 0
// or
wdio repl --config ./wdio.conf.js --capability browserA
```

Does it make sense? Which parameter name would you think is the most intuitive?

> Will have a look at it then

Awesome!

**Comment by praveendvd** [comment]
https://github.com/webdriverio/webdriverio/tree/main/packages/wdio-repl 

I believe this is package we should look into

**Comment by christian-bromann** [comment]
@praveendvd this on is just handling the repl session itself. You might want to take a look how a repl session is being initiated: https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-cli/src/commands/repl.ts

**Comment by praveendvd** [comment]
@gaunap  and @christian-bromann  , lets continue conversation in the PR 🎉
