### ISSUE TITLE
[🐛 Bug]: Unable to use the Web Element identified using $$ and index in other File

### ISSUE THREAD

**Issue by saurabh-gadre** [webdriverio/webdriverio#8059]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.14 & 7.16.16

### Node.js Version

14.16.1

### Mode

WDIO Testrunner

### What happened?

Not sure if this an defect or existing implementation causing issues.
When user is using $$ selector to find a element with multiple occurrence and then appending index using [] in Page Object Typescript file and then storing the web element reference in some class variable and utilizing it in some other file. On Actual test execution The script breaks saying element not found.

example:- 
**SomePage.ts** --->
class SomePage{
       let link_edit = $$('[class="demo-class"]')[0];
       ..........
       ..........
}

other file - **SomePageStepDef.ts** -->

Then("XXXXXXXXXXXXXXX",  async function()=>{
    await somePage.link_edit.click();     // this step does not work
});

Directly using $$('[class="demo-class"]')[0].click() in Step Definition file works. I cannot share the base code as it organization internal and I am working on migration protractor to WebdriverIO.

### What is your expected behavior?

The Element at particular index should be found and script should work when using $$ selector with [] to specify index of the required element.

### How to reproduce the bug.

example:- 
**SomePage.ts** --->
class SomePage{
       let link_edit = $$('[class="demo-class"]')[0];
       ..........
       ..........
}

other file - **SomePageStepDef.ts** -->

Then("XXXXXXXXXXXXXXX",  async function()=>{
    await somePage.link_edit.click();     // this step does not work
});

Directly using $$('[class="demo-class"]')[0].click() in Step Definition file works. I cannot share the base code as it organization internal and I am working on migration protractor to WebdriverIO.

### Relevant log output

```typescript
Error saying unable to click on element of undefined
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> let link_edit = $$('[class="demo-class"]')[0];

Please use proper `async/await` here, e.g.:

```ts
let link_edit = await $$('[class="demo-class"]')[0];
```

**Comment by saurabh-gadre** [comment]
Already tried. Having await class variable is not allowed in the class also constructor cannot be made async. The elements located with $ works fine without even using async / await.

**Comment by christian-bromann** [comment]
@saurabh-gadre have you tried to debug what `console.log($$('[class="demo-class"]'))` returns?

**Comment by saurabh-gadre** [comment]
Hi @christian-bromann, It returns a Promise { pending }. I can directly interact with $$('[class="demo-class"]') and perform click. Issue is when doing following 
In step definition file.

Then("XXXXXXXXXXXXXXX", async function()=>{
await somePage.link_edit.click();  OR

await somePage.link_edit[O]. click (); 
// Defined some var as let link_edit = $$('[class="demo-class"]') in Page Object class
});

In above case the promise does not resolve to an element to perform the click operation. thanks for helping out.

**Comment by saurabh-gadre** [comment]
Yeah right, I understand but believe me, the element array is non-empty. Sharing a example from my local implementation.

import { ChainablePromiseElement } from "webdriverio";
class CommonPage {
  
  menuProducts =$$('[class="collapse navbar-collapse navbar-ex1-collapse"] [class="nav navbar-nav"] a[class="dropdown-toggle"]');
  
  public async openHomePage() {
    await browser.url("https://demo.opencart.com/index.php");

    const pageTitle = await browser.getTitle();
    await expect(await pageTitle).toEqual("Your Store");

  console.log(
      "Menu Product Name index 0: ",
      await $$('[class="collapse navbar-collapse navbar-ex1-collapse"] [class="nav navbar-nav"] a[class="dropdown-toggle"]')[0].getText()
    ); // This works    [0-0] Menu Product Name index 0:  Desktops

    let prodName = await this.menuProducts[0].getText();  // This Fails 
    console.log('Menu Product Name index 0: ', prodName);    
  }
}

export default new CommonPage();


**Error -**
Error: Element could not be found
    at F:\Projects\webdriver.io-automate\webdriverio-cucumber\node_modules\@wdio\utils\build\shim.js:245:31
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0] Completed Scenario: TC-000 - Navigate to HomePage with Error
[0-0] Error: Element could not be found
[0-0]     at F:\Projects\webdriver.io-automate\webdriverio-cucumber\node_modules\@wdio\utils\build\shim.js:245:31
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0] Completed Feature: Register, Login and Purchase any Product
[0-0] FAILED in chrome - F:\Projects\webdriver.io-automate\webdriverio-cucumber\features\shopping-online\shop-online.feature

**Comment by christian-bromann** [comment]
> Error: Element could not be found

This clearly says the element could not be found. Please also check the wdio logs.

**Comment by saurabh-gadre** [comment]
I am still not satisfied with result. The element array is  present but one syntax works and other does not .

Below works fine : 
`console.log( "Menu Product Name index 0: ", await $$('[class="collapse navbar-collapse navbar-ex1-collapse"] [class="nav navbar-nav"] a[class="dropdown-toggle"]'[0].getText()); // This works  and prints   [0-0] Menu Product Name index 0:  Desktops`

And below does not work with the element reference for same element.

 ```
let prodName = await this.menuProducts[0].getText();  // This Fails 
    console.log('Menu Product Name index 0: ', prodName);    
```

Even using the await on the element at index at 0 it fails. Please note the element exists and I feel the framework has some short coming to support this.

**Comment by christian-bromann** [comment]
Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by saurabh-gadre** [comment]
Here is the most minimal example that can be reproduced.

[example.txt](https://github.com/webdriverio/webdriverio/files/8154511/example.txt)
[wdio.logs.txt](https://github.com/webdriverio/webdriverio/files/8154512/wdio.logs.txt)

**Comment by christian-bromann** [comment]
It seems you are fetching `menuProducts` before opening the page. WebdriverIO is not able to keep the state of an element reference. Therefor you have to fetch it when you want to interact with the element. We do __not__ recommend to query all elements within a page object in the PO constructor.

**Comment by saurabh-gadre** [comment]
Okay thanks for looking into the issue. I will try to figure it out if I can refactor the protractor code by trying to overcoming this issue.

**Comment by christian-bromann** [comment]
@saurabh-gadre please see how WebdriverIO [recommends](https://webdriver.io/docs/pageobjects) to write page objects. Also have a look into our [codemod](https://github.com/webdriverio/codemod) and [Protractor migration docs](https://github.com/webdriverio/codemod).
