### ISSUE TITLE
[💡 Feature]: Improve hooks by allowing to access browser object

### ISSUE THREAD

**Issue by Antonius-S** [webdriverio/webdriverio#8060]
### Is your feature request related to a problem?

Currently hooks are executed with `this` pointing to `global` thus having no access to the browser object they're executed from. Now I'm trying to make some browser config values accessible to the hook which is possible only by explicitly adding some property to a global variable like `process`.

### Describe the solution you'd like.

I suggest make hooks run with `this` pointing to browser - this won't break any current behavior

### Describe alternatives you've considered.

Explicitly add values to some global variable like `process`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
@Antonius-S can you please elaborate which hooks need access to the browser object? Currently all hooks have it besides `onPrepare` and `onComplete` which are run in a different process.

**Comment by Antonius-S** [comment]
@christian-bromann it's `afterCommand` that I'm working with now and it has `this` undefined. webdriverio@7.16.16

My case: I'm implementing some logic after any command and need custom configurable values which are included to an object passed as `option` when creating; I assign it to browser object as custom field but can't access it from the hook.

**Comment by christian-bromann** [comment]
Have you tried `browser.config.<your-property>` or `browser.options.<your-property>`?

**Comment by Antonius-S** [comment]
Being called from the hook:

```
>console.log(browser)
Uncaught ReferenceError: browser is not defined
```

**Comment by christian-bromann** [comment]
> Being called from the hook:

Do you use [standalone or testrunner](https://webdriver.io/docs/setuptypes)?

**Comment by christian-bromann** [comment]
Ok, now I fully understand. I think it is reasonable to use the scope here to refer to the actual browser object.

Any contributions that would implement this are highly appreciated. I am happy to support if question arise. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by Antonius-S** [comment]
Okay, I already found how to do it on a live source and will try to prepare PR

**Comment by Antonius-S** [comment]
I prepared the PR though I still can't perform full setup/install/test due to errors (unrecognized "cat" command on `cat ./.husky/postinstall.txt`); however the change seems pretty trivial. I tested this change on live code and it works as it should.
