### ISSUE TITLE
Override 'specs' and 'exclude' from CLI

### ISSUE THREAD

**Issue by georgecrawford** [webdriverio/webdriverio#807]
I'd like to be able to quickly override the list of included specs with the CLI tool (in a similar way to running `'wdio --baseUrl='...'`, rather than editing the wdio.conf.js file or adding `describe.only` or 'describe.skip` to the spec files.

**Comment by christian-bromann** [comment]
duplicate of #791

**Comment by georgecrawford** [comment]
Oops, sorry. And I even commented on it. :-(
