### ISSUE TITLE
Add namespacing to `addCommand()`

### ISSUE THREAD

**Issue by georgecrawford** [webdriverio/webdriverio#808]
I already have a load of custom test helper functionality added with `addCommand()`, and I plan to write many more. The ability to namespace these commands would be fantastic, otherwise the names get long and verbose in order to properly describe what they do.

So, ideally, I'd call `browser.user.login()`, rather than `browser.userLogin()`. Of course, I could introduce my own namespace hack with `browser.addCommand('user.login')`, but then I'd miss out on the clean API provided by the monad, and would have to call with `browser['user.login']()`.

A simple namespace parameter to `addCommand` would suffice. Or, since I'm adding a few helpers in each of a few helper files, it might even be nice to have a `browser.setCommandNamespace('user'); browser.addCommand('login', function() {});`.

Thoughts?

**Comment by christian-bromann** [comment]
Landed in v4. Thanks again!
