### ISSUE TITLE
[🐛 Bug]: Error: Cannot find module '../build'

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#8093]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v7.17.0

### Node.js Version

latest

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
any
```

### What happened?

Seems that something failed releasing WebdriverIO.

### How to reproduce the bug.

n/a

### Relevant log output

```typescript
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by alvstw** [comment]
@christian-bromann I am having the same issue after updating. Did you resolve it?
