### ISSUE TITLE
Perform async actions on test failures and command errors

### ISSUE THREAD

**Issue by georgecrawford** [webdriverio/webdriverio#810]
It's likely that this question has already been answered, so feel free to close if it's a duplicate.

Our test suite is likely to fail in two different ways - Mocha assertion failures, and Selenium command errors (such as a failure to find a required element), both of which may indicate either a badly-written test, or that the site under test isn't performing to specification.

We have wasted huge amounts of time in the past in determining whether the site or the test is to blame, and I'd really like to help our developers by providing as much useful information as possible. 

In both cases, we would like to perform some asynchronous tasks when these failures occur:
- save a screenshot to a file
- dump logs to a file: both the browser console log, and the Selenium command log
- dump the current state of the browser's DOM to a file

The file paths & name should be fully traceable, so the handling code needs access to the current Mocha test details and the current browser instance config and capabilities.

I know there have been a few tickets along these lines in the past, but with the reworked nature of v4.0, what's going to be the best way to do this? I'm happy to hack it in myself given a few pointers, but would love some advice to get started. It's important that these tasks are async and rely on running browser commands, so I think they need to be implemented at the framework level rather than in a reporter. Is that correct? 

I've seen https://github.com/webdriverio/webdriverio/issues/777, https://github.com/webdriverio/webdriverio/issues/269 and others, but I'd like to know the best way to do this in v4.0.

**Comment by georgecrawford** [comment]
I understand the handling of Mocha failures and Selenium errors will likely have to be in difference places in the codebase. Would a ticket in https://github.com/webdriverio/wdio-mocha-framework be more appropriate for the Mocha side?

**Comment by georgecrawford** [comment]
See also #819

**Comment by christian-bromann** [comment]
Nice proposal. Thanks!
Yeah this should be first implemented in our framework adapters and then propagated to this project. If something like an onError function is given in the config file the framework adapter should execute that function if an error actually happens.

**Comment by christian-bromann** [comment]
I believe we are at a point where we can close this. It's now implemented/tested in Mocha and Jasmine. If you want to check on test failures you can use `afterTest` and if you want to check on command failures you can use the `onError` which I have already in place [here](https://github.com/webdriverio/webdriverio/tree/onerror-hook). Feel free to reopen if you think it should stay open I am just cleaning issues.

**Comment by wirsingj** [comment]
Hey,  I too am looking to be able to capture screen shots when an assert fails.   I am using the wdio-cucumber-framework.       I have implemented a custom reporter and can pick up on the failed assertions error:

```
this.on('test:fail', function() {
       console.log(`so sad`)
       throw 
      // return global.browser.saveScreenshot('./snapshot.png');
   });
```

But am not able to access the browser object to take a screen shot.

Has anyone found a good solution for this w/ cucumber?

**Comment by christian-bromann** [comment]
You should use hooks to take screenshots if a test fails.
