### ISSUE TITLE
[🐛 Bug]: Element not found doesnt show proper stack trace

### ISSUE THREAD

**Issue by praveendvd** [webdriverio/webdriverio#8108]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.17.4

### Node.js Version

v16.5.0

### Mode

WDIO Testrunner

### What happened?

```
[chrome 99.0.4844.51 windows #0-0]
[chrome 99.0.4844.51 windows #0-0] 1 failing (11.5s)
[chrome 99.0.4844.51 windows #0-0]
[chrome 99.0.4844.51 windows #0-0] 1) My Login application should login with valid credentials
[chrome 99.0.4844.51 windows #0-0] Error: Can't call setValue on element with selector "#ddd" because element wasn't found
[chrome 99.0.4844.51 windows #0-0] Error: Can't call setValue on element with selector "#ddd" because element wasn't found
```

in this typescript project it Doesnt throw any stack trace to show where the error was thrown

### What is your expected behavior?

Should show line in spec file and pageobject where the error was orginated in 

### How to reproduce the bug.

[package.zip](https://github.com/webdriverio/webdriverio/files/8239283/package.zip)

### Relevant log output

```typescript
[chrome 99.0.4844.51 windows #0-0]
[chrome 99.0.4844.51 windows #0-0] 1 failing (11.5s)
[chrome 99.0.4844.51 windows #0-0]
[chrome 99.0.4844.51 windows #0-0] 1) My Login application should login with valid credentials
[chrome 99.0.4844.51 windows #0-0] Error: Can't call setValue on element with selector "#ddd" because element wasn't found
[chrome 99.0.4844.51 windows #0-0] Error: Can't call setValue on element with selector "#ddd" because element wasn't found
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@praveendvd I can't reproduce this, even without any reporters I get:

```js
 npx wdio run ./test/wdio.conf.ts

Execution of 1 workers started at 2022-03-14T08:41:14.382Z

[0-0] RUNNING in chrome - /test/specs/example.e2e.ts
[0-0] Error in "My Login application.should login with valid credentials"
Error: Can't call setValue on element with selector "ddd" because element wasn't found
    at implicitWait (/private/tmp/8108/node_modules/webdriverio/build/utils/implicitWait.js:34:19)
    at async Element.elementErrorHandlerCallbackFn (/private/tmp/8108/node_modules/webdriverio/build/middlewares.js:20:29)
    at async Element.wrapCommandFn (/private/tmp/8108/node_modules/@wdio/utils/build/shim.js:137:29)
[0-0] FAILED in chrome - /test/specs/example.e2e.ts

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:13
```

How do I need to modify the starter package to reproduce this?

**Comment by praveendvd** [comment]
I am using windows 10 and it happens as it is , I will cross check today @christian-bromann  u know where is this error getting handled so that I can look into that also 🎉

**Comment by christian-bromann** [comment]
Check our framework [wrapper functions](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-utils/src/test-framework/testFnWrapper.ts#L77-L81). WebdriverIO doesn't modify the stack traces.

**Comment by praveendvd** [comment]
@christian-bromann  i ran in windows and mac , i am gettign same behavior .

**Comment by praveendvd** [comment]
<img width="1328" alt="image" src="https://user-images.githubusercontent.com/45095911/159130609-c6779c4e-31c4-448e-85fd-14f96fd507a5.png">

**Comment by WillBrock** [comment]
On Ubuntu it is showing the stacktrace for me. This is with a fresh install of latest. I noticed on Christian's example it only shows the stacktrace for wdio files but not the failure line on the example.e2e.ts file which is odd.

```js
 "spec" Reporter:
------------------------------------------------------------------
[chrome 99.0.4844.74 linux #0-0] Running: chrome (v99.0.4844.74) on linux
[chrome 99.0.4844.74 linux #0-0] Session ID: ce71f3f338878872918f3dcfada89587
[chrome 99.0.4844.74 linux #0-0]
[chrome 99.0.4844.74 linux #0-0] » /test/specs/example.e2e.js
[chrome 99.0.4844.74 linux #0-0] My Login application
[chrome 99.0.4844.74 linux #0-0]    ✖ should login with valid credentials
[chrome 99.0.4844.74 linux #0-0]
[chrome 99.0.4844.74 linux #0-0] 1 failing (10.9s)
[chrome 99.0.4844.74 linux #0-0]
[chrome 99.0.4844.74 linux #0-0] 1) My Login application should login with valid credentials
[chrome 99.0.4844.74 linux #0-0] Can't call setValue on element with selector ".fffff" because element wasn't found
[chrome 99.0.4844.74 linux #0-0] Error: Can't call setValue on element with selector ".fffff" because element wasn't found
[chrome 99.0.4844.74 linux #0-0]     at implicitWait (/home/will/dev/wdio-stack/node_modules/webdriverio/build/utils/implicitWait.js:34:19)
[chrome 99.0.4844.74 linux #0-0]     at async Element.elementErrorHandlerCallbackFn (/home/will/dev/wdio-stack/node_modules/webdriverio/build/middlewares.js:20:29)
[chrome 99.0.4844.74 linux #0-0]     at async Element.wrapCommandFn (/home/will/dev/wdio-stack/node_modules/@wdio/utils/build/shim.js:137:29)
[chrome 99.0.4844.74 linux #0-0]     at async Context.<anonymous> (/home/will/dev/wdio-stack/test/specs/example.e2e.js:8:9)


Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:12 
```

**Comment by praveendvd** [comment]
@WillBrock  fore no stacktrace at all for mac n windows

**Comment by WillBrock** [comment]
Interestingly in TypeScript it's not showing the stack line for the example.e2e.ts file
 
```js
 "spec" Reporter:
------------------------------------------------------------------
[chrome 99.0.4844.74 linux #0-0] Running: chrome (v99.0.4844.74) on linux
[chrome 99.0.4844.74 linux #0-0] Session ID: c13a202bfb63b12b4a8edd1e6f17926f
[chrome 99.0.4844.74 linux #0-0]
[chrome 99.0.4844.74 linux #0-0] » /test/specs/example.e2e.ts
[chrome 99.0.4844.74 linux #0-0] My Login application
[chrome 99.0.4844.74 linux #0-0]    ✖ should login with valid credentials
[chrome 99.0.4844.74 linux #0-0]
[chrome 99.0.4844.74 linux #0-0] 1 failing (11s)
[chrome 99.0.4844.74 linux #0-0]
[chrome 99.0.4844.74 linux #0-0] 1) My Login application should login with valid credentials
[chrome 99.0.4844.74 linux #0-0] Can't call setValue on element with selector ".adfsadfs" because element wasn't found
[chrome 99.0.4844.74 linux #0-0] Error: Can't call setValue on element with selector ".adfsadfs" because element wasn't found
[chrome 99.0.4844.74 linux #0-0]     at implicitWait (/home/will/dev/wdio-st/node_modules/webdriverio/build/utils/implicitWait.js:34:19)
[chrome 99.0.4844.74 linux #0-0]     at async Element.elementErrorHandlerCallbackFn (/home/will/dev/wdio-st/node_modules/webdriverio/build/middlewares.js:20:29)
[chrome 99.0.4844.74 linux #0-0]     at async Element.wrapCommandFn (/home/will/dev/wdio-st/node_modules/@wdio/utils/build/shim.js:137:29)

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:13 
```

**Comment by praveendvd** [comment]
@christian-bromann n @WillBrock  ya I am using typescript , n wdio built in ts-node for execution . ( Just run , npm run wdio)

**Comment by WillBrock** [comment]
@praveendvd I discovered #8129. I don't think that would be why no stacktraces show for you but maybe it is.

**Comment by praveendvd** [comment]
Will give it a try

**Comment by praveendvd** [comment]
@WillBrock 

![image](https://user-images.githubusercontent.com/45095911/159183643-29ad4f0d-99c7-4c95-8b89-60a6776d305d.png)

I get this error when i change the target to es2019 ,

**Comment by praveendvd** [comment]
![image](https://user-images.githubusercontent.com/45095911/159183747-ca23d78c-fb46-4ba0-a4bd-302e6e0dda95.png)


@WillBrock  i get this error when target is es2019

**Comment by praveendvd** [comment]
@WillBrock  but it does fixes the issue (the project runs fine )

**Comment by WillBrock** [comment]
This is beyond my TypeScript knowledge but WebdriverIO is defined in wdio-types/index.d.ts and webdriverio/async.d.ts. It looks like when `target : "ES5"` it uses what is defined in types/index.d.ts but `target : "es2018"`is using WebdriverIO in async.d.ts.

**Comment by christian-bromann** [comment]
> i get this error when target is es2019

See #8166 .. we should move away from namespaces towards type imports.

Is there any chance we can reproduce this for others? Or is this a Windows specific issue?

**Comment by praveendvd** [comment]
@christian-bromann Will try that christian

**Comment by christian-bromann** [comment]
@praveendvd how should we proceed with this? Did you have some time to work on a reproducible example?

**Comment by praveendvd** [comment]
@christian-bromann  its working now 🥳
