### ISSUE TITLE
[🐛 Bug]: Running test with --suite filter is ignoring the filter when ran from package.json file

### ISSUE THREAD

**Issue by VKnightUT** [webdriverio/webdriverio#8110]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.17.4

### Node.js Version

16.14.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [{
        maxInstances: 5,
        browserName: 'chrome',
        acceptInsecureCerts: true
    }],
```

### What happened?

When running a test script from the package.json file and adding the --suite filter it is ignoring the filter. Also happening to the --spec filter. 

### What is your expected behavior?

The --suite filter should correctly run only the tests in the suite.

### How to reproduce the bug.

Follow steps 1-4 or download this repo, run npm install, and skip to step 5: https://github.com/VKnightUT/wdio-basic
1. Create a basic new repo by running "npx wdio" and select minimal options. Skip things like babel and other options so it is the most basic repo possible but have it create test files for you. 
2. Create a copy of the sample test.
3. Create two suites in the wdio.conf.js file as shown:
    suites: {
        example1: ['./test/specs/example.e2e.js'],    
        example2: ['./test/specs/example2.e2e.js'],     
    },
4. Create two test scripts in the package.json file as shown:
    "scripts": {
        "wdio": "wdio run wdio.conf.js",
        "wdio2": "./node_modules/.bin/wdio wdio.conf.js"
    }
5. Try running either script with the command "npm run wdio" or "npm run wdio2" and add the filter --suite at the end. Notice it will run both test files.
6. Try running those same two scripts directly from the command line. Notice the wdio script run from the command line will NOT filter the tests but the wdio2 script will correctly filter them.

Note: This affects the --spec filter as well which is similar to the bug reported here: https://github.com/webdriverio/webdriverio/issues/7735

This happens on older versions of node and webdriverio v7 as well. 

### Relevant log output

```typescript
No relevant log data to help figure this out.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by WillBrock** [comment]
@VKnightUT You'll need to add a `--` in between the node command and your arguments.

```npm run wdio -- --spec foo```

**Comment by christian-bromann** [comment]
> The extra double dashes works but is NOT intuitive.

Can you help us how the docs should be updated?

**Comment by mr-possible** [comment]
It does not work at all in my case, even with double dashes and what not!

**Comment by christian-bromann** [comment]
> It does not work at all in my case, even with double dashes and what not!

Can you elaborate on this?

**Comment by mr-possible** [comment]
@christian-bromann I seem to have noticed this:

The issue occurs with use of `npm` and not `npx`.
So, for example:

The command `npm run wdio --suite sanity` ignores the `sanity` flag.
The command `npx wdio run ./wdio.conf.ts --suite sanity` works just fine.

My `package.json` file:
```
{
  "name": "wdio_web_test_framework",
  "devDependencies": {
    "@wdio/allure-reporter": "^8.32.2",
    "@wdio/local-runner": "^8.32.3",
    "@wdio/mocha-framework": "^8.32.3",
    "@wdio/spec-reporter": "^8.32.2",
    "ts-node": "^10.9.2"
  },
  "scripts": {
    "sanity": "npx wdio run ./wdio.conf.ts --suite sanity",
    "uat": "npx wdio run ./wdio.conf.ts --suite uat",
    "smoke": "npx wdio run ./wdio.conf.ts --suite smoke",
    "regression": "npx wdio run ./wdio.conf.ts --suite regression",
    "allure": "allure generate allure-results --clean && allure open"
  }
}
```

**Comment by christian-bromann** [comment]
This is the expected behavior. If you call `npm run wdio --suite sanity` the `suite` parameter is applied to the NPM command which doesn't know about it and ignores it. To apply the flag to `wdio` you have to separate it with a `--`, e.g. `npm run wdio -- --suite sanity`
