### ISSUE TITLE
Having trouble with .element()

### ISSUE THREAD

**Issue by whasting** [webdriverio/webdriverio#812]
Hello! I'm new to automation and I'm having trouble with the `.click()` method. I'm able to find elements via the `.elements` method, but when I use `.element`, I'll get an error such as:

    Error: no such element: Unable to locate element: {"method":"id","selector":"email"}

Just wondering what I'm doing wrong! Here's the code that's failing:      

    this.When(/^When I click the login button$/, function () {
      client.waitForExist('body');
      client.click('[data-action=loginTest]');
    });

And here's the element I need to find:

    <button data-action="loginTest" type="submit" class="Button--Md--Primary Button--Login">login</button>

**Comment by christian-bromann** [comment]
That error gets thrown somewhere else. It can't find `#email`

**Comment by whasting** [comment]
Was having trouble with this yesterday, but it appears to have resolved itself after having a go at it today! Thank you for your time.
