### ISSUE TITLE
[🐛 Bug]: `RangeError: Maximum call stack size exceeded` error with async jasmine tests

### ISSUE THREAD

**Issue by BenoitZugmeyer** [webdriverio/webdriverio#8126]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.18.0

### Node.js Version

17.6.0

### Mode

WDIO Testrunner

### What happened?

When running asynchronous jasmine tests, if a test timeout, all remaining tests are failing with `RangeError: Maximum call stack size exceeded` with no call stack.

After investigation, the culprit seems to be the [`expectAsyncShim`](https://github.com/webdriverio/webdriverio/blob/c5be0a7fd314fca7368656717ed3aa152ee1cd25/packages/wdio-utils/src/shim.ts#L52) function calling itself indefinitely.

### What is your expected behavior?

Remaining tests are correctly run.

### How to reproduce the bug.

```
git clone https://gist.github.com/5d2ce35e3291993d7dbaf31961c15069 test-wdio
cd test-wdio
npm i
npm run wdio
```

### Relevant log output

```typescript
[0-0] RUNNING in chrome - /test.js
...
[0-0] Error in "test timeout"
Error: Timeout - Async function did not complete within 5000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
    at <Jasmine>
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[0-0] Error in "test foo"
RangeError: Maximum call stack size exceeded
[0-0] Error in "test bar"
RangeError: Maximum call stack size exceeded
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by praveendvd** [comment]
@BenoitZugmeyer  Could we close this issue ? if the fix is merged

**Comment by BenoitZugmeyer** [comment]
I'm not aware of a fix. But sure, close the issue when it's fixed.

**Comment by praveendvd** [comment]
Sorry ignore the comments , I just saw the merge thought it was in wdio repo .

**Comment by christian-bromann** [comment]
@BenoitZugmeyer any chance you can provide a minimal reproducible example?

**Comment by BenoitZugmeyer** [comment]
I have, see "How to reproduce the bug"

**Comment by christian-bromann** [comment]
Ah, cheers! I must have missed that.
Thanks for reporting!

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by christian-bromann** [comment]
fixed in https://github.com/webdriverio/webdriverio/pull/8175

**Comment by erwinheitzman** [comment]
Nice going Christian and thanks for reporting @BenoitZugmeyer 👍

**Comment by BenoitZugmeyer** [comment]
Thank you very much @christian-bromann !
