### ISSUE TITLE
Incorrect `this` context in Mocha before/after/beforeEach/afterEach hooks

### ISSUE THREAD

**Issue by georgecrawford** [webdriverio/webdriverio#814]
It should be possible to access Mocha properties such as `this.currentTest` within the test hooks like `beforeEach`, `afterEach`, etc. See https://github.com/mochajs/mocha/issues/797#issuecomment-16018400, for example? Currently, `this` in `afterEach` is `undefined`.

@christian-bromann said:
> this sounds like a bug then .. it should be fixed within https://github.com/webdriverio/wdio-sync/blob/master/index.js#L43-L59

I'd love to submit a PR, but I"m currently on a fixed v4.0 commit as I can't yet get HEAD to work.

**Comment by christian-bromann** [comment]
haha too late, I've got a contribution for that just yesterday #813 , will update npm today or tomorrow

**Comment by georgecrawford** [comment]
:+1:
