### ISSUE TITLE
[🐛 Bug]: Malformed type for "implicit" parameter of command setTimeouts

### ISSUE THREAD

**Issue by unlok** [webdriverio/webdriverio#8173]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### What happened?

In non-w3c mode in safari13 got such error:
```
Malformed type for "implicit" parameter of command setTimeouts
```
When trying to call:
```js
browser.setTimeout({ 'script': 5000 })
```

So, this code handling [there](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriver/src/command.ts#L53) and if it's [JSONWP](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-protocols/protocols/jsonwp.json#L74)  no problem:
```js
[
  {"name": "type", "type": "string", "description": "The type of operation to set the timeout for. Valid values are: \"script\" for script timeouts, \"implicit\" for modifying the implicit wait timeout and \"page load\" for setting a page load timeout.", "required": true },
  {"name": "ms", "type": "number", "description": "The amount of time, in milliseconds, that time-limited commands are permitted to run", "required": true }
]
```

Params looks predictable. But when we are using [webdriver](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-protocols/protocols/webdriver.json#L57) -  params does not look like positional arguments but they should be.

For non-w3c we call `setTimeout('script', 5000)` [there](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/browser/setTimeout.ts#L62
).

On [this](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriver/src/command.ts#L55) step we have such structure:
```js
[
  {"name":"implicit","type":"number","description":"integer in ms for session implicit wait timeout","required":false}, 
  {"name":"pageLoad","type":"number","description":"integer in ms for session page load timeout","required":false}, 
  {"name":"script","type":"number","description":"integer in ms for session script timeout","required":false}
]
```

But `args` for it `['script', 5000]`. First param `implicit` expects type number but got string (`script`) and code fails there.

### How to reproduce the bug.

no need

### Relevant log output

```typescript
no need
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by unlok** [comment]
@christian-bromann, sorry, did not get. I am calling it like this:
```js
browser.setTimeout({ 'script': 5000 }); // looks like valid call
```

**Comment by christian-bromann** [comment]
The call

```ts
await browser.setTimeout({ 'script': 5000 })
```
should work.

**Comment by unlok** [comment]
@christian-bromann, I described why it is not now working above.

1. I call from my code `await browser.setTimeout({ 'script': 5000 })`
2. Under the hood webdriverio call this methdod - https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/browser/setTimeout.ts#L62
```
setTimeouts('script', script)
```
3. Then on this line - https://github.com/webdriverio/webdriverio/blob/main/packages/webdriver/src/command.ts#L55 I added log and see such structure in variable `console.log(commandParam)`:
```
{
        "name": "implicit",
        "type": "number",
        "description": "integer in ms for session implicit wait timeout",
        "required": false
}
```
3. `console.log(arg)` and I seee `script`.
4. Then checks that `script` is type of number and fails.

So in variable `commandParams` I got structure from this line https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-protocols/protocols/webdriver.json#L57 and it logically fails.

**Comment by christian-bromann** [comment]
Unfortunately I don't have environments that support JSONWireProtocols at this point. So, any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!
