### ISSUE TITLE
engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by ravi005e** [webdriverio/webdriverio#8178]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.19.3

### Node.js Version

16.14.0

### Mode

Standalone Mode

### What happened?

want able to run yarn install

error @wdio/sync@7.19.3: The engine "node" is incompatible with this module. Expected version ">=12.0.0 <16". Got "16.14.0"

### What is your expected behavior?

expect to complete yarn install

clone repo https://github.com/WarleyGabriel/demo-webdriverio-mocha

run yarn install with latest node

### How to reproduce the bug.

yarn install

thats all

### Relevant log output

```typescript
[2/5] 🔍  Resolving packages...
warning @wdio/allure-reporter > allure-js-commons > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[3/5] 🚚  Fetching packages...
error @wdio/sync@7.19.3: The engine "node" is incompatible with this module. Expected version ">=12.0.0 <16". Got "16.14.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by wswebcreation** [comment]
This is due to the fact that sync mode is not supported anymore in NodeJS 16, please see https://webdriver.io/docs/sync-vs-async

**Comment by ravi005e** [comment]
thanks
