### ISSUE TITLE
[🐛 Bug]: <title>JSON object from browser console is lost in getLogs

### ISSUE THREAD

**Issue by eileenzhuang2022** [webdriverio/webdriverio#8179]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

V6 or V7

### Node.js Version

12 or 14

### Mode

WDIO Testrunner

### What happened?

An JS application in chrome (v99) outputs a JSON object to browser console as debug info. I called browser.getLogs('browser') to capture the JSON data. It returned a few logging entries. For the one whose mesage supposed to contain the JSON data, it shows Object as a substring. It is like "JS application.js line 123, Object" The JSON object got lost somewhere 

### What is your expected behavior?

The message returned from getLogs should contain JSON object data dumped by a JS app, like
"JSapplication.js line 123, {nodea:\"valuea\",nodeb:\"valueb\"}"

### How to reproduce the bug.

Have a java script which output a JSON object to console
Call browser.getLogs('browser')

### Relevant log output

```typescript
I set loggingPrefs correctly:
browser:'ALL'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@eileenzhuang2022 thanks for reporting.

Unfortunately there is nothing WebdriverIO can do about it and you might want to report this in the Chromedriver project. One possible workaround is to [receive logs](https://pptr.dev/#?product=Puppeteer&version=v13.5.2&show=api-event-console) through [Puppeteer](https://pptr.dev/) calling the [`getPuppeteer`](https://webdriver.io/docs/api/browser/getPuppeteer/) command.

**Comment by eileenzhuang2022** [comment]
Thank you very much!
