### ISSUE TITLE
[🐛 Bug]: WDIO CLI --spec option doesn't detect files or files within directory containing `[]` brackets

### ISSUE THREAD

**Issue by dipushrestha** [webdriverio/webdriverio#8185]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  browserName: "chrome",
  browserVersion: "100",
  platform: "linux"
}
```

### What happened?

WDIO CLI options --spec doesn't detect files and directories with `[]` brackets.
![image](https://user-images.githubusercontent.com/36785868/161777143-551c0cbb-53af-4154-aa84-025a41d55dd8.png)

### What is your expected behavior?

It should detect spec files with brackets.

### How to reproduce the bug.

Run WDIO CLI with --spec args with having `[]` paths.

```sh
wdio run wdio.conf.ts --spec specs/[test].ts
```

### Relevant log output
![image](https://user-images.githubusercontent.com/36785868/161777143-551c0cbb-53af-4154-aa84-025a41d55dd8.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Why do you use `[...]` as directory name?

**Comment by dipushrestha** [comment]
We're using the next.js page param convention.

**Comment by christian-bromann** [comment]
Thanks for reporting!

WebdriverIO is using [`glob`](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-config/src/lib/FileSystemPathService.ts) to find all testing files. Not sure if it is not able to deal with `[` and `]` but that's where I would look and check first.

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by perillai** [comment]
Hi @christian-bromann , I tried doing a fix on this issue. Actually, when we use 'wdio' to run, it looks for wdio-cli installed globally. wdio-cli installed in the project is not getting recognised. So, my fix will work if the user installs latest wdio-cli using '-g' apart from updating wdio-cli in the node_modules of the project. Or, is there any workaround to make wdio work without installing it globally?

**Comment by perillai** [comment]
> > Actually, when we use 'wdio' to run, it looks for wdio-cli installed globally
> 
> I recommend to install `@wdio/cli` locally per project basis. Otherwise you might get side effects when updating versions.

This is the issue that I got: [wdio is not recognised as ...](https://gitter.im/webdriverio/webdriverio?at=5d77be0dc5939027204833ff). And in the same chat, it had been suggested to add 'wdio' to environment variables. Is that the workaround?

**Comment by christian-bromann** [comment]
@perillai this is a complete different issue as described by the author, so let's don't mix different problems in the issue otherwise it gets to complicated following the conversations.

**Comment by christian-bromann** [comment]
@vmwhereqa 👁️

**Comment by vmwhereqa** [comment]
@christian-bromann : here is the  [fix](https://github.com/webdriverio/webdriverio/pull/9004)

**Comment by christian-bromann** [comment]
Thanks @vmwhereqa , let's continue convo in #9004
