### ISSUE TITLE
[🐛 Bug]: Definitions for eslint-plugin-wdio rules were not found

### ISSUE THREAD

**Issue by alexstep-dev** [webdriverio/webdriverio#8188]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.19.3

### Node.js Version

16.14.2

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  browserName: 'chrome',
  browserVersion: '100.0.4896.60',
  platformName: 'Windows 11'
}
```

### What happened?

Hello!
I faced a problem with [eslint-plugin-wdio](https://github.com/webdriverio/webdriverio/tree/main/packages/eslint-plugin-wdio).

After I installed the plugin and configured ESlint I received the error about its rules:

- **wdio/no-pause**
- **wdio/no-debug**
- **wdio/await-expect**

If I set any other value except "off" or "0" for those rules of even if I haven't described the rules at all, each file (even ESlint config file) in my project shows me this error:

![image](https://user-images.githubusercontent.com/16436849/161907501-1fff0f6e-dc70-4a48-b9f2-083c2242c7cb.png)

As you can see, adding "off" of "0" as a value disables any mentioned rule.
If I disable all of those rules error disappears.

### What is your expected behavior?

I expect the rules should work properly and must be configurable.

### How to reproduce the bug.

Install and cofigure the latest version of [eslint-plugin-wdio](https://www.npmjs.com/package/eslint-plugin-wdio) from NPM.
Here is my [project and its config](https://github.com/alexstep-dev/aqa_wdio_learn/tree/eslint-wdio-plugin-issue) in relevant branch.

### Relevant log output

There's no output log because of plugin's error.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
You are missing a piece in the plugins section:

```patch
- plugins: ["mocha"],
+ plugins: ["mocha", "wdio"],
```
