### ISSUE TITLE
[🐛 Bug]: Misleading error behavior if path to tsconfig is invalid

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#8192]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
any
```

### What happened?

If the `tsNodeOpts.project` path is incorrect the testrunner fails likely due to compiling issues (e.g. `Cannot use import statement outside a module`). It can be frustrating if one would tweak the tsconfig thousand times until they would figure out that the path was incorrect.

### What is your expected behavior?

Let's throw a proper error message that no `tsconfig.json` was found under given path.

### How to reproduce the bug.

n/a

### Relevant log output

```typescript
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by harsha509** [comment]
Closing this as issue is fixed with commit https://github.com/webdriverio/webdriverio/commit/59b965474e32d9e8544d7b4bd83d969b842fb894 !
