### ISSUE TITLE
[📖 Docs]: Markdown Reporter example not working

### ISSUE THREAD

**Issue by DrNio13** [webdriverio/webdriverio#8198]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Clearer documentation with correct code snippet. Developers would need to only specify the path for the generated markdown files, by following the example.

### Description of the improvement / report

Following the Markdown Reporter [installation guide](https://webdriver.io/docs/wdio-markdown-reporter/#installation) no markdown files are generated on the specified directory.

The part `reporter: : [` from the example, is not correct or at least it does not work outside or inside the `services` configuration object.

```
// wdio.conf.js
export.config = {
  reporter: : [
    [markdownReporter, {
      outputDir: './some-path-here',
    }],
  ],
};
```

I tried placing the reporter outside the `services` configuration object like this:

```
{
...
reporter: [markdownReporter, {
     outputDir: './reports',
 }],
...
}
```

And inside the `services` config and it did not work

```
// Test runner services
// Services take over a specific job you don't want to take care of. They enhance
// your test setup with almost no effort. Unlike plugins, they don't add new
// commands. Instead, they hook themselves up into the test process.
{
...
services: [
    ['chromedriver', {
        args: []
    }],
    ['reporter', [markdownReporter, {
        outputDir: './reports',
    }]]
],
...
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
@DrNio13 can you try:

```ts
reporters: ['spec',
    ['markdown', {
        outputDir: './my-folder-path',
    }]
],
```

**Comment by DrNio13** [comment]
@christian-bromann 

it does not work better than my last snippet in the comment.

`[0-0] 2022-04-11T05:53:39.359Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2022-04-11T05:53:39.744Z ERROR @wdio/local-runner: Failed launching test session: TypeError: ReporterClass is not a constructor
[0-0]     at BaseReporter.initReporter (/app/shared/Unit.UI/node_modules/@wdio/runner/build/reporter.js:157:20)
[0-0]     at Array.map (<anonymous>)
[0-0]     at new BaseReporter (/app/shared/Unit.UI/node_modules/@wdio/runner/build/reporter.js:22:50)
[0-0]     at Runner.run (/app/shared/Unit.UI/node_modules/@wdio/runner/build/index.js:78:26)
[0-0]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[0-0] FAILED`

**Comment by christian-bromann** [comment]
> Is it expected that only failed tests will be in the markdown file?

Probably not. The WebdriverIO team doesn't manage this plugin. We recommend to raise an issue in the [original project](https://github.com/carmenmitru/wdio-markdown-reporter). All we can do is to remove it from our docs and install wizard.
