### ISSUE TITLE
Commands using waitUntil should check failure cause

### ISSUE THREAD

**Issue by georgecrawford** [webdriverio/webdriverio#820]
`waitUntil` will throw an error if the wait times-out (`Promise never resolved with an truthy value`), but also if the command encounters an error (`Promise was fulfilled but got rejected with the following reason: ...`). Commands which use `waitUntil`, such as `waitForVisible`, must check the thrown error to see which reason was encountered. For a time-out, a message like `element (#splash) still  visible after 40000ms` is perfect, but if there was a Selenium error with the looping command, it's vital to print that instead, eg. `waitForVisible failed with error: stale element reference: element is not attached to the page document`.

**Comment by christian-bromann** [comment]
Nice proposal! Feel free to open a PR :wink:

**Comment by christian-bromann** [comment]
Merged. Thanks again!
