### ISSUE TITLE
Firefox not opening after update

### ISSUE THREAD

**Issue by anupamck** [webdriverio/webdriverio#8207]
On updating wdio version to 6.12.1 from 6.0.13, I am unable to execute tests on Firefox locally. Wdio is not able to even open the browser window - it merely flickers occasionaly. 

When I downgrade and run "npm i", tests on Firefox execute once again. 

Firefox version - 98.0.2

Note: The same problem does not happen on Chrome (version 100.0.4896.75)

[Debug logs - Firefox problem.txt](https://github.com/webdriverio/webdriverio/files/8473768/Debug.logs.-.Firefox.problem.txt)

**Comment by luckyyyyy** [comment]
> 该日志并没有说明问题的原因。一个最小的可重现示例将有助于调查。你能提供这个吗？



> This logs don't say much about the reasoning of the problem. A minimal reproducible example would help to investigate. Can you please provide this?

$ ./geckodriver --port 4444 --log debug
1649802953026	geckodriver	INFO	Listening on 127.0.0.1:4444
1649802964485	webdriver::server	DEBUG	-> POST /session {"capabilities":{"alwaysMatch":{"browserName":"firefox","moz:firefoxOptions":{"args":["-remote-debugging-port","52822"]}},"firstMatch":[{}]},"desiredCapabilities":{"browserName":"firefox","moz:firefoxOptions":{"args":["-remote-debugging-port","52822"]}}}
1649802964486	webdriver::server	DEBUG	<- 400 Bad Request {"value":{"error":"invalid argument","message":"Argument --remote-debugging-port can't be set via capabilities","stacktrace":""}}
1649802964491	webdriver::server	DEBUG	-> POST /session {"capabilities":{"alwaysMatch":{"browserName":"firefox","moz:firefoxOptions":{"args":["-remote-debugging-port","52822"]}},"firstMatch":[{}]},"desiredCapabilities":{"browserName":"firefox","moz:firefoxOptions":{"args":["-remote-debugging-port","52822"]}}}
1649802964492	webdriver::server	DEBUG	<- 400 Bad Request {"value":{"error":"invalid argument","message":"Argument --remote-debugging-port can't be set via capabilities","stacktrace":""}}
1649802964493	webdriver::server	DEBUG	-> POST /session {"capabilities":{"alwaysMatch":{"browserName":"firefox","moz:firefoxOptions":{"args":["-remote-debugging-port","52822"]}},"firstMatch":[{}]},"desiredCapabilities":{"browserName":"firefox","moz:firefoxOptions":{"args":["-remote-debugging-port","52822"]}}}
1649802964493	webdriver::server	DEBUG	<- 400 Bad Request {"value":{"error":"invalid argument","message":"Argument --remote-debugging-port can't be set via capabilities","stacktrace":""}}
1649802964494	webdriver::server	DEBUG	-> POST /session {"capabilities":{"alwaysMatch":{"browserName":"firefox","moz:firefoxOptions":{"args":["-remote-debugging-port","52822"]}},"firstMatch":[{}]},"desiredCapabilities":{"browserName":"firefox","moz:firefoxOptions":{"args":["-remote-debugging-port","52822"]}}}
1649802964494	webdriver::server	DEBUG	<- 400 Bad Request {"value":{"error":"invalid argument","message":"Argument --remote-debugging-port can't be set via capabilities","stacktrace":""}}

**Comment by christian-bromann** [comment]
@luckyyyyy thanks for providing these logs, they indeed indicate something is not correct.

**Comment by Pitros** [comment]
This issue is related to firefox driver update v0.31 which happened 2 days ago. Had the same issue, for now specified manually previous version `geckodriver-v0.30.0` and it seems to be working fine.

**Comment by christian-bromann** [comment]
Talked with one of the Geckodriver devs about it who said:
> ah yes that is expected. you do not want to do that. use the webSocketUrl capability set to true

**Comment by mrister** [comment]
Having the same issue.

**Comment by christian-bromann** [comment]
fixed in #8211
