### ISSUE TITLE
[💡 Feature]: Screenshot issue

### ISSUE THREAD

**Issue by luckyyyyy** [webdriverio/webdriverio#8209]
### Is your feature request related to a problem?

no

### Describe the solution you'd like.

I don't want to save the screenshot, I just want to get the buffer of the screenshot and provide it to my application for processing.

I looked at the source code and it is easy to modify, would you consider adding this API?

and uploadFile savePDF saveRecordingScreen ...

thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Please use [`takescreenshot`](https://webdriver.io/docs/api/webdriver/#takescreenshot).

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
