### ISSUE TITLE
Allow multiple reporters

### ISSUE THREAD

**Issue by wgcrouch** [webdriverio/webdriverio#821]
Karma allows multiple reporters when running tests, this could be useful. 

eg using spec reporter and xunit together, so you can see the progress as its running, and still have the junit.xml output

**Comment by christian-bromann** [comment]
Planned for v4

**Comment by Robinfr** [comment]
I would also love this. +1

**Comment by just-boris** [comment]
+1, it makes sense when you are using a reporter which doesn't write to console, e.g. `xUnit` reporter.
It would be nice to combine it with `spec`

**Comment by christian-bromann** [comment]
This will be possible with v4. We hope to publish the new version with the beginning of the next year and we got already couple reporter available:
https://github.com/webdriverio/wdio-allure-reporter
https://github.com/webdriverio/wdio-junit-reporter
https://github.com/webdriverio/wdio-dot-reporter
