### ISSUE TITLE
[💡 Feature]: Select tests with --exclude command should handle free text search just like --spec command does

### ISSUE THREAD

**Issue by perhenrikandersson** [webdriverio/webdriverio#8210]
### Is your feature request related to a problem?

Having to write the full path(s) when excluding test file(s) is a bit cumbersome. Would be much easier if I could just write a word that the excluded test file(s) file name should contain, just as when specifying what specs to use.

### Describe the solution you'd like.

Same as we already have with the --spec command where you can either specify the full path or just a single word.
https://webdriver.io/docs/organizingsuites#run-selected-tests
![image](https://user-images.githubusercontent.com/3188255/163112898-ba6b628d-1799-4b3e-bba2-8e603b6a999a.png)

E.g. the following command should exclude all tests with a file name containing the word "dialog"
--exclude dialog

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Thanks for reporting!

I think being compliant with the `--spec` param makes totally sense here.

Any contributions that implements this are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by fgkolf** [comment]
Hello, I would like to work on this one!

**Comment by christian-bromann** [comment]
Awesome @fgkolf , let me know if you have any questions.

**Comment by fgkolf** [comment]
If i get this right this is already [implemented](https://github.com/webdriverio/webdriverio/blob/01c124d84e3ab97306d93c8ed6f1388fffb75fcc/packages/wdio-cli/src/commands/run.ts#L81-L84) and [documented](https://webdriver.io/docs/organizingsuites/#exclude-selected-tests). @christian-bromann any insights on this?

**Comment by christian-bromann** [comment]
@fgkolf I think what the issue author asks here is the possibility to add a `--exclude foobar` parameter which would exclude a `foobar.e2e.js` file. As far as I know this is currently not possible.

**Comment by tech-dm-klymenko** [comment]
Hello, 
As far as I see this task is not in progress. So I will give it a shot

**Comment by christian-bromann** [comment]
I believe the [`ConfigParser`](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-config/src/lib/ConfigParser.ts) is a good place to start looking into.

**Comment by tech-dm-klymenko** [comment]
Now I'm a little bit limited on time, so work on this task is not going as quickly as I would like, but I'm still working on it

**Comment by henrik-andersson** [comment]
When I reported this issue I think I was using webdriverio version 7. At that time the --spec command worked as described in this ticket. But with webdriver 8, the spec command does not work like this anymore, I think it's no longer possible to use just parts of a file name when specifying spec file(s).

I'm currently on webriverio version 8.10.5 and at least on that version you need to specify a path to a spec file.

So just saying this to make this ticket a bit clearer and to avoid any possible confusions if comparing/testing the --spec command.

**Comment by Pawel1894** [comment]
@tech-dm-klymenko Ahh sorry, I'll look for something else then :) Have fun with this one.

**Comment by christian-bromann** [comment]
@tech-dm-klymenko did you make any progress on this?

**Comment by tech-dm-klymenko** [comment]
@christian-bromann 
This issue is now in 'pending' state from my side. Because it could not be completed without fixing "--spec" functionality. Now everything necessary for completion is already merged. As result, I plan to finish my current Jasmine task (related to AfterHook) and then I will complete this issue and create a PR for it

**Comment by christian-bromann** [comment]
Awesome, let me know if I can help with anything.

**Comment by Delta456** [comment]
This issue can be closed as #12077 is merged
