### ISSUE TITLE
[🐛 Bug]: webdriverio's expect not working with node 16

### ISSUE THREAD

**Issue by Badisi** [webdriverio/webdriverio#8219]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.19.5

### Node.js Version

16.14.2

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  browserName: 'chrome',
  maxInstances: 5,
  acceptInsecureCerts: true
}
```

### What happened?

The following code is working fine on `node12`, `node14` but not on `node16` :

```js
describe('Test', () => {
  beforeEach(async () => {
    await browser.url('http://localhost:4200');
  });
  it('Button should be displayed', async () => {
    const buttonEl = $('button');
    await expect(buttonEl).toBeDisplayed();
  });
});
```

```sh
# With node16:
Error: Expected [object Promise] to be displayed.
    at <Jasmine>
    at /Users/Badisi/tests-e2e/index.e2e.ts:18:33
    at step (/Users/tests-e2e/index.e2e.ts:33:23)
    at Object.next (/Users/Badisi/tests-e2e/index.e2e.ts:14:53)
```

----

A possible workaround is :

```js
describe('Test', () => {
  beforeEach(async () => {
    require('expect-webdriverio');
    global.wdioExpect = global.expect;
    const jasmine = require('jasmine');
    global.expect = jasmine.expect;

    await browser.url('http://localhost:4200');
  });
  it('Button should be displayed', async () => {
    const buttonEl = $('button');
    await global.wdioExpect(buttonEl).toBeDisplayed();
  });
});
```

----

It's obvious that this has to do with `expect-webdriverio` and `jasmine` but I don't know exactly where the problem is.

Any advices on how I should handle this ? Is the workaround legit or is it simply a bug that needs to be fixed ?

Thanks!

### How to reproduce the bug.

Run the example, provided in the "**What happened?**" section above, in a `node16` environment.

### Relevant log output

```typescript
Error: Expected [object Promise] to be displayed.
    at <Jasmine>
    at /Users/Badisi/tests-e2e/index.e2e.ts:18:33
    at step (/Users/tests-e2e/index.e2e.ts:33:23)
    at Object.next (/Users/Badisi/tests-e2e/index.e2e.ts:14:53)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by Badisi** [comment]
Thanks @christian-bromann.

Like I said in the description, it is obvious that this has to do with `expect-webdriverio` and `jasmine` but I don't know exactly where the problem is and I'm not too familiar with one or the other.

Do you have any guidances ?

**Comment by christian-bromann** [comment]
> Do you have any guidances ?

I think you are pointing into the right direction. I have the same guess.

**Comment by bburggraff** [comment]
@christian-bromann @Badisi - I'm encountering the same issue as well. I think it was introduced as part of https://github.com/webdriverio/webdriverio/pull/8175.

Is it as simple as changing this to expectAsync instead of expectSync?
https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-utils/src/shim.ts#L421

**Comment by christian-bromann** [comment]
@bburggraff mind raising a PR with a test for this?

**Comment by christian-bromann** [comment]
@bburggraff that PR just reverts the patch that has introduced this bug trying to patch another bug. I would prefer to have a fix for this so we don't have to revert things.

**Comment by bburggraff** [comment]
> @bburggraff that PR just reverts the patch that has introduced this bug trying to patch another bug. I would prefer to have a fix for this so we don't have to revert things.

I see.

I'm not super familiar with the code base, but I'll try to look into this.

**Comment by christian-bromann** [comment]
fixed in https://github.com/webdriverio/webdriverio/pull/8300
