### ISSUE TITLE
[🐛 Bug]: <Error calling: npx wdio config>

### ISSUE THREAD

**Issue by sheekha-singh** [webdriverio/webdriverio#8220]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.19.5

### Node.js Version

12.22.12

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
Using AWS device farm
```

### What happened?

Using v12.22.12 (npm v6.14.16) , wdio - @wdio/cli@7.19.5 and Appium version - 1.16.0 -
Tests run locally but not on AWS Device farm. I tried all combinations on device farm and I get the exact same error. Nothing works.

`Installing packages: @wdio/cli

@wdio/cli@7.19.5
added 301 packages from 367 contributors and audited 302 packages in 11.043s
37 packages are looking for funding
run npm fund for details

found 1 high severity vulnerability
run npm audit fix to fix them, or npm audit for details

Finished installing packages.

Running WDIO CLI Wizard...

=========================
WDIO Configuration Helper
? Where is your automation backend located? (Use arrow keys)
❯ On my local machine
In the cloud using Experitest
In the cloud using Sauce Labs
In the cloud using Browserstack or Testingbot or LambdaTest or a different ser
vice
I have my own Selenium cloud �[31D�[31C(node:3777) UnhandledPromiseRejectionWarning: Error: Error calling: npx wdio config
at ChildProcess. (/home/device-farm/.npm/_npx/3777/lib/node_modules/wdio/build/utils.js:21:31)
at ChildProcess.emit (events.js:314:20)
at maybeClose (internal/child_process.js:1022:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
(node:3777) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3777) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

### What is your expected behavior?

I expected for the test to run on aws device farm

### How to reproduce the bug.

Create a test run in device farm with Mocha framework and try using the versions mentioned above in the yaml file

### Relevant log output

```typescript
const { config } = require("./wdio.shared.conf");

config.capabilities = [
  {
    maxInstances: 1
  }
];

exports.config = config;









exports.config = {
  runner: "local",
  maxInstances: 1,
  port: 4723,
  path: "/wd/hub",
  logLevel: 'debug',
  deprecationWarnings: false,
  bail: 0,
  baseUrl: "http://localhost",
  waitforTimeout: 60000,
  connectionRetryTimeout: 240000,
  connectionRetryCount: 3,
  specs: [
    [
            "./test/specs/BasicAuthentication.test.js",
            "./test/specs/OperatorDashboard.test.js"
                ],
                
              ],
  framework: "mocha",
  reporters: ["spec"],
 // newCommandTimeout: 300,
 // services: ['aws-device-farm'],
  mochaOpts:{
 //   ui:'bdd',
    timeout: 5000
  }




Running WDIO CLI Wizard...

=========================
WDIO Configuration Helper
=========================

? Where is your automation backend located? (Use arrow keys)
❯ On my local machine 
  In the cloud using Experitest 
  In the cloud using Sauce Labs 
  In the cloud using Browserstack or Testingbot or LambdaTest or a different ser
vice 
  I have my own Selenium cloud [31D[31C(node:4291) UnhandledPromiseRejectionWarning: Error: Error calling: npx wdio config
    at ChildProcess.<anonymous> (/home/device-farm/.npm/_npx/4291/lib/node_modules/wdio/build/utils.js:21:31)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
(node:4291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4291) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 
[DEVICEFARM] ########### Entering phase post_test ###########
 
 
[DEVICEFARM] ########### Finish executing testspec ###########
 
[DEVICEFARM] ########### Setting upload permissions ###########
 
 
[DEVICEFARM] Tearing down your device. Your tests report will come shortly.



Added log output in the above section
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by sheekha-singh** [comment]
I tried it with Node v 14 as well as 16.13.0. I get the same error. I basically tried all combinations of Node and Appium to get it to kickoff the WDIO cli wizard

**Comment by sheekha-singh** [comment]
Here's the log with latest node version. I used 17.0.0 and I still get that error. 

`[DEVICEFARM] Setting up your device. This usually takes 2-3 minutes.
[DEVICEFARM] ########### Start executing testspec ###########
 
 
[DEVICEFARM] ########### Entering phase install ###########
 
[DeviceFarm] nvm install 17.0.0
Downloading and installing node v17.0.0...
Downloading https://nodejs.org/dist/v17.0.0/node-v17.0.0-linux-x64.tar.xz...

########                                                                  11.5%
###################                                                       27.4%
#################################                                         46.1%
#############################################                             63.8%
###########################################################               82.0%
#############################################################             85.9%
################################################################          89.9%
###################################################################       93.7%
######################################################################    97.6%
######################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v17.0.0 (npm v8.1.0)
[DeviceFarm] echo "Navigate to test package directory"
Navigate to test package directory
[DeviceFarm] cd $DEVICEFARM_TEST_PACKAGE_PATH
[DeviceFarm] npm install *.tgz

added 1 package, and audited 19 packages in 1s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice 
npm notice New minor version of npm available! 8.1.0 -> 8.6.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.6.0>
npm notice Run `npm install -g npm@8.6.0` to update!
npm notice 
[DeviceFarm] export APPIUM_VERSION=1.16.0
[DeviceFarm] avm $APPIUM_VERSION
/usr/bin/avm: line 261: appium: command not found
  [36m    exists[0m : [90m[0m
[DeviceFarm] ln -s /usr/local/avm/versions/$APPIUM_VERSION/node_modules/.bin/appium  /usr/local/avm/versions/$APPIUM_VERSION/node_modules/appium/bin/appium.js
 
[DEVICEFARM] ########### Entering phase pre_test ###########
 
[DeviceFarm] echo "Start appium server"
Start appium server
[DeviceFarm] appium --log-timestamp --default-capabilities "{\"deviceName\": \"$DEVICEFARM_DEVICE_NAME\", \"platformName\":\"$DEVICEFARM_DEVICE_PLATFORM_NAME\", \"app\":\"$DEVICEFARM_APP_PATH\", \"udid\":\"$DEVICEFARM_DEVICE_UDID\", \"platformVersion\":\"$DEVICEFARM_DEVICE_OS_VERSION\", \"chromedriverExecutable\":\"$DEVICEFARM_CHROMEDRIVER_EXECUTABLE\"}" >> $DEVICEFARM_LOG_DIR/appiumlog.txt 2>&1 &
[DeviceFarm] start_appium_timeout=0; while [ true ]; do
    if [ $start_appium_timeout -gt 60 ];
    then
        echo "appium server never started in 60 seconds. Exiting";
        exit 1;
    fi;
    grep -i "Appium REST http interface listener started on 0.0.0.0:4723" $DEVICEFARM_LOG_DIR/appiumlog.txt >> /dev/null 2>&1;
    if [ $? -eq 0 ];
    then
        echo "Appium REST http interface listener started on 0.0.0.0:4723";
        break;
    else
        echo "Waiting for appium server to start. Sleeping for 1 second";
        sleep 1;
        start_appium_timeout=$((start_appium_timeout+1));
    fi;
done;
Waiting for appium server to start. Sleeping for 1 second
Waiting for appium server to start. Sleeping for 1 second
Waiting for appium server to start. Sleeping for 1 second
Waiting for appium server to start. Sleeping for 1 second
Waiting for appium server to start. Sleeping for 1 second
Waiting for appium server to start. Sleeping for 1 second
Waiting for appium server to start. Sleeping for 1 second
Waiting for appium server to start. Sleeping for 1 second
Waiting for appium server to start. Sleeping for 1 second
Waiting for appium server to start. Sleeping for 1 second
Appium REST http interface listener started on 0.0.0.0:4723
 
[DEVICEFARM] ########### Entering phase test ###########
 
[DeviceFarm] echo "Navigate to test source code"
Navigate to test source code
[DeviceFarm] cd $DEVICEFARM_TEST_PACKAGE_PATH/node_modules/*
[DeviceFarm] echo "Start Appium Node test"
Start Appium Node test
[DeviceFarm] npx wdio run wdio.android.conf.js

                 -:...........................-:.
                 +                              +
              `` +      `...`        `...`      + `
            ./+/ +    .:://:::`    `::///::`  ` + ++/.
           .+oo+ +    /:+ooo+-/    /-+ooo+-/ ./ + +oo+.
           -ooo+ +    /-+ooo+-/    /-+ooo+-/ .: + +ooo.
            -+o+ +    `::///:-`    `::///::`    + +o+-
             ``. /.     `````        `````     .: .``
                  .----------------------------.
           `-::::::::::::::::::::::::::::::::::::::::-`
          .+oooo/:------------------------------:/oooo+.
      `.--/oooo-                                  :oooo/--.`
    .::-``:oooo`                                  .oooo-``-::.
  ./-`    -oooo`--.: :.--                         .oooo-    `-/.
 -/`    `-/oooo////////////////////////////////////oooo/.`    `/-
`+`   `/+oooooooooooooooooooooooooooooooooooooooooooooooo+:`   .+`
-/    +o/.:oooooooooooooooooooooooooooooooooooooooooooo:-/o/    +.
-/   .o+  -oooosoooososssssooooo------------------:oooo- `oo`   +.
-/   .o+  -oooodooohyyssosshoooo`                 .oooo-  oo.   +.
-/   .o+  -oooodooysdooooooyyooo` `.--.``     .:::-oooo-  oo.   +.
-/   .o+  -oooodoyyodsoooooyyooo.//-..-:/:.`.//.`./oooo-  oo.   +.
-/   .o+  -oooohsyoooyysssysoooo+-`     `-:::.    .oooo-  oo.   +.
-/   .o+  -ooooosooooooosooooooo+//////////////////oooo-  oo.   +.
-/   .o+  -oooooooooooooooooooooooooooooooooooooooooooo-  oo.   +.
-/   .o+  -oooooooooooooooooooooooooooooooooooooooooooo-  oo.   +.
-+////o+` -oooo---:///:----://::------------------:oooo- `oo////+-
+ooooooo/`-oooo``:-```.:`.:.`.+/-    .::::::::::` .oooo-`+ooooooo+
oooooooo+`-oooo`-- `/` .:+  -/-`/`   .::::::::::  .oooo-.+oooooooo
+-/+://-/ -oooo-`:`.o-`:.:-````.:    .///:``````  -oooo-`/-//:+:-+
: :..--:-:.+ooo+/://o+/-.-:////:-....-::::-....--/+ooo+.:.:--.-- /
- /./`-:-` .:///+/ooooo/+///////////////+++ooooo/+///:. .-:.`+./ :
:-:/.           :`ooooo`/`              .:.ooooo :           ./---
                :`ooooo`/`              .:.ooooo :
                :`ooooo./`              .:-ooooo :
                :`ooooo./`              .:-ooooo :
            `...:-+++++:/.              ./:+++++-:...`
           :-.````````/../              /.-:````````.:-
          -/::::::::://:/+             `+/:+::::::::::+.
          :oooooooooooo++/              +++oooooooooooo-
 
                           Webdriver.IO
              Next-gen browser and mobile automation
                    test framework for Node.js


Creating WebdriverIO project in /tmp/scratch0Aozku.scratch/test-packagep1ZCBo/node_modules/apptest/run

Installing packages:  @wdio/cli 


added 617 packages, removed 1 package, and audited 634 packages in 25s

71 packages are looking for funding
  run `npm fund` for details

7 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

Finished installing packages.

Running WDIO CLI Wizard...

=========================
WDIO Configuration Helper
=========================

? Where is your automation backend located? (Use arrow keys)
❯ On my local machine 
  In the cloud using Experitest 
  In the cloud using Sauce Labs 
  In the cloud using Browserstack or Testingbot or LambdaTest or a different ser
vice 
  I have my own Selenium cloud [31D[31C/tmp/scratch0Aozku.scratch/test-packagep1ZCBo/node_modules/apptest/node_modules/wdio/build/utils.js:21
                return reject(new Error((error && error.message) ||
                              ^

Error: Error calling: npx wdio config
    at ChildProcess.<anonymous> (/tmp/scratch0Aozku.scratch/test-packagep1ZCBo/node_modules/apptest/node_modules/wdio/build/utils.js:21:31)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1062:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)

Node.js v17.0.0
 
[DEVICEFARM] ########### Entering phase post_test ###########
 
 
[DEVICEFARM] ########### Finish executing testspec ###########
 
[DEVICEFARM] ########### Setting upload permissions ###########
 
 
[DEVICEFARM] Tearing down your device. Your tests report will come shortly.
`

**Comment by mwalton-trs** [comment]
Worked with @sheekha-singh on this issue.  Here are some more details:

The `@wdio/cli` dependencies weren't included in the node_modules directory within the bundled .tgz (when running `npm-bundle`).  This alone should not be an issue, because when you run `npx wdio run <config.js>` it should automatically install the correct version of `@wdio/cli` based on the package.json.

But when installing `@wdio/cli` from AWS Device Farm, it automatically goes through the WDIO Configuration Helper, which is a CLI utility that doesn't work for automated installations.

Suggestions to make things easier for others in the future:
1) Make `@wdio/cli` default to bypass the WDIO Configuration Helper when installing the packages (don't run `npx wdio config`)
2) Not sure if this falls into the realm of AWS Device Farm, but if you run `npx wdio run <config.js>` then we know a configuration file has already been created, so the WDIO Configuration Helper shouldn't even be run at all in that case (even if `@wdio/cli` was not installed previously).

**Comment by mwalton-trs** [comment]
To fix the issue, add `@wdio/cli` (and other `@wdio` libraries) to the bundledDependencies in the package.json.  Then run `npm install` and then `npm-bundle` should include those.

**Comment by christian-bromann** [comment]
You have been using [this depcrecated NPM package](https://www.npmjs.com/package/wdio) when running `npx wdio run wdio.conf.js`. You have to have `@wdio/cli` installed as dependency.

**Comment by adminruparupa** [comment]
in my case i just upgrade local node done
