### ISSUE TITLE
[💡 Feature]: override automatic jsonwp/w3c protocol choice

### ISSUE THREAD

**Issue by felix9** [webdriverio/webdriverio#8228]
### Is your feature request related to a problem?

On BrowserStack, IE11 returns a capabilities that wdio thinks is jsonwp, but it actually implements w3c instead, and jsonwp doesn't work.

Conversely, Edge 40 (v15) returns a capabilities that wdio thinks is w3c, but it actually implements jsonwp instead; w3c doesn't work.

### Describe the solution you'd like.

While it's plausible to fix wdio's `isW3C` function for these cases, it seems to me that it's hard to anticipate all the potential weird and rare ways that `isW3C` gets the answer wrong.

So I think it might be better to have a flag that can override that guess.

### Describe alternatives you've considered.

Workaround is to manually overwrite all the w3c or jsonwp commands to the correct variant in a `before` hook.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by erwinheitzman** [comment]
I'd rather fix the underlying issue then to introduce a workaround for it to the API.

**Comment by christian-bromann** [comment]
I agree with @erwinheitzman here. Happy to make the `isW3C` flag more strict but if BrowserStack sends back JSONWP capabilities but runs W3C WebDriver behind the scene that it is a bug in BrowserStack.
