### ISSUE TITLE
[🐛 Bug]: Slack service show for failed test - total failed equal to zero 

### ISSUE THREAD

**Issue by ellatom** [webdriverio/webdriverio#8257]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

V7

### Node.js Version

v17.5.0

### Mode

WDIO Testrunner

### What happened?

When i run tests and the test failed the total failed appear as equal to 0.
This happens both for jest/mocha assertions failing and for error in spec or tests.
![image](https://user-images.githubusercontent.com/68844149/164235697-57ecab68-8c57-4ee9-bc0a-c8f5b3ff8171.png)

### What is your expected behavior?

I have fixed this issue - it occur on package ‘wdio-slack-service’ - file 'src/index.js '.
I propose the following code to fix the issue.
There are two issues:
1.'message' in original code added as functio message()), even though it's not a function, but a key in an object
2.Not always there is a key 'matcherResult', this is when a condition should be added to validate this.

```
let testError = "";

if ('matcherResult' in results.error)
                    testError = results.error.matcherResult.message.replace(/[\u001b\u009b][-[+()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]/g, "");
                else{
                    testError = results.error
                }
```

After the update both of the error- no matter what there origin assertion or code will appear in the report and total failed will be count and not be equal to zero.

### How to reproduce the bug.

Create a test which failing on jest/mocha assertion.
Create a test which fails due to runnning code error.

After running this tests and sending the report to slack the failed tests will show the following result
Total tests: 0 | Total passed: 0 | Total failed: 0

instead of (for each test)
Total tests: 1 | Total passed: 0 | Total failed: 1

### Relevant log output

```typescript
before the fix:
Total tests: 0 | Total passed: 0 | Total failed: 0
after the fix:
Total tests: 1 | Total passed: 0 | Total failed: 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting @ellatom 

Please raise this issue or even better a PR in the [slack service](https://github.com/carmenmitru/wdio-slack-service) project. Thanks!
