### ISSUE TITLE
[🐛 Bug]: Step duration returned by afterStep -> result.duration is inaccurate (Cucumber)  

### ISSUE THREAD

**Issue by anupamck** [webdriverio/webdriverio#8258]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.19.5

### Node.js Version

14.15

### Mode

WDIO Testrunner

### What happened?

While executing a feature file (cucumber), in the console, I return the duration that each cucumber step takes to execute using the following command:

```  
afterStep: function (step, scenario, result, context) {
    console.log(result.duration);
  },
```

I obtain responses like: 
22.421457
55.5830156
25.109421
in the terminal. 

However, these values, assuming they are in ms, are much smaller than I expect. It also appears strange that a millisecond value is expressed with 6 decimal places.

For instance, when I ask the browser to pause for 1 second, I expect the step duration to be at least 1000 ms, which isn't the case. The value I received was "0.1203976".

In contrast, the Allure report generated in the same run shows duration values that are more plausible:

![image](https://user-images.githubusercontent.com/34277143/164449193-19d7e500-a49d-4df1-98f9-e3a488f79f90.png)

1. Why does this discrepancy exist? 
2. How else can I obtain the correct values for how long each step takes to execute? 

**Additional Info**
* We use cucumber
* With wdio version 6, the afterStep -> duration value worked as expected with the following command:
`  afterStep: function (test, context, { error, result, duration, passed, retries }) {
    console.log(duration);
}`

### What is your expected behavior?

The result.duration values in the function as part of the afterStep hook is in line with what is observed (consistent with values in the Allure report). 

### How to reproduce the bug.

Details to reproduce are included in the bug description. 

### Relevant log output

```typescript
Included in the bug description.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

You can find the snippet that creates the result object [here](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-cucumber-framework/src/index.ts#L45-L51). We are getting it from the Cucumber framework and already convert it from nano s to ms. But this might be wrong.

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by joshskumar** [comment]
yes the Issue with the conversion from nano to ms. It should be 1e6 and not 10e6. Can I take this up

**Comment by christian-bromann** [comment]
These numbers all look completely different I wonder how the Allure reporter generates them.

**Comment by anupamck** [comment]
This functionality worked perfectly in wdio v6. So I excavated its code and saw that this was how the duration is calcuated at the `afterHook`:

```
afterHook (uri, feature, scenario, step, result) {
        const payload = buildStepPayload(uri, feature, scenario, step, {
            type: 'hook',
            state: result.status,
            error: result.exception,
            duration: new Date() - this.testStart
        })

        this.emit('hook:end', payload)
    }
```

Where `testStart` is defined in another hook:

```
    handleBeforeStep (uri, feature, scenario, step, /*sourceLocation*/) {
        this.testStart = new Date()
        const type = getStepType(step.type)
        const payload = buildStepPayload(uri, feature, scenario, step, { type })

        this.emit(`${type}:start`, payload)
    }
```

You can find this here: https://github.com/webdriverio/webdriverio/blob/3251fc37b8d112074c33e9eb65475a2bbec3da12/packages/wdio-cucumber-framework/src/reporter.js

I also think Allure does something similar. Each step within Allure's reporter is depicted as:
```
{
      "name" : "And there are 5 Teasers displayed",
      "time" : {
        "start" : 1654845240014,
        "stop" : 1654845240204,
        "duration" : 190
      },
      "status" : "failed",
```
How exactly it obtains the start and stop timestamps here is a mystery to me. 

The current v7 of WDIO relies on the cucumber world object. 
```
function getResultObject (world: ITestCaseHookParameter): Frameworks.PickleResult {
    return {
        passed: (world.result?.status === Cucumber.Status.PASSED || world.result?.status === Cucumber.Status.SKIPPED),
        error: world.result?.message as string,
        duration: world.result?.duration?.nanos as number / 1e6 // convert into ms
    }
}
```
I think therein lies the problem. I am not sure if the world object is delivering the step duration we want. I looked through its documentation and couldn't find what it was delivering. It might be worthwhile to revert to calcuating duration using the system's `Date()`. 

I can't solve this problem on my own, but I hope this info can help somebody else who can.

**Comment by BorisOsipov** [comment]
Hi! We have rewritten the reporter to the new allure-js version. Please try version 8.5.0 of wdio-allure-reporter and provide more details if the issue still persists. Feel free to create a new issue with actual details if it reproduces.
