### ISSUE TITLE
Link to testrunner 'hooks' page 404's

### ISSUE THREAD

**Issue by klamping** [webdriverio/webdriverio#826]
Just a note that in the documents for the testrunner wdio.conf.js file, the link to the `hooks` documentation doesn't work as the page doesn't exist:
https://github.com/webdriverio/webdriverio/blob/master/examples/wdio.conf.js#L176

**Comment by juliepagano** [comment]
Ran into this today. Is there alternate documentation somewhere else with a little more information on working with the hooks?

**Comment by christian-bromann** [comment]
Yeah I first wanted to add a docs page for that but then I skipped it because I thought the small text is self explanatory. What information are missing here? We can easily add a docs page for that somewhere here: https://github.com/webdriverio/webdriverio/tree/master/docs/guide/testrunner

**Comment by juliepagano** [comment]
I think I was mostly confused about the bits with promises, but I figured it out once I took a closer look at the code.

**Comment by christian-bromann** [comment]
:+1: feel free to update the description so it makes more sense to you (and probably others)
