### ISSUE TITLE
client.on('error') not being called

### ISSUE THREAD

**Issue by benjyblack** [webdriverio/webdriverio#827]
According to [this document](http://webdriver.io/guide/usage/eventhandling.html) the `client.on('error')` hook should be called whenever an error occurs. Using version 3.2.5 of webdriverio I'm unable get the listener callback to fire:

```js
// set up global error handler
client.on('error', function (err) {
  console.log('Global error handler called');
});

client
.url('http://google.com')
.click('#non-existing-element')
.catch(function (err) {
  console.log('Local catch called');
});

// outputs >> 'Local catch called'
// does NOT output >> 'Global error handler called'
```

**Comment by benjyblack** [comment]
Seems to work fine with webdriver 3.1.0.

**Comment by christian-bromann** [comment]
@benjyblack thanks for reporting! Gets the error thrown without calling catch?

**Comment by benjyblack** [comment]
Nope, if there's no catch, then nothing gets logged.

**Comment by benjyblack** [comment]
Have also noticed some other odd error handling behavior, and this happens in webdriver v3.1.0 as well. I can't seem to get `.on('error')` to fire when throwing an error from a custom command:

```js
// set up global error handler
client.on('error', function (err) {
  console.log('Global error handler called');
});

client.addCommand('throwError', function () {
  throw new Error('Custom command error');
});

client
.throwError()
.catch(function (err) {
  console.log('Local catch called');
});

// outputs >> 'Local catch called'
// does NOT output >> 'Global error handler called'
```

Would you like me to open another issue regarding `.on('error')` handling errors thrown from custom commands?

**Comment by christian-bromann** [comment]
yes please, thanks!

**Comment by benjyblack** [comment]
Think I've figured out the issue actually. I thought I'd tried removing the `.catch` and the global error handler still wasn't being called, but this doesn't seem to be the case actually. Just tried removing the catch and the global error _is_ called. I guess this is intended behavior? If the error is eventually `caught` then the 'error' event is never emitted?

**Comment by christian-bromann** [comment]
fixed this issue in v4
