### ISSUE TITLE
[💡 Feature]: <Preset localstorage for tests>

### ISSUE THREAD

**Issue by CorporatePittypang** [webdriverio/webdriverio#8297]
### Is your feature request related to a problem?

Currently the application starts and the value change happen after the readout of the value from localstorage, hence it is not possible to start the application with prepared localstorage values. 

It is possible to fiddle with browser profiles, but that would alter the whole test running, not just the given test case set.

### Describe the solution you'd like.

I would like to have a way to pre-define a JSON structure of the localStorage values, and the application should read the values, given in this structure, even if that happens at the app init stage. 

### Describe alternatives you've considered.

If it would be possible to define commands, what runs after the environment has been built, but the test case is not yet using it, that could work as well. 

### Additional context

https://stackoverflow.com/questions/71913075/set-localstorage-and-read-upon-app-startup-in-selenium
My issue was asked on stackoverflow, but i had no answers so far, and my findings were unsufficient in this case as well. 

It slows down the e2e testing quite a lot, but i would not like to adapt the production code and make the steps skippable in other, hacky ways. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
> I would like to have a way to pre-define a JSON structure of the localStorage values, and the application should read the values, given in this structure, even if that happens at the app init stage.

How is this different from using the `execute` command and use the localStorage API to fill the storage with given values?

**Comment by CorporatePittypang** [comment]
The execute version happens too late, the readout from the storage is already happened by that time.

**Comment by CorporatePittypang** [comment]
There is another possibility, that the mobile application does not use the localstorage, but reads up from an xml in the file system, what we can not edit from the webdriver.

**Comment by christian-bromann** [comment]
> The execute version happens too late, the readout from the storage is already happened by that time.

Not if you go on a different (possible empty) page served from the same domain and then accessing the local storage API.

That said, afaik I don't think any browser would allow us to populate the local storage of a domain before visiting it.

**Comment by CorporatePittypang** [comment]
Thanks, i think we will have to investigate some way to work around this, and make the mobile context sweep up the pre-set local storage values. I was wondering, how comes, that this option is not a required one, but now it seems logical to be blocked from the browser's side.
