### ISSUE TITLE
Error: "Request failed with status 500 due to session not created: This version of ChromeDriver only supports Chrome version 98 Current browser version is 101.0.4951.4[🐛 Bug]: <title>

### ISSUE THREAD

**Issue by ellatom** [webdriverio/webdriverio#8298]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.15

### Node.js Version

V17.5.0

### Mode

WDIO Testrunner

### What happened?

Hi,
I'm getting error when running automation on electron app with version lower than google chrome installed version.
I can't downgrade the google chrome version.
Is there a way to run automation on computer with the following:
google chrome version 101.0.4951.41
electron app version 100.0.4896.60
chrome driver version 101.0.4951.41 or 100.0.4896.60
Thanks,Ella

### What is your expected behavior?

The test running without error

### How to reproduce the bug.

Run automation on electron app with version lower than google chrome installed version.
Run tests with the following versions:
google chrome version 101.0.4951.41
electron app version 100.0.4896.60
chrome driver version 101.0.4951.41 or 100.0.4896.60
configuration fle 'wdio.conf.ts':

  services: [
    [
      'electron',
      {
        newSessionPerTest: false,
        binaryPath: process.env.RELATIVE_PATH_TO_ELECTRON, 
        appArgs: ['--disable-infobars', '--disable-dev-shm-usage', '--no-sandbox', '--remote-debugging-port=9222'],
        chromedriver: {
          port: 9519,
          logFileName: 'wdio-chromedriver.log',
        },
        safaridriver: {
          port: 4444,
          logFileName: 'wdio-safaridriver.log',
        },
      },
    ],

### Relevant log output

```typescript
Error: Failed to create session.
session not created: This version of ChromeDriver only supports Chrome version 98
Current browser version is 101.0.4951.41 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
After looking at this again it seems to be the same issue as https://github.com/webdriverio-community/wdio-electron-service/issues/28. Anyway, given you are using the electron service for setting up the tests I suggest to raise the issue there if it is not the same and mentioned. Sorry for not being clear enough in the discussion.
