### ISSUE TITLE
[🐛 Bug]: Missing failing Steps when useCucumberStepReporter: true in allure-reporter

### ISSUE THREAD

**Issue by JordiSAGE** [webdriverio/webdriverio#8299]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

webdriverio: 7.19.4, allure-reporter: 7.19.5

### Node.js Version

v16.14.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
reporters: [
        'dot',
        'spec',
        [
            'allure',
            {
                outputDir: path.resolve(cfgReportDir + '/allure-results'),
                disableWebdriverStepsReporting: true,
                disableWebdriverScreenshotsReporting: true,
                useCucumberStepReporter: true,
            },
        ],
    ],
```

### What happened?

Since I upgraded my project to nodejs v16.14.0, webdriverio 7.19.4 and allure-reporter: 7.19.5, failed steps are missing and no longer showing in allure report, both on Jenkins server and running tests locally, when the parameter useCucumberStepReporter is set to true.
Command line test execution:
![image](https://user-images.githubusercontent.com/33693547/166487796-1d02107c-08fc-4bed-9fc2-ebffa5465d38.png)

Allure report generated from previous test execution:
![image](https://user-images.githubusercontent.com/33693547/166489998-a7385253-4ac8-42ec-a752-896f65752903.png)

Thanks in advance for your help!

### What is your expected behavior?

The allure report generated after the wdio test execution, should show the failed steps when the parameter useCucumberStepReporter is set to true.

### How to reproduce the bug.

To reproduce the bug, run a wdio feature using nodejs v16.14.0, webdriverio 7.19.4 and allure-reporter: 7.19.5 and the parameter useCucumberStepReporter set to true.

### Relevant log output

```typescript
"spec" Reporter:
------------------------------------------------------------------
[Chrome 100.0.4896.127 win32 #0-0] Running: Chrome (v100.0.4896.127) on win32
[Chrome 100.0.4896.127 win32 #0-0] Session ID: b1a43613-a281-4d37-aaea-a7f75e6a7a49
[Chrome 100.0.4896.127 win32 #0-0]
[Chrome 100.0.4896.127 win32 #0-0] » \features\A-BPRO-BTP-001.feature
[Chrome 100.0.4896.127 win32 #0-0] Bank transaction process for 
[Chrome 100.0.4896.127 win32 #0-0] Test coverage from transctions process 
[Chrome 100.0.4896.127 win32 #0-0]
[Chrome 100.0.4896.127 win32 #0-0] As as user I want to check  transaction process
[Chrome 100.0.4896.127 win32 #0-0]    ✓ Given the user is logged into with "param:loginType" using user name "param:loginUserName" and password "param:loginPassword"
[Chrome 100.0.4896.127 win32 #0-0]    ✓ And the user opens the "Bank transactions management" entity
[Chrome 100.0.4896.127 win32 #0-0]    ✓ Then the "Bank transaction management" screen is displayed
[Chrome 100.0.4896.127 win32 #0-0]    ✓ When the user selects the main data table of the page
[Chrome 100.0.4896.127 win32 #0-0]    ✖ And the user selects row that has the text "DDD" in column with header: "Bank"
[Chrome 100.0.4896.127 win32 #0-0]    ? And the user opens "Display" function on toolbox of the selected row
[Chrome 100.0.4896.127 win32 #0-0]    ? And the user waits 10 seconds
[Chrome 100.0.4896.127 win32 #0-0]
[Chrome 100.0.4896.127 win32 #0-0] 4 passing (14.4s)
[Chrome 100.0.4896.127 win32 #0-0] 1 failing
[Chrome 100.0.4896.127 win32 #0-0]
[Chrome 100.0.4896.127 win32 #0-0] 1) As as user I want to check  transaction process And the user selects row that has the text "DDD" in column with header: "Bank"
[Chrome 100.0.4896.127 win32 #0-0] Error: Grid row not found.
[Chrome 100.0.4896.127 win32 #0-0] Error: Grid row not found.
[Chrome 100.0.4896.127 win32 #0-0]     at DataTable.<anonymous> (C:\Projects\Cucumber\lib\page-model\object\data-table.ts:1164:19)
[Chrome 100.0.4896.127 win32 #0-0]     at Generator.next (<anonymous>)
[Chrome 100.0.4896.127 win32 #0-0]     at fulfilled (C:\Projects\Cucumber\lib\page-model\object\data-table.ts:28:58)
[Chrome 100.0.4896.127 win32 #0-0]     at runMicrotasks (<anonymous>)
[Chrome 100.0.4896.127 win32 #0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)


Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:23
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by praveendvd** [comment]
@christian-bromann  I could take this up , if there is no volunteers in 1 week 🎉🎉

**Comment by christian-bromann** [comment]
@praveendvd go for it!

**Comment by kaksjonovs** [comment]
Hello @praveendvd could you please check with `@wdio/allure-reporter:v7.19.7`.
I had the same issue and it was fixed with: https://github.com/webdriverio/webdriverio/pull/8262
At least for me.

**Comment by praveendvd** [comment]
@JordiSAGE  could you check and confirm with above version and see if we can close this

**Comment by JordiSAGE** [comment]
Hi,
First of all, thanks for your support!
Unfortunately, it seems that the @wdio/allure-reporter:v7.19.7 is failing from my side when trying to run the command "npm install @wdio/allure-reporter@latest", simply finishing the installation shortly after starting without any errors.
Please, check my packages config above:
  "dependencies": {
    "@babel/cli": "7.17.6",
    "@babel/core": "7.17.9",
    "@babel/preset-env": "7.16.11",
    "@babel/register": "7.17.7",
    "@cucumber/cucumber": "^8.0.0",
    "@types/chai": "4.3.0",
    "@types/cucumber": "^7.0.0",
    "@types/node": "^17.0.23",
    "@types/source-map-support": "^0.5.4",
    "@wdio/allure-reporter": "^7.19.7",
    "@wdio/cli": "^7.19.7",
    "@wdio/config": "^7.19.5",
    "@wdio/cucumber-framework": "^7.19.7",
    "@wdio/devtools-service": "^7.19.7",
    "@wdio/dot-reporter": "^7.19.7",
    "@wdio/local-runner": "^7.19.7",
    "@wdio/mocha-framework": "^7.19.7",
    "@wdio/reporter": "^7.19.7",
    "@wdio/runner": "^7.19.7",
    "@wdio/shared-store-service": "^7.19.7",
    "@wdio/spec-reporter": "^7.19.7",
    "allure-commandline": "2.17.2",
    "bytenode": "1.3.5",
    "chai": "~4.3.6",
    "cucumber-tag-expressions": "2.0.3",
    "dotenv": "^16.0.0",
    "fs-copy-file-sync": "1.1.1",
    "puppeteer": "^13.5.2",
    "rimraf": "3.0.2",
    "source-map-support": "0.5.21",
    "wdio-cucumber-reporter": "^0.0.2",
    "wdio-typescript-service": "0.0.3",
    "wdio-wait-for": "^2.2.6",
    "webdriverio": "^7.19.7"
  },
I've updated all the @wdio packages to their latest versions with the same result.
Thanks again!
