### ISSUE TITLE
Adding information to a custom reporter

### ISSUE THREAD

**Issue by dhoulker** [webdriverio/webdriverio#830]
I've been writing a custom reporter, as described here

https://github.com/webdriverio/webdriverio/blob/master/examples/wdio/reporter/my.custom.reporter.js

```this.on('test:start', function(test) {```

I can get to the test object, which looks like this:

````
{ event: 'test:start',
  pid: 26547,
  title: 'Should display section module (containing 3 modules of content and grey arrow icon above)',
  pending: false,
  parent: 'Homepage',
  type: 'test',
  file: '/../../Acceptance/test/specs/desktop/index.js',
  err: null,
  runner: { '26547': { browserName: 'chrome' } } }
````

Is there anyway to add to this object and make provide additional information to my custom reporter? For example, could i pass it a screenshot?

**Comment by christian-bromann** [comment]
Nope. A screenshot would require to take an extra command. We will introduce service plugins with v4 which will allow to interfere into the test process to take screenshots for example. A reporter should not slow down the execution or add additional commands.
