### ISSUE TITLE
[🏠 Internal]: Replace Lerna with a new monorepo tooling

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#8302]
### Is your feature request related to a problem?

Lerna is [not actively maintained](https://github.com/lerna/lerna/pull/3092) anymore. To avoid future devx issues we should move to a different toolchain.

### Describe the solution you'd like.

One could take a look to https://monorepo.tools/#tools-review to see what other tooling is out there. Just note that the comparison might be biased. Given the best thing about the current setup is the release pipeline (with nicely automated changelog) I would favor something that provides an identical result.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by erwinheitzman** [comment]
Depending on what we like to get out of the build/package management system, [npm workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces) might be enough for our us. Might be worth considering when reviewing our options.

**Comment by juristr** [comment]
We are helping move Lerna forward. Read more here: https://github.com/lerna/lerna/issues/3121

**Comment by christian-bromann** [comment]
That is awesome to hear. This issue is irrelevant then.
