### ISSUE TITLE
[🐛 Bug]: Cucumber - Screenshot not attached in Allure report in failed step 

### ISSUE THREAD

**Issue by anupamck** [webdriverio/webdriverio#8323]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.19.17

### Node.js Version

14.17.6

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
Cucumber
```

### What happened?

Despite clearly including the command for capturing screenshot in case of failure in the `Afterstep` hook, no screenshot is captured and attached in the Allure report. 
`     afterStep: function (step, scenario, result, context) {
        //  browser.takeScreenshot();
         if(!result.passed) {
             browser.takeScreenshot();
             console.log("A test has failed!");
         }
     },`  

I've also ensured that the `disableWebdriverScreenshotsReporting` flag is set to false. 

Further, the log message directly below the screenshot works. Therefore, the hook is executed. I also notice that if I take a screenshot before the `if(!result.passed)` condition, screenshots are attached in every step in the Allure report, which is the expected behaviour. 

### What is your expected behavior?

Screenshots are attached with the failed step in the Allure report. 

### How to reproduce the bug.

https://github.com/anupamck/wdio-allure-screenshot-bug 

It is just the standard example repo with cucumber + page objects and one additional test. 

### Relevant log output

```typescript
-
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by praveendvd** [comment]
@anupamck you should use async await for hooks too , could you try that :

```
afterStep: async function (step, scenario, result, context) { // browser.takeScreenshot(); i

f(!result.passed) { 
await browser.takeScreenshot(); 

console.log("A test has failed!"); } },
```

**Comment by praveendvd** [comment]
https://github.com/webdriverio/webdriverio/issues/7940

**Comment by praveendvd** [comment]
Please leave a comment if its still needs to reopened

**Comment by anupamck** [comment]
@praveendvd - Thank you! Making it async resolved the problem. 

If that is the case, does it not make sense to update this in the documented example too? Under documentation?

**Comment by anupamck** [comment]
https://webdriver.io/docs/allure-reporter/ 

```
afterStep: function (step, scenario, { error, duration, passed }, context) {
  if (error) {
    browser.takeScreenshot();
  }
}
```
It isn't wrong, strictly speaking, since the feature works in most cases without async await. But if this issue isn't a bug, I think the document ought to also mention this.

**Comment by praveendvd** [comment]
@anupamck  as

**Comment by christian-bromann** [comment]
Thanks both @praveendvd and @anupamck 👏
