### ISSUE TITLE
[💡 Feature]: Log messages from named Cucumber hooks to the WDIO reporter

### ISSUE THREAD

**Issue by hammzj** [webdriverio/webdriverio#8324]
### Is your feature request related to a problem?

[An addition to name Before and After hooks has been added in Cucumber v8.1.0](https://github.com/cucumber/cucumber-js/blob/v8.1.0/docs/support_files/hooks.md#named-hooks).

Currently, these only are sent to Cucumber's formatter, which I've discussed as as not being used in WebDriverIO in issue #7692. Therefore, we will not see these messages in any WebDriverIO reporter output.

### Describe the solution you'd like.

When a Cucumber `Before/After` hook has the `name` parameter provided, the WebDriverIO reporters should log the string of that parameter prior to the Cucumber hook being executed.

### Describe alternatives you've considered.

I could just log the message within the function of the hook, changing it from
```js
//Hook with name
Before({name: 'General setup'}, function(){
  //...do some setup
});
```

to

```js
//Hook with log
Before(function(){
  logger.info('General setup');
  //...do some setup
});
```

However, this is a little less clean when there is a lot going on in the function. Having the `name` parameter is much cleaner to read and is now the standard way of handling it in Cucumber v8.1.0.

### Additional context

[Cucumber 8.0 release notes](https://cucumber.io/blog/open-source/announcing-cucumber-js-8-0-0/)

[Named hooks reference](https://github.com/cucumber/cucumber-js/blob/v8.1.0/docs/support_files/hooks.md#named-hooks)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Hey @hammzj ,
thanks for filing the issue. Your suggestion makes sense.

We would appreciate any help on this so please consider to help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by christian-bromann** [comment]
> I guess I'm not sure how WDIO reporters are going to handle this just yet, or where it will appear.

Ideally the `wdio-reporter` package should ensure that all events to reporters are compliant. So I would start there. Afaik Mocha also has named hooks so it would make sense to propagate these information anyway.

> If I can take this up, I'll do what I can but no promises on my poor TypeScript abilities 🥲

Feel free to type everything with `any` and raise a PR, I am happy to help getting the types into place 😉

**Comment by christian-bromann** [comment]
Fixed by https://github.com/webdriverio/webdriverio/pull/11069
