### ISSUE TITLE
Allow command line args to be passed on to jasmine/mocha/cucumber

### ISSUE THREAD

**Issue by Sironfoot** [webdriverio/webdriverio#834]
I'm running tests on a highly dynamic marketing based site that requires me to pass command line arguments to my webdriver tests, something like this:

> wdio --campaignId=123 --productId=456

I'm writing my tests in jasmine, and for some reason these command args aren't getting passed onto jasmine. I can read them just fine in my wdio.conf.js file, for instance in the onPrepare event:

````javascript
exports.config = {
    ....other options (snip)...

    framework: 'jasmine',

    jasmineNodeOpts: {
        defaultTimeoutInterval: 9999999,
        expectationResultHandler: function (passed, assertion) { }
    },

    onPrepare: function (config) {
        var campaignId = parseInt(process.argv[2].replace('--campaignId=', ''));
        console.log(campaignId) // outputs 123
    }
};
````

But I can't read them in jasmine...

````javascript
describe('Campaign Tests', function () {

    beforeEach(function(done) {
        browser.session(function(err, client) {
            var campaignId = parseInt((process.argv[2] || '').replace('--campaignId=', ''));
            console.log(campaignId) // NaN/undefined
        });
    });

    it('should test something...snip...'
````

AFAIK, jasmine is being run in a separate process and thus the command args aren't being passed along. So can I make a feature request and provide a way for custom arguments to be passed along to external testing frameworks (jasmine, mocha etc.).

Maybe there is a way of doing this that I've missed, but I couldn't find anything in the docs or Google. I also posted a Stackoverflow question here: http://stackoverflow.com/questions/33153459/webdriverio-how-to-send-arguments-to-jasmine-tests

**Comment by christian-bromann** [comment]
@Sironfoot have you tried to use env variables? E.g. by running your test like:
```sh
CAMPAIGNID=123 PRODUCTID=456 wdio
```
and in your test you should be able to access them via
```js
process.env.CAMPAIGNID
```

**Comment by christian-bromann** [comment]
Closed due to inactivity
