### ISSUE TITLE
how to enable cookie

### ISSUE THREAD

**Issue by shawnLiujianwei** [webdriverio/webdriverio#835]
i create the client 

var webdriverio = require('webdriverio');
  
    var options = {
        desiredCapabilities: {
            browserName: 'phantomjs',
            javascriptEnabled:true,
            webStorageEnabled:true
        },
        "host":"localhost",
        "port":9444,
        "logLevel":"debug"
    };

i always got the cookie is disabled , how can i enable the cookies . 

thanks

**Comment by christian-bromann** [comment]
@shawnLiujianwei cookies should be enabled automatically. Is PhantomJS blocking it?

**Comment by shawnLiujianwei** [comment]
should be blocked by phantomjs. thanks

**Comment by narainsagar** [comment]
can anyone tell what's the solution to this? 
@shawnLiujianwei  did you get the answer?
thanks

**Comment by shawnLiujianwei** [comment]
@narainsagar 
i think this was blocked by phantomjs , now it works for me .

**Comment by narainsagar** [comment]
Thanks for the response. @shawnLiujianwei  What you did then? Could you give me any link or note? Thanks
