### ISSUE TITLE
[🐛 Bug]: <Alert closing automatically>

### ISSUE THREAD

**Issue by praveenngp15** [webdriverio/webdriverio#8351]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

"@wdio/cli": "^7.19.3", 

### Node.js Version

16.15.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
import { Suite } from '@wdio/types/build/Frameworks';
import * as fs from 'fs';

const video = require('wdio-video-reporter');

export let config: WebdriverIO.Config = {
    specs: ['./test/**/*.spec.ts'],
    suites: {
        login: ['./test/**/example.spec.ts']
    },

    capabilities: [
        {
            browserName: 'chrome',
            maxInstances: 1,
            'goog:chromeOptions': {
                args: ['--start-maximized']
            }
        }
    ],


    framework: 'Jasmine',
    logLevel: 'error',
    jasmineOpts: {
        defaultTimeoutInterval: 120000
    },
    reporters: [
        'dot',
        'spec',
        [
            'junit',
            {
                outputDir: './reports',
                outputFileFormat(options: { cid: any; capabilities: any }) {
                    // optional
                    return `results-${options.cid}.${options.capabilities}.xml`;
                }
            }
        ],
        [
            video,
            {
                saveAllVideos: true, // If true, also saves videos for successful test cases
                videoSlowdownMultiplier: 3 // Higher to get slower videos, lower for faster videos [Value 1-100]
            }
        ]
    ],

    onPrepare() {
        const dirJunit = `reports`;
        if (fs.existsSync(dirJunit)) {
            fs.rmdir(dirJunit, {recursive: true}, (err) => {
                if (err) {
                    throw err;
                }

                console.log(`${dirJunit} is deleted!`);
            });
        }

        const dirVideo = `_results_`;
        if (fs.existsSync(dirVideo)) {
            fs.rmdir(dirVideo, {recursive: true}, (err) => {
                if (err) {
                    throw err;
                }
                console.log(`${dirVideo} is deleted!`);
            });
        }
    },

    async beforeSuite(suite: Suite) {
    },

    async afterSuite(suite: Suite) {
        await browser.pause(20000);
    },
    services: ['chromedriver'],
    autoCompileOpts: {
        autoCompile: true,
        // for all available options
        tsNodeOpts: {
            transpileOnly: true,
            project: 'tsconfig.json'
        }
    }
};
```

### What happened?

Alert is closing automatically 

await browser.url('https://chercher.tech/practice/popups')
        await $("//input[@name='alert']").click()
        await browser.pause(10000)
        await browser.acceptAlert()

So not able to accept or dismiss the alert

### What is your expected behavior?

Alert should not close automatically

### How to reproduce the bug.

**await browser.url('https://chercher.tech/practice/popups')
        await $("//input[@name='alert']").click()
        await browser.pause(10000)
        await browser.acceptAlert()**

### Relevant log output

```typescript
no such alert: no such alert
  (Session info: chrome=101.0.4951.54)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by praveenngp15** [comment]
When adding video reporter the alert is automatically accepting

const video = require('wdio-video-reporter');


reporters: ['spec', 

    [
        video,
        {
            saveAllVideos: true, // If true, also saves videos for successful test cases
            videoSlowdownMultiplier: 3 // Higher to get slower videos, lower for faster videos [Value 1-100]
        }
    ]


If reporter is not added it is working fine.

**Comment by christian-bromann** [comment]
Can you create a mini project that reproduces this problem?

**Comment by praveenngp15** [comment]
Created sample project and pushed in below git [repo]([wdio-video-reporter-main.zip](https://github.com/webdriverio/webdriverio/files/8709101/wdio-video-reporter-main.zip))
https://github.com/praveenngp15/wdio-video-reporter.git

**Comment by christian-bromann** [comment]
Thanks, feel free to help us investigate this issue. Thank you!

**Comment by erwinheitzman** [comment]
I have investigated the issue and the problem lies in making screenshots in the afterCommand hook which closes the alert.

**Comment by christian-bromann** [comment]
Thanks for investigating @erwinheitzman 

I assume one option could be that the video reporter checks wether an alert is open and if so skips the `screenshot` command.

**Comment by erwinheitzman** [comment]
That would be a simple fix we could also look into other ways of creating videos

**Comment by christian-bromann** [comment]
Raised an issue within the video reporter. Any contributions are appreciated.
