### ISSUE TITLE
windowHandleMaximize fail

### ISSUE THREAD

**Issue by sean-hill** [webdriverio/webdriverio#836]
Hey there,

`windowHandleMaximize` works great testing on my local Mac machine, but when testing on my production linux server, it doesn't do anything, the screen just stays the same size.

Here's some info about what I did to test:

	# Commands

	.getViewportSize()
	.then(function(size){
		console.log('Initial window size:', size);
	})
	.windowHandleMaximize()
	.getViewportSize()
	.then(function(size){
		console.log('Maximized window size:', size);
	})

	# Logs

	17:42:42.566 INFO - Executing: [execute script: return (function () {
		return {
			screenWidth: Math.max(document.documentElement.clientWidth, window.innerWidth || 0),
			screenHeight: Math.max(document.documentElement.clientHeight, window.innerHeight || 0)
		};
	}).apply(null, arguments);, []])
	17:42:42.573 INFO - Done: [execute script: return (function () {
		return {
			screenWidth: Math.max(document.documentElement.clientWidth, window.innerWidth || 0),
			screenHeight: Math.max(document.documentElement.clientHeight, window.innerHeight || 0)
		};
	}).apply(null, arguments);, []]
	Initial window size: { width: 320, height: 439 }
	17:42:42.592 INFO - Executing: [maximise window])
	17:42:42.704 INFO - Done: [maximise window]
	17:42:42.714 INFO - Executing: [execute script: return (function () {
		return {
			screenWidth: Math.max(document.documentElement.clientWidth, window.innerWidth || 0),
			screenHeight: Math.max(document.documentElement.clientHeight, window.innerHeight || 0)
		};
	}).apply(null, arguments);, []])
	17:42:42.722 INFO - Done: [execute script: return (function () {
		return {
			screenWidth: Math.max(document.documentElement.clientWidth, window.innerWidth || 0),
			screenHeight: Math.max(document.documentElement.clientHeight, window.innerHeight || 0)
		};
	}).apply(null, arguments);, []]
	Maximized window size: { width: 320, height: 439 }

Let it be noted that I did call `.windowHandleSize(windowSize)` previous to these commands. I'm testing my mobile website, so I set the width and height to an iPhone, but after logging in to my site, I wanted to maximize the view to take a screenshot.

**Comment by christian-bromann** [comment]
Have you tried to use windowHandleSize to get back to a normal (desktop) resolution?

**Comment by sean-hill** [comment]
Hey @christian-bromann so I just  came up with my own solution :smile: I made a custom command:

	// Makes the window real big
	function makeWindowLarge() {
		return this.windowHandleSize({ width: 1280, height: 1080 });
	};

Works fine for me :smile:

**Comment by christian-bromann** [comment]
Nice :+1:
