### ISSUE TITLE
emit an error event after querying a non existing element

### ISSUE THREAD

**Issue by electricmonk** [webdriverio/webdriverio#838]
Hi,

The function event spec has an ignored test for emitting an error event after querying a non-existing element. The comment says that this doesn't work, but doesn't detail _why_.

https://github.com/webdriverio/webdriverio/blob/master/test/spec/functional/events.js#L60

Is there any way to get error events on these cases? I'd like to print the page source to logs.

**Comment by christian-bromann** [comment]
the event handler doesn't catch error from the webpage but from the node process. I guess I quarantined that to get a blue build and publish the package. Not sure why this happens though.

**Comment by christian-bromann** [comment]
I think I wouldn't consider this an issue anymore. With wdio and element as 1st citizen we allow to query for elements that are not available at execution time, e.g.

```js
// ...
someElementInPageObject: { get: function () { return $('#notExistingYet'); } },
// ...
```
and
```js
PageObject.someElementInPageObject.waitForExist();
PageObject.someElementInPageObject.click();
```

The test would pass if we add an error emit call to the [RequestHandler](https://github.com/webdriverio/webdriverio/blob/master/lib/utils/RequestHandler.js#L162-L169). But adding this will screw up the wdio testrunner logs.

**Comment by christian-bromann** [comment]
Closing this. Not finding an element is not necessary considered an error anymore. Even though the spec tells differently:

> return error with error code no such element.

It should still be possible to wait on elements as described above.
