### ISSUE TITLE
CCLA

### ISSUE THREAD

**Issue by KelseyBlodgett** [webdriverio/webdriverio#8389]
I am a Program Manager at Amazon and am trying to get a CCLA executed for an employee who would like to contribute. Unfortunately the EasyCLA system isn't compatible with how our legal department executes documents. Is it possible to send me an executable copy (the version you are allowed to download is not for signature) so that we can set up the CLA and allow our employees to contribute? 
Thanks

**Comment by christian-bromann** [comment]
If my suggestion above doesn't work for you please raise an issue at https://support.linuxfoundation.org/ and choose the LFX option.

**Comment by christian-bromann** [comment]
@KelseyBlodgett let me know if you have any further questions. Happy to assist. Will go ahead and close this issue though.

**Comment by KelseyBlodgett** [comment]
Sorry, I just saw this update. We have to have all our documents go through our legal department to approve and then they must send through our internal system to a specified signatory. The easyCLA system does not allow me to do this because I have to send it myself to the signatory and cannot send it through our legal system. I will open an issue with the linux foundation but it would be great if there was just an executable copy of the CLA available.
