### ISSUE TITLE
[🐛 Bug]: install for certain node versions fail after @wdio/* v7.20.0

### ISSUE THREAD

**Issue by lfalkner** [webdriverio/webdriverio#8419]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

16.3.0

### Mode

WDIO Testrunner

### What happened?

Upgrading from @wdio packages version `7.16.13` to the latest version, yarn install fails for node `16.3.0`. The same is reproducible on v`7.20.0`, as introduced in https://github.com/webdriverio/webdriverio/compare/v7.20.0...main

### What is your expected behavior?

Update to minor version of wdio should not break `yarn install`

### How to reproduce the bug.

Use node version `16.3.0`

Add version ^17.20.0 to package.json of @wdio/jasmine-framework (for example)

Yarn install will fail

### Relevant log output

```typescript
`error expect@28.1.1: The engine "node" is incompatible with this module. Expected version "^12.13.0 || ^14.15.0 || ^16.10.0 || >=17.0.0". Got "16.3.0"`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Please update your Node.js version from 16.3.0 to 16.10.0 or higher to fix this. This was introduced by the `expect` package requiring you to have Node.js installed with version 16.10.0 or higher.
