### ISSUE TITLE
xunit reporter limitations

### ISSUE THREAD

**Issue by austek-mdsol** [webdriverio/webdriverio#842]
Are there any limitations to xunit output.  I am getting a truncated XML file. file size is about 40Mb and last entries in the file is

```
GET http://127.0.0.1:4444/wd/hub/session/8cac1e93-1966-457a-896a-302b63a3381d/element/175/css/font-weight - {"sessionId":"8cac1e93-1966-457a-896a-302b63a3381d","status":0,"state":"success","value":"300","class":"org.openqa.selenium.remote.Response","hCode":399007869}
DELETE http://127.0.0.1:4444/wd/hub/session/8cac1e93-1966-457a-896a-302b63a3381d - {"sessionId":"8cac1e93-1966-457a-896a-302b63a3381d","status":0,"state":"success","value":null,"class":"org.openqa.selenium.remote.Response","hCode":1688878172}
]]></system-out>
```
If I disable some of the tests then the output is OK.

**Comment by christian-bromann** [comment]
wow. 40 MB is a lot. Not sure if we reach an limit here or if this is caused by a bad implementation pattern. I made an note in the [wdio-junit-reporter](https://github.com/webdriverio/wdio-junit-reporter) project and will tackle this later. Feel free to open a PR with a fix.
