### ISSUE TITLE
Cucumber 0.8.1 compatibility issue

### ISSUE THREAD

**Issue by MartinDelille** [webdriverio/webdriverio#843]
I have a strange bug that occurs only when *wdio* is ran from the local package when using the *cucumber* framework.

    $ node_modules/webdriverio/bin/wdio cucumber.conf.js
    
    My feature
    events.js:141
          throw er; // Unhandled 'error' event
          ^

    TypeError: stepResult.isSuccessful is not a function
        at CucumberReporter.handleStepResultEvent (/path/to/my/project/node_modules/webdriverio/lib/frameworks/cucumber.js:50:24)

    0 passing

If I run 'wdio' using the globally installed package, it works:

    $ wdio cucumber.conf.js
    
    My feature
      Checking the title
        - I am going to the website "http://localhost:9000"
        - I check the title
        - it is equal to "Pouet"

    0 passing (3.40s)
    3 pending

**Comment by MartinDelille** [comment]
I realized I had different *cucumber* version:

- local: 0.8.1
- global: 0.7.0

Forcing my local *cucumber* version to 0.7.0 fix the problem. The *cucumber* framework implementation seems to be outdated. The first problem come from this line:https://github.com/webdriverio/webdriverio/blob/master/lib/frameworks/cucumber.js#L50

**Comment by christian-bromann** [comment]
Thanks for pointing this out. We probably won't fix that in v3.x anymore but I created in issue in the [wdio-cucumber-framework](https://github.com/webdriverio/wdio-cucumber-framework/issues/1) project to address this update.

Thanks for reporting!
