### ISSUE TITLE
[🐛 Bug]: Event hook methods doesn't work!

### ISSUE THREAD

**Issue by JordiSAGE** [webdriverio/webdriverio#8435]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

v16.14.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
beforeSuite: () => {},
    beforeScenario: scenario => {},
    afterScenario: function (uri, feature, scenario, result, sourceLocation) {},
    afterStep: function (uri, feature, { error, result, duration, passed }, stepData, context) {},
    afterFeature: suite => {},
```

### What happened?

It seems that the code located in event hooks, as part of a typescript file, is not working anymore since we upgraded from version 7.19.4 to 7.20.2

### What is your expected behavior?

We expected the code from event hooks to be executed when upgraded to the latest version.

### How to reproduce the bug.
```typescript
import { After, AfterAll, AfterStep, Before, Status } from '@cucumber/cucumber';
import allureReporter from '@wdio/allure-reporter';
import { activeFunction } from '.';
import * as page from './page';

Before(async (scenario: any) => {
    await activeFunction.setLockEntryAfterRemoved(scenario.pickle.uri.split('\\').pop());
    console.log(`Starting scenario ${scenario.pickle.uri}:${scenario.pickle.name}`);
    // WE CALL PUPPETEER PAGE ON THIS CONTEXT
    // TO HAVE IT AVAILABLE IN NEXT INTERACTIONS
    await page.getPage();
    await browser.cdp('Page', 'setDownloadBehavior', {
        behavior: 'allow',
        downloadPath: process.env.downloadFolder,
    });
    console.log('**** BEFORE HOOK ****');
});

After(async (step: any) => {
    let featurePath = '';

    if ((process.env.MAX_INSTANCES as unknown as number) > 1 && step.result.status !== Status.PASSED) {
        featurePath = step.pickle.uri.split('\\').pop();
        console.log(`EXECUTION ERROR DETECTED, REMOVING LOCK ENTRIES FROM FEATURE: ${featurePath}`);
        await activeFunction.deleteByFeaturePath(featurePath);
    }
    if (step.result.status === Status.FAILED) {
        allureReporter.addAttachment('Screenshot', Buffer.from(await browser.takeScreenshot(), 'base64'), 'image/png');
    }
});

AfterStep(async (step: any) => {
    if (step.result.status === Status.FAILED) {
        allureReporter.addAttachment('Screenshot', Buffer.from(await browser.takeScreenshot(), 'base64'), 'image/png');
    }
    await browser.pause(200);
});

AfterAll(async () => {
    if ((process.env.MAX_INSTANCES as unknown as number) > 1) {
        console.log('DELETING BY FEATURE PATH: ' + (await activeFunction.getFeaturePath()));
        await activeFunction.deleteByFeaturePath(await activeFunction.getFeaturePath());
    }
});
```
### Relevant log output

```typescript
No output log generated.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Can you provide any error messages or details what you receive when you run the code? No critical changes have been made to the cucumber adapter that could be relevant to this. A minimal reproducible example would be also helpful.

**Comment by JordiSAGE** [comment]
Hi @christian-bromann

First, Thanks for your support.

You can check the issue by taking the auto-generated wdio project as a base and add the following file:
![image](https://user-images.githubusercontent.com/33693547/174830078-28f9ba67-5460-4a21-b680-f967fcb77f6c.png)
With this content:
```typescript
import { After, AfterStep, Before } from '@cucumber/cucumber';

Before(async (scenario: any) => {
    console.log('**** BEFORE HOOK ****');
});

After(async (step: any) => {
    alert('AFTER');
});

AfterStep(async (step: any) => {
    await browser.pause(200);
});
```
You will see that the before event console.log statement will not be displayed, preventingt any sentence located on it to be executed.
![image](https://user-images.githubusercontent.com/33693547/174830898-1517bb56-4a9d-4ce1-8cd2-aebd09df37c1.png)

Thanks again for your assistance.

**Comment by christian-bromann** [comment]
@JordiSAGE where is the `event-hooks.ts` referenced in the Cucumber config? I am not a Cucumber expert but the framework afaik doesn't pick up this file automatically, no?

**Comment by JordiSAGE** [comment]
Hi again @christian-bromann 
As far as I remember, it shouldn't be referenced in the wdio config in any way, and it was working this way until version 7.19.4

**Comment by christian-bromann** [comment]
@JordiSAGE can you create a minimal reproducible example?

**Comment by JordiSAGE** [comment]
Hi @christian-bromann 
You can reproduce the issue just using the WebdriverIO Starter Toolkit default project with the following configuration:
![image](https://user-images.githubusercontent.com/33693547/176122689-3bd5ad2b-6b75-4fb0-9372-4e53abc7116a.png)
Once generated, it's just a matter of creating the file /events/event-hooks,ts with the following content:
```typescript
import { After, AfterStep, Before } from '@cucumber/cucumber';

Before(async (scenario: any) => {
    console.log('**** BEFORE HOOK ****');
});

After(async (step: any) => {
    alert('AFTER');
});

AfterStep(async (step: any) => {
    await browser.pause(200);
});
```
And that's it.
Thanks again for your assistance!

**Comment by JordiSAGE** [comment]
Sorry, I forgot to add the file in the index.ts when I've refactorized it into a separate file, my bad!
