### ISSUE TITLE
[🐛 Bug]: Grouping Test suites To Run Sequentially throw an error filePath.match is not a function

### ISSUE THREAD

**Issue by igor-lantushenko** [webdriverio/webdriverio#8438]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v7.0.0

### Node.js Version

v15.14.0

### Mode

WDIO Testrunner

### What happened?

Docs said:
[Grouping Test Specs To Run Sequentially](https://webdriver.io/docs/organizingsuites#grouping-test-specs-to-run-sequentially)
Its possible to group selected tests to run sequentially:
```
    "suites": {
        end2end: [
            [
                "./test/specs/test_login.js",
                "./test/specs/test_product_order.js",
                "./test/specs/test_checkout.js"
            ]
        ],
        allb: ["./test/specs/test_b*.js"]
}
```

### What is your expected behavior?

I'm expecting to have single session for al selected tests.
However, I'm getting an error:
```sh
@wdio/cli (v7.0.0)

TypeError: filePath.match is not a function
    at Object.removeLineNumbers (/path/node_modules/@wdio/config/build/utils.js:41:30)
    at /path/node_modules/@wdio/config/build/lib/ConfigParser.js:277:52
    at Array.map (<anonymous>)
    at Function.getFilePaths (/path/node_modules/@wdio/config/build/lib/ConfigParser.js:277:29)
    at ConfigParser.getSpecs (/path/node_modules/@wdio/config/build/lib/ConfigParser.js:187:65)
    at /path/node_modules/@wdio/cli/build/launcher.js:42:47
    at Array.map (<anonymous>)
    at new Launcher (/path/node_modules/@wdio/cli/build/launcher.js:42:18)
    at launch (/path/node_modules/@wdio/cli/build/commands/run.js:124:22)
    at Object.handler (/path/node_modules/@wdio/cli/build/commands/run.js:163:16)
```

### How to reproduce the bug.

To reproduce the bug, create suites structure like:
```js
 "suites": {
        end2end: [
            [
                "./test/specs/test_login.js",
                "./test/specs/test_product_order.js",
                "./test/specs/test_checkout.js"
            ]
        ],
        allb: ["./test/specs/test_b*.js"]
},
```

Launch wdio like:
```js
wdio  --suite makers
```
### Relevant log output

```typescript
@wdio/cli (v7.0.0)

TypeError: filePath.match is not a function
    at Object.removeLineNumbers (/path/node_modules/@wdio/config/build/utils.js:41:30)
    at /path/node_modules/@wdio/config/build/lib/ConfigParser.js:277:52
    at Array.map (<anonymous>)
    at Function.getFilePaths (/path/node_modules/@wdio/config/build/lib/ConfigParser.js:277:29)
    at ConfigParser.getSpecs (/path/node_modules/@wdio/config/build/lib/ConfigParser.js:187:65)
    at /path/node_modules/@wdio/cli/build/launcher.js:42:47
    at Array.map (<anonymous>)
    at new Launcher (/path/node_modules/@wdio/cli/build/launcher.js:42:18)
    at launch (/path/node_modules/@wdio/cli/build/commands/run.js:124:22)
    at Object.handler (/path/node_modules/@wdio/cli/build/commands/run.js:163:16)
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@igor-lantushenko thanks for filing the issue.

WebdriverIO doesn't support grouping suites as you did above. If you like to run them sequentially just define them as

```js
 "suites": {
        end2end: [
            "./test/specs/test_login.js",
            "./test/specs/test_product_order.js",
            "./test/specs/test_checkout.js"
        ],
        allb: ["./test/specs/test_b*.js"]
},
```

and set `maxInstances` to `1`.

That said, I believe it makes sense to build support for this. Therefor any contributions that implement this enhancements are very welcome. We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by igor-lantushenko** [comment]
@christian-bromann thank you for the answer. 
Looks like docs need to be updated before this feature gets implemented. 
Important part for me was: `will be run sequentially in a single instance`
We are running tests in sauce labs and have only 1 device available. Each spec takes around 30 seconds of waiting time till device is ready. We wanted to reduce time and have single session between specs.

**Comment by christian-bromann** [comment]
> Looks like docs need to be updated before this feature gets implemented.

Which part needs to get updated and what update would you suggest?

> Important part for me was: `will be run sequentially in a single instance`

Not sure what you mean by that. Yes, grouping specs as you want to do would avoid spawning new sessions after every test.

**Comment by igor-lantushenko** [comment]
@christian-bromann but here is a doc: https://webdriver.io/docs/organizingsuites#grouping-test-specs-to-run-sequentially

**Grouping Test Specs To Run Sequentially:**
As described above, there are benefits in running the tests concurrently. However, there are cases where it would be beneficial to group tests together to run sequentially in a single instance. Examples of this are mainly where there is a large setup cost e.g. transpiling code or provisioning cloud instances, but there are also advanced usage models that benefit from this capability.

To group tests to run in a single instance, simply define them as an array within the specs definition.

    "specs": [
        [
            "./test/specs/test_login.js",
            "./test/specs/test_product_order.js",
            "./test/specs/test_checkout.js"
        ],
        "./test/specs/test_b*.js",
    ],

In the example above, the tests 'test_login.js', 'test_product_order.js' and 'test_checkout.js' will be run sequentially in a single instance and each of the "test_b*" tests will run concurrently in individual instances.

Maybe I'm getting it wrong and miss something?

**Comment by christian-bromann** [comment]
> Maybe I'm getting it wrong and miss something?

Can you explain how you understand it and what suggestion/changes you would suggest?

**Comment by igor-lantushenko** [comment]
@christian-bromann I'm just suggesting to remove nested array example from documentation (for both `specs` and `suites`) until its done

**Comment by christian-bromann** [comment]
> I'm just suggesting to remove nested array example from documentation (for both `specs` and `suites`) until its done

For `specs` this functionality is working but not for `suites`.

**Comment by igor-lantushenko** [comment]
@christian-bromann but it does not work for `specs` as well, same error

**Comment by christian-bromann** [comment]
Can you provide a minimal reproducible example?

**Comment by igor-lantushenko** [comment]
@christian-bromann  found out the root cause, I had old and different versions: 
```
"@wdio/cli": "7.0.0",
"@wdio/local-runner": "^7.9.0",
"@wdio/mocha-framework": "^7.9.0",
```
and with this setup - I got that error,
after updating the stuff:
```
@wdio/cli": "^7.20.5",
"@wdio/local-runner": "^7.20.5",
"@wdio/spec-reporter": "^7.20.3",
```
Now it is working well, thanks for your time!

**Comment by christian-bromann** [comment]
@igor-lantushenko does it work for both, suite definition and specs?

**Comment by igor-lantushenko** [comment]
@christian-bromann yeap , no problem here, just version mismatch

**Comment by NaZaRKIN123** [comment]
Hi all,

Seems like it doesn't work with TS. I see the next error:
<img width="871" alt="image" src="https://user-images.githubusercontent.com/19157402/199724659-ecf16582-dc68-4785-ba04-56bd946701bf.png">
