### ISSUE TITLE
[🐛 Bug]: Make `releaseAction` call within `click` command optional

### ISSUE THREAD

**Issue by 0xbaddaddee** [webdriverio/webdriverio#8440]
### Have you read the Contributing Guidelines on issues?

- [x] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

6.14.15

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    browserName: 'firefox',
    browserVersion: '101.0.1',
}
```

### What happened?

[This page ](https://the-internet.herokuapp.com/context_menu) contains a box that will trigger a JavaScript alert when right-clicking in it. After accepting the alert, the actual context menu appears, as seen in the attachment image. However, performing a right-click with WebdriverIO 'click' method causes the alert to disappear really quickly, thus never being able to retrieve the alert text with `browser.getAlertText()`.  Instead, using dispatchEvent call on the element does not lead to the alert disappearing.

![image](https://user-images.githubusercontent.com/63643369/174588408-7969ff96-097e-444b-bcad-1e292f681cc0.png)

### What is your expected behavior?

The right-clicking action should perform the same output as if done manually.

### How to reproduce the bug.

```ts
describe('Context Menu Test', () => {
    it ('should alert on right click', async() => {
        await browser.url('https://the-internet.herokuapp.com/context_menu')
        await browser.$('#hot-spot').click( { button: 2 } )

        // However, this keeps the alert visible until accepted or dismissed.

        /*await browser.$('#hot-spot').$(function() {
            (this as HTMLElement).dispatchEvent(new Event('contextmenu'))
        })*/

        const alertText = await browser.getAlertText();
        await browser.acceptAlert();
        expect(alertText).toBe('You selected a context menu')
    })
})
```

### Relevant log output

```typescript
[0-0] RUNNING in firefox - C:Users\me\webdriverio-getting-started\test\specs\contextmenu.spec.ts
[0-0] 2022-06-20T11:14:40.275Z ERROR webdriver: Request failed with status 404 due to no such alert: unknown error
[0-0] Error in "Context Menu Tests should alert on right click"
no such alert: unknown error
    at async UserContext.<anonymous> (C:\Users\me\webdriverio-getting-started\test\specs\contextmenu.spec.ts:10:27)
[0-0] FAILED in firefox - C:\Users\me\webdriverio-getting-started\test\specs\contextmenu.spec.ts
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@0xbaddaddee thanks for raising the issue.

The problem is that WebdriverIO releases the action which causes the alert to disappear again. This issue is similar to https://github.com/webdriverio/webdriverio/issues/6423#issuecomment-881573423 where I already suggested to make the [`releaseAction` call](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/element/click.ts#L136-L138) optional.

I think this is a great first contribution and I am happy to help if you'ld like to take a stab at it.

**Comment by praveendvd** [comment]
@christian-bromann just eager to know why we are using webdriver actions instead of click ? https://www.w3.org/TR/webdriver/#element-click

**Comment by christian-bromann** [comment]
@praveendvd because the webdriver click command doesn't allow to set an offset nor the mouse button, so it is very limited.

You like to take a stab at this?

**Comment by praveendvd** [comment]
@christian-bromann sure christian , was thinking should we use webdriver.click in normal case and for everything else use action . Or we just need to add a parameter to make releaseaction optional ?

**Comment by christian-bromann** [comment]
> Or we just need to add a parameter to make releaseaction optional ?

As mentioned above we should add an option to `ClickOptions`, named maybe `skipRelease` that if set to true skips the [`releaseAction` call](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/element/click.ts#L136-L138).

**Comment by praveendvd** [comment]
@christian-bromann  hi christian i accidentally added the commit to main , i reverted it . will create a separate branch

**Comment by christian-bromann** [comment]
Let's continue convo in #8465, thanks for taking a stab at it @praveendvd
