### ISSUE TITLE
driver.keys('Shift') is not working with IE11

### ISSUE THREAD

**Issue by tridalpatel** [webdriverio/webdriverio#845]
I want to hold shift key and want to click on multiple columns as a part of my task.
To achieve about action, I am using driver.keys('Shift') command to hold shift key and it is working perfectly fine with Firefox and chrome. However, I am facing problem with IE11 and cannot hold shift key using the same command driver.keys('Shift').

Would you please let me know that what should I do to hold shift key in IE11?

IE11 Version : 11.0.20

Thanks in advance.

**Comment by christian-bromann** [comment]
This seems to not be an issue of WebdriverIO. The iedriver doesn't work properly here. I can't think of any way to build workaround to make this working in IE11. That's why I gonna close this issue. You can try to file this issue in the iedriver project.

**Comment by fogrizovic** [comment]
Hi all, 
Just wanted to share a custom command that i´m using as an alternative to browser.keys() which works with Chrome and Internet Explorer. I have taken some information from [this post](https://stackoverflow.com/questions/44339046/browser-keys-is-not-working-on-firefox-53-0-webdriver-io)  
```
browser.addCommand("keys_", function (keys) {
        var result = browser.elementActive()
        if (result.value) {
            var activeElement = (browserName == 'internet explorer') ? Object.values(result.value)[0] : result.value.ELEMENT
            browser.elementIdValue(activeElement, keys)
        }
    })
```
