### ISSUE TITLE
v2 command chaining not working in v3.x and `.debug` not stopping the command queue

### ISSUE THREAD

**Issue by cdaringe** [webdriverio/webdriverio#846]
Hi all,

I read the docs for the v3 release, however I'm experiencing an issue where commands are not run in their expected order.  For example:

```js
// main.js
var client = require('./client.js').client; // get client singleton
var nav    = require('./nav')(client);      // our nav utility uses the _same_ client

client.url(url);
client.waitForExist('#blah').url('... some other url ...');
return nav.doSomethingAfter();
```

```js
// nav.js
module.exports = function(client) {
    return {
        doSomethingAfter: function() {
            return client.execute(function() {
                window.alert('weve navigated to "some other url" by now');
             });
        }
    };
};
```

However, I'm seeing that _nav.doSomethingAfter_ is actually executing the browser code before the client browses to `'some other url'`.  This is unexpected.  Previously commands would chain in the order called.

Suppose I modify main.js to do add many `.call`s:

```js
// main.js
var client = require('./client.js').client; // get client singleton
var nav    = require('./nav')(client);      // our nav utility uses the _same_ client

client.url(url);
client.
    .call(function() { debugger; })
    .call(function() { debugger; })
    .waitForExist('#blah').url('... some other url ...');
return nav.doSomethingAfter();
```

and nav.js add a `.debug()` call:

```js
// nav.js
module.exports = function(client) {
    return {
        doSomethingAfter: function() {
            return client.debug().execute(function() { // note the addition of the `debug()` call
                window.alert('hopefully, weve navigated to "some other url" by now');
             });
        }
    };
};
```

In running this:

1. I get to the first `debugger;` before `nav.doSomethingAfter()`'s `.execute()` called.
1. Again, unexpectedly, doSomethingAfter's `.debug()` and `.execute()` are called next
1. Even stranger, the `.debug()` call does not stop the command queue.  I can hit play in my debugger and make it to the second  `.call(function() { debugger; })` even when my terminal says I'm in debug mode and the queue has stopped.

I tried to be verbose for clarity!  Please let me know if I omitted key details.

Thanks!

-Chris

<img width="916" alt="screen shot 2015-10-27 at 12 03 28 pm" src="https://cloud.githubusercontent.com/assets/1003261/10769562/f5036ab8-7ca3-11e5-87c5-c0789020e0b9.png">

**Comment by christian-bromann** [comment]
First of all, this:
```js
client.url(url);
client.waitForExist('#blah').url('... some other url ...');
return nav.doSomethingAfter();
```
doesn't work anymore with v3. Commands don't get executed synchronously anymore. They now return a promise. You need to chain your commands and return have to return a command queue.

Secondly: the debugger feature of node isn't really working with WebdriverIO either. I haven't been working on any integration for this since you rarely debug node stuff and are more concerned about everything that happens in the browser. That's why we have the debug command to be able to stop the queue and open dev tools in the browser.

**Comment by cdaringe** [comment]
Thanks christian.  I will consider your points and try and move forward!
