### ISSUE TITLE
[💡 Feature]: add option to spec reporter - "successesFailuresAfterRetries: false"

### ISSUE THREAD

**Issue by pinim** [webdriverio/webdriverio#8460]
### Is your feature request related to a problem?

no, it's only addition i think should good to exist.

### Describe the solution you'd like.

as a developer, when i saw test fails, it can confusing me, so , i think, if test passes after retry, it will be great to remove it from the failure results.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
@pinim can you verify if this is solution you are suggesting?

**Comment by vmwhereqa** [comment]
@christian-bromann : I will take this up

**Comment by christian-bromann** [comment]
Any updates @vmwhereqa ?

**Comment by tamil777selvan** [comment]
Closing this as it's been fixed in #11168
