### ISSUE TITLE
[📖 Docs]: Add information that mock commands are only working for local tests

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#8467]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Missing documentation

### Description of the improvement / report

On pages like https://webdriver.io/docs/api/mock/abort we should show an informational banner saying that these commands are only supported when run locally.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esaari** [comment]
Would this still be true if run against an endpoint that has the CDP endpoint exposed, i.e. Selenium Grid 4? The work done in this PR: https://github.com/webdriverio/webdriverio/pull/6508 should support that, correct?

**Comment by christian-bromann** [comment]
Correct, if a CDP socket is exposed all the commands work.

**Comment by esaari** [comment]
I confirmed I was able to get devtools/mock service working on Selenium Grid as long as the requisite env var is set properly: https://github.com/SeleniumHQ/docker-selenium#grid-url-and-session-timeout, so there is now alternative to running locally :)
