### ISSUE TITLE
Sauce labs job not updated when host set to localhost because using sauce connect

### ISSUE THREAD

**Issue by juliepagano** [webdriverio/webdriverio#848]
I am currently working on using webdriver.io to set up some integration tests with sauce labs using sauce connect. I have my host set to localhost and port set to 4445 per the defaults for sauce connect. The tests run properly, but the job is not being updated with the status at the end.

It looks like the issue is with the line below. The code only attempts to update the job when the host includes "saucelabs" which won't happen when hitting localhost with sauce connect.

https://github.com/webdriverio/webdriverio/blob/master/lib/runner.js#L166

Is updateJob used for any of the other services that webdriver.io uses? If not, would it be sufficient to remove the host check here (if so, I'll work on making a pull request). If that isn't a good solution, any suggestions for modifying this to be more flexible and work for the sauce connect localhost case?

**Comment by christian-bromann** [comment]
@juliepagano thanks for your issue request!

This will get easier once we introduce service plugins with v4. For now I guess it is ok to remove the host check. Since all jobs not running on saucelabs would fail I would suggest to ignore the error of that request (or ignore it only if the job wasn't found).

**Comment by juliepagano** [comment]
Thanks for the quick response! I'll work on a pull request some time in the next day or so. 

I took a quick look through the functional tests earlier and didn't see an obvious test for this code path. I saw some sauce labs job updates in test/runner.js, but looks like that is probably related to the webdriver.io tests themselves updating saucelabs when they run on TravisCI. Should I be looking somewhere else or is this bit of code untested? If untested, should I add a test as part of the pull request?

**Comment by christian-bromann** [comment]
@juliepagano we don't have an actual e2e test for that. If you want to open a PR feel free to add one but I don't expect one as this kind of functionality will be removed soon and ported into a service module where it get's tested. So it's up to you.
