### ISSUE TITLE
ReferenceError: browser is not defined

### ISSUE THREAD

**Issue by yohainnn** [webdriverio/webdriverio#8480]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.3.2

### Node.js Version

16.15.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
 browserName: 'chrome'
 browserVersion: 'latest'
 platformName: 'MacOS High Sierra'
}
```

### What happened?

1. I have followed the wizard terminal installation (chose mocha framework)
2. I specified the mocha package in webstorm's  edit configuration (wasn't in any doc btw, had to look for the issue somewhere else).
3. I have ran the first example test provided by wdio and received an error `ReferenceError: browser is not defined`

This is the test code provided by wdio as an example first test:
```
describe('My Login application', () => {
    it('should login with valid credentials', async () => {
        await browser.url(`https://the-internet.herokuapp.com/login`);

        await $('#username').setValue('tomsmith');
        await $('#password').setValue('SuperSecretPassword!');
        await $('button[type="submit"]').click();

        await expect($('#flash')).toBeExisting();
        await expect($('#flash')).toHaveTextContaining(
            'You logged into a secure area!');
    });
});
```
this is the package.json:
```
{
    "name": "webdriverio-tests",
    "version": "0.1.0",
    "private": true,
    "devDependencies": {
        "@wdio/cli": "^7.20.5",
        "@wdio/local-runner": "^7.20.5",
        "@wdio/mocha-framework": "^7.20.3",
        "@wdio/spec-reporter": "^7.20.3",
        "chromedriver": "^103.0.0",
        "wdio-chromedriver-service": "^7.3.2"
    },
    "scripts": {
        "wdio": "wdio run wdio.conf.js"
    }
}
```

### What is your expected behavior?

expected the test to run

### Relevant log output

```typescript
ReferenceError: browser is not defined
    at Context.<anonymous> (test/specs/example.e2e.js:3:9)
    at processImmediate (node:internal/timers:466:21)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@yohainnn how did you run the test?
