### ISSUE TITLE
wdio-slack-service does not send notification on test failure

### ISSUE THREAD

**Issue by vivekkurhe05** [webdriverio/webdriverio#8485]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.20.5

### Node.js Version

v16.13.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
services: [
    "chromedriver",
    [
      slack,
      {
        webHookUrl: SLACK_WEBHOOK_URL, // Used to post notification to a particular channel
        notifyOnlyOnFailure: true, // Send notification only on test failure
        messageTitle: "Test summary report", // Name of the notification
      },
    ],
  ],
```

### What happened?

I want to send test report on slack channel with total tests passed, failed and skipped. I installed the "wdio-slack-service " dependency.  I am getting notification with notification summary when my test passed. But on failure I did not get any notification nor did I find any summary on slack channel even when the **`notifyOnlyOnFailure`** parameter is set to true.

### What is your expected behavior?

I should get slack notification report on test failure.

### How to reproduce the bug.

1. Setup wdio on your machine
2. Install wdio-slack-service
3. Get a webhook url
4. Modify your test with intent to failing it.
5. Run your test

### Relevant log output

```typescript
"spec" Reporter:
------------------------------------------------------------------
[chrome 103.0.5060.53 mac os x #0-0] Running: chrome (v103.0.5060.53) on mac os x
[chrome 103.0.5060.53 mac os x #0-0] Session ID: 0d710ac8ab883632343ee9c254301ddb
[chrome 103.0.5060.53 mac os x #0-0]
[chrome 103.0.5060.53 mac os x #0-0] » /test/specs/example.e2e.js
[chrome 103.0.5060.53 mac os x #0-0] My Login application
[chrome 103.0.5060.53 mac os x #0-0]    ✖ should login with valid credentials
[chrome 103.0.5060.53 mac os x #0-0]
[chrome 103.0.5060.53 mac os x #0-0] 1 failing (23.4s)
[chrome 103.0.5060.53 mac os x #0-0]
[chrome 103.0.5060.53 mac os x #0-0] 1) My Login application should login with valid credentials
[chrome 103.0.5060.53 mac os x #0-0] Expect $(`#flash`) to have text containing

- Expected  - 1
+ Received  + 2

- You logged into a insecure area!
+ You logged into a secure area!
+ ×
[chrome 103.0.5060.53 mac os x #0-0] Error: Expect $(`#flash`) to have text containing
[chrome 103.0.5060.53 mac os x #0-0]
[chrome 103.0.5060.53 mac os x #0-0] - Expected  - 1
[chrome 103.0.5060.53 mac os x #0-0] + Received  + 2
[chrome 103.0.5060.53 mac os x #0-0]
[chrome 103.0.5060.53 mac os x #0-0] - You logged into a insecure area!
[chrome 103.0.5060.53 mac os x #0-0] + You logged into a secure area!
[chrome 103.0.5060.53 mac os x #0-0] + ×
[chrome 103.0.5060.53 mac os x #0-0]     at Context.<anonymous> (/Users/launchventures/webdriverio-web/test/specs/example.e2e.js:10:41)
[chrome 103.0.5060.53 mac os x #0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)


Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:27 

2022-07-02T13:56:12.817Z INFO @wdio/local-runner: Shutting down spawned worker
2022-07-02T13:56:13.069Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2022-07-02T13:56:13.069Z INFO @wdio/local-runner: shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@vivekkurhe05 thanks for reporting.

Unfortunately there is nothing that can be fixed about this within the core WebdriverIO repository. I recommend to report this problem in the [slack reporter project](https://github.com/kmnaid/wdio-slack-reporter) thanks.
