### ISSUE TITLE
ES6 Generator Issue

### ISSUE THREAD

**Issue by onewithhammer** [webdriverio/webdriverio#849]
I'm unable get ES6 Generator example to work.

Please see the following Gist:

https://gist.github.com/onewithhammer/be9f9b7af0bd0f2b49f7

My environment is:
```
Tonys-MacBook-Pro:Tutorial tkeith$ node --version
v4.2.1
Tonys-MacBook-Pro:Tutorial tkeith$ npm view webdriverio version
3.2.5
Tonys-MacBook-Pro:Tutorial tkeith$ npm view mocha version
2.3.3
```

**Comment by christian-bromann** [comment]
What node/WebdriverIO version are you using?

**Comment by onewithhammer** [comment]
@christian-bromann - any update on this?

**Comment by christian-bromann** [comment]
ES6 generator support is only supported if you used wdio. The Mocha testrunner doesn't support this!
