### ISSUE TITLE
[🐛 Bug]: error in downloading selenium-standalone - Error in "getDownloadStream"

### ISSUE THREAD

**Issue by VitaliLebedzeu** [webdriverio/webdriverio#8501]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [{
        browserName: chrome,
        acceptInsecureCerts: true,
        'goog:chromeOptions': {
            w3c: false,
            args: [
                '--incognito',
                `--window-size=${variables.defaultWidth},${variables.defaultHeight}`,
                '--disable-dev-shm-usage',
                '--disable-gpu',
                '--no-sandbox',
                '--headless'
            ],
            'excludeSwitches': ['enable-automation']
        }
    }],
```

### What happened?

The selenium-standalone service couldn't be downloaded because of the broken URL

This issue was solved in the  [selenium-standalone](https://github.com/webdriverio/selenium-standalone/issues/653). 
Essential to update the version of the selenium-standalone to 8.0.11 or above.

### What is your expected behavior?

selenium should be downloaded without any issues.

### How to reproduce the bug.

`services: [
        ['selenium-standalone', {
            logPath: `${variables.outputDir}/selenium`,
            installArgs: {
                version: '3.9.1',
                baseURL: 'https://selenium-release.storage.googleapis.com',
                drivers: {
                    chrome: {
                        version: 'latest'
                    }
                }
            },
            args: {
                drivers: {
                    version: '3.9.1',
                    chrome: {
                        version: 'latest'
                    }
                }
            }
        }]
    ],`

### Relevant log output

```typescript
Error in "getDownloadStream". Could not download https://selenium-release.storage.googleapis.com/selenium-3.9.1/selenium-server-standalone-3.9.1.jar
See more details below:
404 https://selenium-release.storage.googleapis.com/selenium-3.9.1/selenium-server-standalone-3.9.1.jar
Response code 404 (Not Found)
/app/node_modules/.store/selenium-standalone-npm-8.1.4-9268f2fb8b/node_modules/selenium-standalone/lib/install.js:292
          throw new Error('Could not download ' + downloadUrl);
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> Essential to update the version of the selenium-standalone to 8.0.11 or above.

Please update your dependencies then. The `selenium-standalone` dependency is defined as `"selenium-standalone": "^8.0.3"` so it should get you that version when you install it.

**Comment by VitaliLebedzeu** [comment]
@christian-bromann this issue happens because of the old baseURL described in the documentation. Selenium-standalone doesn't use it anymore. I've created a PR for fixing documentation [#8502](https://github.com/webdriverio/webdriverio/pull/8502)

**Comment by christian-bromann** [comment]
Cheers for the doc update!
