### ISSUE TITLE
[📖 Docs]: document `autoCompileConfig`

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#8519]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Missing documentation

### Description of the improvement / report

It seems that `autoCompileConfig` is no where documented. We should update this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by erwinheitzman** [comment]
Is this about `autoCompileOpts` as I am not aware of any `autoCompileConfig`?

**Comment by christian-bromann** [comment]
Yes, you are right, see I got confused about this and was wondering why we don't have docs for this.

**Comment by christian-bromann** [comment]
Actually we have them [here](https://webdriver.io/docs/typescript/#configuration) but these are testrunner options and should also documented [here](https://webdriver.io/docs/options).
