### ISSUE TITLE
[🐛 Bug]: appium resetApp command refers to non-existent appium endpoint

### ISSUE THREAD

**Issue by jlipps** [webdriverio/webdriverio#8523]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

Standalone Mode

### What happened?

`appium.json` has these lines defining the resetApp command:

```
  "/session/:sessionId/appium/app/resetApp": {
    "POST": {
      "command": "resetApp",
      "description": "Reset the currently running app for this session.",
      "ref": "http://appium.io/docs/en/commands/device/app/reset-app/",
      "parameters": [],
      "support": {
        "ios": {
          "XCUITest": "9.3+",
          "UIAutomation": "8.0 to 9.3"
        },
        "android": {
          "UiAutomator": "4.2+"
        }
      }
    }
  },
```

but the route should be `/session/:sessionId/appium/app/reset`.

we should probably also mark this deprecated since the feature is also deprecated in Appium.

### How to reproduce the bug.

n/a

### Relevant log output

```typescript
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Oh I think this was a missunderstanding as in #6977 someone pointed out that WebdriverIOs command naming wasn't consistent so in https://github.com/webdriverio/webdriverio/pull/7002 we introduced `resetApp` but it didn't point to the same route. I will fix this and mark it as deprecated.

**Comment by jlipps** [comment]
awesome thanks!
