### ISSUE TITLE
[🐛 KY]: Last update breaks node12 support

### ISSUE THREAD

**Issue by aleffeh** [webdriverio/webdriverio#8526]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v7.20.6

### Node.js Version

12.22.8

### Mode

Standalone Mode

### What happened?

Our app had the webdriverio package installed, since the last release (v7.20.6) it broke compatibility with node 12.
What happened is that the KY lib updated and broke compatibility.
The curious fact is that the webdriverio lib doesn't use explicitly this lib

commit with the breaking changes from KY lib.
https://github.com/sindresorhus/ky/commit/e557973db906cb74cc61cc7fcbf06e81b3a44e5c

we solved the issue by removing the `^` from package json. Using the webdriverio v7.20.5 manually.
For lib maintainers, please check wich lib that is depending on ky and lock its version, or bump the minimum node version to 14.x

### How to reproduce the bug.

Last release break the nodejs 12 compatibility layer

### Relevant log output

```typescript
Last release break the nodejs 12 compatibility layer
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Unfortunately it seems that `ky` (which allows to run the `webdriver` package in the browser) doesn't use semver which is why I didn't notice this breaking change. I pushed a commit to pin the version back to `v.0.30.0`.
