### ISSUE TITLE
[🐛 Bug]: getContexts() can also return an array of objects

### ISSUE THREAD

**Issue by magbauti** [webdriverio/webdriverio#8540]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.20.05

### Node.js Version

16.13.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
		platformName: 'iOS',
		maxInstances: 1,
		'appium:deviceName': 'iPhone 11 Pro Max',
		'appium:platformVersion': '15.5',
		'appium:orientation': 'PORTRAIT',
		'appium:automationName': 'XCUITest',
		'appium:app':
			'....Build/Products/Debug-iphonesimulator/App.app',
		'appium:newCommandTimeout': 240,
		'appium:autoWebview': true,
		'appium:noReset': false,
		'appium:clearSystemFiles': true,
		'appium:fullContextList': true,
	},
```

### What happened?

When printing out a list of contexts via the `driver.getContexts()` method, we get the expected string array of:
```
['NATIVE_APP', 'WEBVIEW_1', 'WEBVIEW_2']
```

However, when I enable the `'appium:fullContextList': true` capability, the `getContexts()` method does not return a `string[]` but instead returns an array of objects.

When I print out the contexts, I get something like this:

```
[{ id: 'NATIVE_APP' },
{
id: 'WEBVIEW_37228.6',
title: 'Error',
url: 'https://some-auth-url',
bundleId: 'com.apple.SafariViewService'
},
 {
 id: 'WEBVIEW_42053.1',
title: 'MY APP',
url: 'capacitor://localhost',
bundleId: 'com.my.app'
}]
```

Would it be possible to update the return type of `getContexts()` method to something like: 

```js
getContexts(): string[] | {id:string; title?:string; url?:string; bundleId?:string}[] {...} 
```

### What is your expected behavior?

I expected the array of objects, but I am getting type errors in my tests due to the return type expecting a `string[]` but instead I get an array of objects.

For now I am casting the return value in order to use it:

```ts
const fullContextList = (await driver.getContexts()) as unknown as {
		id: string;
		title?: string;
		url?: string;
		bundleId?: string;
	}[];
```

### How to reproduce the bug.

The bug can be reproduced by enabling and disabling

```
'appium:fullContextList': true,
```

### Relevant log output

```typescript
Here is the driver.getContexts() output when `fullContextList` is set to `true`:


[{ id: 'NATIVE_APP' },
{
id: 'WEBVIEW_37228.6',
title: 'Error',
url: 'https://some-auth-url',
bundleId: 'com.apple.SafariViewService'
},
 {
 id: 'WEBVIEW_42053.1',
title: 'MY APP',
url: 'capacitor://localhost',
bundleId: 'com.my.app'
}]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> Would it be possible to update the return type of `getContexts()` method to something like:

Yes, for that you would need to define a custom type [here](https://github.com/webdriverio/webdriverio/blob/main/scripts/type-generation/webdriver-return-types.json) and define that new custom return type [here](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-protocols/src/types.ts).

Would you like to take a stab at it?

We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by magbauti** [comment]
> > Would it be possible to update the return type of `getContexts()` method to something like:
> 
> Yes, for that you would need to define a custom type [here](https://github.com/webdriverio/webdriverio/blob/main/scripts/type-generation/webdriver-return-types.json) and define that new custom return type [here](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-protocols/src/types.ts).
> 
> Would you like to take a stab at it?
> 
> We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

Oh yeah, sure! I'll give it a try, thanks 👍🏼

**Comment by christian-bromann** [comment]
Raised an PR in #8692, any review would be appreciated.
