### ISSUE TITLE
Dropdown list click each and wait

### ISSUE THREAD

**Issue by syck40** [webdriverio/webdriverio#856]
This is similar to issue #429.  I want to:
1. Click first item in the dropdown list.
2. Submit.
3. When new page loads verify something on it.
4. Hit back.
5. Go to the next item on the dropdownlist and repeat.

I used addCommand as you guys suggested.  Here is what I have:
```js
client
.addCommand('clickAndVerify', function(checkbox, index, done) {
    client
        .elementIdClick(checkbox.ELEMENT).then(function(){
            client.click('#wucSearch_btnImageSubmit')
            .pause(500)
            .getHTML('#profile',function(err,html){
                    console.log('html is '+html);
            }).back()
        });
});

client
.init()
.url('http://blahblah/')
.elements('#wucSearch_ddlConference option', function(err,res){
    res.value.forEach(function(elem){
            client.clickAndVerify(elem, function(err,ress){
                console.log(ress)
            });
        });
})
```
The problem I have is the test would run through the dropdown list super fast and only runs clickAndVerify function at the very last item.  Also any pause or wait action I put inside clickAndVerify doesn't seem to do anything.  Thanks for help.

**Comment by gitLuigi** [comment]
My guess is in your `.elements` and `forEach` part of your callback where the client is not returned that is causing timing issue.
Here's a nice article about how it works:
pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html

If not, maybe because `.pause(500)` is not long enough?
Try using `.waitUntil()` or `.waitForVisible()` or something similar.

**Comment by christian-bromann** [comment]
What WebdriverIO version are you using?

**Comment by syck40** [comment]
version 3.2.6

**Comment by christian-bromann** [comment]
In v3 WebdriverIO is based on promises. You are seeing such behaviour because `clickAndVerify` can't tell when all the async commands are finished. You need to make sure that you always return the promise queue. See http://webdriver.io/guide/usage/customcommands.html for more information.
