### ISSUE TITLE
[🐛 Bug]: Empty JUnit report on async describe

### ISSUE THREAD

**Issue by bvincent** [webdriverio/webdriverio#8572]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.16

### Node.js Version

14.18.1

### Mode

WDIO Testrunner

### What happened?

When using a describe with a async function, JUnit report file is generated but not content is provided in the file.

 "@wdio/junit-reporter": "^7.16.15"
  
Framework used "mocha"

### What is your expected behavior?

Should be able to used async describe and reporter. Or maybe errors & documentation if it is not supported.

### How to reproduce the bug.

Configure junit as reporter then create a test like:

```js
describe('My async describe',  async () => { // <============ This is the problem
    const page = await buildPage(); //Async call for init 

    it("My test", async () => {
        await page.section.header.title.has.value("test"); // Assertion example
    });
});
```
 Run the test and open junit report. The file should be empty.

### Relevant log output

```typescript
No error has been raised.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> Framework used "mocha"

Mocha doesn't allow async describe blocks. They are also not necessary as you can just use hooks:

```js
describe('My async describe',  () => {
    let page
    before(async () => {
        page = await buildPage();
    })

    it("My test", async () => {
        await page.section.header.title.has.value("test"); // Assertion example
    });
});
```
