### ISSUE TITLE
[🐛 Bug]: iOS Predicate String Selector Throws 'InvalidSelectorStrategy", Even Though It Works

### ISSUE THREAD

**Issue by samuelfreiberg** [webdriverio/webdriverio#8574]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

6.5

### Node.js Version

14.20

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
      platformName: 'mac',
      automationName: 'Mac2',
      bundleId: 'testapp.bundle',
}
```

### What happened?

I'm using WebDriverIO/Appium to automated testing on a Mac application. I'm attempting to use the iOS Predicate String selector, which is integrated fully with Appium and the [Mac driver](https://github.com/appium/appium-mac2-driver#element-location) it's using (it's using XCTest under the hood, just like iOS).

However, I'm getting the following error: `InvalidSelectorStrategy`.

I debugged this a bit further in the WebDriverIO bundle. I found the exact location and condition it's hitting is:
```
  switch (defineStrategy(selector)) {
        case 'directly': {
            const match = stringSelector.match(DIRECT_SELECTOR_REGEXP);
            console.log("match: " + match[1] + '\n');
            if (!match || !isMobile && isW3C && !constants_1.W3C_SELECTOR_STRATEGIES.includes(match[1])) {
                throw new Error('InvalidSelectorStrategy');
            }
```

Specifically because the variable `W3C_SELECTOR_STRATEGIES` does not contain "-ios predicate string" selector.

I went in my local copy of the bundle and added the string to this array to see if it would work. 

Everything ended up **working perfectly,** the selector did exactly what it was supposed to do with no error. 

So I'm wondering, if the integration is there and it works perfectly, why limit the usage of this selector? It's the **only** one I can use that will allow me to get specific enough to test my app the way it needs to be tested. 

I'd love to hear feedback, thank you

### What is your expected behavior?

Ability to use `-ios predictor string` selector, even if W3C = true and isMobile = false. 

Mobile is not the only platform that supports this selector! Mac does as well.

### How to reproduce the bug.

Copy my capabilities above with Appium + the Mac2 driver. Try to use the `-ios predicate string` selector.

### Relevant log output

```typescript
`Error: InvalidSelectorStrategy`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by samuelfreiberg** [comment]
I'd like to highlight the fact that this Max driver uses `XCUITest` under the hood, exactly like iOS, which is why this works. Why limit the user to not use it?

**Comment by samuelfreiberg** [comment]
And I'll I did to change it was add '-ios predicate string' in _constants.js_
`exports.W3C_SELECTOR_STRATEGIES = ['css selector', 'link text', 'partial link text', 'tag name', 'xpath', '-ios predicate string'];`

**Comment by samuelfreiberg** [comment]
Nevermind - found out how to do this with xpath. Closing

**Comment by christian-bromann** [comment]
Thanks for reporting!

Two things here:

1. given this works for Mac Driver we should enable it for it. So removing `!isMobile && isW3C && !constants_1.W3C_SELECTOR_STRATEGIES.includes(match[1])` from that condition makes sense to me
2. throwing `InvalidSelectorStrategy` should contain more details as to why this doesn't work, I am not sure why we added this in the first place but IMO if someone chooses to use a selector strategy we should let the driver to just deal with it 

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by samuelfreiberg** [comment]
@christian-bromann Thanks for the input!

There's two solutions I'm thinking of, but I don't know enough to be able to determine which one is best for the repo:

1. Adding `'-ios predicate string'` to the `const W3C_SELECTOR_STRATEGIES` array. I did a quick search in the whole repo, and this is the **only** location this array is being used (this specific check), so I don't think this will cause any other unintended changes.
2. As you mentioned, removing `!W3C_SELECTOR_STRATEGIES.includes(match[1])` from the if statement. Again, I don't know the repercussions of this, and how it could affect other scenarios.

Because the `const W3C_SELECTOR_STRATEGIES` array is only used in this one location, I think that's the less risky change. Also, unlike option 2, we're not removing any logic - we're just adding extra functionality. 

I would go with option 1, but again, my knowledge is limited. I'd love to hear your input on this

**Comment by christian-bromann** [comment]
> 1. Adding `'-ios predicate string'` to the `const W3C_SELECTOR_STRATEGIES` array

Well, `-ios predicate string` is not a W3C selector, so this doesn't seem like a good solution.

> 2\. Again, I don't know the repercussions of this, and how it could affect other scenarios.

We only hit this if people write out full selectors , e.g. `css selector:#foobar`. So it doesn't make sense to have the if statement check for w3c compatibility. Given that Appium supports W3C but has their custom selectors it is totally fine to just ignore that check and rewrite it to:

```ts
        if (!match) {
            throw new Error(`InvalidSelectorStrategy: selector "${stringSelector}" not supported!`)
        }
```

Let's change that and make sure that our unit tests pass (`packages/webdriverio/tests/findStrategy.test.ts`).

**Comment by christian-bromann** [comment]
Raised a PR with suggested changes #8693
