### ISSUE TITLE
Where is the error thrown?

### ISSUE THREAD

**Issue by sean-hill** [webdriverio/webdriverio#858]
Hey there,

If I have something like this:

```
client
    .init()
    .url('http://www.google.com')
    .pause(2000)
    .then(function(){
        console.log(IM_NOT_DEFINED);
    })
    .end();
```

Then neither:

```
process.on('uncaughtException') { ... }
```

or

```
client.on('error') { ... }
```

Catch that `IM_NOT_DEFINED` is not defined. However if I do this:

```
console.log(IM_NOT_DEFINED);

client
    .init()
    .url('http://www.google.com')
    .pause(2000)
    .end();
```

Then `process.on('uncaughtException')` is fired saying that `IM_NOT_DEFINED` is not defined. So I'm just curious where the error is thrown, and how I can listen for it. Thanks!

**Comment by ResolverJay** [comment]
Callback is the key here. Basically what happens in case 1 is callback runs after exception check finishes, so nothing is caught. Just remember callback runs after.

**Comment by christian-bromann** [comment]
Well client.on("error", ...) should at least get triggered.

**Comment by sean-hill** [comment]
My thoughts ls exactly @christian-bromann. Thanks for the tag :)

**Comment by sweinertjr** [comment]
I also ran into this. The silent death caused a lot of searching before I found the typo in the variable name :)

**Comment by Dineshs91** [comment]
I am also facing a similar issue. client.on('error', ...) is not triggered.

**Comment by christian-bromann** [comment]
Since we moved on to use promises instead of callbacks any errors aren't propagated anymore. I suggest to either make sure that each command promise is handled properly or us the wdio testrunner where you even have an error hook that allows you to take screenshots and more.
