### ISSUE TITLE
Setting custom headers does not work on CICD/jenkins

### ISSUE THREAD

**Issue by b49tan** [webdriverio/webdriverio#8591]
WebDriveIO tests pass on local, however they begin to to fail with the below error in CICD.

[INFO] webdriver: [POST] https://testplatform.com/v1/session
.....
[ERROR] @wdio/utils:shim: FetchError: Failed to fetch browser webSocket URL from http://localhost:49214/json/version: request to http://localhost:49214/json/version failed, reason: connect ECONNREFUSED 127.0.0.1:49214

Can someone provide insights on how to use browser.cdp and page.setExtraHttpHeaders when webdriverIO is run on a CICD/jenkins portal?

Currently we are using 
WebdriverIO: 7.16.14, 
Selenium: 3.141.59-20200409, 
devtools service: ^7.16.11, 
node: v14,

**Comment by christian-bromann** [comment]
@b49tan you can't run CDP commands on cloud provider as they usually not expose that protocol.

**Comment by b49tan** [comment]
Hi @christian-bromann Thanks for clearing that out, I do have some follow up questions.

1. These tests used to work about 6 months back, has any change been made to not expose the protocol over the years? Our versions over time changed from node 10 to 12, webdriverIO 5.x to 7.x, chrome versions 95.x to 97.x to 100.x.

2. We have also tried puppeteer to set these headers, and this is not working too. Does this still rely on CDP internally and is that why it is failling?

```
          const pupper = await browser.getPuppeteer();
          const pages = await pupper.pages();
          if (pages && pages.length) {
            pages.forEach((page) => {
              page.setExtraHTTPHeaders(headers);
            });
          }
```

3. Would moving to selenium grid 4 help? I see that a CDP port has been exposed as part of this PR : https://github.com/webdriverio/webdriverio/pull/6508

**Comment by christian-bromann** [comment]
> 1. These tests used to work about 6 months back, has any change been made to not expose the protocol over the years? Our versions over time changed from node 10 to 12, webdriverIO 5.x to 7.x, chrome versions 95.x to 97.x to 100.x.

Not sure, I don't know what WebDriver service you are using. It could be certain that between all these versions something has changed. It could be also something within your infrastructure.

> 2\. Does this still rely on CDP internally and is that why it is failling?

Yes and yes.

> 3\. Would moving to selenium grid 4 help?

Certainly.

**Comment by b49tan** [comment]
Got it, thanks @christian-bromann 
Could you elaborate a bit on how to expose chrome devtools protocol from our CICD/Jenkins - I sense that something could have changed there and I can try fixing that on our end.

**Comment by christian-bromann** [comment]
> Could you elaborate a bit on how to expose chrome devtools protocol from our CICD/Jenkins

That depends what WebDriver backend you use. Using a Selenium 4 grid helps.
