### ISSUE TITLE
[🐛 Bug]: Issue with fibers@5.0.2 version

### ISSUE THREAD

**Issue by Amitesh** [webdriverio/webdriverio#8610]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

>7.10.16

### Node.js Version

>14.19.0

### Mode

WDIO Testrunner

### What happened?

It is installing pyhton which is not required.

### What is your expected behavior?

It should not install python for node > 14.x

### How to reproduce the bug.

Here is the reproduce steps:

- Install nodejs > 14.19.0 
- Use @wdio/sync as dependency in your project
- Do npm install
- It will break for fibers npm package which will install python internally. 
- It will try to install **fibers@5.0.2** 

### Relevant log output

```typescript
Here is detailed analysis link and possible solution.
[https://stackoverflow.com/questions/73166618/npm-installation-error-python-is-not-set-from-command-line-or-npm-configurati/73166619#73166619](https://stackoverflow.com/questions/73166618/npm-installation-error-python-is-not-set-from-command-line-or-npm-configurati/73166619#73166619)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by pmahajan-tavisca** [comment]
temporary solution can be found at: https://stackoverflow.com/questions/73166618/npm-installation-error-python-is-not-set-from-command-line-or-npm-configurati/73166619#73166619

**Comment by christian-bromann** [comment]
@Amitesh thanks for raising an issue.

As we are about to deprecated and remove `fibers` I don't see much value in looking into a fix for it. I recommend upgrading WebdriverIO to latest and use `async` commands.

However if you are interested providing a fix I am happy to merge and release it. Please make a PR against the `v7` branch. Cheers!

**Comment by harsha509** [comment]
A fix is landed in the new release of @wdio/sync!

**Comment by Amitesh** [comment]
> A fix is landed in the new release of @wdio/sync!

Thanks @harsha509 and @christian-bromann
