### ISSUE TITLE
[🐛 Bug]: browser.sharedStore.get('*') -  does not fetch all key values

### ISSUE THREAD

**Issue by JoelGamez** [webdriverio/webdriverio#8629]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.20.7

### Node.js Version

v14.19.2

### Mode

WDIO Testrunner

### What happened?

Using '*' browser.sharedStore.get('*') returns undefined instead of fetching all key values.

### What is your expected behavior?

The documentation states,

"You can also fetch all key values by using the * key"

const store = await browser.sharedStore.get('*')
console.log(value) // returns `{ key: "foobar" }`

### How to reproduce the bug.

Within a step or in a config hook, set some sharedStore objects.

    browser.sharedStore.set('one', [111111111])
    browser.sharedStore.set('two', [222222222])
    
Then try to get them,

 let all = await browser.sharedStore.get("'*'")

 console.log(all, 'all --------------------')

### Relevant log output

```typescript
[0-0] undefined all --------------------
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by christian-bromann** [comment]
I looked into this but wasn't able to reproduce it. I will add a smoke test to ensure we test for this feature. Happy to re-open if you can provide a reproducible example.
