### ISSUE TITLE
Create dash docset

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#863]
Many people using [Dash](https://kapeli.com/dash) to check out the docs. We should add our API docs since it should be pretty straightforward using our [wddoc](https://github.com/webdriverio/wddoc) generator script. We just need to make a new template and have some kind of a build script like [d3-dash-gen](https://github.com/exlee/d3-dash-gen).

**Comment by alobaidizt** [comment]
+1... It's been almost a year since this was tagged with Upcoming. Any news? I'm down to help with that

**Comment by WillBrock** [comment]
This is 3 years old and I don't see a benefit of using Dash so closing. Feel free to re-open if needed.
