### ISSUE TITLE
[🐛 Bug]: Support chromeOptions prefs when running devtools

### ISSUE THREAD

**Issue by LinaRScAl** [webdriverio/webdriverio#8634]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.20.5

### Node.js Version

v16.15.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
browserName: 'chrome',
        'goog:chromeOptions': {
           prefs: {
                'directory_upgrade': true,
                'prompt_for_download': false,
                'download.default_directory': downloadDir
            }
        },
```

### What happened?

When I try to download files in my test (this test is used as an example), no matter what global directory I point in my wdio.conf.js file, it keeps downloading to the wrong folder.  

### What is your expected behavior?

I expect all files to be downloaded to the dir with the name download which is specified in the wdio.conf.js global.downloadDir = path.join(__dirname, '/TEST1/download')

### How to reproduce the bug.

const path = require('path')
//the name of the project is TEST1
global.downloadDir = path.join(__dirname, '/TEST1/download')

export const config = {
    //
    // ====================
    // Runner Configuration
    // ====================
    //
    //
    // ==================
    // Specify Test Files
    // ==================
    // Define which test specs should run. The pattern is relative to the directory
    // from which `wdio` was called.
    //
    // The specs are defined as an array of spec files (optionally using wildcards
    // that will be expanded). The test for each spec file will be run in a separate
    // worker process. In order to have a group of spec files run in the same worker
    // process simply enclose them in an array within the specs array.
    //
    // If you are calling `wdio` from an NPM script (see https://docs.npmjs.com/cli/run-script),
    // then the current working directory is where your `package.json` resides, so `wdio`
    // will be called from there.
    //
    specs: [
        './test/specs/**/*.js'
    ],
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    //
    // ============
    // Capabilities
    // ============
    // Define your capabilities here. WebdriverIO can run multiple capabilities at the same
    // time. Depending on the number of capabilities, WebdriverIO launches several test
    // sessions. Within your capabilities you can overwrite the spec and exclude options in
    // order to group specific specs to a specific capability.
    //
    // First, you can define how many instances should be started at the same time. Let's
    // say you have 3 different capabilities (Chrome, Firefox, and Safari) and you have
    // set maxInstances to 1; wdio will spawn 3 processes. Therefore, if you have 10 spec
    // files and you set maxInstances to 10, all spec files will get tested at the same time
    // and 30 processes will get spawned. The property handles how many capabilities
    // from the same test should run tests.
    //
    maxInstances: 10,
    //
    // If you have trouble getting all important capabilities together, check out the
    // Sauce Labs platform configurator - a great tool to configure your capabilities:
    // https://saucelabs.com/platform/platform-configurator
    //
    capabilities: [{
        maxInstances: 1,
        browserName: 'chrome',

        'goog:chromeOptions': {
                  prefs: {
                'directory_upgrade': true,
                'prompt_for_download': false,
                'download.default_directory': downloadDir
            }
        },
    }],
    //
    // ===================
    // Test Configurations
    // ===================
    // Define all options that are relevant for the WebdriverIO instance here
    //
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    logLevel: 'info',
    //
    // Set specific log levels per logger
    // loggers:
    // - webdriver, webdriverio
    // - @wdio/browserstack-service, @wdio/devtools-service, @wdio/sauce-service
    // - @wdio/mocha-framework, @wdio/jasmine-framework
    // - @wdio/local-runner
    // - @wdio/sumologic-reporter
    // - @wdio/cli, @wdio/config, @wdio/utils
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    // logLevels: {
    //     webdriver: 'info',
    //     '@wdio/appium-service': 'info'
    // },
    //
    // If you only want to run your tests until a specific amount of tests have failed use
    // bail (default is 0 - don't bail, run all tests).
    bail: 0,
    //
    // Set a base URL in order to shorten url command calls. If your `url` parameter starts
    // with `/`, the base url gets prepended, not including the path portion of your baseUrl.
    // If your `url` parameter starts without a scheme or `/` (like `some/path`), the base url
    // gets prepended directly.
    baseUrl: 'http://localhost',
    //
    // Default timeout for all waitFor* commands.
    waitforTimeout: 10000,
    //
    // Default timeout in milliseconds for request
    // if browser driver or grid doesn't send response
    connectionRetryTimeout: 120000,
    //
    // Default request retries count
    connectionRetryCount: 3,
    //
    // Test runner services
    // Services take over a specific job you don't want to take care of. They enhance
    // your test setup with almost no effort. Unlike plugins, they don't add new
    // commands. Instead, they hook themselves up into the test process.
    //services: ['chromedriver'],
    services: ['devtools'],
    
    // Framework you want to run your specs with.
    // The following are supported: Mocha, Jasmine, and Cucumber
    // see also: https://webdriver.io/docs/frameworks
    //
    // Make sure you have the wdio adapter package for the specific framework installed
    // before running any tests.
    framework: 'mocha',
    //
    // The number of times to retry the entire specfile when it fails as a whole
    // specFileRetries: 1,
    //
    // Delay in seconds between the spec file retry attempts
    // specFileRetriesDelay: 0,
    //
    // Whether or not retried specfiles should be retried immediately or deferred to the end of the queue
    // specFileRetriesDeferred: false,
    //
    // Test reporter for stdout.
    // The only one supported by default is 'dot'
    // see also: https://webdriver.io/docs/dot-reporter
    reporters: ['spec'],

    
    //
    // Options to be passed to Mocha.
    // See the full list at http://mochajs.org/
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },
    //
    // =====
    // Hooks
    // =====
    // WebdriverIO provides several hooks you can use to interfere with the test process in order to enhance
    // it and to build services around it. You can either apply a single function or an array of
    // methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
    // resolved to continue.
    /**
     * Gets executed once before all workers get launched.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     */
    // onPrepare: function (config, capabilities) {
    // },
    // onPrepare: function (config, capabilities) {
    //     // make sure download directory exists
    //     if (!fs.existsSync(downloadDir)){
    //         // if it doesn't exist, create it
    //         fs.mkdirSync(downloadDir);
    //     }
    //   },
    /**
     * Gets executed before a worker process is spawned and can be used to initialise specific service
     * for that worker as well as modify runtime environments in an async fashion.
     * @param  {String} cid      capability id (e.g 0-0)
     * @param  {[type]} caps     object containing capabilities for session that will be spawn in the worker
     * @param  {[type]} specs    specs to be run in the worker process
     * @param  {[type]} args     object that will be merged with the main configuration once worker is initialized
     * @param  {[type]} execArgv list of string arguments passed to the worker process
     */
    // onWorkerStart: function (cid, caps, specs, args, execArgv) {
    // },
    /**
     * Gets executed just after a worker process has exited.
     * @param  {String} cid      capability id (e.g 0-0)
     * @param  {Number} exitCode 0 - success, 1 - fail
     * @param  {[type]} specs    specs to be run in the worker process
     * @param  {Number} retries  number of retries used
     */
    // onWorkerEnd: function (cid, exitCode, specs, retries) {
    // },
    /**
     * Gets executed just before initialising the webdriver session and test framework. It allows you
     * to manipulate configurations depending on the capability or spec.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     * @param {String} cid worker id (e.g. 0-0)
     */
    // beforeSession: function (config, capabilities, specs, cid) {
    // },
    /**
     * Gets executed before test execution begins. At this point you can access to all global
     * variables like `browser`. It is the perfect place to define custom commands.
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs        List of spec file paths that are to be run
     * @param {Object}         browser      instance of created browser/device session
     */
    // before: function (capabilities, specs) {
    // },
    /**
     * Runs before a WebdriverIO command gets executed.
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     */
    // beforeCommand: function (commandName, args) {
    // },
    /**
     * Hook that gets executed before the suite starts
     * @param {Object} suite suite details
     */
    // beforeSuite: function (suite) {
    // },
    /**
     * Function to be executed before a test (in Mocha/Jasmine) starts.
     */
    // beforeTest: function (test, context) {
    // },
    /**
     * Hook that gets executed _before_ a hook within the suite starts (e.g. runs before calling
     * beforeEach in Mocha)
     */
    // beforeHook: function (test, context) {
    // },
    /**
     * Hook that gets executed _after_ a hook within the suite starts (e.g. runs after calling
     * afterEach in Mocha)
     */
    // afterHook: function (test, context, { error, result, duration, passed, retries }) {
    // },
    /**
     * Function to be executed after a test (in Mocha/Jasmine only)
     * @param {Object}  test             test object
     * @param {Object}  context          scope object the test was executed with
     * @param {Error}   result.error     error object in case the test fails, otherwise `undefined`
     * @param {Any}     result.result    return object of test function
     * @param {Number}  result.duration  duration of test
     * @param {Boolean} result.passed    true if test has passed, otherwise false
     * @param {Object}  result.retries   informations to spec related retries, e.g. `{ attempts: 0, limit: 0 }`
     */
    // afterTest: function(test, context, { error, result, duration, passed, retries }) {
    // },

    /**
     * Hook that gets executed after the suite has ended
     * @param {Object} suite suite details
     */
    // afterSuite: function (suite) {
    // },
    /**
     * Runs after a WebdriverIO command gets executed
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     * @param {Number} result 0 - command success, 1 - command error
     * @param {Object} error error object if any
     */
    // afterCommand: function (commandName, args, result, error) {
    // },
    /**
     * Gets executed after all tests are done. You still have access to all global variables from
     * the test.
     * @param {Number} result 0 - test pass, 1 - test fail
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // after: function (result, capabilities, specs) {
    // },
    /**
     * Gets executed right after terminating the webdriver session.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // afterSession: function (config, capabilities, specs) {
    // },
    /**
     * Gets executed after all workers got shut down and the process is about to exit. An error
     * thrown in the onComplete hook will result in the test run failing.
     * @param {Object} exitCode 0 - success, 1 - fail
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {<Object>} results object containing test results
     */
    // onComplete: function(exitCode, config, capabilities, results) {
    // },
    // onComplete: function() {
    //     rmdir(downloadDir)
    //   }
    /**
    * Gets executed when a refresh happens.
    * @param {String} oldSessionId session ID of the old session
    * @param {String} newSessionId session ID of the new session
    */
    // onReload: function(oldSessionId, newSessionId) {
    // }
}

_______________________________________
//test

const fs = require('fs');
const path = require('path')

describe('My downloadTest', () => {
    it('should downloadfile', async () => {
        await browser.url('https://the-internet.herokuapp.com/download');
        await (await $('a[href="download/webdriverIO.png"]')).click()
        //the pause to see that the file doesn't go to the folder specified in wdio conf
        await browser.pause(10000)
        const folderPath = '.download/webdriverIO.png'
        fs.access(folderPath, fs.constants.F_OK, (err) => {
            console.log('Checking if the file exists');
            if (err) {
                console.error('File does not exist');
            }
        })
    })
})

//package json
{"devDependencies":
{"@babel/core":"^7.18.5",
"@babel/preset-env":"^7.18.2",
"@babel/register":"^7.17.7",
"@wdio/cli":"^7.20.5",
"@wdio/devtools-service":"^7.19.7",
"@wdio/local-runner":"^7.20.5",
"@wdio/mocha-framework":"^7.20.3",
"@wdio/spec-reporter":"^7.20.3",
"chromedriver":"^102.0.0",
"wdio-chromedriver-service":"^7.3.2",
"wdio-wait-for":"^2.2.6"},
"name":"test1",
"version":"1.0.0",
"description":"",
"main":"index.js",
"scripts":{"test":"npm test",
"wdio":"wdio run wdio.conf.js"},
"dependencies":{"download":"^8.0.0"}}

//

### Relevant log output

```typescript
[0-0] 2022-08-03T03:30:43.399Z INFO devtools: Connect Puppeteer with browser on port 55198
[0-0] 2022-08-03T03:30:43.729Z INFO devtools: COMMAND navigateTo("https://the-internet.herokuapp.com/download")       
[0-0] 2022-08-03T03:30:43.999Z INFO devtools: RESULT null
[0-0] 2022-08-03T03:30:44.005Z INFO devtools: COMMAND findElement("css selector", "a[href="download/webdriverIO.png"]")
[0-0] 2022-08-03T03:30:44.008Z INFO devtools: RESULT { 'element-6066-11e4-a52e-4f735466cecf': 'ELEMENT-1' }
[0-0] 2022-08-03T03:30:44.015Z INFO devtools: COMMAND elementClick("ELEMENT-1")
[0-0] 2022-08-03T03:30:44.077Z INFO devtools: RESULT null  
[0-0] Checking if the file exists
[0-0] File does not exist
[0-0] 2022-08-03T03:30:54.084Z INFO devtools: COMMAND deleteSession()
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by LinaRScAl** [comment]
this is the tree of the project https://prnt.sc/sY8GMi3zM5pZ where all the folders are visible.

**Comment by christian-bromann** [comment]
Thanks for filing the issue!

I don't think this is a bug within WebdriverIO because it just passes along your prefs. Not sure why they aren't applied though.

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by LinaRScAl** [comment]
@christian-bromann thank you for your response. I think I figured it out: it's not working if services: ['devtools'] and working with services: ['chromedriver']. Is there a chance that you may apply this functionality to devtools as well? Thank you in advance.

**Comment by christian-bromann** [comment]
@LinaRScAl good catch, all we need to do is to add it here: https://github.com/webdriverio/webdriverio/blob/main/packages/devtools/src/launcher.ts#L109-L116, mind taking a stab?

**Comment by LinaRScAl** [comment]
@christian-bromann I don't think I can do that yet(

**Comment by christian-bromann** [comment]
@LinaRScAl why you can't do it?

**Comment by LinaRScAl** [comment]
@christian-bromann I've never done it before, and your project is huge, so I don't know where to look for a similar line of the code which, I assume it's being applied when services: ['chromedriver'], so I can copy and paste it to devtools. I'm not a developer unfortunately)

**Comment by erwinheitzman** [comment]
Correct me if I am wrong but I think that in order to get this working we need to do the following:
```js
// make sure puppeteer-extra & puppeteer-extra-plugin-user-preferences are installed

const UserPreferencesPlugin = require("puppeteer-extra-plugin-user-preferences");

const downloadImageDirectoryPath = process.cwd()

puppeteer.use(
  UserPreferencesPlugin({
    userPrefs: {
      download: {
        prompt_for_download: false,
        open_pdf_in_system_reader: true,
        default_directory: downloadImageDirectoryPath,
      },
      plugins: {
        always_open_pdf_externally: true,
      },
    },
  })
);
```
And add it somewhere at the initialization (file) that @christian-bromann shared.

**Comment by christian-bromann** [comment]
I wasn't aware that such package exists. For running Chrome sessions we use `chrome-launcher` we we only need to pass in a `prefs` object. For other sessions (Edge and Firefox) we use `puppeteer-launch` where this package seems to be useful.

**Comment by christian-bromann** [comment]
Raised a PR in #8691, review/feedback would be appreciated.

**Comment by LinaRScAl** [comment]
Hi Christian. @christian-bromann can you please let me know how does it work? Should a wdio version to be updated so this can be tested? I'm not sure if this PR was deployed already... And thank you, thank you!

**Comment by christian-bromann** [comment]
@LinaRScAl yes, this was released to one of the latest webdriverio versions, you can now set `prefs` in `goog:chromeOptions` as follows:

```ts
browserName: 'chrome',
        'goog:chromeOptions': {
           prefs: {
                'directory_upgrade': true,
                'prompt_for_download': false,
                'download.default_directory': downloadDir
            }
        },
```

**Comment by LinaRScAl** [comment]
Unfortunately, it's not working as expected. The same as it was before. I've updated the wdio version + all the dependencies and it's still the same: not downloading a file to the specified folder. I'll provide you with the video recording soon.

**Comment by christian-bromann** [comment]
I just tried with the latest WebdriverIO version and both can download the file. The only difference I recognised is that when using the devtools protocol the `prefs` arguments are passed into the user dir of Chrome but not recognised by the browser causing it to download into the default download dir and not the one used in `prefs`. This would be a chrome-launcher issue I think. I tried running the following script:

```ts
await browser.url('https://the-internet.herokuapp.com/download')
await browser.$('=koko.txt').click()
```

**Comment by paritagandhi** [comment]
> d both automation protocols can d

Was this issue resolved? I upgraded to wdio8 and have the same issue that it does not download to the specified folder?

**Comment by christian-bromann** [comment]
@paritagandhi we recommend to __not__ use the `automationProtocol` settings anymore and run your tests fully on WebDriver. For that protocol we have add [documentation](https://webdriver.io/docs/best-practices/file-download) on how to set the download directory. Since we fixed this bug it might have come back which is the reason why we deprecate the `devtools` package for automation all together.
