### ISSUE TITLE
[📖 Docs]: link to "Protractor boilerplate project" leads to 404 error

### ISSUE THREAD

**Issue by lesteral** [webdriverio/webdriverio#8637]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Other

### Description of the improvement / report

on page https://webdriver.io/docs/protractor-migration/
there are two references to a "Protractor [boilerplate project](https://github.com/webdriverio/protractor-jasmine-typescript)" 

However, this project doesn't seem to exist (and the link leads to a 404 error).

Should a different project be referenced?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Bummer, I think this repository was removed and I don't have a copy anymore. We should remove all references to it.

**Comment by lesteral** [comment]
Christian - no problem (I had hoped it was just a out-of-date link). Thank you for the prompt response.  Regards, Lester

**Comment by christian-bromann** [comment]
Thanks for taking a stab at this one @harsha509 🎉
