### ISSUE TITLE
WDIO 6: Getting "Error: An unknown server-side error occurred while processing the command. Original error: chrome not reachable" - v100.0.4896.127

### ISSUE THREAD

**Issue by sandozsrf** [webdriverio/webdriverio#8639]
### Discussed in https://github.com/webdriverio/webdriverio/discussions/8638

<div type='discussions-op-text'>

<sup>Originally posted by **sandozsrf** August  4, 2022</sup>
Android only: I'm using WebdriverIO 6 with SauceLabs and getting the below issue in Android tests. It fails when we try to switch contexts or if the validation happens after loading through navigation which is mostly consistent. It currently shows the chrome driver version is 100.0.4896.127 but i'm not able to find how to change/update it or check the compatibility.

I tried changing different versions of appium and android but I can see the same issue. Due to project dependencies, I will not be able to update webdriverIO to the recent version(7.x.x) which dropped the support for Node 10. So, I have to try with WebdriverIO 6 as of now.

**Current Node version: 10.16.3**

```
Error: An unknown server-side error occurred while processing the command. Original error: chrome not reachable
  (Session info: chrome=100.0.4896.127)
[emulator-5554 android 12 #0-5] Error: An unknown server-side error occurred while processing the command. Original error: chrome not reachable
[emulator-5554 android 12 #0-5]   (Session info: chrome=100.0.4896.127)
```

In package.json under devDependencies:

```
"wdio-chromedriver-service": "^6.0.4",
"@wdio/codemod": "^0.9.0",
"@rpii/wdio-html-reporter": "6.3.1",
"@wdio/appium-service": "6.1.0",
"@wdio/cli": "6.12.1",
"@wdio/jasmine-framework": "^6.11.0",
"@wdio/junit-reporter": "6.11.0",
"@wdio/local-runner": "6.12.1",
"@wdio/sauce-service": "6.12.1",
"@wdio/spec-reporter": "6.11.0",
"@wdio/sync": "6.11.0",
"appium": "1.22.0",
```

My config looks like

```
capabilities({
    autoWebview: true,
    autoWebviewTimeout: 180000,
    deviceOrientation: 'portrait',
    phoneOnly: true,
    maxSession: 5,
    deviceName: 'Google Pixel 4 GoogleAPI Emulator',
    build: `Test on Emulator`,
    unicodeKeyboard: true,
    autoGrantPermissions: true,
    connectionRetryTimeout: 90000,
    appiumVersion: '1.22.1',
    app: 'storage:filename',
    platformName: 'android',
    platformVersion: '12.0',
    appPackage: 'appPackage_details',
    appWaitActivity: 'appWaitActivity_details',
    videoUploadOnPass: false,
    recordScreenshots: false,
    extendedDebugging: false,
    fullContextList: true,
    automationName: 'UiAutomator2',
    noReset: true,
    newCommandTimeout: 180000,
});
```

Please let me know how to resolve this issue. Any help is appreciated.</div>

**Comment by christian-bromann** [comment]
This can stay a discussion until there is a clue that this is an immediate bug within WebdriverIO.
