### ISSUE TITLE
Not possible to run a single test or test folder from testrunner

### ISSUE THREAD

**Issue by frost0503** [webdriverio/webdriverio#864]
Hi,

I can't see a way to run a single test from command line, out of a whole folder's worth.  Or to run a complete folder and all tests within.

Would it be possible to have an enhancement switch for test and folder of tests

**Comment by christian-bromann** [comment]
@frost0503 you can run a folder full of spec files using the wdio test runner. Check out the [example section](https://github.com/webdriverio/webdriverio/tree/master/examples/wdio)

**Comment by Kryten0807** [comment]
@frost0503 actually asked two questions:

1. how do I run a single test from the command line? and
2. how do I run a complete folder & all tests within

Question 2 has an answer, as pointed out by @christian-bromann, but the first question still has no answer. The only way I can see to run a single test file out of a folder is to modify my `wdio.conf.js`, which is awkward.

Can we enhance the testrunner to accept the name of a single test file on the command line?

**Comment by aguerere** [comment]
Hi @Kryten0807, this could be very helpful. Did you find a way to run a single test from the command line?

**Comment by christian-bromann** [comment]
You could define a single file as a suite and that file via `wdio --suite mySuite`

**Comment by pbrain19** [comment]
Can you give an example I am trying to run as instructed using the --suite flag but it keeps running all the tests. 

./node_modules/.bin/wdio --suite test/specs/hotels_b2c/customer_hotel_search_spec.js

can someone explain what I am doing wrong.

**Comment by christian-bromann** [comment]
@pbrain19 please see http://webdriver.io/guide/testrunner/organizesuite.html

**Comment by pbrain19** [comment]
this says orgnizing suites.. I need to run one file... I dont want to have to change the config every time I want to run one file. 

Also there doesn't seem to be a way to iterate on the results of elements... when I do browser.elements. and access the values array.. All I have access to is an array of objects with IDS but I cant seem to just be able to run a foreach and change the value of each on independently. 


Ideally I would want to do this

var elements = client.elements(someselector)

elements.forEach(function(item) {  item.setValue(x)  })
Is there a  way to do that?

**Comment by christian-bromann** [comment]
If you are running in sync mode, you can do this:
```js
var elements = client.elements(someselector)
elements.value.forEach(function(item) {
    item.elementIdValue(item.ELEMENT);
});
```

**Comment by pbrain19** [comment]
How do I access the base url that I declared in the config? I need to use it in a test.

**Comment by pbrain19** [comment]
Also is there an API client? one that would allow me to test my api.?

**Comment by christian-bromann** [comment]
> How do I access the base url that I declared in the config?

http://webdriver.io/guide/testrunner/browserobject.html

> Also is there an API client? one that would allow me to test my api.?

No, your API should be tested with unit tests

**Comment by david-benes** [comment]
@pbrain19 Hi Paul, 
>> can someone explain what I am doing wrong.
You are calling wdio with invalid --suite argument value. You are supposed to use suite name from config, not path to test. I already filled a bug report, because no test should be run in your case but all tests are run. 

https://github.com/webdriverio/webdriverio/issues/1448

**Comment by mnemanja** [comment]
@christian-bromann made a reference to the correct page. Here's a precise link to the section in case anyone missed: 
http://webdriver.io/guide/testrunner/organizesuite.html#Run-Single-Test-Suites

Run Single Test Suite - essentially this is the command:
`$ wdio wdio.conf.js --spec ./test/specs/e2e/login.js`

**Comment by HuffyPiet** [comment]
Am kind of having a problem here, don't know where this is coming from, new to test-runner tho, so far been able to successfully use WDIO, following the CLI prompt to create wdio.conf.js  but :
 ./node_modules/.bin/wdio 
doesn't do anything at all, using Mocha Framework by the way. Just hangs for a very long time, doesn't do any actions, doesn't display any errors either

**Comment by HuffyPiet** [comment]
<code>$ ./node_modules/.bin/wdio wdio.conf.js --spec ./test/example.js</code> behaved the same way

**Comment by vijen012** [comment]
@HuffyPiet I am also facing same issue. have you found solution if yes please let me know .

**Comment by worc** [comment]
`--spec` can run a single file, but i'm not seeing a command line option to pick one scenario out of that file.

**Comment by charan2628** [comment]
@vijen012 I'm facing the same issue, did you solved it?

**Comment by HuffyPiet** [comment]
> @HuffyPiet I am also facing same issue. have you found solution if yes please let me know .

I had switched to a different role, I haven't been doing testing in a while. I am on a different OS now, maybe windows was the issue or something :D ... Would get at it again and let you know. Sorry for taking long to respond.

**Comment by kbtutorials** [comment]
Hi ,We can run single spec file from folder of spec files ,
below is the tutorial 
https://youtu.be/S2VtT3GboBw

**Comment by humphrypietrsen** [comment]
Thanks, Kbtutorials :)
__

Humphrey

**Comment by AndrewFreemantle** [comment]
As @mnemanja [wrote](https://github.com/webdriverio/webdriverio/issues/864#issuecomment-303373175):
> Run Single Test Suite - essentially this is the command:
> `$ wdio wdio.conf.js --spec ./test/specs/e2e/login.js`

If you have the test command configured as a script in `package.json`, for example:
````json
// package.json
{
  "scripts": {
    "test": "npx wdio run wdio.conf.js",
  }
}
````

Then you can run a single test suite / file like so:
`$ npm run test -- --spec ./test/specs/e2e/login.js`

**Comment by Enik12** [comment]
> As @mnemanja [wrote](https://github.com/webdriverio/webdriverio/issues/864#issuecomment-303373175):
> 
> > Run Single Test Suite - essentially this is the command:
> > `$ wdio wdio.conf.js --spec ./test/specs/e2e/login.js`
> 
> If you have the test command configured as a script in `package.json`, for example:
> 
> ```json
> // package.json
> {
>   "scripts": {
>     "test": "npx wdio run wdio.conf.js",
>   }
> }
> ```
> 
> Then you can run a single test suite / file like so: `$ npm run test -- --spec ./test/specs/e2e/login.js`

Thanks. This sign "--" before --spec works for me.
