### ISSUE TITLE
Be able to set no loggingPrefs

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#865]
see #709

We need the opportunity to be able to set explicitly no loggingPrefs since this can cause issues with Browserstack and other vendors/drivers.

**Comment by stantaylor** [comment]
When I run an android browser test on SauceLabs, it uses selendroid on their side, and I get the error "SEVERE: Error occurred while starting Selendroid session
java.lang.ClassCastException: org.json.JSONObject cannot be cast to org.openqa.selenium.logging.LoggingPreferences"

As a workaround for the immediate future--to get my tests to run--I have had to fork webdriverio and comment out the "set default logging prefs" lines in lib/webdriverio.js (currently, lines 73+)

I guess this is as good a fix as any. I can't think of anything better
https://github.com/webdriverio/webdriverio/pull/709

**Comment by mucaho** [comment]
+1, having the same issue.
@stantaylor 
Wouldn't `delete client.desiredCapabilities.loggingPrefs;` after aquiring a client instance with `require('webdriverio').remote(webdriver_config)` work? Seems like a less intrusive way.

**Comment by maumercado** [comment]
+1 on this issue

**Comment by christian-bromann** [comment]
Ok, removed that loggingPrefs setup completely. Will be released with v4.
