### ISSUE TITLE
[🐛 Bug]: eslint-plugin-wdio await-expect matchers list is incomplete

### ISSUE THREAD

**Issue by Roozenboom** [webdriverio/webdriverio#8650]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest 

### Node.js Version

v16

### Mode

WDIO Testrunner

### What happened?

Some wdio tests are failing because the expect isn't awaited. The await-expect eslint rule is not complaining because the used matcher is not in the list (constants) of matchers used to check if the expect should be awaited or not. 
To be more specific this is happening with the use of the toExist matcher, which is not in the list but the alias toBeExisting is. same for the other alias toBePresent is missing in the list of matchers used. https://v7.webdriver.io/docs/api/expect-webdriverio#toexist

### What is your expected behavior?

when using the await-expect linting rule it should throw an error when the toExist matcher is not awaited

### How to reproduce the bug.

```js
// create a file with a simple expect and matcher toExist
it('should validate current package', async () => {
  expect(element).toExist();
}
```
run eslint with wdio plugin recommended settings

### Relevant log output

```typescript
[0-0] Spec "should validate current package" ran a "toExist" expectation after it finished.
[0-0] 1. Did you forget to return or await the result of expectAsync?
[0-0] 2. Was done() invoked before an async operation completed?
[0-0] 3. Did an expectation follow a call to done()?
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

It seems like we missed to add the whole list in our [`matchers`](https://github.com/webdriverio/webdriverio/blob/86a8c44d84a6e19e4284551260aed0c88763ac0d/packages/eslint-plugin-wdio/src/constants.ts#L1-L33). I assume just adding them there will fix the problem.

Are you interested taking a stab at this?

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by Roozenboom** [comment]
Yes i am interested in taking this task, actually I am already preparing it

**Comment by christian-bromann** [comment]
@Roozenboom sweet!

As we are currently working on v8 in the `main` branch, would you mind sending 2 PRs to `main` and `v7`? Thanks!

**Comment by Roozenboom** [comment]
> @Roozenboom sweet!
> 
> As we are currently working on v8 in the `main` branch, would you mind sending 2 PRs to `main` and `v7`? Thanks!

I created a PR for the main branch and for the v7 branch.

**Comment by christian-bromann** [comment]
Awesome, thanks! Closing.
