### ISSUE TITLE
Losing stack traces in error handling

### ISSUE THREAD

**Issue by vrundbaken** [webdriverio/webdriverio#867]
I'm having a lot of problems with error reporting not including a stack trace. While trying to troubleshoot the issue I found some very peculiar behavior. It seems that after an error is thrown within a wdio commands then it's .stack gets replaced with a combination of .type and .message.

```
return client.isVisible(selector).then(function(isVisible) {
				var error = new Error('Some error');
				console.log( error.stack );
				throw error;
			})
			.catch(function(e) {
				console.error(e.message, e.type, e.stack);
			});
        });
```

At the first console.log I get a beautiful stack trace. After I throw the error and catch it that stack trace turns into "undefined: Some error".

I'm over my head here but I was using node-debug and I found a method that is reasigning e.stack however the stack it's trying to assign to it is an empty array.

```
function throwException(e, stack) {
        stack = stack.slice(0, -1).map(function(trace) {
            return '    at ' + trace;
        });
        e.stack = e.type + ': ' + e.message + '\n' + stack.reverse().join('\n');
        throw e;
    }
```

Before it's reassigned e.stack has the stack trace I'm looking for.

**Comment by christian-bromann** [comment]
Yes we are catching the error and turn it into a WebdriverIO error. I agree with you that the behaviour is odd and the stack trace should get propagated.

**Comment by Dharmoslap** [comment]
Why not to add this feature to the roadmap?

**Comment by christian-bromann** [comment]
@Dharmoslap because I wanted to do some investigation first to figure out what to do best with these error stacks. If you come up with a suggestion/proposal I am happy to discuss and eventually merge it 😉

**Comment by christian-bromann** [comment]
I don't see this error happening anymore, I tried
```js
        return this.client.element('body').then(() => {
            throw new Error('puubs')
        }).catch((e) => {
            console.log(e, e.message, e.stack);
        })
```
and got the full error stack.

**Comment by j0tunn** [comment]
@christian-bromann to see the error you should set `screenshotOnReject` or `screenshotPath` option in config.
I think problem is here: https://github.com/webdriverio/webdriverio/blob/v4.2.8/lib/webdriverio.js#L263-L264

**Comment by sha1sum** [comment]
@christian-bromann I think this is still valid. I'm attempting to wrap cucumber functions to save screenshots on assertion failures for chai (not just Selenium errors), for example:

```js
  this.Given(
    /^I open the (url|site) "([^"]*)?"$/i,
    { retry: 2 },
    wrap(openWebsite)
  )
```

**screenshotWrapper.js**
```js
export default function (fn) {
  return (...args) => {
    try {
      fn(...args)
    } catch (e) {
      browser.saveScreenshot(`${browser.options.screenshotPath}/${(new Date()).toISOString()}_${fn.name}.jpg`)
      throw e
    }
  }
}
```

As a result, I'm getting the following using verbose output on certain functions, making it almost impossible to debug things:

```
[firefox #0-1] undefined
[firefox #0-1] no stack available
```

@j0tunn is this similar to the behavior you're seeing?

I'm assuming this is due to me attempting to catch and re-throw the error?

**Comment by sha1sum** [comment]
**UPDATE**: My previous comment seems to have absolutely nothing to do with what is occurring. I will leave it for posterity, but not using the wrapper produces the same log output in _some_ circumstances. I will continue to research and open another issue if one is not already present.
