### ISSUE TITLE
Screenshot save on error not working on Windows.

### ISSUE THREAD

**Issue by yoshi6jp** [webdriverio/webdriverio#868]
`:` that can not be used in the filename on Windows.
- https://msdn.microsoft.com/ja-jp/library/windows/desktop/aa365247(v=vs.85).aspx#naming_conventions

But the filename to save screenshot was included `:`.

https://github.com/webdriverio/webdriverio/blob/master/lib/webdriverio.js#L118

```javascript
path.join(screenshotPath, 'ERROR_' + sanitize.caps(desiredCapabilities) + '_' + new Date().toJSON() + '.png')
```

```javascript
new Date().toJSON() // => "2015-11-10T13:43:57.374Z"
```

**workaround**

```javascript
path.join(screenshotPath, 'ERROR_' + sanitize.caps(desiredCapabilities) + '_' + new Date().toJSON().replace(/:/g,"-")  + '.png')
```

```javascript
new Date().toJSON().replace(/:/g, "-") // =>  "2015-11-10T14-00-23.982Z"
```

**Comment by wvankuipers** [comment]
:+1: I had the same problem, I will create a pull-request so this can be fixed.
