### ISSUE TITLE
[🐛 Bug]: Yarn2 - MISSING_PEER_DEPENDENCY

### ISSUE THREAD

**Issue by ChandlerFerry** [webdriverio/webdriverio#8699]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
Not Applicable
```

### What happened?

1. Create a new Yarn2 Project
2. Install a Webdriver IO Package
3. Received [YN0002 - MISSING_PEER_DEPENDENCY](https://yarnpkg.com/advanced/error-codes#yn0002---missing_peer_dependency) warnings

### What is your expected behavior?

Expected to receive a clean install

### How to reproduce the bug.

```
mkdir test
cd test
yarn init -2
yarn add @wdio/cli
```

### Relevant log output

```typescript
➤ YN0002: │ @wdio/cli@npm:7.20.9 doesn't provide typescript (p1a648), requested by @wdio/types   
➤ YN0002: │ @wdio/config@npm:7.20.8 doesn't provide typescript (p4bdba), requested by @wdio/types
➤ YN0002: │ @wdio/utils@npm:7.20.7 doesn't provide typescript (p47b45), requested by @wdio/types
➤ YN0002: │ devtools@npm:7.20.8 doesn't provide typescript (pb80d8), requested by @wdio/types
➤ YN0002: │ webdriver@npm:7.20.8 doesn't provide typescript (pe41cc), requested by @wdio/types
➤ YN0002: │ webdriverio@npm:7.20.9 doesn't provide typescript (pbcb48), requested by @wdio/types
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Will this cause other package managers to warn if `typescript` is not installed? I believe this will be the case for NPM. I want to avoid the situation that folks that don't use TypeScript are being forced to install it as dependency even though non of the packages need it. Therefor I wonder if it makes more sense to move the `typescript` peer dependency into a `optionalDependency`.

**Comment by ChandlerFerry** [comment]
It's definitely a valid question, and one I was contemplating as I was making the initial PR but unfortunately got busy.

Let me do some testing in the morning and I'll make sure to test & reduce the impact radius.

**Comment by erwinheitzman** [comment]
If this is regarding the installation of Typescript as a user, [optional dependencies](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#optionaldependencies) would be best here.

If this is regarding the installation as a dev (contributor), defining it as a dev dependency should suffice (which we already do if I am not mistaken).

**Comment by christian-bromann** [comment]
> I would just remove Typescript as a dependency all together because it isn't a requirement in any way

We unfortunately use [some `typescript` types](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-types/src/Compiler.ts#L5) which is why it is a peer dep in the first place.

**Comment by erwinheitzman** [comment]
> > I would just remove Typescript as a dependency all together because it isn't a requirement in any way
> 
> We unfortunately use [some `typescript` types](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-types/src/Compiler.ts#L5) which is why it is a peer dep in the first place.

Damn, we use it for only one line.
I want to suggest to replace the transformer types and get rid of the dependency.
How do you feel about that?

**Comment by christian-bromann** [comment]
> How do you feel about that?

It is gonna be hard to just replace the type but we might can have some looser types there in favor to get rid of the import.

> EDIT: there's no issues when it's not installed right? If so, it would be optional

Yeah, let's try with an optional import first. I think it is added for these kind of use cases. It doesn't complain if not installed.

**Comment by erwinheitzman** [comment]
In that case we don't have to add anything.
One thing to note is that optional packages get installed by default (but can be skipped by running `npm install --no-optional`) which might not be what we want.

**Comment by ChandlerFerry** [comment]
After some research, I believe that what we were looking for is [peerDependenciesMeta](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta)

[Yarn](https://yarnpkg.com/configuration/manifest#peerDependenciesMeta.optional) also has a section on this, but I had to learn a bit more to understand if it would solve the problem.

From my testing, I believe this solution fits the bill for both reduced blast radius and proper management across all package managers.
