### ISSUE TITLE
Authentification basic for firefox with WebdriverIO

### ISSUE THREAD

**Issue by antho03** [webdriverio/webdriverio#870]
Hi, i use webdriverIO for create my selenium tests.
I try to pass credentials on my staging website, i have try somes solutions
-Firefox Profile : don't work with webdriverIO for me .. just ok in java
-User and password in URL like that : http://user:password/site.com/

Someone have one solution ? 
Thx guys !

**Comment by christian-bromann** [comment]
it should be `http://user:password@site.com/`

**Comment by antho03** [comment]
Hi, thx for your answer !
Yes it was a mistake of my, but i have try like that "http://user:password@site.com/" and this don't work :/
Authentication is always asked ..

**Comment by christian-bromann** [comment]
This is a limitation of Selenium. I am not sure if there is a workaround for that. I've seen people who were able to get it working like this.

**Comment by antho03** [comment]
Ok .. don't work for me :/
For firefox profile, You know the correct code ?
