### ISSUE TITLE
v4.0 does not save custom commands to command list

### ISSUE THREAD

**Issue by georgecrawford** [webdriverio/webdriverio#872]
```js
browser.addCommand('george', function() {
    browser.url('/');
})
browser.george();
console.log(browser.getCommandHistory())

// gives:

[ { name: 'init', args: [] },
  { name: 'windowHandleMaximize', args: [] },
  { name: 'timeoutsAsyncScript', args: [ 5000 ] },
  { name: 'url', args: [ '/' ] } ]
```
Custom commands in v4.0 are somehow not added to the `commandList`, so obviously bypass https://github.com/webdriverio/webdriverio/blob/v4.0/lib/webdriverio.js#L169-L172 somehow.

**Comment by georgecrawford** [comment]
Closed in favour of https://github.com/webdriverio/wdio-sync/issues/7

**Comment by christian-bromann** [comment]
Why is that an issue of the wdio-sync project?

**Comment by georgecrawford** [comment]
Erm, I'm not sure what you mean. A fix in that project fixes the bug. Is that wrong?

**Comment by christian-bromann** [comment]
oh I've just seen that we overwrite addCommand [here](https://github.com/webdriverio/wdio-sync/blob/master/index.js#L31) ... ignore me ;-)
