### ISSUE TITLE
ProtocolError: selector needs to be typeof `string`

### ISSUE THREAD

**Issue by GuilhermeAOliveira** [webdriverio/webdriverio#873]
Hello guys(@christian-bromann , @vvo ).

I'm trying to get an especific element of an array. But when I try to click on it, shows that message: 
" ProtocolError: selector needs to be typeof `string` ".

```
var x = [];
...
.getHTML('.selector-class', function(err, html) {
                        x = html[0].toString();
                        console.log(x);
                        console.log(typeof x);
                    })
                    .click(pinto)
```

...in console, I got that x typeof is a string, and I can't click.
I don't know if it's a stupid question, but I didn't find anything about this kind of error.

**Comment by christian-bromann** [comment]
@GuilhermeAOliveira please check what type the variable `pinto` is. Apparently it is not a string. The first argument of the click command is a query selector with type of string.

**Comment by GuilhermeAOliveira** [comment]
Sorry. I mean "x".

In console, when I print "typeof x" it shows "string", so I can't understand why it's not working.

Check again my example, It's right now.

Sorry for this @christian-bromann

**Comment by christian-bromann** [comment]
I don't understand the issue here? getHTML returns the html as string.

**Comment by christian-bromann** [comment]
I don't understand the issue here? getHTML returns the html as string.
