### ISSUE TITLE
[🐛 Bug]: The `exclude` capability parameter no longer ignores desired spec files when the --spec command is used to run a test

### ISSUE THREAD

**Issue by dragosMC91** [webdriverio/webdriverio#8730]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.20.9

### Node.js Version

12.22.7

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
[
        {
            browserName: 'chrome',
            'goog:platformName': 'desktop',
            exclude: [
                './test/specs/*mobile*.js'
            ],
            'goog:loggingPrefs': { browser: 'WARNING' },
            'goog:chromeOptions': {
                args: [
                    '--no-sandbox',
                    '--disable-dev-shm-usage',
                    '--window-position=1050,210',
                    '--window-size=1366,768',
                ],
            },
        },
        {
            browserName: 'chrome',
            'goog:platformName': 'mobile',
            exclude: [
                './test/specs/*desktop*.js'
            ],
            'goog:loggingPrefs': { browser: 'WARNING' },
            'goog:chromeOptions': {
                mobileEmulation: {
                    deviceName: 'iPhone 8',
                },
                args: [
                    '--window-position=1050,210',
                    'use-mobile-user-agent',
                ],
                prefs: {
                    protocol_handler: {
                        excluded_schemes: {
                            sms: false,
                            tel: false,
                        },
                    },
                },
            },
        },
    ]
```

### What happened?

After updating to the latest wdio cli version I noticed that the `exclude` capability was no longer filtering out certain tests from execution based on some naming rules.

A quick look made me thing that this issue was coming from https://github.com/webdriverio/webdriverio/pull/8456/files

### What is your expected behavior?

Given an array of capabilities, when I run a single spec file using the `--spec` command I expect the that test to run only with the capabilities which have an `exclude` attribute that does not match the name of the current test.

### Steps to reproduce:
1. pull https://github.com/dragosMC91/wdio-exclude-pattern-bug-highlight
2. yarn install in the root (not that i'm using yarn **1.22.10** and node v **12.22.7**)
3. run the dummy test via `yarn test --spec test/specs/example.desktop.test.js`

### Expected result
A single browser instance is opened for this test corresponding to the `'goog:platformName': 'desktop'` capability since the mobile capability should exclude anything which has 'desktop' within the filename via `exclude: ['./test/specs/*desktop*.js'],` 

### Actual result
The spec file is run for each capability.

### Important note
Running the spec file via `yarn test` takes the `exclude` pattern into consideration and only runs the `desktop` capability.

### Relevant log output

```typescript
2022-08-16T14:03:45.355Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,wdio.conf.js,--spec,test/specs/example.desktop.test.js
2022-08-16T14:03:45.362Z INFO @wdio/local-runner: Start worker 1-0 with arg: run,wdio.conf.js,--spec,test/specs/example.desktop.test.js
[0-0] 2022-08-16T14:03:45.670Z INFO @wdio/local-runner: Run worker command: run
[1-0] 2022-08-16T14:03:45.672Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - /test/specs/example.desktop.test.js
[0-0] 2022-08-16T14:03:45.953Z INFO webdriver: Initiate new session using the WebDriver protocol
[1-0] RUNNING in chrome - /test/specs/example.desktop.test.js
[1-0] 2022-08-16T14:03:45.957Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2022-08-16T14:03:45.981Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2022-08-16T14:03:45.981Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       'goog:platformName': 'desktop',
[0-0]       'goog:loggingPrefs': [Object],
[0-0]       'goog:chromeOptions': [Object]
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     'goog:platformName': 'desktop',
[0-0]     'goog:loggingPrefs': { browser: 'WARNING' },
[0-0]     'goog:chromeOptions': { args: [Array] }
[0-0]   }
[0-0] }
[1-0] 2022-08-16T14:03:45.985Z INFO webdriver: [POST] http://localhost:9515/session
[1-0] 2022-08-16T14:03:45.985Z INFO webdriver: DATA {
[1-0]   capabilities: {
[1-0]     alwaysMatch: {
[1-0]       browserName: 'chrome',
[1-0]       'goog:platformName': 'mobile',
[1-0]       'goog:loggingPrefs': [Object],
[1-0]       'goog:chromeOptions': [Object]
[1-0]     },
[1-0]     firstMatch: [ {} ]
[1-0]   },
[1-0]   desiredCapabilities: {
[1-0]     browserName: 'chrome',
[1-0]     'goog:platformName': 'mobile',
[1-0]     'goog:loggingPrefs': { browser: 'WARNING' },
[1-0]     'goog:chromeOptions': { mobileEmulation: [Object], args: [Array], prefs: [Object] }
[1-0]   }
[1-0] }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

The [`ConfigParser`](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-config/src/lib/ConfigParser.ts#L184-L244) is the best place to start looking here.

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by christian-bromann** [comment]
@dragosMC91 thanks for reporting!

Can you elaborate what do you think `'goog:platformName'` does and where this is defined?

**Comment by dragosMC91** [comment]
> @dragosMC91 thanks for reporting!
> 
> Can you elaborate what do you think `'goog:platformName'` does and where this is defined?

Sorry for the delayed reply I was on holiday, I think this was a custom capability which was added on my project to be able to differentiate between the mobile and desktop capabilities via a method like 
```
    isMobile: function() {
        const capabilities = browser.requestedCapabilities
            ? browser.requestedCapabilities
            : browser.capabilities;
        return capabilities['goog:platformName'] === 'mobile';
    },
```
But why does this capability matter @christian-bromann  ? the `exclude` parameter works based on file names (in this case files containing `desktop/mobile`), it has nothing to do with `goog:platformName`

**Comment by DmitrySannikov** [comment]
@dragosMC91 as far as I understand this PR will help you to understand this behaviour, but I am not sure that it is fine when spec flag ignore `exclude` parameter
https://github.com/webdriverio/webdriverio/pull/8432

**Comment by RafalSkorka** [comment]
I am also having this problem and I think `exclude` from capabilities should not be ignored when `spec` is provided from the CLI.  I would expect the code to behave like this:
```

        //Only merge capability specs if --spec is not defined
        if (spec.length === 0) {
            if (Array.isArray(capSpecs)) {
                specs = ConfigParser.getFilePaths(capSpecs, undefined, this._pathService)
            }
        }

        if (Array.isArray(capExclude)) {
            exclude = ConfigParser.getFilePaths(capExclude, undefined, this._pathService)
        }
```

**Comment by christian-bromann** [comment]
Any help on investigating this issue and/or providing a fix would be much appreciated.

**Comment by hammzj** [comment]
This is most likely related to my contribution https://github.com/webdriverio/webdriverio/pull/8432.

I thought I had accounted for `--exclude` [here](https://github.com/webdriverio/webdriverio/pull/8432/files#diff-a6371afe18573d692a9a45868ec620cbcb7be1000b7f967217384f0fe356dc96R233-R244), but I suppose there are some   discrepancies here.

However, we should _not_ remove any work done to get the `--include` parameter out of its current state as it's working as intended based on the original description of how it is supposed to function.

**Comment by hammzj** [comment]
Ah, that's right. I didn't handle for `--exclude` within that change:
https://github.com/webdriverio/webdriverio/pull/8432#issuecomment-1156425960

**Comment by dragosMC91** [comment]
> @dragosMC91 as far as I understand this PR will help you to understand this behaviour, but I am not sure that it is fine when spec flag ignore `exclude` parameter #8432

@DmitrySannikov thanks for pointing me to the right direction, I finally got around to looking over that change and address it via https://github.com/webdriverio/webdriverio/pull/9013

**Comment by dragosMC91** [comment]
@christian-bromann I tried to address the issue here: https://github.com/webdriverio/webdriverio/pull/9013
I was not able to build the project locally and run/ extend unit tests...followed the steps here https://webdriver.io/docs/contribute#set-up-project , used nvm with node 14 lts but `npm run build` fails, is there any step from the setup guide missing ?

**Comment by dragosMC91** [comment]
@hammzj I think I fixed this, btw were you able to build your project in the end, it still doesn’t work for me? https://github.com/webdriverio/webdriverio/issues/8376#issuecomment-1155243942

**Comment by hammzj** [comment]
Hey @dragosMC91, answered over in your PR. I'm gonna be in a bit of crunch time til the end of the month so I'll not be able to take a look at this for a bit 😞 I'll be around for any questions though
