### ISSUE TITLE
new wdio conf using experitest : ''experitest:accessKey'' does not exist in type 'DesiredCapabilities | W3CCapabilities'.ts(2322)

### ISSUE THREAD

**Issue by xbrys31** [webdriverio/webdriverio#8733]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.21.0

### Node.js Version

14.17.5

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
'experitest:accessKey'
```

### What happened?

Create new webdriverIO project
run the command npx wdio conf.ts
answer the questions 
first question choose In the cloud using experitest
Then provide an accesKey, ie : toto
 Access key from Experitest Cloud (EXPERITEST_ACCESS_KEY) : toto
framework cucumber
compiler : typescript

When a open the generated conf : wdio.conf.ts, i have a typescript error
on the lines
    capabilities: [{
     'experitest:accessKey': 'toto',
...

Type '{ 'experitest:accessKey': string; maxInstances: number; browserName: string; acceptInsecureCerts: true; }' is not assignable to type 'DesiredCapabilities | W3CCapabilities'.
  Object literal may only specify known properties, and ''experitest:accessKey'' does not exist in type 'DesiredCapabilities | W3CCapabilities'.ts(2322)

![image](https://user-images.githubusercontent.com/69726619/185351363-8d0817c7-c59b-4e08-99e9-016c38e7813e.png)

### What is your expected behavior?

I expect to have no typescript error 2322

### How to reproduce the bug.

Create new webdriverIO project
run the command npx wdio conf.ts
answer the questions 
first question choose In the cloud using experitest
Then provide an accesKey, ie : toto
 Access key from Experitest Cloud (EXPERITEST_ACCESS_KEY) : toto
framework cucumber
compiler : typescript

Open the generated conf : wdio.conf.ts,aan look to the typescript error
on the lines
    capabilities: [{
     'experitest:accessKey': 'toto',
...

### Relevant log output

```typescript
Type '{ 'experitest:accessKey': string; maxInstances: number; browserName: string; acceptInsecureCerts: true; }' is not assignable to type 'DesiredCapabilities | W3CCapabilities'.
  Object literal may only specify known properties, and ''experitest:accessKey'' does not exist in type 'DesiredCapabilities | W3CCapabilities'.ts(2322)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

Indeed, we don't have `experitest` in our typing definition. I suggest to add them to our [`VendorExtensions`](https://github.com/webdriverio/webdriverio/blob/4c399ec43289d5ef2237ab09029b72e7f4f430a1/packages/wdio-types/src/Capabilities.ts#L144-L185). Would you like to raise a PR for it?

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!
