### ISSUE TITLE
[🐛 Bug]: afterCommand does not fire after `browser.url`

### ISSUE THREAD

**Issue by monkpit** [webdriverio/webdriverio#8734]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.20.9

### Node.js Version

16.17.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

    browserName: 'chrome',
    acceptInsecureCerts: true

### What happened?

When trying to use `afterCommand` to detect `browser.url` calls, the hook never fires. `beforeCommand` works fine.

### What is your expected behavior?

```javascript
exports.config = {
  beforeCommand(commandName, args) {
    if (commandName === 'url') {
      console.log('Testing - beforeCommand - url was called');
    }
  },
  afterCommand(commandName, args, result, error) {
    if (commandName === 'url') {
      console.log('Testing - afterCommand - url was called');
    }
  }
}
```

The `beforeCommand` gets logged, the `afterCommand` does not trigger the log statement.

I have tried without the `if (...)` and just logged every command, and I only get a `beforeCommand` for the `url` command - no `afterCommand` fires.

I thought #7837 was related, but even with `beforeCommand` defined I still don't get the expected `afterCommand` firing.

### How to reproduce the bug.

```javascript
exports.config = {
  beforeCommand(commandName, args) {
    if (commandName === 'url') {
      console.log('Testing - beforeCommand - url was called');
    }
  },
  afterCommand(commandName, args, result, error) {
    if (commandName === 'url') {
      console.log('Testing - afterCommand - url was called');
    }
  }
}
```

### Relevant log output

```typescript
beforeCommand gets logged, afterCommand does not.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment]
Might be related to #7837

**Comment by erwinheitzman** [comment]
I cannot reproduce this when I generate a new project, can you provide a reproducible example that we can run?

**Comment by monkpit** [comment]
@erwinheitzman Thank you for looking into it - I also cannot reproduce this from scratch. I am not sure at what point between a fresh WDIO config and my current config that this issue arises. I will look more into it as I have time and will reopen this issue if I can publish reproducible example.

Thanks again!

**Comment by erwinheitzman** [comment]
@monkpit it might be the difference between the configs, what happens when you paste the config in your project?

**Comment by monkpit** [comment]
@erwinheitzman I did a little testing today and it seems it only crops up when the `wdio-video-reporter` service is enabled. I guess I'll file an issue on that repo.
