### ISSUE TITLE
[🐛 Bug]:  On windows, @wdio/selenium-standalone-service: Error: Port 4444 is already in use.

### ISSUE THREAD

**Issue by spaudel1** [webdriverio/webdriverio#8735]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.21

### Node.js Version

16

### Mode

WDIO Testrunner

### What happened?

I have experienced this issues only on windows only when you execute a test and re run the test, you get Port 4444 is already in use error. 

Port 4444 does not automatically get closed when test execution is completed. 

Workaround:
Restart the terminal (bash)

### What is your expected behavior?

I would expect the port 4444 automatically get closed when test execution is competed. 

### How to reproduce the bug.

To Reproduce this bug, use  @wdio/selenium-standalone-service
1. On Bash, run any test. For example:  ```npm test -- --spec test/specs/test.spec.js```
2. When the test completes, re-run the test ```npm test -- --spec test/specs/test.spec.js```
3. Notice following error:
`ERROR @wdio/selenium-standalone-service: Error: Port 4444 is already in use.
    at Object.start (C:\Users\username\code\org\ui\node_modules\selenium-standalone\lib\start.js:141:11)`

### Relevant log output

```typescript
ERROR @wdio/selenium-standalone-service: Error: Port 4444 is already in use. at Object.start (C:\Users\username\code\org\ui\node_modules\selenium-standalone\lib\start.js:141:11)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> I would expect the port 4444 automatically get closed when test execution is competed.

It does, can you verify it is a stale selenium-standalone process?

**Comment by spaudel1** [comment]
@christian-bromann : Previous test run did not error out. 
As part of workround, I am killing the process running on port 4444 using below command
`netstat -ano | findstr :4444`
`taskkill //F //PID <PID>`
This will terminate the process and next test run would run normally. 

Here is some additional example which indicates there was no error on previous test run. 
```
...
Spec Files:      1 passed, 1 total (100% completed) in 00:00:47

2022-08-21T04:52:44.213Z INFO @wdio/local-runner: Shutting down spawned worker
2022-08-21T04:52:44.477Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2022-08-21T04:52:44.478Z INFO @wdio/local-runner: shutting down

me@my-pc MINGW64 ~/code/test-automation/ui (master)
$ npm test -- --spec test/specs/test.spec.js 
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> webdriverio-tests@0.1.0 test
> wdio wdio.conf.js "--spec" "test/specs/test.spec.js"


Execution of 1 workers started at 2022-08-21T04:54:01.233Z

2022-08-21T04:54:01.235Z DEBUG @wdio/utils:initialiseServices: initialise service "selenium-standalone" as NPM package       
2022-08-21T04:54:01.290Z INFO @wdio/cli:launcher: Run onPrepare hook
2022-08-21T04:54:02.989Z ERROR @wdio/selenium-standalone-service: Error: Port 4444 is already in use.
    at Object.start (C:\Users\user\code\test-automation\ui\node_modules\selenium-standalone\lib\start.js:141:11)
```

**Comment by christian-bromann** [comment]
@spaudel1 can you provide a reproducible example? Testing this didn't lead me to an error.

**Comment by marcmyers** [comment]
@christian-bromann I was able to reproduce this issue with the following repo: https://github.com/marcmyers/webdriverio-7-windows-issue

**Comment by christian-bromann** [comment]
@marcmyers I am using a Mac machine and was able to run your example twice in a row with success. Maybe you could create a GitHub Action mimicking the environment you are using?

@spaudel1 have you been able to provide a reproducible example?

**Comment by colleenhobbs** [comment]
Is this issue the same as https://github.com/webdriverio/selenium-standalone/issues/599 ?

**Comment by spaudel1** [comment]
@colleenhobbs @christian-bromann I was able to resolve the this issue. The issue was with Java JDK 18 (https://www.oracle.com/java/technologies/downloads/#jdk18-windows). I uninstalled JDK 18 and reinstall Open JDK 17 using below command and now this is no longer an issue.  
`winget install Microsoft.OpenJDK.17`

**Comment by christian-bromann** [comment]
@spaudel1 thanks for the feedback. Will close the issue then.
