### ISSUE TITLE
[📖 Docs]: Save pdf

### ISSUE THREAD

**Issue by Pankaj-Pippin** [webdriverio/webdriverio#8757]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Unclear documentation, Missing documentation

### Description of the improvement / report

Hi,

https://webdriver.io/docs/api/browser/savePDF/

Please include the values for option PDFPrintOptions

Like for page size, it should be in mm, cm or inches?

A working example would be great instead of the single line example

Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
The `PDFPrintOptions` is documented on that page. It is an object with the following properties: `{ orientation, scale, background, width, height, top, bottom, left, right, shrinkToFit, pageRanges }` and their types are listed in the table. A working example can be found in the [example section](https://webdriver.io/docs/api/browser/savePDF/#example). Please let me know if you have any further questions.
