### ISSUE TITLE
[🐛 Bug]: savePdf not saving other than letter size pdf like A3

### ISSUE THREAD

**Issue by Pankaj-Pippin** [webdriverio/webdriverio#8758]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

^6.0.1

### Node.js Version

16.16.0

### Mode

Standalone Mode

### What happened?

Hi,

When using browser.savepdf we can change the value from landscape to portrait
but whatever page size we give the resulting pdf is coming with 27.9 x 21.6 cm; 11.00 x 8.50 inches which is the default value for browser.printPage

browser name: chrome
browserversion: 104.0.5112.81
platformname: windows10

// We are trying pdf to be printed for A3 paper size

browser.savePDF('screenpdf.pdf',{orientation:'portrait',
          scale: 1,
          background: true,
          width:  29.7,
          height: 42.0,
          top: 10,
          bottom: 10,
          left: 5,
          right: 5,
          shrinkToFit: true});
          
          
However, the output pdf is always 27.9 x 21.6 cm; 11.00 x 8.50 inches

Thanks

### What is your expected behavior?

It should be saving pdf with "A3" paper size but the page output is in "Letter" size

### How to reproduce the bug.

````js
var expect = require('chai').default;
describe("Browse Google Site",async ()=>
it("Google page",async ()=>
{
      //Deleting cookies
      // browser.deleteAllCookies()
      //OPENING BROWSER
      await browser.url("https://google.com");
      //To print the title of the page
      await console.log(browser.getTitle());
      //Maximize window
      browser.maximizeWindow();

  

      browser.savePDF('screenpdf.pdf',{orientation:'portrait',
          scale: 1,
          background: true,
          width:  29.7,
          height: 42.0,
          top: 10,
          bottom: 10,
          left: 5,
          right: 5,
          shrinkToFit: true});
  
   //setting timeout
    await browser.setTimeout({ 'pageLoad': 30000 })

   await browser.pause(4000);

}))
````

### Relevant log output

```typescript
No error
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by Pankaj-Pippin** [comment]
Hi,

Forgot to mention, we tried to give different page size too but it always fallback to default "Letter" size

**Comment by christian-bromann** [comment]
@Pankaj-Pippin thanks for filing the issue. Can you provide some WebdriverIO logs?

**Comment by christian-bromann** [comment]
These are not the WDIO logs, this looks like your terminal output. Check if you have `outputDir` set which determines where the log files are stored.

**Comment by Pankaj-Pippin** [comment]
Hi,

Will this help?

logLevel: 'error',

[wdio-chromedriver.log](https://github.com/webdriverio/webdriverio/files/9423441/wdio-chromedriver.log)
[log (1).log](https://github.com/webdriverio/webdriverio/files/9423717/log.1.log)
[error.log](https://github.com/webdriverio/webdriverio/files/9423718/error.log)

Thanks

**Comment by christian-bromann** [comment]
The logs show that WebdriverIO is sending the correct values to Chromedriver:

```
[90m2022-08-25T09:59:29.427Z[39m [96mINFO[39m [97mwebdriver[39m: [POST] http://localhost:9515/session/7394087ea32f441477e37f85cc1fb9c2/print
[90m2022-08-25T09:59:29.427Z[39m [96mINFO[39m [97mwebdriver[39m: [33mDATA[39m {
  orientation: 'portrait',
  scale: 1,
  background: true,
  width: 29.7,
  height: 42,
  top: 10,
  bottom: 10,
  left: 5,
  right: 5,
  shrinkToFit: true
}
```

So we should investigate if this is a problem within the WebDriver spec or in Chromedriver.

**Comment by Pankaj-Pippin** [comment]
Hi

I tried running in linux too same issue coming.

is it coming to me only ?

[out_Linux.log](https://github.com/webdriverio/webdriverio/files/9424263/out_Linux.log)
[error_Linux.log](https://github.com/webdriverio/webdriverio/files/9424264/error_Linux.log)

Thanks

**Comment by BorisOsipov** [comment]
It is chromedriver [issue](https://bugs.chromium.org/p/chromedriver/issues/detail?id=3996&q=print&can=2). Nothing to fix from our side.

**Comment by christian-bromann** [comment]
@BorisOsipov thanks for looking up the issue in the Chromedriver project. Closing.
