### ISSUE TITLE
[🐛 Bug]: Appium does _not_ start with Node v18 but works with Node v16

### ISSUE THREAD

**Issue by andrew-hm** [webdriverio/webdriverio#8760]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

^7.23.0

### Node.js Version

18.7.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  specs: [ './e2e/specs/**/*.spec.js' ],
  reporters: [ 'spec' ],
  capabilities: [
    {
      'appium:platformVersion': '15.5',
      'appium:deviceName': 'iPhone Simulator',
      browserName: 'Safari',
      platformName: 'iOS'
    }
  ],
  services: [ [ 'appium' ] ],
  maxInstances: 1,
  execArgv: [],
  sync: false,
  deprecationWarnings: true,
  waitforTimeout: 15000,
  connectionRetryTimeout: 240000,
  connectionRetryCount: 1,
  framework: 'jasmine',
  runner: 'local',
  port: 4723,
  baseUrl: 'http://0.0.0.0:4000/',
  suites: { home: [ './e2e/specs/home.spec.js' ] },
}
```

### What happened?

Using node v16, this works as expected: `WDIO_LOG_PATH=wdio.log WDIO_DEBUG=trace wdio --suite home`. The ios simulator boots up, loads up safari, loads the website running locally and passes the tests.

Using node v18, the same command does not work. It fails to launch the ios simulator. I can go between node v16 and v18 for chrome driver, safari driver as expected, this is isolated to appium as a service as listed above.

I traced the error down to the the webdriver package, specifically request/factory which returns a NodeJSRequest. From here I'm not sure if its the implemented _libRequest that relies on got that is the issue or an unpredictable behavior with EventEmitter in node v18.

When makeRequest is called by the startWebDriverSession from utils, its either an issue with the call to this.emit('request') or afterwards when making call to this._request which ends up making a call to the _libRequest from NodeJSRequest.

I feel like it is related to the EventEmitter either from this library or got's, something could of changed with node 18, as it usually does. I also tried using node v18.2.0 with same result. Its also entirely possible since we're not using esm module type this could be it too. I say this because when i run yarn why got, it shows as got@11.8.5 and neglects to use the version of got as seen in the webdriver/package.json of ^12.1.0. should we be using wedriver@next or is it possible the regular tag releases aren't getting the updates from main?

i dont expect this to get fixed as its pretty low level and can i can get around by using node v16 instead. wanted to report it in case anyone else came across the same thing and started pulling their hair out.

### How to reproduce the bug.

use node 18 and run `WDIO_LOG_PATH=wdio.log WDIO_DEBUG=trace wdio --suite home` with the above wdio.conf.js

### Relevant log output

```typescript
dont pay attention to the logs, they are not indicative of the issue as the result from the appium not starting earlier up the call stack

[0-0]     at ClientRequest.<anonymous> (./node_modules/got/dist/source/core/index.js:970:111)
[0-0]     at Object.onceWrapper (node:events:642:26)
[0-0]     at ClientRequest.emit (node:events:539:35)
[0-0]     at ClientRequest.emit (node:domain:475:12)
[0-0]     at ClientRequest.origin.emit (./node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
[0-0]     at Socket.socketErrorListener (node:_http_client:454:9)
[0-0]     at Socket.emit (node:events:527:28)
[0-0]     at Socket.emit (node:domain:475:12)
[0-0]     at emitErrorNT (node:internal/streams/destroy:151:8)
[0-0]     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
[0-0]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Hey @andrew-hm 

thanks for reporting and investigating the issue. I am not sure where this error could be located. Is there something like this reported in the Appium project?

**Comment by christian-bromann** [comment]
Thanks to @harsha509 who reminded me that in Node.js v18 you need to set `hostname` to `127.0.0.1` to connect to Appium. I think we should update [the default value](https://github.com/webdriverio/webdriverio/blob/da229d18a630c18ec826669af70ec74e40165826/packages/webdriver/src/constants.ts#L17) from `localhost` to `127.0.0.1`.

**Comment by andrew-hm** [comment]
@christian-bromann thanks, i tried that but it didnt work with node v18. it continued to work with node v16 though. i even tried forcing appium to `127.0.0.1` as well on its address args, but to no avail. this is the config i ended up with. works in v16 but not v18. i appreciate the help. ciao!

```js
{
  specs: [ './e2e/specs/**/*.spec.js' ],
  reporters: [ 'spec' ],
  capabilities: [
    {
      browserName: 'Chrome',
      'appium:automationName': 'UiAutomator2',
      platformName: 'Android',
      'appium:platformVersion': '12.0',
      'appium:deviceName': 'Pixel',
      'appium:orientation': 'PORTRAIT'
    },
    {
      platformName: 'iOS',
      'appium:automationName': 'XCUITest',
      'appium:deviceName': 'iPhone Simulator',
      'appium:platformVersion': '15.5',
      browserName: 'Safari'
    }
  ],
  services: [
    'shared-store',
    [
      'appium',
      {
        args: {
          port: 4723,
          logLevel: 'debug',
          address: '127.0.0.1',
          allowInsecure: 'chromedriver_autodownload'
        }
      }
    ]
  ],
  maxInstances: 1,
  sync: false,
  waitforTimeout: 15000,
  hostname: '127.0.0.1',
  port: 4444,
  connectionRetryTimeout: 240000,
  connectionRetryCount: 0,
  runner: 'local',
  specFileRetries: 0,
  baseUrl: 'http://192.168.1.172:4000/',
  suites: { home: [ './e2e/specs/home.spec.js' ] },
}```

**Comment by andrew-hm** [comment]
I'm betting this all goes away when I update the packages to esm, `type:module` and pull in the `@next` tag.

**Comment by andrew-hm** [comment]
found it, `https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-appium-service/src/launcher.ts#L18` needs to be set to `127.0.0.1` for node 18 to work

**Comment by christian-bromann** [comment]
@andrew-hm good catch! Mind raising a PR?

**Comment by andrew-hm** [comment]
shirley, no problem

**Comment by christian-bromann** [comment]
This got fixed in v8, if folks running v7 and stumble upon this, please set the hostname option for the Appium service to `127.0.0.1` manually. Thanks!
