### ISSUE TITLE
Implement syslog-style log levels

### ISSUE THREAD

**Issue by georgecrawford** [webdriverio/webdriverio#878]
I find these options quite confusing, and not entirely useful: https://github.com/webdriverio/webdriverio/blob/master/lib/utils/Logger.js#L16.

Could we consider using the standardised syslog levels (https://en.wikipedia.org/wiki/Syslog#Severity_level), so a user can clearly increase/decrease noise when desired?

**Comment by christian-bromann** [comment]
Agree! Especially since we now have separate packages. I would like to apply the same approach like in the Appium project. This would require to have a dedicated `wdio-logger` package.

**Comment by georgecrawford** [comment]
Just a thought - is `Logger` actually anything more than a reporter? As long as we fire events for `command`, `result` and `error` (which we already do), and add further events for `log` and `debug`, there remains no reason to pass the logger instance around webdriverio, and it can instead become a simple reporter.

**Comment by christian-bromann** [comment]
Right but it does not only log on those events but also when a certain class or function requires the module to log an info or a warning.

**Comment by georgecrawford** [comment]
Right, but there are only three uses of that, and they could all easily become events instead:
```
lib/commands/debug.js:32:10:   this.logger.debug()
lib/webdriverio.js:247:17:   logger.printException(e.type || 'Error', e.message, stacktrace)
lib/utils/RequestHandler.js:183:22:   this.logger.log('SET SESSION ID ' + this.sessionID)
```
It's just a thought.

**Comment by christian-bromann** [comment]
I don't think it is a good idea. I would like to require that package also in services and frameworks to log certain events and we can't make events out of everything.

**Comment by georgecrawford** [comment]
Cool. No prob.

**Comment by georgecrawford** [comment]
In terms of a user adding useful log lines to a reporter's output, I've added https://github.com/webdriverio/webdriverio/pull/1020 which solves this use-case for me.

**Comment by msegado** [comment]
> I find these options quite confusing

This is the main issue I'm facing as a new user; I can guess what "silent", "verbose", and "error" do, but I'm not sure what "command", "data", or "result" are and don't know what a reasonable default would be. Adding some terse descriptions in the docs and `wdio` setup wizard would probably help with this... I'd offer to do so but need to figure it out myself first ;-)

For inspiration, here is the log level section from Selenium's docs:

> For WebDriver the following log levels have been selected (ordered from highest to lowest):
> 
> OFF: Turns off logging
> SEVERE: Messages about things that went wrong. For instance, an unknown command.
> WARNING: Messages about things that may be wrong but was handled. For instance, a handled exception.
> INFO: Messages of an informative nature. For instance, information about received commands.
> DEBUG: Messages for debugging. For instance, information about the state of the driver.
> ALL: All log messages. A way to collect all information regardless of which log levels that are supported.

**Comment by christian-bromann** [comment]
@msegado created an issue for it. We've planned to refactor the logging anyway soon. 😉

**Comment by msegado** [comment]
Awesome =) Makes a bit more sense now that I've actually run a test and seen the logs, too! (...which didn't take long by the way; nice job on the installation/setup UX.)

**Comment by christian-bromann** [comment]
see #1982

Let's also figure out if the banner at the top is necessary or not

**Comment by christian-bromann** [comment]
This will land in v5
