### ISSUE TITLE
[🐛 Bug]: input.setValue() / input.clearValue does not trigger `input` event

### ISSUE THREAD

**Issue by vvscode** [webdriverio/webdriverio#8787]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.21.0

### Node.js Version

v16.17.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
  browserName: 'chrome',
  // osx
}
```

### What happened?

In my code, I use reaction on the `input` event. When I enter some value with `.setValue('123')` it works as expected. But when I do `.setValue('')` or (`.clearValue()) the even is not emited

### What is your expected behavior?

Trigger `input` (and other events) on input clear

### How to reproduce the bug.

```
// jest
const { remote } = require('webdriverio');

function sleep(x) {
  return new Promise((resolve) => setTimeout(resolve, x));
}

jest.setTimeout(30000);

describe('List of paragraphs', () => {
  let browser;
  let input;
  let button;
  // beforeAll(async () => {});

  beforeEach(async () => {
    browser = await remote({
      capabilities: {
        browserName: 'chrome',
      },
    });
    await browser.url('https://xvjhzt.csb.app/');
    await browser.$('input').waitForExist({
      timeout: 5000,
    });
    input = await browser.$('input');
    button = await browser.$('button');
  });
  afterEach(async () => {
    await browser.deleteSession();
    await sleep(1000);
  });

  async function isInputVisible() {
    return await input.isDisplayed();
  }

  async function getParagraphs() {
    const pList = await browser.$$('p');
    const pListText = await Promise.all(pList.map((p) => p.getText()));
    return pListText;
  }

  async function type(str) {
    return await input.setValue(str);
  }

  async function clickButton() {
    return await button.click();
  }

  async function isButtonHidden() {
    return !(await button.isDisplayed());
  }

  async function getInputValue() {
    return await input.getValue();
  }

  only('renders button which appears on input and disappears on clear', async () => {
    await type('123');

    expect(await isButtonHidden()).toBe(false);

    // await type('');
    await input.clearValue();
    await sleep(5000);
    expect(await isButtonHidden()).toBe(false);
    await sleep(5000);
  });
});

```

### Relevant log output

```typescript
Video: https://monosnap.com/file/9IT2tGo2CGqKZk5QhMCDkAXR6YevNN

URL to test: https://xvjhzt.csb.app/

Manual manipulation works fine
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by vvscode** [comment]
Code works if I use 
```
    await input.keys(['Backspace', 'Backspace', 'Backspace']);
```
but it looks more like a workaround

**Comment by BorisOsipov** [comment]
@vvscode it is well known chromedriver issue. 
see https://github.com/SeleniumHQ/selenium/issues/6741 or https://bugs.chromium.org/p/chromedriver/issues/detail?id=2702&q=&sort=-id&colspec=ID%20Status%20Pri%20Owner%20Summary

**Comment by vvscode** [comment]
@BorisOsipov  maybe. In my case, it's not React code (just mention the difference)

**Comment by christian-bromann** [comment]
@vvscode thanks for raising the issue. WebdriverIO has no influence which events are send. This should either be reported in the WebDriver spec or the driver as WebdriverIO is not responsible for actually executing the command. Happy to discuss this further if you have any suggestions, otherwise closing.

**Comment by vvscode** [comment]
@christian-bromann  I do understand your point (as a developer)

But as a consumer of your API I do expect to have a solution in the wdio wrapper (which is doable) =)

**Comment by christian-bromann** [comment]
> But as a consumer of your API I do expect to have a solution in the wdio wrapper (which is doable) =)

What are you suggesting?

**Comment by vvscode** [comment]
I have a workaround with typing backspace - why don't add it on the WD level?

it's a hack, but it's for users

```
input.clearValue();
input.sendKeys(BACKSPACE);
```

**Comment by christian-bromann** [comment]
> why don't add it on the WD level?

Because it is a hack and might cause other side effects.

**Comment by vvscode** [comment]
> it's a hack

that's why I do propose to localize it with proper abstraction, instead of making all the consumers repeat this from project to project 

> and might cause other side effects

Like what?
