### ISSUE TITLE
can not run files in a browser context

### ISSUE THREAD

**Issue by dtracers** [webdriverio/webdriverio#879]
Hi I am trying to use webdriver IO so I can run unit tests automatically that require a browser context.

I was running a test and it said 'document' not defined while compiling.

I have it set up to use the chrome driver with selenium. and those appear to be working fine.

Is document only defined inside the mocha tests and not outside it?
I also need to load css files using the link.
Is this not possible to create unit tests for?
It will not let me load any html files.

**Comment by christian-bromann** [comment]
WebdriverIO was made to do e2e tests _not_ unit tests. You can access document properties by calling

```js
browser.execute(function() {
    return document.title;
}).then(function(res) {
    console.log(res.value); // returns document.title
});
```

You can write unit tests within the browser context using zuul
