### ISSUE TITLE
Make session ID available in browser global?

### ISSUE THREAD

**Issue by indolering** [webdriverio/webdriverio#880]
I'm using the session ID to deterministically generate variables used in my tests so that I can trace DB and log entries back to specific tests.  Checking `browser.requestHandler.sessionID` returned an invalid ID on BrowserStack.  They instead suggested that I use:

```
browser.session().then(function(sessionData) {
// sessionData.sessionId
})
```

This is a bit awkward because it introduces async behavior where none is required ... if my unit test is running, then the session ID should be available!

I would prefer it if the browser global included the browser ID as a parameter and abstract away differences between vendors.

**Comment by christian-bromann** [comment]
You can access the session id via `browser.requestHandler.sessionId`

**Comment by indolering** [comment]
`browser.requestHandler.sessionID`*
