### ISSUE TITLE
no such alert error in the docker container

### ISSUE THREAD

**Issue by halit-carbon** [webdriverio/webdriverio#8800]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v7

### Node.js Version

v18.6.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
browserName: chrome
browserVersion: 104
platform : Docker container
[
            '--disable-infobars',
            '--disable-web-security',
            '--disable-extensions',
            '--disable-dev-shm-usage',
            '--disable-notifications',
            '--ignore-certificate-errors',
            '--use-fake-ui-for-media-stream',
            '--use-fake-device-for-media-stream', 
            '--window-size=1920,1080',
        ];
```

### What happened?

I am having an issue running my tests in a Docker container (Linux based) and also selenoid. There are some alerts which I am not able to interact with. When the alerts or prompt come up, I do not handle them, I get an error about having an unhandled alert. When I try to interact with the alert, I get the error "no such alert".

Note: this code works without docker container.

[0-0] Error in "Patient app - Login alert example"
e2e            | no such alert: no such alert
e2e            |   (Session info: chrome=104.0.5112.79)
e2e            |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
e2e            |     at async UserContext.<anonymous> (/usr/lib/wdio/__tests__/specs/patient/testHalo.spec.ts:12:16)

[0-0] Error in "Patient app - Login prompt example"
e2e            | no such alert: no such alert
e2e            |   (Session info: chrome=104.0.5112.79)
e2e            |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
e2e            |     at async UserContext.<anonymous> (/usr/lib/wdio/__tests__/specs/patient/testHalo.spec.ts:22:16)

### What is your expected behavior?

I want to handle alert in docker container. I want to enter some data in prompt and accept it.

### How to reproduce the bug.

it('alert example', async () => {
        await browser.url('https://demo.automationtesting.in/Alerts.html');

        await $('//*[text()="Alert with OK & Cancel "]').click();
        await $('//*[text()="click the button to display a confirm box "]').click();
        expect(await browser.getAlertText()).toContain('Press a Button !');
        await browser.acceptAlert();
        expect(await $("[id='demo']").getText()).toContain('You pressed');
    });

    it('prompt example', async () => {
        await browser.url('https://demo.automationtesting.in/Alerts.html');

        await $('//*[text()="Alert with Textbox "]').click();
        await $('//*[text()="click the button to demonstrate the prompt box "]').click();
        expect(await browser.getAlertText()).toContain('Please enter your name');
        await browser.sendAlertText('Test prompt');
        await browser.acceptAlert();
        expect(await $("[id='demo1']").getText()).toContain('Test prompt');
    });

### Relevant log output

```typescript
[0-0] Error in "Patient app - Login alert example"
e2e            | no such alert: no such alert
e2e            |   (Session info: chrome=104.0.5112.79)
e2e            |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
e2e            |     at async UserContext.<anonymous> (/usr/lib/wdio/__tests__/specs/patient/testHalo.spec.ts:12:16)


[0-0] Error in "Patient app - Login prompt example"
e2e            | no such alert: no such alert
e2e            |   (Session info: chrome=104.0.5112.79)
e2e            |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
e2e            |     at async UserContext.<anonymous> (/usr/lib/wdio/__tests__/specs/patient/testHalo.spec.ts:22:16)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Can you provide some WDIO logs?

**Comment by halit-carbon** [comment]
[wdio-0-0.log](https://github.com/webdriverio/webdriverio/files/9477263/wdio-0-0.log)

**Comment by christian-bromann** [comment]
Just from looking at the looks I am not really sure what is going on. Any investigations or leads to how to resolve this would be appreciated, thanks!

**Comment by christian-bromann** [comment]
I will go ahead and close this as it is unclear if this is related to a bug within WebdriverIO. If there is anything I can do to help investigate this, please let me know. Cheers!
