### ISSUE TITLE
FR: method for performing action on set of nodes

### ISSUE THREAD

**Issue by lorensr** [webdriverio/webdriverio#883]
For instance in this example, I'd like to click all elements that match a selector, instead of just the first one.

```coffeescript
elems = browser.elements '.item-checkbox'
console.log elems
for elem in elems
  # neither of these work
  browser.click elem
  elem.click()
```
```
{ state: 'success',
  sessionId: '66fe2543-7b28-40e7-8bbb-d7da7d2af928',
  hCode: 1564933402,
  value: 
   [ { ELEMENT: '702' },
     { ELEMENT: '703' },
     { ELEMENT: '704' },
     { ELEMENT: '705' },
     { ELEMENT: '706' },
     { ELEMENT: '707' } ],
  class: 'org.openqa.selenium.remote.Response',
  status: 0 }
```
http://stackoverflow.com/questions/33724967/how-to-click-all-matching-elements-in-webdriver

**Comment by christian-bromann** [comment]
Are you using the wdio testrunner?

**Comment by lorensr** [comment]
I don't think so – this is using http://chimpjs.com/ inside a cucumber `When` definition

**Comment by christian-bromann** [comment]
ahh ok, so I guess all commands are synchronous. Instead of using `click` you need to use [`elementIdClick.html`](http://webdriver.io/api/protocol/elementIdClick.html). As you can see you get the rare Selenium references back and the click command only understands query selectors. Let me know if that works for you.

**Comment by christian-bromann** [comment]
Well I often ask myself if whether or not this is useful. In general this is not a common use case. As a person you also can't click on multiple elements at the same time.
