### ISSUE TITLE
[🐛 Bug]: "ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook" persists although tests passed

### ISSUE THREAD

**Issue by louis57** [webdriverio/webdriverio#8835]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.24.0

### Node.js Version

v16.14.0

### Mode

WDIO Testrunner

### What happened?

I have used WebDriverIO and run tests on Browserstack (BS). This is my `wdio.conf.ts` to run test on BS

```
    user: process.env.BROWSERSTACK_USERNAME__,
    key: process.env.BROWSERSTACK_ACCESS_KEY__,
    services: [
        ['browserstack', {
            browserstackLocal: true
        }],
    ],`
```
This conf works fine until last few days, when I execute the tests from my laptop to run on BS, suddenly I get this error `ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook`, and it persists although all tests passed, as per screenshot. And I haven't changed anything in my `wdio.conf.ts` in months. This error just randomly shows up and persists.
![error2](https://user-images.githubusercontent.com/12949146/189373315-7a9ff671-32c8-4b54-9880-0318d1177a92.png)

Notes:
- I don't use/have `onPrepare ` hook
- This error doesn't show when I execute the tests from my local chrome
- My Gitlab Pipeline trigger for the job using the same `wdio.conf.ts` works fine without this error. Only happens when I execute tests from my laptop to run on BS

I have tried many solutions I could find: 
- uninstall and reinstall the Binaries (cli, services, etc with latest versions), 
- delete node_modules and npm install again,  
- try to pull up a new wdio.conf with `npm init wdio .`

nothing solves it. 

### What is your expected behavior?

`ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook` should not show when tests passed

### How to reproduce the bug.

- Clone webdriverIO Browserstack repo
- Run local test 

It's hard to reproduce, since I also can't reproduce it on another laptop 

### Relevant log output

```typescript
Execution of 1 workers started at 2022-09-09T14:01:52.439Z

2022-09-09T14:01:52.689Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:700:9)
    at Object.execFile (node:child_process:327:17)
    at D:\git-projects\integrity-line-api\e2e\node_modules\browserstack-local\lib\Local.js:88:34
    at LocalBinary.binaryPath (D:\git-projects\integrity-line-api\e2e\node_modules\browserstack-local\lib\LocalBinary.js:146:7)
    at Local.getBinaryPath (D:\git-projects\integrity-line-api\e2e\node_modules\browserstack-local\lib\Local.js:251:19)
    at Local.start (D:\git-projects\integrity-line-api\e2e\node_modules\browserstack-local\lib\Local.js:83:10)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at bound  (node:internal/util:346:12)

Continue...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by Ankit098** [comment]
@christian-bromann This is quite weird - especially since @louis57 mentioned they are only seeing this on a particular machine... will check if this is a bug.

**Comment by louis57** [comment]
@christian-bromann 
I mean, if I change my `wdio.conf` to run tests on browser on my laptop with this `services: ['chromedriver'],`, then I don't have any error. What strange is, it was working just fine one minute before, and next run this error just shows up and persists. 

I have contacted Browserstack Support, they also suggested to update Browserstack service to latest version. I did, and it doesn't help 

> This error doesn't show when I execute the tests from my local chrome
What do you mean by that?

**Comment by christian-bromann** [comment]
> then I don't have any error.

Yeah since you don't run through the BS servíce.

**Comment by louis57** [comment]
I found out, there is a Browserstack binary downloaded implicitly on my laptop on the runtime, every time I execute tests. And somehow the file was corrupted at the time I reported this issue with `@wdio/cli:utils` . So I removed this corrupted file, and everything is back to normal. no error occurs.
I close this issue. Thanks for your support.

**Comment by lyucos** [comment]
> 
Hi! I have the same issue. Could you tell, how did you located corrupted file?

**Comment by lyucos** [comment]
> I found out, there is a Browserstack binary downloaded implicitly on my laptop on the runtime, every time I execute tests. And somehow the file was corrupted at the time I reported this issue with `@wdio/cli:utils` . So I removed this corrupted file, and everything is back to normal. no error occurs. I close this issue. Thanks for your support.

Hi! I have the same issue. Could you tell, how did you located corrupted file?

**Comment by Ankit098** [comment]
@lyucos the binary would be in the `~/.browserstack` folder.. It is downloaded when you use the binding for the first time (after which the downloaded one is reused).

**Comment by AnushaPattanKotreshkumar** [comment]
I am facing the same issue, Can anyone please specify the steps to resolve this issue?  @louis57 @christian-bromann 
I had gone through above comments and deleted the binary file, but it was throwing Binary file is missing. Please assist. Thanks in advance.

2022-12-07T01:52:16.919Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:700:9)
    at Object.execFile (node:child_process:327:17)
    at C:\Anusha\wdio-project\OLS-WDIO\ols_ui_mobile\node_modules\browserstack-local\lib\Local.js:88:34
    at LocalBinary.binaryPath (C:\Anusha\wdio-project\OLS-WDIO\ols_ui_mobile\node_modules\browserstack-local\lib\LocalBinary.js:146:7)
    at Local.getBinaryPath (C:\Anusha\wdio-project\OLS-WDIO\ols_ui_mobile\node_modules\browserstack-local\lib\Local.js:251:19)
    at Local.start (C:\Anusha\wdio-project\OLS-WDIO\ols_ui_mobile\node_modules\browserstack-local\lib\Local.js:83:10)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at bound  (node:internal/util:346:12)

**Comment by malisanjay5433** [comment]
INFO @wdio/cli:launcher: Run onPrepare hook
2023-01-04T06:53:37.489Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: Appium exited before timeout (exit code: 1)
    at ChildProcess.<anonymous> 
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)

Continue...
2023-01-04T06:53:37.492Z INFO @wdio/cli:launcher: Run onWorkerStart hook


**I have done changes in the wdio.conf.js, At default service section you have to replace with the following code. it will work for sure. if same issues you're encountered with.**  
```
services: [
    [
      "appium",
      {
        args: {
          address: "localhost",
          port: 4723,
          relaxedSecurity: true,
        },
        logPath: "./",
      },
    ],
  ],
```

**Comment by lyucos** [comment]
> @lyucos the binary would be in the `~/.browserstack` folder.. It is downloaded when you use the binding for the first time (after which the downloaded one is reused).

Hi! Sorry, but could you help where I can find exactly this files?

**Comment by samuelfreiberg** [comment]
@christian-bromann What does the browserstack service responsible for?

I'm seeing this error intermittently in my tests, and it's starting to become a bigger issue with more failures.

Do you have any background on this? @louis57  @Ankit098

**Comment by vinitaqualizeal** [comment]
This error appears because we do not end the appium session. Run this from cmd or run cmd window - "taskkill /F /IM node.exe"

This ends node.js last running session and after this you won't receive error in the next run. However, onPrepare hook error is not going to impact your test run.

**Comment by QuintilianoNery** [comment]
Hello, it is also possible to solve this problem, run the local file, it will ask for your credentials, once this is done, just run the test again and it will work.


[BrowserStackLocal-win32.zip](https://github.com/webdriverio/webdriverio/files/13311192/BrowserStackLocal-win32.zip)
