### ISSUE TITLE
IE Cant Delete Specific Cookies

### ISSUE THREAD

**Issue by kmgilbert100** [webdriverio/webdriverio#884]
In Internet Explorer if you try and delete a specific cookie like so 

```
.deleteCookie('test')
```

It does not work... however

```
.deleteCookie()
```

Does successfully delete all cookies. The single deletion works in firefox in chrome just not IE.

Anyone else have this issue or able to replicate?

**Comment by christian-bromann** [comment]
This is an iedriver issue and I don't see anything I can do about it (in terms of workarounds). Please file an issue on the iedriver issue tracker. Thanks!
