### ISSUE TITLE
[🐛 Bug]: Jest Matchers not available in expect

### ISSUE THREAD

**Issue by umerkk** [webdriverio/webdriverio#8862]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.24

### Node.js Version

14

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [
		{
			maxInstances: 5,
			//
			browserName: 'chrome',
			'goog:chromeOptions': {
				args: ["--headless", "--no-sandbox"]
			}
		},
	],
```

### What happened?

I migrated from V4 to V7. Added all new dependencies i.e local-runner etc.
I've been using the following syntax in my tests

`expect(browser.isExisting("#obf-OverlayBackground")).toBe(true);`
which i had to change to 
`expect($("#obf-TPromptTitle").isExisting()).toBe(value);`

However, i do get an error saying `to.Be()` is not a function and printing the expect objects confirms that.
However on the docs, it says the expect object extends JEST Matchers. https://webdriver.io/docs/assertion

I am not sure what i am doing wrong here.

### How to reproduce the bug.

n/a

### Relevant log output

```typescript
TypeError: expect(...).toBe is not a function
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
The way you call `isExisting`, e.g. `browser.isExisting("#obf-OverlayBackground")` is not valid WebdriverIO syntax so this obviously fails.

> TypeError: expect(...).toBe is not a function

Can you provide a code snippet that is throwing this error?

**Comment by umerkk** [comment]
Browser.isExisting was an old syntax working in v4. 

My new syntax is 

expect($("#obf-TPromptTitle").isExisting()).toBe(value);

This is the one throwing the error.

**Comment by christian-bromann** [comment]
> Browser.isExisting was an old syntax working in v4

This version of WebdriverIO is not compatible with `expect-webdriverio`.


> expect($("#obf-TPromptTitle").isExisting()).toBe(value);

Why not just do `await expect($("#obf-TPromptTitle")).toBeExisting()`?

**Comment by umerkk** [comment]
As you can see i am looking for jest matchers and not just isExisting functionality. 

The question is, how can i get them and which versions are incompatible. 

My webdriverio is on 7.24.0.

**Comment by christian-bromann** [comment]
I check on a new set up project and I had no issues using Jest matchers, e.g.:

```js
await browser.url('https://google.com')
expect(await browser.getUrl()).toBe('https://www.google.com/')
```

I expect that some package is not updated. Please try to update all. Can you provide a minimal reproducible example otherwise?

**Comment by umerkk** [comment]
This is what my dependences looks like. I am using gulp-webdriver as task runner.

  "devDependencies": {
    "@wdio/cli": "^7.24.0",
    "@wdio/codemod": "^0.12.0",
    "@wdio/jasmine-framework": "^7.24.0",
    "@wdio/junit-reporter": "^7.24.0",
    "@wdio/local-runner": "^7.24.0",
    "@wdio/spec-reporter": "^7.24.0",
    "gulp": "^4.0.2",
    "gulp-change": "1.0.0",
    "gulp-clean-css": "^4.2.0",
    "gulp-json-editor": "2.2.1",
    "gulp-nuget-pack": "^0.1.0",
    "gulp-rename": "1.2.2",
    "gulp-sass": "~4.0.2",
    "gulp-sourcemaps": "^2.6.5",
    "gulp-tslint": "6.1.2",
    "gulp-typescript": "^5.0.1",
    "gulp-uglify": "2.0.0",
    "gulp-util": "^3.0.8",
    "gulp-webdriver": "~4.0.0",
    "husky": "^8.0.1",
     "istanbul-instrumenter-loader": "^3.0.1",
    "jasmine-ajax": "3.1.1",
    "jasmine-core": "2.5.0",
    "jscodeshift": "^0.13.1",
    "karma": "^6.3.15",
    "karma-chrome-launcher": "^3.1.0",
    "karma-coverage": "^2.2.0",
    "karma-edge-launcher": "0.4.2",
    "karma-firefox-launcher": "^1.1.0",
    "karma-ie-launcher": "1.0.0",
    "karma-jasmine": "^1.1.0",
    "karma-jasmine-ajax": "0.1.13",
    "karma-junit-reporter": "^1.1.0",
    "karma-phantomjs-launcher": "1.0.2",
    "karma-spec-reporter": "0.0.31",
    "karma-webpack": "^4.0.2",
    "npm-run-all": " ^4.1.5",
    "parallel-webpack": "^2.4.0",
    "phantomjs-prebuilt": "^2.1.16",
    "selenium-standalone": "6.24.0",
    "source-map-loader": "^0.2.4",
    "terser-webpack-plugin": "^2.2.1",
    "tslint": "3.15.1",
    "typescript": "^3.4.1",
    "webdriverio": "~7.0.0",
    "webpack": "^4.32.2",
    "webpack-bundle-analyzer": "^3.3.2",
    "webpack-merge": "^4.2.1",
    "webpackbar": "^4.0.0",
    "yargs": "^14.2.0"

**Comment by christian-bromann** [comment]
Can you provide a reproducible example?

**Comment by DmytroCh** [comment]
Hi @christian-bromann , I have same problem with [stringContaining()](https://jestjs.io/docs/expect#expectstringcontainingstring) jest matcher. Here is a fail example project: https://github.com/DmytroCh/expect-error-wdio
