### ISSUE TITLE
Syntax error in Cucumber JS causes WebdriverIO to hang with no error message.

### ISSUE THREAD

**Issue by sheltonial** [webdriverio/webdriverio#888]
Using the Cucumber framework does not raise error messages when they occur, it just hangs. Finding the cause of the hang is then a nightmare trial and error process. An example is requiring in a file that does not exist eg. `var foo = require('fileThatDoesNotExist');`.

Using the Mocha framework with WebdriverIO seems to raise errors fine.

**Comment by christian-bromann** [comment]
What Cucumber version are you using? Please try `"cucumber": "~0.5.3”`

**Comment by sheltonial** [comment]
Using 0.7.0. Tried going back to 0.5.3 but the same issue occurs.

**Comment by christian-bromann** [comment]
I guess the problem is that cucumber only provides a callback. If that callback didn't get called it hangs. You can try to implement your steps like this:

```js
it(..., function(done) {
    var steps = browser
                           .click(..)
                           .then(...) 
                           .getTitle()
                           .then(...)
                           .click(...)
                           .call(done);

    steps.catch(done);
})

**Comment by sheltonial** [comment]
Thanks, but that solution is unrelated to the initial question, which is around requiring in a file that does not exist.

This is how to replicate the issue in your examples...
1. pull down webdriver `git pull git@github.com:webdriverio/webdriverio.git`
2. `npm install`
3. `npm install cucumber@0.7.0` - cucumber is not in `package.json`, had to to this to get it working
4. Fix path error in `examples/wdio/wdio.cucumber.conf.js`... in `cucumberOpts.require` the path needs to be `'./examples/wdio/runner-specs/cucumber/step-definitions.js'` (just added `wdio`)
5. confirm it runs ok - `./bin/wdio examples/wdio/wdio.cucumber.conf.js`
6. now, let's break it! open `examples/wdio/runner-specs/cucumber/step-definitions.js`, and require in a file which does not exist (eg. `var foo = require('foo');`).
7. now run again with `./bin/wdio examples/wdio/wdio.cucumber.conf.js` and it will hang with no error messaging.

**Comment by jamesseanwright** [comment]
I'm encountering the same issue. Going to run CucumberJS directly with a mock of the global `browser` object to see what syntax errors occur. In the meantime, it would be great to have this fixed. I'm more than happy to do a pull request if I ever figure it out!

**Comment by jamesseanwright** [comment]
Just a brief update: I pulled in my code manual via CommonJS and experienced no errors. Additionally, I transpiled my ES6/7 code with the Babel CLI (our test suite uses `babel-core/register`) and also gave no syntax errors. I'll continue to investigate.

**Comment by jamesseanwright** [comment]
Update #2: a handler I registered with `process`'s `unhandledRejection` event is invoked with a `TypeError`. I think that this is potentially due to `q` swallowing errors; I'll investigate further to confirm this. Is there any reason why native `Promise`s can't be used?

**Comment by christian-bromann** [comment]
@jamesseanwright I think they aren't supported by cucumber .. this will change with v4 anyway. Thanks for investigating tho

**Comment by jamesseanwright** [comment]
@christian-bromann I have locally replaced the [Cucumber reporter](https://github.com/webdriverio/webdriverio/blob/master/lib/frameworks/cucumber.js)'s usage of `q` with native `Promise`s and removed my `unhandledRejection` handler; consequently, I successfully see an error message with a full stack trace. This isn't an issue with CucumberJS itself.

Although there's a new major version due, is there no possibility to move to native `Promise`s in the latest release? I'm more than happy to do the work, especially as it will provide a more viable development experience going forward.

**Comment by christian-bromann** [comment]
@jamesseanwright we moved the cucumber integration into an own package: https://github.com/webdriverio/wdio-cucumber-framework. Since we will release v4.0 soon I you don't need to waste your time in fixing the issue.

**Comment by jamesseanwright** [comment]
@christian-bromann Nice, I like that approach. Do you have an ETA on version 4? For now, I might just fork it with a crude Promise replacement for the Cucumber reporter, as it's really hard to debug errors without that information.

**Comment by christian-bromann** [comment]
Sounds good to me. I don't have an ETA because I don't know how much time I can spend working on the project every day but the last tasks are only around documentation improvements.

**Comment by jamesseanwright** [comment]
That's understandable. Thanks for the info!

**Comment by dcypherthis** [comment]
@jamesseanwright did you pursue a crude promise replacement?  This would help me out tremendously in the meantime while I'm waiting for V4 docs to be updated.  I cant make an upgrade until they are ready, but i'm still facing the same issue you were here
