### ISSUE TITLE
How Do I Create an Infinite Loop?

### ISSUE THREAD

**Issue by FiatPax** [webdriverio/webdriverio#889]
I have created some loops but after some time it ends up terminating with timeout error and also I think it'd terminate anyways when chainit hits the max listeners for eventemitter?

How can I create a loop that won't end and will run till the process terminated externally?

**Comment by christian-bromann** [comment]
Selenium as well as webdriverio has certain timeouts which prevent tests from getting staled. Why would you like to create an infinite loop?
