### ISSUE TITLE
How to implement a takesScreenshot Handler?

### ISSUE THREAD

**Issue by fbuchinger** [webdriverio/webdriverio#89]
Hi,

I noticed that the phantomjs driver is taking screenshots by default when a test fails (`takesScreenshot: true` in `desiredCapabilites`). Unfortunately, these png screenshots are simply dumped base64-encoded to my console. how can i implement a handler in webdriverjs that saves them to disk? (probably something like http://stackoverflow.com/questions/15902142/webdriverjs-selenium2-from-nodejs-correct-syntax-for-taking-screenshot, but for automatic screenshots).

kind regards,

Franz

**Comment by lamanhhien** [comment]
how to screenshot full browser ?
