### ISSUE TITLE
'suite:end' is fired one more time than 'suite:start'

### ISSUE THREAD

**Issue by just-boris** [webdriverio/webdriverio#890]
Tried with example from `examples/wdio/wdio.customreporter.conf.js`

Got these events with `suite` prefix:

```
suite:start
suite:start
suite:end
suite:end
suite:end
```

As you can see, there is an extra `suite:end` event. it breaks any custom reporter which relies on `suite` events

**Comment by georgecrawford** [comment]
I encountered this too, and addressed it in https://github.com/webdriverio/wdio-mocha-framework/pull/9/files#diff-a7bcb5fcc46018435e1ce3fa65fcb992R151. @just-boris: was this using Mocha?

**Comment by christian-bromann** [comment]
Closing. I think this is fixed by @georgecrawford commit. If not feel free to reopen.
