### ISSUE TITLE
[🐛 Bug]:  Mobile screenshots have incorrect aspect ratio on big pages

### ISSUE THREAD

**Issue by nmattia** [webdriverio/webdriverio#8903]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.16

### Node.js Version

v16.15.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  browserName: "chrome",
  "goog:chromeOptions": {
    args: [
      "headless",
      "disable-gpu",
    ],
    mobileEmulation: {
      deviceMetrics: { height: 667, width: 375, pixelRatio: 3 },
    },
  },
}
```

### What happened?

When setting `mobileEmulation` to either a device name or through `deviceMetrics`, screenshot dimensions depend on the size of the page (as opposed to being exactly `deviceMetrics.width` X `deviceMetrics.height`.

I.e., when calling `saveScreenshot("screenshot.png")`, the image `screenshot.png` may have an aspect ratio larger than `deviceMetrics.height/deviceMetrics.width` if the page is very long. In order to work around this I need to set `--window-size=...` in the chrome args.

### What is your expected behavior?

The screenshot should have the size of the device screen.

### How to reproduce the bug.

Resulting image "screenshot.png" has dimensions 750 × 13654

``` ts
import { remote } from "webdriverio";

/** Create a chrome instance and run callback, deleting session afterwards */
async function withChrome<T>(
  cb: (browser: WebdriverIO.Browser) => T
): Promise<T> {
  const browser = await remote({
    capabilities: {
      browserName: "chrome",
      "goog:chromeOptions": {
        args: [
          "headless",
          "disable-gpu",
        ],
        mobileEmulation: {
          deviceMetrics: { height: 667, width: 375, pixelRatio: 3 },
        },
      },
    },
  });

  const res = await cb(browser);
  await browser.deleteSession();
  return res;
}

/** Visit page and wait until loaded */
async function visit(browser: WebdriverIO.Browser, url: string) {
  await browser.url(url);
  await browser.waitUntil(
    () => browser.execute(() => document.readyState === "complete"),
    {
      timeout: 10 * 1000,
      timeoutMsg: "Browser did not load after 10 seconds",
    }
  );
}

withChrome(async (browser: WebdriverIO.Browser) => {
    await visit(browser, "https://webdriver.io");
    await browser.saveScreenshot("screenshot.png");
})
```

### Relevant log output

```typescript
2022-09-23T09:03:22.255Z INFO devtools:puppeteer: Initiate new session using the DevTools protocol
2022-09-23T09:03:22.257Z INFO devtools: Launch Google Chrome with flags: --enable-automation --disable-popup-blocking --disable-extensions --disable-background-networking --disable-b
ackground-timer-throttling --disable-backgrounding-occluded-windows --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-first-run --no-default-browser-ch
eck --disable-hang-monitor --disable-prompt-on-repost --disable-client-side-phishing-detection --password-store=basic --use-mock-keychain --disable-component-extensions-with-backgrou
nd-pages --disable-breakpad --disable-dev-shm-usage --disable-ipc-flooding-protection --disable-renderer-backgrounding --force-fieldtrials=*BackgroundTracing/default/ --enable-featur
es=NetworkService,NetworkServiceInProcess --disable-features=site-per-process,TranslateUI,BlinkGenPropertyTrees --window-position=0,0 --window-size=375,667 --headless --disable-gpu -
-device-scale-factor=3
2022-09-23T09:03:22.788Z INFO devtools: Connect Puppeteer with browser on port 58298
2022-09-23T09:03:22.868Z INFO devtools: COMMAND navigateTo("https://webdriver.io/")
2022-09-23T09:03:25.352Z INFO devtools: RESULT null
2022-09-23T09:03:25.357Z INFO devtools: COMMAND executeScript("return (() => document.readyState === "complete").apply(null, arguments)", <object>)
2022-09-23T09:03:25.361Z INFO devtools: RESULT true
2022-09-23T09:03:25.362Z INFO devtools: COMMAND takeScreenshot()
2022-09-23T09:03:26.280Z INFO devtools: RESULT iVBORw0KGgoAAAANSUhEUgAAAu4AADVWCAYAAABqQJkOAAABJ2lDQ1BTa2lhA...
2022-09-23T09:03:26.286Z INFO devtools: COMMAND deleteSession()
2022-09-23T09:03:26.288Z INFO devtools: RESULT null
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for raising the issue @nmattia 

This happens due to the fact that the `devtools` package takes a full page screenshot while WebDriver binaries actually only take a screenshot of the viewport. The code in question is this: [`takeScreenshot.ts#L14`](https://github.com/webdriverio/webdriverio/blob/main/packages/devtools/src/commands/takeScreenshot.ts#L14). As we are striving to have the same experience between `devtools` and `webdriver` automation I'ld suggest to switch the `fullPage` flag to `false`.

We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by nmattia** [comment]
hi @christian-bromann,

Just to clarify, are you suggesting that I send a PR that switches `fullPage` to false? Happy to do it, just double checking.

**Comment by christian-bromann** [comment]
> Just to clarify, are you suggesting that I send a PR that switches `fullPage` to false?

Yes, for the `main` and `v7` branch.

**Comment by nmattia** [comment]
@christian-bromann any idea when this might get released?

**Comment by christian-bromann** [comment]
Soon 😉
