### ISSUE TITLE
Polyfill for nth-match CSS 4 selector

### ISSUE THREAD

**Issue by Risto-Stevcev** [webdriverio/webdriverio#891]
It would be nice to have the [nth-match](http://www.w3.org/TR/selectors4/#nth-match-pseudo) pseudo-selector polyfill when using WebdriverIO.

In jQuery, this can easily be achieved programatically with something like: `$('elem.someclass').eq(2)`, but it would require using messy xPath in the current version of WebdriverIO, because the nth element of `.someclass` can't be selected using any other CSS selector except for currently unavailable CSS 4 `nth-match`.

There's the `elements` protocol, but there's no way to send the nth element from that to another command. 

It would be nice to either have that polyfill like this:

``` javascript
browser.selectByValue('select.comparators:nth-match(2)', 'Some value')
```

Which could be polyfilled by using the `this.elements` protocol and selecting the `WebElement JSON` index from what is asked for in nth-match. If there's no `nth-match` in the selector, it can just default to it's current behavior and use `this.element`.

Or something generic and similar to jQuery, which would detect if the selector argument is left out and would attempt to read the result from the previous promise, such as this:

``` javascript
browser.elements('select.comparators').eq(2).selectByValue('Some value')
```

**Comment by christian-bromann** [comment]
Let's also enable `:visible` and `:hidden`

**Comment by jkwaldrip** [comment]
I'm running into a problem with this right now.  Is this issue scoped for any future release?

**Comment by christian-bromann** [comment]
@jkwaldrip this wasn't really high on my prio list. Happy to receive PRs for that. You can work around this now by doing:

```js
const comparators = $$('select.comparators');
comparators[2].selectByValue('Some value');
```

**Comment by jkwaldrip** [comment]
@christian-bromann Thanks, I've added an update on #1140 for the issue I was encountering with setValue() in case anyone else runs into it.

**Comment by BlueRaja** [comment]
This should probably be closed. `nth-match` doesn't even exist anymore.  It also [was never equivalent to jQuery's `:eq(2)` selector](https://stackoverflow.com/a/31415015/238419) _(which is confusing, which is why it was removed)_

**Comment by christian-bromann** [comment]
agree with @BlueRaja. My [workaround](https://github.com/webdriverio/webdriverio/issues/891#issuecomment-301149715) above is actually the valid solution. You can also use `.filter` to limit the selection by arbitrary functions, e.g.

```js
        const results = $$('.commands.property a').filter(function (link) {
            return link.isVisible();
        });
```
