### ISSUE TITLE
Job status isn't being updated on Saucelabs

### ISSUE THREAD

**Issue by philipwalton** [webdriverio/webdriverio#892]
I'm not sure if this is broken or if I'm missing something, but I suppose either way it's worth me reporting this confusion:

When I run the `webdriverio.saucelabs.js` file, the job succeeds but never marks it as a pass. From what I can tell by reading the [docs and the code](https://github.com/webdriverio/webdriverio/blob/266e97302c23efe25351140588e274e4099970e3/examples/wdio.conf.js#L27-L30), this is supposed to just work.

Here's what I'm running:

```sh
export SAUCE_USERNAME=xxxxxxxx
export SAUCE_ACCESS_KEY=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

node examples/cloudservices/webdriverio.saucelabs.js
```

It's not clear to me whether `updateJob:true` only works when used the configuration file, but I've tried that and it doesn't work either. I've also tried running the `webdriverio.saucelabs.js` file and passing  `updateJob:true` in the `.remote()` function, but that also doesn't seem to work (added in the last line).

```js
var webdriverio = require('../../index'),
    client = webdriverio.remote({
        desiredCapabilities: {
            browserName: 'chrome',
            version: '27',
            platform: 'XP',
            tags: ['examples'],
            name: 'This is an example test'
        },
        host: 'ondemand.saucelabs.com',
        port: 80,
        user: process.env.SAUCE_USERNAME,
        key: process.env.SAUCE_ACCESS_KEY,
        logLevel: 'silent',
        updateJob: true
    }).init();
```

Am I missing something?

**Comment by christian-bromann** [comment]
That feature only works if you run your tests using the wdio test runner. Using it like this (as remote client) you have to do the request by yourself.

**Comment by philipwalton** [comment]
Thanks for the clarification. As I mention in the original issue, I think this should be documented better, as it wasn't clear to me at all what the `remote()` function did.

**Comment by christian-bromann** [comment]
Agree! We will clarify the usage of the remote function with v4 as it doesn't play the central role anymore.
