### ISSUE TITLE
[💡 Feature]: Use `npm set-script` in config wizard to add script to package.json

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#8921]
### Is your feature request related to a problem?

tbd

### Describe the solution you'd like.

tbd

### Describe alternatives you've considered.

n/a

### Additional context

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MMoudy49** [comment]
The inclusion of `npm set-script` requires an npm version of 7.x or greater. It might be a good idea to include that in the documentation or only run that command when npm version is 7.x or greater.

**Comment by christian-bromann** [comment]
Thanks for the notice. This will be released for the upcoming `v8` release which requires NodeJS v16 and older. These versions have NPM v7 and higher.
