### ISSUE TITLE
[💡 Feature]: Sequential Test Suites: Re-Run Specific Spec File on Failure 

### ISSUE THREAD

**Issue by samuelfreiberg** [webdriverio/webdriverio#8933]
### Is your feature request related to a problem?

Using WebDriverIO v7 + Appium v2.

I have _x_ amount of spec files that test _x_ amount of component in the same test app. Although these components are all independent of each other, they are in the same test app. Thus, I grouped all these spec files together to run sequentially so the app wouldn't have to be torn down + rebooted after each spec file. This wasted precious time in our automation pipeline.

I would expect, if a specific spec file were to produce a failure, that specific spec file would be re-run. However, that's not the case. If one spec file fails, the **whole suite** is re-run. I don't think that makes sense in this case.

Even though I'm grouping these spec files together, that doesn't mean one failure is related to another failure. In my case, it just means I don't need to reset the state of the app after each spec file is run.

### Describe the solution you'd like.

Even when specs are grouped sequentially, we should have the option on a failure to either:

1. Re-run the whole test suite
2. Re-run the specific spec file that failed

Currently, only #1 is an option

### Additional context

**Additional context and thoughts:**

I am grouping these specs together sequentially because we don't the need the app to reset after each spec file. I've looked through Appium docs and can't find any other way to not reset the app after each spec file. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Thanks for raising an issue.

Please check our docs on retrying tests. Especially in Mocha it should be possible to retry individual groups within spec files, see https://webdriver.io/docs/retry/#rerun-suites-in-mocha. Another options is to retry [individual `it` blocks](https://webdriver.io/docs/retry/#rerun-single-tests-in-jasmine-or-mocha).

If the docs are not clear in this regards we should look into improving them. I will go ahead and close but happy to reopen if there is something we can work on.
