### ISSUE TITLE
[🐛 Bug]: Allure reporter using Cucumber Step Reporter won't list execution's final step

### ISSUE THREAD

**Issue by Lautenschlager-id** [webdriverio/webdriverio#8937]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v7.20.5 | "@wdio/allure-reporter": "^7.19.7" | "@wdio/cucumber-framework": "^7.20.7"

### Node.js Version

16.17.0

### Mode

WDIO Testrunner

### What happened?

Using / Relates to: Cucumber (`@wdio/cucumber-framework`) with Allure Reporter (`@wdio/allure-reporter`);

If Allure's option `useCucumberStepReporter` is `true`, I expect Cucumber's steps to be recorded appropriately and displayed in the report.

However, it seems that the execution's final step doesn't get listed in the report. Read the step-by-step to understand better.

@update: __It seems to only be affecting nameless scenarios!__

### How to reproduce the bug.

To reproduce the bug:

1. Set Allure as a reporter with `useCucumberStepReporter = true` in `wdio.conf.js`
```js
	reporters: [
		[ "allure", {
			useCucumberStepReporter: true
		} ],
	],

```

2. Create a feature, for example `test.feature`, with nameless scenarios
```
Feature: Debugging
	Background:
		Given A
		When B

	Scenario:
		Given C
		When D
		Then E
```

3. Create the steps for A, B, C, D, and E.
```js
Given(/^[A-E]$/, () => {});
```

4. Execute the created feature and observe the generated report.

Expected:
```
Given A
When B
Given C
When D
Then E
```

Actual result:
![image](https://user-images.githubusercontent.com/26045253/192907282-fcb95c25-f0ce-4ca8-adb6-1a345f3c68e9.png)

Note that `Then E` is missing.

### Relevant log output

```
 "spec" Reporter:
------------------------------------------------------------------
[5f38de6 android 12 #0-0] Running: 5f38de6 on android 12
[5f38de6 android 12 #0-0] Session ID: ID
[5f38de6 android 12 #0-0]
[5f38de6 android 12 #0-0] » \features\test.feature
[5f38de6 android 12 #0-0] Debugging
[5f38de6 android 12 #0-0]
[5f38de6 android 12 #0-0]    ✓ Given A
[5f38de6 android 12 #0-0]    ✓ When B
[5f38de6 android 12 #0-0]    ✓ Given C
[5f38de6 android 12 #0-0]    ✓ When D
[5f38de6 android 12 #0-0]    ✓ Then E
[5f38de6 android 12 #0-0]
[5f38de6 android 12 #0-0] 5 passing (2.6s)


Spec Files:      1 passed, 1 total (100% completed) in 00:00:18

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for filing the issue.

This seems indeed like bug. We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by Lautenschlager-id** [comment]
Important update: it seems to be affecting only nameless scenarios.
<hr>
![image](https://user-images.githubusercontent.com/26045253/193049300-d4cc4268-9252-4b53-9a4f-ed9a8f58b85e.png)
<hr>
![image](https://user-images.githubusercontent.com/26045253/193049489-801a5fd4-f375-4ac9-b246-a3ed432cd1ce.png)

**Comment by BorisOsipov** [comment]
Hi! We have rewritten the reporter to the new allure-js version. Please try version 8.5.0 of wdio-allure-reporter and provide more details if the issue still persists. Feel free to create a new issue with actual details if it reproduces.
