### ISSUE TITLE
[🐛 Bug]: Allure Reporter reporting wrong success rate if Cucumber Step Reporter is on

### ISSUE THREAD

**Issue by Lautenschlager-id** [webdriverio/webdriverio#8939]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v7.20.5 | "@wdio/allure-reporter": "^7.19.7" | "@wdio/cucumber-framework": "^7.20.7"

### Node.js Version

16.17.0

### Mode

WDIO Testrunner

### What happened?

Success metrics fail on `useCucumberStepReporter = true` if a feature implements a Scenario Outline with a broken example. Note that for the bug to happen, this example must not be the last one to be executed, or else it is displayed first in the report and thus it counts as an actual failure. Read the step by step to understand better.

Attachments:

100% passed (?)
![image](https://user-images.githubusercontent.com/26045253/193093028-4ba3177a-e6da-42b4-b384-00e03978d959.png)

Listed execution - PASSED
![image](https://user-images.githubusercontent.com/26045253/193093160-f24bf5ba-5e0b-429f-b686-45cc16b23d73.png)

One of the values in the Examples table has failed, since it's in the same scenario it goes in `retries` 
![image](https://user-images.githubusercontent.com/26045253/193093271-885a9888-78d5-4029-8e29-65c5b6bde028.png)

### What is your expected behavior?

I expect all scenarios to count on the success rate. 100% is only 100% when all executions have passed, without exception.

Given it has executed three scenarios and one has failed, then the success rate is only 66%, and not 100%.

### How to reproduce the bug.

To reproduce the bug:

1. Set Allure as a reporter with `useCucumberStepReporter = true` in `wdio.conf.js`
```js
	reporters: [
		[ "allure", {
			useCucumberStepReporter: true
		} ],
	],

```

2. Create a feature, for example `test.feature`
```
Feature: Foobar
	Scenario Outline: Any
		Given ok
		When <bar>

		Examples:
			| bar    |
			| ok     |
			| not ok |
			| ok     |
```

3. Create a step that will break when "not ok"
```js
// if the value is "not ok", then the step fails
Given(/^(not )?ok$/, (not) => { if (not) throw new Error(not); });
```

4. Execute the created feature and observe the generated report.

Expected: 66% success rate and a mention that one out of three test executions have failed

Actual result: 100% success rate
![image](https://user-images.githubusercontent.com/26045253/193093976-7beb6f56-49f0-4838-bf4a-271a0d662ad6.png)
![image](https://user-images.githubusercontent.com/26045253/193093933-8a975bab-575e-4605-a6e6-0bed841c8fd5.png)

### Relevant log output

```typescript
[5f38de6 android 12 #0-0] Running: 5f38de6 on android 12
[5f38de6 android 12 #0-0] Session ID: f059ce7c-df5c-4593-ae46-043e18e36c02
[5f38de6 android 12 #0-0]
[5f38de6 android 12 #0-0] » \features\test.feature
[5f38de6 android 12 #0-0] Foobar
[5f38de6 android 12 #0-0] Any
[5f38de6 android 12 #0-0]    ✓ Given ok
[5f38de6 android 12 #0-0]    ✓ When ok
[5f38de6 android 12 #0-0]
[5f38de6 android 12 #0-0] Any
[5f38de6 android 12 #0-0]    ✓ Given ok
[5f38de6 android 12 #0-0]    ✖ When not ok
[5f38de6 android 12 #0-0]
[5f38de6 android 12 #0-0] Any
[5f38de6 android 12 #0-0]    ✓ Given ok
[5f38de6 android 12 #0-0]    ✓ When ok
[5f38de6 android 12 #0-0]
[5f38de6 android 12 #0-0] 5 passing (3.3s)
[5f38de6 android 12 #0-0] 1 failing
[5f38de6 android 12 #0-0]
[5f38de6 android 12 #0-0] 1) Any When not ok
[5f38de6 android 12 #0-0] Error: not
[5f38de6 android 12 #0-0] Error: not
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by BorisOsipov** [comment]
It is not a bug it is how allure handles test retries. If you have two tests with the same name and parameters it will handle it as retries of one test.

To "fix" it you must have unique tests names. For Scenario Outline the esiest way is append example value to scenario name like this:

```
Feature: Foobar
  Scenario Outline: Any <bar>
    Given ok
    When <bar>

    Examples:
      | bar    |
      | ok     |
      | not ok |
```

**Comment by Lautenschlager-id** [comment]
That doesn't really make sense @BorisOsipov. The issue is that even with a broken scenario it still reports to 100%. Isn't that inconsistent?

**Comment by BorisOsipov** [comment]
@Lautenschlager-id 

- It is correct because the last execution of this series of test retries is passed. So, there are no failed\broken *actual* test results(only outdated broken test). That's why you see 100%. 
- Allure has two parts 
1 - generate test results data from tests excution.
2 - generate report from data collected in part 1.

wdio-allure-reporter is responsibol
