### ISSUE TITLE
How can I choice the one from the same elements?

### ISSUE THREAD

**Issue by wzl610** [webdriverio/webdriverio#894]
If I have two inputs which are the same class name,then I want to set the value "test" to the second input ,how can I  do that ? Thanks~

**Comment by christian-bromann** [comment]
Depends on the html structure. You can do nested element querying, e.g.
```html
section
    div.header
        span.myElem
    div.main
        span.myElem
```
if you want to query the first myElem element you can do:
```js
browser.element('.header').getAttribute('.myElem', 'class')
```

**Comment by wzl610** [comment]
But when my html structure like this
section
     input.myinput
     input.myinput

How can I choice the first input?

**Comment by christian-bromann** [comment]
Either use last or first child (if possible). If that doesn't work the only chance it to use xPath. Just open your dev tools, look for the element you want to, do right click and click on "Copy xPath". It will put the exact xPath to that element in your clipboard.
