### ISSUE TITLE
Need help to handle error - WebdriverIO

### ISSUE THREAD

**Issue by PantHarry-21** [webdriverio/webdriverio#8943]
Hi,
I have a scenario - I have a list of links, user have the access to delete all links, I am writing script for the scenario that if there is no link, return "There is no link available" and if there is any link the proceed with delete process.
I have written a script but it is only fulfilling a single scenario. 
If it is working with "There is no link available", then else condition is not working.

Code ->   

 **try{
                    noDataText = await b.$('Selector').isExisting();
                    let noDataText = false;
    
                }catch(error){
                    noDataText = true;
    
                }
    
                console.log(noDataText);
                
                if(noDataText==false) {
                    let actionBtn = await b.$('Selector');
                    await actionBtn.click();
                    await b.pause('2000')
    
                    let deleteOption = await b.$("Selector");
                    await deleteOption.click();
                    await b.pause('2000')
    
                    let confirmDelete = await b.$("Selector");
                    await confirmDelete.click();
    
                    let linkDeleted = await b.$("Selector");
                    successMsg = await linkDeleted.getText();
                    assert.equal(successMsg, "Link Deleted Successfully");
                    
                    }else if (noDataText==true) {
                        console.log("No custom link available in the page to delete")
                    }**

Please Help.....

**Comment by christian-bromann** [comment]
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

Please understand that it is difficult for anyone to support you here given we don't have the application you are working with. We can only make assumptions. Please make your questions concrete to a specific issue that is related to WebdriverIO. The support channel is a good place to ask these questions.
