### ISSUE TITLE
calling switchTab without an window handle is not working

### ISSUE THREAD

**Issue by wvankuipers** [webdriverio/webdriverio#897]
Calling `browser.switchTab()` without a window handle fails to select the first available tab (or window).

Doing this:

    browser.url('http://github.com').newWindow('http://google.com').switchTab().url()

Results in returning `http://google.com` instead of the expected `http://github.com`.

This also results in the `.close()` function not selecting the first available tab as expected, since it relies on the `switchTab` functionality.

**Comment by christian-bromann** [comment]
Let's move convo to #898
