### ISSUE TITLE
[🐛 Bug]: TypeError: Cannot read properties of undefined (reading 'duration')

### ISSUE THREAD

**Issue by Joosakur** [webdriverio/webdriverio#8973]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.25.1

### Node.js Version

16.17.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
services: ['selenium-standalone'],
  capabilities: [
    {
      browserName: 'chrome',
      'goog:chromeOptions': {
        args: ['headless', 'disable-gpu', 'no-sandbox'],
      },
    },
  ],
```

### What happened?

When updating wdio and specifically @wdio/mocha-framework from version 7.16.13, one test started failing with `TypeError: Cannot read properties of undefined (reading 'duration')`. I investigated it and the first version with the issue was 7.16.15. Based on the stacktrace I narrowed the breaking change to be this PR: https://github.com/webdriverio/webdriverio/pull/7989 

I noticed that the failing test was missing a `describe` function from around it, so probably the test itself wasn't valid either and this issue is very minor, but the error message was somewhat confusing and it might be worth adding some extra null-check there.

### What is your expected behavior?

The test should pass or give a more clear error message

### How to reproduce the bug.

```
it(`should have title`, async function () {
  await browser.url(url)
  await expect(await $('h1')).toHaveText(title)
})
```

### Relevant log output

```typescript
[0-1] TypeError in ""after all" hook for "..."
TypeError: Cannot read properties of undefined (reading 'duration')
    at MochaAdapter.prepareMessage (.../node_modules/@wdio/mocha-framework/build/index.js:159:58)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!



Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by Joosakur** [comment]
> Thanks for reporting!
> 
> Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

Hmm, I did that but the PR shows huge diff with ton of conflicts. Should I rebase my fork on top of v7 branch first or something like that?

**Comment by christian-bromann** [comment]
I think you tried to merge `main` into `v7`. I recommend to checkout `v7` branch first and manually apply the same fixes there. These branches have diverged quit a lot which is why we are currently maintaining both and there for need a PR to both branches: `main` and `v7`.
