### ISSUE TITLE
[🐛 Bug]: Launching Google Chrome and Firefox Browser with Geolocation preference

### ISSUE THREAD

**Issue by markcielos24-gmail** [webdriverio/webdriverio#8975]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

@wdio/cli = 7.25.0

### Node.js Version

16.16.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [
    {
      maxInstances: 1,
      browserName: 'chrome',
      'goog:chromeOptions': {
          args: [
            'incognito',
            'disable-gpu',
            'no-sandbox',
            'window-size=1920,1080',
            'start-maximized',
          ],
          prefs: {
            'credentials_enable_service': false,
            'profile': {
              'password_manager_enabled': false,
              'default_content_setting_values': {
                'geolocation': 1
              }
            }
          },
          w3c: true,
        },
      acceptInsecureCerts: true
    },
   {
      maxInstances: 3,
      browserName: 'firefox',
      'moz:firefoxOptions': {
          args: [
            // '-headless'
          ]
        }
        ,
      acceptInsecureCerts: true
    }
],
services: ['chromedriver','geckodriver',['firefox-profile',{
      'media.navigator.streams.fake': true,
      'media.navigator.permission.disabled': true,
      'geo.enabled': true
      }]],
```

### What happened?

Hi,
I am using webdriverio as automation tool and I want to launch google chrome & firefox where geolocation is already allowed so that it would not ask/show the notification box for asking to allow/block the location. This could be a duplicate of below link but I tried the solution given there and it works fine when I set the geolocation=2 (meaning to block) but its not working when I set geolocation=1 (meaning to allow) as the chrome browser is still asking to allow/block the location, weird that the other option(2-block) worked but (1-allow) did not. 
For Firefox I used 'geo.enabled': true, when behavior with chrome, when set to false it works as expected it is not asking for location permission anymore its already selected to block but its not working when we set it to true(firefox still asking for location permission)

https://github.com/webdriverio/webdriverio/issues/1329
https://stackoverflow.com/questions/37401087/webdriverio-chimpjs-launch-google-chrome-with-gelocation-permitted

capabilities: [
    {
      maxInstances: 1,
      browserName: 'chrome',
      'goog:chromeOptions': {
          args: [
            'incognito',
            'disable-gpu',
            'no-sandbox',
            'window-size=1920,1080',
            'start-maximized',
          ],
          prefs: {
            'credentials_enable_service': false,
            'profile': {
              'password_manager_enabled': false,
              'default_content_setting_values': {
                'geolocation': 1
              }
            }
          },
          w3c: true,
        },
      acceptInsecureCerts: true
    },
   {
      maxInstances: 3,
      browserName: 'firefox',
      'moz:firefoxOptions': {
          args: [
            // '-headless'
          ]
        }
        ,
      acceptInsecureCerts: true
    }
],
services: ['chromedriver','geckodriver',['firefox-profile',{
      'media.navigator.streams.fake': true,
      'media.navigator.permission.disabled': true,
      'geo.enabled': true
      }]],

### What is your expected behavior?

My expected behavior of it would be that chrome will not ask for the location permission anymore when geolocation is set to "1" as we already set it to allowed("1"). 
As escribed in the bug description, its working fine when geolocation was set to = "2", it already know that it was set to block the location as that is the meaning of "2". But when we set it to ="1" which means to already allow location, it is still asking again for the location permission just like nothing was set but we actually already set it to allow("1").
Same for Firefox I used 'geo.enabled': true, when behavior with chrome, when set to false it works as expected it is not asking for location permission anymore its already selected to block but its not working when we set it to true(firefox still asking for location permission)

### How to reproduce the bug.

open the url "https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_geolocation" using below wdio.conf,js pref for chrome. 
Click the [Try it] button, notice that when geolocation is set to "2" that chrome will not ask for the location anymore as it was set to block(geolocation="2"). Rerun where geolocation is set to "1", click the [Try it] button and notice that chrome will ask for location information(expected should be that chrome should not ask for location permission anymore as we set the geolocation="1" which means to allow location access).
For firefox, do the same set of instructions just set 'geo.enabled' to either true/false.

### Relevant log output

```typescript
no relevant log output needed
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for raising an issue.

This is unlikely a bug in WebdriverIO given that it only forwards the data to the browser. However it is still worth investigating in order to provide better documentation around this.

Thanks for reporting!

Any contributions that brings in more clarity on this topic are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by markcielos24-gmail** [comment]
Thanks @christian-bromann for looking into this, please reply when an update becomes available.

**Comment by christian-bromann** [comment]
Would you like to help us look into this?

**Comment by markcielos24-gmail** [comment]
As much as I want to help, unfortunately my coding skills are not of the developer level, am confident in terms of test automation coding, not so sure if I will be of any help. I'd like to try but I might end up taking much of your time assisting me :D

**Comment by christian-bromann** [comment]
Permission APIs have landed in the WebDriver protocol and can be used like this:

```ts
await browser.setPermissions({ name: 'geolocation' }, 'granted')
console.log(await browser.executeAsync((done) => {
    return navigator.geolocation.getCurrentPosition(
        (position) => done(null, position),
        done
    )
}))
```

Unfortunately the support is still [very limited](https://wpt.fyi/results/webdriver/tests/classic/permissions?label=experimental&label=master&aligned) but will hopefully improve over time. Closing as there is nothing we can do in WebdriverIO to make it work.

**Comment by christian-bromann** [comment]
Actually it is possible using WebDriver Bidi and emulating the commands:

```ts
import { remote } from 'webdriverio'

const browser = await remote({
    capabilities: {
        browserName: 'chrome',
        webSocketUrl: true
    }
})

await browser.scriptAddPreloadScriptCommand({
    functionDeclaration: /*js*/`async () => {
        navigator.geolocation.getCurrentPosition = (cbSuccess, cbError) => cbSuccess({
            coords: {
                accuracy: 20,
                altitude: null,
                altitudeAccuracy: null,
                heading: null,
                latitude: 52.52,
                longitude: 13.39,
                speed: null
            },
            timestamp: Date.now()
        })
    }`
})

await browser.url('https://www.google.com/maps')
await browser.$('.app-viewcard-strip button').waitForExist()
await browser.$$('.app-viewcard-strip button').map((b) => b.getHTML())
await browser.$('aria/Your Location').click()
await browser.pause(4000)

await browser.deleteSession()
```
