### ISSUE TITLE
Expose --grep command line functionality in wdio

### ISSUE THREAD

**Issue by nmalaguti** [webdriverio/webdriverio#899]
mocha exposes a `--grep` command line that allows you to filter your tests to specific test suites. It would be great if `wdio` exposed a similar command line option.

**Comment by ResolverJay** [comment]
Try this, it works for me.
```
wdio --mochaOpts.grep filter wdio.mocha.conf.js
```

**Comment by christian-bromann** [comment]
ohh right .. this gets propagated. Thanks @ResolverJay

**Comment by fireproofsocks** [comment]
I wouldn't call this issue closed until there's an example included in the docs.  Specifically, it'd be quite appropriate to include how to organize tests into suites and/or how to run single tests on the getting started page @ http://webdriver.io/guide/testrunner/gettingstarted.html

**Comment by christian-bromann** [comment]
well this particular issue is about the grep argument in WebdriverIOs cli interface. If you need documentation around a certain topic please create a new issue with your questions around that and we can work on that :wink:

**Comment by fireproofsocks** [comment]
It's not an issue per se, it's an omission with the docs.  Here's a pull request for your consideration: https://github.com/webdriverio/webdriverio/pull/943 

Docs and examples are critical: https://medium.com/@craftsmancoding/wtfm-dbbec02eb172#.al5qi0cjl

**Comment by jedwards1211** [comment]
@christian-bromann there is a problem though: webdriver.io still creates sessions for each test suite, even if `--mochaOpts.grep` prevents that suite from running.  So if you have 100 test suites, it would end up creating 100 sessions even if you grep for tests in only one suite.
