### ISSUE TITLE
[🐛 Bug]: element.click() with passed args throws exception

### ISSUE THREAD

**Issue by davidjonesdialexa** [webdriverio/webdriverio#9008]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.21.0

### Node.js Version

18.9

### Mode

WDIO Testrunner

### What happened?

element.click() with passed args throws exception

### What is your expected behavior?

element is clicked with x offset

### How to reproduce the bug.

```js
const elem = await $('selector')
await elem.click({x: 30})
```

### Relevant log output

`invalid argument: Exception while reading JSON`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by davidjonesdialexa** [comment]
I've tried simplifying this down to the simplest reproduction, and I still get the Exception. As long as I pass in an arg, I get the Exception

**Comment by christian-bromann** [comment]
Thanks for filing the issue.

Can you provide a reproducible example please?

**Comment by davidjonesdialexa** [comment]
I've tried this on multiple different elements within my app, I get the same error as long as I pass in any arg. That's why I boiled down the reproducible bug to be so simple

**Comment by davidjonesdialexa** [comment]
There's nothing special about when, where, or how I call the click function. It's on a React Native component and I need to offset the click by a few pixels. The `click()` call works fine as long as I don't pass in an arg

**Comment by davidjonesdialexa** [comment]
I'll see what I can come up with, I'm working on a private project so obviously can't share code

**Comment by davidjonesdialexa** [comment]
I got this to work by using touchAction instead of click
