### ISSUE TITLE
Using xpath to find parent and then click on another child element not working.

### ISSUE THREAD

**Issue by BlindChickens** [webdriverio/webdriverio#902]
Imagine a structure like this:

    <div>
        <h4>THIS PERSON<h4>
        <a>ADD<a>
    <div>
        <h4>THAT PERSON<h4>
        <a>ADD<a>

Now I would like to click on the ADD link in the div with the header that says "THIS PERSON".
So I thought I would do it like this:
>yield browser.element('//h4[contains(.,"THIS PERSON")]/..').click('a=ADD');

Now this is not the exact problem so I don't want to use n-th:child() type of stuff to find the first div. I want to get the parent thing to work. So please help and tell me why that does not work.

**Comment by christian-bromann** [comment]
Your example looks about right, isn't it working?

**Comment by BlindChickens** [comment]
Thank you Christian for replying, but yeah I figured it out.

**Comment by christian-bromann** [comment]
Cool :+1:

**Comment by rahulmr** [comment]
Hello @BlindChickens and @christian-bromann , will this work on appium native app?
@BlindChickens could you please post the code which you are using?

In my case, I am trying to run tests on 4.2.2 so resourceId is not going to work. My development guys say adding content-desc itself to every screen might be a sort of mini-project.

So I was thinking of using xpath as a rescue.
```
LinearLayout 
     TextView: Username:
     EditText: Required
LinearLayout
     TextView: Password:
     EditText:                  // This is actually NAF true so Required is not shown in the UIAutomatorViewer
```

What I want to do is, find the `TextView` Username and then its parent and from parent get the child `EditText`, so want some good simple way to do the same.
Whether I should use xpath (how to use xpath with webdriverio ??) or combination xpath plus `UiSelector()`.
Actually, I was very happy to use `UiSelector()` `resourceId` but unfortunately came to know that our devices will be `4.2.2 API 17` upgrades seem difficult.
