### ISSUE TITLE
It can`t change the size of screenshot of firefox?

### ISSUE THREAD

**Issue by wzl610** [webdriverio/webdriverio#903]
var webdriverio = require('webdriverio');
var options = {
  desiredCapabilities: {
    browserName: 'firefox'
  }
};
webdriverio
    .remote(options)
    .init()
    .setViewportSize({
        width : 300,
        height : 568
    })
    .pause(1000)
    .url('http://www.baidu.com')
    .pause(1000)
    .saveScreenshot('./img/test2.png',function(){
        console.log("success");
    })
    .pause(1000);

But I found the size of screenshot is 810px * 600px,could you tell me how to set the size of screenshot of the firefox?

**Comment by christian-bromann** [comment]
This is actually not a bug. As @drets pointed out:

> FF makes screenshot of whole page when you send this command: https://code.google.com/p/selenium/wiki/JsonWireProtocol#/session/:sessionId/screenshot
CHROME makes screenshot of view port only
http://stackoverflow.com/a/31840790/2517622
