### ISSUE TITLE
[🐛 Bug]: Cannot use multiple tags for Cucumber tag expression

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#9035]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

16

### Mode

WDIO Testrunner

### What happened?

Running with multiple tags does not work.
Passing flags `--cucumberOpts.tagExpression="@login and @anothertag"` should filter tests to run both tags.
All tests are skipped and test run does not start.

Passing just  `--cucumberOpts.tagExpression="@login"` or `--cucumberOpts.tagExpression="@anothertag"` does the job.

[It should work.](https://cucumber.io/docs/cucumber/api/#tag-expressions)

### What is your expected behavior?

Test run should start, tests that include both tags should run.

### How to reproduce the bug.

Start a test run with multiple tags, i.e. `--cucumberOpts.tagExpression="@login and @anothertag"`

### Relevant log output

```typescript
N\A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!



Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by perillai** [comment]
I tried recreating this bug, but I am unable to. Having both tags with an operator 'and' runs the test fine. Can you please share your feature file and wdio.conf?

**Comment by christian-bromann** [comment]
Thanks for checking @perillai !

@nextlevelbeard can you provide a reproducible example?

**Comment by christian-bromann** [comment]
ping @nextlevelbeard

**Comment by christian-bromann** [comment]
I will go ahead and close this. Let me know if you can provide a simple reproducible example and I am happy to reopen.
