### ISSUE TITLE
Phantomjs command line options

### ISSUE THREAD

**Issue by michahell** [webdriverio/webdriverio#905]
I can not find any documentation regarding passing options to phantomJs using a wdio.conf.js file.
This is what i'm trying to do using webdriverio: https://github.com/robotframework/Selenium2Library/issues/215. This is how it should be done (apparently) when webdriverio is used as a node dependancy: https://gist.github.com/christian-bromann/ab0700dfe55438a80386

**Comment by christian-bromann** [comment]
It should be part of your capabilities where you define 'browserName: "phantomjs"'

**Comment by michahell** [comment]
Yes... but.. how?

**Comment by michahell** [comment]
aha, the link is just wrong! 
this should be the link, I presume? https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/

**Comment by christian-bromann** [comment]
> Like so it doesn't work at least:

mhm .. this should work actually. Sauce Labs doesn't really matter much here since you want to use an headless browser. I will have to investigate but these properties should get propagated. Could you check the Selenium logs if you see these when the session gets created?

**Comment by michahell** [comment]
Hmm, okay. When I set logLevel to 'verbose', I see that in a ```DATA``` log event, the desiredCapabilities has the phantomjs.cli.args object, but in the following ```RESULT``` log, I see none of the options reflected, only the ```acceptSslCerts":false``` option which is false by default.

- Could it have to do with the phantomJs version i'm using? Which is 1.9.8, due to a bug in a higher version we had to downgrade to this version. I can check if installing the latest phantomJs version may solve this.

- Also, we're using this npm package for firing up selenium: https://www.npmjs.com/package/grunt-selenium-webdriver.

*[edit]* hmm, it might not be a webdriverIO issue, i'm just reading grunt-selenium-webdriver's package description: 

"Starts a selenium local server on http://127.0.0.1:4444/wd/hub with all browsers in PATH available, including phantom. However, if you get errors with test run using default phantomjs try the task below."

**Comment by michahell** [comment]
Okay I seem to have been wrong about the CLI options passed to phantomJs, they are indeed passed, because when I comment them out, 2 simple tests fail and when they are not commented out the tests pass. I tested two simple things:

1) loading an existing non HTTPS + basic auth website. (http://www.nu.nl/)
2) loading our own HTTPS + basic auth webapp. (https://dev.local/)

Interestingly enough, the first tests (which doesn't have anything to do with SSL / HTTPS) fails too.. huh?
Anyway, this is indeed the way CLI options are passed to phantomJS:

```javascript
capabilities: [
    { 
      browserName: 'phantomjs',
      'phantomjs.cli.args': [
        '--ignore-ssl-errors=true',
        '--ssl-protocol=tlsv1',
        '--web-security=false',
        '--debug=false'
      ]
    }
  ]
```
