### ISSUE TITLE
[🐛 Bug]: Worker service hook never runs if another service throws error on constructor

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#9051]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

16

### Mode

WDIO Testrunner

### What happened?

A service hook (before) did not run when another service threw an error in the constructor.

### What is your expected behavior?

If a service throws an error, other services run just fine and all of their hooks, run, both worker and launcher.

### How to reproduce the bug.

Have a service A throw an error during initialization:
```ts
import { Services, Capabilities, Options } from '@wdio/types'

export default class WorkerServiceA implements Services.ServiceInstance {
	constructor(
		private _options: MyServiceOpts,
		private _capabilities: Capabilities.RemoteCapability,
		private _config: Omit<Options.Testrunner, 'capabilities'>
	) {
		this.options = _options;
		
		console.log("Hello from service A, let's throw an error in constructor!")
		throw new Error("Boom")
	}
}
```

Have a different worker service B initialize just fine, containing a `before` hook:

```ts
import { Services, Capabilities, Options } from '@wdio/types'

export default class WorkerServiceB implements Services.ServiceInstance {
	constructor(
		private _options: MyServiceOpts,
		private _capabilities: Capabilities.RemoteCapability,
		private _config: Omit<Options.Testrunner, 'capabilities'>
	) {
		this.options = _options;
		
		console.log("I, service B, initialize just fine.")
	}
	
	async before(capabilities: Capabilities.RemoteCapability, specs: string[], browser: WebdriverIO.Browser) {
		console.log("before hook never runs if Service A throws an error")
	}

}
```

### Relevant log output

```typescript
N\A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting the issue.

I'ld suggest to ensure we handle plugin loads very transparent and propagate initiation issues to the runner. All services are initiated [here](https://github.com/webdriverio/webdriverio/blob/e5f951e242c098f6173dd77802870e5e2dba62e0/packages/wdio-utils/src/initialiseServices.ts#L23-L73) and initiated [here](https://github.com/webdriverio/webdriverio/blob/e5f951e242c098f6173dd77802870e5e2dba62e0/packages/wdio-utils/src/initialiseServices.ts#L94-L143).

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by christian-bromann** [comment]
Fixed in https://github.com/webdriverio/webdriverio/pull/9365

Moving on the runner will explicitly fail if services can't be initialised.
