### ISSUE TITLE
[💡 Feature]: Ability to get element's commands

### ISSUE THREAD

**Issue by KuznetsovRoman** [webdriverio/webdriverio#9057]
### Is your feature request related to a problem?

At the moment, the only way to check if an element has any method without network requests is to use `browser._propertiesObject_`. However, it doesn't seem to be part of the public API.

The problem is also complicated by the fact that `browser.overwriteCommand('notExisting', () => 'res', true)` will make your code fall, and even

```ts
try {
    await browser.overwriteCommand('notExisting', () => 'res', true);
} catch (err) {
    // unreached
    console.log(err)
}
```

Won't work

### Describe the solution you'd like.

it would be convenient to have a getElementCommands - method that returns a [list of commands added to the element](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/element.ts). And possibly a similar one - getBrowserCommands.

This solution allows you not only to check if a command exists, it will also be useful for debugging and for writing custom wrappers

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
The `browser` object has a property called `commandList` which we started to document in the updated v8 project website. I was mentioned in a code example in the current website too: https://webdriver.io/docs/browserobject#get-desired-capabilities.

> it would be convenient to have a getElementCommands - method that returns a [list of commands added to the element](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/element.ts). And possibly a similar one - getBrowserCommands.

For what purpose to you need to know all available commands?

> The problem is also complicated by the fact that `browser.overwriteCommand('notExisting', () => 'res', true)` will make your code fall, and even

I agree. The `overwriteCommand` method should throw if the command was not defined in the first place or maybe just fall back to use `addCommand`.

**Comment by KuznetsovRoman** [comment]
> For what purpose to you need to know all available commands?

For writing custom wrappers, as i mentioned.

For example, you could make a logger like that:

```ts
const commands = await browser.getElementCommands();

commands.forEach(commandName => {
    browser.overwriteCommand(commandName, function(originFn, ...args){
        console.log(`${commandName} was called with args:`, ...args);
        return originFn(...args);
    }, true)
})

```

Or you can implement custom implicit timeout, (since version with [setTimeout](https://webdriver.io/docs/api/browser/setTimeout) is not recommended and it doesn't work with `react$`)

There are many things that can be done if you differentiate between the commands of the elements and the browser

**Comment by christian-bromann** [comment]
> For example, you could make a logger like that:

Why not use WDIO hooks for this or a custom reporter that is triggered when commands are being called?

> Or you can implement custom implicit timeout, (since version with [setTimeout](https://webdriver.io/docs/api/browser/setTimeout) is not recommended and it doesn't work with `react$`)

Not sure if I understand you correct here, can you elaborate?

> There are many things that can be done if you differentiate between the commands of the elements and the browser

Sure, but I want to be careful which interfaces I introduce which have to be maintained. This is why I am asking what you like to do with it. If you have use cases that can be valuable in a lot of ways to many folks I am happy to add something otherwise to justify.

**Comment by KuznetsovRoman** [comment]
> Why not use WDIO hooks

They don't provide information about the context of the invoked command. `browser.command` cannot be distinguished from `element.command`

> Not sure if i understand you correct here

I would like to use something like this to get rid of the need to explicitly call `waitForExist`

```ts
const commands = await browser.getElementCommands();

const ignoreCommands = ["waitForExist", "isExisting", ...] // commands, starting with "wait"  or "is"
const overwritingCommands = _.difference(commands, ignoreCommands); // click, getValue, moveTo...

overwritingCommands.forEach(commandName => {
    browser.overwriteCommand(commandName, async function (originFn, ...args) {
        await this.waitForExist({timeout: N});
        
        return originFn(...args);
    }, true)
});
```

Because `setTimeout({implicit: N})`, as mentioned in the documentation, will cause problems with `waitForExist`.

**Comment by christian-bromann** [comment]
There should be no need for this. WebdriverIO automatically uses `waitForExist` for every element command which is why things like:

```ts
await $('foo').click()
```

works. Can you provide an example where this doesn't work as expected?

**Comment by KuznetsovRoman** [comment]
But we can't choose timeout, so it fails if element will appear in ~10 seconds. (`await $('foo').click()` won't just wait that long) Slow Single Page Applications could be an example

**Comment by christian-bromann** [comment]
So you would like to set these explicit timeouts dynamically, per command or in arbitrary positions of your spec file?

**Comment by KuznetsovRoman** [comment]
Command like `setImplicitTimeout` would be nice.

**Comment by christian-bromann** [comment]
Can specify your use case?

> So you would like to set these explicit timeouts dynamically, per command or in arbitrary positions of your spec file?

**Comment by KuznetsovRoman** [comment]
Problem:

```ts
await browser.url('https://lawyersearch.ru');
await browser.$('#__next > div > header > div > div.Bx-rt.css-yn5rap > div > button').click();
// await browser.pause(250); unwrap this to see the login window
await browser.$$('input')[0].setValue('testmal1@mail.ru');
await browser.$$('input')[1].setValue('testtest');
// await browser.pause(250);
await browser.throttle({
    offline: false,
    latency: 500,
    uploadThroughput: 1000,
    downloadThroughput: 10000
})
await browser.$('#__next > div > header > div > div.Bx-rt.css-yn5rap > div > div > div > div > div.css-48h5p0 > button:nth-child(1)').click();
const myPageButton = await browser.$('#__next > div > header > div > div.Bx-rt.css-yn5rap > div > div > div > a > div');
await myPageButton.waitForExist({timeout: 60000}); // This is essential, fails otherwise
await myPageButton.click();
```

I want some command like `browser.setImplicitTimeout` so i wouldn't need to use `await myPageButton.waitForExist({timeout: 60000})`:

```ts
await browser.setImplicitTimeout(60000);

await browser.url('https://lawyersearch.ru');
...
await browser.$('#__next > div > header > div > div.Bx-rt.css-yn5rap > div > div > div > div > div.css-48h5p0 > button:nth-child(1)').click();
await browser.$('#__next > div > header > div > div.Bx-rt.css-yn5rap > div > div > div > a > div').click();
...
```

**Comment by KuznetsovRoman** [comment]
As i see, [there is](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/utils/implicitWait.ts#L18) an implicit wait. The ability to change this `waitForExist`'s timeout would be nice.

**Comment by christian-bromann** [comment]
Have you tried to just do `browser.options.waitforTimeout = 1000`?

**Comment by KuznetsovRoman** [comment]
Oh, didn't know you can set those in runtime
Sorry to disturb
