### ISSUE TITLE
Update Cucumber Version Compatibility from 0.7.0

### ISSUE THREAD

**Issue by kiraLinden** [webdriverio/webdriverio#906]
Could you please update cucumber integration. Only version 0.7.0 seems supported 0.8.1 just died

**Comment by joshuacc** [comment]
:+1: I've also been having problems with this and would like to upgrade to take advantage of new features in Cucumber.

**Comment by christian-bromann** [comment]
I am afraid we don't update the adapter in v3 anymore. In v4 each adapter has an own npm package. We will update the Cucumber version before releasing https://github.com/webdriverio/wdio-cucumber-framework

**Comment by joshuacc** [comment]
@christian-bromann do you have a rough idea of when v4 will be released?

**Comment by christian-bromann** [comment]
We will release a beta soon where you can run a wdio + mocha + dot-reporter setup
Then we start publishing more framework adapters (jasmine, cucumber). No ETA on that though.
