### ISSUE TITLE
Consider exposing a public node API

### ISSUE THREAD

**Issue by philipwalton** [webdriverio/webdriverio#907]
A [PR](https://github.com/webdriverio/gulp-webdriver/pull/27) was recently submitted to [gulp-webdriver](https://github.com/webdriverio/gulp-webdriver) because of a bug where the wdio binary was no longer in the expected location. I think a case can be made that relying on the wdio binary in the first place isn't a good idea, and as shown by the need for the proposed fix, not very future-proof.

Since gulp is a node process and wdio is also a node process, there's really no reason to start a new node subprocess when gulp could just require the internal webdriverio modules and run them.

Exposing a public node API would likely also make it easier for third-party developers to build on top of webdriverio and expands its usefulness.

**Comment by christian-bromann** [comment]
Hi @philipwalton ,
thanks for filing the issue. I totally agree with you. The current solution is suboptimal but it was for me the quickest way to let people use v3 of WebdriverIO using gulp-webdriver. We are currently working on v4 and going to consider this while we move forward. Thanks!

**Comment by philipwalton** [comment]
Great! Good to know.

**Comment by christian-bromann** [comment]
Actually there already is some kind of public API. It is just not documented. To run wdio programatically you just need to require the launcher and run it:

```js
var launcher = require('webdriverio/lib/launcher')

var configFile = require('path/to/wdio.conf.js');
launcher.init(configFile, {}); // last argument could by any cli args
```

**Comment by philipwalton** [comment]
Looks like `launcher.init` takes a filepath rather than an object. So you could do:

```js
var launcher = require('webdriverio/lib/launcher');

launcher.init('./path/to/wdio.conf.js'), {}); // last argument could be any cli args
```

The only problem is it doesn't seem like there's currently any exit hook.

**Comment by christian-bromann** [comment]
This will change in [v4](https://github.com/webdriverio/webdriverio/blob/v4.0/lib/cli.js#L258-L265)
```js
let launcher = new Launcher(configFile, args)
launcher.run().then((exitCode) => {
    if (exitCode instanceof Error) {
        return process.nextTick(() => { throw exitCode })
    }

    process.exit(exitCode)
})
```

**Comment by philipwalton** [comment]
Cool, but just to be extra nit-picky :) it seems like you could avoid returning the exit code in the `then` handler by rejecting the promise and using `catch`. So it might look like:

```js
let launcher = new Launcher(configFile, args)
launcher.run()
  .then(() => process.exit())
  .catch((err) => process.nextTick(() => { throw err }))
```

**Comment by christian-bromann** [comment]
Good point :+1:

**Comment by christian-bromann** [comment]
Last task for this one is to document how to trigger the run method programmatically.

**Comment by dtothefp** [comment]
@christian-bromann I'd like to use this functionality as I'm currently spawning a child process to run wdio and relying on the binary location. Assuming this is in v4 have you release a beta version on npm? I saw an issue on this but was unclear if it's happened yet?

**Comment by christian-bromann** [comment]
@dtothefp no haven't published a beta yet. Will happen this week hopefully.

**Comment by christian-bromann** [comment]
Since this is actually implemented in v4 I will close this PR to clean up the issue list ;-)

**Comment by dtothefp** [comment]
@christian-bromann does that mean there is a beta of v4 on npm yet? Also are there any docs on this feature? Would be great to use instead of a child process

**Comment by christian-bromann** [comment]
Still working on a beta. I hope I can release it until beginning of next year. I will keep you posted. Documentation is part of the release process ;-)

**Comment by dtothefp** [comment]
@christian-bromann just following up, notice v4 went out with significant updates. Has documentation been updated...looks like the changelog and test examples are bending?
