### ISSUE TITLE
test:start not firing when using the cucumber framework

### ISSUE THREAD

**Issue by dhoulker** [webdriverio/webdriverio#909]
I'm using the cucumber framework for my tests. 

I've tried to use a customer reporter that i wrote when using Mocha, however the `test:start` event doesn't seem to be firing when i switch to cucumber.

The `'start'` and `'suite:start'` events are working fine.

Has anyone else run into this?

**Comment by christian-bromann** [comment]
moved to webdriverio/wdio-cucumber-framework#2
