### ISSUE TITLE
[💡 Feature]: Parallelize Tests with multiple data sets

### ISSUE THREAD

**Issue by SRKarumuri** [webdriverio/webdriverio#9090]
### Is your feature request related to a problem?

At the moment in WebdriverIO if I have any Test with multiple set of Data means it can run only concurrently, which is a time taking thing. It would be nice where I have an option to run same test parallelly based on its data sets.

This future will be a big plus to webdriverio Project.

For example where I have 100 Tests in that first 50 tests follows Flow 1 with different set of Data and rest 50 tests follows Flow 2 with different test data. In order to run these 100 tests parallelly I need to create 100 Tests (when any change request comes I end up maintaining all 100 tests which is not a good testing practice). 

If I create 2 Tests and each test runs 50 times with its iteration data means the test runs concurrently and takes lot of time to finish the execution.

### Describe the solution you'd like.

At the moment based on specs files we have added and based on maxInstances it will open those many instances to run parallelly.

Example 1: 
specs: [
        './test/specs/One.ts',
        './test/specs/Two.ts',
    ],
maxInstances: 5

In above case it runs both the scenarios parallelly.

Example 1: 
specs: [
        './test/specs/One.ts',
        './test/specs/Two.ts',
    ],
maxInstances: 1

In above case it runs one by one test concurrently.

I am not sure if it is possible or not to read spec file and check if the Test got any Data Iteration\ data provider if so based on maxInstances it should run that test parallelly.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SRKarumuri** [comment]
@christian-bromann As you suggested I have created the New Feature request for Data Provider

**Comment by christian-bromann** [comment]
> For example where I have 100 Tests in that first 50 tests follows Flow 1 with different set of Data and rest 50 tests follows Flow 2 with different test data.

Does this mean you have 50 individual tests that need to be run on two different data sets?

How about the following solution to this: you can kick off two different testrunner tests [programatically](https://webdriver.io/docs/setuptypes/#launcherconfigpath-opts) and pass in data to fetch a specific data set which you then populate to the worker (e.g. via a service). You can then wait until both of these `launcher.run()` calls finish. That would achieve what you explained already.

**Comment by SRKarumuri** [comment]
> > For example where I have 100 Tests in that first 50 tests follows Flow 1 with different set of Data and rest 50 tests follows Flow 2 with different test data.
> 
> Does this mean you have 50 individual tests that need to be run on two different data sets?
> 
> How about the following solution to this: you can kick off two different testrunner tests [programatically](https://webdriver.io/docs/setuptypes/#launcherconfigpath-opts) and pass in data to fetch a specific data set which you then populate to the worker (e.g. via a service). You can then wait until both of these `launcher.run()` calls finish. That would achieve what you explained already.

For more clarity you can see below example
I have a test called "My Wdio Test" which navigates through 25 Web pages to complete the process.
I want to run "My Wdio Test" parallelly for 50 different data sets. (Lets say my maxInstances: 10)

**Comment by christian-bromann** [comment]
Why is my idea above not working for this example?

**Comment by SRKarumuri** [comment]
> Why is my idea above not working for this example?

Will check more about test launcher programmatically today. Do you have any specific document with more details as I couldn't find much useful one.

**Comment by christian-bromann** [comment]
See https://webdriver.io/docs/setuptypes/#package-api-2

**Comment by christian-bromann** [comment]
Yes, you should be able to pass in custom data like:
```js
capabilities: [{
   browserName: 'chrome',
   'test:data': { ... }
}]

**Comment by SRKarumuri** [comment]
> ```js
> capabilities
> ```

Is there a way to access the test:data in my Test,

**Comment by christian-bromann** [comment]
Yes, `browser.capabilities['test:data']`, see docs: https://webdriver.io/docs/browserobject/

**Comment by SRKarumuri** [comment]
> Yes, `browser.capabilities['test:data']`, see docs: https://webdriver.io/docs/browserobject/

I tried this way earlier which dint worked for me. I retested it again I am getting as Undefined.

**Comment by SRKarumuri** [comment]
> > Yes, `browser.capabilities['test:data']`, see docs: https://webdriver.io/docs/browserobject/
> 
> I tried this way earlier which dint worked for me. I retested it again I am getting as Undefined.

I have used console.log('My Launcher capabilities =>', await browser.capabilities)
```
 My Launcher capabilities => {
[0-0]   acceptInsecureCerts: true,
[0-0]   browserName: 'chrome',
[0-0]   browserVersion: '106.0.5249.119',
[0-0]   chrome: {
[0-0]     chromedriverVersion: '106.0.5249.61 (511755355844955cd3e264779baf0dd38212a4d0-refs/branch-heads/5249@{#569})',
[0-0]     userDataDir: 'C:\\Users\\XY40493\\AppData\\Local\\Temp\\scoped_dir15188_1457339396'
[0-0]   },
[0-0]   'goog:chromeOptions': { debuggerAddress: 'localhost:5750' },
[0-0]   networkConnectionEnabled: false,
[0-0]   pageLoadStrategy: 'normal',
[0-0]   platformName: 'windows',
[0-0]   proxy: {},
[0-0]   setWindowRect: true,
[0-0]   strictFileInteractability: false,
[0-0]   timeouts: { implicit: 0, pageLoad: 300000, script: 30000 },
[0-0]   unhandledPromptBehavior: 'dismiss and notify',
[0-0]   'webauthn:extension:credBlob': true,
[0-0]   'webauthn:extension:largeBlob': true,
[0-0]   'webauthn:virtualAuthenticators': true
[0-0] }




```

**Comment by christian-bromann** [comment]
Ah I am sorry, it is `browser.requestedCapabilities` since these are custom and ignored by the browser.

**Comment by SRKarumuri** [comment]
> Ah I am sorry, it is `browser.requestedCapabilities` since these are custom and ignored by the browser.

Perfect Thanks ``browser.requestedCapabilities`` is working

**Comment by SRKarumuri** [comment]
> Ah I am sorry, it is `browser.requestedCapabilities` since these are custom and ignored by the browser.

Is below wat is correct to run same test parallelly with different data set

```
const Launcher = require('@wdio/cli').default

let base_URL= ['https://www.google.co.za','https://www.google.co.uk','https://www.google.co.in']
for (let i=0; i<base_URL.length; i++)
{
    const wdio = new Launcher('./wdio.conf.ts',
        { 
            spec: ['./test/specs/example.e2e.ts'],
            capabilities: 
            [{
                browserName: 'chrome',
                acceptInsecureCerts: true,
                'test:data':
                {
                    url: base_URL[i]
                }
        
            }],
            services: ['chromedriver'],
        
        }
    )
    
    wdio.run().then((exitCode) => {
        process.exit(exitCode)
    }, (error) => {
        console.error('Launcher failed to start the test', error.stacktrace)
        process.exit(1)
    })

}
```

**Comment by christian-bromann** [comment]
No, this will exit the process for all once the first testrun finishes.

**Comment by SRKarumuri** [comment]
> No, this will exit the process for all once the first testrun finishes.

True same thing happened to me. 
Is there any way to know how many instances are opened. Example: 
I launched 3 instances 
Test 1
Test 2
Test 3

On each test before test can I know how many instances are running parallel and on Test 2 it's intense sequence number.

**Comment by christian-bromann** [comment]
No, the launcher doesn't expose that information afaik.

**Comment by SRKarumuri** [comment]
In launcher I could able to use the switch statement and launch multiple sessions. 

I am wondering what would be the smartest way to pass different set of data to each hook.

**Comment by christian-bromann** [comment]
Is there anything actionable for this issue or do you think this solution can work for you. If you have a proposal on how to integrate this into the WebdriverIO test runner I am happy to hear but if you think the solution through starting the runner programatically works, I think we can close this. What do you think?

**Comment by SRKarumuri** [comment]
> Is there anything actionable for this issue or do you think this solution can work for you. If you have a proposal on how to integrate this into the WebdriverIO test runner I am happy to hear but if you think the solution through starting the runner programatically works, I think we can close this. What do you think?

I am thinking based of spec files and based on max parallel instance it will open those many instances right. If it is possible to read the spec file and if it got loop to the suite means based on the loop count and maxparallelinstances it should open those many instances for same test.

**Comment by christian-bromann** [comment]
@SRKarumuri so we can close this issue? I am happy to work on a blog posts with you once you got a setup running to show other folks how this could be achieved.

**Comment by SRKarumuri** [comment]
> @SRKarumuri so we can close this issue? I am happy to work on a blog posts with you once you got a setup running to show other folks how this could be achieved.

I am happy to close this.
