### ISSUE TITLE
[💡 Feature]: switchToFrame/switchToWindow without side effects to browser

### ISSUE THREAD

**Issue by sezaru** [webdriverio/webdriverio#9096]
### Is your feature request related to a problem?

Currently AFAIK there is no way to run functions like `switchToFrame` and `switchToWindow` without side effects, meaning that running these functions asynchronously can affect other browser calls.

### Describe the solution you'd like.

I would like a way to either "clone" the current browser context into a new browser instance so I can safely use `switchToFrame` and `switchToWindow` in isolation or have an option too so these functions return a new isolated context.

Something like this:

```js
const browser = await remote({...})
...
const browser2 = await browser.switchToFrame(someFrame)
const elementInsideFrame = await browser2.$(someInsideFrameSelector)
const elementOutsideFrame = await browser.$(someOutsideFrameSelector)
```

or

```js
const browser = await remote({...})
...
const browser2 = await browser.cloneContext()
await browser2.switchToFrame(someFrame)
const elementInsideFrame = await browser2.$(someInsideFrameSelector)
const elementOutsideFrame = await browser.$(someOutsideFrameSelector)
```

Would something like this be possible?

if not, can we maybe have a special selector for iframes that would allow us to query them without needing to switch the browser context like we currently have with shadow roots?

Something like this:

```js
const element = await browser.$('>>> iframe#parent_iframe iframe#iframe1 button')
```

### Describe alternatives you've considered.

The only possible way I see now to make this work is to make sure the code from `switchToFrame` to `switchToParentFrame` is blocking.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
> Would something like this be possible?

This is not possible. The browser wouldn't allow you to interact with windows that are to active.

> if not, can we maybe have a special selector for iframes that would allow us to query them without needing to switch the browser context

This is also technically not possible.

> The only possible way I see now to make this work is to make sure the code from `switchToFrame` to `switchToParentFrame` is blocking.

I am not sure what you mean by that but you can always switch back and forth. I don't see how side effects can apply when asynchronous code is run in the correct way using `async/await`.

I will go ahead and close but am happy to assist further.
