### ISSUE TITLE
[🐛 Bug]: EmulateDevice() is not a function

### ISSUE THREAD

**Issue by AlfredoMoretta** [webdriverio/webdriverio#9106]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.25.2

### Node.js Version

14.9.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [
        {
            browserName: 'chrome',
            'goog:chromeOptions': {
                args: [
                    // '--headless',
                    '--no-sandbox',
                    '--incognito',
                    // '--start-fullscreen',
                    '--disable-notifications',
                    '--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36'
                    '--ignore-certificate-errors', 
                ],
                prefs: {
                    /*
                        0 ==> default
                        1 ==> Allow
                        2 ==> Block
                    */
                    // 'profile.managed_default_content_settings.javascript': 2,
                    // 'profile.managed_default_content_settings.images': 2,
                    'profile.default_content_setting_values.notifications': 2,
                    // 'profile.managed_default_content_settings.stylesheets':2,
                    // 'profile.managed_default_content_settings.cookies': 2,
                    'profile.managed_default_content_settings.plugins': 2,
                    'profile.managed_default_content_settings.popups': 2,
                    'profile.managed_default_content_settings.geolocation': 2,
                    'profile.managed_default_content_settings.media_stream': 2,
                },
            },
        },
    ],
```

### What happened?

i added as described in documentation services: ['devtools'] ,and put it in my package.json :
`"dependencies": {
        "wdio-chromedriver-service": "^7.3.2",
        "@wdio/allure-reporter": "^7.24.0",
        "@wdio/cli": "^7.24.0",
        "@wdio/cucumber-framework": "^7.24.0",
        "@wdio/devtools-service": "^7.25.2",
        "@wdio/selenium-standalone-service": "^7.24.0",
        "@wdio/spec-reporter": "^7.24.0",
        "@wdio/sync": "^7.24.0",
        "@wdio/reporter": "7.25.1",
        "@wdio/local-runner": "^7.24.0",
        "@babel/cli": "7.12.1",
        "@babel/core": "7.12.3",
        "@babel/preset-env": "7.12.1",
        "@babel/register": "7.12.1",
        "@wdio/codemod": "^0.12.0",
        "chromedriver": "^105.0.0",
        "cucumber-html-reporter": "5.2.0",
        "webdriverio": "^7.24.0",
        "wdio-cucumberjs-json-reporter": "4.4.3"
    }`

when i write the code it recognize emulateDevice() as a method ,but when i run a test the error is :
`TypeError: browser.emulateDevice is not a function`

### What is your expected behavior?

i expect to run my tests emulate devices with emulateDevice() function, but i always have :
`TypeError: browser.emulateDevice is not a function` as error

### How to reproduce the bug.

openURI() { 
browser.emulateDevice('iPhone X');
browser.url('http://www.google.com);
}

### Relevant log output

```typescript
[chrome 106.0.5249.119 mac os x #0-0] TypeError: browser.emulateDevice is not a function
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Do you have a minimal reproducible example?

**Comment by AlfredoMoretta** [comment]
good morning christian and first of all thanks to answer me.
In my project i use cucumber as you can see from my package.json.

I've the error immediately in the Given step:

`Given(/^a logged in user  in UK$/, nation => {
    CommonPage.openURI('LOGIN', nation);})`
    
    and my CommonPage.openURI is this:
`openURI(page, nation) {
        const _nation = nation.toUpperCase();
        const _url = this.pages[page]
            ? page == 'HOMEPAGE'
                ? _magicURL(this.host, this.countries, _nation)
                : this.host.concat(
                      '/',
                      this.countries[_nation],
                      '/',
                      this.pages[page]
                  )
            : this.host.concat('/', this.countries[_nation]);
        console.log(browser.capabilities);
       browser.emulateDevice('iPhone X');
        browser.url(`https://${_url}`);}`

**Comment by christian-bromann** [comment]
@AlfredoMoretta unfortunately this doesn't help much to reproduce it, given I don't have your Cucumber code. Please try to provide an example I can run on my machine as well that doesn't require a special set up.

**Comment by AlfredoMoretta** [comment]
@christian-bromann  thank you for your support,i really appreciate your work.Till we can't reproduce the issue ,in my opinion you can close this issue.
