### ISSUE TITLE
How do I test my website with a different IE version

### ISSUE THREAD

**Issue by wzl610** [webdriverio/webdriverio#911]
I already placed the IEDriver in the path,when I write the test case as follow:
```javascript
var options = {
    desiredCapabilities: {
        browserName:'internet explorer',
        version:7
    }
};
```
and then it open the IE with version 11,however I change the version of the ie,it also open the version 11,how can I change the version of it?Thank you!

**Comment by christian-bromann** [comment]
If you only have one IE installed on your system in only can run that version. If you want to test multiple IEs I would recommend to use services like Sauce Labs.

**Comment by wzl610** [comment]
Thanks
