### ISSUE TITLE
Always call `onComplete`

### ISSUE THREAD

**Issue by georgecrawford** [webdriverio/webdriverio#912]
I haven't looked into what would be required to do this, but I think the `onComplete` hook should always be called, even when an exception has been thrown somewhere serious. A common use for `onPrepare`/`onComplete` will be to start a service locally (Appium, Selenium Standalone, etc.), and it's important to teardown these processes and to leave the system healthy after a failed test run.

**Comment by christian-bromann** [comment]
I implemented services with launch modules (e.g. `wdio-sauce-service/launcher`) in a way that they never stop the test process. I also made sure that the test process itself never throws (so it resolves always with an exit code). It might make sense to introduce an option that prevents that tests even start if one of the launch services failed (which should not be the common case).

**Comment by georgecrawford** [comment]
Thanks.
