### ISSUE TITLE
[💡 Feature]: Soft assertions ( assertions that fail, but dont cause the current block to end ) 

### ISSUE THREAD

**Issue by paulmrogers** [webdriverio/webdriverio#9125]
### Is your feature request related to a problem?

I usually work on integration tests. By this I mean long running tests that run against a full environment.
If i have several assertions in an it block ( I hope Im using the correct terms here ), Id like to know the reult of all of them before moving onto the next block.
For example, if im working on a payroll application, I may have assertions for gross pay, tax deducted, insurance deducted etc.
On an integration test, Ive likely to had to log in, do some other actions ( eg, log the number of hours worked ) before I can access the payroll.
If it fails on the first assertion, I have no idea if the others are ok, or also will fail.

### Describe the solution you'd like.

some mechanism to say "Continue running if these assertions fail,but record the outcome"
Id also like the abilty to end the execution early on unrecoverable errors. eg, if i cant login to the app, probably not a lot of point in continuing.

Maybe something liek this:

```
describe ('my appliction'), function(){

  it ('logins to the appliaction')() => {
      onFail()=>{
         exit()
     }
     await browser.url('https://someapp')
     assert.equal( browser.title , "The Home Page" )
     assert( browser.$('username')..isExisting())
  }

  it ('gets the payroll info')() => {
    onFail() => { continue }
    assert.equal( browser.$('hoursWorked').getText(), '40').  // if this fails we carry on to the next assertion
    assert.equal( browser.$('hoursAbsent').getText(), '0')
    
  }  

}
```
And somewhere in the reults we have

```
✓ logins to the appliaction 
✖gets the payroll info -> Failure on hoursWorked
                                       ->  hoursAbsent ✓
```       
The test I am currently working on so far has 26 assertions. I possibly could break them into smaller chunks, but they are all on the same page, so seems appropriate to keep them together, and splitting them up gives scoping problems with variables.

### Describe alternatives you've considered.

Ive tried splitting the assertions into different blocks, but I keep umping into scoping problems with variables

### Additional context

im pretty new to javascript and webdriver ( lots of experience with other testing tools ) and had similar issues with those, but maybe there is some technique im missing with this language and framework

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Hey @paulmrogers , thanks for raising the issue.

We have an [open issue](https://github.com/webdriverio/expect-webdriverio/issues/227) to support soft assertions out of the box.If you use the wdio testrunner with Jasmine you will have soft assertions too.

I will go ahead and close but am happy to answer further questions.

**Comment by paulmrogers** [comment]
thanks for the reply. I'll go check this out

**Comment by muzammilzahoor291-cloud** [comment]
Using [instafinsta](https://instafinsta.co/) has been a surprisingly enjoyable experience. The platform combines speed, simplicity, and functionality in an impressive way. I never feel confused while navigating its features, and everything responds smoothly. It is wonderful to see a service that focuses on quality while keeping the user experience comfortable and convenient.
