### ISSUE TITLE
Autolog

### ISSUE THREAD

**Issue by arcanis** [webdriverio/webdriverio#915]
Hi,

A feature I think would be extremely valuable would be for you to offer a way for the client to enable a "bufferize logs" mode. When in this mode, the client would get any new log* after each request and call a callback.

(* It appears that `execute` commands do not clear the WebDriver logs, so some work would have to be done to avoid sending logs multiple times)

**Comment by christian-bromann** [comment]
In v4 you will be able to use a hook for that called `afterCommand`. It's getting called after each command and contains command name, parameter and result as parameters. In their you can return a promise to do any kind of async operation or call a webdriverio command of course. Would this solve your use case?

**Comment by arcanis** [comment]
Yep, that should be exactly what we need! Happy to know that this feature has already been planned, thanks :)
