### ISSUE TITLE
[🐛 Bug]: Cannot disable w3c for Firefox browser

### ISSUE THREAD

**Issue by tv2022** [webdriverio/webdriverio#9154]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

14.20.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
	acceptInsecureCerts: true,
	browserName: 'firefox',
	'moz:firefoxOptions': {
		binary: '/Applications/Firefox-87.app/Contents/MacOS/firefox-bin',
		args: ['--ignore-certificate-errors'],
		w3c: false
	}
}
```

### What happened?

Not able to disable the w3c command to perform Drag and drop or mouse touch actions on Firefox. Chrome capability allows w3c: false option in capabilities but Firefox doesn't allow it. 

### What is your expected behavior?

Firefox capability should allow this capability `w3c: false`

### How to reproduce the bug.

Try to start the Firefox browser using below capability values.

```typescript
{
	acceptInsecureCerts: true,
	browserName: 'firefox',
	'moz:firefoxOptions': {
		binary: '/Applications/Firefox-87.app/Contents/MacOS/firefox-bin',
		args: ['--ignore-certificate-errors'],
		w3c: false
}```

### Relevant log output


Failed to start the session with the below error:

```typescript
Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
23:15:21.505 INFO [ServicedSession$Factory.apply] - Invalid moz:firefoxOptions field w3c
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'C02DG8JVMD6R', ip: '2600:1700:512:1c30:0:0:0:41%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '11.0.4'
Driver info: driver.version: unknown
remote stacktrace: 
org.openqa.selenium.InvalidArgumentException: Invalid moz:firefoxOptions field w3c
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'C02DG8JVMD6R', ip: '2600:1700:512:1c30:0:0:0:41%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '11.0.4'
Driver info: driver.version: unknown
remote stacktrace:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Hey @tv2022 , thanks for raising an issue.

This is unfortunately nothing we can fix in WebdriverIO. Please raise this issue in the [Geckodriver](https://github.com/mozilla/geckodriver/releases) project. Thanks!

**Comment by tv2022** [comment]
@christian-bromann Thanks for the quick reply. The reason for raising this issue here is the same capabilities works fine with other. tools like Protractor with the same Geckodriver version 0.32.0 only with WebDriverIO it's throwing an error. Do you still think it's not WebDriverIO specific?

**Comment by christian-bromann** [comment]
Protractor doesn't work with Geckodriver as it communicates through WebdriverBidi or Chrome Devtools but not the WebDriver v1.
