### ISSUE TITLE
Xunit reporter reporting false failures

### ISSUE THREAD

**Issue by dimirey** [webdriverio/webdriverio#916]
The xunit reporter is consistently tagging my cucumber test cases as 'failed' even though there is no obvious failure in the test. Another issue is that the tests that are marked as 'failed' do not increment the testsuite failures. I'm using webdriverio v 3.3.0 and cucumber v 0.5.3

`<testsuites name="firefox.40_0.osx10_10" tests="0" failures="0" errors="0" disabled="0" time="181.157">
  <testsuite name="Sanity (Repeat notifications and Restrict contacts)" tests="0" failures="0" skipped="0" disabled="0" time="177.297" timestamp="Tue Dec 01 2015 15:53:47 GMT-0800 (PST)" id="1" file="/features/web_cn_sanity/sanity_repeatnotifications.feature">
      <testsuite name="Enable Repeat notifications" tests="12" failures="0" skipped="0" disabled="0" time="150.651" timestamp="Tue Dec 01 2015 15:53:47 GMT-0800 (PST)" id="2" file="/features/web_cn_sanity/sanity_repeatnotifications.feature">
          <testcase name="I am on the test homepage" disabled="false" time="124.577" id="3" file="/features/web_cn_sanity/sanity_repeatnotifications.feature" status="failed" classname="firefox.40_0.osx10_10">
              <system-out type="command"><![CDATA[
POST http://ondemand.saucelabs.com:80/wd/hub/session - {"desiredCapabilities":{"browserName":"firefox","version":"40.0","javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"platform":"OS X 10.10","screenResolution":"1280x1024","name":"Feature: Sanity (Repeat notifications and Restrict contacts)","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"3.3.0","name":"webdriverio"}}}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/execute - {"script":"window.onbeforeunload = function() {};","args":[]}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/url - {"url":"https://qa-console.test.me/"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"[data-class='index.input_email']"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/0/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element - {"using":"css selector","value":"[data-class='index.input_email']"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element/0/value - {"value":["t"]}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"[data-class='index.input_password']"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/1/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element - {"using":"css selector","value":"[data-class='index.input_password']"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element/1/value - {"value":["t"]}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"[data-class='index.button_login']"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/2/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element - {"using":"css selector","value":"[data-class='index.button_login']"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element/2/click - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#menuBarCntr > div.header.headerCompose > div"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/3/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/4/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/4/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/4/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/4/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/4/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/4/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/4/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/4/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/4/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/4/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/4/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/4/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"[data-class='home.header.settings_icon']"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/5/displayed - {}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/4/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element - {"using":"css selector","value":"[data-class='home.header.settings_icon']"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element/5/click - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"[data-class='home.admin.contexts']"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/4/displayed - {}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/6/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element - {"using":"css selector","value":"[data-class='home.admin.contexts']"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element/6/element - {"using":"xpath","value":"./option[normalize-space(.) = \"test_test Repeat Notifications\"]|./optgroup/option[normalize-space(.) = \"test_test Repeat Notifications\"]"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element/7/click - {}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/4/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"[data-class='home.admin.orgTab']"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/8/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element - {"using":"css selector","value":"[data-class='home.admin.orgTab']"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element/8/click - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#rn "}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/4/displayed - {}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/9/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#rn "}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/9/selected - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element - {"using":"css selector","value":"#rn "}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element/9/click - {}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/4/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/4/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#orgSettingsHeader > div > div.btnSave > button"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/10/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element - {"using":"css selector","value":"#orgSettingsHeader > div > div.btnSave > button"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element/10/click - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#rn "}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#rn "}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/9/selected - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"[data-class='button_logout']"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/11/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element - {"using":"css selector","value":"[data-class='button_logout']"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element/11/click - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/execute - {"script":"window.onbeforeunload = function() {};","args":[]}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/url - {"url":"https://qa-console.test.me/"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"[data-class='index.input_email']"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/12/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element - {"using":"css selector","value":"[data-class='index.input_email']"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element/12/value - {"value":[t]}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"[data-class='index.input_password']"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/13/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element - {"using":"css selector","value":"[data-class='index.input_password']"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element/13/value - {"value":["t"]}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"[data-class='index.button_login']"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/14/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element - {"using":"css selector","value":"[data-class='index.button_login']"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element/14/click - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#menuBarCntr > div.header.headerCompose > div"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/15/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/16/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/16/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/16/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/16/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/16/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/16/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/16/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/16/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/16/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/16/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/16/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/16/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"[data-class='home.header.settings_icon']"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/16/displayed - {}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/17/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element - {"using":"css selector","value":"[data-class='home.header.settings_icon']"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element/17/click - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"[data-class='home.admin.contexts']"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/16/displayed - {}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/18/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element - {"using":"css selector","value":"[data-class='home.admin.contexts']"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element/18/element - {"using":"xpath","value":"./option[normalize-space(.) = \"test_test Repeat Notifications\"]|./optgroup/option[normalize-space(.) = \"test_test Repeat Notifications\"]"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element/19/click - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"[data-class='home.admin.orgTab']"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/16/displayed - {}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/20/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element - {"using":"css selector","value":"[data-class='home.admin.orgTab']"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element/20/click - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#rn "}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/16/displayed - {}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/21/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#rn "}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/21/selected - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element - {"using":"css selector","value":"#rn "}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#helpOverlay > div.helpBack"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element/21/click - {}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/16/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#orgSettingsHeader > div > div.btnSave > button"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/22/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element - {"using":"css selector","value":"#orgSettingsHeader > div > div.btnSave > button"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element/22/click - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#rn "}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"#rn "}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/21/selected - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/elements - {"using":"css selector","value":"[data-class='button_logout']"}
GET http://ondemand.saucelabs.com:80/wd/hub/session/0/element/23/displayed - {}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element - {"using":"css selector","value":"[data-class='button_logout']"}
POST http://ondemand.saucelabs.com:80/wd/hub/session/0/element/23/click - {}
DELETE http://ondemand.saucelabs.com:80/wd/hub/session/0 - {}
]]></system-out>``

**Comment by christian-bromann** [comment]
@dimirey thanks for reporting this issue. We will try to reproduce the issue in our new junit reporter that will be available with v4. Let's continue our conversation there.
