### ISSUE TITLE
[🐛 Bug]: node16 module resolution issues - @wdio/globals/types, expect-webdriverio

### ISSUE THREAD

**Issue by SCG82** [webdriverio/webdriverio#9160]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.0.0-alpha.249

### Node.js Version

18.10.0

### Mode

WDIO Testrunner

### What happened?

`module: esnext`, `moduleResolution: node` seems to work in my ESM project (with `npm i --legacy-peer-deps`), but with `module: node16`, `moduleResolution: node16` there's a TSC error: `Cannot find type definition file for '@wdio/globals/types'` (same error for `expect-webdriverio`).

tsconfig:
```json
{
    "compilerOptions": {
        "module": "node16",
        "target": "es2022",
        "allowJs": false,
        "allowUnreachableCode": false,
        "allowUnusedLabels": false,
        "esModuleInterop": true,
        "forceConsistentCasingInFileNames": true,
        "incremental": false,
        "isolatedModules": true,
        "moduleResolution": "node16",
        "noEmit": true,
        "noFallthroughCasesInSwitch": true,
        "noImplicitOverride": true,
        "noImplicitReturns": true,
        "noUncheckedIndexedAccess": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "preserveConstEnums": true,
        "skipLibCheck": true,
        "sourceMap": false,
        "strict": true,
        "types": [
            "node",
            "mocha",
            "@wdio/globals/types",
            "@wdio/mocha-framework"
        ]
    }
}
```

### How to reproduce the bug.

To reproduce this bug:
- use node 18.10.0
- clone https://github.com/webdriverio/cucumber-boilerplate
- edit package.json: change typescript version to `^4.8.4`
- edit tsconfig: change `module` and `moduleResolution` to `node16`
- run `npm i`
- run `npx tsc --noEmit`

### Relevant log output

```shell
error TS2688: Cannot find type definition file for '@wdio/globals/types'.
  The file is in the program because:
    Entry point of type library '@wdio/globals/types' specified in compilerOptions

  tsconfig.json:52:7
    52       "@wdio/globals/types",
             ~~~~~~~~~~~~~~~~~~~~~
    File is entry point of type library specified here.

error TS2688: Cannot find type definition file for 'expect-webdriverio'.
  The file is in the program because:
    Entry point of type library 'expect-webdriverio' specified in compilerOptions

  tsconfig.json:54:7
    54       "expect-webdriverio"
             ~~~~~~~~~~~~~~~~~~~~
    File is entry point of type library specified here.


Found 2 errors.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment]
node16 is only supported for typescript 4.7+

**Comment by erwinheitzman** [comment]
Reference: https://www.typescriptlang.org/tsconfig#moduleResolution

**Comment by erwinheitzman** [comment]
@SCG82 can you make sure you meet the requirements for using this and close the issue if it works?

**Comment by SCG82** [comment]
I'm using Typescript 4.8.4

**Comment by SCG82** [comment]
https://github.com/webdriverio/webdriverio/pull/9170 & https://github.com/webdriverio/expect-webdriverio/pull/934 will resolve this issue

**Comment by mikob** [comment]
@SCG82 I'm still getting this error:
```
{
  "compilerOptions": {
    "declaration": true,
    "target": "esnext",
    "outDir": "dist",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "skipLibCheck": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "noImplicitAny": false,
    "lib": [
      "esnext",
      "dom",
    ],
    "types": [
      "node",
      "@wdio/globals/types"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.tsx",
    "src/**/*.vue"
  ]
}
```

```
    "webdriverio": "^8.3.9"
    "typescript": "4.9.5",
    "@wdio/types": "^8.3.0",
```

**Comment by christian-bromann** [comment]
@mikob please provide a reproducible example

**Comment by goosewobbler** [comment]
@christian-bromann I'm getting this issue with `wdio-electron-service` when I try to upgrade TS to 5.1 - you can see this error in this [PR build](https://github.com/webdriverio-community/wdio-electron-service/actions/runs/5316012109/jobs/9625065453?pr=81).

**Comment by christian-bromann** [comment]
@goosewobbler mind raising a new issue for this?
