### ISSUE TITLE
Hi, I want to ask why the node is limited to >=12.0.0 <16 on v7

### ISSUE THREAD

**Issue by ouliuquan** [webdriverio/webdriverio#9198]
This confuses me on nodejs 16 and nodejs 18, I can't use v7 but I can use v6. Can this be fixed?

v7:
https://github.com/webdriverio/webdriverio/blob/8475c2bfd0480e1870fbeb9a781b5ffbad526c38/packages/wdio-sync/package.json#L10

v6:
https://github.com/webdriverio/webdriverio/blob/50fe76c577ec654c5df67af766bd1c171db7cb2f/packages/wdio-sync/package.json#L10

**Comment by christian-bromann** [comment]
Read more about this here: https://webdriver.io/blog/2021/07/28/sync-api-deprecation

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by ouliuquan** [comment]
@christian-bromann Thanks for the answer and the link, got me in a new direction.
