### ISSUE TITLE
[🐛 Bug]: Remove Sauce Headless Suggestion in Setup Wizard

### ISSUE THREAD

**Issue by mmchen01** [webdriverio/webdriverio#9199]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### What happened?

Installing the webdriver.io setup and in the wizard there is the option to run on Sauce headless. This suggestion in the wizard needs to be removed/updated. Sauce is in the process of EOL for the Headless containerized environment in US-East. Headless mode can still be used through webdriver capabilities however the containerized US-East headless environment will not exist after the EOL is complete.

https://github.com/webdriverio/webdriverio/blob/2091b60cc1a91ee7b4c89e6864708a3c8d74879c/packages/wdio-cli/src/constants.ts#L315

### How to reproduce the bug.

Install the webdriver.io and go through the wizard

### Relevant log output

```typescript
'Do you want to run your test on Sauce Headless? (https://saucelabs.com/products/web-testing/sauce-headless)'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment]
Hi @mmchen01 do you happen to have a reference of this removal?

**Comment by christian-bromann** [comment]
Removed for `v8` in `main` branch, see https://github.com/webdriverio/webdriverio/commit/13cd692fafcb6ae80309b50d2490201de92a7c5f#diff-77007d1fd1f17a3a42b172c92c6000f6ac64d45f7091c24822551c25d0a9d45fL313-L318

**Comment by christian-bromann** [comment]
@mmchen01 this is fixed and release within v8. If you like to have the same fixed in v7 feel free to send a PR. Thanks!
