### ISSUE TITLE
Disable Cookies in Firefox

### ISSUE THREAD

**Issue by RedMage** [webdriverio/webdriverio#920]
Hello.

I am tring to disable cookies in firefox but to no avail. Here is my setup code:

    var webdriverio = require('webdriverio');
    var firefox_profile = require('firefox-profile');
    var util = require('util');

    var profile = new firefox_profile();

    profile.setPreference("network.cookie.cookieBehavior", 2);
    var options  = { desiredCapabilities: { browserName: 'firefox', firefox_profile: profile }};
    Browser = webdriverio.remote(options).init(options);
    console.dir(Browser.options.desiredCapabilities.firefox_profile.defaultPreferences);

The output of the defaultPreferences reveals the custom setting. However, cookies are still active in the browser instance. 

Here is the output from the selenium server

    Done: [new session: Capabilities [{loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@392f71f6, firefox_profile={userPrefs=/tmp/692cc754-5b15..., platform=ANY, javascriptEnabled=true, handlesAlerts=true, browserName=firefox, requestOrigins={name=webdriverio, url=http://webdriver.io, version=3.2.6}, rotatable=true, locationContextEnabled=true, desiredCapabilities={firefox_profile={userPrefs=/tmp/692cc754-5b15-4f5f-b499-7c948b1a4882/user.js, defaultPreferences={extensions.update.notifyUser=false, devtools.errorconsole.enabled=true, security.warn_entering_secure.show_once=false, extensions.update.enabled=false, browser.dom.window.dump.enabled=true, dom.disable_open_during_load=false, offline-apps.allow_by_default=true, extensions.blocklist.enabled=false, browser.startup.page=0, toolkit.telemetry.rejected=true, prompts.tab_modal.enabled=false, app.update.enabled=false, app.update.auto=false, network.cookie.cookieBehavior=2, toolkit.networkmanager.disable=true, network.manage-offline-status=false, browser.search.update=false, toolkit.telemetry.enabled=false, browser.link.open_newwindow=2, extensions.autoDisableScopes=10, browser.EULA.override=true, browser.EULA.3.accepted=true, security.warn_entering_weak=false, browser.safebrowsing.enabled=false, toolkit.telemetry.prompted=2, security.warn_entering_secure=false, security.warn_leaving_secure.show_once=false, browser.download.manager.showWhenStarting=false, webdriver_accept_untrusted_certs=true, dom.max_script_run_time=30, javascript.options.showInConsole=true, network.http.max-connections-per-server=10, network.http.phishy-userpass-length=255, extensions.logging.enabled=true, browser.offline=false, security.warn_leaving_secure=false, browser.link.open_external=2, signon.rememberSignons=false, webdriver_enable_native_events=true, browser.tabs.warnOnClose=false, security.fileuri.origin_policy=3, security.fileuri.strict_origin_policy=false, webdriver_assume_untrusted_issuer=true, startup.homepage_welcome_url="about:blank", browser.shell.checkDefaultBrowser=false, browser.safebrowsing.malware.enabled=false, security.warn_submit_insecure=false, security.warn_viewing_mixed=false, browser.sessionstore.resume_from_crash=false, browser.tabs.warnOnOpen=false, security.warn_entering_weak.show_once=false, security.warn_viewing_mixed.show_once=false}, _preferencesModified=true, profileDir=/tmp/692cc754-5b15-4f5f-b499-7c948b1a4882, _deleteZippedProfile=true, _deleteOnExit=true, extensionsDir=/tmp/692cc754-5b15-4f5f-b499-7c948b1a4882/extensions}, browserName=firefox}, version=}]]

It does not appear to be actually using my preferences. Is there some thing I am missing in the setup?

**Comment by JosePedroDiasSky** [comment]
Take a look at the examples on its page: https://github.com/saadtazi/firefox-profile-js
On both examples the profile sent to webdriver is the the encoded one, so:

After setting up your profile (`profile.setPreference()`, etc.), you must call the asynchronous `profile.encoded(cb)` method which returns the encoded profile to its callback. Assign the encoded profile as value for the desiredCapabilities firefox_profile key. Worked for me.

**Comment by christian-bromann** [comment]
We now have a service that makes this even easier. Checkout https://github.com/webdriverio/wdio-firefox-profile-service. Closing
