### ISSUE TITLE
[🐛 Bug]: Test hooks `beforeTest` and `afterTest` in config/service don't get called for static skipped and pending tests

### ISSUE THREAD

**Issue by nagpalkaran95** [webdriverio/webdriverio#9205]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v7

### Node.js Version

14.20.0

### Mode

WDIO Testrunner

### What happened?

The hooks should be called for all skipped tests (static + dynamic) and pending tests (pending = no test definition)

The hooks are only getting called for dynamic skipped tests.

### What is your expected behavior?

The hooks should be called for tests that are skipped (static + dynamic) and pending tests (tests which have no definition)

### How to reproduce the bug.

* Add beforeTest and afterTest hooks in your service/config file
```
// sample config file
exports.config = {
    specs: ['./specs/sampleError.js'],
    exclude: [],
    maxInstances: 5,
    capabilities: [{
        maxInstances: 5,
        browserName: 'chrome',
        acceptInsecureCerts: true,

    }],
    logLevel: 'error',
    bail: 0,
    baseUrl: 'http://localhost',
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    services: ['chromedriver'],
    framework: 'mocha',
    reporters: ['spec'],

    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },

    afterTest: async (test, context, result) => {
      console.log('After Test Global Config Hook')
    },

    beforeTest: async (test, context) => {
      console.log('Before Test Global Config Hook')
    },
}
```

* Run a sample test file as given below
```
// sample test file
describe('test', function() {
  context('example', function () {

     // hooks will be called
      it('Dynamic Skip', function() {
          console.info('Dynamic Skip')
          if(true)
              this.skip()
      });

     // hooks won't be called
      it.skip('static skip', async () => {
          console.info('static skip')
      });

     // hooks won't be called
     it('Pending Test');
  });
});
```

### Relevant log output

```typescript
$ npx wdio run ./wdio-issue.conf.js                                                                                                                        

Execution of 1 workers started at 2022-11-18T11:09:39.453Z

[0-0] RUNNING in chrome - /specs/sampleError.js
[0-0] Before Test Global Config Hook
[0-0] Dynamic Skip
[0-0] After Test Global Config Hook
[0-0] PASSED in chrome - /specs/sampleError.js

 "spec" Reporter:
------------------------------------------------------------------
[chrome 107.0.5304.110 mac os x #0-0] Running: chrome (v107.0.5304.110) on mac os x
[chrome 107.0.5304.110 mac os x #0-0] Session ID: e9496779148f3915296b5559097db03d
[chrome 107.0.5304.110 mac os x #0-0]
[chrome 107.0.5304.110 mac os x #0-0] » /specs/sampleError.js
[chrome 107.0.5304.110 mac os x #0-0] test
[chrome 107.0.5304.110 mac os x #0-0]     example
[chrome 107.0.5304.110 mac os x #0-0]        ? Dynamic Skip
[chrome 107.0.5304.110 mac os x #0-0]        - Dynamic Skip
[chrome 107.0.5304.110 mac os x #0-0]        - static skip
[chrome 107.0.5304.110 mac os x #0-0]        - Pending Test
[chrome 107.0.5304.110 mac os x #0-0]
[chrome 107.0.5304.110 mac os x #0-0] 3 skipped (73ms)


Spec Files:	 1 passed, 1 total (100% completed) in 00:00:08
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Hey,
thanks for filing the issue. This seems like something we want as service are using these hooks and would be interested in data for skipped tests as well. We should ensure to pass in a `isSkipped` flag to allow services to skip any operation in case they aren't interested operating on skipped tests.

We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by christian-bromann** [comment]
> The hooks should be called for all skipped tests (static + dynamic) and pending tests (pending = no test definition)

Just revisiting this. Unfortunately Mocha sorts skipped and pending tests out and there is not really a chance to execute something in here. While we wrap the it call and technically can tap into this the wdio hook would could not behave like other wdio hooks since we can't prevent Mocha from continuing until the hook is executed.

All in all while it seems feasible it is connected with a lot of hacks and I don't see much value providing hooks also for skipped or pending tests. If you like to get ahold of these information, you can use a reporter or have a reporter/service combination.
