### ISSUE TITLE
Is it possible to include user input in a middle of woriking proccess?

### ISSUE THREAD

**Issue by ishikawayoshi** [webdriverio/webdriverio#921]
Hi, i have a one question about webdriver.io is it possible to include user input in a middle of working procces, e.g manualy click button and handle it and after that continue procces?

**Comment by christian-bromann** [comment]
Yeah, you can use the readline module for that. Kinda like how debug works: https://github.com/webdriverio/webdriverio/blob/master/lib/commands/debug.js
