### ISSUE TITLE
[💡 Feature]: window.postMessage(...)

### ISSUE THREAD

**Issue by ingemarson** [webdriverio/webdriverio#9214]
### Is your feature request related to a problem?

yes, I already ask a question on gitter but without any success. the problem I have, is that the html page uses postMessage to send messages between a main window and a popup. my page object should be able to hook on that using  window.addEventListener("message", ...). 

### Describe the solution you'd like.

maybe access to the window object? or something like browser.addEventListener("message", ...) ...

### Describe alternatives you've considered.

- executeAsync returning the window object => fail
- executeAsync receiving some callback => fail

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
@ingemarson thanks for filing the issue.

This is currently technically not possible. I recommend raise a feature request in https://github.com/w3c/webdriver-bidi as it should be supported as event in the protocol at some point. I will close as there is currently nothing actionable. There might be ways to achieve this with the devtools automation protocol.

**Comment by ingemarson** [comment]
hey christian, many thanks for your fast response! kind of disappointing, but as it is technically not possible, what should you do ;-)
