### ISSUE TITLE
Issue with Parallel tests in WebdriverIO for varied dataset

### ISSUE THREAD

**Issue by Zarmeena** [webdriverio/webdriverio#9257]
> @Trueside you can always do things like this:
> 
> ```js
> describe(' TEST ', async () => {
>     for (const case of Object.values(dataObject)) {
>         it(`test with ${case.username}`, () => {
>             // case.username
>             // case.password
>         })
>     }
> })
> 
> dataObject = {
>     case1: {
>         username: 'validName',
>         password: 'validPass'
>     },
>     case2: {
>         username: 'invalidName',
>         password: 'invalidPass'
>     }
> }
> ```

@christian-bromann How can we execute Selenium tests in parallel through this? It continues to execute with next dataset in the currently focused browser window, itself and abruptly terminate. Also, it considers it to be a single execution instead of 2, corresponding to the dataset used.

_Originally posted by @Zarmeena in https://github.com/webdriverio/webdriverio/issues/4452#issuecomment-1330441248_

**Comment by erwinheitzman** [comment]
You're not using a unique name so the first result is overwritten with the second which is why you only see one.
You cannot run these in parallel while they are in the same file. In order to use one dataset I would dynamically create the test files using fs.writeFileSync and using a string template.

**Comment by erwinheitzman** [comment]
Oh and please refrain from pinging individuals when it's not needed.

**Comment by Zarmeena** [comment]
The example quoted above was from one of the discussions in past from another user, and was used by me for reference. 

Also, I have already gone through the WebdriverIO documentation , my problem statement is different from standard parallel execution which I have already implemented. 

Thanks for your response

**Comment by christian-bromann** [comment]
> my problem statement is different from standard parallel execution which I have already implemented.

Running tests within a single spec in parallel is not supported by WebdriverIO. We advise to split up tests into multiple spec files.
