### ISSUE TITLE
wdio doesn't work with Chrome 108

### ISSUE THREAD

**Issue by sdoigmm** [webdriverio/webdriverio#9258]
Chrome's latest version is 108. I have 108 installed.

I can't use wdio with ChromeDriver 106, as it won't work with Chrome 108.

The ChromeDriver npm package's latest version is 107.

Will I have to upgrade wdio to use ChromeDriver 107, and roll back my Chrome to use 107?

**Comment by christian-bromann** [comment]
You can customise which Chromedriver is version is being downloaded, see `CHROMEDRIVER_VERSION` environment variable, see also https://github.com/giggio/node-chromedriver#versioning

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
