### ISSUE TITLE
XUnit outputDir can't handle absolute paths

### ISSUE THREAD

**Issue by yozlet** [webdriverio/webdriverio#926]
The XUnit reporter appends the specified `outputDir` to the current working directory even if `outputDir` starts with `/`. So, if you specify an `outputDir` of `/tmp/test-reports/` the reporter will actually write to `$CWD/tmp/test-reports/`.

The code in question is here: https://github.com/webdriverio/webdriverio/blob/master/lib/reporter/xunit.js#L173

/cc @shawnbot

**Comment by christian-bromann** [comment]
the xunit reporter moved to another repository. We will make sure to fix that before we release that package.
