### ISSUE TITLE
[🐛 Bug]: attach to session will not decorate protocol commands to the driver object

### ISSUE THREAD

**Issue by CNLHC** [webdriverio/webdriverio#9260]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

main

### Node.js Version

v16.16.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
    platformName: "Android",
    platformVersion: "12",
    automationName: "uiautomator2",
    "appium:noReset": true,
    "appium:appPackage": "*",
    "appium:appActivity": "*",
    "appium:ensureWebviewsHavePages": true,
    "appium:nativeWebScreenshot": true,
    "appium:newCommandTimeout": 3600,
    "appium:connectHardwareKeyboard": true,
  }
```

## The Problem
I am using webdriverio with appium.

I tried attach to an existing session with `attach` function
```
  const driver = await wdio.attach({
    port: 4723,
    capabilities: opts.capabilities,
    sessionId: "9a8ef319-4543-4837-b040-7b2f8c941adf",
  });
```

All the basic functions of the driver object work fine, such as selecting an element via `$` and invoking the client method.

However, the driver object does not have commands defined in the appium protocol [on this page](https://webdriver.io/docs/api/appium).

Invoking methods dedicated to appium such as `isLocked` will trigger an error like `driver.isLocked is not a function` 

## The Debugging Log
I have performed some investigation on this problem, here is my debugging log.

1. break at [`attach function`](https://github.com/CNLHC/webdriverio/blob/e0218987be31b073650473f421675b91b6c18359/packages/webdriverio/src/index.ts#L93) and find the `params` is 

```
{
  port: 4723,
  capabilities: {
    platformName: "Android",
    platformVersion: "12",
    automationName: "uiautomator2",
    "appium:noReset": true,
    "appium:appPackage": "*",
    "appium:appActivity": "*",
    "appium:ensureWebviewsHavePages": true,
    "appium:nativeWebScreenshot": true,
    "appium:newCommandTimeout": 3600,
    "appium:connectHardwareKeyboard": true,
  },
  sessionId: "9a8ef319-4543-4837-b040-*****",
  hostname: "127.0.0.1",
  protocol: "http",
  path: "/",
  requestedCapabilities: undefined,
}
```

2. break at [line](https://github.com/CNLHC/webdriverio/blob/e0218987be31b073650473f421675b91b6c18359/packages/webdriverio/src/index.ts#L96) that before invoking attachToSession. the `automationProtocol` is `webdriver` which i think is expected.

3. break at [line](https://github.com/CNLHC/webdriverio/blob/f3f6d45be0126df49d40adc8de7ea77bed39bd2d/packages/webdriver/src/index.ts#L100) in attachToSession before invoking `getPrototype`. here the option variable is identical to the `params` posted above.

4. break at [line](https://github.com/CNLHC/webdriverio/blob/b58aa2334c45a06b2193b2f255ef6bf4600aa574/packages/webdriver/src/utils.ts#L190) in the `getPrototype`. It is obvious that this function needs the `isMobile` to be true to merge appium commands into the driver prototype. But so far the `isMobile` has not been set yet.

## My Solution

I have submitted a PR to solve this problem  in https://github.com/webdriverio/webdriverio/pull/9259

### What is your expected behavior?

The appium should work with webdriverio

### How to reproduce the bug.

mentioned in the previous section

### Relevant log output

```typescript
mentioned in the previous section
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for raising the issue.

My suggestion here:
- add `const environment = sessionEnvironmentDetector({ capabilities, requestedCapabilities })` to the `attachToSession` method to determine the environment based on the capabilities provided
- enhance the [`isMobile`](https://github.com/webdriverio/webdriverio/blob/06a65895589a3bfc98a68f617cafe2a133bdd484/packages/wdio-utils/src/envDetector.ts#L96) detector to also check for w3c valid Appium caps, e.g. `automationName` (deprecated) as well as `appium:automationName` (valid)

What do you think?

**Comment by CNLHC** [comment]
> 

Hello

The first suggestion was already proposed in the PR https://github.com/webdriverio/webdriverio/pull/9259 but you just closed it. I guess it is because of the use of deprecated `automationName`?

`sessionEnvironmentDetector` only accepts `Capabilities.DesiredCapabilities` while the attaching input is a union type `Capabilities.DesiredCapabilities | Capabilities.W3CCapabilities`. That is why the PR uses `automationName` to narrow down the type and eliminate the type error issued by the typescript.

I will try to enhance the sessionEnvironmentDetector to make it accept `W3CCapabilities` too

**Comment by christian-bromann** [comment]
@CNLHC you can also just check if `alwaysMatch` is given as property and transform the `W3CCapabilities` into `Capabilities`.

**Comment by CNLHC** [comment]
Thanks for your suggestion. I have used this method to submit another PR https://github.com/webdriverio/webdriverio/pull/9261, would you please review the code? @christian-bromann
