### ISSUE TITLE
[🐛 Bug]: npm wdio init . creates package.json and package-lock.json in parent folder

### ISSUE THREAD

**Issue by darkartswizard** [webdriverio/webdriverio#9285]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v8

### Node.js Version

16.13.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
n/a
```

### What happened?

![image](https://user-images.githubusercontent.com/50789857/205246910-ff0138b9-406f-47a6-9677-9dbe86f46d78.png)

create a new project folder and navigate to it.
In this case my test repo dir is \repos\v8-yes

qtpmgrossman@MSI MINGW64 /d/repos/v8-yes$ npm init wdio .

creates package.json and package-lock.json in parent \repos

### What is your expected behavior?

creates package.json and package-lock.json in \repos\v8-yes

### How to reproduce the bug.

create a new project folder and navigate to it in VS Code bash or external PowerShell.
In this case the test repo dir is \repos\v8-yes

Execute command
npm init wdio .

creates package.json and package-lock.json in parent \repos

WDIO Configuration Wizard says
? A project was detected at "D:\repos", correct? (Y/n)

### Relevant log output

```typescript
0 verbose cli [
0 verbose cli   'D:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'init',
0 verbose cli   'wdio',
0 verbose cli   '.'
0 verbose cli ]
1 info using npm@8.1.0
2 info using node@v16.13.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:D:\Users\qtpmgrossman\AppData\Roaming\nvm\v16.13.0\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:D:\repos\.npmrc Completed in 1ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:C:\Users\qtpmgrossman\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:D:\Program Files\nodejs\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 2ms
18 timing config:load Completed in 13ms
19 timing npm:load:configload Completed in 13ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 1ms
22 timing config:load:flatten Completed in 3ms
23 timing npm:load:cleanupLog Completed in 2ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 2ms
26 timing npm:load Completed in 23ms
27 http fetch GET 200 https://registry.npmjs.org/create-wdio 444ms (cache revalidated)
28 timing arborist:ctor Completed in 0ms
29 timing arborist:ctor Completed in 0ms
30 timing arborist:ctor Completed in 0ms
31 timing command:init Completed in 64234ms
32 verbose stack Error: command failed
32 verbose stack     at ChildProcess.<anonymous> (D:\Users\qtpmgrossman\AppData\Roaming\nvm\v16.13.0\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
32 verbose stack     at ChildProcess.emit (node:events:390:28)
32 verbose stack     at maybeClose (node:internal/child_process:1064:16)
32 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
33 verbose cwd D:\repos\v8-yes
34 verbose Windows_NT 10.0.19045
35 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "init" "wdio" "."
36 verbose node v16.13.0
37 verbose npm  v8.1.0
38 error code 1
39 error path D:\repos\v8-yes
40 error command failed
41 error command C:\WINDOWS\system32\cmd.exe /d /s /c create-wdio "."
42 verbose exit 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for raising the issue.

This is the expected "new" behavior. WebdriverIO checks for an existing `package.json` in the directory tree to find some information about the project (e.g. whether it is a CJS or ESM project). If you have a `package.json` in the parent directory it is seen as the root directory of your project. Is the root `package.json` intentional?

**Comment by darkartswizard** [comment]
Is the root package.json intentional?
No. I did not put it there.
I keep deleting it and the npm init wdio . keeps recreating it in the parent folder and then says it found the project asking if that is the project path I want to use.

**Comment by christian-bromann** [comment]
Can you verify:

- you are in `/d/repos/v8-yes`
- there is no `package.json` in `/d/repos`
- you call `npm init wdio .`
- a `package.json` is created in `/d/repos/v8-yes`

**Comment by darkartswizard** [comment]
Watch me replicate the issue in under 2 minutes.
https://www.youtube.com/watch?v=zBVaun92qFY

**Comment by christian-bromann** [comment]
Sorry Paul but still no luck:

![test](https://user-images.githubusercontent.com/731337/205837429-fdde8b84-5536-4b1e-854e-5714550bd168.gif)

My last hunch here is that you might use an outdated version of `create-wdio` here. Can you try `npm init wdio@latest .`?

**Comment by darkartswizard** [comment]
I went to my Mac to test the jasmine-boilerplate 
The project complained about the missing configuration path being a duplicate of the actual path: "/Users/macuser/Desktop/repos/jasmine-boilerplate"
"/Users/macuser/Desktop/repos/jasmine-boilerplate/Users/macuser/Desktop/repos/jasmine-boilerplate/wdio.conf.js"

```
macuser@Macs-iMac jasmine-boilerplate % npm run wdio

> jasmine-boilerplate@1.0.0 wdio
> node --loader ts-node/esm ./node_modules/.bin/wdio

(node:30342) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
? Error: Could not execute "run" due to missing configuration, file 
"/Users/macuser/Desktop/repos/jasmine-boilerplate/Users/macuser/Desktop/repos/jasmine-boilerplate/wdio.conf.js" not found! Would you like to create one? (y/N) 
```

**Comment by darkartswizard** [comment]
> Can you try npm init wdio@latest .?

Deleted the package files from root.
Same result:

```
PS D:\repos\v8-yes> npm init wdio@latest .
...
Installing @wdio/cli to initialize project...
✔ Success!
Debugger listening on ws://127.0.0.1:51943/69f2e899-169b-4ab6-9872-dea9106c22c0

For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Debugger listening on ws://127.0.0.1:51948/4e6416d0-9a6d-4b31-8b79-1ca78cfdb6d8

For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

===============================
🤖 WDIO Configuration Wizard 🧙
===============================

? A project was detected at "D:\repos", correct? (Y/n)
```

**Comment by christian-bromann** [comment]
> I went to my Mac to test the jasmine-boilerplate

That is a different error that I just fixed. Jasmine was still using a workaround that wasn't needed anymore.

> Same result:

I am not sure what else could it be.

**Comment by christian-bromann** [comment]
@darkartswizard is there anything we can do to make this issue reproducible. If not, I am not sure what to do with this issue at this point.

**Comment by darkartswizard** [comment]
Good news: I can confirm this is no longer reproducible on my Windows box.
Also not an issue on my Mac.

Please close the ticket.
