### ISSUE TITLE
[🐛 Bug]: Upgrade TypeScript v7 project to V8 with ncu breaks Expect connection

### ISSUE THREAD

**Issue by darkartswizard** [webdriverio/webdriverio#9286]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.0

### Node.js Version

16.13.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
n/a
```

### What happened?

Ran ncu mode-check-updates on V7 existing TypeScript project.

```
qtpmgrossman@MSI MINGW64 /d/repos/Test-Automation-with-WebdriverIO
$ ncu -u
Upgrading D:\repos\Test-Automation-with-WebdriverIO\package.json
[====================] 13/13 100%

 @wdio/allure-reporter    ^7.26.0  →  ^8.0.0
 @wdio/cli                ^7.27.0  →  ^8.0.2
 @wdio/jasmine-framework  ^7.26.0  →  ^8.0.2
 @wdio/local-runner       ^7.27.0  →  ^8.0.3
 @wdio/mocha-framework    ^7.26.0  →  ^8.0.2
 @wdio/spec-reporter      ^7.26.0  →  ^8.0.0
 expect-webdriverio        ^3.0.0  →  ^4.0.1

Run npm install to install new versions.
```
After npm install 

toBeExisting and toHaveTextContaining have red underlines

await expect(SecurePage.flashAlert).toBeExisting();
await expect(SecurePage.flashAlert).toHaveTextContaining('You logged into a secure area!');

generates

Property 'toBeExisting' does not exist on type 'Matchers<ChainablePromiseElement<Element>>'.
Property 'toHaveTextContaining' does not exist on type 'Matchers<ChainablePromiseElement<Element>>'.

### What is your expected behavior?

Sample TypeScript script should still pass

await expect(SecurePage.flashAlert).toBeExisting();
await expect(SecurePage.flashAlert).toHaveTextContaining('You logged into a secure area!');

### How to reproduce the bug.

To reproduce:

Take known good V7 TypeScript project.
Run ncu to update versions

Rerun example.e2e.ts script

```
import LoginPage from '../pageobjects/login.page';
import SecurePage from '../pageobjects/secure.page';

describe('My Login application', () => {
    it('should login with valid credentials', async () => {
        await LoginPage.open();

        await LoginPage.login('tomsmith', 'SuperSecretPassword!');
        await expect(SecurePage.flashAlert).toBeExisting();
        await expect(SecurePage.flashAlert).toHaveTextContaining(
            'You logged into a secure area!');
    });
});
```
![image](https://user-images.githubusercontent.com/50789857/205251760-35630857-2a6f-4651-b84a-1a1b8fdbf6ae.png)

### Relevant log output

```typescript
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment]
Can confirm this, I had it at some point during beta testing but later on could no longer reproduce it.

**Comment by christian-bromann** [comment]
@darkartswizard we mentioned in the release post that one required step for TypeScript project is to update the `types` property in `tsconfig.json` to include `@wdio/globals/types`, do you have that set?

**Comment by darkartswizard** [comment]
That's buried pretty deep. 
If it had worked, I'd recommend a adding a section on TypeScript install changes like this in the Getting Started page.
 
However I still have the same issue. 
I updated the tsconfig.json and restarted Code but Expect is still broke.

Here is my tsconfig.json:

```
{
    "compilerOptions": {
        "moduleResolution": "node",
        "types": [
            "jasmine",
            "node",
            "@wdio/jasmine-framework",
            "@wdio/globals/types",
            "expect-webdriverio"
        ],
        "target": "es2019"
    }
}
```

Anything missing?

**Comment by darkartswizard** [comment]
Got it! It's an order issue.  Putting **"@wdio/globals/types",** at the top resolved the issue.
Still recommend documenting this in a Getting Started for TypeScript section. 

{
    "compilerOptions": {
        "moduleResolution": "node",
        "types": [
            "@wdio/globals/types",
           "jasmine",
            "node",
            "@wdio/jasmine-framework",
            "expect-webdriverio"
        ],
        "target": "es2019"
    }
}

**Comment by christian-bromann** [comment]
> It's an order issue.

Interesting. Yeah with Jasmine the types for expect clash, that is why we recommend to implicitly import `expect` from `@wdio/globals` in v8 to avoid this confusion.

> Still recommend documenting this in a Getting Started for TypeScript section.

There is no TypeScript section in the getting started guide. I think the best place would be our [TypeScript docs](https://webdriver.io/docs/typescript). What do you think?

**Comment by darkartswizard** [comment]
> I think the best place would be our [TypeScript docs](https://webdriver.io/docs/typescript).
Sounds even better. 

> There is no TypeScript section in the getting started guide.
True. Since TypeScript is a supported language, a link to the TypeScript Setup page right from the Getting Started page would give a bit more visibility to new users. It's a great feature but rather hidden since the TypeScript Setup is by default hidden under Configuration. 

Other that that we can close this ticket.

**Comment by christian-bromann** [comment]
@darkartswizard please make suggestions for these comments by doing edits directly to our docs and raise a PR. Let me know if it is unclear how to do that, happy to help.

**Comment by vivacenontroppo** [comment]
This issue is still present in some Boilerplate codes you promote. Even more, they have tricks like @ts-expect-error included for this reason. E.g. https://github.com/webdriverio/jasmine-boilerplate/blob/main/wdio.local.conf.ts

**Comment by christian-bromann** [comment]
@vivacenontroppo thanks for letting us know, contributions with fixes are welcome 😉
