### ISSUE TITLE
[🐛 Bug]: npm init wdio . --yes  does not automatically enter Default for Config Wizard Questions

### ISSUE THREAD

**Issue by darkartswizard** [webdriverio/webdriverio#9287]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.0

### Node.js Version

16.13.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
n/a
```

### What happened?

```
npm init wdio . --yes

? A project named "wdio" was detected at "D:\repos\Test-Automation-with-WebdriverIO", correct? Yes
? Where should your tests be launched? local - for e2e testing of web and mobile applications
? Where is your automation backend located? On my local machine
? Which framework do you want to use? Mocha (https://mochajs.org/)
? Do you want to use a compiler? TypeScript (https://www.typescriptlang.org/)
? Do you want WebdriverIO to autogenerate some test files? Yes
? Where should these files be located? D:\repos\Test-Automation-with-WebdriverIO\test\specs\**\*.ts
? Do you want to use page objects (https://martinfowler.com/bliki/PageObject.html)? Yes
? Where are your page objects located? D:\repos\Test-Automation-with-WebdriverIO\test\pageobjects\**\*.ts
? Which reporter do you want to use? spec
? Do you want to add a plugin to your test setup?
? Do you want to add a service to your test setup? chromedriver
? What is the base url? http://localhost    
? Do you want me to run `npm install` (Y/n) 
```

Does not pick a default set up which will use Mocha with Chrome using the [Page Object](https://martinfowler.com/bliki/PageObject.html) pattern.

### What is your expected behavior?

All config questions are given default values.

### How to reproduce the bug.

Create a new folder and navigate. Init wdio by passing --yes 
npm init wdio . --yes 

```
$ npm init wdio . --yes
...
Installing @wdio/cli to initialize project...
✔ Success!

===============================
🤖 WDIO Configuration Wizard 🧙
===============================

? A project named "wdio" was detected at "D:\repos\Test-Automation-with-WebdriverIO", correct?
```

All questions are asked, none skipped with default.

### Relevant log output

```typescript
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

Seems like the parameter is not recognised. The best place to start looking would be [here](https://github.com/webdriverio/webdriverio/blob/13cd692fafcb6ae80309b50d2490201de92a7c5f/packages/wdio-cli/src/commands/config.ts#L50)

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by christian-bromann** [comment]
Ok, looked into this and it appears that NPM recognises `--yes` as an NPM parameter and not as an `create-wdio` parameter which is very confusing but I remember this difference with yarn where something like `yarn create wdio ./test --yes` actually would work. So in order to attach parameter to the right process one would need to run:

```sh
npm init wdio ./test -- --yes
```

**Comment by darkartswizard** [comment]
Opening new ticket to update documentation.
Assume new users can infer "--yes" implies "-- --yes"
Provide a concrete example like the ones above.

npm init wdio . -- --yes
