### ISSUE TITLE
[💡 Feature]: Do not include uploaded image from suite

### ISSUE THREAD

**Issue by mayankshukla94** [webdriverio/webdriverio#9290]
### Is your feature request related to a problem?

When uploading a large image (`> 50 MB`), the image is included in the `suite` data structure. This yields to larger `suite` object. When this suite is used by other packages such as `wdio-html-nice-reporter`, it causes issues due to its large size. 

For example, `wdio-html-nice-reporter` uses this suite object to generate the report by encoding it using `JSON.stringify`. This fails with error such as `Invalid string length`. Please refer https://github.com/rpii/wdio-html-reporter/issues/64 for more info.

![image](https://user-images.githubusercontent.com/40030809/205309192-dfd9d62b-1a34-42d6-91ed-636c0f442498.png)

### Describe the solution you'd like.

An option to exclude uploaded image from the `suite` data structure can help to avoid this error.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
> When uploading a large image (`> 50 MB`)

Why is this image so large? Are you using the image comparison service and test on a large site?

> An option to exclude uploaded image from the `suite` data structure can help to avoid this error.

This option should live in the `wdio-html-nice-reporter` right?

**Comment by mayankshukla94** [comment]
> Why is this image so large? Are you using the image comparison service and test on a large site?

I'm trying to test an image size upload limit

> This option should live in the wdio-html-nice-reporter right?

`suite` object is passed via `wdio` to the `reporter` and it encodes it using `json`, if we can avoid passing it?

**Comment by christian-bromann** [comment]
> if we can avoid passing it?

Sure - but again, this should be fixed within the html reporter.

I am not sure if it makes sense to add a general option about this, given this is very specific to the HTML reporter. Therefor I suggest to raise an issue and make all necessary changes in `rpii/wdio-html-reporter`. Let me know if you have other suggestions. Closing.
