### ISSUE TITLE
Mapping Desired Capabilities to BrowserStack

### ISSUE THREAD

**Issue by dtothefp** [webdriverio/webdriverio#930]
I'm using webdriverio for local testing with selenium-standalone and remote testing with BrowserStack. I'm also spawning child processes and running `wdio` binary to run tests in parallel.  Everything works great locally but I'm confused how the capabilites I specify in wdio config map to what is getting sent to BrowserStack. Specifically I'm confused about `browserName` and how to make this work with mobile device capabilities in BrowserStack.

https://www.browserstack.com/automate/capabilities

If I log out the `desiredCapabilities` in `webdriverio.js` the following works:

```js
{ browserName: 'iPhone',
  version: '',
  javascriptEnabled: true,
  locationContextEnabled: true,
  handlesAlerts: true,
  rotatable: true,
  platform: 'ANY',
  'browserstack.local': 'true',
  'browserstack.debug': 'true',
  project: '@hfa/frontend-boilerplate',
  build: '0.1.0',
  name: 'e2e',
  loggingPrefs: { browser: 'ALL', driver: 'ALL' } }
```

but if I try to be more precise as I do with the `karma-browserstack-launcher` it will not work 

```js
  {
    browserName: 'iPhone 6',
    os: 'ios',
    os_version: '8.3'
  },

//desired caps
browserName: 'iPhone 6',
  version: '',
  javascriptEnabled: true,
  locationContextEnabled: true,
  handlesAlerts: true,
  rotatable: true,
  platform: 'ANY',
  os: 'ios',
  os_version: '8.3',
  'browserstack.local': 'true',
  'browserstack.debug': 'true',
  project: '@hfa/frontend-boilerplate',
  build: '0.1.0',
  name: 'e2e',
  loggingPrefs: { browser: 'ALL', driver: 'ALL' } }
```

```sh
ERROR: Error: OS and OS Version not supported.
```

I'm generally confused at how to get the properties to map to BrowserStack in the way that I want. With https://github.com/karma-runner/karma-browserstack-launcher/blob/master/index.js my settings would look something like below

```js
{ os: 'ios',
  os_version: '8.3',
  device: 'iPhone 6',
  browser: undefined,
  tunnelIdentifier: 'karma0.4834306400734931',
  browser_version: 'latest',
  url: 'http://localhost:9876/?id=48667633',
  'browserstack.tunnel': true,
  timeout: 300,
  project: '0.1.0',
  name: 'Karma test',
  build: '@hfa/frontend-boilerplate' }
09 12 2015 16:01:48.534:INFO [launcher]: Starting browser Samsung Galaxy S5 (android 4.4) on BrowserStack
{ os: 'android',
  os_version: '4.4',
  device: 'Samsung Galaxy S5',
  browser: undefined,
  tunnelIdentifier: 'karma0.4834306400734931',
  browser_version: 'latest',
  url: 'http://localhost:9876/?id=68164477',
  'browserstack.tunnel': true,
  timeout: 300,
  project: '0.1.0',
  name: 'Karma test',
  build: '@hfa/frontend-boilerplate' }
```
Any info you could offer would be great

**Comment by akhillb** [comment]
For selenium testing on mobile devices on BrowserStack, you shouldn't be using `os` and `os_version`. You have to use `device` capability. Do not confuse it with `karma-browserstack-launcher`'s configuration, since it is not used for selenium testing and uses the Automate API. If you are still confused, [check this link to see how to write your desired capabilities](https://www.browserstack.com/automate/node#setting-os-and-browser)

**Comment by christian-bromann** [comment]
Thanks for answering this question @akhillb
