### ISSUE TITLE
[💡 Feature]: add ability to change ws endpoint via options in `getPuppeteer` method

### ISSUE THREAD

**Issue by DudaGod** [webdriverio/webdriverio#9323]
### Is your feature request related to a problem?

In our company we have some tool like selenoid which returns browser sessions on user requests. We also provide users ability to connect to browsers using CDP with url like - `ws://some-host.com/wd/v1/quotas/quota_name/devtools`. But the current implementation of `getPuppeteer` - https://github.com/webdriverio/webdriverio/blob/ac07a398bce33ca46321267141901cc0a500ec18/packages/webdriverio/src/commands/browser/getPuppeteer.ts is tied to the tools like: selenium4, selenoid/moon, ...

Why can't we have a general solution? For example, let the user specify the ws url on which they want to connect to the browser. Perhaps you don’t want to give users such an opportunity because the browser itself must return the URL by which it receives ws requests to attach to browser via CDP (like selenium4 do it). Maybe capability `se:cdp` is an official protocol that all tools that provide access to browsers must support?

### Describe the solution you'd like.

Add option `devtoolsBaseUrl` in which I can specify my url like - `ws://some-host.com/wd/v1/quotas/quota_name/devtools`.

### Describe alternatives you've considered.

All tools that provide access to browsers must return `se:cdp` capability because it is official standart, but I didn't find info about it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BorisOsipov** [comment]
>Why can't we have a general solution? For example, let the user specify the ws url on which they want to connect to the browser.

Because wdio build-in or custom services have known nothing about your custom `ws://some-host.com/wd/v1/quotas/quota_name/devtools` url and use `getPuppeteer` without args to get access to CDP.

**Comment by christian-bromann** [comment]
> we have some tool like selenoid

What tool is it?

> Add option `devtoolsBaseUrl` in which I can specify my url like - `ws://some-host.com/wd/v1/quotas/quota_name/devtools`.

This will only work if you know the url in advance which in most cases is not the case. How would this work with parallel browser?

> Why can't we have a general solution?

There is: the WebDriver bidi protocol defines a `webSocketUrl` capability that allows browser to connect to. This of course doesn't work for Devtools. Whatever you use can just mock a chromeOptions debugger endpoint to make it so WebdriverIO can connect. That said, a general solution is difficult given there is no standard for it. I am not sure if introducing an option make sense given we don't know much about this tool.

So there are 2 options here: either your tool is more compliant to the rest of the tools or it creates a service that simplifies the integration for it with WebdriverIO given it is different than current tooling.

Closing but happy to continue the discussion.

**Comment by christian-bromann** [comment]
> At the moment it looks like it's easier for me to support `se:cdp` capability than writing a separate service for inner tool.

That will do it!
