### ISSUE TITLE
[🐛 Bug]: Docs Website is broken

### ISSUE THREAD

**Issue by ayush547** [webdriverio/webdriverio#9333]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

-

### Node.js Version

-

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
-
```

### What happened?

Bugs -
1. Some doc pages are broken
2. "resetApp" link is broken

Some doc pages are broken - [Browser Object Page](https://webdriver.io/docs/browserobject/) / [CLI Options](https://webdriver.io/docs/clioptions/)
This page does exist on the repo and shows up on both internal and external search results.

Navigating to the link directly leads to - ![image](https://user-images.githubusercontent.com/49569838/205879911-bd71ba58-91a6-4862-a673-57c5a1fbbfc8.png)

While going through internal website search -
![image](https://user-images.githubusercontent.com/49569838/205880569-bbc27114-a42c-41b6-97e7-3154777e26a2.png)
Takes us to -
![image](https://user-images.githubusercontent.com/49569838/205880592-3d52226d-1e5c-405c-a32f-17b3c516ab66.png)

Also "resetApp" exists in search results,
![image](https://user-images.githubusercontent.com/49569838/205888560-3d717e8c-b790-4d84-b596-bde059be2838.png)
But navigating to it leads to -
![image](https://user-images.githubusercontent.com/49569838/205888665-627a2fcc-8601-4c17-ab77-e44227a4e7fe.png)

### What is your expected behavior?

Appropriate pages open up

### How to reproduce the bug.

Steps mentioned in description.

### Relevant log output

```typescript
-
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
It seems that the redirects don't quite work due to the fact the click comes from the Algolia widget. I reached out to them to re-access the account and re-index the page.
