### ISSUE TITLE
[🐛 Bug]: Error - SeleniumStandalone.start is not a function

### ISSUE THREAD

**Issue by Diazole** [webdriverio/webdriverio#9338]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.0.7

### Node.js Version

16.18.1

### Mode

Standalone Mode

### What happened?

https://github.com/webdriverio/webdriverio/blob/v8.0.7/packages/wdio-selenium-standalone-service/src/launcher.ts#L9
```
import * as SeleniumStandalone from 'selenium-standalone';
console.log(SeleniumStandalone);
```

produces:

```
[Module: null prototype] {
  default: { install: [AsyncFunction: install], start: [AsyncFunction: start] },
  install: [AsyncFunction: install]
}
```

I think `import * as SeleniumStandalone from 'selenium-standalone';` needs to be `import SeleniumStandalone from 'selenium-standalone';`?

I'm not sure why `install` is exported but `start` isn't as they are both named exports - https://github.com/webdriverio/selenium-standalone/blob/v8.2.4/index.js#L3

### What is your expected behavior?

`SeleniumStandalone.start({ drivers: { firefox: {} } });` should call the exported start func.

### How to reproduce the bug.

```
import * as SeleniumStandalone from 'selenium-standalone';
SeleniumStandalone.start({ drivers: { firefox: {} } });
```

### Relevant log output

```typescript
2022-12-06T11:22:07.253Z DEBUG @wdio/utils:initialiseServices: initialise service "selenium-standalone" as NPM package
2022-12-06T11:22:07.253Z INFO @wdio/cli:launcher: Run onPrepare hook
2022-12-06T11:22:07.766Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
TypeError: SeleniumStandalone.start is not a function
    at SeleniumStandaloneLauncher.onPrepare (file:///.../@wdio/selenium-standalone-service/build/launcher.js:92:42)
    at async file:///.../@wdio/cli/build/utils.js:42:17
    at async Promise.all (index 0)
    at async Launcher.run (file:///.../@wdio/cli/build/launcher.js:82:13)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for this fix!
