### ISSUE TITLE
[🐛 Bug]: devtools-service cdp is not working

### ISSUE THREAD

**Issue by iuanee** [webdriverio/webdriverio#9348]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.0.8

### Node.js Version

16

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
  maxInstances: 5,
  browserName: 'chrome',
  acceptInsecureCerts: true
}
```

### What happened?

 i was using devtools-service cdp service with the code below. this code print out 'request sent: url - ${url} in v7 but not v8. can you please help taking a look? sample code is found here: v7 - https://github.com/iuanee/sandbox-v7 ; v8 - https://github.com/iuanee/sandbox-v8
class EventValidator {

enableCDP() {
  browser.cdp('Network', 'enable');
}

addEventListener() {
  browser.on('Network.requestWillBeSent', (params) => {
  const { url } = params.request;
  console.log(request sent: url - ${url});
});
}

}

### What is your expected behavior?

print out the following: 
request sent: url - ${url}

### How to reproduce the bug.

git clone the following repo:
- https://github.com/iuanee/sandbox-v8

run npm install
run yarn wdio --spec test/specs/example.e2e.js

### Relevant log output

```typescript
it should print out the following: 
request sent: url - ${url}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

Hard to say if this is related to the WebdriverIO or Puppeteer update. I would not recommend to use the `cdp` command anymore at this point given you have access to the puppeteer instance today through the `getPuppeteer` command.

Any investigations / contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by dragosMC91** [comment]
Maybe this info will help narrow down the hunt for the issue:

I noticed that `browser.on` commands are not working anymore and `only` these commands for example:
- Network.loadingFinished
- Network.requestWillBeSent

The `browser.cdp` on the other hand works fine as before (tested in my repo) for example:
- browser.cdp('Network', 'getRequestPostData', {...})
- browser.cdp('Network', 'getResponseBody', {...})
- browser.cdp('Emulation', 'setScrollbarsHidden', { ... })
- browser.cdp('Emulation', 'setGeolocationOverride', { ... })

@christian-bromann you said to use `devtools` through `puppeteer` which I tested and works fine, but does this mean the separate `devtools` service is now redundant? Is there any argument to keep using devtools and not just switch to puppeteer entirely ?

**Comment by christian-bromann** [comment]
> but does this mean the separate `devtools` service is now redundant? Is there any argument to keep using devtools and not just switch to puppeteer entirely ?

For doing work on the Chrome DevTools protocol I would not use the devtools service anymore, as Puppeteer gives you all what you need.
