### ISSUE TITLE
Change reporterOptions to be per-reporter

### ISSUE THREAD

**Issue by georgecrawford** [webdriverio/webdriverio#935]
I propose that `reporterOptions` is likely to get unwieldy with multiple reporters, as you may want the same key name (e.g. `outputDir`) to be set with different values depending on the reporter. We could continue to support this in a backwards-compatible way, but also support a new format:
```js
reporterOptions: {
    allure: {
        outputDir: 'blah-allure'
    },
    junit: {
        outputDir: 'blah-junit'
    }
}
```

**Comment by georgecrawford** [comment]
If @christian-bromann agrees, I'll implement this.

**Comment by georgecrawford** [comment]
Any keys which are already in `reporter` could be set on just that reporter, and all others are set on *every* reporter, eg:
```js
reporterOptions: {
    mysetting: 'asd',
    allure: {
        outputDir: 'blah-allure'
    },
    junit: {
        outputDir: 'blah-junit'
    }
}
```
gives:
```
allure: {mysetting: 'asd', outputDir: 'blah-allure'}
junit: {mysetting: 'asd', outputDir: 'blah-junit'}
```

**Comment by christian-bromann** [comment]
:+1:

**Comment by christian-bromann** [comment]
Closing, let's continue conversation to #936
