### ISSUE TITLE
multiple browsers - not in parallel

### ISSUE THREAD

**Issue by dangasaur** [webdriverio/webdriverio#938]
I developed a load driver using selenium-webdriver that opens multiple instances of chrome/firefox/phantom and runs independent chains of actions on each instance.  I would like to port this to webdriver.io because of better promise support but I'm stuck at de-serializing the browsers.

For example:
```
let browserArray = [];
let bCount = 5;
for (let i = 0; i < bCount; i++) {
	let browser = webdriverio.remote(options)
		.init()
		.url('http://www.google.com')
		.getTitle().then((title) => console.log('title #' + i++ + ' is: ' + title))
		.end();
	browserArray.push(browser);
}

Q.all(actions).then(() => {
	console.log('all done')
});
```
The above code will only spawn one browser at a time, waiting until the title is printed before spawning the next browser.

Any suggestions?

**Comment by christian-bromann** [comment]
What do you try to solve?

**Comment by dangasaur** [comment]
I would like N browsers running concurrently but each running an independent chain of actions.

**Comment by christian-bromann** [comment]
Have you checked out [multiremote](https://github.com/webdriverio/webdriverio/blob/master/examples/multiremote/webdriverio.multiremote.chat.js)?

**Comment by dangasaur** [comment]
Hmm, maybe I misunderstood the documentation for multiremote.  It looked like it was sending the same commands to different browsers but this example clearly shows otherwise.  I'll give it a shot.

**Comment by christian-bromann** [comment]
You can do both: control the set of browser with the same commands but also control each one individually

**Comment by dangasaur** [comment]
Working for me.  Thanks Christian.

**Comment by christian-bromann** [comment]
Awesome!
