### ISSUE TITLE
Run multiple remotes concurrently

### ISSUE THREAD

**Issue by SwinX** [webdriverio/webdriverio#940]
Hi! I understand this might be a bit duplicate, but I will fire issue anyway.
What I'm trying to do: implement my own concurrent tests runner on top of Webdriver.io. The main idea is to have multiple remotes (3 for instance) for each browser and pass this remotes to mocha tests, where actual commands will be executed.

When I'm using multiple remotes (i.e. `webdriverio.remote(config)`) for single browser (`chrome` for instance) - everything goes OK, tests are being executed.
If I'm adding 2nd browser (`firefox`) - then results starting to become strange. I see from mocha debug log output that for firefox tests are not executed and from webdriver log, that session is being started and stopped immediately.

Please advice where should I look. Not attaching anything to the issue because not sure what is needed for investigation.

**Comment by christian-bromann** [comment]
Why don't you try the wdio testrunner?

**Comment by SwinX** [comment]
@christian-bromann thank you for quick response!

We did examine wdio testrunner, but decided to go with our own one. We need more control about run process, some feature like retries which probably you will never want to implement, etc.
BTW seems like my issue was never related to webdriver.io. If my suspicions will turn into confidence I will close this issue.

**Comment by SwinX** [comment]
Confirm that issue was not related to `webdriver.io`.
As a conclusion - if you want to use several instances of `webdriver.io`, you just need to start multiple clients and all will go well.

**Comment by christian-bromann** [comment]
What kind of control do you need here? Btw. we will implement a flake retry sequence within the next version. Additionally we have a lot is open source work going on for integrating more frameworks, reporter and services.
