### ISSUE TITLE
[🐛 Bug]: 'npm init wdio' command is choosing chromedriver option irrespective of user input in services selection

### ISSUE THREAD

**Issue by vjuturu** [webdriverio/webdriverio#9400]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.0.13

### Node.js Version

16.13.2

### Mode

WDIO Testrunner

### What happened?

1. Enter 'npm init wdio@latest ./' and continue with the setup
2. when services selection showed up with the following question -- 'Do you want to add a service to your test setup?' , select any other options like 'geckodriver' or 'appium' or 'selenium-standalone' using up or down arrow keys and click ENTER button.
3. Observe that always 'chromedriver' was displayed as selected option.
4. Please find attached screenshots which shows selenium-standalone was selected by user but after clicking ENTER button 'chromedriver' was displayed.

![User_Selected_Selenium-Standalone_Service](https://user-images.githubusercontent.com/8421048/207634838-ac46a8e5-dfc8-45b2-ad3e-65c04efda3d7.png)
![WDIO_displayed_service_ selection_as_ chromedriver](https://user-images.githubusercontent.com/8421048/207634863-c29fc688-d759-4f15-9697-f1860d6d42dc.png)

### What is your expected behavior?

services should be selected based on users input.
 'Do you want to add a service to your test setup?' If user selects 'geckodriver' or 'appium' or 'selenium-standalone' it should select respective service.

### How to reproduce the bug.

1. Enter 'npm init wdio@latest ./' and continue with the setup
2. when services selection showed up with the following question -- 'Do you want to add a service to your test setup?',  select any other options like 'geckodriver' or 'appium' or 'selenium-standalone' using up or down arrow keys and click ENTER button.
3. Observe that always 'chromedriver' was displayed as selected option.

following video shows user selected 'selenium-standalone' service but chrome driver was shown as selected option.

https://user-images.githubusercontent.com/8421048/207635530-444a0d10-167c-47c0-ae60-88e1b2a4c6d7.mov

### Relevant log output

```typescript
? Do you want to add a service to your test setup? chromedriver
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
As the comment next to the question states:
> (Press <space> to select, <a> to toggle all, <i> to invert selection, and <enter> to proceed)

You have do unselect Chromedriver and select the service you like to install with the `space` bar. This is a multi selection so you can pick multiple services.

I would lie if I say I never was confused by this either 😉
