### ISSUE TITLE
[🐛 Bug]: Key.Escape sends a unicode character to input field, instead of pressing Escape

### ISSUE THREAD

**Issue by segovia** [webdriverio/webdriverio#9401]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.0.13

### Node.js Version

16.13.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
Latest chrome on ubuntu.
```

### What happened?

On wdio v7, I had code like so:
```
await browser.$('[name=username]').setValue('user30');
await browser.keys(['Escape']);
```

After upgrading to v8, it now looks like:

```
import {Key} from 'webdriverio';

await browser.$('[name=username]').setValue('USER30');
await browser.keys([Key.Escape]);
```

When my login form submits the form values, I see that the username has actually gotten an extra unicode character at the end. The payload looks like:
`username: USER30`

### What is your expected behavior?

I expect the Escape key not to append a unicode character at the end.

### How to reproduce the bug.

See code snippets on "What happened section"

### Relevant log output

```typescript
[0-0] 2022-12-15T09:40:05.854Z INFO devtools: COMMAND elementSendKeys("ELEMENT-2", "USER30")
[0-0] 2022-12-15T09:40:05.903Z INFO devtools: RESULT null
[0-0] 2022-12-15T09:40:05.906Z INFO devtools: COMMAND performActions(<object>)
[0-0] 2022-12-15T09:40:05.931Z INFO devtools: COMMAND releaseActions()
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by jhaltrecht-rev** [comment]
@segovia did you find a workaround to this bug? I installed v8 yesterday and am experiencing the same issue of seeing unicode when using "Enter", "Tab", etc.

**Comment by christian-bromann** [comment]
I put up a PR with a fix for it.

> did you find a workaround to this bug?

@jhaltrecht-rev a workaround for a bug is not really a solution, getting involved into the project and provide bug fixes is.

**Comment by segovia** [comment]
Thanks @christian-bromann, the fix worked for me.
