### ISSUE TITLE
[🐛 Bug]: <wdio 7.28.0 isn't working for node 12,13 >

### ISSUE THREAD

**Issue by udarrr** [webdriverio/webdriverio#9425]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.28.0

### Node.js Version

12

### Mode

WDIO Testrunner

### What happened?

In 7.28.0 was changed version puppeter-core from 13.1.3 to 19.4.0 and it doesn't support node 12 currently because puppeter-core 19.4.0 only from node 14. But wdio7 should support node 12 because it was dropped only for wdio8 regarding the doc 
https://webdriver.io/blog/2022/12/01/webdriverio-v8-released

### How to reproduce the bug.

Start 7.28.0 on node 12

### Relevant log output

```typescript
-
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
I would not recommend to use Nodejs v12 anymore. Are there any issues updating to a newer NodeJS version?

**Comment by udarrr** [comment]
Agree but for some reason somewhere still exist node12. If for wdio7 since 7.28 no way support node 12,13 im my opinion it shoud be included in doc like breaking changes.

**Comment by christian-bromann** [comment]
@udarrr you are right. I reverted the change and will release a new v7 version.

**Comment by udarrr** [comment]
resolved in 7.28.1

**Comment by christian-bromann** [comment]
Thanks for confirming!
