### ISSUE TITLE
ERROR @wdio/cli:launcher: No specs found to run, exiting with failure

### ISSUE THREAD

**Issue by kannanmf** [webdriverio/webdriverio#9447]
Hi,

I've upgraded from webdriverio, @wdio/cli, @wdio/*** versions from v7 to 8.0.** Since this, I got the following error message, during test execution:

**WARN @wdio/config:ConfigParser: pattern test/features/**/*.feature did not match any file
ERROR @wdio/cli:launcher: No specs found to run, exiting with failure**

**Issue is** If My wdio.conf.ts file location is under test/config/wdio.conf.ts

I can able to reproduce the same issue (move wdio.conf.ts file from root folder to another folder) with the boilerplate wdio-cucumber project using the cmd `npm init wdio .`

Please let me know, How to fix this issue?

**Comment by christian-bromann** [comment]
> Please let me know, How to fix this issue?

As mentioned in the [release blog post](https://webdriver.io/blog/2022/12/01/webdriverio-v8-released):

> Furthermore did we fix the behavior of relative spec or exclude paths. Before v8 every path within specs, exclude or --spec was always seen relative from the users working directory. This behavior was confusing especially when the wdio.conf.js was not within the root of you project. This got fixed now so that specs and exclude path will be always seen as relative to the config file and --spec arguments, relative from the working directory.

Make sure to set the path relative to the config file. For further questions please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).

**Comment by WillBrock** [comment]
> I can able to reproduce the same issue (move wdio.conf.ts file from root folder to another folder) with the boilerplate wdio-cucumber project using the cmd npm init wdio .

I was also able to reproduce the issue with a clean install from the steps in the Getting Started guide where the config file is in the same location where the command is ran. 

When running this:

```
npm init wdio .
npx wdio run ./wdio.conf.js --spec example.e2e.js
```

I get this error:
```
@wdio/cli (v8.6.5)

Error: spec file(s) /foo/bar/dev/wdio-v8-js/example.e2e.js not found
```

If I specify the full path to the file it will run.
```
npx wdio run ./wdio.conf.js --spec test/specs/example.e2e.js
```

**Comment by christian-bromann** [comment]
Thanks for verifying the bug @WillBrock , we logged this already in #9495
