### ISSUE TITLE
Add support for puppeteer-extra

### ISSUE THREAD

**Issue by thu2004** [webdriverio/webdriverio#9449]
One of the useful plugin is puppeteer-extra-plugin-stealth. It let you do test automation and web scraping without getting blocked.

https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra

You can verify the blocking with this web page. https://bot.sannysoft.com/

Some useful background links:
https://www.zenrows.com/blog/web-scraping-without-getting-blocked#how-to-configure-your-scraper-to-use-a-proxy
https://zditect.com/blog/51666706.html

**Comment by christian-bromann** [comment]
Hey,
thanks for filing the issue. This seems indeed like a useful feature. We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by harsha509** [comment]
quick update!
Still working on it!

**Comment by dore51** [comment]
Hey @harsha509, do you still work on it?

**Comment by christian-bromann** [comment]
I will go ahead and close this as no one showed interest in implement it. I think WebdriverIO is interested enhancing its feature set and some of the feature puppeteer-extra has would be good to have. However it would be nice to have support for these cross browser and leverage WebDriver Bidi as much as possible. If anyone is interested please raise another issue. Thanks.
