### ISSUE TITLE
Add option to retry failed requests

### ISSUE THREAD

**Issue by 1999** [webdriverio/webdriverio#946]
We write our tests using webdriverio. But unfortunately our selenium grid is not stable enough or we experience network problems. The problem is that webdriverio can't get SessionId for other requests and mocha tests fail after timeout.

Currently `request` library is used to send requests to SG, but it doesn't support retries (or does it?) and it would be very helpful in our case. Would you mind if I make a PR which adds this option (retries for example) and also switches to `got`, `asker` etc?

**Comment by christian-bromann** [comment]
We are open for all PRs. An optional request retry wouldn't hurt to have :wink:

**Comment by 1999** [comment]
That's nice. But what library should I replace `request` with? I like `asker`, it supports retries, but it's not quite popular.

**Comment by christian-bromann** [comment]
We should rather modify the RequestHandler to support retries than replacing the request library.

**Comment by 1999** [comment]
Okay, I'll take a closer look at this.

**Comment by christian-bromann** [comment]
let's continue our conversation in #952
