### ISSUE TITLE
Alternate for reset Appium command for WebdriverIO

### ISSUE THREAD

**Issue by sharutkarsh** [webdriverio/webdriverio#9479]
### Is your feature request related to a problem?

could not find an alternate of reset commandthe 

### Describe the solution you'd like.

Is there any other capability which performs the same function as we used to have by reset Appium command?

### Describe alternatives you've considered.

Nothing

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
It seems we removed it as part of https://github.com/webdriverio/webdriverio/pull/7002 .. I am checking in with the Appium team if this command is still suppose to be used.

**Comment by christian-bromann** [comment]
Please see https://github.com/appium/appium/issues/15807, alternatives are:

- https://webdriver.io/docs/api/appium#activateapp
- https://webdriver.io/docs/api/appium#terminateapp

**Comment by vmladenov-at-tricentis** [comment]
Hi, 
Actually it looks like it was remove in the node16 migration and I think it was removed by mistake?

**Comment by sharutkarsh** [comment]
Yeah it looks like, but not sure if they will fix it, as they have already suggested a workaround.

**Comment by christian-bromann** [comment]
The command was removed intentionally because it is a deprecated command in Appium. Please see the referenced issue above.
