### ISSUE TITLE
Incomplete API Documentation re callbaks

### ISSUE THREAD

**Issue by fireproofsocks** [webdriverio/webdriverio#948]
This is a general issue, but an important one: most of the examples in the API documentation does not detail what exactly is passed to the callback. 

For example, the getTitle().then(callback) returns a string:
```
.getTitle().then(function(title) {
    console.log(title); // outputs: "Google"
}) 
```

This can be inferred from the http://webdriver.io/api/property/getTitle.html page, but it would be better to offer a function signature including data types.

It's anyone's guess what parameters are passed to the callbacks of windowHandles(), getCurrentTabId(), etc. etc. etc... most of them require users to guess and do some unneeded busy work of logging the output. There's no reason that this info should be omitted from the API examples.  All examples should include both a function signature of the callback and an example demonstrating the output.

**Comment by christian-bromann** [comment]
Well the example states that `console.log(title);` outputs `"Google"` which definitely implies that the variable title is a string right? Could you point out the commands that are lacking information of what results are getting returned? How would think we could improve the docs?

**Comment by fireproofsocks** [comment]
Pretty much all the commands lack this basic info -- I think the getTitle callback is one of the few exceptions that proves the rule.  If you're not seeing the problematic omissions here, then it sounds like I'd better submit another pull request, even though it ends up a bit like the deaf leading the blind since a lot of this stuff I am struggling with.

**Comment by fireproofsocks** [comment]
Oh my... I started to add examples to these, but it appears you guys have painted yourselves into a corner.  Although I understand the pragmatic reason why you'd want to use doc-generators to generate documentation pages from comments in the source code it's a bad idea because education, effective adoption, and feedback suffer considerably.  Writing good docs and writing good code are two completely different skill sets, so you've immediately blocked any real feedback from users who aren't developers of a certain level.  By using documentation generators, you have broken the feedback loop.  If some master-educator wanted to contribute to the docs, you've blocked them: who can decipher how those documentation pages are generated from the source code comments?  Understanding how a documentation generator works is completely unrelated to both educating your users and to writing the source code.  It's a needless flaming hoop to jump through.   Importantly, who but a developer would even know to look in the source code to update the documentation? (READ: at a minimum your CONTRIBUTING.md file must be updated to demonstrate how users can contribute to the documentation).  I would update the CONTRIBUTING.md file myself if I had any authority to speak on how your documentation parser is working, but that really is the deaf leading the blind.  Unfortunately, I can't submit a pull request until you get the docs better organized and ready for contributions, and I would urge you to consider improving docs a priority, otherwise all your work development is wasted.

To repeat the initial omissions: 
- Every single function in the API docs needs to demonstrate its output via an example AND explicitly state the data type (e.g. string, array, object, etc).
- Include real examples that go beyond the single function so a user can understand how a function might actually be used in practice.  E.g. switchTab() doesn't get called in isolation, it's used in a chain of other commands, otherwise it doesn't make sense.  The examples need to reflect real use cases.

The amount of time wasted from these types of omissions is very measurable, and unfortunately they are not easy to remedy when you're relying on documentation generators.

**Comment by christian-bromann** [comment]
@fireproofsocks thanks for your comment, here are my 2cents

> to generate documentation pages from comments in the source code it's a bad idea because education, effective adoption, and feedback suffer considerably

I can not fully agree with that one.

> By using documentation generators, you have broken the feedback loop.

What kind of feedback loop? Since I started doing that I got many great contributions on command documentations.

> you've blocked them: who can decipher how those documentation pages are generated from the source code comments?

Did I? I don't think it is that cryptic and pretty straight forward to understand. I never was asked how this documentation works, people just submitted PRs and all of them were merged right away.

> who but a developer would even know to look in the source code to update the documentation?

Who but a developer would be even interested in changing the documentation?

I understand your frustration around this and I agree that the command documentation has to be improved. Please note that this is an open source project and fully maintained by some contributor spending their free time in improving this library. We do what we can but often documentation is lower prioritized than it should be.
Right now WebdriverIO has more than 200 commands. Using a doc generator is not just the most efficient way to keep documentation up to date but also the easiest one in terms of agreeing on one particular way of doing things. I looked around couple of other libraries and all of them do the same. I am not only generating the website documentation, I also generate a whole sublime plugin with it and more maybe in the future. I refuse to have some kind of markdown file for every command where I have to copy paste the specifics in order to apply them in a different context. I've done that too often. How else should we maintain that amount of information? All good software I can think of that provides a certain API generates its documentation out of the source code. If someone doesn't understand how he can improve the documentation in the source code comments than I am happy to do that for him if he posts the changes in an issue or emails me these. For the v4 release I will go over each command and try to add some more meaningful examples.

**Comment by fireproofsocks** [comment]
> Who but a developer would be even interested in changing the documentation?

Users.  There's a difference between noob/unfamiliar developers/QA-engineers and senior developers able to contribute to source code.

At a minimum, the CONTRIBUTING.md needs to be updated to include the syntax/procedure/locations for contributing to the docs -- without that, the feedback loop is hindered.  You can't measure how many contributions were _not_ made: it costs you nothing to be specific about this.  I understand why you're using the documentation-generators: convenience.  It's definitely not the best format for educating or soliciting feedback from users.  Again, the effectiveness of each documentation approach when it comes to onboarding/educating newcomers can (and has) been measured.  To be clear: I'm not talking about good software, I'm talking about good documentation.  There is a difference, and unfortunately, there are few standouts of quality docs even from quality software.  Get specifics into the CONTRIBUTING.md and that will open up the possibility of improved docs from the community.

**Comment by fireproofsocks** [comment]
I have submitted the following PR that includes an update to the contributing guidelines and a start on some of the examples: https://github.com/webdriverio/webdriverio/pull/964

Some of the problem here re omissions could be remedied in part by making visible the `@return` declarations in the generated documentation pages.

**Comment by fireproofsocks** [comment]
When will that PR go live (i.e. when will its changes be reflected on the webdriver.io site)?  I'm having to bookmark my repo for reference.

**Comment by christian-bromann** [comment]
Your changes are already live: http://webdriver.io/api/window/getCurrentTabId.html
I realised though that there are two contribute.md:
https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md
https://github.com/webdriverio/webdriverio/blob/master/docs/contribute.md

I will have to streamline this. I am currently working on the new website for v4. We are moving our stuff to AWS so deployments will get way easier for me and the team.

**Comment by fireproofsocks** [comment]
Ah cool.  Ok, so do we need another PR to remedy the CONTRIBUTING.md vs. docs/contribute.md files?  And how does that affect the doc generator?

**Comment by christian-bromann** [comment]
No, let's leave it as it is for now. I think I will handle that as part of the build process.

> And how does that affect the doc generator?

What do you mean by that?

**Comment by fireproofsocks** [comment]
I mean that the http://webdriver.io/contribute.html page seems to come from the docs/contribute.md and not  from the /CONTRIBUTING.md file.

**Comment by christian-bromann** [comment]
Right. I will copy that file over during the build process:

```sh
$ cp ./CONTRIBUTING.md docs/contribute.md
```

something along this line

**Comment by christian-bromann** [comment]
The hexo generator now copies the main CONTRIBUTING.md form the root directory into the markdown source (ref https://github.com/webdriverio/hexo-wdio-generator/blob/master/lib/build.js#L66) so that we only need to maintain one file. Closing.
