### ISSUE TITLE
[📖 Docs]: scrollIntoView vs. scrolltoView confusion

### ISSUE THREAD

**Issue by synedra-mpe** [webdriverio/webdriverio#9487]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Unclear documentation

### Description of the improvement / report

https://webdriver.io/docs/api/element/scrollIntoView/

Seems only `scrollIntoView()` is correct here, but docs mention missleading `scrolltoView()`, which does not exist imho.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
I don't see `scrolltoView` being mentioned anywhere in the WebdriverIO codebase. Closing but happy to re-open if you can point out where this confusion can come from.

**Comment by synedra-mpe** [comment]
oh - sorry, a browser extension on my computer was the cause.
