### ISSUE TITLE
[🐛 Bug]: Typos in sauce service readme

### ISSUE THREAD

**Issue by anselmbradford** [webdriverio/webdriverio#9491]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8

### Node.js Version

16.13.2

### Mode

Standalone Mode

### What happened?

The [sauce readme](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-sauce-service/README.md)
 has this paragraph: 

> If you want to use an existing Sauce Connect tunnel you only need to provide or the tunnelIdentifier, or if you are using a parent tunnel the parentTunnel into you capabilities like this:

### What is your expected behavior?

Should instead read something like:

> If you want to use an existing Sauce Connect tunnel you only need to provide a tunnelIdentifier, or if you are using a parent tunnel, include the parentTunnel in the capabilities like this:

### How to reproduce the bug.

Visit https://webdriver.io/docs/sauce-service/#configuration and read through the text.

### Relevant log output

```typescript
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for raising the issue. I pushed a commit with a fix. You can always, and we encourage to raise PRs with doc fixes yourself. If you have any problems doing so, let me know. Cheers!
