### ISSUE TITLE
Report pass/fail result to SauceLabs

### ISSUE THREAD

**Issue by geekdave** [webdriverio/webdriverio#95]
Currently when my tests finish running on SauceLabs, the status just changes to `Finished`, regardless of whether the tests pass or fail.

Would it be possible to communicate my test's pass/fail status to SauceLabs?

I'm using Mocha, and tearing down my tests with this code:

``` js
    after(function(done) {
        client.end(done);
    });
```

**Comment by hamishtaplin** [comment]
@christian-bromann is the after hook in each test? where does `request` come from? It doesn't appear to be an available global variable.

Also, can this be done in the config file?

**Comment by christian-bromann** [comment]
@hamishtaplin this is an old thread we now have `wdio-sauce-service` that will do the work for you

**Comment by hamishtaplin** [comment]
@christian-bromann So it is, I'm not getting pass/fail results in SauceLabs though?

**Comment by christian-bromann** [comment]
> So it is

Does this mean you run wdio testrunner with latest WebdriverIO and `wdio-sauce-service`

**Comment by hamishtaplin** [comment]
@christian-bromann yes

**Comment by christian-bromann** [comment]
Then there is an issue with the credentials or similar. Feel free to create an issue and provide an minimal reproducible example. Thanks!
