### ISSUE TITLE
Add "maxInstances" config to limit number of parallel browser instances

### ISSUE THREAD

**Issue by klamping** [webdriverio/webdriverio#950]
Implement a way to only run a specific number of instances at a time when multiple capabilities/browsers are defined. I.E. I want to have 10 different capabilities, but only run 2 in parallel at a time. This is due to parallel usage limits in Browserstack. If I go above my parallel limit, some instances timeout waiting for a session to free up.

**Comment by christian-bromann** [comment]
I improved the way we schedule things in here. You can specify maxInstances for all capabilities as well as only for certain ones.

**Comment by gerbil** [comment]
maxInstances got ignored in my conf.js for browserstack

**Comment by christian-bromann** [comment]
@gerbil what version are you using?

**Comment by gerbil** [comment]
Nevermind, i think it's a grunt-webdriver issue, not wdio itself. Just checked direct wdio call and it's working fine with browserstack + maxinstances. Thnx.
