### ISSUE TITLE
[🐛 Bug]: findElements ($$) failing while using forEach to iterate over element

### ISSUE THREAD

**Issue by testSadab** [webdriverio/webdriverio#9520]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v8 (latest)

### Node.js Version

18

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
    browserName: 'chrome'
    browserVersion: 'latest',
    platform: 'macOS'
}
```

### What happened?

I am trying to iterate over elements and print the value, when i use for loop or map code works as expected but forEach gives error out of 10 run 9 times.

Code:
```
const elements = $$("//a");
await elements.forEach(async element => console.log(await element.getText()));
```

### What is your expected behavior?

element should iterate as usual and print the value

### How to reproduce the bug.

Clone the repo:  https://github.com/testSadab/WebdriverIOMochaTS
Switch to branch: findElementsIssue

Commands:
npm install
npm run wdio

### Relevant log output

```typescript
https://github.com/testSadab/WebdriverIOMochaTS/blob/findElementsIssue/result_logs.txt
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
I checked our retry mechanism which should prevent this from happening and indeed it wasn't working anymore. Put in a fix for it.

**Comment by testSadab** [comment]
Working as expected now, much appreciated !!
