### ISSUE TITLE
[🐛 Bug]:Couldn't add script to package.json: Error: Error calling: npm pkg set scripts.wdio=wdio run ./wdio.conf.js

### ISSUE THREAD

**Issue by fypnlp1** [webdriverio/webdriverio#9529]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8

### Node.js Version

16.17.1

### Mode

Standalone Mode

### What happened?

  I am trying to install appium with webdriverIO ver 8

I answered the following questions while setting up webdriver8 configuration

===============================
🤖 WDIO Configuration Wizard 🧙
===============================

    ? Where should your tests be launched? local - for e2e testing of web and mobile applications
    ? Where is your automation backend located? On my local machine
    ? Which framework do you want to use? Mocha (https://mochajs.org/)
    ? Do you want to use a compiler? No!
    ? Do you want WebdriverIO to autogenerate some test files? No
    ? Which reporter do you want to use? spec
    ? Do you want to add a plugin to your test setup? 
    ? Do you want to add a service to your test setup? appium
    ? What is the base url? http://localhost
    ? Do you want me to run `npm install` Yes

After filling in the above I got the following: 
Documentation: https://webdriver.io
@wdio/cli (v8.1.0)

Error: ⚠️ Couldn't add script to package.json: Error: Error calling: npm pkg set scripts.wdio=wdio run ./wdio.conf.js
    at ChildProcess.<anonymous> (file:///Users/jacquelinegeorge/Documents/WebdriverIOPOC/webdriver-appium-v8/node_modules/@wdio/cli/build/utils.js:506:31)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
    at createWDIOScript (file:///Users/jacquelinegeorge/Documents/WebdriverIOPOC/webdriver-appium-v8/node_modules/@wdio/cli/build/utils.js:676:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runConfigCommand (file:///Users/jacquelinegeorge/Documents/WebdriverIOPOC/webdriver-appium-v8/node_modules/@wdio/cli/build/commands/config.js:118:5)
    at async Object.handler (file:///Users/jacquelinegeorge/Documents/WebdriverIOPOC/webdriver-appium-v8/node_modules/@wdio/cli/build/commands/config.js:126:5)

### What is your expected behavior?

I was expecting a successful installation. So I was very surprised.  

### How to reproduce the bug.

See the info in the 'what happened' box

### Relevant log output

```typescript
The log output is above in section 'what happened'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Which operating system are you using? Which command did you run to setup WebdriverIO?

**Comment by fypnlp1** [comment]
Hello.  thanks for getting back to me so quickly.    
I am using a Mac o/s 13.0.1. 
I installed with npm init wdio webdriver-appium-v8

**Comment by christian-bromann** [comment]
Have you tried:
```sh
npm init wdio@latest ./webdriver-appium-v8
```

**Comment by fypnlp1** [comment]
Let me try.  I will be right back.

**Comment by fypnlp1** [comment]
Ok:  This is is what I got : 
```
Documentation: https://webdriver.io
@wdio/cli (v8.1.0)

Error: ⚠️ Couldn't add script to package.json: Error: Error calling: npm pkg set scripts.wdio=wdio run ./wdio.conf.js
    at ChildProcess.<anonymous> (file:///Users/jacquelinegeorge/Documents/WebdriverIOPOC/webdriver-appium-v8/node_modules/@wdio/cli/build/utils.js:506:31)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
    at createWDIOScript (file:///Users/jacquelinegeorge/Documents/WebdriverIOPOC/webdriver-appium-v8/node_modules/@wdio/cli/build/utils.js:676:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runConfigCommand (file:///Users/jacquelinegeorge/Documents/WebdriverIOPOC/webdriver-appium-v8/node_modules/@wdio/cli/build/commands/config.js:118:5)
    at async Object.handler (file:///Users/jacquelinegeorge/Documents/WebdriverIOPOC/webdriver-appium-v8/node_modules/@wdio/cli/build/commands/config.js:126:5)


⚠️  Ups, something went wrong: Error calling: npx wdio config!
```

**Comment by fypnlp1** [comment]
I don't know if this helps, but I am also using node v16.17.1

**Comment by christian-bromann** [comment]
I am using MacOS and can not reproduce this with the same Node.js version.

**Comment by fypnlp1** [comment]
I am very confused right now.

**Comment by fypnlp1** [comment]
Ok, let me show you something:  [Please watch this video](https://www.dropbox.com/s/3xc3km8nxx2wx4q/Error%20on%20set%20up%20.mov?dl=0)

Display from Terminal:

```
===============================
🤖 WDIO Configuration Wizard 🧙
===============================

? Where should your tests be launched? local - for e2e testing of web and mobile applications
? Where is your automation backend located? On my local machine
? Which framework do you want to use? Mocha (https://mochajs.org/)
? Do you want to use a compiler? No!
? Do you want WebdriverIO to autogenerate some test files? No
? Which reporter do you want to use? spec
? Do you want to add a plugin to your test setup? 
? Do you want to add a service to your test setup? chromedriver, appium
? What is the base url? http://localhost
? Do you want me to run `npm install` Yes


Installing wdio packages:
- @wdio/local-runner@latest
- @wdio/mocha-framework@latest
- @wdio/spec-reporter@latest
- wdio-chromedriver-service
- @wdio/appium-service@latest
- chromedriver

> chromedriver@108.0.0 install /Users/jacquelinegeorge/Documents/WebdriverIOPOC/webdriver-appium-v8/node_modules/chromedriver
> node install.js

Current existing ChromeDriver binary is unavailable, proceeding with download and extraction.
Downloading from file:  https://chromedriver.storage.googleapis.com/108.0.5359.71/chromedriver_mac_arm64.zip
Saving to file: /var/folders/x2/px4zdh5d6gd1xpqwc2n9xtqc0000gp/T/108.0.5359.71/chromedriver/chromedriver_mac_arm64.zip
Received 1040K...
Received 2080K...
Received 3120K...
Received 4160K...
Received 5200K...
Received 6240K...
Received 7280K...
Received 8004K total.
Extracting zip contents to /var/folders/x2/px4zdh5d6gd1xpqwc2n9xtqc0000gp/T/108.0.5359.71/chromedriver.
Copying from /var/folders/x2/px4zdh5d6gd1xpqwc2n9xtqc0000gp/T/108.0.5359.71/chromedriver to target path /Users/jacquelinegeorge/Documents/WebdriverIOPOC/webdriver-appium-v8/node_modules/chromedriver/lib/chromedriver
Fixing file permissions.
Done. ChromeDriver binary available at /Users/jacquelinegeorge/Documents/WebdriverIOPOC/webdriver-appium-v8/node_modules/chromedriver/lib/chromedriver/chromedriver
npm WARN my-new-project@ No description
npm WARN my-new-project@ No repository field.
npm WARN my-new-project@ No license field.

+ chromedriver@108.0.0
+ @wdio/mocha-framework@8.1.0
+ @wdio/local-runner@8.1.0
+ wdio-chromedriver-service@8.0.1
+ @wdio/spec-reporter@8.1.0
+ @wdio/appium-service@8.1.0
added 118 packages from 86 contributors and audited 558 packages in 11.402s

126 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

✔ Success!

Creating a WebdriverIO config file...
✔ Success!

Adding "wdio" script to package.json.

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, fund, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    /Users/jacquelinegeorge/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.14.17 /usr/local/lib/node_modules/npm

wdio config

Initialize WebdriverIO and setup configuration in your current project.

Options:
      --version          Show version number                           [boolean]
      --watch            Run WebdriverIO in watch mode                 [boolean]
  -h, --hostname         automation driver host address                 [string]
  -p, --port             automation driver port                         [number]
      --path             path to WebDriver endpoints (default "/")      [string]
  -u, --user             username if using a cloud service as automation backend
                                                                        [string]
  -k, --key              corresponding access key to the user           [string]
  -l, --logLevel         level of logging verbosity
                  [choices: "trace", "debug", "info", "warn", "error", "silent"]
      --bail             stop test runner after specific amount of tests have fa
                         iled                                           [number]
      --baseUrl          shorten url command calls by setting a base url[string]
  -w, --waitforTimeout   timeout for all waitForXXX commands            [number]
  -f, --framework        defines the framework (Mocha, Jasmine or Cucumber) to r
                         un the specs                                   [string]
  -r, --reporters        reporters to print out the results on stdout    [array]
      --suite            overwrites the specs attribute and runs the defined sui
                         te                                              [array]
      --spec             run only a certain spec file - overrides specs piped fr
                         om stdin                                        [array]
      --exclude          exclude certain spec file from the test run - overrides
                          exclude piped from stdin                       [array]
      --mochaOpts        Mocha options
      --jasmineOpts      Jasmine options
      --cucumberOpts     Cucumber options
      --autoCompileOpts  Auto compilation options
      --yarn             Install packages via Yarn package manager.
                                                      [boolean] [default: false]
  -y, --yes              will fill in all config defaults without prompting
                                                      [boolean] [default: false]
  -t, --npmTag           define NPM tag to use for WebdriverIO related packages
                                                    [string] [default: "latest"]
      --help             Show help                                     [boolean]

Documentation: https://webdriver.io
@wdio/cli (v8.1.0)

Error: ⚠️ Couldn't add script to package.json: Error: Error calling: npm pkg set scripts.wdio=wdio run ./wdio.conf.js
    at ChildProcess.<anonymous> (file:///Users/jacquelinegeorge/Documents/WebdriverIOPOC/webdriver-appium-v8/node_modules/@wdio/cli/build/utils.js:506:31)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
    at createWDIOScript (file:///Users/jacquelinegeorge/Documents/WebdriverIOPOC/webdriver-appium-v8/node_modules/@wdio/cli/build/utils.js:676:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runConfigCommand (file:///Users/jacquelinegeorge/Documents/WebdriverIOPOC/webdriver-appium-v8/node_modules/@wdio/cli/build/commands/config.js:118:5)
    at async Object.handler (file:///Users/jacquelinegeorge/Documents/WebdriverIOPOC/webdriver-appium-v8/node_modules/@wdio/cli/build/commands/config.js:126:5)


⚠️  Ups, something went wrong: Error calling: npx wdio config!
```

**Comment by christian-bromann** [comment]
Can you check the Node version in your VS Code terminal as well? Given you have a different terminal session there, based on your configuration , it might have a different node version.

**Comment by fypnlp1** [comment]
<img width="574" alt="Screenshot 2023-01-03 at 16 59 43" src="https://user-images.githubusercontent.com/116070074/210404493-84056bc8-03f5-40e9-b440-2a8daede87cd.png">

**Comment by christian-bromann** [comment]
This is in your terminal, what I am asking is call the same command within your VS Code.

**Comment by fypnlp1** [comment]
let me check :

<img width="1031" alt="Screenshot 2023-01-03 at 17 19 03" src="https://user-images.githubusercontent.com/116070074/210408148-0ba8a8ea-7d6c-4c46-ae4a-b6dcac0e33d4.png">

**Comment by christian-bromann** [comment]
Ok, one last thing, what's the NPM version being used?

**Comment by christian-bromann** [comment]
Ok, it seems like you are using NPM v6 which is really old. I recommend to update NPM and retry. Adding the NPM script is not really important, you are basically still set up and can start writing your tests. I raised a PR to not throw an error and give you a description how to set the script manually. I will go ahead and close this one. Let me know if you have any further questions.

**Comment by ahmadfadlie95** [comment]
Hi, I tried to update the node version and npm version to the latest, but now I got this error:

<img width="616" alt="Screenshot 2023-06-08 at 2 37 11 PM" src="https://github.com/webdriverio/webdriverio/assets/81462016/4996b222-dcda-49b4-b761-cfbec3f8f27e">

**Comment by christian-bromann** [comment]
@ahmadfadlie95 no idea why your NPM is failing to install the package.

**Comment by masumshamsur** [comment]
@ahmadfadlie95  were you able to solve the error you facing, I am also having the same errors. please help me if you are able to.

Thanks

**Comment by Monir1999** [comment]
Creating a WebdriverIO config file...
✔ Success!

Autogenerating test files...
✔ Success!

Adding "wdio" script to package.json
⚠️  Couldn't add script to package.json: "spawn EINVAL", you can add it manually by running:

        npm.cmd pkg set scripts.wdio="wdio run ./wdio.conf.js"

Autogenerating test files...
✔ Success!

Adding "wdio" script to package.json
⚠️  Couldn't add script to package.json: "spawn EINVAL", you can add it manually by running:

        npm.cmd pkg set scripts.wdio="wdio run ./wdio.conf.js"

Adding "wdio" script to package.json
⚠️  Couldn't add script to package.json: "spawn EINVAL", you can add it manually by running:

        npm.cmd pkg set scripts.wdio="wdio run ./wdio.conf.js"


        npm.cmd pkg set scripts.wdio="wdio run ./wdio.conf.js"
        how to solve this problem?
