### ISSUE TITLE
execute - what the hell you doing?

### ISSUE THREAD

**Issue by bondarum** [webdriverio/webdriverio#953]
```javascript
it('', function(done)
    {
        this.client
            .execute( function( name, frameId ){
                var frame = document.getElementById( frameId );
                var innerFrame = frame.contentDocument;

                return innerFrame.getElementsByName( name )[0].id;

            }, scope.encodeField( field ), scope.frameId )
            .then(function( res ){
                scope.helper = '#' + res.value;
                console.log('HELPER', scope.helper);  // this is irrelevant 
            })
            .call(done);
    });
```

So I want to get some data from element in iframe. I thought I've done everything right, no rocket science here. What happens is whole test is failing due to "contentDocument" of undefined.
I'm sure page is loaded and every selector is sound but still. Funny thing it works in 40% cases.
I really need some explanation.

**Comment by christian-bromann** [comment]
Hi @bondarum ,
I don't think this is an issue of WebdriverIO. I am not sure what's wrong here the code looks ok. I think Stackoverflow is a better platform to ask questions like that.
Thanks
