### ISSUE TITLE
execute - Inject a JS script from URL into the page

### ISSUE THREAD

**Issue by svalchinov** [webdriverio/webdriverio#954]
The page I'm testing currently loads jquery from a cdn so running it in PhantomJS throws a Can't find variable: jQuery. 

I am trying to inject a script into the page context (i.e. jquery) using the execute method without success.

Is something like this possible to do/implement?
driver.url('URL').execute('URL').getTitle()

**Comment by christian-bromann** [comment]
No, you need to grab the content of the jquery.js file and put it into the execute script. I guess there are jquery packages available even on NPM. The other way would be to use the execute command to inject a new script tag to the page that loads jquery.
