### ISSUE TITLE
[💡 Feature]: way to run setup code before driver is attached to test

### ISSUE THREAD

**Issue by piotrblasiak** [webdriverio/webdriverio#9546]
### Is your feature request related to a problem?

Currently, in order to set up resources in preparation of a test you need to do that using `before(() => {...});`, but this is executed when the driver is already attached to the test (as should be, since it may be needed). But very often, whatever is done here doesn't need the browser yet and is simply wasting browser time. This is especially wasteful if you're using a device farm.

### Describe the solution you'd like.

The ideal solution would be a beforeSession(() => {...}); function or similar, that is executed before the driver is attached to the test - so that the available browser sessions can be used by other tests while this is executing.

### Describe alternatives you've considered.

I've checked hooks, altho this wouldn't be ideal it could have been a workaround - but I couldn't find a way to do it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RossVertizan** [comment]
@piotrblasiak what is wrong with using the hooks?  Why wouldn't it work for you and why wouldn't it be ideal?

I'm curious as I've generally found a hook that allows me to do what I want to do.  From what you have described I would have thought that the either the '''onPrepare''' or the '''onWorkerStart''' hooks would be the ones to look at?

```
// =====
    // Hooks
    // =====
    // WebdriverIO provides several hooks you can use to interfere with the test process in order to enhance
    // it and to build services around it. You can either apply a single function or an array of
    // methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
    // resolved to continue.
    /**
     * Gets executed once before all workers get launched.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     */
    // onPrepare: function (config, capabilities) {
    // },
    /**
     * Gets executed before a worker process is spawned and can be used to initialise specific service
     * for that worker as well as modify runtime environments in an async fashion.
     * @param  {String} cid      capability id (e.g 0-0)
     * @param  {[type]} caps     object containing capabilities for session that will be spawn in the worker
     * @param  {[type]} specs    specs to be run in the worker process
     * @param  {[type]} args     object that will be merged with the main configuration once worker is initialized
     * @param  {[type]} execArgv list of string arguments passed to the worker process
     */
    // onWorkerStart: function (cid, caps, specs, args, execArgv) {
    // },
    /**
     * Gets executed just before initialising the webdriver session and test framework. It allows you
     * to manipulate configurations depending on the capability or spec.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     * @param {String} cid worker id (e.g. 0-0)
     */
    // beforeSession: function (config, capabilities, specs, cid) {
    // },
    /**
```

**Comment by piotrblasiak** [comment]
> @piotrblasiak what is wrong with using the hooks? Why wouldn't it work for you and why wouldn't it be ideal?
> 
> I'm curious as I've generally found a hook that allows me to do what I want to do. From what you have described I would have thought that the either the '''onPrepare''' or the '''onWorkerStart''' hooks would be the ones to look at?
> 
> ```
> // =====
>     // Hooks
>     // =====
>     // WebdriverIO provides several hooks you can use to interfere with the test process in order to enhance
>     // it and to build services around it. You can either apply a single function or an array of
>     // methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
>     // resolved to continue.
>     /**
>      * Gets executed once before all workers get launched.
>      * @param {Object} config wdio configuration object
>      * @param {Array.<Object>} capabilities list of capabilities details
>      */
>     // onPrepare: function (config, capabilities) {
>     // },
>     /**
>      * Gets executed before a worker process is spawned and can be used to initialise specific service
>      * for that worker as well as modify runtime environments in an async fashion.
>      * @param  {String} cid      capability id (e.g 0-0)
>      * @param  {[type]} caps     object containing capabilities for session that will be spawn in the worker
>      * @param  {[type]} specs    specs to be run in the worker process
>      * @param  {[type]} args     object that will be merged with the main configuration once worker is initialized
>      * @param  {[type]} execArgv list of string arguments passed to the worker process
>      */
>     // onWorkerStart: function (cid, caps, specs, args, execArgv) {
>     // },
>     /**
>      * Gets executed just before initialising the webdriver session and test framework. It allows you
>      * to manipulate configurations depending on the capability or spec.
>      * @param {Object} config wdio configuration object
>      * @param {Array.<Object>} capabilities list of capabilities details
>      * @param {Array.<String>} specs List of spec file paths that are to be run
>      * @param {String} cid worker id (e.g. 0-0)
>      */
>     // beforeSession: function (config, capabilities, specs, cid) {
>     // },
>     /**
> ```

The timing of those hooks is good, but now the problem is to find all the tests, run any setUp code and save the results for the tests themselves to use - something I assume you'd have to use globals or files.

**Comment by christian-bromann** [comment]
> now the problem is to find all the tests

What kind of information do you need and what is the set up code doing?

**Comment by piotrblasiak** [comment]
> > now the problem is to find all the tests
> 
> What kind of information do you need and what is the set up code doing?

So the setup code would do things like use the API to create a page/entities in the backend to be displayed and tested by the frontend, and similarly the teardown would clean those entities up. There is no reason for the api calls to the backend for the setup to be done while the session is attached. Unless I'm mistaken this should save a lot of time if possible to do before.

**Comment by christian-bromann** [comment]
> So the setup code would do things like use the API to create a page/entities in the backend to be displayed and tested by the frontend, and similarly the teardown would clean those entities up.

As @RossVertizan already mentioned the WebdriverIO hooks are ideal for this type of work. You can execute async calls in them and have the test fail if the setup fails for some reason. I recommend use `onPrepare` to run a script once for all tests and `onWorkerStart` before every worker (test/browser combination).

> There is no reason for the api calls to the backend for the setup to be done while the session is attached. Unless I'm mistaken this should save a lot of time if possible to do before.

Not sure if I understand this correctly but yeah, running a setup script once before all tests makes sense to me.

I will close the issue as I don't see a bug here. Happy to assist further.

**Comment by piotrblasiak** [comment]
Great, the thing now is that it's not something to run once all for all tests - but every test might have some special setup code. So ideally, that setup code would be placed in the same file as the test itself - otherwise I would have to scan for all test classes in the hook somehow, execute that special setup function and save the result in a file or global scope I guess?

**Comment by RossVertizan** [comment]
Ok, got it.  So, the setup is creating unique assets on the back-end for each test, so it needs to be done on a per-test basis which means it has to by one of the hooks that runs in the worker and once the worker has spawned you are using valuable browser time.  I am presuming there is a reason why you can't run one big script at the beginning to create assets for all tests and then one at the end to rip them all down, presumably there are conflicts in the assets or it would be too much data?

I'm not expert in this, but wouldn't the ```beforeSession``` hook work in this case?  Running a simple example on my desktop, I see that the ChromeDriver (in my case) is launched, then the ```beforeSession``` hook is executed and only when the hook has finished does it launch the browser session.  From this function you can get the name of the spec file the test will execute e.g.

```file:///<somepath>/my-app/specs/my-test23.js``` 

in the specs argument to the beforeSession function.  If you were to create a matching setup file e.g.:

```file:///<somepath>/my-app/specs/my-test23-pretest.js``` 

then you could easily find and execute a function within.

However, this is where I come unstuck, what do you mean by 

> save the result in a file or global scope

I thought you were just creating assets on the server.  I suppose even if you do need to save data, you have a way of referencing the filesystem, so you could write to a file such as:

``file:///<somepath>/my-app/rundata/my-test23-rundata.js``` 

Is any of this making any sense or am I way off?

**Comment by piotrblasiak** [comment]
Thanks @RossVertizan (and everyone else) for the help, I was not aware you could get the name of the spec file about to execute - that's useful.

I do think however that it would be valuable, and probably could speed a lot of tests out there is if these hooks were available inside the test files as well - so that you would not have to save & read what you call asset data to/from temporary files but as variables inside the files. In some cases, this asset data may not even be serialisable. In my case I have an event invitation page that I want to test, so I create that invitation and get it's id. Then I use that id in the url I want to test: `http://localhost:9090/invitations/${id}`.
Setting up one invitation before all tests could work sometimes, but usually the test expects the asset to be in a certain state. I do already create some other assets which do not need to be created fresh, but a lot of time will be spent on creating one-off assets per test.

I hope this makes sense.

**Comment by piotrblasiak** [comment]
I see. Mocha.

**Comment by piotrblasiak** [comment]
A thing I'm seeing is that both the before and beforeSession hooks are all executed multiple times, I guess once per worker - but the specs array contains all the specs, not just the ones that are going to be executed by this worker. This kind of makes these 2 hooks unusable in this situation, and I'm only left with the onPrepare hook where I'll have to find the specs myself somehow.

**Comment by RossVertizan** [comment]
Yes, the ```beforeSession``` hook will get executed as every worker is launched, which is what we wanted, right?

As for the specs array containing all of the specs, are you using the [spec grouping](https://webdriver.io/blog/2021/03/23/grouping-specs), meaning that your specs definition looks like this:
```
specs: [
        ['./test/actions/**/*.js']
    ],
```
and **not** like this:
```
specs: [
        './test/actions/**/*.js'
    ],
```
You might be doing this so that you launch a single browser and use it for all of your tests, which fits in with what yo said earlier in the thread.

In this case the 'before' hook will give you the single spec that is about to be executed, however, given that you are looking at optimising browser usage, I don't think this will help as one test will execute and complete and then the browser will sit idle while the before script executes.

So, at this point, I can't see a way to have the assets created just as you need them.  Assuming you are grouping the specs, I would suggest you make a comparison with execution time/utilisation when you don't group the specs.

**Comment by piotrblasiak** [comment]
Actually I wasn't using spec grouping but I should have been and now I am to improve performance, which is great - thanks ;)
In the end I found a workable solution:

```
const preparePromise = (async () => {
    const invitation = await createInvitation(...);
    return {invitation};
})();

describe(() => {
    it("works", async () => {
        const {invitation} = await preparePromise;

        Do the actual test...
    })
});
```

It's not ideal, but close to it.
