### ISSUE TITLE
(v8) getting no specs at all when using jasmine framework

### ISSUE THREAD

**Issue by HananArgov** [webdriverio/webdriverio#9547]
as can be seen in the attached image, when using jasmine framwork, we don't get any spec path at all

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/48208030/211200849-5350520f-0145-435d-ae55-ae6545df9c24.png">

https://github.com/webdriverio/webdriverio/blob/a2171f12ff08c1e03bb769ffc46c5e263ab833d6/packages/wdio-reporter/src/index.ts#L81-L84

my suggestion is to update the path in the following line
https://github.com/webdriverio/webdriverio/blob/a2171f12ff08c1e03bb769ffc46c5e263ab833d6/packages/wdio-reporter/src/index.ts#L70
so it would be:
```
            this.specs.push(...runner.config.specs)
```

**Comment by HananArgov** [comment]
i'm not sure if this suggestion is correct though, and what are the repercussions of it.
i've tested this locally (made the change in the code in the package itself), and it worked

**Comment by christian-bromann** [comment]
@HananArgov can you provide a bit context as to which issue you are working on?

**Comment by christian-bromann** [comment]
Closing due to missing context. Happy to re-open if more context can be provided.
