### ISSUE TITLE
user-data-dir

### ISSUE THREAD

**Issue by bazjapan** [webdriverio/webdriverio#956]
Hi,
I'm trying to use a certain chrome profile

see - http://stackoverflow.com/questions/14480717/load-chrome-profile-using-selenium-webdriver

This is what I have but it doesn't work, it always opens a new profile - 

 desiredCapabilities: {
        browserName: 'chrome',
        chromeOptions : {
        args: [
            'user-data-dir='+user_profile
        ]}

    }

**Comment by Pasupathi-Rajamanickam** [comment]
Any solution for this found?
