### ISSUE TITLE
[🐛 Bug]: webdriverio@8.1.3  import { Key } from 'webdriverio'   Key is undefined

### ISSUE THREAD

**Issue by yolopunk** [webdriverio/webdriverio#9573]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.1.3

### Node.js Version

19.2.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
    platformName: 'Windows',
    'appium:automationName': 'Windows',
    'appium:deviceName': 'WindowsPC',
    'appium:app': 'xx',
    'appium:ms:experimental-webdriver': true
  }
```

### What happened?

I want send Enter key. But, the Key varaiable is undefined

### How to reproduce the bug.

```js
import { Key, remote } from 'webdriverio'

...

 await driver.keys([Key.Enter])
```

### Relevant log output

```typescript
TypeError: Cannot read properties of undefined (reading 'Enter')
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
I am not sure how you set up your project , if it is TypeScript chances are that your import configurations are wrong. I just tested it in a simple ESM script and it worked. I will close the issue but would be happy to re-open if you could provide a reproducible example. Thanks!

**Comment by yolopunk** [comment]
@christian-bromann  I used commonJS module before. I switched to ESM that is work.  Thanks a lot!
