### ISSUE TITLE
[🐛 Bug]: Configuration wizard: validate relative path for specs/feature files and page objects

### ISSUE THREAD

**Issue by fypnlp1** [webdriverio/webdriverio#9578]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8

### Node.js Version

v19.3.0

### Mode

Standalone Mode

### What happened?

I was I am trying to build an automation framework using cucumber. I filled out the following correctly : 

<img width="825" alt="Screenshot 2023-01-12 at 16 10 17" src="https://user-images.githubusercontent.com/116070074/212120128-b1c48e66-1b18-4b2c-95c7-1fe12205f7ee.png">

### What is your expected behavior?

I was expecting to wdio file correctly show feature files, step definition files and page object folder correctly.  Instead I keep seeing the following: 

[watch this video](https://www.dropbox.com/s/aweeht1y7vu4gz8/cucumber%20page%20layout%20%20error.mov?dl=0)

### How to reproduce the bug.

Please view the 'what happened' box 

### Relevant log output

```typescript
Please view the 'what happened' box
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@fypnlp1 thanks for raising the issue and the well made video describing the problem!

The problem here is that you answered the questions, e.g. "Where should the feature files be located?" with `y` which is not a path to a directory. I am not sure why the wizard put all the files in the current directory though.

So to solve this issue I'ld suggest to:

- verify that the path for specs and page objects starts with `./` to enforce a relative path to the project

Would you like to take a stab at this? Happy to help through the process.

**Comment by fypnlp1** [comment]
> @fypnlp1 thanks for raising the issue and the well made video describing the problem!
> 
> The problem here is that you answered the questions, e.g. "Where should the feature files be located?" with `y` which is not a path to a directory. I am not sure why the wizard put all the files in the current directory though.
> 
> So to solve this issue I'ld suggest to:
> 
> * verify that the path for specs and page objects starts with `./` to enforce a relative path to the project
> 
> Would you like to take a stab at this? Happy to help through the process.

I  would massively appreciate the help.    Thank you so much.

**Comment by christian-bromann** [comment]
> Let me know when you are free

Please see https://webdriver.io/community/openofficehours

**Comment by KierenLWoods** [comment]
@christian-bromann i will take a shot at this one

**Comment by erwinheitzman** [comment]
@KierenLWoods thanks for doing so, let us know if you have any questions!

**Comment by erwinheitzman** [comment]
I think you are overcomplicating it a bit, what about we [resolve](https://nodejs.org/api/path.html#pathresolvepaths) the path and check the file [access](https://nodejs.org/api/fs.html#fspromisesaccesspath-mode)?

**Comment by erwinheitzman** [comment]
I think the check can be done in the answer itself unless it has to be reused in other places

**Comment by KierenLWoods** [comment]
@erwinheitzman i think there is an limitation with checking file access, as the function returns an error if the file/folder doesn't already exist, this then blocks the existing functionality which would create the desired folder structure to store the generated files.

**Comment by erwinheitzman** [comment]
@KierenLWoods that's what I would expect, you can handle this like so:
```js
import { accessSync, constants } from 'node:fs'

const filePath = 'example/path'
let isAccessible = false
try {
  accessSync(filePath, constants.R_OK | constants.W_OK)
  isAccessible = true
} catch (err) {
  // either throw here or ignore and throw later
}

if (!isAccessible) {
  throw new Error(`File could not be found at ${filePath}`)
}
```

Reference: https://nodejs.org/api/fs.html#fsaccesssyncpath-mode

**Comment by erwinheitzman** [comment]
You can also use the promisified version and do:
``` 
const isAccessible = await accessSync(filePath, constants.R_OK | constants.W_OK).then(() => true).catch(() => false);

if (!isAccessible) {
  throw new Error(`File could not be found at ${filePath}`)
}
```

This is more readable but promises always carry a little performance cost over their sync counterpart.

**Comment by KierenLWoods** [comment]
@erwinheitzman with that approach you would get the Error returned also when selecting the default value, would it be worth removing the default value so user  has to actually enter the file path they desire?

**Comment by erwinheitzman** [comment]
What's the current default? 👀

**Comment by KierenLWoods** [comment]
The default for this question depends on whether its a local or browser runner : 
 default: /* istanbul ignore next */ (answers) => {
            const pattern = isBrowserRunner(answers) ? 'src/**/*.test' : 'test/specs/**/*';
            return getDefaultFiles(answers, pattern);
        }
If you then accept the default filepath that is generated, using the access function would return an error.

**Comment by erwinheitzman** [comment]
Ah right, the paths don't exist yet. Should have considered this from the start, apologies.

In that case no check is needed and we should instead fix the issue as to why "foo" is not working as path since it is a valid relative path 🙂
