### ISSUE TITLE
[📃 Docs]: provide translation for project documentation

### ISSUE THREAD

**Issue by AugustinMauroy** [webdriverio/webdriverio#9582]
### Is your feature request related to a problem?

It's no an problem

### Describe the solution you'd like.

I propose to add the i18n feature of docusaurus to provide the website for all

**Ref:** https://docusaurus.io/docs/i18n/tutorial

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
@AugustinMauroy we tried calling out for help on translating the documentation via Crowdin but realised that it is hard to find contributor to this. Would you be willing to help translating it into a specific language?

**Comment by AugustinMauroy** [comment]
It's French. And I am happy to know that there is a crowdin

**Comment by christian-bromann** [comment]
Would you be interested contributing a french translation?

**Comment by AugustinMauroy** [comment]
Yeeaahh

**Comment by AugustinMauroy** [comment]
@christian-bromann any news ?

**Comment by christian-bromann** [comment]
Not yet, I will try to set something up soon.

**Comment by christian-bromann** [comment]
@AugustinMauroy we set up a Crowdin project and I enabled the French language. You can just go to https://crowdin.com/project/webdriver-io and help us translate the docs. Let me know if you have any questions.

**Comment by AugustinMauroy** [comment]
I'm starting to translate.

**Comment by christian-bromann** [comment]
Translations are making progress:

![Screenshot 2023-04-16 at 20 38 56](https://user-images.githubusercontent.com/731337/232372504-3072a338-e981-4000-ae5c-784147906e84.png)

Hindi und Spanish will be translated by two contractor I hired with money from our OpenCollective.

@AugustinMauroy are you still interested finishing the French translation?

**Comment by lacell75** [comment]
I can help for french language if needed

**Comment by AugustinMauroy** [comment]
I continue the work!

**Comment by christian-bromann** [comment]
> I can help for french language if needed

Awesome, just head to https://translate.webdriver.io , sign up with your GitHub or whatever works for you best and use the platform to provide the translation. It comes with good suggestions, e.g. from Google Translate, so most of it will be just clicking on the best translation and tweak it only if necessary.

**Comment by m4hdyar** [comment]
@christian-bromann can you add the persian language? I'm happy to help.

**Comment by christian-bromann** [comment]
@m4hdyar that's awesome! Just enabled the language, you can go ahead and send in translation through https://translate.webdriver.io

**Comment by Byacrya** [comment]
> @m4hdyar that's awesome! Just enabled the language, you can go ahead and send in translation through [translate.webdriver.io](https://translate.webdriver.io). This one will be a bit more difficult as we have to change the text direction but I am convinced that shouldn't be too hard these days anymore.

Hi, could you also kindly enable Simplified Chinese translation, please? Also, is there any way to preview the translations?

**Comment by christian-bromann** [comment]
@Byacrya awesome, just added "Chinese (simplified)". They also have "Chinese (traditional)" and specific versions for Macau, Hong Kong and Singapore. Let me know if the simplified one doesn't work out.

You can preview the translations when setting up the website locally. I am working on setting up Crowdin in context and find better ways to deploy translated content on a dev server but for now checking it out locally is the way to go.

**Comment by Byacrya** [comment]
> @Byacrya awesome, just added "Chinese (simplified)". They also have "Chinese (traditional)" and specific versions for Macau, Hong Kong and Singapore. Let me know if the simplified one doesn't work out.
> 
> You can preview the translations when setting up the website locally. I am working on setting up Crowdin in context and find better ways to deploy translated content on a dev server but for now checking it out locally is the way to go.

Thanks! But unfortunately, I can only help with the Simplified one as I am more acquainted with it, and there are major differences in how words are used or spelled. 

By the way, when will be the appropriate time which the translations to be made publicly available?

**Comment by christian-bromann** [comment]
> By the way, when will be the appropriate time which the translations to be made publicly available?

I honestly don't know. I don't think we need to have all strings translated but at least 30-50% so it is useful.

**Comment by christian-bromann** [comment]
Closing in favor of #10261

Thank you @AugustinMauroy for kicking of this issue and effort translating the docs. We just released the first translations to production 🎉 More translations to come!
