### ISSUE TITLE
[🐛 Bug]: `Hook executed :` console noise from spec reporter w/ cucumber and realtimeReporter

### ISSUE THREAD

**Issue by zachlysobey** [webdriverio/webdriverio#9589]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16

### Node.js Version

18

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  // ...
  reporters: [
    ['spec', { realtimeReporting: true
  ]
}
```

### What happened?

With cucumber hooks (`Before(...)`, etc...) the `spec-reporter` with `realtimeReporting` enabled spits logs that look like `Hook executed :` with no additional context. For folks who have a bunch of hooks like myself, it ends up creating a lot of low-value noise.

The log comes from the following line, as introduced in webdriverio/webdriverio#7572

> https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-spec-reporter/src/index.ts#L151

### What is your expected behavior?

I see two approaches to better behavior:

1) Empower adding of a `Hook.title` to cucumber hooks

    _Experimentally, I tried a number of approaches to this, but no solution presented itself. Apologies if I missed something._

2) avoid logging at all if a title isn't present

The 2nd option is something I'd personally be willing to implement and PR. For `1)`, I couldn't easily trace the code to that point, so I'm not immediately clear on how to tackle it.

### How to reproduce the bug.

With a cucumber project, set a `Before` hook, and use the spec reporter as described above. Run the tests.

### Relevant log output

```typescript
Hook executed :
Hook executed :
Hook executed :
Hook executed :
Hook executed :
Hook executed :
...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by zachlysobey** [comment]
@praveendvd hope you don't mind a mention here, but since you were the author of #7572 maybe this is of interest to you 🤷

**Comment by zachlysobey** [comment]
I did end up having some more luck tracing the source of the hook title (or lack thereof)

Pasting here as a breadcrumb for later explorations

> https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-cucumber-framework/src/reporter.ts#L119-L126

**Comment by christian-bromann** [comment]
Thanks for raising the issue.

If you can provide a PR with a fix for this that would be awesome. I think we need to ensure that the Cucumber framework adapter sends along a proper title, e.g. scenario and step name. Let me know if you need any help making a contribution. Cheers!

**Comment by praveendvd** [comment]
@zachlysobey Hi there is no title for hooks thats why it was throwing that , what would be a recommend behaviour ? print the hook name or remove the log itself if user wants ?
