### ISSUE TITLE
How to find sibling elements?

### ISSUE THREAD

**Issue by yhjor1212** [webdriverio/webdriverio#959]
as title

**Comment by christian-bromann** [comment]
There is no sibling selector method in Selenium. However you use css selector or xpath methods to grab siblings.

**Comment by jkarttunen** [comment]
@yhjor1212 Normal CSS sibling selectors seem to work: 'h4 + div'

Not so with content selectors like 'h4=foo + div

**Comment by batje** [comment]
I found this too, 
`[name='mycontrol']`
 works but 
`[name='mycontrol'] + table `
does not find the sibling
Maybe reopen the issue?

**Comment by christian-bromann** [comment]
@batje it is up to the browser driver to support this. WebdriverIO can't provide support for it out of the box.
