### ISSUE TITLE
Error parsing cert retrieved from AIA (as DER):  ERROR: Couldn't read tbsCertificate as SEQUENCE  ERROR: Failed parsing Certificate

### ISSUE THREAD

**Issue by bhanuagarwal73** [webdriverio/webdriverio#9596]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7

### Node.js Version

16.x.x

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [{

        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        maxInstances: 3,
        //
        browserName: chrome,
        acceptInsecureCerts: true,

        "goog:chromeOptions": runtimeArgs.browserName === 'chrome' ? {
            "args": ["user-agent=gcp-automation-test (Windows NT)",
                `${process.env.HEADLESS === 'true' ? '--headless' : undefined}`,
                `${process.env.HEADLESS === 'true' ? '--window-size=1920,1080' : undefined}`
            ]
        } : {},

        "bstack:options": runtimeArgs.service === 'browserstack' ? {
            "projectName": "merx-shopify-automation",
            "buildName": `${runtimeArgs.env} - ${runtimeArgs.brand} - ${runtimeArgs.suite} - ${runtimeArgs.browserName}`,
            "os": runtimeArgs.os,
            "osVersion": runtimeArgs.osVersion,
            "deviceName": runtimeArgs.device,
            "networkLogs": true,
            "consoleLogs": "errors",
            "browserVersion": "latest",
            "local": true
        } : {}



package.json file:
"devDependencies": {
        "@wdio/allure-reporter": "^7.25.4",
        "@wdio/browserstack-service": "^7.25.4",
        "@wdio/cli": "^7.25.4",
        "@wdio/globals": "^8.1.3",
        "@wdio/junit-reporter": "^7.25.4",
        "@wdio/local-runner": "^7.25.4",
        "@wdio/mocha-framework": "^7.25.4",
        "@wdio/selenium-standalone-service": "^7.25.4",
        "@wdio/spec-reporter": "^7.25.4",
        "capitalize": "^2.0.4",
        "chromedriver": "^109.0.0",
        "cross-env": "^7.0.3",
        "flatted": "^3.2.7",
        "superagent": "^8.0.3",
        "ts-node": "^10.9.1",
        "typescript": "^4.8.4",
        "wdio-chromedriver-service": "^8.0.1",
        "wdio-light-reporter": "^0.2.7",
        "xunit-viewer": "^7.2.0"
    },
    "scripts": {
        "wdio": "wdio run wdio.conf.ts",
        "BVT": "wdio run wdio.conf.ts --suite BVT",
        "P1": "wdio run wdio.conf.ts --suite P1",
        "mobile_BVT": "wdio run wdio.conf.ts --suite mobile_BVT"
    },
    "dependencies": {
        "allure-commandline": "^2.20.1",
        "uuid": "^9.0.0"
    }
```

### What happened?

When browser getting launched then seeing error in terminal as:
Error parsing cert retrieved from AIA (as DER):
ERROR: Couldn't read tbsCertificate as SEQUENCE
ERROR: Failed parsing Certificate

In addition, I am running the 3 instances but out of that 1st instance of [0-0] not showing latest UI (means no change in Front-end but seeing logs over terminal)

### What is your expected behavior?

It should show the updated UI (like whatever actions are doing such as add-to-cart, login... it should show the same in UI also.
In addition, if added --ignore-certificate-errors then shouldn't show below errors:
Error parsing cert retrieved from AIA (as DER):
ERROR: Couldn't read tbsCertificate as SEQUENCE
ERROR: Failed parsing Certificate

### How to reproduce the bug.

Just run the code with 3 parallel instances against chromedriver UI

### Relevant log output

```typescript
Error parsing cert retrieved from AIA (as DER):
ERROR: Couldn't read tbsCertificate as SEQUENCE
ERROR: Failed parsing Certificate
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for raising the issue. Hard to say what is going on without any logs. My assumption is that you try to run your tests behind a firewall or proxy that is not configured correctly. See https://webdriver.io/docs/proxy how to setup WebdriverIO with a proxy setup.

I will close this issue as it is unlikely a problem with WebdriverIO.
