### ISSUE TITLE
[🐛 Bug]: Watch shows "You are trying to attach to a protocol stub" error when re-running tests

### ISSUE THREAD

**Issue by romaricpascal** [webdriverio/webdriverio#9608]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.1.3

### Node.js Version

v18.12.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
https://github.com/alphagov/govuk-frontend/blob/467e25a5f9f20d417d6bec9ed2bff99e67b68b7d/wdio.conf.js (uses devtools protocol) or https://github.com/alphagov/govuk-frontend/blob/90791a088da2bfa24efb3a89277069fb73ced930/wdio.conf.js (uses webdriver with the workaround from https://github.com/webdriverio/webdriverio/issues/8279)
```

### What happened?

When watching file changes to re-run the tests, wdio displays an error when re-running the tests after a change (see Log outputs for details). This does not stop the tests from re-running, but is a worrying output in the console while you run your tests.

The issue happens both with devtools and webdriver protocols.

### How to reproduce the bug.

1. Checkout https://github.com/alphagov/govuk-frontend/tree/467e25a5f9f20d417d6bec9ed2bff99e67b68b7d (devtools) or https://github.com/alphagov/govuk-frontend/tree/90791a088da2bfa24efb3a89277069fb73ced930 (webdriver)
2. run `npm install`
3. run `npm run wdio -- --watch`. This will run the tests a first time
4. run `touch src/govuk/components/character-count/character-count.e2e.mjs` to trigger a test re-run (if `touch` is not available on your system, you can open and save the file)

### Relevant log output

```typescript
[0-0] 2023-01-12T17:47:37.962Z ERROR @wdio/runner: Error: You are trying to attach to a protocol stub, this should never occur, please file an issue.
[0-0]     at ProtocolStub.attachToSession (file:///<redacted>/govuk-frontend/node_modules/webdriverio/build/protocol-stub.js:31:19)
[0-0]     at attach (file:///<redacted>/govuk-frontend/node_modules/webdriverio/build/index.js:73:27)
[0-0]     at async Runner._startSession (file:///<redacted>/govuk-frontend/node_modules/@wdio/runner/build/index.js:221:29)
[0-0]     at async Runner.run (file:///<redacted>/code/govuk-frontend/node_modules/@wdio/runner/build/index.js:58:23)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!



Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!
