### ISSUE TITLE
Webdriverio and Selenium Grid

### ISSUE THREAD

**Issue by sean-hill** [webdriverio/webdriverio#961]
Hey, I don't know if there is a solution posted on here yet, so please redirect me if needs be.

I'm trying to use Webdriverio along with Selenium Grid.

Using the `selenium-standalone` module, I've started selenium with `selenium-standalone start -- -role hub`, I think followed the docs of Webdriverio to initialize a client. However, I get this error:

	RuntimeError: Error forwarding the new session Empty pool of VM for setup Capabilities [{loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@1b55eef7, platform=ANY, javascriptEnabled=true, handlesAlerts=true, browserName=chrome, requestOrigins={name=webdriverio, url=http://webdriver.io, version=3.2.5}, rotatable=true, locationContextEnabled=true, chromeOptions={args=[]}, version=}]

	NoSessionIdError: A session id is required for this command but wasn't found in the response payload

Just curious how to get this to work, thanks.

**Comment by christian-bromann** [comment]
If you start a hub you need also to run a node server so that the hub can redirect the requests to available nodes. This error tells me that you didn't get a sessionID assigned from the hub which makes sense since it isn't the job of the hub to create sessions.

**Comment by sean-hill** [comment]
Perfect thank you!
