### ISSUE TITLE
[🐛 Bug]: Watch mode with Webdriver protocol shows "FetchError" on re-runs

### ISSUE THREAD

**Issue by romaricpascal** [webdriverio/webdriverio#9612]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.1.3

### Node.js Version

v18.12.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
https://github.com/alphagov/govuk-frontend/blob/ceeb9a7c6c0c807d8e2eae923b890f26ddebd476/wdio.conf.js
```

### What happened?

When running the wdio test runner in watch mode, re-runs of tests trigger a "TypeError: Failed to fetch browser webSocket URL", preventing the tests to run.

The error is the same as https://github.com/webdriverio/webdriverio/issues/8279, but occurs in a different context.

### How to reproduce the bug.

1. Checkout https://github.com/alphagov/govuk-frontend/tree/467e25a5f9f20d417d6bec9ed2bff99e67b68b7d (devtools) or https://github.com/alphagov/govuk-frontend/tree/90791a088da2bfa24efb3a89277069fb73ced930 (webdriver)
2. run `npm install`
3. run `npm run wdio -- --watch`. This will run the tests a first time
4. run `touch src/govuk/components/character-count/character-count.e2e.mjs` to trigger a test re-run (if `touch` is not available on your system, you can open and save the file)

### Relevant log output

```typescript
[0-0] 2023-01-16T11:39:35.733Z ERROR @wdio/runner: TypeError: Failed to fetch browser webSocket URL from http://localhost:50849/json/version: fetch failed
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!



Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!
