### ISSUE TITLE
WaitUntil produces unexpected results

### ISSUE THREAD

**Issue by wvankuipers** [webdriverio/webdriverio#962]
The `WaitUntil` command produces unexpected results when used multiple in tests.

Example:

     this.waitUntil(function() { [do something that will passe in 1000 ms] }, 1000);

Results in the correct success state.

    this.waitUntil(function() { [do something that will passe in 1000 ms] }, 1000);
    this.waitUntil(function() { [do something that will passe in 2000 ms] }, 2000);
    this.waitUntil(function() { [do something that will passe in 3000 ms] }, 3000);

Results in a incorrect error state.

I have pinpointed the problem to the following lines (78, 79) in the file `lib/commands/waitUntil.js`

     return defer.resolve(self.pause(interval)
                .then(waitUntilPrivate.bind(self, condition, timeout, interval, starttime)));

What will happen is that the `.bind()` function is executed before the self.pause(interval) is finished. This causes the tests to fail.

I will create a pull request that resolves this issue.

**Comment by christian-bromann** [comment]
Cool, let's close this one then and continue convo on #963
