### ISSUE TITLE
[🐛 Bug]: Broken types in `@wdio/global/types`

### ISSUE THREAD

**Issue by kyryloonufriiev** [webdriverio/webdriverio#9639]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.2.0

### Node.js Version

latest

### Mode

Standalone Mode

### What happened?

I am getting an error trying to build my setup with typescript

```
node_modules/@wdio/globals/types.d.ts:1:42 - error TS2694: Namespace '"/Users/kyrylo/project/node_modules/webdriverio/build/index"' has no exported member 'Browser'.

1 type BrowserType = import('webdriverio').Browser
```

### How to reproduce the bug.

Simply typescript project with wdio

### Relevant log output

```typescript
-
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by kyryloonufriiev** [comment]
@christian-bromann I suspect this is happening due to an internal PR that fixes types after killing the sync mode. The `webdrvierio` package indeed doesn't exports any `Browser` or `Element` type instead it declares global types in the namespace `WebdrvierIO`

**Comment by christian-bromann** [comment]
@kyryloonufriiev can you provide a reproducible example please?

**Comment by kyryloonufriiev** [comment]
@christian-bromann checkout this repo - https://github.com/kyryloonufriiev/webdriverio-types-issue-example

**Comment by christian-bromann** [comment]
> checkout this repo

There doesn't seem to be anything in it, just two empty files

**Comment by kyryloonufriiev** [comment]
Sorry. You meant to do `yarn && npx tsc`

**Comment by kyryloonufriiev** [comment]
@christian-bromann These are the errors I see

```
node_modules/@wdio/globals/types.d.ts:1:42 - error TS2694: Namespace '"/Users/kyrylo/Projects/webdriverio-types-issue-example/node_modules/webdriverio/build/index"' has no exported member 'Browser'.

1 type BrowserType = import('webdriverio').Browser
                                           ~~~~~~~

node_modules/@wdio/globals/types.d.ts:2:42 - error TS2694: Namespace '"/Users/kyrylo/Projects/webdriverio-types-issue-example/node_modules/webdriverio/build/index"' has no exported member 'Element'.

2 type ElementType = import('webdriverio').Element
                                           ~~~~~~~

node_modules/@wdio/globals/types.d.ts:4:53 - error TS2694: Namespace '"/Users/kyrylo/Projects/webdriverio-types-issue-example/node_modules/webdriverio/build/index"' has no exported member 'MultiRemoteBrowser'.

4 type MultiRemoteBrowserType = import('webdriverio').MultiRemoteBrowser
                                                      ~~~~~~~~~~~~~~~~~~

node_modules/@wdio/globals/types.d.ts:5:53 - error TS2694: Namespace '"/Users/kyrylo/Projects/webdriverio-types-issue-example/node_modules/webdriverio/build/index"' has no exported member 'MultiRemoteElement'.

5 type MultiRemoteElementType = import('webdriverio').MultiRemoteElement
                                                      ~~~~~~~~~~~~~~~~~~

node_modules/puppeteer-core/lib/esm/puppeteer/common/TargetManager.d.ts:23:51 - error TS2694: Namespace '"/Users/kyrylo/Projects/webdriverio-types-issue-example/node_modules/puppeteer-core/node_modules/devtools-protocol/types/protocol"' has no exported member 'Target'.

23 export type TargetFactory = (targetInfo: Protocol.Target.TargetInfo, session?: CDPSession) => Target;
                                                     ~~~~~~


Found 5 errors in 2 files.

Errors  Files
     4  node_modules/@wdio/globals/types.d.ts:1
     1  node_modules/puppeteer-core/lib/esm/puppeteer/common/TargetManager.d.ts:23
```

You can ignore the error in `puppeteer-core`, I've already fixed it there, should be released with the next version. What I want to solve is the errors in `@wdio/globals/types`

**Comment by christian-bromann** [comment]
Thanks for reporting, I pushed a fix and release it momentarily.
