### ISSUE TITLE
[🐛 Bug]: Mochawesome report error

### ISSUE THREAD

**Issue by testSadab** [webdriverio/webdriverio#9642]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest (8.2.1)

### Node.js Version

16

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    browserName: 'chrome'
    browserVersion: 'latest',
    platform: 'macOS'
}
```

### What happened?

I am trying to setup mochawesome report in current project following https://webdriver.io/docs/wdio-mochawesome-reporter/ but getting error when trying to install `wdio-mochawesome-reporter`

Logs: https://github.com/testSadab/WebdriverIOMochaTS/blob/mocha_report/installation_error.txt

if I add  `--legacy-peer-deps` as suggested in error then i am able to install the package but that creates problem that i have to add `--legacy-peer-deps` with all installation command in project.

Also if i am using `"mochawesome-report-generator": "^6.2.0",` which is latest version for generating report i get another error
I was able to generate report with `"mochawesome-report-generator": "^3.1.5"` though

Logs: https://github.com/testSadab/WebdriverIOMochaTS/tree/mochawesome_generate_issue/report_generate_error.txt

### What is your expected behavior?

I should be able to install `wdio-mochawesome-reporter` like any other package and generate mochawesome report without adding `--legacy-peer-deps`

Also i should be able to generate mochawesome report with latest version "mochawesome-report-generator"

### How to reproduce the bug.

To reproduce first issue
git clone https://github.com/testSadab/WebdriverIOMochaTS.git
npm install
npm install wdio-mochawesome-reporter --save-dev    (1st error steps)

or you can setup new project from scratch using `npm init wdio ./PathOfProject` 
select `mocha` for framework
select `typscript` for compiler
select `mochawesome` for report

To reproduce 2nd error
git checkout mochawesome_generate_issue
npm install --legacy-peer-deps
npm run wdio
npm run report

### Relevant log output

```typescript
https://github.com/testSadab/WebdriverIOMochaTS/blob/mocha_report/installation_error.txt

https://github.com/testSadab/WebdriverIOMochaTS/blob/mochawesome_generate_issue/report_generate_error.txt
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@testSadab thanks for filing the issue.

The `mochawesome` reporter is not part of this repository, please file the issue here: https://github.com/fijijavis/wdio-mochawesome-reporter.
