### ISSUE TITLE
[🐛 Bug]: The value of "command" imported from "webdriver" package is undefined

### ISSUE THREAD

**Issue by Frully** [webdriverio/webdriverio#9678]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.3.0

### Node.js Version

18.12.1

### Mode

Standalone Mode

### What happened?

I try to import the command function of the "webdriver" package, but get an undefined.

### What is your expected behavior?

command should be a function

### How to reproduce the bug.

```js
import {command} from 'webdriver';

console.log(command);
```

### Relevant log output

```typescript
undefined
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Hey @Frully , thanks for raising the issue.

Unfortunately I can't reproduce this. I created a new directory, installed latest `webdriver` from NPM and created a file with the content you provided above. It printed a function as expected.
