### ISSUE TITLE
NoSessionIdError

### ISSUE THREAD

**Issue by sean-hill** [webdriverio/webdriverio#968]
Hey there, I'm having an issue where the `NoSessionIdError` is being repeatedly thrown. Basically my flow is I have a chain of commands, but perhaps half way through, an error is thrown, at that point I'd like to delete my session, and close the browser. For example:

    client
	    .init()
	    .url('http://www.google.com')
	    .do()
	    .something()
	    .now()
	    .end();

Now assume that in between the commands `do` and `something` I'd like to quit the browser because some test case didn't pass.

If I do

	.do()
	.then(function(testCase){

		if (testCase === 'failed') {
			return this.end();
		}

	})
	.something()
	.now()
	.end();

Webdriver continues to run the commands after it and I get this error repeatedly over and over till my server runs out of memory:

	23:47:26.111 INFO - Done: [delete session: 485c371e-6003-4801-8ba4-77472ed2871f]
	23:47:26.114 WARN - Exception thrown
	org.openqa.selenium.remote.SessionNotFoundException: Session ID is null. Using WebDriver after calling quit()?
	Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
	System info: host: 'N/A', ip: 'N/A', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-36-generic', java.version: '1.7.0_75'
	Driver info: driver.version: RemoteWebDriver
		at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:125)
		at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:66)
		at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:572)
		at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:622)
		at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:324)
		at org.openqa.selenium.remote.server.handler.CaptureScreenshot.call(CaptureScreenshot.java:35)
		at org.openqa.selenium.remote.server.handler.CaptureScreenshot.call(CaptureScreenshot.java:1)
		at java.util.concurrent.FutureTask.run(FutureTask.java:262)
		at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
		at java.lang.Thread.run(Thread.java:745)
	23:47:26.118 WARN - Exception: Session ID is null. Using WebDriver after calling quit()?
	Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
	System info: host: 'N/A', ip: 'N/A', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-36-generic', java.version: '1.7.0_75'
	Driver info: driver.version: RemoteWebDriver
	RuntimeError: Session ID is null. Using WebDriver after calling quit()?
	Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
	System info: host: 'N/A', ip: 'N/A', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-36-generic', java.version: '1.7.0_75'
	Driver info: driver.version: RemoteWebDriver
	    at end() - test-cases:132:7
	NoSessionIdError: A session id is required for this command but wasn't found in the response payload
	    at end() - test-cases:132:7
	NoSessionIdError: A session id is required for this command but wasn't found in the response payload
	    at end() - test-cases:132:7
	NoSessionIdError: A session id is required for this command but wasn't found in the response payload
	    at end() - test-cases:132:7
	NoSessionIdError: A session id is required for this command but wasn't found in the response payload
	    at end() - test-cases:132:7
	NoSessionIdError: A session id is required for this command but wasn't found in the response payload
	    at end() - test-cases:132:7
	NoSessionIdError: A session id is required for this command but wasn't found in the response payload
	    at end() - test-cases:132:7
	NoSessionIdError: A session id is required for this command but wasn't found in the response payload
	    at end() - test-cases:132:7
	NoSessionIdError: A session id is required for this command but wasn't found in the response payload
	    at end() - test-cases:132:7
	NoSessionIdError: A session id is required for this command but wasn't found in the response payload
	    at end() - test-cases:132:7
	NoSessionIdError: A session id is required for this command but wasn't found in the response payload
    Error: spawn ENOMEM
	FATAL ERROR: Malloced operator new Allocation failed - process out of memory

	<--- Last few GCs --->

	    3890 ms: Scavenge 29.2 (60.0) -> 23.3 (60.0) MB, 14.8 / 0 ms [allocation failure].
	    4556 ms: Scavenge 30.3 (60.0) -> 24.8 (61.0) MB, 39.6 / 0 ms [allocation failure].
	    5295 ms: Scavenge 31.9 (63.0) -> 25.5 (63.0) MB, 23.2 / 0 ms [allocation failure].
	    5895 ms: Scavenge 32.9 (63.0) -> 26.5 (64.0) MB, 36.4 / 0 ms [allocation failure].
	   10296 ms: Scavenge 33.8 (64.0) -> 26.9 (64.0) MB, 260.1 / 0 ms [allocation failure].

	<--- JS stacktrace --->

	==== JS stack trace =========================================

	Security context: 0x189b27336ae1 <JS Object>
	    2: parse(aka urlParse) [url.js:~80] [pc=0x232fb8db997f] (this=0x2e88f1048609 <an Object with map 0x1cd46fcc94f9>,url=0x184229f5a301 <String[43]: https://github.com/cheeriojs/cheerio/issues>,parseQueryString=0x189b27304131 <undefined>,slashesDenoteHost=0x189b27304131 <undefined>)
	    3: arguments adaptor frame: 1->3
	    4: fixBugsField [/usr/lib/node_modules/npm/node_modules/normalize-packag...
This would be all right if the error was only thrown once, but it continues to throw it till the node process runs out of memory.

**Comment by christian-bromann** [comment]
@sean-hill if you call `end` you can't execute more commands because your session and browser got closed. Your example could work this way though:

```js
.do()
.then(function(testCase){

    if (testCase !== 'failed') {
        return this.something().now();
    }

})
.end();
```

Always call end at the end of your automation.
