### ISSUE TITLE
client.call(...) undocumented

### ISSUE THREAD

**Issue by fholzer** [webdriverio/webdriverio#970]
`client.call()` not documented on API page, but used in examples: https://github.com/webdriverio/webdriverio/blob/master/examples/standalone/webdriver.with.appium.chrome

**Comment by christian-bromann** [comment]
It used to be there but was removed with v3.x (not intentionally). We will add again with v4. This is how the command was documented:

```js
/**
 *
 * Call an own function within running chain. It is mostly used to end an async BDD/TDD block (see example below).
 *
 * <example>
    :call.js
    it('some title', function(done) {
        client
            .click('#elemA')
            .setValue('.firstname','webdriverbot')
            // use call to end async test spec (e.g. in Mocha or Jasmine)
            .call(done);
    });
 * </example>
 *
 * @param {Function} callback  function to be called
 * @type utility
 *
 */
```

**Comment by christian-bromann** [comment]
fixed by https://github.com/webdriverio/webdriverio/commit/df0ff316fb26d8c109fce544fc05a351010f1c45
