### ISSUE TITLE
Test sessionStorage with  Webdriver

### ISSUE THREAD

**Issue by kundarsowjanya** [webdriverio/webdriverio#9702]
### Is your feature request related to a problem?

HI, want to use sessionStorage.setItem("key", "value") inside wedriverio testcase after browser.url but currently I'm getting error like this 

ERROR webdriver: Request failed with status 404 due to invalid session id: invalid session id

### Describe the solution you'd like.

after entering to browser want to set sessionStorage.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
You should be able to do so via:

```ts
await browser.execute(() => sessionStorage.setItem("key", "value"))
```

Your error might be related to a different problem but hard to say given the information provided is limited.
