### ISSUE TITLE
If we add specs in capabilities then test not run in parallel

### ISSUE THREAD

**Issue by rajivnw** [webdriverio/webdriverio#9707]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v7

### Node.js Version

latest

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
"capabilities": [
{
platformName: "Android",
specs: ["tests/android//*.js"],
//...
},
{
platformName: "iOS",
specs: ["tests/ios//*.js"],
//...
}
]
```

### What happened?

If we add specs in capabilities then test not run in parallel. And if we remove specs then 2 thread will run for each platform as there are 2 capabilities exist. 

### How to reproduce the bug.

"capabilities": [
{
platformName: "Android",
specs: ["tests/android//*.js"],
//...
},
{
platformName: "iOS",
specs: ["tests/ios//*.js"],
//...
}
]

### Relevant log output

```typescript
not running in parallel
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for filing the issue.

Any help investigating the issue and come up with a solution would be appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by christian-bromann** [comment]
Looking into this I can't reproduce the problem at all. It also looks like your spec definition is wrong, it should be `tests/android/*.js` (remove double slash `//`). Happy to re-open this if a reproducible example can be provided.
