### ISSUE TITLE
How to handle user identification request popup in firefox

### ISSUE THREAD

**Issue by kundarsowjanya** [webdriverio/webdriverio#9708]
### Is your feature request related to a problem?

Hi, 

I'm using browserName as firefox in config file  and when I run testcase , user identification request popup is coming in firefox, each time I need to click on yes to execute testcase, else all testcase will fail. Is there anyway I can handle this scenario.

### Describe the solution you'd like.

I don't want to see this popup, once I run testcase it should redirect to application instead of this popup.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
> user identification request popup is coming in firefox, each time

Can you explain what this popup is or reference to docs?

**Comment by christian-bromann** [comment]
Closing as there hasn't been any further information provided.
