### ISSUE TITLE
Test report is failed to write in case of folder does not exist in project root

### ISSUE THREAD

**Issue by Pashokus** [webdriverio/webdriverio#971]

**Comment by christian-bromann** [comment]
@Pashokus could you please be a bit more specific?

**Comment by Pashokus** [comment]
I have specified a path for the reporter, like this:
 reporterOptions: {
        outputDir: './reports/'
}

When I run my tests, writing reports fails due to error: 'folder doesn't exist'
Could you add a functionality that can create a folder before writing reports?

**Comment by christian-bromann** [comment]
the junit reporter should create that outputDir if not existing (see https://github.com/webdriverio/wdio-junit-reporter/blob/master/lib/reporter.js#L102). Please update to v4 and use this reporter.
