### ISSUE TITLE
Is there a way to customize the picture name generated by test runner?

### ISSUE THREAD

**Issue by iamusenix** [webdriverio/webdriverio#972]
I was using test runner and want to take screenshots for errors. But the generated file name is something like 

"ERROR_chrome.any_2015-12-30T08-53-54.337Z.png"

I want to use customized name, at least to add spec name in it. I only found the 'screenshotPath' property in config file. Is there any chance to customize the name? Thanks.

**Comment by christian-bromann** [comment]
Nope, there is no way to customise the screenshot name. I am not sure how to make that customisable. How would you like to name these screenshots?

**Comment by iamusenix** [comment]
Thanks for you quick response. 
I used to save screenshots by catching any exceptions when working with 1.0.  I created a folder for target host and timestamp, and then named the file with test case name. For example, 

'localhost/2015-12-31-09:23/this is a login case.png'

So I can match the screenshots and corresponding failed cases easily.
It would be great if we can customize the name and path. 

Also I noticed there is a hook 'expectationResultHandler' for jasmine providing an opportunity to save screenshots when an assertion failed. If there is any hook for selenium server error, I can save screenshots in this hook by myself.

**Comment by christian-bromann** [comment]
I guess it makes sense to have a file name that corresponds to the test name since the creation timestamp is saved anyway as meta data. In v4 there will be an `onError` hook you can use to do anything if a command fails.

**Comment by iamusenix** [comment]
@christian-bromann Thanks for your comments and looking forward to V4. :)

**Comment by christian-bromann** [comment]
I think the best way to achieve what you want here is to implement an own service that either creates the screenshots or grabs them from the selenium response in the onError hook. The way this (`ERROR_chrome.any_2015-12-30T08-53-54.337Z.png`) is generated doesn't allow us to get any information about the test run (it's not in the scope of the testrunner). I believe using it makes more sense if you use WebdriverIO in standalone mode.
