### ISSUE TITLE
No types for new WebdriverBidi protocol

### ISSUE THREAD

**Issue by MarcAntoineNiggemann** [webdriverio/webdriverio#9726]
Hi,
I am trying to use new WebdriverBidi commands, but there is no type to declare those new commands, hence not available in a typescript program.
Checked PR https://github.com/webdriverio/webdriverio/pull/8505 but no type for the new commands found.

Can we have new types for those new commands ?
Thanks :)

Regards,
Marc-Antoine

**Comment by christian-bromann** [comment]
Thanks for reporting!

This is indeed weird. Everything is suppose to be set-up to register the types for `send` and `sendAsync`.

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!
