### ISSUE TITLE
[🐛 Bug]: Serenity WebdriverIO v8 adoption moduleResolution issues

### ISSUE THREAD

**Issue by jan-molak** [webdriverio/webdriverio#9729]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.3.3

### Node.js Version

16.18.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
Not relevant
```

### What happened?

I'm working on introducing support for WebdriverIO v8 to [Serenity/JS](https://github.com/serenity-js/serenity-js) and face quite a few issues related to WebdriverIO type definitions/ESM setup. Unfortunately, those issues are currently blocking me from supporting WebdriverIO v8.

Here's some background, as per my [conversation on Gitter](https://gitter.im/webdriverio/webdriverio?at=63e2a4d26fc5ff38e451658b) with @christian-bromann:

- Serenity/JS is a Node.js framework written in TypeScript and relying on CommonJS and Node module resolution (for now; I wanted to upgrade WDIO to v8 before considering migrating to ESM)
- [`@serenity-js/webdriverio` module](https://github.com/serenity-js/serenity-js/tree/main/packages/webdriverio) providing support for integrating with WebdriverIO relies on several WebdriverIO APIs that you'll find referenced [on the `features/webdriverio-8`](https://github.com/serenity-js/serenity-js/tree/features/webdriverio-8/packages/webdriverio/src/screenplay/models) branch I've prepared to work on the upgrade. 
- In particular, Serenity/JS relies on:
  - `Browser` and `Element` types from `webdriverio` in [`src/screenplay`](https://github.com/serenity-js/serenity-js/tree/features/webdriverio-8/packages/webdriverio/src/screenplay)
  - `@wdio/types` and `@wdio/reporter` in [`src/adapter`](https://github.com/serenity-js/serenity-js/tree/features/webdriverio-8/packages/webdriverio/src/adapter)

Serenity/JS WebdriverIO module is compiled using the following [effective `tsconfig.json`](https://github.com/serenity-js/serenity-js/blob/features/webdriverio-8/packages/webdriverio/tsconfig.json):
```json
{
  "compilerOptions": {
    "target": "es2019",
    "lib": [
      "es2019",
      "dom"
    ],
    "module": "commonjs",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "forceConsistentCasingInFileNames": true,
    "noEmitOnError": false,
    "noImplicitOverride": false,
    "noImplicitReturns": true,
    "pretty": true,
    "removeComments": false,
    "types": [
      "node"
    ]
  }
}
```

It also relies on the following WebdriverIO modules, as you can see in its [`package.json`](https://github.com/serenity-js/serenity-js/blob/features/webdriverio-8/packages/webdriverio/package.json):
```
    "@wdio/cli": "^8.3.3",
    "@wdio/devtools-service": "^8.3.3",
    "@wdio/dot-reporter": "^8.3.0",
    "@wdio/local-runner": "^8.3.3",
    "@wdio/mocha-framework": "^8.3.0",
    "@wdio/reporter": "^8.3.0",
    "@wdio/spec-reporter": "^8.3.0",
    "@wdio/types": "^8.3.0",
    "webdriverio": "^8.3.3"
```

My understanding is that WebdriverIO v8 is designed to support both ESM and CommonJS-compatible consumers. 

However, with the above setup, I'm getting the following compilation error, as you can see in my [CI build on GitHub](https://github.com/serenity-js/serenity-js/actions/runs/4119757238/jobs/7113779569):

```
node_modules/webdriverio/node_modules/webdriver/build/types.d.ts:1:23 - error TS1452: 'resolution-mode' assertions are only supported when `moduleResolution` is `node16` or `nodenext`.

1 /// <reference types="node" resolution-mode="require"/>
```

The error is raised against:
```
     2  node_modules/@wdio/reporter/build/index.d.ts:1
     4  node_modules/@wdio/types/build/Options.d.ts:1
     2  node_modules/@wdio/types/build/Reporters.d.ts:1
     1  node_modules/@wdio/types/build/Services.d.ts:1
     1  node_modules/@wdio/types/build/Workers.d.ts:1
     1  node_modules/webdriverio/build/commands/browser/savePDF.d.ts:1
     1  node_modules/webdriverio/build/commands/browser/saveRecordingScreen.d.ts:1
     1  node_modules/webdriverio/build/commands/browser/saveScreenshot.d.ts:1
     1  node_modules/webdriverio/build/commands/element/saveScreenshot.d.ts:1
     1  node_modules/webdriverio/build/types.d.ts:1
     1  node_modules/webdriverio/build/utils/interception/devtools.d.ts:1
     1  node_modules/webdriverio/build/utils/interception/types.d.ts:1
     1  node_modules/webdriverio/node_modules/devtools/build/types.d.ts:1
     1  node_modules/webdriverio/node_modules/webdriver/build/bidi.d.ts:1
     2  node_modules/webdriverio/node_modules/webdriver/build/request/index.d.ts:1
     1  node_modules/webdriverio/node_modules/webdriver/build/types.d.ts:1
```

It feels like the issue is caused by the following assertion present in WebdriverIO dependencies:

```
/// <reference types="node" resolution-mode="require"/>
```

As per the error message, it seems like a consumer module **must** use `moduleResolution` of `node16`/`nodenext` in order to use WebdriverIO v8: 
```
error TS1452: 'resolution-mode' assertions are only supported when `moduleResolution` is `node16` or `nodenext`.
```
However, switching to [`nodenext`](https://www.typescriptlang.org/tsconfig#moduleResolution) would force Serenity/JS and presumably all _its consumers_ to using [Node ESM](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#esm-nodejs).

### What is your expected behavior?

I'd expect WebdriverIO v8 to support both CJS and ESM consumers.

Please feel free to point out any mistakes I might have made when attempting to migrate to v8 :-)

### How to reproduce the bug.

See https://github.com/serenity-js/serenity-js/pull/1493

### Relevant log output

```typescript
See checks for https://github.com/serenity-js/serenity-js/pull/1493
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> I'd expect WebdriverIO v8 to support both CJS and ESM consumers.

We should make clear here that WebdriverIO supports both when it comes to executing tests. Tests can be written in CJS and as long as they get executed with `@wdio/cli` they can be run. Your scenario is less of a consumer and more adopter I guess.

I am not sure what needs to be done to loose the strictness on `moduleResolution` or if this is even possible. Every hints or contributions are welcome. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by jan-molak** [comment]
> > I'd expect WebdriverIO v8 to support both CJS and ESM consumers.

> We should make clear here that WebdriverIO supports both when it comes to executing tests. Tests can be written in CJS and as long as they get executed with @wdio/cli they can be run. Your scenario is less of a consumer and more adopter I guess.

Yes, that's fair enough. I think this issue would affect projects using WebdriverIO as a library. Thank's for clarifying the title.

> I am not sure what needs to be done to lose the strictness on moduleResolution or if this is even possible. 

Yeah, I'm not sure either. I've tried to hack the `@wdio/*` modules locally to remove the `'resolution-mode'` assertions, and that got loaded correctly. 

However unrelated to this issue, I then hit issues with Mocha's ESM loader, which attempts to load every file as an ESM module and [falls back to CJS only when ESM fails](https://github.com/mochajs/mocha/blob/202e9b8b4d1b6611c96d95d631c49d631d88c827/lib/nodejs/esm-utils.js#L37-L82). For reasons I don't fully understand (yet), making Serenity/JS depend on WDIO 8 makes Mocha use the ESM loader, which doesn't work with TypeScript.

I also noticed that quite a few `.d.ts` files in WDIO8 have duplicate `/// <reference types="node" resolution-mode="require"/>` lines at the top. 

Feels like a bit of a rabbit hole!

**Comment by SCG82** [comment]
@jan-molak Can you try https://github.com/webdriverio/webdriverio/pull/9736?

**Comment by jan-molak** [comment]
Hey @SCG82 - many thanks for picking this up. Unfortunately, and unless I'm missing something, it seems like the issue is still present in the latest version:

```
       node_modules/webdriverio/node_modules/webdriver/build/types.d.ts:1:23 - error TS1452: 'resolution-mode' assertions are only supported when `moduleResolution` is `node16` or `nodenext`.
       
       1 /// <reference types="node" resolution-mode="require"/>
```

```
       Errors  Files
            2  node_modules/@wdio/reporter/build/index.d.ts:1
            4  node_modules/@wdio/types/build/Options.d.ts:1
            2  node_modules/@wdio/types/build/Reporters.d.ts:1
            1  node_modules/@wdio/types/build/Services.d.ts:1
            1  node_modules/@wdio/types/build/Workers.d.ts:1
            1  node_modules/webdriverio/build/commands/browser/savePDF.d.ts:1
            1  node_modules/webdriverio/build/commands/browser/saveRecordingScreen.d.ts:1
            1  node_modules/webdriverio/build/commands/browser/saveScreenshot.d.ts:1
            1  node_modules/webdriverio/build/commands/element/saveScreenshot.d.ts:1
            1  node_modules/webdriverio/build/types.d.ts:1
            1  node_modules/webdriverio/build/utils/interception/devtools.d.ts:1
            1  node_modules/webdriverio/build/utils/interception/types.d.ts:1
            1  node_modules/webdriverio/node_modules/devtools/build/types.d.ts:1
            1  node_modules/webdriverio/node_modules/webdriver/build/bidi.d.ts:1
            2  node_modules/webdriverio/node_modules/webdriver/build/request/index.d.ts:1
            1  node_modules/webdriverio/node_modules/webdriver/build/types.d.ts:1
```

Here's the build log - https://github.com/serenity-js/serenity-js/actions/runs/4156784424/jobs/7190810475

I'm wondering if specifying [module type as `ESNext` in WebdriverIO](https://github.com/webdriverio/webdriverio/pull/9736/files#diff-06e365ef3b4aed8cfd86bfa9f3af5567698f63a5ee88a9ea6ac555308e1ad402R15) makes TypeScipt produce those resolution assertions?

@christian-bromann - would you mind re-opening this ticket? Or would you like me to raise a new one?

**Comment by SCG82** [comment]
@christian-bromann The published package shouldn't have `resolution-mode` (they do). When building locally (for example `webdriver/build/types.d.ts`) I'm not seeing `resolution-mode` in the `reference-type` triple-slash directives.

**Comment by SCG82** [comment]
@jan-molak You'll most likely need to add `"skipLibCheck": true` to your project's tsconfig

**Comment by jan-molak** [comment]
Thanks for getting back to me, @SCG82.

`skipLibCheck` works to mask the compilation issue, but with that, I'm hitting a problem with Mocha trying to load WDIO code as ESM within Serenity tests

```
 TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/jan/Projects/serenity-js/serenity-js/packages/webdriverio/spec/adapter/reporter/BrowserCapabilitiesReporter.spec.ts
```
the above error comes from a spec file, which loads the [implementation file](https://github.com/serenity-js/serenity-js/blob/ebe1ca57bb98f09bc4554f32e87f44a0dbce2c22/packages/webdriverio/src/adapter/reporter/BrowserCapabilitiesReporter.ts#L4-L5) that relies on:
```typescript
import Reporter from '@wdio/reporter';
import type { Capabilities, Options, Reporters } from '@wdio/types';
```

This issue, I think, is caused by how [Mocha's file loader works](https://github.com/mochajs/mocha/blob/202e9b8b4d1b6611c96d95d631c49d631d88c827/lib/nodejs/esm-utils.js#L37-L82), trying to load ESM version first and then falling back to commonjs only when ESM fails. If a module exposes both CJS and ESM versions under the same path (e.g. `@wdio/reporter`), this mechanism doesn't seem to work.

Perhaps this problem could be solved if WDIO shipped two separate versions of transpiled files, available at separate paths - e.g. `@wdio/reporter/esm` and `@wdio/reporter/cjs`, which would allow consumer libraries and frameworks to load the appropriate version?

I think Puppeteer follows this convention and this is something I'm considering doing for Serenity/JS:

<img width="327" alt="Screenshot 2023-02-12 at 22 16 45" src="https://user-images.githubusercontent.com/1089173/218340580-a64f1b17-e4b8-43d9-9bfd-d78e456a9f03.png">

Is this something worth investigating for WDIO?
