### ISSUE TITLE
cucumber config

### ISSUE THREAD

**Issue by benjaminlees** [webdriverio/webdriverio#973]
In `webdriverio/lib/frameworks/cucumber.js` line 226 the method `Cucumber.Cli.Configuration(execOptions)` is called but a second argument is not passed to it.
However in `cucumber/lib/cucumber/cli/configuration.js` line 8 there is an if statement `if (args.length >0)` where args is the second argument being passed to the cucumber configuration function. 

As args is undefined I am getting the error ` ERROR: Cannot read property 'length' of undefined`.

**Comment by christian-bromann** [comment]
Please use Cucumber v0.5.3. We will update the cucumber version with the new WebdriverIO release. I will an own package (https://github.com/webdriverio/wdio-cucumber-framework).
