### ISSUE TITLE
All the testcases are failing if I use headless option inside capabilities

### ISSUE THREAD

**Issue by kundarsowjanya** [webdriverio/webdriverio#9738]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [{
        browserName: 'MicrosoftEdge',
        'ms:edgeOptions': {
            args: ['--headless']
        }
    }],
```

### What happened?

All  testcases are failing with headless option, without that it's working fine

### What is your expected behavior?

testcases should pass even with headless option, I need this for CI/CD setup

### How to reproduce the bug.

    capabilities: [{
        browserName: 'MicrosoftEdge',
        'ms:edgeOptions': {
            args: ['--headless']
        }
    }],

### Relevant log output

```typescript
assertionError_waitUntil condition failed with the following reason: Can't call getText on element with selector 
") doesn't exist
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
I think the error says it all. The element you are selecting does not exist. Not sure how headless is connected to this. Note that the resolution of a headless browser is smaller than with viewport. Please use the debugging capabilities of WebdriverIO to debug this. There is nothing much we can do from the contributor side.

**Comment by kundarsowjanya** [comment]
Actually, I'm getting this error only when I use headless option but without that it is working fine, I want to integrate testcases in CI/CD for that , I'm using headless option, but getting this error. Is there anyway I can fix it?

**Comment by christian-bromann** [comment]
> Is there anyway I can fix it?

Sure, as I mentioned above, try to debug your problem by running your tests headless on your machine.

**Comment by erwinheitzman** [comment]
I agree with Christian as a lot of people are running this in headless. If something major would be broken in running headless we would definitely know it imo.
