### ISSUE TITLE
Is it necessary to provide headless capability for each browser if we want to run webdriverio testcases in jenkins?

### ISSUE THREAD

**Issue by kundarsowjanya** [webdriverio/webdriverio#9740]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Other

### Description of the improvement / report

is it necessary to provide headless capability for each browser if we want to run webdriverio testcases in jenkins?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Please read the docs: https://webdriver.io/docs/capabilities/#run-browser-headless

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
