### ISSUE TITLE
[🐛 Bug]: log.map is not a function @wdio-runner

### ISSUE THREAD

**Issue by MadSandwich** [webdriverio/webdriverio#9761]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

On both latest LTS and latest

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [{
        maxInstancesPerCapability: +process.env.MAX_INSTANCES,
        browserName: process.env.BROWSER_NAME,
        acceptInsecureCerts: true,
        'goog:chromeOptions': {
            w3c: false,
            args: [
                '--incognito',
                `--window-size=${process.env.WINDOW_WIDTH},${process.env.WINDOW_HEIGHT}`,
                '--disable-dev-shm-usage',
                '--disable-gpu',
                '--no-sandbox',
                `${(process.env.HEADLESS === 'true') ? '--headless' : '--start-fullscreen'}`
            ],
            'excludeSwitches': ['enable-automation'],
            'prefs': {
                'download.default_directory': process.env.DOWNLOAD_DIRECTORY
            }
        }
    }]
```

### What happened?

Sometimes `_fetchDriverLogs` function return `string` for logTypes instead of `array` / `array of objects` that resulting in ERROR that failing execution even if all steps / features pass successfully.
![CDViewer_YVrX7nkca8](https://user-images.githubusercontent.com/57759145/218476645-64cd2e8d-3ffc-4d2c-aa8c-a3610512b9dd.png)
![CDViewer_Oed8Rr0tXI](https://user-images.githubusercontent.com/57759145/218476652-f6e1eac1-f01a-4372-b4b3-c6154ed610d6.png)

### What is your expected behavior?

Do not fail test execution if ERROR received for log generation.

### How to reproduce the bug.

Unfortunately, I wasn't able to find out a simple reproducible example.

### Relevant log output

I add some console.logs to define the problem

When I receive a string instead of object:
```typescript
[0-0]  Error:  logs.map is not a function
[0-0] logs type string
[0-0] logs content /session/e8369eff6c7895b05b1777c4cec98b34/se/log
[0-0] FAILED in chrome - file:<path to file>
Print exitCode after test execution: 1
```
____________________________________________________

When I receive an object as it expected:
```typescript
[0-0] logTypes [ 'browser', 'driver' ]
[0-0] logs type object
[0-0] logs content [
[0-0]   {
[0-0]     level: 'WARNING',
[0-0]     message: 'virtual void DevToolsClientImpl::AddListener(DevToolsEventListener *) subscribing a listener to the already connected DevToolsClient. Connection notification will not arrive.\n',
[0-0]     timestamp: 1676292984987
[0-0]   }
[0-0] ]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by MadSandwich** [comment]
As a simple solution, we can just not capture logs if only session is retrieved:
```           if (!logs || logs.length === 0 || typeof logs === 'string') {
                return;
            }```

**Comment by MadSandwich** [comment]
@christian-bromann it doesn't return an object of string, just simple string. Or I didn't get your question?

**Comment by BorisOsipov** [comment]
@MadSandwich Christian means which driver do you use e.g. chromedriver\winappdriver\etc.

**Comment by MadSandwich** [comment]
> @MadSandwich Christian means which driver do you use e.g. chromedriver\winappdriver\etc.

Selenium-standalone service, Chromedriver only.

**Comment by BorisOsipov** [comment]
@MadSandwich any chance to share repo with reproducible example?

**Comment by MadSandwich** [comment]
@BorisOsipov as I write in the description I really can't share my real repo in which I found and debug this issue and unfortunately wasn't able to reproduce it with simple scenario. I would try tomorrow to somehow recreate this, but for now I didn't have any to share

**Comment by BorisOsipov** [comment]
@MadSandwich Thank you. I fully understand that you cannot provide your production code to reproduce the issue. We would greatly appreciate any reproducible example that you can provide.
