### ISSUE TITLE
[🐛 Bug]: `expect` fn with broken TS definitions

### ISSUE THREAD

**Issue by MattFerreira18** [webdriverio/webdriverio#9764]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.3.5

### Node.js Version

18.14.0

### Mode

WDIO Testrunner

### What happened?

 Creating a new project for React components testing, the `expect` function, imported from `@wdio/globals` package, has your TS definitions broken, not showing the suggested fns that can be used to create the assertion.

![image](https://user-images.githubusercontent.com/52766091/218554968-ab6f1620-8801-4bc3-935c-cd1c6b24252c.png)

### How to reproduce the bug.

Using the CLI, create a new project for React component testing. Make a component testing, and try to make use of the `expect` fn TS definitions for autocomplete.

### Relevant log output

```typescript
.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for filing the issue.

Just out of curiosity, did you add `@wdio/globals/types` to your tsconfig `types` property? Does the issue resolve adding `/// <reference types="@wdio/globals/types" />`?

I am off this week but can look into a fix next week.

**Comment by MattFerreira18** [comment]
> Thanks for filing the issue.
> 
> Just out of curiosity, did you add `@wdio/globals/types` to your tsconfig `types` property? Does the issue resolve adding `/// <reference types="@wdio/globals/types" />`?
> 
> I am off this week but can look into a fix next week.

 I have tested here and the two ways worked correctly. Particularly I didn't know it was possible to specify the package types. Thanks for the help 😄.

**Comment by christian-bromann** [comment]
I wonder why it is not automatically picked up like other packages would. Keeping the issue open for investigations, if anyone has a clue, please let us know.

**Comment by vparlah** [comment]
Hey there! I ran into a same problem with my project today after updating some wdio packages to version 8.3.9. Important to note, I generated a new package-lock.json after the update.

After looking into it a bit, it seemed like the issue was caused by some third-party dependencies.

I was able to solve the problem by reverting to the previous package-lock.json state, with only the new wdio packages installed. This fixed the issue for me.


**node js  version:** 18.12.1
**dependencies:** 
``` json 
  "dependencies": {
    "@faker-js/faker": "^7.6.0",
    "@wdio/appium-service": "^8.3.9",
    "@wdio/cli": "^8.3.9",
    "@wdio/globals": "^8.3.9",
    "@wdio/local-runner": "^8.3.9",
    "@wdio/mocha-framework": "^8.3.0",
    "@wdio/spec-reporter": "^8.3.0",
    "axios": "^1.2.3",
    "wdio-wait-for": "^3.0.1"
  },
  "devDependencies": {
    "@types/mocha": "^10.0.1",
    "@typescript-eslint/eslint-plugin": "^5.48.2",
    "@typescript-eslint/parser": "^5.48.2",
    "eslint": "^8.32.0",
    "eslint-config-airbnb-typescript": "^17.0.0",
    "eslint-config-prettier": "^8.6.0",
    "eslint-plugin-jsonc": "^2.6.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-wdio": "^8.0.14",
    "jsonc-eslint-parser": "^2.1.0",
    "prettier": "^2.8.3",
    "ts-node": "^10.9.1",
    "typescript": "^4.9.4"
  }

```

**Comment by christian-bromann** [comment]
> **UPDATE:** No more issue this morning 🤔

Thanks for confirming I will go ahead and close then. Let me know if you still experience any issues and I am happy to re-open.
