### ISSUE TITLE
Passing commandline arguments to browser

### ISSUE THREAD

**Issue by kiraLinden** [webdriverio/webdriverio#977]
I'm running into https://github.com/sgentle/phantomjs-node/issues/204 and would like to know how to pass in a command line argument when phantomjs is invoked.

I tried doing 
```
before_script:
  - "npm install -g bower"
  - "cd test/site/www && bower install && cd ../../../"
  - "phantomjs --ssl-protocol=any --webdriver=4444 2>&1 >/dev/null &"
  - "2>/dev/null 1>/dev/null python -m SimpleHTTPServer 8080 &"
```

in .travis.yml but it doesn't seem to be taking it

**Comment by christian-bromann** [comment]
Make sure travis uses the latest phantomjs version (>v1.9.2) and use these capabilities:

```js
desiredCapabilities: {
   browserName: 'phantomjs',
   "phantomjs.cli.args" : ["--ignore-ssl-errors=yes"]
}
```
