### ISSUE TITLE
elementSendKeys doesn't take string array of KEYS

### ISSUE THREAD

**Issue by Atabic** [webdriverio/webdriverio#9770]
Hey team, We recently encountered a problem where we want META + ENTER on an element but cannot do that. Kindly update this so we can use this function to achieve something like that. 

Also, another thing I noticed is that the text you getting as a key is then converted to an array, Is this intentional?
``` let typeInput: string[] = [text] ```

I would love to create a PR for this if you guys are okay with this change
Reference to the file is attached below:
https://github.com/webdriverio/webdriverio/blob/948a4993962f18a6cba4c0fb48a58b176b9fb57c/packages/devtools/src/commands/elementSendKeys.ts#L19

**Comment by praveendvd** [comment]
have you tried https://webdriver.io/docs/api/browser/keys/

browser.keys

**Comment by christian-bromann** [comment]
The solution outlined by @praveendvd is correct, you can also use the actions API, e.g.:

```ts
    import { Key } from 'webdriverio'

    await browser.action('key')
      .down(Key.Command).down(Key.Enter)
      .pause(10)
      .up(Key.Command).up(Key.Enter)
      .perform()
```

**Comment by Atabic** [comment]
What if I want to achieve the same with elementSendKeys? It does not take an array of keys. Can we update that too?
Check this: https://v7.webdriver.io/docs/api/jsonwp/#elementsendkeys 
You guys implemented that in previous versions.

**Comment by christian-bromann** [comment]
`elementSendKeys` is a deprecated JSONWireProtocol command which isn't support it many environments anymore. There is a [`keys`](https://webdriver.io/docs/api/browser/keys) command which you can use.

**Comment by Atabic** [comment]
This works but we have to focus on the element first and then perform keys. Why the elementSendKeys doesn't work with multiple keys? Also, we want to send keys to an element directly and not by browser, What's the appropriate way to do that?

Also, Webprotocol is the alternative to JSONWireProtocol and it also contains the same method.
https://webdriver.io/docs/api/webdriver/#elementsendkeys

**Comment by christian-bromann** [comment]
> Why the elementSendKeys doesn't work with multiple keys?

This has been changed from JSONWP to WebDriver, latter only takes a string rather than an array of strings, you may can try something like this:

```js
import { Key } from 'webdriverio'

await $('input').setValue(`Foo${Key.Space}Bar`)
```

But not sure if the special character is recognised.

> Also, we want to send keys to an element directly and not by browser, What's the appropriate way to do that?

To just set a simple value, use `addValue` or `setValue`.
