### ISSUE TITLE
[🐛 Bug]: AppiumService driver TypeError: reset is not a function

### ISSUE THREAD

**Issue by DmytroChuchmaiBarges** [webdriverio/webdriverio#9772]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.3.9

### Node.js Version

16.19.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    clientApp: {
        capabilities: {    
            platformName: 'Android',
            'appium:deviceName': 'deviceName', 
            'appium:platformVersion': 'platformVersion',
            'appium:orientation': 'PORTRAIT',
            'appium:automationName': 'UiAutomator2',
            'appium:appPackage': 'my.app.package',
            'appium:appActivity': 'my.app.activity',
            'appium:noReset': false,
            'appium:newCommandTimeout': 240,
        }
    },
}
```

### What happened?

I need to reset an app between my cucumber features.
I'm running tests locally on android devices,
- Interactions with the app work fine when removing this command
- the app is pre-installed
- it used to work on the same appium version,
- I also tried 'appium:noReset': true capability, but it does not affect (should it?)

After **upgrading to v8** my tests started failing with **TypeError: clientApp.reset is not a function**
**Appium server logs** don't show this command, so it seams wdio does not send one.

### What is your expected behavior?

Android/iOS application should reset. As original appium should.

### How to reproduce the bug.

use: 
config.services = [
    [
        'appium',
        {
            logPath: 'tmp',
            command: 'appium',
            'pre-launch': true,
            'session-override': false,
        },
    ],
];

//mobile app test should contain in any part of the test scenario
await clientApp.reset();

### Relevant log output

```typescript
[MultiremoteBrowser #0-3] 1) Test registration form validation 
[MultiremoteBrowser #0-3] TypeError: clientApp.reset is not a function
[MultiremoteBrowser #0-3] TypeError: clientApp.reset is not a function
[MultiremoteBrowser #0-3]     at resetApps (file:///Users/user/src/testAutomation/tests/helpers/utils.js:57:104)
[MultiremoteBrowser #0-3]     at AuthenticationWorld.<anonymous> (file:///Users/user/src/testAutomation/tests/pg/hooks/sanity_hook.js:43:11)
[MultiremoteBrowser #0-3]     at async wrapPromiseWithTimeout (/Users/user/src/testAutomation/node_modules/@cucumber/cucumber/src/time.ts:63:10)
[MultiremoteBrowser #0-3]     at async Object.run (/Users/user/src/testAutomation/node_modules/@cucumber/cucumber/src/user_code_runner.ts:86:16)
[MultiremoteBrowser #0-3]     at async Object.run (/Users/user/src/testAutomation/node_modules/@cucumber/cucumber/src/runtime/step_runner.ts:50:20)
[MultiremoteBrowser #0-3]     at async TestCaseRunner.invokeStep (/Users/user/src/testAutomation/node_modules/@cucumber/cucumber/src/runtime/test_case_runner.ts:130:12)
[MultiremoteBrowser #0-3]     at async TestCaseRunner.runHook (/Users/user/src/testAutomation/node_modules/@cucumber/cucumber/src/runtime/test_case_runner.ts:251:12)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by DmytroChuchmaiBarges** [comment]
It seams that this command was deprecated, any ideas how to handle such case?

**Comment by praveendvd** [comment]
@DmytroChuchmaiBarges  

could you add : 

/session/:session_id/appium/app/reset

to this file and see if its working for you  

https://github.com/webdriverio/webdriverio/blob/93d2894a6119891d47b125a4160438f39813cb8e/packages/wdio-protocols/src/protocols/appium.ts

**Comment by DmytroChuchmaiBarges** [comment]
@praveendvd 
Thank you for a fast response,
I added following code:

```
clientApp.addCommand('reset', command('POST', '/session/:sessionId/appium/app/reset', {
        command: 'reset',
        description: 'application reset',
        ref: 'http://appium.io/docs/en/commands/device/app/reset-app/',
        parameters: []
    }));
```
and it does work

Can I expect it to be fixed in next appium service versions?

**Comment by praveendvd** [comment]
I will take it up and raise a PR , thank you

**Comment by praveendvd** [comment]
@christian-bromann any guess why it would have got removed from the file ?

**Comment by christian-bromann** [comment]
> any guess why it would have got removed from the file ?

because the Appium team confirmed that this command is deprecated and is not working reliably. They suggest to use other available commands, e.g. `terminateApp` and `launchApp`.

**Comment by praveendvd** [comment]
@christian-bromann  so we don't need a fix ? This command is still mentioned in appium page

**Comment by christian-bromann** [comment]
> so we don't need a fix ?

No.

> This command is still mentioned in appium page

Yes, but it will be deprecated eventually. The team mentioned to me that they would not recommend to use the command.
