### ISSUE TITLE
Create a directory that does not exist

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#978]
```js
reporterOptions: {
	outputDir: './cache/tests/reports'
},

screenshotPath : './cache/tests/shots',

logOutput: './cache/tests/logs'
```

```js
Error: ENOENT: no such file or directory, open '/Users/***/cache/tests/reports/WDIO.xunit.firefox.35084.xml'
    at Error (native)
```

I think you should create a directory that does not exist. I don't want care about it....

**Comment by monolithed** [comment]
Of course I can do something ugly like:

```js
onPrepare: function () {
	child_process.execSync('mkdir -p ./cache/tests/{reports,shots,logs}');
}
```

**Comment by christian-bromann** [comment]
Good point.

**Comment by ryancat** [comment]
I tried with the most recent version as of today (4.10.2). With relative setting like `./errorShots/` in wdio.conf.js, I still get the error for no such directory. I have to manually create it so that the error screenshots can be saved.
