### ISSUE TITLE
Add `.fill(selector, data, submit)` 

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#980]
Fills the fields of a form with given values and optionally submits it. 
Fields are referenced by their name attribute.

```js
.setValue('input[name="username"]', '')
.setValue('input[name="password"]', '')
.click('input[name="submit"]')
```

Vs:

```js
.fill('[name="form"]', { username: '', password: ''}, true);
```

The latest example more elegant and structured.

PS: [CasperJS#fill](http://docs.casperjs.org/en/latest/modules/casper.html#fill),  [Zombie](https://github.com/assaf/zombie)

**Comment by christian-bromann** [comment]
I see the convenience for that but the list of commands is pretty long by now so I don't know if this makes sense if you already can do it if the current commands. I will leave it open in case anyone +1's it.

**Comment by christian-bromann** [comment]
For the sake of not bloating up the API I will not add this command. Feel free to create a service like [this](https://github.com/webdriverio/wdio-sauce-service) example that offers to add such a command (and maybe more that are similar to CapserJSs API).
