### ISSUE TITLE
ERROR @wdio/selenium-standalone-service: Error: not found: java

### ISSUE THREAD

**Issue by kundarsowjanya** [webdriverio/webdriverio#9804]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
chrome
```

### What happened?

I'm running my testcases in jenkins after npm install , when I try to run testcases I'm getting this error

**ERROR @wdio/selenium-standalone-service: Error: not found: java**

In local all testcases are working fine.
but in jenkins I'm facing this issue.

### What is your expected behavior?

test cases should work.

### How to reproduce the bug.

Getting ERROR @wdio/selenium-standalone-service: Error: not found: java, error in jenkins

### Relevant log output

```typescript
ERROR @wdio/selenium-standalone-service: Error: not found: java
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
I think the error is clear. If you decide to use the Selenium standalone server you need to ensure that Java is installed on that machine as it is a requirement.
