### ISSUE TITLE
ERROR webdriver: Request failed with status undefined due to TimeoutError: Timeout awaiting 'response' for 120000ms when running

### ISSUE THREAD

**Issue by kundarsowjanya** [webdriverio/webdriverio#9809]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [{
        browserName: 'MicrosoftEdge',
        browserVersion: 'latest',
        'ms:edgeOptions': {
            args: ['--headless']
        }
    }],
```

### What happened?

So if I use capabilities like this 

    capabilities: [{
        browserName: 'MicrosoftEdge',
        browserVersion: 'latest',
        'ms:edgeOptions': {
            args: ['--headless']
        }
    }],

I'm getting , Timeout error

webdriver: Request failed with status undefined due to TimeoutError: Timeout awaiting 'response' for 120000ms

suppose if I add capbilities
 capabilities: [{
        browserName: 'MicrosoftEdge',
        'ms:edgeOptions': {
            args: ['--headless']
        }
    }],

like this testcases will execute fine, If I specify browser version I'm getting this error, 

### What is your expected behavior?

testcases should work even after specifying version

   capabilities: [{
        browserName: 'MicrosoftEdge',
        browserVersion: 'latest',
        'ms:edgeOptions': {
            args: ['--headless']
        }
    }],

### How to reproduce the bug.

   capabilities: [{
        browserName: 'MicrosoftEdge',
        browserVersion: 'latest',
        'ms:edgeOptions': {
            args: ['--headless']
        }
    }],

### Relevant log output

```typescript
ERROR webdriver: Request failed with status undefined due to TimeoutError: Timeout awaiting 'response' for 120000ms when running
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> If I specify browser version I'm getting this error,

When running local tests the edgedriver picks the browser version that is available on your machine. This capability is usually only really useful when running against a browser grid.

I close this issue because it is not really related to WebdriverIO given that the driver has issues here providing the session. You might want to check the driver logs for more information on this problem.
