### ISSUE TITLE
Simplify some `wait*` methods

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#981]
| Method | Alternative
|---|---|
| **`waitForExist`** | `wait('input')` |
| **`waitForEnabled`** | `wait('input:enabled')` <br />`wait('input:disabled')`  |
| **`waitForSelected`** | `wait('input:checked')` <br />~~`wait('input:focus')`~~ <br />~~`wait('input:active')`~~ <br />~~`wait('input:target')`~~ |
| **`waitForText`** | `wait('input:empty')` |
| **`waitForValue`** | `wait('input:valid')` <br />`wait('input:invalid')` |
| **`waitForVisible`** | ~~`wait(':not([style*="display: none"])')` ?<br /> it can be provided via custom `:visible` pseudo-class ))~~  | — 
| **`waitUntil`** |   `wait(fn)` |
6 + 1 equivalent methods?
Please correct me if I'm wrong...

**Comment by christian-bromann** [comment]
Looks good but it will be hard when people use more complex selectors. For example if someone wants to check wait for an input with class X and name Y the selector would be: `wait('.X[name="Y"]:empty')` right? I guess if we enhance the [find element helper](https://github.com/webdriverio/webdriverio/blob/v4.0/lib/helpers/findElementStrategy.js) something like this would be possible for sure but it would require a different approach to transform the string into an xPath. Have you seen something like this somewhere else? In general I am in favor of streamlining commands as we have a bit too much of them.

**Comment by monolithed** [comment]
> it would require a different approach to transform the string into an xPath.

`:checked`,  `:enabled/:disabled`, `:empty` (IE 9.0+), `:valid/:invalid` (IE 10.0+) are standard pseudo-classes. 
What did you mean? Do you want to implement them for IE9-?
It seems we have to implement only `:visible` )

> Have you seen something like this somewhere else? 

`Nightmare`, `Zombie`,  `Protractor`, `navit`, `Capybara` have only one method `wait`. 
But no one has implemented `:visible`

**Comment by christian-bromann** [comment]
> are standard pseudo-classes.

in CSS3. Others are: `[foo^="bar"], [foo$="bar"], [foo*="bar"], :root, :nth-child(), :nth-last-child(), nth-of-type, nth-last-of-type(), :last-child, :first-of-type, :last-of-type, :only-child, :only-of-type, :empty, :target, :enabled, :disabled, :checked, :not(), ~`

The problem is that I don't know if all these are automatically supported in Selenium as well then. I mean at the end I could just crop the `:visible`/`:valid` etc part from the selector and run the actual command that is currently implemented.

**Comment by christian-bromann** [comment]
For the sake of not bloating up the API I will not add this command. Feel free to create a service like this example that offers to add such a command (and maybe more that are similar to CapserJSs API).
