### ISSUE TITLE
[🐛 Bug]: Component Testing: receive error events from Bidi

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#9810]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

18

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
[{
    browserName: 'chrome'
}]
```

### What happened?

Transplanted the [react example](https://github.com/webdriverio/component-testing-examples/tree/main/react-typescript-vite) from the examples repository to team project of mine.

Received the error as the logs show.

### What is your expected behavior?

Tests should run.

### How to reproduce the bug.

Still trying to figure this out but transplanting the react example for component testing to my project leads to this.
I´ve ruled out dependencies being the problem by having all the same dependencies installed on the example project and it stills runs.

### Relevant log output

```typescript
@wdio/local-runner: Run worker command: run
RUNNING in chrome - file:///tests/HelloWorld.test.tsx
INFO webdriver: Initiate new session using the WebDriver protocol
INFO webdriver: [POST] http://localhost:9515/session
INFO webdriver: DATA {
  capabilities: { alwaysMatch: { browserName: 'chrome' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'chrome' }
}
WARN chromedriver: [1677059807.228][WARNING]: virtual void DevToolsClientImpl::AddListener(DevToolsEventListener *) subscribing a listener to the already connected DevToolsClient. Connection notification will not arrive.
INFO @wdio/runner: Run spec file file:///Users/redacted/repo/tests/HelloWorld.test.tsx for cid 0-0
INFO webdriver: COMMAND navigateTo("http://localhost:60261/0-0/test.html?spec=/Users/redacted/repo/tests/HelloWorld.test.tsx")
INFO webdriver: [POST] http://localhost:9515/session/cb2748fd48bfb1c8b79db33129694549/url
INFO webdriver: DATA {
  url: 'http://localhost:60261/0-0/test.html?spec=/Users/redacted/repo/tests/HelloWorld.test.tsx'
}
NFO @wdio/browser-runner:plugin: Received request for: /0-0/test.html?spec=/Users/redacted/repo/tests/HelloWorld.test.tsx
INFO webdriver: RESULT null
INFO webdriver: COMMAND executeScript(<fn>, <object>)
INFO webdriver: [POST] http://localhost:9515/session/0fef0afc284dae6036465c28b26ca420/execute/sync
INFO webdriver: DATA { script: 'fetchExecutionState(...) [1168 bytes]', args: [] }
INFO webdriver: RESULT {
  errors: [
    {
      filename: 'http://localhost:59432/node_modules/expect-webdriverio/lib/index.js',
      message: "Uncaught TypeError: Cannot read properties of undefined (reading 'extend')"
    }
  ],
  failures: null,
  hasViteError: false
}
Error:  Test failed due to following error(s):
- index.js: Uncaught TypeError: Cannot read properties of undefined (reading 'extend')
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Is this happening also when you run it within the component testing example repository? The error sounds like a problem with the module resolution likely with `expect` , I think the first step is to expose the stack trace here to know more. Can you provide a minimal reproducible example?

**Comment by nextlevelbeard** [comment]
Hey Christian, 
Having a hard time in general getting more output from these type of browser based errors that are the result of a `executeScript`, maybe this can be improved in the future, offering perhaps a more detailed stack trace?

FYI I've been migrating the project from CRA to Vite and have since stopped having an issue with this.

**Comment by christian-bromann** [comment]
> maybe this can be improved in the future, offering perhaps a more detailed stack trace?

Yes, I was planning to integrate the new Bidi capabilities to get all error events through the new protocol

**Comment by christian-bromann** [comment]
@nextlevelbeard can you verify that this error still occurs. We shipped a bunch of fixes to the browser runner to better detect errors in the bootstrap process. I will go ahead and close but happy to re-open if you still see this.
