### ISSUE TITLE
Test cases is not working in jenkins for edge configuration

### ISSUE THREAD

**Issue by kundarsowjanya** [webdriverio/webdriverio#9811]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
edge
```

### What happened?

I'm trying to run testcases in jenkins for edge browser but somehow I'm getting this error
```

WARN webdriver: Request failed with status 500 due to Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: cannot find msedge binary
16:59:46  [0-0] Build info: version: '4.4.0', revision: 'e5c75ed026a'

```

But for chrome it worked well. Could you please suggest the solution?

### What is your expected behavior?

test cases should execute in jenkins for edge.

### How to reproduce the bug.

For edge capability it;s not working in jenkins

### Relevant log output

```typescript
WARN webdriver: Request failed with status 500 due to Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: cannot find msedge binary
16:59:46  [0-0] Build info: version: '4.4.0', revision: 'e5c75ed026a'
 System info: host: 'dynamic-agent-26bf004e-8a22-4c33-9536-f9109b22e86f-d8ztz-20swr', ip: '100.67.1.152', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.147+', java.version: '11.0.17'
16:59:46  [0-0] Driver info: driver.version: unknown
16:59:46  [0-0] Build info: version: '4.4.0', revision: 'e5c75ed026a'
16:59:46  [0-0] System info: host: 'dynamic-agent-26bf004e-8a22-4c33-9536-f9109b22e86f-d8ztz-20swr', ip: '100.67.1.152', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.147+', java.version: '11.0.17'
16:59:46  [0-0] Driver info: driver.version: unknown
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> Could you please suggest the solution?

Try, `browserName: 'Microsoft Edge'` and ensure you have the browser installed on your Jenkins machine.

**Comment by kundarsowjanya** [comment]
Hi,
But I didn't install any browser in jenkins machine but still , I was able to run it for chrome, but for MicrosoftEdge and firefox it's not working and even I tried with webdriverio/selenium-standalone, docker image  with that also I was able to run it for chrome not for edge and firefox, Do I need to explicitly install these browsers in jenkins? If yes ,may I know the procedure to install browsers in jenkins please? OR Some document if available.

**Comment by christian-bromann** [comment]
> Do I need to explicitly install these browsers in jenkins?

Yes, WebdriverIO doesn't do this for you.

> If yes ,may I know the procedure to install browsers in jenkins please? OR Some document if available.

I am not to familiar with Jenkins but I am sure there are information on the internet about that.
