### ISSUE TITLE
[📖 Docs]: Depreciated Applitools Service Not Obviously Marked as Depreciated 

### ISSUE THREAD

**Issue by elisabeth-oliver-applitools** [webdriverio/webdriverio#9815]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Other

### Description of the improvement / report

Recently Applitools has depreciated the Applitools WDIO service in favor of the general sdk. 

This page https://v6.webdriver.io/docs/applitools-service.html is one of the first results when searching "wdio applitools" which causes confusion for some users as they attempt to implement this no longer supported service. 
I found similar documentation for [v5](https://v5.webdriver.io/docs/applitools-service.html) and [v7](https://v7.webdriver.io/docs/applitools-service/) of the documentation as well. 

I am aware these are out of date documentation, and that the current version (v8) correctly does not list the service, however, I was hoping there was some way we could remove these pages listing the depreciated documentation or more prominently mark them as depreciated to reduce confusion for users. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
I removed the page from the S3 bucket. It will take a while until it has propagated to the website and is being recrawled but it should hopefully do the trick.
