### ISSUE TITLE
Special characters removed using WDIO CLI

### ISSUE THREAD

**Issue by dtothefp** [webdriverio/webdriverio#982]
Submitting a string in my capabilities

`'dfp/FEOPS-24/FEOPS-10/FEOPS-18/ci-tests:e2e:debug'`

will result in this

`'dfp FEOPS 24 FEOPS 10 FEOPS 18 ci tests:e2e:debug'`

Not sure if this is somehow stripped out by the child process?

**Comment by christian-bromann** [comment]
How is this set in your config?

**Comment by dtothefp** [comment]
It is merged in as a property of capabilities for Browser Stack

https://www.browserstack.com/automate/capabilities

When I run tests through the karma browser stack launcher these characters are preserved so I figured it most likely is happening somewhere in Webdriver

**Comment by christian-bromann** [comment]
Just set the variable in the main configs (not in the capabilities). Then grab that data via: `browser.options.MY_DATA`

**Comment by dtothefp** [comment]
The problem isn't that I need the data but browser stack uses those properties to name/categorize my builds in the interface. Is here a way for me to escape the characters so they are not removed?

**Comment by christian-bromann** [comment]
Ok I am confused. What kind of data is that and where is it stored and what has it to do with Browserstack?

**Comment by dtothefp** [comment]
No problem....sorry I'm on an iPad right now so can't give you a good demo. If you look at the link https://www.browserstack.com/automate/capabilities browser stack accepts build, project and name as parameters for test metadata that groups tests in their ui. Essentially something is stripping out characters from these properties when I run Webdriver so in the browser stack ui the test grouping is not consitent with other tests I'm running in the same ci build that are run with another tool like karma. Hope that explains it

**Comment by christian-bromann** [comment]
I guess the only way to find out is to check the logs. WebdriverIO doesn't strip anything.

**Comment by christian-bromann** [comment]
Let's close this issue. I don't see that this has something to do with WebdriverIO. Feel free to reopen if not.

**Comment by dtothefp** [comment]
No problem, thanks for the info. Looks like this is a problem on the BrowserStack side
