### ISSUE TITLE
How to pass security.default_personal_cert in firefox capabilities ?

### ISSUE THREAD

**Issue by kundarsowjanya** [webdriverio/webdriverio#9858]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
   browserName: 'firefox'
}
```

### What happened?

I'm getting user identity popup in firefox while executing testcases . So I want to enable security.default_personal_cert . So

How to pass security.default_personal_cert in firefox capabilities ?

### What is your expected behavior?

How to pass security.default_personal_cert in firefox capabilities ?

### How to reproduce the bug.

Getting User identity popup when I hit url in testcase.

### Relevant log output

```typescript
Getting User identity popup when I hit url in testcase.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
This seems to be a configuration that can be set using the [Firefox Profile Service](https://webdriver.io/docs/firefox-profile-service). Let me know if there are any issues using it.
