### ISSUE TITLE
setValue / clearValue doesn't work, webdriver 8.3.2 with XCUITest

### ISSUE THREAD

**Issue by cervebar** [webdriverio/webdriverio#9859]
Environment:

WebdriverIO version: 8.3.2
Node.js version: v16.17.0
driver: XCUITest
testing on real device: iPhone SE 17.5.1
used via Appium 2
Xcode:14.2

Additional wdio packages used (if applicable): none
Config of WebdriverIO
```
 const optsLocalIOS = {
    path: '/wd/hub/',
    port: 4723,
    capabilities: {
        platformName: "ios",
        "appium:app": "/tmp/ipa-test",
        "appium:automationName": "XCUITest",
        "appium:xcodeOrgId": "myteamid",
        "appium:xcodeSigningId": "iPhone Developer",
        "appium:udid":"auto",
        "appium:showXcodeLog": true
    }
};
```
Describe the bug
`setValue` appends text to input (which is problem when there is already some text), nor `clearValue` doesn't clear that input

Steps to Reproduce

```
   const usernameInput = await driver.$('~username')
    await usernameInput.clearValue()
    await usernameInput.setValue('myusername')
```

Expected behavior
To clear the input field

**Comment by christian-bromann** [comment]
@cervebar thanks for raising the issue.

Unfortunately this isn't something we can fix in WebdriverIO as it appears to be an issue with Appium not executing the command correctly. I advise to raise the same PR there and provide Appium logs for the team to investigate, thanks!
