### ISSUE TITLE
[📖 Docs]: Unclear if you should await an element used with a WebdriverIO assertion

### ISSUE THREAD

**Issue by jeroenbern-ontoforce** [webdriverio/webdriverio#9875]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Unclear documentation

### Description of the improvement / report

When using WebdriverIO assertions with a selector, it is unclear if you should use the await keyword on the selector or not.

On this page: https://webdriver.io/docs/api/expect-webdriverio/#tohaveattributecontaining
The assertion example is:
```javascript
const myInput = await $('input')
await expect(myInput).toHaveAttributeContaining('class', 'form')
```
Notice the await keyword before the `$('input')` selector.

But in the 'From Sync to Async' documentation here: https://webdriver.io/docs/async-migration#webdriverio-assertions
The assertion example is:
```javascript
await expect($('input')).toHaveAttributeContaining('class', 'form')
```
Notice the `$('input')` selector has no await keyword.

It is unclear for me if we need to use the await keyword inside the expect, when using WebdriverIO assertions like `toBeDisplayed()` or `toHaveAttributeContaining()` , ...

Is this supposed to work as expected?
```javascript
const myInput = $('input')
await expect(myInput).toHaveAttributeContaining('class', 'form')
```
or just 
```javascript
await expect($('input')).toHaveAttributeContaining('class', 'form')
```

or is the 'From Sync to Async' documentation wrong?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Thanks for raising the issue.

Technically you don't need to use `await` in front of the `$` command at all because these calls can get chained and the element is resolved afterall.

Do you like to take a stab and fix the doc issue?

**Comment by christian-bromann** [comment]
I will go ahead and close this. Both suggested options are possible:

```js
const myInput = $('input')
await expect(myInput).toHaveAttributeContaining('class', 'form')
```
and
```js
await expect($('input')).toHaveAttributeContaining('class', 'form')
```

If you think the docs are unclear at a specific point, please let us know ideally with a PR. Thank you!
