### ISSUE TITLE
[💡 Feature]: Easily allow injection of environment variables for Component Testing

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#9881]
### Is your feature request related to a problem?

Some components need to use enviroment variables that need to be injected in the browser when using the browser runner.
These variables are going to often be shared with the frontend project under test and it's development environment.

Vite allows a way to do so with the `define` property in the vite config.

https://vitejs.dev/config/#using-environment-variables-in-config

However, the `preset` and `viteConfig` WDIO configuration properties are mutually exclusive.

### Describe the solution you'd like.

A documented way to inject environment variables in to the browser runner so that components can use it.

One way would be to be able to define a WDIO configuration with both `viteConfig` and `preset` properties.

```js 

//wdio.conf.ts

// Imported with Node, not at test time
import * as dotenv from 'dotenv'

// Use an already defined .env file that the App Under Test also uses
const myEnvs = dotenv.config()

export const config: WebdriverIO.Config = {
    preset: 'react',
    viteConfig: {
        define: myEnvs, // Built however users want, process.env, dotenv, etc
    }
}
```
or
```js
export const config: WebdriverIO.Config = {
    preset: 'react',
    viteConfig: defineConfig(({ command, mode }) => {
      return {
        define: myEnvs, // Built however users want, process.env, dotenv, etc
      }
    })
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
@nextlevelbeard does #9880 solve this?

**Comment by nextlevelbeard** [comment]
Not quite, seeing weird behavior where an error is throw evaluating the string value of an environment key.
```js
  preset: 'react',
  viteConfig: {
    define: { 
      FOO: "BAR"
    },
  },
```
leads to 
```
 Error:  Test failed due to following error(s):
  - env.mjs: Uncaught ReferenceError: BAR is not defined
    at http://localhost:50275/node_modules/vite/dist/client/env.mjs:16:26
```

**Comment by christian-bromann** [comment]
Please see https://vitejs.dev/config/shared-options.html#define

> String values will be used as raw expressions, so if defining a string constant, it needs to be explicitly quoted (e.g. with JSON.stringify).

So you have to define it as following:
```ts
  preset: 'react',
  viteConfig: {
    define: { 
      FOO: "'BAR'"
    },
  },
```
