### ISSUE TITLE
Returning an array of promises built with Bluebird throws an error

### ISSUE THREAD

**Issue by mrotaru** [webdriverio/webdriverio#989]
Here's an example:
```
it("should foo", function() {
  client
    .url("www.example.com")
    .then(function() {
      return Promise.all([
        client.isExisting(".foo").then(function(existing){
          expect(existing).to.equal(true);        
        })
      ]);    
    });
});
```
From what I've read so far, `webdriverio` should work with other promise libraries, such as Bluebird ? I searched through the issues and docs but could not find a lot of info on using promises. The error thrown is:
```
Unhandled rejection TypeError: promise.inspect is not a function
    at WebdriverjsAngular.resolvePromise (C:\code\foo\node_modules\webdriverjs-angular\node_modules\webdriverio\lib\utils\PromiseHandler.js:50:34)
```
("webdriverio": "^3.4.0", node v5.1.0)

**Comment by mrotaru** [comment]
So it looks like the webdriver package used is actually the one which comes with `[webdriverjs-angular](https://github.com/webdriverio/webdriverjs-angular)`, which isn't yet updated to use v3 of `webdriverio`. Once that is done, this should work.

Is it possible to build and return an array of promises with webdirver 2 / webdriverjs-angular ?

**Comment by christian-bromann** [comment]
No it isn't. We probably will drop the support for that package and introduce an angular service or plugin that will be compatible with v4. I would recommend to switch to v3 and add a waitforexist (to wait for an element that pops up when the app has loaded) after each `url` command call.
