### ISSUE TITLE
USB error while trying to send text to prompt box

### ISSUE THREAD

**Issue by PrLu** [webdriverio/webdriverio#9913]
not sure what's the cause, but whiel trying to send text to prompt box, it is throwing **"USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)"** .
But while trying to accept and dismiss the alert, it's working.
**URL:** https://demo.automationtesting.in/Alerts.html
**Code written :** 
**Note: first two test case is working, 3rd one is not working.**
describe.only('test suit 1',()=>{
    beforeEach(()=>{
         browser.url('https://demo.automationtesting.in/Alerts.html')
    })
    it('test case 1',async ()=>{
        await $('body > div.container.center > div > div > div > div.tabpane.pullleft > ul > li.active > a').click();
        await $('#OKTab > button').click();
        await browser.pause(3000);
        const isAlertOpen = await browser.isAlertOpen();
        if(!isAlertOpen){
            const alertText = await browser.getAlertText(); //get the alert text
            console.log("The alert text is: ",alertText) //logs the text to 
            await browser.pause(3000);
            await browser.acceptAlert();
            await browser.pause(3000);
        }
        
    })
    it('test case 2',async ()=>{
        await $('body > div.container.center > div > div > div > div.tabpane.pullleft > ul > li:nth-child(2) > a').click();
        await $('#CancelTab > button').click();
        await browser.pause(3000);
        const isAlertOpenAccept = await browser.isAlertOpen();
        if(!isAlertOpenAccept){
            const confirmMessage = await browser.getAlertText(); //returns the confirm box text
            console.log('The confirm message is: ', confirmMessage) 
            await browser.dismissAlert();
        }
        await $('#CancelTab > button').click();
        await browser.pause(3000);
        const isAlertOpenDismiss = await browser.isAlertOpen();
        if(!isAlertOpenDismiss){
            const confirmMessage = await browser.getAlertText(); //returns the confirm box text
            console.log('The confirm message is: ', confirmMessage) 
            await browser.acceptAlert();
        }
    })
    it.only('test case 3', async()=>{
        await $('body > div.container.center > div > div > div > div.tabpane.pullleft > ul > li:nth-child(3) > a').click()
        await $('#Textbox > button').click()
        await browser.pause(4000);
        let isAlertOpen = await browser.isAlertOpen();
        if (!isAlertOpen){
            await browser.pause(3000);
            console.log('going to send text')
            await browser.sendAlertText("It's testing time."); // types the text BrowserStack
            await browser.pause(3000);
            const promptboxText = await browser.getAlertText();//returns the text of prompt box
            console.log('The prompt box text is: ', promptboxText); //logs the text
            await browser.acceptAlert(); //accepts the prompt box
            //await browser.dismissAlert();
        }
    })
})

**WDIO Logs:**
T:\Autoamtion Lethal\webdriverio\automationCorner\project1>npm run wdio

> wdio
> wdio run ./wdio.conf.js

Execution of 1 workers started at 2023-03-07T16:34:09.959Z

2023-03-07T16:34:10.016Z INFO chromedriver: Initiate Chromedriver Launcher (v8.1.1)
2023-03-07T16:34:10.017Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-03-07T16:34:10.019Z INFO chromedriver: Start Chromedriver (T:\Autoamtion Lethal\webdriverio\automationCorner\project1\node_modules\chromedriver\lib\chromedriver\chromedriver.exe) with args --port=9515 --url-base=/
2023-03-07T16:34:10.037Z INFO chromedriver: Starting ChromeDriver 110.0.5481.77 (65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}) on port 9515
2023-03-07T16:34:10.038Z INFO chromedriver: Only local connections are allowed.
2023-03-07T16:34:10.038Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
2023-03-07T16:34:10.048Z INFO chromedriver: ChromeDriver was started successfully.
2023-03-07T16:34:10.136Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-03-07T16:34:10.137Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.conf.js
[0-0] 2023-03-07T16:34:10.752Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - file:///T:/Autoamtion%20Lethal/webdriverio/automationCorner/project1/test/specs/example.e2e.js
[0-0] 2023-03-07T16:34:10.876Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2023-03-07T16:34:10.940Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2023-03-07T16:34:10.940Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
[0-0] }

DevTools listening on ws://127.0.0.1:55509/devtools/browser/5ece3e07-83d2-414e-89b0-2f6705681337
2023-03-07T16:34:11.402Z WARN chromedriver: [1678206851.402][WARNING]: virtual void DevToolsClientImpl::AddListener(DevToolsEventListener *) subscribing a listener to the already connected DevToolsClient. Connection notification will not arrive.
[0-0] 2023-03-07T16:34:11.418Z INFO webdriver: COMMAND navigateTo("https://demo.automationtesting.in/Alerts.html")
[0-0] 2023-03-07T16:34:11.420Z INFO webdriver: COMMAND findElement("css selector", "body > div.container.center > div > div > div > div.tabpane.pullleft > ul > li:nth-child(3) > a")
[0-0] 2023-03-07T16:34:11.420Z INFO webdriver: [POST] http://localhost:9515/session/9fcb8f3e64395c2cd7bc867b3dd57cd3/url
[0-0] 2023-03-07T16:34:11.420Z INFO webdriver: DATA { url: 'https://demo.automationtesting.in/Alerts.html' }
[0-0] 2023-03-07T16:34:11.421Z INFO webdriver: [POST] http://localhost:9515/session/9fcb8f3e64395c2cd7bc867b3dd57cd3/element
[0-0] 2023-03-07T16:34:11.422Z INFO webdriver: DATA {
[0-0]   using: 'css selector',
[0-0]   value: 'body > div.container.center > div > div > div > div.tabpane.pullleft > ul > li:nth-child(3) > a'
[0-0] }
[0-0] 2023-03-07T16:34:15.720Z INFO webdriver: RESULT null
[0-0] 2023-03-07T16:34:15.738Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': 'd588e1cb-61c5-4326-b32c-cebd23752a23'
[0-0] }
[0-0] 2023-03-07T16:34:15.742Z INFO webdriver: COMMAND elementClick("d588e1cb-61c5-4326-b32c-cebd23752a23")
[0-0] 2023-03-07T16:34:15.743Z INFO webdriver: [POST] http://localhost:9515/session/9fcb8f3e64395c2cd7bc867b3dd57cd3/element/d588e1cb-61c5-4326-b32c-cebd23752a23/click
[0-0] 2023-03-07T16:34:15.768Z INFO webdriver: RESULT null
[0-0] 2023-03-07T16:34:15.768Z INFO webdriver: COMMAND findElement("css selector", "#Textbox > button")
[0-0] 2023-03-07T16:34:15.768Z INFO webdriver: [POST] http://localhost:9515/session/9fcb8f3e64395c2cd7bc867b3dd57cd3/element
[0-0] 2023-03-07T16:34:15.769Z INFO webdriver: DATA { using: 'css selector', value: '#Textbox > button' }
[0-0] 2023-03-07T16:34:15.776Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '0e6e1db1-73d3-4bfa-b92e-ef64366801d0'
[0-0] }
[0-0] 2023-03-07T16:34:15.778Z INFO webdriver: COMMAND elementClick("0e6e1db1-73d3-4bfa-b92e-ef64366801d0")
[0-0] 2023-03-07T16:34:15.778Z INFO webdriver: [POST] http://localhost:9515/session/9fcb8f3e64395c2cd7bc867b3dd57cd3/element/0e6e1db1-73d3-4bfa-b92e-ef64366801d0/click
[0-0] 2023-03-07T16:34:15.800Z INFO webdriver: RESULT null
[7008:36436:0307/220416.727:ERROR:device_event_log_impl.cc(218)] [22:04:16.727] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[7008:36436:0307/220416.728:ERROR:device_event_log_impl.cc(218)] [22:04:16.728] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[7008:36436:0307/220416.728:ERROR:device_event_log_impl.cc(218)] [22:04:16.728] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[0-0] 2023-03-07T16:34:19.804Z INFO webdriver: COMMAND isAlertOpen()
[0-0] 2023-03-07T16:34:19.804Z INFO webdriver: [GET] http://localhost:9515/session/9fcb8f3e64395c2cd7bc867b3dd57cd3/alert
[0-0] 2023-03-07T16:34:19.807Z INFO webdriver: RESULT true
[0-0] 2023-03-07T16:34:19.809Z INFO webdriver: COMMAND deleteSession()
[0-0] 2023-03-07T16:34:19.809Z INFO webdriver: [DELETE] http://localhost:9515/session/9fcb8f3e64395c2cd7bc867b3dd57cd3
[0-0] 2023-03-07T16:34:19.994Z INFO webdriver: RESULT null
[0-0] PASSED in chrome - file:///T:/Autoamtion%20Lethal/webdriverio/automationCorner/project1/test/specs/example.e2e.js
2023-03-07T16:34:20.111Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-03-07T16:34:20.112Z INFO @wdio/cli:launcher: Run onComplete hook

 "spec" Reporter:
------------------------------------------------------------------
[chrome 110.0.5481.178 windows #0-0] Running: chrome (v110.0.5481.178) on windows
[chrome 110.0.5481.178 windows #0-0] Session ID: 9fcb8f3e64395c2cd7bc867b3dd57cd3
[chrome 110.0.5481.178 windows #0-0]
[chrome 110.0.5481.178 windows #0-0] » \test\specs\example.e2e.js
[chrome 110.0.5481.178 windows #0-0] test suit 1
[chrome 110.0.5481.178 windows #0-0]    ✓ test case 3
[chrome 110.0.5481.178 windows #0-0]
[chrome 110.0.5481.178 windows #0-0] 1 passing (8.5s)

Spec Files:      1 passed, 1 total (100% completed) in 00:00:10

2023-03-07T16:34:20.113Z INFO @wdio/local-runner: Shutting down spawned worker
2023-03-07T16:34:20.368Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-03-07T16:34:20.368Z INFO @wdio/local-runner: shutting down

**package,json:**
{
  "dependencies": {
    "wdio": "^6.0.1"
  },
  "devDependencies": {
    "@wdio/cli": "^8.5.6",
    "@wdio/local-runner": "^8.5.6",
    "@wdio/mocha-framework": "^8.5.6",
    "@wdio/spec-reporter": "^8.4.0",
    "chromedriver": "^110.0.0",
    "wdio-chromedriver-service": "^8.1.1"
  },
  "scripts": {
    "wdio": "wdio run ./wdio.conf.js"
  }
}

**wdio.conf.js**
exports.config = {
    //
    // ====================
    // Runner Configuration
    // ====================
    // WebdriverIO supports running e2e tests as well as unit and component tests.
    runner: 'local',
    
    //
    // ==================
    // Specify Test Files
    // ==================
    // Define which test specs should run. The pattern is relative to the directory
    // of the configuration file being run.
    //
    // The specs are defined as an array of spec files (optionally using wildcards
    // that will be expanded). The test for each spec file will be run in a separate
    // worker process. In order to have a group of spec files run in the same worker
    // process simply enclose them in an array within the specs array.
    //
    // If you are calling `wdio` from an NPM script (see https://docs.npmjs.com/cli/run-script),
    // then the current working directory is where your `package.json` resides, so `wdio`
    // will be called from there.
    //
    specs: [
        './test/specs/**/*.js'
    ],
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    //
    // ============
    // Capabilities
    // ============
    // Define your capabilities here. WebdriverIO can run multiple capabilities at the same
    // time. Depending on the number of capabilities, WebdriverIO launches several test
    // sessions. Within your capabilities you can overwrite the spec and exclude options in
    // order to group specific specs to a specific capability.
    //
    // First, you can define how many instances should be started at the same time. Let's
    // say you have 3 different capabilities (Chrome, Firefox, and Safari) and you have
    // set maxInstances to 1; wdio will spawn 3 processes. Therefore, if you have 10 spec
    // files and you set maxInstances to 10, all spec files will get tested at the same time
    // and 30 processes will get spawned. The property handles how many capabilities
    // from the same test should run tests.
    //
    maxInstances: 10,
    //
    // If you have trouble getting all important capabilities together, check out the
    // Sauce Labs platform configurator - a great tool to configure your capabilities:
    // https://saucelabs.com/platform/platform-configurator
    //
    capabilities: [{
    
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        maxInstances: 5,
        //
        browserName: 'chrome',
        acceptInsecureCerts: true
        // If outputDir is provided WebdriverIO can capture driver session logs
        // it is possible to configure which logTypes to include/exclude.
        // excludeDriverLogs: ['*'], // pass '*' to exclude all driver session logs
        // excludeDriverLogs: ['bugreport', 'server'],
    }],
    //
    // ===================
    // Test Configurations
    // ===================
    // Define all options that are relevant for the WebdriverIO instance here
    //
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    logLevel: 'info',
    //
    // Set specific log levels per logger
    // loggers:
    // - webdriver, webdriverio
    // - @wdio/browserstack-service, @wdio/devtools-service, @wdio/sauce-service
    // - @wdio/mocha-framework, @wdio/jasmine-framework
    // - @wdio/local-runner
    // - @wdio/sumologic-reporter
    // - @wdio/cli, @wdio/config, @wdio/utils
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    // logLevels: {
    //     webdriver: 'info',
    //     '@wdio/appium-service': 'info'
    // },
    //
    // If you only want to run your tests until a specific amount of tests have failed use
    // bail (default is 0 - don't bail, run all tests).
    bail: 0,
    //
    // Set a base URL in order to shorten url command calls. If your `url` parameter starts
    // with `/`, the base url gets prepended, not including the path portion of your baseUrl.
    // If your `url` parameter starts without a scheme or `/` (like `some/path`), the base url
    // gets prepended directly.
    baseUrl: 'http://localhost',
    //
    // Default timeout for all waitFor* commands.
    waitforTimeout: 10000,
    //
    // Default timeout in milliseconds for request
    // if browser driver or grid doesn't send response
    connectionRetryTimeout: 120000,
    //
    // Default request retries count
    connectionRetryCount: 3,
    //
    // Test runner services
    // Services take over a specific job you don't want to take care of. They enhance
    // your test setup with almost no effort. Unlike plugins, they don't add new
    // commands. Instead, they hook themselves up into the test process.
    services: ['chromedriver'],
    //automationProtocol: 'devtools',
    // Framework you want to run your specs with.
    // The following are supported: Mocha, Jasmine, and Cucumber
    // see also: https://webdriver.io/docs/frameworks
    //
    // Make sure you have the wdio adapter package for the specific framework installed
    // before running any tests.
    framework: 'mocha',
    //
    // The number of times to retry the entire specfile when it fails as a whole
    // specFileRetries: 1,
    //
    // Delay in seconds between the spec file retry attempts
    // specFileRetriesDelay: 0,
    //
    // Whether or not retried specfiles should be retried immediately or deferred to the end of the queue
    // specFileRetriesDeferred: false,
    //
    // Test reporter for stdout.
    // The only one supported by default is 'dot'
    // see also: https://webdriver.io/docs/dot-reporter
    reporters: ['spec'],

    
    //
    // Options to be passed to Mocha.
    // See the full list at http://mochajs.org/
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },
    //
    // =====
    // Hooks
    // =====
    // WebdriverIO provides several hooks you can use to interfere with the test process in order to enhance
    // it and to build services around it. You can either apply a single function or an array of
    // methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
    // resolved to continue.
    /**
     * Gets executed once before all workers get launched.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     */
    // onPrepare: function (config, capabilities) {
    // },
    /**
     * Gets executed before a worker process is spawned and can be used to initialise specific service
     * for that worker as well as modify runtime environments in an async fashion.
     * @param  {String} cid      capability id (e.g 0-0)
     * @param  {[type]} caps     object containing capabilities for session that will be spawn in the worker
     * @param  {[type]} specs    specs to be run in the worker process
     * @param  {[type]} args     object that will be merged with the main configuration once worker is initialized
     * @param  {[type]} execArgv list of string arguments passed to the worker process
     */
    // onWorkerStart: function (cid, caps, specs, args, execArgv) {
    // },
    /**
     * Gets executed just after a worker process has exited.
     * @param  {String} cid      capability id (e.g 0-0)
     * @param  {Number} exitCode 0 - success, 1 - fail
     * @param  {[type]} specs    specs to be run in the worker process
     * @param  {Number} retries  number of retries used
     */
    // onWorkerEnd: function (cid, exitCode, specs, retries) {
    // },
    /**
     * Gets executed just before initialising the webdriver session and test framework. It allows you
     * to manipulate configurations depending on the capability or spec.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     * @param {String} cid worker id (e.g. 0-0)
     */
    // beforeSession: function (config, capabilities, specs, cid) {
    // },
    /**
     * Gets executed before test execution begins. At this point you can access to all global
     * variables like `browser`. It is the perfect place to define custom commands.
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs        List of spec file paths that are to be run
     * @param {Object}         browser      instance of created browser/device session
     */
    // before: function (capabilities, specs) {
    // },
    /**
     * Runs before a WebdriverIO command gets executed.
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     */
    // beforeCommand: function (commandName, args) {
    // },
    /**
     * Hook that gets executed before the suite starts
     * @param {Object} suite suite details
     */
    // beforeSuite: function (suite) {
    // },
    /**
     * Function to be executed before a test (in Mocha/Jasmine) starts.
     */
    // beforeTest: function (test, context) {
    // },
    /**
     * Hook that gets executed _before_ a hook within the suite starts (e.g. runs before calling
     * beforeEach in Mocha)
     */
    // beforeHook: function (test, context) {
    // },
    /**
     * Hook that gets executed _after_ a hook within the suite starts (e.g. runs after calling
     * afterEach in Mocha)
     */
    // afterHook: function (test, context, { error, result, duration, passed, retries }) {
    // },
    /**
     * Function to be executed after a test (in Mocha/Jasmine only)
     * @param {Object}  test             test object
     * @param {Object}  context          scope object the test was executed with
     * @param {Error}   result.error     error object in case the test fails, otherwise `undefined`
     * @param {Any}     result.result    return object of test function
     * @param {Number}  result.duration  duration of test
     * @param {Boolean} result.passed    true if test has passed, otherwise false
     * @param {Object}  result.retries   informations to spec related retries, e.g. `{ attempts: 0, limit: 0 }`
     */
    // afterTest: function(test, context, { error, result, duration, passed, retries }) {
    // },

    /**
     * Hook that gets executed after the suite has ended
     * @param {Object} suite suite details
     */
    // afterSuite: function (suite) {
    // },
    /**
     * Runs after a WebdriverIO command gets executed
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     * @param {Number} result 0 - command success, 1 - command error
     * @param {Object} error error object if any
     */
    // afterCommand: function (commandName, args, result, error) {
    // },
    /**
     * Gets executed after all tests are done. You still have access to all global variables from
     * the test.
     * @param {Number} result 0 - test pass, 1 - test fail
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // after: function (result, capabilities, specs) {
    // },
    /**
     * Gets executed right after terminating the webdriver session.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // afterSession: function (config, capabilities, specs) {
    // },
    /**
     * Gets executed after all workers got shut down and the process is about to exit. An error
     * thrown in the onComplete hook will result in the test run failing.
     * @param {Object} exitCode 0 - success, 1 - fail
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {<Object>} results object containing test results
     */
    // onComplete: function(exitCode, config, capabilities, results) {
    // },
    /**
    * Gets executed when a refresh happens.
    * @param {String} oldSessionId session ID of the old session
    * @param {String} newSessionId session ID of the new session
    */
    // onReload: function(oldSessionId, newSessionId) {
    // }
}

**Comment by christian-bromann** [comment]
Please see https://stackoverflow.com/questions/64927909/failed-to-read-descriptor-from-node-connection-a-device-attached-to-the-system, this error message can be ignored and is not from WebdriverIO but from Chromedriver.
