### ISSUE TITLE
[🐛 Bug]: config location is used as rootDir after updating to version 8

### ISSUE THREAD

**Issue by nnaydenow** [webdriverio/webdriverio#9920]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v8.4.0

### Node.js Version

v16.14.2

### Mode

WDIO Testrunner

### What happened?

Our project has folder which contains all configuration files including `wdio.conf.js`.
```
 - package
    - config
        - wdio.conf.js
    - package.json
```
After upgrading from v7.19.7 to 8.4.0 configuration is not working correctly.
If we run the command `npx wdio wdio.conf.js` error for no specs appears. After quite debugging I found that the wdio assumes the root folder is where the config is stored (package/config), not where the command is ran. https://github.com/webdriverio/webdriverio/blob/e613208bb6c514612d0ba4e9e3e3f15665fc87a0/packages/wdio-config/src/lib/ConfigParser.ts#L55-L58

### What is your expected behavior?

rootDir to be the location where wdio was used, not where its configuration is stored.

### How to reproduce the bug.

Move the config file in nested folder and use its relative path to be loaded.

- npx wdio config/wdio.conf.js

### Relevant log output

```typescript
Execution of 0 workers started at 2023-03-09T12:31:31.185Z

2023-03-09T12:31:32.589Z ERROR @wdio/cli:launcher: No specs found to run, exiting with failure

Spec Files:      0 passed, 0 total (0% completed) in 00:00:01
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by Acksakal** [comment]
"scripts": {
    "wdio": "wdio run ./src/wdio.conf.js"
  }
Above does not work. I guess, you just have to have your wdio config file in the project root folder. Otherwise, you'll keep getting the following error:
'Could not execute "run" due to missing configuration, file "wdio[.js/.ts]" not found! Would you like to create one? (y/N)'

At least, that was my experience. I am a rookie in this, if somebody knows how to fix, pls. let me know.
