### ISSUE TITLE
[🐛 Bug]: Misleading documentation towards way of acessing custom properties of configuration

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#9921]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

18

### Mode

WDIO Testrunner

### What happened?

In v8 `browser.options` was "replaced" with `browser.config` but it no longer carries the custom configuration properties that users added to their config.

The types still mention that `browser.config` is usable and the proper way to access custom configurations.
```ts
    /**
     * Applied WebdriverIO options (options that aren't officially part of WebdriverIO are stripped
     * out of this object).
     */
    options: Options.WebdriverIO | Options.Testrunner;
    /**
     * Given WebdriverIO options (including custom configurations)
     */
    config: Options.WebdriverIO | Options.Testrunner;
```

### What is your expected behavior?

Be able to access custom configuration in some way.

### How to reproduce the bug.

In a WDIO configuration file:
```ts
export const config: Partial<WebdriverIO.Config> = {
  myCustomKey: "myCustomValue"
}
```

In a test (i.e. Cucumber)
```ts
const { myCustomKey } = browser.config
//or
const { myCustomKey } = browser.options
```

### Relevant log output

```typescript
N\A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@nextlevelbeard thanks for raising the issue. We moved away allowing to store custom configurations within `wdio.cong.js` files. We don't believe it is the right place to store this data. There are various of other ways to do this. I pushed a commit to remove the property from types.
