### ISSUE TITLE
[🐛 Bug]: ChromeOptions 'prefs' should not be limited to strings

### ISSUE THREAD

**Issue by nmattia** [webdriverio/webdriverio#9924]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.25.1

### Node.js Version

16.15.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
    capabilities: {
        browserName: "chrome",
        "goog:chromeOptions": {
            args: [
                "--ignore-certificate-errors", // allow self-signed certificates
                "--disable-gpu",
            ],

            // Disables permission prompt for clipboard, needed for tests using the clipboard
            prefs: {
                'profile.content_settings.exceptions.clipboard': ({
                    '*': {'last_modified': Date.now(), 'setting':1},
                } as any)
            }
        },
    },
}
```

### What happened?

The `as any` cast is needed, because the `prefs` otherwise excpet `string | number | boolean` as values.

### What is your expected behavior?

The `as any` cast should not be necessary.

### How to reproduce the bug.

To reproduce the bug, try to typecheck any wdio config with the following capabilities:

```ts

{
    capabilities: {
        browserName: "chrome",
        "goog:chromeOptions": {
            args: [
                "--ignore-certificate-errors", // allow self-signed certificates
                "--disable-gpu",
            ],

            // Disables permission prompt for clipboard, needed for tests using the clipboard
            prefs: {
                'profile.content_settings.exceptions.clipboard': {
                    '*': {'last_modified': Date.now(), 'setting':1},
                }
            }
        },
    },
}
```

### Relevant log output

```typescript
src/frontend/src/test-e2e/util.ts:42:9 - error TS2322: Type '{ '*': { last_modified: number; setti
ng: number; }; }' is not assignable to type 'string | number | boolean'.

    42         'profile.content_settings.exceptions.clipboard': ({
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
The `prefs` needs to be serialised in a WebDriver request so we can only accept `string | number | boolean`. You can get rid of the `any` cast by doing:

```ts
        'goog:chromeOptions': {
            prefs: {
                'profile.content_settings.exceptions.clipboard': JSON.stringify({
                    '*': {'last_modified': Date.now(), 'setting':1},
                })
            }
        }
```

Would that work? Open this up to something like `any` would not improve ambiguity. Ideally it would be nice if there is documentation on what prefs are available.

**Comment by christian-bromann** [comment]
I will go ahead and close the issue. If anyone has documentation on Chrome prefs

**Comment by christian-bromann** [comment]
I updated the type to accept JSON objects. I realised that this is part of the request payload and Chromedriver takes care creating necessary files for it.

**Comment by nmattia** [comment]
Sorry for dropping the ball! This sounds like a great solution, thanks @christian-bromann !
