### ISSUE TITLE
[💡 Feature]: Proposal: Allow running the same sped file multiple times in parallel 

### ISSUE THREAD

**Issue by WillBrock** [webdriverio/webdriverio#9926]
### Is your feature request related to a problem?

I'd like to be able to run the same test multiple times in parallel. The reason for this is to prevent flaky tests from getting introduced into the code. The way that I would use it is that when a new branch gets submitted it will run through all the regular tests like normal but will then detect if it's a new test being added and run that test again x number of times in parallel.  

### Describe the solution you'd like.

Two ways I could see doing this when running tests.

1) Add a --allow-duplicates argument which will then not filter out duplicate tests

```
npx wdio run ./wdio.conf.js --spec example.e2e.js example.e2e.js example.e2e.js --allow-duplicates
```

2) Add a --multi-run argument which will allow you to specify how many times you'd want each spec to run (not sure if multi-run is the best name) 

```
npx wdio run ./wdio.conf.js --spec example.e2e.js --multi-run=10
```

### Additional context

I will implement the change if this is something we can do.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
I tend towards solution two with the following constraint: the `--multi-run` parameter can only be applied when also one single `--spec` parameter is applied. The testrunner needs to know which spec file to run multiple times. Or we find a different way to define it.

**Comment by WillBrock** [comment]
I was kind of thinking it would run any test that is specified or matched multiple times. If someone passes a suite that contains 500 tests and the multi-run option is set it would run those, although I don't think someone would want to do that.

I could see in my case to pass multiple spec's. The reason for that is if we've disabled some tests and we are re-introducing them I would want to run each test that is being enable in the branch.

```
npx wdio run ./wdio.conf.js --spec foo.e2e.js bar.e2e.js baz.e2e.js --multi-run=10
```
Probably not something someone would do often but if they wanted they could pass the suite and multi-run. I would actually probably use the suite part in some instances. We run tests each night on fresh databaess to create data for our manual testers and right now I loop over tests to do that but I could use the mulit-run option to do that instead.
```
npx wdio run ./wdio.conf.js --suite FooBar --multi-run=3
```

**Comment by ArminazK** [comment]
hello, imho `--multi-run` could be confused with `multiremote` mode.
To me this sounds like project specific feature. So anyone can loop easily their tests in different ways on current wdio. 
Instead of creating this complex logic, better to focus removing flakiness in tests/framework.
Sorry for jumping in the thread. :/

**Comment by WillBrock** [comment]
> hello, imho `--multi-run` could be confused with `multiremote` mode.

I'm open to suggestions on a better name for this.

> Instead of creating this complex logic, better to focus removing flakiness in tests/framework.

The change in code for this is about 3 lines. The reason for this change is to prevent flakiness in tests/framework.

**Comment by ArminazK** [comment]
> I'm open to suggestions on a better name for this.

`--loop-times` or something like this.

> The change in code for this is about 3 lines. The reason for this change is to prevent flakiness in tests/framework.
It might add 3 lines of code, but it does not eliminate flakiness, to my mind this is more hiding than prevention.
As I said you can hunt down all the flakiness without adding this feature to wdio before event merging to your branch.
Why just not to trigger couple times a job for those fresh added tests?

**Comment by WillBrock** [comment]
> It might add 3 lines of code, but it does not eliminate flakiness, to my mind this is more hiding than prevention.
> As I said you can hunt down all the flakiness without adding this feature to wdio before even merging to your branch.
> Why just not to trigger couple times a job for those fresh added tests?

I think you're missing the point. It's not really feasible when you run hundreds of jobs a day with hundreds of thousands of tests in total. One job could run when there are 5 other jobs running or one job could run when no other jobs are running, when this happens there could be an increase load on the server which could cause a slight slowdown and the flaky test not get caught always until other factors are caught. This is just one example. You say we can hunt it down before it gets merged and that is exactly what this change is doing.

**Comment by christian-bromann** [comment]
> It might add 3 lines of code, but it does not eliminate flakiness

This feature is not about eliminating flakiness, it is more about detecting it.

I slightly agree with the name confusion but don't have a better name for it either, let's ensure we document this practice including the flag well so folks know what it is and suppose to do.

**Comment by christian-bromann** [comment]
Thanks @WillBrock for shipping the feature, closing
