### ISSUE TITLE
Config format

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#993]
#### Actual format

``` js
{
    framework: 'mocha',
    mochaOpts: { },

    reporter: 'spec',
    reporterOptions: { },

    services: ['sauce'],
    sauceConnect: true,
    sauceConnectOpts: { },

    plugins: { // inconsistent with other sections
        webdrivercss: { }
    }
}
```
#### Proposal (as a possible format)

``` js
{
    frameworks: {
        active: ['bdd'],

        options: {
            mocha: { }
        }
    },

    reporters: { // Mocha?
        active: ['spec'],

        options: {
            spec: { }
        }
    },

    services: {
        active: ['sauce'],

        options: {
            sauce: { }
        }
    },

    plugins: {
        active: ['webdrivercss'],

        options: {
            webdrivercss: { }
        }
    }
}
```

The last example is more bloated, but is more consistent and user-orientated. It is easy to use and navigate.

**Comment by georgecrawford** [comment]
Or even:
```
{
    frameworks: {
        mocha: {
            ui: 'bdd',
            timeout: 300000
        }
    },

    reporters: {
        spec: { }
    },

    services: {
        sauce: {
            connect: true,
        }
    },

    plugins: {
        webdrivercss: { }
    }
}
```
I agree that something like this would be a better pattern, and think that v4.0 is the perfect time to introduce it, so suggest it's done sooner rather than later. cc @christian-bromann

**Comment by christian-bromann** [comment]
I agree. I like @georgecrawford proposal better. What do you think @monolithed ?

**Comment by monolithed** [comment]
@christian-bromann, Actually, it was the first proposal I liked. If its use is obvious to anyone, of course yes!

**Comment by christian-bromann** [comment]
@vvo also suggested to set the cloud service in that way:

> Currently the guide advise people to just put they user and key no matter what the cloud service is without saying much more.

> So as a user here's how I felt: "I have a saucelabs account, so there must be somewhere I need to say type: saucelabs" But could not find such configuration entry, so after putting user and key (and removing the hub configuration, it worked. Thanks to our magical user and key detection of cloud services.

> But still I felt like "Uh?" because being magical in the configuration file do not help reduce the FUD, it raises it.

> I would prefer something like:

> wdio.conf.js

> ```js
{
  cloud: {
    service: 'saucelabs' // testingbot, browserstack,
    user:,
    key
  }
}
```
> What do you think?

**Comment by christian-bromann** [comment]
I would suggest a mixture of both:

```
{
    cloud: {
        service: 'saucelabs' // testingbot, browserstack,
        user: 'foobar',
        key: 'XXXXXXXX'
    },

    framework: {
        mocha: {
            ui: 'bdd',
            timeout: 300000
        }
    },

    reporters: {
        spec: { }
    },

    services: {
        sauce: {
            connect: true,
        }
    },

    plugins: {
        webdrivercss: { }
    }
}
```

**Comment by christian-bromann** [comment]
since cloud and framework can only contain one option the object should be different. I would even say framework should have this format:

```js
    framework: {
        name: "mocha",
        ui: 'bdd',
        timeout: 300000
    },
```

**Comment by monolithed** [comment]
Two identical sections with different format? I think it does not make a sense. 

> since cloud and framework can only contain one option the object should be different. 

1. It is inconsistency
2. What if I want to use `requirejs`?

```js
framework: {
        mocha: {
              ...
        },
        requirejs: {
              ...
        }
}
```

Why not?

**Comment by christian-bromann** [comment]
> Two identical sections with different format? I think it does not make a sense.

What do you mean?

> What if I want to use requirejs?

`requirejs` is not a valid test framework. With framework I mean the following things here: Mocha, Jasmine, Cucumber, QUnit. They all require framework adapter like [wdio-mocha-framework](https://github.com/webdriverio/wdio-mocha-framework)

**Comment by monolithed** [comment]
> What do you mean?

```
    cloud: {
        service: 'saucelabs' 
        user: 'foobar',
        key: 'XXXXXXXX'
    },

    services: {
        sauce: {
            connect: true,
        }
    },
```

Really, what sense does it make? What problem we want to solve?

> requirejs is not a valid test framework. 

I like experience Mocha + [RequreJS adapter](https://github.com/karma-runner/karma-requirejs) in Karma ))

**Comment by christian-bromann** [comment]
@monolithed 

> but I have an experience using Mocha and RequreJS adapter in Karma ))

Karma is unit test framework which might require this to load the app properly within the browser. WebdriverIO is an integration framework that requires a deployed app to test on

I gave the config structure another thought and came to the conclusion that the proposed structure adds nesting to the config file and adds kind of a complexity on its own, especially when you don't apply and configs you end up doing this:

```js
services: {
    serviceA: {},
    serviceB: {},
    ....
```
which looks ugly. I think I will skip this for time being as it can be implemented later anyway.

**Comment by vvo** [comment]
Please if something is a collection of services make it so it's array based.

"BAD":

(completely random example, not accurate)
```js
services: {
  saucelabs: {},
  testingbot: {}
}

frameworks: {
  mocha: {},
  jasmine: {}
}
```

"GOOD":

```js
services: [{name: 'testingbot', config: {}}];
frameworks: [{name: mocha, config: {}}]
```

Why is this important? Because anything that holds multiple values is always easier to iterate on and to programmatically build as an array.

As soon as you need to programmatically iterate or build a collection then an array of values is really straightforward.

Otherwise, I think both https://github.com/webdriverio/webdriverio/issues/993#issuecomment-172113461 and https://github.com/webdriverio/webdriverio/issues/993#issuecomment-172113075 are the way to go (service and framework wise)

**Comment by christian-bromann** [comment]
We decided on the following solution:
```js
config.export = {
  //
  reporters: [
    // without options:
    'dot',
    // with options:
    ['dot', { some opts }
  ]
}
```
