### ISSUE TITLE
AssertionError: expected { state: 'pending' }

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#994]
#### Ok

```js
yield browser
	.url('/user/login')
	.getTitle()
	.should.be.equal('')
```

#### Fail

```js
yield browser
	.url('/user/login')
	.getTitle()
	.should.equal('')
```

```
AssertionError: expected { state: 'pending' } to equal ''
```

#### Config:

```js
{
	before () {
		chai.should();
		chai.use(chaiAsPromised);
		chaiAsPromised.transferPromiseness = browser.transferPromiseness;
	}
}
```

http://chaijs.com/guide/styles/#should

**Comment by christian-bromann** [comment]
Why are confusing something here.

1. If you want to use yield (recommended) than you don't need that transferPromises package. Just do:
`(yield browser.url('/user/login').getTitle()).should.be.equal('')`

2. If you want to use chaiAsPromised than do it like this: https://github.com/webdriverio/webdriverio/blob/master/test/spec/functional/chaiPromises.js#L37-L43

Note that you have to use `...should.be`__eventually__`.equal(...)`

**Comment by monolithed** [comment]
Oh, thanks!
