### ISSUE TITLE
Use DOMContentLoaded event

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#995]
The `DOMContentLoaded` event is fired when the initial HTML document has been completely loaded and parsed, without waiting for stylesheets, images, and subframes to finish loading. 
A very different event - `load` - should be used only to detect a fully-loaded page.
No one wants to wait until all resources will be loaded.
Let me know please if it possible to use `DOMContentLoaded` instead of `load`

**Comment by christian-bromann** [comment]
You can't listen to these events via Selenium but it works internally in a way that it finishes the url command once all resources were loaded (or a specific timeout was reached).

**Comment by monolithed** [comment]
> You can't listen to these events via Selenium

I see what you mean.  

```js
browser
   .url(url) // document has been completely loaded and I see it, 
             // but the Selenium wants to wait until all resources will be loaded.
```

I have no experience with Selenium, but I guess there's a flag.

**Comment by monolithed** [comment]
@christian-bromann 

> For commands that cause a new document to load, the point at which the command returns is determined by the session’s page load strategy. A value of `normal` causes the command to return after the `load` event fires on the new page, a value of `eager` causes it to return after `DOMContentLoaded` fires, and a value of none causes it to return immediately.

http://www.w3.org/TR/webdriver/

I just discovered, that in [selenium 2.40](http://selenium.googlecode.com/git/java/CHANGELOG), the `pageLoading` strategy is already implemented.

```
Implemented pageLoadingStrategy capability in Firefox.
```

```java
partial interface WebDriver {
    const DOMString CONSERVATIVE = 'conservative';
    const DOMString NORMAL = 'normal';
    const DOMString EAGER = 'eager';
    const DOMString NONE = 'none';
};
```

Example:

```
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(CapabilityType.PAGE_LOAD_STRATEGY, "eager");

WebDriver driver = new FirefoxDriver(capabilities);
WebDriverWait wait = new WebDriverWait(driver, 10);

driver.get("http://exmple.com"); // Document has been completely loaded and I use it!
```

**Comment by christian-bromann** [comment]
translated into WebdriverIO it would be:

```js
var client = require('webdriverio').remote({
    desiredCapabilities: {
        browserName: 'firefox'
        pageLoadStrategy: 'eager'
    }
})
```
something around that.

**Comment by monolithed** [comment]
@christian-bromann, so, does it not implemented yet?

**Comment by christian-bromann** [comment]
well if it is implemented in Selenium it can be somehow propagated to the server. Unfortunately the Selenium website is lacking on information around that.

**Comment by monolithed** [comment]
It seems you should reopen the issue, because is a very serious question

**Comment by christian-bromann** [comment]
There is nothing I can do about it here. It's not a bug or a missing feature. It's only a lack of documentation on the Selenium site. I just checked the project on GitHub and my assumption was right. You can use `pageLoadStrategy` or `pageLoadingStrategy`. Check out https://github.com/SeleniumHQ/selenium/blob/ab1e647d0fc8fc39e6b00ae94321ab228b6728f2/javascript/firefox-driver/js/sessionstore.js#L172-L173. Apparently it is only working on Firefox as far as I can see. Not sure if Chromedriver supports this.

**Comment by monolithed** [comment]
Thanks!

**Comment by monolithed** [comment]
Nope, not yet
