### ISSUE TITLE
Improve `command` events

### ISSUE THREAD

**Issue by georgecrawford** [webdriverio/webdriverio#996]
I think we could improve the events emitted for commands. They're a bit confusing now.

We have: `runner:beforecommand` and `runner:aftercommand`, which fire before/after an outermost webdriverio command is run (i.e. not for the inner commands in a wrapped command chain, such as `waitFor...`). Then we have `runner:command` and `runner:result` which are the raw Selenium HTTP requests and responses. 

I see two problems
- the word `command` is overloaded to mean two very different things here. I'd prefer `request` and `response` for the Selenium HTTP traffic, to match common terminology.
- there's no event fired for every webdriverio command (i.e. at the stage that it's [added to the commandList](https://github.com/webdriverio/webdriverio/blob/v4.0/lib/webdriverio.js#L164)), which is a shame as it could really help greatly in debugging complex custom commands with many levels of wrapping. I think we should also fire an event here - we should probably call this one `command`, and the outer one `usercommand` or `parentcommand` or something.

**Comment by marcelas** [comment]
Having a way to hook to the before command on a screenshot call inside wdio-screenshot for instance would be really useful. This would allow me to correctly place the mouse where I need before the screenshot is taken and after the lib did the required window manipulation

**Comment by christian-bromann** [comment]
This issue became outdated. We only emit for command and result and don't have any runner events anymore.
