### ISSUE TITLE
[🐛 Bug]: browser.emulateDevice is not a function

### ISSUE THREAD

**Issue by carri747** [webdriverio/webdriverio#9984]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.30.2

### Node.js Version

18.15.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
browserName: 'chrome',
        'goog:chromeOptions': {
            args: [
                '--disable-infobars',
                '--no-sandbox',
                '--disable-gpu',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage',
                '--window-size=1920,1080',
                `--user-agent=${userAgent}`
            ],
            prefs: {
                ['profile.default_content_setting_values.images']: 2
            }
        }
```

### What happened?

Hi,
I've detected an issue using emulator device. This is the piece of code that it's failing suddenly few days ago the same code works fine and nothing has changed in package.json 

```
    let userAgent = userAgentValue === UserAgent.DEFAULT ? UserAgent.DEFAULT_VALUE : userAgentValue.toLowerCase();
    let windowSize = await browser.getWindowSize();
    await browser.emulateDevice({
        viewport: {
            width: windowSize.width,
            height: windowSize.height
        },
        userAgent: userAgent
    });
```

Partial Pacakage.json

@wdio/devtools-service": "7.30.2",
@wdio/selenium-standalone-service": "7.30.2",
"selenium-standalone": "8.3.0",
        "webdriverio": "7.30.2"

Chrome version 111

### How to reproduce the bug.

Use the  browser.emulateDevice directly 

### Relevant log output

```typescript
TypeError: browser.emulateDevice is not a function
    at C:\Dev\git\XXXX\AutomationTest\src\utils\helpers\web.ts:44:19
    at Generator.next (<anonymous>)
    at fulfilled (C:\Dev\git\XXXX\AutomationTest\src\utils\helpers\web.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

No more logs are shown
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@carri747 thanks for raising an issue. Do you have a minimal reproducible example for this bug?

**Comment by wklos** [comment]
Chromium issue - see https://github.com/chromium/chromium/commit/0154caeefc74530d5cb57ce71608beb1b77bca39

Adding `--remote-allow-origins=*` to goog:chromeOptions args fixes the problem.

**Comment by carri747** [comment]
Thanks very much 
@christian-bromann  for your interest 
@wklos your solution works perfectly 
Amazing community
